### ISSUE TITLE
French keyboard layout: cannot make a # character

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#41093]
- VSCode Version:
Version 1.20.0-insider
Commit 8697a5e4ec152832a2612929c87d56302dbb2e79
Date 2018-01-03T05:14:21.686Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows 10 x64

Steps to Reproduce:

1. press `alt-gr + 3` (3 on the top kb row), this is the standard way to print a `#` with a French keyboard

What happens:
The `split editor` action is executed and nothing is printed.

What should happen:
The `#` character should be printed and no split editor action should be executed

Reproduces without extensions: Yes

See included screenshot: that's with the visual keyboard, but the same thing happens when doing the same thing with a real keyboard:

![vscode_kb](https://user-images.githubusercontent.com/199648/34522596-a6fc0526-f093-11e7-8337-7bdb6a1cf098.gif)

**Comment by ghiscoding** [comment]
Just curious, but you might have an associated keyboard shortcut for that key (File --> Preferences --> Keyboard Shortcuts). I use French/English Canada keyboard and don't have any shortcut associated and I don't see this behavior, however you're probably on French France keyboard?

**Comment by warpdesign** [comment]
I have the default shortcut set in keyboard shortcuts, which is supposed to be `ctrl + *`:

![keyboard1](https://user-images.githubusercontent.com/199648/34557295-165b3ea4-f13a-11e7-8dba-522b59c5175d.png)

The weird thing is that when opening keybinbdings.json, I see this:

![keyboard2](https://user-images.githubusercontent.com/199648/34557303-20733536-f13a-11e7-9245-49f2dcd004c5.png)

Not sure what this `oem_5` is, nor what this little `!` means.

I didn't change anything related to keyboard shortcuts.

**Comment by warpdesign** [comment]
Btw, yes, I use `French France`.

**Comment by warpdesign** [comment]
More digging...  Running the `Developer: Inspect Key Mappings` returns this:

```
-----------------------------------------------------------------------------------------------------------------------------------------
|                         Digit3 |   "   |                         3 |                         " |                          3 |    NO   |
|                   Shift+Digit3 |   3   |                   Shift+3 |                   Shift+" |                    shift+3 |    NO   |
|                Ctrl+Alt+Digit3 |   #   |                Ctrl+Alt+3 |                Ctrl+Alt+" |                 ctrl+alt+3 |    NO   |
|          Ctrl+Shift+Alt+Digit3 |  ---  |          Ctrl+Shift+Alt+3 |          Ctrl+Shift+Alt+" |           ctrl+shift+alt+3 |    NO   |
-----------------------------------------------------------------------------------------------------------------------------------------
```

This is what's expected. However, pressing `ctrl+alt+3` again runs the split command, and does not print the `#` character.

**Comment by ghiscoding** [comment]
Do you have any keybinding set? 
You can open the keybinding from the Keyboard Shortcut window, just below the search input, there's a sentence saying
> For advanced customizations open and edit `keybinding.json`

You can click on the `keybinding.json` and see what binding you have associated. Apart from that, I wouldn't know what else to check.

**Comment by mlasson** [comment]
Hello, 

I have the same problem on my computer (with the same configuration) with "alt + 3". 

I have also a different behavior of "alt gr + 2": it moves the current tab on the second editor group.

But if I press "alt gr + 2 followed by space" (or "alt gr + 2 followed by 2"), then it outputs the desired "~" (which is the [normal behavior on a French keyboard](https://en.wikipedia.org/wiki/Tilde#Keyboards)). 

My programming language has a lot of ~ so my tabs keep moving around ! So I would love to know if there is a "hack" to get aroung the bug while it gets fixed. 

Note that there is no problem with "Alt Gr + 4", "Alt Gr + 5", ..., "Alt Gr + 0", "Alt Gr + )",  "Alt Gr + =, "Alt 
 Gr+ $" and "Alt Gr + e".

Thanks !

**Comment by Nevor** [comment]
Hello,

I have tracked down the problem to the new addition of `workbench.action.moveEditorTo<First/Second/Third>Group` action family and their associated shortcuts (`Ctrl+Alt+1/2/3`) c60114fd2d6a5cb86ebf3064863f61aeaff6a1d6. It has to be noted that `Ctrl+Alt` is equivalent to `AltGr` on some keyboards (like French or German ones) and is used to write some additional characters (#, ~, € for instance). Moreover, there does not seem to have any means of distinguishing `Ctrl+Alt` from `AltGr` in Javascript. Finally, Microsoft's Raymond Chen [advises of not using](https://blogs.msdn.microsoft.com/oldnewthing/20040329-00/?p=40003) any `Ctrl+Alt` keybindings because of these very problems.

So the fix would seem to use different shortcuts. I made a quick look to find other problematic default keybindings and there was only `Ctrl+Alt+up/down/enter/space` which are more or less harmless (no problem for `space/enter` and on my computer with an Intel based GPU,  `up/down` is already caught for rotating the screen).

**Comment by warpdesign** [comment]
@Nevor Good catch!
I guess `Ctrl+Alt+up/down` is a problem too then since users won't be able to use them without rotating their screen if they happen to have a Windows machine with Intel GPU.

**Comment by warpdesign** [comment]
For anyone with French/German keyboard layout having this issue, as a workaround, changing the `Move Editor into Second Group` and `Move Editor into Third Group` shortcuts which are assigned to `ctrl + alt + é` and `ctrl + alt + "` fixes the problem and allows to print `"` and `~` characters again.

**Comment by alexandrudima** [comment]
The usage of ctrl+alt+2, ctrl+alt+3, etc. by default on Windows was brought in with https://github.com/Microsoft/vscode/commit/c60114fd2d6a5cb86ebf3064863f61aeaff6a1d6 for https://github.com/Microsoft/vscode/pull/40635

I suggest we do not ship with any default keybindings bound to `ctrl+alt+` key that produces printable character, as it inhibits the production of various characters on various keyboard layouts.
