### ISSUE TITLE
Ubuntu repo maybe broken?

### ISSUE THREAD

**Issue by bl3chd0se** [Microsoft/vscode#41094]
When trying to configure the ubuntu repository with key provided here:
https://code.visualstudio.com/docs/setup/linux

The packages files seems different from the checksums provided
Expected filesize is 35343
Actual filesize in repo is 35578

```Err:3 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  File has unexpected size (35578 != 35343). Mirror sync in progress?
  Hashes of expected file:
   - Filesize:35343 [weak]
   - SHA512:c9496b6c369f633e2ae431bb758cf970671c191bd02264713ce864dc327475b9ca7cdddda7dee0a14a556dc65d6b59a8f79f16c47e178a6345c90878c99fa0c8
   - SHA256:fba8fa5d5d6d200e9b45febf5bb0e9fe0d9165202c2cbfe38c72d64a423cf4a3
   - SHA1:66776788449c7465ac8668f904c730310fd95e37 [weak]
   - MD5Sum:c87007bbbd77cb0d60fa69f5f83b6a7c [weak]
  Release file created at: Thu, 21 Dec 2017 18:21:42 +0000
Reading package lists... Done  
E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (35578 != 35343). Mirror sync in progress?
   Hashes of expected file:
    - Filesize:35343 [weak]
    - SHA512:c9496b6c369f633e2ae431bb758cf970671c191bd02264713ce864dc327475b9ca7cdddda7dee0a14a556dc65d6b59a8f79f16c47e178a6345c90878c99fa0c8
    - SHA256:fba8fa5d5d6d200e9b45febf5bb0e9fe0d9165202c2cbfe38c72d64a423cf4a3
    - SHA1:66776788449c7465ac8668f904c730310fd95e37 [weak]
    - MD5Sum:c87007bbbd77cb0d60fa69f5f83b6a7c [weak]
   Release file created at: Thu, 21 Dec 2017 18:21:42 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Add repository
2. Add keyfile
3. apt-get update

**Comment by alexaandru** [comment]
I have the same problem. My OS is: `Linux Mint 17.3 Rosa`.

**Comment by adrianharabula** [comment]
Same problem on ubuntu 16.04.3.

**Comment by Tyriar** [comment]
Thanks all for the report, we're investigating. In the meantime you can hopefully still pull the packages from the URLs and install manually via `dpkg -i <...>.deb`:

- Stable https://packages.microsoft.com/repos/vscode/pool/main/c/code/code_1.19.1-1513676564_amd64.deb
- Insiders https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.20.0-1514960103_amd64.deb

**Comment by natec425** [comment]
So you can `apt-get update`,  you might want to comment out the entry in `/etc/apt/sources.list.d/vscode.list`. Change `deb [arch=....` to `# deb [arch=......`. I don't know if there is a better way to do this, but it worked for me.

**Comment by AlexanderYukhanov** [comment]
Hello team, do you have any ETA on this issue? It affects (by braking apt update) one of use cases for our prod service.

**Comment by julian-klode** [comment]
Reason: The latest repository update only updated Release and Release.gpg, but InRelease is still from Dec 21st.

**Comment by IronGeek** [comment]
Actually, the `Release.gpg` is still not updated too...

![d3b77da0-3ac0-409e-ad3e-f0f26e07aa74](https://user-images.githubusercontent.com/1383932/34553367-a9b9fcf2-f159-11e7-9540-c077fda3bda1.png)

**Comment by jongreen-telensa** [comment]
I'm seeing the same thing, but with `(35649 > 35343)` instead, on Debian 9.3. Same SHA/MD5 sums.

**Comment by felpin** [comment]
Using Ubuntu 16.04 I get the error:
```bash
E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages  Writing more data than expected (228420 > 227140)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by KillWolfVlad** [comment]
Linux Mint 18.3 (based on Ubuntu 16.04) 64-bit

After installation `code_1.19.1-1513676564_amd64.deb` from [official site](https://code.visualstudio.com/docs/?dv=linux64_deb) I get the error when I try update system

`$ sudo apt update`

 ```
....
Reading package lists... Done
E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages  Writing more data than expected (227448 > 227140)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by dwaynebradley** [comment]
It appears that the "Release" file shown above in the post from @IronGeek is related to an insiders build for v1.20.0 and not the stable build of v1.19.1 from 12-21-2017.

Here is the v1.20.0 insiders build from https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/:

`code-insiders_1.20.0-1514873705_amd64.deb          03-Jan-2018 21:55            45834862`

Here is the v1.19.1 stable build from https://packages.microsoft.com/repos/vscode/pool/main/c/code/:

`code_1.19.1-1513676564_amd64.deb                   21-Dec-2017 18:21            45385688`

**Comment by KillWolfVlad** [comment]
Fixed, issue can be closed :tada:

![image](https://user-images.githubusercontent.com/18448635/34579680-d3c7bf28-f1ab-11e7-937e-b5942c173910.png)

**Comment by Tyriar** [comment]
Thanks for your patience everyone, the team is planning on putting together better monitoring to hopefully catch this sort of thing earlier

**Comment by taoqf** [comment]
```sh
E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  Writing more data than expected (38219 > 38059)
   Hashes of expected file:
    - Filesize:38059 [weak]
    - SHA512:d960bc2562e8e3914627b1f8a255d6e78506acac42c7c540d6ce09c4d20f0447edb9d2596b87bb64d1d59e4786a89f7c9f7711743d057d10041f95cf8a7f7dd1
    - SHA256:692a9d9348b76a7ab30c112a4e1f4e99a8ba99454ec1ed4a5c82d1afa45c43f7
    - SHA1:4dfaf756f7b30988ddacc77863a363ffd6f409a4 [weak]
    - MD5Sum:256db81b96e2ac1ef30d0d1c63545b85 [weak]
   Release file created at: Fri, 26 Jan 2018 18:29:25 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Neptunao** [comment]
`E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages  Writing more data than expected (246868 > 245766)`
Linux Mint 18.3

**Comment by lcofre** [comment]
E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (38219 != 38059). Mirror sync in progress?
   Hashes of expected file:
    - Filesize:38059 [weak]
    - SHA512:d960bc2562e8e3914627b1f8a255d6e78506acac42c7c540d6ce09c4d20f0447edb9d2596b87bb64d1d59e4786a89f7c9f7711743d057d10041f95cf8a7f7dd1
    - SHA256:692a9d9348b76a7ab30c112a4e1f4e99a8ba99454ec1ed4a5c82d1afa45c43f7
    - SHA1:4dfaf756f7b30988ddacc77863a363ffd6f409a4 [weak]
    - MD5Sum:256db81b96e2ac1ef30d0d1c63545b85 [weak]
   Release file created at: Fri, 26 Jan 2018 18:29:25 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

Ubuntu 17.10

Thanks very much for your work!

**Comment by danzone** [comment]
Err:12 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  File has unexpected size (38219 != 38059). Mirror sync in progress?
  Hashes of expected file:
   - Filesize:38059 [weak]
   - SHA512:d960bc2562e8e3914627b1f8a255d6e78506acac42c7c540d6ce09c4d20f0447edb9d2596b87bb64d1d59e4786a89f7c9f7711743d057d10041f95cf8a7f7dd1
   - SHA256:692a9d9348b76a7ab30c112a4e1f4e99a8ba99454ec1ed4a5c82d1afa45c43f7
   - SHA1:4dfaf756f7b30988ddacc77863a363ffd6f409a4 [weak]
   - MD5Sum:256db81b96e2ac1ef30d0d1c63545b85 [weak]
  Release file created at: Fri, 26 Jan 2018 18:29:25 +0000

 Ubuntu 17.10

Thanks a lot!

**Comment by Tyriar** [comment]
I'll try look into this asap, in the meantime you can pull the latest from the repo https://code.visualstudio.com/

**Comment by danzone** [comment]
I just tried to make an apt-get update, and now the issue is gone away.

**Comment by AlexanderYukhanov** [comment]
Just tried it on Ubuntu DSVM. Still broken

**Comment by mattayes** [comment]
```
Get:11 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [38.1 kB]                               
Err:11 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  File has unexpected size (38219 != 38059). Mirror sync in progress?
  Hashes of expected file:
   - Filesize:38059 [weak]
   - SHA512:d960bc2562e8e3914627b1f8a255d6e78506acac42c7c540d6ce09c4d20f0447edb9d2596b87bb64d1d59e4786a89f7c9f7711743d057d10041f95cf8a7f7dd1
   - SHA256:692a9d9348b76a7ab30c112a4e1f4e99a8ba99454ec1ed4a5c82d1afa45c43f7
   - SHA1:4dfaf756f7b30988ddacc77863a363ffd6f409a4 [weak]
   - MD5Sum:256db81b96e2ac1ef30d0d1c63545b85 [weak]
  Release file created at: Fri, 26 Jan 2018 18:29:25 +0000

...

E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (38219 != 38059). Mirror sync in progress?
   Hashes of expected file:
    - Filesize:38059 [weak]
    - SHA512:d960bc2562e8e3914627b1f8a255d6e78506acac42c7c540d6ce09c4d20f0447edb9d2596b87bb64d1d59e4786a89f7c9f7711743d057d10041f95cf8a7f7dd1
    - SHA256:692a9d9348b76a7ab30c112a4e1f4e99a8ba99454ec1ed4a5c82d1afa45c43f7
    - SHA1:4dfaf756f7b30988ddacc77863a363ffd6f409a4 [weak]
    - MD5Sum:256db81b96e2ac1ef30d0d1c63545b85 [weak]
   Release file created at: Fri, 26 Jan 2018 18:29:25 +0000
```

Ubuntu 17.10

Thanks for your help!

**Comment by mattayes** [comment]
Tried again, was successfully able to update.

**Comment by Tyriar** [comment]
I just deleted the 1.19.3 package, so you should be able to update to 1.19.**2**. I'll try republishing 1.19.3 now

**Comment by Tyriar** [comment]
The new one seems to work, thanks for the report all.

**Comment by RomkeVdMeulen** [comment]
```
Err:15 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  Writing more data than expected (284174 > 281970)
```

**Comment by EstherAF** [comment]
It's happening again:

```
Err:13 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages
E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages  Writing more data than expected (284174 > 281970)
```

On Ubuntu 16.04

**Comment by Gargravarr2112** [comment]
Yep, happening again for me on Ubuntu 16.04 fresh install (breaking my automatic imaging :smile:  )

**Comment by MannikJ** [comment]
Also seeing it in Linux Mint 18.3

**Comment by CapturedMomentum** [comment]
Err:9 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  Writing more data than expected (283444 > 281970)
E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages  Writing more data than expected (283444 > 281970)

Ubuntu 16.04.1

**Comment by k4mui** [comment]
E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages  Writing more data than expected (284174 > 281970)

Ubuntu 16.04.4

**Comment by Nazg-Gul** [comment]
This isn't distro-related. Most likely, the issue is caused by InRelease being older than rest of the repository (it's dated 14 March, while Packages and rest are dated 15 March). and it contains wrong checksums and file sizes.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/45868
