### ISSUE TITLE
How to generate xxx.i18n.json

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#4109]
It`s great that vscode supports internationalization. I want to know how to generate and edit
the json files in the https://github.com/Microsoft/vscode/tree/master/i18n. 
Is there a tool? Is it open source?

**Comment by dbaeumer** [comment]
Unfortunately the files can currently not be edited since we receive them from a different source.

**Comment by Tyriar** [comment]
In the past contributors have created github issues describing the issue with the text/language/key and we forwarded it to the i18n team.

**Comment by wojtekmaj** [comment]
So is there a way to contribute to i18n at the moment?

**Comment by dbaeumer** [comment]
@wojtekmaj only via GitHub issues. There is not way right now to provide PR to change i18n files.

**Comment by NeoLegends** [comment]
Please make for one! The german translation feels entirely machine generated to me as a native speaker!

**Comment by wangweixuan** [comment]
Is this issue forgotten by everyone? Glad that we can now close it! https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

**Comment by dbaeumer** [comment]
Agree. This got delivered with 1.12.
