### ISSUE TITLE
HTML - on save, Visual Studio Code editor adds extra whitespaces before and after quotation marks (")

### ISSUE THREAD

**Issue by hajdun** [Microsoft/vscode#41098]
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:
Windows 10 (latest)

Steps to Reproduce:

1. Save html in editor

Expected: 
html saved normally, like 
type="checkbox"

Actual:
Code broken because of bad whitespace additions in my html like
  type="checkbox "
which literally breaks behavior

Reproduces without extensions: Yes

Overwritten user settings:
{
    "editor.formatOnSave": true,
    "html.format.preserveNewLines": false,
    "html.format.extraLiners": ""
}

Overwritten workspace settings:
// Remove trailing auto inserted whitespace
{
    "editor.trimAutoWhitespace": true
}

**Comment by aeschli** [comment]
That's likely caused by `"editor.formatOnSave": true`. The other settings don't influence the formatter.
Can you paste a sample code?
