### ISSUE TITLE
Extension that calls process.exit() brings down extension host

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#411]
D'oh :)

@alexandrudima fyi, I think we should prevent/override calls to process.exit() but obviously there might be more ways to bring down the host.

**Comment by alexandrudima** [comment]
On the long term, I think we should recover from extension host process crashes

**Comment by bpasero** [comment]
@alexandrudima could you verify this one please? it is easy to reproduce by installing the Yo extension and following the steps:
- open vscode workspace
- run yo from f1 and pick code-generator
- pick the ts extension
- pick "test" as name
- click through until you get the conflict
- click abort

=> in the console you should see a warning that an extension tried to call process.exit()
