### ISSUE TITLE
Message "Git not found. Install it or configure it using the 'git.path' setting" on brand new, fresh, shiny, Git-less installations of VSCode

### ISSUE THREAD

**Issue by klsorenson** [Microsoft/vscode#41104]
- VSCode Version: 1.19.1
- OS Version: Win 7, Win 8.1, Win 10 (all builds), Server 2008 R2, Server 2012, Server 2012 R2, Server 2016, Server 1709. 

Steps to Reproduce:

1. Install VS Code for the first time with no existing Git install
2. Launch VS Code

Reproduces without extensions: Yes

Perhaps this is an easily answered question, and not an issue. 
Everything I've located thus far points to issue #40229 which seems to apply mostly to existing Git installations that aren't detected properly. This seems a bit different, since there aren't any Git installations to detect. 
From the release notes, I haven't been able to locate anything that indicates Git is installed with VS Code, nor enabled by default. 
During testing, we noticed this error messages on brand new, fresh Windows installations as well as outside of our lab on our own workstations. Our own workstations, which had a variety of older VS Code installations, some have Git and some do not. The lab environment VMs were recently created and had never had an older version of VS Code installed, nor had they had any version of Git or Git-like software installed.

**Comment by joaomoreno** [comment]
We could perhaps only show this message if we detect a `.git` folder in your workspace...

**Comment by suntong** [comment]
Any way to fix this? 

> From the release notes, I haven't been able to locate anything that indicates Git is installed with VS Code, nor enabled by default.

According to what I read, from https://code.visualstudio.com/docs/editor/versioncontrol

> Visual Studio Code has integrated source control and includes Git support **in-the-box**. 

Anyway, I'm more interested in how to fix this?
In that _"Git not found. Install it or configure it..."_ provides a link, but I don't see or know what to download and Install git on Windows.

**Comment by suntong** [comment]
Found it, Install Git from https://git-scm.com/download/win first

**Comment by GandalfSaxe** [comment]
@joaomoreno Why does VSCode not detect git from the user PATH environment? Why does it *have* to be specified explicitely if `git` is not present in a small list of "standard locations"?

**Comment by GandalfSaxe** [comment]
@joaomoreno I don’t understand. If I open the command line and type “git” it knows where the program is because it’s in the PATH, but VSCode still have to be told explicitly?

Why can’t VSCode just read the PATH variable if there is a git path?

**Comment by joaomoreno** [comment]
@GandalfSaxe That's not what this issue is about.

If you do witness that issue, simply unconfigure `git.path`, reload Code, open `Git: Show Git Output` and see which paths Code looks for git in.
