### ISSUE TITLE
Double clicking explorer sash no longer sizes ideal width

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#41102]
After double clicking the explorer sash no files/folders should be truncated with '...'. Looks like this is a regression from the explorer badges.

![image](https://user-images.githubusercontent.com/2193314/34527434-65e90888-f05a-11e7-95cd-a1742df08e82.png)

**Comment by jrieken** [comment]
> Looks like this is a regression from the explorer badges.

What makes you think that?

**Comment by Tyriar** [comment]
@jrieken because I think it worked in the previous version and the truncation is happening right next to the M badges.

**Comment by bpasero** [comment]
Yeah this is an issue with the `::after` element of badges. In [`getOptimalWidth`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L471) of the explorer we compute the optimal width of all labels (by selecting `.explorer-item .label-name`) in the explorer but that does not account for any badge showing up.

Happy to review a PR if the change is reasonable.

**Comment by Tyriar** [comment]
So this works but I'm not particularly happy with it https://github.com/Microsoft/vscode/commit/e0ecb0d59921f5d7c46b62a62e2308e3487b2840 on https://github.com/Microsoft/vscode/tree/tyriar/41102

Seems like a difficult thing to accomplish without changing how the badges are represented.

**Comment by bpasero** [comment]
@Tyriar yeah that is a bit ugly / hack. It would also need to be added to the open editors view [`getOptimalWidth`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/openEditorsView.ts#L398) call.

**Comment by Tyriar** [comment]
@bpasero would you want to accept a PR with this fix (+ open editors view)? @jrieken can you think of a better way to get the badge size when we only have the set of elements?

**Comment by bpasero** [comment]
@Tyriar yeah why not, we can discuss in there.

**Comment by Tyriar** [comment]
Also testing this a bit more it didn't seem to return the correct width for the pseudo-element sometimes. This is free for someone else to pickup if they want to dig deeper.
