### ISSUE TITLE
Integrated Terminal does not accept non-integer values for font size

### ISSUE THREAD

**Issue by sabriele** [Microsoft/vscode#41109]
_Probably similar to issue raised in #35991 as well as the other issues referenced in that issue.
Raising issue because the majority of other users affected seem to be running on Windows. Also, am on version 1.19.1 and it still doesn't seem to be fixed for me (I believe the others have had it fixed by 1.17.2)._
- VSCode Version: 1.19.1
- OS Version: macOS High Sierra 10.13.2 (17C88)
- Reproduces without extensions: Yes

Integrated Terminal font size does not change when decimals are added to it (13 px and 13.2 px looks the same). This is unlike the corresponding Editor font size which shows a clear difference between two font sizes that are separated by even one decimal point e.g. 13.2 px and 13.3 px.

**Steps to Reproduce:**
1. In User Settings, set 
```json
"editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace",
"terminal.integrated.fontFamily": "", // defaults to editor.fontFamily's value.
"window.zoomLevel": -1,
"editor.fontSize": 13.2,
"terminal.integrated.fontSize": 13.2
```
2. Screenshot below shows that the Integrated Terminal's font looks a bit horizontally squished. _(The text_ `"terminal.integrated.fontSize": 12,` _has been placed both in the Editor and Integrated Terminal for easy comparison.)_

![screen shot 2018-01-04 at 12 41 05 am](https://user-images.githubusercontent.com/4678102/34529824-29e9a7be-f0e8-11e7-85ce-3269ae8d1105.png)

**Comment by Tyriar** [comment]
Unfortunately canvas does not appear to support drawing of floating point sized fonts. Proof:

![image](https://user-images.githubusercontent.com/2193314/34534369-b6a148a4-f072-11e7-9eda-a0388bb8c6a4.png)

**Comment by sabriele** [comment]
@Tyriar Sorry I hadn't realised that and thank you.

**Comment by Tyriar** [comment]
We both learned something 😄
