### ISSUE TITLE
The Code Editor starts but appear all black

### ISSUE THREAD

**Issue by elultimocapo421** [Microsoft/vscode#41101]
![vsimage](https://user-images.githubusercontent.com/33487969/34526931-df5c2bde-f071-11e7-8a9d-0f61e2d9edb5.JPG)

**Comment by elultimocapo421** [comment]
All begins when i made the last updation of Windows. When i finish this, i can't use the main Code editors like Visual Studio Code and Atom. I don't know what i can do

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/40329 ?

**Comment by rebornix** [comment]
@elultimocapo421 can you confirm if it's #40329 and if you have the same problem with Atom?

**Comment by elultimocapo421** [comment]
I have installed one thousand times  each code editor, trying several versions of both and all without success. i going to do it again, i will install both editors for take a photo of what's going in on.

**Comment by elultimocapo421** [comment]
@usernamehw , thanks for answer.
**I did updated Windows.** I began to install and try several versions of the code editors after have been look the problem.

The curious of this is that both editors are sensible to whatever action, the unique problem is that I can't see anything. Now , after install the code editors again this happend:

Atom:
-Start but appear in blank
-it functional, the editor answer to my orders but i can't see anything. I can use all the options in the menu bar or inside of the editor, you know that in the welcome page there are some links, and are functionals.

Vs Code:
-Is the same problem only that appear in black.

![editors](https://user-images.githubusercontent.com/33487969/34955628-50636d44-f9f3-11e7-864d-7ef6f661ef7b.PNG)

**Comment by elultimocapo421** [comment]
hi, @bpasero where can i use that code?

**Comment by bpasero** [comment]
@elultimocapo421 from the command line

**Comment by elultimocapo421** [comment]
i can't use it ,  it doesn't appear...

**Comment by bpasero** [comment]
@elultimocapo421 so you where able to start using `code --disable-gpu` but the window did not appear?
