### ISSUE TITLE
"code --status" errors out

### ISSUE THREAD

**Issue by MikeB2012** [Microsoft/vscode#41105]
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

When I run "code --status" I get the following error:

PS C:\Program Files\Microsoft VS Code> code --status

[main 10:26:17 AM] SyntaxError: Unexpected token  in JSON at position 1754
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:132:413)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by bpasero** [comment]
I suspect an issue with the result from PS.

**Comment by dbaeumer** [comment]
Looks like the JSON returned from the PS script is not valid JSON. I will add some code that prints the JSON in terms of the failure to better understand why it is not parseable.

**Comment by dbaeumer** [comment]
I have no idea why this is failing. I added more proper logging code. 

@MikeB2012 can you try this with the insider build from tomorrow and see if it prints more information. 

Running code -status require PowerShell on your System. Do you by any change don't have it installed ? Which version of Windows are you running?
