### ISSUE TITLE
Trim trailing whitespace and Trim trailing newline overwrite the redo stack

### ISSUE THREAD

**Issue by floribon** [microsoft/vscode#41115]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.9.0-4-amd64
- Extensions: none
---

This is a follow-up of #19881. The issue wasn't caused by an extension but the user settings **files.trimFinalNewlines** and **files.trimTrailingWhitespace**. If I set these to true, I cannot redo after saving. Enabling only one or the other makes the problem behave differently.

Steps to Reproduce:

1. Set files.trimFinalNewlines and files.trimTrailingWhitespace to true in user settings
2. Open a file and add a word "hello"
3. Add another word on a new line "world"
3. Undo (ctrl + Z) ("world" is properly erased, cursor back to line 1)
4. Save (ctrl + S)
5. try to redo (ctrl + Y): **nothing happens** (we expect "world" to come back)

When enabling only trimFinalNewlines, this scenario seems to work but it breaks when we only add one word ("hello") on an indented line and undo + save + redo.

**Comment by fredwu** [comment]
Same issue here, I disabled `files.trimFinalNewlines` for now to work around it. Took me a while too to realise it's not caused by extensions...

**Comment by fredwu** [comment]
Not sure why this issue is labelled "feature request" instead of "bug". 🤔

**Comment by floribon** [comment]
Agreed this is a bug and I've had to disable these settings for months now. Any ETA?

**Comment by jscheel** [comment]
It seems like a number of "on save" actions corrupt the undo stack, I wouldn't think that this is limited to just these options. I can also replicate corruption of my redo stack with the beautify extension.

**Comment by AiryShift** [comment]
As of the current latest commit on `master` (5215f2379d), I can no longer reproduce the bug as described. I guess it's fixed and will be released eventually.

**Comment by quassy** [comment]
> It seems like a number of "on save" actions corrupt the undo stack, I wouldn't think that this is limited to just these options. I can also replicate corruption of my redo stack with the beautify extension.

See also #87741.

**Comment by floribon** [comment]
The problem I described seems to be fixed in the current release indeed, thanks!
