### ISSUE TITLE
Typo in "After editing the file" notification

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#41111]
Reported via Twitter from https://twitter.com/deathbypecanpie

Golbal instead of global :) pic.twitter.com/6zzZ4VDRuf

![6ogjkmk_](https://user-images.githubusercontent.com/173559/34534477-14c50bfa-f073-11e7-8521-b864b9c828d7.jpg)

**Comment by jens1o** [comment]
looks like a 3rd party extension.

**Comment by leonardosnt** [comment]
Duplicate #23932 ?

**Comment by cleidigh** [comment]
@auchenberg 
*Duplicate: #23932
