### ISSUE TITLE
Extension status bar animation does not fit well

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4111]
I find the animation for the extension status bar entry does not fit well with the other animation we use for git where we just keep the icon but indicate progress through animation. 

I suggest to go back to how it was before so that the icon is still visible but just animated.

cc @egamma 

Refs: https://github.com/Microsoft/vscode/issues/4024

**Comment by joaomoreno** [comment]
The icon is still visible, just overlaid in an animation the same way the install and uninstall buttons are.

**Comment by joaomoreno** [comment]
*go back* means a wiggle animation. I personally think it would fit even worse than the current animation.

Forwarding to @bgashler1 who can figure out a better animation for installing extensions.

Also, notice that this won't survive long, once we move this into a viewlet.

**Comment by bgashler1** [comment]
Since we will be improving the extension experience soon and notification experiences, this shouldn't be any concern pretty soon.  I propose we leave this the way it is. Closing unless there are objections.

**Comment by bgashler1** [comment]
Related to #637
