### ISSUE TITLE
Hash sum mismatch

### ISSUE THREAD

**Issue by joowdx** [Microsoft/vscode#41117]
- VSCode Version: 1.19.1-1513676564_amd64
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Tried adding the repository manually and 
`sudo apt update` 
```
E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  Writing more data than expected (35578 > 35343)
   Hashes of expected file:
    - Filesize:35343 [weak]
    - SHA512:c9496b6c369f633e2ae431bb758cf970671c191bd02264713ce864dc327475b9ca7cdddda7dee0a14a556dc65d6b59a8f79f16c47e178a6345c90878c99fa0c8
    - SHA256:fba8fa5d5d6d200e9b45febf5bb0e9fe0d9165202c2cbfe38c72d64a423cf4a3
    - SHA1:66776788449c7465ac8668f904c730310fd95e37 [weak]
    - MD5Sum:c87007bbbd77cb0d60fa69f5f83b6a7c [weak]
   Release file created at: Thu, 21 Dec 2017 18:21:42 +0000
```

2. I removed the gpg file `/etc/apt/trusted.gpg.d/ and the list file`manually `/etc/apt/trusted.gpg.d/` and ran `sudo apt update` again and it still gave me the same error.

3. Tried following each and every possible fix given [here](https://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error) doing the step 1 and 2 again in every possible fix but no luck, none of it fixed the thing.

4. Tried doing step 2 again and installed the [deb file](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions) knowing that it'll add the repository automatically yet still same error when updating.

5. Found the [same issue](https://github.com/Microsoft/vscode/issues/25883) a year ago and tried how he fixed it still no luck.

6. Finally I tried doing everything from a live usb to see if the problem was just my system but again no luck, still faced the same error.

Do really find this weird because I haven't faced this kind of problem when installing it earlier before I've reseted my laptop.
Help! Thanks.

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/41094
