### ISSUE TITLE
Enable "smart case" for search

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41119]
"Smart case" is a ripgrep feature that will handle a query as case-sensitive if it contains uppercase characters, and case-insensitive if it doesn't.

For example, a document contains

```
asdf
asdF
```

With "smart case" enabled, the query `asdf` matches line 1 and line 2. And the query `asdF` only matches line 2.

It also works for regular expressions. The regex query `asd\S` matches line 1 and line 2. The query `asd[A-Z]` only matches line 2.

We should introduce a setting, `search.smartCase` or `editor.find.smartCase`. This is easy to hook up for ripgrep, but we also need to implement it for when results are provided by the editor, and for when ripgrep is not used. This is easy for non-regex queries. For regex queries, ripgrep previously attempted to tell whether the regex would match any uppercase characters. But this had unintended consequences, like `\w` triggering case-sensitivity, so now it only checks whether the regex text has any unescaped uppercase characters (https://github.com/BurntSushi/ripgrep/issues/717). Fortunately this is easy for us to match.

- Does this make sense for editor find or just search?
- If both, is it a problem that search is respecting some `editor.find` settings but not all?

cc @rebornix 

Alternately, the "case sensitive" toggle button could be a 3-mode switch which also can enable smart case.

**Comment by octref** [comment]
See #42684 for an issue.
I think this should go to editor find too. Vim has this on by default.
One thing would be great: When this setting is on, whenever you type in the first uppercase char it toggles the Match Case icon (but later people can still toggle it off).

**Comment by roblourens** [comment]
I agree, we had talked about more UI for that. Just filed https://github.com/Microsoft/vscode/issues/42687
