### ISSUE TITLE
Python's auto formatting can not work on the linux.

### ISSUE THREAD

**Issue by bulletforkiller** [Microsoft/vscode#41127]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.14.0-kali1-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.2.0
vscode-docker|Pet|0.0.22
vscode-emacs-friendly|lfs|0.8.2
Go|luk|0.6.70
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
python|ms-|0.9.1
cpptools|ms-|0.14.5
vscode-icons|rob|7.19.0
vscode-lldb|vad|0.7.3

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
Please file issues against the python extension you are using.
