### ISSUE TITLE
Duplicate source control providers

### ISSUE THREAD

**Issue by dhirschfeld** [Microsoft/vscode#41128]
- VSCode Version: Code - Insiders 1.20.0-insider (8697a5e4ec152832a2612929c87d56302dbb2e79, 2018-01-03T05:14:21.686Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|7.2.0
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.1
docker-explorer|for|0.1.6
rest-client|hum|0.16.2
mssql|ms-|1.3.0
python|ms-|0.9.1
azure-account|ms-|0.2.2
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.0.0
vscode-docker|Pet|0.0.22
annotator|ryu|0.11.0
partial-diff|ryu|0.5.1
code-settings-sync|Sha|2.8.7
Align|ste|0.2.0
cython|tcw|0.1.0
cmake|twx|0.0.17
gitblame|wad|2.2.0
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.1

---

Steps to Reproduce:

It just started happening - I don't know how or why!?
![image](https://user-images.githubusercontent.com/881019/34551424-7e77b87a-f165-11e7-80cd-3b35597dca87.png)

Reproduces without extensions: ***No***

**Comment by joaomoreno** [comment]
Is your project in a network share? Is there anything special about it? Can you reproduce in other projects?

**Comment by dhirschfeld** [comment]
Yep, it's on a network share. Only seen in that instance. Will report back tomorrow if I still see the issue...

**Comment by joaomoreno** [comment]
OK let me know.
