### ISSUE TITLE
Extension Errors are clipped and stacked

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4112]
Testing #4024 
- VSCode Version: Alpha
- OS Version: Windows

Steps to Reproduce:

1. create several extension issues (e.g. remove the package.json from an extension)
2. restart code 
3. open the extension status bar item

Each error is shown in a separate message box and the error message is clipped

![image](https://cloud.githubusercontent.com/assets/172399/13741208/597ece8a-e9d5-11e5-9d58-b7f22979776b.png)

Suggest to show the error messages in the output window and an extension-errors channel.

FYI: @joaomoreno

**Comment by bpasero** [comment]
I very much like that :+1:

**Comment by joaomoreno** [comment]
I can take that.
