### ISSUE TITLE
I want multiple diffrence terminals.

### ISSUE THREAD

**Issue by rabbitmeow** [Microsoft/vscode#41129]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

I wanna use powershell to run javac when I developing java program and use subsystem ubuntu to develop js. Can you provide a function to support that?
thank you very much.

**Comment by Tyriar** [comment]
You can do this with extensions, check out https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals and https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
