### ISSUE TITLE
Intellisense seems to ignore exclude patterns

### ISSUE THREAD

**Issue by mwmessin** [Microsoft/vscode#41121]
- VSCode Version: 1.19.1
- OS Version: OSX Sierra 10.12.6

Steps to Reproduce:

1. Open a large project folder (I have one with a massive node_modules)
2. Observe terrible intellisense performance (Typescript in my case; Code Helper proc memory will balloon)
3. Add "**/node_modules" to the settings or workspace "files.exclude" (verify it disappears from explorer sidebar)
4. Observe intellisense performance is still terrible (even after restarts)
5. Create a new workspace that cherry picks just your src/ and vendor/ directories for example; Magically performance is no longer terrible, goto and autocomplete work again.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
To explicitly exclude files from intellisense, create a [`jsconfig.json`](https://code.visualstudio.com/docs/languages/javascript#_javascript-project-jsconfigjson) file at the root of your workspace with the content:

```json
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by mwmessin** [comment]
aha! it only works if the file is named `jsconfig.json`, mine was named `tsconfig.json`

**Comment by mwmessin** [comment]
also this seems problematic for vscode in combination with https://github.com/Microsoft/TypeScript/issues/15869

**Comment by mjbvz** [comment]
1. Back with the tsconfig.
1. Set `"typescript.tsserver.log": "verbose"` in your user settings
1. reproduce the problem
1. From a TS file, run the `Open TS Server log` command and view the `tsserver.log` file

In this file, a list of all files in your TS project will be printed. This should look like:

``
Info 120  [12:58:27.169] Project '/Users/matb/projects/vscode/extensions/typescript/tsconfig.json' (Configured) 0
Info 120  [12:58:27.169] 	Files (86)
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es5.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.reflect.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.proxy.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.iterable.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.promise.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.generator.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.collection.d.ts
	/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.core.d.ts
	/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/protocol.d.ts
	/Users/matb/projects/vscode/extensions/typescript/src/protocol.d.ts
	/Users/matb/projects/vscode/extensions/typescript/src/protocol.const.ts
	/Users/matb/projects/vscode/extensions/typescript/src/utils/is.ts
	/Users/matb/projects/vscode/extensions/typescript/node_modules/vscode-nls/lib/main.d.ts
	/Users/matb/projects/vscode/extensions/typescript/src/utils/logger.ts
....
```

Are any unexpected files or directories being included in the project?

**Comment by mwmessin** [comment]
did that, it showed all the stuff from node_modules and vendor that I was ignoring not being ignored...

So our project put the exclude: inside of a tsconfig.app.json (not at the root of proj) which does an extends: "../tsconfig". Vscode doesn't like that, moving the exclude: up to the root tsconfig fixed the issue.

thanks @mjbvz I consider this solved. (But maybe it'd be cool if it hunted for extended tsconfigs)
