### ISSUE TITLE
The background task of the ES6 compilation can't reset the problems

### ISSUE THREAD

**Issue by stuartZhang** [Microsoft/vscode#41125]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing length exceeds browsers' URL characters limit
- Task version: 2.0.0
---

Steps to Reproduce:
1. git clone: https://git.dehuinet.com/zhanghy/vue_lab.git
2. Change your local npm-server reference from https://registry.npmjs.org/ to http://npm.dehuinet.com:8100/, since some of dependencies comes from the latter.
3. Open VSCode
4. Open the "vue_lab" project.
5. Type "Ctrl + `" to open the integrated terminal.
3. Execute: npm install
4. [Execute: npm run dev] OR [Run the task "run-dev"]
5. Open the URL http://localhost:8080/#/ in your default web browser.
6. Open the vue file "src\components\HelloWorld.vue"
7. [Insert the line break between 40 and 41 lines] or [Insert several whitespaces in the beginning of the 42th line]
8. Type "Ctrl + S" to save the file.
9. View the output of the integrated terminal.
![stylelint-errr-1](https://user-images.githubusercontent.com/13935927/34547729-4ce12422-f138-11e7-8ba5-9ea2fba0268d.png)
10. View the VSCode editor.
![stylelint-errr-2](https://user-images.githubusercontent.com/13935927/34547809-ce56b74c-f138-11e7-8b35-19fb31e2b231.png)
At this point, the error highlight is in place correctly.
11. [Delete the line break in the 41th line] OR [Delete the improper whitespaces in the beginning of the 42th line]
8. Type "Ctrl + S" to save the file.
9. View the output of the integrated terminal.
The webpack reports the success of the compilation and packing.
![stylelint-errr-3](https://user-images.githubusercontent.com/13935927/34547963-d5929f20-f139-11e7-8614-957fe79769ab.png)
10. However, **the error highlight isn't erased from the VSCode Editor**.

As for the details of the task configuration, please you peruse the file ".vscode/tasks.json"

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
The problems are only cleared when the end pattern is detected in the output. The ends pattern in our example is defined as `"endsPattern": "^\\s+End: .+"` which I can't detect in the output. I can't even detect the beginsPattern `"beginsPattern": "Compiling\\.\\.\\.",`.

For problem matcher that run in the background (e.g. watching compile tasks) the match of the begins patterns signals the start of a compilation run and the ends pattern signals the end. Problems are cleared when the end pattern are detected in the output. 

I will close the issue. Please ping if this will not address your problem.

**Comment by stuartZhang** [comment]
Please you see the previous snapshot where the text "End:" appears.

**Comment by dbaeumer** [comment]
Now I see. It it right aligned. Sorry for that. But I think that `^\\s+End: .+` since the line seems to start with `I You application ...`

If you provide me with a simple GitHub repository I can clone I can have a look whether this might be a problem with a line wrapping in the terminal.
