### ISSUE TITLE
Changing a file's case externally on case insensitive file system can get workbench into bad state

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#41122]
- VSCode Version: code-oss-dev 1.20.0 (Commit unknown, Date unknown)
- OS Version: Darwin x64 17.3.0

Steps to Reproduce:

1. On MacOS case-insensitve file system
1. Create a workspace with a file `FOO.ts`
1. Open `FOO.ts`
1. Close all files
1. Outside of VS Code, rename `FOO.ts` to `foo.ts`
    * Note no update in vscode's file explorer
1. Double click on `FOO.ts` in the file explorer
     * Note that this opens a file called `FOO.ts`
1. Refresh the file explorer
    * Note the file name change is now properly picked up
1. Open `foo.ts` from the explorer

💥— Both `FOO.ts` and `foo.ts` are now open. These editors are for the same file on disk. Saving either one updates both editors. You also get duplicate entires in quick open

![a](https://user-images.githubusercontent.com/12821956/34546777-16cad64a-f0ab-11e7-9a1b-68464fb32ba5.gif)

This appears to be the root cause of #40682

**Comment by bpasero** [comment]
Welcome to https://github.com/Microsoft/vscode/issues/12448
