### ISSUE TITLE
Feature Request: Python virtual environment starts with vs code, access from terminal

### ISSUE THREAD

**Issue by addohm** [Microsoft/vscode#41124]
I truly like vscode.  The one sole feature that turns me away is the fact that I have to fire up my virtual environment, then fire up vscode, and if I want to use the terminal inside of vscode, I have to fire up yet another virtual environment.

Pycharm does all this for you.  You launch pycharm.  When you open up a project, if it's already been set up with the appropriate interpreter, it will start up within that environment and the embedded terminal will also be within that environment.

Is this a feature we can expect to see come to vscode?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36585
