### ISSUE TITLE
HTML Formatting -> Feature Request -> Choose Attributes to force align

### ISSUE THREAD

**Issue by peacefulseeker** [Microsoft/vscode#41135]
Hi,

would be nice to have feature in HTML formatting to choose which attributes to "force-align" and which not.
For example we are working with xhtml files with structure like that:
```
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
              xmlns:h="http://java.sun.com/jsf/html"
              xmlns:c="http://java.sun.com/jsp/jstl/core"
              xmlns:f="http://java.sun.com/jsf/core"
              xmlns:ui="http://java.sun.com/jsf/facelets"
              xmlns:p="http://primefaces.org/ui">
</ui:composition>
```
And these attributes nice to read when they are separated by new line. This can be done via 
`  "html.format.wrapAttributes": "force-aligned",` setting.
Would be nice to have feature like include specifict attributes like:
 ```  
"html.format.wrapAttributes": {
    "type": "force-aligned",
    "include_attributes": ["xmlns:", "requiredMessage", "and so on"]
  },
```

**Comment by aeschli** [comment]
We use JSBeautify as the underlying HTML formatter. Please file the suggestion there: https://github.com/beautify-web/js-beautify
