### ISSUE TITLE
Extensions default filters.

### ISSUE THREAD

**Issue by Guema** [Microsoft/vscode#41138]
Hello VScode team, happy new year !

So, i was thinking about a default filter for extension.
When i go to my extension category, i would like to only see enable-for-this-workspace extensions.
This is absolutely possible by filters, but a little improvement could be to add an option allowing to change default filter from "@installed" to "@what-ever-i-want-because-i-m-capricious @and-lazy-too" for example. allowing to win some time and directly go straight to the point.

In my case, working on multiple projects, having a lot of extensions i use only in specific folder/workspace, i don't need to see project2 and project3 extensions when i work on project1. But i will see them at the top, even if they are disabled, because project2 and project3 extensions starts with "A", "B" or "C".

**Comment by Guema** [comment]
I see you are working on something that somewhat solving this request.
I close it.

**Comment by ramya-rao-a** [comment]
Yes @Guema.

In the latest Insiders, the default view contains `Enabled` and `Recommended` sections. You can customize this view and get to choose between `Enabled`, `Disabled`, `Installed` and `Recommended Sections`

**Comment by ramya-rao-a** [comment]
Marking this issue as duplicate of #27061 as there is more user activity there.
