### ISSUE TITLE
We changed our default indent from spaces to tabs and should announce this properly

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4113]
We seem to have changed the default from 4 spaces to 4 tabs and this will cause issues for any project that left the default settings in expecting new files to get spaces and not tabs.

I hope release notes are good enough, but I have a feeling this might backfire badly to us.

Refs: https://github.com/Microsoft/vscode/issues/3922

**Comment by bpasero** [comment]
One example: The typescript project uses spaces and does not configure indentation.

**Comment by alexandrudima** [comment]
@bpasero Any suggestions? We have usually communicated breaking changes in the release notes.

For the TypeScript project the guessing should guess spaces, does it not do so?

**Comment by bpasero** [comment]
@alexandrudima sure it does, but not for new files, so you end up polluting the workspace with partial tab partial whitespace files.

Why did we decide to change the defaults?

**Comment by alexandrudima** [comment]
@bpasero Are you arguing we should go back to the default `insertSpaces`: true ?

**Comment by alexandrudima** [comment]
That is fine by me

**Comment by bpasero** [comment]
@alexandrudima yes, now that I saw the TypeScript workspace I think that would be good.
