### ISSUE TITLE
Feature request: Extract Inline Style to CSS file Or <Style> tag  in Visual Studio Code

### ISSUE THREAD

**Issue by Linrstudio** [Microsoft/vscode#41132]
Steps to Reproduce:

1. select a inline style css text;
2. Light icon display, click to show extract menu: 
    menuitem: extract to css file
    menuitem: extract to &lt;style&gt; tag

**Comment by aeschli** [comment]
duplicate of #41134 (Basically the same. I already mentioned in there that a code action (light bulp) would be the better than a context menu)
