### ISSUE TITLE
Window freezes when changing clock backwards

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41136]
Unfortunately it looks like spdylog is still causing the window to freeze from time to time on Windows. I was for a long time suspecting my change from sync to async dialogs to cause the behaviour but now I see that it might not be the case.

Here is what I did today and what in the past often has caused the renderer (window) to show a dialog that it no longer responds:

![image](https://user-images.githubusercontent.com/900690/34559357-dba3a6a4-f141-11e7-958b-2d2465c9e983.png)

* wake up a sleeping Windows 10 VM in parallels that has Code Insiders running (as well as code out of sources)
* check for updates in the Code Insiders version (it downloads the update from today)
* undo a change from git viewlet and confirm it (since I was always suspecting this to originate from my dialog changes, I wanted to trigger a dialog to see if it is reproducible)
* in the version where we run out of sources I did the same from the git viewlet
* meanwhile in Code Insiders acknowledge the update from the gear icon
* now the installer tells that Code Insiders did not correctly shutdown and thus cannot install
* abort the installation
* check process explorer and notice how the Window is still running even though the main process is gone (!)
* open VS and attach to the window process
* pause using the debugger and notice how you always end up in this stack:

![image](https://user-images.githubusercontent.com/900690/34559288-8fdbea6a-f141-11e7-885f-ba1ea19cb870.png)

Notice how VS indicates that lots of memory gets allocated and freed:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/34558702-6a8c3e9c-f13f-11e7-936d-02f4aef6522f.gif)

It is worth mentioning that my logs folder for Code Insiders does not contain any new entry for today (4th of January) in the renderer, the last entries are from the day before (3rd of January):

[logs.zip](https://github.com/Microsoft/vscode/files/1603003/logs.zip)

This is a tough one, I cannot easily reproduce. It very often typically happens with the steps above where I come into the office the next day, resume by VMs and check for updates. 

Maybe this is related to the fact that VS Code is running over night and spdylog somehow fails to create a new log folder for the new day from the renderer? The weird thing however is that the extension host log folder seems to have an entry from the 4th. But there is no entry for the renderer (e.g. I would expect some entries for the discarding of changes from the git viewlet).

I can also not really understand why this does not happen in stable. Did we change anything in insiders around spdylog?

**Comment by bpasero** [comment]
I was able to reproduce running out of sources and now the stack reveals a little more:

![image](https://user-images.githubusercontent.com/900690/34559288-8fdbea6a-f141-11e7-885f-ba1ea19cb870.png)

**Comment by joaomoreno** [comment]
Awesome steps and details!

**Comment by joaomoreno** [comment]
Steps:

1. Open Code
2. Run a keybinding command (Show Explorer)
3. Forward date by 1 day
4. Run a keybinding command
5. Reverse date change
6. Run a keybinding command
7. Close Code

It freezes.

**Comment by joaomoreno** [comment]
We're hitting this: https://connect.microsoft.com/VisualStudio/Feedback/Details/1121801

**Comment by joaomoreno** [comment]
I've contacted a dev in VS Libs for help.

**Comment by sandy081** [comment]
Good job @joaomoreno

**Comment by joaomoreno** [comment]
VS reports that the issue is **not** yet fixed, unfortunately.

**Comment by joaomoreno** [comment]
Created PR for spdlog: https://github.com/gabime/spdlog/pull/610

**Comment by joaomoreno** [comment]
Verified in dev that it doesn't freeze any more when changing time back.
