### ISSUE TITLE
Unable to download the symblos..

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/vscode#41144]
- VSCode Version: Unable to download the symbols..  Pf
- OS Version:

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/35101458/34562869-3cfe77ec-f176-11e7-896b-a166de5ab0cf.png)

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Closing as cause-by extension. Please file this against the AL language extension
