### ISSUE TITLE
Opening Native Console with keybinding(workbench.command.terminal.openNativeConsole)

### ISSUE THREAD

**Issue by MrMuMu** [Microsoft/vscode#41146]
- VSCode Version: 
Version 1.20.0-insider
Commit 52d0befdb31841cbebd7aec20cfffc932f1c02ec
Date 2018-01-04T05:14:02.889Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows 10 Enterprise x64

Steps to Reproduce:

1. Remove the keybinding of workbench.action.terminal.toggleTerminal
2. Remove the keybinding of workbench.action.terminal.new
3. Set a binding for workbench.command.terminal.openNativeConsole to Ctrl + "

- Expected Result
new command prompt

- Actual Result
warn no provider for [object Object]
![error](https://user-images.githubusercontent.com/11612804/34562835-2bc7fb34-f161-11e7-8e21-33375fe3ea56.jpg)

It occurs when all extensions are disabled. Also there is no conflict with the binding.

**Comment by Tyriar** [comment]
I think this was a result of a refactor that changed the openNativeConsole command which has been fixed now.
