### ISSUE TITLE
Terminal window being overtaken by cmder

### ISSUE THREAD

**Issue by jsjain007** [Microsoft/vscode#41140]
Vscode's integrated terminal does not opens instead [cmder](http://cmder.net/) app get active focus when i try to open integrated terminal with `ctrl + backtick`.

- OS Version: Windows 10 version 1703
- Version 1.19.1
- Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
- Shell 1.7.9
- Node 7.9.0

Steps to Reproduce:

1. open [cmder](http://cmder.net/) console in background
2. open vs code
3. Try to open integrated terminal with ctrl + backtick
4. cmder get active focus and comes to foreground.

In my user settings also I am using powershell as default
`    "terminal.integrated.shell.windows":"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
cmder's keybinding intercepts the keystroke before it reaches the VS Code window, you need to disable it in cmder's settings.

**Comment by jsjain007** [comment]
But when vscode is active window then how does even cmder can intercept the keybinding ?

**Comment by Tyriar** [comment]
@jsjain007 some API Windows exposes I guess. We have out own keybindings system but it needs to reach the window to act upon it.
