### ISSUE TITLE
"enter" as the key for the "closeFindWidget" command performs an (wrong) additional search

### ISSUE THREAD

**Issue by pbgc** [microsoft/vscode#41142]
I edited my keybindings.json to create a fairly acurate clone of the emacs keys.
In that file I have:

```
    {
        "key":"ctrl+s",
        "command":"actions.find",
        "when":"editorTextFocus"
    },
    {
        "key":"ctrl+s",
        "command":"editor.action.nextMatchFindAction",
        "when":"editorFocus && findWidgetVisible"
    },
    {
        "key":"enter",
        "command":"closeFindWidget",
        "when":"editorFocus && findWidgetVisible"
    },
    {
        "key":"ctrl+r",
        "command":"actions.find",
        "when":"editorTextFocus"
    }
```

To emulate emacs search behaviour.

The problem is with:

```
    {
        "key":"enter",
        "command":"closeFindWidget",
        "when":"editorFocus && findWidgetVisible"
    }
```
This should only close the find widget and with any other key it does!!! But with the **enter** key (that's the one I need) It does an additional search before closing ... so the cursor gets positioned in the wrong place after closing the Find Widget.

- VSCode Version: 1.19.1
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. edit keybindings.json
2. paste (json above):
{
        "key":"ctrl+s",
        "command":"actions.find",
        "when":"editorTextFocus"
    },
    {
        "key":"ctrl+s",
        "command":"editor.action.nextMatchFindAction",
        "when":"editorFocus && findWidgetVisible"
    },
    {
        "key":"enter",
        "command":"closeFindWidget",
        "when":"editorFocus && findWidgetVisible"
    },
    {
        "key":"ctrl+r",
        "command":"actions.find",
        "when":"editorTextFocus"
    }
3. on a file press ctrl+s, write a word that exists several times and press ctrl-s to search for it
4. press enter to close the Find Widget
5. see that the cursor jumps to the next find!
6. edit keybinding and change the key "enter" no another one
7. repeat the procedure 3. and 4. and see that now it works as intended.

Does this issue occur when all extensions are disabled?: Yes

**Comment by pbgc** [comment]
@rebornix any expectations for this be solved ? I know this cannot be a priority ... but it's a bug :) and prevents the emacs keymap to work as it should.

**Comment by rebornix** [comment]
It no longer exists anymore.
