### ISSUE TITLE
Changing font to Arial changes the Terminal window font to mono space sans serif and not Arial

### ISSUE THREAD

**Issue by LosManos** [Microsoft/vscode#41147]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.5.1

---

Steps to Reproduce:

1. Add/change User settings font to "editor.fontFamily": "Arial"

Expected outcome: The terminal window should have Arial font that looks, somewhat, like the editor's Arial font.
Actual outcome: The terminal window has a sans serif mono spaced font. See attached image.

Reproduces without extensions: Yes

![vscode font problem](https://user-images.githubusercontent.com/1331446/34563371-b1ce828e-f152-11e7-827c-7fde7df1a6db.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35681
