### ISSUE TITLE
Ignore trim whitespace icon really out of place

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#41141]
The trim whitespace icon is really out of place because:
* Larger than surrounding icons
* Lines are bolder than surrounding icons
* Not very clear what it means
* When it is disabled it looks like the equality sign

I am also not convinced if an icon is needed for this since it is very hard to describe visually what this action is supposed to do. Why not put it under the elipses where you can have text so it is much clearer?

fyi @chryw @joaomoreno for ux feedback

![screen shot 2018-01-04 at 12 17 41](https://user-images.githubusercontent.com/1926584/34561227-49ce3c0a-f149-11e7-82f4-792035dbc5df.png)

**Comment by alexandrudima** [comment]
Here is the icon in Visual Studio:

![image](https://user-images.githubusercontent.com/5047891/34610254-f691b46e-f228-11e7-9fb2-39e476279553.png)

**Comment by isidorn** [comment]
There it does not look so much out of place, since their icon design is different.
I would still vote to put it under elipses because we will have a hard time finding a descriptive enough icon.

**Comment by alexandrudima** [comment]
One of these icons is the same (from GitExtensions). Can you tell which one it is ?

![image](https://user-images.githubusercontent.com/5047891/34611393-058d9974-f22e-11e7-9fcd-d1cd243ff9fe.png)

**Comment by isidorn** [comment]
@alexandrudima The one before the last looks like it might be it.

**Comment by alexandrudima** [comment]
@chryw Do we have somewhere a better icon, like this one from Word:

<img width="107" alt="image" src="https://user-images.githubusercontent.com/5047891/34674450-34f0c4ca-f486-11e7-9b5c-3ba176d172c3.png">

**Comment by chryw** [comment]
@alexandrudima We do have that icon for "show/hide paragraph marks". What does "trim whitespace" button do? Is it related to paragraph?

**Comment by alexandrudima** [comment]
@chryw It toggles if trim whitespace should be considered when diffing:

I believe the paragraph icon from Word better communicates the notion of "whitespace"

![kapture 2018-02-05 at 12 01 24](https://user-images.githubusercontent.com/5047891/35806157-da687ce6-0a7e-11e8-9a79-2af417d6ae22.gif)

**Comment by chryw** [comment]
@alexandrudima that still feels weird to me if we use a show/hide paragraph mark icon for trim/ignore whitespace. Because what the button does isn't toggling paragraph mark. Would this icon ![image](https://user-images.githubusercontent.com/7075677/35830573-8be77e08-0a7b-11e8-9910-ee95259a69c1.png) work instead?

**Comment by alexandrudima** [comment]
I believe Word uses the Paragraph mark to show/hide all whitespace, not just paragraph marks:

<img width="119" alt="screen shot 2018-02-06 at 09 45 19" src="https://user-images.githubusercontent.com/5047891/35849677-b1457626-0b22-11e8-9caf-899c22abc694.png">

So, over the years, I have associated that icon more with "whitespace" than with "paragraphs". i.e. I have personally seen that icon more often in Word than in typography / books. That is why I was suggesting that one.

---

IMHO  ![image](https://user-images.githubusercontent.com/7075677/35830573-8be77e08-0a7b-11e8-9910-ee95259a69c1.png) is not more suggestive of "ignore trim whitespace" than what we have today.

**Comment by chryw** [comment]
@alexandrudima ok please see attachment
[Paragraph_vscode.zip](https://github.com/Microsoft/vscode/files/1700280/Paragraph_vscode.zip)

**Comment by alexandrudima** [comment]
Here is how it looks now. It uses opacity to distinguish the toggle. Opacity 0.5 when trim whitespace is ignored, opacity 1 when trim whitespace is not ignored:

![kapture 2018-02-07 at 10 37 58](https://user-images.githubusercontent.com/5047891/35909182-0bf656c8-0bf3-11e8-93b9-d54793c66fa2.gif)

**Comment by isidorn** [comment]
@alexandrudima @chryw looks much better imho. Thanks a lot!
