### ISSUE TITLE
Menus: making a different group a primary group than "navigation" misses separator

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41143]
If you pass a function to `fillInActions` for the `isPrimaryGroup` check which e.g. wants a group with the id "`2_files`" to be primary group, the group is put first, but there is no separator to other groups.

Steps:
* change the [`fillInActions`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/titleControl.ts#L404) call to `fillInActions(this.contextMenu, { shouldForwardArgs: true, arg: this.resourceContext.get() }, actions, group => group === '2_files');`

![image](https://user-images.githubusercontent.com/900690/34562372-6400af86-f14e-11e7-88bf-fbd32a699846.png)

**Comment by jrieken** [comment]
> but there is no separator to other groups.

Which other groups are there? Do you have working code that shows this? All groups in the sense of the menu-service [should be separated](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/browser/menuItemActionItem.ts#L59) but there are still hacks required because of the `Action#order`-crime

**Comment by bpasero** [comment]
Nevermind, I confused the method. Works fine now, for the editor title context menu I am using the groups:
```
1_close
-------
2_files
----------
3_preview
```

One thing we might want to revisit is if navigation is always the first group. For example, for the editor title context menu I would want that 1_close always comes first and navigation maybe below but currently I am not sure if there is a way to enforce that behaviour other than changing 1_close to be navigation (which does not make so much sense since the actions within are all related to closing).
