### ISSUE TITLE
Changing only the case of a file and staging it with another file causes it to not be committed and shows the old filename

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#41145]
- VSCode Version: Code - Insiders 1.20.0-insider (f9115349ef09cfef2bed669680d10ac58b490dce, 2017-12-21T16:27:29.385Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
sort-lines|Tyr|1.4.1
vscode-eslint|dba|1.4.3
gitlens|eam|7.2.0
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.1
flow-for-vscode|flo|0.7.3
intellij-idea-keybindings|k--|0.2.18
debugger-for-chrome|msj|4.0.0
annotator|ryu|0.11.0
vscode-fileutils|sle|2.7.1
---

Changing only the case of a file and staging it with another file causes it to not be committed and shows the old filename git

Steps to Reproduce:

1. Create new two files called `_test1.js` and `_test2.js`.
2. Rename `_test1.js` to `_Test2.js`
3. Open source control panel

EXPECTING: new filename / casing appears

ACTUAL: old filename appears

5. Select both files and stage.

EXPECTING: both files are staged.

ACTUAL: only the non renamed file is staged.  You also can't delete (Discard Changes) the renamed file and it stays "stuck". 

![jan-04-2018 05-09-02](https://user-images.githubusercontent.com/2301847/34562857-6d5e2bda-f10d-11e7-98d9-ac56f165193f.gif)

Reproduces without extensions: Yes/No

**Comment by greggb** [comment]
Seeing this also, was about to open an issue, but found this one in search.

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0

I'm able to stage and commit from an external terminal, but within VSCode the file still references the original name.

**Comment by joshunger** [comment]
@joaomoreno thanks
