### ISSUE TITLE
Terminology in Preferences not matching online docs, difficulty finding things in Settings

### ISSUE THREAD

**Issue by mccreeker** [Microsoft/vscode#41158]
- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:

1. Type a bunch of text inside an html file.
2. Get annoyed when you hit Enter or Tab thinking you're going to a new line or adding an indent when instead the word you just typed changes to the auto-suggested word from the drop-down.
3. Do a web search trying to figure out how to disable this or what it's even called.
4. Find a VS Code page about IntelliSense using terminology and phrases describing features that aren't named the same way in Preferences, Settings, or Keymap - such as "quick info" for Ctrl+Space, which isn't in the Settings json and is called toggleSuggestionDetails in Preferences > Keymap.
5. Get even more frustrated that you can't copy just the Ctrl+Space Command name in Keymap to try to find it in Settings, it instead copies the whole setting block.
6. After chopping out all of that copied setting block to search Settings just for toggleSuggestionDetails, discover it's not even there anyways.
7. Post a GitHub issue about UX-unfriendliness and time-burning difficulty of trying to figure out VS Code settings because there's just no user forum.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Have you tried to type "enter" in `settings.json` search?

**Comment by roblourens** [comment]
From what I understand from https://code.visualstudio.com/docs/editor/intellisense, "intellisense" is a generic term for multiple features. "quick info" is specifically the docs for an item that shows up in the suggestions prompt. 

`toggleSuggestionDetails` is the name of an action that can have a keybinding. `suggestion` is used for the relevant settings, try searching for that. But that exact action name doesn't make sense for a setting name.

It would be useful to be able to copy individual cells in the keybindings editor. Is there an issue for that @sandy081?

Sorry for the frustration. Is https://code.visualstudio.com/docs/editor/intellisense the page you looked at? Can you suggest how we could have explained things better?

**Comment by sandy081** [comment]
@roblourens There is no issue for that. Only possibility is to have a context menu action to copy each cell which does not look nice.

**Comment by mccreeker** [comment]
The point is "quick info" isn't listed anywhere in VS Code that I could see, so trying to look for it always resulted in "nothing found". I was pointing out a disconnect in the documentation and the settings that prevented me from finding what it was talking about (easily).

Thanks for all the explanations, but I posted here to point out how difficult it was to try to figure things out myself due to things not being named the same as the docs or even across different parts of VS Code, making search impossible or unnecessarily difficult. Is there any way that can be fixed? I posted an "issue" because I consider this kind of thing a major time-consuming issue.

Yes I was initially referencing https://code.visualstudio.com/docs/editor/intellisense, but had gone into some sub-pages. There's more references than what I've pointed out that are not findable in VS Code, and different sections like Settings or User Settings or Workspace Settings or other sections just simply have some or many things that refer to the same thing but are named different.

**Comment by roblourens** [comment]
@mjbvz @gregvanl Do you think there are discrepancies between how we describe features in the docs vs in the product? We never use the term "intellisense" in the actual product, I guess because it's a generic umbrella term, where setting/keybinding descriptions point to specific feature names. But another example is that the "quick info" keybinding is called "toggleSuggestionDetails", and just from looking at the docs, it seems hard for a user to connect the dots between the two names. Why not just call it "suggestion details" in the docs?

**Comment by mccreeker** [comment]
Yes, I was pointing out the discrepancies. I haven't taken time to record them all, but there are more than I pointed out here, and it's time-consuming enough just to find what something is called, in documentation, but then be further burdened when that referenced thing is not named that way in the actual program being the documentation is about.

**Comment by roblourens** [comment]
I know you were, that comment was for the other 2 :)

**Comment by john-cj** [comment]
Just as example: `Ctrl+Shift+O` is called "Go to Symbol in File..." in VS Code (Ctrl-K Ctrl-S to verify it), but it's name in docs is "Quick Outline":

> [... open Quick Outline by pressing Ctrl+Shift+O](https://code.visualstudio.com/docs/getstarted/keybindings)

Also, if you go to Menu > Help > Keyboard Shortcut Reference, in the PDF you will see this:

> Ctrl+Shift+F - Show Search (actually it should be named "Search in files")
> Ctrl+Shift+H - Replace in files (it's okay)
> Ctrl-T - Show all Symbols (actually it should be named "SEARCH for Symbols ACROSS FILES")

**Comment by roblourens** [comment]
The search one is ok, it refers to the "View: Show Search" command.

I think the others could be updated, especially "Quick outline" which might be an outdated term. Is that right @mjbvz?

**Comment by john-cj** [comment]
@roblourens Yes, Ctrl+Shift+F is for "View: Show Search" command, but:

- It's also for "Search: Find in Files" command
- Currently it's description is inconsistent with description of Ctrl+Shift+H
- "Search in Files" is more informative for the user.

![search](https://user-images.githubusercontent.com/18004961/38217979-f501cf9a-36d8-11e8-8664-b24f85181430.png)

![search2](https://user-images.githubusercontent.com/18004961/38218244-c1c10f1e-36d9-11e8-91e3-6ce20ccc0b0c.png)

**Comment by roblourens** [comment]
There is a command for each viewlet to show the viewlet. In the keyboard reference they are just listing all those commands. I think it makes sense. I don't think anyone will be confused by what "show search" could possibly mean.

**Comment by roblourens** [comment]
Do you think there's anything to do here @mjbvz? 

https://github.com/Microsoft/vscode/issues/41158#issuecomment-357043415

https://github.com/Microsoft/vscode/issues/41158#issuecomment-378046287
