### ISSUE TITLE
Multi-line paste while zoomed inserts clipboard into wrapped lines more than once

### ISSUE THREAD

**Issue by fractos** [microsoft/vscode#41152]
- VSCode Version: 1.19.1 
- OS Version: Windows 8.1 64-bit, Windows 10 Home 64-bit

Steps to Reproduce:

1. Open a file with lines longer than, say, 80 characters
2. Enable word wrapping
3. Select some text and Copy to clipboard
4. Zoom in with Ctrl-+ such that the lines wrap
5. Using Shift-Alt to select multiple lines, choose a column that a wrapped line has text appearing in twice
6. Note that the cursor appears on the wrapped lines across all rows that the column has content on

![vscode-multiline-paste-issue](https://user-images.githubusercontent.com/657772/34570845-e044a76c-f164-11e7-8809-6e8ddeffc6f8.PNG)

7. When pasting, the clipboard is pasted into all rows including the wrapped content, so some lines will have the pasted contents twice.

Does this issue occur when all extensions are disabled?: Yes

I have a horrible feeling that this was added as a feature.

**Comment by alexandrudima** [comment]
Let's track in #26393

The issue is not about pasting, but about creating multiple cursors over wrapped lines.
