### ISSUE TITLE
implement auto complete HTML tag when insert </

### ISSUE THREAD

**Issue by isaaccentenario** [Microsoft/vscode#41150]
- VSCode Version:
- OS Version: Ubuntu 17.04

Please implement auto complete HTML tag when type </

**Comment by usernamehw** [comment]
Works out of the box for me. What vscode version are you using?

**Comment by aeschli** [comment]
What do you mean by 'insert'?
What you want already is there on typing
![html-complete-close-tag](https://user-images.githubusercontent.com/6461412/34831756-20168dd2-f6e8-11e7-9c88-d7835e2052a7.gif)

**Comment by isaaccentenario** [comment]
This does not work for me. The version I use is 1.19.1. When I type nothing happens
![screenshot from 2018-01-11 12-03-40](https://user-images.githubusercontent.com/9929536/34832075-9e4c35d8-f6c7-11e7-852e-ae2f372b5146.png)

**Comment by aeschli** [comment]
@isaaccentenario Is the editor in 'HTML' mode?
