### ISSUE TITLE
Unable to annotate the block code

### ISSUE THREAD

**Issue by a-little-boy** [Microsoft/vscode#41154]
![2018-01-04 23-38-59](https://user-images.githubusercontent.com/27721311/34571167-c25c1b38-f1a8-11e7-800e-c76a30590d8d.png)

**Comment by a-little-boy** [comment]
I use ctrl+/   and then it turns out to be like this

**Comment by mjbvz** [comment]
Does this still repo if you disable all extensions?

**Comment by a-little-boy** [comment]
@mjbvz thank you

**Comment by mjbvz** [comment]
Did that fix the issue? Any idea what extension may have caused it?

**Comment by a-little-boy** [comment]
@mjbvz    I delete all the extensions and restore the personal settings, then   it is ok

**Comment by mjbvz** [comment]
Thanks. Closing as caused by extension
