### ISSUE TITLE
Failed to save '<filename>.java': The content on disk is newer. Click on Compare to compare your version with the one on disk.

### ISSUE THREAD

**Issue by etem** [Microsoft/vscode#41159]
I'm getting error message `"Failed to save '<filename>.java': The content on disk is newer. Click on Compare to compare your version with the one on disk." ` every few minutes while editing a java file. This happens only when the Java extensions are installed. The opened file is local. 
Auto save is enabled with following settings: 
```
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 200,
```
- VSCode Version: 1.19.1/1.20.0-insider
- OS Version: Fedora 27

Steps to Reproduce:

1. Install `Java Extension Pack` or `Language Support for Java(TM) by Red Hat` extensions.
2. Open a .java file and make some changes. 

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
