### ISSUE TITLE
Disable typing pop-up suggestions not working

### ISSUE THREAD

**Issue by mccreeker** [Microsoft/vscode#41166]
- VSCode Version: 1.19.1
- OS Version: W10

Steps to Reproduce:

1. Type something like $ or <br> in something like a .php file.
2. Watch a bunch of junk pop-up obscuring code or causing you to accidentally add the top suggested item on Tab or Enter, or extra keystroke if nothing's there (like after a break tag).
3. Go to Preferences > Settings > User Settings, add "editor.quickSuggestions": false, save, even restart, watch it be ignored.
4. Try the below block and watch it also fail:
{
    "git.enabled": false,
    "editor.renderWhitespace": "all",
    "editor.insertSpaces": false,
    "editor.detectIndentation": true,
    "editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": false
    },
}

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
I can repro this in php files and not other files.
Adding `"php.suggest.basic": false` to the settings fixes this.

cc @roblourens

**Comment by roblourens** [comment]
Wait, does every extension have to check `editor.quickSuggestions`? Does the go extension do that itself?

**Comment by ramya-rao-a** [comment]
No, extensions don't need to check for `editor.quickSuggestions`.

VS Code shouldn't have triggered suggest and called the php completion provider

**Comment by mccreeker** [comment]
OK I added `"php.suggest.basic": false` to the User Settings file and it worked (though I had to close and re-open VS Code to get it to work).

I'm not sure why this fix requires another PHP-specific setting.

**Comment by roblourens** [comment]
Actually there is another generic setting - `"editor.suggestOnTriggerCharacters": false`. This will prevent it from appearing on trigger characters (`$`, etc).

This is missing from https://code.visualstudio.com/docs/editor/intellisense#_settings, I think it should be mentioned there

**Comment by mccreeker** [comment]
Amazing this needs so many settings set to false to just stop auto-popups... and that the documentation is lagging behind in such a popular hot modern tool.

**Comment by roblourens** [comment]
Just 2 settings should actually be necessary. And well, we tweak the docs every day :)
