### ISSUE TITLE
задача сборки очень долго загружается

### ISSUE THREAD

**Issue by ivansulimenko** [Microsoft/vscode#41161]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.1.1
vscode-gutter-preview|kis|0.12.2
px-to-rem-with-scss|med|1.0.3
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|3.0.3
vscode-html-scss|P-d|0.0.42
local-history|xyz|1.6.2

---

Steps to Reproduce:

1. запустить vs code c gulp файлом и нажать ctrl+shift+b
2. поиск задачи сборки длится 5+ минут! сместо секунд...

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
Please file issues in English, thanks!
