### ISSUE TITLE
Explorer tab tool windows shouldn't appear if they are empty

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#41160]
- VSCode Version: 1.19.1
- OS Version: Windows 10 FCU

Steps to Reproduce:

1. Install `XML Tools` and `Git History (git log)` - these two extensions add tool windows
2. Open up a simple text or md file.
3. Note that there are three (empty) tool windows that even when collapsed take up VALUABLE vertical space in the Explorer tab:

![image](https://user-images.githubusercontent.com/5177512/34581560-2344b622-f14e-11e7-9744-92029121c5d1.png)

While this is perhaps something each individual extension author could fix, I think VSCode needs to be smarter by not display empty tabs that have no commands (tool bar buttons).  Perhaps the API needs to be updated to only activate these tool windows when appropriate.  IE I don't need to see the XML Document tool window unless I'm viewing an XML document - duh.

Does this issue occur when all extensions are disabled?: NO

**Comment by Gruntfuggly** [comment]
Even better, would be to allow tree views to expand/shrink according to their content (within reason), unless specifically resized by the user.

**Comment by sandy081** [comment]
Extension authors can already control the visibility of the view progrmmatically by providing the when clause. Refer [here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews). 

Allowing a new way to control the same will be cumbersome.
