### ISSUE TITLE
Indentation: guessed 4 spaces when it should be 3?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4116]
This might be intentional because we assume that indentation is always a multiplication by 2, but when I have a file with 3 spaces as indent and run the automated guessing, I end up with 4 spaces guessed. Similar 5 spaces gets guessed to 4 spaces as well.

![image](https://cloud.githubusercontent.com/assets/900690/13742150/802da060-e9da-11e5-8d7a-23e3e4a3454a.png)

Checking with Sublime they seem to not detect anything and fallback to the default configured.

Refs: https://github.com/Microsoft/vscode/issues/3922

**Comment by alexandrudima** [comment]
This is by design, the guessing code only guesses 2, 4, 6 or 8. Update the test plan to reflect this.

**Comment by Poorchop** [comment]
Indentation isn't even being guessed correctly for me at all. I loaded a script that consists purely of tabbed indentations, but Code guessed four spaces instead and I have to manually change this setting every time I restart the program.

I've only tested with [this script](https://github.com/TingPing/plugins/blob/master/HexChat/highlight.lua) so far. To replicate, clone the entire repository and open the cloned plugins folder. Proceed to open the script in question and you will see that it incorrectly guessed four spaces. Tested in 1.1.0 and 1.1.1.

**Comment by alexandrudima** [comment]
@Poorchop I have cloned the repository at https://github.com/TingPing/plugins and opened `HexChat/highlight.lua`. The indentation is guessed as Tabs@4.

Can you please check your user settings if you change `editor.detectIndentation` to `false` or if this reproduces when running VS Code with `code --disable-extensions`?

**Comment by Poorchop** [comment]
Good call. The problem was with the EditorConfig extension and the issue is being tracked [here](https://github.com/editorconfig/editorconfig-vscode/issues/51). I'll keep my extensions in mind next time I notice a problem and try running vanilla first before reporting an issue. Thanks.
