### ISSUE TITLE
There is no line break in a markdown file

### ISSUE THREAD

**Issue by luis-fonseca** [Microsoft/vscode#41163]
- VSCode Version: 1.19.1
- OS Version: Mint Linux 18.3

Steps to Reproduce:

1.  Changing the following settings has no effect on a markdown file.
```
"editor.rulers": [100],
"editor.wordWrapColumn": 100,
"editor.wordWrap": "wordWrapColumn"
```
2. There is no line break when it reaches the specified character limit. However, a pure text file works correctly.

The first image is a markdown file.
![captura de tela em 2018-01-04 19-13-33](https://user-images.githubusercontent.com/5729008/34584591-887197e2-f183-11e7-804b-e92e3c57642b.png)

The second image is a flat file.
![captura de tela em 2018-01-04 19-14-17](https://user-images.githubusercontent.com/5729008/34584612-97a7486a-f183-11e7-8972-9132da4d8ebb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Markdown contributes a default language specific setting for wordwrap:

```json
  "[markdown]": {
    "editor.wordWrap": "on"
  }
```

To override this, add:

```json
"[markdown]": {
    "editor.wordWrap": "wordWrapColumn"
}
```

to your user settings
