### ISSUE TITLE
Integrated Terminal turns to snow when waking from suspend (Ubuntu 16.04/16.10)

### ISSUE THREAD

**Issue by JackKenney** [Microsoft/vscode#41164]
- VSCode Version: 1.19.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open VSCode
2. Open Integrated Terminal
3. Suspend computer
4. Wake computer

Screenshot:
![studiocodeerror](https://user-images.githubusercontent.com/8908922/34585098-63518bbe-f16c-11e7-956b-d5afb5270c96.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by marcellobarile** [comment]
It happens to me as well on Ubuntu 17.04 / NVIDIA GTX 1070 (drivers ver. 387.34).
I'm able to get it back removing the terminal and opening a new one from the "View" menu. When the issue happens also the minimap seems to be affected, reloading the internal terminal fixes both though.

**Comment by JackKenney** [comment]
I do have an NVIDIA card, GeForce GTX 750 (driver: 384.90)

**Comment by marcellobarile** [comment]
ah ah interesting... let's see what the internet says about some similar issue...

**Comment by Tyriar** [comment]
This is an upstream Chromium issue and will happen with any `HTMLCanvasElement`
