### ISSUE TITLE
Import quick fix not working

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#41168]
- VSCode Version: Code - Insiders 1.20.0-insider (1903689569101cef7dedf612d9100a2141cb14f0, 2018-01-04T07:36:13.087Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
json-to-ts|Mar|1.5.4
material-icon-theme|PKi|3.2.1
path-intellisense|chr|1.4.2
githistory|don|0.2.3
tslint|eg2|1.0.24
auto-rename-tag|for|0.0.15

(2 theme extensions excluded)

---

Steps to Reproduce:

1. In a file that has a quick fix to add an import, select the quick fix.

<img width="579" alt="screen shot 2018-01-04 at 7 31 01 pm" src="https://user-images.githubusercontent.com/13488/34590596-de3e26b6-f185-11e7-8755-2faeca53898c.png">

2. No import statement is added to the file, menu selection is ignored

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Fixed by e8c76c4617fcc7b932455606055f83837839f247
