### ISSUE TITLE
How to disable function hover pop-up without disabling anything else, and preferably to only activate on demand with a keyboard shortcut?

### ISSUE THREAD

**Issue by mccreeker** [Microsoft/vscode#41162]
Maybe I'm searching wrong, StackOverflow is always a major risk of losing reputation for valid questions: https://stackoverflow.com/search?q=%5Bvisual-studio-code%5D+disable+function+hover+pop-up

- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Create a function in a .php file.
2. Innocently hover the mouse cursor over it at some other point in time without thinking anything of it.
3. Watch a pop-up cover the text you're reading or block what you were going to click.
4. Churn through settings and the web to find how to disable this, discover multiple posts about it with suggestions that don't work (anymore).
5. Try suggestion to put `"editor.hover": false,` in your User Settings, watch it put a green squiggly underline under it that when hovered over says it's an "Unknown configuration setting".
6. Find nowhere else but a GitHub Issue to post the problem.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/15667

**Comment by mccreeker** [comment]
`"editor.hover": false,` randomly started working after saving other settings... some of which didn't stick the first save either; not sure how to save properly.

Now I'd still like to see the pop-up on demand, but holding Ctrl and hover or clicking doesn't cause it to appear, so not sure how to get it to appear with the hover auto-popup disabled... 

PHPStorm allows this when holding Ctrl and hovering, I don't see a reason why VS Code shouldn't. Pop-up boxes should be available on demand (as a disable-able option of course) when if they're not automatic, this seems like common sense.

**Comment by usernamehw** [comment]
You can see from this issue https://github.com/Microsoft/vscode/issues/15667 that people want it, but now it's impossible. `"editor.hover": false,` works after editor reload and prevents hover from popping up even when triggered by command `editor.action.showHover`. What's left? Vote and wait...

**Comment by mccreeker** [comment]
The solution actually isn't working. I've tried it twice according to the instructions. Now what?
