### ISSUE TITLE
explorer context menus not firing commands in Insiders

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#41167]
![image](https://user-images.githubusercontent.com/1487073/34590012-fbd78d6a-f168-11e7-83f4-c203d5789b99.png)

Does this issue occur when all extensions are disabled?: Yes

Problem: Explorer context menus are not firing commands in Insiders, works fine in stable.

To reproduce:

1. scaffold out a new extension using `yo code`
2. add the following to `contributions` in `package.json`

```json

        "menus": {
            "explorer/context": [
                {
                    "command": "extension.sayHello",
                    "when": "explorerResourceIsFolder == true",
                    "group": "zzz_@1"
                }
            ]
        }
```

3. `F5` to run the extension
4. Open a folder, right click on an empty space or a folder and choose `Hello World`

Result: Nothing happens
Expected: the `sayHello` command to be executed

**Comment by bpasero** [comment]
@isidorn probably the same as https://github.com/Microsoft/vscode/issues/41157

**Comment by isidorn** [comment]
@chrisdias thanks for the nice issue report. However this is a duplicate
