### ISSUE TITLE
Java Extension... java.home problem

### ISSUE THREAD

**Issue by 98-f355-f1** [Microsoft/vscode#41176]
- VSCode Version: Code - Insiders 1.20.0-insider (5153c9aa420bc235b463b773881b2871c8d22566, 2018-01-05T05:13:51.780Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: the listing length exceeds browsers' URL characters limit
---
I am new to using Java with Visual Studio Code... I get this error and it's annoying.  However, it seems that the programs are compiling and working properly despite this warning.  I want to get rid of this warning.  It comes from the Red Hat Java extension.

I have gone into the folder and placed the file directory into the extensions.json file, but it seems to not fix it.  I have both the RedHat and Oracle versions of the Java 9.0 SDK.  I use another IDE for Java, but would rather use the VSC.

Steps to Reproduce:
1. Open the VSC
2. Open any .java file, and the error shows up
3. Once I click it away, it goes away, until I compile and run a .java file again.  (it doesn't seem to affect the operations).. it's annoying make it go away.

Reproduces with extensions: Yes
![capture](https://user-images.githubusercontent.com/28711409/34601060-9c4f4af0-f1b7-11e7-9556-11d66c4a03f7.PNG)

**Comment by rebornix** [comment]
Please file this issue against the Java extension you are using, thanks!
