### ISSUE TITLE
Crash on Ubuntu when open containing folder

### ISSUE THREAD

**Issue by ucandoit1010** [Microsoft/vscode#41173]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-40-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.1
php-intellisense|fel|2.2.4
php-ci|sma|0.2.8

---

Steps to Reproduce:
When open containing folder.
Crash always happen !

1.https://ibb.co/e3PHjw
2.https://ibb.co/hsYtPw

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Can you close all instances of VS Code and then run `code --verbose` from a terminal and check the output after the crash?

**Comment by ucandoit1010** [comment]
Here is the message.
Force quit vs code , then run code --verbos.

https://imgur.com/a/Ocz8y

**Comment by Tyriar** [comment]
@ucandoit1010 are you normally running using sudo? If so that's probably why it doesn't work, we don't really support running under sudo.

**Comment by ucandoit1010** [comment]
OK , I run this command :
sudo code --user-data-dir="~/.vscode-root"

**Comment by Tyriar** [comment]
@ucandoit1010 still, the reason this is probably happening is because you're running as sudo and running as sudo has its own quirks. I recommend backing up your settings, keybindings and writing down your extensions and then deleting your user data and extensions directories. These directories should be at:

```
$HOME/.config/Code/User/
$HOME/.vscode/extensions/
```

**Comment by Tyriar** [comment]
If you need editing of root-owned files, we have a change coming to bring up an admin dialog

**Comment by ucandoit1010** [comment]
Thank you sir !
