### ISSUE TITLE
display indentation incorrectly

### ISSUE THREAD

**Issue by mickeydonkey** [Microsoft/vscode#41170]
- VSCode Version: 1.19.1
- OS Version: fedora 25

Steps to Reproduce:

1.
open following file with vscode(left) and vi(right):
[sample_indent_error.txt](https://github.com/Microsoft/vscode/files/1605371/sample_indent_error.txt)

![indent_error](https://user-images.githubusercontent.com/12562760/34593587-bda095ac-f206-11e7-9611-a992154eb870.PNG)

2.
 
Does this issue occur when all extensions are disabled?: Yes

**Comment by ArthurCose** [comment]
Check your tab size on the bottom right, it looks like it's currently configured to 4 spaces rather than 8.

**Comment by mickeydonkey** [comment]
Yes, I have to configure Vim a bit ,`:set tabstop=4` makes code on the right hand side looks the same as that in vscode. Thank you @ArthurCose
