### ISSUE TITLE
内置终端在中文环境下执行code -h命令显示乱码

### ISSUE THREAD

**Issue by gaohuanjiang** [Microsoft/vscode#41177]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
xml|Dot|1.9.2
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
docomment|k--|0.0.17
Go|luk|0.6.70
python|ms-|0.9.1
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
vscode-icons|rob|7.19.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
> Built-in terminal in the Chinese environment code -h command to display garbled

@gaohuanjiang Does this happen in [VS Code insiders](https://code.visualstudio.com/insiders/)? Can you provide a screenshot of the problem

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/40238
