### ISSUE TITLE
underline in terminal doesn't display, looks just like space

### ISSUE THREAD

**Issue by mickeydonkey** [Microsoft/vscode#41171]
- VSCode Version: 1.19.1
- OS Version: fedora 25
 
Steps to Reproduce:

1. open a terminal 
2. input some command with underline "a_b_c" It looks like "a b c"

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/35901

**Comment by mickeydonkey** [comment]
Thx, close it now.
