### ISSUE TITLE
SCM: blue border around entire view when clicking on viewlet

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41174]
Seeing this today running out of sources:

![before](https://user-images.githubusercontent.com/900690/34600481-0615ec92-f1f8-11e7-8d82-fa6400cb6230.gif)

**Comment by joaomoreno** [comment]
These outline rules are a pain.

**Comment by joaomoreno** [comment]
OK this was a crazy fix!

Problem is [this rule](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/media/shell.css#L128) which establishes a `:before` child with `position: absolute` and `width: 100%; height: 100%`... this can only work if the list is `position: relative`...
