### ISSUE TITLE
{literal} behaves weird

### ISSUE THREAD

**Issue by anacierdem** [Microsoft/vscode#41183]
- VSCode Version: Version 1.19.1 (1.19.1)
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:

1. Put
```
{literal}
  <style></style>
{/literal}
```
inside an HTML document.

2. Html is not interpreted and not highlighted.

Does this issue occur when all extensions are disabled?: No

`{literal}` is used in Smarty's tpl files. I also have `"files.associations": {"*.tpl": "html"}` in my configuration but the issue is the same for .html files.

Expected outcome:

Html should be highlighted and `{literal}` should be interpreted as text.

**Comment by aeschli** [comment]
Most template languages are not really HTML, but there seems to be some bug with `{literal}` as element body:
An other example: `<div>{literal}</div>`

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#78

**Comment by anacierdem** [comment]
Updated;

Does this issue occur when all extensions are disabled?: Yes

'No' was a mistake previously
