### ISSUE TITLE
Missing package in debugger extension

### ISSUE THREAD

**Issue by ncannasse** [Microsoft/vscode#41182]
When running a debugger extension which has either a missing package `require('not_installed_package')` or a package using a native extension that has not been recompiled for Electron - for instance `require('deasync')` - VSCode will only report the following error 

```js
"The process of debugger adapter has terminated in an unexpected manner"
``` 

It would be very helpful to also print the process stdout/stderr which should give more information about the actual underlying issue.

**Comment by isidorn** [comment]
@ncannasse do you see an error message in the console if you F1 > developer tools
We might have decided to deliberetly not show these messages, since they are only for extension developers and maybe more data is seen in the console. Please check there

**Comment by ncannasse** [comment]
I checked in Developer Tools, the same message is displayed with a vscode stack trace, but no other trace is output there.

**Comment by isidorn** [comment]
And what errors can you see in your `process.stderr`that vscode does not seem to show?
If you run vscode, open developer tools, put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L440) do you see the `socket.on('error'`being hit? And do you see the message which VSCode seems to hide

**Comment by isidorn** [comment]
Also let's continue the discussion here https://github.com/Microsoft/vscode/issues/41190
