### ISSUE TITLE
javascript.format.insertSpaceBeforeFunctionParenthesis doesn't work

### ISSUE THREAD

**Issue by satowine1** [Microsoft/vscode#41181]
- VSCode Version: 1.19.1
- OS Version: Windows 7

Steps to Reproduce:

1. Add javascript.format.insertSpaceBeforeFunctionParenthesis : true to personal settings
2. Write, for example:
`a.forEach(){
//some code
}
`

Expected outpt:
`a.forEach () {
//some code
}`
Real Output:
`a.forEach(){
//some code
}
`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This setting controls the space between `function ()`, not the space before a function call paren. We don't have built-in formatting support for adding a space before function call parens. Try using one of the other js/ts formatting extensions for more advanced formatting options like that
