### ISSUE TITLE
Cannot write @ or # symbols

### ISSUE THREAD

**Issue by jorgegonzalezperez** [Microsoft/vscode#41185]
- VSCode Version: Code - Insiders 1.20.0-insider (c4065a8ba5261456338f850a37e67732d98bf57a, 2018-01-05T08:06:27.790Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.1.4
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.0
vscode-angular2-files|ale|1.3.10
html-class-suggestions|And|1.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
tslint|eg2|1.0.24
LogFileHighlighter|emi|1.2.0
auto-rename-tag|for|0.0.15
Angular2|joh|2.11.2
indent-rainbow|ode|0.7.2
material-icon-theme|PKi|3.2.1
vscode-css-peek|pra|2.0.3
trailing-spaces|sha|0.2.11
code-spell-checker|str|1.6.2
code-navigation|vik|0.2.0
html-css-class-completion|Zig|1.15.0

---

Steps to Reproduce:

1. Press AltGr + 2 or AltGr + 3
2. Nothing happends

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Which commands are bound to the desired key combination?

You can search for "alt+2", "ctrl+alt+2", "alt+3", and "ctrl+alt+3" and then remove those keybindings.

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by juanpedrob9** [comment]
@alexandrudima Actually I have the same problem as @jorgegonzalezperez  with a French Canadian layout, I did like you said and removed Alt+1/2/3 shortcuts but I still can't type any "±,@£" with Alt-Car + 1/2/3.  Any other suggestions ? It started after an update last week.

Windows 10 Pro 16299
Version 1.20.0-insider
Commit b811600ecc57992a82a1f50ed9bf128065bc8787
Date 2018-01-08T09:42:12.918Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by alexandrudima** [comment]
Since about a week, we ship with default bindings for `ctrl+alt+1/2/3`, which is wrong.

https://github.com/Microsoft/vscode/issues/41196#issuecomment-355973833

Fixed in https://github.com/Microsoft/vscode/issues/41196 by @bpasero

A fix will come out soonish (~1 day)
