### ISSUE TITLE
Implement toggle in shortkeys of left bar

### ISSUE THREAD

**Issue by lucini** [Microsoft/vscode#41186]
Ex: Explorer - Ctrl+Shift+E

Pressing first time Show Explorer, second time Hide Explorer.

**Comment by isidorn** [comment]
Fair feature request, not so passionate about doing it.
In the meantime please use Cltr + B

**Comment by ryanolsonx** [comment]
I think that this feature would be great to have.

**Comment by ebynum** [comment]
My current solution for this (for the Explorer Viewlet) adds the following keybinding (in keybindings.json):

    {
        "key": "cmd+shift+e",
        "command": "workbench.action.toggleSidebarVisibility",
        "when": "explorerViewletVisible && explorerViewletFocus"
    }

1. When the Explorer Viewlet is not currently visible, it shows (and focuses) the viewlet. [Default behavior.]
2. When the Explorer Viewlet is visible, but not focused, it focuses the viewlet. [Default behavior.]
3. When the Explorer Viewlet is visible and focused, it hides the viewlet. [New behavior.]

A similar technique is available for the Search Viewlet.

However, the ability to detect the visibility/focus of the Extensions, Debug, and Source Control Viewlets is not currently presented, and has been requested in issues #41276, #41278, and #41280.

**Comment by isidorn** [comment]
Great. Closing as there is a solution for this then
