### ISSUE TITLE
There was a mess in markdowm

### ISSUE THREAD

**Issue by FourEyebrowXiake** [Microsoft/vscode#41187]
![image](https://user-images.githubusercontent.com/18180417/34611545-ef942380-f260-11e7-9eb6-2988e1457701.png)

file address：https://github.com/FourEyebrowXiake/JianLi/blob/master/README.md
The file was created in atom. I open it in vscode for editing. this is markdom preview in vscode:
![image](https://user-images.githubusercontent.com/18180417/34611749-af9f1d10-f261-11e7-9229-4c2900e9cd98.png)
It is normal in  local preview, but When uploaded to github, it went awry

**Comment by mjbvz** [comment]
Seems like a issue with github since it works in VS Code, right?

**Comment by FourEyebrowXiake** [comment]
right,  Working properly in vscode.

**Comment by mjbvz** [comment]
Ok, closing as external since this seems unrelated to vscode
