### ISSUE TITLE
Indentation: Weird indentation in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4119]
I have the default settings and a file like this with 6 leading spaces:

```
      "foo": "bar"
```

The status bar indicates to me that pressing tab will insert 1 tab, but when I press tab on the next line, I get mixed tab/whitespaces:

![image](https://cloud.githubusercontent.com/assets/900690/13742697/9ca5ab72-e9dd-11e5-9a8c-54f23e3f9f70.png)

Refs: https://github.com/Microsoft/vscode/issues/3922

**Comment by alexandrudima** [comment]
This is by design. Pressing Tab on an empty line is implemented "smart". We do not have a setting to turn this off.

It brings indentation to the previous indented line or if the previous indented line ends with `{`, it brings indentation to the previous indented line + 1 indent, etc.

**Comment by alexandrudima** [comment]
In this case specifically, the previous indent was 6 spaces. The indent picks up that it should add 6 spaces, but since it is configured with tabs, it turns as many of those into tabs as possible, hence the 1 tab + 2 spaces.

**Comment by alexandrudima** [comment]
It has to do mixed whitespace because of the JSDoc case, e.g.:

![image](https://cloud.githubusercontent.com/assets/5047891/13742793/520f32a8-e9de-11e5-8040-46d01a5d37d6.png)

Where pressing Enter inserts 1 tab and 1 space. Then the language regex rules kick in and append a `* `

**Comment by alexandrudima** [comment]
@bpasero I could make it so that pressing tab never inserts mixed whitespace, but as shown above, this might break other use-cases (such as JSDoc) where mixed whitespace is desired.

So if you have any ideas...

**Comment by bpasero** [comment]
i am not a strong enough user of this feature, lets see what community says
