### ISSUE TITLE
git.stage custom keybinding not staging file when selecting using arrow keys in source control

### ISSUE THREAD

**Issue by cevhyruz** [Microsoft/vscode#41191]
- VSCode Version: Code 1.19.1 
- OS Version: Linux x64 4.12.0-kali1-amd64
- Extensions: none
---
I'm not sure if this is a bug or not. I had ` {
  "key": "shift+s",
  "command": "git.stage"
} ` custom keybinding and it works okay if you click the file using the mouse or press enter when it is highlighted before performing the keyboard shortcut 

Steps to Reproduce:

1. modify some files and go to source control.
2.navigate through files using arrow keys and perform the keyboard shortcut.

**Comment by joaomoreno** [comment]
This command can't pick up the selection from the SCM panel, unfortunately. We don't support it.
