### ISSUE TITLE
Disabling a keybinding using Alt does not disable it for Right Alt

### ISSUE THREAD

**Issue by mickael-mounier** [Microsoft/vscode#41196]
- VSCode Version: Code - Insiders 1.20.0-insider (c4065a8ba5261456338f850a37e67732d98bf57a, 2018-01-05T08:06:27.790Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-refresh-html|baj|0.0.2
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
vsc-material-theme|Equ|1.2.0
vscode-todo-plus|fab|1.7.2
Go|luk|0.6.70
vscode-todo-parser|min|1.9.1
python|ms-|0.9.1
azure-account|ms-|0.2.2
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
vscode-code-outline|pat|0.0.12
vscode-docker|Pet|0.0.22
vscode-icons|rob|7.19.0
code-spell-checker|str|1.6.2

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Go to keyboard shortcuts and delete the Alt+3 shortcut for the `workbench.action.openEditorAtIndex3` action
2. In an editor, press Right Alt + 3
3. Notice the action being executed

I upgraded my insiders version today and this problem appeared. If these shortcuts are new then the bug might be present in older versions.

Is there a workaround for this? I'm using a French keyboard layout where Right Alt + number is required for many different things.

I've reproduced this bug successfully with US layout and extensions disabled.

Thanks!

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@shobhitchittora wanna do that change?

**Comment by shobhitchittora** [comment]
Sure. 😎👍

**Comment by bpasero** [comment]
@shobhitchittora it looks like we typically use `Shift+Alt` instead of `Ctrl+Alt` on Windows as a workaround. However unfortunately `Ctrl+Alt+1` is already taken (the other `+2` and `+3` are not).

**Comment by bpasero** [comment]
@shobhitchittora fyi I went ahead and fixed it since it is rather critical for our insiders users. I changed to use `Shift` instead of `Ctrl` on Windows and Linux.

**Comment by shobhitchittora** [comment]
@bpasero  Thanks for pointing that out. So I see there are two options - 

1. Replace `Ctrl+Alt+1` with `Shift+Alt+1` ( which is not taken as per my search ).
2. Remove primary key binding, and allow the user to set his/her own binding as per @alexandrudima.

Which should I go with?

**Comment by shobhitchittora** [comment]
Adding to my previous comment, `primary` is a required key in keyBinging Interface.

https://github.com/Microsoft/vscode/blob/2bab83a097135cf8c2a1ca1498bb8906f06d2cb3/src/vs/platform/keybinding/common/keybindingsRegistry.ts#L22

**Comment by bpasero** [comment]
@shobhitchittora no action required from you as per https://github.com/Microsoft/vscode/issues/41196#issuecomment-356232351

**Comment by shobhitchittora** [comment]
@bpasero Happy to follow up in case.
