### ISSUE TITLE
VSCode does not start on Azure VMs running Ubuntu 16.04

### ISSUE THREAD

**Issue by bonggeek** [Microsoft/vscode#41197]
- VSCode Version: All versions
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Create a Ubuntu 16.04 VM on Azure
2. Enable remote desktop 
3. Install VSCode
4. Connect over remote desktop and launch VSCode
5. VSCode will not come up, where other programs will work fine

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3451
