### ISSUE TITLE
Breakpoint not hit in imported file (using Typscript and node.js)

### ISSUE THREAD

**Issue by TinusScheppers** [Microsoft/vscode#41198]
It seems the breakpoints in imported files are not hit when there 'parent' does not contain a breakpoint.

- VSCode Version: 1.19.1
- OS Version: Windows 10

Steps to Reproduce:

1. Setup new project with this setup (same results if source files are in root):
![afbeelding](https://user-images.githubusercontent.com/2527506/34625513-3b7b4bb4-f259-11e7-8a9b-35164749a265.png)

 
2. tsconfig.json
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "bin",
        "sourceMap": true
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

3. launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\src\\index.ts",
            "preLaunchTask": "tsc: build - tsconfig.json",
            "outFiles": [
                "${workspaceFolder}/bin/**/*.js"
            ],
            "internalConsoleOptions":"openOnSessionStart"
        }
    ]
} 
```
4. tasks.json
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

5. app.ts (break on console.log):
```ts

class App {
    public start() {
        console.log("Test App");     
    }
}

export default new App()
```

6. index.ts:
```ts
import app from './App'

console.log("Test Index")
app.start()
```

If I place a breakpoint in the app.ts file it is not hit, if I also break in index.ts (doesn't matter where) and then debug the breakpoint in app.ts is hit. After then removing the breakpoint from index.ts (leaving the app.ts) and debugging again the breakpoint in app.ts is hit! Debugging again (no changes to breakpoints) and no breakpoint is hit.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Which version of Node are you using?

**Comment by TinusScheppers** [comment]
The version is v8.9.0

**Comment by roblourens** [comment]
Can you try this in 1.20? There was a bug fixed that is probably related.
