### ISSUE TITLE
Cannot read property 'cacheKey' of undefined

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#41193]
- VSCode Version: Code - Insiders 1.20.0-insider (5153c9aa420bc235b463b773881b2871c8d22566, 2018-01-05T06:16:44.455Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Go to a repository.
2. `code-insiders .`
3. Use ctrl-p to navigate to some file.
4. An error message appears: `Cannot read property 'cacheKey' of undefined`.
5. The error doesn't happen if I open a file with the explorer.

**Comment by andy-ms** [comment]
The error also happens if I hit `ctrl-p`, type a letter, then hit `escape`. So it's not an error when opening a file but when closing the `ctrl-p` menu.

**Comment by julianlam** [comment]
Happening to me as well. I'm not sure if it's related, but I also can no longer `Ctrl-P` to find a file by successively typing parts of directory names.

**Comment by roblourens** [comment]
This was fixed in https://github.com/Microsoft/vscode/commit/c4065a8ba5261456338f850a37e67732d98bf57a, and insiders was updated again, so you should get the fix if you update again.
