### ISSUE TITLE
Continuing issue with heroku login with invisible text

### ISSUE THREAD

**Issue by hojungan** [Microsoft/vscode#41195]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. heroku login on integrated terminal
**texts are not visible, including path name**
**Issue occurred after update back in November 2017, VS Code is up to date version 1.19.1 **
**Re-installing heroku cli proved to be only temporary fix as this issue re-occurs constantly**

![vscodeherokuissue1](https://user-images.githubusercontent.com/25507659/34622922-1b9404b2-f21d-11e7-9501-1b5729c61ef9.png)
![vscodeherokuissue2](https://user-images.githubusercontent.com/25507659/34622923-1ba65f90-f21d-11e7-9046-bc077ee62c02.png)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
