### ISSUE TITLE
OS X: VS Code does not honor locale

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4120]
VSCode 0.10.12-alpha
OS X 10.11.3

- switch to German:
![2016-03-14 12-09-53](https://cloud.githubusercontent.com/assets/1898161/13742718/b36122c4-e9dd-11e5-93dc-771ec418e443.png)
- launch VS Code from Finder

Observe: VS Code UI is still in English

**Comment by dbaeumer** [comment]
@joaomoreno I move this to you. The problem is the missing i18n folders in the app bundle for electron.

**Comment by joaomoreno** [comment]
This is fixed already.

**Comment by joaomoreno** [comment]
Make sure you get the latest `node_modules`.
