### ISSUE TITLE
Use key as prefix in snippets without prefix

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#41205]
As I see this snippet (without prefix) doesn't work:
```javascript
{
  "tick": {
    // "prefix": "check",
    "body": "✅"
  },
}
```
Would be nice to back it up using the key (`tick` here).

Logic now:
```javascript
trigger: "prefix"
description: "description" ==> "key"
```
Logic after:
```javascript
trigger: "prefix" ==> "key"
description: 
if ("prefix") /* the same as above */ "description" ==> "key"
else /* no prefix */ "description" ==> "" /* empty */
```
------ 
I guess it will be only useful to people who never writes (or uses) descriptions:
```javascript
{
  "tick": { "body": "✅" },
  "log": { "body": "console.log($1)"}
}
```
---------
  Maybe going even further:
```javascript
{
  "tick": "✅",
  "log": "console.log($1)",
  "for": [
    "for ($1; $2; $3) {",
    "\t$4",
    "}$0"
  ]
}
```

**Comment by jrieken** [comment]
Yeah, not yet convinced... I am OK with not requiring the prefix but I'd then only show the snippet in the "Insert Snippet" command and not when having a prefix

**Comment by usernamehw** [comment]
It would defeat the purpose of such snippet for me.
