### ISSUE TITLE
Git footer options are not showing up on latest daily build

### ISSUE THREAD

**Issue by johnroper100** [Microsoft/vscode#41203]
Since I updated to the latest daily build of code-insiders, the git branch indicator and the button to push/pull updates have disappeared from the footer.

- VSCode Version: 1.20.0-insider c4065a8ba5261456338f850a37e67732d98bf57a
- OS Version: Pop!_OS (ubuntu) 17.10

Steps to Reproduce:

1. Open a project that uses git

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/40851
