### ISSUE TITLE
Can we switch default "editor.tabSize" from 4 to 2 for indentation?

### ISSUE THREAD

**Issue by trivikr** [Microsoft/vscode#41200]
I noticed that VSCode adds default `editor.tabSize` as 4
Is there a reason for doing this?

I went through some popular JavaScript projects, and noticed that all of them use 2 spaces for indentation:
* Vue https://github.com/vuejs/vue/blob/dev/src/server/render.js
* React https://github.com/facebook/react/blob/master/packages/react/src/React.js
* Yarn https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js
* Electron https://github.com/electron/electron/blob/master/tools/get-endianness.js
* React Native https://github.com/facebook/react-native/blob/master/local-cli/util/assertRequiredOptions.js
* Redux https://github.com/reactjs/redux/blob/master/src/combineReducers.js
* Bootstrap https://github.com/twbs/bootstrap/blob/v4-dev/js/src/alert.js
* d3 https://github.com/d3/d3/blob/master/test/d3-test.js

When it comes to TypeScript projects, they also use 2 spaces for indentation:
* stimulus https://github.com/stimulusjs/stimulus/blob/master/scripts/dist-to-packages.js
* majestic https://github.com/Raathigesh/majestic/blob/master/src/main/menu.ts
* ant-design https://github.com/ant-design/ant-design/blob/master/scripts/sort-api-table.js
* angular https://github.com/angular/angular/blob/master/tools/check-environment.js
* deeplearnjs https://github.com/PAIR-code/deeplearnjs/blob/master/src/environment.ts
* loklak_search https://github.com/fossasia/loklak_search/blob/master/src/main.ts

Only Microsoft projects seem to use 4 spaces for indentation (may be because of C# influence?):
* VSCode https://github.com/Microsoft/vscode/blob/master/src/bootstrap.js
* TypeScript https://github.com/Microsoft/TypeScript/blob/master/src/server/editorServices.ts

I noticed that popular JavaScript formatters/standards use 2 spaces for indentation:
* Prettier https://prettier.io/docs/en/options.html#tab-width
* Standard https://github.com/standard/standard#the-rules

Is the value of `editor.tabSize` 4 because VSCode is used for other languages (like Python) where 4-spaces is a standard?
If yes, can language specific indentation setting can be created (say `javascript.tabSize`)?

**Comment by usernamehw** [comment]
```json
"[javascript]": {
  "editor.tabSize": 2
}
```

**Comment by trivikr** [comment]
Thanks @usernamehw, can the following code be added as default settings in VSCode?
```
"[javascript]": {
  "editor.tabSize": 2
}
```

**Comment by usernamehw** [comment]
I'm not the one to decide this.

**Comment by mjbvz** [comment]
1. Four spaces is a reasonable default IMO. It is not more or less right than 2 space indentation
1. You can very easily change it 
1. Changing the default now would be super painful, as operations like format would suddenly start reformatting documents for any user that has not set `editor.tabSize`
