### ISSUE TITLE
The Insider's Edition update1.20.0-insider broke my snippet extensions

### ISSUE THREAD

**Issue by TreTuna** [Microsoft/vscode#41207]
- VSCode Version: Code - Insiders 1.20.0-insider (c4065a8ba5261456338f850a37e67732d98bf57a, 2018-01-05T07:58:53.336Z)
- OS Version: Darwin x64 17.3.0
- Extensions: https://marketplace.visualstudio.com/items?itemName=xabikos.ReactSnippets
---

Steps to Reproduce:

1. Have React Snippets extension installed
2. Updated to today's build of VSC Insider's edition
3. rcc -> should have created a React Class Component, instead, it now autocompletes to "RTCIceCandidate"
4. The snippets don't even show up in the drop-down options anymore

Gif showing that it works in regular VSC but not in newest update of Insider's edition:
https://monosnap.com/file/ptlhT48QGhBxvoeCRyRjwVh50WuYbG

When I noticed this problem I immediately tried on my other Mac that still had the previous version of Insider's on it and everything still worked there, as soon as I updated it, that one broke too. 

Reproduces without extensions: Yes - Disabled all extensions except for the snippets extensions I'm using. Tried each one individually and none of them work anymore

**Comment by jrieken** [comment]
@TreTuna Can you check what the 'F1 > Insert Snippet' command shows? Do you find your snippet in that list? Can you share your snippet file?

**Comment by TreTuna** [comment]
@jrieken Thanks for responding.

There are no snippets found at all on my Insider's Edition VSC, however, my installation of Release VSC has them all. My snippets files are empty as I have no custom made snippets myself, all of mine come from extensions.

I have side-by-side installations of release VSC and Insider's Edition. All settings/extensions/etc are matched using the Settings Sync extension and the Insider's edition just doesn't see the snippets at all.

Insider's Edition Version 1.20.0-insider - Insert Snippet:
![Insider's Edition](https://user-images.githubusercontent.com/16496746/34693130-68291702-f477-11e7-8e51-e003d2143293.png)

Release VSC Installation Version 1.19.1 - Insert Snippet:
![VSC Verion 1.19.1](https://user-images.githubusercontent.com/16496746/34693176-9070f98c-f477-11e7-95bb-6567f6e370aa.png)

**Comment by jrieken** [comment]
Oh, wait this is insiders vs stable, right? Both have separate locations for snippets, `~/Library/Application Support/Code - Insiders/User/snippets` and `~/Library/Application Support/Code/User/snippets`. You can sym-link them or copy them

**Comment by TreTuna** [comment]
Yes, this is an issue with Code Insiders 1.20.0 (the version before that worked fine), not stable VSC 1.19.1. It's also a problem with snippets from *extensions* and not user created ones in those files.

I have no personally created user snippets. However, to test if this was a full snippets issue or just extension snippets, I created a custom snippet real quick in Insider edition and that worked fine, however, all my snippets from *extensions* still are not loading in and do not work in insiders edition as of the 1.20.0 release.

**Comment by jrieken** [comment]
> all my snippets from extensions still are not loading in and do not work in insiders edition

Installed extensions aren't shared between insiders and stable. So those you also need to 'double' install. You can check with the extensions viewlet: Select an extension, Select Contributions and check if there is a checkmark in the snippets column in the Languages section.

**Comment by TreTuna** [comment]
All my extensions are double installed, in fact, when this issue arose I did not even have the stable version of VSC installed on either of my computers. Insiders has been stable enough for me for the last 6 months that I had deleted the Stable build. I only reinstalled the stable build on my work machine when this happened so that I could test if they worked there and seeing that it did I'm now working in that version until this issue is resolved with Insiders. The computer I'm typing this on (my personal MBP) still only has Insider's 1.20.0 installed, all 6 of my snippets extensions have all the checkmarks, and yet I have no snippets available for use.

**Comment by jrieken** [comment]
>  all 6 of my snippets extensions have all the checkmarks, and yet I have no snippets available for use.

Hm, that's weird. What extensions are those? Do you get snippets from the builtin/default extensions. Like TypeScript -> Class Definition?

**Comment by TreTuna** [comment]
Here are the snippet extensions I have installed. I've used pretty much all of these for 9+ months without any issues until now. 

![Snippet Extensions](https://user-images.githubusercontent.com/16496746/34733282-a62097c4-f51c-11e7-9fe0-b1fde430cffb.png)

**Comment by TreTuna** [comment]
Here is an animated gif of scrolling through my list of available items when I press control+space. The only real snippet I have is the first sniptest there that I created specifically to see if the user added custom snippets work.

![controlspacelist](https://user-images.githubusercontent.com/16496746/34733656-faec90e0-f51d-11e7-856b-a30381c8c72e.gif)

**Comment by jrieken** [comment]
Yeah, thanks I can now reproduce.

**Comment by jrieken** [comment]
There is actually two issues: one is a falsy assumption that the file name denotes the target files (when it's a json file) and then there seem to be extensions that use the same file to register snippets for different languages

**Comment by TreTuna** [comment]
Just wanting to say, today's installed update fixed this issue. Thank you @jrieken for your help!
