### ISSUE TITLE
Provide the ability for an extension to conditionally provide snippets that render the same as package.json-provided snippets

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#41202]
I'd like to be able to conditionally provide snippets based on some knowledge of the project type a user has opened with my extension. I previously opened #26943 requested `when` support for snippets but it was suggested that I just change to a `CompletionItemProvider` instead.

I've implemented a provider that reads the standard snippet JSON format in an attempt to provide the exact same behaviour as when the snippets were contributed via `package.json`:

```ts
export class SnippetCompletionItemProvider implements CompletionItemProvider {
	private completions = new CompletionList();

	constructor(filename: string) {
		const snippets = require(path.join("../../..", filename));
		for (const snippetType of Object.keys(snippets)) {
			for (const snippetName of Object.keys(snippets[snippetType])) {
				const snippet = snippets[snippetType][snippetName];
				const completionItem = new CompletionItem(snippetName, CompletionItemKind.Snippet);
				completionItem.filterText = snippet.prefix;
				completionItem.insertText = new SnippetString(
					isArray(snippet.body)
						? snippet.body.join("\n")
						: snippet.body,
				);
				completionItem.detail = snippet.description;
				completionItem.documentation = new MarkdownString().appendCodeblock(completionItem.insertText.value);
				this.completions.items.push(completionItem);
			}
		}
	}

	public provideCompletionItems(
		document: TextDocument, position: Position, token: CancellationToken,
	): CompletionList {
		return this.completions;
	}
}
```

This appears to work fine and renders snippets that look just like the built-in ones, with one exception - the placeholders are hidden in the built-in snippets but visible in mine:

<img width="726" alt="Code's snippets" src="https://user-images.githubusercontent.com/1078012/34628071-f862017c-f25a-11e7-9dcf-b353e93d4c05.png">

<img width="721" alt="My snippets" src="https://user-images.githubusercontent.com/1078012/34628078-008d1166-f25b-11e7-8eb3-89973366facd.png">

I've been searching through the code and believe this is because of `_rewriteBogousVariables` from [here](https://github.com/Microsoft/vscode/blob/d89ca728f6f55705b5579df89baf5e0316699534/src/vs/workbench/parts/snippets/electron-browser/snippetsFile.ts#L74-L114).

I could copy that code into my completion provider, but it means I have to maintain it if there are any changes/bugfixes in the future. I think it would be better if Code exposed a way for us to be able to provide snippets that render the same as Code's but that we can be added conditionally. (Alternatively, is it possible #26943 could be re-considered? I think it would be a nicer solution!).

**Comment by jrieken** [comment]
Hm, the different is because of this: [`this.documentation = new MarkdownString().appendCodeblock('', new SnippetParser().text(this.snippet.codeSnippet));`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/snippets/electron-browser/snippetsService.ts#L274.). It take the parser, computes the actual insert text (w/o placeholders) and uses that as doc. That's something the core can do with easy but nothing extension easily can do...

Unsure what to do about it...

**Comment by DanTup** [comment]
Would you consider implementing #26943 instead? It would avoid having to leak any of this snippet-specific code out into extensions and also be consistent with a lot of the other things in `package.json` that support `when` conditions (like commands). It seems like an elegant solution to this problem (it also might be relatively simple to carry the condition into the snippet completion provider and evaluate it there during completion?).

**Comment by DanTup** [comment]
Actually, I just read your comments about snippets wanting scopes, so maybe pushing people to completion providers is better - so maybe finding a way to expose this does make more sense..

**Comment by jrieken** [comment]
> It would avoid having to leak any of this snippet-specific code out into extensions and also be consistent

Another way would be make it the default presentation for a snippet completion. So, when the type is snippet we always generate such a string and append to the doc. Tho it will collide with suggestions that already try to emulate this.

**Comment by DanTup** [comment]
Ah yeah, I forgot there was a kind specifically for snippets. Though whether users would expect the rendering to change like that based on the kind, I'm not sure.

In the interest of shipping my changes so I can add project-specific snippets, I'm just going to hide the preview for now (not set the `documentation` property). That way I wouldn't be impacted if there are any changes, it's no worse than snippets were a while back (before the previews).

If you come up with a good way to handle this, I'll update it :-)

**Comment by jrieken** [comment]
> If you come up with a good way to handle this, I'll update it :-)

A good idea might be to use the preview only when the documentation is missing ;-)

**Comment by DanTup** [comment]
That'd work for me; though I don't know if it'd make sense to support both. If I added documentation that was just a line of text, the preview would disappear?

Thinking about the original problem again (my preview has `$tokens` in it and Code's doesn't), if the preview is always effectively replacing them with a blank value, would just stripping out $xxx with a regex make them the same? It's not a good long-term fix (since if you change the display of snippets we'll fall out of sync) but it's something I can do myself today to improve the experience.

**Comment by jrieken** [comment]
> Thinking about the original problem again (my preview has $tokens in it and Code's doesn't), if the preview is always effectively replacing them with a blank value,

That's just variables... Also placeholders come into play, so $1, $2 etc then also all other snippet features...

**Comment by DanTup** [comment]
@jrieken I think that stuff all already works using my completion provider at the top? The only difference I noticed (but it's possible I didn't test properly!) was the preview being different?

**Comment by DanTup** [comment]
On reflection I've decided to leave this as-is. It means the user may see things like `typedef ${1:Type} ${2:Name}(${3:params});` but that's probably better than seeing just `typedef` and then all these placeholders appearing when they complete.

I'll revisit if you add a better way to handle it.

**Comment by jrieken** [comment]
Ok. Closing until you'll change your mind.
