### ISSUE TITLE
Line highlight fails inside merge conflict areas when background color set in theme

### ISSUE THREAD

**Issue by jibsen** [Microsoft/vscode#41201]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299

Highlighting of current line works fine inside inline merge conflict blocks, but if the color theme changes the background color of these areas, the line highlighting disappears.

Steps to Reproduce:

1. Choose a theme with line highlighting, I used Solarized Dark
2. Add a 'merge conflict' to the editor, for instance
~~~
<<<<<<<
check if
line highlighting
works here
=======
>>>>>>>
~~~
3. Check that line highlighting works inside the merge conflict area

![vscode_merge_before](https://user-images.githubusercontent.com/1367512/34627419-c5dbc02a-f260-11e7-81b5-8fe90484e40f.png)

4. Set the background color for merge conflicts, for instance add to settings:
~~~json
    "workbench.colorCustomizations": {
		"merge.currentHeaderBackground": "#207972",
		"merge.currentContentBackground": "#0D4A4E"
    },
~~~
5. Now current line is no longer highlighted inside the merge conflict area

![vscode_merge_after](https://user-images.githubusercontent.com/1367512/34627450-d840f186-f260-11e7-8ef2-71f7ac41e3ec.png)

**Comment by jibsen** [comment]
Same appears to apply to `diffEditor.insertedTextBackground` and `diffEditor.removedTextBackground`, also it removes highlighting of specific changes within lines.

**Comment by chrmarti** [comment]
The merge decorations are on top of the current line decoration. You can use transparency to let the underlying decoration shine through:
```
	"workbench.colorCustomizations": {
		"merge.currentHeaderBackground": "#20797288",
		"merge.currentContentBackground": "#0D4A4E88"
	}
```

**Comment by jibsen** [comment]
I see, thank you, that explains the issue. I also had to add transparency to `editor.selectionHighlightBackground`, because if it is solid you cannot see selections through it. I guess it too is applied over the other decorations.

Is there any documentation, or some way to tell which colors are supposed to be transparent when working on a theme?

It would be nice if the [theme color reference](https://code.visualstudio.com/docs/getstarted/theme-color-reference) mentioned it.

**Comment by chrmarti** [comment]
@aeschli for the suggestion to document the order in which decorations are applied.

**Comment by aeschli** [comment]
@chrmarti The description in the color definition should mention that the color needs to be transparent.

**Comment by jibsen** [comment]
Thanks!

**Comment by chrmarti** [comment]
Good call, thanks @aeschli!

**Comment by bobbrow** [comment]
Can you add documentation about `"diffEditor.insertedTextBorder"` as well?  I just hit this today.

**Comment by aeschli** [comment]
@bobbrow "diffEditor.insertedTextBorder" is documented here: https://code.visualstudio.com/docs/getstarted/theme-color-reference#_diff-editor-colors
I don't think the border needs to be transparent, does it?

**Comment by bobbrow** [comment]
Bah, I copied the wrong value.  I meant `diffEditor.insertedTextBackground`

**Comment by bobbrow** [comment]
@jibsen had made a similar comment above, but it looks like the documentation was not updated for this property or `diffEditor.removedTextBackground`

**Comment by aeschli** [comment]
Thanks @bobbrow, I updated the descriptions.

**Comment by bobbrow** [comment]
Thanks!
