### ISSUE TITLE
If try open file in FAR Manager via Emenu (windows explorer file context menu: Open with Code) I get error message to in console

### ISSUE THREAD

**Issue by michalzobec** [microsoft/vscode#41218]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.5.1

---

Steps to Reproduce:

1. in FAR Manager select PS1 multiple files (more than one file)
2. Activate Plugins by F11 - select EMenu - Context menu - Text menu - Open with Code
3. I get following error message to console attached in screenshot

problem is cannot reproduce if select only one file.
log file was created, but is empty.
I running FAR Manager and Code in User rights context.

Reproduces without extensions: Yes/No - not applicable

![2018-01-06 10_24_34- k__ work_software_script-library_bitbucket_actual_my_scripts_myown_autoassembl](https://user-images.githubusercontent.com/13049276/34638470-4848b76e-f2cc-11e7-8f48-4f4d9d5acb49.png)

**Comment by joaomoreno** [comment]
Maybe FAR Manager tries to launch Code multiple times in the same second?

**Comment by joaomoreno** [comment]
**Repro steps:**

Paste the following in the Command Prompt, in VS Code's dev folder:

```
start "one" .\scripts\code.bat foo.txt
start "two" .\scripts\code.bat bar.txt
```

Code should come up with both `foo.txt` and `bar.txt` open. None of the newly opened command prompt windows should show an error.

**Comment by chrmarti** [comment]
@joaomoreno I cannot reproduce with these steps in 1.19.3. Any hints on how to do that?

**Comment by michalzobec** [comment]
hello, I am sorry, I not get notification.

maybe you have right, this bug maybe initiate FAR Manager. I try use following command

C:\Users\u11478m>code K:\!!work\software\script-library\bitbucket\actual\my\scripts\myown\AutoGenAssemblyVersion\ChangeLog.md K:\!!work\software\script-library\bitbucket\actual\my\scripts\myown\AutoGenAssemblyVersion\License.md

and I not get any error messages to command line back.

but if I try open files via FAR Manager I still getting error messages as I wrote before.
![2018-02-07 13_48_51- k__ work_software_script-library_bitbucket_actual_my_scripts_myown_autogenasse](https://user-images.githubusercontent.com/13049276/35918359-c96411aa-0c11-11e8-9ea8-0afb5bbac32c.png)

this behavior is working only for more than one file. If will try only one file in FAR Manager I not get any error message.

**Comment by joaomoreno** [comment]
@chrmarti Those steps reliably repro it for me on Windows.

**Comment by joaomoreno** [comment]
@michalzobec The fix is still not out. It will come with 1.20.

**Comment by michalzobec** [comment]
@joaomoreno hello, in what release this bug was fixed? I cannot found fix 41218 in 1.20.0 and 1.20.1.

**Comment by joaomoreno** [comment]
K, I guess I'm going to have to try out FAR Manager.

**Comment by michalzobec** [comment]
if you want, I can test it, if you have night build of vscode with this fix.

**Comment by joaomoreno** [comment]
@michalzobec Is this still an issue for you?
