### ISSUE TITLE
Get rid of ^C^C^C^C in powershell

### ISSUE THREAD

**Issue by cmoon2000** [Microsoft/vscode#41212]
In `Powershell`, How to get rid of these things. I can't copy selected text using `Ctrl-C` or using Ctrl key in general

![capture](https://user-images.githubusercontent.com/6170794/34633786-fe5933ba-f2b0-11e7-8537-f0f5b0f898e7.PNG)

- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro

**Comment by Tyriar** [comment]
Did you have a selection to copy? If the terminal is focused the default behavior is to only attempt to copy when there is a selection, otherwise send the ctrl+c to the terminal.

**Comment by cmoon2000** [comment]
If I have a selection by using mouse, then I can copy the text. In other case, I have a selection using keyboard, such as `shift+left/right arrow`, then hit ctrl+c, it will replace the selection by ^C.

**Comment by Tyriar** [comment]
Oh, I think this would be a feature for the powershell extension to properly handle then, please create an issue at https://github.com/PowerShell/vscode-powershell
