### ISSUE TITLE
Indentation: Toggling view scrolls down a bit

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4121]
When I have spaces and toggle the view to have tabs, the content scrolls down:

![untitled](https://cloud.githubusercontent.com/assets/900690/13742845/96263e6e-e9de-11e5-962d-359eb745653a.gif)

Refs: https://github.com/Microsoft/vscode/issues/3922

**Comment by alexandrudima** [comment]
Nice catch!
