### ISSUE TITLE
Proposal: vscode project settings using 2 files

### ISSUE THREAD

**Issue by mazyvan** [Microsoft/vscode#41215]
Seems like some people prefer to commit the .vscode file to git and some other don't.
[YouTube video discussion](https://youtu.be/C8p7rHwctAg)

In large projects this configuration can be annoying.

I propose to have one file to be committed (the team default configurations) and another one that overwrite the previous one that never must be committed.

Just like on npm with the dev packages installations

What do you think? 🤔

What names do you propose?

**Comment by sandy081** [comment]
Seems related to #851
