### ISSUE TITLE
[ emmet ] Not working inside php tag

### ISSUE THREAD

**Issue by hoangnamitc** [Microsoft/vscode#41216]
Hi Adm,
My problem is emmet not working in file .php
Please support for me!

![rec_20180106 08 53 57](https://user-images.githubusercontent.com/7042462/34635247-747b066e-f2bf-11e7-8163-892cce8c7884.gif)

Thanks you reading !

**Comment by ramya-rao-a** [comment]
It works as expected for me.
In your gif it does work in your second attempt.
Can you share what did you do differently between the first and second attempt?
Also share any emmet related settings you have changed

**Comment by hoangnamitc** [comment]
Thanks @ramya-rao-a !

The first, i press key tab but emmet not working.
The second i enter div tag before then emmet woking.

emmet not woking for the first. this problem ony in file .php
File .html is Good.

**Comment by ramya-rao-a** [comment]
Is that the complete contents of the php file?

**Comment by hoangnamitc** [comment]
This is all my problem,
![emmet](https://user-images.githubusercontent.com/7042462/34662775-a8ed49c6-f485-11e7-99ec-bac4c34f84f7.gif)

My setting:
![image](https://user-images.githubusercontent.com/7042462/34662795-c2993a1a-f485-11e7-8d45-c456c630e569.png)

**Comment by ramya-rao-a** [comment]
The fix will be out in tomorrow's Insiders which you can get from https://code.visualstudio.com/insiders
