### ISSUE TITLE
Allow to use ~ or / in finder to bring up path input dialog

### ISSUE THREAD

**Issue by sleagon** [Microsoft/vscode#41217]
- VSCode Version: 1.19.1 (1.19.1)
- OS Version: MACOS 10.12.6

Steps to Reproduce:

1. CMD+O, active basic file explorer
2. just click ~ or / in the keyboard. (normally, we can get the dialog called go to dir.)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@sleagon can you share a screencast how this normally works for you in other apps?

**Comment by sleagon** [comment]
![xx](https://user-images.githubusercontent.com/7693290/34638874-c59e8a02-f30f-11e7-9376-b93c7e1d64ab.gif)
here i tried to open a file in chrome.
by the way,  all extensions have been disabled during the test.

**Comment by bpasero** [comment]
@sleagon so you are literally just typing "~" in that dialog and that brings up the input prompt?

**Comment by sleagon** [comment]
@bpasero 
yes, like shortcut keys. 
you can active it by typing ~ or /.
it's pretty useful when you need to switch from dir1 to dir2 frequently.

**Comment by bpasero** [comment]
I am not quite sure why these keybindings would not work in VS Code. If someone has any insights, comment here.
