### ISSUE TITLE
In user settings, allow user to set editor.tokenColorCustomizations and workbench.colorCustomizations based on current theme

### ISSUE THREAD

**Issue by ryanolsonx** [Microsoft/vscode#41211]
I'm one of those developers that can't seem to stick to one theme in my text editor. Sometimes I use solarized, other times tomorrow-night. So - I use Ctrl-k Ctrl-t a lot.  I really enjoy being able to switch themes easily.

My problem is that I create some of my own modifications for these themes using `editor.tokenColorCustomizations` and `workbench.colorCustomizations`. Currently, whenever I switch to a different theme (that I've added some customizations to), I have to go to my user settings and uncomment chunks of my user settings so that it uses my settings for that theme.

Is there any way that we could have theme specific settings? I don't know what this would take technically but if we could have something that looks like:

```json
{
  "gruvbox": {
    "workbench.colorCustomizations": {
      "statusBar.background": "#282828",
      "statusBar.foreground": "#83A598"
    }
  },
  "solarized-light": {
    "editor.tokenColorCustomizations": {
      "textMateRules": [
        {
         "scope": "keyword.control.import",
         "settings": {
           "foreground": "#D33682"
         }
       }
      ]
    }
  }
}
```
that would be really awesome. It doesn't need to look like this. I only include this as a thought. There's probably a much better way to represent a theme specific workspace setting.

I switched a while back from Atom and I was able to accomplish this using a top level css selector. That made things really nice.
```css
.theme-dracula-syntax {
  // disable italics
  * {
    font-style: normal !important;
  }
}
```

I know that things work different in vs code. So I'd appreciate any ideas that might help me with this small problem.

**Comment by usernamehw** [comment]
You can try this in [Insiders](https://code.visualstudio.com/insiders/) version:
```javascript
"workbench.colorCustomizations": {
  "[Monokai]": {
    "editor.background": "#13171f"
  }
}
```
The same syntax for `editor.tokenColorCustomizations`

**Comment by usernamehw** [comment]
You can try this in [Insiders](https://code.visualstudio.com/insiders/) version:
```javascript
"workbench.colorCustomizations": {
  "[Monokai]": {
    "editor.background": "#13171f"
  }
}
```
The same syntax for `editor.tokenColorCustomizations`

**Comment by usernamehw** [comment]
Disabling italic: https://github.com/Microsoft/vscode/issues/32579#issuecomment-341502559

**Comment by ryanolsonx** [comment]
Thanks @usernamehw . That's exactly what I was looking for. 👍
