### ISSUE TITLE
Vscode hangs OS

### ISSUE THREAD

**Issue by A50** [Microsoft/vscode#41219]
- VSCode Version:
code_1.19.1-1513676564_amd64
- OS Version:
Ubuntu 17.10

Steps to Reproduce:

1. Open Chrome 62.0.3202.89 
2. Open VSCode

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by rebornix** [comment]
>Does this issue occur when all extensions are disabled?: Yes/No
No

As you described, it's caused by extensions, you may want to find the bad extension and file issues there.

**Comment by A50** [comment]
you are right, problem is php exstension
