### ISSUE TITLE
Ctrl+alt shortcuts works same as AltGr

### ISSUE THREAD

**Issue by tehKaiN** [Microsoft/vscode#41225]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Doxygen|bbe|1.0.0
gitignore|cod|0.5.0
doxdocgen|csc|0.0.7
arm|dan|0.1.2
vscode-markdownlint|Dav|0.12.0
line-counter|dol|0.3.0
latex-workshop|Jam|3.12.0
hex-fmt|ker|1.0.0
vscode-todo-parser|min|1.9.1
movemaster|Kai|0.0.1
cpptools|ms-|0.14.5
platformio-ide|pla|0.9.0
rust|rus|0.3.2
shader|sle|1.1.2
shader-toy|ste|0.4.0
m68k|ste|0.0.1
cmake|twx|0.0.17
cmake-tools|vec|0.10.4
debug|web|0.21.2

---

Steps to Reproduce:

1. In OS, enable Polish or any other keyboard layout with alt chars
2. Try "Add cursor above" shortuct: <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>up</kbd> or define any other like that
3. Currently, doing <kbd>AltGr</kbd>+<kbd>up</kbd> also triggers "Add cursor above", but it shouldn't

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
https://en.wikipedia.org/wiki/AltGr_key#Control_+_Alt_as_a_substitute
<img width="125" alt="image" src="https://user-images.githubusercontent.com/5047891/34673868-09f9f018-f484-11e7-85cc-29b842fb8586.png">

We simply do what the platforms we're built on top do (Chromium, Windows).
