### ISSUE TITLE
Compare Changes Error: No Provider for merge-conflict.conflict-diff

### ISSUE THREAD

**Issue by tonysneed** [Microsoft/vscode#41224]
- VSCode Version: 1.19.1
- OS Version: Windows 10, macOS

Steps to Reproduce:

1. Select conflict when merging changes
2. Click Compare Changes.

Error: Unable to open 'Filename.cs': Current Changes ⟷ Incoming Changes': no provider for merge-conflict.conflict-diff

This error takes place both in Windows and Mac versions of VS Code with the EntityFrameworkCore repo.

**Comment by stereokai** [comment]
Happens to me too. How to deal with it?

**Comment by richardsweeneyobjective** [comment]
Happens to me too, no workaround found:
VSCode Version; 1.19.1 (latest today)
OS Version: Windows 10 Pro 64-bit

Steps to reproduce:
1. Select conflict when merging changes
2. Click Compare Changes

Error: Unable to open 'mainTemplate.json: Current Changes ⟷ Incoming Changes': no provider for merge-conflict.conflict-diff
