### ISSUE TITLE
Indent using Spaces / Tabs cannot be invoked more than once on a given file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4122]
After I ran those actions once I cannot run them again and I get a message that the action is not enabled in the current context.

Refs: https://github.com/Microsoft/vscode/issues/3922

**Comment by isidorn** [comment]
@bpasero I can not repro this ben with latest vscode running out of source.
Can you give me precise steps if you can repro

**Comment by bpasero** [comment]
F1 > Indent using spaces > 4
F1 > Indent using spaces > 4

**Comment by isidorn** [comment]
@gregvanl this was the bug you also found - it shoud be fixed now!
