### ISSUE TITLE
Identation guides not rendering properly

### ISSUE THREAD

**Issue by ralves09** [Microsoft/vscode#41229]
- VSCode Version: 1.19.1
- OS Version: MacOS 10.13.2 (17C88) on a MacBook (Retina, 12-inch, 2017)

Steps to Reproduce:

1. Just open, create or edit any file of any type
2. Some guides are render, others not. This changes when I change de zoom level

Does this issue occur when all extensions are disabled?: Yes

Its a fresh installation.

<img width="1005" alt="screen shot 2018-01-06 at 17 27 20" src="https://user-images.githubusercontent.com/5287233/34643249-3ea8c4ba-f308-11e7-882c-a1579f6a2437.png">
<img width="544" alt="screen shot 2018-01-06 at 17 30 57" src="https://user-images.githubusercontent.com/5287233/34643250-3ec75fec-f308-11e7-9a19-5fe9d3944e08.png">

**Comment by rebornix** [comment]
@ralves09 do you still see this issue with latest version? It might be releated to Electron's rendering and since we updated Electron version already, it would be great if you can help verify.

**Comment by ralves09** [comment]
@rebornix, I have just tested and is everything fine!
Thank you for your attention!
