### ISSUE TITLE
Use WorkbenchList for custom dropdowns

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41223]
It looks like the custom dropdowns are using the bare `List` widget. I suggest to make it possible to pass in a `treeCreator` (similar to the one [in quick open](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L46)) and let clients instantiate a [`WorkbenchList`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L92) where the widget is used. 

The advantage of `WorkbenchList` is that users can configure keybindings for navigation within the list:

![image](https://user-images.githubusercontent.com/900690/34641151-e74e31ee-f2ff-11e7-9587-b29496243490.png)

With this, users that have custom keybindings could use them also within the dropdown.

@cleidigh what do you think?

**Comment by cleidigh** [comment]
@bpasero 
I think this makes sense.
The implication would be adding disabled option awareness directly within the tree widget since it would have to be aware of disabled options to use the normal navigation key bindings.  I'm pretty sure this is not currently supported.

- Is your thought that passing the tree creator is optional or is it always used?
- Do you want support for multiple disabled options?  Original/current Select only supports one.
- Should the widget directly render the disabled options?  Currently client passes in a line or whatever.
- Do you want to maintain first character navigation?
- If possible, do you want to try to hit the January milestone?  I think this is possible assuming no major issues.  I could make it my priority.

**Comment by bpasero** [comment]
@cleidigh can you share how this breaks layers? If the tree creator is passed in from the outside it should work fine. Maybe look at `quickOpenWidget` as example which is using this pattern. 

I am not sure how disabled input entries are related to this issue, don't you have this problem already today with the list or are you actually handling disabled items in the list navigation? That would make things a bit more complicated, I agree.

This is not a high priority item but I thought I would report it because it would be good if all our list/tree users had the same keyboard accessibility consistently with other trees/list in other places.

**Comment by cleidigh** [comment]
@bpasero 
I'm still working through the differences between list and tree, but I think it may still be necessary to import various tree properties/interfaces even if we pass in treeCreator.  From quickOpenWidget constructor:

treeCreator?: (container: HTMLElement, configuration: ITreeConfiguration, options?: ITreeOptions) => ITree;

Am I'm misinterpreting this?  I have started to prototype the tree by moving selectBox to
vs/workbench/parts/selectBox 

Concerning the disabled options, I mentioned it as a requirement tweak to the built-in navigation, yes
I to support this now. That was the main reason I had to do my own keyboard controller which I thought was safer . than modifying list.  I'm confident I can modify the tree in the same respect.

**Comment by bpasero** [comment]
@cleidigh sorry, I was not very clear: quick open is using a tree so there is a tree creator. of course for the dropdown we would have a list creator so that a `WorkbenchList` instance can be created from the outside, no need to use the tree here. You can see in [`listService`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L92) that there is a `WorkbenchList`

The disabled options will be an issue though which may indicate that this cannot be done. The whole idea of the `WorkbenchList` is to actually not implement a custom controller for keybinding navigation but instead let the `WorkbenchList` handle all navigation through central commands that the user can configure. I fear unless the disabled entries are not part of the `List` widget, this might be tricky to do after all.

**Comment by bpasero** [comment]
I am not convinced anymore that this is really needed, given that the native dropdowns use the same keybindings as the one we now have for the custom dropdown too. 

Closing until there is more user feedback around this, sorry for the hassle.
