### ISSUE TITLE
List: keyboard bindings not supported for opening

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41220]
There is a command for lists called `list.open` that can be used to open an element of a list or tree. It looks like newer lists we added do not support this behaviour, specifically:
* open editors view (Explorer)
* breakpoints view (Debug)
* repositories view (SCM)

**To reproduce:**
* put keyboard focus into one of the lists
* press `Cmd+ArrowDown`

=> does not open

Works fine, e.g. from the SCM view for file changes which also uses a list widget.

**Comment by isidorn** [comment]
`cmd + down` does not trigger `list.open` now that I tried it. @joaomoreno did you do something special in the `scmViewlet` for this?
For breakpoints view and open editors I use a custom handling for opening because I have different behavior if it is double click vs single click and if ctrlcmd is held. [Code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/breakpointsView.ts#L99)
We would have to enrich the open event if I were to drop my custom handling.

**Comment by bpasero** [comment]
@isidorn sorry the command is called [`list.select`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/commands.ts#L273)

The handling typically goes like this:
* list/tree user registers for selection event
* list/tree user opens element upon selection

**Comment by isidorn** [comment]
@bpasero thanks for the pointer, though that does not really change much. For some reason that command does not get triggered when I do enter or cmd + down from either open editors or breakpoints view (even if I remove all my listeners and increase the weight of the command).

Though even if I got the event I still have the issue I mentioned above that this event is not giving me enuogh information to properly open the file. I would have to listen to this event and contiue listening on keyboard events to properly open, which is not that nice.

**Comment by bpasero** [comment]
@isidorn @joaomoreno oh yeah, I forgot to mention that when creating the `WorkbenchList` you need to set `keyboardSupport: false` in the options. Otherwise the default controller eats the keybindings up!

**Comment by bpasero** [comment]
@isidorn once this is adopted we can inline `keyboardSupport: false` into workbench list & tree so that future users not fall into this.

**Comment by bpasero** [comment]
@isidorn let me take this, I am in this area

**Comment by joaomoreno** [comment]
@bpasero Thank you!

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/42314
