### ISSUE TITLE
Display issue with multiple monitors (different resolution)

### ISSUE THREAD

**Issue by gsedlacz** [microsoft/vscode#41228]
- VSCode Version: 1.19.1
- OS Version: win10 1709

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

Initially I thought it would be a Chrome-Extension Bug as it firt appeared when I opened an instance of Chrome from within vscode.
Therefore i openened a bug over there.
Any missing information might be found over there: https://github.com/Microsoft/vscode-chrome-debug/issues/575

Steps to reproduce:

1. Close an instance of Chrome that is displayed on the WQHD monitor.
2. Run an instance of VSCode on another monitor that offers a FHD resolution.
3. Within this window you have to launch chrome.

It also happens if I drag the VSCode window from the HD monitor to the WQHD one:
![image](https://user-images.githubusercontent.com/33100708/34638672-33ccbd94-f2d1-11e7-96d5-b481d8a46afd.png)

Further information:
If you drag the new Chrome instance the smaller monitor it works.
Within the Windows display settings I set the "Change the size of texts, apps and other items" to 125%.
launch.json (default):
```

"version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]

```
![image](https://user-images.githubusercontent.com/33100708/34595276-fc392778-f1d6-11e7-96b1-d87952e98856.png)

This is a close up of the window shown above as it shows that thought to be inner image clearly leaves its window.
![image](https://user-images.githubusercontent.com/33100708/34595719-5fbef8f6-f1da-11e7-9fde-5d90a5b687b7.png)

Is this a known bug ?

**Comment by bpasero** [comment]
Does it reproduce if you run "code --disable-gpu"?

**Comment by MettTheFrameless** [comment]
Thank you for your answer.

For VSCode itself --disable-gpu does the trick but if I open chrome from the chrome debug plugin the new chrome instance remains faulty.

Will this bug get fixed ?
