### ISSUE TITLE
Repeated prompts for GitHub credentials

### ISSUE THREAD

**Issue by sky96line** [Microsoft/vscode#41230]
- VSCode Version:1.19.1
- OS Version:Windows 7(Ultimate)

Steps to Reproduce:

1.Commit changes to github via visual code

Does this issue occur when all extensions are disabled?: Yes

**Comment by cleidigh** [comment]
@sky96line 
Can you provide more information?
- git set up
- do other git commands work?
- access to repository from other programs?

**Comment by CoenraadS** [comment]
You need to update your credential manager: https://github.com/git-for-windows/git/releases
