### ISSUE TITLE
Opens file twice when creating missing overrides.

### ISSUE THREAD

**Issue by RCHowell** [Microsoft/vscode#41233]
- VSCode Version: 1.19.1
- OS Version: macOS 10.12.6

Steps to Reproduce:
1. Open two different files so that one is in the left pane and one is in the right pane.
2. In the right pane, extend some abstract class.
3. VSCode will underline your class and will ask `Create (n) missing overrides`? **Click it.**
4. The file from the right pane is then opened in the left pane.

Does this issue occur when all extensions are disabled? **No**

![screen shot 2018-01-06 at 6 04 02 pm](https://user-images.githubusercontent.com/5731503/34644823-13b2c75c-f30c-11e7-9515-d202ffbcd32c.png)
![screen shot 2018-01-06 at 6 04 20 pm](https://user-images.githubusercontent.com/5731503/34644824-13c11e74-f30c-11e7-9f43-8fed38d30fa4.png)
![screen shot 2018-01-06 at 6 04 28 pm](https://user-images.githubusercontent.com/5731503/34644825-13d13df4-f30c-11e7-98bc-df2af746e20a.png)

**Comment by bpasero** [comment]
I think this works as designed because the extension seems to be opening a file in the first group and we show it there event though it is already opened in the second group.
