### ISSUE TITLE
VSCode causes my screen flicker when running on 4k external monitor

### ISSUE THREAD

**Issue by blastmann** [Microsoft/vscode#41238]
- VSCode Version: 1.19.1
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Start VS Code, keep the window on focus
2. Copy and paste a large number of texts
3. The whole screen will flicker (not only VS Code)

Does this issue occur when all extensions are disabled?: Yes

Etc:
- Occurs when all plugins are disabled
- Does not occur when window is not in focus
- Occurs on external 4k display at 3360x1890
- `"editor.disableTranslate3d": true` not work

**Comment by blastmann** [comment]
https://www.youtube.com/watch?v=GkjwA79ebW4

FYI, the video above shows the details about this issue.

**Comment by bpasero** [comment]
Does it reproduce if you run "`code --disable-gpu`"?

**Comment by blastmann** [comment]
No. It's working now. Thanks. @bpasero

**Comment by bergmeister** [comment]
I have a similar problem that happens only on a particular Azure VM (no high-res, only 2 HD monitors). The problem happens also in the latest Insider build. I have tried `code --disable-gpu` but no luck. For some reason, I do not have the setting `editor.disableTranslate3d`...

**Comment by drewlustro** [comment]
Also have this problem :|

**Comment by bergmeister** [comment]
The problem could be solved at the end and it turned out to be a bug in the latest Citrix Virtual host software (I am using a thin client to connect to my dev VM in Azure)

**Comment by dyyylan** [comment]
I've been getting this as well for as long as I've had my 4k monitor (about 1 year) and have just dealt with it. The whole screen flickers to a strange black screen with green lines whenever i switch tabs inside vscode, which is pretty frequent so it's definitely annoying.

Starting with the `--disable-gpu` flag resolves the screen flickering, but the app itself still flickers black momentarily. Still an upgrade, I guess...

I'm on macOS 10.13.4 and VSCode 1.22.2.

It seems fine on my 1080p monitor (no scaling) and on Windows (any monitor/scaling).

**Comment by capaj** [comment]
I have a similar issue, but the flickering is much more severe. I run on 
![image](https://user-images.githubusercontent.com/1305378/39520957-cd986aea-4e0c-11e8-8bee-492cf06f23d4.png)

and I my flickering is recorded here, sorry about my phone camera being out of focus so much:
https://www.youtube.com/watch?v=peHqRBlXUM4

atom doesn't have any issues whatsoever even when in 4k. When I make the window smaller, flickering goes away, but that's not a solution.

**Comment by unapieer** [comment]
Version 1.23.0 (1.23.0)
OS Version: macOS 10.12.6

HI,

I am little bit of a noob.
I am in VS Code, where/how do I enter `code --ignore-gpu-blacklist` ? 

Sorry to sound out of touch.

**Comment by bergmeister** [comment]
@unapieer On the command line, the command `code` opens VSCode because the binary is called `code`, therefore it is an argument on how to open/start VSCode in the first place.

**Comment by capaj** [comment]
it would be really nice if that flag was enabled by default so that we wouldn't have to pass it every time.

**Comment by bergmeister** [comment]
Without being a VSCode expert, I would say, it does not make sense to disadvantage most of the users with not using the GPU to account for a few people. A user setting would make more sense IMHO.

**Comment by kavehv** [comment]
I'm running into the same issue.  I'm not sure what changed, but it just started happening randomly on 10.13.4 and 5 with VSCode 1.23.1 on the 3008x1692 scaled setting on Dell P2715q monitor driven by my 2015 Macbook Pro (with AMD GPU).

**Comment by johnelm** [comment]
`--ignore-gpu-blacklist` fixes it here.  It doesn't show in the CLI help text, but it works.  The flashing was intolerable, very happy to have it solved.

( `--disable-gpu` didn't help (it _does_ appear in the help text)  ).

**Comment by drewlustro** [comment]
## 😭 Still happens w/ `code --ignore-gpu-blacklist`

<img width="698" alt="screen shot 2018-05-22 at 3 01 52 pm" src="https://user-images.githubusercontent.com/194885/40385086-8796e86a-5dd3-11e8-8e2d-28c75fef8307.png">

**Comment by JaredSartin** [comment]
Mine just started doing it too... Mac 10.13.3 and 1.23.1 VSC

**Comment by johnelm** [comment]
oops, I should have been specific about my OS level - I'm at 10.13.2 ( and `--ignore-gpu-blacklist` is solving the issue for me ).  I've updated my earlier post to include this.

**Comment by JaredSartin** [comment]
Running `code . --high-dpi-support=1` seems to fix it as per #45492

**Comment by tryangul** [comment]
code-insiders works here as well
`macOS 10.12.6 - Intel HD 530`

**Comment by bpasero** [comment]
@blastmann (or anyone) do you still see this in our insiders release?  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by blastmann** [comment]
@bpasero The newest insider release seems working good now. I can't reproduce this issue.
