### ISSUE TITLE
Syntax highlight broken for Batch file

### ISSUE THREAD

**Issue by wlai2768** [Microsoft/vscode#41235]
Steps to Reproduce:

1. Open a new file
2. Change file type to Batch file
3. Paste below two lines.  The first "for" line color rendering is broken.

```batch
for %%i in ( %* ) do if "%%i"=="--watch" goto :do_%1_%2_watch
for %%i in ( 
    %* 
) do if "%%i"=="--watch" goto :do_%1_%2_watch
```

**Comment by aeschli** [comment]
This issue was moved to mmims/language-batchfile#22
