### ISSUE TITLE
Leakage when refreshing explorer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4123]
* open a workspace with ~40 files/folders in the root dir
* refresh the explorer
* take a heap snapshot
* refresh the explorer 10 times
* take another heap snapshot, heap grew by 0.1MB

**Comment by bpasero** [comment]
@jrieken did you get anything more concrete out of the heap snapshot than those basic types here?

![image](https://cloud.githubusercontent.com/assets/900690/13822365/a1b22680-eba5-11e5-9edc-d05bc3aae489.png)

**Comment by bpasero** [comment]
See attached heap allocations over time, picking a span between multiple refreshes, I do not see information about leaks:

![untitled](https://cloud.githubusercontent.com/assets/900690/13839289/321c4790-ec1a-11e5-89a0-521f3123f12d.gif)
