### ISSUE TITLE
how can I hide menus When my extension not active

### ISSUE THREAD

**Issue by hanfengcan** [Microsoft/vscode#41237]
I found in different file, menus context is difference. 
![image](https://user-images.githubusercontent.com/4559753/34648027-c946c076-f3cc-11e7-8b36-28fb25d01741.png)

![image](https://user-images.githubusercontent.com/4559753/34648041-e63e636e-f3cc-11e7-93ae-5b8e2a9811a6.png)

how can I hide menus when my extension inactive

**Comment by jrieken** [comment]
Wait... @hanfengcan this is the editor or explorer menu right? You should use the `when`-condition to define *when* a command should show as menu item. See https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

**Comment by hanfengcan** [comment]
@jrieken editor menu. I hope these contributes menus can be hide  when my extension inactive

my code 
```
        "menus": {
            "editor/context": [
                {
                    "when": "editorHasSelection",
                    "command": "port.sendSelect",
                    "group": "1_port"
                },
                {
                    "when": "editorTextFocus&&!editorHasSelection",
                    "command": "port.sendALine",
                    "group": "1_port"
                },
                {
                    "when": "editorTextFocus&&!editorHasSelection",
                    "command": "port.sendAll",
                    "group": "1_port"
                }
            ]
        }
```
