### ISSUE TITLE
VSCode freezes with NFS share when changing files

### ISSUE THREAD

**Issue by grandtele** [microsoft/vscode#41249]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Align|ste|0.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.  **nfs server**
/etc# cat exports 
/opt *(rw,fsid=0,insecure,sync,no_subtree_check,all_squash,no_wdelay,anonuid=0,anongid=0,sec=krb5p:krb5i:krb5) 

2. **nfs client (mac os)**
mount -t nfs -o sec=krb5p,rw,soft,intr,sync,rsize=8192,wsize=8192,retrans=3,timeo=900,vers=3,actimeo=1,noatime,locallocks,rdirplus,resvport

3. Just open any files and click by Tabs, it will be freezed
![video-02ku9ux](https://user-images.githubusercontent.com/22945890/34651696-f6118be0-f3db-11e7-9e58-40f41fe76efd.gif)

---
I try VSCode half year ago, and this problem is exist, now it also exist.
Sublime Text - haven't such issue

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by grandtele** [comment]
- VSCode Version: Code - Insiders 1.20.0-insider (c4065a8ba5261456338f850a37e67732d98bf57a, 2018-01-05T07:58:53.336Z)
- OS Version: Darwin x64 17.3.0
- Extensions: none
---

Steps to Reproduce:

1. **nfs server**  
We have alot of nfs shares in different countries, this is typical share
/home *(rw,fsid=0,insecure,sync,no_subtree_check,all_squash,no_wdelay,anonuid=0,anongid=0,sec=krb5p:krb5i:krb5)
2. **nfs client** mount -t nfs -o sec=krb5p,rw,soft,intr,sync,rsize=65535,wsize=65535,retrans=2,timeo=1200,vers=3,ac,**actimeo=3600**,noatime,locallocks,resvport

I play with params on client side, looking case in caches attributes (param actimeo)
with actimeo=0 - impossible to navigate

Sublime also have such freeze on tab navi, but time of hold not more 0.5s (very small, can feel difference only if work with local files)

![video-09my0yq](https://user-images.githubusercontent.com/22945890/34662468-9a642194-f459-11e7-98c5-d2ea4d87fdf0.gif)

**Comment by bpasero** [comment]
@grandtele so it looks like it is just the clicking into the editor tab that gets stuck, it is NOT the entire application getting stuck or is it?

**Comment by grandtele** [comment]
All Application is frozen
![video-56h81qm](https://user-images.githubusercontent.com/22945890/34666260-1ec4fc62-f46c-11e7-9ecd-f5c3e91c0291.gif)

**Comment by bpasero** [comment]
Thanks. I fear this could be an issue with node.js. Even though we load the file async, maybe some lookup (DNS?) blocks the world :-/.

**Comment by grandtele** [comment]
I fond same issue(problem) at Atom - without solutions.

I fond tmp solution - merge nfs to samba:
All servers connect to private network via openvpn, and in this network will samba share.

I check this scheme now at 1 server and it work good

Cheers

**Comment by fritzw** [comment]
This issue still happens with:

```
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

However, I suspect that this is not really a bug in VSCode or node or any other dependency, but rather an NFS bug. Especially because this doesn't only freeze VSCode, but also any other applications that happens to access the changing files.

In our concrete case, linking a C++ executable from multiple object files freezes VSCode, the ld process, and some other random processes which happen to access the NFS share during the time until the NFS mounts have recovered. Frozen processes are in the D state (uninterruptible sleep) until the NFS mounts have recovered. This happens even when you start the linking process in a separate terminal from VSCode. Strangely enough, the problem doesn't appear to occur when compiling a single cpp file to an object file.

For the record, the NFS shares are mounted with the following options:

    type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=krb5p,clientaddr=xxx.yyy.zzz.150,local_lock=none,addr=xxx.yyy.zzz.33)

**Comment by topolittle** [comment]
I had the same issue, furthermore the folder refresh was not working.

However, the issue has dissapeared by mounting the share this way:
`sudo mount -t nfs $server_ip:<nfs share> <your mount point> -o addr=$server_ip,clientaddr=$client_ip`
server_ip is the ip address of the nfs share
client_ip is the ip address of the machine accessing the share

I am on Fedora 29 on both server side and client side. The client is accessing the server via VPN (OpenVPN).

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
