### ISSUE TITLE
Why I can not really clean the terminal？

### ISSUE THREAD

**Issue by reaCodes** [Microsoft/vscode#41243]
- VSCode Version:1.19.1
- OS Version:Windows 10 16229.192

When I use `clear` in PowerShell, the previous information will be completely cleared. But I use the same method, the previous information is only hidden in the top. I know this is not a bug, but I think this design is not very good. Why design like this, may change later?

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
See https://github.com/xtermjs/xterm.js/issues/106

**Comment by CookieCrumbles** [comment]
So is this solved now ?

**Comment by Tyriar** [comment]
Nope, it needs to be fixed upstream before pulling it into VS Code

**Comment by CookieCrumbles** [comment]
I'm under the impression that this is either of no importance to most people or this is such a annoying bug to fix that they don't get around to it :-). I really wish this got fixed, it screwed me over to many times when reviewing data. I had to revert back to ISE for most of my projects. Thanks for replying so quickly. IF you could push this a bit up the ladder, i would appreciate it :)

cheers

**Comment by Tyriar** [comment]
@CookieCrumbles I looked at it briefly yesterday as a result of your comment, it's not so simple unfortunately https://github.com/xtermjs/xterm.js/issues/106#issuecomment-356067007, I pinged the author of winpty who might be able to help.
