### ISSUE TITLE
The caret will move backward after moving the window

### ISSUE THREAD

**Issue by aswasn** [Microsoft/vscode#41241]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.5

---

example.md
```
ABC
```

Steps to Reproduce:

1. open a file in vscode, for example, the `example.md` showed above.
2. assume the caret is behind the character C now.
3. drag and move the window.
4. it looks like that the caret is still behind the character C. BUT, if you type a "D", you will find the text becomes "ABDC"!!! The caret moved back!

Reproduces without extensions: Yes

**Comment by aswasn** [comment]
This bug is really annoying

**Comment by rebornix** [comment]
Let's track it in https://github.com/Microsoft/vscode/issues/38163
