### ISSUE TITLE
[loc]Request to add Esperanto language to VS Code

### ISSUE THREAD

**Issue by neoeinstein** [Microsoft/vscode#41247]
We expect at least three language contributors sign up and product team sign off before adding new language to transifex.
Please vote by adding your transifex account name here.

**Comment by neoeinstein** [comment]
My transifex account name: neoeinstein

**Comment by danyeh** [comment]
Adding language info: https://en.wikipedia.org/wiki/Esperanto

**Comment by felipesabino** [comment]
My transifex account name: felipesabino

**Comment by RobinvanderVliet** [comment]
My Transifex username: robin0van0der0vliet

**Comment by ahampt** [comment]
Transifex name: ahampt

**Comment by felipesabino** [comment]
@neoeinstein Now that we have 3+ contributors, do you know what are the next steps and how to proceed?

Anyway, is there something else I could do to help moving this forward? Well, I am also pinging @danyeh just in case it helps.

**Comment by danyeh** [comment]
Thank you for contributing! Esperanto (eo) has been enabled in Transifex for 3 VS Code projects.
