### ISSUE TITLE
failed to load .csproj file

### ISSUE THREAD

**Issue by Tyfyter** [Microsoft/vscode#41255]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.13.1

---

Steps to Reproduce:
Unknown.

The omnisharp log contained this:
Starting OmniSharp server at 1/7/2018, 3:31:34 PM
    Target: c:\Users\Tyfyter\Documents\My Games\Terraria\ModLoader\Mod Sources\elemental\elemental.sln

OmniSharp server started
    Path: C:\Users\Tyfyter\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\OmniSharp.exe
    PID: 7556

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.1.7601.65536 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "C:\Users\Tyfyter\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\Tyfyter\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "C:\Users\Tyfyter\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\Tyfyter\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\Tyfyter\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild
            MSBuildToolsPath = C:\Users\Tyfyter\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Tyfyter\Documents\My Games\Terraria\ModLoader\Mod Sources\elemental'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\Tyfyter\Documents\My Games\Terraria\ModLoader\Mod Sources\elemental
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'c:\Users\Tyfyter\Documents\My Games\Terraria\ModLoader\Mod Sources\elemental\elemental.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\Users\Tyfyter\Documents\My Games\Terraria\ModLoader\Mod Sources\elemental\elemental.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Users\Tyfyter\Documents\My Games\Terraria\ModLoader\Mod Sources\elemental\elemental.csproj'.
c:\Users\Tyfyter\Documents\My Games\Terraria\ModLoader\Mod Sources\elemental\elemental.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Tyfyter\Documents\My Games\Terraria\ModLoader\Mod Sources\elemental'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Tyfyter\Documents\My Games\Terraria\ModLoader\Mod Sources\elemental' on host 9000.

Reproduces without extensions: Error is an extension function not working, so disabling extensions would cause this error.

**Comment by rcjsuen** [comment]
@Tyfyter If it's a bug with the extension then you should open a bug in the [OmniSharp/omnisharp-vscode repository](https://github.com/OmniSharp/omnisharp-vscode).

**Comment by rebornix** [comment]
@Tyfyter please file issues against omnisharp, thanks.
