### ISSUE TITLE
Suggestion: Login and sync across devices

### ISSUE THREAD

**Issue by DStoyanoff** [Microsoft/vscode#41253]
Hello,
I wasn't able to find such issue (it's hard to find across so many issue though).

I am using VSCode on two PCs - one at home and one at work. I did setup my extensions and settings and etc at work to suit my needs the best and this thing is changing over time, as I find more useful extensions. 

When I got home however (or decide to switch from vs code to insiders version), I need to set up everything from scratch and to sync it manually on each change.

My suggestion is to have some sort of login inside VS Code (just like the regular VS), which will allow you to sync your settings, themes, extensions and etc.

I will be happy to hear if there is an existing way to do this, but I haven't found yet (except for workspace and extension recommendations in a specific repo).

Cheers!

**Comment by cleidigh** [comment]
@DStoyanoff 
There is a great extension just for this.

https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
