### ISSUE TITLE
Discussion: eslint errors + custom eslint rules

### ISSUE THREAD

**Issue by shobhitchittora** [Microsoft/vscode#41254]
Hi. I was going around the vscode repo when I tried to run eslint on the `src` folder and found **100+** lint errors. Also running a fixer does seem to fix ( most of ) those issues as - 

```js
./node_modules/eslint/bin/eslint ./src --fix
````

Is there a way to fix this ?

Also I'd like to suggest/discuss adding `eslint:recommended` rules and/or custom eslint rules to the project. It would be great if lint checks are added in the build pipeline! 😇

**Comment by mjbvz** [comment]
I believe we already do run eslint using `gulp eslint`. The failures you see when running gulp directly seem to be for test fixtures or for a few external files that have been copied into the vscode repo

@joaomoreno Is that correct?

**Comment by joaomoreno** [comment]
That is correct. The way to run eslint over our sources is through `gulp eslint`. The current `master` branch has zero issues with that.

**Comment by shobhitchittora** [comment]
@mjbvz @joaomoreno Thanks for clearing this out. I totally missed this! 👍🏻
