### ISSUE TITLE
Linebreak debugging in an unsaved file should not allow icon to show

### ISSUE THREAD

**Issue by fatherjack** [Microsoft/vscode#41251]
- VSCode Version: 1.19.1
- OS Version: Win 10 Pro 1709 16299.125

Steps to Reproduce:

1. create new file - do not save it
2. add multiple lines of code 
3. place the cursor in one line and press F9 to add a breakpoint
4. in the left hand margin the breakpoint icon (red dot) shows, even though you cannot add a breakpoint to an unsaved file.

In my opinion you should not be able to apparently add a breakpoint when it will be ignored. 
Pressing F9 should not have any effect. 
When right clicking in the left hand margin the popup menu of Add Breakpoint and Add Conditional Breakpoint should be disabled unless the file is saved.

Tested using a PowerShell script file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I do not agree.
Users might watn to first add breakpoints before saving a file, while limit this scenario?
If the file with brekapoints is unsaved and you start debugging the debugger shuold return those breakpoints as unverified and tehy will appear grayed out - if that is not the case please file an issue against the powershell extension.

Closing as this was a concious design decision.

**Comment by fatherjack** [comment]
If this is by design then the save process (from untitled1 to (for example) test1.ps1) should preserve the break points in the newly saved file. Currently if I create a new file and add multiple lines of code then assign break points in it the debugger UI shows Untitled [3] representing the break point on line 3. If I save the file as Test.ps1 there is no change in the debug UI and when I click on the untitled [3] VSCode opens a new empty file.

**Comment by isidorn** [comment]
@fatherjack that is a new issue, can you please create a new issue so we track that limitation. Thanks
