### ISSUE TITLE
Debug console is closed when reloading extension host window

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4125]
VS Code 0.10.12-alpha on OS X 10.11.3

- launch hello world extension from VS Code
Observe: debug console appears and extension host windows opens
- "reload window" in extension host window
Observe: window reloads and debug console disappears (most of the time)
It seems that the 'closing timer' of the debug console is applied to the new debug console that appears after the session restart.

The debug console should stay open after a reload.

When using a "Restart" instead of the "Reload", the console doesn't close.

**Comment by isidorn** [comment]
We no longer automatically close the debu console
