### ISSUE TITLE
git error occurs when the path of the file include Korean characters.

### ISSUE THREAD

**Issue by c0sm0s171578** [Microsoft/vscode#41257]
Hello, I appreciate your excellent application.
But I got an issue about Korean character

- VSCode Version: 1.19.1
- OS Version: Mac OS 10.13.2

Steps to Reproduce:

1. mkdir 헬로우
2. open 헬로우 with atom
3. initialize git repository at 헬로우 folder
4. write aa.c in 헬로우 folder
5. Try to stage aa.c at source control panel
6. Error must occur

Although the file must be inside the repository, The error message says the file is not inside the repository
![image](https://user-images.githubusercontent.com/29162801/34655659-d9ce1e4c-f450-11e7-9f20-1d0b75f88ed3.png)

This is git log
![image](https://user-images.githubusercontent.com/29162801/34655657-d184004e-f450-11e7-90e0-b0bbc404d90a.png)

In addition, When I tested, If the folder name is English and the file name is Korean, this error didn't occur. but not only direct parent folder name is Korean also If any recursive parent folder name is Korean, this error occurs too.

Thank you.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/41246
