### ISSUE TITLE
1.19 breaks files.trimFinalNewlines

### ISSUE THREAD

**Issue by seiks** [Microsoft/vscode#41256]
Hi.

After updating to 1.19 I noticed that automatic trimming of newlines has broken.

- VSCode Version: 1.19.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Set `files.trimFinalNewlines` to `true`.
2. Open up a new file.
3. Add text/whatever and multiple newlines at the end of file.
4. Save and see that nothing happens.
5. Close file. You can even close VSCode.
6. Re-open file/VSCode and try again.
7. Nothing happens.

Extensions and language environments which do their own trimming work just fine (obviously).

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by seiks** [comment]
I tried this with the insiders build and the bug seems to be fixed. I could not reproduce it. 👍 

+ VSCode Version: 1.20.0-insider (c4065a8ba5261456338f850a37e67732d98bf57a)

**Comment by seiks** [comment]
In retrospect, I should have probably tried the insiders build before opening up an issue. My apologies for that. Open source and GitHub are still a bit new to me.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by seiks** [comment]
I did that again with the same results as my initial report.

However, I decided to reset my settings and only set `files.trimFinalNewlines` to `true` and what do you know, it started working. There seems to be some configuration options in my config that are causing conflicts.

I'll investigate this more and report back.

**Comment by seiks** [comment]
I found the underlying issue.

When `editor.formatOnSave` is set to `true` alongside `files.trimFinalNewlines`, the trim function will break for filetypes which don't have a proper formatter available. This is why the bug might not show up in all use cases.

I initially discovered this breakage in functionality while editing a `fish` file, and then later on noticed that normal text files do not get trimmed either (for instance).

It would seem that some change in 1.19 made these two settings incompatible with each other. That is my assumption, at the very least.

**Comment by seiks** [comment]
And just to confirm, I reran this same experiment with 18.1 again and it trims everything properly with just the aforementioned settings enabled (and nothing else).

**Comment by bpasero** [comment]
@seiks I can reproduce in stable, weird indeed. I can however not reproduce in insiders so it looks like this is fixed, even though I am not sure what change fixed it.

**Steps:**
* configure `editor.formatOnSave: true`
* configure `files.trimFinalNewlines: true`
* open a plain text file
* add multiple new lines at the end
* save

=> new lines are not removed in stable, but in insiders

/cc @jrieken

**Comment by seiks** [comment]
I can confirm. I can neither reproduce this in insiders, so we are all good. 👍
