### ISSUE TITLE
Add a view to the explorer that contains functions that were navigated to

### ISSUE THREAD

**Issue by chenyong** [microsoft/vscode#41258]
This is a suggesting trying to make going back and forward among code more natural.

### Current problem

* "Go to Definition" and "Go Back" are great features. However they are not obvious. Most the time you just forget what's in the history.

* There are cursor movements during operations, VS Code will navigate to a previous cursor position after calling "Go Back", which is not ideal.

### A tool to learn from

This is a common problem in navigating among code. I got some ideas and sorted it out into a [post](https://medium.com/cirru-project/stack-editor-programming-by-functions-a961f1d9555c). My solution is listing functions in the sidebar, which makes is really clear which functions I can navigate to:

![](https://cdn-images-1.medium.com/max/1000/1*Yv5HN8g7JKft6qQZGXIh0w.jpeg)

And exactly, this idea came from IDEs, which I mean JavaScript DevTools. You add a break post, and all related functions are listed, which makes it super easy to navigate among these functions related to the code we currently work on:

![](https://cdn-images-1.medium.com/max/1000/1*Tjz0YJYnC8qA-iNklRaOgQ.png)

I tried it out with my own [editor](https://github.com/Cirru/cumulo-editor/), and it works quite well(combined with quick navigate `Command P`). In stead of opening files and navigate to function and edit, I prefer better opening the functions directly and go back/forth:

![](https://pbs.twimg.com/media/DLSnJ0FVAAA0Ehd.png:large)

### Possible solution

So maybe we would add a new icon under "Explorer" icon, which links to a new panel displaying opened functions. Since function are listed, navigating would be natural enough.

![687474703a2f2f7673636f64652d646f6373312e72656164746865646f63732e696f2f656e2f6c61746573742f676574737461727465642f696d616765732f75736572696e746572666163652f6c61796f75742e706e67](https://user-images.githubusercontent.com/25790987/35138433-7ecd9004-fd29-11e7-8274-7a91cd63866a.png)

**Comment by chenyong** [comment]
I believe #5605 is a different feature. 5605 wants the possibility of of displaying definitions in current file, which I roughly achieve by calling "Go to Symbol in File..." to get the list. What is described in this issue is listing the call stack function of a deep inside function, those functions are from different files but connected by function callings.

**Comment by intijk** [comment]
I agree with @chenyong , #5606 is a different feature, what he request here is to `go back to function definition` instead of `go back to stupid last cursor potion`

Same request here.

**Comment by bpasero** [comment]
Oh I see, you want to display the functions you have navigated to.

**Comment by chenyong** [comment]
@bpasero yep.

https://github.com/Microsoft/vscode/issues/27112 is related to my issue. I want to **go back by functions**, rather than by cursors(which is the only go back solution at current). Visualizing the functions is like its next step.

**Comment by tommai78101** [comment]
Does this issue also means, we can see highlighted functions in the editor, just by putting a text cursor on the function name that's being used?

As in:

1. If you put a cursor on the function, the sidebar will highlight the function, as well as in the minimap (arrow pointing towards it).

![image](https://user-images.githubusercontent.com/6444116/39578354-f655f63c-4eb1-11e8-8912-d9f747fabeea.png)

2. And then you can see all places where the function is used in the sidebar, like so:

![image](https://user-images.githubusercontent.com/6444116/39578325-deec787c-4eb1-11e8-8730-e96434e26bda.png)
