### ISSUE TITLE
vs code editor become colorful

### ISSUE THREAD

**Issue by sunjiayu12** [Microsoft/vscode#41260]
- VSCode Version: 1.19.1
- OS Version: Ubuntu 17.04

There are a lot of times when I logout and re-login, there are some "colorful" regions in my Visual Studio Code Editor interface, as is shown [here](https://stackoverflow.com/questions/48123827/how-to-deal-with-visual-studio-code-colorful-bug-in-ubuntu)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@Tyriar any idea of this issue, I'm afraid it's a canvas issue.

**Comment by rebornix** [comment]
@sunjiayu12 can you try to open https://microsoft.github.io/monaco-editor/ in chromium and see if you see the same problem?

**Comment by sunjiayu12** [comment]
@rebornix Thanks, I tried to open Monaco Editor in chromium and Firefox, logged out, waited for some time, and logged in, but there were no same problem. 
And I found that, the probability of this bug has positive correlation with the time of logout. If I logout and re-login instantly, this problem doesn't happen:smile:

**Comment by jeffhuys** [comment]
@sunjiayu12 do the regions stay until you restart VSCode? Can you "wipe away" the regions by, for instance, scrolling?

**Comment by Tyriar** [comment]
This is a Chromium issue and we typically close these off. Forcing a refresh of the canvases will fix it, zooming in and out will do: tctrl++, ctrl+-
