### ISSUE TITLE
click through tooltips (or make them go away after mouse leaves)

### ISSUE THREAD

**Issue by ad8e** [Microsoft/vscode#41269]
- VSCode Version: 19.1
- OS Version: Windows 8.1
- C/C++: 0.14.5

On mouseover of code, an intellisense bubble appears, like so:

![bubble](https://user-images.githubusercontent.com/19739817/34638189-a19bea44-f294-11e7-9587-6c2161125a73.png)

These bubbles don't do much when clicked, but they get in my way when I try to click things under them. I would prefer if clicks passed through these bubbles, or if the bubbles disappeared when the mouse leaves the original text (there seems to be special code to persist the bubble when the mouse transfers to it). The info in the bubbles is useful, but the click obstruction is not.

From Microsoft/vscode-cpptools#1413

**Comment by alexandrudima** [comment]
Today, the hover tooltip is clickable, as the text inside it is selectable (can be copy pasted). That is the reason why the hover doesn't disappear when moving the mouse over it and it "sticks around".

@stevencl if you have addition input.

**Comment by ad8e** [comment]
To give some insight on how often select-in-tooltip is used, the bottom third of a single-line tooltip fails to select text when clicked (VSC 1.19.1, Windows 8.1, C/C++ 0.14.5. separate bug which is unreported). Anybody trying to select in a tooltip would have immediately noticed this huge region being unclickable, and all tooltips from the C/C++ extension are single lines. Since this bug isn't reported, that presumably means that nobody cares about selecting in tooltips within C/C++.

**Comment by ad8e** [comment]
Implemented in new setting in 1.25: editor.hover.sticky.
