### ISSUE TITLE
Multiple Cursors feature not working anymore on Windows Alt + Click

### ISSUE THREAD

**Issue by hashguide** [Microsoft/vscode#41267]
- VSCode Version: 1.19.1
- OS Version: Windows 10

Steps to Reproduce:

1. Multiple cursors Alt + Click used to work flawlessly, but now does not work on Windows 10
2. Tried restarting vscode and OS with no luck

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexandrudima** [comment]
Have you customized the setting `editor.multiCursorModifier` ?

**Comment by hashguide** [comment]
That is the answer I was looking for! I searched google, but I guess had the wrong keywords. Thank you!

One of my extensions must have changed the setting because I do not remember ever messing with that setting. Whatever extension that was, `CtrlCmd` is now the correct button.
