### ISSUE TITLE
Implement Increase Indent and Decrease Indent feature

### ISSUE THREAD

**Issue by VivekmanikandanD** [Microsoft/vscode#41262]
Please implement Increase Indent and Decrease Indent feature as available in Visual Studio which will be very helpful for aligning the codes.

**Comment by usernamehw** [comment]
Select text => <kbd>Tab</kbd> / <kbd>Shift</kbd>+<kbd>Tab</kbd> ?

**Comment by VivekmanikandanD** [comment]
Hey thanks for the help.. It works perfectly.
