### ISSUE TITLE
-w/--wait not working on ubuntu from zip

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4126]
- OS Version: ubuntu 14.04

Steps to Reproduce:

1. download latest code-alpha.zip
2. unzip
3. run in (default ubuntu terminal) <unzipped>/code-alpha
4. > it seems to be waiting without `--wait` option. also, `--help` isn't working. it always prints
```
bash: no job control in this shell
parallels@ubuntu:~/Downloads/VSCode-linux-x64$ ./code-alpha --help
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
parallels@ubuntu:~/Downloads/VSCode-linux-x64$ ^C
```

**Comment by bpasero** [comment]
@Tyriar is the idea that this only works when you install from deb to get the script? should we do something for the Linux zips to get this too?

**Comment by Tyriar** [comment]
@bpasero yes, the zip doesn't contain the launcher. I'm wondering whether we should even ship the zip at all anymore since the deb and rpm files are just archives, including everything in the zip plus more. See https://github.com/Microsoft/vscode-website/issues/73#issuecomment-195578442

**Comment by bpasero** [comment]
@Tyriar well we also ship the zip for windows for those people that really want to have just the app (e.g. also for portable usecases), so I think we should not offer the zip as primary download on the web site but as alternative. @chrisdias fyi
