### ISSUE TITLE
In the terminal, why fonts will change?

### ISSUE THREAD

**Issue by reaCodes** [Microsoft/vscode#41266]
- VSCode Version: 1.19.1
- OS Version: Windows 10

Steps to Reproduce:

1. run `123`

![image](https://user-images.githubusercontent.com/13817254/34661108-4440d0cc-f482-11e7-8102-1c361a160834.png)

2. run `123abc`

![image](https://user-images.githubusercontent.com/13817254/34661120-63884ea6-f482-11e7-85ff-bb672aeb3201.png)

You can see `123` changes from Bold to thin

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/29439
