### ISSUE TITLE
cannot install rope library on visual studio code for python for renaming symbol(F2)

### ISSUE THREAD

**Issue by desmondanh** [Microsoft/vscode#41261]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
python|ms-|0.9.1
shell-launcher|Tyr|0.1.6

(1 theme extensions excluded)

---

Steps to Reproduce:

1. create a python file
2. right click rename symbol for a variable
3. get error and guide to install rope library
4. cannot install with error:
Command ""C:\Program Files\Python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\ANHNGU~1\\AppData\\Local\\Temp\\pip-build-9kktmsku\\rope\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ANHNGU~1\AppData\Local\Temp\pip-ty2vv7yw-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ANHNGU~1\AppData\Local\Temp\pip-build-9kktmsku\rope\

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@desmondanh please file issues against the python extension you are using, thanks.

**Comment by desmondanh** [comment]
the problem is on Visual studio code when i click install when it recommended to install "rope library" it does run but with error like above.
I solved it by downloaded it manually from PyPI - the Python Package Index and install it with
"python setup.py install"
