### ISSUE TITLE
Feature request: Working sets for the file explorer

### ISSUE THREAD

**Issue by derwaldgeist** [Microsoft/vscode#41274]
Quite often, I want to focus on implementing a specific feature in a complex project with a lot of files (which may even be spread across several project roots). Navigating the tree to pick the right files gets quite tedious in these cases.

To make it easier to focus on a specific part of your code, Eclipse and Atom's Nuclide extension offer a concept called "working sets". These allow you to restrict the file tree to a set of files or folders you've selected before. I would love to see this functionality in VS Code, as this is the major feature I'm missing from Atom.

**Comment by derwaldgeist** [comment]
PS: I've seen that the similar request #10962 has been closed as a dupe of #9498, but the latter is *not* what I mean. In my case, it's all about filtering the explorer view, not about storing sets of open files.

**Comment by isidorn** [comment]
There are already Open Editors view and similar feature reqeusts.
Thus I am closing this one (I also do not see us doing something like this in the near future)

Thanks for the suggestion though

**Comment by prufrock123** [comment]
@isidorn, @bpasero - Pleeeease add this? 

I saw it is closed for consideration for the next 6-12 months. But this feature would be _so_ helpful
