### ISSUE TITLE
Visibility of Extensions Viewlet (for "when" contexts)

### ISSUE THREAD

**Issue by ebynum** [Microsoft/vscode#41276]
There is not currently a way to detect the visibility (or focus) of the "Extensions Viewlet" like there is for the Search and Explorer Viewlets.
[searchViewletVisible, searchInputBoxFocus, explorerViewletVisible, explorerViewletFocus]

My use-case for this is to allow intelligent toggling of the sidebar viewlets (roughly like https://github.com/Microsoft/vscode/issues/41186), although I suspect there are other uses for the visibility and focus when clause contexts.

My requested names would be extensionsViewletVisible, extensionsViewletFocus, and extensionsInputBoxFocus, although the singular names would work equally well.

**Comment by ramya-rao-a** [comment]
Is this still meant for the January milestone? If not, can you move it to February milestone?

**Comment by sandy081** [comment]
@ebynum Context for active viewlet is already available. Check [here](https://code.visualstudio.com/docs/getstarted/keybindings#_active-view-or-panel-when-clause-context)

**Comment by ebynum** [comment]
@sandy081 That's perfect. (It didn't exist in January when the ticket was created.)
