### ISSUE TITLE
"Open to Side" no longer works from explorer or problems view

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41272]
Steps to Reproduce:

1. focus a problem in problems view
2. Hit `Ctrl+Enter` on macOS

=> problem is not opened to the side

It looks like there is a [`MarkerFocusContextKey`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/markers/common/constants.ts#L14) required for this but I never see it set when the problems viewer gets focus.

/cc @joaomoreno

**Comment by bpasero** [comment]
Looks like it also does not work for the explorer. I think the [`onFocusChange`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L153) is never fired?

**Comment by joaomoreno** [comment]
The `problemFocus` is correctly set.

**Comment by bpasero** [comment]
Looking into the explorer issue...

**Comment by bpasero** [comment]
@isidorn please check my change in https://github.com/Microsoft/vscode/commit/52e2c4227eb41c208708829bd9bf3d1092a9fad9

**Comment by isidorn** [comment]
@bpasero this looks good. To be sure I have pushed https://github.com/Microsoft/vscode/commit/726774a832322bd537202fdeb0ae44bf2ed8c349 for other commands
Why did you give the command a bigger workbench weight of 50?

**Comment by bpasero** [comment]
@isidorn this is a consequence of [`list.select`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/commands.ts#L273) being defined with the same keybinding. This is not ideal and maybe a bit of debt, but this requires to "override" the command with a more specific one as done for the explorer (and e.g. also problems view or search).
