### ISSUE TITLE
Terminal fails to render command output

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#41281]
1. Open Terminal
2. Press <kbd>Enter</kbd> consecutively until you reach the bottom of the terminal's view port
3. Run any command

No output is provided

I saw this first by running a long `git status` command:

![kapture 2018-01-08 at 12 25 13](https://user-images.githubusercontent.com/22350/34668763-1121745c-f46f-11e7-98e9-6b2b4673207e.gif)

**Comment by Tyriar** [comment]
All 3 reports are on mac so far, not sure if that's a coincidence or not

**Comment by Tyriar** [comment]
Managed to repro:

<img width="342" alt="screen shot 2018-01-08 at 9 23 16 am" src="https://user-images.githubusercontent.com/2193314/34683001-9c30677a-f455-11e7-9336-a95411d6f257.png">

**Comment by Tyriar** [comment]
It appears to only happen sometimes

**Comment by nabeelomer** [comment]
Its actually been happening all the time with me.

**Comment by Tyriar** [comment]
Current thinking is it's a race condition in `RenderDebouncer` https://github.com/xtermjs/xterm.js/pull/1182/commits/a846e8c08d323cebecf542af37865ba57c06041e

**Comment by Tyriar** [comment]
Found the problem, bad implicit type check: `0 !== null`

**Comment by Tyriar** [comment]
Pushed the fix, will be fixed in tomorrow's insiders. For curious parties here's the fix https://github.com/xtermjs/xterm.js/pull/1182/commits/a19b05f8139754069fdd2bf0387b6111f92905ac

**Comment by Tyriar** [comment]
As a workaround in the meantime I think pressing enter/resizing the terminal should fix the problem
