### ISSUE TITLE
Funny behaviour in the integrated terminal

### ISSUE THREAD

**Issue by nabeelomer** [Microsoft/vscode#41283]
- VSCode Version: January 2018 (version 1.20) Insiders
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Open the integrated terminal.
2. Fill the terminal with text so that it needs to auto-scroll.
3. `ls`
4. Notice that no output appears.

Does this issue occur when all extensions are disabled?: Yes
  
  [A screen recording of the bug](https://drive.google.com/file/d/1jv2ypwCXNwszl4Xq4WSJHUf1yb2EVI6t/view?usp=sharing).

**Comment by Tyriar** [comment]
Can you check the commit of your insiders release (Code - Insiders > About).

Might be the same as https://github.com/Microsoft/vscode/issues/41300

**Comment by Tyriar** [comment]
It does indeed look like the same issue, see https://github.com/Microsoft/vscode/issues/41281
