### ISSUE TITLE
Language support for Antler

### ISSUE THREAD

**Issue by bgarrant** [microsoft/vscode#41282]
I have had this same issue for a while now and wondering if there is a work around. When I use a custom language syntax like Antlers (https://marketplace.visualstudio.com/items?itemName=ahdesign.language-antlers) for example, the HTMl Autocomplete (Intellisense) no longer functions.  If I associate `antlers` with `html` then I lose the antlers syntax coloring.  How can I get both Antlers (or any other language) to work alongside the HTML Intellisense since the file has an .html extension?

I am using Latest VSC 1.19.1 on a 2017 MBP High Sierra

**Comment by bgarrant** [comment]
This works in other editors such as Atom so can't figure out why VSC can get this to work? Wether I am using a Twig or Antlers extension, same issue.  No HTML Autocomplete or Intellisense.

Type `<div class` and you will get nothing but text suggestions. and it does not even complete the `<div class="">`.

**Comment by bgarrant** [comment]
It all comes back to the mixed language issue.  It seems VSC as no way to natively do this.  Once I enable another language this is what I get for HTML autocomplete when typing `<d`

![screen shot 2018-01-08 at 11 49 58 am](https://user-images.githubusercontent.com/2436728/34688147-1e753872-f47f-11e7-8b71-09ffc3acd4b2.png)

**Comment by bgarrant** [comment]
When in plain HTML mode on same file I lose the Antlers syntax coloring but I get this when typing same `<d`.

![screen shot 2018-01-08 at 11 55 20 am](https://user-images.githubusercontent.com/2436728/34688201-5f01ab1e-f47f-11e7-86b7-5ec535a7acfc.png)

**Comment by bgarrant** [comment]
Is there any way to use two languages together?

**Comment by aeschli** [comment]
The clean way is if there's an Antler extension that implements a proper Antler language server, or forwards all requests to HTML (if Antler really compatible with HTML)

**Comment by aeschli** [comment]
Proper Antler support should come from a Antler language server. See https://github.com/microsoft/vscode/issues/47288 on why this is the best solution.

We have https://github.com/microsoft/vscode/issues/49210 to think about how a simpler story to basic HTML support working in HTML template languages that don't have a language server.
