### ISSUE TITLE
[JavaScript] Functions indented incorrectly with formatOnSave

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#41288]
When using the 
```json
	"[javascript]": {
		"editor.formatOnSave": true
	},
```
setting

```js
const foo = ({
	x,
	y
}) => ({
	y: x,
	x: y
});
```

gets formatted to

```js
const foo = ({
	x,
	y
}) => ({
		y: x,
		x: y
	});
```
Which breaks eslint

`[eslint] Expected indentation of 1 tab but found 2. (indent)`

----

Version 1.19.1

tested without extension (`code --disable-extensions .`)

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/21068 to track this upstream
