### ISSUE TITLE
[folding] Go To Line doesn't scroll to desired line when the code is collapsed

### ISSUE THREAD

**Issue by guilhermeagostinelli** [Microsoft/vscode#41286]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: none
---

Steps to Reproduce:

1. Collapse a piece of code.
2. Hit Ctrl+G and type the number of one of the hidden lines.

When doing that, the cursor gets positioned correctly, but the screen gets scrolled to the collapsible line and not to the desired line.

**Comment by aeschli** [comment]
This work for me:
- close a folding region (e.g. from line 10 to 20)
- open the `Go to Line` command (or Ctrl + G)
- enter 15. -> Editor scrolls, folding region not yet open
- press enter -> region opens, cursor placed on line 15.
