### ISSUE TITLE
terminal lineHeight property not work

### ISSUE THREAD

**Issue by koutsenko** [Microsoft/vscode#41284]
I've illustrated it. For editor and terminal I used a lineHeight = 11 value.
In editor it works, but in terminal it fails.
VSCode 1.19.1, W10x64.

<img width="708" alt="screen1" src="https://user-images.githubusercontent.com/529293/34669795-8bfe566c-f484-11e7-8d10-2c4e8f575ba7.png">

**Comment by Tyriar** [comment]
This is working as designed:

![image](https://user-images.githubusercontent.com/2193314/34682445-cf6badcc-f453-11e7-9faa-a1613bf81b80.png)

It's a little weird that the format is different but that's the way it was implemented upstream. Even if it was supported it's not possible to use a `lineHeight` less than the `fontSize` of  for technical reasons so I'll close this off.

**Comment by koutsenko** [comment]
OK, "as designed"...
Also, the multiplier less than 1 doesn't work.
