### ISSUE TITLE
Standalone editor: error spans don't update on typing

### ISSUE THREAD

**Issue by rchande** [Microsoft/vscode#41299]
I'm hosting the standalone Monaco editor and calling monaco.editor.setModelMarkers to show squiggles underneath errors. In my particular scenario, I don't compute diagnostics every time the user types, but instead when they explicitly click a button. When they click the button, my squiggles appear in the correct location. However, as the user types, the squiggles stay in one place.

For example, imagine I had tagged the second token of this line with an IMarkerData:
```token1 [token2]```. 

That's the span 8...14.
If the user starts typing at the start of `token1`, the editor continues to tag span 8...14 and I wind up with something highlighted like
```123tok[en1 tok]en2```.

It would be nice if the editor could automatically move the span start forward to produce
```123token1 [token2]```

Is there a way to get the standalone monaco editor to automatically track IMarkerData spans forward and backward as the user types? I think I could probably subscribe to the model text changed event and do this myself...

**Comment by alexandrudima** [comment]
The editor does that. 

Errors are tracked ranges. 

My guess is you are calling `monaco.editor.setModelMarkers` with stale data.

**Comment by alexandrudima** [comment]
working example: https://microsoft.github.io/monaco-editor/playground.html

```
 var ed = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});
monaco.editor.setModelMarkers(ed.getModel(), 'asd', [{
    startLineNumber: 1,
    startColumn: 2,
    endLineNumber: 1,
    endColumn: 5,
    message: 'hello'
}])
```
