### ISSUE TITLE
Issues with polyfills in extensions

### ISSUE THREAD

**Issue by remojansen** [Microsoft/vscode#41297]
The [official vscode python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) recently experimented [some issues](https://github.com/Microsoft/vscode-python/issues/432) caused by a polyfill.

The polyfill is the [`reflect-metadata`](https://github.com/rbuckton/reflect-metadata) module. This module overrides the `Reflect` global object. Every time the `reflect-metadata` is imported, the `Reflect` global is overwritten. This is a problem because this global object allows us to define metadata and it contains an internal `WeakMap` that stores the metadata. When the global is overwritten, the `WeapMap` is also overwritten and all the metadata is deleted.

If two extensions import `reflect-metadata`, one will remove the metadata created by the other.

We can fix this by changing the polyfill (`reflect-metadata`) source code but if some extension is using an outdated version or some extension is using a different polyfill we will have the same problem.

So I was wondering if it is possible for the vscode extensions runtime to isolate the globals between extensions? or prevent polyfill-related issues?

cc: @DonJayamanne

**Comment by jrieken** [comment]
> So I was wondering if it is possible for the vscode extensions runtime to isolate the globals between extensions?

The idea is cool but I am afraid it's too late for that. We don't know what extensions/node_modules actually depend on something like that and we wouldn't wanna break them... The only option we have to fix this at the source, e.g at reflect-metadata

**Comment by remojansen** [comment]
@jrieken thanks for the help. Will see if I can try to get a fix merged into reflect-metadata.

**Comment by remojansen** [comment]
The issue in reflect-metadata has been fixed. More info at https://github.com/inversify/InversifyJS/issues/737#issuecomment-358064760
