### ISSUE TITLE
vscode-ripgrep CPU 100%

### ISSUE THREAD

**Issue by caobingsheng** [Microsoft/vscode#41291]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.CPU   87℃     -_-|||

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please provide enough details to repro the issue.
