### ISSUE TITLE
Opening output panel should flush buffer without delay

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4129]
I find it weird that opening the output channel appends the last output only after the 300ms delay. This makes it feel as if the output came in just at the time you open the panel. I suggest to just take whatever is in the buffer at that time and append it.

Refs: https://github.com/Microsoft/vscode/issues/3926

**Comment by isidorn** [comment]
@bpasero Why do I think I do this, I think I do the proper thing [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputEditorInput.ts#L120)
I do not do any scheduling for the initial `setOutput`
