### ISSUE TITLE
Document Tabs Scroll - inconvenient and barely visible

### ISSUE THREAD

**Issue by nkernytskyy** [Microsoft/vscode#41295]
When more document tabs are open than the window width can fit, some tabs are hidden and can be navigated to by using the horizontal slider.

This **tabs slider** (horizontal scroll) is very thin and is invisible until hover, so I'd prefer **the slider**:

- to be thicker, AND/OR
- to be visible at any time, not only when hovered, AND/OR
- to be replaced or accompanied by arrow buttons [<] [>] like in Sublime Text editor.

This is a default VS Code feature, so this is not an issue by itself, but a rather minor inconvecience.

**Comment by nkernytskyy** [comment]
![scroll](https://user-images.githubusercontent.com/35230869/34680079-9fd2cf3a-f4a0-11e7-84d5-45b7fb4ebfeb.png)

**Comment by nkernytskyy** [comment]
![sc](https://user-images.githubusercontent.com/35230869/34680150-db1b9324-f4a0-11e7-8d3d-aa5640228155.png)

-- Sublime Text solution for tabs navigation with arrow buttons [<] [>]

**Comment by nkernytskyy** [comment]
**In general** slider is cooler as it requires fewer mouse-button keystrokes, but it can be **hardly got in focus on small screens**.

**Comment by usernamehw** [comment]
In some way related https://github.com/Microsoft/vscode/issues/39059

**Comment by bpasero** [comment]
Yeah there is that issue and another one for making the slider taller.
