### ISSUE TITLE
VSCode 0.10.1 editor panel hangs on a PHP file

### ISSUE THREAD

**Issue by alessandrofrancesconi** [Microsoft/vscode#413]
After few seconds working on a PHP file, the editor panel hangs and the whole program needs to be killed.
Only the editor panel stops responding, while the menu bar can be clicked (but clicking on "Exit" doesn't produce any effect).

Task manager shows a stable 40% CPU load coming from code.exe process.

Windows 10 Pro x64 build 1511
VSCode 0.10.1

**Comment by sevaa** [comment]
Same here, started with the latest update. One comment: when I open a PHP file, I get a message: "Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'"

This might be relevant.

**Comment by alessandrofrancesconi** [comment]
Where do you get that message?

**Comment by DerTolleEmil** [comment]
This message appears when you don't have the php binary in your path variable and haven't set the path in the user settings. However, it is irrelevant in regards to the freeze. This issue sounds like a duplicate of #160

**Comment by alessandrofrancesconi** [comment]
Yes it's a duplicate, I close this
