### ISSUE TITLE
Typescript Intelisense broken in Mac

### ISSUE THREAD

**Issue by pitAlex** [Microsoft/vscode#41308]
Hello,
There is something wrong with the  Intelisense for typescript in Mac that makes really hard to work with vscode. The thing can break without any errors and when it does it won't recover until I restart the app. And even then it works for 5 minutes or so until it breaks again. 

Here is a sample of what I am experiencing : https://drive.google.com/open?id=10nFMNAuLhpyHXuC9FVPBFW9Z6bkNDp9K

This thing has been going for months now and I was hoping for a fix with every update but no luck. Its only related to typescript. The editor works fine in other languages that I used it.  Please do not come to me with "extensions related"  because I have disabled them all and it still does it. 
Help me fix this thing. I really like vscode, with everything it offers, but at this rate I will be force to look for another editor as I simply cannot do any work with it, not in typescript.

**Comment by mjbvz** [comment]
Thanks for the info. Can you please share the TypeScript server log from your session:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by pitAlex** [comment]
Hi,
I already have "typescript.tsserver.log" with "verbose" active and it does not print errors, as you can see in the clip as well.
If you still want the log file, tell me how to share it with you in private.

**Comment by mjbvz** [comment]
@pitAlex You will need to check the log file for the errors, not the output console. If you don't see anything, I can take look. Just send it to me by email: matb at microsoft.com

**Comment by pitAlex** [comment]
Hey,
I have an update, I have removed hammerjs typings and it doesn't seem to do it anymore. I made a few adjustments to not trigger errors because of missing types and now it seems to work fine.
Can typings create such issue? where there can be some conflicts or something?
