### ISSUE TITLE
Some shortcuts work on my Laptop keyboard but not on my other keyboard

### ISSUE THREAD

**Issue by YairZiv5951** [Microsoft/vscode#41301]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-python-docstring|aza|0.0.5
path-intellisense|chr|1.4.2
code-runner|for|0.8.7
terminal|for|0.0.10
vscode-power-mode|hoo|2.0.0
python|ms-|0.9.1
material-icon-theme|PKi|3.2.1
java|red|0.16.0
vscode-icons|rob|7.19.0
ayu|tea|0.11.2
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
combo-mode|yur|0.0.6

(12 theme extensions excluded)

---

Steps to Reproduce:

1. Connect a keyboard to a laptop (have 2 keyboards total, one laptop keyboard and one external
2. Try and use the ctrl + shift + p shortcut

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@YairZiv5951 

When pressing `ctrl + shift + p` on your external keyboard does VS Code receive the key combination ? Have you tried using a different external keyboard ? (I've heard of broken hardware before).

What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by YairZiv5951** [comment]
Wow, apparently that combination does not work on my keyboard. That's weird, every other combination like Ctrl+shift+key works. Well I guess the problem is on my end. Thanks!

**Comment by YairZiv5951** [comment]
Wow, apparently that combination does not work on my keyboard. That's weird, every other combination like Ctrl+shift+key works. Well I guess the problem is on my end. Thanks!

**Comment by YairZiv5951** [comment]
Wow, apparently that combination does not work on my keyboard. That's weird, every other combination like Ctrl+shift+key works. Well I guess the problem is on my end. Thanks!

**Comment by YairZiv5951** [comment]
Wow, apparently that combination does not work on my keyboard. That's weird, every other combination like Ctrl+shift+key works. Well I guess the problem is on my end. Thanks!

**Comment by YairZiv5951** [comment]
Wow, apparently that combination does not work on my keyboard. That's weird, every other combination like Ctrl+shift+key works. Well I guess the problem is on my end. Thanks!
