### ISSUE TITLE
OS-specific properties in launch configs not resolved

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41305]
In today's insiders,

- Start the launch config in the vscode repo, "Launch vs code"
- It launches Chrome and fails to attach
- Enable logging, see that the runtimeExecutable is not set because the OS-specific props are left in place - 

`From client: launch({"type":"chrome","request":"launch","name":"Launch VS Code","windows":{"runtimeExecutable":"/Users/roblou/code/vscode/scripts/code.bat"},"osx":{"runtimeExecutable":"/Users/roblou/code/vscode/scripts/code.sh"},"linux":{"runtimeExecutable":"/Users/roblou/code/vscode/scripts/code.sh"},"trace":true,"urlFilter":"*index.html*","runtimeArgs":["--inspect=5875"],"webRoot":"/Users/roblou/code/vscode"})`

**Comment by isidorn** [comment]
I can not reproduce following your steps. Do you still see this with latest from source?
If yes, do you also see this for a simple node app with the following `launch.json` for example

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}",
            "osx": {
				"program": "${workspaceFolder}/hey.js"
			},
        }
    ]
}
```

![screen shot 2018-01-09 at 11 53 33](https://user-images.githubusercontent.com/1926584/34717560-cc34a8a8-f533-11e7-819f-0815c2b2d8d4.png)

**Comment by roblourens** [comment]
Works in today's insiders.
