### ISSUE TITLE
openFilesInNewWindow no longer seems to be working

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#41302]
- VSCode Version: 1.19.1
- OS Version: OSX 10.13.2

With ```"window.openFilesInNewWindow": "off"```

It is still opening files in a new window.  I'm not sure when this stopped working as I haven't used it in a while.  I normally open JS files from Eclipse using vscode.  Now it is opening a new window each time.

**Comment by bpasero** [comment]
@dakaraphi please post exact steps to reproduce

**Comment by dakaraphi** [comment]
FYI, this seems to have been an anomaly.  After rebooting OSX this problem no longer occurs.
