### ISSUE TITLE
configure auto imports

### ISSUE THREAD

**Issue by ribrdb** [Microsoft/vscode#41304]
It should be possible to customize how auto imports are added.
Specifically I would like them added as
import {Foo} from "./foo.js"
since browsers do not add the .js.
Also, if #41303 is fixed it would be nice to be able to add absolute imports instead of relative.

**Comment by mjbvz** [comment]
Tracked by https://github.com/Microsoft/TypeScript/issues/19019

The new expected behavior is to add filenames to import paths if other imports in the file also use them
