### ISSUE TITLE
Integrated Terminal output delayed

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#41300]
- VSCode Version: Insider
- OS Version: macOS

![ll](https://user-images.githubusercontent.com/876920/34681802-ca6be622-f451-11e7-8be5-2917756bca82.gif)

**Comment by rebornix** [comment]
After typing at the last line, I didn't get any result, can't scroll down as well. Then I scroll up and scroll back, the contents are generated finally.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/41281
