### ISSUE TITLE
"Go to Symbol in Workspace" only working with currently open files

### ISSUE THREAD

**Issue by jsonMartin** [Microsoft/vscode#41319]
- VSCode Version: 1.19.1
- OS Version: Mac OS 10.13.2

Steps to Reproduce:

1. Open a Javascript (or more specifically, React) project, and ensure no files are open.
2. "Go to Symbol in Workspace" for a function that definitely exists. It returns no results, saying "No symbols matching".
3. Now, open the file containing the function, and repeat the above step to search for the function symbol in the workspace. Note that it is available now.
4. When closing the file, the symbol is no longer accessible when using the "Go to Symbol in Workspace" menu.

Workspace based "Go to Symbol" search is working fine for me with a different PHP based project, but not at all with these Javascript projects (I've tried two different JS projects, with both current and Insiders build). 

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mjbvz** [comment]
Try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your workspace:

```js
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This tells VS Code to treat all js files in your workspace as part of the same project
