### ISSUE TITLE
Undo and staged changes in SCM

### ISSUE THREAD

**Issue by zygimantas** [Microsoft/vscode#41312]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
bracket-pair-colorizer|Coe|0.10.14
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.24
beautify|Hoo|1.1.1
csharp|ms-|1.13.1
team|ms-|1.122.0
vscode-icons|rob|7.19.0

---

Steps to Reproduce:

1. Open any file which is already in source control.
2. Switch to Source Control window (SCM) in VSCode.
3. Edit a file and save. As expected, the file will be included in "Changes" list.
4. Add file to "Staged Changes".
5. Edit the same file and undo the change. Save.

Actual result:

The file stays in "Staged Changes" list even there are no actual changes.

Expected result:

The file should be gone from "Staged Changes" as it is removed from the "Changes" in the same situation.

Reproduces without extensions: Yes

**Comment by zygimantas** [comment]
I even had a situation when the same file was in both, "Changes" and "Staging Changes". After clicking + in "Changes", the file was gone from both lists.

**Comment by joaomoreno** [comment]
This is how git works.

More info: https://git-scm.com/book/en/v2/Getting-Started-Git-Basics#_the_three_states
