### ISSUE TITLE
Integrated terminal swallows text sometimes

### ISSUE THREAD

**Issue by kdheepak** [Microsoft/vscode#41311]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (b811600ecc57992a82a1f50ed9bf128065bc8787, 2018-01-08T09:35:04.606Z)</li>
	<li>OS Version: Darwin x64 16.7.0</li>
	<li><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
quick-open-file|Ala|0.1.2
bracket-pair-colorizer|Coe|0.10.14
vsc-material-theme|Equ|1.2.0
matlab|Gim|0.8.0
output-colorizer|IBM|0.1.2
code-settings-sync|Sha|2.8.7
omnipascal|Wos|0.15.0
Bookmarks|ale|0.18.0
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
vscode-new-file|dku|4.0.1
githistory|don|0.2.3
tslint|eg2|1.0.24
code-runner|for|0.8.7
Python-autopep8|him|1.0.2
vue-snippets|hol|0.1.5
path-autocomplete|ion|1.8.0
language-julia|jul|0.9.1
cmake-tools-helper|mad|0.1.1
vscode-clang|mit|0.2.2
python|ms-|0.9.1
cpptools|ms-|0.14.5
debugger-for-chrome|msj|4.0.0
gitlink|qez|0.4.2
subtle-brackets|raf|2.1.0
typescript-hero|rbb|1.8.0
vscode-icons|rob|7.19.0
gi|rub|0.2.11
vscode-table-formatter|shu|1.2.1
vscode-multiclip|sle|0.1.3
guides|spy|0.9.1
cmake|twx|0.0.17
vim|vsc|0.10.8
vscode-todo-highlight|way|0.5.11

(4 theme extensions excluded)

</details></li>
</ul>
---

Steps to Reproduce:

1. Run a command that fills text in the screen
2. Run another command that is supposed to output text

![animation](https://user-images.githubusercontent.com/1813121/34691336-866d260c-f479-11e7-9fa3-6d441a7119a8.gif)

The same thing happens when I launch code with extensions disabled.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/41281, should be fixed in tomorrow's build

**Comment by kdheepak** [comment]
Thanks!
