### ISSUE TITLE
FileSystemProvider: workbench load hangs on remote files

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#41322]
- VSCode Version: 1.20.0-insider (f9115349ef09cfef2bed669680d10ac58b490dce, 8697a5e4ec152832a2612929c87d56302dbb2e79)
- OS Version: Mac 10.13.1

Steps to Reproduce:

1. Register an extension with a file system provider
2. Launch the extension
3. Open a saved workspace
2. Open some remote files
3. Close the launched instance (not sure if the issue is caused by a particular way I closed the instance.... kind of a pain to test this when I don't know how to reset the workspace state.)
4. Relaunch vscode
4. Observe:
    * vscode shows tabs for the remote files, but displays a progress bar in the editor and explorer areas.
    * dev tools console: "WARN Workbench did not finish loading in 10 seconds, that might be a problem that should be reported."
    * after several minutes, no extensions have been activated yet; nothing loads.

There doesn't seem to be any way to get vscode to load the workspace without recreating the workspace file. (Is there a way to reset the state of a workspace so vscode doesn't try to reopen the remote files?).

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@jrieken @isidorn this could be a consequence of us not starting the extension host until files are loaded? We do not load the extension host until all editors are restored but of course, if the editors need the extension host for loading this will not work anymore...

**Comment by jrieken** [comment]
ops

**Comment by bpasero** [comment]
@jrieken I wonder if we could lift the requirement that the editor has to be done loading for the workbench to signal the started phase (same applies to viewlet loading which would probably also result into this issue).

The ugly thing is that this might mean that we have to start the extension host while the editors are restoring (which is what we had before).

**Comment by jrieken** [comment]
Yeah, I think we should block on restoring, e.g. setting the editor inputs, but not on waiting for the inputs to resolve. We could simply not return [this promise](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L334) but it only the containing code.

**Comment by jrieken** [comment]
@bpasero I have pushed 876b47a9bd as workaround to unblock us

**Comment by bpasero** [comment]
@jrieken maybe a better fix is to do what you did and also not wait for any viewlets to restore. On top of that I would maybe still introduce a little delay before declaring the workbench as “running”, simply to delay execution of all the tons of things after the viewlet and editor had a little bit of chances to do their work. Otherwise we basically are back to were we came from when everything blocked the editor/viewlet restore.

I still have to check if there is anyone relying on the editor or viewlet to be fully restored, but I don't think so.

**Comment by bpasero** [comment]
I pushed a change that:
* moves all lifecycle phase business into shell in one place
* sets `Phase.Restoring` after 800ms after startup or if the startup of the workbench was faster, right before the `Running` phase
* puts extension host business back to `Phase.Restoring`

**Comment by jrieken** [comment]
> sets Phase.Restoring after 800ms after startup or if the startup of the workbench was faster, right before the Running phase.

Not sure that's a good design as it waters down the meaning of lifecycle phases. Now more have the fuzzy characteristics of 'Eventually'. @bpasero Isn't it enough to have this logic in the extension host manager? So, 800ms after Restoring or on Running start extensions etc? Are there other components that need this behaviour?

**Comment by bpasero** [comment]
@jrieken yeah I can move the delay into the extension host, that is pretty much the only guy we have that can slow down the `Restore` phase.

**Comment by chrmarti** [comment]
Verified with a local ftp server.
