### ISSUE TITLE
'null' shows in title

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4132]
* on linux, use code for `git difftool <commit>`
* notice that the header shows `null`

![screen shot 2016-03-14 at 13 56 46](https://cloud.githubusercontent.com/assets/1794099/13745147/bc174c86-e9ec-11e5-8782-146c45b6a723.png)

**Comment by jrieken** [comment]
this actually happens whenever I start with just `code-alpha` and not have a file/folder identifier, like `code-alpha .`

unsure if this is for @bpasero or @Tyriar

**Comment by bpasero** [comment]
@jrieken can you check if your "current workspace" is /dev/null? I think I have seen this on Mac already before.

**Comment by jrieken** [comment]
don't think so. I was running the git difftool command from a folder on my desktop and then ran code-alpha from inside that dir

**Comment by bpasero** [comment]
@jrieken pushed a change that when diffing we always have an empty workspace. however if you can still find a case where "null" opens, please reopen. If am quite sure this is a case where /dev/null is passed as path to VS Code. This might have happened with one of the other ways of using VS Code as tool (e.g. git rebase, git config or git add -p).
