### ISSUE TITLE
Break points not sticking in gutter

### ISSUE THREAD

**Issue by meMuszr** [Microsoft/vscode#41325]
- VSCode Version: 1.20.0-insider [5153c9aa420bc235b463b773881b2871c8d22566]
- OS Version: Debian (buster) x64 - 4.14.0-2

Steps to Reproduce:
1. Clone [repo](https://github.com/meMuszr/vscode-inside-debug-bug)
2. Debug in latest vscode-insiders

Does this issue occur when all extensions are disabled?: Yes

When I hover over the gutter to set a breakpoint, I get a red dot for the line I'm on and clicking to set it, the breakpoint shows up in the breakpoints list in the debugger side-panel yet doesn't stick on the gutter of the file. 

With the breakpoints activated in the list -- debugging still does not work; although -- changing the stopAtEntry field in the configuration for launch.json to true does stop the program with the main() in the call stack, however no panel to continue, stop, step over / into. Leaving me to stop the program manually from the terminal.  

Downloading and installing the stable release [1.19] does resolve the issue.

**Comment by isidorn** [comment]
This should be fixed in latest vscode insiders
