### ISSUE TITLE
Why is code always backspacing if typing is delayed?

### ISSUE THREAD

**Issue by DouglasAllen** [Microsoft/vscode#41327]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
p5js-snippets|aci|0.0.6
AzureFunctionsSnippets|ahm|0.1.0
makeRunner|ale|0.1.1
gherkin-indent|Ara|2.0.0
erb|Cra|0.0.1
vscode-markdownlint|Dav|0.12.0
empty-indent|Dmi|0.2.0
vscode-nupkg|eri|0.0.8
prettier-vscode|esb|1.0.1
extbundles-csharp|Fel|1.1.0
code-runner|for|0.8.7
haml|gro|0.0.2
AzureFunctionsSnippets|hha|0.1.0
ruby-linter|hoo|1.0.0
cs-syntax-visualizer|itn|0.0.2
csharpextensions|jch|1.3.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
vscodeilviewer|jos|0.0.1
indentation-level-movement|kai|1.1.1
vscode-schema|kuk|0.4.1
csharpfixformat|Leo|0.0.54
MagicPython|mag|1.0.12
Runner|mat|0.1.14
ruby-symbols|mig|0.1.5
ruby-rubocop|mis|0.5.0
python|ms-|0.9.1
csharp|ms-|1.13.1
azurerm-vscode-tools|msa|0.3.7
indent-rainbow|ode|0.7.2
twospacefourspace|Ohm|0.2.1
vscode-versionlens|pfl|0.19.1
vscode-erlang-workbench|pro|0.0.9
Ruby|reb|0.15.0
reloaded-cpp|rel|0.1.6
vscode-paste-and-indent|Rub|0.0.8
aspnet-helper|sch|0.6.4
indenticator|Sir|0.4.2
guides|spy|0.9.1
python|tht|0.2.3
haml|vay|1.0.1
markdown-pdf|yza|0.1.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by DouglasAllen** [comment]
I'm getting annoyed with whatever feature this is supposed to be. I'm not a touch typist and so I expect my cursor to stay put until I do type something. Please tell me how to get rid of this stupid feature. Who and why is it there? I'm very angry. This is polite for me.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
