### ISSUE TITLE
Some mongo shell output is discarded in vscode terminal when it is running on windows

### ISSUE THREAD

**Issue by zhaoyi0113** [Microsoft/vscode#41324]
- VSCode Version:   1.19
- OS Version:  windows 10 pro

Steps to Reproduce:

1.   Open vs code on windows 10 pro 
2.   Open a terminal on vs code
3.   Run a mongo shell command on that terminal to connect to a mongo server. What I did is run 
       `mongo mongodb://localhost:27017`
4.   Run below command in the mongo shell:
      > db.test.explain().find()
5.   You should see a JSON data output. Try to run the same command multiple times, then you will see an incomplete output followed by the mongo shell prompt. After that, run the same command again it won't return any output. This command works fine if I run a native window batch terminal.

Does this issue occur when all extensions are disabled?: Yes/No [Yes]

**Comment by zhaoyi0113** [comment]
I attached below screenshot for this issue.

<img width="867" alt="capture" src="https://user-images.githubusercontent.com/3355579/34704627-8b659920-f54e-11e7-99d8-34bde04c6122.PNG">

**Comment by guiguan** [comment]
this only happens on Windows version of vscode

**Comment by Tyriar** [comment]
@zhaoyi0113 are you sure you weren't on 1.20 insiders? This looks a lot like https://github.com/Microsoft/vscode/issues/41281

**Comment by zhaoyi0113** [comment]
@Tyriar  This is different than #41281. First, it happens only on windows. Second, once the issue happens, I can get correct output from some other command like `show dbs`. But I can't get any output from this command `db.test1.explain().find()`. Resize/Enter doesn't solve the issue. It can be easily reproduced if you have a mongo server running.

**Comment by Tyriar** [comment]
Could you try reproduce using the xterm.js demo? https://github.com/xtermjs/xterm.js

If it happens you can run `term.setOption('debug', true)` in the devtools console and listen to what mongo is sending over to the terminal.

**Comment by Tyriar** [comment]
Upstream https://github.com/Tyriar/node-pty/issues/170

**Comment by zhaoyi0113** [comment]
I put a screenshot on that. It does happen on xterm demo. After enable debug mode, I couldn't see any output from the console. But if I open a native command window, it works perfectly. I think xterm is using `node-pty` underneath, so it has the same behavior as I reported.

![image](https://user-images.githubusercontent.com/3355579/34922119-aa43d4de-f9df-11e7-86fc-736fdc76b04c.png)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
