### ISSUE TITLE
missing syntax highlights for md-headers

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4133]
see attached screen capture

![screen shot 2016-03-14 at 14 03 00](https://cloud.githubusercontent.com/assets/1794099/13745286/8b1ff712-e9ed-11e5-9951-bfce2a35555d.png)

**Comment by jrieken** [comment]
![screen shot 2016-03-21 at 12 26 35](https://cloud.githubusercontent.com/assets/1794099/13917301/2c31744c-ef60-11e5-9ed8-5a05e2384b07.png)

**Comment by jrieken** [comment]
nothing in the light theme

**Comment by aeschli** [comment]
The headers are using the standard red from the light theme
