### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by fsebbah** [Microsoft/vscode#41339]
Since some days, I have this "message of error" : 
"L'hôte d’extension s'est arrêté de manière inattendue."
I tried to desactivate some extensions but it's the same.
The tool of debug give me these informations :

[Extension Host] Found all parseable documents.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Parsing documents and looking for CSS class definitions...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2569 [Extension Host] debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: %cnode::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: 0x390bcd785bbc
 8: 0x390bd03ab202
%c
<--- Last few GCs --->

[1338:0x7fcc91818000]   821474 ms: Mark-sweep 2048.3 (2102.4) -> 2048.3 (2099.4) MB, 4345.9 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 4346 ms) last resort 
[1338:0x7fcc91818000]   825645 ms: Mark-sweep 2048.3 (2099.4) -> 2048.3 (2099.4) MB, 4169.4 / 0.0 ms  last resort 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x26f4a852b959 <JS Object>
    1: createChildren [/Users/Franck1/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib/typescript.js:~94901] [pc=0x390bd03ab202](this=0x19cbec2b1289 <a NodeObject with map 0x38034a359b79>,sourceFile=0x2fde67f02311 <undefined>)
    2: getChildren [/Users/Franck1/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib/typescript.js:~94957] [pc=0x390bd0...

 
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
bracket-pair-colorizer|Coe|0.10.14
vscode-generate-getter-setter|DSK|0.4.2
vsc-material-theme|Equ|1.2.0
beautify|Hoo|1.1.1
material-icon-theme|PKi|3.2.1
ionic2|Tha|3.0.2
html-css-class-completion|Zig|1.15.0
html-snippets|abu|0.2.1
emojisense|bie|0.3.0
angular2-snippets|dan|1.0.16
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
angular-bootstrap|her|4.0.9
ftp-simple|hum|0.5.8
vscode-angular2-emmet|jak|2.0.3
ng-bootstrap-snippets|ktr|0.3.0
Go|luk|0.6.71
tsimporter|pmn|1.2.14
typescript-hero|rbb|1.8.0
html5-boilerplate|sid|1.0.1
bootstrap4-vscode|the|3.0.0
lodash-snippets|tom|1.0.0
bootstrap-3-snippets|wcw|0.1.0
markdown-pdf|yza|0.1.7

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Does this still happen if you disable all extensions and restart VS Code? You can also  start code with the `--disable-extensions` command line flag to check this
