### ISSUE TITLE
Issue with the Sharp symbol #

### ISSUE THREAD

**Issue by etmschneider** [Microsoft/vscode#41332]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (f4ed56b0d61050f6a94cfa033a058fabfdc0d651, 2018-01-09T05:13:28.256Z)</li>
	<li>OS Version: Windows_NT x64 10.0.16299</li>
	<li><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
ocaml|hac|0.6.43
csharpfixformat|Leo|0.0.54
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
vscode-arduino|vsc|0.2.10

</details></li>
</ul>
---
I am using a French (France) keyboard, and in the editor, with the last nightly version, I cannot type in a sharp symbol  (er even here, I need to paste it #). We got it with <ALT GR+3>. Well, not 3 (because 3 is <SHIFT+">... I guess the <ALT GR+3> combination key was set another way... It seems only this combination is impacted, the other <ALT GR+ ...>s seem to work, e.g. <ALT GR+5> gives you the expected [, etc.

Steps to Reproduce:

1. Switch to French keyboard
2. Try to hit <ALT GR+3>, you obtain nothing.

Reproduces without extensions: Yes/No

**Comment by warpdesign** [comment]
duplicate #41196

**Comment by etmschneider** [comment]
Oops, sorry.
