### ISSUE TITLE
Search works only in opened or recently opened files

### ISSUE THREAD

**Issue by tonoslav** [Microsoft/vscode#41336]
![image](https://user-images.githubusercontent.com/3399021/34715444-02ceb68a-f52d-11e7-9091-e8aa38ce1364.png)

## Steps to Reproduce:

1. For example (forms.less) is opened
![image](https://user-images.githubusercontent.com/3399021/34715484-224d1f24-f52d-11e7-93f2-8ad6eea305b9.png)

2. Now I open other .less file (helpers.less)
![image](https://user-images.githubusercontent.com/3399021/34715526-441124c0-f52d-11e7-9ab2-713e0f8ebc16.png)

3. I even noticed it was opened but after I focused there, it works on that file too

## Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/3399021/34715689-bc8d456e-f52d-11e7-993b-ac049ba0a15e.png)

even opened files are 

![image](https://user-images.githubusercontent.com/3399021/34715705-ce044720-f52d-11e7-896c-709236ed28b8.png)

and each contains **cursor** property

## More info

Also CTRL+P doesn't find all files it should

There might be problem with some cache or something like that

**Comment by surajrao** [comment]
Ctrl + P might be present in 1.19.2 as well.

https://stackoverflow.com/questions/48204173/how-can-i-search-my-project-for-files-in-the-vs-code-command-palette

**Comment by roblourens** [comment]
- Are you searching in a directory tracked by OneDrive?
- Are there any errors in the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by tonoslav** [comment]
@roblourens 
1. No
2. No (I think), see image

![image](https://user-images.githubusercontent.com/3399021/34871227-253cb336-f78d-11e7-936c-ccda2e4010e5.png)

**Comment by tonoslav** [comment]
@roblourens thats different project but it doesn't work in both of them, even if I remove pattern
You can see it in screenshots that there is no pattern I  just wanted to show you pane output.

It used to work everywhere, It can't be excluded by any of those because it works when I open them manually from explorer.

Btw i am not 100% sure but I think that it maybe started to work again, but I don't even updated my VS Code and when I now try to search for "cursor" it shows a lot of files with the same rules, nothing changed in my project, weird

**Comment by roblourens** [comment]
> It used to work everywhere, It can't be excluded by any of those because it works when I open them manually from explorer.

Well, open files can be included in search even when they are covered by an exclude setting, due to another issue. 

> Btw i am not 100% sure but I think that it maybe started to work again, but I don't even updated my VS Code and when I now try to search for "cursor" it shows a lot of files with the same rules, nothing changed in my project, weird

I'll leave this open for now, if you notice something else or it stops working for now, we can investigate some more.

**Comment by hoyosjs** [comment]
@roblourens I'm experiencing this problem now. Find used to search recursively in all the files of the open folder, but now I get the same behavior described here.  The matches are limited to the files open in editors. Also, you mentioned something about 'if the folder is being tracked by OneDrive'; can you expand on that?

**Comment by roblourens** [comment]
If your workspace is in Onedrive on Windows, it may not be searched correctly. The issue is here: https://github.com/Microsoft/vscode/issues/35433
