### ISSUE TITLE
Add GitHub markdown emoji support to preview

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#41338]
- VSCode Version: Code - Insiders 1.20.0-insider (f9115349ef09cfef2bed669680d10ac58b490dce, 2017-12-21T16:27:29.385Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
sort-lines|Tyr|1.4.1
vscode-eslint|dba|1.4.3
gitlens|eam|7.2.0
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.1
flow-for-vscode|flo|0.7.3
intellij-idea-keybindings|k--|0.2.18
debugger-for-chrome|msj|4.0.0
annotator|ryu|0.11.0
vscode-fileutils|sle|2.7.1
---

Steps to Reproduce:

1. Create `foo.md` 
2. Type `:smiley:`
3. Open Preview

Expecting: emoji is rendered in preview

Actual: emoji is not rendered in preview

I tried to find an existing issue but I didn't see any?

![image](https://user-images.githubusercontent.com/2301847/34718117-b802ef8e-f4f2-11e7-9978-b79a911e949c.png)

Reproduces without extensions: Yes

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji

**Comment by joshunger** [comment]
Lovely another extension to install thanks @usernamehw
