### ISSUE TITLE
Terminal in VSCode does not show underscore symbols

### ISSUE THREAD

**Issue by teror4uks** [Microsoft/vscode#41331]
- VSCode Version: 1.19.1
                Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
                Date 2017-12-19T09:41:01.414Z
                Shell 1.7.9
                Renderer 58.0.3029.110
                Node 7.9.0
                Architecture x64
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. create file with underscore symbols in name - `touch _test_ ` or `touch t_e_s_t` 
2. Open VSCode terminal
3. Call `ls` or `git status` for display files in directory

Reality Results:
- Files with underscore symbols printing with space instead underscore. 

Expected Results:
 - All symbols printing right

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/35901
