### ISSUE TITLE
File opened in preview stay opened even if closeOnFocusLost=true

### ISSUE THREAD

**Issue by tarzasai** [Microsoft/vscode#41335]
I have `enablePreview=true`, `enablePreview=true` and `closeOnFocusLost=true` (all default values).

- VSCode Version: 1.19.1
- OS Version: Windows 10 64bit build 1703

Steps to Reproduce:

1. on the eplorer bar, double-click to open any file.
2. single-click another file to open it in preview mode.
3. click the tab of the first opened file: the one in preview mode should close but it doesn't.

**Comment by bpasero** [comment]
@tarzasai no, this is not the behaviour of preview files. The idea is that there is always just one file in preview at max but it will not close unless you open another file in preview.
