### ISSUE TITLE
Refactoring library rope/pylint is not installed

### ISSUE THREAD

**Issue by shannonls** [Microsoft/vscode#41334]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.9.1
cpptools|ms-|0.14.5
java|red|0.16.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.install Refactoring library rope is not installed / Pylint;
2.Open the terminal install and create virtualenv environment ;
3.Active the virtualenv environemnt;
4.Choose a symbol and press F2;
4.VSCode will prompt error: **"Refactoring library rope is not installed"**.

I use the python develop envrionment and I have install the tools of Reactoring or Pylint. But when I switch into virtualenv mode the vscode missed the global system installed packages. And it's not perfect to install these tools again into virtualenv again. 

I don't think this is what most users expect...

 

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Not sure if this is an issue with the integrated terminal.

**Comment by shannonls** [comment]
[
![capture11](https://user-images.githubusercontent.com/10648096/34759477-a3af48e8-f5d3-11e7-8962-603620225ad1.PNG)
](url)

In Addition, this happened when statebar show: Python(virtualenv) mode

**Comment by Tyriar** [comment]
I believe this is working as expected because you're launching the virtual environment in one process (the integrated terminal) and you're expecting it to affect the VS Code window's environment.

There are other issues with using Python virtual environments within VS Code but this particular one is working as designed imo. Correct me if I'm wrong.

**Comment by shannonls** [comment]
Yes it's a design issue.  Of course I know it works as logic expected, but I think most users will expect the vscode extensions work in Windows environment because develop tools is not part of project and should not be added into project's virtual environment.

**Comment by Tyriar** [comment]
@shannonls but you're creating the virtual environment within a separate process (your shell) that vscode can't really communicate with. It's also a technical limitation.

**Comment by shannonls** [comment]
@Tyriar Sorry for incomplete description. I just create a virtual environment without activate it in terminal.     
 Vscode finds the venv directory and switch into virtual environment automatically(like fs communication). Of course I can switch vscode running mode (choosing  python environment). The problem is, vscode will miss system-wide python extensions in virtual-env mode.  
From my understanding , the python running environment displayed in bottom status bar should be only used for run/debug user code, vscode itself including its extensions should always use the system-wide/user-wide/some 'global' scope python environment.   

How do you think?

**Comment by Tyriar** [comment]
@shannonls for anything Python specific it should be handled by the Python extension https://github.com/Microsoft/vscode-python. There might be issues related to this over there. They may need new APIs for what you're asking which they can request here, I'm not too familiar with it.
