### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:14950)

### ISSUE THREAD

**Issue by pollingerMaxi** [Microsoft/vscode#41340]
In response to #40767 

- VSCode Version: 1.19.1
- VSCode builtin node Version: 7.9.0
- Node Version: 8.2.1
- OS Version: W10 Pro x64

I get this error:
```
Debugging with inspector protocol because Node.js v8.2.1 was detected.
node --inspect-brk=14950 start.js 
Debugger listening on ws://127.0.0.1:14950/7e0983cf-b876-4c8b-8931-797d4e82de71
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:14950/7e0983cf-b876-4c8b-8931-797d4e82de71
```

This is my launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\compiledServer\\start.js",
            "cwd": "${workspaceRoot}\\compiledServer",
            "sourceMaps": true,
            "outFiles": [],
            "restart": true
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858,
            "outFiles": [],
            "protocol": "inspector"
        }
    ]
}
```

It worked before, never touched it and it just stopped working. It's weird because the app i'm working at works in production but i can't debug it in my dev machine. I can't get it to work launching it via node command nor pm2.

**Comment by pollingerMaxi** [comment]
Updated Node to latest stable (8.9.4) and still same problem.

**Comment by pollingerMaxi** [comment]
I feel really silly now, but i fixed it.

The error was that someone changed the path of the logger folder, which starts at the very beginning of the application and was crashing it.
Fixed the path and started working again.

Error was not that descriptive though. There where no errors in the launch.json, rather they were in the start.ts.

**Comment by auchenberg** [comment]
@pollingerMaxi Glad to hear you got it working. What was the problem in your `start.js`? If you start your node process would it throw an exception that wasn't shown in the VS Code console?

**Comment by pollingerMaxi** [comment]
@auchenberg If i tried to start the application with node, no exception was shown in the console. Just blank space and back to console. So i didn't have any feedback of what was happening.
I just put some console.log like this:
`"use strict";
console.log("before");
Object.defineProperty(exports, "__esModule", { value: true });
var serverApp_1 = require("./serverApp");
var loggerConfig_1 = require("./config/loggerConfig");
var appConfig = require("./config/appConfig");
var pm2 = require('pm2');
loggerConfig_1.initializeLogger();
console.log("after");`

and the "after" was never showed. That's when i started to check on the log configuration, and the path where the logs were saving was made for linux instead of windows.

**Comment by auchenberg** [comment]
Interesting, this is probably caused by your Node process crashing before our debugger is fully attached. Your console.logs should be shown in your console. so you could set `"console": "integratedTerminal"` to use the terminal inside code for this.

**Comment by pollingerMaxi** [comment]
@auchenberg Yes, it was weird, but i imagined that this was happening because it was like really really early after the app launched, so, as you said, probably the debugger wasnt attached yet.
Thanks for the advice, and luckily problem was solved :)
