### ISSUE TITLE
Shows error when deleting from an external storage

### ISSUE THREAD

**Issue by andresitodeguzman** [Microsoft/vscode#41343]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|0.4.1
vscode-color|ans|0.4.5
vscode-eslint|dba|1.4.3
php-debug|fel|1.12.1
php-pack|fel|1.0.1
vscode-prettydiff|Hex|0.6.5
beautify|Hoo|1.1.1
ftp-simple|hum|0.5.8
vscode-github|Kni|0.25.0
team|ms-|1.122.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Connect a memory card or any external storage drive
2. Create a new file on that drive example `sample.js`
3. Try deleting the file (del)

![image](https://user-images.githubusercontent.com/10202948/34724782-17a05408-f58a-11e7-8a66-f9f679763a9b.png)
![image](https://user-images.githubusercontent.com/10202948/34725390-bbf3bb3e-f58b-11e7-8d3e-20aa09ac3515.png)

Since it is on an external storage, moving it to the recycle bin surely is not allowed. The error is shown every time, instead of directly deleting it. 

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/14638
