### ISSUE TITLE
Tab key moves cursor in the GUI not in the edited text/code

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#41342]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (f4ed56b0d61050f6a94cfa033a058fabfdc0d651, 2018-01-09T05:13:28.256Z)</li>
	<li>OS Version: Windows_NT x64 6.2.9200</li>
	<li><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.5.1

</details></li>
</ul>
---

Steps to Reproduce:

1. Open a (new) file, for example 'Test.ps1'
2. Type some text and click the TAB key on the keyboard

A this point I'm expecting to see the cursor jump one tab space further in the text editor. What really happens is that the cursor is moving outside the editor and to the GUI buttons on the left (Explorer, Search, Debug, Extensions, ...).

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@DarkLite1 you might have accidentally enabled accessibility mode, you can get out by invoking this:

![image](https://user-images.githubusercontent.com/900690/34759116-4c7c88ae-f5da-11e7-929d-fe143e8cd382.png)

**Comment by DarkLite1** [comment]
That must have been it, thank you for the help.
