### ISSUE TITLE
the first #include always be reported as a error. 

### ISSUE THREAD

**Issue by Liuchang0812** [Microsoft/vscode#41348]
the first #include always be reported as a error.  "#include errors detected. Please update your includePath". 

- VSCode Version:  Version 1.19.1 Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
- OS Version: ubuntu 17.10

Steps to Reproduce:

1. open any cpp file
2. swap two include lines

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
