### ISSUE TITLE
Column select copy & paste

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4134]
- VSCode Version:  0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Select a region using column select (multiple lines)
2. Copy
3. open another editor (e.g. notepad)
4. Paste

Observe: you paste a single line. I would expect to paste as many lines as I have selected in the source

**Comment by alexandrudima** [comment]
@dbaeumer Was the file you were copying from using LF or CRLF?

**Comment by alexandrudima** [comment]
I use the line ending of the source file and perhaps Notepad is not understanding `\n`. i.e. when I paste in VSCode it works as expected.

**Comment by dbaeumer** [comment]
Good point. The file had \n line ending. Feel free to close
