### ISSUE TITLE
Hint of objects properties

### ISSUE THREAD

**Issue by k-egor-smirnov** [Microsoft/vscode#41346]
- VSCode Version: 1.19.1
- OS Version: Windows 10

Steps to Reproduce:

1. Write something method that contains jsdoc with object and their options
2. Try to write property of object in that method

I write method call and expect hint of propery described in JSDoc

Code:
![image](https://user-images.githubusercontent.com/17943083/34727432-b5201d2e-f578-11e7-9b97-268b3670b7c7.png)

Method:
![image](https://user-images.githubusercontent.com/17943083/34727528-06e2443e-f579-11e7-8aef-3b188c096247.png)

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
@k-egor-smirnov Where are you expecting the intellisense? For the property name or for the value?

**Comment by k-egor-smirnov** [comment]
Intellisense is working with name but I expect also hint for value

вт, 9 янв. 2018 г., 23:54 Matt Bierner <notifications@github.com>:

**Comment by mjbvz** [comment]
@k-egor-smirnov I don't understand what you mean. Please provide a self-contained code example with repo steps and a short description of the expected behavior.
