### ISSUE TITLE
An Angular project created in Ng CLI cannot be edited in VS Code

### ISSUE THREAD

**Issue by philr-vistatec** [Microsoft/vscode#41352]
- VSCode Version: 1.19.0
- OS Version: Windows 10
- Angular CLI: 1.6.1
- Node: 8.9.4

Steps to Reproduce:

1. Create folder `codeprj` in Windows Explorer
2. Create new Angular project with CLI `ng new angprj` in different folder
3. Right click `codeprj` and choose `Open with Code`
4. In Code add a new app.component.ts file - content doesn't matter
5. Close Code
6. From `angprj` project copy `app.component.html` into `codeprj`
7. Reopen `codeprj` in Code. Can edit the .ts file but the .html gives:
    
<pre>
Unable to open 'app.component.html': A system error occurred (EPERM: operation not permitted, stat 'e:\Dev\angprj\app.component.html').
</pre>

In Windows explorer, file permissions are identical.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
> From angprj project copy app.component.html into codeprj

How do you do that?

**Comment by philr-vistatec** [comment]
Windows Explorer or [Total Commander](https://www.ghisler.com/).

If you cannot repo it might be best to close the issue. After rebooting my machine I now cannot edit any files.

I've had this issue a while and have so far ruled out anti-virus and administrator permissions. Having real trouble isolating conditions that are consistently reproducible.
