### ISSUE TITLE
ThrottledEmitter kinda duplicates debounceEvent

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#41355]
See https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/async.ts#L670 and https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/event.ts#L280. Both make sure a rapid firing event is being held back for a bit

**Comment by bpasero** [comment]
I think I looked at `debounceEvent` and there was some behaviour that I did not want.

**Comment by jrieken** [comment]
>  there was some behaviour that I did not want

which?

**Comment by bpasero** [comment]
@jrieken the `ThrottledEmitter` provides methods to conditionally `throttle` and `resume` while `debounceEvent` is always debouncing. For my use case I want to throttle events while editors are restoring on startup. I could not find this functionality in `debounceEvent`.

**Comment by jrieken** [comment]
Hm, then maybe `EventBufferer` is what you want. @joaomoreno will know more about all the utils he added too

**Comment by joaomoreno** [comment]
`EventBufferer` will conditionally hold off on firing the events. Doesn't seem to help @bpasero

**Comment by bpasero** [comment]
Yeah the `EventBufferer` seems to come a bit closer though it seems to release all `Events` that happened while a function was executed, not just the last.

**Comment by joaomoreno** [comment]
Oh, I see... so it can help. You need to add an optional reducer to `bufferEvents`. You also need to make `fn` be async since your condition seems to be async.

**Comment by bpasero** [comment]
Not used anymore.
