### ISSUE TITLE
[feature request] Add "set syntax" option for unsaved files

### ISSUE THREAD

**Issue by guyzyl** [Microsoft/vscode#41359]
Hi, 
It would be nice if there could be a quick action that allows you to set the syntax of a new created file which was not yet saved. 
That way a user can get the features of a specific language (code completion, syntax highlighting, etc), without having to save the file. 
This is good for cases when writing or copying snippets of code, where you still want the complete set of features VSCode can provide, but you do not want or need to save the file. 
The feature should work similarly to the "set syntax" option in Sublime Text.
Thanks!

**Comment by usernamehw** [comment]
There is already an action: `Change Language Mode`
