### ISSUE TITLE
Support updating debugAdapter provided sourceReference documents

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#41362]
- VSCode Version: 1.20.0-insider
Commit 8697a5e4ec152832a2612929c87d56302dbb2e79
- OS Version: Windows 10

I would like to be able to use the sourceReference feature of the debug protocol to return source files to VS Code. But I have ran into one issue - I can't seem to get VS Code to re-query for new content if my virtual document changes.

The debug protocol appears to support this by issuing a "loadedSource" event with a reason of "changed". But when I tied to do this it didn't work. Here is the event I sent:

```
<- (E) {"event":"loadedSource","body":{"reason":"changed","source":{"path":"Source file extracted from PDB File. Original Path: C:\\proj\\DebuggeeTest\\EmbeddedSourceTest\\SmallFile.cs","name":"SmallFile.cs","sourceReference":1,"sources":[],"checksums":[{"algorithm":"SHA1","checksum":"47755c1e39034a3ca708d4659bc36eea3e3880d4"}]}},"seq":44,"type":"event"}
```

I couldn't find any code in VS Code to actually consume the "loadedSource" event, so I am assuming this method will not currently work.

Is there anything else I can do, or do I need a new VS Code feature for this?

**Comment by isidorn** [comment]
@gregg-miskelly you are correct this is currently not implemented in VSCode.
We accept PRs that fix this. I would do this in such a way that the `Process` adds a listener on the `Session` and updates it `sources` map. [Code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L540)

@weinand fyi

**Comment by remss** [comment]
I seems that the "removed" reason for "loadedSource" event is not implemented yet too (vscode 1.27). Can you confirm ?

**Comment by weinand** [comment]
„removed“ is implented in current Insiders (1.28 )

**Comment by remss** [comment]
@weinand Great news!

Until now I believed that the protocol defines only features implemented in the last VScode but if this is not the case how can we know if a feature is available is VSCode?

**Comment by weinand** [comment]
The debug adapter protocol is independent from VS Code and contains quite a few features that are not implemented in VS Code but exist in VS or VS for Mac.

In the release notes we always try to clearly state whether a new DAP feature is implemented in VS Code or not.

**Comment by remss** [comment]
I understand but it is difficult to review all release notes to find if a feature of the DAP is implemented or not. 
For now the only way I see is to test the feature and see if it does something. But when it doesn't I'm not sure if the feature is not implemented or if I misuse the DAP.
Maybe some labels like "VSCode-only" or "VS-only" in the DAP documentation could help developers what is available for the IDE they target ?

**Comment by weinand** [comment]
Please file a feature request at https://github.com/Microsoft/debug-adapter-protocol/issues

**Comment by remss** [comment]
https://github.com/Microsoft/debug-adapter-protocol/issues/7

**Comment by weinand** [comment]
The loaded scripts view now supports "related resources" per script.
But a "loadedSource" event with reason "changed" is not yet supported.

Moved to November.

**Comment by weinand** [comment]
The event sent is:
```ts
{
	"event": "loadedSource",
	"body": {
		"reason": "changed",
		"source": {
			"path": "Source file extracted from PDB File. Original Path: C:\\proj\\DebuggeeTest\\EmbeddedSourceTest\\SmallFile.cs",
			"name": "SmallFile.cs",
			"sourceReference": 1,
			"sources": [
			],
			"checksums": [
				{
					"algorithm": "SHA1",
					"checksum": "47755c1e39034a3ca708d4659bc36eea3e3880d4"
				}
			]
		}
	},
	"seq": 44,
	"type": "event"
}
```

**Comment by weinand** [comment]
A "changed" event now properly triggers an updates of the "script" node in the LoadedScripts view.

Please note that a "changed" event does not trigger a refetch of the document content.

**Comment by weinand** [comment]
@gregg-miskelly I've added the feature that a "changed" event now triggers a reload of the source content.

**Comment by gregg-miskelly** [comment]
Thanks!
