### ISSUE TITLE
Opens links in Chrome regardless of default browser settings

### ISSUE THREAD

**Issue by kirkholloway** [Microsoft/vscode#41369]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: none
---

Steps to Reproduce:

1. Set default browser to something other than Chrome
2. Command + Click a link or click "Submit bug" button
  
@zeke

**Comment by kirkholloway** [comment]
Also, at times the tab opened in Chrome doesn't actually show the page, and instead just shows the new tab page.

**Comment by MarshallOfSound** [comment]
> Chrome doesn't actually show the page, and instead just shows the new tab page.

This is a bug in Chrome, basically you have a new update for Chrome staged (ready to relaunch and update) and when Chrome is "launched" it launches the new version of Chrome instead of the old one.  If you relaunch Chrome this will stop happening, I believe this is on the Chrome teams radar.

**Comment by zeke** [comment]
@MarshallOfSound how many repos do you watch!?

**Comment by bpasero** [comment]
@zeke maybe he just watches you ;)

**Comment by kirkholloway** [comment]
I can't replicate this anymore. I think there must've been something screwy with my system settings. Happy to close.
