### ISSUE TITLE
Quick double click can open the same viewlet context menu multiple times

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#41363]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (f4ed56b0d61050f6a94cfa033a058fabfdc0d651, 2018-01-09T06:08:10.994Z)</li>
	<li>OS Version: Darwin x64 17.3.0</li>
	<li><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
color-info|bie|0.5.0
emojisense|bie|0.3.0
lit-html|bie|0.2.0
markdown-checkbox|bie|0.0.5
markdown-emoji|bie|0.0.7
markdown-mermaid|bie|0.1.1
test-ext|bie|0.0.2
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.22
vscode-reveal|evi|1.0.0
mdmath|goe|2.1.0
rest-client|hum|0.16.2
vscode-styled-components|jpo|0.0.10
graphql-for-vscode|kum|1.7.0
mssql|ms-|1.3.0
python|ms-|0.9.1
azure-account|ms-|0.2.2
csharp|ms-|1.13.1
github-issues-prs|ms-|0.9.0
vsliveshare|ms-|0.1.0-preview.164
debugger-for-chrome|msj|4.0.0
angular2-inline|nat|0.0.17
vscode-code-outline|pat|0.0.12

(17 theme extensions excluded)

</details></li>
</ul>
---

Steps to Reproduce:

1. Extensions viewlet
2. Quickly double click the `More` button
3. Select `Install from vsix`
4. 💥 File explorer opens, as does another instance of the context menu

Reproduces without extensions: Yes

![jan-09-2018 11-11-43](https://user-images.githubusercontent.com/12821956/34738570-40e20ce6-f52e-11e7-8227-ac214f75954b.gif)

Note: I'm double clicking here using a quick double tap on the mac trackpad. This looks like the same issue as #36244

**Comment by gushuro** [comment]
Quick double click seems fixed, but quickly clicking 4+ times on the `More` button still show this issue.
