### ISSUE TITLE
revert file when doing Git clean

### ISSUE THREAD

**Issue by zivni** [Microsoft/vscode#4137]
- VSCode Version: 0.10.10
- OS Version: windows 8.1

Steps to Reproduce:

1. init git in project
2. edit a file save, and commit
3. edit the file and do not save
4. Go to Git view
5. on the file chose clean (git clean)

The editor should also preform a revert file action. there is no reason to keep the changes in memory but reverting on disk.

 As a side effect, when trying to save gives an error that the file on disk is newer and cannot save.

**Comment by joaomoreno** [comment]
This might cause some data loss, I prefer we keep it the way it is and make it an explicit user action to get rid of the dirty state that he caused in the buffer.
