### ISSUE TITLE
Explorer: restore focus to last view that had focus

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41377]
Somehow we lost the support in the explorer to restore the focus to the view that last had focus. I remember I added code once to restore focus to either "Open Editors" or "Files Explorer" when clicking on the Explorer viewlet to open it again depending on where focus was last.

Worse, today when the "Files Explorer" is collapsed, the focus does not go to anything within the explorer:

![image](https://user-images.githubusercontent.com/900690/34757837-1bbd8dea-f5d4-11e7-847a-bea217011d0c.png)

Not sure if this is related but I am seeing a similar issue with the SCM viewlet: When focus is in the changes view input box and I click to another viewlet and back, the focus is not restored there, even though it looks like [`PanelViewlet`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/panelViewlet.ts#L135) has a concept of `lastFocusedPanel`

**Comment by isidorn** [comment]
I believe this behavior should be built into the split view and shared across vscode. Righting explorer specific code does not make much sense to me
Thus assigning to @sandy081 and @joaomoreno

**Comment by sandy081** [comment]
I will take a look

**Comment by bpasero** [comment]
@sandy081 seems to work fine for explorer now, but should this also work in other views like Debug and SCM?

**Comment by sandy081** [comment]
Debug and SCM viewlets override to have specific focus behaviour. @isidorn @joaomoreno FYI
