### ISSUE TITLE
Weird colors in terminal

### ISSUE THREAD

**Issue by richtone** [Microsoft/vscode#41371]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 `10.0.16299`
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
jshintrc-generator|ben|1.0.0
jshint|dba|0.10.15
node-module-intellisense|lei|1.5.0
JavaScriptSnippets|xab|1.5.0

---

![2018-01-09 23_01_40-app js - pensieve - visual studio code](https://user-images.githubusercontent.com/6845025/34746801-b97a977e-f595-11e7-80a4-323b3419d41d.png)

Steps to Reproduce:

1. Open terminal
2. See the colors

Reproduces without extensions: Yes

**Comment by DanielPintilei** [comment]
I guess the same thing happens in my case
![white_terminal](https://user-images.githubusercontent.com/9828983/34865568-e80e2978-f781-11e7-87ce-3ff26c3c343c.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/40327
