### ISSUE TITLE
Insert mode in VSVim swallows CMD + arrow keys sometimes

### ISSUE THREAD

**Issue by kdheepak** [Microsoft/vscode#41373]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (f4ed56b0d61050f6a94cfa033a058fabfdc0d651, 2018-01-09T06:08:10.994Z)</li>
	<li>OS Version: Darwin x64 16.7.0</li>
	<li><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
quick-open-file|Ala|0.1.2
bracket-pair-colorizer|Coe|0.10.14
vsc-material-theme|Equ|1.2.0
matlab|Gim|0.8.0
output-colorizer|IBM|0.1.2
code-settings-sync|Sha|2.8.7
omnipascal|Wos|0.15.0
Bookmarks|ale|0.18.0
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
vscode-new-file|dku|4.0.1
githistory|don|0.2.3
tslint|eg2|1.0.24
code-runner|for|0.8.7
Python-autopep8|him|1.0.2
vue-snippets|hol|0.1.5
path-autocomplete|ion|1.8.0
language-julia|jul|0.9.1
cmake-tools-helper|mad|0.1.1
vscode-clang|mit|0.2.2
python|ms-|0.9.1
cpptools|ms-|0.14.5
debugger-for-chrome|msj|4.0.0
gitlink|qez|0.4.2
subtle-brackets|raf|2.1.0
typescript-hero|rbb|1.8.0
vscode-icons|rob|7.19.0
gi|rub|0.2.11
vscode-table-formatter|shu|1.2.1
vscode-multiclip|sle|0.1.3
guides|spy|0.9.1
cmake|twx|0.0.17
vim|vsc|0.10.8
vscode-todo-highlight|way|0.5.11

(4 theme extensions excluded)

</details></li>
</ul>

---

Steps to Reproduce:

I'm unable to reproduce this consistently at the moment, but I have experienced this multiple times.
I have to toggle vim mode off and on and then I'm able to use CMD + right arrow to go to the end of the line.

**Comment by bpasero** [comment]
@kdheepak maybe report this to the VIM extension

@rebornix not sure if this is an editor issue or not, leaving up to you to decide.

**Comment by rebornix** [comment]
Hi @kdheepak IMHO it's an issue with the Vim extension you are using, please file issues there first.
