### ISSUE TITLE
[badge request] Node Security (nodesecurity.io)

### ISSUE THREAD

**Issue by ivangabriele** [Microsoft/vscode#41375]
Hi,

I think the the name is pretty self-explanatory. Their badge is a check for (some) vulnerabilities.

Could you please allow Node Security badges in the [approved badges list](https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_approved-badges) ?

Url : https://nodesecurity.io

**Comment by joaomoreno** [comment]
Fixed in https://github.com/Microsoft/vscode-vsce/commit/3992398656d20cf794ca24c0442953e4eb9ea799

Docs fixed in https://github.com/Microsoft/vscode-docs/commit/9f71c38181b99968331c8375438e9c7308d24bd4
