### ISSUE TITLE
no copy path action for remote resources

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#41374]
* Open a remote resource or have one in the explorer
* there is no more 'copy path' command

**Comment by bpasero** [comment]
I also fixed this for the editor tab title context menu where "Copy Path" and "Reveal in Explorer" show up.

**Comment by sandy081** [comment]
@isidorn Is there a sample extension for remote file system provider to verify this?

**Comment by isidorn** [comment]
@sandy081 https://github.com/jrieken/ftp-sample
