### ISSUE TITLE
outdent when multiple selections are active

### ISSUE THREAD

**Issue by rgl** [Microsoft/vscode#41383]
When there are multiple selections (multiple cursors) we can indent by pressing `tab`, it would be really nice if we could press `shift+tab` to outdent.

**Comment by alexandrudima** [comment]
@rgl this works fine for me:

![kapture 2018-02-05 at 14 20 40](https://user-images.githubusercontent.com/5047891/35806432-c5bb1d02-0a7f-11e8-95db-87abb51cd6f0.gif)
