### ISSUE TITLE
enlarge margin of "Discard All changes" and "Stage All changes" to avoid dangerous operation

### ISSUE THREAD

**Issue by suixudongi8** [Microsoft/vscode#41382]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
xml|Dot|1.9.2
gitlens|eam|7.2.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
python|ms-|0.9.1
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|4.0.0
java|red|0.16.0
vscode-adaptivecards|tom|1.0.7
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
vscode-react-native|vsm|0.5.7

---

Steps to Reproduce:

1.
![sketch](https://user-images.githubusercontent.com/10978000/34763921-c1e24ae6-f627-11e7-8431-104fb3182ca9.png)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
The dangerous operation is already avoided by always having an alert popup which confirms the operation.

**Comment by suixudongi8** [comment]
Thanks!
