### ISSUE TITLE
VSCode didn't shutdown completely, and cost 40% cpu

### ISSUE THREAD

**Issue by Rhuaer** [Microsoft/vscode#41384]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
vscode-markdownlint|Dav|0.12.1
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
gitlens|eam|7.2.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
auto-rename-tag|for|0.0.15
vscode-yarn|gam|1.3.0
beautify|Hoo|1.1.1
code-beautifier|mic|1.7.2
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
python|ms-|0.9.1
azure-account|ms-|0.2.2
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.0.0
color-highlight|nau|2.3.0
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7
stylelint|shi|0.31.0
jsx|Twe|0.0.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. This issue occurs randomly, and disappears later
1. Open 3-4 vscode, and start node server with terminal,
1. Close all vscode,
1. Finally there is one vscode as background process in the task manager, and vscode cost 40% cpu

Reproduces without extensions: No

**Comment by Tyriar** [comment]
@Rhuaer when this happens again can you check the "command line" of the bad processes? You can view this in task manager by right clicking on the columns and checking command line.

**Comment by Rhuaer** [comment]
![vscoderemain](https://user-images.githubusercontent.com/13702561/34932470-d69114a6-fa0d-11e7-8eb0-6b0d80d55341.gif)

@Tyriar Here is the bug's gif. I started node server by terminal 2 days ago,  I closed two Vscode today afternoon, but they didn't shutdown.

**Comment by Tyriar** [comment]
Looks like the problem processes are the extension host, not a terminal/node server?

**Comment by alexandrudima** [comment]
@Rhuaer From the gif, it looks like there are two extension host processes hanging at full CPU (1 core). This indicates that there is an extension running that is entering some form of endless loop.

You have installed very many extensions, so it is difficult to try to guess which one it is. Here are steps to find out which extension it is:
https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions
