### ISSUE TITLE
Impossible to keep indentation on empty lines when formatting

### ISSUE THREAD

**Issue by ericmc2** [Microsoft/vscode#41394]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Whenever VSCode formats my code, the indentation on empty lines between code gets removed. As I undestand it, I should be able to disable this behavior with "editor.trimAutoWhitespace": false or "files.trimTrailingWhitespace": false. Unfortunately, these settings do not seem to have any effect on it.

So far I've noticed this when writing JavaScript and HTML. Other languages, for which I don't have any formatters installed, are not affected.

Steps to Reproduce:

1. Set "editor.trimAutoWhitespace" and "files.trimTrailingWhitespace" to false
2. Write a JavaScript function with empty lines between code
3. Format the document

**Comment by aeschli** [comment]
Formatters don't use "editor.trimAutoWhitespace" and "files.trimTrailingWhitespace", they have their own settings, e.g. `html.format.`.
In the case of HTML, we use JSBeautify as the underying formatter, which doesn't support the feature your request. To add this, this needs to be filed as a feature request against https://github.com/beautify-web/js-beautify

**Comment by ericmc2** [comment]
Ah, I see. Thank you! I'll file a feature request for JSBeautify. I was confused because the global setting didn't work, even though there was no language specific setting overriding it.
