### ISSUE TITLE
vscode-standardjs not showed on search result

### ISSUE THREAD

**Issue by jasonxia23** [Microsoft/vscode#41397]
- VSCode Version: 1.18.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Just search **vscode-standardjs** on marketplace in VSCode;
2. **vscode-standardjs-snippets** other than **vscode-standardjs** showed in the result.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
This is the missing extension: https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs

It uses "vscode-standardjs" in the readme, but isn't returned when searching for 

- "vscode-standardjs" https://marketplace.visualstudio.com/search?term=vscode-standardjs&target=VSCode&category=All%20categories&sortBy=Relevance
-  "standardjs" https://marketplace.visualstudio.com/search?term=standardjs&target=VSCode&category=All%20categories&sortBy=Relevance

Who is responsible for marketplace issues now? @auchenberg @chrisdias?

**Comment by auchenberg** [comment]
Closing as the indexing problem have been resolved by the marketplace team.
