### ISSUE TITLE
Incorrect highlighter for HTML comments - add and even number of slashes   

### ISSUE THREAD

**Issue by vdizdarevic** [Microsoft/vscode#41399]
Example that simple shows highlighter problem:

### <div>
        <div>
        
        <div>
        </div>
        

          
        <div>
        </div>
        

        

        </div>
</div>

Add number of slashes in closing part makes highlighter problem.

**Comment by aeschli** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/33944
