### ISSUE TITLE
Terminal: <ctrl+any character> should be sent to the terminal

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#41398]
- VSCode Version: 1.19.1
- OS Version: Windows x64

Steps to Reproduce:

1. Open the integrated terminal
2. Open `bash` to switch to Linux on Windows
3. Type `nano`
4. Type `ctrl + o` to save the file

What happens?

This opens the VSCode quick open instead of sending `ctrl+o` to the terminal.

Some combinations, like `ctrl+x` will properly send the signal to the terminal, but most won't and will get propagated to VSCode instead.

Does this issue occur when all extensions are disabled?: Yes

**Note** it works as expected with `CMD.exe`.

**Comment by Tyriar** [comment]
This is all driven by the `terminal.integrated.commandsToSkipShell` setting which can be modified by users. It's kind of a crappy system and there's an open issue pondering improvements https://github.com/Microsoft/vscode/issues/19770
