### ISSUE TITLE
Wiki Documentation Issue

### ISSUE THREAD

**Issue by rashwell** [Microsoft/vscode#414]
There are really two issues.  
1) https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source
    The link at the bottom of the above page doesn't allow the wiki to be forked.
2) The instructions for the window build.  On a clean install git and node, etc.  Before the "gulp watch" incremental build will work you will also need to :+1: 
      npm install dateformat -g
      npm install inherits -g
      npm install isarray -g
      npm install inflight -g
      npm install once -g

And then the gulp watch's dependencies will be met.  I would have just submitted a documentation update, but that is when I ran into bullet 1) above, I am probably missing something simple, but I don't see a wiki folder in the main vscode project, or the vscode-doc project either, so I don't know how to contribute the hint.

**Comment by chrisdias** [comment]
Fixed link in _Footer.md, testing out build...

**Comment by chrisdias** [comment]
I cannot repro this problem. Did you run `scripts\npm install` prior to running `gulp watch`? That should install all necessary dependencies.
