### ISSUE TITLE
Missing colors in some git-rebase-todo tokens

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4140]
Related to #4006

`x`, `exec`, `d`, `drop`.

![image](https://cloud.githubusercontent.com/assets/22350/13746153/33745ca6-e9f2-11e5-9047-10795a52071e.png)

**Comment by bpasero** [comment]
@Tyriar since you are on the themes already

**Comment by bpasero** [comment]
@joaomoreno pushed some colors, please verify for Dark and Light theme. I did not add explicit color for the message, only for the verb and git sha.

**Comment by Tyriar** [comment]
Looks good :+1:

**Comment by joaomoreno** [comment]
`x`, `exec`, `d`, `drop` are still not colored.

![image](https://cloud.githubusercontent.com/assets/22350/13881200/c69c81e8-ed17-11e5-9d51-37b3f727cb33.png)
