### ISSUE TITLE
"typescript.reportStyleChecksAsWarnings" defaults to true?

### ISSUE THREAD

**Issue by zelein** [Microsoft/vscode#41409]
I started noticing that vscode began reporting unused variables/imports as warnings instead of errors.

My tsconfig uses `noUnusedLocals: true`, so (for example) all unused imports shall cause a compiler error.
I have a vscode watch task that compiles typescript and uses my tsconfig to pull its settings.

Due to the latest release adding this new rule and defaulting it to true - these errors are now defaulting to warnings in vscode. This causes a disconnect from what is actually an error, but is now being reported as a warning.

I was not aware of this new setting and until I did some digging, had no idea why this was occurring.

Why was this new setting added and defaulted to true when it causes a disconnect between the compiler watch task? This seems like an opt-in setting as it changes the default behavior of how the compiler should behave in vscode.

**Comment by mjbvz** [comment]
Please see the discussion around this change here: https://github.com/Microsoft/vscode/pull/37616
