### ISSUE TITLE
VS Code doesn't correctly display Russian letters

### ISSUE THREAD

**Issue by JohnyL** [Microsoft/vscode#41401]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: omnisharp 1.13.1

VS Code doesn't correctly display Russian letters:

![VS_Code_Russian_letters_dont_display](https://i.imgur.com/vZwwCIC.png)

**Comment by aeschli** [comment]
@JohnyL Please make sure that the file is loaded with the correct encoding. 
Also, can you add a link to the file?

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by JohnyL** [comment]
I wonder why it's closed. The problem is *not* with the source code file encoding but with `Debug Console` - the output is from there.
