### ISSUE TITLE
Text selection with double/triple-clicks doesn't work with urls inside a terminal

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#41415]
Run this in the terminal: `echo "test http://google.com"`.

I'm used to the double-click-to-select-word thing, but it doesn't work if I'm doing it over a url. For instance I can select "test" this way, but not "google".

Also, I can't select a whole line with a triple-click if those clicks happen over a url, I can otherwise.

**Comment by Tyriar** [comment]
This is happening because `MouseZoneManager` calls `preventDefault` on the event when a zone is hit. See:

https://github.com/xtermjs/xterm.js/blob/62d6c242fce8cc4bc983821d914348392833ee83/src/input/MouseZoneManager.ts#L153-L158

**Comment by Tyriar** [comment]
Caused by https://github.com/xtermjs/xterm.js/commit/95f68a41d7e625155561edfa0e19f7d9fe65d71b#diff-4e435601801169766b8d5c882bfa9683

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1021, PR: https://github.com/xtermjs/xterm.js/pull/1264

**Comment by octref** [comment]
@Tyriar Still doesn't seem to be fixed for me though. I'm on 519088548b09221e9d590d2e10e14ec6d27ac79a with macOS 1.13.2.

**Comment by Tyriar** [comment]
@octref you're right, it's seems to be only fixed for local links (eg. `echo './README.md'`)

**Comment by Tyriar** [comment]
It's a little close to release, I'll fix this for URLs in the following iteration as it needs a new drop of xterm.
