### ISSUE TITLE
Keyboard Input not working when mouse cursor is hovered over the application's window

### ISSUE THREAD

**Issue by joshuamaxwell** [Microsoft/vscode#41411]
- VSCode Version: 1.17.1
- OS Version: CentOS7.3.1611

Steps to Reproduce:

1. Manually install an extension from a VSIX.
2. Use the prompt to 'reload' the editor
3. Typing is no longer possible unless I move the mouse outside of the application window. I can repeatedly tap on the 'a' key and hover my mouse off the vscode window and 'a' start apearing next to the cursor as expected then hover my mouse back over the vscode window and 'a' no longer appears

Does this issue occur when all extensions are disabled?: Yes

**Comment by joshuamaxwell** [comment]
I can also replicate this by opening the text editor to have full normal functionality, click on the desktop outside of the application window (thus causing the window to lose focus) then click back inside the application and I no longer get any keyboard input registered unless I move the mouse cursor to hover outside of the application window.

**Comment by bpasero** [comment]
@joshuamaxwell where exactly do you click into the window and cannot type as a result?

**Comment by joshuamaxwell** [comment]
Anywhere in the window, as far as I know. I was just clicking inside the window so that the application regains focus. Perhaps I could try selecting the vscode application from the task bar then hover over the window?

I've also watched the console in developer tools and I see nothing out of the ordinary.

Once the application gets into this state where it is not receiving keyboard input while the mouse cursor is over the application window, the only way to get it functioning again is to go to the file menu and close the vs code application and then reopen it again.

**Comment by bpasero** [comment]
@joshuamaxwell in that state is the entire window frozen and not even mouse interaction works, could that be?

**Comment by joshuamaxwell** [comment]
Oh no, everything works quite normally EXCEPT vscode doesn't register keyboard input when the mouse cursor is hovering over the application. Meaning I can use ctrl+p for example only when i push the cursor off from hovering over the application. So i shove the mouse away and type away, then i grab the mouse and click away in the menus and editor tabs then shove it back away and start typing again. That is what i COULD do if I needed to use vscode.

it sounds sort of similar to [#37775](https://github.com/Microsoft/vscode/issues/37775)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by joshuamaxwell** [comment]
Unfortunately, not immediately since this environment is not connected to internet and corporate security posture involves review boards to get new software. So I'll get any new versions reasonably soon but I won't be able to "give this version a try".

If this isn't a common problem for others then I guess it could be far more specific to my own environment and set up. I have seen other issues reporting problems with the keyboard input so just trying to narrow down on the common denominator if there is one

**Comment by eme42** [comment]
I am seeing the same issue.

**Comment by bpasero** [comment]
Does this still happen?
