### ISSUE TITLE
CLI to open file on specified char doesn't work (file:line[:character])

### ISSUE THREAD

**Issue by PLyczkowski** [Microsoft/vscode#41410]
- VSCode Version: 1.19.1
- OS Version: Windows 10 64 Version	10.0.16299 Build 16299

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/7307968/34784896-ded17138-f62f-11e7-8551-c0800116f05a.png)

**Comment by PLyczkowski** [comment]
Addendum:
This works >
![image](https://user-images.githubusercontent.com/7307968/34785137-8a91cf4a-f630-11e7-932e-f431078a7cd4.png)
So the documentation seems to be wrong then? No need for square brackets.

**Comment by bpasero** [comment]
@PLyczkowski the square brackets are to describe that the line or column is optional.

**Comment by PLyczkowski** [comment]
Ah, I see, thanks.
