### ISSUE TITLE
Release notes notification show even if vscode downgrades to an older version

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4141]
related to #4023

Steps to Reproduce:

1. Open local storage and modify key `storage://global/releasenotes/lastversion` to `1.0.0`
2. Reload code - notice how we show the release notes popup
3. I would not show the release notes in a scenario where we downgrade a VSCode version - as the user has probably already seen those release notes in the past

**Comment by joaomoreno** [comment]
This doesn't happen often, I doubt that it will be an issue.
