### ISSUE TITLE
[folding] Search doesn't un-collapse section if also switching files

### ISSUE THREAD

**Issue by andy-ms** [microsoft/vscode#41419]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (2bab83a097135cf8c2a1ca1498bb8906f06d2cb3, 2018-01-10T06:16:46.780Z)</li>
	<li>OS Version: Linux x64 4.4.0-21-generic</li>
	<li>Extensions: none</li>
</ul>
---

Steps to Reproduce:

1. Create `a.ts` and write:
```ts
function f() {
    searchtext;
}
```
2. Collapse the function.
3. Create `b.ts` (without closing `a.ts`).
4. Ctrl-shift-f, type `searchtext`, and hit enter. You should see a result in `a.ts`.
5. Click on the result and you are navigated to `a.ts` -- but you can't see `searchtext` anywhere since `f` is still collapsed.
6. It *will* uncollapse if you click on `searchtext` a second time while still looking at `a.ts`.

**Comment by andy-ms** [comment]
This problem also affects go-to-definition:
**a.ts**
```ts
namespace N {
    export function f() {}
}
```

**b.ts**
```ts
N.f();
```

Collapts `a.ts` and go-to-definition on `f` in `b.ts` -- I would expect it to expand sections as necessary to get me to the definition, but instead I'm just left at the top of the file.

**Comment by ewerybody** [comment]
Is this hard to fix?! It's pretty annoying. I collapse a lot :/
