### ISSUE TITLE
Text Search: add an ability to search a variable by his name and type

### ISSUE THREAD

**Issue by elad335** [Microsoft/vscode#41412]
This is an apparent issue when developing a big project, sometimes different veraibles have the same name what makes it hard to search for them in the code.
of course this can be added for functions as well.

thx in advance, elad;)

**Comment by roblourens** [comment]
The closest I can suggest is the command "Go to symbol in workspace" which will let you filter for symbols and show whether it's a property, class, etc. We don't have any way to also search for type here, and I don't know of any plan to implement this in the near future.
