### ISSUE TITLE
--user-data-dir incorrect help

### ISSUE THREAD

**Issue by izznogooood** [Microsoft/vscode#41429]
- VSCode Version: 1.19.2
- OS Version: Arch

Steps to Reproduce:

1. sudo code --user-data-dir /some/dir

Workaround:

"sudo code --user-data-dir=/some/dir"

Comment:

Djesus crist people, fix the --help list allready!

https://github.com/Microsoft/vscode/issues/7243

**Comment by bpasero** [comment]
@izznogooood I cannot reproduce, for me `sudo code --user-data-dir=/some/dir` works. What happens in your case?

**Comment by izznogooood** [comment]
Yes that would work. your --help does not inform you to use "--user-data-dir=/some/dir", but "--user-data-dir /some/dir". Your --help is missing a critical piece of information.

https://github.com/Microsoft/vscode/pull/41430

**Comment by bpasero** [comment]
@izznogooood sorry, I confused myself. I meant to say that for me it works without the "=". What happens in your case without the "="? And does it only NOT work with sudo or never?

**Comment by izznogooood** [comment]
Oh I see, well not here ...
 
'''
[anders@idea ~]$ code --help
Visual Studio Code 1.19.2

Usage: code [options] [paths...]

To read from stdin, append '-' (e.g. 'ps aux | grep code | code -')

Options:
  -d, --diff <file> <file>                                       Compare two files with each other.
  -a, --add <dir>                                                Add folder(s) to the last active window.
  -g, --goto <file:line[:character]>                             Open a file at the path on the specified line and character
                                                                 position.
  --locale <locale>                                              The locale to use (e.g. en-US or zh-TW).
  -n, --new-window                                               Force a new instance of Code.
  -p, --performance                                              Start with the 'Developer: Startup Performance' command enabled.
  --prof-startup                                                 Run CPU profiler during startup
  --inspect-extensions                                           Allow debugging and profiling of extensions. Check the developer
                                                                 tools for the connection uri.
  --inspect-brk-extensions                                       Allow debugging and profiling of extensions with the extension
                                                                 host being paused after start. Check the developer tools for the
                                                                 connection uri.
  -r, --reuse-window                                             Force opening a file or folder in the last active window.
  --user-data-dir <dir>                                          Specifies the directory that user data is kept in, useful when
                                                                 running as root.
  --log <level>                                                  Log level to use. Default is 'info'. Allowed values are
                                                                 'critical', 'error', 'warn', 'info', 'debug', 'trace', 'off'.
  --verbose                                                      Print verbose output (implies --wait).
  -w, --wait                                                     Wait for the files to be closed before returning.
  --extensions-dir <dir>                                         Set the root path for extensions.
  --list-extensions                                              List the installed extensions.
  --show-versions                                                Show versions of installed extensions, when using
                                                                 --list-extension.
  --install-extension (<extension-id> | <extension-vsix-path>)   Installs an extension.
  --uninstall-extension (<extension-id> | <extension-vsix-path>) Uninstalls an extension.
  --enable-proposed-api <extension-id>                           Enables proposed api features for an extension.
  --disable-extensions                                           Disable all installed extensions.
  --disable-gpu                                                  Disable GPU hardware acceleration.
  -s, --status                                                   Print process usage and diagnostics information.
  -v, --version                                                  Print version.
  -h, --help                                                     Print usage.
[anders@idea ~]$ sudo code 
You are trying to start vscode as a super user which is not recommended. If you really want to, you must specify an alternate user data directory using the --user-data-dir argument.
[anders@idea ~]$ sudo code --user-data-dir=/root  <------ ok
[anders@idea ~]$ sudo code --user-data-dir /root
You are trying to start vscode as a super user which is not recommended. If you really want to, you must specify an alternate user data directory using the --user-data-dir argument.
[anders@idea ~]$ sudo su
[root@idea anders]# code --user-data-dir /root
You are trying to start vscode as a super user which is not recommended. If you really want to, you must specify an alternate user data directory using the --user-data-dir argument.
[root@idea anders]# code --user-data-dir=/root <------- ok
[root@idea anders]# 
'''

**Comment by bpasero** [comment]
I see, I think this is just an issue with our code.sh script, I can fix that.

**Comment by izznogooood** [comment]
That's great, thanks.
