### ISSUE TITLE
Save User Settings Across Machines/PCs

### ISSUE THREAD

**Issue by gitDylanHub** [Microsoft/vscode#41427]
Is there a way to set and keep VS Code User Settings across different Machines/PCs?

- VSCode Version:1.19.2
- OS Version: Windows 10, any OS

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by AlexandrLi** [comment]
Try this useful extension:
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
