### ISSUE TITLE
Support to open windows in the same (Linux) workspace window

### ISSUE THREAD

**Issue by lufinkey** [microsoft/vscode#41424]
- VSCode Version: 1.19.1
- OS Version: Linux Mint 18.2

Steps to Reproduce:

1. Open visual studio code in a separate workspace
2. Attempt to open a code file (js, php, whatever) in vscode
3. Watch as you switch workspaces and the file opens in the already opened vscode window

Expected Behavior

1. Open visual studio code in a separate workspace
2. Attempt to open a code file in vscode
3. vscode sees that there is no open vscode window in this workspace, and opens one

At the very least this should be an option. It's been driving me crazy for weeks because every other text editor follows the expected behavior

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@lufinkey I cannot reproduce, what are the exact steps? What is opened in the first window and what is opened in the second window and what file are you trying to open and how do you open it?

**Comment by lufinkey** [comment]
On most Linux desktop environments, there is a thing called [workspaces](https://help.ubuntu.com/stable/ubuntu-help/shell-workspaces.html). The idea of them is to divide work into different "screens".

If visual studio is open on a workspace, and I switch to a different workspace and try to open a file with visual studio code, it will open in the currently open window, rather opening a new window in the current workspace. Most text editors that I have used will open a new window in the current workspace. It would be preferable if the latter was the default behavior, or at the very least if there was an option available to change the behavior.
