### ISSUE TITLE
vscode app becomes unresponsive in editor although menus work

### ISSUE THREAD

**Issue by arrowplum** [Microsoft/vscode#41426]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
comments|Ale|1.0.3
bracket-pair-colorizer|Coe|0.10.14
vscode-markdownlint|Dav|0.12.0
xml|Dot|1.9.2
vsc-material-theme|Equ|1.2.0
vscode-github|Kni|0.25.0
vscode-simple-icons|Lau|1.8.0
vscode-docker|Pet|0.0.23
path-intellisense|chr|1.4.2
goto-documentation|cxf|0.0.1
gitlens|eam|7.2.0
prettier-vscode|esb|1.0.1
CppSnippets|har|0.0.13
rest-client|hum|0.16.2
c-cpp-flylint|jbe|0.5.4
Go|luk|0.6.72
cpptools|ms-|0.14.5
vscode-lldb|vad|0.7.3
vscode-todo-highlight|way|0.5.11
debug|web|0.21.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Use for a few days without restarting editing largish c project
2. At some point see gutter not redrawn and clicks in app (under toolbar) are not registered

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
@arrowplum We have some tools to help analyse performance issues. Check out https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by arrowplum** [comment]
@aeschli is it a performance issue? It seems like it just goes non responsive until I restart. If I resize the window it all goes blank.

**Comment by arrowplum** [comment]
I will try the code  --status thing next time it happens maybe there is more info there

**Comment by arrowplum** [comment]
@aeschli output of code --status
```
ATTENTION: default value of option force_s3tc_enable overridden by environment.

Version:          Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
OS Version:       Linux x64 4.13.0-26-generic)
CPUs:             Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (4 x 3095)
Memory (System):  7.55GB (0.94GB free)
Load (avg):       1, 1, 1
VM:               100%
Screen Reader:    no

CPU %	Mem MB	Process
    1	   108	code main
    0	    23	   zygote
    6	   301	     window (● ldap_ee.c - Untitled (Workspace) - Visual Studio Code)
    0	    54	       terminal
    0	     0	         /bin/bash
   14	   100	           ./target/Linux-x86_64/bin/asd --config-file ../joe_aerospike_dev.conf
    0	   116	       watcherService
    3	   155	       extensionHost
    0	    46	         electron_node server.js 
    0	    46	         electron_node jsonServerMain.js 
    0	    70	         /home/joem/.vscode/extensions/ms-vscode.cpptools-0.14.5/bin/Microsoft.VSCode.CPP.Extension.linux
    0	    31	           /home/joem/.vscode/extensions/ms-vscode.cpptools-0.14.5/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 15338 0
    0	    15	           /home/joem/.vscode/extensions/ms-vscode.cpptools-0.14.5/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 15338 2
    0	    46	         electron_node server.js 
    1	   178	         /home/joem/.vscode/extensions/ms-vscode.cpptools-0.14.5/bin/Microsoft.VSCode.CPP.Extension.linux
    0	    23	           /home/joem/.vscode/extensions/ms-vscode.cpptools-0.14.5/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 31472 0
    0	    54	       searchService
    0	    39	       terminal
    0	     0	         /bin/bash
    0	   100	     shared-process
    3	    85	   gpu-process

Workspace Stats:
|  Window (● ldap_ee.c - Untitled (Workspace) - Visual Studio Code)
|    Folder (aerospike-server-enterprise): 1122 files
|      File types: c(349) h(329) lua(76) filters(27) vcxproj(27) config(23)
|                  html(21) md(14) mk(11) gitignore(11)
|      Conf files: makefile(38) cmake(8) sln(3)
|    Folder (aerospike-server): 2649 files
|      File types: h(616) o(476) c(399) d(226) 0(59) cc(57) lua(56) in(30)
|                  sh(22) gitignore(17)
|      Conf files: makefile(25) cmake(8) sln(4) launch.json(1)
|                  settings.json(1)



```

**Comment by bpasero** [comment]
@arrowplum next time this happens can you maybe make a screenshot or recording of how this looks like?

**Comment by bpasero** [comment]
@arrowplum are you using VS Code in a VM?

**Comment by arrowplum** [comment]
Yes. VMware Version 10.1.1 (7520154) running ubuntu 16.04.3 LTS

**Comment by bpasero** [comment]
@arrowplum maybe try to run "`code --disable-gpu`" and see if that helps.

**Comment by arrowplum** [comment]
@bpasero you marked this needs more info. I gave you the more info but you didn't remove the tag. vscodebot now closed this (very real) issue. I upgraded and noticed the issue is still there unless I --disable-gpu. Please reopen it since I cannot.

**Comment by bpasero** [comment]
@arrowplum it would have helped if you would have commented on my question I asked? So does it not reproduce when you run code --disable-gpu?
