### ISSUE TITLE
`--wait` doesn't return when opening a new window and closing the first one

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4142]
Related to #4006

OS X
1. Close all Code instances
2. Run `code-alpha --wait monkey.txt`, do some changes, save
3. Open a new Window
4. Close the first one

I'd expect the command line to return after step 4.

**Comment by bpasero** [comment]
Would be solved with https://github.com/Microsoft/vscode/issues/4159

**Comment by mhofman** [comment]
I have the same issue on Windows 10, Code version 1.1.0.

**Comment by bpasero** [comment]
Yes, this is indeed not fixed yet.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/18199
