### ISSUE TITLE
Windows search service process 'SearchIndexer.exe' seems to block VSCode installation

### ISSUE THREAD

**Issue by codespook** [microsoft/vscode#41421]
- **VSCode Version**: 1.19.2 (but not version specific in my opinion, same behavior occurred in previous versions too)
- **OS Version**: Windows 7 SP1 64 bit

**Steps to Reproduce**:

1. Click "Check for update" through the bottom left corner gear menu in VSCode.
2. If an update is available and is downloaded, click "restart to update" in the bottom left corner gear menu in VSCode.
3. The installer will be perpetually stuck in the "Preparing to install..." step.
4. Open task manager. `SearchIndexer.exe` will probably be running. Kill that process.
5. Observe how the installer immediately enters the next installation step.

**Does this issue occur when all extensions are disabled?**: Irrelevant

**Comment by roblourens** [comment]
SearchIndexer.exe is for the windows search service, not related to vscode search. Any idea why it would impact install @joaomoreno?

**Comment by nikw92** [comment]
Updated issue title to be more specific. Thanks @roblourens.

**Comment by joaomoreno** [comment]
@nikw92 Are you sure about that state being perpetual? If you wait long enough, does the update eventually start?

**Comment by joaomoreno** [comment]
Yeah 15 minutes is a good wait time...

I have no idea what is going on here.
