### ISSUE TITLE
Drag and drop feedback lacking when reordering tabs/open editors

### ISSUE THREAD

**Issue by devuxer** [Microsoft/vscode#41420]
The ability to reorder tabs/open editors via drag and drop is an excellent feature of VSCode, but it's difficult to tell when you release the mouse button exactly where the dropped tab/editor is going to end up.

If you look at how tab reordering works in Chrome or Firefox (or Visual Studio, for that matter), you don't actually have to wait to release the mouse button to see where the tab is going to end up--it previews the reordering of tabs for you as you're dragging. With Excel, if you drag a worksheet tab to a different position, a little triangle appears to point to where the tab will drop.

With VSCode, however, the tab you are currently mousing over highlights, but it's not obvious whether the tab you're dragging will end up before or after the highlighted tab. It would be preferable to highlight the gap between the tabs (like Excel) or simply preview where the tab will end up (like Chrome, Firefox, etc.).

The same principle applies when dragging and dropping within the Open Editors panel. It should be obvious which rows the dropped row will end up between before dropping it.

**Comment by devuxer** [comment]
@bpasero ,

Could you please reference the duplicate issue? I did search through all open issues with "drag and drop" but didn't find it. Thx.

**Comment by bpasero** [comment]
@devuxer no I would not do that. But the label is a good indicator: just go through the issues labeled `workbench-tabs` and you should find it.
