### ISSUE TITLE
Pasting multiple lines into terminal doesn't work for certain terminal programs.

### ISSUE THREAD

**Issue by ghurley** [Microsoft/vscode#41428]
- VSCode Version: 1.19.2
- OS Version: Mac Sierra 10.12.6

Steps to Reproduce:

1. Open the integrated terminal
2. Start ipython
3. Copy multiple lines (statements) to the clipboard
4. Paste them into the integrated terminal's running ipython REPL.

Only the first statement will go through. All statements will be correctly pasted if instead of ipython you use the standard python REPL. All statements will _also_ get pasted if instead of pasting to the integrated terminal, you paste to ipython that's running in an external terminal (e.g. Terminal.app). Multiple lines of text will _also_ get pasted to ipython in the integrated terminal if the lines collectively constitute a single statement. E.g.

foo = [1,
           2]

ipython is the only program I've found where this occurs and given that it correctly accepts multiline statements it's almost certainly a problem with ipython. However, I'm still filing it as an issue because ipython does not behave this way when run in any other terminal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
We simply send the pasted text over to the shell, in this case ipython. So it's probably not handling it correctly, maybe the specific line endings being sent aren't working in ipython?
