### ISSUE TITLE
Release note link does not respect vscode version

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4143]
Related to #4023

Steps to Reproduce:
1. Open local storage and modify key `storage://global/releasenotes/lastversion` to an older version
2. Reload code - notice how we show the release notes popup, click on the 'Release Notes'
3. User is taken to the following link https://code.visualstudio.com/updates#vscode
4. I would expect that the release notes of the current vscode are shown - not the latest

The scenario where I see this happening is that we want to notify insiders what is updated in their update, so we change the https://code.visualstudio.com/updates#vscode, however now some user which is using stable is coming back from vacation and opens stable for the first time - he gets updated and gets the wrong release notes (the ones created for insiders).

**Comment by joaomoreno** [comment]
Well that page shows the release notes for *all* versions.

**Comment by isidorn** [comment]
No, it does not, it only shows the latest version for me.
There are links for other versions, but the user is taken directly to the latest

**Comment by joaomoreno** [comment]
It is the only link we have access to in source. It will be ok for 90% of the cases. Finally, it has also been like this since a year and we never heard complaints.

We can always disable this popup for insiders, but I think that would suck.

**Comment by isidorn** [comment]
It should maybe be possible to define this link per vscode product, so insiders would go to one link, stable to another and so on...
I agree it is not important since it works for 90% case but that is why I tagged this as a feature-request

**Comment by mjbvz** [comment]
I believe this was fixed. Our current release note flow has changed quite a bit. Please open if you think this issue still exists
