### ISSUE TITLE
editor.autoClosingBrackets does not affect python f"", r"", b"" strings autocompletion

### ISSUE THREAD

**Issue by pohmelie** [Microsoft/vscode#41434]
```
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:41:01.414Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
When `editor.autoClosingBrackets` set to `false` only simple `"` and `'` stop autocompletes, but `f"`, `b"`, `r"` and combinations are still autocompletes. Maybe #35636 is the reason, I'm not familiar with codebase.

**Comment by fireattack** [comment]
There is also a problem when you end your f string with `}`.

For example, try to type 
```python
print(f'my var is {var}')
```

It will not only doesn't auto close the quote when you typing `f'`, it also will place **two** quotes when you type `'` between `}` and `)`, which IMO is more annoying.

See the animation below.

![image](https://user-images.githubusercontent.com/4130991/39833418-9a480eec-538f-11e8-8e75-7cbc393bda2a.png)

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/55315
