### ISSUE TITLE
inconsistant comment behavior with command + / on jsx

### ISSUE THREAD

**Issue by TrashPanda** [Microsoft/vscode#41437]
When commenting multiple lines of jsx code with command + / 
what you are seeing:
```            
{/* <div className="small-bar"></div>
<div className="medium-bar"></div>
<div className="large-bar"></div> */}
```
compare to javascript code:
```  
// constructor(props) {
//   super(props);
// }
```
what I would expect for jsx:
```            
{/* <div className="small-bar"></div> */}
{/* <div className="medium-bar"></div> */}
{/* <div className="large-bar"></div> */}
```

Imo multiple singleline comment is better during the editing the code, and I would expect consistent behavior from command + / to use singleline only

- VSCode Version: 1.17.1
- OS Version: mac/ubuntu

Steps to Reproduce:

1. command + / over multiple lines of jsx code 
2. compare to command + /  over multiple line javascript code 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
JSX has no concept of a proper line comment, so we fallback to the block comment for the entire selection. This is the designed behavior

**Comment by TrashPanda** [comment]
Maybe I am used to webstorm. It's really helpful when you can comment out the entire section and then recover the code line by line. Is there a way to change the setting for that?
