### ISSUE TITLE
Code Helper attempts to index MPEG-TS files in project and eats 100% cpu

### ISSUE THREAD

**Issue by jon-valliere** [Microsoft/vscode#41439]
- VSCode Version: 1.19.2
- OS Version: 10.13.2

Steps to Reproduce:

1.  Add a MPEG-TS file (e.g. somefile.ts) outside of your normal code folder but somewhere in the project so it shows up in "Explorer" in VSC
2. Look at your processes -- intellicode totally stops working and the process eats 100%

The TypeScript processor should be smart enough to be able to detect if the file is text or not.

**Comment by usernamehw** [comment]
I wonder if you can exclude media folder(or files) from `tsconfig.json`:
```javascript
{
  // ...
  "exclude": [
    "media"
  ]
}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21136
