### ISSUE TITLE
IntelliSense engine is not responding

### ISSUE THREAD

**Issue by menting311** [Microsoft/vscode#41436]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.5

---

Steps to Reproduce:

1. Fresh install of VS code, only cpptools extension installed
2. Set all needed include paths to clear all squiggles.
3. Start typing cpp object and hit '.', this is where I expect auto complete suggestions. I do get suggestions when I type one more letter, but it is showing all symbols, not just those that match the type of object I am using.

In the output window of VS code I see this everytime I expect a auto complete suggestions:
Failed to read response from server: 4
IntelliSense engine is not responding. Using the Tag Parser instead.
Failed to send request to server: 17
IntelliSense client has disconnected from the server - D:\REPOSITORY\WMS\SRC\HUB_REQ_TOTALS.CPP

In the log file (vscode.cpp.log.10300.txt) it seems to get cutoff when writing to the file. It starts with....
Log initialized. Verbosity level = 7
handle_compile
handle_change
changes(1) range [0, 0], cursor [4294967295]
handle_quick_info
edge::host - open file: D:\REPOSITORY\WMS\SRC\HUB_REQ_TOTALS.CPP
edge::host - open file: D:\REPOSITORY\WMS\CONTROLLER\HUBSBASED.HPP
edge::host - open file: D:\REPOSITORY\WMS\CONTROLLER\BASE.HPP
edge::host - open file: D:\REPOSITORY\WMS\LIB\DAL\HUBS_FWD.HPP
edge::host - open file: D:\REPOSITORY\WMS_VS_PROJECTS\3RD_PARTY_LIBS\BOOST_1_34_1\BOOST\FUNCTION.HPP
edge::host - open file: D:\REPOSITORY\WMS_VS_PROJECTS\3RD_PARTY_LIBS\BOOST_1_34_1\BOOST\PREPROCESSOR\ITERATE.HPP
.....

Then about 1,000 lines of similar output, then finishes with:
.....
edge::host - open file: D:\REPOSITORY\WMS_VS_PROJECTS\3RD_PARTY_LIBS\BOOST_1_34_1\BOOST\FILESYSTEM\CONVENIENCE.HPP
edge::host - open file: C:\USERS\TMENTING\APPDATA\LOCAL\LXSS\ROOTFS\USR\INCLUDE\C++\5\STACK
edge::host - open file: C:\USERS\TMENTING\APPDATA\LOCAL\LXSS\ROOTFS\USR\INCLUDE\C++\5\BITS\STL_STACK.H
edge::host - open fi

Is there anything else I could provide to figure out what is happening?

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please file this against the cpp tools repo: https://github.com/Microsoft/vscode-cpptools/issues
