### ISSUE TITLE
Extension provided keyboard shortcuts show as source "Default"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#41433]
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install the Sublime keymap extension
2. Open Keyboard Shortcuts editor
3. Search for "zen"

Both the VS Code default Toggle Zen Mode (Ctrl+K Z) and Sublime keymap (Shift+F11) are displayed as source "Default".

We should at least let the user know if a keyboard shortcut came from an extension, better yet the specific extension name.

**Comment by usernamehw** [comment]
Could be a duplicate of https://github.com/Microsoft/vscode/issues/37034

**Comment by sandy081** [comment]
Thanks @usernamehw for mentioning the dup
