### ISSUE TITLE
Debug Console: allow process output to be persistent

### ISSUE THREAD

**Issue by bsdooby** [Microsoft/vscode#41431]
- VSCode Version: 1.19.2
- OS Version: Linux (Slackware 14.2, 64bit)
- Extension: C/C++ 0.14.5

Steps to Reproduce:

1. Configure to use internal terminal
2. Start application in non-debug mode (i.e. SHIFT+F5)
3. Application prints to std::cout (standard console output) for debugging purposes
4. Application exits and internal terminal gets closed
5. Upon next start prior output of application is lost and cannot be used
    for comparison (e.g. poor man's debugging) with current output

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is a fair feature request.
If more users ask for this I would be open for a PR that ads a configuration for this.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L666
