### ISSUE TITLE
editor.tabSize being ignored

### ISSUE THREAD

**Issue by mccreeker** [Microsoft/vscode#41435]
- VSCode Version: 1.19
- OS Version: W10

Steps to Reproduce:

1. add "editor.tabSize": 2 to your Workspace Settings
2. notice VS Code never auto-formats any indents to 2 spaces

Does this issue occur when all extensions are disabled?: Yes

**Comment by lacroixdavid1** [comment]
From https://code.visualstudio.com/docs/getstarted/settings : 

```
  // When opening a file, `editor.tabSize` and `editor.insertSpaces` will be detected based on the file contents.
  "editor.detectIndentation": true,
```

Setting `editor.detectIndentation ` to `false` will make `editor.tabSize` to work.

**Comment by aeschli** [comment]
Thanks @lacroixdavid1 !
