### ISSUE TITLE
Integrated terminals not persisted between restarts

### ISSUE THREAD

**Issue by lidderupk** [Microsoft/vscode#41443]
- VSCode Version:1.19.2
- OS Version: Mac Sierra 10.12.6

Steps to Reproduce:

1. Open a project in vs code.
2. Add a few integrated terminals.
3. Rename terminals.
![image](https://user-images.githubusercontent.com/3187457/34804342-fa5a61ba-f62c-11e7-8a1a-02fcb8f2b929.png)
4. Save workspace as `file.code-workspace`
5. Restart vs code by using `code file.code-workspace`. Or restart code and open workspace.
6. All the files are open as before 👍.
7. The terminal goes back to bash 👎.
![image](https://user-images.githubusercontent.com/3187457/34804355-1698d726-f62d-11e7-936a-4474e7f1af84.png)

**_Is there a way to persist the different terminals between restarts?_**

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20013
