### ISSUE TITLE
vscode打开就显示扩展宿主意外终止，一直就是这样，

### ISSUE THREAD

**Issue by xiangyue520** [Microsoft/vscode#41441]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
vscode打开就显示扩展宿主意外终止，一直就是这样，
只是更新的时候，才会不显示，但是第二次启动就又会这样显示，已经重新安装过vscode

**Comment by fightingcat** [comment]
translation: Extension host terminated unexpectedly.
Can you try to start vscode with "--disable-extensions"? Then remove your extensions one by one to figure out which extension caused problem.
你能试试加上"--disable-extensions"参数启动vscode吗？在图标上点右键，属性，在目标一项中加入这个参数（要加在引号后面带空格）。然后把扩展一个一个卸载掉，看看是不是哪个扩展引起的。

**Comment by wsz7777** [comment]
windows 用户啊，这个就很尴尬。。。
