### ISSUE TITLE
VSC does not detect changes on the disk until trying to save the file

### ISSUE THREAD

**Issue by LordHog** [Microsoft/vscode#41442]
- VSCode Version: 1.19.2
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Open a file in VSC (I had a project folder open).
2. Open the same file in another editor (I had used UltraEdit), modify the file, then save it.
3) When switching back to VSC no changes are detected.
4) In VSC make some modifications to the file (I just typed a space character) then try to save the file
5) VSC displays an "Error", "Failed to save 'file_name_here.ext': The content of disk is newer: Click to compare your version with the one on disk."

**Comment by LordHog** [comment]
Hello VSCodeBot, I did search prior to creating this.  I had searched using "Detect Modification" and "Detect Change(s)" and "Detect", but I couldn't find anything.  Apparently my "search fu" is weak with this bug.  Can you reference the duplicate report?

**Comment by nousacademy** [comment]
Fix this!!!! About to delete!
