### ISSUE TITLE
Missing`isEditing` keyboard condition in Explorer "when" Context

### ISSUE THREAD

**Issue by damassi** [Microsoft/vscode#41440]
I'm setting up keyboard shortcuts for the sidebar explorer, but I'm noticing that when in input mode, existing keyboard shortcut commands still apply. 

For example: 

```json
  {
    "key": "a",
    "command": "explorer.newFile",
    "when": "explorerViewletVisible && filesExplorerFocus"
  }
```

<img width="276" alt="screen shot 2018-01-10 at 3 40 23 pm" src="https://user-images.githubusercontent.com/236943/34801268-9856b9f6-f61c-11e7-840a-f6d26bdcfd9f.png">

Whenever I'm in edit / input mode, if I type the letter "a" it refires the above command leading to the inability to enter the character. 

**Possible Fix:**

By adding an `isEditing` condition, I can check against it via: 

```json
  {
    "key": "a",
    "command": "explorer.newFile",
    "when": "explorerViewletVisible && filesExplorerFocus && !isEditing"
  }
```

Thoughts? Is there any other workaround for this?

**Comment by usernamehw** [comment]
```json
"when": "explorerViewletVisible && filesExplorerFocus && !inputFocus"
```

**Comment by damassi** [comment]
Yup, this does it! Thanks @usernamehw.
