### ISSUE TITLE
Improve diff editor title when comparing files

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4144]
Related to #3954

Maybe we could use the subtitle part to show the folders, like:

**tK4ZY9_monkey.txt ↔ monkey.txt** - /private/var/folders/lr/b36df5dx0y7cy_mywg5r623800000gn/T, /Users/joao/Work/fakeproject

![image](https://cloud.githubusercontent.com/assets/22350/13746374/740772e8-e9f3-11e5-8e16-6b6143bbb085.png)

**Comment by bpasero** [comment]
-1. but I thought about replacing the path with something shorter if it is actually a substring of the tmp path (e.g. $tmp/).

**Comment by joaomoreno** [comment]
Why :-1: when we are actually doing it across the product?

![image](https://cloud.githubusercontent.com/assets/22350/13749186/91cdfb46-ea00-11e5-84f2-6154f4123c48.png)

![image](https://cloud.githubusercontent.com/assets/22350/13749228/b5b41c5c-ea00-11e5-81fe-388dd5d39923.png)

![image](https://cloud.githubusercontent.com/assets/22350/13749201/9e3c0e40-ea00-11e5-864e-8ac53ee09379.png)

![image](https://cloud.githubusercontent.com/assets/22350/13749213/a4c54722-ea00-11e5-9468-8b716d4051aa.png)

**Comment by bpasero** [comment]
@joaomoreno we used to have what you suggest and I always felt it was hard to read what exactly is being compared so I chose the easiest thing that could possibly work and just show 2 full paths. the issue here is the ugly tmp path, I did not hear complaints otherwise.

**Comment by joaomoreno** [comment]
That's cause no one uses the `Compare with` action :dancer: 

Likewise, I think it looks awkward here:

![image](https://cloud.githubusercontent.com/assets/22350/13749502/05e8b7fe-ea02-11e5-97ac-2d649d127acb.png)

**Comment by bpasero** [comment]
Nah, how do you think I got so many points on SO: http://stackoverflow.com/questions/30139597/visual-studio-code-is-there-a-compare-feature-like-that-plugin-for-notepad

;)

**Comment by bpasero** [comment]
I still think in any case it would help to replace the long tmp path with something short.

**Comment by bpasero** [comment]
Examples where imho it does not work:

Comparing a workspace local file to out of workspace

![image](https://cloud.githubusercontent.com/assets/900690/13754362/f66b4764-ea16-11e5-8077-ea5fbf3cd32e.png)

Comparing root level file to other file

![image](https://cloud.githubusercontent.com/assets/900690/13754376/0686e8ce-ea17-11e5-8d8d-1621a26d4e2f.png)

@stevencl @bgashler1 maybe you have some ideas

**Comment by bpasero** [comment]
@joaomoreno I also think in your case it makes no sense to show xyz_monkey.txt, I think it would make more sense to allow for the --diff parameter to set a label for the left hand side so that the context from where this file is from becomes clear (e.g. the commit hash or message).

**Comment by joaomoreno** [comment]
+1 on labels, git even supports that such that it would appear as `Theirs` and `Ours` in the UI

**Comment by bpasero** [comment]
Closing in favour of #4452
