### ISSUE TITLE
statusBar.background not working

### ISSUE THREAD

**Issue by Saoskia** [Microsoft/vscode#41448]
I've included a screenshot showing the problem with the code contained in the user settings file.
![screen shot 2018-01-11 at 1 13 13 pm](https://user-images.githubusercontent.com/18042873/34805257-364c824e-f6d1-11e7-832f-4e8970863130.png)

editorLineNumber.foreground is working as it should, but the background colour of the status bar is not changing. I've tried it with multiple themes, including the default themes, but the result is always the same.

I should also note that prior to this no longer working, I opened VSCode and it said my version was corrupted (statusBar.background was still working at this time). However, after closing and reopening the program, the error did not reappear, and the [Unsupported] that popped up after the error was no longer in the title bar. I did reinstall VSCode, however the problem persisted.

Obviously the issue isn't a big deal, purely cosmetic, but it does bother me.

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unity-debug|Uni|1.2.1
python|ms-|0.9.1
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Include the code featured in the above screenshot in the user settings file and save.
2. The line numbers will change colour, but the status bar will not.

Reproduces without extensions: Yes

**Comment by usernamehw** [comment]
Could this be no opened folder case?
```json
"statusBar.noFolderBackground": "#ffff00",
```

**Comment by Saoskia** [comment]
Wow, yeah it is. That didn't even occur to me, thanks :)
