### ISSUE TITLE
Extensions per OS Platform

### ISSUE THREAD

**Issue by mtxr** [Microsoft/vscode#41444]
- VSCode Version: 1.20 Insider
- OS Version: OSX 10.13.1

I'm the creator of https://github.com/mtxr/vscode-sqltools and I would like to give support for SQLite3 on my extension.

The problem is that the node `sqlite3` or others sqlite modules are compiled using node-gyp during `npm install`.

I would be good to have a extension supports per OS or mark some packages to be built/download during extension installing process.

Any other suggestions?

**Comment by joaomoreno** [comment]
@mtxr People so far have been doing the downloading themselves in the `activate` call.
