### ISSUE TITLE
.editorconfig setting for *not* adding a newline is not respected

### ISSUE THREAD

**Issue by bdharrington7** [Microsoft/vscode#41447]
- VSCode Version:
```
code -v
1.19.2
490ef761b76b3f3b3832eff7a588aac891e5fe80
x64
```
- OS Version:
macOS 10.13.1

Steps to Reproduce:

1. Edit .editorconfig to not add newlines for files in a certain directory (or everything)
2. Restart vscode
3. remove final newline on the file, hit save
4. note that the new line is inserted anyway

for reference, here was the .editorconfig I was using: 
```
[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = false
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by lacroixdavid1** [comment]
From https://github.com/editorconfig/editorconfig-vscode as it is the recommended extension from deprecated project https://github.com/Microsoft/vscode-editorconfig :

```
Known Issues

trim_trailing_whitespace = false is not applied when user/workspace setting of files.trimTrailingWhitespace is set to true.
```

See issue https://github.com/editorconfig/editorconfig-vscode/issues/153
