### ISSUE TITLE
Bug: While saving cursor for typing moves up of document space and goes to selection

### ISSUE THREAD

**Issue by sanudatta11** [Microsoft/vscode#41451]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
angular2-snippets|dan|1.0.16
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
vsc-material-theme|Equ|1.2.0
prettier-vscode|esb|1.0.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
php-pack|fel|1.0.1
code-runner|for|0.8.7
terminal|for|0.0.10
vue-snippets|hol|0.1.5
rest-client|hum|0.16.2
crane|Hvy|0.3.8
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
HTMLHint|mka|0.4.0
prettify-json|moh|0.0.3
python|ms-|0.9.1
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
team|ms-|1.122.0
debugger-for-chrome|msj|4.0.0
vetur|oct|0.11.5
view-in-browser|qin|0.0.5
typescript-hero|rbb|1.8.0
java|red|0.16.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
python|tht|0.2.3
cordova-tools|vsm|1.3.2
gitblame|wad|2.2.0
ReactSnippets|xab|1.7.0
html-css-class-completion|Zig|1.15.0

(6 theme extensions excluded)

---

Steps to Reproduce:

1. Write any code and type Ctrl+S to save it
2. The Cursor moves away from document space and goes to document selection
3. Press down arrow next moment, It goes down to end of the document.
4. Creates bad UX because I need to always find the line number if anytime I press down after saving.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@sanudatta11  I cannot reproduce. Focus does not move when invoking ctrl+S:

![kapture 2018-02-05 at 14 28 49](https://user-images.githubusercontent.com/5047891/35806767-eb79a8aa-0a80-11e8-91ba-53b29fdc1a80.gif)
