### ISSUE TITLE
Keyboard conflicts on Linux

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4145]
Related to #4092

- VSCode Version: 18ebb4a4f5491af7b16e91e42fc36410bbb2e4d7
- OS Version: Linux

Steps to Reproduce:

1. Open vscode, open developer tools -> notice warnings

![screen shot 2016-03-14 at 14 53 16](https://cloud.githubusercontent.com/assets/1926584/13746657/9eae2a54-e9f4-11e5-9771-dfbdac74b7f2.png)

**Comment by weinand** [comment]
This conflict prevents column selection with the keyboard on Linux.

**Comment by alexandrudima** [comment]
I'm sorry about that, I didn't get a chance last night to try it out on Linux. I suggest we make these commands not bound by default on Linux since there are no modifiers + arrow keys combinations left. Objections?
