### ISSUE TITLE
Path intellisence not working with paths aliases

### ISSUE THREAD

**Issue by Ristaaf** [Microsoft/vscode#41458]
- VSCode Version: 1.19.1
- OS Version: Windows 10 Fall Creators Update

Steps to Reproduce:

1. Create a paths alias in the tsconfig.json as this: ```"paths": {
      "@myapp/*": ["app/*"]
    }```
2. Try to import from the alias triggering intellisence after writing ```import {} from "@myapp/``` This will not show any folders under app, so the path intellisence does not work at all in this use case!

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/19113

Should be fixed by TS 2.7

**Comment by octref** [comment]
@mjbvz Is this supposed to be fixed? Does not seem to be working for me.

**Comment by octref** [comment]
Tested together with @mjbvz. If you have a baseUrl it should work. However, the path completions items are not having the correct `CompletionItemKind`.

**Comment by ramya-rao-a** [comment]
@mjbvz How do you want to handle this? Push it to Feb for the right CompletionKind or mark it as verfied?

**Comment by mjbvz** [comment]
I’ll open another bug for the kind. I’d say the main feature is verified

**Comment by ramya-rao-a** [comment]
Thanks @mjbvz 
Added the verified label

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/21582 to track the kind issue upstream

Will be opening a few more upstream bugs around `compilerOptions.paths` path completions as well
