### ISSUE TITLE
 The properties of the ReactNative component after the upgrade are not prompted 

### ISSUE THREAD

**Issue by caozhepeng** [Microsoft/vscode#41457]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
file-icons|fil|1.0.7
auto-rename-tag|for|0.0.15
vscode-angular2-emmet|jak|2.0.3
react-native-snippet|jun|0.3.7
console-log-snippet-javascript|lev|0.1.0
debugger-for-chrome|msj|4.0.0
vscode-stylesheet-beautify|n23|0.0.3
html-snippets|wge|0.1.5

Example:
     <FlatList
            data={}
            renderItem={}>
          </FlatList>
When writing the 'data' attribute, only manually knocked out the 4 letters data, similarly, knock in "renderItem" this property can only be manually knocked out the word before the related attributes write a 'R' or 'ren' will prompt at the beginning of the R, you use a plugin no, this is how to solve, thank you!

**Comment by mjbvz** [comment]
Please provide a code example and some steps to reproduce this issue
