### ISSUE TITLE
open folder shortkey is not working in ubuntu 16.04

### ISSUE THREAD

**Issue by BHS-Web** [Microsoft/vscode#41452]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.4.0-98-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
closeunmodified|Gru|0.0.7
crane|Hvy|0.3.8
html-css-class-completion|Zig|1.15.0
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
vscode-database|baj|1.2.0
vscode-intelephense-client|bme|0.8.5
phpserver|bra|2.2.0
php-autocomplete|bsc|0.4.2
paste-image-to-qiniu|fav|0.0.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
php-pack|fel|1.0.1
code-runner|for|0.8.7
live-html-previewer|hdg|0.3.0
ftp-simple|hum|0.5.8
phpcs|ika|0.7.0
intellij-idea-keybindings|k--|0.2.18
vscode-gutter-preview|kis|0.12.2
csharp|ms-|1.13.1
copy-file-name|nem|1.0.0
vscode-css-peek|pra|2.0.3
LiveServer|rit|3.0.2
vscode-icons|rob|7.19.0
copy-copy-paste|roc|0.0.5
php-ci|sma|0.2.8
open-in-browser|tec|1.1.0
code-navigation|vik|0.2.0
highlight-matching-tag|vin|0.4.4
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please include enough details to reproduce the issue. It works for me.
