### ISSUE TITLE
Create shorcut that link to first compile error (Terminal view)

### ISSUE THREAD

**Issue by biboc** [microsoft/vscode#41454]
I use vscode tasks to compile my source code with gcc.
If gcc gives me 30 errors (Terminal view), I would like to clic on a shortcut  (ALT+E for instance) that brings me right in the source code where the error is.

Is it already available? Or could you make this possible?

**Comment by Tyriar** [comment]
What is the format of the paths in the errors?

**Comment by biboc** [comment]
I'm on Ubuntu, it's absolute path 
/home/USER/PROJECT/file.c:111:16: error: 'abcdefgh' undeclared (first use in this function)
         return abcdefgh;

Currently, I can CTRL+Left mouse to go to the error

**Comment by dbaeumer** [comment]
@sandy081 would make sense to put this into the problems view (Contributing the command) since this will work for all problems then (not only for problem detected by tasks)

**Comment by sandy081** [comment]
@dbaeumer What are the other problems (not generated by tasks) that are shown in the terminal

**Comment by dbaeumer** [comment]
I mean problems contributed via an extension.

**Comment by sandy081** [comment]
@dbaeumer Sorry, I am not sure if I understand what has to be supported by problems view? Is it that problems view contribute commands that can detect problems in the terminal and open the problem(file)?

**Comment by dbaeumer** [comment]
Something like "Open first problem" which then opens the file containing the first problem of the problem view. From there on we can navigate using the error navigation shortcuts of the editor.
