### ISSUE TITLE
Auto imports in JS/JSX and global refactoring

### ISSUE THREAD

**Issue by Dudelmoser** [Microsoft/vscode#41450]
There are basically two things which constantly force me to switch to IntelliJ/Webstorm for bigger React projects: refactoring across multiple files and auto imports.

Setting up redux actions, reducers etc. is really frustrating if you have to import all those action type constants manually, same with React components, actions themselves etc. I've tried several plugins and none of them gave reliable results. They usually don't work with unnamed default exports (meaning they look at the export variable name only instead of the class or function name), require manually triggering a scan before using newly created exports etc. Defining certain modules or folders to keep track of exports might be an option to avoid cluttering the import suggestions and decreasing the performance. Auto-importing when pasting - especially JSX code - would be a nice bonus. There's a decent extension for path intellisense, but it's so slow that I'm usally done typing before the path suggestion pops up.

IntelliJ also manages to refactor variables and even files reliably, including changing the import paths accordingly. 

I'm absolutely amazed by the rest of VSC, therefore I would love not having to switch IDEs for those two tasks.

**Comment by mjbvz** [comment]
Can you please split this into individual feature requests for missing features, or individual bug reports for something that is not working as expected. Please include repo steps and small code examples. [Here's our guide](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues)

Thanks
