### ISSUE TITLE
Assign default task to last task I've run

### ISSUE THREAD

**Issue by biboc** [Microsoft/vscode#41455]
I have many task and I constantly switch between task. 
I would like that each time I choose a task to be executed it becomes the default one ("generation task").
OR
Make it easier to change the default task, for instance, a button on the select task picker to set default task. Something easier than going in json configuration and add:
```
            "group": {
                "kind": "build",
                "isDefault": true
            }
```

Is it already available? Could make this possible?
Thanks

**Comment by dbaeumer** [comment]
This is currently not available. However Run Task uses a MRU list with the last executed task shown first. You can bind a keyboard short cut to Run Task. The executing the last task is pressing this short cut and then enter.

**Comment by alexr00** [comment]
There is also now a rerun task command that I think will accomplish what you want. https://code.visualstudio.com/docs/editor/tasks#_run-behavior
If that doesn't solve the use-case then I can re-open.
