### ISSUE TITLE
No 'Clone Git Repository' option under Start

### ISSUE THREAD

**Issue by realmohsin** [Microsoft/vscode#41465]
- VSCode Version: 1.19.2
- OS Version:  Windows 10 Home, Version 1709, OS Build 16299.192

Hello,
I am just starting out learning how to code.  I am using an online course offered on edx.org by Microsoft called 'Designing a Technical Solution.'  The course requires Visual Studio Code. 

The course was teaching me how to use Git with Visual Studio Code, but I ran into an issue.  According to the instructions there should be a 'Clone Git Repository' option on the Start page.  This is an earlier lecture video where I can see that option in the instructor's screen, under 'Open folder..' :
 [https://www.youtube.com/watch?time_continue=41&v=IpbECeZPkDI](url) 

This option is not available for me on my vscode start screen.  I have installed Git and in the output panel it says: **Using git 2.15.1.windows.2 from C:\Program Files\Git\cmd\git.exe**
But instead of 'Clone Git Repository...', I see 'Add Workspace Folder...'
Git also does not show up under Source Control Tab. (Not sure if that's relevant.)
Here is a screenshot of my vscode start screen:
![vscodestart](https://user-images.githubusercontent.com/35280245/34820349-394a9bcc-f68e-11e7-991f-0d0249160591.png)

I don't think I can continue the course if I can't figure out why my starting installations of vscode and git don't match what's in the course. I installed the latest versions of vscode and git using recommended options during setup.

Can someone please help me with this issue in a way a non-programmer can understand (if that's even possible) so that I can continue this introductory coding course?  I would greatly, greatly appreciate it.

**Comment by joaomoreno** [comment]
This action was removed from the Welcome page, unfortunately.

But here's a great tip: every time you want to run an action, try <kbd>F1</kbd> and type the action name, in this case: `Clone`.

**Comment by realmohsin** [comment]
Thank you.

**Comment by johnw6761** [comment]
Why was this removed?
