### ISSUE TITLE
"sourceFileMap" do not support relative path, can we update it ?

### ISSUE THREAD

**Issue by yrj1982hp** [Microsoft/vscode#41469]
- VSCode Version: 1.19.2
- OS Version: window 7

Steps to Reproduce:

1. Config as: 
             "sourceFileMap": {
                "/usr1/WN_NodeB_GIT" : "${workspaceFolder}\\..\\..\\..\\..\\"                
            },
2. VSCODE can't display the crrunt code line when debugging using single step or breakpoint,
3. change config as:
             "sourceFileMap": {
                "/usr1/WN_NodeB_GIT" : "${workspaceFolder}\\..\\..\\..\\..\\"                
            },
4.VSCODE can display the crrunt code line when debugging using single step or breakpoint

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@yrj1982hp for what kind of debugging is this? 
What is "crrunt"?

**Comment by yrj1982hp** [comment]
@yrj1982hp for what kind of debugging is this?
 What is "crrunt"?
------yrj1982hp :
current
 
There is no difference between the configs in step 1 and 3.
------yrj1982hp:
3.change config as:
 "sourceFileMap": {
 "/usr1/WN_NodeB_GIT" : "D:\NodeBCode\R19.1\WN_NodeB_GIT"
 },

**Comment by weinand** [comment]
What debugger extension are you talking about?
