### ISSUE TITLE
Windows 10下VScode编辑java文件，编码设置成UTF-8时，输入中文会变成乱码

### ISSUE THREAD

**Issue by sasha6806** [Microsoft/vscode#41462]
- VSCode Version: 1.19.1 with Java Extension Pack
- OS Version: Windows 10 home insider

Steps to Reproduce:

1. files.encoding = utf8
2. create a new file with name gbtest.php. you can input correct chinese.
3. then, create a new file with name gbtest.java. your input chinese will become wrong characters.
VScode的缺省编码方式是utf8
编辑一个新文件扩展名是php的，可以正常输入中文，输入法是win10自带的中文输入法
但是，编辑一个新文件扩展名是java的，输入的中文就变成了乱码，只有把VSCode的编码方式
变成GB2312，之前输入的中文才能正常显示

Does this issue occur when all extensions are disabled?: Yes/No
No
禁用Java Extension Pack和关联包之后，Java文件中文乱码现象消失

**Comment by bpasero** [comment]
This is https://github.com/redhat-developer/vscode-java/issues/394 (@sasha6806 @aeschli fyi)
