### ISSUE TITLE
分屏，主屏到扩展屏幕，光标位置错误

### ISSUE THREAD

**Issue by itcongaili** [Microsoft/vscode#41467]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
mssql|ms-|1.3.0
material-icon-theme|PKi|3.2.1
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.分屏，主屏到扩展屏幕，光标位置错误
2.

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment]
Translation: When using multiple monitors in extended mode, the cursor position is wrong.

**Comment by alexandrudima** [comment]
@itcongaili 

What do you mean the cursor position is wrong? Do you mean the mouse cursor or the blinking cursor? Can you include a screenshot?

What does multiple monitors have to do with it? Does this reproduce only when having multiple monitors? Do you use different scaling for the different monitors?
