### ISSUE TITLE
Long links in terminal are broken

### ISSUE THREAD

**Issue by pvpshoot** [Microsoft/vscode#41460]
When inapp terminal print long multiline links, clickable link is only first line

- VSCode Version: 1.19.2 
- OS Version: macOs 10.13.2 (17C205)
- zsh

Steps to Reproduce:

1. open terminal and echo long link, which will be moved to the next line

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rcjsuen** [comment]
@pvpshoot Do you mean that a) the hyperlink only underlines the first line and not the second and also that b) the second line cannot be clicked but the first link can?

Would you mind attaching a screenshot?

**Comment by pvpshoot** [comment]
I apologize if I was not clear
![src 2fcomponents 2fmap 2fmapservice js e2 80 94 elections_private 2018-01-11 14-55-23](https://user-images.githubusercontent.com/6636655/34822203-8701fabc-f6df-11e7-885e-6a1336484965.png)
the url is cut of by new line
and if i want to click it, the browser will open without `user_group_select`

**Comment by jay-bricksoft** [comment]
can confirm this behavior

- VSCode Version: 1.19.1
- OS Version: windows 10
- powershell

to reproduce: 

run this in therminal for a test:
```bash
node -e "console.log('test long link in vscode: http://abcdefghijklmnopqrstuvwxyz.ab/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/?a=a&b=b&c=c&d=d&e=e&f=f&g=g&h=h&i=i&j=j&k=k&l=l&m=m&n=n&o=o&p=p&q=q&r=r&s=s&t=t&u=u&v=v&w=w&x=x&y=y&z=z&_a=1&_b=2&_c=3&d=4&e=5&f=6&g=7&h=8&i=9&j=0')"
```
every part of the url after the (forced) linebreak will be cut off, when ctrl+click on that url in therminal

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28746
