### ISSUE TITLE
Deleting an extension does not give immediate user feedback

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4146]
Related to #4024

- VSCode Version: 18ebb4a4f5491af7b16e91e42fc36410bbb2e4d7
- OS Version: Linux

Steps to Reproduce:

1. Open VSCode, install an extension
2. quick open > show installed extensions > click on the delete button to uninstall the extension
3. I do not get any feedback and quick open stays open, I only get notifications once I manually close the quick open
4. I would expect quick open gets closed once I click on uninstall and that I see notifications once the extension gets uninstalled

**Comment by joaomoreno** [comment]
You know there is no notifications while quick open is open.

Closing as won't fix, cause I wanna move away from quick open.

**Comment by isidorn** [comment]
I am just saying that action should just close quick open

**Comment by joaomoreno** [comment]
It is in its current state because others feel that it shouldn't close, since you might want to uninstall other extensions.

**Comment by isidorn** [comment]
Ok, just my 2 cents that the current uninstall experience is bad and making it work for the most common case is more important (uninstalling one extension).
If a user wants to uninstall multiple extensions he can open quick open multiple times, he has more work to do but nothing feels broken. The current state with no uninstall feedback feels broken, especially now that we have introduced install feedback.

**Comment by joaomoreno** [comment]
Ok. Should it also close when clicking the *visually identical* install action?

**Comment by isidorn** [comment]
No, since for that I get feedback both in the quick open icon and in the status bar icon. And the scenario to install multiple extensions is higher likely to happen then to uninstall multiple imho.

Maybe the delete icon could also provide feedback like the install icon in quick open.

**Comment by joaomoreno** [comment]
I'd just get a bug that the two actions look alike but behave differently.

And the uninstall icon also provides feedback, it turn itself into the install one..

![bug](https://cloud.githubusercontent.com/assets/22350/13747865/a0e13fae-e9fa-11e5-8c75-fa498c06ae93.gif)

**Comment by isidorn** [comment]
Ok, makes sense, I just created this one that would improve this experience a bit I think
https://github.com/Microsoft/vscode/issues/4165
