### ISSUE TITLE
Provide update notifications for portable mode

### ISSUE THREAD

**Issue by schlamar** [microsoft/vscode#41470]
If you are using VS Code in portable mode, there is no convenient method to get a notification about an update:

- no notification / check in the app itself
- no RSS feed with releases or something similar (at least I haven't found anything)

**Comment by schlamar** [comment]
Just found out about https://github.com/Microsoft/vscode/releases.atom.

I guess I'm fine with that, though a check / notification in the app would be better.

**Comment by necodon** [comment]
It seems like update by itself , I use version 1.19 by 201801 , and I can see the version issue

**Comment by Alex-Khouri** [comment]
As far as I can tell, the problem isn't that the portable version doesn't provide update notifications, but rather that it simply cannot update itself. There are no options anywhere to check for updates, and when a new version is released the program doesn't display an option to update. As a result, the only way to update is to re-run the portable installer in the existing installation directory, which is inconvenient for two reasons:

1.) It takes the same amount of time as a full installation
2.) It erases your debugger configuration file, meaning that you have to re-configure the debugger from scratch

I had a suspicion that this could have something to do with the following code from the `settings.json` file in `..\VSCodePortable\App\DefaultData\code\User`:

"update.channel": "none"

I theorised that this overrides the default setting (which is `"update.channel": "default"`), even though it isn't visible inside VS Code Portable's settings menu. The `..\VSCodePortable\App\DefaultData` directory is adjacent to the VS Code core package (which is contained inside two separate folders - `..\App\VSCode` and `..\App\VSCode64` - for 32-bit and 64-bit respectively). For this reason, I suspected that any settings contained within the `..\DefaultData` directory override any respective defaults, even if the overrides aren't visible inside VS Code.

Therefore, I updated `..\VSCodePortable\App\DefaultData\code\User\settings.json` to include `"update.channel": "default"`, but that hasn't fixed the problem (i.e. there's still no option to check for updates anywhere, and VS Code Portable still doesn't update automatically).

Has anyone else got any other ideas?
