### ISSUE TITLE
If project folder is subfolder of git repo, coloring of changed files does not update after commit

### ISSUE THREAD

**Issue by agos** [Microsoft/vscode#41477]
- VSCode Version: 1.19.2
- OS Version: OS X 10.13.2

Steps to Reproduce:

1. Open a subfolder of a git repository
2. Modify some files, commit
3. The change decorators in the document panels and in the file tree panel won't go away
4. Doing the same after opening the root of the git repository works as expected

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/3025
