### ISSUE TITLE
SOURCE CONTROL: GIT over 5k files .

### ISSUE THREAD

**Issue by Clickys** [Microsoft/vscode#41474]
- VSCode Version: 1.19.2
- OS Version: win10

Steps to Reproduce:

1. When iam installing vs code , the source control:git it points to C:\Users\My user which for a reason are too many git files ove there and i get this enormous file messages like in picture.  (http://prntscr.com/hz25sj )  Is it possible to fix that ?
2.

**Comment by Clickys** [comment]
One more thing , does anyone know why i get this error when iam trying to debug my js code?  http://prntscr.com/hz2xfx

**Comment by joaomoreno** [comment]
Run `git rev-parse --show-toplevel` to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.

**Comment by SeaOfLight** [comment]
Hi I got same problem, I am on the mac, I dont see .git folder when i run git rev-parse --show-toplevel
how to fix that?

**Comment by keepnode** [comment]
@SeaOfLight when you run `git rev-parse --show-toplevel`  screen will print the path.
like this:`/Users/keepnode`
you can run `cd /Users/keepnode `
`ls -a`
you will find the .git folder.
run`rm -r -f .git`
you will fix that.

**Comment by Clickys** [comment]
ty sir
