### ISSUE TITLE
Extension icon needs more UI love <3

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4147]
Related to #4024

The Extension icon that we currently use in the status bar needs more UI love. IMHO 'extension' is not the first word on top of the user's head when he sees that icon.

We will also make this icon even more prominant in the future since it we will probably add an extension viewlet and then it will be in the activity bar.
So creating this item now to start the thought process if we decide to change it.

ping @joaomoreno 

![screen shot 2016-03-14 at 15 02 00](https://cloud.githubusercontent.com/assets/1926584/13746864/bc38af9e-e9f5-11e5-8da2-107c77ee82e4.png)

**Comment by bgashler1** [comment]
@isidorn thanks for sharing your thoughts on this.  The icon is consistent with the icon in VS for extensions, so we will probably leave it unless we hear from users that it's not clear.  We should definitely keep an eye out for this kind of feedback during the Insiders release when we get the viewlet in the product, and we can respond quickly to that.

While we work out the viewlet ideas, I will decrease the size of this icon to visually blend better with the rest of the icons in the status bar.  That's undoubtedly throwing this icon off balance.

**Comment by Tyriar** [comment]
Can be closed since we have the viewlet now @joaomoreno @bgashler1?

**Comment by joaomoreno** [comment]
Oh, wow!
