### ISSUE TITLE
Red squiggly error line randomly appears on chunk of code, no error shown, sometimes randomly disappears

### ISSUE THREAD

**Issue by mccreeker** [Microsoft/vscode#41476]
- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. just randomly type or paste valid useful code
2. watch red squiggly line randomly appear under valid useful code chunks
3. hover over red line and nothing happens
4. hold Ctrl and hover, or do that and click and nothing happens
5. ignore it then watch it randomly disappear seconds or minutes later

A: I'm unable to see why the red line is appearing.
B: Nothing indicates what it thinks is wrong.
C: I don't know what causes it to randomly disappear.

Edit: I did notice an invalid red line disappears if the file is saved again, but only after a second or two. Other editors I've used auto-scan in real-time even before save.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
What language?

**Comment by mccreeker** [comment]
This is in .php files.

**Comment by roblourens** [comment]
- Can you post an example of a code snippet that causes this to happen? I don't see it.
- Does it happen if you set `"php.validate.enable": false`?

**Comment by mccreeker** [comment]
Sure, when it happens again.
