### ISSUE TITLE
Window splits inside a tab.

### ISSUE THREAD

**Issue by trusktr** [Microsoft/vscode#41486]
Can we have splits similar to Vim (or NeoVim) where a single tab can have multiple "window splits"? I find this workflow much better than tabs-inside-splits. I'd rather have splits-inside-tabs like Vim because then I can group files together in a single tab, and only make one tab visible at a time.

Does this exist?

**Comment by Kroc** [comment]
I assume you mean like MSWord / VB6, where you can split the text-view? I have missed this feature for a loooong time. Notepad++ doesn't have it. Atom doesn't have it, nor does VSCode. I can't remember if TextMate did on the Mac.

This functionality would also be useful for keeping the markdown preview with the content in question.

**Comment by trusktr** [comment]
Note sure about MSWord / VB6, never tried those. Vim's window splits are the best way that I know of to describe the feature.

Here's a similar request for Atom, which gives more of an idea: https://github.com/atom/atom/issues/672

**Comment by trusktr** [comment]
And another one: https://github.com/atom/atom/issues/11349

**Comment by trusktr** [comment]
Basically that Atom feature request is exactly the same request here, for VSCode. It'd be super great for productivity!

**Comment by bpasero** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/36700
