### ISSUE TITLE
TypeScript built-in support plugin problems with relative paths in `baseUrl`

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode#41488]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Go to (or clone) the project 'https://github.com/Microsoft/roosterjs-react'
2. Open the samples content: https://github.com/Microsoft/roosterjs-react/tree/master/sample/script
3. Open `Sample.tsx`

Reproduces without extensions: Yes
The TypeScript support is built-into VSCode

Description:

The `tsproject.json` supports `baseUrl` property and the code is correctly transpiled as the non-relative modules are resolved correctly according to `tsproject.json` settings:

```json
"baseUrl": "../../",
```

The built-in VScode support cannot resolve, instellisense and navigate to `roosterjs-react' package, that should be resolved according to `baseUrl` path:

![image](https://user-images.githubusercontent.com/14539/34847133-a7b3662a-f71a-11e7-8ce5-f7a72c02c5c3.png)

Thanks!

**Comment by mjbvz** [comment]
Seems like a bug in the project.  Here's what I see when I run tsc from the root of the project:

```js
 ./node_modules/.bin/tsc -p sample/script/tsconfig.json
sample/script/sample.tsx(10,8): error TS2307: Cannot find module 'roosterjs-react'.
```
