### ISSUE TITLE
Upgrade to version 1.19.2 breaks terminal.

### ISSUE THREAD

**Issue by mscottx88** [Microsoft/vscode#41481]
- VSCode Version: 1.19.2
- OS Version: Windows 10 

Steps to Reproduce:

1. Set your "terminal.integrated.shell.windows" setting to an 8+3 legacy DOS style path such as "D:/Progra~2/Git/bin/bash.exe"
2. Try to open the terminal.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/20876337/34838429-e905efe8-f6b2-11e7-9e8b-7a66ee22d184.png)

The image above shows what very briefly appears in the terminal which then promptly closes.

EDIT:
Also, verified that none of the following are working after upgrading to 1.19.2:

`"D:\\Program Files\\Git\\bin\\bash.exe"`
`"D:/Program Files/Git/bin/bash.exe"`
`"D:/Progra~2/Git/bin/bash.exe"`

EDIT:
This may or may not be related directly to VS Code, but after uninstalling and reinstalling Git resolves the issue above.  But I can say that the issue only cropped up _after_ upgrading to 1.19.2.

EDIT:
The plot thickens.  I reinstalled, re-upgraded to 1.19.2 then I was able to use the terminal like before.  Cool.  Then I launched `npm run test` and Bullguard antivirus quarantined a `suspicious` file.  Now my terminal is broken again just like the image above.  Going to downgrade to 1.19.1 to see if the problem persists.

EDIT:
After downgrading back to 1.19.1 and reinstalling Git (version is 2.14.3), I am able to run `npm run test` again just like before without Bullguard antivirus ruining everything.

**Comment by Tyriar** [comment]
v1.19.2 definitely has nothing to do with this issue and I recommend going back to it.

For the legacy path part I never expected this to work and we don't intent to explicitly support it. I've heard some cases where anti-virus software will block winpty from doing its thing, the solution is to tell it that it's safe.

**Comment by Tyriar** [comment]
I can now repro using `cat /dev/urandom | tr -dc -- 'A' | head -c 12` under Ubuntu 17.10

**Comment by mscottx88** [comment]
Well im staying at 1.19,1 because 1.19.2 is the first version to interfere with Bullguard.  You may close this issue if you feel it is not related (although it just started happening and does not happen with version 1.19.1).

Cheers!
