### ISSUE TITLE
Values in keyboard UI should be copyable

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41483]
> Get even more frustrated that you can't copy just the Ctrl+Space Command name in Keymap to try to find it in Settings, it instead copies the whole setting block.

From #41158

I should be able to copy the values of cells in the keybindings editor, either just through normal text selection, or a context menu option.

**Comment by jburtondev** [comment]
Hi @roblourens is this issue still up for grabs?

**Comment by shobhitchittora** [comment]
@sandy081 Can this be closed now?

**Comment by sandy081** [comment]
I am still waiting for @mccreeker 's opinion. Will close it then. Thanks for reminder.

**Comment by mccreeker** [comment]
Isn't it closed when it's fixed or addressed? Looks like it got 3 thumbs-up and has been added to keybindings-editor, feature-request, Backlog, and made a 'good first issue'... not sure how you guys work issue flow.

**Comment by sandy081** [comment]
@mccreeker There was a PR that added `Copy Command` action in Keybindings editor. 

I asked for your opinion in the PR [here](https://github.com/Microsoft/vscode/pull/41567#issuecomment-357750574) if this is sufficient. If agreed upon I would close it.

**Comment by iansan5653** [comment]
@sandy081 What's left to fix for this issue?

**Comment by sandy081** [comment]
Nothing.
