### ISSUE TITLE
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"

### ISSUE THREAD

**Issue by BrahimS** [Microsoft/vscode#41489]
- VSCode Version: 1.19.2
- OS Version: 10.13.2

Steps to Reproduce:
Each time i opened the integrated terminal, i got this error message: 
```
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v6.12.3 --silent` to unset it.
```

I've found a solution, which is to: 

1. brew uninstall nvm
2. curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash

It work on Terminal as well as iTerm, but the problem persist on VScode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by davidhunt135** [comment]
I am also having this issue. My PATH variable seems to include the npm path when in terminal but not in the vscode integrated terminal. Setting `"terminal.integrated.shellArgs.osx": []` was my previous solution but now it removes the error and I have no access to nvm and therefore I cannot change my node version

**Comment by Tyriar** [comment]
nvm does not support or recommend the homebrew distribution so installing via the official script is how you should do it. Also this is how I init my nvm in `.bashrc` on a Linux non-login shell http://www.growingwiththeweb.com/2018/01/slow-nvm-init.html

**Comment by BrahimS** [comment]
Hi @Tyriar , Thanks for your response,
I forgot to mention that i'am using oh-my-zsh.

**Comment by davidhunt135** [comment]
Hi @Tyriar 

I uninstalled the brew version before installing nvm. This does not solve my problem, running as a login shell. When running as a non-login shell (which, as you know, vscode isn't by default) I don't get the error but nvm is not recognized at all. It would be preferable to run the terminal in vscode and have it match the behaviour of the non-integrated terminal

**Comment by Tyriar** [comment]
I just wrote a FAQ on the website about the proper fix for this issue: https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md#why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched
