### ISSUE TITLE
NLS - InnoSetup is not localized

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4148]
- VSCode Version: alpha
- OS Version: Win
- Locale: German

Steps to Reproduce:

1. My labtop is set up for German and VS Code appears localized
2. When there is an auto update, I get prompted in German whether I want an update

`->` then the InnoSetup install dialogs show up in English since they are not localized.

**Comment by egamma** [comment]
Assigning to March and flagging as important for discussion.

**Comment by dbaeumer** [comment]
@joaomoreno where is the source for the strings we show in InnoSetup. May be I can have a look how we best pipe them to the translation team. 

@egamma do you remember if button on the dialog where in English or German. If we translate the strings we show then we need a translated version of InnoSetup as well.

**Comment by egamma** [comment]
This is the dialog that I see. However, given that I do not have a full German setup (OS is English and my explorer is in English), we should reproduce this on a Machine that is cleanly configured as German.

![image](https://cloud.githubusercontent.com/assets/172399/13774983/466dd5a2-eaa2-11e5-932b-4ce6356bf2c0.png)

**Comment by egamma** [comment]
Moving to April.

**Comment by aeschli** [comment]
Assigning to @egamma for verification
