### ISSUE TITLE
detect links when registering a file system for a scheme

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#41482]
Today, the editor [supports ftp and http(s)](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/linkComputer.ts#L80) links in link detection. That's fair but when registering a file system for a certain scheme, e.g. ftp, we should also detect those.

**Comment by aeschli** [comment]
Verified with the https://github.com/jrieken/ftp-sample
