### ISSUE TITLE
Cannot edit values in watch window.

### ISSUE THREAD

**Issue by johnb003** [Microsoft/vscode#41485]
Editing "values", not the variable name, only works in the auto watch window, not in the manual watch window.

- VSCode Version: Version 1.19.1 (1.19.1)
- OS Version: OS X 10.12.6

Steps to Reproduce:

1. debug
2. hit a break point
3. put some variable in the watch window
4. attempt to edit, or even select for copy, the value.

Does this issue occur when all extensions are disabled?: Yes/No
I cannot actually use a debugger without extensions....

**Comment by isidorn** [comment]
This works fine in vscode. 
Double click to edit, context menu to copy.

Please file this against the extension you are debugging.
If you still think this is a vscode issue try reproducing in latest vscode insiders https://code.visualstudio.com/insiders/
And I have no clue what is the difference between auto watch and manual watch window
