### ISSUE TITLE
Source Control view: provide the option to "open file" instead of "open changes"

### ISSUE THREAD

**Issue by madjos** [Microsoft/vscode#41480]
- VSCode Version: All
- OS Version: All

Steps to Reproduce:

1. Open the "Source Control" view in VS Code (Ctrl+Shit+G).
2. Click on an item/file that is staged/unstaged.
3. The "working tree" view of the file is displayed - a split view showing the diffs.
4. You need to right click and select "Open file" to just see the file.

Requests:

On step 2, allow me to Ctrl+Click a file to open it (just like Click opens changes).
Provide a setting to toggle which the default is (open file/open changes).

![image](https://user-images.githubusercontent.com/3002635/34838421-dcc40c06-f6b2-11e7-966d-57ab7cdd675d.png)

**Comment by joaomoreno** [comment]
Related to #41137

Also related to the changes around list service and tree service for multi select... @bpasero @isidorn  Which modifier are you using for multi select, and which modifier should I then use for alternative actions?

**Comment by bpasero** [comment]
@joaomoreno current thinking is to use `Cmd/Ctrl` to expand the selection and `Alt` to "Open to Side".

**Comment by isidorn** [comment]
Yup. And I plan to adopt this in debug views / open editors and the FileReusltsNavigation class

**Comment by joaomoreno** [comment]
This is in!
