### ISSUE TITLE
Context menu support missing from Problems panel problems list [MacOS]

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode#41490]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Open a file with source code problems to trigger built-in linters/language support like TypeScript
2. try to select a problem listed in Problems panel using mouse context menu

Reproduces without extensions: Yes

The feature of using context menu for selecting problems (for copy/paste) was reported #13115 (introduced/closed)
It appears that I cannot use context menu in Problems panel - both in regular and insiders release and I failed to find a reference if that feature was removed.
I can still use keyboard shortcut for COPY/PASTE in Problems panel though.

Thanks!

**Comment by sandy081** [comment]
Thanks @peterblazejewicz for finding this. It was broken from bf6ff401a18faf27d0c84d9b4f7c47d8209e3642

Fixed.
