### ISSUE TITLE
Entering a full path in quickopen matches gitignored files, but not search.excluded files

### ISSUE THREAD

**Issue by scottsb** [Microsoft/vscode#41495]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: none
---

It's hard to identify the exact circumstances that trigger this, but starting from some recent version (either 1.18 or 1.19), quick open began consistently missing files that it should clearly match. This seems to happen most particularly in large repositories with many files.

To illustrate here is a screen recording of an obvious case:

![missingfiles](https://user-images.githubusercontent.com/6756989/34853528-3a8a83b6-f702-11e7-8bfd-01e4af49fbe8.gif)

**Comment by bpasero** [comment]
Since I see the label "file results", this seems to be an issue with the RipGrep matching and not with the fuzzy scorer of quick open that is only used for sorting purpose as far as I know.

**Comment by roblourens** [comment]
Are those files covered by a gitignore pattern? It now skips gitignored files by default. You can disable this with `"search.useIgnoreFiles": false` if you prefer.

If that's not it, do you see any pattern to which files it can't find (besides "recently opened" files, which are searched differently)

**Comment by roblourens** [comment]
I do see that - when you enter a full path like that, it matches immediately and bypasses the actual search that's looking at the gitignore file. But this is inconsistent with `search.exclude` - if it's excluded that way, it still won't match if you enter a full path. That seems wrong...

**Comment by chrmarti** [comment]
Absolute paths and paths from a root folder should always match, ignoring the `search.exclude` and `.gitignore` settings. At least that is how we designed it.

**Comment by roblourens** [comment]
Ok. Seems like that doesn't work for .exclude settings anymore, I guess that's the bug.

**Comment by roblourens** [comment]
This should now work consistently for absolute paths but not relative paths, by design.
