### ISSUE TITLE
What is IFileStat.hasChildren needed for?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#41497]
There is [`IFileState.hasChildren`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L416). I believe it is to indicate that a folder has children but those are not aren' loaded yet. I don't think that we actually use this anywhere and this is from a time where empty folder would be rendered different. 

This is expensive to compute for remote scenarios and I'd opt to nuke it unless we surprising actually use it.

**Comment by bpasero** [comment]
@jrieken I removed `hasChildren` as we do not seem to have a use case for it. I think the original purpose was to maybe render folders which are empty but not yet resolved differently in the explorer but I am not seeing this used anymore. Every folder shows up with a expando, even if empty.

**Comment by jrieken** [comment]
Thanks
