### ISSUE TITLE
Explorer shortcut caught when writing the name of the file/folder

### ISSUE THREAD

**Issue by cosmarc** [Microsoft/vscode#41491]
- VSCode Version: 1.19.2
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Set a shortcut for create file/folder like `shift + F`
2. Write a file/folder name that contains `F` (uppercase F)

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
```json
"when": "explorerViewletVisible && filesExplorerFocus && !inputFocus"
```

**Comment by isidorn** [comment]
@usernamehw thanks for answering
@cosmarc use the when clause that @usernamehw pointed out. More about our keybindings can be found here https://code.visualstudio.com/docs/getstarted/keybindings
