### ISSUE TITLE
Quick open exclude settings conflict with .gitignore settings file

### ISSUE THREAD

**Issue by mustiy** [Microsoft/vscode#41494]
- VSCode Version: 1.19.2
- OS Version: Windows 10

Sample dummy folders attached.
[working_example.zip](https://github.com/Microsoft/vscode/files/1624524/working_example.zip)
[not_working_example.zip](https://github.com/Microsoft/vscode/files/1624525/not_working_example.zip)

Steps to Reproduce:
1. My workspace seetings to be able to quick open (Ctrl+P) files in folder node_modules
```
    "files.exclude": {
        "**/node_modules": false
      },
      "search.exclude": {
        "**/node_modules": false
      }
```
2. But it didn't work in my project folder. I can not quick open files in node_modules folder.
3. I thought it should work and created a dummy folder structure and it worked.
4. The difference that i found was the .gitignore file causing this behavior. In .gitignore file this section conflicts with my workspace settings :
```
	# dependencies
	/node_modules

```
Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This is expected, settings cannot override the gitignore file. If you don't want search to use the gitignore file at all, you can disable that feature with `"search.useIgnoreFiles": false`.

**Comment by mustiy** [comment]
I wasn't aware of this setting.

Thanks for your help.
