### ISSUE TITLE
Regex Search All Unrecognized Flag: "!"

### ISSUE THREAD

**Issue by RandomClown0** [Microsoft/vscode#41493]
VSCode 1.19.1  
Windows 10

Steps to Reproduce:

1. In file **Find**, regex find with negative lookahead, *ex:* `input (?:(?!required).)*>`. This will work
2. In left side panel **Search all files**, regex search with the same as above

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
See this note in the search docs: https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

> VS Code does support regular expression searches, however, backreferences, lookaround, and multiline matches are not supported. This is because VS Code depends on the search tool ripgrep, which, while extremely fast, doesn't support these advanced regex features.
