### ISSUE TITLE
Original color theme disappeared when version update.

### ISSUE THREAD

**Issue by ddryo** [Microsoft/vscode#41507]
Please excuse my poor English.

- VSCode Version:1.19.2
- OS Version:Windows 10

Steps to Reproduce:

1. My files of original color theme disappeared from "C:\Program Files\Microsoft VS Code\resources\app\extensions" when version update.

**Comment by usernamehw** [comment]
That's how it works. Embedded extensions change on update.

External extensions stay the same:
`%UserProfile%/.vscode/extensions`  is not rewritten.

**Comment by ddryo** [comment]
Thanks!
