### ISSUE TITLE
command+f and immediately command+v cause vscode about 1~2 seconds.

### ISSUE THREAD

**Issue by kevinwon1985** [Microsoft/vscode#41505]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3

---

Steps to Reproduce:

1.press command+f to call find input
2.immediately press command+v to copy some text
3.and vscode will no response about 1~2 seconds. not everytime but often

Reproduces without extensions:No

**Comment by alexandrudima** [comment]
@kevinwon1985 Do you have a specific example of when vscode hangs? I believe searching for the string you paste is slow. Can you share the exact file you are opening (or a very similar one if you cannot) and the string you are searching for?
