### ISSUE TITLE
[loc]Translate error in CHS. "Close the file in the right".

### ISSUE THREAD

**Issue by Setsuna-Kitahara** [Microsoft/vscode#41508]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vbscript|Dar|1.0.4
python|ms-|0.9.1

---

Steps to Reproduce:

1.Right click file tabs

![image](https://user-images.githubusercontent.com/33174519/34860795-f50cebe6-f79a-11e7-9bd6-22c0003d2616.png)

Reproduces without extensions: Yes
（“关闭到右侧” means that this file will OPEN IN THE RIGHT SIDE.）

**Comment by danyeh** [comment]
@Setsuna-Kitahara, it will be great if you can help to correct directly in Transifex. See https://aka.ms/vscodeloc on the process. Thank you!

**Comment by danyeh** [comment]
I saw it was fixed in Transifex. Close here. Thank you for your feedback!
https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hans/$/131029059?q=close right
