### ISSUE TITLE
Number of GIT pending changes keep increasing by simply opening/closing a file

### ISSUE THREAD

**Issue by ipsusila** [Microsoft/vscode#41509]
- VSCode Version: 1.19.2
- OS Version: Windows 10
- Git Version: 2.15.0

Steps to Reproduce:

1. Open an empty directory, create new file, then save it
2. Initialized git repository in this directory, it will shows the number of pending changes in Source Control menu
3. Close file (1), then open it again. Number of pending changes will increased. Clicking Split editor also increase the number of pending changes.

Screen capture: [https://youtu.be/inn0WXwZ4QI](https://youtu.be/inn0WXwZ4QI)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you reproduce in our [insider release](https://code.visualstudio.com/insiders)?

**Comment by ipsusila** [comment]
Yes, it still happen in `insider release`. For debugging purpose, I wrote a wrapper around `git` command which log `arguments`, `stdout` and `stderr` when executing `git`. Then, the `git.path` parameter in user settings is set to the full path of the wrapper. Below is sample output when opening a directory.

```
EXEC>> git-wrapper.exe --version
  STDOUT: git version 2.15.0

  STDERR: 
------------------------------------------------
EXEC>> git-wrapper.exe rev-parse --show-toplevel
  STDOUT: C:\Work\Projects\golang\src\github.com\ipsusila\tutor\testgit

  STDERR: 
------------------------------------------------
EXEC>> git-wrapper.exe config --get commit.template
  STDOUT: 
  STDERR: 
------------------------------------------------
EXEC>> git-wrapper.exe status -z -u
  STDOUT: ?? main.go 
  STDERR: 
------------------------------------------------
EXEC>> git-wrapper.exe symbolic-ref --short HEAD
  STDOUT: master

  STDERR: 
------------------------------------------------
EXEC>> git-wrapper.exe rev-parse master
  STDOUT: master

  STDERR: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

------------------------------------------------
EXEC>> git-wrapper.exe for-each-ref --format %(refname) %(objectname) --sort -committerdate
  STDOUT: 
  STDERR: 
------------------------------------------------
EXEC>> git-wrapper.exe remote --verbose
  STDOUT: 
  STDERR: 
------------------------------------------------
```

**Comment by joaomoreno** [comment]
Can you reproduce this in other folders in your machine? How are you opening the folder? Using the `File > Open Folder` command, or using `code .` from the command line?

PS: You can always see the git commands that were executed in `Git: Show Git Output`.

**Comment by ipsusila** [comment]
Yes, it was reproducible in other folders. I open the folder using `File > Open Folder`. 
After some more investigation, I think this issue occurs because I'm using `MSYS2 git`, with workaround mentioned in #4651 (Previously, the workaround,  was working).

Currently, after I switched to *Git for Windows*, this issue does not occurs anymore.


> PS: You can always see the git commands that were executed in Git: Show Git Output.

Thank you for the information. I didn't realized that command 👍

**Comment by joaomoreno** [comment]
Good to know. Code only supports Git for Windows currently.
