### ISSUE TITLE
Full-width characters are shifted by rectangle selection

### ISSUE THREAD

**Issue by maccyo12** [Microsoft/vscode#41500]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Enter Full-width characters.
2. Press Shift-Alt And drag.

The position of the mouse cursor is different from the selection position.

![trable](https://user-images.githubusercontent.com/21338006/34856180-06e19218-f787-11e7-9930-3b06aef9561e.gif)

---

英語が苦手なため、日本語でも手順の説明をします。
1. 全角文字を入力します。
2. Shift-Alt を押しながらドラッグします。

マウスカーソルの位置と実際に選択されている文字の位置が異なります。

**Comment by yh1224** [comment]
This issue is also fixed by #44259.

**Comment by alexandrudima** [comment]
Duplicate of #22717
