### ISSUE TITLE
"Select All" button in Find UI for better multi-cursor support

### ISSUE THREAD

**Issue by chriskuech** [Microsoft/vscode#41504]
For a while, I've still felt that VS Code's multi-cursor support isn't as intuitive or convenient as Sublime's.  In analyzing my workflow on Sublime, I think the major difference between support in Sublime and VS Code is that Sublime has a giant button in their CTRL+F UI for "Find All" which selects all instances of the pattern.  I would like a similar button in the CTRL+F UI for VS Code.  You could add "Select" and "Select All" buttons right above the "Replace" and "Replace All" buttons to mimic the current design.

**Comment by rebornix** [comment]
thanks, dup of https://github.com/Microsoft/vscode/issues/20453
