### ISSUE TITLE
Finding “\n” using regular expression is very slow in a file containing a lot of lines

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode#41503]
- VSCode Version: 1.19.2
- OS Version: Windows 7 64-bit

Steps to Reproduce:

1. Create a file with 10000 lines.
2. Type `\n` in the find widget and turn on “Use Regular Expression”.

Does this issue occur when all extensions are disabled?: Yes

Also, searching for `^` and `$` is still fast.

**Comment by alexandrudima** [comment]
On my machine, searching for `\n` in a file with 25k lines is dominated by:
* (40ms) actually finding `\n` 20k times
* (67ms) creating 20k decorations

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/5047891/35105468-09a2ecce-fc6c-11e7-91f1-aa1f4f31af31.png">

I can look into optimizing this specific search, as searching for `\n` is trivial.

**Comment by EFanZh** [comment]
@alexandrudima It seems that this issue only affects VS Codes on Windows. It is fast on my Linux machine.

**Comment by EFanZh** [comment]
@alexandrudima Did you test it on Windows? I couldn’t reproduce it on Linux, so I think this is a platform-specific issue.

**Comment by EFanZh** [comment]
@alexandrudima  I have tested your fix on version 1.20.0-insider (84991c4). Searching for `\n` is fast on Windows now, but searching for `.\n` is still very slow. Still, this problem only appears on Windows.
