### ISSUE TITLE
[Feature request] Make combination "LAlt + LR Arrow" to jump to uppercase letters.

### ISSUE THREAD

**Issue by zero3growlithe** [Microsoft/vscode#41518]
I would like to request a feature found in "Sublime Text" editor, where holding down **Left Alt** key and pressing **Left** or **Right** arrow would allow for more precise cursor jumps where it stops **before** each word splitting character defined in user settings (it stops on right side of the character when jumping left from right side, and stops on left side if jumped right from left side, also jumps over if same direction is pressed again), and **before** any **uppercase** letter (no matter which side the cursor is coming from, it always stops on left side of the uppercase character).

This makes changing longer variable names a lot easier and faster since you don't need to delete the whole name when you need to change only one part of that name.

Example from Sublime Text:
https://i.imgur.com/cVeDXo3.gifv

**Comment by Gruntfuggly** [comment]
There is an extension which does this:
https://marketplace.visualstudio.com/items?itemName=maptz.camelcasenavigation

**Comment by zero3growlithe** [comment]
Thank you very much! I kept searching for it but at no avail, then I'm closing this issue :)
