### ISSUE TITLE
Emmet: "Wrap with Abbreviation" should wrap the complete tag element

### ISSUE THREAD

**Issue by theGivingTree** [Microsoft/vscode#41516]
- VSCode Version: 1.19.1
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Put a cursor on opening div tag. (start, end or middle of the line):
```
<div>
  foo
</div>
```
2. Execute "Wrap with Abbreviation"

3. Only opening div tag, `<div>` is wrapped, not the entire `<div>` node.
This is not the same output compared to https://docs.emmet.io/actions/wrap-with-abbreviation/

+ Additional Note
The command works fine with: `<div>foo</div>` (single line node)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Looks like when there is a selection, only the selected text should be wrapped.
When there is no selection, the current node should be wrapped.

PRs are welcome to fix this.
The place to add the fix is https://github.com/Microsoft/vscode/blob/1.19.2/extensions/emmet/src/abbreviationActions.ts#L41

**Comment by pfongkye** [comment]
Hi @ramya-rao-a I opened PR #41602 ready for review.

**Comment by ramya-rao-a** [comment]
Thanks @pfongkye!
