### ISSUE TITLE
Show project name along with file and workspace name in title

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#41510]
![image](https://user-images.githubusercontent.com/3254987/34861760-94572840-f71b-11e7-8939-9b07ab21fd31.png)

It would be nice to also show the name of the project folder here.
e.g. my workspace has several folders added, the one containing the currently open file is `satisfier`.
It would be nice to show `spy.spec.ts -- satisfier -- komondor (Workspace)`

**Comment by bpasero** [comment]
@unional you can configure this from the `window.title` setting by adding `${folderName}`

**Comment by unional** [comment]
Thanks, but that doesn't work well when opening project. You will get: `spy.spec.ts -- satisfier -- satisfier`

And logic inside `${ ... }` is not supported, e.g: `${folderName !== rootName ? folderName : ''}`

**Comment by adam-p** [comment]
I have the same or a similar problem. I want this:
```
filename.ext -- path/in/workspace -- workspacename
```

I think this should do it:
```
"window.title": "${activeEditorShort}${separator}${folderName}${separator}${rootName}"
```

But all that gives me is:
```
filename.ext -- workspacename -- workspacename
```

Seems broken?
