### ISSUE TITLE
Closing window that was created with `-w` quits code in OS X

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4151]
Related to #4006

OS X

1. Quit Code
2. `code-alpha -w`
3. <kbd>Cmd W</kbd> to close the window

Code quits altogether, when it should still be running.

**Comment by bpasero** [comment]
Tough. We behave like ST now, I explicitly checked because I wondered too...

**Comment by bpasero** [comment]
You didnt think it through.
