### ISSUE TITLE
shell script wrong syntax color 

### ISSUE THREAD

**Issue by eromoe** [Microsoft/vscode#41517]
- VSCode Version: 1.19.1
- OS Version: win7

This is fine:
![image](https://user-images.githubusercontent.com/3938751/34864832-0f7683fa-f7b1-11e7-9fad-38607d300557.png)

But : 

![image](https://user-images.githubusercontent.com/3938751/34864816-0919c30a-f7b1-11e7-8df0-41f197b4bf49.png)

You see? The last `{` .

test code : 
```
function setup_dircolors(){
    echo "####################################"
    echo "set dircolors"

    if [ ! -d ~/.dir_colors ]; then
        git clone https://github.com/seebi/dircolors-solarized ~/.dir_colors
    fi

    dircolorsdb=\$HOME/.dir_colors/dircolors.256dark

    if grep -q 'dircolors' ~/.zshrc ; then
        sed -i "s%dircolors .*%dircolors $dircolorsdb"`"%" ~/.zshrc
    else
        echo 'eval `dircolors '"$dircolorsdb"'`' >> ~/.zshrc
    fi
}
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#99
