### ISSUE TITLE
Compare local file with source control in right click context menu

### ISSUE THREAD

**Issue by victorivens05** [Microsoft/vscode#41529]
I couldn't find this suggestion elsewhere, so here goes.

VS Code now have a extremely helpful feature to show, in the explorer pane, what is modified from Git (in yellow) and what's new (in green). This helps in big project to rapidly identify what files one is working.

Although for modified files, if I need to check differences from Git (sometimes I simply forget what changes were made) I have to move the Source Control Pane and find that specific file in order to diff.

It would be helpful if an option to diff with source control was added to the right click context menu.

**Comment by m0llux** [comment]
Working on it as we speak.

**Comment by apfohl** [comment]
As @ysengrimm and I started working on that issue, we discovered that you already have an "Open Changes" button in the upper right corner (editor title menu bar). This is also easier to access than having this action inside a sub-menu.

![button](https://user-images.githubusercontent.com/480983/35174147-8a97b00a-fd6e-11e7-8254-d992c12218df.png)

If this is what you are looking for, I would suggest closing this issue.

**Comment by victorivens05** [comment]
That's exactly what I meant. I will close the issue, but the fact that I couldn't find it by myself, and even you guys couldn't point it before you started working on the issue, shows that the position of the button doesn't provide a great UX, but that's just an opinion.

Thanks.
