### ISSUE TITLE
List: more advanced commands for navigation

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#41527]
Extracted from @Tyriar comment in https://github.com/Microsoft/vscode/issues/1023

- <kbd>ctrl</kbd>+<kbd>&uarr;</kbd>: Move the focus up without selecting the item
- <kbd>ctrl</kbd>+<kbd>&darr;</kbd>: Move the focus down without selecting the item
- <kbd>ctrl</kbd>+<kbd>space</kbd>: Add/remove the focused item from the selection

**Comment by usernamehw** [comment]
<kbd>Ctrl</kbd>+<kbd>a</kbd>: Select all items in folder. If all items already selected - select all in outer scope

**Comment by usernamehw** [comment]
I don't understand how <kbd>ctrl</kbd>+<kbd>↑</kbd> is different from <kbd>↑</kbd>

**Comment by bpasero** [comment]
I would stay away from having <kbd>Ctrl</kbd>+<kbd>a</kbd> select all in the explorer, people are very used to that keybinding selecting all in the editor, even if the explorer has focus and I see not a lot of value in selecting all of the explorer typically.

We currently do not support cut command in the explorer.

The difference between <kbd>ctrl</kbd>+<kbd>↑</kbd> and <kbd>↑</kbd> is that the latter will stop the multi selection whereas the former keeps it stable I think so that you can jump over an item and select a different one.

**Comment by stephenfriedman** [comment]
Still not clear what the multi-selection command is when running VS code on a Mac.

**Comment by usernamehw** [comment]
I think my previous comments weren't clear enough. 

<kbd>Ctrl</kbd>+<kbd>a</kbd> should select all folders in current scope (not always everything in file tree)

 I understand how <kbd>Ctrl</kbd>+<kbd>↑</kbd> **SHOULD** be different from <kbd>↑</kbd>, but <kbd>↑</kbd> is already not cancelling item selections (compared to Atom).

**Comment by joaomoreno** [comment]
Some of these things are already implemented. Marking the rest as out of scope.
