### ISSUE TITLE
Getting error ''Extension host terminated unexpectedly."

### ISSUE THREAD

**Issue by akshath4u** [Microsoft/vscode#41522]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: MacOs High Sierra
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
autofilename|Jer|0.1.3
Angular2|UVB|0.4.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|7.2.0
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
terminal|for|0.0.10
node-debug2|ms-|1.19.0
typescript-hero|rbb|1.8.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
vscode-add-angular2-files|seb|2.0.1
guides|spy|0.9.1
Align|ste|0.2.0
code-spell-checker|str|1.6.2
vscode-import-cost|wix|2.6.0

(1 theme extensions excluded)

---

Steps to Reproduce:
-Whenever restart the window.

Reproduces without extensions: Yes
<img width="1089" alt="screen shot 2018-01-12 at 1 17 40 pm" src="https://user-images.githubusercontent.com/9428527/34868407-af9af300-f7a9-11e7-89cf-99c19bb04f08.png">

**Comment by Tyriar** [comment]
> Reproduces without extensions: Yes

@akshath4u did you check without extensions by running `code --disable-extensions`?
