### ISSUE TITLE
Wrong behavior on multiple cursor 

### ISSUE THREAD

**Issue by fascox** [Microsoft/vscode#41524]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
code-settings-sync|Sha|2.8.7
cobol|bit|1.7.6
code-runner|for|0.8.7
ruby-linter|hoo|1.0.0
Untabify|ili|0.0.2
ruby-rubocop|mis|0.5.0
Ruby|reb|0.15.0
vscode-icons|rob|7.19.0
vim|vsc|0.10.9

(3 theme extensions excluded)

---

Steps to Reproduce:

1. add multiple cursors on first column with shift-alt-cmd + (up or down)  
2. when window scroll down or up  to add cursor on line above/below takes to much key repetition and editor start to flashes
3. have to wait while all key repetition are consumed.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
I could not reproduce:

![kapture 2018-01-18 at 10 05 00](https://user-images.githubusercontent.com/5047891/35089698-02d5e3da-fc38-11e7-801b-ae5e668476f4.gif)

Are there more specific steps?

**Comment by fascox** [comment]
I've been able to identify the problem. It seems linked to “Vim emulation” plugin.
Can you verify too?

VSCodeVIM - Vim emulation for Visual Studio Code

--
Fabio Scognamiglio
CEO & Founder of altotouch
Software & Systems Engineer

Mobile:  +39 347.33.13.496
Skype:  fasco.x
Twitter: @fascox

**Comment by alexandrudima** [comment]
@fascox Please open an issue against https://github.com/VSCodeVim/Vim
