### ISSUE TITLE
中文乱码。找不出原因

### ISSUE THREAD

**Issue by cverymuch** [Microsoft/vscode#41523]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
format-indent|Kas|1.3.0
code-settings-sync|Sha|2.8.7
project-manager|ale|0.23.1
githistory|don|0.2.3
gitlens|eam|7.2.0
git-project-manager|fel|1.4.0
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
php-symbols|lin|2.1.0
Go|luk|0.6.73
prettify-json|moh|0.0.3
cpptools|ms-|0.14.5
vscode-proto3|zxh|0.1.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by SpadeRoy** [comment]
+1

**Comment by ohko** [comment]
+1 此问题我也遇到了，也是在"formatOnSave"时产生乱码，前两天“goreturns”提示更新，使用"go get -u"更新了相关包，应该是相关包有更新产生了此问题。
之前的版本一直运行正常。

**Comment by SpadeRoy** [comment]
i think the problems is the 'goreturns' or 'goimports'

**Comment by SpadeRoy** [comment]
restart the Go extension can fix it. @ohko

**Comment by ohko** [comment]
@SpadeRoy Thank you , but i restart the osx, the problem has always existed.

**Comment by roblourens** [comment]
It sounds like this is a problem with the Go extension, please file an issue on the extension's repo.
