### ISSUE TITLE
Typescript intellisense not working when tsconfig.json extends another one

### ISSUE THREAD

**Issue by petrkoutnycz** [Microsoft/vscode#41532]
- VSCode Version: 1.19.1
- OS Version: Windows 10 (OS Build 14393)

Steps to Reproduce:

1. in project, for example have /folder/tsconfig.json present in a project
2. from /tsconfig.json (the root one) extend previous config via "extends" clause
3. intellisense is not working

Does this issue occur when all extensions are disabled?: Yes

This issue seemed to be solved in https://github.com/Microsoft/vscode/issues/31067, but I am facing it again.

**Comment by mjbvz** [comment]
Please provide a small example project or at least describe the project structure and paste up the tsconfigs

**Comment by dicarlo2** [comment]
- VSCode Version: 1.19.2
- OS Version: macOS 10.13.2
/tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": "./packages",
    "target": "esnext",
    "module": "commonjs",
    "declaration": true,
    "experimentalDecorators": true,
    "lib": [
      "es2017",
      "es2017.object"
    ],
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "paths": {
      "@neo-one/*": [
        "./neo-one-*/src"
      ]
    },
    "pretty": true,
    "typeRoots": [
      "@types",
      "./@types"
    ]
  }
}
```
/packages/neo-one-smart-contract-test262/tsconfig.json
```
{
  "extends": "../../tsconfig.json"
}
```

`tsc` in the root folder works fine. VSCode does not recognize any non-relative module imports, including built-in node modules.

**Comment by petrkoutnycz** [comment]
Okay, I will. Thank you.

**Comment by mjbvz** [comment]
Closing as not actionable without more information
