### ISSUE TITLE
Render error in MacOS with nvidia cards

### ISSUE THREAD

**Issue by sekkit** [Microsoft/vscode#41539]
- VSCode Version: all
- OS Version: OS X 10.12, 10.13

Steps to Reproduce:

1. Type in code
2. sometimes the popup menu is rendering wrong content.
3. close the menu, the bug is temporarily gone. but it occurs repeatedly.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@sekkit can you share a screenshot of what you see when the menu is wrong?
