### ISSUE TITLE
Cant right click in the terminal window to copy text

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/vscode#41531]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
markdown-mermaid|bie|0.1.1
jsrefactor|cms|2.11.4
vscode-npm-script|eg2|0.3.3
scriptcsRunner|fil|0.1.0
task-master|ian|0.1.39
csharpextensions|jch|1.3.0
python|ms-|0.9.1
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
typescript-javascript-grammar|ms-|0.0.26
vs-keybindings|ms-|0.1.7
team|ms-|1.122.0
color-highlight|nau|2.3.0
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7

---

Steps to Reproduce:

1. Have typescript project
2. Build it, get compilation error
3. highlight TS##### error code in terminal window by click+dragging mouse
4. right click highlight to open context menu

Expected: Context menu opens with copy/paste
Actual: text is deselected.

**Comment by Tyriar** [comment]
On windows right click copies when there is a selection and paste when not, just like cmd.exe. You want to set `terminal.integrated.rightClickCopyPaste` to false in your settings to override the default.

**Comment by StingyJack** [comment]
Will setting it to false give a context menu? Windows seems to do permit  right click copy/paste sometimes and requires the Mark/paste others.

**Comment by Tyriar** [comment]
Setting it to false should give a context menu.
