### ISSUE TITLE
Tab size not being respected

### ISSUE THREAD

**Issue by mccreeker** [Microsoft/vscode#41542]
- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open a .php file and hit the Tab key.
2. Notice it indents by 2 characters (while showing the tab arrow).
3. Go to Settings and notice `"editor.tabSize": 4,`, `"editor.insertSpaces": true,` and `"editor.detectIndentation": true,`.
4. Change the latter two to false in User Settings. Also try changing tabSize to 4 there as well.
5. Save the file, close it, close the editor, open both back up again, and notice nothing has changed and the same problem happens on any file even with new typed or pasted tabs no matter what even if it's pasted from another source.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@mccreeker Those are indeed the 3 settings that influence what pressing <kbd>Tab</kbd> will do:
```js
  // When opening a file, `editor.tabSize` and `editor.insertSpaces` will be detected 
  // based on the file contents.
  "editor.detectIndentation": true,

  // Insert spaces when pressing Tab. This setting is overridden based on the file 
  // contents when `editor.detectIndentation` is on.
  "editor.insertSpaces": true,

  // The number of spaces a tab is equal to. This setting is overridden based on the 
  // file contents when `editor.detectIndentation` is on.
  "editor.tabSize": 4,
```

So, if you use:
```js
  "editor.detectIndentation": false,
  "editor.insertSpaces": false,
  "editor.tabSize": 4,
```

All files will be opened with those settings. This will be confirmed in the status bar:
<img width="89" alt="image" src="https://user-images.githubusercontent.com/5047891/35089169-6b22de18-fc36-11e7-8862-a65daac1642e.png">

Here are some reasons why things might be not working for you:
1. You have installed an extension that uses VS Code API to tweak those settings at runtime. e.g. `editorconfig` extension. Try with disabling all extensions.
2. You have installed an extension that reimplements <kbd>Tab</kbd>. Try with disabling all extensions.
3. You have workspace settings; you open a folder and the folder has a `.vscode/settings.json` file where the user settings are overwritten.
4. You have modified your keybindings for <kbd>Tab</kbd> that it does something else than the default. Check your `keybindings.json` file.

**Comment by mccreeker** [comment]
So I checked that Spaces area at the bottom and noticed it said 2, clicked on it and changed it there, then did a 2nd review of all my settings and saw that `"editor.tabSize": 2,` was in Workspace Settings, which wasn't being respected before when I wanted to use that (for some reason, I'm not sure what I missed there), so I deleted it since I just want to use 4 now, restarted, and everything's working fine now. Thanks.
