### ISSUE TITLE
Keybindings - Show Conflict - label is confusing

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#41541]
The Show Conflicts action made me expect that this action filters or groups the key bindings which have conflicts. However, the action really does a find for the same key binding that is currently selected. For this reason I suggest to rename the action to ´Find same keybinding´.

**Comment by ramya-rao-a** [comment]
@sandy081 Is this still meant for the January milestone? If not, can you move it to February milestone?

**Comment by sandy081** [comment]
It's just a label change, I would like to push it in this milestone.

**Comment by sandy081** [comment]
I am calling this action `Show Same Keybindings` as it shows all entries with same keybindings. Any changes/improvements are welcome.
