### ISSUE TITLE
Guidance for editing settings is not localized

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4154]
See 'Place your settings...'

![image](https://cloud.githubusercontent.com/assets/172399/13747291/e246f68a-e9f7-11e5-9ecd-ba90833fd06c.png)

**Comment by bpasero** [comment]
This is because the file was already created with your english locale, the string itself is NLSed: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/actions/openSettings.ts#L138
