### ISSUE TITLE
Ubuntu code.desktop Icon=code to Icon=vscode

### ISSUE THREAD

**Issue by xxRockOnxx** [Microsoft/vscode#41548]
I always change `/usr/share/applications/code.desktop` every time I install a new version.

I know this is a minor issue but it's been for a while already.

I'm using Ubuntu GNOME if that matters/

**Comment by Tyriar** [comment]
@xxRockOnxx why do you change it?

**Comment by xxRockOnxx** [comment]
@Tyriar because it does not use vscode's icon

Using `Icon=code`

<img src="https://i.imgsafe.org/ae/ae58faa032.png">

Using `Icon=vscode`

<img src="https://i.imgsafe.org/ae/ae58fa68da.png" />

**Comment by Tyriar** [comment]
That's a custom icon. If you don't touch anything it works fine under Ubuntu Gnome 17.10.
