### ISSUE TITLE
Autocomplete / intellisense should not complete entry when typing open paren character

### ISSUE THREAD

**Issue by ajsharp** [Microsoft/vscode#41554]
- VSCode Version: 1.19.2 490ef761b76b3f3b3832eff7a588aac891e5fe80
- OS Version: 10.13.2

Steps to Reproduce:

1. Start typing a method name that partially matches other methods/properties that have been loaded into intellisense
2. Type an open paren `(` character.
3. The wrong method is autocompleted.

Does this issue occur when all extensions are disabled?: Yes

Here's a video of the issue: https://www.useloom.com/share/809fb9a728ad4a04ad7c0b8ce8d29433. 

This issue is occurring on a front-end react javascript project/file, but I'm guessing it will happen anywhere there is a partial intellisense match.

What's happening here is that I'm trying to type `this.socket.on('event', function() {})`, but when I type the `(` character, it autocompletes to `onclose`, which is the first item in the intellisense list. I haven't typed enter or tab, I've just typed the open paren character, which I would assume would close out the intellisense list and not select the first item.

**Comment by mjbvz** [comment]
We treat `(` as an "accept completion" character for suggestion methods in javascript and typescript. You can disable this by setting `"editor.acceptSuggestionOnCommitCharacter": false` or cancelling out of the suggestion UI before hitting `(`
