### ISSUE TITLE
rpm package is missing icon in CentOS installer

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4155]
- VSCode Version: 0.10.12-alpha
- OS Version: CentOS

See attached screenshot

![capture](https://cloud.githubusercontent.com/assets/1931590/13747374/39bbc99a-e9f8-11e5-84a0-1b9daacf41f6.png)

**Comment by Tyriar** [comment]
Tried adding `Icon: <icon>.xpm` to the spec file as per http://www.rpm.org/max-rpm/s1-rpm-inside-tags.html but it didn't seem to show the icon in Fedora or CentOS' "Software Installer". I also looked through some other applications rpm files and they didn't seem to have the Icon tag.

**Comment by Tyriar** [comment]
Added the icon to the rpm didn't seem to fix it, not going to invest more time into this.
