### ISSUE TITLE
Coloring of multiline arguments function

### ISSUE THREAD

**Issue by iddan** [Microsoft/vscode#41562]
- VSCode Version: 1.19.2
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Write a simple function - see coloring
2. Write a function with multiline arguments - see coloring

Does this issue occur when all extensions are disabled?: Yes

Because of the line break `interview` is not highlighted in blue

<img width="285" alt="screen shot 2018-01-08 at 22 07 08" src="https://user-images.githubusercontent.com/12671072/34690064-588e6614-f4c0-11e7-8005-34b02131a243.png">

Because of the parentheses `async` is highlighted in blue instead of `interview`

<img width="624" alt="screen shot 2018-01-08 at 22 04 12" src="https://user-images.githubusercontent.com/12671072/34689951-fe0f3e84-f4bf-11e7-810b-4eb54944a953.png">

This issue occurs on various of color themes I tested.

**Comment by mjbvz** [comment]
Please share source text along with the screenshots

**Comment by iddan** [comment]
```javascript
export const interview = (
   fabricatedCase : FabricatedCase
) : Promise<InterviewTest> => {
```

```javascript
export const interview = async (
   fabricatedCase : FabricatedCase
) : Promise<InterviewTest> => {
   const res = await fetch(API_URL + '/interviews', {
       method: 'POST',
       headers: new Headers({
           'Content-Type': 'application/json',
       }),
       body: JSON.stringify(fabricatedTest),
   });
   const interviewTest = await res.json();
   return interviewTest;
};
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#558
