### ISSUE TITLE
${configurationName} variable

### ISSUE THREAD

**Issue by witM** [Microsoft/vscode#41566]
Microsoft, please do support for _variable that holds current configuration name selected from cpp_property.json_ file for Visual Studio and Visual Code available in tasks  This for example be: **${configurationName}**. This is very needed and I wonder why you didn't do that (maybe did?) Do that should be simple update so please to make this.

**Comment by witM** [comment]
This should work like any others 'built-in' macros

**Comment by aeschli** [comment]
@witM Where would this variable be used?

**Comment by witM** [comment]
I want to pass this to my task configuration as a **command line argumen**t. See this: https://sourceforge.net/projects/smartbuildertool/
Instead write many configuration tasks I could write one. And general this seems to be natural like ${workspaceRoot} variable so please for some update for that.

**Comment by dbaeumer** [comment]
@witM to which value would `${configurationName}` resolve?

**Comment by witM** [comment]
It will be use in* task.json* file. This would be very practical because
for build the project *we could use this as a command line argument with
many configurations setup with external build tool* like compilers and so
on. For example project configuration name in VsCode will correspond to the
build configuration in build tool. It's very flexible if you don't use
MSBuild tool right? This is the case, using own external tool to build.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by witM** [comment]
Please see this: https://sourceforge.net/projects/smartbuildertool

**Comment by witM** [comment]
Resolve...to the name of current selected configuration in VsCode
(cpp_properties.json) while start build the project

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
