### ISSUE TITLE
Add folder name to terminal

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#41563]
VSCode: 1.19.2

In workspace project, when opening a new terminal, it asks you which folder/project to open the terminal for.
But then the terminals only have names like `1: bash`, `2: bash`...
I would be nicer to add the folder/project name to it. e.g: `1: bash - projA`, `2: bash -moduleB`, etc.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/29816
