### ISSUE TITLE
Feature: Opening Vsc on a different desktop should create a new instance

### ISSUE THREAD

**Issue by CEbbinghaus** [Microsoft/vscode#41564]
I use separate desktops for different projects that I'm working on, so when I want to start a new instance of visual studio code on a new Desktop it just tabs me back to a desktop with VSC open.

It would improve QOL if opening Visual studio code on a new desktop would create a new instance of VSC on that Desktop

**Comment by bpasero** [comment]
You can start "`code --user-data-dir <folder>`" to force a new instance.
