### ISSUE TITLE
sometimes files just disappear it's  kinda scary

### ISSUE THREAD

**Issue by kadamharish** [Microsoft/vscode#41568]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please add more details...

**Comment by kadamharish** [comment]
sometimes folder structure changes automatically while just clicking on
it.. or while expanding the folder, sometimes the file disappears not
physically but visually then again I have to click on Explorer to get
everything normal.

**Comment by bpasero** [comment]
@kadamharish can you share a video or screen cast when this happens?
