### ISSUE TITLE
Path incorrectly copied to tasks.json

### ISSUE THREAD

**Issue by drazen64** [Microsoft/vscode#41575]
- VSCode Version: 1.19.2
- OS Version: WIndows 10 Enterprise, v1709, build 16299.192

Steps to Reproduce:

1. Create new project `dotnet new xunit --name WebServer.Test`
2. Go to project folder and add reference to the existing project
 `dotnet add reference ..\Webserver\Webserver.csproj`
This adds following lines to the csproj file:
```
<ItemGroup>
    <ProjectReference Include="..\Webserver\Webserver.csproj" />
</ItemGroup>
```

3. Start VS Code and click "Yes" when it warns that required assets are missing.
4. Path to the referenced project in tasks.json is missing `../` at the beginning 
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "Webserver/Webserver.csproj"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
```

Does this issue occur when all extensions are disabled?:  VS Code does not offer to create tasks.json

**Comment by dbaeumer** [comment]
@drazen64 this is a problem with the Omnisharp extension.

**Comment by dbaeumer** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1962
