### ISSUE TITLE
Touchpad scroll jumps (Surface Pro Type Cover)

### ISSUE THREAD

**Issue by karray** [Microsoft/vscode#41576]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-cudacpp|kri|0.1.1
Angular-BeastCode|Mik|5.1.19
python|ms-|0.9.1
cpptools|ms-|0.14.5
csharp|ms-|1.13.1

---

Steps to Reproduce:

1. Open any file
2. Scroll with touchpad (Surface Pro Type Cover)

Reproduces without extensions: Yes

**Comment by vasilescur** [comment]
I've found a workaround: Try restoring the window (un-maximize), then maximize it again.

**Comment by bpasero** [comment]
#13612
