### ISSUE TITLE
Changing workspace configuration file does not update explorer in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41571]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (ca023a700f35212071dfe9544272719cbbf80e4c, 2018-01-12T06:08:12.310Z)</li>
	<li>OS Version: Darwin x64 17.3.0</li>
	<li><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.5
close-all|ben|1.0.2
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.22
vsc-travis-ci-status|fel|1.1.0
ayu|tea|0.12.0
vscode-open-in-github|ziy|1.3.1

(13 theme extensions excluded)

</details></li>
</ul>

---

Steps to Reproduce:

1. open a saved multi root workspace with 3 folders
2. open the workspace config file
3. remove 2 using multi select in explorer from context menu
4. bring back the 2 removed root folders by typing into the workspace config file

=> the folders are not restored

Works fine if removing from the file and restoring from the file.

**Comment by ramya-rao-a** [comment]
@sandy081 I reverted the fix as it was breaking tests in Windows

**Comment by sandy081** [comment]
@ramya-rao-a  Sorry for that. I thought there were not any platform specific changes in the fix, hence ran tests only on Mac. 

Fixed it now.
