### ISSUE TITLE
TextEditorEdit.delete() across multiple lines does not shrink the selection when word wraps

### ISSUE THREAD

**Issue by Jasonlhy** [Microsoft/vscode#41573]
- VSCode Version: 1.19
- OS Version: I have tested on Windows 10, Window 7 and macOS 10.12

Steps to Reproduce:

1. Set the editor with word wrap
```json
"editor.wordWrapColumn": 100,
"editor.wordWrap": "wordWrapColumn",
```

2. Write an extension with a testing function like this,

It aims to delete the first selection range.

```ts
export function smartBackspace(): Thenable<Boolean> {
    const editor = window.activeTextEditor;
    const returned = editor.edit(editorBuilder => {
        editorBuilder.delete(new Range(editor.selection.start, editor.selection.end));
    });

    return returned;
}

function registerSmartBackspace() {
    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = commands.registerCommand('extension.smartBackspace', smartBackspace);

    return disposable;
}
````

3. Run the extension and paste the testing sample on a new page

```js
Authorization: 'Bearer YnzgPsmz_avev-9lx47q8TlNHnONvREoftEwtU14lJ9x-Z3R1Ut6pv3DYOGnIojS93uU_DiKyfu0Dez2lbEJVy_ftxydQw-ZEzqZID5V7rBCIGKPaTn5I1sraktowXKT6Z4Kg8sdTXvavV6Q5jwlgMZ-VB-t9TzI7-eKLcgOkGx750bCZU7fyAQIrCD73ceZRRJjDdP3aScj-ZmlcmAVVA',
```

4. Execute the testing function and the selection still is here

![word_wrap](https://user-images.githubusercontent.com/1687930/34907702-96c01fb2-f8bd-11e7-9839-30dab915595e.gif)

However, this problem doesn't appear when word wrap is turned off.
![no_word_wrap](https://user-images.githubusercontent.com/1687930/34907719-ca3d9e3c-f8bd-11e7-86e4-99070105ac2a.gif)

Does this issue occur when all extensions are disabled?: No, the original delete button works fine.

I also tested it in vscode 1.12 on Ubuntu, this problem doesn't appear.

**Comment by alexandrudima** [comment]
Great find, thank you!
