### ISSUE TITLE
cd to the directory of currently opened file in terminal

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#41572]
- VSCode Version: 1.19.2
- OS Version: linux arch

Request for enchancement:
Add to the right click menu of the terminal entry "change current working directory to the directory where the file is located". This should ensure that there is nothing entered in the terminal and type "cd DIRECTORY" and hit enter

**Comment by Tyriar** [comment]
Currently we defer this behavior to extensions https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here
