### ISSUE TITLE
Allow invocation of codelens actions via keyboard

### ISSUE THREAD

**Issue by savpek** [microsoft/vscode#41579]
It would be nice to invoke current line codelens actions without moving hands of from keyboard to mouse. 

It could be done via context ctrl+. where codelens actions are added or from ctrl+p, or even new shortcut key which opens context menu which contains only codelens actions.

They are sometimes available if extension implements them that way that they are added to menus/context etc but this probably could be handled more generic way in vscode itself?

**Comment by maricn** [comment]
Any plans on handling this? I am surprised there's no more activity for this feature.

**Comment by GustavoKatel** [comment]
Hi! I just opened a PR with the ability to trigger codelenses with the keyboard. Hope you find this helpful as I do :D

I appreciate any suggestions and comments from people coming to this issue
