### ISSUE TITLE
Incorrect syntax highlight using Typescript templates

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/vscode#41583]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299

---

Steps to Reproduce:

1. Write down this code. The syntax highlight for the class property is incorrect. It should be the same as the variable declaration.

 ![](https://puu.sh/z0UNR.png)
2.
```
let myFunc = function<T,U>(txt:string,num:number){}

class MyClass {
  myProp = myFunc<number, () => void>("syntax highlight is incorrect", 1);
}

let myProp = myFunc<number, () => void>("syntax highlight is correct here", 1);
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#559
