### ISSUE TITLE
Not able to debug HTML code with JavaScript in Visual Studio Code

### ISSUE THREAD

**Issue by rajast** [Microsoft/vscode#41585]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
vscode-standard-format|che|0.0.12
jsrefactor|cms|2.11.4
xml|Dot|1.9.2
vscode-html-css|ecm|0.2.0
beautify|Hoo|1.1.1
rest-client|hum|0.16.2
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
debugger-for-chrome|msj|4.0.0

**Issue:** The debugger opens localhost:8080 and gives error that the site cannot be opened. Please let me know how this can be resolved.

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by auchenberg** [comment]
Please give the README in https://github.com/Microsoft/vscode-chrome-debug a look. You probably need to update the `url` property in your `launch.json` to either the path of the HTML file you want to load in Chrome, or the URL of the local web server you have running.
