### ISSUE TITLE
autoFindInSelection does not work in replace mode

### ISSUE THREAD

**Issue by mikolino** [Microsoft/vscode#41584]
The setting editor.find.autoFindInSelection doesn't work as it should when entering replace mode. One work around is to press Ctrl+F Ctrl+H.

It was reported casually in the thread [27083](https://github.com/Microsoft/vscode/issues/27083#issuecomment-313899395) but I couldn't find an Issue or acknowledgement from developers.

- VSCode Version: 1.19.2
- OS Version: Windows 8.1

Steps to Reproduce:

1. Select text
2. Press Ctrl+H

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Already fixed ;)

**Comment by zerratar** [comment]
This is not fixed, can still reproduce the same error in.
VSCode Version 1.21.1
OS Version: Windows 10 Pro, 1709, build 16299.309

**Comment by dkent600** [comment]
Doesn't work at all when only a single line is selected.
