### ISSUE TITLE
immortal file type error in explorer view and render window

### ISSUE THREAD

**Issue by MikeSummit** [Microsoft/vscode#41580]
- VSCode Version: Code 1.18.1 ( 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
vscode-color|ans|0.4.5
cform|aws|0.0.10
jsontotype|dan|0.0.3
aws-cloudformation-yaml|Dan|0.2.0
angular2-snippets|dan|1.0.16
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
terraform-autocomplete|erd|0.0.8
json-tools|eri|1.0.2
gc-excelviewer|Gra|2.0.16
beautify|Hoo|1.1.1
rest-client|hum|0.16.2
output-colorizer|IBM|0.1.2
lambda-snippets|log|0.2.0
json-to-ts|Mar|1.5.4
terraform|mau|0.0.20
Angular-BeastCode|Mik|5.1.19
terraform-snippets|min|1.10.5
python|ms-|0.9.1
vscode-json-transform|oct|0.1.2
cf-templates|pra|0.0.4
typescript-hero|rbb|1.8.0
indenticator|Sir|0.4.2
json2yaml|tux|0.2.0

---
A file permanently acts like its original extension, even if the extension is changed or the file is deleted and a new file with the same name and different extension is added.

**Steps to Reproduce:**

1. create a file with a known extension, for example myfile.**txt**
2. change the extension, for example myfile.**js**
3. the file continues to be treated like a **txt** file and is never treated like a **js** file.
4. delete the file and add a new file with the same name and an extension different from the original, for example myfile.**js**.
5. the file continues to be treated like a **txt** file and is never treated like a **js** file.
6. multiple other sequences of create, change, delete, add all permanently act like the original extension and never take on characteristics of the current extension.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Can you explain what this means: the file continues to be treated like a txt file and is never treated like a js file.?

**Comment by MikeSummit** [comment]
The apparent error behavior stopped after the last update.

Here is what it **was** doing:

If you create a TXT file, it gets an Icon in the VSCode file explorer that represents TXT, and it gets no code syntax coloring. After changing the extension to .JS. the file would keep the TXT icon and have no syntax coloring. But after the latest update it now changes icon and coloring as expected.
