### ISSUE TITLE
Debug UI is not localized

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4158]
![image](https://cloud.githubusercontent.com/assets/172399/13747425/8287a09a-e9f8-11e5-83de-39643bb93d44.png)

**Comment by isidorn** [comment]
I call [nls.localize](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugViewlet.ts#L71) on all the titles of my panes.
Forwarding to @dbaeumer

**Comment by dbaeumer** [comment]
@egamma this is know. I haven't received translations yet.

**Comment by dbaeumer** [comment]
@isidorn are the strings for VARIABLES, ... come from the server? All strings in VSCode should be localized. Only the strings in vscode-node-debug aren't

**Comment by dbaeumer** [comment]
@isidorn I can't find any reference to 'VARIABLES' in our codebase. Could you point me to the location where the string is 'inserted' into the user interface

**Comment by isidorn** [comment]
There is a pointer in my comment above, just click on nls.localize

**Comment by dbaeumer** [comment]
Very strange. If I build locally it is translated.

![capture](https://cloud.githubusercontent.com/assets/1931590/13750758/1ed700ea-ea07-11e5-959f-e0cef497d185.png)

**Comment by dbaeumer** [comment]
Fixed. A tool once created a global gitignore for me and put a rule in saying to ignore everything that has in debug in its path :-(.

**Comment by isidorn** [comment]
HALTEPUNKTE :heart:
