### ISSUE TITLE
Getting timeout error 'Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a target that matches:...'

### ISSUE THREAD

**Issue by rajast** [Microsoft/vscode#41599]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
vscode-standard-format|che|0.0.12
jsrefactor|cms|2.11.4
xml|Dot|1.9.2
vscode-html-css|ecm|0.2.0
beautify|Hoo|1.1.1
rest-client|hum|0.16.2
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
debugger-for-chrome|msj|4.0.0

issue: When debugging and running my HTML, JavaScript I',m getting error 'Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a target that matches:', the application closes. Please let me know how to resolve it.

Here is launch.json:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      
        {
           "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "C:/Projects/PhoneField/PhoneFieldHTML.html"
            
        }
       
    ]
}

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please give the README in https://github.com/Microsoft/vscode-chrome-debug a look. You probably need to update the url property in your launch.json to either the path of the HTML file you want to load in Chrome, or the URL of the local web server you have running.

**Comment by ArthurMenezes** [comment]
I have a problem similar to this, but with attach. my settings:
`
{
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "url": "http://repo.intra.snap.com.br/",
            "userDataDir": false,
            "console": "internalConsole",
            "trace": "verbose",
            "sourceMaps" : true ,
        },
`

url is an internal url for network, the web server is also on the network.
I'm getting the following error: Can not connect to runtime process, timeout after 10000 ms - (reason: Can not find a target that matches: http://repo.intra.snap.com.br/. Available pages: [.. ..URLS]
