### ISSUE TITLE
function popup bug report

### ISSUE THREAD

**Issue by simple-is-best** [Microsoft/vscode#41591]
- VSCode Version: 1.19.1(1.19.1)
- OS Version:macOS High Sierra 10.13.2(17C88)

Steps to Reproduce:

key stroke "print(" -> function popup start
key stroke ")" -> function popup close, but...
key stoke "alt+enter" -> function popup not close

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
> key stoke "alt+enter" -> function popup not close

why should it? did you configure that keybinding for that? Also in what language does this happen? How it works is that a language/extension starts with a certain character and we keep asking it/showing its information as long as it keeps returning a result.

**Comment by simple-is-best** [comment]
sorry my english. i'm korean. i use `Python` with `Python Extension` and `Sublime keybinding`.
If i press `(` vscode automatically make `)` too.
So when I input arguments and want move next line, without pressing `) + Enter`, i'm just press `Command+Enter`
I aleady work next line, but function popup keep going.

**reference screenshot image**
[https://imgur.com/a5ffQcV](https://imgur.com/a5ffQcV)

**Comment by jrieken** [comment]
Ok, please file this issue then against the `Phyton Extension` because that determines when to close the pop up.
