### ISSUE TITLE
When condition doesn't work in keybindings json

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#41594]
- VSCode Version: 1.19.2
- OS Version: arch linux

Steps to Reproduce:

1. Insert the following settings:
```
   {
        "key": "ctrl+e",
        "command": "workbench.action.quickOpen",
        "when": "!terminalFocus"
    }
```
2. Focus terminal and press Ctrl + E
3. quickOpen appears!

PS Ctrl+E is used by bash (means go to the end of the line)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
You want to *unbind* the default, try this:

```js
    {
        "key": "ctrl+e",
        "command": "-workbench.action.quickOpen",
        "when": "terminalFocus"
    }
```

If that doesn't work try unbinding globally and rebinding:

```js
    {
        "key": "ctrl+e",
        "command": "-workbench.action.quickOpen"
    },
    {
        "key": "ctrl+e",
        "command": "workbench.action.quickOpen",
        "when": "!terminalFocus"
    }
```

**Comment by Yanpas** [comment]
Thanks, only second option helped!
What about making this default configuration?

**Comment by Tyriar** [comment]
The rationale behind the current behavior is that many people rely on ctrl+e for quick open and he terminal was added later. Also end should work on most platforms to go to the end of the line.
