### ISSUE TITLE
No syntax highlighting on single-line XML

### ISSUE THREAD

**Issue by HTD** [Microsoft/vscode#41593]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (ca023a700f35212071dfe9544272719cbbf80e4c, 2018-01-12T05:14:50.541Z)</li>
	<li>OS Version: Windows_NT x64 10.0.16299</li>
	<li><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.1
vscode-eslint|dba|1.4.3
xml|Dot|1.9.2
tslint|eg2|1.0.24
python|ms-|0.9.1
csharp|ms-|1.13.1
team|ms-|1.122.0

</details></li>
</ul>

---

Steps to Reproduce:

1. Open file C:\Windows\Performance\WinSAT\DataStore\*Formal.Assessment (Initial).WinSAT.xml
2. Notice that XML syntax is not highlighted since this XML is all in one line, however it is still a perfectly valid XML and as such should be highlighted.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
@HTD Can you paste that line to this issue?

**Comment by typeoneerror** [comment]
@aeschli same issue here. a .js file with an array that is 11566 characters on one line (can't share the data, unfortunately private). I can share that syntax highlighting stops at column 1000 which seems significant.

**Comment by aeschli** [comment]
Oh, now remember. We have a limit on the line length (20'000 characters). Lines that are longer will not be colourized. That's necessary for performance reasons.

**Comment by typeoneerror** [comment]
@aeschli just to confirm, I have a 11,566 character file and if I delete everything after character 1000, highlighting starts working again. Should my file not be syntax highlighted at < 20K? Looks like the limit is actually 1000? 🧐

**Comment by aeschli** [comment]
The code says 20'000, and its also what I see:
![image](https://user-images.githubusercontent.com/6461412/35095041-71bc7aac-fc47-11e7-8728-d80e84b950c3.png)
![image](https://user-images.githubusercontent.com/6461412/35095056-7bc472ca-fc47-11e7-95ec-ae9231dd27cd.png)

**Comment by aeschli** [comment]
Please paste your example to a gist or in this issue, maybe it's something else.

**Comment by typeoneerror** [comment]
@aeschli below is 1022 characters.

![screenshot 2018-01-18 12 36 20](https://user-images.githubusercontent.com/218700/35120248-5d66292c-fc4c-11e7-8505-8769330509c9.png)

Deleting to 1000 and syntax shows up again:

![screenshot 2018-01-18 12 36 44](https://user-images.githubusercontent.com/218700/35120263-6b6e5d0a-fc4c-11e7-86b1-e82749a79bf0.png)

1022 data:

```
/* eslint-disable*/ export const hpData = [{"name":"TESTING","type":"ABC","values":[10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000]},{"name":"TESTING","type":"ABC","values":[null,null,null,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000]},{"name":"TESTING","type":"ABC","values":[null,null,null,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000]},{"name":"TESTING","type":"ABC","values":[null,null,null,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000]},{"name":"TESTING","type":"ABC","values":[null,null,null,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000]}]; 
```

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
vscode-eslint|dba|1.4.4
flow-for-vscode|flo|0.7.3
vscode-language-babel|mgm|0.0.11
debugger-for-chrome|msj|4.0.0
Ruby|reb|0.15.0
vscode-icons|rob|7.19.0
language-stylus|sys|1.8.0
vim|vsc|0.10.11
vscode-todo-highlight|way|0.5.11
---

Could be issue with Babel Javascript syntax highlighter?
