### ISSUE TITLE
Extra ` character when mapping "alt+`" to "workbench.action.terminal.toggleTerminal"

### ISSUE THREAD

**Issue by oquirozm** [Microsoft/vscode#41590]
- VSCode Version: 1.19.2
- OS Version: MacOS High Sierra 10.13.2

Steps to Reproduce:

1. Map "alt+`" to "workbench.action.terminal.toggleTerminal" in keybindings.json.
2. Type "alt+`" once and the terminal will come up. Press it again and it will go away but leaving an extra character in the file in focus.

**Comment by alexandrudima** [comment]
Let's continue tracking in #41024, where the same occurs for `alt+i`.
