### ISSUE TITLE
Maybe `-w` should not spawn Code as a child, when it is not running yet

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4159]
Related to #4006 

OS X

This is more of a discussion item mixed with a few issues. This also **only** applies to when Code is not already running.

There are many repercussions to spawning Code as a direct child of the cli code and we should maybe stay away from it and always spawn as an independent process.

![image](https://cloud.githubusercontent.com/assets/22350/13747501/ce582760-e9f8-11e5-84fa-cf796edd3b09.png)

Here are a few examples why:

#### Move to background

1. Launch `code-alpha -w`
2. Hit <kbd>Ctrl Z</kbd> in the Terminal, which will send that process to the background
3. Switch to Code's window, it will appear frozen, you can't do anything, spinny comes along
4. Go back to terminal, run `fg` to bring Code back to life

#### `SIGINT`

1. Launch `code-alpha -w`
2. Type a few characters to get a dirty buffer
3. Switch back to the Terminal, hit <kbd>Ctrl C</kbd>
4. Switch back to Code and hit `Cancel` when it asks you about the dirty files
5. You immediately get an error from the shared process. What happened was that that `SIGINT` caused by <kbd>Ctrl C</kbd> propagated to all our process structure and killed most, except the renderer and its children. After the `Cancel`, the renderer and children became orphan processes.

**Comment by bpasero** [comment]
Moving to @Tyriar who does the spawn from cli.ts

**Comment by bpasero** [comment]
Well, let me keep it here for me to discuss with Mr. Moreno.

**Comment by bpasero** [comment]
I think we are good for GA atm.

**Comment by Tyriar** [comment]
Note the only reason I removed `detached: true` was to prevent the cli from terminating. It looks like that's now handled by the `exit` variable.

**Comment by bpasero** [comment]
Pushed a change to always detach. This should fix the issues reported by Joao. Needs verification on all platforms.
