### ISSUE TITLE
Virtual Drive confuses git client

### ISSUE THREAD

**Issue by Orillion360** [Microsoft/vscode#41598]
Visual Studio Code's git gets confused when you use a virtual drive (subst) on Windows. It will find multiple repositories that are all the same. Does not appear to confuse the git command line client.

- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro 1709 build 16299.192

Steps to Reproduce:

1. Use the windows subst command to create a virtual drive
2. Open visual studio code in the virtual drive or in the original location

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/3833088/34918882-be6d5564-f95a-11e7-865e-3503c5b51dd8.png)

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?
