### ISSUE TITLE
wrong macro expansion for $dir in windows ! (includes backward slash)

### ISSUE THREAD

**Issue by nateshmbhat** [Microsoft/vscode#41606]
## Environment data
VS Code version:  1.19.1
Python Extension version: 3.5.2
Python Version:  3.5
OS and version:   Windows 8.1

## Actual behavior
in settings.json , when we use `$dir ` in any settings , it takes backward slash as separator and becoz of that "path1\path2\path3\"  , since it includes a backward slash at end of path , that end quotes " gets ignored and it throws me a file not found error . 

## Expected  behavior
`$dir` should resolve to `"path1\\path2\\path3\\"`  or `"path1/path2/path3/"` (with forward slashes)

## Steps to reproduce:  
Put this in settings.json

```
"code-runner.executorMap": {
 "cpp": "cd $dir "
} 
```

**Comment by aeschli** [comment]
You need to file this against https://github.com/formulahendry/vscode-code-runner
