### ISSUE TITLE
Invisible underscore in directory name within Terminal

### ISSUE THREAD

**Issue by KHZ-INTL** [Microsoft/vscode#41607]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (ca023a700f35212071dfe9544272719cbbf80e4c, 2018-01-12T06:17:00.820Z)</li>
	<li>OS Version: Linux x64 4.9.76-1-lts</li>
	<li><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python-docs|Muk|0.8.3
python|ms-|0.9.1
autodocstring|njp|0.1.3

</details></li>
</ul>

---

Steps to Reproduce:

1. In terminal within the Code-insiders, change Directory to one that contains underscore/s in the name
in the screenshot the foldername should be "FTA_Schedules" but it is "FTA Schedules"

Notes:
- Listing directory with "ls" command correctly shows folder name with underscore.

![underscores-missing-in-terminal](https://user-images.githubusercontent.com/9879109/34928635-e5ef2fd6-fa0e-11e7-9dc1-2ff851078c74.png)

Reproduces without extensions: Yes/No

**Comment by tambnice** [comment]
No

**Comment by KHZ-INTL** [comment]
@tambnice 
What do you mean by No ?

**Comment by fedorg** [comment]
I'm having this problem as well. Fortunately, it goes away once you change the zoom level.
My current understanding is this problem might have something to do with display scaling and/or resolution, and it also might be Linux-specific.
The underscores in the terminal are always visible on my old 1366*768 15'' machine but on a more modern 1920*1080 15'' screen they disappear at certain zoom levels.

**Comment by KHZ-INTL** [comment]
@fedorg 
Indeed your suggestion, zooming out  (View > Zoom out) worked out. However, the text size is abit small for my taste. 
I have a  monitor, roughly 1680 x 1200.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901

**Comment by KHZ-INTL** [comment]
@Tyriar, it maybe a rendering issue but I don't think it's a duplicate?

**Comment by Tyriar** [comment]
@KHZ-INTL what makes you say that? The underlying issue is that the rows get clipped horizontally, hiding the underscore under certain conditions or other characters that expand beyond the regular cell bounds.

**Comment by KHZ-INTL** [comment]
Right, I read the post again. This issue post is a duplicate. I didn't quite understood until you explained. Thanks.
