### ISSUE TITLE
Debug output doesn't appear in debug console without "outputCapture": "std"

### ISSUE THREAD

**Issue by johnshew** [Microsoft/vscode#41600]
Version info:
- VSCode: 1.19.2
- OS: Windows 10 1709
- Node: 8.9.3
- Debug: 3.1.0  (from `npm install debug`)

To reproduce: create a simple node app that generates debug output using the debug package,  Then:
1. Run the app with launch,json that does not have `"outputCapture": "std"`.  No debug output.
2. Run the app with launch.json that has `"outputCapture": "std"`.  Debug output visible.

It appears this issue occurs because debug defaults to sending output directly to process.stderr and the vscode debug console doesn't seem to pick it up unless `"outputCapture": "std"` is present.  

Is this expected behavior from vscode?  

Or perhaps my launch.json is misconfigured:

```javascript
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "node",
            "request": "attach",
            "name": "Attach",
            "port": 9229
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha Tests",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": [
                "-u",
                "tdd",
                "--timeout",
                "999999",
                "--colors",
                "${workspaceFolder}/lib/test"
            ],
            "env": {
                "DEBUG": "*,-mocha:*"
            },
            "outputCapture": "std",
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\lib\\server.js"
        },        
    ]
}
```

**Comment by roblourens** [comment]
> It appears this issue occurs because debug defaults to sending output directly to process.stderr and the vscode debug console doesn't seem to pick it up unless "outputCapture": "std" is present.

This is exactly the case that the outputCapture setting was added to support - many logging packages write directly to the output stream, which isn't sent over Node's debug socket. So that flag switches the debugger to listen to stdout/err instead of log messages over the debug socket.

**Comment by johnshew** [comment]
Given the popularity of Debug package in the node community, why not adjust your node.js template auto-generate "outputCapture" : "std"?

I guess more broadly why isn't this just the default all the time?

**Comment by roblourens** [comment]
Getting output through the debug socket gives you rich output, not just text. For example if I log an object, I can dynamically inspect that object in the console. This is what people expect coming from tools like chrome devtools.
