### ISSUE TITLE
Lines getting split in certain file type

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#41603]
In a handlebars .hbs file, when I save it a long line gets split into 2 lines probably because it exceeds some line width. Which setting controls this? I tried `	"html.format.wrapLineLength": 0,` because there's HTML formatting in that file but that didn't work. In my JS files they don't do this because I disabled it, but in this file format it is splitting the line.

**Comment by aeschli** [comment]
You probably have `"editor.formatOnSave": true` enabled.
To not have any line breaking, set the value to a very high limit: e.g. `"html.format.wrapLineLength": 999999`

**Comment by rightaway** [comment]
The comment to that setting says `  // Maximum amount of characters per line (0 = disable).` but when I set it to 0 it doesn't work. Does it work for you?
