### ISSUE TITLE
Extension errors should be aggregated

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4160]
Related to #4024

Steps to Reproduce:

1. Install an extension, create errors in it's `package.json`
2. Click on the extensions widget in the status bar, notice you get multiple error notifications
3. It would be cool if all the error notifications are aggreagted per extension, that way the user would not get scared with a bunch of errors in his face

![screen shot 2016-03-14 at 15 29 05](https://cloud.githubusercontent.com/assets/1926584/13747689/c0107dd2-e9f9-11e5-87ed-1372be934810.png)

**Comment by joaomoreno** [comment]
They will move to the output...
