### ISSUE TITLE
Auto-closing backticks in Python

### ISSUE THREAD

**Issue by i5ar** [Microsoft/vscode#41615]
Backticks are used in Python docstrings (e.g. [Google Style Python Docstrings](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)).
It will be nice to have backticks behave like double/single quotes in Python (like in JavaScript they do already).

**Comment by aeschli** [comment]
@DonJayamanne Assigning to you. Can you take this one?
Looks at the example, backticks are used inside strings, but not in code.
I'd still suggest to add
`{ "open": "`", "close": "'", "": ["comment"] }`
to the autoClosingPairs

**Comment by i5ar** [comment]
More info:
Backticks in Python are often used inside [docstrings](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings): The text inside the backticks gets converted into the HTML `code` tag by third-party software to generate documentation. Google advises using double backticks (common in reStructuredText), Django contributors often use single backticks (like in markdown).

My point of view:
Considering backticks are still part of Python 2 syntax can be a good excuse to add them.
Although not the best solution for the future since docstrings are just text and `txt` files don't have this auto-closing behavior in VS Code.
The best would be an option in the settings but until 2020 (Python 2 will be supported until 2020) I can accept backticks are still part of the language.

**Comment by DonJayamanne** [comment]
@aeschli I'm on the fence for this. Personally i don't see any problem in adding this functionality. 
It feels something similar to using backticks in markdown. Though it can be used in code as well. 
On a side note, the use of backticks in code was dropped in Python 3 (https://docs.python.org/3.1/whatsnew/3.0.html#removed-syntax).

@brettcannon what're your thoughts on this?

**Comment by brettcannon** [comment]
I can't think of any reason why anyone would want a single backtick, so I don't see anything wrong with auto-closing them.

**Comment by chrmarti** [comment]
@aeschli I think you changed to wrong language.

**Comment by i5ar** [comment]
@aeschli also, may I ask you to add them to *surrounding pairs* as well, please.

**Comment by aeschli** [comment]
Sorry for that, thanks @chrmarti for spotting this.

**Comment by joaomoreno** [comment]
Verified in dev and by code review.
