### ISSUE TITLE
Code is not restoring to full screen on mac

### ISSUE THREAD

**Issue by FernandoMiguel** [Microsoft/vscode#41616]
- VSCode Version:
$ code --version
1.20.0-insider
b36655544f413f67aec02d64ce619d165749b957
x64
    "window.restoreWindows": "all",
    "window.restoreFullscreen": true,
- OS Version:
MacOS High Sierra 10.13.3 Beta (17D34a)

Steps to Reproduce:
1. Open Code.
2. Switch windows to Full Screen mode
3. Close or Restart Code
4. windows are restored to window mode on open

was working fine a few builds ago.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
It is a setting: `"window.restoreFullscreen": true`

**Comment by FernandoMiguel** [comment]
hi @bpasero 
has you can see from my post above, window.restoreFullscreen is set in my preferences, and it is not working.
please reopen this issue

**Comment by bpasero** [comment]
@FernandoMiguel are you referring to the fact that only one of the windows is restoring fullscreen and the others are not?

**Comment by FernandoMiguel** [comment]
@bpasero none restores to full screen, no matter if I have just one or multiple Code windows in different workspaces.

**Comment by bpasero** [comment]
@FernandoMiguel yeah, sounds a lot like https://github.com/Microsoft/vscode/issues/32247

**Comment by FernandoMiguel** [comment]
maybe, but mine is not restoring even if I just have a single window
