### ISSUE TITLE
Add Emmet's "Update" and "Remove" Tag features in non HTML files

### ISSUE THREAD

**Issue by ryanditjia** [microsoft/vscode#41618]
- VSCode Version: 1.19.2
- OS Version: macOS High Sierra 10.13.2

Steps to Reproduce:

1. Use Flow's syntax inside a .js file:
`class App extends Component<Props> { ... rest of React here}`

2. Emmet's "Update" and "Remove" Tag features won’t work anywhere below that line.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
The Update/Remove tag currently works only for pure html files
