### ISSUE TITLE
New "pipe into code" feature should open in Untitled file

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#41614]
Love the new "pipe into code" feature!

The scenario I was messing around with was like...
```
curl https://some-cool-raw-script.com | code -
```

actual example that downloads a [PowerShell script from gist](https://gist.github.com/tylerl0706/a1f2e0c9f0219051a06fa5c409307846):
```
curl https://gist.githubusercontent.com/tylerl0706/a1f2e0c9f0219051a06fa5c409307846/raw/a7199adc2a3150d886518361feb8ec27958417dc/TweetScript.psm1 | code-insiders -
```

After I run that, I'd like to be able to easily change the language to the language of the script. This is possible, but some debuggers are not able to handle the fact that you have `.txt` as an extension but the language set in code to whatever language... for example, a PowerShell script with `.txt` as the file extension but PowerShell set as the language.

However, what I have noticed is that debuggers often support Untitled files that have the language set in code.

If the "pipe into code" piped the text into an Untitled file, rather than a `.txt` debuggers would probably be happier 😃 

Again, thanks for the awesome feature!

**Comment by tylerl0706** [comment]
@bpasero thanks for reopening!

**Comment by bpasero** [comment]
@TylerLeonhardt should we close this as out of scope given language detection runs now?

**Comment by TylerLeonhardt** [comment]
Yeah I guess so. Considering it would take a fair amount of work and the experience as it is is close enough to this feature.

The only thing I can think of that would still benefit from this is if a  language extension supports untitled files but not extensionless files for things.

Example: the PowerShell debug adapter has the ability to completely debug an untitled file (something I specifically added to the PowerShell debug adapter back in the day) but given the language's history being on Windows, one cannot debug a non-Untitled script that does not have a PowerShell extension (`ps1`,`psm1`). 

That could be fixed theoretically, but I just wanted to call that out that there are possible differences and this feature would still be worthwhile.
