### ISSUE TITLE
Error Installing Azure Data Lake binary dependencies

### ISSUE THREAD

**Issue by maikgroenewegen** [Microsoft/vscode#41610]
- VSCode Version: 1.19.2
- OS Version: MacOS 10.13.2

Steps to Reproduce:

1. Installed the Azure Data Lake extension
2. Execute ADL: Login brings up binary dependencies messages
3: Output shows:

[Debug] VSCode MachineId:b168731534c31d7701d568f1cff5de68fad64fa92654d8c11a6c06be6af911dd
[Info] Installing compilehost-0.0.6.tar.gz to /Users/<MYUSER>/.vscode/extensions/usqlextpublisher.usql-vscode-ext-0.2.8/compilehost
[Info] Attempting to download https://go.microsoft.com/fwlink/?linkid=862386
[Info] Installing reference-0.0.1.tar.gz to /Users/<MYUSER>/.vscode/extensions/usqlextpublisher.usql-vscode-ext-0.2.8/reference
[Info] Attempting to download https://go.microsoft.com/fwlink/?linkid=834604
[Info] Installing scopecompiler-0.0.8-mono.tar.gz to /Users/<MYUSER>/.vscode/extensions/usqlextpublisher.usql-vscode-ext-0.2.8/scopecompiler-mono
[Info] Attempting to download https://go.microsoft.com/fwlink/?linkid=859945
[Info] Installing DataLakeConsoleAppForDotNet-0.0.3-mono.tar.gz to /Users/<MYUSER>/.vscode/extensions/usqlextpublisher.usql-vscode-ext-0.2.8/DataLakeConsoleAppForDotNet-mono
[Info] Attempting to download https://go.microsoft.com/fwlink/?linkid=865110

4. Install does not continue
5. Developer Tools shows:
[msazurermtools.azurerm-vscode-tools]Cannot read property 'indexOf' of null
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4056
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4056 TypeError: Cannot read property 'indexOf' of null
	at Function.CorrelationContextManager.patchError.AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
This issue was moved to Microsoft/AzureDatalakeToolsForVSCode#10
