### ISSUE TITLE
vsc 看不到一些类型的字符

### ISSUE THREAD

**Issue by daijinru** [Microsoft/vscode#41611]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cssrem|cip|0.0.3
vscode-eslint|dba|1.4.3
python|ms-|0.9.1
sublime-keybindings|ms-|3.0.3
vetur|oct|0.11.5

(1 theme extensions excluded)

---

Steps to Reproduce:

1. 从 .sketch 复制一段文本到 vsc,导致编译器崩溃。
2.粘贴这一段文本到 notepad，看到该字符含有其它 vsc 无法查看的字符。已知两个编辑器都是 utf-8

Reproduces without extensions: Yes/No

Google translate:

1. Copying a piece of text from .sketch to vsc causes the compiler to crash.
2. Paste this paragraph of text to notepad, I saw that the character contains other vsc can not see the characters. Both editors are known to be utf-8

**Comment by aeschli** [comment]
@daijinru Can you add a link to such a file?
