### ISSUE TITLE
Column select mode spans rectangle in unexpected way

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4161]
testing #4092

OS: Linux

I would expect that "Shift+Alt+mouse drag" spans a rectangle between the mouse down and the mouse up location. But this is not what I observe. Instead the rectangle spans from the previous caret location to the mouse up location. This is unexpected and less useful.

(in Sublime Alt-Cmd spans a rectangle between the mouse down and the mouse up location).

**Comment by alexandrudima** [comment]
This is consistent with Visual Studio.

1. Pressing shift and alt before mousedown, uses the primary cursor selection start as the anchor.
2. Doing mousedown and then shift and alt uses the mousedown position as the anchor.

IMHO, this allows both use-cases, while the Sublime way does not allow case 1.
