### ISSUE TITLE
Enable Closing of InputBox via API (support ctrl+[ to close the vscodevim command line)

### ISSUE THREAD

**Issue by hkleynhans** [Microsoft/vscode#41617]
Using vscode 1.18.1 on macOS High Sierra.

When entering vim command mode using :, you cannot exit it using ctrl+[, you have to use the esc key.

In order to fix https://github.com/VSCodeVim/Vim/issues/2220 the API has to support closing of the InputBox through the API.

**Comment by jrieken** [comment]
The API allows passing of a `CancellationToken` (which you can create with the `CancellationTokenSource`). Once cancelled the input box will close.

**Comment by hkleynhans** [comment]
Thanks for the info!

**Comment by jpoon** [comment]
@jrieken we'd like to trigger that `CancellationToken` from the extension. However, from my initial testing, I can't seem to bind to any input from that InputBox. I didn't see any relevant context here either: https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

Particularly, VIM users would like to be able to close that InputBox using `Ctrl`+`[`
