### ISSUE TITLE
Incorrect behaviour of Explorer tab on "New file" right-click folder action

### ISSUE THREAD

**Issue by eJuke** [Microsoft/vscode#41626]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
debugger-for-chrome|msj|4.0.0

---

Steps to Reproduce:

1. Create a project with some inner folders
2. Right-click on inner folder -> New file
3. Scroll down without any input to field
4. Try to collapse/expand folder

Expected: correct expanding/collapse
Actual: some files missed or moved down on Explorer

Video example: https://www.screencast.com/t/uMHk7fzC0qWO

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
fyi @joaomoreno
