### ISSUE TITLE
Terminal panel automatically maximized

### ISSUE THREAD

**Issue by H1KHC** [Microsoft/vscode#41625]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.5

Description:
The terminal panel automatically maximized when I resize the window.

I think this was caused by the method of maximizing this panel. Maybe it was like this:
```c
if(window.height - panel.height > MAX_PANEL_HEIGHT)
    enablePanelMaximize();
else /*...*/;
```

And when I resize the window to be less high, the condition is reached because I only changed the window's height, didn't change the panel's.

Although this is not a serious problem, I still feel annoyed as I should use my mouse to click the button each time I do so.

Hope you can fix this 😄

---

Steps to Reproduce:

1. Open an empty window, no folder open needed
2. Open the powershell terminal, and make it longer(x-axis)
3. Put the window on a top corner, either left-top or right-top(You can drag it there using mouse or using keyboard Win+Right,Win+Up)
By now, you can see the maximize button has changed

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
I acknowledge this bug and we accpet PRs that fix this

Easy repro steps
1. open panel
2. reduce size of whole vscode window such that the panel thinks it is maximized
3. increase size of hwole vscode window, panel remains maximized and occupies most of space

**Comment by shobhitchittora** [comment]
@isidorn I'd like to take this. Will drop a PR. 😇

**Comment by shobhitchittora** [comment]
@isidorn Just to clarify and document the issue, I'm uploading a gif.

![untitled](https://user-images.githubusercontent.com/4711855/34978992-0ac7f6aa-fac6-11e7-9d29-e56bbd421f38.gif)

**Comment by isidorn** [comment]
@shobhitchittora yes that is exactly the issue, thanks for providing a gif

**Comment by shobhitchittora** [comment]
@isidorn I just opened a PR. Please check.
