### ISSUE TITLE
Time is not localized in last update check message

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4162]
![image](https://cloud.githubusercontent.com/assets/172399/13747738/0adb32b2-e9fa-11e5-9201-138276f8ca0e.png)

**Comment by joaomoreno** [comment]
@egamma [We seem to do the right thing here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/menus.ts#L653). Have you seen dates properly localised anywhere in our product?

**Comment by egamma** [comment]
@joaomoreno I haven't seen dates properly localized anywhere else in our product, but I think the hope was that we do not display dates :smile: 

The string is properly externalized but dates also needs to be localized using toLocaleDateString().

**Comment by joaomoreno** [comment]
But that is exactly what I do, as per the snippet in my last comment. Apparently it doesn't work?

**Comment by egamma** [comment]
@joaomoreno on my machine the OS was not German, on a German windows machine the date formatted properly. However, it would not work when the user uses the --locale argument or the local setting support.

So the plan is that @dbaeumer provides an API to find the current locale.

**Comment by dbaeumer** [comment]
I added the API to vs/base/common/platform

However I am not convinced that we should pass in the ui language we chose to this call. I for example have my system configured to use English with German date formatting. If we would pass in the locale/language I would see an English date format in that case.

@egamma I am closing this and opt to not tweak this by passing in the locale/language.

**Comment by egamma** [comment]
@dbaeumer agreed. I'm assigning to you for verification. I don't trust my mixed locale setup on my machine.

**Comment by dbaeumer** [comment]
I will reopen this. I have my settings so that I use Swiss date and number format. However the time in the menu is still showing with PM also the rest of the UI doesn't. I am not sure if this is correctly honored by the JS API. Need to test this under node.

**Comment by dbaeumer** [comment]
@egamma I opt to revisit this in April.

**Comment by egamma** [comment]
:+1:

**Comment by dbaeumer** [comment]
Still seeing this. Running code directly in node however prints the correct statement. See screenshot.
![capture](https://cloud.githubusercontent.com/assets/1931590/14672688/a3cbf346-06f9-11e6-8718-885ac11ef00d.png)

Assigning to @joaomoreno to further investigate.

**Comment by joaomoreno** [comment]
I use `toLocaleTimeString()`, as discussed earlier. If you open dev tools and try to run that method on a Date, what do you get?

**Comment by dbaeumer** [comment]
![capture](https://cloud.githubusercontent.com/assets/1931590/14675054/6187cede-0707-11e6-84f4-24101c510afb.png)

**Comment by dbaeumer** [comment]
Might be an electron issue. I tested it with older node version as well and they behave correctly.

**Comment by joaomoreno** [comment]
cc @bpasero

**Comment by bpasero** [comment]
@joaomoreno go ahead and verify :)

**Comment by joaomoreno** [comment]
@dbaeumer I could not figure out how to launch Electron on a language other than the system's. How to do it?

**Comment by joaomoreno** [comment]
Moving to backlog. ping @dbaeumer

**Comment by dbaeumer** [comment]
@joaomoreno don't know either. When I tested it for node I change the system locale. I think you need to do the same for electron.

**Comment by joaomoreno** [comment]
I'm sorry but something is wrong here... I changed my system's language to German and I get:

![image](https://cloud.githubusercontent.com/assets/22350/15579118/80110b72-2363-11e6-8d7f-6411412da23a.png)

Do you guys still see this? cc @egamma @dbaeumer

**Comment by dbaeumer** [comment]
I now see this on WIndows/German locale which seems ok. No am/pm. May be the latest electron update makes a difference.

![capture](https://cloud.githubusercontent.com/assets/1931590/15604284/c8f70ac0-23ff-11e6-8e31-1eb1640e6e24.png)

**Comment by weinand** [comment]
On OS X with English as the primary language but Swiss regional settings I get US format for time:

![2016-05-27 16-22-54](https://cloud.githubusercontent.com/assets/1898161/15610832/9efa8cce-2427-11e6-9f14-551b1af654a4.png)

![2016-05-27 16-24-47](https://cloud.githubusercontent.com/assets/1898161/15610834/a3761db8-2427-11e6-967c-aa67fc2e0b40.png)
