### ISSUE TITLE
Ctrl-Up and Ctrl-Down don't advance cursor when hits page limit

### ISSUE THREAD

**Issue by ygoe** [Microsoft/vscode#41621]
I use the Ctrl-Up and Ctrl-Down feature very often, so I can scroll a limited amount of distance without losing my place. This has the advantage of allowing me to use the mouse less for view adjustment.

I've noticed that there is a difference between how this behaves in the full Visual Studio and in Code. In Visual Studio, when you use Ctrl-Up/Down and the view moves such that the cursor is at the limit of the screen, then the editor will advance the cursor such that it remains on the last line visible. Code, however, does not do this, so the next time you hit a key (e.g. a cursor key without pressing Ctrl) then the view resets back to the line you were originally on which is quite jarring.

-----

Here you have your duplicate for #2091 which I cannot vote for because you have closed it because there are too few votes and duplicates. Please leave this one open to give others a chance to vote for it if they also want this bug fixed.

**Comment by alexandrudima** [comment]
I have provided what is IMHO a viable workaround in https://github.com/Microsoft/vscode/issues/2091#issuecomment-346379180:

i.e. Use the following in your `keybindings.json`:

```
    {
        "key": "ctrl+down",
        "command": "editorScroll",
        "args": {
            "to": "down",
            "by": "line",
            "revealCursor": true
        }
    },
    {
        "key": "ctrl+up",
        "command": "editorScroll",
        "args": {
            "to": "up",
            "by": "line",
            "revealCursor": true
        }
    }
```

**Comment by alexandrudima** [comment]
@rebornix can we please add these rules to the Visual Studio keymap ?
