### ISSUE TITLE
Option for merging single child directories with parent in the file tree

### ISSUE THREAD

**Issue by gulshan** [microsoft/vscode#41627]
If a directory has a single directory as a child, please provide an option for showing them merged together in the file tree. So, instead of showing this-
```
+ com
  + domain
    + app
       File1
       File2
```
the file tree will look like-
```
+ com/domain/app
   File1
   File2
```

**Comment by gulshan** [comment]
@isidorn Please mention the other issue with same request, so that I can at least put my vote there.

**Comment by isidorn** [comment]
@gulshan please use our issue search. I would do the same, use the files-explorer tag to narrow down the search. Thanks

**Comment by gulshan** [comment]
@isidorn Actually I do have searched before posting this issue, after closure of this issue as duplicate and again a while ago using the label you mentioned. And yet unable to find any other issue requesting same feature. The closest thing I got is #6328 requesting "file nesting" which is a different feature.

**Comment by isidorn** [comment]
@gulshan you are correct, I made a mistake of thinking this is file nesting
Reopening.

**Comment by gulshan** [comment]
The Gitlens extension does this in their tree.

**Comment by firelizzard18** [comment]
This would be absolutely awesome. I've always loved how github handles this when viewing a repo. It's a significant reduction of UI/UX noise.

**Comment by Deathhush** [comment]
This feature is crucial for Java developers and as mentioned in #39252 . Most of the editors/IDEs for serious Java development, like Atom, IntelliJ, Eclipse, do this. And even visual studio online's own treeview for displaying code repository does this.

Given we are now enhancing the Java experience in vscode by adding various extensions and the recent official Java bundle, this feature will be essential to move this effort forward.

This is NOT a dup as the file nesting feature, which is a totally different thing. @bpasero

**Comment by akaroml** [comment]
I really need to echo this one. For Java projects, the deep folder structure is really annoying and inefficient if they are not organized in a better way. VS Code should support this.

**Comment by hkiang01** [comment]
Oracle's own documentation regarding [Naming a Package](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) necessitates fully qualified package names to prevent name collisions. This creates a need for "deep" packages, or packages with files in deep directory structures. Collapsing these empty directories greatly serves Java developers in being able to more easily navigate their Explorer.

**Comment by stalkerg** [comment]
@bpasero this feature keep explorer as file hierarchy explorer, nothing change but it 200% needed.

**Comment by gulshan** [comment]
Ok. This is a planned feature for November iteration!

**Comment by isidorn** [comment]
Just as an exploration for now. But we plan to address this feature in the near future.

**Comment by Wyntau** [comment]
If multi level directories merged together to show, then we may should consider how to right click mouse to create new file or sub directory in middle level directory

**Comment by gulshan** [comment]
Also, how renaming and deleting individual directory UX goes is a concern. But I think awesome vscode people will figure it out.

**Comment by beastdestroyer** [comment]
Perhaps a toggle in the explorer itself to flatten directories?

**Comment by isidorn** [comment]
We did the initial exploration for this but we will not have time for a full implementation this milestone. Thus pushing to february. Note that in february I am on vacation for 2 weeks so this might only happen in march, but we will see.

**Comment by PHCCorso** [comment]
+1 for this feature. It hurts my eyes to see this giant nested folders hell, and it's the only single thing that's keeping me from using vs code to develop in Java.

**Comment by ExE-Boss** [comment]
Same here, I still use NetBeans for Java development.

**Comment by AntSworD** [comment]
Look forward to this feature

**Comment by rsieja** [comment]
![](https://media.giphy.com/media/cALkoAIov3Y9a/giphy.gif)

**Comment by sprynm** [comment]
> so this might only happen in march - @isidorn 

Coming up June tomorrow so I was hoping to inject this with some new vigor.  It is still on your task list?

**Comment by isidorn** [comment]
We were focued on other things unfortunetely. Keep your eyes open on our plan and when we have cycles we plan to tackle this.

**Comment by tboby** [comment]
Would it be possible for this to be implemented in a way that any extension treeview can take advantage?

**Comment by isidorn** [comment]
We will implement this for the new tree. So all trees in the workbench might benefit from it.
The extension treeview is being adopted to the new tree by @alexr00 soon, so it should also benefit once we introduce this.

**Comment by KristjanTammekivi** [comment]
> We will implement this for the new tree. So all trees in the workbench might benefit from it.
> The extension treeview is being adopted to the new tree by @alexr00 soon, so it should also benefit once we introduce this.

That's great news! I may be pushing my luck, but is there any chance https://github.com/microsoft/vscode/issues/6328 will be included soon after?

**Comment by NNeto** [comment]
Is is already implemented on 1.37.0-insider ?

**Comment by charrondev** [comment]
It looks like the September release shipped a new tree view that supports compressing items from https://github.com/microsoft/vscode/pull/77876 [`CompressableObjectTree`](https://github.com/microsoft/vscode/pull/77876/files)

I was trying to track down the actual PR for that implemented this module in the Source control management view, and found this https://github.com/disksing/vscode/pull/1419. That seems to be a good enough reference point. I'm a little confused about the contribution workflow though.

@joaomoreno were you planning on tackling it? If it's not in the next iteration plan, I'd like to try working on it.

**Comment by joaomoreno** [comment]
This work already started: https://github.com/microsoft/vscode/tree/joao/explorer-compressed-tree

It's still quite buggy and will polish it out probably next month.

**Comment by joaomoreno** [comment]
This has landed in `master`, behind a `explorer.compressSingleChildFolders` setting. It's coming out soon on Insiders so please give it a try and let us know if you hit any issues:

![Peek 2019-11-06 16-06](https://user-images.githubusercontent.com/22350/68310269-01a42480-00b0-11ea-9bc7-00dc43369fea.gif)

**Comment by ExE-Boss** [comment]
Now&nbsp;that&nbsp;this has&nbsp;been&nbsp;implemented, does&nbsp;that&nbsp;mean that&nbsp;#6328 will&nbsp;be&nbsp;next?

**Comment by joaomoreno** [comment]
@ExE-Boss Unfortunately it doesn't mean that.

**Comment by AntSworD** [comment]
GOOD! Waiting for the release date

**Comment by lsmith130** [comment]
Just noticed this is now working in VS Code Insiders! Thank you!!

**Comment by Md-Tahazzot** [comment]
I hate this system

**Comment by isidorn** [comment]
@Md-Tahazzot please use the following setting `"explorer.compactFolders": false`

**Comment by Tylerian** [comment]
> @ExE-Boss Unfortunately it doesn't mean that.

Why is the Team so reticent on implementing that feature? It's very well waited by the community and just a few dozen lines of code, heck, it even has been pull requested multiple times...

**Comment by the-kenny** [comment]
@Tylerian this issue isn't the place to discuss the implementation of another issue...

**Comment by bradisbell** [comment]
Please don't make "clever" UI hacks like this default in the future.  It's seemingly impossible to create a new folder on a new project, and then get to the root level folder to edit files.  Clicking on the root of the project doesn't fix anything, even though it's underlined.

I'm all for a customizable IDE, but the amount of time wasted trying to figure out what config file to undo things like this is really frustrating.  It should not be a default.
