### ISSUE TITLE
open multiple files from search results

### ISSUE THREAD

**Issue by daren-burke** [Microsoft/vscode#41623]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.4
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-npm-script|eg2|0.3.3
vscode-npm|fkn|3.3.0
docker-explorer|for|0.1.6
beautify|Hoo|1.1.1
rest-client|hum|0.16.2
mssql|ms-|1.3.0
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
team|ms-|1.122.0
debugger-for-chrome|msj|4.0.0
vscode-docker|Pet|0.0.23
java|red|0.16.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
---

Steps to Reproduce:

1. search for text
2. see multiple results across many files
3. open one result in a file
4. attempt to open another result in a different file
5. currently open file is switched with new result file

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
You can use ctrl+click to open results in a new editor group, same as from the file explorer or quick open.
