### ISSUE TITLE
Open a new TextEditor,when someone click some texts.

### ISSUE THREAD

**Issue by jialj** [Microsoft/vscode#41629]
- VSCode Version:1.18.0
- OS Version: macOs

Steps to Reproduce:
I am developing an VSCode Extension. I want to achieve such a function， when some texts were click in an TextEdit，then a new tab was opened. I want to know ,How can I do this?
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/jlo4i.png
Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by jrieken** [comment]
Checkout this API: https://code.visualstudio.com/docs/extensionAPI/vscode-api#DocumentLinkProvider

**Comment by jialj** [comment]
@jrieken ,thanks for the link your provided. My problems have been solved.
