### ISSUE TITLE
NSFW watches root when having remote workspace

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#41637]
Was debugging some file event related issue while being [connected to ftp](https://github.com/jrieken/ftp-sample) and noticed that event from everywhere on my system came in... Figured that's because of missing `schema`-checks...

**Comment by jrieken** [comment]
@Tyriar I have pushed 775edfef5a but there might other cases like this

**Comment by Tyriar** [comment]
@jrieken seems like this would cover it from a scheme perspective? Not sure what else we need to cover here.

**Comment by jrieken** [comment]
Yeah, just checking if you know other places in the file watcher world that might be affected by this?

**Comment by Tyriar** [comment]
Nope 😄 thanks for the fix!
