### ISSUE TITLE
[folding] implement vim markers folding

### ISSUE THREAD

**Issue by fsoft72** [microsoft/vscode#41633]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-babel-coloring|dza|0.0.4
rest-client|hum|0.16.2
hg|mrc|1.2.3
python|ms-|0.9.1
markdown-preview-enhanced|shd|0.3.2
vim|vsc|0.10.9

---

Implement the folding method present in vim, where you can define a folding section by specifying the block with: "{{{" and "}}}" respectively.
Furthermore you can have a "title" for the block because everything in the "{{{" line will be shown as text.

For example: 

# {{{ require ( self, a, b c )
def require ( self, a, b, c ):
    print "hello"
# }}}

will be folded in:

# require ( self, a, b, c )

Thanks :-)

**Comment by costincaraivan** [comment]
If this is to be implemented, I hope Visual Studio Code can go all the away. I guess @fsoft72 only uses the default Vim markers, but Vim actually allows customizing the fold markers.

What I'm actually asking for is exposing the fold markers as user settings - having customizable default fold markers for all the file types, which can be overridden by the language specific ones.

Vim example:
set foldmethod=marker -> equivalent to enabling folding based on regions in Visual Studio Code
set foldmarker=##-,-## -> configuration option for the actual fold marker, its default value is {{{,}}}

Folding collapses the whole region and the text after the starting fold marker stays as the region name.

Should I open a separate issue for this?

**Comment by aeschli** [comment]
Folding regions are configured currently defined by the extension that defined the language.
Here is an example (for Java): https://github.com/Microsoft/vscode/blob/268ec647b7e6c280b474d0da5e51049269000944/extensions/java/language-configuration.json#L28

Not sure that there is a default that would work with every language, the languages syntaxes are too different. and E.g. `{{{` is not valid in many languages.

https://github.com/Microsoft/vscode/issues/36002 is the request to also have that setting in the user settings.

Ok to mark this as a dup of #36002. The alternative is that you make PRs to the language configurations where `{{{`/`}}}` makes sense.

**Comment by costincaraivan** [comment]
This more flexible than the current approach.

Example: in Vim I define as the global foldmarker say ##- and -##. Then in all languages that use # as the comment marker, I can use these markers to fold.

In languages that don't use # as the comment marker, I just "hide" the marker in comments: // ##- and // -##.

Both versions are easy to insert using snippets.

This covers 99% of the languages I'm currently using: Ruby, Python, Bash, Javascript, Java, Groovy, C#, etc.

**Comment by daiyam** [comment]
Hi,

I've done a quick experimental extension to add custom folding: [Zokugun Folding](https://marketplace.visualstudio.com/items?itemName=zokugun.zokugun-folding).
The main problem is that I can't remove the existing folding so you get 2 folding providers...

Here my settings with *vim folding markers*:
```
"folding": {
    "*": {
        "start": "\\{\\{\\{",
        "end": "\\}\\}\\}"
    }
}
```

**Comment by aeschli** [comment]
Clsoing based on comment https://github.com/microsoft/vscode/issues/41633#issuecomment-378183022
This should come as a folding provider or we allow users to change the folding makers.
