### ISSUE TITLE
Translate 'Untitled'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#4163]
Start VS Code with --locale=de or --local=pseudo
 
![image](https://cloud.githubusercontent.com/assets/6461412/13747810/62369240-e9fa-11e5-998d-4d42166beafe.png)

'Untitled' should also be translated.

**Comment by bpasero** [comment]
I am not sure if we want to change this because the name shown is the name used for saving and I feel not good to hand this out to translators. It is basically a portion of the URI path we create. I would never want this to be translated to 2 words e.g. Closing as wontfix.
