### ISSUE TITLE
Multiple *duplicate* Git Providers listed in Source Control

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [Microsoft/vscode#41636]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
unique-lines|bib|1.0.0
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
vscode-svgviewer|css|1.4.3
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.1.0
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
JSDocTagComplete|Hoo|0.0.2
task-master|ian|0.1.39
output-colorizer|IBM|0.1.2
vscode-tfs|iva|0.6.0
docthis|joe|0.6.0
PowerShell|ms-|1.5.1
typescript-javascript-grammar|ms-|0.0.26
debugger-for-chrome|msj|4.0.0
indent-rainbow|ode|0.7.2
tsimporter|pmn|1.2.14
csharp2ts|raf|0.0.21
sass-indented|rob|1.4.6
code-settings-sync|Sha|2.8.7
markdown-preview-enhanced|shd|0.3.2
stylelint|shi|0.31.0
addDocComments|ste|0.0.8
html-css-class-completion|Zig|1.16.1

---
In git controlled project.  Git folder is named _git, and location file is named .git_location.

Steps to Reproduce:

1. In environment:
GIT_WORK_TREE                  D:\_Project
GIT_DIR                                D:\_Project\.git_location
Contents of .git_location:
gitdir: D:/Project/_git

2. View Git in VSCode and see multiple Source Code Providers with the same name.  When I start, there are 13 duplicates.

Reproduces without extensions: *Yes*

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by Michael-Tajmajer-Emrsn** [comment]
The issue still presents itself.

Version 1.20.0-insider
Commit 2d79f9da3ca330ad7ebeb7dc3f538a0cf1634fa3
Date 2018-01-18T05:14:16.814Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by aboukirev** [comment]
I had this happening on Windows 10 with MSYS2 and a git wrapper that applied `cygpath -w` to arguments.  `git.path` in VSCode was configured to invoke the wrapper.  As soon as I pointed `git.path` to actual `git.exe` in MSYS2, the problem is gone.  Might be helpful to others.

**Comment by aboukirev** [comment]
Apparently, on Windows curly braces in the command above `git rev-parse --symbolic-full-name --abbrev-ref develop@{u}` must be escaped for PowerShell like the following `git rev-parse --symbolic-full-name --abbrev-ref "develop@\{u\}"`.  In regular `cmd` shell no escaping was necessary and would even break it.  But Microsoft made PowerShell a default shell now and, I believe, git is now executed in context of PowerShell.

**Comment by joaomoreno** [comment]
@Michael-Tajmajer-Emrsn Are you using Git for Windows?

**Comment by joaomoreno** [comment]
@aboukirev Code doesn't support MSYS2, please install Git for Windows.

**Comment by Michael-Tajmajer-Emrsn** [comment]
Yes, I'm using Git for windows:
git version 2.14.1.windows.1
C:\Program Files\Git\cmd\git.exe

**Comment by joaomoreno** [comment]
@Michael-Tajmajer-Emrsn What does `git worktree list` return?

**Comment by Michael-Tajmajer-Emrsn** [comment]
D:/_Working_Folder/_git  (bare)

The Env:
GIT_WORK_TREE                  D:\_Working_Folder
GIT_DIR                        D:\_Working_Folder\.git_location

Contents of the .git_location file:
gitdir: D:/_Working_Folder/_git

**Comment by jonaskello** [comment]
I'm get duplicate providers (they are the same), on both Windows with Git for Windows and Mac. It happens less frequently on MacOS but always on Windows with Git for Windows. When this happens all git functions stop working and I need to restart vscode (sometimes it works to close just of the providers but most often it does not work). It happens every 3 minutes or so on Windows so it is really slowing me down.

```
Windows 10
$ git --version
git version 2.15.1.windows.2

MacOS Sierra 10.12.4
$ git --version
git version 2.11.0 (Apple Git-81)
```

**Comment by joaomoreno** [comment]
@Michael-Tajmajer-Emrsn Can you give me the **exact** output of `git worktree list`?

**Comment by joaomoreno** [comment]
@jonaskello Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by jonaskello** [comment]
@joaomoreno I've used the insider release for an hour now and still no duplicate providers 👍 

Not sure if this is because the insider release has a fix or if it is because it is new without any settings or plugins customized.

**Comment by joaomoreno** [comment]
The insider release has a fix. 👍

**Comment by jonaskello** [comment]
I've run the insiders release all day. It works better but after a few hours of work it also gets duplicate providers:

![image](https://user-images.githubusercontent.com/664076/35442928-5d8cf788-02a9-11e8-8579-70d7d2dae299.png)

**Comment by joaomoreno** [comment]
Also, can you confirm that it also happens for macOS, like you mentioned it does for stable?

**Comment by Michael-Tajmajer-Emrsn** [comment]
Output again:
git worktree list
D:/_Working_Folder/_git  (bare)

**Comment by jonaskello** [comment]
@joaomoreno  I've been using vscode 1.19.3 on MacOS for several hours over the weekend without seeing duplicate providers. I see above that I was using 1.19.2 in my previous report but from the release notes it does not seem like it should have anything new regarding this issue. I will try 1.19.3 for windows in the next days to see if it makes a difference.

**Comment by joaomoreno** [comment]
@Michael-Tajmajer-Emrsn Why do your paths have underscores?

**Comment by Michael-Tajmajer-Emrsn** [comment]
?  Because the corporate policy is to use underscores, that puts the folders on the top of Windows Explorer.

**Comment by joaomoreno** [comment]
Sorry, one more question. Why is Git showing you forward slashes?

**Comment by Michael-Tajmajer-Emrsn** [comment]
Maybe because that is the path in my .git_location file.

The environment is:
Name                           Value
----                           -----
GIT_WORK_TREE                  D:\_Working_Folder
GIT_DIR                        D:\_Working_Folder\.git_location

D:\_Working_Folder\ [master ≡ +0 ~15 -0 !]> git --version
git version 2.14.1.windows.1
D:\_Working_Folder [master ≡ +0 ~15 -0 !]> git worktree list
D:/_Working_Folder/_git  (bare)

D:\_Working_Folder [master ≡ +0 ~15 -0 !]> type .\.git_location
gitdir: D:/_Working_Folder/_git

I can change that in the file if you think that would help!

**Comment by joaomoreno** [comment]
Can you take a screenshot of the command prompt showing all those outputs?

**Comment by Michael-Tajmajer-Emrsn** [comment]
![image](https://user-images.githubusercontent.com/26899055/35527351-14957372-04f0-11e8-8b7f-77eb5dcc69dc.png)

**Comment by joaomoreno** [comment]
You are suffering from duplicate providers for sure due to the fact that git converts backward slashes to forward slashes... Any idea on how or why it is doing that?

**Comment by Michael-Tajmajer-Emrsn** [comment]
No clue -- I changed my .git_location forwarder file to use forward slashes and that has no effect.

I could try changing my env var to point directly to my git folder and see if that helps.

**Comment by Michael-Tajmajer-Emrsn** [comment]
I changed the GI_DIR to point directly to my _git folder, and git for windows still shows slashes and not backslashes && code still shows many providers :-(

**Comment by joaomoreno** [comment]
So, how does `.git_location` work? I couldn't find any information online about it.

**Comment by Michael-Tajmajer-Emrsn** [comment]
That is just the name I use, it sets the gitdir so that the git folder may be somewhere else.

The file is usually named .git, and allows Git to locate the folder.  The format is: gitdir: full_path_to_git_folder.

I set it in the enviroment, though that isn't needed - I could set GIT_DIR directly (which I have tried, and did not work).

I use it because there is no way to disable git in Visual Studio 2017 && if there is *any* .git up the tree VS will refuse to use other source control options (like TFS).

**Comment by joaomoreno** [comment]
Got it. Does it reproduce in a repository in which you don't set the `GIT_DIR` at all?

**Comment by Michael-Tajmajer-Emrsn** [comment]
If I have a standard .git folder it works fine -- it is just when I set the environment vars that the issue appears.

GIT_WORK_TREE
GIT_DIR

**Comment by joaomoreno** [comment]
Awesome. Can you narrow it to one of them? Or only to both simultaneously?

**Comment by Michael-Tajmajer-Emrsn** [comment]
Need to use both of them for git to operate :-(

**Comment by joaomoreno** [comment]
Sure, just wanted to know if the issue reproduces with just one of them.

**Comment by joaomoreno** [comment]
@Michael-Tajmajer-Emrsn Can you give this version a try? https://az764295.vo.msecnd.net/insider/432c8dfa81947a9b7081882b6de46c0e28a64c83/VSCode-win32-x64-1.20.0-insider.zip

**Comment by Michael-Tajmajer-Emrsn** [comment]
Hay, that looks a lot better!!

**Comment by joaomoreno** [comment]
Very cool. That fix is already in `master`, so it should go into January's release next week.

Thanks for your patience!

**Comment by ramya-rao-a** [comment]
Marking as verified as per @Michael-Tajmajer-Emrsn's findings in https://github.com/Microsoft/vscode/issues/41636#issuecomment-362055986

**Comment by eboblin** [comment]
still having this problems with win10 and january release of vs code. It happened before couple of times and restarting vs code helped. Now i constantly see two similar repositories:
http://prntscr.com/ibrldo
