### ISSUE TITLE
Build task does not end 

### ISSUE THREAD

**Issue by taekwonv** [Microsoft/vscode#41632]
- VSCode Version: 1.17.2
- OS Version: MacOSX 10.13.2

Steps to Reproduce:

1. Run a build task
2. It never terminates. 

Hello,

It seems there were couple of similar issues before, unfortunately this problem happens to me. I installed VSCode 1.17.2 on my Macbook and build task shown below never ends when it runs. The task actually runs the following command 'clang++ -Wall test.cpp -v' on the shell, it works fine and terminates when it runs on the shell. The only way to terminate build task on VSCode is to press a key on terminal pane(window) and press a key again when 'Terminal will be reused by tasks, press any key to close it.' pops. Would this be something wrong with my task.json or else? Would this be still a ongoing issue with VSCode?

Below is my tasks.json.

Thanks!

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build",
            "command": "clang++",
            "args": [
                "-Wall",
                "test.cpp",
                "-v" 
              ],
            "isShellCommand": true,
            "showOutput": "always",
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "relative",
                    "${workspaceRoot}"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
    ]
}

**Comment by dbaeumer** [comment]
@taekwonv this is known and got fixed with 1.19.x. Please update.
