### ISSUE TITLE
terminal output bugged when reaching the bottom

### ISSUE THREAD

**Issue by tim241** [Microsoft/vscode#41630]
- VSCode Version: 1.20.0
- OS Version: Arch Linux

Hello, when I execute a build script/do a few things in the terminal, the output gets all messed up at the bottom
I made a short video to display this issue: (I disabled all extensions before recording)

https://youtu.be/p9iiAlgt27k

I'm using a 1440x900 screen

Steps to Reproduce:

1. Open any project
2. execute a few `ls` commands inside the terminal

Does this issue occur when all extensions are disabled?: Yes

EDIT: I thought it could be my `compton` but after disabling my `compton` the issue still persists

**Comment by Tyriar** [comment]
This should be fixed, it was a bug when pulling in an upstream terminal lib
