### ISSUE TITLE
Integrated Terminal Cursor Rendering Error with Powerline font

### ISSUE THREAD

**Issue by Evilcat325** [Microsoft/vscode#41644]
- VSCode Version: 1.19.2
- OS Version: Windows 10.0.16299
- Sub OS Verison: Ubuntu 16.04.3 LTS

Steps to Reproduce:

1. Use ubuntu.exe as integrated terminal
2. Install zsh and use a powerline font theme
(setup in screenshot is powerline9k theme with Source Code Pro for Powerline at 14 font size)

It renders correctly on macOS
But On windows with a subsystem shell, it seems to have error calculating the cursor position when powerline font is presented. 

It breaks when a utf '\ue0d0' is in the prompt

![vscode bug 1](https://user-images.githubusercontent.com/2355763/34965496-6529544e-fa22-11e7-932d-04b018ba42fa.PNG)
If include anything on the right side, it would be wrapped (is should at the end if render correctly)
![vscode bug 2](https://user-images.githubusercontent.com/2355763/34965497-65347874-fa22-11e7-8aff-8b4f9b1606d1.PNG)
It might be a full-width half-width issue, but the render is done in canvas within xTerm. 
![vscode bug 3](https://user-images.githubusercontent.com/2355763/34965498-653cd7f8-fa22-11e7-838a-538fba24de14.PNG)
When it has input, it usually breaks after a 'space'. And the error space usually correlate with number of powerline font character
![vscode bug 4](https://user-images.githubusercontent.com/2355763/34965499-65457da4-fa22-11e7-99f1-650e70356a35.PNG)
When the last char is not 'space' is seems to correct itself upon typing.
![vscode bug 5](https://user-images.githubusercontent.com/2355763/34965495-652061d6-fa22-11e7-83b4-6326c5ee7815.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by Evilcat325** [comment]
```
{
    "workbench.iconTheme": null,
    "terminal.integrated.shell.windows": "ubuntu.exe",
    "terminal.integrated.fontSize": 14,
    "terminal.integrated.fontFamily": "Source Code Pro for Powerline",
}
```

**Comment by Tyriar** [comment]
@Evilcat325 can you try running the select default shell command via the command palette (F1) and select WSL bash? That might help. If it doesn't I'm not sure there is anything that can be done currently as this is probably an upstream issue in winpty.
