### ISSUE TITLE
Every time I type `next(` VS Code will replace it with `INSPECT_MAX_BYTES(`

### ISSUE THREAD

**Issue by pakastin** [Microsoft/vscode#41641]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Type `next(` in JavaScript code
2. VS Code will replace it with `INSPECT_MAX_BYTES(`

Super annoying, because `next(` is very common with `express` 😞

**Comment by jrieken** [comment]
Likely a dupe of https://github.com/Microsoft/vscode/issues/41060 but @pakastin should clarity what 'replace' means in the context of  the issue. You mean suggest and selects that or simply inserts that text without further user interaction (e.g not selecting a suggestion)?

**Comment by pakastin** [comment]
Yeah, it just replaces `next(` immediately with `INSPECT_MAX_BYTES(` when the last character is pressed. I have never used `INSPECT_MAX_BYTES` so I'm not that sure about the duplicate..

**Comment by pakastin** [comment]
Oh, sorry: try `return next(` to reproduce.

**Comment by pakastin** [comment]
Hmm..you're right, typing that last `(` selects a suggestion – that's the bug.

**Comment by pakastin** [comment]
This setting seems to fix the annoyance, however I'm not sure if it should be on by default or not:
```js
"editor.acceptSuggestionOnCommitCharacter": false
```

**Comment by jrieken** [comment]
That also depends on the language/extension you are using. I am afraid but won't get around sharing that with us...

**Comment by pakastin** [comment]
Ok, that must be the case..well, I got it fixed with the setting – sorry I bothered, but developing node.js just was super annoying with the default settings.

Thanks for doing such a great editor though! I had a hard time moving from Atom, but I finally decided to give VS Code a try and there are things I like a lot! 👌
