### ISSUE TITLE
sidebar visibility can be toggled even when`sidebarVisible` context is not satisfied.

### ISSUE THREAD

**Issue by xc1427** [Microsoft/vscode#41645]
- VSCode Version: Version 1.20.0-insider (1.20.0-insider) b36655544f413f67aec02d64ce619d165749b957

- OS Version: macOS 10.13.1 (17B1003)

Steps to Reproduce:

1. add a key-binding as below,

```
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "shift+escape",
        "command": "workbench.action.toggleSidebarVisibility",
        "when": "sidebarVisible"
    }
]
```
2. hit `shift+escape`, sidebar visibility is toggled even when sidebar is **not visible**. What's more, if originally we are in _explorer_ viewlet and a new `Untitled File` is opened, `shift+escape` key stroke can only open the sidebar, but cannot close it.

Please re-verify this PR https://github.com/Microsoft/vscode/commit/8fd521b525a26309e9764c1361dfc4a38b9dd55e 
https://github.com/Microsoft/vscode/issues/36595

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/35225

**Comment by xc1427** [comment]
This could be closed as this issue has already been addressed.
