### ISSUE TITLE
Why is it that you can't fold a code area with a comment code and not all of it is unscientific?

### ISSUE THREAD

**Issue by zhaozhiqi** [Microsoft/vscode#41649]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Why is it that you can't fold a code area with a comment code and not all of it is unscientific?
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Please explain more. Can you add a code sample and screenshots?
