### ISSUE TITLE
IntelliSense not recognizing prototype functions

### ISSUE THREAD

**Issue by iArePJ** [Microsoft/vscode#41648]
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a variable that is a function.
2. Try to call functions of that variable.
3. IntelliSense doesn't recognize parameters of function.

```Javascript
var Gameplay = function() {
}

Gameplay.prototype.test = function(param1,param2) {
}

var GAME = new Gameplay();
GAME.test(<the parameters are not recognized by VSCode>);
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21296
