### ISSUE TITLE
[Theming] Improve priority of the list.inactiveSelectionForeground before git.decorations.enabled

### ISSUE THREAD

**Issue by Zx-EvM** [microsoft/vscode#41643]
- VSCode Version: 1.19.2
- OS Version: Windows 10 Version: 1709 Build: 16299.192

Steps to Reproduce:

1. 
2.

`list.inactiveSelectionForeground` that used to highlight currently open file in working tree doesn't work when `git.decorations.enabled` set to `true`.

Gif with disabled `git.decorations`:

![vsgitds](https://user-images.githubusercontent.com/20873402/34963669-99fbe7d2-f9fe-11e7-8e59-ae8f6c125d77.gif)

Gif with enabled `git.decorations`:

![vsgitens](https://user-images.githubusercontent.com/20873402/34964575-18ddce2c-fa03-11e7-8d6d-f6beb69015c0.gif)

Does this issue occur when all extensions are disabled?: No — This depends on themes but I think theming options (in particular `list.inactiveSelectionForeground`) should work correctly.

**Comment by equinusocio** [comment]
At thhe moment these properties have high priority among the `list.inactiveSelectionForeground`
<img width="427" alt="screen shot 2018-01-16 at 15 05 43" src="https://user-images.githubusercontent.com/10454741/34992865-d62e69fc-face-11e7-979a-32f139bca840.png">

**Comment by jrieken** [comment]
Not sure... That's what the feature is about, showing certain items in a specific colour. It feels like you want the default for `"explorer.decorations.colors"` be changed but that a tough call as that will break muscle memory for most folks.

**Comment by equinusocio** [comment]
We can just let theme authors handle the theme api. `list.inactiveSelectionForeground` and `list.inactiveSelectionBackground` should not have a low priority respect any of`gitDecoration.*` settings.

**Comment by Zx-EvM** [comment]
@jrieken Any update on it? It's not possible to make different colors to stylize decorators sybols (`M`, `U`) separately from `list.inactiveSelectionBackground`. Thus, I think, theme creators will have the opportunity to hightlight currently opened file + safe original colors on decorators.

**Comment by jrieken** [comment]
Closing - no change planned
