### ISSUE TITLE
[Feature Request] Fix bracket auto-closing feature

### ISSUE THREAD

**Issue by ChenglongWang** [Microsoft/vscode#41658]
- VSCode Version: 1.19.2
- OS Version: Windows 10

I think this is old problem has existed for few years.
When you need to type a bracket in front of another bracket, the cursor will jump to end of the last bracket. It seems like a side effect of auto-closing feature. I don't think this behavior has any positive effect on typing. 
Is there any possible solution for fix this issue other than just disabling auto-closing feature: `"editor.autoClosingBrackets": false,` .  Maybe adding some simple judgement flags can fix this problem? if closing bracket  `)` num is not equal to `(`, then just input otherwise skip.

Related question on stackoverflow: https://stackoverflow.com/questions/46589115/disable-closing-bracket-swallowing

**Comment by usernamehw** [comment]
`keybindings.json`
```json
{
    "key": "]",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
        "snippet": "]"
    }
},
{
    "key": "Shift+]",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
        "snippet": "}"
    }
},
{
    "key": "Shift+0",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
        "snippet": ")"
    }
}
```

**Comment by ChenglongWang** [comment]
I have received a temp solution from Alexander? It works fine for me.
keybindings.json
{
    "key": "]",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
        "snippet": "]"
    }
},
{
    "key": "Shift+]",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
        "snippet": "}"
    }
},
{
    "key": "Shift+0",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
        "snippet": ")"
    }
}
