### ISSUE TITLE
Shorten the time in terminal

### ISSUE THREAD

**Issue by teterovic** [Microsoft/vscode#41657]
Feature request:
![image](https://user-images.githubusercontent.com/7413906/34978529-cd8ff53e-fa9e-11e7-9216-a9b951d89147.png)

The time looks very tiny, wouldn't it be better to just use an icon that expands when clicked or that shows the time when covered. Of course there is a copy issue, but that can be also solved by manipulating the clipboard / use ids for the icons and reconnect them with time.

This is probably more an extension idea

**Comment by Tyriar** [comment]
I'm assuming time is tiny for you due to https://github.com/Microsoft/vscode/issues/34320 which is fixed in Insiders.

As for you request, you can't really have that sort of thing in a terminal unfortunately due to the way they work. At least without a bunch of command-specific hacks 😄
