### ISSUE TITLE
Feature Request: Problems | Output | Debug | Terminal - horizontal or vertical windows/tabs side by side positioned on the same screen

### ISSUE THREAD

**Issue by mnp-mid** [Microsoft/vscode#41656]
I would really like to see problems / output / debug / terminal window side by side located and integrated in visual studio.

**Reasons:**
I use Visual Studio Code together with grunt in the terminal for angularjs development. However, once I change the some code I need to see, if the compling of the files was correct in the terminal and so switch back and forth between problems and terminal all the time. The same goes for the debugging konsole, which I mostly forget to check and at some point I realiese that there was an error in the application. 

VS Code Version: 1.19.2
OS Version: Windows 10

**Suggestions:**
- Predefined or fixed layout would be fine for me as a start. 
- Horizontal or vertical aligned however possible
- Toolbar my be located at the same position and on clicking on the tab, it shows the relevant toolbar.

![vs-featurerequest](https://user-images.githubusercontent.com/33545902/34976760-4a7d07aa-fa98-11e7-9008-34975c82567e.png)
![vs-featurerequest2](https://user-images.githubusercontent.com/33545902/34976762-4d2420d8-fa98-11e7-8a96-2a026edca0e9.png)

**Comment by Tyriar** [comment]
I'm going to close this off in favor of https://github.com/Microsoft/vscode/issues/7504 and https://github.com/Microsoft/vscode/issues/3360
