### ISSUE TITLE
Underscore is missing in terminal.

### ISSUE THREAD

**Issue by joshiomkarj** [Microsoft/vscode#41654]
- VSCode Version: 1.19.2 Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
- OS Version: Ubuntu 16.04.2

Steps to Reproduce:

1. Run a simple go program to print a string containing underscore, example
`
package main
import "fmt"
func main() {
	fmt.Println("hello_world")
}
`
2. Run the file
![undescore_missing](https://user-images.githubusercontent.com/5148617/34975996-6eb382e4-faba-11e7-85b2-9cc158608289.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
