### ISSUE TITLE
Can't print 

### ISSUE THREAD

**Issue by bha** [Microsoft/vscode#41659]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Go to file
2. Print option is mission

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/5953
