### ISSUE TITLE
Extension in status bar does not indicate when an extension is being uninstalled

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4165]
Related to #4024

- VSCode Version: 18ebb4a4f5491af7b16e91e42fc36410bbb2e4d7
- OS Version: Linux

Steps to Reproduce:

1. Install an extension, uninstall it
2. Notice that the extension status bar does not update while the extension is being uninstalled
3. I would expect the same animation as when an extension is being installed

**Comment by joaomoreno** [comment]
It does. It's just instant.
