### ISSUE TITLE
Support *.scss.liquid syntax

### ISSUE THREAD

**Issue by kairyou** [Microsoft/vscode#41651]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
StarboundJson|Kyl|0.1.3
vscode-docker|Pet|0.0.23
project-manager|ale|0.23.1
vscode-eslint|dba|1.4.4
vscode-quick-select|dba|0.2.5
tslint|eg2|1.0.24
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
githd|hui|1.1.1
vscode-duplicate|mrm|1.2.0
mssql|ms-|1.3.0
python|ms-|0.9.1
atom-keybindings|ms-|3.0.4
language-liquid|nei|0.0.3
marko|pca|0.2.2
vscode-nginx|sha|0.4.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Configure file type associations in settings.
```json
 "files.associations": {
        "*.scss.liquid": "scss"
    }
```
2. Type `bac`, suggestions do not appear.
![image](https://user-images.githubusercontent.com/544524/34970032-fa0ba49c-faac-11e7-866c-25bf01edbeff.png)

3. It appeared when I change the language from `SCSS` to `CSS`.
![image](https://user-images.githubusercontent.com/544524/34970040-086c3a38-faad-11e7-9379-dd871d8ef655.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This works for me with a simple content
- add the setting as described abov
- create a file foo.scss.liquid
```scss
.foo {
	bac
}
````

![image](https://user-images.githubusercontent.com/6461412/35450325-f52e27b8-02bf-11e8-8a8e-c61ea9e43207.png)

@kairyou Can you attach your code example?

**Comment by kairyou** [comment]
@aeschli When removed the Liquid codes, the autocomplete works normally.

**Comment by aeschli** [comment]
We only support proper SCSS syntax. What you need is an extension of the Liquid SCSS syntax.
Doing a quick search on the marketplace I don't think that exists yet.
