### ISSUE TITLE
Keep html elements within plain text inline on save.

### ISSUE THREAD

**Issue by sqnkov** [Microsoft/vscode#41667]
I want to keep my translation in order, but to do that, I need to disable the new-line for each html element that is within plain text, as follows:

This is how it should be:
![1](https://user-images.githubusercontent.com/9406520/34987369-94cfd10e-fac3-11e7-80dd-63b19993a13b.PNG)

And this is what happens after beautify on save:
![2](https://user-images.githubusercontent.com/9406520/34987381-a256d552-fac3-11e7-853b-a93061ef18fd.PNG)

How can I disable this?

**Comment by ZombieProtectionAgency** [comment]
How would you define plain  text? That text is a header. Beyond that HTML smushes all whitespace into a single space on render so `Plain text ... ` and `Plain text \n...` both render as the former.

**Comment by sqnkov** [comment]
I want to keep the anchor on the same line, in order for the i18n angular directive to work. Is there a way to bypass this?

**Comment by aeschli** [comment]
What you can currently configure is which tags should not be formatted:
`"html.format.contentUnformatted": "h1"`

There's currently no possibility to define an attribute (e.g. 'i18n') that prevents formatting.
We use jsbeautify as underlying formatter, so feature requests for new options must go there: https://github.com/beautify-web/js-beautify
