### ISSUE TITLE
next and previous editor just jumps around

### ISSUE THREAD

**Issue by gotenxds** [Microsoft/vscode#41660]
- VSCode Version: 1.18
- OS Version: mac 10.13.2

Steps to Reproduce:

1. Open a bunch of editors
2. Try and traverse them with the workspace.action.nextEditor shotcut

You'l get this 
https://media.giphy.com/media/xULW8BFmLKRLfB9XDW/giphy.gif

Its a bit small but you can see what I mean, it just jumps around and opens random files.

YUP

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by gotenxds** [comment]
@bpasero Tried it now, seems to work fine, any reason no to work with the nightly build? does it tends to be buggy ?

**Comment by bpasero** [comment]
@gotenxds not sure, but good to know we fixed it.
