### ISSUE TITLE
Feature request Sticky Method/Function Names on top

### ISSUE THREAD

**Issue by MiguelQueiroz** [Microsoft/vscode#41666]
Hello, 

I would like to know if its possible to have something like sticky function/method names on top of the page, during scrolling this sticky bar would contain the function name etc, in scope?

I have explained the case with a screenshot, where A is actual VS code, and B is the version i would "imagine" , where i scrolled  a little bit down, and the function name is occluded but the sticky bar on the ( B) side, shows the function above. This is handy when the function is big ( although not good practice) but in some cases, there is no way around.
![vscode01](https://user-images.githubusercontent.com/2479868/34987103-e4285634-fab1-11e7-8a70-99c9820f709d.png)

**Comment by usernamehw** [comment]
Very similar feature-request: https://github.com/Microsoft/vscode/issues/9418
