### ISSUE TITLE
File explorer does not refresh if a file replaces a folder with the same name

### ISSUE THREAD

**Issue by oparaskos** [Microsoft/vscode#41665]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open visual studio code on some folder (ive chosen C:/temp)
2. Create a file within a folder (eg C:/temp/myfile.txt/myfile.txt)
3. VS Code refreshes view to reflect correct folder structure
4. Run a command like `rm -rf C:/temp/myfile.txt/ && touch C:/temp/myfile.txt` 
5. Go back to VS Code and attempt to reload the file panel
6. The VS Code file panel still shows the folder structure from step 3, the reload button doesn't update it.

Does this issue occur when all extensions are disabled?: Yes

---

4.1. Note that manually running the same tasks seems to give code enough time to keep up - I found this when i made a mistake in a gulp file which was supposed to copy a file to a destination (it copied to destination/filename/filename, i corrected the script and then the vscode file panel would not update)

**Comment by isidorn** [comment]
Can you still reproduce this issue with the latest vscode insiders?
https://code.visualstudio.com/insiders/
