### ISSUE TITLE
Copy pasting string that goes for multiple lines in integrated terminal includes line breaks

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#41661]
- VSCode Version: 1.19.12
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Output a long sting to the integrated terminal, so it goes down multiple lines.
2. Copy the string and paste it somewhere else
3. Line breaks are added to the copied string

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I cannot reproduce, copying this:

<img width="907" alt="screen shot 2018-01-16 at 7 40 44 am" src="https://user-images.githubusercontent.com/2193314/34997178-9a156940-fa90-11e7-8490-fcf1ecd94d2a.png">

Results in:

```
~/dev/Tyriar/xterm.js @1103_search_wide_emoji
❯ laskdmlasdmkl amslkdm lkasdmlksdm lasdkmsdlknasdlkndslkasdmladsk maldkads laksd masldkmasdl mklasd mlasdkmasld mkasdlkasmdlmas dlkams dlask dmlasd kmasdl kas mdlaksd mlasd kmasdl kasdmlaskdmasd
bash: laskdmlasdmkl: command not found
```

**Comment by jpike88** [comment]
Could be my fault.
