### ISSUE TITLE
Task with "reveal": "silent" always appears

### ISSUE THREAD

**Issue by ygoe** [Microsoft/vscode#41671]
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a custom task like below.
2. Run it, for example through the "Trigger Task on Save" extension.

```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Compile JavaScript",
			"type": "shell",
			"command": "uglifyjs site.js --compress --mangle --output site.min.js",
			"options": {
				"cwd": "${workspaceFolder}/js"
			},
			"group": "build",
			"presentation": {
				"reveal": "silent"
			}
		}
	]
}
```

The task panel is always displayed, whether there is an error or not. What is the "reveal" option for if it doesn't work as described?

**Comment by dbaeumer** [comment]
This is actually as designed since the task has no problem matcher and therefore it can't be detect whether an problem has been detected. For those task simply use presentation `never`.

However we could relax the implementation and check for the error code of the process and reveal then.

**Comment by dbaeumer** [comment]
@alexr00 can you please add steps to verify this.

**Comment by alexr00** [comment]
To verify start with this task:

    {
        "label": "ExitWithCode",
        "type": "shell",
        "command": "exit 0",
        "presentation": {
            "echo": true,
            "reveal": "silent",
            "focus": false,
            "panel": "shared",
            "showReuseMessage": true,
            "clear": false
        }
    }

Run the task and confirm that the terminal that the task executed in is not shown. Then change "exit 0" to "exit 4" and run again. The terminal that the task executed in should be shown. Finally, change "reveal":"silent" to "reveal":"never" and rerun again. The terminal should not be shown.
