### ISSUE TITLE
Mac: Recent files should be split into files and folders

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4167]
I love `-w`, am using it left and right. The problem is that all those files are occupying space in my **Recent** list... My most common workspaces don't even show up anymore after a few simple file edits.

![image](https://cloud.githubusercontent.com/assets/22350/13747951/f994e59c-e9fa-11e5-9530-866fd9793403.png)

Could we provide two groups of recent? Files and folders, separately?

**Comment by bpasero** [comment]
Yes, I hate this. I wonder if "-w" should add to the recents at all. Anyway the reason for not splitting this is afaik that the File > open command does not distinguish between files and folders and so I made the recent list also ignore that.

But I do see others like Sublime splitting it, so might be a good idea to add it.

**Comment by joaomoreno** [comment]
If we only did what others did we'd have tabs. Oh, wait...
