### ISSUE TITLE
Intellisense incredibly slow when working inside Unity3D Playmaker extension namespace

### ISSUE THREAD

**Issue by meds** [Microsoft/vscode#41670]
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install Playmaker from unity asset store
2. Create class extending FsmStateAction

Observe: 

Intellisense functions take incredibly long to load and work, including go to definition and autocomplete

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Which language? If JS, did you configure a [jsconfig.json](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson)?

**Comment by meds** [comment]
Ah no it's in C#, I didn't know people used JS in Unity hehe

**Comment by mjbvz** [comment]
Thanks. Please file this issue against the c# or unity extension
