### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by EscapistH** [Microsoft/vscode#41675]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.9.1
cpptools|ms-|0.14.5
material-icon-theme|PKi|3.2.1
java|red|0.16.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.open a pythonfile
2.the problem will happen

Reproduces without extensions: No

**Comment by jrieken** [comment]
can you share that file with us?

**Comment by EscapistH** [comment]
I mean if i use python extension and open or creat a python file,the vscode tell me a error:Extension host terminated unexpectedly. I have two choice:Developer Tools,Resrtart Extension Host

**Comment by jrieken** [comment]
can you share that file with us?

**Comment by Jhuynh760** [comment]
I am also experiencing the same issue. Any python file I open I just get an immediate extension host terminated unexpectedly. This also occurs when I try to open a cpp file as well.

Using the same python extension and version as well as C/C++ by MS version 0.14.6

**Comment by EscapistH** [comment]
I am sorry i don't know which file you want. if you want the python file that i edit. you can get them on my github homepage[https://github.com/EscapistH](url)

**Comment by jrieken** [comment]
@DonJayamanne can you comment

**Comment by EscapistH** [comment]
by the way, when i am using the python extension, i can't use git

**Comment by jrieken** [comment]
> and i try to search same questions on net, someone said if they delet the git extension folder(C:\Program Files\Microsoft VS Code\resources\app\extensions), the problem will disappear

@joaomoreno ideas?

**Comment by Jhuynh760** [comment]
I have disable the extension and I am not longer getting the error.

**Comment by EscapistH** [comment]
if i use vscode without python extension, it will run without error, i will move onto #342 and close this issue soon.
thank you very much. @jrieken @DonJayamanne
