### ISSUE TITLE
Improve Windows update experience

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#41676]

**Comment by mikemaccana** [comment]
There's no details here, but presumably this is to speed up the update time? It would be great for vscode to say 'restart to update' and it just restarts with the new version running, more like Chrome, less like 
the current 90s-style installshield-type thing.

**Comment by joaomoreno** [comment]
@mikemaccana It'll come close to that. 👍

**Comment by mikemaccana** [comment]
@joaomoreno Cool and thanks!
