### ISSUE TITLE
Auto-import creates duplicate import, rather than adding to existing

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#41684]
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

If you have, say

```javascript
import { a, b } from "./util"
```

in your module, and then you do something like 

`blah = c;`

place your mouse at the end of `c`, hit control-space, see the option to auto-import c, and select it, VS Code will add a new import,

```javascript
import { c } from "./util";
```

rather than add c to the import of that module you already have.

This seems to only happen with local modules, but *not* modules that are in node_modules.  For example, telling Code to auto-import MobX's `observe` when you already have `observable` and `autorun`, it'll work perfectly, and just add `observe` to the end of the existing import list.

btw - this is one of my favorite features of all time.  A major convenience - thank you so much for adding it!  This bug is extremely minor, but I thought you'd still want to know about it.

Does this issue occur when all extensions are disabled?: Yes/No

Yes, same issue, no difference.

**Comment by mjbvz** [comment]
Can you please check if this still happens in vscode insiders. We've picked up a new TypeScript version that fixed a number of bugs around auto imports. Hopefully this was already addressed

**Comment by arackaf** [comment]
I just downloaded it, and boom - works perfectly.  

Thanks so much for everything you all do :)
