### ISSUE TITLE
Tool to generate/update a language pack from transifex

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#41682]
Create an extension for a new language:
- Initialized from translations from transifex
- Contains a script to update (and republish)

**Comment by aeschli** [comment]
[vscode-language-pack-bg.zip](https://github.com/Microsoft/vscode/files/1643859/vscode-language-pack-bg.zip)

**Comment by aeschli** [comment]
@dbaeumer Dirk can you comment on the file format?

**Comment by dbaeumer** [comment]
File format looks good to me.

**Comment by aeschli** [comment]
I updated the code yeoman generator to contain a 'languagePack' option.

-> `npm install -g generator-code@next`

**Comment by aeschli** [comment]
[vscode-language-pack-ru-0.0.1.vsix.txt](https://github.com/Microsoft/vscode/files/1651614/vscode-language-pack-ru-0.0.1.vsix.txt)

**Comment by aeschli** [comment]
[vscode-localization-hu-0.0.1.vsix.txt](https://github.com/Microsoft/vscode/files/1652516/vscode-localization-hu-0.0.1.vsix.txt)

**Comment by aeschli** [comment]
[vscode-localization-hu-0.0.1.vsix.txt](https://github.com/Microsoft/vscode/files/1655222/vscode-localization-hu-0.0.1.vsix.txt)

**Comment by aeschli** [comment]
[vscode-localization-hu-0.0.1.vsix.txt](https://github.com/Microsoft/vscode/files/1655374/vscode-localization-hu-0.0.1.vsix.txt)

Files with version and 'contents' property...

**Comment by aeschli** [comment]
[vscode-localization-ps-0.0.1.vsix.txt](https://github.com/Microsoft/vscode/files/1655550/vscode-localization-ps-0.0.1.vsix.txt)
Pseudo language (with german string contents)

**Comment by aeschli** [comment]
[vscode-language-pack-pt-br-0.0.1.vsix.txt](https://github.com/Microsoft/vscode/files/1674230/vscode-language-pack-pt-br-0.0.1.vsix.txt)

**Comment by aeschli** [comment]
[vscode-language-pack-ps-0.0.1.vsix.txt](https://github.com/Microsoft/vscode/files/1674493/vscode-language-pack-ps-0.0.1.vsix.txt)

@dbaeumer Pseudo language as discussed

**Comment by dbaeumer** [comment]
@aeschli the vsix seems to be incomplete. For example the bundle for git only contains translations for the package but not for other files. Can you please have a look and attach a new one

**Comment by aeschli** [comment]
[vscode-language-pack-ps-0.0.1.vsix.txt](https://github.com/Microsoft/vscode/files/1676859/vscode-language-pack-ps-0.0.1.vsix.txt)

Updated VSIX (with all git resources)
