### ISSUE TITLE
Adopt logging service across the workbench

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#41680]
We want to do a quick pass over our code and spread some logging love around. I've decided to split this into into logical parts and assign potential owners to each part. Some of these parts are huge, so take a resonable approach to it:

- If you don't think it's your responsibility, forward it to the person you think it is;
- If it's too much work, split it across more people;
- If it's not relevant to logging, mark it as completed.

I suggest to take the following strategy:

- Use the `info` log level for informational data, which should appear in a regular run of Code
- Use the `trace` log level for traceable function calls, state changes, etc
- Use the `warn` log level for non-blocking, non-critical, possibly expected errors

You can refer to [`vs/platform/update/electron-main/abstractUpdateService`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/update/electron-main/abstractUpdateService.ts) for an example.

**_Warning_: Be careful with concurrent edits to this issue, as always. Refresh the page before you edit it (hopefully you won't need to) or before you check a checkbox.**

## Platform

- [ ] `vs/platform/actions` @jrieken
- [ ] `vs/platform/backup` @Tyriar
- [x] `vs/platform/broadcast` @bpasero
- [ ] `vs/platform/clipboard` @rebornix
- [ ] `vs/platform/commands` @jrieken
- [ ] `vs/platform/configuration` @sandy081
- [ ] `vs/platform/contextkey` @alexandrudima
- [x] `vs/platform/contextview` @joaomoreno
- [x] `vs/platform/environment` @joaomoreno
- [ ] `vs/platform/extensionManagement` @sandy081
- [ ] `vs/platform/extensions` @sandy081
- [x] `vs/platform/history` @bpasero
- [ ] `vs/platform/instantiation` @jrieken
- [ ] `vs/platform/integrity` @alexandrudima
- [x] `vs/platform/issue` @RMacfarlane
- [ ] `vs/platform/keybinding` @alexandrudima
- [x] `vs/platform/lifecycle` @bpasero
- [x] `vs/platform/list` @joaomoreno
- [ ] `vs/platform/markers` @jrieken
- [ ] `vs/platform/opener` @jrieken
- [ ] `vs/platform/progress` @jrieken
- [x] `vs/platform/request` @joaomoreno
- [x] `vs/platform/state` @bpasero
- [x] `vs/platform/storage` @bpasero
- [x] `vs/platform/telemetry` @chrmarti
- [ ] `vs/platform/theme` @aeschli
- [x] `vs/platform/update` @joaomoreno
- [x] `vs/platform/url` @joaomoreno
- [x] `vs/platform/windows` @joaomoreno
- [x] `vs/platform/workspaces` @bpasero

## Workbench Parts

- [ ] `vs/workbench/parts/backup` @Tyriar
- [ ] `vs/workbench/parts/cache` @jrieken
- [x] `vs/workbench/parts/cli` @joaomoreno
- [ ] `vs/workbench/parts/codeEditor` @alexandrudima
- [x] `vs/workbench/parts/debug` @isidorn
- [ ] `vs/workbench/parts/emmet` @ramya-rao-a
- [x] `vs/workbench/parts/execution` @isidorn
- [ ] `vs/workbench/parts/extensions` @sandy081
- [x] `vs/workbench/parts/feedback` @RMacfarlane
- [x] `vs/workbench/parts/files` @isidorn 
- [ ] `vs/workbench/parts/html` @mjbvz
- [ ] `vs/workbench/parts/markers` @sandy081
- [ ] `vs/workbench/parts/output` @sandy081
- [ ] `vs/workbench/parts/performance` @jrieken
- [ ] `vs/workbench/parts/preferences` @sandy081
- [x] `vs/workbench/parts/quickopen` @bpasero
- [x] `vs/workbench/parts/relauncher` @bpasero
- [x] `vs/workbench/parts/scm` @joaomoreno
- [ ] `vs/workbench/parts/search` @sandy081
- [ ] `vs/workbench/parts/snippets` @jrieken
- [x] `vs/workbench/parts/stats` @chrmarti 
- [x] `vs/workbench/parts/surveys` @joaomoreno
- [ ] `vs/workbench/parts/tasks` @dbaeumer
- [ ] `vs/workbench/parts/terminal` @Tyriar
- [ ] `vs/workbench/parts/themes` @aeschli
- [x] `vs/workbench/parts/trust` @joaomoreno
- [x] `vs/workbench/parts/update` @joaomoreno
- [x] `vs/workbench/parts/watermark` @chrmarti
- [x] `vs/workbench/parts/welcome` @chrmarti

## Electron Main

- [x] `vs/platform/url/electron-main/urlService` @joaomoreno 
- [x] `vs/platform/update/electron-main/updateService.*` @joaomoreno 
- [x] `vs/platform/request/electron-main/requestService` @joaomoreno
- [x] `vs/code/electron-main/sharedProcess` @joaomoreno
- [x] `vs/code/electron-main/auth` @joaomoreno
- [x] `vs/base/parts/ipc/electron-main/ipc.electron-main` @joaomoreno

## Misc

- [ ] `vs/workbench/api` @jrieken _(@joaomoreno: joh, feel free to distribute work if it's too much)_
- [ ] `vs/editor` @alexandrudima @rebornix _(@joaomoreno: not sure if interesting for the editor. we'd have to come up with an editor log service)_

**Comment by joaomoreno** [comment]
@egamma @kieferrm Moving this to February, since we are near endgame.

**Comment by jrieken** [comment]
Not a fan of doing this over eagerly

**Comment by bpasero** [comment]
Me neither, and I did a pass once already and I think I would not add much more.

**Comment by bpasero** [comment]
@joaomoreno fyi I expanded the `electron-main` section and assigned you to some items within.

**Comment by joaomoreno** [comment]
I'll close this issue since February is over. Everyone who has unchecked checkboxes, reevaluate whether you want to add logging to your areas and create a separate issue for that.
