### ISSUE TITLE
add command "Find All References of the current file"

### ISSUE THREAD

**Issue by myrdd** [microsoft/vscode#41681]
I'd like to request a new command, which is kind of a follow-up of #22977. Said issue requested "Find All References of a file" to be triggerable from a typescript `import` line like this:
```ts
import {Obj} from "./myfile";
```
In the above line, I just need to trigger `editor.action.referenceSearch.trigger` (`shift+f12`), with the cursor being on `./myfile", and I'll get all places where the given file is imported— that is, #22977 is resolved and works, great! :) This is a demonstration of the currently working file-reference search:

![screenshot of file-reference search](https://user-images.githubusercontent.com/4286829/34995326-6c3d217a-fad6-11e7-9f38-ef5cc952fab7.png)

I'd like to have a new command to **Find All References of the current file**, which can be assigned a keybinding.

Currently, when I want to find all references of a file, I first need to search for a file which is importing the currently-active file. (I'm doing a global search of the filename/path.)

**Comment by mjbvz** [comment]
Same feature request as #66150 (newer issue but that one has more upvotes)
