### ISSUE TITLE
Add ability to add a Panel through an extension

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#41686]
Requested by @dakaraphi in #41071

When a tree view is shown, it should be predictable where it is shown. This is why I think they all need to be on their own panel. If I want to view bookmarks, I don't want it maybe open at the bottom of the explorer, or the middle or who knows where because I have 5 or 6 other tree view contributions.

**Comment by sandy081** [comment]
Contributing to activity bar is implemented here - https://github.com/Microsoft/vscode/issues/43645

Changing this to contribute to panel only

**Comment by simonhaenisch** [comment]
Just to clarify: is this a request for allowing to contribute new panels (with custom web views), i. e. next to "Problems", "Output", "Debug Console" and "Terminal"?

**Comment by sandy081** [comment]
Yes

**Comment by nbransby** [comment]
I have a use case to add a 'debug console'-like view to the panel, is this feature planned anytime soon?

**Comment by mindplay-dk** [comment]
@sandy081 maybe adjust the title and description of this issue? I only understood what this was about after reading Simon's comment and almost opened a duplicate. (Title and description is quite clear on e.g. #86789 which was closed as duplicate, so maybe borrow from there.)

**Comment by sbatten** [comment]
7a5b90c74c6871af5f12037302476137422a5cf4

**Comment by sandy081** [comment]
@sbatten can this be closed as it is enabled?
