### ISSUE TITLE
disable reminder for minor versions by default

### ISSUE THREAD

**Issue by morozovsk** [Microsoft/vscode#41683]
- VSCode Version: 1.19.1
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. start vscode
2. 
![screen018](https://user-images.githubusercontent.com/1822063/34995778-2ab6d16a-fae0-11e7-81b9-c4bf05a554c4.png)

I have version 1.19.1. But vcscode tells me about update to 1.19.2

Do I need update it everyday? I use it couple times a week. Why do I need update it everytime?
Please disable it for minor versions by default.

Does this issue occur when all extensions are disabled?: Yes
PS: I already googled it: "update.channel": "none"
Make it ready for use not for googling.

**Comment by joaomoreno** [comment]
Updates, and especially those with patch versions (third digit), might bring important security fixes. It is in every user's best interest to update.
