### ISSUE TITLE
German translation Issues

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4168]
This issue collects problems with the german translation

**Comment by egamma** [comment]
![image](https://cloud.githubusercontent.com/assets/172399/13747930/eaed82ce-e9fa-11e5-9cf5-3526d1e7b811.png)

Suggest Tabulatorgroesse

**Comment by aeschli** [comment]
Datei > Einstellung > Tastenkombinationen
![image](https://cloud.githubusercontent.com/assets/6461412/13748077/8fccf2fc-e9fb-11e5-89a0-5fa7c1d97ab9.png)

I think 'Tastenkombinationen' should be used consistently.
-> Standard-Tastenkombinationen
-> Uberschreiben Sie die Tastenkombinationen, indem Sie diese in den benutzerdefinierten Tastenkombinationseinstellungen (keybinding.json) eintragen.

**Comment by felixfbecker** [comment]
Where can the locale get edited? I would like to do a PR and I see "dont edit this file, it is generated" everywhere

**Comment by dbaeumer** [comment]
@felixfbecker the can't be edited right now because there source is somewhere else. We are investigating how we can make this more friendly

**Comment by felixfbecker** [comment]
@dbaeumer So where is this source? I think it would make sense to take these once from the external source, but allow the community improve them via PRs.

**Comment by dbaeumer** [comment]
@felixfbecker I agree and we are working on it.

**Comment by egamma** [comment]
![image](https://cloud.githubusercontent.com/assets/172399/13771201/87992b0a-ea8c-11e5-8376-c5d19dc868ac.png)

... but it is correct http://windows.microsoft.com/de-de/windows-vista/open-a-command-prompt-window

**Comment by egamma** [comment]
English Format Code, German: Formatcode

![image](https://cloud.githubusercontent.com/assets/172399/13775167/5bfab61e-eaa3-11e5-824b-b9b386578c4a.png)

**Comment by felixfbecker** [comment]
Should be _Code formatieren_

**Comment by johnliu2016** [comment]
Fixed in loc files

**Comment by dbaeumer** [comment]
Closing. Fixed according to last comment.
