### ISSUE TITLE
Command line tool installation wants 'code' alias removed, no such alias present.

### ISSUE THREAD

**Issue by KevDog** [Microsoft/vscode#4169]
- VSCode Version: 0.10.10
- OS Version: OSX 10.11.3

On attempting to install 'code' command line, I get the following: 
  'Please remove the 'code' alias from '/Users/kstevens/.bashrc' before continuing.'

'alias' returns the following: 

alias acsdev='ssh -l kcs6 acsdev.acsu.buffalo.edu'
alias cmsdev='ssh -l kcs6 cms-dev.acsu.buffalo.edu'
alias cq_start='cd /Applications/day/5.6.1-custom-v2/crx-quickstart/bin/ && ./start && cd -'
alias gcam='git commit -am'
alias ls='ls -la'
alias rvm-restart='rvm_reload_flag=1 source '\''/Users/kstevens/.rvm/scripts/rvm'\'''
alias sandbox='cd ~/code/src/ubcode/sandbox/kcs6'
alias simple_server='python -m SimpleHTTPServer 9000'
alias tree='tree'
alias ubcms='cd ~/code/src/ubcode/ubcms_local/'
alias ubcode='cd ~/code/src/ubcode'
alias vlt='/Users/kstevens/bin/vault-cli-2.4.34/bin/vlt'

[example_bashrc.txt](https://github.com/Microsoft/vscode/files/172170/example_bashrc.txt)

Steps to Reproduce:

1. Not sure, it might be machine specific.  
2. I have included my .bashrc file. I have tried commenting out any line with 'code' in it, in case a poorly formed regex was to blame. No joy.

**Comment by joaomoreno** [comment]
Code is talking about line 30 in your `.bash_rc` file. If you remove it and install the new CLI via the command you can keep `vsc` by setting `alias vsc=code`.

**Comment by KevDog** [comment]
Ah, then the true bug is that commenting the line oiut is insufficient, which is what I tried before filing the issue.

**Comment by joaomoreno** [comment]
Yeah all great points. I can add those two safeguards:

- check whether the line is commented out
- provide the line number

**Comment by joaomoreno** [comment]
Verification: When having the old alias, Code should advise to update to the new symlink. It should report in which file the alias is described, which line within the file and should ignore the line if it is commented out.

**Comment by KevDog** [comment]
João,

Thanks for taking care of this one. I learned a bit about how things work under the covers as I had forked the repo and identified the methods that had to change. I wasn't able to come up with a good way to write a failing test for it, though.

Nice to see bugs picked off so quickly.

**Comment by joaomoreno** [comment]
No worries, thanks for the effort!

**Comment by isidorn** [comment]
There are no longer docs on how to setup the old alias. Do you still have that somewhere or should I go hunting in vscode-docs history?

**Comment by joaomoreno** [comment]
```
vsc () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
```

**Comment by KevDog** [comment]
code () { VSCODE_CWD="$PWD" open -n-b "com.microsoft.VSCode" --args $* ;} is the way it used to be on the VSCode setup page, I used vsc because I had another command aliased to code.
