### ISSUE TITLE
macOS: restoring multiple windows as fullscreen causes title cheese

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#41691]
* on mac, had vscode in fullscreen mode
* selected restart to update
* vs code restored not in fullscreen
* title bar is missing, icons overlap contents

<img width="192" alt="screen shot 2018-01-16 at 08 01 50" src="https://user-images.githubusercontent.com/1794099/34998374-c37691e4-fa93-11e7-9c0b-90a08b568264.png">

**Comment by jrieken** [comment]
> Did you have more than one window open? 

Yeah, usually one in full screen and one or two separate windows in 'normal' mode

> Any related setting that could have an impact?

Not sure, I use fancy headers

**Comment by bpasero** [comment]
> Yeah, usually one in full screen and one or two separate windows in 'normal' mode

For some reason, electron does not let me restore more than one window in full screen. In this case, do you remember if the other windows had the same bug or only the main (last active) one?

> Not sure, I use fancy headers/titles for the windows

That is: `"window.titleBarStyle": "custom"` ?

**Comment by bpasero** [comment]
Still unclear how this happened...

**Comment by bpasero** [comment]
@jrieken did this ever happen again lately?

**Comment by jrieken** [comment]
yes, happens always

**Comment by jrieken** [comment]
I see this when working without an external monitor. I usually have multiple code windows running in full screen and it seems that only one is restored as fullscreen and others, previous full screen windows, have the screen cheese

**Comment by bpasero** [comment]
Ah yeah, now I can easily reproduce. This is actually a consequence of https://github.com/Microsoft/vscode/issues/32247 and reported as https://github.com/electron/electron/issues/13077

I cannot even add a simple workaround because the window reports back to me that it is indeed fullscreen even though it is not. Only after a timeout of 0 I get the correct value. I have pinged Electron people.

**Comment by bpasero** [comment]
I will investigate in October and close as wont-fix if it cannot be fixed.

**Comment by FernandoMiguel** [comment]
I have not seen this happen for me for a few months. i used to have this regularly before

**Comment by bpasero** [comment]
@FernandoMiguel you are on macOS restoring multiple windows that were fullscreen on startup?

**Comment by FernandoMiguel** [comment]
@bpasero 
`macos 10.15 Beta (19A582a)`

```
Version: 1.39.0-insider
Commit: 5cd3b2abc98ebc8c8e226f0cd95a9bca93e2b4ad
Date: 2019-10-08T13:14:14.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
```
