### ISSUE TITLE
Incorrect licence listed on the website

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#417]
The licence is [given here](https://github.com/Microsoft/vscode/blob/master/LICENSE.txt) as MIT but on the website it is [Microsoft Pre Release](https://code.visualstudio.com/License).

**Comment by chrisdias** [comment]
The license on code.visualstudio.com is for the VS Code product.  The license found in the vscode repo is for the open source code.

**Comment by SteveALee** [comment]
Ah, yes, OK. I think the product licence still mentions Preview though, not Beta.

**Comment by chrisdias** [comment]
good point, thanks!

**Comment by chrisdias** [comment]
The [website](https://code.visualstudio.com) now has the "BETA" banner and the [license](https://code.visualstudio.com/license) refers to "BETA".  Issue #60 explains the difference between the repository license and the Visual Studio Code product license.

**Comment by SteveALee** [comment]
@chrisdias FYI that Beta banner does **not** appear on mobile version of the website. It is on the Licence page though.

**Comment by chrisdias** [comment]
@bgashler1 can you look at this?

**Comment by bgashler1** [comment]
@SteveALee, are you referring to the "BETA" flag that appears in the top left corner or the yellow banner below the logo?

**Comment by SteveALee** [comment]
@bgashler1 Yes I am.
