### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sween** [Microsoft/vscode#41705]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
chef|Pen|0.6.4
Go|luk|0.6.73
csharp|ms-|1.13.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
will re-open when there is actionable information in this issue
