### ISSUE TITLE
PowerShell terminal process terminated exit code 4294901760

### ISSUE THREAD

**Issue by Chiliyago** [Microsoft/vscode#41708]
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows Server 2012 R2 Standard

Steps to Reproduce:

1. Open VS Code (as administrator)
2. Open PowerShell file
3. Error notice: The terminal process terminated with exit code: 4294901760

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
