### ISSUE TITLE
Debug action widget should update for the selected thread

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41709]
When one thread is paused, and others are running, I can't pause a running thread, because the debug widget only shows the "continue" button. It seems like the behavior should match how it works for debugging multiple sessions, when the debug widget state updates for what's focused in the call stack. Am I misunderstanding the thread debug model, or is this a bug?

This issue came out of last week's meeting

cc
@weinand 
@mostafaeweda
@ebluestein

**Comment by isidorn** [comment]
This is fixed in the latest insiders. Please try it there and if the issue still remeains please comment  with reproducable steps and I will reopen. Thanks a lot
https://code.visualstudio.com/insiders/
