### ISSUE TITLE
FEATURE REQUEST: COMMAND SHORTCUT FOR ARROW KEYS

### ISSUE THREAD

**Issue by ellisOverson** [Microsoft/vscode#41703]
A lot of my coding mistakes are made from moving my hand back and forth between the arrow keys and the home row of typing. 

would it be possible to create an option where you hold down command and your , i, j, k, l keys turn into arrow keys.

Holding down command: 
arrow up would be "i"
arrow down would be "k"
arrow left would be "j"
arrow right would "l"
"home" key would be "u"
"end" key would be "o"

I feel this may add value to vscode.

**Comment by alexandrudima** [comment]
This is doable via customizing keybindings - https://code.visualstudio.com/docs/getstarted/keybindings
