### ISSUE TITLE
Bug while scroling with trackpad

### ISSUE THREAD

**Issue by BhawanS** [Microsoft/vscode#41701]
windows 10 , i have lag when i scroll on any page

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
bug while filling issue? forgot to fill in steps that allow us to repo or forgot to attach perf trace? please do so: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by Izet0004** [comment]
Also here, it's been a bug for months. You will just get the answer: "Resize your window" which will work for like 5 minutes.. Pretty annoying they wont look into it, when it's such a big issue.
