### ISSUE TITLE
--status flag not working

### ISSUE THREAD

**Issue by Chiliyago** [Microsoft/vscode#41707]
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows Server 2012 R2 Standard

Steps to Reproduce:

1. Start VS Code (as administrator)
2. Open cmd prompt (as administrator)
3. Enter:  "code --status"
4: Result: [main 3:12:24 PM] Startup error: I

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Chiliyago** [comment]
I tried that but as soon as I open any .ps1 file the error returns.

**Comment by dbaeumer** [comment]
@Chiliyago 

> I tried that but as soon as I open any .ps1 file the error returns.

What exactly does that mean. And can you run other PowerShell scripts or is PowerShell completely disabled on our machine.

**Comment by Chiliyago** [comment]
Sorry I accidentally was thinking this was another issue. I will delete my last comment.

**Comment by dbaeumer** [comment]
@Chiliyago good to know. Can you try insider. We added mote logging here in case the querying of the data fails.
