### ISSUE TITLE
While debugging, show decorations marking the locations of all threads

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41714]
VS shows decorations in the margin, marking the locations of all paused threads. Very useful. It also could work for multi-process debugging. I don't know whether it should mark the location of the top frame of any stack, or every location that appears in any frame of any stack.

This idea came out of last week's meeting

cc
@weinand
@mostafaeweda
@ebluestein

**Comment by isidorn** [comment]
The whole vscode debug ux is sort of a slave to the focused stack frame. So this would go against that metaphor.
Though if you come up with sketches and exact ideas that make sense we might consider this.
