### ISSUE TITLE
Properties File Language highlighting is Wrong

### ISSUE THREAD

**Issue by ChuanyuWang** [Microsoft/vscode#41719]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
vue-snippets|hol|0.1.5

---

Steps to Reproduce:
1.  Copy below content into file `test.properties`
```
#Error dialog description
ERROR_TEXT=Currently there's no data in the back end

#This is the title for the detail page business benefits panel
BENEFITS=Business Benefits
```
2. Open file `test.properties` with VSCode
3. The language highlight is wrong 
- line 4 is comment, but is grey out
- line 5 key and value is not recognized

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to textmate/ini.tmbundle#4
