### ISSUE TITLE
Extreme CPU usage for no reason

### ISSUE THREAD

**Issue by KFlash** [Microsoft/vscode#41718]
- VSCode Version: 1.19.2 (*same on 1.18*)
- OS Version: Windows 10

Steps to Reproduce:

1. Use VSCode on Windows and open Task Manager. CPU usage is around 98% all the time.
2. Close VSCode and the CPU usage is back to norma

**Additional info**

I tried to figure out the root cause of this, but not sure. Sometimes I'm using the TSC  watch task in the background while developing and it seems to trigger this. But even if I turn that off and do normal stuff, the CPU usage goes sky high again. 
When I investigated that issue I found out that I also now are using the `super keyword` to extend the main class in the code.  Either VSC or TS are using a lot of resources on this too, and the CPU goes high again.

If I do normal typing without any use of `super` the CPU usage is normal. Same if I turn off the watch task.

I can just close VSCode and the CPU usage goes back to normal, but sometimes it doesn't remember the files I had open before I closed it down when this issue happen.

And I can also add that I also run out of memory a few times when this happen. Forcing me to do a manual reboot of the computer. 

I have no good idea's what's going on except I may think VSC somehow is duplicating itself? If I have one copy of the program open, it should stand as (1) in the Task Manager. But when the CPU usage go sky high it show 13 instances of the program? And I still have only one copy open. 

I was looking at the `Task Manager` in Wndows now. 13 VSC and `1 Console Window Host` is running.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by KFlash** [comment]
@bpasero Well. Now VSCode started to consume all my memory as well. Anyway. Is this what you need?

```js
Version:          Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
OS Version:       Windows_NT x64 10.0.17074)
CPUs:             Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)
Memory (System):  7.92GB (1.11GB free)
VM:               0%
Screen Reader:    no
CPU %   Mem MB  Process
    0       99  code main
    0       24     gpu-process
    0       73     shared-process
    1      279     window (xxx.ts - foo- Visual Studio Code)
    0       11       "C:\Program Files\Microsoft VS Code\Code.exe" --reporter-url=https://rink.hockeyapp.net/api/2/apps/0ac07349c6e34e978fdfb42074932f22/crashes/upload --application-name=VSCode "--crashes-directory=C:\xxx\kflas\AppData\Local\Temp\VSCode Crashes" --v=1
    0       31       terminal
    0        7         "c:\Program Files\Microsoft VS Code\resources\app\node_modules\node-pty\build\Release\winpty-agent.exe" \\.\pipe\winpty-control-2056-1-1d38f5a8a817c12-11a627ced40a93884c7cf78c28e256ac 0 1 208 3
    0       77           C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0        3             C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\Microsoft VS Code\bin\code.cmd" --status"
    0       32               electron_node cli.js
    0       51                 "C:\Program Files\Microsoft VS Code\Code.exe" --status
    0       31                   gpu-process
    0       78                   powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
    0        7                     C:\WINDOWS\system32\conhost.exe 0x4
    0       10           C:\WINDOWS\system32\conhost.exe 0x4
    0       14       watcherService
    0        6         C:\WINDOWS\system32\conhost.exe 0x4
    0       72       extensionHost
    0       22         electron_node jsonServerMain.js
    0      208         electron_node electronForkStart.js tsserver.js
    0       21           electron_node typingsInstaller.js tsserver.js typesMap.js
    0     1704         electron_node server.js
    0       21       searchService
```

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by KFlash** [comment]
After I disabled the extension VSC are *only* using 5 GB of RAM. And the only extension I'm using is the TSLint one. Same as I have used for months before this issue happen. The issue I'm now facing with VSC happen after the last 2 - 3 updates.

The only difference after disabling is the change in this line `Memory (System):  7.92GB (0.57GB free)`

Anyway. Need to reboot the computer now to get it back to normal state.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by KFlash** [comment]
I tried it, and disabled what I could, but still it seem to freeze from time to time.  But it looks like VSC have gone from using a lot of CPU to eat a lot of memory. And I tracked it  down now to be the TSC watch tasks. CPU and memory are back to normal I avoid using it, but soon as I turn it on this happen.

**Comment by KFlash** [comment]
```js
Version:          Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
OS Version:       Windows_NT x64 10.0.17074)
CPUs:             Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)
Memory (System):  7.92GB (3.10GB free)
VM:               0%
Screen Reader:    no
CPU %   Mem MB  Process
    0       97  code main
    0       64     shared-process
    0      262     window (xxx.ts - foo- Visual Studio Code)
    0       63       extensionHost
    0       25         electron_node jsonServerMain.js
    0      181         electron_node electronForkStart.js tsserver.js
    0       22           electron_node typingsInstaller.js tsserver.js typesMap.js
    0       31       terminal
    0        7         "c:\Program Files\Microsoft VS Code\resources\app\node_modules\node-pty\build\Release\winpty-agent.exe" \\.\pipe\winpty-control-11008-1-1d38f71379064a1-781a64e594b547b946c809a472b5b4eb 0 1 208 6
    0       67           C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0       10           C:\WINDOWS\system32\conhost.exe 0x4
    0       14       watcherService
    0        5         C:\WINDOWS\system32\conhost.exe 0x4
    0       10       "C:\Program Files\Microsoft VS Code\Code.exe" --reporter-url=https://rink.hockeyapp.net/api/2/apps/0ac07349c6e34e978fdfb42074932f22/crashes/upload --application-name=VSCode "--crashes-directory=C:\Users\xxx\AppData\Local\Temp\VSCode Crashes" --v=1
    0       24     gpu-process
```

**Comment by bpasero** [comment]
From that status details I see neither high CPU nor memory usage.

**Comment by KFlash** [comment]
The status details above is from me turning off both the watch task and plugins. The system still uses 4.5  GB RAM and I only have VSC open and this browser window. Turning on the watch tasks will bring the CPU usage up to 80 - 85%.

**Comment by bpasero** [comment]
@KFlash it would be helpful if you could run `code --status` WHEN VS Code consumes lots of resource, not WHEN not.
