### ISSUE TITLE
[folding] Some useful editor actions (like fold/unfold) are not available for readonly files

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4171]
- debug a node app a stop somewhere
- in the CALL STACK select a frame from an internal module
- in the editor fold a method
Observe: this works fine
- press F1 and type "fold"
Observe: the fold and unfold actions are not available

**Comment by isidorn** [comment]
This is because Martin does not register those actions for readonly editors. Forwarding to @aeschli
