### ISSUE TITLE
language service could not be started

### ISSUE THREAD

**Issue by Chiliyago** [Microsoft/vscode#41711]
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Start new instance of VS Code in Administrator mode
2. Error will show up eventually.
1/16/2018 3:31:41 PM [NORMAL] - Visual Studio Code v1.19.2 64-bit
1/16/2018 3:31:41 PM [NORMAL] - PowerShell Extension v1.5.1
1/16/2018 3:31:41 PM [NORMAL] - Operating System: Windows 64-bit
1/16/2018 3:31:41 PM [NORMAL] - Language server starting --
1/16/2018 3:31:41 PM [NORMAL] -     exe: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
1/16/2018 3:31:41 PM [NORMAL] -     args: C:\Users\timothyo\.vscode\extensions\ms-vscode.powershell-1.5.1\scripts\Start-EditorServices.ps1 -EditorServicesVersion '1.5.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.5.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\timothyo\.vscode\extensions\ms-vscode.powershell-1.5.1\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\timothyo\.vscode\extensions\ms-vscode.powershell-1.5.1\logs\1516145501-c1be9861-1fb6-4601-b727-32ea6d4a8a4f1516145497216\EditorServices.log' -SessionDetailsPath 'C:\Users\timothyo\.vscode\extensions\ms-vscode.powershell-1.5.1\sessions\PSES-VSCode-2968-493412' -FeatureFlags @()
1/16/2018 3:31:42 PM [NORMAL] - powershell.exe started, pid: 8580
1/16/2018 3:31:42 PM [NORMAL] - powershell.exe terminated or terminal UI was closed
1/16/2018 3:32:41 PM [NORMAL] - Language server startup failed.
1/16/2018 3:32:41 PM [ERROR] - The language service could not be started: 
1/16/2018 3:32:41 PM [ERROR] - Timed out waiting for session file to appear.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
