### ISSUE TITLE
typescript server died

### ISSUE THREAD

**Issue by tlimpanont** [Microsoft/vscode#41729]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.2.0
material-icon-theme|PKi|3.2.1
jsx|Twe|0.0.1
terminal-tabs|Tyr|0.1.1
gitignore|cod|0.5.0
githistory|don|0.3.0
vscode-babel-coloring|dza|0.0.4
terminal|for|0.0.10
intellij-idea-keybindings|k--|0.2.18
vue|liu|0.1.5
vscode-jade-snippets|mrm|1.0.1
node-debug2|ms-|1.20.0
vetur|oct|0.11.6
git-merger|sha|0.3.6
js-jsx-snippets|sky|0.0.9
react-beautify|tai|0.3.0
vscode-react-native|vsm|0.5.7
gitblame|wad|2.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
@tlimpanont do you have any more steps on reproducing? Does this normally happen? is it immediate after launch? Does it happen consistently? etc.
