### ISSUE TITLE
Configuring tasks has more text than a Twilight novel

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4172]
Related to #4019

![screen shot 2016-03-14 at 15 48 33](https://cloud.githubusercontent.com/assets/1926584/13748263/58faa7dc-e9fc-11e5-9215-4452e6a16fc3.png)

Instead of repeating 'Creates a tasks.json file for' multiple times I suggest to do the following:
* Rename 'Pick a tasks template' to 'Create a 'tasks.json' file for'
* Cut all the descriptions in half by removing the 'Creates a tasks.json file for' part
  * e.g Creates a task.json file that compiles using msbuild -> compiles using msbuild

**Comment by dbaeumer** [comment]
Dups #4196

**Comment by isidorn** [comment]
Hmm this bug is older than 4196

**Comment by dbaeumer** [comment]
@isidorn agree but it had more hints what to change. That is why I kept that one open :-)
