### ISSUE TITLE
Telex Keyboard must "confirm" when typing

### ISSUE THREAD

**Issue by nighttiger1990** [microsoft/vscode#41723]
- VSCode Version: Version 1.19.2 (1.19.2)
- OS Version: Mac-OS High Sierra 10.13.2 (17C88)

Steps to Reproduce:
1. Choose Telex Keyboard
2. Type "something" and "something" display with white color. 
3. Do something to "confirm word" (like press "ESC") then "something" display normal color
How can skip step called "confirm word" when using Telex? Or is this bug with VSCode? 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jrieken** [comment]
What is 'Telex Keyboard'?

**Comment by nighttiger1990** [comment]
Vietnamese Keyboard
