### ISSUE TITLE
strange intellisense suggestion in settings.json

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#41732]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (54240a7bd3854fc9e0c07b399683547500a1914e, 2018-01-17T05:14:17.405Z)</li>
	<li>OS Version: Windows_NT x64 10.0.16299</li>
	<li><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|7.5.3
python|ms-|0.9.1
debugger-for-chrome|msj|4.0.0

</details></li>
</ul>

---

Steps to Reproduce:

1. Add `"files.associations": {}` in setting.json
2. Trigger Intellisense in those brackets
3. bug

expect:
![1e9627152f05d7d3d60b39bb9dd785b9](https://user-images.githubusercontent.com/8474118/35036179-dd1307c6-fbb6-11e7-9707-d705692a1fd5.png)

https://github.com/Microsoft/vscode/blob/master/extensions/configuration-editing/src/settingsDocumentHelper.ts#L60

happened instead:
![1dcb17271de70ca1115ce82314c4d3b4](https://user-images.githubusercontent.com/8474118/35036359-772c72fc-fbb7-11e7-9d77-036400c2bda5.png)

This bug occurs only with Insider.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
I can reproduce.

@aeschli @sandy081 literally nothing changed on my end how this setting is contributed [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/files.contribution.ts#L188).

Did something change how the [`settingsDocumentHelper`](https://github.com/Microsoft/vscode/blob/master/extensions/configuration-editing/src/settingsDocumentHelper.ts#L27) works? It still seems to work fine for `files.exclude` though.

**Comment by sandy081** [comment]
@bpasero AFIK I did not change in this file related to `files.*` completion proposals.

**Comment by bpasero** [comment]
@aeschli help!
