### ISSUE TITLE
update-alternatives: error: alternative path /usr/bin/code-oss doesn't exist

### ISSUE THREAD

**Issue by pazucj** [Microsoft/vscode#41733]
- VSCode Version: > 1.1
- OS Version: Raspberry Pi 3

Steps to Reproduce:

After install vs code via dpkg I got error:

`sudo dpkg -i ./.build/linux/deb/armhf/deb/code-oss_1.20.0-1516181563_armhf.deb
(Reading database... 135207 and directories currently installed.)
Preparing to unpack .../code-oss_1.20.0-1516181563_armhf.deb ...
Unpacking code-oss (1.20.0-1516181563) over (1.20.0-1516181563) ...
Setting up code-oss (1.20.0-1516181563) ...
update-alternatives: error: alternative path /usr/bin/code-oss doesn't exist
Processing triggers for gnome-menus (3.13.3-9)...
Processing triggers for desktop-file-utils (0.23-1)...
Processing triggers for mime-support(3.60)... `

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6442

**Comment by pazucj** [comment]
@Tyriar u linked me not resolved topic and closed this one. What a stupid moderator

**Comment by Tyriar** [comment]
@pazucj because the linked issue is about supporting raspberry pi which we don't do currently, and your issue is about installing the deb package on raspberry pi.
