### ISSUE TITLE
ENOENT : no such file or directory /electron-main/main.js

### ISSUE THREAD

**Issue by pazucj** [Microsoft/vscode#41731]
- VSCode Version: > 1.1
- OS Version: Raspbian / Rapsberry Pi 3

npm --version : 5.6.0
node --version : v9.4.0

Steps to Reproduce:

1.Succesfully install from command ./scripts/npm.sh install .
2.When I put ./scripts/code.sh it returns me : 

```
[6253:0117/101132.743091:WARNING:audio_manager.cc(295)] Multiple instances of AudioManager detected
[6253:0117/101132.743423:WARNING:audio_manager.cc(254)] Multiple instances of AudioManager detected
{ errorCode: 'load',
  moduleId: 'vs/code/electron-main/main',
  neededBy: [ '===anonymous1===' ],
  detail: 
   { Error: ENOENT: no such file or directory, open '/home/pi/Development/vscode/out/vs/code/electron-main/main.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/pi/Development/vscode/out/vs/code/electron-main/main.js' } }
```

I tried to rm -rf node-modules and reinstall via ./scripts/npm.sh install and there is the same issue

Does this issue occur when all extensions are disabled?: Yes

Where I can get main.js from electron-main folder?

**Comment by lucasqueiroz** [comment]
Can you explain how you fixed this? I'm having the same issue

**Comment by pazucj** [comment]
No I didn't fix this. But this issue is for my mistake because I didn't go with step to step in compiling vscode for RPi. Good Luck
