### ISSUE TITLE
Keybindings.json opens in position 2

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41737]
1. open keybindings in position 3
2. click on action to open keybindings.json

=> it opens in position 2, why?

**Comment by sandy081** [comment]
Because it opens two files `Default keybindings` and `keybindings.json` files. These files always open next to each other. So when you open from position 3, defaults open in position 1 and keybindings.json in poistion 2.

**Comment by bpasero** [comment]
If position is already 3, then maybe just open in the same position?

**Comment by sandy081** [comment]
We cannot open two editors in one position, as said they are two editors opens next to each other.

**Comment by bpasero** [comment]
Yeah, I think you need to special case the situation where the active editor is in position 3 and in that case just open the keybindings.json in position 3?

**Comment by sandy081** [comment]
Yeah that can be done.

**Comment by ramya-rao-a** [comment]
@sandy081  Is this still meant for the January milestone? If not, can you move it to February milestone?

**Comment by bpasero** [comment]
This no longer reproduces ever since the grid was added.
