### ISSUE TITLE
no highlight for XML type files with different file extention

### ISSUE THREAD

**Issue by svasil** [Microsoft/vscode#41735]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
close-all|ben|1.0.2
xml|Dot|1.9.2
live-html-previewer|hdg|0.3.0
vs-keybindings|ms-|0.1.7
stardog-rdf-grammars|sta|0.0.6
code-spell-checker|str|1.6.2
markdown-all-in-one|yzh|1.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open any XML type file more then 10M --> no highlight

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This is by design.

VSCode will not tokenize files larger than 20MB or with more than 300K lines. 

The reason is that storing tokens for such large files begins to consume a large amount of memory.
