### ISSUE TITLE
VSCode: Regex highlighting not properly

### ISSUE THREAD

**Issue by mnp-mid** [Microsoft/vscode#41739]
Highlighting is not proper for regular expressions.
I am using Visual Studio Code with AngularJs + Typescript.

- VSCode Version: 1.19.2
- OS Version: Windows

Steps to Reproduce:
```
function test(str: string) {
    str.match(/a/ims);       // <- not highlighted as below
    str.match(/a/im);        // <- works good
}
```

![image](https://user-images.githubusercontent.com/33545902/35041053-b99ec5e2-fb83-11e7-83cd-e1747e13ef8e.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#560
