### ISSUE TITLE
Workspace settings info message wording

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#4174]
![image](https://cloud.githubusercontent.com/assets/6461412/13748555/8ca4652c-e9fd-11e5-8942-75cdababa543.png)

To me it was not immediately clear what 'Never show again' refered to. Never show me the user settings editor again? Also I found 'Never' a bit harsh.

Maybe 'Don't show again' or 'Don't ask again' 
or "Always Ignore', 'Ignore' (instead of 'Close')

The better solution would be if the User settings editor has a warning on the actual settings that are overwritten.

**Comment by bpasero** [comment]
Will check for a better label.

**Comment by bpasero** [comment]
:+1:  for Don't show again
