### ISSUE TITLE
Code won't launch & throws segfault

### ISSUE THREAD

**Issue by Miesvanderlippe** [Microsoft/vscode#41749]
- VSCode Version: 1.19.2 or 1.20.0-insider
- OS Version: Debian9.3 4.9.0-5-amd64 SMP Debian 4.9.65-3+deb9u2

Steps to Reproduce:

1. Install Code or Code-Insiders from repos as suggested by guide
2. Launch code from terminal or Gnome3

Does this issue occur when all extensions are disabled?: Yes

The following errors are from 2 separate launches. 
```
sudo dmesg --human | tail:

[Jan17 16:29] code[10681]: segfault at 7fff3f1f2ff0 ip 00007f93b90bd420 sp 00007fff3f1f2ff0 error 6 in libstdc++.so.6.0.22[7f93b9003000+172000]

[Jan17 16:31] code[10833]: segfault at 7fff602c8ff0 ip 00007f43c398e0ef sp 00007fff602c8ff0 error 6 in libnspr4.so[7f43c3967000+35000]
```

Please do tell me if I can add any more useful log.

**Comment by Tyriar** [comment]
Does `code --verbose` reveal anything useful?

**Comment by Miesvanderlippe** [comment]
There's no output sadly.

```
miesl@debian-miesl:~$ code --verbose
miesl@debian-miesl:~$ 
```

**Comment by Tyriar** [comment]
@bpasero any ideas on how to investigate this further?

**Comment by bpasero** [comment]
@Tyriar @Miesvanderlippe if this is a native crash, maybe follow https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#linux

**Comment by Miesvanderlippe** [comment]
I owe you guys an apology. It appears I messed up my shared library config so Code tried to launch with a lib that came w/ Firefox instead of the correct one. Thanks a lot for the link to the debugging steps.
