### ISSUE TITLE
CTRL+C doesn't copy all if last lines are folded

### ISSUE THREAD

**Issue by amgalan81mn** [microsoft/vscode#41744]
Example from #83985 (edited by @aeschli):
- create a markdown document from the content below
- collapse all (Ctrl+K, Ctrl+0)
-  Ctrl+A to select all,

-> the copied text does not include the WaveRecord onwards, it is only copied as far as the #Data Structures (line 6)

```
# (APIBlueprint document)

# Introduction
This is my introduction

# Data Structures

## WaveRecord (object)

+ mailingId: 103 (number, required) - The mailing identifier.
+ waveId: 253 (number, required) - The wave identifier.
+ name: `Initial Test` (string, required) - The wave name.
+ portion: 500 (number, required) - The wave portion of the mailing (1 - 10000), 10000 represents the whole mailing.
+ status: `Processed` (enum, required) - The wave status.
    + Members
        + `Draft` - The wave has been created but not queued.
        + `Processed` - The wave has been processed.
        + `Queued` - The wave has been queued but not processed.
+ createDate: `2016-07-30T16:28:22` (string, required) - The create date (UTC).
+ modifyDate: `2016-07-31T07:49:18` (string, required) - The last modified date (UTC).
```

**Comment by jrieken** [comment]
ctrl+a where?

**Comment by amgalan81mn** [comment]
i'm working with text file, but python is also same syntax structure

last collapsed row won't includes in selection.

Ctrl+a, even with mouse dragging.

I illustrated problem with 3 parts of image with description

**Comment by aeschli** [comment]
@amgalan81mn Can you please add the screenshots that show the problem?

**Comment by amgalan81mn** [comment]
I've already attached the screen shot. see previous mail

**Comment by amgalan81mn** [comment]
try this one, copy paste this content to create new file in VS Code editor
   2 collapse all
      3 notice: last row must be collapsed
   4 select all
      5 with mouse or with CTRL+A
   6 copy
   7 create new file
   8 paste
9 this is what happens, i lost my 10th line
   10 you won't see this line

**Comment by amgalan81mn** [comment]
get sublime idea, treat collapsed "..." characters as a character, like
sublime
so i can selection move easier up down just doing dragging and dropping,
cause its now more advanced thing happens to do that now

**Comment by AliShug** [comment]
I also hit this problem.

**Comment by aeschli** [comment]
IMo the problem is with convertModelRangeToViewRange:
https://github.com/microsoft/vscode/blob/4ec6717139357f3e96c51ddd8d5ef601af31f737/src/vs/editor/common/viewModel/splitLinesCollection.ts#L765.

When converting a range both start and end positions are converted to the last visible line.
