### ISSUE TITLE
Column select keybindings seem to conflict in Linux

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4175]
![image](https://cloud.githubusercontent.com/assets/22350/13748787/97281ea2-e9fe-11e5-8898-856b71054802.png)

 :-1:

**Comment by alexandrudima** [comment]
@egamma I will simply not bind them by default on Linux, this is a minefield

**Comment by alexandrudima** [comment]
Dup of #4145

**Comment by egamma** [comment]
:+1:
