### ISSUE TITLE
code --status fails on windows

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#41754]
- open vscode workspace
- code-insiders --status

This the output I get. It works fine on stable.

![image](https://user-images.githubusercontent.com/172399/35053594-db7bf6d6-fbaa-11e7-9b8b-151f78e409bd.png)

![image](https://user-images.githubusercontent.com/172399/35053805-7d8b59c6-fbab-11e7-9a84-6a98c74b39c0.png)

**Comment by dbaeumer** [comment]
I was not able to reproduce this on latest insider
```
Version 1.20.0-insider
Commit 54240a7bd3854fc9e0c07b399683547500a1914e
Date 2018-01-17T05:14:17.405Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Any additional information. When this happens can you add the full json structure to the issue. Looking at the code the only possibility for indexOf on `null` would be not receiving a command line which is very strange and I would like to understand why this is happening before I add a if :-)

**Comment by bpasero** [comment]
@dbaeumer I also got this on Windows just now and it looks like [`cleanUNCPrefix` ](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/ps.ts#L150) might get undefined or null as value?

**Comment by bpasero** [comment]
One thing I did is I ran "code --status" using our EXE directly and not our CMD file, that might have an impact?

**Comment by dbaeumer** [comment]
@bpasero this was my analysis as well: see https://github.com/Microsoft/vscode/issues/41754#issuecomment-358578385

The problem is that this can only happen if the command line is not existing and this can actually not happen with any VS Code processes. So I was curious why this happens. Can you reproduce?

**Comment by bpasero** [comment]
@dbaeumer tried again and now I cannot reproduce.
