### ISSUE TITLE
Define locale extension point for language pack contributions

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#41752]
Ref: #39178

Proposal:

```json
"contributes": {
        "localizations": [
            {
                "languageId": "br",
                "languageName": "Brasil",
                "translations": "translations"
            }
        ]
}
```

- Implement intelli-sense in language file

CC: @dbaeumer  @aeschli

**Comment by sandy081** [comment]
@aeschli @dbaeumer Updated the extension point as we discussed. 

@dbaeumer Changed the `path` property in the language packs cache file to `translations`.

**Comment by dbaeumer** [comment]
@sandy081 is this in latest insider ?

**Comment by sandy081** [comment]
@dbaeumer Yes :)
