### ISSUE TITLE
Allow to open an integrated terminal as administrator

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41753]
Extracted from https://github.com/Microsoft/vscode/issues/22803

**Comment by Tyriar** [comment]
@bpasero fyi this been brought up before https://github.com/Microsoft/vscode/issues/7407#issuecomment-224798714

**Comment by bpasero** [comment]
@Tyriar nice, should we maybe document this?

**Comment by Tyriar** [comment]
Already mentioned in https://code.visualstudio.com/docs/editor/integrated-terminal#_windows
