### ISSUE TITLE
multi target debugging restart removes from dropdown (golang)

### ISSUE THREAD

**Issue by ptou** [Microsoft/vscode#41756]
- VSCode Version: 1.19.2 (490ef76)
- OS Version: Fedora 26
- `# uname -a`
`Linux hostname 4.14.11-200.fc26.x86_64 #1 SMP Wed Jan 3 13:58:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Steps to Reproduce:

1. Debug `target1`
2. Debug `target2`
3. With `target2` selected, Restart (toolbox, menu, or keys)
4. Observe only `target1` remaining
4a. Even though `target2` is actually running.
5. Attempt to "start debugging" of `target2` does nothing. (Since `target2` is actually already running)
6. Need to hit "Stop" twice to end debugging.

In step 3, it does not matter which `targetN` is the one restarting, that's the one that will "dissappear".

Does this issue occur when all extensions are disabled?: N/A
Golang, so "`debug type 'go' is not supported` without extensions.

**Comment by isidorn** [comment]
This works as expected for me. I might be related to how Go is handling restart, forwarding to @ramya-rao-a 
@ptou do you see this for any go programs you debug? Do you do something differently than me in this gif?

![tworestart](https://user-images.githubusercontent.com/1926584/35093513-db4a3ba8-fc42-11e7-837a-415da1e17740.gif)

**Comment by ptou** [comment]
> do you see this for any go programs you debug? Do you do something differently than me in this gif?
Correct on both accounts.
I see this with any go (extension: lukehoban 0.6.73).  Upon restart, the dropdown still exists, but there is only one entry: the one that was not restarted.

Also, even though there is only one dropdown, _showing_ the "Second", the debug bar actions are against the restarted "First".  i.e. if I hit restart or stop, it is the restarted "first" that is restarted/stopped even though the dropdown shows the single item of "Second".

**Comment by isidorn** [comment]
@ptou if you have the time can you also please try this using the latest vscode insiders
https://code.visualstudio.com/insiders/

**Comment by ptou** [comment]
![image](https://user-images.githubusercontent.com/5247146/35106695-8274e6c6-fc34-11e7-8561-e829177eba8d.png)
`code-insiders-1.20.0-1516256474.el7.x86_64.rpm` w/ `lukehoban.go0.6.73`
Same effect.

**Comment by isidorn** [comment]
@ptou thanks for trying out. If you have more time you can try it with setting up two simple javascript samples. You can debug them by just pressing F5 in a new folder. Here's a snippet
`console.log('hey there')`

@ramya-rao-a can you please tryout with go, My guess is there is something wrong there regarding the restart functinoality.

**Comment by ptou** [comment]
Confirmed works as expected with python.
![image](https://user-images.githubusercontent.com/5247146/35108516-688228e6-fc39-11e7-9631-3737866209fd.png)

**Comment by isidorn** [comment]
@ptou thanks, then it seems to be a go issue.

**Comment by ramya-rao-a** [comment]
@ptou The below are the details of the setup I used

- Opened VS Code with the folders `hello` and `outlet` from https://github.com/golang/example/ in multi-root set-up
- Created the below debug config in both folders
```
{
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}",
            "showLog": true
}
```
- Added breakpoints at https://github.com/golang/example/blob/master/hello/hello.go#L26 and https://github.com/golang/example/blob/master/outyet/main.go#L110
- Started debugging the `outyet` program
- Started debugging the `hello` program
- When breakpoint was hit in `hello`, pressed the "restart" button
   - `hello` disappears for a second and re-appears
   -  In Windows, it took a few seconds, but it did re-appear

![multi-target](https://user-images.githubusercontent.com/16890566/35169982-703cbb16-fd13-11e7-83a1-56a2c2d010e6.gif)

**Comment by ptou** [comment]
![image](https://user-images.githubusercontent.com/5247146/35680976-94e18b5a-0721-11e8-8124-577628cd4c97.png)
> Created the below debug config in both folders
I created config in both folders, and "outyet" is not a valid debug target.
![image](https://user-images.githubusercontent.com/5247146/35681061-dedab63c-0721-11e8-9441-11c68866ee78.png)
