### ISSUE TITLE
Provide possibility to use [taskRunner].autoDetect option in workspace or folder settings

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#41758]
_From @AlexAkhremenko on January 17, 2018 11:53_

I set
```
"settings": {
  "gulp.autoDetect": "off",
  "npm.autoDetect": "off"
}
```
in workspace settings and still see these detected tasks.
Also, in this way I don't see any tasks from my tasks.json.

_Copied from original issue: Microsoft/vscode-docs#1355_

**Comment by dbaeumer** [comment]
Auto detection in global to a workspace. So it can't be disabled per file type since it is not bound to a file type. 

I am closing the issue since I don't understand how this should work per file / language mode. Please provide an example if you still think this request is reasonable.

**Comment by AlexAkhremenko** [comment]
What do you mean 'disabled per file type'? I repeat, I request to include these options into workspace settings. When I set these options in the workspace settings, I still saw autodetected tasks.

**Comment by dbaeumer** [comment]
I looked at the code the the settings are correctlz defined as resource settings so you should be able to disable them in the workspace settings. Need to test and see why this might fail.

**Comment by AlexAkhremenko** [comment]
I have checked again and now it works well. Also my defined tasks work too.

**Comment by dbaeumer** [comment]
OK. Closing the issue then.
