### ISSUE TITLE
Allow me to disable project-wide auto-save when running a build task

### ISSUE THREAD

**Issue by axefrog** [microsoft/vscode#41764]
- VSCode Version: 1.19.2
- OS Version: Windows 10

I have a large project with about ten sub-project folders (some TypeScript, some JavaScript) and often have numerous files from different sub-projects open in various states of non-completion. I have a few tasks configured for building each of the TypeScript projects when I need to. I'll then make an edit to one of those projects and want to build it so that it becomes available to the other projects, but the act of calling that build task causes all open files to be saved, regardless of whether they're relevant to the build, or whether I actually wanted to save them yet.

The main place where this causes an issue is in projects where I'm running webpack-dev-server (or some other watch process), which reloads the page when it detects changes. I'll be in the process of writing some JavaScript code and realise I need a small change to one of my TypeScript projects in order to complete my edits. If I save prematurely, my webpack project will reload and display errors. VS Code's hot-exit feature keeps my unsaved code safe for the moment, so declining to save just yet is fine. I want to be able to modify and build the relevant TypeScript sub-project and then continue the edits I was making to my webpack project, and *then* hit save when I'm ready. Unfortunately building the TypeScript project forces all files across the entire project to save, which causes my local dev server to reload the page and display errors before I was able to complete my changes.

I have looked for a setting related to this, and all I can find is the general auto-save setting, which doesn't seem to be related to build-related auto-saving.

**Comment by alexr00** [comment]
We now classify build related auto saving the same as other autosaving.
