### ISSUE TITLE
Don't steal file associations upon install

### ISSUE THREAD

**Issue by craigmaslowski** [Microsoft/vscode#41768]
I installed VS Code to test it out. During install, it stole all file associations and configured itself as the default application for a number of file extensions. This is time consuming to undo. This should be an opt in feature rather than a default. 

- VSCode Version: 1.19.2
- MacOs Sierra

Steps to Reproduce:

1. Install VS Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Code tells the OS _hey, I can open these file types_. If you don't have any other application which is suited to open those file types, then I guess macOS will set Code to open them. But we're not stealing anything. There is no way to do that.

**Comment by craigmaslowski** [comment]
Then why were file types that were assigned to Atom were reassigned to Code after install.
