### ISSUE TITLE
Scrolling not working in Open Dialog

### ISSUE THREAD

**Issue by tmquinn** [Microsoft/vscode#41760]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.7
vscode-eslint|dba|1.4.4
gitlens|eam|7.5.3
prettier-vscode|esb|1.1.2
vscode-sort-json|ric|1.10.2
code-spell-checker|str|1.6.2

---

Steps to Reproduce:

1. File > Open...
2. Try to scroll with middle mouse wheel or by clicking scroll gutter

Expected:
Stuff Scrolls

Actual:
No Scrolling for you!

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@tmquinn do you mean scrolling in this dialog:

![image](https://user-images.githubusercontent.com/900690/38080178-05efbf92-3341-11e8-8f3f-d793f3495533.png)

?
