### ISSUE TITLE
Column selection does not cover folded text

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4176]
testing #4092
OS: Linux

- fold some text
- select columns across the folded text
- expand the folded regions
Observe: no columns selected in expanded text

This behavior is different (inconsistent) from normal text selection mode.

**Comment by alexandrudima** [comment]
This is a limitation of the implementation. We implement column selection different than Visual Studio. 

The conceptual "rectangular selection" is there when doing column select commands, but it is not a built-in concept, instead the "rectangular selection" gets "projected" on the visible lines.

Once it is projected, it is not "re-projected" when edits occur (e.g. file changes on disk), when tab size changes (e.g. configuration change), when folded regions are unfolded, etc.
