### ISSUE TITLE
Add option to ignore all notification messages from an extension

### ISSUE THREAD

**Issue by fandy** [microsoft/vscode#41767]
Sometimes a plugin is broken but you don't want to spend the time to dig into it. It would be great if we could disable notifications from popping up with a user preference setting.

**Comment by NatoBoram** [comment]
Now that would've been a wonderful solution to https://github.com/bmewburn/vscode-intelephense/issues/615.

**Comment by SteveBenz** [comment]
Perhaps another way to approach this would be to show which extension originated the notification - perhaps even have a direct link from the notification to the extension's notification-related settings.

Bad actors can be blamed and uninstalled.  Well-intentioned extensions that misunderstand their customers desires can avoid people rage-quitting.

**Comment by nikitavoloboev** [comment]
Please address this issue. I am coming from widely used ESLint VSCode extension which throws a notification whenever you open ANY JS project. And the maintainer of the extension @dbaeumer said that he won't address this issue directly. It's very annoying.

**Comment by kaiserdan** [comment]
It doesn't have to be a sophisticated notification management interface like on Windows or macOS. Already being able to "mute" extension popups/notifications with a simple entry in the settings.json would solve the problem.

**Comment by kenny1983** [comment]
I am also 2000% in favour of this feature. I love VS Code but if it keeps allowing this popular trend that everything follows nowadays (i.e. software devs thinking their users would like to be nagged incessantly about every little thing and spammed with marketing crap) then I will stop using it, as @skuester said above.

**Comment by NatoBoram** [comment]
@nikitavoloboev It would be certainly better if I could answer you in https://github.com/microsoft/vscode-eslint/issues/727, but @dbaeumer censored that issue, preventing anyone from commenting with a solution to this problem.

I think the best workaround right now is to disable the extension globally and only enable it in a project that uses it.

**Comment by steveberdy** [comment]
+1

I'm using the C# extension, and as I'm building and contributing to [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers), I get dozens of popups from OmniSharp, which is very disruptive.

![image](https://user-images.githubusercontent.com/86739818/126804767-ac57d1d9-2d3f-4e3e-bac3-88db6b095808.png)

**Comment by wilsonthedrunk** [comment]
+1

I have to dismiss the toast popup on a failed unit test before I can scroll to the error in the output terminal.  This happens every run.

**Comment by perigoso** [comment]
Why must the notifications pop-up? 99% of the time i dont care about it, can they not just show up as a little icon?
![image](https://user-images.githubusercontent.com/39195157/146922897-d4a8b9dd-df1f-42eb-9b81-aca3117f4e82.png)
The notifications right now are extremely annoying

**Comment by perigoso** [comment]
I made a patch that disables all pop ups in the workbench CSS, because MS doesnt care, and the pop ups are p*ssing me off
it's for archlinux, but the patch can probably be used anywhere its just a regex
https://aur.archlinux.org/packages/code-hide-notifications/

**Comment by russeg** [comment]
holy, i have to disable an extension because of this.

is there an unsurmountable technical reason why this feature cannot be implemented? surely this is not that hard, correct?

**Comment by perigoso** [comment]
it wont be because they dont care, but yeah it should be a "15 minute job"

**Comment by ffactory-ofcl** [comment]
+1 to this. The Elmtooling extension https://marketplace.visualstudio.com/items?itemName=Elmtooling.elm-ls-vscode shows a popup every time you save a file while it contains an error - which happens all the time and shouldn't warrant a notification.

**Comment by syntaxbliss** [comment]
+1. Can't believe there's no way to disable notifications per extension, some of them are terribly annoying.

**Comment by moalamri** [comment]
+1 I need a way to disable notifications for specific extension

**Comment by Asef00** [comment]
+1 GitHub Copilot is killing me with the `Your Copilot experience is not fully configured` message on each space, new line, tab,...

**Comment by cagils** [comment]
> Go to the extension source and look for notifications’ API, mostly “showErrorMessage” or “showWarningMessage” , annotate that code and it will stop showing notifications until the next update of that extension

Thanks for that. I edited out the 'showInformationMessage' for my offending extension (Random Theme Switcher). Since I use WSL remotes, I needed to change it from the WSL .vscode-server/extensions folder (extension was present in both host and remote directories).

**Comment by sweedheart** [comment]
Real showstopper for vscode. Tried switching from PHPStorm, but this is so annoying and as always: new features are more important than addressing issues that are open > 4 years. Reminds me of some other companies in that sector: Atlassian etc. Oh, this is Microsoft. Wonder why that is working at all...

**Comment by marcodallagatta** [comment]
Bump for this, it's been almost 5 years since the issue has been opened.

**Comment by waynebloss** [comment]
Every time eslint can't load a config this is soooo annoying. What's the holdup?

**Comment by perigoso** [comment]
there's no holdup, they just don't care

**Comment by Lippiece** [comment]
Bump

**Comment by diminutivesloop** [comment]
This would be helpful for suppressing errors from extensions such as [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) which throw errors when merge conflicts show up in config files that they parse such as `package.json`. It would be even better if specific error notifications could be suppressed, but even just ignoring by extension would be a help.

**Comment by moalamri** [comment]
What if we inform extension developers to add an option to disable notifications? For me I only have a single extension and I didn't add any notifications nor any menu contexts or statusbar items, I think abusing those places is extremely wrong and developers should know and respect that.

**Comment by devjoda** [comment]
Bump for this 😎

**Comment by steveberdy** [comment]
Maybe we need a bounty for this.

**Comment by steveberdy** [comment]
Again, we need a bounty for this.

**Comment by dephraiim** [comment]
Is there reason why this feature cannot be implemented?

**Comment by dephraiim** [comment]
Is there reason why this feature cannot be implemented?

**Comment by chenyukang** [comment]
+1 
5 years now still can not be implemented?

**Comment by robclancy** [comment]
Here's to another 5 🍻

**Comment by daviddossett** [comment]
Closing given that we added the Do Not Disturb mode via https://github.com/microsoft/vscode/pull/149645 in the June release.

**Comment by Lippiece** [comment]
> Closing given that we added the Do Not Disturb mode via #149645 in the June release.

@daviddossett, I'm sorry, but wasn't the problem in ignoring a specific extension's notifications and not all of them?

**Comment by robclancy** [comment]
Hahaha wtf. now someone needs to make a new issue to start the 5 year process again

**Comment by perigoso** [comment]
I'll take this, honestly, close enough

**Comment by NatoBoram** [comment]
Some extensions might provide important information that you may want to see as soon as it's given. A Do Not Disturb mode doesn't solve anything. Not only that, but the effort on Do Not Disturb is kinda wasted since being able to mute a specific extension's spam would have the same effect, but better.

**Comment by Lippiece** [comment]
@daviddossett Seriously wtf, everybody's been waiting for something to happen 5 fucking years and now you just close the issue?

**Comment by waynebloss** [comment]
See also microsoft/vscode-eslint#1238

**Comment by daviddossett** [comment]
Apologies all, I was closing a few of these related issues at once and misunderstood that this is about suppressing a single extension's notifications.

**Comment by astier** [comment]
I would like to note that it would be great not only to be able to disable notifications from extensions but from vscode itself. I personally disable the menu-bar because I don't need it for the most part. If I need the menu-bar I toggle it, do my work with it and toggle it again to hide it. Each time I hide it vscode informs me that `You can still access the menu bar by pressing the Alt-key`. First of all thats wrong because I set `enableMenuBarMnemonics` to `false`. Second I don't want to see this message every time.

**Comment by TomasTillmann** [comment]
> +1
> 
> I'm using the C# extension, and as I'm building dotnet projects, I get dozens of popups from OmniSharp, which is very disruptive.
> 
> ![image](https://user-images.githubusercontent.com/86739818/126804767-ac57d1d9-2d3f-4e3e-bac3-88db6b095808.png)

For those who might need to solve this specific case, omnisharp has this option:  `"omnisharp.disableMSBuildDiagnosticWarning": true` which disables this specific annoying warning message. Just put it into settings.json.

**Comment by ppoliani** [comment]
It's quite hard to comprehend the reasons why this feature has not been implemented yet. I'm sure there must be some reasons but they have not been conveyed properly.

In the meantime one the way I dealt with this is by changing a couple of line in the css. Unfortunately, the notifications messages are so annoying that they go against dev productivity.

For anyone interested, I added the following lines to the workbench css (on Mac it's `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css`)

```css
.notifications-toasts {
  display: None !important;
}
```

I wish this feature lands soon so we don't have to manually change the source code to make it work.

**Comment by matter-it-does** [comment]
@ppoliani  Doesn't that invalidate the gatekeeper checks about codesign
Also does this persist after vscode updates?

**Comment by codeams** [comment]
I had to go with custom css as well, using
https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css

**Comment by gardner** [comment]
VSCode throws up too many notifications. I don't want to break my focus and pay attention to a notification that I don't care about. Please consider non-intrusive notifications. One idea would be to have a small notification indicator that expands a notification window when clicked.

**Comment by NatoBoram** [comment]
@gardner That's what do-not-disturb does. This issue is specifically about muting an entire extension from the notification system.

**Comment by thelittleerik** [comment]
How the f is this still not addressed? 

Why is this issue open for 5 years? 
What's needed to be done? 

Intellephense is begging for donations in every goddamn week. 
I don't want their premium and take a NO, once for an answer.

**Comment by codeams** [comment]
Install a plug-in to edit the IDE code like Custom CSS and JS (and a checksum fixer).

VSCode doesn't care about minimal or clean.

It's not worth waiting for something they've shown they don't care to invest in.

**Comment by zardoy** [comment]
> Install a plug-in to edit the IDE code like Custom CSS and JS (and a checksum fixer).

Yeah, there is a [way](https://marketplace.visualstudio.com/items?itemName=zardoy.extensions-control) to ignore messages from extensions by specifying message regex / severity or extension id for a long time, but it invoves vscode patching... though I think it will continue to be more powerful than builtin solution?

**Comment by codeams** [comment]
> Hey folks, I did a quick exploration in the July iteration to see how we might handle this. The basic idea:
> 
> * Turn off notifications from a specific source (e.g. an extension or a specific category of built-in notifications) right from a notification itself.
> * Manage notifications per source via a menu from the notification center
> 
> It could look like something like this. Thoughts?
> 
>  CleanShot.2023-08-03.at.09.41.24.mp4

That looks perfect!
Would the on/off flags be included in the settings sync?

**Comment by IanMatthewHuff** [comment]
Just wanted to bring in some quick comments here on this issue from the VS Code Edu team.

We're looking for a solution where we can block all notifications except those provided by a set of extensions that we specify in settings. Our scenario involves student learners, and any notifications that they get can be distracting to their focus. For something like our python course, we would want to specify our own extension and perhaps something like the Pylance extension to be the only things that could show notifications. So this would be an allowlist (instead of a block list) and it would be in settings so that we could change it on a per course basis.

Would be a very helpful feature to us if it makes it into an iteration soon. Thanks!
https://github.com/microsoft/vscode-edu-extension/issues/578

**Comment by itpropro** [comment]
Any updates on this @daviddossett ?

**Comment by exxocism** [comment]
https://github.com/microsoft/vscode/issues/41767#issuecomment-1664306693
That's so cool man

**Comment by bpasero** [comment]
Made the changes as suggested in https://github.com/microsoft/vscode/issues/41767#issuecomment-1664306693 by @daviddossett to allow for disabling notifications by extension:

![Recording 2023-12-19 at 11 36 09](https://github.com/microsoft/vscode/assets/900690/063f739b-ca61-403f-bf93-4230deff667c)

This behaves exactly like our existing "Do not disturb" mode but allows for more fine grained control. Notifications of `Error` severity will always show (same as with the global DND mode).

**Comment by Screenfeed** [comment]
Thanks 👍 
Now all we need is to be able to mute notifications of `Error` severity and we're good.

**Comment by bpasero** [comment]
This can now be used from our insider builds:  https://code.visualstudio.com/insiders/

**Comment by IanMatthewHuff** [comment]
@bpasero and @daviddossett . Quick question on the implementation here. Is this configurable from a setting? Or only via the notification dialog? For the vscode for education scenario we are looking to turn off confusing notifications that students are running into and preconfigure that in the student profile. However after playing with turning off notifications for an extension locally I wasn't seeing the value persisted either in the settings or in the globalState.json, so I'm not sure if we could pre-configure this.

**Comment by LiamMorrow** [comment]
> This behaves exactly like our existing "Do not disturb" mode but allows for more fine grained control. Notifications of Error severity will always show (same as with the global DND mode).

Are there any plans to every allow us to disable error notifications?  The dotnet extension has been broken for months now with blazor apps, and spews out so many error notifications.  I still want the extension overall, but it is super distracting getting hammered with notifications I cannot disable without going into devtools to temporarily hide all notifications.

**Comment by zardoy** [comment]
> Are there any plans to ever allow us to disable error notifications?

There is seems to be logical reason for not letting you hide errors as error notifications should always be fixed. However you can still use extension like from https://github.com/microsoft/vscode/issues/41767#issuecomment-1644937214 to hide whatever you want (and my guess was right). As Jakub mentioned its possible to hide errors from PowerShell extension, so I think it would also be possible to solve your case as well. Anyway, I still personally don't understand what was the point of making it machine specific (even profile specific)? this is simply annoying...

**Comment by bpasero** [comment]
This feature is closely modelled after how our global "Do not disturb mode" works:
* only Info and Warning notifications can be ignored
* we store this state in storage and not settings

If you have interest in anything else, please open separate issues, thanks!

**Comment by arthniwa** [comment]
I also want to be able to to hide error notifications. Sometimes I deliberately change the code and see if it triggers an error. These popup notifications are very unpleasant to look at. It would also be nice to incorporate this within the extension settings.
