### ISSUE TITLE
Get the type of code at a position?

### ISSUE THREAD

**Issue by APerricone** [Microsoft/vscode#41766]
This request is similar to #580 , 
I think it is enough see if the code at a position is a string, a number, a keyword, a definition, a space, a comment and get the start and the end of this "type".
It is not necessary know all TextMate scope, only the type of code...

**Comment by jrieken** [comment]
closing as duplicate as the *only* types we store are those you are suggesting.

**Comment by APerricone** [comment]
Wow, you answered in no time :1st_place_medal: 
I would like to create an extension for string manipulation, but there is no way to see if the code is string or not.
