### ISSUE TITLE
Windows 10 "how do you want to open this file?" dialog with new icon - icon almost invisible.

### ISSUE THREAD

**Issue by wpostma** [Microsoft/vscode#41761]
- VSCode Version:  1.19.2
- OS Version: Windows 10 (fall creators update)

Steps to Reproduce:

1.  Right click on a file in Windows explorer that you want to have associated with Visual Studio Code.
2. Click Open With.
3. Look visually for the visual studio code icon.
4. Notice that the icon being all blue, conflicts with the Windows 10 designer's choice to force a background color of blue, and a highlight color of blue, on you when you use windows 10 ui.

While I hate to bring up the icon thing AGAIN, I would like it if someone at Microsoft could talk to someone else at microsoft and note that:   

A.  The Windows 10 UI designers in their INFINITE WISDOM have decided that NOBODY does all blue icons, because they've chosen to color all icons with a blue background where the icon itself is transparent.

B.  The Visual Studio Code designers in their similarly infinite WISDOM have decided that nobody better use blue as their selection bar color (hint: everyone on windows does, all the time).

Not tryna start a holy war, just advocating for people with less than 20-20 vision who might not be able to see this icon at  all:
![image](https://user-images.githubusercontent.com/1833470/35058097-c7689238-fb6b-11e7-9a4a-ab82c9c98bf2.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by wpostma** [comment]
Incidentally I loved the little orange fish icon. So there all you haters.

**Comment by bpasero** [comment]
Uninstall -> Reinstall should fix this.
