### ISSUE TITLE
Have to press esc twice to close environment quickpick

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41778]
- Open .js file, no launch.json present
- Press F5
- See environment quick pick
- Press esc
- Quick pick blinks
- Press esc again

![image](https://user-images.githubusercontent.com/323878/35073877-e9a180f6-fb9f-11e7-9a10-de06cafae020.png)

**Comment by joaomoreno** [comment]
When I press F5, it just start debugging. How to get the environment quick pick?

**Comment by isidorn** [comment]
@joaomoreno install chrome extension so I can not pick which adapter to use for javascript.
Or hit F5 on some language which is not javascript
