### ISSUE TITLE
Multi-cursor shortcuts mostly don't work

### ISSUE THREAD

**Issue by grdoor** [Microsoft/vscode#41771]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.3.2
xml|Dot|1.9.2
EditorConfig|Edi|0.11.1
auto-close-tag|for|0.5.5
mssql|ms-|1.3.0
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
qub-msbuild|qub|0.6.3
vscode-icons|rob|7.19.0
vscode-hexdump|sle|1.6.0

---

Steps to Reproduce:

1. Help -> Welcome, click on the interactive playground
2. The first playground box is Multi-Cursor editing
3. Try box selection shortcuts
ctrl+shift+alt+[Up|Down|Left|Right]arrow shortcuts do nothing: the cursor doesn't move.
Shift+Alt + drag w/mouse just selects as usual, no box select.
Ctrl+Alt+[Up|down]Arrow does nothing. Cursor doesn't move, no cursors added.
Ctrl+click _does_ work.
Ctrl+Shift}L _does_ work.
Shift+Alt+[Up|Down]Arrow _does_ work.

I am using VSCode through an MSTSC remote desktop connection.

Reproduces without extensions: Yes [No change in observed behavior from what's described above]

**Comment by alexandrudima** [comment]
Two likely causes:
* either you unwillingly changed the setting `"editor.multiCursorModifier"`
* the software you are using is not forwarding the keys/modifier combinations.

Have you been successful in using these gestures in other software on that machine you are connecting to ? i.e. are you sure this is a problem with VS Code ?

**Comment by grdoor** [comment]
I've worked around by updating the keyboard shortcut to just alt+shift rather than ctrl+alt+shift. That seems to work. Most likely issue is probably RDP failing to forward the full keyboard chord. I'll close this unless I repro it on another box w/o the RDP intermediary (which, after further experimentation, is what I've decided to blame as well).
