### ISSUE TITLE
'Auto detecting the task system failed' can be more user friendly

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4177]
Related to #4019

Steps to Reproduce:

1. have a broken `gulpfile.js`
2. generate task runner > choose gulp
3. Notice the error
4. This should be a warning, not an error
5. There should be an action to open the output service, task channel to make it easier for the user to locate the error

![screen shot 2016-03-14 at 16 13 23](https://cloud.githubusercontent.com/assets/1926584/13749028/edb554e6-e9ff-11e5-8393-e72e5cc6a121.png)

**Comment by dbaeumer** [comment]
Agree. But instead of an action we should automatically open the output. Setting to March to investigate. Might move to April since this is not a regression.

**Comment by isidorn** [comment]
Nice!
