### ISSUE TITLE
Multiroot workspaces and problemMatcher - how do I configure a build task to run relative to the target folder?

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#41780]
- VSCode Version: 1.19.2
- OS Version: Windows 10

For the life of me I cannot get VS Code to build my TypeScript projects relative to their own folder in my multiroot workspace so that the problemMatcher will open files correctly when they are clicked in the problems panel. Instead, the project keeps building relative to the entire multiroot workspace, as evidenced by the TypeScript compiler error paths being displayed in the terminal output (see further below).

I do not want to use chains of `${workspaceFolder}../../../` just to get the problemMatcher to work properly, because the workspace involves multiple separate repositories, and if I commit the tasks.json file to the repository with parent paths relevant only to my personal setup, somebody else might unsuccessfully try to build the project with the task path incorrectly configured for their setup.

Seeing as pictures are worth a thousand words, here is my folder structure:

![image](https://user-images.githubusercontent.com/298883/35075196-6bf645e4-fc3d-11e7-8672-a83b93d75cc4.png)

Here's the workspace configuration:

```json
{
	"folders": [
		{
			"path": "."
		},
		{
			"name": "@frptools/corelib",
			"path": "projects\\corelib"
		},
		{
			"name": "@frptools/structural",
			"path": "projects\\structural"
		},
		{
			"name": "@frptools/streams",
			"path": "projects\\streams"
		},
		{
			"path": "projects\\collectable"
		},
		{
			"name": "@collectable (aggregate package)",
			"path": "projects\\collectable\\packages\\collectable"
		},
		{
			"name": "@collectable/core",
			"path": "projects\\collectable\\packages\\core"
		},
		{
			"name": "@collectable/list",
			"path": "projects\\collectable\\packages\\list"
		},
		{
			"name": "@collectable/red-black-tree",
			"path": "projects\\collectable\\packages\\red-black-tree"
		},
		{
			"name": "@collectable/map",
			"path": "projects\\collectable\\packages\\map"
		},
		{
			"name": "@collectable/set",
			"path": "projects\\collectable\\packages\\set"
		},
		{
			"name": "@collectable/sorted-map",
			"path": "projects\\collectable\\packages\\sorted-map"
		},
		{
			"name": "@collectable/sorted-set",
			"path": "projects\\collectable\\packages\\sorted-set"
		}
	],
	"settings": {
		"typescript.tsdk": "node_modules/typescript/lib",
		"typescript.referencesCodeLens.enabled": false,
		"typescript.implementationsCodeLens.enabled": false,
		"window.menuBarVisibility": "toggle",
		"git.ignoreLimitWarning": true,
	}
}
```

Here is what's in the project I'm building:

![image](https://user-images.githubusercontent.com/298883/35075243-b99bdb06-fc3d-11e7-9f17-38b29d03466d.png)

Here is the task I'm trying to run:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "@collectable/list (watch)",
      "group": "build",
      "type": "typescript",
      "tsconfig": "@collectable\\list\\tsconfig.json",
      "option": "watch",
      "problemMatcher": "$tsc-watch"
    }
  ],
  "options": {
    "cwd": "${workspaceRoot}"
  }
}
```

The `options` property above has only been introduced in the process of trying different possible solutions, to no avail.

Here's the error:

![image](https://user-images.githubusercontent.com/298883/35075425-a801474a-fc3e-11e7-8bb6-f883c9d63063.png)

Here's the embedded terminal output:

```
> Executing task in folder @collectable/list: tsc --watch -p "d:\Dropbox\Work\Dev\frptools\projects\collectable\packages\list\tsconfig.json" <


Ready.

frptools/projects/collectable/packages/list/src/functions/append.ts(1,37): error TS2307: Cannot find module '@collectable/core'.
frptools/projects/collectable/packages/list/src/functions/append.ts(2,19): error TS2307: Cannot find module '../internals/_dev'.
frptools/projects/collectable/packages/list/src/functions/concat.ts(1,23): error TS2307: Cannot find module '../internals/_dev'.
frptools/projects/collectable/packages/list/src/functions/concat.ts(2,30): error TS2307: Cannot find module '@collectable/core'.
frptools/projects/collectable/packages/list/src/functions/empty.ts(1,25): error TS2307: Cannot find module '@collectable/core'.

... and so on ...
```

For the problemMatcher, I have tried:

```json
{ "base": "$tsc-watch", "fileLocation": ["relative"] }
{ "base": "$tsc-watch", "fileLocation": ["relative", "${workspaceRoot}"] }
{ "base": "$tsc-watch", "fileLocation": ["relative", "${workspaceFolder}"] }
{ "base": "$tsc-watch", "fileLocation": ["relative", "@collectable\\list"] }
```

Is there a solution to this, or is this something that has not yet been implemented properly for multiroot workspaces?

**Comment by dbaeumer** [comment]
This works for me in a test workspace with two folders. I have attached a zip demoing this. Is there anything special with your setup. Can you provide me with a GitHub repository I can clone that demos what you are seeing. 

@mjbvz what is strange is that the tasks.json refers to the tsconfig.json having the folder name in it. Since the tasks.json is scoped to the folder why do you add the folder name. Could this cause problems?

**Comment by dbaeumer** [comment]
[41780.zip](https://github.com/Microsoft/vscode/files/1645847/41780.zip)

**Comment by dbaeumer** [comment]
Reopening. @mjbvz can you please comment?

**Comment by axefrog** [comment]
@dbaeumer Sorry for the slow reply. Your test setup didn't really replicate the conditions I described. You'll note that I have a projects folder and that those projects have deep subfolders of their own, and that I'm referencing some of those in the workspace, rather than only the workspace's direct child folders. The names of the workspace folders have also been manually added in order to relate the subfolders to scoped npm package names represented by each respective folder.

**Comment by dbaeumer** [comment]
@axefrog without being able to reproduce this it is hard to fix :-)
