### ISSUE TITLE
`outputChannel.clear()` is not working when a channel is not displayed

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#41788]
- VSCode Version: Version 1.20.0-insider (1.20.0-insider) b811600ecc57992a82a1f50ed9bf128065bc8787
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Create an output channel and a command to write something to it:
```javascript
    const outputChannel = window.createOutputChannel('Test');
    vscode.commands.registerCommand(`test.command`, () => {
      outputChannel.clear();
      outputChannel.append('1\n2\n3'); // should print exactly 3 lines
    });
```
**package.json**
```javascript
"contributes": {
		"commands": [
			{
				"command": "test.command",
				"title": "Write to Test output channel"
			}
		]
	},
...
```
2. Launch the command a few times **while the output channel is not displayed** (when some other output channel is displayed).
3. Open the output channel and observe an unexpected input (duplicated results or partially cleaned).

![vsc](https://user-images.githubusercontent.com/979966/35080643-9b383e58-fc5a-11e7-9296-64ca1bd6bcfe.gif)

The same code is working as expected in v1.19 and also when the output channel is displayed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@ArtemGovorov Great catch. Fixed.
