### ISSUE TITLE
gulp fails to run on windows if terminal is setted to bash...

### ISSUE THREAD

**Issue by heartoneto** [Microsoft/vscode#41787]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|hbe|0.17.0

---

> Executing task: node_modules\.bin\gulp.cmd compileForJest <

/usr/bin/bash: node_modules.bingulp.cmd: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.

Steps to Reproduce:

1. Set the terminal to bash: "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
2. Run any gulp task 

This is the tasks.json contents, i'm using the first task as a workaround: 
        {
            "label": "build",
            "type": "shell",
            "command": "gulp",
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "type": "gulp",
            "task": "compileForJest",
        }

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36216
