### ISSUE TITLE
Expose theme colors to webview via css variables

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#41785]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (54240a7bd3854fc9e0c07b399683547500a1914e, 2018-01-17T05:14:17.405Z)</li>
	<li>OS Version: Windows_NT x64 10.0.17074</li>
</ul>

Currently only a couple theme colors are exposed to webviews via css variables, I would like to have access to a full set of theme colors (at least the workbench based ones).

**Comment by benrr101** [comment]
Currently I'm ~~stealing~~borrowing some code from the gitlens extension, which does a decent job of adding various shades of the colors. It's not a perfect solution, but it's a decent workaround for me.

https://github.com/eamodio/vscode-gitlens/blob/master/src/ui/shared/colors.ts

**Comment by eamodio** [comment]
@mjbvz Looks great -- thanks!
