### ISSUE TITLE
how can I start contributing to resolve errors?

### ISSUE THREAD

**Issue by lohxx** [Microsoft/vscode#41783]
I have cloned the project and run it, but I do not know where to start, do you have any documentation that explains the directories or any part of the application source file?

**Comment by Lisoph** [comment]
Hey @lohxx, have you looked at the ["how to contribute"](https://github.com/Microsoft/vscode/wiki/How-to-Contribute) guide?

Disclaimer: I'm not a vscode developer myself.

**Comment by isidorn** [comment]
@Lisoph thanks that document describes it quite well

**Comment by lohxx** [comment]
@isodorn I have read this document and I have followed all the step-by-step, my doubt is in relation to the code, where do I start in the code? any tips?

**Comment by isidorn** [comment]
@lohxx regarding the code unforunetly we do not have a documenation around the code structure.
Maybe the best place to start is to search issues in this repository which are tagged with help-wanted. Usualy each issue owner possts a code pointer for where it is good to start looking for contributing for that specific issue / feature.

https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+

hope that helps

**Comment by Lisoph** [comment]
@lohxx regarding finding a place to start, what I did when I started developing my own extension, is to look at how other extensions do stuff.

In any way, the `package.js` file of an extension is more or less the root, as I understand it. Things like languages, grammars, keybindings and themes are defined there.

Hope this helps!
