### ISSUE TITLE
Dragging a webview (previewHtml) sometimes won't allow docking like normal editors

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#41786]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (54240a7bd3854fc9e0c07b399683547500a1914e, 2018-01-17T05:14:17.405Z)</li>
	<li>OS Version: Windows_NT x64 10.0.17074</li>
</ul>

---

Steps to Reproduce:

1. Drag a webview tab to move it into a new group
2. Observe that sometimes (often) the drag icon changes from a move cursor to a copy cursor and the dock areas don't work like a normal editor.

Reproduces without extensions: Yes/No

**Comment by eamodio** [comment]
Which issue is this a duplicate of?

**Comment by mjbvz** [comment]
#25856 / #25854 I believe
