### ISSUE TITLE
[settings-editor] searching for symbol or line when search field is focused results in focused search

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#41784]
1. Open settings editor
2. Focus search field
3. `Go to symbol in file` or `Go to line number`
4. Editor scrolled where you wanted to, but focus is still on the search field

I admit, it is possible to access the desired symbol or line with more keyboard actions, but it's not expected from a widget to just scroll and not capture focus for the match.

---

Also works when your focus is in the default editor:
1. Focus default settings
2. `Go to symbol in file` or `Go to line number`
3. Focus remained on the default settings

**Comment by roblourens** [comment]
Now that the settings UI exists, we aren't investing more in the JSON editor
