### ISSUE TITLE
[loc]Request to add Malayalam (ml) language to Transifex VS Code project

### ISSUE THREAD

**Issue by asphub** [Microsoft/vscode#41792]
Request to add Indian language - Malayalam (ml) in VS Code

**Comment by intermediatech** [comment]
Yes.. We should need Malayalam (ml) support.

**Comment by jrieken** [comment]
fyi @dbaeumer

**Comment by danyeh** [comment]
First step is to get translation going in Transifex. So change the title.
We expects three localization contributors to start. Guide here: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by danyeh** [comment]
Language info: https://en.wikipedia.org/wiki/Malayalam

**Comment by Gireesh-SB** [comment]
That would be nice!!

**Comment by anuraj** [comment]
I am interested to participate in Malayalam language localization effort in transifex - anuraj

**Comment by danyeh** [comment]
Now I can identify two Transifex accounts:
https://www.transifex.com/user/profile/asphub/
https://www.transifex.com/user/profile/anuraj/

@intermediatech or @Gireesh-SB , could you please let me know your Transifex account? Thanks!

**Comment by intermediatech** [comment]
@danyeh 
https://www.transifex.com/user/profile/intermedia.vishnu/

**Comment by Gireesh-SB** [comment]
@danyeh  
My Transifex account: https://www.transifex.com/user/profile/Gireesh.SB/

**Comment by danyeh** [comment]
Malayalam (ml) enabled in Transifex for 3 VS Code projects. 
Thank you for contributing!

**Comment by arunshaji95** [comment]
I would like to participate in the translation.
https://www.transifex.com/user/profile/arunshaji95/
