### ISSUE TITLE
[Debug console] Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by Pho3nixHun** [Microsoft/vscode#41796]
- VSCode Version: 
```
Version 1.20.0-insider
Commit 531d713432c82e4ffe341f35d03a461713f96660
Date 2018-01-18T06:16:50.298Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
- OS Version:
Debian 9.2 x64 with Gnome3
Steps to Reproduce:

1. Start remote debugging (NodeJS)
2. Try to enter any command on debug console (You might have to wait a bit or receive a few debug message before you get this warning toast)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by ramon-garcia** [comment]
I have also this bug using latest insiders build

Also using Debian 9, GNOME 3. 

For now, reverted to using non insiders build. Works without trouble.

**Comment by weinand** [comment]
What version of node are you using?

**Comment by Pho3nixHun** [comment]
v6.11.3 on ARM

**Comment by weinand** [comment]
What exactly do you mean by "Start remote debugging (NodeJS)"?

**Comment by weinand** [comment]
Do you see this problem when a debug session is active?

**Comment by weinand** [comment]
@isidorn I can reproduce this in the Insiders when no debug session is active. In Stable we showed "Please start a debug session to evaluate" on the debug console.

**Comment by weinand** [comment]
Actually I can reproduce this even when a debug session is active: if I type an existing variable name in the REPL, its value is returned. If I enter an non-existing value, I get the "Cannot read property 'item' of undefined" message.

**Comment by isidorn** [comment]
Somebody touched the suggest controller which was showing this error, basically doing enter in the repl when no suggestion is available.
Just modified the current null guard has fixed the issue.

fyi @jrieken

**Comment by jrieken** [comment]
Yeah, make sense
