### ISSUE TITLE
Vscode cannot install vetur. 

### ISSUE THREAD

**Issue by fengshenhai-0727** [Microsoft/vscode#41797]
- VSCode Version:
- OS Version:

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/23276885/35088494-f0e588a6-fc6e-11e7-8486-4248670ded89.png)
Open the developer tool and make the following error.
![image](https://user-images.githubusercontent.com/23276885/35088598-3c9427f8-fc6f-11e7-8360-ec0a4f571023.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
@fengshenhai-0727 It seems you do not have permissions to access to the TEMP directory. 

May be you installed VS Code as root user and trying to open it as a normal user who does not have permissions?

**Comment by fengshenhai-0727** [comment]
Impossible，I can install success through vsix.

**Comment by sandy081** [comment]
When you install vsix, we extract it directly into extensions folder. But when you install an extension from gallery, we download the vsix into TEMP directory. This error could be due to when user does not have permissions in that folder.

Please check the permissions for the TEMP directory and try

**Comment by fengshenhai-0727** [comment]
I have set permissions for the directory(/var/folders/qt/qvx921xx3_90rqpxntv_wtbh0000gq/T).
![image](https://user-images.githubusercontent.com/23276885/35133092-4d5b25ba-fd09-11e7-93cf-55fd3b00bf17.png)
![image](https://user-images.githubusercontent.com/23276885/35133066-3680f7a2-fd09-11e7-92d6-a53d83ce4abd.png)
Can you allow vscode to install extensions with root access?

**Comment by sandy081** [comment]
@joaomoreno do we have such requests already?

**Comment by joaomoreno** [comment]
No, Code will never install extensions with root access. A user should always have write access to his configured TEMP variable.

**Comment by zack-lin** [comment]
The same problem to me

**Comment by sandy081** [comment]
Closing this based on [comment](https://github.com/Microsoft/vscode/issues/41797#issuecomment-360063694)
