### ISSUE TITLE
Need support for @-moz-document

### ISSUE THREAD

**Issue by jerrybk108** [Microsoft/vscode#41791]
I see a error is marked for my scss file:
@-moz-document url-prefix()

Could you please support for this case?

Thanks,
Hieu Tran

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
vscode-javascript-snippet-pack|aka|0.1.5
angular1-code-snippets|ale|0.0.3
html-class-suggestions|And|1.0.7
angulardoc-vscode|Ang|3.0.5
jshintrc-generator|ben|1.0.0
git-easy|bib|1.9.1
htmltagwrap|bra|0.0.7
vscode-standard-format|che|0.0.12
vscode-ipaddress|Com|1.0.0
jshint|dba|0.10.15
EditorConfig|Edi|0.11.1
json-tools|eri|1.0.2
auto-rename-tag|for|0.0.15
angular-bootstrap|her|4.0.9
vscode-angular-components-intellisense|ipa|0.7.1
javascript-unit-test-snippet|iZD|1.0.0
autofilename|Jer|0.1.3
svn-scm|joh|1.5.0
ng-bootstrap-snippets|ktr|0.3.0
jscs-formatter|moo|0.1.1
vscode-scss|mrm|0.6.2
jscs|ms-|0.1.9
language-vscode-javascript-angular2|nwa|0.0.11
vscode-html-scss|P-d|0.0.42
datetime|rid|1.0.5
code-settings-sync|Sha|2.8.7
html5-boilerplate|sid|1.0.1
css-auto-prefix|spo|0.1.4
vscode-gulp|tan|0.0.4
lorem-ipsum|Tyr|1.1.0
vscode-angular-support|vis|0.1.4
codeheader|wh0|1.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
This works from me, but you need the curly brackets (using the spec from https://developer.mozilla.org/en-US/docs/Web/CSS/@document):
![image](https://user-images.githubusercontent.com/6461412/35095570-328ab8f6-fc49-11e7-8bd9-ef4a2d7281a3.png)

Is that you complete example? Do you have a better/more complete spec that shows that the body is not required?

**Comment by hieutranagi47** [comment]
Oh, I'm sorry for providing more information late.

My sample code:
```
@mixin ellipsis-text() {
    position: relative;
    text-align: justify;
    text-align-last: left;
    @-moz-document url-prefix() {
        overflow: hidden;
        position: relative;
    }
}
```
![hint-error](https://user-images.githubusercontent.com/15606737/35468273-96e41e10-0355-11e8-80e8-7eb126ede071.png)
You can take a look at the image attachment.
