### ISSUE TITLE
CentOS: Code Alpha doesn't show up in the Application Installer after installation

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4179]
- VSCode Version: 0.10.12-alpha
- OS Version: CentOS6

Steps to Reproduce:

1. Install rpm package using Application Installer
2. Switched to the installed tab

Observe: vscode is not listed. However it is installed successfully.

**Comment by Tyriar** [comment]
My experience with both Unity dash and the gnome dash is that it takes some time to pick up new installations. I'll double check on my instance by removing, reinstalling and restarting if it doesn't show up.

**Comment by Tyriar** [comment]
Reproduced the issue. I have a feeling only packages installed via the application installer GUI through the official repo show up in the list, similar to how launchpad only lets you use some features when installing through the GUI. It's definitely installed (`yum list installed | grep code-alpha`) and can be uninstalled through the command line without issue so I'll close this off (`yum remove code-alpha.x86_64`).
