### ISSUE TITLE
After "Undo all - Redo all", latest code is not restored

### ISSUE THREAD

**Issue by nurp** [Microsoft/vscode#41798]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
Bookmarks|ale|0.18.0
xml|Dot|1.9.2
matlab|Gim|0.8.0
latex-workshop|Jam|3.12.3
Go|luk|0.6.73
MagicPython|mag|1.0.12
python|ms-|0.9.1
cpptools|ms-|0.14.6
vscode-hexdump|sle|1.6.0
python|tht|0.2.3

---

Steps to Reproduce:

1. Undo (ctrl+z) until it can't undo anymore
2. Red (ctrl+shift+z) until it can't redo anymore
3. It will not show your latest edits.

This happened in a .py file and I lost a lot of my edits.
between those edits, I hibernated my laptop, changed network (move between work-home) and I had the same project open also on another vscode window but the project files were at server (not on my local Windows machine where I had this problem). I don't know if it created any confusion. 

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
I have tried, but cannot reproduce. Do you perhaps have more specific steps that would help in reproducing ?

**Comment by nurp** [comment]
I just tried again on a file that I've been editing whole day. I ctrl+z'ed until I can't anymore.
Then pressed ctrl+shift+z to redo but nothing came back. This time I lost all the redo history.
and this time I also opened a project on a unix server. What can I do, log something? So it happens both on local and remote projects. I can try to debug it if you tell me which file to put a breakpoint?

**Comment by alexandrudima** [comment]
@nurp What settings do you have? Do you use auto-save? Do you use an on-save participant that would change the source code? If this reproduces only in a certain file type, it is possible that there is an extension running that might change the text buffer on save. Does this reproduce when you disable extensions ?

**Comment by nurp** [comment]
No, I don't use auto-save.
I had files.trimTrailingWhitespace enabled. now I disabled, let's see. I'll try disabling extensions after this.

**Comment by alexandrudima** [comment]
`files.trimTrailingWhitespace` is something that would modify the buffer on save. Is it possible you have executed `ctrl+z`, `ctrl+z`, ..., `ctrl+s` (with buffer having trailing whitespace) ?

The `ctrl+s` would push edits that would trim trailing whitespace and *drop* your redo stack.
