### ISSUE TITLE
Snippets are not expandable once blurred.

### ISSUE THREAD

**Issue by LAITONEN** [Microsoft/vscode#41809]
**Desired Behavior:**
In Sublime Text, if you type the shortcut of a snippet, move your cursor away and then place it back to the end of the shortcut and click <kbd>Tab</kbd>, it will expand anyway.

**Actual Behavior:**
In VS Code, if you try to perform the same trick, it will either indent the cursor or, if inside the Javascript React file, will expand the shortcut into JSX element. For example, if you have a `clog` shortcut for `console.log()`, it will morph into: `<clog></clog>`.

**Versions:**

- VSCode Version: 1.19.2
- OS Version: macOS Sierra 10.12.4

**Steps to Reproduce:**
This was tested with Javascript and Javascript React Language Modes.
1. Create a snippet.
2. Create a .js file.
3. Type the shortcut.
4. Move the cursor away and then place it back.
5. Press <kbd>Tab</kbd>.

**Does this issue occur when all extensions are disabled?:** Yes

**Comment by jrieken** [comment]
Use `"editor.tabCompletion": true,`
