### ISSUE TITLE
Allow to edit the left hand side of a diff editor if possible

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#4180]
You can hit it by using `Compare with` action and `--diff`. This is really sad. The editor on the left should only be read-only if the input behind it is really read-only (coming from the git index, for example).

cc @alexandrudima @bpasero

**Comment by bpasero** [comment]
Yes I always wanted that actually :)

**Comment by alexandrudima** [comment]
On my side it would be pretty easy to just comment out the forcing of `readOnly=true` on the left-hand-side. But I need to add an option to allow the workbench to make the git diff case left-hand-side readOnly.

**Comment by alexandrudima** [comment]
There's also the inline diff case, where I cannot make the "original" editable.

**Comment by bpasero** [comment]
@alexandrudima yeah I think we know in all places if the left hand side should be editable or not, I think it would only be the file-2-file compare where this applies.

**Comment by alexandrudima** [comment]
Ok, there is a new option `originalEditable` to the diff editor. It is false by default.

**Comment by bpasero** [comment]
@alexandrudima cool, let me pick this up then...

**Comment by bpasero** [comment]
@alexandrudima so by default this option is true or false?

**Comment by alexandrudima** [comment]
:) Wrote in comment and in jsdoc: it is false by default.

**Comment by joaomoreno** [comment]
Don't editor inputs have a `readonly` property?

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
Hm, I forgot that this adds a bit more complexity to how actions operate on the active editor and how dirty state is indicated. I think I was a bit too optimistic for March but will check. Otherwise April it will be.

**Comment by bpasero** [comment]
Surprisingly lots of things actually do work in terms of dirty indication but the one for the actual editor does not because it only checks for the right hand side.

**Comment by nojvek** [comment]
If this something that can be done as a first PR? Would be great if you could indicate issues that would be easy wins for an outsider to contribute. I really really really really want git diffing to work on the right side. I will buy you a coffee/beer if you fix this :stuck_out_tongue_winking_eye:

**Comment by bpasero** [comment]
@nojvek you can always edit on the right hand side when comparing outgoing changes in git!

**Comment by bpasero** [comment]
(this feature request is about being able to edit either the left hand or the right hand side when comparing 2 files)

**Comment by nojvek** [comment]
Oh I just saw that after doing an upgrade. This seems fairly recent. This really bought me a lot of joy when it worked.

**Comment by bpasero** [comment]
It was always possible to edit the right hand side of the diff editor for git changes view.

**Comment by bpasero** [comment]
From @alexandrudima 

> * in the explorer,
> * right click on a file A, choose "Select for compare"
> * right click on another file, choose "Compare with A"
> * observe: left hand side of the diff is not editable
> 
> Fix: use `originalEditable` when the diff editor models are both editable files.

**Comment by Yanpas** [comment]
It would be cool to have two buttons in the middle "copy changes from left to right" and vice versa.

Like this (Eclipse):
![image](https://user-images.githubusercontent.com/7345761/35747611-eb6bff7e-085b-11e8-982c-7a4c87716bdb.png)

**Comment by nojvek** [comment]
Yeah the copy changes is super useful.

**Comment by therealmarv** [comment]
So the option works
```json
"diffEditor.originalEditable": true
```

but VSCode 1.20.0 (1.20.0) complains about "Unknown configuration setting":

![image](https://user-images.githubusercontent.com/1050582/36089634-94139a98-0fe5-11e8-8bf5-1c517ba50008.png)

**Comment by therealmarv** [comment]
What's also strange (mac here): `Cmd+S` does not save the original! The UX handling is really weird with the original file and I had lost my editing once. I have to close the diff window after editing and save the unsaved original which is not how I assumed the saving should work with this option turned on.

**Comment by eamodio** [comment]
It would be nice if there was read-only on/off control of both sides of the diff editor. In GitLens, when diffing history both sides should be read-only.

**Comment by duartemolha** [comment]
Can someone explain to me where I can set originalEditable ?

Really confused. That option is not listed on my settings v1.27.1

**Comment by thomasfrobieter** [comment]
This setting is just working for the split view. If switched to inline view, i can't even just select (nor copy) the original text.

**Comment by t-hofmann** [comment]
would be nice to have that available also in the "ui" version of "settings"
Having both editable is very convenient for refactoring: 
1. identify common code and 
2. possibly move that to a parent-class

Nice.

**Comment by Paperalien** [comment]
> 
> 
> It would be cool to have two buttons in the middle "copy changes from left to right" and vice versa.
> 
> Like this (Eclipse):
> ![image](https://user-images.githubusercontent.com/7345761/35747611-eb6bff7e-085b-11e8-982c-7a4c87716bdb.png)

The ability to move code from the original to the new is pretty fundamental in vcs compare tools. I don't think I've ever found a diff tool before that doesn't have it.

**Comment by tdomhan** [comment]
`"diffEditor.originalEditable": true,` works perfectly! Is there any way to make this the new default? I can't imagine ever not wanting this on.

**Comment by Thaina** [comment]
Now `"diffEditor.originalEditable": true` has a bug. It allow edit on left side but then it make right side cannot be edited

Please stop hacking around and just let the diff editor can edit both side. Maybe just having lock icon that can be toggled and that's all

**Comment by bpasero** [comment]
![before (3)](https://user-images.githubusercontent.com/900690/69167049-8baead00-0af4-11ea-856a-789e42ff051c.gif)

I pushed a change to enable this by default if the left-hand editor is not readonly. Pressing `CtrlCmd+S` or `File > Save` will now save both sides of the diff editor. 

Feedback welcome, it will be in tomorrows insider build: https://code.visualstudio.com/insiders/

**Comment by jharrang** [comment]
@bpasero Thanks for implementing! Now that this is closed, is it possible to finally implement https://github.com/microsoft/vscode/issues/25887 and https://github.com/microsoft/vscode/issues/37350? This would address a critically missing piece of editor functionality that has been heavily requested for over two years.

Also mentioning @alexandrudima who has been consolidating a number of issues to #25887

Thanks much!
