### ISSUE TITLE
cant find my custom themes anymore after update

### ISSUE THREAD

**Issue by ReyoungLee** [Microsoft/vscode#41804]
- VSCode Version: 1.19.1=>1.19.2
- OS Version: win10 1709

Steps to Reproduce:

1.update as the guide. 
2.custom themes disappeared

Does this issue occur when all extensions are disabled?: No

**Comment by ReyoungLee** [comment]
i made a custom theme based on the built-in monokai theme, i changed many colors and token colors...and it's gone...i have to do it again.

**Comment by usernamehw** [comment]
Was it in your [EXTENSIONS FOLDER](https://code.visualstudio.com/docs/extensions/yocode#_your-extensions-folder) or just in the vscode folder itself?

**Comment by ReyoungLee** [comment]
@usernamehw thank u for replying. i've checked that folder, it wasn't there.

i made this theme by duplicate the theme-monokai folder(in the extensions folder) and rename it and then edit it. so i checked the folder immediately after find that it's gone

**Comment by usernamehw** [comment]
So it was in a different folder? If it was in path like this it is expected of it to rewrite the folder on update:
`C:\Program Files\Microsoft VS Code\resources\app\extensions`
⬆️ this is a folder for internal (embedded) extensions that ships with vscode

---

`%USERPROFILE%\.vscode\extensions` - this folder is where external extensions is (including yours)

**Comment by ReyoungLee** [comment]
@usernamehw ah  i know what u mean now. sorry i didnt check the link you gave carefully.
i dont know there is another extensions folder for user(not the app) before.
so if this is the way vscode works, i'll use the extension folder for me.
thank you.
