### ISSUE TITLE
A small problem in regex finding

### ISSUE THREAD

**Issue by FishyFizz** [Microsoft/vscode#41805]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.1.2
vscode-great-icons|emm|2.1.22
cpptools|ms-|0.14.6
team|ms-|1.122.0
vscode-lua|tri|0.9.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.Text in editor is shown below

		e1:SetCode(EFFECT_UPDATE_ATTACK)
		e1:SetValue(e:GetLabel())
		e1:SetReset(RESET_EVENT+0x1ff0000)

2.The regex which would have matched it is shown below but it missed the hit
.*SetCode.*(\n.*){0,3}SetReset
two asterisks were invisible but made "SetCode" italic. (Markdown Styling)

(The regex pattern worked well with notepad++ and regex101.com)

Update:
I found the results matching the pattern with notepad++. And it matched in VSCode after I opend a file containing one of the results(yeah it only found this one). And it matched two when two editor windows stayed open...
Possible to make it search the whole workspace just like what it does for the regex patterns without "\n"?
 

Reproduces without extensions: Yes

**Comment by usernamehw** [comment]
You can put as many `*` as you want if you wrap the code into backticks (\`)
`.*SetCode.*(\n.*){0,3}SetReset`

**Comment by usernamehw** [comment]
What exactly wrong with it? I'm not often using them, looks like working to me:
![regex](https://user-images.githubusercontent.com/9638156/35098053-bd9773b6-fc63-11e7-8540-a9aa10006f72.png)

**Comment by FishyFizz** [comment]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Alexander<mailto:notifications@github.com>
发送时间: 2018年1月18日 20:14
收件人: Microsoft/vscode<mailto:vscode@noreply.github.com>
抄送: FishyFizz<mailto:fishy_fizz@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Microsoft/vscode] A small problem in regex finding (#41805)


In fact it just searches the currently opened file when the regex pattern is containing \n . But it searches the whole workspace when the regex pattern is not containing \n .

It made me a little uncomfortable because I was working on the relevancy of Effect.SetCode and Effect.SetReset , I wanted to test if they were always used together (within few lines).And there were over 8000 pieces of scripts.

If you save several files like the one you’ve shown, and open one of them,then try “search in files”. Only the opend file will be searched.

**Comment by juler69** [comment]
I have experienced the same problems with regex searches, mostly when using Find in Folders.
I frequently either:
* cannot find things that should match
* can only find the first instance of a match
* find a small subset of matches and miss the rest

If I repeat the search using Find in a single open file it usually works.
Sometimes when I get right out of any files in the folder I am searching and repeat the search it works where it didn't previously if the folder was expanded.

**Comment by alexandrudima** [comment]
Given a file with the contents:
```
	e1:SetCode(EFFECT_UPDATE_ATTACK)
	e1:SetValue(e:GetLabel())
	e1:SetReset(RESET_EVENT+0x1ff0000)
```

And a regex search for `.*SetCode.*(\n.*){0,3}SetReset`, the find in file search gives one hit:

![image](https://user-images.githubusercontent.com/5047891/35624124-54582686-068e-11e8-8be3-46a454f6d0a7.png)

When the file is closed (and we use rg for searching), the match is indeed not found:
![image](https://user-images.githubusercontent.com/5047891/35624173-7e9f9e4c-068e-11e8-8e04-d41933edbf6a.png)

I am not sure if we ever implemented multi-line search when searching across files

**Comment by roblourens** [comment]
No, we don't support multiline search across files. https://github.com/Microsoft/vscode/issues/13155
