### ISSUE TITLE
Undo history doesn't clear on git branch change

### ISSUE THREAD

**Issue by tomellwood** [Microsoft/vscode#41807]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
dustjs|Azk|0.1.1
vscode-eslint|dba|1.4.4
vscode-fileutils|sle|2.7.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a file - switch to terminal and checkout a new branch which changes the open file.
2. In VSCode, Edit > Undo will revert the file back to how it is on the previous branch.

**Expected Behaviour:**
Should checking out a new branch not clear the undo history for the project? I don't think VSCode should have the ability to change the file if git is controlling it. Edit > Undo should do nothing in this scenario.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
I don't really think that is expected behaviour. Imagine you're using VIM, Sublime, etc. If you check out another branch using Git, I would never expect my undo stack in VIM or Sublime to change.

**Comment by tomellwood** [comment]
You're completely right - I'd always thought Sublime cleared the undo history on branch switch.

I assumed this was a bug, but if it's the desired behaviour then I guess this turns more into a feature request. I'll just close the issue for now, it's no big deal.

I do wonder though, what's the benefit of being able to undo to another branch's version of the file?
