### ISSUE TITLE
TextEditor.insertSnippet: Callback for when the snippet is finished / accepted

### ISSUE THREAD

**Issue by Lisoph** [microsoft/vscode#41803]
I propose adding a callback parameter / option to `TextEditor.insertSnippet` which get's called when the user has accepted the snippet / exited snippet mode.

This would allow for daisy-chaining multiple snippet inserts. As soon as the user is done with one snippet, he will be directed to finish the next one, and so on - like signing a contract: "sign here, here and here".

The callback should fire whenever the user exits snippet mode:
- When the user finishes the snippet.
- When the user cancels the snippet.

Maybe adding a `reason` parameter to the callback, which indicates how the snippet mode was exited, would be useful.

Thoughts?

**Comment by desasaliho** [comment]
https://auth.ccm.net/user/activate_account/eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjM4MTJkM2VlZTcyMzFkNWIyYWRjNzMxNjJhNjcyYTYwYzIxMTA1NTk4YTUxYWIzYWFhYWU2YmFmNTBhNzIyOTAifQ.eyJqdGkiOiIzODEyZDNlZWU3MjMxZDViMmFkYzczMTYyYTY3MmE2MGMyMTEwNTU5OGE1MWFiM2FhYWFlNmJhZjUwYTcyMjkwIiwiaWF0IjoxNTE2NDk3MDU4LCJleHAiOjE1MTY1ODM0NTgsInVzZXJJZCI6OTIwMjU0OSwidHlwZSI6ImNyZWF0ZUFjY291bnQifQ.RaEyMkHx0B8fX3J8EfzxbA1BUx7L1lnO3uNdRtvs9ULD2fJO_i5V3oC2C6g0ri4p295gIbx_TbQSX63scXXmZBd5tVDW6D6f3GiDSxfXVhOI18L7XtxXiDfX5tR7-w7FM11vpXD-3fRxi1XHlHOYTjeF0nRt6HvoVUyMf7HK8VM?clientId=ccmEN

**Comment by Lisoph** [comment]
@desasaliho What's this?
