### ISSUE TITLE
Major debugger issues

### ISSUE THREAD

**Issue by RomanOvidiu** [Microsoft/vscode#41801]
- VSCode Version: 1.19.2
- OS Version: Windows 10, latest version, all updates installed

Steps to Reproduce:

1.Launch Visual Studio Code in Windows
2.Load up a JavaScript project. 
3.Try to place breakpoints into source code files.

At times, the breakpoints will disappear and line-by-line execution will not be marked anymore. If this starts to happen, a possible solution is to uninstall and reinstall the editor. However, this does not work for me anymore and the software isn't usable.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this.
What version of node do you have? Can you share a repository for which you can reproduce this all the time? Can you share exact reproducable steps?

**Comment by RomanOvidiu** [comment]
I have Node 8.9.1

Unfortunately, i cannot share the source code for the project i'm working on.

The steps are the ones that i have mentioned in the ticket. I'm not doing anything out of the ordinary. Just loading up a project and trying to place breakpoints in the source files, then i'm launching the project, and i'm trying to do a step-by-step execution, after making a request with Postman.

**Comment by roblourens** [comment]
Do the breakpoints really disappear, or just turn gray?

**Comment by RomanOvidiu** [comment]
They disappear altogether and when you should see which line you have reached with the execution, the highlight for the line disappears as well.

When you want to place new breakpoints, you just can't do it anymore, that's when they disappear.

I will make a gif when the issue appears again.

**Comment by roblourens** [comment]
> When you want to place new breakpoints, you just can't do it anymore, that's when they disappear.

So you click in the margin and nothing happens? Very odd, a gif would help a lot.

**Comment by RomanOvidiu** [comment]
I now have a sample of the behavior for you. When you see the mouse moving over the breakpoint line in the editor, i am clicking continuously, and no breakpoints are placed there.
In the clip named "2nd sample", i demonstrated the behavior better.

**Comment by roblourens** [comment]
What's happening is, it is setting the breakpoints but they are all being moved down to the same line. A few things could be happening

- There's something wrong with your sourcemaps, and they are mapping many lines to the same line
- That file doesn't actually match the file that's being run (e.g. if it was changed, and not rebuilt)

I would look carefully at your project. Have you been able to debug it with anything else? Chrome devtools, etc?

**Comment by RomanOvidiu** [comment]
I am developing a REST API. After each code change, i am restarting the server (so it will run on the new code version). I did debug this with WebStorm, and it worked, to some extent (i'm not very good with their proprietary debugger, but this is another discussion altogether). 
How would i be able to check if the sourcemaps are ok ?

**Comment by roblourens** [comment]
Can you share the project with me?

**Comment by RomanOvidiu** [comment]
I'm sorry. That's just not possible. I have an NDA for the project.

**Comment by roblourens** [comment]
Ok. If you can, you could take a log by setting `"trace": true` and reproing it again, then upload the log here or email it to me. It will contain paths of your files, and if you've built with inlined sources, then it would contain sources too. So you may not be able to do that. But otherwise this is hard to debug remotely.

**Comment by RomanOvidiu** [comment]
So i've paid attention to the breakpoints, when it crashed again, and it moved a lot of them outside of methods, on empty lines, and so on.
This fits the behavior you described. 
Could you point me in the direction of a solution ? This is really frustrating for me, as i get 5-6 crashes a day, and some of the occur during conferences with other developers on my team or with clients.  So i need to reinstall VS Code 5-6 times/day.
I'd like to contribute in some way, or something like that, so that this can get fixed.
I cannot send you anything related to the project, as that would expose me to possible penalties in the workplace, or possible legal action, according to the NDA i've signed.

**Comment by RomanOvidiu** [comment]
I just checked, and the logs do not contain any source code. 
The path that i checked is : "~\AppData\Roaming\Code - Insiders\logs" (right now the debugger only works in the "insider" version, on my workstation).
I will check with management and i will let you know if i can send you the logs.

**Comment by roblourens** [comment]
> This is really frustrating for me, as i get 5-6 crashes a day, and some of them occur during conferences with other developers on my team or with clients. So i need to reinstall VS Code 5-6 times/day

I guess I'm not even clear on what the problem is then. I thought you were just having trouble setting breakpoints. Can you describe a little more what you mean by "crash"?

**Comment by RomanOvidiu** [comment]
The debugger crashes. Sorry for the confusion. However, so far, i have been paying attention to the first break point that gets hit when i start a debugging session and, if the break point is located at the end of the code file and there isn't any code on that line, i just have to remove it and the debugger will work just fine.
So, for now, i have been able to use the debugger as i was supposed to.
However, if i do not remove the break point that got pushed outside of the source code in the file, when i try to start another debugging session, 90%+ of the time, the debugger will stop working.
I'm still expecting the response from the management, so i can send you those logs.
