### ISSUE TITLE
GIT integration failure

### ISSUE THREAD

**Issue by underdog** [Microsoft/vscode#41808]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---
GIT not integrating with VSCode.
No GIT icon for SCM
No GIT option to add as SCM
No option to initialize GIT repo
![2018-01-18_7-22-43](https://user-images.githubusercontent.com/510960/35100238-f63459a2-fc52-11e7-8ad8-ecd91e79efeb.png)

Steps to Reproduce:

1. installed GIT for windows 2.15.1.2-64-bit
2. I've manually added the path to git.exe within user settings and still no joy
3. I've uninstalled git and vscode several times and reinstalled
4. I've uninstalled git alone and reinstalled and rebooted with no success of integration with vscode

PATH value for OS
Path=C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Chevron\GIL Tools\GILSystemPath;C:\Program Files (x86)\Support Tools;C:\Program Files (x86)\WebEx\PTools020000000;C:\Program Files\Git\cmd;C:\Users\<USERNAME>\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin

Default settings (git)
// Whether auto fetching is enabled
  "git.autofetch": false,

  // Whether auto refreshing is enabled
  "git.autorefresh": true,

  // Controls what type of branches are listed when running `Checkout to...`. `all` shows all refs, `local` shows only the local branchs, `tags` shows only tags and `remote` shows only remote branches.
  "git.checkoutType": "all",

  // Confirm before synchronizing git repositories
  "git.confirmSync": true,

  // Controls the git badge counter. `all` counts all changes. `tracked` counts only the tracked changes. `off` turns it off.
  "git.countBadge": "all",

  // Controls if Git contributes colors and badges to the explorer and the open editors view.
  "git.decorations.enabled": true,

  // The default location where to clone a git repository
  "git.defaultCloneDirectory": null,

  // Enables commit signing with GPG.
  "git.enableCommitSigning": false,

  // Whether git is enabled
  "git.enabled": true,

  // Commit all changes when there are no staged changes.
  "git.enableSmartCommit": false,

  // Ignores the legacy Git warning
  "git.ignoreLegacyWarning": false,

  // Ignores the warning when there are too many changes in a repository
  "git.ignoreLimitWarning": false,

  // Ignores the warning when Git is missing
  "git.ignoreMissingGitWarning": false,

  // Path to the git executable
  "git.path": null,

**Comment by joaomoreno** [comment]
If you run `Git: Show Git Output`, what does that show?
