### ISSUE TITLE
Views state: persist when it changes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41817]
Steps to Reproduce:

1. hide a view
2. open a new window

=> the new window is still showing the view

I think it is good that we changed that the view visibility is now based on global state and not workspace state. But I think given that we should also update the storage state when the views change such as new windows will benefit from the configuration of the user.

**Comment by sandy081** [comment]
@bpasero I am updating the storage when the view's visibility is changed [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L746)

So when a new window is opened, it should get latest state, unless window is opened too fast and reads old state??

Also existing windows will not get these changes.

**Comment by bpasero** [comment]
@sandy081 oh you are right, then this issue can be closed 👍
