### ISSUE TITLE
Configuring a gulp task runner takes more than 3s sometimes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4181]
Related to #4019

- VSCode Version: 18ebb4a4f5491af7b16e91e42fc36410bbb2e4d7
- OS Version: El Capitan

Steps to Reproduce:

1. open vscode repo, delete `tasks.json`
2. Configure Tasks Runner > gulp
3. `tasks.json` is generated only after 3 seconds, I would expect it is instantanious

**Comment by dbaeumer** [comment]
There is little I can do about it since I spawn gulp to determine the task. If I call gulp --tasks-simple on the command line it takes quite some time as well. For example for VSCode between 2 and 3 seconds on my machine.

**Comment by isidorn** [comment]
Makes sense
