### ISSUE TITLE
Shortcut alt+e doesn't work

### ISSUE THREAD

**Issue by mkoczka** [Microsoft/vscode#41814]
- VSCode Version: 1.20.0-insider
- OS Version:  Windows 10 Enterprise 10.0.15063 Build 15063

Additional info from about dialog:
Commit 2d79f9da3ca330ad7ebeb7dc3f538a0cf1634fa3
Date 2018-01-18T05:14:16.814Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Go to the code editor, and hit ALT-E
2. See that while you are holding ALT the E is underlined, but hitting E doesn't do anything

Does this issue occur when all extensions are disabled?: Yes

Related: #33806, #27798

Can reproduce this also on released vscode version 1.19.2

**Comment by alexandrudima** [comment]
This works fine for me. Remember, you have to use the left-hand-side <kbd>Alt</kbd> on your keyboard if your keyboard layout uses the right-hand-side <kbd>Alt</kbd> for <kbd>AltGr</kbd> (e.g. Polish keyboard layout)

**Comment by johndebord** [comment]
This doesn't work for me. Pressing alt+e make the edit menu pop up in the upper left corner.
Could this be an OS issue?
