### ISSUE TITLE
Search viewlet restored input from different distros

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#41813]
* I run code insiders, and
* I run `scripts/code`
* for some bizarre reason both share search history (which they shouldn't because it's different products). 

![jan-18-2018 14-58-31](https://user-images.githubusercontent.com/1794099/35101577-577a2892-fc60-11e7-9559-5b52c9759ec8.gif)

**Comment by bpasero** [comment]
This is `"editor.find.globalFindClipboard": true` and scary and I think should be off by default.

**Comment by roblourens** [comment]
It's enabled in other products like Sublime and Chrome by default. But I still have to agree. Thoughts @rebornix?
