### ISSUE TITLE
Missing Intellisense on Interfaces in package.

### ISSUE THREAD

**Issue by nwayve** [Microsoft/vscode#41819]
I'm not sure if it's this particular npm package, a configuration issue on my end, or what, but it seems like I can't get any intellisense on the interfaces and objects in this particular library package, and nothing about it seems off.

- VSCode Version: 1.19.2
- OS Version: Windows 10 -> 1709
- Node v9.3.0
- npm v5.6.0

Steps to Reproduce:
1. npm init -y
2. npm i openapi3-ts
3. npm i -D typescript
```json
{
  "name": "open-api-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "openapi3-ts": "^0.6.2"
  },
  "devDependencies": {
    "@types/node": "^9.3.0",
    "typescript": "^2.6.2"
  }
}
```
4. Configure workspace settings:
```json
{
    "typescript.tsdk": "./node_modules/typescript/lib"
}
```
5. tsc init
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true
  }
}
```
6. Create `index.ts` file:
```typescript
import * as OpenAPI from 'openapi3-ts';

OpenAPI.
// Intellisense only shows 3 functions and 4 classes in the intellisense popup
// None of the interfaces show up
let foo: OpenAPI.OpenAPIObject;
foo.
// We do get intellisense on this interface's properties.
```

Does this issue occur when all extensions are disabled?: Yes

This could be an issue with this library's configuration and/or typescript's configuration, but given that I'm still getting some intellisense from the package, I wanted to make sure this was expected behavior in vscode.

**Comment by mjbvz** [comment]
Here's what I see:

![screen shot 2018-01-18 at 4 34 39 pm](https://user-images.githubusercontent.com/12821956/35128862-81156ccc-fc6d-11e7-8103-9a8109c26c54.png)

We only return interface and type suggestions in context where they are valid. That is why no interfaces are shown for `OpenAPI.` Here's suggestions in a type context:

![screen shot 2018-01-18 at 4 34 58 pm](https://user-images.githubusercontent.com/12821956/35128879-8d4330ec-fc6d-11e7-9c5f-353597d0eaa3.png)

**Comment by nwayve** [comment]
> We only return interface and type suggestions in context where they are valid.

Oooh, interesting.  I must have overlooked that in the docs.  Thanks for your time and the info on that.
