### ISSUE TITLE
Unplugging external monitor breaks integrated terminal rendering in 

### ISSUE THREAD

**Issue by nvdv** [Microsoft/vscode#41827]
- VSCode Version: 1.19.2
- OS Version: macOS 10.13.2 (Macbook Pro 13 2016 and Macbook Pro 15 2017)

Steps to Reproduce:

1. Open VS Code and integrated terminal with external monitor.
2. Hide integrated terminal.
3. Unplug external monitor.
4. Show integrated terminal.

Does this issue occur when all extensions are disabled?: Yes
![screen shot 2018-01-18 at 5 47 54 pm](https://user-images.githubusercontent.com/745431/35120301-ba514e30-fca8-11e7-934c-d668cc12bc1c.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
