### ISSUE TITLE
"acceptSelectedSuggestion" command behaves differently for return statements

### ISSUE THREAD

**Issue by ianjosephthompson** [Microsoft/vscode#41828]
I had a pet peeve in older version of Visual Studio Code (VSC) where I type a namespace which VSC doesn't understand, hit the "." (period) key, and the top Intellisense suggestion is accepted instead of the "." character being typed.

I mitigated this in previous builds with a custom keyboard shortcut.  In the current version, this is the default behavior instead (which I super appreciate), EXCEPT the behavior appears to be different when typing a return statement.

Repro Steps:
 * Open a JavaScript file
 * Type:
`var x = function () {`
`  //  put your cursor here`
`};`
 * Inside the function body, type:
`
Ext
`
 * Observe the Intellisense suggestion box appears.
 * Hit the period key
 * Observe how a period character is added and the suggestion box closes.
 * Delete the body of the function
 * Inside the function body, type:
`
return Ext
`
 * Observe the Intellisense suggestion box appears.
 * Hit period key
 * Observe how the top suggestion is selected and no period character is typed

**Comment by mjbvz** [comment]
This is because `.` is treated as a "commit character" for JS property suggestions. You can disable this by setting `"editor.acceptSuggestionOnCommitCharacter": false` or canceling out the suggestion popup before hitting `.`
