### ISSUE TITLE
Changing between single and double quotes is annoying due to auto-quoting

### ISSUE THREAD

**Issue by jarrettv** [Microsoft/vscode#41825]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.13.0-25-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.4
vscode-npm|fkn|3.3.0
vscode-mysql|for|0.2.2
python|ms-|0.9.1
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.0.0
vscode-input-sequence|tom|0.2.0
ReactSnippets|xab|1.7.0

---

Steps to Reproduce:

1. Highlight a single quote and change it to double quote
2. The editor types extra quotes and you have to delete them

Reproduces without extensions: Yes/No

**Comment by reginaldwhite** [comment]
I've noticed this as well!

**Comment by alexandrudima** [comment]
:+1: we might consider adding an exception in this case to the surround selection code.
