### ISSUE TITLE
CLI --proxy-server not setting value

### ISSUE THREAD

**Issue by TheCodeGnome** [Microsoft/vscode#41821]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-standard-format|che|0.0.12
compulim-vscode-closetag|Com|1.1.0
githistory|don|0.3.2
php-debug|fel|1.12.1
auto-close-tag|for|0.5.5
format-indent|Kas|1.3.0
format-php|Kas|1.1.2
php-symbols|lin|2.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
HTMLHint|mka|0.4.0
team|ms-|1.122.0

---
**Description:**
I'm trying to install extensions via command line as part of a Code install script. Our environment var for the corp proxy causes a timeout, but manually setting the proxy addess using "http.proxy" in user settings works. In order for this script to work, I need to set the proxy via CLI (otherwise I may as well install the extensions via the GUI and that defeats the point of the script). However, setting the proxy via --proxy-server only launches code without making any visible changes. Testing shows it does not seem to make any hidden changes either. The same thing (only opening Code) happens with --no-proxy-server.

If I manually set "http.proxy", close Code, then run the code --install-extension command, everything works fine. Essentially, you cannot set a proxy server via command line.

**Steps to Reproduce:**
1. Launch cmd.
2. Input { code --proxy-server="http://proxy:port" }
3. Code will launch, so close it.
4. In cmd, input { code --install-extension wix.vscode-import-cost }, or any other extension.
5. Action will timeout.

![image](https://user-images.githubusercontent.com/15162807/35112054-daf311d6-fc4a-11e7-92b9-535b4c094552.png)
_Image showing CLI outputs (sensitive data redacted)._

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Unfortunately, the CLI still uses the legacy proxy server support:

https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support

**Comment by TheCodeGnome** [comment]
Then scroll up. The [same page](https://code.visualstudio.com/docs/setup/network#_proxy-server-support) says I can use the --proxy-server cli command to set that value.

Might be a good idea to update/clarify the documentation.
