### ISSUE TITLE
Allow hiding any status bar items

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41820]
I can hide custom tree views in the sidebars, but I can't hide statusbar items from extensions, unless that extension implements a setting for it. Example, the liveshare extension always shows this annoying status bar item: 
![image](https://user-images.githubusercontent.com/323878/35111782-e99d7830-fc30-11e7-8f79-c334b815587e.png)

and I can't get rid of it unless I disable the extension. I should be able to show/hide these just as I can with tree views in the explorer and viewlet icons in the activity bar.

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/3874 ?

**Comment by roblourens** [comment]
Guess so, thanks
