### ISSUE TITLE
Terminal text garbled after resizing output window

### ISSUE THREAD

**Issue by cxh004405** [Microsoft/vscode#41826]
![vscode_garbled_terminal_text_filtered](https://user-images.githubusercontent.com/13354779/35120252-22a00bee-fc5d-11e7-82bb-feb656f5a00e.png)
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vsc-material-theme|Equ|1.2.0
beautify|Hoo|1.1.1
minify|Hoo|0.3.0
material-icon-theme|PKi|3.2.1
vscode-docker|Pet|0.0.23
plsql|cas|0.0.3
vscode-eslint|dba|1.4.4
php-debug|fel|1.12.1
code-runner|for|0.8.7
ansible|haa|0.2.7
vscode-swift|kia|0.8.0
ftp-sync|luk|0.3.3
theme-monokai-pro-vscode|mon|1.1.5
mssql|ms-|1.3.0
python|ms-|0.9.1
vscode-ai|ms-|0.1.6
azure-account|ms-|0.2.2
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
PowerShell|ms-|1.5.1
vscode-icons|rob|7.19.0

(8 theme extensions excluded)

---

Steps to Reproduce:

1. Run script multiple times from integrated terminal.
2. Clear output multiple times.
3. Run additional commands.
4. At some point resize screen, terminal text becomes garbled. Must restart code to correct.
5. Haven't found a way to easily reproduce the issue consistently.

Does this issue occur when all extensions are disabled?: Yes/No
No, cannot consistently reproduce even with extensions enabled

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
