### ISSUE TITLE
Add new "step" and "step into next function call" buttons in Debug toolbar

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#41824]
To follow the pattern of Chrome DevTools, https://developers.google.com/web/updates/2018/01/devtools#async, and the recent changes in https://github.com/Microsoft/vscode-chrome-debug-core/issues/266 we should consider renaming the existing step button to "step into next function call" and introduce a "step" button for JavaScript debuggers.

![chrome](https://user-images.githubusercontent.com/173559/35115127-fa3214ac-fc3b-11e7-958c-ba3badfb9eae.png)

@roblourens @weinand

**Comment by roblourens** [comment]
I actually didn't notice that they'd added that, like "step into, but not into an async function". I think it makes sense. We can add the stepBack button, but it's specifically in the debug protocol as "step back". I wonder whether extensions should be able to add arbitrary debug widget actions, which could trigger custom debug requests.

**Comment by weinand** [comment]
This requires a DAP addition.
