### ISSUE TITLE
Keywords and Storage.types have the same color in Dark theme for Go

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#41822]
_From @sullyme on January 3, 2018 20:5_

These are the colors in **X IDE:**

![image](https://user-images.githubusercontent.com/18464442/34537646-7ec7246a-f0c9-11e7-880b-bd76964317b7.png)

This instead in my **VSCode**:

![image](https://user-images.githubusercontent.com/18464442/34537686-9caa0c4a-f0c9-11e7-91f7-08a72d5dfb5d.png)

How can I format colors of my code better?

Eg: `chan` and `int` have the same color!

_Copied from original issue: Microsoft/vscode-go#1439_

**Comment by ramya-rao-a** [comment]
_From @smt923 on January 10, 2018 17:27_

This isn't really an issue for this project, some vscode syntax themes have more or less color stuff, here is my vscode + vscode-go + [the brilliant Dracula theme](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula) (plus I have ligatures in the font but that's unrelated)

![syntax](https://i.imgur.com/TuOFl9G.png)

You'll have to find another color theme that has more colors I think there's a vscode dark plus, or if you want one more like your old theme there's plenty of monokai (it looks like that one is based on monokai but I could be wrong) and monokai variant themes on the marketplace for vscode

For example, the 'Monokai' theme that I think is preinstalled looks like this:

![monokai](https://i.imgur.com/hgIICJp.png)

just in case you don't know already, once you've installed a font you can go to file -> preferences -> color theme to change the theme

**Comment by ramya-rao-a** [comment]
_From @sullyme on January 10, 2018 18:54_

Thanks a lot. That screenshot (https://user-images.githubusercontent.com/18464442/34537686-9caa0c4a-f0c9-11e7-91f7-08a72d5dfb5d.png) is from Visual Studio Code Dark+ theme which I love. Monokai is more grey... and Dracula I don't like it: too many lines.

Now I will go with Monokai. But I'm unhappy.

**Comment by ramya-rao-a** [comment]
Thanks @smt93 for chiming in!

@sullyme The issue is with how the Dark theme assigns colors for the different textmate scopes which is controlled in the core VS Code

**Comment by ramya-rao-a** [comment]
@aeschli 

Sample code:
```
package main

import "fmt"

func main() {
	c := make(chan int)
	c <- 3987
	fmt.Print(<-c)
}
```

`chan` has the scope `keyword` and `int` has the scope `storage.type`. Same color gets assigned to both in the Dark theme.

**Comment by aeschli** [comment]
Unfortunately 'storage.type' is used by maybe grammars for keywords like constructs such as `var`, `function` (e.g. in JavaScript). But I can updated some of specific scopes that go uses.
