### ISSUE TITLE
Bail early if --diff is not used with correct arguments of 2 existing files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4182]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. code --diff file1 file2 where file2 doesn't exist

Code opens with the second file empty in a dirty buffer. I can't see any use case for this. I think a better behavior would be to show a dialog that the second file doesn't exist.

**Comment by bpasero** [comment]
I decided to just open an empty workspace in this case. The issue with showing 2 dirty files should be fixed by that.
