### ISSUE TITLE
Debug type dropdown requires two Escapes to close

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#41836]
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install the Chrome debugger so you have two possible Node.js debuggers
2. Without a launch.json, start a Node.js app debug session (for example, a new Express App)
3. When the Debug type dropdown is displayed, press Escape

The Debug type dropdown briefly disappears and then reappears. A second Escape closes it.

This does not happen when the Debug type dropdown is displayed from the 'Configure or Fix launch.json' gear button

**Comment by isidorn** [comment]
@gregvanl this is fixed in latest insiders
