### ISSUE TITLE
URLs with URLEncoded values aren't opened correctly in the browser

### ISSUE THREAD

**Issue by kirkholloway** [Microsoft/vscode#41837]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: none
---

Steps to Reproduce:

1. Create a link with the value: "http://localhost/?user=test%2B1@example.com"
2. Command/ctrl + Click on the link to open it

**Comment by kirkholloway** [comment]
The link will not be opened in it's proper state of "http://localhost/?user=test%2B1@example.com"

**Comment by Tyriar** [comment]
@kirkholloway are you clicking the link in the editor or terminal?

**Comment by kirkholloway** [comment]
Inside the editor

**Comment by alexandrudima** [comment]
I'm not sure what exactly should happen in this case.

@jrieken The code goes into `Link.resolve()` which then does an `URI.parse` on that text. It then travels to the opener service.

**Comment by jrieken** [comment]
We call `toString` with skipEncoding: `true` so that no unnecessary encoding happens

**Comment by jrieken** [comment]
dups #25852
