### ISSUE TITLE
Delete line (Cmd + Shift + K) jumps screen to the right

### ISSUE THREAD

**Issue by setek** [Microsoft/vscode#41831]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.2.0
autofilename|Jer|0.1.3
code-settings-sync|Sha|2.8.7
sort-lines|Tyr|1.4.1
vscode-eslint|dba|1.4.4
gitlens|eam|7.5.4
sass-lint|gle|1.0.1
prettify-json|moh|0.0.3
sublime-keybindings|ms-|3.0.3
vetur|oct|0.11.6
partial-diff|ryu|0.5.1
git-merger|sha|0.3.6
vscode-fileutils|sle|2.7.1
language-stylus|sys|1.8.0
twig|wha|1.0.2
ReactSnippets|xab|1.7.0

---

Steps to Reproduce:

1. Delete line (Cmd + Shift + K)

Screen jumps to the right, even though word-wrap is on.

Reproduces without extensions: No

**Comment by alexandrudima** [comment]
I cannot reproduce. Do you have any additional steps?

![ctrl-shift-k](https://user-images.githubusercontent.com/5047891/35230046-49e41ade-ff95-11e7-80ae-43ac642e4e6f.gif)

**Comment by setek** [comment]
Sorry, was a public holiday here :)

It was GitLens, I disabled it, and everything worked properly again.

Disabling, restarting, Re-enabling, and it seems to all work just fine.

Thanks :)
