### ISSUE TITLE
Expand Selection when using Multi Cursor only selects first line

### ISSUE THREAD

**Issue by alan-cole** [Microsoft/vscode#41838]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
lorem-ipsum|Tyr|1.1.0
sort-lines|Tyr|1.4.1
Bookmarks|ale|0.18.0
vagrant|bbe|0.5.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.4
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
file-icons|fil|1.0.7
sass-lint|gle|1.0.1
behatcomplete|har|0.1.0
php-symbols|lin|2.1.0
camelcasenavigation|map|0.3.42
VS-code-drupal|mar|0.0.12
twig-language|mbl|0.2.6
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|3.0.3
incrementor|nms|0.1.0
vetur|oct|0.11.6
px-to-rem|sai|1.2.3
trailing-spaces|sha|0.2.11
cucumber|ste|0.9.6
gitblame|wad|2.2.0

---

Steps to Reproduce:

1. New SCSS file with the following:
```
.class {
  font-size: 12px;
  padding: 24px 26px;
  border-left: 36px solid red;
}
```
2. Place a cursor in each CSS rule (font-size, padding, border-left).
3. Use the 'Expand Select' function.

Expected: All three rules are selected up until the colon.
Actual: Only the first rule is selected up to the colon.

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
@aeschli @octref I have adopted JSON, CSS, HTML to the new proposed API which adds the notion of multiple positions per request.
