### ISSUE TITLE
Generate 'isWatching' could be true if task has 'watch' in name

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4184]
Related to #4019

When generating a `tasks.json` we always set the `isWatching` to `false`, however we could use a simple heuristic to set this to `true` if a task name has 'watch' in the name. IMHO this heuristic could work nicely in practice.

To repro, just generate `tasks.json` for vscode repo

**Comment by dbaeumer** [comment]
@isidorn nice idea, but not easy to realize. The problem is that when in watching mode you need special regular expression to determine in the output when the task is active and when inactive. Otherwise the spinner will not stop :-).

**Comment by dbaeumer** [comment]
For task 2.0.0 I implemented that isBackground will be true if the associated matcher has a background property. This is a stronger indication than a name.
