### ISSUE TITLE
The Source Control Window implicitly includes the home directory on Linux systems.

### ISSUE THREAD

**Issue by Harsha-Yalagach** [Microsoft/vscode#41849]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 3.10.0-693.11.6.el7.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
vscode-processes|and|0.0.4
autoconf|mae|0.0.2
python|ms-|0.9.1
cpptools|ms-|0.14.6

---

Steps to Reproduce:

1. Add your HOME directory to a GIT Version control.
2. Open up any project in VS Code.
3. VS Code will show the contents of the versioned HOME Directory in the SCM Side Bar Window.

Expected Behavior:
VS Code should not include versioned HOME directory in the SCM Sidebar window implicitly.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
If the files you edit are in a git repository, Code will load up that repository. You can disable git by using `git.enabled = false`. You can even do it per workspace.
