### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by aszt** [Microsoft/vscode#41843]
- VSCode Version:1.19.2
- OS Version:windows 1709（内部版本 16299.192）

Steps to Reproduce:

1.下载vscode
2.安装python插件
3.报错（Extension host terminated unexpectedly. Code:  3221225477  Signal:  null）

![问题截图](https://user-images.githubusercontent.com/25339146/35130950-688f1978-fcfe-11e7-95d5-9c47356852ff.png)

尝试过的解决方案
1.删除resources\app\extensions\git文件夹无效
2.添加git.path无效

求解决方案

**Comment by joaomoreno** [comment]
How much memory does your system have?
