### ISSUE TITLE
Reload by gb2312 big file (7547k,txt) no-response (full load one of cpu cores)

### ISSUE THREAD

**Issue by sweetbai** [Microsoft/vscode#41845]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.12.1
githistory|don|0.3.2
git-project-manager|fel|1.4.0
php-debug|fel|1.12.1
phpcs|ika|0.7.0
intellij-idea-keybindings|k--|0.2.18
Go|luk|0.6.73
mssql|ms-|1.3.0
python|ms-|0.9.1
csharp|ms-|1.13.1
gitblame|wad|2.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.
