### ISSUE TITLE
Sometimes the suggest widget is laid out incorrectly

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41840]
Sometimes as I'm typing, but very rarely, I see the suggest widget+docs flash in the wrong location. Today I got lucky and caught it in action. 

![image](https://user-images.githubusercontent.com/323878/35129548-ff9dfc14-fc70-11e7-8ab2-94cbe74d5964.png)

If I type one more character, or close/reopen it, it goes to the right place.

![image](https://user-images.githubusercontent.com/323878/35129682-7aa772a0-fc71-11e7-99ef-b34f53378b58.png)

Is there any remaining issue for this? How can I help debug it?

**Comment by ramya-rao-a** [comment]
Same as https://github.com/Microsoft/vscode/issues/33115#issuecomment-365449153
Fixed in latest Insiders
