### ISSUE TITLE
Can't save an empty file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41841]
- cmd+n
- cmd+s
- Nothing happens

If I type a character, then I can save. This is a regression from 1.19

**Comment by jpsheehan** [comment]
I cannot replicate the issue on my machine, can you paste the version information from the Help > About dialog here?

**Comment by roblourens** [comment]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (531d713432c82e4ffe341f35d03a461713f96660, 2018-01-18T06:07:53.601Z)</li>
	<li>OS Version: Darwin x64 17.3.0</li>
</ul>

Latest insiders, reproes with extensions disabled.

**Comment by shobhitchittora** [comment]
+1 . I'm able to replicate the issue on the latest Insiders. Details below - 

* VSCode Version: Code - Insiders 1.20.0-insider (531d713, 2018-01-18T06:07:53.601Z)
* OS Version: High Sierra 10.13.2

**Comment by shobhitchittora** [comment]
Adding to that `workbench.action.file.saveAs` works ( shift + cmd + s ).

**Comment by shobhitchittora** [comment]
@isidorn I see that the line below got changed a few days back. Can this be the cause here ?

https://github.com/Microsoft/vscode/blob/47832c90391103f27df84ded193decb72bb327b5/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L477

**Comment by bpasero** [comment]
This is actually pretty bad because it also means you can no longer Cmd+S to trigger the format on save handlers.
