### ISSUE TITLE
Alt+Up/Down in replace box in editor find widget triggers move lines actions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#41855]
From @eamodio [here](https://github.com/Microsoft/vscode/issues/18233#issuecomment-358906962)

In replace box of editor find widget, `alt+up/down` should not trigger `editor.action.moveLinesUpAction` or `editor.action.moveLinesDownAction` commands

**Comment by grabantot** [comment]
Same problem with the commit message input box.

**Comment by ramya-rao-a** [comment]
Same problem in the extensions view as well.

**Comment by JacksonKearl** [comment]
@sbatten custom menu bar seems to fix this, any idea why?

**Comment by sbatten** [comment]
@JacksonKearl I thought it might have to do with the `ModifierKeyEmitter` in `MenubarPart.ts` but commenting that out didn't change the behavior

**Comment by JacksonKearl** [comment]
This seems to be somehow related to menus: It affects actions which have menu bar items (move/copy lines up/down), doesn't affect lines which do not (Delete lines).

Strangely, globally changing the each id from 'editor.action.moveLinesUpAction' to ''editor.action.moveLinesUpAction2' (or similar) will fix the issue

**Comment by rebornix** [comment]
No longer reproducible.
