### ISSUE TITLE
Delete line does not close parameter hints when followed by comment

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#41852]
1. Type open brace `(` so that `parameter hints` is visible
```javascript
console.log
// text should be longer than cursor position
```
2. Delete the 1st line
![delete_line](https://user-images.githubusercontent.com/9638156/35141442-f9851e2a-fd0b-11e7-8e45-8511d29ce373.png)

**Comment by jrieken** [comment]
I believe that TS which should return something falsy to end this

**Comment by usernamehw** [comment]
I believe it's not limited to `JS` & `TS`

**Comment by mjbvz** [comment]
Actually I don't think this is a ts specific problem. The JS/TS extension never get asked for the parameter hints again after the first line is deleted, but the widget keep showing

Should the VS Code parameter hint controller re-request hints when the underlying document changes?

**Comment by jrieken** [comment]
> VS Code parameter hint controller re-request hints when the underlying document changes?

Yeah, that's the assumption
