### ISSUE TITLE
Simplify --goto to open file at specific line and column without --goto

### ISSUE THREAD

**Issue by googol7** [microsoft/vscode#41858]
At the moment files can be opened at a specific line and column like this:

`code --goto src/app/pages/main.tsx:24:9`

Why not omit `--goto` like Atom does it:

`atom src/app/pages/main.tsx:24:9`

See: https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_command-line

Related tickets:
[Simplify --goto's usage](https://github.com/Microsoft/vscode/issues/3567)
[Opening a file from command line with line number (--goto) is broken](https://github.com/Microsoft/vscode/issues/39891)

**Comment by bpasero** [comment]
@googol7 you can run Code with a path that does NOT exist on disk to actually create it. Keep that in mind.

**Comment by googol7** [comment]
@bpasero Let’s say the file `foo.txt:4` exists and the user runs

`code foo.txt:4:3:2`

I'd prefer VS Code to open the existing file `foo.txt:4` and jump to line 3, character 2 rather creating a new file 'foo.txt:4:3:2`

**Comment by APerricone** [comment]
Hello,
I am not sure about opening a new issue, but it is possible create a link to a line? for example:
`file:///home/perry/harbour-src/contrib/hbunix/chdir.c:48` try to open **chdir.c:48**, instead of open **chdir.c** and go to line 48... Is it possible do the second case?

**Comment by josh-ua** [comment]
Quick workaround: create an alias, `code -g` also works fine without a line number. So I have:
`alias code="code -g"`

so, something like `code ./home/josh/file.c` opens fine and `code ./home/josh/file.c:30` opens the file and highlights line 30

**Comment by iloveitaly** [comment]
Would be great if the `vscode:` protocol could support line numbers as well. This would make it easy for frameworks to link out to the exact line in VS code which triggered an error.

**Comment by stuaxo** [comment]
Supporting the VIM syntax would be good, as VIM and Gedit already have this:

`[+LINE[:COLUMN]]`

e.g.  `code blah.py +2`

**Comment by minomikula** [comment]
> Hello,
> I am not sure about opening a new issue, but it is possible create a link to a line? for example:
> _**file:///home/perry/harbour-src/contrib/hbunix/chdir.c:48**_ try to open **chdir.c:48**, instead of open **chdir.c** and go to line 48... Is it possible do the second case?

YES!!! this would be really helpfull. We generate some .ts files from java and it would be nice to have links to original fields in ts.

**Comment by stuaxo** [comment]
@minomikula encourage anyone that would find this useful to vote for this, we are only short 3 votes.

**Comment by AlencarGabriel** [comment]
Hello, I have an extension that provides a hover documentation with a link to the file. And many users request that the link go at the documentation in question.

As the link uses Markdown notation, simply calling the file via URI "file://" recognizing the lines and columns with ":", would already meet this need.

Example: 

![image](https://user-images.githubusercontent.com/10109480/81299982-75b68980-904d-11ea-9d2c-417d78bc9e2d.png)

**Comment by cas--** [comment]
It is disappointing to see this closed as my alternative editor Geany handles this exactly as googol7 [outlined](https://github.com/microsoft/vscode/issues/41858#issuecomment-358931374), so to need an extra command switch is annoying.
