### ISSUE TITLE
add outline support for `gotoSymbol`

### ISSUE THREAD

**Issue by hua03** [Microsoft/vscode#41856]
[Code Outline](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) is very clear for checking the code, but it's a bit inconvenient. So I think if  outline support for gotosymbol can be added to VSCode, which makes the levels of variables and functions more obvious. Like this:
![image](https://user-images.githubusercontent.com/19561959/35143605-03323e7c-fd3d-11e7-9059-06f17811fc71.png)

**Comment by jrieken** [comment]
#5605
