### ISSUE TITLE
Debugging Typescript in Visual Studio Code - Corresponding Javascript cannot be found

### ISSUE THREAD

**Issue by EmbarkingFrog** [Microsoft/vscode#41851]
Hello,
This is an issue that many have encountered. I only reach out to you after days of trying to troubleshoot and after no responses on Stackoverflow.
I've followed all online advice related to this issue to no avail. I'm sure the solution is very silly but for the life of me I cannot find it.

- VSCode Version: 1.19.2
- OS Version: Windows 10.0.16299 Build 16299
- Node version: 8.9.4
- npm version: 5.6.0

Steps to Reproduce:
1. Clone github project : https://github.com/EmbarkingFrog/chatbot-tests
2. Try and debug (F5)

Does this issue occur when all extensions are disabled?: Yes

Here's what I've checked as part of the solution:

- My .ts files are being compiled into .js files and .js.map files right next to them.
- The .js files seem to have a correct sourcemap URL at the end
- The .js.map files seem to have a correct .js file URL at the beginning
- My VSCode launch.json has an outFiles property that points to the app.js file.

As for my configuration:
[File directory structure](https://i.stack.imgur.com/wLxIN.png)

npm package.json file:
```
{
  "name": "chatbot-tests",
  "version": "1.0.0",
  "description": "chatbot-tests",
  "main": "index.js",
  "types": "./lib/main.d.ts",
  "scripts": {
    "prestart": "gulp",
    "start": "node dist/app.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/EmbarkingFrog/chatbot-tests.git"
  },
  "keywords": [
    "chatbot"
  ],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/EmbarkingFrog/chatbot-tests/issues"
  },
  "homepage": "https://github.com/EmbarkingFrog/chatbot-tests#readme",
  "dependencies": {
      ...removed for readability...
  },
  "devDependencies": {}
}
```

Gulp file:

```
var gulp = require("gulp");`
var ts = require("gulp-typescript");
var tsProject = ts.createProject("tsconfig.json");
var sourcemaps = require('gulp-sourcemaps');

gulp.task("default", function () {
    return tsProject.src()
        .pipe(tsProject())
        .js
        .pipe(sourcemaps.init())
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("dist"));
});
```

tsconfig.json file:

```
{
    "compilerOptions": {
        "outDir": "./built",
        "allowJs": true,
        "target": "es5",
        "sourceMap": true
    },
    "include": [
        "./src/**/*"
    ]
}
```

launch.json file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "name": "debug node",
            "program": "${workspaceFolder}/src/app.ts",
            "request": "launch",
            "outFiles": [
                "${workspaceRoot}/dist/app.js"
            ]
        }
    ]
}
```

The URL at the end of app.js:
`//# sourceMappingURL=app.js.map`

The beginning of app.js.map:
`{"version":3,"names":[],"mappings":"","sources":["app.js"],"sourcesContent":["\"use strict...`

Help would be greatly appreciated. Thank you very much!

**Comment by roblourens** [comment]
Your sourcemaps are empty and don't actually point at the .ts files. In your gulpfile, you initialize gulp-sourcemaps after the compilation, so they don't actually do anything. See this example on how to use gulp-typescript with gulp-sourcemaps: https://www.npmjs.com/package/gulp-typescript#source-maps

**Comment by EmbarkingFrog** [comment]
@roblourens Thank you so very much. I can imagine it's frustrating to answer newbie questions but I've been stuck for a while because of this silly mistake and you've helped me a lot!

**Comment by roblourens** [comment]
No problem, gulp-sourcemaps is especially frustrating to set up correctly.
