### ISSUE TITLE
Beeping while working with Angular Material

### ISSUE THREAD

**Issue by amehlen** [Microsoft/vscode#41859]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Angular-BeastCode|Mik|5.2.2
live-sass|rit|1.2.0
LiveServer|rit|3.0.2
markdown-pdf|yza|0.1.7

Hello,
I'm working on an Angular Material Project in VS Code. Nearly everytime when I edit or save a modification I receive a different number of "beeps". I tried to reinstall VS Code and the plug-ins but the problem still exist. Also when I create or open another Angular Material Project. Working with another language there is no "beeping".

I'm working on a Windows 7 Pro in a virtual machine.

Best regards

---

Steps to Reproduce:

1. Open an Angular 5 Material project in VS Code.
2. Edit or save a modification
3. After a few seconds different numbers of "beeps"

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
Please try without extensions enabled.
