### ISSUE TITLE
catch up with TS 1.8.9 and honour file size event

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4185]

**Comment by chrisdias** [comment]
please see my comments in #4254, i am not prompted on OSX either.

**Comment by chrisdias** [comment]
related to #4007

**Comment by jrieken** [comment]
@chrisdias You see a crash because there are too many files. Unless we have a proper tsserver you must be careful to find the right amount of files - more than 500 less than it takes to crash the server

**Comment by chrisdias** [comment]
@jrieken when should i expect to get prompted to configure excludes then?

**Comment by jrieken** [comment]
when you have more than 500 files but (less than it takes to crash the server OR a recent server build which handles this better)
