### ISSUE TITLE
Git status (color) is not shown for files in a git submodule

### ISSUE THREAD

**Issue by reneroth** [Microsoft/vscode#41865]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.2.0
material-icon-theme|PKi|3.2.1
lorem-ipsum|Tyr|1.1.0
yaml|ada|0.0.9
vscode-eslint|dba|1.4.4
githistory|don|0.3.2
gitlens|eam|7.5.5
eppz-code|epp|1.2.41
php-intellisense|fel|2.2.5
auto-rename-tag|for|0.0.15
ginfuru-vscode-jekyll-syntax|gin|0.0.5
pug2html|gin|0.0.5
theme-monokai-pro-vscode|mon|1.1.5
atom-keybindings|ms-|3.0.4
vetur|oct|0.11.6
laravel-blade|one|1.13.0
stylelint|shi|0.32.0
vscode-fileutils|sle|2.7.1
highlight-bad-chars|wen|0.0.2

(18 theme extensions excluded)

---

Steps to Reproduce:

1. Open a git project with a git submodule
2. Change something in one of the submodule's files
3. See (or not see) missing color git status indicator for the file in the Explorer sidebar

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
This seems fixed by now.
