### ISSUE TITLE
Must fix letter d bug (SUPER IMPORTANT)!!!!!!!!!!!!

### ISSUE THREAD

**Issue by ntisod-te15-stefan** [Microsoft/vscode#41861]
The d is fucked up please fix (I have OCD).

https://gyazo.com/be852c80e3378756c0247e1a240d694c

**Comment by jrieken** [comment]
@ntisod-te15-stefan from where is that screen shot?

<img width="157" alt="screen shot 2018-01-19 at 18 03 19" src="https://user-images.githubusercontent.com/1794099/35162256-0eae10ae-fd43-11e7-8935-3c564bf22525.png">

**Comment by ntisod-te15-stefan** [comment]
It’s from the interactive playground.


fre 19 jan. 2018 kl. 18:04 skrev Johannes Rieken <notifications@github.com>:

**Comment by chrmarti** [comment]
Which OS is this? Seems like a different font than I have on OSX:
![image](https://user-images.githubusercontent.com/9205389/35213506-296441da-ff5e-11e7-9d06-a5d1c1bba991.png)

**Comment by ntisod-te15-stefan** [comment]
Visual studio code 1.19.2 running Windows 7 Enterprise

**Comment by Lisoph** [comment]
What font are you using?

**Comment by abolivar** [comment]
![screenshot from 2018-02-15 11-19-38](https://user-images.githubusercontent.com/92059/36267575-3b8e5d5e-1242-11e8-9a30-9514f9ce403f.png)

Version 1.21.0(Same error in Prod Version)
Ubuntu

**Comment by chrmarti** [comment]
For Linux see #35675.
