### ISSUE TITLE
Need CTRL K D from visual studio

### ISSUE THREAD

**Issue by MangeshPersonal** [Microsoft/vscode#41863]
Being a Visual studio guy i miss the CTRL + K + D feature for formating the code 
please make sure it is there in coming release

**Comment by rcjsuen** [comment]
@MangeshPersonal What kind of files are you trying to format? VS Code comes with formatters built-in for certain types of files.

**Comment by PaulInglis** [comment]
Update your Keyboard shortcuts to reflect this.  Currently it is assigned to "Move last selection to next find match", but you can easily assign it for formatting code.

- File > Preferences > Keyboard shortcuts (or CTRL + K, CTRL, + S
- Search for "Format Document", or "editor.action.formatDocument" and re assign the keyboard shortcut to CTRL + K, CTRL + D

**Comment by auchenberg** [comment]
Hi @MangeshPersonal 

You should try our Visual Studio Keymap which includes CTRL + K + D. https://marketplace.visualstudio.com/items?itemName=ms-vscode.vs-keybindings
