### ISSUE TITLE
Resetting credentials git in VSCODE

### ISSUE THREAD

**Issue by Atlacat** [Microsoft/vscode#41867]
- VSCode Version: newest
- OS Version: win 10

Steps to Reproduce:

1.Sign into git with incorrect credentials
2.Try to change the credentials or find documentation on changing creds

Does this issue occur when all extensions are disabled?: yes

**Comment by joaomoreno** [comment]
Code never remembers your credentials. Some other configured git credential manager is doing that. Please find which one it is and change it there.
