### ISSUE TITLE
Request for Dart Code to show up as recommended for Dart projects

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#41866]
Apologies if this isn't the right place to raise this - I've been digging through code and PRs trying to figure out where recommendations come from (or how to submit them) and it seems they used to come from a file `extensionTips.json` but that file has been deleted (apparently they're in product.json? but I don't know where that is).

It would be nice if [Dart Code](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code) showed up as a recommendation for workspaces containing `.dart` and `pubspec.yaml` files (disclaimer: it's my extension!). It's the only significant Dart extension and includes all the usual functionality (code completion, a debugger, etc.).

If the format is the same as the old `extensionTips.json` then I think it would be best added like this:

```js
    "Dart-Code.dart-code": "{**/*.dart,**/pubspec.yaml}",
```

**Comment by ramya-rao-a** [comment]
@Dantup As you can imagine maintaining the white list of recommendations doesn't scale well, especially for the numerous file types that are not supported out of the box in VS Code (i.e the ones that get "PlainText" assigned to them in the absence of supporting extensions.)

To that end, I had logged #38543 and the behavior described in https://github.com/Microsoft/vscode/issues/38543#issuecomment-358550640 is now available in the latest Insiders. Do share your thoughts about this approach in #38543

**Comment by DanTup** [comment]
Cool; that sounds reasonable. I'll see how it works in Insiders and post in that issue. Thanks!
