### ISSUE TITLE
ShowFixes:DeclareMethod'X' Generates New Method In Middle Of Imports Statement

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#41871]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.1
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|0.10.14
vscode-stylesheet-formatter|dba|0.2.0
git-extension-pack|don|0.1.3
githistory|don|0.3.2
gitlens|eam|7.5.5
EditorConfig|Edi|0.11.1
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.1.1
rest-client|hum|0.16.2
Angular1|joh|0.2.0
Angular2|joh|2.11.2
vscode-csharp-snippets|jor|0.2.0
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.0.0
open-html-in-browser|pea|0.0.2
vscode-icons|rob|7.19.0
bootstrap-3-snippets|wcw|0.1.0
JasmineSnippets|xab|1.0.1
vscode-open-in-github|ziy|1.3.1

---

Steps to Reproduce:

1.Create Angular4 ServiceX with multiple Import Statements
2. Inject ServiceX into component
3. In component, enter ServiceX method name (MethodX) which does not yet exist 
4. Select show fixes light bulb.
5 Select Declare method 'MethodX'
6. MethodX is generated in ServiceX in the middle of an import statement.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please paste up a code example
