### ISSUE TITLE
JavaScript and jQuery provide HTML snippet that matches selector [feature request]

### ISSUE THREAD

**Issue by Gaboik** [Microsoft/vscode#41873]
It would be great for Visual Studio Code to provide HTML snippets just like [those provided when editing CSS files](https://code.visualstudio.com/docs/languages/css#_hovers) for when you make a DOM query in a JavaScript file. I miss this feature especially when using jQuery.
For example, when writing something like
`$('th#Etat select option:selected')`
, I think it would be useful to have an HTML snippet provided when you hover your mouse over the string argument passed as the DOM query.
Sometimes, when i write complex selectors, I find myself pasting them into a CSS file to debug them using the HTML snippet, it would be more efficient to have them provided directly into the JS file.

I understand that this is a very specific feature request and I am not sure how one would go about implementing it. Perhaps this would only apply to the `$()` method?

**Comment by jrieken** [comment]
can (should?) been done as extension

**Comment by Gaboik** [comment]
I found [this extention](https://marketplace.visualstudio.com/items?itemName=lolkush.quickstart) which by it's name looks like it does what I want but has no documentation and doesn't seem to work.
