### ISSUE TITLE
Feature Request: Enable debugging of untitled JavaScript files

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#41877]
Just as with the [VSCode PowerShell extension](https://github.com/PowerShell/vscode-powershell/issues/555), I'd like to create a new JavaScript file, and debug it without explicitly saving it to the filesystem.

Right now, I'm getting an odd, generic error message when I try to debug an untitled file:

```
Attribute 'program' is not absolute ('${workspaceFolder}/Untitled-7'); consider adding '${workspaceFolder}/' as a prefix to make it absolute.
```

Is there already a way to do this?

Cheers,
Trevor Sullivan

**Comment by isidorn** [comment]
Not sure what powershell does to enable this but in theory the javascript extension would need to ask code for the content of the currently active file and use that content to debug it (since it can not read it from disk). Forwarding to @weinand to decide how feasible this is

**Comment by weinand** [comment]
Would require a debug adapter protocol addition. Not worth the effort.
