### ISSUE TITLE
Is there a way to run a /silent uninstaller for vscode?

### ISSUE THREAD

**Issue by goanpeca** [Microsoft/vscode#41872]
Hi @joaomoreno is there a way to have the VSCode uninstaller run in silent mode as well? I was following [these instructions](http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline) for the installer as well, but they do not seem to work for the uninstaller.

Thanks!

**Comment by joaomoreno** [comment]
Sure, these are the supported flags: http://www.jrsoftware.org/ishelp/topic_uninstcmdline.htm
