### ISSUE TITLE
Weird symbols in Terminal output when resizing

### ISSUE THREAD

**Issue by cgadam** [Microsoft/vscode#41880]
- VSCode Version: Version 1.19.2 (1.19.2)
- OS Version: macOS High Sierra 10.13.2

From time to time when I expand the area containing the TERMINAL output I get the following weird symbols. The terminal output breaks.

![screen shot 2018-01-19 at 15 01 23](https://user-images.githubusercontent.com/5420982/35164671-1880d68e-fd2a-11e7-8b51-d51fa83b9b4b.png)

I have to close the current TERMINAL and open a new one.
Couldn't find exact steps to reproduce but it happens often.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
