### ISSUE TITLE
Update Doesn't take

### ISSUE THREAD

**Issue by FlorianTolk** [Microsoft/vscode#41881]
After updating to the newest version of vscode, (Version 1.19) you have to launch vscode from the terminal, otherwise it thinks it's an outdated form.

I am using Ubuntu 17.10

**Comment by Tyriar** [comment]
Can you clarify what you mean by "it thinks it's an outdated form"? Also how did you update?

**Comment by FlorianTolk** [comment]
The notification will come up asking me to update to the version I just updated to

**Comment by Tyriar** [comment]
@FlorianTolk how did you update? And what version does the Help > About dialog show?
