### ISSUE TITLE
Scroll position is lost for (Working Tree) tabs

### ISSUE THREAD

**Issue by jarrettv** [Microsoft/vscode#41883]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.13.0-25-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.4
vscode-npm|fkn|3.3.0
vscode-mysql|for|0.2.2
python|ms-|0.9.1
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.0.0
vscode-input-sequence|tom|0.2.0
ReactSnippets|xab|1.7.0

---

Steps to Reproduce:

1. Open a file from git list of changed files
2. Scroll down the file
3. Tab to another tab
4. Tab back, notice the file has lost scroll position

**Comment by shobhitchittora** [comment]
@jarrettv 
I ***cannot*** reproduce this on macOS (10.13.2) and latest Code. The Working tree tab scrolls down to the first change ( git diff ) in the file. If you think that should not be the intended behavior, please suggest an alternative.
