### ISSUE TITLE
open file

### ISSUE THREAD

**Issue by vendforce** [Microsoft/vscode#41886]
- VSCode Version: 1.19.2
- OS Version: Arch 

https://imgur.com/a/f9lCF

Can anyone tell me where the open file option is , I can see start new file, open folder . where is open file ? 
why can't I just search for just a single file ?

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/35180537-b3aab3f4-fdb2-11e7-8634-3c4ab42b0f0a.png)
