### ISSUE TITLE
sync setting emitts an Error message

### ISSUE THREAD

**Issue by tmgaki** [Microsoft/vscode#41899]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 
code-settings-sync|Sha|2.8.7
Reproduces without extensions: No

1. Sync:upload/update ( [alt]+[shift]+[U] )
2. Error has occured 
DevelopperTool :
Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
e.doShow @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2744

and shown following message.
Sync : Error Logged In Console (Help menu > Toggle Developer Tools).

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
