### ISSUE TITLE
duplicated git status representations in the explorer view are shown with git on mingw64

### ISSUE THREAD

**Issue by taketori** [Microsoft/vscode#41896]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.73
vs-script-commands|mkl|7.0.0

- git version: 2.15.0
- vscode settings about git:  
```
 "git.path": "batpath/GitOnMSYS2ForVSCode.bat", 
```

 I have used the .bat file which is written in #4651 and the bat have worked well except this issue.
the output `~~.bat status -z -u` looks same as output `git status -z -u` like below.

```
$ bapath/GitOnMSYS2ForVSCode.bat status -z -u
 M concat.go M converter.go M download.go ~~
$ git status -z -u
 M concat.go M converter.go M download.go ~~
```
---

Steps to Reproduce:

1. edit file(s) in the folder git manages and save it.
2. "M" is shown like below.
3.  or just change active files in vscode, "M"s are added.

![image](https://user-images.githubusercontent.com/22736/35181462-76f1ece0-fe05-11e7-8c8f-3033bcafba67.png)

``
text below is shown in output panel.
```
git rev-parse --show-toplevel
git config --get commit.template
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
fatal: ambiguous argument 'master@u': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

git rev-list --left-right master...master@u
fatal: ambiguous argument 'master...master@u': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

git for-each-ref --format %(refname) %(objectname)
git remote --verbose
```

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Can you try to reproduce in our [insider release](https://code.visualstudio.com/insiders)?

**Comment by ipsusila** [comment]
This issue is related/similar with #41509.

**Comment by taketori** [comment]
I'm sorry for my late reply.
I tried insider release, but problem kept happening.
but I version-uped vscode to 1.20, it does not happen.
I don't know what's the difference from insider release and vscode still show git errors like this pic.
![image](https://user-images.githubusercontent.com/22736/36143142-94f2fb76-10ed-11e8-94fb-64ee81705a32.png)
but, for me, things are looking perfect. so I'll close this issue.
thank you anyway!
