### ISSUE TITLE
`paths` options not working in jsconfig.json

### ISSUE THREAD

**Issue by stanleynguyen** [Microsoft/vscode#41890]
- VSCode Version: 1.19.2
- OS Version: macOS High Sierra 10.13.2

I have a file structure of this way
```
shared
|- some-file
|- some-folder
src1
|- jsconfig.js
|- some-other-file
|- some-other-folder
```

my `jsconfig.json` is
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "*": ["*", "../shared/*"]
    }
  }
}
```

However, I only get suggestions from the `baseUrl` which is `src1`, but none from `shared` folder

Does this issue occur when all extensions are disabled?: Yes

**Comment by stanleynguyen** [comment]
Hi @mjbvz, have you look into this problem? Is there any quick fix that I can do at the moment because this is critical to my productivity? Thank you.

**Comment by Munksey** [comment]
I'm having a similar issue, but I'm pretty sure the root cause is because we also have a `tsconfig.json` file in the root.

I tried creating a bare minimum project.

Structure

```
app
| - file1.js
| - file2.js
jsconfig.json
tsconfig.json
```

`jsconfig.json`

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "app/*": ["./app/*"]
    }
  },
  "exclude": [
    "node_modules"
  ],
}
```

`tsconfig.json`

```
{
  "exclude": [
    "node_modules"
  ]
}
```

`file1.js`

```
import { two } from 'app/file2';
```

`file2.js`

```
export two = 2;
```

WIth the `tsconfig.json` file, my definition navigation and import statement autocomplete fail.

**Comment by stanleynguyen** [comment]
Thanks @Munksey for the comment. However, for my case, I only use `jsconfig.json` (as I'm not using typescript anywhere in my project) Would there possibly be any tsconfig from vscode or anything that might be the cause?

**Comment by Munksey** [comment]
Hey @stanleynguyen. I was simply providing another example in which `jsconfig.json` wasn't working. Hoping that they might be able to be resolved with the same PR.

Although, I tried setting up an example similar to yours and I was surprised to find your example didn't work (as the documentation seems to indicate it should). However, I experimented a bit and found that changing the `baseUrl` to go back a directory fixed the problem.

Try doing this instead:

```
{
  "compilerOptions": {
    "baseUrl": "../",
    "paths": {
      "*": ["*", "./shared/*"]
    },
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by stanleynguyen** [comment]
@Munksey still doesn't work for me though :( However, looking at this, I think the problem might be with the go back directory in the `paths` field.

**Comment by Munksey** [comment]
That was one of things I changed. I made it so `../shared/*` becomes `./shared/*`.  And the value for `baseUrl` becomes `../`.

What's interesting is that you actually made me realize that I can put `jsconfig.json` in a subdirectory and I was able to come up with a solution for my odd webpack/javascript/typescript project. So my problem is kind of irrelevant now.

If making the two changes I listed above doesn't help, maybe you can try a plugin called "Path Intellisense" (https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense). There's a field called `path-intellisense.mappings` that you can use for custom resolver paths.

**Comment by stanleynguyen** [comment]
Thanks @Munksey  for the suggestion. However, the most specific I can go for the plugins is by workspace but I would need different mappings for different sub-folders so this doesn't help either :(

**Comment by stanleynguyen** [comment]
Any advice? @mjbvz

**Comment by leoniDEV** [comment]
@Munksey I think that if there aren't some special configurations of which the JS files need you can have only the tsconfig.json at the root with `"allowJS": true `and `"checkJS": true`

**Comment by ajhyndman** [comment]
I think it might actually be in the documentation, but I hadn't seen it spelled out, and just realised today that the paths key is just using glob pattern matching.  That means that the `"paths"` key will only match modules at one level of depth, unless you use a pattern like the following:

```
  "baseUrl": "src",
  "paths": {
      "**/*": ["**/*"]
    },
```

**Comment by stanleynguyen** [comment]
Resolved in the newest update of VSCode 👍
