### ISSUE TITLE
终端中的字体很奇怪，自从一次跟新后就出现这样的问题，将就了很久，受不了

### ISSUE THREAD

**Issue by Hideer** [Microsoft/vscode#41892]
- VSCode Version:版本 1.19.2
提交 490ef761b76b3f3b3832eff7a588aac891e5fe80
日期 2018-01-10T15:55:03.538Z
Shell 1.7.9
渲染器 58.0.3029.110
Node 7.9.0
架构 x64
- OS Version:Windows

Steps to Reproduce:
1.输入打开终端的时候字体的间距特别大，如图
![image](https://user-images.githubusercontent.com/31301552/35180661-93a8420a-fdef-11e7-92f5-6b7c3f3475a4.png)

2.

Does this issue occur when all extensions are disabled?: Yes/No
[](url)

**Comment by levinit** [comment]
设置使用等宽字体

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.

**Comment by Hideer** [comment]
excuse me！ Do you know how to solve this problem?

**Comment by levinit** [comment]
@Hideer   monospaced font

**Comment by Hideer** [comment]
编辑器中的字体是正常了，难道终端中需要专门的字体设置么，如果是，那是在哪里呢

**Comment by levinit** [comment]
我平时没用windows
你看看你cmd里面字体有没有问题 在那里设置看看 终端用bash

**Comment by Hideer** [comment]
好的我试试，Thanks!

**Comment by Hideer** [comment]
然而并没有用。。。。
