### ISSUE TITLE
`yo code` line break problems on OSX

### ISSUE THREAD

**Issue by FabianLauer** [Microsoft/vscode#419]
It's nothing serious: On OSX, line breaks in the `yo code` tool don't seem to work properly.
Am I right here or is this an issue with yo itself?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2205595/11319942/b5b94342-9089-11e5-9efb-5503c525512d.gif)

**Comment by chrisdias** [comment]
this is a yo issue. if you make the terminal wider you won't see this behavior.
