### ISSUE TITLE
Indent using spaces shows wrong value for `Configured Tab Size`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4190]
Testing #3922

![image](https://cloud.githubusercontent.com/assets/22350/13750297/28c2bfa6-ea05-11e5-9fa5-7d201bd6733e.png)

The file is indented with spaces and the indentation size is 2. So I'd expect 2 to be the default selected option in that list.

Also, as per #3590, the label should be *Current Indentation Size* to match that expectation.

**Comment by isidorn** [comment]
After discussing with @joaomoreno we will leave the title just the default selected element will be the one from the current file.
