### ISSUE TITLE
SCM: Viewlet should focus the respective repository from the focused file

### ISSUE THREAD

**Issue by michelkaporin** [microsoft/vscode#41901]
- VSCode Version: Latest Insiders
- OS Version: Mac OS

Steps to Reproduce:

1. Open a workspace that contains two repositories
2. Open any file from the second folder repository and start working on it. 
3. Go to SCM viewlet
-> SCM provider focus is on the repository from the top most folder from the workspace.

It would be great, if the SCM provider of the currently opened file would be highlighted. In other words, the tool has to somehow detect the workspace project I was working on lately that I'd like to commit.

Currently I always have to do manual selection of the provider (I am working only on the second repo), which is annoying.

**Comment by joaomoreno** [comment]
Going with #45179 instead

**Comment by michelkaporin** [comment]
@joaomoreno isn't #45179 a different issue? From what I understand text box message is lost together with the focus in #45179, whereas here SCM viewlet isn't selecting a repository I am working on. Got used to it by now, but I find it still a little bit annoying.

**Comment by joaomoreno** [comment]
Oh man, yeah! This one is about list focus, not DOM focus. Thanks for the ping!
