### ISSUE TITLE
How to make ctrl + p search through the current opened folder

### ISSUE THREAD

**Issue by elieobeid7** [Microsoft/vscode#41900]
currently <kbd>Ctrl</kbd> + <kbd>P</kbd> search through any files in current or previous projects. So If I had opened a project recently and now I'm working on a different project, I still see them either in the search result or in recently opened files also in search.

Look through github issues, and they say I can clear the history, indeed I did and it worked, but I don't want to clear the history each time, I work on a new project. I have to remove the files and remove recent opened files and so on and so forth.

Is it possible to restrict the search to the current opened folder and its subfolders?

**Comment by roblourens** [comment]
The "Recently opened" files should show up for individual files that were opened outside of the current folder. When you say "I had opened a project recently" did you open another folder? Are you using a multiroot workspace?

**Comment by elieobeid7** [comment]
I didn't use workspace, should I?  I chose, `open folder` I have two different folders:

`x/a`
`x/b`

`a` and `b` are two different projects I opened `a`, edited the code, closed the folder, opened folder `b` and I still can access everything in `a` through <kbd>Ctrl</kbd> + <kbd>P</kbd>. Tried to restart vscode, tried many things, can't get the folders from `b` to disappear.

**Comment by roblourens** [comment]
I see. In the ctrl+p results, on the right side of the top row, does it say "Recently Opened" or "File Results"?

A screenshot might help. @chrmarti?

**Comment by elieobeid7** [comment]
I attached two screenshots, I used to work in a folder called `jr`, closed that, opened `diaspora` i still see the files from `jr` in recent files and in file results.

It's incredibly annoying, since as shown in the screenshots, if I want to go to `index.php` of `diaspora` i see all index files in `jr` and my friend jr has plenty of them, guess he if he had a son he'd call him index too! he just loves that name :)

Please note, I'm using latest build on windows 10, downloaded vs code couple of days ago, I don't remember having this problem on my fedora. I can't turn on fedora now because I don't know where's my fedora now, but I guess i didn't have the problem on fedora. 

I also don't know if the issue is present in previous windows releases because I just downloaded it on windows few days ago.

![screenshot 2](https://user-images.githubusercontent.com/660142/35187804-ac44c354-fe32-11e7-8f6c-a4b2e16db31c.png)
![screenshot 3](https://user-images.githubusercontent.com/660142/35187805-ac6d0f94-fe32-11e7-82d0-0d505b5b771b.png)

**Comment by roblourens** [comment]
In both screenshots, you have the 'diaspora' folder open. You would see this if you opened the 'jr/index.php' file in the 'diapora' window at some point.

**Comment by elieobeid7** [comment]
no i did the test in a clean way, i removed all the history of jr, then I opened jr, then I closed the folder `file-> close folder` then restarted vs code, then opened diaspora. The path:

`D:\xampp\htdocs\web\jr`
`D:\xampp\htdocs\web\diaspora`


Again the test was a clean test, because previous to this test, i deleted all trace of jr from vs code in order to be able to work on diaspora

**Comment by chrmarti** [comment]
@bpasero Is there anything that might make recent files from one folder show up while in a different folder? I can't reproduce the described behavior.

**Comment by elieobeid7** [comment]
Guys do you like me to make a screen recording and upload a video?

**Comment by bpasero** [comment]
@chrmarti unlikely, the list of recently opened is stored in localStorage with the workspace identifier as key. The only time we migrate that data to somewhere else is when you enter a multi-root workspace after being in a single-folder workspace.

**Comment by chrmarti** [comment]
@elieobeid7 Does it reproduce when you first Clear Editor History in each of the two folders? If so, a recording might indeed help us understand what is happening.

**Comment by elieobeid7** [comment]
closing the issue for now, can't reproduce it while recording, perhaps what needed to be done is clear editor history, I'll reopen it and attach a recording to it if the issue happens again.
