### ISSUE TITLE
控制台移动到右侧输出有时显示会出现排版错误。Output sometimes shows a typographical error, when he console moves to the right .

### ISSUE THREAD

**Issue by Lnaight** [Microsoft/vscode#41907]
在输出长的文字时，排版会有些错位，
In the output of long text, typesetting will be some misplaced,

![image](https://user-images.githubusercontent.com/21970395/35184635-58e212d8-fe33-11e7-9ca1-0502954d9d58.png)

**Comment by isidorn** [comment]
@Lnaight please provide reproducable steps.
Can you also reproduce with vscode insiders https://code.visualstudio.com/insiders/
