### ISSUE TITLE
high usage of  cpu and memory

### ISSUE THREAD

**Issue by levinit** [Microsoft/vscode#41906]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.14.13-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
code-settings-sync|Sha|2.8.7
project-manager|ale|0.23.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.4
prettier-vscode|esb|1.1.2
auto-rename-tag|for|0.0.15
ftp-sync|luk|0.3.3
postcss-language|mhm|2.0.2
HTMLHint|mka|0.4.0
node-debug2|ms-|1.20.0
stylelint|shi|0.32.0

---

Steps to Reproduce:

1. open vscode

Reproduces without extensions: Yes/No

![2018-01-20 22-36-01](https://user-images.githubusercontent.com/24387319/35184566-573ae460-fe32-11e7-88c8-8851df1cc453.png)

cpu usage over 30%+,   memory always 2G+
auto-complete does not work

**Comment by jrieken** [comment]
please use this guide for more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues#collect-information-about-the-running-vs-code

**Comment by levinit** [comment]
I reinstalled vscode, this problem has never happened...😂
