### ISSUE TITLE
wrong order of menu in extensions view

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#41918]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (d21e6a3e388897a2250cb10ae897b6481e0bd61d, 2018-01-19T07:18:51.463Z)</li>
	<li>OS Version: Windows_NT x64 10.0.16299</li>
	<li><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.4
gitlens|eam|7.5.5
python|ms-|0.9.1
debugger-for-chrome|msj|4.0.0

</details></li>
</ul>

---

Steps to Reproduce:

1. Click "More"(...) in the extension view
2. bug

![5fd624fe87efe9c45f4d0bd5afc45627](https://user-images.githubusercontent.com/8474118/35189482-94699fbe-fe8e-11e7-98da-f66be02cfe85.png)

<details>
 <summary>stable 1.19.2</summary>

![e951f8a098dd90819af7025ddcfcb537](https://user-images.githubusercontent.com/8474118/35189518-50057b08-fe8f-11e7-9211-adedadc835cf.png)

</details>

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@bpasero This is the issue related to order computation for actions
