### ISSUE TITLE
Open side-by-side shortcut changed to alt+click

### ISSUE THREAD

**Issue by markgoho-EDT** [Microsoft/vscode#41917]
- VSCode Version: 1.20.0-insider
- OS Version:

Steps to Reproduce:

1. Ctrl+click on a file in the sidebar browser
2. File gets highlighted but does not open a new editor side by side
3. Alt+click achieves the intended effect

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This is because we recently added support for multi-select in the explorer. On Mondays Insider build you can change this via `"workbench.multiSelectModifier": "alt"`
