### ISSUE TITLE
gulp vscode-linux-arm-min fails on 1.9.1

### ISSUE THREAD

**Issue by couven92** [Microsoft/vscode#41913]
- VSCode Version: 1.9.1
- OS Version: Ubuntu Xenial 16.04.3 LTS

Steps to Reproduce:

1. `git checkout tags/1.9.1`
2. Follow the instructions for [Cross Compiling for Debian Based Linux](https://github.com/Microsoft/vscode-wiki/blob/6fe63f1ab90831e1e81651415d3863db799e7360/Cross-Compiling-for-Debian-Based-Linux.md)
3. run `./node_modules/.bin/gulp vscode-linux-arm-min`

Compiling for arm fails:
```
Error: ./extensions/typescript/src/typescriptService.ts (24,3): Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
undefined
```

**Comment by couven92** [comment]
I can also confirm that the issue occurs when building natively on a armv71 Raspberry Pi 3 running Raspbian. The error message is identical

**Comment by mjbvz** [comment]
I think you want `1.19.1`. `1.9.1` is pretty old

**Comment by couven92** [comment]
Oh! I am soo sorry, I must have typo'ed during checkout. My bad, closing...
