### ISSUE TITLE
process not exit

### ISSUE THREAD

**Issue by malaotou** [Microsoft/vscode#41910]
I know the visual code is packaged with electron。
the problem is when click the closing button,the code.exe process is still there.

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
javadebugger|don|0.1.5
Angular2|joh|2.11.2
debugger-for-chrome|msj|4.0.0
angular-native-seed-snippets|seb|0.0.1
nativescript|Tel|0.7.2
nativescript-ng2-snippets|www|2.0.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by malaotou** [comment]
I developed  a election app also have the problem to solve.

**Comment by jrieken** [comment]
use this to generate more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues#collect-information-about-the-running-vs-code
