### ISSUE TITLE
Debugger does not pick up bash_profile exports

### ISSUE THREAD

**Issue by lidderupk** [Microsoft/vscode#41916]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
gc-excelviewer|Gra|2.0.17
vscode-docker|Pet|0.0.23
lorem-ipsum|Tyr|1.1.0
Bookmarks|ale|0.18.0
django-html|bib|1.2.0
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
githistory|don|0.3.2
gitlens|eam|7.5.5
vscode-terminals|fab|1.8.0
auto-close-tag|for|0.5.5
code-runner|for|0.8.7
Scala|itr|0.1.7
MagicPython|mag|1.0.12
Kotlin|mat|1.4.0
rainbow-csv|mec|0.0.1
mssql|ms-|1.3.0
python|ms-|0.9.1
debugger-for-chrome|msj|4.0.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6

(8 theme extensions excluded)

---

Steps to Reproduce:
The bash_profile is not picked when using the debug feature. 

1. I have the following in my bash_profile file:
`export DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/clidriver/lib:$DYLD_LIBRARY_PATH`

Without that the `ibm_db` python module gives me an error in debugger:
`ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ibm_db.cpython-36m-darwin.so, 2): Library not loaded: libdb2.dylib`

2. The debugger works if I manually put this in the env dictionary in launch.json file

```
{
            "name": "db2",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "db2.py",
            "cwd": "${workspaceRoot}",
            "args": [],
            "env": {
                "DYLD_LIBRARY_PATH": "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/clidriver/lib"
            },
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
```
Is this working as expected? Thank you.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
https://github.com/DonJayamanne/pythonVSCode
