### ISSUE TITLE
There is no error to prompt the user when no .NET Framework is installed

### ISSUE THREAD

**Issue by steffen-s** [Microsoft/vscode#41915]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharpfixformat|Leo|0.0.56
csharp|ms-|1.13.1

---

I tried to install VS Code to do some .NET Core development yesterday. I ran into the issue that Intellisense wasn't working for C#, despite the C# extensions being installed. No error dialogs popped up.

After doing some digging, I came across the VS Code setup documentation that specifies .NET Framework 4.5.2 as a requirement, so I installed that. Trying to run VS Code again, now I got an error popup that I needed .NET Framework 4.6, which i then installed and everything was fine - Intellisense and all.

I have already submitted a [pull request](https://github.com/Microsoft/vscode-docs/pull/1360) to rectify the inaccuracy in the setup documentation.

---

Expected Outcome:

I think it would also be beneficial to prompt users when there is no .NET Framework installed at all, rather than just prompting them when they have a version that is too old.

---

Steps to Reproduce:

1. Make sure that no .NET Framework is installed on the PC
2. Install VS Code on Windows 7 - 64 bit
3. Install dotnet-sdk-2.1.4-win-gs-x64
4. Install C# extension + reload VS Code
5. Create a new dotnet console app
6. Type some code and try to use Intellisense - it doesn't work
7. Review error log: FileWatcher is repeatedly attempted to start until it eventually fails
8. Install .NET Framework 4.6 or higher
9. Restart VS Code and repeat step 6) - Intellisense now works

Reproduces without extensions: not tested

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
