### ISSUE TITLE
Inconsistent coloring of CSS rules values

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#4191]
- Switch to the Dark+ default theme
- open a CSS file:
![image](https://cloud.githubusercontent.com/assets/6461412/13750321/3f25dbc0-ea05-11e5-9962-8b33878292ed.png)
- Open a LESS file:
![image](https://cloud.githubusercontent.com/assets/6461412/13750226/ddb12caa-ea04-11e5-878a-f2d28b2b14d5.png)
Values are white, red and blue

- open a SASS file:
![image](https://cloud.githubusercontent.com/assets/6461412/13750293/23d96dbe-ea05-11e5-9686-0658ece2062d.png)
Values are white

**Comment by aeschli** [comment]
Need to decide if we stick with white on the Default VS theme
![image](https://cloud.githubusercontent.com/assets/6461412/13751083/c328fe72-ea08-11e5-9cc3-b35943f2b05f.png)

**Comment by aeschli** [comment]
Change introduced by #3534

**Comment by aeschli** [comment]
To verify: Verify colors for SASS.
Less still has some issues caused by the inconsistent grammar.
Eventually we will have to look for a better grammar.

**Comment by isidorn** [comment]
Does this mean the SASS colors should be the same as in the last stable release?

**Comment by aeschli** [comment]
No SASS value are now consistent to what CSS shows:
- red in Dark Plus
- white in Dark VS

**Comment by isidorn** [comment]
Yup, looks like that now
