### ISSUE TITLE
macOS, powershell 6, and integrated terminal question? 

### ISSUE THREAD

**Issue by minoseah629** [Microsoft/vscode#41920]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
gitlens|eam|7.5.5
mssql|ms-|1.3.0
python|ms-|0.9.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
java|red|0.17.0
vscode-arduino|vsc|0.2.10
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1. Have powershell 6 installed on machine

I want to change my integrated terminal to powershell 6 instead of bash. 
I see this setting is available: "terminal.integrated.shell.osx": 
I had no issue with adjusted my work machine to use powershell 6 instead of cmd using 
"terminal.integrated.shell.windows": "cmd.exe"

**Comment by Tyriar** [comment]
If you're on mac you just need to point `terminal.integrated.shell.osx` to the powershell executable. If it's on the `$PATH` you can use just the name, `powershell` I'm guessing. If it's not on the `$PATH` you will need to fully qualify the path; `/path/to/powershell`

**Comment by minoseah629** [comment]
thank you.
