### ISSUE TITLE
leakage from debug output

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4192]
* have a nodejs app like below
* let it run and see how uuids are printed
* take a heap snapshot after ~1min
* let it runs for another while (~2min)
* take another heap snapshot, heap grew by a few MB

```
var uuid = require('node-uuid');

console.log('starting');
setInterval(() => console.log(uuid.v4()), 100);

```

**Comment by jrieken** [comment]
[Archive 4.zip](https://github.com/Microsoft/vscode/files/172334/Archive.4.zip)

**Comment by joaomoreno** [comment]
I don't think this is a good memory leak test setup. The snippet will endlessly emit output, which gets rendered in a tree. Obviously, the memory will grow.

A better test is to repeatedly start an application that always emits lots of output:

```javascript
var msg = 'hello leak\n';

for (var i = 0; i < 10; i++) {
    msg = msg + msg;
}

console.log(msg);
```

Testing it this way, just like #4114, you'll find that there is no *big* leak here.

[Heap-20160315T231100.heaptimeline 2.zip](https://github.com/Microsoft/vscode/files/174928/Heap-20160315T231100.heaptimeline.2.zip)

![screen shot 2016-03-15 at 23 26 20](https://cloud.githubusercontent.com/assets/22350/13796207/b94614aa-eb05-11e5-8aa0-84d055e0a7da.png)

There are a few leaks (marked red in screenshot) but they are nothing really worrying. In this 1000-line repeated `hello leak` test, after repeating it 6 times, we got 129KB of leaked memory. It's a leak, but definitely not big.

But if you follow the rabbit hole, you'll eventually get there: [every time a new debug session is created, a bunch of new disposables are added to the `toDispose` list of the `DebugService`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L227). This list is only disposed when the service is disposed, so everything those disposables hang on too are leaking, namely instances of `RawDebugSession` which I believe are the essence of the whole leak.

@jrieken please make sure my logic is sound here.

Moving this to @isidorn.

**Comment by jrieken** [comment]
> I don't think this is a good memory leak test setup. The snippet will endlessly emit output, which gets rendered in a tree. Obviously, the memory will grow.

I disagree because the output should be protected against that. From one point on, memory should not grow anymore but usage should become constant (hitting a max output length).

**Comment by joaomoreno** [comment]
But you should only start looking at memory leaks *after* reaching that max output length...

**Comment by isidorn** [comment]
Makes sense, I can definetely add an output limit to the repl - we already have one for the output panel.
I will also handle the listeners in a better way - thanks for finding that

**Comment by jrieken** [comment]
![screen shot 2016-03-21 at 12 16 30](https://cloud.githubusercontent.com/assets/1794099/13917069/c5c412ce-ef5e-11e5-8c0a-cb3418c1fdb7.png)

Over the course of 90 seconds more and more instances of `t` have been accumulated. Since `app.js` roughly prints 10 messages per second, I assume that I have reached the max already

**Comment by jrieken** [comment]
![screen shot 2016-03-21 at 12 21 23](https://cloud.githubusercontent.com/assets/1794099/13917168/715dcb20-ef5f-11e5-9344-974de7f0aa53.png)

Running for 120 seconds with 100 messages printed per second.

**Comment by joaomoreno** [comment]
Yup looks leaky.

**Comment by isidorn** [comment]
Joao and me were looking into this now and we came to the conclussion that here is no leak due to:

1. If you run the program emitting more and more output debug isholding onto those output objects in order to display them so it is expected that the memory is growing. Btw this is limited to 10000 elements.
2. If you run the program 5 times, and compare runs from 2 to 4 you can notice that there is no increase in memory and no extra objects are alocated on the heap.

**Comment by isidorn** [comment]
@jrieken if you disagree ping me and I can come to your desk and show you what I see

**Comment by jrieken** [comment]
yeah, we should do that. With [120 * 100](https://github.com/Microsoft/vscode/issues/4192#issuecomment-199231635) I should have reached your limit
