### ISSUE TITLE
[scss] provide proposals for at-keywords

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#41929]
Hi,
Im trying migrate from Sublime Text to VSCode. 
Intelisense is really bad in SCSS language against SASS, why, its a same language (mix CSS & SASS).

For example:
in SASS a wrote if and i see hint "@if statement", in SCSS not. ( directives, loops, functions, nothing works). In SASS yep.

Native functions like (abs / ceil / nth / append ... etc, ) not works too. 

Screenshot: SASS https://goo.gl/Y7dXPi ; https://goo.gl/okxSoF
Screenshot: SCSS https://goo.gl/KNn3hq ; https://goo.gl/ZriZaF

Is possible to solve it with some workaround or some settings? Its very important for me (Im SCSS coder).

Thx for ur answer.

**Comment by aeschli** [comment]
Please let me add some explainations here:
- VSCode has only built-in support for SCSS, but not for SASS. You probably added some extensions that added some support such as snippets, such as a snippet for @each
- To add the same snippet to SCSS, just use `File > Preferences > User Snippets' and add the `@each` snippet. 
- What you are looking for are built-in proposals for at-keywords, which we don't have. I changed the title

**Comment by Kcko** [comment]
Hi, at first thank for your reply.
You have right, i added SASS extension from Robin Bentley from Marker Place, i will contact author if is possible to create extension for SCSS or I will create own extension or set of snippets.

I will migrate this cool plugin from Sublime Text to VSC https://packagecontrol.io/packages/SCSS%20Snippets%20Complete#selector 

Will anyone be interested in it?

**Comment by Kcko** [comment]
@aeschli can you explain me last thing = differefent behavior  SASS against SCSS?

SASS: see https://goo.gl/SngxCN  (suggestion for map functions)
SCSS: see https://goo.gl/isKSXc (no suggestion for map),  works only when i wrote someValue and now i trigger suggestion (https://goo.gl/QSkTZ8) 

Why so different behavior?
