### ISSUE TITLE
[Bug] Cannot copy full snippet of codes when they are collasped

### ISSUE THREAD

**Issue by MaleDong** [Microsoft/vscode#41922]
- VSCode Version: 1.19.2
- OS Version: Windows 8.1 Professional (SP1) x32 (Not have a test for x64 or on other versions of Windows).

Steps to Reproduce:

1.  Use "//#region"……"//#endregion" to wrap a snippet of codes, something like this:
```
//#region Try wrap with codes
function aa(){
  console.log("Hello World");
}
//#endregion
```
2.  Collaspe it by clicking "//#region" part at its left with your mouse left. Then the snippet of codes are collasped.

3.  Copy the collasped part "//#region ...."

4. Do paste and you will find that ONLY "//#region...." is found WITHOUT "function aa(){...}".
This problem is always happening to all senarios of collasped ones when copying and pasting.

5. See the attached zip file to reproduce this issue:
[Bugs.zip](https://github.com/Microsoft/vscode/files/1649637/Bugs.zip)

**Comment by raulesgalindo** [comment]
It works good on linux

![screenshot from 2018-01-21 10-20-11](https://user-images.githubusercontent.com/11840157/35195649-c0ac1f38-fe94-11e7-860d-705baa744709.png)

**Comment by MaleDong** [comment]
@raulesgalindo ： Thx!

I made an addition to my previous：Not have a test for x64 or on other versions of Windows. And mine is on x32 of Win8.1 (SP1).

**Comment by aeschli** [comment]
When copying, just make sure that the selection goes until the next, not folded line, so it include also the folded content.

![image](https://user-images.githubusercontent.com/6461412/35213789-22370acc-ff5f-11e7-8215-dff9772e4bb8.png)
![image](https://user-images.githubusercontent.com/6461412/35213799-28e1e540-ff5f-11e7-985c-e6e316ac679e.png)

**Comment by MaleDong** [comment]
Sorry but what I mean that, if you use Visual Studio, you'll find that if you folder the snippet of codes and do copy for the folded part, it's always the full codes; compared with this, Visual Studio Code only let you copy the folded statement instead of the full ones. 

Please re-open this issue.

**Comment by aeschli** [comment]
@MaleDong Just to mention, Linux and Windows versions of VSCode behave the same, do you see something else?
