### ISSUE TITLE
Allow rebinding of command palette/quick open navigation keys.

### ISSUE THREAD

**Issue by Kinths** [Microsoft/vscode#41926]
When using the command palette or quick open you are forced to use arrow keys to navigate the list. It would be nice to be able to rebind these keys as using arrow keys is awkward and breaks typing flow. 

As far as I can find there is no way to rebind these keys currently, the list.* keybindings work for autocomplete and some other windows but don't work for command palette or quick open.

Please consider adding the ability to rebind the navigation of these windows, thank you. Sorry, if this is already possible but I was unable to find a way of doing it.

**Comment by bpasero** [comment]
`list.focusUp` and `list.focusDown` can be rebound in keybindings editor. every list and tree will support it.

**Comment by Kinths** [comment]
I have these bound and it doesn't work on the palette or quick open lists

**Comment by Kinths** [comment]
list.focusUp and focusDown don't work on these menus, so can this be reopened?
