### ISSUE TITLE
Typescript highlighting issue

### ISSUE THREAD

**Issue by eltimmo** [Microsoft/vscode#41934]
Hi,

  I've noticed this, it's only cosmetic. Following code will turn green after the first less than condition, if this is made greater than it's okay.

1.19.2 - VSCode Version:
Windows 10 10.0.16299- OS Version:

Steps to Reproduce:

Code as below

```
topYields.sort ((share1,share2) => {
    if (share1.yield < share2.yield) { return 1; }
    if (share1.yield > share2.yield) { return -1; }
    return 0;
  });
```

![image](https://user-images.githubusercontent.com/27624232/35197170-99d02564-fed3-11e7-9887-7fa778370612.png)

![image](https://user-images.githubusercontent.com/27624232/35197189-f3e59a98-fed3-11e7-9302-981e3d555fa0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#562
