### ISSUE TITLE
File preview with quick open 

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#41930]
Im migrating from Sublime Text to VScode and I can not find or set one property (feature), that sublime text has.

Quick pane with file listing show file preview without file open in ST.

Screenshot: https://goo.gl/wD4VDZ
In VSC code i must open file at first :( , does this feature exist or will?

Many Thx for reply.

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/8939
