### ISSUE TITLE
One snippet for all languages?

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#41931]
Is possible create a snippet for more languages or globally for all?
I dont want  repeat the same snippet for php / js / scss (Its mean, create nippet to $lang.json and save it, and when it will change in future , repair in all $lang.json files).

It is a possible in current version of VSC?

**Comment by usernamehw** [comment]
In [Insiders](https://code.visualstudio.com/insiders/) version - yes. https://github.com/Microsoft/vscode/issues/13182#issuecomment-355301995

Should be out in stable in the next release.
