### ISSUE TITLE
VSCode comes to crawling speed when opening Microsoft/Typescript repo

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#41932]
Steps to Reproduce:

1. Open github.com/Microsoft/TypeScript/
2. Build + Run Tests
3. May be edit a couple of files. Everything just feels very laggy

I have tried to use VSCode multiple times to work on a Typescript PR but it seems vscode just can't handle the size of repo. It simply has frozen up on me many times for a couple of seconds. Clicking around the editor, cursor responds after a while. Type on integrated terminal, UI doesn't respond with latest keystroke for a couple of seconds.

ActivityMonitor shows that CodeHelper is taking 3GB of memory and 271% CPU.  This is while vscode is idle. 

```
Version:          Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
OS Version:       Darwin x64 16.6.0)
CPUs:             Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)
Memory (System):  16.00GB (4.20GB free)
Load (avg):       2, 3, 3
VM:               0%
Screen Reader:    no

CPU %	Mem MB	Process
    2	   115	code main
    0	    66	   gpu-process
    0	    33	   shared-process
  131	  2245	   window (TypeScript — program.ts)
    0	    16	     terminal
    0	     0	       /bin/zsh -l
    0	    16	     watcherService
    0	    49	     extensionHost
    0	    49	       electron_node electronForkStart.js tsserver.js 
    0	    16	         electron_node typingsInstaller.js 
    0	    16	       electron_node server.js 
    0	    16	       electron_node jsonServerMain.js 
    0	    16	     searchService

Workspace Stats: 
|  Window (TypeScript — program.ts)
|    Folder (TypeScript): more than 20003 files
|      File types: types(5546) symbols(5546) js(5529) txt(2582) ts(400)
|                  json(169) baseline(112) map(63) lcl(13) md(11)
|      Conf files: tsconfig.json(9) launch.json(1) tasks.json(1)
|                  package.json(1)
```

### Disable extensions: `code --disable-extensions`

This definitely makes things a bit more usable. I wonder what the guilty extension is?

```
$ code --list-extensions
PeterJausovec.vscode-docker
dbaeumer.vscode-eslint
donjayamanne.jupyter
eamodio.gitlens
eg2.tslint
heptio.jsonnet
lukehoban.Go
ms-python.python
msjsdiag.debugger-for-chrome
redhat.java
rlovelett.vscode-swift-language
robertohuertasm.vscode-icons
shinnn.stylelint
steoates.autoimport
sysoev.language-stylus
zxh404.vscode-proto3
```

**Comment by mjbvz** [comment]
Sounds like an extension is the root cause. See [this guide](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions) for help tracking down the root cause. I suspect it may be  eslint or tslint or autoimport, but it could be another as well

**Comment by nojvek** [comment]
I disabled autoimport and its definitely usable again. 

Closing this. Thanks for the guide link.
