### ISSUE TITLE
Make the app available on the OS X App Store?

### ISSUE THREAD

**Issue by yvan-sraka** [Microsoft/vscode#41935]
Hello,

I do not see any issue related to this in this repository after a quick search.

It could be really nice to let the application available in the OS X App Store! I do not know if there is a restriction or a good reason why the app is not already available now?

Thank you for those who could give me an answer.

**Comment by tluanga34** [comment]
Microsoft would need to pay some fees to submit the app in the app store. This project is completely open source so, it is likely not to happen.

**Comment by mjbvz** [comment]
Duplicate of #19544
