### ISSUE TITLE
Impossible to insert space in integrated terminal

### ISSUE THREAD

**Issue by imonmyown** [Microsoft/vscode#41936]
- VSCode Version: Code - OSS 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-19T16:26:02.163Z)
- OS Version: Linux x64 4.11.12-1-rt16-MANJARO
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Start VSCode.
2. Launch integrated terminal (I used bash).
3. Press space key.
4. See if it is echoed in the terminal.

**Comment by Tyriar** [comment]
Can you type other character fine? Can you post a screenshot with some character added to the prompt?

**Comment by imonmyown** [comment]
Of course, here you go
![screenshot from 2018-01-21 23-54-12](https://user-images.githubusercontent.com/31204375/35198893-af51fb0a-ff06-11e7-84e2-68d66b6b9fb2.png)

**Comment by imonmyown** [comment]
[Yes](https://gist.github.com/imonmyown/634086c9eb8bfb65a1a39df1a6bc0efa)

**Comment by Tyriar** [comment]
@imonmyown can you see if this repros under the latest v1.20? Also maybe `"keyboard.dispatch": "keyCode"` is messing with it somehow?
