### ISSUE TITLE
High CPU -  Memory Leak - Intellisense hangs 

### ISSUE THREAD

**Issue by dvalentimribeiro** [Microsoft/vscode#41938]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angulardoc-vscode|Ang|3.0.5
vscode-html-css|ecm|0.2.0
debugger-for-chrome|msj|4.0.0
html-css-class-completion|Zig|1.16.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by cdutson** [comment]
I've been having a memory leak issue myself, though mine seems related specifically to OmniSharp. I'll update with a screenshot the next time it gets out of control. I'm not sure how best to diagnose/trace this to help with the debugging process

**Comment by jrieken** [comment]
follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by cdutson** [comment]
I've got that open. and OmniSharp isn't mentioned by name at all.
