### ISSUE TITLE
file path to language association settings need window reload to work for existing files

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4193]
testing #3925
OS: Linux

- configure "file path to language association settings"

Observe: existing files that match the path or extension do not show the new language when opened in an editor.

If this cannot be fixed I suggest to add a comment like this: "This setting requires reload/restart of VSCode to take effect."

**Comment by bpasero** [comment]
@weinand it should have this comment in the settings, or do you mean somewhere else?

**Comment by weinand** [comment]
@bpasero yes, like other settings with the same requirement.

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
Now reads like this:

![image](https://cloud.githubusercontent.com/assets/900690/13775038/a7199274-eaa2-11e5-85f1-26e502b51f0c.png)

**Comment by weinand** [comment]
@bpasero how do I get this info notification?

**Comment by bpasero** [comment]
@weinand when selecting "Configure file associations..." after you click on the language mode in the status bar.

**Comment by weinand** [comment]
@bpasero aha, I've never used that action. I always changed the associations in the settings.
