### ISSUE TITLE
Silent crash on start

### ISSUE THREAD

**Issue by pronebird** [Microsoft/vscode#41939]
- VSCode Version: 1.19.2
- OS Version: macOS

The VSCode won't start. After some time it warns that another instance of VSCode is already running (which is not). Then it continues to remain in the process list doing nothing. I killed all instances of VScode a few times and tried again but that didn't remedy the issue.

Steps to Reproduce:

1. `code .`.
2

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by mjbvz** [comment]
Are you still running into this issue?

**Comment by pronebird** [comment]
To be fair this was gone after I restarted my mac. Not sure what was the real cause.

**Comment by mjbvz** [comment]
Ok. Please let me know if you hit this again
