### ISSUE TITLE
CMD-S --> Chinese characters become garbled

### ISSUE THREAD

**Issue by KISSMonX** [Microsoft/vscode#41942]
- VSCode Version:  1.20.0-insider  (d21e6a3e388897a2250cb10ae897b6481e0bd61d)
- OS Version: Mac OS 10.13.2

Steps to Reproduce:

1. open/type chinese characters, and cmd-s to save
2. like gif image. 

Does this issue occur when all extensions are disabled?: **No**

So this is an extension of the error, but I do not know which one.

![jietu20180122-105348-hd](https://user-images.githubusercontent.com/2876745/35203626-13660ad4-ff64-11e7-83a8-670a3bea44db.gif)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
