### ISSUE TITLE
No progress and completion indication during task detection

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4194]
Testing #4019 

(this is not a consquence of the new task creation)

When using task detection on our gulpfile in vscode then 
- there is no progress and it takes a while to launch gulp
- there is no information about what has been detected as the build and test task

**Comment by dbaeumer** [comment]
Progress is reported through quick pick now. However no information is provided for auto detected build and test tasks.

**Comment by dbaeumer** [comment]
This got improved for task 2.0.0.

Task detection shows progress in the status bar using VS Codes progress API. In addition the picker shows progress if a task needs to be 'post' resolved.
