### ISSUE TITLE
"Stage selected ranges" etc stopped working

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41940]
- Open a diff editor from the scm viewlet
- Select a change
- Try the "stage selected ranges" or "revert selected ranges" commands
- Nothing happens

**Comment by eamodio** [comment]
For me the commands work (from the palette or a keyboard shortcut), but the menus don't.

**Comment by bpasero** [comment]
I probably broke that with my menu refactoring.

**Comment by bpasero** [comment]
@isidorn fyi this was an issue with using a context for commands that is not serializable to extensions. I introduced a new [`IEditorCommandsContext`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor.ts#L796) that can be send to extensions and adopted some code in `EditorCommands` to resolve that one to `IEditorIdentifier`. If we ever plan to open the "Open Editors" context menu to extensions, we should use the same guy over there as well to be safe.

**Comment by isidorn** [comment]
@bpasero makes sense. Thanks
