### ISSUE TITLE
Powershell [DBG]: History buffer

### ISSUE THREAD

**Issue by PorkyProgs** [Microsoft/vscode#41948]
Recently I took a look at developing my Powershell scripts using the Visual Studio Code (V 1.19.2) Editor and was very much impressed by its modular and broad functionality.  I have for a good while been developing scripts using the Windows System delivered Editor: Powershell_ISE, which I have grown used to.

While debugging in the Powershell_ISE, it is possible in the console (terminal) window to use the history buffer and the Standard Keyboard shortcuts such as 'Ctrl Left/Right Arrow keys' to navigate. However this functionality appears to be lacking in the VSCode Editor, which during the debug at the [DBG]:> prompt all Input must be freshly retyped each time.

Perhaps in such a short time I have not grasped all the functions and features of the VS Code Debugger. So if someone can point me in the right direction I would be grateful. However, if the functionality is lacking I would be equally appreciative if it could be introduced into the Terminal. Interestingly enough, this issue does not occure when I am not debugging.

Otherwise, I can only say 'Keep up the terrific work' the Editor is really worth adopting for scripting development.

**Comment by isidorn** [comment]
@PorkyProgs please try using the up / down arrow keys to navigate through history in the debug console.

**Comment by PorkyProgs** [comment]
Hi Isidor,

Thanks, but naturally I had tried that aswell as the Ctrl Left/Right 
Arrow key to move to former/previous word on the line. However, it did 
not work. Nevertheless, since you are suggesting it works, then where & 
what should I check to see if the configuration for the DBG:> session is 
correct?

Regards/Mit freundlichen Grüßen


Robert Bradlaw

E-mail: mailto:rbradlaw@gmx.de



-------- Forwarded Message --------
Subject: 	Re: [Microsoft/vscode] Powershell [DBG]: History buffer (#41948)
Date: 	Mon, 22 Jan 2018 01:33:23 -0800

**Comment by isidorn** [comment]
@PorkyProgs I do not understand your question. If it is powershell specific I recommend to go to the powershell extension repository and check there.
Please try up / down in debug console to go through input history.
