### ISSUE TITLE
Open textfiles (.txt) using a specific encoding

### ISSUE THREAD

**Issue by joandrsn** [Microsoft/vscode#41949]
In settings, I have no way of specifying what encoding I want to open the text files with default.

Normally in my settings I would have specified that I want `"files.encoding": "utf8"` on the top level and then on the programming language, I can specify a further `"files.encoding": "windows1252"` for specific programming languages. 

But since text files aren't  a programming language I cannot specify that I want to open .txt files using Windows1252 encoding.

- VSCode Version: 1.19.2
- OS Version: Windows 10 Version 1709 (OS Build 16299.125)

**Comment by bpasero** [comment]
You can:

```json
"[plaintext]": {
	"files.encoding": "utf16be"
}
```
