### ISSUE TITLE
Breakpoints don't appear next to line sometimes

### ISSUE THREAD

**Issue by Trevinlc1997** [Microsoft/vscode#41947]
- VSCode Version: 1.19.2
- OS Version: Fedora 27

Steps to Reproduce:

1. Open debugging terminal, close the terminal, go back to VS Code and repeat. (Fixes when you restart vscode) 

![peek 2018-01-22 01-59](https://user-images.githubusercontent.com/24485362/35210473-f2807d8c-ff17-11e7-92d0-41b1be60694d.gif)

Does this issue occur when all extensions are disabled?: Not sure, the extension's I have are 

1. C/C++ 
2. Include Autocomplete

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode-cpptools
