### ISSUE TITLE
Members not exported error on imports

### ISSUE THREAD

**Issue by thaoula** [Microsoft/vscode#41941]
- VSCode Version: Version 1.20.0-insider (1.20.0-insider)
- OS Version: Mac Os High Sierra

Steps to Reproduce:

1. import { Store, Action, createReducer } from 'ngrx-actions';
2.See Store, Action and createReducer have red underline and intensense does not work

Does this issue occur when all extensions are disabled?: Yes/No Yes

This issue seems to occur with Typescript 2.7.0-insiders.20180117 and not RC. I need to use 2.7.0 RC.

![image](https://user-images.githubusercontent.com/349133/35202721-def3364e-ff56-11e7-84fa-1cff67030cf6.png)

I have reported this issue on ngrx-actions also -
#https://github.com/amcdnl/ngrx-actions/issues/21

**Comment by MikeMatusz** [comment]
This has just recently started happening to me for several internal libraries.  Everything builds fine, and non-Insiders correctly sees the exports.  I notice (in my case) that the package.json points to a d.ts file that does export * from another d.ts file, and the ones in the other file are the ones it can't recognize.  Not sure if that's the case here, too.

**Comment by MikeMatusz** [comment]
Tested my theory and it didn't make any difference.  Even if I have everything exported from common.d.ts (my package.json specifies "types: "./common.d.t.s").  I followed the same pattern Angular uses for bundling their packages, but theirs seem to import fine.  And again, in 1.19.3, everything is fine.  Only in 1.20.0-insider am I seeing this problem.  I've been applying updates daily to see if it's fixed, but using 1.19 for actual development in the meantime.  I'm very worried about when 1.20 is released that this will make VSCode almost unusable for my team.

**Comment by alonstar** [comment]
I have the same issue on @ngx-translate/core  after updating the latest version. (Previous Insiders and Stable version is working fine.)

[ts] Module '"d:/Projects/Angular4/node_modules/@ngx-translate/core/core"' has no exported member 'TranslateService'.

Version 1.20.0-insider
Commit 648c46deeeda61fad44ce188684dcb61838b724a
Date 2018-01-31T10:13:25.946Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by sc0ttwad3** [comment]
+1 and same behavior using 1.20-insider with Javascript-only projects. [js] Module ...

**Comment by sc0ttwad3** [comment]
For Javascript files I was getting the same behavior, just as: ```[js] Module ... has no exported member ...```, for valid working modules, until I turned off implicit checking of Javascript files with the setting:

```
// Enable type checking for Javascript files
"javascript.implicitProjectConfig.checkJs": false
```

**Comment by mjbvz** [comment]
This seems to work fine in TypeScript 2.7.2 and 2.8.x
