### ISSUE TITLE
Support for ".rs" files?

### ISSUE THREAD

**Issue by phtdacosta** [Microsoft/vscode#41946]
I tried to attach Rust source files to VSCode but it seems like VSCode don't "recognize" it like it normally recognizes ".py" or ".js" files.

That happened only with me or VSCode really do not recognizes ".rs" files?

Sorry in advance for this simple issue.

**Comment by phtdacosta** [comment]
UPDATE

I'm really confused right now.
.py and .js files gets an icon that is a "blank" page with the VSCode in the center of it, while .rs and .c files get simply the own VSCode main icon...

That's correct? Maybe the different icons are because .py and .js are script languages and .rs and .c are compiled?

LOL

**Comment by aeschli** [comment]
Can you make a screenshot? What icon theme are you using?
That's what I see when opening a `.rs` file, using the built-in Seti-UI theme:
- the `.rs` file is opened as a Rust file (as seen in the status bar)
- It gets a Rust icon, that looks ok to me. Also the other languages you named look ok to me

![image](https://user-images.githubusercontent.com/6461412/35212294-f0d88866-ff59-11e7-8342-6dd247224bf3.png)

**Comment by phtdacosta** [comment]
I did not even know that was possible to SS and post directly on here hahaha

That's what I meant actually.

![image](https://user-images.githubusercontent.com/8548534/35224151-21d3061a-ff6b-11e7-9526-36ec66d8a9dc.png)

**Comment by aeschli** [comment]
@joaomoreno Do we have a list of which file types VSCode can edit?

**Comment by joaomoreno** [comment]
Yeah. And if files aren't in that list, Windows just seems to take the Code's icon as the file icon.

**Comment by phtdacosta** [comment]
Well, for the next updates you guys should add a bunch of new extensions then. Anyways, thanks for all the responses guys! 👍
