### ISSUE TITLE
Doublts about the Extension dir

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#41944]
now, vscode provide --extensions-dir cmd to set the extensions dir. but how can i know the current extension dir . the same question as the user-data-dir

**Comment by jrieken** [comment]
> but how can i know the current extension dir . the same question as the user-data-dir

Where? In the API?

**Comment by midGitub** [comment]
thank you for reply. In anyway. i just want to know the current settings configure status. 0.0

**Comment by jrieken** [comment]
> i just want to know the current settings configure status. 

still don't understand
