### ISSUE TITLE
Find widget behaviour enhancement.

### ISSUE THREAD

**Issue by Psithief** [microsoft/vscode#41957]
## Summary
Currently, the behaviour of the keyboard in the find widget appears to be hardcoded.
This presents issues because the behaviour of keys can vary based on past state that the user may have forgotten.

## How to reproduce

1. Bind a shortcut to "Replace" (`editor.action.startFindReplaceAction`)
2. Use that shortcut once. The find/replace widget opens, focused on the Find Input.
3. Add some text. The current keyboard behaviour is:
    * <kbd>Enter</kbd> → Find Next
    * <kbd>Shift + Enter</kbd> → Find Previous
    * <kbd>Ctrl + Down</kbd> → Focus on the editor
    * <kbd>Tab</kbd> → Focus on the replace input
4. Close the widget, then reopen it. The focus automatically moves to the replace field, where the behaviour is now:
    * <kbd>Enter</kbd> → Replace One
    * <kbd>Ctrl + Enter</kbd> → Replace All
    * <kbd>Ctrl + Down</kbd> → Focus on the editor
    * <kbd>Shift + Tab</kbd> → Focus on the find input

## Problem
The behaviour has changed depending on whether the user has already used the widget this session. If the user opens the widget with their shortcut a second time, <kbd>Enter</kbd> now replaces text with nothing instead of finding the next item.

## Root cause
The "Find" widget hides the replace text box, requiring an extra box click to make it visible.
It's not possible to open a find widget that has both find and replace capability without use of the mouse, without the aforementioned drawbacks. This defeats the purpose of keyboard shortcuts.

## Requested Enhancement
Any of the following:

1. Don't hide the replace input when the user uses the "Find" (`action.find`) shortcut, _so users don't attempt to kludge_ using the "Replace" shortcut as a combined find/replace.
2. Don't automatically switch focus to the replace input if the find input contains text, so users don't press enter and start deleting text they were only trying to find.
3. If the widget calls any editor actions (anything that starts `this._codeEditor`) such as find next, replace one, replace all, then those commands must all appear in the default keybindings and be able to be overridden.

## Code reference
* Hardcoded find input keys: https://github.com/Microsoft/vscode/blob/5880cfba4f1e2f123529ec16f4d9ada0c5104cfc/src/vs/editor/contrib/find/findWidget.ts#L582
* Hardcoded replace input keys: https://github.com/Microsoft/vscode/blob/5880cfba4f1e2f123529ec16f4d9ada0c5104cfc/src/vs/editor/contrib/find/findWidget.ts#L613

## Related issues

#39130
#37102
#32617

**Comment by amunger** [comment]
this looks fixed, the cursor is always placed in the replace input field for consistency
