### ISSUE TITLE
Can not show symbols

### ISSUE THREAD

**Issue by kcloze** [Microsoft/vscode#41959]
I used vs code  to edit php class file ,but can not find any symbols .

- VSCode Version: 1.19.2
- OS Version:ubuntu 16.4

Steps to Reproduce:

1.ctr + T
2.ctr + @ (sublime plugin)

![image](https://user-images.githubusercontent.com/1489176/35216782-c857f2c4-ffa3-11e7-9192-bb974e2e0146.png)
![image](https://user-images.githubusercontent.com/1489176/35216921-47751a32-ffa4-11e7-9f47-b8e2a73557b6.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jrieken** [comment]
You need an extension doing that for you, e.g: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense
