### ISSUE TITLE
Contextual Menu - some things are missing

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#41963]
Im migrating from SublimeText 3 and I´m missing a few things.

ST3 has  has more options to work with files and folders, see screenshot: 
![image](https://user-images.githubusercontent.com/2746333/35219777-371c3fba-ff74-11e7-8f10-d99eb9ea6531.png)

I miss very much duplication of file / cut & and paste file (move file).

Will be implemented this advanced operations in the future?

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/25563

https://github.com/Microsoft/vscode/issues/30400

https://github.com/Microsoft/vscode/issues/36104
