### ISSUE TITLE
`Change Language Mode` keybinding is bound to `Preference: Language extension`

### ISSUE THREAD

**Issue by xc1427** [Microsoft/vscode#41962]
- VSCode Version:  Version 1.19.2 (1.19.2) 490ef761b76b3f3b3832eff7a588aac891e5fe80 and Version 1.20.0-insider (1.20.0-insider) d21e6a3e388897a2250cb10ae897b6481e0bd61d
- OS Version: macOS High Sierra 10.13.1 (17B1003)

Steps to Reproduce:

1. Press CMD + K + M
2. Language extension panel appears.

Expected behavior:

- Change language mode panel appears.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by sandy081** [comment]
@xc1427 Can you please open your keybindings and let us know to what action the above keybinding is bound to?

**Comment by xc1427** [comment]
@sandy081  ![image](https://user-images.githubusercontent.com/5611770/35656967-fb37a084-0734-11e8-89af-a0e45e07c1b9.png)

Sorry for the late reply. I just saw your notification.

**Comment by sandy081** [comment]
@xc1427 May i know which panel do you see?
