### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms

### ISSUE THREAD

**Issue by mikhail-tin** [Microsoft/vscode#41964]
Hi. I have tried create an extension use the next tutorial(https://code.visualstudio.com/docs/extensions/example-hello-world) and I faced an issue.

> Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Response from the target seems invalid: [ {

- VSCode Version: Version 1.19.2
- OS Version: Win 7 x64 
- Node:  v9.4.0

Steps to Reproduce:
1. npm install -g yo generator-code
2. yo code
3. cd my_new_extension
5. code .
6. Press F5 

Thx!

**Comment by weinand** [comment]
@mikhail-tin I cannot reproduce this by following your steps.

When using yeoman are you generating a JavaScript or a TypeScript extension?

**Comment by mikhail-tin** [comment]
Hi, Plese see below:

> ? What type of extension do you want to create? New Extension (TypeScript)
> ? What's the name of your extension? examle
> ? What's the identifier of your extension? examle
> ? What's the description of your extension?
> ? What's your publisher name (more info: https://code.visualstudio.com/docs/tools/vscecli#_publis
> hing-extensions)? later
> ? Initialize a git repository? No
>    create examle\.vscode\launch.json
>    create examle\.vscode\settings.json
>    create examle\.vscode\tasks.json
>    create examle\src\test\extension.test.ts
>    create examle\src\test\index.ts
>    create examle\.vscodeignore
>    create examle\.gitignore
>    create examle\README.md
>    create examle\CHANGELOG.md
>    create examle\vsc-extension-quickstart.md
>    create examle\tsconfig.json
>    create examle\src\extension.ts
>    create examle\package.json


So. node_modules was installed.
And I pressed F5
![image](https://user-images.githubusercontent.com/17845768/35728374-6e766bf6-081c-11e8-95fd-be726ac8a1e7.png)

**Comment by weinand** [comment]
@roblourens I could not reproduce this on Windows 7 and VSCode Version 1.19.3.
Could you explain the error message from above?

**Comment by mikhail-tin** [comment]
Hi. 
I have got a new version of VS Code 1.19.3 and installed it. 
The issue was still there. 
After that I downloaded the latest version from official site and tried to install it.
I faced an issue like this: "for installation x64bit, please uninstall 32bit version" Ok.. I uninstalled 32bit  version and installed new x64. 
There is no more any issue. 
I guess my issue was related with 32bit version.

Probably my issue was related with  incremental updates, because I installed VS Code more then 2 year ago.

**Comment by weinand** [comment]
@mikhail-tin Thanks for the update, I'm glad to hear that you could solve your issue!
