### ISSUE TITLE
Editor position is intermittently jumpy when switching tabs

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#41968]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.17074
---

I haven't yet figured out a real rhyme or reason yet, but the current editor position when switching tabs is preserved (restored) properly. In some cases switching back and forth between tabs will cause the editor position to shift down by 1 line (after each tab switch) probably code lens related, while other times it will stay stable (even if the document has code lens to show). But sometimes (less frequently) the position can jump by a much larger number of line (sometimes by a hundred or more). I can't reproduce this all the time, but once it starts with a document, it seems to persist (jumps all around each switch -- sometimes even going back to the original switch line). I seem to have had better luck causing this if the find widget is open, but it definitely happens even with out it.

This can only be reproduced with code lens enabled -- setting `"editor.codeLens": false` causes the editor position to always be restored properly

Steps to Reproduce:

1. Open a document scroll down to some position (note the top line)
2. Open another document and do the same
3. Switch back and forth and notice that the editors move down by at least 1 line (and might jump around more)
4. Open the find widget on one of the documents and repeat 3 -- should notice that the editor can jump around seemingly randomly now

Might need to use a larger file to see the behavior more easily

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
> Switch back and forth and notice that the editors move down by at least 1 line (and might jump around more)

It jumps because the code-lens appear/disappear?

**Comment by jrieken** [comment]
is this #19917?

**Comment by eamodio** [comment]
No it isn't just that the code lens is showing. Say the top line of the document is 100 when you switch it will be 101 then 102 etc each time you switch. Or sometimes it will jump much greater -- the top line will be ~200, ~300 which is easier to reproduce with the find widget open. The shift by 1 line is annoying, but the other completely loses the place you were at in the file

**Comment by jrieken** [comment]
And this is with or without extensions?

**Comment by eamodio** [comment]
This is reproducible without extensions.

Here is a GIF showing it with all extensions disabled (running with `--disable-extensions`)
![tab-switching](https://user-images.githubusercontent.com/641685/35409119-4878e21e-01df-11e8-97a1-d9ea1ce14c4d.gif)

**Comment by jrieken** [comment]
Is does look like #19917... What happens is that editor used the n-1 code lenses and now that a new model comes it they are invalidated, resolved, and replaces. Instead of just staying stable for a while...

**Comment by eamodio** [comment]
I'm sorry but I really don't think these are related -- #19917 seems like people don't like that the code "moves" because of code lens. The code has always moved in response to code lens being added into the document, but this isn't that. Before 1.19 this was far more stable. This is about the stability of keeping your view in view -- look at the line numbers at the top. You will see at first that it keeps moving down, at first by 1 or 2, but then you will see it jump more, and then when I open the find box, it jumps by tens (and then hundreds) of lines. Switching tabs should not cause you to lose context of what you were looking at.

**Comment by jrieken** [comment]
Just looked at this with @alexandrudima. A little jumpiness is expected (still bad) and bigs jumps are harder to understand. We will investigate.

**Comment by ravid7000** [comment]
Something similar issue encounter. It do not hold position of horizontal scrollbars. It reset to zero while switching between tabs.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/36756634/37281364-c76edb72-2616-11e8-9dc6-8c3af9882200.gif)

**Comment by mattacosta** [comment]
This still occurs with the find widget open.

Version 1.22.0-insider
Commit 95b0cffe72a9d32e6ef3780dcc050a336e7b2968
Date 2018-03-28T05:17:37.707Z

**Comment by alexandrudima** [comment]
I pushed further changes to further improve this (also in the find widget open + code lens case).
