### ISSUE TITLE
Changing system date into the past causes high CPU usage in VS Code

### ISSUE THREAD

**Issue by gmenih341** [Microsoft/vscode#41966]
- VSCode Version: 1.19.2
- OS Version: Linux 4.14.14-1-ARCH

Steps to Reproduce:

1. Open up Visual Studio Code
2. Change your system time to 1 day before today
3. Observe as CPU usage goes up

If you change the date back, it will stop using so much CPU. It's not really an issue, just thought i'd share my observation.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks
