### ISSUE TITLE
JS code hint don't work in react(*.js)

### ISSUE THREAD

**Issue by brealisty** [Microsoft/vscode#41960]
- VSCode Version: 1.19.2
- OS Version: Ubuntu 16.04

![test](https://user-images.githubusercontent.com/12651762/35217467-61807fd2-ffa6-11e7-8cf2-e3bdc6bfa4b5.gif)
this is the vscode, as you can see, the toString() function didn't hit

![test1](https://user-images.githubusercontent.com/12651762/35217533-9763544e-ffa6-11e7-8ecc-cfd357dd581e.gif)
and this is another editor, it work will.

what's wrong about this problem. Do I need add some config?

**Comment by mjbvz** [comment]
You need to [annotate the type using jsdocs](https://code.visualstudio.com/Docs/languages/javascript#_intellisense) to get proper intellisense. Something like:

```js
  /**
   * @param {React.MouseEvent<HTMLInputElement>} e 
   */
handle(e) {}
```
