### ISSUE TITLE
Enable the Problem Toolbar to be used into a separate window？

### ISSUE THREAD

**Issue by GrizzlyHills** [Microsoft/vscode#41967]
- Just like Google Chrome Developer Tools.It could set the Dock side into a separate window.It is shown in the figure below.
![](https://github.com/GrizzlyHills/LearnGit/blob/master/img/Chrome%20Developer%20Tools.png?raw=true)
- And the figure below is Problems Toolbar of VSC.It can only move the Problems Toolbar workspace to the right.
![](https://github.com/GrizzlyHills/LearnGit/blob/master/img/VSC-Problems.png?raw=true)
- I think it would make the job more efficient and take full advantage of the extended screen if this feature could be added.

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/10121
