### ISSUE TITLE
Dozens of command prompts appear 23/7

### ISSUE THREAD

**Issue by smergol1** [Microsoft/vscode#41973]
### Reproduction Steps
1) open Vs Code
2) do any of following actions:

Actions:
  - open a folder
  - open a file
  - open a already opened file
  - open Github Desktop

3) when doing any of above listed actions there appear command prompts. They appear in line like one calls the other and are present for some milliseconds. Its really annoying since everytime I swap between files I have to wait like 3 seconds

## Technical analysis

I noticed this "bug" after i had to work at home due to a storm. At work I am using Mac OSX.
This "bug" appears on 32-bit && 64-bit versions. The "bug" also occurs when running 'code.exe  --disable-extensions'

When opening Github Desktop the same behaviour appears.

I think it's just been forgotten to hide the command prompts.
## Technical Information

using Win 7 Home Premium 
![systeminfo](https://user-images.githubusercontent.com/31403441/35231375-e665ec54-ff98-11e7-92a0-697d555634ce.PNG)

![devices_pc](https://user-images.githubusercontent.com/31403441/35231369-dfdf9a92-ff98-11e7-8ba9-7503424b0a4e.PNG)

![image](https://user-images.githubusercontent.com/31403441/35231437-168b5356-ff99-11e7-92fd-f81f93a8b452.png)

![image](https://user-images.githubusercontent.com/31403441/35231395-f5c48da4-ff98-11e7-8bc3-72c8367b39c3.png)

**Comment by jrieken** [comment]
please attach gifs, steps, and screen shot in this issue

**Comment by smergol1** [comment]
Well i did.. Not directly within the issue itself but within the given link.

Did you open the link? Pls open it. I added Reproduction steps, a video and
my thoughts within the site the link refers to..

I won't move that to Github. Thanks for fast responding time but if you
won't even look at the provided data then you can close the issue.

**Comment by jrieken** [comment]
Thanks, but the link doesn't work for me

**Comment by smergol1** [comment]
@jrieken 
Ok, I don't know why the link doesn't work since its our own home page :)
But i updated the question.

**Comment by jrieken** [comment]
hm.... do you use the normal windows command prompt or something special?

**Comment by jrieken** [comment]
> When opening Github Desktop the same behaviour appears.

Might be a problem of your git installation.. Assigning to @joaomoreno for help

**Comment by smergol1** [comment]
@jrieken @joaomoreno 
Okey, i reinstalled git and now only when opening a new file one command prompt appears. Probably it has to to with git.

**Comment by smergol1** [comment]
Okey, I think you guys can close this issue. I tried some different settings and it appears that its caused by my settings. For the moment I can't get fully rid of the problem but it's a matter of time. 

Thans for support.
