### ISSUE TITLE
Save with Encoding shows 'UTF-8 (configured encoding)' while it is UTF with BOM

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#4197]
- create a file
- click on the encoding in the status bar: 'Save with Encoding' to 'UTF-8 with BOM'
- again click on the encoding in the status bar: 'Save with Encoding': 
  The picker says 'UTF-8 (configured encoding)' -> should say 'UTF-8 with BOM (configured encoding)'
![image](https://cloud.githubusercontent.com/assets/6461412/13752061/4be5cdfe-ea0d-11e5-9734-5b128d07dd43.png)

**Comment by bpasero** [comment]
@aeschli I am trying to say what is configured in settings, I can make the wording more explicit.

**Comment by bpasero** [comment]
Configured Encoding => Configured in Settings
