### ISSUE TITLE
Second argument is replaced upon completing the first argument in a method call

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#41971]
- VSCode Version: Latest Insiders
- OS Version: Mac OS

Steps to Reproduce:
1. Insert cursor before the first argument (that accesses some property) to the method.
2. Start typing new argument that also accesses property. 
3. On suggestion appearance, press Tab to enter suggestion value
It replaces the old first argument instance with the property from the new argument. 

![vscode](https://user-images.githubusercontent.com/2239563/35227216-bad6a62e-ff8d-11e7-9291-85fc71e8e9f9.gif)

**Comment by mjbvz** [comment]
I can't repo this. Can you please share some complete example source?

**Comment by michelkaporin** [comment]
Tested in JavaScript, and it works fine there. Seems like it's language specific, although I thought autocomplete behaviour is a generic one. 

Here is an example code that has a problem in Java:
```java
public class Test {
    public int testInt;

    public boolean method(int x, int y, int z) {
        return true;
    }
}

public class Main {
    public static void main(String[] args) {
        Test t = new Test();
        t.method(t.testInt, t.testInt);
    }
}
```

Should I address the issue in https://github.com/Microsoft/vscode-java-pack instead?

**Comment by mjbvz** [comment]
@michelkaporin Sorry, at a glance I thought that was JS :) 

Yes, please file the issue against the java intellisense extension. It may be customizing the completion insert behavior
