### ISSUE TITLE
Find in files shortcut (Ctrl+Shift+F) toggles the focus

### ISSUE THREAD

**Issue by ConnorsFan** [Microsoft/vscode#41974]
The shortcut for "Search in files" (Ctrl+Shift+F) toggles the focus between the search field and the editor window. This often cause me to type search text that ends up in my code.

- VSCode Version: 1.19.2
- OS Version: MS Windows 7

Steps to Reproduce:

1. Type the shortcut Ctrl+Shift+F
2. The focus is in the search field
3. Type the shortcut Ctrl+Shift+F again
4. The focus is back in the editor

Most common sequence:

1. While debugging my Web application
2. I go to VS Code and type the shortcut Ctrl+Shift+F
3. I type some search text and make a search
4. I switch back to the running Web application to test something
5. I go back to VS Code to search something else
6. To make sure that I am searching in files, I type Ctrl+Shift+F
7. I start typing some search text
8. That text is inserted in my code editor
9. I am frustrated because it is the 10th time it happened in the last hour

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
The viewlet focusing keybindings toggle focus by default to make it easier to switch back and forth with the editor, but you can change that if you like by changing the ctrl+shift+f keybinding:

![image](https://user-images.githubusercontent.com/323878/36013949-13090c24-0d1c-11e8-9e1c-066a716c23b9.png)
