### ISSUE TITLE
Small feature requests

### ISSUE THREAD

**Issue by abhishek-nigam** [Microsoft/vscode#41976]
Hello, I love VS code and I use it as my primary code editor,
I just wanted to request two minor features:

1. Tabbed integrated terminals. Current there is a drop-down that lets you switch between integrated terminals you have opened inside a window. I think it will be more convenient to have tabs for them to switch between.
2. I absolutely love VS Code's intellisense. I think the intellisense/suggestions panel can be made more beautiful and easier to read(with bigger fonts and color scheme), as an example we look at Atom's suggestions panel, which I think is easier to read.

Thanks!!

(P.S. Sorry, I am a newbie on GitHub and don't know how to add appropriate tags to this request)

**Comment by usernamehw** [comment]
1. Duplicate of https://github.com/Microsoft/vscode/issues/10546
2. Similar to https://github.com/Microsoft/vscode/issues/26572
Probably something can be achieved with:
```javascript
"editor.suggestLineHeight": 40,
"editor.suggestFontSize": 22,
```

**Comment by abhishek-nigam** [comment]
@usernamehw Yes, you're references are spot on. They are exactly what I desired. So I should close this one. Glad to see that these requests are already being looked into. Thanks
