### ISSUE TITLE
Add an option to display popup "toast" at the bottom of the screen

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#41975]
Hey,

It's very anoying to have the popup showing warnings and infos on top, hidding tabs, close buttons, search field and so on.

Could it be possible to ad an option like : 
`"workbench.popup.position" : "top" / "bottom"`

Here is an example : 
![image](https://user-images.githubusercontent.com/5599375/35229038-9541cec0-ff92-11e7-805d-169b22171fed.png)

I did the trick with this css : 
```
.global-message-list.transition {
  bottom: 25px !important;
}
```
It could be a great help since it's a quickwin helpfull feature.

Thanks to consider !

**Comment by bpasero** [comment]
This landed via https://github.com/Microsoft/vscode/pull/43770 and can be tried out in our preview release: https://code.visualstudio.com/insiders/
