### ISSUE TITLE
Repeat the update！

### ISSUE THREAD

**Issue by Leechaoran** [Microsoft/vscode#41980]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:-

1.Thanks for providing this excellent editor.
2.When I updated to 1.19.2, the next time I opened the work back to 1.18.1,  then prompt me to update   the new version. Unlimited updates like that now reflect this issue to you.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Does it go on forever?

**Comment by Leechaoran** [comment]
Yes ，update the end of use, the next time you open still prompted to update.

**Comment by joaomoreno** [comment]
Does it get fixed if you fully uninstall and then reinstall VS Code?
