### ISSUE TITLE
Configuration inheritance does not appear to inherit baseUrl from base config

### ISSUE THREAD

**Issue by Merryweather** [Microsoft/vscode#41983]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601 (also reproduced on Windows 10)
---

The team I work with have been experiencing the issue highlighted in #40682.  We discovered that the issue can be eliminated by ensuring baseUrl is set in the tsconfig at the root of our source folder.  That configuration file, however, should already have been inheriting baseUrl from another config file at the same level.  It would appear that the config value was not being inherited as expected.

Steps to Reproduce:

1. Take the following example project and open the MyProjectRoot folder in VSCode:
[MyProjectRoot.zip](https://github.com/Microsoft/vscode/files/1652845/MyProjectRoot.zip)

2. Open B.ts and demonstrate that the bug described in #40682 is present.

You can use F2 to rename the unused variable, which would demonstrate the issue as described in #40682, or use the 'light-bulb' accelerator to remove the unused local variable, which follows the path we've been using during our investigation.  Both lead to the same end.

You will end up with two tabs open for B.ts, but that is not the issue we are looking at here, I'm just using it as a vehicle to demonstrate the actual issue that I want to highlight.

3. Close the two 'B.ts' tabs *without saving*.
4. Open tsconfig.json and uncomment line 12, such that there is now an entry for baseUrl under compilerOptions.  Save the change.
5. I have been closing and reopening VSCode at this point.  I have not established if this step is essential.
6. Repeat step 2

Hopefully you will find you are unable to reproduce the bug.

So, if you return to tsconfig.json, you can see that it extends another-tsconfig.json.  Looking at the base configuration, you can see that it already contained an entry for baseUrl, which I would have expected to be inherited by tsconfig.json.  Both files are at the same level.  The entry for noUnusedLocals, present in the base config, is being inherited as I expect, which indicates to me that there is not a general problem with inheritance from the base config.

I was expecting there to be no difference in the behavior of VSCode between the case where baseUrl is inherited from another-tsconfig.json and the case where it is overridden within tsconfig.json.

Reproduces without extensions: Yes

**Comment by Merryweather** [comment]
Another point, possibly worth mentioning, is that I could not reproduce the issue from #40682 if I created my example project folder structure such that the path to B.ts contained only lowercase characters (hence the name of the root folder in the attached archive is 'MyProjectRoot').

I have been working under the assumption that the changes in behavior caused by the presence (or lack thereof) of uppercase characters in the path was part of #40682 and unrelated to the inheritance problem that is the focus of this issue.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) using typescript 3.0?
