### ISSUE TITLE
'Reopen with Encoding' doesn't contain UTF-8 with BOM

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#4198]
- have a UTF-8 file
- click on the encoding  status bar, 'Reopen with Encoding'
- picker doesn't allow to open as a UTF-8 with BOM

![image](https://cloud.githubusercontent.com/assets/6461412/13752140/9ee19e8e-ea0d-11e5-967d-1c6cad19a555.png)

**Comment by bpasero** [comment]
That is as designed because for decoding it does not make any difference.
