### ISSUE TITLE
Avoid calls to getValue() and favour createSnapshot() instead

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41984]
This is a follow up from https://github.com/Microsoft/vscode/issues/32503 where in many places `model.getValue()` is replaced with `model.createSnapshot()` to prevent allocating a 256 MB string which results in an error.

There are still places where `model.getValue()` is called and `model.getValueInRange()`. 

Things in the editor to revisit:
* `IModelContentChangedEvent` having the value as `string`
* `findModel` (for a replace operation)
* more?

**Comment by svitlana-galianova** [comment]
Hey, I would like to help to replace `model.getValue()` with `model.createSnapshot()`.

**Comment by alexandrudima** [comment]
@svitlana-galianova It is not a trivial refactoring.

A snapshot is stateful, and once read, cannot be reset. So a snapshot cannot immediately replace a `string`, like e.g. in the `IModelContentChangedEvent` (which is the most problematic usage). Replacing the `string` with a snapshot would make it that the first listener would read the snapshot and it would be at the end for all the other listeners...

In fact, I much more prefer tackling real world repros like #42473 than going for find all references for these calls... So I will close this issue in favor of #42473 and others likes it.
