### ISSUE TITLE
Visual Studio opens only as blank and black screen.

### ISSUE THREAD

**Issue by ashwinr63** [Microsoft/vscode#41990]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please see this guide on how to report an issue https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues
