### ISSUE TITLE
Emmet not working for "HTML" elements in JSX. 

### ISSUE THREAD

**Issue by jhc1982** [Microsoft/vscode#41998]
I am not getting any HTML code complete with VS Code. I tried using Sublime Babel, which is great for code complete of "HTML" elements in JSX, but the color scheme was unworkable. Keys and Values in JS Objects have the same color.

I uninstalled Sublime Babel but then no code complete.

Typing "div" for example results in "HTMLDivElement". Isn't emmet supposed to be baked into VS Code now?

- VSCode Version: 1.19.2 (1.19.2)
- OS Version: 10.12.6

**Comment by Clickys** [comment]
Emmet doesnt work for me either in vscode . any suggestion please ?

**Comment by ramya-rao-a** [comment]
What is the file extension on the files you are trying emmet on? .js or .jsx?

Please read [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet). It should have everything you need to get going.

**Comment by Clickys** [comment]
If you have disabled the editor.quickSuggestions setting, you won't see suggestions as you type. My editor quicksuggestions obj is this. What should i change to enable quickSuggestions ?
 "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },

**Comment by ramya-rao-a** [comment]
@Clickys Your settings for quicksuggestions look fine. Can you share any of the emmet settings that you might have changed? What is the file extension on the files you are trying emmet on? Do you get emmet suggestions in html and css files?

**Comment by jhc1982** [comment]
I just got this from another forum which worked to resolve my problem. I guess it’s Demi baked :)

“Emmet is baked in, but you need to activate it for jsx. Just add this to your vs code settings: 

"emmet.includeLanguages": {
   "javascript": "javascriptreact"
},

”
