### ISSUE TITLE
Intellisense incorrectly autocompleting

### ISSUE THREAD

**Issue by nach00** [Microsoft/vscode#42004]
- VSCode Version: Current insiders
- OS Version: Ubuntu

Steps to Reproduce:

1. Coding in Ruby
2. Create def, then when I type `end`, it starts to auto complete (which is fine) for `e` and `n`, but then when I type `d`, it autocompletes to `def`, which is not what I needed. I've tried messing with all the Intellisense settings, but the only one that will nullify this issue is disabling the feature completely. The first image is when I get the incorrect autocomplete, the second is when I press `enter`.

Does this issue occur when all extensions are disabled?: No
![test1](https://user-images.githubusercontent.com/5945533/35253383-be3ea45c-ffaa-11e7-9e0f-20f6aefcb3ca.png)

![test2](https://user-images.githubusercontent.com/5945533/35253384-c0c7f034-ffaa-11e7-9bd4-433e1dbb5a1a.png)

**Comment by jrieken** [comment]
dupes #29210
