### ISSUE TITLE
Optimize word selection for wide character

### ISSUE THREAD

**Issue by maokelong** [Microsoft/vscode#42005]
- VSCode Version:1.19.2
- OS Version:Windows 10 v1709

Steps to Reproduce:

1. Enter some commonplace sentences consisting of Chinese punctuation and  Chinese words like " 这里使用符号化语言，对 some algorithm 进行量化分析："
2. Select words(ctrl + alt + left-arrow) from right to left and the following parts of the sentence will be selected sequentially "进行量化分析："+ "algorithm "+"some "+"这里使用符号化语言，对 "

This doesn't make sense. Words never consists of punctuation no matter of English nor Chinese.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/50045 , which shares the same root cause.
