### ISSUE TITLE
Perl Syntax Highlighting breaks with //= on any new line 

### ISSUE THREAD

**Issue by talhaobaid** [Microsoft/vscode#42008]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
perltidy|sfo|1.2.1

---

Steps to Reproduce:

1. Create/open a file with Perl code in editor, having .pm/.pl extension.
2. Write //= (); on a new line in the middle of the code.
3. The rest of the code below will turn leaving the identifiers only

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to textmate/perl.tmbundle#29
