### ISSUE TITLE
Can't enter fullscreen mode when launch from tmux session

### ISSUE THREAD

**Issue by bguzryanto** [Microsoft/vscode#42000]
- VSCode Version: Version 1.19.2 (1.19.2)
- OS Version: Mac OS Sierra 10.12.1 (16B2657)

Steps to Reproduce:

1.  Launch `code` from tmux session
2. Click the green button on the left title bar to maximize the screen
3. Nothing happened but 'disabled sound' occurred. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Read: https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41
