### ISSUE TITLE
text is blurry for my hardware

### ISSUE THREAD

**Issue by yupangestu** [Microsoft/vscode#42009]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
jshint|dba|0.10.15
vscode-eslint|dba|1.4.4
jquerysnippets|don|0.0.1
tslint|eg2|1.0.24
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
php-pack|fel|1.0.1
beautify|Hoo|1.1.1
ftp-simple|hum|0.5.8
Go|luk|0.6.73
node-debug2|ms-|1.19.0
laravel-blade|one|1.13.0
laravel5-snippets|one|1.4.0
vscode-paste-and-indent|Rub|0.0.8
vscode-react-native|vsm|0.5.7

---

Steps to Reproduce:

1. open and it occurs randomly

Reproduces without extensions: Yes/No

# My Spec

1. Windows 10 Pro
2. Intel I3 4005U 1.7 Ghz
3. RAM DD3 10GB

**Comment by roblourens** [comment]
Please include more details about your machine and display.
