### ISSUE TITLE
Copying SQL code to SQLITE3 in Integrated Terminal copies garbage 

### ISSUE THREAD

**Issue by devbnj** [Microsoft/vscode#42011]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
jshint|dba|0.10.15
vscode-eslint|dba|1.4.4
vscode-coffeescript-preview|dre|0.1.4
tslint|eg2|1.0.24
python|ms-|0.9.1

---

Steps to Reproduce:

1. Use any SQL file - example:
create table if not exists item (itemid integer PRIMARY KEY, 
    idesc varchar(90) NOT NULL, 
    itemgid integer NOT NULL, 
    iuom integer NOT NULL,
    imodelnum varchar(20), 
    iskunum varchar(20),
    iaddress varchar(90), 
    icity varchar(90), 
    izip varchar(10),
    istate varchar(20), 
    icountry varchar(2),
    ilongitude decimal (6, 2), 
    ilatitude decimal (6, 2), 
    ipprice decimal (20,4), 
    ispricemin decimal (20,4), 
    ispricemed decimal (20,4), 
    ispricemax decimal (20,4), 
    ibegval decimal (20,4), 
    ircval decimal (20,4), 
    islval decimal (20,4), 
    isubscription decimal (20, 4),
    isales integer NOT NULL, 
    ipurch integer NOT NULL, 
    istock integer NOT NULL, 
    inetval decimal (20,4), 
    islrate decimal (20,4), 
    iaverate decimal (20,4), 
    iminstk decimal (20,4), 
    isafestk decimal (20,4), 
--     itstatus integer DEFAULT 1 NOT NULL, 
    irelvl decimal (20,4), 
    ieoq decimal (20,4), 
    ilrdate date, 
    ilidate date, 
    iconum integer NOT NULL, 
    iyrno integer NOT NULL,
    FOREIGN KEY (itemgid) references itemgroup (itemgroupid), 
    FOREIGN KEY (iuom) references itemunits (unitid), 
    FOREIGN KEY (isales) references chartacs (accountid), 
    FOREIGN KEY (ipurch) references chartacs (accountid), 
    FOREIGN KEY (istock) references chartacs (accountid));

error:
  ...> --     itstatus integer DEFAULT 1 NOT NULL,
   ...>     irelvl decimal (20,4),
   ...>     ieoq decimal (20,4),
   ...>     ilrdate date,
   ...>     ilidate date,
   ...>     iconum integer NOT NULL,
   ...>     iyrno integer NOT NULL,
   ...>     FOREIGN KEY (itemgid) references itemgroup (it    FOREIGN KEY (itemgid) ref(iuom) references itemunits (unitid),
   ...>     FOREIGN KEY (isales) references chartacs (accountid),
   ...>     FOREIGN KEY (ipurch) references    FOREIGN KEountid),
   ...>     FOREIGN KEY (istock) references chartacs (accountid));
Error: near "FOREIGN": syntax error
sqlite>

2. On the integrated terminal in VSCode, from Foreign Key onwards there's garbage. On an actual terminal, it works fine.
   ...>     irelvl decimal (20,4), 
   ...>     ieoq decimal (20,4), 
   ...>     ilrdate date, 
   ...>     ilidate date, 
   ...>     iconum integer NOT NULL, 
   ...>     iyrno integer NOT NULL,
   ...>     FOREIGN KEY (itemgid) references itemgroup (itemgroupid), 
   ...>     FOREIGN KEY (iuom) references itemunits (unitid), 
   ...>     FOREIGN KEY (isales) references chartacs (accountid), 
   ...>     FOREIGN KEY (ipurch) references chartacs (accountid), 
   ...>     FOREIGN KEY (istock) references chartacs (accountid));
sqlite> 

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
It looks like some characters are going missing or something? Does this reproduce consistently in the same spot?

`itemgroup (it FOREIGN`
