### ISSUE TITLE
Ext host log file not found

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#42018]
Steps:

- In dev, open the output panel and pick the extension host log
- Close dev
- Open dev 

I've often gotten these errors in the dev tools:

![image](https://user-images.githubusercontent.com/22350/35265012-2430ab74-001f-11e8-8ffc-03a17aaa83c1.png)

**Comment by sandy081** [comment]
@joaomoreno I am not able to reproduce it on my system. If you are able to repro it on your system, can we debug it together?
