### ISSUE TITLE
Suggestions to improve Visual Studio Code by making it closer to an IDE

### ISSUE THREAD

**Issue by Raj2032** [Microsoft/vscode#42014]
_Please note that I am NOT asking a question, I am trying to give suggestions_

I have a few suggestions to improve VSCode as there are some issues with it such as:

- There is no "Run" button to run and execute.
- If I make a mistake, it does not show up unless if I have saved the file
- If I open new curly braces and press enter, it would use the Egyptian style curly braces and I wish it would use the other style, for example,

int main() {
}

By default I want it do this as soon as I create these curly braces
int main()
{
}

**Comment by veleek** [comment]
Hey @Raj2032, you may be in luck.  I think that VSCode already supports all of the functionality that you're interested in.

1. On the Debug tab (the No Bugs! icon), you can click the little gear at the top to enable various "Launch Configurations".  You can setup a Launch Configuration such that your code is built and run.  How to do so depends on exactly which VSCode Language Provider you are using so I would take a look at the [launch configuration documentation](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations) (and the rest of the general documentation on debugging provided there) for some more detail.
2. This is another thing that will be dependent on the Language Provider that you're using.  I'm writing some JavaScript code right now, so I have the ESLint extension installed.  That extension provides a setting `eslint.run` which I can set to either `onSave` or - the option you would prefer - `onType` which would allow me to see errors without needing to save.  As before, this is specific to the language and/or extensions you're using so you'd have to see their documentation to determine if they support what you need.
3. For JavaScript (and TypeScript), this behavior is built in to VSCode already.  The `javascript.format.placeOpenBraceOnNewLineFor*` settings can control your preference.  For other languages you can probably get this behavior with an existing extension.  As an example [this plugin](https://marketplace.visualstudio.com/items?itemName=ryannaddy.vscode-format) will put the braces on the lines as you specified.  There may be more full featured extensions, that's just what I found at the time.

**Comment by Raj2032** [comment]
Ok so I am using C++ but right now I am not too sure how to still get C++
to run within VSCode. Could you please give me something specific for C++
(as I am confused), thanks :) I did get a jason file. I don't know what to
do.

**Comment by veleek** [comment]
Sorry, I have never tried running C++ within VSCode.  I recommend installing the "C/C++" extension from the Extensions tab and reading through it's documentation.  If you're still having trouble, post another question with some detail about what you've tried and what errors or problems you're running into.

**Comment by Raj2032** [comment]
I did there is no play button :(

**Comment by Gruntfuggly** [comment]
Go to the debug view (View -> Debug), and click the 'cog' button to the right of where it says "No Configurations". Then choose your debugger and it should create a debug configuration for you. You should now be able to start the debugger with the green arrow button.
