### ISSUE TITLE
editor.formatOnSave prevents onWillSaveTextDocument from firing

### ISSUE THREAD

**Issue by jedmao** [Microsoft/vscode#42013]
- VSCode Version: 1.19.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. `"editor.formatOnSave": true`
2. Open a file that has no formatting (e.g., README.md).
3. Modify the file.
4. Hit save. `onWillSaveTextDocument` is never hit.

@jrieken, you might be interested in this!

See also: https://github.com/editorconfig/editorconfig-vscode/issues/183

**Comment by jrieken** [comment]
Works for me. @jedmao please provide a sample that reproduces this

**Comment by jedmao** [comment]
@jrieken you can clone the [`editorconfig-vscode`](https://github.com/editorconfig/editorconfig-vscode) project and set a breakpoint [here](https://github.com/editorconfig/editorconfig-vscode/blob/5881a2aca11219241189b7a9bc0511dca25695ef/src/DocumentWatcher.ts#L64). Remove `"editor.formatOnSave": true` and the breakpoint is hit. Reintroduce `"editor.formatOnSave": true` and the breakpoint is never hit.

**Comment by jrieken** [comment]
I cannot produce with that sample. Can you check your log (F1 > Show Log > Extension Host) and search for `onWillSave` in that log? What we do is that we ignore willSave-listener that have thrown errors (max 3) or that took too long to finish (max 1500ms). When that happens you'll find entries in the log.

Another theory is that the main side is throwing errors, causing no further listener to run as they run [in sequence](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadSaveParticipant.ts#L305). That'll be in tomorrows insiders, please report back with the information of that

**Comment by jedmao** [comment]
@jrieken `onWillSave` is not in the log and the only thing related to the extension is thus:

```
[2018-01-24 10:38:39.721] [exthost1] [info] ExtensionService#_doActivateExtension
EditorConfig.EditorConfig {"startup":true,"activationEvent":"*"}
[2018-01-24 10:38:39.721] [exthost1] [info] ExtensionService#loadCommonJSModule
C:\Users\jedma\.vscode\extensions\EditorConfig.editorconfig-0.12.0\out\src\editorConfigMain
```

If my `onWillSave` listener threw errors it should still hit the breakpoint on the first line of the callback, no? Anyway, there are no entries in the log.

Your last theory aligns with what I was thinking, based off what I've read. I'll check the Insiders, as you suggested. Stay tuned!

**Comment by jrieken** [comment]
> If my onWillSave listener threw errors it should still hit the breakpoint on the first line of the callback, no?

Nah, at one point we'll simply stop calling you. See: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDocumentSaveParticipant.ts#L78

> I'll check the Insiders, as you suggested

Yeah, I remember vaguely that I have triaged an issue with is about a failing save-hook on the main side. Tomorrow we are smarter

**Comment by jedmao** [comment]
@jrieken it appears to be firing properly in the Insiders edition!

**Comment by jrieken** [comment]
haha, maybe the other thing got fixed in the meantime... I'll ask around

**Comment by bpasero** [comment]
I did not touch that code much, mainly added support to save snapshots recently, but should not have an impact.

**Comment by jedmao** [comment]
Closing for now, unless I can reproduce later.
