### ISSUE TITLE
Save As dialog

### ISSUE THREAD

**Issue by Ngranger** [Microsoft/vscode#42015]
The "Save as type" menu doesn't list SVG as one of the file extensions that someone can save a file as, which seems like an oversight to me.

**Comment by bpasero** [comment]
We only show the first 10 extensions a language mode provides so that the dialog does not explode like this:

![image](https://user-images.githubusercontent.com/900690/35261137-290ee30a-000f-11e8-94a5-5d4a936e0131.png)

Closing as designed.

**Comment by Ngranger** [comment]
![screenshot 2018-01-23 00 46 37](https://user-images.githubusercontent.com/28519061/35262097-c482336e-ffd8-11e7-9fc0-27fff84f3245.png)

This is what I'm referring to, where I have a valid SVG file that I'm using the (File>Save As) method on to save a copy of the SVG to make a variation of the asset and VS Code isn't supplying the option to save the file as an SVG.
