### ISSUE TITLE
编辑器上的"拆分编辑器"的快捷图标点击无响应

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#42019]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (60440c72461e96893766bce73d7bdf1f5136a19f, 2018-01-23T07:19:15.823Z)</li>
	<li>OS Version: Windows_NT x64 10.0.16299</li>
	<li><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
we-app-vscode|eme|0.8.0
code-runner|for|0.8.7
python|ms-|0.9.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
js-atom-grammar|ms-|0.1.14
typescript-javascript-grammar|ms-|0.0.26
java|red|0.17.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
vscode-java-test|vsc|0.2.0

(1 theme extensions excluded)

</details></li>
</ul>

---

Reproduces without extensions: No

**Comment by mjbvz** [comment]
So this issue does not occur when you disable all extensions?

**Comment by czfadmin** [comment]
This issue still occurs when I disable all extensions.
