### ISSUE TITLE
当我更新到最新版之后, 无法分屏了

### ISSUE THREAD

**Issue by zhu110guang** [Microsoft/vscode#42027]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (60440c72461e96893766bce73d7bdf1f5136a19f, 2018-01-23T07:19:15.823Z)</li>
	<li>OS Version: Windows_NT x64 10.0.15063</li>
	<li><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.4
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
php-pack|fel|1.0.1
sublime-keybindings|ms-|3.0.3
seti-icons|qin|0.1.3
vscode-icons|rob|7.19.0
plsql-language|xyz|1.1.2

(1 theme extensions excluded)

</details></li>
</ul>

---

Steps to Reproduce:

1.  click the   '日'  button ,  fail
2. shift+alt +2   success

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
> When I updated to the latest version, can not be split screen

- Does it work in the very latest Insiders version? 
- If not, please give more details about what happens when you click the screen split button.
