### ISSUE TITLE
Explorer: adding a folder to single-folder workspace collapses first folder

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42029]
Steps to Reproduce:

1. start in a single folder workspace
2. add a folder to the workspace

=> the added folder is nicely expanded, but the first one is now collapsed.

This makes adding a folder more hectic than it could be. Ideally the expansion state of the first folder is preserved so that visually only the new folders are added.

**Comment by isidorn** [comment]
I have improved the expansion strategy in the explorer.
Now it covers this case. Let me know if you still find some strange corener case
