### ISSUE TITLE
Debug actions widget comes out while Debug adpator process stops unexpectedly

### ISSUE THREAD

**Issue by HappyUncleMeng** [Microsoft/vscode#42021]
- VSCode Version:1.19.1
- OS Version:Win7 Pro

Steps to Reproduce:

1.Open a new vscode by Extension mode
2.Open a program in the new openning vscode,and run program in debug mode.
3.Find debug process. Kill it by force. Then a message comes out saying Debug adpator process has terminated unexpectedly
4.Then the debug actions widget appears. And the stop button(stop debug) is useless. Seems vscode doesn‘t cut off the seesion between vscode and debug adpator.

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
@HappyUncleMeng I could not reproduce this on my machine.
Can you also reproduce this if you try with latest vscode insiders
https://code.visualstudio.com/insiders/
