### ISSUE TITLE
UI : Force user choice when multiple TS imports are available

### ISSUE THREAD

**Issue by cyrilletuzi** [Microsoft/vscode#42023]
Reopening #41175 as it was closed as a duplicate when it was not. The issue is still here in last insiders.

VSCode Version: Insiders 1.20
TS Version : 2.7

Now that Microsoft/TypeScript#19694 is fixed in TS 2.7, TS imports with multiple sources are proposed in VS Code Insiders.

I've made some students use it in an Angular course, and I have an important UI feedback. The multiple imports suggested for an identical name should not just be proposed : the choice should be forced before including the auto-import.

Otherwise, people very often doesn't notice there is multiple choices, and then just hit "Enter", selecting the default one proposed and resulting in broken code that won't compile (as the import won't be the good one). Even for more experienced users, it happens very often.

(I must say I'm not happy about how I am treated here.

I was the one who initially reported that auto imports feature was completely broken in Microsoft/TypeScript#19694. It was in itself a problem : it was not an edgy case at all, it gave me the impression nobody tested this feature in real world project.

Despite the fact it was a major issue, the fix have been delayed to the next TypeScript release, and VS Code chose to enable it despite it produced broken code. Meaning during 3 months, VS Code was producing broken code in many TS projects, like Angular ones.

When I suggested to just temporarily disable this feature until it was fixed, which would have been the healthy thing to do, I was treated like I was just annoying (see #38551 and #40234).

Now we are finally near an acceptable auto imports feature, but the UI is still problematic, and when I report a feedback from real world usage from many people, my issue is again not taken seriously and marked as duplicate when it's not. As a result, as next VS Code release is very soon, I have no hope it will be fixed for January release, meaning we're going for a fourth month with problematic auto imports.

That's very frustrating and discouraging about participating in OSS.)

**Comment by mjbvz** [comment]
Please provide some repo steps or a small example project

---

I know this is issue is very important to you, but understand the larger picture: auto imports are being used successfully in the wild by lots of JS and TS devs. And feedback tells me that auto imports are adding value for most of these users. This was true even back with TS 2.6. We are not going to turn it off just because it does not work correctly in some cases
