### ISSUE TITLE
UI for a selected file is confusing.

### ISSUE THREAD

**Issue by yashcr07** [Microsoft/vscode#42020]
- VSCode Version: 1.20.0- insider (673355d8)
- OS Version: Windows 10 1706

Steps to Reproduce:

1. Open any file in a project.
2. Now open another file
3. You'll see that the first file which was opened, looks like it is selected, with the second file having less opacity on its backgroud.

This confusing and it takes a few more seconds to realize which file is actually active.

Does this issue occur when all extensions are disabled?: Yes

![vscode bug](https://user-images.githubusercontent.com/7511296/35265406-00d3e642-0046-11e8-9bbf-203150cc0b58.png)

**Comment by bpasero** [comment]
You can turn "preview" off via `"workbench.editor.enablePreview": false`

**Comment by yashcr07** [comment]
But if I start editing the previewed file, it becomes active but it doesn't reflect on the files window as selected.
