### ISSUE TITLE
Debug/Run should not autoclose console if console was open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4203]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. write a small js program that prints to the console
2. open console
3. run it using Ctrl+F5

Observe: you see the output and then the output closes after 1 second. That might be ok for debug but is annoying in run mode.

**Comment by dbaeumer** [comment]
@isidorn not sure if you or Andre. In general I think debug/run should only close the debug console if the console got open programmatically beforehand through a launch.

**Comment by isidorn** [comment]
Setting to march for discussion
