### ISSUE TITLE
gpg warnings prevent signed git commit

### ISSUE THREAD

**Issue by far-blue** [Microsoft/vscode#42033]
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80

I have gpg 2.2 on some of my machines and gpg 2.1 on others. On the gpg 2.1 machines I get a warning 'skipped packet of type 12 in key box' (because gpg2.2 added a new packet type to my keychain structures) but everything still works fine. I can sign commits using git directly on the command line without issues.

However, if I try a signed commit in VSCode it fails. I suspect the warnings are interfering with the process.

**Comment by joaomoreno** [comment]
How does it fail? Can you record a screencast? What does `Git: Show Git Output` show?

**Comment by far-blue** [comment]
It doesn't do or show anything, it just doesn't commit. I select the files I want staged then type in a commit message and click the tick and I just get the little 'working' coloured rectangle constantly moving across the side-pane below the 'SOURCE CONTROL: GIT' title. But no errors seem to show in the git output.

The last three lines of the git output are:
```
git show :portals/domains/javascript/domain/index/index/util.js
git commit --quiet --allow-empty-message --file - -S
git show :portals/domains/javascript/domain/index/index/util.js
```

A 'git status' on the cli shows the files have not been committed.

**Comment by far-blue** [comment]
I restarted and now get a slightly different reaction. I get a 'git: gpg failed to sign the data' error message and the following output:
```
git commit --quiet --allow-empty-message --file - -S
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by far-blue** [comment]
I've resorted to exporting my public keys, deleting the public key store in the .gnupg folder and then re-importing and that seems to have fixed everything. This suggests it is the use of a gpg2.2 keychain with gpg2.1 that is causing the issue.

**Comment by joaomoreno** [comment]
Makes sense. Closing.
