### ISSUE TITLE
Git: Permission denied (publickey). 

### ISSUE THREAD

**Issue by George35mk** [Microsoft/vscode#42039]
From the command line is work perfect
The problem is when I use vscode interface

- VSCode Version: latest
- OS Version: Windows 10

Steps to Reproduce:

1. when I try to push the code or create new branch I get this message
2.

Does this issue occur when all extensions are disabled?: Yes/No 
yes

**Comment by George35mk** [comment]
I have remote server on 192.168.2.3 

In the commad line I can push the code but if I click the button I get a popup with this error

inside the .ssh I have a folder with this config

```
Host 192.168.2.3
    User git
    IdentityFile ~/.ssh/gitlab_rsa
```

please dont close this issue I cannot find exampple solution with Windows 10 vscode

**Comment by George35mk** [comment]
There is any way to configure the RSA key before vscode push the code to prevent this error

**Comment by George35mk** [comment]
the rsa keys are in `C:\Users\George35mk\.ssh`  folder

there i have this files

```
- config
- github_rsa
- github_rsa.pub
- id_rsa
- id_rsa.pub
- known_hosts
```

My work gitlab projects is on remote server and I want to connect with ssh

if I connect with git bash I can create a new branch but I can't do the same with VSCODE gui
The VScode don't communicate with this repository

## This work is creating new branch on the server on 192.168.2.3
![1](https://user-images.githubusercontent.com/20750445/35325777-6634d462-00fd-11e8-8b1f-093646d33e0d.PNG)


## But when I do the same thing with the VScode like this I get this error popup

![2](https://user-images.githubusercontent.com/20750445/35325970-fa2832f4-00fd-11e8-98c9-4823d16bb6a1.PNG)

![3](https://user-images.githubusercontent.com/20750445/35325981-0042ec42-00fe-11e8-8ce9-bdd73e75d164.PNG)

**Comment by George35mk** [comment]
basically, I can't do anything with vscode on this type of repository

**Comment by George35mk** [comment]
The VScode don't even ask me for ssh keys, nothing if this is the problem

**Comment by joaomoreno** [comment]
You're actually making different operations in both examples. In the command line you are simply creating a branch. In VS Code, you're creating it and trying to push it to the remote. The branch was successfully created... the status bar actually reports the correct branch name.

Can you run `git push` from a normal Command Prompt?

**Comment by George35mk** [comment]
ok give me  a sec

**Comment by George35mk** [comment]
if I run on power shell this command I get this message
```Everything up-to-date```

**Comment by George35mk** [comment]
Joao Moreno, Now I work with git bash and I have created the branch on the remote the problem is I have lost all the interactive features that VScode provide with git integrations I can commit the change with VScode but I cannot pull, Push or to see the changes. I see all the time this icon on the bottom and does not disappear even when I have created and publish the branch.

![4](https://user-images.githubusercontent.com/20750445/35330450-2973d71c-010c-11e8-842c-595d20e24cc4.PNG)

**Comment by George35mk** [comment]
In gitbash when I create or commit new changes or push. is askme for the password
```
$ git push origin ng-gui
Enter passphrase for key '/c/Users/George35mk/.ssh/id_rsa':
```

If the vscode can do the same is gonna work

**Comment by George35mk** [comment]
Or If is possible to set a workspace in VScode and set a password for the ssh key for this project

**Comment by George35mk** [comment]
I want to say that when I run `git status` I get this

```console
On branch ng-gui
```

**Comment by George35mk** [comment]
OMG Finaly I find the solution to this freakin Error

- Step 1 in your project folder run **`start-ssh-agent`**
- Step 2 add your id_rsa or whatever name of your private RSA key **password**
- Step 3 in the same directorie opn the cmd or power shell and run **`code`**

**Comment by stoberov** [comment]
Hey,

A VSCode user since the very beginning here. 

The same thing (permission denied error) started happening to me since the last Windows update we got at the office ~3-4 days ago. 
 
Indeed, one solution is to run **start-ssh-agent** inside the Integrated Terminal, but it has to be done every time. Another solution is to run the VSCode instance with administrator privileges - still a bit annoying.

@joaomoreno , I wonder if there is some edge case that VSCode does not cover for?

**Comment by George35mk** [comment]
Yes, bro, I get the same  error again after the new windows 10 update I solve this problem in the past 

by using the https version and nor the *ssh* I solve this problem but again in new update the not even the https let me push I pc is complicated I have gihub, bitbucket and gitLab I try the solution you propose with the administration rights. 

Thanks, Best George35mk.

**Comment by stoberov** [comment]
Hey,

Thanks for a quick reply! In those 8 minutes, I too noticed that the issue was present with projects where the git origin was set to **git**@git........git . Other projects that are using origin **https**://git..... do not experience the issue. 

So, my temporary solution at the moment is to migrate from GIT to HTTPS - **git remote set-url origin https://git.xxxxxxxxxxxxxxxxxxxxxxxxx.git** .

Will see how it goes.

**Comment by joaomoreno** [comment]
Guys check this comment: https://github.com/Microsoft/vscode/issues/44244#issuecomment-368250055
