### ISSUE TITLE
Split Editor menu button doesn't work

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#42031]
### Issue Type: Bug
![screenshot 4](https://user-images.githubusercontent.com/9638156/35272011-df1c727c-0044-11e8-9d04-98d773b88dbf.png)

VS Code version: Code - Insiders 1.20.0-insider (60440c72461e96893766bce73d7bdf1f5136a19f, 2018-01-23T07:19:15.823Z)
OS version: Windows_NT x64 10.0.17063

**Comment by bpasero** [comment]
Good catch 👍
