### ISSUE TITLE
Changing default keybind for toggleWordWrap still uses default bind

### ISSUE THREAD

**Issue by grzegorzjudas** [Microsoft/vscode#42038]
- VSCode Version: 1.19.2
- OS Version: OSX Sierra

Steps to Reproduce:

1. Open keybindings.json
2. Add following to the array:
```js
    {
        "key": "cmd+l", // lowercase L
        "command": "editor.action.toggleWordWrap"
    }
```
3. Open a new document
4. Enter a long text without spaces so it's longer than the screen width
5. Press default toggleWordWrap keybind (alt+z)
6. Press modified keybind (cmd+l)

**Expected:**
Only cmd+l changes the line wrapping

**Actual:**
Both keybinds still change the word wrapping

This is critical for me, as alt+z is, using Polish system keyboard layout, a character "ż" (all other special characters for the language work, and it also work fine for other programs and system).

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

**Comment by grzegorzjudas** [comment]
Thanks!

It did indeed work. That being said, the default should still be overridden by custom rule, no? Not use both at the same time.

**Comment by usernamehw** [comment]
It just works this way ¯\\\_(ツ)\_/¯

**Comment by grzegorzjudas** [comment]
Anyways, I think having to write custom rules/disabling default rules for Polish system with Polish keyboard layout in order to write Polish characters, which work just fine for other programs is something to at least think about...

**Comment by alexandrudima** [comment]
@grzegorzjudas Sorry about that, I guess you are trying to produce `ź` (option - z). We have tried quite hard to find keybindings that are useful for the majority of users, but at one point we ran out of cmd+ keybindings.

We currently ship with a single default set of keybindings, which is not optimized per keyboard layout. We have some heuristics to bind to the current keyboard layout, but they are all runtime heuristics and not something designed by a human. This is something you can upvote in #1240

The good news is that you can remove it; an easier gesture is to press the edit button next to the command in the Keybindings Editor (cmd+k cmd+s) which will remove the keybinding for you in `keybindings.json`.
