### ISSUE TITLE
Changes to files not being automatically reflected to Git source control

### ISSUE THREAD

**Issue by victorasantos10** [Microsoft/vscode#42045]
- VSCode Version: 1.19.2
- OS Version: Windows 10 Enterprise x64 10.0.10586 Build 10586

In previous versions of VSCode, all changes was automatically reflected to Source Control after saving files. Now, we need to click "Refresh" to include it.  I didn't found anything that describes this as a feature.

Demo:

![ezgif-4-512c60e886](https://user-images.githubusercontent.com/8058097/35287448-43631e9c-005a-11e8-9e0f-858f070dc2dc.gif)

The bug still occurs when launching with `code --disable-extensions`.

**Comment by Gruntfuggly** [comment]
There is a preference "git.autorefresh" - it might be set to "false" ?

**Comment by victorasantos10** [comment]
@Gruntfuggly Tried to set it to false, restarted VSCode, true, restarted again. Still happens

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by victorasantos10** [comment]
@joaomoreno Tried on insider release, and isn't happening.

**Comment by joaomoreno** [comment]
Great!
