### ISSUE TITLE
editor.useTabStops: false causes weird cursor behavior on outdent

### ISSUE THREAD

**Issue by inosik** [microsoft/vscode#42041]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spaces-inside-braces|Air|0.3.1
TabOut|alb|0.1.4
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.12.1
bettergitcommits|dav|0.5.0
EditorConfig|Edi|0.11.1
genuuid|esp|0.3.3
auto-close-tag|for|0.5.5
Ionide-fsharp|Ion|3.15.8
Ionide-Paket|Ion|1.8.1
vscode-icon-theme|jtl|1.6.1
csharp|ms-|1.13.1
embrace|myc|1.0.0
vscode-subword-navigation|ow|1.1.5
vscode-code-outline|pat|0.0.12
subtle-brackets|raf|2.1.0
vscode-yaml|red|0.0.8
rewrap|stk|1.6.1
vscode-cil-complete|wk-|0.0.5

(7 theme extensions excluded)

---

I use the Ionide plugin for F#, which sets `editor.useTabStops` to `false` for F# files to prevent #27851. When trying to outdent in a new line, the cursor jumps to the beginning of the line, but the whitespace characters are _outdented_, as if `editor.useTabStops` was set to `true`. I did a screen capture with `"editor.renderWhitespace": "boundary"`, to show what happens:

![Screen capture](https://user-images.githubusercontent.com/11393003/35280876-c82517f6-0051-11e8-991c-6854844c0e80.gif)

I don't know if the actual cursor behavior is as designed or not, but these whitespace characters end up as trailing whitespace when using `"files.trimTrailingWhitespace": false`, which I sometimes use to prevent unnecessary whitespace diffs in some OSS projects.

Steps to Reproduce:

1. Set `editor.useTabStops` to `false`
2. Outdent

Reproduces without extensions: Yes

**Comment by kspeakman** [comment]
This is super annoying. See my comments from the linked issue.

**Comment by jamesderlin** [comment]
This drives me crazy.  With `editor.useTabStops: true`, I get annoying behavior that affects the backspace key on a new indented line, making it outdent instead acting like a normal backspace.  That seems silly since if I wanted to outdent, I could use Shift+Tab, and it makes removing single spaces of indentation hard.

With `editor.useTabStops: false`, I get annoying behavior that affects Shift+Tab, outdenting and moving the cursor to the beginning of the line.

So `editor.useTabStops` is a damned-if-you-do, damned-if-you-don't setting for me.

**Comment by inosik** [comment]
If that helps, I use the (now deprecated) [Backspace++ extension](https://marketplace.visualstudio.com/items?itemName=jrieken.backspace-plusplus) to work around this. I usually use <kbd>Backspace</kbd> to outdent in Visual Studio as well, so I don't have to adapt my typing much.

The deprecation notice of the extension says that VS Code behaves like that now, but it seems it doesn't with `editor.useTabStops` being set to `false`.

**Comment by rebornix** [comment]
I'm not able to reproduce this issue in latest Insiders, please report if you are still seeing it.

**Comment by inosik** [comment]
You're right, VS Code 1.50.1 seems to be fixed as well. This might have been fixed accidentally.
