### ISSUE TITLE
Badge loading color doesn't use badge foreground

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#42047]
1.20 60440c72461e96893766bce73d7bdf1f5136a19f 2018-01-23T07:19:15.823Z

![dark_text_for_badge](https://user-images.githubusercontent.com/9638156/35290197-83ee93c2-007a-11e8-926d-f7b864374b96.png) ![white_text_when_loading](https://user-images.githubusercontent.com/9638156/35290202-88f1fcba-007a-11e8-9e78-395578e16e48.png)

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/blob/57d505aeeb5269e93ec95a09178c95c230573bf5/src/vs/workbench/services/progress/browser/media/progressService2.css#L14

**Comment by jrieken** [comment]
Needs a better icons I guess

**Comment by usernamehw** [comment]
Closing as duplicate of #44604
