### ISSUE TITLE
Dropdown menu is shown on the wrong screen first time

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#42044]
- VSCode Version: 1.19.2
- OS Version: xubuntu 16.04
I have two monitors. The bug:
![peek 2018-01-23 19-05](https://user-images.githubusercontent.com/7345761/35286248-82891750-0070-11e8-87b2-b0dcdefdef95.gif)

**Comment by bpasero** [comment]
We fixed this in insiders.
