### ISSUE TITLE
Integrated terminal hangs on startup

### ISSUE THREAD

**Issue by benorosz** [Microsoft/vscode#42042]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Open terminal

I've tried it with Powershell, cmd, and bash and the results are the same each time. Terminal path is valid, I'm using the 64-bit paths on a 64-bit system, there are no errors in the dev tools, there are no special characters in any of the paths, and I've looked here for similar issues and found #37044 that describes exactly my issue, but it was closed with nothing actually resolved. The weird thing is that it was working just fine a few weeks ago, then without any updates to anything (to my knowledge), the terminal stopped functioning entirely. I've tried a fresh install as well but no dice.

**Comment by Tyriar** [comment]
@benorosz I haven't been able to reproduce this class of issues unfortunately.

Can you share you settings.json and anything special about your setup/env?

**Comment by benorosz** [comment]
> {
    "git.path": "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Git\\git.exe",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "workbench.colorTheme": "Visual Studio Dark",
    "editor.minimap.enabled": false,
    "explorer.enableDragAndDrop": false,
    "editor.renderIndentGuides": false,
    "git.decorations.enabled": false,
    "editor.dragAndDrop": false,
    "workbench.tips.enabled": false,
    "files.exclude": {
        "dist": true
    },
    "editor.scrollBeyondLastLine": false,
    "workbench.settings.openDefaultSettings": false,
    "window.newWindowDimensions": "maximized",
    "html.format.indentInnerHtml": true,
    "terminal.integrated.cwd": "C:\\Users\User\\git\\ecorr-spa",
    "git.defaultCloneDirectory": "C:\\Users\User\\git\\ecorr-spa",
    "html.autoClosingTags": false,
    "workbench.startupEditor": "newUntitledFile"
}

Nothing unusual about my environment as far as I'm aware.

**Comment by Tyriar** [comment]
Ok, I'll close this in favor of https://github.com/Microsoft/vscode/issues/37044 then to keep the issue count down as it's the same issue.
