### ISSUE TITLE
Issue reporter is always on top

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#42057]
### Issue Type
Bug

### Description

I'm not yet sure if I like that the issue reporter is always on top of my workbench window. 

However, it's always on top even of windows from another application. For example, when I press "Preview in GitHub" the browser opens below the issue report. I have to manually move it away or close it.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (60440c72461e96893766bce73d7bdf1f5136a19f, 2018-01-23T07:11:12.714Z)
OS version: Darwin x64 16.7.0

**Comment by RMacfarlane** [comment]
Fixed with #42028
