### ISSUE TITLE
[c++] Strings containing an open-curly brace inside a function call at the end of a function are not terminated, highlighted the rest of the file as a string.

### ISSUE THREAD

**Issue by xHuike** [Microsoft/vscode#4205]
- VSCode Version: 0.10.10
- OS Version: Debian GNU/Linux 8.3 (jessie)

Steps to Reproduce:

1. Type this into your editor:
void editorBug()
{
    anotherFunct("{");
}
2. Everything after the second quote will be highlighted as a string, as if the string was not terminated.

**Comment by aeschli** [comment]
What language is that? Java, C#...?

**Comment by xHuike** [comment]
It's C++.

**Comment by aeschli** [comment]
Can't reproduce. This seems to be fixed:
![image](https://cloud.githubusercontent.com/assets/6461412/13776273/86a288c8-eaa9-11e5-995c-26c9431d0dcf.png)
