### ISSUE TITLE
Issue Reporter should open on the same display as the workbench window

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#42056]
### Issue Type
Bug

### Description

1) Working with two displays
2) Open workbench window on display 2
3) Open issue reporter
-> Issue reporter opens on display 1

The issue reporter should open on the same display.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (60440c72461e96893766bce73d7bdf1f5136a19f, 2018-01-23T07:11:12.714Z)
OS version: Darwin x64 16.7.0

**Comment by RMacfarlane** [comment]
Fixed with #42028
