### ISSUE TITLE
my debug bar and breakpoints disapeared. cant see the breakpoints red ball even  though the code stops when they are hit. same thing with the debug little bar (top bar). cant see it anymore.

### ISSUE THREAD

**Issue by mttdev-br** [Microsoft/vscode#42059]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
html-css-class-completion|Zig|1.16.1
vscode-color|ans|0.4.5
vscode-styled-jsx|bla|0.2.2
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
vscode-icons|rob|7.19.0
react-beautify|tai|0.3.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please provide nice reproducable steps so we can investigate.
Also please try reproducing with vscode insiders https://code.visualstudio.com/insiders/

**Comment by olivierchatry** [comment]
I have the same issue on 1.19.2, but I'm not sure how to reproduce it. Working on a nodejs express server. Only this project is affected by the bug. VS insiders seems to work.

**Comment by isidorn** [comment]
If vsinsiders works then there is nothing we can do here.
There will be a stable update in about 2 weeks which will have all the ifxes from insiders

**Comment by isidorn** [comment]
Also seems to be duplicate of https://github.com/Microsoft/vscode/issues/42109
