### ISSUE TITLE
Debug: replace notification about "errors in workspace" with a modal dialog

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42050]
I find this flow very weird:
* I F5 to start debug
* I have errors in my workspace
* a non-modal message pops up asking me if I want to debug anyway

Imho it would be tolerable to show a modal confirmation dialog in this case that asks me to proceed. Clicking on proceed would continue to debug.

/cc @weinand

**Comment by isidorn** [comment]
Showing a native modal blocking dialog here makes sense.
@weinand let me know if you have any objections?

**Comment by isidorn** [comment]
![screen shot 2018-01-25 at 17 54 02](https://user-images.githubusercontent.com/1926584/35401053-c1a095d8-01f8-11e8-98ac-10db73a80d98.png)

**Comment by bpasero** [comment]
@isidorn very cool 👍
