### ISSUE TITLE
Cannot find runtime 'node' on PATH for nvm installed node

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42053]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (d21e6a3e388897a2250cb10ae897b6481e0bd61d, 2018-01-19T07:10:59.044Z)</li>
	<li>OS Version: Darwin x64 17.3.0</li>
	<li><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.3.0
material-icon-theme|PKi|3.2.1
vscode-eslint|dba|1.4.4
tslint|eg2|1.0.24
prettier-vscode|esb|1.1.2
debugger-for-chrome|msj|4.0.0
vim|vsc|0.10.13

(1 theme extensions excluded)

</details></li>
</ul>

---

Steps to Reproduce:

1. Have an index.js with a `console.log`
2. Use the auto generated launch config

![image](https://user-images.githubusercontent.com/4033249/35295190-5280e31e-002d-11e8-97b8-672d477d6c36.png)

I only have one node installed through NVM.
After installing I have this in my `.zshrc`:

```bash
export PATH=~/.nvm/versions/node/v8.9.1/bin:$PATH
```

```bash
repro > node --version
v8.9.1
repro > where node
/Users/octref/.nvm/versions/node/v8.9.1/bin/node
repro > echo $PATH
/Users/octref/.nvm/versions/node/v8.9.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by octref** [comment]
If I put `"runtimeExecutable": "/Users/octref/.nvm/versions/node/v8.9.1/bin/node"` in the debug config the error goes away.

**Comment by octref** [comment]
After talking to @roblourens, I found putting this line in `~/.bash_profile` solved the problem.

```bash
export PATH=~/.nvm/versions/node/v8.9.1/bin:$PATH
```

However, I'm wondering how can I make VS Code read the PATH from my login shell (zsh).

**Comment by joaomoreno** [comment]
That's odd. What is the value of your `SHELL` variable?

**Comment by octref** [comment]
```
> process.env.SHELL
"/bin/zsh"
> process.env.PATH
"/Users/octref/.nvm/versions/node/v8.9.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
```

Yesterday when I was checking with Rob, I'm sure the PATH had been `"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"`.

However now if I drop this line off my `~/.zshrc`, 
```bash
# export PATH=~/.nvm/versions/node/v8.9.1/bin:$PATH
```

The `process.env.PATH` still have the nvm PATH in it. Seems it's not affected by my zshrc setting even though my default shell is `/bin/zsh`.

**Comment by roblourens** [comment]
Did you launch vscode from a terminal this time?

**Comment by octref** [comment]
Interesting...So this would happen:

- Install code-insiders to PATH
- `/usr/local/bin/code-insiders` get created
- I modify my `~/.zshrc` to exclude the nvm line that changes the PATH
- `/usr/local/bin/code-insiders` is gone

**Comment by joaomoreno** [comment]
OK I'm really confused. Wanna do a screensharing session?

**Comment by octref** [comment]
@joaomoreno Somehow the problem is gone and I'm never able to repro it again. I guess it's because I removed a bunch of zsh-plugins and some sections in my `~/.zshrc` (which I initially setup on Linux and moved as-is to macOS). If it comes up again I'll let you know.
