### ISSUE TITLE
Log Uploader - word smithing

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#42058]
### Issue Type
Bug

### Description

This is what the uploader is currently saying:

```
Upload session logs to secure endpoint?

Please review your log files: '/xxxx/xxxxx/Library/Application Support/code-oss-dev/logs/20180123T113255'

Enter 'y' to confirm upload...
```

We need to be more explicit about the logs may contain personal information and should be reviewed. The confirmation needs to be around that the user has reviewed the logs and agrees to upload them in the current form.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (60440c72461e96893766bce73d7bdf1f5136a19f, 2018-01-23T07:11:12.714Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.33GB free)|
|Process Argv|/Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_786624|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Made recommended additions/changes:

<img width="804" alt="screen shot 2018-01-26 at 1 12 59 pm" src="https://user-images.githubusercontent.com/12821956/35460988-b9354ce8-029a-11e8-80ae-93205d743492.png">

**Comment by kieferrm** [comment]
Here is another wording proposal:

```
You are about to upload your session logs to a secure Microsoft endpoint that only Microsoft's members
of the VS Code team can access.

Session logs may contain personal information such as full paths or file contents. Please review and redact your session
log files here: ....

I confirm that I have reviewed and redacted my log files and I agree to Microsoft using them to debug VS Code.
```
