### ISSUE TITLE
Missing GDPR annotation

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42068]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/electron-browser/outputServices.ts#L562

FYI, just noticed this

**Comment by sandy081** [comment]
@kieferrm Not sure how we add this GDPR annotation. I see you have taken care for all. Are you still updating them or it has to be done by each one of us introducing the telemetry data? If so is there a guidance for the format ?

**Comment by sandy081** [comment]
Removed the telemetry entry as it is no longer needed
