### ISSUE TITLE
arm64 linux support?

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#42067]
can we get a build for 64-bit ARM?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6442

**Comment by Spongman** [comment]
errr. that issue is about the rapberry pi which is armhf. this is specifically about arm64.

**Comment by Tyriar** [comment]
@Spongman when we support raspberry pi we will likely add support for arm64 at the same time.

**Comment by Spongman** [comment]
Brilliant!
