### ISSUE TITLE
Add the ability to change the font size and font family of the file explorer

### ISSUE THREAD

**Issue by cvachon-akivo** [Microsoft/vscode#42060]
Please add settings for `explorer.fontSize` and `explorer.fontFamily`.

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
mssql|ms-|1.3.0
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.0.0

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/519
