### ISSUE TITLE
Feature request: Don't close the task terminal when I press a button

### ISSUE THREAD

**Issue by petekinnecom** [Microsoft/vscode#42066]
- VSCode Version: 1.20.0-insider/60440c72461e96893766bce73d7bdf1f5136a19f/x64
- OS Version: MacOS

Steps to Reproduce:

1. Add this as a custom task in a non-empty project. (Or on windows, run any command that displays the path to a file in your project.) 

```
    {
      "args": ["."],
      "command": "find",
      "presentation": {
        "echo": true,
        "focus": true,
        "panel": "new",
        "reveal": "always"
      },
      "problemMatcher": [],
      "taskName": "repro",
      "type": "shell",
    }
```
2. Run the 'repro' task.
3. When the process terminates, see the text: "Terminal will be reused by tasks, press any key to close it."
3. Try to `cmd+click` on one of the file paths to open the file in an editor.
4. Terminal closes as soon as you push cmd, so you can't click on the path. 

Does this issue occur when all extensions are disabled?: Yes

I think this behavior is recently introduced in the insiders build.

Essentially, I have a task (running tests) that outputs a stack trace when it fails.  It used to be that I could `cmd+click` on some `/path/to/file.ext:123` and get right to the code that failed. But now the terminal closes as soon as I start pressing `cmd`.

This also means that I can't use search in the terminal, because I need to press `cmd+f`. 

Specifying `"focus": false` in the task's json somewhat mitigates the issue. However, I sometimes debug my tests interactively in the terminal during a test run, so the terminal ends up with focus regardless in many cases.

Let me know if there's a switch/setting I'm missing. If not, a global setting or a per-task setting to disable the "Terminal will be reused by tasks, press any key to close it." behavior would be great.

Thanks for the application and hard work!

**Comment by Tyriar** [comment]
What I'm hearing is modifiers should not be considered, and commands that will trigger keybindings (cmd+f) should not close.

**Comment by gwk** [comment]
Yes! Another glaring example is trying to copy a string from the build output with `cmd+c` - the current behavior is maddening. Thanks!

**Comment by Tyriar** [comment]
This is actually a regression and the fix I added doesn't fix everything It was caused by this PR: https://github.com/Microsoft/vscode/pull/38714 (https://github.com/Microsoft/vscode/issues/37983)

**Comment by Tyriar** [comment]
Reverted the commit that caused the issue https://github.com/Microsoft/vscode/pull/38714/commits/f32ed90bebdeef4713ba62fc2c4a663e693a3905 and cherry picked the revert to release/1.20

**Comment by BillDenton** [comment]
When is the recovery build that fixes this major issue going to be released? Every time I get a build error that I need to click on this catches me so I have to do another build to see the error. IMHO it is a bit early to close the issue given that there isn't release build that is fixed.

**Comment by Tyriar** [comment]
@BillDenton it's out now. We close the issue when the issue is fixed not when it's released, that's the process.

**Comment by BillDenton** [comment]
@Tyriar Just updated and tested it. Working OK - a relief. Thanks.
