### ISSUE TITLE
Check casing of locale string with module resolution and loader names

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4206]
- VSCode Version: 0.10.12-alpha
- OS Version: all

Currently the nls bundles are generated with filename where locale information is all lower case. However the country/dialect part of a locale (e.g. CH in de-CH) is usually specified using uppercase characters which is not matching the file on disk if the disk is case sensitive (e.g. Linux and may be MAC). The needs to be changes and tested on both Chinese locales since they have a dialect / country part.

**Comment by dbaeumer** [comment]
Changed by generating files where the territory part is in uppercase which matches what gets returned from the OS.

**Comment by dbaeumer** [comment]
Steps to verify: 
- Linux
- start code from a shell and pass --locale=zh-tw
- ensure locale is NOT picked up
- start code from a shell and pass --locale=zh-TW
- ensure locale is picked up.

**Comment by aeschli** [comment]
Verified
