### ISSUE TITLE
when click or press command key click the class string in template label or click @click method it not jump the style or method implementation

### ISSUE THREAD

**Issue by songxing10000** [Microsoft/vscode#42069]
- VSCode Version:1.19.2
- OS Version:10.12.6 (16G29)
![image](https://user-images.githubusercontent.com/10040131/35309598-43372cfe-00e8-11e8-87ce-e9b5e9e54160.png)

![image](https://user-images.githubusercontent.com/10040131/35309619-5be735c8-00e8-11e8-8050-16297ca2f81f.png)

**Comment by usernamehw** [comment]
https://github.com/vuejs/vetur/issues
