### ISSUE TITLE
Non standard shortcut for closing window on macOS

### ISSUE THREAD

**Issue by BrettGregson** [Microsoft/vscode#42078]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0

**Steps to Reproduce:**

Pressing CMD + W when no documents are open closes the main window. *This is not standard macOS behaviour*. This is particularly irritating when closing a large amount of documents rapidly using the shortcut, as pressing it one too many times closes the main window

**Comment by bpasero** [comment]
Keybindings are configurable.
