### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by unixc3t** [Microsoft/vscode#42079]
when I install the vetur plugin , I found the error
Platform: linux mint
Vetur version:latest
VS Code version:latest

![dd](https://user-images.githubusercontent.com/4446148/35310553-eea52a42-00ec-11e8-913f-e4a93677b443.png)

**Comment by mjbvz** [comment]
Does this still happen if you disable all extensions and restart VS Code?

**Comment by unixc3t** [comment]
@mjbvz  I disable all extensions ,  I install the vetur plugin ， I found the error, end of central directory record signature not found

**Comment by unixc3t** [comment]
@mjbvz  I download the plugin from
https://octref.gallery.vsassets.io/_apis/public/gallery/publisher/octref/extension/vetur/0.11.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

I Manual installation it  and slove the install question

**Comment by joaomoreno** [comment]
Yeah we should really provide a manual override for this.
