### ISSUE TITLE
Typescript intellisense doesn't work for files listed in tsconfig.json

### ISSUE THREAD

**Issue by RANUX** [Microsoft/vscode#4207]
- VSCode Version: 0.10.10
- OS Version: OS X Yosemite

Intellisense doesn't work when i manually list files in "files" directive in tsconfig.json. Sample project https://github.com/RANUX/vscode-ts-project-tests 
First i created tsconfig.json:
```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "system",
    "target": "es5"
  },
  "files": [
    "typings/meteor/meteor.d.ts"
  ]
}
```
Then i created file "typings/meteor/meteor.d.ts" with type definitions for Meteor and started to write code in other .ts file. After that i tried to access to Meteor declaration in my new .ts file, but found that intellisense doesn't work.

**Comment by dbaeumer** [comment]
@RANUX this is the design of the TS compiler (tsc and tsserver). As soon as you add a files section only files listed are consider to be part of the project defined by that tsconfig.json file. The other file will be in its own project scope. This is how tsc works. If you think tsc should change that behavior please file an issue here: https://github.com/Microsoft/TypeScript/

**Comment by RANUX** [comment]
@dbaeumer but the problem is that I can't get intellisense for files only listed in "files" section. I understand that files listed in "files" section only accessible for project where tsconfig.json placed in root of the project structure.

**Comment by dbaeumer** [comment]
@RANUX you need to have both collection.ts and meteor.d.ts. Sorry for not being precise about this earlier. If you have only meteor.d.ts in the files section and you open collection.ts the collection.ts will open in its own virtual project not knowing anything about meteor.d.ts. That is why you don't get intellisense in that case.

Pls ping if adding both files to the files section doesn't fix the problem.

**Comment by RANUX** [comment]
@dbaeumer thank you! Now intellisense works fine. But i think, it's not obvious behavior and it should be documented somewhere, maybe in FAQ.
