### ISSUE TITLE
Hiding editor region doesn't trigger codelens rendering

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#42072]
- Set `"workbench.settings.useNaturalLanguageSearchPost": true`
- Open settings editor, search "a"
- Don't scroll. Collapse the "filtered results" section
- See in the "marketplace extensions" section that there are gaps for the codelenses but they have not faded in yet
- Scroll a little bit
- See that it triggers the codelenses to appear

**Comment by jrieken** [comment]
This is actually working in the meantime...
