### ISSUE TITLE
About Search

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#42075]
hope vs-code provide multi search results view. can see several keyword result at the same time .

**Comment by usernamehw** [comment]
Use regex?

**Comment by doyee** [comment]
@midGitub you can use regex search

**Comment by midGitub** [comment]
thanks ,that's a solution.

**Comment by roblourens** [comment]
Also duplicate of https://github.com/Microsoft/vscode/issues/16488

**Comment by mccreeker** [comment]
Not seeing how to do a regex search that's separate from a normal search... I need multi-search instances due to comparing two different code installs for a site conversion.
