### ISSUE TITLE
Pasting into JavaDoc style comments doesn't add asterisk.

### ISSUE THREAD

**Issue by goldingdamien** [Microsoft/vscode#42073]
Not a major issue, but when pasting text into JavaDoc style comments, it would be convenient if it auto-formatted. If this is possible via another method please let me know.

**Comment by warpdesign** [comment]
I also noticed.

**Comment by mjbvz** [comment]
Duplicate of #25894

**Comment by goldingdamien** [comment]
Just want to note that this is being closed due to a duplicate which was closed due to not enough traction.
Maybe this issue voids that reason.

**Comment by warpdesign** [comment]
@goldingdamien I guess it does.
