### ISSUE TITLE
vscode terminal path word wrap issue

### ISSUE THREAD

**Issue by VinayKumarVerma** [Microsoft/vscode#42083]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Angular2|joh|2.11.2
debugger-for-chrome|msj|4.0.0
vscode-icons|rob|7.19.0
html-css-class-completion|Zig|1.16.1

---

Steps to Reproduce:

1. Open the project with long file path
2. Open the terminal 
3. Move the terminal to right by clicking on `move to right` view
4. Try resizing the terminal 
5. Instead of wrapping the file path its open few more lines of file path

> Example
- xxxxxxxxxxxxxxxx/e/Code/react-practise/my-app
- xxxxxxxxxxxxxxxx/e/Code/react-
- xxxxxxxxxxxxxxxx /e/Code/react-
- xxxxxxxxxxxxxxxx/e/Code/react-
- xxxxxxxxxxxxxxxx/e/Code/react-
- xxxxxxxxxxxxxxxx/e/Code/reac
- $

Reproduces without extensions: Yes

**Comment by warpdesign** [comment]
I confirm: the problem is still there in latest insider build:

Version 1.20.0-insider
Commit 8eae654dd46d0a184353f8062d013279a73053a8
Date 2018-01-24T05:13:15.227Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26375
