### ISSUE TITLE
Emmet not works in latte files

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#42089]
#Hi, 
emmet is not works in latte lang / file (no problem in html)
see short video, how to solve it?

![](http://files.rjwebdesign.cz/i/20180124-124658.gif)

Of course, I set includeLanguages in user settings
![](https://goo.gl/Q6yYFy)

**Comment by Kcko** [comment]
After multiple reset of VSC it started working 😄

**Comment by ramya-rao-a** [comment]
Not sure what happened there :)
If you see the issue again, please feel free to re-open
