### ISSUE TITLE
Canceling new file/ new directory / rename action should not move focus away

### ISSUE THREAD

**Issue by agos** [Microsoft/vscode#42084]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0

---

## Steps to Reproduce:

1. Focus on explorer
2. Start new file / new directory / rename action via shortcut
3. Cancel the action by pressing ESC

## Expected behaviour: 

The focus is still on the file explorer, and pressing the same shortcut should have the same effect

## Actual behaviour:

The focus is not on the file explorer, nor on the frontmost buffer. The file action shortcuts will do nothing.

### Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Fixed in latest insiders. Will be in stable in 2 weeks. Basically duplicate
