### ISSUE TITLE
Wrap with Abbreviation not working for JSX tags in VSCode v1.19.2

### ISSUE THREAD

**Issue by fiznool** [Microsoft/vscode#42085]
- VSCode Version: 1.19.2
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Create a new `.js` file and import React.
2. Write some JSX.
3. Select the JSX, `Cmd-Shift-P` and choose `Emmet: Wrap with abbreviation`

Expected outcome:

- Should be able to type the tag that you want to wrap with, and it should wrap the JSX

Actual outcome:

- Nothing happens. I'm pretty sure this used to work on a previous version of VSCode.

Does this issue occur when all extensions are disabled?: Yes

![emmet](https://user-images.githubusercontent.com/820863/35328797-7a1faa4a-00f5-11e8-9c7c-b88d2479283f.gif)

**Comment by ramya-rao-a** [comment]
You are working on a js file which doesnt have emmet support by default. Can you change the language mode to `javascriptreact`? 

Click on `Javascript` on the bottom right corner. Select `Javascript React` from the drop down that will then appear
