### ISSUE TITLE
Building VS Code - Importing a npm module 

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#4208]
I was trying to understand how to import a npm module into vscode.  So far I have added added the npm module to `package.json` with `./scripts/npm.sh install modulename --save`.  I have added it also to `gulpfile.vscode.js` to the array `baseModules`.  I have created a typings file for it as well but when I run `gulp watch` and `./scripts/code.sh` I keep getting an error saying my npm module that I am trying to use does not exist.  What is the correct steps to import and use a npm module?

**Comment by NickHeiner** [comment]
This doesn't sound like it has anything to do with VSCode. It sounds like you're just using Node.js incorrectly. What is the exact error message? 

What is in `./scripts/npm.sh`?

**Comment by jsloyer** [comment]
`./scripts.npm.sh` is the wrapper for npm for vscode.  This is nothing to do with Node.js, I have added a package to `package.json`.  I am wondering how I register the package with vscode to be able to call the package in a typescript file.

**Comment by aeschli** [comment]
@jsloyer Where is the code located that tries to access that node module? In the VS code main code base (/src) or is it an extension?

**Comment by triceam** [comment]
It is in a fork of VS Code main, not in an extension (working with @jsloyer on this).

**Comment by jsloyer** [comment]
@aeschli I was more or so wondering how to pull in a npm module and then call it from typescript.

**Comment by jsloyer** [comment]
Closing in favor of #4265 with detailed steps on how to reproduce.
