### ISSUE TITLE
Missing Gnome Menu Entry

### ISSUE THREAD

**Issue by yokall** [Microsoft/vscode#42088]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 3.10.0-514.26.2.el7.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
mojolicious|kra|1.8.0
vscode-duplicate|mrm|1.2.0
vscode-cosmosdb|ms-|0.3.0
azure-account|ms-|0.3.0
vscode-icons|rob|7.19.0
Perl6Snippets|ser|0.0.5
cucumber|ste|0.9.6
gitblame|wad|2.2.0

---

Steps to Reproduce:

1. Open applications menu and check all menus, VS Code is no longer there.  It used to appear in Accessories and Programming

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@yokall do you have the file `/usr/share/applications/code.desktop`, what's the contents? Also how did you install VS Code?

**Comment by yokall** [comment]
Yes I have `/usr/share/applications/code.desktop`

```
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %F
Icon=code
Type=Application
StartupNotify=true
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code --new-window %F
Icon=code
```

I have tried installing from the rpm directly and also the yum repo, both behave the same

**Comment by Tyriar** [comment]
I'm guessing this is related to your environment and/or distro not picking up the desktop file as I haven't seen any other reports.
