### ISSUE TITLE
Not founded files via Quick Panel

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#42098]
Im trying to find some PHP file via Quick Panel (ctr+shift+p).
File is located  in <project>vendor/nette/application/src/Application/UI/   (Multiplier.php class)

From my previous editor (ST3) https://goo.gl/LHtt3c

In VSC https://goo.gl/UPGmTh (therm "Multipiler", nothing found) , more specific therm"Multiplier Nette", still not found, see: https://goo.gl/YM31Xc

Searching via quick panel is limited to deep of folder or some keywords like "/src/" or something like that? 

Thx

**Comment by Kcko** [comment]
I found solution in another issue https://github.com/Microsoft/vscode/issues/41647#issuecomment-358052974

user settings: `search.useIgnoreFiles": false`

**Comment by usernamehw** [comment]
@Kcko, if it's resolved you can close the issue then.

**Comment by Kcko** [comment]
@usernamehw you have right.
