### ISSUE TITLE
Run code actions on save

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42092]
Now that we have added code action kinds we could denote them to run on save. Similar to the new command a new setting could exists, e.g. `editor.onSaveCodeaction: [quickfix.cleanup, etc.]`

**Comment by mjbvz** [comment]
A few potential designs for this feature:

## `editor.onSaveCodeaction` User Setting

Add a user setting that lists code action kinds that should be run on save.

**Pro**
- Easily customizable by user.
- Does not require extensions to adopt any new APIs

**Con**
- The setting is not very discoverable or easy to explain
- What should be the default value?
- What if java want organize imports to be run on save but typescript does not? (I know you can use `"[java]": { "editor.onSaveCodeaction": [...]}`) 

## Add a new `CodeAction.runOnSave` property

Add a `runOnSave` property to the `CodeAction` class. Use this property to determine which code actions to run on save

**Pro**
- Lets extensions fully control which actions should be run on save
- The `runOnSave` property could be controlled by a more explicit setting such as `"typescript.organizeImports.runOnSave": true`

**Con**
- Requires extension adoption
- Could lead to lots of extension specific settings such as, `"typescript.organizeImports.runOnSave": true`


## Other open questions

- How do we handle multiple code actions that should be run on save? These may return conflicting edits

**Comment by jrieken** [comment]
I think I'd prefer option 1. We could help with the discoverability by adding the predefined code action kinds to the json-schema. It's also more similar to the keybindings story we have around code actions.
