### ISSUE TITLE
Cannot find module error reported when using paths in tsconfig.

### ISSUE THREAD

**Issue by Roaders** [Microsoft/vscode#42095]
- VSCode Version: 1.19.2 and 1.18.1
- OS Version: Windows 10 and WIndows 7

Steps to Reproduce:

1. clone this repo: https://github.com/Roaders/vs-code-path-issue
2. look at imports in `app.module.ts` - error reported: `Cannot find module: '@app/app.component'.`
3. build app with `npm run build` to verify that the path specified in `tsconfig.json` does in fact work.

Does this issue occur when all extensions are disabled?: This is a clean install of vs code with no extensions installed

I have seen a few people reporting similar issues to this in angular projects. I do not think that it is an angular issue, it might be an issue with using tsconfig files that extend others.

**Comment by mjbvz** [comment]
Try adding `"baseUrl": "src",` to your compiler options. This fixed the issue for me
