### ISSUE TITLE
Drag and drop outside content

### ISSUE THREAD

**Issue by robsonsobral** [microsoft/vscode#42094]
Hi!

There's a feature important to me that is missing: to drag and drop text from other apps.

- VSCode Version: 1.19.2
- OS Version: MacOS 10.13.2

Steps to Reproduce:

1. Open the browser
2. Select some text
3. Drag and drop the selected text into editor

Expected behavior:

3. Drag it until the cursor reaches the desired position
4. Drop the content

Does this issue occur when all extensions are disabled?: I couldn't run it this way on my mac.

Thank you!

**Comment by robsonsobral** [comment]
It looks like i'm the only one who drags text from browser into Sublime Text editor.

**Comment by sbaeurle** [comment]
Hey, what is the current status of this issue?

I would like to use this in combination with the zotero quick drag&drop feature.

**Comment by robsonsobral** [comment]
It looks like, everybody prefers to use the clipboard area... Sadly, I've no idea on how to fix this issue.

**Comment by stevehjohn** [comment]
This is an issue on Windows too.

**Comment by FlashSheridan** [comment]
It even fails dragging from one VSCode window pane to another.

**Comment by robsonsobral** [comment]
I guess this is an Electron limitation, but I'm not sure.

**Comment by assignUser** [comment]
I would also like to use this in combination with the zotero quick drag&drop feature.

**Comment by metachow** [comment]
It's been 4 years since the feature request was posted. So sad.

**Comment by robsonsobral** [comment]
> This is not electron, this is related with the monaco-editor.

Maybe we can ask for it [here](https://github.com/microsoft/monaco-editor/issues/590) and/or [here](https://github.com/microsoft/monaco-editor/issues/1050).

**Comment by mjbvz** [comment]
This has been enabled for the past few VS Code releases:

![43ae951a-481a-4990-abad-98351a0026e0](https://user-images.githubusercontent.com/12821956/182715561-fc62ece0-1b27-4cba-84ed-b8db2d674de6.gif)
