### ISSUE TITLE
Add an option to choose the shell for integrated terminal

### ISSUE THREAD

**Issue by codec-abc** [Microsoft/vscode#42099]
Hi,

This is a feature request for the integrated-terminal of vscode. Currently, vscode give access to different "terminal emulator" (not sure if it is the correct wording). On my Windows 10 machine, I can choose between `cmd.exe`, `powershell.exe` and `bash.exe`. I can choose the default one thanks to the `Terminal: Select Default Shell` command which set the `terminal.integrated.shell.windows` value in the preference file. 

What I would like is to be able to open a different terminal without changing my default one. It may seems strange at first, but for some project it make more sense for me to use `cmd.exe` and for some other `bash.exe` is a better fit. For that, I would like a new `Open Terminal` command that would open the same dropdown that is used for selecting the default one. Also, an other way to let user add a new custom terminal in the GUI would be a nice addition. It may take the form of another plus button which would bring the dropdown to let choose the user pick a terminal as illustrated in the image below. I am not opinionated about the best way to do this in the GUI though.

![shell-selector2](https://user-images.githubusercontent.com/1208646/35338559-883c2986-011e-11e8-8188-ab4044888b64.png)

**Comment by Tyriar** [comment]
You can do this right now using extensions https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher or by just running the shell as a sub shell (launch cmd terminal, run "powershell"). There are no plans on adding this to core right now, the thinking is to avoid bloat when the majority of users don't need this convenience, those that do can get a relevant extension.

**Comment by codec-abc** [comment]
Seems fair. Thanks for providing alternative ways of doing this and doing the extension too.
