### ISSUE TITLE
Integrated terminal panel becomes garbled

### ISSUE THREAD

**Issue by astamm78** [Microsoft/vscode#42107]
- VSCode Version: 1.19.2
- OS Version: 10.13.2

Steps to Reproduce:

1. Connect to external monitor
2. Open Visual Studio Code on external monitor
3. Open integrated terminal
4. Hide integrated terminal window
5. Disconnect from external monitor
6. Reconnect external monitor
7. Re-open integrated terminal window

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
This is fixed in 1.20
