### ISSUE TITLE
Debug action bar missing

### ISSUE THREAD

**Issue by davidcoleman007** [Microsoft/vscode#42109]
When debugging npm react launch, the action bar will not show, but yet a valid debugging session is active:
![image](https://user-images.githubusercontent.com/41075/35347021-e51383e2-0101-11e8-9a15-ff18242a336a.png)

Launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "attach",
        "name": "Attach by Process ID",
        "processId": "${command:PickProcess}"
      },
    {
      "type": "node",
      "request": "launch",
      "name": "Launch via NPM",
      "runtimeExecutable": "npm",
      "runtimeArgs": [
        "run-script",
        "inspect"
      ],
      "port": 5859,
      "timeout": 60000
    },
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8081/webstore/checkout",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```

rebooting repeatedly has solved in the past.  Recently reboot did nothing.

I do not have any custom setting to disable the debug action bar:

![image](https://user-images.githubusercontent.com/41075/35347143-31f18eac-0102-11e8-983d-c0d35606736a.png)

most times while experiencing this issue I will not see red dots indicating breakpoints in file gutter.  This time I do see them, however I don't see the action bar.

This is a recent development.  I always keep my app updated, and it has started in the last week or so.

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.1
vscode-exports-autocomplete|cap|0.5.4
vscode-typescript-react-redux-snippets|cho|0.3.7
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.4
githistory|don|0.3.5
eslint-disable-snippets|drK|1.1.4
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.0
vscode-npm|fkn|3.3.0
react-component|jer|1.0.1
vscode-redux-devtools|jin|0.0.11
calculator|lix|0.1.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.0.0
indent-rainbow|ode|0.7.2
vscode-subword-navigation|ow|1.1.5
trailing-spaces|sha|0.2.11
react-redux-es6-snippets|sle|0.4.0
react-redux-es6-snippets|tim|2.1.0
highlight-matching-tag|vin|0.4.4
babelrc|wad|1.0.0
better-align|wwm|1.1.6

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by davidcoleman007** [comment]
this seems to happen when debugging is started too soon after reboot/launch of vs code itself.

1. I signed out of windows 
2. signed in.  
3. waited for all windows bg processes to finish for sure
4. launched vs code
5. waited for a few minutes to be sure project had indexed.
6. debugged again.

It worked and action bar was present:
![image](https://user-images.githubusercontent.com/41075/35347752-13248856-0104-11e8-995d-475d1945ad1d.png)

**Comment by isidorn** [comment]
@davidcoleman007 thanks for the report. I do not really need steps on how to not reproduce it, but how to reproduce it.
Can you reproduce using latest vscode insiders https://code.visualstudio.com/insiders/
