### ISSUE TITLE
Wrap individual lines with abbreviation only wraps first line

### ISSUE THREAD

**Issue by BB-000** [Microsoft/vscode#42102]
1. Select some lines
2. 'wrap individual lines with abbreviation'
3. Enter abbreviation 
4. Hit enter
5. Only first line wrapped

<img width="594" alt="screen shot 2018-01-24 at 15 56 05" src="https://user-images.githubusercontent.com/9916373/35342282-9a5e79ba-011f-11e8-9c29-3adce611dbd4.png">
<img width="916" alt="screen shot 2018-01-24 at 15 56 16" src="https://user-images.githubusercontent.com/9916373/35342294-9f0d17a0-011f-11e8-8606-dbf707ef5ae0.png">
<img width="644" alt="screen shot 2018-01-24 at 15 56 31" src="https://user-images.githubusercontent.com/9916373/35342301-a2879c02-011f-11e8-8a90-b44b0c61b16e.png">

**Comment by ramya-rao-a** [comment]
You are using multi cursor to do the selection which translates into multiple selections
The `Wrap Individual Lines ...` works on single selection
