### ISSUE TITLE
Path abbreviation relative to project folders

### ISSUE THREAD

**Issue by siegebell** [microsoft/vscode#42101]
Very long filenames have display issues: #10941, #33068, #20598, #6993. My own problem is that they get clipped in the quick file search (cmd+P). E.g. I cannot tell if foo.ts is under tests/ or src/. Sometimes I cannot even tell which workspace folder it's in. This is even worse when I've loaded a remote folder that has a long hostname.

I have a suggestion on how to abbreviate these paths: skip the chunk of path leading up to the workspace folder name.

For example, if I have loaded folder /a/b/c/d/e/f/g/foo, then /a/b/c/d/e/f/g/foo/tests/foo.c would be abbreviated as .../**foo**/tests/foo.c or **foo**/tests/foo.c.

In general, scheme://hostname/[in-between-path]/project-folder/[path-to-file] would be abbreviated as scheme://hostname/.../**project-folder**/[path-to-file], or **project-folder**/[path-to-file] (at least when the path is local). Bonus points if you render project-folder with emphasis.

**Comment by kcaze** [comment]
It looks like in `getUriLabel()` in [`LabelService:130`](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/label/common/labelService.ts#L130), the URIs are already computed relative to a workspace root when possible.

Is there still a need abbreviate the paths further? If so, one possible approach is to compute the minimal path segments needed to disambiguate each quick open entry (I can give pseudo code for doing this in O(n*m^2) where n = number of entries and m = number of path segments per entry).
