### ISSUE TITLE
Why Visual Studio Code do not show any opened content ?

### ISSUE THREAD

**Issue by vyacheslavv44** [Microsoft/vscode#42100]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Nor .txt files, nor .js files, nor folders. Nothing. It's just a grey background. My PC Win 10, 64 bit. How to fix this ?

**Comment by vyacheslavv44** [comment]
![screenshot002](https://user-images.githubusercontent.com/26522058/35340604-fae4e77a-013c-11e8-8fad-706a0324ba38.jpg)

**Comment by bpasero** [comment]
@vyacheslavv44 does it reproduce if you run "`code --disable-gpu`"?

**Comment by vyacheslavv44** [comment]
Sorry for my ignorance, where I can use such command "code --disable-gpu"?
I just click with my mouse to run editor, - as with any others text editors.

**Comment by bpasero** [comment]
@vyacheslavv44 from the "Command Prompt"

**Comment by vyacheslavv44** [comment]
I will try right now!

**Comment by vyacheslavv44** [comment]
Wow ! You are genius ! IT'S WORKING )) 
Very Big Thanks !

**Comment by vyacheslavv44** [comment]
![screenshot003](https://user-images.githubusercontent.com/26522058/35345799-fef8fb32-0149-11e8-8608-9a3db19bc37b.jpg)

Look ))

**Comment by bpasero** [comment]
@vyacheslavv44 great

**Comment by bpasero** [comment]
Marking as duplicate of https://github.com/Microsoft/vscode/issues/42100

**Comment by jens1o** [comment]
@bpasero You're marking the same issue as a duplicate?

**Comment by bpasero** [comment]
Ah I meant to write: https://github.com/Microsoft/vscode/issues/37707
