### ISSUE TITLE
Vulnerability in 1.19.x

### ISSUE THREAD

**Issue by bluec0re** [Microsoft/vscode#42116]
- VSCode Version: 1.19, 1.19.1, 1.19.2
- OS Version: Linux, Mac, Windows

I've found a vulnerability in version 1.19 and above which allows attackers to compromise systems where vscode is running.

Could a maintainer contact me at i*\*o@b*******e.** for further details?

**Comment by ChiChou** [comment]
Emmmm, I think I found this, too. Is it the port 9333?

**Comment by egamma** [comment]
@ChiChou the fix for the above mentioned issue went into 1.19.3. Can you contact me at egamma at microsoft dot com and provide more details.

**Comment by ChiChou** [comment]
Hi @egamma , have you received the mail?

**Comment by egamma** [comment]
@ChiChou yes, I´ve received the mail and replied to it on the same day.

**Comment by ChiChou** [comment]
Sorry, Gmail marked it as junk.
