### ISSUE TITLE
"Continue to End" function for breakpoint stepping

### ISSUE THREAD

**Issue by johnbillion** [microsoft/vscode#42112]
I'd love to see an extra button in the debug toolbar which continues script execution until the script completes, ignoring further breakpoints. This would be akin to deactivating all breakpoints, continuing, and then reactivating all breakpoints.

Regularly while debugging, I'll inspect the code I'm interested in and then need to complete the execution of the script, but without pausing on any further breakpoints for the remainder of the request.

Google Chrome has a similar feature whereby you long-press the `Resume` button when paused on a breakpoint and the script will resume and ignore any further breakpoints for 500ms.

<img width="200" alt="" src="https://user-images.githubusercontent.com/208434/35348672-9f6e11de-0130-11e8-9f4e-22a40ac2797d.png">

**Comment by isidorn** [comment]
PRs that add this feature are welcome
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActionsWidget.ts#L48

A simplier way with no UX to tackle this is to add a new command palette action "Continue and Ignore Breakpoints".
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActions.ts#L328

**Comment by svitlana-galianova** [comment]
Hey, I would like to help out here

**Comment by isidorn** [comment]
@svitlana-galianova great, however before we start on any PRs we have to figure out how this would be implemented.
First of let's not add this to the debug toolbar (limited ux space). 
Let's only add it to the command palette, so people can assign keybindings to it.
For that we would need a new debug command here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugCommands.ts#L219
You would need to register it in the command palette.
Also do not give any default keybindings.
The command would deactivate breakpoints, continue, after 500ms activate breakpoints

**Comment by isidorn** [comment]
Since extensions can contribute this command to the debug toolbar I am closing this as extension-candidate. If somebody wants to write an extensions that adds this let me know and I can provide pointers
