### ISSUE TITLE
Duplicate identifier error after moving a typescript file

### ISSUE THREAD

**Issue by voxking** [Microsoft/vscode#4211]
- VSCode Version: 0.10.10
- OS Version: Windows 10

Typescript says things are duplicate when i move a file around.
My guess is that the location of the file is not updated in the typescript service properly because when i restart VSCode it fixes itself but still its annoying to have to restart the editor.

Steps to Reproduce:

1. get a large typescript code base like react.d.ts or something similar
2. move it
3. watch it happen

**Comment by voxking** [comment]
![screen](https://cloud.githubusercontent.com/assets/15142474/13762990/c38b848e-ea3a-11e5-88c9-24f75903bdc1.png)

**Comment by dbaeumer** [comment]
Moving to TS. 

What we do in this case is we send a close request of the file in its old location and then an open at the new location. There is now API to signal a move right now. If there is something VSCode can do different to solve the problem, please move back.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7516

**Comment by voxking** [comment]
Sorry thought it was just vscode issue, thanks for your support :bow:
