### ISSUE TITLE
textDocument/formatting fails to work for multi-root folders using the language server protocol

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#42119]
Any OS and VS Code version.

1. Open a multi-root workspace.
2. Install an extension that uses the language server protocol and supports textDocument/formatting, such as cpptools (https://github.com/Microsoft/vscode-cpptools ).
3. Format Document on a file in the 2nd workspace folder (files in the 1st workspace folder work correctly).

Bug: Formatting fails. Our language server is returning the correct data, but it gets ignored by VS Code and the document is never updated with the edits from the formatting.

This is https://github.com/Microsoft/vscode-cpptools/issues/1391 .

An example of input/output is:

`************************************************************************************************************************
{
    "jsonrpc": "2.0",
    "id": 3,
    "method": "textDocument/formatting",
    "params": {
        "textDocument": {
            "uri": "file:///f%3A/New%20folder%20%288%29/New%20folder/test14.cpp"
        },
        "options": {
            "tabSize": 4,
            "insertSpaces": false
        }
    }
}
************************************************************************************************************************
Content-Length:375

{
    "jsonrpc": "2.0",
    "id": 3,
    "result": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 43
                },
                "end": {
                    "line": 1,
                    "character": 0
                }
            },
            "newText": " + 0;\r\n"
        }
    ]
}`

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-languageserver-node#305
