### ISSUE TITLE
Image is too large to display in editor - please add configuration option for larger limit

### ISSUE THREAD

**Issue by alecperkey** [Microsoft/vscode#42122]
- VSCode Version: 1.20.0-insider
- OS Version: Win 10 Home 10.0.16299 Build 16299

Steps to Reproduce:

1. Open image/file larger than 1mb, no preview. I don't want to open in an external program.
2. Cry

Does this issue occur when all extensions are disabled?: Yes

Related links: 

RL.1 - hard coded limit in VS Code 
https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/resourceviewer/resourceViewer.ts#L158

RL.2 - testing shows this limit is unnecessary unless you're on a stone age pc
https://bugs.chromium.org/p/chromium/issues/detail?id=805655

RL.3 - full code which should use accept a user preference if available, or at least raise the limit in hard code to something like 32mb
https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/resourceviewer/resourceViewer.ts#L86-L158

6mb gifv of my test (RL.2): https://i.imgur.com/ZughJwH.gifv
[loading-10000-1mb-images-no-problem-gifv.zip](https://github.com/Microsoft/vscode/files/1661836/loading-10000-1mb-images-no-problem-gifv.zip)

my pc specs during test (RL.2): https://i.imgur.com/ghtNjgT.png
![my-pc-specs](https://user-images.githubusercontent.com/1241041/35359194-fd3cd8c2-010d-11e8-986c-b8bbe269f85b.png)

**Comment by bpasero** [comment]
As designed because of https://bugs.chromium.org/p/chromium/issues/detail?id=805655
