### ISSUE TITLE
Format on tab size 4 doesn't work on Mac

### ISSUE THREAD

**Issue by zhaoyi0113** [Microsoft/vscode#42127]
I am using vscode for javascript develop and have a problem on format. Earlier I am using tabsize 2 which works perfectly. But it doesn't work when I change it to tabsize: 4. Below is my workspace settings. The version of vscode I am using is `1.19.2 `. 

```
{
	"prettier.tabWidth": 4,
  "editor.tabSize": 4,
"editor.formatOnSave": false,
"editor.detectIndentation": false,
}
```

After above settings, when I click `Format Document`, it is still using 2 as the tab size.

**Comment by mjbvz** [comment]
Does this still happen if you disable all extensions and restart VS Code?

**Comment by zhaoyi0113** [comment]
I have tried restart VS code and it still happens. How can I disable all extensions? I installed some plugins and is there a way to disable all of them?

**Comment by mjbvz** [comment]
https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension for individual extensions

To disable all extensions, start code with the `--disable-extensions` command line flag or run the `Disable all extensions` command and restart

**Comment by zhaoyi0113** [comment]
Ok, thanks. Disable all extensions works fine. How can I know which extension impact this behavior?

**Comment by mjbvz** [comment]
Not reliably. It's probably one of your formatter extensions however. You can disable those one by one until finding the culprit

**Comment by seajean** [comment]
I have the same issue, and I have disabled all extension, and I wonder why the format document context menu  still work after I disable all extensions. my VS version is 1.21.0-insider (1.21.0-insider)
