### ISSUE TITLE
No option for excluding a folder from ctrl-p and search results, but still shown on left-nav.

### ISSUE THREAD

**Issue by dzearing** [Microsoft/vscode#4212]
Steps to Reproduce:
Add "node_modules" and "lib" to files.exclude

Expected:
shown in leftnav but excluded from ctrl-p and search, but still in the left nav

Resulted:
excluded in ctrl-p and search, but also the left nav

There is files.exclude and search.exclude, but no filelist.exclude or something... If search.exclude would exclude the file from showing up in ctrl-p, that would be another fine alternative.

**Comment by bpasero** [comment]
@dzearing can you attach a screenshot where it is still showing in Cmd+P?

**Comment by dzearing** [comment]
Oddly I can't seem to repro it now with search.exclude containing the lib folder. I see the lib folder in left nav, but ctrl-p is not resolving to files from within it. I swear this wasn't working, but maybe it was patched in the recent update. I will close for now and reopen if I can pinpoint the repro.
