### ISSUE TITLE
copy search results

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/vscode#42120]
- VSCode Version: 1.19.2 x64
- OS Version: win 10

Steps to Reproduce:

1. Search for something
2. Try and copy the results of that search to an email...

Would be nice if there were a way to copy all the output of the search window...

**Comment by ryanburr** [comment]
Can this be reopened? The scenario of copying the output of search is still valid as #8594 only applies to copying the path of a single result

**Comment by roblourens** [comment]
I would handle copying individual results and all results with that issue.

**Comment by roblourens** [comment]
Actually it was this issue. Try it out when we start updating Insiders again after the stable release this week.
