### ISSUE TITLE
Markdown formatting for JSDocs arguments is broken

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [Microsoft/vscode#42125]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (673355d8f42c0b676442a454fcce940a4e270aff, 2018-01-22T05:14:14.888Z)</li>
	<li>OS Version: Windows_NT x64 10.0.17074</li>
	<li><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
yandex-translate|air|1.0.5
Bookmarks|ale|0.18.0
sqf|Arm|1.0.4
unique-lines|bib|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.12.1
vscode-eslint|dba|1.4.4
xml|Dot|1.9.2
gitlens|eam|7.5.6
EditorConfig|Edi|0.12.0
tslint|eg2|1.0.24
vsc-material-theme|Equ|1.3.0
vsc-figlet|fer|0.0.8
file-icons|fil|1.0.7
vscode-npm|fkn|3.3.0
vscode-nginx-conf-hint|han|0.0.4
npm-dependency-links|her|1.0.0
minify|Hoo|0.3.0
rest-client|hum|0.16.2
discord-vscode|icr|2.1.0
vscode-insertdatestring|jsy|2.2.0
vscode-icon-theme|jtl|1.6.1
indentation-level-movement|kai|1.1.1
StarboundJson|Kyl|0.1.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
autoconf|mae|0.0.2
vscode-todo-parser|min|1.9.1
HTMLHint|mka|0.4.0
python|ms-|0.9.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
typescript-javascript-grammar|ms-|0.0.26
node-modules-resolve|nau|1.0.2
indent-rainbow|ode|0.7.2
ejs-language-support|Qas|0.0.1
vscode-icons|rob|7.19.0
MDTools|sea|1.0.1
code-settings-sync|Sha|2.8.7
vscode-nginx|sha|0.5.0
sqflint|ska|0.8.6
vscode-wakatime|Wak|1.1.22
html-css-class-completion|Zig|1.16.1

(2 theme extensions excluded)

</details></li>
</ul>

---

Steps to Reproduce:

1. Write an argument description in JSDocs with the markdown (bold in my case)
  ```ts
/**
 * **Generates string with greeting**
 * @param {string} username **Username** for the greeting.
 */
function greeting(username: string) {
    return `Hello, ${username}!`;
}
```
2. Hover over an argument name OR type the code to trigger the description tooltip

| ℹ️  | **To note!** |
|:---:|---|
| **1**  | The behavior below occurs only if the description starts with bold formatting. |
| **2** | This only occurs with the asterisk (`*`) bold formatting. |

Excepted Result: **Username** for the greeting.

Actual Result: *Username*\* for the greeting.

<details><summary>Example from my code (screenshot)</summary>
<img src="https://user-images.githubusercontent.com/10401817/35362755-3d7d7938-0199-11e8-82ae-583d104da148.png" />

</details>

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21402
