### ISSUE TITLE
Can not build TypeScript in Visual Studio Code

### ISSUE THREAD

**Issue by imben1109** [Microsoft/vscode#42137]
- VSCode Version: 1.18.1
- OS Version: Window 7

Steps to Reproduce:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ]
        }
    ]
}
```

**Command**
ctrl + shift + b 
tsc: build

It would trigger 
tsc -p "xxxxx\xxxx\xxx\${Current Project Folder}\tsconfig.json"

Then it throw an exception 
it cannot parse JSON as
xxxxx\xxxx\xxx\${Current Project Folder}\tsconfig.json\tsconfig.json

**Comment by mjbvz** [comment]
I see you are on the last release, 1.18. Does this still happen in the [current insiders builds](https://code.visualstudio.com/insiders/)?
