### ISSUE TITLE
Can You Please add (ctl+ , ctl-) short cut futures simile we use in visual studio  

### ISSUE THREAD

**Issue by harshilhbm** [Microsoft/vscode#42138]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please provide more info

[This guide](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests) has suggestions about how to file an actionable feature request
