### ISSUE TITLE
Flatpak package do not support Fcitx changes input method.

### ISSUE THREAD

**Issue by Honghe** [Microsoft/vscode#42133]
- VSCode Version: ➜  
```
~ flatpak run com.visualstudio.code --version
1.19.2
490ef761b76b3f3b3832eff7a588aac891e5fe80
x64
```
- OS Version: Ubuntu 16.04.3 x65
- Fcitx Version:  fcitx version: 4.2.9.1

Steps to Reproduce:
1. Start vscode. The issue remain after restart vscode  and Fcitx.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
We do not have a flatpak package, this must be a community package. Also you should be careful about installing non-MS code like this as they could do anything to it before bundling.
