### ISSUE TITLE
Feature Request: Ability to specify the working directory for a task

### ISSUE THREAD

**Issue by Connorcpu** [Microsoft/vscode#4213]
It would be nice if I could specify the working directory for a task without needing to create a separate script or anything. For example, on my current project I need to run the build system from one of my project's subfolders, and it would be nice if I could just invoke it without a script that changes directories first.

**Comment by dbaeumer** [comment]
There is an options property which takes a cwd property to specific the current working directory of the command executed.
```json
		"command": "...",
		"options": {
			"cwd": "..."
		}
```
