### ISSUE TITLE
Can't update the presentationHint of a Source during a debug session

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42139]
- Start debugging with the node2 or chrome debugger
- Right click on a stack frame, "toggle skipping this file"
- The debug adapter will now send the opposite presentation hint for the stackFrame.source (if it was not skipped, it will now send "deemphasize". If it was skipped, it will stop sending "deemphasize")
- But the stack frame view is not updated - it still appears with the original presentationHint

Looking at the code, it seems like the Source is cached by id, and the presentationHint is never updated, even if the debug adapter sends a Source with a different presentationHint. This must have changed at some point.

**Comment by isidorn** [comment]
@roblourens please let me know if my fix solves this issue.
Now I simply override the raw source data whenever I get a new raw source from the adapter.
Not sure if this is the best strategy. Feedback welcome

**Comment by roblourens** [comment]
That should work for my adapter, and I think it makes sense. I don't know if anyone else is depending on vscode caching some Source properties. But I guess they shouldn't be.

**Comment by weinand** [comment]
After toggling a stackframe for the first time it correctly updates to a dimmed presentation.
But toggling the stackframe again doesn't result in the original presentation.

**Comment by isidorn** [comment]
Strange, because I take the priority of the incoming source object.

**Comment by isidorn** [comment]
@weinand good catch. This was not working because I was merging whatever was coming in with what I already had. And when you toggle back the source to be shown it does not have any `presentationHint` since it is back to normal. However with my merge stragety the old `presentationHint` would not get updaed. Now I always override the presentationHint with whatever I get from the adapter

**Comment by bpasero** [comment]
I assume this is now correct after invoking the action:

![image](https://user-images.githubusercontent.com/900690/37041417-7ac0d4f6-215c-11e8-8e90-e2ce0282c0bc.png)

**Comment by isidorn** [comment]
Yeah, but after you invoke it again module.js should no longer be dimmed

**Comment by bpasero** [comment]
@isidorn yeah that is what I saw
