### ISSUE TITLE
Spamming me nonstop, way to disable?

### ISSUE THREAD

**Issue by dant00ine** [Microsoft/vscode#42132]
IDE is working fine, don't really care about the error. Any way to disable it? Not sure what the repro steps are, but I have a sensitive state open and I'd rather not restart the IDE at the moment... grumble grumble

`The TypeScript language service died 5 times after it got started. The service will not be restarted.`

Well, if it won't be restarted, could you then not spam me 5-6 times every 20 seconds...
Got work to do here... grumble grumble

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
django-html|bib|1.2.0
tslint|eg2|1.0.24
php-intellisense|fel|2.2.5
smarty|imp|0.2.0
mssql|ms-|1.3.0
python|ms-|0.9.1
sass-indented|rob|1.4.6
react-beautify|tai|0.3.0
swig-tpl|zha|0.0.6

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by dant00ine** [comment]
No error messages after restarting the IDE.. sorry for trouble
