### ISSUE TITLE
Regression: Text mate snippets do not work anymore

### ISSUE THREAD

**Issue by g-arjones** [Microsoft/vscode#42136]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.6
Ruby|reb|0.15.0

---

Steps to Reproduce:

1. Use the following CompletionItemProvider:

```ts
languages.registerCompletionItemProvider('csharp', {
        provideCompletionItems(doc, pos) {
            const range = doc.getWordRangeAtPosition(pos);
            const word = doc.getText(range);
            if (word === 'override') {

                const item = new vscode.CompletionItem('M1()', vscode.CompletionItemKind.Method);
                item.textEdit = vscode.TextEdit.replace(range, 'protected override void M1()\n{\n\tthrow new NotImplementedException();{{}}\n}')
                item.additionalTextEdits = [vscode.TextEdit.insert(new vscode.Position(0, 0), 'using System;\n')];
                item.filterText = word;

                return [item];
            }
        }
    });
```
2. Type 'override'

Reproduces without extensions: Yes/No

I expected the behavior shown by @jrieken in #6874, but rather than have the cursor positioned inside the method, I get the cursor at the end of the snippet (and {{}} is added). I tried $0 but that didn't work also..

**Comment by jrieken** [comment]
This is not a regression. What you need to do is to use the correct Textmate syntax *and* use the `SnippetString` type.
