### ISSUE TITLE
Double Split Editor - vertical + horizontal

### ISSUE THREAD

**Issue by pallapo** [Microsoft/vscode#42147]
It will be nice to split editor in a vertical AND horizontal manner.
I mean, in 4k screens there is enough space to host 3 horizontal editor AND 2 or 3 vertical editor opened at the same time.
Atom already does it. (see blow)

![atom_splitted_editor](https://user-images.githubusercontent.com/17046997/35384131-a1c0a25a-01c4-11e8-8d83-f86d5a3cb04d.png)

**Comment by usernamehw** [comment]
Have you tried to search first for a similar issue?

https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
