### ISSUE TITLE
Allow 100% panel width and height

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#42149]
VSCode Version:VS code Insiders (1.20.0)
OS Version: Windows &

Steps to Reproduce:

1. Open VS code
2.Open Integrated terminal window
3. expand Explorer view
result: the Integrated terminal view shrinks to allow the explorer view to take the full height. 
expected: the explorer view adjusts its height as (window_height - Integrated terminal Height). allowing the integrated terminal to have a 100% window width.

Does this issue occur when all extensions are disabled?: Yes

**Comment by scottmas** [comment]
This should probably be an option. But it might be worth doing a poll to see if there's a strong default preference. Intellij products make the terminal have 100% width fwiw.

**Comment by Antony-Jones** [comment]
Alternatively, could we just pop the terminal out into a tab?

**Comment by zhihaoy** [comment]
I would like to be given an option to Toggle the editor region.  VS allows it.

**Comment by isidorn** [comment]
fyi @sbatten

**Comment by nnja** [comment]
+1 to this issue.

It would also be nice if the width for "move panel right" was customizable. If I have a terminal open and no code windows, using "move panel right" will still show a default vs code new editor pane, even if I already closed it.

**Comment by ztmdsbt** [comment]
The terminal in VsCode is the best command line shell I've used in windows now. I use it as the default command line shell instead of CMD/Git Bash/ConEmu.

**Comment by hektormisplon** [comment]
I also would love an option to use the terminal in full screen. Not necessarily over the explorer view but certainly 100% width & height when explorer view is hidden.

It would be cool just to have a workspace setting for this imo.

**Comment by SeanPlusPlus** [comment]
+1 to this issue

**Comment by sbatten** [comment]
It isn't everything that's been asked for here, but maximizing the panel will now take over the editor space entirely in tomorrow's insiders as opposed to leaving that little gap.

**Comment by codeforgeek** [comment]
+1 to this issue. I would love to use a full-width terminal in vs code.

**Comment by sanket-bhalerao** [comment]
it will also be good to have the terminal pane like this

![explorer](https://user-images.githubusercontent.com/9264813/66540459-80f21700-eb49-11e9-8132-3be04250c9fd.png)

**Comment by edimitchel** [comment]
> 
> 
> it will also be good to have the terminal pane like this
> 
> ![explorer](https://user-images.githubusercontent.com/9264813/66540459-80f21700-eb49-11e9-8132-3be04250c9fd.png)

Or like the one in my issue : https://github.com/Microsoft/vscode/issues/61481#issue-372487152

![image](https://user-images.githubusercontent.com/2922851/66652269-a0666e00-ec35-11e9-94df-d330d44ea5cc.png)

**Comment by markhulia** [comment]
+1 to this issue. It would be a great feature

**Comment by mfeyx** [comment]
+1 for this... would be nice to have this option. :)

**Comment by GianCastle** [comment]
+1

**Comment by agalbenus** [comment]
+1

**Comment by lukenofurther** [comment]
+1

**Comment by chazragg** [comment]
+1

**Comment by RazgrizHsu** [comment]
+1 for this, if cloud be optional

**Comment by tchkreddy** [comment]
+1

**Comment by tumf87** [comment]
this would be awesome, especially given the option of splitting terminals side by side.

**Comment by dwoodwardgb** [comment]
+1

**Comment by KevinHewson** [comment]
+1

**Comment by taohexxx** [comment]
+1

**Comment by ElPapi42** [comment]
+1

**Comment by jspiew** [comment]
+1

**Comment by dalemane** [comment]
Still looking forward to having this feature. We use a lot the integrated terminal!

**Comment by ceo** [comment]
+1 , anyone knows how to do this ?

**Comment by ceo** [comment]
> > it will also be good to have the terminal pane like this
> > ![explorer](https://user-images.githubusercontent.com/9264813/66540459-80f21700-eb49-11e9-8132-3be04250c9fd.png)
> 
> Or like the one in my issue when side bar is to right : [#61481 (comment)](https://github.com/microsoft/vscode/issues/61481#issue-372487152)
> 
> ![image](https://user-images.githubusercontent.com/2922851/66652269-a0666e00-ec35-11e9-94df-d330d44ea5cc.png)

was this photoshop ?? or is it possible to edit manually

**Comment by sanket-bhalerao** [comment]
> 
> 
> > > it will also be good to have the terminal pane like this
> > > ![explorer](https://user-images.githubusercontent.com/9264813/66540459-80f21700-eb49-11e9-8132-3be04250c9fd.png)
> > 
> > 
> > Or like the one in my issue when side bar is to right : [#61481 (comment)](https://github.com/microsoft/vscode/issues/61481#issue-372487152)
> > ![image](https://user-images.githubusercontent.com/2922851/66652269-a0666e00-ec35-11e9-94df-d330d44ea5cc.png)
> 
> was this photoshop ?? or is it possible to edit manually

@ceo if you are asking how to do this in vscode -> its not currently possible. Once this feature request goes through it should be possible.
if you are just asking about the images in the feature request, the dark themed one i have created using MSPaint.

**Comment by vlkv** [comment]
+1 for 100% wide bottom panel. This will be MUCH more convenient for terminal usage.

**Comment by bulliana** [comment]
+1 for wide terminal panel!

**Comment by AlexJoeb** [comment]
+1

**Comment by ricristian** [comment]
+1

**Comment by kanlukasz** [comment]
Please stop spamming this issue with "+1" posts
It doesn't add anything new.

If you want to vote and support this issue, just set thumbs up on the issue post owner (👍) - this is how the Microsoft team considers the popularity of the FR

**Comment by tchkreddy** [comment]
A compettitive example from IntelliJ
![image](https://user-images.githubusercontent.com/7251057/96329792-bb9c6280-106d-11eb-9a81-157f71dfa73c.png)

**Comment by snwfdhmp** [comment]
+1 for this feature !

**Comment by seasofttongkhanh** [comment]
+1

**Comment by maddinek** [comment]
+1 just to keep it alive since its open for a while :D

**Comment by snwfdhmp** [comment]
FYI currently I chose to hide the file explorer when I want the terminal to be full-width.

**Comment by rmlmedia** [comment]
+1

**Comment by matheusqueirozzabin** [comment]
+1

**Comment by tylerleecgi** [comment]
Still not done? IntelliJ it is then.

**Comment by sanket-bhalerao** [comment]
Hi All,

I am glad that all of you find this feature request useful and upvoted and "+1"d for this feature.
I am positive that everyone who has added a "+1" comment has also upvoted the original feature request as well. However, If for some reason you missed it please consider upvoting the original feature request.

**Comment by necrifede** [comment]
+1

**Comment by PhoeniXAbhisheK** [comment]
+1

**Comment by panteo** [comment]
+1

**Comment by AdaoNatalino** [comment]
+1

**Comment by Fibonacci-Solucoes-Ageis** [comment]
+1

**Comment by kernelbare** [comment]
+1

**Comment by jehillert** [comment]
+1

**Comment by jehillert** [comment]
I have an Eizo FlexScan EV2730Q, which is a 1920x1920 square monitor.  I use it as my daily driver, with VS Code filling the whole space.  After using the requested feature on intelliJ, I can say it is indispensable for big square monitors.  I find myself wishing VS Code had it 3-4 times a day.  Granted, my resolution is super rare, but for the few people who use them it would make a huge difference.  I only need about 2/3 the height of the sidebar I have now, but I really really could use the full width to open two side-by-side terminals.

**Comment by jehillert** [comment]
![square_monitor](https://user-images.githubusercontent.com/25601296/119334367-a9605380-bc50-11eb-8514-232d806a4954.png)

**Comment by sarthak9793** [comment]
Can anyone please tell me how to change the terminal panel to it's default size

**Comment by robocrax** [comment]
+1

This is useful for a vertical monitor setup.

All my files are displayed within the given height and don't even touch the start of my terminal, I would definitely prefer the full width terminal and the sidebar shrinks it's height.

I'm currently using [Auto Hide](https://marketplace.visualstudio.com/items?itemName=sirmspencer.vscode-autohide) extension but it only works when I click on the editor and not the terminal but atleast it does something. Microsoft please add a full-width option as a toggle.

**Comment by TigerTim** [comment]
+1 looking forward for this feature

**Comment by phasjim** [comment]
+1! Would love this feature ❤️

**Comment by Loggy** [comment]
+1

**Comment by BlaineEXE** [comment]
+1

**Comment by AaronBeaudoin** [comment]
This would be fantastic! For example, `docker ps` output tends to really wide, and on a smaller laptop the output wraps around if the terminal isn't taking up the entire width of my screen. Without this feature my only option is to run a terminal window separately. It's be really nice if I could just have a full-width terminal right inside of VS Code.

**Comment by ibukanov** [comment]
On small laptops this will allow to have the editor on the left occupying the full screen (or have two editor views on top of each other) and the sidebar and the panel on the right on top of each other for best use of screen estate.

**Comment by robocrax** [comment]
Something like the new Microsoft Edge vertical tabs where there's a pin button. If settings sync then this might be a setting that you don't want to sync.

You could have a preference of unpinning left menu on 1 screen and not on your other synced devices.

**Comment by sbatten** [comment]
To Verify:
Try out the 4 new commands `Set Panel Alignment To...`
Also try out the menu entries under `View > Appearance > Align Panel`

**Comment by jhillert-dmg** [comment]
Can we have a screenshot?  I am half awake and not sure if this GitHub notification is for real or just my subconscious mind taunting me with suggestions of the things I so desperately want but now fear middle-age has put out of reach, like an end to my student loans or a healthy body mass index...

**Comment by imekachi** [comment]
On 1.64.0-insider

![image](https://user-images.githubusercontent.com/5445243/151009293-1f707d95-f2ca-4218-8515-059edd56465a.png)

![image](https://user-images.githubusercontent.com/5445243/151010123-45df7cf8-cef8-4000-bff7-5bceccc6dc57.png)

![image](https://user-images.githubusercontent.com/5445243/151010380-8452e22d-6400-4146-8bbf-0749703c89d8.png)

![image](https://user-images.githubusercontent.com/5445243/151010364-dcd30089-9e8e-44e3-8726-140373821760.png)


Wow, thank you 🎉

**Comment by jhillert-dmg** [comment]
Oh boy!!! So happy. Thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you!!!

**Comment by ckhall** [comment]
this is great!  is there a timeframe on when this becomes GA? next release?

**Comment by gjsjohnmurray** [comment]
> this is great! is there a timeframe on when this becomes GA? next release?

Yes, in 1.64 which looks on track to publish on Thursday.

**Comment by ckhall** [comment]
> > this is great! is there a timeframe on when this becomes GA? next release?
> 
> Yes, in 1.64 which looks on track to publish on Thursday.

Thank you!

**Comment by vlkv** [comment]
Thank you very much!
