### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by addula** [Microsoft/vscode#42143]
Cannot navigate to definition or declaration in a requirejs project.

**Comment by mjbvz** [comment]
Please provide some example code or small example project

**Comment by RaidoS** [comment]
In my case (Ubuntu 14), for **Peek difition** should using `Ctrl+Shift+F10` instead `Crtl+Shift+F12` as it written at [docs](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_go-to-definition-peek-definition) .
**Go to defition** (`F10`) working fine

**Comment by tungptseven** [comment]
I'm working with Win10 and our Angular Project has the same problem. My team tried any possible way (`f12`, `right click > go to definition`, ...) but nothing happened

**Comment by addula** [comment]
@mjbvz Following is the example code. Consider there are two files.
File1.js looks like below
`define(['angular'], function(angular) {
//some angular module creation and adding controllers/services goes here
return File1;
});`
File2.js
`define(['angular', 'File1'], function(angular, File1) {
//accessing File1 methods is working fine but clicking on those methods is not taking to File1 (definition) this is working fine in WebStorm and Sublime
//some angular module creation and adding controllers/services goes here
});`

**Comment by addula** [comment]
@mjbvz Simple terms, Require+Angular application opened in VSCode is not supporting Go to definition.

**Comment by mjbvz** [comment]
We don't support intellisense for AMD style modules (`define([...], function(...) { ...}`)

This is tracked by https://github.com/Microsoft/TypeScript/issues/6942. If this is new code I recommend using `import` and `export` instead.
