### ISSUE TITLE
rust-lang syntax highlight 

### ISSUE THREAD

**Issue by NateLing** [Microsoft/vscode#42145]
- VSCode Version: Version 1.20.0-insider (1.20.0-insider)
- OS Version:macos 10.13.3

1. rust lambada has no highlight, like this:
![image](https://user-images.githubusercontent.com/9606668/35383161-73ac5b2e-01fc-11e8-94b9-d91e6459a3b2.png)
2. struct type has no highlight, like this:
![image](https://user-images.githubusercontent.com/9606668/35383268-bc2f5c98-01fc-11e8-8c52-f9d0ee19e4a7.png)
3.reference has no highlight, like this:
![image](https://user-images.githubusercontent.com/9606668/35383305-d94bc4f6-01fc-11e8-8a7b-a50d63802695.png)
4.Generics struct has no highlight, like this:
![image](https://user-images.githubusercontent.com/9606668/35383703-f8ccdcec-01fd-11e8-98de-238c2b389243.png)
5.Mutable data and invariant data should have different color.

**Comment by mjbvz** [comment]
Our rust grammar comes from this repo: https://github.com/zargony/atom-language-rust

Please file these issues against them
