### ISSUE TITLE
Using regular expression with trailing \n to find text is very slow in CRLF files

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode#42142]
- VSCode Version: Version: 1.19.2
- OS Version: Windows 7 64-bit

I don’t think #41503 has been properly fixed, so I open a new issue for it.

On Windows platform, search text using a regular expression with trailing `\n` (such as `.\n`) is very slow when there is a lot of matching texts.

Originally, searching for `\n` is also very slow, but it seems to be fixed by 73d60bd, but other search terms with trailing `\n` is still very slow.

**Comment by alexandrudima** [comment]
@EFanZh Thanks for insisting. I can reproduce, but only when the file uses `\r\n` as an EOL terminator (not when the file uses `\n`).

**Comment by alexandrudima** [comment]
To reproduce:
* create a file with CRLF line endings
* have >10k lines
* search for `.\n` in regex mode
