### ISSUE TITLE
Option to Disable Automatic Expand of Explorer View to Show Current File Being Edited

### ISSUE THREAD

**Issue by 0reo27** [Microsoft/vscode#42146]
**Feature Request**

**Summary**

This is easiest to reproduce by doing the following steps:

1. Have 2 files in separate directories open in the editor.
2. Collapse Folders in Explorer - `workbench.files.action.collapseExplorerFolders`
3. Close one file.
4. Explorer expands to show the next file which is now being edited.

**Example:**

![example](https://user-images.githubusercontent.com/24741350/35383734-0dbfa594-01fe-11e8-99bf-bc984cc297b9.gif)

**Recommendations**

1. Add an option to disable this behavior.

P.S. One can access the file in the Side Bar by right clicking on the editor title and selecting "Reveal in Side Bar".

**Comment by isidorn** [comment]
`"explorer.autoReveal": false`

**Comment by 0reo27** [comment]
Well, that's embarrassing. I couldn't find the setting myself and after some time searching, I honestly thought it didn't exist. Thanks for the quick response and sorry for the unnecessary issue. Cheers!
