### ISSUE TITLE
Add a setting making `Delete Permanently` the default

### ISSUE THREAD

**Issue by the-kenny** [Microsoft/vscode#42156]
Every time I want to delete a file I get the message that vscode failed to move it to the trash folder. There should be a setting to make `delete permanently` the default as there are many situations where a system might not have any trash trash folder.

I'm on Linux without any trash, but this applies to Windows 10 as well (see linked issues).

This was requested at least twice before, but was closed. See #34534 and #37900. Note that I don't consider this a feature request but a bug as it makes the delete feature pretty annoying on some setups.
.

**Comment by bpasero** [comment]
@the-kenny you can hold the `Shift` key to bypass the trash. You know that?

**Comment by Naramsim** [comment]
It would be nice to add this information as a one time tip when somebody deletes something

**Comment by bpasero** [comment]
@Naramsim I would think this is pretty much established for quite a while now: https://support.microsoft.com/en-us/help/171051/how-to-bypass-the-recycle-bin-when-deleting-files

**Comment by the-kenny** [comment]
I wasn't aware of this at all. All I found was the old issues I referenced earlier.

Note that the `Shift-DEL` behavior isn't native to Linux (nor to macOS if I remember correctly) and I still think an option to make it the default would be appropriate (as it should be possible to tailor an editor to the needs of the user, not the other way around)

**Comment by bpasero** [comment]
@the-kenny how does your requested feature work on Linux then?

**Comment by the-kenny** [comment]
My request is about an option `files.confirmDelete: boolean` or similar which controls whether files are deleted permanently or moved to trash. Basically the `Shift`-key as a setting :)

**Comment by bpasero** [comment]
Not a big fan of the setting, this is an issue with Electron not giving me any API to find out if the trash is supported or not...

**Comment by bpasero** [comment]
@the-kenny Linux behaves exactly like Windows for me using Shift-delete:

![image](https://user-images.githubusercontent.com/900690/35401521-0f8b872a-01fa-11e8-9f41-10354533b101.png)

**Comment by the-kenny** [comment]
@bpasero Clarifying: I'm asking for a setting to make delete-permanently the default. Nothing more.

Other than that; why are you against such a setting?

**Comment by bpasero** [comment]
@the-kenny a setting is never a good solution for a bug because it will still hit a lot of people. As I said earlier, I want API from Electron telling me if "move to trash" is supported for a given file path and then show the correct info to the user on a case by case basis.

Your setting will just always make the delete permanently, but this is not a fix for those people on Windows where delete only fails for some files (e.g. on UNC shares) but not others.

**Comment by the-kenny** [comment]
That's a good point. Maybe it's a better idea to make a `trashBehavior` option that has multiple possible values: `moveToTrash`, `deletePermanently`, `trashIfPossible` (preliminary names).

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/14638
