### ISSUE TITLE
Prevent committing files with unused variables

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#42157]
We used to block committing code with unused variables, when TSLint was making that check. Now we leave that task up to TypeScript, so the hygiene script won't catch unused variables anymore. This is too bad, since when committed and pushed, code containing unused variables will work and run, yet the build will fail.

Another point of view to this problem is that these unused variables are now considered to be compilation errors. We never prevented people from pushing code which is broken, in terms of compilation. So... this would be a no-op.

**Comment by egamma** [comment]
@joaomoreno I´ve submitted https://github.com/Microsoft/vscode/pull/42831 to enable the unused variable tslint rule, please see this PR for details.
