### ISSUE TITLE
Recommendation prompt is shown for .js files

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#42154]
![image](https://user-images.githubusercontent.com/172399/35389059-7abb41da-01d6-11e8-977f-13bcc334006e.png)

This prompt should only be shown when a file is open for which we have no language registered.

**Comment by ramya-rao-a** [comment]
@egamma Can you get a consistent repro of this?
Looks like a race condition.
We do show this prompt only for files which don't have any mime type supported, and we make this check at the right point in the lifecycle.

**Comment by egamma** [comment]
@ramya-rao-a I cannot repro reliably, but I just saw it again when opening a .json file.

**Comment by ramya-rao-a** [comment]
Was that in a workbench that was already open for a while or a newly opened VS Code window?

**Comment by ramya-rao-a** [comment]
We were waiting for `LifecyclePhase.Eventually` assuming that extensions are registered by then.
Wrong assumption.
Updated to use `extensionService.whenInstalledExtensionsRegistered` instead
