### ISSUE TITLE
In windows: start -> "vscode" does not find Visual Studio Code

### ISSUE THREAD

**Issue by generateui** [Microsoft/vscode#42150]
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. Hit Windows start button or hit Windows key from keyboard
2. type "vscode"

Windows does not find Visual Studio Code, where I sort-of expected it would. It will when typing "code" (without "vs" prefix). Since on many social outlets (blogs, GH, Reddit, ...) Visual Studio Code is marketed as vscode, I suggest making this work.

**Comment by joaomoreno** [comment]
Actually I get this:

![image](https://user-images.githubusercontent.com/22350/35398404-0e2985ce-01f2-11e8-9aa4-654c9550b1b8.png)

What do you get?

**Comment by imba-tjd** [comment]
I give my test.
![image](https://user-images.githubusercontent.com/24759802/35481159-3b611d72-0459-11e8-8b58-ba94531c58d5.png)

**Comment by timbovaird** [comment]
I do this everytime I launch vscode, finally annoyed me enough to search for a solution.

![image](https://user-images.githubusercontent.com/16712403/37870049-2312ad42-2fbc-11e8-98aa-a0c2105afb2b.png)

**Comment by tabedzki** [comment]
For me, "vscode" links to the executable. Is there a way to make it that "vs code" also links to the executable?

**Comment by ajarouih** [comment]
1 - Click on the Start Menu. It's the Windows icon in the bottom left corner.

2- Write anything you want exemple "`vscode`" and click and Filters button in the up right corner .

3- Click on the last button "`Show emplacements`" .

4 - Click on Advanced , and enable indexing Crypted files .

The problem : is that  `%AppData%`  files are always ignored by system by default in windows 8+ that all of them begin always with  a point , ie : `.VisualCode` [.]

![](https://media.giphy.com/media/2uxZuOyxS2ewbaGuOo/giphy.gif)

**Comment by joaomoreno** [comment]
Closing as won't fix. Just search for `code`. Thanks for understanding.
