### ISSUE TITLE
Discard changes for one file discards all of the changes in mercurial

### ISSUE THREAD

**Issue by apieceofbart** [Microsoft/vscode#42155]
- VSCode Version:  1.19.2
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Have a repo setup using mercurial
2. Add mercurial (Hg) SCM Provider from the Source Control menu
3. Make a change to two files
4. In the Source Control menu click discard icon next to one of the files
5. In the prompt window asking if you want to confirm discarding changes for this file click "Discard Changes"

Once you do this changes to all files are discarded.

Does this issue occur when all extensions are disabled?: Yes/No
When I open code with `--disable-extensions` flag I don't see any file changes in Source Control panel only message: "There are no active source control providers"

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository, which I assume to be https://github.com/mrcrowl/vscode-hg
