### ISSUE TITLE
File Explorer context menus provided by extensions don't work if there is no active editor

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#42163]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (8708c716367d9ea6822c860c1fcfcff4e2034605, 2018-01-25T11:32:01.804Z)</li>
	<li>OS Version: Windows_NT x64 10.0.17083</li>
</ul>

---

Steps to Reproduce:

1. Close all editors
2. Right click on a file in the File Explorer
3. Pick an item contributed by an extension (say GitLens Show File History)
4. Observe that nothing happens -- if there is an active editor the command works fine.

In this scenario I don't see the callback provided in `registerCommand` getting called.

Reproduces without extensions: No

**Comment by bpasero** [comment]
@isidorn I can reproduce and we should fix for January.

**Comment by isidorn** [comment]
@eamodio great catch, tahnks for reporting.
The issue was that I was passing an incorrect context when there was no selection in the explorer (the full FileStat instead of just the resource).

**Comment by eamodio** [comment]
Thanks!
