### ISSUE TITLE
Incorrect coloring after heredoc in a shell script

### ISSUE THREAD

**Issue by kkimdev** [Microsoft/vscode#42168]
- VSCode Version: 1.19.2
- OS Version: Windows 10.0.16299

Steps to Reproduce:
open a script file test.sh
```sh
cat > /etc/profile.d/yarn_global_bin.sh << 'EOF'
#!/bin/sh

PATH="$PATH:`yarn global bin`"
EOF

echo "sdfsdf"
```

then the last line, `echo......` is incorrectly colored
Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Duplicate of https://github.com/atom/language-shellscript/issues/72 which has been closed as wont-fix upstream
