### ISSUE TITLE
Python - autocomplete of function parameters not working

### ISSUE THREAD

**Issue by nbahmanyar** [Microsoft/vscode#42169]
- VSCode Version: 1.19.3
- OS Version: Windows 10

Steps to Reproduce:

1. add `    "python.useCodeSnippetsOnMethodSuggest": true,` to user settings
2. function parameters don't autocomplete.

Function parameter autocompletion works with Typescript using the above setting, but not with Python.

Thanks for the help.

**Comment by mjbvz** [comment]
Please file this issue against the python extension
