### ISSUE TITLE
Snippet inside dollar signs

### ISSUE THREAD

**Issue by ketozhang** [Microsoft/vscode#42167]
I'm attempting to use the following snippet in a Markdown file

```JSON
"align": {
	"prefix": "\\align",
	"body": [
		"\\begin{align}",
		"\t$TM_SELECTED_TEXT$1",
		"\\end{align}"
	]
}
```

Very commonly this snippet is typed inside dollar signs for Markdown LaTeX such as `$$\align[TAB]$$`. How do I have the snippet not consider the `$$` as a prefix?

> _`[TAB]` refers to tab completion_

What works perfectly is if there is a space on the left and right of the prefix `$$ \align[\tab] $$`  and also parenthesis `(\align[TAB])`. I'm assuming there is a config where snippets ignore whitespaces, parenthesis, etc.

My only solution is to literally put the dollar signs in the snippet and just use `\align`.

```JSON
"align": {
	"prefix": "\\align",
	"body": [
		"$$",
                "begin{align}",
		"\t$TM_SELECTED_TEXT$1",
		"\\end{align}",
                "$$"
	]
}
```

**Comment by jrieken** [comment]
> How do I have the snippet not consider the $$ as a prefix?

Not really sure what you mean? Can you attach an animated gif or more precise steps?

**Comment by ketozhang** [comment]
1. Add the first code block above to snippet
2. First try to use the snippet `\align` via tab completion between `$$ HERE $$`. **Works**
2. Then try to use the snippet `\align` via tab completion between `$$HERE$$`. **Does not work**

![blah](https://user-images.githubusercontent.com/13506487/35545854-136487e6-0526-11e8-8fe1-8a2c11fc7c99.gif)

**Comment by ketozhang** [comment]
Solved, just set the following three to true (only `"other"` was true by default)

```json
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
```

**Comment by jrieken** [comment]
The problem here is that quick suggestions (suggestion that show as you type) only appear at word ends and not when typing inside a word. What a word is is defined by the language. Having said this, with todays [Insiders](https://code.visualstudio.com/insiders/) builds tab completion has gotten much smarter. Set the option `on` and pressing tab will complete your snippet.
