### ISSUE TITLE
Warning notification shown after creating debug config 

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#42176]
A warning notification shown after creating debug config, which is confusing as you just added a configuration.

**Steps:**
1. Open folder with no `launch.json`
2. Go to debug view, select config dropdown, click add configuration
3. Select Node.js 
4. Default `launch.json` is generated but a warning notification is shown.

**Expected:**
No warning to be shown as there is a debug config,.

<img width="1552" alt="screen shot 2018-01-25 at 4 51 29 pm" src="https://user-images.githubusercontent.com/173559/35420116-901dd974-01f0-11e8-95ed-fa8b24009f73.png">

**Comment by isidorn** [comment]
I have removed this info message all together. Since in 95% case there will be a launch configuraiton present, and it is sort of stating the obvious.

**Comment by auchenberg** [comment]
👍
