### ISSUE TITLE
Allow to set files.autoSave as language specific or folder setting

### ISSUE THREAD

**Issue by yunyu** [microsoft/vscode#42170]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|0.2.2
simple-react-snippets|bur|1.1.1
arm|dan|0.1.2
vscode-eslint|dba|1.4.4
prettier-vscode|esb|1.1.2
sublime-babel-vscode|jos|0.2.9
Go|luk|0.6.73
python|ms-|0.9.1
material-icon-theme|PKi|3.2.1
python|tht|0.2.3
tiger-vscode|yun|0.0.1
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Search for the "Configure language specific settings" command by pressing Ctrl+Shift+P
2. Select any language
3. In the configuration specific to that language, paste the line `"files.autoSave": "afterDelay"`
4. VSCode reports "Unknown editor configuration setting", but the global setting for "files.autoSave" works

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Similar to #39051. Currently `"files.autoSave"` is not a supported language specific setting

**Comment by tschaub** [comment]
I was just going to open the same issue.  In my case, I'm finding it hard to configure VSCode for both JavaScript and Go development.  For Go, `files.autoSave` is nice.  For JavaScript, `files.autoSave` wreaks havoc with HMR or other bundle on change tools.

**Comment by tschaub** [comment]
Can anyone provide guidance on how someone might fix this?  Is there a commit or merge request that implements something similar that could be used as a starting point?

**Comment by tschaub** [comment]
I see where `overridable: true` could be added to the `files.autoSave` (and `autoSaveDelay`) configuration: https://github.com/Microsoft/vscode/blob/7e7961895c6c940365bfc4bbf2287a8b8c851195/src/vs/workbench/contrib/files/browser/files.contribution.ts#L282-L293

Then it looks like overrides would need to be provided when getting the configuration: https://github.com/Microsoft/vscode/blob/7e7961895c6c940365bfc4bbf2287a8b8c851195/src/vs/workbench/services/textfile/common/textFileService.ts#L96

Maybe this override would look like
```js
{overrideIdentifier: model.getLanguageIdentifier().language, resource}
```

But I'm uncertain what `model` and `resource` would be in this context.  I also have no idea how this would impact other configuration and am uncertain how folder overrides are handled.  And it looks like there are a few other places where the `files.autoSave` configuration is accessed that would need updating.

Any suggestions from vscode contributors on whether this is the right direction?  I imagine there are complications, but would be happy to get something started unless this is something that is not easily achievable with the way this configuration is handled.

**Comment by zion** [comment]
@tschaub I came to the same conclusion as you. Setting `overridable: true` where you suggested did indeed remove the "Unknown editor configuration setting" error in the `settings.json` file. But I couldn't figure out how to actually apply the settings. 

I was testing this with a workspace, so that might be yet another variable here. I really want to have control over what files are auto saved. I have a workspace that has 2 project folders, one for api and one for front end. I suspect that many others do as well, this would be a great enhancement to Code. 

Any guidance or insights you can offer us @bpasero?

**Comment by rusnasonov** [comment]
It can be usefull for some sort of virtual FileSystemProviders when writeFile operation is very expensive.

**Comment by tschaub** [comment]
Adding a reference to #82101 (allowing `files.eol` to be set per-language) in case there are things to crib from in that change.

**Comment by broly8** [comment]
This problem also bothers me. Expect to be resolved.

**Comment by g10guang** [comment]
Missing Feature **autosave just for current open directory file**.

**Comment by iqDF** [comment]
vote vote vote!

**Comment by desmondlzy** [comment]
Yeah, I feel this feature could be really helpful to me! 

Autosaving for source code is nice, but when editing latex file with 'compile upon save', frequent save can keep on invoking the compiler and let error messages flood in... I deal with it by toggling autosave or set up a workspace config, neither of which is really neat. So I would really love it if we can config autosave for different file types!

**Comment by tusharsadhwani** [comment]
Bump.
Really need autosave for python (as of now), but for nothing else. It's annoying to keep toggling that setting.

**Comment by whitecolor** [comment]
Such improvements may be waited for years. Probably some custom extension is needed.

**Comment by abdul06** [comment]
This feature would be great!

**Comment by willium** [comment]
Are there any extensions that do this? Or any hope of bringing this back in scope?

Our use case: declaration files that are auto-generated by TypeScript aren't recognized by VSCode eslint plugin until they're saved, requiring a tedious workaround or turning on auto-save which can cause problems with watch scripts.

**Comment by whitecolor** [comment]
@willium 
I've made the extension but didn't publish it, it worked for me, so you may try, build and place/link it to the vscode extensions folder =) 
https://github.com/whitecolor/vscode-autosave-ext

**Comment by thehale** [comment]
@wclr Can you add an OSI license to your autosave extension? (e.g. MIT, Apache-2.0, or MPL)?

**Comment by wclr** [comment]
@thehale yes.

**Comment by BachoSeven** [comment]
why was this closed?

**Comment by thehale** [comment]
> why was this closed?

See https://github.com/microsoft/vscode/issues/110047#issuecomment-998997523

It's also been superseded by #181942, which is currently in the Insiders build: https://github.com/microsoft/vscode/issues/181942#issuecomment-1849420616
