### ISSUE TITLE
Visual studio Black screen opening 

### ISSUE THREAD

**Issue by ashwinr63** [Microsoft/vscode#42181]
- VSCode Version: 1.19.3
- OS Version:16299.192

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/8831182/35425412-b64e91d4-0280-11e8-8935-7b27eb1c051f.png)

![image](https://user-images.githubusercontent.com/8831182/35425431-cbb3722e-0280-11e8-81f0-62ec5599b3af.png)

i'm not able to open the editor at all to work, Kindly help me with this issue

**Comment by mjbvz** [comment]
Does this still happen if you run `code` with the `--disable-gpu` flag?

**Comment by ashwinr63** [comment]
It runs while providing the flag 'code --disable-gpu'. 

But how can always use the command prompt or temp settings to open the editor . Isn't there any permanent solution to the problem
