### ISSUE TITLE
Feature request:insert key

### ISSUE THREAD

**Issue by BugHiding** [Microsoft/vscode#42184]
The insert key can't use. When I want to use the insert key to switch between the two text-entering modes.

- overtype mode
- insert mode

[Insert Key](https://en.wikipedia.org/wiki/Insert_key)

VSCode is cool,THX.:rose:

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/1012

**Comment by BugHiding** [comment]
THX:sparkling_heart:
[Overtype](https://marketplace.visualstudio.com/items?itemName=adammaras.overtype)
The extension is Good!
THX:thumbsup:
