### ISSUE TITLE
Bug about go to symbol in workspace

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#42180]
"go to symbol in file" works when using lua 
,but 
"go to symbol in file in workspace" not works in workspace.

when using golang. both are ok.

and, although it (go to symbol in file) works . why just show all the symbol automatically. Forcely asking user to type some keyword and there show the result list. ... (tuokuzifangpi joke.)

**Comment by mjbvz** [comment]
Please file this issue against your lua extension
