### ISSUE TITLE
SHIFT+F12 can not show "All the reference"

### ISSUE THREAD

**Issue by tljustin** [Microsoft/vscode#42188]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
referenceshelper|gay|0.2.2
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
vscode-clang|mit|0.2.2
python|ms-|0.9.1
cpptools|ms-|0.14.6
team|ms-|1.122.0
vscode-code-outline|pat|0.0.12
vscode-icons|rob|7.19.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please provide steps to reproduce the problem: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues
