### ISSUE TITLE
Please Improved Search result display [New feature Request]

### ISSUE THREAD

**Issue by doyee** [Microsoft/vscode#42187]
- VSCode Version: All version till now
- OS Version: Mac

Steps to Reproduce:

1.this snapshot is the display panel of search result of Vscode
<img width="1279" alt="screen shot 2018-01-26 at 3 13 32 pm" src="https://user-images.githubusercontent.com/2289290/35429154-c2659a30-02ad-11e8-8345-2ca0c1924997.png">
2.I want to search result like below：
<img width="1240" alt="screen shot 2018-01-26 at 3 11 35 pm" src="https://user-images.githubusercontent.com/2289290/35429178-d95addf4-02ad-11e8-96d2-cd1f955c24d3.png">
  Most like nodepad++, the results of the search are displayed independently, and the results of the search can be replicated at once.

thanks

**Comment by doyee** [comment]
VSCode search result without the lineNumber, timestamp and so on.
     I think it's very useful for a programer to check the log

**Comment by doyee** [comment]
@roblourens Do you have a plan to improve the search viewlet?

**Comment by roblourens** [comment]
There are several issues tracking various improvements to the search viewlet.

**Comment by doyee** [comment]
@roblurens，what is plan to improve the viewlet

**Comment by roblourens** [comment]
Here are existing feature requests but we don't have any immediate plan to act on them: https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afeature-request+label%3Asearch

**Comment by doyee** [comment]
@roblourens there so many same requests of search, why not to act on them?
Don't just reply, and no real action

thanks
