### ISSUE TITLE
emmet is now shitty

### ISSUE THREAD

**Issue by GirgisDev** [Microsoft/vscode#42196]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
ng-template|Ang|0.1.8
bracket-pair-colorizer|Coe|0.10.14
vscode-great-icons|emm|2.1.22
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
icon-fonts|idl|1.10.1
path-autocomplete|ion|1.8.1
vscode-angular2-emmet|jak|2.0.3
vscode-gutter-preview|kis|0.12.2
vetur|oct|0.11.6
material-icon-theme|PKi|3.2.1
LiveServer|rit|3.1.0
vscode-icons|rob|7.19.0
autoimport|ste|1.5.3
highlight-matching-tag|vin|0.4.4
markdown-all-in-one|yzh|1.0.3

(5 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
There is nothing we can do for an issue that has been logged with no details whatsoever. 

Please read [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) for tips on logging issues in the future.

Also read [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet) to understand how to get how Emmet works in VS Code.
