### ISSUE TITLE
Discard all changes only discards one

### ISSUE THREAD

**Issue by cambraidwood** [Microsoft/vscode#42197]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. make a few changes, in a few files
2. look on your source control tab
3. use the revert arrow to dis-guard all changes
4. it only reverts the top file, not the others ... you have to do it again

**Comment by joaomoreno** [comment]
Can you repeat the operation, but this time keep the Git Output open? Run <kbd>F1</kbd> `Show Git Output`, to show it. What is its full output?
