### ISSUE TITLE
Terminal scrolled to top after switching terminals

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42199]
### Issue Type
Bug

### Description

Sometimes when switching terminals the terminal shown is scrolled to the very top. Not sure what the steps are that repoduce it.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (ed4c237467bfe7c37b173da782cb65e333484a13, 2018-01-26T06:08:15.259Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1298749|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.0
autofilename|Jer|0.1.3
vscode-docker|Pet|0.0.23
regex|chr|0.1.0
ssh|chr|0.0.3
vscode-eslint|dba|1.4.4
ghlink|dt|0.0.6
tslint|eg2|1.0.24
rest-client|hum|0.16.2
vscode-azureappservice|ms-|0.5.1
vscode-azurefunctions|ms-|0.5.0
vscode-cosmosdb|ms-|0.4.0
azure-account|ms-|0.3.0
azurecli|ms-|0.4.0
github-issues-prs|ms-|0.9.0
vsliveshare|ms-|0.1.0-preview.202
debugger-for-chrome|msj|4.0.0
vetur|oct|0.11.6
vscode-versionlens|pfl|0.19.1
vscode-open-in-github|sys|1.6.0
i18n-sample|vaz|0.1.0

</details>

**Comment by Tyriar** [comment]
I've been trying to get a repro for this pretty much since the beginning 😄. It's definitely annoying but no idea what causes it.

**Comment by chrmarti** [comment]
Attaching a simple JavaScript file and a compound launch config that seem to reproduce it quite reliably:
- Start compound launch
- Switch between the two terminals using the drop-down switcher
- After switching a few times usually both terminals end up jumping to the top at some point

[42199.tar.gz](https://github.com/Microsoft/vscode/files/1685334/42199.tar.gz)

**Comment by chrmarti** [comment]
It sometimes take longer to occur. Not sure what affects it.

**Comment by Tyriar** [comment]
@chrmarti this is perfect, I should be able to root cause this very longstanding issue with this ❤️

**Comment by Tyriar** [comment]
It's happening because `Viewport.onScroll` is triggered before `scrollTop` is updated.

<img width="307" alt="screen shot 2018-02-01 at 8 41 36 am" src="https://user-images.githubusercontent.com/2193314/35690830-bf8b7f28-072b-11e8-8f86-8cb37a234a49.png">

Looks like a race condition that happens when the pty sends a line feed just as the terminal is being reattached and the scroll bar is getting fixed up.

**Comment by Tyriar** [comment]
Trace causing the problems:

<img width="238" alt="screen shot 2018-02-01 at 8 45 54 am" src="https://user-images.githubusercontent.com/2193314/35691061-5d714768-072c-11e8-9536-fd93a28cd1ca.png">

**Comment by Tyriar** [comment]
Ok so what appears to be happening is a line feed goes off, triggers a scroll and the viewport element's `scrollTop` is being set to the correct value in syncScrollArea. After the async break though `scrollTop` is 0 😕

**Comment by Tyriar** [comment]
It happens for the terminal that is hidden, not shown.

**Comment by Tyriar** [comment]
I have a fix but I think I'll push it to next version just in case.
