### ISSUE TITLE
missing 1.19.3 package as DEB and RPM

### ISSUE THREAD

**Issue by ulrichSchreiner** [Microsoft/vscode#42190]
on both URL's
~~~
https://packages.microsoft.com/yumrepos/vscode/
https://packages.microsoft.com/repos/vscode/pool/main/c/code/
~~~
there is no package (deb, rpm) for 1.19.3

**Comment by Tyriar** [comment]
The deb should have been up for a few days, the rpm will be published tomorrow

**Comment by stic** [comment]
Hi Tyriar,
The rpm is there but the repo still points to 1.19.2 (hence dnf doesn't update correct), could that be sorted? Seems lot like #40972. Thanks.

**Comment by jlmagee** [comment]
on Fedora 26 with the below version of vscode, the Download Now link still tries to download a tar file

Version 1.20.0-insider
Commit f9398645d1d624538708eeebf96e6fdeb546f5d7
Date 2018-02-06T15:17:22.839Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Tyriar** [comment]
@stic the repo should not contain both 1.19.3 and 1.20.0: https://packages.microsoft.com/yumrepos/vscode/

@jlmagee we do not ship insiders as an rpm

**Comment by jlmagee** [comment]
@Tyriar The big .RPM button at https://code.visualstudio.com/insiders/ downloads an rpm of insiders/  

What is the next glib excuse?

**Comment by jlmagee** [comment]
@mjbvz @alexandrudima @Tyriar There is no rational indication that #42311  has anything to do with this issue. Until about 15 days ago, the "Download Now" selection from the settings button of the code-insiders UI opened the page at https://code.visualstudio.com/insiders/ from which an RPM of code-insiders could be downloaded. Now it navigates a browser to a forced download of a tar file which is not what is desired on a Fedora 26 laptop.  

**Please re-open #42311  and work on resolving that issue.**

**Comment by davidwhitman** [comment]
The latest build at https://packages.microsoft.com/yumrepos/vscode/ is 1.20.x and 1.21 has been out for a while. Is the February release going to get pushed to the repo?

**Comment by Tyriar** [comment]
I updated the docs to indicate that there may be a delay. This happens most months for various reasons that are generally out of our team's control https://github.com/Microsoft/vscode-docs/commit/edd77942d0a43d734ffed7aa51b0c13b98bc6744
