### ISSUE TITLE
TS Auto Module Importing doesn't work on new version of VSCode (1.19.2)

### ISSUE THREAD

**Issue by adevknight** [Microsoft/vscode#42192]
- VSCode Version: 1.19.2
- OS Version: Windows 10 x64 10.0 Build 16299

Steps to Reproduce:

1.  Open any angular project source code with VSCode
2.  Open any `.ts` file, e.g: `myapp.component.ts`
3.  Inside `export class MyAppComponent {}`
type following `myform: FormGroup;`
the Editor should show `red underline` and `light bulb icon on left sidebar` indicating and error, since `FormGroup` in unknown. On this version of VSCode we can only see the `red underline` ,  **there is no** `light bulb icon` appear on left side bar (near line number).
4.  On previous version the `light bulb icon`  will appear and if we click on it there is an option for auto importing `Form Group from @angular/forms`

Does this issue occur when all extensions are disabled?: Yes

**UPDATE:** 
I already updated VSCode to 1.19.3, at the beginning there is no problem with the **auto module import** feature on Angular2+ project (with or without enabling extension), but after few days the problem apear again and this time auto module import will not work at all even after disabling all extensions, and i'm tired of re-installing VSCode from the beginning again.

Here is my `tsconfig.json`
```
 {
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
  {
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

and there is a message:
```
[Info  - 12:21:02 AM] Linter is running.
[Info  - 12:21:06 AM] TSLint library loaded from: d:\Desktop\One\AngularProj\node_modules\tslint\lib\index.js
Warning: The 'deprecation' rule requires type information.
Warning: The 'no-use-before-declare' rule requires type information.
```

My node_module
**TSLint** version: 2.8.0
**TypeScript** version: 2.6.1

**Comment by mjbvz** [comment]
Do you have a `tsconfig.json`? Also, can you please try this in the [latest VSCode insiders build](https://code.visualstudio.com/insiders/)
