### ISSUE TITLE
Test: proposed API for multi root folder changes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42195]
Refs: #35407

Complexity: 3

- [x] windows @weinand 
- [x] linux @chrmarti 
- [x] macOS @octref 

There is new proposed API (`updateWorkspaceFolders(start: number, deleteCount: number, ...workspaceFoldersToAdd: { uri: Uri, name?: string }[]): boolean`) to update the workspace folders of the workspace from an extension. The API provides full control over:
* removing existing folders
* adding new folders
* doing both at the same time (this allows to e.g. move an existing folder to another index)

**Verify:**
* the JSDoc of this method allows you to understand what the method is doing
* you see a little status message when a folder is added or removed with the name of the extension
* changes are always reflected without a window reload and the extension host continues to work (note that some transitions still require the extension host to restart, e.g. when the first folder changes)
* test with empty workspace, single folder workspace and multi-root workspace
* test adding folder(s), removing folder(s), and changing folders (e.g. rename a folder name or swapping folders position)

**FYI - to test against the latest API do the following:**

* open your extensions package.json file
* change the engine.vscode property to *
* run npm run postinstall (assuming you have the vscode module as dev-dependency)
* undo the engine-version change from step 2
* run with --enable-proposed-api  
* copy the updateWorkspaceFolders method from vscode.proposed.d.ts into vscode.d.ts of the vscode node_module

**Comment by chrmarti** [comment]
@bpasero You still need to copy the `vscode.proposed.d.ts`, don't you?

**Comment by bpasero** [comment]
@chrmarti yeah thats right!

**Comment by octref** [comment]
I was able to use `updateWorkspaceFolders` to remove one folder, but `onDidChangeWorkspaceFolders` did not fire. Wondering if I'm doing something wrong...

Code is

```ts
import * as vscode from 'vscode';

export const activate = (context: vscode.ExtensionContext) => {
  vscode.workspace.onDidChangeWorkspaceFolders((e) => {
    console.log(e.added.length) // never executed
    console.log(e.removed.length)
  })

  vscode.commands.registerCommand('extension.helloWorld', () => {
    vscode.workspace.updateWorkspaceFolders(0, 1) // this did remove one folder
  })
};
```

@bpasero Any ideas?

Also instead of `--enable-proposed-api` , it should be adding `"enableProposedApi": true` to `package.json`, right?

**Comment by bpasero** [comment]
@octref if do any change that modifies the first folder in the list, the extension host will restart so you will not be able to get any event.

**Comment by chrmarti** [comment]
I can't get `--enable-proposed-api` to work on Linux. I tried adding it when starting the host and in the launch config. I'm now using `"enableProposedApi": true` in the package.json, that works. Any idea what I did wrong with the command line parameter?

**Comment by bpasero** [comment]
@jrieken might know

**Comment by jrieken** [comment]
The flag needs the extension id and I do believe the property in package.json is almost always required
