### ISSUE TITLE
Preserve window size when restoring a maximized window

### ISSUE THREAD

**Issue by prasannavl** [microsoft/vscode#422]
The window size is not preserved, if VSCode is closed being maximized. 
The correct behavior should be that it restore to the previous un-maximized size, when restored.

**Comment by mackenza** [comment]
what platform?

**Comment by prasannavl** [comment]
Windows. 

But I suspect, it should be a problem with all platforms unless the window managers override it, which could hide the problem.

**Comment by mackenza** [comment]
where did this standard of restoring un-maximized when you shut down maximized come from? I am on Linux (Mint Cinnamon) and every app I tried restored maximized if I shut it down maximized. I am not around my Windows machines right now so can't test there. Is this in some sort of Windows style guide item?

**Comment by prasannavl** [comment]
I'm afraid there's really no style guide in that aspect. But Windows always properly stores the window sizes, and its a convention that's just in practice, unless an application overrides it explicitly. 

This deviates from it.

Just to clarify, yes it opens maximized, if it shuts down maximized - that's correct behavior. But when you restore it now, it loses its last saved state.  

Technically, its an Electron bug, where it only stores the last size, which when maximized is the maximized size instead of the restored window sizes.

**Comment by bpasero** [comment]
Yeah, known issue.

**Comment by regs01** [comment]
This could be related
If there is any VS Code window is open, new instance resets window size to default. Still there as of 0.10.11.

**Comment by bpasero** [comment]
Well we open any Nth window (for N > 1) in the default size, what would you expect otherwise?

**Comment by regs01** [comment]
well, i more expect size i want, cause i have to resize the tiny window every time i open it. just save the last size and use it always until any window get resized.

**Comment by bpasero** [comment]
@regs01 so you would expect the second window to open with the size of the window that is already open?

**Comment by regs01** [comment]
@bpasero kind off. so i just resize it once and it will save my size, then any instance, no matter if 1st, 2nd or 3rd will open with my size. well, any other app does like this.

**Comment by bpasero** [comment]
@regs01 I suggest you open a separate issue on that topic as this one here talks about a different problem.

**Comment by prasannavl** [comment]
@bpasero I'd say that the point made by @regs01 and this are highly related. So much so, that fixing this unless explicitly overridden should fix that as well naturally. 

The idea is that whenever a window is created, it should now use the last saved size. Now, the intricate detail here is that the last saved size should never be the maximized size. (If the window is maximized when it quits, it should rather save the size before maximization with an isMaximized flag). And any window that's created uses this size and flag on creation.

**Comment by prasannavl** [comment]
Pseudocode (It doesn't reflect electron's api. Just the idea): 

```
let { w, h, x, y, isMaximized } = getSavedSizeObject();
window.create(w, h, x, y); 
if (window.isMaximized) window.maximize();
window.show();
```

**Comment by bpasero** [comment]
@prasannavl I am not entirely convinced that the one issue is the same as the other. your issue talks about the fact that when you maximize a window from a certain size and then restart and restore, the previous size is not restored. I see this as an actual bug we should fix eventually.

The other point is about how new windows should be sized when you open them. I am not sure there is a solution that makes everyone happy. Yes, you could just pick the window size of the window that is the last active one, but from a UX perspective we decided not to create a window with the exact same dimensions because it can make it hard to actually notice that you have 2 windows open now. That is why we decide to fall back to the default size and you will notice that any further window you open from that point will cascade the window a little bit so that they are not exactly overlapping.

Now, you could also argue that maybe the window that opens should inherit a size that was associated with that folder when you previously opened it. Imagine we would remember each window dimensions for each folder opened and restore it if you ever open that folder again. Still, this might not fix the UX issue of overlapping windows.

I would be open to discuss other solutions but I would think that discussion should happen in another work item.

**Comment by prasannavl** [comment]
@bpasero The problem you mention can be solved this way, in a manner to keep everyone reasonable happy until more advanced configurations (if all worth going through the trouble) are added.  

If its the first window opened by the application, use the same size. 
If it is indeed a new one, cascade x, and y a bit. Now in order to do this, first check x + width, and y + height to make sure its not outside bounds of the visible screen. If it is, reduce the cascade values by half and try again, until its either zero, or succeeds. If all fails, now do the same thing again, with negative cascades as it approaches zero again. 

The nifty little trick here, will be that, `don't use the sizeTracker.setAll` pseudo code above on window creation when its a non-first window. It will however work during resizes. So, the cool thing is, now the user size will always be respected, even though new windows cascade.

**Comment by prasannavl** [comment]
PS: You could also very well, just let the platform's window manager handle the secondary windows positions, by ignoring the x and y completely. Windows should handle the cascading on its own (Win32 should, but not sure if electron overrides it) I would consider that as a first stage to the solution.

**Comment by bpasero** [comment]
I am quite sure that the framework we use (Electron) on Windows does not provide any functionality to position the window in a clever way, but I can try again.

**Comment by prasannavl** [comment]
@bpasero Why I'm not highly familiar with electron at the moment, I do know enough to agree that it doesn't provide any clever positioning. But what I was pointing at, was that does electron let the platform manager natively handle its position, or does it override the native functionality and thereby dum it down?

If its the former, then should be easy or I'm afraid the logic that I mentioned using the cascade, or similar has to be implemented. But considering the fact that you already do cascade it, can't we just use the same cascade logic that you already do, but just with the saved size instead of the default fallback size?

**Comment by regs01** [comment]
I just wanted to say exactly same. It's been pretty common in Windows to cascade windows. I was saying use same size, but i didn't say anything about same position, right because of cascading.

So there is a logic that could work flawlessly
1. First instance should open with saved size, saved position and saved state (maximized/restored).
2. Second instanced should only utilize saved size, but not position and state. If it's not possible to cascade it, then just use random position. State, though, is debatable. Some might would prefer all instances maximized.

**Comment by bpasero** [comment]
Allright, let me update the issue to reflect the discussion.

**Comment by glen-84** [comment]
> Some might would prefer all instances maximized

If I right-click on the taskbar icon and select `New Window` when I already have a maximized window open, the new window is not opened in a maximized state, which is really not helpful, as I then have to manually maximize it each time.

**Comment by MikeSouza** [comment]
@bpasero 
>Well we open any Nth window (for N > 1) in the default size, what would you expect otherwise?

I agree with @prasannavl and @regs01.

I expected the same behavior as the other Visual Studio products.  The workflow most people who've used older Visual Studio products with multiple window instances opened, are familiar with a use case along the lines of:

1. Close all windows of Visual Studio 20XX that may already be open.  May also need to ensure that no zombie devenv.exe processes are lingering in the background.
2. Open a new instance of Visual Studio 20XX.
3. Resize the window to however you like.
4. Close the window, which will persist the window size.
5. Open N > 0 instances of Visual Studio 20XX.  Each will use the last persisted window size.

**Comment by regs01** [comment]
Most annoying thing about this problem is that it saves default window size every time you open second window. So basically those who are using multiple windows just stuck in a little window.

**Comment by bpasero** [comment]
Configuring `window.newWindowDimensions` helps in that case

**Comment by regs01** [comment]
window.newWindowDimensions helps to launch in previously stored size. But if it was maximized, then window size gets lost and resets to default.

**Comment by tgdn** [comment]
Doing something similar to what [electron-window-state](https://www.npmjs.com/package/electron-window-state) does is probably the intended behaviour here

**Comment by adonig** [comment]
Here is a workaround for those who still suffer. Don't maximise the window by clicking the "maximise" button. Just drag the window borders to the borders of the screen so the window fills the whole screen. Thereafter it stores the size on close and launches maximised.

**Comment by kocicmickey** [comment]
This bug accidentally saved my butt when I just started to use VS Code and accidentally made it full-screen. I couldn't figure out a way to exit full-screen mode, but when I shut down VS Code and restarted it, it was back to windowed. That helped me greatly because I can't find information on how to exit full screen using VS Code.

**Comment by rakkarage** [comment]
everyone on windows and linux is losing window size on maximize many times every day for 4 years?

**Comment by rakkarage** [comment]
another workaround is to use devilspie2.lua or something to resize window when it starts

`if (get_window_name()=="Visual Studio Code - Insiders") then
	unmaximize();
	set_window_geometry(160, 90, 1600, 900);
end`

**Comment by bpasero** [comment]
Electron 4 introduced a new method `BrowserWindow.getNormalBounds()` that allows to ask the window for its bounds in non-maximized state. I pushed a change to use this method on Linux and Windows such as when you restore the window, you will get those bounds returned.

**Comment by regs01** [comment]
Did it go into June 2019 update?

**Comment by bpasero** [comment]
No, July. 
This issue has already been fixed in our insiders version but not yet released to the stable version. To benefit from the fix, you can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
Verification: verify that the "normal" bounds of a window are persisted, via
* be on Windows
* position the window (not maximized) somewhere 
* maximize window
* close
* start
* the window should opened maximized
* now restore the window (click restore button in title)
* the window should now have the size and position where you left it before
