### ISSUE TITLE
Cmd and Alt/Option partially flipped on Mac (when combined with mouse clicks?)

### ISSUE THREAD

**Issue by mrwonko** [Microsoft/vscode#42205]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
xml|Dot|1.9.2
graphviz-preview|EFa|0.0.3
vscode-docker|Pet|0.0.23
dot|Ste|0.0.1
githistory|don|0.3.6
haskell-linter|hoo|0.0.6
vscode-ghc-mod|hoo|1.2.0
language-haskell|jus|2.4.0
Go|luk|0.6.73
python|ms-|0.9.1
azure-account|ms-|0.3.0
cpptools|ms-|0.14.6
language-purescript|nwo|0.1.2
java|red|0.17.0
RustyCode|sav|0.19.1
code-spell-checker|str|1.6.2
cmake|twx|0.0.17

Steps to Reproduce:

* Alt-Click a function name. Instead of creating a multi-cursor, it goes to the function definition.
* Cmd-Click a function name. Instead of going to the function definition, it creates a multi-cursor.

The keys are not universally flipped; Cmd+Up still moves the cursor to the top of the file, Cmd+W still closes a tab, Alt+Up still moves a line, Alt+Z still toggles word wrap. Only modifiers for mouse clicks seem to be affected.

Does this issue occur when all extensions are disabled?: Yes (go to definition doesn't work without the language extension, but multi-cursor still shows incorrect behavior.)

**Comment by alexandrudima** [comment]
There is a setting called `editor.multiCursorModifier` with the default value `"alt"`. It looks like the value is `"ctrlCmd"` in your case.

That is what the setting does; it flips what cmd+click and alt+click do.

**Comment by mrwonko** [comment]
Thanks, that was indeed the case. I must have somehow accidentally enabled that, maybe I autocompleted the wrong thing…
