### ISSUE TITLE
Editing the "condition" or "hitCondition" on a breakpoint results in a remove and add event

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42200]
Editing the "condition" or "hitCondition" on a breakpoint does not preserve the identity of a breakpoint (aka uuid) but results in a remove and then an add event. I would expect to receive a changed event instead (as I do when the enable state changes).

This behaviour is undesirable and surfaces now in the extension API for breakpoints.

**Comment by isidorn** [comment]
Debt -> will tackle in debt week.
Bascially the updateBreakpoints API needs to work both with DebugProtocl.Breakpoint and with the IRawBreakpoint
