### ISSUE TITLE
Shortcut command, "deleteWordRight" is deleting left when at end of line.

### ISSUE THREAD

**Issue by NCA-Bolt** [Microsoft/vscode#4220]
- VSCode Version: 0.10.11
- OS Version: Windows 10 Pro

Steps to Reproduce:

Using the default keyboard shortcut for "ctrl+delete", use the shortcut on text when at the end of the line. The entire line will be deleted.

![1](https://cloud.githubusercontent.com/assets/17713219/13765288/c4a4e37a-eaa7-11e5-9031-810d60f3bd5a.png)
![2](https://cloud.githubusercontent.com/assets/17713219/13765289/c4a79eb2-eaa7-11e5-86b2-990e37b877df.png)

Expected behaviour is that it will shift the previous line up to the cursor if it is at the end of the line.

**Comment by alexandrudima** [comment]
Thank you for filing. Dup of #3882
