### ISSUE TITLE
Feature: key mappings inside terminal

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#42216]
I am a Mac OS user and one iTerm feature that I miss most in the vscode integrated terminal is custom key mappings.  E.g., in iTerm, I map {cmd+left arrow} to home (ie it sends 0x01) and {cmd+right arrow} to end (ie, it sends 0x05).  This creates a much more consistent experience with text editors like vscode where these cmd+left/right arrow map to the start/end of line.

I would love to see the ability to create these mappings in the integrated terminal!

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-docker|Pet|0.0.23
ActiveFileInStatusBar|Ros|1.0.3
gitignore|cod|0.5.0
githistory|don|0.3.6
gitlens|eam|7.5.6
jsonnet|hep|0.0.15
git-tree-compare|let|1.1.4
Go|luk|0.6.73
python|ms-|0.9.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
Ruby|reb|0.16.0
java|red|0.17.0
vscode-open-in-github|sys|1.6.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
vscode-proto3|zxh|0.1.2

---

**Comment by Tyriar** [comment]
This is out for PR https://github.com/Microsoft/vscode/pull/42778

The default keybinding for cmd+left/right may change in the future but you should always be able to customize for this behavior once this gets merged in.

**Comment by josh-tepper** [comment]
Oh excellent.  Looking forward!
