### ISSUE TITLE
VS Code doesn't work after windows force shut down

### ISSUE THREAD

**Issue by is-prime** [Microsoft/vscode#42218]
- VSCode Version: 
>Version 1.19.3
>Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
>Date 2018-01-25T10:36:34.867Z
>Shell 1.7.9
>Renderer 58.0.3029.110
>Node 7.9.0
>Architecture x64
- OS Version: Windows 8.1 x64
- Description: Windows crashed while vs code was running. On reopening VS code's interface doesn't work anymore.
Image: https://imgur.com/a/reYM5
The navbar works but it shows the same page on clicking new window, new folder etc.
Tried restarting the pc, doesn't work.
Steps to Reproduce:

1. Open VS Code
2. Crash Windows

Does this issue occur when all extensions are disabled?: Cannot access settings either

**Comment by mjbvz** [comment]
Can you please try starting VS Code with the `--disable-gpu` command line flag to see if that fixes the problem
