### ISSUE TITLE
Warnings from settings editor are not removed 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42212]
- Open settings editor and make sure you have some warnings in the RHS
- Warnings are displayed in Problems panel
- Close the settings editor

Expected: Warnings in problems panel disappers
Observed: They remain

**Comment by roblourens** [comment]
I can't repro this

**Comment by roblourens** [comment]
Actually it does repro, only in today's build.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/commit/7c272edbda883f2a8141b2434cdab43b3d43d363
