### ISSUE TITLE
Release updates don't restore working files

### ISSUE THREAD

**Issue by jmalonzo** [Microsoft/vscode#4221]
- VSCode Version: 0.10.11
- OS Version: 10.11.13

Steps to Reproduce:

1. Work on a few files to populate the Working Files pane.
2. Don't close/shutdown VSCode whilst you wait for an update.
3. Once an update is available, click 'Update Now'.
4. Code restores the 'Working Files' to the worked files last  time you shutdown Code. 

Expected behaviour: Code should save the session (e.g. Working Files) prior to updating, and restore those Files once it's been updated/restarted due to an update.

**Comment by bpasero** [comment]
this is https://github.com/Microsoft/vscode/issues/172
