### ISSUE TITLE
MacOS version on the official Download page is very old

### ISSUE THREAD

**Issue by gertjan-carbon** [Microsoft/vscode#42213]
- VSCode Version: #NA 
- OS Version: MacOS any version

Steps to Reproduce:

1. Got to https://code.visualstudio.com/download
2. Download MacOS version
3. Get 25/10/2017 version.

As all my users run without admin credentials, they get popups all the time to install the update helper.
I'll need to repackage the version currently after updating it on an admin console and that is a sloppy solution.

**Comment by gertjan-carbon** [comment]
https://go.microsoft.com/fwlink/?LinkID=620882
gives a 302 to:
https://vscode-update.azurewebsites.net/latest/darwin/stable
gives a 302 to:
https://az764295.vo.msecnd.net/stable/7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba/VSCode-darwin-stable.zip
Which unpacks and contains the build from late October.

**Comment by octref** [comment]
@gertjan-carbon The exact zip file unzips to this to me...

![image](https://user-images.githubusercontent.com/4033249/35646723-f96244fe-0684-11e8-8c32-bba4478d86cb.png)

If you run `shasum -a 256 VSCode-darwin-stable.zip` and it gives out this:
```
0fbc3c63d5a6e9a44908c3b018bedb35b8d1b750c2e8dd08b65401ec4fda73a7  VSCode-darwin-stable.zip
```

Then that's our stable build 1.19.3 released on Jan, 25, 2018.

How were you unzipping and installing it after you download the Zip?

**Comment by gertjan-carbon** [comment]
By default the Mac just unzips it for you in the downloads folder. For some reason this was still the old version.
After going through the whole process on the command line, it is now showing the 1.19.3 version indeed.
I have never know the Mac to cache old versions... or in the last 2 days the file has indeed changed. I didn't verify the version yesterday as it was still showing the old date after unzipping. 
..
