### ISSUE TITLE
merge window does nothing but killed the other window

### ISSUE THREAD

**Issue by ryenus** [Microsoft/vscode#42211]
- VSCode Version: 1.19.3
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. open vscode, then open another separate vscode window
2. try **Window (menu) > Merge All Windows**

**Expected**: the two windows are merged and can be switched using the window bar above the tab bar.

**Actual**: the window bar is blank, and clicking it doesn't make the switch

![image](https://user-images.githubusercontent.com/610161/35450603-73f50414-02fb-11e8-8361-16eded35e1df.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35361
