### ISSUE TITLE
Annoying info message "Please remove the 'code' alias from '/Users/<user>/.bash_profile"

### ISSUE THREAD

**Issue by fbertin** [Microsoft/vscode#4222]
- VSCode Version: 0.10.11
- OS Version: MacOS X El Capitan (v10.11.3)

Steps to Reproduce:

1. After having updated my Visual Studio Code app I'm always having this info message on the top and even if I update my .bash_profile file it continues with this message in an endless loop!

**Comment by joaomoreno** [comment]
Sorry for that @fbertin. Can you show me your `.bash_profile`? Maybe I can pinpoint the line number that makes it popup that message.

Also, #4169 might help you.

**Comment by fbertin** [comment]
Hi @joaomoreno! You're right, #4169 helped me to solve the problem! Thanks for your help!

**Comment by joaomoreno** [comment]
Alright, closing as a duplicate of #4169
