### ISSUE TITLE
Scrolling horizontally moves cursor instead of moving the screen

### ISSUE THREAD

**Issue by samirm** [Microsoft/vscode#42223]
Every time I try to scroll my windows horizontally it moves the cursor instead of scrolling. Did not find any setting to change this.

- VSCode Version: 1.19.3
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
How are you attempting to scroll horizontally? Are you holding a key down?

**Comment by mjbvz** [comment]
Weird. Does this also happen in other apps  too or only in VS Code? Also, is screen reader more enabled by-chance? This would be indicated in the status bar

**Comment by samirm** [comment]
Screen reader mode is not enabled and this only happens in VS Code out of all the programs I use.

I've been playing around with this and discovered some more strange behaviour. If I toggle word wrap, my horizontal scroll bar disappears and scrolling horizontally still moves the cursor instead of the screen. However, if I try scrolling horizontally in Notepad (with word wrap disabled), everything works as expected. But if I turn word wrap on, then the cursor starts moving instead of the screen in Notepad.

I can't tell you whether the scroll bar disappears in VS Code with word wrap enabled or disabled since it doesn't seem to do anything other than disappear my scroll bar.

I don't think it should make any difference, but the file I'm trying to scroll in VS Code is a TypeScript (.ts) file.

**Comment by alexandrudima** [comment]
Duplicate of #17476
