### ISSUE TITLE
Make process of finding styling errors in vscode build easier

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#42220]
- [ ] Make hygiene to show the **line/column** where errors occurred
- [ ] Add more `TSLint` rules - preferably the ones that have `--fix` flag
- [ ] Add a linter for `CSS` 

Also, if you format this code (which passes hygiene):
```ts
export class KeybindingsEditorInput extends EditorInput {
	constructor( @IInstantiationService instantiationService: IInstantiationService) {
		super();
		this.keybindingsModel = instantiationService.createInstance(KeybindingsEditorModel, OS);
	}
}
```
It removes the whitespace before `@` aaaaand now hygiene fails... 😅

**Comment by joaomoreno** [comment]
Hygiene shows the line, that should be enough for most of it.

We can add selective TSLint rules that we decide as a team to use.

CSS lint would be cool. But it's not something we really suffer from.

You must format code using the formatting rules configured in the project. Our formatter has exactly the same rules as our hygiene checker. If you use VS Code to format, that space will stay. Maybe @mjbvz knows why.

**Comment by usernamehw** [comment]
@joaomoreno, sorry, but I can't find how to get a line where format is failing.

Precommit hook is giving a link to file but no line number (clicking on it will use latest cursor position):
![precommit](https://user-images.githubusercontent.com/9638156/35510460-379db546-0509-11e8-881a-e84459275cfc.png)

I even executed `gulp hygiene` on the entire project, but got the same thing.

**Comment by joaomoreno** [comment]
Oh yeah... maybe for the formatter you can't. But you don't have to. If you open that file in Code and run `Format Code`, it will just do the right thing. In the team we usually have `editor.formatOnSave: true`.
