### ISSUE TITLE
Bottom Output panel keeps opening on startup

### ISSUE THREAD

**Issue by mccreeker** [Microsoft/vscode#42222]
- VSCode Version: 1.19.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Close the empty Output panel at the bottom (it's not named anywhere).
2. Close VS Code.
3. Open VS Code.
4. Notice the bottom panel with tabs Problems, Output, Debug Console, Terminal is open AGAIN, obscuring the bottom 3rd of your code.

![image](https://user-images.githubusercontent.com/33667567/35458672-81fb1f82-029a-11e8-92c6-d9718bd49fc1.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@mccreeker I can not reproduce this.
Do you aslo see this with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by mccreeker** [comment]
It stopped doing it, not sure why.
