### ISSUE TITLE
VS Code make an audible "beeb-beep" when I save or use [ctrl-s] 

### ISSUE THREAD

**Issue by ilennert** [Microsoft/vscode#42224]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
svn-scm|joh|1.8.0
csharp|ms-|1.13.1
vscode-docker|Pet|0.0.23

---

Steps to Reproduce:
I just save my work with the ctrl-s key sequence

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Does this still happen if you disable all extensions and restart VS Code?

**Comment by ilennert** [comment]
Yes, in fact, I also updated it after disabling the extensions and it still does it.  If I could just somehow disable it without disabling all my sounds...

**Comment by ilennert** [comment]
I have determined, it is not VS Code but, the Angular CLI, ng serve that is causing the beeping.  Sorry to post it here...

**Comment by mjbvz** [comment]
Thanks for the update. Closing as external
