### ISSUE TITLE
task.json is not update until vscode reload

### ISSUE THREAD

**Issue by BenoitValdes** [Microsoft/vscode#42226]
### Issue Type
Bug

### Description

Hi,

I am make a python program that use arguments to work. Each time I want to change the argument through the task.json build task, I have to reload vscode else the changes are not took in acount.

I hadn't this issue at work (at work I am usin OSX maybe that's the difference)

Regards

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (89264676133f25c4990706c889a48eab277544f7, 2018-01-26T05:15:09.585Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3593)|
|Memory (System)|15.95GB (9.17GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.1
QML|bbe|1.0.0
clarissecomandport|Ben|0.5.0
python|ms-|0.9.1
datetime|rid|1.0.5
vscode-icons|rob|7.19.0
indenticator|Sir|0.4.2

(1 theme extensions excluded)

</details>

**Comment by bvaldes** [comment]
6 month later it works for me too. Thanks

**Comment by dbaeumer** [comment]
Sorry for the delay. Happy to hear it works for you :-)
