### ISSUE TITLE
Code Helper is using older versions of Node than the one installed on a system

### ISSUE THREAD

**Issue by hiredgun** [Microsoft/vscode#42227]
- VSCode Version: 1.19.3 (1.19.3)
- OS Version: 10.13.3

I encountered a problem today with my eslint complaining that "Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (54)". After debugging I found out that during installation, npm creates node binding for node-sass. This binding is created based on [MODULE_RUNTIME_VERSION](https://nodejs.org/en/download/releases/)  of currently installed Node which in my case is 59 since I have Node 9.4.0 installed on my mac. As you can see, the version reported by eslint is 54. 

The reason why eslint reports above error is that I'm using Webpack's [module resolution](https://webpack.js.org/concepts/module-resolution/) to import components with shorter paths (e.g 'components/fooo' instead of '../../../components/foo'). In order to tell eslint that this is a correct import, I need to use [eslint-import-resolver-webpack](https://www.npmjs.com/package/eslint-import-resolver-webpack) plugin which is using webpack.config.js file to configure eslint based on resolve section included in webpack's config file. Since I have some sass plugins configured in my webpack.config.js file, while eslint-import-resolver-webpack is trying to load weback's config file it encounters above error with unsupported runtime (54).

The error is thrown in node-sass lib [here](https://github.com/sass/node-sass/blob/master/lib/binding.js#L13) becasue [this line](https://github.com/sass/node-sass/blob/master/lib/extensions.js#L202) returns `54` from `process.versions.modules`.  

I decided to debug process:
```js
console.log(process.execPath, process.versions);
```
and got this:

```js
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper 
{ 
  http_parser: '2.7.0',
  node: '7.9.0',
  v8: '5.8.283.38',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '54',
  openssl: '1.0.2k' 
}
```
As I can see, the whole process described above is triggered by eslint task and the output from console.log is displayed in output window everytime I open new js file in vs code.

On my mac I have node 9.4.0 and the same console.log returns:

```js
/Users/agent47/.nvm/versions/node/v9.4.0/bin/node 
{ 
  http_parser: '2.7.0',
  node: '9.4.0',
  v8: '6.2.414.46-node.17',
  uv: '1.18.0',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.29.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' 
}
```

As you can see modules number, node version and exec path are different. 

My node-sass installed by npm have binding only for `darwin-x64-59` runtime so while eslint is trying to resolve paths using webpack's config it looks for `darwin-x64-54` which is not available.

Is this expected behaviour that eslint task executed by VS Code have  execute path 
 set to `Code Helper`and node and modules version different from the one I have installed on my os?

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/345
