### ISSUE TITLE
[Question] Are VSCode users affected by this failure of Electron?

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#42221]
- VSCode Version: 1.19.3 e 1.20.0-insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Is the most current version of VSCode and VSCode - Insiders affected by this failure? Especially for Windows users.

https://electronjs.org/blog/protocol-handler-fix

Sorry for the silly question, but I did not find anything like it here, looking for the "electron-update" and "electron" labels.

Anyway, thanks for the info.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The 1.19.2 update already fixed this: https://code.visualstudio.com/updates/v1_19

**Comment by Tekbr** [comment]
@mjbvz Thanks!!
