### ISSUE TITLE
Cannot hide explorer arrows

### ISSUE THREAD

**Issue by PKief** [Microsoft/vscode#42238]
### Issue Type
Bug

### Description

In the latest insider version of VSCode I'm not able to hide the arrows before the folder icons in the explorer.

The following config only removes the margin of the file icons but it does not hide the arrows before the folder icons:

```json
"hidesExplorerArrows": true
```

With this config it now looks like this:

<img src="https://user-images.githubusercontent.com/12248527/35470475-74058470-034a-11e8-8a52-3a76c99436db.png" alt="image" width="200px"/>

But it should behave like this (*not showing any arrows*):

<img src="https://user-images.githubusercontent.com/12248527/35470491-ab820dba-034a-11e8-97e3-1564d153ddb8.png" alt="image" width="200px"/>

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (89264676133f25c4990706c889a48eab277544f7, 2018-01-26T05:15:09.585Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icon-theme|jtl|1.6.1
vscode-simple-icons|Lau|1.8.0
material-icon-theme|PKi|3.2.1
seti-icons|qin|0.1.3
vscode-icons|rob|7.19.0

</details>

**Comment by jens1o** [comment]
This also affects `vscode-icons`.

**Comment by bpasero** [comment]
@sandy081 maybe from your changes?
