### ISSUE TITLE
Cannot launch program 'e:\path\to\program.ts'; setting the 'outDir or outFiles' attribute might help.

### ISSUE THREAD

**Issue by Shyam9553** [Microsoft/vscode#42235]
- VSCode Version: 1.12.1
- OS Version: Windows 8.1 Pro 32-bit

Steps to Reproduce:
1. I really don't have idea

Whenever I try to debug my TypeScript program, I always get error  **Cannot launch program 'e:\path\to\program.ts'; setting the 'outDir or outFiles' attribute might help.**

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}",
            "outFiles": [
                "${workspaceRoot}/out/*.js"
            ]
        }
    ]
}
```

@weinand

**Comment by mjbvz** [comment]
Are you really on VS Code 1.12? If so, please upgrade to 1.19  and let me know if you still run into this issue

**Comment by weinand** [comment]
@Shyam9553 did you verify that there is a transpiled *.js file in your workspace's "out" directory?

**Comment by Shyam9553** [comment]
@weinand there is no transpiled *.js file and i am using Node 9.4.0

**Comment by weinand** [comment]
You will have to transpile TS to JS yourself as the debugger doesn't do this.
Please see https://code.visualstudio.com/docs/languages/typescript#_transpiling-typescript-into-javascript
