### ISSUE TITLE
Terminal output can block the renderer process

### ISSUE THREAD

**Issue by wkrueger** [Microsoft/vscode#42234]
- VSCode Version: 1.19.3
- OS Version: win 10 1709

Steps to Reproduce:

1. Have a decently big project
2. F1 + run build task + tsc watch
3. Hit CTRL+S
2. Try to scroll any window while the issue list rolls (in my case it is a big issue list)
3. Any editor interaction gets UI blocks while parsing is taking place. Since parsing may occur frequently, this can become annoying.

EDIT: 
 - Might be related to having a big issue list?

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
By parsing, do you mean the syntax highlighting / colorization? How large is your file in terms of line account and file size?

**Comment by wkrueger** [comment]
By parsing I mean the whole edit cycle (edit > save > TS parsed and emits error list > editor reads list and maps it to marks)

I've been playing with an open sourced react project. Cloned it and renamed everything to .ts and .tsx
It's about ~1500 small files, which render an huge TS compiler error list with ~10k errors.

(ok, 10k problems is something that wouldnt happen in "real-life" projects, so I'd leave this just as a performance improvement suggestion)

So I guess that the UI blocks happen while the editor is parsing the TS output? That would apply to any other problem checkers?

**Comment by mjbvz** [comment]
Please share an example file or small project that demonstrates this problem

**Comment by wkrueger** [comment]
https://github.com/wkrueger/WoWAnalyzer

I just forked this js project for the issue (git cloned with --depth=1), renamed everything to tsx and added a tsconfig, which brings a 10k+ issue list.

  - Run build task > tsc: watch
  - Find any file big enough for scrolling i.e. `src/Main/App.tsx`
  - Hit CTRL/CMD + S, try to scroll while the error list is rolling

![gif](https://i.imgur.com/ST4tC1f.gif)

**Comment by Tyriar** [comment]
All terminal work is on the renderer process at the moment, I'd like to eventually move that to a web worker. Tasks also does a bunch of extra work checking every line with regexes and registering problems against them which could contribute to this.

**Comment by Tyriar** [comment]
Upstream https://github.com/xtermjs/xterm.js/issues/1515

**Comment by Tyriar** [comment]
Looks like this actually can be fixed by https://github.com/Microsoft/vscode/issues/53974 🎉

**Comment by Tyriar** [comment]
Fixed by https://github.com/Microsoft/vscode/issues/53974, https://github.com/Microsoft/vscode/pull/54090
