### ISSUE TITLE
VSCode with Babel plugins?

### ISSUE THREAD

**Issue by babakness** [Microsoft/vscode#42233]
I have this question posted on stackoverflow as well

https://stackoverflow.com/questions/48472212/visual-studio-code-and-babel-plugin

- VSCode Version: 1.19.2 
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Install Babel 7 w/ plugin-proposal-pipeline-operator
2. Use new syntax in Javascript file.
3. Notice pipe operator underlined in red

Is it possible have webpack/babel produce sourcemaps which are used if a error is detect post compile?

**Comment by mjbvz** [comment]
Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by babakness** [comment]
Yeah I did but no response as of yet:

https://stackoverflow.com/questions/48472212/visual-studio-code-and-babel-plugin

I'll keep it in mind though, didn't mean to bother. Maybe its not possible and could be made a feature request? Thanks.
