### ISSUE TITLE
Can open two settings editors that share a default settings editor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42230]
We create a unique uri for the default settings editor each time it's opened, but "Split Editor" actually bypasses this, and will clone the current editor. Then there are two default settings editors open which point at the same model.

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorActions.ts#L103

Not sure whether it's possible to get around this.

cc @sandy081

**Comment by sandy081** [comment]
Yah tricky one. Let me think about it.
