### ISSUE TITLE
Upgrade on MacOS not working

### ISSUE THREAD

**Issue by andrewssi** [Microsoft/vscode#42231]
- VSCode Version: 1.17.2 
- OS Version: Mac OS 10.13.2

Steps to Reproduce:

1. Run 'Check for updates' from 'Code' menu
2. See error message "Could not create temporary directory: Permission denied"
3. Same problem when run with `code --disable-extensions` 

* VMWare Airwatch is installed, which may be the issue (but not for certain)
* Running as System Administrator. Installed as System Administrator
<img width="903" alt="screen shot 2018-01-27 at 1 05 13 pm" src="https://user-images.githubusercontent.com/14302060/35467569-1fd19942-0364-11e8-9098-12926b6fc456.png">

**Comment by andrewssi** [comment]
I tried running 'sudo Code' from the command line. Interestingly I didn't get an error message and it seemed to complete, but the upgrade didn't happen after Code was restarted.

**Comment by mjbvz** [comment]
Let us know if the problem happens with the next update

**Comment by andrewssi** [comment]
Hi @mjbvz - version 1.19 has exactly the same problem when updating. I couldn't reopen, therefore raised as new : #43793
