### ISSUE TITLE
Selenium WebDrive auto compilation works only when other file open

### ISSUE THREAD

**Issue by Lagistos** [Microsoft/vscode#42239]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.0.15
angular2-switcher|inf|0.1.4
Angular-BeastCode|Mik|5.2.2
hg|mrc|1.2.3
cpptools|ms-|0.14.6
debugger-for-chrome|msj|4.1.0
angular2-inline|nat|0.0.17
vscode-icons|rob|7.19.0
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

So i use selenium webdriver js with typescript,
i wrote some code and the auto compilation works only when the index.js in the seleium folder in the node_ modules is open, and when i close it the auto compilation stop working

when i stoped using typescript and move to vanila javascript the autocompilation worked perfectly

The code `
import { Builder, By, Key, promise, until } from 'selenium-webdriver';
const driver = new Builder().forBrowser('firefox').build();
`

Thanks

**Comment by mjbvz** [comment]
Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
