### ISSUE TITLE
[IntelliSense] [Salsa] doesn't recognize JSDoc callback parameter

### ISSUE THREAD

**Issue by santiagohdzb** [Microsoft/vscode#4223]
Hi everyone, I'm in love with the new VS Code's Salsa, but I'm facing this issue:

![asasdadasd](https://cloud.githubusercontent.com/assets/8533075/13767114/bc11993e-ea24-11e5-8eb2-a6e37ee5ce8d.png)

![asasdadasd](https://cloud.githubusercontent.com/assets/8533075/13767230/b1b0ae0c-ea25-11e5-8b8b-54c139354766.png)

I'm trying to use InselliSense with [JSDoc](http://usejsdoc.org/tags-param.html#callback-functions)'s callback documentation.

Am I doing something wrong? How am I supposed to do this?

- VSCode Version: 0.10.11
- OS Version: Win 10

Steps to Reproduce:
    1. Open a new Javascript file
    2. add the code you see above

**Comment by anseki** [comment]
Hi @santiagohdzb,
Now, it seems that IntelliSense indicates some types other than primitive data type and `Object` as `any`.
Some types of JavaScript's built-in-object (e.g. `Date`, `RegExp`, etc.) are recognized, but some types (e.g. `Array`, `Map`, etc.) are not.
https://github.com/Microsoft/vscode/issues/3802

**Comment by egamma** [comment]
Moving to TypeScript for investigation.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7515
