### ISSUE TITLE
format

### ISSUE THREAD

**Issue by xiaorong61** [Microsoft/vscode#42246]
C 语言右键格式化后缩进为 4 格，
而编辑器右下角所显示的缩进默认为 2 格，
很不协调。

https://translate.google.com/#auto/en/C%20%E8%AF%AD%E8%A8%80%E6%A0%BC%E5%BC%8F%E5%8C%96%E5%90%8E%E7%BC%A9%E8%BF%9B%E4%B8%BA%204%20%E6%A0%BC%EF%BC%8C%0A%E8%80%8C%E7%BC%96%E8%BE%91%E5%99%A8%E5%8F%B3%E4%B8%8B%E8%A7%92%E6%89%80%E6%98%BE%E7%A4%BA%E7%9A%84%E7%BC%A9%E8%BF%9B%E9%BB%98%E8%AE%A4%E4%B8%BA%202%20%E6%A0%BC%EF%BC%8C%0A%E5%BE%88%E4%B8%8D%E5%8D%8F%E8%B0%83%E3%80%82

**Comment by mjbvz** [comment]
Please post repo steps. A gif or screenshots showing the problem would also be helpful
