### ISSUE TITLE
[V-test][GO] Getting error message like "Error: Type Error: Bad argument" when opening a folder containing GO code.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4224]
- VSCode Version: Windows10
- OS Version:

Steps to Reproduce:

1. Install go from this location:https://visualstudiogallery.msdn.microsoft.com/bd7675ba-1bf5-4395-8c5a-4fc19dfc0d76  
2. Create directory structure and set environment variable for GOPATH, GOBIN. by following instruction provided at : https://golang.org/doc/install?download=go1.6.windows-amd64.msi 
3. Now add a .go file under workspace dir and execute below command to generate a EXE under GOBIN file.
4. Once exe is generated successfully, open the workspace folder in VSCODE.
5. Open go file and install GO extension.
6. Verify extension installed successfully without any error.
6. Verify GOPATH error should not be displayed as environment variables are already been set.

Actual: Getting error message "Error : Type Error: Bad argument".
![image](https://cloud.githubusercontent.com/assets/17735796/13767376/d3d11480-ea26-11e5-9b37-1d0e264ecd00.png)

Expected: There should not be any error message like this.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-go#246
