### ISSUE TITLE
Improve documentation for `typescript.tsdk` to make workspace usage clearer

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#42243]
The `typescript.tsdk` setting is documented as follows:

```
Specifies the folder path containing the tsserver and lib*.d.ts files to use.
```

Given the name of this setting and its corresponding documentation, if this setting is specified in workspace settings, it's reasonable for a user to expect for VSCode to begin using that TS version.

However, that is not the case. In addition to this step, the user must manually configure the TypeScript version through the UI. https://code.visualstudio.com/docs/languages/typescript#_using-the-workspace-version-of-typescript

![](https://code.visualstudio.com/assets/docs/languages/typescript/select-ts-version-message.png)

I understand this additional opt-in step is required for security reasons, as detailed in https://github.com/Microsoft/vscode/issues/30069#issuecomment-312732928.

However I would like VSCode to make this requirement clearer. The documentation for `typescript.tsdk` should make it clear that VSCode will not automatically use the specified version and additional steps are required.

As part of this I also think the relationship between the `typescript.tsdk` setting and the UI's TypeScript version controls could be a lot clearer. After playing around with the setting, I was eventually able to infer that `typescript.tsdk` defines the "global" or "workspace" TypeScript version (depending on whether it's a user or workspace setting) as seen in the UI's TypeScript version picker. The current documentation for `typescript.tsdk`, however, suggests that it simply sets the TypeScript version—with no mention of the required additional steps.

**Comment by marcobeltempo** [comment]
I am interested in working on this issue.  

@mjbvz Do you suggest implementing a prompt after confirming `tsdkVersion` was set?
[vscode/extensions/typescript/src/utils/versionProvider.ts](https://github.com/Microsoft/vscode/blob/c168e385ef9519dbdb7c110a04279f0f2b972ab2/extensions/typescript/src/utils/versionProvider.ts#L41-L48)
```ts
		// Allow TS developers to provide custom version
		const tsdkVersion = workspace.getConfiguration().get<string | undefined>('typescript.tsdk_version', undefined);
		if (tsdkVersion) {
			return API.fromVersionString(tsdkVersion);
		}
		return undefined;
	}
```

**Comment by mjbvz** [comment]
@marcobeltempo Sure. I personally think the "prompt when the workspace has a typescript.tsdk" would be the more useful of the two. We actually used to have this logic but removed it.

 Two considerations:

- The prompt/notification should only happen if there is a workspace tsdk setting. 
- The prompt/notification should only happen once per workspace. Use a `workspaceState: Memento` to track this

The prompt used to happen when we started the tsserver itself: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptServiceClient.ts#L336 You'd probably want to look at the `VersionPicker` class too  for implementing this. Let me know if you need some additional pointers or if you have any questions

**Comment by marcobeltempo** [comment]
@mjbvz  if the workspace `"typescript.tsdk"` is set, do we want the check to happen on startup...
1.  only if the bundled version is being used
2.  if the local version us being used, should we display an information message?
3. check to see if the workspace `"typescript.tsdk"` is set at any point after startup and display an appropriate message

**Comment by jedrichards** [comment]
Furthermore, although out of scope of this ticket, shouldn't the presence of a local `typescript` module in `node_modules` also be seen as a reason to prompt the user to use that TypeScipt version?

**Comment by ryardley** [comment]
After update the Typescript tsdk setting appears to not be valid in version 1.32.1 macOs. I assume this affects this issue. 

![image](https://user-images.githubusercontent.com/1256409/54169558-3fbc5a80-44c7-11e9-8a43-6af5f14a9f62.png)

**Comment by ryardley** [comment]
So it appears I had a borked vscode setup. I had to totally reinstall to fix another issue. Please ignore the above.

**Comment by Svish** [comment]
This seriously needs to be fixed... I honestly thought adding the `typescript.tsdk` to my `.vscode/settings.json` was how to make VS Code use the correct version of Typescript. Only discovered today, pretty much by accident, when looking in the Typescript Output console that it was actually "Using tsserver from: wrong path". Tried searching in the settings thing on how to switch, but nothing there. Having to manually click on a tiny number in the status bar, that I didn't even know was there, is not exactly an obvious mechanic...

I don't understand why VS Code can't just automatically switch to using the given typescript version if it is specified in the workspace settings? But if for some reason it can't do that, there _needs_ to at least be _some_ sort of prompt/notification. "Hey, you just added the `typescript.tsdk` to `settings.json` / opened a workspace with `typescript.tsdk` defined; Would you like me to completely ignore it like I have all these months, or to actually use it?"

**Comment by mjbvz** [comment]
Prompting is now being tracked by #65546. That issue also explains why we can't execute code in your workspace automatically

Besides expanding the in product tsdk setting documentation with e5efdb4b4b59db8b03b9f0984ae149772b4a998f, I made a quick pass improving our website docs around this: https://github.com/microsoft/vscode-docs/commit/22b8efbaee78cfbbd597a3c6e2452c709a630bc5

If you still feel the documentation could be clearer, please just submit a PR. You can use the two changes I linked to to see what files you need to edit
