### ISSUE TITLE
files.insertFinalNewline and files.trimFinalNewlines does not work in certain file extensions

### ISSUE THREAD

**Issue by azrinaziz** [Microsoft/vscode#42241]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.4
php-intellisense|fel|2.2.5
cpptools|ms-|0.14.6
material-icon-theme|PKi|3.2.1

---

User Settings:

```
{
    "editor.fontFamily": "'Fira Code', Consolas, monospace",
    "editor.fontSize": 13,
    "editor.fontLigatures": true,
    "editor.lineHeight": 21,
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Tomorrow Night Blue",
    "files.autoGuessEncoding": true,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "explorer.sortOrder": "type",
    "window.menuBarVisibility": "toggle",
    "material-icon-theme.folders.theme": "specific",
    "material-icon-theme.folders.color": "#fdd835",
    "php.suggest.basic": false,
    "php.validate.enable": true,
    "php.validate.run": "onSave",
    "php.validate.executablePath": "E:/Dev/wamp64/bin/php/php7.1.11/php.exe",
    "php.executablePath": "E:/Dev/wamp64/bin/php/php7.1.11/php.exe",
    "C_Cpp.clang_format_fallbackStyle": "WebKit",
    "eslint.autoFixOnSave": true
}
```

Steps to Reproduce:

1. Create any ```php``` and ```txt``` files.
2. Write some code, press ```enter``` several times,  and save it.
3. Look at the endline.
4. Works fine on ```html```, ```js```, ```c```, and ```cpp``` source files.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Can you please try this in [the latest insiders builds](https://code.visualstudio.com/insiders/) and let me know if you still see this issue

**Comment by azrinaziz** [comment]
The bug was fixed in the latest insider builds. Closing this issue. Thank you.
