### ISSUE TITLE
Unwanted search keyword synchronization between multiple panes for the same file.

### ISSUE THREAD

**Issue by puruzio** [Microsoft/vscode#42252]
- VSCode Version: 1.19.3
- OS Version: MACOS 10.13.2

Steps to Reproduce:

1. Open any text file in two panes/windows side by side.
2. In the left pane, search for a word and keep the search bar open
3. In the right pane, search for a different word and keep the search bar open
4. Click anywhere on the left pane. VS code synchronizes the search keyword based on the one from the right pane, and as a result, the cursor jumps to the first line of code where it finds that (changed) keyword. 

The desired result is for there to be no search keyword synchronization.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
You can turn in off by setting `editor.find.globalFindClipboard` to `false`.
