### ISSUE TITLE
Reindent Lines stopped working after 1.19

### ISSUE THREAD

**Issue by narutse** [Microsoft/vscode#42250]
- VSCode Version: 1.19.x
- OS Version: Ubuntu 17.10, Windows 10

I used to bind Reindent Lines (editor.action.reindentlines) to a key, which would put the current line at the correct indentation (for C++, but I've tested with other languages as well). However, after version 1.19, this feature stopped working. I tried using ctrl+shift+p and enter the command and it also fails. Format Document/Selection still works, but it rearranges my curly braces and requires either selection or affects the whole documents. (I don't intend either effect.)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rebornix** [comment]
If I remember correctly, C++ extension disabled indentation rules as those rules can't cover different code styles for indentation.
