### ISSUE TITLE
Tab won't add indentation when acceptSuggestionOnEnter

### ISSUE THREAD

**Issue by MonFig** [Microsoft/vscode#42256]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
js-file-header|arj|0.0.1
color-info|bie|0.5.0
apex-autocomplete|chu|0.2.13
vscode-eslint|dba|1.4.4
FreeMarker|dco|0.0.9
githistory|don|0.3.8
vscode-babel-coloring|dza|0.0.4
gitlens|eam|7.5.7
react-native-react-redux|EQu|1.4.1
auto-close-tag|for|0.5.5
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.15
code-runner|for|0.8.7
vscode-power-mode|hoo|2.1.0
path-autocomplete|ion|1.8.1
vscode-csharp-snippets|jor|0.2.0
markdown-shortcuts|mdi|0.8.1
vscode-language-babel|mgm|0.0.12
vscode-fileheader|mik|0.0.2
vscode-autoprefixer|mrm|2.1.2
python|ms-|0.9.1
cpptools|ms-|0.14.6
sublime-keybindings|ms-|3.0.3
short-js-doc|mya|0.1.10
color-highlight|nau|2.3.0
vetur|oct|0.11.6
vuehelper|oys|0.1.0
vscode-icons|rob|7.19.0
vue-vscode-snippets|sdr|1.3.0
require-complete|sen|0.1.0
background|sha|1.1.17
code-settings-sync|Sha|2.8.7
addDocComments|ste|0.0.8
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)
---

`Tab` key won't add indentation when `"editor.acceptSuggestionOnEnter": "on"`, I'm afraid that it's a key-bindings conflicting bug, and it never happend in older versions.

Steps to Reproduce:

1. set `"editor.acceptSuggestionOnEnter": "on"` in user-settings
2. Expect to see new indentations been added when `tab` key pressed, and format new html elements when cursor's after something like `div`.
3. But in fact, though the second half is shown as expected，**no new indentations been added.**
4. I think this is a really normal demand, and it works fine in VS Code of older-versions and sublime text. If you would fix this issue, please let me know.
Appreciate it.

Reproduces without extensions: Yes/No
Yes

**Comment by mjbvz** [comment]
So this still occurs when you disable all extensions and restart VSCode? You can also start code with the `--disable-extensions` command line flag to check if disabling extensions fixes this
