### ISSUE TITLE
Cannot scroll with mousewheel if inside integrated terminal and using less/screen/vim 

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#42254]
```
$ code --status
Version:          Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
OS Version:       Darwin x64 16.6.0)
```

1. `less somefile.txt`
2. Use mouse pad / mousewheel to scroll. Doesn't work. Key up / down works, but mousewheel doesn't

This works inside the native mac osx terminal just fine.

Basically integrated terminal needs to **sends arrow keys when in alternate screen mode when mouse scrollup/scrolldown events are fired**

Integrated terminal breaks usability of  screen / less / vim e.t.c

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/426

**Comment by Tyriar** [comment]
Thanks @nojvek, I've wanted this fixed for a while I just wasn't 100% sure what to do. I made it end up/down when the buffer has no scrollback (like the alt buffer).
