### ISSUE TITLE
in strings files, CSS error is occur

### ISSUE THREAD

**Issue by readingsnail** [Microsoft/vscode#42262]
- VSCode Version:1.20.0-insider(1.20.0-insider), ed4c237467bfe7c37b173da782cb65e333484a13
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Mac's application translation files (using strings) is open
2. and watch error message - css
<img width="1329" alt="2018-01-28 9 36 32" src="https://user-images.githubusercontent.com/1904967/35477787-ee772366-040e-11e8-8d74-bc30e5aa0997.png">

3. [additional] if available, add to 'open to' application. VS Code is awesome, but always drag and drop. so i wanna easily open to document or else

Does this issue occur when all extensions are disabled?: Yes/No
[exmaple strings.txt](https://github.com/Microsoft/vscode/files/1670670/exmaple.strings.txt)

**Comment by mjbvz** [comment]
This is caused by one of your extensions, likely one for auto completing css class names. You should be able to open the VS Code developer tools by running the `Developer: Toggle Developer tools` command in vscode to find more information about the error

Please file the issue against whichever extension is causing this

**Comment by readingsnail** [comment]
<img width="1062" alt="2018-01-28 6 15 29" src="https://user-images.githubusercontent.com/1904967/35480693-42466ea0-0457-11e8-8247-4e4d904113f5.png">

So 2913 columm Code is here (workbench.main.js:2913)
return e===a.Severity.Error&&console.error(i.toErrorMessage(t,!0)),this.handler.showMessage(this.toBaseSeverity(e),t,n)},e.prototype.hideAll=function(){this.handler&&this.handler.hideMessages()},e.prototype.confirm=function(e){var t=e.message;return e.detail&&(t=t+"\n\n"+e.detail),c.TPromise.wrap(window.confirm(t))},e.prototype.confirmWithCheckbox=function(e){return this.confirm(e).then(function(e){return{confirmed:e,checkboxChecked:!1}})},e.prototype.dispose=function(){this.toDispose=s.dispose(this.toDispose)},e}();t.WorkbenchMessageService=l}),define(l[1215],u([0,1,749,79,4,1214,20,10,30,21,51,60]),function(e,t,n,i,r,o,s,a,c,l,u,h){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var p=function(e){function t(t,n,i){var r=e.call(this,t,i)||this;return r.windowService=n,r}return d(t,e),t.prototype.confirmWithCheckbox=function(e){var t=this.massageMessageBoxOptions(this.getConfirmOptions(e));return this.windowService.showMessageBox(t).then(function(e){return{

**Comment by mjbvz** [comment]
Yes this issue is coming from the `html-css-class-completions` extension as shown in the error message
