### ISSUE TITLE
Closing preferences dirty reopens it in some cases

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42268]
### Issue Type
Bug

### Description

1. open settings
2. make it dirty
3. close settings (do not save)

=> settings editor opens again

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (ed4c237467bfe7c37b173da782cb65e333484a13, 2018-01-26T06:08:15.259Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.59GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.5
close-all|ben|1.0.2
vscode-eslint|dba|1.4.4
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.22
vsc-travis-ci-status|fel|1.1.0
ayu|tea|0.12.0
vscode-open-in-github|ziy|1.3.1

(14 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Do you have autosave enabled? I can repro with any file using these steps, but not sure if it's the same:

- `"files.autoSave": "onFocusChange"`
- Open any file. Type something.
- cmd+w
- Save dialog pops up. While it's open, the file autosaves.
- Press "Don't save"
- File does not close. :bug:

Is this like what you're seeing? If not please record a gif or something.

**Comment by bpasero** [comment]
Weird I cannot reproduce anymore. However I see something is weird when auto save is on focus change: 
* have a dirty file
* close it
* the file gets saved in the background
* the file does not close

@roblourens is that what you saw?

**Comment by roblourens** [comment]
That sounds like what I was describing, although I saw the "Do you want to save?" dialog and clicked "Don't save"

**Comment by bpasero** [comment]
@roblourens what I saw is different though (not having auto save enabled):
* open settings
* make a change
* close settings
* "do not save" in dialog

=> settings editor closes briefly and then comes back again

**Comment by roblourens** [comment]
I haven't been able to repro that.

**Comment by sandy081** [comment]
I cannot reproduce it either

**Comment by bpasero** [comment]
@roblourens @sandy081 looks like it only reproduces if the settings editor is opened in group 2 or 3, can you try?

**Comment by roblourens** [comment]
Still can't repro

**Comment by bpasero** [comment]
@roblourens @sandy081 also seems to be related to having a search input in the search which seems to trigger `searchSettingsTarget`!

**Comment by bpasero** [comment]
Full steps:
* settings editor in group 2
* something searched for
* make settings dirty (not auto save)
* close settings
* do not save from dialog
* settings editor closes and comes back in the background

**Comment by bpasero** [comment]
I guess this is a timing issue where the editor closes but still wants to resolve the preferences model. This triggers me to open the file because we always open dirty files.

This is likely exhibited since we switched to async dialogs, so the settings editor has a chance to resolve the model before it gets reverted...

**Comment by bpasero** [comment]
Weird, now I cannot reproduce anymore. Not a big deal, as it seems very hard to reproduce.

**Comment by roblourens** [comment]
I wasn't able to repro yesterday either. Let me know if you see it again...
