### ISSUE TITLE
Collapse of source view is non-anticipatory.

### ISSUE THREAD

**Issue by jinyutao** [Microsoft/vscode#4226]
- VSCode Version:0.10.11
- OS Version:WIN7 64Bit

Steps to Reproduce:

1. Input source code
void fun()
{
int i=0;
#ifdef ANY
  i=1;
#else 
  i=2;
#endif
  .... 
}

2. click the [-]icon left "{"
SHOW:
void fun()
{...
#ifdef ANY
  i=1;
#else 
  i=2;
#endif
  .... 
}

RIGHT IS:
void fun()
{...
}

**Comment by aeschli** [comment]
@jinyutao Maybe you can add a screenshot?
The current indentation strategy is based purely on the indentation of lines, A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand code blocks, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.

**Comment by jinyutao** [comment]
Thanks the answer.
Add screenshot:
Source code is:
![image](https://cloud.githubusercontent.com/assets/11645091/13772451/44f0a36c-eacf-11e5-89f0-955ab572373c.png)

click the [-]icon
![image](https://cloud.githubusercontent.com/assets/11645091/13772472/666601ea-eacf-11e5-9010-721214ec916d.png)

According to answer，modify indent to same,then OK.
before:
![image](https://cloud.githubusercontent.com/assets/11645091/13772592/f1d6edb6-eacf-11e5-8b5c-1270d4e173d9.png)
after:
![image](https://cloud.githubusercontent.com/assets/11645091/13772602/fe502ff8-eacf-11e5-9bb1-8f44516b8419.png)

But,I think If we can customize the collapse rules according to different languages. Just like the syntax highlighting rules, is not better.

**Comment by aeschli** [comment]
The langage agnostic folding would know that 'void fun()' is the start of a folding section, and '}' the end.
It could also have a rule for #ifdef/#else/#endif

**Comment by BestTurtle** [comment]
If this issue matters to you, please head over to  [#3422](https://github.com/Microsoft/vscode/issues/3422) and hit the thumbs up!
