### ISSUE TITLE
Crash on openning a json file ~7Mb size

### ISSUE THREAD

**Issue by raphaelquati** [Microsoft/vscode#42260]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (84991c4c508b6e91c49a9371aed8ae2dd0718c8a, 2018-01-23T10:59:53.150Z)</li>
	<li>OS Version: Windows_NT x64 10.0.17074</li>
	<li><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
jenkins-status|ale|0.5.1
jshint|dba|0.10.15
vscode-eslint|dba|1.4.4
xml|Dot|1.9.2
tslint|eg2|1.0.24
vs-code-xml-format|fab|0.1.5
beautify|Hoo|1.3.0
Go|luk|0.6.73
mssql|ms-|1.3.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
vscode-docker|Pet|0.0.23
java|red|0.17.0
vscode-icons|rob|7.19.0
jenkinsfile-support|sec|0.1.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
ascii-unicode-escape|yar|0.1.0

</details></li>
</ul>

---

Steps to Reproduce:

1. Open VSCode (insider) - Open a json file (~7Mb)
2.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/815086/35477438-941a412e-03a9-11e8-81ef-2c4d74e58243.png)

![image](https://user-images.githubusercontent.com/815086/35477434-847e0d4a-03a9-11e8-8a9f-7caa60413e04.png)

![image](https://user-images.githubusercontent.com/815086/35477440-a0078d34-03a9-11e8-9546-140dce10f065.png)

**Comment by raphaelquati** [comment]
More info:

The file is not formatted. So json file has 1 line.

"Formatting" the file, increases the size of file, but VSCode opens the file correctly.


![image](https://user-images.githubusercontent.com/815086/35477482-84da5cb6-03aa-11e8-85e6-8046163d0290.png)

**Comment by alexandrudima** [comment]
@raphaelquati Can you please provide the file that causes the crash on open. Otherwise, a very similar one (or even a generated one) so we can reproduce the crash?

**Comment by raphaelquati** [comment]
The file contains sensitive data. I need to obfuscate the file.

**Comment by raphaelquati** [comment]
The file
[dump2.zip](https://github.com/Microsoft/vscode/files/1763282/dump2.zip)

**Comment by alexandrudima** [comment]
Thank you @raphaelquati 

I can reproduce the crash, even when renaming the file to `.txt`. i.e. it is not JSON grammar related. 

@rebornix I believe this to be a regression from the new text buffer implementation. Every 3rd, 4th run I am able to open the file without crashing and I was able to record a profile run:

Here is opening the file in stable:
[stable.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1763511/stable.cpuprofile.txt)
![image](https://user-images.githubusercontent.com/5047891/36737625-ccb84fea-1bdb-11e8-838a-f3bdfe720424.png)

And here is opening the file on master (running from sources):
[master.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1763519/master.cpuprofile.txt)
![image](https://user-images.githubusercontent.com/5047891/36737694-f82b3d18-1bdb-11e8-8fa0-78d17fea1de5.png)

@rebornix From a quick look, it appears `getLineContent` is called many times on the same line. Perhaps some easy caching will get us out of the perf cliff? I also notice that it runs OOM, and I cannot understand why that would happen, for a 11MB file...

**Comment by rebornix** [comment]
Thanks @alexandrudima good catch here ;)

After the change to `SplitLine.getLineContent/getLineData` and adding a cache for line content, I opened this file, scrolled for 10 seconds, run `--status` command, the memory usage now became

```
OS Version:       Darwin x64 17.3.0
CPUs:             Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)
Memory (System):  16.00GB (0.69GB free)

CPU %	Mem MB	   PID	Process
    0	   115	 39686	code-oss main
    0	    82	 39694	   gpu-process
    0	    66	 39696	   shared-process
    0	   262	 43504	   window (dump2.txt)
    0	   131	 43506	     extensionHost
```

The renderer process memory usage increases by about 70 MB (a cold start uses 197 MB usually). It can be higher sometimes if the GC is not kicked in but it should be sane.

**Comment by alexandrudima** [comment]
Nice! Good work @rebornix
