### ISSUE TITLE
Minimap glitch after system suspend.

### ISSUE THREAD

**Issue by mrluissan** [Microsoft/vscode#42261]
- VSCode Version: Version 1.19.3
- OS Version: ubuntu 16.04 LTS

Steps to Reproduce:

1. Open VSCode
2. Suspend the system or simply leave vscode minimized for around 20 minutes.
3. Maximize the vscode window and the minimap is "corrupted".
It looks like this:
![screenshot from 2018-01-28 00-37-37](https://user-images.githubusercontent.com/3933427/35477553-b4910a2a-03c5-11e8-97c9-ccd4845ac8a6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
Duplicate of #30292
