### ISSUE TITLE
Visualize breakpoint types in breakpoints viewlet

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#42266]
This is a part of a series of requests to enable "custom breakpoints" support in VS Code. See Microsoft/vscode#38568

**Scenario:**
Today I can set breakpoint and conditional breakpoints, but as we expand beyond those the importance of being able to disintquish between them grows too.

We have different gutter icons for the breakpoint types, but in the breakpoint viewlet we don't show the icon, as illustrated in:

<img width="1552" alt="screen shot 2018-01-27 at 6 09 35 pm" src="https://user-images.githubusercontent.com/173559/35478959-99f5c46a-039f-11e8-9e91-050e4395002c.png">

**Proposal:**

1. Show breakpoint gutter icon in viewlet list

@stevencl We should probably spend some UX time to discuss how we best can solve this.

**Comment by weinand** [comment]
The design for this already exists here: https://github.com/Microsoft/vscode/issues/3388#issuecomment-194595298

I think we can close this issue an put #3388 "On Deck"
