### ISSUE TITLE
Issue with opening file from zip in editor

### ISSUE THREAD

**Issue by chhil** [Microsoft/vscode#42263]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.5.2
vscode-docker|Pet|0.0.23
java|red|0.17.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. VScode editor has a java file open.
2. Double click on java inside a zip file (I use 7zip for unzipping). VSCode window comes into focus you can see the file open and then the tab with file disappears leaving only the previous open file available.
3. If the file in the zip is the first file to be opened then the vscode editor displays it fine.

Reproduces without extensions: Haven't tried

**Comment by bpasero** [comment]
@chhil does this setting help? `"workbench.editor.closeOnFileDelete": false`

**Comment by chhil** [comment]
After updating the user settings to set the property to false I no longer see the problem.
file->preferences->settings->user settings
`"workbench.editor.closeOnFileDelete": false`

Thank you.

**Comment by bpasero** [comment]
Ok that is a good workaround. It looks like the file is being deleted after passed on to Code and we then just close it.
