### ISSUE TITLE
Awk lexer

### ISSUE THREAD

**Issue by svnpenn** [Microsoft/vscode#42265]
Please create syntax highlighting for Awk, thank you.

**Comment by svnpenn** [comment]
https://github.com/mirror/scintilla/issues/1

**Comment by svnpenn** [comment]
https://github.com/simonsteele/pn/issues/152

**Comment by svnpenn** [comment]
https://github.com/XhmikosR/notepad2-mod/issues/208

**Comment by svnpenn** [comment]
https://github.com/mirror/scite/issues/1

**Comment by svnpenn** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1620

**Comment by mjbvz** [comment]
We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
