### ISSUE TITLE
F8/Shift+F8 to navigate through all errors across all files, not the current one

### ISSUE THREAD

**Issue by muravjov** [Microsoft/vscode#42274]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 3.19.0-18-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.73

---

I use F8/Shift+F8 to navigate errors, but if there is no errors/warnings in current opened file then F8/Shift+F8 does nothing.

Steps to Reproduce:

1. Open a project with errors/warnings in more than one file 
2. Try to loop through all of them with hotkeys - F8/Shift+F8
3. Result: you cannot loop through all issues, only part of them,- depending on what file is currently opened.

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/14783

**Comment by muravjov** [comment]
Thanks, @usernamehw , I close this one as #14783 duplicate
