### ISSUE TITLE
Test: Screen reader support in the terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#42278]
Tests #8339

Complexity: 4

- [x] Windows/NVDA @joaomoreno  
- [x] macOS/VoiceOver @mjbvz 

---

The terminal now support screen readers, targeting NVDA on Windows and VoiceOver on macOS. Here is an overview of what's supported:

- Terminal is announced when focused
- Characters entered into the terminal via keyboard are announced
  - Character and word echo settings are respected
- Read command output upon execution (up to 20 rows to prevent DOM from growing)
- Support screen reader navigation within current viewport
  - NVDA can read out row content on mouse over
  - NVDA/VoiceOver navigation mode works with rows (esc to enter this mode in NVDA, press left to navigate to rows in VoiceOver)

Please learn the basics of the screen reader and attempt to use the terminal. Note that you will need to switch the editor to "Screen Reader Optimized" mode (alt+f1).

### Known issues

- Characters are not read out when deleted from the prompt
- Reading out history when navigating shells using up/down sometimes doesn't work
- Holding down up/down while navigating rows in NVDA can skip over the terminal

**Comment by bpasero** [comment]
@Tyriar not for January?

**Comment by Tyriar** [comment]
@bpasero fixed, thanks for spotting it.

**Comment by sandy081** [comment]
@Tyriar #42415 is blocking to test this.
