### ISSUE TITLE
VSCode icon confuses *.h C++ header with C header

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#42279]
- VSCode Version: 1.19.3
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Open a C++ project
2. Check the icons in the file explorer

<img width="154" alt="screen shot 2018-01-28 at 13 04 09" src="https://user-images.githubusercontent.com/18319900/35487028-c9e153ce-042b-11e8-807a-ef47062bc179.png">

The header is in fact a C++ header. But now VSCode only marks a C++ header with a C++ icon only if it is named "*.hpp" or something.

In the past it's not the case (if my memory serves me) - it can distinguish C and C++ header, even if the filenames are both "*.h", though I don't know how it did it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by Leedehai** [comment]
Sorry but I didn't install any extension that handles icon displaying or file type detection..
@bpasero

**Comment by aeschli** [comment]
We never distinguished `.h` files from being C or C++ header files. The file association is by default associated to C.

If it helps, you can manually change the default association in the settings:
```
    "files.associations": {
        "*.h": "cpp"
    }
```

**Comment by aeschli** [comment]
No plans to fix this.
