### ISSUE TITLE
Word wrap doesn't work in Insiders?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#42277]
### Issue Type
Bug

### Description

Word wrap isn't working at all for me when I trigger via keybinding or command palette.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (89264676133f25c4990706c889a48eab277544f7, 2018-01-26T05:15:09.585Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3398)|
|Memory (System)|15.94GB (9.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.3
EditorConfig|Edi|0.12.0
tslint|eg2|1.0.24
git-project-manager|fel|1.4.0
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
vscode-header-source|ryz|1.1.0
lorem-ipsum|Tyr|1.1.0
shell-launcher|Tyr|0.1.6

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
I cannot reproduce on Linux. `alt`+`z` works fine for me.

@Tyriar Have you tried to disable all extensions? Perhaps there is something specific about the folder you open (folder settings, workspace settings). Perhaps there is something specific about the file you are opening?

**Comment by Tyriar** [comment]
I can't repro on my macbook either. I had https://github.com/Microsoft/vscode-docs with accessibility.md open, this repo does has wordwrap defined in the settings which could have affected it https://github.com/Microsoft/vscode-docs/blob/master/.vscode/settings.json

I believe I did try to open another repo (I think vscode) and it didn't work there either. Reloading didn't fix the problem.

**Comment by alexandrudima** [comment]
I just pulled `vscode-docs` and I am not seeing anything wrong. The `.md` files open word-wrapped and `alt`+`z` disables word-wrapping. Do you have reproducible steps ?

**Comment by Tyriar** [comment]
I don't have access to my Windows machine until tonight, I'll try check on it then

**Comment by alexandrudima** [comment]
@Tyriar Have you been able to reproduce?

**Comment by Tyriar** [comment]
I think the root cause was screen reader optimization was on. I'll assume this is by design.

**Comment by alexandrudima** [comment]
Ah, yes, this pop-over would explain that:

![image](https://user-images.githubusercontent.com/5047891/35613618-f6c3ead0-066c-11e8-8d48-9ee4744280ea.png)
