### ISSUE TITLE
typescript service shutdown after initiated

### ISSUE THREAD

**Issue by g1mi** [Microsoft/vscode#42272]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
beautify|Hoo|1.3.0
html-snippets|abu|0.2.1
vscode-wxml|cod|0.1.9
vscode-eslint|dba|1.4.4
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.22
auto-close-tag|for|0.5.5
vue-snippets|hol|0.1.5
vetur|oct|0.11.6
view-in-browser|qin|0.0.5
vue-vscode-snippets|sdr|1.3.0
open-in-browser|tec|1.1.0
gitblame|wad|2.2.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
A few questions:

- Does this happen if you disable all extensions?
- Does this happen for all projects you open, or just one specifically?
- Have you set a custom `typescript.tsdk` value in your workspace or user settings?

Can you also please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
