### ISSUE TITLE
Can't run python file using the 'run python file in terminal' when using wsl as the integrated terminal

### ISSUE THREAD

**Issue by AddAndy** [Microsoft/vscode#42276]
It looks like VSCode doesn't change paths when running code in wsl.

If you try to run a python file with the right click 'run in terminal' command, you get the following error:
```
$ python c:/Users/Karma/ws/sandbox/flask.py
python: can't open file 'c:/Users/Karma/ws/sandbox/flask.py': [Errno 2] No such file or directory
```

it should be launching from /mnt/c/ instead of c:/

- VSCode Version: 1.19.3
- OS Version: Windows 10 16299.192

Steps to Reproduce:

1. Configure VS code integrated terminal to     
`"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"`
2. right click on python file and select 'run python file in terminal'

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
I believe this functionality comes from the Python extension. Please file this issue against them
