### ISSUE TITLE
Extension editor "contributions" shows data for latest version of extension, not installed version

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42283]
- Install old version of extension (example, try this old version of C# (rename to .vsix): 
[csharp-1.11.0.zip](https://github.com/Microsoft/vscode/files/1671752/csharp-1.11.0.zip))
- Click on extension in extension viewlet
- See that "contributions" shows 15 settings including `csharp.referencesCodeLens.enabled`
- Open settings, try to set that setting, and see that it doesn't exist, because it was added after 1.11.0

Also,
- Open the Changelog tab, see that it covers up to 1.13.1

**Comment by roblourens** [comment]
If I disable wifi and try this again, then I see info for the installed version. That makes me think this might be by design. But I think that when an extension is installed, this page should show info for the actually installed version.

**Comment by sandy081** [comment]
We always shows the details of the latest extension available in the market place. We also show a button to update (saying out of date). It will be useful for users to see what is the latest and update to it.

To know the difference, having a change log will be helpful.
