### ISSUE TITLE
VSCode claims installation is corrupt on update

### ISSUE THREAD

**Issue by BraidenCutforth** [Microsoft/vscode#42282]
- VSCode Version: 1.19.3 (1.19.3) (On update from unknown version to this version)
- OS Version: macOS High Sierra version 10.13.2

Steps to Reproduce:

1. Code was open
2. Installed Live Server 3.1.0
3. Restarted Code (had to in order for extension to work, is this normal?)
4. On restart it claimed that VSCode was corrupt
5. Restarted again and the Release Notes appeared and no warning was shown

Does this issue occur when all extensions are disabled?: Unknown
The extensions were all enabled the entire time.
Has not happened again (don't know if it will)

Extensions:

- C/C++ from Microsoft v0.14.6
- C++ intellisense from Austin v0.2.2
- Debugger for Chrome from Microsoft v4.1.0
- HTML CSS Support from ecmel v0.2.0
- Intellisense for CSS class names from Zignd v1.16.1
- Java Extensions Pack from Microsoft v0.2.0
- Language Support for Java from Red Hat v0.17.0
- Live Server from Ritwick Dey v3.1.0
- Magic Python from MagicStack Inc. v 1.0.12
- Python from Microsoft v0.9.1
- Python for VSCode from Thomas Haakon Townsend v0.2.3
- TSLint from egamma v1.0.24

#20863 Seems to be a similar issue/the same issue

**Comment by joaomoreno** [comment]
Yeah, dupe of #20863. It seems like it still happens...
