### ISSUE TITLE
Line deletion (Shift + Del) and copy and pasting (Ctrl+C , Ctrl +V), pasting empty string.

### ISSUE THREAD

**Issue by sy-zaw** [Microsoft/vscode#42281]
I love VSCode for its fast and feature rich extensions, especially git and semi intellisense. 
I don't know how to on the verbose, so my report might be incomplete. Please guide me if you guys need more info.

Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:32:23.601Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.0-32-generic (Ubuntu 16.04)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
composer-support-client|Hyp|0.16.2
gitlens|eam|7.5.7
php-debug|fel|1.12.1
mssql|ms-|1.3.0
python|ms-|0.9.1
Ruby|reb|0.16.0
git-merger|sha|0.3.6
vscode-todo-highlight|way|0.5.11
phpcomments|yur|0.0.1
---

Steps to Reproduce:

1. copy  a bunch of code(ctrl+c)
2. delete the line at the destination -- using shift+delete
3. try to paste the code(ctrl+v) -- it shows the deleted line (looks like ctrl+z , not ctrl+v)

Steps to Reproduce:
1.  copy the code (ctrl+c) or (ctrl+x)
2. delete the line using (shift+delete)
3. try to paste the code (ctrl+v) -- it just pasted the  some empty string (not the copied code)

Reproduces without extensions: Yes/No

**Comment by usernamehw** [comment]
As I see it <kbd>Shift</kbd>+<kbd>Del</kbd> is an alias for `Cut` action.

**Comment by mjbvz** [comment]
Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by sy-zaw** [comment]
Thanks for the quick feedback.
