### ISSUE TITLE
Feature Requests : Add a RESTART FEATURE for Visual Code on Windows platform

### ISSUE THREAD

**Issue by LIUHUANUCAS** [Microsoft/vscode#42288]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment]
What do you mean by "RESTART FEATURE"? Automatically exit and start Visual Studio Code?

Why do you want this feature? Did you experience any issue and the `Reload Window` command can not fix it?

**Comment by mjbvz** [comment]
Unclear what you are asking. Please follow this guide to report issues: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by LIUHUANUCAS** [comment]
Assume that I have opened three windows and write code with echo of them, I want to Restart one of window ,If I use the exist key on tool bar FILE menue,all window will be closed,which I don't want to see.
What's more, all the file that I opened  will be lossing when I reopen the window.

**Comment by yume-chan** [comment]
So, at first, why do you want to "restart one of window"?

Anyway, I still believe you are referring the `Reload Window` command which has already existed for a long time.
