### ISSUE TITLE
[V-test][GO] When trying to install missing tools from the Analyzer (status bar) then it is throwing error like : 'go' is not recognized.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4228]
VSCode Version: Windows10
OS Version: 0.10.12-alpha

Steps to Reproduce:
1.Install go from this location:https://visualstudiogallery.msdn.microsoft.com/bd7675ba-1bf5-4395-8c5a-4fc19dfc0d76

2.Create directory structure and set environment variable for GOPATH, GOBIN. by following instruction provided at : https://golang.org/doc/install?download=go1.6.windows-amd64.msi 
3.Now add a .go file under workspace dir and execute below command to generate a EXE under GOBIN file.
4.Once exe is generated successfully, open the workspace folder in VSCODE.
5.Open go file and install GO extension.
6.Verify extension installed successfully without any error.
7.Verify GOPATH error should not be displayed as environment variables are already been set.
8. Verify status bar and click on install missing tools.
![image](https://cloud.githubusercontent.com/assets/17735796/13768629/95a31e1a-ea35-11e5-8d38-3d835b3a4080.png)
9. Verify pop-up message and click on install button.
![image](https://cloud.githubusercontent.com/assets/17735796/13768618/64832942-ea35-11e5-9c1e-1961e9a64039.png)
10. Verify output window.
Actual: 
1. Output windows throwing error like 'go' is not recognized as an internal or external command, for all the tools. But when I copied the same command on command prompt and executed it is displaying some different error message like:
**C:\Users\v-pavanp>C:\WINDOWS\system32\cmd.exe /s /c "go get -u -v github.com/tpng/gopkgs"
github.com/tpng/gopkgs (download)
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/tpng/gopkgs: exec: "git": executable file not found in %PATH%**

![image](https://cloud.githubusercontent.com/assets/17735796/13768600/43fd4a9a-ea35-11e5-8933-1e7b83bc5b1d.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-go#245
