### ISSUE TITLE
Launch config validation for unknown debug type falls back on Node

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42285]
![image](https://user-images.githubusercontent.com/323878/35489207-8cfc8178-0448-11e8-8705-9cb560951e26.png)

- Don't have the Chrome extension installed
- Open a chrome launch config like in the screenshot
- Launch config props that are in node-debug are recognized and not underlined. The hover for them shows the documentation for the node-debug versions of these props.
- chrome-specific props are underlined and not recognized

It's weird to fall back on the props that node-debug has, since it's an unrelated debug extension. I think either all the props should be underlined, or none of them (if `type` is not recognized, then doing more validation could just distract from the real issue)

**Comment by isidorn** [comment]
Hey @roblourens this is just how our json schema validation works. Based on the atributes present it  determines what schema it is. In this case this is closest to the node schema thus it flags all the unknown node atributes.
What we need is somehow to tell the json schema that the "type" is the attribute which should be respected the most. However the schema does not support this.

Also there are already feature requests in this area opened by @weinand so closing as duplicate
fyi @aeschli
