### ISSUE TITLE
Open file same as Highlighted  text - Feature Request

### ISSUE THREAD

**Issue by cukulkarni** [Microsoft/vscode#42297]
- VSCode Version: 1.19.3 
- OS Version: Windows 10
This is not an issue just a suggestion if possible, it will be great help.

Request for new Feature:
1. Select a text in the editor and press Ctrl + P
2. This should add the selected text by default into it 

![image](https://user-images.githubusercontent.com/28684235/35500203-a7d2285a-04fb-11e8-8033-36a9ed299d3a.png)

**Comment by shobhitchittora** [comment]
@cukulkarni +1.
Members can you please triage this.

**Comment by yume-chan** [comment]
Although a will designed language server should support navigating to files with <kbd>Ctrl</kbd> + <kbd>Mouse Click</kbd>, I agree it's an enhancement for more flexible usage.

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/41725

**Comment by cukulkarni** [comment]
Great. Many thanks for taking cognizance of this request. 

I am sure there may be some more users who would like this to have as **this feature is available in Eclipse Editor.** 

Thanks again!
