### ISSUE TITLE
JSX elements with dot (i.e <Grid.Row>) wrong highlighting

### ISSUE THREAD

**Issue by ppozniak** [Microsoft/vscode#42298]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.0-25-generic
- No extensions
---

Steps to Reproduce:

1. Place cursor on component that has dot (for example semantic UI react `<Grid.Row>`
2. Closing of that component should be highlighted
3. Instead, all `Grid` words are highlighted

![image](https://user-images.githubusercontent.com/13921243/35500525-0ac443f0-04d7-11e8-956b-67c7de8288c3.png)

**Comment by mjbvz** [comment]
This is the designed behavior currently (since `Grid` is a namespace) but agree we should behave more like the HTML extension when highlighting tag occurrences
