### ISSUE TITLE
Function name repeat when code copied.

### ISSUE THREAD

**Issue by f2009** [Microsoft/vscode#42299]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.11.6

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please follow this guide to report issues: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues
