### ISSUE TITLE
After update to 1.19.3, conflicts with SASS?

### ISSUE THREAD

**Issue by vushe** [Microsoft/vscode#42293]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
better-whitespace|chm|1.0.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
php-pack|fel|1.0.1
plantuml|jeb|2.5.2
vscode-postcss-sorting|mrm|3.0.1
atom-keybindings|ms-|3.0.4
trailing-spaces|sha|0.2.11
bunker|sld|1.1.6
rst-vscode|tht|2.0.0

---

Seems that issue appeared after update to 1.19.3. VS Code is, of course, running.
When I try to run `sass` or `node-sass` from command line or integrated terminal (I'm basically using scripts to call those), they are crashing.

A workaround I found is just to close VSCode, run sass and start VSCode again.

Issue persists without extensions.

Other info: I have quite a fresh installation of latest Linux Mint on my laptop.

P.S. Sorry if repeating issue.

**Comment by octref** [comment]
> they are crashing.

What exactly is crashing and what's the error?

**Comment by vushe** [comment]
That appears to be my local issue as everything works normally in guest mode.
I will comment later on if reason is found.

**Comment by vushe** [comment]
Issue seem is resolved as suggested [here](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers):
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
