### ISSUE TITLE
"Open to Side" from context menu no longer moves focus

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42295]
Steps to Reproduce:

1. select "Open to Side" from context menu
2. expect focus to move to the opened editor

=> focus remains

Compared to stable where focus moved.

**Comment by isidorn** [comment]
@bpasero what I see with latest out of source is that if I have no editor open and do "Open to Side" the focus nicely moves. However when you have already an editor open the focus is wrongly passed to the editor which is already open, not the newly opened one on the side.
I am nicely passing `preserveFocus: false` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L284)

Forwarding to you to investigate why are you focusing the wrong editor
