### ISSUE TITLE
link navigation through the files

### ISSUE THREAD

**Issue by vammex** [Microsoft/vscode#42308]
I feel my VSCode navigation doesnt work well. 
Sometimes I cannot open another file by clicking a link (should I?), sometimes I just cannot pass to already opened file by clicking a link from another opened.
The most weird is that sometimes i even cannot scroll a file as a result of clicking a link to a function that exists in this file and located somewhere below.

Which navigation links of those have to be working? 
I have "editor.links": true option at the settings.
Working with JS.

VSCode Version: 1.19.3
OS Version: win 8.1

**Comment by alexandrudima** [comment]
@vammex Can you provide a specific example of two files, the way in which you link from one to another, what is happening vs. what you think should happen ?

**Comment by vammex** [comment]
@alexandrudima 
for example 
i click on the link "controllerPropChange" in order to open a file  with that controllerPropChange function declaration
it may happen in two variations, the first is the second file has been already opened aside in a tab, or in another case, it hasn't been opened and in normal way, i am gonna click on menu left to open a file.
i would like to understand how it should work for both of cases.
so, when i click it, in both cases, it may sometimes open a file for me, it may not open, and i cannot comprehend the inner logic of what's going on.

![0111](https://user-images.githubusercontent.com/19187347/35559073-6be4702a-05b2-11e8-8b40-4165a7c2f05a.PNG)
![0222](https://user-images.githubusercontent.com/19187347/35559075-6c08236c-05b2-11e8-8bcd-9a0b1b478ff3.PNG)

**Comment by alexandrudima** [comment]
Thanks, these links go to definition, and for `.js` files are computed by the TypeScript language service.

**Comment by vammex** [comment]
@alexandrudima 
what does it mean for me?
why does this navigator work inconsistently?

**Comment by alexandrudima** [comment]
Thank you for the explanation. 

We refer (internally) to feature that is problematic for you as "Go To Definition". The fact that it is rendered as a link is something user-facing, but the feature can be invoked via <kbd>F12</kbd> besides via the mouse gesture. 

I have forwarded the bug to a different team member who can help you further.

**Comment by mjbvz** [comment]
@vammex  Do you have a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson)? If not, try creating one.

If the issue still happens after you create the `jsconfig.json`, please  provide example code or a small example project so we can investigate further
