### ISSUE TITLE
.vscode/settings.json loading is case-sensitive

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/vscode#42300]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.4
githistory|don|0.3.8
plantuml|jeb|2.5.2
Go|luk|0.6.73
VS-code-vagrantfile|mar|0.0.7
PowerShell|ms-|1.5.1
qub-xml|qub|1.2.1

---

Steps to Reproduce:

1. Create .vscode/Settings.json with some custom workspace settings.
1. Open the workspace in VS Code.
1. Observe that workspace settings are not applied.
1. Rename file to .vscode/settings.json.
1. Observe that workspace settings are applied.

I would expect this to be case-insensitive, at least on platforms with case-insensitive filesystems (though perhaps even everywhere).

**Comment by sandy081** [comment]
Verify in both linux and windows/mac machines

- In Windows/Mac verify that VS Code applies settings from `settings.json` file with different cases under `.vscode` folder 

- In Linux verify that VS Code applies settings strictly from `settings.json` file under `.vscode` folder
