### ISSUE TITLE
Intellisense is brutal slow

### ISSUE THREAD

**Issue by bender404** [Microsoft/vscode#42306]
- VSCode Version: 1.19.3
- OS Version: Windows 10

Sometimes it take 20-30sec. if context buble show something. It's happened only in .ts file

**Comment by mjbvz** [comment]
Does it still happen if you disable all extensions and restart vscode? You can also run code with the `--disable-extensions` command line flag to check this

If you still see the problem, please provide more information about your workspace: number of files, general layout, do you have a jsconfig or tsconfig, ...

**Comment by djensen47** [comment]
Mine is not brutally slow but it is noticeable. If I type as fast as I'm typing this message there is a noticeable lag. Holding down backspace is worse. 

It only started happening immediately after the update to 1.19.3.

**Comment by mjbvz** [comment]
Closing this issue since I have not heard back from the original poster. Please try upgrading to VS Code 1.20 and also try disabling extensions. Let me know if you still see the problem

**Comment by djensen47** [comment]
My issues magically disappeared. 👌
