### ISSUE TITLE
how to change a color of open editor links back to white?

### ISSUE THREAD

**Issue by vammex** [Microsoft/vscode#42307]
I am in Dark VS color mode and i like it
after the latest update i see some color changes
how to change a color of open editor links back to white? right now it is about a green color which so hard to read

- VSCode Version: 1.19.3 
- OS Version: win 8.1

![010](https://user-images.githubusercontent.com/19187347/35509359-96808816-04fc-11e8-811d-0c4c7b9b8d6a.PNG)

**Comment by jrieken** [comment]
Two settings

```json
"explorer.decorations.colors": false | true,
"explorer.decorations.badges": false | true,
```
