### ISSUE TITLE
Translation is lost in insider build if you don't manually set it in locale.json

### ISSUE THREAD

**Issue by Joelism** [Microsoft/vscode#42304]
### Issue Type
Bug

### Description

See title, and my system language is zh-CN.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (757ff83f0dece1ecf43d3a92e91fe467de1cc9dc, 2018-01-29T05:13:39.772Z)
OS version: Windows_NT x64 10.0.17083

Reproduces without extensions

**Comment by dbaeumer** [comment]
@Joelism I tried this today with a German Windows version and starting VS Code starts in German without any command line arguments or any settings in locale.json.

I used the insider from last night

<img width="760" alt="capture" src="https://user-images.githubusercontent.com/1931590/35630958-fd93da24-06a2-11e8-9b9f-2dbd91c98bf1.png">


Are you still seeing the issue.

**Comment by Joelism** [comment]
Sadly yes. I also tried it on some other PCs on a Windows stable build, still the same.

Found an interesting thing though. After you delete your user profiles in %APPDATA%, on the first launch, extensions that have Chinese localization will be shown in Chinese while everything else is in English. But if you restart Code, all strings are in English.

**Comment by Joelism** [comment]
If I set German as system language, VS Code starts in German, too. Weird.

**Comment by dbaeumer** [comment]
@octref @rebornix can you help me with this and test VS Code insider under a Chinese locale. What is strange is the @Joelism sees this only under `zh-CN` and not under `de` for example.

**Comment by octref** [comment]
@dbaeumer Confirmed. If you set `zh-CN` in `locale.json` VS Code will be loaded in Chinese, but it's in English when I first launch it from Windows with CHinese locale. #

**Comment by dbaeumer** [comment]
OK. I found out what it is. Chrome / Electron reports Chinese locales as `zh-CN` / `zh-TW` and I tested for lower case. It worked for German since it only reports `de`.
