### ISSUE TITLE
Add "VS Code" to Windows Start button search

### ISSUE THREAD

**Issue by JavChz** [Microsoft/vscode#42315]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-stylus|sys|1.8.0
sort-lines|Tyr|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. In Windows Search need type "Visual Studio Code" and "VS Code alone doesn't work"
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you share a screenshot? Mine shows up for "vscode", "VS Code", "Visual Studio Code", etc.
