### ISSUE TITLE
Deleting consecutive multiple cursors is very slow

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode#42317]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Create a new text file with 4000 empty lines
2. Put the cursor on the first line
3. Scroll to bottom
4. <kbd>Alt</kbd> + Click on the last line to add 3999 more cursors
5. Press <kbd>Delete</kbd> key or <kbd>Backspace</kbd> key
6. You should notice the deletion takes a lot of time

But if the cursors are not consecutive, deletion will be much faster.

To illustrate the problem:

If the cursors are positioned like this (`|` represents a cursor position):

```
|
|
|
|
|
|
```

The deletion will be very slow.

If the cursors are positioned like this (just by pressing <kbd>Enter</kbd> in the last case):

```

|

|

|

|

|
```

The deletion will be a lot faster.

**Comment by alexandrudima** [comment]
A lot of time is spent in the decorations tree and in the view model...

![image](https://user-images.githubusercontent.com/5047891/38993529-34055bea-43e4-11e8-9cd8-45603008b8eb.png)

**Comment by isidorn** [comment]
Verified this now takes 1 second. Which is good imho
