### ISSUE TITLE
Code folding doesn't work properly when indentation is not regular

### ISSUE THREAD

**Issue by brunoscopelliti** [Microsoft/vscode#42312]
- VSCode Version: **1.19.3**

![capture](https://user-images.githubusercontent.com/3489757/35511643-fd0466ac-04fc-11e8-854b-b1afbe23a213.PNG)

- OS Version: **Window 10**

Steps to Reproduce:

1. Copy the following function, and paste it in a javascript file.

```js
function log () {
    console.log(`
***
Log!
***
    `);
}
```

2. Toggle code folding.

![issue](https://user-images.githubusercontent.com/3489757/35511938-385dff82-04fe-11e8-9b92-ef0048045115.gif)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by usernamehw** [comment]
Because all folding is indent-based. Duplicate of #3422

**Comment by mix3d** [comment]
*closed, working as designed* haha. Language-based folding is a much needed missing feature. Hopefully it gets added soon.

**Comment by brunoscopelliti** [comment]
Sorry, for the duplicated issue.
