### ISSUE TITLE
Cannot update to 0.10.11 - Error "Unable to execute file in temporary directory. Setup aborted; Error 5: Access is denied"

### ISSUE THREAD

**Issue by andreiropotica** [Microsoft/vscode#4231]
- VSCode Version: (latest) 0.10.11
- OS Version: Windows 8.1 x64 / Windows 10 x64 (2 different systems)

Steps to Reproduce:

1. Have installed 0.10.10
2. Download update
3. Execute update (from any folder on system (downloads or D drive (Windows is on C))

Error is thrown:
![untitled](https://cloud.githubusercontent.com/assets/11310468/13770334/f028f23e-ea8e-11e5-907b-cb0e6a454b83.png)

I have Admin access on PC.

**Comment by joaomoreno** [comment]
You could reproduce this on **both** Windows 8.1 and Windows 10?

Does it work if it auto updates itself from within the product?

**Comment by andreiropotica** [comment]
Yes on both, no, auto update does not work, no error is thrown in auto update.

**Comment by joaomoreno** [comment]
Is your disk drive somehow full?

**Comment by andreiropotica** [comment]
No, C drive has 99 GB free and D drive has 848 GB free...

**Comment by joaomoreno** [comment]
Does a restart help?

I've found [this link](http://www.tomshardware.co.uk/forum/61736-63-unable-execute-file-temporary-directory-setup-aborted) that doesn't explain the root cause but does have a workaround.

It seems to be that your Windows installations are in some strange state.

**Comment by bgse** [comment]
No repro here on Windows 8.1 x64, update went through without a hitch.

**Comment by andreiropotica** [comment]
It was a domanin anti-spyware policy problem, the administrator fixed it. Thank you for all your suport!

**Comment by joaomoreno** [comment]
Very happy that you solved it! Thanks for letting us know what was wrong. :+1:
