### ISSUE TITLE
Test auto attach for node.js subprocesses (aka cluster support)

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42318]
Test for #40123:

Complexity: 4

- [x] Windows - @aeschli 
- [x] OS X - @RMacfarlane 
- [x] Linux -  @bpasero 

For node-debug we've added a mechanism that tracks all subprocesses of a debuggee and tries to automatically attach to those that are launched in debug mode. This feature is enabled by setting the launch config attribute `autoAttachChildProcesses` to true.

Whether a process is in debug mode is guessed by analysing the program arguments. Currently we detect the patterns `--inspect`, `--inspect-brk`, `--inspect-port`, `--debug`, `--debug-brk`, `--debug-port` (all optionally followed by a '=' and a port number).

Here is an example based on the 'cluster' node module:

test.js:
```js
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length;

if (cluster.isMaster) {
	console.log(`Master ${process.pid} is running`);

	// Fork workers.
	for (let i = 0; i < numCPUs; i++) {
		cluster.fork();
	}

	cluster.on('exit', (worker, code, signal) => {
		console.log(`worker ${worker.process.pid} died`);
	});
} else {
	// Workers can share any TCP connection
	// In this case it is an HTTP server
	http.createServer((req, res) => {
		res.writeHead(200);
		res.end('hello world\n');
	}).listen(8000);

	console.log(`Worker ${process.pid} started`);
}
```

the launch config:
```json
{
	"type": "node",
	"request": "launch",
	"name": "Cluster",
	"program": "${workspaceFolder}/test.js",
	"autoAttachChildProcesses": true
},
```

Verify that this feature works for the example from above or other node.js programs that create sub-processes in debug mode.

**Comment by aeschli** [comment]
I had trouble when creating my own example: https://github.com/Microsoft/vscode/issues/42493

**Comment by wywywywy** [comment]
Hi.  

I copied word for word this test plan but can't get it working.  It never attaches to the child processes.

Is there anything else I need to do?

Windows 10
VS Code ver 1.20.1 (latest) 
Node ver 8.9.1

Debug console

```
Debugging with inspector protocol because Node.js v8.9.1 was detected.
node --inspect-brk=3971 test.js 
Debugger listening on ws://127.0.0.1:3971/b5bc61df-63fc-46d7-8e53-1f99838e25d9
Master 25692 is running
```

Thanks.
