### ISSUE TITLE
node_module path intellisense

### ISSUE THREAD

**Issue by Armada33** [Microsoft/vscode#42326]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: the listing length exceeds browsers' URL characters limit
---

Is there a way for path intellisense to work with angular-cli.json when adding scripts and styles from the "node_modules" folder?

**Comment by mjbvz** [comment]
What isn't working for angular projects? Please provide repo steps or a small example project
