### ISSUE TITLE
Test: Language Pack

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#42324]
Tests: #39178

Complexity: 5

- [x] Windows - @auchenberg  
- [x] OS X - @jrieken 
- [x] Linux - @isidorn

## General

- for all testing open the developer console and ensure that you don't see any exceptions coming from message resolving.

## Test default English

- start VS Code with --locale=en
- Ensure that the whole UI comes in English. Try to activate all pre-bundled extensions and ensure that their UI is in English
- double check the developer console for any UI message related exceptions.

## Test a pre bundle Translation

- start VS Code with a locale we pre-bundle ('zh-tw', 'zh-cn', 'ja', 'ko', 'de', 'fr', 'es', 'ru', 'it')
- do the same testing as for English default above.

# Test Language Pack Extension

## Install

- install [this VSIX](https://github.com/Microsoft/vscode/files/1676859/vscode-language-pack-ps-0.0.1.vsix.txt) using the Install VSIX command. **NOTE:** You have to rename the attached VSIX to *.vsix
- The VSIX contains a English pseudo translation. All voles are doubled and messages are surrounded with `[` `]`. During tested ensure that all strings that should be translated are pseudo translated.
- start VS Code with --locale=ps
- Ensure that the whole UI comes in psuedo English. Try to activate all pre-bundled extensions and ensure that their UI is in English.
- double check the developer console for any UI message related exceptions.

## Update the Language pack extension

- Open the extension folder using the command `Extensions: Open Extensions Folder`
- Open the installed Language pack extension under that folder
- Open the `main.118n.json` file under translations folder
- Change the following translation value
```
"indentationToSpaces": "［Coonveert Indeentaatiioon too Spaacees
```
- Open the `package.json` under the Language pack extension folder
- Increase the version
- Start VS Code with --locale=ps (Do it two times)
- Ensure that above change you have done to translations is picked

## Uninstall

- Uninstall the language pack extension 
- Start VS Code with --locale=ps
- Since extension is uninstalled, VS Code should fall back to default english 

## Miscelleneous

- install the above attached VSIX extension again
- Open the extension folder using the command `Extensions: Open Extensions Folder`
- Copy the Language pack extensions folder into another folder (say Desktop)
- Uninstall the Language pack extension
- Quit VS Code
- Copy the extension folder you copied in step 2 to the extensions folder
- Start VS Code with --locale=ps
- VS Code should not pick the locale
- Restart VS Code again with --locale=ps
- VS Code should pick the locale
- Delete the language pack extension from the extension folder
- Restart VS Code with --locale=ps
- VS Code should fall back to default english 

## Other Features

- Install the above attached VSIX extension again
- Enabling / Disabling a language pack extension should not be allowed
- Extension editor should show the localization contributions
- Open `package.json` of Language pack extension and test the semantics and intelli-sense for `localizations` contribution in `package.json`
- Open language configuration file using command `Configure Language` and test the suggestion provides languages from installed language packs.

**Comment by bpasero** [comment]
@dbaeumer not for January?

**Comment by dbaeumer** [comment]
@bpasero thanks for catching this. Yes, for January
