### ISSUE TITLE
Test improved suggestion memory

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42329]
Test for: #41060
Complexity: 2

- [x] Any OS - @sandy081 
- [x] Any OS - @mjbvz 

We have refined the feature to remember selected suggestions. There is now a setting `editor.selectSuggestions` with `never`, `byRecency`, and `byPrefix`. Make sure that

* the setting and its values are named and documented well so that you understand what it does
* that the default isn't annoying (`byRecency`)
* that the `byPrefix` behaviour is similar to how ST works

**Comment by bsvipas** [comment]
@jrieken I don't know if it's good place here to discuss, but I suggest to make `byPrefix` default, because it's way better than `byRecency` and I believe a lot of users will change that.

**Comment by jrieken** [comment]
@bsvipas The place to discuss this is https://github.com/Microsoft/vscode/issues/41060. The feedback from there is that `byPrefix` isn't much liked...
