### ISSUE TITLE
Close Other Editors stopped working on version 1.20.0-insider

### ISSUE THREAD

**Issue by etiennejcharles** [Microsoft/vscode#42337]
- VSCode Version:  1.20.0-insider
- OS Version: high sierra 10.13.3 

Steps to Reproduce:

1. Open VS Code Insiders 
2. View -> Command Palette
3. Search for "Close Others"
4. Find out it doesn't work

![example](https://user-images.githubusercontent.com/2872476/35518700-45287e54-04e0-11e8-8e6a-4c62bae93efa.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@isidorn looks like a regression to me that we should fix for January. Maybe also check with other commands you moved to the command palette.
