### ISSUE TITLE
Content of Application.app is not loaded

### ISSUE THREAD

**Issue by JulianTillmann** [Microsoft/vscode#42339]
- VSCode Version:  1.19.3
- OS Version: Win 10 1709
- AL Version: 0.11.14434
- Docker Version: 17.12.0
- NAV Docker Image: microsoft/dynamics-nav:2018-de

Steps to Reproduce:

1. Use AL: Go!
2. add var 'Test: Record "Company Information"; to pageextension 50100
3. variable is underlined, it says "Company Infoprmation" is missing. IntelliSense doesn't know about the table. 

I've tried creating multiple new Projects, delete the app package, uninstalling VSCode, re-setting docker, etc.

**Comment by alexandrudima** [comment]
@JulianTillmann I believe this is an issue related to one of the extensions that you have installed. Which extensions do you have? AFAIK vscode does not ship by default with a command called "AL: Go!"

(You can run Help > Report Issue to get a generated markdown table).

**Comment by JulianTillmann** [comment]
Sorry, wrong site
