### ISSUE TITLE
Runaway extension host process

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#42338]
![image](https://user-images.githubusercontent.com/1487073/35520933-5175f47e-04cd-11e8-92a5-3e6cb27d01c4.png)

I removed the setting to enable the background update on windows, clicked on the menu to update from the gear, and then the "old style" setup started.  After a minute or so, received this message:

![image](https://user-images.githubusercontent.com/1487073/35520840-0fb261c6-04cd-11e8-9341-10abc0e15e02.png)

**Comment by chrisdias** [comment]
here is the command line:

![image](https://user-images.githubusercontent.com/1487073/35521761-6c5207d6-04cf-11e8-94d1-6798ec73fad5.png)

**Comment by joaomoreno** [comment]
@alexandrudima @dbaeumer Doesn't the extension host process check for its parent periodically?

**Comment by dbaeumer** [comment]
The extension host process does exactly this.

@chrisdias did you try to kill the process. We have seen cases where the process is in the shutdown but someone the OS doesn't let the process continue this.

**Comment by chrisdias** [comment]
yes i had to kill the process.

**Comment by dbaeumer** [comment]
@chrisdias were you able to kill it ?

**Comment by chrisdias** [comment]
@dbaeumer yes  

i guess close this b/c there is nothing else we can do to figure out what went wrong...
