### ISSUE TITLE
Test pattern-matching when clause

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42331]
Test for: #26044
Complexity: 2

- [x] Any OS - @aeschli 
- [x] Any OS - @rebornix 

There is a new context key operator and it's regex-matching. The syntax is `name =~ /regex/` and it's supported when customising keybindings and when contributing menu items (from extensions). Test that

* you can use the new context key expression as desired, e.g try to contribute an explorer action for `f2{1,4}`-files
* you can use the new context key when configuring keybindings
* you cannot break it

**Comment by rebornix** [comment]
LGTM, can't break it.
