### ISSUE TITLE
Reference CodeLens - wrong reference count

### ISSUE THREAD

**Issue by ekulabuhov** [microsoft/vscode#42347]
My reference counter is stuck at zero IF I open the file that is referenced first. If I open files in a different order - everything is working as expected.

![image](https://user-images.githubusercontent.com/4452263/35524689-fa897984-052a-11e8-92ae-23fe1fac48c5.png)

- VSCode Version: 1.19.3
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Set "javascript.referencesCodeLens.enabled": true
2. Create a class
3. Require that class from another file

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does the reference count update if you switch focus back to file1? What if you make an edit in it?

**Comment by ekulabuhov** [comment]
@mjbvz It doesn't update when I switch focus. It does update when I make edit to file1. It doesn't update when I make edit to file2.

I've also noticed that if I add jsconfig.json file to the root (even an empty one) - it starts working as expected. I found some explanation here: https://code.visualstudio.com/docs/languages/jsconfig#_why-do-i-need-a-jsconfigjson-file

> File Scope - no jsconfig.json: In this mode, JavaScript files opened in Visual Studio Code are treated as independent units. As long as a file a.js doesn't reference a file b.ts explicitly (either using /// reference directives or CommonJS modules), there is no common project context between the two files.
> 
> Explicit Project - with jsconfig.json: A JavaScript project is defined via a jsconfig.json file. The presence of such a file in a directory indicates that the directory is the root of a JavaScript project. The file itself can optionally list the files belonging to the project, the files to be excluded from the project, as well as compiler options (see below).

I kind of expected it to act as explicitly referenced CommonJS modules. Not sure why it behaves the way it behaves now.

**Comment by ekulabuhov** [comment]
Found that you need to set "allowJs": true if you're using tsconfig.json in a mixed project (both TS and JS).

@mjbvz from the documentation it seems like there supposed to be a hint telling you to create jsconfig.json:

> The JavaScript experience is improved when you have a jsconfig.json file in your workspace that defines the project context. For this reason, we offer a hint to create a jsconfig.json file when you open a JavaScript file in a fresh workspace.

That would be super useful! Unfortunately, I think it's missing.
