### ISSUE TITLE
Comparison windows causes VS code to not respond

### ISSUE THREAD

**Issue by Maraud3r** [Microsoft/vscode#42348]
I noticed this today after I updated to 1.19. I was in the process of doing a merge on a code branch and just happened to click on the git source control and then clicked on a html file to look at the differences.

When I did the window wouldn't scroll. After a few minutes of me clicking it came back and asked if I wanted to kill it and re-open which I did, but that didn't seem to fix the problem, if I repeat the steps I get the same outcome.

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|1.0.1
Aurelia|Sim|0.0.6
vscode-css-formatter|aes|1.0.1
Aurelia|beh|1.2.2
jshint|dba|0.10.15
vscode-eslint|dba|1.4.4
githistory|don|0.3.8
gitlens|eam|7.5.7
vscode-great-icons|emm|2.1.22
debugger-for-chrome|msj|4.1.0
gitblame|wad|2.2.0
bootstrap-3-snippets|wcw|0.1.0

---

Steps to Reproduce:

1. Launch VS Code
2. Click on the Source Control item
3. Click on a HTML file to perform the compairson

**Comment by joaomoreno** [comment]
Does this reproduce with `code --disable-extensions`?
