### ISSUE TITLE
Allow disabling color picker 

### ISSUE THREAD

**Issue by tempit** [Microsoft/vscode#42344]
Use case: I'm writing an extension for a CSS preprocessor. As part of our syntax, we have imported variables. When those variables are color values, I present return a ColorInformation for them, so they get the color indicator. However, I would like to disable the color picker when hovering over the indicator, as users can't change the value of the variable.
I send an empty result for the color presentation request in this case, which prevents the color picker from changing the color, but I would like it not to open at all. Is it possible to make the color picker not open when the color presentation result is empty?

Good color picker (with presentation result, will change color on click): 
![image](https://user-images.githubusercontent.com/1898725/35523598-e1f8e6a0-0527-11e8-82cc-3cdb9fbee321.png)

Unwanted color picker (no presentation result, will not change value on click):
![image](https://user-images.githubusercontent.com/1898725/35523698-195e8b40-0528-11e8-8951-e8855c199add.png)

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/34341, thanks for your feedback!
