### ISSUE TITLE
Test: Git submodules

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#42341]
Tests #7829

Complexity: 3

- [x] Windows @dbaeumer 
- [x] macOS @bpasero 
- [x] Linux @sandy081 

Basic git submodule support is in:

- Submodules get an explorer decoration
- Submodules appear as separate repositories in the SCM view
- Submodule `HEAD` changes appear in the outer repository's status list; you can click them to see the diff which shows the `HEAD` change
- You can stage, unstage and revert submodule `HEAD` changes

**Comment by bpasero** [comment]
@joaomoreno this is a very cool feature, only found some minor issues.
