### ISSUE TITLE
Option to disable comment formatting

### ISSUE THREAD

**Issue by Zooce** [Microsoft/vscode#42345]
It would be nice not to have the leading asterisk in a doxy comment if possible, and even better, to have the option to completely disable formatting in comments would be amazing!

```
/**
 * << I don't want these!!!!
 * Yes, this is a comment.
 */
```

**Comment by mjbvz** [comment]
What language are you working in?

**Comment by Zooce** [comment]
I'm working in C++.

**Comment by mjbvz** [comment]
I believe that this behavior comes from your c++ extension. Please file the issue against them
