### ISSUE TITLE
c_cpp_properties.json file rewritten *every* restart

### ISSUE THREAD

**Issue by gdamore** [Microsoft/vscode#42349]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
Go|luk|0.6.73
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.14.6
cmake|twx|0.0.17
cmake-tools|vec|0.10.4
clang-format|xav|1.6.1

---

Steps to Reproduce:

1. Edit the c_cpp_properties.json file (e.g. to add a new includePath for intellisense
2. Confirm the contents updated to disk (after saving), e.g. by "less .vscode/c_cpp_properties.json"
2. Restart
3. The file is now "reverted" to a default, without any of the changes

I suspect maybe one of the cmake related extensions?

Reproduces without extensions: NO

**Comment by alexandrudima** [comment]
Moved to https://github.com/Microsoft/vscode-cpptools/issues/1500
