### ISSUE TITLE
Files detected as generated are not searched and do not appear in Quick Open

### ISSUE THREAD

**Issue by gregmarr** [Microsoft/vscode#42340]
- VSCode Version: 1.19.3
- OS Version: Mac OS Sierra

Steps to Reproduce:

1.  Open a directory containing .go files with this header (just the first line may be enough, did not try with files from other languages):

// Code generated by go-swagger; DO NOT EDIT.
// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

2. When you open one of those files through the Explorer window, you get a warning notification that it's a generated file and should not be edited. (This can be annoying as it doesn't go away on its own but that's a separate issue).  Sometimes the warning doesn't appear right away, but does if you type in the file.

3. Try to search for text in one of those files using the search in files window.  It will not appear in the results.

4. Try to use Quick Open to open one of the files.  They don't appear, even when you type the exact name.

5. Now open that file using Explorer window, and repeat the search and quick open.  The file will appear.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Most likely those files are covered in your `.gitignore` file, or some `search.exclude` pattern. Please check that. You can set `"search.useIgnoreFiles": false` if you don't want it to look at your .gitignore file.

**Comment by gregmarr** [comment]
Thanks.  Is this a new setting?  It worked fine until very recently.  It seemed to stop working at the same time that the generated files warning appeared.

**Comment by roblourens** [comment]
The setting was turned on by default in the last release. I don't know anything about the warning popup, that is probably coming from an extension.

**Comment by gregmarr** [comment]
Thanks.  The warning is indeed coming from from the Go support extension.
