### ISSUE TITLE
Not Enough Disk Memory To Save File

### ISSUE THREAD

**Issue by sdefrancesco** [Microsoft/vscode#42355]
I was recently coding in Visual Studio and I got an error message on the toolbar saying **'There wasn't enough disk space to save the changes'**. I clicked cancel and my file was overwritten with a blank file. I did not commit it to git, Is there anyway i can revert back to my original file? I've been working on this git branch for a few weeks and have not staged my changes in some time and I am afraid I won't be able to get it back. Is there something I can do? Help is greatly appreciated.

**Comment by joaomoreno** [comment]
Unfortunately there doesn't seem to be much we can do for you now. Did you have any backups?
