### ISSUE TITLE
Test: Log uploader

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42352]
#40056

Complexity: 2

**OS:**
- [x] Linux @octref 
- [x] Mac @weinand 
- [x] Windows @chrmarti 

## Overview
The new `--upload-logs` command line flag can be used to upload logs from the current user session to a secure storage endpoint. This is to help with investigations

## Testing
1. Start code

1. Run `code-insiders --upload-logs` and go through the flow, pressing `y` to confirm upload

     - ✅ Do the instructions make sense?
     - ✅ Did you receive a log id at the end?

1. Run `code-insiders --upload-logs` and go through the flow, pressing anything except `y` to deny upload

     - ✅ Logs were not uploaded
     - ✅ Do the cancelled messages make sense?

1. Exit code

1. Try running  `code-insiders --upload-logs` again

     - ✅ Error message about no running instance makes sense

**Comment by weinand** [comment]
@mjbvz you said "go through the flow". Is there any more "flow" than this?
![2018-01-30_17-37-22](https://user-images.githubusercontent.com/1898161/35578430-51385188-05e4-11e8-84c8-c81bdf5003d8.png)

**Comment by mjbvz** [comment]
@weinand Nope. That's it. I'll post internal instructions on checking the uploaded logs

**Comment by chrmarti** [comment]
Note: It doesn't work on Windows, filed #42635.

**Comment by octref** [comment]
Other than #42507 everything else looks good.
