### ISSUE TITLE
Error in Syntax

### ISSUE THREAD

**Issue by INGCRENGIFO** [Microsoft/vscode#42359]
Hi, I created a syntax for vs code. But in some cases it does not work well.

![imagen](https://user-images.githubusercontent.com/12200313/35532800-80d6cde2-0509-11e8-98a8-a3d437ad0899.png)
As you can see, let from pallet, is highlighted, which it shouldn't. Didn't check if it happens with other expressions.

Another one:
![imagen](https://user-images.githubusercontent.com/12200313/35532876-bcf1104e-0509-11e8-9c4f-e8c4e0336c10.png)

How can I fix it? Is it a "Vs Code" error?

**Comment by INGCRENGIFO** [comment]
He will not let me join the group without an invitation.

**Comment by auchenberg** [comment]
@INGCRENGIFO What's your email, then I can invite you?

**Comment by INGCRENGIFO** [comment]
@auchenberg ingcrengifo@gmail.com
