### ISSUE TITLE
Test issue reporter

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#42351]
Tests #41041

Complexity: 3

- [x] MacOS @gregvanl 
- [x] Windows ~~macOS~~ @stevencl  (I tested on Windows as I don't have access to MacOS in the office)
- [x] Linux @Tyriar  

The issue reporter should
- open from 'Report Issue' in help menu, from 'Report Issue' command, and from 'Submit a Bug' in the feedback part
- open with same styling and zoom as workbench (dynamic changes to these not supported)
- open GitHub preview with data
- not send data that is not checked
- search GitHub for issues when typing in 'Title' field

**Comment by stevencl** [comment]
Note that I tested on Windows as I don't have access to MacOS in the office.
