### ISSUE TITLE
Asterisk seems to be treated specially in documentation preview

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42353]
_From @jawnsy on January 29, 2018 17:43_

**Description**

Documentation preview requires an asterisk to be escaped, while `godoc` does not require the escaping. This is a pretty minor issue but I'd expect vscode-go to behave as close to `godoc` as possible.

**Actual behavior**

This comment:

```go
// ValidFileName returns nil if the string is a valid file name, or an
// error otherwise. If pattern is true, file glob patterns are permitted
// ("*" and "?", e.g. "abc*")
```

is rendered like so:

![actual](https://user-images.githubusercontent.com/52710/35525071-4f20a43e-04d8-11e8-9619-a8f2d8e060da.png)

Notice that the * is missing between "".

**Expected behavior**

`godoc -http` renders it like so:

![godoc](https://user-images.githubusercontent.com/52710/35525064-4aa133a6-04d8-11e8-9a5b-51b306bb1611.PNG)

I'd expect this to be correct, though I haven't read godoc spec.

**Workaround**

You can escape the * in the comment (`\*`), like so:

```go
// ValidFileName returns nil if the string is a valid file name, or an
// error otherwise. If pattern is true, file glob patterns are permitted
// ("\*" and "?", e.g. "abc*")
```

Then it appears to be rendered as expected:

![workaround](https://user-images.githubusercontent.com/52710/35525157-8de95508-04d8-11e8-88f4-4e74d273875d.png)

**Version info**

vscode-go 0.6.73

VSCode version info (OS: Windows 10):

```
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

_Copied from original issue: Microsoft/vscode-go#1486_

**Comment by ramya-rao-a** [comment]
Thanks for reporting!
Seems to be an issue with VS Code and not the Go extension.
I get similar issues on hover text when using typescript

**Comment by jrieken** [comment]
> Seems to be an issue with VS Code and not the Go extension.

@ramya-rao-a Are you saying that you are using `MarkdownString#appendText` and this still happens? 

There are two APIs (old/new). The old is `MarkedString` and extension authors must manually escape markdown syntax. The new is `MarkdownString` with some sugar-utils to append text as text or markdown.

**Comment by ramya-rao-a** [comment]
For Go, I am using the old `MarkedString`, I can give the one a try.
My screenshots in https://github.com/Microsoft/vscode/issues/42353#issuecomment-361346005 are for typescript. @mjbvz What do you use there?

**Comment by mjbvz** [comment]
We support markdown content in JSDocs so we don’t escape anything. The * is probably being treated as the start of italics. Can you escape the * manually in the doc?

**Comment by ramya-rao-a** [comment]
@mjbvz Thats right. The text between the 2 * is being treated as italics in typescript.

So what's the expectation here?
We cant expect code owners to escape the * all the time

**Comment by jawnsy** [comment]
The expectations might be different between JavaScript/TypeScript/JSDoc and Go/godoc.

I'd expect JSDoc to render markdown content **if** the [Markdown plugin](http://usejsdoc.org/plugins-markdown.html) is configured, but **not** otherwise. In other words, I'd expect the preview to be as close as possible to what I'd see in generated HTML. The current behavior doesn't seem to check the configuration before rendering?

godoc doesn't seem to support Markdown [as far as I can tell](https://blog.golang.org/godoc-documenting-go-code), so it shouldn't be rendered in VSCode either.

**Comment by mjbvz** [comment]
@ramya-rao-a No good solution. Either you convert your jsdocs to markdown or we disable markdown everywhere. I don't think we can detect when a jsdoc comment should or shouldn't be markdown (although if you surround the `*` with spaces, I don't think it will be treated as italic)

**Comment by ramya-rao-a** [comment]
@mjbvz Anyway I can tell the hoverprovider to treat given content as just string and not markdown?

**Comment by mjbvz** [comment]
@ramya-rao-a In general, or for a given jsdoc?

**Comment by mjbvz** [comment]
Closing this as-designed for jsdocs. No good solution without breaking jsdocs that do want to use markdown.

Workaround is to escape any special markdown characters, such as `\*`
