### ISSUE TITLE
Provide file content based extension recommendations

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#42368]
Per observation in https://mobile.twitter.com/dan_abramov/status/958094132018376706, Flow language users are having their Flow code treated as TypeScript out of the box, which creates a cumbersome first hand experience.

We should explore ways to provide file content based extension recommendations, so we for example could analyse JavaScript files starting with ```// @flow```, and provide a recommendation to install the Flow language extension.

**Comment by Tyriar** [comment]
Recommendation for the Flow extension plus potentially disabling the out of the box JS linting as well would be ideal, since Flow uses .js and the types are getting squiggles.

**Comment by gaearon** [comment]
Even with the Flow extension: 

<img width="1231" alt="screen shot 2018-01-30 at 2 43 40 pm" src="https://user-images.githubusercontent.com/810438/35572254-26ed0710-05cc-11e8-8d93-e95c6e144cdf.png">

**Comment by egamma** [comment]
Another option is to add support for disabling a bundled extension.
