### ISSUE TITLE
AutoImport (ctrl . ) stopped to work 

### ISSUE THREAD

**Issue by fatihkaratay** [Microsoft/vscode#42369]
Right after I upgraded VS Code to Version 1.19.3, I started to have some problems. IntelliSense was working just fine on C# files. I was able to import other classes. However, after a couple of minutes later, it stopped to work. IntelliSense works but I can't import other classes using "ctrl + . " shortcut. 

I have Win10 64 and my VS Code version is 1.19.3
Node: 7.9.0

**Comment by mjbvz** [comment]
This is in c# files, correct?

**Comment by fatihkaratay** [comment]
Yes, it only happens in c# files.

**Comment by mjbvz** [comment]
Thanks. Please file this issue against your C# extension instead
