### ISSUE TITLE
Update not working if chained carts are present. 

### ISSUE THREAD

**Issue by brownwk** [Microsoft/vscode#42362]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.start code
2.click check for updates
3. Nothing happens
4. Error CERT PKIXVerifyCert for vscode-update.azurewebsites.net failed error=-8172

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/setup/network

You can try using `--ignore-certificate-errors`

**Comment by brownwk** [comment]
Could you add that option to the help output or add it to preferences?
