### ISSUE TITLE
Feature: Language Translations in Extension ReadMe Preview

### ISSUE THREAD

**Issue by rwatts3** [microsoft/vscode#42360]
Greetings, 

I would like to propose the ability to add i18n translations to the extension descriptions within vscode. 
There are a lot of great packages developed by vscode developers from different parts of the world. 

With that said we each may speak a different language, and it would be nice to have a translated version of the Details tab within the extension preview in order to better understand the purpose of their extension prior to downloading. 

This feature may already exist, and I may simply not know where to enable, or turn it on. 

Thanks in advance. 

Ryan

**Comment by dbaeumer** [comment]
I assign this to you since this would be something that the extension and the extension editor needs to handle (e.g. reading a different readme.md file)

Please ping if there is something you expect from the general NLS story.

**Comment by sandy081** [comment]
@joaomoreno Any clue if the market place supports localization?

**Comment by joaomoreno** [comment]
cc @viradhamMS @pkuma-msft

**Comment by viradhamMS** [comment]
We do have plans for localization in backlog. it certainly is a useful feature. But I don't see us getting to it in the next 6 months at least.

**Comment by pkruk2** [comment]
Would be nice to have. The Readme is the second thing the user sees after description. Hard to call an extension "localized" when the main introduction point is not localized...
