### ISSUE TITLE
Test: Extension contributed TS Server plugins

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42361]
#41113

Complexity: 3

**OS**:
- [x] Linux @aeschli 
- [x] Mac @roblourens 
- [x] Windows @sandy081 

## Summary
Extensions can now contribute TS Server plugins that augment our JS and TS tooling

## Testing
1. Install the lit-html extension: https://marketplace.visualstudio.com/items?itemName=bierner.lit-html

1. In a new workspace, create some js and ts files

    - ✅ You get html intellisense for strings such as:

        ```js
        const z = html`<img>`
       ```

    - ✅ Format works for the html content

1. Now create a `jsconfig` or `tsconfig` and restart vs code

    - ✅ You still get intellisense
  
1. In your `jsconfig`/`tsconifg`, try to configure the lit html plugin and restart the ts server:

    ```json
	{
		"compilerOptions": {
			"module": "commonjs",
			"target": "es2016",
			"jsx": "preserve",
			"plugins": [
				{
					"name": "typescript-lit-html-plugin",
					"tags": ["foo"]
				}
			]
		},
		"exclude": [
			"node_modules",
			"**/node_modules/*"
		]
	}
    ```

    - ✅ This config will break syntax highlighting but you now should be able to manually trigger intellisense inside of `foo` tagged templates:

        ```js
        const z = foo`<img>`
        ```

1. Now install a workspace version of typescript and run `Select TypeScript version` in the workspace to switch to it

    - ✅ The html intellisense should no longer be enabled.

1. Now install the plugin manually into your workspace `npm install typescript-lit-html-plugin` and restart the tsserver

    - ✅ IntelliSense should be back

## Other things to check

-  IntelliSense should still be enable for loose files js/ts in your workspace even if when you have a `jsconfig` / `tsconfig`. To test, just create a normal `tsconfig` and try using html template intellisense in an `js` in the same workspace

- Check out the documentation for contributing tsserver plugins: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensionAPI/extension-points.md#contributestypescriptserverplugins . Does it make senses if you wanted to write an extension like this?

**Comment by aeschli** [comment]
Pretty cool! Nice work.
