### ISSUE TITLE
Test: Language Pack Generation

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#42366]
Tests: #41682

Complexity: 3

- [x] Windows - @dbaeumer
- [x] OS X - @RMacfarlane
- [x] Linux - @ramya-rao-a 

- install the `next` version of the vscode yeoman generator:
`npm install -g generator-code@next`
- run yeoman (`yo code`) and verify that you see a new option `New Language Pack (Localization)`
- Run the yeoman generator and choose one of the languages from transifex:
https://www.transifex.com/microsoft-oss/vscode-editor/languages/
Do not pick one of the built-in langages such as:
	`zh-tw`,`zh-cn`,`ja`,`ko`,`de`,`fr`,`es`,`ru`,`it`
- verify that this create a new folder with `package.json`. Please look at the `README.md` and `vsc-extension-quickstart.md` and check if they make sense

To download the languages file

- Get an transifex API token from https://www.transifex.com/user/settings/api that has access to projects 'vscode-editor', 'vscode-workbench' and 'vscode-extensions'
- Set the API token to the environment variable `TRANSIFEX_API_TOKEN`.
- In the VSCode repo (master) run `npm run update-localization-extension {path_to_lang_pack_ext}`
- verify that this added new files to `path_to_lang_pack_ext/translations` and that updated the `package json` content by adding a list of paths to `localizations/translations`
- in the extension run `vsce package`
- load the generated VSIX into VSCode
- run VSCode with the new locale
- verify that you see the translated strings. Note that some languages have not completed the translations on transifex. Non-translated string fall back to English.

**Comment by aeschli** [comment]
I pushed a fix for #42525. Make sure your vscode is on the latest of master. No update of the generator-code needed.

**Comment by ramya-rao-a** [comment]
@aeschli I made changes to the translations in the generated extension (after running `npm run update-localization-extension`) and expected the changes to show up after installing the vsix. The changes dont show up. Am I missing something?

**Comment by aeschli** [comment]
@ramya-rao-a That should work, vsce should package whatever is in the `translations` folder. If that's not the case that would be a bug in vsce.
