### ISSUE TITLE
When developing with Unity and C#, vscode can't find reference to System.Xml.XmlDocument

### ISSUE THREAD

**Issue by satscape** [Microsoft/vscode#42371]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.14.14-041414-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
csharpfixformat|Leo|0.0.59
python-docs|Muk|0.8.3
unity-tools|Tob|0.1.9
unity-debug|Uni|1.2.1
shaderlabvscodefree|aml|1.1.0
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
vscode-python-docstring|aza|0.0.5
django-html|bib|1.2.0
django-snippets|bib|1.1.0
unity3d-pack|dim|1.0.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
code-runner|for|0.8.7
terminal|for|0.0.10
rest-client|hum|0.16.2
py-paste-indent|hye|0.0.2
vscode-csharp-snippets|jor|0.2.0
docomment|k--|0.0.17
TrelloVSCodeExtension|kat|0.1.2
unity-code-snippets|kle|1.1.0
Go|luk|0.6.73
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
prettify-json|moh|0.0.3
python|ms-|0.9.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
python-coding-tools|nil|1.0.1
autodocstring|njp|0.1.4
vscode-code-outline|pat|0.0.12
vscode-icons|rob|7.19.0
shader|sle|1.1.2
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscode-arduino|vsc|0.2.10
jinja|who|0.0.8
mono-snippets|zra|0.0.2

---

Steps to Reproduce:

1. 
```
using System.Xml;
// blah...inside a method:
XmlDocument xmlDoc = new XmlDocument();
```
vscode reports: "The type XmlDocument could not be found..."
MonoDevelop and Unity have no issues with that line of code (including at runtime)
It doesn't stop me developing using vscode, but would be nice to have it fixed.

https://msdn.microsoft.com/en-us/library/system.xml.xmldocument(v=vs.110).aspx

**Comment by alexandrudima** [comment]
Moved to https://github.com/OmniSharp/omnisharp-vscode/issues/1986
