### ISSUE TITLE
Test extension logger

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42375]
Test for https://github.com/Microsoft/vscode/issues/40053

Complexity: 2

- [ ] any OS @auchenberg 
- [x] macOS @weinand

Create an extension that uses the logger exposed on the ExtensionContext. This is proposed API, so set `"enableProposedApi": true` and copy the vscode.proposed.d.ts into your workspace.

Things to look for
- Logs from extensions in multiple windows go to different folders
- Log level is accurate after changing it (via `Developer: Set Log Level`)

**Comment by weinand** [comment]
@roblourens in the LogLevel enum:
```
	/**
	 * The severity level of a log message
	 */
	export enum LogLevel {
		Trace = 1,
		Debug = 2,
		Info = 3,
		Warning = 4,
		Error = 5,
		Critical = 6,
		Off = 7
	}
```
is there a specific reason why "Off" has the value 7?
I would have expected that "Off" has the value 0.

**Comment by roblourens** [comment]
This matches the internal enum: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/log/common/log.ts#L17

I think it's natural to say `if (msg.level > logLevel) ...` but it could be the other way too.

**Comment by weinand** [comment]
@roblourens thanks, matching the internal enum makes sense.

**Comment by auchenberg** [comment]
Validated on Ubuntu.
