### ISSUE TITLE
Process inherits vscode environment when launched by debugger

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#42373]
I noticed that if I launch code from the terminal, it uses a logs folder in the `code-oss` user data folder. But if I launch it with a debugger, it uses the `code - insiders` user data folder. This is because the debug adapter inherits the `VSCODE_LOGS` environment variable.

The terminal explicitly removes all the vscode environment variables from the terminal process. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L107. Maybe we should do the same when spawning debug adapters?

cc @weinand

**Comment by weinand** [comment]
Yes, it probably makes sense to remove VS Code environment variables.
(But there is always the risk of breaking a debug extension...)

**Comment by roblourens** [comment]
Seems to be fixed
