### ISSUE TITLE
Test newly adopted less and scss syntaxes

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42379]
Testing https://github.com/Microsoft/vscode-css-languageservice/issues/57 and https://github.com/Microsoft/vscode-css-languageservice/issues/58

Complexity: 2

- [x] Windows - @dbaeumer
- [x] OS X - @bpasero
- [ ] Linux - @chrmarti

You can test both syntax by editing a scss/less file.

1. Test that scss language service could handle `!important` as a function argument, for example as an arg of [if](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#if).
2. Test that less language service could handle variables as media query args, such as `@media (@m)`.

**Comment by bpasero** [comment]
Do we really need cross platform coverage for that? Imho a verification needed would have been enough.

**Comment by octref** [comment]
@bpasero Sorry for that, should have been an any OS item. (Haven't created testplan items for a while).

**Comment by ramya-rao-a** [comment]
Since this was an "any OS" item and we dont really need a 3rd tester here.
Closing,
