### ISSUE TITLE
Feature Request: Accept all of one sort of change in the merge tool.

### ISSUE THREAD

**Issue by ntomallen** [Microsoft/vscode#42387]
- VSCode Version: 1.19.3
- OS Version: Windows 10 Pro 17025.rs_prerelease

Would love to see a button which allows the user to "accept all incoming" or "accept all current" changes. Sometimes I have large configuration files that had to be tweaked just right (e.g. a gradle build) that I know need to stay identical after a merge, and I just want to keep all of the changes from one side. Another case is when I have a very old branch I'm merging in that has merge conflicts in one file that I know is way out of date compared to the current copy. So I just want to be able to keep all of the current changes.

**Comment by chrmarti** [comment]
These commands are already available from the command palette (Ctrl + Shift + P).
![image](https://user-images.githubusercontent.com/9205389/35551551-f1aca222-058f-11e8-9fd4-d013229b4dcc.png)

**Comment by ntomallen** [comment]
Fantastic, I did not realize that!
