### ISSUE TITLE
Debugging doesn't start on a fresh TypeScript extension when running the "Debug: Start" action

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4238]
Testing #3906

Linux

1. `yo code`
2. Choose TypeScript extension
3. Open the extension in Code
4. Run `Debug: Start` or `Run`.

Nothing happens besides the appearance of an `out` folder in the explorer. You need to run the action once more to get the instance of Code running your extension.

**Comment by isidorn** [comment]
Dup of #4105
