### ISSUE TITLE
Closing editor does not work anymore in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42389]
Steps to Reproduce:

1. open SCM view
2. click on a change
3. directly trigger close editor via keybinding (Cmd+W)

=> Cannot read property id of undefined

![image](https://user-images.githubusercontent.com/900690/35551482-9dba4f52-058f-11e8-8839-3f1358afd208.png)

**Comment by isidorn** [comment]
Duplicate
