### ISSUE TITLE
Difficult to select and copy from integrated terminal

### ISSUE THREAD

**Issue by jdunham22** [Microsoft/vscode#42381]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-svn|eli|0.1.0
python|ms-|0.9.1
cpptools|ms-|0.14.6

---

Steps to Reproduce:

1. After a build task, the Terminal Window contains output, and you can select some of the output text with a left mouse click and drag action.
2.  If you drag down to the end of the window before releasing you can right-click and get a copy/paste/select-all context menu.   Copy/ctrl-C is grayed out and if you press it, then your selected text is not transferred to the clipboard.
3. If you choose select all, you cannot get the context menu back, though it turns out that Ctrl-C will work in this state.
4. If you drag to some other point besides the bottom of the output window, then Ctrl-C will copy the selected text to the clipboard, but the right-click context menu is not available and if you right click, your selection highlight disappears.

So the only way to select all is to first select some text down to the bottom of the window, and the only way to copy text is to use ctrl-c, though it does not work if you have selected down to the bottom of the window unless you then choose to select all.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by jdunham22** [comment]
{
"terminal.integrated.env.windows": {
"sample_variable": "C:/Avnera/foo"
},
"files.associations": {
"*.lg": "json",
"flash_if.h": "c",
"sysutil.h": "c",
"msgcommon.h": "c",
"applog.h": "c"
}
}

**Comment by jdunham22** [comment]
I just tried removing  "editor.emptySelectionClipboard": false,
but it didn't seem to have any effect on the issue.

**Comment by Tyriar** [comment]
By default right clicking inside the terminal on Windows is meant to copy when there is a selection, and paste when not. Have you tried tweaking `terminal.integrated.rightClickCopyPaste` to see if that gives you the expected behavior?

**Comment by jdunham22** [comment]
Okay so part of my issue was not knowing that terminal.integrated.rightClickCopyPaste feature was on.  I wasn't understanding why the context menu was suppressed in various situations.
  
However the real problem is if you click and drag, and then mouse-up when the pointer is down in the status bar, the behavior is not as expected.   Text will be selected down to the bottom, but then when you right-click on that selected text and choose Copy, nothing is moved to the clipboard (the previous contents remain).

If you do the same thing and press Ctrl-C then the selection highlight clears away but still nothing is transferred to the clipboard.

If you do both of the above actions on the selected text, then you get Error "Cannot read property 'isWrapped' of undefined"

When ending the selection somewhere inside the output window, then the behavior is fine, but if you end it by mousing up down in the status bar it is terribly confusing because it looks like your text is selected and you could copy it but you can't.   

If you have terminal.integrated.rightClickCopyPaste true and select text this way, then right click  on it, it shows the context menu rather than pasting whatever is in the clipboard, but if you choose copy from that context menu, nothing is copied.  It's the same problem where text looks selected, but the program behaves as if nothing is selected.

**Comment by jdunham22** [comment]
verified.  The problem is not seen in the insiders build.  Thanks!
