### ISSUE TITLE
Preserve the text case when doing case-insensitive search and replace

### ISSUE THREAD

**Issue by letheed** [microsoft/vscode#42382]
i.e. a case insensitive match on "foo" and replace with "bar" would give

"foo Foo FOO" => "bar Bar BAR"

This is usually what I really want when I do a massive search-replace. Instead I need to make 2 or 3 case-sensitive search-replace ATM.

This is mostly what emacs' smart query-replace does.

**Comment by roblourens** [comment]
I'd like this too.

https://www.gnu.org/software/emacs/manual/html_node/emacs/Replacement-and-Lax-Matches.html#Replacement-and-Lax-Matches

> Thus, the command `M-x replace-string <RET> foo <RET> bar <RET>` replaces a lower case ‘foo’ with a lower case ‘bar’, an all-caps ‘FOO’ with ‘BAR’, and a capitalized ‘Foo’ with ‘Bar’. (These three alternatives—lower case, all caps, and capitalized, are the only ones that replace-string can distinguish.)

**Comment by sandy081** [comment]
@roblourens This seems to be a dup of https://github.com/microsoft/vscode/issues/11853

**Comment by roblourens** [comment]
This was actually implemented in https://github.com/microsoft/vscode/issues/9798
