### ISSUE TITLE
font aliasing for terminal

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#42392]
- VSCode Version: 1.20.0 (Insiders)
- OS Version: macOS

`window.fontAliasing` works for everything except Terminal. I really like the new feature `auto` which decides which font aliasing apply depending on DPI. But I miss it for Terminal. So my suggestion is to introduce new feature which can enable font aliasing for terminal: `terminal.integrated.fontAliasing` -> `none | default | antialiased | auto` like it's in `window.fontAliasing`.

Thank you!

cc @Tyriar since you're terminal master 😄

**Comment by Tyriar** [comment]
Already tracked in https://github.com/Microsoft/vscode/issues/36249 😃
