### ISSUE TITLE
Open Editors: "Open to Side" with keyboard still activates group

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42399]
Compared to explorer where we do not. I think you always activate the target group, even though `preserveFocus` is `true`.

**Comment by isidorn** [comment]
@bpasero what do you mean by activate group?
I see exactly the same behavior in open editors and explorer on mac with latest out of source. That is file is opened as preview and the focus is passed to the file.

**Comment by bpasero** [comment]
@isidorn this:

![image](https://user-images.githubusercontent.com/900690/35633359-4f7cf9be-06a9-11e8-90d6-50286f7fc796.png)

Just compare how "Open to Side" works in Explorer vs Open Editors

**Comment by isidorn** [comment]
I do not see any behavior difference between open editors and explorer. Can you please elaborate what are you trying to say?
That the open editors should not activate the group?

Keep in mind that in the explorer I have no notion of groups.

**Comment by bpasero** [comment]
Needs more thinking, the activate group call is there for a reason because if you click on an editor in the "open editors" view which is already opened, nothing would happen, so we need to manually activate the group the editor is in.

**Comment by aeschli** [comment]
@bpasero Steps to verify?

**Comment by bpasero** [comment]
@aeschli trigger "Open to Side" via keybinding (Ctrl+Enter) and verify that the editor that opens is not getting activated (same as explorer).

**Comment by octref** [comment]
I don't see any difference between pressing Ctrl-Enter on a file in open editors or explorer. However @bpasero it seems the current behavior is exactly the reverse of what you want?

- Open `foo.ts`
- Focus on `foo.ts` in either Open Editor or Explorer
- Ctrl-Enter
- `foo.ts` is open in editor group 2 and given focus (I guess that's what you meant by "activate"?)

**Comment by bpasero** [comment]
@octref @aeschli sorry, got confused. This is actually about Alt-click to open to side, it should not activate.
