### ISSUE TITLE
When the runtime，the rg.exe take up a lot of memory,i think the memory leak.

### ISSUE THREAD

**Issue by zoudongyang** [Microsoft/vscode#42390]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
px2rem|art|0.0.3
path-intellisense|chr|1.4.2
cssrem|cip|0.0.3
bracket-pair-colorizer|Coe|0.10.14
jshint|dba|0.10.15
vscode-eslint|dba|1.4.4
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
vscode-fileheader|mik|0.0.2
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
material-icon-theme|PKi|3.2.2
view-in-browser|qin|0.0.5
vscode-icons|rob|7.19.0
vue-vscode-snippets|sdr|1.3.0
open-in-browser|tec|1.1.0
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please include more details. What exactly are you doing when this happens? What exactly do you see?
