### ISSUE TITLE
Cannot close editors with X

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42398]
* open an editor
* press the X to close it
* 💥 an exception occurs and shows in your face

**Comment by jrieken** [comment]
<img width="1238" alt="screen shot 2018-01-30 at 09 57 49" src="https://user-images.githubusercontent.com/1794099/35557084-5eb13266-05a4-11e8-9e7c-32d7b4478947.png">

**Comment by bpasero** [comment]
@isidorn a regression from your changes?
