### ISSUE TITLE
Closing extension Code instance doesn't make `Run` stop

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4239]
Testing #3906

Linux

1. `yo code`, TypeScript extension, `code` into it
2. Run the `Run` action until the extension Code instance comes up
3. Close the Code instance that comes up

It appears that the instance is still running, in the original Code window.

![bug](https://cloud.githubusercontent.com/assets/22350/13772128/c1a3004a-ea92-11e5-8bcc-a457020b8082.gif)

**Comment by weinand** [comment]
@isidorn could you please stop the debug adapter in this case?

**Comment by isidorn** [comment]
@bpasero in this particular case I do not get called from the workbench. It would be great if the workbench could notify me via the broadcast mechanism the [same way](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L142) it does when the user reloads the other window.

Could we add something like this?

**Comment by bpasero** [comment]
@isidorn we could but I am not sure about doing this for GA, I do not think running an extension without debugger attached is a real scenario with many users, is it?

**Comment by isidorn** [comment]
@bpasero I agree this is not GA. I think @weinand agrees, Andre let us know

**Comment by weinand** [comment]
I agree. It's just for completeness... moved to backlog

**Comment by isidorn** [comment]
Assigning to @bpasero, once you start broadcasting something give the bug back to me so I do the right thing

**Comment by bpasero** [comment]
@isidorn I added a new broadcast you should listen to: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/thread/electron-browser/threadService.ts#L29
