### ISSUE TITLE
Format Code command missing on Mac OS X

### ISSUE THREAD

**Issue by markburgessstl** [Microsoft/vscode#424]
The format code command seems to have been lost, unless I am missing something.  Please restore!

**Comment by Zhouzi** [comment]
You can press `cmd+shift+p` to search for a command. If you start typing "format", here is what you get:
<img width="599" alt="screen shot 2015-11-21 at 22 10 08" src="https://cloud.githubusercontent.com/assets/2291025/11320555/abdf08c6-909c-11e5-95e5-43d0ecbffa48.png">

So the shortcut is `shift+alt+f`

**Comment by jwulf** [comment]
It's visible for me for JavaScript files. For `.jsx` (JavaScriptReact) files, it's missing. It doesn't show up in the palette, and the keyboard shortcut does nothing.

**Comment by Zhouzi** [comment]
I might be wrong but from what I've found, the current support for jsx is limited to syntax highlighting. That's probably why you can't use the "format code" feature.

**Comment by markburgessstl** [comment]
OK, so it seems that if you don't have a launch.son file in a .vscode folder, the Format Code command is not available. (Again, I am using the Mac version. My project is Mono C#)  This seems like a problem.

**Comment by jwulf** [comment]
@markburgessstl - are you saying that in a Mono C# project on Mac OS X, you see "Format Code" as an option when you have a `launch.json` file in a `.vscode` folder in your project; and do not see "Format Code" when you don't have the `launch.json` file?

**Comment by markburgessstl** [comment]
Well, I was saying that but now I'm not so sure.  Now the "Format Code" command seems to be working.   If this happens again and I can constantly reproduce the problem I will post an update.  Otherwise please ignore/close this issue.
