### ISSUE TITLE
Handle dirty git submodules better

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42409]
Testing: https://github.com/Microsoft/vscode/issues/42341

Steps:
* have a simple repo with one submodule within
* in the submodule change to a another branch
* make some changes
* in the main repo try to stage or commit the submodule file

=> does not work

Commiting even shows an error:

![image](https://user-images.githubusercontent.com/900690/35560300-52699558-05ad-11e8-8026-9958c0fd6e06.png)

---

Also, can't stage or revert dirty submodule.

**Comment by joaomoreno** [comment]
This works!
