### ISSUE TITLE
Git: repositories view always expands very large in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42406]
Testing: https://github.com/Microsoft/vscode/issues/42341

I am always getting this view where the repositories list is having a very large size compared to the rest:

![image](https://user-images.githubusercontent.com/900690/35559697-a88f263e-05ab-11e8-8fe2-c99ae3c432f6.png)

Steps:
* clone repo in https://github.com/electron/electron
* it has many submodules in the "vendor" folder

**Comment by joaomoreno** [comment]
#41970
