### ISSUE TITLE
Log picker provides too little guidance

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42400]
re #40717

* run the Show Log Files command
* the picker isn't talking about logs but processes
* the current window should be reflected with its title, e.g. 'Window - vscode' instead of 'Window'
* the sorting is questionable because 'Main' and 'Shared' are less commonly understood by users

<img width="690" alt="screen shot 2018-01-30 at 09 45 37" src="https://user-images.githubusercontent.com/1794099/35558110-72dbdbee-05a7-11e8-85d1-0d894f7ca224.png">

**Comment by sandy081** [comment]
@jrieken 

> the picker isn't talking about logs but processes

Is to change the `placeholder` like `Select process log` or `Select log for process`?

> the current window should be reflected with its title, e.g. 'Window - vscode' instead of 'Window'

`vscode` tag is also applicable to other processes too. May be how about `Window (current)`?

**Comment by jrieken** [comment]
Nah, `vscode` was the folder/workspace I have opened

**Comment by sandy081** [comment]
{ id: Constants.sharedLogChannelId, label: nls.localize('sharedProcess', "Shared") },
![image](https://user-images.githubusercontent.com/10746682/35628441-348aee48-069c-11e8-92e8-c695719ba0c3.png)

Good enough?

**Comment by jrieken** [comment]
Yeah, I like. Maybe an upper-cases here and the 'Select Log for Process'
