### ISSUE TITLE
Syntax highlighting breaks with multiple string templates on one line

### ISSUE THREAD

**Issue by StrahilKazlachev** [Microsoft/vscode#4240]
- VSCode Version: 0.10.11

var result = condition ?  `` `${condition_true}core` : `${condition_false}core`;``
![vscode_backticks](https://cloud.githubusercontent.com/assets/5302492/13772133/2fe24db0-ea9b-11e5-8cb6-b1f9be433a54.jpg)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#127
