### ISSUE TITLE
Add option to reveal logs from within a channel

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42402]
re #40717

The test plan says

> Currently shown content is cleared and only show logs from that point.
-- Full content is shown after window reload.

which is easier said than done because if I clear the output for the window or extensions log they are gone (new logs are started). IMO it would be nice to reveal the log from within the channel

**Comment by sandy081** [comment]
@jrieken Won't this be inconsistent with other output channels?

**Comment by jrieken** [comment]
Well, it will be a Output Log Channel ;-) I am always confused that I don't have the command from within the panel and that I have to go through F1 again
