### ISSUE TITLE
Submodules: discard of "submodule" is a no-op?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42408]
Testing https://github.com/Microsoft/vscode/issues/42341

Should there be a message at least why you cannot discard changes to the submodule file or could we support it?

![image](https://user-images.githubusercontent.com/900690/35560163-e1f7182c-05ac-11e8-8481-896bab9e2f6d.png)

**Comment by joaomoreno** [comment]
This is the same as #42409. Your submodule is "dirty"
