### ISSUE TITLE
Border changes style when selected

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42419]
* open output panel
* select a channel -> picker is selected with a rectangle
* select something else -> picker border is a *rounded* rectangle

![jan-30-2018 11-30-06](https://user-images.githubusercontent.com/1794099/35561553-f5cbd24e-05b0-11e8-8e46-c98dc87a4786.gif)

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/39657
