### ISSUE TITLE
Allow to create new files as admin (Save as)

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42411]
Testing #40592

- Try to save a file in a directory where user has no permissions to save using `Save as...` option

Expected to see the option to Retry as admin

![image](https://user-images.githubusercontent.com/10746682/35560359-7b423700-05ad-11e8-8b71-170968c568ef.png)

**Comment by bpasero** [comment]
Currently only saving to an existing file is supported, you cannot create new files as admin.

**Comment by regs01** [comment]
Save As dialog won't even let try to save it. Save into Documents folder instead, it says.
