### ISSUE TITLE
Multiple dialogs can only be closed in exact order

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#42414]
Refs: #40590

Linux

1. Open two windows, in each open the help about dialog
2. Notice that you can only click ok in the second about dialog, not the first
3. Because of this my first window seems to be blocked since there is no way for me to unblock it (unless I go to the second window and click ok on tha bout dialog)

This also reproduces for reverting git changes in multiple windows. Those dialogs must be closed in reverse order how they got opened.

**Comment by bpasero** [comment]
@isidorn does that reproduce in stable too?

**Comment by isidorn** [comment]
@bpasero yes I can also repro in stable
