### ISSUE TITLE
Image zoom: now possible to pinch zoom into entire window

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42422]
Testing: #42130 

I now seem to be able to pinch zoom into the entire workbench:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/35562060-82deb7fe-05b2-11e8-95c0-5568222f96e2.gif)

**Comment by bpasero** [comment]
Moving to January as this is quite bad, maybe we should disable pinch zoom if there is no fix.

**Comment by mjbvz** [comment]
@bpasero I can't repo. Did you have `"editor.mouseWheelZoom": true` or some other setting enabled?

**Comment by bpasero** [comment]
@mjbvz this is on macOS using pinch zoom on the trackpad!

**Comment by mjbvz** [comment]
@bpasero That is what I tried and I can't zoom the whole workbench. You must be doing something different. Can you please take a look at this, or we can disable pinch to zoom altogether for this iteration

**Comment by mjbvz** [comment]
Possible fixed by 0d97fab352b0c70e50aecf03268a18bcd8fadd33
