### ISSUE TITLE
Split view: hide not transalted

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#42428]
Refs: https://github.com/Microsoft/vscode/issues/42324
Linux

1. Open vscode in some non english language
2. Explorer (or any split view) right click -> "Hide" is not translated

**Comment by isidorn** [comment]
Ok for some languages it is translated.
Might be that the translation is simply missing for korean and chineese

**Comment by dbaeumer** [comment]
Yes, discovered the same. @isidorn I will close the issue. If the strings is not translated yet I fill in the English version.
