### ISSUE TITLE
Image zoom: Wording feedback

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42420]
Testing: https://github.com/Microsoft/vscode/issues/42130

I find the "Whole Image" a bit weird, and liked the "Fit Image" better that we had before. Any reasons for the change?

**Comment by mjbvz** [comment]
We discussed this in the Redmond sitdown and the general consensus was that `Fit` was confusing, especially the first time you see it in the status bar. Any other ideas for that setting?
