### ISSUE TITLE
Retry as admin message goes in loop when selected Retry as admin

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42424]
Testing #40592

Linux

- Have a file `sample.txt` that has write permissions only for admin users
- From a guest user, open this file in two VS Code windows
- Edit this file in both windows
- Save it from the first window (Use Retry as Admin option)
- Try to save it from the second window which shows Retry as admin message
- Selecting Retry as admin goes in loop.

![kapture 2018-01-30 at 11 44 20](https://user-images.githubusercontent.com/10746682/35562207-f826324e-05b2-11e8-9eb1-8f53b5009f82.gif)

**Comment by sandy081** [comment]
@bpasero I did not get the file has changed on disk error. May be do following 

- Save it from first window (You see the message to retry as admin)
- Save it from second window (You see the message to retry as admin)
- From the first window, retry as admin. 
- From the second window, retry as admin

**Comment by bpasero** [comment]
Great catch.
