### ISSUE TITLE
Image zoom: alignment of zoom control to rest is uneven

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42425]
Testing: #42130

Somehow I feel that the "Whole Image" status bar entry is not aligned to the image dimensions to the side it seems to be lower:

![screen shot 2018-01-30 at 11 45 11](https://user-images.githubusercontent.com/900690/35562231-0a7eba4c-05b3-11e8-8cdc-073da823a7e3.png)

**Comment by mjbvz** [comment]
I checked and they are properly vertically aligned. The descenders on the `g` may be throwing it off. Somehow our standard status bar items don't seem to use lowercase `g`, `p`, `j`, or `q`s

What do you proposed? Shifting it up manually looks wrong. We could go ALLCAPS or perhaps small caps? I'm in favor of leaving as-is though

**Comment by bpasero** [comment]
Yeah you are right, maybe the issue is more that the status bar entry is disconnected from the other one, even though both talk about the image in some way. I am fine closing this.
