### ISSUE TITLE
changing the Twitter feedback setting has no immediate effect

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42429]
testing #41189 on Windows:

I was surprised that changing the setting "workbench.statusBar.feedback.visible" has no affect and requires a reload. Enabling the settings is immediate.

Since most other settings have an immediate effect, we should consider to show an alert.

A consequence of this issue is the following:
- set setting to false (Smiley still shows)
- click on Smiley to open form:
![2018-01-30_12-02-38](https://user-images.githubusercontent.com/1898161/35563118-f9f087e8-05b5-11e8-8a99-2e50a7b14e16.png)

Observe: checkbox does not reflect the state of the setting.

**Comment by weinand** [comment]
While continuing testing I noticed that in some situations the Smiley disappears correctly.
So, it seems that the intent is to update immediately.

**Comment by bpasero** [comment]
@weinand it will have an effect once you close the feedback dialog. can you try again with the settings opened at the same time to verify that something gets written? this might be a file watcher problem then in the end.

**Comment by weinand** [comment]
@bpasero yes, on closing the feedback form the visibility of the Smiley sis updated correctly.
The initial problem occurs when I change the setting via the settings editor.

**Comment by bpasero** [comment]
Good catch 👍
