### ISSUE TITLE
Image viewer should give an indicatin when a image is too large to present

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#42439]
https://github.com/Microsoft/vscode/issues/42130

Currently I simply get
<img width="381" alt="capture" src="https://user-images.githubusercontent.com/1931590/35564042-1b8c2e90-05b9-11e8-9aab-9897c3fdb076.png">

Would be good to know what the max dimensions are.

**Comment by mjbvz** [comment]
This is a file size limit, not an image dimension limit. We should makes this more clear

**Comment by bpasero** [comment]
Changed to:

![image](https://user-images.githubusercontent.com/900690/35608494-ab4e472a-0659-11e8-90b6-2a8fae7645e8.png)

**Comment by raulesgalindo** [comment]
I worked it too jeje
![image](https://user-images.githubusercontent.com/11840157/35609614-f4300b00-062b-11e8-8b08-8f525692560c.png)
