### ISSUE TITLE
Opening Terminal autocloses

### ISSUE THREAD

**Issue by Eventyret** [Microsoft/vscode#42430]
- OS Version:
Version 1.20.0-insider
Commit eed7e193125f3d4cfebe2089d1b2a9c674388754
Date 2018-01-30T09:51:29.494Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Steps to Reproduce:
Windows 10 Pro

1. Open VSCode
2. Try focus terminal (it auto closes)
3. Open problems the "bar" will stay
4. Clicking on terminal will close "the bar"

Does this issue occur when all extensions are disabled?: Yes

Tested with different terminals, Git bash, Powershell, 

checking Developer tools and you will get
`[uncaught exception]: TypeError: Cannot read property 'focus' of null
onError @ index.js:39`

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/42415
