### ISSUE TITLE
Terminal can't be opened

### ISSUE THREAD

**Issue by ParamitaDhyana** [Microsoft/vscode#42431]
### Issue Type
Bug

### Description

The terminal can not be opened after updating the latest version.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (eed7e193125f3d4cfebe2089d1b2a9c674388754, 2018-01-30T09:51:29.494Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2195)|
|Memory (System)|15.88GB (11.89GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.4
react-redux-react-router-snippets|dis|0.4.29
vscode-babel-coloring|dza|0.0.4
vscode-great-icons|emm|2.1.22
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
webpack|jer|2.0.2
docthis|joe|0.6.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|4.1.0
vscode-extension-auto-import|Nuc|1.4.1
convert-css-in-js|pau|1.0.0
material-icon-theme|PKi|3.2.2
sass-indented|rob|1.4.6
quokka-vscode|Wal|1.0.94

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by weinand** [comment]
Please upgrade to a more recent version.
