### ISSUE TITLE
Compare file option should be disabled when same file is selected from two groups

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42437]
Testing #41688

- Open a file in two different editor groups
- Multi-select the same file in two different groups

Compare command does not makes sense here. Also copy path can also just copy once.

**Comment by isidorn** [comment]
Agree with this limiation. However the context keys we are using have limited functionality.
Might look into fixing this is somebody else complains.

**Comment by isidorn** [comment]
Nobody complained, I also do not see this as a big limitation.
Closing as will not fix
