### ISSUE TITLE
Error while Downloading and configuring the .NET Core Debugger

### ISSUE THREAD

**Issue by dhnnjy** [Microsoft/vscode#4244]
- VSCode Version: 0.10.11
- OS Version: ubuntu 14.04-x64

After installing csharp extension, I'm getting message 'installation is successful'. But after that, there is this error,

    error: File '/home/dhananjay/.vscode/extensions/ms-vscode.csharp-0.3.6/NuGet.config' does not exist.
    dotnet exited with error code 1
    Error while installing .NET Core Debugger.

But C# is present in installed extensions list.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#96
