### ISSUE TITLE
Image zoom: Support diff editors too

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#42446]
Testing #42130

It is possible to compare 2 images in the diff editor and then I would expect 2 zoom controls, similar how we have 2 indications of the size:

![screen shot 2018-01-30 at 12 36 27](https://user-images.githubusercontent.com/900690/35564377-39883ec4-05ba-11e8-916b-c659f73e44cb.png)

**Comment by mjbvz** [comment]
The zoom level currently shows for whichever side of the diff view you last interacted with. Having two zoom controls in status bar is not great IMO.  We should see if there is a better way to present this

**Comment by bpasero** [comment]
@mjbvz maybe the zoom control should just zoom both sides at the same time?
