### ISSUE TITLE
Pinch to zoom doesn't work on Surface Book under Windows

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#42444]
Testing https://github.com/Microsoft/vscode/issues/42130

I couldn't zoom the image using touch input.

**Comment by warpdesign** [comment]
I confirm: `touch input` = pinch to zoom on the `screen`, not on the touch pad.

**Comment by mjbvz** [comment]
I'm closing this issue as we have not heard further feedback on it.

If someone has a surface book and wants to investigate fixing this, please let me know

**Comment by warpdesign** [comment]
@mjbvz I have a Surface Book and just tested with the latest VSCode: 1.34.0.

Pinch to zoom works but is inverted: doing the zoom-in gesture zooms out, while doing the zoom-out gestures zooms in.

**Comment by warpdesign** [comment]
Just had a brief look, both macOS and Windows 10 report positive `event.deltaY` values when zooming out and negative `event.deltaY` values when zooming in.

Is there some macOS specific code for handling the `wheel` event?

**Comment by warpdesign** [comment]
Had a look at the resourceViewer.ts file which seems to handle the zoom and noticed @hwhung0111 did two fixes 5 days ago (after the 1.34.0 was tagged): 4c1b302a934138a05f80f073f153430e41d6cf41 and da5f8383d987eaa408d0a72f82e94e6e8dccb158.

So I downloaded the latest insider build to see if it fixes the problem, and it does.

**Comment by hwhung0111** [comment]
I just installed the newest vscode insider (1.35.0). The pinch gesture works fine on my ASUS laptop. Does it only happen on Surfacebook?

**Comment by warpdesign** [comment]
@hwhung0111 as I said it's fixed in the latest insider build.

**Comment by hwhung0111** [comment]
@warpdesign Sorry, I didn't read it carefully.
