### ISSUE TITLE
Droping a language pack .vsix inside extensions folder does not pick up the language

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#42441]
Refs: https://github.com/Microsoft/vscode/issues/42324
Linux

1. Copy the .vsix into the extensions folder
2. Restart vscode multie times with --locale=ps 
3. The lanugage is not picked up

Note that the language gets nicely picked up if I properly install the extension from the "Install vsix" dropdown in viewlet.
However jus droping the .vsix into the extensions folder does not work. I was also not expecting this to work, but it is specified in the test plan item thus I tried.

**Comment by dbaeumer** [comment]
@sandy081 assuming you are not updating the languagepack.json file. Please ping if there is something you think I need to do.

**Comment by sandy081** [comment]
@isidorn Yes, dropping the .vsix folder should not work. This is a mistake in Test plan item/

Updated the test plan item, please try it again.
