### ISSUE TITLE
Add "language pack" to package.json categories

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#42450]
Refs: #42324

Open a package.json of a language pack, notice it has `"language pack"` under `"cateogories"`, however it produces a warning since the `package.json` is not aware of this category.

![screen shot 2018-01-30 at 12 40 18](https://user-images.githubusercontent.com/1926584/35564530-be0f4354-05ba-11e8-8307-46fd7fd9ccdb.png)

**Comment by sandy081** [comment]
@seanmcbreen @chrisdias  Before adding this to our json schema, I think do we need to add this new category `Language Packs` to the Market place?

**Comment by sandy081** [comment]
Duplicate of #43701
