### ISSUE TITLE
Open Editors: triggering Ctrl+Shift+C with selection throws

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42456]
Testing: #41084

* click on a file in "open editors" view
* trigger Ctrl+Shift+C (linux)

=> Cannot read property fsPath of undefined

![image](https://user-images.githubusercontent.com/900690/35565344-7e6456b0-05bd-11e8-9dd1-d3b6a2c0d481.png)

I think in stable this used to open the containing folder in the terminal.

**Comment by dbaeumer** [comment]
Works for me under Windows.

**Comment by raulesgalindo** [comment]
Ctrl+Shift+C, opens the containing folder in the terminal on linux, confirmed. What branch did you used?

**Comment by isidorn** [comment]
@bpasero works for me both on linux and mac. Can you please try with latest insiders
If you still see it let me know and we will investigate on your machine

**Comment by bpasero** [comment]
Seems fine now.
