### ISSUE TITLE
Integrated Terminal is not working!

### ISSUE THREAD

**Issue by ssahaxd** [Microsoft/vscode#42459]
- VSCode Version: 1.20.0-insider 
- OS Version: Windows 10  v-1709
---
After Updating cannot open Integrated Terminal, after pressing ctrl + `   the terminal window opens for a few sec and closes itself automatically.
Same happens if I try to open the integrated terminal the  View -> Integrated Terminal,
Also tried to open code as administrator but nothing helps.

**Comment by solidxsnake** [comment]
+1 here. This is a problem with the newest Insiders build (commit: eed7e193125f3d4cfebe2089d1b2a9c674388754, date: 2018-01-30T09:51:29.494Z)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/42415

**Comment by jtleaming** [comment]
I just had this same problem this morning.
