### ISSUE TITLE
Context menu actions don't change if auto save is disabled

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#42458]
Testing https://github.com/Microsoft/vscode/issues/41084

Form the test plan I was under the impression I should see a Save action in the context menu if auto save is disabled. I only see:

<img width="336" alt="capture" src="https://user-images.githubusercontent.com/1931590/35565429-cbf87f1e-05bd-11e8-8b7d-4bb81b2c8fbf.png">

**Comment by isidorn** [comment]
The save action should only be in the open editors view, not the explorer. Sorry if that is not clearly explained

**Comment by dbaeumer** [comment]
Create https://github.com/Microsoft/vscode/issues/42463 to add Save since I have the open editors section hidden.
