### ISSUE TITLE
Extract to constant in enclosing scope

### ISSUE THREAD

**Issue by makrem025** [Microsoft/vscode#42457]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Add a new JavaScript file with this content:
```
function multipleUrls() {
    const obj = {
        url: `some-common-url-prefix/not-common`
    };

    const obj2 = {
        url: `some-common-url-prefix/something-else`
    };
}
```
2. Select the text `some-common-url-prefix`
3. Press (on Mac) `CMD+.` to get the context menu with the `Extract to constant in enclosing scope` command. Click that command.
4. It now extracts the entire variable, instead of the text I selected. Ending up like this:
```
function multipleUrls() {
    const newLocal = `some-common-url-prefix/not common`;

    const obj = {
        url: newLocal
    };

    const obj2 = {
        url: `some-common-url-prefix/not common`
    };
}
```

NB: If I select all instances of `some-common-url-prefix` with `CMD-d`, and do the above steps, it only extracts the first variable, not all of them which is what I would expect. This should perhaps be reported as a separate issue?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21485
