### ISSUE TITLE
Command prompt not showing up

### ISSUE THREAD

**Issue by ayrtonvwf** [Microsoft/vscode#42455]
### Issue Type
Bug

### Description

Ctrl+' OR right click on folder > "Open in Command Prompt".
The Command Prompt appears and disappears in less than a second.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (eed7e193125f3d4cfebe2089d1b2a9c674388754, 2018-01-30T09:51:29.494Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X4 630 Processor (4 x 2813)|
|Memory (System)|4.00GB (1.31GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe E:\Ayrton\Sites\digi-arte\ayrton.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by solidxsnake** [comment]
Dupe: https://github.com/Microsoft/vscode/issues/42459

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/42415
