### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by vinodkpasi** [Microsoft/vscode#42461]
In one javascript file i written few methods.
I referred this javascript file in other javascript file.
Auto intellisense not displaying all the methods of first javascript file.
Do I need to configure anything in VS Code to enable the intellisense support?

**Comment by mjbvz** [comment]
Please try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your workspace with the contents:

```json
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This tells VS Code to treat all JS files in the workspace as part of the same project

**Comment by vinodkpasi** [comment]
I used jsconfig.json file but intellisense is not working
