### ISSUE TITLE
Action order in Explorer

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#42465]
Testing https://github.com/Microsoft/vscode/issues/41084

I would suggest to move the two compare actions below the rename and delete since they are less frequent.

**Comment by isidorn** [comment]
@dbaeumer this is how it was already in vscode stable. And I am not brave enough to break muscle memory of users. So will not do it.

**Comment by dbaeumer** [comment]
Since a context menu opens below the cursor position and these actions are less frequent I think we should consider the change.

**Comment by isidorn** [comment]
Reopening for discussion then.

@bpasero thoughts welcome

**Comment by bpasero** [comment]
Not sure, I think we looked at how Windows puts them, where they are also at the end:

![image](https://user-images.githubusercontent.com/900690/35570612-fb1f39ec-05cf-11e8-892a-89d44c424269.png)
