### ISSUE TITLE
Tasks invoked when using pwsh.exe integrated shell

### ISSUE THREAD

**Issue by agarstang** [Microsoft/vscode#42464]
- VSCode Version: 1.19.3
- OS Version: Windows Server 2016 (10.0 .14393.0)

Using PowerShell Core `6.0.1` (`pwsh.exe`) as integrated terminal inccorectly resolves the arguments to invoke the shell based on exe name when launching a task.

See: [L434-L447](https://github.com/Microsoft/vscode/blob/a0ac2afdb4a5b271aa09f9ee7f6f271ca7011966/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L434-L447)

```
> Executing task: d:\Documents\Dev\_Tasks\Task.ps1 <

/d : The term '/d' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ /d /c d:\Documents\Dev\_Tasks\Task ...
+ ~~
+ CategoryInfo          : ObjectNotFound: (/d:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

Steps to Reproduce:

1. Set the following settings:
```
"terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\6.0.1\\pwsh.exe",
"terminal.integrated.shellArgs.windows": [
        "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command"
    ],
```
2. Set the following `.vscode\tasks.json` to any `.ps1` file:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Terraform Plan",
            "type": "shell",
            "command": "${workspaceRoot}\\_Tasks\\Task.ps1",
            "presentation": {
                "reveal": "always",
                "panel": "dedicated",
                "focus": true
            },
            "problemMatcher": []
        }
    ]
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
In this case you need to use the shell options to tell a specific shell to the task and then you have full control over the command line arguments.

```
			"options": {
				"shell": {
					"executable": "C:\\Program Files\\PowerShell\\6.0.1\\pwsh.exe",
					"args": [
						"-NoProfile", "-ExecutionPolicy", "Bypass", "-Command"
					]
				}
			}

```

**Comment by dbaeumer** [comment]
Please note that the options are currently task only. I do have a issue to be able to globally set the shell for a task.
