### ISSUE TITLE
connot find module ...

### ISSUE THREAD

**Issue by HosseinAlipour** [Microsoft/vscode#42462]
the error is apparent enough, I have tried to install 'npm i -g typescript@next` and add it to vscode setting.
![image](https://image.ibb.co/h26fuR/vscode.png)

- VSCode Version:
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:36:34.867Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:windows 10

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Does this only happen in typescript@next? Also, please provide information about how your project is structured and your `tsconfig.json`
