### ISSUE TITLE
"Compare Selected": cannot bind key to?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42469]
Testing: https://github.com/Microsoft/vscode/issues/41084

I am trying to bind a key to "Compare Selected" to compare with the selected entry in the file explorer but it always opens an untitled file and the keybinding does not show up? I tried with `Ctrl+Shift+L` and `Ctrl+O.`

**Comment by isidorn** [comment]
Works for me both on mac and windows for both of your keybindinds
Can you doulbe check with latest insiders.

**Comment by bpasero** [comment]
@isidorn here is my keybindings file:

```json
{
    "key": "ctrl+l",
    "command": "selectForCompare"
},
{
    "key": "ctrl+shift+l",
    "command": "compareSelected"
}
```

Steps:
* click on a file
* press Ctrl+L
* arrow up
* press Ctrl+Shift+L

=> an untitled file opens for me
