### ISSUE TITLE
[js] should not remove whitespace after 'function'  

### ISSUE THREAD

**Issue by slawkacz** [Microsoft/vscode#4246]
- VSCode Version: 0.10.11
- OS Version: 10.11.3

Formatting JavaScript code causes whitespace remove after 'function' word. This is inappropriate behaviour considering previous versions of IDE. Should be some flag which allow user to set proper formatting for such situation.  

`
Before (0.10.6):
var foo = function () {};

Now: 
var foo = function() {};
`

**Comment by dbaeumer** [comment]
Moving to TS. They own the formatter settings for Salsa which we now use.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7543
