### ISSUE TITLE
Can't drag editor from explorer to open editors

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#42470]
Testing #41688

Shouldn't it be possible to do so? In the same way both areas can be dragged onto the editor pane.

**Comment by isidorn** [comment]
Yes this was possible around 6 months ago.
Though nobody complained since I removed it.
I know @bpasero was also touching this area.

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/535fc34ba442fc22bc02008c83fe4ee1ab38f23b
