### ISSUE TITLE
Call the value `first` instead of `never` for editor.selectSuggestions

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42477]
Testing #42329

`never` option looks as if suggestion will never be selected. But the purpose of this setting value is to always select first suggestion (Description tells the same).

So I think it is easy to understand if we call the value `first` or similar that conveys the meaning directly.

**Comment by jrieken** [comment]
We agreed on `editor.suggestSelection` with `first`, `recentlyUsed`, and `recentlyUsedByPrefix`
