### ISSUE TITLE
Loading a big file should not display infinite progress

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#42474]
Testing #42103

When I open a large (300MB) file, the editor shows infinite progress. It would be great if we could show finite, determinate progress, just like Sublime.

**Comment by bpasero** [comment]
If there is any kind of progress that the model can return to me we could try to hook this in.

**Comment by rebornix** [comment]
The only problem I have with the infinite progress bar is it's triggering many layout events and slowing down the file loading, I put more details in https://github.com/Microsoft/vscode/issues/42660 . 

If we know the file size in advance, then it's possible as while model building, we cache the content length.

**Comment by bpasero** [comment]
@rebornix ah, didn't see your comment until now. Should we just close #42660 and move this one to February to look into? I fear that perf issue is caused by CSS animations...

**Comment by rebornix** [comment]
Let's track it here. Finite progress bar looks appealing to me, the only thing we need to keep in mind is avoid perf issue of CSS animation (described in #42660, and it's somehow similar to the old blinking cursor).
