### ISSUE TITLE
Syntax Highlighting for Batch scripts doesn't handle percent escapes

### ISSUE THREAD

**Issue by pedro-w** [Microsoft/vscode#42472]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.3
vbscript|Dar|1.0.4
vscode-firefox-debug|hbe|1.0.1
copy-markdown-as-html|jer|1.0.0
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
debugger-for-edge|msj|0.4.1
svg-snippets|sid|1.0.1
markdown-pdf|yza|0.1.7

If a batch script references a file with a percent (%) sign in it, the percent needs to be doubled to escape it. VS code seems not to apply correct syntax highlighting to this.
![example](https://user-images.githubusercontent.com/22172519/35569576-55260742-05c4-11e8-8a62-4f2eb135eb9a.png)

---

Steps to Reproduce:

1. Save a batch file containing (for example) text `copy "50% done.txt" %K%`
2. Make sure Language Mode is Batch
3. See highlighting is not right  

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to mmims/language-batchfile#24
