### ISSUE TITLE
'Create jsconfig.json file...' should be 'Create jsconfig.json'

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4247]
Related to #4007

- VSCode Version:
- OS Version: Linux

Steps to Reproduce:

1. Open any .js workspace, get a notification
2. Notice the long action title 'Create jsconfig.json file...', I would go with a shorter version 'Create jsconfig.json', 'file' is superflous

![screen shot 2016-03-15 at 14 08 15](https://cloud.githubusercontent.com/assets/1926584/13778660/6720b700-eab7-11e5-8313-32c87bf0d390.png)

**Comment by jrieken** [comment]
duplicate
