### ISSUE TITLE
Cannot zoom out image on Ubuntu

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#42482]
Testing #42130

Clicking to zoom in works.
But Alt+Clicking does not work, as it is a gesture consumed by the OS (to move windows).

**Comment by mjbvz** [comment]
alt+shift+click seems to work. Gimp uses ctrl+click though, as do some windows programs. I'll switch over to use ctrl on those platforms but keep alt on mac since mac uses ctrl+click is for right click
