### ISSUE TITLE
Pressing Esc should dismiss drop down without changing selected item

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#42487]
### Issue Type
Bug

### Description

Open the output window
Click on the drop down
Press the down and up arrows to change the currently highlighted item.
Press Esc - the drop down closes and the currently highlighted item becomes the selected item
Expected - the drop down should close and the original selected item shoudl remain selected

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (eed7e193125f3d4cfebe2089d1b2a9c674388754, 2018-01-30T09:51:29.494Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|Memory (System)|7.89GB (0.83GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|yes|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.4.4
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.22
vscode-gutter-preview|kis|0.12.2
csharp|ms-|1.13.1
vs-keybindings|ms-|0.1.7
vsliveshare|ms-|0.1.0-preview.171
team|ms-|1.122.0
debugger-for-chrome|msj|4.1.0
addDocComments|ste|0.0.8
cordova-tools|vsm|1.3.3

</details>

Reproduces only with extensions

Found when testing: https://github.com/Microsoft/vscode/issues/40589

See how this dropdown works to contrast (I press Esc at the end):
![dropdown](https://user-images.githubusercontent.com/1704059/35571561-618ff334-05ca-11e8-91bf-a01cd04b90b1.gif)

**Comment by bpasero** [comment]
@cleidigh I guess somehwere in `showSelectDropDown` you should remember the currently selected index and in `onEscape` you should restore that item.

**Comment by cleidigh** [comment]
@stevencl 
@bpasero 
The custom select box behavior for Escape matches the original and current implementation of the native selectBox.  The active selection remains with Escape.

Do we want to change that?  Both custom and native?

**Comment by bpasero** [comment]
@cleidigh looks like you are right, the previous behaviour is the same as the custom behaviour. Though it seems to me that the true native behaviour is what @stevencl describes. If it is not a lot of work and a small PR, let's do it. Not high prio though.

**Comment by raygervais** [comment]
I'd like to take a crack at adding this feature if it's within the scope of what is wanted for the custom select box component. 

Again, just need some direction towards where I need to look in the code base and I'll get straight to it 💻 👍

**Comment by cleidigh** [comment]
@raygervais 
Let's tagteam this as I had already started.

Start by reviewing the select box files:
\src\vs\base\browser\ui\selectBox\selectBoxCustom.ts  etc

We have to change the keyboard controllers and used a cached selected option if Escape.
Why don't you start your focus on selectBoxCustom .
I am going to look at the native solution as that has several issues I have already been looking into.

**Comment by raygervais** [comment]
@cleidigh, 
Sounds good! 

Should I create a WIP PR so that you and I can discuss from there (after I review and attempt changes)?
Or post here code changes / suggestions?

**Comment by cleidigh** [comment]
@raygervais 
A WIP PR sounds great.  We can work off that together.

**Comment by raygervais** [comment]
Noted, will do tonight if I have a chance 👍
