### ISSUE TITLE
'Have a project and experience better IntelliSense and code navigation' needs polish

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4248]
Related to #4007

- VSCode Version:
- OS Version: Linux

Steps to Reproduce:

1. Open any .js workspace, get a notification
2. 'Have a project and experience better IntelliSense and code navigation' does not sound specific enough imho. I would mention JavaScript, and we never surface 'InteliSense' in UI, so I would go for 'suggestions'

So something like:
'Configure a JavaScript project and experience better suggestions and code navigation'

![screen shot 2016-03-15 at 14 08 15](https://cloud.githubusercontent.com/assets/1926584/13778660/6720b700-eab7-11e5-8313-32c87bf0d390.png)

**Comment by chrisdias** [comment]
"Create a jsconfig.json to enable richer IntelliSense and code navigation across the entire workspace."
