### ISSUE TITLE
Weird breakpoint setting behaviour 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42485]
re #42321

Take the extension snippet below and in the *debuggee* have a file with the content below. Then do

* open the files
* put cursor at the start of line fours
* invoke the command -> see three breakpoints on lines 4, 5, 6
* remove all breakpoints, move cursor onto line 5, invoke command again
* 🐛 no editor annotation appears, breaks are listed in the debug view

```ts
 vscode.commands.registerCommand('extension.sayHello', () => {

        if (vscode.window.activeTextEditor) {

            const { selection, document } = vscode.window.activeTextEditor;

            vscode.debug.addBreakpoints([
                new vscode.SourceBreakpoint(new vscode.Location(document.uri, selection.with(selection.start.translate(2), selection.start.translate(2)))),
                new vscode.SourceBreakpoint(new vscode.Location(document.uri, selection.with(selection.start.translate(1), selection.start.translate(1)))),
                new vscode.SourceBreakpoint(new vscode.Location(document.uri, selection.with(selection.start.translate(0), selection.start.translate(0)))),
            ]);
        }
});
```

(notice two empty lines at the bottom)

```
42
line 2
3,9,27
vier


````

![jan-30-2018 15-28-11](https://user-images.githubusercontent.com/1794099/35571367-368817ea-05d2-11e8-8451-2c020b33599e.gif)

**Comment by weinand** [comment]
@isidorn I can reproduce (even if line 5 and 6 are not empty).
Since Breakpoints are not verified (and you show them anyway in the Breakpoints view), I would expect that all breakpoints with valid location are shown in the gutter.

**Comment by isidorn** [comment]
Nice catch. The issue was that my breakpoint decorations were breaking because I went to the editor model to get the max column for an nonexistent line. In this case line 7.
Now I added a simple check if the line number is within range, if not I do not show it.
