### ISSUE TITLE
Touchpad Scroll works TOO fast.(No smooth scroll)

### ISSUE THREAD

**Issue by spiders-here** [Microsoft/vscode#42491]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1.Open a file in VS Code, 
2.Scroll using touchpad,

Machine: Lenovo Ideapad 320-15isk
Touchpad- Elan smart-apd

**Two finger scroll:**
![touch](https://user-images.githubusercontent.com/34307061/35572679-23311880-05fb-11e8-971a-5fb666ea179c.gif)

Scroll with mouse wheel/Scrollbar works fine.
**Scrollbar using pointer:** 
![scrollbar](https://user-images.githubusercontent.com/34307061/35572677-22cdd388-05fb-11e8-80f6-722bda825e93.gif)

adding removing extensions doesn't make a difference.

**Comment by bpasero** [comment]
I would say this is #13612
