### ISSUE TITLE
Variables are not resolved correctly in multi root compound launch configs

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42495]
testing #42036:

- create two folder workspace with this launch config in folder f1:
   ```
   {
	"type": "node",
	"request": "launch",
	"name": "Launch f1",
	"runtimeExecutable": "echo",
	"args": [ "root f1: ${workspaceFolder}" ],
   }
   ``` 
- and this launch config in folder f2:
   ```
   {
	"type": "node",
	"request": "launch",
	"name": "Launch f2",
	"runtimeExecutable": "echo",
	"args": [ "root f2: ${workspaceFolder}" ]
   }
   ``` 
- create a compound launch config in workspace settings:
   ```
   {
	"name": "Compound",
	"configurations": ["Launch f1","Launch f2"]
   }
   ``` 
- run "Compound"

Observe:
both variables resolve to the same value:
![2018-01-30_16-10-05](https://user-images.githubusercontent.com/1898161/35573679-15bc09e4-05d8-11e8-9339-f5d8bb82db88.png)

BTW, if the variables are qualified with the folder name, variables are resolved correctly.

**Comment by isidorn** [comment]
@weinand great catch and repro steps

**Comment by weinand** [comment]
works fine now.
