### ISSUE TITLE
Can't customize find match color in scrollbar

### ISSUE THREAD

**Issue by kavasto** [Microsoft/vscode#42496]
Version: 1.19.3
OS: Win 10

```
    "workbench.colorCustomizations":
    {
      "editorOverviewRuler.findMatchForeground": "#ff0000ff",
    }
```

I presume this is meant to color the find matches under the scrollbar. Doesn't seem to do anything.

**Comment by alexandrudima** [comment]
Indeed, it appears the find widget doesn't use this color, but only the global search...

**Comment by Skuriles** [comment]
Can confirm this. 
How can the find widget color be changed in scrollbar?

**Comment by kavasto** [comment]
Looks like this was fixed.
