### ISSUE TITLE
vscode not killing terminal on close

### ISSUE THREAD

**Issue by vlazh** [Microsoft/vscode#42492]
### Issue Type
Bug

### Description

Open terminal (Ctrl+J) then try close vscode window.
Setting "terminal.integrated.confirmOnExit": true.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (eed7e193125f3d4cfebe2089d1b2a9c674388754, 2018-01-30T09:49:48.999Z)
OS version: Linux x64 4.13.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|Load (avg)|1, 0, 0|
|Memory (System)|7.77GB (3.93GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-modules|cli|0.2.2

</details>
Reproduces without extensions

**Comment by agustinbcu01** [comment]
Happens also in windows. 


Visual Studio Code - Insiders

Version 1.20.0-insider
Commit eed7e193125f3d4cfebe2089d1b2a9c674388754
Date 2018-01-30T09:51:29.494Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
