### ISSUE TITLE
Hover message needs to be concise

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4249]
Related to #4007

- VSCode Version:
- OS Version: Linux

Steps to Reproduce:

1. Open any .js workspace, hover over the lightbulb in status bar
2. Notice the unusualy long hover text, compare it to the rest of the hover in the status bar. They are all very clear and short
3. I would change it to 'Configure JavaScript Project'

![screen shot 2016-03-15 at 14 15 01](https://cloud.githubusercontent.com/assets/1926584/13778851/5df5a9aa-eab8-11e5-8306-7c5bbe4e8df1.png)

**Comment by jrieken** [comment]
I picked what Chris proposed for the message
