### ISSUE TITLE
Intellisense and error squigglies do not take folders into account

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42499]
test #42036:

- create two folder workspace with this launch config in folder f1:
   ```
   {
	"type": "node",
	"request": "launch",
	"name": "Launch f1",
	"runtimeExecutable": "echo",
	"args": [ "root f1: ${workspaceFolder}" ],
   }
   ``` 
- and this launch config in folder f2:
   ```
   {
	"type": "node",
	"request": "launch",
	"name": "Launch f2",
	"runtimeExecutable": "echo",
	"args": [ "root f2: ${workspaceFolder}" ]
   }
   ``` 
- create a compound launch config in workspace settings:
   ```
   {
	"name": "Compound",
	"configurations": [
		{
			"folder": "f1",
			"name": "Launch f1"
		},
		{
			"folder": "f2",
			"name": "Launch f2"
		}
	]
   }
   ``` 
- in the workspace settings editor change the first name "Launch f1" in the "Compound" to "Launch f2".

Observe:
no error is shown (because names are verified independently from their folders). 

- now change the name to "Launch f3".

Observe:
error is shown (because no "Launch f3" exists anywhere).

**Comment by isidorn** [comment]
I acknowledge the bug but I do not plan to fix it in the forseable future
