### ISSUE TITLE
jsconfig.json guidance - give me option to never get prompted again

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4250]
Related to #4007

- VSCode Version:
- OS Version: Linux

Steps to Reproduce:

1. Open vscode repo and open any js file, notice the light bulb appearing in the status bar
2. Clicking on the status bar I get options to create a `jsconfig.json`, however since I have a TS project I do not want to do this. Instead I want an option to never do this and hide the light bulb for this workspace
3. So giving options like 'Create jsconfig.json', 'Later', 'Never' would make a nicer TS experience

**Comment by jrieken** [comment]
duplicate
