### ISSUE TITLE
Quick open shows weird truncation when highlighting matches

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#42501]
Using the open recent dialog, it seems to pointelessly truncate the last two characters of each folder name (most of these end in 'gui'):

![screenshot from 2018-01-30 15-39-25](https://user-images.githubusercontent.com/376658/35575558-960295c2-05d4-11e8-9a12-95ba4252bae7.png)

**Comment by bpasero** [comment]
I have seen this before in another issue but was never able to reproduce. Does it reproduce if you disable icons?

**Comment by Gruntfuggly** [comment]
Yes, turning off icons doesn't change it.

It seems to be something to do with the '-' character. For instance, if I type 'asl-e' it happens, but typing 'asl-g' it does not? 

Could be a regex issue...

**Comment by bpasero** [comment]
@Gruntfuggly are you able to share the sources with me to try to reproduce?

**Comment by bpasero** [comment]
@Gruntfuggly no, the history is somewhere else. Can you configure `"workbench.quickOpen.closeOnFocusLost": false` and then use dev tools to inspect the element that is cropped? I wonder if the entry already contains the "..." or if something else adds it.

![image](https://user-images.githubusercontent.com/900690/35580293-ecc60c2c-05e8-11e8-8687-af01d4994d94.png)
![image](https://user-images.githubusercontent.com/900690/35580306-f3a88ac4-05e8-11e8-89df-1ad305e9184b.png)

**Comment by bpasero** [comment]
@Gruntfuggly also when you scroll down that list, is there an entry which is so large that it maybe pushes the rest?

**Comment by Gruntfuggly** [comment]
It looks like **text-overflow: ellipsis** is comming from the monaco-icon-label class.

![screenshot from 2018-01-31 08-48-47](https://user-images.githubusercontent.com/376658/35613390-d2a7b810-0663-11e8-967d-d9aaa9c20e7b.png)

There are larger entries in the list further down which are wider that the dropdown, but these are present even when the text is not truncated.

**Comment by bpasero** [comment]
@Gruntfuggly that does not explain why the "..." shows in such a weird spot, e.g. I would expect to first fill the full available space and then show "...". See what I get:

![image](https://user-images.githubusercontent.com/900690/35615728-57c8ba3a-0673-11e8-9aa3-cac40ff14f54.png)

This could be a Chrome layouting issue after all. Can you check if the element is expanded to the full width?

**Comment by Gruntfuggly** [comment]
The **quick-open-row** div is full width. 
The **monaco-icon-label** div is truncated
The **quick-open-entry-description** span which fillows the monaco-icon-label div then takes up the remaining width.

This is the same for when there is truncation and when there isn't. The onlty thing that would appear to be different in our cases is that my description is shorter than the available width?

When using the inspector, I can't see anything obviously different from when it is truncated and when it isn't.

Some further clues maybe though - it only happens to certain file types:

![screenshot from 2018-01-31 10-07-57](https://user-images.githubusercontent.com/376658/35616941-a736cb3e-066e-11e8-9ca0-27e39c555893.png)

It is definitely not the icon though - it happens with no icon theme selected.

It only happens when I've typed a dash. I've tried lots of other combinations, but it's only with dash and certain other letters.

**Comment by Gruntfuggly** [comment]
One last clue - I think it is related to the showing the search term within the results. Below you can see that the entries highlighted with '-d' are truncated, but the one with '-D' is not.

![screenshot from 2018-01-31 10-13-16](https://user-images.githubusercontent.com/376658/35617242-91331864-066f-11e8-91fa-01dde7602d02.png)

I think it must be something to do with a pixel rounding error or something.

**Comment by bpasero** [comment]
I can reproduce on Linux when I have a file called `asl-emcs-ddu-profile-editor-g.js` and search for `-g` and I think it has to do with the fact that the highlight causes some characters to become slightly larger (because they show up in bold) and as such the entire label gets a "`...`" at the end because it now overflows.

/cc @joaomoreno if you have any idea how to fix this

**Comment by bpasero** [comment]
Some ideas:
* Fix flex in items (wrap a div around label and description in quick open with flex: 1 for description
* Remove weird display: flex for parent of file label that is not needed anymore?
