### ISSUE TITLE
editor.detectIndentation can not be disabled

### ISSUE THREAD

**Issue by kdong007** [Microsoft/vscode#42505]
- VSCode Version: Version 1.19.3 (1.19.3)
- OS Version: OSX 10.13.2

Steps to Reproduce:

my settings
{
  "editor.detectIndentation": false,
  "editor.tabSize": 4,
  "editor.insertSpaces": true,
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "eslint.autoFixOnSave": false,
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "files.exclude": {
    "**/.git": true,
    "**/.DS_Store": true,
    "ios": true,
    "android": true
  }
}

no other things like editorconfig exists in my project

my javascript all indent with 2 tabspace

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexandrudima** [comment]
@kdong007 Check if you have installed the Editorconfig extension. Does this reproduce when disabling all extensions?
