### ISSUE TITLE
Can't use "launch" setting in a language override

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42510]
I want to use "launch" to set a default configuration for js files, but I get "Unknown Identifier" when it's in a language override block. Should that be allowed?

```json
"[javascript]": {
        "launch": {
            "configurations": [
                {
                    "name": "Default Launch Program",
                    "program": "${file}",
                    "protocol": "inspector",
                    "request": "launch",
                    "type": "node"
                }
            ]
        }
    },
```

**Comment by roblourens** [comment]
This still reproes today

**Comment by weinand** [comment]
@isidorn if this actually works, it should be mentioned in the release notes and the debugger documentation.

**Comment by isidorn** [comment]
Seems to not work afterl all then.
Let's keep this as a feature request.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L704

fyi @sandy081

**Comment by sandy081** [comment]
This is language driven. You have to pass the language identifier to get the launch for that language.  Not sure how you want to show this in the drop down? Drop down changes with active editor?

**Comment by weinand** [comment]
@roblourens Even if this would work I do not understand what the semantics would be?
"F5" uses the currently selected launch config. It does not take the open editor into account.

**Comment by roblourens** [comment]
I guess I was thinking about how `[javascript]` and `${file}` both relate to the currently open file. I'm not sure it makes sense in general after all.

Ideally I would keep the current F5 experience for non JS files with no launch.json, where it prompts to pick a debug adapter. But yeah I'm not sure how that would work exactly.

**Comment by weinand** [comment]
no plans to work on this in the near future.
