### ISSUE TITLE
Test log output channel coloring random

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#42517]
Testing #40717

It is nice that the output channels use syntax coloring, but the coloring sometimes appears random (see below). Suggest to only color elements we understand, i.e., the header but not the body of the message.

![image](https://user-images.githubusercontent.com/172399/35580870-8d344952-05ea-11e8-9dff-c5fb860ecf9c.png)

**Comment by sandy081** [comment]
Assigning to January for investigation

**Comment by sandy081** [comment]
Since it is not important enough to fix during end game, moved to february

**Comment by rdumont** [comment]
For the record, this seems to be also breaking any previous colors in the output, as they get escaped.

For instance, this:
![image](https://user-images.githubusercontent.com/430448/36309623-874cb2ac-130c-11e8-9b53-41698063dbfc.png)

Should look like this:
![image](https://user-images.githubusercontent.com/430448/36309643-9d962bd8-130c-11e8-8515-4c34253fbb3a.png)

**Comment by sandy081** [comment]
@rdumont Agreed. Changed to bug.

**Comment by sandy081** [comment]
@rdumont This issue is for improving syntax highlight for vscode log channels and your issue is related to colouring in regular channels which is mentioned and fixed here #43271.

**Comment by sandy081** [comment]
Raised a request https://github.com/emilast/vscode-logfile-highlighter/issues/47 to support this.

**Comment by sandy081** [comment]
@egamma Updated to the latest grammar from vscode-logfile-highlighter and it highlights filesystem links properly. Check it out and let me know if that is good enough.

**Comment by chrmarti** [comment]
Verified. Filed #44808 for another edge case.
