### ISSUE TITLE
Settings search doesn't search in disabled extensions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42519]
testing #42380:

I was searching for the ESLint setting "autoFixOnSave".
I had ESLint installed and I was pretty sure that ESLint has an "autoFixOnSave" setting.
But search did not find anything.

After some investigation I noticed the the extension was disabled.

It would have helped if search would have shown results for disabled extensions.

**Comment by roblourens** [comment]
It didn't search in disabled extensions before, and I'd have to do some work to show settings that aren't currently registered. When we figure out how searching settings in extensions that aren't installed should work, then it would show up there.

**Comment by roblourens** [comment]
I think we should keep the current behavior.
