### ISSUE TITLE
Startup Performance regressed 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42513]
Startup performance between 1.19.3 and (todays) 1.20.0 release severely regressed from 1725ms to 2021ms. We should understand why. The value I am referring to is `"[main, renderer] start => workbench ready"` from 'F1 > Startup Performance'. I ran both versions, four times on fresh data and without extensions, like so (I have used one run to warm it up first):

```
jrieken:/Applications$ open Visual\ Studio\ Code.app/ --args --user-data-dir=/Users/jrieken/Desktop/data_stable/ --disableExtensions

jrieken:/Applications$ open Visual\ Studio\ Code\ -\ Insiders.app/ --args --user-data-dir=/Users/jrieken/Desktop/data_insider/ --disableExtensions
```

| 1.19.3 | 1.20.0 |
|---|---|
| 1791 | 2004 |
| 1764 | 2029 |
| 1664 | 2020 |
| 1682 | 2023 |

**Comment by rebornix** [comment]
Two long running tasks I noticed when reloading the window

Font info restore
![image](https://user-images.githubusercontent.com/876920/35606043-d1f4918e-0601-11e8-98de-0b20112a6fb2.png)

and when we have Welcome Page open

![image](https://user-images.githubusercontent.com/876920/35606049-e54a313a-0601-11e8-8621-0f50a0c0d73c.png)

**Comment by jrieken** [comment]
So from checking the startup tickers this points towards code loading... We did grew quite a bit this milestone (+186KB) but I don't think that alone explains it. Also extension host startup appears slower but I need to drill into what exactly we are measuring there 

![img_0306](https://user-images.githubusercontent.com/1794099/35617101-8c97d2ec-0677-11e8-8929-6c9e60b3e490.jpg)

**Comment by bpasero** [comment]
@jrieken one thing we did in 1.20 is to start the extension host earlier, as a fix for https://github.com/Microsoft/vscode/issues/41322

See: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L180 vs in 1.19: https://github.com/Microsoft/vscode/blob/release/1.19/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L118

**Comment by jrieken** [comment]
Yeah, but starting it earlier shouldn't make it slower but finish sooner...

**Comment by jrieken** [comment]
It should always be this period: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L403

```ts
perf.mark('willLoadExtensions');
this.extensionService.whenInstalledExtensionsRegistered().done(() => {
	perf.mark('didLoadExtensions');
});
```

**Comment by isidorn** [comment]
By bisecting vscode builds it seems this commit is to blame https://github.com/Microsoft/vscode/commit/04594c864be35281ff7eca15a6db2a5a735bb320

**Comment by dbaeumer** [comment]
The explanation is: the first read of the commit returned undefined resulting in not passing -no-lazy to the renderer process and resulting in not generating cached data for the render process.

**Comment by dbaeumer** [comment]
@isidorn can you verify when the new build arrive

**Comment by isidorn** [comment]
I have just verified that the startup slowdown is no longer present in the latest vscode insiders.
Great!
