### ISSUE TITLE
Sometimes settings search results are confusing

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42515]
testing #42380:

- open settings
- enter "mock" in the search box

Result:
![2018-01-30_17-55-30](https://user-images.githubusercontent.com/1898161/35579492-11a3c48c-05e7-11e8-9f8b-5b97178f4641.png)

Without any hint or visual cue it is really difficult to understand what is shown in the search result.
After analysing the results I got the impression that in some cases "mock" matched the word "mode". But for other results I have no explanation.

Overall a user might get the feeling that search is acting "strange".
Could we somehow indicate that if there are no exact matches, only fuzzy bing results are shown?

**Comment by roblourens** [comment]
We used to show the two types of results in groups, so you would know that the bing matches were fuzzy. Maybe there's another way we can communicate that. 

We can basically get an infinite number of low-scoring matches, at least for short queries that match other short words fuzzily. The top result here is scored 0.07 which is very low - It might have helped in this case to add a minimum score threshold, although sometimes long queries will match a correct result with a very low score.

cc @sandy081

**Comment by sandy081** [comment]
I think we need to make a decision when to show a result from bing search provider. IMO all above results are not helpful. It would be good not to show them. 0.07 score is too low to be considered.
May I know the examples of long queries with appropriate matches but low score... if they are appropriate matches why is the score low?

**Comment by roblourens** [comment]
Playing with this some, the score used to vary much more than it does now. I remember bad results with high scores and good results with low scores. For example I remember long queries like "how do I change the font family" returning `editor.fontFamily` with a low score due to the other words.

But there was some work done to normalize the scores across queries, and now a low score seems to be a much more reliable indicator of a bad result. I'll add a low threshold of .1.

**Comment by roblourens** [comment]
Actually I changed my mind. There are still cases of good results with low scores, at least once you get into fuzzy matches. For example, "sugest" returns good results under .1.

I think that any four letter word like "mock" will end up fuzzy matching a lot of words and it's hard to tell what's good.

**Comment by roblourens** [comment]
I don't think there's anything I can do to improve this right now, scores are not consistent enough to know that a certain score is always good or bad.
