### ISSUE TITLE
Save As not working

### ISSUE THREAD

**Issue by ragar005** [Microsoft/vscode#42512]
Ctrl+Shift+S not working in VS Code Insiders. Giving some red lines to drag.

**Comment by bpasero** [comment]
@ragar005 I cannot reproduce, can you share a video of what happens? And maybe your keybindings file and exact steps?

**Comment by isidorn** [comment]
@ragar005 also make sure you are on the latest vscode insiders since there were a lot of fixes in this area

**Comment by ragar005** [comment]
@isidorn Yes, I did updated with new latest build.

**Comment by ragar005** [comment]
@bpasero Sure, I will try to record a video and try to post. Thanks

**Comment by ragar005** [comment]
I am making sure if its just vs code and i have just found out that it is the same issue with other code editors too. Maybe something wrong with my system here at work. Sorry. I will figure it out. I think you can close this issue. Thanks
