### ISSUE TITLE
Cannot launch Terminal in VSCode Insiders

### ISSUE THREAD

**Issue by pmout** [Microsoft/vscode#42516]
- VSCode Version: 

Version 1.20.0-insider
Commit eed7e193125f3d4cfebe2089d1b2a9c674388754
Date 2018-01-30T09:51:29.494Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:
Windows 10 x64

Steps to Reproduce:

1. view -> integrated terminal or Ctrl+ç

It looks like the window tries to open but it closes instantly.
Works perfect before update to latest version.

Does this issue occur when all extensions are disabled?: Yes

**Comment by SwingCoder911** [comment]
I also had this problem. I did some debugging and the problem looks to be near the area of terminalService.ts, line 127. The script is trying to set focus on a terminal in the terminal array but for some reason the terminal array "this.terminalInstances" is empty.
![vscode_bugreport](https://user-images.githubusercontent.com/2496912/35582490-d6943072-05a3-11e8-8517-cfc2315a2a6f.png)

**Comment by minoseah629** [comment]
#42498 shows that there was a fix committed
