### ISSUE TITLE
Esc to unselect all files selected using cmd/ctrl + a in list view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#42511]
Verifying #22769

- In SCM view, do cmd/ctrl + a to select all files

Expected `Esc` to unselect them

**Comment by bpasero** [comment]
@joaomoreno the place to add this would be [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/commands.ts#L442), I wonder why we never added it for lists?

**Comment by raygervais** [comment]
I'd like to help resolve this files issue if no one is currently working on it. 👍
