### ISSUE TITLE
Don't show Node version detection message, except in exceptional cases

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42520]
We show a message like `Debugging with inspector protocol because Node.js v8.8.1 was detected.` every time debugging starts, when version detection happens. This is usually just noise, as most users are on Node 8+ versions. We should only show it when an old version of Node is detected, or some other unusual case happens, e.g. picking "inspector" because a runtimeExecutable is present.

**Comment by weinand** [comment]
- We should now make the "inspector" protocol really the default.
- "legacy" is only used in these cases:
   - attribute 'protocol' set to 'legacy'
   - version probing detects version < 8.0

So a "Node version detection message" is only needed when a user didn't request 'legacy' explicitly, that is in the version probing case.
