### ISSUE TITLE
Language id/name display for snippets should be consistent with language id/name elsewhere

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42529]
Testing #42330

`Change Language Mode` shows Language name with the language id in brackets along with icon
![image](https://user-images.githubusercontent.com/16890566/35585773-bc9e268c-05ad-11e8-989e-18dfe0817588.png)

The older `Open User snippet` shows the Language name

![image](https://user-images.githubusercontent.com/16890566/35585840-e3d4f5d2-05ad-11e8-9113-f80bc1e19c7b.png)

The new `Configure User Snippets` shows the language id with the language name in brackets

![image](https://user-images.githubusercontent.com/16890566/35585879-fe78335e-05ad-11e8-84af-3dbc97eed3d1.png)

The `Change Language Mode` shows the language list in the best way.

**Comment by jrieken** [comment]
I know but that's on purpose 🙊 The challenge is the intermixed global snippets which apply to many languages. I don't wanna have language names left and right or are suggesting to always use the id in brackets?

<img width="434" alt="screen shot 2018-01-31 at 09 05 54" src="https://user-images.githubusercontent.com/1794099/35611668-12d64c74-0666-11e8-9be2-a234f4030023.png">
