### ISSUE TITLE
Source control diff windows do not close properly

### ISSUE THREAD

**Issue by Erchamion** [Microsoft/vscode#42522]
### Issue Type
Bug

### Description

Step 1: open source control (using git).
Step 2: make a change to a file under source control and save the file.
Step 3: click on the file to view the diff
Step 4: now close the diff window.  

Expect:  
The diff window to close.

Actual:
The diff window remains open.  In order to close the window you can do one of two things:
  1.  Navigate to a different tab (if no other tabs are open see number two below) then click 'x' (close button) on the diff tab.
  2.  Single or Double click on the changed file in source control.  Wait a second then double click the file in source control or the tab itself to make it sticky.  Now click the 'x' button and the window should close properly.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (eed7e193125f3d4cfebe2089d1b2a9c674388754, 2018-01-30T09:51:29.494Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|15.92GB (7.13GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/42527
