### ISSUE TITLE
Closing a diff editor with the x button doesn't work until you click somewhere else

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#42527]
### Issue Type
Bug

### Description

1. Have a folder in your workspace with uncomitted changes

2. Go to the SCM viewlet and click on one of the file changes

3. Try to close the diff editor with the 'x' button - this appear to do nothing

4. Click anywhere else in the editor, and then hit the 'x' button - now the tab closes. 

See video: https://cl.ly/1U0R3s0G451R

There is no output from the developer console. 

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8cac1acd97466afc75c663dc1626d8562a9a3f3d, 2018-01-30T17:19:56.812Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.73GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron /Users/ggilmore/mess/src-merge/ -add|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces only with extensions

**Comment by gushuro** [comment]
This is still an issue in today's build (2018-01-31T17:16:58.361Z)

**Comment by isidorn** [comment]
This works in latest insiders.
@bpasero please verify
