### ISSUE TITLE
Sometimes adding a folder to a workspace causes the explorer viewet to be blank

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#42526]
### Issue Type
Bug

### Description

I can't reliably repdroduce this, but sometimes adding a folder to a workspace (with `code-insiders . -add`)  causes the explorer viewlet to be blank. 

The stack trace is complaing about this line: https://github.com/Microsoft/vscode/blob/b543a60cffb349ab96f546afa8ce3ef9786d97ea/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L782 - trying to call `isRoot` when `fs === null` is an error.

I'm not sure how this can happen, but this line: https://github.com/Microsoft/vscode/blob/b543a60cffb349ab96f546afa8ce3ef9786d97ea/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L803

has the `model.findClosest` call, which is apparently returning `null`. I don't know why it is returning null in this circumstance. 

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8cac1acd97466afc75c663dc1626d8562a9a3f3d, 2018-01-30T17:19:56.812Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by nicksnyder** [comment]
I have started to hit this issue myself.

**Comment by isidorn** [comment]
@ggilmore thanks for the great analysis.
Also not sure why this is happening, but for now I simply added a null guard in the isRoot check. We also pass that array to the tree to expand elements but the tree can handle null elements so it should be fine

@ggilmore @nicksnyder please let me know if you still see the issue in tomorrow's insiders. Thanks a lot
