### ISSUE TITLE
Linux: cannot watch large folders (ENOSPC)

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4252]
- VSCode Version: c4b514244e2651117b9990295730265f5b902436
- OS Version: Linux

Steps to Reproduce:

1. git clone https://github.com/Microsoft/TypeScript.git
2. you do not have to open any file, just wait a minute and notice multiple errors in developer console
3. I do not see this on OS X, only linux

Marking as important as I am not sure what does this potentially break. Extension host might be crashing.

![screen shot 2016-03-15 at 14 50 14](https://cloud.githubusercontent.com/assets/1926584/13779831/48c3e4de-eabd-11e5-8c4e-e393468c4b40.png)

**Comment by bpasero** [comment]
@isidorn this means the watcher is running out of handles, does the advise in http://code.visualstudio.com/Docs/supporting/faq#_linux-faq help?

**Comment by isidorn** [comment]
@bpasero that does not help, as my linux has that configured since forever

**Comment by bpasero** [comment]
@isidorn I think we are hitting the limits of what the OS can do...

**Comment by Tyriar** [comment]
@bpasero have you looked into [Watchman](https://facebook.github.io/watchman/) by Facebook? That's what [ember-cli](http://ember-cli.com/) uses.

**Comment by bpasero** [comment]
@Tyriar post GA I want to look into other options for watching on Mac/Linux. Though I believe if we change to adding watched folders one by one as needed by the UI, we can keep using chokidar. The expensive part in chokidar is watching large root folders recursively.

**Comment by Tyriar** [comment]
@bpasero I actually just ran into an `ENOSPC` when trying to build with `gulp watch` while running a single instance of `code ~`. Is watching the entire tree necessary? That's an enormous amount of files/processing when only a tiny subset of the files are likely being worked on.

**Comment by bpasero** [comment]
@Tyriar if you can find out any way to prevent this issue by increasing the file limit on Linux, we should update the existing entry at http://code.visualstudio.com/Docs/supporting/faq#_linux-faq

**Comment by Tyriar** [comment]
@bpasero Any reason the number is so small in the FAQ? It's apparently capable of much more http://stackoverflow.com/a/17437601/1156119

**Comment by bpasero** [comment]
@Tyriar good point! does it work with a higher number?

**Comment by Tyriar** [comment]
@bpasero yeah that fixes it. I'll update the docs, I'll also add how to load in the new config value without restarting.

**Comment by Tyriar** [comment]
Users should also be notified in a nicer way that this is how they increase the value. While we could do this set up as part of the .deb/.rpm packages, I would prefer to stay away from messing with global config files like that.

**Comment by bpasero** [comment]
@Tyriar nice, yes please update the docs. I think this is not a good situation to be in, so my suggested way forward is to reduce the number of file handles the watcher needs to install.

**Comment by Tyriar** [comment]
@bpasero :+1: 

Should you close this off (since it's solved by https://github.com/Microsoft/vscode-docs/issues/236) and make a new issue to explicitly stop watching entire directories trees when they're too large?

**Comment by bpasero** [comment]
I will leave this open and cleanup post GA, I have a bunch of watcher related issues for April.

**Comment by Tyriar** [comment]
Sounds good, I just put the docs PR up https://github.com/Microsoft/vscode-docs/pull/237.

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
Will be addressed in https://github.com/Microsoft/vscode/issues/3998
