### ISSUE TITLE
Global User snippets not working for jsonc language id

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42539]
Testing #42330

Add a global user snippet with `jsonc` in the scope
Open a json file, change the language mode to `jsonc`
Start typing the prefix of the snippet, see that the snippet doesnt show up.

If you add a snippet with `json` scope. It does show up in the `jsonc` file

**Comment by jrieken** [comment]
@aeschli How are json and jsonc determined? Is this a property on the text model?

**Comment by aeschli** [comment]
@jrieken They are just two separate language modes. See the definition here: https://github.com/Microsoft/vscode/blob/9a1f471ba620538386a23b28ed2d01ad85e700d0/extensions/json/package.json#L24

**Comment by jrieken** [comment]
The snippet services uses [`getLanguageIdAsPosition`](https://github.com/Microsoft/vscode/blob/b10cad5e0de47e35d15947cb4c246d00b650e82a/src/vs/workbench/parts/snippets/electron-browser/snippetsService.ts#L326) and for `jsonc` that seems to always be `json`. I guess this roots back from the grammar. 

<img width="481" alt="screen shot 2018-06-25 at 13 57 12" src="https://user-images.githubusercontent.com/1794099/41849067-f13f55ce-787f-11e8-82c9-352f9d09e9f5.png">

Starting with @aeschli

**Comment by Tyriar** [comment]
FYI this broke my theme when viewing settings.json as I targeted `json` specifically in a rule https://github.com/Tyriar/vscode-theme-generator/issues/53

**Comment by aeschli** [comment]
@Tyriar I'll come up with a compatible solution in #53010
