### ISSUE TITLE
Quickfix for installing @type removes installed modules

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42535]
Testing #42358

1. Have a workspace that already installs `request` and `lodash`
2. Have a file like so
```ts
import * as _ from 'lodash'
import * as req from 'request'
```
3. Quick fix anyone of them by installing `@types` dependency
4. Notice many installed modules in your `node_modules` are gone

Before:

![image](https://user-images.githubusercontent.com/4033249/35587778-a44013c4-05b3-11e8-92c6-2ce08cfad5ca.png)

After: 

![image](https://user-images.githubusercontent.com/4033249/35587766-9b4204d0-05b3-11e8-8d82-6ee062fb7fd6.png)

**Comment by octref** [comment]
This happens when you have a `node_modules` installed using yarn.

**Comment by mjbvz** [comment]
Thanks! Opened https://github.com/Microsoft/TypeScript/issues/21504 to track this upstream
