### ISSUE TITLE
Preserve flags (readonly, hidden) when overwriting a file that is readonly

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#42538]
- VSCode Version: 1.20 Insiders
- OS Version: Windows 10

Testing #40592

Steps to Reproduce:

1. Create a readonly file (attrib +r readonly.txt) in a user folder
2. Change the file and save.
3. You will see "File is write protected. Select 'Overwrite' to attempt to remove protection."
4. Click Overwrite and notice that the readonly protection is removed.
5. Now do the same sequence in an Admin folder such that you first need to do "Overwrite" and then "Overwrite as Admin". The readonly bit is preserved. 

Overwrite should act the same way in both scenarios and remove the readonly protection as described in the first prompt.

**Comment by bpasero** [comment]
@gregvanl I do this intentionally because I fear that a file that only an admin can change should preserve as much of its flags as possible simply because there could be a very good reason to have it that way. 

I would argue that maybe it should be the other way around and we should preserve all flags also when overwriting any normal file.

**Comment by gregvanl** [comment]
@bpasero I agree, I think simple Overwrite shouldn't remove readonly protection, just update the file contents. 
If the behavior is changed, we need to remember to also change the message.

**Comment by bldrdash** [comment]
I believe this relates to Samba issues as well

- #29195
- #36542

On 

- VSCode Version: 1.20.1
- OS Version: Windows 10
- Remote Drive: Samba 4

Before edit:
```bash
12116759 -rwxrw-r-- 1 cba cba 0 Feb 18 09:24 notepad.sh
12116760 -rwxrw-r-- 1 cba cba 0 Feb 18 09:24 vscode.sh
```

After editing with vscode and notepad respectively:
```bash
12116759 -rwxrw-r-- 1 cba cba 4 Feb 18 09:25 notepad.sh
12116760 -rw-rw-r-- 1 cba cba 4 Feb 18 09:25 vscode.sh
```
