### ISSUE TITLE
Suggestions for the prefilled comment in global snippets file

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42534]
Testing #42330

Comparing the pre-filled comment on the user snippets for the old kind vs the new kind

![image](https://user-images.githubusercontent.com/16890566/35587559-02274f62-05b3-11e8-82ad-4ba1c0ca516e.png)

- Add `Place your global snippets here` in the beginning
- Change `The scope defines in watch languages the snippet is applicable.` to `Add comma separated ids of the languages where the snippet is applicable in the scope field. If scope is left empty or omitted, the snippet gets applied to all languages.`

**Comment by roblourens** [comment]
`watch` -> `which`

Space between `inserted.` and `Possible`
