### ISSUE TITLE
"Open File" action appears in diff editor for custom schemes but does nothing

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#42532]
If I register a new scheme (call it `foo`) and open a diff editor with left resource `foo://1` and right resource `foo://2`, the git extension displays an "Open File" action (`git.openFile`), but clicking on it does nothing.

![image](https://user-images.githubusercontent.com/754768/35586276-4ea7ca28-05af-11e8-9936-103238bdffb4.png)

The when clause looks like this:
```
"when": "gitOpenRepositoryCount != 0 && isInDiffEditor && resourceScheme != extension && resourceScheme != merge-conflict.conflict-diff"
```

But the handling logic looks like this:
extensions/git/src/command.ts
```
if (arg.scheme === 'git') {
	uris = [Uri.file(fromGitUri(arg).path)];
} else if (arg.scheme === 'file') {
	uris = [arg];
}
```

Either (1) the git extension should not register the button in the cases that it will perform no action or (2) it should always open the URI.

I would prefer (1) but it looks like context key expressions neither support `resourceScheme == git || resourceScheme == file` nor `!(resourceScheme != git && resourceScheme != file)` 

I will submit a PR to do (2).

**Comment by joaomoreno** [comment]
Actually, there's going to be regex support for when contexts... so we could probably do something like `resourceScheme = /git|file/`. Right @jrieken ?

**Comment by jrieken** [comment]
Alsmost, don't forget the `˜`

**Comment by eamodio** [comment]
@joaomoreno any chance you could exclude the `gitlens-git` scheme, because it won't work for it either.

**Comment by joaomoreno** [comment]
@eamodio Great foresight, as always! Thanks!
