### ISSUE TITLE
Have different name for Quick Fix All suggestions

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42549]
Testing #42358

Here I found the Quick Fix All name a bit confusing. What it does is "Correct all spelling in this file" instead of "Change spelling to `toLocaleString` for all occurrences.

![image](https://user-images.githubusercontent.com/4033249/35591052-841c4a54-05bd-11e8-95e1-5a6dd2d99a14.png)

**Comment by mjbvz** [comment]
Yep, I agree this is confusing. We need a "fix all" version of the message from TS. Tracked upstream by https://github.com/Microsoft/TypeScript/issues/21380 upstream

**Comment by mjbvz** [comment]
Reopening since this is now fixed upstream but requires API adoption on our side

**Comment by octref** [comment]
Don't see this fixed yet. I'm on TS 2.9.1-insiders.20180525.

![image](https://user-images.githubusercontent.com/4033249/40812176-4a71e1f2-64e9-11e8-9699-7e6f72832f50.png)

**Comment by mjbvz** [comment]
This is only fixed in master. Will be in the next insiders build too

**Comment by bpasero** [comment]
Very cool 👍
