### ISSUE TITLE
Feature request: Scope to folder

### ISSUE THREAD

**Issue by eiva** [Microsoft/vscode#42546]
There few requests already both were closed without any notes about "why":

* https://github.com/Microsoft/vscode/issues/31368
* https://github.com/Microsoft/vscode/issues/17696

This is a really useful feature, especially after adding workspaces.

For example: I want to concentrate on one particular "Project" inside "workspace".
It's not a deal to open just this folder because there a lot of settings were made for workspace, not for the specific project.

**Comment by eiva** [comment]
It would be nice to see a duplicated issue which is not closed as a duplicate itself...

**Comment by zumpiez** [comment]
@eiva Not sure if you still care or not, but I believe that this was closed as a dupe of https://github.com/Microsoft/vscode/issues/41860

**Comment by eiva** [comment]
@zumpiez Thanks for the information.
