### ISSUE TITLE
Issue reporter "disabling all extensions..." grayed out. Should this be a hyperlink?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#42547]
- VSCode Version:1.20 Insiders
- OS Version: Windows 10

Testing #42351 

On the "Is this problem reproducible when extensions are disabled?" section, the "disabling all extensions and reloading the window" text is grayed out and looks like it should be a hyperlink to a document describing how to disable extensions with the --diable-extensions command line switch.

**Comment by RMacfarlane** [comment]
I disable the link if there are no enabled extensions. Perhaps it would be better to remove that line completely in this situation?

**Comment by RMacfarlane** [comment]
Closing this as as-designed
