### ISSUE TITLE
Quick Fix All does not show up for add import

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42540]
Testing #42358

After installing `lodash` and `@types/lodash`, have this in a TS file

```ts
assign
each
```

Quick fix all is not present for fixing both, which I think would be helpful.

![image](https://user-images.githubusercontent.com/4033249/35588319-2073dc40-05b5-11e8-86be-012296c2d586.png)

This one too:

![image](https://user-images.githubusercontent.com/4033249/35588467-9adc4972-05b5-11e8-890d-d77369e6189c.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21523
