### ISSUE TITLE
Issue reporter GitHub search often fails to return results

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#42545]
- VSCode Version: 1.20 Insiders
- OS Version:macOS

Testing #42351

As you type strings in the Title text box, sometimes there are hyperlinks in the Similar Issues list, but after a few strings it will stop producing results. For example, just re-typing "hidden" sometimes brings up results, sometimes not. Seems to fail after 3-4 queries. Waiting for results from the same string doesn't seem to help as if that query failed and a new string change (example type space) is needed to start a new query.

**Comment by RMacfarlane** [comment]
This is caused by hitting GitHubs rate limit for searching issues - only 10 searches can be done within a minute. I'll work on displaying something in the UI when this happens

**Comment by aeschli** [comment]
Verified that a label shows up. Message could be improved: https://github.com/Microsoft/vscode/issues/42725
