### ISSUE TITLE
jsconfig.json guidance: never getting 'configure excludes' on Linux

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4254]
Related to #4007

- OS Version: Linux

Steps to Reproduce:

1. open vscode repo, open any .js file, generate `jsconfig.json`
2. modify jsconfig.json such that nothing is excluded
3. Wait some time and trigger inteli-sense in .js -> notice exception
4. I am never offered to 'configure excludes', I only see this on Linux, it works nicely on OS X

![screen shot 2016-03-15 at 15 31 43](https://cloud.githubusercontent.com/assets/1926584/13781280/0b362b3a-eac3-11e5-84b1-1732d4314279.png)

**Comment by jrieken** [comment]
You must not have too many files cos we aren't on the latest TS server version.

**Comment by jrieken** [comment]
related to #4185

**Comment by isidorn** [comment]
Got it, but why does this work on OS X then?

**Comment by jrieken** [comment]
different nodejs versions?

**Comment by isidorn** [comment]
might be that...

**Comment by chrisdias** [comment]
I am not getting prompted on OSX.
Node version v4.3.1

Create a workspace using `ember new bigApp`
Open `app/app.js`
accept prompt to create `jsconfig.json`
edit `jsconfig.json` to remove folders from `exclude` section
reload window

result -> not prompted to add `exclude` information.

I see this in the console:   
```
//Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91 [Extension Host] Error: Service died.
    at /Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:187:46
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (/Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:186:37)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:137:31)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

here is my `jsconfig.json`:
``` json
{
	"compilerOptions": {
		"module": "commonjs"
	},
	"exclude": [

	]
}
```

**Comment by isidorn** [comment]
After upgrading my node version on linux I no longer see this
