### ISSUE TITLE
Minimizing the Issue Reporter locks VS Code

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#42548]
- VSCode Version: 1.20 Insiders
- OS Version: macOS

Testing #42351 

Steps to Reproduce:

1. Bring up the Issue Reporter
2. Yellow button to minimize the reporter

Screen goes black. Bring up VS Code from Dock Bar and Issue Report is in front of VS Code and unresponsive. Can't close, minimize or expand.

**Comment by RMacfarlane** [comment]
Fix was to remove setting the workbench as the parent of the reporter window, done in https://github.com/Microsoft/vscode/commit/683fcaa92bc43629f615a1971deeafdbf63d0ef6
