### ISSUE TITLE
Writing hidden files while running as Admin erases content

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#42542]
- VSCode Version: 1.20 Insiders 
- OS Version: Windows 10

Testing #40592

Steps to Reproduce:

1. Create a hidden file (attrib +h hidden.txt) in a protected location like Program Files
2. Open VS Code running from an Admin Command Prompt.
3. Make a file change and save.
4. Check the file on disk. It now has zero bits.

Doesn't repro with 1.19.3 or will running as normal user and getting the retry as Admin prompt

**Comment by gregvanl** [comment]
This also reproduces when simply writing hidden files in a non-protected user location.

**Comment by gregvanl** [comment]
Doesn't look like save is working in general for hidden files with 1.20. If you make a file change, close the file and reopen, the contents is gone.

**Comment by bpasero** [comment]
@gregvanl such a good find 👍
