### ISSUE TITLE
Cannot disable updates on OS X

### ISSUE THREAD

**Issue by CsBigDataHub** [Microsoft/vscode#42555]
- VSCode Version: 1.17.2
- OS Version: Sierra 10.12.3

Steps to Reproduce:

1. Install visual studio code.
2. In setting - "update.channel": "none"
3. Restart visual studio code.
4. Wait for Info message: Visual Studio Code will be updated after it restarts.

I am unable to get updates to disable on OS X.  I can set the user settings to use Update.Channel = None in this file $HOME/Library/Application Support/Code/User/settings.json (per Microsoft) , however updates do not actually get disabled.  Plus when I pre-populate this data in the user profile on first launch the user settings are actually never applied.

**Comment by joaomoreno** [comment]
Can you show me the full contents of the `$HOME/Library/Application Support/Code/User/settings.json` file?

**Comment by CsBigDataHub** [comment]
{
    "update.channel": "none"
}

This is the only thing in the settings.json.  The install process is to copy Visual Studio Code.app to applications then copy the settings.json to all users in $HOME/[User ID]/Library/Application Support/Code/User/settings.json and we copy the file to the user template.

After the install of the compiled package , Visual Studio Code.app does not see the user settings file and will update.

**Comment by joaomoreno** [comment]
> and we copy the file to the user template

What does this mean?

> After the install of the compiled package

What compiled package?

**Comment by CsBigDataHub** [comment]
What compiled package?
This means Visual Studio Code.app

We are trying to automate a process of installing VSCode and disabling updates.
So after dragging Visual Studio Code.app to the Applications folder, we have a file settings.json in server with 
{
"update.channel": "none"
}

We are going to replace the settings file from $HOME/[User ID]/Library/Application Support/Code/User/settings.json with the settings file from server before launching the application.

When we open VSCode for the first time we still are able to update the application and user settings are actually never applied.

**Comment by joaomoreno** [comment]
When you open VS Code, and press <kbd>Cmd ,</kbd>, the settings file should open. What's in it?

**Comment by CsBigDataHub** [comment]
Thanks, for some reason I could not reproduce the issue.
