### ISSUE TITLE
Settings search count doesn't refresh when commenting settings

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#42550]
In relation to https://github.com/Microsoft/vscode/issues/42378 

Sometimes when commenting/uncommenting a setting which matches the search, the count number doesn't get properly updated. 

It seems to happen only with the Toggle Comment command, before changing anything else in the settings. If you type a character in the settings.json, then the count number gets updated properly from that moment on(even when using toggle comment).

Steps to reproduce:

1. Open VS Code
2. Open settings
3. Perform a search with at least a match
4. Toggle comment on one of the lines that matched the search

**Comment by gushuro** [comment]
Probably related, if you perform a search, and then add one of the results to the settings using the pencil, the count doesn't get updated.
Again, if you interact with the .json (for example writing a character) the count updates properly

**Comment by roblourens** [comment]
I can't repro either right now, but I saw it when you showed me. Will keep open for now.

**Comment by roblourens** [comment]
Not really investing in the old settings editor anymore
