### ISSUE TITLE
Voice Over: "Read character" command not working in integrated terminal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#42559]
#42278

- VSCode Version: Version 1.20.0-insider (1.20.0-insider)
- OS Version: MacOS 10.13

Steps to Reproduce:

1. Enable voice over
1. In terminal
1. Focus on prompt
1. Trigger the `Read Character command` : VO+c (ctrl+option+c)

**expected**
Reads character at cursor

**Actual**
Does not. Says `"End of Text"`

Seems to work in MacOS terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This happens because the backing `textarea` and the cursor is not synced with the actual prompt as it's a very tricky problem. This would need a fairly robust solution to https://github.com/Microsoft/vscode/issues/20676

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/pull/2329

**Comment by rebornix** [comment]
I tried on macOS but still hear "End of text" all the time.
