### ISSUE TITLE
Global snippets from extensions are not read if language is not provided

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42553]
Testing #42330

When trying to contribute global snippets from extension, the below works, 
```
"snippets": [
     "language": "go",
     "path": "./snippets/tryme.code-snippets"
]
```
but the below doesnt
```
"snippets": [
     "path": "./snippets/tryme.code-snippets"
]
```

Doesnt the need to specify language here make the whole point of global snippets moot?

**Comment by jrieken** [comment]
Yeah, problem seems to be bad handling of the empty/missing scope...

<img width="519" alt="screen shot 2018-01-31 at 09 18 55" src="https://user-images.githubusercontent.com/1794099/35612100-ccf7e67a-0667-11e8-9f31-f9ebb28cd878.png">
