### ISSUE TITLE
Issue report mandatory field asterisk isn't themable 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#42569]
### Issue Type
Bug

#42351

### Description

It looks like the red is the same regardless of theme, maybe the same color as the text would be sufficient to avoid potential conflicts? Maybe just a lighter red in dark themes would suffice?

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8cac1acd97466afc75c663dc1626d8562a9a3f3d, 2018-01-30T17:28:33.081Z)
OS version: Linux x64 4.13.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3491)|
|Load (avg)|1, 1, 1|
|Memory (System)|62.83GB (56.57GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces only with extensions

**Comment by aeschli** [comment]
Verified that color 'inputValidation.errorBorder' is used
