### ISSUE TITLE
Multiselecting quickly sometimes doesn't take effect on slow VM

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42560]
Testing https://github.com/Microsoft/vscode/issues/41473

I can only repro this on my Linux VM which feels a little slow, and since speed seems to be the issue, it might be hard to repro.

- Have no files open
- Click file A in the explorer to open it
- Quickly ctrl+click file B to also select it
- Two files should be selected, but instead, file B is opened and only file B is selected in the explorer

If I wait for file A to open before ctrl+clicking B, it doesn't repro

**Comment by isidorn** [comment]
I could not repro this on my win and linux vm
Users seeing this can use as a workaround: "workbench.list.openMode": "doubleClick"

For now closing as will not fix. Will consider reopening if more users report this and the workaround does not work for them
