### ISSUE TITLE
Configure excludes polish

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4256]
Related to #4007

Steps to Reproduce:

1. Have a large workspace, generate a jsconfig.json that does not exclude anything, click on Configure Excludes in the status bar
2. You get the attached message
3. I propose the following changes:

* Rename "Configure excludes..." action to "Configure Excludes"
* In this particular case the suggestion is not very precise, why are we tryign to be smart here, the user should decide what to exclude himself imho
* The title of the project seems to be wrong - why not use the same we show in the explorer header, in this case 'vscode'

![screen shot 2016-03-15 at 15 35 26](https://cloud.githubusercontent.com/assets/1926584/13781547/0dbfbe1a-eac4-11e5-9e2c-e497966475ae.png)

**Comment by egamma** [comment]
:+1: 
While the algorithm to find large folders is nice. A user that configures the excludes knows where the generated js resources are. Therefore do not add the guessed folders to the message.

**Comment by jrieken** [comment]
I disagree, folks won't know to exclude things like `temp` folders which become giant because of a transient build step. node_modules et al are the obvious but we have been hurt more than once with those unusual folders

**Comment by jrieken** [comment]
> Rename "Configure excludes..." action to "Configure Excludes"

 I put the `...` because it opens a new UI element which I believe is the rule?

> In this particular case the suggestion is not very precise, why are we tryign to be smart here, the user should decide what to exclude himself imho

see above

> The title of the project seems to be wrong - why not use the same we show in the explorer header, in this case 'vscode'

Agree, it's the filename of the configuration but the action already takes you there...

**Comment by isidorn** [comment]
> I put the ... because it opens a new UI element which I believe is the rule?

Not sure where else in UI we use this rule? AFAIK we do not follow it in debug and task world
@stevencl opinions?

**Comment by jrieken** [comment]
![screen shot 2016-03-15 at 17 11 59](https://cloud.githubusercontent.com/assets/1794099/13784838/0e32293e-ead1-11e5-9876-567f3f0d9d40.png)

Like here for instance. Unsure if it's applies to message-actions?

**Comment by isidorn** [comment]
Yeah i was thinking more of action labels

**Comment by jrieken** [comment]
removed in the `...` with #4248

**Comment by egamma** [comment]
>I disagree, folks won't know to exclude things like temp folders which become giant because of a transient build step. node_modules et al are the obvious but we have been hurt more than once with those unusual folders

Good point but then let's use heuristics and not show just all folders including many files. Only mention the suspects 'temp' and 'tmp' if they are big.

**Comment by jrieken** [comment]
I'd approach it the other way around and not show folders like `src` or `test` and if that results to a case in which I have no folder left to propose exclusion for a generic message will show. 

And on the other hand tsserver will generate a similar message which blames the last folder (https://github.com/Microsoft/TypeScript/blob/release-1.8/src/compiler/program.ts#L1117)

**Comment by egamma** [comment]
Excluding well known source folders like `src` and `test` works for me.

**Comment by jrieken** [comment]
excluding `src`, `test`, and `tests` now

**Comment by isidorn** [comment]
Nice!
