### ISSUE TITLE
Issue reporter which background color is used?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#42567]
### Issue Type
Bug

#42351

### Description

Is the background color sourced from the file explorer? Maybe the default should be the same as the editor/welcome page/interactive playground?

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8cac1acd97466afc75c663dc1626d8562a9a3f3d, 2018-01-30T17:28:33.081Z)
OS version: Linux x64 4.13.0-31-generic

Reproduces only with extensions

**Comment by RMacfarlane** [comment]
Yeah, it's using the sidebar background color. Originally I had it as the editor background color, but the input boxes on the light colored theme blended into it. Those themes, and most of the provided themes, don't have a border color for inputs

**Comment by Tyriar** [comment]
Ok makes sense, feel free to close
