### ISSUE TITLE
Voice Over in terminal gets into focus loop when holding arrow

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42561]
#42278

### Issue Type
Bug

### Description
1. Enable voice over
1. In terminal
1. Get a few screens of output
1. Hold VO+left arrow to scroll through it

**Expected**
This scrolls through lines and continues when you hit top of the screen

**Actual**
Once we hit the top of the screen, the focus seems to go into a loop:

![jan-30-2018 14-32-05](https://user-images.githubusercontent.com/12821956/35595111-632ff108-05ca-11e8-8404-1f9c69a87d52.gif)

When pressing the arrow key one at a time instead of holding it down, everything works as expected

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8cac1acd97466afc75c663dc1626d8562a9a3f3d, 2018-01-30T17:19:56.812Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.83GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|yes|
|VM|0%|

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
@mjbvz to clarify, it didn't "trap" the focus after this happened when you pressed either up or down did it?

**Comment by mjbvz** [comment]
@Tyriar No, not for single presses. This only happened when holding the key down to select through multiple elements

**Comment by Tyriar** [comment]
@mjbvz but if you stop and press the other direction does everything go back to normal or did it get into a corrupted state? If the former then this is as good as we can do AFAIK.

**Comment by mjbvz** [comment]
Yes, if you stop everything is normal afterwards

**Comment by Tyriar** [comment]
Closing then as I couldn't see a way we could fix this, plus it's not disastrous if it happens, the user can just backtrack
