### ISSUE TITLE
Reveal in explorer should pre-select all or none of the selected items

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42576]
Testing #41473

- Multi select 2 files that are siblings
- Choose `Reveal in Explorer`
- The Explorer opens with only one of the 2 items pre-selected

Either neither should be selected, or both should be selected. Why choose the one that is alphabetically higher than the other

**Comment by mjbvz** [comment]
Ran into this as well. Another idea: open a separate window for each item, just like we do for items in different folders (not sure about this however, could be obnoxious)

**Comment by isidorn** [comment]
@mjbvz I think that would be too spamy
@ramya-rao-a this is a fair feature request that both should be selected

Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L390
Basically the `windowService` should also have `showItemsInFolder`

**Comment by oriash93** [comment]
I'm not sure is that simple.

https://github.com/Microsoft/vscode/blob/master/src/vs/platform/windows/electron-main/windowsService.ts#L424

As you can see, `windowService`'s  `showItemInFolder` method, calls `showItemInFolder` method from Electron's Shell class [(Docs here)](https://electronjs.org/docs/api/shell#shellshowiteminfolderfullpath), which says:
"Show the given file in a file manager. If possible, select the file." 
It can't support more than one file.
