### ISSUE TITLE
Bracketed property completions starting with whitespace

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#42572]
Regarding #42370
When an object has a property with a whitespace at the beginning, it doesn't show up as a suggestion when using dot.

<img width="203" alt="" src="https://user-images.githubusercontent.com/5607882/35596922-da862366-05d0-11e8-82f2-9424a8a1920e.png">

It does appear if you trigger autocomplete inside `['']` using ctrl+space

<img width="344" alt="" src="https://user-images.githubusercontent.com/5607882/35596850-774861a6-05d0-11e8-88ba-57b8eb876de8.png">

**Comment by mjbvz** [comment]
A little weird but actually by-design for backwards compatibility. See https://github.com/Microsoft/TypeScript/pull/20547#issuecomment-352517496
