### ISSUE TITLE
No keyboard equivalent of Ctrl/Cmd +Click when multi selecting

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42578]
Testing #41473

Ctrl/Cmd+Click is used to mutli select non consecutive items
There is no keyboard equivalent for this.

In #1023 @Tyriar suggests to use `Ctrl+Space` for this

**Comment by Tyriar** [comment]
I think ctrl+space is a windows and linux(?) thing, we should do whatever feels natural on the platform.

**Comment by ramya-rao-a** [comment]
I was testing on Windows and use of arrows followed by Ctrl+Space seems to be the norm

**Comment by usernamehw** [comment]
Duplicate of #41527 ?
