### ISSUE TITLE
Fast two double-click only registers as one double-click for workbench.list.openMode: doubleClick

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42571]
Testing #42323

When I'm using single-click mode, I constantly do a quick succession of two single-clicks to peek what's inside a folder.

However, if I do two quick double-click, it only registers as one double-click. It's the same behavior on both macOS / Win. Maybe reduce the debounce time a little bit?

**Comment by bpasero** [comment]
@octref I noticed the same but there is not much I can do. It looks like the third click will be recorded as triple click (event.detail === 3) and the fourth click will be a single click again. This is really what I get from the browser and I do not think I can change that.
