### ISSUE TITLE
Workspace highlighting can be misleading

### ISSUE THREAD

**Issue by juler69** [Microsoft/vscode#42577]
- VSCode Version:

Version 1.20.0-insider
Commit c4065a8ba5261456338f850a37e67732d98bf57a
Date 2018-01-05T08:06:27.790Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:

Steps to Reproduce:

1. Click on a file in the workspace, the file is highlighted
2. Hit the up or down arrow to progress to another file, the original file remains highlighted and the other file is highlighted less intensely.
3. Hit delete and the file I have moved to is the one that gets deleted, although visually I would expect the more intensely highlighted file to be the one being deleted.

This highlighting mimics the mouseover highlighting effect (although it is slightly different) but the outcome of each is not the same.

I guess I am just highlighting (pardon the pun) the fact that the highlighting does not always emphasize the file being deleted which has meant I have often deleted the wrong file by mistake.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
I would like to close as designed, this is entirely adjustable by the theme you have installed and even via settings.
