### ISSUE TITLE
Explorer: Disable "new file" and "new folder" actions when multiple items are selected

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42581]
#41473

### Issue Type
Feature Request

### Description

**Steps**
1. Multi-select multiple folders in the explorer.
1. Click on the "new file" action in the explorer sash

**Problem**
The "new file" action create a single new file in one of these folders. Should it instead be disabled when you have multiple items selected?

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8cac1acd97466afc75c663dc1626d8562a9a3f3d, 2018-01-30T17:29:05.837Z)
OS version: Windows_NT x64 10.0.17052

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz (6 x 1896)|
|Memory (System)|31.93GB (24.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
During the design of this feature we decided to still show actions which do not make sense in a mutli select environemnt. Examples are the ones you mentioned and rename.
All those actions work based on the "focused" element - which is basically the last one you clicked.

For now I will take no action on this one and we see if the users find this confusing.

**Comment by isidorn** [comment]
Closing since no user complained and due to my explanation above
