### ISSUE TITLE
Markdown Open preview action is not multi-select aware

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42583]
**Steps to reproduce**

1. Select multiple md files in the explorer
1. Trigger open preview

**Bug**
Only a single preview is opened

**Comment by bpasero** [comment]
Still just opens one preview for me.

**Comment by mjbvz** [comment]
The new behavior of md previews breaks the concept of this change as there can only be a single preview per group.

**Comment by mjbvz** [comment]
Closing this as no longer applicable due to how the new logic preview works. The alternative would be to try to open each file's preview in a separate editor group, which does not sound like a good experience
