### ISSUE TITLE
"Toggle inline view" doesn't do anything

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42589]
- Open diff editor
- Use ... menu
- "Toggle inline view"
- nothin doin :bug:

Related to https://github.com/Microsoft/vscode/issues/41940?

**Comment by bpasero** [comment]
@isidorn editorIndex is optional (the dropdown menu in the editor does not set it, only the group). I think that is causing an exception

![image](https://user-images.githubusercontent.com/900690/35607998-64ec38de-0657-11e8-9c66-4e69c83b3b5b.png)

Maybe check for all places that access `editorIndex` and make sure you check if the index is provided.

**Comment by isidorn** [comment]
@bpasero I checked your code and the `group.getEditor` should return null if I pass crap into it.
`editorIndex` can be `0` right? So I have to check with `types.isNumber(context.editorIndex)`

**Comment by bpasero** [comment]
@isidorn yeah I would throw in a call to "`typeof context.editorIndex === 'number'`"
