### ISSUE TITLE
Windows background update doesnt work sometimes

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42585]
Testing #41950

- Install an older version of VS code Insiders, enable `update.enableWindowsBackgroundUpdates` and reload
- After a while the gear has 1 notification, and it says `Install Update...`. Click it
- A notification says that installation is occurring in the background, the gear has an item  `Installing Update...` instead of `Downloading Update..` that is disabled
- After a while the gear has 1 notification, and it says `Restart for Update` instead of `Restart Now`. Click it,
- Code closes and Modal progress window shows up with `Updating VS Code ...`
- Code comes back, gear icon still has the `Install Update` item

Checked the version, its still the old one.
Repeated the above (all other than installing older version) a couple of times and in the last attempt, the update was actually successful

Re-installed the old version, and repeated the above steps, the update was now successful. I cannot repro the case where I was stuck in the older version.

But the text  `Installing Update...` instead of `Downloading Update..` and `Restart for Update` instead of `Restart Now` can be reproed everytime

**Comment by ramya-rao-a** [comment]
Also #41950 talks about `Downloading Update..`. Instead what I saw in Windows was `Installing Update...`

**Comment by joaomoreno** [comment]
#42433
