### ISSUE TITLE
javascript prompt

### ISSUE THREAD

**Issue by spitWind** [Microsoft/vscode#42596]
- VSCode Version:least
- OS Version:win10

Steps to Reproduce:

1. can't view interface ;
2.can't prompt interface  of Object; there is in file  name *.d.ts; but not show

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
@spitWind I am sorry, I do not understand what the problem is. Can you please provide more information, perhaps a screenshot, or more detailed steps.
