### ISSUE TITLE
Translation of "about" in zh-TW

### ISSUE THREAD

**Issue by FlandreDaisuki** [Microsoft/vscode#42599]
![visual studio code_001](https://user-images.githubusercontent.com/5981459/35610857-eb9e2aa4-069d-11e8-9045-641ef2530a87.png)

這邊指的應是 Node.js 的版本而非 **節點**

OS: Linux Mint 18.3

**Comment by danyeh** [comment]
Fixed in Transifex. https://www.transifex.com/microsoft-oss/vscode-editor/translate/#zh-Hant/$/135093796?q=node
Will be reflected in VS Code this week.
