### ISSUE TITLE
Weird TS suggestions for object literal key

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42591]
This code:

```ts
const z = [];
const x = z.map(y => ({
	
}));
```

- Start typing a property key in the object literal
- Get a suggestion for whatever you typed, when that name doesn't exist anywhere, and TS doesn't have a type for the object literal
- Keep typing, and the suggest widget pops up for **every other** keypress

![jan-30-2018 18-56-05](https://user-images.githubusercontent.com/323878/35602885-7b335d38-05ef-11e8-9386-82337b63f99a.gif)

**Comment by mjbvz** [comment]
Weird but seems unrelated to the new bracketed property logic as it also repos in 2.6

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/21580 to track this upstream
