### ISSUE TITLE
Reload Window is slower compared to 1.19

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42593]
Up to 1.19, after running `Reload Window` VS Code starts reloading immediately.
Current build has a ~0.5 second deplay between running the command and starting to reload, as reported by multiple team members from Redmond.
We should find out the cause.

Top is stable, bottom is current.

![reload](https://user-images.githubusercontent.com/4033249/35604322-975b9834-05f6-11e8-94a2-9f08387c62d3.gif)

**Comment by jrieken** [comment]
maybe related to https://github.com/Microsoft/vscode/issues/42513

**Comment by jrieken** [comment]
likely the sdylog issue

**Comment by joaomoreno** [comment]
Definitely spdlog. Duplicate of #42396

@jrieken I checked startup perf of spdlog and I couldn't find any differences from before the update.
