### ISSUE TITLE
Toggle Output is delayed compared to 1.19

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42594]
In 1.19, Cmd+J to toggle panel is almost instant. However today when testing #40716, I noticed Cmd+J is sometimes having a delay before performing the UI update.

Up is Stable, bottom is current.

![panel](https://user-images.githubusercontent.com/4033249/35604444-14d7c418-05f7-11e8-8126-a9575d2c1277.gif)

**Comment by rebornix** [comment]
spdlog.flush takes about 100ms.

**Comment by sandy081** [comment]
@octref Good finding
