### ISSUE TITLE
ctrl+shift+b运行输出会乱码，而f5正常，找不出原因。

### ISSUE THREAD

**Issue by HongLuDianXue** [Microsoft/vscode#42595]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
output-colorizer|IBM|0.1.2
MagicPython|mag|1.0.12
python|ms-|0.9.1
python|tht|0.2.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@HongLuDianXue I'm sorry I do not understand what is the problem. Can you please provide more details that we can try and reproduce ?
