### ISSUE TITLE
Sidebar can not be resized after integrated terminal set to vertical and do a global search.

### ISSUE THREAD

**Issue by eddylin** [Microsoft/vscode#42590]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
node-debug2|ms-|1.20.1

---

Steps to Reproduce:

1. Open vscode, create a new file.
2. Open intergrated terminal and set it to vertical.
3. Do a global search for like "hello".
4. Close integrated terminal then Sidebar can not be resized.

**Comment by Tyriar** [comment]
I can't seem to reproduce, maybe this has been fixed in 1.20? Any additional steps to help repro would be useful

**Comment by eddylin** [comment]
I can't reproduce it again, I think it is fixed in 1.20.

**Comment by eddylin** [comment]
I can't reproduce it again, I think it is fixed in 1.20.
