### ISSUE TITLE
Unable to find code-folding vertical bar to collapse and expand the functions in typescript and html

### ISSUE THREAD

**Issue by dhrubajrk** [Microsoft/vscode#42608]
- VSCode Version: 1.19.3
- OS Version: Windows 10

Steps to Reproduce:
1. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

![image](https://user-images.githubusercontent.com/9625385/35614291-8d650826-0694-11e8-96a9-818fc3b0958c.png)

**Comment by alexandrudima** [comment]
@dhrubajrk Did you use a screen reader ? We cannot communicate collapsed sections properly, so we disable the folding feature when a screen reader is attached. Did you change the setting `editor.folding` ?

**Comment by dhrubajrk** [comment]
Yes, I enabled the screen reader by mistake when I was working with JAWS and Windows Screen Reader. How do I disable the screen reader just for VS Code? `editor.folding` is set to true and `editor.showFoldingControls` is set to always.

**Comment by dhrubajrk** [comment]
Thanks a lot. Setting `editor.accessibilitySupport` to off has resolved the issue.
