### ISSUE TITLE
404 when reporting issue

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42603]
### Issue Type
Bug

### Description

The issue reporter opened a URI in the browser that shows a 404. It seems to have to do with the stacktrace included in the body, when I remove that it works:

https://go.microsoft.com/fwlink/?LinkId=534872&title=Cannot%20read%20property%20%27provideDecoration%27%20of%20undefined&body=%0A%23%23%23%20Issue%20Type%0ABug%0A%0A%23%23%23%20Description%0A%0ATypeError%3A%20Cannot%20read%20property%20%27provideDecoration%27%20of%20undefined%0A%09at%20%2Fusr%2Fshare%2Fcode-insiders%2Fresources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fnode%2FextensionHostProcess.js%3A534%3A586%0A%09at%20%2Fusr%2Fshare%2Fcode-insiders%2Fresources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fnode%2FextensionHostProcess.js%3A98%3A524%0A%09at%20new%20n.Class.derive._oncancel%20(%2Fusr%2Fshare%2Fcode-insiders%2Fresources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fnode%2FextensionHostProcess.js%3A75%3A657)%0A%09at%20Object.t.asWinJsPromise%20(%2Fusr%2Fshare%2Fcode-insiders%2Fresources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fnode%2FextensionHostProcess.js%3A98%3A487)%0A%09at%20%2Fusr%2Fshare%2Fcode-insiders%2Fresources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fnode%2FextensionHostProcess.js%3A534%3A551%0A%09at%20Array.map%20(native)%0A%09at%20e.%24provideDecorations%20(%2Fusr%2Fshare%2Fcode-insiders%2Fresources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fnode%2FextensionHostProcess.js%3A534%3A475)%0A%09at%20e._doInvokeHandler%20(%2Fusr%2Fshare%2Fcode-insiders%2Fresources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fnode%2FextensionHostProcess.js%3A579%3A983)%0A%09at%20e._invokeHandler%20(%2Fusr%2Fshare%2Fcode-insiders%2Fresources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fnode%2FextensionHostProcess.js%3A579%3A701)%0A%09at%20e._receiveRequest%20(%2Fusr%2Fshare%2Fcode-insiders%2Fresources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fnode%2FextensionHostProcess.js%3A578%3A836)%0A%0A%0A%23%23%23%20VS%20Code%20Info%0A%0AVS%20Code%20version%3A%20Code%20-%20Insiders%201.20.0-insider%20(8adf87c03d78597e385ef787e8fb1ef564f8995b%2C%202018-01-31T06%3A18%3A41.654Z)%0AOS%20version%3A%20Linux%20x64%203.13.0-108-generic%0A%0A%3Cdetails%3E%0A%3Csummary%3ESystem%20Info%3C%2Fsummary%3E%0A%0A%7CItem%7CValue%7C%0A%7C---%7C---%7C%0A%7CCPUs%7CIntel(R)%20Core(TM)%20i7-4770HQ%20CPU%20%40%202.20GHz%20(4%20x%202194)%7C%0A%7CLoad%20(avg)%7C0%2C%200%2C%200%7C%0A%7CMemory%20(System)%7C3.86GB%20(0.17GB%20free)%7C%0A%7CProcess%20Argv%7C%2Fusr%2Fshare%2Fcode-insiders%2Fcode-insiders%20--enable-proposed-api%7C%0A%7CScreen%20Reader%7Cno%7C%0A%7CVM%7C100%25%7C%0A%0A%3C%2Fdetails%3EExtensions%3A%20none%0AReproduces%20only%20with%20extensions%0A%0A%3C!--%20Generated%20by%20VS%20Code%20Issue%20Helper%20--%3E%0A

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (eed7e193125f3d4cfebe2089d1b2a9c674388754, 2018-01-30T09:40:57.870Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|18%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.0
autofilename|Jer|0.1.3
vscode-docker|Pet|0.0.23
regex|chr|0.1.0
ssh|chr|0.0.3
vscode-eslint|dba|1.4.4
ghlink|dt|0.0.6
tslint|eg2|1.0.24
rest-client|hum|0.17.0
vscode-azureappservice|ms-|0.5.1
vscode-azurefunctions|ms-|0.5.0
vscode-cosmosdb|ms-|0.4.0
azure-account|ms-|0.3.0
azurecli|ms-|0.4.0
github-issues-prs|ms-|0.9.0
vsliveshare|ms-|0.1.0-preview.202
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
vscode-versionlens|pfl|0.19.1
vscode-open-in-github|sys|1.6.0
i18n-sample|vaz|0.1.0

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
Looks like this is due to the size of the url. I was testing with the reportIssueUrl as GitHub directly instead of the fwlink, and GitHub supported urls of 4k+ characters - I'm able to load this query string fine when the base is GitHub. I'll add some more length related checks and see if there's anything I can do to reduce the length

**Comment by chrmarti** [comment]
There still is a range of lengths that don't trigger the reporter's length check and then end at the 404.

**Comment by RMacfarlane** [comment]
What lengths? Could you give an example url?

**Comment by chrmarti** [comment]
Not sure what lengths, but this one shows a 404: `https://go.microsoft.com/fwlink/?LinkId=534872&title=test&body=%0A%23%23%23%20Issue%20Type%0ABug%0A%0A%23%23%23%20Description%0A%0A123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890%0A%0A%23%23%23%20VS%20Code%20Info%0A%0AVS%20Code%20version%3A%20Code%20-%20Insiders%201.20.0-insider%20(3f8cf5311b631c5bc395df1e8b9c795358c1ef80%2C%202018-02-03T01%3A26%3A08.181Z)%0AOS%20version%3A%20Darwin%20x64%2016.7.0%0A%0A%3Cdetails%3E%0A%3Csummary%3ESystem%20Info%3C%2Fsummary%3E%0A%0A%7CItem%7CValue%7C%0A%7C---%7C---%7C%0A%7CCPUs%7CIntel(R)%20Core(TM)%20i7-4770HQ%20CPU%20%40%202.20GHz%20(8%20x%202200)%7C%0A%7CLoad%20(avg)%7C4%2C%203%2C%203%7C%0A%7CMemory%20(System)%7C16.00GB%20(0.07GB%20free)%7C%0A%7CProcess%20Argv%7C%2FApplications%2FVisual%20Studio%20Code%20-%20Insiders.app%2FContents%2FMacOS%2FElectron%7C%0A%7CScreen%20Reader%7Cno%7C%0A%7CVM%7C20%25%7C%0A%0A%3C%2Fdetails%3E%3Cdetails%3E%3Csummary%3EExtensions%20(20)%3C%2Fsummary%3E%0A%0AExtension%7CAuthor%20(truncated)%7CVersion%0A---%7C---%7C---%0AEditorConfig%7CEdi%7C0.12.0%0Aautofilename%7CJer%7C0.1.3%0Avscode-docker%7CPet%7C0.0.24%0Aregex%7Cchr%7C0.1.0%0Assh%7Cchr%7C0.0.4%0Avscode-eslint%7Cdba%7C1.4.5%0Aghlink%7Cdt%7C0.0.6%0Atslint%7Ceg2%7C1.0.24%0Arest-client%7Chum%7C0.17.0%0Avscode-azureappservice%7Cms-%7C0.5.1%0Avscode-azurefunctions%7Cms-%7C0.5.1%0Avscode-cosmosdb%7Cms-%7C0.4.0%0Aazure-account%7Cms-%7C0.3.0%0Aazurecli%7Cms-%7C0.4.0%0Agithub-issues-prs%7Cms-%7C0.9.0%0Avsliveshare%7Cms-%7C0.1.0-preview.202%0Adebugger-for-chrome%7Cmsj%7C4.1.0%0Avscode-versionlens%7Cpfl%7C0.19.1%0Avscode-open-in-github%7Csys%7C1.6.0%0Ai18n-sample%7Cvaz%7C0.1.0%0A%0A%0A%3C%2Fdetails%3E%0AReproduces%20only%20with%20extensions`

**Comment by ramya-rao-a** [comment]
The distro with the updated link didnt get updated in the release branch
Fixed with https://github.com/Microsoft/vscode/commit/ce8fa24b9276b3f4b0817f798692ed0068cfff6b
