### ISSUE TITLE
Commit message is lost when selecting a different view in Activity Bar

### ISSUE THREAD

**Issue by tomi** [Microsoft/vscode#42606]
- VSCode Version: Version 1.19.0 (1.19.0)
- OS Version: OSX 10.11.6 (15G18013)

Steps to Reproduce:

1. Select source control from activity bar
2. Write some commit message
3. Select explorer from activity bar
3. Select source control from activity bar

Does this issue occur when all extensions are disabled?: Yes

I just lost a long commit message because of this. Sometimes I need to check something when writing the commit message, and I wouldn't expect the commit message to be lost.

**Comment by joaomoreno** [comment]
#41232
