### ISSUE TITLE
Expansion state lost when reordering root folders through API

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42607]
### Issue Type
Bug

### Description

Testing #42195

I was rotating folders 1..n-1. The expansion state is always reset to the first level and no others being expanded.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8adf87c03d78597e385ef787e8fb1ef564f8995b, 2018-01-31T06:18:41.654Z)
OS version: Linux x64 3.13.0-108-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2194)|
|Load (avg)|0, 0, 0|
|Memory (System)|3.86GB (0.37GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --enable-proposed-api|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces only with extensions

**Comment by isidorn** [comment]
I will takle this as part of https://github.com/Microsoft/vscode/issues/29715
