### ISSUE TITLE
Feature request: //@ts-ignore style ignores for js syntax + ts / js ignore for entire function, etc.

### ISSUE THREAD

**Issue by babakness** [Microsoft/vscode#42604]
Request: please enable some way to disable JavaScript syntax checks for the next line of code as well as the next statement, entire function and entire class if possible.

Currently it seems to be an all or nothing ordeal with JS syntax checking

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/19573
