### ISSUE TITLE
A bug about search

### ISSUE THREAD

**Issue by ruixinMRK** [Microsoft/vscode#42601]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
path-intellisense|chr|1.4.2
vscode-jasmine-es5|dee|1.0.1
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
phpcs|ika|0.7.0
path-autocomplete|ion|1.8.1
svg|joc|0.0.9
vscode-postcss-sorting|mrm|3.0.1
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
better-less|rad|0.4.3
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7
stylelint|shi|0.32.0
svg-snippets|sid|1.0.1
JavaScriptSnippets|xab|1.5.0

---
When I work area there are multiple projects, I just want to search a project of the content, I filled out in the search function to include file, then search out the result of the current workspace file to open, there will be a few images below
[http://www.mcrspace.com/bugImg/one.png](url)
[http://www.mcrspace.com/bugImg/two.png](url)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
- Is that file (package.vue) open when you do the second search?
- Is it different if you use `./weixin_es6` in the include box instead?
