### ISSUE TITLE
Folding is not working in xml

### ISSUE THREAD

**Issue by ritoscue** [Microsoft/vscode#4260]
- VSCode `Version:0.10.11`
- OS Version:

Steps to Reproduce:

1.  Open File folding.txt in VS Code:
[folding.txt](https://github.com/Microsoft/vscode/files/174182/folding.txt)

2. select language xml
3. try folding
4. Result is like:
![folding](https://cloud.githubusercontent.com/assets/10951907/13783006/92161646-ea97-11e5-8b1d-58bddadfef2f.PNG)

**Comment by aeschli** [comment]
What you see is what's expected. The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand tags, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
