### ISSUE TITLE
Compounds: sync + parallel execution

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode#42611]
Hello,

Here is my scenario: I want to launch server and client using compounds, but the problem is that I want to bundle in debug mode before launching client.

A possible launch.json could be:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Server",
            "program": "${workspaceFolder}/server.js",
            "cwd": "${workspaceFolder}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "BundleClient",
            "program": "${workspaceFolder}/bundleclient.js",
            "cwd": "${workspaceFolder}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Client",
            "program": "${workspaceFolder}/client.js",
            "cwd": "${workspaceFolder}"
        }
    ],
    "compounds": [
        {
            "name": "Server/Client",
            "configurations": ["Server", ["BundleClient","Client"] ]
        }
    ]
}
``` 

There are other ways to achieve this, but I think such `launch.json` would be easier to configure where BundleClient, Client are executed synchronously.

Thank you in advance for your opinion.

**Comment by isidorn** [comment]
There might be already a feature request simliar to this. @weinand might you know which it is?

**Comment by weinand** [comment]
What exactly do you mean by "I want to bundle in debug mode"?

**Comment by Alphapage** [comment]
Instead of launching `BundleClient` then `Client` manually, I want to compound both. But the problem is compound executes in parallel, so client will be launched before being bundled.
So when BundleClient debugger stops, I need compound to launch client.
The goal is to be able to debug BundleClient+Client during the same session (this is just an example)
```
 "compounds": [
        {
            "name": "Server/Client",
            "configurations": ["Server", ["BundleClient","Client"] ]
        }
    ]
```

**Comment by weinand** [comment]
So is "BundleClient" really a program you want to debug or is it the task to "bundle" the client?
In the latter case I suggest to turn "BundleClient" into a real task and add it as a "preLaunchTask" to the "Client" launch configuration.

**Comment by Alphapage** [comment]
I want to debug "BundleClient": what I do for now is launching "BundleClient" in debug mode, then when finished, launching "Client" in debug mode (boring repetition).
I tried `npm run BundleClient && npm run Client` as a workaround, but the debugger stops after BundleClient without continuing with Client.
That's why instead of launching BundleClient manually, then Client manually, I think it would great to be able to queue BundleClient and Client as if it was a single debugging session.

**Comment by weinand** [comment]
so "BundleClient" and "Client" are two separate programs (running on two instances of node.js) and first you want to debug "BundleClient" until it terminates and then you want to debug "Client"?

**Comment by Alphapage** [comment]
Yes

**Comment by weinand** [comment]
Couldn't you just merge "BundleClient" and "Client" into one program that runs on one instance of node.js?

**Comment by Alphapage** [comment]
I think it will increase memory usage for Client which is unnecessary. And Client could be a browser app debuggable using vscode-chrome-debug.

**Comment by weinand** [comment]
We do not have plans to add this functionality to compound launches.
But you could do this in an extension by using the debug API.
