### ISSUE TITLE
Is there a way to open workspace from code in extension

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode#42610]
- VSCode Version: 1.19.2
- OS Version: Microsoft Windows [Version 10.0.16299.125]

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

Currently, I can open folder with `vscode.commands.executeCommand('vscode.openFolder', <folder-path>)` or open a single file with `vscode.commands.executeCommand('vscode.open', <file-path>)` in the extension, is there a way to open a workspace (`.code-workspace` file)?

I tried these ways with failure:

1. `vscode.commands.executeCommand('vscode.openFolder', <folder-contains-.code-workspace-file>)`
2. `vscode.commands.executeCommand('vscode.open', <.code-workspace-file-path>)`
3. `vscode.commands.executeCommand('workbench.action.openWorkspace', <.code-workspace-file-path>);`

Thanks.

**Comment by bpasero** [comment]
@Sneezry `vscode.openFolder` with the URI of the workspace file will do it.

**Comment by Sneezry** [comment]
I can verify that works on my side, thanks!
