### ISSUE TITLE
Unable to start VSCode 1.19.3 in X2go 

### ISSUE THREAD

**Issue by adityanp** [Microsoft/vscode#42619]
Hi All

I am unable to start VSCode on CentOS7 with x2go client with XFCE

- VSCode Version: 
1.19.3
7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
x64

- OS Version: CentOS Linux release 7.4.1708 (Core)

Steps to Reproduce:
when i run 
code --verbose 

[5124:0131/175252.364561:ERROR:gl_surface_glx.cc(411)] GLX 1.3 or later is required.
[5124:0131/175252.364615:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
[5124:0131/175252.367414:ERROR:gpu_child_thread.cc(324)] Exiting GPU process due to errors during initialization
[main 5:52:52 PM] Starting VS Code
[main 5:52:52 PM] from: /usr/share/code/resources/app
[main 5:52:52 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'sticky-quickopen': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false }
[main 5:52:52 PM] Resolving machine identifier...
[main 5:52:52 PM] Resolved machine identifier: 9c2805e8-2432-4739-b86b-bb3892eced82
[5093:0131/175252.694409:ERROR:browser_main_parts.cc(122)] X IO error received (X server probably went away)

I have tried fix given in [16994](https://github.com/Microsoft/vscode/issues/16994) ... No use.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3451
