### ISSUE TITLE
Find match count resets when switching editor

### ISSUE THREAD

**Issue by Miniwa** [Microsoft/vscode#42618]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Open file in editor.
2. Open Find (Ctrl-F), search for something inside the file.
3. Press F3 to move to the next match.
3. Switch editor window.
4. Switch back to the original editor, Find match count is graphically 1, but pressing F3 again will still move to the next match (3 if you were at 2).

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Right now we don't have any state persistence for find widget in editors. We may consider this again in the future.
