### ISSUE TITLE
[html] formatter option "html.format.unformatted" doesn't work

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4262]
testing #4066

- use this html:
```html
<HTML><HEAD><TITLE>Your Title Here</TITLE></HEAD><BODY BGCOLOR="FFFFFF"><CENTER><IMG SRC="clouds.jpg" ALIGN="BOTTOM"> </CENTER><HR> <a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site<H1>This is a Header</H1><H2>This is a Medium Header</H2> Send me mail at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>.<P> This is a new paragraph!<P><B>This is a new paragraph!</B><BR><B><I>This is a new sentence without a paragraph break, in bold italics.</I></B><HR></BODY></HTML>
```

- change `html.format.unformatted` from `null` to `B` and format code

Observe: 

```html
<HTML>

<HEAD>
	<TITLE>Your Title Here</TITLE>
</HEAD>

<BODY BGCOLOR="FFFFFF">
	<CENTER>
		<IMG SRC="clouds.jpg" ALIGN="BOTTOM"> </CENTER>
	<HR>
	<a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
	<H1>This is a Header</H1>
	<H2>This is a Medium Header</H2> Send me mail at
	<a href="mailto:support@yourcompany.com">support@yourcompany.com</a>.
	<P> This is a new paragraph!
		<P>
			<B>This is a new paragraph!</B>
			<BR>
			<B>
				<I>This is a new sentence without a paragraph break, in bold italics.</I>
			</B>
			<HR>
</BODY>

</HTML>
```

- change `html.format.unformatted` back to `null` and format code:

Observe: no difference to previous

**Comment by weinand** [comment]
With the fix I now see a difference, but the difference does not make any sense to me:

`html.format.unformatted =  B`

![2016-03-23 14-24-43](https://cloud.githubusercontent.com/assets/1898161/13986537/3c9eaaa8-f103-11e5-9388-297658702874.png)

`html.format.unformatted =  null`

![2016-03-23 14-24-28](https://cloud.githubusercontent.com/assets/1898161/13986547/4410cf82-f103-11e5-8998-d67cf271d648.png)

**Comment by aeschli** [comment]
As spec'ed in the settings comment, 'null' defaults to all inline tags.
B is one of the inline tags, so no difference on the formatting here.
HR and A are also, that's why they were put on its own line in the first screenshot, but not in the second.

I verified that we correctly pass the options to beautify-html.

**Comment by weinand** [comment]
@aeschli thanks, now I understand.
