### ISSUE TITLE
Support alt+shift+<key> and alt+ctrl+<key> sequences in terminal

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#42629]
- VSCode Version: 1.19.3
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. run terminal, hit `shift + alt + 3`
2. actually `alt + 3` passed to terminal

`shift + alt + 3` shortcut types `#` in the start of a line and hits enter. Handy shortcut

**Comment by Tyriar** [comment]
To get the shift+alt+3 command (default `workbench.action.moveEditorToThirdGroup`) to work within the terminal you will need to add it to the whitelist of commands that skip the shell `terminal.integrated.commandsToSkipShell`.

**Comment by Yanpas** [comment]
That didn't help

**Comment by Tyriar** [comment]
@Yanpas what do you expect to happen when you hit shift+alt+3?

**Comment by Yanpas** [comment]
I expect this:
![peek 2018-02-01 13-58](https://user-images.githubusercontent.com/7345761/35675189-32befa84-0758-11e8-89ba-0f52a44a4412.gif)

**Comment by Tyriar** [comment]
Oh, you *want* it send to the term. This will need to be supported upstream in xterm.js, please create an issue there. I'll close this off as this is a very specific request about sequence support in xterm.js.

**Comment by Tyriar** [comment]
To verifier, see https://github.com/xtermjs/xterm.js/issues/1267 for key strokes outside of shift+alt+3 to test.
