### ISSUE TITLE
The Chinese language will output ʱ���....

### ISSUE THREAD

**Issue by CareSzy** [Microsoft/vscode#42628]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
php-intellisense|fel|2.2.5
code-runner|for|0.8.7
changeEncode|lan|0.0.8
vscode-clang|mit|0.2.2
python|ms-|0.9.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1

---

Steps to Reproduce:

  
1.The Chinese language will output ʱ���....

#!/usr/bin/python
# -*- coding: UTF-8 -*-
 
import time; 

ticks = time.time()
print ("时间戳:", ticks)
2.Run Code
![image](https://user-images.githubusercontent.com/35266951/35626416-a50a70ba-06d0-11e8-8feb-2eb40ffe2bfe.png)

![tim 20180131215201](https://user-images.githubusercontent.com/35266951/35626532-feb7b33e-06d0-11e8-94c8-8e5d32a8d082.png)

Reproduces without extensions: Yes

**Comment by shibang** [comment]
I meet the same problem, Chinese language will turned to "���" or other characters like "ćľčŻ" after save!!!

**Comment by shibang** [comment]
你看看你的 VSCode 右下角的编码是不是 UTF-8，如果不是的话改一下，然后保存运行看看

**Comment by Tyriar** [comment]
@isidorn might be an issue with displaying unicode in the output panel. If we support that I'm guessing it's an issue with https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner

**Comment by isidorn** [comment]
Ansi characters are supported in the output channel since it is just an editor.
@shibang please file this against the extension you are using
@sandy081 fyi
