### ISSUE TITLE
Clicking middle mouse button on a tab title closes the currently open tab, instead of the hovered one

### ISSUE THREAD

**Issue by tomrav** [Microsoft/vscode#42622]
- VSCode Version: 1.20.0-insider
- OS Version: OS X 10.12.1
Does not appear to happen in the non insiders version.

Steps to Reproduce:

1. Open two files, in two tabs
2. Click on the first tab so it is active
3. Hover over the tab label for the second file
4. Click middle mouse button (scroll button)

Expected: Hovered file to be closed
Actual: Currently active window is closed

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/42518
