### ISSUE TITLE
Terminal window closing immediately

### ISSUE THREAD

**Issue by polatengin** [Microsoft/vscode#42627]
### Issue Type
Bug

### Description

Open **VS Code Insiders** with latest updates applied.

*Ctrl+"* keyboard shortcuts or *View*/*Integrated Terminal* menu or right clicking on a file in explorer and choosing *Open In Command Prompt* opens **Terminal** but closes immediately.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (648c46deeeda61fad44ce188684dcb61838b724a, 2018-01-31T10:13:25.946Z)
OS version: Windows_NT x64 10.0.17083

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|31.89GB (20.50GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
csharp|ms-|1.13.1
vscode-docker|Pet|0.0.23
vscode-icons|rob|7.19.0
unity-debug|Uni|1.2.1

</details>
Reproduces only with extensions

**Comment by jtleaming** [comment]
I was having similar issues today. Saw there was a resolution from Integrated terminal doesn't open #42415 but it did not resolve the issue for me.

**Comment by jtleaming** [comment]
<iframe src="https://giphy.com/embed/26wkxvS4gSl5rhaxi" width="480" height="256" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/26wkxvS4gSl5rhaxi">via GIPHY</a></p>

**Comment by jtleaming** [comment]
![](https://media.giphy.com/media/26wkxvS4gSl5rhaxi/giphy.gif)

**Comment by ciruz** [comment]
I can confirm, just updated insiders (9affae559e7b6dd46acfe2ac3123fb0ea87c6615) and I still get this error.

**Comment by jochenvanwylick** [comment]
+1 same problem here

**Comment by Tyriar** [comment]
Should be fixed now

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/42711

**Comment by jochenvanwylick** [comment]
Fix worked for me on Win10 with
![image](https://user-images.githubusercontent.com/3002474/35724851-8661755c-07ff-11e8-85d1-575b448480fa.png)
