### ISSUE TITLE
Renaming first folder restarts extension host

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42625]
### Issue Type
Bug

### Description

Testing #42195

Shouldn't be necessary to restart the extension host when only the name of the first folder changed, should it?

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (010de7da99e63841dfe5bc5a45ce1509f9fd1479, 2018-01-31T09:45:32.303Z)
OS version: Linux x64 3.13.0-108-generic

Reproduces without extensions

**Comment by bpasero** [comment]
This is a consequence of only having methods to add or remove folders but not to update them (to change their name). Imho not a big deal though.

/cc @sandy081

**Comment by bpasero** [comment]
This is actually the same as https://github.com/Microsoft/vscode/issues/42639
