### ISSUE TITLE
Unexpected events for single updateWorkspaceFolders operation

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42639]
testing #42195:

- workspace with 4 folders f1, f2, f3, f4
- code that swaps f2 with f3 (but removes and adds f4 unnecessarily):
   ```js
   const folders = vscode.workspace.workspaceFolders;
   vscode.workspace.updateWorkspaceFolders(1, folders.length-1, folders[2], folders[1], folders[3]);
   ```

For this single operation I get these two events:
onDidChangeWorkspaceFolders: added: 0, removed: 3
onDidChangeWorkspaceFolders: added: 3, removed: 0

I would have expected to only receive a single event:
onDidChangeWorkspaceFolders: added: 2, removed: 2

(or even better a single changed event:
onDidChangeWorkspaceFolders: added: 0, removed: 0, changed: 2
)

Another case:
renaming a folder with this code:
```
        const folders = vscode.workspace.workspaceFolders;
        vscode.workspace.updateWorkspaceFolders(1, 1, { uri: folders[1].uri, name: folders[1].name + 'x' });
```
results in two events too.

**Comment by bpasero** [comment]
Yeah this is another issue similar to https://github.com/Microsoft/vscode/issues/42625 where all I have is a remove and add API, where I should change to have an API that allows for both things at once.

**Comment by joaomoreno** [comment]
I now see `added 0 removed 0` for both examples. 👍
