### ISSUE TITLE
--upload-logs not functional on Windows

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42635]
### Issue Type
Bug

### Description

Testing #42352

![image](https://user-images.githubusercontent.com/9205389/35628484-58f38196-069c-11e8-8e2b-d2a3a606d09f.png)

Could be https://github.com/nodejs/node/issues/11656 .

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (648c46deeeda61fad44ce188684dcb61838b724a, 2018-01-31T10:13:25.946Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|5.98GB (3.13GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces only with extensions

**Comment by mjbvz** [comment]
https://github.com/electron/electron/issues/4218

**Comment by joaomoreno** [comment]
Yeah, there's no stdin in the main process. That's why we have the CLI process.

**Comment by mjbvz** [comment]
@joaomoreno Ok. So no stdin at all, even if you manually try to configure it?

I investigated moving the upload logs confirmation prompt to the CLI process but it's not easy since we need to print the path to the logs as part of this prompt. Any alternatives?

**Comment by joaomoreno** [comment]
None at all. 😢 

Shouldn't you be able to print the path to the logs easily from the CLI? The same world lives there: environment service, etc.

**Comment by mjbvz** [comment]
Ok, I've reworked the flow to no longer use stdin because it was getting complicated. Instead we ask the user the pass in a `--upload-logs=iConfirmLogsUpload` command line argument once they have reviewed the logs

**Comment by chrmarti** [comment]
Not sure if this is from this change, but it still doesn't work:

PS C:\devel\angular-test> code-insiders.cmd --upload-logs

You are about to upload your session logs to a secure Microsoft endpoint that only Microsoft's members of the VS Code team can access.

Session logs may contain personal information such as full paths or file contents. Please review and redact your session log files here: 'C:\Users\chrmarti.REDMOND\AppData\Roaming\Code - Insiders\logs\20180201T065704'

By continuing you confirm that you have reviewed and redacted your session log files and that you agree to Microsoft using them to debug VS Code.

Please run code with '--upload-logs=iConfirmLogsUpload' to proceed with upload
PS C:\devel\angular-test> code-insiders.cmd --upload-logs=iConfirmLogsUpload

Uploading...
Error posting logs: Error: ENOENT: no such file or directory, open 'C:\Users\CHRMAR~1.RED\AppData\Local\Temp\vscode-log-uploadA7YtlR\logs.zip'
[main 10:48:21 AM] Error: ENOENT: no such file or directory, open 'C:\Users\CHRMAR~1.RED\AppData\Local\Temp\vscode-log-uploadA7YtlR\logs.zip'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:208:31
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:440:735
    at Object.next (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:440:840)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:84:882
    at new n.Class.derive._oncancel (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:81:234)
    at r (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:84:659)
PS C:\devel\angular-test>

**Comment by mjbvz** [comment]
Weird. I haven't see this on master. Let me try the latest insiders build

**Comment by mjbvz** [comment]
Doh! I forgot to push a local fix yesterday which probably explains why this was totally all "works on my machine". Should be fixed by 5a8934a1d5d0e7a663ef6da38ca14605060f1e2d

I'll cherry pick this to 1.20 too
