### ISSUE TITLE
File dialog: Cannot navigate to \Windows\System32\drivers\etc, even as administrator

### ISSUE THREAD

**Issue by johnrom** [Microsoft/vscode#4263]
- VSCode Version: 0.10.11
- OS Version: Windows 10, 10586.164

Steps to Reproduce:
1. Open VSCode
2. Open File
3. Navigate to \Windows\System32\drivers

The etc directory is not visible. I have enabled hidden files and folders and run VSCode as administrator.

It is possible to enter \Windows\System32\drivers\etc\hosts into the Open File dialog in order to edit the hosts file.

**Comment by bpasero** [comment]
So you say this folder does not show up in our native file picker?

**Comment by DickvdBrink** [comment]
Notepad++ does the same on my system. It isn't visible but you can navigate to it from the adressbar in the open dialog.

**Comment by bpasero** [comment]
Interestingly I can see the etc folder with notepad but not with VS Code. Since we do not do anything special I suspect an upstream issue.

**Comment by gerane** [comment]
Atom has this issue as well. I always felt it has something to do with the auto update check upon launch. It always seemed to me that VS Code and Atom are not actually getting elevated to administrator properly. It always appeared to me with Atom, that the updater was being elevated to Administrator, but then it was not properly opening the actual editor as Administrator after then updater was finished. I'm not quite sure how VS Code is handling this, but thought I would add that this is also an issue with Atom. Even when elevated you cannot edit the hosts file for example in either editor.

**Comment by bpasero** [comment]
If so, this is an issue with Electron that should be reported against their repo.

**Comment by gerane** [comment]
The task manager reports code.exe as running elevated, but I still cannot edit anything that requires elevation. After testing Atom.exe just now, and bypassing its auto update shortcut, it has the same issue. Task Manager reports it as running elevated, but unable to edit anything that requires elevation. I will go look at the Electron issues.

**Comment by gerane** [comment]
I will also note, that there is another issue here that says I should be able to close all open instances of VS Code and then RunAs and get elevation, but this does not work on my machines.

**Comment by gerane** [comment]
Very odd, I decided to do a complete uninstall and reinstall, and I can now get it to run elevated properly if no other instances are running. The etc directory is still not visible, but I can actually open the files and edit them without getting a permissions error.

**Comment by gerane** [comment]
This is being cause by Code not handling FileSystem redirection when running as 32bit process on a 64bit OS. Code is being redirected from C:\Windows\System32\drivers to C:\Windows\sysWOW64\drivers where is no \etc folder.

This is very problematic. If you create a new file, and save it to C:\Windows\System32\drivers, it saves under C:\Windows\sysWOW64\drivers.

**Comment by mattpwhite** [comment]
This is standard behavior for a 32-bit process on 64-bit Windows.  There's no particularly sane/safe way to "handle" this in a 32-bit process.  You can [disable](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365743(v=vs.85).aspx) redirection temporarily, but things will go real bad for you if you end up trying to load a dll while it's off.  Popping a file picker has a pretty good chance of loading a dll (shell extensions would be one example).

A 64-bit version of Code would be nice, but until then, just use the [sysnative ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384187(v=vs.85).aspx) alias.

**Comment by bpasero** [comment]
Closing, as there does not seem to be anything we can do.
