### ISSUE TITLE
Search details

### ISSUE THREAD

**Issue by salc** [Microsoft/vscode#42636]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
goto-documentation|cxf|0.0.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
mark-as-excluded|jcm|0.2.5
gitignore|mic|1.0.1
vscode-hexdump|sle|1.6.0
html-css-class-completion|Zig|1.16.1
---

Search details always opened by default.

**Comment by roblourens** [comment]
Please provide more information

**Comment by salc** [comment]
project search (shift+ctrl+F)
search details already expanded (seems by default). They should expand only by clicking the horiz-more icon (...)
I need to close it on every search to get more search results on the screen.

**Comment by roblourens** [comment]
It should be expanded by default if it was expanded manually before, or if there was any text in the include/exclude boxes. Is that the case?

**Comment by salc** [comment]
nop, i close it and fields are empty. when i reopen it, i see it expanded again.
i have exclusions in settings. Is that the same thing? Could it be messed up by plugins?

**Comment by roblourens** [comment]
Hm, can you give me the exact steps to repro this? Like when you say "close/reopen" are you talking about the viewlet or the whole window?

**Comment by salc** [comment]
Sorry, you are right, it wasn't very clear :-)
for open or reopen, i mean the search panel (open/reopen = shift+ctrl+F) 
for close i was talking about the search detail fields clicking on horiz-more icon (...) and then returning to explorer using shift+ctrl+E

**Comment by salc** [comment]
ok, I deleted the .vscode dir and uninstalled all plugins. Restarted vscode and now it works like it should. So i think it has something to do with plugins messing around.
