### ISSUE TITLE
wordPattern in language-configuration.json not working on extension host process

### ISSUE THREAD

**Issue by pltrant** [microsoft/vscode#42649]
- VSCode Version: 1.19.3
- OS Version: Windows 10

Steps to Reproduce:

1. Add a wordPattern to the language-configuration.json file:
```
"wordPattern": "[\\S]+"
````

2. Perform an action that is reliant upon a word match, such as a DocumentHighlightProvider that triggers when a word is selected.  Using test code such as:
```
if (true) then
  print 'test'
.
```

Clicking on `if` will correctly trigger, but clicking on `.` will not.  A wordPattern of `[\S]+` should match against both.

If you contribute the setting on activate from an extension, it does work correctly:

```javascript
vscode.languages.setLanguageConfiguration('langID', {wordPattern: /[\S]+/});
```

**Comment by alexandrudima** [comment]
I cannot reproduce:

* `package.json`:
```js
{
    "publisher": "alex",
    "name": "42649",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "contributes": {
        "languages": [
            {
                "id": "myLang",
                "extensions": [
                    ".mylang"
                ]
            }
        ]
    },
    "main": "index.js"
}
```

* `index.js`:

```js
const vscode = require('vscode');

exports.activate = function (context) {
    vscode.languages.setLanguageConfiguration('myLang', {wordPattern: /[\S]+/});
    vscode.languages.registerDocumentHighlightProvider('myLang', {
        provideDocumentHighlights: (document, position) => {
            console.log(`INVOKED WITH ${JSON.stringify(position)}`);
        }
    })
}
```

* testfile `42649.mylang`:
```
if (true) then
  print 'test'
.
```

When I click on `.`, I get:
![image](https://user-images.githubusercontent.com/5047891/38987827-6c978aea-43d1-11e8-82f5-67d2d82f0f89.png)

So the highlight provider is invoked for line number 3 aka. position `(2,0)`.

**Comment by pltrant** [comment]
@alexandrudima, if you contribute the wordPattern via `vscode.languages.setLanguageConfiguration` it does work correctly.  However, it does not work if you contribute the wordPattern via the language-configuration.json file.

**Comment by alexandrudima** [comment]
@pltrant I unfortunately still cannot reproduce. Here are the complete files:

* `package.json`:
```js
{
    "publisher": "alex",
    "name": "42649",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "contributes": {
        "languages": [
            {
                "id": "myLang",
                "extensions": [
                    ".mylang"
                ],
                "configuration": "./config.json"
            }
        ]
    },
    "main": "index.js"
}
```

* `config.json`:
```js
{
    "wordPattern": "[\\S]+"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function (context) {
    vscode.languages.registerDocumentHighlightProvider('myLang', {
        provideDocumentHighlights: (document, position) => {
            console.log(`INVOKED WITH ${JSON.stringify(position)}`);
        }
    })
}
```

* `42649.mylang`:
```
if (true) then
  print 'test'
.
```

I see the provider invoked for the line number 3.

**Comment by pltrant** [comment]
In testing it again, I think the issue is with `getWordRangeAtPosition` in relation to how the `wordPattern` is contributed.  Specifically, the below code is executed by my documentHightlightProvider class:

```javascript
let highlights = [];
let textRange = document.getWordRangeAtPosition(position);
let lineNum = textRange.start.line;
...
```

If I contribute the `wordPattern` via `vscode.languages.setLanguageConfiguration`, it works fine.  If I contribute the `wordPattern` via the language-configuration.json file, `getWordRangeAtPosition` fails.  It's as if it's not reading the language specific wordPattern under that scenario.  If I explicitly provide the regex pattern for it to use (`document.getWordRangeAtPosition(position, /[\S]+/)`), it works fine, but there still shouldn't be a difference based upon how the `wordPattern` is contributed.

A separate bug that caused the confusion in this issue: I wasn't thinking it wasn't working at all, because `start.line` against an undefined object was causing the function (in my example code) to abort early and was not throwing an error at all, so none of the remaining code was being executed.

**Comment by alexandrudima** [comment]
Ok, when using `setLanguageConfiguration`, both the renderer process and the extension host process use the provided word definition.

When using a language configuration file, it is read only on the renderer process, and the extension host process ends up using the default word definition and therefore `document.getWordRangeAtPosition` uses the default word definition.
