### ISSUE TITLE
WorkspaceEdit: edit followed by deleteResource does not work

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#42640]
Testing #42334

Run the extension below.

- inserts text to the current document
- deletes the resource

The deleteResource seems to be ignore

```ts
'use strict';
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        let editor = vscode.window.activeTextEditor;
        if (editor) {
            let doc = editor.document;
            let docUri = doc.uri;

            let we = new vscode.WorkspaceEdit();
            we.insert(docUri, new vscode.Position(0, 0), 'Hello');
            we.deleteResource(docUri);
            vscode.workspace.applyEdit(we);
        }
    });

    context.subscriptions.push(disposable);
}
```

**Comment by jrieken** [comment]
@aeschli It should show like this: '(deleted from disk)'. 

<img width="267" alt="screen shot 2018-01-31 at 16 34 07" src="https://user-images.githubusercontent.com/1794099/35631600-9424298e-06a4-11e8-8284-1480097c0daf.png">

@bpasero Is there a way to prevent this? Don't we know that is was us, e.g. our file service, deleting the file so that we don't keep the editor around?

**Comment by bpasero** [comment]
@jrieken it will close by default, unless `workbench.editor.closeOnFileDelete` is configured, which you maybe did?

**Comment by jrieken** [comment]
> which you maybe did?

Nope... It also doesn't explain @aeschli's observation which is having both editors visible...

**Comment by bpasero** [comment]
@jrieken ah I see, the file is dirty and gets deleted from disk. we never ever close an editor that is dirty, no matter what happens.

**Comment by jrieken** [comment]
So, should save it then before deleting?

**Comment by jrieken** [comment]
> we never ever close an editor that is dirty, no matter what happens.

Wait. I have an editor with unsaved changes and then I delete the file form the explorer and the editor doesn't stick around. @bpasero How is that controlled? I always thought that's why we have file events and file service events?

**Comment by bpasero** [comment]
@jrieken yeah, the explorer [reverts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L673) the file before then deleting it.

**Comment by jrieken** [comment]
Hm... Uses a service isn't available in the common-layer (in contrast to the file service)... Would a simple save work?

**Comment by jrieken** [comment]
>  Would a simple save work?

I believe no

**Comment by bpasero** [comment]
@jrieken you mean `ITextFileService`? that one should be accessible from `common`, at least the interface lives in `vs/workbench/services/textfile/common/textfiles.ts`

**Comment by jrieken** [comment]
Sorry, imprecise wording. By 'common-layer' I have meant platform or accessible from the editor

**Comment by bpasero** [comment]
@jrieken it does not seem like ITextFileService could not live in common, there are not a lot of workbench dependencies (just a few interfaces that could also be moved). We would have to provide some kind of bogus default implementation for the standalone editor though.

**Comment by jrieken** [comment]
> We would have to provide some kind of bogus default implementation for the standalone editor though.

Yeah, I'd opt for the other direction and that we move the workspace edit up, so rename and code actions would be gone from the standalone editor

**Comment by jrieken** [comment]
@bpasero I have moved the rename/bulk-edit logic into a separate `IBulkEditorService`. The *real* implementation lives in the workbench layer and can use whatever it takes to implement rename/delete/create. Today it uses the `IFileService` [for that](https://github.com/Microsoft/vscode/blob/16909577223cd1b2981b63e071d6ecfe5422e4f4/src/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.ts#L338) which seems to be insufficient.  I'll leave it up to you to correct.

**Comment by bpasero** [comment]
@jrieken I adopted new methods `ITextFileService#delete` and `ITextFileService#move` in the `bulkEditService`. These new methods will:
* revert a dirty file if it gets deleted
* preserve the contents of a dirty file if it gets moved

There are 2 outstanding questions:
* currently there is no prompt happening when the file is dirty and about to be deleted, would you expect one?
* currently I do not expect the URIs in these methods to be folders, just files because the text file service is typically just talking about files. would the bulk service ever pass in folder resources?

**Comment by jrieken** [comment]
Yes, folder support is needed

**Comment by bpasero** [comment]
@jrieken added folder support. The explorer is now using the `ITextFileService#move()` method for both renaming a file/folder or when using drag and drop. This opens the door for participation in these operations from extensions. I checked that nobody else is using this functionality so far besides the explorer.
