### ISSUE TITLE
Code copied from vscode carry html code together

### ISSUE THREAD

**Issue by oxydron** [Microsoft/vscode#42648]
When you copy any code from vscode and paste, for instance, on gmail, it will carry colors, background, etc within gmail text area. This is a problem on another scenarios too.

- VSCode Version: 1.19.2
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. Copy any code from Visual Code
2. Paste on gmail

Does this issue occur when all extensions are disabled?: Yes

Screenshot:
![image](https://user-images.githubusercontent.com/331134/35633908-921a1ddc-0691-11e8-9b75-30e0bc90d8aa.png)

**Comment by rebornix** [comment]
Close in favor of https://github.com/Microsoft/vscode/issues/21071#issuecomment-418887276. Thanks for your feedback.
