### ISSUE TITLE
Seperate configuration of tab size and indent size

### ISSUE THREAD

**Issue by lankyboycie** [microsoft/vscode#42643]
- VSCode Version:1.19.2
- OS Version: Centos 7

I'd like to be able to configure tab size and indentation size separately. When reading a file I'd like a tab character to be displayed as 8 spaces, when pressing the tab key on the keyboard I'd like it to insert 4 spaces. At present in VS code tab size and indentation size is one setting.

This sort of thing is available in eclipse, for instance, so it must be something that others have previously deemed to be useful.

**Comment by usernamehw** [comment]
IDK, `keybindings.json`
```json
{
    "key": "tab",
    "command": "type",
    "args": {
        "text": "    ",
    },
    "when": "editorTextFocus"
}
```

**Comment by alexandrudima** [comment]
Let's track in #10339
