### ISSUE TITLE
Git UI not updating with file changes

### ISSUE THREAD

**Issue by jboone0052** [Microsoft/vscode#42644]
I am having an issue with vs code where I open a folder that has 2 projects, a front end and a back end. Each project has a git repository associated with it. When I make a change to a file in either of the projects then go to the source control window it doesn't show any modified files. If I run a git status in the terminal it shows the modified files. If I close out of code and open it back up, it will show the modified files in the source control window but not any file that is newly modified after opening code back up. This doesn't happen with other projects I open with multiple sub repositories like this. 

- VSCode Version: 1.19.3
- OS Version: 10

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
It only happens for this specific folder with 2 folders, but doesn't happen with other projects with multiple sub repositories?

Can you think of anything special about that specific folder? Is it in a network share? Does it have special characters?
