### ISSUE TITLE
How to rename a workspace folder by using a "splice" style API?

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42642]
testing #42195:

The "splice" API style results in this code for a simple rename:
```js
function renameWorkspaceFolder(folder: vscode.WorkspaceFolder) {
    const allfolders = vscode.workspace.workspaceFolders;
    const ix = allfolders.indexOf(folder);
    vscode.workspace.updateWorkspaceFolders(ix, 1, { uri: folder.uri, name: 'new name' });
}
```

Or is there a simpler way to rename a folder programmatically?

**Comment by bpasero** [comment]
@weinand no, you are doing it right. a rename of a folder is a remove and add at the same place.
