### ISSUE TITLE
No quick fix for removing all unused declarations

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42659]
Testing #42358

In the below case `boo`, `hoo` and `foo` are unused variables.

<img width="437" alt="screen shot 2018-01-31 at 10 56 16 am" src="https://user-images.githubusercontent.com/16890566/35641598-7ea53dde-0675-11e8-8a10-62622db3c6b3.png">

I'd expect the quick fix all option to remove all unused declarations in the file instead of removing all unused declarations of `foo` which is not useful

**Comment by mjbvz** [comment]
I believe that's what the fix all action already does. It just doesn't have a good name yet, see: https://github.com/Microsoft/TypeScript/issues/21380

Can you verify?

**Comment by ramya-rao-a** [comment]
I didn't click on it :)

Yes, thats right. It does remove all unused declarations
