### ISSUE TITLE
Example CodeActionProvider has incorrect return type

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#42653]
Testing #42333

In https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_20.md, the example code for provideCodeActions returns a single code action instead of an array.

**Comment by mjbvz** [comment]
Fixed by https://github.com/Microsoft/vscode-docs/commit/1df91e3b0186db4fe4b8e38a8d3ee189be5e0f54
