### ISSUE TITLE
Importing an npm module

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#4265]
- VSCode Version: latest
- OS Version: OSX

I am trying to import an npm moduleinto vscode to use.  I am following this tutorial, https://github.com/DefinitelyTyped/demo-typescript-node-minimal.  I got it to run locally outside of vscode successfully.

Steps to Reproduce:

1. `./scripts/npm.sh install xregexp --save`
2. open `build/gulpfile.vscode.js` change var baseModules = [...] to the following.
    ```
    var baseModules = [
        'applicationinsights', 'assert', 'child_process', 'chokidar', 'crypto', 'emmet',
        'events', 'fs', 'getmac', 'glob', 'graceful-fs', 'http', 'http-proxy-agent',
        'https', 'https-proxy-agent', 'iconv-lite', 'electron', 'net',
        'os', 'path', 'readline', 'sax', 'semver', 'stream', 'string_decoder', 'url',
        'vscode-textmate', 'winreg', 'yauzl', 'native-keymap', 'weak', 'zlib', 'xregexp'
    ];
    ```
3. Create a typings file, `src/typings/xregexp.d.ts` with the following
    ```
    // Type definitions for XRegExp 2.0.0
    // Project: http://xregexp.com
    // Definitions by: Bart van der Schoor <https://github.com/Bartvds>
    // Definitions: https://github.com/borisyankov/DefinitelyTyped

    declare module 'xregexp' {
        // scopes: 'default', 'class', or 'all'
        /*
         Native flags:
         g - global
         i - ignore case
         m - multiline anchors
         y - sticky (Firefox 3+)
         Additional XRegExp flags:
         n - explicit capture
         s - dot matches all (aka singleline)
         x - free-spacing and line comments (aka extended)
         */
        export interface TokenOpts {
            scope?: string;
            trigger?: () => boolean;
            customFlags?: string;
        }

        export function XRegExp(pattern: string, flags?: string): RegExp;
        export function XRegExp(pattern: RegExp): RegExp;

        export module XRegExp {
            function addToken(regex: RegExp, handler: (matchArr: RegExpExecArray, scope: string) => string, options?: TokenOpts): void;

            function build(pattern: string, subs: string[], flags?: string): RegExp;
            function cache(pattern: string, flags?: string): RegExp;
            function escape(str: string): string;
            function exec(str: string, regex: RegExp, pos?: number, sticky?: boolean): RegExpExecArray;
            function forEach(str: string, regex: RegExp, callback: (matchArr: RegExpExecArray, index: number, input: string, regexp: RegExp) => void, context?: Object): any;
            function globalize(regex: RegExp): RegExp;

            function install(options: string): void;
            function install(options: Object): void;

            function isInstalled(feature: string): boolean;
            function isRegExp(value: any): boolean;
            function matchChain(str: string, chain: RegExp[]): string[];
            function matchRecursive(str: string, left: string, right: string, flags?: string, options?: Object): string[];

            function replace(str: string, search: string, replacement: string, scope?: string): string;
            function replace(str: string, search: string, replacement: Function, scope?: string): string;
            function replace(str: string, search: RegExp, replacement: string, scope?: string): string;
            function replace(str: string, search: RegExp, replacement: Function, scope?: string): string;

            function split(str: string, separator: string, limit?: number): string[];
            function split(str: string, separator: RegExp, limit?: number): string[];

            function test(str: string, regex: RegExp, pos?: number, sticky?: boolean): boolean;

            function uninstall(options: Object): void;
            function uninstall(options: string): void;

            function union(patterns: string[], flags?: string): RegExp;
            var version: string;
        }
    }
    ```
4. Import xregexp into git, open `src/vs/workbench/parts/git/browser/views/changes/changesView.ts`
    ```
    import xregexp = require('xregexp');
    ```
5. Call xregexp in the render function in `src/vs/workbench/parts/git/browser/views/changes/changesView.ts`
    ```
    private render(): void {
        if (this.$el) {
            return;
        }

        this.$el = $('.changes-view');
        this.$commitView = $('.commit-view').appendTo(this.$el);

        var exp = xregexp.XRegExp(/abc/);
        var match = exp.exec('abcdefgh');
        console.log(match);
    ....
    ```

5. `gulp watch`
6. `./scripts/code.sh`

The following error is produced:
```
xregexp.XRegExp is not a function: TypeError: xregexp.XRegExp is not a function
    at ChangesView.render
```

**Comment by bpasero** [comment]
@jsloyer adding a new npm module to vs code you will need to add it to our npm-shrinkwrap.json file too.

**Comment by jsloyer** [comment]
@bpasero I added xregexp to the npm-shrinkwrap file and still have the issue.  Can we please reopen this?

**Comment by bpasero** [comment]
@alexandrudima do we need to tell the loader this is a node.js module?

**Comment by alexandrudima** [comment]
@jsloyer You are doing everything OK from a vscode point of view. However, I have tried your steps and ran into the same problem.

The problem is that the .d.ts file does not match the xregexp node module. When I installed xregexp, I got version 3.1.0. The type definitions you add in xregexp.d.ts are for the 2.0.0. I think the difference from 2.0 to 3.0 for xregexp is in how they export their functionality, which is a breaking change, thus the major version increment.

I was able to get your code to run by doing the following:

* Use a .d.ts for version 3 for xregexp (replace xregexp.d.ts content with the one at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ceeac0ccf8ced1960b6b12c51557a621e45a7c40/xregexp/xregexp.d.ts)

* Change step 5 to consume xregexp as it wants to be consumed in version 3.0:
```typescript
		var exp = xregexp(/abc/);
		var match = exp.exec('abcdefgh');
		console.log(match);
```

![image](https://cloud.githubusercontent.com/assets/5047891/13809243/0fced30c-eb6a-11e5-9313-27d56340ea4f.png)

**Comment by f111fei** [comment]
@bpasero 

I use `npm shrinkwrap` to update `npm-shrinkwrap.json`. But the file is different from [you](https://github.com/Microsoft/vscode/blob/master/npm-shrinkwrap.json). 
Its about `120KB`  and  `3500 lines`.

os version : `windows 7` 
npm version : `3.8.3`

How do you update npm-shrinkwrap.json now?

**Comment by bpasero** [comment]
@joaomoreno did it the last time and could comment how he produced that file.

**Comment by joaomoreno** [comment]
Tricky. We must run `npm shrinkwrap` on all 3 platforms and sort of do a *merge* between them. This is due to some `optionalDependencies` which will only install some dependencies on some platforms.

**Comment by f111fei** [comment]
@joaomoreno  Its a manual merge? And I use `npm shrinkwrap` on windows 7,  `npm-shrinkwrap.json` is about `3500 lines` **very** different from yours `400 lines`.  Here is my `npm-shrinkwrap.json`

[npm-shrinkwrap.txt](https://github.com/Microsoft/vscode/files/242526/npm-shrinkwrap.txt)

What should I do?

**Comment by joaomoreno** [comment]
Oh and we don't shrinkwrap dev dependencies! So, you should clean everything up, and run `npm install --production` to not install dev dependencies... sorry for that!

**Comment by f111fei** [comment]
@joaomoreno Soga. Thanks!!!
