### ISSUE TITLE
Possible to disable?: 'Save as Workspace?' prompt, upon closing a window 

### ISSUE THREAD

**Issue by DavidLudwig** [Microsoft/vscode#42657]
Using the latest, released version of VSCode, at the time of this writing (2018-Jan-31; version 1.19.3), on MacOS High Sierra (and last tested on 10.13.2), and with extensions disabled, I see the following behavior, which, in some cases, can be unnecessarily time-consuming:

Attempting to close a window that has files open from multiple, disparate directories, the following prompt always appears:

"Do you want to save your workspace configuration as a file?"

A set of buttons (with "Don't Save", "Cancel", "Save") is also presented, offering options.  One of the dialogs buttons must be selected, in order to close the window.

Screenshot: <br>
<img width="504" alt="vscode" src="https://user-images.githubusercontent.com/475856/35640030-02061464-068a-11e8-823a-bb4adfbdc7b7.png">

This prompt does not come up when trying to close a window that is associated with a single file, or a single directory.

Here is an example of how to launch VSCode from an OS' command shell, to reproduce this prompt:

`code -n --disable-extensions DirectoryA DirectoryB`

Is there a way to disable this prompt via setting(s) in VSCode?  If not, much such a feature be feasible?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30972 and https://github.com/Microsoft/vscode/issues/30974

**Comment by DavidLudwig** [comment]
I am interested in discussing the possibility of adding a user-configurable setting that would alter this behavior.  If it were set, closing a new, unnamed and unsaved workspace could, effectively, choose the "Don't Save" option.

I am unsure which of the aforementioned issues, #30972 or #30974, would be appropriate to make this suggestion, if any.  #30974 looks a bit closer, but I am uncertain.

If you have a moment: do you have any suggestions on where, exactly, to continue discussion of this?  I am guessing that limiting discussion to one, and only one of those cases (or some other one!), would be best.

**Comment by DavidLudwig** [comment]
Additionally,

I would be willing to try providing a candidate pull request for this, then iterate on such according to feedback, if it would help.
