### ISSUE TITLE
WorkspaceEdit api - after saving a deleted file, it still shows up as deleted.

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#42667]
Testing https://github.com/Microsoft/vscode/issues/42334

Deleting a file using WorkspaceEdit.deleteResource correctly shows "(deleted from disk)" in the tab title. But if I then edit that tab and save it, it still shows up as deleted, though its a saved file.

Also, if I modify a file with the api after deleting it, the changes still show up on the current tab.
```
let we = new vscode.WorkspaceEdit();
we.deleteResource(documURI);
we.insert(documURI, position, "InsertText");
vscode.workspace.applyEdit(we);
```
I'm not quite sure what should happen in this case, but I expected the edits to happen in the same order (first delete, then fail when trying to insert).

**Comment by jrieken** [comment]
fixed by @bpasero changes
