### ISSUE TITLE
onDidChangeTextDocument and onDidCloseTextDocument fired when adding/removing workspaces

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42666]
Testing #42195

I noticed this because of a bunch of errors from Vim when I'm adding/removing workspaces.

Have this as an extension

```ts
export const activate = (context: vscode.ExtensionContext) => {
  vscode.workspace.onDidChangeTextDocument((e) => {
    console.log(e.document.fileName)
  })
  vscode.workspace.onDidCloseTextDocument((e) => {
    console.log(e.fileName)
  })
}
```

And try adding/removing folders using either the UI or the API.

I'm getting `onDidChangeTextDocument` and `onDidCloseTextDocument` for `/Users/octref/Desktop/test.code-workspace`, which sort of make sense, but I don't think they should apply to the workspace file itself, especially when that file is outside of any active workspaces.

However when adding workspaces, I also get `onDidChangeTextDocument` where `e.document.fileName` points to `/launch` and `e.contentChanges[0].text` looks like this, which is quite unexpected...

```
"{"id":"vscode://schemas/launch","type":"object","title":"Launch","required":[],"default":{"version":"0.2.0","configurations":[],"compounds":[]},"properties":{"version":{"type":"string","description":"Version of this file format.","default":"0.2.0"},"configurations":{"type":"array","description":"List of configurations. Add new configurations or edit existing ones by using IntelliSense."
```

**Comment by bpasero** [comment]
I would say that this is expected since we use the model API to make changes to certain files and they end up being synchronized to the extension host. @jrieken to confirm.

**Comment by jrieken** [comment]
Yeah, as designed
