### ISSUE TITLE
Suggest widget in tagged template shows collapsed doc

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42662]
Testing https://github.com/Microsoft/vscode/issues/42361

Have file with these contents:

```ts
const z = html`<html><div sty></div> </html>`
```

Trigger suggestions on `sty`. Get attribute intellisense with weird collapsed quick info.

![image](https://user-images.githubusercontent.com/323878/35642081-d0138de6-0676-11e8-8501-f70a25a8655e.png)

**Comment by joaomoreno** [comment]
How to verify?

![image](https://user-images.githubusercontent.com/22350/35727955-402be6ca-080a-11e8-832c-450b5caecb00.png)
