### ISSUE TITLE
"runtimeVersion": "default" special handling?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42664]
Testing https://github.com/Microsoft/vscode/issues/42316

- Set `"runtimeVersion": "default"` which is it's default value
- `Node.js version default not available via nvm.`

Is this supposed to work? I have a default set up in nvm via `nvm alias default`. I would guess we'd just run `node` normally for this.

**Comment by weinand** [comment]
No, this is not supposed to work.
The problem is that I would have to duplicate lots of the internal logic of nvm and nvm-windows to support symbolic values.
Dealing with version numbers is easy because both tools organise the node versions in folders that use the version number as its name.

**Comment by roblourens** [comment]
But `node` runs whatever is configured as the default by nvm, I assume windows is the same, so you don't have to duplicate any logic. And it seems like the default value of `runtimeVersion` shouldn't be an invalid value.

**Comment by weinand** [comment]
Oh, I see: 'default' is illegal default value.
I will just ignore value 'default'.
