### ISSUE TITLE
Support short version numbers for runtimeVersion in node-debug

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42669]
Testing https://github.com/Microsoft/vscode/issues/42316

Just a suggestion that would make this even more useful. 

nvm takes incomplete version strings, and will find the latest matching version. For example I can use `nvm install 8.9` and it will find 8.9.4 as the latest 8.9. I use this often when I can't remember what versions are available. Or I can just use `nvm install 9` to check whether a new 9.x has been released yet.

It would be useful if I could set `"runtimeVersion": "8"` and have node-debug look up the latest installed 8.x.x version in nvm.

**Comment by Farenheith** [comment]
Hello!
I'd like to see this enhancement in the future.
Consider that in a big team, maybe not everyone have exactly the same **node 12** and **node 14** version installed and, in most cases, it doesn't need to have, so if we could just add **"runtimeVersion": "12** and **"runtimeVersion: "14"** it'd be very convenient!
