### ISSUE TITLE
Source control integration ignores files staged with `git add -N`

### ISSUE THREAD

**Issue by nilsweb** [Microsoft/vscode#42665]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.0
quokka-vscode|Wal|1.0.94
gitlens|eam|7.5.9
debugger-for-chrome|msj|4.1.0
color-highlight|nau|2.3.0
sass-indented|rob|1.4.6
vim|vsc|0.10.13
---

Steps to Reproduce:

1. Stage a new file unknown to git using `git add -N <filename>`
2. Take a look at the "Source Control" and/or "Explorer" panel

Reproduces without extensions: Yes

---

Hey everyone,
I just noticed that if I stage a previously unknown file using `git add -N <filename>` to make it known to git so I can partially stage the content, VSCode assumes it's "unchanged" (disappears from the file list in the "Source Control" panel and doesn't get coloured in the "Explorer" panel). It doesn't really affect the overall experience using VSCode but I just wanted to let you know.
Thanks!

**Comment by shobhitchittora** [comment]
@nilsweb Thanks for pointing this out! There's definitely a disparity between the actual behavior and the vscode behavior. The same is documented below - 

| Command        | Code        | Term           | 
| ------------------ |:------------:|:-------------:| 
| `touch test.js` | <img width="437" alt="1-code" src="https://user-images.githubusercontent.com/4711855/35898843-1523fa06-0bef-11e8-9404-7b66ecb2383d.png">    | <img width="467" alt="1-zsh" src="https://user-images.githubusercontent.com/4711855/35898844-155dca06-0bef-11e8-8822-c4ee3152cedb.png"> | 
| `git add test.js` |  <img width="430" alt="2-code" src="https://user-images.githubusercontent.com/4711855/35899110-9c84b0f2-0bf0-11e8-96ad-85a7e2aa3df4.png"> | <img width="355" alt="2-zsh" src="https://user-images.githubusercontent.com/4711855/35899109-9c4abffa-0bf0-11e8-8f2f-f71ddb4bdbf9.png">   
| `git add -N test.js` | <img width="433" alt="3-code" src="https://user-images.githubusercontent.com/4711855/35899115-a1d7e8a8-0bf0-11e8-92e1-7fd858893047.png">    |  <img width="537" alt="3-zsh" src="https://user-images.githubusercontent.com/4711855/35899114-a19bf596-0bf0-11e8-944c-78cc68c29983.png"> | 

@joaomoreno need your suggestion on this. Any way we can add another decorator for partially added files ( or files with --intent-to-add )?

**Comment by joaomoreno** [comment]
Sure, we can, if it is useful to have. What usefulness does `-N` bring?

**Comment by nilsweb** [comment]
It just adds an empty file object (don't really know how it's actually called) to Git without staging the content. That way, you can partially stage a file using `git add -p filename` that was previously unknown to Git. Maybe there's some other use case but I primarily use it in a situation like that.

**Comment by shobhitchittora** [comment]
@joaomoreno I agree with you. I don't immediately see a benefit of adding extra scm decorator for this case. It can be taken up if more people ask for this. 

Cheers 👍🏻.

**Comment by okready** [comment]
I just ran up against this issue as well. I'll often use `git add -N` if I'm switching between work environments, such as my desktop PC and laptop, and I want to create a simple patch with my local changes to copy to the other system without having to make a commit (`git diff` will include the content of files added with `-N` in the patch alongside other unstaged modifications). There may be a better workflow I'm not familiar with, but this tends to work okay. At the very least, I would argue that having the file disappear entirely in the source control view seems like a bug since there is something there that's relevant to the working tree's status.

**Comment by sshock** [comment]
I ran into this as well.  I'm in the habit of running `git add -N .` so that new files will show up in `git diff` without having to stage them first.

I just started using vscode and found it very surprising and confusing when these files did not show up in the "Source Control" panel!
