### ISSUE TITLE
Suggestions for quickstart.md in language pack extension

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42675]
Testing #42366

Regarding the contents of `vsc-extension-quickstart.md` file

![image](https://user-images.githubusercontent.com/16890566/35648688-69131502-068b-11e8-88f4-c947986fc295.png)

The `translations` folder doesnt get created until the npm script for `update-localization-extension` is run. I would suggest replacing the `To populate or update the ..` with `To create/update the ..`

![image](https://user-images.githubusercontent.com/16890566/35648739-916df1a2-068b-11e8-9eac-63b7d0520951.png)

- Both step 1 and 4 talk abt `cd` to VS Code folder. I would suggest to first cover everything about the API token and then move on to cloning the repo
- Missing instructions on the token needing to have access to 'vscode-editor', 'vscode-workbench' and 'vscode-extensions'

**Comment by aeschli** [comment]
To verify:
- `npm -g update generator-code` (should be 1.1.27 or greater)
- yo code
- pick 'New language pack'
- in the created extension verify that vsc-extension-quickstart.md is good
