### ISSUE TITLE
Debug dropdown changes values when launching compound configuration

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#42678]
Testing #42036
![debug dropdown changes](https://user-images.githubusercontent.com/3672607/35651035-13754630-0693-11e8-92eb-183e7ddba0d1.gif)

My compound configuration uses configurations from two of the folders in my workspace.
```
	{
		"name": "Compound",
		"configurations": ["Launch Extension", "Launch Program"]
	}
```

When launching it, the selected value in the dropdown changes to the last configuration in the list. I would expect it to remain on "Compound (workspace)".

**Comment by isidorn** [comment]
@RMacfarlane nice catch, I also noticed this. Will fix in debt week -> february
