### ISSUE TITLE
Validation for language id when creating language pack extension from yeoman

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42674]
Testing #42366

When running `yo code`, I chose `es-es` i.e Spanish. Below is the Readme from the resulting extension

```
The translated strings are maintained here:
* [vscode-editor project](https://www.transifex.com/microsoft-oss/vscode-editor/language/es-es/)
* [vscode-workbench project](https://www.transifex.com/microsoft-oss/vscode-workbench/language/es-es/)
* [vscode-extensions project](https://www.transifex.com/microsoft-oss/vscode-extensions/language/es-es/)
```

All links above ended up with 404
My mistake was to use `es-es` instead of `es`

Can we have some kind of validation when generating the extension?

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-generator-code#104
