### ISSUE TITLE
Code becomes unresponsive when using multi cursor on very long line

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#42677]
Testing https://github.com/Microsoft/vscode/issues/42357

VS Code version: Code - Insiders 1.20.0-insider (010de7da99e63841dfe5bc5a45ce1509f9fd1479, 2018-01-31T09:45:32.303Z)
OS version: Linux x64 4.10.0-40-generic

1. Create a 5 million long line
2. Create multiple cursors in this line (~20 near each other)
3. Try editing using the cursors

**Bug**
This made code unresponsive in my testing

**Comment by rebornix** [comment]
Considering it's not actionable due to current architecture, closing it for now.
