### ISSUE TITLE
cli: give better hint what to put for --locale

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4268]
Currently the help text reads "Use a specific locale, "pseudo" can be used to test localization."

I doubt that a user wants to know about "pseudo", instead I would give a concrete example how to put a language in there (e.g. what is the format).

@dbaeumer I suggest to do this for GA since people might want to tweak this.

**Comment by bpasero** [comment]
In: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/cli.ts#L39

**Comment by dbaeumer** [comment]
Agree.
