### ISSUE TITLE
Next occurence should not replace dedicated search input's content

### ISSUE THREAD

**Issue by SEAPUNK** [Microsoft/vscode#42686]
### Issue Type
Bug/Feature Request

### Description

- Open the dedicated search tab (Cmd-Shift-F)
- Search for some text
- Open a file with text in it
- Highlight a word and Add Next Occurence (Cmd-D)
- Click on dedicated search tab's input field
- Watch it get replaced with the highlighted word on focus

This is _incredibly_ annoying, especially when I'm doing regex searches for similar terms. If there's text in the search input, it should not get replaced with whatever I highlight and Cmd-D, or at least be recoverable with undo (Cmd-Z).

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (648c46deeeda61fad44ce188684dcb61838b724a, 2018-01-31T17:21:50.909Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4621416|
|Screen Reader|no|
|VM|25%|

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
You can disable this with `"editor.find.globalFindClipboard": false`, but the previous text being lost is a bug. I don't think I can change the undo stack but I can add it to the history.

**Comment by SEAPUNK** [comment]
`"editor.find.globalFindClipboard": false` is exactly what I needed, thank you!
