### ISSUE TITLE
Find widget causes hang when getting seeded with long selection

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#42680]
Testing https://github.com/Microsoft/vscode/issues/42357

VS Code version: Code - Insiders 1.20.0-insider (010de7da99e63841dfe5bc5a45ce1509f9fd1479, 2018-01-31T09:45:32.303Z)
OS version: Linux x64 4.10.0-40-generic

1. Create a large text file with a long line (~50,000)
2. Select the long line and then trigger the find widget

**Bug**
Sometimes this made code unresponsive. This seems to happen when the string contains some non-letter characters 

Other times, i get "Invalid Regular Expression" Regexp too big. I suggest we limit the size of the seed we try to use in these cases. I trigged this by accident

**Comment by rebornix** [comment]
There isn't anything we can do currently to improve this experience due to the architecture we have.
