### ISSUE TITLE
Small selection highlighting rendering glitch

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42681]
**Steps to Reproduce:**

1. In a file:

```
a
aa
```

2. Select all

**Bug**
Tiny edge rendering glitch between lines:

![screen shot 2018-01-31 at 2 44 13 pm](https://user-images.githubusercontent.com/12821956/35651658-5a92ee94-0695-11e8-9a5d-1bf96cb6c3be.png)

**Comment by joaomoreno** [comment]
Duplicate of #38591?
