### ISSUE TITLE
No installers available to install rope

### ISSUE THREAD

**Issue by FlavioCestari** [Microsoft/vscode#42682]
- VSCode Version: 1.19.3
- OS Version: Windows 7 Enterprise
- Python Extension Version: 0.9.1

Steps to Reproduce:

1.Select the text to be renamed.
2.Right click to launch the context menu.
3.Select the ‘Rename Symbol’ menu option.
4.Rename symbol and type ENTER.
5.Click in "Install rope" button. Displayed message: [INFO] "No installers available to install rope".

Does this issue occur when all extensions are disabled?: n/a

**Comment by alexandrudima** [comment]
@FlavioCestari I don't think we ship with a button labeled "Install rope". I believe that is something an extension shows. Which extensions do you have installed?

**Comment by FlavioCestari** [comment]
@alexandrudima
You are right. The VSCODE show the message "[Error] Refactoring library is not installed" and the buttons "Install rope" and "Close", but I guess it is caused by "vscode-python" extension, refactoring feature (rename symbol) specifically. Thanks.

**Comment by alexandrudima** [comment]
Moved to https://github.com/Microsoft/vscode-python/issues/678
