### ISSUE TITLE
^acceptSelectedSuggestion no longer works

### ISSUE THREAD

**Issue by jseanxu** [Microsoft/vscode#4269]
- VSCode Version: 0.10.11
- OS Version: Win10

Steps to Reproduce:

1. Open keybindings.json
2. Add this key binding:
```
{ "key": "space", "command": "^acceptSelectedSuggestion", "when": "editorTextFocus && suggestWidgetVisible" }
```
3. Open a code file (C#, JS, TS)
4. Type "publ" followed by the space key

Expected:
The text should be `public ` (with a space at the end)

Actual:
The text is `publ `, no autocompletion occurred.

Note:
"acceptSelectedSuggestion" without the caret still works

**Comment by jseanxu** [comment]
Looking thru the default bindings, I noticed this binding at the very bottom of the file:
```
{ "key": ".", "command": "^acceptSelectedSuggestion", "when": "editorTextFocus && suggestWidgetVisible && editorLangId == 'typescript' && suggestionSupportsAcceptOnKey" }
```

Pressing `.` does not autocomplete in TypeScript either.

**Comment by alexandrudima** [comment]
I can confirm it doesn't work on TypeScript due to the context key `suggestionSupportsAcceptOnKey` not being set.

**Comment by jrieken** [comment]
There is two problems:

1. this commit introduced a regression in that it turns around the boolean condition (missing `!`) https://github.com/Microsoft/vscode/commit/2461331b4fab7f1c00c213cd3980128541da1bf9
2. we ended up with having the command two times when working on the acceptOnEnter config setting

**Comment by jrieken** [comment]
@joaomoreno @alexandrudima Despite the fixes above this still happens. The reason seems to be that `suggestWidget#onListSelection` uses a timeout. That gives the triggerOnCharacter command a chance to run (and clear the previous suggest model) such that accept doesn't work

**Comment by jrieken** [comment]
the timeout and like breakage happened in https://github.com/Microsoft/vscode/commit/6b495479328cecb3c1d2873b20c58ffb9d49f619

**Comment by joaomoreno** [comment]
Oh, the missing `!`! Ugh, sorry about that.

The `setTimeout` was just a leftover. I made a change that enables me to simply remove it. :+1: 

@jrieken can you see whether the `acceptSelectedSuggestion` now works?

**Comment by jrieken** [comment]
works
