### ISSUE TITLE
Customize quote character for autocomplete string-indexed memebers

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42691]
From https://github.com/Microsoft/vscode/issues/36429

I just see it using double quotes, but this should be customizable for a codebase that wants single quotes.

![image](https://user-images.githubusercontent.com/323878/35655401-8ab0df08-06a6-11e8-975b-06d9e154b2c3.png)

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/21768 to track this upstream
