### ISSUE TITLE
Cannot uninstall extensions

### ISSUE THREAD

**Issue by kiewic** [Microsoft/vscode#42698]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: I have tried with all my installed extensions: Git Lens, C#, C/C++ Clang Command Adapter

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-eslint|dba|1.4.4
gitlens|eam|7.5.9
vscode-clang|mit|0.2.2
csharp|ms-|1.13.1
code-spell-checker|str|1.6.3

---

Steps to Reproduce:

1. Go to the *Extensions* tab
2. Select a extension
3. Click *Uninstall*, and nothing happens, the extension is not uninstalled, but there is no error. Restarting VSCode is not helping

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@kiewic Do you see a dialog asking for the confirmation when you click uninstall button?

**Comment by kiewic** [comment]
I don't see any dialog.

**Comment by sandy081** [comment]
Can you please try with latest insiders and see if you can reproduce it?

**Comment by davidmcl** [comment]
I have this problem as well...

VSCode 1.20.0
Linux Mint 18.3 

Also no dialog, straight to the error at the top, shown in the screenshot attached.
Same result on all extensions tried (3).

Thanks,
David


![screenshot at 2018-02-11 19-25-39](https://user-images.githubusercontent.com/2047925/36081243-9acde4da-0f61-11e8-8489-ef796118080d.png)

**Comment by sandy081** [comment]
@davidmcl Can you please open extensions folder and see if this extension exist and if so provide us the folder name and its `package.json` details?

**Comment by davidmcl** [comment]
1337 theme is one of the ones I can't remove, so using that as the example here.

Extension exists in: `/home/{username}/.vscode/extensions`

screenshot of folder and pdf of package.json attached


![screenshot at 2018-02-13 14-53-56](https://user-images.githubusercontent.com/2047925/36156246-5cb9bc1e-10ce-11e8-952c-92649fcac977.png)

[package.json.pdf](https://github.com/Microsoft/vscode/files/1720323/package.json.pdf)

**Comment by davidmcl** [comment]
I had a thought that these might be related to some format issue due to new versions of code coming out and these extensions were installed on "old" versions of vscode.

That thought may have some merit as I was able to install and uninstall new themes & extensions without a problem.

David

**Comment by sandy081** [comment]
@davidmcl This looks to me completely different issue than what it is reported. Can you please file a separate issue for yours, so that this original issue does not get side tracked?
