### ISSUE TITLE
A javascript error in the main process

### ISSUE THREAD

**Issue by devarajchidambaram** [Microsoft/vscode#42705]
I got these error after update the visual studio code in windows 10
![vs error](https://user-images.githubusercontent.com/4964048/35666903-cdc83182-0751-11e8-96dd-0c155e317dcc.png)

**Comment by mjbvz** [comment]
Your installation appears to be corrupt. Often this is due to a bad upgrade or an over-zeleous anti-virus program.

Please try reinstalling VS Code to fix this
