### ISSUE TITLE
task.json schema update on documentation sites

### ISSUE THREAD

**Issue by skillfully** [Microsoft/vscode#42706]
- VSCode Version: 1.19.3
- OS Version: Ubuntu LTS 16.04.3

Hi,
could you trigger an update of this [site](https://code.visualstudio.com/docs/editor/tasks-appendix#_schema-for-tasksjson)
I think this schema is not already up to date. For example ...
```
interface BaseTaskConfiguration {

    /**
     * The type of a custom task. Tasks of type "shell" are executed
     * inside a shell (e.g. bash, cmd, powershell, ...)
     */
    type: "shell" | "process";
```
There is no note about other possible types like grunt, gulp etc. that are shown at [task docs](https://code.visualstudio.com/docs/editor/tasks). This is very annoying because you always have to search for the right configuration

Thanks ...

**Comment by dbaeumer** [comment]
This is actually hard to document since the list is open ended and depends on installed extensions. But we should mention that their could be others.

**Comment by dbaeumer** [comment]
This has happened a while ago.
