### ISSUE TITLE
When working with PHP, problems arise. I declare a class in one file and try to call its methods in another file. I'm making a file connection, but I do not see these methods.

### ISSUE THREAD

**Issue by Vladislav-bolgar** [Microsoft/vscode#42708]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
crane|Hvy|0.3.8

(6 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
vscode doesn't have support for this out of the box. You'll have to use one of the extensions that give PHP language support.
