### ISSUE TITLE
wrong comment syntax inside <?php ?> code block in a .blade.php file

### ISSUE THREAD

**Issue by vesper8** [Microsoft/vscode#42703]
What title says.. I've installed Laravel Blade Snippets which is supposed to add full support of Laravel .blade.php files

Inside my blade file I have a <?php $someCode; ?> block and if I try to comment lines inside this block it wraps the php code in "blade" comments 

```
{{--  $test = 1;  --}}
```

instead of
```
// $test = 1;
```

**Comment by roblourens** [comment]
VS Code doesn't have builtin support for Blade, so that behavior is coming from the extension
