### ISSUE TITLE
Link recognizer isn't too good with MSDN links (esp ones with open & close paren)

### ISSUE THREAD

**Issue by paultwright** [Microsoft/vscode#4270]
0.10.8 - VSCode Version:
Windows 7 Enterprise 
Version 6.1 (Build 7601: Service Pack 1) - OS Version:

Steps to Reproduce:

1. Copy & paste URL into editor from your favorite MSDN reference article.
For example: **https://msdn.microsoft.com/en-us/library/ee677285(v=azure.10).aspx**
2.  Note that the underlining stops before the close parenthesis and after the .10.

Expected Behavior:  Underline to the end of .aspx

**Comment by alexandrudima** [comment]
@paultwright Thank you for reporting, this is already fixed in 0.10.10, so please update to the latest release.
