### ISSUE TITLE
Terminal doesnt start

### ISSUE THREAD

**Issue by eleson2** [Microsoft/vscode#42718]
- VSCode Version:
Version 1.20.0-insider
Commit 9affae559e7b6dd46acfe2ac3123fb0ea87c6615
Date 2018-02-01T05:15:24.027Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:  Windows 7 enterprise

Steps to Reproduce:

1. Press shortcut to start integrated terminal
2. A short flash of terminal windows is shown and then it disappears.
Alt:
1. Press shortcut to start  Problem, output or Debug.
2. Click on the Terminal tab. 
3. A short flash of terminal windows is shown and then it disappears.

Does this issue occur when all extensions are disabled?: Yes/No
Yes 

Also, yesterdays release showed a problem when related to connecting to azure. 
That problem doesn't show today. 
Terminal is cmd.exe

**Comment by crissi** [comment]
same here, using same version

**Comment by user3323** [comment]
> Version 1.20.0-insider
> Commit 9affae559e7b6dd46acfe2ac3123fb0ea87c6615
> Date 2018-02-01T05:15:24.027Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

win7x64

The same problem! What the hell? It was never like this before.

User settings for terminal:

>   "terminal.integrated.fontSize": 16,
>   "terminal.integrated.cursorBlinking": true,
>   "terminal.integrated.cursorStyle": "line",
>   "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"

Here is how it looks like, when I press **Ctrl+~**

![terminal disappear](https://user-images.githubusercontent.com/24613274/35680311-a5adeea6-0762-11e8-8c14-5cdf47171665.gif)

**Comment by user3323** [comment]
update has arrived... now it's **fixed**

> Version 1.20.0-insider
> Commit 519088548b09221e9d590d2e10e14ec6d27ac79a
> Date 2018-02-01T14:21:12.284Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

**Comment by eleson2** [comment]
Update downloaded and I can confirm this is resolved.
