### ISSUE TITLE
First opened terminal does not get focus

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42713]
### Issue Type
Bug

### Description

- Close terminal
- Restart
- Open terminal via keyboard shortcut
-> The terminal does not get focus, I cannot start typing immediately

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (9affae559e7b6dd46acfe2ac3123fb0ea87c6615, 2018-02-01T06:08:26.978Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.64GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir tmp/user --extensions-dir tmp/ext|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/40416
