### ISSUE TITLE
Using mouse middle click in explorer 

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#42712]
For file explorer - treating middle click like double click: `open file/toggle tree` (or, perhaps, a little bit different: open file and not change focus?)

**Comment by bpasero** [comment]
I extracted the one for quick open to: https://github.com/Microsoft/vscode/issues/42714

**Comment by bpasero** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/39534
