### ISSUE TITLE
Syntax highlight regex in find in file/s when regex is enabled

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#42715]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 16.04.3 x64

It would look nice if VS Code syntax highlighted regex in the find in file/s text fields when regex is enabled.

**Comment by rebornix** [comment]
this issue can be merged into https://github.com/microsoft/vscode/issues/76762. To make this happen, we may want to change the input box to a Monaco editor.
