### ISSUE TITLE
Can't open integrated terminal 

### ISSUE THREAD

**Issue by Abdullah-AlAttar** [Microsoft/vscode#42711]
### Issue Type
Bug

### Description

After the last update when I try to open the terminal , the termiinal window closes.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (9affae559e7b6dd46acfe2ac3123fb0ea87c6615, 2018-02-01T05:15:24.027Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|Memory (System)|11.90GB (4.62GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.0.12

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment]
Nope, sorry about that, it is not a duplicate.

It is caused by us having `node_modules.asar` being left-over from the previous installation.

**Comment by Tyriar** [comment]
Thanks for the quick fix @alexandrudima

**Comment by jochenvanwylick** [comment]
Fix worked for me today on Win10 with
![image](https://user-images.githubusercontent.com/3002474/35724830-78abad06-07ff-11e8-9dab-1877fd225640.png)
