### ISSUE TITLE
When inserting an emoji on OSX, it is placed two spaces left of the cursor

### ISSUE THREAD

**Issue by justinschuldt** [Microsoft/vscode#4271]
- VSCode Version: 0.10.11
- OS Version: OS X  10.11.1 (15B42)

Steps to Reproduce:
1. Press Control + Command + Space to bring up the emoji insert modal
2. Click one

Additionally, to actually see the emoji in VSC (instead of an empty square), I have to press backspace one time with the cursor to the right of the emoji.

I know this is a dumb bug, but figured I would log it anyway.
Keep up the great work, VSC is awesome.

**Comment by alexandrudima** [comment]
I have just tested this on a mac mini and it appears to be working fine now.

**Comment by roblourens** [comment]
For me, adding an emoji does very strange stuff right now. The emoji window still shows up in a random place (off screen in the gif) but when I click one, it duplicates text around the cursor, or just puts the emoji in the wrong place.

![jan-25-2017 11-01-29](https://cloud.githubusercontent.com/assets/323878/22304783/be3cacf4-e2ed-11e6-9cf8-029060f42ed8.gif)

**Comment by alexandrudima** [comment]
Maybe I should've recorded a gif of it working :) -- I tried on a mac mini, I'm not sure if that would make a difference.

**Comment by alexandrudima** [comment]
And the mandatory gif that this was working at least for me :

![osx-emoji](https://cloud.githubusercontent.com/assets/5047891/25750874/68b18236-31b3-11e7-84e3-9faa187770d2.gif)
