### ISSUE TITLE
Issue reporter: Improve 'API rate limit' label

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#42725]
- enter many search terms to the Issue reporter
- at some point 'API rate limit' shows up
- It wasn't clear to me what to do now

Ideally, this would never show up (not sure if it is feasible to use a hardcoded access token with limited capabilities)
Or, add a sentence that says that something like: 'Only 10 searches can be done within a minute'

**Comment by gregvanl** [comment]
How about saying something like "GitHub query limit exceeded. Please wait."?
"API rate limit exceeded" does let the user know where the throttling occurred or what they should do.
Can the issue reporter retry the query automatically after a timeout?

**Comment by RMacfarlane** [comment]
How about this?
![image](https://user-images.githubusercontent.com/3672607/35695645-feba3c08-0739-11e8-88ab-b5bcfa3a157c.png)
The time until reset is calculated from a value in GitHub's response. I can redo the search after the timeout. I'm not sure what token could be hardcoded safely, so will not attempt that right now.

**Comment by gregvanl** [comment]
I'm not sure you want to include specific numbers and timeout intervals since GitHub could change these. I would leave the message generic.

**Comment by RMacfarlane** [comment]
Ok, I'll just change it to "GitHub query limit exceeded. Please wait."
