### ISSUE TITLE
launch.json usewsl is not ignored on non-windows OS

### ISSUE THREAD

**Issue by rallu** [Microsoft/vscode#42723]
- VSCode Version: 1.19.3
- OS Version: Windows 10 & MacOSx

Steps to Reproduce:

1. Set `"usewsl": true` in launch.json in VScode windows to run code in bash. Works perfectly.
2. Git commit
3. Open in Mac VScode and get message about not finding Windows Subsystem for linux.

Maybe `usewsl` should be ignored on non-windows machines?

Annoying since now I have to change that value every time I change from Windows to Mac.

**Comment by weinand** [comment]
Oops, this is a bug.

As a workaround you can just wrap the `useWSL` attribute in a `windows`section like this:
```json
			"windows": {
				"useWSL": true,
			},
```
With this it only takes effect on windows.
