### ISSUE TITLE
Wrong highlighting when using ES6 interpolation

### ISSUE THREAD

**Issue by soyzamudio** [Microsoft/vscode#4272]
- VSCode Version: 0.10.11 (0.10.11)
- OS Version: 10.11.2

Everything after the interpolated text is highlighted as a string.

<img width="577" alt="screen shot 2016-03-15 at 11 31 24 am" src="https://cloud.githubusercontent.com/assets/3433118/13789496/96cdc332-eaa1-11e5-8ccb-4a05184cb4e4.png">

**Comment by vincecoppola** [comment]
+1

**Comment by aeschli** [comment]
See to be fixed in the March release.
I tried with this sample:
```json
function hello(param) {
    return {
        message: `This ${this.param[0].name} is out of stock`,
        buttons: [
            
        ]
    }
}

```
