### ISSUE TITLE
Add toggle terminal keyboard shortcut

### ISSUE THREAD

**Issue by dtrugman** [Microsoft/vscode#42728]
Currently, we can toggle, focus and manipulate the integrated terminal using the following actions and more:
```
workbench.action.terminal.toggleTerminal
workbench.action.terminal.focus
workbench.action.terminal.focusAtIndex1
...
workbench.action.terminal.focusAtIndex9
workbench.action.terminal.focusNext
workbench.action.terminal.focusPrevious
```

But, **we cannot toggle the integrated terminal's _location_ from bottom to side** using a keyboard shortcut! (only using the integrated 'Move to Side' or 'Move to Bottom' buttons)

This change in location allows easier transition from programming mode to debugging/running/etc during development and I believe it to be very useful.

**Comment by user3323** [comment]
Great idea!

But, please, make it at least just work! Cause it doesn't.

https://github.com/Microsoft/vscode/issues/42718

**Comment by Tyriar** [comment]
You can toggle the position of the panel/terminal with this command: `workbench.action.togglePanelPosition`
