### ISSUE TITLE
Open File: unable to open a file with spaces in name if absolute path is provided

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42726]
Steps to Reproduce:

1. open quick open (Cmd+P)
2. paste the absolute path of an existing file that contains spaces (for me: `C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js`)

=> no results shown to open

**Comment by humphd** [comment]
I was teaching my students about workflows for fixing bugs in VSCode, and used this bug as an example.  I wrote them a guide at https://github.com/humphd/vscode/tree/good-first-experience-issue-42726#walkthrough-fixing-a-bug-in-visual-studio-code.

I was going to do a PR, but it looks like one of them beat me to it, so I'll let @aushakou continue.

**Comment by bpasero** [comment]
Good findings 👍

**Comment by tsalinger** [comment]
Doesn't work for me. Tested on Win10 and Ubuntu

**Comment by bpasero** [comment]
@roblourens @chrmarti this probably got lost when moving to RipGrep for search. The idea is that a full absolute path of an existing file should always return a result, at least from quick open (not sure about other use cases). Let me know if this should be baked into the file-search or if we should add this to the picker as a special case and let the search service behave as before.

**Comment by chrmarti** [comment]
This works when there are no spaces in the path on Mac. So the code is still there, we just need to fix it.

**Comment by bpasero** [comment]
@chrmarti can you point me to the code?

**Comment by chrmarti** [comment]
Here: https://github.com/Microsoft/vscode/blame/master/src/vs/workbench/services/search/node/fileSearch.ts#L569

The path gets there without the spaces due to: https://github.com/Microsoft/vscode/blame/master/src/vs/base/parts/quickopen/common/quickOpenScorer.ts#L314

**Comment by bpasero** [comment]
@chrmarti thanks, my fix was not complete it seems.
