### ISSUE TITLE
Terminal: Scrollbar disapears when switching from Retina to non-retina display

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#42727]
Verifying https://github.com/Microsoft/vscode/issues/34320

Version 1.20.0-insider (1.20.0-insider)
9affae559e7b6dd46acfe2ac3123fb0ea87c6615
2018-02-01T06:03:40.857Z

- open VSCode a retina monitor
- open the terminal
- drag vscode to non-retina monitor
- note that the scrollbar is no longer shown
- resize the terminal (or VSCode) brings it back

**Comment by lramos15** [comment]
@Tyriar @aeschli  I can no longer reproduce this issue
