### ISSUE TITLE
Can't search different words in different tabs at the same time

### ISSUE THREAD

**Issue by guerrerocarlos** [Microsoft/vscode#42724]
- VSCode Version: 1.19
- OS Version: MacOS High Sierra

Search box gets auto populated with the search box from the previous tab, making it impossible to search different words on each tab and change between them at the same time.

Steps to Reproduce:

1. Open two files, one in each tab.
2. Press Ctrl+F in both tabs.
3. Search for a word in one tab.
4. Select the other tab.

**Result: The content from the previous tab search box is automatically (and unexpectedly) added to the current search box.**

Does this issue occur when all extensions are disabled?: Yes

![vscode-error](https://user-images.githubusercontent.com/82532/35676546-d490f6f4-0754-11e8-9f46-9580162da7df.gif)

**Comment by roblourens** [comment]
You can disable this behavior with `"editor.find.globalFindClipboard": false`

**Comment by rebornix** [comment]
Close as the solution is provided above.
