### ISSUE TITLE
Implement Copy-Paste and Drag'n'Drop from File Explorer

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#42722]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299

![vs code drag-drop](https://user-images.githubusercontent.com/4777512/35675604-ad3e29b4-0759-11e8-86f4-10aea16f3b77.gif)

**Comment by Deilan** [comment]
There's already existing #6566, which was closed by the author for some reason.

**Comment by bpasero** [comment]
@Deilan you can drop from the file explorer into the VS Code explorer unless you run as administrator, are you?

**Comment by Deilan** [comment]
@bpasero Oh, that's right. But Copy-Paste doesn't work even without administrator privileges
