### ISSUE TITLE
Close Unmodified Editors: does not work when invoked from command palette

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42732]
Steps to Reproduce:

1. run "Close Unmodified Editors in Group" from command palette
 
=> nothing happens

**Comment by isidorn** [comment]
Great find man!

How many different ways can a man close an editor?? A bunch I tell you.

**Comment by bpasero** [comment]
@isidorn one command to rule them all, one command to find them, one command to bring them all and in the darkness bind them!

**Comment by isidorn** [comment]
@bpasero exactly my thinking 🧙‍♂️
