### ISSUE TITLE
[bat] The command `set "flag="` breaks syntax highlighting

### ISSUE THREAD

**Issue by DmitrySokolov** [Microsoft/vscode#42733]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
hg|mrc|1.2.3
cpptools|ms-|0.14.6
cmake|twx|0.0.17

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Create test.cmd
```bat
@echo off
setlocal
set "flag="
endlocal

exit /b 0
```

EXPECTED
`endlocal` and the rest of command are highlighted

ACTUAL
`endlocal` and the rest of command have the default font color

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to mmims/language-batchfile#23

**Comment by aeschli** [comment]
Fixed in mmims/language-batchfile#23, reopening to sync our grammar

**Comment by aeschli** [comment]
Updated the grammar

**Comment by alexandrudima** [comment]
![image](https://user-images.githubusercontent.com/5047891/39186183-e92f3c28-47c9-11e8-9d1b-e5fd0e6bbfd7.png)
