### ISSUE TITLE
Issue Reporter: looks unbalanced now

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42734]
See below:

![image](https://user-images.githubusercontent.com/900690/35682120-ddc465a2-075f-11e8-805a-255c4c231c9e.png)

I find the issue reporter quite unbalanced and harder to read now. E.g. the checkbox seems out of place.

**Comment by kieferrm** [comment]
I agree, the current layout is not the best. A few things come to mind:
- There are 4 distinct groups or sections. These sections should visually be distinguished by padding around them.
   - Type and Title
   - System Info
   - Reproducible with Extensions
   - Steps
- The check box on the left for the Reproducible with Extensions section sticks out. We should experiment with replacing it with a horizontal radio button group with (yes, no). We ask a question and it's a single choice answer.

**Comment by RMacfarlane** [comment]
How about this?
![image](https://user-images.githubusercontent.com/3672607/35710175-e3c38f40-076a-11e8-886a-836f77440c48.png)

**Comment by bpasero** [comment]
Better, but still: https://github.com/Microsoft/vscode/issues/42805
