### ISSUE TITLE
Extensions: allow to right click to bring up gear menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42737]
No reason not to allow that imho:

![image](https://user-images.githubusercontent.com/900690/35683204-8115f268-0763-11e8-8557-99d9de43ffcf.png)

**Comment by jrieken** [comment]
Doesn't work for me...

**Comment by sandy081** [comment]
@jrieken It's only for gear menu which means only for installed extensions. Did you try on installed extensions?

**Comment by sandy081** [comment]
It works for me

![image](https://user-images.githubusercontent.com/10746682/46016281-a6de8200-c0d4-11e8-989b-71bcf5f9e488.png)

**Comment by jrieken** [comment]
yes

**Comment by jrieken** [comment]
> allow to right click to bring up gear menu

this is about the gear, right? not the row

**Comment by sandy081** [comment]
Context menu is for the list entry not for the gear.

@bpasero What was your expectation?

**Comment by sandy081** [comment]
@jrieken It is context menu on the row (or extension) not on the gear icon.

**Comment by jrieken** [comment]
almost anywhere ;-)

**Comment by bpasero** [comment]
Yeah that is an "issue" with any context menu in any tree/list that has an action under the cursor.
