### ISSUE TITLE
Changing between editors quickly looses folding state

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#42738]
Verifying #40114

```
- add to keybindings
[
    {
        "key": "shift+ctrl+a",
        "command": "workbench.action.nextEditorInGroup"
    },
    {
        "key": "shift+ctrl+s",
        "command": "workbench.action.previousEditorInGroup"
    }
]
```
- open 2 files in separate tabs
- in one file, fold some sections
- use the two shortcuts very quickly. Note that at some point the folding gets lost

**Comment by bpasero** [comment]
@aeschli I think this is not an issue with the workbench saving the state. the change that I did is to always store the proper state for the model that is currently visible, here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/textEditor.ts#L251

**Comment by aeschli** [comment]
The problem is on the folding side. Folding regions are updated async, initially triggered by 'restoreViewState'. If 'saveViewState' is called before the async update is finished is sync, the uninitialized, 'empty' state is stored.
