### ISSUE TITLE
Provide API to pull information from language service

### ISSUE THREAD

**Issue by joelday** [Microsoft/vscode#4273]
It would be helpful to be able to pull information from the language service that is already running, either just to ensure that separate compilation is identical to that of the language service. This would allow extensions to more easily add features such inferred types, etc. Would also provide performance significant gains.

**Comment by jrieken** [comment]
The extension can export API to other extensions

**Comment by dbaeumer** [comment]
Agree. We already discussed that a while ago but I haven't found time to implement yet.

**Comment by joelday** [comment]
@dbaeumer excellent to hear! I assume this has additional interop/remoting challenges? I don't know much about how the language servers work.

**Comment by dbaeumer** [comment]
@joelday the idea is actually to provide API and extension could use in the extension host. So you would not know that there is a server running.

**Comment by mjbvz** [comment]
I believe that TypeScript server plugins enable this sort of functionality: https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

Here's a simple example vscode extension that registers a tslint plugin with the typescript server: https://github.com/mjbvz/test-vscode-tsserver-plugin We haven't fully rolled out this functionality yet so the API may chance

Please take a look at using TS server plugins and let me know if you run into any issues or have any questions

**Comment by octref** [comment]
@mjbvz Is `typescriptServerPlugins` contribution point already enabled? Currently if I install your extension, do I get that plugin auto running with bundled TS or does it have to be workspace's version of TS? I didn't see it in either https://github.com/styled-components/vscode-styled-components/blob/master/package.json or your styled repo.

@jrieken 
> The extension can export API to other extensions

Do you have an example somewhere? Can't find any in vscode-extension-samples.

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/blob/5ecc577420b7ad266966861803e160d2ea33a889/src/vs/vscode.d.ts#L6184
