### ISSUE TITLE
Focus border around drop-down of custom combo (Windows)

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42743]
### Issue Type
Bug

### Description

Looks unexpected to me:

![image](https://user-images.githubusercontent.com/9205389/35685501-33ab8db0-076a-11e8-9b5c-bad96562ce97.png)

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (519088548b09221e9d590d2e10e14ec6d27ac79a, 2018-02-01T14:21:12.284Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|5.98GB (2.86GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces without extensions

**Comment by bpasero** [comment]
I would say this is "as designed". The native dropdown also had such a style:

![image](https://user-images.githubusercontent.com/900690/35688523-a9810e6e-0771-11e8-8895-f3d449501e98.png)

**Comment by cleidigh** [comment]
@chrmarti 
@bpasero 
FYI,  in my original submission I had actually added a new color for the drop-down outline.  That was deemed unnecessary.  Do we want to reconsider that or close this?

**Comment by bpasero** [comment]
I would close as designed, but let's hear from @chrmarti

**Comment by chrmarti** [comment]
I'm fine with the current design. It just jumped at me at first. Closing.
