### ISSUE TITLE
Explorer empty/unused space on left

### ISSUE THREAD

**Issue by mlepage** [Microsoft/vscode#42757]
Typically I use VS Code full screen with one or two panes, and explorer visible but as narrow as possible. My directory tree visible in explorer can get several levels deep, and with file names such as long_file_name.c, often I can see only the beginning of them in explorer. This is not optimal, as often a lot of source files share the same prefix (first few words).

This problem goes away if I make explorer wider, but I want to keep that space for source code. It doesn't seem to me that I can scroll the explorer view horizontally (please correct me if I am wrong), which would also allow me to see more of my file names.

Is it possible to have a mode where the visible content of explorer is right justified instead of left justified? This would only be the case for the expanded directories. I think such a mode could benefit in this case, and if there's downsides, I'd love to hear about them.

Also, I notice there is quite a bit of unused space on the left, in two ways. Maybe we can address these?

First unused space is because my directory tree is several levels deep, I acknowledge that. But if I scroll back up to the top, there's an expand triangle icon to the left of my top level directory, which isn't necessary in this case since I have only the one top level directory. Wouldn't a user with only one directory in the explorer want it always expanded? (Is there some purpose for collapsing it that I can't think of?) Because if it's always expanded and no good reason to collapse it, I'd gladly love to have that icon go away and recover that horizontal space (it's worth 3-4 characters in a file name I wager). I'd love at least to have a project option to omit it, something like top-level-directory-collapsible=false.

Second unused space is to the left of that top level directory and its collapsing icon. I'm looking at my screen and there's another whole empty margin to the left of all content in my explorer, worth another 4 characters or so of file name. To my eye it looks like maybe the sort of margin where clicking in it would activate breakpoint icons or something, but I've never seen anything there. Does that empty margin on the left serve a purpose? I'd gladly get rid of it to push my explorer contents quite close to the left, to recover more horizontal space for file name characters.

If the space is purely for visual aesthetics, then can I suggest that when the user resizes the explorer pane to the minimum width, that it recognize that the user is trying to get more space, and if the content (file names) still exceeds the width, then eliminate the margin? So sort of a more content-aware layout that anticipates the user's needs and desires.

Does that make sense? What do you think?

- VSCode Version: 1.19.3
- OS Version: Debian 9

Steps to Reproduce:

1. Open file explorer with workspace/folder somewhat deep
2. Make explorer as narrow as it can be

**Comment by isidorn** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/15539
