### ISSUE TITLE
VSC find populates chrome search in browser 

### ISSUE THREAD

**Issue by davidjforhan** [Microsoft/vscode#42755]
I don't think this is supposed to happen. Other glitchy things are happening  between chrome and VSC. I'm on Chrome Version 64.0.3282.119 (Official Build) (64-bit)
VSC just recently updated.

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0

---

Steps to Reproduce:

1. perform a search in chrome
2. switch to VSC, search box is populated with chrome search
3. in reverse, search in VSC updates search box in chrome

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
This can be disabled with `"editor.find.globalFindClipboard": false`
