### ISSUE TITLE
Allow SCM Commands to be executed on a workspace level

### ISSUE THREAD

**Issue by kwiesmueller** [Microsoft/vscode#42754]
Today I stumbled about this issue where I had to edit all of our Docker Projects residing in own git repos.
I loved to finally have the new workspaces feature, but when finishing my work and wanting to commit I was looking for a way to commit and push all repos at once.
This would be a critical addition for me.
I could imagine simple Cmd+Shift+P Commands like 'git push all'.

Cheers,
kwiesmueller

**Comment by joaomoreno** [comment]
There's a hidden command which does exactly that: `git._syncAll`. We don't advertise it because it's a shaky and dangerous operation. But if you know what you're doing, feel free to assign a keybinding to it.
