### ISSUE TITLE
Uninstalling of language pack extension doesn't take affect after reload

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42759]
Testing #42366 (tried on both Windows and Linux)

- Go through the steps in #42366 till you see the translations in the product
- uninstall the language pack extension and reload when prompted
- The translations do not go away
- Close VS Code and open again
- The translations are now gone

**Comment by sandy081** [comment]
Yeah this is expected. It is required to restart VS Code to change the language.

@dbaeumer FYI
