### ISSUE TITLE
VScode not showing All PSdrive

### ISSUE THREAD

**Issue by mikedopp** [Microsoft/vscode#42756]
- VSCode Version:1.19.3
- OS Version: Win7 Pro 64

Steps to Reproduce:

1. import-module Vmware.VimAutomation.Core
    Connect-VIServer <local.io>
PSDrive
2. Visual Studio Code cannot find PSdrive's for VimDatastore
    Powershell Admin Console can. Not sure of cause.

Does this issue occur when all extensions are disabled?: Yes then I cant run Powershell...
![psdrive_powershelladminconsole](https://user-images.githubusercontent.com/6381494/35694543-e7549f2c-073e-11e8-9b80-e1d206ad3978.PNG)
![vscode_psdrive](https://user-images.githubusercontent.com/6381494/35694552-eae05ab4-073e-11e8-8f08-def9cb0cd4a0.PNG)

Weird right?

**Comment by alexandrudima** [comment]
I guess our integrated terminal is not running as Administrator ?

**Comment by Tyriar** [comment]
Yeah the terminal doesn't run as admin unless VS Code is running as admin. Closing this as designed for now.
