### ISSUE TITLE
Weird diff result

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#42751]
Extracted from https://github.com/Microsoft/vscode/issues/9012#issuecomment-361654763

@alexandrudima Not sure if it is expected, why does the additional space in the second line in the following diff is not highlighted

![image](https://user-images.githubusercontent.com/10746682/35578635-f323c022-05e4-11e8-99b6-4bcb44498e46.png)

**Comment by sbatten** [comment]
When verifying, I found this case where the fourth line claims it preserves some spaces on the left but are all highlighted on the right.


![image](https://user-images.githubusercontent.com/6561887/40755572-ce983596-6433-11e8-8c8f-7477ba99c5ba.png)

**Comment by alexandrudima** [comment]
Here is a Copy-Paste friendly version of the screenshot above 

```
   farst line
sacond line   
thard line
   faurth   line   
```

```
first line   
   second    line
third line   
      fourth     line     
```

---

The diff algorithm matches the 3 spaces on original line 4 with the spaces on modified line 3. i.e.

<img width="893" alt="screen shot 2018-05-31 at 09 53 17" src="https://user-images.githubusercontent.com/5047891/40769652-d66db068-64b8-11e8-8c2c-a83308b7e8fa.png">

---

This is expected, as the character level diffing runs on multiple lines. Here is a clearer example:

```
hello my dear world
```
```
hello my 
lovely world
```

IMHO this is a good thing, as it allows me to see that "dear" was replaced with "lovely" and a newline was added

<img width="713" alt="screen shot 2018-05-31 at 09 58 25" src="https://user-images.githubusercontent.com/5047891/40769828-4490dfde-64b9-11e8-80eb-c19637c991a2.png">

**Comment by sbatten** [comment]
thanks for the explanation. I agree, I just missed the transferring of spaces and thought there could be a deeper issue.
