### ISSUE TITLE
[Localization] View -> Toggle Render Whitespace is not being translated

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4275]
- VSCode Version: 0.10.12-alpha --locale=fr (or any locale)
- OS Version: Windows 10

"Toggle Render Whitespace" under the View menu is not being localized in any language even though it is bracketed in --locale=pseudo.

![togglerenderwhitespace](https://cloud.githubusercontent.com/assets/12900364/13791540/d7c1ab0c-eaaa-11e5-9f12-337846465828.JPG)

**Comment by isidorn** [comment]
I have it under nls localize [here](https://github.com/edumunoz/vscode/blob/master/src/vs/editor/contrib/indentation/common/indentation.ts#L173)
I guess we do not have newer translations - moving to @dbaeumer

**Comment by dbaeumer** [comment]
We haven't received translation yet for that string. Closing.
