### ISSUE TITLE
Change python block comment to """

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/vscode#42767]
Per https://github.com/Microsoft/vscode-python/issues/473

VSC provides Python config file currently contains `"blockComment": [ "'''", "'''" ]`
while users want  `blockComment": [ "\"\"\"", "\"\"\"" ]`

**Comment by aeschli** [comment]
@DonJayamanne Don, your opinion?

**Comment by DonJayamanne** [comment]
@aeschli I agree with this change
