### ISSUE TITLE
Quick Open does not show files in newly added folders

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42762]
### Issue Type
Bug

### Description

![quickopen](https://user-images.githubusercontent.com/4033249/35698701-b593d99a-0742-11e8-9f51-bea0c29f7b63.gif)

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (519088548b09221e9d590d2e10e14ec6d27ac79a, 2018-02-01T14:12:38.058Z)
OS version: Darwin x64 17.3.0

**Comment by octref** [comment]
Me and @roblourens didn't get a reliable repro yet. Will keep an eye on it if it happens again.

**Comment by bpasero** [comment]
@octref that is pretty bad, does the fulltext search also not work?

**Comment by roblourens** [comment]
We saw this once or twice, then tried many more times and never saw it again. So we didn't try text search or debug while it was reproing :/

Logs showed that it was running rg on the right folder, but apparently losing the results somewhere, which is a weird problem.
