### ISSUE TITLE
Cannot launch deugger

### ISSUE THREAD

**Issue by dblairski** [Microsoft/vscode#42768]
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: socket hang up).

- VSCode Version: 1.19.2
- OS Version: 8.1

Steps to Reproduce:

1. Press f5
2. see error: Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: socket hang up).

Does this issue occur when all extensions are disabled?: Yes
![vscodeerror](https://user-images.githubusercontent.com/17909648/35701941-e40c6d5c-0754-11e8-9b64-023be1c5061e.JPG)

**Comment by auchenberg** [comment]
We recommend you using the "launch" configuration for Chrome, so please use the "Launch Chrome against Localhost" config, unless you know how to enable remote debugging in Chrome, etc.
