### ISSUE TITLE
Changes made to translations in generated language pack extension do not take affect

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42760]
Testing #42366 (tried on both Windows and Linux)

- Go through the steps in #42366 till you see the translations in the product
- Uninstall the extension
- Now make some changes to the translation strings. I chose the `actions.clipboard.pasteLabel`
- Create the vsix again and install it
- The updated translations do not appear

**Comment by ramya-rao-a** [comment]
Tried again (this time changing the version of the extension before creating the vsix) and it worked.
This is weird...
When installing extensions via vsix, the version shouldn't matter. What's being installed should always override anything thats in the product

**Comment by sandy081** [comment]
@ramya-rao-a We do override when you install from VSIX. 

In this case, we hold the cache of translation files by extension id + version. Hence, version change is needed to revalidate the cache.

**Comment by ramya-rao-a** [comment]
@sandy081 Wont this be a hindrance for extension developers? Unlike other extensions, we can't just F5 to see the language pack in action. The only way is to create a vsix and install it. This will force users to keep incrementing the version over the course of developing/testing the extension

**Comment by sandy081** [comment]
@ramya-rao-a Valid point. 

@dbaeumer Why can't we support normal extension development workflow for lang pack extensions? This would be more expected.

**Comment by dbaeumer** [comment]
The main problem here is that F5 doesn't start a new main process and the language detection has to happen in main. For example the global menus are created in main with the language of the first startup. So we would need a complete new way how we F5 VS.

What we could do to make this a smarter experience is that we delete an existing cache location for a language pack when installed and it exists. @sandy081 would this be something we can do?

**Comment by sandy081** [comment]
@dbaeumer I think, we have to invalidate `Language packs cache` (mine - primary) but not `Translations cache` (yours on main side) that depends on the former.

Language packs cache key is extension identifier + version. I might need an additional installation timestamp as the key.

**Comment by dbaeumer** [comment]
@sandy081 I would not add an installation time stamp to the key since under normal use cases it is not necessary. An extension with the same version must be the same extension when installed from the market place. So I would rather clean my cache if an LP extension is installed from the command line or via a VSIX directly.

**Comment by sandy081** [comment]
Discussed with @dbaeumer and we agreed upon adding time stamp to the hashkey only for vsix installations.

**Comment by dbaeumer** [comment]
Since we never received an outside report on this I will close it as out-of-scope. If someone feels strong about that we should address this, please speak up.
