### ISSUE TITLE
Command line not working as I'd expect

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/vscode#4276]
- VSCode Version: f291f4ad600767626b24a4b15816b04bee9a3049
- OS Version: Mac OS X 10.10.5 14F1605

## Steps to Reproduce

```
λ which code
/usr/local/bin/code
```

1. Start without VS Code open
2. Run `code -v`

### Expected
I see the version of VS Code.

### Actual
VS Code opens a new instance in my current working directory, editing a new file called `-v`. 

What am I doing wrong here? I see the same issue for flags like `--version` or `--help`.

**Comment by bpasero** [comment]
@NickHeiner are you sure you ran the "code" from /usr/local/bin/code? How did you install Code?

**Comment by NickHeiner** [comment]
> @NickHeiner are you sure you ran the "code" from /usr/local/bin/code?

Yes. When I run `which code`, it shows `/usr/local/bin/code`. 

>  How did you install Code?

I used whatever the instructions were on https://code.visualstudio.com/ when it first launched.

**Comment by bpasero** [comment]
@joaomoreno can you advise

**Comment by joaomoreno** [comment]
@NickHeiner, you probably pasted that code in, since we recommended to do it. Can you undo what you did in the instructions on https://code.visualstudio.com? This will make it work.

We should warn users about this.

**Comment by NickHeiner** [comment]
I actually don't know how to remove this. It's not in any of my files like `~/.bash_profile`. I tried the "Shell Command: Uninstall 'code' command in PATH" command, but that just made `which code` return nothing. `type code` still returns the same result.

**Comment by joaomoreno** [comment]
This is odd. `~/.bash_profile`, `~/.bashrc`, `~/.zshrc`... it's in none of those?

Which shell are you using? You can figure it out by running `echo $0`.

**Comment by NickHeiner** [comment]
I figured it out! My `bash_profile` included a file which included a file which defined the `code` function. I must have added that function as part of the original setup steps when VS Code was first released. Sorry for the confusion when I misstated above that it wasn't being brought in via `bash_profile`.

Once I remove that function, the `code` command works as expected. Awesome!

**Comment by Tyriar** [comment]
Good to hear :) closing this off.
