### ISSUE TITLE
Global search with file filters does not work for Network Shares 

### ISSUE THREAD

**Issue by deathly809** [Microsoft/vscode#42765]
If you open VSCode in an network share the "files to include" with a valid file extension returns nothing (* returns a subset of all results) and the "files to exclude" returns everything even with gibberish.

- VSCode Version:
C:\Users\jerobins.REDMOND>code --version
1.19.2
490ef761b76b3f3b3832eff7a588aac891e5fe80
x64

- OS Version:
Windows 10

Steps to Reproduce:

1. Open VSCode in a network share
2. Do your search with "files to include" or "files to exclude" set to something
3. In the files to exclude case it returns everything, in the files to include case it returns nothing.  (for me atleast)

As you can see in the image below I have some xml files.
![image](https://user-images.githubusercontent.com/1381210/35699142-10024848-0744-11e8-9a33-65d32b91e422.png)

When I filter "files to include" it fails.
![image](https://user-images.githubusercontent.com/1381210/35699153-15d23a62-0744-11e8-8dc6-35408d73b3a8.png)

I mounted the share as a drive and the problem went away.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
Could you try this with the Insiders version? There were some bugs fixed with UNC paths for search in the past month.

**Comment by deathly809** [comment]
@roblourens Seems to work correctly in the insiders version.
