### ISSUE TITLE
Terminal dropdown doesn't show selection when using arrow keys

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42761]
Version 1.20.0-insider
Commit 519088548b09221e9d590d2e10e14ec6d27ac79a
Date 2018-02-01T14:21:12.284Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

This is on Parallels so it's possible it's a VM glitch?

- Open Terminal
- Click on dropdown to expand
- Use arrow keys to change the selected value
- The selected item isn't highlighted

In 1.19 it's always highlighted blue. In 1.20 it's highlighted with a themed color in the debug viewlet dropdown. Maybe the theme color is not set correctly for the terminal one.

Notice the value changing in the select box title, but there's no indication in the list itself.

![feb-01-2018 11-13-54](https://user-images.githubusercontent.com/323878/35698117-0b8c834e-0741-11e8-9382-83622c2a17fb.gif)

**Comment by Tyriar** [comment]
I think this is related to the non-standard `select` implementation?

**Comment by cleidigh** [comment]
@roblourens 
I am trying to reproduce this but no luck so far.  I don't think Parallels is the likely issue Unless it does something very different from VMWare.  That is the way I do all my programming Windows7 under OS X.

@Tyriar you commented but it was not obvious to me if you are implying you also saw this?

I'm trying to figure out what else I can test to show this.

**Comment by bpasero** [comment]
@roblourens what theme are you using?

**Comment by roblourens** [comment]
Monokai
