### ISSUE TITLE
[Localization] Extensions icon hover tooltip not localized

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4277]
- VSCode Version: 0.10.12-alpha --locale=fr (or any locale)
- OS Version: Windows 10

Steps to Reproduce:

1. Launch a localized VS Code instance
2. Hover over the extensions icon in the bottom left
3. "Extensions" tooltip is not localized 

![extension hover](https://cloud.githubusercontent.com/assets/12900364/13792586/bf4f815c-eaaf-11e5-9c8a-1e2dc2068a37.JPG)

**Comment by joaomoreno** [comment]
[It is](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsWidgets.ts#L95), we just didn't send it to the localization team.
