### ISSUE TITLE
Cursor gets hidden during debugging so I can't step over breakpoints

### ISSUE THREAD

**Issue by computersarecool** [Microsoft/vscode#42774]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Make a breakpoint on a line of code
2. "Start Debugging" or press F5

Does this issue occur when all extensions are disabled?: Yes

I am making an OpenGL app.  When it encounters a break point the cursor gets hidden, so I can not use my cursor to step through the break point.  Effectively it leaves my computer frozen unless I use my keyboard to kill the process.

The cursor should not be hidden during debugging as it makes it impossible to use the debugger at all.

**Comment by isidorn** [comment]
This is either caused by your debugging extension or your theme extension

**Comment by computersarecool** [comment]
Actually it was caused by the fact that my application (and the [GLFW](https://github.com/glfw/glfw) library hid my cursor.  It seems that there should be a way to prevent this in the application though.
