### ISSUE TITLE
Previous version of extension not removed from `extensions` directrory

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#42772]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: None (All disabled)

Steps to Reproduce:

1. Install the previous version of the Python extension from the VSIX file (https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/0.9.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage)
2. VS Code will automatically download the latest version `2018.1.0`.
3. Everything seems to be ok, however if you look at `.vscode/extensions` directory both versions of the Python extension are in there.

**Note:** 
* Previously I had the previous version of the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) installed from the Marketplace not a VSIX file. 
* However to replicate the issue I had to obviously install from a VSIX.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@DonJayamanne We remove the deprecated extension in the next restart.

**Comment by DonJayamanne** [comment]
yes, thats fine. thanks
Just checked the old version is out. Funny didn't realize this happened in start. I though re-loading VS Code would remote the old version.

**Comment by sandy081** [comment]
We did not do on reload because there could be always another window which could be still using it.
