### ISSUE TITLE
YAML indentation always is reset to 4 

### ISSUE THREAD

**Issue by KJTsanaktsidis** [Microsoft/vscode#42771]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.0
vscode-docker|Pet|0.0.23
gitlens|eam|7.5.10
Go|luk|0.6.73
terraform|mau|0.0.20
python|ms-|0.9.1

---

Steps to Reproduce:

1. Configure tab indentation to be 2 spaces:
```
"settings": {
    "editor.tabSize": 2,
    "editor.detectIndentation": false,
    "[yaml]": {
        "editor.insertSpaces": true,
         "editor.tabSize": 2,
         "editor.detectIndentation": false,
      }
  }
```
2. Open a Yaml file, which is indented with 2 spaces
3. Switch to another tab (absolutely _anything_ can be in it)
4. Switch back to the YAML file.
5. The indentation setting has been set to 4 spaces (as indicated in the bar at the bottom). Pressing the tab key will insert 4 spaces now instead of 2.

Reproduces without extensions: Yes

Any ideas what might be causing this?

**Comment by usernamehw** [comment]
EditorConfig?

**Comment by alexandrudima** [comment]
Disable EditorConfig. Does the issue still reproduce? If yes, then check for `.editorconfig` files in your folder hierarchy.

**Comment by KJTsanaktsidis** [comment]
```
[*]
indent_style = space
indent_size = 4
```

Derp. Thanks!
