### ISSUE TITLE
"auto import" adds extra tabs

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42776]
Log file ID: 1376465198

As I showed you.

I couldn't repro this in other files.

- Open preferencesRenderers.ts
- It has `import * as arrays from 'vs/base/common/arrays';`
- Type `first`
- Pick auto import option from 'arrays'.
- It adds `arrays.				first` with several tabs between arrays and first. 

See the verbose log in `typescript_13`

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/21891 upstream with minimal repo
