### ISSUE TITLE
Extension Authoring - Access Configuration Property from Package.json

### ISSUE THREAD

**Issue by hipstersmoothie** [microsoft/vscode#42779]
Is it possible to access settings defined in configuration in the package.json?

I would like something like:
```json
    "contributes": {
        "jsonValidation": [
            {
                "fileMatch": "{{config.my.prop}}",
                "url": "someSchema"
            }
        ],
        "configuration": {
            "title": "My Config",
            "properties": {
                "my.prop": {
                    "type": "string",
                    "default": "*.json",
                    "description": "Something"
                }
            }
        }
    }
```

**Comment by sandy081** [comment]
@hipstersmoothie Please look at the api `getConfiguration`. Reference:  https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace

**Comment by hipstersmoothie** [comment]
I read about that API but it seems like I would have to write some JS to get that working. Is it possible just to do it all like I have in the example above? Specifically i want to do it all in the package JSON:

1. Define a config setting
2. use that setting in another part of the "contributes" section - in my case jsonValidation

**Comment by sandy081** [comment]
@hipstersmoothie Ah I see now what you are asking for. I do not think that can be done now.
