### ISSUE TITLE
A Folder is stuck in git

### ISSUE THREAD

**Issue by elieobeid7** [Microsoft/vscode#42775]
![capture](https://user-images.githubusercontent.com/660142/35710969-1c04d9d8-07c3-11e8-84a5-dadff09294f6.PNG)
This folder is stuck in git, even if I add `vendor/*` to git ignore, even if I discard it, tried all the options, adding the vendor's folder fixed it in git, in terminal, not in vscode git viewer. I'm on windows 10 and vscode latest update.

the folder in question is

https://github.com/mebjas/CSRF-Protector-PHP

installed through composer. So to summarize, adding the entire vendor folder solved it in git, in vscode, no option makes the file disappear.

**Comment by joaomoreno** [comment]
https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore

**Comment by elieobeid7** [comment]
The folder I was trying to commit, had a `.git` folder inside it, removing that fixed the problem

https://stackoverflow.com/a/5898123/1920003
