### ISSUE TITLE
suggestion: always show list of explorers on right click on explorer sashes

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#42770]
When I right click on a contributed explorer sash, i get a context menu to Hide it:

![image](https://user-images.githubusercontent.com/1487073/35703090-cf7e81d6-074f-11e8-99d9-45aebc326770.png)

To unhide it, i have to know to right click on the `EXPLORER` area at the top of the viewlet, and then I get a nice list that I can toggle things on/off:

![image](https://user-images.githubusercontent.com/1487073/35703095-d548db98-074f-11e8-80c9-01ee35c14f43.png)

This suggestion is to show the entire context menu on the right click of any explorer sash, instead of the "Hide" context menu. This would give me as the user an indication that i can toggle explorers on/off as soon as i find the context menu.  

![image](https://user-images.githubusercontent.com/1487073/35704300-e2f33352-0753-11e8-87bb-6dbea1e14044.png)

**Comment by kieferrm** [comment]
We should also show the context menu in the space below the last sash when all sections are closed. For example, below Azure Storage in the screen shot below. That would align the model with what we do in the activity bar and in the panel title bar. 

<img width="430" alt="screen shot 2018-02-01 at 2 39 15 pm" src="https://user-images.githubusercontent.com/4674940/35707208-b66eeac4-075d-11e8-838c-fc7ab8c002b3.png">

**Comment by sandy081** [comment]
The context menu on the view title is aligned with the rest of our UI (activity bar, panels). Context menu on the empty area is good.

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/36546037-98b01038-17ea-11e8-9854-2b351e33aee6.png)

![image](https://user-images.githubusercontent.com/10746682/36546047-a17ba18c-17ea-11e8-84c6-05a9378c91c1.png)

**Comment by bpasero** [comment]
@sandy081 can we show the explorer in that list too, just disabled? a bit unexpected to not see it imho:

![image](https://user-images.githubusercontent.com/900690/36727038-19f2b8ec-1bbc-11e8-9718-60e00153ef7b.png)

**Comment by bpasero** [comment]
@sandy081 I think there is still an issue that the sort order is not reflected in the menu:

![image](https://user-images.githubusercontent.com/900690/36778225-6c1ff5a2-1c6c-11e8-918b-675046eef962.png)

**Comment by sandy081** [comment]
It was like this from beginning. For no reason, I always show them in the default order. Change it to respect the current order.
