### ISSUE TITLE
Can not minimize or change window size on Linux

### ISSUE THREAD

**Issue by computersarecool** [Microsoft/vscode#42773]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Install and Run Visual Studio Code
2. Try to change the window size

Does this issue occur when all extensions are disabled?: Yes

I do not know if this is intentional design (I hope not) but I am unable to un-maximize or move the Visual Studio Code window.  I have installed taskbar tweaker which puts maximize / minimize / resize options on all of my windows, but Code does not display them (see image).

How can I resize the window?

![screenshot from 2018-02-01 15-53-37](https://user-images.githubusercontent.com/5414692/35709593-1c6547ec-0768-11e8-8d8f-0c704233871d.png)

(Here you can see chrome in the foreground with the resize buttons and Code in the background with no such buttons available)

**Comment by bpasero** [comment]
@computersarecool could you try with this newer build for Linux to reproduce: https://az764295.vo.msecnd.net/exploration/ed422f909ea470f79e3e3e39c948803d9b764919/code-exploration-1.22.0-1522303929_amd64.tar.gz
