### ISSUE TITLE
python workspaceFolder bug

### ISSUE THREAD

**Issue by zzylog7** [Microsoft/vscode#42787]
### Issue Type
Bug

### Description

python debug Error: spawn ${workspaceFolder}\env\Scripts\python.exe ENOENT, "env" is python venv directory , I modify .vscode/setting.json >> python.pythonPath to a full dir and it worked!

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (519088548b09221e9d590d2e10e14ec6d27ac79a, 2018-02-01T14:21:12.284Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|Memory (System)|11.91GB (6.19GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.10
vscode-eslint|dba|1.4.5
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.24
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
php-pack|fel|1.0.1
svn-scm|joh|1.13.2
php-cs-fixer|jun|0.1.56
python|ms-|2018.1.0
php-docblocker|nei|1.3.3
autodocstring|njp|0.1.4
vetur|oct|0.11.7
ayu|tea|0.12.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by alexandrudima** [comment]
Moved to https://github.com/Microsoft/vscode-python/issues/691
