### ISSUE TITLE
Hitting enter does not indent line properly

### ISSUE THREAD

**Issue by mccreeker** [microsoft/vscode#42782]
- VSCode Version: 1.19.2
- OS Version: W10LTSB

Steps to Reproduce:

1. Type a line of code that opens a block, like an HTML div tag or a PHP function or a Javascript function, then hit Enter.
2. Notice your cursor is plopped at the at the same horizontal point as the beginning of the above opening block line, instead of one indent inward.

![image](https://user-images.githubusercontent.com/33667567/35714865-6b2b1cc0-078c-11e8-84e6-ad8fbeb8d0da.png)

I read this may have something to do with TypeScript, but implied it deletes an empty line, but that's not what's happening here as it's keeping the other indents. Also I'm not using TypeScript, and as mentioned it happens when coding PHP and HTML too, and I'm not seeing that I'm using any code formatting TypeScript anything.

I thought this previous bug was the problem - https://github.com/Microsoft/vscode/issues/41702 - but apparently that's part of this bigger issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by andremacola** [comment]
If you change the language to HTML and then back to PHP the problem is solved until you close the editor.

**Comment by aeschli** [comment]
I need a code sample to reproduce...
