### ISSUE TITLE
Keywords on intellisense mixed in with React component properties

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/vscode#42788]
Hi, since latest update (I guess) the React's component properties are now mixed in with general keywords in intellisense. Any idea how can I turn off general keywords? Or is this a bug?

- VSCode Version: 1.19.3
- OS Version: Mac OS

Steps to Reproduce:

1. Open ~~TS~~ TSX React class **Edited**
2. Get class properties

![screen shot 2018-02-02 at 3 35 27 pm](https://user-images.githubusercontent.com/2682705/35716780-106c3258-082f-11e8-9b72-03aa9496a183.png)

![screen shot 2018-02-02 at 3 40 00 pm](https://user-images.githubusercontent.com/2682705/35716821-5aaf30a4-082f-11e8-8d05-f0d7fbc97821.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I'm unable to repo this in [VS Code insiders](https://code.visualstudio.com/insiders/). Can you please try the latest insiders build

If it still doesn't work, please share a complete code snippet and your user/workspace settings

**Comment by tomitrescak** [comment]
Hi, downloaded Insiders build. Following is the result:

![screen shot 2018-02-05 at 3 38 59 pm](https://user-images.githubusercontent.com/2682705/35788688-03c2e386-0a8b-11e8-98c3-f10429efe636.png)

Here is the code:

```ts
interface Props {
  a: number;
  d: number;
  z: number;
}
class Foo extends React.Component<Props> {
}

class Boo extends React.Component {
  render() {
    <Foo 
  }
}
```

These are my user preferences: 

```json
{}
```

These are workspace prefs

```json
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```

**Comment by in19farkt** [comment]
I have the same problem. If I use the version typescript 2.7.1, then the properties of the component are mixed with the keywords. When I switch the version to 2.6.2, the keywords are not displayed in the intellysense and the problem disappears.

- VSCode Version: 1.20.0
- OS Version: Ubuntu 17.10

**Comment by mjbvz** [comment]
Thanks!  Opened https://github.com/Microsoft/TypeScript/issues/21844 to track this upstream

Closing as upstream
