### ISSUE TITLE
JSON Intellisense Snippet Completion

### ISSUE THREAD

**Issue by hipstersmoothie** [Microsoft/vscode#42780]
Sorry if this shouldn't go here! But couldn't find any docs.

I noticed when authoring an extension i get snippet completions for some of the fields.

Such as:
```json
"configuration": { "title": "", "properties": {}}
```

and 

```json
"configuration":[{"title": "","properties": {}}]
```

How is this defined? In the schema? Or separate snippet files?

Could I get a link to an example or documentation on how to implement this behavior?

**Comment by hipstersmoothie** [comment]
Found it!

**Comment by hipstersmoothie** [comment]
On second though it would be cool if VSCode did the automatically based on the required properties in the schema

**Comment by hipstersmoothie** [comment]
Also when i have default snippets enabled and tab while typing a property, i am never given the option to pick from one of the defaults

**Comment by hipstersmoothie** [comment]
There also seem to be no merging of defaults via 'oneOf' or 'anyOf'

**Comment by aeschli** [comment]
Please file separate issues, thanks!
