### ISSUE TITLE
TypeScript language services stopped unexpectedly 5 times in the past 5 minutes.

### ISSUE THREAD

**Issue by adam2138** [Microsoft/vscode#42790]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
xml|Dot|1.9.2
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
icon-fonts|idl|1.10.1
easy-icons|jam|0.3.1
vscode-simple-icons|Lau|1.8.0
node-module-intellisense|lei|1.5.0
Go|luk|0.6.73
mssql|ms-|1.3.0
cpptools|ms-|0.14.6
vuejs-extension-pack|mub|0.3.0
vetur|oct|0.11.7
material-icon-theme|PKi|3.2.2
vscode-icons|rob|7.19.0
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by adam2138** [comment]
在过去 5 分钟内，TypeScript 语言服务意外中止了 5 次。

**Comment by alexandrudima** [comment]
Translation: "TypeScript language services stopped unexpectedly 5 times in the past 5 minutes."

**Comment by mjbvz** [comment]
A few questions:

- Does this happen if you disable all extensions?
- Does this happen for all projects you open, or just one specifically?
- Have you set a custom `typescript.tsdk` value in your workspace or user settings?

Can you also please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
