### ISSUE TITLE
Inbuilt source control (Git) not working properly.

### ISSUE THREAD

**Issue by vaibhavagrawal2912** [Microsoft/vscode#42791]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
githistory|don|0.4.0
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
terminal|for|0.0.10
html-css-class-completion|Zig|1.16.1

---

Steps to Reproduce:

1. Whenever I try to discard some changes or stage some changes I need to do it 2 times.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Does that happen always? Does it happen for every workspace you try it on? Can you record a screencase?
