### ISSUE TITLE
Create a git  branch outside vscode does not switch the branch in vscode

### ISSUE THREAD

**Issue by DrDelete** [Microsoft/vscode#42797]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.3.9
EditorConfig|Edi|0.12.0
tslint|eg2|1.0.24
debugger-for-chrome|msj|4.1.0
vscode-docker|Pet|0.0.23

---

Steps to Reproduce:

1. Open the terminal in vscode
2. From a master branch type 'git checkout -b feature/whatever
3. Watch vscode -> it does not automatically switch to it while for example VS2017 does this nicely.
4. The only way I see my new branch is when switching back to one of the already existing branches in the vscode. When I open the branch list, the new one is listed.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Are you sure it just doesn't take a bit to sync (up to 10 seconds)?

**Comment by DrDelete** [comment]
I wait a minute, still no changes

**Comment by joaomoreno** [comment]
Is the folder you have open in VS Code the root of the repository?

**Comment by DrDelete** [comment]
Yes.

When i created the branch in the terminal, the git context is switched, because when I try 'git branch -d feature/whatever' I get a valid git error because the context is already switched to the feature/whatever branch.

**Comment by joaomoreno** [comment]
What if you just checkout to another branch, does the state update? What if you touch a few files from the terminal, do they appear as modified eventually?

**Comment by DrDelete** [comment]
@joaonoreno : I want to know if you tried my reproduce steps... did you have the same issue?

**Comment by joaomoreno** [comment]
I tried and it doesn't reproduce. So... does it reproduce **for you** in the [insider release](https://code.visualstudio.com/insiders)?

**Comment by JanithaR** [comment]
The issue exists. I just checked out a branch from terminal and I saw the change reflected in SourceTree but not on VSCode. It still said 'master' at the bottom right. Only after going into 'Source Control' tab and clicking the 'Refresh' button at the top actually did the switch.
