### ISSUE TITLE
insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets not behaving correctly

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vscode#4279]
- VSCode Version: 0.10.12
- OS Version: OSX

 #4022
Steps to Reproduce:

1. add `"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true` to the workspace settings.  
2. open a TS file and copy `if (x) {var x = 1;}`
3. select the line and format
4. expected==Actual => `if (x) { var x = 1; }`
5. change the option to false. 
6. format again 
7. Actual == `if (x) { var x = 1; }` but expected  `if (x) {var x = 1;}`

**Comment by dbaeumer** [comment]
Moving to TS. We pass the right option to the tsserver.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7540

**Comment by magnushiie** [comment]
Now that InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces have been added to TypeScript, I think this issue should be reopened to add it to VS Code too.

**Comment by magnushiie** [comment]
Ah, Microsoft/vscode#18043 tracks this, waiting on Microsoft/TypeScript#13275
