### ISSUE TITLE
Icon theme: hidesExplorerArrows is not applied to all trees

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#42793]
Steps to Reproduce:

1. have an icon theme that sets `hidesExplorerArrows: true`
2. run a search

=> notice how the search uses twistie while the explorer does not

Not sure about custom views (cc @sandy081)

**Comment by sandy081** [comment]
This is not applied to custom views.

**Comment by sandy081** [comment]
IMO, hiding twisties in Problems view does not look good because Problems view has most of the times only one level of children. Hence I would prefer not to opt in there and leave this option only for explorer trees.

Assigning others who own respective areas.

**Comment by alexr00** [comment]
Since custom tree views often have elements that don't have icons, this should continue to not be applied to custom tree views.

**Comment by andreamah** [comment]
Search follows whatever SCM does with `hidesExplorerArrows`. It ignores it in list view (since most entries should be files, which require some visual cue to show collapse/expand state). In the tree view, it removes the arrow from the folders (https://github.com/microsoft/vscode/issues/163822).
