### ISSUE TITLE
Add option to hide the value of className and css props for React

### ISSUE THREAD

**Issue by kripod** [Microsoft/vscode#42796]
As CSS-in-JS is getting more and more popular, I think it would be great if all the inline styles could be hidden _(under a clickable `…` notation)_ when desired.

This way, the HTML structure of a JSX document could be emphasized without having to use separate files for styling.

**Comment by mjbvz** [comment]
Just to make sure I understand, do you mean collapsing long `style={...}` sections?

**Comment by kripod** [comment]
@mjbvz Yes, exactly. But all of them should be collapsible/expandable by a single click.

**Comment by mjbvz** [comment]
Thanks. Depends on #3422

**Comment by mjbvz** [comment]
So multi-line style blocks are already collapsible:

![apr-17-2018 15-36-32](https://user-images.githubusercontent.com/12821956/38902387-2a56cf74-4255-11e8-9428-4b95843d4faa.gif)

We don't support collapsing single line styles and I don't think support for folding within a single line is planned anytime soon
