### ISSUE TITLE
Cancelling opening a folder from a multi-root unsaved workspace corrupts the current worksapce

### ISSUE THREAD

**Issue by jtanx** [Microsoft/vscode#42799]
- VSCode Version: 1.19.3
- OS Version: Windows 10  10.0.16299.125

Steps to Reproduce:

1. Have an unsaved multi-root workspace (e.g. add two folders to the same workspace)
2. Have an integrated terminal open
3. Attempt to open a folder (CTRL + K O)
4. At the confirmation box, click cancel:
    ![image](https://user-images.githubusercontent.com/5137410/35722992-bafa9486-084c-11e8-9c98-a5077586b713.png)
5. Terminal is now broken: 
    ![image](https://user-images.githubusercontent.com/5137410/35723043-e62079e6-084c-11e8-99c9-9634e7c32fa2.png)
6. Various other things are broken. For example, I can't run extension commands any more.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jtanx** [comment]
I just tried on insiders and it does the same thing.

![image](https://user-images.githubusercontent.com/5137410/35726496-37471c2e-0859-11e8-8911-9a5f8c5855a6.png)


It's not just limited to the terminal, it's like it reaches a state where things are semi-destructed - including interacting with extensions - try run any extension command and it won't work.

**Comment by bpasero** [comment]
I can reproduce. Should probably first ask the main window to veto the unload before even forwarding this to the window.
