### ISSUE TITLE
Why is the use of CPU very high

### ISSUE THREAD

**Issue by varichs** [Microsoft/vscode#42792]
- VSCode Version:1.19.3
- OS Version:Windows10 x64

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/22510514/35719179-2124c7b0-0823-11e8-9e16-8a7a81ff340e.png)

2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by svipben** [comment]
It may happen if you have a lot of files in your project and you need to exclude them for e.g. for JavaScript `node_modules`, `bower_components`, tmp files, cache, etc.

**Comment by roblourens** [comment]
Please include as many details as possible. Did you just open a project? How long was `rg.exe` using lots of CPU? Does it occur with extensions disabled?
