### ISSUE TITLE
Wrong Import in Auto Import 

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#42794]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
material-icon-theme|PKi|3.2.2
ionic3-vs-ionView-snippets|dan|1.0.1
gitlens|eam|7.5.10

(2 theme extensions excluded)

---

Steps to Reproduce: Screen Shots added ⏬
<img width="794" alt="screen shot 2018-02-02 at 12 31 29 pm" src="https://user-images.githubusercontent.com/10536234/35720752-08333740-0815-11e8-8ad9-b0c4cd70b98b.png">
<img width="592" alt="screen shot 2018-02-02 at 12 31 58 pm" src="https://user-images.githubusercontent.com/10536234/35720759-179096ec-0815-11e8-99b3-e76f353f2ad6.png">

output
<img width="344" alt="screen shot 2018-02-02 at 12 32 21 pm" src="https://user-images.githubusercontent.com/10536234/35720776-2637125c-0815-11e8-93b3-43bc0388d57e.png">

But after removing this auto-imported suggestion and clicking on the bubble again it shows the right path to import

<img width="475" alt="screen shot 2018-02-02 at 12 36 14 pm" src="https://user-images.githubusercontent.com/10536234/35720904-b05ec01a-0815-11e8-924d-d7c75149edd2.png">

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Can you please try this in [vscode insiders](https://code.visualstudio.com/insiders/). We've made a lot of fixes to auto-imports and I believe this may already have been addressed

**Comment by prasanthnv** [comment]
I think the problem is fixed in vscode insiders.
