### ISSUE TITLE
VS Code as Git editor with --wait option doesn't let me edit interactive rebase file

### ISSUE THREAD

**Issue by WouterDeKort** [Microsoft/vscode#42806]
- VSCode Version: 1.19.3
- OS Version: Windows 10 1703

Steps to Reproduce:

1. git config --global core.editor "code --wait"
2. git rebase HEAD~3 -i

Does this issue occur when all extensions are disabled?: Yes

I've setup VS Code as the global editor for Git on my Windows 10 pc like this:

`git config --global core.editor "code --wait"
`If I now run something like `git rebase HEAD~3 -i`, after a long wait VS Code is launched and I see that it opens a tab named `git-rebase-todo` but before I can do (or see) anything the tab is closed and the command line thinks the rebase is finished by showing something like

`Successfully rebased and updated refs/heads/Maintenance.`

I see this behavior when using both PowerShell and the regular Console.

This is the content of my global git config file:

```
[user]
    name = Wouter de Kort
    email = ...
[winUpdater]
    recentlySeenVersion = 2.15.1.windows.2
[core]
    editor = code --wait
[diff]
    tool = default-difftool
[difftool "default-difftool"]
    cmd = code --wait --diff $LOCAL $REMOTE
```
I thought that adding the `--wait` flag was all I had to do. Any idea why Code is opening and closing the rebase file in one go?

**Comment by bpasero** [comment]
@WouterDeKort does it help if you configure `"workbench.editor.closeOnFileDelete": false`?

**Comment by WouterDeKort** [comment]
@bpasero It's strange but I can't reproduce the issue. The rebase now opens Code for the actual rebase and for entering a new commit message. I have no idea what has changed over the weekend.
