### ISSUE TITLE
cannot read property 'toCommandArgument' 

### ISSUE THREAD

**Issue by mfathy99** [Microsoft/vscode#42802]
i am trying to add key-binding to the (**run python file in terminal**) command but i am getting this error
**cannot read property 'toCommandArgument of Undefined'**

**Comment by usernamehw** [comment]
For extensions file issues against corresponding repositories https://github.com/Microsoft/vscode-python

**Comment by mfathy99** [comment]
i' ve the same issue at moved to #https://github.com/Microsoft/vscode-python/issues/689

**Comment by usernamehw** [comment]
Then you should probably close this one.

**Comment by listentojohan** [comment]
Still an issue with latest release 1.21.0
