### ISSUE TITLE
Search exclude does not work correctly

### ISSUE THREAD

**Issue by pantonis** [Microsoft/vscode#42800]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 1.19.3
2. Windows 10

Does this issue occur when all extensions are disabled?: Yes

When I search for something, vs code searched into node_modules
Below is my settings.json

```
{
    "files.exclude": {
        "**/node_modules": true,
        "**/.git": true,
        "**/.DS_Store": true,
        "**/*.js.map": true,
        "**/*.js": {
            "when": "$(basename).ts"
        }
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
    },
    "window.zoomLevel": 0,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "extensions.ignoreRecommendations": true,
    "explorer.confirmDragAndDrop": false
}
```

**Comment by roblourens** [comment]
Are those files in node_modules open?

**Comment by pantonis** [comment]
No

**Comment by roblourens** [comment]
Can you show the output of the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by pantonis** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/3295086/35749660-fa6af044-085a-11e8-80d0-1063cf2bbfb2.png)

**Comment by roblourens** [comment]
Those excludes are not being applied. Is the "Use excludes" button enabled?

![image](https://user-images.githubusercontent.com/323878/35752446-e01ea914-0810-11e8-8d1e-9877a751c5ca.png)

**Comment by pantonis** [comment]
Thanks for the help.

Didn't know that I had to press the button to exclude. In my opinion when you specify the exclude files and paths in settings you should not be pressing a button to make it work.

Thanks again

**Comment by roblourens** [comment]
The button is enabled by default. You probably clicked it at some point.
