### ISSUE TITLE
[Localization] Default settings file contents for the intalled extensions are not localized.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4280]
- VSCode Version:0.10.12-alpha
- OS Version: WIndows10

Steps to Reproduce:
1. Launch app with any supported locale. >Code-alpha --locale=ko
2. Go to File->Preference->Workspace settings
3. Verify default setting contents.
4. Install any recommended extension by clicking on extension info icon from the status bar. In my case I installed for GO.
5. Once extension is installed successful then click on restart window button from pop-up.
6. Perform step 2-3 again.
Actual:
I verified under default setting file new entry added for extension but Commented text are not localized.
I verified with  GO, Powershell, TSLint  extensions. 
![image](https://cloud.githubusercontent.com/assets/17735796/13794845/50d1049c-eabb-11e5-9b0e-a019fb93c92d.png)

Expected : All the commented text under default settings should be localized after reload as this is read only file.

**Comment by dbaeumer** [comment]
@isidorn Please ensure that propert localized. If so feel free to close.

**Comment by isidorn** [comment]
This is an issue with the go extension - I have moved this bug there
https://github.com/Microsoft/vscode-go/issues/248

**Comment by dbaeumer** [comment]
Thanks.

**Comment by jasonyueyang** [comment]
@isidorn: Does this issue apply to all extensions or is it specific to the Go extension?

**Comment by isidorn** [comment]
@jasonyueyang well all extensions need to be externalizied, while this issue is specific for the go extensions, since that extension contributes these settings
