### ISSUE TITLE
Issue reporter: align labels with radios

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42805]
Have a look at how I do it in the feedback dialog:

![image](https://user-images.githubusercontent.com/900690/35726613-c89826ae-0805-11e8-9dce-d1bd0cb26bce.png)

Suggest to use `display: flex` to align them properly:

![image](https://user-images.githubusercontent.com/900690/35726631-d54ed384-0805-11e8-99c0-783db9acc372.png)

**Comment by RMacfarlane** [comment]
Fixed as part of 0c7afa823e90f84559214176676b37d13022458a
