### ISSUE TITLE
unclear meaning of sentence

### ISSUE THREAD

**Issue by aldonetti** [Microsoft/vscode#42807]
seems the string is incomplete and unclear
in https://github.com/Microsoft/vscode/blob/2d4b6e912412437c2b0b7e70e634b819627d7e21/extensions/git/package.nls.json
it's this
"config.inputValidation": "Controls when **to show input validation the input counter**.",
what does it mean please? translators are wondering 
thanks!!
@agriffard - FYI

**Comment by usernamehw** [comment]
![scm_input_validation](https://user-images.githubusercontent.com/9638156/35728345-56d2ca80-081c-11e8-9ff8-1c8f7cfb2123.png)

**Comment by joaomoreno** [comment]
Pushed a fix: https://github.com/Microsoft/vscode/commit/ec218b9088a13047ec20b32b4259d600ff28d855

**Comment by octref** [comment]
I verify this is sensible English.
