### ISSUE TITLE
Extra black space on top window after computer idle (display sleep) in os x

### ISSUE THREAD

**Issue by jon-at-work** [Microsoft/vscode#42817]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
vscode-sort|hen|0.2.5
yang|mar|0.1.3
python|ms-|2018.1.0
debugger-for-chrome|msj|4.1.0
gitblame|wad|2.2.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:
I have a three displays in total, the screenshot if from one of the external displays. The problem is intermittent.

0. Run Visual Studio Code in fullscreen.
1. Sleep or turn off displays. E.g leave computer idle.
2. Turn on screens.

See attached screen dump, the problem is the extra size on top.
<img width="1280" alt="screen shot 2018-02-02 at 11 59 55" src="https://user-images.githubusercontent.com/33722263/35730118-2da26dec-0811-11e8-981a-67afa801116b.png">

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Does it reproduce if you run "code --disable-gpu"?
