### ISSUE TITLE
Improve throttling of remote searches

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42814]
Improve throttling of remote searches:

From @roblourens [here](https://github.com/Microsoft/vscode/issues/42741#issuecomment-362424792)

I debugged some and realized that I'm doing something slightly wrong, in that the remote search is debounced, but each new search waits on the old one to complete. It should actually fire immediately and cancel the previous search if it has not completed yet. I didn't realize that the ThrottledDelayer is queuing the promises, makes sense though.

I have a change to make the ThrottledDelayer simply not wait on the search to complete. But, I don't think I want to check it in now because the impact isn't that bad, with the remote search timeout. And it isn't noticeable under normal network conditions. The change is here: 0dbb7a0

**Comment by roblourens** [comment]
I actually don't think there's a problem here.

For some reason I thought earlier that it would be possible for an infinite number of requests to queue up, if the user keeps typing just slower than the debounce. But that's not true. The current behavior is correct as far as I can tell.
