### ISSUE TITLE
Prettify large file - close without saving it - crash

### ISSUE THREAD

**Issue by nanoteilchen** [Microsoft/vscode#42816]
The editor hangs, when big files are closed with unssafed changes and without saving them.

Steps to Reproduce:
1. Open "big" Json-File (mine is actually only 317kb, but everything on one line)
2. Prettify it. Now it has about 120'000 rows
3. Close the file **without** saving it
4. Editor hangs/crashes. It takes a few minutes until the file is closed

Using newest version on a mac.

**Comment by rebornix** [comment]
Is it possible that you can provide the file that crashes on your machine? And when you say *Close the file without saving it*, do you mean:

* Close the file by commands or click
* A window pops up, asks if you want to Save or not
* You click on *Dont' save* ?

**Comment by rebornix** [comment]
Let's track it in https://github.com/Microsoft/vscode/issues/41184
