### ISSUE TITLE
[Localization] Setting.json file usage text (comments) didn't change when user changing the locale.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4281]
- VSCode Version:
- OS Version:0.10.12-alpha

Steps to Reproduce:

1. Launch app with any targeted locale from command prompt > code-alpha --locale=ko
2. Navigate to File->Preference->Workspace settings.
3. It will launch both default setting and settings.json file.
4. Verify commented text under both the files and should match with target locale.
5. Close app and re-launch with different local or with default locale (EN) from cmd prompt > code-alpha
6. Repeat action from 2-4

Actual: Setting.json file usage text didn't change when user changed the locale.
![image](https://cloud.githubusercontent.com/assets/17735796/13795397/c205c826-eabd-11e5-8fa4-d53cf3ecc45c.png)

Expected: When application re-launch with targeted local then usage text (comments) should be localized.

**Comment by bpasero** [comment]
As designed, the file is being created and saved once.
