### ISSUE TITLE
Refresh folders

### ISSUE THREAD

**Issue by VladReznik** [Microsoft/vscode#42810]
If I reinstall modules in folder npm_modules explorer in VS code is not refresh project folder...so I dont see new folders in npm_modules...Always needed to close and open VS code to see new folders..fix it pls :)

**Comment by usernamehw** [comment]
![refresh](https://user-images.githubusercontent.com/9638156/35730124-f92b1dd2-0821-11e8-9fc1-ac471805a3b7.png)

**Comment by VladReznik** [comment]
Thanks for this...but I must click every time. Anyway thanks

**Comment by Dominik-K** [comment]
@VladReznik You can [create a keyboard shortcut to refresh the explorer](https://github.com/Microsoft/vscode/issues/28432#issuecomment-361998975).

duplicates #28432

**Comment by bpasero** [comment]
This is because we ignore changes in `node_modules` folder. To lift this, you can change the `files.watcherExclude` setting to not ignore this folder.
