### ISSUE TITLE
findnextselection shortcut doesn't work

### ISSUE THREAD

**Issue by kcris** [Microsoft/vscode#42811]
- VSCode Version:1.19.3
- OS Version: linux, x64

Steps to Reproduce:

1. select some text
2. press Ctrl-F3

next occurence for the selected text is not found
ps: it is found if I first press Ctrl-F, then press Ctrl-F3

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
I can't reproduce this issue in latest version, can you please give it another try?

**Comment by kcris** [comment]
Hi, I just tried again using vscode 1.27.1 (kubuntu 18.04 lts, 64 bit).
Problem persists. Ctrl-F3 does not search at all.
Having the Search overlay opened or not, does not make any difference.

Using Ctrl-F then F3 works.

**Comment by rebornix** [comment]
@kcris thanks! I'll play with Ubuntu (or probably kubuntu) to see if I can reproduce. Thanks for your feedback!

**Comment by rebornix** [comment]
It seems that Ctrl+F3 is a global shortcut for switching desktops https://docs.kde.org/trunk5/en/applications/fundamentals/kbd.html , it's probably why it's not working in VSCode. @kcris can you confirm that?

**Comment by kcris** [comment]
Hi, yes, I confirm. 
Sorry, I was not aware of that before (I only had one virtual desktop).
