### ISSUE TITLE
color picker auto hide

### ISSUE THREAD

**Issue by GaryChangCN** [Microsoft/vscode#42818]
- VSCode Version: 1.19.3
- OS Version: macos 10.13.2

Steps to Reproduce:

1. Split editor for two
2. enter user setting page
3. open color picker
4. color picker will hide when cursor move to red box which marked in the following picture

![image](https://user-images.githubusercontent.com/12539978/35730696-0288006c-084e-11e8-915f-beff364bd634.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by GaryChangCN** [comment]
![imb_qutdgr](https://user-images.githubusercontent.com/12539978/35731670-89914a2a-0851-11e8-832a-5d94f1a7f67d.GIF)

**Comment by wyckster** [comment]
I can confirm this happens in Windows too, version 1.22.2 x64.

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/36195 and thanks for your feedback.
