### ISSUE TITLE
Search: show list of excluded files, when checkbox is checked

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#42813]
What happened to the list of exclusions displayed in the Search viewlet?

<img width="751" alt="screen shot 2018-02-02 at 11 27 09" src="https://user-images.githubusercontent.com/22350/35728500-0e008122-080c-11e8-9caf-e4346acad881.png">

It is very hard to understand what is going wrong with my search. It took me wayyyyy too long to figure out I needed these two things in my workspace settings, in order to find stuff in `node_modules`:

```
    "search.exclude": {
        "**/node_modules": false
    },
    "search.useIgnoreFiles": false
```

We used to list the exclusion in the textbox... that would at least tell me that node_modules were being excluded. Without that I'm just trying stuff in the dark.

**Comment by roblourens** [comment]
That's been gone for awhile. I thought it added more noise than useful info, especially for multiroot workspaces. Next time I recommend using the toggle button on the right side of the excludes box, rather than editing your settings for one search. Does that help?

**Comment by joaomoreno** [comment]
I used the toggle button a few times and, even worse than not getting what I wanted, I felt in the dark as to what the button actually does. And I use the product every day. We need some affordance relative the button's enablement with its consequences.

**Comment by roblourens** [comment]
When you toggle off the button, it still doesn't show results in node_modules? Works for me, what query did you try?

Can you set the log level to trace, run the search again, and paste the log from the renderer?

**Comment by joaomoreno** [comment]
Doesn't reproduce, I don't remember what setup I was in...
