### ISSUE TITLE
"TextEditor is disposed" spam in debug console

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#42827]
This was believed to be fixed in #32408/#30578 however I'm still seeing it:

<img width="1137" alt="screen shot 2018-02-02 at 14 38 21" src="https://user-images.githubusercontent.com/1078012/35738449-dfc915f6-0826-11e8-8efa-f0c3f62e02a7.png">

I'm not sure how to get a stack or something to confirm that it's still coming from decorations (though I suspect so), so let me know if there's a way to get more info about it.

**Comment by DanTup** [comment]
Oh, btw, this was appearing as I was tabbing between documents. When a document becomes visible I send off an async request to get some data and then build decorations when it completes. I believe these came from me tabbing away from the doc during the decorations being built.

**Comment by alexandrudima** [comment]
I have found the place that warns. This looks like a good warning which we don't want to remove. Your extension is doing something wrong.

i.e. I believe you are using some code pattern like the following:
```ts
let editor = vscode.window.activeTextEditor;
let expensiveResult = await computeSomethingOrFetchFromServerAsync(editor.document.uri);
// At this point `editor` could have been disposed in the meantime,
// by the user closing it, or by switching to another editor, etc.
editor.setDecorations(type, expensiveResult.decorations)
```

The problem is that by the time the `expensiveResult` is computed, the `editor` you have captured in your closure can no longer exist / can be disposed. So, on return from an async computation, the code should check if the `activeTextEditor` is still the one it computed something for...

```ts
if (!vscode.window.activeTextEditor) { return; } // Possible when all editors are closed
const uri = vscode.window.activeTextEditor.document.uri;
let expensiveResult = await computeSomethingOrFetchFromServerAsync(uri);
// At this point `editor` could have been disposed in the meantime,
// by the user closing it, or by switching to another editor, etc.
if (!vscode.window.activeTextEditor) { return; } // Possible when all editors are closed
if (vscode.window.activeTextEditor.uri.toString() !== uri.toString()) {
  // the computation was so slow, that the user had time to switch or close the editor
  return;
}
vscode.window.activeTextEditor.setDecorations(type, expensiveResult.decorations)
```

**Comment by DanTup** [comment]
@alexandrudima Thanks for the info! I did spot that there was a case where we might do this (we track the active editor, but didn't null it out when it moved to something we don't draw decorations for). I changed https://github.com/Dart-Code/Dart-Code/commit/d05b27f3621b3bf638ba57d57a35bbd71e9440ae and have been unable to repro.

Thanks!
