### ISSUE TITLE
intellisence for typescript doesnt work for imports

### ISSUE THREAD

**Issue by dankrz** [Microsoft/vscode#42828]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.5
jsrefactor|cms|2.11.4
vscode-great-icons|emm|2.1.24
easy-icons|jam|0.3.1
team|ms-|1.122.0
debugger-for-chrome|msj|4.1.0
material-icon-theme|PKi|3.2.2
csharp2ts|raf|0.0.21
vscode-icons|rob|7.19.0
javascript-typescript|sou|0.0.5
autoimport|ste|1.5.3
move-ts|str|1.7.2
ayu|tea|0.12.0

(5 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please provide steps to reproduce the problem + example code
