### ISSUE TITLE
Open Editors: "Open to Side" does not work in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42823]
Steps to Reproduce:

1. have 3 groups open
2. click on an editor in group 3
3. right click on an editor in group 2 and pick "open to side"

=> does not work

**Comment by isidorn** [comment]
This works for me.
Can you still reproduce in latest. And if yes what are you doing differently than me in this gif

![opentoside](https://user-images.githubusercontent.com/1926584/35907264-af0896c4-0bed-11e8-912b-8d6a5e73dbf9.gif)

**Comment by bpasero** [comment]
@isidorn the file is not active, check: ![flicker_chrome58](https://user-images.githubusercontent.com/900690/35910616-7ce4f05c-0bf7-11e8-8f02-6a265d5860b8.gif)

**Comment by isidorn** [comment]
@bpasero I can repro now.
The command nicely calls into the `editorService`
It seems that the issue is on the `editorService` side, can you look into it?

![screen shot 2018-02-07 at 12 34 08](https://user-images.githubusercontent.com/1926584/35914359-453b3bdc-0c03-11e8-9608-817c756f339c.png)

**Comment by bpasero** [comment]
@isidorn I see the issue and now I am not so sure anymore if this should be fixed or not, depends on how you look at it: the "open to side" command is always relative to the currently active editor and not to the selection in the "open editors" view. For example this seems to work nicely:
* 2 groups opened
* second group has an editor active and focused
* right click on an editor in first group and pick "open to side"
* editor opens to the side of the active editor

I think we can leave this as is given it is not a regression.

**Comment by isidorn** [comment]
@bpasero makes sense that the editor service is not aware of the open editor selection state.
Let's leave it like it is until somebody actually complains.
