### ISSUE TITLE
Some environment variables not passed into the configured shell task

### ISSUE THREAD

**Issue by imonmyown** [Microsoft/vscode#42829]
- VSCode Version: Code - OSS 1.19.3 (554a9c6dcd8b0636ace6f1c64e13e12adf0fcd1d, 2018-01-27T23:06:58.321Z)
- OS Version: Linux x64 4.14.15-1-rt12-MANJARO
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
crystal-lang|fau|0.3.9
auto-comment-blocks|kev|1.0.1
vscode-emacs-friendly|lfs|0.8.2
(1 theme extensions excluded)
---

In particular my shell env didn't have LIBRARY_PATH and LD_LIBRARY_PATH in it.

Steps to Reproduce:

1. set an environment variable in the shell you use (I used bash)
2. configure a shell task (in tasks.json) with a single `env` command
3. check the output of the task for the env variable you set on step 1.

Reproduces without extensions: No

**Comment by rbaprado** [comment]
I also seem to face this problem. My tasks.json:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "cargo run",
            "command": "cargo",
            "args": [
                "run"
            ],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            "problemMatcher": [
                "$rustc"
            ],
            "options": {
                "env": {
                    "RUST_LOG": "info",
                    "MOBTAG_STATIC_PATH": "/home/buzz/Projetos/MobTag/Code/backend/public"
                }
            }
        }
    ]
}
```
My application cannot see neither RUST_LOG nor MOBTAG_STATIC_PATH

**Comment by dbaeumer** [comment]
Dups #42822
