### ISSUE TITLE
Renderer freezes after opening 2GB or larger files

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#42839]
- VSCode Version: Stable/Insiders
- OS Version: macOS

Steps to Reproduce:

1. Open a 1.5GB file (with Line Model or Piece Tree)
2. It opens successfully (say the machine has enough memory)
3. Open a 2.1 GB file
4. It freezes after 1+ mins.

As we load the whole file to memory, it exceeds the memory limit of v8 process. We can expose `max_old_space_size ` flag in cli then users can increase the limit themselves.

**Comment by rebornix** [comment]
@bpasero correct me if I'm wrong, but it seems that when we run `Code --js-flags="abc"`, `js-flags` is not passed to the renderer process so we need to explicitly have this option in cli.

**Comment by bpasero** [comment]
@rebornix it should be passed on to the renderer, e.g. when I add `--js-flags=harmony` I see how that flag is passed on to the renderer when I check with `ps aux`. See also https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md
