### ISSUE TITLE
No tabs: Close button closes wrong editor

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42830]
### Issue Type
Bug

### Description

- `"editor.showTabs": false`
- open two editors side by side
- focus left editor
- click on close button of right editor
-> left editor closes

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (7636a7d6f7d2749833f783e94fd3d48d6a1791cb, 2018-02-02T11:14:28.251Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir tmp/user --extensions-dir tmp/ext|
|Screen Reader|no|
|VM|20%|

</details>Extensions: none
Reproduces without extensions

**Comment by isidorn** [comment]
I have cherry picked the fix on top of the release branch.
I have also checked that the close works fine across diferent areas: command palette, open editors, tabs view title, no tabs view title.
@bpasero can you also please verify these areas with the latest fix. Thanks
