### ISSUE TITLE
[Localization] Configure file associations to languagues setting not localized

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4283]
- VSCode Version: 0.10.12-alpha --locale=fr (or any locale)
- OS Version: Windows 10

Steps to Reproduce:

1. Launch VS Code from command prompt with --locale=fr
2. Open workspace settings file
3. Scroll to line 123

Actual:
Non-localized setting for Configure file associations
![localizefileassociations](https://cloud.githubusercontent.com/assets/12900364/13796741/a143d760-eac5-11e5-9b16-26b09ad001d3.JPG)

Expected:
Localized setting text. It is bracketed in --locale=pseudo with double vowels.

**Comment by bpasero** [comment]
@vsccarl please test with PSEUDO, those strings are not localized yet.

**Comment by vsccarl** [comment]
@bpasero I saw before that in PSEUDO mode, bracketed and double vowel strings should be translated.
Here it is in PSEDUO:
![configfileassocpseudo](https://cloud.githubusercontent.com/assets/12900364/13821965/1f4c7ed2-eb61-11e5-8571-7f7b8a252433.JPG)
