### ISSUE TITLE
VSCode Icon Color too Close to VS17

### ISSUE THREAD

**Issue by mseyma** [Microsoft/vscode#42836]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1

---

Steps to Reproduce:
The icon color for VSCode is too close to visual studio 17 which is causing me grief (I'm color blind). Are there any plans to change the icon color for VSCode so that it's more distinguishable from VS17?

**Comment by siegebell** [comment]
Let's give them a rest before trying to change the icon again...
1. [New VS Code icon is ugly! (#35783)](https://github.com/Microsoft/vscode/issues/35783)
2. [The Icon Journey](https://code.visualstudio.com/blogs/2017/10/24/theicon)
