### ISSUE TITLE
Changed UI (again) with no mention in release notes

### ISSUE THREAD

**Issue by designermonkey** [Microsoft/vscode#42834]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.5
phpunit|ema|2.1.1
php-debug|fel|1.12.1
composer|ika|0.7.1
vs-code-phpunit-snippets|jam|0.0.2
php-docblocker|nei|1.3.3
java|red|0.18.1
open-in-browser|tec|1.1.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.2.0

(2 theme extensions excluded)

---

So, again the UI has changed without mention that I can find in the release notes. I know this could be put down to me just having a moan, but programmers really use syntax highlighting, code colouring, and text form to easily scan over files quickly to see what is right or wrong...

...and you have changed it again.

I'd like to know why this keeps happening? Of course I will have to get used to it (again), it is really irritating me that I have to spend time reading code more deeply for a couple of weeks to get used to the new highlighting (and now the use of italics!!)

**Comment by aeschli** [comment]
@designermonkey Can you be more specific what has changed? 
What file types? What theme do you use?

**Comment by Vuneu** [comment]
@aeschli I'm not sure if this is what @designermonkey means, but I just noticed a lot of the syntax highlighting from my Ruby files has disappeared, for comparison:

![image](https://user-images.githubusercontent.com/8165068/36049859-ee683262-0da9-11e8-9a17-4da0906e6208.png)
This screenshot is from ~5 months ago.

![image](https://user-images.githubusercontent.com/8165068/36050095-bb3b8f3c-0daa-11e8-8d83-053fd61323c5.png)

This is from the latest version.

The theme I'm using is [Atom One Dark](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark), but the default Dark+ looks pretty much the same:

![image](https://user-images.githubusercontent.com/8165068/36050053-93fb9a98-0daa-11e8-84f8-6fc4c2d21fbe.png)

**Comment by aeschli** [comment]
@Vuneu We use the Ruby grammar from https://github.com/textmate/ruby.tmbundle/commits/master/Syntaxes/Ruby.plist and there hasn't been any change since August 2017. I reverted back to the state in 2016 and it looks the same. Did you maybe use an extension that replaced the Ruby grammar?

**Comment by Vuneu** [comment]
@aeschli As I mentioned on my ealier edit, it's an issue with an extension, rather than a VSCode issue.

**Comment by aeschli** [comment]
@designermonkey Can you be more specific what has changed?

**Comment by designermonkey** [comment]
Sorry for the delay.

I can't be specific about it, as I can no longer see an older version for reference. I have since learned about how colour schemes work, but I know that the scheme I was using had not changed or updated, so somehow the mappings of colours to contexts has changed. A lot less colouring is apparent in contexts throughout the themes I use (Base16 themes).

As @Vuneu has shown, there is a lot less highlighting going on in the Base16 themes too. I use PHP primarily, but wouldn't know about extensions, as I don't have any syntax highlighting extensions installed.

**Comment by aeschli** [comment]
The PHP grammar has had updates, so it's likely what has caused the changes. We use the grammar from https://github.com/atom/language-php and trust that they make reasonable changes in order to fix bugs and issues. 
If you have a concrete example where things got worse, then we can dig deeper and see if the grammar regressed, or if the theme you use makes assumptions that it shouldn't make.

**Comment by aeschli** [comment]
Closing for now, I'd be happy to reopen if you have an example to look at.

**Comment by designermonkey** [comment]
If it's a reasonable upgrade, then it's an extension issue to upgrade the use of the grammar. Thanks for feedback; it would be helpful to developers to mention these things in release notes though!
