### ISSUE TITLE
Shorcut for selecting all selections?

### ISSUE THREAD

**Issue by serjyamp** [Microsoft/vscode#42832]
Sublime Text has a great feature Alt + F3 which allows to select all equal parts of text (selected using Ctrl + D).
Where to find Alt+F3 in VSCode?

**Comment by usernamehw** [comment]
https://stackoverflow.com/questions/46539714/select-all-occurrences-of-selected-word-in-vscode

**Comment by alexandrudima** [comment]
Our action is called "Select All Occurrences of Find Match" and is bound by default to ctrl+shift+L.
