### ISSUE TITLE
Add "Suggestions and Fixes" service for errors (like is VS Studio)

### ISSUE THREAD

**Issue by Stargor14** [Microsoft/vscode#42849]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Already implemented I believe as [`code actions`](https://code.visualstudio.com/docs/editor/editingevolved#_code-action) using the lightbulb ui
