### ISSUE TITLE
Node intellisense is not working

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#4284]
- VSCode Version: 0.10.12-alpha
- OS Version: OS X El Capitan 10.11.1

Steps to Reproduce:

I followed the instructions in this [doc](http://code.visualstudio.com/docs/runtimes/nodejs) and can't get intellisense to work. These are the steps I took. 

1. `npm install -g typings`
2. `typings install node express --ambient`
3. Confirmed that the typing files were added
4. Created a `jsconfig.json` file and added the contents as instructed [here](http://code.visualstudio.com/docs/runtimes/nodejs#_adding-a-jsconfigjson-configuration-file). 
5. <kbd>ctrl+space</kbd> after a variable or object, expecting to see intellisense. 

![image](https://cloud.githubusercontent.com/assets/2449568/13796901/c746856a-eac6-11e5-916c-43bca9bcabdb.png)

**Comment by egamma** [comment]
Cannot reproduce 

![image](https://cloud.githubusercontent.com/assets/172399/13813626/d81eaf4a-eb82-11e5-9df5-b4636f297f62.png)

Can you try whether 'Reload JavaScript' help?

**Comment by waderyan** [comment]
Hmm... I tried `Reload Javascript` but didn't work. 

I tried installing `typings install lodash --ambient`. Same issue. 

![image](https://cloud.githubusercontent.com/assets/2449568/13823026/2f6e5674-eb65-11e5-82b6-5ab7e474502d.png)

**Comment by egamma** [comment]
Could it by that your tsdk setting points to an older version of TypeScript?

**Comment by waderyan** [comment]
Not sure. I'm on 1.9.  

```
tsc --version
Version 1.9.0-dev.20160130
```

**Comment by egamma** [comment]
Can you check whether you have tsdk  defined in your user settings. This was required to enable Salsa in January.

Notice the commandline tsc version has nothing to do with this. Code ships with a version of tsc.

**Comment by waderyan** [comment]
After removing `"typescript.tsdk"` from my settings this was resolved.

**Comment by egamma** [comment]
@waderyan mentioned to remove the typescript.tsdk in the March release noes.
