### ISSUE TITLE
CSS syntax coloring fails for 'justify-items' property, missing scope.

### ISSUE THREAD

**Issue by patoezequiel** [Microsoft/vscode#42843]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
csharp|ms-|1.13.1
vscode-icons|rob|7.19.0

---

> Update 1: The same problem happens with the `justify-self` CSS property.

## Steps to Reproduce:

1. Write a `justify-items` property on any selector of a CSS file, for instance:

```
div {
    justify-items: stretch;
}
```

2. Verify that the property name `justify-items` is not being colored colored like a property name.

3. Verify using the TM scope inspector that, unlike other CSS property names, the token for `justify-items` doesn't have the **support.type.property-name.css** scope.

![screenshot_3](https://user-images.githubusercontent.com/5291103/35750876-3e5d245a-0835-11e8-9771-e60293daa829.png)
![screenshot_4](https://user-images.githubusercontent.com/5291103/35750880-3ebdb23e-0835-11e8-803f-458b86fecfff.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to atom/language-css#137
