### ISSUE TITLE
Focus next/previous search result

### ISSUE THREAD

**Issue by salc** [Microsoft/vscode#42842]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
goto-documentation|cxf|0.0.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
mark-as-excluded|jcm|0.2.5
gitignore|mic|1.0.1
vscode-hexdump|sle|1.6.0
html-css-class-completion|Zig|1.16.1

---

Steps to Reproduce:

1. Ctrl+shift+F to make a full project search for something that is in the project more than once, for example the letter "a".
2. Once the results come out, click on first result row so that the file containing the result will open in the editor.
3. put the mouse pointer before the selected word in the editor and then press key "canc" to delete it. To here, all normal.
4. now, move to the next result line of the search left panel by pressing key F4.
5. again, put the mouse pointer before the selected word in the editor and then press key "canc" to delete it. The selected word doesn't get deleted but instead a result row of the search gets removed. This is because the search panel keeps focus even if I clicked inside the editor to place the cursor.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Not sure what "canc" is, do you mean backspace or delete?

> This is because the search panel keeps focus even if I clicked inside the editor to place the cursor.

This works for me. Do all keys (arrow keys, letters, etc) only go to the viewlet, even after clicking in the editor? Can you try in the Insiders build?

**Comment by salc** [comment]
sorry, you're right, i have a damn italian keyboard. Its the delete key.

**Comment by salc** [comment]
if you first press arrow keys and then delete, the editor will catch focus again and the delete key will work.
So you just have to click into the editor to position cursor before the selected word and then press delete.

**Comment by roblourens** [comment]
I guess I don't understand the problem. Pressing F4 or clicking in the editor should give focus to the editor.

**Comment by salc** [comment]
F4 moves to the next result inside the search panel and automatically points to the word inside the editor. Now you can see the cursor blinking inside the editor after the selection. So the focus should be in the editor, but if you press the delete key, the keystroke still go to the search panel and not where the cursor is. What i'm saying is that F4 keeps focus in the search panel unless you move cursor inside the editor.

**Comment by roblourens** [comment]
I can repro after all. The condition on the keybinding to delete the item is probably wrong. Thanks.
