### ISSUE TITLE
additional event info in quick pick (showQuickPick)

### ISSUE THREAD

**Issue by tnrich** [Microsoft/vscode#42841]
Hey there,

I was hoping to listen for the "cmd" key being held down while a user selects a quickPick option.

Right now, I believe the event being returned is just the item, but maybe the api could be extended to also include the underlying event that triggered the click.

Is there any interest in supporting this? 

Thanks!

cc @tgreen7

**Comment by jrieken** [comment]
Very unlikely that we will expose low-level'ish information like keyboard events et al. What is it you are trying to achieve? Some sort of alternative command similar to the cmd+click in open file?

**Comment by tnrich** [comment]
@jrieken like I said above I'd like to trigger different user flows depending on if the user is holding down a certain key while selecting a given quick pick option. In my particular case I want to listen to the Cmd/Ctrl key :) 

Does that make sense?
