### ISSUE TITLE
$10 in bash does not get colorized correctly

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#42845]
<img width="265" alt="screen shot 2018-02-02 at 11 42 22 am" src="https://user-images.githubusercontent.com/2193314/35751683-39c13cdc-080e-11e8-9d5f-f752bf657da7.png">

```sh
echo '10:'$9
echo '10:'$10
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#102
