### ISSUE TITLE
Clicking into editor sometimes causes search bar to fire

### ISSUE THREAD

**Issue by jdatskuid** [Microsoft/vscode#42852]
### Issue Type
Bug

### Description

I've not been able to figure out how to consistently reproduce this issue, though I see it frequently throughout my day. This often occurs when I've left VS Code for some time, working in the browser for example, and then click into one of my editors (my window is typically split into 2 or 3 vertical editor panels). When I click into the editor, the search suddenly fires, causing my editor to jump to a totally different position then what was visible when I clicked (and causes me to lose the location where I was previously working).

So far it keeps catching me by surprise, so I'm not 100% sure yet, but I think that any search in any panel applies. So even if the editor I'm clicking into had no search bar visible, it will suddenly perform a search, copying the search term either from another editor or from global search.

If I can find a more definite pattern, I'll update. Just wanted to get this out there because it's kind of infuriating to lose my position in a file with 1000's of lines when jumping back and forth between the browser and VS Code.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (eed7e193125f3d4cfebe2089d1b2a9c674388754, 2018-01-30T09:40:57.870Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.78GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_167977|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
apex|Joh|0.0.2
ForceCode|Joh|0.5.35
visualforce|Joh|1.0.2
vscode-eslint|dba|1.4.5
gitlens|eam|7.5.10
python|ms-|2018.1.0
debugger-for-chrome|msj|4.1.0

</details>
Reproduces only with extensions

**Comment by jdatskuid** [comment]
I figured out the repro steps. This is related to issue #42724.

Steps to repro:

1. Open a file (FILE_1).
2. Open another file (FILE_2) in a split editor.
3. Return focus to FILE_1.
4. Search for a term (TERM_1).
5. Switch focus to FILE_2.
6. Search for a term (TERM_2).
7. Switch focus back to FILE_1 by clicking somewhere within the file's contents.

Expected behavior: cursor should appear where clicked within FILE_1.

Actual behavior: VS Code changes the search term in FILE_1's editor to TERM_2, which immediately initiates a search, causing focus to jump to the next occurrence of TERM_2 within FILE_1.

**Comment by alexandrudima** [comment]
I also found this behaviour so irritating and annoying that I had to disable it via `editor.find.globalFindClipboard: false`. @rebornix Can we please turn it off by default, it does not work at all with our UX where we have a find widget per editor.

My most annoying case is exactly the same one as @jdatskuid . I often have two editors opened side-by-side and I want to search for different things in the two editors. With this feature, it is impossible to do so.

**Comment by rebornix** [comment]
It's already turned off by default.
