### ISSUE TITLE
Provide a pacman repo

### ISSUE THREAD

**Issue by zzag** [Microsoft/vscode#42855]
It would be nice to have a Visual Studio Code pacman repo. Arch Linux-based distros aren't so rare. For example, at a given moment, Manjaro is the second popular distro on distrowatch. https://distrowatch.com/dwres.php?resource=popularity

Also, Sublime Text provides its own pacman repo: https://www.sublimetext.com/docs/3/linux_repositories.html#pacman

Packaging stuff for pacman is simple:
- create PKGBUILD file or update `pkgver` field
- build package by running `makepkg --clean --sign`
- update package database by running `repo-add path/to/repo.db.tar.gz path/to/vscode-package.pkg.tar.xz`

---

PS. Yes, I know there is `visual-studio-code-bin` package in AUR but I don't want to install the package because every time there is an update I should go check out PKGBUILD for malicious things.

**Comment by Tyriar** [comment]
We'll be shipping a snap package soon which will be the preferred way to install on all distros supported. The snapcraft team tells me that both Arch and Manjaro are now supported. https://github.com/Microsoft/vscode/issues/5458

**Comment by zzag** [comment]
Cool. Will you also ship insiders edition?

**Comment by Tyriar** [comment]
That's the plan 👍
