### ISSUE TITLE
Command handlers receive an empty object

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#42851]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Steps to Reproduce:
**(create an extension)**

1. Create a VS Code command
2. Register a command handler for the command
3. Invoke the command from a command palette, and nothing is passed into the command handler. When invoked from a file or tree context menu then the file uri is passed.
4. Add a keyboard shortcut to the above command
5. However if the command is invoked via a keyboard shortcut, then an empty `{}` object is passed into the command handler.

Is this by design, to pass an `empty object` into the command handler when commands are invoked via the keyboard shortcuts.

**Comment by joaomoreno** [comment]
@alexandrudima Instead of `[]`, I now get `[null]`, which I argue is still not ideal.

**Comment by alexandrudima** [comment]
Good catch @joaomoreno
