### ISSUE TITLE
Auto-imports don't work when using trigger characters

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42859]
- VSCode Version:
- OS Version:

**Steps to Reproduce:**
1. In a project:

`a.js`:
```js
export function foo() {}
```

`b.js`:
```js
fo
```

2. Trigger suggestions on `fo` in `b.js`
3. Select the auto import suggestion for `foo`.
4. Press `(` to accept completion

**Bug**
Auto import not added

**Comment by mjbvz** [comment]
Root cause seems to be that the workspaceedit we provide gets invalidated, possibly by the editor bracket completions

**Comment by mjbvz** [comment]
@jrieken Just confirmed that this is indeed the root cause. Sequence of behavior is:

1. User accept suggestion. This suggestion has a command registered on it
2.  The suggest controller processes the suggestion and invokes the command.
3. Bracket matching kicks in for the original suggestion insertion
3. The command form the suggestion is invoked in the TS extension. This command builds up a workspace edit.
4. The workspace edit is applied within the command. However the editor model has changed since the workspace edit was created, so the operation fails

Possible workaround would be to change to use `additionalTextEdits` instead of a command in TS (however we sometimes would still need the command)

**Comment by jrieken** [comment]
> *Note* that
		 * additional modifications to the current document should be described with the
		 * [additionalTextEdits](#CompletionItem.additionalTextEdits)-property.


Yeah, don't use a command to edit the text document... We should really work on migrating TypeScript away from such hacks
