### ISSUE TITLE
Adopt TS 2.7 for building VS Code

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42853]
Tracks using VS Code 2.7 to build vscode.

May require a few fixes in built-in extensions that use `"strict": true` since TS added a few more checks here

**Comment by mjbvz** [comment]
Blocked by https://github.com/palantir/tslint/issues/3711 Will push out to next iteration

**Comment by andy-ms** [comment]
@mjbvz I just did a fesh install in a vscode clone and don't see any tslint errors.
