### ISSUE TITLE
Folding is not working on Powershell functions

### ISSUE THREAD

**Issue by Satak** [Microsoft/vscode#4285]
0.10.11- VSCode Version:
windows 8.1 - OS Version:

Steps to Reproduce:

1. create powershell function
2. folding is not working for function if the content is not indented

**Comment by aeschli** [comment]
That's a known limitation of the currently implemented folding strategy which is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand functions, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
