### ISSUE TITLE
Issue Reporter: UX issues

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#42856]
### Issue Type
Bug

### Description

The issue reporter has several issues that we should address:
- When working is more than one display the issue reporter opens always on the primary display. If the workbench window is on the secondary display, this causes the issue reporter to be invisible.
- The issue reporter window is always on top of the workbench window. This is an issue on smaller displays.
- The issue reporter is slightly too large on initial layout. This causes the "Preview on GitHub" issue to be scrolled out of the viewport.
- We use a fwlink. This link is length restricted to a degree that makes the issue reporter hard to use.

### VS Code Info

VS Code version: code-oss-dev 1.21.0 (Commit unknown, Date unknown)
OS version: Darwin x64 16.7.0

Reproduces without extensions

**Comment by chrmarti** [comment]
Verified all except the links length issue for which I'll reopen #42603.
