### ISSUE TITLE
Difficult to search the "source control providers" list

### ISSUE THREAD

**Issue by BattleBas** [Microsoft/vscode#42850]
VSCode Version: Latest Insiders
OS Version: Windows 7 OS

Screenshot of issue:
![capture](https://user-images.githubusercontent.com/3441183/35756570-77d17398-0831-11e8-97dc-2e00a036c9b1.PNG)

It would be great to have the option to sort the source control providers alphabetically. Currently it is difficult to find a source control provider in a large list because there is no apparent order, sorting it alphabetically would help. 

I was imaging having a menu option available (3 dots) that you could click and then have an option show up stating "Order alphabetically". This could also be a configuration option instead which would be fine as well because I don't see a use case for having to quickly toggle the sorting option. Maybe something like "git.sortProviders": true.

Illustration of providing a menu option:
![example](https://user-images.githubusercontent.com/3441183/35757149-82d10f22-0833-11e8-9b65-12324c6b021e.PNG)

~thank you

**Comment by joaomoreno** [comment]
@BattleBas Is your issue with finding them, or with sorting them? For finding, I'd rather have some sort of filter feature other than changing the sort order.

**Comment by BattleBas** [comment]
Thank you for the response!
My main issue is with finding them, anything to help make it easier to search through the list would help. How do you propose the filter feature would work? Would it be a list of filter options or a search box?

Do you know what the current sort order is for the providers? Maybe displaying this information could help, in case its currently sorted by most recently changed or something along those lines.

**Comment by joaomoreno** [comment]
The current sort is by "appearance"... the first ones to be discovered by Code stay at the top. This is useful because often they follow the same order as workspace folders, coincidentally.
