### ISSUE TITLE
vscode marketplace cert is self-signed, preventing any extension installation

### ISSUE THREAD

**Issue by hausdorff** [Microsoft/vscode#42868]
You can see it, _e.g._, when you visit the site: https://marketplace.visualstudio.com/vscode

This is borderline catastrophically bad, it basically means that no one can download any new extensions. I'm going to randomly tag in the top contributors, and hope one of them sees it: @bpasero @joaomoreno @jrieken @alexandrudima 

This is also the cause of the recent resurgent interest in #34385.

**Comment by hausdorff** [comment]
Ok, this issue seems to be resolved. I think we can close it for now.

**Comment by David-Abi** [comment]
@hausdorff 
hi,  I still don't get how this was resolved. Kindly help
I have had to wait for a lasting solution if there's one. 
I have read up too many suggestion on #34385 issue.
Best regards

**Comment by hausdorff** [comment]
@David-Abi I don't think you are talking about the issue detailed here. The issue I'm describing is with the certificates for the vscode marketplace. These have been fixed.
