### ISSUE TITLE
Recieve Error XHR failed: message when trying to install extensions (macOS Sierra)

### ISSUE THREAD

**Issue by brandonb81** [Microsoft/vscode#42865]
I have a clean install of VS Code for macOS High Sierra. Upon opening the editor and going to the _Extension_ tab on the left, I receive an XHR error. I've seen this issue posted but with no viable solutions.

- VSCode Version: 1.19.3 (1.19.3)
   <img width="290" alt="screen shot 2018-02-02 at 8 48 35 pm" src="https://user-images.githubusercontent.com/17714530/35762772-7ea1c2ee-085a-11e8-942d-3d7792df9cbe.png">

- OS Version: macOS High Sierra (Version 10.13.3)

Steps to Reproduce:

1. Open fresh install of VS Code
2. Go to _Extensions_ tab
3. Receive a __Error XHR failed:__ message
   * <img width="1088" alt="screen shot 2018-02-02 at 8 30 58 pm" src="https://user-images.githubusercontent.com/17714530/35762739-585d8c22-0859-11e8-859f-43daf14b92ca.png">
4. Open Developer tools and see extensionquery failed
    * <img width="1042" alt="screen shot 2018-02-02 at 8 46 56 pm" src="https://user-images.githubusercontent.com/17714530/35762768-4dc61774-085a-11e8-8a16-7a48a6e84967.png">
5. Opened Network Settings and no Proxies are configured
    * <img width="548" alt="screen shot 2018-02-02 at 8 53 14 pm" src="https://user-images.githubusercontent.com/17714530/35762797-1f81fc4c-085b-11e8-9aeb-c03db286f15f.png">

Does this issue occur when all extensions are disabled?: Yes/No
* This issue is related to trying to install extensions.

**Comment by brandonb81** [comment]
I'm now currently not getting this error. Must have been on your guys' end.

**Comment by sandy081** [comment]
@joaomoreno When do we show the XHR failed message?

- No internet connection?
- Proxy issues?
- Market place is not reachable?

**Comment by joaomoreno** [comment]
Must've been some server problem.
