### ISSUE TITLE
Issue reporter: Loading process information takes a long time

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#42860]
### Issue Type
Bug

### Description

The issue reporter loads system, workspace and running process information with a single request. The later takes a long time on Windows. This can keep the user from submitting a bug report or feature request for which the running process information is unneeded.

We should split the calls and only request the process information for performance issues.

### VS Code Info

VS Code version: code-oss-dev 1.21.0 (Commit unknown, Date unknown)
OS version: Windows

Reproduces without extensions

**Comment by egamma** [comment]
FYI here some back ground on why this operation is slow on Windows https://github.com/Microsoft/vscode/issues/39376#issuecomment-349595709
