### ISSUE TITLE
C# #if and #endif indentation is reset after formatting messing with folding of outer code

### ISSUE THREAD

**Issue by uday0408** [Microsoft/vscode#42861]
- VSCode Version: 1.19.3
- OS Version: Mac OS X, 10.13
- C# Extension version: Omnisharp 1.13.1

For C#, after formatting with Omnisharp installed, the #region and #endregion statements are indented at the same level of enclosing code. But #if and #endif are formatted to have no indentation, thus messing with folding when #if/#endif enclosing code is nested.

I don't know if this is Omnisharp or VSCode problem.

Steps to Reproduce:

1. Apply formatting to following code
```
public static class Main
{
    public static int Foo(int x)
    {
        x = 5;
        #if false
        x++;
        #endif
        return x;
    }
}
```
    
2. After formatting it looks like this:
```
public static class Main
{
    public static int Foo(int x)
    {
        x = 5;
#if false
        x++;
#endif
        return x;
    }
}
```

3. This messes with folding of entire code!!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
I believe the way Omnisharp (Roslyn) formats is the generally accepted way for formatting C# macros.

The problem is that our folding regions are currently computed in a language agnostic way, based on indentation.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2008

**Comment by aeschli** [comment]
The request for language aware folding is #3422.

Moving to Omnisharp for deciding about whether the formatter needs to be changed or made configurable.
