### ISSUE TITLE
Potential security issue with storing ftp-sync.json inside project

### ISSUE THREAD

**Issue by gopi-ar** [Microsoft/vscode#42867]
We observed bots trying these URLs on a few of our servers this morning. We've forbidden anything prefixed with a `.` from being served so we noticed this in our NGINX logs:

```
Feb 03 08:09:01 error.log: 2018/02/03 08:09:01 [error] 1021#0: *263862511 access forbidden by rule, client: 195.22.127.249, server: _, request: "GET /.ftpconfig HTTP/1.1", host:

Feb 03 08:09:01  error.log: 2018/02/03 08:09:01 [error] 1021#0: *263862550 access forbidden by rule, client: 195.22.127.249, server: _, request: "GET /.remote-sync.json HTTP/1.1", host:

Feb 03 08:09:02 error.log: 2018/02/03 08:09:02 [error] 1021#0: *263862555 access forbidden by rule, client: 195.22.127.249, server: _, request: "GET /.vscode/ftp-sync.json HTTP/1.1", host: 

```

The last request is worrisome if some users actually use such a plugin and store their vscode project configs inside their repos. We haven't investigated this internally because we don't use FTP but this might be of interest to the vscode team looking at security.

We didn't find an email on the repo to report security issues so posting this here.

**Comment by alexandrudima** [comment]
@gopi-ar VS Code does not store any credentials in a file called `ftp-sync.json`. Do you perhaps use an extension that would do so ?

**Comment by gopi-ar** [comment]
@alexandrudima we don't personally store vs-code's project files inside a repo. Raised the issue in your other users did. Still, might be good form to encourage storing project files outside a source code repo.

**Comment by alexandrudima** [comment]
@gopi-ar Which extension is storing sensitive stuff in `ftp-sync.json` ? I need to know in order to contact them and ask them to fix this. IMHO, none of the Microsoft authored extensions, nor VSCode core, would do this.

**Comment by gopi-ar** [comment]
No clue at all, sorry. We found a bot scanning for this URL so felt we had to report this; that's all the info we have unfortunately. Feel free to close the issue if necessary.

**Comment by alexandrudima** [comment]
@sandy081 Can we run a full-text search over all extensions with `ftp-sync.json` to find out which one it is ?

**Comment by sandy081** [comment]
Sure

**Comment by sandy081** [comment]
@alexandrudima [ftp sync](https://github.com/lukasz-wronski/vscode-ftp-sync) extension uses uses `ftp-sync.json` to sync user repo.

**Comment by alexandrudima** [comment]
Moved to https://github.com/lukasz-wronski/vscode-ftp-sync/issues/228
