### ISSUE TITLE
Application not responding during debugging (breakpoints) then Visual Studio GUI does not respond

### ISSUE THREAD

**Issue by computersarecool** [Microsoft/vscode#42866]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Debug an application with a breakpoint
2. Wait, then try to hover over a value

Does this issue occur when all extensions are disabled?: Yes

When the application is stuck on a breakpoint, the following happens:

![screenshot from 2018-02-02 19-46-43](https://user-images.githubusercontent.com/5414692/35762804-ce4cac8a-0852-11e8-9bf5-9922447e130d.png)

When this happens, the Visual Studio Code GUI kind of freezes so hovering over variables does not show their current value.  However, I am not sure if this is a code issue or an Ubuntu issue.

**Comment by weinand** [comment]
@computersarecool what debugger are you using?
The alert you are seeing is not coming from VS Code. That seems to be an alert from the runtime you are running your program on.

**Comment by computersarecool** [comment]
I am using `gdb`.  I think the issue could be with Ubuntu / Gnome but I am not sure how to get around this.
If the program is paused on a breakpoint, it does not seem like a "not responding" alert should pop up from the OS.

**Comment by weinand** [comment]
Please file the issue against the gdb extension. VS Code has only a builtin node.js debugger (which you are not using).
