### ISSUE TITLE
Add LivePreview feature

### ISSUE THREAD

**Issue by Ayman97** [Microsoft/vscode#42875]
Isn't awesome to see this feature in VS Code ?

**Comment by PixelT** [comment]
It doesn't make sense to add this as an editor's functionality
Use https://browsersync.io/ instead

**Comment by Ayman97** [comment]
@usernamehw 
Like the built-in feature that exists in Brackets

**Comment by Ayman97** [comment]
@PixelT I'll try it, Thanks

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/12080 ?
