### ISSUE TITLE
[jade] comment line color wrongly colored after new lines

### ISSUE THREAD

**Issue by Lonefy** [Microsoft/vscode#4287]
- VSCode Version: 0.10.11
- OS Version: win10

the color of first comment line seems incorrect,when there are `odd number of empty line` before.
screen shot:
![image](https://cloud.githubusercontent.com/assets/7921431/13800349/77c243ec-eb63-11e5-8e83-9a7254940e4f.png)

![image](https://cloud.githubusercontent.com/assets/7921431/13800477/9a150d84-eb64-11e5-84a3-41e0dd85a3a7.png)

![image](https://cloud.githubusercontent.com/assets/7921431/13800363/8db9cefe-eb63-11e5-9360-07479191ba4c.png)

**Comment by aeschli** [comment]
Reproduced with snippet
```
.ssdsd
	ul.asdasd
		li.asdasd
	
	// asdsdas
```

**Comment by aeschli** [comment]
This issue was moved to davidrios/jade-tmbundle#74

**Comment by aeschli** [comment]
David mentioned this is a vscode issue only. I need to investigate again.

**Comment by aeschli** [comment]
I created https://github.com/Microsoft/vscode-textmate/issues/17

**Comment by alexandrudima** [comment]
Fixed Microsoft/vscode-textmate#17 and adopted via 7533f1e141f561776175043c7be6431fc25c0e1d
