### ISSUE TITLE
Intellisense keeps highlighting erased characters

### ISSUE THREAD

**Issue by Kinrany** [Microsoft/vscode#42878]
![vscode-bug](https://user-images.githubusercontent.com/1634186/35766787-6c561b72-08ef-11e8-94af-ca1f6c1fa3d5.png)

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
angular2-snippets|dan|1.0.17
vscode-eslint|dba|1.4.5
vscode-npm-script|eg2|0.3.3
search-node-modules|jas|1.2.0
node-module-intellisense|lei|1.5.0
code-beautifier|mic|1.7.2
vscode-exec-node|mir|0.5.0
angular2-inline|nat|0.0.17
Angular2|UVB|0.4.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0
markdown-all-in-one|yzh|1.0.5

---

Steps to Reproduce:

1. Type `.` to open Intellisense with all the options
2. Type any single character to see the options that have that character
3. Erase that character to see all the options again, but the erased character is still highlighted

Repeat to highlight any number of characters, but not more than one per line.

Only the last erased character stays.

 - Reproduces without extensions: Yes

**Comment by jrieken** [comment]
@Kinrany Thanks for reporting this. We shipped this since almost a year and no one noticed or bothered to report. Fixed with a one line change.
