### ISSUE TITLE
:( Cannot read property 'toCommandArgument' of undefined

### ISSUE THREAD

**Issue by Michany** [Microsoft/vscode#42876]
Warning when I use keyboard shortcut to run python in terminal

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
easy-icons|jam|0.3.1
vs-color-picker|lih|0.7.0
python|ms-|2018.1.0
cpptools|ms-|0.14.6
sas|Vac|0.1.2
clang-format|xav|1.6.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/42802

**Comment by alexandrudima** [comment]
https://github.com/Microsoft/vscode-python/issues/689
