### ISSUE TITLE
Insiders build stop updating?

### ISSUE THREAD

**Issue by PixelT** [Microsoft/vscode#42879]
```
Version 1.20.0-insider (1.20.0-insider)
3c59a4923cd1d17df13db4475cf6292de32aa95e
2018-01-25T06:03:47.483Z
```
As above, I have last update on 2018-01-25.
System: MacOS
Does anybody else has this same situation?

**Comment by joaomoreno** [comment]
If you check for updates in the app menu, what does that say?

**Comment by PixelT** [comment]
Nothing. No error, warnings or info messages. But I downloaded yesterday new Insider version and I will see if the update will be available soon.

**Comment by joaomoreno** [comment]
OK. New insiders will be released at the end of this week. Closing for now. Let me know if you still don't get updates at the end of the week.
