### ISSUE TITLE
Add Install button for Insiders on Marketplace

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#42874]
As I see it could be done by simply adding a button with slightly changed `href`
```diff
- <a href="vscode:extension
+ <a href="vscode-insiders:extension
```

**Comment by sandy081** [comment]
@joaomoreno This has to be supported by market place right?

**Comment by joaomoreno** [comment]
cc @viradhamMS @pkuma-msft

We already brought this up, especially during the design phase of the install button. Is this in the Marketplace's backlog yet?

**Comment by pkuma-msft** [comment]
@joaomoreno Yes this is in our backlog

**Comment by joaomoreno** [comment]
@usernamehw We care. But we also care about other stuff. 👍

**Comment by usernamehw** [comment]
From the message it seems like there's a separate issue tracker where this issue already exists...

**Comment by OrangutanGaming** [comment]
Has anyone created a userscript for this?

**Comment by usernamehw** [comment]
I mean ... it's just feels useless keeping it open.

For button design you can try something like `split dropdown`:

![Screenshot (124)](https://user-images.githubusercontent.com/9638156/72095163-06dc5480-3329-11ea-959d-1d4d2a0a1a5f.png)

The main button would install in `Stable`, while dropdown would contain (`Insiders` & `Exploration`) entries.

https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns
