### ISSUE TITLE
workbench.action.files.saveAll totally disregards while clauses

### ISSUE THREAD

**Issue by johndebord** [Microsoft/vscode#42870]
- VSCode Version: 1.19.3 x64 CS: 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
- OS Version: Ubuntu Linux 16.04

Steps to Reproduce:

1. goto keybindings.json
2. make this keybind:
```
{
    "key": "ctrl+x ctrl+s", // (or any bind of your choosing)
    "command": "workbench.action.files.saveAll",
    "while": "!editorHasSelection" // (or any other while clause)
}
```
3. select some text
4. press the keybind
5. it should not saveAll, but it does; ignoring the while clause.

**Comment by johndebord** [comment]
Any takers?

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/35225 ?

**Comment by usernamehw** [comment]
Wait, there is no **while** condition, only **when**.

**Comment by johndebord** [comment]
Why do I make such stupid mistakes?
Why????!!!
WHYYYYYYY?????????!!!!!!!!

Thanks usernamehw..
