### ISSUE TITLE
keyboard input are not displayed on Integrated Terminal 

### ISSUE THREAD

**Issue by chemidy** [Microsoft/vscode#42877]
When i launch the go binary game invaders in an integrated terminal, an error occured on the game.

`Cannot read file: open imgs/start.png: no such file or directory
Cannot decode file: image: unknown format
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x10c584f]
goroutine 1 [running]:
...`

After that the integrated terminal is not usable, keyboard input are not displayed. 

- VSCode Version: Version 1.19.3 (1.19.3) & Version 1.20.0 (1.20.0)
- OS Version: macos 10.13.3 (17D47)

Steps to Reproduce:

1. go get github.com/sausheong/invaders
2. launch invaders (an error occurred)
3. the terminal is broken

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Tyriar** [comment]
@chemidy I haven't seen any reports like this, does this happen when running in Terminal.app?

**Comment by chemidy** [comment]
OK, this is not a vscode issue, it's also broken in Terminal.app. Thks
