### ISSUE TITLE
Wierd font size of terminal

### ISSUE THREAD

**Issue by ShangxuanWu** [Microsoft/vscode#42873]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|0.8.0
python|ms-|2018.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

I sometimes got this wierd terminal font size when I attach my macbook  to external display.
Fonts are fixed when I close the terminal and start a new one.

![image](https://user-images.githubusercontent.com/12669087/35765615-b0c76dd8-0895-11e8-9e6c-e93b063f81a2.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
