### ISSUE TITLE
IntelliSense remembers my last selection (please remove this)

### ISSUE THREAD

**Issue by Vacummus** [Microsoft/vscode#42884]
In the November 2017 release, IntelliSense has been updated to remember your last selection. The use of this feature has been VERY frustrating and makes IntelliSense feel buggy. For example, I have a class called `Variable`. When I type `var` and select `Variable`, VS Code remembers that selection. The next time I type `var` and hit tab, instead of selecting `var` (which is what I am expecting), it selects `Variable`. This makes it very unpredictable since now it's less likely to select what I am expecting due to this feature. Not sure how many people like this feature, but please at the very least provide a way to disable it.

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/41060

**Comment by Vacummus** [comment]
Thanks. Glad to see I am not alone in this. Looks like they will be be making this feature configurable: https://github.com/Microsoft/vscode/issues/42477#issuecomment-362313891
