### ISSUE TITLE
Wrong hotkey hint for .md file preview

### ISSUE THREAD

**Issue by ShangxuanWu** [Microsoft/vscode#42888]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

This hint is wrong. It should be `Command + Shift + v` .

![image](https://user-images.githubusercontent.com/12669087/35768762-5508af04-08cf-11e8-807d-41922edc6cf9.png)

**Comment by usernamehw** [comment]
Those are different commands. One opens to the Side.

**Comment by alexandrudima** [comment]
![image](https://user-images.githubusercontent.com/5047891/35798952-9088b0ba-0a64-11e8-8f05-bf402b863883.png)
