### ISSUE TITLE
A

### ISSUE THREAD

**Issue by denisenricohasyim93** [Microsoft/vscode#42882]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
python|ms-|2018.1.0
java|red|0.18.1
python|tht|0.2.3
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@denisenricohasyim93 Please create a new issue with complete steps and a proper description.
