### ISSUE TITLE
pressing delete while inside expression in Watch window deletes the whole entry and leaves VSCode in a bad state

### ISSUE THREAD

**Issue by AleksandarPantic** [Microsoft/vscode#42881]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Start debugging session in any (backend or frontend) javascript app and set a break point
2. After execution stops, add anything to the Watch window
3. Try editing the expression in the Watch window; use the 'delete' key while editing
4. Result: instead of a single letter being deleted, the whole expression is deleted from the Watch window, and the VSCode is left in a bad state which is reflected in all other expressions being greyed out, i.e. almost invisible

After launching with `code --disable-extensions` the same thing happens (while using a node.js application)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Duplicate #42753
