### ISSUE TITLE
Unable to download VS code from https://vscode-update.azurewebsites.net/latest/win32-x64/stable

### ISSUE THREAD

**Issue by kperisetla** [Microsoft/vscode#42883]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Goto 
2. Click "Download" button, it redirects to URL https://vscode-update.azurewebsites.net/latest/win32-x64/stable which is not reachable.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Can you check your network? This is accessible for me.

What IP address does `vscode-update.azurewebsites.net` resolve to? What makes you say it is not reachable? Do you get an HTTP error code?
