### ISSUE TITLE
Extension Host terminated unexpectedly

### ISSUE THREAD

**Issue by stizzle123** [Microsoft/vscode#42891]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Once I open vscode, the error pops up and I'm unable to do anything
2. Also, I have disabled Typescript Hero and nothing has changed

Reproduces without extensions: Yes/No

**Comment by stizzle123** [comment]
Please, I'd like a solution to the issue "Extension Host terminated unexpectedly", vscode only works when I'm connected to the internet, can't use it offline. Didn't have this issue with the previous version.

**Comment by alexandrudima** [comment]
@stizzle123 IMHO, this is a problem with one of the extensions you have installed. Does this issue reproduce when disabling extensions?

To troubleshoot the start-up of the extension host, can you please open `F1 > Show logs... > Extension Host` and look for the last messages before the extension host crashes. Also, you can run `F1 > Developer Tools` and check the console.
