### ISSUE TITLE
Debugger attach request hangs with cluster fork.

### ISSUE THREAD

**Issue by entr0cks** [Microsoft/vscode#42894]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
---
Steps to Reproduce:
1. fork some processes with cluster module.
2. run node program with --inspect
3. add attach configuration to launch.json with port 9230. Port number is displayed in console with last step.

Result: 
Now you should see a blue bar running from left to right under the debug bar.
Can't stop it with "Debug: stop" or trying to run any other debug configuration.

Note: 
Using 9229 for master and 9231 for a second fork works. Also "Debugger attached." is logged in console for either.
With 9230 only the "Debugger listening on ...." is displayed after closing VS Code like with others.
9232 Times out like it's supposed to when creating only 2 forks.
Netstat displays 9230 as listening and when the debugger is "attach looping" there's also an "established" connection.

Reproduces without extensions: Yes

**Comment by entr0cks** [comment]
After continuing work, at some point I was able to connect to all forks again. A hour after finally writing this issue.
Had this problem for the whole day. Where it didn't want to close or start a new debugger connection, for first forked processes, without closing VS Code. 
Couldn't reproduce it anymore either.

**Comment by weinand** [comment]
You might want to try the new auto-attach (aka cluster) feature in the upcoming January release (or in Insiders).

**Comment by entr0cks** [comment]
Yeah, read about it already while searching through the issues here.
Thank you anyway!
