### ISSUE TITLE
Document DebugSession and related classes + concepts

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#42896]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: irrelevant

Writing a debug adapter currently is a big guessing game and requires hours of searching and fruitless attempts. This is mostly because there's no documentation about the details, for e.g. `DebugSession` or `StoppedEvent` (what values can we use for the reason?). So, my feature request here is about documenting debug adapters and related code parts (like `DebugConfigurationProvider`) fully. Thank you.

**Comment by weinand** [comment]
We are planning to document the Debug Adapter Protocol, but not any language specific implementations. The "truth" for the protocol is here: 
https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json

But If you don't like to read JSON-schema you can use the generated TypeScript definitions:
 https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts

**Comment by mike-lischke** [comment]
Great, thanks.

**Comment by mike-lischke** [comment]
A small side note:

```TS
export declare class StoppedEvent extends Event implements DebugProtocol.StoppedEvent {
    body: {
        reason: string;
        threadId: number;
    };
    constructor(reason: string, threadId: number, exception_text?: string);
}
```

The member `exception_text` should probably be `exceptionText`, to keep naming consistency.

**Comment by weinand** [comment]
A new introduction is now available [here](https://microsoft.github.io/debug-adapter-protocol/overview) on our new DAP web site: https://microsoft.github.io/debug-adapter-protocol/
