### ISSUE TITLE
Autosave accumulates duplicate copies `fileName-localhost.localdomain-%d.md`

### ISSUE THREAD

**Issue by chrisshaw** [Microsoft/vscode#42902]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.14.14-300.fc27.x86_64
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Launch `code --disable-extensions`
2. Turn on Autosave
3. Open file in current folder (a .md in this case)
4. Edit the file
5. Autosave
6. Keep editing the file
6. Observe the addition of the file in the directory. Intermittently accompanied by a refresh of your file (often an earlier snapshot, resulting in lost work)

You will also occasionally see the error: Failed to save '....': The content on disk is newer. Click on Compare to compare your version with the one on disk.

![screenshot from 2018-02-03 17-45-16](https://user-images.githubusercontent.com/2966918/35772804-15bcee9c-090a-11e8-849f-af09a8d6d3a0.png)

**Comment by bpasero** [comment]
It is very unlikely that VS Code is causing this. Could something be wrong with your Linux installation?

**Comment by chrisshaw** [comment]
This is a relatively new find for me so hard to know where Fedora may have introduced any issue. I bumped it up to the latest 4.16 and then down to 4.11 and am still seeing issues.

Do you have advice on diagnostics?

This does, however, seem to be isolated to .md files, and Atom isn't having issues.

**Comment by chrisshaw** [comment]
Found the issue. This was not caused by VS Code but a new service I'd recently started.
