### ISSUE TITLE
Cursor moves below the line selected

### ISSUE THREAD

**Issue by Waffun** [Microsoft/vscode#42906]
I'm using "htmltagwrap" for wrap the selected text with tags, but when i click on the line number to select the whole line, and use Ctrl+W to wrap that line, the extensions works wrong because the line selection move the cursor below the line that i needed selected.

![t1](https://user-images.githubusercontent.com/22793954/35775288-c699f444-0964-11e8-86b9-90563b59ab73.png)
![t2](https://user-images.githubusercontent.com/22793954/35775289-c6f6d52e-0964-11e8-996e-37659c22a7bd.png)

- VSCode Version:1.19.3
- OS Version:
Ubuntu 17.10

Steps to Reproduce:

1. Click on the line number
2. You will see that the whole line is selected and the cursor jumps to the line below

Expected behavior:
Select only the line clicked and mantain the cursor in that line

**Comment by alexandrudima** [comment]
@Waffun I don't believe we ship out-of-the-box with a "htmltagwrap" command. Is this perhaps coming in from an extension ?

**Comment by octref** [comment]
Seems to be this one: https://marketplace.visualstudio.com/items?itemName=bradgashler.htmltagwrap

Please report extension issues in their own repo: https://github.com/bgashler1/vscode-htmltagwrap
