### ISSUE TITLE
Cursor control without arrow keys in 'find', 'find-and-replace', 'sidebar', and 'terminal' windows.

### ISSUE THREAD

**Issue by johndebord** [Microsoft/vscode#42900]
It would be nice to have control over the cursor in the 'find', 'find-and-replace', 'sidebar', and 'terminal' windows without having to move my hand away from home-row and use the arrow keys.

**Comment by Tyriar** [comment]
Do you have any suggestions on how this would work? There's a vim extension which may be a better place to ask this and they can ask for APIs. I don't see this sort of thing landing standard though.

**Comment by johndebord** [comment]
I guess we can just ignore the 'find', 'find-and-replace', and 'sidebar' cursor control.

But for the terminal here's what I was thinking.
Here's what I was thinking (API calls):
workbench.action.terminal.
workbench.action.terminal.
workbench.action.terminal.

**Comment by johndebord** [comment]
I guess we can just ignore the 'find', 'find-and-replace', and 'sidebar' cursor control.
Since we can easily 'select-all' and edit whatever we're searching for.

But for the terminal here's what I was thinking.
Here's what I was thinking (API calls):
workbench.action.terminal.cursorLeft
workbench.action.terminal.cursorRight
workbench.action.terminal.commandPrevious
workbench.action.terminal.commandNext

cursorLeft/Right for editing a command if you miss-typed it.
commandPrevious/Next for cycling through your most recent commands.

**Comment by Tyriar** [comment]
For the terminal, shells already support these sort of keybindings out of the box, no? http://www.keyxl.com/aaaf192/83/Linux-Bash-Shell-keyboard-shortcuts.htm

**Comment by bpasero** [comment]
@johndebord there already exists commands for navigation within tree/lists and opening, see:

![image](https://user-images.githubusercontent.com/900690/35871051-8c99311e-0b63-11e8-85a9-35158034188b.png)

(list.select maps to opening).

**Comment by Tyriar** [comment]
> I guess we can just ignore the 'find', 'find-and-replace'. Since we can easily 'select-all' and edit whatever we're searching for.

Seems like everything is already covered then.
