### ISSUE TITLE
VSCode Eats F13 on Windows

### ISSUE THREAD

**Issue by nickcox** [Microsoft/vscode#42908]
### Issue Type
Bug

### Description

Press F13 without VS Code open. Observe that Windows interprets it as expected.

Press F13 with VS Code Window active. Observe that nothing happens (in terms of global Windows key handlers). Code seems to swallow the key-press.

From `Developer: Inspect Key Mappings`

```
"F13": {
	"vkey": "VK_F13",
	"value": "",
	"withShift": "",
	"withAltGr": "",
	"withShiftAltGr": ""
}
```

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (3f8cf5311b631c5bc395df1e8b9c795358c1ef80, 2018-02-03T01:33:20.355Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz (4 x 2395)|
|Memory (System)|15.71GB (9.35GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe . --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled
Reproduces without extensions

**Comment by alexandrudima** [comment]
I have just connected an Apple keyboard (has F13-F15 keys) to a Windows machine.

F13 appears to work correctly in VSCode, but your bug is about the fact that VSCode is somehow eating it. I wonder how I could reproduce that.

> Press F13 without VS Code open. Observe that Windows interprets it as expected.
> Press F13 with VS Code Window active. [...] Code seems to swallow the key-press.

How could I validate this? Windows doesn't do anything for me when I press F13 and VS Code is closed and also doesn't do anything for me when I press F13 and VS Code is opened.

**Comment by nickcox** [comment]
Hmmmm. Not sure about the most general way to test. Here what I did:

* Create a shortcut to a text document on my desktop
* Right-click > Properties > Shortcut key
* Press F13
* Press OK
* Observe that with most other applications active the text document can be opened by pressing F13
* Observe that with VS Code active F13 does not open the text document

**Comment by alexandrudima** [comment]
With the Apple Keyboard (has F13-F19), the Shortcut Key input accepts F1-F12, but not F13-F19, so unfortunately I cannot test it with this method.

Anyway, I am 100% sure we don't do anything special in our code for F13 (compared to other keys), so if there are no keybindings bound to F13 (check in ctrl+k ctrl+s), then it should just pass through to the OS.

I'm sorry I spent some time looking through the office for a different keyboard with F13, but couldn't find one.

**Comment by nickcox** [comment]
Sorry, I should have mentioned that, when I tried it, the Shortcut dialog didn't populate the 'Shortcut key' field with the text `F13` as it did for `F1`-`F12` but the binding actually still worked anyway. (Weird. One for you bros on the Windows team? jk)

Have you tried this test with the other function keys? I have the same issue with the other keys `F10`, for example, although Code reports that the key is only bound in debug mode. `Ctrl-F10` works fine though. (As does Ctrl-F13.)

**Comment by nickcox** [comment]
Ah. I've realised that this issue only seems to manifest when I'm running Code as Admin. (Which I usually do for... reasons.)

No issue whatsoever if I launch code from a non-admin terminal so I guess that's the workaround.

**Comment by alexandrudima** [comment]
@nickcox I think that is a general problem on Windows and the way events are passed on Windows between processes... 

If the foreground window is running in an administrator process, then events will not be received by less privileged processes... or something along those lines.

So I believe any foreground process ran as admin would "eat" up F13.
