### ISSUE TITLE
Disable Automatic Comment Block

### ISSUE THREAD

**Issue by k1rb** [Microsoft/vscode#42901]
When I type `##` immediately get:
```powershell
##############################
#.SYNOPSIS
#Short description
#
#.DESCRIPTION
#Long description
#
#.EXAMPLE
#An example
#
#.NOTES
#General notes
############################## 
```
  
If I press escape it leaves the block, if I ctrl+z it removes everything including the `##` that I just typed (as expected with an undo), when I re-type `##` it does it all over again.

This is **EXTREMELY** annoying. Please how can I make it stop. Sorry this is opening as an issue but I cannot find where or how to shut this off, in default settings I have searched for "comment" and "complete", etc, have found nothing useful.

My user settings are:
```
{
    "workbench.startupEditor": "Scratch",
    "editor.renderWhitespace": "all",
    "editor.tabCompletion": false,
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.detectIndentation": false,
    "editor.wordWrap": "off",
    "editor.quickSuggestions": false,
    "editor.acceptSuggestionOnEnter": false,
    "editor.wordBasedCompletion": false,
    "editor.quickSuggestionsDelay": 20,
    "editor.wordBasedSuggestions": false,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "explorer.confirmDragAndDrop": false,
    "explorer.confirmDelete": false,
    "editor.parameterHints": false,
    "editor.autoClosingBrackets": false,
    "editor.formatOnType": false,
    "editor.suggestOnTriggerCharacters": false
}
```

**Comment by alexandrudima** [comment]
@k1rb What file type is this ?

**Comment by k1rb** [comment]
@alexandrudima .ps1

**Comment by alexandrudima** [comment]
Interestingly, when I type `##` in a `.ps1`, nothing happens on a default installation of VS Code. Is this perhaps something that happens due to a specific extension? Does this reproduce when disabling all extensions ?

**Comment by octref** [comment]
@k1rb
This is caused by the PowerShell extension: https://github.com/PowerShell/vscode-powershell/blob/master/snippets/PowerShell.json#L536-L555

Please report extension specific issues to the extension repo: https://github.com/PowerShell/vscode-powershell/issues
