### ISSUE TITLE
{ Translation } redo untranslated and keybinding incorrect

### ISSUE THREAD

**Issue by ogerly** [Microsoft/vscode#42907]
- VSCode Version: 1.19.3
- OS Version: 17.10

Steps to Reproduce:

0. Set VSCode to German
1. Open keybindings settings
2. See "redo"

First: redo is untranslated.
Second: Keybinding is set to Strg+Y, while Strg+Z is default in German settings usually. (Z for "Zurück")

Does this issue occur when all extensions are disabled?: Yes

**Comment by jens1o** [comment]
You can translate `redo` for anyone using this guide: https://aka.ms/vscodeloc

The second issue is indeed an issue, but I fixed it for me using the keybinding manager.

**Comment by ShalokShalom** [comment]
Well, thanks for confirming. 

It did happen here in the first trails, that the pressing of Ctrl+Z on the keyboard showed ctrl+y on the screen. In the keybindings editor popup.

This changed after a few trails into a correct behaviour.

**Comment by ShalokShalom** [comment]
That something basic like redo is untranslated, while everything else - much rare ones - happen to be fully translated, is it an idea that this string/element got changed recently. 

So, this might be also a reason to the other issues. 

So, is this function changed or extended since a while?

**Comment by alexandrudima** [comment]
The Keybindings Editor shows both command ids and command titles.

When a command id has an associated title, the title is presented.

The title is something that is localized, the command id is not.

**Comment by sandy081** [comment]
Yes. As @alexandrudima  said, `redo` command has no title and the keybindings editor shows id in such cases and ids are shown differently (font) than titles.

Ids are never translated.

**Comment by ShalokShalom** [comment]
> When a command id has an associated title, the title is presented.

Well, its not the case here. I love it when people close unresolved issues.
The issue about the incorrect default and the incorrect input is also unresolved.

Makes three unresolved issues.

**Comment by jens1o** [comment]
Although I have respect for your opinion, I think separating the issues into separated github issues would improve the workflow :)

**Comment by ShalokShalom** [comment]
Since I see zero interest to actually solve issues to which I contribute, do I consider ANY future reports as superflous from now on.

**Comment by alexandrudima** [comment]
@ogerly For the keybinding problem you are raising, can you please let me know:
* your OS
* your keyboard layout

**Comment by alexandrudima** [comment]
@ShalokShalom Can you please let me know:
* your OS
* your keyboard layout

**Comment by ShalokShalom** [comment]
Ogerly will probably not answer you, he never looks into Github notifications. 
His setup is that one of an Ubuntu 17.10 (fork) and a German keyboard layout. 

I am on KaOS with de_AT.UTF-8 and here is the default setting (Ctrl+Z) correct and working. 
Therefore, I see undo and redo as separate commands,  

redo is default at Y, while undo on the correct Z.

Is this intended?

Thanks for your support.

**Comment by alexandrudima** [comment]
@ShalokShalom We have a list of known issues related to keybindings on Linux:
https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

I will assume you are sitting in front of the machine and that KaOS is installed natively on that machine (no remoting, no virtualization).

If that is the case, and assuming you have installed multiple keyboard layouts, then we are most likely suffering from:
a) switching keyboard layouts while VS Code is running #23690
b) `setxkbmap -query` does not return the keyboard layout that is currently active. #24166

**Comment by ShalokShalom** [comment]
> I will assume you are sitting in front of the machine and that KaOS is installed natively on that machine (no remoting, no virtualization).

Yep

> 
If that is the case, and assuming you have installed multiple keyboard layouts, then we are most likely suffering from:

I just removed the second binding, in order to avoid that this is possible. 
They are still installed, while not loaded.

**Comment by alexandrudima** [comment]
Thanks for the extra information. This appears to work fine on my ubuntu system. I have installed the `at` keyboard layout and the keybinding for Undo is labeled `Ctrl+Z` as expected:
![screenshot from 2018-02-05 15-53-50](https://user-images.githubusercontent.com/5047891/35810819-34af5860-0a8d-11e8-8009-8a4212502243.png)

When I open an editor in VSCode and run `F1 > Developer: Inspect Key Mappings` here is what I get:
```
Layout info:
{
	"model": "pc105",
	"layout": "at,us",
	"variant": ",",
	"options": "",
	"rules": "evdev"
}
isUSStandard: false
...
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|       HW Code combination      |  Key  |    KeyCode combination    | Pri |          UI label         |         User settings          |    Electron accelerator   |       Dispatching string       | WYSIWYG |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                           KeyY |   z   |                         Z |     |                         Z |                              z |                         Z |                         [KeyY] |         |
|                      Ctrl+KeyY |   z   |                    Ctrl+Z |     |                    Ctrl+Z |                         ctrl+z |                    Ctrl+Z |                    ctrl+[KeyY] |         |
|                     Shift+KeyY |   Z   |                   Shift+Z |     |                   Shift+Z |                        shift+z |                   Shift+Z |                   shift+[KeyY] |         |
|                Ctrl+Shift+KeyY |   Z   |              Ctrl+Shift+Z |     |              Ctrl+Shift+Z |                   ctrl+shift+z |              Ctrl+Shift+Z |              ctrl+shift+[KeyY] |         |
|                       Alt+KeyY |   z   |                     Alt+Z |     |                     Alt+Z |                          alt+z |                     Alt+Z |                     alt+[KeyY] |         |
|                  Ctrl+Alt+KeyY |   ←   |                Ctrl+Alt+Z |     |                Ctrl+Alt+Z |                     ctrl+alt+z |                Ctrl+Alt+Z |                ctrl+alt+[KeyY] |         |
|                 Shift+Alt+KeyY |   Z   |               Shift+Alt+Z |     |               Shift+Alt+Z |                    shift+alt+z |               Shift+Alt+Z |               shift+alt+[KeyY] |         |
|            Ctrl+Shift+Alt+KeyY |   ¥   |          Ctrl+Shift+Alt+Z |     |          Ctrl+Shift+Alt+Z |               ctrl+shift+alt+z |          Ctrl+Shift+Alt+Z |          ctrl+shift+alt+[KeyY] |         |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
...
	"KeyY": {
		"value": "z",
		"withShift": "Z",
		"withAltGr": "←",
		"withShiftAltGr": "¥"
	},
```

So, on my machine, VSCode correctly detects that the scan code `[KeyY]` produces the character `z`. Then, the UI of VSCode correctly shows that Undo is Ctrl+Z and when I press the key between T and U (scan code `[KeyY]`, labeled as Z on German keyboards), undo works as expected.

What is identified by the `native-keymap` module when you run the same `Inspect Key Mappings` command ?

**Comment by ShalokShalom** [comment]
Yep, Undo is at Z here as well, as stated. This was not working on Ogerlys device only. 
Is there Redo on your device as well? What is the difference?

Inspect Key Mappings gives me a huge list:
https://gist.github.com/ShalokShalom/fdc9892e2c5356d09199912185e56179

**Comment by alexandrudima** [comment]
@ShalokShalom Ok, thank you. But then it looks to me that you have absolutely no problem, right ?

And it is only @ogerly that had a problem. Perhaps we can ask him to go through https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings
