### ISSUE TITLE
String is too long to recognize

### ISSUE THREAD

**Issue by D3xian** [Microsoft/vscode#42905]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-base64|ada|0.0.1
vscode-database|baj|1.3.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
vscode-eslint|dba|1.4.5
vscode-stylesheet-formatter|dba|0.2.0
wpy-beautify|doi|2.0.10
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.1.2
insert-file|esp|0.0.2
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
path-autocomplete|ion|1.8.1
docthis|joe|0.6.0
code-beautifier|mic|1.7.2
ecdc|mit|0.11.0
vscode-filesize|mkx|1.1.0
vscode-autoprefixer|mrm|2.1.2
vscode-csscomb|mrm|5.2.2
vscode-less|mrm|0.6.3
mssql|ms-|1.3.0
debugger-for-chrome|msj|4.1.0
js-patterns-snippets|nik|0.0.5
vetur|oct|0.11.7
view-in-browser|qin|0.0.5
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
vue-vscode-snippets|sdr|1.3.0
highlight-matching-tag|vin|0.4.4
JavaScriptSnippets|xab|1.5.0
clang-format|xav|1.6.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1.Open this website
2.http://gallery.echartsjs.com/editor.html?c=xrJgNA-Nxz
3. Put （var fillimg=********） in the editor
4.Editor does not recognize

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
What do you mean that it does not recognize the string? Please describe the expected behavior and what is going wrong.

Also, does this still happen if you disable all extensions?
