### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by mkhstar** [Microsoft/vscode#42910]
Frequently Getting Extension host terminated unexpectedly. Dont know what to do can someone help me fix this?

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
vscode-faker|dee|1.2.1
LiveServer|rit|3.1.0
vscode-icons|rob|7.19.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@mkhstar 

1. You can run `F1 > Toggle Developer Tools` and look for an error in the console.

2. You can run `F1 > Open Logs folder` or `F1 > Show Logs... > Extension Host`

3. You can run `F1 > Show Running Extensions` and see which extensions are running. The running extensions are most likely the root cause of the crash.

**Comment by mkhstar** [comment]
@alexandrudima 
When I start Microsoft Visual Code no error shows up. I can open html, css and javascript files. But when i open a php file the error fires up and it causes all the extensions to stop working . When i followed your troubleshooting i realized that when i startup Microsoft Visual Code for the first time at the show running extensions these extensions starts up git,emmet,html,merge-conflict,Bracket Pair Colorizer, Live Server,vscode-icons.
When i open php none of them becomes available. I think it might be due to the php extension

**Comment by roblourens** [comment]
- Does it happen with any PHP file, or just one particular file? 
- Does it still happen if you set `"php.validate.enable": false`?

**Comment by mkhstar** [comment]
Oh wow magic after setting "php.validate.enable": false?
The error hasn't shown up again

**Comment by roblourens** [comment]
Ok, so it's related to the built-in PHP support. 

Can you try to unset that setting and help us narrow it down?

Please look for additional error details from the sources above:

> You can run F1 > Toggle Developer Tools and look for an error in the console.
> You can run F1 > Open Logs folder or F1 > Show Logs... > Extension Host

And, does it happen with any PHP file, or just one particular file?

**Comment by devangsolanki-blog** [comment]
I am facing the same issue, but while opening VSC.
