### ISSUE TITLE
Add link to the documentation in the generated jsconfig.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4291]
Testing #4007 

jsconfig.json is now support comments and we should add a comment with a link to the documentation, as is done for the task.json.

![image](https://cloud.githubusercontent.com/assets/172399/13805564/0bd511da-eb56-11e5-8881-c01fba1586ae.png)

**Comment by jrieken** [comment]
@egamma I need to know the link?

**Comment by egamma** [comment]
http://go.microsoft.com/fwlink/?LinkId=733559

**Comment by egamma** [comment]
@jrieken sorry I've decided to create a fresh forward link and to not to reuse an existing. I've updated the commend above with the link.

**Comment by jrieken** [comment]
no worries. updated
