### ISSUE TITLE
css class intellisence

### ISSUE THREAD

**Issue by abvaalgit** [Microsoft/vscode#42911]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Stephn-R** [comment]
@abvaalgit there are already tools that provide support for intellisense in CSS. You can find more information herein:

https://code.visualstudio.com/docs/languages/css

**Comment by aeschli** [comment]
@abvaalgit Please give more information whats missing.
Maybe it dup of
[css] propose class names that exist in HTML #28442
or 
[html] intellisense for css class names that exist in other files #27635 ?

**Comment by abvaalgit** [comment]
@aeschli  ok ..
yes [intellisense for css class names that exist in other files] is not working ...and thousands other  issues
you must add all features and enhancements that have been added in intelliJ Platfrom (the best ide in the world)  it is good prototype for your job..
good luck mans

**Comment by aeschli** [comment]
It would be great if you can help us make VSCode better, but we need more specific requests.
Please add a code sample and describe the steps that demonstrate the problem and what the editor can do to help.
