### ISSUE TITLE
Add an API that fires after all documents are saved as part of a Save All action

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#42913]
I have some functionality in Dart Code that reloads on-save. Currently I use `onDidSaveTextDocument` but this fires multiple times if you use `Save All` so I have to de-bounce it to fire my reload only once. While this works, it introduces an artificial delay and is also a bit of a race - depending on the timing of saving it may still fire multiple times (finding a value that works perfectly is impossible).

It would be great if there was something like a `vs.workspace.onDidSaveTestDocuments` that fired after all saves are complete from a single operation (whether it be save all or an individual save that only affected one file, including when saves are a result of hitting `F5`).

**Comment by jrieken** [comment]
The easiest workaround is to listen on onDidSave and to iterator over all document and to check the dirty state.
