### ISSUE TITLE
Promote configure excludes to a message box

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4292]
Testing #4007 

Currently we show the 'configure excludes' message in the status bar. Since this is an exceptional situation we should promote this to a message that is more in the face of the user.

**Comment by jrieken** [comment]
Problem with that is that an accidental ESC will dismiss the message without you knowing what happened. That's my I am in favour of a trigger that you cannot dismiss easily.

**Comment by egamma** [comment]
Accidental dismiss is a problem, agreed. - closing
