### ISSUE TITLE
Escaping characters in a string fails to render a usable snippet

### ISSUE THREAD

**Issue by fatherjack** [Microsoft/vscode#42930]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
vscode-markdownlint|Dav|0.13.0
xml|Dot|1.9.2
json-tools|eri|1.0.2
mssql|ms-|1.3.0
PowerShell|ms-|1.5.1
vscode-docker|Pet|0.0.23
material-icon-theme|PKi|3.2.2

---
As per guidance at https://www.jaapbrasser.com/quickly-and-securely-storing-your-credentials-powershell/ I am trying to create a snippet to insert the string 

$Cred | Export-CliXml -Path "${env:\userprofile}\Secret.Cred"

Steps to Reproduce:

1. Open File menu, expand Preferences and select User Snippets
2. choose PowerShell language
3. [powershell.json file opens]
4. Enter the snippet JSON as 
"Credential": {
		"prefix": "_Cred_Single",
		"body": [
			"$Cred | Export-CliXml -Path "${env:userprofile}\Secret.Cred",
		],
		"description": "Snippets for creating a secure file for credential details and for importing credential from a file. with thanks for code example to @Jaap_Brasser - https://www.jaapbrasser.com/quickly-and-securely-storing-your-credentials-powershell/"
	}

5. Edit the line that begins $Cred to escape the combination of $ and { and \ and env: as well as the need for " to appear in the output.

6. >> I don't think there is any combination that results in the correct output. The escaping for one character affects others in the line and doesn't work as expected/described.

Reproduces without extensions: Yes/No

**Comment by SQLDBAWithABeard** [comment]
I can reproduce this also 

 could not escape the “${env:

**Comment by tjlundstrom** [comment]
I was able to get it to work with this:
```
		"body": [
			"$$Cred | Export-CliXml -Path \"\\$\{{env:\\userprofile}\\Secret.Cred\"",
		],
```

It's not pretty but it output `$Cred | Export-CliXml -Path "${env:\userprofile}\Secret.Cred"`

**Comment by SQLDBAWithABeard** [comment]
Which is odd because if I copy that code exactly I get this

![image](https://user-images.githubusercontent.com/6729780/36026170-cc2b6366-0d8d-11e8-8d94-fdaed21c0752.png)

**Comment by tjlundstrom** [comment]
My bad, try this:
```
"body": [
    "$$Cred | Export-CliXml -Path \"\\${env:\\userprofile}\\Secret.Cred\"",
],
```
This is giving no errors in the editor and properly producing: `$Cred | Export-CliXml -Path "${env:\userprofile}\Secret.Cred"`

See #1670 for similar problem

**Comment by fatherjack** [comment]
Great, thanks. Now I just need to work out how to add tabs!! ie {1:filename}
