### ISSUE TITLE
all extentions stopped working, close editor and reopen every time to get it work, and still repeat same thing

### ISSUE THREAD

**Issue by Wharley01** [Microsoft/vscode#42933]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
code-gnu-global|aus|0.2.2
vscode-refresh-html|baj|0.0.2
bracket-pair-colorizer|Coe|0.10.14
compulim-vscode-closetag|Com|1.1.0
vscode-eslint|dba|1.4.5
xml|Dot|1.9.2
es7-react-js-snippets|dsz|1.3.3
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.3
react-native-react-redux|EQu|1.4.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.6
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
terminal|for|0.0.10
beautify|Hoo|1.3.0
phpcs|ika|0.7.0
vscode-browser-sync|jas|1.3.0
react-native-snippet|jun|0.4.2
cpptools|ms-|0.14.6
node-debug2|ms-|1.19.0
team|ms-|1.122.0
debugger-for-chrome|msj|4.1.0
java|red|0.18.1
vscode-icons|rob|7.19.0
todotasks|san|0.5.0
jsx|Twe|0.0.1
highlight-matching-tag|vin|0.4.4
vscode-java-debug|vsc|0.6.0
vscode-react-native|vsm|0.5.7
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.16.1

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please file this guide to report issues: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues
