### ISSUE TITLE
Mac- cannot launch in High Sierra 10.3.3

### ISSUE THREAD

**Issue by EwellBMyne** [Microsoft/vscode#42935]
When I try to launch VS Code, I get an error saying it will not work with this release of macOS. This is not a beta version of macOS. I have tried both stable and insider's edition.
![snip20180204_1](https://user-images.githubusercontent.com/29761733/35781099-8bce6792-09b3-11e8-9820-bf108af90314.png)

- VSCode Version: 1.18, 1.20
- OS Version: macOS 10.3.3

Steps to Reproduce:

1. Copy VSCode to Mac
2. Try to launch

Does this issue occur when all extensions are disabled?: Yes/No

No extensions have been installed yet. Tried it anyway, no difference.

**Comment by EwellBMyne** [comment]
Process:               Electron [10882]
Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Version:               1.19.3 (1.19.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [10882]
User ID:               501

Date/Time:             2018-02-04 14:02:17.904 -0500
OS Version:            Mac OS X 10.13.3 (17D47)
Report Version:        12
Anonymous UUID:        280DF019-3F9E-24D0-BB06-0462870F79C5


Time Awake Since Boot: 92000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x104731000 -        0x104731ff7 +com.microsoft.VSCode (1.19.3 - 1.19.3) <1A780387-B9CC-365B-9D6C-C38A9E714A15> /Applications/Visual Studio Code.app/Contents/MacOS/Electron
       0x11274c000 -        0x11279698f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld

Model: Macmini5,1, BootROM MM51.007B.B00, 2 processors, Intel Core i5, 2.3 GHz, 8 GB, SMC 1.76f0
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE4), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: iPhone 2, Ethernet, en6
Network Service: iPad, Ethernet, en4
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SanDisk Ultra II 500GB, 500.11 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: iPhone
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: iPad
USB Device: IR Receiver
Thunderbolt Bus: Mac mini, Apple Inc., 22.2

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by EwellBMyne** [comment]
The behavior is the same with either.  I had indeed tried the Insiders Build before posting the problem.
This is the data it sends to Apple, in case this gives any ideas. I am not convinced this is a VS Code problem- it's very possible it is on my end, but I have no idea at this point where to look.

Process:               Electron [19690]
Path:                  /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCodeInsiders
Version:               1.20.0-insider (1.20.0-insider)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [19690]
User ID:               501

Date/Time:             2018-02-05 09:01:17.664 -0500
OS Version:            Mac OS X 10.13.3 (17D47)
Report Version:        12
Anonymous UUID:        280DF019-3F9E-24D0-BB06-0462870F79C5


Time Awake Since Boot: 160000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10f1cd000 -        0x10f1cdff7 +com.microsoft.VSCodeInsiders (1.20.0-insider - 1.20.0-insider) <1A780387-B9CC-365B-9D6C-C38A9E714A15> /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron
       0x11a424000 -        0x11a46e98f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld

Model: Macmini5,1, BootROM MM51.007B.B00, 2 processors, Intel Core i5, 2.3 GHz, 8 GB, SMC 1.76f0
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE4), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SanDisk Ultra II 500GB, 500.11 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: IR Receiver
Thunderbolt Bus: Mac mini, Apple Inc., 22.2


________________________________

**Comment by bpasero** [comment]
@EwellBMyne do you see the same with this version: https://az764295.vo.msecnd.net/exploration/395608d787740e20d207d278c4d1494995a719a9/VSCode-darwin-exploration.zip ?

**Comment by thegamenicorus** [comment]
I've this problem today (with OSX 10.13.3), It's appear all the time when I try to open VSCode. Seem like this error related to Electron.

My quick fix is download fresh installer from website and install in my Application. And I can launch VSCode again with installed extensions. Everything working fine now.

**Comment by EwellBMyne** [comment]
I've reinstalled it, a week ago, and it complains about the OS NOT being supported, even though I an current. I can try again tomorrow to install.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EwellBMyne** [comment]
Visual Studio Code cannot be opened because of a problem.

Check with the developer to make sure Visual Studio Code works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.


Click Report to see more detailed information and send a report to Apple.

________________________________

**Comment by EwellBMyne** [comment]
Process:               Electron [40704]
Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Version:               1.22.1 (1.22.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [40704]
User ID:               501

Date/Time:             2018-04-07 10:44:40.439 -0400
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Anonymous UUID:        280DF019-3F9E-24D0-BB06-0462870F79C5

Sleep/Wake UUID:       F670067F-5A62-4328-B985-41FB6737FA41

Time Awake Since Boot: 300000 seconds
Time Since Wake:       510 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x106600000 -        0x106600ff7 +com.microsoft.VSCode (1.22.1 - 1.22.1) <1A780387-B9CC-365B-9D6C-C38A9E714A15> /Applications/Visual Studio Code.app/Contents/MacOS/Electron
       0x108e35000 -        0x108e7f9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld

Model: Macmini5,1, BootROM MM51.007F.B00, 2 processors, Intel Core i5, 2.3 GHz, 8 GB, SMC 1.76f0
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE4), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.5f3, 3 services, 27 devices, 1 incoming serial ports
Network Service: iPhone 2, Ethernet, en6
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SanDisk Ultra II 500GB, 500.11 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: iPhone
USB Device: IR Receiver
Thunderbolt Bus: Mac mini, Apple Inc., 22.2


________________________________

**Comment by thegamenicorus** [comment]
Well, Crash again on my machine.
------------------------------------
Process:               Electron [94525]
Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Version:               1.22.2 (1.22.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [94525]
User ID:               501

Date/Time:             2018-04-19 10:49:59.070 +1000
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Anonymous UUID:        65E741A0-7AEF-6565-203D-9DEED303B0A4

Sleep/Wake UUID:       CCE25330-9E87-4053-8F16-2DDD149E3670

Time Awake Since Boot: 120000 seconds
Time Since Wake:       350 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libnode.dylib
  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found

Binary Images:
       0x10c673000 -        0x10c673ff7 +com.microsoft.VSCode (1.22.2 - 1.22.2) <1A780387-B9CC-365B-9D6C-C38A9E714A15> /Applications/Visual Studio Code.app/Contents/MacOS/Electron
       0x10c67e000 -        0x10c698fff +com.github.Squirrel (1.0 - 1) <0A9F60FF-F2D2-364A-962A-65137E68760E> /Applications/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x10c6c2000 -        0x10c725ff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Applications/Visual Studio Code.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x10c7a2000 -        0x10c7b6fff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Applications/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x10caa1000 -        0x10caeb9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
       0x10cb3f000 -        0x110aa5f6b +com.github.electron.framework (0) <97EE2AE0-0A06-3E62-B6F3-CF666EF00628> /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
    0x7fff47a95000 -     0x7fff47a95fff  com.apple.Carbon (158 - 158) <F8B370D9-2103-3276-821D-ACC756167F86> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff53b27000 -     0x7fff53b27fff  com.apple.quartzframework (1.5 - 21) <DCEB0FCC-2C32-3D02-8752-7B6FA009AB85> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff53b28000 -     0x7fff53d73ff7  com.apple.QuartzCore (1.11 - 584.40) <ABC7F8FA-5F5A-31F4-868B-FDC4175BAFAC> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff545a7000 -     0x7fff548cffff  com.apple.security (7.0 - 58286.51.6) <7212D257-5324-3DBA-8C26-504D6B8F632A> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff5495d000 -     0x7fff5498dfff  com.apple.securityinterface (10.0 - 55109.50.6) <343FFA91-89CF-3A3F-833A-D65A2647CCF1> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff6e847000 -     0x7fff6e848ffb  libSystem.B.dylib (1252.50.4) <C7810EA7-A61F-3817-8E54-E2EC4E26F946> /usr/lib/libSystem.B.dylib
    0x7fff6eafe000 -     0x7fff6eb54fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib

Model: MacBookPro9,1, BootROM MBP91.00D9.B00, 4 processors, Intel Core i7, 2.3 GHz, 16 GB, SMC 2.1f170
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Graphics: NVIDIA GeForce GT 650M, NVIDIA GeForce GT 650M, PCIe
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x0198, 0x393955353432382D3036332E4130304C4620
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x0198, 0x393955353432382D3036332E4130304C4620
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.190.18.1a3)
Bluetooth: Version 6.0.5f3, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS547550A9E384, 500.11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS31N
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1
