### ISSUE TITLE
How to make this doc box stay below what I'm typing instead of above?

### ISSUE THREAD

**Issue by pillaiindu** [Microsoft/vscode#42937]
I code Elixir in VSCode through vscode-elixir extension. The doc tip (showed in the screenshot) always stays at the top until the line of code is very high in the page that there is no space above the function (in which case it move below).

I want the functionality reversed, so that the doc tip stays always below the function, until there is no space below the function. Is there some setting to achieve that?

Thank you!

Below is the screenshot.
![VSCode Screenshot](https://i.imgur.com/eDICADB.png)

**Comment by ramya-rao-a** [comment]
@joaomoreno Why would this be a "bug"? Isn't this a feature request (also tracked in #33752)?
