### ISSUE TITLE
Compatibility issues with relational operating systems.

### ISSUE THREAD

**Issue by Hideer** [Microsoft/vscode#42941]
A compatibility problem with Windows7 and Windows10 may be found during the process of use, and the font spacing of the terminal in Windows7 will be unreasonably undrawn.

who can help me?

**Comment by yume-chan** [comment]
1. What's your Visual Studio Code version?
2. Can you attach a screenshot for your problem?

**Comment by Tyriar** [comment]
I'm guessing this is https://github.com/Microsoft/vscode/issues/35681. Note that even for mono space fonts the spacing may be slightly different that the editor due to different rendering techniques.
