### ISSUE TITLE
SCM badges look strange

### ISSUE THREAD

**Issue by pushqrdx** [Microsoft/vscode#42940]
Description:
 Badges are oval shaped with weird (uncentered) text position.

It's a little bit aesthetic yet i find it important to polish those little things (because they are very easy to fix). I hope someone from the awesome team finds a little bit of time to fix that.

Here is a [picture](https://imgur.com/XAJulJ3) representing the issue, where the badge is oval shaped and the `7` isn't at the center.

**Comment by joaomoreno** [comment]
Can you take a screenshot of what you mean?

**Comment by pushqrdx** [comment]
@joaomoreno [here](https://imgur.com/XAJulJ3), you can see the oval shaped badge icon (usually when there's an odd number)

**Comment by joaomoreno** [comment]
We can't make it circular, because they can grow horizontally... but we can make it have a minimum width such `width >= height`.

**Comment by shobhitchittora** [comment]
@joaomoreno I think a better solution could be if we can change the left-right padding fo the badge itself. 

Code pointer - 
https://github.com/Microsoft/vscode/blob/91120eb786357aa1e16217ad6a67cf0740f26e8e/src/vs/base/browser/ui/countBadge/countBadge.css#L7
@pushqrdx would you like to take this up?

**Comment by pushqrdx** [comment]
@shobhitchittora I've put together a quick [demo](https://jsfiddle.net/7jvq9w2g/) for the fix i have in mind, tell me what you think and i'll submit a pr.

**Comment by pushqrdx** [comment]
@shobhitchittora @joaomoreno i have submitted a [pr](https://github.com/Microsoft/vscode/pull/43256). hope you take a look.
