### ISSUE TITLE
Zoom Out keyboard shortcut on Ubuntu

### ISSUE THREAD

**Issue by ASHWINI-GUPTA** [Microsoft/vscode#42942]
- VSCode Version: Code 1.19.3
- OS Version: Linux x64 4.13.0-32-generic

I encounter the problem with the VSCode Zoom Out keyboard shortcut on Ubuntu (Ctrl + NumPad_Subtract) it is not working with the laptop keyboard without NumPad layout.

**Comment by alexandrudima** [comment]
@ASHWINI-GUPTA Please bind the shortcut to a different keybinding using the Keybindings Editor (ctrl+k ctrl+s)
