### ISSUE TITLE
Uploading logs: 'Unable to move the cache'

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42949]
### Issue Type
Bug

### Description

There seemed to be issues with handling of a cache folder:

```
PS C:\devel\angular-test> code-insiders --upload-logs=iConfirmLogsUpload

Uploading...
[12232:0205/090511.890:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[12232:0205/090511.890:ERROR:cache_util.cc(134)] Unable to move cache folder C:\Users\chrmarti.REDMOND\AppData\Roaming\Code - Insiders\Cache to C:\Users\chrmarti.REDMOND\AppData\Roaming\Code - Insiders\old_Cache_000
[12232:0205/090511.890:ERROR:disk_cache.cc(132)] Unable to create cache
.
.
.
.
Upload successful! Log file ID: 3004556063
```

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (3f8cf5311b631c5bc395df1e8b9c795358c1ef80, 2018-02-03T01:33:22.197Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|5.98GB (2.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces without extensions

**Comment by yangbing007** [comment]
I also run into this problem and eventually failed to solve id,so i reinstalled the system and gave up Blazor.

**Comment by yangbing007** [comment]
I was going to develop a BIM model interaction page with Blazor WebAssembly, but i had to use Three.js, the JS interaction syntax and scheme of  Blazor is disgusting!
