### ISSUE TITLE
formatter autopep8 is not installed

### ISSUE THREAD

**Issue by jisooyu** [Microsoft/vscode#42947]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
jshint|dba|0.10.15
vscode-eslint|dba|1.4.5
java-debug|DSn|0.0.2
code-runner|for|0.8.7
vscode-javac|geo|0.0.47
beautify|Hoo|1.3.0
rest-client|hum|0.17.0
csharpextensions|jch|1.3.0
svn-scm|joh|1.15.0
git-tree-compare|let|1.1.4
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
Kotlin|mat|1.4.0
hg|mrc|1.2.3
python|ms-|2018.1.0
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
team|ms-|1.122.0
java|red|0.18.1
python|tht|0.2.3
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.2.0
html-css-class-completion|Zig|1.16.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
VS Code does not ship out-of-the-box with the `autopep8` python package. Please create an issue against the python extension.
