### ISSUE TITLE
Where is workspace "memory" stored and how to clear it?

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#42948]
I noticed VS Code memorizes which tabs are open when I re-open a workspace. Where is this information stored? (asking for Mac & Linux)

**Comment by bpasero** [comment]
Windows:  `C:\Users\<userid>\AppData\Roaming\Code\Local Storage`
Linux: `/home/<userid>/.config/Code/Local Storage`
macOS: `/Users/<userid>/Library/Application Support/Code/Local Storage`

**Comment by ffxsam** [comment]
@bpasero is there a recommended way to clear out workspace cache other than just removing the files? (will that remove anything else unintentionally?)

**Comment by bpasero** [comment]
@ffxsam open an empty window and type `window.localStorage.clear()` into dev console

**Comment by ffxsam** [comment]
Perfect, thanks!

**Comment by ffxsam** [comment]
Oddly enough, I was still left with a 3MB file (same size as before running `localStorage.clear()`). So I don't think that did the trick.

It would be nice if there were a command-line command, a la Atom's `atom --clear-window-state`.
