### ISSUE TITLE
Deleting files in explorer

### ISSUE THREAD

**Issue by piotrkolodziej** [Microsoft/vscode#42954]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.1.8
vscode-icon-theme|jtl|1.6.1
csharp|ms-|1.13.1

(2 theme extensions excluded)

---

Steps to Reproduce:

I have this issue every time I am deleting migrations.

1. Expand the directory with multiple files (the directory should be not on the top level)
2. Delete the file

The result being, VS Code automatically selects the element at the top of the explorer (unreleated folder). I'd expect it to return the focus to the first available parent of deleted file.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
This is fixed in the latest vscode insiders and will be in vscode stable in a couple of days.
Once an element is deleted, its sibling will get selected, not the top level one

**Comment by piotrkolodziej** [comment]
Super! Thank you.
