### ISSUE TITLE
doubled quoted hilight for ini file doesn't work correclty

### ISSUE THREAD

**Issue by Jalkar** [Microsoft/vscode#42958]
There is an issue in  [https://github.com/Microsoft/vscode/blob/master/extensions/ini/syntaxes/ini.tmLanguage.json]

The double quote hilight does not take account of escaped double quote

exemple file : 

```ini
[test]
hilightValues = "expected \" double quote colored"
shouldNotBeHilight = toto
```
everthing after the first double quote will be hilight as inside a double quote

**Comment by aeschli** [comment]
This issue was moved to textmate/ini.tmbundle#5
