### ISSUE TITLE
How to DISCARD my input command in vscode terminal

### ISSUE THREAD

**Issue by LIUHUANUCAS** [Microsoft/vscode#42953]
- how to **discard** my input command for terminal in vscode when I input command ,for example command ='git push ',But I don't want to execute the command ?  I must delete an character **step by step** at vscode terminal,which will be **time-comsuimg**.
- what has happended in linux is that I can use CTRL+C to terminate the input and have a new line and continue to input new command.
But vscode terminal can not response when I use CTRL+C,

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment]
For Windows shells, hit <kbd>ESC</kbd> to clear the input.

I'm not familiar with macOS so I don't know that side.
