### ISSUE TITLE
Error:XHR failed:  plugin not install

### ISSUE THREAD

**Issue by alihb** [Microsoft/vscode#42959]
- Extension Name: configuration-editing
- Extension Version: 0.0.1
- OS Version: Linux x64 4.13.0-32-generic
- VSCode version: 1.19.3

 We have written the needed data into your clipboard. Please paste:

**Comment by octref** [comment]
> We have written the needed data into your clipboard. Please paste:

Can you try it again and paste the relevant data to GitHub?
