### ISSUE TITLE
Python Run selection/Line In Python Terminal error

### ISSUE THREAD

**Issue by boazdori** [Microsoft/vscode#42957]
- VSCode Version: 1.19.3
- OS Version: Windos 10
- Python version 3.6

Steps to Reproduce:

1.When running line of code to the terminal repl by using Run Selection/Line in python terminal I get an error 

I am running the following code

ints = [4, 0, 1, 5, 6]

and get the following 

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\user\Documents\Visual Studio 2017\Projects> & cmd /k "C:\Users\user\Anaconda3\Scripts\activate.bat & powershell"
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\user\Documents\Visual Studio 2017\Projects> ints = [4, 0, 1, 5, 6]
ints : The term 'ints' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ints = [4, 0, 1, 5, 6]
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (ints:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\user\Documents\Visual Studio 2017\Projects>

seems like run selection dosn't activate the python repl. this happend after the updating the python extension.
any ideas?

**Comment by Tyriar** [comment]
@boazdori you're running the line inside powershell, not python. It looks like the issue you're having is related to the python extension https://github.com/Microsoft/vscode-python
