### ISSUE TITLE
Rendering Problems

### ISSUE THREAD

**Issue by Faust90** [Microsoft/vscode#42952]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Open Visual Studio Code

Does this issue occur when all extensions are disabled?: Yes

After the last update the IDE graphics are corrupted, here is a screenshot.
![render-problem](https://user-images.githubusercontent.com/17139906/35796305-6c8d560a-0a5c-11e8-8290-5740356987bd.png)

**Comment by alexandrudima** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/35675
