### ISSUE TITLE
Don't always disable auto pairs when not before a whitespace

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#42956]
From https://github.com/Microsoft/vscode/issues/18071#issuecomment-310753772

When adding a quote after the `=` in  `<div class=></div>` you will get `<div class='>` but would rather like to have `<div class=''>` 

Auto-pairs tests whether character after the cursor is a new line or a whitespace. Otherwise it will not insert the pair, just a single quote.
We should extend the language specification to give a list of characters where auto-pairs are enabled. In the case of HTML, for `'` and `"`, that would be `>`

The example is quite common in HTML when adding attributes to existing elements.

**Comment by aeschli** [comment]
Other example from #43039 
In .html file, you type a tag `<div></div>`, and type {{ inside of it ... and what you expect is that curly braces will auto-close. But they don't.

They want to auto-close only in situations when there is a space after your caret:

![ng - curly braces](https://user-images.githubusercontent.com/24613274/35863871-b9215816-0b58-11e8-9d93-cf502a7ace55.gif)

**Comment by user3323** [comment]
@aeschli 

how about parenthesis right before semicolon?..

![parenthesis - semicolon](https://user-images.githubusercontent.com/24613274/36057999-e4960306-0e1f-11e8-97f7-a795a7c6b076.gif)

or that's a different case?

**Comment by aeschli** [comment]
Same issue. The auto pair heuristic currently does not add a closing bracket when the next character is not a whitespace or line end.

**Comment by Mimis40** [comment]
Please work on this soon, I would really like to see it implemented!

**Comment by aeschli** [comment]
@rebornix FYI

**Comment by arxpoetica** [comment]
Just ran into this, and, when using mustache style syntax, it can be a real hang up. Is there a way to turn this off across the board? Why should their be a discrepancy?

**Comment by JacksonKearl** [comment]
@rebornix What would you think of just delegating the determination of which characters allow matching to the user via settings? I have a branch up here: https://github.com/JacksonKearl/vscode/tree/feature-demo/auto-closing-config that demos this.

This is how it looks if you set
`"editor.autoClosingEnabledBefore": " \"\n\t<>.,';"`:

![afterandbefore](https://user-images.githubusercontent.com/8586769/41446795-7ce0937c-7006-11e8-9a85-844cf31e7039.gif)

(First run through is with the new setting second is original)
