### ISSUE TITLE
C# Unity auto complete hints are wrong

### ISSUE THREAD

**Issue by zeyangl** [Microsoft/vscode#4295]
- VSCode Version:  0.10.11
- OS Version: 10.11

Steps to Reproduce:

1. As shown in the following image, the autocompletion hints are wrong. It shows raw xml instead of formatted method information.

![image](https://cloud.githubusercontent.com/assets/1244606/13807673/4aa9819c-eb9d-11e5-83ea-6a810e06f0ce.png)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#97
