### ISSUE TITLE
Intellisense auto-replaces exact match with partial, but recently used, incorrect value

### ISSUE THREAD

**Issue by sinbad** [Microsoft/vscode#42961]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.1
toml|be5|0.0.3
gitlens|eam|7.5.10
latex-workshop|Jam|3.13.0
docomment|k--|0.0.17
Go|luk|0.6.73
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7
rewrap|stk|1.6.1
unity-tools|Tob|0.1.9
pdf|tom|0.2.0
unity-debug|Uni|1.2.1
unity-snippets|Ycl|0.1.2
vscode-open-in-github|ziy|1.3.1

---

Steps to Reproduce:

Image to illustrate: https://imgur.com/a/H4JC0

1. In C# code, add a couple of variables which are similar, say in this case "score" and "scoreArea"
2. Type "sc" then pick "scoreArea"
3. Type another line but type exactly "score". 
4. Instead of Intellisense defaulting to "score", it defaults to "scoreArea" because that was most recently picked previously, even though there is an exact match
5. If you press Space or "." the default Intellisense pick overrides what you typed

I expected it to prefer the exact match; this is very disruptive to code flow since it auto-replaces correct code with incorrect code. 

It is not limited to prefixes, I've had it replace "gm" (a valid local var) with "GameManager" (a type) as well. 

Reproduces without extensions: I can't realistically do this since without the csharp extension intellisense doesn't work.

**Comment by kleber-swf** [comment]
I think this is related to the history of using those words. It's nice, but a exact match should be a higher priority imho.

**Comment by sinbad** [comment]
Yes - the priority-based default is a relatively new feature and this problem has only occurred since then. It's usually beneficial, but should not override exact matches as you say.

**Comment by sinbad** [comment]
Just been referred to an upcoming workaround for this in 1.20, along with an earlier issue, so closing this in favour: https://github.com/Microsoft/vscode/issues/41060
