### ISSUE TITLE
Copy  file form one instance (window), unable to paste to other window.

### ISSUE THREAD

**Issue by ranvirgorai** [Microsoft/vscode#42960]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-wakatime|Wak|1.1.22
vscode-eslint|dba|1.4.5
fileheadercomment|doi|0.0.3
prettier-vscode|esb|1.1.2
vscode-fileheader|mik|0.0.2
python|ms-|2018.1.0
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
node-debug2|ms-|1.19.0
java|red|0.18.1
vscode-fileutils|sle|2.7.1
Align|ste|0.2.0
code-spell-checker|str|1.6.3
react-beautify|tai|0.3.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.2.0
vscode-react-native|vsm|0.5.7

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
@bpasero Does #164 cover this one too? (Seems specifically for copy-paste across apps, not across windows in VS Code).
