### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by kenjiyamamoto** [Microsoft/vscode#42969]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.3.0
vscode-docker|Pet|0.0.24
nativescript|Tel|0.7.2
vscode-eslint|dba|1.4.5
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.1.2
Angular2|joh|2.12.0
code-beautifier|mic|1.7.2
python|ms-|2018.1.0
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.1.0
vscode-icons|rob|7.19.0
vscode-format|rya|0.0.6
python|tht|0.2.3
nativescript-ng2-snippets|www|2.0.1
JavaScriptSnippets|xab|1.5.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Please describe the issue and reopen the issue again.
