### ISSUE TITLE
vscode load same module 2 times if require it with absolute path and relative path

### ISSUE THREAD

**Issue by wsg36236** [Microsoft/vscode#42964]
- VSCode Version:1.19.3
- OS Version:win10

Steps to Reproduce:

**1. create file app.js with code:**
var test = require("./test.js");
var common = require("./common.js");

common.test();
test.test();

**2.create file test.js with code:**
exports.test = function () 
{
    var common = require("D:\\codes\\JavaScript\\node\\Test2Path\\common.js");
    common.test();
}

"D:\\codes\\JavaScript\\node\\Test2Path\\common.js" must replace as your common.js's absolute path.

**3.create file common.js with code:**
(function () {
console.log("common.js loaded");

exports.test = function () 
{
    console.log("common test");
}
})();

**4. run app.js with vscode**
it will print "common.js loaded" 2 times, but if run app.js just with node, it only print 1 time, so vscode cause common.js be loaded 2 times if require it with absolute path and relative path.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This seems like a node issue, not a vscode issue. Please try asking this on stackoverflow or reporting the issue against node
