### ISSUE TITLE
[Feature Request] Allow to define and select Debug and Release build configurations

### ISSUE THREAD

**Issue by 1g0rb0hm** [microsoft/vscode#42967]
It would be great to have support for **Debug** and **Release** configurations similar to:
* [How to: Set debug and release configurations in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-debug-and-release-configurations)
* or [Xcode build schemes and configurations](https://medium.com/practical-ios-development/some-practical-uses-for-xcode-build-schemes-and-build-configurations-swift-e50d15a1304f)

This is useful for compiled programming language projects written in C/C++ for example.

**Comment by alexr00** [comment]
You can do this to some extent now with input variables.
