### ISSUE TITLE
Formatter inconsistencies

### ISSUE THREAD

**Issue by mhchem** [Microsoft/vscode#42968]
- VSCode Version: 1.19.3
- OS Version: Windows 10

Steps to Reproduce:
1. Create an extension with the following fomatter in `activate()`.
```ts
    let formatter = vscode.languages.registerDocumentFormattingEditProvider('myfiletype', {
        provideDocumentFormattingEdits(document: vscode.TextDocument): vscode.TextEdit[] {
            let ret = [];
            ret.push(vscode.TextEdit.replace(document.lineAt(1).rangeIncludingLineBreak, "aaa" + counter + "\n         aaaa\n\n"));
            ret.push(vscode.TextEdit.replace(document.lineAt(0).rangeIncludingLineBreak, "bbb" + counter + "\n         bbbb\n\n"));
            counter++;
            return ret;
        }
    });
    let counter = 0;
```
2. Run the extension and in a corresponding file (with at least a few lines), execute Format Document twice.

3. The result is fine. 
```
bbb1
         bbbb

aaa1
         aaaa


aaa0
         aaaa
```

4. In the code, comment the line `counter++;` (or remove `+ counter +`) from the lines above.

5. Execute the extension with the same file and run Format Document twice.

6. The result is
```
bbb0
aaa0
         bbbb

         aaaa


aaa0
         aaaa
```
Notice that the line order changed.

This looks like the `.replace` commands are cached somehow and if nothing changes – counter stays the same or there is no need for a counter – then it is not correctly re-evaluated and the two commands mix up. This might even be a JS compiler bug?

**Comment by jrieken** [comment]
The command is surely run an invoked two times but it's a weird edit sequence because they overlap. Needs some drilling
