### ISSUE TITLE
ts version indication should not show 'unknown'

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4296]
* configure vs code to use a different _tsdk_ 
* the status bar shows _unknown_ which I believe is a little unhappy. maybe _custom_ is better?

<img width="161" alt="screen shot 2016-03-16 at 11 01 15" src="https://cloud.githubusercontent.com/assets/1794099/13808475/80c00350-eb66-11e5-9497-3665ffe49d56.png">

**Comment by dbaeumer** [comment]
Agree. I assume you built the tsserver.

**Comment by jrieken** [comment]
correct
