### ISSUE TITLE
Auto-closing tag

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#42974]
- VSCode Version: 1.20.0-ins
- OS Version: win7x64

![div br](https://user-images.githubusercontent.com/24613274/35813306-f2353ee6-0a9b-11e8-8e64-e3d171914ce9.gif)

When you type `<div> </div>`, and trying to type `</br>` inside of it - right after **</** it will auto-close `</div>`, although **div is already closed**.

And more - after you delete some letters and force type the `</br>` - it will move it to the same vertical line as `<div>` stays.

So messed up. :confused: 

Even with another tag `<p>` inside of `<div>`:
![div br 2](https://user-images.githubusercontent.com/24613274/35813314-f5fde780-0a9b-11e8-8382-a6c4f24035d6.gif)

**Comment by usernamehw** [comment]
Never heard of `</br>` tag before 😕

**Comment by octref** [comment]
Think that's working as expected. I see no reason writing a single `</br>` without an opening `<br>`, not mentioning `<br>` is self-closing.
