### ISSUE TITLE
Hidding a Split View does not call setVisible(false) on the view

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#42978]
1. Set a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L150)
2. Using the context menu hide the OPEN EDITORS view in the explorer viewlet, notice the breakopint is not being hit
3. Using the context menu bring back the OPEN EDITORS view, notice the breakpoint being hit

I would expect the setVisible(false) to be called once a view is being hidden.
I have quite some layout optimization code which is depended on the fact if the view is hidden or not. And my optimisations do not seem to work since the view is not aware it is hidden.

**Comment by isidorn** [comment]
I can reproduce this using the exact steps I provided in the original comment

**Comment by sandy081** [comment]
@isidorn As mentioned in comment [here](https://github.com/Microsoft/vscode/issues/42978#issuecomment-365632310) I am disposing the view when it is removed. So I do not think it is required to call setVisible(false) if it is getting disposed.

![image](https://user-images.githubusercontent.com/10746682/36842343-b4788d20-1d4b-11e8-95da-193ed246f305.png)

**Comment by isidorn** [comment]
@sandy081 ok, makes sense, sorry for the confusion. Verified it gets disposed
