### ISSUE TITLE
cannot find module SPDLOG when debugging extension

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#42973]
i have updated the mode modules versions for my extension.

after updating when i run the extension in debugging mode , i get this error.
Activation function of extension doesnt get hit.

Is this really coming from VS Code ? 
![image](https://user-images.githubusercontent.com/8774556/35811227-c2b38de4-0aaf-11e8-97e6-051d4f00e9dc.png)

**Comment by weinand** [comment]
@joaomoreno @sandy081 any clue?

**Comment by sandy081** [comment]
I too see this error on insiders. `spdlog.node` does not exist in the reported location. Not sure who is requesting for spdlog from that location.

@joaomoreno need your help here

**Comment by weinand** [comment]
@shanalikhan most likely this is a caught exception and you have enabled "All Exceptions".
Is this the case?

**Comment by shanalikhan** [comment]
Yes
When i start debugging the extension, and put the breakpoint on very first line of activation function- It doenst get hit instead shows exceptions.
So i have to enable "All Exceptions" in order to view the root cause and got this error.

**Comment by weinand** [comment]
If you have checked "All Exceptions" then it is expected that you break on these kinds of exceptions.
Normally they are handled internally and they represent no problem at all and you would not see them. You can just press the Play button to continue.

But I suggest that you configure your exception options like this:
![2018-02-06_17-14-05](https://user-images.githubusercontent.com/1898161/35870408-e0da25fa-0b61-11e8-9aa3-a53e8bbc23d6.png)
