### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by kencoder97** [Microsoft/vscode#42970]
Some typo in the document.
https://code.visualstudio.com/docs/python/editing#_formatting
It should be [python.formatting.] not  [python.linting.]

![screenshot from 2018-02-05 21-19-56](https://user-images.githubusercontent.com/26746668/35809240-a41847b6-0aba-11e8-843c-6a9ec006d87d.png)

**Comment by gregvanl** [comment]
Thanks for finding this!
Fixed with https://github.com/Microsoft/vscode-docs/commit/9dd2f595c315c7b1bac56912413d9154d3527e19
