### ISSUE TITLE
Typescript: Autocomplete with method name

### ISSUE THREAD

**Issue by arnaudpourbaix** [Microsoft/vscode#42972]
In typescript, autocomplete replaces code when typing `(`  in several cases.

- Version 1.19.3
- Windows 10
- All extentions are disabled (--disable-extensions)

Steps to Reproduce:
1. Create an empty class:
    `export class TestService {    }`
2. Try adding a public method named **start** and hit key **(**
3. Codes replace `start(` by `statusbar()`

statusbar is the first suggestion in autocomplete. Yet, I didn't select it !
Please note that doing the same test without public modifier does work.

This is very annoying, the only way that works reliably is to add a space before **(**, but then, you have to remove it afterward.

**Comment by mjbvz** [comment]
`(` is a commit character for typescript and javascript. Set `"editor.acceptSuggestionOnCommitCharacter": false` to disable this behavior
