### ISSUE TITLE
Setting 'stopOnEntry: true' in launch.json for debugging vscode extension has no effect

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode#42982]
See here for some earlier discussion: https://github.com/Microsoft/vscode/issues/42858 But I'll make this a 'self contained' report.

Version 1.20.0-insider
Commit 9affae559e7b6dd46acfe2ac3123fb0ea87c6615
Date 2018-02-01T06:16:57.002Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Run npm install in attached project [my-new-extension.zip](https://github.com/Microsoft/vscode/files/1696125/my-new-extension.zip)
2. Open the project with code-insiders (also reproducible with stable release Code 1.19.3) 
3. Observe that `stopOnEntry: true' is set in launch.json file. Also hovering over that property gives hover-help suggesting this isn't a silly typo.
4. Press F5 to launch.
5. Observe that the extension host does not get stopped as it should.

Does this issue occur when all extensions are disabled?: Yes. In fact, no extensions are installed in my `code-insiders` install.

**Comment by weinand** [comment]
@roblourens I see the same on macOS.

**Comment by roblourens** [comment]
I'm not sure how useful stopOnEntry is with extensionhost debugging, but you're right that it was broken :)

**Comment by roblourens** [comment]
Fixed in https://github.com/Microsoft/vscode-node-debug2/commit/1d854e76cc14956cd86714c5af36fd28914d7960

**Comment by kdvolder** [comment]
> I'm not sure how useful stopOnEntry is with extensionhost debugging

I tend to agree. Its not very useful when breakpoints register properly and you can stop execution at desired location even in code that executes during early extension activation. However, I have had issues with that in the past and 'stopOnEntry: true' was a workable workaround in some cases. I discovered that 'stopOnEntry' wasn't working while trying to use it again as a workaround for such a problem.

Breakpoints seem to be working fine however in the latest code insiders that I've tried. And so I have little use for it at the moment.

**Comment by nonoroazoro** [comment]
I met the same problem on Mac too, moreover, the break points did't work at all while they worked in the previous version of VSCode (I don't quite remember, maybe 1.18). The behavior is much like this issue: https://github.com/Microsoft/vscode/issues/42858

**Comment by nonoroazoro** [comment]
Here's the record: 
![debug issue](https://user-images.githubusercontent.com/383132/37814136-6bd6b92a-2ea3-11e8-8ec6-4f8473be9c7b.gif)

**Comment by weinand** [comment]
@nonoroazoro after pressing F5 does a new VS Code window opens?

**Comment by nonoroazoro** [comment]
@weinand Yes, the extension did work, but the UI of VSCode debugger is not working.

**Comment by weinand** [comment]
And this problem persists even after a reboot?

**Comment by nonoroazoro** [comment]
@weinand Yes. I tried to re-install the VSCode and remove all of the extensions , check my node, npm and typescript version (8.9.1, 5.5.1 and 2.6.1), still not work.
