### ISSUE TITLE
[json] Default snippets never preseneted

### ISSUE THREAD

**Issue by hipstersmoothie** [Microsoft/vscode#42987]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Type bar.json
2. Key will be suggested as a property hit enter
3. Vscode produces result.json
4. I expected to be given a chance to choose a default snippet, but the editor just puts an empty object. In the current situation i have to type the full key value and then a colon to see the default snippets.

bar.json
```json
{
	"$schema": "./bar.schema.json",
	""
}
```

bar.schema.json
```json
{
	"type": "object",
	"properties": {
		"foo": {
			"required": [
				"id"
			],
			"type": "object",
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"defaultSnippets": [
				{
					"body": {
						"id": "$1"
					}
				}
			]
		}
	}
}
```

result.json
```json
{
  "$schema": "./bar.schema.json",
  "foo": {
    
  }
}
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by octref** [comment]
You opened two issues. I'll mark this as dupliate of #42988.
