### ISSUE TITLE
Debug API / Ask Debugger to Evaluate a given Expression

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#42989]
For a very cool extension I have in mind, I would love to be able to ask the active debugger (if there is an active debug session) to evaluate a given expression and get back the result of that evaluation.

My ultimate goal is to provide a watch-window like pane that visualizes given expressions (like svg, graphs, matrices or tables).

**Comment by weinand** [comment]
At the moment we have no plans to duplicate the Debug Protocol as extension API.
But you can use the `DebugSession.customRequest(...)`API to run any DAP request.

The following code to run the "evaluate" request works for me:

```typescript
'use strict';

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {

        const session = vscode.debug.activeDebugSession;
        if (session) {
            session.customRequest("evaluate", { "expression": "Math.sqrt(10)" }).then(reply => {
                vscode.window.showInformationMessage(`result: ${reply.result}`);
            }, error => {
                vscode.window.showInformationMessage(`error: ${error.message}`);
            });
        }

    });

    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```

To try this:
- create simple "Hello World" extension with yeoman.
- replace the extension.ts with my code from above
- press F5 to launch (and debug) extension
- in new window open a simple node.js program
- press F5 to debug simple program 
- press F1 and type "Hello" and run the "Hello World" extension.

Observe: the result of the expression "Math.sqrt(10)" will be shown in an info notification.

**Comment by hediet** [comment]
Now I see what I did wrong - in order to access local variables, I have to pass a frameId, otherwise I just get "not available". How do I get the frameId of the current frame?

Is there an event that fires when the debugger halts so that I can re-evaluate all my expressions?

**Comment by robe007** [comment]
@weinand I have tried the code that you exposed above and the `const session = vscode.debug.activeDebugSession;` returns **undefined**. I have made a [question](https://stackoverflow.com/q/54817476/2954267) on SO about it. Some ideas?

**Comment by robe007** [comment]
> At the moment we have no plans to duplicate the Debug Protocol as extension API.
> But you can use the `DebugSession.customRequest(...)`API to run any DAP request.
> 
> The following code to run the "evaluate" request works for me:
> 
> ```ts
> 'use strict';
> 
> import * as vscode from 'vscode';
> 
> export function activate(context: vscode.ExtensionContext) {
> 
>     let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
> 
>         const session = vscode.debug.activeDebugSession;
>         if (session) {
>             session.customRequest("evaluate", { "expression": "Math.sqrt(10)" }).then(reply => {
>                 vscode.window.showInformationMessage(`result: ${reply.result}`);
>             }, error => {
>                 vscode.window.showInformationMessage(`error: ${error.message}`);
>             });
>         }
> 
>     });
> 
>     context.subscriptions.push(disposable);
> }
> 
> export function deactivate() {
> }
> ```
> 
> To try this:
> 
> * create simple "Hello World" extension with yeoman.
> * replace the extension.ts with my code from above
> * press F5 to launch (and debug) extension
> * in new window open a simple node.js program
> * press F5 to debug simple program
> * press F1 and type "Hello" and run the "Hello World" extension.
> 
> Observe: the result of the expression "Math.sqrt(10)" will be shown in an info notification.

# @
