### ISSUE TITLE
[json] Don't fill in default value when default snippets are available

### ISSUE THREAD

**Issue by hipstersmoothie** [Microsoft/vscode#42988]
- VSCode Version: Version 1.20.0-insider (1.20.0-insider)
- OS Version: 10.13.3

Steps to Reproduce:

1. Type bar.json
2. Key will be suggested as a property hit enter
3. Vscode produces result.json
4. I expected to be given a chance to choose a default snippet, but the editor just puts an empty object. In the current situation i have to type the full key value and then a colon to see the default snippets.

bar.json
```json
{
	"$schema": "./bar.schema.json",
	""
}
```

bar.schema.json
```json
{
	"type": "object",
	"properties": {
		"foo": {
			"required": [
				"id"
			],
			"type": "object",
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"defaultSnippets": [
				{
					"body": {
						"id": "$1"
					}
				}
			]
		}
	}
}
```

result.json
```json
{
  "$schema": "./bar.schema.json",
  "foo": {
    
  }
}
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by aeschli** [comment]
Ok, thanks.
The defaultSnippets where ignored when looking for a good default value when completing a property.
I fixed it by now also checking the defaultSnippets (with the highest priority). I also changed that if there are more than one snippet (or enum), rather trigger folllow-up code assist and let the user pick the best one.

**Comment by alexandrudima** [comment]
Now I get the following when accepting `foo`:
```json
{
	"$schema": "./bar.schema.json",
	"foo": {
		"id": ""
	}
}
```
