### ISSUE TITLE
VSCode HTML Emmet tab through 

### ISSUE THREAD

**Issue by sivachallapalli** [Microsoft/vscode#42980]
- VSCode Version: 1.19.3
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:

1. Use html emmet:  table>tr*10
2. For me, 9 tr is getting skipped when tabbing through 
[Gif](https://i.stack.imgur.com/KPMiC.gif

![](https://i.stack.imgur.com/KPMiC.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
@gushuro The 9th tabstop gets replaced with `${0}` in this case. Must be a bug in the `addFinalTabStop` function in the `vscode-emmet-helper`

**Comment by jens1o** [comment]
resolved in the next insider release.
