### ISSUE TITLE
Visual Studio Code closes when laptop charger is plugged in or out

### ISSUE THREAD

**Issue by CodeLover254** [Microsoft/vscode#42984]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
jshint|dba|0.10.15
xml|Dot|1.9.2
php-intellisense|fel|2.2.6
file-icons|fil|1.0.7
code-runner|for|0.8.7
beautify|Hoo|1.3.0
easy-icons|jam|0.3.1
python|ms-|2018.1.0
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.1.0
qub-xml|qub|1.2.1
java|red|0.18.1
javascript-typescript|sou|0.0.5

============================================
This has been happening ever since I did my first install in the year 2017. Am using an HP15 Corei3 machine running windows 8.1.

**Comment by mjbvz** [comment]
Does this happen with any other apps, such as chrome?

**Comment by CodeLover254** [comment]
No, it doesn't happen in chrome. Just visual studio code. I have updated the app severally but the behavior is still persistent. I don't understand the relationship between the laptop charger and visual studio code.

**Comment by octref** [comment]
@microsoft/vscode I'm wondering if anyone has any lead.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by CodeLover254** [comment]
[Code__PID__27892__Date__02_14_2018__Time_03_37_23PM__577__Log.txt](https://github.com/Microsoft/vscode/files/1723999/Code__PID__27892__Date__02_14_2018__Time_03_37_23PM__577__Log.txt)
[Code__PID__32408__Date__02_14_2018__Time_03_37_24PM__29__Log.txt](https://github.com/Microsoft/vscode/files/1724000/Code__PID__32408__Date__02_14_2018__Time_03_37_24PM__29__Log.txt)

The crash logs here :-)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
