### ISSUE TITLE
Search exclude

### ISSUE THREAD

**Issue by salc** [Microsoft/vscode#42986]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
goto-documentation|cxf|0.0.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.6
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
html-css-class-completion|Zig|1.16.1

---

In user settings  I have the following search exclude:

```
"search.exclude": {
        "**/.git": true,
        "**/node_modules": true,
        "**/bower_components": true,
        "**/tmp": true
 }

```
but when I make a search of "_" in the entire project (Ctrl-shit+F), VSCode continues to search inside the .git folder.

here's a link to a screenshot:
[https://i.imgur.com/m6DkhHn.png](https://i.imgur.com/m6DkhHn.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Can you check that the "Use Exclude Settings and Ignore Files" button is toggled on (bottom right corner)?

![image](https://user-images.githubusercontent.com/323878/35752446-e01ea914-0810-11e8-8d1e-9877a751c5ca.png)

**Comment by salc** [comment]
no it wasn't toggled. I have never used those hidden fields. 
Don't you think that the button should be ON by default? Maybe it could be a simple check box under the two input fields saying: "Check to disable settings Exclude and Ignore files" 
Anyway, thanks and sorry for the false alarm :-).

**Comment by roblourens** [comment]
It is on by default, so it must have been toggled at some point, maybe on accident...
