### ISSUE TITLE
OS X: "Open in Terminal" doesn't work for me

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4298]
- VSCode 0.10.12-alpha
- OO X 10.11.3

- in the VS Code explorer run the "Open in Terminal" action

Observe: nothing happens

**Comment by jbeckton** [comment]
Same issue on Linux as well. "Open new Terminal" does not work either

**Comment by weinand** [comment]
New versions of iTerm have changed the AppleScript API which broke the VSCode iTerm scripts. I made VS Code smarter in detecting what version of iTerm is available and call either the old `iterm` or a new `itermNew` script.

**Comment by pflannery** [comment]
@joaomoreno 
this PR https://github.com/Microsoft/vscode/pull/3495 resolves the Linux issue where x-terminal-emulator isn't available. 
Fedora 23 is an example where this problem is happening. Using this PR and changing the command to `gnome-terminal` works.

**Comment by bpasero** [comment]
Verified that "Open in Terminal" works for me and opens my terminal. @weinand note that I do not have iTerm installed so you might want to assign this one to someone else?
