### ISSUE TITLE
Feature: Suggest switch to workspace typescript version notification

### ISSUE THREAD

**Issue by csvn** [Microsoft/vscode#42981]
I've had a lot of co-workers where the linting was disabled since they were not running the workspace version (it's required for [`tslint-language-service`](https://github.com/angelozerr/tslint-language-service)), and it's easy to miss if the Typescript version is the same between workspace/VSCode. The bundled VSCode version seems also to often be newer than the workspace version. This can fool users into thinking that newer language features (e.g. string-enums from TS@2.6.0) are available in the project.

As I understand from #30069, it's not possibly to automatically set to workspace version for security reasons.

To mitigate issues and workaround the above issue I am proposing a way for VSCode to more strongly suggest switching from the bundled VSCode version to the workspace Typescript version in a notification. Maybe trough a workspace setting, e.g. `typescript.suggestWorkspaceVersion`, which could display a notification message that **strongly** suggests switching to [workspace version](https://code.visualstudio.com/Docs/languages/typescript#_using-the-workspace-version-of-typescript) of Typescript. 

This could be very useful for projects with older Typescript versions or projects using `tslint-language-service`. Feedback is welcome.

**Comment by mjbvz** [comment]
Closing this do to lack of feedback in the past half year. We used to do this, and it spawned a lot of issue reports where users were confused by the notification
