### ISSUE TITLE
Emmet expansion not work when i copy and paste classname with . (dot)

### ISSUE THREAD

**Issue by hassanbinsafdar** [Microsoft/vscode#42992]
Emmet works great and work well but problem is when i type . and paste any classname in html file tab key does not expand code but when i type it works

**Comment by ramya-rao-a** [comment]
Copy paste doesn't trigger auto-completions in general. You can press `Ctrl+Space` after you paste the text to trigger the auto completions.

**Comment by ramya-rao-a** [comment]
Another option is to use the command `Emmet: Expand Abbreviation`.

**Comment by hassanbinsafdar** [comment]
Emmet: Expand Abbreviation working perfect thanks i just changed settings "emmet.triggerExpansionOnTab": false, to "emmet.triggerExpansionOnTab": true, and its working fine Thanks :) 👍
