### ISSUE TITLE
Javascript code beautifier incorrectly handling array assignment

### ISSUE THREAD

**Issue by jamievicary** [Microsoft/vscode#42995]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Load VS Code
2. Enter text "if (true) [a, b] = [c, d];"
3. Save as "test.js"
4. Beautify (SHIFT+ALT+F)
5. The text is changed to "if (true)[a, b] = [c, d];", deleting the space before the first [

This is incorrect behaviour, since the text inputted in 2 is already well-formatted, and the space before the first [ should not be deleted by the beautifier. Note that this is valid array assignment syntax in ES6.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/21675 to track this upstream
