### ISSUE TITLE
Dragging vscode maximized from one window to another can hide terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#42999]
I think the expected intersection observer events are not being fired.

Tested on Ubuntu 17.10

**Comment by Tyriar** [comment]
Workaround: Hide and show terminal or create a new terminal.

**Comment by Kurtz1993** [comment]
Also happening on Windows.

Here's a quick gif.
![screen](https://user-images.githubusercontent.com/5412470/36277421-762a4f72-1256-11e8-944b-ec002d0a0ba7.gif)

**Comment by Tyriar** [comment]
@Kurtz1993 I suspected this might also be happening, thanks for verifying 😃

**Comment by Tyriar** [comment]
This doesn't appear to happen in the xterm.js demo with Chrome v64, it might be related to either relayout in VS Code or a bug that's been fixed in Chrome that's still present in Electron.

**Comment by Tyriar** [comment]
I think it's the latter, that this is fixed in Chromium. I added a workaround to force the terminal renderer to resume when on layout of a *visible* terminal.
