### ISSUE TITLE
addSelectionToNextFindMatch doesn't respect multi selection

### ISSUE THREAD

**Issue by dorian-marchal** [Microsoft/vscode#42998]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Creates a new document :
```
foo
foo

foo
foo

foo
foo
```
2. Select the first "foo" of each paragraph (with <kbd>Alt + Double click</kbd>).
```
[foo]
foo

[foo]
foo

[foo]
foo
```

3. Trigger `addSelectionToNextFindMatch` (<kbd>Ctrl + D</kbd>).

__Actual:__
```
[foo]
foo

[foo]
foo

[foo]
[foo]
```

__Expected:__
```
[foo]
[foo]

[foo]
[foo]

[foo]
[foo]
```

This is how Atom works (and Sublime Text, too, I think).
It is very helpful to perform complex edit operations to multiple similar code blocks.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
The main difficulty here is that `ctrl+D` is implemented stateless. i.e.

It doesn't know it arrived at:

```
[foo]
foo

[foo]
foo

[foo]
foo
```
via mouse clicking, or via a series of `ctrl+D` (add selection to next match) and `ctrl+K ctrl+D` (move selection to next match).

**Comment by dorian-marchal** [comment]
In fact, I just tested it on Atom and it seems that both editors show the the exact same behavior.
I don't know if it's always been like that. Maybe I imagine things. :smile:

Anyway, it is not a regression when switching from Atom to VSCode, so this issue can be closed, I think.
