### ISSUE TITLE
Move Editor Left / Right actions incosistent when tabs are disabled

### ISSUE THREAD

**Issue by myfonj** [Microsoft/vscode#42997]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299

---

## Steps to Reproduce:
1. Assure `"workbench.editor.showTabs": true`.
2. Open three editors in one group.
3. Switch to the second edtor.
4. Invoke "Move Editor Left" (`workbench.action.moveEditorLeftInGroup`; ctrl+shift+pageUp by default) action once.
5. Invoke "Move Editor Right" thrice.
6. Observe tab movement in Tab Bar (left once, right twice) and Open Editors panel (up once, down twice) without creating new group.
7. Set `"workbench.editor.showTabs": false`.
8. Repeat step 3 - 5.

## Expected result:
Editor moves in Open Editors panel up once and down twice.

## Actual result:
- Editor does not change position from second to first with "Move Editor Left".
- New editor group is created with "Move Editor Right". (As if "Move Editor Into next Group" had been invoked instead.)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@myfonj if tabs are disabled, moving editors within a group would have no visible impact otherwise, that is the reason why we move across groups in that case and no-one has complained so far.

**Comment by myfonj** [comment]
I see, but I slightly disagree: there is the Open Editors panel in the left sidebar.
My report could be reworded into _"How can I move active editor up/down in Open Editors panel with keyboard when tabs are not displayed?"_.

**Comment by myfonj** [comment]
Illustrative gif "Moving settings.json editor back and forth with tab enabled and then disabled":
![vscode-move-editor-left-right-2018-02-06](https://user-images.githubusercontent.com/1761395/35848901-14058376-0b20-11e8-8920-295c41f2ce67.gif)

> (...) that is the reason why we move across groups in that case

But there is a dedicated action with separate hotkey for moving editors across groups, isn't there? 

FMPoW there is very weak excuse for changing actions outcome based on state of completely different ("visual") pref: in this case setting `"workbench.editor.showTabs": true` changes `workbench.action.moveEditorRightInGroup` action to do the `workbench.action.moveEditorToNextGroup` (which is still working) and `workbench.action.moveEditorLeftInGroup` to `workbench.action.moveEditorToPreviousGroup` (which does nothing when active editor is in the first group).

**Comment by bpasero** [comment]
We probably added the other commands for moving editors across groups later and now that we have them I am fine to remove the inconsistent behaviour. This means that people that got used to this behaviour will have to change to the `workbench.action.moveEditorToNextGroup` and `workbench.action.moveEditorToPreviousGroup` commands.
