### ISSUE TITLE
Allow user to disable "Terminal will be reused by tasks, press any key to close it" message.

### ISSUE THREAD

**Issue by gwk** [Microsoft/vscode#42993]
10b14c6
- VSCode Version: 1.20 Insider 3f8cf5311b631c5bc395df1e8b9c795358c1ef80
- OS Version: macOS 10.13.4 beta

Steps to Reproduce:

1. Run a build task that outputs to the integrated terminal. VSCode should display "Terminal will be reused by tasks, press any key to close it" message at the end of the build output.

This message takes up three lines of console output (newlines before and after). When working on a laptop screen with the terminal pane at the bottom, it is proving to be quite annoying. I understand that the message is educational, but having learned how it works I never need to see it again, and I want the real estate back. Moreover, the message is visually distracting when I am looking at long lists of build errors.

Thanks!

**Comment by oriash93** [comment]
Hey, I hope it's ok I took up on this. 
I added an option, true by default, whether to show this message.

**Comment by dbaeumer** [comment]
PRs are always welcome. However the default value for the setting should be `false` to avoid changing the current behavior.

**Comment by oriash93** [comment]
I know, the current behavior is to show the message, that's why it defaults to 'true'

**Comment by dbaeumer** [comment]
Usually we try to avoid using true as the default. So I would opt to have a setting hide which defaults to false. This is more in line with JS falsify values.

**Comment by oriash93** [comment]
Got your point 👍 . I changed it
