### ISSUE TITLE
Consider to not let debug adapters user errors show up in the dev console 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#4299]
Currently debug adapter user errors are treated like fatal exceptions on the VS Code side and show up in the dev console because "developers should understand what is going on". This does not make a lot of sense for this type errors because no developer needs to know them or is interested in them.

The errors reporting through this mechanism are conceptually equivalent to errors reported by the TypeScript transpiler but it would be strange if we would send TypeScript errors to the dev console.

I suggest that we only show errors on the dev console that have the "sendTelemetry" flag set. The errors that have the "showUser" flag set are forwarded to the Notification service without sending them to the dev console.

**Comment by isidorn** [comment]
This is a workbench concept that all globaly handled errors are shown to the user via message service are also logged to the console.
In this scenario you would only want them to be shown in the message service. However we do not have that notion for the errors that are handled globaly by the workbench.
@bpasero or am I missing something?

**Comment by bpasero** [comment]
Yes, we typically rather spam the dev console with anything that ends up in errors land. 

Can you point to the code in debug land that logs these errors? We can maybe add another flag to explicitly bypass the logging to dev console.

**Comment by isidorn** [comment]
Erros from the debug adapter are handled [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/node/rawDebugSession.ts#L82)

**Comment by bpasero** [comment]
And where does it reach our code to print it to the console and user?

**Comment by isidorn** [comment]
My understanding was that because I do not handle this error - but I bubble it up, the workbench will handle it. And workbench handling it means - show it via message service and print to console.
Am I mistaken?

**Comment by bpasero** [comment]
Right. If you want to handle errors for the user, just use the message service and prevent error bubbling?

**Comment by isidorn** [comment]
Makes sense that I can do it here but I still think some errors must bubble up - like the global workbench actions. Since for those I am not interecpting the error.
Though for this case I can do as you suggested.

**Comment by bpasero** [comment]
I think we once had the idea to be able to annotate errors so that we can handle this in one place and not every author has to do it. E.g. to be able to specify options (show to user, show in dev console). We never really took a crack on this, but I am also easy to review such a change if you wanna tackle it.

**Comment by isidorn** [comment]
Yes I can take a look. What is the current place where we handle these global errors?

**Comment by bpasero** [comment]
I think it all goes down to errors.onUnexpectedError and its error handler in there.
