### ISSUE TITLE
Unable to zoom out past default zoom level.

### ISSUE THREAD

**Issue by shurcooL** [Microsoft/vscode#430]
When I tried the very first public release of VCS, I was able to both zoom in and out from the initial zoom.

My personal preferred zoom level is around 90%; I like content to be as dense as possible as long as I can still read the fonts, that way I can fit more windows/information on a screen at at time.

An update from a few months ago changed it so I could only zoom in, but not zoom out past the default zoom level.

Now that the source code is available, I've looked into why that happens and found this comment in [src/vs/workbench/electron-browser/actions.ts#L169](https://github.com/Microsoft/vscode/blob/bff376d1388d40050aaabf9ec96101a427b506de/src/vs/workbench/electron-browser/actions.ts#L169):

```TypeScript
export class ZoomOutAction extends Action {
...
	if (webFrame.getZoomLevel() > 0) {
		webFrame.setZoomLevel(webFrame.getZoomLevel() - 1); // prevent zoom out below 0 for now because it results in blurryness
	}
...
}
```

I'm opening this issue to track this issue (I did not find any existing open issues tracking this specific problem), because I'd really like to see it resolved so I can use 90% zoom level. Thank you!

**Comment by shurcooL** [comment]
FWIW, I was using OS X with a hi-dpi Retina screen and I did not notice any issues with blurryness at 90% level, if I remember correctly. Perhaps it's only visible on non-hi-dpi screens?

**Comment by jel-massih** [comment]
I have standard 1920x1080 and 1920x1200 displays that dont have any noticable blurring at 80-90%

I also prefer working at 90% in many cases.

If there is still a desire to not allow the overall zoom <100%, what about having zooming only affect the editor panel (like Visual Studio and most other text editors)?

**Comment by bpasero** [comment]
This will be possible with the newly introduced and persisted `window.zoomLevel` setting.

**Comment by shurcooL** [comment]
Thank you!
