### ISSUE TITLE
Apply text opacity decoration without setting text color

### ISSUE THREAD

**Issue by grdowns** [Microsoft/vscode#43004]
I'm working on the C++ extension here at Microsoft. One of our features for this release is inactive region colorization, similar to Visual Studio. While we've achieved end to end, there are a couple "nice to have" changes that would make the feature shine more. For modularity's sake I will expound upon just one here.

We would like a way to modify only the opacity of text without modifying other properties. We are using `vscode.TextEditor.setDecorations` to apply a text decoration to the inactive region. `vscode.TextEditor.setDecorations` applies properties filled out in a `vscode.DecorationRenderOptions`. However, this interface does not allow for directly setting the opacity of the text without modifying the other color properties. E.g. supplying `rgba:(150,150,150,0.5)` will set the opacity with the unwanted side effect of changing the color to gray.

Are there other means of setting the text opacity unaware to us? If not, we would greatly appreciate having such a thing implemented to give the user an experience more comparable to Visual Studio.

**Comment by mjbvz** [comment]
As part of #15710, I'd also like to do the same for JS and TS

**Comment by alexandrudima** [comment]
Verified using the following extension:

* `package.json`:
```js
{
    "publisher": "alex",
    "name": "43004",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {
	var dectype = vscode.window.createTextEditorDecorationType({
		opacity: '0.5'
	});
	vscode.window.activeTextEditor.setDecorations(dectype, [
		new vscode.Range(0, 0, 0, 1),
		new vscode.Range(1, 0, 1, 1),
		new vscode.Range(2, 0, 2, 1),
		new vscode.Range(3, 0, 3, 1),
		new vscode.Range(4, 0, 4, 1),
		new vscode.Range(5, 0, 5, 1),
		new vscode.Range(6, 0, 6, 1),
		new vscode.Range(7, 0, 7, 1),
		new vscode.Range(8, 0, 8, 1),
		new vscode.Range(9, 0, 9, 1),
	]);
}
```

![image](https://user-images.githubusercontent.com/5047891/39186306-54dd8b3c-47ca-11e8-9fc4-83ddff7dd4aa.png)
