### ISSUE TITLE
vscode.TextEditor.setDecorations apply to columns

### ISSUE THREAD

**Issue by grdowns** [microsoft/vscode#43008]
Follow-up from #43004. `vscode.TextEditor.setDecorations` takes as its second parameter a `vscode.Range`. `vscode.Range` is an aggregation of two `vscode.Position`'s,  each of which contain a line number and column number.

However, `vscode.TextEditor.setDecorations` discards the column information supplied from the `vscode.Range`. This causes the entire line to be decorated regardless of whether a column is supplied. This is a problem in our context as preprocessor directives in C++ may be preceded by whitespace. In our C++ code we have applied a temporary "fix" which trims the preceding whitespace from the inactive region before determining which lines should be decorated. Thusly, when the user has `"editor.renderWhitespace"` set to `all` or `boundary`, the preceding whitespace does not have any text decorations applied to it as it should.

![2018-02-05-174801_575x257_scrot](https://user-images.githubusercontent.com/35574547/35837761-ccc7e464-0a9c-11e8-94ba-f27445af6eb3.png)

**Comment by alexdima** [comment]
Closing since we now have semantic tokens. Please reopen if this is still an issue.
