### ISSUE TITLE
Prevent hidden class mutations

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4300]
Based on property assignment V8 creates hidden classes for it's objects. However, doing something like `delete this.aProperty` ruins that hidden class and causing the code to be de-optimized. 

Searching for `delete this.\w+;` (as regex) points to @joaomoreno, @bpasero, and @isidorn. Consider replacing such constructs with assigning `null`

**Comment by jrieken** [comment]
<img width="319" alt="screen shot 2016-03-16 at 11 40 23" src="https://cloud.githubusercontent.com/assets/1794099/13809618/e4271384-eb6b-11e5-9abc-9e0e5fef4158.png">

**Comment by bpasero** [comment]
I can start

**Comment by isidorn** [comment]
Forwared to me once you are done
