### ISSUE TITLE
Cannot specify a global problemMatcher in tasks.json

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#43003]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 16.04

My tasks.json looks like this:
```
{
    "version": "2.0.0",
    "command": "make",
    "options": {
        "cwd": "${workspaceRoot}/build"
    },
    "tasks": [
        {
            "label": "target1",
            "group": "build",
            "problemMatcher": {
                "base": "$gcc",
                "fileLocation": "absolute"
            },
        },
        {
            "label": "target2",
            "group": "build",
            "problemMatcher": {
                "base": "$gcc",
                "fileLocation": "absolute"
            },
        }
       ...
    ]
}
```

Because most tasks use the same `problemMatcher`, I'd like to move it to the common section at the top.  According to [tasks.json schema](https://code.visualstudio.com/docs/editor/tasks-appendix), this is a valid thing to do.

However, when I make this change, VSCode notices that the individual task does not have a problemMatcher and tries to help by prompting me to choose one.   If I choose "Continue without scanning the task output", the task gets run without a problem matcher.  If I choose "Never scan the task output", VSCode adds `"problemMatcher": []` attribute to the task, which overrides the global setting.

I could find no way to get this working.

**Comment by dbaeumer** [comment]
@vadimcn the global problem matcher property is for a single global task which is supported in tasks `0.1.0` only. This should be made more clear in the documentation. 

Being able to define a global problem matcher to be used in tasks defined in the tasks sections makes sense and is a fair feature request.

**Comment by dongzhuoer** [comment]
Maybe you can add an explanation is the [docs](https://code.visualstudio.com/docs/editor/tasks) (search "Task properties can also be defined in the global scope")

**Comment by dbaeumer** [comment]
To verify:

```
{
	"version": "2.0.0",
	"problemMatcher": [],
	"tasks": [
		{
			"type": "shell",
			"label": "echo",
			"command": "echo",
			"args": [
				"Hello World",
			],
			
		}
	]
}
```

Shouldn't prompt for a matcher.

**Comment by dongzhuoer** [comment]
![peek 2018-05-29 08-33](https://user-images.githubusercontent.com/15871952/40632566-0b1a6fda-631b-11e8-92a1-85aa4f2e7096.gif)

**Comment by dongzhuoer** [comment]
VSCode 1.23.1 on Ubuntu 17.04, I added `--disable-extensions` option
