### ISSUE TITLE
'workbench.action.files.open' and 'workbench.action.files.openFolder' do not automatically give the new window focus.

### ISSUE THREAD

**Issue by johndebord** [Microsoft/vscode#43005]
- VSCode Version: 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:
1. invoke either 'workbench.action.files.open' or 'workbench.action.files.openFolder'
2. press escape or the arrow keys (nothing will happen because the window doesn't have focus)

The focus is not automatically given to the new window.
This can be troublesome because if I want to navigate the 'open file' or 'open folder' window I have to take my hands off of home-row and click the window with my mouse for it to gain focus.

**Comment by bpasero** [comment]
I cannot reproduce:
* open a folder
* press Ctrl+K Ctrl+O to bring up the "Open Folder" dialog
* pick a folder
* the window has focus (e.g. the editor is focused)

What am I doing differently?

**Comment by johndebord** [comment]
Perhaps start with a blank slate.
Then press Ctrl+k Ctrl+o.
For me, the window that pops up isn't initially in focus.
So I have to click on it to navigate it with my keyboard.

**Comment by bpasero** [comment]
Looks like https://github.com/Microsoft/vscode/issues/40631
