### ISSUE TITLE
Applying a codefix loses the cursor

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#43002]
### Issue Type
Feature Request

### Description

* Type:
```ts
function f() { await 0; }
```
* Move cursor to `await`.
* Click on the light bulb and apply the codefix.
* The cursor is gone. It would be nice if it were still at the position it was before the codefix.

Ideally, there would be a key I could press to enter the lightbulb-menu so I wouldn't have to use the mouse at all.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (f2b21097100fc2fc0e84cc34f453c9a85a49a2bb, 2018-02-02T06:17:03.200Z)
OS version: Linux x64 4.4.0-83-generic

**Comment by mjbvz** [comment]
@andy-ms I'm unable to reproduce this in the VS Code 1.20 main release or in the current insiders. Are you still hitting this?

**Comment by andy-ms** [comment]
Yeah, the cursor is gone the moment I click on the light bulb, and then typing does nothing. I'm on the 2018-02-08 release of vscode insiders.

**Comment by mjbvz** [comment]
Ok, thanks. Yes I still see this when clicking on the light-bulb. When trigging quick fixes with `ctrl`+ `.` the cursor stays in place. Seems like a generic quick fix ui problem
