### ISSUE TITLE
Can't close issue reporter with cmd+w

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#43013]
When I press cmd+w with focus in the issue reporter, I see "File" in the menu bar blink, but the window doesn't close. It should be able to respect these keyboard shortcuts.

Also, there should be a new feature area github tag for the issue reporter.

**Comment by bpasero** [comment]
This is not straightforward, our menu is not fit for anything that is not a Code window currently. Even if we make the "Close Window" entry work with any window, it will not work because "Close Editor" is also enabled and comes first.

**Comment by RMacfarlane** [comment]
This was fixed in a previous iteration
