### ISSUE TITLE
Dark+ theme: CSS changes in color

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4301]
There are minor changes in the coloring of CSS only in Dark+ theme. Open debugViewlet.css, scroll to the end and notice the difference

Now:

![screen shot 2016-03-16 at 12 05 11](https://cloud.githubusercontent.com/assets/1926584/13810316/89809514-eb6f-11e5-948f-ec66038b31d2.png)

Stable

![screen shot 2016-03-16 at 12 05 18](https://cloud.githubusercontent.com/assets/1926584/13810315/85490274-eb6f-11e5-8516-ce20c5f46341.png)

**Comment by aeschli** [comment]
#4191 made that change. It will stay for now.
