### ISSUE TITLE
Line Paste between Files bug

### ISSUE THREAD

**Issue by cpmcgrath** [microsoft/vscode#43012]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Do a Line Copy (Ctrl + c when no selection is made)
2. Navigate to a different file 
3. Paste the Line (Ctrl + v, without any selection)

Expected behaviour:
The Copied Line is pasted above the current line, as it does if you pasted it in the origin file.

Actual behaviour:
It pastes the line at your caret position which could be in the middle of a word.

**Comment by cpmcgrath** [comment]
In Version 1.20.0 This seems to be fixed within a window, but if I have two windows open copy a line from one to another causes the same bug.

**Comment by ddehghan** [comment]
@cpmcgrath i am pretty sure this is not fixed. it still happens in the same file or different file. the core problem is that they are copying the \n. see https://github.com/Microsoft/vscode/issues/61840

**Comment by alexandrudima** [comment]
To the verifier:

Please try empty selection (full line) `ctrl+c`, `ctrl+v` across VS Code windows. This should work now because we write vscode specific data to the clipboard. The same covers multiple cursors (copy with N cursors, paste with N cursors in a different window).
