### ISSUE TITLE
The MAC system has this problem, the indentation line

### ISSUE THREAD

**Issue by 674891229** [Microsoft/vscode#43010]
The MAC system has this problem, the indentation line

![image](https://user-images.githubusercontent.com/20722192/35839952-3962585c-0b2e-11e8-96c5-36015b2d2cdd.png)

**Comment by octref** [comment]
@674891229 What's your OS and VS Code version?

**Comment by alexandrudima** [comment]
@674891229 Are you using `workbench.zoomLevel`? Does this reproduce when using `View > Reset Zoom` ?
