### ISSUE TITLE
Git: Staging changes results in unintended UNIX file mode changes (0755 to 0644)

### ISSUE THREAD

**Issue by deoren** [Microsoft/vscode#43014]
### Visual Studio Code

- Version 1.19.3
- Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
- Date 2018-01-25T10:36:34.867Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64
- OS Version: Windows 10

### Git for Windows

`$ git --version`
```
git version 2.16.1.windows.2
```

## Steps to Reproduce

1. Clone a repo with scripts that have the UNIX execute bit set
1. Modify a script that previously had the execute bit set
1. Use the git diff UI to stage content
1. Run git diff --staged and observe how the file mode has changed
    ```
    old mode 100755
    new mode 100644
    ```

Does this issue occur when all extensions are disabled?: Yes

## Attempts to reproduce with other tools

I tested with Notepad++ and `git add FILE` and again with Atom Editor using its support for staging content. Neither reproduced the issue.

**Comment by joaomoreno** [comment]
What happens if you run `git diff` after step 2? Did the file already lose the executable bit then?

**Comment by deoren** [comment]
> @joaomoreno: What happens if you run git diff after step 2? Did the file already lose the executable bit then?

Thanks for the follow-up. I will retest and post back soon.

**Comment by deoren** [comment]
I tested on a completely different system with `core.filemode=false` set both in global and local configuration files. On that system I could not reproduce.

I will test on the original system later today and report back then. I will also recheck the configuration settings.

I'm also running the version of Git for Windows just released (`git version 2.16.1.windows.3`), so I'll test both versions on the original system to see whether the new version might have something to do with the difference in behavior I'm seeing.

**Comment by deoren** [comment]
I was able to reproduce the behavior on the original system.

## Environment

- Windows 10 Version 1703
- Visual Studio Code Version 1.19.3
    - Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
    - Date 2018-01-25T10:36:34.867Z
    - Shell 1.7.9
    - Renderer 58.0.3029.110
    - Node 7.9.0
    - Architecture x64
- Git for Windows version 2.16.1.windows.2
- Extensions (normally) enabled
    - Docker
    - GitLens
    - PowerShell
    - Python
    - reStructuredText
    - SVN
- `core.filemode=false`
    - set in local config
    - set in global config

## How I reproduced the behavior

With two monitors, Visual Studio Code (VS) on one side and a Git Bash (GB) window on the other, here is what I did:

1. Modified Visual Studio Code shortcut to use `--disable-extensions`
1. Launched Visual Studio Code
1. (VS) Modified content (removed a comment block of 6-7 lines)
1. (VS) Hit Save
1. (GB) Ran `git diff`, found no mention of a filemode change
1. (GB) Ran `git add .` (from Git Bash)
1. (GB) Ran `git diff --staged`, found no mention of a filemode change
1. (GB) Ran `git reset HEAD --hard`
1. (VS) Modified content again (same changes)
1. (VS) Hit Save
1. (VS) I clicked on the red gutter decoration and it brought up the CodeLens UI to stage or unstage the change
1. (VS) I reverted the change
1. (GB) I found no mention of a filemode change when running `git diff` or `git diff --staged` (which is as I expected, no changes were present)
1. (VS) I repeated my modifications
1. (VS) I staged the change
1. (GB) Ran `git diff --staged` and found a filemode change

At this point I see that Visual Studio Code 1.20.0 has been released and I also have yet to upgrade Git for Windows on this box. I start by upgrading VSC and see if the behavior remains. I'll then upgrade Git for Windows and test yet again.

**Comment by deoren** [comment]
Reproduced using Visual Studio Code 1.20.0 and Git for Windows version 2.16.1.windows.2. Going to upgrade Git for Windows and see if the problem remains.

**Comment by deoren** [comment]
I upgraded Git to version 2.16.1.windows.3 and the problem still remains.

**Comment by deoren** [comment]
Worth noting (from original system):

`$ ls -l`
```
total 13
drwxr-xr-x 1 deoren 197121    0 Feb  4 00:22 buildenv/
-rw-r--r-- 1 deoren 197121  116 Jan 28 08:44 README.md
-rwxr-xr-x 1 deoren 197121 6358 Feb  7 22:47 release_build.sh*
```

`$ git diff --staged`
```
diff --git a/tools/release_build.sh b/tools/release_build.sh
old mode 100755
new mode 100644
index cfd613e..72eb73b
--- a/tools/release_build.sh
+++ b/tools/release_build.sh

CONTENT HERE
```

The `ls` command shows that the execute bit is in place for the `release_build.sh` script, but `git diff` shows that the file mode has changed (or is it instead showing that the index entry has changed?).

When I tried to reproduce the problem on a different Windows 10 Version 1703 system earlier I may have only relied on the output of `ls -l` to indicate that I couldn't reproduce the problem, so I'll try again on that second system and this time (now that I read your directions more closely) double-check the results with `git diff` to confirm the filemode change.

**Comment by deoren** [comment]
I checked the second system that I reported results for earlier (https://github.com/Microsoft/vscode/issues/43014#issuecomment-363829775) and found in the commit log (`git diff HEAD^..HEAD`) where the filemode change took place (even if `ls -l` does not show it).

In short, I reproduced on both systems.

**Comment by joaomoreno** [comment]
Can you use the Command Prompt instead of the Git Bash to try to reproduce this?

**Comment by deoren** [comment]
You mean substitute each place where I used Git Bash with the Command Prompt instead? Sure, I can do that.

Is there anything particular you would like to have done differently, any more detail on a specific step?

**Comment by joaomoreno** [comment]
No. I'd just like to understand where indeed does the bit actually changes. VS Code doesn't manipulate the Git repository. It spawns `git add`. So, it doesn't make much sense that you wouldn't be able to reproduce without VS Code in the picture.

**Comment by deoren** [comment]
Using the command prompt, I:

1. Ran `git add .` from the working directory.
1. Ran `git diff --staged`, found no filemode changes. 
1. Ran `git reset path\to\file`
1. Ran `git add --patch` and staged the hunk (only the one, as I tested before)
1. Ran `git diff --staged`, found no filemode changes.

**Comment by deoren** [comment]
I forgot to note this in the last comment, but I repeated the steps via VSC and was able to reproduce the problem again using the previously provided steps (https://github.com/Microsoft/vscode/issues/43014#issuecomment-363997448). 

Is there a way to turn on logging of `git` activity? Would something like Process Explorer or Process Monitor show the `git add` calls from VSC?

**Comment by deoren** [comment]
After I wrote that, I realized that there is an OUTPUT panel that collects debug log info. I went to the OUTPUT tab and here is the git calls that I found.

When I modified the file and hit save, these were the entries recorded:

```
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...origin/master
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
```
and then when I used the gutter decoration + CodeLens to stage the change, this was recorded:

```
git show HEAD:tools/release_build.sh
git hash-object --stdin -w --path tools/release_build.sh
git update-index --cacheinfo 100644 7cbde288e70ae71b4e35389ea4fe3c185bc77421
 tools/release_build.sh
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...origin/master
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
git show :tools/release_build.sh
git show HEAD:tools/release_build.sh
git show :tools/release_build.sh
```

I am going to guess that the `git update-index` call is responsible for modifying the filemode, but that's all it is on my part, a guess. The other commands appear to only be used for read-only output, whereas the `update-index` call looks to be a read-write command.

**Comment by joaomoreno** [comment]
> and then when I used the gutter decoration + CodeLens to stage the change, this was recorded:

Can you show me in a screenshot what action you clicked?

**Comment by joaomoreno** [comment]
Nevermind, I now went back to your original comment as I see you mentioned:

> Use the git diff UI to stage content

Remember to send screenshots in the future, it's just much easier for me to understand what exactly you are talking about.

**Comment by deoren** [comment]
> @joaomoreno: Remember to send screenshots in the future, it's just much easier for me to understand what exactly you are talking about.

Will do.

**Comment by joaomoreno** [comment]
Don't get me wrong, it's a great bug catch! I just got a bit lost in all the information.

**Comment by deoren** [comment]
@joaomoreno Understood. I opted for verbose detail vs making you hunt for it, but I can see how screenshots would have helped make it all come together. I'll try to remember to include those in the future.

Thanks for the work on this. Will tomorrow's Insider build contain the fix? If so, do you wish to have any feedback from a follow-up test or are you confident that the root cause has been found and fixed?

**Comment by deoren** [comment]
@joaomoreno As expected, it looks like the problem is resolved.

## Output from making changes to a Bash script 

... and then using CodeLens to stage them:

```
git show HEAD:tools/release_build.sh
git hash-object --stdin -w --path tools/release_build.sh
git ls-tree -l HEAD -- tools/release_build.sh
git update-index --cacheinfo 100755 70fe819b248bf77cdbcde6155d898bd2a1e4a037
 tools/release_build.sh
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...origin/master
git show :tools/release_build.sh
git show HEAD:tools/release_build.sh
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
git show :tools/release_build.sh
git hash-object --stdin -w --path tools/release_build.sh
git ls-tree -l HEAD -- tools/release_build.sh
git update-index --cacheinfo 100755 a9f1fc797195bc20637c90cabdd73b504e0b1562
 tools/release_build.sh
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git show :tools/release_build.sh
git show :tools/release_build.sh
git rev-list --left-right master...origin/master
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
git show :tools/release_build.sh
git hash-object --stdin -w --path tools/release_build.sh
git ls-tree -l HEAD -- tools/release_build.sh
git update-index --cacheinfo 100755 2c9e26ba2e405e1855322e210a1073b65a850231
 tools/release_build.sh
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...origin/master
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
git show :tools/release_build.sh
git show :tools/release_build.sh
git show :tools/release_build.sh
```

## Output from making changes to a Markdown file

and then using CodeLens to stage them:

```
git show :BUILDS_README.md
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...origin/master
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
git show HEAD:BUILDS_README.md
git hash-object --stdin -w --path BUILDS_README.md
git ls-tree -l HEAD -- BUILDS_README.md
git update-index --cacheinfo 100644 61ab9b8bd43a2448406eb57e19954ac1749b25c6
 BUILDS_README.md
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...origin/master
git show :tools/release_build.sh
git show :BUILDS_README.md
git show HEAD:BUILDS_README.md
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
git show :BUILDS_README.md
```

## Results

0644 set for non-executable file-type, 0755 for executable file-type. Nice!

Thanks again for fixing this.
