### ISSUE TITLE
On macOS with `editor.find.seedSearchStringFromSelection: false`, external command-e doesn't populate global search string

### ISSUE THREAD

**Issue by koliyo** [Microsoft/vscode#43019]
- VSCode Version: Version 1.19.3 (1.19.3)
- OS Version: macOS 10.12.6 (16G1212)

The standard mac "Use Selection for Find" (Command-E) shortcut works inside VS Code with `editor.find.seedSearchStringFromSelection: false`. However it does not work with the global "Find in files" when using a search-selection from an external application.

Steps to Reproduce:

1. Set `editor.find.seedSearchStringFromSelection: false`
2. Go to an external application, eg Terminal.app
3. Select some text
4. Press `cmd-E`
5. Switch to VS Code
6. Press `cmd-shift-f`

Expected result
The search string should contain the external selection from terminal.

Note: It does work for local search within a file. When swiching back from terminal to VS code the local file search filed is populated with the external string. But not the global "Find in files"

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
This was implemented in 1.20. It will be released in a few days, or try it in Insiders now.

You'll just need to set `search.globalFindClipboard`
