### ISSUE TITLE
Terminal can not use.

### ISSUE THREAD

**Issue by chunjine** [Microsoft/vscode#43018]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
tslint|eg2|1.0.24
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7

---

Steps to Reproduce:
Terminal can not use. can not input, no response.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Can you post a screenshot of the terminal and paste your settings.json file in?

**Comment by chunjine** [comment]
It works today when my computer restarted.
tks.
