### ISSUE TITLE
Cursor beyond EOL with arrow keys

### ISSUE THREAD

**Issue by mWaltari** [Microsoft/vscode#43025]
- VSCode Version: 1.19.3
- OS Version: Win10x64

Steps to Reproduce:

Cursor won't go beyond EOL which makes cursor very jumpy. some people may have used to that, I admit that. If one is used to editor where Cursor goes freely beyond EOL, jumpy cursor is confusing.

Attached animation from Text Editor Pro 
![cursorbeyondeolgif](https://user-images.githubusercontent.com/4082975/35852271-1f687206-0b33-11e8-852a-a17ff263daaa.gif)

**Comment by octref** [comment]
#37007
