### ISSUE TITLE
IntelliSense Unknown Property - `speak: none;` for sass

### ISSUE THREAD

**Issue by zigang93** [Microsoft/vscode#43022]
- VSCode Version: 1.19.3
- OS Version: macos 10.13.2

What happen: 
vscode show warning sign for `Unknown Property - speak: none;`

![screen shot 2018-02-06 at 4 50 58 pm](https://user-images.githubusercontent.com/11520821/35849843-f3a68c0e-0b5d-11e8-9fa3-14aee821ae3c.png)

it should not a unknown property.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
From what I can find out, 'speak' is not supported by any browser.

**Comment by zigang93** [comment]
it already support on chrome.. but not in firefox yet.. 
maybe in future will be updated? but can we just remove the warning?

check here: 
http://www.cssportal.com/css-properties/speak.php
