### ISSUE TITLE
Settings editor should not retain view state

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#43023]
Steps to Reproduce:

1. scroll the settings editor to the end
2. close it
3. reopen it

=> the right hand side now looks almost empty

Imho we should just not save any view state for the settings editor after it closed.

![flicker_chrome58](https://user-images.githubusercontent.com/900690/35851025-ffde24be-0b26-11e8-859d-dee3788cef32.gif)

**Comment by sandy081** [comment]
This is true for all files and settings file is also same. There were users who want to retain the state like cursor etc when reopen the editor.

So closing this as wont fix
