### ISSUE TITLE
Minor highlighting issue with typescript

### ISSUE THREAD

**Issue by thupi** [Microsoft/vscode#43021]
- VSCode Version: 1.19.3 (1.19.3)
- OS Version: macOS High Sierra - 10.13

Steps to Reproduce:

1. Create a .ts/.tsx file in vscode.
2. Type `export { Something as default } from 'something';`.

Now you shound see default highlighed with blue. However, if one would want to do it the other way arround, `export { default as Something} from 'something'`, then it highlights the text as expected :-)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/569 to track this upstream
