### ISSUE TITLE
Markdown editor scrolls away cursor location

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#43028]
- clone https://github.com/Microsoft/node-jsonc-parser
- open `README.md` in preview mode
- edit comment in getNodeValue (line 193)
- after an editing pause, the editor scrolls away and the cursor is no longer visible. Typing scrolls it back

**Comment by aeschli** [comment]
![markdown-jump2](https://user-images.githubusercontent.com/6461412/35853776-c476d936-0b2e-11e8-95b0-02239693d074.gif)

**Comment by mjbvz** [comment]
I believe this was fixed by the new markdown preview -> editor scroll sync logic. Let me know if you still see this
