### ISSUE TITLE
print statement is highlighted as red 

### ISSUE THREAD

**Issue by s1ssagar** [Microsoft/vscode#43024]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rails|bun|0.3.0
solargraph|cas|0.12.0
vscode-eslint|dba|1.4.5
vscode-html-css|ecm|0.2.0
Go|luk|0.6.73
python|ms-|2018.1.0
Ruby|reb|0.16.0
vscode-icons|rob|7.19.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Any print statement is showing as error
![screenshot from 2018-02-06 14-52-25](https://user-images.githubusercontent.com/13457095/35851235-64d64128-0b4d-11e8-86dd-8195b022c846.png)

2.

Reproduces without extensions: Yes/No

**Comment by noonedeadpunk** [comment]
The same thing for me. It appeared just after update of python extension to 2018.1.

PS: using print() function doesn't help, as pylint still complaining
![Screenshot](https://i.stack.imgur.com/mzv20.png)

**Comment by evanwang22** [comment]
I'm observing the same despite having `print-statement` explicitly disabled in a .pylintrc file in the directory of the project I'm editing

![screen shot 2018-02-06 at 3 50 27 pm](https://user-images.githubusercontent.com/1356938/35883725-42c457f6-0b56-11e8-9426-45e7c1592b22.png)

OS Version: macOS Sierra 10.12.6
VSCode Version: Version 1.19.3 (2018-01-25T10:20:43.015Z)

**Comment by singh5** [comment]
Unfortunately I am having the same problem, despite the fact that I am using print statements correctly. Although this issue doesn't stop me from running my code, I do think it is a little annoying. 

![image](https://user-images.githubusercontent.com/5952868/35889180-1e18d076-0b60-11e8-991e-04ebfdceb9a9.png)

OS: Ubuntu 16.04 LTS

VSCode:
- Version 1.19.3
- Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
- Date 2018-01-25T10:32:23.601Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

Pylint:
- pylint 1.8.2, 
- astroid 1.6.1
- Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
- [GCC 5.4.0 20160609]

Hope this helps!

**Comment by zerkms** [comment]
To be fair - it's how `pylint` behaves, VS Code and the python extension just mark whatever pylint marked as a linting error.

**Comment by octref** [comment]
@DonJayamanne FYI 

Please report this issue to https://github.com/Microsoft/vscode-python.

**Comment by noonedeadpunk** [comment]
Thanks, created bug in vscode-python: https://github.com/Microsoft/vscode-python/issues/722
