### ISSUE TITLE
Graying out the "launches" section in Workspace configuration is confusing

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#43033]
1. Open the workspace settings editor
2. Have a "launch" section

Notice how this section is grayed out.
@sandy081 when we talked you explained that you are graying out all non "settings" area since this UX is very settings specific.
However the issue is that it is hard to get to these workspace configurations in any other way. And that most users will discover workspace configuraitons through the settings UX.
Due to that I believe it is not the smartest idea to gray out the "launch" section. It makes sense to only gray out those parts which the user should not never edit manually.

fyi @weinand

**Comment by sandy081** [comment]
@isidorn I do not think users go to settings editor to configure workspace launches. I think the flow is

- Go to Debug view, and find some UX there to configure workspace launches, which should open the workspace configuration file.

- Have a command to configure workspace launches, which should open the workspace configuration file.

Same is true with workspace extension recommendations.

**Comment by isidorn** [comment]
@sandy081 I doubt that most users think as you assume because both me and @weinand as VS Code users followed the same train of thought:
"debug is in workspace confgurations" -> "how do I get there the fastest?" -> "oh yes I open the settings"

imho most users will also follow this train of thought.

**Comment by weinand** [comment]
In addition, user-level launches are available via the same flow. And there nothing is greyed out.

**Comment by sandy081** [comment]
> @sandy081 I doubt that most users think as you assume because both me and @weinand as VS Code users followed the same train of thought:
"debug is in workspace confgurations" -> "how do I get there the fastest?" -> "oh yes I open the settings"

I think you have a valid issue here, but the solution you proposed is implementation driven. IMO as a user how can I guess launches are in Settings editor (which was never the case till now)? We do not show launches in Settings editor in case of Single folder case. Does not it is inconsistent? 

> In addition, user-level launches are available via the same flow. And there nothing is greyed out.

There is a difference, User level launches are inside settings, not outside. 

I am assuming we are confused with the terminology here. The file in which `Folders`, `Settings`, `Launches` and `Extensions Recommendations` (in future may be `Tasks`) is called `Workspace Configuration` file. It's the Workspace Configuration file that has the workspace Launches. Workspace settings are nothing to do with workspace launches. I am not sure if I would like to have Settings editor to be the one place to configure all (Folders, Launches...).

As a user, I would expect some UX help in Debug viewlet to configure Workspace launches by opening the Workspace configuration file.

**Comment by isidorn** [comment]
@sandy081 yes and as a user you have some help, debug dropdown shows an action "Add Config Workspace" which nicely opens the workspace configuraiton file. This is how the user is introduced to this concept.
Afterwards my assumption is that he will figure out, "oh this is a workspace configuration file" and then follow the same train of thought as me and @weinand 

Also why does the workspace configuration file have the same line "Place your settings here to overwrite user settings" since this is a configuration file, and not a settings file?

**Comment by sandy081** [comment]
Good point! that is a bug in IMO. When user opens the workspace configuration file, that line should not be there.. just like not greying out.
