### ISSUE TITLE
Alt + Click to open link doesn't work

### ISSUE THREAD

**Issue by epoberezhny** [Microsoft/vscode#43034]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
haml|kar|1.1.0
Ruby|reb|0.16.0

---

Steps to Reproduce:

1. Enable `Selection -> Use Ctrl + Click for Multi-Cursor`
2. Try to open link in text editor or terminal with `Alt + Click`. It doesn't work :(

But if you choose `Use Alt + Click for Multi-Cursor` and try to open link by `Ctrl + Click` it works perfect.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This actually works now, I think this was fixed as part of another issue.

Note that you might also be having an OS-level conflict. I'm running on Ubuntu 17.10 which uses win+mouse to move the active window, on most Linux distros it is alt+mouse in which case alt+click won't work by design.

**Comment by epoberezhny** [comment]
Thanks! Yes, it's an OS-level conflict. Sorry, I'm new to Ubuntu and its shortcuts.
