### ISSUE TITLE
VS Code hangs with lldb + ipython

### ISSUE THREAD

**Issue by roversch** [Microsoft/vscode#43035]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.6

---

Steps to Reproduce:

1. Create a 'fresh' `launch.json`.
2. Launch ipython.
3. Pick `(lldb) Attach` from the debugging drop-down menu.
4. Run Python script from ipython, lldb stops at breakpoint in C++ code, as expected.
5. Unable to `Step` or `Continue` from the debugging menu. Have to hit `Disconnect` twice to disconnect.

After this, Ipython is still running, but unresponsive. I have to 'Force quit' it from the Activity Monitor (process that needs to be killed is called `lldb-mi`).

Reproduces without extensions: Yes (with `cpptools` of course)

**Comment by weinand** [comment]
Please file this issue against the debugger you are using.

**Comment by roversch** [comment]
@weinand This does not happen with `lldb` from the command line, and since it is the `lldb-mi` process (like MIEngine) and not `lldb` it made me think the problem lies with VS Code.

**Comment by weinand** [comment]
VS Code has no "lldb-mi" process. This is part of the cpptools extension.
The only debugger extension built into VS Code is the Node.js debugger.

**Comment by roversch** [comment]
I see. I'll migrate this issue to the repo of the extension, then. Thanks for the feedback!
