### ISSUE TITLE
Ctrl + Shift _ o does not show all methods in my controller

### ISSUE THREAD

**Issue by paamonim** [Microsoft/vscode#43038]
When I try to see all methods in my controller, I get only a partly list, some methods are not shown eventhough they are there!

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
Ruby|reb|0.16.0
highlight-matching-tag|vin|0.4.4
simple-ruby-erb|vor|0.2.1
![inkedcapture_li](https://user-images.githubusercontent.com/8426465/35863217-aeaff97a-0b56-11e8-91fc-d9695a6aa7b6.jpg)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please file this issue against your ruby extension
