### ISSUE TITLE
Auto indentation fails with javascript functions

### ISSUE THREAD

**Issue by lordgreg** [Microsoft/vscode#4303]
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.3

Steps to Reproduce:

1. Write a JS function like this:
```
   .run(function (Config) {
    // some code here
    });
```
2. press alt+shift+f
3. Result:
```
 .run(function(Config) {
    // some code here
  });

```
4. The whitespace between `function` and `(Config)` part gets deleted, which leads to our linter crying!
5. Expected result:
```
 .run(function (Config) {
    // some code here
  });

```

Bug.

**Comment by dbaeumer** [comment]
VSCode 0.10.12 will offer a setting for this:
```json
	"typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": true
```

**Comment by lordgreg** [comment]
@dbaeumer isn't that something that VSCode should find out from linterfiles? So for example if we have eslint enabled and the option ` "space-before-function-paren": [2, "always"]` exists, the auto-indent shouldn't delete the space?
