### ISSUE TITLE
[Feature Request] Renaming a folder/file should be mirrored in code

### ISSUE THREAD

**Issue by iulia-codes** [Microsoft/vscode#43031]
**Use case:**

folder1 and index.ts on the same level

```
/folder1
   FileFromFolder1.ts
index.ts
```

Following code in `index.ts`

`import './folder1/FileFromFolder1';`

Action: rename `folder1` to `folder2`
**Expected:** all the places in the code where `folder1 `is referenced automatically update to `folder2`.

**Comment by mjbvz** [comment]
Duplicate of #19439
