### ISSUE TITLE
Feature request - Keybindings Shortcuts - filter source:user

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#43037]
- VSCode Version: 1.20.0-ins
- OS Version: win7x64

In `Keyboard Shortcuts` we have a column called "**Source**".

How about to create a filter called "source:user", so as "source:default", etc... ?

![image](https://user-images.githubusercontent.com/24613274/35862775-7a4e0b00-0b55-11e8-8b1a-141e2a5afb52.png)

**Comment by shobhitchittora** [comment]
@sandy081 any code-pointer to start on this?

**Comment by sandy081** [comment]
@shobhitchittora Here it is - https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/common/keybindingsEditorModel.ts#L91

**Comment by ergun1017** [comment]
hey! @shobhitchittora are you working on this?

If not, I can take this.

**Comment by shobhitchittora** [comment]
@ergun1017 I've already started on this. Thanks for asking though.😇

**Comment by shobhitchittora** [comment]
@sandy081 sumitted a PR here. Care to comment / review. 😇
