### ISSUE TITLE
c# referencesCodeLens ain't _work _when _working _with _workspaces

### ISSUE THREAD

**Issue by alwalide** [Microsoft/vscode#43032]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
bracket-pair-colorizer|Coe|0.10.14
supersharp|cra|0.1.4
tslint|eg2|1.0.24
code-runner|for|0.8.7
vscode-firefox-debug|hbe|1.1.0
beautify|Hoo|1.3.0
path-autocomplete|ion|1.8.1
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
ng-bootstrap-snippets|ktr|1.0.0
vscode-todo-parser|min|1.9.1
mssql|ms-|1.3.0
csharp|ms-|1.13.1
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|4.1.0
material-icon-theme|PKi|3.2.2
csharp2ts|raf|0.0.21
code-settings-sync|Sha|2.8.7
open-in-browser|tec|1.1.0
bootstrap4-vscode|the|3.0.0
quokka-vscode|Wal|1.0.96
html-css-class-completion|Zig|1.16.1

if working with c# projects (folders) referencesCodeLens  works perfectly, but as soon as I save multiple folders to be as workspace it disappear. 

---

Steps to Reproduce:

1. save multiple folders as workspaces 
2. open that workspace and try to find any referencesCodeLens

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by alwalide** [comment]
Oh right that was so obvious. Thank you for using gentle words.
