### ISSUE TITLE
c# ref syntax highlighting broken

### ISSUE THREAD

**Issue by CCludts** [Microsoft/vscode#43040]
- VSCode Version: 1.19.3
- OS Version: Windows10 pro x64

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/18717967/35865371-9dd0485a-0b54-11e8-9b1b-92daa56552a8.png)
![image](https://user-images.githubusercontent.com/18717967/35865619-479b26b6-0b55-11e8-8b47-8e07251c9bd3.png)

1. type 'ref' after an equality sign, or other operators (eg ||, &&, |, &, *, +, -)
2. syntax will be highlighted always, even when ref is the start of a symbol/variable name
3. not dependent on any color theme or extension installed

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by aeschli** [comment]
I'm not able to reproduce this in the latest build:
![image](https://user-images.githubusercontent.com/6461412/35924944-b95c6f60-0c24-11e8-89f1-5cd87289e945.png)

If you still see this (try https://code.visualstudio.com/insiders/), please paste your sample as well.

**Comment by CCludts** [comment]
The bug also shows in an empty c# file, just like your screenshot.
Seems like it's fixed in the latest insiders build though, since I cant reproduce it there.
