### ISSUE TITLE
Sorting of menu groups

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#43045]
Steps to Reproduce:

1. Create an extension with yeoman
2. Play around with navigation@x 

Here's the relevant part of my package.json:
   ``` "contributes": {
        "menus": {
            "commandPalette": [
                {
                    "command": "extension.createNewFolders"
                }
            ],
            "explorer/context": [
                {
                    "command": "extension.createNewFolders",
                    "group": "navigation@3"
                }
            ]
        },
        "commands": [
            {
                "command": "extension.createNewFolders",
                "title": "New Folders From Path"
            }
        ]
```

The problem is that the number you set in navigation@x doesn't seem to produce predictable results at all.

For example, if I set 'navigation' or 'navigation@3' I'll get the following result, depending on whether I opened the context menu on a folder or a file:

![group_ordering_low](https://user-images.githubusercontent.com/15158320/35868422-bb0d3808-0b5c-11e8-8b27-8d63b9b53027.png)

If I set 'navigation@10' I'll get the following result. Note how this time the ordering is different when the context menu is launched on a folder:
![group_ordering_high](https://user-images.githubusercontent.com/15158320/35868458-db1359e8-0b5c-11e8-8a5e-ac85b0672d13.png)

I'd like my extension to appear just below the 'New Folder' entry or at least prevent it from appearing as the very first element in the list.

**Comment by bpasero** [comment]
@isidorn only today I found out that for commands you can add "@<some number>" to further control the order within a group. We should maybe adopt that for our commands in the explorer so that extensions can contribute commands between other commands (by adding some gaps for them).

**Comment by isidorn** [comment]
@bpasero but I already contribute the order for each command [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileActions.contribution.ts#L176)
It feels strange to me to now change all the commmands to add the group@order 
What I would expect is that in a central place commands by extensions are given an order based on the number contributed after the @ in their group. @jrieken thoughts?

**Comment by jrieken** [comment]
I'd say it needs proper documentation. Also, I wouldn't use 10, 20, 40 but 1, 2, 3 etc.

**Comment by isidorn** [comment]
@jrieken we use 10, 20, 40 to leave gaps between commands so extensions or us could add additional commands in between.

I could change them to all be single digit but not sure if that would be a breaking change?
@bpasero If we decide to do that should I also change the order of the editor title commands?

**Comment by jrieken** [comment]
> we use 10, 20, 40 to leave gaps between commands so 

@isidorn that only gives you 9 gaps and then you need to do things like 10.1, 10.2. So, you could start like that, e.g 1,2,3 and have 1.1 etc

**Comment by bpasero** [comment]
I think we should not change it unless there is a convincing reason. Changing it will break the order of every contributed action from extensions, no?

**Comment by isidorn** [comment]
@bpasero yes changing it will break extensions.
@jrieken your suggestion makes sense, wish I have done it from day one, now it feels a bit too late due to @bpasero point
