### ISSUE TITLE
Extension API: Suggestion: Ability to control selection and collapse state of explorer views

### ISSUE THREAD

**Issue by joelday** [Microsoft/vscode#43043]
As a developer, having registered a TreeDataProvider as an explorer view, I would like the ability to reveal nodes, change the collapse and selection state of nodes, etc. via commands or user actions in the workspace and editors.

Allows for implementation of features similar to "explorer.autoReveal"

Thanks!

**Comment by sandy081** [comment]
`reveal` API is being tracked here #30288. One of the use cases behind this api is auto reveal. If your request for this, I would mark this as a dup, otherwise please update your requirements for the specific API and the use case. Thanks.

**Comment by joelday** [comment]
@sandy081 The only requirement that I wasn't able to find requested was for the ability to control the expanded/collapsed state, independent of reveal.

**Comment by sandy081** [comment]
@joelday May I know your use case behind this requirement?
