### ISSUE TITLE
PHP Debugger not working

### ISSUE THREAD

**Issue by InKiev** [Microsoft/vscode#43041]
### Issue Type
Bug

### Description

1. Open a PHP file.
2. Add breakpoint
3. Run debugger

### Expected results

Debugger stops at breakpoint.

### Additional info
My OS has Insiders and stable, stable works perfectly, I've tried to re-install Insiders and it didn't work, I've tried to re-install the extension, it didn't work either, has been about two weeks since the last time debugger worked in Insiders.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (42cef1e36517ec4c06ef4e9bf5d57be30d287cad, 2018-02-06T02:30:51.952Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.89GB (1.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.24.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-uriencode|die|0.0.1
githistory|don|0.4.0
gitlens|eam|7.5.10
php-debug|fel|1.12.1
code-runner|for|0.8.7
php-symbols|lin|2.1.0
vscode-docker|Pet|0.0.24
vscode-icons|rob|7.19.0
vscode-open-in-github|ziy|1.3.1

(4 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by octref** [comment]
@felixfbecker FYI
