### ISSUE TITLE
JavaScript `var` and `const` multi-line defintions not coloured.

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#4304]
- VSCode Version: 0.10.11
- OS Version: Microsoft Windows [Version 10.0.10586]

Steps to Reproduce:

Enter the following code in a ECMA/JS file:

```javascript
var foo = 1,
    bar = 2;
const FOO = 1,
     BAR = 2;
```

**Comment by stkb** [comment]
Filed at Microsoft/TypeScript-TmLanguage#121
