### ISSUE TITLE
Anti-malware software activated when working in the terminal?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [Microsoft/vscode#43047]
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:36:34.867Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Every time I do something in the terminal anti-malware kicks into action and consumes huge amounts of CPU time. I use the git bash in the terminal, but I checked just the bash in its own terminal outside of VS code, and no such anti-malware software activity is detected.

**Comment by Tyriar** [comment]
What anti-malware software are you referring to?

**Comment by PetrKryslUCSD** [comment]
It is the Windows Defender Antivirus.

**Comment by PetrKryslUCSD** [comment]
Actually from my latest experiments I gather it is the VS code per se, not the terminal.
Here is an illustration:
https://www.dropbox.com/s/psbs73v55116mpc/FFsplit-180206-151955.flv?dl=0

**Comment by Tyriar** [comment]
@PetrKryslUCSD sorry about the delay, looks like the link expired, could you reupload if available?

**Comment by PetrKryslUCSD** [comment]
Here is the link again, it should work now:
https://www.dropbox.com/s/psbs73v55116mpc/FFsplit-180206-151955.flv?dl=0
