### ISSUE TITLE
Add a command for "Open to Side" from quick open

### ISSUE THREAD

**Issue by AngerM** [microsoft/vscode#43059]
- VSCode Version: 1.19.3
- OS Version: Mac 10.13.2

Steps to Reproduce:

1. Go to keyboard shortcuts
2. Rebind all the openToSide actions
3. Use Quick Open to find a file and try new keyboard shortcut, doesn't work. ctrl+enter still does work

Does this issue occur when all extensions are disabled?: Yes

Rebound shortcuts are below
```
    {
        "key": "ctrl+v",
        "command": "search.action.openResultToSide",
        "when": "fileMatchOrMatchFocus && searchViewletVisible"
    },
    {
        "key": "ctrl+enter",
        "command": "-search.action.openResultToSide",
        "when": "fileMatchOrMatchFocus && searchViewletVisible"
    },
    {
        "key": "ctrl+v",
        "command": "problems.action.openToSide",
        "when": "problemFocus"
    },
    {
        "key": "ctrl+enter",
        "command": "-problems.action.openToSide",
        "when": "problemFocus"
    },
    {
        "key": "ctrl+v",
        "command": "explorer.openToSide",
        "when": "explorerViewletFocus && explorerViewletVisible && !inputFocus"
    },
    {
        "key": "ctrl+enter",
        "command": "-explorer.openToSide",
        "when": "explorerViewletFocus && explorerViewletVisible && !inputFocus"
    }
````

**Comment by octref** [comment]
Ctrl-V is probably used by another shortcut (paste). You need to move that shortcut to something else for it to work.

**Comment by AngerM** [comment]
That doesn't explain why the old shortcut (which the keybindings should have removed) still worked.

**Comment by sandy081** [comment]
@alexandrudima Redirecting to you.. looks like this is how we resolve commands for key bindings

**Comment by alexandrudima** [comment]
@AngerM

You have rebound 3 open to the side commands:
1. open search results to the side. From the `when` clause I guess this will execute when being on a search result:
```
    {
        "key": "ctrl+v",
        "command": "search.action.openResultToSide",
        "when": "fileMatchOrMatchFocus && searchViewletVisible"
    },
    {
        "key": "ctrl+enter",
        "command": "-search.action.openResultToSide",
        "when": "fileMatchOrMatchFocus && searchViewletVisible"
    }
```

2. open problem to the side. From the `when` clause I guess this will execute when being on an error or warning in the problems view:
```
    {
        "key": "ctrl+v",
        "command": "problems.action.openToSide",
        "when": "problemFocus"
    },
    {
        "key": "ctrl+enter",
        "command": "-problems.action.openToSide",
        "when": "problemFocus"
    },
```

3. open file to the side (from explorer). From the `when` clause I guess this will execute when being on a file in the explorer:
```
    {
        "key": "ctrl+v",
        "command": "explorer.openToSide",
        "when": "explorerViewletFocus && explorerViewletVisible && !inputFocus"
    },
    {
        "key": "ctrl+enter",
        "command": "-explorer.openToSide",
        "when": "explorerViewletFocus && explorerViewletVisible && !inputFocus"
    }
```

I don't believe any of these commands is about the quick open. I believe quick open is hard-coded to open to the side with `ctrl+enter`: https://github.com/Microsoft/vscode/blob/f3a07be7eb6d216567691de880255f9a0ea25e8e/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L211

**Comment by bpasero** [comment]
Currently not possible. Very related: https://github.com/Microsoft/vscode/issues/39101

**Comment by vincentwhales** [comment]
Is it possible to write an extension to override this behavior?

**Comment by asethwright** [comment]
If possible, it would be even better to be able to have separate bindings from the quick open for actions. For example, here is my workflow from VIM:

ctrl-p : launch quickopen
...
fuzzy search
ctrl-j : navigate down
ctrl-k : navigate up
...
ctrl-v : open to side
ctrl-s : open below
enter: open in same window

I find this flow offers a lot of flexibility for viewing files side by side very quickly. But I understand it may be a feature set that is limited to VIM emulation. Still, not being able to customize this is the one thing that I miss from my VIM setup.

**Comment by neildaemond** [comment]
@asethwright 

I tried to add the 'open below' functionality you suggested via https://github.com/microsoft/vscode/issues/80035 (with pull request: https://github.com/microsoft/vscode/pull/80036) but it got closed because "this feature request can be done via an extension and we do not want it as part of VSCode"

I think 'open below' is just as important 'open to side'. I may try write an extension for it then.

**Comment by ppwwyyxx** [comment]
Thanks @bpasero for adding the command for "open to side"!

@neildaemond and @asethwright made some good points above that "open below" is also important and available in vim (by ctrlp). I'm wondering whether there could be a command for both "open to side" and "open below"?

**Comment by bpasero** [comment]
This is currently not planned, however if you change `workbench.editor.openSideBySideDirection` to `down` you get this behaviour.
