### ISSUE TITLE
Python: Intellisense and linting not working.

### ISSUE THREAD

**Issue by nautilus7** [Microsoft/vscode#43057]
- VSCode Version: 1.20.0-Insider (python extension version 2018.1)
- OS Version: Windows 10 Education x64 (Creator's Fall Update)

Steps to Reproduce:

1. Install python extension
2. Install pylint
3. Nothing works!

I am unable to make python intellisense and linting to work on vscode. I have tried all possible fixes and suggestions around without any success. I attach a picture, which provides many additional info about my setup.

![vscode_pylint](https://user-images.githubusercontent.com/1540233/35879601-50c9187c-0b84-11e8-9a8b-b99076fd0b60.png)

The file shown opened in the photo is located in `C:\Users\Σπύρος\Documents\enigma2\lib\python\Screens\Hotkey.py`.

While I have included the required python modules in the `autoComplete.extraPaths` variable, pylint throws errors about not being able to find `enigma` module.

In addition, intellisense doesn't work. When I right-click on a class/module and select "peak definition", it shows nothing. Autocomplete doesn't work as well, even for `os` module. Same for all other modules. The folders shown in the bottom right explorer windows contain all required modules. Each sub folder contains an empty `__init__` file to tell python that it contains modules.

The python version and pylint version are displayed in the upper right corner in the cmd window. Both are in windows PATH.

What I noticed some days ago, when I tried different solutions, was that if I move the whole project folder to somewhere else (e.g. C:\), I was able to make intellisense to work. So there must be something wrong with the files being located inside `C:\User\Σπύρος\...` because of the Greek letters being used. But this worked only for autocomplete. **Pylint didn't work in this case either.**

**Comment by usernamehw** [comment]
Wrong repo. You should file it against python extension.

**Comment by nautilus7** [comment]
ok, sorry!
