### ISSUE TITLE
Linting / error highlighting misbehaving on some edits

### ISSUE THREAD

**Issue by joshualemli** [Microsoft/vscode#43050]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. make edits to `.js` file
2. switch focus to another window (i.e. a browser or another application)
3. switch back to VS-Code
4. make more edits or view previous edits
5. error highlights appear (red squiggly line) where no errors exist!
6. saving or re-opening the file seems to fix this

**Comment by joshualemli** [comment]
I should also add that this seems to occur when naming/renaming `var` variables.

**Comment by joshualemli** [comment]
I am still experiencing this issue but it is difficult to reproduce and seems irregular.  : (   I will check this thread to see if anyone has questions because I can't seem to pin down what is causing the issue.

**Comment by mjbvz** [comment]
Possible path casing related ( similar symptoms to #40682).

Can you please check your tsserver trace to confirm this:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Trigger the error
3. Open the output pane and go to the typescript section.
4. Look for the last lines of the form: 

```
[Trace  - 23:26:10] Event received: syntaxDiag (0).
Data: {
    ...
}
[Trace  - 23:26:10] Event received: semanticDiag (0).
...
```

Does the file path's case in the output match the expected (actual) case of the file path on your system?

**Comment by joshualemli** [comment]
Thank you for these instructions.  I have set tsserver trace to `verbose` and will check the output and respond to this thread when I get this error again.

**Comment by mjbvz** [comment]
Closing this for housekeeping purposes. Please let me know if you see the problem again and are able to capture a trace.
