### ISSUE TITLE
Font becomes unreadable in terminal after Command-B.

### ISSUE THREAD

**Issue by jleach** [Microsoft/vscode#43054]
- VSCode Version: Version 1.19.3 (1.19.3)
- OS Version: macOS 10.13.3 (17D47)

Steps to Reproduce:

1. Use VSCode for a while. Command-B often triggers this issue. No new plugins were installed since my last update; they worked fine for months.

![screenshot 2018-02-06 10 10 30](https://user-images.githubusercontent.com/390891/35876186-514a7812-0b26-11e8-8e92-66fba818627a.png)

**Comment by Tyriar** [comment]
This is fixed in upcoming version
