### ISSUE TITLE
problemMatcher's "relative" fileLocation should be smarter

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#43058]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 16.04

I have a cmake project I am using with [cpptools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools]).  Because of the way this project is set up, all compiler errors use  absolute source file paths.  
However, cpptools' `$gcc` problem matcher uses `"fileLocation": ["relative","${workspaceRoot}"]`, so paths get unconditionally concatenated with the prefix.   
An error location such as `/home/vadimcn/project/src/application.cpp:123:45` gets interpreted as `/home/vadimcn/project/home/vadimcn/project/src/application.cpp:123:45`, and when I click on an error in the Problems panel, VSCode complains:  `Unable to open 'application.cpp': File not found (file:///home/vadimcn/project/home/vadimcn/project/src/application.cpp).`

I would suggest that the "relative to" prefix should not be added if the error location path is already absolute.

**Comment by octref** [comment]
Report to https://github.com/Microsoft/vscode-cpptools thanks.

**Comment by vadimcn** [comment]
I can file it with the extension of course, but I think his bug will circle back to VSCode: The extension does not know whether the path will be absolute or relative, but they have to choose one of the two values for `fileLocation`.   Whichever they choose will be wrong for some projects.  This is a missing feature in the VSCode itself.

**Comment by octref** [comment]
I see. Giving to @dbaeumer.

**Comment by dbaeumer** [comment]
Dups #449
