### ISSUE TITLE
VSCode changes .git folder Hidden attribute which bugs tsc -w

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/vscode#43069]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open VSCode with a project using git.
2. Click on VSCode to focus on the application. This will modify the `.\git` folder Hidden Attribute.

Using a File Watcher software, I receive this popup when I focus on VSCode after `tsc -w` finishes compiling.
![](https://puu.sh/ziinZ.png)

The change of the `\.git` folder causes `tsc -w`  to trigger the `File change detected. Starting incremental compilation...` message again but it doesn't actually compile anything.

Changing the setting to `"git.enabled": false,` fixes the problem. (But obviously also disables git in VSCode).

**Comment by joaomoreno** [comment]
VSCode doesn't touch the git folder. It runs `git status`.

Does `git status` cause the same event?
