### ISSUE TITLE
Extension logs should be accessible from "Show Logs"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#43064]
The "Show Logs" and "Open Log File" commands only show log files from VS Code itself. We should show the log files from extensions there as well.

**Comment by ira-gordin-sap** [comment]
Hi,
I implement VS Code extensions. How I can write to log from my extensions?
Thanks,
Ira

**Comment by mushon4** [comment]
Thanks Ira for the question I wan to view logs of installed extenstion. say Hi to everyone :)
