### ISSUE TITLE
Green light bulb feels out of style

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4306]
Why is the light bulb green and not white like most things in the status bar?
Looks out of style IMHO

ping @bgashler1 

![screen shot 2016-03-16 at 12 47 01](https://cloud.githubusercontent.com/assets/1926584/13811299/34c835ee-eb75-11e5-959a-40b695864c9a.png)

![screen shot 2016-03-16 at 12 47 20](https://cloud.githubusercontent.com/assets/1926584/13811311/40c19e08-eb75-11e5-952c-30b50f6794b1.png)

**Comment by egamma** [comment]
It needs to get attention and white just doesn't work.

**Comment by isidorn** [comment]
I think we should tackle all these non-white colors in the status bar in the future. There must be something which looks nice and draws attention as well.
Assigning to backlog and @bgashler1

**Comment by bgashler1** [comment]
We're thinking of doing some notification work in the future (i.e. a unified area for notifications).  This will address many other related issues with notifications.

While we wait to get that in the product, I can provide a temporary solution for this.

**Comment by Tyriar** [comment]
When considering the future direction, remember that differentiating green and red is one of the biggest color blindness problems.
