### ISSUE TITLE
"The window has crashed" error

### ISSUE THREAD

**Issue by sea1jxr** [Microsoft/vscode#43062]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.17074
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
regex|chr|0.1.0
tslint|eg2|1.0.24
vscode-auto-open-markdown-preview|hnw|0.0.4
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.1.0
vscode-jest|Ort|2.6.0
annotator|ryu|0.11.0
powerquerymlanguage|sea|1.0.0
change-case|wma|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open one particular folder (code .). 
**Actual**: Error message that says: "We are sorry for the inconvenience! You can reopen the window to continue where you left off."
**Expected**: It should work

Note: Other folders work fine.  I am wondering if it has to do with the previously opened windows.

Reproduces without extensions: Yes

**Comment by sea1jxr** [comment]
I delete the folder C:\Users\<user>\AppData\Roaming\Code and the issue is resolved.

**Comment by octref** [comment]
Glad you resolved it!
