### ISSUE TITLE
Ctrl+Click and middle-click no longer does "Open to the side"

### ISSUE THREAD

**Issue by GollyJer** [Microsoft/vscode#43067]
- VSCode Version
  **1.20.0-insider**
- OS Version
  **Windows 10**

Steps to Reproduce:

1. `Ctrl+Left Click` on any file in Explorer.
2. `Middle click` on any file in Explorer.

Does this issue occur when all extensions are disabled?
**Yes**

I'm guessing this is a purposeful change but I wanted to report it just in case... I used to `ctrl+click` or `middle-click` files in the sidebar to quickly open them up for side-by-side  reading.  It seems this is no longer possible with any mouse combination.

I can understand that `ctrl+click` may have been changed to multi-select behavior but can we maybe retain the functionality with `middle-click`?

Thanks,
Jeremy

**Comment by randomAnon12** [comment]
Currently middle click acts correctly, or at least I am assuming it is. The default behavior in many other applications is too close what is clicked on, and that is what I am experiencing here in VS Code. 

I am, however unable to reproduce the Ctrl+Click issue. Currently that opens another window as expected.

**Comment by bpasero** [comment]
@GollyJer I cannot reproduce the middle click behaviour in stable to open to the side, I do not think we ever supported that. 

As for the Ctrl+click behaviour, this changed because of multi select but we have an option to change it back: `"workbench.list.multiSelectModifier": "alt"`

**Comment by GollyJer** [comment]
Thanks for the response @bpasero.  I'll update my behavior to use the `alt` key now that I know the expected behavior.

@randomAnon12 and @bpasero. You're both correct. Looks like middle clicking doesn't do anything different than simple clicking.  I guess I was always `ctrl + middle-click`ing.

@randomAnon12 In web browsers middle clicking a link opens the link in a new tab and middle clicking the tab closes the tab. This would be nice behavior for vscode... `click` navigates within the preview/italic-labeled editor (current behavior) but `middle-click` "fully opens" the file in a new editor in the "background" (i.e. - doesn't activate the tab).  

What do you think? This would enable very efficient opening and closing of file editors for quick viewing.
