### ISSUE TITLE
Unverified Breakpoints during debug

### ISSUE THREAD

**Issue by Declan1984** [Microsoft/vscode#43061]
- VSCode Version: 

Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:36:34.867Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:

Microsoft Windows 7 Professional Version 6.1 (Build 7601: Service Pack 1)

Steps to Reproduce:

The debugger was working great on Python program a few days ago; started building tests using Python's unittest and debug continued to work, then in the last day or so, it stopped recognizing breakpoints set in either the test file or other modules accessed during tests.  Code execution will stop during test run at the point of the breakpoint, but it doesn't highlight the line of code as currently being stopped at the breakpoint and the breakpoint dot is shaded gray and says "Unverified Breakpoint"

Doesn't work when Python Extension is enabled or disabled (when disabled, I can't even set breakpoints).

1.   Write Python module
2. Write separate test module using unittest
3. Set breakpoint
4. Run debugger

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
Please file this issue against the Python extension.
