### ISSUE TITLE
Let auto-updates be installed after I exit VSCode

### ISSUE THREAD

**Issue by Plasma** [Microsoft/vscode#43068]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
LogFileHighlighter|emi|2.0.0
vs-code-xml-format|fab|0.1.5
gc-excelviewer|Gra|2.0.17
beautify|Hoo|1.3.0
ecdc|mit|0.11.0
mssql|ms-|1.3.0
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
vscode-nginx|sha|0.5.0
vscode-table-formatter|shu|1.2.1
vscode-hexdump|sle|1.6.0

---

It would be great if updates were automatically installed after I close VSCode, instead of prompting me to interrupt my workflow and install right then.

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/9539
