### ISSUE TITLE
Different cursor when moving over line numbers

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4307]
- VSCode Version:
- OS Version: El Capitan

Steps to Reproduce:

1. In vscode I never get the white mouse pointer - always the black one
2. Move over line numbers - notice that the mouse pointer is white only here. This feels a bit out of style, I would prefer it was the black pointer also here. Sorry for no screenshots - not sure how to capture the mouse on the mac

**Comment by alexandrudima** [comment]
@isidorn Is this still an issue?

**Comment by isidorn** [comment]
@alexandrudima nope - looks good now
