### ISSUE TITLE
Variables window does not allow unfolding first element of any python data structure

### ISSUE THREAD

**Issue by csakumar** [Microsoft/vscode#43074]
- VSCode Version: 1.19.3 Shell 1.7.9 x64 Arch
- OS Version: Windows 7 Professional
Extensions used : Python 2018.1.0 from Microsoft

Steps to Reproduce:

1. Create any python data object with multiple elements.
2. While in debug mode, try unfolding the first element of the data object. While the icon changes to unfolded mode, the data element does not populate
3. Try unfolding the successive data element and it works as expected.
Does this issue occur when all extensions are disabled?: Yes

In the Attachment, please note the unfolded mode for 0th and 1st row of playerData object. Although 0th row icon indicates that it is unfolded, there is no populated data. 
![image](https://user-images.githubusercontent.com/36219018/35899404-dd4abed8-0b91-11e8-8bfe-54752ee23b73.png)

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#721

**Comment by weinand** [comment]
VS Code does not have a builtin Python debugger. I'll move this issue to the correct repository.
