### ISSUE TITLE
feedback bug

### ISSUE THREAD

**Issue by kobetw** [Microsoft/vscode#43070]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.24
debugger-for-chrome|msj|4.1.0

The following is my question
I have a problem,  I can't use my select all( ctrl + A )  when I  download the vscode from the  Official website  and install completly， I  have never modify my keyword,  nothing i have to do.  

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Can you try to do this?

Ctrl + Shift + P -> Preferences: Open Keyboard Shortcuts -> type in "select all" -> take a screenshot of the settings?

For example:

![image](https://user-images.githubusercontent.com/4033249/35942880-23239aea-0c0c-11e8-92c4-bf0aa88edac1.png)
