### ISSUE TITLE
Debug configuration doesn't show up for second project in multi-root workspace

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43079]
I'm sure this has worked for me before, but today I added a second folder to my workspace then used the `Add config (devicelab)` option in the debug dropdown to add a new config. For some reason, the new launch config doesn't show up in that dropdown.

launch.json in the original folder (flutter_tools) has two configs that both appear (they're pretty much the same as this one, just with different args/program).

![debug](https://user-images.githubusercontent.com/1078012/35905976-d9f06c98-0be0-11e8-8542-11d62490ec67.png)

**Comment by DanTup** [comment]
Unsure if related, but dev console has a lot of warnings (284):

![warnings](https://user-images.githubusercontent.com/1078012/35906040-19f833ac-0be1-11e8-90d2-064675673416.png)

**Comment by DanTup** [comment]
Note: after a "Reload Window" the config shows up, suggesting the config is fine but something went wrong earlier.

**Comment by isidorn** [comment]
I am not getting an event from the configuration service. Forwarding this issue to @sandy081 
Here are exact steps:

1. Start with single folder vscode (no workspace)
2. Add another folder to this workspace
3. Add a configuration to the second folder's `launch.json`
4. No configurationChange [event](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L354) gets fired

**Comment by sandy081** [comment]
@isidorn I cannot reproduce this issue. I followed the steps as above and I could see the launches dropdown is getting updated. Not sure if I miss any steps here?

**Comment by isidorn** [comment]
@sandy081 I can reproduce all the time exactly following the steps above, so please drop by my machine

**Comment by isidorn** [comment]
After investigating with @sandy081 I have created a new bug which captures the issue more correctly
https://github.com/Microsoft/vscode/issues/44034
@DanTup feel free to comment more there if I missed something
