### ISSUE TITLE
Tasks: Depended background tasks are run multiple times

### ISSUE THREAD

**Issue by MofX** [Microsoft/vscode#43076]
I have a task, that depends on multiple background tasks (e.g. multiple instances of tsc watch).

When I run the tsc watch task on it's only, only one instance of it can be started at a time, as expected. When running the task, that depends on the watch tasks, it starts new instances of the background tasks on every start.

After the first time I run my depends task, "Tasks: Show Running Tasks" lists all of the background tasks as expected. After the seconde time I run my depends task, I get the duplicate amount of terminals, but "Show Running Tasks" still shows one instance of all the background tasks running.

After killing any of the multiple instances of the background tasks, it get's removed from the list of running tasks, even if one instance is still running.

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Watch All",
			"dependsOn": [
				"server:watch:tsc",
				"client:watch:tsc",
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": []
		},
		{
			"type": "npm",
			"label": "client:watch:tsc",
			"script": "watch:client",
			"problemMatcher": [
				"$tsc-watch"
			],
			"isBackground": true
		},
		{
			"type": "npm",
			"label": "server:watch:tsc",
			"script": "watch:server",
			"problemMatcher": [
				"$tsc-watch"
			],
			"isBackground": true
		}
	]
}
```

**Comment by eamodio** [comment]
I thought I was going nuts there for a while until I came across this 😄
