### ISSUE TITLE
[less] How to eliminate marks of the less term expected？

### ISSUE THREAD

**Issue by sosout** [Microsoft/vscode#43087]
In less file, I write JS directly, the console is OK, but Vscode reminds "less term expected", See below：
![qq](https://user-images.githubusercontent.com/22269613/35908108-aa780558-0c2a-11e8-975e-80063396a93a.png)

Excuse me，is there any way to eliminate the mark?
Thanks！

vscode version: 1.19.3
Computer system: win7

**Comment by aeschli** [comment]
Looks like feature not documented on http://less2css.org/

**Comment by aeschli** [comment]
@sosout In the meantime you will have to turn off validation with `"less.validate": false`

**Comment by nuintun** [comment]
@aeschli Same problem, see [less parser](https://github.com/less/less.js/blob/v3.0.0/lib/less/parser/parser.js#L689), this syntax will eval string as javascript.

**Comment by matthew-dean** [comment]
Hi, Matthew Dean from the Less team here. Is there a way I could coordinate with the VSCode team to see how they're linting Less? I use VSCode to work on Less fixes, and I frequently see valid Less code flagged as having invalid or unexpected values.

**Comment by octref** [comment]
Hi @matthew-dean, we currently maintain our own parser at https://github.com/Microsoft/vscode-css-languageservice/tree/master/src/parser for css, less and scss.

This is not really ideal, as we would need to update it from time to time to match the updated syntax of Less. It would be great if we can have a linter maintained by the less team to check against the up-to-date syntax for less. Currently, if people are using latest syntax of Less that VS Code cannot handle yet, we suggest them to turn off VS Code's validation and use a plugin such as https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint.

**Comment by matthew-dean** [comment]
@octref Thanks for responding!

If the Less team created / maintained such a linter, what sort of format / API should it return? It would be nice to provide a linter that is general purpose for any team that needs Less linting. I can't promise anything, as I'm not sure of the work involved, but it seems reasonable.

**Comment by aeschli** [comment]
For linting, we can actually run any OS command as a VSCode task and extract the warnings/errors using regular expressions.
However, we also use our parser for code completion proposals, hovers, document symbols (outlines), color decorators, folding regions and more. To provide these, our css/less/scss language support implements the [language server protocol](https://microsoft.github.io/language-server-protocol). The LSP is an editor neutral API that has gained quite some traction across [editors and IDEs](https://microsoft.github.io/language-server-protocol/implementors/tools/). Of course this not little work but that would be the ideal API to implement... :-)

**Comment by matthew-dean** [comment]
@aeschli Oh cool, I'll check it out.

**Comment by octref** [comment]
@matthew-dean In particular, you can study https://github.com/shinnn/vscode-stylelint or https://github.com/Microsoft/vscode-tslint, which are great examples of integrating a linter as a LSP extension.

**Comment by rjgotten** [comment]
@aeschli 
> Looks like feature not documented on (...)

The official Less website lives at http://lesscss.org

Also; you may want to amend your comment and remove the link. That domain is squatted and redirects to a secondary one where ads are being served, including ones that tempt users to install browser extensions.

**Comment by musso** [comment]
Still having the same problem using VS Code Version 1.27.2 (1.27.2)
Apart from `"less.validate": false`, any quick solution?

**Comment by aeschli** [comment]
The fix will be in to upcoming 1.28 build.
But you can already try this in the insider build.

**Comment by anyclub** [comment]
same question

win10 64 
vscode 1.28.2
