### ISSUE TITLE
Previous suggestion list not cleared on space

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#43086]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.9.0-5-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.24
vscode-intelephense-client|bme|0.8.5
ayu|tea|0.12.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Install intelephense extension
2. start typing a use declaration - `use x`

Reproduces without extensions: NA

This is observed with an extension but I dont believe it is caused by the extension. When I type out a use declaration in PHP I will get a lengthy (but `isIncomplete:false`) completion list from the extension which shows immediately when typing `use`. 

Then pressing space and starting to type the next token does not clear the previous suggestion list or trigger another completion request as expected. The same suggestion list remains with now stale suggestions for the context.

If I press escape to close the popup then type the next token I observe another completion request and appropriate suggestions for the next token. You can see the behaviour in the below gif.

![no_completion_request](https://user-images.githubusercontent.com/5885195/35908043-b010b3f2-0c43-11e8-923e-72121cf3b6b0.gif)

**Comment by dbaeumer** [comment]
@bmewburn since the server reports the list as `isIncomplete:false` VS Code expects the list to be complete and filters it on typing. This is why VS Code doesn't send another completion request. Have you reported this issue to the extensions?

**Comment by bmewburn** [comment]
Thanks for the fast reply @dbaeumer . It's my extension :) . Maybe I misunderstand how the `isIncomplete` flag works. In the above case all relevant suggestions for `us|` are returned and typing more (word) characters would not change the result. I assumed that space, being a word separator, changes the completion context though, and would trigger further completion requests.

So if `us|` returns 50 matches to complete a single token should I instead set `isIncomplete:true` for this result because there are potentially hundreds of matches when considering the entire phrase `use x|` `use y|` `use z|`?

Had I selected `use` from the list then it the popup would have closed and suggested again for the following token.

**Comment by bmewburn** [comment]
Thinking about this more I see how having the list remain on space has advantages because a lang server could return full method signature suggestions when in a context where the user may want to override a base method. eg `func|` => `function myFn($p)`. Though if this is the case I dont understand why, in the gif above, list items like `call_user_func` are not filtered out. The space in `use N` seems to be ignored then.

**Comment by dbaeumer** [comment]
@bmewburn if space is a defined word separator code complete should close correctly. I tested this with TS and it works as expected. If space is a word seperator then can you provide me with a GitHub repository I can clone that demos the behaviour.
