### ISSUE TITLE
Searching for regexp in files shows results only from open files

### ISSUE THREAD

**Issue by acristu** [Microsoft/vscode#43081]
- VSCode Version:1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba)
- OS Version: Microsoft Windows [Version 10.0.15063]

I ran into #32095 while searching using regexp.

Steps to Reproduce:

1. Regular search for `name: "`
2. Occurrences in all files are found
3. Search using regexp for `\{(?:\s|\r?\n)*?name: "(\w+)",`
4. Only occurrences in open files are found

Does this issue occur when all extensions are disabled?: **Yes**

No errors in Developer Tools Console.

**Comment by roblourens** [comment]
Multiline search is not allowed, so it should show an error message for that query (because of the `\n`) but it was getting swallowed.

**Comment by acristu** [comment]
Could we have an option to allow multiline search, disabled by default?

**Comment by roblourens** [comment]
It's just not implemented. https://github.com/Microsoft/vscode/issues/13155
