### ISSUE TITLE
Tag must be paired, no start tag: [ </br> ]

### ISSUE THREAD

**Issue by zhuweiyou** [Microsoft/vscode#43083]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.5.0
---

`<br>` should be a self-closing element

![image](https://user-images.githubusercontent.com/8413791/35907643-7c54fcf4-0c29-11e8-8e6a-bddb1dc80430.png)

**Comment by yume-chan** [comment]
You can use `<br>` or `<br/>`, but I have never heard of `</br>`.

I can not reproduce your problem, Code doesn't complain about my `</br>`.

Can you post a minimal repro and the list of your extensions?

**Comment by zhuweiyou** [comment]
I use the <br>

**Comment by zhuweiyou** [comment]
I restart vscode, that warning does not exist.

Syntax check may not keep up in real time

Thank you.
