### ISSUE TITLE
When editing js and saving, cursor jumps to bottom of source code

### ISSUE THREAD

**Issue by ben-brainlabs** [Microsoft/vscode#43080]
If I am editing a javascript file - I save often (cmd+s on mac)

This causes the cursor to jump to the very bottom of the source code, losing the place I was just editing.

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
swagger-jsdoc-examples|Cra|0.0.4
vscode-docker|Pet|0.0.24
ejs-language-support|Qas|0.0.1
ejs-snippets|Tao|0.1.0
html-css-class-completion|Zig|1.16.1
vsc-docker|Zim|0.34.0
vscode-view-readme|ans|0.2.1
vscode-database|baj|1.3.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.5
vscode-instant-markdown|dba|1.4.1
line-counter|dol|0.3.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
vscode-npm|fkn|3.3.0
docker-explorer|for|0.1.6
vscode-mysql|for|0.2.2
docker-linter|hen|0.5.0
mysql-syntax|jak|1.2.0
mysql-scratchpad|jbl|0.1.1
docthis|joe|0.6.0
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
font-awesome-codes-html|med|0.0.7
vscode-exec-node|mir|0.5.0
prettify-json|moh|0.0.3
font-awesome-5-codes-html|mrd|1.0.1
mssql|ms-|1.3.0
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.1.0
color-highlight|nau|2.3.0
mysql-inline-decorator|odu|0.0.4
autolinting-for-javascript|t-s|1.3.0
bootstrap4-vscode|the|3.0.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment]
Can you try to disable the "vscode-JS-CSS-HTML-formatter" extension then try again?

**Comment by ben-brainlabs** [comment]
Yup - that solves the issues - must be a bug in that extension. Thanks!
