### ISSUE TITLE
Add a setting to change the "User Setting" Path, to Point to an shared place

### ISSUE THREAD

**Issue by Kriegel** [microsoft/vscode#43082]
To have the same Settings all over the World, i prefer to save my Settings in a Cloud file or in a Enterprise share.
So , please add a Setting to Change the User Setting Path, to Point to an shared Place.

**Comment by sandy081** [comment]
@Kriegel  I think we already have a request to Share Settings.

Workspace settings are Team settings. Not sure if you mean different?

**Comment by Kriegel** [comment]
@sandy081 
Thank you for your Answer.
You answered only to the second "nice to have"part with teams.
For this i will open a new issue.

My initial intent for this issue is the first part.

To have the same Settings all over the World, i prefer to save my Settings in a Cloud file or in a Enterprise share.

**So , please add a setting to be able to change the "User Setting" Path, to Point to an shared place.**

**Comment by sandy081** [comment]
@Kriegel Can you please update the summary and description accordingly? Thanks.

**Comment by Kriegel** [comment]
@sandy081 
I am totally new to issues.
so i guess you mean with summary the Headline (Title) of this thread!?
I have changed it and even the initial Post of this thread.

**Comment by sandy081** [comment]
@Kriegel We recently launched settings sync which serve the purpose of sharing settings across machines. 

https://code.visualstudio.com/updates/v1_43#_preview-features

Can this be closed in favour of settings sync feature?

**Comment by Kriegel** [comment]
done, with settings sync.
