### ISSUE TITLE
Disable recommended extensions view

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#43085]
There is a setting 'extensions.ignoreRecommendations' which I believe inhibits the recommended extension notifications.

Could this also be used to ignore the recommend extensions view in the side bar? Everytime I open a new workspace I end up hiding the view from the side bar. 

Either it should remember that I've hidden it or the setting should apply to both.

**Comment by ramya-rao-a** [comment]
>  Everytime I open a new workspace I end up hiding the view from the side bar.

The extensions view doesnt open by default. Do you mean that whenever you open a new workspace and then open the extensions view, you hide the "Recommended" section and only keep the "Installed" section?

**Comment by Gruntfuggly** [comment]
Yes - that's right. I like the recommendations, but all my projects are C++, so I get the same recommendations every time. 8-)

**Comment by ramya-rao-a** [comment]
I am trying to understand your workflow here...

When you open a new workspace and go the the extensions view, what is your intention? To search for new extensions to install? If yes, then how does the existence of the recommended view matter? The second you start typing the search text, both the "Installed" and "Recommended" view go away.

Are you instead referring to the need to remove individual items from the recommended view?

**Comment by Gruntfuggly** [comment]
It's usually to enable or disable extensions. I have some workspaces where I need some C++ extensions and some which I don't. I also develop some extensions, so I tend to disable the 'official' versions in order to link the dev versions.

It's not a huge problem, it's just that I already have the extensions that I want, so I don't need the recommendations. I thought I had disabled the view when I set 'extensions.ignoreRecommendations', but I realised that this is for the popup notifications. It's just a bit confusing.

**Comment by ramya-rao-a** [comment]
> I thought I had disabled the view when I set 'extensions.ignoreRecommendations', but I realised that this is for the popup notifications. It's just a bit confusing.

Yes, I agree that the setting is a little confusing. It was more confusing before :). I recently updated the description on it to say `  // If set to true, the notifications for extension recommendations will stop showing up.` to make it more clear that the setting is about the notifications.

> Either it should remember that I've hidden it or the setting should apply to both.

The recommendations that show up in the notifications/popups are a very small subset of the recommendations that show up in the view, so we cant re-use the same setting to hide the recommendations view.

VS Code does remember your choice (either collapsing the view or resizing it), but it remembers this for each workspace and not at a user level.

@sandy081 Any reason we store the state of the sections in the extensions (or explorer for that matter) at workspace level instead of global level?

**Comment by sandy081** [comment]
@ramya-rao-a With 1.20 we store the extensions visibility state globally. But expansion state and the order is still workspace level.

**Comment by ramya-rao-a** [comment]
@Gruntfuggly In 1.20 you can right click on the "Recommendations" section and choose to hide it. Like @sandy081 mentioned this state is retained across workspaces.

@sandy081 I don't see this feature covered anywhere in the release notes. Can you link the issue that was tracking it? Also, I couldn't find a way to bring back the hidden section

**Comment by sandy081** [comment]
@ramya-rao-a This is not a big feature and is mentioned as a notable fix.  https://github.com/Microsoft/vscode/issues/35462

You can right click on the viewlet title area to select the views to show.

**Comment by ramya-rao-a** [comment]
Thanks @sandy081 

@Gruntfuggly https://github.com/Microsoft/vscode/issues/35462#issuecomment-360512568 should help you
