### ISSUE TITLE
Offset of top level tree items changes with icon them change

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#43084]
From [here](https://github.com/Microsoft/vscode/issues/42097#issuecomment-363645303) by @LazarusX 

![kapture 2018-02-07 at 10 10 20](https://user-images.githubusercontent.com/716650/35896900-86236d90-0bf9-11e8-9545-5f058ebebd15.gif)

**Comment by aeschli** [comment]
I think that is the expected result. The whitespace you see is there for twisties.

**Comment by LazarusX** [comment]
@aeschli Why is the twisty behavior different when switching the file icon theme between Seti and Minimal? In addition, I think the file icon theme setting is not supposed to affect the appearance of extension tree views (see the screen cast in comment: https://github.com/Microsoft/vscode/issues/42097#issuecomment-363645303)

**Comment by aeschli** [comment]
In general, the goal is to have all labels of the same hierarchy level aligned.
The VSCode Set theme does not have any folder icons. In that case, the file icons are shifted to the left, and align with the twisties of folders at the same level. Best is to try it out with files and folders at the same level.
@sandy081 is looking into the custom trees. which can have user-provided icons as well as file icons from the file icon theme.
IMO, again, the custom tree should make sure, that all labels are aligned.
To do so, the custom tree provider will have to provide placeholder icons for file and folders in case that the current file icon theme does not provide these.
The custom tree provider should also be able to indicate whether
- the tree should always show icons for all items: Placeholders icons have to be used for file/folder/items that don't provide any
- the tree should follow the style of the current file icon theme: No icons, icons only for leafs ('seti' style) or show icons for all items. Again placeholders icons are required for non-file/folder items.

**Comment by LazarusX** [comment]
Your point regarding the icons in the file explorer makes sense to me.

But for custom trees, it seems that currently there is no way for extensions to respond to file icon theme style changes.

**Comment by sandy081** [comment]
Agreed that custom views should not be concerned about file icon themes. Reopening it

**Comment by sandy081** [comment]
Fixed by ea787762dbbc9e9fbcce7556117957cb763124cd

**Comment by sandy081** [comment]
![kapture 2018-02-09 at 18 52 12](https://user-images.githubusercontent.com/10746682/36041927-68e69fb8-0dca-11e8-82da-3773bf23abad.gif)

**Comment by sandy081** [comment]
Reopening it because #28974 (ea787762dbbc9e9fbcce7556117957cb763124cd) is reverted

**Comment by sandy081** [comment]
Fixed by 11a262ea52ede4dfdd36e4a8ee29e86f2947097b
