### ISSUE TITLE
Importing from wrong directory in typescript

### ISSUE THREAD

**Issue by avifatal** [Microsoft/vscode#43088]
Hi,
in the following examle, I added the variable `el: ElementRef` to the constructor.
VSCODE took ElementRef from `'@angular/core/src/linker/element_ref'` and not from `'@angular/core';`
when I say "took", I mean I write `ElementR` then clicked in CTRL+SPACE and the option was to take from  `'@angular/core/src/linker/element_ref'`.
Is this angular issue? typescript config issue? or VSCODE issue?

```
import { Directive } from '@angular/core';
import { ElementRef } from '@angular/core/src/linker/element_ref';

@Directive({
  selector: '[appValidatable]'
})
export class ValidatableDirective {

  constructor(el: ElementRef) {
    el.nativeElement.style.backgroundColor = 'yellow';
 }

}
```

Thanks

**Comment by mjbvz** [comment]
Which vs VS Code version are you using? Can you please try this in VS Code 1.20. We fixed a number of bugs around auto imports

**Comment by avifatal** [comment]
@mjbvz thanks, how may i install that? my version is 1.19.3  and there are no upcomming updates.
Thanks

**Comment by bradenhs** [comment]
I just updated to vscode 1.20 and still see this issue.

**Comment by mjbvz** [comment]
Here's what I see in a new angular project with TS 2.7.1:

![screen shot 2018-02-08 at 3 30 59 pm](https://user-images.githubusercontent.com/12821956/36003957-1ed3cee0-0ce5-11e8-8400-af47b3aca95b.png)

Please make sure you are using TS 2.7.1.

If this is still not working, please your `tsconfig.json`
