### ISSUE TITLE
Debugger can't connect to a session launched via npm script

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#43093]
### Issue Type
Bug or Question

### Description
1. clone https://github.com/Deilan/vscode-issue-43093
2. `yarn install`
3. `Launch via nodemon` debug configuration

terminal output:
```
Deilan@DEILAN-PC-WIN10 MINGW64 /c/Dev/node-typescript-vscode (master)
$ cd "C:\Dev\node-typescript-vscode" ; "C:\Program Files\nodejs\npm.cmd" run-script serve:debug --inspect=31676 --debug-brk

> node-typescript-vscode@0.0.1 serve:debug C:\Dev\node-typescript-vscode
> cross-env NODE_ENV=development nodemon --config ./nodemon.json --exec {{pwd}}/node_modules/.bin/ts-node ./src/index.ts --project ./tsconfig.development.json

[nodemon] 1.14.12
[nodemon] reading config .\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 30568 to restart
[nodemon] watching: C:\Dev\node-typescript-vscode\src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `C:\Dev\node-typescript-vscode/node_modules/.bin/ts-node ./src/index.ts --project ./tsconfig.development.json`
[nodemon] spawning
[nodemon] child pid: 29760
[nodemon] watching 2 files
development
[nodemon] clean exit - waiting for changes before restart
```

VS Code error:
![image](https://user-images.githubusercontent.com/4777512/35915133-d23f7062-0c16-11e8-8360-1071447f5608.png)

`launch.config.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch via nodemon",
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "serve:debug"
            ],
            "restart": true,
            "console": "integratedTerminal",
            "internalConsoleOptions": "openOnSessionStart",
            "skipFiles": [
                "node_modules/**",
                "<node_internals>/**"
            ]
        }
    ]
}
```

`package.json`:
```json
{
  "name": "node-typescript-vscode",
  "version": "0.0.1",
  "scripts": {
    "serve:debug": "cross-env NODE_ENV=development nodemon --config ./nodemon.json --exec {{pwd}}/node_modules/.bin/ts-node ./src/index.ts --project ./tsconfig.development.json"
  },
  "devDependencies": {
    "@types/node": "^8.5.1",
    "nodemon": "^1.14.12",
    "rimraf": "^2.6.2",
    "ts-node": "^4.1.0",
    "tslib": "^1.7.1",
    "tslint": "^5.7.0",
    "typescript": "^2.6.2"
  },
  "dependencies": {
    "cross-env": "5.1.3"
  }
}
```

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (f9398645d1d624538708eeebf96e6fdeb546f5d7, 2018-02-06T15:20:43.871Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Memory (System)|31.88GB (11.70GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by weinand** [comment]
@Deilan how does the "serve:debug" script launch nodemon in debug mode?

The VS Code debugger and the script will have to agree on a common debug port.
With you launch config the VS Code debugger will pass a "--inspector-brk=12345" to the npm "serve:debug" script. But I don't think that the script will do anything with that argument.

**Comment by Deilan** [comment]
@weinand The issue is that `--inspect=5858` is not passed correctly in that case by default. Let me introduce an example on what's happening.

If I launch debug configuration as is, the following command will be executed:
`cd "C:\vscode-issue-43093" ; "C:\Program Files\nodejs\npm.cmd" run-script serve:debug --inspect=8004 --debug-brk`

and that's what arrives to the script itself (note that `--inspect=8004` and `--debug-brk` are not there):
`cross-env NODE_ENV=development nodemon --config ./nodemon.json --exec {{pwd}}/node_modules/.bin/ts-node ./src/index.ts --project ./tsconfig.development.json`

According to [npm run-script docs`](https://docs.npmjs.com/cli/run-script), additional arguments should be passed after double dash.

> As of npm@2.0.0, you can use custom arguments when executing scripts. The special option -- is used by getopt to delimit the end of the options. npm will pass all the arguments after the -- directly to your script:
`npm run test -- --grep="pattern"`


So if i slightly change the initial command and execute it manually:
`cd "C:\vscode-issue-43093" ; "C:\Program Files\nodejs\npm.cmd" run-script serve:debug -- --inspect=8004 --debug-brk` (note additional `--` before `--inspect` and `--debug-brk)

everything is being launched and passed correctly then:
`cross-env NODE_ENV=development nodemon --config ./nodemon.json --exec {{pwd}}/node_modules/.bin/ts-node ./src/index.ts --project ./tsconfig.development.json "--inspect=10706" "--debug-brk"` (note the `--inspect=5858` and `--debug-brk` args)

So it seems to me that for a case with `npm` as `runtimeExecutable`  `--inspect`, `--debug-brk`, etc. should be passed after `--`.

**Comment by weinand** [comment]
@Deilan thanks for the investigation.

In the node debugger we do not want to understand (and hardcode) all the idiosyncrasies of the tools that you could use as a "runtimeExecutable". 

In your launch configuration please add a "--" argument as the last item in the "runtimeArgs" array attribute and see whether this makes a difference:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch via nodemon",
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "serve:debug",
                "--"
            ],
            "restart": true,
            "console": "integratedTerminal",
            "internalConsoleOptions": "openOnSessionStart",
            "skipFiles": [
                "node_modules/**",
                "<node_internals>/**"
            ]
        }
    ]
}
```
Doing it this way is way more transparent than having some "magic" that works for 'npm' but not for 'foobar'.

**Comment by liqwid** [comment]
@weinand how about adding a technique with the runtimeArg "--" and adding "--inspect-brk=PORT" to the docs?

because I believe that --inspect-brk should rather reside in `launch.json` then in `package.json`

this is the full config example that launches a regular npm script:
```
{
    "type": "node",
    "request": "launch",
    "name": "Debug tests",
    "runtimeExecutable": "npm",
    "cwd": "${workspaceRoot}",
    "runtimeArgs": [
        "run-script",
        "debug",
        "--"
    ],
    "args": [
        "--inspect-brk=9898"
    ],
    "port": 9898
}
```

btw, you can change `--inspect-brk` to `--inspect` for no breakpoint stops.

**Comment by weinand** [comment]
Your approach only works if you are using a version of npm that supports the "--" argument and your package.json defines a script that interprets an appended "--inspect-brk=9898" correctly.

E.g. this package.json script will work:
```json
  "scripts": {
    "start": "node"
  },
```
but this does not
 ```json
  "scripts": {
    "start": "node test.js "
  },
```
because if a "--inspect-brk=9898" is appended the effective command becomes:
```
node test.js --inspect-brk=9898
```
and here the "--inspect-brk=9898" will have no effect because it is passed to the test.js program instead of the node runtime. 

So the workaround for this is to create a script that has the "--inspect-brk=9898" in the correct position:
 ```json
  "scripts": {
    "start": "node test.js",
    "debug": "node --inspect-brk=9898 test.js"
  },
```


BTW, there is no need to specify the "--inspect-brk=9898" and the "port": 9898.
So the following is the recommended way to launch an npm script in debug mode:
```
{
    "type": "node",
    "request": "launch",
    "name": "Debug tests",
    "runtimeExecutable": "npm",
    "runtimeArgs": [
        "run-script",
        "start",
        "--"
    ]
}
```

**Comment by liqwid** [comment]
Thanks for explanation! :)

Still it's hard to find this info and I believe docs could be expanded to cover cases where "--" argument is required(e.g. npm > 2). I'll try to file a pull request on this one if one doesn't exist yet, please let me know if any additional useful information could be added.

**Comment by weinand** [comment]
I don't think that VS Code should document how "npm" works...
But I'll raise this issue with the owners of the documentation and the "VS code Recipes".

/cc FYI @gregvanl @auchenberg
