### ISSUE TITLE
Needed: Command-By-Extension Tracker

### ISSUE THREAD

**Issue by CodeMouse92** [Microsoft/vscode#43099]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 17.10

I've noticed that it is possible for multiple extensions to take control of the same function, button, or commend. For example, I recently had an issue that turned out to be [`AStyle` taking over for `C/C++` on the `Format Document` command](https://github.com/Microsoft/vscode-cpptools/issues/1519#issuecomment-363596788). Obviously, this is essential and expected behavior, but it is frustrating how much effort and guesswork it takes to determine which extension is doing what.

It would be considerably easier for diagnosing issues if a dedicated Output pane were created, such that when enabled, it would simply display a list of `<command> executed by <extension>` notices, as the commands are run. For example...

```
'Format Document' executed by AStyle
'Format Selection' executed by C/C++
'Format Document' executed by AStyle
'Format Document' executed by AStyle
'Lint Current Document' executed by 'flylint'
```

**Comment by jrieken** [comment]
I believe we already log command invocations but not language feature invocations. Formatting is a special case and similar problems already exist. We might tackle that in a special way (e.g. letting user select a formatter or run formatter in sequence)

**Comment by jrieken** [comment]
We now log each language feature provider invocation. Do this "F1 > Set Log Level > Trace" and "view > log (ext host)" and see how each provider is invoked and how its result is reported back

**Comment by sandy081** [comment]
@jrieken I see provider is invoked with extension name but not sure what is `e` there?

![image](https://user-images.githubusercontent.com/10746682/49520767-49b93680-f8a4-11e8-8af2-c870f6e26bc6.png)

**Comment by jrieken** [comment]
yeah, the `e` is the ctor name - or whatever is left from that...
