### ISSUE TITLE
[css] support `place-items` 

### ISSUE THREAD

**Issue by jamesbarrett95** [Microsoft/vscode#43098]
### Problem statement
Bug [x]
Feature Request []

### Enviornment

- VSCode Version: 1.19.3
- OS Version: Windows 10

### Actual Behaviour
![image](https://user-images.githubusercontent.com/15526293/35920907-2274f918-0c11-11e8-849e-1ea1be0dd1c3.png)

### Steps to Reproduce:

1. In a CSS file, write ```place-items: center center```

Does this issue occur when all extensions are disabled?: Yes

### Additional Information

```place-items``` documentation: https://developer.mozilla.org/en-US/docs/Web/CSS/place-items

**Comment by aeschli** [comment]
It's still in a working draft so we have to see when we adopt it.

**Comment by connorshea** [comment]
Also tracked here: https://github.com/mdn/data/issues/228

**Comment by connorshea** [comment]
mdn/data v2.0.0 now includes `place-items`, just need to update to that version :)

**Comment by octref** [comment]
OK, will do next month. Thanks!
