### ISSUE TITLE
TYPO -> VSCode Intellisense -> cloneWithRows() pop-up

### ISSUE THREAD

**Issue by Haribo7891** [Microsoft/vscode#43091]
- VSCode Version: Version 1.19.3 (1.19.3)
- OS Version: macOS High Sierra 10.13.3 (17D47)

Steps to Reproduce:

1. The Intellisense pop-up for `cloneWithRows()` has a typo in the first paragraph on the word _information_. Currently it is: `Clones this ListViewDataSource with the specified dataBlob and rowIdentities. The dataBlob is just an aribitrary blob of data. At construction an extractor to get the interesting **informatoin** was defined (or the default was used).`

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Please open this issue against whichever library you are using.
