### ISSUE TITLE
You cannot add file from WinRar

### ISSUE THREAD

**Issue by aboodh95** [Microsoft/vscode#43094]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

I don't know if this is important but you cannot add file to your project in case the file in WinRar, once you make the drag and drop you will get this error 
![image](https://user-images.githubusercontent.com/12459798/35916004-5b034ec2-0c22-11e8-8a3b-7ed2a31cb4ee.png)

**Comment by bpasero** [comment]
@aboodh95 does it work if you configure `"workbench.editor.closeOnFileDelete": false` ?

**Comment by aboodh95** [comment]
it's not working, still getting the error

**Comment by bpasero** [comment]
@aboodh95 ah so the file actually is still within the ZIP archive is that true? I think you will first have to unzip that archive to open the file.

**Comment by aboodh95** [comment]
yes, the file inside the zip,

Thank you

**Comment by bpasero** [comment]
We do not support that at the moment, you need to unzip first.
