### ISSUE TITLE
Untitled file save as the same name of a directory in current directory

### ISSUE THREAD

**Issue by SiqingYu** [Microsoft/vscode#43107]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 16.04
![peek 2018-02-08 08-28](https://user-images.githubusercontent.com/22290018/35948971-2a1695b6-0caa-11e8-8952-85b405c70fd5.gif)

If there is a directory  `foo/` in the current directory, and I want to save a *untitled* file as `foo` in the current directory, the explorer automatically changes into the `foo/` directory.
I proposed this as a  trivial feature request.
Of course, I can create the file in a shell.
If you feel like this does not make a difference, feel free to close this.

**Comment by isidorn** [comment]
@SiqingYu can you please attach a gif or a picture to clarify what you are trying to do
Thanks
