### ISSUE TITLE
Untitled file save as the same name of a directory in current directory

### ISSUE THREAD

**Issue by SiqingYu** [Microsoft/vscode#43108]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 16.04

If there is a directory  `foo/` in the current directory, and I want to save an **untitled** file as `foo` in the current directory, the explorer automatically changes into the `foo/` directory.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/43107
