### ISSUE TITLE
Allow users to set default location of `Terminal/Output/..` pane

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#43106]
Currently every project you open, when you open the Terminal it will always be on the bottom.

I really wish you could make it so that the `Terminal` sidebar will always open to the right like so:

![2018-02-07 at 17 18](https://user-images.githubusercontent.com/6391776/35927408-ef5d80ee-0c2a-11e8-8cbe-68252ca324b8.png)

Perhaps you can do this already. But I searched for it in settings and couldn't find it.

**Comment by isidorn** [comment]
@nikitavoloboev I think I already replied to you on gitter
