### ISSUE TITLE
Tab Indent Randomly Stops Functioning

### ISSUE THREAD

**Issue by ConduciveMammal** [Microsoft/vscode#43109]
Not entirely certain here, every so often, couple of times a day, tab indenting will completely disable, I can Shift+Tab to reverse indent but not the other way, it's so sporadic, there's no telling what's causing it, and seems to happen in all types of files. Normally I'll return to the code to see it no longer works, but just now I was indenting some CSS and it stopped functioning on the third tab. Just stopped completely, requiring two reloads to return.

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-caniuse|aka|0.5.3
avocode|avo|0.0.3
vscode-custom-css|be5|2.7.0
color-info|bie|0.5.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
vscode-liquid-snippets|kil|1.1.0
start-git-bash|McC|1.2.1
vscode-autoprefixer|mrm|2.1.2
debugger-for-chrome|msj|4.1.0
language-liquid|nei|0.0.3
new-cmd|odo|0.2.0
live-sass|rit|1.2.0
LiveServer|rit|3.1.0
code-settings-sync|Sha|2.8.7
trailing-spaces|sha|0.2.11
stylelint|shi|0.32.0
highlight-matching-tag|vin|0.4.4
html-css-class-completion|Zig|1.16.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@ConduciveMammal It could be that one of the extensions you have installed is causing this. Run `code --disable-extensions` and see if you still get the issue.
