### ISSUE TITLE
tab-space-heuristics cannot figure out correct tab size if indentation level is 4 spaces but a tab is 8 spaces

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4310]
(This is not a bug but just a funny use case from the past where tabs where fixed at 8 spaces and if you wanted to use an indentation size of 4 the editor would either insert 4 spaces for one level or a tab for two levels).

I have lots of (old) C/C++ file that use an indentation of 4 spaces but use a tab for every 8 spaces. So spaces and tabs are mixed everywhere. The heuristics guesses the tab size to be 4.

```C
static char *mapfont(f)
char *f;
{
    struct fontmap *ftp;

    for (ftp= fontmap; ftp->name != NIL; ftp++) {
	if (strcmp(f, ftp->name) == 0)
	    break;
    }
    if (ftp->name != NIL)
	f= fontmap[ftp->ref].name;
    else {
	fprintf(stderr, "don't know font %s\n", f);
	f= NIL;
    }
    return f;
}

```

You can just close this after having seen it...

**Comment by alexandrudima** [comment]
Indeed:
```
linesIndentedWithTabsCount: 5, linesIndentedWithSpacesCount: 7
indentationGuesser.js:128 spacesDiffCount: 9,0,0,0,8,0,0,0,0
indentationGuesser.js:129 tabSize: 4, tabSizeScore: 8
```

The current strategy wants to find a tabSize that minimizes differences, which it kinda succeeds at :).

I think it could be further improved by starting to look at the content. It would be cool for it to understand that lines ending in `{` should have a smaller indent than the following line, etc.
