### ISSUE TITLE
How may I tell vscode html format, not to send my comments to a new line?

### ISSUE THREAD

**Issue by pillaiindu** [Microsoft/vscode#43102]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 16.04

I put comments on ending divs like the following
```
<div class="col">
  <div class="row">
    <div class="card">

      <h1>Some heading</h1>
      <p>Some text for the card.</p>
      <img src="some/image.jpg" alt="">

    </div> <!-- /.card -->
  </div> <!-- /.row -->
</div> <!-- /.col -->
```

I have also configured my emmet to put the closing div tag comments on the same line as the closing tag.

**The problem**
When I format the document inside VSCode (Ctrl+Shift+I), it sends all of my closing div comments to the new line like the following,

```
<div class="col">
  <div class="row">
    <div class="card">

      <h1>Some heading</h1>
      <p>Some text for the card.</p>
      <img src="some/image.jpg" alt="">

    </div>
    <!-- /.card -->
  </div>
  <!-- /.row -->
</div>
<!-- /.col -->

```

Which is a problem for me, and I have to manually backspace them back to the closing div tags.
I wish a setting like `"html.format.commentOnNewLine": true,` which I set to `false` to get the desired effect.

Thank you for the nice editor!

**Comment by aeschli** [comment]
We use jsbeautify as the underlying formatter. You have to file the feature request there:
https://github.com/beautify-web/js-beautify

**Comment by pillaiindu** [comment]
Thank You @aeschli !

I [filed the feature](https://github.com/beautify-web/js-beautify/issues/1337) at js-beautify. :)
