### ISSUE TITLE
Linkification in terminal is unreliable

### ISSUE THREAD

**Issue by eloff** [Microsoft/vscode#43112]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.24
gitlens|eam|7.5.10
Go|luk|0.6.73

---

Steps to Reproduce:

1. setup multi-root project (may reproduce with single project, but I haven't tested that)
2. in terminal in directory of first project run go build . or go test . with errors

Sometimes the links are added, sometimes they are not, sometimes they are added after a very long delay. Sometimes it looks like they are added (you can see the underline on hover), but then there's some additional output and suddenly they are gone. It seems like scrolling the terminal up/down briefly helps most of the time. The file names don't change, so this has something to do with the rendering or linkification in the terminal. I try option-click on the file names even without seeing the underline on hover, but it has no effect. Typing in the terminal does not help (so the linkification doesn't work even if the terminal clearly has focus.)

Reproduces without extensions: Not tried

**Comment by Tyriar** [comment]
This should be fixed in the upcoming release 😃
