### ISSUE TITLE
How to execute command using zsh

### ISSUE THREAD

**Issue by PixelT** [Microsoft/vscode#43118]
I have installed oh-my-zsh + I set in my settings:
```
"terminal.integrated.shell.osx": "/bin/zsh"
```

But when I try to execute command, it's open `Output` tab with message:
```
Execute 'Terminal' command...
/bin/sh: workbench.action.terminal.toggleTerminal: command not found
```

When I open `Terminal` tab, I normally have zsh (instead of bash)

how to fix it?

**Comment by Tyriar** [comment]
What's the "Output tab" you're referring to? Can you point it out in a screenshot?

**Comment by PixelT** [comment]
![](https://i.imgur.com/GBQv25D.png)

**Comment by Tyriar** [comment]
😕 it looks like you're trying to run a command as a shell script somehow.

What command are you running to trigger this? Normally toggle terminal is ctrl+` or you can run it in the command palette (F1, type "toggle terminal").

Also do you have any extensions installed?

**Comment by PixelT** [comment]
`ctrl + `` toggle terminal normally, also `toggle terminal` from command palette toggle terminal.
I installed https://github.com/robbyrussell/oh-my-zsh but on terminal it works OK.
I use https://marketplace.visualstudio.com/items?itemName=gsppvo.vscode-commandbar and execute terminal by:
```
        {
            "text": "Terminal",
            "commandType": "pallete",
            "command": "workbench.action.terminal.toggleTerminal"
        }
```

**Comment by Tyriar** [comment]
@PixelT that extension appears to provide similar functionality to the tasks feature in VS Code https://code.visualstudio.com/docs/editor/tasks, it doesn't launch VS Code commands.

The terminal can be launched using the following:

- ctrl+\`
- Command palette (F1, "toggle terminal")
- Custom keybinding
- The view menu
