### ISSUE TITLE
Allow to close tabs to the left

### ISSUE THREAD

**Issue by thatbignerdguy** [Microsoft/vscode#43119]
Hey guys, thanks for making this great software! 

I just recently moved completely over to vscode, but one feature I really miss from my old editor was a "close tabs to the left" button. It comes in real handy when you've got a lot of tabs open and you want to isolate some in the middle.

Sorry if this is a duplicate request, I searched and couldn't find it anywhere.

Thanks again!

**Comment by data83** [comment]
As of May 2018 this has been implemented.
Simply add the following to your User Settings JSON:
`"workbench.editor.tabCloseButton": "left",`

**Comment by thatbignerdguy** [comment]
@data83 That setting just moves the actual close button for the tab to the left. This feature request is asking for the ability to close all of the tabs to the left of a tab (the inverse of "Close to the right" button when you right click on a tab).

**Comment by bpasero** [comment]
@thatbignerdguy did you see there is a command to do this:

![image](https://user-images.githubusercontent.com/900690/39670174-3651447c-50ff-11e8-81d1-8667051a0082.png)

**Comment by thatbignerdguy** [comment]
@bpasero Yes, thank you. This feature request is to add it to the context menu of the tabs, next to the "Close to the Right" button:

![image](https://user-images.githubusercontent.com/3871200/39936292-db8c04e0-5500-11e8-8553-c71917910c25.png)

Should I edit the title and/or description of the top comment?

Thanks!

**Comment by bpasero** [comment]
An extension should be able to provide this!

**Comment by thatbignerdguy** [comment]
@bpasero I tried writing this as an extension before, but I was unable to get the context menu item to appear in the correct place. I could only get it to appear in a new group before or after all of the other context menu groups. I couldn't get it to be placed within the "close" grouping next to the "Close to the Right" button.

Do you know if this is possible with the current extension API?

Thanks again!
