### ISSUE TITLE
[json] Merge default snippets for 'allOf

### ISSUE THREAD

**Issue by hipstersmoothie** [Microsoft/vscode#43117]
- VSCode Version:
- OS Version:

bar.schema.json
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "allOf": [
        {
            "type": "object",
            "defaultSnippets": [
                {
                    "body": {
                        "prop1": ""
                    }
                }
            ],
            "properties": {
                "prop1": {
                    "type": "object"
                }
            }
        },
        {
            "type": "object",
            "defaultSnippets": [
                {
                    "body": {
                        "prop2": ""
                    }
                }
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        }
    ]
}
```

Steps to Reproduce:

1. Use bar.schema.json
2. Create a JSON file and trigger suggestions
3. expect a default Snippet to have both prop1 and prop2, but its only the ones defined in the schema are present

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by aeschli** [comment]
I think It's really up to the schema author to define what default snippets there should be. If you want a snippet that contains the properties of all 'allOf' variables, define it at the level of the 'allOf'.
No action planed here.
