### ISSUE TITLE
Allow to "close" folders to ignore them in certain features like searching

### ISSUE THREAD

**Issue by leonardosalles** [Microsoft/vscode#43115]
- VSCode Version: 1.19.3
- OS Version: Windows 10 

Feature request:
Please add the feature to close folders from workspace and  then the search don't perform in these folders, it is so terrible to have multiple folders because you search for a file that you know that is in the actual project an a bunch of trash files appear.

**Comment by bpasero** [comment]
@leonardosalles you can remove a folder from the workspace easily:

![image](https://user-images.githubusercontent.com/900690/35931860-5720d356-0c36-11e8-8636-a8a421018db9.png)

**Comment by leonardosalles** [comment]
@bpasero Sure, I know that but I am talking about a close folder, without remove it, so I can close all the folders and reopen when I want to work on them.

**Comment by roblourens** [comment]
You can pick a folder to search in by right clicking and using "Find in Files". It will put a pattern in the "files to include" box. You can also use that box to search in multiple folders.

**Comment by leonardosalles** [comment]
Dude, this is not the purpose of the issue, a  bunch of IDE's have this feature, you can add a bunch of folders and close them whenever you want, I know that I can right click in folder to search inside, I know that I can remove folders, but it will be easy if vscode have the same feature of anothers IDE's, you add a bunch of folders, close them, and open the only one that you are working at the moment. You guys never saw this feature before???
