### ISSUE TITLE
git changes in gutter to open file do not go away after commit is made

### ISSUE THREAD

**Issue by shelbyspeegle** [Microsoft/vscode#43110]
### Issue Type
Bug

### Description

i'm not exactly sure the name of this feature, but i am referring to the green / blue 'hinting' in the gutter that show when changes are made to a file tracked by git.
![s](https://user-images.githubusercontent.com/7694692/35928083-862b8af8-0be9-11e8-9f1b-e699700c906b.png)

repro steps (see attached video):
1. make changes to a file tracked by git (note hinting appears).
2. add the changes to the staging area.
3. commit the changes.
4. at this point i would expect the hinting in the gutter to go away because the changes have been committed.
5. push changes (step not necessary but shown in attached video).
6. close file that had committed changes.
7. reopen file with that had committed changes.
8. note that the hinting in the gutter are now updated (not present).

![a](https://user-images.githubusercontent.com/7694692/35927956-399252da-0be9-11e8-96bd-c0ee510ce2f2.gif)

is this a bug or is there a setting to address this? i tried `"git.autofetch": true,` in hopes that might help, but it does not.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (f9398645d1d624538708eeebf96e6fdeb546f5d7, 2018-02-06T15:10:07.211Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|/Users/sspeegle/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled
Reproduces without extensions

**Comment by shelbyspeegle** [comment]
looks like duplicate of to #43092.

**Comment by octref** [comment]
Thanks for finding the duplicate! Let's track it in #43092.
