### ISSUE TITLE
Quickpick input tooltips can become out of sync with its placeholder content

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#43114]
- VSCode Version: 1.19
- OS Version: Windows 10

The tooltip over the input (for the placeholder), shows the wrong content (previous content) if the quickpick is replaced with a new one.

For example, in GitLens if you open file or branch history in a quickpick and see the tooltip over the input (it should be correct), but then pick one of the commits (which will open a new quickpick), and see that the tooltip over the input will still show the previous tooltip content, not the updated content.

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
Good catch 👍
