### ISSUE TITLE
Issue Reporter is blank

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#43123]
- VSCode Version: Version 1.20.0-insider
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Help -> Report Issue
2. It opens a blank window with "Issue Reporter" as the title

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
Could you open the dev tools with `Ctrl+Shift+i` and report any errors you see? Are you on the latest version of insiders?

**Comment by RMacfarlane** [comment]
Thanks. This may be a duplicate of https://github.com/Microsoft/vscode/issues/42808, do you have any extensions installed and enabled? Are you able to update to a newer version of insiders?

**Comment by andy-ms** [comment]
As far as I can tell I'm on the latest version that was published to Linux Mint's update manager. But the listed date in help -> about is Feb 2.

**Comment by RMacfarlane** [comment]
@Tyriar Any idea why this package would be stale?

**Comment by Tyriar** [comment]
@RMacfarlane when we freeze Insiders and do manual Insiders builds these don't make it to the apt repo unless I manually publish them.

**Comment by andy-ms** [comment]
Thanks, got the update and it's fixed now.
