### ISSUE TITLE
spawn pidof ENOENT error

### ISSUE THREAD

**Issue by UTexas80** [Microsoft/vscode#43128]
- VSCode Version:
Version 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:09:39.780Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:
Windows 10

Steps to Reproduce:
The only steps I can include to reproduce the problem is:
1. Open Visual Studio Code - the message appears on startup and
2. It also happens whenever I change a theme

Does this issue occur when all extensions are disabled?: Yes/No 
Yes

**Comment by aeschli** [comment]
@UTexas80 Where does this show up? Can you check the console in the Developer Tools for more information?
Maybe a dup of https://github.com/Microsoft/vscode/issues/40237#issuecomment-351890737?

**Comment by aeschli** [comment]
Please also check the various log files:
![image](https://user-images.githubusercontent.com/6461412/35969926-c63117be-0cc8-11e8-8f43-19bd9dfeab94.png)

**Comment by UTexas80** [comment]
Hello 
I had checked #40237 and it didn't appear to be a duplicate.
- The error appears the first time I startup the program
- It also happens whenever I change the theme....Here is a snapshot of the Developer Tools [console:](url)
`
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.terminal.focus
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.toggleZenMode
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  editor.foldAll
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.showCommands
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.showCommands
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.quickOpen
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.gotoSymbol
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.joinTwoGroups
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.openGlobalSettings
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.gotoLine
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.splitEditor
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  extension.queryBuild
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.slurpSexpForward
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.slurpSexpBackward
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.barfSexpForward
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.barfSexpBackward
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.spliceSexp
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.splitSexp
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.wrapAroundParens
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.wrapAroundSquare
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.wrapAroundCurly
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  paredit.indentRange
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  mysql.runQuery
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  theme_swapper.swapTheme
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  workbench.action.reloadWindow
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  editor.action.showSnippets
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
keybindingsRegistry.ts:202 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  openhab.basicUI
e._assertNoCtrlAlt @ keybindingsRegistry.ts:202
console.ts:123 [Extension Host]% Object
console.ts:123 [Extension Host]% Object
console.ts:123 [Extension Host]% null
console.ts:123 [Extension Host]% null
console.ts:123 [Extension Host] NS: NightSwitch is now active!
messageService.ts:126 spawn pidof ENOENT
e.doShow @ messageService.ts:126
messageService.ts:126 spawn pidof ENOENT
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e._showMessage @ mainThreadMessageService.ts:70
e._showMessage @ mainThreadMessageService.ts:40
e.$showMessage @ mainThreadMessageService.ts:34
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
messageService.ts:126 spawn pidof ENOENT
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e._showMessage @ mainThreadMessageService.ts:70
e._showMessage @ mainThreadMessageService.ts:40
e.$showMessage @ mainThreadMessageService.ts:34
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
messageService.ts:126 spawn pidof ENOENT
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e.resume @ messageService.ts:64
(anonymous) @ workbench.ts:1008
e.fire @ event.ts:142
(anonymous) @ quickOpenController.ts:534
messageService.ts:126 spawn pidof ENOENT
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e.resume @ messageService.ts:64
(anonymous) @ workbench.ts:1008
e.fire @ event.ts:142
(anonymous) @ quickOpenController.ts:534
messageService.ts:126 spawn pidof ENOENT
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e.resume @ messageService.ts:64
(anonymous) @ workbench.ts:1008
e.fire @ event.ts:142
(anonymous) @ quickOpenController.ts:534
messageService.ts:126 spawn pidof ENOENT
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e._showMessage @ mainThreadMessageService.ts:70
e._showMessage @ mainThreadMessageService.ts:40
e.$showMessage @ mainThreadMessageService.ts:34
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560


Also, can you please tell me how I can access the log files?

Thank you.

**Comment by UTexas80** [comment]
Hello
I had checked #40237 and it didn't appear to be a duplicate.
- The error appears the first time I startup the program
- It also happens whenever I change the theme....Here is a snapshot of the
Developer Tools [console:](url)
`
[image: Inline image 1]

Also, can you please tell me how I can access the log files?

Thank you.

On Thu, Feb 8, 2018 at 6:09 AM, Martin Aeschlimann <notifications@github.com

**Comment by aeschli** [comment]
The screenshot didn't get attached. Can you try doing this with the web UI (https://github.com/Microsoft/vscode/issues/43128)?
Theme switching does not spawn a process, so it's likely some other functionality that listens on setting changes.
- Did you validate that the `git.path` is a valid path as described in #40237
- Did you try running VSCode with all extensions disabled? See [here](https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) for instructions
- To see the logs, open the output view (View > Output) and use switcher to get to the logs. 
Even better: run vscode with `code --upload-logs` and follow the instructions.

**Comment by UTexas80** [comment]
![image](https://user-images.githubusercontent.com/16102161/35979464-6a324fe4-0cb6-11e8-8220-c5eec72998b0.png)

**Comment by aeschli** [comment]
- Did you validate that the `git.path` is a valid path as described in #40237
- Did you try running VSCode with all extensions disabled? See [here](https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) for instructions

**Comment by UTexas80** [comment]
1. Git Path is a valid path
2. ran VS code with all extensions disabled .Problem has not resurfaced under this condition.

**Comment by UTexas80** [comment]
When I re-enable the extensions the code reappears.

**Comment by UTexas80** [comment]
Thank you for reopening this issue...

**Comment by aeschli** [comment]
@UTexas80 Thanks for finding out that this is related to extensions.
It would be great if you could find out which one causes this. Maybe try the 'R' extension first (Ikuyadeu.R).

**Comment by UTexas80** [comment]
Thank you for following up. Will do. Since it is my work PC (and I don't have remote access) I will look at it the first thing Monday morning.
Cheers.

**Comment by UTexas80** [comment]
I don't know if it is any consolation but I decided to try a little reverse logic. I have the following copy of VS Code on my home pc.

Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

The only extensions installed include:
dark-plus-syntax, Ond Dark Pro, the aforementioned R LSP client, Relative Path and Settings Sync.

For my test, I changed themes and didn't get the dreaded 'spawn pidof ENOENT' error. 
From what I can discern, the difference between my home PC and work PC VS Code versions is that for the R LSP client extension, I added an extra installation step at home by including a reference to the R Language Server. I don't remember providing that step for my work PC. Irregardless, I am going to follow up on your recommendation and remove this extension from my work PC tomorrow. 

Cheers,

Glen

**Comment by UTexas80** [comment]
![spawn43128](https://user-images.githubusercontent.com/16102161/36673837-23834484-1ad2-11e8-8cb9-c5383b851359.png)
 I removed the R Support & R LSP client extension(s) but unfortunately I am still receiving the spawn pidof ENOENT error.

**Comment by UTexas80** [comment]
I have the R Support, R Development and R LSP Client extensions loaded for a couple of weeks on my Code Insiders program [Version 1.21.0-insider] and  have not experienced any issues yet. It is just the vanilla Visual Studio Code that I'm having problems.

**Comment by aeschli** [comment]
@Microsoft/vscode Any ideas on who is spawning `pidof`?

**Comment by UTexas80** [comment]
quick question to help me troubleshoot. I looked around but was not able to find out how to search my extensions using some 'not' logic. For instance, I know that I can find enabled or installed extensions but how do I find extensions that are NOT themes (since I have about 500 of them).
ty.

**Comment by bpasero** [comment]
There seem to be similar issues: https://github.com/Microsoft/vscode/issues/40237 and https://github.com/Microsoft/vscode/issues/44296

**Comment by UTexas80** [comment]
On the plus side, at least I'm not alone

**Comment by UTexas80** [comment]
My gut instinct is the "theme-switcher" extension; so I am going to disable it, see what happens and then let you know. fingers crossed.

**Comment by UTexas80** [comment]
Nope...that wasn't it. back to the drawing  board.

**Comment by UTexas80** [comment]
Good news and bad news. 
Good News ->The last package I uninstalled was causing the spawn endot error so the issue seems to be corrected.
Bad News -> I don't remember the name of the package. 

Is there anyway I can get a history log of my installs / uninstalls?

Thank you.

**Comment by UTexas80** [comment]
I uninstalled it yesterday and the log file only contains entries from today. I am so bummed.

**Comment by aeschli** [comment]
closing the issue as we have not been able to pin it down. Also there hasn't been many other reports on the issue.
