### ISSUE TITLE
Add `trailing` option to `editor.renderWhitespace`

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#43127]
Please add an option to `editor.renderWhitespace` that has a similar effect to the existing `boundary` option, but only renders whitespace on the trailing (right) side.

And for symmetry, maybe a `leading` option too, for the left side?

**Comment by jlippuner** [comment]
Bump. I'd like this feature too

**Comment by akelsch** [comment]
I agree. `"editor.renderWhitespace": "boundary"` renders inner whitespace which I don't like.

Languages relying on indentation get unnecessarily cluttered. Look at how VSCode renders the following Haskell code snippet (CTRL+F ·· to highlight):

```
lcp :: Eq a => [a] -> [a] -> [a]
lcp [] _··= []
lcp _··[] = []
lcp (x : xs) (y : ys) | x == y····= x : lcp xs ys
······················| otherwise = []
```

What I would like is the following:

```
lcp :: Eq a => [a] -> [a] -> [a]
lcp [] _  = []
lcp _  [] = []
lcp (x : xs) (y : ys) | x == y    = x : lcp xs ys
······················| otherwise = []
```

We can achieve this behavior in other IDEs like IntelliJ by toggling leading/inner/trailing whitespace individually:

![09605af10d80fd3fcc0c41e4537b0950](https://user-images.githubusercontent.com/28652314/59035538-c934bc00-886d-11e9-9e46-687debbef6ab.png)
