### ISSUE TITLE
Recognise inline JSDoc in function parameters/arguments

### ISSUE THREAD

**Issue by vp2177** [Microsoft/vscode#43121]
- VSCode Version: 1.19.3

Steps to Reproduce:

1. With the following code: 
```
function someFunction(/**string*/ aString) {
  ...
```
2. Hover over `someFunction`. I'd expect `aString` to be shown with `string` type, as is the case with the following code:
```
/** @param {string} aString */
function someFunction(aString) { 
  ...
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Try:

```js
function someFunction(/** @type {string} */ aString) {
    ...
```

**Comment by vp2177** [comment]
Oops, thank you - should have thought of that.
