### ISSUE TITLE
Cancel completions dialog on backspace

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#43122]
- VSCode Version: Version 1.20.0-insider
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Type:
```ts
const x = {a: 0};
x.
```
2. Decide against it. Quickly type backspace then enter.
3. Expected: `x\n`. Got: `xa`. Meaning, it accepted completions even *after* I had backed out.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
@jrieken Just saying, I can't repro it on mac.

**Comment by jrieken** [comment]
When I am quick enough I can reproduce... Maybe some debounce'ing that hits us.

**Comment by jrieken** [comment]
I am not able to reproduce anymore...
