### ISSUE TITLE
JSONC syntax highlight for internal settings.json

### ISSUE THREAD

**Issue by myfonj** [Microsoft/vscode#43120]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Reproduces without extensions: Yes

## STR:
1) Invoke "Preferences: Open User Settings" command or open `settings.json` file directly.
2) Observe chosen syntax is JSON, although this file is internally processed as JSONC.
3) If the file contains no `// comment` type one there and save.
4) Observe comment being highlighted as a syntactic error.
5) Change syntax to JSONC.
6) Observe no syntactic error highlight.
7) Close the editor.
8) Repeat step 1.

## Expected outcome:
`settings.json` is opened as JSONC file, at least when opened for the second time.

## Actual outcome:
`settings.json` is opened as plain JSON file every single time.

---

It is almost impossible not to run into this glitch (there is a comment line in the default config file, isn't there?), so I hardly believe it wasn't reported already (yes, I searched and found nothing).  If there is some easy workaround (like renaming the file or something), please pardon me and let me know (and take this report as a sign it wasn't communicated sufficiently).

**Comment by aeschli** [comment]
I'm not able to reproduce this and it's surprising as the JSONC language definition has 'settings.json' is explicitly associated with jsonc: https://github.com/Microsoft/vscode/blob/2fbfa8d500d05706205ea12cd8dde6a8effc20c8/extensions/json/package.json#L61

Do you maybe have a user setting or any other extension that changes the file associations?

**Comment by myfonj** [comment]
Ah, you are right, got `"files.associations":{"*.json": "json"}` buried in my settings, no clue why X|
Thanks a lot for the pointer and sorry for wasting your time.
