### ISSUE TITLE
trying to type a tab character over a sequence of spaces results in unexpected behaviour

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4312]
If I want to align the two comments in the following snippet, I would select the spaces between the ';' and '/' and replace them with one or more tabs. In VS Code this results in an unexpected behaviour: the whole lines are indented by one tab instead of replacing the selected spaces with a tab.  

```js
var foo = 123;       // this is a comment
var bar = 4;       // another comment
```

**Comment by coe-jeubanks** [comment]
A related problem I've found in VS Code 1.0:

With VS Code option: "editor.insertSpaces": set to true, snippets only translate \t characters to spaces when they are at the beginning of the string.

Following snippet correctly translates \t character to spaces:

"If statement": {
"prefix": "if",
"body": [
"if ${true}",
"\t$0",
"end-if"
]
}

Following snippet incorrectly leaves \t as a tab character:

"If statement": {
"prefix": "if",
"body": [
"if ${true}",
"_\t$0",
"end-if"
]
}
