### ISSUE TITLE
PHP Debugger

### ISSUE THREAD

**Issue by InKiev** [Microsoft/vscode#43134]
### Issue Type
Bug

### Description

1. Open a PHP file.
2. Add breakpoint
3. Run debugger

### Expected results
Debugger stops at breakpoint.

### Additional info
Debugger was working before the January's update.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.89GB (0.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.24.0
php-debug|fel|1.12.1
php-symbols|lin|2.1.0
vscode-icons|rob|7.19.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by octref** [comment]
You have opened this issue before: #43041

Please report this issue to https://github.com/felixfbecker/vscode-php-debug
