### ISSUE TITLE
Invert block cursor text color for readability

### ISSUE THREAD

**Issue by josb** [microsoft/vscode#43130]
### Issue Type
Feature Request

### Description

The character under the block cursor is hard to read. Compare the screenshots:

NeoVim running in iTerm2:
<img width="84" alt="inverted foreground color" src="https://user-images.githubusercontent.com/50617/35940765-0d242310-0c05-11e8-9af4-51cb6b0f95c5.png">

VS Code:
<img width="157" alt="guess the character" src="https://user-images.githubusercontent.com/50617/35940772-11e24a58-0c05-11e8-9e00-ee0278f8063a.png">

Note how in the NeoVim/iTerm2 combo the foreground color is automatically inverted for readability. It would be great if there was a setting for this.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 16.7.0

**Comment by donkeysmash** [comment]
You could use alpha value make it slightly transparent until this is supported.
For example,
```
"workbench.colorCustomizations": {
    "editorCursor.foreground": "#75dc926b"
}
```

**Comment by josb** [comment]
Thanks for the workaround, @donkeysmash !

**Comment by JeanMertz** [comment]
I'd love to see this happen. The alpha value is a great workaround, but inverting the colors is a lot clearer in my opinion. 👍

**Comment by alexandrudima** [comment]
We are computing it, but computing can only take us so far. This can be defined by the theme or directly in user settings via the colors `editorCursor.foreground` / `editorCursor.background`

e.g.

![image](https://user-images.githubusercontent.com/5047891/67419855-c133a980-f5cd-11e9-868d-5f3ca348cfd4.png)
