### ISSUE TITLE
Image zooming: pinch to zoom gestures are inverted

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#43138]
On a Surface Book with Windows 10, the pinch to zoom using the trackpad is inverted:
 - expanding fingers will zoom out
 - doing the opposite gesture will zoom in

I expect the other way around.

This happens both with stable 1.20 and latest insider:

```
Version 1.20.0-insider
Commit f9398645d1d624538708eeebf96e6fdeb546f5d7
Date 2018-02-06T15:20:43.871Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Windows 10 x64
```

**Comment by warpdesign** [comment]
**update** Same problem when using ctrl + two fingers move.

**Comment by mjbvz** [comment]
Yes pinching also seems inverted on mac os. The zooming when holding ctrl though matches mac os: up to zoom in, down to zoom out. Perhaps this is because of Apple's "natural" scroll direction. I'll take a look at some other windows apps and try to match their behavior

**Comment by warpdesign** [comment]
There is also an option for inverting scrolling in Windows 10: I tried changing it but the bug is still there.

**Comment by mjbvz** [comment]
Please try this out in the next insiders build. I'm not 100% sure my fix handles all possible OS and input device combinations correctly so please provide feedback if something still doesn't feel right

**Comment by user3323** [comment]
@mjbvz 

for win7x64, it's fixed now. Thanks!
