### ISSUE TITLE
Document edits from an extension and the Undo stack

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#4313]
- VSCode Version: 0.10.11, 10.10 & 10.8
- OS Version: Win 8.1

Steps to Reproduce:

1. In a document, type some text.
2. Invoke a command from an extension that makes an edit to the document. (With `TextEditor.edit()`)
3. Press ctrl+z to undo

Would expect steps 1 & 2 to produce separate entries in the undo stack: the edit from (2) to be undone, and the text edit in (1) only with a further undo.
However the undo removes both the edit from (2) and the text from (1)

If, in between steps 1 & 2, you move the text cursor, then 2 separate entries to the undo stack _are_ created, as expected.

Can provide a sample extension if necessary.

**Comment by aminroosta** [comment]
+1

**Comment by 74th** [comment]
+1
