### ISSUE TITLE
Input lag on High Sierra and scaled display resolution mode

### ISSUE THREAD

**Issue by tehapo** [microsoft/vscode#43137]
- VSCode Version: 1.20.0
- OS Version: 10.13.3
- Computer: MacBook Pro (Retina, 15-inch, Mid 2014, NVIDIA GeForce GT 750M) with external 4k monitor

Steps to Reproduce:

1. Open macOS display settings and select a scaled resolution.
2. Start typing and you'll get a small but still noticeable input lag.

Does this issue occur when all extensions are disabled?: Yes

After upgrading to High Sierra I started noticing some input lag while typing. Not a significant delay between the keypress and things happening on the screen, but enough to be annoying. At the time I initially noticed this, I was running on an older version of VSCode, so this is really not a new issue with the 1.20.0 release.

While playing around with display resolutions, it seems like the lag is gone or at least less apparent when not using a scaled display resolution. In my normal setup the external 4k monitor is running on the "Looks like 2560 x 1440" mode. If I change it to the native 3840x2160, the lag seems at least less annoying.

**Comment by rebornix** [comment]
@tehapo I have a similar setup as you do, I can see some lag when scrolling in diff view but not typing. Do you mind helping do some profiling?

1. Command Palette -> Toggle Developer Tools
2. Performance -> Round Button -> Click
3. Type
4. Stop

Then you can see a good waterflow graph and know about the fps rate. Please try to find below section 

![image](https://user-images.githubusercontent.com/876920/35946029-1dca96ce-0c17-11e8-96f3-ae3e8f36874c.png)

This is what happens when you type (`t._type`), and on my machine the fps rate when typing is around 20. It's not good but usually I can't tell the difference between 20 and 60. Let me know if the fps rate is worse on your machine and please let me know how much time does it take to type (including `t._type`, compose layer trees, render, compose, paint, etc). Thanks in advance!

**Comment by tehapo** [comment]
@rebornix Thanks for your fast reply! I did some profiling and the lag actually seems more apparent when adding or removing line breaks and the lines reflow. However this only occurs at seemingly random times. I did manage to capture a profiling session that has a section with fps dropping to 14 fps. Please see the attached screenshot and profiling session as JSON that can be imported into dev tools

<img width="1667" alt="screen shot 2018-02-08 at 22 39 11" src="https://user-images.githubusercontent.com/368220/35997135-40b97e2e-0d21-11e8-9e2a-b4db1849c2d7.png">

[Profile-20180208T224356.json.zip](https://github.com/Microsoft/vscode/files/1708716/Profile-20180208T224356.json.zip)

**Comment by nehvaleem** [comment]
having exact same issue. At least switching to 4k resolution seems to minimze the effect. But it is a dealbreaker for me, using macos on 4k resolution isn't that a great idea overall :) (ofc for movies and games it rocks)

**Comment by tehapo** [comment]
@nehvaleem Do you happen to also have the same Macbook Pro model (Retina, 15-inch, Mid 2014, NVIDIA GeForce GT 750M) or at least the same GPU? I was initially thinking if this might be related to NVIDIA GPU drivers.

**Comment by rebornix** [comment]
@tehapo @nehvaleem can you try to run `code --disable-gpu` and see if the problem is mitigated?

**Comment by mekicha** [comment]
@rebornix  I am also noticing the same input lag on my machine. Running `code --disable-gpu` did not help

**Comment by tehapo** [comment]
@rebornix I tried running VSCode with the `--disable-gpu` flag and looks it helps with the lag on my setup. But at the same time it introduces some very noticeable flickering glitches on the whole editor screen.

**Comment by RoarkeRandall** [comment]
Anecdotal, but I I've been having perf issues since upgrading to 4k monitors w/ scaling enabled. Just switched to "default for display" and the perf is a LOT better when scrolling and typing.

**Comment by tehapo** [comment]
Sounds like this is most likely related to my lag issue.
https://bugs.chromium.org/p/chromium/issues/detail?id=773705#c167

**Comment by tehapo** [comment]
Upgraded to macOS 10.13.4 and the issue still persists.

**Comment by rawksteady** [comment]
I'm currently having the same issue, although older retina model (2012/2013). Adding to it, there's a much more noticable delay when switching tabs/editors and previewing files (single click).

**Comment by wujekbogdan** [comment]
@tehapo
I've noticed the same problem after upgrading macos to 10.3.x, but it has nothing to do with vscode.

I've noticed a lag when typing... but not in another editor. I've also noticed a lag when switching between tabs in Chrome. The lag doesn't appear instantly after changing the resolution, it seems to increase over time. Switching resolution to non-scaled solves the problem.  

It's a known issue, related somehow to Nvidia drivers (not confirmed neither by Apple nor by Nvidia, though). Have a look: https://forums.geforce.com/default/topic/1037574/geforce-apple-gpus/lot-of-slowdowns-or-problems-in-high-sierra-using-recent-nvidia-driver/

**Comment by alexanderchan** [comment]
Similar report here related to graphic problems in high sierra especially when scaling: http://scaleup.us/2017/11/09/high-sierra-slow-chromefirefox-issues/

**Comment by tehapo** [comment]
The input lag I was experiencing seems to be almost gone after I installed some updates. I'm currently running macOS High Sierra 10.13.6 + VS Code 1.26.1 and there is still a small lag, but it's way less noticeable than before.

**Comment by leecommamichael** [comment]
Can anyone confirm that the lag worsens when using the in-built _Solarized Light_ color theme? I've profiled the editor and GPU render delays increase by ~20% with _Solarized Light_. This is so strange, I am still experiencing this lag. 

macOS:  10.13.6
VSCode: 1.27.2

**Comment by tehapo** [comment]
Current setup:
macOS: 10.14.4
VSCode: 1.34.0

The input lag I originally experienced is no longer reproducable. Closing the ticket now.
