### ISSUE TITLE
latest Fedora repository package outdated

### ISSUE THREAD

**Issue by int3l** [Microsoft/vscode#43143]
Current latest version on the [official download web page](https://code.visualstudio.com/Download):
[v1.20](https://code.visualstudio.com/docs/?dv=linux64_rpm) build: code-1.20.0-1518023659.el7.x86_64.rpm ([Release Notes](https://code.visualstudio.com/updates/v1_20))

Current latest version in the [fedora official repo](https://packages.microsoft.com/yumrepos/vscode/):
[v.1.19.3](https://packages.microsoft.com/yumrepos/vscode/code-1.19.3-1516876593.el7.x86_64.rpm) build:  code-1.19.3-1516876593.el7.x86_64.rpm ([Release Notes](https://code.visualstudio.com/updates/v1_19))

Is there a particular reason for the version discrepancy?
Best Regards

**Comment by int3l** [comment]
Labels: linux fedora package update new release

**Comment by octref** [comment]
We are waiting for rpm packages to be signed. It'll be updated soon.

**Comment by batisteo** [comment]
I genuinely wonder why it takes one week to sign the packages.
