### ISSUE TITLE
View state of in-memory editors not preserved

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4314]
Steps to Reproduce:
1. Start debugging session 
2. Click on same stack frame from an internal module - an in-memory editor is opened
3. Ctrl-tab, Ctrl-tab you are back in the in-memory editor, but the view state is not preserved the cursor is at the beginning of the file

**Comment by bpasero** [comment]
To investigate.

**Comment by bpasero** [comment]
I think you fixed that!

**Comment by isidorn** [comment]
Yeah I did 😎
