### ISSUE TITLE
Additional date-based snippet variables

### ISSUE THREAD

**Issue by twwilliams** [Microsoft/vscode#43140]
I'm happy to see the new date-based snippet variables in v1.20.0. I would love to see some additional ones since I wanted to use this for generating journal templates. Something like this:

- **CURRENT_DAYNAME:** Monday, Tuesday, ...
- **CURRENT_DAYNAME_SHORT:** Mon, Tue, ...
- **CURRENT_MONTHNAME:** January, February, ...
- **CURRENT_MONTHNAME_SHORT:** Jan, Feb, ...

Thank you.

**Comment by jrieken** [comment]
A little more tricky because you might want to consider localisation settings...
