### ISSUE TITLE
"Disable all extensions and reload the window" in issue reporter

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#43156]
The issue reporter has a link that says `Try to reproduce the problem after disabling all extensions and reloading the window.` which apparently runs the "Disable all installed extensions" action and reloads the window. That action causes any extension disable or workspace-disable state to be lost. I have several extensions disabled or disabled in different workspaces and it's annoying to lose that state.

Is it possible to simulate starting Code with `--disable-extensions`, which is transient and doesn't affect permanently disabled extensions?

Also, it would be nice if that link showed a confirmation popup, because it's possible to click on accident and reload your windows. I expected it to take me to some doc site when I clicked it.

**Comment by RMacfarlane** [comment]
Changed so that `disabling all extensions and reloading the window` only temporarily effects extension state
