### ISSUE TITLE
URL encoding causes link to not work when ctrl + click

### ISSUE THREAD

**Issue by bmdixon** [Microsoft/vscode#4315]
- VSCode Version: 0.10.11
- OS Version: Windows 10 Version 1511

Steps to Reproduce:

1. Type a URL containing symbols e.g. `http://a-test-site.com/#test=true`
2. Ctrl + Click this URL
3. URL gets encoded into `http://a-test-site.com/#test%3Dtrue` when opened in a browser

**Comment by alexandrudima** [comment]
The string is good right before using URI.parse in links.ts around line 342

**Comment by bmdixon** [comment]
Was this incorrectly associated/closed? That commit looks more like it addresses https://github.com/Microsoft/vscode/issues/4334 than this issue?

**Comment by alexandrudima** [comment]
@jrieken I still see this issue on master

**Comment by jrieken** [comment]
yeah, sorry from issue.

**Comment by jrieken** [comment]
related to #2990
