### ISSUE TITLE
Incorrect display of emphasis in markdown files

### ISSUE THREAD

**Issue by chikean** [Microsoft/vscode#43150]
### Issue Type
Bug

### Description

In markdown files, when multiple words are emphasised using asterisks and separated by commas, VSCode incorrectly displays all subsequent text in that line as emphasised. The effect does not carry through to the live preview.

#### Steps:
1. Create a markdown file (e.g. text.md)
1. Write a line that contains two words using emphasis markdown, separated by a comma (e.g. "Hello I have found some *problems*, *specifically during* my use of emphasis in markdown.")

#### Expected Results:
Only the words 'problems', 'specifically' and 'during' are italicized in the VSCode editor.

#### Actual Results:
The entire phrase 'specifically during my use of emphasis in markdown.' is italicized, while the phrase 'problems' is not.

Screenshot:

![image](https://user-images.githubusercontent.com/18460362/35949480-d4892fd4-0cc5-11e8-9c8a-142fee05d01b.png)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3392)|
|Memory (System)|15.89GB (7.95GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-markdownlint|Dav|0.13.0
vscode-eslint|dba|1.4.5
pgsql|dou|0.1.0
MagicPython|mag|1.0.12
python|ms-|2018.1.0
azure-account|ms-|0.3.0
PowerShell|ms-|1.5.1
vscode-docker|Pet|0.0.24
python|tht|0.2.3

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#1
