### ISSUE TITLE
@sort:rating for the extensions doesn't work correctly

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#43158]
- VSCode Version: All
- OS Version: All

Steps to Reproduce:

1. Select Show Popular Extensions
2. Select Sort by: Rating.
3. Optionally filter by something like C++.

Does this issue occur when all extensions are disabled?: Yes

Bug: The extensions aren't sorted by rating correctly. The top of the list appears to be sorted, but then it becomes unsorted later on. Looks like it sorts partially all the 5 stars at the top and some of the 4.5 starts, then there are un-reviewed extensions followed by the rest in a random order.

![image](https://user-images.githubusercontent.com/19859882/35954405-44619004-0c3e-11e8-9f84-32ee1950e999.png)

**Comment by ramya-rao-a** [comment]
@sean-mcmanus I dont get the same results as you... The below is what I get, which matches the search and sort results of the [marketplace](https://marketplace.visualstudio.com/search?term=C%2B%2B&target=VSCode&category=All%20categories&sortBy=Rating)

![image](https://user-images.githubusercontent.com/16890566/36046021-78a36884-0d8c-11e8-806e-a9e8e33fc957.png)

**Comment by sean-mcmanus** [comment]
Scroll to the bottom to get my screenshot. As I mentioned in the description, the top part is sorted, then it becomes unsorted near the bottom. In addition, your screenshot shows 5 star extensions listed before 4.5 star ones.

**Comment by sean-mcmanus** [comment]
Oh, looks like it's a marketplace bug then.

The C++ extension would like fixes to the marketplace such that our C++ extension is not 3rd from the bottom when sorted by Rating. Most of our lowest ratings are due to issues we've already fixed but we don't have any way to remove the reviews which are no longer valid. I already emailed the marketplace people, but they have not responded at all.

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode/issues/27229#issuecomment-316383722 explains the logic behind the sort by rating

cc @modigrv

**Comment by sean-mcmanus** [comment]
Okay, that explains the behavior, but I think their algorithm weighting is messed up and isn't giving meaningful results. It appears to put 4.5-5 star extensions at the top, followed by unrated extensions, and then 3-4.5 extensions at the bottom, and the C++ extension has a median rating of 4 stars out of 175 review (which would be 5 if the invalid 1 star reviews were omitted) but it's sorted after an extension with an average/median of 3 stars with only 4 reviews total.
