### ISSUE TITLE
in symbols foud  in php 

### ISSUE THREAD

**Issue by ooing** [Microsoft/vscode#43157]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: Extensions are disabled
---

## in sublime
![sublime](https://raw.githubusercontent.com/ooing/image/master/2018-02-08_091753.png)

## in vscode
![vscode](https://raw.githubusercontent.com/ooing/image/master/2018-02-08_091828.png)

**Comment by V-ed** [comment]
Visual Studio Code does not support PHP by default, but you can install the extension [PHP IntelliSense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) from the extension store or within VSCode to start working with PHP in it. This includes the **Find all symbols** feature you are asking about in your issue.

You can read more about PHP in VSCode [here](https://code.visualstudio.com/docs/languages/php).

**Comment by ooing** [comment]
@V-ed  thank
