### ISSUE TITLE
Gutter display still missing in 1.20.0

### ISSUE THREAD

**Issue by johnmhoran** [Microsoft/vscode#43161]
- VSCode Version: 1.20.0
- OS Version: Windows 10 Fall Creator's Update -- Windows 10 Pro Version 1709

Steps to Reproduce:

1.  Open Git Bash
2.  Navigate to project.
3.  Checkout correct branch.
4.  Run `code .`
5.  In Visual Studio Code, open the file to work on.
6.  Make a change in the file and save.
7.  Changes/edits are not displayed in the gutter as they used to be with versions prior to 1.19.1.  In addition, the file count in the SCM view icon does not increment until I close and re-launch VSCode.

Does this issue occur when all extensions are disabled?: Yes.

This issue is a continuation of closed issue #40668 .

The gutter display stopped working for me with 1.19.1.  At the suggestion of @joaomoreno , I installed 1.20.0-insider, which displayed the gutter indicators properly.  This led me to think that when 1.20.0 stable was released, all would be well.

However, earlier today I downloaded and installed 1.20.0 on my Windows 10 laptop -- the same laptop mentioned above -- and the problem I experienced with 1.19 has grown.  The gutter indicator does not display changes, and the source control icon on the left also does not display changes. The latter is a new problem not present in 1.19. When I make a change in a not-yet-edited file, the gutter remains blank and the file count stays the same in the SCM view icon.  If I close and reopen VSCode, the SCM view icon updates to the correct number.

At first glance it seems I may again have to revert to 1.18.

**Comment by joaomoreno** [comment]
Does the same happen if you open Code via the Start Menu, instead of via Git Bash?

**Comment by johnmhoran** [comment]
@joaomoreno Yes -- same behavior if I open VSCode from the Start Menu.  In contrast, the current Insiders edition works fine -- just tried:
```
Version 1.21.0-insider
Commit 91120eb786357aa1e16217ad6a67cf0740f26e8e
Date 2018-02-08T05:16:13.920Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
This was also the case [a month or so ago](https://github.com/Microsoft/vscode/issues/40668#issuecomment-357313814) with the then-current 1.20 Insiders edition, but, alas, not with the 1.20 stable release.

**Comment by joaomoreno** [comment]
Interesting. Maybe you have some settings in your stable release which disable the feature? Can you check?

**Comment by johnmhoran** [comment]
@joaomoreno  I deleted all user settings and disabled all extensions -- the problems remain with the gutter display and SCM view icon counter.  I'm back to using `1.18.1`, which works fine.

**Comment by joaomoreno** [comment]
@johnmhoran Could it be the theme you have installed which hides those colors?

**Comment by johnmhoran** [comment]
@joaomoreno Unfortunately, no: I see the same behavior with other themes, including Visual Studio light, default light, Visual Studio Dark and default dark.  And no problems with any themes I've tried when I use `1.18.1` as well as the current insiders edition.

**Comment by joaomoreno** [comment]
I'm running out of ideas. Here's the summary, let me know if I got anything wrong:

- Stable 1.18.1 works. 1.19 does not work. 1.20 does not work
- Any Insider version works
- Local workspace, using Git for Windows

At this point I'd ask you to run from a brand new user data dir and extensions dir:

```
code --user-data-dir %HOMEDRIVE%%HOMEPATH%\Desktop\user-data-dir --extensions-dir %HOMEDRIVE%%HOMEPATH%\Desktop\extensions-dir
```

**Comment by johnmhoran** [comment]
@joaomoreno  What does it mean to "run from a brand new user data dir and extensions dir"?  And where would I paste the command, and what does it do?

**Comment by joaomoreno** [comment]
Code has a directory where its stores the user settings and another one where it stores extensions. `--user-data-dir` lets you change the first one, `--extensions-dir` lets you change the second one. I'd like you to run Code using new directories and see whether the issue still reproduces. You can point them to some directories in your Desktop, for example; Code will create them for you.

**Comment by johnmhoran** [comment]
Thank you, @joaomoreno .  I've tried the command and several variations.  

The 1.20.1 gutter indicators work:
* When I initially download and install 1.20.1 and open it from the installation wizard.  
* If I navigate to a project in File Explorer and open VSCode by right-clicking on the project folder and selecting `Open with Code`.
* If I navigate to a project in the Windows command prompt and run `code .`.

The 1.20.1 gutter indicators do not work:
* If I do a fresh install of 1.20.1, navigate to my project in Git Bash and run `code .`.
* If I do a fresh install of 1.20.1 and run the command you suggested in the Windows command prompt.

If I do a fresh install and run the equivalent command in Git Bash -- `code --user-data-dir ~/Desktop/user-data-dir --extensions-dir ~/Desktop/extensions-dir` -- VSCode does not open at all, although 2 instances of VSCode are listed in my Task Manager.

The gutter indicators still work in 1.18.1 no matter how I launch the tool, though unfortunately 1.18.1 no longer seems to want to load Git Lens.

**Comment by john-hu** [comment]
I got the same issue with 1.20.1.

I can double confirm @johnmhoran's result. I can only work through command line `code .`.

The way I open the vscode is to click it at Mac Dock in my daily coding. If I open the vscode in this way. The gutter doesn't work.

**Comment by joaomoreno** [comment]
@johnmhoran Do you have any special environment set in your Command Prompt session? Any plugins, extensions in Windows?

**Comment by johnmhoran** [comment]
@joaomoreno No special environment that I'm aware of.  Here are the first 10 lines (i.e., just a portion) of the git output for 3 methods of launching VSCode:

1.  Navigate to a project in Git Bash and run `code .` (gutter not working).  

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.15.1.windows.2 from C:\Program Files\Git\cmd\git.exe
git rev-parse --show-toplevel
git config --get commit.template
git status -z -u
git rev-parse --show-toplevel
git symbolic-ref --short HEAD
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-toplevel
```

2. Navigate to a project in the Windows command prompt and run `code .` (gutter works) (in the 6th line, I've replaced the project name with `[project]`).

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.15.1.windows.2 from C:\Program Files\Git\cmd\git.exe
git rev-parse --show-toplevel
git config --get commit.template
git status -z -u
git show :src/[project]/__init__.py
git check-ignore -z --stdin
git symbolic-ref --short HEAD
git rev-parse develop
git rev-parse --symbolic-full-name --abbrev-ref develop@{u}
```

3.  Open by right-clicking the project directory in File Explorer (gutter works).

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.15.1.windows.2 from C:\Program Files\Git\cmd\git.exe
git rev-parse --show-toplevel
git config --get commit.template
git status -z -u
git rev-parse --show-toplevel
git symbolic-ref --short HEAD
fatal: Not a git repository (or any of the parent directories): .git

git rev-parse develop
git rev-parse --symbolic-full-name --abbrev-ref develop@{u}
```

**Comment by joaomoreno** [comment]
In case (1), does `git show` never get run?

**Comment by johnmhoran** [comment]
You're correct, @joaomoreno -- using Git Bash, `git show` never gets run in 1.20.1 (or in the latest version of the Insiders Build).  With 1.18.1, `git show` is run in the 7th line of the output.

**Comment by john-hu** [comment]
Oh! I think I am in difference case. 

The gutter shows once I disable the perforce scm. In my workspace, I opened a lot of folders, including git projects and perforce projects. The perforce projects are at top of the list. Once the perforce scm is enabled, all gutters of git projects are disappeared.

**Comment by joaomoreno** [comment]
@john-hu Very interesting, created this: https://github.com/Microsoft/vscode/issues/44484

@johnmhoran That's very odd. I just gave Git Bash a try and this is what I see:

<img width="724" alt="screen shot 2018-02-27 at 09 55 52" src="https://user-images.githubusercontent.com/22350/36719136-725cf9a6-1ba4-11e8-85f0-1b3805fa23ab.png">

Also no gutters. But notice the path for the `world` file. Do you also get the same?

**Comment by joaomoreno** [comment]
@johnmhoran Can you try the latest Insider? It has a bit more logging:

![image](https://user-images.githubusercontent.com/22350/36719507-8435f1c2-1ba5-11e8-88f5-d6cb4415a6c5.png)

**Comment by johnmhoran** [comment]
@joaomoreno Your screenshot gave me an idea.  Most of my repos are located under C:/Code/, but I have a test repo under C:/Users/JMH/ -- similar to the location of your test repo.

From Git Bash, VSCode 1.18.1 works well on repos in both locations.  The gutter displays properly, and `Git: Show Git Output` includes `git show :[path to file]`.

With both VSCode 1.20.1 and Insiders Build 1.21.0 (updated today), the gutter displays properly for the repo under C:/Users/JMH/.  Here's an output example for Insiders Build:
```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.16.2.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\Users\JMH\gittestrepo01
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name --abbrev-ref master@{u}
> git check-ignore -z --stdin
> git rev-list --left-right master...origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :Index.html
```

However, for repos under C:/Code/, the gutter display does not work in either 1.20.1 or the current Insiders Build.  Here's an output example for Insiders Build:
```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.16.2.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\Code\jmh_links
> git status -z -u
> git rev-parse --show-toplevel
> git symbolic-ref --short HEAD
> git rev-parse --show-toplevel
> git rev-parse master
> git rev-parse --show-toplevel
> git rev-parse --symbolic-full-name --abbrev-ref master@{u}
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-list --left-right master...origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
```
I don't know what this tells us except that there's something different between 1.18.1 (gutter OK everywhere) and 1.20.1/Insiders Build 1.21.0 (gutter OK under C:/Users/JMH/ but not under C:/Code/).  This is the case even when I use identical `settings.json` files for 1.18.1, 1.20.1 and Insiders Build.

**Comment by joaomoreno** [comment]
@johnmhoran Awesome! Now we're getting somewhere. Can you try opening a few other files within `c:\Code\jmh_links`, just to make sure the problem doesn't happen to a few files only?

**Comment by johnmhoran** [comment]
@joaomoreno I just tried several other files re 1.18.1 vs. 1.20.1 -- same behavior.  With several files opened, in 1.18.1, clicking the tab to move from file to file displays `git show :[filename]` in the output each time.  In 1.20.1, instead, `git rev-parse --show-toplevel` is displayed.

**Comment by joaomoreno** [comment]
Can you reproduce the issue in another `c:\Code\*` folder? Or even `c:\Code` itself?

**Comment by johnmhoran** [comment]
@joaomoreno  I've tested in a newly-created git repo under c:\code, and also temporarily made c:\code itself a git repo.  In each, tested five files:
```
test_css.css
test_html.html
test_javascript.js
test_python.py
test_text.txt
```
Same behavior with 1.18.1, 1.20.1 and current Insiders Build as previously described, i.e., in this morning's tests, only 1.18.1 showed changes in the gutter, no changes displayed in 1.20.1 or Insiders Build.  

In each case, launched from Git Bash.  Also tested several other repos under c:\code -- same behavior.

**Comment by joaomoreno** [comment]
Is the folder called `Code` or `code`? Are you opening it with the correct casing in VS Code?

**Comment by johnmhoran** [comment]
The folder is `C:\Code`.  I don't know what it means to open with the "correct casing", but I open both 1.18.1 and 1.20.1 the same way in Git Bash, and the gutter display works in 1.18.1 but not in 1.20.1.

**Comment by johnmhoran** [comment]
@joaomoreno On reflection I understood your question and it gave me an idea.  The issue seems to be case-related when I open a repo in VSCode from Git Bash, though the behavior I see is not entirely consistent.  

The correct case in the path to the repo matters with some paths but not all, and with 1.19.1, 1.20.1 and the latest Insiders Build, but not 1.18.1.  
* 1.18.1 -- The gutter display works no matter what combination of uppercase and lowercase is used in the path.  `/c/code/Test_git_Repo` and `/c/Code/test_git_repo` are both fine (in File Explorer it's displayed as `C:\Code\test_git_repo`).  Sometimes when the casing is way off, the gutter display works but the tree indicators (e.g., `M`) are not displayed.
* 1.19.1, 1.20.1 and the current Insiders Build -- Generally the gutter display works only when the correct uppercase and lowercase path segments are provided.  `/c/Code/...` -- yes.  `/c/code/...` -- no.  
  * Today I create a new directory directly under c, inside of which I placed a test repo and ran `git init`.  After an initial commit I edited several test files, and found the gutter display worked when opening 1.20.1 in Git Bash regardless of the uppercase/lowercase used for the path.  Strange.

In any event, something changed between 1.18.1 and 1.19.1 that imposed a strict case-sensitivity on the path when using Git Bash to launch VSCode.  I've checked the release notes for 1.19 and 1.20 but can't identify that change.  Do you have any hunches?

**Comment by joaomoreno** [comment]
cc @bpasero for ideas. Just read the last post, since it's quite a lengthy discussion. Are you aware of any casing restriction changes lately?

**Comment by bpasero** [comment]
@joaomoreno explain tomorrow over Coffee please...

**Comment by joaomoreno** [comment]
@johnmhoran Alright cool, I was able to reproduce with that last information. Pushing a fix for March! Thanks for your persistence. 🍻

**Comment by johnmhoran** [comment]
@joaomoreno Very cool!  Thank you for your patience and help, and for a great editor.  🍻

**Comment by joaomoreno** [comment]
@johnmhoran Let's make sure it does work, can you give the [latest insider release](https://az764295.vo.msecnd.net/insider/5450fdc79778b5a76a27ea7e5fd68e9ebbe44107/VSCodeSetup-x64-1.22.0-insider.exe) a try?

**Comment by johnmhoran** [comment]
@joaomoreno I've accessed several repos using a variety of incorrect cases in path segments using the latest insider release (below).  In each case, the gutter display worked as expected (and the SCM view icon count updates as soon as I save an edit to a previously-unedited file).

```
Version 1.22.0-insider
Commit 5450fdc79778b5a76a27ea7e5fd68e9ebbe44107
Date 2018-03-12T05:15:51.483Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
👍
