### ISSUE TITLE
Typescript errors remain when running in watch mode

### ISSUE THREAD

**Issue by raregrass** [Microsoft/vscode#4316]
- VSCode Version: 0.10.11
- OS Version: win 10

Steps to Reproduce:

1. I run a react project with webpack and watching mode typescript
2. typescript number is 1.8.7, the latest version.
3. I changed the tsdk to my own typescript lib.

I find some errors generated by editor still remain even when I fixed those errors and i think this issue is same as #909. 

I changed my tasks.json file to follow the method mentioned by @dbaeumer , like below:
`{
	"version": "0.1.0",

	// The command is tsc. Assumes that tsc has been installed using npm install -g typescript
	"command": "tsc",

	// The command is a shell script
	"isShellCommand": true,

	// Show the output window only if unrecognized errors occur.
	"showOutput": "silent",

	// Tell the tsc compiler to use the tsconfig.json from the open folder.
	"args": ["-p", "."],

	// use the standard tsc problem matcher to find compile problems
	// in the output.
	// "problemMatcher": "$tsc",
      
    "isWatching": true,
    
    "problemMatcher": {
        "fileLocation": "relative",
        "pattern": {
            "regexp": "^([^\\s].*)\\((\\d+|\\d+,\\d+|\\d+,\\d+,\\d+,\\d+)\\):\\s+(error|warning|info)\\s+(TS\\d+)\\s*:\\s*(.*)$",
            "file": 1,
            "location": 2,
            "severity": 3,
            "code": 4,
            "message": 5
        },
        "watching": {
            "activeOnStart": true,
            "beginsPattern": "^\\s*(?:message TS6032:|\\d{1,2}:\\d{1,2}:\\d{1,2} (?:AM|PM) -) File change detected\\. Starting incremental compilation\\.\\.\\.",
            "endsPattern": "^\\s*(?:message TS6042:|\\d{1,2}:\\d{1,2}:\\d{1,2} (?:AM|PM) -) Compilation complete\\. Watching for file changes\\."
        }
    }
}`

but did not make it. Those errors remain until i ctrl+shift+b to restart. Waiting for your help and thanks!

**Comment by dbaeumer** [comment]
@raregrass there is a predefined problem matcher for this: $tsc-watch. 

problemMatcher: '$tsc-watch'

That should help. Let me know if it works.

**Comment by raregrass** [comment]
Seems work, thank you.
But I find this matcher doesn't be written to the doc of vscode website, I think it should be clear for users.

**Comment by raregrass** [comment]
@dbaeumer

**Comment by dbaeumer** [comment]
With the latest build we added templates to generate the tasks.json file and one of the templates is tsc in watch mode. Closing,
