### ISSUE TITLE
DropDown: Add dropdown.listBackground color

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#43162]
Add color to allow optional contrast between and select
and an extended drop-down list.

**Comment by Tyriar** [comment]
@cleidigh FYI recovery builds are only for high impact issues in order to minimize risk.

**Comment by cleidigh** [comment]
@Tyriar 
I wasn't sure that was correct.  The the reason I did it is that I'm fixing a color clash
with Monokai that occurs now that we have a custom drop-down.  The background color
is exactly the same as the list focus color making it unreadable.  I was thinking this was important enough to fix ASAP.  I was going to do it with two PR 's one for the new color and one to specifically change Monokai.

Does this type of issue meet that criteria?
