### ISSUE TITLE
No Visual Feedback when performing VCS Pull / Push

### ISSUE THREAD

**Issue by vikramiyer** [Microsoft/vscode#43160]
- VSCode Version: 1.20.0
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. No visual cues when performed git pull / push on VSCode. Need a behavior like this below.

<img width="640" alt="screen shot 2018-02-08 at 2 53 39 pm" src="https://user-images.githubusercontent.com/287302/35954846-1cc02c98-0ce0-11e8-9d75-8d34d58911a9.png">

2. Do not get a hint within the editor on what are the file changes when performing VCS operation, though it appears in the Output tab. Its a click away but still doesn't list the files changed. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
I'm assuming you are referring to git. This would be solved by having git history within the product: #68

**Comment by vikramiyer** [comment]
I see that this pull request #68 was raised in 2015. Is there any traction on this ticket at all ? Is it coming in any milestone ?

**Comment by joaomoreno** [comment]
@vikramiyer There is no current traction. You can always check the milestone of each issue in the right side of the issue page. That issue is currently in the Backlog.
