### ISSUE TITLE
Can't use integrated terminal.

### ISSUE THREAD

**Issue by Veado** [Microsoft/vscode#43166]
- Version 1.20.0
- Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
- Date 2018-02-07T17:09:39.780Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64
- OS Version: Win10 pro

Steps to Reproduce:

1. Update vscode to vsersion 1.20.0.
2. Reopen vscode, can't use integrated terminal, have no response.

![20180208132713](https://user-images.githubusercontent.com/15306100/35956963-ce46a120-0cd3-11e8-84a3-ff95e6a83269.png)

User setting: 
```
{
  "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
  "editor.tabSize": 2,
  "extensions.ignoreRecommendations": false,
  "git.autofetch": true
}
```

I tried to specify powershell and git-bash, reinstall vscode, restart computer, ban all extensions. terminal still no response.

**Comment by Veado** [comment]
But it may not causes by the update operation, someone can't use integrated terminal before update.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169
