### ISSUE TITLE
Feature Request - Remember enter / leave full screen and reopen with the same setting.

### ISSUE THREAD

**Issue by shobhitchittora** [Microsoft/vscode#43165]
Just saw that whatsapp web on mac can remember my last window state ( full screen or not ) and re-opens with the same setting. This made me realize that every-time I open Code on my big monitor I've to explicitly trigger a full-screen. 

Would it make sense to have this for Code ? 

Putting a code pointer here to verify I'm looking in the right file.
https://github.com/Microsoft/vscode/blob/91120eb786357aa1e16217ad6a67cf0740f26e8e/src/vs/workbench/electron-browser/window.ts#L207

**Comment by bpasero** [comment]
`"window.restoreFullscreen": true`
