### ISSUE TITLE
"Open Workspace Configuration File" does nothing

### ISSUE THREAD

**Issue by cdaringe** [Microsoft/vscode#43167]
- VSCode Version: 1.20.0
- OS Version: osx, latest

Steps to Reproduce:

1. open vscode
2. attempt to open **Workspaces: Open Workspace Configuration File** via  the Command Palette
3. observe _nothing_ happen.  no problems logged to console pane

Does this issue occur when all extensions are disabled?: **Yes**

Expected file to open per [release notes](https://code.visualstudio.com/updates/v1_20#_improved-debugging-support-for-multi-root-workspaces).

![untitled mov](https://user-images.githubusercontent.com/1003261/35957715-da0fc572-0c51-11e8-9ad0-9dea3373bf68.gif)

**Comment by bpasero** [comment]
@cdaringe you need to be in a workspace to open the workspace config file.

**Comment by cdaringe** [comment]
Does not every open folder context have a workspace? For example, I created a workspace settings file, and the above still happens.  Perhaps you imply a multi root workspace?  I will try when I'm back at my keyboard :)

**Comment by DanTup** [comment]
Shouldn't there be a message telling the user what's wrong rather than silently doing nothing?
