### ISSUE TITLE
go代码中保存某些中文词会变成�

### ISSUE THREAD

**Issue by a1305315624** [Microsoft/vscode#43175]
### Issue Type
Bug

### Description

go代码中有些中文注释或者string,会变成�,1.20和上个版本开始出现,之前没出现过.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_143395|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
vsc-material-theme|Equ|1.3.0
material-icon-theme|PKi|3.2.2
vscode-docker|Pet|0.0.24
better-toml|bun|0.3.1
gitlens|eam|8.0.0
git-project-manager|fel|1.4.0
Go|luk|0.6.73
sublime-keybindings|ms-|3.0.3
plsql-language|xyz|1.1.2

</details>
Reproduces only with extensions

**Comment by rebornix** [comment]
This is caused by IME bug in Electron 2 but now the latest version should already fixed.
