### ISSUE TITLE
editor.setDecorations doesn't update the hover message

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#4317]
- VSCode Version: 0.10.11
- OS Version: OSX 10.10.5

Steps to Reproduce:

- Create a simple plugin doing nothing but updating the same line decoration in a interval:
```javascript
var i = 0;
var decType = window.createTextEditorDecorationType({});

setInterval(() => {
  var decoration = {
    range: new vscode.Range(0, 0, 0, 1000),
    hoverMessage: 'test' + (++i)
  };
  window.activeTextEditor.setDecorations(decType, [decoration]);
}, 200);
```
- Observe the decoration hover message not being changed, even when the line content is changing (only deleting the line seems to update the message):

![v](https://cloud.githubusercontent.com/assets/979966/13816576/a1b37136-ebda-11e5-93fe-c878c250550e.gif)

**Comment by alexandrudima** [comment]
Thank you, nice find!

**Comment by ArtemGovorov** [comment]
Wow, it was fast, thanks for fixing it! The credit for finding it goes to @asos-massimo.
