### ISSUE TITLE
In the new version 1.20, the color palette of CSS cannot pop up.

### ISSUE THREAD

**Issue by bymomo** [Microsoft/vscode#43176]
- VSCode Version: 1.20
- OS Version: win10 1709

Steps to Reproduce:In the new version 1.20, the color palette of CSS cannot pop up.,,,,There was no problem until the 1.20 version was updated.

1. The mouse moves on the color value, unable to bring up the color panel.
2.In the new version 1.20, the color palette of CSS cannot pop up.
3.There was no problem until the 1.20 version was updated.

Does this issue occur when all extensions are disabled?: Yes/No  Yes!
![006](https://user-images.githubusercontent.com/28828166/35962981-44b9f842-0cee-11e8-89ec-b34156f7f778.png)
![007](https://user-images.githubusercontent.com/28828166/35962985-46d3e0d4-0cee-11e8-9ba8-5c72f44502cd.png)

**Comment by bymomo** [comment]
![008](https://user-images.githubusercontent.com/28828166/35965379-ab3180ca-0cf5-11e8-97ce-d5a43e4ab1ed.png)

Just tested, the mouse moves to the color code, it can pop up,

It's a little bit different from the previous version.
I'm sorry

**Comment by JJBocanegra** [comment]
Couldn't it be shown on both elements?

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/40634 which is the earliest one, thanks all for your feedback.
