### ISSUE TITLE
Allow to configure a default language for unknown file types

### ISSUE THREAD

**Issue by mat-m** [Microsoft/vscode#43174]
- VSCode Version: 1.20.0
- OS Version: Windows 10 x64 10.0.15063

Steps to Reproduce:

1. Override  "files.defaultLanguage" with  a default syntax, e.g.  "files.defaultLanguage": "markdown",
2. Open a file with no extension, e.g. a README file

The Language Mode is set to plain text. I would expect it to be the  `files.defaultLanguage` value

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@mat-m that setting is only for new untitled files

**Comment by mat-m** [comment]
@bpasero : So we are doomed to plain text for text files with random names and no extension ?
I tried to play with the globbing pattern, but could not found one which allows to select files with no dot in their name.

**Comment by bpasero** [comment]
We can reopen and rename this one.

**Comment by alexandrudima** [comment]
Let's track in #1800. Once #1800 is in, one can write an extension that does anything in this area.
