### ISSUE TITLE
Tabs - order alphabetically

### ISSUE THREAD

**Issue by oldbasilbear** [Microsoft/vscode#43178]
### Issue Type
Feature Request

### Description

I frequently have multiple tabs open, and often find that I cannot quickly see the tab which I want to access.

If there was an option to list the tabs alphabetically (by file name), it would enable me to scan the list more easily to quickly find the one that I want to select.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.4.0-112-generic

**Comment by bpasero** [comment]
@oldbasilbear are you talking about a picker like this one:

![image](https://user-images.githubusercontent.com/900690/35988322-67cb4b6e-0cfe-11e8-8bdc-55ad4054a5d8.png)

Or do you want to sort the opened tabs by alphabet permanently?

**Comment by oldbasilbear** [comment]
Hi @bpasero - I am after the latter of those two please, and yes, it does appear to be what ConnorsFan is requesting on #27286 (I missed that in my search)
Thanks for taking a look.

**Comment by oldbasilbear** [comment]
I will close this issue as it is already covered on #27286
