### ISSUE TITLE
Can't move multiple lines with alt+up

### ISSUE THREAD

**Issue by dnutiu** [Microsoft/vscode#43177]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.0.0
Go|luk|0.6.73
cpptools|ms-|0.14.6
material-icon-theme|PKi|3.2.2

---

Steps to Reproduce:

1. Alt+click to select three consecutive code lines
2. Hold alt and press up arrow or down arrow
3. Only top and bottom line starts to move, middle line is ignored.

Reproduces without extensions: Yes

**Comment by drzymalanet** [comment]
Reproducible in Code 1.21.1 on Linux x64

**Comment by rebornix** [comment]
@metonimie does selecting these three consecutive lines and then moving them up/down work for your case? Or you need multi cursor to do something others.

**Comment by metonimie** [comment]
Hello, @rebornix, selecting three lines and moving them works fine for me, thanks!
