### ISSUE TITLE
Add separate theme colors for explorer rendered diagnostics

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#43179]
The new error highlight in the explorer window is great, but for some reason the colours are all black for me. I've tried different themes, but it doesn't make any difference:

![image](https://user-images.githubusercontent.com/376658/35965111-c161608e-0cb1-11e8-9f4b-4cb2ae91243b.png)

**Comment by Gruntfuggly** [comment]
Ah - I've figured it out. It's using the colour from 'editorError.foreground' from 'workbench.colorCustomizations'.

I can see the logic in doing this, but I have the foreground colour set to black to hide the squigglies and use the background colour instead to show a double underline, which makes the stand out more.

The theme has different colours for the editor area and the explorer area, so is it sensible to use the same colours? Maybe there should be a separate setting?

**Comment by usernamehw** [comment]
It's especially bad when you have transparent editor warnings and errors.

**Comment by jrieken** [comment]
@joaomoreno didn't you tweak the colors in the last endgame? is this still the same symbolic color?

**Comment by joaomoreno** [comment]
@jrieken This is what I've done: https://github.com/Microsoft/vscode/commit/6f5520d57efeb72432edbb3b44d7359ca51fb106#diff-f6007616cdb736289ea324f011eec319

**Comment by jrieken** [comment]
Alright

**Comment by yavrib** [comment]
I'd like to take this as my first issue. Can you point me where I can start?

**Comment by jrieken** [comment]
Sure - here is the code that adds the decorations (using the squiggle colors): https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/markers/electron-browser/markersFileDecorations.ts#L53. You can use the `registerColor`-function to define new colors, like here: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/view/editorColorRegistry.ts#L36. I'd define two colors, for errors and for warnings.
