### ISSUE TITLE
Find all reference seldomly selectes a bunch of text

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#43187]
For the past 4 weeks I noticed that find all references seldomly selects random text.
Here are example steps on how to reproduce it
1. Open debugService, do a find all references on `private configurationManager`
2. Click on the references in the widget
3. Notice some text randomly gets selected

This is captured in the gif below.

Note that sometimes I would also double click in the widget, the widget closes and still some weird selection happens in the main editor.

![findallreferences](https://user-images.githubusercontent.com/1926584/35966364-e0d3c3d8-0cbd-11e8-8a37-5551056c0987.gif)

**Comment by jrieken** [comment]
Yeah, I have seen this too.. But no clue how that happens... @alexandrudima this looks like the native browser selection. any ideas how that happens or how we prevent that in outer editors?

**Comment by alexandrudima** [comment]
@jrieken I can reproduce when dragging from a search result, so I suppose it is something about the tree that needs to be suppressed ?

See https://github.com/Microsoft/vscode/issues/44525

**Comment by isidorn** [comment]
I can still reproduce, so reopening and removing needs more info. Let me know if I can help with providing more information.

**Comment by alexandrudima** [comment]
@isidorn How can you still reproduce? The editor text is no longer selectable. I did that change in 3c040d051e707f21bfb0aef4196972b71a913761

**Comment by isidorn** [comment]
@alexandrudima my mistake. I was seeing it last week probably before your commit. Since I did not see any activity here I assumed I will hit it sooner or later. I will reopen if I see it again.
