### ISSUE TITLE
Auto save is dangerous

### ISSUE THREAD

**Issue by amitguptagwl** [Microsoft/vscode#43189]
I opened a file, Typed something by mistake. It saved the file automatically and I never got to know what I did.

Is it possible to save the state of a unsaved but modified file without writing to the actual file?

**Comment by MaleDong** [comment]
If you are using git or svn, you can do comparations.
But if you are locally writing codes, you have to disable this by clicking "Auto Save" again to make it "unchecked".

**Comment by amitguptagwl** [comment]
I do use gits for technical projects but not for simple notes, and other files. I believe in sublime, they maintain the state of open file separately than saving it to original file. Hence I asked if we have some configuration or if we can take it as feature request. 

I don't want to use multiple editors for different purpose.

**Comment by amitguptagwl** [comment]
Can we take it as feature request? The reason I would like to raise that request is when you modify the code knowingly or by mistake and you don't commit it, you're actually not sure why you did the changes after a long time. (Other people may have other reasons)

**Comment by MaleDong** [comment]
For auto-backup things, CSV,TFS,Git or SVN does better. However VSC doesn't do that itself.

**Comment by MaleDong** [comment]
@amitguptagwl : 
There's a plug-in that helps you, hope this helps: https://marketplace.visualstudio.com/items?itemName=xyz.local-history

**Comment by MaleDong** [comment]
@amitguptagwl ：Well……the plug-in seems that it can save automatically with different kinds of versions of your specific files and do comparations. You can compare them with each other and know what's changed in your file :)

**Comment by amitguptagwl** [comment]
Please correct me if my understanding is wrong, 

Suggested plugin will help to maintain the history of a file(s). But it'll not stop vscode editor from autosave the changes in current file. Now if I stop autosave, and I have some open files in the editor, I believe I'll loose unsaved files or the editor will ask me to save the files.

**Comment by MaleDong** [comment]
Do you mean that the plug-in CANNOT work to save history of files when your VSC is in "Auto-Save" mode?

**Comment by MaleDong** [comment]
@amitguptagwl 
Do you mean that the plug-in CANNOT work to save history of files when your VSC is in "Auto-Save" mode?

If yes, I'm afraid you don't take this well.
In fact, this will catch the event of saving——No matter whether it's manually saving or automatically saving.

Plz download my video to see what's happening there——NOTICE THE LEFT BAR OF "LOCAL HISTORY" IN MY VIDEO. There's ALWAYS the changing list occuring to you to see at what time you changed what by comparations.

[AutoSave.zip](https://github.com/Microsoft/vscode/files/1723028/AutoSave.zip)

**Comment by MaleDong** [comment]
@amitguptagwl 
Do you mean that the plug-in CANNOT work to save history of files when your VSC is in "Auto-Save" mode?

If yes, I'm afraid you don't take this well.
In fact, this will catch the event of saving——No matter whether it's manually saving or automatically saving.

Plz download my video to see what's happening there——NOTICE THE LEFT BAR OF "LOCAL HISTORY" IN MY VIDEO. There's ALWAYS the changing list occuring to you to see at what time you changed what by comparations.

Notice that AutoSave WILL HAPPEN ONCE YOUR FILE IS CHANGED IMMEDIATELY. PLZ OPEN THE AUTOSAVE=TRUE

[AutoSave.zip](https://github.com/Microsoft/vscode/files/1723028/AutoSave.zip)

**Comment by amitguptagwl** [comment]
well.. that was my question not the conclusion. Thanks for the video.

I'll say my perception was wrong, doesn't matter if I use this plugin or not, if I disable autosave, and write something to file, it doesn't write to original file. Now if I open the vscode workspace, and open the same workspace with some other editor (tried sublime), I can see my unsaved changes with vscode but not with other editor. This is what I was expecting.

So no issue. Thanks again.

**Comment by MaleDong** [comment]
@amitguptagwl : Until now you must open "AutoSave".
