### ISSUE TITLE
Failed to cache the CSS classes in the Workspace error message

### ISSUE THREAD

**Issue by OuchSaray** [Microsoft/vscode#43182]
- VSCode Version: 1.20.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Update the IDE to the latest version
2. Open it and you can see the following error message: <Failed to cache the CSS classes in the workspace for the first time: Cannot read property 'map' of undefined>

<img width="1216" alt="screen shot 2018-02-08 at 09 34 20" src="https://user-images.githubusercontent.com/16121371/35965589-4f23f50c-0cb3-11e8-96d9-13048f01224b.png">

Does this issue occur when all extensions are disabled?: No

**Comment by sayemon10** [comment]
having same issue.. :/

**Comment by BVJeon** [comment]
I saw it too. These days VSCode is used frequently, but I hope you can fix it with good cheer.

**Comment by AndyBlak1** [comment]
Same issue here.

**Comment by Lego2012** [comment]
Same for me

**Comment by diablofong** [comment]
Same issue here.

**Comment by mmosfetx** [comment]
Same issue here, I disabled the extension for "IntelliSense for CSS class names" by Zignd and stopped receiving the message.  For double checking, Re-enabled that extension and it appeard again.  So something related to that extension possibly?

**Comment by OuchSaray** [comment]
# @mmosfetx is right, I disabled it and the error message disappeared :)

**Comment by mmosfetx** [comment]
If you have further interest it looks like it can be tracked at the devs github page [https://github.com/zignd/HTML-CSS-Class-Completion/issues/114](url)

**Comment by octref** [comment]
Thanks for @mmosfetx for pointing out the culprit. You can subscribe to https://github.com/zignd/HTML-CSS-Class-Completion/issues/114 for updates.

Meanwhile a tip: hovering over the "error" should now show the misbehaving extensions.

**Comment by biobii** [comment]
I have same issue here.

**Comment by SergioSuarezDev** [comment]
Same issue here

**Comment by youngda** [comment]
Same issue here
