### ISSUE TITLE
RSS feed for VSCode updates

### ISSUE THREAD

**Issue by dorian-marchal** [Microsoft/vscode#43184]
On  [the VSCode update page](https://code.visualstudio.com/updates), there is a "RSS" link, but the target feed is related to the [VSCode blog](https://code.visualstudio.com/blogs).

Is there a RSS feed for the VSCode updates ?

I found [this old related issue](https://github.com/Microsoft/vscode/issues/3197) (closed without response) :

> @Tyriar any news on the RSS? I would like RSS for:
> https://code.visualstudio.com/updates/
> ...but the RSS link in the bottom right corner is some other blog or something?

**Comment by Tyriar** [comment]
No update, I just pinged the internal issue though.
