### ISSUE TITLE
The location of Source Control Viewlet's ContextMenu is under cursor when screen height is small

### ISSUE THREAD

**Issue by qbcbyb** [Microsoft/vscode#43183]
### Issue Type
Bug

### Description

In the `Souce Control Viewlet` panel, I clicked down repository's `more`  menu to open context menu, but the pop menu's location is under my cursor, and when I let the mouse up, the pop menu go's up. it execute the first menu of pop.  The Image below is the state when I clicked down the `more` menu . 

![catpure](https://user-images.githubusercontent.com/6168648/35965705-aff4062c-0cf6-11e8-9830-e3e93fc42118.png)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2492)|
|Memory (System)|7.89GB (0.62GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|8.0.0
EditorConfig|Edi|0.12.0
prettier-vscode|esb|1.1.3
quickOpenSelection|fin|1.0.2
auto-close-tag|for|0.5.5
weex|jay|0.4.0
mdhelper|jos|0.0.11
intellij-idea-keybindings|k--|0.2.20
vscode-less|mrm|0.6.3
python|ms-|2018.1.0
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
vue-vscode-snippets|sdr|1.3.0
vscode-todo-highlight|way|0.5.11
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.5.0

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
This is a nasty one.

@bpasero I suggest to move the dropdown menu of the toolbar's more action to the right of it always. Also, do we already have an upstream bug for dropdown menus accepting the initial mouse click which spawned them>

**Comment by bpasero** [comment]
@joaomoreno I am not sure that opening it to the right is expected though, I think we only do that when you use the mouse and right-click (exactly for that reason). On macOS this issue does not reproduce because the menu actually shows a scroll bar. 

I am not aware of an upstream bug for this, but maybe check [this query](https://github.com/Microsoft/vscode/labels/workbench-menu) where I usually keep these issues.
