### ISSUE TITLE
Cannot find "Close","Maxinum" and "Minimum" buttons when "Report Issues" window opens for the first time

### ISSUE THREAD

**Issue by MaleDong** [Microsoft/vscode#43198]
### Issue Type
Bug

### Description

1) Open the VSC (Version is 1.20.0)
2) Turn to "Help" => "Report Issue".
3)  In my Windows 8 (Simplified Chinese, x86, SP1). It seems that the windows cannot let me maximun/minimun or close unless I adjust its width or height by stretching it with mouse....:(
4) Here's the attachment of bug report in video.
[Issue43198.zip](https://github.com/Microsoft/vscode/files/1706812/Issue43198.zip)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|Memory (System)|3.15GB (1.60GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by MaleDong** [comment]
PS：Why "vscodebot" reports it as "new release"? It should read the 1st line as "Bug".

**Comment by RMacfarlane** [comment]
For verifier: Change screen resolution to be as low as possible and make sure the window doesn't exceed the bounds of the screen
