### ISSUE TITLE
Unable to update launch.json (via API) in multi-root workspace

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43197]
I have some "project upgrade" functions that run when my extension activates to handle breaking changes. I merged my two debuggers today such that I need to update the `type` inside the `launch.json`.

I have the following code;

```ts
function convert_legacy_debug_types(workspace: vs.WorkspaceFolder) {
	// Read launch.json config.
	const launchFile = vs.workspace.getConfiguration("launch");

	const configs = launchFile.get<any[]>("configurations");
	if (!configs)
		return;

	let hasChanged = false;

	// Find Dart CLI items that might need upgrading.
	configs.filter((c) => c.type === "dart-cli" || c.type === "flutter").map((d) => {
		console.log("Found old dart-cli/flutter debug type, setting to dart...");
		d.type = "dart";
		hasChanged = true;
	});

	if (hasChanged)
		launchFile.update("configurations", configs);
}
```

This code works great if I open a single folder. However if I open a multi-root workspace there are two issues:

1. I only seem to get the launch configs for one of the projects
2. The `update` call at the end doesn't seem to persist to risk at all (not even for the one projects we modified)

I tried passing the workspace uris into `getConfiguration` however it warns:

> Accessing a window scoped configuration for a resource is not expected. To associate 'launch' to a resource, define its scope to 'resource' in configuration contributions in 'package.json'.

What's the correct way to make the code above work for a multi-root workspace?

**Comment by isidorn** [comment]
@DanTup please use the `inspect` instead of the `get`.
The same way I am doing in our core [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L529)
Let me know if that is not working and I will reopen this.

@sandy081 can correct me if I am wrong, but I believe this is the correct way to do it also for extensoins

**Comment by DanTup** [comment]
@isidorn I'm confused; the doc for `inspect` suggests it only takes a single argument (`string`), how do I pass the workspaceFolder? (your example code seems to pass it as a second argument?)

**Comment by sandy081** [comment]
@DanTup Example code from @isidorn is internal. What ever you did by passing the URI to `getConfiguration` is correct and gives you the configuration for that resource. 

Warning should not be shown as it is applicable only when you access `window` configurations using a resource where `launch` is not. 

I will fix the warning.

**Comment by DanTup** [comment]
@sandy081 Aha, you're right. It does work, but I had to add `WorkspaceFolder` as the configuration target for the update at the end:

```ts
launchFile.update("configurations", configs, vs.ConfigurationTarget.WorkspaceFolder);
```

I'm not sure why (isn't the `launchFile` variable already for the workspace folder?), but it's working. Thanks!

**Comment by sandy081** [comment]
@DanTup While writing default target is always `Workspace` and you can write launches into Workspace configuration file too in a MR workspace.

**Comment by DanTup** [comment]
Yep, the warning is from reading the value with:

```ts
const launchFile = vs.workspace.getConfiguration("launch", workspace.uri);
```

**Comment by sandy081** [comment]
`launch` and `task` are resource specific configurations by default. So accessing them needed a resource to be passed. 

Updated the warning strategy to consider them resource scoped.
