### ISSUE TITLE
Unable to permanently delete file(s)/folder(s) when right-clicking them in the Explorer, holding Shift and clicking 'Delete'

### ISSUE THREAD

**Issue by liam-potter** [Microsoft/vscode#43193]
### Issue Type
Bug

### Description

When right-clicking file(s)/folder(s) in the Explorer it used to be possible to hold Shift before clicking 'Delete' in the context menu to permanently delete them. This no longer works and it always prompts to move them to the Recycle Bin instead.

It now seems it is only possible to permanently delete file(s)/folder(s) by tapping them in the Explorer to highlight them and pressing Shift+Delete.

Would it be possible to restore the old behaviour?

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (91120eb786357aa1e16217ad6a67cf0740f26e8e, 2018-02-08T05:16:13.920Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|15.93GB (7.96GB free)|
|Process Argv|D:\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.5
gitlens|eam|8.0.0
vscode-auto-open-markdown-preview|hnw|0.0.4
vue-snippets|hol|0.1.5
discord-vscode|icr|2.2.1
edge|luo|0.1.4
vetur|oct|0.11.7
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|2.8.7
pdf|tom|0.2.0
vscode-import-cost|wix|2.6.2
html-css-class-completion|Zig|1.16.1

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
This is now possible by hodling the alt key before clicking on the context menu.
We should have put this in the release notes, my apologies for missing on that.

We will not bring back the old behavior with shift.

**Comment by liam-potter** [comment]
I can learn to live with this, but it took me a good couple of minutes to realise I had to let go of the Alt key after the context menu has appeared!

Out of curiosity, is there a particular reason why the old behaviour with Shift will not be brought back?
 Holding Shift whilst clicking Delete in a context menu in order to permanently delete something is common practice in Windows - if not most OSes.

It seems strange to drop this in favour of the current solution (which most people will not even realise exists) but keep the standard "Press Shift+Delete to permanently delete selected files" functionality.

**Comment by cretz** [comment]
@isidorn - Note it says `Shift+Del` next to `Delete Permanently` in the context menu that appears when alt+right-click even though shift has nothing to do with it anymore.

Also, I am curious like @liam-potter about the reasoning for this alteration. Can you at least link to the issue where this was discussed so I can see the points made?

**Comment by isidorn** [comment]
@liam-potter @cretz thanks for your interest. The reason why we started using the `alt` key for the click is because we have long ago defined that the alt key presents an alternative command in the context menu. More about that can be found [here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus)
The alt key is a shorthand for alternative, so that is why we choose that long ago for alternative contributable commands.

This milestone we have changed the explorer context menu to also use contributable commands and not treat any command specailly, so we simply changed the delete key to conform to our spec for commands.

As for the shortcut it still says Shift+Del, because that is still the keyboard shortcut for delete. The alt is only for the mouse click.

**Comment by liam-potter** [comment]
@isidorn - Thank you for your reply.

Personally I feel that that the VSCode team has it wrong on this occasion and that Delete Permanently should not be considered as an alternative command at all.

The main operation of the Delete command, with or without Shift, is to remove the selected item(s) from the folder within which they exist. That's it.

Yes, the default behaviour after this operation is to move the selected item(s) to Bin/Trash but this is why Windows, and probably most other OSes with contextual menus, use the Shift key as a modifier for the same Delete command - you're still just removing item(s) from a folder but modifying the way in which they are removed.

You are more than welcome to disagree with me, but I do think this is worth further discussion.

**Comment by arturock** [comment]
I understand the alternative actions reason from a point of view, however I don't think It justifies this change at all. If its about getting alternative options, why does the menu have the same entries except the delete one? Maybe replacing shift by alt on the old behavior would have more sense.
I'm Currently on Debian and using alt+right-click doesn't work but ctrl+alt+right-click does.
I miss the good old behavior

**Comment by isidorn** [comment]
We brought back this behavior. SO try out the latest vscode stable and holding down shift and triggering the menu should offer the delete peremenantly action.

**Comment by arturock** [comment]
Thanks for your answer @isidorn. I tried in latest stable but new behavior still (Linux, .tar.gz):

Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:01:43.521Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Last stable version with previous behavior where delete permanently was triggered by having shift pressed before clicking the delete menu item, not before triggering menu:

Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:32:23.601Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by isidorn** [comment]
@arturock my mistake we brought it back only for windows.
@bpasero maybe we should also do this for linux since it also has some builtin alt behavior?
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/browser/menuItemActionItem.ts#L34

**Comment by bpasero** [comment]
@isidorn sure why not

**Comment by liam-potter** [comment]
The behaviour is still a little buggy and not quite what I was expecting. If you're using Alt you have to let go of the key pretty quickly or the context menu disappears. If you already have a file right clicked and then try to do the "hold modifier key whilst right clicking" action on another file it often will not work (and accidentally right clicking the wrong file is a pretty common occurrence).

The problem I have with all of this is that it's taking me longer than it really should to do a very simple operation. VSCode used to do this perfectly and replicate default OS behaviour - and it has not yet been confirmed where it was discussed that the Delete command should be changed to this new behaviour.

The default behaviour in almost every OS/software I am aware of is to treat Delete as a single command but allow a modifier key (usually Shift) to modify the way in which that operation is performed.

- You do not need to hold any modifier keys whilst right-clicking the files/folders (only whilst clicking the `Delete` command itself in the context menu)
- The `Delete` command is treated as a single command since both soft/hard deletes have the same end result - the items are removed from whatever folder they are in 
- Clicking `Delete` without holding any modifier keys should prompt the user to send the items to trash/recycle bin.
- Clicking `Delete` whilst holding the `Shift` key should prompt the user to remove the items permanently.

It feels very strange that VSCode is breaking this trend.

**Comment by arturock** [comment]
No problem @isidorn. May I suggest to return to the old behavior just like it was?

**Comment by isidorn** [comment]
We can not return to the old behavior due to the reason specified in my comment above. Thanks for your comments and suggestions though.

**Comment by isidorn** [comment]
Also we will probably improve this based on your suggestion once we have async context menus -> which require adoption to electron 2.0. For that you can track our work on the `tyriar/electron-2.0.x` branch. Thanks

**Comment by arturock** [comment]
Just to note It will be kinda weird the inconsistency between shift+del on keyboard and alt+delete with menu

**Comment by isidorn** [comment]
Now the menu supports both shift and alt.
