### ISSUE TITLE
collapse

### ISSUE THREAD

**Issue by cherchyk** [Microsoft/vscode#4319]
- VSCode Version: 0.10.11
- OS Version: W7

Steps to Reproduce:

When I click on minus sign in tine 785 then instead of collapsing from 785 to 787 or from 785 to 788 it collapse from 785 to 791.  Lines  789-791 should not be collapsed.

![image](https://cloud.githubusercontent.com/assets/1703275/13817685/81a5a90c-eb69-11e5-88bc-7f5b7b9eeec4.png)

**Comment by aeschli** [comment]
What you see is what's expected. The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, use brackets, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
