### ISSUE TITLE
Cannot change the layout of User Settings to rows

### ISSUE THREAD

**Issue by MasseGuillaume** [Microsoft/vscode#43191]
- VSCode Version: 1.20.0
- OS Version: NixOS 17.09.2731.92d088e891e

Steps to Reproduce:

1. Open user settings
2. Toggle Editor Group Layout

The layout is still in column. I would like to edit setting in rows. (I have a vertical screen, so not a lot of width).

**Comment by satiewaltz** [comment]
I was about to file a ticket for this until I found this issue, and noticed it's been a while since this has been reported.

Is it possible that I could make a solution for this? I prefer having my panels as rows and I'd like to help push this into a real feature in any way I can.

**Comment by sandy081** [comment]
I do not think this feature will be implemented in near future and we have built a new richer settings UI. So closing this in favour of the new UI.
