### ISSUE TITLE
Debugger inline values jumps to second line when hit enter.

### ISSUE THREAD

**Issue by dinindu-d** [Microsoft/vscode#43199]
### Issue Type
Bug

### Description

Set "debug.inlineValues": true.
Set breakpoint somewhere.
After paused on the step, goto the end of the line and hit enter.

**Before**
`const stack = [];| stack = Array(2) [Object, Object]`

**After**
```
const stack = [];
| stack = Array(2) [Object, Object]
```

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.90GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_254014|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.0
vscode-eslint|dba|1.4.5
vscode-great-icons|emm|2.1.24
auto-rename-tag|for|0.0.15
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
mssql|ms-|1.3.0
cpptools|ms-|0.14.6
licenser|ymo|1.1.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by isidorn** [comment]
@dinindu-d I acknowledge the bug. This is just how decoartions are behaving, unfortunetly the inline decorations do not seem to have an option to not grow beyond the line.
@aeschli maybe you have an idea how to solve this?

fyi @nojvek in case you are interested into looking for a fix

**Comment by nojvek** [comment]
debugger.inlineValues uses the editor's decorator api.

A fix we can do is that if the editor is edited , then we re-sync the inlineValue decorators

I'm not sure how this works but would love it if the bug was assigned to me so I can see it in my issues list

**Comment by isidorn** [comment]
@nojvek that's a good idea.
@kieferrm can you please add @nojvek to our project so we can assign some issues to him?
