### ISSUE TITLE
Renaming identifiers should save on other files

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#432]
It is right now very problematic for me when renaming things. I need to rename an identifier and save all other files the rename touches that is in the workspace folder.

When renaming files it should save the renamed identifiers on other files, even though they are open. If there are other open workspace files, that contains other unsaved changes I think it should save only the renamed identifier, and leave the rest unsaved.

**Comment by jrieken** [comment]
@tinganho Can you explain why it is problematic that files aren't saved?

**Comment by tinganho** [comment]
If one identifier touches a lot of files in my open works space, I need to save all those files in order to get the change working. It happens to me all the time.

**Comment by jrieken** [comment]
Like changes in JS files and hitting reload in the browser? How about using the Auto-Save feature?

**Comment by tinganho** [comment]
Yes kind of. 

I have not tried auto save. I will give it a try.
