### ISSUE TITLE
Add icons for intellisenses

### ISSUE THREAD

**Issue by MaleDong** [Microsoft/vscode#43204]
### Issue Type
Feature Request

### Description

When we search for sepecific files listed in the file explorer by pressing "Ctrl+P", we can see lots of files with its proper icons.

But we cannot find any icons when in the intellisense mode such as "const xxx = require('../model/a.js');".

You can compare the two images below to see the result. Hope when intellisense chooses the proper icon for the specific known file.

[File Explorer]
![withicons](https://user-images.githubusercontent.com/6959154/35972496-0f3ac89e-0d0d-11e8-8006-05a70a8a673f.png)
[Intellisenses：Notice that there're no js icons for the intellisensed specific file tips at all]
![noicon](https://user-images.githubusercontent.com/6959154/35972510-1f7ce49e-0d0d-11e8-8548-6de581b5a896.png)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 6.3.9600

**Comment by mjbvz** [comment]
They do have icons, it's the little file thing next to the name :) This file icon is specific to path / file suggestions

For JS/TS at least, I'm not sure using the explorer's js file icon conceptually makes sense for intellisense. The existing file icon already shows that the suggestion is for a file, and these suggestions will always be for JS/TS files

Closing as out of scope

**Comment by MaleDong** [comment]
In fact it would be nicer if the intellisense "senses" the file type according to the file extension such as "*.js" to show the file icon, which means it would be very sensive for us to see which type(s) of files we're now referring (Just like what we see in VS……class, struct or enum will have different kinds of type icons).
