### ISSUE TITLE
编辑器de制表符长度经常识别混乱。

### ISSUE THREAD

**Issue by milobluebell** [Microsoft/vscode#43205]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
vscode-eslint|dba|1.4.5
es7-react-js-snippets|dsz|1.3.3
tslint|eg2|1.0.24
php-debug|fel|1.12.1
php-intellisense|fel|2.2.7
php-pack|fel|1.0.1
sass-lint|gle|1.0.1
intellij-idea-keybindings|k--|0.2.20
python|ms-|2018.1.0
node-debug2|ms-|1.21.0
sass-indented|rob|1.4.6
vscode-react-native|vsm|0.5.7
markdown-all-in-one|yzh|1.0.5

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I don't understand, please explain more in english.
