### ISSUE TITLE
VS Code terminal render underscores as space

### ISSUE THREAD

**Issue by MaxymVlasov** [Microsoft/vscode#43207]
- VSCode Version:
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:32:23.601Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
Linux vm 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Start type underscores in VS Code terminal

Does this issue occur when all extensions are disabled?: Yes

At the same time, if change default highlight color to some other (for example, by using grep) I can see underscores

![](http://i.piccy.info/i9/4141cde548c485d574527f4fc31a125c/1518095025/12445/1217554/Screenshot_from_2018_02_08_15_03_15.png)

This problem same to zsh and bash.

```bash
➜  remote-monitor git:(master) ✗ bash --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
➜  remote-monitor git:(master) ✗ zsh --version
zsh 5.2 (x86_64-ubuntu-linux-gnu)
```

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
