### ISSUE TITLE
Incorrect types versions being downloaded in the typescript cache folder

### ISSUE THREAD

**Issue by nitish24p** [Microsoft/vscode#43202]
This issues started happening after i updated my VSCode. 

For all my javascript files which import from node modules eg
 ```javascript
import { View } from 'react-native'
```
The reference to the type file is given in the path  `/Users/mac/Library/Caches/typescript/2.7/node_modules/@types/react-native/index`. 

When i check the version of the `@types/react-native` in the cache folder the version is `0.52.8`.
While my package.json version of the react-native package is `0.49.3` . This is causing import flow errors all over my project. When i tried to manually set a version to the `@types/react-native`  package via package.json in the parent cache folder, it gets overwritten to the new version (0.52.8).

- VSCode Version: 1.20.0
- OS Version: OSX ex capitan 10.11.6

I am using the `vs-code-flow plugin`. Is it likely that its an issue caused by the plugin

**Comment by mjbvz** [comment]
Please try manually installing the correct `@types` version in your workspace:

```bash
$ npm install --save-dev @types/react-native@0.49.3
```

Does this fix the problem?

**Comment by nitish24p** [comment]
@mjbvz i tried adding the types package manually as you suggested, and no it doesnt solve the problem. Although now the reference to the module is within my node modules and not the typescript cache.

**Comment by mjbvz** [comment]
@nitish24p Do you think the issue with the typings themselves or with your flow imports? Can you provide an example screenshot of one of the errors

**Comment by nitish24p** [comment]
I get the following error.. when i do the following
```javascript
import {
  ActivityIndicator,
  DatePickerAndroid,
  Keyboard,
  Modal,
  Picker,
  ScrollView,
  TimePickerAndroid,
  View
} from 'react-native';
```

I get 
```
Named import from module `react-native` (This module only has a default export. Did you mean `import Keyboard from ...`?)
```
Now when i see the reference of `react-native` it references `workspace/App/node_modules/@types/react-native/index`

**Comment by AirshipAlex** [comment]
I'm seeing the original error here too. Not sure what's up.

VS Code: 1.20.1
flow-for-vscode: 0.7.3
React Native: 0.54.0
Flow-bin: 0.66.0

**Comment by mjbvz** [comment]
Not sure what to do about this since it seems caused by flow. In VS Code 1.21, you can now [disable the built-in js/ts extension](https://code.visualstudio.com/updates/v1_21#_manage-builtin-extensions). I recommend doing that if you are using the vscode flow extension 

Please let me know if you see this error in a normal js or ts project when not using the flow extension

**Comment by nitish24p** [comment]
So i changed my flow config to use the latest one from create-react-native-app and it fixed the error. dont know if this is a hack or some issue with the extension or vscode, or my flow config

**Comment by leggomuhgreggo** [comment]
[Link for the lazy](https://github.com/react-community/create-react-native-app/blob/44ea03cfe0799a4ee914b08f4983afe4ee4bdcb1/react-native-scripts/template/.flowconfig)

thanks for reporting @nitish24p
