### ISSUE TITLE
Shell script syntax highlighting error

### ISSUE THREAD

**Issue by vladrulez** [Microsoft/vscode#43209]
- VSCode Version: code 1.20.0-1518023506
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Make a .sh file containing the following codes:
```sh
Variable=$(cat << 'EOF'
text
EOF
)
echo test
```

2. The last line must be highlighted as a new statement, but it is not.

Does this issue occur when all extensions are disabled?: Yes

Screenshot https://i.imgur.com/z2dcbjY.png

**Comment by vladrulez** [comment]
Screenshot https://i.imgur.com/z2dcbjY.png

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#103
