### ISSUE TITLE
In the menu in the Russian localization there is not a translated item

### ISSUE THREAD

**Issue by EagleEYErus** [Microsoft/vscode#43214]
- VSCode Version: 1.20.0
- OS Version: macOS High Sierra 10.13.3

Steps to Reproduce:

1. In the editor, click on the bottom left of the settings icon
2. All menu items will be localized, except one

Does this issue occur when all extensions are disabled?: Did not try

![2018-02-08 17 11 37](https://user-images.githubusercontent.com/15634499/35977397-174c963e-0cf4-11e8-8b77-de732a2bc084.png)

**Comment by dbaeumer** [comment]
It takes us ~ 1 week to translate the strings into all language. So a x.0 release can ship with partly English strings and we try our best to have the first recovery build fully translated. Closing since we received full translations for Russian yesterday.
