### ISSUE TITLE
Placeholder in error: Cannot determine executable for debug adapter '{0}'.

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43215]
This error message doesn't get its placeholder replaced correctly:

![Cannot determine executable for debug adapter '{0}'.](https://user-images.githubusercontent.com/1078012/35977447-1131b4aa-0cdb-11e8-9dc2-65a5337e4bd0.png)

(Don't worry about the reason for the error; that's my fault; but the message should have the ID in it!)

**Comment by joaomoreno** [comment]
Verified by code review.
