### ISSUE TITLE
loc]Request to add Filipino(fil) language to Transifex VS Code project 

### ISSUE THREAD

**Issue by agentzero1** [microsoft/vscode#43218]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by danyeh** [comment]
We expect at least **three language contributors** sign up and product team sign off before adding new language to Transifex. Please **vote** by adding your **Transifex account name** here in this issue (request).
How to request guide: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by jedau** [comment]
Putting my name in the hat. Transifex Account Name: **jedau**

**Comment by danyeh** [comment]
We don't have plan to enable additional language for VSCode in MLCP in near term. Hence close the request here.
New request should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)
