### ISSUE TITLE
Find popup doesn't have recent searches

### ISSUE THREAD

**Issue by NN---** [Microsoft/vscode#43210]
There is no simple way to find something that has been searched before.
I would expect that 'Arrow Up' and 'Arrow Down' go through recent find text.

**Comment by roblourens** [comment]
alt+up and alt+down do this

**Comment by NN---** [comment]
Thanks.
It was not obvious.
Is it possible to have drop down list to open with mouse click or some shortcut?

**Comment by roblourens** [comment]
It's come up before - if we do some more significant UI work on find/search, we will probably look into it.
