### ISSUE TITLE
se pone muy lento 

### ISSUE THREAD

**Issue by nickdeyvis** [Microsoft/vscode#43219]
- VSCode Version: <code>Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)</code>
- OS Version: <code>Windows_NT x64 10.0.16299</code>
- CPUs: <code>Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)</code>
- Memory (System): <code>11.83GB (2.53GB free)</code>
- Memory (Process): <code>224.30MB working set (225.35MB peak, 203.98MB private, 49.64MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|1635|
|main|app.isReady => window.loadUrl()|3446|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|4460|
|renderer|require(workbench.main.js)|1012|
|renderer|create extension host => extensions onReady()|5636|
|renderer|restore viewlet|18|
|renderer|restore editor view state|3329|
|renderer|overall workbench load|3776|
|main + renderer|start => extensions ready|16934|
|main + renderer|start => workbench ready|14726|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by octref** [comment]
It translates as "it gets really slow"

@nickdeyvis Can you please use English, thanks.

**Comment by jrieken** [comment]
Please attach the profile files.
