### ISSUE TITLE
Ctrl+D highlights substrings :( 

### ISSUE THREAD

**Issue by squarewave24** [Microsoft/vscode#43217]
on Sublime 3.0 Build 3143

![image](https://user-images.githubusercontent.com/843437/35978766-94a13e18-0cb4-11e8-828e-77f677acd9aa.png)

i've read other posts on here and they claim that we should use the find widget options, but my find widget is set to whole words.  yet it keeps selecting substrings. 

![image](https://user-images.githubusercontent.com/843437/35979070-5984d21c-0cb5-11e8-9f59-d51dc4c15926.png)

**Comment by alexandrudima** [comment]
@squarewave24 Can you please include some steps
