### ISSUE TITLE
Python indentation error with blank line after def

### ISSUE THREAD

**Issue by untitledds** [Microsoft/vscode#43211]
### Issue Type
Bug

### Description

CODE:
```
class pc(object):

    def __init__(self, pcname, model):
        self.pcname = pcname
        self.model = model

    def print_name(self):
        print('Workstation name is', self.pcname, 'model is', self.model)
```
1. Format Selected
2. Run Selection 
```
IndentationError: unexpected indent

>>> class pc(object):
...
  File "<stdin>", line 2

    ^
IndentationError: expected an indented block
>>>     def __init__(self, pcname, model):
  File "<stdin>", line 1
    def __init__(self, pcname, model):
    ^
IndentationError: unexpected indent
>>>         self.pcname = pcname
  File "<stdin>", line 1
    self.pcname = pcname
    ^
IndentationError: unexpected indent
>>>         self.model = model
  File "<stdin>", line 1
    self.model = model
    ^
IndentationError: unexpected indent
>>>
>>>     def print_name(self):
  File "<stdin>", line 1
    def print_name(self):
    ^
IndentationError: unexpected indent
>>>         print('Workstation name is', self.pcname, 'model is', self.model)
  File "<stdin>", line 1
    print('Workstation name is', self.pcname, 'model is', self.model)
    ^
IndentationError: unexpected indent
```

If i delete blank line after def, no error

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|11.89GB (3.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.1.8
project-manager|ale|0.24.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
net-core-starters-pack|bla|1.0.0
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|0.10.14
vscode-quick-select|dba|0.2.5
git-extension-pack|don|0.1.3
githistory|don|0.4.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
gitlens|eam|8.0.0
EditorConfig|Edi|0.12.0
csharpextensions|jch|1.3.0
vscode-csharp-snippets|jor|0.2.0
docomment|k--|0.0.17
MagicPython|mag|1.0.12
python|ms-|2018.1.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
material-icon-theme|PKi|3.2.2
jinja|who|0.0.8
highlight-trailing-white-spaces|yba|0.0.2
vscode-open-in-github|ziy|1.3.1

</details>
Reproduces without extensions

**Comment by octref** [comment]
You should file an issue for https://github.com/Microsoft/vscode-python
