### ISSUE TITLE
Finding newlines \n does not work in Search sidebar

### ISSUE THREAD

**Issue by cbrnr** [Microsoft/vscode#43212]
- VSCode Version: 1.20.0
- OS Version: macOS 10.13.3

I know there are several (closed) issues on this, e.g. #313, but finding newline characters `\n` still doesn't work as expected.

Steps to Reproduce:

1. Open a buffer with some text
2. Open the Search sidebar (Find in Files)
3. Enable Regular Expressions
4. Enter `\n` in the search field and hit Enter - individual lines will be completely selected
5. Interestingly, this works as expected with the normal Find dialog.
6. Furthermore, replacing characters with `\n` works as expected, even in Find in Files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It's still not officially supported for search - https://github.com/Microsoft/vscode/issues/13155

If it seems inconsistent, it's because open files are searched by the editor, which does support multiline search. And replace with \n is easier than searching with \n.
