### ISSUE TITLE
Building 1.2.0 on Windows 7 x64 - error Command failed with exit code 3221225477.

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#43223]
- Visual Studio Professional 2015, activated with:

```
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
```

- Node, win7, x86:

```
C:\Acme\projects\vscode-build>node -v
v8.9.4
```

- VSCode Version: 1.2.0

- OS Version: Win7 x64

Steps to Reproduce:

1. Commands:

```
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

set PYTHON=C:\Program Files (x86)\Python271\python.exe

set PATH=%PATH%;C:\Program Files\7-Zip

npm.cmd config set loglevel verbose

mkdir tmp

npm.cmd config set cache tmp --global

npm.cmd cache clean --force

npm install yarn

npm set npm_config_arch ia32

yarn

yarn run watch
```

2. On `yarn run watch`:

```
C:\Acme\projects\vscode-build>yarn run watch
yarn run v1.3.2
$ gulp watch --max_old_space_size=4096
[16:06:30] Node flags detected: --max_old_space_size=4096
[16:06:30] Respawned to PID: 21904
error Command failed with exit code 3221225477.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

P.S. Building behind corporate proxy, if that matters.

**Comment by mrkafk** [comment]
Workaround:

```
gulp compile --verbose
gulp vscode-win32-ia32
```

**Comment by joaomoreno** [comment]
Glad you could find a workaround. We use the `max_old_space_size=4096` flag because we easily run into out-of-memory issues in our big builds. If you can build, that's great, so I'll close this issue.

How much memory does your system have btw?

**Comment by mrkafk** [comment]
8GB. `gulp` crashes immediately after being started by `yarn`.

**Comment by mrkafk** [comment]
@joaomoreno 

Curioser and curioser, I've just had `gulp vscode-win32-ia32` crash with:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

So out of blue I tried:

```
gulp  --max_old_space_size=2000 vscode-win32-ia32
```

And it built the product properly.

Perhaps node / gulp does not like setting full 4GB for `--max_old_space_size` ?

**Comment by joaomoreno** [comment]
Oh that could very well be!
