### ISSUE TITLE
Powershell Syntax Highlighting breaks on Regex in Parentheses

### ISSUE THREAD

**Issue by Slayman** [Microsoft/vscode#43224]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 
PowerShell|ms-|1.5.1

(1 theme extensions excluded)

---

Steps to Reproduce:
1. Create Regex: `$_ -match '(?i)^[a-z]{3}[0-9a]S[0-9]{3,}'`
2. Try to use Regex to validate Script:` [ValidateScript({$_ -match '(?i)^[a-z]{3}[0-9a]S[0-9]{3,}'})]`
3. It breaks the Moment you go from `[({$_ -match '(?i)^[a-z]{3}[0-9a]S[0-9]{3,}'})]`
to `[V({$_ -match '(?i)^[a-z]{3}[0-9a]S[0-9]{3,}'})]`

4. the first `'` is ignored and thus everything after the second `'` is now highlighted as string.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
https://GitHub.com/powershell/editorsyntax has changed the grammar to what we had in 1.20. That means this issue is back again. 
Duplicate of #36991
#36991 moved to https://GitHub.com/powershell/editorsyntax.
