### ISSUE TITLE
extensions.ignoreRecommendations to true but still getting recommendations

### ISSUE THREAD

**Issue by BritFox42** [Microsoft/vscode#43221]
Hello,

My parameters:

    "update.channel": "none",
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "extensions.autoUpdate": false,
    "extensions.ignoreRecommendations": true,

But i'm still getting extensions recommandations, like "Notepad++ keymap".
And it tells me it's recommanded because Notepad++ is installed...
So how to be sure the rest is disabled ???

How to stop Visual Studio Code  spying the list of applications installed on my computer ?

**Comment by ramya-rao-a** [comment]
The `extensions.ignoreRecommendations` setting is to stop the notifications/prompt for recommendations. We will look into adding a setting to disable recommendations altogether until the user specifically asks for them.

**Comment by ramya-rao-a** [comment]
In the latest [Insiders](https://code.visualstudio.com/insiders), you add the setting `"extensions.showRecommendationsOnlyOnDemand": true` to avoid VS Code from providing any recommendations unless you specifically ask via the `Extensions: Show Recommended Extensions` command
