### ISSUE TITLE
Watcher: Lots of errors in Linux

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#43227]
1. Run Code OSS: `./scripts.code.sh`, just open any folder with a few files in it

![image](https://user-images.githubusercontent.com/22350/35982483-3937c006-0cf0-11e8-80fd-50f4db26d303.png)

**Comment by bpasero** [comment]
Could be https://github.com/Microsoft/vscode/issues/7950 ?

**Comment by joaomoreno** [comment]
Yeah for sure!
