### ISSUE TITLE
No when I'm looking for something about Visual Studio, Google result show Visual Studio Code result instead and it is boring

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#43222]
Why you did this to us?

I can not find anything useful about Visual Studio in first page of Google's search result. any article, marketplace, blah blah blah is about VSCode, even if I search for `blah blah Visual Studio 2017`.

Damn, it's really boring!

**Comment by roblourens** [comment]
"Visual Studio 2017" gives me results for VS. You can try "Visual Studio IDE" too.
