### ISSUE TITLE
Preferred quote character for autocomplete/quick fixes

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#43225]
You guys are doing so great!

Can there please be a setting for the preferred quote character to use in autocomplete scenarios?  To be used for auto-import statements, or auto-quoting of completed member names with spaces (the new feature that uses string indexing to access members that are not valid javascript identifiers).  

Right now it's always using double-quote character whereas I happen to prefer a single-quote character for js/ts as a habit (perhaps to reduce the need for escape characters for UI literal double-quotes and quoted html attributes?) - this would be nice for consistency.

**Comment by mjbvz** [comment]
Thanks! Opened https://github.com/Microsoft/vscode/issues/43225 to track this upstream
