### ISSUE TITLE
Git: "Open File" from context menu of an outgoing change opens the diff editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#43229]
And not the file anymore.

**Comment by joaomoreno** [comment]
Actually the repro is:

1. Open the context menu on the resource
2. <kbd>Escape</kbd>

The `git.openResource` action runs, which is the default click action for git resources.

**Comment by joaomoreno** [comment]
Bisect told me this caused it: https://github.com/Microsoft/vscode/commit/d2fd388ba42b22d8bbb4618549dc9c9140ef764f
