### ISSUE TITLE
Emmet expansion STILL does not work for imported React custom components (Please reopen issue #40463)

### ISSUE THREAD

**Issue by LPsyCongroo** [Microsoft/vscode#43239]
Can we reopen issue #[40463](https://github.com/Microsoft/vscode/issues/40463)

I'm having the exact same problem but even disabling the extensions doesn't work. The original poster of the issue seemed to have figured something out but was vague on the details. The issue was closed without a concrete solution. Not helpful for those with the same issue =/

- VSCode Version: 1.20 (and 1.19 - updating didn't work either)
- OS Version: Windows 10

Steps to Reproduce:

1.
```javascript
//my_react_comp.js
export default class MyReactComp extends Component () {
  //render, etc
}
```

2.
```javascript
//app.js
import MyReactComp from "./my_react_comp.js";

export default class App extends Component {
  render() {
    return (

      MyReactComp
      // before I could type this and tab, getting <MyReactComp><MyReactComp/>
      //now I can't.

    );
  }
}
```

Here is my config:
```json
// Place your settings in this file to overwrite the default settings
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "window.zoomLevel": 1,
    "editor.tabSize": 2,
    "workbench.colorTheme": "Visual Studio Dark",
    "emmet.syntaxProfiles": {
        "javascript": "jsx"
    },
    "files.associations": { "*.js": "javascriptreact" },
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
}
```

**Comment by ramya-rao-a** [comment]
>  before I could type this and tab, getting <MyReactComp><MyReactComp/> now I can't

What do you mean by "before"? A couple of releases ago? Or a long time ago?

**Comment by LPsyCongroo** [comment]
At most, around 3 weeks ago. I'm not sure what the default behavior is
supposed to be, but I never had really had to configure anything to get
this to work. There are no extensions that I uninstalled that I think could
have had anything to do with it (I uninstalled a laravel extension with no
dependencies).  Everything in my config after color theme, I added today in
an effort to make it work.  Thanks to the last three settings, I can expand
any html element like "div" (which I couldn't before either) but the
imported component won't expand.

Intellisense also used to show me that what was imported was a class/object
but it's not doing that either.  It only does that if the component class
is in the same file.

[image: Inline image 3]

**Comment by pavelloz** [comment]
... i cant believe this is still an issue after the battle that has been won over it.

This is the third time im fighting (and wasting time) with this issue on one of my computers and im pretty close of leaving VS code because this is beyond stupid for me. This has been changed without any real reason communicated to the community, there are numerous issues reported on github, setting `"emmet.triggerExpansionOnTab": true` is apparently not working - i did manage to make it work twice, but not today and you would think with experience it gets easier.

Any changes to what have been perfectly fine is just a stupid idea. Bring back default tab behavior for emmet and allow those who dont use it remap it to whatever they want to. This is true for ALL editors that support emmet and so far and nobody complained about this state of things (or at least ive never seen anyone) - why are you trying to force people to change their behavior and dig into some weird configurations? Ive never seen any real explanation behind those changes and ive seen a lot of complaints because of it being implemented.

This is so frustrating when people have work to do and they have to fight against something completely useless and unproductive like this.

Dont change things that are working.

**Comment by LPsyCongroo** [comment]
I tried adding setting triggerExpansionOnTab to true and now any characters I type will tab and expand, which is what I was used to.  Now I can at least use Emmet the way I did before.

Unfortunately, there are still intellisense problems. 

The behavior is as follows:

Intellisense _will_ recognize an imported object in the drop down in the render function...
EXCEPT when it is inside the parenthesis of the return statement. This is a little annoying, as react components are often written as JSX _inside_ a parenthesis when there is more than one line. I don't know of an extension that takes care of this but I'd love to hear about it if anyone else does.

@ramya-rao-a  
I'll be happy to run any tests you guys need to help see if there is a fix for this. All in all, my only complaint was that an issue was closed but no definitive solution was left for others to find and read about. I think it might be a good practice to ask those who've found a fix on their own to mention what worked in case someone else has the same problem =]

@pavelloz I know not having your editor work the way it should can be frustrating. Here's the relevant parts of my final config. It was thanks to your mention of triggerExpansionOnTab that I at least got the Emmet part working, so I hope it will work for you:

```JSON
{
    "emmet.syntaxProfiles": {
        "javascript": "jsx"
    },
    "files.associations": { "*.js": "javascriptreact" },
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "emmet.triggerExpansionOnTab": true
}
```

**Comment by ramya-rao-a** [comment]
@LPsyCongroo If you want emmet to expand your custom tags using tab in javascript files, then the settings you need is either
```
"emmet.triggerExpansionOnTab": true,
"files.associations": { "*.js": "javascriptreact" }
```
or
```
"emmet.triggerExpansionOnTab": true,
"emmet.includeLanguages": {
	"javascript": "javascriptreact"
}
```

`"emmet.triggerExpansionOnTab": true` will ensure emmet is called when you press the tab key. 
`"files.associations": { "*.js": "javascriptreact" }` makes VS Code treat all javascript files as javascriptreact files
`"emmet.includeLanguages": {"javascript": "javascriptreact"}` makes the emmet extension in VS Code treat javascript files as javascriptreact files

I have tried both the above combinations using your sample code and they work as expected. Please give them a try.

**Comment by pavelloz** [comment]
Hey, thanks for quick reply, i managed to fix it, but the problem was not in the config but in the keybindings.

So basically i changed nothing, but the source of keybinding - when it was "Default" it didnt work, when i edited the binding, clicked tab, enter, it changed to "User" and now it works.

![image](https://user-images.githubusercontent.com/546845/36003936-d2a91922-0d38-11e8-8a2d-d66512911a3b.png)

Imagine how desperate i was to even try that...

**Comment by ramya-rao-a** [comment]
@LPsyCongroo Glad to hear that setting `emmet.triggerExpansionOnTab` solved the issue for you, looks like my above reply came just minutes after you got things working.

Nevertheless, please give [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet) a read when you have some time

> Intellisense will recognize an imported object in the drop down in the render function...
EXCEPT when it is inside the parenthesis of the return statement. 

I was not able to repro this. See the below gif
![jsx](https://user-images.githubusercontent.com/16890566/36003914-eb5dd5b0-0ce4-11e8-82f3-931032d6c753.gif)
Am I missing something?

> All in all, my only complaint was that an issue was closed but no definitive solution was left for others to find and read about

I just assumed that some other extension was interfering with the tab key and so didn't press for any more details. Will make sure to do so in the future

**Comment by ramya-rao-a** [comment]
@pavelloz Emmet on tab should work without needing any changes to the keybindings. Can you share any changes done around emmet from your keybindings file? To open this file run the command `Preferences: Open Keyboard Shortcuts File`

**Comment by pavelloz** [comment]
Screenshot i pasted above illustrates all the changes i did around emmet. I replaced tab with tab, it changed from default to user. 

Ful version:
https://user-images.githubusercontent.com/546845/36004252-6d2c099a-0d3a-11e8-8c3c-11cc8c89bd31.png

**Comment by ramya-rao-a** [comment]
@pavelloz Can you click on the "keybindings.json" link to open the json file and remove/comment the entry for emmet expansion and see if that changes anything? I can't wrap my mind around the theory that changing a default keybinding to a user keybinding (without changing either the command/key/when clause) makes any difference 😕

**Comment by LPsyCongroo** [comment]
@ramya-rao-a 
I played around a bit and it is quite strange.  In an empty parenthesis it works fine, but within a div it doesn't.  What's more, when I forgot to erase the class above the div, it worked.

![git](https://user-images.githubusercontent.com/16440817/36004805-9e51edce-0d02-11e8-8ff1-d0a4e70017ec.gif)

**Comment by mjbvz** [comment]
@LPsyCongroo This is the expected behavior. Please see my comment on https://github.com/Microsoft/vscode/issues/43266#issuecomment-364295334

**Comment by pavelloz** [comment]
@ramya-rao-a I dont know how, but my `keybindings.json` file got emptied (`// Empty` comment) , source of keybinding in the GUI got reverted to "Default" and emmet doesnt work again. So now, i did the same thing as yesterday, so now my keybindings.json is:

```json
[
  {
    "key": "tab",
    "command": "editor.emmet.action.expandAbbreviation",
    "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorReadonly && !editorTabMovesFocus"
  },
  {
    "key": "tab",
    "command": "-editor.emmet.action.expandAbbreviation",
    "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorReadonly && !editorTabMovesFocus"
  }
]```

Which is exactly default - now it works perfectly.

**Comment by LPsyCongroo** [comment]
@ramya-rao-a 
@mjbvz 
Thanks.  If that's the default, it's possible some extension I was using provided the intellisense behavior I was used to. Now the hunt begins. 

If I find something before this issue wraps up, I'll post it.

**Comment by ramya-rao-a** [comment]
@pavelloz Restarting the editor shouldnt change the keybindings. If it does, then thats a serious issue. Can you test that?

**Comment by pavelloz** [comment]
@ramya-rao-a It was a joke, but i tested it - this time keybindings are intact.
They did however cleared somewhere in the space-time continuum yesterday.

**Comment by ramya-rao-a** [comment]
@pavelloz Do you have any extensions for keymaps installed? They might be interfering with the keybindings. Disable them, clear your `keybindings.json` file and then see if you get emmet using tab
