### ISSUE TITLE
[REQUEST] Find open file

### ISSUE THREAD

**Issue by yuric18** [Microsoft/vscode#43230]
Let's suppose you have several open files, like, on my workspace I have 1961 files. When I have to open a specific file (just open and then move to a specific line number) I need to use the scroll bar and find the file manually. 

What if we have a search bar fixed on the Explorer, so we can type a file name and it starts to filter the files opened on the workspace?

**Comment by bpasero** [comment]
@yuric18 we typically use our pickers for that purpose, have you tried? E.g. Ctrl+P to open any file or View  > Show All Editors

![image](https://user-images.githubusercontent.com/900690/35986705-173f5568-0cfa-11e8-8462-189b41883abd.png)
