### ISSUE TITLE
Shell script parsing - # as a command flag makes a bad highlight

### ISSUE THREAD

**Issue by Eriobis** [Microsoft/vscode#43236]
- VSCode Version: 1.20.0
- OS Version:

Steps to Reproduce:

1. Create a .sh file
2. Use this command : `curl -# $PROXY -X POST -H "Authorization: Bearer ${API_KEY}" "${URL}"`
3. Everything after the # should be grayed out, but it's an argument for the command

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by Eriobis** [comment]
Found a way to fix it, add

`
"begin": "(^\\s+)?(?<=^|\\W)(?=#)(?=-#)"
`

at line 144 of the shell-unix-bash.tmLanguage.json into the "comment": { section

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#104
