### ISSUE TITLE
Enable "code ." to be entered on the Windows 10 Windows Explorer address bar

### ISSUE THREAD

**Issue by mwherman2000** [microsoft/vscode#43237]
Enable "code ." to be entered on the Windows 10 Windows Explorer address bar **and** have vscode open the currently displayed directory path.

For example, entering "cmd" in the Windows Explorer address bar will open the Command Prompt with its cwd set to Windows Explorer's currently displayed directory path.  Why can't vscode work the same way?

Best regards,
Michael Herman (Toronto)

**Comment by mwherman2000** [comment]
Bonus request: Entering "code anysubfolder" should open the folder "anysubfolder" in Windows Explorer's currently displayed directory path (if it exists)

**Comment by Hyperclaw79** [comment]
Alternatively, you could type `code.cmd .` instead to open up VS Code in that file directory.
The only backdrop is that it opens an empty cmd shell in the background.
Inferring from the behaviour, I think it is equivalent to opening a cmd in that directory and running `code .` in it.

**Comment by abdallahmansour6** [comment]
> For me, I can open "code ." from address bar by adding new path in system env variable C:\Program Files\Microsoft VS Code.
> 
> It will open vscode for current directory. Make sure the where command display code.exe at the top
> 
> $ where code C:\Program Files\Microsoft VS Code\Code.exe C:\Program Files\Microsoft VS Code\bin\code C:\Program Files\Microsoft VS Code\bin\code.cmd

I will be thankful if you explain why did it work

**Comment by 5p4r70n** [comment]
> Alternatively, you could type `code.cmd .` instead to open up VS Code in that file directory. The only backdrop is that it opens an empty cmd shell in the background. Inferring from the behaviour, I think it is equivalent to opening a cmd in that directory and running `code .` in it.

add "exit" at the end of the file "code.cmd"  that will close the terminal after opening the visual studio code.. :)

@abdallahmansour6
in my win11 system "code" detected in console but from address bar its not working , rest all are working fine 
i think from address bar windows is looking somewhere else instead of the env variable..
