### ISSUE TITLE
Source control icon is blinking every few seconds

### ISSUE THREAD

**Issue by van-Kalsing** [Microsoft/vscode#43234]
![issue](https://user-images.githubusercontent.com/3389910/35987960-4a82d58a-0d0e-11e8-87a5-7cfa8c75111a.png)

Marked icon does blink every few seconds and that's annoying

- VSCode Version: 1.20.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open a folder with initialized git repository

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Did this not happen in 1.19 for you?

Also, run the `Git: Show Git Output` command. The output will tell you what commands git are running. What do you see there?

Do you use multiple workspaces?

**Comment by van-Kalsing** [comment]
Icon blinks every time git commands are invoking. I noticed this when I was watching for Git Output and SC icon. For example when upstream isn't configured for active branch, Git Output contains this block multiple times:
```
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
git status -z -u
git symbolic-ref --short HEAD
git rev-parse dtmp
git rev-parse --symbolic-full-name --abbrev-ref dtmp@{u}
fatal: no upstream configured for branch 'dtmp'
```
Icon blinks every time the block appears in the output. Similar blinkings take place every time I save changes.

I've noticed this behavior only for version 1.20.

**Comment by van-Kalsing** [comment]
I've set upstream for current branch and regular blinking stopped. But I don't want blinking to take place for branches without upstream, just initialized repositories (you can try to reproduce issue by opening folder with just initialized repository. In that case Git Output also contains regular 'fatal' messages), etc.

**Comment by van-Kalsing** [comment]
> Do you use multiple workspaces?

No

**Comment by joaomoreno** [comment]
How fast does `git status` run in your system?

**Comment by mctep** [comment]
Hi! I have the same issue.

OSX Version 10.13.3
VSCode Version 1.20.0

```bash
# start VSCode
Looking for git in: /usr/local/bin/git
Using git 2.13.3 from /usr/local/bin/git
git rev-parse --show-toplevel
git config --get commit.template
git status -z -u
git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

git symbolic-ref --short HEAD
git rev-parse branch-name
git rev-parse --symbolic-full-name --abbrev-ref branch-name@{u}
git rev-list --left-right branch-name...origin/branch-name
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

# repeats every few seconds
git check-ignore -z --stdin
git status -z -u
git symbolic-ref --short HEAD
git rev-parse branch-name
git rev-parse --symbolic-full-name --abbrev-ref branch-name@{u}
git rev-list --left-right branch-name...origin/branch-name
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose
```
> How fast does git status run in your system?

```bash
$ time git status
On branch branch-name
Your branch is up-to-date with 'origin/branch-name'.
nothing to commit, working tree clean

real	0m0.011s
user	0m0.004s
sys	0m0.006s
```

> Do you use multiple workspaces?

No.

> Did this not happen in 1.19 for you?

No.

**Comment by van-Kalsing** [comment]
> How fast does git status run in your system?

About 0.043s

test.sh:
```
#!/bin/bash
i=0
while [ $i -lt 100 ]; do
    git status >> /dev/null
    i=$((i + 1))
done
```

Execution of test and its output:
```
$ time bash test.sh

real    0m4.270s
user    0m0.045s
sys     0m0.420s
```

**Comment by joaomoreno** [comment]
Broken by https://github.com/Microsoft/vscode/commit/135b261f884410b427c9ec8bd56059a792a352ad

**Comment by joaomoreno** [comment]
@van-Kalsing @mctep @wolfsilver @HI0T

Since I can't seem to reproduce this happening every few seconds, I need one of you to record a screencast of Code in that state, having the `Git: Show Git Output` panel open. I want to see what comes out of that panel every few seconds, as the badge comes and goes.

**Comment by wolfsilver** [comment]
![gif](https://user-images.githubusercontent.com/2452450/36144916-99ee65c8-10ea-11e8-9e66-cee2cd4bf090.gif)

**Comment by joaomoreno** [comment]
@wolfsilver Awesome. Can you now launch with `code --verbose`, then open the Developer Tools and include that in the movie too? I'm interested in seeing what kind of file events trigger that status call. Something like this: 

![image](https://user-images.githubusercontent.com/22350/36145442-ae19b1e4-10b1-11e8-9d68-31c049b29b2d.png)

**Comment by mctep** [comment]
@joaomoreno Looks I have found the problem.

In my case there is meteor mongo database that triggers files changes in `.meteor` directory when running. But this files in `.gitignore`.

I have created small repo for reproduce https://github.com/mctep/vscode-bug

Clone run and `bash test.sh`.

**Comment by wolfsilver** [comment]
@joaomoreno can't reproduce now.
This reproduce on my work PC.
I'm on the way home for Spring Festival.
sorry

**Comment by joaomoreno** [comment]
@mctep Great. That explains a lot. If there are really changes happening inside your workspace, then it's fine. We just have to tweak the timings in which `git status` runs.

**Comment by van-Kalsing** [comment]
![issue](https://user-images.githubusercontent.com/3389910/36198380-7e257c4e-1187-11e8-9ded-64c7714f519a.gif)

**Comment by joaomoreno** [comment]
@van-Kalsing Thanks for that! 
Can you try out our [insider release](https://code.visualstudio.com/insiders), make sure it reproduces too over there?

**Comment by van-Kalsing** [comment]
@joaomoreno Yes, it reproduces.

![issueinsiders](https://user-images.githubusercontent.com/3389910/36246274-058da342-1240-11e8-81ac-3f38cddb5f14.gif)

```
$ git --version
git version 2.14.1.windows.1
```

**Comment by joaomoreno** [comment]
@van-Kalsing Keeping that window open in the background, open a Command Prompt. In it, type `git status`. Do those file events appear in the devtools still?

Do you have any git plugin installed?

**Comment by HarrisKirk** [comment]
I also have this problem.   VSCode 1.20.1   
Did not happen with vscode 1.19

**Comment by van-Kalsing** [comment]
@joaomoreno Now 1.21.0-insiders. Blinking still exists (it's not on gif because the window is without focus).

> Do you have any git plugin installed?

No

![issueinsiders](https://user-images.githubusercontent.com/3389910/36507347-7122eebc-176a-11e8-9a22-dfccbe439469.gif)

**Comment by joaomoreno** [comment]
@van-Kalsing Can you update to the latest Git and see whether it still reproduces? Git 2.16.2 has released a new feature which should help with this!

**Comment by HarrisKirk** [comment]
I updated to git 2.16.2 and the issue appears to be resolved.

**Comment by joaomoreno** [comment]
@van-Kalsing Can you confirm this too?

**Comment by joaomoreno** [comment]
Hard to verify. Git 2.16.2 released support for running `git status` without touching the index, which we leverage. The fix is aimed at older Git versions and starts ignoring events on the `.git` folder itself when considering when to run `git status`.

**Comment by sbatten** [comment]
Happened to have 2.16.1.windows.4 installed and was able to repro on 1.20.1, verified fixed in latest insiders.

**Comment by van-Kalsing** [comment]
@joaomoreno I've updated Git to 2.16.2 and icon stopped to blink (now only on saving files). Thanks
