### ISSUE TITLE
Each click into actionbar is delayed by 50ms?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#43232]
It looks like each click to any action in the action bar is [delayed by 50ms](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/actionbar/actionbar.ts#L142), coming in from https://github.com/Microsoft/vscode/commit/a740256d083701021fe588fd0a4c9c095bdeb68f. That means any user interaction in this control is delayed. What is the reason?

**Comment by bpasero** [comment]
Wait, this came in via https://github.com/Microsoft/vscode/commit/a740256d083701021fe588fd0a4c9c095bdeb68f. @jrieken whats the reason? If I take the timeout out I see no issue.

**Comment by alexandrudima** [comment]
Yeah, my change removes the timeout...

**Comment by jrieken** [comment]
Yeah, no idea why that is... Maybe something that was/is an issue with the animation? I seems to work without but to keep the flow I'll change to `setImmediate` first
