### ISSUE TITLE
Git: Add number of modified lines to scm viewlet

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#43231]
![before](https://user-images.githubusercontent.com/9638156/35985259-4a7d5fd0-0d07-11e8-8619-b9e8654c0987.png)
![after](https://user-images.githubusercontent.com/9638156/35985274-52913c00-0d07-11e8-976f-aa420deefac0.png)

**Comment by joaomoreno** [comment]
That's pretty cool.

**Comment by joaomoreno** [comment]
This can be provided by an extension, given decorations support.

**Comment by usernamehw** [comment]
@joaomoreno, not sure I understand... Is it possible to put decorators from the extension to the existing git viewlet?

**Comment by joaomoreno** [comment]
Any extension can contribute decorations to any resource. Those decorations will appear wherever that resource appears, including the SCM viewlet.

**Comment by usernamehw** [comment]
@joaomoreno, I was only able to find how to add new scm view and apply decorations to it (https://code.visualstudio.com/docs/extensionAPI/api-scm#_source-control-model) but not how to change the existing one. 

Can you provide an example of code or a link to similar extension?

Still, isn't it makes sense to have it inside vscode to be able to theme red/green colors?

**Comment by joaomoreno** [comment]
@jrieken Can you provide guidance on how to add decorations to resources?

> Still, isn't it makes sense to have it inside vscode to be able to theme red/green colors?

Not sure I understand what this means.

**Comment by jrieken** [comment]
>  Can you provide guidance on how to add decorations to resources?

The decoration provider api isn't meant for that

**Comment by joaomoreno** [comment]
Oh! Too bad, I thought it would be possible to get this now.
