### ISSUE TITLE
Multi-select in the Explorer: Delete deselected folder instead of selected ones

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#43233]
### Issue Type
Bug

### Description

1. Multi-select several folders in the explorer.
2. Deselect a single folder (CTRL+Click)
3. Use the delete key on the keyboard

Expected: It should delete the folders in the multi-selection
Actual: It wants to delete the deselected folder

VSCode:
![multiselect_deselectone_delete_vscode](https://user-images.githubusercontent.com/15158320/35986501-81c38c16-0cf9-11e8-96b4-cd62ca2f52d5.gif)

Windows Explorer shows a different behavior:
![multiselect_deselectone_delete_windowsexplorer](https://user-images.githubusercontent.com/15158320/35986519-8f8f9678-0cf9-11e8-94a5-1c6fc7ddb89a.gif)

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (91120eb786357aa1e16217ad6a67cf0740f26e8e, 2018-02-08T05:16:13.920Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|Memory (System)|7.88GB (2.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
regex|chr|0.1.0
tslint|eg2|1.0.24
python|ms-|2018.1.0
ayu|tea|0.12.0
vscode-todo-highlight|way|0.5.11

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
@tsalinger good catch, I have fixed this in the explorer.

@joaomoreno I see the same issue in the list - if an element is being removed from a selection, it should not be focused. I tried fixing this by changing code [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/list/listWidget.ts#L472) however did not want to do it without your approval.

**Comment by joaomoreno** [comment]
@isidorn Sure, do what makes sense.

**Comment by isidorn** [comment]
@joaomoreno I have pushed
This changes the following:
* If a selection change range, focus the element clicked. Previously focus was not changed which I felt was wrong
* If an element is removed from a selection do not focus it
