### ISSUE TITLE
Large number of Multi-Cursor hangs on brackets

### ISSUE THREAD

**Issue by SpontaneousDuck** [microsoft/vscode#43238]
- VSCode Version: 1.20.0
- OS Version: Win10 1730 15063

Steps to Reproduce:

1. Using a large text file (60k lines) use shift+alt to place a cursor on every line in the file.
2. Typing most characters works with some input lag which is understandable. But, entering an opening or closing brackets cause the editor to hang and require restart. ("{" or "}")

Does this issue occur when all extensions are disabled?: Yes

**Comment by SpontaneousDuck** [comment]
Trying smaller multi-cursor selection sizes inside the 60k line file. Selection sizes greater than 5000 lines cause this problem to occur.

**Comment by SpontaneousDuck** [comment]
Issue is caused by the editor.matchBrackets setting. Changing this setting to false causes the problem to not occur.

**Comment by jats22** [comment]
Hi! I would like to take this up. Would love any code pointers. Thanks.

**Comment by deep110** [comment]
Hi, if no one is taking it up, I would like to give it a go. Would love any starting references. Thanks

**Comment by jats22** [comment]
Hi @deep110 already on it. :+1:

**Comment by Hexman768** [comment]
Are there any updates on this issue, I would love to give it a go! Also little update, the issue does not seem to kill vscode when entering an open bracket "{" on version 1.36.1, Only the closing bracket causes the program to crash now.
