### ISSUE TITLE
Build output disappears when terminal has focus and Ctrl is pressed

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#43246]
### Issue Type
Bug

### Description

Steps to reproduce:

1. Start build when terminal is hidden
2. Open/show integrated terminal (it gets keyboard focus this way)
3. Press Ctrl (left or right - doesn't matter, also Alt, Shift, etc)

Result: build output disappears, shell appears.

Additional info: doesn't reproduce when integrated terminal don't have keyboard focus (e.g. build was started with terminal on screen). But it always reproduces after:

1. Click on build ouput
2. Press Ctrl

I'm not sure if it supposed to work this way or not, but 1.19.3 works differently (doesn't switch to shell on Ctrl/Alt/Shift presses).

What doesn't work: sometimes it's impossible to Ctrl-Click on warning or error printed during build, it disappears right when Ctrl is pressed, before click could be made.

Also the following scenario works sort of inconsistently:

1. Run build when terminal is not on screen (hidden)
2. Show integrated terminal (with keyboard shortcut like Ctrl+~)

Result: build output appears in terminal

3. Hide terminal (with the same shortcut)
4. Show terminal again

Result: shell appears

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.4.0-112-generic (Ubuntu 14.04)

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
nightswitch-lite|gha|2.0.3
cpptools|ms-|0.14.6
shader|sle|1.1.2
cmake|twx|0.0.17
code-navigation|vik|0.2.0
vscode-todo-highlight|way|0.5.11
lua-for-vscode|xxx|0.0.23

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by cperthuis** [comment]
reproduced on OSX with CTRL and Command swapped in the OS settings.
It's extremely severe, it's impacting the dev workflow for the C/C++ extension making it impossible to jump to any compilation error. It's totally breaking our workflow.
An urgent patch would be greatly appreciated! Thanks.

**Comment by octref** [comment]
Tracking in #43250

**Comment by octref** [comment]
Actually, being tracked in https://github.com/Microsoft/vscode/issues/42066 and it'll go to our recovery build.
