### ISSUE TITLE
Gauntlet toolbar zooms in 

### ISSUE THREAD

**Issue by jwhit-MSFT** [Microsoft/vscode#43241]
Gauntlet toolbar removes options when I zoom the editor view. I want to control which options are removed or (preferably) keep the toolbar from zooming at all.

**Comment by seanmcbreen** [comment]
I think the is actually an issue for the gauntlet team either:
1. a feature request
2. looking at a new way to layout/offer up the controls.

I can connect you with that team via email.

Sean
