### ISSUE TITLE
Single quote in JSX breaks vscode code formatting

### ISSUE THREAD

**Issue by hamiltonia** [Microsoft/vscode#4324]
- VSCode Version: 0.10.11
- OS Version: Win 7, Mac OS 10.11.3

Steps to Reproduce:

If there is a single quote inside JSX, code formatting does not work for the entire file. Furthermore, if such a file is opened and tried code formatting, it breaks for all other files until a vscode restart.

Sample:

```
class Sample extends Component {
    render() {
        <View style={styles.container}>
            <Text style={styles.title}>Don't</Text>
        </View>
    }
}
``` 

First reported by @taypo: https://github.com/Microsoft/vscode-react-native/issues/156

**Comment by egamma** [comment]
@dbaeumer is this our edit infrastructure or the TS formatter?

**Comment by dbaeumer** [comment]
Salsa formatter. Moving.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7548
