### ISSUE TITLE
UX issue: workbench.action.terminal.runSelectedText does not move cursor to next line

### ISSUE THREAD

**Issue by kachkaev** [Microsoft/vscode#43242]
- VSCode Version: 1.20.0
- OS Version: macOS High Sierra

Does this issue occur when all extensions are disabled?: Yes

---

I'm coming form the Atom background, where it was possible to easily execute a few commands from an opened cheatsheet one-by-one. Thanks to [platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) and the ability to attach `ctrl+enter` to `platformio-ide-terminal:insert-selected-text` action, I could just navigate to a bunch of lines, _ctrl+enter_ the first one, then focus my eyes on the terminal and finally keep pressing _ctrl+enter_ again and again until I run all the commands that I want.

VSCode's awesome built-in terminal has a similar command called `workbench.action.terminal.runSelectedText`, which can be also bound to `ctrl+enter` to get parts of an opened file copy-pasted to the terminal.

However, the difference is that in VSCode the cursor does not move to the next line after `ctrl+enter` is pressed, no matter if the selection is empty or not.

It'd be great if VSCode could also move the cursor one line down when the length of the selection is zero. I guess here's a bit of code that could be changed for that:
https://github.com/Microsoft/vscode/blob/0e0c3ca415408794342ecaeb74ae2b9ae4d785e0/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts#L418-L425

I'm completely new to VSCode and am curious if what I'm asking for is reasonable and doable. Thanks a lot for this truly awesome app! 🎉

**Comment by octref** [comment]
You could use this extension (quite popular)
https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner

**Comment by kachkaev** [comment]
Hi @octref! I saw the code-runner extension and IMO its purpose is completely different. The ‘feature’ I am mentioning in this issue is more a UX bug fix than the actual new functionality. Its main purpose is in reducing the number of key presses a typical user would have to do when copy-pasting any text to any currently opened terminal. To be honest, I'm not sure that a couple of extra lines in the code snippet mentioned above is what can become an extension.

Once I get a bit more comfortable with VSCode, I can submit a PR with my vision of what I mean. No worries if gets rejected later – it'll be at least a bit more clear about what I consider as missing. If doing an extension will be the right way to go after the discussion, I'll be happy to work on that.

WDYT?

**Comment by octref** [comment]
I see. Leaving to @Tyriar to decide.
IMO when running `workbench.action.terminal.runSelectedText` on such a selection:

```
ls
ls
```

I would expect both commands to be run. Otherwise multiline commands such as 

```
command \
  --flag
```

would be broken.

**Comment by kachkaev** [comment]
When you select multiple lines as in your examples above, all of them run in one go, which is already correct.

The only problematic case is when _no characters are selected_ (`selection.isEmpty()`). VSCode runs the current line (regardless of `\` in the end, but that's totally fine), however, the cursor _remains on the same line_ instead of jumping line one down as this happens in Atom. From my own experience this jump is quite handy as it turns `ctrl+enter` `↓` `ctrl+enter` `↓` `ctrl+enter` `↓` into just `ctrl+enter` `ctrl+enter` `ctrl+enter` in a pretty common scenario.

**Comment by octref** [comment]
Oh I see what you actually meant...After running the current line, make the cursor go one line below.

**Comment by kachkaev** [comment]
Do we need a config option for this improved behaviour or is just changing the default one is OK? If the config option is needed, what would be the best name for it and the default value?

Would you be happy to accept a PR? I'm not sure I can do a good one but I can try.

**Comment by Tyriar** [comment]
I think this might be best left to a simple extension that runs the line and moves the cursor, I imagine after changing this people will want the old behavior back (eg. to run the same line multiple times). As for a setting to drive this behavior, it's *very* specific and would see limited usage so I think an extension is the way to go.

If you wanted to write one it should be very easy, you can use https://github.com/Microsoft/vscode-generator-code to generate a TS command extension and then you will just need to call:

`vscode.commands.executeCommand('workbench.action.terminal.runSelectedText')` followed by getting the `activeTextEditor` and doing a check on the current cursor and moving the line if there's no range in the selection. See https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametexteditoraspan-classcodeitem-id324texteditorspan
