### ISSUE TITLE
Triple click to copy extension id from editor copies a lot of other stuff

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#43240]
### Issue Type
Bug

### Description

- Click on any extension in the extensions view to open the extensions editor
- Triple click on the extension id (next to the extension name) -> the whole id gets selected 
- Ctrl+C to copy and them paste elsewhere

Expected: The extension id gets copy pasted
Actual: The extension id along with everything that follows it gets copy pasted

For eg: In the case of `ms-azuretools.vscode-azurefunctions`, the below gets copied to the clipboard
ms-azuretools.vscode-azurefunctions
Preview
Microsoft40,119RepositoryLicense
An Azure Functions extension for Visual Studio Code.
Install
Details
Contributions
Changelog
Dependencies

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (f9398645d1d624538708eeebf96e6fdeb546f5d7, 2018-02-06T15:20:43.871Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|Memory (System)|31.92GB (18.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.73
vsliveshare|ms-|0.2.66
debugger-for-chrome|msj|4.1.0
vscode-versionlens|pfl|0.19.1
sass-indented|rob|1.4.6
language-stylus|sys|1.8.0

</details>
Reproduces only with extensions

**Comment by ramya-rao-a** [comment]
@sandy081 I would suggest to add `help-wanted` and `good-first-issue` label to this one

**Comment by shobhitchittora** [comment]
@ramya-rao-a This is weird one. From my investigation if you give  - 
```css
user-select: text
``` 
to the element next to the `identifier` tag ( which is the `preview` tag in this case ), it fixes selection for the `identifier`. But this in-turn breaks again if you select `preview` tag.

Any to suggestions on this?

Attaching screenshot for the css - 
<img width="655" alt="screen shot 2018-02-10 at 3 03 48 pm" src="https://user-images.githubusercontent.com/4711855/36060648-ac667b88-0e73-11e8-8172-178314b43660.png">

**Comment by ramya-rao-a** [comment]
No idea :)
You will have to play around with values for `user-select` and understand how it behaves in different scenarios
