### ISSUE TITLE
Hitting inotify limit should be reported to the user

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#43247]
- VSCode Version: 1.20.0
- OS Version: Ubuntu 16.04

I've noticed that VSCode has stopped updating the list of tasks when I modify my `tasks.json` until I restart it.

After some head-scratching, I found this line in Developer Tools console: "[IPC Library: Watcher] Uncaught Exception:  Inotify limit reached", and indeed, one of the directories in my workspace had a large number of files (~45K) in its subtree.   Once I removed this directory and restarted VSCode, everything went back to normal.

Hitting inotify limit should be reported to the user.

**Comment by bpasero** [comment]
Continues in https://github.com/Microsoft/vscode/issues/7950
