### ISSUE TITLE
[Python 3] Defining multiple variables to same value in a single line causes error

### ISSUE THREAD

**Issue by teolicht** [Microsoft/vscode#43253]
### Issue Type
Bug

### Description

Define multiple variables (e.g 3) to a single value in a single line.  
Example: `var1, var2, var3 = argv` makes `var1` underlined red with: `[pylint] E0632:Possible unbalanced tuple unpacking with sequence: left side has 3 label(s), right side has 0 value(s)`

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.82GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
vscode-discord|max|1.0.2
python|ms-|2018.1.0
cpptools|ms-|0.14.6
sublime-keybindings|ms-|3.0.3
vscode-icons|rob|7.19.0

(3 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by usernamehw** [comment]
wrong repo https://github.com/Microsoft/vscode-python

**Comment by teolicht** [comment]
@usernamehw How do I report the bug in that repo's Issues tab? If I click 'New issue' it won't let me post the issue...
