### ISSUE TITLE
Add global commands for "new file" and "new folder"

### ISSUE THREAD

**Issue by gringonivoli** [Microsoft/vscode#43254]
- VSCode Version: 1.20
- OS Version: macOS Sierra

Missing commands for "new file" and "new folder".

Steps to Reproduce:

1.  Focus on File Explorer over a folder.
2. Press cmd + P.
3. Type "new folder" or "new file" and the commands not show.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/43363
