### ISSUE TITLE
Explorer: Make unsupported files visible

### ISSUE THREAD

**Issue by dgoodine** [Microsoft/vscode#43252]
- VSCode Version: 1.20.0
- OS Version: Mac OS 10.13.2

I use VSCode for developing code for Unity and often find that it would be useful to at least see files in the directory hierarchy where they would be, even if I can't do anything useful with them.

Often while writing code I'll want to verify that resources (like prefabs, shaders, etc.) are in the right place and it's awkward to have to switch back to Unity and drill down through the folders where I was just looking. Ditto for refactoring code file names that have a corresponding non-code asset.

Not necessarily a huge feature, but instead of filtering out files in a folder that VSCode can't operate on, simply show them with a generic file icon (and maybe slightly greyed out text) that only supports renaming, deletion, etc.

**Comment by bpasero** [comment]
@dgoodine the file explorer in VS Code is not hiding any files unless you configured some exclude rules via the `files.exclude` setting?

**Comment by dgoodine** [comment]
@bpasero You're absolutely right.  In fact, Unity has an option to do exactly that: add files to the filter for exclusion.  I must have done that when I first started using VSCode with Unity and completely forgotten about it.

I just went back to the workspace settings and removed the filters for files I wanted to see.  I'll close this.
