### ISSUE TITLE
Code Helper running multiple instances, chewing up memory

### ISSUE THREAD

**Issue by JCaraballo113** [Microsoft/vscode#43258]
### Issue Type
Performance Issue

### Description

Open Code. Check activity monitor, close it, open it again. You'll see "code helper" instances just keep opening up and never close

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|Load (avg)|3, 6, 5|
|Memory (System)|4.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

|pid|CPU|Memory (MB)|Name|
|---|---|---|---|
|716|39|111|code main|
|717|9|45|-- gpu-process|
|719|2|61|-- shared-process|
|858|12|193|-- window (Traits.react.js — opensea-next)|
|859|1|135|---- extensionHost|
|917|0|25|------ electron_node cssServerMain.js |
|918|0|37|------ electron_node server.js |
|938|0|33|------ electron_node jsonServerMain.js |
|958|0|41|------ electron_node server.js |
|964|0|111|------ electron_node electronForkStart.js tsserver.js |
|974|0|37|-------- electron_node typingsInstaller.js tsserver.js typesMap.js |
|860|0|20|---- watcherService|
|861|0|25|---- terminal|
|862|0|0|------ /bin/bash -l|
|927|0|20|---- searchService|
|983|89|90|-- shared-process|
|984|0|0|-- /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=|

</details><details>
<summary>Workspace Info</summary>

```
|  Window (Traits.react.js — opensea-next)
|    Folder (opensea-next): 288 files
|      File types: js(187) scss(32) png(27) ttf(12) json(11) ts(5) svg(4)
|                  jsx(3) gif(2) gitignore(1)
|      Conf files: launch.json(1) package.json(1);
```

</details>
<details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
erb|Cra|0.0.1
react-native-react-redux|EQu|1.4.1
EditorConfig|Edi|0.12.0
vsc-material-theme|Equ|1.3.0
beautify|Hoo|1.3.0
vscode-todo|Mat|0.8.0
vscode-jest|Ort|2.6.0
vscode-react-native-storybooks|Ort|2.5.1
material-icon-theme|PKi|3.2.2
code-settings-sync|Sha|2.8.7
unity-debug|Uni|1.2.1
vscode-wakatime|Wak|1.1.22
html-css-class-completion|Zig|1.16.1
vscode-caniuse|aka|0.5.3
react-pure-to-class-vscode|ang|1.1.2
vscode-color|ans|0.4.5
vscode-icontheme-nomo-dark|be5|1.3.5
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.1.1
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.5
gitlens|eam|8.0.0
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.1.3
php-intellisense|fel|2.2.7
flow-for-vscode|flo|0.7.3
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
css2react|got|0.0.6
CppSnippets|har|0.0.13
webpack|jer|2.0.2
sublime-babel-vscode|jos|0.2.9
docomment|k--|0.0.17
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
python|ms-|2018.1.0
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
node-debug2|ms-|1.19.0
PowerShell|ms-|1.5.1
team|ms-|1.122.0
debugger-for-chrome|msj|4.1.0
color-highlight|nau|2.3.0
seti-icons|qin|0.1.3
Csharp-ASPNETCore|rah|1.0.5
Ruby|reb|0.16.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
autoimport|ste|1.5.3
vscode-react-native|vsm|0.5.7
vscode-todo-highlight|way|0.5.11
bootstrap-3-snippets|wcw|0.1.0
vscode-import-cost|wix|2.6.2
JavaScriptSnippets|xab|1.5.0

(7 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by hsavit1** [comment]
Same for me

**Comment by danielvy** [comment]
Have a similar issue. Macbook Pro running MacOS 10.13.x , this started around VSCode 1.18 (not 100% sure exactly when but definitely 1.19 had this problem). 

After a some time running VSCode, Code Helper process is reaching ~100% CPU, closing VSCode doesn't terminate this process and reopening starts a new "Code Helper" process.

**Comment by shobhitchittora** [comment]
+1 on this. What does Code Helper actually does ?

**Comment by jrieken** [comment]
> +1 on this. Can someone explain what Code Helper does ?

@shobhitchittora Yes! Follow this guide, provide more information, and we be able to tell you what's going on: https://github.com/Microsoft/vscode/wiki/Performance-Issues
