### ISSUE TITLE
Clicking on explorer banner while context menu causes it to collapse

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode#43259]
- VSCode Version: 1.20.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. On a viewlet (in the explorer), open a context menu by right clicking an item on the explorer.
2. Click on anything on the banner and it will collapse rather than clicking the button.

![vscode_explorer_bug](https://user-images.githubusercontent.com/5290572/36002047-89b0f182-0cdd-11e8-91eb-3ce873fdd560.gif)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
