### ISSUE TITLE
Terminal going blank when pressing Control key

### ISSUE THREAD

**Issue by artin-phares** [Microsoft/vscode#43250]
### Issue Type
Bug

### Description

1. Run task that produces links in terminal (eg. typescript produces errors with file paths)
2. Try to follow any link with Control + click

Actual: Terminal is cleared out as soon as Control key is pressed, link is not opened
Expected: Terminal stays the same, link is opened  

Terminal allows to `Ctrl + click to follow link`.  
When running tasks it says `Terminal will be reused by tasks, press any key to close it`.  
But it should not be closed in case Control key is pressed (same as Alt, Shift, etc.)

![0f507f13c4d75e5e8cfdf11fd1838242](https://user-images.githubusercontent.com/671082/35997667-39de67d6-0d2b-11e8-885d-5923c97dbb9a.png)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3500)|
|Memory (System)|7.94GB (4.93GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
stylelint|shi|0.32.0

</details>
Reproduces without extensions

**Comment by BillDenton** [comment]
IMHO this is **major showstopper** issue, which makes the terminal unusable. I can't navigate easily to build errors.

**Comment by peterkohaut** [comment]
I tried insiders build and this issue was fixed. But only for CTRL key, when I try to use home/end/pgup/pgdown/arrows, terminal is closed. This is unusable, I'm going back to 1.19 till this issue is resolved.

**Comment by BillDenton** [comment]
Any update on this? This is a major on pain on every build, which is very often if you're using TDD.

**Comment by octref** [comment]
Being tracked in #42066 and it'll go to our recovery build.

**Comment by teki** [comment]
Workaround till it is fixed: press Command and hold in the editor view in focus (on macOS) and then hover the mouse on the issue in the terminal view.

**Comment by octref** [comment]
You can subscribe to #42066 for updates. Fix is already in recovery build.
