### ISSUE TITLE
⌘+K Does not clear terminal.

### ISSUE THREAD

**Issue by serkanyersen** [Microsoft/vscode#43264]
Keyboard shortcuts show <kbd>⌘</kbd> <kbd>K</kbd> as `Clear` when terminal is focused. However this does not work.

- VSCode Version: 1.20.0
- OS Version: osx sierra 10.12.6

Steps to Reproduce:

1. Open Terminal and focus
2. run any command `ls` for example
3. On your keyboard hit <kbd>⌘</kbd> <kbd>K</kbd>
4. Terminal is not cleared. VSCode expects key sequence.

Does this issue occur when all extensions are disabled?: Yes

Current solution I have is to re-bind it as <kbd>⌘</kbd> <kbd>K</kbd> + <kbd>⌘</kbd> <kbd>K</kbd> this could be the default.

**Comment by jbarson** [comment]
Works for me.  

- VSCode Version: 1.20.0
- OS Version: osx sierra 10.13.3

**Comment by octref** [comment]
Also @Tyriar for input. Seems Cmd+K is part of many shortcut chords. I always use just Ctrl+L which works for all terminal though.

**Comment by Tyriar** [comment]
This normally breaks for people who define ctrl+k chord keybindings or who have extensions that do so. You can get it back by redefining the cmd+k keybinding in your keybindings.json:

```js
{ "key": "cmd+k", "command": "workbench.action.terminal.clear", "when": "terminalFocus" }
```
