### ISSUE TITLE
Visual Studio Code doen't load zsh when debuging which was configed

### ISSUE THREAD

**Issue by flashlib** [Microsoft/vscode#43269]
My setting is as following:
```
    "terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.integrated.shellArgs.osx": [],
```

But the shell is using **sh** when debuging, I find by the following code:

    #include <stdlib.h>
    #include <stdio.h>

    int main(int argc, char **argv) {
        system("tom");
        return EXIT_SUCCESS;
    }

The output of Debug Console is:
```
@"sh: tom: command not found\r\n"
```

But in the embeded terminal, when I run ```tom```, the output is from **zsh**:
```
$ tom
zsh: command not found: tom
```

**Comment by flashlib** [comment]
I think I have found the reason, the CMake uses /bin/sh as its Shell, following is from my Makefile:
```
# The shell in which to execute make rules.
SHELL = /bin/sh
```

I tried to change it to /bin/zsh, but it didn't make sense.
Any suggestion would be appreciated!

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#1631
