### ISSUE TITLE
Cannot debug extension anymore (Electron window pops up instead)

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#43263]
- VSCode Version: master @ d2d18a47fd44fc (08/02/2018), via `scripts\code.bat`
- OS Version: Windows 10

Steps to Reproduce:

1. Open any extension repository folder
2. Press F5

Note that this didn't happen in the past, and also everything works fine using the latest insiders release. So this is specific to building and running vs code from scratch. To avoid any doubt, I cloned the vscode repo from scratch.

![screenshot](https://user-images.githubusercontent.com/530988/36002795-5ae1fea0-0d23-11e8-8e06-94b10ecc70f5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
If you run VS Code from source and want to debug an extension, you'll have to add the path of the VS Code project as the first argument to your launch configuration, e.g.:
```js
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                        "<absolute path to VS Code project>",
                        "--extensionDevelopmentPath=${workspaceRoot}"
            ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/out/**/*.js" ],
            "preLaunchTask": "npm: watch"
        },

```

**Comment by letmaik** [comment]
OK thanks, but don't you consider this a bug? Why would it not work directly?

**Comment by weinand** [comment]
@bpasero could you please answer?

**Comment by weinand** [comment]
I've created this [PR](https://github.com/Microsoft/vscode-node-debug2/pull/188).
