### ISSUE TITLE
PHP class name incorrectly highlighted unless it's on a new line

### ISSUE THREAD

**Issue by neerolyte** [Microsoft/vscode#43260]
- VSCode Version: 1.20.0
- OS Version: OS X 10.13.3

Steps to Reproduce:

1. Create file with `php` mode
2. paste code:

```php
class Foo {
}class Bar {}
```
3. Observe incorrect highlighting of `Bar` e.g:

![image](https://user-images.githubusercontent.com/1070702/36002623-ec6639c6-0d7e-11e8-80ab-6b33ffd0b5a5.png)

Does this issue occur when all extensions are disabled?: Yes

This is pretty minor.

**Comment by roblourens** [comment]
Fixed upstream
