### ISSUE TITLE
Can't run foreach and console.log on arrays in debug console

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#43267]
### Issue Type
Bug

### Description

I remember using this before and it used to work.

![image](https://user-images.githubusercontent.com/4033249/36005361-29d31420-0cec-11e8-9389-bc8b06cc9b39.png)

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (91120eb786357aa1e16217ad6a67cf0740f26e8e, 2018-02-08T06:09:08.922Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_827594|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.3.0
vscode-eslint|dba|1.4.5
tslint|eg2|1.0.24
prettier-vscode|esb|1.1.3
Go|luk|0.6.73
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
shader|sle|1.1.2
language-stylus|sys|1.8.0
vim|vsc|0.10.13

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by weinand** [comment]
@octref I tried this for legacy and inspector protocol and launch and attach mode but I cannot reproduce this.
Is this reproducible for you?
With what version of node are you running the serviceHost.ts?

**Comment by octref** [comment]
v8.9.1. I think I found the cause.

- Open up `/extensions/html`
- In `launch.json`, make the port 6045 https://github.com/Microsoft/vscode/blob/master/extensions/html/.vscode/launch.json#L32
- In `htmlServerMain.ts`, add two lines in here https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/htmlServerMain.ts#L177-L179

  ```ts
	documents.onDidChangeContent(change => {
		const arr = [1, 2, 3];
		triggerValidation(change.document);
		console.log(arr);
	});
  ```
- Run the html extension, open an html file, attach html server
- Put a breakpoint after that arr declaration

  ![image](https://user-images.githubusercontent.com/4033249/36041512-a0c9c948-0d7d-11e8-87a2-86eb19b1307b.png)

It's caused by these two lines

```ts
console.log = connection.console.log.bind(connection.console);
console.error = connection.console.error.bind(connection.console);
```

And the output went to the client extension's html output channel

![image](https://user-images.githubusercontent.com/4033249/36041679-2e81fc1a-0d7e-11e8-89dc-46e18fc9aa65.png)

I guess the current behavior is reasonable. Sorry for the bogus issue.

**Comment by weinand** [comment]
@octref np, thanks for your investigation!
