### ISSUE TITLE
`⌘K Enter` is documented as Tab 'Keep Open' on Mac, but doesn't work

### ISSUE THREAD

**Issue by craigkovatch** [Microsoft/vscode#43265]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.24
csharp|ms-|1.13.1

---

Steps to Reproduce:

1. Right-click a tab, observe that `⌘K Enter` is the keyboard shortcut for 'Keep Open'
![image](https://user-images.githubusercontent.com/10970257/36005244-933e2fb8-0ceb-11e8-97d1-817315c2badd.png)

2. Press ⌘K+Enter in the text editor, get this error message; 
![image](https://user-images.githubusercontent.com/10970257/36005210-69247624-0ceb-11e8-8acd-26b4407b9581.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Well it does not, the keybinding is `Cmd+K` followed by just `Enter`.
