### ISSUE TITLE
Imported React components dont show up in suggestions inside html elements

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#43266]
From https://github.com/Microsoft/vscode/issues/43239#issuecomment-364290699 by @LPsyCongroo

![git](https://user-images.githubusercontent.com/16440817/36004805-9e51edce-0d02-11e8-8ff1-d0a4e70017ec.gif)

- Works inside empty `return()`
- Doesnt work inside an html element inside the `return()`
- Works inside the html element inside the `return()` if already present outside the html element but inside the `return()`

**Comment by mjbvz** [comment]
@ramya-rao-a In the second case (inside the `div`) you are writing the body text of that element. We don't show suggestions there until you type `<` or `{` which signals that we are now starting an html element or js
