### ISSUE TITLE
Multi-cursor editing Alt+Click not working

### ISSUE THREAD

**Issue by SiqingYu** [Microsoft/vscode#43272]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.0-32-generic
- Extensions: Extensions are disabled
---

Alt+Click not working.
Other shortcuts such as Shift+Alt+ ↑ / ↓ (Insert cursor above/below) worked well.
I think this is because the shortcut is conflicted with Ubuntu Unity Dash shortcut `Alt`.
Any good way to resolve it?

**Comment by SiqingYu** [comment]
I noticed that there is a ps on [keyboard-shortcuts-linux.pdf](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf)

> The Alt+Click gesture may not work on some Linux distributions.
> You can change the modifier key for the Insert cursor command to
> Ctrl+Click with the “editor.multiCursorModifier” setting.

It solves the problem.

**Comment by octref** [comment]
Glad you found the solution!
