### ISSUE TITLE
Promote extension log API to stable

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#43275]
https://github.com/Microsoft/vscode/blob/f15c6481fb4637f767532757ef545a8c2460ce1a/src/vs/vscode.proposed.d.ts#L401

**Comment by roblourens** [comment]
Earlier discussion at https://github.com/Microsoft/vscode/commit/98c58dfe9a793c0ac9084b3beb83692bfd25c582

**Comment by ramya-rao-a** [comment]
@roblourens Moving to March since you are not here ...

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/pull/43276#issuecomment-373446670

**Comment by jrieken** [comment]
I have added `ExtensionContext#logPath`. This will replace the proposed `logDirectory`-property which is currently used by node.debug and node.debug2. The old property is still around but will generate warning. @roblourens @weinand please adopt

**Comment by weinand** [comment]
I've update node-debug to use `ExtensionContext.logPath` instead of `ExtensionContext.logDirectory`.

**Comment by weinand** [comment]
@jrieken Is there already an API proposal for the "logging-related methods on the output channel api"?

**Comment by jrieken** [comment]
You can use the simple `appendLine` - we didn't plan for that change because we didn't know anyone uses it. An idea might be to accept a log level when calling `appendLine` but nothing has been discussed yet

**Comment by jrieken** [comment]
We have pushed `ExtensionContext#logPath`

**Comment by jrieken** [comment]
*Verify* that there is `ExtensionContext#logPath`, that it is documented, and that it is unique per extension.

**Comment by DanTup** [comment]
Am I right in thinking the path is the only thing being provided here, no logging API?

The path seems to have a long random folder name in it - restarting didn't seem to generate a new one - do these ever change? Do the logs ever get cleaned up?
