### ISSUE TITLE
problemMatcher: location always shows (line,col) format

### ISSUE THREAD

**Issue by ozyx** [Microsoft/vscode#43277]
- VSCode Version:
    - Version 1.20.0
    - Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
    - Date 2018-02-07T17:10:31.920Z
    - Shell 1.7.9
    - Renderer 58.0.3029.110
    - Node 7.9.0
    - Architecture ia32
    - OS Version:

Using a custom problemMatcher, in the "Problems" window, location is always shown as (line,col) format, even when the location match group only contains a single number.

I'm currently building MASM assembly code in VSCode and decided to create a custom problemMatcher to match the error output of `ml.exe`. Some example errors are formatted as such:

```
AW4.asm(25) : error A2008: syntax error : someVariable
AW4.asm(24) : error A2071: initializer magnitude too large for specified size
AW4.asm(24) : error A2206: missing operator in expression
```

My problemMatcher is as follows:
```json
"problemMatcher": {
                "owner": "masm",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                    "regexp": "^(.*)\\((\\d+)\\)\\s+:?\\s+(error|warning)\\s+([A-z]+\\d+):\\s+(.*)$",
                    "file": 1,
                    "location": 2,
                    "severity": 3,
                    "code": 4,
                    "message": 5,
                    "loop": true
                }
            }
```

Notice the 2nd match group is a number matching the line of code where the error occurred. There is no comma, so the format used by `location` should be `(line)`. However, it still defaults to `(line,column)` format (and arbitrarily chooses 5 as a column) as seen here:

![image](https://user-images.githubusercontent.com/9259993/36007777-add9dea0-0cf8-11e8-9086-860b834b6c27.png)

If I hover over `location`, the description reads: 
```"The match group index of the problem's location. Valid location patterns are: (line), (line,column) and (startLine,startColumn,endLine,endColumn). If omitted (line,column) is assumed."```

Does this issue occur when all extensions are disabled?: Yes

I've attached my `tasks.json`.
Please let me know if you need any more info, or if I'm just doing something wrong...

P.S.: I'm really loving VSCode and I use it every day, so thanks for all your hard work.

[tasks.json.txt](https://github.com/Microsoft/vscode/files/1709470/tasks.json.txt)

**Comment by dbaeumer** [comment]
@ozyx can you let me know how the lines look like that have and error. If not column is specified we try to use the first non space character as the column. Your matcher is correct in that sense.
