### ISSUE TITLE
One scanner flags installer with malware on VirusTotal.com

### ISSUE THREAD

**Issue by JVimes** [Microsoft/vscode#4328]
Gotta be a false-positive, but wanted to make devs aware. Scan results: [release](https://www.virustotal.com/en/file/43f310e049d33b4707b55270e8f935c09203d6fdcaa8ea4e2b5145f899a2d443/analysis/), [insiders](https://www.virustotal.com/en/file/aaad3c7e4e14d7b39ae5d032d82e9010e82b56da446f4b79932a96660ce5e748/analysis/)

- VSCode Version: 0.10.10, 0.10.10-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Download the installer from the official site.
2. Scan it on VirusTotal.com

**Comment by joaomoreno** [comment]
cc @chrisdias

**Comment by joaomoreno** [comment]
Thanks for this @JVimes. We also think this can be a false positive, so I'm closing the issue.

We are going to send our bits around to a virus check team in Microsoft for further inspection, nevertheless.
