### ISSUE TITLE
Add types and import windows-process-tree properly (via import)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#43287]
![image](https://user-images.githubusercontent.com/900690/36014792-e39aa326-0d6b-11e8-86eb-7cbfc56ad2b9.png)

**Comment by Tyriar** [comment]
@bpasero I copied what's done with windows-foreground-love as the module is windows only, is there a better way of doing this when the module doesn't get downloaded for non-Windows?

**Comment by bpasero** [comment]
@Tyriar true, we have more places where we follow this ugly pattern. 

I was referring to this pattern ([code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L649)):

![image](https://user-images.githubusercontent.com/900690/36041453-dc787912-0dc8-11e8-9c5c-ee400fd7f528.png)

**Comment by Tyriar** [comment]
Sure I can try using a dynamic import like how vscode-xterm is being loaded, should work fine 👍
