### ISSUE TITLE
Allow customization of search match text color

### ISSUE THREAD

**Issue by brunobely** [microsoft/vscode#43283]
I couldn't find this by searching, but it would be very good for readability if we could add the option to change the foreground color for find matches (`editor.findMatchForeground`?). Otherwise, we have to pick a background color that won't clash with any possible color in our theme, which is not an easy feat.

Example of how it works now in VS Code:
![image](https://user-images.githubusercontent.com/4048689/36012056-3802e7ac-0d21-11e8-8a54-49155d6a1f71.png)

Example of how it works in Sublime:
![image](https://user-images.githubusercontent.com/4048689/36012070-42bbb016-0d21-11e8-8fff-e8030a66ddcf.png)

**Comment by matthiasdailey-ccri** [comment]
See https://github.com/Microsoft/vscode/issues/29091
