### ISSUE TITLE
File events are not working

### ISSUE THREAD

**Issue by hrasadi** [Microsoft/vscode#43285]
- VSCode Version: 1.20.0
- OS Version: macOS 10.13.3 

Steps to Reproduce:

1. Make a change in a file in the repo and save.
2. Check the 'Changes' pane of the Source Control, the changes are not listed
3. Hit the Synchronize Changes for the repo
4. Changes would appear 

This started to manifest itself after updating to January 2018 release.

**Comment by cwal** [comment]
I am seeing the same behaviour.

**Comment by joaomoreno** [comment]
It seems that file events aren't working.

What is your workspace configuration? You just opened a folder with Code?

If you make file system changes outside of Code (eg delete a file), does Code's explorer update its state accordingly?

**Comment by hrasadi** [comment]
Thank for the reply. 

1- No! I have created and saved a Code workspace and have multiple folders in it.
2- No! Code does not realize filesystem changes made outside of its environment unless I manually refresh the workspace (from 'Explorer' pane)

**Comment by hrasadi** [comment]
Update:
I rebooted my computer and the the problem was fixed. I cannot confirm whether or not it was the system reboot or Code being restarted that fixed the problem, but I can confirm that the fix came before updating to the latest release (1.20.1).
