### ISSUE TITLE
checkout branchs results in some files disappearred

### ISSUE THREAD

**Issue by mhy-web** [Microsoft/vscode#43286]
- VSCode Version: 1.20.0 (1.20.0)
- OS Version: 10.13.3
- Git Version: 2.14.1
Steps to Reproduce:

1. In any branch of a repository, Create a folder A and a file a.js in A and just in current branch.
2. Checkout another branch and do something 
3. Checkout branch in step 1, you might find the folder A and file a.js are disappearred

This bug has appearred many times in  recent months, but when I try to reproduce it , I have failed.
In step 2, maybe compiling，coding,  push code to remote repository and other thing result in this bug, I don't know, I need to restart my vscode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you reproduce this bug outside of VS Code? Just using Git, for example?
