### ISSUE TITLE
Global Search is only returning results from opened files

### ISSUE THREAD

**Issue by bluefunc90** [Microsoft/vscode#43288]
### Issue Type
Bug

### Description

1. open new folder
2. search for a keyword
3. no result
4. open a file(including the keyword above) from the folder
5. search for the keyword again
6. result only from opened files

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|Memory (System)|7.92GB (2.21GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
gitlens|eam|8.0.0
team|ms-|1.122.0
vscode-boot-dev-pack|Piv|0.0.2
vscode-boot-java|Piv|0.1.3
vscode-boot-properties|Piv|0.1.3
vscode-concourse|Piv|0.1.3
vscode-manifest-yaml|Piv|0.1.3
java|red|0.18.1
angular-follow-selector|san|1.1.1
vscode-angular-support|vis|0.1.4
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.2.0

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
@bluefunc90 I'm not sure how this was off my radar for so long. I think the issue has some missing history. Is this still a problem on the latest version?

**Comment by bluefunc90** [comment]
@roblourens Thanks for the response and you don't have to worry about the delay. The delay was because there were some problems on my github account.. And you don't have to worry about this issue too, because the problem's gone on the latest version. Thank you very much.
