### ISSUE TITLE
Make "editor.scrollBeyondLastLine" configurable beyond true or false

### ISSUE THREAD

**Issue by bschlenk** [microsoft/vscode#43294]
I'm the kind of person who always presses enter 5 times after running a shell command. I like having some space. But too much space leaves me feeling vulnerable, as if I was stranded in the middle of the ocean. This all or nothing approach with the "editor.scrollBeyondLastLine" option isn't working for me.

Can this option be configurable by the line number? If I want to be able to scroll past the bottom by 5 lines, I should be able to set the value to 5. If I want to have the current behavior, I could set the value to true, or "all".

**Comment by msikma** [comment]
Would like to second this. It was one of the things I liked about Webstorm—it would scroll down about 10 or so lines past the bottom, but no further. So I didn't have to look "all the way down" (I know, it sounds silly, but it still felt nice), and I never scrolled so far I ended up with just one line.

**Comment by alexandrudima** [comment]
Duplicate of #7517
