### ISSUE TITLE
Typescript 2.7 "definite assignment assertion" error

### ISSUE THREAD

**Issue by simll** [Microsoft/vscode#43296]
### Issue Type
Bug

### Description

I got error when I use Typescript Decorators and ["definite assignment assertion"](https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#stricter-class-property-checks):
![image](https://user-images.githubusercontent.com/4560658/36018922-712e0524-0db8-11e8-96e4-57049178b01d.png)
(Attachment: [test project](https://github.com/simll/report), error file path: `src/components/HelloWorld.vue`)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz (8 x 3293)|
|Memory (System)|11.96GB (5.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
tslint|eg2|1.0.24
vetur|oct|0.11.7

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
Seems like an issue with vetur. I can't repo in a normal TS file using TS 2.7

Please file this issue against Vetur

**Comment by simll** [comment]
You are right. I find an issue like this, https://github.com/vuejs/vetur/issues/682.
Thanks for you help.
