### ISSUE TITLE
Be able to colour tabs in a multi-root project

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#43292]
It would be nice to be able to have different file tabs be the colour of the project they're in, when using a multi-root workspace.

Projects can already have a different toolbar colour, tabs should inherit those colours.

**Comment by jpike88** [comment]
@bpasero would be nice for you to link the duplicate issue, I searched before I added this one and would like to subscribe to it.

**Comment by bpasero** [comment]
Yeah I would say a variant of https://github.com/Microsoft/vscode/issues/35379 maybe add your comment there.

**Comment by bpasero** [comment]
Actually I meant to say: https://github.com/Microsoft/vscode/issues/31308
