### ISSUE TITLE
In the editor keyboard keys failure

### ISSUE THREAD

**Issue by LiuCaiHe** [Microsoft/vscode#43290]
### Issue Type
Performance Issue

### Description

In the editor letters, numbers, symbol keyboard all invalid
Restart the editor for some time as well
Repeated so ...

Submit bug with editor, Make my GitHub account

> Your account has been flagged.
> Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

|pid|CPU|Memory (MB)|Name|
|---|---|---|---|
|9720|27|131|code main|
|9721|9|49|-- gpu-process|
|9723|38|360|-- window (manage.vue — czb-fleet)|
|9806|98|115|---- extensionHost|
|9898|0|66|------ electron_node server.js |
|9902|0|115|------ electron_node vueServerMain.js |
|9933|0|115|------ electron_node server.js |
|9949|0|33|------ electron_node server.js |
|9807|0|49|---- watcherService|
|9809|0|33|---- terminal|
|9810|0|0|------ /bin/zsh -l|
|10088|0|16|-------- node /usr/local/bin/yarn run dev|
|10090|0|262|---------- node /Users/liucaihe/WebServer/youfenqi/czb-fleet/node_modules/.bin/webpack-dev-server --inline --progress --config build/webpack.dev.conf.js|
|10091|0|16|------------ open -W http://localhost:8081/|
|9907|0|49|---- searchService|
|9724|1|98|-- shared-process|
|10291|86|82|-- shared-process|
|10293|0|0|-- /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=|

</details><details>
<summary>Workspace Info</summary>

```
|  Window (manage.vue — czb-fleet)
|    Folder (czb-fleet): 91 files
|      File types: js(40) vue(14) gz(7) DS_Store(6) svg(3) json(2) png(2)
|                  html(2) css(2) ttf(2)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
beautify|Hoo|1.3.0
crane|Hvy|0.3.8
output-colorizer|IBM|0.1.2
TurboJavaScript|Ice|0.1.2
format-indent|Kas|1.3.0
vscode-docker|Pet|0.0.24
jsx|Twe|0.0.1
html-snippets|abu|0.2.1
vscode-database|baj|1.3.0
stylus|buz|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.5
vscode-dash|dee|1.8.0
wpy-beautify|doi|2.0.10
githistory|don|0.4.0
Vue2|duc|0.1.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.0.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.12.1
auto-rename-tag|for|0.0.15
code-runner|for|0.8.7
mdmath|goe|2.1.0
vscode-nginx-conf-hint|han|0.0.4
vscode-emacs|hir|0.1.1
docthis|joe|0.6.0
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
codeacejumper|luc|1.1.5
prettify-json|moh|0.0.3
mssql|ms-|1.3.0
python|ms-|2018.1.0
azure-account|ms-|0.3.0
vetur|oct|0.11.7
vuehelper|oys|0.1.0
vscode-css-peek|pra|2.1.0
vscode-wechat|qin|0.0.6
grammarkdown-language|rbu|0.4.3
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
vue|sea|0.4.2
keyboard-scroll|sel|0.1.0
vscode-nginx|sha|0.5.0
addDocComments|ste|0.0.8
language-stylus|sys|1.8.0
vscode-babel-repl|t-s|0.1.2
vscode-gulp|tan|0.0.4
python|tht|0.2.3
es-quotes|vil|0.2.6
gitblame|wad|2.2.0
JavaScriptSnippets|xab|1.5.0

(4 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by MaleDong** [comment]
Change the discription into English so as to make more people understand what you say:)
Notice this:

![default](https://user-images.githubusercontent.com/6959154/36021326-68dd0002-0dc0-11e8-9253-d53fbf2ebb8b.PNG)

**Comment by egamma** [comment]
@MaleDong thank you for your help, but it is still not clear to me what the issue is. What does the screenshot have to do with the issue title ´In the editor keyboard keys failure´
