### ISSUE TITLE
JSON schema support for .jshintrc and .jscsrc

### ISSUE THREAD

**Issue by scottaddie** [Microsoft/vscode#433]
Prior to the 0.10.1 release, the following	settings were baked into the editor:

```json
        // Control whether jshint is enabled for JavaScript files or not.
	"jshint.enable": true,

	// The jshint options object to provide args to the jshint command.
	"jshint.options": {},
```

Now that there's an official [JSHint extension](https://marketplace.visualstudio.com/items/dbaeumer.jshint), the following schema support should be added by it rather than including it into the editor:

```json
		{
			"fileMatch": [
				"/.jshintrc"
			],
			"url": "http://json.schemastore.org/jshintrc"
		},
```

I'd argue the same point regarding the [JSCS extension](https://marketplace.visualstudio.com/items/ms-vscode.jscs). It should add the following to the settings, rather than baking it into the editor:

```json
		{
			"fileMatch": [
				"/.jscsrc"
			],
			"url": "http://json.schemastore.org/jscsrc"
		}
```

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-jshint#4
