### ISSUE TITLE
Starting VSCode with multiple windows opened

### ISSUE THREAD

**Issue by sstaub** [Microsoft/vscode#43304]
### Issue Type
Bug

### Description

When I have opened more than one window, after the next start of the VSCode app only the last selected window will opens, instead of all used windows.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (d28f096018e2673a8437c788e3eed781ddb505ce, 2018-02-09T06:08:42.088Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.50GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
file-templates|brp|1.2.0
doxdocgen|csc|0.0.7
gitlens|eam|8.0.0
CppSnippets|har|0.0.13
cortex-debug|mar|0.1.13
vscode-todo-parser|min|1.9.1
cpptools|ms-|0.14.6
vscode-code-outline|pat|0.0.12
platformio-ide|pla|0.12.1
vscode-icons|rob|7.19.0
vscode-todo-highlight|way|0.5.11
debug|web|0.21.2

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
`"window.restoreWindows": "all"`

**Comment by sstaub** [comment]
Thank you, maybe it should a standard behavior.
