### ISSUE TITLE
Opening .bat file in VSCode via context menu in windows explorer tries to execute it

### ISSUE THREAD

**Issue by TobiSchluter** [microsoft/vscode#43302]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
SystemVerilog|msh|0.0.17
cmake|twx|0.0.17
cmake-tools|vec|0.10.4

---

Steps to Reproduce:

1. right-click on .bat file in explorer (unpacked from downloaded .zip file)
2. select "Open with code"
3. get "Windows protected your PC" screen ("prevented an unrecognized app from starting")

So it seems that VSCode or the Explorer wants to run the .bat file instead of opening it for editing.  That's definitely not the behavior I expect when I want to inspect a batch file before executing it. (Opening the file via the File -> Open dialog in VSCode works fine. My system's security wasn't compromised because the .bat file was from a trusted source, but it sure looks like a security issue.)

**Comment by the-ress** [comment]
I don't think it's a bug. It's just what SmartScreen does. It's being extra cautious and runs the check before any action - including the built-in Edit command. Then it starts the editor (even though the SmartScreen wording might suggest it runs the script).

![b9019d36-b68f-447c-a109-1bfe64328c84](https://user-images.githubusercontent.com/1612377/81509425-de7e5a00-930a-11ea-8863-6e78e279283c.gif)

**Comment by TobiSchluter** [comment]
Interesting didn't notice that, probably i just used less on a command line to view the batch file.

So it's a UI bug ("issue") in Windows. It's  kind of self-defeating if SmartScreen makes you believe that you're about to execute a file when you're trying to look at it in order to decide whether to execute it.

I'm leaving this open, as there may be a way to register "Open with Code" with the Explorer that doesn't trigger this warning, but please feel free to close if you consider it outside VS Code's scope.
