### ISSUE TITLE
Terminal text corrupts when moved to non-retina screen after sleep

### ISSUE THREAD

**Issue by Lexicality** [Microsoft/vscode#43309]
Corrupted terminal:
![screen shot 2018-02-09 at 11 16 39](https://user-images.githubusercontent.com/847422/36025599-86ae64f2-0d8b-11e8-958e-516bf2397c54.png)
Same terminal after moving window to retina and back:
![screen shot 2018-02-09 at 11 26 37](https://user-images.githubusercontent.com/847422/36025766-22952f0e-0d8c-11e8-8ba3-f3f5e820af0d.png)

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-jest|Ort|2.6.0
vscode-docker|Pet|0.0.24
vscode-eslint|dba|1.4.5
githistory|don|0.4.0
gitlens|eam|8.0.0
Go|luk|0.6.73
terraform|mau|0.0.20
python|ms-|2018.1.0
Align|ste|0.2.0
vim|vsc|0.10.13
jinja|who|0.0.8
vscode-proto3|zxh|0.1.2

---

Steps to Reproduce:

1. Plug a non-retina (but higher "resolution") screen into a retina macbook pro
2. Move VSCode to external monitor in full screen display
3. Unplug external monitor
4. Open integrated terminal in vscode
5. Run `ipython`
6. Hide integrated terminal
7. Put laptop to sleep by closing the lid
8. Plug laptop back in to external monitor
9. Open laptop and log in
10. VSCode does a layout dance for a few seconds on the non-retina monitor
11. Open integrated terminal
12. ![screen shot 2018-02-09 at 11 34 24](https://user-images.githubusercontent.com/847422/36026028-3720c144-0d8d-11e8-9de6-1d070ac663fa.png)

The terminal behaves like normal and will return to normal text if the main vscode window is resized

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This should be fixed when you update to 1.20

**Comment by Lexicality** [comment]
Ah, sorry. I did search before making this but I must have left `is:open` in the searchbox. 😞

**Comment by Tyriar** [comment]
No worries 😃
