### ISSUE TITLE
Syntax highlighting in debug console

### ISSUE THREAD

**Issue by ETLaurent** [microsoft/vscode#43310]
Hi, it would be nice to have the syntax highlighting on what is typed in debug console, like in Chrome.
That would be very confortable, for those who use the debug console a lot.

Thanks

VSCode:
![image](https://user-images.githubusercontent.com/8301962/36025876-fdc11e5a-0d94-11e8-850e-a21cf3f4b8f9.png)

Chrome:
![image](https://user-images.githubusercontent.com/8301962/36025904-0ebfd6ba-0d95-11e8-84db-3b6f5830ccdb.png)

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
EditorConfig|Edi|0.12.0
quokka-vscode|Wal|1.0.98
vscode-standardjs-snippets|cap|0.7.5
vscode-standardjs|che|1.2.1
vscode-eslint|dba|1.4.5
gitlens|eam|8.0.0
vscode-npm-script|eg2|0.3.3
file-icons|fil|1.0.7
auto-close-tag|for|0.5.5
vue|jcb|0.1.5
graphql-for-vscode|kum|1.8.3
vetur|oct|0.11.7
apostrophecms-vs-snippets|pun|1.9.2
sass-indented|rob|1.4.6
nunjucks|ron|0.2.3
vscode-todo-highlight|way|0.5.11

**Comment by arnavb** [comment]
Has there been any update on this? It makes code hard to read somewhat in the current state.

**Comment by iansan5653** [comment]
#71458 adds significantly more options for colors in this console, so this might be something that is possible now.

**Comment by isidorn** [comment]
@iansan5653 those two are unrealted. For this feature request the debug console would have to have an AST language understanding

**Comment by iansan5653** [comment]
I understand, I just meant from a rendering perspective, that's one way it could be done. I guess it's probably not the best way anyway.

**Comment by weinand** [comment]
@isidorn AST language understanding is not necessary for this feature (syntax highlighting in editors isn't based on AST either).

What we would need is:
- a mechanism that identifies the language of text sent to the debug console and 
- the syntax highlighting engine from the VS Code text editor working against the debug console's text model.

For the first we could add a "language" attribute to the output events.
@isidorn how feasible is the latter item?

**Comment by isidorn** [comment]
Debug console does not have a text model since it is not an editor, but a tree.
The debug console text input field has a text model and for that it would be feasable. However I do not think it makes that much sense to only do it for the input and not for the actual content.

**Comment by isidorn** [comment]
The Debug Console input now uses the language mode of the current active editor. This means that the Debug Console input now supports syntax coloring, indentation, auto closing of quotes, and other language features. More about this can be found here https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_42.md#debug-console-improvements

We still do not support syntax highlighting in the Debug Console Tree (the rest of the debug console that is not the input). That would require more work since our syntax coloristaion is not built to work with the Tree but the Editor. Thus leaving this feature request open.

**Comment by arnavb** [comment]
That's great news @isidorn! Congrats to the VSCode team!

**Comment by ETLaurent** [comment]
![image](https://user-images.githubusercontent.com/8301962/84383645-f2a8c600-abec-11ea-9ced-ab771cc419c8.png)

Nice 👌 
I guess we can close this issue.

Thank you!

**Comment by isidorn** [comment]
We still do not support syntaxHyghlighting in the debug console output. Thus I would prefer to leave this issue open.

**Comment by ItsCubeTime** [comment]
I would love to see support for this in the output "tree" as well

**Comment by znorman-harris** [comment]
I agree that having syntax highlighting in the output tree would be fantastic. For example: in Eclipse the debug/input terminal retains all syntax highlighting for user-specified commands which is really easy to interpret. Here's a screenshot showing previous commands retaining their syntax highlighting:

![image](https://user-images.githubusercontent.com/31664668/167911494-3392032e-487c-4486-89fa-d0d9e5ad354c.png)

**Comment by silicogen** [comment]
Syntax highlighting in the debug console is what I’d very like to use. I need it.
