### ISSUE TITLE
ecmascript: esnext numeric separator hightlight

### ISSUE THREAD

**Issue by yukulele** [Microsoft/vscode#43316]
js/ts number with [numeric separators](https://github.com/tc39/proposal-numeric-separator) are not correctly highlighted

- VSCode Version: 1.20
- OS Version: macOS High Sierra

Steps to Reproduce:

1. use number with numeric separators (example: `60_000`)

Does this issue occur when all extensions are disabled?: yes

![screenshot](https://user-images.githubusercontent.com/347244/36030652-654bc170-0da8-11e8-8544-46e381e84f90.png)

**Comment by mjbvz** [comment]
Fixed by 3e9d16948c18af03e2b8211fca570c7e91cb1514
