### ISSUE TITLE
Character '_' (underline) not is visible in the terminal.

### ISSUE THREAD

**Issue by fabiuz** [Microsoft/vscode#43314]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.12.8-200.fc25.x86_64
- Interface: Gnome 3
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
crane|Hvy|0.3.8
format-indent|Kas|1.3.0
csharpfixformat|Leo|0.0.61
nativescript|Tel|0.7.2
Angular2|UVB|0.4.1
omnipascal|Wos|0.15.0
pascal|ale|0.10.0
vscode-great-icons|emm|2.1.24
php-debug|fel|1.12.1
php-intellisense|fel|2.2.7
php-pack|fel|1.0.1
code-runner|for|0.8.7
reasonml|fre|1.0.23
peachpie-vscode|iol|0.9.5
easy-icons|jam|0.3.1
react-component|jer|1.0.1
Angular2|joh|2.12.0
vscode-csharp-snippets|jor|0.2.0
vscodeilviewer|jos|0.0.1
php-symbols|lin|2.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2018.1.0
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
node-debug2|ms-|1.20.0
debugger-for-chrome|msj|4.1.0
vscode-code-outline|pat|0.0.12
tns-cli|pko|0.0.3
autoimport|ste|1.5.3
vala|thi|0.3.1
nativescript-xml-snippets|tsv|1.0.6
vscode-react-native|vsm|0.5.7

(11 theme extensions excluded)

---

Steps to Reproduce:

1. Open terminal in the Visual Studio Code.
2. Enter the caractere _ .
3. The caractere _ not is displayed but others characters other than _ are displayed normally.

Reproduces without extensions: Yes/No

**Comment by jens1o** [comment]
cc @Tyriar 

The bot detected the wrong asignee :D

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901

**Comment by fabiuz** [comment]
In the Visual Code Settings is:
"terminal.integrated.fontFamily" : ""
"terminal.integrated.fontSize" : "14"

// Controls the font family.
  "editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",

  // Controls the font size in pixels.
  "editor.fontSize": 14,

If I use the default settings, the character _ is not displayed.
But, If I change the value of "terminal.integrated.fontSize" for a value diferent of 14, the character is displayed.

And, I noticed, other detail, if I not change "terminal.integrated.fontSize" but 
"terminal.integrated.fontFamily" for other font, independently of value in "terminal.integrated.fontSize", is charactere _ is displayed.
