### ISSUE TITLE
Create file/folder is missing from command pallete

### ISSUE THREAD

**Issue by Hurtak** [Microsoft/vscode#43320]
- VSCode Version: 1.20
- OS Version: MacOS

Steps to Reproduce:

1. Focus file explorer
2. Select some folder with keyboard
3. Open command pallette
4. search for create file/folder command - these commands are now missing, were present in previous versions

Does this issue occur when all extensions are disabled?: Yes
It also occurs when I disable all user settings.

**Comment by isidorn** [comment]
@Hurtak yes they are no longer in the command palette, but you can still assign keybindings to them 
`explorer.newFile` is the command id.
We felt like they are explorer specifc and do not really belong to the command palette.

Closing as designed for now.

**Comment by Hurtak** [comment]
Is there any other way to create folder only with keyboard without creating and remembering keybinding?

If not, this seems like bad decision for users that prefer to use only keyboard because apparently since 1.20 I need to:
- create keybindings for all sorts actions (create folder, create file ...)
- remember these keybindings

Before this change I just searched for less common actions, that we not worthy of its own keybinding, in command palette.

How about showing these explorer specific commands only when explorer is focused?

**Comment by isidorn** [comment]
@Hurtak you are correct. More users have complained and we will fix this.
More details can be found here https://github.com/Microsoft/vscode/issues/43363
