### ISSUE TITLE
Error: Extension host terminated unexpectedl

### ISSUE THREAD

**Issue by Hurdock** [Microsoft/vscode#43323]
- VSCode Version: 1.20
- OS Version: Windows 10

Steps to Reproduce:

1. If you install php Intellisense as an Extension.

Does this issue occur when all extensions are disabled?: Yes/No 

That's all. It seems when you install the 'php extension' suggested by Visual Code, you're going to get that error.

**Comment by roblourens** [comment]
Does it still happen if you set `"php.validate.enable": true`?

**Comment by Hurdock** [comment]
Yes. 

![yas](https://user-images.githubusercontent.com/15019878/36250669-2e8fdd8a-1247-11e8-93b5-0d9a41cc8f52.PNG)

**Comment by roblourens** [comment]
Sorry, I meant `false` to check whether this is related to the builtin PHP support.

**Comment by Hurdock** [comment]
Thanks, it worked.

2018-02-15 18:16 GMT+02:00 Rob Lourens <notifications@github.com>:

**Comment by roblourens** [comment]
Ok. Can you run the `Set Log Level` command, set it to Trace, and check for any errors in the Extension Host or Window logs?

![image](https://user-images.githubusercontent.com/323878/36363779-1ae53868-1583-11e8-9eca-a23e2df460df.png)
