### ISSUE TITLE
I can't remove the class's underline(Monokai Theme)

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#43328]
### Issue Type
Bug

### Description

My settings are:
```json
{
    "workbench.colorTheme": "Monokai",
    "editor.tokenColorCustomizations": {
        "comments": {
            "fontStyle": ""
        },
        "[Monokai]": {
            "textMateRules": [
                {
                    "name": "Class name",
                    "scope": "entity.name.class",
                    "settings": {
                        "fontStyle": ""
                    }
                }
            ]
        }
    }
}
```
However, class is still underlined.
![user](https://user-images.githubusercontent.com/24318019/36034335-c2ce0c7c-0dee-11e8-85a9-891bf1f1ef44.png)
![test](https://user-images.githubusercontent.com/24318019/36034348-cc942584-0dee-11e8-8fb6-2a18729cebe0.png)

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (d28f096018e2673a8437c788e3eed781ddb505ce, 2018-02-09T05:14:50.066Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|7.89GB (2.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by usernamehw** [comment]
https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_textmate-theme-rules

**Comment by shizengzhou** [comment]
@usernamehw Thank you.
