### ISSUE TITLE
`WorkspaceConfiguration.update(…)` should not trigger a `onDidChangeConfiguration` event

### ISSUE THREAD

**Issue by Tom-Bonnike** [Microsoft/vscode#43327]
Alternatively, there should be a way to check if the `onDidChangeConfiguration` event was triggered by the user or programmatically.
Right now, we need to use a flag to ignore the event, which is not ideal.

Happy to help implementing it if you like the suggestion.

**Comment by sandy081** [comment]
@Tom-Bonnike What is the usecase behind it?

**Comment by Tom-Bonnike** [comment]
Sorry, should have explained that in my initial message. I’ve recently been working on a status bar formatting toggle extension (https://marketplace.visualstudio.com/items?itemName=tombonnike.vscode-status-bar-format-toggle). Basically everytime you click the status bar, it enables/disables the formatting programmatically using `workspace.getConfiguration(…).update(…)`.

I’m also listening to the `onDidChangeConfiguration` event so that I can update the status bar text (and the toggle status) if the user **manually changes** their configuration.

The issue is that everytime I programmatically change the configuration (actually, I do that three times for the three different formatting settings), it triggers a `onDidChangeConfiguration` event, leading to the status bar text to “flash” multiple times.
It’s obviously not a big issue, but I’d argue that programmatically updating the configuration **should not** trigger a `onDidChangeConfiguration` event.

**Comment by sandy081** [comment]
I don't think I agree that event should not be triggered when configuration is updated programatically. If an event is not tirggered when an extension changes a configuration, how will other extensions get to know if there is a change in configuration or not?

I think, for your issue, you have to check if there is a change in the configuration value that you are looking for and react only when there is a change. You can get to know if the expected configuration value changed or not, you can do following:

`ConfigurationChangeEvent.affectsConfiguration(<setting>)`

**Comment by Tom-Bonnike** [comment]
> how will other extensions get to know if there is a change in configuration or not?

Oh, that’s a good point.
I’m already using `affectsConfiguration`. But that’s the issue, I’m listening to the same changes as what I’m updating programmatically.

For example:
```js
// Somewhere in the code:
workspace.getConfiguration('editor').update('formatOnPaste', true)

// Elsewhere in the code
workspace.onDidChangeConfiguration(event => {
  if (event.affectsConfiguration('editor.formatOnPaste')) {
    // This will always trigger, I have no way to know if it’s because of my own update or because of the user’s.
  }
})
```

Right now, I have to store a `SHOULD_IGNORE_NEXT_CONFIGURATION_CHANGES` flag in the `extensionState`, which isn’t ideal 😄

**Comment by sandy081** [comment]
Ok, it seems you already have state for formatOnPaste. I think this can be fixed programmatically by always getting the value from the configuration.
