### ISSUE TITLE
Make debugger tooltip customisable

### ISSUE THREAD

**Issue by Deilan** [microsoft/vscode#43326]
### Issue Type
Feature Request

### Description
Make debugger tooltip (which appears on hover over variables): 
- able to be pinned
- able to be floating
- resizable

**Comment by Deilan** [comment]
@isidorn @weinand Also take a look at #43325 because it may be also included as a part of the current issue.

**Comment by isidorn** [comment]
@Deilan thanks for creating seperate issues (which is the correct thing to do). However let's keep this in one issue and see if it attracts traction of users.

**Comment by weinand** [comment]
no traction -> no plans to work on this.

**Comment by Deilan** [comment]
I know this one is not very popular. But I think it's important it terms of debugging user experience.

**Comment by Trass3r** [comment]
Other missing features from VS are adding/removing/editing the expressions in the DataTip:

https://docs.microsoft.com/en-us/visualstudio/debugger/view-data-values-in-data-tips-in-the-code-editor

**Comment by cateyes99** [comment]
I'd say the `resizable` feature is the most important in terms of debugging UX, even compared to the other 2.

**Comment by isidorn** [comment]
I agree that making the debug hover resizable would be great, for that assigning this to September just to investigate what is needed to be done here.

**Comment by isidorn** [comment]
Actually decided to go down this path https://github.com/microsoft/vscode/issues/106865
So please try it out with VS Code insiders and provide feedback.
For now we will not make resizing the deubg hover a manual process since imho that would not be a nice experience, ideally this automatic resizing which we do know should improve the expreience.

**Comment by isidorn** [comment]
Since we did improvement in #106865 there are no more plans for change here.
