### ISSUE TITLE
Terminal issue on latest version

### ISSUE THREAD

**Issue by CFuchs174** [Microsoft/vscode#43322]
- VSCode Version: 1.20.0
- OS Version: Windows 10 Pro x64 with Fall Creators Update

The terminal behaves different to a "normal" PowerShell Console. A concrete issue can be seen when using the latest MikTex-Version (2.9) and for example calling "latex". Worked with previous versions.

Steps to Reproduce:

1. Use the integrated terminal (PowerShell) to call the latex compiler, e.g. "latex sample.tex"
2. See Latex crash within the terminal. Latex' log file points to an internal error when writing a file.
3. When executing the exact command in a regular PowerShell window (in the same directory) everything works fine. 
4. Happens with every latex file since updating to the latest version.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Please open an issue for https://github.com/PowerShell/vscode-powershell
