### ISSUE TITLE
Unable to Encode Spaces in Visual Studio launch.json's args field

### ISSUE THREAD

**Issue by jeffball55** [Microsoft/vscode#43324]
- VSCode Version: Visual Studio Community 2017, Version 15.2 (26430.13 Release)
- OS Version: Microsoft Windows 10 Enterprise

Steps to Reproduce:

1. Put test.c, CMakeLists.txt, and launch.vs.json as shown below in a folder
2. Use File->Open->Folder option to the folder
2. CMake->Build All
3. CMake->Debug->argtest.exe
4. Analyze output

I'm currently trying to set the debugging startup arguments for a CMake based project in Visual Studio.  Normally this would be done via the `launch.vs.json` file.  However, the arguments that I need to pass contain spaces in them.  For example, the below launch.vs.json file should pass the arguemnts `FIRST ARGUMENT` and `SECOND ARGUMENT` as the first and second argument.  However, the program ends up getting 4 arguments: `FIRST`, `ARGUMENT`, `SECOND`, and `ARGUMENT`.  I've tried various different encodings for spaces, but cannot get a space to be encoded properly in the resulting arguments.  This is especially problematic as one of the arguments to my program is a path inside C:\Program Files.  As such, the path is broken into 2 separate arguments, rather than one as it should be.

For reference, launching via the command line with this command works as expected:

    argtest.exe "FIRST ARGUMENT" "SECOND ARGUMENT"

launch.vs.json

    {
      "version": "0.2.1",
      "defaults": {},
      "configurations": [
        {
          "type": "default",
          "project": "CMakeLists.txt",
          "projectTarget": "argtest.exe",
          "name": "argtest.exe",
          "args": ["FIRST ARGUMENT", "SECOND ARGUMENT"]
        }
      ]
    }

test.c

    #include <stdio.h>
    int main(int argc, char ** argv) {
    	int i;
    	for (i = 0; i < argc; i++)
	    	printf("%d = %s\n", i, argv[i]);
    	return 0;
    }

CMakeLists.txt

    cmake_minimum_required (VERSION 2.8.8)
    project (argtest)
    SET( CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/ )
    add_executable(argtest test.c)

**Comment by weinand** [comment]
@jeffball55 You are talking about Visual Studio, not Visual Studio **Code**, correct?

**Comment by jeffball55** [comment]
Whoops, did not realize this was for Visual Studio Code.  Sorry about that.

**Comment by weinand** [comment]
np :-)
