### ISSUE TITLE
Lift the 60 chars limit on the camel case matcher

### ISSUE THREAD

**Issue by nachocab** [microsoft/vscode#43338]
### Issue Type
Bug

### Description

Let's say I have two classes that share some part of their names:

![screen shot 2018-02-09 at 12 26 16](https://user-images.githubusercontent.com/27538/36040885-d07cc7e6-0d94-11e8-86ef-52b6d26683fb.png)

I can access them correctly on the quick panel, but when I type a letter that matches the end of the long name, the long class disappears from the quick panel:

![screen shot 2018-02-09 at 12 26 25](https://user-images.githubusercontent.com/27538/36040919-f719bee0-0d94-11e8-898b-0c2cf2f9a1bc.png)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
This is because our camel case matcher is limited to 60 characters length for performance reasons.

**Comment by nachocab** [comment]
Ah, that explains it. Being able to extend that to at least the line length (120) would make a huge difference for some of my files 👍
