### ISSUE TITLE
Error while loading children in the custom view

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#43336]
From @letmaik [here](https://github.com/Microsoft/vscode/issues/40357#issuecomment-364383573)

Yes, it's not minimal but it's very suitable for debugging:

- Clone the debug-issue40357 branch of https://github.com/letmaik/vscode-git-tree-compare
- Run npm install and then run the extension with F5 in vs code
- You will see log output in the debugging console for each call to getChildren and getTreeItem including the returned values. You will see that in all cases getChildren returns a non-empty array and you will see there is a corresponding number of getTreeItem calls following that, again with the correct content.
- If things work correctly, you see at least one tree item, otherwise none.

**Comment by letmaik** [comment]
Just wanted to report that I don't have issues with the Insiders build on this issue, so I think you fixed something since 1.20.0 since I still see the issues there.

**Comment by sandy081** [comment]
I could also not reproduce with latest insiders. Hence closing it.

**Comment by octref** [comment]
Since both of you verified it's fixed in Insiders so I'll just skip verifying it.
