### ISSUE TITLE
Support LookBehinds In the Search Bar

### ISSUE THREAD

**Issue by IanLoC** [Microsoft/vscode#43330]
Please implement Positive and Negative Lookbehinds in the search/search and replace bar.
sometimes replacing data on the fly that are nestled in a certain pattern would be nice.
eg.

(?<=\d{3})data(?=.txt(?:$|\s)
would select only data in the bolded

123**data**.txt
982**data**.txt ...
334data.ini
433data.url.com

  ###
so that I can change small segments without affecting the surrounding data.

SublimeText supports this, and I hope that VSCode will in the future too. #

**Comment by roblourens** [comment]
These features are not supported by the ripgrep tool that powers search. You can set `"search.useRipgrep": false` to work around it but it will be much slower.
