### ISSUE TITLE
Copy and Search on Selection

### ISSUE THREAD

**Issue by guyellis** [Microsoft/vscode#43339]
I love the `copy-on-selection` super-power you just added to VSCode: https://code.visualstudio.com/updates/v1_20#_copy-on-selection

# Feature Request

Please can you add a `copy-and-search-on-selection` super-power to VSCode?

I find that 99% of the time that I copy text from the console it's to do a Ctrl+Shift+F (global find) in the code base.

This would enable those of us who work like this to skip the `Ctrl+Shift+F` step and hit enter right away to search. 

Those that don't work in this way would not enable this option. (i.e. it would be off by default - same as `copy-on-selection`)

**Comment by Tyriar** [comment]
@roblourens to implement this would a new command that's active for ctrl+shift+f when `terminalFocus` be the best approach?

**Comment by Tyriar** [comment]
@guyellis so you wan to do a global search using the selection in the terminal? I think it makes sense to transfer the selection to global find when ctrl+shift+f is pressed but to launch a search when any selection happens is very specific and likely also be detrimental to performance.

**Comment by guyellis** [comment]
@Tyriar do you say that it will be detrimental to performance because search is not a faster operation? If so, then I would agree with that statement.

My feeling is that when a developer selects something in the console (with `copy-on-select` enabled) most of the time it is then to do a global search. So if there was an option to `copy-and-search-on-select` that the global search box would be opened, populated with the selected text and given the focus. All that would be left to do would hit enter which I would imagine would still be a manual final operation so that in those cases when a search was not needed you wouldn't hit enter.

Does that make sense?

**Comment by Tyriar** [comment]
> My feeling is that when a developer selects something in the console (with copy-on-select enabled) most of the time it is then to do a global search

I disagree, I'm normally copying file names or command output to paste elsewhere. I don't think we'd want to support the flow you're proposing as so few people would discover/use it, could be bad for perf (unnecessary searches could be costly) and it does weird things with focus when you select.

I definitely want to auto fill when ctrl+shift+f happens though which should the needed actions to ctrl+shift+f and enter as you would do in the editor. Let's track that in this issue :+1:

**Comment by Tyriar** [comment]
It looks like the search viewlet pulls in the text from the active editor, I was expecting this to be done at the level of the command. @roblourens any suggestions on how to seed the search string from the terminal when it was focused? I was thinking of adding a separate command `when: "terminalFocus"` but that's not how the editor does it.

**Comment by roblourens** [comment]
I tried to clean this up once and ended up reverting it. A couple cases that I think were tricky

- Selecting text in the editor then invoking search from the menu, the editor is not focused in this case
- Clicking the activity bar icon, editor loses focus

We could add a command for the terminal with the 'when' like you suggest and have all the commands set the text instead of having the search viewlet do it. Just need to make sure it works for clicking the activity bar icon which I think is a generic "show viewlet" command.
