### ISSUE TITLE
Live preview in buffer of search and replace while typing

### ISSUE THREAD

**Issue by ozra** [Microsoft/vscode#43348]
### Issue Type
Feature Request

### Description

I searched both open and closed issues and couldn't find this.

Howl Edit, although young and immature, has some nifty things going. I really love that one _sees the replaced text and the replacement_ for every place in the doc, (lines in between are skipped to show more of the action in the screen), with tinted red/green colors highlighting the addition/removal, _updated in real time_ in the buffer _while typing_.

This goes for find also, naturally, which is _very convenient for complex regexes_. ("Was it `\1` or `$1` in this editor, now again?" - quickly discovered!). The instant feedback speeds up work flows tremendously.

As a sidenote, Howl uses a single field, with the common pattern of "delimiter", "search-term", "delimiter", "replacement". I really like predictability and easy discoverable interfaces with simple rules, allowing complex and efficient work, primarily based on buffer-editing behaviour rather than different UI/UX-behaviours all over.

**Keep it up with this highly promising editor!**

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.13.0-32-generic

**Comment by sandy081** [comment]
@ozra Live replace preview feature is already supported in Search/replace

![kapture 2018-09-12 at 22 57 37](https://user-images.githubusercontent.com/10746682/45452819-508a4000-b6df-11e8-9cb5-9985e2ee6f7d.gif)

Is this what you suggested?
