### ISSUE TITLE
Cannot create jsconfig.json file

### ISSUE THREAD

**Issue by gwynjudd** [Microsoft/vscode#4334]
- VSCode Version: March insiders build
- OS Version: Windows 8

Steps to Reproduce:

1. Opened a .js file in the new build and clicked on the "lightbulb" button in the taskbar

![image](https://cloud.githubusercontent.com/assets/314188/13826339/c4b8de50-ec1b-11e5-9651-bfa1d30ac6df.png)

![image](https://cloud.githubusercontent.com/assets/314188/13826342/cb2c4cfe-ec1b-11e5-81f3-8b8aa850f7da.png)

2. Saw a message asking if I wanted to create a project - I said yes to creating a jsconfig.json file

![image](https://cloud.githubusercontent.com/assets/314188/13826348/d3263d2a-ec1b-11e5-9eec-e0949f686bcf.png)

3. Got this error message:

![image](https://cloud.githubusercontent.com/assets/314188/13826255/69c3ed1e-ec1b-11e5-9bdb-31f22d3bb92c.png)

4. Then I tried to close the editor window and got this message:

![image](https://cloud.githubusercontent.com/assets/314188/13826381/0723c4f8-ec1c-11e5-87e7-1fa89856b2ae.png)

5. Clicked "Save" to try to save changes, and got this error:

![image](https://cloud.githubusercontent.com/assets/314188/13826392/15eb2544-ec1c-11e5-8303-c482d55e5a6b.png)

**Comment by jrieken** [comment]
fixed by 32bd7fd
