### ISSUE TITLE
Wrong suggestion when adding compound to subfolder

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#43340]
For example, try adding a compound debug in `extensions/html/.vscode/launch.json`

It's suggesting configurations in root, not in html extension folder.

![image](https://user-images.githubusercontent.com/4033249/36042076-8656fea8-0d7f-11e8-85fc-cc09dce0e431.png)

**Comment by isidorn** [comment]
This is fine. We allow you to reference any configuration from a sibling folder. We do not treat the configurations in your launch.json any specially.
Let me know if the "Launch Extension" is not offered at all since that would be a bug
