### ISSUE TITLE
Add ES2018 as target to the used tsconfig-schema.json

### ISSUE THREAD

**Issue by m451** [Microsoft/vscode#43342]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.14393
---

vscode will download the tsconfig-schema.json used for tsconfig validation, which is awesome. 
TS 2.7 just added support for ES2018 targets, see https://github.com/Microsoft/TypeScript/pull/20385 

the current tsconfig-schema yet doesn't allow to use this. I'm not sure where you're pulling the schema from otherwise I'd added a pull request myself. 

P.S.: note that with json-schema draft-07 if/then/else was added for even more flexible dependencies in the schema definition. E.g. "only allow target ES2018 if TS version is >=2.7" would be possible now.

**Comment by mjbvz** [comment]
Fixed upstream: https://github.com/SchemaStore/schemastore/pull/404#issuecomment-364572050
