### ISSUE TITLE
[theming] editorOverviewRuler.addedForeground & deletedForeground not working

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#43356]
My file has some lines added and some edited.

In gutter I can see the added lines are green, and edited are blue. A removed has a little red arrow

![image](https://user-images.githubusercontent.com/1018196/36051991-ca09edec-0da0-11e8-9591-312dd5628e6c.png)

scrollbar annotations are all blue. I would expect added sections to have same green color and a little red line to indicate something has been removed. This gives me an overview of all edits in file by just looking at scrollbar.

![image](https://user-images.githubusercontent.com/1018196/36052007-daa3cfe2-0da0-11e8-8867-749e6a6285ea.png)

Also would love it if the minimap showed the gutter lines as well.

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/12829

**Comment by nojvek** [comment]
@octref @alexandrudima  . Seems vscodebot closed the bug as dupe but the other bug is already closed and not open for collaboration.

Care to elaborate what the negative feedback was ? The decorators on scrollbar for git are on the left. The errors are on the right. You can make them a bit more translucent so they are not grabbing attention.

Making everything blue doesn't make sense at all.

**Comment by nojvek** [comment]
Also it seems there is a bug and the colors cannot be customized even though the documentation says so: https://code.visualstudio.com/docs/getstarted/theme-color-reference

```
    "workbench.colorCustomizations": {
        "editorOverviewRuler.addedForeground": "#4d7e00",
        "editorOverviewRuler.deletedForeground": "#a00011",
        "editorOverviewRuler.modifiedForeground": "#007fa1"
    }
```

Does not apply the correct colors. It's still blue everywhere.

**Comment by octref** [comment]
They should be customizable.

Per https://github.com/Microsoft/vscode/issues/12829#issuecomment-345203835

> @octref I did not define those colors. fyi they are configurable AFAIK and @aeschli changed them to be green<->green, blue<->blue and red<->red both in the line decorations and in the overview ruler and the feedback was overwhelmingly negative.

I'm giving this to you @aeschli

**Comment by nojvek** [comment]
Can we add a [bug] tag to this issue please?

**Comment by sandy081** [comment]
@aeschli Steps to verify?

**Comment by aeschli** [comment]
To verify:
- open a diff with deletions and additions
- set in the settings
    "workbench.colorCustomizations": {
        "editorOverviewRuler.addedForeground": "#ff0000",
        "editorOverviewRuler.deletedForeground": "#00ff00",
        "editorOverviewRuler.modifiedForeground": "#0000ff"
    }
- check that the overview rulers shows these colors
