### ISSUE TITLE
El host de extensiones finalizó inesperadamente.

### ISSUE THREAD

**Issue by lmarcela** [Microsoft/vscode#43353]
### Issue Type
Bug

### Description

Este problema ocurre tan pronto se inicia el programa y no permite cerrarlo.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|Memory (System)|7.89GB (2.64GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by octref** [comment]
Please follow our issue reporting guideline. Use English. Have repro steps.

https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues
