### ISSUE TITLE
PowerShell in VSCode Terminal Behaving Differently than PowerShell.exe in cmd.exe

### ISSUE THREAD

**Issue by kevintbrown** [Microsoft/vscode#43359]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.4.0
mssql|ms-|1.3.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
vim|vsc|0.10.13

---

When using PowerShell in a cmd.exe window, if I start typing a command I no longer want to execute, I can press "Ctrl+C" and it will break out of the existing line, write a new prompt, and move the cursor to the end of that new prompt.  Additionally the partially written command will not be in my history if I press up-arrow.

Native PowerShell.exe version:
```
C:\Users\kebr> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Native PowerShell.exe behavior example:

```
C:\Users\kebr> $x = Get-Process^C
C:\Users\kebr> _
<where the underscore represents the cursor position>
```

When doing the same thing in the Terminal within VSCode it appends ^C to the existing command and does not cancel out.

VSCode PowerShell Version:

```
C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

VSCode PowerShell behavior example: 

```
C:\> $x = Get-Process^C_
<where the underscore represents the cursor position>
```

**Steps to Reproduce:**

1. Open Terminal
2. Create powershell Terminal type
3. Starting typing a line of code, do **not** press "Enter"
4. Press Ctrl-C

**Expected behavior:**

Command entry should be cancelled and cursor moved to a new clean prompt with no text in it.

**Actual behavior:**

"^C" is appended to the command entry and the cursor remains at the end of the line.

**Possible workaround:**

After writing all of this I figured out you can hit Esc to clear the current command prompt entry line, and that works in the Terminal window in VSCode...I wonder if I can somehow rebind that (assuming text isn't selected, which I know you can check for with "when") since I'm in the habit of using Ctrl+C.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
We're tracking all these issues in https://github.com/Tyriar/node-pty/issues/7

Currently the only workaround is to use esc instead
