### ISSUE TITLE
Not able to hit the breakpoint in vscode(Version 1.14.0 (1.14.0))

### ISSUE THREAD

**Issue by kanikaanand** [Microsoft/vscode#43352]
- VSCode Version:1.14.0 
- OS Version: mac OS Sierra 10.12.6

Steps to Reproduce:

1. built a node project in vscode 
2. placed a breakpoint
3. started server from debug tab
4. hit the endpoint
5. flow works fine but control never stops at the breakpoints

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
@kanikaanand How does your launch.json look like?

**Comment by kanikaanand** [comment]
it has the program as this: 

"program": "${workspaceRoot}/index.js

**Comment by kanikaanand** [comment]
Hi, I upgraded to 1.20.0 and still face the same problem.

**Comment by weinand** [comment]
@kanikaanand Could you please include the complete launch config here (the one which includes the line `"program": "${workspaceRoot}/index.js`).

**Comment by kanikaanand** [comment]
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/index.js"
        }
    ]
}

**Comment by weinand** [comment]
if your program `index.js` is just this:
```js
console.log("hello");
debugger;
```
and you set a breakpoint in line 1, then press 'F5', are you hitting the breakpoint or are you stopping on the debugger statement?

What version of node.js are you using?

**Comment by kanikaanand** [comment]
it does not stop at the breakpoint. I am using node version v6.9.5

**Comment by weinand** [comment]
Does it help if you add a `"protocol": "inspector"` to your launch config?
