### ISSUE TITLE
Format Code doesn't work for an unsaved buffer

### ISSUE THREAD

**Issue by chmllr** [Microsoft/vscode#4335]
- VSCode Version: 0.10.11
- OS Version: Windows 7

Steps to Reproduce:

- Open a new buffer (Ctrl+N)
- Set the language mode to JavaScript (Ctrl-K M)
- Type some code with wrong indentation, e.g.
```
var x = 1;
    var y = 2;
```
- Try to format the code (Alt+Shift+F)

__What happens__: Nothing.
__What is expected to happen__: Code should be formatted.

I tried to fix this bug, but realized that it might be a design issue:

- Code formatting is carried out by an external plugin (in case of JS it's the TS-Server)
- VSC issues a corresponding "format" message [formattingProvider.ts:102](https://github.com/Microsoft/vscode/blob/4da8ef4e95e423071596a64b3d37c638b6700a62/extensions/typescript/src/features/formattingProvider.ts#L102) to the TS-Server consisting params of the format `{"file":null,"line":1,"offset":1,"endLine":25,"endOffset":3}`.
- The TS-Server tries to open file `null` from its `syntaxTreeCache` which leads to this error:

    "{"seq":0,"type":"response","command":"format","request_seq":76,"success":false,
    "message":"Error processing request. Cannot read property 'replace' of null"}"

which is caught at [formattingProvider.ts:105](https://github.com/Microsoft/vscode/blob/4da8ef4e95e423071596a64b3d37c638b6700a62/extensions/typescript/src/features/formattingProvider.ts#L105) but not logged anywhere, apparently.

So the issue is, an unsaved buffer has no file path and, hence, is not accessible for the TS-Server. potentially, this might be fixed by using some internal fake path, which would be known to the TS-Server's `cacheSyntaxTree`. Apparently, a physical file is not a hard requirement. Initially I assumed, that VSC only sends a file name to the TS-Server, who reads the file, computes the range and sends the formatted code back. However, a fast test disproved this:

- save a buffer to a file
- delete file immediately from the FS 
- change the code and try to format it
- ensure it worked

So: the TS-Server uses the filename but reads the file content from some internal cache shared between VSC and TSS. This cache might be the right place to reference the unsaved buffer. But if I'm right, it's a subject for a major design change.

If you have better suggestions because I overlooked something feel free to inform me and I could make another attempt.

**Comment by dbaeumer** [comment]
Works for me on latest (the next upcoming build)

![bug](https://cloud.githubusercontent.com/assets/1931590/14015780/d0efb522-f1bb-11e5-9ce8-05aeff47835e.gif)

**Comment by chmllr** [comment]
@dbaeumer sorry, your test (at least on the screenshot) is wrong. You have a _previously_ saved file test.js. I was talking about unsaved buffers, before you save the content of a new tab.

Just repeat the repro steps I described.

**Comment by dbaeumer** [comment]
@chmllr sorry for that. I now see what you are talking about. This is a general issue in the tsserver we use. The corresponding issue in TS land is: https://github.com/Microsoft/TypeScript/issues/4526.

I will keep that issue closed since it dups https://github.com/Microsoft/TypeScript/issues/4526

**Comment by chmllr** [comment]
@dbaeumer Great, thanks a lot!
