### ISSUE TITLE
File explorer: type to search & select prefix

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#43358]
IntelliJ / pycharm / webstorm has this amazing feature where you type in file explorer, it scrolls to  files/folders with that prefix. It allows quick navigation of file explorer to find what you need super quick.

Also Since ctrl/cmd+p only finds files but not folders, We should allow finding of folders. If folder is found, then file explorer scrolls to that folder.

**Comment by nojvek** [comment]
I made an attempt at #43400 but I need help from someone in vscode to productionize it. Current solution is looking deep inside privates a bit too much.

**Comment by isidorn** [comment]
If I understand correctly this is a duplicate of https://github.com/Microsoft/vscode/issues/10026
