### ISSUE TITLE
Panel Glitch - Multiple "Add Configuration"

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#43350]
### Issue Type
Bug

### Description

- Open 2 launch.json
- In first editor, open Panel
- Switch to second editor, close Panel
- You end up with two "Add Configuration"

![panel](https://user-images.githubusercontent.com/4033249/36049510-d464fc04-0d97-11e8-87d4-2871669dd182.gif)

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (d28f096018e2673a8437c788e3eed781ddb505ce, 2018-02-09T06:08:42.088Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|17%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.3.0
tslint|eg2|1.0.24
prettier-vscode|esb|1.1.3
vscode-slm|mrm|1.1.0
PowerShell|ms-|1.5.1
vetur|oct|0.11.7
vim|vsc|0.10.13

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
@octref good catch!
