### ISSUE TITLE
New Window does not start a new instance of VS Code in a separate window

### ISSUE THREAD

**Issue by oscarcao** [Microsoft/vscode#43360]
- VSCode Version: 1.20.0
- OS Version: 10.13.3

Steps to Reproduce:

1. Use any of the create 'New Window' approaches: 
- From menubar: File > New Window
- Pressing keyboard shortcut: CMD + Shift + N
- From Dock: Right Click VS Code Icon > New Window
2. The current workspace is replaced with a blank workspace.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@oscarcao that should not be the case. can you share your settings?

**Comment by oscarcao** [comment]
These are my custom settings:

// Place your settings in this file to overwrite the default settings
{
"telemetry.enableCrashReporter": false,
"git.confirmSync": false,
"window.nativeTabs": true,
"workbench.iconTheme": "material-icon-theme",
"git.enableSmartCommit": true,
"editor.minimap.enabled": false,
"extensions.ignoreRecommendations": true,
"workbench.startupEditor": "none",
}

**Comment by bpasero** [comment]
@oscarcao maybe try to set `"window.nativeTabs": false`

**Comment by oscarcao** [comment]
Setting `"window.nativeTabs": false` resolves the issue. However, for Hyperdock's window snapping feature to work, I need to have nativeTabs enabled.

**Comment by bpasero** [comment]
This is a OS setting then, nothing VS Code controls:

![image](https://user-images.githubusercontent.com/900690/36295730-a0db6164-12e9-11e8-80d1-dec1f4c8379b.png)
