### ISSUE TITLE
Intellisense doesn't use jsdoc for class instance properties

### ISSUE THREAD

**Issue by 1999** [Microsoft/vscode#43367]
- VSCode Version: Version 1.19.3 (1.19.3)
- OS Version: OSX (Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64)

Looks like intellisence is using jsdoc param types only when method is declared as a prototype method.

## prototype method (works as expected)

<img width="795" alt="screen shot 2018-02-10 at 12 39 07 pm" src="https://user-images.githubusercontent.com/73191/36057226-d36c4910-0e5f-11e8-8aa0-4715d2369824.png">

## class property (fallback to any, why?)

<img width="784" alt="screen shot 2018-02-10 at 12 39 28 pm" src="https://user-images.githubusercontent.com/73191/36057231-e3a757c0-0e5f-11e8-8840-132941e31cdb.png">

**Comment by 1999** [comment]
Well, that's cool but to me it's more like a workaround for an issue. Isn't `onStreamGot` a function at the same time? The only difference is that it will be an own property of newly created object but not  a property of this object's prototype. So why should I use `@type` instead of `@param` here?

**Comment by yume-chan** [comment]
I have tried with JSDoc 3.5.5

----

``` js
/** Test class */
export class A {
    /**
     * Test method
     * @param {string} input
     */
    method(input) { }
}
```

Works

----

``` js
/** Test class */
export class A {
    /**
     * Test method
     * @param {string} input
     */
    method = (input) => { }
}
```

Doesn't work

----

``` js
/**
 * Test class
 * @constructor
 */
export function A() {

}

/**
 * Test method
 * @param {string} input
 */
A.prototype.method = (input) => { }
```

Works

----

``` js
/**
 * Test method
 * @param {string} input
 */
export const method = (input) => { }
```

Doesn't work

----

So I think it's intended, or this usage has not been specially treated by JSDoc.

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/19231
