### ISSUE TITLE
FR: full-sized terminal in a new buffer tab

### ISSUE THREAD

**Issue by LER0ever** [Microsoft/vscode#43369]
Currently the integrate terminal only takes up the size of the debug panel. It would be really nice if it can be treated in a buffer tab, i.e. full-sized terminal tabs.
Or maybe even implement split support. so that it can also work as a flexible terminal emulator.

Currently this is the largest terminal size I can get:
![image](https://user-images.githubusercontent.com/10568668/36057431-af362110-0dd3-11e8-9ddc-8c78986dff81.png)

**Comment by Tyriar** [comment]
Closing in favor of:

- Split terminals https://github.com/Microsoft/vscode/issues/7504
- Allow to dock editors and panels anywhere in the workbench 
 https://github.com/Microsoft/vscode/issues/11472

You might also find the toggle maximize panel command useful, eg:

```js
{ "key": "ctrl+shift+q",    "command": "workbench.action.toggleMaximizedPanel" },
````

**Comment by LER0ever** [comment]
Thanks! Indeed my FR is exactly a combination of #7504 and #11472 . I'll subscribe to those two instead.
