### ISSUE TITLE
markdown highlight desapeared

### ISSUE THREAD

**Issue by wilfredinni** [Microsoft/vscode#43362]
### Issue Type
Bug

### Description

for some reason, after installing a markdown extension (Markdown Preview Github Styling) the highlight of the raw text desapeared 

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (d28f096018e2673a8437c788e3eed781ddb505ce, 2018-02-09T05:14:50.066Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2395)|
|Memory (System)|3.88GB (0.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
project-manager|ale|0.24.0
vscode-markdownlint|Dav|0.13.0
githistory|don|0.4.0
code-runner|for|0.8.7
output-colorizer|IBM|0.1.2
python|ms-|2018.1.0
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7
vscode-todo-highlight|way|0.5.11
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|1.0.5

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
Please provide a screenshot of the problem

**Comment by mjbvz** [comment]
Likely fixed by 38cfb0438e2c831fb01d8a6df511957c1f018dac
