### ISSUE TITLE
Css suggestions does no work for id

### ISSUE THREAD

**Issue by Skeletoo** [Microsoft/vscode#43368]
### Issue Type
Bug

### Description

i have issues when i try to use suggestion for css files. for classes works well but when i'm  using for id i have no suggestions try it with a file with like 500 lines of code

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|3.91GB (0.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-eslint|dba|1.4.5
vsc-material-theme|Equ|1.3.0
prettier-vscode|esb|1.1.3
LiveServer|rit|3.2.0

</details>
Reproduces without extensions

**Comment by octref** [comment]
Please do not open multiple issues for the same problem. Dup of #43365
