### ISSUE TITLE
New file / New folder command missing after latest update

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#43363]
- VSCode Version: 1.20

After updating to 1.20, the `New File` command is missing from the command palette.

**Comment by bpasero** [comment]
@isidorn I think we should restore this command for our recovery release:

![image](https://user-images.githubusercontent.com/900690/36059403-dcecadd0-0e38-11e8-9956-ea4037fd75a5.png)

**Comment by isidorn** [comment]
I have added these actions again to the command palette.
As before they open the viewlet if it is not open already.
@bpasero please code review / verify. Thanks
