### ISSUE TITLE
Non-breaking space character modified in editor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#43366]
Fork of https://github.com/Microsoft/vscode/issues/43364

- `echo '\xa0' > test.txt`
- Open test.txt in vscode
- Modify it somehow - type a newline at the end, and save
- The `A0` character has been transformed to `EF BF BD`

```
$ xxd test.txt
00000000: efbf bd0a 0a 
```

(`0A` is newline)

A0: http://www.fileformat.info/info/unicode/char/00a0/index.htm

EF BF BD: https://apps.timwhitlock.info/unicode/inspect?s=%EF%BF%BD

**Comment by rebornix** [comment]
![charcode](https://user-images.githubusercontent.com/876920/36995767-d029b582-2069-11e8-9a06-3063f2929be6.gif)

@roblourens can you provide more detailed reproduce steps? I can't reproduce locally as above.
