### ISSUE TITLE
Finding non-printable character gives unexpected results

### ISSUE THREAD

**Issue by tedhudek** [Microsoft/vscode#43364]
- VSCode Version: 1.20
- OS Version: Win10 RS3

Recreating this problem manually doesn't work because pasting the non-printable diamond char yields a different byte sequence.  Here's one way to repro:

1. `git clone https://github.com/tedhudek/cfg.git`
2. In Code, open the cfg folder.
3. Open src/device-audiorequirements.md and copy the diamond char from line 20.
4. Open the search panel.
5. The find bar is already populated with the diamond char.
6. Hit enter to search.
7. 175 results in the one open file.
8. Close the file.
9. Put the cursor back in the search bar and hit enter again.
10. No results.
11. Expected result is the character appears in two files, both of which are in the src folder.

Another oddity is that if you add a space (or any character) to the file and save it, Code changes all occurrences of the diamond char (which was byte code A0) to the byte sequence EF BF BD.  So you add one char and now the file is (in this case) 353 bytes longer.  Git functionality in Code does not report the changes, but git diff on the command line does.

**Comment by roblourens** [comment]
Hm, not sure what's going on. We use ripgrep for search, and it doesn't find `A0`, but it does find it when I write `C2 A0` to a file which is apparently the correct UTF-8 representation. Do you know whether this file is supposed to be interpreted as a different encoding? The search also doesn't work when I specify UTF-16.

I think the editor rewriting that character is just another bug, filed https://github.com/Microsoft/vscode/issues/43366 for that.

**Comment by tedhudek** [comment]
Hi Rob, not as far as I know, should be UTF-8.  Could it also be a bug in Code that Find only works on the diamond char for occurrences in open editors?  My scenario is, I do a big conversion to .md (this output comes out of Pandoc), and then I want to remove all the diamond chars.  So I scope search to a folder and search for it.  Search fails except for the open editor.  So I opened all files in that directory, and was able to work around it that way.  But at first it was reporting zero hits when I didn't have any of the files open.  That seems like a bug to me.

**Comment by roblourens** [comment]
Search in open editors is implemented differently. Given #43366, I think it's probably searching using that EF BF BD sequence in memory for open editors.

So the only question is whether to report this upstream to ripgrep. It has the same behavior as grep here and works with C2 A0 which is [apparently the correct UTF-8 representation](http://www.fileformat.info/info/unicode/char/00a0/index.htm). So without more information I'd have to assume this is a Pandoc issue.
