### ISSUE TITLE
Writing commit message in the main window

### ISSUE THREAD

**Issue by skippednote** [Microsoft/vscode#43373]
- VSCode Version: 1.20
- OS Version: Ubuntu 16.04

Is there some way to write commit message in the main window where I can use snippets for the commit messages instead of small Window in the left sidebar?

**Comment by joaomoreno** [comment]
Currently, the only way is to configure Code to be the default git editor, and then running `git commit` from a terminal:

https://code.visualstudio.com/docs/editor/versioncontrol#_git-patchdiff-mode
