### ISSUE TITLE
Files included in .gitignore are colour red

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#43377]
Latest code on latest Windows

Files listed in .gitignore are showing in the file list as red :(

![image](https://user-images.githubusercontent.com/618922/36060238-5a140444-0e3d-11e8-8bfd-406f5f58c1ed.png)

**Comment by SteveALee** [comment]
OK, I now see it is more pink than and is probably intentional?

I'm not convinced it makes sense as a warning in the files list, esp. node_modules - perhaps just the VC list - but then you'd need a new 'ignored' section

**Comment by usernamehw** [comment]
Is the color the same in another color theme?

**Comment by SteveALee** [comment]
Thanks - I just realised it must be theme specific and should be tweekable. Thanks for the info!

**Comment by SteveALee** [comment]
#808080 works nicely for me

**Comment by SteveALee** [comment]
#808080 works nicely for me
