### ISSUE TITLE
Auto import suggestion not working with Angular 5, typescript 2.7.1 with the latestvisual studio code

### ISSUE THREAD

**Issue by rkramakrishna17** [Microsoft/vscode#43374]
### Issue Type
Bug

### Description

So I have a Angular component but when i went to app.module.ts file to import it. I have mentioned the component name in the declarations but it was not suggesting which file to auto-import with typescript version 2.7.1 but this clearly working with version 2.5.1.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.13.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-7300 Radeon R6, 10 Compute Cores 4C+6G (4 x 1500)|
|Load (avg)|1, 1, 1|
|Memory (System)|6.75GB (1.74GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
html-css-class-completion|Zig|1.16.1
path-intellisense|chr|1.4.2
gitlens|eam|8.0.0
vscode-html-css|ecm|0.2.0
Angular2|joh|2.12.0
typescript-hero|rbb|2.2.0
vscode-icons|rob|7.19.0

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Do you still see this issue in the latest VS Code builds using typescript 2.9?

**Comment by rkramakrishna17** [comment]
No.. I don't see this issue. Thanks for the fix.

checked in :
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
