### ISSUE TITLE
Should be able to search for extensions by creator

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4337]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Press F1
2. Type ext install
3. Type Microsoft.

Actual:
Brings up two non-Microsoft produced extensions.

Expected:
Be able to search by creator (e.g. Microsoft).

**Comment by egamma** [comment]
This is supported in the market place.

**Comment by joaomoreno** [comment]
And it's now supported in the product!

![image](https://cloud.githubusercontent.com/assets/22350/16586462/5d0be2a0-42c6-11e6-8591-b558aa9bc0dd.png)
