### ISSUE TITLE
New command, "Select to Bracket", that will select the text between ...

### ISSUE THREAD

**Issue by user3323** [microsoft/vscode#43371]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

https://code.visualstudio.com/updates/v1_20#_select-text-while-jumping-between-brackets
tells us:
> There is a new command, **Select to Bracket**, that will select the text _**between two matching brackets**_ (as opposed to the already existing command, Go to Bracket, which only moves the cursor to the matching bracket).

I'm not an expert in English, but I think "between two matching brackets" means, that brackets (parenthesis, etc.) should be **_excluded_** from this selection...

![select the text between](https://user-images.githubusercontent.com/24613274/36058079-47038526-0e21-11e8-8f42-5274a70c8442.gif)

.. shouldn't they?

**Comment by alexandrudima** [comment]
I don't know what would be best, to select the brackets or not...

This came in as PR #39066 from @afonsobspinto

**Comment by afonsobspinto** [comment]
Hey. That's a great question. We faced the same one. 
We ended up opting to select the brackets too since it was @chrisdavies's preference in the PR #28163

>  I vote for selecting the brackets as well. I'm often trying to yank code, which generally includes the brackets.

I should try to add support for multicursors soon, so let me know if you want me to change the behavior too.

**Comment by user3323** [comment]
@alexandrudima 

how about to make an option?
1) with brackets
2) without brackets

**Comment by alexandrudima** [comment]
We could add an argument to the command implementation.

It would be definable in `keybindings.json` like e.g.:
```json
	{
		"key": "shift+cmd+\\",
		"command": "editor.action.selectToBracket",
		"args": { "selectBrackets": false }
	}
```

Those would be available in the last argument (not used now) for the `run` method:
```ts
public abstract run(accessor: ServicesAccessor, editor: ICodeEditor, args: any): void | TPromise<void>;
```
https://github.com/Microsoft/vscode/blob/1633d0959a33c1ba0169618280a0edb30d1ddcc3/src/vs/editor/contrib/bracketMatching/bracketMatching.ts#L61

**Comment by kanlukasz** [comment]
Is it possible to select without brackets now?
I looking for solution for selection without brackets because it's really useful.

#### Example - CSS sorting: 
Step 1 - Select all **without** brackets
Step 2 - Run command - Sort lines Asc.

Above scenario is impossible right now :(

**Comment by ppnman** [comment]
Let's say that there is a command called `selectBracket`.
Then `selectBracket (` select the text between brackets does not include brackets themself.
 `selectBracket )` select the text between brackets include brackets themself.

**Comment by jsejcksn** [comment]
You might be interested in [Shrink/Expand Selection](https://code.visualstudio.com/docs/editor/codebasics#_shrinkexpand-selection)

**Comment by yisibl** [comment]
@alexandrudima @afonsobspinto Do you have the opportunity to support this?

I want the behavior of selectToBracket to continue to expand(`editor.action.smartSelect.grow`) like Smart selection.

**Comment by ReaperTech** [comment]
Does anyone know - is there a shortcut key for editor.action.selectToBracket ? When I search through Keyboard Shortcuts it is not listed.

**Comment by kanlukasz** [comment]
From what i know they didn't add this but it's not a problem because you can make your own shortcut:

```
{
    "key": "ctrl+shift+'",
    "command": "editor.action.selectToBracket",
    "args": {
        "selectBrackets": false
    }
}
```

**Comment by ReaperTech** [comment]
> From what i know they didn't add this but it's not a problem because you can make your own shortcut:
> 
> ```
> {
>     "key": "ctrl+shift+'",
>     "command": "editor.action.selectToBracket",
>     "args": {
>         "selectBrackets": false
>     }
> }
> ```

Thanks @kanlukasz ! If anyone reading this wants to know where you place this text ->
press **ctrl+shift+p** and type **Preferences: Open Keyboard Shortcuts**, select the **Open Keyboard Shortcuts (JSON)** icon top right and add it in there.
![image](https://user-images.githubusercontent.com/43549638/68857274-240af300-06eb-11ea-9bdb-6ecbfd9f6ce1.png)
https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization
