### ISSUE TITLE
an error message diaolog popup when launch vscode

### ISSUE THREAD

**Issue by g8up** [Microsoft/vscode#43376]
- VSCode Version:1.19
- OS Version:Mac

Steps to Reproduce:

1.launch vsocde
2.popup an error message:
>[_my_extension_folder]: Error: ENOENT: no such file or directory, scandir '_my_extension_folder'

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@g8up Is there any error stack trace?

Please check the logs in output panel and also the console in development tools
