### ISSUE TITLE
Git Submodule doesn't update if modified from integrated terminal

### ISSUE THREAD

**Issue by McPrescott** [Microsoft/vscode#43375]
### Issue Type
Bug

### Description

There is a similar issue @ [No auto fetch for submodules](https://github.com/Microsoft/vscode/issues/42436) . This is however, slightly different.

While working in the same workspace I typically commit from the integrated terminal. When I update the main repository changes are shown immediately. However if I make any changes to a submodule, changes are not updated unless VS Code is reloaded. 

Is this another issue that should be fixed by configuring an upstream link or is this a bug?

I didn't include System Info as I thought is was superfluous. It can be added if requested.

**Comment by joaomoreno** [comment]
> I didn't include System Info as I thought is was superfluous.

More details are rarely superfluous. Which OS? Which version? Does it reproduce in the latest [insider release](https://code.visualstudio.com/insiders)?

Here's what I see:

![kapture 2018-02-12 at 10 40 14](https://user-images.githubusercontent.com/22350/36090604-4d899130-0fe1-11e8-8ecc-f65a86cb67ce.gif)
