### ISSUE TITLE
Image preview zooming issue

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#43388]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

When you try to zoom an image, using "Ctrl + Mouse Wheel scrolling"....

scrolling it up (outwards) - will make an image zoomed out...
scrolling it down (to you) - will make an image zoomed in..

How come?
Why do we need this inversion?

**Comment by mjbvz** [comment]
Duplicate of #43138
