### ISSUE TITLE
When files in One Drive fold， Find in Files only searches in opened files in workspace

### ISSUE THREAD

**Issue by yifeitao** [Microsoft/vscode#43381]
- VSCode Version:1.20.0
- OS Version: Windows 10 1709

Steps to Reproduce:

1. Ctrl-Shift-F (Search in files). Type something I know it's in my source files.
2. VSCode does not find anything.
3. Open one source file
4. Repeat the search, it does find the term within the opened file.

**This is only happening when files in One Drive fold. When open files not in One Drive folder, it works.**

Does this issue occur when all extensions are disabled?: Yes

**Comment by yifeitao** [comment]
when I close the ‘Files On-Demand’ feature of onedrive, it's OK now.
**So the bug only happen when you use the ‘Files On-Demand’ feature of onedrive.**

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/35433. It should be fixed in Insiders, please try it out.
