### ISSUE TITLE
Format code only in selection

### ISSUE THREAD

**Issue by PragmaticEd** [Microsoft/vscode#43383]
I know there is command `editor.action.formatDocument`, that works perfectly, however, most of the time i need to format code only in selection, leaving the rest of the document as it is.

Is that possible?

**Comment by usernamehw** [comment]
`editor.action.formatSelection` ?

**Comment by PragmaticEd** [comment]
Thanks @usernamehw , thats the one..

I ended up with this, in case someone else needs it:
```json
   {
        "key": "shift+alt+f",
        "command": "editor.action.formatDocument",
        "when": "editorTextFocus & !editorHasSelection"
    },
    {
        "key": "shift+alt+f",
        "command": "editor.action.formatSelection",
        "when": "editorTextFocus && editorHasSelection"
    }
```
