### ISSUE TITLE
Realtive file links in terminal are resolved realtive to first folder in workspace, not current working directory

### ISSUE THREAD

**Issue by eloff** [Microsoft/vscode#43398]
### Issue Type
Bug

### Description

Create a multi-root workspace. Create files with the same name in both workspace "project" folders. Relative file links should be resolved relative to the current working directory, but you'll see they are resolved relative to the first project in the workspace, even when e.g. running tests in the terminal from the second workspace folder.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.34GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_659617|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.24
gitlens|eam|8.0.0
Go|luk|0.6.74
vscode-proto3|zxh|0.1.2

</details>
Reproduces only with extensions

**Comment by eloff** [comment]
As an aside, I've been searching all over for a way to set the "primary" or default project in a multi-root workspace. This could allow working around the problem. Is there a way to do that?

**Comment by octref** [comment]
What kind of file are you working on? We fixed that for [html](https://github.com/Microsoft/vscode/issues/38469), but this is a feature offered by extensions and should be fixed in that specific extension.

**Comment by eloff** [comment]
This is for the integrated terminal, I think it's odd that how relative links are handled in the terminal should depend on the extension used - but you would know better than I would. I'm working with Go files (and the Go extension to vscode.)

**Comment by octref** [comment]
With this API: https://code.visualstudio.com/docs/extensionAPI/vscode-api#_registerDocumentLinkProvider

extensions could register link providers for different files. But for terminal it's a VS Code problem.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/27107
