### ISSUE TITLE
Horizontal file layout - feature?

### ISSUE THREAD

**Issue by AnthonyMichaelc** [Microsoft/vscode#43390]
A feature request, explain how to do this....

I take advantage of the vertical page layout to have at least 2 files open at the same time, however, for anyone who has a small screen (13 inch laptop ,etc) being able to drag an open file to the botton of the screen can be better since you can see each file at full with. 

I will paste in a screenshot of atom as reference.

<img width="1094" alt="screen shot 2018-02-10 at 11 11 22 am" src="https://user-images.githubusercontent.com/13970615/36064054-5c31c638-0e53-11e8-8883-be8f3e1b1a29.png">
<img width="1068" alt="screen shot 2018-02-10 at 11 11 51 am" src="https://user-images.githubusercontent.com/13970615/36064055-5c431992-0e53-11e8-9cca-95b407abe125.png">

**Comment by usernamehw** [comment]
keybindings => `workbench.action.toggleEditorGroupLayout` ?

**Comment by AnthonyMichaelc** [comment]
@usernamehw How would that be implemented in settings?

**Comment by usernamehw** [comment]
@AnthonyMichaelc Split editor => <kbd>F1</kbd> => type `horizon` => <kbd>Enter</kbd>

**Comment by usernamehw** [comment]
Are you asking about changing the default value?

**Comment by AnthonyMichaelc** [comment]
@usernamehw I am asking if there is a way to have both. I referenced atom because they allow you to grab the tab of a file and then drag it all the way to the right for a vertical layout or you can drag it down to the bottom for a horizontal layout without having to do a keyboard function that makes it strictly only vertical or only horizontal.

Not an Atom fan but having the ability to drag a file to either the side or bottom at any time is better user friendly in cases where you are plugged into a monitor and then unplug to work on the go or something like that. If this is something that is deemed not valuable to add I understand and will use the command you just showed me, just curious if this is a feature that could be added.

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/14909

**Comment by AnthonyMichaelc** [comment]
@usernamehw Thank you for linking me to that discussion.
