### ISSUE TITLE
出现file not found错误

### ISSUE THREAD

**Issue by james-tech** [Microsoft/vscode#43392]
### Issue Type
Bug

### Description

- VSCode Version: 1.20
- OS Version:  Mac 10.12.6 (16G1114)

Steps to Reproduce:

1.  a.h in dir {workspaceroot}/lib_src, with content:

#include <map>
#include <string>

using namespace std;

class Iobserver
{
  public:
	virtual void update(const string &json) = 0;
	Iobserver()
	{
		_observerid = _curr_last_id++;
	}
	Iobserver(int id)
	{
		_observerid = id;
	}

	int id()
	{
		return _observerid;
	}

  protected:
	int _observerid;
	static int _curr_last_id;
};

class Ipublisher
{
  public:
	virtual bool register_observer(Iobserver &o) = 0;
	virtual bool unregister_observer(Iobserver &o) = 0;
	virtual bool publish_msg(const string &json) = 0;
};

2. b.cpp in dir {workspaceroot}/src:

#include "a.h"

class Cpublisher : public Ipublisher
{
  public:
	bool register_observer(Iobserver &o);
	bool unregister_observer(Iobserver &o);
	bool publish_msg(const string &json);

  private:
	map<int, Iobserver *> observers;
};

class Cobserver : public Iobserver
{
  public:
	void update(const string &json);

	Cobserver() : Iobserver() { ; }
	Cobserver(int id) : Iobserver(id) { ; }
};

3. set c_cpp_properties.json : 
"configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include",
                "${workspaceRoot}",
                "${workspaceRoot}/lib_src"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "",
                "path": [
                    
                    "/usr/include",
                    "${workspaceRoot}",
                    "${workspaceRoot}/lib_src"
                ]
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
4. edit b.cpp, 
class Cobserver : public Iobserver1111111111 // <<< here won't found symble
{
  public:
	void update(const string &json);

	Cobserver() : Iobserver() { ; }
	Cobserver(int id) : Iobserver(id) { ; }
};

5. now vscode will report : "a.h" file not found, and after I fix up the b.cpp Iobserver1111111 to Iobserver, I also need to restart vscode then it will work fine... 

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-database|baj|1.3.0
vscode-clang|mit|0.2.2
mssql|ms-|1.3.0
cpptools|ms-|0.14.6

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
