### ISSUE TITLE
Autocomplete suggestions do not always select the first suggestion by default, breaking flow

### ISSUE THREAD

**Issue by majelbstoat** [Microsoft/vscode#43391]
- VSCode Version: Version 1.20.0 (1.20.0)
- OS Version: OSX High Sierra 10.13.3

There is a very confusing behaviour in VSCode's autocomplete, such that under certain circumstances, when a list of suggestions is offered, the first one is not selected by default. For example, in this screenshot, pressing `.`, resulted in this state:

<img width="556" alt="screenshot 2018-02-10 08 42 00" src="https://user-images.githubusercontent.com/425787/36064358-b1032086-0e3e-11e8-8107-06ac61230acd.png">

My expectation is to scan the autocomplete suggestions from top to bottom, moving the cursor down if I need to make a change. What frequently happens is, I see the first suggestion, in this case 'children', is the one I want, and press Enter. However, pressing Enter does not insert 'children', but instead inserts 'routes'. 

To me, this is completely unexpected, and really breaks the flow of writing code, as I have to check which suggestion is selected each time. What makes it worse is that this only happens in certain situations, leading me to believe VSCode is deliberately do this to try and be helpful.

I've tried looking for a setting to control this, but haven't been able to find one.

I've noted this behaviour while writing JS, Typescript, and Go.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/41060#issuecomment-364284879

**Comment by majelbstoat** [comment]
Cool :) Thanks for the pointer.
