### ISSUE TITLE
HTML language not supported or defined

### ISSUE THREAD

**Issue by Silviu276** [Microsoft/vscode#43394]
I am totally new to coding and visual studio but I know something HTML and I tried to make a small website and I writed:

<!DOCTYPE html>
<html>
    <head>
    </head>
       <title>My First Website</title>
    <body>
    </body>
</html>

(I learned HTML from Codecademy, if it helps..)

and I tried to run it, but I received an error ("Code language not supported or defined"). I don't know how to solve it so.. please help me a bit!

P.S.: I have HTML language mode activated.

**Comment by Silviu276** [comment]
Umm.. my code does not appear... why?

**Comment by apap04** [comment]
You gotta launch the file in your browser.

**Comment by apap04** [comment]
![tcgip](https://user-images.githubusercontent.com/17275723/36065471-71c4c62e-0e69-11e8-9d05-80dc58015194.gif)

**Comment by aeschli** [comment]
@Silviu276 @apap04 is right, we don't have a feature to 'run' a html page out of VSCode. You need to open the file in a browser instead.
