### ISSUE TITLE
Visual Studio Code should not discriminate against .gitignore files. It should infact worship them.

### ISSUE THREAD

**Issue by binuwu** [Microsoft/vscode#43395]
- VSCode Version: `1.19.1`
- OS Version: `Windows 10` (latest public build as of 2/10/2018)

Steps to Reproduce:

1. Open a file
2. Hit "Save as" or use Control + Shift + A
3. Change the file type in the dropdown
4. Hover over "Plain Text"
5. You will see that it's calling `.gitignore` as a "plain text" file.

**This is not okay, `.gitignore` should be be hailed, it is our saviour, our god. How dare they call it just a mere *plain* text. Hmph!**

Here's an image:
![this_is_sinning](https://pixls.space/QeUc4.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

(P.S I'm extremely sorry for this shitpost please don't hate me)

**Comment by binuwu** [comment]
Also might as well add `.gitignore` highlighting

**Comment by asdeq** [comment]
i keep accidentally opening microsoft visual studio

(why did you DM me this bin)

**Comment by victionn** [comment]
(and me too)

**Comment by apap04** [comment]
(same)

**Comment by Oskarr1239** [comment]
(same)

**Comment by TAGC** [comment]
But why.

**Comment by endmylife** [comment]
lolwat

**Comment by Pizzacus** [comment]
He DMed it to me too

Okay, nice to see bin truely DMs his shitposts to EVERYONE

**Comment by asdeq** [comment]
bin jesus do you use like a selfbot to mass dm

**Comment by binuwu** [comment]
I am a god shitposter what do you mean

**Comment by binuwu** [comment]
Me and Shiro are like true gods of all shitposting.
We may not shitpost much, but when we do: it's really good.

**Comment by Oskarr1239** [comment]
XD

**Comment by Pizzacus** [comment]
That is a bad shitpost tho please delet

**Comment by binuwu** [comment]
What no it isn't

**Comment by binuwu** [comment]
I'm actually serious about this issue. I love `.gitignore` and git in genral!!

**Comment by asdeq** [comment]
f to pay respects

**Comment by asdeq** [comment]
f

**Comment by ShayBox** [comment]
This is why you get banned from discord bin, not because b1nzy hates you, which he probably does.

**Comment by binuwu** [comment]
What does this have to do with Discord?

**Comment by xdMatthewbx** [comment]
WHOMST

**Comment by octref** [comment]
VS Code is a program. As such, it does not discriminate or worship.

If you are a real worshiper of .gitignore, consider making an extension to better support it: https://code.visualstudio.com/docs/extensions/overview
