### ISSUE TITLE
Releasing mouse button outside window does not stop selecting text on Linux

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode#43404]
- VSCode Version:  1.20.0
- OS Version: Arch Linux 64-bit

Steps to reproduce:

- Make sure you are using Visual Studio Code for Linux.
- Press your left mouse button to begin selecting text.
- Move your mouse cursor outside the window.
- Release the mouse button.
- Move your mouse cursor inside the window.

You should notice that although you have released your mouse button, the text selection still follows your mouse cursor.

**Comment by alexandrudima** [comment]
I could not reproduce on Ubuntu 16.04.4 LTS , it might be something specific to Arch Linux

**Comment by EFanZh** [comment]
I was using [Synergy](https://en.wikipedia.org/wiki/Synergy_(software)) to control my Linux PC from a Windows PC.

Here is what I have tried:

- I cannot reproduce if
  - I was using the Linux PC’s mouse to control Visual Studio Code on the same Linux PC, or
  - I was using the Windows PC’s mouse to control Visual Studio Code on the same Windows PC, or
  - I was using the Linux PC’s mouse to control Visual Studio Code on the Windows PC through Synergy, or
  - I was using the Windows PC’s mouse to control gedit on the Linux PC through Synergy, or
  - I was using the Windows PC’s mouse to control KWrite on the Linux PC through Synergy.
- I can reproduce only if
  - I was using Windows PC’s mouse to control Visual Studio Code on the Linux PC through Synergy.

Maybe it is a Synergy problem since using a mouse to control Visual Studio Code on the PC that the mouse directly connects to works just fine.

But maybe it is a Visual Studio Code problem since under the same condition, gedit and KWrite do not have the same problem.

**Comment by alexandrudima** [comment]
@EFanZh VSCode is built with Electron, which is built on top of Chromium. We have 100% the same source code running in all situations, so I don't believe it is a problem in our sources.

Perhaps you can reproduce the issue on Chromium when opening https://microsoft.github.io/monaco-editor/ . If that is the case maybe you can search for or create a new issue at https://bugs.chromium.org/p/chromium/issues/ and link to it here.
