### ISSUE TITLE
'||' isn't supported for the 'when' context value of explorer view?

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode#43407]
Steps to Reproduce:

I'd like to show customized explorer view with combined conditions, e.g. 
```json
"explorer": [
                {
                    "id": "testExplorer",
                    "name": "Test Explorer",
                    "when": "resourceExtname == '.javahtml' || resourceLangId == 'java'"
                }
            ]
```

However, when I used '||', the when condition totally does not work. Does context value 'when' support '||' or '&&' now? Or I used it wrongly? Thanks.

**Comment by isidorn** [comment]
This is not supported for context keys. There is already a feature request for this imho
fyi @alexandrudima
