### ISSUE TITLE
Change matching HTML tag when either is edited

### ISSUE THREAD

**Issue by s-sujan** [Microsoft/vscode#43402]
Currently using 1.20.0. This is a feature-request.

Can we have a feature where the matching opening/tag is changed automatically when either of them is modified? As in—

If I want to change `<h1>Hello!</h1>` to `<h4>Hello!</h4>`, editing one of the tags should suffice, and VSCode should modify the other accordingly.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag
