### ISSUE TITLE
Git 'discard change' needs two clicks to make the file disappear in source control explorer

### ISSUE THREAD

**Issue by DrakeXiang** [Microsoft/vscode#43409]
- VSCode Version: 1.20.0
- OS Version: windows 10.0.16299.192

Steps to Reproduce:

1.  Get a git repository and open the project in vscode
2.  Modify some files
3. Click 'discard changes' button in source control explorer. (Changes are indeed discarded)

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
This is to prevent accidental "discard changes".
