### ISSUE TITLE
SASS INDENTED Highlight Support Needed

### ISSUE THREAD

**Issue by rakletadmin** [Microsoft/vscode#43406]
Q: Do you support the indentation based Sass syntax (.sass) ?
A: No, but there are several extensions in the Marketplace supporting the indented flavor of Sass.

``THIS IS CRAZY. THERE ISN'T ANY EXTENSIONS FOR SASS INDENTED``

- VSCode Version: 15.6.6
- OS Version: Win10

Steps to Reproduce:

1. Simply try to write SASS indented version.
2. No highlight on variables, mixins and etc.
 
Does this issue occur when all extensions are disabled?: Yes

**Comment by duttaditya18** [comment]
This pisses me off as well. But this works pretty well : https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented

And adding another native Syntax Highlighting to vscode would be a pain to maintain.

**Comment by gercheq** [comment]
This doesn't work with Visual Studio Enterprise.

**Comment by erwinverdonk** [comment]
@gercheq Unfortunately for you this is not the repository for VS Enterprise.
