### ISSUE TITLE
Java syntax highlighting errors

### ISSUE THREAD

**Issue by H-C-H** [Microsoft/vscode#43414]
### Issue Type
Bug

### Description
The built-in Java Textmate grammar has several highlighting inconsistencies/errors.

- Variables/constants starting with a capital letter are scoped as `storage.type.java`
- Angle brackets are inconsistently scoped, either as
    - keyword.operator.comparison.java
    - keyword.operator.bitwise.java
    - punctuation.bracket.angle.java
- Fields are highlighted incorrectly/differently depending on access modifier
- See images below

![screen shot 2018-02-11 at 11 42 22](https://user-images.githubusercontent.com/31404215/36072494-c93b5820-0f20-11e8-85cd-bea9b6615360.png)

## Steps to reproduce:
1. Use built in Monokai color theme (or other colorful theme)
2. Set syntax to "Java"
3. Write _completely normal_ Java code or paste the following example code:
```Java
public class Main {
    // with/without access modifier:
    public
    Set<Map.Entry<K, V>> entrySet0;
    Set<Map.Entry<K, V>> entrySet1;

    public static void main(String[] args) {
        Set<Map.Entry<K, V>> entrySet0;
        Node<K, V> m = someNode;
        Node<K, V> first = (Node<K, V>) someValue;
    }

    public static void method() {
        final int MY_CONSTANT = 0;
        int a = MY_CONSTANT + 1;

        int A = 1, B = 2;
        boolean less = A < B;
    }
}
```

![screen shot 2018-02-11 at 11 43 23](https://user-images.githubusercontent.com/31404215/36072493-c9205dc2-0f20-11e8-922b-5326720179ee.png)
### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.16GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by H-C-H** [comment]
Here is the same code rendered in Sublime Text. Very different!

![screen shot 2018-02-12 at 09 14 43](https://user-images.githubusercontent.com/31404215/36087942-3edde264-0fd5-11e8-8a24-ba966ed251ae.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-java#127
