### ISSUE TITLE
A workspace compound configuration is not visible in the Debug dropdown

### ISSUE THREAD

**Issue by silkyfray** [Microsoft/vscode#43419]
- VSCode Version: 1.20.0 commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
- OS Version: Windows 10 x64

Does this issue occur when all extensions are disabled?: Yes

Description:
A workspace compound configuration is not visible in the Debug dropdown if the "configurations" array is not declared.

Steps to Reproduce:
1.  See attached images

Shows as expected.
![image](https://user-images.githubusercontent.com/2873559/36072809-6591d6de-0f1e-11e8-971c-54d3bc30323e.png)

Remove the configurations array and save the file. The compound launch is no longer visible.
![image](https://user-images.githubusercontent.com/2873559/36072847-0737a2f2-0f1f-11e8-964f-fa5c3df013a6.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/43079
