### ISSUE TITLE
Debugging protractor test with patched function causes test to crash 

### ISSUE THREAD

**Issue by gawicks** [Microsoft/vscode#43410]
- VSCode Version: 1.20.0
- OS Version: Windows 10 1709
- Works as intended in VSCode Version 1.19.3 
- Extensions are disabled?: Yes
- Node version: 8.9.4

[bug.zip](https://github.com/Microsoft/vscode/files/1714080/bug.zip)

The attached zip contains a project that the issue reproduces in. It's a minimal protractor-tsnode project with a single patched method. ts-node fails to find the patched method, and crashes under the debugger. Note that simply running the project with npm test works fine.

Steps to Reproduce:

1. Extract the attached zip file . 
2. Do an npm install
3. Start debugging (F5)
- Debugger crashes with protractor_1.browser.element(...).foo is not a function
trace: 
```
      - Failed: protractor_1.browser.element(...).foo is not a function
          at Object.<anonymous> (C:\Users\~\Desktop\bug\index.ts:11:41)
          at step (C:\Users\~\Desktop\bug\index.ts:32:23)
          at Object.next (C:\Users\~\Desktop\bug\index.ts:13:53)
          at C:\Users\~\Desktop\bug\index.ts:7:71
          at new Promise (<anonymous>)
          at __awaiter (C:\Users\~\Desktop\bug\index.ts:3:12)
          at UserContext.<anonymous> (C:\Users\~\Desktop\bug\index.ts:6:16)
          at new Promise (<anonymous>)
          at SimpleScheduler.promise (c:\Users\~\Desktop\bug\node_modules\selenium-webdriver\lib\promise.js:2242:12)
      From asynchronous test: 
      Error
          at Suite.<anonymous> (C:\Users\~\Desktop\bug\index.ts:6:5)
          at Object.<anonymous> (C:\Users\~\Desktop\bug\index.ts:5:1)
          at Module._compile (module.js:643:30)
          at Module.m._compile (C:\Users\~\Desktop\bug\node_modules\ts-node\src\index.ts:422:23)
          at Module._extensions..js (module.js:654:10)
          at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\~\Desktop\bug\node_modules\ts-node\src\index.ts:425:12)

```

**Comment by weinand** [comment]
@gawicks sorry, but from the stacktrace it appears that not the Debugger is crashing but your test. 
What version of node.js are you using?

**Comment by gawicks** [comment]
@weinand I'm on node 8.9.4. Yes you're right that its the test that crashes under the debugger. Sorry i could not make the proper distinction here.

The attached zip can help you re-create the issue. Let me know if you need more info.

**Comment by weinand** [comment]
I can reproduce the problem only on Windows.
If I remove the `${workspaceRoot}/` from the `"conf.js"` the test works fine.
```json
    {
        "type": "node",
         "request": "launch",
         "name": "Launch Program",
         "program": "${workspaceRoot}/node_modules/protractor/bin/protractor",
         "args": ["conf.js"],
         "sourceMaps": true,
         "preLaunchTask": "npm: update"
    }
```

**Comment by weinand** [comment]
@gawicks does the test work for you as well?

**Comment by gawicks** [comment]
Thanks for the quick response. I can confirm that this works.

**Comment by gawicks** [comment]
I'm happy with this workaround. But should I leave this bug open for you to investigate the regression?

**Comment by weinand** [comment]
Yes, leave it open. @roblourens should decide.

**Comment by gawicks** [comment]
@weinand Thanks.

**Comment by roblourens** [comment]
I think that @weinand's suggestion is the correct fix. If protractor doesn't like an absolute path here, the debugger can't do anything about that.

**Comment by gawicks** [comment]
@roblourens Any explanation as to why this reproduces only on windows and on >v1.19.3 ? Perhaps there is a path related change that's causing this to break.

**Comment by roblourens** [comment]
No, but that seems unlikely, vscode is just running the command as provided. It might break outside of the debugger if you just run the same command in the terminal.

**Comment by gawicks** [comment]
No it doesn't . 
Running `node node_modules\protractor\bin\protractor C:\Users\~\Desktop\bug\conf.js` (Absolute path) works fine. It's running under the debugger that's causing this.

Also let me re-iterate that this used to work fine before the new release.

**Comment by roblourens** [comment]
I spent some time trying it, and this is pretty weird. It works fine in the terminal, and you can also work around it with `"console": "integratedTerminal"`. But it fails when the debug adapter spawns the process, whether it's in debug mode or not. 

The difference between 1.19 and 1.20 is just the casing of the drive letter - `${workspaceRoot}` completed with a lowercase letter in 1.19 and uppercase in 1.20. So it works fine if I write in the absolute path with a lowercase letter in `args`. And it works in the terminal regardless of the path casing.

I wonder whether the command prompt in Windows does anything to normalize paths? I didn't think so but that would explain this.

**Comment by roblourens** [comment]
Is this still an issue? Given my last comment, I'm not sure what we would do to work around this on our end. We aren't going to give a certain drive letter casing just for this library, so I think it will have to be fixed on their end.
