### ISSUE TITLE
"net::ERR_FILE_NOT_FOUND" when loading explorer

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode#43412]
- VSCode Version: 1.20.0
- OS Version: Window 10

Steps to Reproduce:

when loading customized explorer view, toggle developer tools, it has error
"[vscode installation folder]/resources/app/out/vs/workbench/electron-browser/bootstrap/undefined net::ERR_FILE_NOT_FOUND"

the implementation of the `getTreeItem` method of `TreeDataProvider` might return `TreeItem` with undefined iconPath and command since the interface marks them as nullable, not sure whether this is related.

**Comment by sandy081** [comment]
@ansyral I am not able to reproduce this when I do not provide an `iconPath` and `command`. Can you please try again on latest (preferably insiders) and let me know if you see it yet?
