### ISSUE TITLE
Al abrir el terminal no se hace focus

### ISSUE THREAD

**Issue by DiegoSerra** [Microsoft/vscode#43418]
### Issue Type
Bug

### Description

Teniendo el terminal cerrado:

Ctrl + ñ
Escribir npm ... (npm se escribe en el archivo, no en el terminal)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Memory (System)|15.94GB (9.57GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
tslint|eg2|1.0.24
bootstrap4-vscode|the|3.0.0
vscode-todo-highlight|way|0.5.11
html-css-class-completion|Zig|1.16.2

</details>
Reproduces only with extensions

**Comment by egamma** [comment]
@DiegoSerra can you please report your issue in English.

**Comment by egamma** [comment]
Closing the issue, please reopen the issue with more information.
