### ISSUE TITLE
Arduino project (ino file) find all references not working

### ISSUE THREAD

**Issue by benchuk** [Microsoft/vscode#43426]
### Issue Type
Bug

### Description

go to definition is working (only after multiple installations and debugging)
find all in project works ok
find all references not working.
tried to remove  all extensions also did not help

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|7.92GB (2.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.14.6
platformio-ide|pla|0.12.1
debug|web|0.21.2

</details>
Reproduces only with extensions

**Comment by octref** [comment]
Report to cpptools

**Comment by benchuk** [comment]
This used to work but is no failing, on windows
It does work on mac
@octref will try
