### ISSUE TITLE
[loc] Request to add Urdu (ur) language to VS Code

### ISSUE THREAD

**Issue by ahmadawais** [Microsoft/vscode#43421]
Hey, Folks! 🙌

This is [Ahmad Awais](https://twitter.com/mrahmadawais/) — a regular core contributing developer for WordPress. I am the General Translation Editor and Locale Manager for [Urdu translation of WordPress](https://ahmadawais.com/urdu-wordpress/) — take a look at the [WordPress Urdu Team](https://make.wordpress.org/polyglots/teams/?locale=ur).

I along with [my team](https://WPCouple.com/team) will be willing to take part in this initiative for VSCode translation in Urdu.

- Translation language interested: `Urdu (ur)`
- Transifex username: `mrahmadawais`

#### Status
- I have requested the language addition.
- Signed up on Transifex
- Getting the team signed up at Transifex

---

Folks, if you are here to help translate VSCode in Urdu then vote this thread and comment with your [Transifex](https://www.transifex.com/) username.

Looking forward!

**Comment by MrSaqibAmeen** [comment]
Hey, 

I am interested in translating this awesome piece of software - VSCode - into Urdu. 💯
Signed up on Transifex, username: `mrsaqibameen`

Looking forward!

**Comment by danyeh** [comment]
Thank you for showing interest to contribute! Urdu (ur) has been enabled in Transifex for VS Code projects.
