### ISSUE TITLE
Syntax coloring in JSX changes when a destructured object preceding it in the same file is spread over more than one line.

### ISSUE THREAD

**Issue by anyong** [Microsoft/vscode#4342]
- VSCode Version: 0.10.12-insider
- OS Version: Win10

Steps to Reproduce:

1. Set file type to JavaScript React
2. Try this one:

```jsx
// Minimal example
class A {
    function foo () {
        var {a
            } = x;
        
        return (
            <div/>
        )
    }
}
```

Then add a comma after the a:

```jsx
var {a,
    } = x;
```

If you play around with the number of variables and commas, the highlighting on the JSX component will change drastically from one color scheme to another.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#128
