### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by okprogrammer** [Microsoft/vscode#43425]
I cound't  add any extension in the vs code. Even my friend also face same problem. When i surf on the internet about this problem where I see many people complaint about this."**THEY CAN'T ADD EXTENSION IN THE VS CODE IN WINDOW OPERATING SYSTEM**" while people work on Linux or mac they can add extension.#  I am working on window that's why i couldn't add extension.

**Comment by octref** [comment]
Can you give a bit more info (if possibly, with screenshots).

What's on your Extension Viewlet? What happens when you try to install an extension?
