### ISSUE TITLE
Create folder with parents when name has slashes

### ISSUE THREAD

**Issue by jgeorgeson** [Microsoft/vscode#43435]
### Issue Type
Feature Request

### Description

It's cumbersome to have to _MB3 > New Folder_  to for each directory create a each parent directory individually. It'd be great to be able to specify the full path in the folder name text field (such as `com/example/application/component` and Code will create the complete folder structure.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

**Comment by usernamehw** [comment]
Duplicate of #31305

**Comment by jgeorgeson** [comment]
Sorry, the _Help > Report Issue_ form didn't find that one. Will subscribe there.
