### ISSUE TITLE
Cannot open terminal with Ctrl + `

### ISSUE THREAD

**Issue by WangYu5818** [Microsoft/vscode#43433]
### Issue Type
Feature Request

### Description

使用vscode时，按Ctrl+` 终端打不开

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 6.1.7601

**Comment by octref** [comment]
Please use English to report issue.

Can you do Ctrl+Shift+P -> Open Keyboard Shortcuts -> Search for ``Ctrl ` `` and see what are the keybindings bound to it?

**Comment by liuzhenrain** [comment]
I encountered the same mistake,like this
![image](https://user-images.githubusercontent.com/6817052/36129774-ca99da5a-10a3-11e8-9589-7f3fcb5bb596.png)
And I'm not change the settings: "terminal.integrated.shell.windows"
![image](https://user-images.githubusercontent.com/6817052/36129800-e9c73b5c-10a3-11e8-8c5c-8f552d35249d.png)

VS Code Info
版本 1.20.0
提交 c63189deaa8e620f650cc28792b8f5f3363f2c5b
日期 2018-02-07T17:09:39.780Z
Shell 1.7.9
渲染器 58.0.3029.110
Node 7.9.0
架构 x64

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169
