### ISSUE TITLE
Selection Highlighting on Breakpoint Line

### ISSUE THREAD

**Issue by mattmcnabb** [Microsoft/vscode#43432]
When debugging, attempting to highlight text on the same line as a highlighted breakpoint, the highlight is not visible. This appears to happen only when using a light theme.

- VSCode Version: 1.20.0
- OS Version: Windows 10.0.16299.98
Please see [this issue](https://github.com/PowerShell/vscode-powershell/issues/1194) in the VSCode PowerShell extension repo.

**Comment by isidorn** [comment]
@mattmcnabb works fince for me. What theme are you using?
![screen shot 2018-02-14 at 11 05 18](https://user-images.githubusercontent.com/1926584/36198619-59c98288-1177-11e8-88cc-824444fad15c.png)

**Comment by bergmeister** [comment]
I have the problem that using the dark theme that the 2 colours (text selection and breakpoint highlighting of the line) are nearly indistinguishable. I am using the latest Insider build on WinServer 2012R2 with the PowerShell extension and default settings

**Comment by mattmcnabb** [comment]
@isidorn  so if I'm debugging in the PowerShell extension, notice that I get the line highlighted and also get a selection highlight on that same line:

![image](https://user-images.githubusercontent.com/6998507/36239250-0e1eae4e-11d6-11e8-81b6-8250efab2145.png)

Any idea what that element is? I can't seem to find how to theme that, and I'm guessing it needs to have some transparency.

**Comment by isidorn** [comment]
@mattmcnabb I added transparency to that color. You can try it out in monday's vscode insiders and let us know if the issue is fixed for you. Thanks for reporting!
