### ISSUE TITLE
In split screen mode, adding lines in one causes scroll position in other to be lost

### ISSUE THREAD

**Issue by donkeybonks** [Microsoft/vscode#43448]
Tested with version 1.14.2

Basically I like to write unit tests in split screen mode. Sometimes I have the same test file open in both sides for whatever reason it might be (perhaps referencing other similar tests).

When you add a line break or paste lines above the other view, your scroll position in the other view is 'moved up' a little and you have to adjust your scroll to get back to what you were looking at.

It would be really nice if scroll position was preserved.

**Comment by alexandrudima** [comment]
Duplicate of #46455
