### ISSUE TITLE
switch between split editor types stoped working 

### ISSUE THREAD

**Issue by odedpriva** [Microsoft/vscode#43444]
- VSCode Version:
```
$ code --version
1.20.0
c63189deaa8e620f650cc28792b8f5f3363f2c5b
x64
```
- OS Version:
```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.3 (17D47)
      Kernel Version: Darwin 17.4.0
```
Steps to Reproduce:

1. split window
2. using cmd+opt+1 has no affect. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@odedpriva I do not think we assign `cmd+opt+1` out of the box, what would you expect to happen?

**Comment by odedpriva** [comment]
This used to work ( I believe till I updated to latest but I'm not sure), 

I expect it switch between horizontal and vertical split.

**Comment by pet3r** [comment]
The default keybinding changed.

It is `shift+alt+0` for Linux.
Maybe `cmd+opt+0` for Mac.

**Comment by odedpriva** [comment]
working ... thanks.
