### ISSUE TITLE
TypeScript: import choices missing

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#43446]
vscode: 1.20.0

```ts
// index.ts
export * from './foo'

// foo.ts
export function foo() { return 'foo' }

// boo.ts

foo // suggests `import form '.'` and missing `import from './foo'`
```

This makes auto import practically not usable because it easily introduces cyclic dependency graph.

Also, `add import into existing import clause` is also gone (probably due to the same reason).

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21904
