### ISSUE TITLE
Extension host crashes over night

### ISSUE THREAD

**Issue by sahas-** [Microsoft/vscode#4344]
- VSCode Version:0.10.11
- OS Version:Mac 10.11.3

Steps to Reproduce:

1. Left vscode over night
2. Code --> Preferences --> Color Theme 

<img width="753" alt="screen shot 2016-03-16 at 8 10 03 pm" src="https://cloud.githubusercontent.com/assets/10361685/13833352/25892762-ebb3-11e5-8e5d-db34bee10b10.png">

This error does go away after restarting vscode once.

**Comment by bpasero** [comment]
@sahas- so you cannot reproduce if you do Code > Preferences > Color Theme after you restarted?

**Comment by bpasero** [comment]
To me this rather looks like the extension host crashing over night and the first action after the night was triggering the crash. 

@sahas- would be interesting to know for which workspace this happened and what kind of extensions you had installed?

**Comment by sahas-** [comment]
Here are my current extensions

<img width="594" alt="screen shot 2016-03-17 at 7 53 08 am" src="https://cloud.githubusercontent.com/assets/10361685/13846491/7450875c-ec15-11e5-98b7-c2a72317bb26.png">

**Comment by bpasero** [comment]
I suspect a leak on the extension host side, so we have to expand our leak testing to the extension host.

**Comment by bpasero** [comment]
@sahas- and please attach the workspace or pointers how to get there

**Comment by jrieken** [comment]
Also, please try to reproduce this without extensions enabled (--disableExtensions) so we know if it's on our side or an extension issue

**Comment by sahas-** [comment]
@bpasero - can you pls point me to some instructions to extract the workspace?
@jrieken  - its not reproducible now, with or without extensions. May be, I need to leave it over night and see..

**Comment by bpasero** [comment]
@sahas- the folder you open vs code with

**Comment by jrieken** [comment]
@sahas- I have made an extension that allows you to monitor heap usage and garbage collection. It's not yet in the gallery but there steps how to install it locally: https://github.com/jrieken/vscode-extheap

It would be of great help if you can install and check the `GC Stats` from time to time and also supply some heap snapshot of the extension host (esp. when men usage has grown)

**Comment by jrieken** [comment]
Assuming you are on a mac you can try unzipping and opening the vsix-file with VS Code.

[vscode-extheap-0.0.1.vsix.zip](https://github.com/Microsoft/vscode/files/178260/vscode-extheap-0.0.1.vsix.zip)

**Comment by sahas-** [comment]
It crashed again this morning 

<img width="895" alt="screen shot 2016-03-18 at 7 24 17 am" src="https://cloud.githubusercontent.com/assets/10361685/13877693/7f19289a-ecda-11e5-884a-13f65c371066.png">

workspace:
https://gist.github.com/sahas-/88c6cafd675e699d66d4

I've enabled this new extension too (after restarting vscode)

**Comment by jrieken** [comment]
@sahas- Did the heap readings provide any interesting insights so far?

**Comment by sahas-** [comment]
Haven't seen that crash after but here is what I got this morning..


garbage collected
============================================================
{
	"pause": 4160290,
	"pauseMS": 4,
	"gctype": 2,
	"before": {
		"totalHeapSize": 38409232,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 28204288,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 38409232
	},
	"after": {
		"totalHeapSize": 39441168,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 22390312,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 39441168
	},
	"diff": {
		"totalHeapSize": 1031936,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -5813976,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 1031936
	}
}
garbage collected
============================================================
{
	"pause": 2464733,
	"pauseMS": 2,
	"gctype": 2,
	"before": {
		"totalHeapSize": 35313424,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 24027496,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 35313424
	},
	"after": {
		"totalHeapSize": 37377296,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 22625192,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 37377296
	},
	"diff": {
		"totalHeapSize": 2063872,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -1402304,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 2063872
	}
}
garbage collected
============================================================
{
	"pause": 364196,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 29121808,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23460720,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 29121808
	},
	"after": {
		"totalHeapSize": 29121808,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 22711232,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 29121808
	},
	"diff": {
		"totalHeapSize": 0,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -749488,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 0
	}
}
garbage collected
============================================================
{
	"pause": 313037,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 26042640,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23674536,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 26042640
	},
	"after": {
		"totalHeapSize": 27057936,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 22818336,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 27057936
	},
	"diff": {
		"totalHeapSize": 1015296,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -856200,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 1015296
	}
}
garbage collected
============================================================
{
	"pause": 330872,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 26042640,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23760072,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 26042640
	},
	"after": {
		"totalHeapSize": 27057936,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 22915440,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 27057936
	},
	"diff": {
		"totalHeapSize": 1015296,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -844632,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 1015296
	}
}
garbage collected
============================================================
{
	"pause": 283504,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 26042640,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23856608,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 26042640
	},
	"after": {
		"totalHeapSize": 27057936,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23011456,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 27057936
	},
	"diff": {
		"totalHeapSize": 1015296,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -845152,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 1015296
	}
}
garbage collected
============================================================
{
	"pause": 364659,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 26042640,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23972304,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 26042640
	},
	"after": {
		"totalHeapSize": 27057936,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23127648,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 27057936
	},
	"diff": {
		"totalHeapSize": 1015296,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -844656,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 1015296
	}
}
garbage collected
============================================================
{
	"pause": 316962,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 26042640,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 24074632,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 26042640
	},
	"after": {
		"totalHeapSize": 27057936,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23232424,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 27057936
	},
	"diff": {
		"totalHeapSize": 1015296,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -842208,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 1015296
	}
}
garbage collected
============================================================
{
	"pause": 267838,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 29121808,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 24177896,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 29121808
	},
	"after": {
		"totalHeapSize": 29121808,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23338696,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 29121808
	},
	"diff": {
		"totalHeapSize": 0,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -839200,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 0
	}
}
garbage collected
============================================================
{
	"pause": 421694,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 26042640,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 24326144,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 26042640
	},
	"after": {
		"totalHeapSize": 28089872,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23475864,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 28089872
	},
	"diff": {
		"totalHeapSize": 2047232,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -850280,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 2047232
	}
}
garbage collected
============================================================
{
	"pause": 288071,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 27074576,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 24423208,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 27074576
	},
	"after": {
		"totalHeapSize": 28089872,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23577768,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 28089872
	},
	"diff": {
		"totalHeapSize": 1015296,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -845440,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 1015296
	}
}
garbage collected
============================================================
{
	"pause": 259141,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 27074576,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 24517920,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 27074576
	},
	"after": {
		"totalHeapSize": 28089872,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23672456,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 28089872
	},
	"diff": {
		"totalHeapSize": 1015296,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -845464,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 1015296
	}
}
garbage collected
============================================================
{
	"pause": 208300,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 28089872,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 24627376,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 28089872
	},
	"after": {
		"totalHeapSize": 28089872,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23778640,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 28089872
	},
	"diff": {
		"totalHeapSize": 0,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -848736,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 0
	}
}
garbage collected
============================================================
{
	"pause": 220852,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 28089872,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 24590544,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 28089872
	},
	"after": {
		"totalHeapSize": 28089872,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23865624,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 28089872
	},
	"diff": {
		"totalHeapSize": 0,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -724920,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 0
	}
}
garbage collected
============================================================
{
	"pause": 133848,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 30153744,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23865624,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 30153744
	},
	"after": {
		"totalHeapSize": 30153744,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 23865624,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 30153744
	},
	"diff": {
		"totalHeapSize": 0,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": 0,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 0
	}
}
garbage collected
============================================================
{
	"pause": 620660,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 30153744,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 25909848,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 30153744
	},
	"after": {
		"totalHeapSize": 30153744,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 25908920,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 30153744
	},
	"diff": {
		"totalHeapSize": 0,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -928,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 0
	}
}
garbage collected
============================================================
{
	"pause": 1187496,
	"pauseMS": 1,
	"gctype": 2,
	"before": {
		"totalHeapSize": 34281488,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 25908920,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 34281488
	},
	"after": {
		"totalHeapSize": 36345360,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 25889264,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 36345360
	},
	"diff": {
		"totalHeapSize": 2063872,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -19656,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 2063872
	}
}
garbage collected
============================================================
{
	"pause": 8468,
	"pauseMS": 0,
	"gctype": 2,
	"before": {
		"totalHeapSize": 37463568,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 29140016,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 37463568
	},
	"after": {
		"totalHeapSize": 37463568,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 29140016,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 37463568
	},
	"diff": {
		"totalHeapSize": 0,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": 0,
		"heapSizeLimit": 0,
		"totalPhysicalSize": 0
	}
}
garbage collected
============================================================
{
	"pause": 4323699,
	"pauseMS": 4,
	"gctype": 2,
	"before": {
		"totalHeapSize": 37463568,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 29898728,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 37463568
	},
	"after": {
		"totalHeapSize": 35268112,
		"totalHeapExecutableSize": 9437184,
		"usedHeapSize": 21253376,
		"heapSizeLimit": 1535115264,
		"totalPhysicalSize": 35268112
	},
	"diff": {
		"totalHeapSize": -2195456,
		"totalHeapExecutableSize": 0,
		"usedHeapSize": -8645352,
		"heapSizeLimit": 0,
		"totalPhysicalSize": -2195456
	}
}

**Comment by jrieken** [comment]
looks like there is plenty of heap-space left

**Comment by jrieken** [comment]
We are using a native nodejs module that gives us support for weak-references. Over some intense debug sessions in the last days we have learnt that this module can crash the node process, esp later version of node/v8 show this (https://groups.google.com/forum/m/#!topic/v8-dev/xBlM2iyuPyY)

With https://github.com/Microsoft/vscode/commit/7c4c828dcbf46e243a4c523b57873394e7deac6a we do not use this module any more

**Comment by isidorn** [comment]
Adding a verified label since we no longer use that module, no other way to verify this

**Comment by a11smiles** [comment]
@bpasero @jrieken Guys, I just installed code-1.6.1-1476373175.el7.x86_64.rpm on CentOS 7.  I'm now getting the same error almost immediately when I start Code.  Additionally, _none_ of my extensions currently work.

```
Extension host terminated unexpectedly. Please reload the window to recover.
connect EACCESS /tmp/Code-1c52fa-1.6.1-shared.sock
```
