### ISSUE TITLE
Roboto Mono Regular Font does not display

### ISSUE THREAD

**Issue by tillyboy** [Microsoft/vscode#43441]
### Issue Type
Bug

### Description

I cannot use the Roboto Mono Regular with VS Code, albeit the font being properly installed and working in any other part of the OS so far. Medium and Light weights work just fine.

Since Roboto Mono Regular is set as default mono font of my OS, I also tried

    "editor.fontFamily": "'Roboto Mono Regular', 'monospace', monospace",

in my config. It then falls back to Hack somehow (which is the out-of-the-box mono font for my distro).

Issue is reproducible with extensions disabled and config unaltered.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.15.0-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (8 x 1720)|
|Load (avg)|1, 1, 1|
|Memory (System)|11.73GB (7.62GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|0.24.0
vscode-eslint|dba|1.4.5
auto-close-tag|for|0.5.5
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
Ruby|reb|0.16.0
vscode-icons|rob|7.19.0
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by octref** [comment]
From Google Fonts it seems the correct value is `Roboto Mono` (no regular).

![image](https://user-images.githubusercontent.com/4033249/36124477-06156ecc-1005-11e8-8d8a-7d3fbcac9de0.png)
