### ISSUE TITLE
TextContentProvider not loading properly 

### ISSUE THREAD

**Issue by kingerking** [Microsoft/vscode#43455]
Am I trying to run a React application from within a TextContentProvider. I successfully got a simple hello world HTML sample working but cant seems to get a React application loaded. i read on the website about the content security policy and put this in my head tag of my react application.
```
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src *; style-src 'self'; script-src *;">
```
This still did nothing.

**Comment by mjbvz** [comment]
Run the `Developer: Webview tools` command to debug the webview. What errors do you see?

**Comment by kingerking** [comment]
In the web browser there are no errors but in the review tools it gives me a
```
main.c17080f1.css Failed to load resource: net:: ERR_FILE_NOT_FOUND
```
This is while running an express server in the extension. I get the same error when simply grabbing the *index.html* with node's *fs* module.

**Comment by kingerking** [comment]
Update: So I tried using [inliner](https://npmjs.com/package/inliner) to compile everything into a single HTML file. Now I get a resource not available Error dialog in vs code. The same dialog appears when trying to load Webview tools while loading the single HTML file.

**Comment by mjbvz** [comment]
Your extension needs to use absolute `file://` paths to all its webview resources. Take a look at what the markdown preview does to load its webview scripts for example: https://github.com/Microsoft/vscode/blob/bdcc2be7d6b1d7dded0e31fc1345f3944416c5ae/extensions/markdown/src/features/previewContentProvider.ts#L164

**Comment by kingerking** [comment]
That worked! thank you.
