### ISSUE TITLE
Dock Tabs to Debugger Tray

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#43454]
I would like the option to dock an arbitrary editor, in this case; tabs, into other trays specifically the debugger tray.

OS - Windows10 (1709)
VS Code - 1.19.2

**Comment by bpasero** [comment]
@SheepDomination can you explain how that would look like or work? You mean to move an editor into the debug side bar?

**Comment by SheepDomination** [comment]
Move a tab into the pane, which contains; console, terminal etc.  Let me know if more info is needed.
