### ISSUE TITLE
WATCH expression removed when editing text

### ISSUE THREAD

**Issue by ak99372** [Microsoft/vscode#43453]
- VSCode Version: 1.20
- OS Version: Win10

Steps to Reproduce:

1. Start debugging and place new expression into WATCH
2. Right click (or double click) to **Edit** the expression
3. Select/Highlight portion of the text of the expression
4. Press [Delete] to remove highlighted portion of the expression

**Expected behavior:**
Highlighted portion of the text to be erased, remaining text of the expression and expression itself to remain in the WATCH.

**Actual behavior:**
The whole expression is removed from the watch.

Note: I understand that I could use [backspace] key instead, however editing watch expression text should scope edit to the text of the expression. Also it should be more consistent with behavior of Watch from other editors (like Visual Studio, IntelliJ...etc)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by cristi-neagu** [comment]
I can confirm this. You don't need to select any text. As long as the cursor is in the watch expression, pressing `Delete` will make it disappear. The watch window also grays out.

**Comment by isidorn** [comment]
This is fixed in latest vscode insiders
