### ISSUE TITLE
unexpected trap bluescreen

### ISSUE THREAD

**Issue by necoengenheiro** [Microsoft/vscode#43452]
### Issue Type
Bug

### Description

Hi

When keypress ctrl-x vscode throw bluescreen exception unexpected trap

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|Memory (System)|5.88GB (2.79GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.2.7
debugger-for-chrome|msj|4.1.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by egamma** [comment]
@necoengenheiro is there anything special when you press ctrl-x? Can you always reproduce the problem? You indicate that this problem only happens with extensions, can you narrow down which extension is causing the problem.
