### ISSUE TITLE
spdlog.node lagging the vscode

### ISSUE THREAD

**Issue by AnnAngela** [Microsoft/vscode#43456]
### Issue Type
Bug

### Description

While using the vscode, I suddenly found out that the CPU Usage was full, then I checked the proccesses and found out that the vscode proccess took 70% CPU usage. Then I opened the thread list of that proccess, there was some threads using 20% CPU which its "Start Address" included "spdlog.node". After killing the threads, the CPU usage went low and nothing else happened.
In the first few times I did not take this seriously. But they came out tens of times after updating to 1.20.0, and made me very uncomfortable. I tried to reproduce the problem seriously but failed. But inadvertent operation can successfully reproduce that. Please help me to figure out the issue, and forgive my poor English.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|Memory (System)|7.90GB (3.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled
Reproduces without extensions

**Comment by joaomoreno** [comment]
> I tried to reproduce the problem seriously but failed. But inadvertent operation can successfully reproduce that.

I do not understand if you still have this problem, or if it just happens rarely.
