### ISSUE TITLE
Text selection bug in PowerShell editor for Edge browser

### ISSUE THREAD

**Issue by stasku** [Microsoft/vscode#4345]
- VSCode Version: Unknown (whatever is used by extensions in Azure Portal at https://portal.azure.com)
- OS Version: Windows 10 Enterprise build 14257.rs1_release.160131-1800/

Originally reported by customers of Azure Automation extension of Azure Portal here: https://feedback.azure.com/forums/246290/suggestions/12296892

Steps to Reproduce (as stated by customers):

(User 1)
When editing a runbook and trying to select a single line of text, I cannot select all of the text and end of the selection jumps around. You can reproduce easily if the line is a comment and start with a # symbol.

(User 2)
Also: If the line does not have a space at the end, and the last character is part of a word (ie, not a paren/bracket), the cursor will have its position set to just after the first character of the word. 

For $variable, that means after '$' 
For $variable.property, that means after 'p'

TBH, I was almost convinced this was simply and issue in Edge causing problems, vs the editor. 
Because for instance, in many multi-line text editors (like this one), sometimes when trying to navigate up with the arrow key, it stops moving up at the beginning of a paragraph just after a line break that was created with **Enter** (as opposed to **Shift+Enter**, oddly enough).

**Comment by alexandrudima** [comment]
Dup of #2802

We have fixed this and have a new editor version with the fix. Details at https://opentools.azurewebsites.net/
