### ISSUE TITLE
`Cannot read property 'path' of undefined` error when TreeItem has empty label

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode#43466]
- VSCode Version: 1.20.0
- OS Version: Windows10

I have a customized explorer view to show the layout of tree structure.  And if  `TreeItem` contains children whose label is empty, when selecting the node to expand its children, vscode pop out error "Cannot read property 'path' of undefined". This used to work before 1.20.0, any idea of the error? Thanks.

The detailed stacktrace is as below:

![image](https://user-images.githubusercontent.com/1982828/36084032-00a59324-0ff4-11e8-962f-4ca80c040e34.png)

**Comment by Tyriar** [comment]
Verified via code review
