### ISSUE TITLE
Tab dosen't work

### ISSUE THREAD

**Issue by Yi-yi** [Microsoft/vscode#43460]
Well, I mean the Tab key works as before. Thank you. It's Ok to close the issue now.
-----------------------------------------------------------------------------------------------------------
Sorry, the `tab` returns. I just re-open vs code and it returns. Thanks! 
------------------------------------------------------------------------------------------------------------
I try to use `tab` as a hotkey and cancel it after I find it doesn't fit my needs.  But now the `tab` just doesn't work. However, in the `keyboard shortcut`, there is no user-defined hotkey using `tab`! As I don't know how to reset to default,  I just can't use `tab` anymore.
![image](https://user-images.githubusercontent.com/12591699/36083200-3e276456-1004-11e8-8523-3c4f2337f75e.png)

![image](https://user-images.githubusercontent.com/12591699/36083274-cf59d620-1004-11e8-9c51-328b9d464314.png)

**Comment by ramya-rao-a** [comment]
> I just re-open vs code and it returns. 

Can add more details? What do you mean by "it returns" ?

>  I try to use tab as a hotkey and cancel it after I find it doesn't fit my needs.

What do you use the tab as a hotkey for?

**Comment by icewind7030** [comment]
I faced this bug quite often, you can recover the tab bar by changing the user setting with this: 
`"workbench.editor.showTabs": true`

**Comment by ramya-rao-a** [comment]
@icewind7030 I think @Yi-yi is referring to tab key and not the editor tabs

**Comment by icewind7030** [comment]
@ramya-rao-a oh, sorry!
