### ISSUE TITLE
Conflicting default key binding

### ISSUE THREAD

**Issue by kanitw** [Microsoft/vscode#4346]
- VSCode Version: 0.10.11
- OS Version: Mac OSX

Steps to Reproduce:

1.   Code > Preference > Keyboard Shortcut
2.  Search for  `"shift+alt+left"`  and `"shift+alt+right"`

You'll find two occurences of them:

```
{ "key": "shift+alt+left",        "command": "cursorWordLeftSelect",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+right",       "command": "cursorWordRightSelect",
                                     "when": "editorTextFocus" },
```

```
{ "key": "shift+alt+left",        "command": "workbench.files.action.openPreviousWorkingFile" },
{ "key": "shift+alt+right",       "command": "workbench.files.action.openNextWorkingFile" },
```

The latter group overrides the former.   However, IMHO, `cursorWordLeftSelect` is the right one because that's Mac's default behavior which works in every application.  It's kinda weird to declare specific shortcut that overrides OS-wide behavior.

**Comment by bpasero** [comment]
I do not see this conflict on master so I guess it was being taken care of already.

**Comment by alexandrudima** [comment]
@jrieken Can you pls try this on a mac, just open dev tools once to see if the warnings appear
