### ISSUE TITLE
[css] Redundant css suggestion for color

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#43464]
- VSCode Version: Any
- OS Version: Any

Steps to Reproduce:

1. Use the below content and trigger suggestions at the end of the property value
```
.foo {
   color: #123
}
```
2. The suggestion list has 2 entries. 1 from emmet, and the other from the css extension repeating the value that is already typed.

<img width="685" alt="screen shot 2018-02-11 at 8 25 55 pm" src="https://user-images.githubusercontent.com/16890566/36083667-cdf71266-0f69-11e8-8695-cda7b9be3385.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by praveenpuglia** [comment]
Is this part of the css-language-service?

**Comment by aeschli** [comment]
@praveenpuglia Yes, but it's ok to have the issue here.

**Comment by octref** [comment]
@ramya-rao-a What are you asking for?
Suggesting `#123` is working as expected from css. If you want exact match to come before others there are issue for it but I can't find.

**Comment by ramya-rao-a** [comment]
@octref Why do we even suggest #123 in this case? It doesnt add any value.

**Comment by octref** [comment]
@ramya-rao-a Well just found out I was the guy that opened the exact issue: https://github.com/Microsoft/vscode/issues/21362

**Comment by aeschli** [comment]
IMO @ramya-rao-a is valid here.
If there's a known set of values for a css property, e.g. for `display`, we should show each value as a proposal.
In this case, we guessed possible values by looking at other locations. When doing that we should ignore the current value. If some other location has that value, then, ok.
