### ISSUE TITLE
High CPU consumption of the extension host (was In the editor keyboard keys failure)

### ISSUE THREAD

**Issue by LiuCaiHe** [Microsoft/vscode#43468]
### Issue Type
Performance Issue

### Description

In the editor letters, numbers, symbol keyboard all invalid

Restart the editor for some time as well

Repeated so ...

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.97GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

|pid|CPU|Memory (MB)|Name|
|---|---|---|---|
|805|33|131|code main|
|806|6|33|-- gpu-process|
|807|7|360|-- window (Untitled-1 — czb-fleet)|
|887|100|115|---- extensionHost|
|1010|0|82|------ electron_node server.js |
|1017|0|33|------ electron_node server.js |
|1019|0|147|------ electron_node electronForkStart.js tsserver.js |
|1026|0|49|-------- electron_node typingsInstaller.js tsserver.js typesMap.js |
|1023|0|33|------ electron_node server.js |
|1040|0|164|------ electron_node vueServerMain.js |
|1230|0|33|------ electron_node jsonServerMain.js |
|1294|0|33|------ electron_node htmlServerMain.js |
|888|0|33|---- watcherService|
|891|0|33|---- terminal|
|892|0|0|------ /bin/zsh -l|
|986|0|16|---- searchService|
|1760|0|33|---- terminal|
|1761|0|0|------ /bin/zsh -l|
|808|4|82|-- shared-process|
|2859|70|82|-- shared-process|
|2860|0|0|-- /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=|

</details><details>
<summary>Workspace Info</summary>

```
|  Window (Untitled-1 — czb-fleet)
|    Folder (czb-fleet): 90 files
|      File types: js(40) vue(13) gz(7) DS_Store(6) svg(3) json(2) png(2)
|                  html(2) css(2) ttf(2)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
vs-treeview|DaG|2.0.3
vscode-markdownlint|Dav|0.13.0
beautify|Hoo|1.3.0
crane|Hvy|0.3.8
output-colorizer|IBM|0.1.2
TurboJavaScript|Ice|0.1.2
format-indent|Kas|1.3.0
vscode-docker|Pet|0.0.24
jsx|Twe|0.0.1
html-snippets|abu|0.2.1
vscode-database|baj|1.4.1
stylus|buz|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.5
vscode-dash|dee|1.8.0
wpy-beautify|doi|2.0.10
githistory|don|0.4.0
Vue2|duc|0.1.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.0.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.12.1
auto-rename-tag|for|0.0.15
code-runner|for|0.8.7
mdmath|goe|2.1.0
vscode-nginx-conf-hint|han|0.0.4
vscode-emacs|hir|0.1.1
docthis|joe|0.6.0
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
codeacejumper|luc|1.1.5
prettify-json|moh|0.0.3
mssql|ms-|1.3.0
python|ms-|2018.1.0
azure-account|ms-|0.3.0
vetur|oct|0.11.7
vuehelper|oys|0.1.0
vscode-css-peek|pra|2.1.0
vscode-wechat|qin|0.0.6
grammarkdown-language|rbu|0.4.3
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
vue|sea|0.4.2
keyboard-scroll|sel|0.1.0
vscode-nginx|sha|0.5.0
addDocComments|ste|0.0.8
language-stylus|sys|1.8.0
vscode-babel-repl|t-s|0.1.2
vscode-gulp|tan|0.0.4
python|tht|0.2.3
es-quotes|vil|0.2.6
gitblame|wad|2.2.0
JavaScriptSnippets|xab|1.5.0

(4 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by egamma** [comment]
@LiuCaiHe to find out which vs Code is causing the issue can you please run code --status when the problem occurs and attach the output.

**Comment by LiuCaiHe** [comment]
@egamma TKS

**Comment by egamma** [comment]
@LiuCaiHe  just curious, could you narrow down which extension has caused the slow down?

**Comment by egamma** [comment]
@LiuCaiHe thanks for the information.

@formulahendry fyi a user reported slow down when using your extension. Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions for how to profile the running extension.

**Comment by formulahendry** [comment]
Thanks @egamma for the info!
