### ISSUE TITLE
GDB error

### ISSUE THREAD

**Issue by SpawnTree** [Microsoft/vscode#43472]
### Issue Type
Bug

### Description

The app crashes when debuging c++. GDB cannot find any *.out file even though the file is present in the $MAIN_DIR. 

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.13.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|Load (avg)|1, 1, 0|
|Memory (System)|15.63GB (7.96GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-markdownlint|Dav|0.13.0
z80-asm|Ima|0.0.2
llvm|RRe|0.0.1
code-gnu-global|aus|0.2.2
language-gas-x86|bas|0.0.1
arm|dan|0.1.2
githistory|don|0.4.0
easy68k|dsi|0.0.2
gitlens|eam|8.0.0
git-project-manager|fel|1.4.0
mips|kda|0.0.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.6
merlin32|oli|1.0.0
beeb-vsc|sim|0.0.6
pyz80|sim|1.1.1
m68k|ste|0.0.1
kickassembler|tom|0.0.2
scrawl|tra|0.0.2

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Please file this issue against the cpptools extension

**Comment by SpawnTree** [comment]
Thanks for the suggestions. I have already fixed the problem.
