### ISSUE TITLE
 Cannot read property 'filter' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43473]
Issue Id: <b>322d28a7-2d74-fbdd-1bbb-b7e4864bca57</b><br /><br />*Versions* <br />- 1.20.0<br />*Stack* <br />TypeError: Cannot read property 'filter' of null<br />[/vs/workbench/browser/parts/views/treeView.ts#L400:50 (filter)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/browser/parts/views/treeView.ts#L400:50 (filter))<br />[/vs/workbench/browser/parts/views/treeView.ts#L378:61 (hasToAlignWithTwisty)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/browser/parts/views/treeView.ts#L378:61 (hasToAlignWithTwisty))<br />[/vs/workbench/browser/parts/views/treeView.ts#L373:7 (alignByTheme)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/browser/parts/views/treeView.ts#L373:7 (alignByTheme))<br />[/vs/workbench/browser/parts/views/treeView.ts#L349:23 (align)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/browser/parts/views/treeView.ts#L349:23 (align))<br />[/vs/base/parts/tree/browser/treeView.ts#L253:25 (renderElement)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeView.ts#L253:25 (renderElement))<br />[/vs/base/parts/tree/browser/treeView.ts#L1111:7 (render)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeView.ts#L1111:7 (render))<br />[/vs/base/parts/tree/browser/treeView.ts#L1099:7 (refreshViewItem)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeView.ts#L1099:7 (refreshViewItem))<br />[/vs/base/parts/tree/browser/treeViewModel.ts#L159:8 (onRefreshItem)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeViewModel.ts#L159:8 (onRefreshItem))<br />[/vs/base/parts/tree/browser/treeViewModel.ts#L134:7 (onRefreshItems)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeViewModel.ts#L134:7 (onRefreshItems))<br />[/vs/base/parts/tree/browser/treeView.ts#L964:7 (onRefreshItemSet)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeView.ts#L964:7 (onRefreshItemSet))<br />

**Comment by bpasero** [comment]
@sandy081 maybe a candidate, it is a top crash in telemetry

**Comment by sandy081** [comment]
Theoretically this should not happen as siblings of an element cannot be null as the result should contain at-least itself. 

But, I see this is happening in the product. I do not think of steps to reproduce this, may be timing issue in the tree. Will try to get to this.

Moreover, I have not yet seen any issues filed against custom views related to this. I would definitely consider this as a candidate if I see/get to the real impact.

**Comment by sandy081** [comment]
This got fixed by the changes from #28974

**Comment by sandy081** [comment]
I am removing the bug label to remove it from verification list as there are no steps to reproduce.
