### ISSUE TITLE
[C#] Intellisense for the common operations are not user friendly (or irrelevant) and not displaying in correct order.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4347]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:

1. Launch app and open any folder which contains C# files.
2. Open any .cs file and verify all the recommended extensions are installed to get intellisense.
3. Try to add some code for File IO operation without adding any namespace for IO operation. Like:
  public GlobalIntakeToolTokenCache(string userId)
        {
          File
        }

4. Use intellisens to fix error.
5. Verify all the available options and compare them with visual studio.
![visualstudio-vscode](https://cloud.githubusercontent.com/assets/17735796/13836467/0c967b18-ebbf-11e5-9fca-c6269da3d9e5.png)

Actual:
1  The order of the suggestions in the list are not displaying according to user preference. In my case I am expecting It should ask for adding the namespace System.IO.
2.  When I selected second option form the list "Create field" then it is added a File variable and didn't fix the issue.
3. When I selected the forth option from the list "Create property" then it is added property but didn't fix the issue.
4. When I selected the fifth options "Declare local variable then it is creating a new variable with var keyword and considering my declare type as a class File. It looks like:   var file = File;

Expected: System should be smart enough to display the common actions first. Like in my case when I type a Keyword File then my intension is to use C# inbuilt APIs.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#99
