### ISSUE TITLE
 Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43478]
Issue Id: <b>0cfb9ada-3213-616c-8263-d5cc847cde76</b><br /><br />*Versions* <br />- 1.20.0<br />-  f9398645d1d624538708eeebf96e6fdeb546f5d7<br />*Stack* <br />TypeError: Cannot read property 'top' of undefined<br />[/vs/base/parts/tree/browser/treeViewModel.ts#L156:12 (top)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeViewModel.ts#L156:12 (top))<br />[/vs/base/parts/tree/browser/treeViewModel.ts#L134:7 (onRefreshItems)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeViewModel.ts#L134:7 (onRefreshItems))<br />[/vs/base/parts/tree/browser/treeView.ts#L964:7 (onRefreshItemSet)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeView.ts#L964:7 (onRefreshItemSet))<br />[/vs/base/parts/tree/browser/treeView.ts#L960:7 (onItemsRefresh)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeView.ts#L960:7 (onItemsRefresh))<br />[/vs/base/common/event.ts#L144:18 (call)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/event.ts#L144:18 (call))<br />[/vs/base/common/event.ts#L144:18 (call)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/event.ts#L144:18 (call))<br />[/vs/base/common/event.ts#L212:41 (fire)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/event.ts#L212:41 (fire))<br />[/vs/base/common/event.ts#L142:15 (call)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/event.ts#L142:15 (call))<br />[/vs/base/parts/tree/browser/treeModel.ts#L527:21 (fire)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeModel.ts#L527:21 (fire))<br />[/vs/base/parts/tree/browser/treeModel.ts#L507:19 (doRefresh)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/parts/tree/browser/treeModel.ts#L507:19 (doRefresh))<br />

**Comment by sandy081** [comment]
Stack is not having information about the tree/view that is causing this.

@joaomoreno is this something to be fixed in tree?

**Comment by joaomoreno** [comment]
We'd need to see which tree it really is. 😢

**Comment by sandy081** [comment]
Closing this as there is no enough information to fix it.
