### ISSUE TITLE
Classes in CamelCase have a different color than other classes

### ISSUE THREAD

**Issue by chimit** [Microsoft/vscode#43483]
- VSCode Version: 1.20.0 (1.20.0)
- OS Version: macOS High Sierra 10.13.3 (17D47)

![camelcasecolorbug](https://user-images.githubusercontent.com/839349/36087603-386de95e-100e-11e8-8b73-47432a0e816c.png)

This affects all color themes.

**Comment by octref** [comment]
What's the language and can you try Cmd+Shift+P -> Inspect TM Scopes -> Move over both `Something` and `SomethingElse` -> Show us screenshots of the values?

**Comment by chimit** [comment]
It's PHP.

![2018-02-13 16 48 53](https://user-images.githubusercontent.com/839349/36140878-cfddc6cc-10dd-11e8-88e2-26572007743e.png)
![2018-02-13 16 49 00](https://user-images.githubusercontent.com/839349/36140879-d0057ac8-10dd-11e8-9aa7-40fd837bee84.png)

**Comment by roblourens** [comment]
Reproes in vscode, not in Atom.
