### ISSUE TITLE
[Terminal - Windows] Ctrl+C doesn't kill ngrok in Powershell

### ISSUE THREAD

**Issue by veleek** [Microsoft/vscode#43482]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
githistory|don|0.4.0
xml|Dot|1.9.2
code-sync|gol|2.5.3
vscode-auto-open-markdown-preview|hnw|0.0.4
prettify-json|moh|0.0.3
mssql|ms-|1.3.0
python|ms-|2018.1.0
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.1.0
vscode-icons|rob|7.19.0

---

Steps to Reproduce:

1. Launch integrated terminal (Powershell)
2. Start ngrok (e.g. `ngrok http 1337`)
3. View ngrok output
4. Press Ctrl+C to kill ngrok

Expected:
ngrok exits

Actual:
ngrok continues running.

Reproduces without extensions: Yes

I have tried the workaround suggested in #28635 and removed `terminal.copySelection` from my settings, but it still doesn't work.

```
"terminal.integrated.commandsToSkipShell": [
        "editor.action.toggleTabFocusMode",
        <snip>
        "workbench.action.terminal.clear",
        //"workbench.action.terminal.copySelection",
        "workbench.action.terminal.deleteWordLeft",
        <snip>
        "workbench.action.togglePanel"
    ]
```

**Comment by Tyriar** [comment]
Tracking ctrl+c issues on Windows in https://github.com/Tyriar/node-pty/issues/7
