### ISSUE TITLE
Pinned extension readme is closed when switching to file explorer

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#43488]
### Issue Type
Bug

### Description

1. Go to the extensions tab
2. Select one of your extensions
3. Right click on the readme tab and select "keep open"
4. Switch to file explorer

The extension readme is not open anymore.
Another observation: When switching to a source file and back, the scroll position within the readme is not restored.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (ef42990520a856451ba5ad6fa1d299b0e0c185a2, 2018-02-12T05:14:21.574Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|Memory (System)|7.88GB (3.15GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces only with extensions

**Comment by sandy081** [comment]
@tsalinger I do not see `keep open` command on the tab. Not sure if you have any extensions that contribute this command?

Extension editors are open only when Extension viewlet is open. 

Not retaining the scroll position is already reported https://github.com/Microsoft/vscode/issues/27498

**Comment by tsalinger** [comment]
Ok, I close this issue since this is the intended behavior.

The `keep open` command is not visible if you have set `"workbench.editor.enablePreview": false`.
