### ISSUE TITLE
Code completion missing entries in VSCode 1.20

### ISSUE THREAD

**Issue by tobiasviehweger** [Microsoft/vscode#43489]
- VSCode Version: 1.20.0
- OS Version: Windows 10 Pro 16299.192

Steps to Reproduce:

1. Use the following minimal example.
[repro.zip](https://github.com/Microsoft/vscode/files/1715820/repro.zip)

2. When using Ctrl + Space to show code completions for MyModel (a sequelize-typescript model), many static methods are missing (e.g. findAll). This was working in 1.19.
![image](https://user-images.githubusercontent.com/2111803/36090061-0ece0e14-0fdf-11e8-8e1f-56914a60582d.png)

However, if I type the full method name, it seems to find it, as it then suggests the correct parameters:
![image](https://user-images.githubusercontent.com/2111803/36090076-24e9ac44-0fdf-11e8-8319-0f14d0de037f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21894
