### ISSUE TITLE
[Node] Debugger is constructing invalid path when providing non-existing file or folder name in the launch.json

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4348]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open any folder which contains node project.
2. Configure node debugger for opened folder.
3. Open launch.json and set the program property with non-existing file or folder.
4. Debug the project and verify error message.
Actual: The path in the error message contains both backward slash and forward slash. 
![image](https://cloud.githubusercontent.com/assets/17735796/13836881/1b2e5444-ebc3-11e5-8ef2-35643dc45d69.png)
Expected: Debugger should construct the correct path for non-existing file as well.

**Comment by weinand** [comment]
@v-pavanp the error message comes from the node debug adapter. The node debug adapter (and node itself) can deal with files that contain both forward and backward slashes. So if the file would exist, node could run it and there would be no error. But since the file doesn't exist the error is shown. There is no need for the node debug adapter to 'fix' the file path.

**Comment by jasonyueyang** [comment]
@weinand: the error message can be more user-friendly, similar to the improvement you made in https://github.com/Microsoft/vscode/issues/4343. For example, instead of "Attribute 'program' does not exist ('foo')", it might be better to say something like "File from 'program' does not exist ('foo')".

**Comment by weinand** [comment]
@jasonyueyang yes, that's a great suggestion. However, before starting to fix individual messages one by one, I think a native speaker should review all English messages in VS Code.

/cc @egamma @dbaeumer

**Comment by egamma** [comment]
@weinand great idea, but let's not forget that we want to lock down on string changes.
