### ISSUE TITLE
SourceMaps.loadSourceMapContents: Could not download sourcemap in debug console

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#43487]
### Issue Type
Bug

### Description

Here's a small excerpt of what I see in the debug console:
```
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/core/bootstrap.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/core/bootstrap-amd.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/core/vs\loader.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/core/vs\workbench\node\extensionHostProcess.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/core/paths.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/core/vs\workbench\node\extensionHostProcess.nls.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/extensions\emmet\out/abbreviationActions.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/extensions\emmet\out/defaultCompletionProvider.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/extensions\emmet\out/extension.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/ef42990520a856451ba5ad6fa1d299b0e0c185a2/extensions\emmet\out/util.js.map

```
1. Create new project with yeoman
2. Run it

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (ef42990520a856451ba5ad6fa1d299b0e0c185a2, 2018-02-12T05:14:21.574Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|Memory (System)|7.88GB (2.99GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by weinand** [comment]
@joaomoreno since build "ef42990520a856451ba5ad6fa1d299b0e0c185a2" was released I suspect that the build process failed to generate source maps?

**Comment by joaomoreno** [comment]
Unfortunately, only the Mac builds publish source maps. ef42990520a856451ba5ad6fa1d299b0e0c185a2 was one of those builds in which Windows 64 was built on a separate commit than all other platforms, including Mac.

**Comment by mike-lischke** [comment]
Side note: source map download can fail for other reasons, including being in a VPN. Not a good behavior that debugging is broken  (and kills the launched extension host after a while) if that download is not possible. I've just bitten by that, after the last vscode came in.

**Comment by weinand** [comment]
@mike-lischke source maps for VS Code are optional. They are downloaded once for a new VS Code version and then cached locally. If the download fails you are just not seeing the TS source but JS instead.

@roblourens extension debugging is not affected by missing source-maps, correct?

**Comment by mike-lischke** [comment]
What I saw was a bit different. The extension did not start in the extension host and no error was printed in the developer tools log. After a minute or so the extension host crashed and was closed. When I then closed vscode I got another crash.

I admit that is a pretty special situation. Just wanted to let you know. This is a closed issue anyway...

**Comment by weinand** [comment]
Let's get @roblouren's answer...

**Comment by roblourens** [comment]
> The extension did not start in the extension host and no error was printed in the developer tools log.

If the extension doesn't start and the debug adapter doesn't attach, it wouldn't even get to the point where it tries to download sourcemaps. You must have seen a different issue.

The original issue here has happened before, and it's annoying but basically harmless.
