### ISSUE TITLE
Proxy authentication request at startup

### ISSUE THREAD

**Issue by Davidinfo81** [microsoft/vscode#43486]
### Issue Type
Bug

### Description

Hi,

In our enterprise, we have a proxy with simple authentication and at Vscode startup, I have two windows with proxy authentication request... 
How to disable all update or internet connexion ?
I only need to use internet access when updating extensions (manually)

Thanks,

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU G1840 @ 2.80GHz (2 x 2794)|
|Memory (System)|11.89GB (6.82GB free)|
|Process Argv|C:\ProgramData\AppV\447FE3A8-6BAA-48B5-957A-952560E94505\98BCE443-7212-40BE-BD68-33D6FC68AF98\Root\Code.exe -n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
xml|Dot|1.9.2
code-runner|for|0.8.7
beautify|Hoo|1.3.0
VBScript|lug|0.0.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
material-icon-theme|PKi|3.2.2
spellchecker|swy|1.2.13
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.16.2

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
You can search for `@tag:usesOnlineServices` in the Settings Editor.
