### ISSUE TITLE
Can You Provide Different Color of Angular 2 in HTML (template file) like PHP

### ISSUE THREAD

**Issue by manoj30dec** [Microsoft/vscode#43494]
Can You Provide Different Color of Angular 2 in HTML (template file) just like in HOME.PHP each and everything related to PHP code it render in red color.   So could you provide same kind of feature for Angular template binding ?

**Comment by roblourens** [comment]
There are at least a couple extensions for this, try them out: https://github.com/Microsoft/vscode/issues/130#issuecomment-345939427
