### ISSUE TITLE
Matched quote/paren/brace/bracket deletion

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#4349]
I kind of expect if I delete the first character of the following pairs:
```ts
""
''
{}
()
<>
```
It will delete the end character too. Given that the cursor is between the pairs and no characters are between the pairs.

**Comment by alexandrudima** [comment]
@tinganho These pairs are defined per-language. Would you expect these pairs to be the same for all languages we support?

fyi @joaomoreno

**Comment by tinganho** [comment]
>@tinganho These pairs are defined per-language. Would you expect these pairs to be the same for all languages we support?

Are there any examples of why it shouldn't behave the same? 

>e.g. in JavaScript all except <> work as you expect, given JavaScript defines character pairs for the first 4.

I tried in JS and TS and it doesn't work.

**Comment by alexandrudima** [comment]
Yes, for example `'` is not a character pair in plain text files. Or `<` is not a character pair in JavaScript as it is only used as a comparator operator.

Here I am doing it in a JavaScript file: 

![character-pair-delete](https://cloud.githubusercontent.com/assets/5047891/13846501/d5d9d730-ec47-11e5-97ab-147dc747c359.gif)

What version of VSCode are you using that it doesn't work for you?

**Comment by tinganho** [comment]
I'm in version `Version 0.10.11 (0.10.11)`. Though it hasn't worked since the beginning like when VSCode launched for me.

![mar 17 2016 21 06](https://cloud.githubusercontent.com/assets/1324476/13846734/375ebab6-ec84-11e5-8302-adaa58d37d45.gif)

**Comment by alexandrudima** [comment]
I think `"editor.autoClosingBrackets"` controls this behaviour, is it possible you have set it to false in either user settings or workspace settings?

**Comment by tinganho** [comment]
These are the seetings I have set:
```json

// Place your settings in this file to overwrite the default settings
{
	"editor.tabSize": 4,
	"editor.insertSpaces": true,
	"typescript.useCodeSnippetsOnMethodSuggest": true,
	"javascript.suggest.useCodeSnippetsOnMethodSuggest": true,
    "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib"
}
```
And my default settings have set it to true.
```json
// Controls if the editor should automatically close brackets after opening them
	"editor.autoClosingBrackets": true,
```

**Comment by alexandrudima** [comment]
That is most weird. Here it works for me on 0.10.11 with your settings:

Do you have any extensions installed? Does it reproduce when running VS Code with the following command line argument: `--disableExtensions`?

![character-pair-0 10 11](https://cloud.githubusercontent.com/assets/5047891/13853606/bf774b88-ec67-11e5-8604-631b138cf6aa.gif)

**Comment by tinganho** [comment]
@alexandrudima I found out what the problem was. It was indeed an extension `Backspace++`.

cc @jrieken

**Comment by alexandrudima** [comment]
Maybe we can bring the functionality of `Backspace++` into the core, I have seen at least one issue asking for a smarter backspace implementation

**Comment by tinganho** [comment]
That would be awesome!

**Comment by ls42** [comment]
That would be most awesome!

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscode-backspace#3

**Comment by jrieken** [comment]
**verifier** install backspace++ before testing this

**Comment by RO-mix** [comment]
But still it does not delete matching bracket if in between there is something. Or may be i`m doing it wrong way? 
vscode 1.10 insider.
