### ISSUE TITLE
Improve New feature - Error indicators in the Explorer

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#43497]
Just a small hint, i suggest you to use the new decorator to detect in explorer the comments likes : 

```
// TODO 
// BUG
// FIXME
```

**Comment by jrieken** [comment]
I like the idea! Even better, it can be done as extension. Search for those strings and create diagnostics (DiagnosticsCollections/Diagnostic) for them and tata you have it

**Comment by jrieken** [comment]
A top (and for the near future) will come API that independently of diagnostics will allow you to add decorations to explorer entries
