### ISSUE TITLE
node debug adapter must support file URLs

### ISSUE THREAD

**Issue by Apoorva-GA** [Microsoft/vscode#43491]
- I have a javascript program which executes certain parts of the code in a node [VM](https://nodejs.org/api/vm.html). We are using inline source map to map the files executed in the VM. 
- The source map format used is as such: `# sourceURL= <absolute filepath to js file>`.
The source maps given in this format seems to work fine when run on Mac. On Windows, the same format doesn't seem to work. 
- I have checked the same with `chrome://inspect` and the debug points are honoured.
It doesn't work with node debugger of VSCode.

*More info*: 
Debugger is getting attached after the program executes. Debugger stops on `debugger` keyword but not on the actual breakpoints.

we are using ` inspector.open(port, "127.0.0.1", true)` but have tried `--inspect-brk=port` and the problem is the same.

The debug config looks like below:
```
{
        type: "node",
        name: "Gauge Debugger",
	request: "attach",
	port: port,
	protocol: "inspector"
}
```

The same thing works on mac : 10.13.3(High Sierra) but not on windows 10.

- VSCode Version: 1.20.0
- OS Version: windows 10

Am I missing something?

**Comment by roblourens** [comment]
You said you're using sourcemaps and also `sourceURL`. Is sourceURL actually what you're using, or sourceMappingURL? Or both?

**Comment by Apoorva-GA** [comment]
I am using `sourceURL`.

**Comment by roblourens** [comment]
I'm guessing there is no sourcemap or transpilation process - you are just using sourceURL to point from the evaluated script to the source. Is that right?

We rely on how Node handles this. I think it has to be a URL, relative path, or path fragment, not an absolute path, so a file: url may work. If not you could try just removing the drive letter, if the sources are on C:. This is sort of a little-used feature.

**Comment by Apoorva-GA** [comment]
Yes, there is no sourcemap or transpilation process and I am just using sourceURL.

Tried by removing the drive letter still the break points are not getting honoured.(Debugger is getting attached after the execution).

**Comment by roblourens** [comment]
I think a file URL is probably the best bet... if not, set `"trace": true` and upload the log here.

**Comment by Apoorva-GA** [comment]
I tried with the file URL but it hits debug points on the file(though line number is always +1) in node internals and not the actual source file. 

Please find the attached log file below : 
[logFile.log](https://github.com/Microsoft/vscode/files/1726662/logFile.log)

**Comment by Apoorva-GA** [comment]
@roblourens any update on this?

**Comment by roblourens** [comment]
Thanks for the log, I guess the problem is that the debug adapter doesn't expect to get file URLs but sourceURL only works with file URLs.

**Comment by Apoorva-GA** [comment]
If that was the case, any idea as to how the same thing is working on mac?

**Comment by roblourens** [comment]
Chrome probably assumes the / paths are like paths rooted from `/`. Which in the Node case happens to be the drive root.

**Comment by Apoorva-GA** [comment]
But its working fine with remote debugging with chrome dev tools( `chrome://inspect`). I am facing this problem only in windows. Can't think of how it is different in windows?

**Comment by roblourens** [comment]
I fixed this some time ago
