### ISSUE TITLE
'Cannot read property 'toString' of null.' when starting debugger for second+ time

### ISSUE THREAD

**Issue by helloworld111gh** [Microsoft/vscode#43490]
### Issue Type
Bug

### Description

Steps to Reproduce:

1. Have project open, with "console" in debugger launch configuration set to "integratedTerminal"

2. Start debugging the program (F5), then quit the application (ex. by using Ctrl-C). Keep the Node Debug Console open.

3. Try debugging the program again (F5)

OR 

2. Start debugging the program (F5), then click on the Restart button

Expected:
Debugger and program should load like it does in step 2

Actual:
This error occurs:

TypeError: Cannot read property 'toString' of null
    at Function.e.isBusy (terminalSupport.ts:56)
    at Function.e.runInTerminal (terminalSupport.ts:38)
    at _.dispatchRequest (rawDebugSession.ts:393)
    at _.e.dispatch (v8Protocol.ts:148)
    at _.e.handleData (v8Protocol.ts:104)
    at Socket.<anonymous> (v8Protocol.ts:41)
    at emitOne (events.js:96)
    at Socket.emit (events.js:191)
    at readableAddChunk (_stream_readable.js:178)
    at Socket.Readable.push (_stream_readable.js:136)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X6 1090T Processor (6 x 3199)|
|Memory (System)|16.00GB (10.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by weinand** [comment]
I cannot reproduce this problem.
Did you configure the integrated terminal in any way, e.g. by setting a special shell via the "terminal.integrated.shell.windows" setting?
