### ISSUE TITLE
When switching workspace, the select folder dialog is not focused in Fedora 27 with Gnome 3

### ISSUE THREAD

**Issue by Markussss** [Microsoft/vscode#43498]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.14.16-300.fc27.x86_64

---

When opening the workspace selector dialog (using the keyboard shortcut Ctrl+K+O), the VSCode window still has focus and can be written to (typing on the keyboard), resized (Super+arrow keys), etc.

I don't know if this is an issue with Gnome, with Fedora, or with Linux, as I haven't tested it across different distros or desktop environments. As far as I know, this has been present for the whole time I've been using VSCode (~1 year).

---
Steps to Reproduce:
---

1. Open the workspace selector (Ctrl+K+O)
2. Try navigating the select folder dialog box with the keyboard, or close it with Esc.
---
1. Open an empty file
2. Open the workspace selector (Ctrl+K+O)
3. Type some text
4. Close the workspace selector without selecting a new workspace
5. The text you typed will be present in the new empty file

Reproduces without extensions: Yes

**Comment by batisteo** [comment]
This might be related to Wayland.

**Comment by bpasero** [comment]
@Markussss could you try with this newer build for Linux to reproduce: https://az764295.vo.msecnd.net/exploration/ed422f909ea470f79e3e3e39c948803d9b764919/code-exploration-1.22.0-1522303929_amd64.tar.gz
