### ISSUE TITLE
Saving the file requiring admin permissions results in % appended at the end

### ISSUE THREAD

**Issue by Nikki1993** [Microsoft/vscode#43499]
- VSCode Version: 1.20.0
- OS Version: Solus OS

Steps to Reproduce:

1. Trying to edit system file located under /etc/profile.d/qt.sh
2. After saving the file and clicking Retry as Admin it results in file saving but also adding % at the end 
![profile](https://user-images.githubusercontent.com/1446529/36094596-9493d9bc-0ff7-11e8-97db-9630e6e06c04.png)

I created the file using terminal `touch`, saving an empty file results in nothing but writing smth to it and then saving it, ads the % even though **it's not visible in the file itself.** Using loclal text editor (gedit - Gnome Text Editor) saves the file correctly with no extra output.

**Comment by bpasero** [comment]
@Nikki1993 are you sure this is not something like https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol ?

**Comment by Nikki1993** [comment]
Could be, I had a thought about it but then I figured why when I edit it with vscode it prints it out and yet gedit doesn't. That inconsistency raised my alarm. Could just very well still be zsh percent symbol.

**Comment by bpasero** [comment]
@Nikki1993 does it reproduce e.g. when you edit `/etc/hosts` ?

**Comment by Nikki1993** [comment]
Oh snap, I totally missed this github notification, my bad, but for the sake of it, no, no % is added when editing *hosts* file.
