### ISSUE TITLE
Keyboard shortcut to focus the "Working Files" section of the sidebar. 

### ISSUE THREAD

**Issue by fa137** [Microsoft/vscode#435]
Apparently after focusing the sidebar, we cannot navigate to the working files section using the keyboard arrow keys. Only options available through keybindings are to select the previous and next working file. There isn't a option to cycle through them or select them individually through sidebar using keyboard shortcuts.

**Comment by bpasero** [comment]
Great ask and great opportunity for someone to do a PR, it should be easy to add!

**Comment by Xelom** [comment]
What kind of functionality is required here? Is navigating to working files section with a shortcut enough? Maybe we can navigate through the sections while focused to the sidebar via Ctrl + Up and Ctrl + Down arrow?

**Comment by takumif** [comment]
3db22b0377e2398c83522f65e6b299da5e4c874f added keyboard shortcuts for focusing on working files, so this issue should be closed now.

**Comment by bpasero** [comment]
Yes, it is Cmd+K E as keybinding.
