### ISSUE TITLE
Remember open panes (like the integrated terminal)

### ISSUE THREAD

**Issue by StickNitro** [Microsoft/vscode#43500]
Feature request.

I use vscode a great deal on multi project workspaces, I use the integrated terminal quite extensively and would like to have the option for vscode to remember my open terminal panes, or just remember open panes in general.

At present I have to re-open all the integrated terminal panes and rename them all which is quite a chore.  Perhaps these could be remembered as part of a workspace and consider only remembering the panes that have been renamed

**Comment by fabiospampinato** [comment]
Your use case seems a great fit for my [Terminals](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals) extension. It basically allows you to define some terminals to automatically open at startup.

**Comment by Tyriar** [comment]
This is tracked in https://github.com/Microsoft/vscode/issues/20013

**Comment by StickNitro** [comment]
@fabiospampinato that extension is just what I am looking for, thank you
