### ISSUE TITLE
Allow to theme the tooltip color (title attribute over HTML elements)

### ISSUE THREAD

**Issue by mbenkmann** [microsoft/vscode#43509]
- VSCode Version: 1.20.0
- OS Version: Linux

I am building a color theme and I cannot find any settings to customize the text, background and border colors of the workbench UI tooltips. I'm talking about e.g. the following:

* Popup "New File" when you hover over the respective icon in the Explorer.
* Popup "Find" when you hover over the text input field of the Find widget (Ctrl-F)

It seems to be hardcoded to white on black. I've tried all the themes that ship with VS Code by default and none of them changes this color. That leads me to believe it's not possible or undocumented. There is also no color property with any suggestive name. I've tried all that seemed fitting to me and none did the trick.

**Comment by praveenpuglia** [comment]
I think VS Code uses the native browser tooltips for those and native tooltips can't really be styled.

**Comment by mbenkmann** [comment]
That would be a problem. For a browser, white on black makes sense since most websites have a light background. But many if not most of the most popular themes for VS Code have a dark background which makes that color combination hard to read.
Anyway, according to https://www.w3schools.com/css/css_tooltip.asp those tooltips can be styled. I've tried their online JavaScript demo and it works in Chrome.

**Comment by praveenpuglia** [comment]
That tooltip example is for a custom tooltip and not how to style the native tooltip. Making a custom tooltip that's as good as the native tooltip in terms of positioning itself will be hard. 

Also, default browser tooltips are White on Black. To differentiate from the background, which is almost always light in color for websites they include shadows and colors too. So for a dark background, it shouldn't be a problem anyway. 

Please correct me if I am not getting something.

**Comment by mbenkmann** [comment]
The following screenshot is from VS Code with the high contrast color theme. That tooltip does not stand out at all. It's especially bad when it overlaps with other white on black text (just imagine the tooltip a bit higher so that it overlaps with "Keyboard Shortcuts"). Being able to theme this (especially with a border) would improve visibility immensely.

![foo](http://winterdrache.de/data/tooltip_hc.png)
