### ISSUE TITLE
Edit and continue [C#]

### ISSUE THREAD

**Issue by 7654098** [Microsoft/vscode#43502]
### Issue Type
Feature Request

### Description

I know, that's a very strange question (I had to find the answer, but I'm not able).

Is it possible to edit and continue C# code in VS Code?

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

**Comment by mjbvz** [comment]
Please ask this question against the c# extension

**Comment by 7654098** [comment]
This is the feature request. 

Could you please tell me, if the feature "Edit and Continue" is exist in VS Code. If not, do you have any roadmap for it?
