### ISSUE TITLE
Allow extensions to contribute additional paths to "quick open"

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#43505]
In IntelliJ it's possible to include non-project files in the quick-open dialog:

![screen shot 2018-02-05 at 9 48 59 am](https://user-images.githubusercontent.com/1821610/35817348-5b9261d0-0a5a-11e8-9d7f-e124d67f730d.png)

It would be useful to support in Code. For Dart, dependencies are stored outside of the project (similar to the NuGet cache, I guess) but users may wish to open them.

Maybe an extension could provide a set of additional paths that should be searchable?

**Comment by bpasero** [comment]
@DanTup we support to open a file if you paste the absolute path, would you expect we search your entire disk as soon as you type a file name?

**Comment by DanTup** [comment]
Of course not; that's why I suggested:

> Maybe an extension could provide a set of additional paths that should be searchable?

The request came from one of my users; the editor he's using has the checkbox shown top-right of the screenshot. I'm not sure of exactly what it does though maybe he can clarify (cc @briblanch).

**Comment by briblanch** [comment]
@DanTup I think your idea of the ability to add different paths that are searchable is the right idea.

**Comment by drorata** [comment]
Atom has a nice plugin [advanced-open-file](https://atom.io/packages/advanced-open-file) which is doing what I believe @DanTup points at. This addon, however, does search/complete the whole file system.

**Comment by drorata** [comment]
Is there any feedback on this issue? Easily opening files across the filesystem (and not only from the current project/dir+sub-dirs) is very missing in vscode.

**Comment by adimascio** [comment]
Without searching on the entire disk, it could just try to complete with files or subdirectories that matches the current input. This could maybe be combined with https://github.com/Microsoft/vscode/issues/21372 so that extension editors be able to customize as they wish ?

**Comment by drorata** [comment]
I believe this is all that has to happen; the content of the "current" directory has to be scanned and fuzzy completion should be suggested. The way [advanced-open-file (for Atom)](https://atom.io/packages/advanced-open-file) or [ido (for emacs)](https://www.masteringemacs.org/article/introduction-to-ido-mode)  work is really helpful and I am puzzled it is not possible with vscode.

**Comment by nealot** [comment]
Could this also include recent files or does that warrant a new issue? Emacs has Recentf which lists the most recent files and I thought Quick Open performed a similar task before realizing that it only indexes workspace files. I think many people would appreciate a command that searches for recent files without having to open the system file manager.

**Comment by DanTup** [comment]
I'm definitely not asking for any file on disk, just a known set of folders outside the workspace. Imagine if `node_modules` was stored one level up for a project - you might want its contents in Quick Open since your project is using those files.

In Dart, there is a file (`.packages`) that declares the full paths to all of the packages being used (which do not live inside your actual project folder, but rather cache folders elsewhere). The original request here is that the extension can somehow tell VS Code to include those filenames in quick open.

**Comment by roblourens** [comment]
I see. I don't understand why not just add those folders to the workspace?

**Comment by DanTup** [comment]
@roblourens 

> I don't understand why not just add those folders to the workspace?

It would be a bit messy. If the user has 30 dependent packages, they wouldn't want 31 folders in their workspace just so they can (infrequently) jump into a file. Adding the parent folder would give them all packages cached on their machine, not just those in use by the current project.

We can already add these things to the workspace symbol provider, so it would be nice if we could do the equivalent here (though it's not a big deal, the workspace symbol list makes up for it a little).

@drorata You don't need to navigate folders in quick open, you can just type the filename and it'll filter across the full list of files. I'm not sure why people keep talking about scanning the whole disk though, that was never being asked for - only the ability to supply additional folders/files to appear in there from an extension.

**Comment by drorata** [comment]
@DanTup I am not sure what you mean by "quick open". I do know that while working within vscode (started from some directory) I occasionally want to visit file elsewhere (e.g. looking up some configuration for instance). Therefore, I think it is very valuable to have the ability to hit `CMD+P` for example and navigate away from the "root" directory of the project.

**Comment by DanTup** [comment]
@drorata 

> I am not sure what you mean by "quick open".

Quick Open is the feature in VS Code when you hit `Ctrl/Cmd+P` that lists all files and lets you filter:

<img width="657" alt="screen shot 2018-08-16 at 14 25 34" src="https://user-images.githubusercontent.com/1078012/44211172-474d9800-a160-11e8-9182-a9d1c740b640.png">

That's what this issue relates to. Allowing additional files to be included by an extension (eg. things that may be referenced by the project but are not inside the open workspace folder).

**Comment by drorata** [comment]
@DanTup Assuming you understand the use case I'm trying to describe, wouldn't it fit naturally to "quick open"?

**Comment by DanTup** [comment]
I don't personally think so - quick open gives you a list of paths and quickly filters them. It doesn't have a concept of a current folder so navigating up/down doesn't seem to fit in to me. That's not to say it's not a good idea, but if you're trying to navigate folders you could use the standard Open dialog.

In any case, it's not what this issue is about - this was specifically about allowing *an extension* to supply additional paths that it knows are relevant to a project. Your suggestion may be best in its own issue.

**Comment by roblourens** [comment]
Ok, it sounds like you want some folders which are not full workspace folders, but get some subset of the features for workspace folders enabled (just quickopen and the language service). I'm not sure what the best solution is.
