### ISSUE TITLE
Slow performance on file delete from the tree view (using trash)

### ISSUE THREAD

**Issue by Oscuro87** [Microsoft/vscode#43508]
### Issue Type
Performance Issue

### Description

When I'm deleting a file from the tree view on the left, hit the "delete" button, it takes several seconds (2-3 seconds) before the action is done.

Additional infos:
1) With all the extensions disabled, it still takes about 1 to 2 seconds, but it feels faster.
2) When trying to delete more than one file, the action becomes slower and slower, and is directly related to the amount of files deleted. (<= 1.0 additional (felt) second per additional file)
3) I'm working a lot with files-heavy node.js projects, though I ignored the node_modules folder in the settings (the node_modules folder is greyed)
4) I'm using the insiders build (1.21.0), and I did not have this issue in 1.20.x

It's not a big bug, I can just pop the terminal and delete the files with rm, just letting you know.

Thank you :-)

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (9a4ba7d06157091c882a03f118793db5d4657a82, 2018-02-12T06:16:15.252Z)
OS version: Linux x64 4.10.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3956)|
|Load (avg)|1, 1, 0|
|Memory (System)|7.78GB (0.47GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

|pid|CPU|Memory (MB)|Name|
|---|---|---|---|
|8385|0|111|code-insiders main|
|8398|0|24|-- zygote|
|8445|0|215|---- shared-process|
|8499|0|80|------ extensionHost|
|8572|0|111|-------- electron_node electronForkStart.js tsserver.js |
|8586|0|56|---------- electron_node typingsInstaller.js tsserver.js typesMap.js |
|8500|0|48|------ watcherService|
|8527|0|48|------ searchService|
|8448|0|96|---- shared-process|
|12690|0|80|---- shared-process|
|8436|0|104|-- gpu-process|
|12706|0|0|-- /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=|
|12707|0|0|---- /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=|

</details><details>
<summary>Workspace Info</summary>

```
|  Window (router.js - cms2-front - Visual Studio Code - Insiders)
|    Folder (cms2-front): 21 files
|      File types: js(11) json(2) tmpl(2) babelrc(1) gitignore(1) md(1)
|                  html(1) scss(1)
|      Conf files: package.json(1) webpack.config.js(1);
```

</details>

Reproduces without extensions

**Comment by bpasero** [comment]
@Oscuro87 when you do Alt+click and then select delete permanently, does it make a difference?

**Comment by Oscuro87** [comment]
Hello @bpasero!

It does! When using your trick (which I just learned 👍 ) it deletes the files instantly!

**Comment by Oscuro87** [comment]
Sorry but I'm using this on Linux, I believe the windows tag is wrong

**Comment by IsaacJT** [comment]
Hello,

I'm also encountering this problem on Fedora 28 with KDE and Code 1.25.0. Deleting the file with "delete permanently" also works fine.

Deactivating all extensions and trying again makes no difference.

This occurs on both NFS shares and btrfs-formatted volumes. I haven't tried it on other disk formats.

**Comment by krasi-georgiev** [comment]
+1 on slow performance when deleting without the shift.

**Comment by Oscuro87** [comment]
I would like to report that I **no longer** have this issue as of version 1.30.2 Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8

I will test further, but it is looking good so far, even "node_modules" (!!) folder is deleted instantly.

**Comment by chiboreache** [comment]
+1

**Comment by chiboreache** [comment]
mmm.. no it isn't `~_~`


```
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.20.4-arch1-1-ARCH
```
