### ISSUE TITLE
Markdown syntax highlighting for ~~text with strikethrough~~ and task-items

### ISSUE THREAD

**Issue by maranomynet** [microsoft/vscode#43504]
It would be very nice to see `~~text with strikethrough~~` being greyed out (or somehow highlighted) in source mode (not "Preview" mode) – like `_italic_` and `**bold**` text is.

Also greying out finished/checked `* [x] task-items` would be sweet.

**Comment by mikaoelitiana** [comment]
I am interested to work on this one. I checked some documentation but I can't find yet how to add strikethrough style because this fontStyle seems to be not supported by vscode yet. 
Does somebody know where I can add this?

**Comment by alexandrudima** [comment]
`strikethrough` is not something TM grammars support, so I would not recommend deviating from TM grammars/themes with custom font properties such as strike-through in TM themes.

This could perhaps be implemented via editor decorations. Strike-through could be useful for other programming languages, for rendering deprecated method names, etc..

**Comment by neilsustc** [comment]
A workaround: using extension [TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) with this settings

```
"todohighlight.keywordsPattern": "~~.+?~~",
"todohighlight.defaultStyle": {
    "color": "none",
    "backgroundColor": "none",
    "textDecoration": "line-through"
}
```

**Comment by christophfriedrich** [comment]
*TODO Highlight* is good for simple cases. I wanted to style more than one regex, so I found the [*Highlight* extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight). It can even style different capture groups of the same regex differently!

With *Highlight*, the strikethrough style would be configured like this:

````
"highlight.regexes": {
    "(~~.+?~~)": [
        {
            "color": "none",
            "backgroundColor": "none",
            "textDecoration": "line-through"
        }
    ]
}

**Comment by WickyNilliams** [comment]
Since vscode now puts a strikethrough on calls to deprecated code, I wonder if the editor support is there so that this could actually be implemented now?

![image](https://user-images.githubusercontent.com/1091390/96736977-10fdaa00-13b5-11eb-9bbc-5981ce4c94a8.png)

**Comment by BettyJJ** [comment]
@alexdima According to #78358, TextMate supports strikethrough. 

It is handy if vscode can supports strikethrough in fontStyle so that we can put all font styles in one place, instead of putting some in themes and some in editor decorations. To use a separate plugin for this is such an overkill.

**Comment by alexdima** [comment]
It looks like TM [added this in 2016](https://github.com/textmate/textmate/commit/2593550f9a736111e399a5cd162261f564f8a554) (When we initially implemented TM support in VS Code, I don't think they had support for it)

**Comment by K4LCIFER** [comment]
I would  love this feature. I use strikethrough a lot for to-do lists, and it's pretty tedious to have to do it manually all of the time. Is there an update on the status of this?

**Comment by 4086606** [comment]
I'd like to be using this feature but for other languages as well, its super useful

**Comment by SNDST00M** [comment]
microsoft/vscode-textmate#158 is now on deck for January :shipit:

**Comment by SNDST00M** [comment]
I would actually suggest that checkbox strikethrough is an extension candidate and would be a good feature PR for [`mjbvz/vscode-markdown-checkboxes`](https://github.com/mjbvz/vscode-markdown-checkboxes)

**Comment by mjbvz** [comment]
Support for `~~` was added in https://github.com/microsoft/vscode-markdown-tm-grammar/pull/101. Thanks @SNDST00M! Pushing fix to adopt this for our built-in themes now

**Comment by mjbvz** [comment]
As @SNDST00M notes, I think checkboxes should be handled in that checkboxes extension. VS Code does not include support for checkboxes out of the box

**Comment by SNDST00M** [comment]
Wow beat me to it :)

**Comment by ArturoDent** [comment]
This works for me (in the vscode markdown preview):

`<span style="color:gray">~~strikethrough~~</span>`

although sometimes I have to hit the markdown preview keybinding more than once to see it??

Obviously it isn't automatically done by vscode without the `span` tag but maybe it is a temporary solution for some.
