### ISSUE TITLE
Git Submodules not updating 

### ISSUE THREAD

**Issue by nilsborg** [Microsoft/vscode#43517]
### Issue Type
Bug

### Description

Hi there!
I have a couple submodules in my project. And whenever I commit outside VSCode with a more sophisticated git client, the file explorer status of all the files just stays the same, even though the files should not be marked as changed anymore.
Also the VCS section in the editor is kinda stuff the same way.

Thanks!
n

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.19GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
EditorConfig|Edi|0.12.0
code-settings-sync|Sha|2.8.7
vscode-svgo|ajh|0.1.0
halcyon-vscode|bri|0.0.8
vscode-eslint|dba|1.4.5
prettier-vscode|esb|1.1.3
auto-rename-tag|for|0.0.15
vscode-scss|mrm|0.6.2
language-liquid|nei|0.0.3
stylelint|shi|0.32.0
open-in-browser|tec|1.1.0
gitblame|wad|2.2.0

(4 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
@nilsborg Just to confirm: both the file explorer and the SCM view don't react to file changes? Does this happen if you make regular file changes outside VS Code (simply delete a file).

**Comment by nilsborg** [comment]
Hi! 

Ehm not 100% sure .. I’ll keep an eye on this. Definitely though I started noticing this with this project which has sub modules.. regular repo works just fine when files get changed outside vscode

**Comment by Robominister** [comment]
I seem to be having a (possibly) related issue in the latest VSCode version.

Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:02.816Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

I have a main project (called **client,**) which has another project added as a sub-module (**common**) Suppose there are 2 commits in common, and 2 commits in client (the 2nd client project commit simply updates the commit from common that is used).

**Expectations**
If I use the Source Control tab in VSCode to check out each of the specific commits for client, I expect the common sub-project to get updated to the version that was in that commit.

**What happens**
The sub-module ("common") isn't updated: it stays at the same commit. (I have to manually run git submodule update --recurse to get the correct sub-module commit: at this point, VSCode catches the change to the working tree as expected),
