### ISSUE TITLE
Find in files not working as expected

### ISSUE THREAD

**Issue by Anisana** [Microsoft/vscode#43515]
Since updating to v1.20.0, the "Find in files" functionality no longer seems to search in all non-excluded files.

- VSCode Version:
Version 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:10:31.920Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

- OS Version: Windows 7 Enterprise, 64-bit
CPUs: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)
Memory (System): 15.67GB (2.42GB free)
Process Argv: C:\Program Files (x86)\Microsoft VS Code\Code.exe
Screen Reader: no
VM: 0%

- Extensions:

Extension | Author (truncated) | Version
-- | -- | --
vscode-svgviewer | css | 1.4.3
githistory | don | 0.4.0
gitlens | eam | 8.0.0

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Open search box (`ctrl+shift+f` on windows)
2. Enter a random word that you know exists in the files in the workspace
3. Press enter

Expected outcome:

- All non-excluded files are searched and all relevant results shown.

Actual outcome/Observations:
- If you have any files currently open in the editor, only those files are searched.
- When submitting this ticket I disabled all my extensions and reloaded the window. I then searched before clicking to view my previously opened file, and no results were returned even though I know the word I searched for exists in the file I have open. When I focussed that file and re-searched, results for that files were displayed.
- I had a friend test this for me on version 1.19.3 and the search works as expected, so this appears to be an issue confined to version 1.20.0.

**Comment by roblourens** [comment]
Are you sure the files aren't covered by a gitignore file or excludes? Please toggle the "Use Excludes and Ignore Files" button (bottom right) and try again
![image](https://user-images.githubusercontent.com/323878/35752446-e01ea914-0810-11e8-8d1e-9877a751c5ca.png)

**Comment by Anisana** [comment]
Cool thanks, will do. I'd secretly hoped that this would be a duplicate but I couldn't find the ticket myself.
