### ISSUE TITLE
Vs code is not opening after last update (1.20)

### ISSUE THREAD

**Issue by deep5050** [Microsoft/vscode#43512]
Blank white screen appears when trying to launch it. Problems only with the 1.20 version. 1.19.3 is working smoothly (after a clean install of the 1.19.3 setup )!!

**Comment by deep5050** [comment]
X64 windows

**Comment by jens1o** [comment]
Could you try opening the command prompt and enter `code --disable-gpu`?

**Comment by octref** [comment]
@deep5050 Can you post a screenshot or gif showing the behavior?
