### ISSUE TITLE
VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80

### ISSUE THREAD

**Issue by mharisbaig** [Microsoft/vscode#43510]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.24.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
gitignore|cod|0.5.0
git-extension-pack|don|0.1.3
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
vscode-npm-script|eg2|0.3.3
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
phpcs|ika|0.7.0
vscode-angular2-emmet|jak|2.0.3
react-native-snippet|jun|0.4.2
vscode-github|Kni|0.26.0
MagicPython|mag|1.0.12
python|ms-|2018.1.0
node-debug2|ms-|1.19.0
bootstrap4-vscode|the|3.0.0
vscode-react-native|vsm|0.5.7
bootstrap-3-snippets|wcw|0.1.0
jinja|who|0.0.8
vscode-open-in-github|ziy|1.3.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by jens1o** [comment]
What's the problem?
