### ISSUE TITLE
Custom compose key configuration does not work

### ISSUE THREAD

**Issue by timtro** [Microsoft/vscode#43526]
- VS Code Version 1.20.0
  Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
  Date 2018-02-07T17:10:15.949Z
  Shell 1.7.9
  Renderer 58.0.3029.110
  Node 7.9.0
  Architecture x64
- Linux (Ubuntu 17.10.1,  4.13.0-32-generic \#35)
- Issue is reproducible without plugins loaded.

The issue is identical to [this one](https://github.com/Microsoft/vscode/issues/34277), #34277. The issue was closed because Chrome displayed the same behaviour, indicating an upstream problem. However, I am currently able to use my custom compose combinations from `~/.XCompose` in Chrome. I'm wondering if this is something we can fix now.

**Comment by alexandrudima** [comment]
I have reopened #34277, as it contains more information...
