### ISSUE TITLE
Session (opened tabs) is lost after Code update

### ISSUE THREAD

**Issue by bocekm** [Microsoft/vscode#43524]
Whenever I update Code to new release, next time I start the Code (e.g. after system restart) the What's new tab pops up and all the previously opened tabs are gone. Just the What's new tab is opened and I can't see an option to reopen the previous tabs.

I have been using the "window.restoreWindows": "all" option.

- VSCode Version: 1.20.0
- OS Version: Fedora 27

Steps to Reproduce:

1. Have one Code window with multiple file tabs opened
2. Update Code to new version
3. Close and open Code
4. The tabs from step 1 are not opened, just What's new tab is

Does this issue occur when all extensions are disabled?: I would need to wait for another code release to see whether the issue occurs without extension but I doubt it would have any effect.

**Comment by bocekm** [comment]
I have reopened the editor without extensions and I'll try to keep it open till the new version is out. By the way I use the following extensions: GitLens, Python, RPM Spec, Sublime Text Keymap.

**Comment by bpasero** [comment]
Likely https://github.com/Microsoft/vscode/issues/12058 and https://github.com/Microsoft/vscode/issues/39125
