### ISSUE TITLE
vscode jest debug profile with external jest-config

### ISSUE THREAD

**Issue by firsttris** [Microsoft/vscode#43522]
Holla,
I'm trying to create a jest debug profile with external config.

but i always get the following message:

**Error: Can't find a root directory while resolving a config file path.**

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "launch",
            "port": 9229,
            "runtimeArgs": [
                "--inspect-brk",
                "${workspaceRoot}/node_modules/jest/bin/jest.js",
                "-i",
                "-t should dispatch GetAccessToken Test",
                "-c ${workspaceRoot}/jest-config.json",  
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        },
    ]
}
```

while running jest with config from cli is possible, im not able todo this from a vscode debug profile.

on cli you can pass config with -c jest-config.json

any advice?

regards
tristan

**Comment by weinand** [comment]
@firsttris what do you mean by "external config"?

A "launch.json" will only be found if you open a project folder in VS Code (otherwise there is no ".vscode" folder where the launch.json could live). 

BTW, a somewhat simpler and clearer config for jest is:
```json
        {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
            "args": [
                "-i",
                "-t should dispatch GetAccessToken Test",
                "-c ${workspaceFolder}/jest-config.json",  
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }
```

**Comment by firsttris** [comment]
Hey @weinand 

thx for taking the time to reply to my issue!

with external config i mean external Jest config **jest-config.json**

if the jest-config is located in package.json i have no issue.

**Comment by firsttris** [comment]
i updated my debug-profile to the more cleaner version, thx!

i have no issues running Jest with external config from CLI.

i have no issue with running VSCode Debug Profile for Jest and Jest-config in Package.json

but with VSCode Debug Profile for Jest and Jest-Config in a external file e.g. <root>/jest-config.json

![image](https://user-images.githubusercontent.com/1709260/36110510-1be09d30-1023-11e8-9662-66103ca37b33.png)

**Comment by weinand** [comment]
Does it make a difference if you make the "jest-config.json" relative, e.g.
```
```json
        {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
            "args": [
                "-i",
                "-t should dispatch GetAccessToken Test",
                "-c jest-config.json",  
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }
```

**Comment by firsttris** [comment]
Same Issue
(already tried all possible variants for absolut & relative paths)

```
Error: Can't find a root directory while resolving a config file path.
Provided path to resolve:  jest-config.json
cwd: /home/firsttris/Projects/sfmdigital
    at exports.default (/home/firsttris/Projects/sfmdigital/node_modules/jest-config/build/resolve_config_path.js:42:11)
    at readConfig (/home/firsttris/Projects/sfmdigital/node_modules/jest-config/build/index.js:72:84)
    at getConfigs (/home/firsttris/Projects/sfmdigital/node_modules/jest/node_modules/jest-cli/build/cli/index.js:342:56)
    at /home/firsttris/Projects/sfmdigital/node_modules/jest/node_modules/jest-cli/build/cli/index.js:173:27
    at Generator.next (<anonymous>)
    at step (/home/firsttris/Projects/sfmdigital/node_modules/jest/node_modules/jest-cli/build/cli/index.js:129:40)
    at /home/firsttris/Projects/sfmdigital/node_modules/jest/node_modules/jest-cli/build/cli/index.js:148:20
    at new Promise (<anonymous>)
    at /home/firsttris/Projects/sfmdigital/node_modules/jest/node_modules/jest-cli/build/cli/index.js:126:16
    at runCLI (/home/firsttris/Projects/sfmdigital/node_modules/jest/node_modules/jest-cli/build/cli/index.js:213:22)
```

**Comment by weinand** [comment]
@firsttris the error message you are seeing originates from jest, not from VS Code. So you might want to investigate on the jest side as well, e.g. https://github.com/facebook/jest/issues/3499.

**Comment by firsttris** [comment]
i thought so as well..

but...

- this issue only happens within a VSCode Debug Profile. not from CLI
- In Webstorm i have also not issue debugging with external jest-config
- A jest config change (like suggested in the issue you liked) won't help since jest can't find the config in the first place

continue investigating on both sides

**Comment by weinand** [comment]
So where does the jest-config.json actually live?

**Comment by firsttris** [comment]
jest-config.json is in the ProjectRoot Directory.

i found out if i rename the jest-config.json to `jest.config.js`

it finds the config without --config (-c) argument

because they setup some default names, for look for:
https://github.com/facebook/jest/blob/master/packages/jest-config/src/constants.js#L16

```
       {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
            "args": [
                "-i",
                "-t should dispatch GetAccessToken Test"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }
```

for me this workaround is acceptable.

if you don't want to explore further why --config (-c) is not working, we can close this issue

**Comment by weinand** [comment]
Oh, I think I know what the problem is.
A construct like "-c jest-config.json"  must be passed as two separate arguments, e.g. "-c", "jest-config.json". The equivalent "--config=jest-config.json" can be passed as one.

Try this:
```json
        {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
            "args": [
                "-i",
                "-t", "should dispatch GetAccessToken Test",
                "-c", "jest-config.json"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }
```

**Comment by firsttris** [comment]
thanks for your help, your suggestion is working!

**Comment by weinand** [comment]
Great, and sorry for not spotting this earlier.
