### ISSUE TITLE
Completion unexpectedly triggers on second keypress of an edit group in a snippet

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43523]
When my extension inserts a snippet, the code completion unexpectedly opens after the second keypress when typing a name. For example@

```ts
editor.insertSnippet(new vs.SnippetString("var a = new ${1:Danny}();"), new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)));
```

This inserts `var a = new Danny();` with the word `Danny` selected. The first key press does not invoke completion, but the second keypress does invoke completion (the trigger type is set to `0`/`Invoke`) and subsequent keypresses do not.

This seems kinda strange, but also causes issues if the user presses a commit character because the completion can insert unexpected things.

Here I'm invoking the "Create class" action in my code just to trigger the insertion of the snippet at the top of the document. I type `aaa` slowly, and on the second `a` you can see the completion provider log that it was invoked (in the debug console on the left).

It seems strange to invoke on the second keypress, but also seems unexpected to be invoking during editing of a placeholder (I think it's more common for a user to be typing something new, not referencing something existing, during these sorts of edits?).

![completion](https://user-images.githubusercontent.com/1078012/36106930-860d38a2-1010-11e8-9b8d-1747d6597037.gif)

**Comment by DanTup** [comment]
I'm actually no longer convinced it's not a good idea to open completion - some of my quick fixes probably will result in the user completing existing class names.

The behaviour here seems weird though, like sometimes it seems to alternate between invoking (I think maybe it invokes, next key press gets filtered client-side resulted in no results, which causes the next key to invoke again?).

![alternating](https://user-images.githubusercontent.com/1078012/36154322-f57fca66-10c8-11e8-87a5-e2c0d9112503.gif)

**Comment by DanTup** [comment]
Ugh, the GIF is kinda bad, but you can see it towards the end (the completion basically appears/disappears on alternating keypersses - when it doesn't appear is when it didn't invoke the completion provider). If it was invoking on ever key press it would look correct because the completion results would include the class name (which is being updated on each key press).

**Comment by jrieken** [comment]
Yeah, I can reproduce... Will take a look

**Comment by jrieken** [comment]
Simpler steps are

* type `d` and select it from left to right
* over-type the selection with `e`
* 🐛 no intellisense

**Comment by jrieken** [comment]
![mar-02-2018 16-11-08](https://user-images.githubusercontent.com/1794099/36905767-73b05ec8-1e34-11e8-8df3-1d2bfd38618f.gif)
