### ISSUE TITLE
VSCode spawns hundreds of Git processes when opening a project with lots of submodules

### ISSUE THREAD

**Issue by lediur** [Microsoft/vscode#43528]
- VSCode Version: 1.20.0 (also occurs on 1.21 Insider)
- OS Version: Windows 10 Pro 16299

Steps to Reproduce:

1. Open a folder containing a repo with a lot of submodules (e.g. https://github.com/github/linguist, which contains 300 submodules in the `vendors/grammars` subdirectory). The submodules must be initialized and updated for this bug to manifest, so you must init and update submodules after cloning https://github.com/github/linguist from scratch.
2. Wait some seconds, or open the Git pane
3. VSCode spawns hundreds of Git subprocesses all at once, which effectively fork bombs my machine for several minutes, during which the entire computer (OS, VSCode, mouse cursor) is completely unresponsive.
  ![image](https://user-images.githubusercontent.com/1077648/36112296-112d754c-0fde-11e8-8c10-c40418764270.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by lediur** [comment]
I did a test with the latest stable VSCode on a similarly specced MacBook Pro with macOS High Sierra. While there was a spike of high CPU activity, the machine remained responsive.

**Comment by joaomoreno** [comment]
Interesting. We can limit the automatic discovery of submodules to remain within sensible limits

**Comment by rizickus** [comment]
As I see it now limit is hardcoded to the maximum 10 submodules. Can this number be optional? Ironically, my current repo I am working on has 11 submodules and with latest VS Code version I have lost the ability to manage them nicely.

**Comment by joaomoreno** [comment]
@rizickus Yeah we can make it a setting. Note that you can always open a sub repository by opening a file within it.

**Comment by ChrisBartonLC** [comment]
@joaomoreno the last release was perfect for us but this release has made working with submodules harder. Of course I understand why the change was made. Oddly enough we also have 11 submodules and now we don't have good awareness of commits on them which we find useful because it helps teamwork. I would be happy with an 'Open All Submodule' command or a setting.
