### ISSUE TITLE
Erroneous `this` automatically added

### ISSUE THREAD

**Issue by arb** [Microsoft/vscode#43533]
### Issue Type
Bug

### Description

When I type a function name, "this" is prepended to it, even though I'm not inside a class. Below is a gif of it happening.
![wat](https://user-images.githubusercontent.com/1591483/36116845-b4b4d5c6-1005-11e8-95a0-3a8ab89175ca.gif)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1196324|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
EditorConfig|Edi|0.12.0
material-icon-theme|PKi|3.2.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.5
vscode-icons|rob|7.19.0
rewrap|stk|1.7.0
change-case|wma|1.0.0

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Please provide a complete code example

**Comment by arb** [comment]
I can't provide a completed code example as it is proprietary code. If there is a way to just disable the automatic `this` insertion, I'd be fine just disabling the setting.
