### ISSUE TITLE
[Feature Request] Open Powershell as native console

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#4353]
Could you add functionality to specify which console to open when using the `ctrl+shift+c` keyboard shortcut to run the command `workbench.action.terminal.openNativeConsole`
This would allow users to specify using Powershell over Cmd

**Comment by felixfbecker** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/1905

**Comment by stkb** [comment]
@tht13 You can use the [Open in User-defined Console](https://marketplace.visualstudio.com/items?itemName=vilicvane.console) extension

**Comment by felixfbecker** [comment]
@stkb that doesn't apply to right click > open command prompt here though

**Comment by stkb** [comment]
@felixfbecker That's true, but I was only replying to tht13 about his original request regarding the `ctrl+shift+c` shortcut.

Though if they implement the choice for the right-click menu they should do it for `ctrl+shift+c` action too, of course.

**Comment by joaomoreno** [comment]
Yeah, closing as duplicate of #1905.
