### ISSUE TITLE
Discard Changes and Stage Changes buttons are pretty close together

### ISSUE THREAD

**Issue by zlw11063** [Microsoft/vscode#43535]
The feature I'd like to suggest is a simple one. More of just an adjustment, rather than a feature. On the Source Control panel, the buttons for staging files and discarding changes are awfully close together. I haven't had any unfortunate coordination issues, thank goodness, but I had the thought that it might be helpful to move the discard button a bit further away. Floating it to the left next to the file name could be a solution. Just a suggestion. Great work on the editor.

**Comment by joaomoreno** [comment]
The discard button **always** has a confirmation dialog, so you'd be fine even if you click it.
