### ISSUE TITLE
Implementation suggestion for embedded language functionality

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#43538]
### Background
There have been many users requesting support for embedded languages. Use cases and arguments for this can be seen in #1751. Not only would user experience be improved by providing intellisense for the embedded language but, in the case of completion suggestions, they could be better controlled (eg emmet and word based suggestions). This ticket suggests a way in which intellisense inside embedded languages could be implemented.

### Implementation
A new `ErrorCode` would be added -- `LanguageRangeError` -- that would allow a language server to signal that it cannot fulfill a request because the request context is within an embedded language range and the server does not understand the syntax.

The advantage of this method is that it:
* Leverages the exsiting LSP.
* Avoids problems with message ordering should a language server have to instead send a notification containing language ranges.
* Avoids a round trip to the language server should language ranges instead need to be queried before the regular request. 

It also makes a distinction between an empty response -- the LS is the authority and there are no appropriate actions to be taken. And a "can't fulfill" response -- there still may be appropriate actions to be taken, just not by the queried language server (eg emmet, word based suggestions).

The existing LSP error response is:
```typescript
interface ResponseError<D> {
	/**
	 * A number indicating the error type that occurred.
	 */
	code: number;

	/**
	 * A string providing a short description of the error.
	 */
	message: string;

	/**
	 * A Primitive or Structured value that contains additional
	 * information about the error. Can be omitted.
	 */
	data?: D;
}
```

The error response in this case would be of type `ResponseError<LanguageRange[]>`. If `ResponseError.data` is set it would be expected that the `LanguageRange` items would be in order and continuous but not necessarily cover the full range of the document.

```typescript
interface LanguageRange {
    range:Range,
    languageId?:string
}
``` 

The behaviour of VSCode would be as follows.

1. VSCode makes a request to providers registered against the current document languageId. 
2. Receives an `LanguageRangeError` response.
3. If `ResponseError.data` is not set this signals that word based suggestions may be appropriate. Else continue to 4.
4. The request range context is identified in `ResponseError.data`. If `LanguageRange.languageId` is not set then word based suggestions may be appropriate or the language id taken from a user configuration (think of templating languages eg PHP with HTML v PHP with XML). If a language id is available then continue to 5.
5. The request would be forwarded to language servers listening on the new language id using a virtual document uri.
6. A document provider would provide the virtual document which would consist of the text between the returned ranges. The document provider would whitespace replace text in ranges identified with a different language id to that of the language id of the current range context.

### API
A `LanguageRangeError` would only be an appropriate error response for requests that have a `Position` parameter. API providers that could return such a response would include.

`CompletionItemProvider`
`DefinitionProvider`
`DocumentHoverProvider`
`DocumentHighlightProvider`
`ImplementationProvider`
`ReferenceProvider`
`RenameProvider`
`SignatureHelpProvider`
`TypeDefinitionProvider`

cc @aeschli

**Comment by felixfbecker** [comment]
This sounds very similar to the proposal I outlined in this comment: https://github.com/Microsoft/vscode/issues/670#issuecomment-330392419
https://github.com/Microsoft/vscode/issues/670#issuecomment-330964531 (continuation)

Except that mine does not work through errors but through a notification (similar to diagnostics) so that the editor knows up front what ranges are embedded languages instead of first having to attempt the request and the language server having to fail the response with the same range data every time.

**Comment by bmewburn** [comment]
Credit to @felixfbecker, I had been following his suggestions in #670 and #1751 . The main difference is the optimistic resolution. I assume that the language server knows all, until on occasion, it doesn't. There will be cases where this isn't true (eg a PHP view that is 80% HTML).

**Comment by jrieken** [comment]
This has already been discussed in various issues and on various occasions. The outcome is that VS Code won't do anything special for embedded languages and that it's the sole responsibility of the embedder, e.g. html must know that it embeds js and it must handle it.
