### ISSUE TITLE
Send didOpen requests after LS crashed

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode#43534]
I've reported the same issue over at https://github.com/Microsoft/vscode-languageserver-node/issues/304, but haven't gotten any reaction for more than three weeks, so trying here again :)

Direct quote from the other issue:

> This is the scenario: I have VS Code open, with a file open with unsaved changes. Now my language server crashes for some reason. VS Code restarts my language server. New LS instance starts up, but as far as I can tell this new instance never receives a didOpen request with the content of the unsaved file that is open in the editor. So now the state in the editor and the LS have diverged: my LS doesn't know about the unsaved edits in the file.

> So I guess one option would be that VS Code sends a didOpen request when it restarts a LS after a crash for all open files.

> Or is there some other way we should handle that?

This issue (bug?) is causing some serious problems in the julia language extension and we don't know what the correct way to handle it is.

Any feedback, comment would be greatly appreciated!

**Comment by davidanthoff** [comment]
@dbaeumer would be fantastic if we could get some response on this eventually, and even if it is "I don't have time to look into this for the next x weeks", then we could at least move forward with the julia extension. Right now our next release is blocked because of this issue.

**Comment by dbaeumer** [comment]
Sorry, I was out on vacation and very busy with other stuff for the Jan. release. Will comment on the original issue in the LS repository.

**Comment by davidanthoff** [comment]
Cool, thanks! And sorry to be ungeduldig :)
