### ISSUE TITLE
Internal Typo With JavaScript Intellisense

### ISSUE THREAD

**Issue by Gisgar3** [Microsoft/vscode#43541]
While working on a bot for Discord, I noticed that there was a typo in the Intellisense results for JavaScript. The below image shows the MessageBox with the typo: 
![bug1](https://user-images.githubusercontent.com/24739483/36120963-d6338758-1012-11e8-8bd4-bdad0ed0aaa3.PNG)  

Within the MessageBox, you can see that 'their' is misspelled as 'thier.' Simple mistake, but thought it was okay to make an issue for.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21905
