### ISSUE TITLE
php code syntax highlighting does not work in markdown files

### ISSUE THREAD

**Issue by nicholascloud** [Microsoft/vscode#43545]
- VSCode Version: 1.20.0

<img width="396" alt="screen shot 2018-02-12 at 4 29 57 pm" src="https://user-images.githubusercontent.com/513420/36123362-ff7b6d84-1011-11e8-9062-424a0a86a25e.png">

- OS Version: OSX 10.13.3

<img width="698" alt="screen shot 2018-02-12 at 4 30 32 pm" src="https://user-images.githubusercontent.com/513420/36123386-13910e0a-1012-11e8-9135-b438c10fdd18.png">

Steps to Reproduce:

- open empty editor
- set file type to markdown
- add php code snippet

<img width="259" alt="screen shot 2018-02-12 at 4 32 34 pm" src="https://user-images.githubusercontent.com/513420/36123476-5a2235d8-1012-11e8-85ce-84a65e69f87f.png">

- **observe php syntax highlighting does not work**
- add additional code snippets for other languages

<img width="341" alt="screen shot 2018-02-12 at 4 33 42 pm" src="https://user-images.githubusercontent.com/513420/36123517-8aa5f46a-1012-11e8-89f7-a16c3910070c.png">

- observe syntax highlighting works

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

c.f.: [twitter thread with VSCode support](https://twitter.com/nicholascloud/status/961643518820306944)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#9
