### ISSUE TITLE
"Go to symbol ..." does not behaves like before the 0.10 version

### ISSUE THREAD

**Issue by ElCondor1969** [Microsoft/vscode#4354]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Hi to all.
Since I installed the version 0.10 of the program the symbol search command does not behave the same as before.
For example, consider the following code in Javascript:

`var a={
  Func: function() {
    return true;
  }
};`

Before the 0.10 version if you search the symbols using the command "Go to symbol ..." (CTRL + SHIFT + O), the FUNC function was present in the results list.
With version 0.10 instead the FUNC function it is absent from the list of results.
Notice that the Chrome debugger , searching for symbols by the CTRL + SHIFT + O command, shows properly the FUNC function in the results list.

Bye.

**Comment by lpproulx** [comment]
I'm also seeing this behavior. It was working fine before switching to salsa.

![image](https://cloud.githubusercontent.com/assets/1503865/13850650/3f5fe3be-ec31-11e5-9986-cdc67f967715.png)

**Comment by egamma** [comment]
This has been addressed in TypeScript 1.8.9 and we have integrated 1.8.9 yesterday. We will push an update with this changes to the [insider channel](https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build) next Monday.
