### ISSUE TITLE
Feature Request: collapse all tabs from side-by-side mode into single editor group

### ISSUE THREAD

**Issue by breathe** [Microsoft/vscode#43542]
I searched but couldn't find this functionality or a similar feature request -- so thought I would propose feature.

It would be nice to be able easily exit side-by-side mode by collapsing all the tabs in all editor groups into one editor-group without duplicate views of the same file.  

I find that typically over time I end up with my tabs somewhat haphazardly spread across editor-groups without a solid conceptual model for which editor-group a given file might be in.  When this happens I typically want to collapse everything back into a single editor-group -- then gradually I will move specific tabs to one of the side-views based on whatever I'm currently working on when I find I want easy reference access to that particular file ...  Eventually I'll end up with 'too many' tabs in the side-view and simply want to re-collapse them all again ...

This feature would also be convenient to use sometimes after switching to a laptop from a larger screen.

**Comment by usernamehw** [comment]
`workbench.action.joinTwoGroups` ?

**Comment by breathe** [comment]
Thank you @usernamehw!
