### ISSUE TITLE
Duplicated [ts] hints

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#43554]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

We have something like this:

![dupe1](https://user-images.githubusercontent.com/24613274/36130607-584297e4-1076-11e8-9e9e-fdcae23d1324.png)

... and if we hover on the "x" - there would be a TypeScript hint about duplicate. But it's duplicated by itself.

![dupe2](https://user-images.githubusercontent.com/24613274/36130671-9dc781bc-1076-11e8-821c-2514b72d3f10.png)

Is that a bug?

**Comment by mjbvz** [comment]
Please share the code for your example. Also, does this still  happen if you disable all extensions?

**Comment by user3323** [comment]
@mjbvz 

**_file.ts_**
```
class Point {

  constructor(private x?: number, private y?: number) {

  }

  get x() {
    return this.x;
  }

}
```

Yes, it does happen with disabled exts.

**Comment by mjbvz** [comment]
Thanks! Opened https://github.com/Microsoft/TypeScript/issues/21923 to track this upstream
