### ISSUE TITLE
[PHP] variable selection doesn't work (anymore)

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#4355]
- VSCode Version: 0.10.11
- OS Version: Windows 10 Pro (Version 1511; OS Build: 10586.164)

Steps to Reproduce:

1. Double click some variable within php
2. See that it doesn't select the variable, only the text

![vs_code_variable_select](https://cloud.githubusercontent.com/assets/7961978/13844045/88a2af88-ec37-11e5-9df5-8821ced18cb8.gif)

This worked fine in some previous versions.

**Comment by alexandrudima** [comment]
@Morgy93 From popular user demand, the cursor double clicking, word navigation and word deletion now respect a new setting called `editor.wordSeparators`. This allows you to define, as best suits your workflow how these features should behave.

In this case, you can change the default to remove $ as a word separator:

```
"editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"
=>
"editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
```

**Comment by alexandrudima** [comment]
This, and many other changes, can always be tracked in the [Release Notes](https://code.visualstudio.com/Updates).
