### ISSUE TITLE
"Focus editor group" commands don't work on readonly editor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#43550]
- Open a readonly editor, e.g. by debugging eval code or inlined sources
- Focus somewhere in the workbench 
- Press cmd+1
- Nothing happens, should focus editor. Works when the editor is not readonly

**Comment by bpasero** [comment]
@roblourens I cannot reproduce when I run "out of sources" at least. Are you sure you did not configure some keybinding?

**Comment by roblourens** [comment]
Today it works. Not sure what I was seeing, sorry.
