### ISSUE TITLE
Singleline heredoc causes following lines to be rendered as Strings

### ISSUE THREAD

**Issue by otbutz** [Microsoft/vscode#43567]
- VSCode Version: 1.20.0
- OS Version: Win 10 x64 1709

Minimal working example:

```sh
#!/bin/bash
sudo tee -a  /etc/environment <<< "http_proxy=\"http://${http_proxy_input}\""
echo "This is not rendered as String"
```

VSCode
![vscode](https://user-images.githubusercontent.com/22315436/36141683-fb2bf994-10a5-11e8-9b74-6c2401fbc087.png)

Notepad++
![notepadplusplus](https://user-images.githubusercontent.com/22315436/36141686-fef11e88-10a5-11e8-9dfc-9c6ccbfdac56.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#108
