### ISSUE TITLE
Search in Terminal (Ctrl+F) finds just one match per line

### ISSUE THREAD

**Issue by Dzugaru** [Microsoft/vscode#43566]
### Issue Type
Bug

### Description

1. Ctrl+F in Terminal
2. Try searching (and clicking "Next match") for something that appears several times on one line

https://monosnap.com/file/cO6oUEe4ZD1mjY7laD0Ty3XdfiXHfE

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (91120eb786357aa1e16217ad6a67cf0740f26e8e, 2018-02-08T05:16:13.920Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|Memory (System)|7.89GB (2.83GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled
Reproduces without extensions

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28768
