### ISSUE TITLE
Allow to use touch for drag and drop operations

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/vscode#43562]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.24

---

Steps to Reproduce:

1. Open VS Code on a Surface Laptop running Win10 and split multiple tabs
2. Use a finger to try to drag one tab from one split to the other

Nothing happens. Dragging & dropping with a mouse / touchpad works fine.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
There is literally no drag and drop support in any UI component using touch.

**Comment by JoshuaKGoldberg** [comment]
> There is literally no drag and drop support in any UI component using touch.

Well, darn. 

What are your / the team's thoughts on adding this in? Are there any sets of incremental tracking items or known blockers in the way?
