### ISSUE TITLE
Panel titles in Settings not styled properly

### ISSUE THREAD

**Issue by mbenkmann** [Microsoft/vscode#43568]
- VSCode Version: 1.20.0
- OS Version: Linux

The Settings Window has 3 panels "DEFAULT SETTINGS", "USER SETTINGS" and "WORKSPACE SETTINGS". The title color of the "DEFAULT SETTINGS" panel seems to be hardcoded, which I guess is acceptable if not ideal.
The title color of "USER SETTINGS" and "WORKSPACE SETTINGS" is panelTitle.activeForeground when it is active, but a hardcoded color if inactive. Instead the inactive panel should follow panelTitle.inactiveForeground.

Furthermore, if contrastActiveBorder is unset by the user settings, the active panel's title is underlined. If contrastActiveBorder is set, even to a completely transparent color, the underline disappears. There does not seem to be a way to style that underline independently.

Both of the above are problems if you use the high contrast base theme but set the contrastActiveBorder to transparent in user settings because it's ugly and buggy (see different issue from me). It makes it so that the active panel's title cannot be underlined and the inactive panel's title cannot be set to a more subdued color. So it's hard to make obvious which of the 2 panels is selected.

To fix this:
* the inactive panel title's color should obey panelTitle.inactiveForeground
* the underline under the active panel title should have a color (which themes may set to transparent if desired) independent of contrastActiveBorder

Side note: The inactive panel titles in the PROBLEMS/OUTPUT/... side panel do obey panelTitle.inactiveForeground. The problem with the underline being tied to contrastActiveColor exists in that side panel, too, unfortunately.

**Comment by sandy081** [comment]
You can change the underline colour using `panelTitle.activeBorder`.

Fixed inactive tabs in settings editor to use `panelTitle.inactiveForeground`

Verify that colour of inactive tabs in settings editor can be customised using `panelTitle.inactiveForeground`
