### ISSUE TITLE
search.followSymlinks have no affect in linux 

### ISSUE THREAD

**Issue by asmorodskyi** [Microsoft/vscode#43573]
- VSCode Version:  1.20.0-1518023659.el7  ( same behavior for few versions before ) 
- OS Version:  openSUSE Leap 42.3 

Steps to Reproduce:

Do search for some text which present only in folder available via symlink in project with   search.followSymlinks = true

==> nothing found 

Expected : code will follow symlink during search and find desired pattern

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This probably isn't related to symlinks. Do you find results for all other files that aren't behind symlinks? Do you find results for that file if it is not behind a symlink?


Do make sure it isn't excluded by a setting or gitignore file, try toggline the "Use Excludes and Ignore Files" button (bottom right)
![image](https://user-images.githubusercontent.com/323878/35752446-e01ea914-0810-11e8-8d1e-9877a751c5ca.png)

**Comment by asmorodskyi** [comment]
1. checkout project  https://github.com/os-autoinst/os-autoinst-distri-opensuse
2. checkout somewhere else project https://github.com/os-autoinst/os-autoinst
3. create a symlink for os-autoinst inside os-autoinst-distri-opensuse
so you will have something like this :
```
asmorodskyi@e113:/var/lib/openqa/share/tests/sle> ls -la
total 208
drwxrwsr-x 11 asmorodskyi openqa   4096 Feb  9 17:53 .
drwxr-xr-x  4 geekotest   root     4096 Nov 26 16:28 ..
-rw-r--r--  1 asmorodskyi openqa    309 Jan 19 10:51 cpanfile
drwxrwsr-x 31 asmorodskyi openqa   4096 Jan 23 14:58 data
drwxrwsr-x  8 asmorodskyi openqa   4096 Feb 14 09:18 .git
drwxr-sr-x  2 asmorodskyi openqa   4096 Nov  1 19:17 .github
-rw-r--r--  1 asmorodskyi openqa     83 Feb  6 16:23 .gitignore
drwxrwsr-x  3 asmorodskyi openqa   4096 Feb 12 09:16 lib
-rw-r--r--  1 asmorodskyi openqa   2615 Dec  4 07:37 Makefile
lrwxrwxrwx  1 asmorodskyi openqa     37 Jan  2 11:15 os-autoinst -> /home/asmorodskyi/source/os-autoinst/
lrwxrwxrwx  1 asmorodskyi openqa     23 Jun 12  2017 .perltidyrc -> os-autoinst/.perltidyrc
drwxrwsr-x  6 asmorodskyi openqa   4096 Aug 24 15:36 products
-rw-r--r--  1 asmorodskyi openqa   2287 Mar 31  2017 README.md
drwxrwsr-x  2 asmorodskyi openqa   4096 Jan  2 14:08 script
drwxrwsr-x 40 asmorodskyi openqa   4096 Feb  6 16:23 tests
drwxrwsr-x  2 asmorodskyi openqa   4096 Dec 21 13:02 tools
-rw-r--r--  1 asmorodskyi openqa    290 Oct  4 15:58 .travis.yml
-rw-r--r--  1 asmorodskyi openqa    934 Jan 26 14:27 variables
drwxr-sr-x  2 asmorodskyi openqa   4096 Nov 20 10:08 .vscode
-rw-r--r--  1 asmorodskyi openqa 141503 Feb 14 09:18 .vstags

```
4. try to search for "sub script_output" inside Code where you used "Open folder" for os-autoinst-distri-opensuse. This string exists only inside os-autoinst so it could be found only with proper use of followSymlinks feature 
==> it is not happening

**Comment by asmorodskyi** [comment]
![screenshot from 2018-02-14 09-24-50](https://user-images.githubusercontent.com/23258171/36194792-7491ca0a-116b-11e8-8495-b8e3ecfa5912.png)

string not for for os-autoinst-distri-opensuse

**Comment by asmorodskyi** [comment]
![screenshot from 2018-02-14 09-24-57](https://user-images.githubusercontent.com/23258171/36194824-8a4758e2-116b-11e8-87d4-c74b41a30612.png)

same string found when you open directly os-autoinst

**Comment by asmorodskyi** [comment]
Hi @roblourens , 
I still see "needs more info" label on issue. Not trying to push you - just clarifying - does it mean that my answer is not actually answers your questions or you don't have enough time to review it ?
