### ISSUE TITLE
Go To Next Error does not go to next error

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/vscode#4357]
- VSCode Version: 0.10.11
- OS Version: OS X

Steps to Reproduce:

When I press F8 I can navigate to the next error in the current file. But when I remove all errors in a current file and I press F8 it does not navigate to the error in the next erroneous file. Is this a bug or a feature? Thanks

**Comment by jrieken** [comment]
That is how it's meant to work. The editor has no notion of a _next file_. There is talk about a dedicated error view (at the bottom) but for now 'F1 > Show Errors & Warnings' is the workaround

**Comment by tomitrescak** [comment]
Thought so. The dedicated error view would be a killer! Thanks
