### ISSUE TITLE
TypeScript Reference CodeLens - get references from all providers

### ISSUE THREAD

**Issue by ekulabuhov** [Microsoft/vscode#43574]
- VSCode Version: 1.20.0
- OS Version: Ubuntu 16.04 LTS

Current implementation uses ITypeScriptServiceClient to count all the references:
https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/referencesCodeLensProvider.ts#L41

Would it be feasible to ask for references provided by extensions too? (e.g. `vsc.languages.registerReferenceProvider(<language>, <referencesProvider>`)?

**Comment by mjbvz** [comment]
What problem are you trying to solve? Can you provide an example

**Comment by ekulabuhov** [comment]
Example: I have installed an extension that helps me with code navigation. For example it adds "Go to Definition" and "Find All References" functionality between HTML template file and the controller. The problem is when I right click in the code editor and select "Find All References" I get a different list of references to the one I get from clicking on the "x references" CodeLens.

I believe it's happening because it's calling different code in these two cases.

**Comment by octref** [comment]
@mjbvz How to verify this? @ekulabuhov Can you try the insider build to see if this fixes your problem?

https://code.visualstudio.com/insiders/

**Comment by mjbvz** [comment]
Download and install this extension: 
[fake-ref-0.0.1.vsix.zip](https://github.com/Microsoft/vscode/files/2421069/fake-ref-0.0.1.vsix.zip)

It consists of:

```ts
import * as vscode from 'vscode';

const provider = new class implements vscode.ReferenceProvider {
    async provideReferences(document: vscode.TextDocument, _position: vscode.Position, _context: vscode.ReferenceContext, _token: vscode.CancellationToken): Promise<vscode.Location[]> {

        return [new vscode.Location(document.uri, new vscode.Position(0, 0))];
    }
};

export function activate(_context: vscode.ExtensionContext) {
    vscode.languages.registerReferenceProvider('javascript', provider);
}
```

1. Open a js file such as:
```
// first

class Foo {};
class Boo {};
```

1. Enable references code lens in file
1. See 1 reference on the classes. Confirm it comes from the fake reference provider (it should be on the first line of the document)

**Comment by octref** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/4033249/46101784-a94ae580-c181-11e8-949e-97c9a92ef8d5.png)
