### ISSUE TITLE
Cannot select Python interpreter in a multi-root folder workspace

### ISSUE THREAD

**Issue by kentwait** [Microsoft/vscode#43572]
- VSCode Version: 1.20.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Create a workspace
2. Add a folder A to the workspace
3. Add another folder B to the workspace
4. Set folder-specific Python interpreter for folder B. Folder should now have a .vscode/settings.json file.
5. Open a Python file in folder B. Import will fail for packages only installed within the virtual environment. Specific interpreter set in folder settings is not used in multi-root workspace. Opening only folder B, vscode loads the correct interpreter.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
