### ISSUE TITLE
Integrated terminal is sh instead of gnome-terminal (Linux Mint)

### ISSUE THREAD

**Issue by zbendefy** [Microsoft/vscode#43578]
Hi!
I use Linux Mint 18.3 (64bit cinnamon), and I Updated from 1.19 to 1.20.0.
Previously the integrated terminal used the gnome-terminal, but now since 1.20 it uses the sh terminal.

This causes C++ debugging to be unavailable since the debugger cannot start with the sh terminal (I get the error message: **Unable to start debugging. No terminal is available to launch the debugger. Please install Gnome Terminal or XTerm)**

**Comment by Tyriar** [comment]
@zbendefy did you used to get gnome-terminal pop up in another window when you started debugging?

**Comment by zbendefy** [comment]
No, it did not pop up, only the error message. Previously (on 1.19) it popped up though. I have the following extensions installed:
CMake
CMake tools
CMake tools helper
C++ (the microsoft extension)

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#1553

**Comment by zbendefy** [comment]
I tried the following:
- Set "terminal.integrated.shell.linux": "/usr/bin/gnome-terminal", but it didnt work, VSCode cant find the specified file. I checked on the file system but its there.

Next I tried to locate the file in the integrated terminal (which is an sh instead of the regular terminal), and when I ran ls on /usr/bin, there was no gnome-terminal there (even though in the file explorer, and in an linux mint terminal it is there)

**Comment by weinand** [comment]
duplicate of https://github.com/Microsoft/vscode-cpptools/issues/1550

**Comment by weinand** [comment]
@zbendefy your issue has been closed because it is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/1550 (which is still open).
