### ISSUE TITLE
Git console error when started on a non-existing workspace folder

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#43580]
Create a workspace description where the first workspace folder doesn't exist
```
{
	"folders": [
		{
			"path": "../bla-bla"
		}
	],
	"settings": {
	}
}
```
Check the console:
[Extension Host] rejected promise not handled within 1 second (at Console.originalConsole.(anonymous function) [as warn] (/home/aeschli/workspaces/vscode/extensions/git/node_modules/diagnostic-channel-publishers/dist/src/console.pub.js:42:39))

**Comment by joaomoreno** [comment]
@aeschli This feels very wrong to me. This should be handled somewhere above. Otherwise, you're gonna need every extension to do `fs.exists`. IMO the git extension shouldn't even be activated if the folder doesn't exist.

**Comment by joaomoreno** [comment]
cc @bpasero
