### ISSUE TITLE
Output Window is removing new lines

### ISSUE THREAD

**Issue by MrVallentin** [Microsoft/vscode#4358]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:
1. Printing any line that only contains a new line to the output window.

This might be by design. But it would be much appreciated, if the output window didn't ignore lines only containing new lines. Personally I like to split out outputted chunks for text with new lines for ease of readability.

It also looks like the output window is printing per line-break, as the "extra" new line in `"Test\n\nTest\n"` still isn't printed.

My current _workaround_ is adding a single space before the new line. Though this adds complication.

**Comment by isidorn** [comment]
@MrVallentin are you writing an extension that writes to the output?
Or are you debugging the program that writes to the debug repl?

Small sample where this is reproduced would also be useful.

**Comment by MrVallentin** [comment]
@isidorn the output is coming from programs launched by the "Tasks: Run Build Task". It happens no matter which program I've been using (as I would expect). Python, Lua, Batch, exe, etc.

To be more specific, I've been doing a lot of Python lately, and for ease of testing/execution, I've used the following task:

```json
{
	"version": "0.1.0",
	"showOutput": "always",
	
	"windows": {
		"command": "python",
		"showOutput": "always"
	},
	
	"args": [ "${workspaceRoot}/main.py" ]
}
```

**Comment by isidorn** [comment]
@MrVallentin can you past the example of main.py so I try to reprodcue this issue on my machine?

**Comment by MrVallentin** [comment]
@isidorn it really is just:

```python
print("Test")
print("")
print("Test")
```

Which results in:
```
Test
Test
```

Instead of:
```
Test

Test
```

But as soon as you simply add a space:
```python
print("Test")
print(" ") # tiny little space
print("Test")
```

Then it does successfully print:
```
Test

Test
```

As said it doesn't matter what application is running as a task, whether
it is C++ printing:
```cpp
std::cout << "Test" << std::endl;
std::cout << std::endl;
std::cout << "Test" << std::endl;
```

C:
```c
printf("Test\n");
printf("\n");
printf("Test\n");
```

or Lua:
```lua
print("Test")
print(" ")
print("Test")
```

VSCode always removes lines only consisting of a single new line.

**Comment by isidorn** [comment]
This is happening because the `processRunnerSystem` is not calling [outputChannel.append](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/node/processRunnerSystem.ts#L307) for empty output. Forwarding to @dbaeumer

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.12.0-insider (d8a1d8b8a7c886547ba6bc0d81fc2ff639d4c9f5, 2017-04-27T06:05:48.177Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none

Still repros in both the Output panel and the Debug Console with task.json:
```json
{
  "version": "0.1.0",
  "command": "node",
  "args": ["4358.js"]
}
```

4358.js:
```js
console.log('foo');
console.log('');
console.log('bar');
```

**Comment by dbaeumer** [comment]
Strange the python test case worked for me. Will check what is different with JS. Interesting is also that this repros in the Debug panel. This fix I did was only in task land. So this might be a different issue with JS.

**Comment by dbaeumer** [comment]
Could reproduce. There is still a bug in the LineDecoder. In the JS case to strings are coming. One `foo\n` and one `\nbar\n` which in not handled correctly. Will fix that case in May
