### ISSUE TITLE
Command palette and quick open cannot have their suggestions navigated with custom keybinds.

### ISSUE THREAD

**Issue by Kinths** [Microsoft/vscode#43583]
- VSCode Version: 1.20.0
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Rebind list.FocusUp/down
2. Open command palette or quick open
3. Attempt to navigate suggestion list with custom keybinds

Does this issue occur when all extensions are disabled?: Yes

Full disclosure: I have opened this issue before, it was closed saying that list.focusUp/Down achieves this functionality. I have tested this (as well as selectNextSuggestion) and it does not achieve this functionality. After a brief look at the code for the quick open widget I think I may have figured out why.  Because quick open and command palette have input fields that are focused, the relevant keybindings need to be passed down to the tree. However, in the code for quick open these keybindings are hardcoded to down/up and page/down up. https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L198

As far as I can tell custom keybinds for list navigation are never passed down to the tree.

**Comment by bpasero** [comment]
@Kinths you will have to use this command instead: `workbench.action.quickOpenNavigateNext` and `workbench.action.quickOpenNavigatePrevious`
