### ISSUE TITLE
openTextDocument never completes (or opens file) in tests

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43581]
I'm trying to write some tests for my extension but I'm unable to a file opened.

Code looks like this:

```ts
const ext = vs.extensions.getExtension("Dart-Code.dart-code");
const helloWorldFolder = vs.Uri.file(path.join(ext.extensionPath, "test/data/hello_world"));
const helloWorldFile = vs.Uri.file(path.join(helloWorldFolder.fsPath, "bin/main.dart"));

describe("dart_hover_provider", () => {
	let doc: vs.TextDocument;
	let editor: vs.TextEditor;

	before(async () => {
		await ext.activate();
		await vs.commands.executeCommand("vscode.openFolder", helloWorldFolder);
		console.log("OPENING " + helloWorldFile.fsPath);
		console.log("EXISTS? " + fs.existsSync(helloWorldFile.fsPath));
		doc = await vs.workspace.openTextDocument(helloWorldFile);
		console.log("OPENED");
		editor = await vs.window.showTextDocument(doc);
		console.log("SHOWED");
	});
```

This code outputs:

> OPENING m:\Coding\Applications\Dart-Code\test\data\hello_world\bin\main.dart
dart_hover_provider.test.ts:17
> EXISTS? true

However it then hangs. The file never opens in the dev host window that's spawned (the folder has opened). I've tried `openTextDocument` with both the `Uri` and it's `fsPath` but they behave the same.

![doesnt open](https://user-images.githubusercontent.com/1078012/36147950-20e72fda-10b2-11e8-95a7-2d66801f7434.png)

**Comment by DanTup** [comment]
The code is here:

https://github.com/Dart-Code/Dart-Code/commit/2622ceab605d9505a22bdad893c1d43ddefb188e
it's on the `automated-tests` branch. The latest changeset simply comments out this test (`dart_hover_provider.test.ts`).

Note: You'll need a valid Dart SDK in `PATH` (or extracted somewhere and the `dart.sdkPath` pointing at it) before running.

**Comment by DanTup** [comment]
Nothing useful in the consoles of either Code instance (though it breaks on a bunch of rejected promises from looking for Git).

**Comment by DanTup** [comment]
Passing the `Uri` to `showTextDocument` (skipping `openTextDocument`) also made no difference, still sat waiting.

**Comment by DanTup** [comment]
Calling `await vs.commands.executeCommand("vscode.open", helloWorldFile);` seems to have the same behaviour.

**Comment by DanTup** [comment]
@jrieken Based on comments in #43677 by @bpasero I now think this is because of the `vscode.openFolder` command causing the window to be reloaded (and the tests aborted)?

Are there any example tests that open folders I can look at? I can't figure out how I should do this?

**Comment by jrieken** [comment]
@bpasero will know (I believe he added multi-root tests). Generally, 'yes' opening a folder can trigger a reload, best would be start with an (event empty) workspace

**Comment by DanTup** [comment]
There's nothing really in my test before opening the folder (except activating the extension) so I'm not really sure what I could remove. I'm not entirely familiar with how the test code runs (eg. whether it's inside an extension and therefore affected by reloads).

I'm happy to dig through someone elses tests to figure this out if someone can point me in the direction of some :)

**Comment by bpasero** [comment]
@jrieken @DanTup yes, there are some simple tests for multi-root by pointing the text runner to a workspace file: https://github.com/Microsoft/vscode/blob/master/scripts/test-integration.sh#L17

**Comment by jrieken** [comment]
closing as question

**Comment by DanTup** [comment]
Aha, I see. In this case it's just a folder, but same deal (passing as an arg when launching the tests from the `npm test` command) works. Thanks @jrieken!

**Comment by danielpinto8zz6** [comment]
hi, can you show me how you fixed? thx

**Comment by DanTup** [comment]
@danielpinto8zz6 Pass the folder/workspace file as an argument when launching the tests.

eg. Line 53 here for `launch.json`:

https://github.com/Dart-Code/Dart-Code/blob/c1e3928f4ca3d49868e2119c2b4c12b304e7454f/.vscode/launch.json#L48-L65

And for `npm test` you can set the `CODE_TESTS_WORKSPACE` env variable. I have this all in [a script](https://github.com/Dart-Code/Dart-Code/blob/c1e3928f4ca3d49868e2119c2b4c12b304e7454f/test/test_all.ts#L65-L66) because I run the tests multiple times (for dev + stable versions of Code, Dart SDK, Flutter SDK, and also multiple sets of tests that use different workspaces).

**Comment by danielpinto8zz6** [comment]
@DanTup Thank you so much
