### ISSUE TITLE
Add search history to all search boxes

### ISSUE THREAD

**Issue by leocb** [Microsoft/vscode#43587]
### Issue Type
Feature Request

### Description

A really usefull feature would be a history of searched terms (not the search results)
my suggestion is: When pressing arrow up or down on search boxes, we could bring a history of past search terms, just like the terminal does for commands.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.13.0-32-generic

**Comment by roblourens** [comment]
It exists for all of these - keyboard shortcut is alt+up/down
