### ISSUE TITLE
Unix -opening and closing for `` is not getting detected properly

### ISSUE THREAD

**Issue by ethic123** [Microsoft/vscode#43582]
### Issue Type
Bug

### Description

In Unix Script, Create a sqlplus session using ``. You will see that it is detecting the opening grave (accent) not the closing one.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.14393

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.24
python|ms-|2018.1.0

</details>
Reproduces without extensions

**Comment by egamma** [comment]
@ethic123 please provide a snippet that illustrates the problem.

**Comment by ethic123** [comment]
Please try below snippet in VSCode
![image](https://user-images.githubusercontent.com/13498501/36154853-b66f754e-10f8-11e8-80f7-be6f39228613.png)


echo $abc

abc=`sqlplus -S $user/$password@"$tns" <<-EOF
        SET ECHO OFF;
        SET HEADING OFF;
        SET PAGESIZE 0;
        SET TERMOUT OFF;
        SET SERVEROUTPUT ON;
        SELECT 1 FROM DUAL;
        exit;
		EOF`

echo $abc

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#109
