### ISSUE TITLE
Git Discard Changes has to be run twice to clear changes

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode#43589]
- VSCode Version: 1.20.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Git repository in VS Code
2. Modify a file in that project
3. Go to the UI (or command palette) and discard changes.
4. Click "Discard Changes" to the prompt
5. Git will still show pending changes in the file.

Does this issue occur when all extensions are disabled?: Yes

[VSCode_GitDiscardChanges.zip](https://github.com/Microsoft/vscode/files/1720334/VSCode_GitDiscardChanges.zip)

**Comment by joaomoreno** [comment]
Please check your CRLF settings: https://help.github.com/articles/dealing-with-line-endings/

Also, run `git status` between both actions to understand what the state of the repository is.

Use `Git: Show Git Output` to see which git commands Code runs and try running them manually.

**Comment by wsmelton** [comment]
@joaomoreno The video shows the result of using `git status`.

**Comment by wsmelton** [comment]
After installing 1.20.1 I no longer see this issue.
