### ISSUE TITLE
When text is copied and pasted, its indentation changes

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#43586]
### Issue Type
Bug

### Description

When I select a piece of indented HTML, say 3 lines, copy and immediately paste, the selected/pasted block is de-indented.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.87GB (8.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
vscode-bad-code-highlighter|bha|0.1.6
unique-lines|bib|1.0.0
featurehighlight|Blo|1.4.1
find-related|eam|0.6.0
vscode-duplicate|mrm|1.2.0
oracle-plsql|myc|1.0.3
selectline-statusbar|tom|0.0.2
gitblame|wad|2.2.0
cursor-align|yo1|1.0.4

</details>
Reproduces without extensions: Yes

**Comment by egamma** [comment]
@PunchyRascal please provide a snippet that illustrates the problem.

**Comment by PunchyRascal** [comment]
![indent-bug](https://user-images.githubusercontent.com/821272/36158118-cc9a05a4-10db-11e8-94e7-f8a039e09eb4.gif)

**Comment by aeschli** [comment]
Reproduced with
```
<div>
	<div>
		<div>
			<a href=""></a>
			<a href=""></a>
		</div>
	</div>
</div>
```
Looks like an issue with `"editor.autoIndent"`.

The issue doesn't appear with `"editor.autoIndent": false`

**Comment by rebornix** [comment]
Thanks all for your feedback, let's track this issue in https://github.com/Microsoft/vscode/issues/32320 , which talks about similar bug (indentation adjustment when pasting, moving, entering) in HTML/PHP like language. All your input will be considered when we tackle this issue.
