### ISSUE TITLE
Valid regex lookahead not working on folder search

### ISSUE THREAD

**Issue by leocb** [Microsoft/vscode#43584]
- VSCode Version: 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b - 2018-02-07T17:10:15.949Z)
- OS Version: Ubuntu 17.10 4.13.0-32-generic

VScode project wide search is not working with valid regex look ahead - both negative and positive look ahead doesn't work.
![selection_009](https://user-images.githubusercontent.com/8310271/36150955-a61426b4-10ac-11e8-8f17-60349ba32f69.png)
![selection_010](https://user-images.githubusercontent.com/8310271/36150956-a6384c1a-10ac-11e8-8072-eaff6fce8056.png)

Steps to Reproduce:

1. Create a new folder and open VSCode on it.
2. Create a new file
3. Type "this is a test string" as the file content and save
4. Press Ctrl + F and search for "test(?=\s?string)" with regex active - see that this works
5. Try the same search on the project search tab (Ctrl + Shift + F), an error about invalid flag is displayed.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by roblourens** [comment]
These are not supported, because folder search uses ripgrep which doesn't support these regex features https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options
