### ISSUE TITLE
Explorer lists home folder on file open

### ISSUE THREAD

**Issue by miedmondson** [Microsoft/vscode#43596]
### Issue Type
Performance Issue

### Description

On Mac, when dragging and dropping a file onto VSCode icon in the Dock, a new window opens with my home directory in the Explorer sidebar. This starts reading a lot of files, heating up the CPU, when there is little chance that I want to browse my home directory in VSCode. Note: This is an entirely different experience compared to if you open a New Window, in which case my home directory is not read into the Explorer sidebar. Is there a flag to disable showing my home directory in the Explorer? Should drag'n'drop'ing a file load the relative local directory of the file instead?

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

Reproduces without extensions

**Comment by bpasero** [comment]
@miedmondson is that file direct parent the home directory and does that one contain a .vscode folder?

**Comment by miedmondson** [comment]
The file was under ~/Desktop/.
I was also having similar problems when using Transmit (SFTP client) to "remotely edit" files -- it downloads a local file under ~/Library/Caches/Transmit/{UUID}/ to edit, then upload -- but then I found a .vscode folder in my home directory. Renaming it solved my issue; well, each attempt to edit opens in an existing window instead of a new window, but no more CPU-spiking.

**Comment by bpasero** [comment]
@chrmarti again this is due to the fact that we open the folder if we find a .vscode folder it in the parent chain. Maybe we should be smarter and detect common places like "~" to prevent opening a potential very large folder by accident?

**Comment by chrmarti** [comment]
For `~` there already is an additional check for `settings.json`, if that does not exist that `.vscode` folder is ignored.

**Comment by bpasero** [comment]
@miedmondson do you have a settings.json file in that folder (~/.vscode)?

**Comment by miedmondson** [comment]
@bpasero Yes, I have a ~/.vscode/settings.json.

Removing it gave the same behavior as removing ~/.vscode:
- Dragging and dropping a file onto VSCode icon in dock opens file in an existing window
- Editing a remote file using Transmit opens the file in an existing window

No CPU spiking.

**Comment by bpasero** [comment]
@chrmarti I think we should disable this always when it comes to "~" because we know this can be a very large folder and imho it is unlikely that someone would use this as a development folder.

**Comment by bpasero** [comment]
@chrmarti another thing to keep in mind is that this folder often contains single configuration files that users might want to edit without opening the entire home directory (e.g. `bash_profile`). 

We could also think about making this a setting, but then I would disable it by default.

**Comment by chrmarti** [comment]
@chrmarti There is usually no `~/.vscode/settings.json`, so users should really only see this if they opened `~` before and added some settings there. 🤔

**Comment by bpasero** [comment]
@chrmarti which can often be something that happens without the user being aware of, e.g. configuring a task or a launch config. Maybe we should add telemetry how often we open the home folder and how often the user then moves away from that to a single file.

**Comment by chrmarti** [comment]
@miedmondson Do you remember what settings were in `.vscode/settings.json`? I wonder if you placed these there accidentally or if maybe an extension was writing something there.

@bpasero `tasks.json` and `launch.json` are not checked for, only `settings.json`.

**Comment by bpasero** [comment]
@chrmarti ok I see

**Comment by miedmondson** [comment]
@chrmarti It was some configs for haxe.

https://github.com/vshaxe/vshaxe/wiki/Configuration

> The vshaxe extension supports the following settings. They can be configured in user or workspace settings file (.vscode/settings.json)

**Comment by chrmarti** [comment]
@miedmondson When you say the CPU spiked, which process was using a lot of CPU? (There is a chance this is #34711, but could be something else.)

**Comment by miedmondson** [comment]
@chrmarti  Putting the settings.json back in ~/.vscode and dragging a file onto VSCode icon in Dock...

https://www.dropbox.com/s/bjpo6v5cqxjhk1e/Screenshot%202018-02-27%2008.21.06.png?dl=0

/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg

**Comment by chrmarti** [comment]
That is very likely caused by an extension, some declare a file pattern on which they need to activate.

**Comment by chrmarti** [comment]
Continuing the discussion in #34711.

**Comment by bpasero** [comment]
@chrmarti just fyi what you said does not seem to be our behaviour, we seem to just check for a `.vscode` folder to decide if we open the folder or not. I pushed https://github.com/Microsoft/vscode/commit/d674f7b7e1922535bf62351b3a368f16fd635a01 due to https://github.com/Microsoft/vscode/issues/44980 where our heuristic to find the home folder on Linux was not working. Now we require a `settings.json` file in the `.vscode` folder to open the folder.

**Comment by chrmarti** [comment]
We should check for `.vscode/settings.json` when in the home folder only. Not sure why we didn't do this on Mac.

**Comment by bpasero** [comment]
@chrmarti the user was on Linux but the home folder path was symlinked so it never matched with the user path you expected it to be...
