### ISSUE TITLE
Nested excludes in .gitignore messes up Find in Files

### ISSUE THREAD

**Issue by ToadKing** [Microsoft/vscode#43592]
- VSCode Version: 1.19.3
- OS Version: Windows 10 Pro x64 [Version 10.0.16299.192]

Steps to Reproduce:

1. Clone this repo: https://github.com/ToadKing/vscode-gitignore
2. Do a Find in Files search for "testing" with `"search.useIgnoreFiles"` set to `true`

Expected results: Four matches found in all four text files.
Actual Results: Only matches in e.txt and g.txt are found.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Is this a problem with the .gitignore patterns, or just the fact that it only looks at .gitignore and not files that are added to git but covered by the .gitignore? If I add a file next to b.txt, it is ignored by git, so I think we are interpreting the patterns correctly.
