### ISSUE TITLE
Error Code 0xc000007b while updating

### ISSUE THREAD

**Issue by tweakimp** [Microsoft/vscode#43590]
## Issue Type
Bug

### Description

In VS Code Insider:
Search for and download update.
Click install update.
Click "restart for update".
**This error shows up:**
![error](https://i.imgur.com/vs9PfDp.png)
After clicking OK, VS Code starts with no errors, but has not installed the update.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (ef42990520a856451ba5ad6fa1d299b0e0c185a2, 2018-02-12T05:14:21.574Z)
OS version: Windows_NT x64 10.0.10240

Version 1.21.0-insider
Commit ef42990520a856451ba5ad6fa1d299b0e0c185a2
Date 2018-02-12T05:14:21.574Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|15.93GB (11.28GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
@tweakimp Please disable background updates with the following setting: `"update.enableWindowsBackgroundUpdates": false`

Please enable it back again mid next week and let me know if you still have the same problem.

**Comment by tweakimp** [comment]
So no updates for me for a week? :'( I'll do it though, for science!

**Comment by joaomoreno** [comment]
@tweakimp Give it a try any time now, let me know how it goes.

**Comment by tweakimp** [comment]
It worked!

**Comment by joaomoreno** [comment]
Sweet! Thanks @tweakimp!

**Comment by dbaeumer** [comment]
Marking as verified. Running with background update for a while without problems.

**Comment by tweakimp** [comment]
Does this mean I can revoke the setting?

**Comment by joaomoreno** [comment]
What do you mean? I thought this worked for you.

**Comment by tweakimp** [comment]
It did work and I can confirm that I was able to revoke the setting and it still works.
