### ISSUE TITLE
TreeItem with undefined CollapsibleState still shows triangle expander

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#43608]
We started noticing this bug on insiders a few days ago. We haven't changed our TreeDataProvider, but now even leaf nodes have the triangle expander thing.

Before:
![screen shot 2018-02-13 at 10 49 35 am](https://user-images.githubusercontent.com/11282622/36167738-bfd14254-10ab-11e8-8ad8-edeec42ffe08.png)

Now:
![screen shot 2018-02-13 at 10 50 23 am](https://user-images.githubusercontent.com/11282622/36167755-ca3941b0-10ab-11e8-93ec-1ec60969c5cb.png)

@sandy081 I'm guessing it might have to do with the change to hasChildren in this commit: https://github.com/Microsoft/vscode/commit/125ac04d1f72d9e42f2bd8f1ac9b2bf61ff1e3cc#diff-094f2529578f3d0493f637a194e2687bR339

VS Code version: Code - Insiders 1.21.0-insider (00f2d8ed7196606d31cc1759a171486d1cc00deb, 2018-02-13T06:08:48.197Z)
OS version: Darwin x64 17.4.0

**Comment by sandy081** [comment]
Yeah, its broken in insiders as I was falsly assuming that the tree item has always collapsible state. 

Default is always `none`.

Fixed it. 

Thanks @EricJizbaMSFT for reporting.
