### ISSUE TITLE
Bash terminal on Windows should linkify paths with both '/' and '\'

### ISSUE THREAD

**Issue by bobbylight** [Microsoft/vscode#43603]
- VSCode Version:  1.19.3
- OS Version:  Windows 7

Steps to Reproduce:

1.  Open a bash terminal in VS Code
2.  Run a process that logs paths with the Windows '\\' path separator

While `paths/like/this` are linkified, `paths\like\this` aren't.  I assume this is because the path separator is tied to the shell, not to the OS default.  It seems like the most user-friendly thing on Windows would be to accept both '/' and '\\' as path separators when linkifying paths in the terminal.

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/38686
