### ISSUE TITLE
f# not shown in status bar

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4360]
* fresh windows 10
* downloaded latest alpha build, installed _ionide f#_ extension
* create a file `testing.fsx`
* file is coloured, F# shows in 'change language' UI, but not in status bar (others like php, js do)

![screen shot 2016-03-17 at 14 08 55](https://cloud.githubusercontent.com/assets/1794099/13846794/042ac8b8-ec4a-11e5-9f86-10f3a6921a69.png)

**Comment by bpasero** [comment]
This is because ionide does not contribute an alias for their language contribution.

**Comment by bpasero** [comment]
@alexandrudima starting with you for the core side

**Comment by Krzysztof-Cieslak** [comment]
If we should add anything just let me know.

**Comment by alexandrudima** [comment]
@Krzysztof-Cieslak you could add at one `alias` when you contribute the language.

e.g.:
```
...
"contributes": {
	"languages": [{
		"id": "fsharp",
		"aliases": [ "F#" ],
		"extensions": [ ".fs", ".fsx", ".fsi" ],
		"configuration": "./fsharp.configuration.json"
...
```

We will also change some logic on our side that if the `alias` key is missing we pick up the `id`.

**Comment by jrieken** [comment]
@bpasero Wondering why we show something in the 'change language' UI then?

**Comment by bpasero** [comment]
@jrieken that is very likely our own F# coloring?

**Comment by alexandrudima** [comment]
@jrieken This is weird, I see the issue in source code (where the latest contribution of a language gets to determine its name), but I cannot reproduce when running out of development.

**Comment by alexandrudima** [comment]
Scratch that, I mixed up the `.vscode-oss-dev` vs `.code-oss-build-dev` folders. I can reproduce.

**Comment by alexandrudima** [comment]
@bpasero No further work needed on your side.

**Comment by bpasero** [comment]
@alexandrudima thanks! love those comments ;)
