### ISSUE TITLE
Perform showOpenedFileInNewWindow by dragging a tab out of the current window - like Sublime or IntelliJ IDEA

### ISSUE THREAD

**Issue by Nowaker** [Microsoft/vscode#43607]
Dragging a tab out of the current window like below should create a new window (like `showOpenedFileInNewWindow`).

![image](https://user-images.githubusercontent.com/611746/36167015-fb8b1f3c-10b9-11e8-8b2e-bbd1ad474ec4.png)

Then, moving a tab from a newly created window back to the original window should automatically close the new window. It currently works in a weird way - the target window opens a file but the source window still has the same tab.

**Comment by ketozhang** [comment]
Duplicate of #10121

We are all waiting for this feature. Please upvote that thread.

**Comment by RoyTinker** [comment]
Actually I think it's a duplicate of https://github.com/Microsoft/vscode/issues/8171 -- that one is a bit more specific.
