### ISSUE TITLE
Git decorations on sidebar Explorer not showing after opening a folder.

### ISSUE THREAD

**Issue by jmvelazquezr** [Microsoft/vscode#43606]
### Issue Type
Bug

### Description

Git decorations on the sidebar Explorer (modifiedResource, untrackedResource, etc) don't show up on the sidebar after opening a versioned folder. The decorations flash for less than a second then disappear. I have to go to the Source Control view and hit refresh for the decorations to reappear on the Explorer.

Steps to reproduce:

1. Open VSCode
2. Open versioned folder
The expected decorations for (untracked, modified, etc.) resources are invisible.
3. Open and refresh Source Control View
4. Return to Explorer view
The decorations appear as expected.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.13.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|Load (avg)|1, 0, 0|
|Memory (System)|15.63GB (9.87GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by jrieken** [comment]
Can you attach the reading from the git log? Check 'view > output > git' for that. Thanks
