### ISSUE TITLE
JavaScript Multiline Comments - Incorrect Caret Placement

### ISSUE THREAD

**Issue by srm985** [Microsoft/vscode#43619]
- VSCode Version: 1.20.0
- OS Version: Windows 10

When attempting to write multi-line comments in a JavaScript file, the caret is placed in the incorrect position after pressing 'Enter'. My expected response would be as follows: I begin by typing the sequence '/' -> '/\*' -> '/\*\*' and after typing that second asterisk, the text expands automatically to '/\*\* \*/'. Then if I were to press enter, the text would break apart into three lines and the caret would be placed on the second line such as:

/\*\*
\* |<-caret here
\*/

From here I could simply type my comment. The issue now seems to be that once the text is expanded, it then shows a drop down selection labeled 'JSDoc comment'. By pressing 'Enter', this causes that option to be selected and instead of breaking apart the text, it exits the text and the caret is placed at the end of the text.

Steps to Reproduce:

1. Type '/' -> '/\*' -> '/\*\*'
2. The text expands to '/\*\* \*/
3. Press 'Enter'
4. Caret is placed incorrectly /\*\* \*/ |<-caret here

Does this issue occur when all extensions are disabled?: [Yes]/No

**Comment by mjbvz** [comment]
Thanks! Yes this is a really annoying bug. Should be fixed in the next VS Code insiders build
