### ISSUE TITLE
Allow placement of caret after end of line - like IntelliJ IDEA

### ISSUE THREAD

**Issue by Nowaker** [microsoft/vscode#43616]
Setting "Allow placement of caret after end of line" in IntelliJ IDEA allows one to move caret to any location by mouse-click or arrow keys.

![image](https://user-images.githubusercontent.com/611746/36171919-f2b21388-10c9-11e8-9ea9-e7e23f9927ef.png)

**Comment by flo2k** [comment]
This feature would be very nice to have.

**Comment by usernamehw** [comment]
Duplicate of #13960
