### ISSUE TITLE
Background updater can't delete Code.exe

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#43612]
From @pbriggeman

> I am having an issue updating Visual Studio Code - Insider's Build,  The log output from the installer is shown below:
> 
> ```
> Feb 12 13:40:40.605 INFO Starting: C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe, true
> Feb 12 13:40:40.668 INFO Checking for running Code - Insiders.exe processes... (attempt 1)
> Feb 12 13:40:40.681 INFO Code - Insiders.exe is running, wait a bit
> Feb 12 13:40:41.182 INFO Checking for running Code - Insiders.exe processes... (attempt 2)
> Feb 12 13:40:41.193 INFO Code - Insiders.exe is running, wait a bit
> Feb 12 13:40:41.694 INFO Checking for running Code - Insiders.exe processes... (attempt 3)
> Feb 12 13:40:41.706 INFO Code - Insiders.exe is running, wait a bit
> Feb 12 13:40:42.206 INFO Checking for running Code - Insiders.exe processes... (attempt 4)
> Feb 12 13:40:42.218 INFO Code - Insiders.exe is running, wait a bit
> Feb 12 13:40:42.719 INFO Checking for running Code - Insiders.exe processes... (attempt 5)
> Feb 12 13:40:42.729 INFO Code - Insiders.exe is running, wait a bit
> Feb 12 13:40:43.230 INFO Checking for running Code - Insiders.exe processes... (attempt 6)
> Feb 12 13:40:43.240 INFO Code - Insiders.exe is running, wait a bit
> Feb 12 13:40:43.741 INFO Checking for running Code - Insiders.exe processes... (attempt 7)
> Feb 12 13:40:43.749 INFO Code - Insiders.exe is running, wait a bit
> Feb 12 13:40:44.250 INFO Checking for running Code - Insiders.exe processes... (attempt 8)
> Feb 12 13:40:44.258 INFO Code - Insiders.exe is not running
> Feb 12 13:40:44.267 INFO Starting update, silent = true
> Feb 12 13:40:44.267 INFO do_update: "C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe", _
> Feb 12 13:40:44.373 INFO header: Header, id: Inno Setup Uninstall Log (b) 64-bit, app id: {1287CAD5-7C8D-410D-88B9-0D1EE4A83FF2}, app name: Visual Studio Code - Insiders, version: 1048, num recs: 102371, end offset: 26529072, flags: 0x35, crc: 0x545ea7d9
> Feb 12 13:40:44.374 INFO num_recs: 102371
> Feb 12 13:40:44.374 INFO move_update: "C:\\Program Files\\Microsoft VS Code Insiders\\unins000.dat", _
> Feb 12 13:40:44.374 INFO Delete: "bin" (attempt 1)
> Feb 12 13:40:44.374 INFO Delete: "Code - Insiders.exe" (attempt 1)
> Feb 12 13:40:44.425 INFO Delete: "Code - Insiders.exe" (attempt 2)
> Feb 12 13:40:44.626 INFO Delete: "Code - Insiders.exe" (attempt 3)
> Feb 12 13:40:45.077 INFO Delete: "Code - Insiders.exe" (attempt 4)
> Feb 12 13:40:45.877 INFO Delete: "Code - Insiders.exe" (attempt 5)
> Feb 12 13:40:47.128 INFO Delete: "Code - Insiders.exe" (attempt 6)
> Feb 12 13:40:48.929 INFO Delete: "Code - Insiders.exe" (attempt 7)
> Feb 12 13:40:51.379 INFO Delete: "Code - Insiders.exe" (attempt 8)
> Feb 12 13:40:54.585 INFO Delete: "Code - Insiders.exe" (attempt 9)
> Feb 12 13:40:58.636 INFO Delete: "Code - Insiders.exe" (attempt 10)
> Feb 12 13:41:03.636 INFO Delete: "Code - Insiders.exe" (attempt 11)
> Feb 12 13:41:03.650 ERRO Access is denied. (os error 5)
> ```
> 
> I suspect that this has quite a bit to do with how this laptop is configured by our IT dept.  I am connected to a local domain with standard user privileges.  In order to install any software on the laptop I am required to enter my local administrator account privileges.  VSCode installs and runs just fine, the issue occurs when VSCode is self-updating.  Once VSCode is loaded, it reports that it has an update and I click "Install Update..." when I click on the gear icon.  VSCode then downloads the update.  When it completes the download, it requests that I restart VSCode and that's when this error is generated.  I've tried running VSCode as the local administrator and follow the same steps above, but the issue still persists, any help that you can provide will be much appreciated!

**Comment by joaomoreno** [comment]
@pbriggeman When you click `Install Update...` within VS Code, you're supposed to see an Administrator popup dialog, prompting you whether to grant permissions to VSCode's setup package. Do you get that popup?

**Comment by pbriggeman** [comment]
@joaomoreno 

1. There is an notification ("1") on the gear icon (rollover indicates "New Code - Insiders update available").  I click on the gear icon and then click on "Install update..." and at this point, I am presented with the administrator login popup.
2. I enter my credentials and then notification turns into a clock and says "Installing update...".  When VSCode is done downloading the update the notification turns back to a "1".  
3. I click on "Restart to update..." and then I'm presented with an "Updating VS Code" progress bar.  Within a minute or so an error window is displayed:

![image](https://user-images.githubusercontent.com/106990/36211461-483aa478-116f-11e8-8ee0-600ff256892a.png)

For what it's worth, I believe that there should be a second admin authorization when doing a restart, it's acting like it's not carrying the authorization through the entire process...

BTW - Awesome product, my default editor!

**Comment by joaomoreno** [comment]
OK, do something else. Next time you see that error coming up, open a process explorer (eg Process Hacker) and look for `Code - Insiders.exe`. What's the full command line of those running processes?

**Comment by pbriggeman** [comment]
@joaomoreno 

C:\Users\PBRIGG~1\AppData\Local\Temp\1\vscode-update-x64\CodeSetup-insider-936b796aa8667de5edb536b00ce8a8e61fcebfb6.exe /verysilent /update="C:\Users\PBRIGG~1\AppData\Local\Temp\1\vscode-update-x64\CodeSetup-insider-936b796aa8667de5edb536b00ce8a8e61fcebfb6.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon

**Comment by joaomoreno** [comment]
@pbriggeman That's the `CodeSetup-insider-936b796aa8667de5edb536b00ce8a8e61fcebfb6.exe` process. I meant the `Code - Insiders.exe` process.

**Comment by pbriggeman** [comment]
Code - Insiders.exe is not active at the point where the installer fails:

![image](https://user-images.githubusercontent.com/106990/36426289-94e21c96-1617-11e8-86c0-b80d551eab41.png)

However, when I first start VS Code, these are the processes that are running:

![image](https://user-images.githubusercontent.com/106990/36426421-e445aee2-1617-11e8-8f83-bed60d7087c3.png)

The topmost Code - Insiders.exe has no start-up params, the fist indented process is:
`"C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,10,19,23,41,61,74 --disable-gl-extensions="GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent" --gpu-vendor-id=0x8086 --gpu-device-id=0x0416 --gpu-driver-vendor="Intel Corporation" --gpu-driver-version=20.19.15.4531 --gpu-driver-date=9-29-2016 --gpu-secondary-vendor-ids=0x10de --gpu-secondary-device-ids=0x11fc --service-request-channel-token=9B39D1C0D53B63655EBAE4A149823716 --mojo-platform-channel-handle=1492 /prefetch:2`

The second indented process:
`"C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=6F5E19767E50100993954C218EC9517D --lang=en-US --app-user-model-id=Microsoft.VisualStudioCodeInsiders --app-path="C:\Program Files\Microsoft VS Code Insiders\resources\app" --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --disable-blink-features=Auxclick --enable-pinch --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --service-request-channel-token=6F5E19767E50100993954C218EC9517D --renderer-client-id=4 --mojo-platform-channel-handle=2144 /prefetch:1`

Second level indented:
`"C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" --reporter-url=https://rink.hockeyapp.net/api/2/apps/0ac07349c6e34e978fdfb42074932f22/crashes/upload --application-name=VSCode "--crashes-directory=C:\Users\PBRIGG~1\AppData\Local\Temp\1\VSCode Crashes" --v=1`

Next second level indented Code - Insiders:
`"C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Program Files\Microsoft VS Code Insiders\resources\app\out\bootstrap" --type=extensionHost`

First third level indented:
`"C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" C:\Users\pbriggeman\.vscode-insiders\extensions\dbaeumer.vscode-eslint-1.4.6\client\node_modules\vscode-languageclient\lib\utils\electronForkStart C:\Users\pbriggeman\.vscode-insiders\extensions\dbaeumer.vscode-eslint-1.4.6\server\out\eslintServer.js --node-ipc --clientProcessId=2996`

Second third level indented:
`"C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\typescript\out\utils\electronForkStart.js" "c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\PBRIGG~1\AppData\Local\Temp\1\vscode-tscancellation-db8de10974316d65554a.sock* --locale en`

Fourth level indented
`"C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/pbriggeman/AppData/Local/Microsoft/TypeScript/2.7 --enableTelemetry --typesMapLocation "c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js/../typesMap.json"`

Final fist level indented
`"C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=175AE7A6570E41D0315BEFC77960FF11 --lang=en-US --app-user-model-id=Microsoft.VisualStudioCodeInsiders --app-path="C:\Program Files\Microsoft VS Code Insiders\resources\app" --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --service-request-channel-token=175AE7A6570E41D0315BEFC77960FF11 --renderer-client-id=6 --mojo-platform-channel-handle=2352 /prefetch:1`

If you have any questions, please let me know.,

**Comment by joaomoreno** [comment]
@pbriggeman Can you verify that the update always fails with the following error?

```
INFO Delete: "Code - Insiders.exe" (attempt 11)
ERRO Access is denied. (os error 5)
```

**Comment by pbriggeman** [comment]
I can definitely confirm that this happens every single time, that logfile is permanently burned into my cerebral cortex.  :)

**Comment by joaomoreno** [comment]
So... `inno_updater.exe` is elevated (orange color) and `Code - Insiders.exe` isn't running, yet still can't be deleted. Hm.

Let's do something else: When you hit that point, in which the error dialog comes up, try to manually delete or move `Code - Insiders.exe` using the Windows Explorer. Do you get an error?

**Comment by pbriggeman** [comment]
OK, so the issue comes down to RORKA, our internal security policy requires a 20 character password and our admin login window does not store the admin username.  All this amounts to an inordinate amount of time for me to type in credentials just as the main Code Insiders window (which releases the Code Insiders.exe) closes and I just can't type fast enough to delete/rename the file before the error happens.  In the meantime, I've just been performing a full install weekly to overwrite whatever exists in my "Program Files/Code Insiders" directory.  So far no issues...

**Comment by joaomoreno** [comment]
@pbriggeman That's too bad! But the auth dialog does show up, right? We can increase the timeout to give you enough time to input the pwd. Can you share a screen recording of the experience?

Instead of full installs, you can disable background updates with the `update.enableWindowsBackgroundUpdates` setting.

**Comment by pbriggeman** [comment]
@joaomoreno My apologies, the auth dialog box that pops up is for the file delete that I'm trying to do on ~\Code Insiders.exe before the error occurs.  I tried deleting it while the error window was open, but the file is still held by the process and deleting after the error popup just keeps Code Insiders from starting.

**Comment by pbriggeman** [comment]
@joaomoreno OK, here's the video of the entire process...

WARNING! This video product may cause drowsiness, do not operate heavy equipment while watching this video.

Dropbox File:  https://www.dropbox.com/s/g2xz6ov6z8wjgkt/2018-02-26-13-44-00.flv?dl=0

Please let me know if you have any issues viewing this file.

**Comment by joaomoreno** [comment]
Thanks for the video!

Let's make sure `inno_updater.exe` runs elevated. Using Process Hacker, add the `Elevation` column and check whether `inno_updater.exe` has `Full` elevation. Here's what it looks like in my machine:

<img width="1626" alt="screen shot 2018-02-27 at 09 47 35" src="https://user-images.githubusercontent.com/22350/36718827-6aea3f22-1ba3-11e8-82f0-a66e9a627233.png">

**Comment by pbriggeman** [comment]
Not sure if you folks changed the upgrade process, but whatever you did on last night's build, you've fixed my problem!!  I can't thank you enough!

**Comment by joaomoreno** [comment]
That's odd. Are you sure? 

Can you simulate another update with: shutdown Code, edit the `C:\Program Files\Microsoft VS Code Insiders\resources\app\product.json` as an Administrator and change the `commit` field to `latest`. Start Code, you will get an update to the same version.

**Comment by pbriggeman** [comment]
@joaomoreno -- Edited the "product.json" file as you requested and recorded the exact same process as earlier, still updates perfectly with no issues!

Video:  https://www.dropbox.com/s/sesm94n23rff77p/2018-02-28-09-13-48.zip?dl=0

**Comment by joaomoreno** [comment]
Did nothing else change in your system meanwhile?

**Comment by pbriggeman** [comment]
There were no other changes, system files or updates, I walked in this morning, booted up my laptop and the first thing I did is run Code Insiders to get the latest update (changing the update.enableWindowsBackgroundUpdates setting had no effect on the update process).

And while I have your ear, would there be any chance that there could be a "sync extensions", I probably have at least 20 installs of Code Insiders across all of my laptops and servers.   I sure would like a way to have any installed extension on one install get automagically installed to the other installs on next application start?  (Just asking...)

**Comment by joaomoreno** [comment]
I think these guys did it: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

OK good to know this is now working for you, I'll close it and keep it in mind if it comes up again.

**Comment by joaomoreno** [comment]
@pbriggeman I just watched your video, which shows the old update mechanism... That has always worked!

I'm interested in getting it to work with `update.enableWindowsBackgroundUpdates=true`. Can you enable that again and see whether it succeeds?

**Comment by pbriggeman** [comment]
@joaomoreno - Welp, not sure what happened here, but when I enabled the background update mechanism, the update is now working properly without any issues.  I guess we can close this issue now.  Thank you so much for your help!!

**Comment by RMacfarlane** [comment]
Verified by user
