### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by okprogrammer** [Microsoft/vscode#43614]
When i add any extension . After  two hours when i see it is still adding. After 4-5 hours,I got furstate and cancel the extension. This is very bad in vs code

**Comment by egamma** [comment]
I cannot reproduce this, please provide more information: 

- What are the extensions that show this behaviour?
- What do you mean by `i see it still adding`, can you add a screenshot that shows this state.

**Comment by okprogrammer** [comment]
It is always showing like this. But no extension add after 4-5 hours then i close the vs code

**Comment by okprogrammer** [comment]
When i click the install button it never get installed. It always showing
in process.
This is the picture of previous which was after 10 hours.

**Comment by sandy081** [comment]
@okprogrammer May I know if you are behind any proxy settings? 

Can you please set the log level to `trace` using `Set Log Level` command and Open the Shared process log using command `Show Logs...` and try to reproduce the issue and provide us the logs.

**Comment by polomora** [comment]
Can I reopen this issue?
I have just installed vscode on centos v7, and I cannot install any extensions (C/C++ v0.15.0 and Python 2018.1)

**Comment by sandy081** [comment]
@polomora Please open a new issue with proper steps to reproduce and if you see any errors in the logs
