### ISSUE TITLE
[VSCode Alpha] Freeze on startup

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#4361]
- VSCode Version:0.10.12-alpha 32bd7fd3
- OS Version:Win7

The latest version of VSCode alpha freezes during startup when running the extension Gerrit. The reason that I am reporting this here is that the same version of Gerrit (v0.2.1) runs correctly on v0.10.11

I am only able to get the freeze to occur on a specific Git repository, and if I step through the code in debug mode it doesn't freeze. I believe it has something to do with handling of rejected promises.

I will continue to debug the extension, I just posted this here incase a regression had occurred in the way you launch extensions or handle errors within them,.

**Comment by tht13** [comment]
Somehow the issue was resolved by deleting everything in appdata/roamin/vscode - alpha/ except for the User folder. Possibly something to look into there? 
But will close now :smile:

**Comment by aeschli** [comment]
This issue was moved to tht13/gerrit-vscode#1
