### ISSUE TITLE
C# Syntax Highlight: code prefixed with //// and more is not hightlighted as comment

### ISSUE THREAD

**Issue by yuryleb** [Microsoft/vscode#43620]
### Issue Type
Bug

### Description

Code prefixes `//` and `///` are treated as comments but `////` and more - already not:

![vscode-cs-syntax-hl](https://user-images.githubusercontent.com/4529411/36175595-ee396d4a-1107-11e8-87c8-01210245e99d.png)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2310 CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|5.98GB (3.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
csharp|ms-|1.13.1

</details>
Reproduces without extensions

**Comment by bluuman** [comment]
// is syntax for a comment.
/// is syntax for a summary.
maybe this is by design.

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#100
