### ISSUE TITLE
Double color boxes appear inside style blocks in html files in 1.21

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#43628]
- VSCode Version: 1.21 Insiders
- OS Version: Windows and Mac, didnt try Linux

Steps to Reproduce:

1. Have the below content in an html file
```

<style>
    .foo {

    }
</style>
```
2. Inside the `.foo` rule type `c`
3. First suggestion would be `color: #000` from emmet, select it

**Expected**: `color: #000` with 1 color box
**Actual**: `color: #000` with 2 color box

![image](https://user-images.githubusercontent.com/16890566/36183948-d23db1a4-10e5-11e8-8dfa-2786509380ad.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@aeschli I found both HTML extension and LSP registered the document color provider, so we need to delete them from HTML extension. Not sure if CSS will run into the same issue.

**Comment by aeschli** [comment]
Thanks @ramya-rao-a @rebornix, I forgot to remove the client registration.
