### ISSUE TITLE
C# syntax highlight: star (multiplication) in function-call mistakenly highlighted

### ISSUE THREAD

**Issue by CCludts** [Microsoft/vscode#43621]
- VSCode Version: 1.20.0
- OS Version: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592). Windows10 Pro 64x

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/18717967/36176920-73c4ad88-1114-11e8-9fc3-475cfb4dc975.png)

1. Any file with c# language-mode  (new Untitled file works, saving is irrelevant)
2. `Multiply(n1 * n2);`

Does this issue occur when all extensions are disabled?: __Yes__

edit: this issue already existed on the previous release of VSCode

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#99
