### ISSUE TITLE
VSCode can find "Operator Mono" but not "Operator Mono Book" font

### ISSUE THREAD

**Issue by iamed2** [microsoft/vscode#43626]
### Issue Type
Bug

### Description

1. Install Operator Mono
2. Set user setting `"editor.fontFamily": "Operator Mono"` and you should see the font successfully switch
3. Set user setting `"editor.fontFamily": "OperatorMono-Book"` and you should see the font successfully switch (it's a barely perceptible change, it'll look the same)
4. Set user setting `"editor.fontFamily": "Operator Mono Book"` and you should see the fallback font instead of the above

I verified "Operator Mono Book" works in Sublime Text 3 and as CSS in Firefox. 

I am on macOS High Sierra.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|/private/var/folders/z0/r1h4kvk15xdb38hfjd8vq53r0000gn/T/AppTranslocation/E0F458DE-66BC-41ED-991A-774F110DF9D2/d/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_23234087|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
fish|Ted|0.0.4
markdown-julia|col|0.0.1
language-julia|jul|0.9.1

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment]
@iamed2 Our font loading logic is 100% the same as the one in Chrome v58, as Chrome is doing the font loading behind the scenes. I wonder, if you can reproduce this issue in Chrome too, could you please create an issue on their tracker at https://bugs.chromium.org/p/chromium/issues/list and link to it here.

**Comment by iamed2** [comment]
Same thing happens in Chrome as in VSCode. Looking at the tracker, it appears that it might be this: https://bugs.chromium.org/p/chromium/issues/detail?id=641861&q=font-family&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

Regardless, I think I now have the experience I want, somewhat by chance. 

Sublime Text 3 chooses "Medium" as the default weight. There, I need to specify `Operator Mono Book` as the font in order to get that weight. Sublime then chooses the appropriate font face "Operator Mono Book Italic" for italics. If I choose `Operator Mono Medium`, it uses "Operator Mono Medium Italic" as the italic font face. 

VSCode and Chrome both choose "Book" as the default weight, which happens to work for me. However, there appears to be no way to get the same behaviour as Sublime. If I choose `OperatorMono-Medium` in font-family, the italic form will still be "Operator Mono Book Italic".

**Comment by Neo42** [comment]
![avatar](https://user-images.githubusercontent.com/22409868/38171604-28be690c-35cf-11e8-98b9-4f9b27daead3.png)
Mine works just fine.

**Comment by cideM** [comment]
And you're on MacOS @Neo42? Because the problem only occurs on MacOS and not on e.g., Linux. I tried all incantations and for me it also does not work. It finds Operator Mono SSm but not Operator Mono SSm Book.

**Comment by HaiUIT** [comment]
@asadferozali So this seem like a OS issue rather than VSCode issue, isn't it?

**Comment by xgz123** [comment]
The solution is `"editor.fontFamily": "'OperatorMono-Book'"`

**Comment by iamed2** [comment]
No, that doesn't solve the issue completely.

> If I choose OperatorMono-Medium in font-family, the italic form will still be "Operator Mono Book Italic"

**Comment by iamed2** [comment]
@apineda-ghostery Nope, I don't believe there is a possible workaround (other than duplicating the font face as a new font family). I was trying vscode for 3 weeks as a personal trial and I have since gone back to Sublime.

**Comment by AmirFawzy** [comment]
for windows OS that's right it seems a bug or something i had the same exact problem and i try @asadferozali solve and it working fine with me

**Comment by TheMartes** [comment]
I've had this problem for a quite a long time, but today i've found out, that you need to have a compatible theme, to use Operator Mono Book.

**For example.**
I was using rainglow themes, which appears like a solid theme basement for your VSCode but the thing is that it's not work with Operator Mono
![image](https://user-images.githubusercontent.com/16374732/43678343-13e1d8c0-9812-11e8-81a2-87331adf19c1.png)

However, if you choose **Material Theme** or **Egoist One** which is my personal preference, you can use the Operator Mono Book font ligatures. Which works pretty fine.
![image](https://user-images.githubusercontent.com/16374732/43678385-bbcab9da-9812-11e8-8add-384ea28f3712.png)

What's even more weird, is that every theme seems to use different ligatures for each type of code. In picture above you can see, that the comment has nice italic style, but in another theme it's applied to key of that JSON. (This one is called **Monokai**)
![image](https://user-images.githubusercontent.com/16374732/43678434-94eec8a0-9813-11e8-9876-e044b81f77cc.png)

Also, you need to use this setting, to get this font working on your machine. 
`"editor.fontFamily": "'OperatorMono-Book'",`

Hope this helps for someone. 😇

**Comment by iamed2** [comment]
Those themes just have different rules for which parts of code are italicized. That is not related to this issue.

**Comment by madig** [comment]
If you feel like getting your hands dirty, use fonttool's `ttx` utility to decompile the font files into XML. What you're looking for is the `<name>` table. The table is, along with the OpenType font format itself, a bit hairy due to 30 years or so of baggage, programs misinterpreting things and piled-on hacks to work around issues. The nameIDs are explained at https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids. You need 1 and 2 and possibly 16 and 17. Font styles that are not regular, italic, bold or bold italic, commonly get fields 1 and 2 set as if those styles were their own family, the real family and style name get written to 16 and 17 instead then.

So, if all you need is a regular, italic, bold and bold italic, you could make copies of the font files and modify their id 1 (family name) to e.g. "OperatorMonoCode", set 2 to what it should represent and delete 16 and 17. OS/2.fsSelection might need looking at (refer to the spec). Re-compile with `ttx` again. This is probably against the license, but see it as self-defense.

**Comment by olipiskandar** [comment]
try : "editor.fontFamily": "Operator Mono",

**Comment by dreki** [comment]
In macOS, this works for me:
`"editor.fontFamily": "OperatorMono-Book, Monego, iA Writer Duospace, Fira Code iScript, Menlo, Monaco, 'Courier New', monospace",`

(Entirety of config line pasted here to avoid making a mistake while simplifying it.)

**Comment by cideM** [comment]
Can confirm that that works! @dreki 

Note the full path to the font file
<img width="1680" alt="Screen Shot 2019-04-03 at 12 18 06" src="https://user-images.githubusercontent.com/4246921/55471704-a33f3100-560a-11e9-872e-cbda9ce5a58c.png">

Medium and book versions
<img width="1680" alt="Screen Shot 2019-04-03 at 12 18 29" src="https://user-images.githubusercontent.com/4246921/55471705-a33f3100-560a-11e9-9590-1280252adbb1.png">
<img width="1680" alt="Screen Shot 2019-04-03 at 12 18 34" src="https://user-images.githubusercontent.com/4246921/55471706-a33f3100-560a-11e9-8948-76dbd3a00e61.png">

**Comment by iamed2** [comment]
@dreki @cideM Can you get the italics to also appear properly?

**Comment by cideM** [comment]
Yes @iamed2 

<img width="1680" alt="Screen Shot 2019-04-06 at 19 37 23" src="https://user-images.githubusercontent.com/4246921/55673098-6b9ee600-58a3-11e9-9012-c5115d2eb58f.png">

**Comment by cideM** [comment]
@iamed2 Actually I'm now noticing that italics are still in the old font style :(

**Comment by UrbanSwati** [comment]
Try `"editor.fontFamily": "Operator Mono Lig"`

**Comment by noslenac** [comment]
I have a question open regarding this same issue. I know it is an older issue, but it is still a problem. It works in Atom which is also based on Electron / Chromium.

https://superuser.com/questions/1483997/operator-mono-book-font-will-not-display-in-visual-studio-code

**Comment by emilorol** [comment]
I was having the same issue and the solution for me was to use the **_`file name`_** of the font name. 

***Note:*** I am using a Mac with MacOS Mojave:

1. Opened the `Font Book`

![font-book-open](https://user-images.githubusercontent.com/9518604/66969330-1f550f80-f057-11e9-95e4-76d0f1447a27.png)

2. Look up the font I want to use. In my case _"Operator Mono Extra Light"_

3. Right click and I pick `Show in Finder`

![font-book](https://user-images.githubusercontent.com/9518604/66969174-8b834380-f056-11e9-8741-f5dc8261b3e3.png)

4. The font file will be highlighted. In my case _"OperatorMono-XLight.otf"_

![font-file](https://user-images.githubusercontent.com/9518604/66969190-9dfd7d00-f056-11e9-8181-32f711055bc1.png)

5. Copy the file name without the extension to `VS Code`. In my case _"OperatorMono-XLight"_

![font-setting](https://user-images.githubusercontent.com/9518604/66969220-b8cff180-f056-11e9-8b51-09b31fd821dc.png)

6. Done.

![font-working](https://user-images.githubusercontent.com/9518604/66969229-be2d3c00-f056-11e9-828f-c7d1359bbaa6.png)

**Comment by michaelgold** [comment]
> To my surprise it showed up in Windows `font` folder as `Operator Mono Light`! 

That is the key insight here. Fonts are named differently in the Windows fonts folder -- and you need to specify the name as it is listed in the Windows fonts folder in order for VS Code to detect the font.

For example, LMMono is named "Latin Modern Mono" in the Windows Control Panel. However, it is named "Latin Modern Mono 10" in the Windows Font Folder. 

"Latin Modern Mono 10" will work in VS Code, while "Latin Modern Mono" will not.

**Comment by cideM** [comment]
@emilorol do italics work for you? Because I tried the same thing and they didn't

**Comment by emilorol** [comment]
@cideM I just test it and it worked for me. In my case I used **_"OperatorMono-XLightItalic"_** as the font Family.

![OperatorMono-XLightItalic](https://user-images.githubusercontent.com/9518604/67729703-86b07f00-f9c8-11e9-9eb9-492a49ed4376.png)

**Comment by cideM** [comment]
No I mean do they work when you use a normal non-italic font. As in, use the font from your previous post and choose a colorscheme that includes italics and then see if the italics used are from the font family you specified. If I choose `OperatorMono-Book` the italics are still from the default Operator Mono on MacOS @emilorol

**Comment by emilorol** [comment]
@cideM can you think of a color scheme I can use to test it?

**Comment by emilorol** [comment]
Here are my results:

![Screen Shot 2019-10-29 at 8 26 05 PM](https://user-images.githubusercontent.com/9518604/67819174-65b06280-fa8a-11e9-921e-eaa99d774746.png)

![Screen Shot 2019-10-29 at 8 25 31 PM](https://user-images.githubusercontent.com/9518604/67819177-6a751680-fa8a-11e9-8fe0-6c3bb156dd20.png)


You tell me.

**Comment by cideM** [comment]
No so you need to set a non italic font in `editor.fontFamily` then open a file where some text is italic and some text isn't. Then check if both the italics and non italics belong to the same font group. Meaning if you choose XLight (not XLight italic) as ,`fontFamily`, will visual studio code correctly use the XLight-Italic for the italic text or will it use the medium/regular italic

**Comment by emilorol** [comment]
@cideM well it seems like it does not, but I can't be sure for certain. I noticed that in some themes the `comments` are italicized, but not all themes will display them as so. Seems to me this might be a situation of all or nothing kind of thing.

**Comment by gamagomaev** [comment]
Hi!
If you use Ubuntu. 
1. Install fonts (open after file and click install)
2. Restart your PC.
3. For VSCode -> file -> preferences -> settings -> open JSON file, added this string 
'"editor.fontFamily": "Operator Mono Medium",' or    
 "editor.fontFamily": "Operator Mono Book".
Good Lack!

**Comment by jdeyrson** [comment]
Solution (Windows 10)

1. Install (only) Operator Mono Book
2. "editor.fontFamily": "Operator Mono" 
3. Font Weight: normal = ("editor.fontWeight": "400")

<img width="733" alt="Code_H5eCEFJYEs" src="https://user-images.githubusercontent.com/59494903/92135996-1be28800-edd1-11ea-84bb-f8a9251072b8.png">

I also notice that:

1. Install Operator Mono Light
2. "editor.fontFamily": "Operator Mono Light" 
3. Font Weight: normal = ("editor.fontWeight": "300")

**Comment by JackZeled0n** [comment]
Hello friends, this help me.  I work in Win10.

1. Install Operator Mono Font
2. Install Palenight Theme and when you set the color theme choose Palenight Italic
3. Add the setup in settings.json in VSCODE

![imagen](https://user-images.githubusercontent.com/10006692/96756894-f108bf00-1391-11eb-8cde-f2df974aa67f.png)

And you will have this


![imagen](https://user-images.githubusercontent.com/10006692/96757114-3cbb6880-1392-11eb-9a4b-de34df19c6d9.png)

**Comment by farshidinanloo** [comment]
I had the same problem but when I set font family to **operator mono light** it works and after that other type of this font family work too.

**Comment by Anderson9095** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/52376745/100916423-179b3900-34ac-11eb-8463-88ef9e9638c5.png)

**Comment by brunormferreira** [comment]
Hi!

1. Just install the font that you want.
2. Set `"editor.fontLigatures": true` and `"editor.fontLigatures": true` in `settings.json` on VS Code.
3. Restart your VS Code.
4. Be happy!

**Comment by Hussseinkizz** [comment]
This seems closed but it's still haunting us down in 2021 May, and personally, I have found after long hours of searching is to get the font you want to use and look for it in your windows font folder, and there preview the font and in the panel see the font name, then use that name in Vscode font-family setting, for example, "Fira Code Retina" or Operator Mono" but for variants like operator mono book won't work by that name but instead call the font name straight because vscode automatically chooses operator mono book as operator mono default variant. For some tweaked fonts just go with the name shown in the windows settings >  font settings > fonts. This has worked when I tested with various fonts like source code pro, operator mono and others!

**Comment by shaon07** [comment]
> work in vscode win. "editor.fontFamily": "Operator Mono",

mine too

**Comment by datng14** [comment]
Hi, I also faced the same issue when I installed this font. But when I preview this font in font book (macos) I noticed that some types are different. As you can see below, 


OperatorMono-BookItalic
![Screenshot 2022-11-19 at 12 26 19](https://user-images.githubusercontent.com/10556264/202835883-6c984c19-0fde-433d-9d17-d22181750a9c.png)

OperatorMono-Bold
![Screenshot 2022-11-19 at 12 26 36](https://user-images.githubusercontent.com/10556264/202835897-a482e3ae-c814-4c1a-9ba2-610793fc74b6.png)

So I copy the font name and it worked :) 

![Screenshot 2022-11-19 at 12 27 46](https://user-images.githubusercontent.com/10556264/202835944-d5090c4c-fd5e-4104-a72d-5fe9354bb81e.png)
![Screenshot 2022-11-19 at 12 28 08](https://user-images.githubusercontent.com/10556264/202835959-dd8ba056-e0ed-4962-aeea-97ebfc69db01.png)

link font: https://github.com/keyding/Operator-Mono/tree/master/Fonts

**Comment by HabibullohUz** [comment]
<img width="866" alt="Xnip2023-11-06_00-19-31" src="https://github.com/microsoft/vscode/assets/92447259/efe2b3e0-36f2-4dd4-9c1c-901caf101218">


i set the operator mono to vscode and i got the texts changed but the arithmetic symbols didn't!?

`
![Untitled](https://github.com/microsoft/vscode/assets/92447259/37c3f2a5-bd36-4f3d-8617-c3d6b5b6a2c9)
`

below is my dissimilar text. what is the solution to this?

**Comment by parse-code** [comment]
> The solution is `"editor.fontFamily": "'OperatorMono-Book'"`

you are the hero
