### ISSUE TITLE
Get rid of inline git revert confirmation alert - "Are you sure you want to revert the selected changes in $FILE?"

### ISSUE THREAD

**Issue by Nowaker** [Microsoft/vscode#43625]
- VSCode Version: 1.20.0
- OS Version: Arch Linux, OSX High Sierra

**Reasoning: with Undo feature available under CTRL+Z, there's no need for an intrusive alert window like this.**

1. Open a file tracked in git.
2. Make a change.
3. Click on the blue thingie to open inline git diff view. ![image](https://user-images.githubusercontent.com/611746/36179794-6b9b138a-10e3-11e8-83ea-2efeb229e6f2.png)
4. Click "Revert Change". ![image](https://user-images.githubusercontent.com/611746/36179780-5953c7a8-10e3-11e8-8dee-7da1642c98c5.png)
5. Expected: revert a change right away.
6. Actual: alert "Are you sure you want to revert the selected changes in $FILE?" is displayed.

![image](https://user-images.githubusercontent.com/611746/36179869-c48df052-10e3-11e8-8eb7-de2758e454c5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@Nowaker That's actually true. Cool stuff. Would you like to submit a PR?

**Comment by shobhitchittora** [comment]
Anyone looking for a code pointer to remove the blocking check - 

https://github.com/Microsoft/vscode/blob/00262fb3900881a65fe30b2771ba8e58cf4a9b09/extensions/git/src/commands.ts#L761

**Comment by Nowaker** [comment]
With a code pointer, I can sure make it! Will do.

**Comment by fonsecapontes** [comment]
This behavior happens too if you right click in the file, in the Source Control tab, and click in "Discard Changes".

In this case, do we remove only from the first situation?

![image](https://user-images.githubusercontent.com/12723525/36388570-0f2f4372-157b-11e8-9551-2e4617d47e35.png)
