### ISSUE TITLE
Intellisense (C++ Go To Definition, formatter, switch source/header file) stops working

### ISSUE THREAD

**Issue by mark-yacoub** [Microsoft/vscode#43627]
### Issue Type
Bug

### Description

After a lot of code copy-pasting around, checking out git branches that are different, or jumpa  lot through the code, VSCode suddenly stop working, so I can't go to definition, formatter doesn't work, can't Alt+O to header file.
It's fixed by restarting vscode though, which was embarrasing when I was showing off vscode to a co-worker.
It's been happening for a while, since i started using it last year, but it became more frequent recently.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.4.0-109-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 1696)|
|Load (avg)|0, 0, 0|
|Memory (System)|62.81GB (0.65GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.8
code-gnu-global|aus|0.2.2
python|ms-|2018.1.0
cpptools|ms-|0.14.6
debug|web|0.21.2

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
Sorry for the late answer. For whatever reason this only shows up today in our inbox queries. 

This is an issue with the C++ extension. Pls file the issue against https://github.com/Microsoft/vscode-cpptools/issues. Thanks a ton!
