### ISSUE TITLE
Multi line editing in typescript file

### ISSUE THREAD

**Issue by tony09uk** [Microsoft/vscode#43622]
### Issue Type
Bug

### Description

1 - create angular 5 component
2 - add provided sample text
3 - set the cursor next to the comma after mediaType
4 - hold ctrl & tab and down arrow until all pproperties have a cursor on them

expected behaviour:
cursor appears at the end of each line for multi line editing to take place

actual behaviour
cursor appear at the end of each line for multi line editing to take place except for mediaUpdateDate line, where it appears after the letter t 
(mediaUpdat --cursor appears here>|<cursor appears here-- e)

sample:
  initMedia(): FormGroup {
    return this.fb.group({
      mediaType: '',
      mediaUrl: '',
      caption: '',
      sortOrder: '',
      mediaUpdateDate: ''
    })
  }

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|Memory (System)|7.88GB (3.56GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by egamma** [comment]
This is the expected behavior, the editor tries to preserve the column position of the cursor.
