### ISSUE TITLE
Type inference for recursive function (fibonacci) fails.

### ISSUE THREAD

**Issue by Artikash** [Microsoft/vscode#43637]
### Issue Type
Bug

### Description

type this function into any javascript file

```const fib = n => n < 2 ? 1 : fib(n - 1) + fib(n - 2);```

There's no way that this could return anything but a ```number```, but VS Code cannot infer this, instead giving ```const fib: any => any```

Not sure if possible to fix (seems like the sort of thing CS theory might have proved impossible), but please look into it.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3220 @ 3.00GHz (2 x 2999)|
|Memory (System)|3.94GB (0.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-eslint|dba|1.4.5
gitlens|eam|8.0.0
react-native-react-redux|EQu|1.4.1
prettier-vscode|esb|1.1.3
vscode-firefox-debug|hbe|1.1.0
cpptools|ms-|0.14.6
node-debug2|ms-|1.19.0
java|red|0.18.1
vscode-hexdump|sle|1.6.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.2.0
vscode-react-native|vsm|0.5.7
iis-express|war|1.0.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21952
