### ISSUE TITLE
permission request

### ISSUE THREAD

**Issue by raja-rizki** [Microsoft/vscode#43631]
hello sir
I want to ask permission to be a member of your team, I speak in Indonesian, maybe I can help with this, I also handle some other projects, hopefully received

Greetings
thank you

**Comment by egamma** [comment]
@raja-rizki thank you for your interest. We have a separate project for translations by the community. Please see this documentation: https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project
