### ISSUE TITLE
[GIT Version Control] How to configure what commands VSC sends in GIT Control?

### ISSUE THREAD

**Issue by createdbyjurand** [Microsoft/vscode#43638]
- VSCode Version: 1.20.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. "CTRL+SHIFT+G"
2. "..."
3. "Pull"

What VSC does:
git pull
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...j/master
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
git remote --verbose

What I want VSC to do:
git pull

Question/Future feature request:
How can I control what VSC do when I press "git pull"?

**Comment by joaomoreno** [comment]
When you press `Pull`, only `git pull` happens.

The other commands happen in order to fetch the current git status and present it in the UI.
