### ISSUE TITLE
nativescript debug issue

### ISSUE THREAD

**Issue by jemin136** [Microsoft/vscode#43635]
### Issue Type
Bug

### Description

after update new version of vs code getting issue while debug nativescript ts file debuge.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|3.89GB (0.40GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.5
npm-intellisense|chr|1.3.0
vscode-great-icons|emm|2.1.24
file-icons|fil|1.0.7
easy-icons|jam|0.3.1
vsclassic-icon-theme|jez|1.1.0
debugger-for-chrome|msj|4.1.0
autoimport|ste|1.5.3
ayu|tea|0.12.0
nativescript|Tel|0.7.2

(8 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by isidorn** [comment]
Can you reproduce this issue with latest vscode stable and with no extensions?
