### ISSUE TITLE
Generic "Open with" context menu option

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [Microsoft/vscode#43641]
- VSCode Version: 1.19.3
- OS Version: Windows 10 1709

![image](https://user-images.githubusercontent.com/6378638/36194404-cc442b82-1169-11e8-9f3b-84f6c7d9775b.png)

We have received requests from some of the developers using our extension that they would like this productivity feature. I tried finding a way to do this via our extension but I don't think the context menu is extensible.
What we would like is to be able to initiate opening a selected file from the context menu, possibly just using the default app for the file.

Our scenarios are where developers are using the AL extension alongside with Word or SQL Server Report Builder so they would like to be able to open the file without having to have explorer opened in that folder as well. This sounds like a generally useful feature and I can imagine other scenarios as well. Of course, it's not a big priority since it's a productivity feature.

**Comment by isidorn** [comment]
@DominikDitoIvosevic hi. The context menu is the explorer is extensible - extensions can add commands to it. Here are docs covering that https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands

So your extension needs to contribute a command and contribute it in the explorer menu using the id `explorer/context`.

Here's an [example](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/package.json#L155) how our built in markdown extension contributes a command in the explroer context for markdown files.

Similarly you would contribute a command for your `.ai` files

**Comment by DominikDitoIvosevic** [comment]
Hi @isidorn . I see what you mean but the issue is that we want to be able to open Word and RDL files as we would from explorer. I do not want to be able to open .AL files, these are edited from vscode. 
The problem with using the contribute is that then our extension would have to say we are processing .rdl and .docx files which we do not want. We do not want to track them in our workspace and have language server events happen. We just want a generic context menu command to open a file as if we double cliked on it.

This is also a request for a more general feature than just for when working with the AL extension. I think it makes sense to always have this option in vscode for any file. I understand that "Open" might not be a good description for what happens since in vscode you "open" all the files as text files in vscode. Maybe "Open with" but without the prompt but instead open with the default app. Maybe "Open externally"?

**Comment by isidorn** [comment]
@DominikDitoIvosevic I understand, then let's reopen this as a feature request. But honestly I do not see it happening the vscode core product.

**Comment by fabiospampinato** [comment]
@DominikDitoIvosevic @isidorn Am I missing something or this can be done already? Just get the absolute path and pipe it to [open](https://www.npmjs.com/package/open). I think an extension can provide this functionality.

**Comment by DominikDitoIvosevic** [comment]
@fabiospampinato @isidorn , it's true, we have found a way to provide this feature through our extension.
While I would like for you to consider having this as a generic feature, you can close this request as we have solved this locally.

**Comment by fabiospampinato** [comment]
Shameless plug: I've recently published an [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-application) that allows you to open an arbitrary file/folder in an arbitrary app.
