### ISSUE TITLE
Keep scroll position stable when closing a tab in the tab well

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#43642]
**I would reopen #13001, but i can't.**

Steps to Reproduce:

- open many files so that tabs are scrollable, have the first (left-most) tab active
- scroll to the farthest (right-most) tabs
- close a tab in that area
- the whole tab bar scrolls back to the left-most position (active tab)

This leads to loss of focus and confusion. If I want to close multiple tabs there, I have to scroll to them each time I close one.

**Comment by bpasero** [comment]
This was a regression that I fixed via https://github.com/Microsoft/vscode/issues/45527
