### ISSUE TITLE
SnippetString doesn't have builder-method for Choice

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#43643]
In the snippet docs there's syntax for adding choices for placeholders:

> # Choice
> Placeholders can have choices as values. The syntax is a comma separated enumeration of values, enclosed with the pipe-character, for example `${1|one,two,three|}`. When the snippet is inserted and the placeholder selected, choices will prompt the user to pick one of the values.

Currently the `SnippetString` class has methods for `appendPlaceholder`, `appendVariable`, etc. but there isn't an option for choices. We can build these manually, but it'd be better if we could stick to a nice API.

**Comment by DanTup** [comment]
Also seems like the escape method is private, making it more difficult to do this manually without duplicating the implementation.

**Comment by DanTup** [comment]
Actually, `appendText` is escaped so it seems like we can't do this at all without building the whole string ourselves..

... or taking advantage of appendVariable not escaping name .... 😏

**Comment by jrieken** [comment]
Well, you can do `new SnippetString().appendXYZ().value += '${1|my,choice|}'`

**Comment by sksaifuddin** [comment]
Hello,is this issue solved ? I am new on this repo and looking for good first issues to solve, this issue looks good for my purpose. Can anyone please guide me about solving this please? @jrieken  @DanTup

**Comment by jrieken** [comment]
This issue would be closed if it's solved. So, "yes" it up for a grab. This is the code pointer entry point: https://github.com/microsoft/vscode/blob/e5a97bdf4dfe6ee596a99d35890101b77d2daed2/src/vs/workbench/api/common/extHostTypes.ts#L687.
