### ISSUE TITLE
False Automatic Problem Detection

### ISSUE THREAD

**Issue by GoodBoiDoggo** [Microsoft/vscode#43644]
### Issue Type
Bug

### Description

typing && inside an html attribute is detected as an error. (not an error coz angular app)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|7.89GB (1.69GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-html-css|ecm|0.2.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3

</details>
Reproduces without extensions

**Comment by egamma** [comment]
We need more information to reproduce the problem:
- in what file type do you see this error
- provide a snippet that illustrates the error
- provide the full error message.
