### ISSUE TITLE
Debugging not working in 1.20

### ISSUE THREAD

**Issue by adrianroworth** [Microsoft/vscode#43648]
**VSCode version info:**
Version 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:09:39.780Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**OS version:**
Windows 10

**Node version:**
v6.11.0

**Launch.json:**
````JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "root\\to\\app\\path.js",
            "remoteRoot": "/root/to/remote/app/path/"
        }
    ]
}
````

Does this issue occur when all extensions are disabled?: **Yes**

- Able to add and see breakpoint marker
- Does not break at breakpoint when debugger is running.

If "All Exceptions" is ticked in the "breakpoints" list in the debug view, then it will break on these exceptions. **All custom breakpoints do not cause the debugger to halt**.

**Comment by weinand** [comment]
What version of node are you using?

**Comment by weinand** [comment]
Since you have configured "localRoot" and "remoteRoot" you seem to use your launch config for remote debugging. But "address" is still "localhost".

Are you using the launch config for a WSL or Docker setup?

**Comment by weinand** [comment]
Do you debug a long running server or just a short "hello world" like program?

Im the latter case it might be better to use a launch configuration that launches the debuggee (instead of attaching to it),e .g.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/hello.js"
        }
    ]
}
```

**Comment by adrianroworth** [comment]
1) I am running my application inside a docker container. Which is the reason behind the remoteRoot property.

2) It is a long running server

**Comment by noctre-net** [comment]
hello,
I have faced the same issue - debugger successfully launches the app, but does not hit breakpoints.

Here is my environment info:
```
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

OS version Windows 10
Node version v6.11.0
```

And my `launch.json`:
```javascript
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}\\app.js",      
      "env": {
        "NODE_ENV": "dev",
        "DEBUG": "*"
      },
    }
  ]
}
```

The app is express-based web server.
Breakpoints worked fine in the past for this app - one thing that has changed since that time is updating VSCode.

**Comment by weinand** [comment]
@noctre-net please do not hijack other issues with unrelated issues. The original request is about remote debugging in a Docker container and I'm sure yours is not.

Please try the latest VS Code 1.21 and if you still see the problem create a new issue.

**Comment by ernie58** [comment]
@weinand I'm having the same issue as @adrianroworth 
I'm using vscode 1.21
This is my config:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Attach to docker",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": true,
            "sourceMaps": false,
            "outFiles": [],
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/API"
        },
        {
            "name": "Attach to tests",
            "type": "node",
            "request": "attach",
            "port": 5859,
            "address": "localhost",
            "restart": true,
            "sourceMaps": false,
            "outFiles": [],
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/API"
        }
    ]
}
```
I have a long running server inside a docker container

When I put a `debugger;` statement in my code, that seems to work.
But setting a breakpoint from VScode GUI not

**Comment by weinand** [comment]
What version of node.js are you using inside the docker container?
