### ISSUE TITLE
Support to customize the rendering of  white space 

### ISSUE THREAD

**Issue by lorrandavid** [microsoft/vscode#43647]
- VSCode Version: 1.20.0
- OS Version: Ubuntu 16.04.3

Steps to Reproduce:

1. Set indentation to tab
2. Press tab inside editor

![image](https://user-images.githubusercontent.com/17368070/36200440-cbb53fa4-1163-11e8-9c16-8e2bbbcd98bf.png)

Does this issue occur when all extensions are disabled?: Yes

Is there any way to change this arrow character? I've been searching it for a few days I can't find any settings that allow me to do that. It's not a bug but I think we should have an option to customize the editor, perhaps I want to use &raquo; instead of this arrow or another character.

**Comment by egamma** [comment]
The rendering for the tab character cannot be changed but you can disable it using the "editor.renderWhitespace" setting.

**Comment by lorrandavid** [comment]
@egamma thanks for the answer, maybe we can get this feature later on. I'll keep an eye on the updates!

**Comment by lorrandavid** [comment]
@egamma thanks for the answer, maybe we can get this feature later on. I'll keep an eye on the updates!

**Comment by CoericK** [comment]
So is there a way to actually show the arrows? I cannot find it, i only show dots

**Comment by Paalon** [comment]
Including other visualization of invisible characters, it is worth to implement.

**Comment by andoni980** [comment]
Why is worth?

**Comment by andoni980** [comment]
Sorry, I did't undestood the sentence.
it's ok
