### ISSUE TITLE
file search exclude broken in 1.20

### ISSUE THREAD

**Issue by ceres629** [Microsoft/vscode#43646]
- VSCode Version: 1.20
- OS Version: OSX 10.10

Steps to Reproduce:

1. Open a project
2. Do a project wide search
3. Search returns files in directories such as .git that should have been excluded according to my .gitignore.

Does this issue occur when all extensions are disabled?: Yes

1.19 also seems to have this issue. This problem does not exist in 1.18.1 and earlier, in 1.18.1 search does not show results from any files excluded in .gitignore.

**Comment by roblourens** [comment]
`.git/` is usually excluded by the default `files.exclude` setting. You must not have that set, please double check.
