### ISSUE TITLE
why it is coming after installing native-page transition

### ISSUE THREAD

**Issue by ramthename** [Microsoft/vscode#43657]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
atom-keybindings|ms-|3.0.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
Please explain the problem in more detail and provide steps for how to reproduce the problem.
