### ISSUE TITLE
html suggestion not working properly when using multiline

### ISSUE THREAD

**Issue by NeonPimpZ** [Microsoft/vscode#43658]
- VSCode Version: 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b)
- OS Version: Ubuntu 16.04.3 LTS

Steps to Reproduce:

1. Create HTML-File
2. ( | represents cursor ) + ctrl+space
2.1  Write code until linebreak occurs: 

```html
// working, suggests i.e.: `(keyup)=`
<input type="number" (wheel)="ignoreMouseWheel($event)" [...] (| required> 

// not working
<input type="number" (wheel)="ignoreMouseWheel($event)" [...] (|
       required>
```

**Comment by Shinigami92** [comment]
I can reproduce this

```html
<!-- empty space == tabs -->
						<input type="number" [(ngModel)]="item.amount" step="0.1" (| (keyup)="method1($event)" (change)="method2($event)" (wheel)="ignoreMouseWheel($event)" class="text-right" // line length = 192, linebreak through formatting
						    required>
```

**Comment by aeschli** [comment]
I think this issue needs to be filed against the Angular extension. Which one are you using?

**Comment by NeonPimpZ** [comment]
I'm using the following devDependency in my project:
`"@angular/language-service": "~5.2.4"`

also following vscode extensions are used:

- Angular.ng-template
- HookyQR.beautify
- Mikael.Angular-BeastCode
- abusaidm.html-snippets
- anseki.vscode-color
- christian-kohler.path-intellisense
- eg2.ts-tslint
- eg2.tslint
- formulahendry.auto-close-tag
- formulahendry.auto-rename-tag

**Comment by aeschli** [comment]
That's https://github.com/angular/vscode-ng-language-service then. Please file the issue there.
