### ISSUE TITLE
Allow more than 3 side-by-side views for 4k display users

### ISSUE THREAD

**Issue by colibrae** [Microsoft/vscode#43654]
I couldn't tell in the contribution guidelines if something that resembles a feature request is permissible so I am going to post this issue anyway.

I use a 4k display with 3840 pixel wide screen, and with the sidebar closed I can comfortably look at three source files with a reasonable sized font, *with the whole window only taking up half the screen*. It would be very useful if I could at least have four, like at the moment I need to look at some c code in two, but I also need another view for some go code related to what I'm working on because the C implementation has somewhat different data structuring and I need to be able to translate the C version into the Go version.

It's not high priority, of course, but I would expect that a growing number of coders are buying massive pixel displays like I have as a part of facilitating their easier workflow.

**Comment by bpasero** [comment]
Duplicate of #14909
