### ISSUE TITLE
VSCode starts automatically when run node application

### ISSUE THREAD

**Issue by fabianMendez** [Microsoft/vscode#43668]
- VSCode Version: 1.20.1
- OS Version: Windows 7 x86

Steps to Reproduce:

1. Create a node application
2. Set debugging breakpoints
3. Close vscode
4. Run the applications as follows: `node watch.js`

Does this issue occur when all extensions are disabled?: Yes

I have a nodejs application I had set some breakpoints to debug it, but when I try to run it outside of vscode (ie: vscode is closed),then vscode starts and the application stops

```log
C:\Users\...\>node watch.js
[2018-2-14 10:15:34] - .............

[main 10:15:35] update#setState idle
^C
```

**Comment by weinand** [comment]
How do you close VS Code in step 3?
what does watch.js do?

**Comment by fabianMendez** [comment]
I close VS Code using the X button

This is watch.js:

```js
const nodemon = require('nodemon');
const { log } = require('./utils');
const { filePath } = require('./config');

nodemon({
  watch: [filePath],
  exec: 'index.js'
})

nodemon
  .on('start', () => log('Updating file...'))
  .on('restart', (files) => log('File has been modified!'))
  .on('quit', process.exit)
```

Basically, it watchs a file for changes using nodemon and on start or when changes happen it runs index.js which update the file in the db

**Comment by fabianMendez** [comment]
Well, I spot the error (it's not a bug on VS Code), nodemon actually runs `index.js` and vs code is opened because it's the default editor:
```diff
- exec: 'index.js'
+ exec: 'node index.js'
```
