### ISSUE TITLE
Provide a command to delete the currently opened file

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#4366]
- VSCode Version: 0.10.11
- OS Version: Mac OS X El Capitan

Steps to Reproduce:
1. Open Command Palette
2. Search for a "delete" command
3. Note that command does not exist

I would have naturally expected this sort of command to be available from the Command Palette. :) Could we get this added, to enhance the already awesome keyboard experience? :smile: 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

<img width="168" alt="screen shot 2016-03-17 at 8 24 02 am" src="https://cloud.githubusercontent.com/assets/466713/13848968/bb146c4a-ec19-11e5-85c1-90d2a53cf887.png">

**Comment by bpasero** [comment]
Sounds like a good example for an extension.

**Comment by bgse** [comment]
@bpasero Maybe label as help-wanted / effort-easy so we can find stuff like this better. Or even make a label 'extension-opportunity' or something.

**Comment by pcgeek86** [comment]
@bpasero Hmmmm, I disagree that this would be suitable for an extension. A function like this, to delete a file, should probably exist in the core editor. What kind of criteria are you typically using to determine suitability for an extension? Just curious, thanks!

**Comment by bpasero** [comment]
If something can be done via extension, it should be done via extension. Once we add this functionality into the core product this extension is obsolete, but until then it is fine to have it. We currently have 595 feature requests and maybe 7 people working on the source code, so you can imagine that we are not jumping on every new feature someone asks for.

**Comment by pcgeek86** [comment]
@bpasero That makes sense -- so you would eventually plan on incorporating such features into the core product, but as a stop-gap measure, you want to use extensions, due to resource constraints. I understand, thanks. 

I wish I could contribute code, but this isn't my area of expertise, so I'll have to contribute primarily through bug reports and feature requests. :white_check_mark:

**Comment by martellaj** [comment]
Would you guys expect a confirmation dialog of any kind for this command? Like, "Are you sure you want to delete this file?" or no?

**Comment by bgse** [comment]
@martellaj With destructive operations like delete, I'd say a confirmation dialog should be there.

**Comment by pcgeek86** [comment]
Hard to say ... on one hand, yeah I'd expect to have one, but on the other hand, modal dialogs are evil.

**Comment by Tyriar** [comment]
No confirmation but an undo popup might be a nicer UX, especially if it's difficult to trigger the delete by accident. Would probably have to move the file to a tmp directory in order to do this.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/21344
