### ISSUE TITLE
Markdown file setting code snippets invalid

### ISSUE THREAD

**Issue by xluos** [Microsoft/vscode#43665]
### Issue Type
Bug

### Description

Markdown file setting code snippets invalid

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|7.92GB (3.06GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.4.5
vscode-great-icons|emm|2.1.24
vscode-power-mode|hoo|2.1.0
markdown-toc|jof|1.4.0
vscode-clang|mit|0.2.2
python|ms-|2018.1.0
cpptools|ms-|0.14.6
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|1.0.5

(6 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
I don't understand. Please describe the expected behavior

**Comment by xluos** [comment]
The code snippet in markdown.json is unavailable in the markdown file, and the code snippet for the other files is normal.

**Comment by xluos** [comment]
The code snippet in markdown.json is unavailable in the markdown file, and the code snippet for the other files is normal.

**Comment by pyrsmk** [comment]
I don't know if it's related, but since the last 1.20 update, I don't have syntax highlighting anymore in markdown's code snippets.

**Comment by mjbvz** [comment]
@xluos But this only happens when have extensions enabled? markdown-all-in-one or one of your other markdown extension may be causing this because I'm not able to reproduce the issue
