### ISSUE TITLE
Many things are duplicate on a mac - warnings, using suggestions

### ISSUE THREAD

**Issue by CoderJason123** [Microsoft/vscode#43663]
Hello.  I've been using VS Code on a mac for about a year, and I love it.  I thought this issue would get fixed previously by others so i never submitted it.  I primarily use C# mixed in with some reactjs and mvc apps.  

Many things on the mac in vs code are duplicated.  For example, build warnings / problems appear twice for the same issue, same line.  If i go to resolve unresolved references, each suggestion appears twice.

What next step or information can i give you to further investigate?

- VSCode Version:Version 1.20.0 (1.20.0)
- OS Version:mac os high sierra

Steps to Reproduce:

1. any project

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
@CoderJason123 please provide more information so that we can reproduce the problem:
- what is the project setup when this happens
- what warnings are duplicated, are these c# or javascript warnings (pls show a screenshot of the problems view)
- when do the duplicate warnins show up? Are you using tasks with problem matchers?

**Comment by CoderJason123** [comment]
Sure.  Here are 2 images below.  This is an aspnet core 2.0 project, with mvc.  This has happened probably since I started using vs code on the mac, over a year ago.


<img width="595" alt="screen shot 2018-02-14 at 3 13 33 pm" src="https://user-images.githubusercontent.com/33351931/36228377-b45233b8-1199-11e8-8f2e-8d63632e6d66.png">
<img width="792" alt="screen shot 2018-02-14 at 3 13 01 pm" src="https://user-images.githubusercontent.com/33351931/36228378-b465b1cc-1199-11e8-8828-e55b56b10913.png">

**Comment by egamma** [comment]
These errors and warnings are created by the C# extension, please report the issue against this extension in this repository: https://github.com/OmniSharp/omnisharp-vscode
