### ISSUE TITLE
Can't update insider preview since 10th February 2018

### ISSUE THREAD

**Issue by sstoychev** [Microsoft/vscode#43669]
- VSCode Version: 
Version 1.21.0-insider
Commit d28f096018e2673a8437c788e3eed781ddb505ce
Date 2018-02-09T05:14:50.066Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: 

Windows 10 pro
Version 1709
OS Build 16299.248 

core i7 6500 U
8GB RAM
Nvidia GeForce 940MX

Steps to Reproduce:

1. I'm using insiders build and I can't update since 10th February 2018. I'm getting the error from the attached file. I tried disabling all the extensions but it didn't work either:

`C:\Program Files\Microsoft VS Code Insiders>"Code - Insiders.exe" --disable-extensions

C:\Program Files\Microsoft VS Code Insiders>
[main 5:13:17 PM] update#setState idle
[main 5:13:47 PM] update#setState checking for updates
[main 5:13:48 PM] update#setState downloading
[main 5:14:20 PM] update#setState downloaded
[main 5:14:29 PM] update#setState updating
[main 5:14:59 PM] update#setState ready`

![vscode_update_fail](https://user-images.githubusercontent.com/11898259/36211228-54a9d2da-11a9-11e8-8fbc-4b59c2b4043b.PNG)

The error is in Chinese because my windows is originally installed in Chinese and I'm using English language pack. Some messages are still in Chinese. 
I tried to translate it but I get different translations - sometimes that the application cannot be started, others about some GUI problem and I have no idea which one is correct.

After I restart I still get the error, but the process in the terminal is not killed.
I also tried to start vscode as adminstrator, but I couldn't update it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sstoychev** [comment]
Today the update was OK. The current version is:

Version 1.21.0-insider
Commit 70e020b2377f12894ca11254548ce365a0e435f1
Date 2018-02-15T05:17:01.988Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by joaomoreno** [comment]
Excellent. Can you translate the error for me, please?
