### ISSUE TITLE
vscode workspaces unable to see git changes in explorer

### ISSUE THREAD

**Issue by reggi** [Microsoft/vscode#43673]
- VSCode Version: Version 1.20.1 (1.20.1)
- OS Version: 10.12.6

Steps to Reproduce:

1. Add several folders to workspace.
2. Make a change in not the first folder, it doesn't show.

For some reason only the first folder, the original project where you created the workspace shows it's git changes.

What is expected is that:

* When I click a workspace it changes the Source Control tab to be relative to whatever folder is focused.
* When I make a change in a repo it shows it in the orange-y color, notifying there's an edit.

> One of the main things I would like to use a workspace for is to be able to view git changes for different git repos, all at once.

Understandable that it may be slow to implement this properly. A simple solution would be to add the ability to right-click on a workspace and select "Git Focus", then it can switch from one repo to another.

**Comment by reggi** [comment]
Odd behavior is that If I open up the workspace file with another editor, and move one of the projects from the bottom, to the top. Then it gets added to the "Source Control Providers" list in the "Source Control" tab. Ideally it would load all of the repos into here.

This also allows it to show in the Explorer view, but spotty, I'd expect each parent directory to show change, even the workspace itself. But I am seeing this:

![image 2018-02-14 11-22-55](https://user-images.githubusercontent.com/296798/36215296-b19847b8-1179-11e8-8fcb-43c54c2a7bd8.png)

Here I'd expect "app" and "backened" to be orange.

**Comment by joaomoreno** [comment]
> Make a change in not the first folder, it doesn't show.

What exactly doesn't show?

When you open a workspace with two folders and each is a git repository, how does the SCM view appear? Can you show me a screenshot?

**Comment by hannupekka** [comment]
I have this same issue: workspace with 7 folders. If I minimize all the folders, VSCode does not detect changes in some of the folders. 

For example:

![vscode](https://user-images.githubusercontent.com/4472477/36582180-1ed0a6e4-1879-11e8-83b4-75c0ba28eb01.png)

3rd folder from top has changes in one file, as does 3rd folder from bottom. However, VSCode does not show any changes for 3rd from top. If I expand 3rd one from top, it does indicate changes to that one file in the explorer, though.

**Comment by joaomoreno** [comment]
This is https://github.com/Microsoft/vscode/issues/44036 which was fixed a couple days ago.
