### ISSUE TITLE
No keyboard shortcut to open current file in explorer

### ISSUE THREAD

**Issue by Mellbourn** [Microsoft/vscode#43676]
Prior to version 1.20.0, it was possible to open the current file in the file explorer using the `Cmd-Enter` keyboard shortcut. That keyboard shortcut has been removed. The only workaround I have found (except using the mouse) is `Ctrl-Enter`, but that doesn't open the file in the current editor group.
Unfortunately, I can't even recreate the command binding, because I cannot find the command to bind. Is it gone? If so, then I'd like that back too.

To code quickly, I avoid the mouse when I can. For me it was a very common use case to open the file explorer with `Cmd-Shift-E`, navigate to a file using the arrow keys, and then open the file with `Cmd-Enter`.

From the release notes, it seems likely that this change is related to the new multi select functionality. It sounds like I should be able to "get back the old behavior" by setting `"workbench.list.multiSelectModifier": "alt"`, but this does not restore the keyboard shortcut.

(A related aside: It seems a bit ridiculous that the "rename" functionality is on the `Enter` key. I open files far, far more often than I rename them. Couldn't `Enter` open the file instead?)

Thanks for an otherwise great product!

- VSCode Version: 1.20.1
- OS Version: macOS 10.13.3

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@Mellbourn we use enter to rename the same way mac Finder does.
We will fix your issue as part of https://github.com/Microsoft/vscode/issues/42573
The fix will be in insiders release soon, so you can give that a try if you are really relying on this functionality.
