### ISSUE TITLE
SCM API handle merge conflicts like git does

### ISSUE THREAD

**Issue by JohnstonCode** [Microsoft/vscode#43672]
Would it be possible to create an API for SCM providers to use to handle merge conflicts like git does?

**Comment by joaomoreno** [comment]
@JohnstonCode What do you mean by `handle merge conflicts like git does`? Note that git is an extension. Whatever git features VS Code has, happen via the extension API.

**Comment by JohnstonCode** [comment]
[Like this](https://code.visualstudio.com/Docs/editor/versioncontrol#_merge-conflicts)

**Comment by joaomoreno** [comment]
That is all achieved via API: https://github.com/Microsoft/vscode/tree/master/extensions/merge-conflict
