### ISSUE TITLE
previewHtml "errors" show up in the Problems pane

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#43678]
### Issue Type
Bug

### Description

It seems that "errors" in the html/css of a previewHtml tab show up in the Problems pane. This seems counterintuitive to me as the user has no ability to fix them. And in the particular case I saw it (GitLens), I disagree that they are errors.

To see this -- open the GitLens Welcome (`GitLens: Welcome` from the Command Palette). You will notice 5 "problems" show up in the Problems pane.

![image](https://user-images.githubusercontent.com/641685/36215916-6703bfd2-117b-11e8-9581-8000968a4ffc.png)

In this particular case none of these "errors" are actually errors. They are future-proofing for later version of Chrome which will support these properties un-prefixed.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (135d4a5d5cecd82e9e4da7ede655fb09af0dac35, 2018-02-14T05:16:54.138Z)
OS version: Windows_NT x64 10.0.17093

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|31.93GB (16.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces only with extensions

**Comment by aeschli** [comment]
I added support for mask- properties, so these particular errors won't show up anymore.
But I wonder too why documents opened in preview get a document that is synced to the extension host. @jrieken probably knows

**Comment by jrieken** [comment]
> But I wonder too why documents opened in preview get a document that is synced to the extension host.

Why not? It's a file on disk and it's being loaded as document (in order to preview it)

**Comment by jrieken** [comment]
As for today, that's just the design of the system and the reason why we keep saying 'do not build UX with the preview command'. Help is on its way as we are building a better version of the preview feature (one that doesn't rely on virtual documents anymore).
