### ISSUE TITLE
Clicking on the method name doesn't go to method in another .js file

### ISSUE THREAD

**Issue by farazdurrani** [Microsoft/vscode#43685]
### Issue Type
Bug

### Description

I have imported a .js file like this in my current .js file:

`import serviceHelper from '../../api/util/helper.js';
`
Then inside a method in this current js file, I am calling a method of serviceHelper like this:

```
let method0= (params, callback) => {
....	
serviceHelper.method1(params, function(body) {
...
});
});
```

When I CTRL + left click on method1, it doesn't take me to method1 in helper.js. It doesn't go anywhere. It used to take me there no problem 2 updates ago. Something broke?

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|15.88GB (9.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Do you have a [jsconfig.json](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) file? Can you please share some complete, minimal example code
