### ISSUE TITLE
Leak: quick open (files) leaks ActionBar and HiglightedLabel

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4368]
Seeing a wide range of objects stick around after just opening and closing quick open:

![image](https://cloud.githubusercontent.com/assets/900690/13849061/c56b877e-ec54-11e5-96a9-fe6efbe4023f.png)

**Comment by bpasero** [comment]
@joaomoreno boils down to the Renderer in https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenModel.ts#L651 not disposing the template it creates for templateId === templateEntry || templateEntryGroup. I think you added this but I am not sure why it is not getting disposed. One thing I notice is that disposeTemplate() is being called each time you type and get results for the file picker.

**Comment by joaomoreno** [comment]
This was introduced with the adoption of rendering templates.

Fixed in 7f5a4582091feabf3111aa7f34a9d90256d15d67
