### ISSUE TITLE
Incorrect text on page https://code.visualstudio.com/docs/getstarted/theme-color-reference

### ISSUE THREAD

**Issue by mbenkmann** [Microsoft/vscode#43682]
The page https://code.visualstudio.com/docs/getstarted/theme-color-reference
contains this text:

> The most prominent editor colors are the token colors that are based on the language grammar installed.  These colors are defined by the Color Theme and can (currently) not be customized in the settings.

That is incorrect. The current version of VS Code allows you to customize token colors in the user settings as described here:

https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/9cd5c96885ffa727bddee186c8f267b0a6f734ef
