### ISSUE TITLE
Git not available in source control panel

### ISSUE THREAD

**Issue by mikepelley** [Microsoft/vscode#43686]
### Issue Type
Bug

### Description

Fresh install, no git icon in source control panel ("There are no active source control providers"). Already had Visual Studio Community and Git 2.16.1 (64-bit) installed and working. Git is available in the path, tested in regular cmd window. Tried adding git.path to user settings without success. Here's the User Settings file:
{
    "git.path": "C:\\Program Files\\Git\\cmd\\git.exe",
    "git.defaultCloneDirectory": "C:\\Users\\mike\\Documents\\Workspace"
}

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|Memory (System)|15.93GB (7.98GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
gitlens|eam|8.0.0
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.5
svn-scm|joh|1.19.0
python|ms-|2018.1.0
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
team|ms-|1.122.0
html-css-class-completion|Zig|1.16.2

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
If you run `Git: Show Git Output`, what appears?

**Comment by mikepelley** [comment]
In the command palette, Git: Show Git Output is not available. There are only two Git: commands - Clone and Initialize Repository, and a couple of GitLens commands.

**Comment by joaomoreno** [comment]
@mikepelley Go `View > Output`, then pick the `Git` output channel in the dropdown.

**Comment by mikepelley** [comment]
Looks good:
`Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.16.1.windows.1 from C:\Program Files\Git\cmd\git.exe
git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git`
But Source Control says "There are no active source control providers".

**Comment by joaomoreno** [comment]
```
git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
```

This means the folder you have opened isn't a Git repository.
