### ISSUE TITLE
JavaScript properties missing

### ISSUE THREAD

**Issue by Diamond-Frost** [Microsoft/vscode#43680]
I only realized this on JavaScript in HTML, even though it may be on more languages:
When I coded, I noticed some properties I know are in JS weren't showing in the suggestion menu and didn't have any info about them. I still remember `document.getElementById( "someId" ).value` ( .value is missing in this example ) which is not in the menu and is said to return `any`

- VSCode Version: 1.20.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. add missing information & add properties

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
https://stackoverflow.com/questions/12989741/the-property-value-does-not-exist-on-value-of-type-htmlelement
has the answer...
