### ISSUE TITLE
Autocomplete not working with paths aliases

### ISSUE THREAD

**Issue by guilima** [Microsoft/vscode#43688]
- VSCode Version: 1.20.1
- OS Version: Linux (Ubuntu 16.04)

Steps to Reproduce: 
1. Create a paths alias in the jsconfig.json like: "paths": { "modules/\*": ["src/modules/\*"] }
2. Import from the alias triggering intellisence after writing `import {} from "modules/"`. This will not show any folder only files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/21589
