### ISSUE TITLE
Bug report Preview On Github button does not work

### ISSUE THREAD

**Issue by MuratOzsoyler** [Microsoft/vscode#43690]
Clicking Preview on Github button opens an empty browser (Microsoft Edge) tab but apparently no request to Github issued.

- VSCode Version: 1.20.1
- OS Version: Windows 10 1709

Steps to Reproduce:

1. Click Help --> Report Issue menu.
2. Bug report window opens up.
3. Fill in the fields.
4. Click Preview on Github button.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
Are you able to open links from other applications, like Slack or Outlook? What version of Edge are you using?

**Comment by MuratOzsoyler** [comment]
Unfortunately I use neither Slack nor Outlook. But clicking Help --> Documentation menu opens documentation in Edge. Sendfeedback menu in Libre Office also opens related page in Edge.

I can not get the Edge version (neither in Edge, nor in App list in Settings). But install date is 14.12 .2018.

**Comment by MuratOzsoyler** [comment]
Just changed the default browser to Chrome. It worked. Seems something wrong with the Edge. I will change the default back, and report the result.

**Comment by MuratOzsoyler** [comment]
It is working now! I don't know what is changed but it definitely works. Sorry for the misinformation.
