### ISSUE TITLE
Copying from the integrated terminal removes spaces if they are at the end of a line when there are multiple lines of text

### ISSUE THREAD

**Issue by oneoffaccount** [Microsoft/vscode#43696]
- VSCode Version: 1.20.1
- OS Version: Red Hat Enterprise Linux Workstation release 7.2 (Maipo)

Steps to Reproduce:

1. Type text into integrated terminal window that has a space at the end of one of the lines that gets line wrapped.
2. Copy and paste that text into a different window (you can use Cntrl+Shift+C or select and then use middle mouse button)
3.  The copied text will be missing spaces that are at the end of the line wrapped lines.

See the attached picture for an example of the problem.  I can reproduce it easily.  It still occurs with all extensions turned off.  This bit me because I was copying log file from the terminal into another program, but because it removed the spaces the other program wasn't able to parse the log file info properly.

![vscodeterminalcopyspacebug1](https://user-images.githubusercontent.com/30274033/36229584-aac6c74c-11cf-11e8-9ef2-7d5e4ab26d2f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I guess the right whitespace trimming stuff does not look for wrapped lines currently.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1286

**Comment by Tyriar** [comment]
Tracking upstream.
