### ISSUE TITLE
Holding CTRL while clicking a file in the directory tree no longer opens it in the right-side pane

### ISSUE THREAD

**Issue by agm1984** [Microsoft/vscode#43693]
- VSCode Version: V 1.2.0 (Commit: c63189deaa)
- OS Version: Win 10

Steps to Reproduce:

1. Open VS Code
2. Open a project with multiple files
3. Open a file
4. Click a file in the directory tree while holding CTRL

**Actual Results:** File does not open in the right half of the screen
![files](https://user-images.githubusercontent.com/17655219/36227180-1773f52c-1185-11e8-9b3e-cbf0a57fb608.png)

**Expected Results:** File used to open here until the last update that made changes to the directory tree
It appears to be a regression. The hotkey is no longer working.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
`"workbench.list.multiSelectModifier": "alt",` ?

**Comment by agm1984** [comment]
Lol, you're right. It actually works fine if I just hold ALT instead of CTRL.

Thanks for including that setting. I will close this issue. I don't even have to try adding that option because I probably got it mixed up in my head, in which case I am sad I didn't even try alt or shift just in case.
