### ISSUE TITLE
Possibility to add folders one by one in Source Control (GIT) not all files

### ISSUE THREAD

**Issue by radubcrisan** [Microsoft/vscode#43697]
I have a folder with other subfolders. Then in each subfolder many files (over 1000). I want to stage, commit each subfolder at a time (not all subfolders folders at once).

Right now I do not have in VSCode a way to do this easily form interface, I do not want to add 1000 files one by one to click the + sign.

- VSCode Version: 1.20.1
- OS Version: Ubuntu 17.04

**Comment by radubcrisan** [comment]
In terminal we can give the following command on that : `git status *` but wold be nice to have this on interface.

**Comment by joaomoreno** [comment]
For now, you have to resort to using the command line: `git add FOLDER`.

If we show SCM resources as a tree, then we can do it: https://github.com/Microsoft/vscode/issues/14582
