### ISSUE TITLE
Test Failure: FileSearchEngine Files: *.* exclude with unicode on macOS

### ISSUE THREAD

**Issue by humphd** [Microsoft/vscode#43691]
The following test in `src/vs/workbench/services/search/test/node/search.test.ts` fails for me on one of my Macs, and not on the other:

```ts
test('Files: *.* exclude with unicode', function (done: () => void) {
	this.timeout(testTimeout);
	let engine = new FileSearchEngine({
		folderQueries: ROOT_FOLDER_QUERY,
		filePattern: '*.*',
		excludePattern: { '**/üm laut汉语': true }
	});

	let count = 0;
	engine.search((result) => {
		if (result) {
			count++;
		}
	}, () => { }, (error) => {
		assert.ok(!error);
		assert.equal(count, 13);
		done();
	});
});
```

I consistently get it to pass on my iMac, and it always fails on my Macbook, seemingly ignoring the `excludePattern` and thus getting 14 vs. 13 results:

```
1 failing

  1) FileSearchEngine Files: *.* exclude with unicode:
     Error: Uncaught AssertionError: 14 == 13
```

Both systems *seem* identical to me:
* macOS 10.13.3
* on commit `master` (00262fb3900)
* `yarn list` reports identical versions of all installed modules

What else could be different that I'm not looking at?

**Comment by humphd** [comment]
cc @chrmarti in case https://github.com/Microsoft/vscode/commit/783df422b9f0309c09cd4b791502cb7be950ad68 somehow explains this.

**Comment by chrmarti** [comment]
What do you get for `ls -d *laut* | hexdump` on the two machines?                                                                                                                                          

I have: `0000000 c3 bc 6d 20 6c 61 75 74 e6 b1 89 e8 af ad 0a`

**Comment by chrmarti** [comment]
Also, what do you get for `grep laut search.test.ts | hexdump` on the two machines?

I have:
```
0000000 09 09 09 65 78 63 6c 75 64 65 50 61 74 74 65 72
0000010 6e 3a 20 7b 20 27 2a 2a 2f c3 bc 6d 20 6c 61 75
0000020 74 e6 b1 89 e8 af ad 27 3a 20 74 72 75 65 20 7d
0000030 0a
```

**Comment by humphd** [comment]
Updated `master` to 7ddd37c10ef1d5.  @chrmarti there are some differences when I run those commands.

On Macbook Pro, which **fails** the test:

```
$ cd ./src/vs/workbench/services/search/test/node/fixtures
$ ls -d *laut*
üm laut汉语
$ ls -d *laut* | hexdump
0000000 c3 bc 6d 20 6c 61 75 74 e6 b1 89 e8 af ad 0a
000000f

$ grep laut src/vs/workbench/services/search/test/node/search.test.ts
            excludePattern: { '**/üm laut汉语': true }
$ grep laut src/vs/workbench/services/search/test/node/search.test.ts | hexdump
0000000 09 09 09 65 78 63 6c 75 64 65 50 61 74 74 65 72
0000010 6e 3a 20 7b 20 27 2a 2a 2f c3 bc 6d 20 6c 61 75
0000020 74 e6 b1 89 e8 af ad 27 3a 20 74 72 75 65 20 7d
0000030 0a
0000031
```

On iMac, which **passes** the test:

```
$ cd ./src/vs/workbench/services/search/test/node/fixtures
$ ls -d *laut*
üm laut汉语
$ ls -d *laut* | hexdump
0000000 75 cc 88 6d 20 6c 61 75 74 e6 b1 89 e8 af ad 0a
0000010

$ grep laut src/vs/workbench/services/search/test/node/search.test.ts
			excludePattern: { '**/üm laut汉语': true }
brightness:vscode humphd$ grep laut src/vs/workbench/services/search/test/node/search.test.ts | hexdump
0000000 09 09 09 65 78 63 6c 75 64 65 50 61 74 74 65 72
0000010 6e 3a 20 7b 20 27 2a 2a 2f c3 bc 6d 20 6c 61 75
0000020 74 e6 b1 89 e8 af ad 27 3a 20 74 72 75 65 20 7d
0000030 0a
0000031
```

**Comment by humphd** [comment]
Another note: my `git config` on both machines has `core.precomposeunicode=true`
