### ISSUE TITLE
search.exclude not excluding directories when searching

### ISSUE THREAD

**Issue by joevandyk** [Microsoft/vscode#43695]
### Issue Type
Bug

### Description

search.exclude directories are still being searched. screenshot: http://take.ms/n76sU

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.06GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_61455|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-github|Kni|0.26.0
vscode-docker|Pet|0.0.24
vscode-eslint|dba|1.4.5
Go|luk|0.6.76
Ruby|reb|0.16.0
haml|vay|1.0.1
vim|vsc|0.10.13
vscode-open-in-github|ziy|1.3.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by joevandyk** [comment]
Thanks!  http://take.ms/LxlRC is what I see. 

Interestingly I somehow have "disregardExcludeSettings: true" -- that wasn't intentional on my part.

**Comment by roblourens** [comment]
Yes this is because the "Use exclude settings and ignore files" button is toggled off. I didn't notice it in the original screenshot but it's the gear icon below the search input. It's turned on by default but you may have hit it by accident.

**Comment by joevandyk** [comment]
Ah, I see!  Thanks, I didn't see that either.
