### ISSUE TITLE
add new extension category for language packs

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#43701]
We need to add a new category for `package.json` categories. the proposal is this:

* Rename "Languages" to "Programming Languages" in the Marketplace
  * Keep the `Languages` category for `package.json`
* Add a new category to the marketplace called "Language Packs"
* Add a new category for `package.json` called  `LanguagePack`

**Comment by chrisdias** [comment]
https://github.com/Microsoft/vscode/blob/d917cc6bc408822160ff2aad2f3a223c7f5d1e51/src/vs/platform/extensions/common/extensionsRegistry.ts#L151

not sure if it needs to be added anywhere else.

**Comment by sandy081** [comment]
Added `Language Packs`  category to `package.json`. To be consistent with other categories, made it plural and added space.
