### ISSUE TITLE
Proposal: Camelcase all keys in settings

### ISSUE THREAD

**Issue by iamclaytonray** [Microsoft/vscode#43705]
Feature Request:

Because most of the keys in settings are properly camel cased, I propose to finish that. For example, `git.autofetch` should become `git.autoFetch` for better consistency and clarity. If this is approved, I'll send a PR over. Shouldn't take that long to do.

I know this is not a major issue so I have no problem backlogging this for a while.

**Comment by joaomoreno** [comment]
Although this is reasonable logic, it is neither a bug nor a feature request. It's fine to have a few inconsistencies here and there, especially considering the fact that we'd need migration code for all existing settings out there; or worse, we'd need to support both cases. For those reasons, I'll close this issue.
