### ISSUE TITLE
Code variables support in Snippet syntaxt

### ISSUE THREAD

**Issue by asierralozano** [Microsoft/vscode#43703]
Hello!

It would be great to have code variables in the snippet syntax, like $classname, $methodname, etc...
It will need to probably to analyze the current cursor position, and evaluate the code to get those variables, and probably should be also something extension dependent, to include all third-party languages supported by Visual Studio Code.

If you need an example, just let me know! :)

**Comment by jrieken** [comment]
closing as dupe of #10561
