### ISSUE TITLE
git for window take up high memory

### ISSUE THREAD

**Issue by MillionQW** [Microsoft/vscode#43717]
I found that when I using vscode and change my code frequently, a process named 'git for window' always take up high memory , which usually lead to my computer crashed.
![20180215124300](https://user-images.githubusercontent.com/22469401/36241036-c0a1a116-124e-11e8-8b48-a3e3599d6e6a.png)

I ever try to reinstall vscode, but it does not work. This problem only  appear in my computer.

**Comment by joaomoreno** [comment]
Can you show me the full command line of those processes, using Process Hacker?

**Comment by MillionQW** [comment]
@joaomoreno what information you want ? like this?
![qq 20180225220815](https://user-images.githubusercontent.com/22469401/36642326-f5041100-1a78-11e8-80ff-113a408accd8.png)
![qq 20180225220828](https://user-images.githubusercontent.com/22469401/36642327-f878d14a-1a78-11e8-92a9-832c8b6e4afd.png)
![qq 20180225220702](https://user-images.githubusercontent.com/22469401/36642328-fc4af816-1a78-11e8-9713-afaf45e2c2e4.png)

**Comment by joaomoreno** [comment]
This column:

![32851867-4322-df11-98b7-0022190f5762_2_full](https://user-images.githubusercontent.com/22350/36663688-a8af64a2-1ae2-11e8-8d6b-a0b88243dded.jpeg)

You can also use the filter box to only show the git processes.

**Comment by MillionQW** [comment]
![git for window](https://user-images.githubusercontent.com/22469401/37341957-2b22e374-26fe-11e8-940a-9f33a9b7ffc3.png)
@joaomoreno

**Comment by joaomoreno** [comment]
@MillionQW What git version do you have? Can you update to the latest?
