### ISSUE TITLE
Prompt when jumping over save points when undoing in the editor

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#43716]
Feature request or easy to add extension?

This a feature from some other editor I find useful. Basically I want undo to pause the last time the file was saved and ask "Continue to Undo Past Save Point?". I find that super valuable as I often just want to undo all edits since the last 1 or more saves. With that feature I just press and hold Undo until I get the prompt, no thought needed. Without that feature I have to carefully watch all the undos and pray I remember when I last saved. If there are hundreds of undos it's fairly hard.

Note: I get that I can just close the file and re-open but that only works for one last save. If I've saved 5 times then I press and hold undo until I get the prompt, click to continue, then press and hold again, repeat, until I get to the save point I wanted. I also get that if I was checking into some VCS on ever save that I could restore a version 5 versions ago but not all files are in a VCS or are new and have not been added yet.

So, Please consider this request for one of the follow.
* a feature request for the feature described
* a request some events/hooks to make it easy to add
* pointers/tips on how to add it if it's already easy

**Comment by bpasero** [comment]
@jennapv isn't what you want that the editor dirty indicator turns off once you reached the saved state again?

**Comment by jennapv** [comment]
Checking the dirty indicator does not seem like enough. Example

1.  type "abc"<enter>"def" <enter> save
2. type "ghi"<enter>"jkl" <enter> save
3. type "123", Now dirty indicator is on
5. Press undo, "123" is removed, dirty indicator is off 
6. Press undo, "jki" is removed, dirty indicator is off 

     here is where I would like a prompt before undoing since I'm going to pass
     a save point, could check dirty indicator went from off to on? but it's not enough see below.

7. Press undo, "ghi" is removed, dirty indicator is still on
8. Press undo, "def" is removed, dirty indicator is still on

     Here again I'd like a prompt as I'm passing a save point, the dirty indicator will not change here
     it will remain on.
