### ISSUE TITLE
[hidpi] Scaling is not recomputed when changing between high/regular-DPI monitors (chromium behaves correctly)

### ISSUE THREAD

**Issue by colemickens** [Microsoft/vscode#43710]
- VSCode Version:
```
Version 1.21.0-insider
Commit 9a4ba7d06157091c882a03f118793db5d4657a82
Date 2018-02-12T06:16:15.252Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
- OS Version: Linux 4.15

Steps to Reproduce:

1. Run Visual Studio Code - Insiders on a machine with a high dpi screen.
2. Return home, dock your machine in a configuration with a single regular dpi screen.

Note:

1. `google-chrome-unstable` properly resizes itself to normal scaling.
2. `code-insiders` stays doubled, and is unusable.

Note, this also affects VSC when running in mixed DPI modes, but Chrome also doesn't handle this perfectly. Chrome will use the scaling of the primary monitor. For this exact bug, I'm only worried about moving between docked/undocked. It's a pain to have to restart VSC when everything else just works.

Screenshot of VSC being improperly still scaled at 2x:
![screenshot from 2018-02-14 18-23-09](https://user-images.githubusercontent.com/327028/36237952-297c92d6-11b4-11e8-8f05-df39486dd85a.png)

Screenshot of Google Chrome dev edition properly scaled at 1x (w/o restart):
![screenshot from 2018-02-14 18-23-18](https://user-images.githubusercontent.com/327028/36237953-29939558-11b4-11e8-8db7-41ad973a0f67.png)

**Comment by bpasero** [comment]
@colemickens could you try with this newer build for Linux to reproduce: https://az764295.vo.msecnd.net/exploration/ed422f909ea470f79e3e3e39c948803d9b764919/code-exploration-1.22.0-1522303929_amd64.tar.gz

**Comment by colemickens** [comment]
@bpasero Howdy. Hit this again today, tried your build. I can only confirm one direction (long story, year of Linux on the desktop, etc), but it behaved as expected when I transitioned from an external standard-DPI monitor, back to the internal display scaled at 2x. The UI displayed normally without me having to restart the editor.

Out of curiosity, what did you do? Was it bumping electron?

**Comment by bpasero** [comment]
@colemickens yes that build is using a much newer Electron build. Did you see any difference with that build?

**Comment by colemickens** [comment]
Yeah, I had mention that it did correct re-adjust when switching from low-DPI to high-DPI. I was unable to test the other direction but I assume it works.

**Comment by colemickens** [comment]
@bpasero Any ideas when Electron will be rev'd? I assume it impacts lots of other things. Maybe there's an Issue I can follow?

And/or can we re-open this bug?
