### ISSUE TITLE
Replace dialog is not intuitive

### ISSUE THREAD

**Issue by kontomondo** [microsoft/vscode#43711]
- VSCode Version: 1.20.1
- OS Version: Any

Steps to Reproduce:

1. Activate the Replace dialog
2. Replace in selection, replace and replace all icons are small and not intuitive, requiring hover overs to read the meaning of the said icons.

Suggestion: Have buttons with text instead of icon-only, eg. having "Replace" and "Replace All"  buttons instead of the current icon. Would be great to have a checkbox with associated "In selection" text instead of the icon as well.

Does this issue occur when all extensions are disabled?: Yes

**Comment by chojrak11** [comment]
Basically, find in selection and replace in selection doesn't work at all... 1.21.0 here.
