### ISSUE TITLE
Shortcuts to switch between left/right terminal does not work

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#43721]
### Issue Type
Bug

### Description

- Ctrl+`
- Cmd+D
- Cmd+Alt+Left prints "1D" to the left terminal, does not switch focus
- Set focus on left terminal with mouse
- Cmd+Alt+Right prints "1C" to the left terminal, does not switch focus

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (135d4a5d5cecd82e9e4da7ede655fb09af0dac35, 2018-02-14T06:09:28.551Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|4, 3, 4|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions disabled</summary>

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
@chrmarti do you redefine `commandsToSkipShell` in your settings?

**Comment by chrmarti** [comment]
@Tyriar Yes. It works when I comment the setting, it doesn't work when the setting is the empty list.

**Comment by Tyriar** [comment]
@chrmarti this is as designed, currently setting that to anything will override *everything*, so you need to have this in the new list or it won't work:

```
"workbench.action.terminal.focusTerminalLeft", "workbench.action.terminal.focusTerminalRight"
```

The bad design problem is tracked in https://github.com/Microsoft/vscode/issues/19770 😄
