### ISSUE TITLE
Fails to debug Node.js with Segmentation Fault:11 error

### ISSUE THREAD

**Issue by gunjpan** [Microsoft/vscode#4372]
- VSCode Version: 0.10.11 (commit # f291f4ad600767626b24a4b15816b04bee9a3049)
- OS Version: OS X El Capitan (10.11.3)

Steps to Reproduce:

1. run node debugger as `node --debug-brk <anyfile.js>`
2. change debug mode to `attach` and step thru. 
It terminates debugger with `Segmentation fault: 11`

**Comment by enzoaeneas** [comment]
This is occurring on Windows 7 as well in Launch mode.
Continue and expression evaluation fail because node has become unresponsive.

**Comment by weinand** [comment]
@enzoaeneas Windows does not have a "Segmentation Fault: 11" error. If you want to have your issue investigated, please create a new issue with full details.

**Comment by weinand** [comment]
@gunjpan What version of node are you using? Is the problem reproducible if you install a different version of node (e.g. 4.x -> 5.x or 5.x -> 4.x, or 0.12.x)?

If a different version of node makes no difference could you please provide a code snippet that shows the issue?

**Comment by gunjpan** [comment]
@weinand : Thank you for the reply.. Looks like it was an issue with Node version. I was on Node v. 4.3.x, changing it to the latest as well as LTS 4.4.0 made debug work again. Closing it.
