### ISSUE TITLE
VS Code Setup Error - uc.micro folder creation access is denied

### ISSUE THREAD

**Issue by sefo** [Microsoft/vscode#43727]
- VSCode Version: 1.20.1
- OS Version: Windows x64

Steps to Reproduce:

1. Update current VSCode install
2. Or just install from scratch

I've been using VSCode for months on my work laptop doing updates and installing plugins.

Trying to install the 1.20.1 upgrade destroyed everything.

At first I got the error https://github.com/Microsoft/vscode/issues/21711

The annoying solution proposed there was to uninstall and reinstall.

Installing the new version from scratch I got the "cannot create uc.micro folder" bug.

Whether the antivirus blocks it or not, this is not an issue with the antivirus. (I can't disable it or create rules anyway) VSCode has worked in the past and doesn't anymore.

Then I tried using the zip version but I got a bunch of "cannot find ouput file" errors while trying to unzip the "resources/app/extensions/extension-editing" and "resources/app/extensions/markdown" folders.

I solved those by just not unzipping them. I guess I won't be using these 2 extensions.

Now VSCode is working, using settings from the previous install which is a *very good thing*.
I just lost 2 hours doing this.

**Comment by joaomoreno** [comment]
> Whether the antivirus blocks it or not, this is not an issue with the antivirus.

How are you sure this is not an issue with the antivirus. Something in your system is preventing from extracting the `uc.micro` folder. We need to find out what that thing is.

**Comment by sefo** [comment]
Yes, this is an issue with McAffee antivirus (for which I don't have the rights to add an exception)

However there's a second with the zip version on extensions "resources/app/extensions/extension-editing" and "resources/app/extensions/markdown"

That can also be an issue with McAffee but it used to work on every upgrade until now.

**Comment by CarreraPHP** [comment]
This Issue is happening to me as well. In earlier versions like 1.18, there was option to ignore copying of the "uc.micro" folder files, this is not there in 1.20. Also, when the Installation/Update rollbacks, it crashes the existing version as well.
