### ISSUE TITLE
PHP Class names that are all upper case are displayed white while others green

### ISSUE THREAD

**Issue by NoOorZ24** [Microsoft/vscode#43726]
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

In php file write:

DB::function();
Db::function();

first one has white class name (because all are upper case),
secound one has green (because has lowercase).

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by NoOorZ24** [comment]
It seems like it's white when ever there are at least 2 upper case characters in naming:
A:: is green
TwoWhite:: is white

**Comment by roblourens** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/43483
