### ISSUE TITLE
 Uncaught Error: Error processing 'threads' request. Unknown Error: 0x8007139f

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43729]
Issue Id: <b>8dc9ecee-9b0b-a996-f28d-98ae597ed736</b><br /><br />*Versions* <br />- 1.20.0<br />-  f9398645d1d624538708eeebf96e6fdeb546f5d7<br />-  3f8cf5311b631c5bc395df1e8b9c795358c1ef80<br />-  f2b21097100fc2fc0e84cc34f453c9a85a49a2bb<br />*Stack* <br />Error: Error processing 'threads' request. Unknown Error: 0x8007139f<br />[/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L193:92](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L193:92)<br />[/vs/base/common/winjs.base.raw.js#L1209:0 (onError)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1209:0 (onError))<br />[/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1041:0 (_run)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1041:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L53:5 (errorDispatch)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L53:5 (errorDispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L136:6 (clb)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L136:6 (clb))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L104:11 (dispatch)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L104:11 (dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L41:8 (handleData)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L41:8 (handleData))<br />    at emitOne (events.js:96:13)<br />

**Comment by isidorn** [comment]
This error should pop up to the user and be reported in telemetry.
However nothing we can do about it since it comes from an debug adapter and the message is not specific enough
