### ISSUE TITLE
 Not supported

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43732]
Issue Id: <b>a87fda22-596e-74c4-8ffc-2577338225a0</b><br /><br />*Versions* <br />- 1.20.0<br />-  f9398645d1d624538708eeebf96e6fdeb546f5d7<br />-  3f8cf5311b631c5bc395df1e8b9c795358c1ef80<br />-  42cef1e36517ec4c06ef4e9bf5d57be30d287cad<br />-  f2b21097100fc2fc0e84cc34f453c9a85a49a2bb<br />*Stack* <br />Error: Not supported<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L870:8](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/viewModel/splitLinesCollection.ts#L870:8)<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L566:31 (getViewLineMinColumn)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/viewModel/splitLinesCollection.ts#L566:31 (getViewLineMinColumn))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#L335:20 (getViewLineMinColumn)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/viewModel/viewModelImpl.ts#L335:20 (getViewLineMinColumn))<br />[/vs/editor/common/viewLayout/viewLinesViewportData.ts#L98:15 (getLineMinColumn)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/viewLayout/viewLinesViewportData.ts#L98:15 (getLineMinColumn))<br />[/vs/editor/browser/view/viewImpl.ts#L412:21](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/browser/view/viewImpl.ts#L412:21)<br />[/vs/editor/browser/view/viewImpl.ts#L383:29 (_actualRender)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/browser/view/viewImpl.ts#L383:29 (_actualRender))<br />[/vs/editor/browser/view/viewImpl.ts#L590:9 (func)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/browser/view/viewImpl.ts#L590:9 (func))<br />[/vs/editor/browser/view/viewImpl.ts#L383:2 (safeInvokeNoArg)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/browser/view/viewImpl.ts#L383:2 (safeInvokeNoArg))<br />[/vs/editor/browser/view/viewImpl.ts#L239:7 (_renderNow)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/browser/view/viewImpl.ts#L239:7 (_renderNow))<br />[/vs/editor/browser/view/viewImpl.ts#L379:7 (_flushAccumulatedAndRenderNow)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/browser/view/viewImpl.ts#L379:7 (_flushAccumulatedAndRenderNow))<br />

**Comment by alexandrudima** [comment]
Closing in favour of #44805
