### ISSUE TITLE
 Terminal with ID 2 does not exist (has it already been disposed?)

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43736]
Issue Id: <b>0112948f-d962-7d1a-22f1-e7a9da812dcc</b><br /><br />*Versions* <br />- 1.20.0<br />-  f9398645d1d624538708eeebf96e6fdeb546f5d7<br />-  3f8cf5311b631c5bc395df1e8b9c795358c1ef80<br />*Stack* <br />Error: Terminal with ID 2 does not exist (has it already been disposed?)<br />[/vs/workbench/parts/terminal/common/terminalService.ts#L230:9](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/terminal/common/terminalService.ts#L230:9)<br />[/vs/workbench/parts/terminal/common/terminalService.ts#L138:37 (_getIndexFromId)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/terminal/common/terminalService.ts#L138:37 (_getIndexFromId))<br />[/vs/workbench/api/electron-browser/mainThreadTerminalService.ts#L50:46 (getInstanceFromId)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/api/electron-browser/mainThreadTerminalService.ts#L50:46 (getInstanceFromId))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L174:16 (apply)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L174:16 (apply))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L159:27 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L159:27 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L108:39 (_invokeHandler)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L108:39 (_invokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L90:9 (_receiveRequest)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L90:9 (_receiveRequest))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L33:65 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L33:65 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L213:4 (onMessage)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L213:4 (onMessage))<br />[/vs/base/common/event.ts#L142:15 (call)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/event.ts#L142:15 (call))<br />

**Comment by Tyriar** [comment]
This is an error that can occur when extensions try to use an already disposed terminal. It should remain.

**Comment by Tyriar** [comment]
@dbaeumer this could be related to tasks? https://twitter.com/HowFarAmI/status/968159381186600960

**Comment by Tyriar** [comment]
@dbaeumer FYI there was a report of getting this error in tasks https://twitter.com/HowFarAmI/status/968159381186600960, it's not this because particular trace as it's definitely coming via the API.
