### ISSUE TITLE
 Command failed: /usr/local/bin/git -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u}

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43738]
Issue Id: <b>46fce020-a96d-9f4e-e736-6b2ac7148904</b><br /><br />*Versions* <br />- 1.20.0<br />-  7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba<br />*Stack* <br />Error: Command failed: /usr/local/bin/git -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u}<br />fatal: No upstream configured for branch 'master'<br /><br />	at ChildProcess.exithandler (child_process.js:217:12)<br />	at emitTwo (events.js:106:13)<br />	at ChildProcess.emit (events.js:194:7)<br />	at maybeClose (internal/child_process.js:899:16) <no sourcemaps><br />	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) <no sourcemaps><br />

**Comment by joaomoreno** [comment]
@ramya-rao-a Why are we getting telemetry for extensions we do not own?

https://github.com/eamodio/vscode-gitlens/blob/ee14b2f31e9492fcda9d1767fb33a8379f4e7da1/src/git/git.ts#L105

**Comment by ramya-rao-a** [comment]
If there is no stack traces that trace back the error to an extension, then we have no clear way to distinguish core errors from extension errors.

One thing we did was to use a different error handler (the one that does not log any telemetry) in areas where we know that any errors being caught is coming from extensions. For eg: https://github.com/Microsoft/vscode/search?utf8=✓&q=onUnexpectedExternalError&type=

In this case, we need to see where in our code is this error being caught and handle it with the right error handler `onUnexpectedExternalError`
