### ISSUE TITLE
 Unable to write to Workspace Settings because angulardoc.repoId is not a registered configuration.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43734]
Issue Id: <b>6a091882-97c7-ffa5-aec6-348d3a8dd140</b><br /><br />*Versions* <br />- 1.20.0<br />-  3f8cf5311b631c5bc395df1e8b9c795358c1ef80<br />-  7636a7d6f7d2749833f783e94fd3d48d6a1791cb<br />*Stack* <br />Error: Unable to write to Workspace Settings because angulardoc.repoId is not a registered configuration.<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L80:2 (call)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L80:2 (call))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L274:31](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L274:31)<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L383:16 (wrapError)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L383:16 (wrapError))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L152:14 (resolveAndValidate)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L152:14 (resolveAndValidate))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L139:37 (doWriteConfiguration)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L139:37 (doWriteConfiguration))<br />[/vs/base/common/async.ts#L464:32 (factory)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/async.ts#L464:32 (factory))<br />[/vs/base/common/async.ts#L455:8 (consume)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/async.ts#L455:8 (consume))<br />[/vs/base/common/winjs.base.raw.js#L1641:0 (init)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1641:0 (init))<br />[/vs/base/common/async.ts#L447:9](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/async.ts#L447:9)<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L139:20 (queue)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L139:20 (queue))<br />

**Comment by sandy081** [comment]
Error is valid because the setting that is being updated is not registered. Since there is no complete call stack trace I cannot know who is calling this.
