### ISSUE TITLE
 Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43730]
Issue Id: <b>69a3a0cd-ef81-05ed-81db-de348b414b8a</b><br /><br />*Versions* <br />- 1.20.0<br />-  f9398645d1d624538708eeebf96e6fdeb546f5d7<br />*Stack* <br />Error: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L80:2 (call)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L80:2 (call))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L274:31](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L274:31)<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L401:15 (wrapError)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L401:15 (wrapError))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L152:14 (resolveAndValidate)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L152:14 (resolveAndValidate))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L139:37 (doWriteConfiguration)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L139:37 (doWriteConfiguration))<br />[/vs/base/common/async.ts#L464:32 (factory)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/async.ts#L464:32 (factory))<br />[/vs/base/common/async.ts#L455:8 (consume)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/async.ts#L455:8 (consume))<br />[/vs/base/common/winjs.base.raw.js#L1641:0 (init)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1641:0 (init))<br />[/vs/base/common/async.ts#L447:9](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/async.ts#L447:9)<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L139:20 (queue)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L139:20 (queue))<br />

**Comment by sandy081** [comment]
Error thrown here is valid as the user (core/extension) is trying to write into workspace or folder configuration in an empty workspace. Since there is no complete stack trace, I cannot say who is making this request.
