### ISSUE TITLE
BUG VS code problem matcher doesn't scan task output if the task type is "shell"

### ISSUE THREAD

**Issue by mohamed-samir-mohamed** [Microsoft/vscode#43745]
- VSCode Version: 1.20.1
- OS Version: Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Steps to Reproduce:

1.create a task with type "shell"
2.add your problem matcher
3. test your regular expression very well.
4. run task
5. no errors, warnings

example

  {
            "label": "build x",
            "type": "shell",
            "command": "cd xpath && dub build",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher":[ {
                "owner": "Dlang",
                "fileLocation": ["relative", "xpath"],
                "pattern": {
                    "regexp": "(.*)\\((\\d*),(\\d*)\\):(.*):(.*)\\n", //D language problem regex
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }]
        }
info: dub is configured to use dmd compiler which produces errors and warning with first capital letter here is and example output

../../../../.dub/packages/vibe-d-0.7.31/vibe-d/source/vibe/http/server.d(286,33): Deprecation: alias diet.traits.FilterCallback is deprecated - Use SafeFilterCallback instead.
ebs ~master: building configuration "library"...
../../../../.dub/packages/vibe-d-0.7.31/vibe-d/source/vibe/http/server.d(286,33): Deprecation: alias diet.traits.FilterCallback is deprecated - Use SafeFilterCallback instead.
../../lib/ebs/src/ebs/mephisto.d(636,65): Deprecation: vibe.http.common.urlEncode is not visible from module mephisto
../../lib/ebs/src/ebs/mephisto.d(696,61): Deprecation: vibe.http.common.urlEncode is not visible from module mephisto
data ~master: building configuration "library"...
../../../../.dub/packages/vibe-d-0.7.31/vibe-d/source/vibe/http/server.d(286,33): Deprecation: alias diet.traits.FilterCallback is deprecated - Use SafeFilterCallback instead.
cssd 0.1.3: building configuration "library"...
htmld 0.2.18: building configuration "library"...
embaked 0.1.7: building configuration "library"...
plain 0.1.6: building configuration "library"...
vayne ~master: building configuration "library"...
wkhtmltox 0.1.1: building configuration "library"...
writer ~master: building configuration "application"...
src/app.d(3091,21): Error: identifier expected following ., not )
src/app.d(3092,3): Error: found ctx when expecting )
dmd failed with exit code 1.

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by dbaeumer** [comment]
The TypeScript task we ship out of the box is a shell task and problem scanning works without a problem. Can you please provide a GitHub repository I can clone that reproduces your problem. This will allow me to see what you are experiencing.

**Comment by mohamed-samir-mohamed** [comment]
easier for me to debug, I think, would you tell me how can I debug the regex match for a specific problem matcher ?

**Comment by dbaeumer** [comment]
Best would be to build VS Code from source as described here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

You can then start VS Code using scripts/code. The matcher code is in the file: https://github.com/Microsoft/vscode/blob/master/src\vs\platform\markers\common\problemMatcher.ts#L385

**Comment by mohamed-samir-mohamed** [comment]
Ok gotcha, I had to add ^ $ asserts at the begining and the end of my regex in the problem match, now it works pretty well, 
Thanks for your help, I think you can close the issue.

**Comment by dbaeumer** [comment]
Thanks! Closing then.
