### ISSUE TITLE
Cannot access the market place 

### ISSUE THREAD

**Issue by FinderSerg** [Microsoft/vscode#43743]
### Issue Type
Bug

### Description

Unable to install any extension through vs code. Only extension I has is python one and I installed it by cloning git repo it extension folder (Because i really needed it and I can't do it in normal way -_-). Before 1.20 update when I entered extensions tab I get "XHR: field" (or something like this), now in 1.20 I'm getting unknown error.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.4.0-112-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2800)|
|Load (avg)|0, 1, 1|
|Memory (System)|7.71GB (2.49GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.2.0-alpha

</details>
Reproduces without extensions

![image](https://user-images.githubusercontent.com/33636554/36252654-00395a04-124e-11e8-95d0-08e7a73b9745.png)

**Comment by egamma** [comment]
@FinderSerg can you open the developer console when the problem happens and attach what is shown there. To open the console:
- Help>Toggle Developer Tools
- Open the Console tab

**Comment by FinderSerg** [comment]
@egamma 
![screenshot from 2018-02-19 14-17-22](https://user-images.githubusercontent.com/33636554/36377406-be85ccca-157f-11e8-89e0-391926da28bb.png)
![screenshot from 2018-02-19 14-17-44](https://user-images.githubusercontent.com/33636554/36377407-bea7cef6-157f-11e8-8dae-f2154e461c7f.png)

**Comment by egamma** [comment]
Are you behind a proxy? This is the documentation for how access the marketplace when you are behind a proxy https://code.visualstudio.com/docs/setup/network

**Comment by FinderSerg** [comment]
@egamma Ok, I think I get the problem. There is some kind of proxy in network I connected. If I run vs code with `code --ignore-certificate-errors` I don't get this problem. It is strange that it was a problem because right certificates are installed in my OS (maybe it's done not right) and in that manual it said that vs code use them. In any way thanks for help, if I need to install extensions in future I will use that flag. And sorry for my bad English... ^-^

**Comment by egamma** [comment]
@FinderSerg Glad I could help!
