### ISSUE TITLE
Debugger - Watch - Using delete key removes the whole line while editing

### ISSUE THREAD

**Issue by mnp-mid** [Microsoft/vscode#43741]
### Issue Type
Bug

### Description

What works:
- Adding a new line into the watch => ok
- Removing the line from the watch using the del key => ok

Scenario of the issue:
- Adding a new line into the watch
- Use F2 Key or double click into the line using the mouse
- Select some text while in edit mode
   -> With back space => selected text is removed
   -> With del key => ISSUE => the whole line is removed

Expected behavior:
While editing the line from the watch, the del key should behaive like the back space key

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|15.78GB (5.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
tslint|eg2|1.0.26
RunOnSave|eme|0.0.16
json2ts|Gre|0.0.6
vscode-firefox-debug|hbe|1.1.0
team|ms-|1.122.0
debugger-for-chrome|msj|4.1.0
debugger-for-edge|msj|0.4.1
gitflow|vec|1.1.2
gitblame|wad|2.2.0

</details>
Reproduces only with extensions

**Comment by isidorn** [comment]
Fixed in latest vscode insiders, closing as duplicate
