### ISSUE TITLE
Consumo exagerado de memória na versão 1.20.1

### ISSUE THREAD

**Issue by 01viniciusmelo** [Microsoft/vscode#43747]
### Issue Type
Bug

### Description

Consumo exagerado de memória na versão 1.20.1. 
I needed make downgrade for version 1.20

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.4.104-18.44-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2399)|
|Load (avg)|2, 2, 1|
|Memory (System)|5.65GB (0.17GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (98)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
ng-template|Ang|0.1.9
angulardoc-vscode|Ang|3.0.5
vscode-generate-getter-setter|DSK|0.4.2
vscode-markdownlint|Dav|0.13.0
EditorConfig|Edi|0.12.0
vsc-material-theme|Equ|1.3.0
json2ts|Gre|0.0.6
beautify|Hoo|1.3.0
crane|Hvy|0.3.8
output-colorizer|IBM|0.1.2
vscode-simple-icons|Lau|1.8.2
Angular2Tests|Mar|0.7.3
json-to-ts|Mar|1.5.4
Angular-BeastCode|Mik|5.2.13
ng-fortytwo-vscode-extension|NG-|0.0.9
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|3.2.2
simontest|Sim|0.18.1
Angular2|UVB|0.4.1
html-css-class-completion|Zig|1.16.2
html-snippets|abu|0.2.1
vscode-angular2-files|ale|1.3.10
plsql|cas|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
code-sql|cod|0.0.3
sql-formatter|cym|1.0.2
angular2-snippets|dan|1.0.19
vscode-simpler-icons|dav|1.5.2
jshint|dba|0.10.16
vscode-eslint|dba|1.4.5
angular-productivity-pack|dev|1.6.1
angular-extension-pack|dog|1.0.0
jquerysnippets|don|0.0.1
gitlens|eam|8.0.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.27
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.1.3
php-debug|fel|1.12.1
php-intellisense|fel|2.2.8
php-pack|fel|1.0.1
angular-component-file-cycler|for|1.0.2
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
AngularMaterial|har|1.2.0
vscode-firefox-debug|hbe|1.1.0
angular-bootstrap|her|4.0.9
Python-autopep8|him|1.0.2
rest-client|hum|0.17.0
ftp-simple|hum|0.5.8
phpcs|ika|0.7.0
angular2-switcher|inf|0.1.6
vscode-angular2-emmet|jak|2.0.3
docthis|joe|0.6.0
angular-essentials|joh|0.3.2
Angular1|joh|0.2.0
Angular2|joh|2.12.0
markdown-table-formatter|jos|0.2.3
vscode-icon-theme|jtl|1.6.1
refactorix|kri|0.3.6
angular-cli-vscode|lf-|0.0.3
vscode-start-pbiviz|lip|0.6.0
angular-extension-pack|loi|0.5.2
angular1-code-snippets-johnpapastyle|lpe|0.1.0
MagicPython|mag|1.0.12
component-creator|mik|2.0.0
mssql|ms-|1.3.0
python|ms-|2018.1.0
azurecli|ms-|0.4.0
typescript-javascript-grammar|ms-|0.0.31
debugger-for-chrome|msj|4.1.0
sqltools|mtx|0.11.4
angular2-inline|nat|0.0.17
angular-component-extension|oni|0.0.13
angular-cli|pko|1.0.1
vscode-cli|pko|1.0.0
tsimporter|pmn|1.2.14
vscode-css-peek|pra|2.1.0
al-formatter|ras|2.1.0
typescript-hero|rbb|2.2.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
angular-follow-selector|san|1.1.1
angular-gui|sas|0.4.3
vscode-table-formatter|shu|1.2.1
autoimport|ste|1.5.3
move-ts|str|1.10.0
python|tht|0.2.3
ngtvd-extensions|tri|0.0.3
gitblame|wad|2.2.0
bootstrap-3-snippets|wcw|0.1.0
vsc-angular-cli|web|1.0.0
angularclihelper|win|1.0.2
nativescript-ng2-snippets|www|2.0.1
JavaScriptSnippets|xab|1.5.0
plsql-language|xyz|1.1.2

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by egamma** [comment]
Since this only reproduces we need to narrow down which extension is causing this. To narrow down which extension is causing the problem pls see https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled

What also helps if you can run ´code --status´ and attach the output when VS Code is open on the workspace that is causing the problem.
