### ISSUE TITLE
Intellisense propose last snippet used instead of first item in list of suggestions

### ISSUE THREAD

**Issue by qutreson** [Microsoft/vscode#43742]
VSCode Version: 1.21.0
OS Version: Windows 10

Steps to Reproduce:

1. Create two user snippets: A and B
2. Trigger Intellisense. You are now proposed the list: A, B with A selected as it is ordered that way
3. Use the snippet B
4. Trigger Intellisense again. You are proposed with the same list in the same order, but with B as it was the last one you used.

Does this issue occur when all extensions are disabled?: Yes

-----

The problem here is that Intellisense now pre-select the last snippet you have used inside of the list of suggestions. Usually, you return the best suggestions first and you would expect the first item of the list of suggestions to be pre-selected, so that you only press enter and keep on going. This was the previous behavior (version 1.19).

As of now, the ordering that you defined in your extensions is still here, but it is not user friendly anymore since you have now to navigate through the list in order to get the first suggestions. This is kind of breaking the Intellisense experience for users using Snippets when coding.

Thanks,

Quentin

**Comment by jrieken** [comment]
It remember the last selected suggestion, use `"editor.suggestSelection": "first",` to always select the first suggestion.
