### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by cryptojonnyboy** [Microsoft/vscode#43753]
Who can help me out with this little issue? On windows 7
![git](https://user-images.githubusercontent.com/35565338/36257609-e1d5d4d4-1257-11e8-9199-93c39e5892ea.JPG)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Is there something which doesn't work? Those messages are expected.
