### ISSUE TITLE
Search is only searching open files

### ISSUE THREAD

**Issue by stevenhay** [Microsoft/vscode#43758]
### Issue Type
Bug

### Description

Searching is only searching files I currently have open and not all files in directories and child directories.
![issue1](https://user-images.githubusercontent.com/26744309/36259935-c71ae0f8-1257-11e8-84a4-c6a1a46fdbb0.PNG)

![issue2](https://user-images.githubusercontent.com/26744309/36259937-c74e24c2-1257-11e8-80fc-80d59f146e63.PNG)

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T05:17:01.988Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2492)|
|Memory (System)|7.89GB (2.50GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.4.0
vscode-eslint|dba|1.4.5
githistory|don|0.4.0
gitlens|eam|8.0.0
vscode-html-css|ecm|0.2.0
RelativePath|jak|1.3.0
csharpextensions|jch|1.3.0
vscode-cfml|Kam|0.3.1
mssql|ms-|1.3.0
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
vscode-code-outline|pat|0.0.12
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
partial-diff|ryu|0.5.1
code-settings-sync|Sha|2.8.7
vscode-gitmoji-snippets|thi|3.2.0
gitflow|vec|1.1.2
vscode-open-in-github|ziy|1.3.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by MikeMatusz** [comment]
This seems to also affect Ctrl+P navigation, auto-import, and various other functionality that relies on being able to see other files in the source tree.

**Comment by roblourens** [comment]
Does this happen for all folders or just this one you've opened?

Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by roblourens** [comment]
I found the likely issue, please try again tomorrow.

**Comment by stevenhay** [comment]
Can confirm this is fixed. Thanks!
