### ISSUE TITLE
SCM: Add empty line between last repository and current repository section

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#43751]
### Issue Type
Feature Request

### Description

Maybe this is just me, but I have a hard time to immediately spot the current repository's section header. Could we try adding like an empty line between the below "vscode-internalbacklog" and the section header "VSCODE". It's not that I can't distinguish these, but I have to look twice and that break my flow of interactions.

![image](https://user-images.githubusercontent.com/9205389/36255229-74de8564-124e-11e8-96ba-76fb1fd0e599.png)

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T06:08:32.814Z)
OS version: Darwin x64 16.7.0

**Comment by joaomoreno** [comment]
Closing as won't fix.
