### ISSUE TITLE
Windows: Code.exe stays stuck

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#43756]
In inno update log is attached [vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1727821/vscode-inno-updater.log)

The reason for the failure according the log is that insiders.exe could not be terminated. When I install insiders again then I get the same error and when say continue the install fails. I even fail to terminate Insiders (actually the extension host process) manually from the task manager (see below).
![image](https://user-images.githubusercontent.com/172399/36259617-0757c51c-125f-11e8-847d-f89d2cda19ef.png)

![image](https://user-images.githubusercontent.com/172399/36259860-dc85ec0a-125f-11e8-80df-bc5005e5d8f5.png)

![image](https://user-images.githubusercontent.com/172399/36259978-46e50914-1260-11e8-8440-9e95651beda8.png)

The background update worked today so the failure isn´t consistent.

**Comment by joaomoreno** [comment]
The failure isn't related to the background update. It's related to the process ending up in that _stuck_ state. Any update/install/uninstall would fail. So we have to figure out why is the process stuck.

**Comment by alexandrudima** [comment]
I have seen this exact same behaviour a few months back when Electron was crashing on each exit on Windows.

My understanding of the situation from a few months back:
- The installer will cause the running exe to shutdown/quit itself.
- The process would crash (there was an Electron bug).
- Windows kicks in and (for whatever reason) decides to create a memory dump or a crash stack or something...
- Windows miserably fails... or something... and the process explorer shows this process and you cannot kill it.

In fact, I think it got a popular name, "zombie process". The only way out AFAIK is a system restart.

**Comment by joaomoreno** [comment]
Seems obsolete.
