### ISSUE TITLE
Slow startup 

### ISSUE THREAD

**Issue by ashwinr63** [Microsoft/vscode#43759]
[487b-exthost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1727899/487b-exthost.cpuprofile.txt)
[487b-main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1727900/487b-main.cpuprofile.txt)
[Uploading 487b-renderer.cpuprofile.txt…]()

- VSCode Version: <code>Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)</code>
- OS Version: <code>Windows_NT x64 10.0.16299</code>
- CPUs: <code>Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)</code>
- Memory (System): <code>7.84GB (3.67GB free)</code>
- Memory (Process): <code>178.01MB working set (183.52MB peak, 160.57MB private, 46.70MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|38|
|main|app.isReady => window.loadUrl()|420|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|522|
|renderer|require(workbench.main.js)|1761|
|renderer|create extension host => extensions onReady()|1578|
|renderer|restore viewlet|0|
|renderer|restore editor view state|644|
|renderer|overall workbench load|922|
|main + renderer|start => extensions ready|4377|
|main + renderer|start => workbench ready|3693|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`487b-exthost.cpuprofile.txt`
-`487b-main.cpuprofile.txt`
-`487b-renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Nothing special here... Loading and scanning extensions was kind slow (and we have added caching ever since).
