### ISSUE TITLE
onDidStartDebugSession can fire without onDidTerminateDebugSession firing later

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43752]
I think this may be deliberate (#29666) but it feels wonky.

I have a class that subscribes to `onDidStartDebugSession` and also `onDidTerminateDebugSession`. If a debug session fails to start, the first is called but the second is not. This means if I set something up (like a status bar, progress indicator, whatever) it gets left around if the debugger didn't start.

It feels like I shouldn't need to start leaking code out elsewhere to try and tidy this up, it feels like these two commands should go together (or at least, we should have some similar event we can rely on to fire when a debugging session ends for whatever reason).

**Comment by isidorn** [comment]
Makes sense to me. Try it out in tomorrows insiders and let us know how it goes
@roblourens fyi

**Comment by DanTup** [comment]
LGTM in insiders 👍

**Comment by isidorn** [comment]
@DanTup thanks, adding verified label
