### ISSUE TITLE
workspace.findfiles behaviour changes

### ISSUE THREAD

**Issue by keyoke** [Microsoft/vscode#43757]
- VSCode Version: 1.20.0
- OS Version: Win 10 16299.248

Steps to Reproduce:

1. Install vscode 1.19.X
2. Install vscode-arduino 0.2.10
3. CTRL+SHIFT+ P
4. select "Arduino: Board Manager"
5. Board Manager opens fine no errors
5. Update vscode 1.20.0
3. CTRL+SHIFT+ P
4. select "Arduino: Board Manager"
5. Error "Cannot read property 'map' of undefined" is shown and board manager UI not shown

I have debugged this issue and found that the following line behaves differently now, the promise is now Rejected... whereas before I think it would return 0 files.. is this now by design?

return vscode.workspace.findFiles(ARDUINO_CONFIG_FILE, null, 1)
..
https://github.com/Microsoft/vscode-arduino/blob/0122379e263a1fcb626169dfdeac9faff4515631/src/deviceContext.ts#L125

issue also open here
https://github.com/Microsoft/vscode-arduino/issues/462

**Comment by roblourens** [comment]
Does this still repro? I'm not aware of any issues with findFiles, and a lot of code has changed in this area.
