### ISSUE TITLE
XText LSP implementation behaves differently in Eclipse Che and VS Code

### ISSUE THREAD

**Issue by xcariba** [Microsoft/vscode#43762]
### Issue Type
Bug

### Description

I`m using XText LSP implementation. When I create content assist proposals with multiline insertText content VSCode adds extra indentations even with autoIndent (and other inent-related options) turned off.

Steps to reproduce (YAML):
- Create file, containing something like
```
mapping:
    key: <|>
```
where `<|>` is a mark, where content assist was called (4 spaces indent)
- Create ContentAssistEntry with insertText like `value: \n      -\n        ` (6 and 8 spaces)
- VScode will insert  `value: \n          -\n            ` (10 and 12 spaces)

Same LSP server works fine in Eclipse Che, it inserts original proposal without extra spaces.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.14.16-300.fc27.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3695)|
|Load (avg)|1, 0, 0|
|Memory (System)|31.29GB (0.45GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/language-server-protocol/issues/83
