### ISSUE TITLE
HTML formatter added breaks and whitespace to text inside P tags

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#43769]
### Issue Type
Bug

### Description

When presented with code like this:
````
  <h1>Overview</h1>
        <div class="doc-text-block">
          <p>Prior to the Design System, our products were developed using varying and competing technologies. This led to longer
            implementation timelines, difficulty in making changes, and locking value within products. Our products became
            dated, inconsistent and difficult for users to interact with.</p>

          <p>To remedy this, in 2013 we introducted a technology stack utilizing best of breed, open-source technology. Since
            then, dozens of products have been built using this technology stack and the Design Syste mand have benefited
            from shorter development times and a consistent look and feel.</p>

          <p>The web development technology world has evolved since the intoduction of the original technology stack. The libraries,
            tools, and even browsers have become more advanced in many ways, enabling features and speed unimaginable even
            five years ago. Therefore, with the release of Design System 5.0 we are introducing an updated Technology Stack.</p>
        </div>
````

Applying "format html" adds breaks apparently for no reason:

![36209056-ab1295b2-1168-11e8-9cd7-8ec31adca941](https://user-images.githubusercontent.com/835148/36268877-adb125da-1245-11e8-910d-a2654c691733.gif)

I tested the block of code on http://jsbeautifier.org (set to 120 character line length) and it does not do this:

<img width="1103" alt="screen shot 2018-02-15 at 11 41 39 am" src="https://user-images.githubusercontent.com/835148/36268916-ccc7229e-1245-11e8-8d5c-459261a2408b.png">

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T06:08:32.814Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.98GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_962795|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.7
sort-lines|Tyr|1.4.1
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.1
project-manager|ale|0.24.0
vscode-eslint|dba|1.4.5
tslint|eg2|1.0.27
prettier-vscode|esb|1.1.3
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.8.1
vscode-text-pastry|jkj|1.2.0
Angular2|joh|2.12.0
vscode-icon-theme|jtl|1.6.1
ecdc|mit|0.11.0
HTMLHint|mka|0.4.0
vscode-scss|mrm|0.6.2
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
stylelint|shi|0.32.0
Align|ste|0.2.0
bootstrap4-vscode|the|4.0.0
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by aeschli** [comment]
Reproduces only with extensions? In that case, can you find out which extension this is and file the bug against the extensions?

I'm not able to reproduce the bug with the sample above and the default html settings. If it's not with an extension, can you provide your html settings?

**Comment by smlombardi** [comment]
That's a mistake, sorry.  I did not test with no extensions.  I only tested with my standard extensions on.  It's been this way as long as I can remember.

**Comment by aeschli** [comment]
So does it reproduce with all extensions disabled?
I ask because I'm not able to reproduce, also not with your settings.

**Comment by smlombardi** [comment]
Yes, it happens even if I disable all installed extensions, and if I create a new, standalone file with only this in it, set to "html" type

```
<h1>Overview</h1>
<div class="doc-text-block">
  <p>Prior to the Design System, our products were developed using varying and competing technologies. This led to longer implementation
    timelines, difficulty in making changes, and locking value within products. Our products became dated, inconsistent and
    difficult for users to interact with.</p>

  <p>To remedy this, in 2013 we introducted a technology stack utilizing best of breed, open-source technology. Since then,
    dozens of products have been built using this technology stack and the Design Syste mand have benefited from shorter
    development times and a consistent look and feel.</p>

  <p>The web development technology world has evolved since the intoduction of the original technology stack. The libraries,
    tools, and even browsers have become more advanced in many ways, enabling features and speed unimaginable even five years
    ago. Therefore, with the release of Design System 5.0 we are introducing an updated Technology Stack.</p>
</div>
```
![feb-16-2018 09-32-18](https://user-images.githubusercontent.com/835148/36312437-8479851a-12fc-11e8-89c2-91c8b8a141d1.gif)

**Comment by aeschli** [comment]
@smlombardi Can you turn on all the line number? Maybe this is the editor wrapping?

**Comment by smlombardi** [comment]
Here's what I did:

1. Paste the above code into a new window.  It breaks funny (probably because I have "format on paste" on)
2. Select each `<p></p>` block.  Choose "join lines",
3. Check they are joined by resizing window. They flow as expected.
4. Choose "format code".  They break strangely.

![feb-16-2018 10-26-24](https://user-images.githubusercontent.com/835148/36314897-373ee60c-1304-11e8-8c04-01a419c9ea7a.gif)

**Comment by aeschli** [comment]
You can see that the funnyness comes from the two different word warping implementations:
- The formatter wraps at 120 chars (VSCode default settings), but it seems to measure from the first word on the line (ignores leading whitespace) and doesn't mind to allowing some extra characters.
- I configured the editor to wrap at 120 as well, but it measures from the beginning of the line.

![image](https://user-images.githubusercontent.com/6461412/36317247-e4610f08-133c-11e8-9246-34405ace4428.png)

I don't think there is a real bug here, but feel free file an issue against http://jsbeautifier.org to rework their wrapping strategy.

**Comment by aeschli** [comment]
To verify that the formatter works ok, I'd suggest to turn off the editor wrapping.
Except from beeing a but generous on the line lengths, I don't see any whitespaces added at places where it shouldn't.
