### ISSUE TITLE
Switching to inline diff view gives bad scrollbar position

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#4376]
Use the following settings. It is important to use a larger font size such that the line numbers overall width must be large:
```
, "editor.fontFamily": "Hack"
, "editor.renderWhitespace": true
, "editor.fontSize": 16
, "editor.lineHeight": 22
```

Open diff side-by-side. Switch to inline. Observe, the scrollbar is not possitioned OK:

![diff-inline](https://cloud.githubusercontent.com/assets/5047891/13852841/4edf0e68-ec64-11e5-91d9-33180edd7291.gif)

**Comment by bpasero** [comment]
If the goal is to keep the top line number stable, I still see it jumping. Note that I do not have Hack installed on my system but I took your settings:

![untitled](https://cloud.githubusercontent.com/assets/900690/13919807/e78b3156-ef6f-11e5-9619-e1ffe239d592.gif)

The file opened in diff is fileActions.ts converted to spaces.

**Comment by alexandrudima** [comment]
@bpasero That is not the goal.

The bug was that the scrollbar was not visible until a resize event ("Observe, the scrollbar is not possitioned OK:").
