### ISSUE TITLE
Format Document

### ISSUE THREAD

**Issue by MyTechSite** [Microsoft/vscode#43767]
- 1.20.1
- Windows 10 1709 Latest all updates:

Steps to Reproduce:

1. Load any C or C++ file and Right Click anywhere and you get "Format Document"  Option.  No problems and it works very well.
2.  Do the same but load or create any C# file, you don't get an option to Format the document.

Any ideas when will this be implemented?

Some people like to create console Applications using VS Code but also like to Format the document for embed the code in a website.

Thank you.

Does this issue occur when all extensions are disabled?: Yes/No

Probably but haven't tried it as I doubt if this is going to make any difference.

**Comment by egamma** [comment]
Please file the request against the C# extension https://github.com/OmniSharp/omnisharp-vscode
