### ISSUE TITLE
Commit commits the whole file, not only selected ranges

### ISSUE THREAD

**Issue by LAITONEN** [Microsoft/vscode#43765]
- VSCode Version: 1.20.0
- OS Version: Sierra 10.12.6

Steps to Reproduce:

1. Make some changes to different files of your code.
2. Add all changes from one file for commit. 
3. Use stage selected ranges to add only some lines of code of another file for commit.
4. Commit.
5. See that the whole file, from which you selected only certain scopes, got committed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
cc @chrmarti for bad bot suggestions

**Comment by joaomoreno** [comment]
@LAITONEN Do you mind sending a screen recording of what you observe?

**Comment by niklas-e** [comment]
This has happened a few times. I'm not sure how to repro as it seems to happen quite randomly. Though I think it's usually occurring when I have to select ranges from multiple sections.

I have also noticed after it has happened and I'm trying to undo the commit and then retry the range selection process, it occurs again. So basically I cannot do the range selection at all when this has occurred.

OS Version: Windows 10 Pro, 1709 (16299.248)
VSCode version: 1.20.0

**Comment by joaomoreno** [comment]
@niklas-e Since it reproduces afterwards, can you record a screencast and show me?

**Comment by niklas-e** [comment]
@joaomoreno sure thing, I'll try to remember to record it next time.

**Comment by SamiEklund** [comment]
In my case this issue was caused by [lint-staged ](https://github.com/okonet/lint-staged). More information about that issue can be found here: https://github.com/okonet/lint-staged/issues/62#issuecomment-359234601

**Comment by LAITONEN** [comment]
Solution of @SamiEklund works. I am closing the issue. Thank you all!

**Comment by LAITONEN** [comment]
Solution of @SamiEklund works. I am closing the issue. Thank you all!

**Comment by joaomoreno** [comment]
Excellent, thank you!
