### ISSUE TITLE
[theming] Make contrastActiveBorder around text optional/themeable

### ISSUE THREAD

**Issue by mbenkmann** [Microsoft/vscode#43761]
- VSCode Version: 1.20.1
- OS Version: Linux

I like contrastActiveBorder and think it is very useful around UI elements such as buttons, list elements, active tabs etc.
However around text in the editor I think it is extremely counterproductive. It makes things harder to read. I find the borders around text so unbearable that I set contrastActiveBorder to transparent because I would rather lose all the benefits than deal with this (after all, I stare at text all day). It would be way more useful to expand the selectionForeground feature to more parts, so that e.g. Find locations (such as the one in the screenshot below) could be made more visible that way. A more general approach that would not require themeing would be to either invert the colors or swap background/foreground similar to what terminals do.

Anyway, until a better solution is implemented I would like to see an independent "contrastActiveTextBorder" color that is used around editor text. It can fall back to contrastActiveBorder so that backwards compatibility would be maintained (for whatever weird person finds this useful), but themes could independently set it to transparent to make it disappear while keeping the contrastActiveBorder around UI elements.

![Image of contrastActiveBorder around a word](http://winterdrache.de/data/contrastActiveBorderAroundWord.png)

**Comment by aeschli** [comment]
I added a new color id 'editor.rangeHighlightBorder' that controls the border color you mention.
No change of out-of-the box behaviour. It's only set in highContrast and it is the contrastActiveBorder color by default (you can change it...)

**Comment by mbenkmann** [comment]
The name seems suboptimal as it sounds similar to editor.findRangeHighlightBackground and would suggest it only affects the same text. We're talking about at least 3 things here whose background colors are  editor.findMatchBackground, editor.findMatchHighlightBackground and editor.findRangeHighlightBackground.
If individual border colors were created for all 3, then there would be an editor.findRangeHighlightBorder which sounds very similar to your name. If indeed your new color affects all 3, it should have a more generic name (such as editor.contrastActiveTexBorder).

**Comment by mbenkmann** [comment]
Just to make sure we're on the same page. Aside from the findRange... there are other occurrences, such as peekViewResult.*
So prefixing the name with "editor." would not be wise. I think my original suggestion contrastActiveTextBorder would work really well as a generic name and it would be easy to notice in the suggestions box while editing the user settings, because it would pop up while you're entering "contrastActive..." to set the contrastActiveBorder.

**Comment by aeschli** [comment]
Good point, there are more uses of `contrastActiveBorder` that I missed. I added more border settings as having border settings for the decorations was a request from others as well.

Agree that `range highlight` and 'findRange highlight' 'findMatchRange highlight' might be confusing, but I want to stick with the terminology that we started.

**Comment by mbenkmann** [comment]
The border around the identifier name in "Peek Definition" is still not themeable.
