### ISSUE TITLE
"this" not reflecting inheritance for static methods

### ISSUE THREAD

**Issue by benjaminmillhouse** [Microsoft/vscode#43764]
- VSCode Version: 1.20.1
- OS Version: OSX 10.13.3

Steps to Reproduce:

1. Create a class with a static method on it that returns "this"
2. Create a class that inherits from the previous class
3. Check the IntelliSense on the inherited class when calling the static method
    3a. IntelliSense shows the returned value as the base class rather than the inherited class
    3b. When following this same flow for an instance method IntelliSense correctly shows the returned   
value as the inherited class

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
@benjaminmillhouse please provide a snippet that illustrates the problem and also mention what language you are using when the problem happens.

**Comment by andy-ms** [comment]
```ts
class C {
    static m() {
        return this;
    }
}
class D extends C {
    static n() {}
}
D.m().n(); // Works at runtime, fails in TS
```

**Comment by benjaminmillhouse** [comment]
Sorry - the language is JavaScript.
Here is some example code:
```javascript
class SomeClass {
    static returnThis() { return this; }
    returnThis() { return this; }
}

class SomeOtherClass { }

SomeClass.returnThis() // IntelliSense detects the returned type as the SomeClass constructor
SomeOtherClass.returnThis() // IntelliSense still detects the returned type as the SomeClass constructor

new SomeClass().returnThis() // IntelliSense detects the returned type as a SomeClass instance
new SomeOtherClass().returnThis() // IntelliSense detects the returned type as a SomeOtherClass instance
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22000
