### ISSUE TITLE
'Split Vertically' on context menu actually splits horizontally

### ISSUE THREAD

**Issue by rfoust** [Microsoft/vscode#43760]
- VSCode Version: Version 1.21.0-insider (1.21.0-insider)
- OS Version: MacOS High Sierra 10.13.3

Steps to Reproduce:

1. Right click on the Terminal window
2. Context menu says "Split Vertically"
3. It actually creates a new terminal window to the right, not the top/bottom. This is also true if the terminal window is docked on the right side.

Does this issue occur when all extensions are disabled?: Yes/No
Haven't tried that yet.

**Comment by usernamehw** [comment]
That's kind of how it works in other software, isn't it?
![7a5tp](https://user-images.githubusercontent.com/9638156/36261773-85be3474-1276-11e8-88ce-8018f75b103e.png)

**Comment by rfoust** [comment]
Oh, I see what you mean.  Just didn't make sense in my head since the window was created horizontally to the right.  Semantics I suppose...

**Comment by rfoust** [comment]
Since this probably isn't a bug, I'll close this issue.
