### ISSUE TITLE
explorer.openEditors.visible is 0, but shows "Open Editors" list header when first opening directory

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#43766]
### Issue Type
Bug

### Description

To reproduce:
* Set vscode settings to `{ "explorer.openEditors.visible": 0 }` and close.
* `mdir temp; cd temp; code-insiders .`
* You will see "Open Editors" in the explorer menu, even though you asked not to see this. (It still shows a maximum of 0 though, so just the title appears.)
Does not reproduce in vscode non-insiders.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (4d122017332a1ed12e083d79f85a054ac3f32fcf, 2018-02-13T05:16:56.295Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|Memory (System)|15.91GB (6.23GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe .|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by andy-ms** [comment]
@isidorn Could you link to the issue this is a duplicate of?

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/43597

**Comment by andy-ms** [comment]
Thanks
