### ISSUE TITLE
Searchable Source Control

### ISSUE THREAD

**Issue by cwpetrich** [microsoft/vscode#43771]
### Issue Type
Feature Request

### Description

Able to search through files in the Source Control menu to look for specific files. 

![image](https://user-images.githubusercontent.com/6043021/36269347-2fb00bec-1236-11e8-984c-ea8e96879a48.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

**Comment by AttilaSATAN** [comment]
:+1:

**Comment by jrieken** [comment]
Thanks to @joaomoreno this will ship in the September release.
