### ISSUE TITLE
"new" Keyword suggestion only working on non-generic class

### ISSUE THREAD

**Issue by PotterDai** [Microsoft/vscode#43779]
- VSCode Version: 1.20.1
- OS Version: MacOS Sierra

Steps to Reproduce:

1. `List<string> l = new `  -> suggest "string" instead of "List<string>()"
2. `TestClass tc = new ` -> suggest "TestClass" as expected

So "new" keyword suggestion only works on non-generic class

**Comment by sean-mcmanus** [comment]
What language/extension is this for?

**Comment by PotterDai** [comment]
@sean-mcmanus You are right! Close it here.
