### ISSUE TITLE
VSCode on Ubuntu 16.04 docker having very weird key bindings

### ISSUE THREAD

**Issue by KasperJanssens** [Microsoft/vscode#43772]
- VSCode Version:
1.19.1
- OS Version:
Ubuntu 16.04 (Docker)
Steps to Reproduce:

1. Launch vscode with 'code .'
2. No plugins installed,  nothing changed but apparently 'e' is backspace, r is 'go right' and 's' is delete line. I have no idea where this keymap comes from, nor did I select it, nor do I find the config back in the keymap.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by egamma** [comment]
For keybinding related issues please follow this guide https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

**Comment by KasperJanssens** [comment]
Okay, I did not see those, thanks for the quick answer. And btw, the "keyboard.dispatch": "keyCode" helped me out.
