### ISSUE TITLE
Git multi select and stage is broken

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#43787]
### Issue Type
Bug

### Description

This is working in 1.19.3 but not 1.20.1.

@isidorn Don't know if it's due to the multi-select update on Viewlets or some changes in git. Giving to you first anyway.

![bug](https://user-images.githubusercontent.com/4033249/36285019-de0ef946-125e-11e8-8b3a-d7fc282c6691.gif)

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T06:08:32.814Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_5334294|
|Screen Reader|no|
|VM|18%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.3.0
tslint|eg2|1.0.27
prettier-vscode|esb|1.1.3
vscode-slm|mrm|1.1.0
PowerShell|ms-|1.5.1
vetur|oct|0.11.7
vim|vsc|0.10.13

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
Nope, this is not list specific as it works nicely in the open editors. Forwarding to @joaomoreno 
I can repro

**Comment by joaomoreno** [comment]
@bpasero @isidorn I did not touch this code since a long time. Care to check what your refactorings might have done here?

**Comment by isidorn** [comment]
@joaomoreno this issue is older than my change in the list so probably @bpasero changes broke this.
I can also investigate if you are out of cycles @bpasero

**Comment by bpasero** [comment]
It actually only reproduces sporadically for me...

**Comment by bpasero** [comment]
This was because of `options.selectOnMouseDown: true`, the right click would select and open the element under the mouse. I am now checking for right-click before doing that because that should not be a button to use for opening/selecting.
