### ISSUE TITLE
Omnisharp/Intellisense outputs error "The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)" but dotnet cli's build command working well

### ISSUE THREAD

**Issue by everton-santos** [Microsoft/vscode#43789]
### Issue Type
Bug

### Description

main project generated by dotnet new webapi
add project dependencies to main project with <ProjectReference Include="..\path-to-dependency\project.csproj" />
using vscode workspaces

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.52GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_3150593|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vs-code-xml-format|fab|0.1.5
csharp|ms-|1.14.0
vs-keybindings|ms-|0.1.7

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
Since this is a problem with an extension, please file this on the extension itself: https://github.com/OmniSharp/omnisharp-vscode
