### ISSUE TITLE
Reliably unreliable npm install behavior when vscode is open due to system filehandle limits

### ISSUE THREAD

**Issue by breathe** [Microsoft/vscode#43785]
### Issue Type
Bug

### Description

I'm observing reliably unreliable npm install behavior when VSCode is open.

Steps to reproduce:

0. open vscode: `code .`
1. rm -rf node_modules
2. npm install
3. Various different incarnations of errors due to file handle limits being hit ...

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|2, 4, 3|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.0.17
quokka-vscode|Wal|1.0.102
wallaby-vscode|Wal|1.0.76
project-manager|ale|0.24.0
npm-intellisense|chr|1.3.0
regex|chr|0.1.0
vscode-eslint|dba|1.4.5
jupyter|don|1.1.4
gitlens|eam|8.0.0
tslint|eg2|1.0.27
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.1.3
path-autocomplete|ion|1.8.1
search-node-modules|jas|1.2.0
vscode-styled-components|jpo|0.0.15
vscode-regexp-preivew|le0|0.0.3
python|ms-|2018.1.0
cpptools|ms-|0.14.6
debugger-for-chrome|msj|4.1.0
advanced-new-file|pat|1.1.0
vscode-versionlens|pfl|0.19.1
gitlink|qez|0.4.2
vscode-import-cost|wix|2.6.2

</details>
Reproduces without extensions

**Comment by egamma** [comment]
@breathe can include the error message that shows up?

Does this help https://code.visualstudio.com/docs/setup/linux#_error-enospc?

**Comment by breathe** [comment]
Hi @egamma — the errors manifest in different ways depending on when the system filehandle limits get hit.

I’ve seen ENFILE errors reported by node file system APIs, and I’ve seen shell commands invoked by package install scripts fail in weird places ...  I’m not really sure if this is a vscode bug or more of an npm bug — I’m actually not sure how I should expect vscode to behave when I rapidly remove and recreate the node_modules/ directory — particularly when I have extensions configured to use resources that can be found in there ...

Would there be any reason to think that symlinks might be contributing to or causing this issue?  My workspace uses symlinks as described in this issue (https://github.com/serverless/serverless/issues/4124) as a way to workaround difficulties with the serverless framework — so I do have a bunch of symlinks to the root node_modules directory within my source tree — and I wonder if that might confuse a special case treatment of node_modules/ that might exist in vscode ...?

**Comment by bpasero** [comment]
@breathe where do you see these errors? can you attach a video or screenshot?

**Comment by breathe** [comment]
It’s in the ‘npm install’ run from within my external iterm2 instance ...  I’ll try to report back with some screenshots or videos during the week.

**Comment by bpasero** [comment]
@breathe any luck?
