### ISSUE TITLE
Indentation in jsdoc comments

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#43783]
### Issue Type
Bug

### Description

1. create a `js` file with the following content
```js
/** */
function m() {}
```
2. Place caret right before the closing `*` in the jsdoc comment
3. Press Enter
-> 
```js
/** 
 * 
*/
``` 
is entered. When I place the caret after the second opening `*` I get the right indentation.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T06:08:32.814Z)
OS version: Darwin x64 16.7.0

Reproduces without extensions

**Comment by mjbvz** [comment]
@rebornix I took a look at this but couldn't get it working properly. You know way more about indention rules so let's take a look together sometime
