### ISSUE TITLE
Pressing the del key while editing removes the whole entry

### ISSUE THREAD

**Issue by LordHog** [Microsoft/vscode#43780]
While editing a watch entry then pressing the del key would remove the entry. I don't believe this should be the case as it should delete a character and not the whole entry. After the entry is remove all the other entries remain in a darken state until double click on another entry

![36184592-9ad9eb8e-10e9-11e8-9b0e-7f29931fa0bb](https://user-images.githubusercontent.com/970098/36279399-deed2396-124b-11e8-844d-4dc514e6c4e6.gif)

VSC: 1.20.1 (was also seen in 1.19.x, probably before though I can't recall)

**Comment by isidorn** [comment]
Fixrd in insiders.
Closing as duplicate
