### ISSUE TITLE
Starting VSCode --help doesn't produce output

### ISSUE THREAD

**Issue by RoscoP** [Microsoft/vscode#43786]
### Issue Type
Bug

### Description

Starting VSCode from powershell with --help doesn't produce any output to the powershell window or open a window with help instructions.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T05:17:01.988Z)
OS version: Windows_NT x64 10

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) @ 2.70GHz|
|Memory (System)|31.88GB|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe --help --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled
Reproduces without extensions

**Comment by egamma** [comment]
Cannot reproduce in my Windows setup
![image](https://user-images.githubusercontent.com/172399/36297664-47188b10-12f4-11e8-8de1-018e4e20db3b.png)

**Comment by RoscoP** [comment]
I was running the exe `Program Files\Microsoft VS Code Insiders\Code - Insiders.exe` - running `...\bin\code-insiders.exe` works.
