### ISSUE TITLE
Search in files doesn't work

### ISSUE THREAD

**Issue by fr500** [Microsoft/vscode#43799]
### Issue Type
Bug

### Description

Since the update last night, I can't search in files within the tree, I press control-shift f, type a string and no results

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T05:17:01.988Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3300)|
|Memory (System)|15.97GB (8.64GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-auto-open-markdown-preview|hnw|0.0.4
tabsanity|jed|0.0.9
cpptools|ms-|0.15.0
trailing-spaces|sha|0.2.11
shell-launcher|Tyr|0.1.6
sort-lines|Tyr|1.4.1
debug|web|0.21.2
TabSpacer|yui|1.0.2

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Should be fixed tomorrow. https://github.com/Microsoft/vscode/issues/43758
