### ISSUE TITLE
Editing JSON, why are some key/value pairs grey?

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/vscode#43796]
### Issue Type
![2018-02-15_20-52-01](https://user-images.githubusercontent.com/12263288/36290440-3609efdc-1293-11e8-84e1-8015b793b01b.png)

Question

### Description

When editing launch.json, I noticed that some key/value pairs are grey.  Most other keys are blue.  What does grey mean?

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       Q 740  @ 1.73GHz (8 x 1729)|
|Memory (System)|7.94GB (1.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Auth
---|---|---
code-runner|for|0.8.7
mssql|ms-|1.3.0
python|ms-|2018.1.0
csharp|ms-|1.14.0
PowerShell|ms-|1.5.1
vscode-autohotkey|sle|0.2.2

</details>
Reproduces without extensions

**Comment by rohmanhm** [comment]
I think required object key.
But I'm not sure 😬

**Comment by egamma** [comment]
These attributes are de-emphasized since the user doesn´t need to change them when customizing a launch configuration.
