### ISSUE TITLE
Cannot disable search exclusion induced by .gitignore.

### ISSUE THREAD

**Issue by Kaba2** [Microsoft/vscode#43795]
### Issue Type
Bug

### Description

Suppose .gitignore has the line "node_modules". Then all directories which mention node_modules is automatically excluded from search results. I have a project-specific directory project/node_modules, which contains our source-code. The line from .gitignore causes this directory also to be excluded from searches. Since I do not want it to be excluded from searches, I go to Workspace Settings, and define 
   {
      "search.exclude": {
     		"**/node_modules": false,
		"./node_modules": true
	}
   }

While these settings are succesful without the .gitignore file, with .gitignore this does not disable the exclusion.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz (4 x 2208)|
|Memory (System)|15.85GB (7.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by roblourens** [comment]
You can disable this in general by setting `"search.useIgnoreFiles": false`, or for a specific search with the "Use Excludes and Ignore Files" button (bottom right)
![image](https://user-images.githubusercontent.com/323878/35752446-e01ea914-0810-11e8-8d1e-9877a751c5ca.png)

**Comment by Kaba2** [comment]
These help by providing workarounds; thanks for those! However, if I want to keep the general idea of using ignore files, then the bug I am reporting is that I don't have fine control over the exclusion, in contrast to what I have without ignore files.

**Comment by Kaba2** [comment]
To be explicit, I'd expect the "search.exclude" setting to take priority over the exclusion in ignore files. This means that I except to be set "project/node_modules": false, say, to include a directory in searches, despite it being excluded in .gitignore.

**Comment by roblourens** [comment]
I understand, but there isn't really an easy way for us to make that work.
