### ISSUE TITLE
[Insider] "Go to File..." only shows recently opened file

### ISSUE THREAD

**Issue by Zooce** [Microsoft/vscode#43790]
"Go to File..." only shows recently open files.

Version 1.21.0-insider
Commit 70e020b2377f12894ca11254548ce365a0e435f1
Date 2018-02-15T05:17:01.988Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Windows 7 x64

Steps to Reproduce:

1. Open a fairly large project
2. Try to open a file with `Go > Go to File...`
3. Type the name of a file that is not in the "recently opened" section of the command palette
4. Notice the resulting "No results found"

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please try again in the next insiders version. Probably https://github.com/Microsoft/vscode/commit/936b796aa8667de5edb536b00ce8a8e61fcebfb6

**Comment by stevenhay** [comment]
This is working for me on the latest build.

Version 1.21.0-insider
Commit 936b796aa8667de5edb536b00ce8a8e61fcebfb6
Date 2018-02-16T05:15:47.029Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Zooce** [comment]
**Works!** Thank you.

Version 1.21.0-insider
Commit 936b796aa8667de5edb536b00ce8a8e61fcebfb6
Date 2018-02-16T05:15:47.029Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
