### ISSUE TITLE
Upgrade on MacOS not working

### ISSUE THREAD

**Issue by andrewssi** [Microsoft/vscode#43793]
- VSCode Version: 1.19.3
- OS Version: Mac OS 10.13.3
- Steps to Reproduce:

Run 'Check for updates' from 'Code' menu
See error message "Could not create temporary directory: Permission denied"
Same problem when run with code --disable-extensions

VMWare Airwatch is installed, which may be the issue (but not for certain)
Running as System Administrator. Installed as System Administrator

This was previously raised as issue #42231, but was requested to test new version

![screen shot 2018-02-16 at 11 29 32 am](https://user-images.githubusercontent.com/14302060/36288092-254451fe-130d-11e8-9eb0-e57027d2abe3.png)

**Comment by vandijkstef** [comment]
Confirming issue on VSCode 1.19.2, also OSX 10.13.3. No Airwatch installed.
Is VSCode failing silently when it's "automatically" checking for updates? Any way to make that verbose?
Any log files somebody might be interested in?

**Comment by andrewssi** [comment]
@vandijkstef I actually did a good hunt for log files, since presumably there is an issue with the folder being used for the upgrade and seeing the permission sets on that folder may bring us closer to the solution. I wasn't able to find anything more verbose, but any suggestions to enable logs/open specific files would be gratefully received.

**Comment by vandijkstef** [comment]
Somehow VSCode just updated to v1.20.1. 
I did try to update by running VSCode as root (yesterday), but that didn't work out. It might be possible the files where downloaded as root, and VSCode (non-rooted) only discovered them today.
No system restart or VSCode restart. I did switch workspaces. (Though the update pop-up came in after +30 minutes after switching)

**Comment by andrewssi** [comment]
@vandijkstef I was also able to initiate the first part of the update operation by running as root.

1) The update appeared to download as root, but restarting VSCode (as root and as non-root) did **not** result in the update being applied
2) I also got a warning saying that running as root was not recommended for VSCode

**Comment by andrewssi** [comment]
New behavior. I have version 1.22.1 installed and tried an update today (1.24 is released). This time nothing happens at all after 'Check for updates...' , and nothing appearing in the output windows either. (Mac OS 10.13.4)

**Comment by maelvalais** [comment]
To solve this issue, I followed the advice in https://github.com/Microsoft/vscode/issues/7426#issuecomment-301018371: 
1. check that permissions for the VSCode cache folders are correct:

     ls -l ~/Library/Caches/com.microsoft.VSCodeInsiders.*

If they are not (in my case, the ShipIt folder was empty and it was owned by root for some reason), I removed it (`sudo rm -Rf /Users/mvalais/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt`)

**Comment by andrewssi** [comment]
@maelvalais Great! Although that exact command didn't work, I tried a similar one:

sudo rm -Rf ~/Library/Caches/com.microsoft.VSCode.ShipIt

And it is now updating fine.

Is there a way to address this issue in the release notes?

**Comment by gmclelland** [comment]
Thanks @maelvalais!
```
sudo rm -Rf ~/Library/Caches/com.microsoft.VSCode.ShipIt
```
Fixed the problem for my vscode not updating.  Before it would simply say "Downloading," but would never finish.
