### ISSUE TITLE
Markdown internal links within the page in preview mode are dead

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#4379]
- VSCode Version: 0.10.11
- OS Version:Win 10

Steps to Reproduce:

1. Link in markdown within the same page: `[Internal link](#TestLink)`
2. Header later in the same document: `####Test Link Heading <a name="TestLink"></a>`

I've tried option 2 with id instead of name, but no difference. The item looks like a link, and it changes my cursor to the little hand to click on the link, but the link is dead when I click on it. 

I've looked up how to properly use `marked` as described in the main vscode pages, but this isn't working...

Is this me doing it wrong or is it something that needs to be fixed?

**Comment by Tyriar** [comment]
The `localhref` attribute in the generated markdown seems to do nothing. Changing it to `href` works but also breaks vscode's viewport when clicked.

**Comment by bpasero** [comment]
#3771
