### ISSUE TITLE
can not open multiple VSCode instances from command line

### ISSUE THREAD

**Issue by foolyoghurt** [Microsoft/vscode#438]
I added `code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* }` to my `.zshrc` but it didn't work. When the first time I use `code a` to open folder `a`, it was OK. However, then I use `code b` to open folder `b`, VSCode still had one instance and still folder `a` is open.

Even I use `open -n /Applications/Visual\ Studio\ Code.app`, things doesn't work too.

**Comment by matteocrippa** [comment]
it also would be fun to have a button that install the cli command in bash_profile like it happens in other similar tools

**Comment by foolyoghurt** [comment]
Finally after I restart my macbook, it works... Maybe it's just something wrong with my macbook
