### ISSUE TITLE
Problems with install at ubuntu 18.04

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#43801]
Dependency error when trying to install code at Ubuntu 18.04:
```

wellington@wellington-desktop:~/Downloads$ sudo dpkg -i code_1.20.1-1518535978_amd64.deb
A seleccionar pacote anteriormente não seleccionado code.
(Lendo banco de dados ... 415419 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar code_1.20.1-1518535978_amd64.deb ...
A descompactar code (1.20.1-1518535978) ...
dpkg: problemas com dependências impedem a configuração de code:
 code depende de libgconf-2-4; porém:
  Pacote libgconf-2-4 não está instalado.

dpkg: erro ao processar o pacote code (--install):
 problemas de dependência - deixando desconfigurado
A processar 'triggers' para gnome-menus (3.13.3-11ubuntu1) ...
A processar 'triggers' para desktop-file-utils (0.23-1ubuntu3) ...
A processar 'triggers' para mime-support (3.60ubuntu1) ...
Erros foram encontrados durante o processamento de:
 code

```

- VSCode Version: code_1.20.1-1518535978_amd64.deb
- OS Version:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu Bionic Beaver (development branch)"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Bionic Beaver (development branch)"
VERSION_ID="18.04"
```

Steps to Reproduce:

1. Download 
2. Try install from Ubuntu Central Software - FAILED
3. Try install with 'dpkg' - FAILED
4. Try 'dpkg' with '--force-all' - FAILED to open (But installed)
5. /usr/share/code/bin/../code: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Your issue is that the dependency libgconf never gets installed, I think running `sudo apt-get install -f` will fix it. If try installing via the apt repo in https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions
