### ISSUE TITLE
[Themes] Predawn Markdown theme is all red text

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4380]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Install Predawn theme
2. Change theme to Predawn Markdown

Actual: All text is red for any language type

Expected: Not entirely sure, but I would expect there to be some color differences. There is no documentation I could find on what to expect with this theme.

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/vscode-themes#7

**Comment by Tyriar** [comment]
Moved to https://github.com/Microsoft/vscode-themes/issues/7

**Comment by AppShipIt** [comment]
Broken link? Possibly related to #3008 (see also #4386).

**Comment by Tyriar** [comment]
The vscode-themes repo is closed source atm is why you're seeing a 404.

**Comment by AppShipIt** [comment]
Ah it's generated code anyway so probably wouldn't make sense to PR.
