### ISSUE TITLE
Intellisense in C# not working at all in Insiders

### ISSUE THREAD

**Issue by byroniac** [Microsoft/vscode#43800]
### Issue Type
Bug

### Description

Just load a C# file in VSCode-Insiders, no intellisense available, maybe Omnisharp editor never loads?

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T05:17:01.988Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (2 x 2992)|
|Memory (System)|7.84GB (4.57GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe F:\MISDIR\APPS3\WhseRequest|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.14.0

</details>
Reproduces without extensions

**Comment by egamma** [comment]
@byroniac issue confirmed, the c# extension is activated but the OmniSharp server isn´t running. I´ve filed https://github.com/OmniSharp/omnisharp-vscode/issues/2048, closing this issue.

**Comment by byroniac** [comment]
I just tested and it works in VSCode-Insiders Linux, but not Windows.
