### ISSUE TITLE
No access to network drives when run as admin

### ISSUE THREAD

**Issue by Trevirirus** [Microsoft/vscode#43807]
### Issue Type
Bug

### Description

Run VS Code as Admin 
trie to access connected network drives via open Folder --> Message Folder / Path not found

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2394)|
|Memory (System)|7.80GB (2.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.13.0
githistory|don|0.4.0
xml|Dot|1.9.2
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
vscode-map-preview|jum|0.4.2
vscode-jade-snippets|mrm|1.0.1
vscode-puglint|mrm|2.3.0
vscode-azureappservice|ms-|0.5.1
python|ms-|2018.1.0
azure-account|ms-|0.3.0
cpptools|ms-|0.15.0
debugger-for-chrome|msj|4.1.0
require-sort|Per|0.0.1
java|red|0.19.0
vscode-icons|rob|7.19.0
bootstrap4-vscode|the|4.0.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@Trevirirus do you get this error from the OS file dialog or afterwards?

**Comment by Trevirirus** [comment]
Inside the OS folder dialog when trying to use my fodler bookmarks;
and inside VS Code on th welcome Tab when trying to open my folder via last used section

**Comment by bpasero** [comment]
@Trevirirus I do not think there is much that VS Code could do if even the OS itself shows you that error. I am going to close this issue, you will have to check your configuration for access rights to these folders.

**Comment by Trevirirus** [comment]
Im able to access these folders from the explorer and also from VS Code when run not in admin mode so there are n restrictions

**Comment by Iw1s** [comment]
I encountered the exact same issue as described by @Trevirirus.  
All network drives connected to my PC aren't visible within the OS folder dialog created by VS Code after the recent update. Though, this is not the case for any other software running on my computer.  
For me, this also only happens when VS Code runs as administrator.
