### ISSUE TITLE
Typescript/tsx attribute names auto-completion is cluttered with js/ts keywords

### ISSUE THREAD

**Issue by guillaume86** [Microsoft/vscode#43812]
- VSCode Version: 1.20.1
- OS Version: Windows 10
- Typescript: 2.7.1

Steps to Reproduce:

1. Open a .tsx file
2. Enter a JSX tag and hit ctrl-space to suggest attributes
3. Here's my auto-completion list:
![image](https://user-images.githubusercontent.com/441850/36300229-b14a0372-1300-11e8-8432-e564e6fadf6d.png)

Notes:

I'm pretty sure it was working fine a few weeks ago, but can't guarantee it because I jumped a lot between IDEs these last weeks.

If keywords cannot be excluded, it would be better to have the attributes at the top, it's a huge time saver when using React components.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/21844

Should already be fixed in `typescript@next` if you want to [give that a try in your workspace](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)
