### ISSUE TITLE
IntelliSense / Syntax highlighting not working properly in Insider 1.21.0

### ISSUE THREAD

**Issue by iricigor** [Microsoft/vscode#43816]
- VSCode Version: Insider 1.21.0
- OS Version: Windows 10

# Steps to Reproduce:

1. Install VS Code
2. Paste code below and change language settings to PowerShell

**Does this issue occur when all extensions are disabled?:** Yes

Installing PowerShell extension has no impact on behaviour

### Code to paste

```PowerShell
$p = get-process | select -first 1
$a = $p.Name -split '='
Write-Host $a
```

# Expected result

Here is screenshot from stable VS Code 1.20.1
![image](https://user-images.githubusercontent.com/15923171/36302546-29e1193a-1309-11e8-8b4c-6f4f131dc9c7.png)
Syntax highlighting is as expected. Notice command in last line.

# Actual result

Here is screenshot from Insiders VS Code 1.21.0
![image](https://user-images.githubusercontent.com/15923171/36302602-4da8b72e-1309-11e8-9116-b564c9e69c7b.png)

### Explanation

Notice again command in last line. It is not correctly colored now. Code itself is correct.

The actual problem is in previous line. Token '=' is not parsed properly (opening and closing apostrophes are not matching). The same thing happens also with quotation marks (i.e. "=" will be wrong), but also other spoecial characters instead of equal sign, like %, !, etc.

Furthermore, this happens only when there is a dot in the beggining of the same line. If code would be `$a = $p -split '='` or if there would be another dot in the same line `$a = $p.name -split '.'`, parsing would be fine.

**Comment by aeschli** [comment]
This issue was moved to PowerShell/EditorSyntax#66
