### ISSUE TITLE
Navigation to file is broken in latest 'insider' release

### ISSUE THREAD

**Issue by drweb86-work** [Microsoft/vscode#43814]
- VSCode Version: latest insider
- OS Version: Win10x64Pro

Ctrl+T sees now only opened files.

Steps to Reproduce:
1. Open project folder
2. Press Ctrl+T, type test
Error => Only files with test in name visible which are opened in tabs
Expected => All files within project folder with test in name are listed in drop down

**Comment by stevenhay** [comment]
Seems to be working for me

![image](https://user-images.githubusercontent.com/26744309/36301719-c006fd14-12fd-11e8-82d7-49bf86fa077b.png)

![image](https://user-images.githubusercontent.com/26744309/36301729-c8803af0-12fd-11e8-8b66-b572c142e592.png)

Version 1.21.0-insider
Commit 936b796aa8667de5edb536b00ce8a8e61fcebfb6
Date 2018-02-16T05:15:47.029Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by drweb86-work** [comment]
Version 1.21.0-insider
Commit 70e020b2377f12894ca11254548ce365a0e435f1 -- commit is different
Date 2018-02-15T05:17:01.988Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by drweb86-work** [comment]
Im sorry, after update it works again
