### ISSUE TITLE
'Smarter IntelliSense' no longer works since 1.20

### ISSUE THREAD

**Issue by edmunn-morphsites** [Microsoft/vscode#43818]
### Issue Type
Bug

### Description

'Smarter IntelliSense' no longer works since 1.20.
I have noticed this happen in HTML, CSS and SCSS, the 3 languages that I mainly use.

In the screenshot below, I type 'bac' each time, and then use the arrow keys to select 'background-color:'. On 1.19, if I then went to type 'bac', it would learn to select 'background-color', not 'backface-visibility', which is the first option alphabetically.

The same happens with 'wid', showing 'widows' instead of the more common 'width'.

I always have emmet disabled, using '"emmet.showExpandedAbbreviation": "never",' in my user settings. I prefer Intellisense over Emmet.

I hope this is enough information.

Thank you,
Edward.

### Screenshot

![screenshot 2018-02-16 10 39 14](https://user-images.githubusercontent.com/20769317/36304229-d1874b4e-1306-11e8-80c2-c8a372cb4a35.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.24GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
minify|Hoo|0.3.0
html-css-class-completion|Zig|1.16.2
Handlebars|and|0.2.0
path-intellisense|chr|1.4.2
auto-close-tag|for|0.5.5

</details>
Reproduces without extensions

**Comment by egamma** [comment]
There is now a setting to control the selection behaviour, does this explanation help https://github.com/Microsoft/vscode/issues/41060#issuecomment-364284879?

**Comment by edmunn-morphsites** [comment]
That's fantastic! I'd not seen it documented though.
Thanks for the assistance @egamma
