### ISSUE TITLE
Reveal in SideBar - Use case where the wrong file is shown/highlighted

### ISSUE THREAD

**Issue by WilliamHolmes** [Microsoft/vscode#43817]
- VSCode Version: 1.20.1
- OS Version: Mac ( HS 10.13.3)

Using Source Control

Steps to Reproduce:

1. Edit & save `FileA.js`
2. Open `FileB.js`
3. Double Click `FileA.js` from the Source Control > Changes
4. You should see a new tab  `FileA.js (Working Tree)`
5. Right click on the `FileA.js (Working Tree)` tab
6. Click on **Reveal in Side Bar**

**EXPECT**: `FileA.js` to be highlighted in the side bar

**BUG**: `FileB.js` is highlighted in the side bar.

Does this issue occur when all extensions are disabled?: **YES**

**NOTES**
1. if you skip **step 2** its works as expected.
2. If you try **step 5** a second time it works as expected.

**Comment by isidorn** [comment]
@WilliamHolmes let me get this clear. You open the git viewlet and where exactly do you right click to reveal in sidebar? Maybe a picture would help. 
Since I can only find reveal in Side Bar in the command palette

**Comment by WilliamHolmes** [comment]
if you right click on the open tab
![image](https://user-images.githubusercontent.com/5538260/36306131-5288702c-130e-11e8-91df-c0d75da2bc89.png)

**Comment by isidorn** [comment]
@WilliamHolmes got it thanks

**Comment by isidorn** [comment]
I just checked and this seems to be fixed in latest vscode insiders.
Please try it there and let us know if you still see it 
https://code.visualstudio.com/insiders/
