### ISSUE TITLE
Unexpected behavior when using AdditionalTextEdits

### ISSUE THREAD

**Issue by qutreson** [Microsoft/vscode#43810]
**- VSCode Version**: 1.21.0
**- OS Version**: Windows 10

In our extension, we want to be able to insert text when using Intellisense around the cursor. 
For instance, we would like to end up in this situation when triggering Intellisense on a method:
`MyProcedureWithVariable(^)` where ^ represents the location of the cursor.

We tried to use the main TextEdit in our to add the part before the cursor "MyProcedureWithVariable(" and to use AdditionalTextEdits to add ")". However, whenever we use additional text edits, the behavior in VS Code seems bogus.

**Steps to Reproduce:**

1. Create a TextEdit with your new text and with a defined range. 
2. Create an AdditionalTextEdit with some text and a range starting after the one of the main textEdit (considering also the length of the new inserted text)
3. Trigger Intellisense without writing anything.

**Expected**: The main text edit is added followed afterwards by the additional one.
**Actual:** The additionalTextEdit is inserted "under" the main text edit. 

A few screenshot of the behaviour:
![image](https://user-images.githubusercontent.com/31541422/36299874-41132ec2-12ff-11e8-9c84-4c2d7b2c7684.png)
Trigger Intellisense:
![image](https://user-images.githubusercontent.com/31541422/36299911-5ec3acee-12ff-11e8-92d0-ac5b4c3f0fbc.png)
Select the completion item:
![image](https://user-images.githubusercontent.com/31541422/36299919-69c5111e-12ff-11e8-87f3-2a51b7385115.png)
After presing Ctrl+Z:
![image](https://user-images.githubusercontent.com/31541422/36299935-79b863fa-12ff-11e8-8f9e-dbe926008426.png)

It looks like the AdditionalTextEdit is inserted at the position where intellisense was triggered and then is replaced by the main TextEdit as the undo shows. This order makes sense this the edits are considered as a stack, but the position of the additionalTextEdits seems wrong to me.

**Other interesting case**:
If I start writing something, for instance I have written M when I trigger intellisense. Then the edit range is not correct anymore, it inserts MyProcedureWithVar after the M instead of replacing it. If I remove the additionalTextEdits from the completion item send to VS Code (and without any other changes), then in the same situation, the M is correctly replaced as expected.

**Comment by rcjsuen** [comment]
If you want to position the cursor, @qutreson, can't you just use a single TextEdit that inserts `MyProcedureWithVariable($1)` and let the [snippet syntax](https://code.visualstudio.com/docs/editor/userdefinedsnippets) move the cursor for you?

**Comment by qutreson** [comment]
Can I do it while keeping the right icon displayed in VS Code? I want to keep the method icon for the suggestion, and not to have the snippet one. If I can do it, then yes, it would fix my problem :)

**Comment by rcjsuen** [comment]
@qutreson Did you try and see? I don't have this problem with my language server.

**Comment by qutreson** [comment]
@rcjsuen, using snippets, actually fixed my problem, thank you :)

**Comment by jrieken** [comment]
Yeah, snippets is the way to go. Using the additional edits on the current position is undefined and most likely results in garbage... Closing as you have a way for this and as there is a dupe
