### ISSUE TITLE
Windows: when deleting a folder with files that are in use, then there is no error message shown

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#43819]
Please see the discussion in this issue https://github.com/Microsoft/vscode/issues/43755. I would have expected that an error shows up when a file cannot be deleted since it is used by another process.

**Comment by arerlend** [comment]
@egamma getting the same behavior as #43755.  Deleting a directory in use by another process fails with no error message.

Repro: open terminal to working directory foo/bar/.  Open foo/ in VS Code.  Right click + delete foo/bar/ in VS Code sidebar explorer.  Refresh and it's still there.  `cd ..` in terminal, delete foo/bar/ again, deletion succeeds, leaving just foo/.

VS Code About:
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by devuxer** [comment]
This one has bitten me several times. I think I've deleted something and it keeps coming back...because there's no error! Hoping this will be fixed. soon.

**Comment by bpasero** [comment]
See https://github.com/electron/electron/issues/15370

**Comment by isidorn** [comment]
@bpasero thanks for providing a pointer
This depends on the linked electron issue, adding upstream label.

**Comment by graph** [comment]
Can you guys do a workaround for windows temporarily until the electron issue is fixed? Like do a file exists check to make sure after the function completes the files have actually been deleted. This bug gets me too often as I'm wondering why my resources are not updating. Maybe do like a temporary polyfill approach to fix this.

Thank you.

**Comment by bpasero** [comment]
The latest Electron update resolves this finally:

![image](https://user-images.githubusercontent.com/900690/96329385-91867880-104c-11eb-9605-768438288450.png)

**Comment by bpasero** [comment]
**Verification:** on Windows, open the terminal and cd into a folder. Try to delete that folder from VSCode. It should show a dialog.

**Comment by isidorn** [comment]
Works great now. Thanks Electron!
