### ISSUE TITLE
Cannot read property 'extensionsPath' of undefined

### ISSUE THREAD

**Issue by WitekS** [Microsoft/vscode#43823]
### Issue Type
Bug

### Description

[Error - 12:50:41] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'extensionsPath' of undefined

  // Path to a folder containing Emmet profiles and snippets.'
  "emmet.extensionsPath": null

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.3.9600

Reproduces without extensions

**Comment by hakamibrahim** [comment]
I have same issue for this on blade template laravel
![image](https://user-images.githubusercontent.com/18589069/36308551-c0dfc1ac-1353-11e8-9fab-2aa947fa60e1.png)

**Comment by phpsti** [comment]
im experiencing the same error. my templates was working a few hours ago. but then something like this happened 

[Error - 23:45:36] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'extensionsPath' of undefined

**Comment by V-ed** [comment]
@tiansin's pull request (onecentlin/laravel-blade-snippets-vscode#47) should fix this issue (it's not a VSCode issue, but rather an extension issue).

**Comment by ramya-rao-a** [comment]
Thanks @V-ed

**Comment by ramya-rao-a** [comment]
@WitekS Can you confirm that you see this issue in blade files only and that by disabling the laravel-blade-snippets-vscode extension the issue no longer occurs?

**Comment by V-ed** [comment]
@ramya-rao-a I'm not @WitekS but I have the exact same problem, so I'm confident enough to say that this error happened with an update to the onecentlin/laravel-blade-snippets-vscode update (I am actually even using a previous version of the extension to prevent the output panel opening each time I enter two chars!).

The problem doesn't occur (at least on my side, of course) if the extension is disabled / on an earlier version of the extension. I even talked about this temporary solution in the first issue that got opened in the extension repo ([here](https://github.com/onecentlin/laravel-blade-snippets-vscode/issues/44#issuecomment-366247373)).

**Comment by ramya-rao-a** [comment]
Thanks for the clarification @V-ed!

**Comment by V-ed** [comment]
@ramya-rao-a No problems, and thanks for looking into the issue and helping @tiansin for the PR!

I'm grateful that you are also helping extension creators as well as the core of VSCode, I really love this community! :)

**Comment by ramya-rao-a** [comment]
Thanks for your contributions as well @V-ed :)

**Comment by WitekS** [comment]
I confirm the error occurred only for blade but after upgrading the extension to version 1.14.2 it looks like it is OK
Thank you for your quick response and professional action
Regards
