### ISSUE TITLE
jsonc: Should not allow invalid JSON syntax (trailing commas)

### ISSUE THREAD

**Issue by perlun** [Microsoft/vscode#43825]
- VSCode Version: Insiders build, 135d4a5d5cecd82e9e4da7ede655fb09af0dac35
- OS Version: macOS 10.13.3 (17D47)

Steps to Reproduce:

1. Open a file with jsonc (JSON with Comments)
2. Write a trailing comma.

----

Trailing commas are **not valid JSON**. However, they are valid JavaScript nowadays.

I had a `tsconfig.json` that looked like this:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "module": "es6",
    "moduleResolution": "node",
    "noEmit": true,
    "noEmitOnError": false,
    "noImplicitAny": true,
    "noImplicitReturns":true,
    "noImplicitThis": true,
    "paths": {
      "notime/tests/*": ["tests/*"],
      "notime/*": [
        "app/*"
      ]
    },
    "sourceMap": true,
    "target": "es2017", // <- here is the error
  },
  "exclude": [
    "tmp",
    "dist",
    "node_modules",
    "bower_components"
  ]
}
```

When using the regular JSON mode, the syntax checking correctly errors about the trailing comma. However, when using jsonc mode, it _does not_ which is a bit sad because it made me start debugging other things, stepping through the node extension I was using etc. instead of looking carefully at the file. I assumed the file was good since it "looked good" in vscode.

I believe jsonc should generate errors for files like the above. **Only** comments should be allowed, but not other "invalid JSON" syntax. Are there particularly good reasons for the current behavior?

**Comment by perlun** [comment]
@vscodebot Thanks, but these do not cover my particular issue.

**Comment by aeschli** [comment]
`jsonc` is intended to be the format of VSCode's settings files and we've gotten many requests to be tolerant on trailing semicolons.

**Comment by aeschli** [comment]
Maybe file a issue against TypeScript to also ignore trailing commas. Wouldn't that be a better solution?

**Comment by usernamehw** [comment]
Not 100% sure, but I think typescript 2.4+ ignores trailing commas in `tsconfig.json`.

**Comment by perlun** [comment]
The issue wasn't actually with the TypeScript compiler per se, but with `ember-cli-typescript` 1.0.6 which failed to parse the JSON because of this (it manually parses the file with a JSON-strict parser.)

Upgrading `ember-cli-typescript` to 1.1.3 solved this issue; it has obviously been changed in this regard. I'll close this issue now, since as you mention, other people have wanted the format to be tolerant on trailing commas. Thanks for your time! 👍
