### ISSUE TITLE
"Copy" as in Copy/Paste works intermittently from editor screen

### ISSUE THREAD

**Issue by stasku** [Microsoft/vscode#4382]
- VSCode Version: Monaco bits used by extensions in Azure Portal at https://portal.azure.com
- OS Version: Windows 10

Originally reported by customers of Azure Automation extension of Azure Portal here: https://feedback.azure.com/forums/246290/suggestions/12269811

Steps to Reproduce (as stated by customers):
(User 1)
When trying to copy paste data, the copy works intermittently at best. I have not been able to reliably replicate a scenario where this works. I can literally select some text, copy it, paste it to notepad (or something else), then go back to copy something else and it fails to copy still retaining what I last had in the clipboard.

(User 2)
It happens for me in PowerShell editor with lots of code and many terms per line.  Also, I typically use Chrome.  It is intermittent.

**Comment by stasku** [comment]
Hi, I have requested Portal team to switch to latest vscode bits, but could you in the meantime check and confirm if this issue is already fixed?
Thanks!

**Comment by alexandrudima** [comment]
@stasku I need some steps to try to reproduce. VSCode is based on Chromium 45 and we do not experience such issues AFAIK.

**Comment by alexandrudima** [comment]
Given I cannot reproduce, I cannot act on this issue. Please reopen or create a new one when more information is available.
