### ISSUE TITLE
No code formatting for single .cs files

### ISSUE THREAD

**Issue by andoral** [Microsoft/vscode#43824]
- VSCode Version: 1.20.0
- OS Version: Windows 10 Pro 1709 x64

Steps to Reproduce:

1. Create single .cs file
2. Write code

Does this issue occur when all extensions are disabled?:  Yes

**Comment by egamma** [comment]
Formatting requires a .csproj file. This looks like this issue https://github.com/OmniSharp/omnisharp-vscode/issues/47. Please continue the discussion in the omnisharp-vscode repository.
