### ISSUE TITLE
[Question] How to disable linter red color on the sidebar

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#43837]
Hi, there is a way to disable the linters related red highlights from the sidebar?

<img width="259" alt="screen shot 2018-02-16 at 16 14 34" src="https://user-images.githubusercontent.com/10454741/36314241-809ea348-1334-11e8-8bd3-1d417941b714.png">

**Comment by V-ed** [comment]
There is a setting that affects sidebar problem coloring :
```json
// Show Errors & Warnings on files and folder.
"problems.decorations.enabled": true,
```

Simply add this to your user settings and voilà.

Also, next time, follow [this guideline for submitting issues](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) (questions are supposed to go to stackoverflow).

**Comment by equinusocio** [comment]
Thank you.
