### ISSUE TITLE
Diff view becomes misaligned wordwrap is turned on

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4383]
#4006 

The numbers become misaligned when word wrap is toggled (<kbd>alt</kbd>+<kbd>z</kbd>).

![image](https://cloud.githubusercontent.com/assets/2193314/13858565/75489600-ec3c-11e5-86b1-6e52c3ea5216.png)

**Comment by flxkid** [comment]
Using VS Code to write documentation in markdown and restructured text format where having this word wrap in the diff view would definitely be useful (paragraph of text all on one line). Instead of removing it (as was done here), can it be fixed?

**Comment by alexandrudima** [comment]
@flxkid We don't track closed issues, especially those with a verified tag. Please create a new issue.
