### ISSUE TITLE
PowerShell copyright wrapping doubles line?

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#43834]
![2018-02-16 1](https://user-images.githubusercontent.com/962340/36312270-d7170e88-12fb-11e8-8e52-21a5033795ac.png)
![2018-02-16](https://user-images.githubusercontent.com/962340/36312273-d89ec6c4-12fb-11e8-9b4e-9335baca4dfe.png)

just noticed this weirdness in latest insiders on windows 10.
thank you

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26375
