### ISSUE TITLE
Syntax highlight bug in PowerShell - not detecting string quoute close

### ISSUE THREAD

**Issue by csharmath** [Microsoft/vscode#43839]
### Issue Type
Bug

### Description
<img width="663" alt="stringsyntaxhighlightbug" src="https://user-images.githubusercontent.com/1450460/36316670-e15354d0-1308-11e8-9b60-ff57bbdba525.PNG">

Paste this to a ps1 file.

```
Get-Disk `
    | Where-Object {$_.Size -gt $MinSize -and $_.BusType -notmatch 'fibre|iscsi|usb' } `
    | Sort-Object -Property Number
# This is not a string but will be displayed as string
```

Expected:  String displayed on between the two single quoutes.
Actual: Everything is displayed as string after the opening single quoute

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T05:17:01.988Z)
OS version: Windows_NT x64 10.0.15063

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
xml|Dot|1.9.2
tslint|eg2|1.0.27
puppet-vscode|jpo|0.9.0
mssql|ms-|1.3.0
python|ms-|2018.1.0
csharp|ms-|1.14.0
PowerShell|ms-|1.5.1
vscode-docker|Pet|0.0.24
smartpaste|reb|0.0.3
java|red|0.19.0
vscode-icons|rob|7.19.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.1

</details>
Reproduces only with extensions

**Comment by aeschli** [comment]
This issue was moved to PowerShell/EditorSyntax#67

**Comment by csharmath** [comment]
This is an even better repro with an MSFT owned psm1.
Open PSDscResources\DscResources\MSFT_ServiceResource\MSFT_ServiceResource.psm1 at line 1392
![image](https://user-images.githubusercontent.com/1450460/36317828-271c4744-130c-11e8-909f-53b1205fb7d6.png)

I guess you guys are not dogfooding VSCode insiders with PowerShell ? So what do you use ?
I found VSCode insiders to be better than VSCode for PowerShell so far, but switching back until this is fixed....

This shows VSCode fine vs VS Code insiders buggy
![image](https://user-images.githubusercontent.com/1450460/36318039-b5025d64-130c-11e8-96cc-8cc0315a4956.png)
