### ISSUE TITLE
Zombie svchost.exe handles

### ISSUE THREAD

**Issue by OfficerHalf** [Microsoft/vscode#43831]
- OS Version: Windows 10 Enterprise
- Version 1.21.0-insider
- Commit 70e020b2377f12894ca11254548ce365a0e435f1
- Date 2018-02-15T05:17:01.988Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

Steps to Reproduce:

1. Run VS Code.
2. Notice a number of svchost.exe processes started. This is fine, and normal.
3. Kill VS Code.
4. ~4 svchost.exe processes started by VS Code are left over. They continue to run until killed or the system is rebooted. This is repeatable, and the number grows each time VS Code is launched.

Does this issue occur when all extensions are disabled?: Yes

CPUs | Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)
-- | --
Memory (System) | 63.88GB (57.51GB free)
Process Argv | C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
html-snippets | abu | 0.2.1
ng-template | Ang | 0.1.9
emojisense | bie | 0.4.0
npm-intellisense | chr | 1.3.0
path-intellisense | chr | 1.4.2
vscode-eslint | dba | 1.4.5
xml | Dot | 1.9.2
vscode-html-css | ecm | 0.2.0
tslint | eg2 | 1.0.27
vscode-npm-script | eg2 | 0.3.3
auto-rename-tag | for | 0.0.15
code-runner | for | 0.8.7
vscode-firefox-debug | hbe | 1.1.0
vscode-auto-open-markdown-preview | hnw | 0.0.4
plantuml | jeb | 2.5.2
Angular2 | joh | 2.12.0
docomment | k-- | 0.0.17
HTMLHint | mka | 0.4.0
hg | mrc | 1.2.3
python | ms- | 2018.1.0
cpptools | ms- | 0.15.0
csharp | ms- | 1.14.0
PowerShell | ms- | 1.5.1
debugger-for-chrome | msj | 4.1.0
vscode-css-peek | pra | 2.1.0
typescript-hero | rbb | 2.2.0
vscode-icons | rob | 7.19.0
partial-diff | ryu | 0.5.1
code-settings-sync | Sha | 2.8.7
stylelint | shi | 0.32.0
autoimport | ste | 1.5.3
lorem-ipsum | Tyr | 1.2.0
shell-launcher | Tyr | 0.1.6
vscode-todo-highlight | way | 0.5.11
vscode-import-cost | wix | 2.6.2
vscode-jumpy | wma | 0.3.1
html-css-class-completion | Zig | 1.16.2

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by OfficerHalf** [comment]
Thought I had tried without extensions - but I guess I hadn't killed all the old zombies before doing so. I'll sort through and see if I can narrow down which ones are causing it.
