### ISSUE TITLE
Expand selection ignores JSX elements

### ISSUE THREAD

**Issue by ColCh** [Microsoft/vscode#43832]
- VSCode Version: 1.20.1
- OS Version: MAC OS 10.13.3

Steps to Reproduce:

1. place cursor inside of JSX element content
2. press "expand selection" multiple times

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>GIF: </summary>

How it's now:
![](https://media.giphy.com/media/Nl51zdi9OQtLLLIK7c/giphy.gif)
Compare it to webstorm:
![](https://media.giphy.com/media/63JCeEzy9PgHyKii57/giphy.gif)
</details>

**Comment by mjbvz** [comment]
Thanks! Looks like this already falls under #14882
