### ISSUE TITLE
Reassigning a keyboard shortcut to a command, with a default keybinding, doesn't work without resetting.

### ISSUE THREAD

**Issue by TobiasPalludan** [Microsoft/vscode#43849]
- VSCode Version:
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
Microsoft Windows [Version 10.0.16299.192]

Steps to Reproduce:

1. Open Keyboard Shortcuts. (File -> Preferences -> Keyboard Shortcuts)
2. Find a command with an already defined shortcut (tested with: "Format Selection" which have "Ctrl + K, Ctrl + F" as the default shortcut)
![image](https://user-images.githubusercontent.com/15048182/36322858-336451a2-134f-11e8-9057-3063de6f1cfc.png)

3. Assign a shortcut for it (tested with: "Ctrl + U") (note: here, source changes to user)
![image](https://user-images.githubusercontent.com/15048182/36322870-41439dfa-134f-11e8-87f5-02179ba8e6bd.png)

4. Delete the shortcut (pressing delete, or right-clicking and pressing delete) (source is still user, but no shortcut is assigned - not even the default one - which is probably intended behavior)
![image](https://user-images.githubusercontent.com/15048182/36322887-51daa078-134f-11e8-8dbc-7b2005b7a869.png)

5. Trying to re-assign a shortcut changes nothing - the keybinding field is empty, and trying the shortcut yields no results. This counts for changing the shortcut to both the same and a different keybinding as before.

Workaround: Simply right-click and reset the keybinding. This will allow you to give it a new keybinding.

Note: For commands that have no default keybinding, this isn't a problem. (such as editor.action.format in the above pictures)

Does this issue occur when all extensions are disabled?: Yes

I hope this was enough information. This was my first issue, ever, so I'm sorry if I got something wrong.

**Comment by sandy081** [comment]
Step 5 works now - Reassigning a short cut changes to the assigned short cut.
