### ISSUE TITLE
autocomplete is not working when working with JSON templates. When I press Ctrl+space, it is stuck on loading. Reinstalling or restart VS Code do not help.

### ISSUE THREAD

**Issue by a-mosheh** [Microsoft/vscode#43845]
- VSCode Version:
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows 10 1709 (OS Build 16299.248)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
@a-mosheh please provide a snippet that illustrates the problem. What kind of JSON templates are you using? Do they come from an extension?

**Comment by a-mosheh** [comment]
Hello, I'm using Azure ARM template JSON (i'm following examples here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-create-first-template),

**Comment by aeschli** [comment]
Can you give more details? Please post the sample code, annotated the location where you try code completion.

That's what I quickly tried and which seems to work for me:
![image](https://user-images.githubusercontent.com/6461412/42805529-5151bde8-89ac-11e8-9b05-96fca23cf858.png)

**Comment by aeschli** [comment]
Closing due to lack of details.
