### ISSUE TITLE
Multiple instance of VS Code is opened in the Process 

### ISSUE THREAD

**Issue by shrivatsahosabettu** [Microsoft/vscode#43842]
As you can see that I have only one VS Code opened in the application bar, but when I see the process there are multiple instances of VS Code is running. What is the reason behind it.

![image](https://user-images.githubusercontent.com/12061573/36318317-7e675c92-1365-11e8-930a-a796cbf17f1c.png)

- VSCode Version: 1.20.1 
- OS Version: Windows 8.1 

Steps to Reproduce:

1. Just open the application of VS Code with all extension disabled. In the Process tab there are multiple VS Code opened.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
VS Code is using a multi-process architecture and you see the different process that VS Code is running.

To understand the purpose of the different process you can run `code --status`
