### ISSUE TITLE
Inactive code is now GREY!

### ISSUE THREAD

**Issue by Darkstarxt** [Microsoft/vscode#43844]
### Issue Type
Bug

### Description

PLEASE ! How can I disable this new feature ! Many Many define are from makefile, now my code is almost ALL grey !

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2693)|
|Memory (System)|11.88GB (4.64GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0
makefiles-support-for-vscode|nae|0.0.3
vscode-todo-highlight|way|0.5.11

</details>
Reproduces only with extensions

**Comment by usernamehw** [comment]
Wrong repo? https://github.com/Microsoft/vscode-cpptools

**Comment by Darkstarxt** [comment]
Sorry ! 

Thanks !
