### ISSUE TITLE
Mutiple program instance of rg.exe started running 

### ISSUE THREAD

**Issue by shrivatsahosabettu** [Microsoft/vscode#43843]
Mutiple instance of rg.exe starts running when VS Code starts. It will be running for about 5-6 min and then all will be gone. My Disk tab in the task manager shows 100% when rg.exe starts running. After rg.exe finishes disk will show 0%-5%.

In the screen print there are only 2 instances are running but actually more are there which I couldn't able to capture as is was running below.

In the user settings I have included code below, but it still the same.
`"search.followSymlinks": false,`

Is this is a issue which need to be fixed or any work around?

- OS Version: Windows 8.1 
- VSCode Version:  1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:33:21.935Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

![image](https://user-images.githubusercontent.com/12061573/36319007-9466f136-1367-11e8-98c5-887bed948915.png)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This is probably from extensions deciding whether to activate on launch. Are you opening a large workspace?

Can you provide the command line arguments of those processes from the Details tab?

**Comment by shrivatsahosabettu** [comment]
Please find the command line arguments for the rg.exe and let me know if this is a issue?

![vc code rg error](https://user-images.githubusercontent.com/12061573/36388796-06a91b54-15c3-11e8-8f7a-34b263ccebd5.png)

**Comment by chrmarti** [comment]
That looks like an extension searching for files through the extension API. (The workspaceContains trigger would use `--quite` as a command line argument.)

When you start using `--disable-extensions` these processes will not show up.

**Comment by chrmarti** [comment]
I have added logging to the upcoming 1.21.0 release that will tell us which extensions spawned the file searches. (#43605)
