### ISSUE TITLE
Integrated Terminal Opens files in Preview Mode

### ISSUE THREAD

**Issue by akras-apixio** [Microsoft/vscode#43856]
- VSCode Version: 1.20.1
- OS Version: OS X 10.11.16

When using integrated terminal, follow links open up in preview mode (one at a time) even though I have `"workbench.editor.enablePreviewFromQuickOpen": false,` in my settings. I expected this to work for integrated terminal, and if not to have a similar option for it.

Steps to Reproduce:

1. `git grep` for something in integrated terminal
2. Cmd + click to follow 2 or more links
3. Only 1 file will open at a time, unless file heading is double clicked (or something like that).

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@akras-apixio you can disable this globally via `"workbench.editor.enablePreview": false`, but I let @Tyriar decide if we want a setting only for the terminal.

**Comment by Tyriar** [comment]
I switched to pin the editors by default as this was the intent when I implemented the feature.
