### ISSUE TITLE
python.linting.flake8CategorySeverity.F should default to "Warning", not "Error"

### ISSUE THREAD

**Issue by danvk** [Microsoft/vscode#43851]
With flake8, the "F*" issues are labeled as errors by default (https://code.visualstudio.com/docs/python/linting#_flake8). 

I think this comes from a misunderstanding of what "F" (vs. "W" or "E") means in this context. For flake8, it means that these are issues flagged by pyflakes, rather than that these are fatal errors. See http://flake8.pycqa.org/en/latest/glossary.html#term-class

The upshot is that issues like unused imports are flagged as errors by default with pyflake, rather than as warnings. They should be warnings:

```json
{
  "python.linting.flake8CategorySeverity.F": "Warning"
}
```

- VSCode Version: Version 1.19.2 (1.19.2)
- OS Version: macOS Sierra 10.12.6 (16G29)

**Comment by usernamehw** [comment]
This issue should probably be filed into the python extension repo.

**Comment by danvk** [comment]
Sure, filed an issue over there.
