### ISSUE TITLE
visual effect issue when renaming multiple files 

### ISSUE THREAD

**Issue by cevn** [Microsoft/vscode#43855]
### Issue Type
Bug

### Description

1. Begin renaming one file. 
2. Right click another file and click rename.

The new Rename box will appear far off to the right of the original filename, instead of replacing the current filename. 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.14GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
elixir-ls|Jak|0.2.11
cql|Law|0.8.7
vscode-docker|Pet|0.0.24
scratchpad|awe|0.1.0
vscode-eslint|dba|1.4.5
tslint|eg2|1.0.27
Go|luk|0.6.76
vscode-elixir|mjm|1.1.0
vetur|oct|0.11.7
rust|rus|0.3.2
vscode-lldb|vad|0.7.5
vim|vsc|0.10.13
vscode-proto3|zxh|0.1.2

</details>
Reproduces without extensions

**Comment by egamma** [comment]
@cevn please provide a screenshot that illustrates the problem.

**Comment by cevn** [comment]
I can no longer repro, guess it was a once off.
