### ISSUE TITLE
Chrome debugger unable to connect to runtime process

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#43854]
### Issue Type
Bug

### Description

I'm following the Angular tutorial docs we have [here](https://code.visualstudio.com/docs/nodejs/angular-tutorial), and with the `launch.json`  provided I always get `Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a target that matches: http://localhost:4200. Available pages: ["file: ...`

The steps are
1. Create angular app with `ng new my-app`
2. Change to that directory and run `ng serve`
3. Open VSCode and open the my-app dir, create the default `launch.json` for Chrome
4. Change the port to 4200 so the launch config is
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
5. Run the debugger

If I add a port to the configuration, like 8000 or 8080, it's able to connect. Am I missing something? Is this expected behavior? Or do we just need to update the docs to say that a port should be added?

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T06:08:32.814Z)
OS version: Darwin x64 17.4.0

Reproduces only with extensions

**Comment by RMacfarlane** [comment]
Just tried this again - I must have had some other process that was interfering, I'm no longer seeing timeouts. If I run into this issue again I'll collect more info about what other processes are running, it would be nice to have a more actionable notification

**Comment by roblourens** [comment]
You probably had another process on that port. The rest of that error message ("available pages...") would have given a clue as to which one. Hopefully the new notifications UX helps.

Also I have a task to pick an unused port before launching which would have helped here.
