### ISSUE TITLE
How to autoindent Stylus?

### ISSUE THREAD

**Issue by iamdubx** [Microsoft/vscode#43859]
- VSCode Version: 1.20.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open Stylus file
2. Write `div`, hit Enter
3. It should autoindent new line

Is there any option to add autoindent in VS Code? For example, I write `div` and after I hit Enter I don't need to make Tab to write styles. This is so super annoying. I had all set up in Sublime, but can't solve it in VS Code. Please help.

**Comment by egamma** [comment]
VS Code doesn´t provide support for stylus. Please try this extension https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus and report issues or feature requests against this extension.
