### ISSUE TITLE
Workspace Settings does not recognize files.exclude

### ISSUE THREAD

**Issue by lepinekong** [Microsoft/vscode#43853]
- VSCode Version: 1.20.0
- OS Version: Windows 10 Pro on Surface Pro 5

Steps to Reproduce:

1. Open Workspace Settings 
2. Type "files.exclude"

Does this issue occur when all extensions are disabled?: Yes/No

![image](https://user-images.githubusercontent.com/5175342/36325416-0ab64bc6-1358-11e8-8dcf-e2dff7aebc6e.png)

**Comment by egamma** [comment]
The setting files.exclude needs to go into the settings section:
```
"settings": {
    "files.exclude"...
