### ISSUE TITLE
Predawn theme not coloring functions properly

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4386]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Install Predawn theme pack
2. Change to Predawn theme

Actual:
Functions are not colored properly. They appear as a single color throughout

![predawncolor](https://cloud.githubusercontent.com/assets/12900364/13860751/2bf2a5c6-ec47-11e5-9fcb-647abfcce553.JPG)

Expected:
Functions, variables, etc should be colored accordingly

E.g. 
![predawngfmarkdown](https://cloud.githubusercontent.com/assets/12900364/13860812/704c3214-ec47-11e5-873c-b018b4ec8a68.JPG)

**Comment by aeschli** [comment]
This has to do with #3008
