### ISSUE TITLE
Code fails to execute tasks, open terminals or new windows with no network connection

### ISSUE THREAD

**Issue by zsquareplusc** [Microsoft/vscode#43864]
- VSCode Version: 1.20.1 (started to get that problem around 1.19.0)
- OS Version: Win7

Steps to Reproduce:

1. no network (no cable, WIFI off)
2. starting a task fails with exit code 1, starting a terminal fails, tab closes immediately

Launching new code instances also fails:
```
> vscode\code.exe                                 
net.js:10                                                    
const cares = process.binding('cares_wrap');                 
                      ^                                      
                                                             
Error: EFILE                                                 
    at net.js:10:23                                          
    at net.js:1645:3                                         
    at NativeModule.compile (bootstrap_node.js:535:7)        
    at NativeModule.require (bootstrap_node.js:475:18)       
    at internal/child_process.js:6:13                        
    at internal/child_process.js:903:3                       
    at NativeModule.compile (bootstrap_node.js:535:7)        
    at NativeModule.require (bootstrap_node.js:475:18)       
    at child_process.js:12:23                                
    at child_process.js:542:3                                
```

Does this issue occur when all extensions are disabled?: Yes

I'm getting the same error with `--disable-extensions`  but even `-h` fails the same way in that situation. Everything works fine when there is a network connection.

**Comment by egamma** [comment]
@zsquareplusc regarding

>starting a task fails with exit code 1, starting a terminal fails, tab closes immediately

what kind of task are you starting, can you give an example?

**Comment by zsquareplusc** [comment]
@egamma sure, see below. But as opening a new terminal tab e.g. with the "+" button also fails, I do not suspect anything to be wrong with the tasks system. It seems to be a general problem with starting new processes in that situation.

Using the "+" button to start a terminal tab, it fails and shows a message at the top of the window, stating this: `Fehler beim Starten des Terminalprozessbefehls "C:\WINDOWS\system32\cmd.exe" (Exitcode: 1).`

Regarding tasks, I have 12 tasks, removed others for brevity:
```
{
    "version": "2.0.0",
    "echoCommand": true,
    "options": {
        "env": {
            "PYTHONPATH": "${workspaceRoot}/xxx"
        }
    },
    "presentation" : {
        "reveal": "always"
    },
    "type": "shell",
    "tasks": [
        {
            "taskName": "App: download-jtag",
            "command": "python -B -m pepper -c.vscode/current_project.json download-jtag",
            "problemMatcher": []
        }
    ]
}
```

Yields:
```
> Executing task: python -B -m pepper -c.vscode/current_project.json download-jtag <

Der Terminalprozess wurde mit folgendem Exitcode beendet: 1
```

**Comment by Tyriar** [comment]
It looks like this is the Windows issue https://github.com/Microsoft/vscode/issues/36630

**Comment by zsquareplusc** [comment]
I fail to see how that is related to 36630. The issue I experience has nothing to do with Python or Windows 10. In my case `code` can not be started without a network. In case it is already running it fails to start any additional tasks such as the integrated terminal or any tasks.

Maybe there is some option that can be used to debug the not-starting problem? Offline, not even `code -h` works (run in a cmd.exe on win7)... a traceback is visible in the first message of this thread.

**Comment by Tyriar** [comment]
@zsquareplusc that issue isn't just Python, it's primarily repro'd in Python though. But you're right as you're on Windows 7. What's in your settings.json?

**Comment by zsquareplusc** [comment]
Settings are shown bellow, but my guess it's none of these causing a problem, or are the settings read even for displaying help with `code -h`? Maybe the problem is in the underlying platform (electron), e.g. in the node.js that is bundled? 

global settings.json:
```
// Platzieren Sie Ihre Einstellungen in dieser Datei, um die Standardeinstellungen zu überschreiben.
{
    "editor.fontFamily": "'Dejavu Sans Mono', Consolas, 'Courier New', monospace",
    "terminal.integrated.fontSize": 13,
    "terminal.integrated.scrollback": 10000,

    "http.proxy": "https://<removed>",
    // "python.linting.flake8Path": "C:\\Python27\\Scripts\\flake8.exe",
    // "python.linting.pylintPath": "C:\\Python27\\Scripts\\pylint.exe",

    "git.path":"C:\\<removed>\\AppData\\Local\\Programs\\Git\\cmd\\git.exe",
    "git.autorefresh": false,
    "git.autofetch": false,

    "explorer.enableDragAndDrop": false,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,

    "editor.rulers": [80, 100, 120],
    "window.zoomLevel": 0,
    "workbench.iconTheme": "vs-seti",

    "editor.minimap.enabled": true,
    "git.confirmSync": false,
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": false,
    "editor.accessibilitySupport": "off",
    "C_Cpp.intelliSenseEngineFallback": "Disabled"
}
```

**Comment by zsquareplusc** [comment]
Now I can no longer reproduce the problem. There was a reboot and Windows updates in between.
Will close the issue for now. Though I still find it a bit strange that starting subprocesses seems to depend on networking...
