### ISSUE TITLE
Selection suggestions

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#43865]
### Issue Type
Feature Request

### Description

1. Fixed or optional ctrl+LMB support for continuous line selection (currently you need to click at each line you want to select).
2. Fixed or optional shft+LMB selection from last selected line (currently its always from first selected;).
https://youtu.be/lNaXDrcaUQw
3. Removed or optional draggingSelected by second click on line number.
https://youtu.be/S0Un4kOjUho

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.15063

**Comment by Ilias48rus** [comment]
When you want to select separate groups of lines, the easiest way to do this is to LMB select 1 and ctrl+LMB select the other groups, why after so much time the essential ctrl+LMB functionality are still not added?
