### ISSUE TITLE
Recent update can not move tabs around

### ISSUE THREAD

**Issue by DavidKindler** [Microsoft/vscode#43873]
### Issue Type
Bug

### Description

I used to be able to move file tabs around to the order that I want them.  I am unable to now and there is a CPU spike when I try doing so.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2591)|
|Memory (System)|7.89GB (1.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
es7-react-js-snippets|dsz|1.3.3
prettier-vscode|esb|1.1.3
vscode-versionlens|pfl|0.19.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by egamma** [comment]
@DavidKindler this works as expected for me in the stable version. 

Is there an error shown in the console (Help>Toggle Developer Tools, then open the Console tab)?

Since you indicate that this only reproduces with extensions, please narrow down which extension is causing the problem. To selectively enable/disable extensions pls see https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled.

**Comment by DavidKindler** [comment]
I disabled all extensions and problem persists.  No errors popping up in Console tab.

**Comment by egamma** [comment]
@DavidKindler please provide more information about the tab configuration when this happens. Please add some screenshots. What is the tab configuration that you want to customize, what do you want to change but doesn´t work.

**Comment by DavidKindler** [comment]
Here is a simple example of how I've been able to reproduce and possibly narrow down the issue.
First disable all extensions and reload.
Create a new directory and open empty folder in VSC.  Create two new files but do not save them.  Attempt to move tabs using mouse - this works.
Create two files and save them.  In my case they were test1.js and test2.js with one commented line.
Try to move the saved files tabs around - does not work. 
But I can still move the unsaved files tabs.

Hope that helps.  I can do a screencast if  you need one,

**Comment by egamma** [comment]
@DavidKindler followed your steps and I can move test1.js and test2. js. Please provide a screencast.

![image](https://user-images.githubusercontent.com/172399/36353156-d8a666ea-14c2-11e8-9ef7-a4f22e78ea3c.png)
![image](https://user-images.githubusercontent.com/172399/36353159-dec48732-14c2-11e8-8f0a-9ade1b229ef4.png)

**Comment by DavidKindler** [comment]
![2018-02-18_09-02-43](https://user-images.githubusercontent.com/1718785/36353376-7302f772-148b-11e8-8bb7-42fa4959de98.gif)


Attached screencast.  You can see that when I try to move the saved versions the editor shows "Not responding" after a few secs. 
https://github.com/Microsoft/vscode/issues/10066
I think this might be related issue but I have not found out how to run in non-admin mode.

**Comment by DavidKindler** [comment]
@egamma - I have been able to resolve this issue by reinstalling a fresh copy of vscode.
Closing out issues.  Thanks.
