### ISSUE TITLE
Alt+click(mac)/ctrl+click(win/linux) on terminal + panel action should split active terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#43877]
This was a suggestion from @isidorn, forking off from https://github.com/Microsoft/vscode/issues/7504

**Comment by isidorn** [comment]
@Tyriar sorry for the slow response, this somehow fall under my radar.
I pushed the change, it works nicely. However feel free to restructure my commit as I might have forgot about some corner case. My commit is basicaly an examply how to do it :)
