### ISSUE TITLE
Configure Language to pt-br not works

### ISSUE THREAD

**Issue by felipetac** [Microsoft/vscode#43870]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. View
2. Command Palette...
3. Configure Language
4. locale: "en" to locale: "pt-br"

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
A translation for pt-br is not supported by VS Code. Please see this project https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project for how to contribute to translations.
