### ISSUE TITLE
Free memory of bug reporting seems off on Mac sierra

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#43885]
### Issue Type
Bug

### Description
How are you calculating free memory on Mac Sierra?  It feels a bit off.  Should it be close to Activity Monitor?  The new bug reporting is 👌 

![image](https://user-images.githubusercontent.com/2301847/36340642-1c11ff18-139f-11e8-9ca6-6b8ef3f456db.png)

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (135d4a5d5cecd82e9e4da7ede655fb09af0dac35, 2018-02-14T06:09:28.551Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|/private/var/folders/90/lpgkdnnj293gmdz2pds2pm3w0000gn/T/AppTranslocation/C1EF80CB-B78A-4648-A359-F116D0267978/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
@joshunger we use node.js: https://nodejs.org/docs/v7.9.0/api/os.html#os_os_totalmem
