### ISSUE TITLE
Inability to use the input method on Ubuntu 17.10

### ISSUE THREAD

**Issue by junhwong** [Microsoft/vscode#43881]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.13.0-32-generic
- Extensions: none
---

Can not type Chinese on ubuntu 17.10, and other software is OK. 

i tried use IBUS and fcitx all both not work!

**Comment by junhwong** [comment]
I found the reason, is to run the snap version, switch to another version successfully.
However, my installation is to use the official website to download the package, it looks the same name after installation! ! !
This is also a problem, snap version can not use the input method.

**Comment by Tyriar** [comment]
@junhwong do you mean the vscode snap doesn't work with IMEs? I'll merge this into https://github.com/Microsoft/vscode/issues/5458

FYI @flexiondotorg
