### ISSUE TITLE
Allow to sort folders of a workspace

### ISSUE THREAD

**Issue by AlexRouSg** [Microsoft/vscode#43889]
When adding multiple workspaces, the folders show up in the order they were added. This can get annoying/confusing over time when trying to find a folder in a long list.

I suggest there should be a way to automatically sort alphabetically and/or manual reorder of the workspace folders.

**Comment by iciclesoft** [comment]
I've created an extension with which you can sort these folders alphabetically that can be used until it's fixed in VSCode. Search for the extension WorkspaceSort or view the source on [GitHub](https://github.com/iciclesoft/workspacesort-for-VSCode).
