### ISSUE TITLE
Adding a .gitignore and saving does not update the pending changes badge in the activity bar

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#43884]
### Issue Type
Bug

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (135d4a5d5cecd82e9e4da7ede655fb09af0dac35, 2018-02-14T06:09:28.551Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|/private/var/folders/90/lpgkdnnj293gmdz2pds2pm3w0000gn/T/AppTranslocation/C1EF80CB-B78A-4648-A359-F116D0267978/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
@joshunger What does `git status` return before you add the `.gitignore` file? What does it return after you add the `.gitignore` file? VS Code shows you exactly the same.

**Comment by joshunger** [comment]
@joaomoreno does this answer your questions?

![git-status-bug](https://user-images.githubusercontent.com/2301847/36378068-9e5f7836-1536-11e8-847f-4f4bea15b254.gif)

**Comment by joaomoreno** [comment]
If you open that folder in Code, after the point in time that gif ends, do the files inside `node_modules` appear?

**Comment by joshunger** [comment]
No because it forces a refresh when you open right?

**Comment by joaomoreno** [comment]
Do any other changes to your workspace cause the activity bar to update?

**Comment by joshunger** [comment]
I don't know @joaomoreno can you elaborate?

**Comment by joshunger** [comment]
@joaomoreno do you need more info?  I don't have permission to remove the label?

**Comment by joaomoreno** [comment]
What I mean is: if you make changes to the folder you have opened in Code using the Windows Explorer, does Code reflect those changes (eg delete a file)?

Also, if you run the `Git: Refresh` command, does the activity bar update?
