### ISSUE TITLE
open in default browser not working, and opening file from bash or finder is not reading as a JS file, it is reading as plain text 

### ISSUE THREAD

**Issue by JHolder17** [Microsoft/vscode#43897]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
open-in-browser|tec|1.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
This functionality is provided by the open-in-browser extension and not by vscode. Please report this behaviour against the open-in-browser extension.
