### ISSUE TITLE
Allow configuration of quotemark inserted by auto import suggestion (feature request)

### ISSUE THREAD

**Issue by codestothestars** [Microsoft/vscode#43895]
Currently, modules added using auto import suggestions are always added using double quotes `"`, which, if TSLint is configured to require single quotes `'`, always results in a TSLint error that needs to be fixed. It would be nice if the type of quote inserted was configurable, perhaps with something like `typescript.autoImportSuggestions.quotemark`.

<img width="802" alt="pre-import" src="https://user-images.githubusercontent.com/9933525/36343926-c5fe2f56-13e0-11e8-8eda-4058c4a2d626.png">

<img width="366" alt="post-import" src="https://user-images.githubusercontent.com/9933525/36343925-c5f085d6-13e0-11e8-9793-033c4026e99a.png">

**Comment by codestothestars** [comment]
If maintainers agree and nobody else jumps on it, I'll be happy to work on a pull request.

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/20619 which is on track for the march release. I'm afraid we need to fix this upstream so there's nothing you can do at the moment

**Comment by codestothestars** [comment]
Okay, sounds good anyway. Thank you!
