### ISSUE TITLE
Not able to open the VSCode

### ISSUE THREAD

**Issue by Tapudp** [Microsoft/vscode#43898]
- VSCode Version: latest (don't know because wasn't able to open and check it)
- OS Version: Windows 10 Version 1709 (OSBuild 16299.192)

Steps to Reproduce:

1. I don't know how but it just appeared I was able to open VSCode just before few hours.

![vscode error](https://user-images.githubusercontent.com/8810813/36344254-7c81f4f4-143d-11e8-919e-6e97af29e165.JPG)

Does this issue occur when all extensions are disabled?: Don't know

**Comment by bpasero** [comment]
@Tapudp maybe do a full uninstall followed by a reinstall
