### ISSUE TITLE
Color Emoji Agility

### ISSUE THREAD

**Issue by zero-master** [Microsoft/vscode#43899]
- VSCode Version: 1.20.0
- OS Version:  Linux z97 4.14.15-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux

Steps to Reproduce:

1. Paste this color emoji in vscode terminal:  🤔
2.  You'll get this agility effect

![image](https://user-images.githubusercontent.com/1130261/36344314-7298dafa-1453-11e8-858c-972ffe987b64.png)

![image](https://user-images.githubusercontent.com/1130261/36344329-d61a6634-1453-11e8-8389-e92afef07cce.png)

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by Tyriar** [comment]
This is as designed, here's iterm for example:

<img width="49" alt="screen shot 2018-02-21 at 10 48 44 am" src="https://user-images.githubusercontent.com/2193314/36498999-dacd5cf6-16f4-11e8-92b7-387f961c918e.png">

I do notice that Terminal.app on mac has a better experience though where emoji are now treated as proper wide characters. I'll merge this issue into https://github.com/xtermjs/xterm.js/issues/1059 which is tracking problems with emoji in the terminal.
