### ISSUE TITLE
feature request: create folder containing selected files

### ISSUE THREAD

**Issue by literalpie** [Microsoft/vscode#43890]
Now that multiple selection is possible in the browser (Yay!)

Similar to the feature in MacOS Finder "Create folder with selection", it would be nice if there was a way to select multiple files/folders in the browser, right click, and easily create a folder that contains those files and/or folders.

**Comment by isidorn** [comment]
This can be done in an extension. If somebody is willing to do an extension I can provide some pointers.

**Comment by literalpie** [comment]
Okay. Thank you for considering it, and for being willing to say no to this issue and others like it. I'm sure that's what makes VS Code such a great editor!

Maybe I will look into making the extension. It could be a fun little project.
