### ISSUE TITLE
Should repeating code folding key board commands Ctrl+k, Ctrl+<number> unfold code?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#4389]
- VSCode Version:code-alpha 
- OS Version:Windows 7

Steps to Reproduce:

1. Ctrl+k, Ctrl+<number> folds code at a specified level
2. Ctrl+k, Ctrl+<number> does nothing.  Should this unfold at that level?

**Comment by aeschli** [comment]
It's Ctrl+k, Ctrl+ **2** (or any number from 1 to 5)

It collapses all regions of the given nesting level in the whole document, except for the region that cursor is in (it stays unchanged)

**Comment by aeschli** [comment]
Ah now I realise that the numbers got cut await from your description.

The actions are only supposed to fold, not unfold. To unfold you would use Unfold all (Ctrl+K, Ctrl+J)
