### ISSUE TITLE
Allow dragging a folder over the label of the project's root directory in explorer

### ISSUE THREAD

**Issue by Kaba2** [Microsoft/vscode#43896]
### Issue Type
Feature Request

### Description

The process of moving a directory up the directory-hierarchy in explorer differs depending on whether the directory is to be moved to the root directory or to a non-root directory. For a non-root directory A, I can grab a sub-directory B, and drag it _upwards_ over the label of the directory A. However, for the root directory, doing the same does nothing. Instead, one has to drag the directory _downwards_ all the way down to the empty space after all files and directories. The request is to allow dragging a folder over the label of the project's root directory, with the usual semantics of moving the sub-directory to the root-directory.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment]
This works in the latest vscode insiders.
Fixed as part of https://github.com/Microsoft/vscode/issues/29715
