### ISSUE TITLE
setDebuggerLinesStartAt1() and setDebuggerColumnsStartAt1() seem to have no effect.

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#43894]
### Issue Type
Bug

### Description

I'm working on a custom debugger for my extension and I found the following issue:

Setting `setDebuggerLinesStartAt1()` and `setDebuggerColumnsStartAt1()` seem to have no effect. Regardless of the value I set the debug indicator (both for the current line as well the one for positions in that line) is always put at the same place. I would expect the debug marker position changes depending on the flag I set for these methods.

I call the methods in the c-tor of my debug session:

```typescript
export class AntlrDebugSession extends LoggingDebugSession {
    /**
	 * Creates a new debug adapter that is used for one debug session.
	 * We configure the default implementation of a debug adapter here.
	 */
    constructor(
        private folder: WorkspaceFolder,
        private backend: AntlrLanguageSupport,
        private grammar: string,
        private consumers: DebuggerConsumer[]) {
        super("antlr4-vscode-trace.txt");

        // This backend uses one-based lines and zero-based columns.
        this.setDebuggerLinesStartAt1(true);
        this.setDebuggerColumnsStartAt1(false);
    }
...
```

My stacktrace creation code looks like this:

```typescript
    protected stackTraceRequest(response: DebugProtocol.StackTraceResponse, args: DebugProtocol.StackTraceArguments): void {

        const startFrame = typeof args.startFrame === 'number' ? args.startFrame : 0;
        const maxLevels = typeof args.levels === 'number' ? args.levels : 1000;

        const stack = this.debugger.currentStackTrace;
        let frames: StackFrame[] = [];
        for (let i = 0; i < stack.length; ++i) {
            let entry = stack[i];
            // At the moment our setting for the columns-starts-at-1 above doesn't seem to have any impact.
            let frame = new StackFrame(i, entry.name, this.createSource(entry.source),
                entry.next[0].start.row, entry.next[0].start.column + 1);
            frames.push(frame);
        }
        response.body = {
            stackFrames: frames,
            totalFrames: stack.length
        };
        this.sendResponse(response);
    }
```

If there were no space
### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4009)|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (16.05GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.3.0
dot|Ste|0.0.1
numbered-bookmarks|ale|0.11.0
spellright|ban|2.1.18
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.5
duk-debug|des|0.4.2
gitlens|eam|8.0.0
tslint|eg2|1.0.27
php-intellisense|fel|2.2.8
live-html-previewer|hdg|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
svg|joc|0.0.9
vscode-phpfmt|kok|1.0.18
vscode-antlr4|mik|1.2.9
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.1.0
vscode-yacc|se2|1.1.0

</details>
Reproduces without extensions

**Comment by weinand** [comment]
Your "stackTraceRequest" code lacks calls to `convertDebuggerLineToClient(...)` and `convertDebuggerLineToColumn(...)`.

These two inherited utility methods take care of converting the line and column values based on the frontend and DA configuration for the DA -> frontend direction.

See https://github.com/Microsoft/vscode-mock-debug/blob/263136c3d66280475ea31992df23eeea33f6a6b6/src/mockDebug.ts#L179.

The symmetrical methods `convertClientLineToDebugger(...)`and `convertClientColumnToDebugger(...)` must be used for the reverse direction: frontend -> DA.
See https://github.com/Microsoft/vscode-mock-debug/blob/263136c3d66280475ea31992df23eeea33f6a6b6/src/mockDebug.ts#L146.

Similar conversions are need for source paths (`convertDebuggerPathToClient(...)`and `convertClientPathToDebugger(...)`).
See https://github.com/Microsoft/vscode-mock-debug/blob/263136c3d66280475ea31992df23eeea33f6a6b6/src/mockDebug.ts#L292.

**Comment by mike-lischke** [comment]
I wish these functions were documented somewhere. How can we know which APIs are important? Also, why does `DebugSession` not call those implicitly? If they are required to make everything working as intended, they shouldn't need any action from the extension writer.

**Comment by weinand** [comment]
No, they are not required. And they are not API.
The only things that is required is to adhere to the [protocol](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json).
The existence of the adapter node module is just a courtesy to those few debug adapter authors that write an Adapter in JS/TS. Please use mock-debug to learn how you can write a DA.

**Comment by mike-lischke** [comment]
Thanks Andre.
