### ISSUE TITLE
Regardless of order, new context menu entries on document show above 'Command Palette'.

### ISSUE THREAD

**Issue by JokerDan** [Microsoft/vscode#43892]
- VSCode Version: Stable | Jan - 1.20.1
- OS Version: Windows 10 - V.1709 | Build 16299.192

Steps to Reproduce:

1. Have extension with commands registered on the document context menu.
2. Have no x in '{x}_group@{y}' set - appears below 'Command Palette'
3. Have x in '{x}_group@{y}' set - appears above 'Command Palette', no matter the value.

Does this issue occur when all extensions are disabled?: Yes/No - N/A, Need extension

---

Even with a ridiculously high group order set, my option appears above the 'Command Palette' 'group'.
"group": "9999999_command@1"

Here is with the group set on the command to 9999999_;

![vscode-context-2](https://user-images.githubusercontent.com/1098786/36343121-f418f910-13ff-11e8-9e8b-5fe82820219b.png)

And without;

![vscode-context-1](https://user-images.githubusercontent.com/1098786/36343119-f054217e-13ff-11e8-814e-c18e5e0031f0.png)

---

I raise this because, I would like my commands to show below the Palette option.

I am using this as a reference, which does not state the group of the Command Palette.
[VSCode Extension API - Sorting of groups.](https://code.visualstudio.com/docs/extensionAPI/extension-points#_sorting-of-groups)

I am unsure if this is more of an issue, or feature request that the 'Command Palette' option is given a group order that can be worked around?

Also to note, even when left out of a group but given an in-group order, they then appear in their own group above the Command Palette option.

**Comment by jrieken** [comment]
Sorting is lexicographical and `9` comes before `a` or `z`. Numbers should be used after the `@`-sign to denote the order inside a group. 

<img width="231" alt="screen shot 2018-02-26 at 15 01 03" src="https://user-images.githubusercontent.com/1794099/36674288-e0bdd46e-1b05-11e8-89bd-b1415156e90e.png">

**Comment by JokerDan** [comment]
@jrieken This does not help with the ability of having my extensions commands appear _below_ the 'Command Palette...' option within the editors context menu.

As per https://code.visualstudio.com/docs/extensionAPI/extension-points#_sorting-of-groups

> The editor context menu has these default groups:
> 
> * navigation - The navigation group comes first in all cases.
> * 1_modification - This group comes next and contains commands that modify your code.
> * 9_cutcopypaste - The last default group with the basic editing commands.

Yet none of these contain the Command Palette and thus, no extensions commands can come after/below the command palette option in the context menu, but be ordered via a inside-group order.

Currently, the only way of having a command appear below the command palette option, is to **not give it any at all**. If you give it either/both a group or inside-group group, the option will appear right above the command palette option as its own group, or in the group order you define prior to the underscore.

This is inconsistent behaviour and does not give us control on ordering extension commands below the command palette option.

Examples;
"group": "" 
(Appears below command palette, no commands have ingroup orders)

"group": "@1" 
(Appears at the top of my context menu (I don't have any navigation options for the language), has ingroup order, so all of my extensions menu entries can be ordered)

"group": "8_@1" 
(Appears above the cutcopypaste group and below modification, **as expected.** Has in group ordering)

"group": "89_@1" 
(Appears above cutcopypaste group still... Driven off first digit? Has in group ordering)

"group": "99_@1" 
(Appears below cutcopypaste group but above command palette group... Has in group ordering)

This ordering may be an issue with putting things at the top of the context menu too as according to the docs navigation does not have a {x}_ group order. (None of the navigation commands are showing due to not being implemented for the language we use so I can not verify this).

Out of curiosity and as per your response of '9' > 'z' being false, I tried combinations of 'z_' and '@z' - Still always above the command palette options in the context menu.

Even though it is not a huge issue in terms of functionality as people will get used to where they are, having the ability to completely control the order the context menu between the default options and extension contributions would be nice.

**Comment by jrieken** [comment]
True. That's because the 'Command Palette...' doesn't define its groups nor an order inside the missing groups. In those cases we append them to the end. This came in via 635ace77e97d830f9cd2ad5b238ed6c3be18e151 - @bpasero Please define a group et al and update the docs we have around this.

**Comment by bpasero** [comment]
@jrieken [using](https://github.com/Microsoft/vscode/commit/f5ab5d6a8b3abc8462c68fcdf6af839ff54dc897#diff-b90278b8812101a32d844114fa0dc752R197) group id `commands` now with order `1`, let me know if you want another ID.

**Comment by jrieken** [comment]
Hm, maybe prefix a number like `9_commands` to make sure this group comes low and to align with others: https://code.visualstudio.com/docs/extensionAPI/extension-points#_sorting-of-groups. The order is just the order of the command in that group, in  package.json `9_commands@1`

**Comment by bpasero** [comment]
@jrieken shouldn't it be `10_commands` then to make sure to be after the cut/copy/paste group?

**Comment by JokerDan** [comment]
@bpasero That is how I would imagine it should be too, but as per my examples above, "89_@1" was still below "9_" cut/copy/paste group which again contributed to the inconsistent/unexpected behaviour of command ordering.

**Comment by JokerDan** [comment]
I just gave one of my extensions the group `10_commands` much like the fix for Command Palette group.

In this case, the only command I am showing is 'Compile Logic' and it is above the cut/copy/paste command section. Maybe internal commands work differently but extensions seem to be driven off the first character only for the main grouping?

![image](https://user-images.githubusercontent.com/1098786/36784451-54495792-1c77-11e8-9fa3-9b1de907e928.png)

**Comment by jrieken** [comment]
Yeah, it sort alphabetically... So 10 < 2 etc. Maybe `z_commands`?

**Comment by JokerDan** [comment]
Either that, or 'A' so it is below VSCode internal commands but extensions can have commands in the context menu below it.

**Comment by mjbvz** [comment]
Hey, I tried verifying this but still wasn't able to get a custom command to show below the command palette item. Is this expected? What group ids should I be using to test this?

**Comment by JokerDan** [comment]
@mjbvz Because the Command Palette was given a group of 'z_commands' you need to give your extension a higher grouping for it to appear below the 'Command Palette' group.

For instance I have now given some of my extensions command contributions the group 'z1' with '@' used for their in  group ordering, and they appear below the Command Palette's 'z' group. 

(This is on the latest insiders build)

**Comment by mjbvz** [comment]
Thanks @JokerDan! Verified this works using that group
