### ISSUE TITLE
Color Picker is not working

### ISSUE THREAD

**Issue by pranshuchittora** [Microsoft/vscode#43891]
### Issue Type
Bug

### Description

Color picker is not showing up as before , after the latest update.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.13.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1895)|
|Load (avg)|2, 1, 1|
|Memory (System)|3.75GB (0.11GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.3.0
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.2.2
vscode-color|ans|0.4.5
cpptools|ms-|0.15.0
js-atom-grammar|ms-|0.1.14
debugger-for-chrome|msj|4.1.0
LiveServer|rit|3.2.0

(3 theme extensions excluded)

</details>

**Comment by egamma** [comment]
Cannot reproduce given the provided information. Please provide more information about what was working and now isn´t working in this release.

**Comment by greg-wolff** [comment]
Also got this problem.

On VS Code 1.20.1
OS: MacOS High sierra 10.13.3

My VSCode is pretty vanilla, but still in CSS files or other areas where VS renders hex codes and displays a colored block. Usually, clicking (or I think hovering?) on the colored block allows you to change the hex code via a color picker UI. Currently, clicking or hovering does nothing. No way to access the color picker now.

**Comment by pranshuchittora** [comment]
![vscode_issue](https://user-images.githubusercontent.com/32242596/36356864-2f95689c-151e-11e8-815b-1e9c01f9b593.png)

I am talking about that small square box before the color code . Previously , when we hover cursor over it color pallet appears and we can play with the colors easily , which is not activating in this new release.

**Comment by shobhitchittora** [comment]
Refs: #42720
