### ISSUE TITLE
`ext install` is slow

### ISSUE THREAD

**Issue by sijad** [Microsoft/vscode#439]
`ext install` is slow with slow internet connection to fetch extensions list, is this possible cache the results?
or use git instead of fetch list every time ([vsoGalleryService.ts](https://github.com/Microsoft/vscode/blob/6e94b27e06cef23a84fca0aff18b7702dc670014/src/vs/workbench/parts/extensions/node/vsoGalleryService.ts#L85))?

**Comment by sijad** [comment]
[Sublime Package Control](https://packagecontrol.io/) can be a good example which uses git
[package_manager.py](https://github.com/wbond/package_control/blob/master/package_control/package_manager.py#L333)

**Comment by jeffallen** [comment]
I'd second this. It is so slow as to be unusable for me in Kyrgyzstan, though it only took me a few minutes to download the 61 meg distro. I type "ext install", then get a sliding blue bar and nothing else. Can't find any way to see what's happening. Wireshark says there is a long slow HTTPS session happening to marketplace.visualstudio.com.

**Comment by sijad** [comment]
is it ok to use IStorageService for caching in this case?
I'd work on this but I'm not sure if you have plan for this or not

**Comment by egamma** [comment]
@sijad We haven't started on the December plan, yet. We are currently busy with catching up/recovering with all the feedback since the OSS announcement.

**Comment by joaomoreno** [comment]
Improved the extension query by reducing the amount of information needed from the server. Current query seems to take between 300 and 500ms on a fast internet connection. Total data is around 100k gzipped.

**Comment by jrieken** [comment]
@joaomoreno Dude still ~2sec for me

**Comment by jrieken** [comment]
[Untitled.mov.zip](https://github.com/Microsoft/vscode/files/64180/Untitled.mov.zip)

**Comment by joaomoreno** [comment]
Yep. Better than 10 seconds, which was the before time. Also, from the office it always takes longer, don't really know why.

**Comment by egamma** [comment]
Just  did it from home and it took between 1-2 seconds.

**Comment by sijad** [comment]
can it be a server side problem?

**Comment by sijad** [comment]
this took around 13 sec for me:
```
curl "https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery" --data '{"filters":[{"criteria":[{"filterType":1,"value":"vscode"}]}],"flags":133}' -H "Accept: application/json;api-version=3.0-preview.1" -H "Content-Type: application/json" --compress -v
```

**Comment by joaomoreno** [comment]
`.04s user 0.01s system 2% cpu 1.899 total` here

Depends very much on the moment, time of day, location, etc.

**Comment by jrieken** [comment]
I verified it takes 1-2 seconds ;-)

**Comment by warpdesign** [comment]
It takes around 5sec here, on a quite fast connection, no matter when I'm trying it during the day.

I still find it quite slow. I wouldn't be against having immediately cached results and updated one after 5 seconds.

Within Code there is nothing that takes that much time. Even find in files takes less time to give some feedback.

Switching to another app while it searches will immediately stop the search too.

**Comment by jrieken** [comment]
I agree, it's unhappy esp with cancel on focus loss model. For the future, the extension UI should move into a different slot, like a viewlets or editors

**Comment by prashaantt** [comment]
For me it's painfully slow at over 1 minute every time on my 8 Mbps line, which I don't think is all that bad by itself. After trying several times over the past few weeks I thought extensions is broken and started googling for help. But today I let `ext install` do its thing while I went away from the computer for a bit and came back to see the extensions list load up for the first time. I've since repeated the same on both my Macs with the same result.

@sijad's `curl` is pretty quick for me though, just in case that makes any sense.

**Comment by egamma** [comment]
@prashaantt did you also try this on 0.10.4? https://github.com/Microsoft/vscode/wiki/December-Pre-Release.
The query has been improved in this version.

**Comment by prashaantt** [comment]
@egamma Thanks for the tip about the insiders channel, I got the 10.5 and it's a huge improvement at a little over 20 sec, but still nowhere near the ~2 seconds others are experiencing here. Perhaps there's still room for improvement.

Thanks for the already great work on this IDE, by the way.

**Comment by egamma** [comment]
@prashaantt thanks, reopening the issue.

**Comment by joaomoreno** [comment]
This has been fixed for the next release
