### ISSUE TITLE
Add a "Reveal in Side Bar" button under sidebar actions

### ISSUE THREAD

**Issue by bschlenk** [Microsoft/vscode#43907]
Intellij has a button to reveal the currently open file in the project explorer. I think having this functionality in VSCode would be much more useful than the current option of right clicking the editor tab and selecting `Reveal in Sidebar`. This would be especially useful when having `explorer.autoReveal` set to false.

Here is a screenshot of the button in intellij (sorry for the terrible quality):
![intellij](https://user-images.githubusercontent.com/1390303/36347136-85ccfa1a-1404-11e8-8f5f-6c80d653ac08.png)

**Comment by isidorn** [comment]
Thanks for your suggestion however I am not convinced we need this action. Especially not in such a prominent place.
Also this action is already exposed to keybindings, so users can trigger it wihout the icon.
`workbench.files.action.showActiveFileInExplorer`

VSCode is also a minimalistic editor unlike IntelliJ and we only add the very important actions to not clog the UI.

In the future it is always better to first create a feautre request, start a discussion and only then provide a PR. Not, the other way around.

**Comment by bschlenk** [comment]
Are hooks exposed for this kind of thing to be added as an extension? Whenever I’m in need of the reveal in sidebar action, I’m already holding my mouse and navigating the file tree. That’s why I think it makes much more sense as an easy to reach button rather than a keyboard shortcut.

**Comment by isidorn** [comment]
No, the explorer title area is not exposed to the extensions.
The tab title area is exposed, however it already contains this action.
Also the explorer is exposed, however it does not make sense to add it there.

**Comment by bschlenk** [comment]
Perhaps the button could only be enabled if `explorer.autoReveal` was set to false, since that’s the only situation where it would be useful?

**Comment by isidorn** [comment]
Yes the button only makes sense in that situation.
However in the title area we do not remove actions, but only disable / enable them. So it would still take up space.

All in all, we will not add this in the near future. Sorry.

**Comment by erikflima** [comment]
To Add a "Reveal in Side Bar" button would be great!

**Comment by draconisNoctis** [comment]
FYI: There is a "Reveal" extension which adds the requested button.
