### ISSUE TITLE
No normal identification of EOF symbols

### ISSUE THREAD

**Issue by super-vip** [Microsoft/vscode#43906]
- VSCode Version:1.20.1
- OS Version:win10 64bit

Steps to Reproduce:

1. Create a new shell script file.
2. Enter the following test code:
```
#!/bin/bash
cat > test_file << 'EOF'
#!/bin/bash
echo "test"
if [ -f "test_file" ] ; then
    echo "yes"
else
    echo "no"
fi
EOF
echo "This a test code."
```
3. The editor does not normally identify the EOF terminator that causes subsequent incorrectly coloring of the code.

Does this issue occur when all extensions are disabled?: No

**Comment by egamma** [comment]
Please provide the steps for how to reproduce this issue in English.

**Comment by aeschli** [comment]
This got fixed by the latest update of the grammar (https://github.com/atom/language-shellscript/pull/105)
