### ISSUE TITLE
Close All should not stop when unsaved files encountered

### ISSUE THREAD

**Issue by mschipperheyn** [microsoft/vscode#43909]
One of the features I loved on Atom and dearly miss on VS Code is when you Close All or Close Others and there are unsaved files. On VSCode it will prompt you to save the file and force you to do that first. Extremely annoying. On Atom, it will close all the files it can and not the files it can't and give you a warning. Love that! Please implement this simple but very usable feature

**Comment by recidive** [comment]
There's a "Close Unmodified" option in the context menu on tabs and tab bar ("..." button on the right). It helps, but there's not a "Close Unmodified to the Right" or "Close Others Unmodified" equivalents.

**Comment by maheshambiga** [comment]
Close the window by clicking on the x button, it will show one single dialog to "Save All" or "Cancel All".

**Comment by renatomariscal** [comment]
I did something accidentally, which left me with 72 open unsaved files.
I don't know how to get rid of them without having to click 1 by 1 in "Don't save" prompt.

Closing the whole window and reopening brings it back. I don't see anything obvious on `~/.vscode`, neither inside the project.

**Comment by IAmdeGroot** [comment]
Same here @renatomariscal  :/
