### ISSUE TITLE
C/C++: Language identifier identifies C's .h files as C++ syntax highlighting doesn't work as a result

### ISSUE THREAD

**Issue by EbukaObizoba** [Microsoft/vscode#43904]
- VSCode Version: 1.20.1
- OS Version: Windows 10 1709

Steps to Reproduce:

1. Open C .h file with code in between an #ifdef and #endif macro
2. The chunk of code in between the preprocessor will be grayed out (no syntax highlighting), and the
     language mode will now be C++ instead of C.
3. Changing the file.associations settings in User/Workspace settings can fix the incorrect C++ file 
    association, but it does not fix the lack of syntax highlighting.

**Comment by egamma** [comment]
Please report the issue against the C++ extension https://github.com/Microsoft/vscode-cpptools
