### ISSUE TITLE
Interactive Playground - IntelliSense not working as expected.

### ISSUE THREAD

**Issue by baileyn** [Microsoft/vscode#43900]
- VSCode Version: 1.21.0-insiders and 1.20 (a little)
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Open `Interactive Playground`
2. Go to `IntelliSense` section.

Does this issue occur when all extensions are disabled?: Yes

The issue is that in the IntelliSense section, it states "In the below example, position the text cursor in front of the error underline," but in neither version is there an error underline.
![look](https://user-images.githubusercontent.com/6194343/36344320-9ddd51ea-13e6-11e8-8906-871f807ee82f.png)

With the the Insiders version, ctrl-space doesn't seem to bring up autocomplete candidates.
![ctrl-space](https://user-images.githubusercontent.com/6194343/36344319-9789b6c6-13e6-11e8-9f77-8071ae1f0bb7.PNG)

Compared to v1.20 which does.
![ctrl-space-work](https://user-images.githubusercontent.com/6194343/36344336-ef64d164-13e6-11e8-8cda-50a5b5e5a1a2.png)

**Comment by baileyn** [comment]
Upon further testing with the other examples, I think it has to do with the interactive editor each example is running in. 

If I take the exact same code in the interactive editor and move it to a file, it works exactly as expected. The same result is achieved in the "Refactoring" section. It won't work in the interactive editor, but it works when moved to a file on its own.

**Comment by chrmarti** [comment]
Reproduces on Windows. Works fine on Mac.

**Comment by Xceno** [comment]
I work with TypeScript (2.7.1) on various react apps and have the same problem everywhere, on all my machines (windows). This isn't only a problem in the interactive playground.

**Comment by chrmarti** [comment]
@Xceno Is this with 1.20.1 or with 1.21-insiders? /cc @mattbierner

**Comment by Xceno** [comment]
@chrmarti This is happening with 1.20.1.

```
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Sidenote: I've forgotten that my VSCode is synced on every PC and got quite a lot of extensions installed. So maybe it's an extension Problem. I'll try disabling them one by one and report back here.

**Comment by Xceno** [comment]
Update: Okay so I've disabled all extensions and I still got the issue. I noticed however, that this is mainly happening when writing `JSX` / `TSX`.

![image](https://user-images.githubusercontent.com/1850967/36412693-97c6232c-161b-11e8-8d25-8f1374718dd0.png)

**Comment by chrmarti** [comment]
@Xceno Could you open a new issue? This seems to be a different problem.
