### ISSUE TITLE
Support opening a folder as a workspace where each child becomes a workspace folder

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43902]
Since VS Code added multi-root support, I've told my users to use this for opening multiple "projects" to work on, since this avoids me having to walk down the tree trying to guess which folders are "projects" and also lets them have their own `launch.json`/`settings.json`/etc.

However, the same question keeps coming up - "why can't I just open my repo root and you treat my sub-folders as projects?".

Given how common this layout is, it seems like maybe Code could support it better. Rather than making the user maintain a `.code-workspace` folder that just lists every folder inside their repo, why not allow us to "open a folder as a workspace" which basically just adds every child folder as a workspace folder (eg. creates a throwaway `.code-workspace` file in memory that has all of the children in it but does not prompt to save - however the user can choose to save it if they wish, eg. if they'd removed some folders they didn't want).

**Comment by AlexRouSg** [comment]
Would be nice if adding/removing folders from the workspace folder be updated in code too. Kinda annoying if we have to reopen a workspace folder to update.

**Comment by JokerDan** [comment]
The multi-root workspace is still fairly new feature but agree it could do with a bit more customization in what we can do with it.

It would be nice to have something like the following;

```
"folders": [{
	"rootFolder":
		"path": "S:\\Path\\To\\WorkspaceRoot",
		"projects": [{
			"relativePath": "\\project1\\",
			"name": "First Project"
		},{
			"relativePath": "\\project2\\",
			"name": "Second Project"
		}]
}
```
Or how it works now but 'rootFolder' a property and if it is present and not empty, it requires projects to be set up?

**Comment by DanTup** [comment]
@JokerDan I'm not sure how what you're proposing differs from what we have today. My request is that a user doesn't need to add all of the folders to a workspace. Having a repo with many projects as the same level is very common, so being able to open a workspace that is all of those folders in one go would be useful.

**Comment by DanTup** [comment]
I did just discover you can do File->Open and multi-select folders. This is almost what I want - I just want to do it by selecting a parent folder and have all child folders opened - in a way that appears on the most recent list so I can easily repeat it.

**Comment by JokerDan** [comment]
@DanTup I meant as in the example I posted that it would be nice to have multiple 'rootFolders' that act as a workspace, allowing you to effectively have many workspaces open in one instance of the editor. Rather than many editors, one for each workspace.

Which is what I thought you were getting at? Currently VSCode supports 1 'workspace' per program instance, in which you can have multiple folders but you can't have one over-arching workspace root. Which makes setting up tasks and builds for each folder can be rather... time consuming.

**Comment by bpasero** [comment]
@DanTup and what is the difference of having each sub folder as a workspace folder compared to just having 1 folder opened?

**Comment by DanTup** [comment]
@bpasero as workspace folders they get their own launch.configs, etc?

**Comment by DanTup** [comment]
FWIW, I've decided that implementing this wouldn't actually solve my users problems. My users have projects inside sub-folders (eg. an `example` folder) and telling them to make that sub-folder a root to run it feels really clunky.

As such, I'm going to add the concept of "project folders" to my extensin which will track the list of all folders within all workspace folders that are actually projects). Therefore, this feature isn't that useful to me.

That said - I do think this could be handled in Code better - for ex. why can't I click an arbitrary folder in Explorer and say "Mark as project" and let it have its own .vscode folder without having to be shown at the top level? And then, when opening a folder where child folders have `.vscode` folders, treat them as roots.

**Comment by DanTup** [comment]
I've raised a new case that I think would be a much better solution to this problem - which is allowing sub-folders in explorer to be WorkspaceFolders - see https://github.com/Microsoft/vscode/issues/45399

**Comment by bpasero** [comment]
As per https://github.com/Microsoft/vscode/issues/45399#issuecomment-371856266
