### ISSUE TITLE
git does not work correctly in a multi-folder workspace

### ISSUE THREAD

**Issue by webarchymeta** [Microsoft/vscode#43903]
### Issue Type
Bug

### Description

Git stopped or incorrectly updating changed info in folders other than the first one in a workspace (Encounter it in a two folder workspace)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz (4 x 2794)|
|Memory (System)|15.98GB (5.98GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
beautify|Hoo|1.3.0
code-beautifier|mic|1.7.2
csharp|ms-|1.14.0
ejs-language-support|Qas|0.0.1
ReactSnippets|xab|1.7.0

</details>

**Comment by egamma** [comment]
Cannot reproduce given the provided information (see the screenshot below that shows 3 changes in 3 different root folders of a multi root folder workspace).

Can you reproduce the behaviour and provide more details?

You state that this only reproduces with extensions only? Can you narrow down which extension is causing the problem? https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled


![image](https://user-images.githubusercontent.com/172399/36352299-09341e4e-14b7-11e8-9956-c390f6d29d7a.png)

**Comment by webarchymeta** [comment]
Sorry, I generated the report inside of visual studio code and somehow "Reproduces only with extensions" gets generated. I have deleted the corresponding phrase.

I have explored a few ways that the reported problem appear repeatedly, at least on my box:

1. Open a git (managed) folder;
2. Add a different folder under git control;
3. Edit a file inside the second folder to make a change;

All the previous changed files inside the second folder are properly marked, but the newly changed ones are processed correctly to display a modified mark . This behavior is not affected by disable/enable all extensions.

When I reload the newly created work-space, the problem disappear.

**Comment by joaomoreno** [comment]
@webarchymeta Can you show me what you mean by recording your screen?

**Comment by webarchymeta** [comment]
OK, here is the captured process:

[Screen Capture of the Process](https://www.archymeta.com/media/tmp/screenCap_1519063087906.webm)

**Comment by joaomoreno** [comment]
This is #44036
