### ISSUE TITLE
integrated shell args not working on asus, works on dell

### ISSUE THREAD

**Issue by darkoverlordofdata** [Microsoft/vscode#43905]
### Issue Type
Bug

### Description

I have 2 laptops, a dell and an asus. I have Windows 10, vscode and MSys2 installed on both, same versions all around. On the dell, these settings work such that when I open the terminal window, I see:

> darko@barsoom MSYS /c/Users/darko/Documents/GitHub/adriac
> $

Settings:

>  "terminal.integrated.shell.windows": "C:/msys64/usr/bin/bash.exe",
>  "terminal.integrated.shellArgs.windows": ["-lic", "cd $OLDPWD; exec bash"], 

On the asus, it does not. work, all I get is 

> darko@barsoom MSYS ~
> $

If I then enter this line manually, I get the correct results:

> $ bash -lic "cd $OLDPWD; exec bash"
> darko@barsoom MSYS /c/Users/darko/Documents/GitHub/adriac
> $
 

 The only difference is that the dell has had vscode installed since last summer and upgraded all along. The asus was just installed this year. It seems like it used to work and I still have the bits left on the older installation, so it still works there (#8429?)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|Memory (System)|11.91GB (8.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
AWK|lug|0.0.2
Kotlin|mat|1.4.0
vscode-clang|mit|0.2.2
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
vetur|oct|0.11.7
html-preview-vscode|tht|0.1.1
vscode-preview-server|yui|1.0.1

</details>
Reproduces without extensions

**Comment by darkoverlordofdata** [comment]
Wow. It get's wierder. I found that on my Asus machine, these settings work instead, staring up bash in the terminal and positioning me in the project folder:

>     "terminal.integrated.shell.windows": "C:\\msys64\\usr\\bin\\bash.exe",
>     "terminal.integrated.shellArgs.windows": ["-l"],

But they don't work on my Dell, it needs these settings to do the same thing: 
>     "terminal.integrated.shell.windows": "C:\\msys64\\usr\\bin\\bash.exe",
>     "terminal.integrated.shellArgs.windows": ["-lic", "cd $OLDPWD; exec bash"],

I am not able to find any differences in versions installed. I'm thinking that maybe there are elves living in vscode :)

**Comment by Tyriar** [comment]
What is `$OLDPWD`?
