### ISSUE TITLE
[Extension][Ruby][Ruby-Linter] Ruby extensions are not displaying in the recommend extension list when opening ruby file or folder.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4390]
- VSCode Version:0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:

1. Launch app and open any folder which contains a ruby project or .rb file. 
2. Click on extension info icon from task bar and select option for " Show extension recommendations" to get list of the extensions to be installed for current workspace project.

Actual: Ruby extension is not displaying in the show recommendations extension list.
![image](https://cloud.githubusercontent.com/assets/17735796/13862588/8f86fdbc-ec51-11e5-9f90-b61ad276f88f.png)

Expected: when user is opening a .rb file then it should display ruby extensions (ruby and ruby-lint) in the recommendations list.

**Comment by egamma** [comment]
@waderyan fyi are there other ruby extension that should be added to the extension list.

**Comment by jrieken** [comment]
I made an easy to edit file for this here: `vs/workbench/parts/extensions/electron-browser/extensionTips.json`

**Comment by waderyan** [comment]
Created PR in vscode-distro. 

https://github.com/Microsoft/vscode-distro/pull/23
