### ISSUE TITLE
No reason to minimize seldom

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#43913]
### Issue Type
Bug

### Description

I found VS Code seldom minimize itself to the the upper left corner of the screen when it switch from the background to the foreground. No obvious reason. Hard to reproduce. The bug can be found at least at Version 1.19.1.
![vs-code-minimize](https://user-images.githubusercontent.com/32985998/36347935-8ef3d6fe-149f-11e8-8b65-a6f629384e4d.PNG)

Nothing to do with the extension. When I first found this at Version 1.19.1, I did not install the markdownlint extension yet.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.3.9600

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0

**Comment by uykusu76** [comment]
This is still happen in version 1.21.0

**Comment by bpasero** [comment]
I have seen this too but so far have no clue why this happens. I suspect an Electron issue but I am open for help.
