### ISSUE TITLE
Split does not appear on IntelliSense

### ISSUE THREAD

**Issue by pavilion** [Microsoft/vscode#43911]
- VSCode Version: 
Version 1.21.0-insider
Commit 936b796aa8667de5edb536b00ce8a8e61fcebfb6
Date 2018-02-16T05:15:47.029Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows 10

Problem: 
Split does not appear on IntelliSense.
![image](https://user-images.githubusercontent.com/3165436/36347760-7fb876ba-1457-11e8-867a-c22ec4855fae.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
This is correct since Array does not provide a 'split' method. String provides a 'split' method.
