### ISSUE TITLE
Can't do column selection with keyboard over Windows remote desktop

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#4391]
- VSCode Version:alpha 0.10.12 commit 05e203c
- OS Version:Windows 7

Steps to Reproduce:

1. Try Ctrl+Shift+Alt+arrow keys to "draw" a rectangle.
2. Nothing happens

Shift+Alt and mouse works correctly.

**Comment by alexandrudima** [comment]
@gregvanl I wonder if those keybindings are reserved on Windows 7?

Do the actions work if you bind them to different keys.

e.g.
```
{ "key": "shift+alt+down",   "command": "cursorColumnSelectDown",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+left",   "command": "cursorColumnSelectLeft",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+pagedown", "command": "cursorColumnSelectPageDown",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+pageup", "command": "cursorColumnSelectPageUp",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+right",  "command": "cursorColumnSelectRight",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+up",     "command": "cursorColumnSelectUp",
                                     "when": "editorTextFocus" },
```

I know the default ones with `ctrl+shift+alt+` are not great, but we could not find any free ones.

**Comment by gregvanl** [comment]
Works on Windows 10.

**Comment by gregvanl** [comment]
I think this is due to running over Windows remote desktop.  I was able to get keyboard column selection to work on a Windows 7 machine when I was directly logged in.  I see the issue only when remoting to a VM (so far tried Windows 7 and 8).  I've update the issue title.  If this is only an issue through remote desktop, I think we can lower the priority

**Comment by alexandrudima** [comment]
#3130 would help in this case, so I suggest to close this issue in favor of #3130
