### ISSUE TITLE
Terminal - caret is not blinking (gets frozen)

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#43916]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

When you change a terminal from one to another - the caret (vertical line) gets frozen, not blinking.
Clicks inside of terminal or typing the text - would not help with it.
What will help - to click, for example, on the tab "Terminal"... or focus on another app of your OS and come back.

![caret is not blinking](https://user-images.githubusercontent.com/24613274/36348958-62c27380-1484-11e8-958b-dfe5df5e838e.gif)

It confuses, cause it looks like the terminal got lagged.

**Comment by Tyriar** [comment]
I cannot seem to reproduce. I'm guessing this was caused when by the terminal splitting refactors. Let me know if it still happens in latest.

**Comment by user3323** [comment]
@Tyriar 

yes, now it's gone.
