### ISSUE TITLE
Errors and warnings in console on marketplace pages

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43919]
I'm not sure if there's a better place to report this, but there are errors and warnings on the marketplace pages:

<img width="1166" alt="screen shot 2018-02-18 at 08 19 09" src="https://user-images.githubusercontent.com/1078012/36349828-91f4385a-1484-11e8-90a9-b9ccdf8a2cb2.png">

**Comment by egamma** [comment]
The error shows up when opening https://marketplace.visualstudio.com/

I´ve informed the market place team. Closing the issue.

**Comment by viradhamMS** [comment]
Thanks Erich and DanTup for reaching out.

We fixed this issue and the changes will be deployed in the next couple of days.

Feel free to reach out to vsmarketplace @ microsoft dot com for any marketplace related issues.
