### ISSUE TITLE
Format on type not working as expected with Insert Line Below command (when extension configures handling of new lines with type formatting).

### ISSUE THREAD

**Issue by fabioz** [Microsoft/vscode#43924]
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a typescript code with `call(a,b)` (which when auto-formatted should have a space after the comma).
2. Use `Shift+Enter` to add a new line after the current line.

At this point, I expected the line `call(a,b)` to be formatted to `call(a, b)`, whereas the line is not formatted (i.e.: the behavior should be mimicking the same behavior of pressing `Enter` at the end of the line).

Note that I know that in this particular case adding a `;` would suffice, but it wouldn't work for other extensions on languages that don't require a `;` at the end (such as Python, where the default for users should be using `Shift+Enter` to add new lines as the close parenthesis is already automatically added).

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
When pressing enter while 'format on type' is enabled then the line is formatted. However, when executing 'insert line below' (`CTRL+Enter`), then the line is not formatted.

**Comment by jrieken** [comment]
Generally format on type is a 'typing' listener and it doesn't listen to commands that change the document. That means there are likely many similar cases like this... Unsure what to do

**Comment by fabioz** [comment]
I think this shouldn't be changed globally, but rather on this particular action -- I agree in general that a typing listener shouldn't listen to changes in the document, the problem is with this particular action as `insert line below` should mimick going to the end of the line and doing an `enter` there (in this case, for anything that comes along, such as indentation or typing listeners).
