### ISSUE TITLE
Diff highlights unchanged text in README.md markdown

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#43922]
### Issue Type
Bug

### Description

The `ies` in dependencies is highlighted for some reason?

![image](https://user-images.githubusercontent.com/2301847/36351296-bce12d4a-1464-11e8-93d5-7fb2c4fc59ce.png)

Before text:  

```
 * `yarn [install]` -- Install project NPM dependencies. This is automatically done when you first create the project. You should only need to run this if you add dependencies in `package.json`.
```

After text:
```
  * `yarn` -- Install project NPM dependencies. You should only need to run this if you add dependencies in `package.json`.
```

 

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (135d4a5d5cecd82e9e4da7ede655fb09af0dac35, 2018-02-14T06:09:28.551Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|6, 6, 5|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|/private/var/folders/90/lpgkdnnj293gmdz2pds2pm3w0000gn/T/AppTranslocation/C1EF80CB-B78A-4648-A359-F116D0267978/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0

</details>
Reproduces only with extensions

**Comment by egamma** [comment]
The expected behaviour is that the word level differences do not show  `ies` since this word is common in both versions.
![image](https://user-images.githubusercontent.com/172399/36352094-04f8c170-14b4-11e8-9fe9-9d239b128bf1.png)
