### ISSUE TITLE
[bat] Batch file syntax highlighting works incorrectly for single-letter variables

### ISSUE THREAD

**Issue by m93a** [Microsoft/vscode#43923]
- VSCode Version: 1.20.0
- OS Version: Windows 10 Pro 1709

Steps to Reproduce:

1. Create a `.bat` file
2. Either use a single-letter variable outside of a string
2. Or use two single-letter variables inside strings on the same line

![image](https://user-images.githubusercontent.com/1671665/36351291-c1359794-14a7-11e8-830e-aecd17408976.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
This issue was moved to mmims/language-batchfile#25
