### ISSUE TITLE
[Extension] Getting message like : can't lint "c:\.<xyz.rb" file , after installing ruby-linter extension.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4392]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. Launch app and open a folder which contains .rb file.
2. Install Ruby and Ruby-linter extensions and verify .rb file for lint message.

Actual: 
1. Getting message like: "Cannot lint c:\src\Ruby\main.rb. The executable was not found. Use the 'ruby.executablePath' setting to configure the location of the executable"
![image](https://cloud.githubusercontent.com/assets/17735796/13863115/d3d6bbb2-ec54-11e5-8195-856efb07174c.png)

2. There is no entry in the default setting file for Ruby's extensions.

Note : I could see for other extensions (Like GO, PHP, ESLint etc.) there are some default configuration available in default setting file but for Ruby there is no entry. 
Expected: After installing the extension it should configure the default setting and linter should work properly.

**Comment by aeschli** [comment]
This issue was moved to hoovercj/vscode-ruby-linter#1
