### ISSUE TITLE
A lot of comments would be wrong.

### ISSUE THREAD

**Issue by linyi3344** [Microsoft/vscode#43929]
- VSCode Version:1.20.0
- OS Version:windows16299.192

Steps to Reproduce:

1.Create an svg file.
2.Add a large comment.
3.open with live server
4.error . then ctrl+u . and you can see 

Does this issue occur when all extensions are disabled?: Yes/No
sorry!I don't know.

**Comment by egamma** [comment]
This is caused by the live server extension, please report the issue against this extension.
