### ISSUE TITLE
Command line options don't work for code insiders version

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#43925]
### Issue Type
Bug

### Description

The command line options don't work for code insiders version.  I'm trying to write a single script to download and install all extensions for VS Code and VS Code Insiders.  I think there is a separate script?  But, would it be possible to fix this bug so I can run my script for VS Code and VS Code Insiders without any special logic?

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (135d4a5d5cecd82e9e4da7ede655fb09af0dac35, 2018-02-14T06:09:28.551Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|/private/var/folders/90/lpgkdnnj293gmdz2pds2pm3w0000gn/T/AppTranslocation/C1EF80CB-B78A-4648-A359-F116D0267978/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0

</details>
Reproduces only with extensions

**Comment by egamma** [comment]
Please provide more details. What command line options are you trying to use? 

The command line when using the stable version is ´code´ when using the insiders version it is ´code-insiders´. If you want to write a single script then you need to distinguish between these two versions of the command line in you script.

**Comment by joshunger** [comment]
`install-extension` . Why have two different scripts?

**Comment by joshunger** [comment]
@egamma got it working 👍 feel free to close
