### ISSUE TITLE
The code prompt fails during using js

### ISSUE THREAD

**Issue by spitWind** [Microsoft/vscode#43937]
### Issue Type
Bug

### Description

 a template :
var a=new User();
db={};
db.user=a;
db.user// can't prompt the type

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|Memory (System)|7.89GB (3.25GB free)|
|Process Argv|F:\Program Files (x86)\MicrosofVC\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.5
docthis|joe|0.6.0
typings-autoinstaller|jvi|1.2.0
node-module-intellisense|lei|1.5.0
cpptools|ms-|0.15.0
ejs-language-support|Qas|0.0.1

</details>
Reproduces only with extensions

**Comment by spitWind** [comment]
please don't close my problem

**Comment by egamma** [comment]
> var a=new User();

@spitWind please provide a complete sample. What is the definition of the `User` class in your example?

**Comment by mjbvz** [comment]
Root cause is https://github.com/Microsoft/TypeScript/issues/10868

As a workaround, try forward declaring `user` when you declare `db`:

```
const db = {  db: /** @type {User} */ (undefined) }
```
