### ISSUE TITLE
File search searches inside .vscode folder

### ISSUE THREAD

**Issue by tschofen** [Microsoft/vscode#43939]
### Issue Type
Bug

### Description

Since 1.20 the search result searches inside th .vscode folder. It appears to ignore the search.exclude all together as result from node_modules appear as well.

I tried to add the .vscode folder to the files.exclude as well as added a search.exclude, but neither worked.
`    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/.vscode": true,
        ".vscode": true,
    },
    "search.exclude": {
      "**/node_modules": true,
      "**/bower_components": true,
      "**/.vscode": true,
      ".vscode": true,
    },
    "search.quickOpen.includeSymbols": true,
    "search.useIgnoreFiles": true,`

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by roblourens** [comment]
Sorry for the slow response. Is this still an issue in the latest release?

**Comment by tschofen** [comment]
Looks like it’s no longer searching in the .vscode folder.
