### ISSUE TITLE
Intellisense for JS object's this not working in function call

### ISSUE THREAD

**Issue by Floriferous** [Microsoft/vscode#43930]
- VSCode Version: 1.20.1
- OS Version: macOS 10.13.3
- Does this issue occur when all extensions are disabled?: Yes

`this` does not properly autocomplete when an object literal is passed as a parameter to a function.

Here's a reproduction (there's certainly a simpler one): 

```js
const myObject = {};

const addObjectValue = (key, value) => {
  myObject[key] = value;
};

addObjectValue("hello", {
  a: "world",
  log() {
    // Here, this is not autocompleted with this.a
    console.log(this.a);
  }
});

myObject.hello.log(); // Logs 'world' properly
```

It may be that this is by design for some obscure JS reasons, in which case I apologise for this issue.

**Comment by Floriferous** [comment]
Turns out my this became undefined when I ran the code (in my more complicated setup). And it's indeed because of a JS quirk.

Here's how it failed:

```js
const myObject = {};

const addObjectValue = (key, value) => {
  myObject[key] = value;
};

addObjectValue("hello", {
  a: "world",
  log() {
    // Here, this is not autocompleted with this.a
    console.log(this.a);
  }
});

const { log } = myObject.hello;
hello.log(); // ERROR: Cannot read property 'a' of undefined
```

When you destructure `log` out of myObject.hello, it's context is undefined. So maybe this issue is a feature rather than a bug trying to prevent developers from making mistakes?

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/22058 to track this upstream
