### ISSUE TITLE
When I type "<" in html file, it creates empty space instead of writing "<" 

### ISSUE THREAD

**Issue by rjayaswal** [Microsoft/vscode#43933]
### Issue Type
Bug

### Description

When I type '<' in html file, it creates empty space instead of writing '<' 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|7.69GB (1.64GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by egamma** [comment]
Cannot reproduce the problem.

Can you reproduce this when you have the extensions disabled?

Please provide a snippet that illustrates the problem.

**Comment by rjayaswal** [comment]
I can still reproduce this issue.
Issue is not reproducible if i disable my all extensions. 
Following are the extensions that was enabled and the issue was getting reproduced.

![image](https://user-images.githubusercontent.com/7348591/36732415-b6bc3e50-1bf3-11e8-9907-4393a792fefa.png)
