### ISSUE TITLE
Copy Word in Cursor extension no longer working in 0.10.11

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#4393]
Copied from https://github.com/Microsoft/vscode/issues/4035#issuecomment-197659811
From @alefragnani 

---

Hi @alexandrudima , do you know if something has changed prior to 0.10.11 about it? 

I had an extension [Copy Word in Cursor](https://marketplace.visualstudio.com/items?itemName=alefragnani.copy-word) that is meant to replace the `Copy` and `Cut` commands when  there is no selection. It automatically selects the word where the cursor is, and copies/cuts to the clipboard, but I just noted that it is not working anymore :cry: . It detects and select the word, but when I call `vscode.commands.executeCommand("editor.action.clipboardCopyAction");`, it does not respect the new selection, and the whole line is copied to the clipboard strangely, if I use the `clipboardCutAction` command, it _cuts_ the selected word, but the clipboard is filled with the entire line, again.

I don't know if the commands itself changed, or if I have to do something else after updating the `selection`. The code is basically:

```TypeScript
  const cursorWordRange = doc.getWordRangeAtPosition(selection.active);
  var newSe = new vscode.Selection(cursorWordRange.start.line, cursorWordRange.start.character, cursorWordRange.end.line, cursorWordRange.end.character);
  editor.selection = newSe;
  vscode.commands.executeCommand("editor.action.clipboardCutAction");

```

Thanks for your help.

**Comment by alexandrudima** [comment]
@alefragnani Thank you for reporting this, the code that was in charge of deciding what to write to the clipboard was not always using the most up-to-date selection.

**Comment by alefragnani** [comment]
Thank you @alexandrudima for fixing it so quickly :smiley: 
I guess it will be available in March release, right?

**Comment by alexandrudima** [comment]
yep!

**Comment by alefragnani** [comment]
Hi @alexandrudima ,

It appears that the issue _returned_ in the version 1.1.0.

Looking at the same source files from your commit, I noted that some of them has changed, but I don't know if this changes could affect the clipboard operations.

Thanks for your help
