### ISSUE TITLE
Add vscode to Microsoft / Mac app stores

### ISSUE THREAD

**Issue by jstlns** [Microsoft/vscode#43947]
It would be nice to be able to install VSCode via Microsoft Store (Windows S support) and OSX app stores.  This could even be extended to support iOS etc.. in the future.

**Comment by bungcip** [comment]
OSX app stores is sandboxed right? 
VSCode will have reduced functionality in such environment. Even snap version of VSCode is using classic confinement.

**Comment by egamma** [comment]
Duplicate of #10759
