### ISSUE TITLE
Bug o Error 

### ISSUE THREAD

**Issue by MagiaBlanca** [Microsoft/vscode#43944]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.24.0
vscode-intelephense-client|bme|0.8.8
laravel-blade|cjh|1.1.2
gitignore|cod|0.5.0
git-extension-pack|don|0.1.3
githistory|don|0.4.0
gitlens|eam|8.0.0
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.11.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.8
php-pack|fel|1.0.1
crane|Hvy|0.3.8
php-cs-fixer|jun|0.1.56
mssql|ms-|1.3.0
php-docblocker|nei|1.3.3
laravel-blade|one|1.15.0
laravel-extension-pack|one|0.2.0
laravel5-snippets|one|1.4.0
laravel-helpers|raf|0.2.2
vscode-icons|rob|7.20.0
sass-indented|rob|1.4.8
laravel-artisan|rya|0.0.16
laravel-5-snippets|sac|2.0.1
html-css-class-completion|Zig|1.17.1
vscode-open-in-github|ziy|1.3.1

---

Steps to Reproduce:

1. Actualizar a la versión mas reciente 1.20
2. Al abrir un archivo ejemplo.blade.php de laravel, el formato de colores es incorrecto

El problema es que cuando abro un archivo del formato .blade.php, los colores que deberian tener el HTML, es erroneo. Me he fijado que este color que muestra el HTML es igual al color que se reproduce al abrir un archivo .php, lo cual me indica que esta reconociendo el arhicvo .blade.php como si fuera uno de .php. Espero lo puedan solucionar

Gracias :D

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Estás viendo este problema solo después de actualizar a 1.20? Puedes compartir algunas capturas de pantalla y código de muestra?

**Comment by roblourens** [comment]
We do not have special syntax highlighting for Blade files. There are some Blade-related extensions, see if they fit your needs.
