### ISSUE TITLE
VS Code will not update (stuck on preparing to install page)

### ISSUE THREAD

**Issue by mesternefeld** [microsoft/vscode#43949]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-view-readme|ans|0.2.1
solargraph|cas|0.12.0
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
Ruby|reb|0.16.0
vscode-icons|rob|7.20.0

---

Steps to Reproduce:

1. Press update and the VSCode process stops responding and never installs update.
This also happens when I install the newest version from online and try to install without uninstalling. 

I also have this issue on the other computer on the Windows Insider Build. I can post that OS version if needed since it happens on both.

If it helps, the VSCode process that stops says VSCodex32 bit which seems a bit odd since the version I have is 64 bit.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
> If it helps, the VSCode process that stops says VSCodex32 bit which seems a bit odd since the version I have is 64 bit.

Where does it say that?

What do you mean by "stops responding"?

**Comment by mesternefeld** [comment]
It says 32 bit installer in the Task manager despite me having the 64 bit version. Would a screenshot help?

And by "stops responding" I mean that the installer sits there on the screen and does not install the update. In one instance I got a (application is not responding error).

I have sat there for over 10 minutes and the update never starts.

**Comment by joaomoreno** [comment]
Yeah, screenshots would be helpful. Also of the frozen installer screen! Thanks.

**Comment by mesternefeld** [comment]
![image](https://user-images.githubusercontent.com/13999153/36392407-0891f69c-1579-11e8-8d3c-5fdd9c78569e.png)
![image](https://user-images.githubusercontent.com/13999153/36392427-1bfb82c0-1579-11e8-8ea0-f7ab2589f4ac.png)
It just gets stuck on the screen on both my computers. I waited over 20 minutes and this is the result.

**Comment by joaomoreno** [comment]
What is the size of `C:\Program Files\Microsoft VS Code\unins000.dat`?

**Comment by mesternefeld** [comment]
It is 1,898 KB

**Comment by joaomoreno** [comment]
Very interesting. Do you have any antivirus installed?

**Comment by mesternefeld** [comment]
yes, I have panda security on both the computers (and the default for windows 10). Should I try installing with it turned off?

**Comment by joaomoreno** [comment]
Yeah, let me know if that works.

**Comment by mesternefeld** [comment]
No change. Still hangs when anti-virus is off

**Comment by joaomoreno** [comment]
Does it reproduce if you fully reinstall Code (uninstall, install)?

**Comment by mesternefeld** [comment]
Well, I could try except then the application would be fully updated and would not be able to check if I could update it. I will say this happened right before the latest update and I did uninstall and reinstall to this version I currently have. So I was able to fully install after not being able to update.

**Comment by mesternefeld** [comment]
The same problem was reproduced when installing the new update. So this error has been in the last 3 updates of VS code. Never had a problem before this.

**Comment by joaomoreno** [comment]
Can you reproduce on another machine? Can you reproduce with our [insider release](https://code.visualstudio.com/insiders)?

**Comment by mesternefeld** [comment]
I just installed the insiders build. It seems to be acting very differently from the other.
I got this issue on VS insiders.
![image](https://user-images.githubusercontent.com/13999153/36691005-07fc037e-1b02-11e8-86c8-13f531ad1435.png
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1760016/vscode-inno-updater.log)
)
It also seemed to have massively broke and VSCode insiders is currently unable to be used.

**Comment by joaomoreno** [comment]
Can you retry while disabling any (and every) antivirus tool?

**Comment by mesternefeld** [comment]
On what VSCode Insiders or on my normal VSCode? I'll have to reinstall because the entire image got corrupted for Insiders when the issue arose above.

**Comment by joaomoreno** [comment]
On any. I'm interested in knowing if you manage to get that update to run at least once successfully and what were the steps to do so.

**Comment by mesternefeld** [comment]
Tried it without Panda Anti-virus (same issue as above but not as catastrophic as the Insiders build). I was unable to turn off Windows defender as you probably guessed.

**Comment by joaomoreno** [comment]
Just to confirm: same issue is the frozen window; catastrophic is the error. Correct?

This is an unfortunate issue, I really don't know how to fix, since we can't seem to get a successful installation working for you. I recommend to use our ZIP release and manually updating it, unfortunately.

**Comment by mesternefeld** [comment]
No, the issue I still get(on regular not insiders) is it freezing on the waiting to download page.
The issue on Insiders is the catastrophic one where the program becomes corrupted when updating and seeing the please reinstall code. 

And that is unfortunate since this is on both my machines and seems as though I'm not the only one with this issue.

**Comment by joaomoreno** [comment]
> seems as though I'm not the only one with this issue.

I am not aware of anyone else having exactly the same issue. What makes you say this? Can you point me to it?

**Comment by 0zkr1** [comment]
I have a similar scenario on Windows 7: the update process stop advancing after request close applications or "Omit". Then, the update process say that it can't delete "Code.exe", then I cancel the update process and it going to "undo" the changes. The result was a mess... I can't started VS Code again.

I usually have 2 instances of VS Code and before I accept the update close the 2 instance. Any suggestion for the next update? Other than "Try using the zip file instead of the installer."?

**Comment by mesternefeld** [comment]
I assumed that is why you added the other issue into this one and the fact that I have the exact same issue on both my machines with different Windows versions

**Comment by joaomoreno** [comment]
> I have the exact same issue on both my machines with different Windows versions

This is what bothers me right now. Is there anything you can think of which you have on both machines and that most people don't?

**Comment by msmarino** [comment]
Hello

I've been suffering with the same problem for months and 2 things in the thread jumped out at me:  Panda AV + Windows Defender.

I have just successfully updated by deactivating Defender while Panda was disabled (update was open and stuck but when I returned it was 60% done!)

**Comment by mesternefeld** [comment]
Yeah I decided that I'd try the new update and leave it overnight and came back to it finished. I think it does go through but it takes way longer than it did before (longer than 20 minutes to set up). Not sure how long it actually takes as leaving it overnight it could have taken any amount of time. All my stuff was reenabled when I did this.

**Comment by joaomoreno** [comment]
Wow. And further updates are still like that? Can you send me your `unins000.dat` file?

**Comment by mesternefeld** [comment]
Yeah this seemed to work for the last 2 updates which is very odd. 

And Github will not allow me to upload that type of file.

**Comment by joaomoreno** [comment]
You can mail it to me to joao moreno at _my company_ dot com.

It definitely still sounds a lot to me that there's some anti-virus/malware tool which monitors the files extracted by Inno Setup.

One cool experiment would be to record the full activity of the setup using [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) so we see what happens.

**Comment by mesternefeld** [comment]
Sorry @joaomoreno I thought I replied. I tried to send you an email but my email bounced. Unsure if you sent the correct thing.

**Comment by joaomoreno** [comment]
Oh, try joao dot moreno at my company dot com

**Comment by mesternefeld** [comment]
I sent an email to you last week to sure it sent properly. I'll send you the file once you reply

**Comment by joaomoreno** [comment]
"my company" is "microsoft" 👍

**Comment by mesternefeld** [comment]
Yes @joaomoreno I sent you an email already with the title "FW: Github Issue 43949." Did you receive it?

**Comment by joaomoreno** [comment]
Got it! Replied. 👍

**Comment by simioluwatomi** [comment]
I think I should just paste my error log here. I got the same error as @mesternefeld some minutes ago and this is the first time it has ever happened.

My setup: Win 7 Pro 32 bit, MS Security Essentials.

```
Apr 17 15:22:55.174 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, true
Apr 17 15:22:55.180 INFO Checking for running Code.exe processes... (attempt 1)
Apr 17 15:22:55.182 INFO Code.exe is not running
Apr 17 15:22:55.188 INFO Starting update, silent = true
Apr 17 15:22:55.322 INFO do_update: "C:\\Program Files\\Microsoft VS Code\\Code.exe", _
Apr 17 15:22:55.323 INFO move_update: "C:\\Program Files\\Microsoft VS Code\\unins000.dat", _
Apr 17 15:22:55.377 INFO Delete: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.378 INFO Delete: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.404 INFO Delete: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.439 INFO Delete: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.440 INFO Delete: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.442 INFO Delete: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
Apr 17 15:22:55.442 INFO Delete: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
Apr 17 15:22:55.443 INFO Delete: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.444 INFO Delete: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.446 INFO Delete: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.447 INFO Delete: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.450 INFO Delete: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
Apr 17 15:22:55.451 INFO Delete: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.451 INFO Delete: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.452 INFO Delete: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.453 INFO Delete: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.455 INFO Delete: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
Apr 17 15:22:55.455 INFO Delete: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.480 INFO Delete: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.482 INFO Delete: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.482 INFO Delete: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.483 INFO Delete: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
Apr 17 15:22:55.484 INFO Delete: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.486 INFO Delete: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.486 INFO Delete: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.487 INFO Delete: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.488 INFO Delete: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.489 INFO Delete: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.489 INFO Delete: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.540 INFO Delete: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.541 INFO Delete: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.541 INFO Delete: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.564 INFO Delete: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.564 INFO Delete: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.569 INFO Delete: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.569 INFO Delete: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.569 INFO Delete: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.570 INFO Delete: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.570 INFO Delete: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.572 INFO Delete: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
Apr 17 15:22:55.572 INFO Delete: "bin" (attempt 1)
Apr 17 15:22:55.620 INFO Delete: "blink_image_resources_200_percent.pak" (attempt 1)
Apr 17 15:22:55.622 INFO Delete: "Code.exe" (attempt 1)
Apr 17 15:22:55.629 INFO Delete: "Code.VisualElementsManifest.xml" (attempt 1)
Apr 17 15:22:55.631 INFO Delete: "CodeSignSummary.md" (attempt 1)
Apr 17 15:22:55.633 INFO Delete: "content_resources_200_percent.pak" (attempt 1)
Apr 17 15:22:55.634 INFO Delete: "content_shell.pak" (attempt 1)
Apr 17 15:22:55.634 INFO Delete: "d3dcompiler_47.dll" (attempt 1)
Apr 17 15:22:55.636 INFO Delete: "ffmpeg.dll" (attempt 1)
Apr 17 15:22:55.637 INFO Delete: "icudtl.dat" (attempt 1)
Apr 17 15:22:55.638 INFO Delete: "inno_updater.exe" (attempt 1)
Apr 17 15:22:55.680 INFO Delete: "libEGL.dll" (attempt 1)
Apr 17 15:22:55.854 INFO Delete: "libGLESv2.dll" (attempt 1)
Apr 17 15:22:55.855 INFO Delete: "locales" (attempt 1)
Apr 17 15:22:57.260 INFO Delete: "msvcp140.dll" (attempt 1)
Apr 17 15:22:57.262 INFO Delete: "natives_blob.bin" (attempt 1)
Apr 17 15:22:57.262 INFO Delete: "node.dll" (attempt 1)
Apr 17 15:22:57.266 INFO Delete: "pdf_viewer_resources.pak" (attempt 1)
Apr 17 15:22:57.267 INFO Delete: "resources" (attempt 1)
Apr 17 15:22:59.719 INFO Delete: "resources" (attempt 2)
Apr 17 15:23:02.500 INFO Delete: "resources" (attempt 3)
Apr 17 15:23:12.778 INFO Delete: "resources" (attempt 4)
Apr 17 15:23:23.589 INFO Delete: "resources" (attempt 5)
Apr 17 15:23:25.754 INFO Delete: "resources" (attempt 6)
Apr 17 15:23:34.918 INFO Delete: "resources" (attempt 7)
Apr 17 15:23:42.584 INFO Delete: "resources" (attempt 8)
Apr 17 15:24:04.814 INFO Delete: "resources" (attempt 9)
Apr 17 15:24:10.980 INFO Delete: "resources" (attempt 10)
Apr 17 15:24:22.195 INFO Delete: "resources" (attempt 11)
Apr 17 15:24:22.696 ERRO The directory is not empty. (os error 145)

```

**Comment by ShiroSensei** [comment]
I thought I had the same issue, but by the time I've read this whole thread, it started.
It was just very slow.
My 2 cents.

**Comment by NBelham** [comment]
I have the same issue. Two VS Code updates seem to stall after downloading the update and then installing.
What's going on here?
![image](https://user-images.githubusercontent.com/17041517/39958339-457fba36-55f1-11e8-9fea-af92c962b81c.png)

**Comment by cafenroy** [comment]
Had the exact same issue with VSCode and Azure Storage Explorer. Uninstalling programs from the Control Panel first fixed the problem.
