### ISSUE TITLE
File order in the VS Code Explorer

### ISSUE THREAD

**Issue by DerHerrGammler** [Microsoft/vscode#43945]
If I create two files like `achievments.js` and `achivments_get.js` in normal explorer they will sorted like this:
- `achievments.js`
- `achievments_get.js`

But the file explorer in VS Code sorting the files in this order:
- `achievments_get.js`
- `achievments.js`

- VSCode Version: 1.20
- OS Version: Win10

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tjommel** [comment]
got the same issue.

**Comment by isidorn** [comment]
dup https://github.com/Microsoft/vscode/issues/27286
