### ISSUE TITLE
[Ruby] Unable to debug .rb file and getting debugger terminal error.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4394]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10
-Ruby Version: rubyinstaller-2.2.4-x64 (install location : http://rubyinstaller.org/downloads/)

Steps to Reproduce:
1. Launch app and open a folder which contains .rb file.
2. Install all the ruby extensions and restart app.
3. Add some break point in .rb file.
4. Debug .rb file  with option "Debug local file"

Actual: Getting Error like : Debugger terminal error: Process failed: spawn rdebug-ide.bat ENOENT 
![image](https://cloud.githubusercontent.com/assets/17735796/13863301/19ee6478-ec56-11e5-92b6-140a0812fbc7.png)

**Comment by egamma** [comment]
pls file against the Ruby extension.

**Comment by v-pavanp** [comment]
Please refer # https://github.com/rebornix/vscode-ruby/issues/10

**Comment by xJoeyv** [comment]
I also have this issue but can't find out the fix by this, Pls Detail!

**Comment by rebornix** [comment]
@xJoeyv please take a look at https://github.com/rubyide/vscode-ruby/wiki to check whether you have installed the dependencies correctly, otherwise please file an issue there.

**Comment by sschuberth** [comment]
The proper link to the upstream bug report is https://github.com/rubyide/vscode-ruby/issues/113.
