### ISSUE TITLE
Undefined very vague error that breaks vs code

### ISSUE THREAD

**Issue by prodigynelson** [Microsoft/vscode#43948]
### Issue Type
Bug

### Description
I use vs code to write react native javascript (so JSX) and randomly, my vs code will break with this [incredibly helpful error](http://prntscr.com/iglk4m). What I mean by this is autocomplete/snippets will cease to work, the [colors of text will get weird](http://prntscr.com/iglkju), and hitting ctrl-s to save will take about 2 seconds in between when I use the hotkey and when the dot next to the file changes, (I use watchman to live reload the iPhone simulator on changes, and the simulator will also wait those 2 seconds because it isn't saved).

I would love to provide steps to reproduce, but I've tried uninstalling VS Code and clearing all caches, not installing any extensions, and I have no idea where to even begin to track down this issue. When I try to look at the line at which it broke, I'm shown [this](http://prntscr.com/iglksw) whic if I prettify looks like [this](http://prntscr.com/igll28). Quitting VS Code, killing all the helper processes in Activity Monitor, and restarting does not fix it reliably, and neither does reloading the window.

About two weeks ago, the same symptoms (autocomplete ceasing to function, weird color text, etc.) would happen and I'd get [this error](https://prnt.sc/ibkw2u) and I have since uninstalled flow and I still get the breaking error.

I love VS Code but I'm getting very frustrated by it breaking unpredictably :( 
*NOTE* This happened on the old release of VS Code and I hoped that updating it would fix it. I am using a hackintosh build, however, this issue also occurs on my macbook pro so I do not believe it is a symptom of me using a hackintosh.

EDIT: not 10 minutes after I posted this issue, my VS Code crashed (like, the official way) for the first time. I pasted the entire [error log on pastebin](https://pastebin.com/jRFNL086).
### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (14.58GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
material-icon-theme|PKi|3.2.2
code-settings-sync|Sha|2.8.7
vscode-wakatime|Wak|1.1.22
path-intellisense|chr|1.4.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
indent-rainbow|ode|0.7.2
vscode-jumpy|wma|0.3.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by egamma** [comment]
Can you confirm that this issue doesn´t happen when you have extensions disabled https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled?

In one of the screenshots you link to there is an exception from a flow extension
![image](https://user-images.githubusercontent.com/172399/36370022-b0866ac0-155d-11e8-95f3-acf28322af90.png)

Since you mention there is a delay with saving. When this happens can you please run ´code --status´ and attach the output. This will help us to understand which VS Code process is causing the slow down.

**Comment by prodigynelson** [comment]
@egamma I uninstalled the flow extension and I still get the error. The "undefined" error happens when all extensions are disabled

**Comment by egamma** [comment]
It looks like the error happens when we report an error, but the message passed to Error is undefined. However, it is not clear the this ERR is causing the behavior you are observing. 

Let´s try something else can you install insiders and do not change anything and I wonder whether you can still reproduce the problem https://code.visualstudio.com/insiders/.

**Comment by prodigynelson** [comment]
@egamma I am using the insider version, and now I am getting [this error](http://prntscr.com/ihj8cm)

**Comment by egamma** [comment]
@prodigynelson this is an error that can happen I don´t think it is related to the issue you mention in the discussion:

>What I mean by this is autocomplete/snippets will cease to work, the colors of text will get weird, and hitting ctrl-s to save will take about 2 seconds

Let´s ignore the error messages for now but focus on this problem. What language are you using when this happens?

**Comment by prodigynelson** [comment]
@egamma JSX

**Comment by egamma** [comment]
OK, sorry but I have to ask again, you have all extensions disabled when this happens? I didn´t see a clear answer in the discussion above.

**Comment by prodigynelson** [comment]
@egamma yes, I am also running separate VS code windows when it happens.

**Comment by prodigynelson** [comment]
@egamma whenever I toggle developer tools, vs code crashes

**Comment by egamma** [comment]
@prodigynelson please file a separate issue on this crash and if possible include some more details about the crash.

**Comment by egamma** [comment]
@prodigynelson let´s focus on the slow down for now:

>and hitting ctrl-s to save will take about 2 seconds

Since you cannot create a CPU profile due to the developer tools crashing, can you run ´code-insiders --status´ when this happens.

**Comment by prodigynelson** [comment]
@egamma [here are the logs when it begins misbehaving](http://prntscr.com/ik44fb)

**Comment by mjbvz** [comment]
@prodigynelson Do you still  see this in the latest VS Code insiders build? What if you install and enable typescript@next in your workspace by following these instructions: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions
