### ISSUE TITLE
NodeJS require JSON file intelisense bug

### ISSUE THREAD

**Issue by DerHerrGammler** [Microsoft/vscode#43946]
- VSCode Version: 1.20
- OS Version: Win10

Steps to Reproduce:

1. Create a JSON file with some content 
2. `require` this file in a js file for NodeJS 

If I create a JSON object in my JavaScript file intelisense checked it and I can access my object with intelisense, but if I require a JSON file intelisense don't give me directly the content of the file. I have to check my file for the content. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/7071
