### ISSUE TITLE
CodeActionProvider is not correctly given the selected range

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43957]
- VSCode Version: 1.20.1
- OS Version: Windows 10

When debugging something, I noticed that the range passed to the code action provider wasn't the selection as I expected. In this animation you'll see the output:

```text
Requesting code fixes for 1:3 - 1:3
Requesting code fixes for 1:2 - 1:2
Requesting code fixes for 1:2 - 1:7
Requesting code fixes for 1:2 - 1:14
Requesting code fixes for 1:2 - 1:21
Requesting code fixes for 1:2 - 2:13
Requesting code fixes for 3:15 - 3:16
Requesting code fixes for 3:15 - 3:16
Requesting code fixes for 3:15 - 3:16
Requesting code fixes for 3:15 - 3:16
```

But the start of the selection never changes. For some reason when my selection goes onto the third line, the start of the range unexpectedly changes.

![Ranges](https://user-images.githubusercontent.com/1078012/36368858-15b7638e-1551-11e8-8174-d252c8ef5ed4.gif)

**Comment by jrieken** [comment]
Is it possible that you have an error/warning on line 3?

**Comment by DanTup** [comment]
I don't believe so, it all looks valid to me now and I can't see any squiggles.

**Comment by jrieken** [comment]
Well, 3:15-3:16 hints towards a bogus/empty squiggle. The problems view shows 5

**Comment by DanTup** [comment]
@jrieken The problems view there is for the extension codebase, it's the left window where the provider is running.

However, I can't repro right now so feel free to close until I can. I'll try and get better data next time (including the problems pane!).

**Comment by jrieken** [comment]
Ok, closing for now. From looking at the code this can only happen when the selection intersects with an error or warning

**Comment by DanTup** [comment]
@jrieken Actually, you're right - there's a squiggle on line 4 (probably the line numbers in range are 0-based) about dead code (because of ``if (false)`)!

I can understand this probably happens to make it easier to trigger quick fixes for these, however if the recommendation is for us to put refactors here, I think this is going to cause issues - eg. I can't select a block of code and perform some refactor over it (like extracting a method) if there are any warnings at all inside that code block (because the language server won't get the correct range)?

**Comment by jrieken** [comment]
> eg. I can't select a block of code and perform some refactor over it (like extracting a method) 

Yeah, idea is that you fix your errors before running refactorings.

**Comment by DanTup** [comment]
This is just a warning not an error. It seems a bit unfriendly to tell a user they can't refactor unless they eliminate all of the warnings (especially if the language server is able to do a good job of knowing if errors/warnings will affect the refactor and return that information to the user). The warnings may also be part of the reason they're refactoring the code.

**Comment by jrieken** [comment]
I understand but I also understand the other side which is language brains that support to fix an error/warning but not when it is enclosed by a large range. People complained that we don't show the light bulb when the selection completely encloses it. 

Tricky, it seems that we should try two times: once with the actual selection and then a error/warning range.

**Comment by DanTup** [comment]
Yeah, I understand. Trying twice sounds reasonable, though you might need to de-dupe results then. Maybe providing the "real range" too and letting the extension decide which is best to use would work?

**Comment by mjbvz** [comment]
I believe this was fixed by #49081

**Comment by DanTup** [comment]
@mjbvz Do I need to do anything to get this fix? I thought I would based on the comments in the linked issue, but it seems to already behave as I expect (I get the selection in the original `range` argument, and not the diagnostics range).

**Comment by DanTup** [comment]
Oh, I read to the end - seems like you improved the existing behaviour. All makes sense and nothing to do for me :-)
