### ISSUE TITLE
Empty jsconfig.json enables node?

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#43952]
- VSCode Version: latest insiders
- OS Version: win10

Steps to Reproduce:

1. use module.exports and require, see error tho it works
2. add empty or gibberish jsconfig.json errors go away

Does this issue occur when all extensions are disabled?: Yes

a.js
```
	class aa {
		constructor() {
			console.log('aa')
		}
		test() {
			console.log('test')
		}
	}
	module.exports = aa;
	module.exports.a = function () {
		console.log('a')
	}
```

Cannot find name 'module'.
An export assignment cannot be used in a module with other exported elements.
Cannot find name 'module'.

b.js
```
	const myModule = require('./a')
	myModule.a()
	let aa = new myModule()
	aa.test()
```

Cannot find name 'require'.
Property 'a' does not exist on type 'typeof aa'.

jsconfig.json
```
	 
```

i found i could use that `@types/node` command to fix the errors too, this is easier and smaller

thanks

**Comment by mjbvz** [comment]
Do you  have `"javascript.implicitProjectConfig.checkJs": true` in your workspace settings? That enabled the semantics checks in plain js files that are not part of a `jsconfig.json` project.

**Comment by rakkarage** [comment]
thanks. yes i do have that setting enabled. and that does seem to be what causes those errors to show in first place. removing that setting and the jsconfig.json and i got no errors... But i want that setting on i think and not sure why adding an empty config fixes the problems.

**Comment by mjbvz** [comment]
Once a file is part of a `jsconfig.json` project, the `jsconfig` controls `checkJs`. Just set:

```js
{
    "compilerOptions": {
       "checkJs": true
    }
}
```

If you want this enabled in files that are part of a jsconfig project.
