### ISSUE TITLE
多个存储库

### ISSUE THREAD

**Issue by 1m188** [Microsoft/vscode#43955]
如果能够同时打开多个存储库就好了，有时候并不想切换文件夹，每次要初始化一个存储库都要换文件夹，最好是打开一个文件夹下面有几个存储库的样子，现在只能够通过命令初始化某个文件夹然后编辑器里会自动打开，但是一旦关闭了多个存储库中的某一个之后，就难以再次打开，或者说没有相关的功能

**Comment by egamma** [comment]
@1m188 please report you issue in English
