### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by juloko** [Microsoft/vscode#43954]
### Issue Type
Idea

### Description

It's not a issue, just an idea. It's a great step on vs community the VS code, standing side by side with the Brackets.

But, there one thing that no one of the IDE faced to web developments haven't. It's a profile saving and installing all the configurations and extensions pre setted. Will be cool have this sync with MS or Tweeter or whaterver...

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)

**Comment by egamma** [comment]
@juloko does this extension cover your needs? https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by juloko** [comment]
Awesome, maybe has all there I need. Thank you for show-me.
