### ISSUE TITLE
Inconsistent behavior when viewing extension README/License

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4395]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Change default browser to IE or Chrome
2. In VS Code: F1 -> extension 
3. Click Readme or License

Actual:
When Edge is the default browser it stays minimized or in the background after clicking readme or license. If IE or Chrome is the default, it will pull the browser window over VS Code.

Expected:
Consistent behavior between browsers.

**Comment by joaomoreno** [comment]
Correct me if I'm wrong, @bpasero, but there is nothing we can do.

**Comment by bpasero** [comment]
@joaomoreno how do you open the browser window?

**Comment by joaomoreno** [comment]
[`shell.openExternal`](https://github.com/atom/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options) - there is an `activate` option, but seems to only work for OS X.

**Comment by bpasero** [comment]
@joaomoreno that option might have been added later, not sure it exists for our version. But yeah, if so this is an Electron issue and not VS Code.
