### ISSUE TITLE
we need search terms history

### ISSUE THREAD

**Issue by athinboy** [Microsoft/vscode#43963]
please do not mention alt+up/down ! 

#34977
#36063
#43698
#39416

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf
Alt+ ↑ / ↓ Move line up/down 

@roblourens

**Comment by egamma** [comment]
@athinboy as has been mentioned in the issues you have linked this is now supported using Alt+up/down. Is your request about to update the keyboard shortcuts cheat sheet?
