### ISSUE TITLE
Change in keyboard map via setxkbmap is not detected by keybindings engine

### ISSUE THREAD

**Issue by oxomoxo** [Microsoft/vscode#43962]
- VSCode Version: 1.20.1 (and previous)
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. with VSCode open [system is in AZERTY]
2. Plug your QWERTY keyboard in
3. setxkbmap us -variant intl
4. Do some edits (kbmap is ok in the editor) ... more edits ... more edits ...
5. Eventually decide to revert some edits,
6. Press Ctrl+Z -> BIM! : Closes your file :/

Does this issue occur when all extensions are disabled?: Yes/No
YES.

**Comment by egamma** [comment]
@oxomoxo please follow this guide for how to provide more information about keyboard problems https://github.com/Microsoft/vscode/wiki/Keybinding-Issues

**Comment by oxomoxo** [comment]
Ok, thanks, definitely case #2 in the wiki, I did a quick search but the issue linked there didn't show up.

**Comment by egamma** [comment]
So then is it ok to close this issue as a duplicate?

**Comment by oxomoxo** [comment]
Yep! ;)

**Comment by egamma** [comment]
@oxomoxo thank you, closing.
