### ISSUE TITLE
Login-AzureRMAccount - Bring to front

### ISSUE THREAD

**Issue by FlemmingRohde** [Microsoft/vscode#43967]
### Issue Type
Bug

### Description

When trying command Login-AzureRMAccount the login prompt is hidden behind the Studio Code GUI. Please make the login prompt focus (bring to front)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (8.76GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
azureautomation|Awe|0.6.2
xml|Dot|1.9.2
git-project-manager|fel|1.4.0
prettify-json|moh|0.0.3
azurecli|ms-|0.4.0
PowerShell|ms-|1.5.1
azurerm-vscode-tools|msa|0.4.0
vscode-manifest-yaml|Piv|0.1.3
vscode-icons|rob|7.20.0
arm-snippets|sam|1.1.0

</details>
Reproduces without extensions

**Comment by tsalinger** [comment]
Please continue this discussion in this repository: https://github.com/Microsoft/vscode-azurearmtools/issues/44
