### ISSUE TITLE
Git: no "Open File" action for a new file that is on the index

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#43961]
Steps to Reproduce:

1. create a new file
2. stage it
3. open it from the changes view

=> there is no action to jump to the actual file to make edits in the editor

**Comment by ajomadlabs** [comment]
Can I go take up this

**Comment by ajomadlabs** [comment]
@joaomoreno Could point me a file to start off

**Comment by joaomoreno** [comment]
In [here](https://github.com/Microsoft/vscode/blob/master/extensions/git/package.json#L713) we define contextual commands for resource changes. We need the `Open File` command for index changes.

**Comment by vstaykov** [comment]
Hi @joaomoreno, I don't see any progress on this so I'll work on it as my first contribution

**Comment by joaomoreno** [comment]
@vstaykov  Yeah this is fixed. Thanks!
