### ISSUE TITLE
Unable to debug test using code lens with net46 framework

### ISSUE THREAD

**Issue by pp1609** [Microsoft/vscode#43960]
We are trying to debug the nunit test in VScode in net46 framework but even if change the target framework from netcoreapp2.0 to net46 it still picking the dll present inside netcoreapp2.0 folder.

Test -> f:\Automation_Framework\12022018\GTS_CS_FWK\Test\bin\Debug\net46\Test.dll

Build succeeded.
0 Warning(s)
0 Error(s)

Time Elapsed 00:00:00.79

NUnit Adapter 3.9.0.0: Test discovery starting
NUnit Adapter 3.9.0.0: Test discovery complete
[xUnit.net 00:00:00.9136379] Discovering: Test
[xUnit.net 00:00:00.9341569] Discovered: Test
Started debugging process #14184.
NUnit Adapter 3.9.0.0: Test execution started
Debugging selected tests in f:\Automation_Framework\12022018\GTS_CS_FWK\Test\bin\Debug\netcoreapp2.0\Test.dll
NUnit3TestExecutor converted 1 of 1 NUnit test cases
NUnit Adapter 3.9.0.0: Test execution complete
Debugging complete.

If we remove the folder netcoreapp2.0 then unable to debug the code.

kindly help.

thanks

**Comment by egamma** [comment]
Please report the issue against the c# extension https://github.com/OmniSharp/omnisharp-vscode/issues.
