### ISSUE TITLE
Code helper stuck at 100% (and battery quickly running out)

### ISSUE THREAD

**Issue by fpiraneo** [Microsoft/vscode#43970]
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra - 10.13.3

As underlined on the issue #39949 and #20630.

I've the same issue when using the LaTeX extension "LaTeX workshop" (rel. 3.13.0); unfortunately in these two issues I didn't found any definitive solution.

Is this issue still open? Any hint other than "disable all extensions"?

**Comment by egamma** [comment]
Please follow this guide for how to track down a performance issue with an extension https://github.com/Microsoft/vscode/wiki/Performance-Issues.

This guide also describes how to create a CPU profile of the running extensions. 
https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by omnilord** [comment]
Just to provide some diagnostics, I was having this problem as well.  I cycled through all of my extensions disabling/enabling one by one and found that the [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag) v.0.0.15 extension was the culprit (for me at least).

**Comment by fpiraneo** [comment]
I don't have "Auto Rename Tag" extension installed and sometimes (not always) the Code Helper process stuck. I don't think it's related to any extension in particular and unfortunately this will be a big issue when debugging: It happens... often, not always and is not easily reproductible.

**Comment by thecrypticace** [comment]
A (hopefully helpful) datapoint:

My Code Helper processes sometimes stick around even after quitting VS Code. This is when I notice them using the CPU the most. Typically killing the one or two processes using 100%+ of the CPU will kill off the rest of the processes.

**Comment by fpiraneo** [comment]
@egamma Erich, I've found around `code --status` command but I think it's only valid on Microsoft / linux os'es; on MacOS VSCode is a directory and I cannot figure out what's the equivalence; can you point me to the right direction? Thanks a lot.

**Comment by fpiraneo** [comment]
For peoples running under OSX and trying to figure out how to run with `code --status` (like me five minutes ago...) try to look at this: [StackOverflow: How to open Visual Studio Code from the command line on OSX?](https://stackoverflow.com/questions/29971053/how-to-open-visual-studio-code-from-the-command-line-on-osx#29971430)

**Comment by egamma** [comment]
@fpiraneo sorry about that, this is also documented here https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line.

I´ll update the performance issue wiki page https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by thecrypticace** [comment]
@egamma I'll capture some traces and data next time this happens. It seems to occur semi-regularly so I'll do both of these things when it happens again.

**Comment by fpiraneo** [comment]
@egamma Here we are:

```
CPUs:             Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz (8 x 2200)
Memory (System):  8.00GB (1.38GB free)
Load (avg):       6, 6, 6
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron

CPU %	Mem MB	   PID	Process
```
and:
```
fpiraneo:~ >ps aux |grep "Code Helper"
fpiraneo         15707  67,8  1,1  5142812  94512   ??  R     3:39pm  41:07.94 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
fpiraneo         21627   0,0  0,0  4267768    892 s001  S+    4:46pm   0:00.01 grep Code Helper
fpiraneo         21554   0,0  1,0  5119272  86108   ??  S     4:45pm   0:04.42 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
fpiraneo         21543   0,0  2,9  5385252 240504   ??  S     4:45pm   0:06.22 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=99DD107C1FAD31C22DA0A8BD2A326B55 --lang=it --app-path=/Applications/Visual Studio Code.app/Contents/Resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#002b36 --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,3553;4,14,34037;4,15,34037 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --service-request-channel-token=99DD107C1FAD31C22DA0A8BD2A326B55 --renderer-client-id=6
fpiraneo         21429   0,0  0,9  5227072  78816   ??  S     4:45pm   0:03.94 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=46C6C1D355DDF64941285EF1D8EAD57F --lang=it --app-path=/Applications/Visual Studio Code.app/Contents/Resources/app --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,3553;4,14,34037;4,15,34037 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --service-request-channel-token=46C6C1D355DDF64941285EF1D8EAD57F --renderer-client-id=5

```
Hopes this help.

**Comment by egamma** [comment]
@fpiraneo thanks, this shows that the CPU is consumed by the extension host process and therefore this is caused by an extension you have installed.

>15707  67,8  1,1  5142812  94512   ??  R     3:39pm  41:07.94 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost

You can narrow this down by selectively disabling extensions https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled

Alternatively you can create a CPU profile as described above, it is straightforward, see also
https://code.visualstudio.com/updates/v1_19#_running-extensions
