### ISSUE TITLE
Background updater needs to beware if windows is going to sleep/shutdown

### ISSUE THREAD

**Issue by pellea** [Microsoft/vscode#43971]
- VSCode Version: Insider
- OS Version: Win 10

Steps to Reproduce:

1. check for updates (and totally forget you did it ...)
2. put the computer to sleep several times with VSCode still running (maybe not related)
3. close VSCode
4. restart the computer

After the restart, I had no VSCode installed. I had to reinstall it completely.

**Comment by joaomoreno** [comment]
@pellea Was the `C:\Program Files\Microsoft VS Code Insiders` folder completely gone?

**Comment by pellea** [comment]
I don't know. I pinned VSCode to the taskbar and when I clicked on the shortcut; it was invalid.

**Comment by joaomoreno** [comment]
OK. If it happens again, let me know.

**Comment by pellea** [comment]
It happened again (though I forced it a little bit).

Here are the only remaining files in the VSCode folder:

```
resources
tools
_
snapshot_blob.bin
ucrtbase.dll
ui_resources_200_percent.pak
unins000.dat
unins000.exe
vcruntime140.dll
views_resources_200_percent.pak
```

**Comment by joaomoreno** [comment]
How did you force it a little bit?

**Comment by pellea** [comment]
I restarted my computer quickly after having closed vscode.

There is the screen where Windows tells us a process  is blocking the restart but it has still restarted without delay and without giving me the possibility to cancel the restart.

**Comment by joaomoreno** [comment]
@pellea Awesome that you test this so nicely! I've pushed some changes which should prevent Windows from forcefully shutting down our updater tool:

https://github.com/Microsoft/inno-updater/compare/143ec7d1047fecc9c723995efbf7b2902be9450a...bfbe0447bc937a2a44b1280d12dc572899b62823

**Comment by mjbvz** [comment]
Verified that windows now warns you if you try to shut down while the installer is running
