### ISSUE TITLE
Provide proper display name, description and icon for out of the box extensions

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#43978]
With #17068, Built-in extensions will be shown in the extension viewlet. This needs adopting all extensions to provide proper name, description, read me and an icon (if no icon is provided it, defaults to VS Code icon) so that user will know about what each extension is for.

I am assigning users based on the last change done to the extension. If you are not the owner, please assign it to actual owner, otherwise me. Also please check it off, if the current details are good enough

**NOTE:** Make sure display name and descriptions are translated using `nls`

- [x] bat @aeschli 
- [x] clojure @aeschli 
- [x] coffeescript @aeschli 
- [x] configuration-editing @sandy081
- [x] cpp - @sandy081
- [x] csharp @aeschli 
- [x] css @aeschli 
- [x] diff @aeschli 
- [x] docker @aeschli 
- [ ] emmet @ramya-rao-a 
- [x] extension-editing @sandy081
- [x] fsharp @aeschli 
- [x] git @joaomoreno  
- [x] gitsyntax @joaomoreno  
- [x] go @ramya-rao-a 
- [x] groovy @aeschli 
- [x] grunt @dbaeumer  
- [x] gulp @dbaeumer 
- [x] handlebars @aeschli 
- [x] hlsl @aeschli 
- [x] html @aeschli 
- [x] ini @aeschli 
- [x] jake @dbaeumer 
- [x] java @aeschli 
- [x] javascript @mjbvz 
- [x] json @aeschli 
- [x] less @aeschli 
- [x] log @sandy081 
- [x] lua @aeschli 
- [x] make @aeschli 
- [ ] markdown @mjbvz 
- [x] merge-conflict @chrmarti 
- [x] npm @egamma  
- [x] objective-c @aeschli 
- [x] perl @aeschli 
- [ ] php @roblourens 
- [x] powershell @aeschli 
- [x] python @aeschli 
- [x] r @aeschli 
- [x] razor @aeschli 
- [x] ruby @aeschli 
- [x] rust @aeschli 
- [x] scss @aeschli 
- [x] shaderlab @aeschli 
- [x] shellscript @aeschli 
- [x] sql @aeschli 
- [x] swift @aeschli 
- [x] theme-abyss @sandy081 
- [x] theme-defaults @sandy081
- [x] theme-kimbie-dark @sandy081
- [x] theme-monokai-dimmer @sandy081
- [x] theme-monokai @sandy081
- [x] theme-quietlight @sandy081
- [x] theme-red @sandy081
- [x] theme-seti @sandy081
- [x] theme-solarized-dark @sandy081
- [x] theme-solarized-light @sandy081
- [x] theme-tomorrow-night-blue @sandy081
- [ ] typescript @mjbvz 
- [x] vb @aeschli 
- [x] yaml @aeschli

**Comment by sandy081** [comment]
Also please make sure that Read me is updated.

**Comment by aeschli** [comment]
@sandy081 Do we have a common template for the readme? Or maybe have it generated from the description? 
IMO it would be good to mention that the extension is a built-in extension, cannot be uninstalled but disabled.

**Comment by egamma** [comment]
Now that @joaomoreno has started it with the git extension I suggest that we add icons for the bundled extensions as well.

**Comment by ramya-rao-a** [comment]
Any guidelines on where should (or shoudlnt) we get the icons from?

**Comment by sandy081** [comment]
Read me will be auto generated from extension manifest details if not provided

![image](https://user-images.githubusercontent.com/10746682/36678792-f6f19714-1b11-11e8-8692-ee59368bb386.png)

**Comment by sandy081** [comment]
@aeschli, @ramya-rao-a, @joaomoreno, @dbaeumer, @mjbvz, @chrmarti, @egamma, @roblourens 

Looks like most of the extensions versions are at `0.1`. Can you please check your extensions versions and bump them at least to `1.0`

**Comment by joaomoreno** [comment]
Done!

**Comment by aeschli** [comment]
Done!

**Comment by ramya-rao-a** [comment]
Done for Emmet. The only remaining thing for Emmet is the icon for which I have contacted the Emmet library owner. Should be able to get something in a day or 2

**Comment by ramya-rao-a** [comment]
@sandy081 I've updated all extensions such that
- the least version is 1.0.0
- the Display Name for language related extensions are appropriately Basics/Features
- removed "and other language features" from the description for all Language Basics extensions. That will just mislead users to expect more from the extension

The only thing left is to get icons for
- Emmet
- Typescript
- Html
- Css
- Json
- Markdown
- Php

which is tracked in #44626.

We can close this issue

**Comment by sandy081** [comment]
Thanks @ramya-rao-a 

Closing this
