### ISSUE TITLE
Task> Run Task fails to start cygwin zsh integrated terminal on Windows

### ISSUE THREAD

**Issue by maarek** [Microsoft/vscode#43977]
- VSCode Version: 1.20.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Set up integrated terminal settings for cygwin zsh. 
    "terminal.integrated.shell.windows": "C:\\.babun\\cygwin\\bin\\zsh.exe",
    "terminal.integrated.shellArgs.windows": [],
2. Run "Task> Run Task" and choose any task.
    "npm: start"
3. Verify terminal execution
    > Executing task in folder test: npm run start <
    /usr/bin/zsh: can't open input file: /d
    The terminal process terminated with exit code: 127
    Terminal will be reused by tasks, press any key to close it.

/d argument commonly passed to cmd is getting passed to the zsh integrated terminal.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by egamma** [comment]
@dbaeumer not clear to me where the /d argument gets appendend.

The npm script runner creates the following ShellExecution:
![image](https://user-images.githubusercontent.com/172399/36390223-9562f00c-15a2-11e8-96f4-260408dc4213.png)

**Comment by dbaeumer** [comment]
The terminal execution adds the /d assuming that under Windows the default is cmd.exe if we don't know it. I can add support for zsh.exe but a better way would be to control the shell for tasks independently from the terminal.

**Comment by dbaeumer** [comment]
The terminal execution adds the /d assuming that under Windows the default is cmd.exe if we don't know it. I can add support for zsh.exe but a better way would be to control the shell for tasks independently from the terminal.

Added zsh.exe. Closing since I have and issue to seperate the terminal from task shell.
