### ISSUE TITLE
checkJS enablement: review the @ts-ignore comments

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#43973]
We have enabled type checking for JS in the `build` folder. Some warnings were disabled with an `@ts-ignore` comment. Please review these warnings and check whether these are indeed type errors or whether the typings need to be fixed.

To search for the warnings search for 
```
// @ts-ignore review
```
Based on git blame the code with these warnings was last touched by @joaomoreno and @dbaeumer

**Comment by dbaeumer** [comment]
@joaomoreno thanks!
