### ISSUE TITLE
Search: dismissing a search result should move to next result

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#43976]
Steps to Reproduce:

1. have search results
2. dismiss the last search result of a file
3. the next file is selected

=> it would be great if the search result within that next file is selected instead

**Comment by bpasero** [comment]
@roblourens still reproduces I think:
![flicker_chrome58](https://user-images.githubusercontent.com/900690/39250889-43e6cd06-48a2-11e8-81f7-9ce9b67a57b2.gif)

**Comment by roblourens** [comment]
That's not the case I was looking at, but I can fix that too.

**Comment by bpasero** [comment]
Better, I filed https://github.com/Microsoft/vscode/issues/48740 as follow up 👍
