### ISSUE TITLE
PSScriptAnalyzer, The light blub is display on the wrong line

### ISSUE THREAD

**Issue by IBM-CliveAllgood** [Microsoft/vscode#43975]
### Issue Type
Bug

### Description

Create a new Powershell file
Type in the following powershell command to get a list application on the local computer.

`Get-AppxPackage | select name, packagefullname`

The PSScriptAnalyzer look at the text and hi-lights the word 'select' as it should be Select-Object , Normally the Light blub icon appears on the same line as the typo, Between the line number and the text on the line.

BUT Visual Stuido Code 1.20.1 now display the icon on the next line below and indenet 

![image](https://user-images.githubusercontent.com/27344602/36387232-3d86c8c0-1590-11e8-9c77-462e44d0f775.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|Memory (System)|7.88GB (3.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\code\Laptop\powershell1.ps1|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
xml|Dot|1.9.2
vscode-auto-open-markdown-preview|hnw|0.0.4
VBScript|lug|0.0.2
python|ms-|2018.1.0
PowerShell|ms-|1.5.1
html-preview-vscode|tht|0.1.1
markdown-all-in-one|yzh|1.0.5

</details>
Reproduces only with extensions

**Comment by jrieken** [comment]
That's the designed behaviour. The lightbulb sits below because showing it on the same line would hide its start. On lines that are indented, which is a very frequent case, the light bulb shows on the same line. Only when the *first* line starts at column 1 the light bulb shows below
