### ISSUE TITLE
Javascript Syntax coloring broken on flow cast

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#43974]
If i refer to this documentation : https://flow.org/en/docs/types/casting/ 

This javascript is valid (and coloring in github is fine too) :

```javascript
export class BrowserWebView extends Component {
  container: HTMLElement | void;

  constructor(props: Object) {
    super(props);

    (this: any).onSizeChange = this.onSizeChange.bind(this);
  }

  componentWillUnmount() {
    window.removeEventListener('resize', this.onSizeChange);
  }
}
```

But the syntax coloring does not render correctly in vscode : 

![image](https://user-images.githubusercontent.com/5599375/36386658-c6ee20f8-1596-11e8-8758-9644c84f6a83.png)

You can notice, that the whole line and next are coloring broken, until finding a "{"

**Comment by egamma** [comment]
The coloring is not legal JS since it includes Flow type annotations. When I remove the type annotations then the coloring is correct. 

![image](https://user-images.githubusercontent.com/172399/36388809-5ba21370-159d-11e8-81c7-b2f6bd34a759.png)
