### ISSUE TITLE
add warning dialog when running powershell(and other integrated apps) and vscode is closing 

### ISSUE THREAD

**Issue by abvaalgit** [Microsoft/vscode#43986]
when vs code is closing maybe powershell is pushing project to git ,so vs must notify a dialog to user is is running are you sure

**Comment by Tyriar** [comment]
Set `terminal.integrated.confirmOnExit` to true in your settings

**Comment by abvaalgit** [comment]
open the issue ..
this is not my meaning ....
its warning always when set true ..i dont want it 
i want give me warning just when working (like cloning from git ) not always integrated opened  just when working and scripting
