### ISSUE TITLE
Windows - The terminal process exited with code 5

### ISSUE THREAD

**Issue by yarabatinaresh** [Microsoft/vscode#43980]
### Issue Type
Bug

### Description

Hi,
I have updated VS code with latest version today. I am getting below issue,

Windows - The terminal process exited with code 5

Steps to Reproduce:

Open VSCode
Open integrated terminal
The terminal process terminated with exit code 5

Please do needful asap.

### VS Code Info
VS Code version: Code 1.20.1
OS version: Windows_NT x64 10.0.14393

**Comment by zigang93** [comment]
Please research/search issue before you open new issue.  https://github.com/Microsoft/vscode/issues/43169
