### ISSUE TITLE
[Flatpak release]: ssh_askpass not found

### ISSUE THREAD

**Issue by charlydelta** [Microsoft/vscode#43982]
### Issue Type
Bug

### Description

- Use Debian Stretch (GNOME + Wayland), everything up-to-date
- Use flatpak from Debian's repos
- Install VS Code using the package (which appears to be officially) distributed at flathub.org
- Start VS Code and try to use Git integration (anything, here `git pull` as an example) on a repo where you use SSH authentication with a SSH key protected by passphrase
  - Error log (as a side note: `/usr/libexec/ssh-askpass` does indeed not exist)
```
git pull
ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Please note

- Error **not reproducible** in `gnome-terminal` (external)
- From global config: `"terminal.integrated.shell.linux": "/bin/bash"`
- Error **not reproducible** in integrated terminal (at least I get a prompt there to input my passphrase for my SSH key)
- SSH key is unlocked, so if I run `git pull` from `gnome-terminal` (external), I do not need to enter the passphrase
- In the integrated terminal I get asked for the passphrase for each command,  so VS Code obviously cannot access the unlocked SSH keys (maybe because of the sandbox? I don't know if this can even be addressed...)
- In the integrated terminal, I do not have access to the commands `ssh-add` or similar. I thought I could just add the SSH key in the terminal to unlock it at least in the sandbox, but to no avail

### Expected behaviour

- I expect the same behaviour as in the `.deb` release where I do not need to unlock the keys and it "just works" out of the box

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Debian Stretch (Kernel: Linux x64 4.9.0-5-amd64)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 3284)|
|Load (avg)|0, 0, 0|
|Memory (System)|15.59GB (0.24GB free) (`htop` says more than 11GB free)|
|Process Argv|/app/extra/vscode/code --extensions-dir=/home/usr/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
We do not ship a flatpak, see https://code.visualstudio.com/docs/setup/linux for the official/trusted channels.

**Comment by charlydelta** [comment]
Sorry for the inconvenience, I thought it was an official channel.

For future reference - I opened an issue in the flathub repositories: https://github.com/flathub/com.visualstudio.code/issues/23
