### ISSUE TITLE
Glitches

### ISSUE THREAD

**Issue by jmmccota** [Microsoft/vscode#43984]
### Issue Type
Bug

### Description

When I'm programing react I can't invoke format code and jump to code, It start to happen after last update. When I restart VS Code, works fine for a few minutes, until, stop.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|Memory (System)|31.92GB (22.54GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|
|Video Board|AMD Radeon R7 270 (2Gb DDR3) + Intel Graphics 5550|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.6
EditorConfig|Edi|0.12.0
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.1.0

</details>
Reproduces without extensions

**Comment by egamma** [comment]
Cannot reproduce given the steps provided above, please reopen the issue and provide more information,
