### ISSUE TITLE
Cannot revert file via command palette

### ISSUE THREAD

**Issue by diminutivesloop** [Microsoft/vscode#43983]
### Issue Type
Bug

### Description
1. Open a file.
2. Edit the file without saving.
3. Open the command palette (ctrl+shift+p) and select the "File: Revert File" command.

Result: The unsaved file edits are not discarded. Note that this same operation succeeds when performed via the application menu (File > Revert File).

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930MX CPU @ 3.00GHz (8 x 3192)|
|Memory (System)|31.94GB (17.95GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|0.24.0
find-related|eam|0.6.0
gitlens|eam|8.0.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
vscode-ghc-mod|hoo|1.2.0
hoogle-vscode|jca|0.0.4
language-haskell|jus|2.4.0
vscode-duplicate|mrm|1.2.0
debugger-for-chrome|msj|4.1.0
code-settings-sync|Sha|2.8.7
vscode-quick-scope|ska|0.1.3
vim|vsc|0.10.13

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@isidorn looks like a regression

**Comment by isidorn** [comment]
@diminutivesloop thanks for reporting, you can find the fix in the vscode insiders from tomorrow
