### ISSUE TITLE
Context list for code completion takes forever to fill, stuck on "Loading..."

### ISSUE THREAD

**Issue by LukaszGrela** [Microsoft/vscode#43994]
### Issue Type
Performance Issue

### Description

Suddenly the context lists stops working and displays the "Loading..." text forever e.g. I'm typing some import and the path is not populated in the context list or I'm trying to ctrl click on functiona name to get to the source. After reloading window it starts to work again.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6410 APU with AMD Radeon R5 Graphics     (4 x 1996)|
|Memory (System)|6.96GB (1.68GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe C:\dev\other\ChromeExtensions\tablist-reactjs|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

|pid|CPU|Memory (MB)|Name|
|---|---|---|---|
|16796|3|69|code main|
|1404|0|63|-- powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"|
|13092|0|7|---- console-window-host (Windows internal process)|
|4848|0|47|-- shared-process|
|13244|5|54|-- gpu-process|
|13444|1|57|-- shared-process|
|17712|25|155|-- window (background.js - tablist-reactjs - Visual Studio Code)|
|8292|0|14|---- watcherService |
|3824|0|6|------ console-window-host (Windows internal process)|
|8548|0|11|---- electron-crash-reporter|
|15892|0|51|---- extensionHost|
|6252|0|107|------ electron_node electronForkStart.js tsserver.js |
|6988|0|48|-------- electron_node typingsInstaller.js tsserver.js typesMap.js |
|13340|0|24|------ electron_node jsonServerMain.js |
|16084|0|31|------ electron_node cssServerMain.js |
|16216|0|66|------ electron_node htmlServerMain.js |
|17136|0|27|------ electron_node server.js |

</details><details>
<summary>Workspace Info</summary>

```
|  Window (background.js - tablist-reactjs - Visual Studio Code)
|    Folder (tablist-reactjs): 52 files
|      File types: js(21) png(18) scss(6) json(3) babelrc(1) gitignore(1)
|                  html(1) lock(1)
|      Conf files: package.json(1) webpack.config.js(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.6
react-native-react-redux|EQu|1.4.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-beautifier|mic|1.7.2
node-debug2|ms-|1.20.0
vscode-react-native|vsm|0.5.7

</details>
Reproduces without extensions

### Screenshot
![image](https://user-images.githubusercontent.com/7643591/36400713-aa137076-15ca-11e8-9f1e-10eb08f62d93.png)

![image](https://user-images.githubusercontent.com/7643591/36400772-e4afb7b2-15ca-11e8-9ee6-37da8f7fd69a.png)

**Comment by LukaszGrela** [comment]
Is there any update on this issue? Worth noting is that this happens so far only on my Windows 10 machine, on MacBook Pro (mid 2012) with latest OS works fine.

**Comment by mjbvz** [comment]
Do you see this in the latest VSCode insiders?

**Comment by LukaszGrela** [comment]
Yes, latest VSCode, working on React with babel, webpack, usually named imports break it. Is there any debug tool I could use to monitor and see what happens behind the scenes?

**Comment by mjbvz** [comment]
Thanks. Can you also try following [these instructions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) to install `typescript@next` in your workspace. I know that typescript@next fixed a few similar sounding issues.

If that still doesn't work, try collecting the TypeScript server logs so we can investigate:


1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. In VS Code, inside a JS/TS file run the`Open TS Server Logs` command. This should open a file with as `tsserver.log` file in it. 

In that log file, look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by LukaszGrela** [comment]
@mjbvz I've got a log, however there is no obvious error in it :(

**Comment by LukaszGrela** [comment]
Sure, can I email it?

**Comment by mjbvz** [comment]
Yes, to matb at microsoft.com
