### ISSUE TITLE
Detect Indentation from Content doesn't work

### ISSUE THREAD

**Issue by yoizfefisch** [Microsoft/vscode#43999]
### Issue Type
Bug

### Description

I have an HTML file open, click on the Tab Size button in the taskbar. From the command pallette that pops open I choose Detect indentation from content. The tab size doesn't change (stays at 4). In my preferences I can see that HTML is supposed to be 2 tabs.
I have the same issue with a CSS file.
HTML worked once, CSS never worked.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-4500M APU with Radeon(tm) HD Graphics    (4 x 1896)|
|Memory (System)|3.46GB (1.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|3.2.1

</details>

**Comment by alexandrudima** [comment]
@yoizfefisch Indentation is controlled via 3 settings:

```js
  // When opening a file, `editor.tabSize` and `editor.insertSpaces` will be detected based on the file contents.
  "editor.detectIndentation": true,

  // Insert spaces when pressing Tab. This setting is overridden based on the file contents when `editor.detectIndentation` is on.
  "editor.insertSpaces": true,

  // The number of spaces a tab is equal to. This setting is overridden based on the file contents when `editor.detectIndentation` is on.
  "editor.tabSize": 4,
```

If you want all files to always have `tabSize: 2`, you must set:
```js
"editor.detectIndentation": false,
"editor.tabSize": 2
```

`editor.detectIndentation` and the associated action, Detect Indentation From Content, means that the content (the text!) will be analyzed and tab settings that best match that content will be used. If the content uses mostly 4 spaces, tab size 4 will be chosen, as that would best match that content.
