### ISSUE TITLE
Adding C/C++ extension to recommended list of plugins 

### ISSUE THREAD

**Issue by asthana86** [Microsoft/vscode#4399]
Add the Microsoft C/C++ extension for VSCode to the list of recommended plugins

Fully Qualified Name: ms-vscode.C/CppTools
Extensions: .c, .cpp, .h, .hpp, .cc, .cxx, .hh, .hxx

**Comment by egamma** [comment]
We must with this until the extension is available in the market place as a preview. Otherwise we recommend something that doesn't exist.

The extension can be published as a preview once https://github.com/Microsoft/vscode-vsce/issues/82 is available.

// @joaomoreno

**Comment by asthana86** [comment]
One change to the above request:

Add the Microsoft C/C++ extension for VSCode to the list of recommended plugins

Fully Qualified Name: **ms-vscode.C-CppTools**
Extensions: .c, .cpp, .h, .hpp, .cc, .cxx, .hh, .hxx

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-distro#24

**Comment by egamma** [comment]
@asthana86 fyi the C++ extension has been added to the recommendations. It will be recommended as soon as it gets added to the market place.
