### ISSUE TITLE
Error debug VS code

### ISSUE THREAD

**Issue by fonsecapontes** [Microsoft/vscode#43998]
- VSCode Version: 1.20.1
- OS Version: Windows 10

When I went debug the projet, received this error: 
'Cannot connect to runtime process, timeout after 10000 ms - (reason: Got a response from the target app, but no target pages found).'

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Possibly you have something else in debug mode on that port? What if you set some other random port in the launch config like `"port": 9230`?
