### ISSUE TITLE
Launch.json Missing after Launch from NPM with Child Processes

### ISSUE THREAD

**Issue by mdhornet90** [Microsoft/vscode#43996]
- VSCode Version: 1.20.1
- OS Version: macOS Sierra

I'm using `cluster` in a project to spawn child processes. When I include the `autoAttachChildProcesses` flag in the npm launch listed in `config.json` and launch it from the debug window, the cluster comes online but the gear icon next to the run menu pops an indicator that it can't find `launch.json`. The only way to resolve the issue is making some sort of change that updates the configurations listed, saving it, and undoing it.

I noticed [this issue](https://github.com/Microsoft/vscode/issues/43273) in the latest round of patches but I'm not sure it's actually related. I've tested this behavior with and without a workspace. This behavior did not occur in 1.20.0.

The above behavior can be observed when running the code in [this repo](https://github.com/mdhornet90/VSCode-Launch-Issue)

Steps to Reproduce:
1. Launch the demo project's only run configuration

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I tried reproing this using your repo in latest insiders and could not.
Can you please try with latest vscode insiders please?
https://code.visualstudio.com/insiders/

**Comment by mdhornet90** [comment]
Just had a chance to confirm that the latest insiders build does not repro the bug in the example project or the actual project I discovered it in. Looks good!
