### ISSUE TITLE
Wakatime plugin

### ISSUE THREAD

**Issue by bartvanderwal** [Microsoft/vscode#44]
Oh, how I would love to have a [WakaTime](https://wakatime.com/) plugin for Visual Studio Code! Don't know if that should have an issue here, as the code'll be elsewhere. But I'll close it if I manage to get it done.

BTW: Great that you opensourced VS Code! I just saw Erich Gamma open source it on Connect(). Amazing, he's the same guy I read the Design Patterns book from during my studies right :P.

**Comment by jrieken** [comment]
there you go :dancers: https://marketplace.visualstudio.com/items/WakaTime.vscode-wakatime

**Comment by bartvanderwal** [comment]
<nowords></nowords>
