### ISSUE TITLE
Does not apply update on restart when the install location is not Applications folder on Mac

### ISSUE THREAD

**Issue by prakashsvmx** [Microsoft/vscode#44007]
- VSCode Version:1.20.1
- OS Version:Mac os Sierra 10.12.3

Steps to Reproduce:

1. Have a older version of VS Code (i.e <1.20.1) 
2. Restart will update visual studio appears. 
3. Click on Update now. 
4. This does not update and restart the VSCode.

Does this issue occur when all extensions are disabled?: Yes/No: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
