### ISSUE TITLE
Would you please add update notify for linux Editor?

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#4400]
- VSCode Version: 0.10.11
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:

1.  VSCode never told me there be newer version released

would you please add a update checker . when new version released . notify linux user to upgrade .

A small pop tip window will be ok, and will help us track the latest VSCode version

**Comment by Tyriar** [comment]
I think thinking about this earlier, we could notify some time in the following month when it's safe to assume there will be a new version released (or pinging update server). https://github.com/Microsoft/vscode/issues/2973 and https://github.com/Microsoft/vscode/issues/229 will supersede this for the majority of cases, but it would still probably be a good thing to have regardless just in case the source repository isn't working or setup for some reason.

**Comment by joaomoreno** [comment]
[We do have it](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/update.ts#L71) but [broke it](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/update-manager.ts#L195) somewhere along the way.

ping @egamma
