### ISSUE TITLE
How can I select UTF-8 with BOM?

### ISSUE THREAD

**Issue by Luberen** [Microsoft/vscode#44005]
I want to change UTF-8 to UTF-8 with BOM through "Reopen with Encoding", but I couldn't find UTF-8 with BOM.
I added `"files.encoding": "utf8bom"` into Preference file but it doesn't work.
How can I select UTF-8 with BOM?

**Comment by bpasero** [comment]
@Luberen to be clear you want to add a BOM to a document?

**Comment by Luberen** [comment]
@bpasero yes I want to add BOM to the document.

**Comment by bpasero** [comment]
@Luberen then just pick "Save with Encoding" instead of "Reopen with Encoding".

**Comment by Luberen** [comment]
@bpasero I can't find UTF-8 **with** BOM in there.

**Comment by bpasero** [comment]
@Luberen ![flicker_chrome58](https://user-images.githubusercontent.com/900690/36417340-f867c57c-162b-11e8-8c0f-b30ab82e303a.gif)

**Comment by Luberen** [comment]
@bpasero Oh, I tried to find in 'Reopen' with Encoding. Why are they different?
Anyway I set UTF-8 BOM now. Thanks

**Comment by bpasero** [comment]
@bpasero they are different, the one reopens with encoding and the other saves with encoding?
