### ISSUE TITLE
print monitor can't show up to korean (error message, etc...)

### ISSUE THREAD

**Issue by waterme10n747** [Microsoft/vscode#44008]
### Issue Type
Bug

### Description

execute any file in VS Code, print monitor(message window) can't show up to korean but english has not problem.
Because of this problem, Can't check up to contents of errors in korean.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|Memory (System)|7.95GB (0.69GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
solidity-extended|bea|3.0.2
LogFileHighlighter|emi|2.1.1
vscode-great-icons|emm|2.1.24
php-intellisense|fel|2.2.8
code-runner|for|0.8.7
solidity|Jua|0.0.31
intellij-idea-keybindings|k--|0.2.21
Go|luk|0.6.76
cpptools|ms-|0.15.0
ActiveFileInStatusBar|Ros|1.0.3
code-settings-sync|Sha|2.8.7
vscode-fileutils|sle|2.7.1
vscode-todo-highlight|way|0.5.11

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
> Reproduces only with extensions

This is probably a bug with the code runner extension, you should find out the extension causing the issue and report against that.
