### ISSUE TITLE
Generated npm task list is invalid, missing comma in tasks array

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#4401]
- VSCode Version: alpha 0.10.12
- OS Version: Windows 8

Steps to Reproduce:

1. Tasks: Configure Task Runner, select npm
2. Missing comma between tasks "update" and "test"
"tasks": [
		{
			"taskName": "install",
			"args": ["install"]
		},
		{
			"taskName": "update",
			"args": ["update"]
		}
		{
			"taskName": "test",
			"args": ["run", "test"]
		}
	]

**Comment by dbaeumer** [comment]
Got already fixed.
