### ISSUE TITLE
Import hint is not shown when typing a name that is exported from a TypeScript local package

### ISSUE THREAD

**Issue by vitalysoftech** [Microsoft/vscode#44019]
- VSCode Version: 1.20.1.
- OS Version: Windows 7 Professional SP1.

Steps to Reproduce:

1. Create "package1" folder and run "npm init" inside. Use all defaults, but for main entry point use "index.ts".
2. Add index.ts to the folder and add simple content there:
```
export function sayHello():string
{
    return "Hello";
}
```
3. Go one folder up and create "package2" folder (it must be in the same folder as "package1").
4. Run "npm init" inside "package2". Use all defaults, but for main entry point use "index2.ts".
5. Add empty "index2.ts" file.
6. Inside "package.json" for "package2" add the following depedency:

```
"dependencies": {
    "package1": "file:../package1"
}
```

7. Inside "package2" folder run "npm install". Make sure that "package1" link was added inside node_modules.
8. Open "package2" folder in VS Code.
9. Open "index2.ts" file for editing and start typing "sayHello". Notice that editor doesn't suggest you to import sayHello from "package1", but ideally should to. index.ts file from package1 is written in TypeScript so editor should have all the required information for the hint.

Is it a place for improvement? How can I make VS Code showing me hints? I want to have a multi-package workspace and having no hints for imports makes it hard to develop.

Thanks in advance.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22252
