### ISSUE TITLE
building never ends

### ISSUE THREAD

**Issue by GGeorgi** [Microsoft/vscode#44018]
- VSCode Version: 1.20.1
- TSC Version: 2.7.1
- Commit f88bbf9137d24d36d968ea6b2911786bfe103002
- Date 2018-02-13T15:34:36.336Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64
- OS Version: windows 10

Here is my `tasks.json` file

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "option": "watch",
            "problemMatcher": [
                "$tsc-watch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

```
After `ctrl+shift+b` in bottom-left corner I keep seeing `Building...`
In `Termnal` window I see this:
```
[12:31:18] Starting compilation in watch mode...
[12:31:22] Compilation complete. Watching for file changes.
```
But `Building...` still there. Also I cannot see problems in Problems tab if I write some wrong code

**Comment by dbaeumer** [comment]
Which shell are you using. This works for me but the output in the shell should be like this:

```
12:31:18 Starting compilation in watch mode...

12:31:22 Compilation complete. Watching for file changes.
```

**Comment by GGeorgi** [comment]
in my case output is also 

```
[19:38:20] File change detected. Starting incremental compilation...
[19:38:21] Compilation complete. Watching for file changes.
```
but it shows all the time Building...
![image](https://user-images.githubusercontent.com/1097647/36489330-33da9602-173f-11e8-85af-af34577a1ff2.png)

**Comment by GGeorgi** [comment]
Microsoft Windows [Version 10.0.16299.248]

**Comment by dbaeumer** [comment]
@GGeorgi to double check. Our output has [] around the time. That shouldn't be there and will make the problem matcher not recognize the start / end pattern.

**Comment by GGeorgi** [comment]
@dbaeumer here is info from vscode about:

Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

This problem happened after I updated typescript to 2.7.2 but I'm not sure that it was the reason.

**Comment by dbaeumer** [comment]
It is very likely the reason. I was able to reproduce it now. It is the way how the tsc compiler clears the terminal since 2.7 which confuses our terminal and then the task problem scanning. I will open an issue against the terminal to further track this down.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/44192 for the details.

**Comment by dbaeumer** [comment]
Fixed for February.

See #44192 for steps to verify

**Comment by Tyriar** [comment]
@chrmarti the problem was introduced with TS 2.7.2, 1.20.1 is on 2.7.1 so I'll add verified back.

**Comment by chrmarti** [comment]
@Tyriar I ran a local install of 2.7.2 with 1.20.1. 🤔

**Comment by Tyriar** [comment]
@chrmarti it was also flaky and would only happen about 20% of the time for me (testing on master before the fix).

**Comment by dbaeumer** [comment]
Yes, it is very flaky.
