### ISSUE TITLE
Recommend language pack extensions based on locale

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44012]
Now that we are pulling language support out from the default product and into extensions, we should recommend appropriate language pack extensions based on the users locale

**Comment by ramya-rao-a** [comment]
@dbaeumer @sandy081 Are we pulling out the bundled translations out of the product for 1.21? If not, then this recommendation feature should not go out as well.

**Comment by dbaeumer** [comment]
@ramya-rao-a no we don't. However for this release we should recommend the extensions that are in the market place. In VS Code I do white list right now the bundled languages so that they get special treatment :-). They are here: https://github.com/Microsoft/vscode/blob/master/src\main.js#L283

**Comment by ramya-rao-a** [comment]
@dbaeumer I have added a check so that we recommend language packs only for the non core languages.

FYI https://github.com/Microsoft/vscode/blob/9a940305cb69991aa3af112db473ba324b6978c5/src/vs/base/common/platform.ts#L106 is the language I am using to recommend the language packs

**Comment by ramya-rao-a** [comment]
@danyeh Can you re-publish the 4 language packs at https://github.com/Microsoft/vscode-loc after updating your local `vsce` tool to the latest version? This will add correct tags to these extensions which will help in search.

We cannot verify the recommendation feature without these tags

**Comment by sandy081** [comment]
Verified from dev.

**Comment by ramya-rao-a** [comment]
@sandy081 How did you verify this? The tags aren't present in the extensions in the marketplace yet.

**Comment by sandy081** [comment]
@ramya-rao-a Published a dummy extension contributing localizations and verified that this extensin is recommended by running from sources. (Have to comment a check in the source though)

**Comment by ramya-rao-a** [comment]
Can you point me to the dummy extension you published?

**Comment by sandy081** [comment]
I unpublished it after testing. It's simple. Add localizations contribution without any translation files and published. Made sure that extension was recommended (in code, hardcode the language to `languageId` you mentioned in the extension)
