### ISSUE TITLE
Upon resizing the window, opened terminal gets blank

### ISSUE THREAD

**Issue by vaibhavagrawal2912** [Microsoft/vscode#44010]
- VSCode Version: 1.20.1
- OS Version: Windows 7 Professional

Steps to Reproduce:

1. Open vs code maximized.
2. Resize and reduce the height of editor.

Does this issue occur when all extensions are disabled?: Yes
![capture1](https://user-images.githubusercontent.com/33507194/36410058-e9b47d50-1634-11e8-92e5-4e46be114fe9.PNG)
![capture2](https://user-images.githubusercontent.com/33507194/36410060-e9df85b8-1634-11e8-9a55-0ae8f056614e.PNG)

Upon resizing to its full height, it remains blank only.

**Comment by edward-ganuelas** [comment]
I have this issue as well when I move VSCode to another monitor. Windows 10 professional.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/42999

**Comment by vaibhavagrawal2912** [comment]
But this is not yet fixed in the latest version also!!

**Comment by Tyriar** [comment]
@vaibhavagrawal2912 it will be fixed in the next version 1.21, in the meantime hide and show the terminal to get things displaying again (ctrl+\`, ctrl+\`)
