### ISSUE TITLE
MSSQL

### ISSUE THREAD

**Issue by willemavjc** [Microsoft/vscode#44016]
### Issue Type
Bug

### Description

Line comments are not supported even though it seems it is configured with the tmLanguage file of the (microsoft) mssql extension.

Example:
```sql
-- This is a sql line comment <== not considered as a comment so not correctly highlighted
create or replace myFunc ( ... )
```

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.0
python|ms-|2018.1.0
vscode-ai|ms-|0.1.7
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
plsql-language|xyz|1.1.2

</details>
Reproduces only with extensions

**Comment by aeschli** [comment]
I'm not able to reproduce the problem. lines starting with `--` are highlighted as comments.
![image](https://user-images.githubusercontent.com/6461412/36416679-08671574-162a-11e8-8856-833dc4456f8a.png)

Can you attach a more complete sample

**Comment by willemavjc** [comment]
![image](https://user-images.githubusercontent.com/321359/36424088-7dcf6c22-1642-11e8-8e23-070982783370.png)

![image](https://user-images.githubusercontent.com/321359/36424105-85a1f42e-1642-11e8-81b7-b7edb61fca07.png)

This is weird. Your example, the same one, does not work here.

**Comment by willemavjc** [comment]
(Aside, what is your script's font? I like it :) By default, it is Consolas which is nice but a little bit different.)

**Comment by willemavjc** [comment]
I found where it comes from.

The Visual Studio Code Tools for AI make it dysfonctions: when I disactivate it, reload, comments are fine; when I reactivate it, reload, comments stop being highlighted.

Perhaps a more global bug within Visual Studio Code: extensions seem to override each others while they should be sealed to their workspace/files type.

![image](https://user-images.githubusercontent.com/321359/36424870-27fe8460-1645-11e8-8de4-b9cf3eabaaca.png)

![image](https://user-images.githubusercontent.com/321359/36424881-3328d69c-1645-11e8-801b-cf133c917c2f.png)
