### ISSUE TITLE
Auto-Completion Feature For Article & paragraph writting

### ISSUE THREAD

**Issue by shrabankr** [Microsoft/vscode#44015]
### Issue Type
Feature Request

### Description

I know VS Code has lot of feature and add-on & I am using few of them. But I have not find any inteligent text auto-completion featute for write long article & paragraph. Thank you

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.15063

**Comment by egamma** [comment]
Please search the market place for available extensions.
