### ISSUE TITLE
Treat semicolon as a commit character for js/ts

### ISSUE THREAD

**Issue by GufNZ** [Microsoft/vscode#44011]
### Issue Type
Bug

### Description

```javascript
// Controls if suggestions should be accepted on commit characters. For instance in JavaScript the semi-colon (';') can be a commit character that accepts a suggestion and types that character.
  "editor.acceptSuggestionOnCommitCharacter": true,
```
But when I type e.g. `;` with a suggestion selected, the selection is not inserted, but the `;` is.

I tried setting some keys to run `acceptSelectedSuggestion` or `acceptSelectedSuggestionOnEnter` (what's the difference between these anyway?) but while that commits the suggestion, it eats the key I just pressed, requiring a 2nd press to get to where I want to be.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|15.89GB (3.07GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.6
vscode-npm-script|eg2|0.3.3
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
code-clip-ring|Sir|0.0.4
vscode-todo-highlight|way|0.5.11
markdown-all-in-one|yzh|1.0.5

</details>
Reproduces without extensions

**Comment by egamma** [comment]
@GufNZ does this happen in TypeScript/JavaScript? Please add some screenshots that illustrate the problem.

**Comment by GufNZ** [comment]
JavaScript (ES6).

I don't have the code handy at the moment, but for example I have an object called `state` with properties on it, but pressing `s` `t` `a` (autocomplete shows up, with `state` selected) `.` results in `sta.` rather than `state.` as expected given that setting.

**Comment by jVanZwieten** [comment]
I've found this functionality to be inconsistent. It seems that you have to hit `tab` to accept the first suggestion, and from then on VSCode will properly accept the suggestions *and* type what you type (so in your scenario, you'd get `state;` by hitting `;`

Furthermore, when it does work, it has the wrong undo order. As per VS, if I hit `undo` in your scenario, the code would revert to `sta;` assuming that I wanted to undo what I didn't explicitly typed.

 Because of the inconsistency and improper undo behavior, I've actually [written an extension](https://github.com/jVanZwieten/punctual-intellisense) to implement the proper behavior. My limitation so far is that I can't detect if the suggestion is a snippet, a limitation in the extension API, which should not be accepted on punctuation.

**Comment by jrieken** [comment]
It's a two-step-thing: Extensions must enumerate accept characters per completion, the feature must be enabled, and one of the character must be typed when a completion is active. So, it depends and we are really requiring more input from @GufNZ on this.

**Comment by GufNZ** [comment]
I am doing a lot of work in .js and .vue files - sounds like the extension for .vue files (vetur) might be missing something?

**Comment by mjbvz** [comment]
`;` is not registered as a commit character for our built-in javascript and typescript support. Seems that C# does register it as one ([along with many others](https://github.com/OmniSharp/omnisharp-vscode/blob/563a1aa58d31a20e69241c5fa0119b457636318f/src/features/completionItemProvider.ts#L15))

We can look into adding `;` as a commit character

**Comment by dyyylan** [comment]
Is there any way to disable commit characters? It seems `,` will accept a suggestion, and with auto-importing enabled in javascript, I'm getting random imports when trying to type function arguments. 

E.g. when typing out the following function:
<img width="768" alt="screen shot 2018-07-13 at 11 31 46 am" src="https://user-images.githubusercontent.com/3457993/42705386-64258a4a-8690-11e8-9cc2-ec7381e4f03e.png">

simply continuing typing (pressing `,` to add another function argument) will change what i typed into some random import and add an import. This causes you to have to very slowly type code in case some variable triggers intellisense and starts adding random imports to your file...

I'd prefer to **only ever** accept an intellisense suggestion by pressing the enter key. Is something like this possible?
