### ISSUE TITLE
Integrated terminal makes vim crash

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#44029]
I stubbled upon a weird problem a few days ago: I am using git (and vim that gets bundled with Windows git, that's not the one from bash/wsl).

Since a few days, calling `git commit -a` from the integrated terminal returns this error:

``` 
E:\Docs\Dev\onmap_v6\yo\editor>git commit -a
hint: Waiting for your editor to close the file...       0 [main] vim 4480 C:\Program Files\Git\usr\bin\vim.exe: *** fatal error - cmalloc would have returned NULL
   8411 [main] vim 4480 cygwin_exception::open_stackdumpfile: Dumping stack trace to vim.exe.stackdump
Aborting commit due to empty commit message.
```

The `git commit -a` command calls the `vim` command which crashes.

The weird thing is that calling the same command from an external cmd prompt works, correctly opening vim without any crash:

```
E:\Docs\Dev\onmap_v6\yo\editor>git commit -a
[sp91 54f16c88] ADDED: crop description title (model viewer) fixes #212
 1 file changed, 335 insertions(+), 332 deletions(-)
```
I can reproduce it everytime I need to commit something in this project.

That's on VSCode Insiders:

>Version 1.21.0-insider
Commit 02c12bc59fdede3ab0e423d2755d95470270f2fa
Date 2018-02-20T05:16:19.690Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

And Windows 10 64bit insiders.

**Comment by warpdesign** [comment]
I am using this shell: `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"`.

**Comment by Tyriar** [comment]
@warpdesign can you get the exact version of Windows Insiders you're on?

@bitcrazed a possible Insiders change is causing vim shipped with git to crash.

**Comment by warpdesign** [comment]
@Tyriar build [17101](https://blogs.windows.com/windowsexperience/2018/02/14/announcing-windows-10-insider-preview-build-17101-fast-build-17604-skip-ahead/) (x64).

**Comment by warpdesign** [comment]
It still happens with latest Windows Insider build `17110`.

**Comment by warpdesign** [comment]
Today I had the problem in an external terminal so it's defintely an issue with insider builds and not related to VSCode.

Closing the issue.

Note that I opened up an issue on Windows Feedback Hub [here](https://aka.ms/Gq3t6b).
