### ISSUE TITLE
Search scope goes out of the scope of column selection

### ISSUE THREAD

**Issue by JACK-THINK** [Microsoft/vscode#44025]
### Issue Type

Bug

### VSCode Version:

Code 1.20.1 (f88bbf9, 2018-02-13T15:34:36.336Z)

| Extension | Author | Version |
| :---: | :---: | :---: |
| Python | Microsoft | 2018.1 |

### OS Version:

Windows_NT x64 10.0.16299

### Description:

I've already set "editor.find.autoFindInSelection": true in the user settings.

If I type anything in the blank of find, the search scope will **go out of the scope of selection** made by **column selection(Shift+Alt+mouse drag)** and be a global one.

On the contrary, If I type anything in the blank of find, the search scope will be **the same the scope** of the normal selection made by mouse drag.

Should the search scope go out of the selection scope made by column selection?

### Steps to Reproduce:

1. Set "editor.find.autoFindInSelection": true in the user settings and restart vscode.
2. Open a regular text file.
3. Do a column selection by (Shift + Alt + drag mouse).
4. Make a search by (Ctrl + F) and type in some letters in the blank.
5. You'll find the search scope go out of the selection scope.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/53429 , thanks for your feedback!
