### ISSUE TITLE
Please allow to disable release notes from vscode and its extensions

### ISSUE THREAD

**Issue by l27-0-0-1** [Microsoft/vscode#44020]
### Issue Type
Feature Request

### Description

Frankly, when I open the editor I expect to see what I was doing before, not some extension author looking for work and promoting their social communication channels. I close those immediately anyway, if I was interested I could always open them myself. I would really appreciate a simple toggle in settings to block this completely.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.5.0

**Comment by sandy081** [comment]
@l27-0-0-1 May I know what are you seeing from extensions? I am suspecting this could be coming from the extensions.

**Comment by l27-0-0-1** [comment]
@sandy081 unfortunately I already closed the tab that gitlens opened, but it's not exclusive to extensions. After vscode updates itself it always opens the release notes, I'm not really interested in those.

**Comment by sandy081** [comment]
Ok, please open an issue against the extension for hiding release notes on update. 

@joaomoreno Do we have a setting to not to show the release notes on update?

**Comment by joaomoreno** [comment]
@l27-0-0-1 This would make a good first PR.

**Comment by flurbius** [comment]
Could you point to a file or class that would be a good starting point for looking into this issue?

**Comment by joaomoreno** [comment]
Right here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/update/electron-browser/update.ts#L183

**Comment by l27-0-0-1** [comment]
@joaomoreno unfortunately I have exactly 0 experience with typescript. I'll still try doing this myself, but chances of success are pretty slim tbh.

**Comment by ledettwy** [comment]
Does this issue also cover the release notes for VS Code itself, or just for plugins?

Having to deal with all of VS Code's release notes screens that get spammed in all of my open windows is annoying.

**Comment by jaychasteen** [comment]
@joaomoreno 
I think I have a solution to this issue, but I can't figure out how to go about testing it. How do I make Code think it was just updated?

**Comment by omerlh** [comment]
Is there anything else left to do to close this issue?
