### ISSUE TITLE
Single window prompt for closing multiple unsaved files in an editor group

### ISSUE THREAD

**Issue by richardlawley** [microsoft/vscode#44024]
If you have multiple unsaved documents open and either use the "Close All" function (main use case) or close VS code without hot exit enabled (secondary use case), at present you get a single message box per file.  

I think Visual Studio's approach is better, where you get a single dialog prompting you to "Save changes to the following items":

![image](https://user-images.githubusercontent.com/1608083/36416761-ee56664c-1621-11e8-8918-732d9a65ec9a.png)

**Comment by bpasero** [comment]
@richardlawley what are your exact steps to get the single message boxes? We show combined dialog in many cases already.

**Comment by richardlawley** [comment]
@bpasero I can see the combined dialog when use File > Close Folder, but single message boxes are still received when right click open tab, Close All (Ctrl+K, W), or Close to the Right.

**Comment by bpasero** [comment]
@richardlawley we also show a combined dialog if you pick "Close All", but its true that we are not doing that if you are within an editor group.

**Comment by BenWildeman** [comment]
this becomes a big issue when an F2 rename decides to go ahead and edit things inside node_modules that's not even referencing the thing you're trying to rename

**Comment by georginio** [comment]
+1

**Comment by nihiluis** [comment]
+1 mood killer 

> this becomes a big issue when an F2 rename decides to go ahead and edit things inside node_modules that's not even referencing the thing you're trying to rename

**Comment by pleek91** [comment]
+1

**Comment by MrToph** [comment]
> this becomes a big issue when an F2 rename decides to go ahead and edit things inside node_modules that's not even referencing the thing you're trying to rename

I keep running into this as well and there's no way to just close them. So I need to sit through 100+ dialogs

**Comment by rpdobson123** [comment]
Had this today after moving an index file with automatic import updates. Going to spend the lunch hour clicking "don't save" about 800 times now,

Given that this scenario is likely much less common than needing to close 6 or 7 files and make a decision on each, it would be nice if there was a buried "Close All (Including Unsaved)" option somewhere to just burn all open windows indiscriminately.

**Comment by toddheslin** [comment]
There sorta is...
<img width="529" alt="image" src="https://user-images.githubusercontent.com/1883112/91365738-f516d580-e855-11ea-83f8-3334373bbcda.png">

That little X in the top right hand corner.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/1883112/91365756-ff38d400-e855-11ea-92f8-a6c19995d0c5.png">

**Comment by ChrisD-Woodside** [comment]
Thank you @toddheslin !! never spotted that before - that does the trick!

**Comment by kilometers** [comment]
@toddheslin You've just saved me an hour or two of rapid clicking.

**Comment by AlokKothiyal08** [comment]
Thank you @toddheslin

**Comment by RichardJECooke** [comment]
@toddheslin Where do you see this `x` please? I can't see it in the sidebar

**Comment by toddheslin** [comment]
@RichardJECooke I don't use vscode anymore and my solution was 5 years ago so I highly suspect the UI has changed :-)
