### ISSUE TITLE
highlight indented code block

### ISSUE THREAD

**Issue by pbuzdin** [Microsoft/vscode#44022]
It could be very usefull to highlight indented code block where cursor is, in big files:
![image](https://user-images.githubusercontent.com/1329807/36416593-7f3b84f4-163a-11e8-82a3-8f3d1f278adc.png)

**Comment by egamma** [comment]
This already possible, pls see use these settings

![image](https://user-images.githubusercontent.com/172399/36430475-8c14a2c6-1655-11e8-9bdd-205a2910c1a9.png)

**Comment by pbuzdin** [comment]
@egamma 
i mean this vertical lines:
![image](https://user-images.githubusercontent.com/1329807/36430788-1109a4ac-1667-11e8-9841-83a02f03d1db.png)

**Comment by egamma** [comment]
@pbuzdin This is a duplicate of #14017

**Comment by pbuzdin** [comment]
@egamma thank you!

I found extension as workaround https://marketplace.visualstudio.com/items?itemName=spywhere.guides

**Comment by egamma** [comment]
@pbuzdin this is a nice extension, thanks for pointing it out.
