### ISSUE TITLE
Missing FS events

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#44036]
Seen on macOS

1. Open a new window
2. Open folder A on that window
3. Add folder B to that workspace
4. Cause file events on folder B

The explorer doesn't update, git doesn't refresh, etc.

**Comment by Tyriar** [comment]
This was also reported at https://github.com/Microsoft/vscode/issues/44034, did something change with the file watcher recently?

**Comment by isidorn** [comment]
@Tyriar my issue is older 44034 < 44036. Just for future

**Comment by bpasero** [comment]
@Tyriar let me know if you don't have time for February and I will take over.

**Comment by bpasero** [comment]
Wait...

**Comment by bpasero** [comment]
@joaomoreno wow crazy bug and simple fix, this has been in for 3 months, thanks for pushing on it ❤️

**Comment by joaomoreno** [comment]
Wow. Thanks for fixing!

**Comment by isidorn** [comment]
@bpasero thanks for givin joao a ❤️ and nothing for me

**Comment by joaomoreno** [comment]
@isidorn You gotta push it!

**Comment by isidorn** [comment]
@bpasero I was kidding, though I still take that beer :)

**Comment by Tyriar** [comment]
Thanks for the fix @bpasero :smile:
