### ISSUE TITLE
Powershell syntax highlighting breaks on literal property containing variable

### ISSUE THREAD

**Issue by jmeijrink** [Microsoft/vscode#44035]
### Issue Type
Bug

### Description

Paste below script block in a window with powershell syntax highlighting:

$someVar."boe"
Write-Host "Color coding is still correct"

$name = "boe"
$someVar."$name"
Write-Host "Color coding is broken by variable in literal property"

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (6309a7734b0b0876b263a6a9cb526fc281100089, 2018-02-20T10:24:00.306Z)
OS version: Windows_NT x64 10.0.17074

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz (8 x 2295)|
|Memory (System)|15.91GB (6.00GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0
PowerShell|ms-|1.5.1
team|ms-|1.122.0
vscode-docker|Pet|0.0.24

</details>
Reproduces only with extensions

![image](https://user-images.githubusercontent.com/788844/36427386-60332f72-164d-11e8-9fc8-c358b6df92fa.png)

**Comment by aeschli** [comment]
This issue was moved to PowerShell/EditorSyntax#69
