### ISSUE TITLE
Color Picker at Image Preview

### ISSUE THREAD

**Issue by joaozitopolo** [Microsoft/vscode#44037]
The zoom improvements of Image Preview are excellent. 
But a Colour Picker, with RGB copy and Last 8 Copied, could be the cherry pick.

**Comment by joaozitopolo** [comment]
@mjbvz The tag "markdown" was automatically setted. My suggestion doesn't refer to markdown, and I have no permission to set the correct tag.
It's about the image preview. Almost time we receive a .png with the design of the pages, but we need to open a graphic editor only to get the RGB of some points, like title colour, some background, etc.

**Comment by mjbvz** [comment]
Yes I'm aware of this. I was already a little reluctant to add image zooming since it felt a little out of scope for an ide. A color eyedropper however seems like a step too far. A extension could certainly add this but I don't think its a good fit for the core product

**Comment by joaozitopolo** [comment]
@mjbvz thank you. You're right, it could run out of scope. I only thought that because the added image zooming... It gave the idea with image viewer was in constant evolution. :-) 
But I agree, some extension or also an external image editor could do that.
