### ISSUE TITLE
markdown does not show images as of latest (1.21.0-insiders) version

### ISSUE THREAD

**Issue by buffos** [Microsoft/vscode#44039]
Version 1.21.0-insider
Commit 6309a7734b0b0876b263a6a9cb526fc281100089
Date 2018-02-20T10:24:00.306Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Windows 10

Steps to Reproduce:

1. Open an md file that has an image tag (local or external does not matter)
2. The image does not show

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please share the markdown source for the image?

**Comment by buffos** [comment]
as simple as that. 
the image exists (ctrl + click on the link opens the image correctly)
![image_error](https://user-images.githubusercontent.com/9776567/36442037-20eaf61c-167d-11e8-9f21-b397b99c22f1.PNG)

**Comment by mjbvz** [comment]
I can't reproduce this in a workspace:

![screen shot 2018-02-20 at 11 20 03 am](https://user-images.githubusercontent.com/12821956/36444359-0bed07a2-1630-11e8-85b2-0d83516a8220.png)

 How did you open the markdown file? Was it part of a workspace?

**Comment by buffos** [comment]
No. just double click an orphan file. 
I also deleted all extensions (deleted extension folder) and installed all extensions again.

The context menu was not updated. I had to "disable all extensions" and then "enable all extensions" to view the options in the context menu.

Which extension are you using for previewing the md?

**Comment by buffos** [comment]
I have just checked. It works inside a workspace. Not as a standalone file

**Comment by mjbvz** [comment]
Just the built-in one

This makes sense now. I recently disallowed webviews (like the markdown preview) from loading local files outside of the current workspace for security reasons. In the case where you have no workspace open, we probably want to treat the markdown file's folder as the implicit workspace and allow loading  images file from there

**Comment by timotei** [comment]
@mjbvz  I am using the following VSCode version:

![2018-03-09 01_19_49-visual studio code](https://user-images.githubusercontent.com/428492/37181993-fc2c0ace-2337-11e8-85a7-a6dd2e2538c8.png)

It seems if I open directly a `.md` file it won't show local images, that are for example near the .MD file. IMO we should just do that by default.

**Comment by mjbvz** [comment]
@timotei See #45155. Should be fixed in 1.22.0 insiders builds
