### ISSUE TITLE
File events missing when transitioned into multi folder workspace

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#44034]
Me and @dantup see this regularly.

1. Start with a single folder vscode
2. Add another folder so you are transitioned into and untitled workspace
3. File events are broken in the just added folder
4. File events are working fine in the first folder

I try file events by making a change outside of vscode to a file and checking if the editor display it.
I can reproduce this all the time on my mac, so let me know what more deatils you need

**Comment by DanTup** [comment]
Seeing it on Windows here. I can repro by following the instructions above and (for ex) creating a file file in the second folder outside of Code, but it doesn't show up in the explorer.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/44036
