### ISSUE TITLE
Rename "Close Unmodified" to not collide with SCM semantics ("Close Saved")?

### ISSUE THREAD

**Issue by enkol** [Microsoft/vscode#44033]
Since the explorer shows "modified" state from source control (i.e. git), the "close unmodified" action for editors is potentially misleading. It behaves more like "close all except unsaved". 
One could expect to keep files which are saved but in modified state (source control wise) open too.

- VSCode Version: 1.20.1
- OS Version: Windows 10 x64

**Comment by bpasero** [comment]
Let me think about a better name, if not I will close as wontfix.

**Comment by bpasero** [comment]
@soneymathew up to you since you introduced this. One idea would be "Close Saved" instead of "Close Unmodified".

**Comment by itamark** [comment]
I can take this.

**Comment by itamark** [comment]
Submitted PR: https://github.com/Microsoft/vscode/pull/44269
