### ISSUE TITLE
Shortcut for "clear search results" does not work anymore

### ISSUE THREAD

**Issue by hwsoderlund** [Microsoft/vscode#44043]
### Issue Type
Bug

### Description

One of my custom shortcuts has stopped working. The shortcut is defined as follows in keybindings.json:

```json
{
  "key": "cmd+escape",
  "command": "search.action.clearSearchResults",
  "when": "editorTextFocus"
},
```

It used to work, and is simply a shortcut for clicking the "clear search results" button, see screen shot 1 below. In the screen shot you can also see that the defined shortcut is displayed in the tooltip. So it appears that VS Code understands that the command ID for that button is indeed `search.action.clearSearchResults`. I am not exactly sure when it stopped working, but my guess is 1-2 weeks ago. 

I have double checked the VS Code source code, and the command ID appears to be correct:
https://github.com/Microsoft/vscode/blob/86021249798a8af7bbdbd54f0fb702c10c8f0eba/src/vs/workbench/parts/search/browser/searchActions.ts#L359

Steps to reproduce:

1. Add the shortcut in keybindings.json
2. Open a file. 
3. Use Cmd+Shift+F and search for a word that exists in the open file. 
4. Focus the editor pane. 
5. Now hit the shortcut, e.g. Cmd+Escape

Expected result: The search results should have been cleared. 

Actual result: The search results are not cleared. Instead a warning is displayed: `command 'search.action.clearSearchResults' not found`. See screen shot 2 below. 

Screen 1:

![image](https://user-images.githubusercontent.com/3725915/36427072-60fffe90-164c-11e8-82df-7c8e289dc14f.png)

Screen 2:

![image](https://user-images.githubusercontent.com/3725915/36427111-80e8adce-164c-11e8-9cfc-58d6651a9341.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
vscode-markdownlint|Dav|0.13.0
EditorConfig|Edi|0.12.1
gc-excelviewer|Gra|2.0.17
beautify|Hoo|1.3.0
code-settings-sync|Sha|2.8.7
vscode-terminal-here|Tyr|0.1.1
vscode-eslint|dba|1.4.6
gitlens|eam|8.0.2
flow-for-vscode|flo|0.7.3
Go|luk|0.6.76
python|ms-|2018.1.0
node-debug2|ms-|1.20.0
vscode-fileutils|sle|2.7.1
Align|ste|0.2.0
gitblame|wad|2.2.0

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
I don't see that command registration existing before, but in any case, I added it so your shortcut will work.

**Comment by hwsoderlund** [comment]
Just got the latest update, and it works again now. Thank you.
