### ISSUE TITLE
VS Live Share not showing login status bar on Ubuntu Linux 16.04

### ISSUE THREAD

**Issue by kevin-williams** [Microsoft/vscode#44048]
### Issue Type
Bug

### Description

Co-worker on MaxOS has his live share connected and sent me a link.  I've installed Live Share on VS Code in Linux, but the link doesn't work.   Also doesn't show the login button on the command line.

Tried on my linux laptop as well with the same result.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.4.0-87-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 1696)|
|Load (avg)|1, 1, 1|
|Memory (System)|31.31GB (9.80GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.7
npm-intellisense|chr|1.3.0
githistory|don|0.4.0
es7-react-js-snippets|dsz|1.3.3
prettier-vscode|esb|1.1.3
githd|hui|1.1.1
vscode-scss|mrm|0.6.2
node-debug2|ms-|1.21.1
vsliveshare|ms-|0.2.146
vscode-react-native|vsm|0.6.0

</details>
Reproduces without extensions

**Comment by RMacfarlane** [comment]
Please report this on Live Share: https://github.com/MicrosoftDocs/live-share
