### ISSUE TITLE
Save proxy authentication

### ISSUE THREAD

**Issue by willemavjc** [microsoft/vscode#44041]
### Issue Type
Feature Request

### Description

Each time I open VS Code, it displays a form asking for my proxy settings. Isn't there a way I could check some box and it would repropose the form filled,  at least?
Thanks!

![image](https://user-images.githubusercontent.com/321359/36430292-227fbca6-1655-11e8-91ec-a0f285e4916f.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

**Comment by willemavjc** [comment]
Will it come one day?

**Comment by solarjoe** [comment]
Same issue for me, the pop-up appers twice (once for the Extensions I guess).

Windows 10, 64-bit
VS Code 1.33.1 (user setup)

I tried lots of things in the GUI settings and settings.json for User Settings and Workspace Settings, also both as mentioned in https://github.com/microsoft/vscode/issues/32566#issuecomment-480692463

```
    "http.proxy": "http://user:password@proxy-ip:port" (with password, without, username only, ...)
    "http.proxyStrictSSL": false or true
    "http.proxySupport": "on (override, off, ...)
```

The environment variables are set (lowercase) and work fine for other programs

```
https_proxy=http://user:password@proxy-ip:port
http_proxy=http://user:password@proxy-ip:port
```

- What is the expected behaviour? Is VS Code always supposed to ask for the password even if it is stored in the URL in the settings or the environment variables?
- Could there be a "store password" in this pop-up which puts it to the settings.json if authentication works?

**Comment by solarjoe** [comment]
I found this issue https://github.com/Microsoft/vscode/issues/38888 

They mention that supplying the proxy parameters on the command line works, even if setting it in VS Code doesn't. And this works for me. Still not beautiful, as the password is clear text, but for the other options (environment variables, settings.json) this would also be the case.

So I added this to my desktop shortcut and the two popups are gone:

`"C:\Path\To\Code.exe" --proxy-server=http://user:password@123.123.123.123:8080`

**Comment by gpion** [comment]
>  that supplying the proxy parameters on the command line works, even if setting it in VS Code doesn't.

Then you'll have to edit all reference to code.exe in the HKCU branck of registry too (shell\open\command  for several object types)

**Comment by solarjoe** [comment]
True, and there was another response https://github.com/microsoft/vscode/issues/32566#issuecomment-530294695 that it doesn't work.
Just the popup is gone.

Is there a way to see which proxy settings are being used when VCS is connecting somewhere? I checked the developer tools but they only state the errors.

**Comment by solarjoe** [comment]
I tried the workaround using node here and it works fine: https://github.com/microsoft/vscode/issues/32566#issuecomment-530995464

**Comment by willemavjc** [comment]
@joaomoreno Is there any plan to do something about it?

**Comment by joaomoreno** [comment]
No plan so far.

**Comment by gpion** [comment]
> No plan so far.

Sad. Time to expect a closed issue with a _"won't fix"_ status then  :-/

**Comment by willemavjc** [comment]
> No plan so far.

Can't believe no one @microsoft care about such an issue which is in 2020 rather a core design issue than anything else... VSCode was meant for developers and developers mainly work in organisations with most of the big ones using proxies since like 20 years, at least.
