### ISSUE TITLE
Make multi root modification APIs stable

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44046]
Currently they are proposed API. 

@jrieken any objections?

**Comment by jrieken** [comment]
Some nits on the API but I'd be OK to :ship: it

**Comment by sandy081** [comment]
@bpasero What has to be verified here?

**Comment by bpasero** [comment]
@sandy081 verify that you can use the new `updateWorkspaceFolders` API without having to run the extension in proposed API mode.
