### ISSUE TITLE
os.homedir() is only supported in node >= 4

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4404]
@Tyriar please fix, I pushed a workaround here: https://github.com/Microsoft/vscode/commit/faffb7df995482275996535681d141e5a71560b8

I think we should still allow to build on older node.js versions unless there is a major reason otherwise.

**Comment by Tyriar** [comment]
@joaomoreno how exactly was the windows build breaking in 3a3c9e15? Doesn't the `process.env['HOME']` only get evaluated if the task is called in to? It feels weird to do `process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME']` here when it should never be run on Windows.

**Comment by Tyriar** [comment]
@joaomoreno oh I think I got it; because we create the gulp task by calling `prepareRpmPackage`, I'll fix it up.

**Comment by joaomoreno** [comment]
:-1: [0.12 is not even LTS now](https://nodejs.org/en/). We should stop supporting it.
