### ISSUE TITLE
PHP Document Format

### ISSUE THREAD

**Issue by AttiviDigitali** [Microsoft/vscode#44045]
### Issue Type
Bug

### Description

PHP document format doesn't work after last update  

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|7.87GB (2.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.8
php-pack|fel|1.0.1
laravel-blade|one|1.16.0
laravel-extension-pack|one|0.2.0
laravel5-snippets|one|1.4.0
vscode-icons|rob|7.20.0
laravel-artisan|rya|0.0.16
bootstrap4-vscode|the|4.0.0

</details>
Reproduces without extensions

**Comment by RMacfarlane** [comment]
Can you provide more details about what isn't working? What steps do you follow to see this issue? What do you expect to happen and what actually happens?

**Comment by AttiviDigitali** [comment]
I'm a PHP Developer, before last update I was  able to click on right button on a page and chose "format document". Now this is not available. I've tried to disable all the plugin but the problem still goes on. 
![cattura](https://user-images.githubusercontent.com/32685700/36721455-39213b0a-1bab-11e8-938d-6db5e2dfc39d.JPG)

**Comment by roblourens** [comment]
I believe it says that you don't have a PHP formatter installed. vscode doesn't have a PHP formatter out of the box. You have to install an extension that provides this. Maybe you had one installed before and uninstalled it.
