### ISSUE TITLE
Do not use 'panel' for split views in UX

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#44044]
The word panel is already taken in our UX for the bottom workbench panel.
Please do not steal this term for the split view views.
Yes I understand it is named like that in our code base, which is fine for it to be confusing for our team members, but we should not make it more confusing for the users.

![screen shot 2018-02-20 at 16 04 40](https://user-images.githubusercontent.com/1926584/36431453-ecdadf38-1657-11e8-9c63-dea3bc8e3572.png)

**Comment by sandy081** [comment]
@joaomoreno This action came from the PR fixing this issue #37714.
