### ISSUE TITLE
Integrated terminal doesn't behave correctly with panel resizing

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#44054]
Version 1.21.0-insider
Commit 6309a7734b0b0876b263a6a9cb526fc281100089
Date 2018-02-20T10:24:00.306Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Open integrated terminal
2. Click "Restore Panel Size" / "Maximize Panel Size"

Expected: Active terminal line is at the top of the panel when height changes (old behavior)
Actual: Active terminal line doesn't shift (and it actually becomes unusable/hidden when "Restore Panel Size" is clicked)

[GIF](https://onedrive.live.com/?authkey=%21AFA2VV7CLBRColc&cid=4977EF4D9058F0C9&id=4977EF4D9058F0C9%21365837&parId=4977EF4D9058F0C9%21365739&o=OneUp)

**Comment by Tyriar** [comment]
I fixed this this morning :smile: https://github.com/Microsoft/vscode/issues/44040, it should hit Insiders late tonight. In the meantime resizing the panel again by dragging should fix it.

**Comment by martellaj** [comment]
Awesome! I figured you'd be on it - you're a rock star!

**Comment by Tyriar** [comment]
@martellaj fixing bugs I caused is my specialty 😉

**Comment by martellaj** [comment]
#jobsecurity

**Comment by martellaj** [comment]
Confirmed the fix btw! Thanks!
