### ISSUE TITLE
How to disable indents trimming?

### ISSUE THREAD

**Issue by r3d9u11** [Microsoft/vscode#44053]
Hi. Is it possible to save auto-indenting (add needed indents on new line) and disable indents trimming on empty line?
![1](https://user-images.githubusercontent.com/15020827/36439790-f8e06aa6-167e-11e8-988b-cbf0b29d7bb4.png)

I tried to set
```
...
"editor.tabSize": 3,
"editor.insertSpaces": false,
"editor.renderWhitespace": "boundary",
"diffEditor.ignoreTrimWhitespace": false,
"files.trimTrailingWhitespace": false,
"files.trimFinalNewlines": false,
"editor.detectIndentation": false,
...
```
but without effect

Thanks!

**Comment by RMacfarlane** [comment]
Try adding `"editor.trimAutoWhitespace": false`. This setting controls if auto inserted whitespace gets trimmed

**Comment by r3d9u11** [comment]
@RMacfarlane many thanks!
