### ISSUE TITLE
Markdown links not syntax colored

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#44058]
### Issue Type
Bug

### Description

Using  a sentence like

```markdown
It is worth reviewing the [entire migration page](https://getbootstrap.com/docs/4.0/migration/) on the Boostrap 4 web site.
```

The linked text and the link itself are no longer syntax colored.  They used to be.

Inspecting the scope shows both items are only scoped to `meta.paragraph.markdown`.

This is the same if the links are in bullet text, then they are scoped `markup.list meta.paragraph.markdown` like the surrounding text.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (6309a7734b0b0876b263a6a9cb526fc281100089, 2018-02-20T10:16:08.796Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1343816|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.4.2
code-settings-sync|Sha|2.8.7
sort-lines|Tyr|1.4.1
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.1
project-manager|ale|0.24.0
vscode-eslint|dba|1.4.6
tslint|eg2|1.0.28
prettier-vscode|esb|1.1.3
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.8.1
vscode-text-pastry|jkj|1.2.0
svg|joc|0.0.9
Angular2|joh|2.13.0
vscode-icon-theme|jtl|1.6.1
ecdc|mit|0.11.0
HTMLHint|mka|0.4.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
polacode|pnp|0.2.2
stylelint|shi|0.32.0
Align|ste|0.2.0
bootstrap4-vscode|the|4.0.0
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#10

**Comment by jrieken** [comment]
<img width="710" alt="screen shot 2018-03-01 at 13 51 37" src="https://user-images.githubusercontent.com/1794099/36845598-ae3cb358-1d57-11e8-8850-32da9b16a3ff.png">
