### ISSUE TITLE
Global launch object in settings broken

### ISSUE THREAD

**Issue by affenwiesel** [Microsoft/vscode#44050]
### Issue Type
Bug

### Description

When starting a debug session using a launch configuration from the section in the user-settings, I get the error: "Cannot read property 'name' of undefined".
However if I copy-paste the content into a local launch.json everything works fine!

**//edit:**
I found one of the issues:
Removing the "preLaunchTask" got me one step further.
Now I get another error message: "Cannot determine executable for debug adapter '{0}'."
This problem is only with the C++ debugger - the others I tried (Java, Python) work fine.

here is my launch configuration:
```json
      {
        "name": "C++", 
        "type": "cppdbg", 
        "request": "launch", 
        // "preLaunchTask": "make",
        "program": "${fileBasenameNoExtension}",
        "stopAtEntry": true,
        "cwd": ".",
        "environment": [],
        "externalConsole": false,
        "windows": {
          "MIMode": "gdb",
          "setupCommands": [
            {
              "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": false
            }
          ]
        },
        "pipeTransport": {
          "pipeCwd": "${fileDirname}",
          "pipeProgram": "c:\\windows\\sysnative\\bash.exe",
          "pipeArgs": [
            "-c"
          ],
          "debuggerPath": "/usr/bin/gdb"
        },
        "sourceFileMap": {
          "/mnt/c": "C:\\"
        }
      }
```

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.66GB (3.70GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Mogli\Docs\Uni\FS05\SiWiR1\Ex4\siwir4|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0

</details>
Reproduces only with extensions

**Comment by isidorn** [comment]
@affenwiesel can you reproduce this behavior with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by affenwiesel** [comment]
Yep, the issue remains the same.
Only now, when I remove the preLaunchTask the error message is:
"Cannot determine executable for debug adapter 'cppdbg'."

**Comment by isidorn** [comment]
From tomorrow's insiders we have fixed all the isues around this on the vscode side.
If you still see some issues, please file it against the C++ extension. Thank you

**Comment by weinand** [comment]
@isidorn duplicate of https://github.com/Microsoft/vscode/issues/44760

**Comment by affenwiesel** [comment]
It seems that part of the issue is fixed in the latest insiders.
However trying to use a preLaunchTask still leads to the above mentioned error:
"Cannot read property 'name' of undefined"

**Comment by weinand** [comment]
@affenwiesel I suggest that you create a new issue with your finding instead of commenting on a closed duplicate...
