### ISSUE TITLE
GO TO Definition doesn`t work.

### ISSUE THREAD

**Issue by liuhao2050** [Microsoft/vscode#4405]
- VSCode Version:0.10.11
- OS Version:ubuntu 14.04 LTS

Steps to Reproduce:

1. When I use F12 or Alt+click to go to   a definition of python class,it doesnt work. Please help me.  
2.

**Comment by liuhao2050** [comment]
Do vs code has this feature in python？ or，some ext. can do it？

**Comment by aeschli** [comment]
The default VS Code build does not have any support for 'go to definition' for Python.
Are you using the [Python](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) extension? If yes and you see this bug there, please file it directly against the extension (https://github.com/DonJayamanne/pythonVSCode)
