### ISSUE TITLE
Setting does not show up in settings editor anymore

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44051]
I have no explanation why this happens but the `window.autoDetectHighContrast` does not show up for me anymore in insiders and stable, works fine when running out of sources though:

![image](https://user-images.githubusercontent.com/900690/36436263-1218fbc0-1664-11e8-8a00-7962296d97ba.png)

![image](https://user-images.githubusercontent.com/900690/36436340-3fd42af8-1664-11e8-873d-e59efc3f6d13.png)

@sandy081 can you check this out?

**Comment by sandy081** [comment]
@bpasero I see it in Windows

![image](https://user-images.githubusercontent.com/10746682/36438394-1d0a636a-166a-11e8-8373-bea4c13c3861.png)
