### ISSUE TITLE
Command Palette `Revert File` does nothing.

### ISSUE THREAD

**Issue by drproteus** [Microsoft/vscode#44057]
- VSCode Version: 1.20.1 (1.20.1)
- OS Version: OS X 10.12.6

Steps to Reproduce:

1. open file -> make changes -> cmd+shift+p -> revert file -> file is not reverted.
2. open file -> make changes -> select File > Revert File -> file is reverted.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@chrmarti fyi https://github.com/Microsoft/vscode/issues/44057#issuecomment-367070742 makes no sense

**Comment by drproteus** [comment]
Why was this closed? It is not a duplicate of the referenced tickets.

**Comment by chrmarti** [comment]
Better :)
