### ISSUE TITLE
Insiders build regressed C++ colorization

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#44067]
The latest VS Code Insiders build doesn't have the correct C++ IntelliSense colorization. I tried Windows.

The right image is Insiders.
![image](https://user-images.githubusercontent.com/19859882/36450720-af91e888-1643-11e8-85ba-06391aaafb41.png)

**Comment by RMacfarlane** [comment]
Does this occur when all extensions are disabled?

**Comment by sean-mcmanus** [comment]
Yes. Repros without any extensions enabled.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/36475071-d99684c0-16f9-11e8-8862-6d0645f0a2b7.png)

I can't reproduce.
Your screenshot on the right looks like the `Dark (Visual Studio)` theme

**Comment by sean-mcmanus** [comment]
Ooops, sorry. I didn't realize my Insider and non-Insider were using different themes. I switched my Insider theme to Dark+ and it matches my non-Insiders now.
