### ISSUE TITLE
BUG: Autocomplete (IntelliSense) for TSX control properties displays some unexpected items

### ISSUE THREAD

**Issue by pmunin** [Microsoft/vscode#44061]
I have a react+typescript project. I create control SearchControl with properties:
```
//searchControl.tsx:
//import...
type Props={
    onSelected:(args:SelectedArgs)=>void
    onAddNew:(args:AddNewArgs)=>void
    storage:object
}
export class SearchControl extends React.Component<Props, any>
{
...
}
```
And when I try to use this control in other file, the properties of control are mixed alphabetically with bunch of other stuff, which I don't even expect to see:
![image](https://user-images.githubusercontent.com/7120440/36445980-d4ab53c0-164d-11e8-89c1-9fbd36917583.png)

If I scroll this intelliSense list down I finally can see expected control's properties mixed alphabetically with snippets and other language items, but it's confusing and make it hard to find actual properties, which I expect to see and the top of the list:

![image](https://user-images.githubusercontent.com/7120440/36446257-c3f9f51c-164e-11e8-983e-0d572c9873bf.png)

- VSCode Version: 1.20
- OS Version: Ubuntu 17.10 / Windows 7 x64

Steps to Reproduce:

1. Create react+typescript project,
2. Create react control with strongly typed properties
3. Try to use this control in render method of other control, and use intelliSense to find properties of control

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/21844

Should already be fixed in `typescript@next` if you want to [give that a try in your workspace](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)
