### ISSUE TITLE
No puedo abrir el simbolo del sistema.Error: El proceso del terminal finalizó con el código de salida: 4294901760

### ISSUE THREAD

**Issue by MissyM** [Microsoft/vscode#44064]
### Issue Type
Bug

### Description

Doy click derecho en uno de mis archivos.
Abrir el simbolo del sistema.
Sale un mensaje en el terminal y rápidamente se desaparece.
El mensaje dice: El proceso del terminal finalizó con el código de salida: 4294901760

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|Memory (System)|3.90GB (0.83GB free)|
|Process Argv|F:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
fractal-vscode-extension|car|0.0.17
color-highlight|nau|2.3.0

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
What's in your settings.json file?
