### ISSUE TITLE
When vscode window is restored after OSX restart PATH variable does not seem to be loaded

### ISSUE THREAD

**Issue by Gozala** [microsoft/vscode#44060]
Whenever OSX restores windows after login vscode seems to fail finding things in `PATH` env. I always get a following error:

```
'code' is not found in PATH or set via 'vscode-open-project.codePath' setting in Code. Open Project won't work.
``` 

Reloading a window or restarting vscode seems to resolve the issue. It might be worth mentioning that in my setup that `code` is under `/usr/local/bin/code` which is added to `PATH` both in `~/.profile` and `~/.bashrc`. Here is also my actual setup https://github.com/gozala/.env (all files are symlinked)

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
racket|Dmy|1.2.0
rls-vscode|TOD|0.0.1
quokka-vscode|Wal|1.0.104
elm-format|aba|0.1.0
project-manager|ale|0.24.0
toml|be5|0.0.3
better-toml|bun|0.3.2
vscode-gist|dba|1.0.0
prettier-vscode|esb|1.1.3
flow-for-vscode|flo|0.7.3
flatbuffers|gab|0.1.0
vscode-yarn|gam|1.5.0
flow-language-mode|goz|0.0.2
vscode-rust|kal|0.4.2
elm|sbr|0.16.0
vscode-open-project|sve|0.0.9
vscode-lldb|vad|0.7.5
debug|web|0.21.2

---

Steps to Reproduce:

1. Restart OSX with reopen windows option on and vscode open:

<img width="529" alt="screen shot 2018-02-20 at 10 52 36 am" src="https://user-images.githubusercontent.com/21236/36442947-35b8719c-162c-11e8-9af7-1d5df578ebff.png">

2. After OSX restarts I see `code` not found warning and errors for other binaries expected to be found in PATH.

![screen shot 2018-02-20 at 10 53 42 am](https://user-images.githubusercontent.com/21236/36443028-7abc17d0-162c-11e8-87d9-dfaff96d2c7a.png)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Even flow can't find node in your PATH. Are you sure this is an issue with Code, and not with your system setup?

**Comment by Gozala** [comment]
> Even flow can't find node in your PATH. Are you sure this is an issue with Code, and not with your system setup?

No I’m not sure, but then I’m also not sure why this happens in first place. It only happens when osx restors windows

**Comment by Gozala** [comment]
> What is /usr/local/bin/code in your system? A symlink? If so, to what?

It’s whatever vscode installs, I’ll double check if it’s a symlink and post back

**Comment by Gozala** [comment]
> What is /usr/local/bin/code in your system? A symlink? If so, to what?

```
readlink $(which code)    
/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
```
