### ISSUE TITLE
[theming] color coding for different languages

### ISSUE THREAD

**Issue by petewulf** [microsoft/vscode#44066]
Unfortunately there's no way to set color coding for specific languages - one single theme for all is just not enough, for example:

![color-code](https://user-images.githubusercontent.com/6872322/36449185-531fe82e-168a-11e8-8612-06500fe97ad8.PNG)

Although i'm inside of a PHP-String, VC misinterprets SQL as keywords, not as a string. If VC already knows which scope its currently in (Developer Tools displays "keyword.other.sql") it should also be possible to colorize the code differently. I can't see obviously if i'm currently inside a string or inside SQL. This increases coding syntax errors exponentially.

Its getting even worse if i mix together for example HTML, CSS, JAVASCRIPT, PHP, MYSQL - it's so hard to differentiate the current scope by eyes because it's all the same, this is horrible and unfortunately not usable for daily work.

**Comment by aeschli** [comment]
You could write a theme that does language specific color coding...

**Comment by petewulf** [comment]
Hi aeschli,

yes, i'd like to do that but i don't know excactly how to access those tokens in the theme config, for example i have this scope info:

![token](https://user-images.githubusercontent.com/6872322/36488119-f4fcdf42-1722-11e8-87b1-f979aa5fbd05.PNG)

As i see the corresponding scope is "keyword { "foreground": "#0000ff" }" but thats the rule for all keywords, not for this language specific or nested one. For my understanding i'll have to create a language based theme but i havent found any useful information how to write the corresponding json config and i also havent't found another theme, which covers this area. 

Is this already possible?

**Comment by petewulf** [comment]
So as i've finally found out roughly how to customize tokens, it would be very handy if the list of scope names would be clickable to insert a new token setting in your settings.json like:

`keyword.other.sql    <--- click`

inserts

```
"editor.tokenColorCustomizations": {
        "textMateRules": [{
			"scope": "source.sql.embedded",
			"settings": {
                "fontStyle": "bold",
                "foreground": "#ffffff"
                },
            }
        ]
    }
```

This would ease and speed up the whole customization process a lot in my opinion

**Comment by aeschli** [comment]
There are currently no plans to support language specific theming.
