### ISSUE TITLE
Double clicking to select, last letter always dark?

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#44065]
### Issue Type
Bug

### Description

From editor, double click on a word to select highlight.

Notice the last letter colour is not the same highlight as the others, depending on theme used it will always be darker and not visible.

In picture below, cannot see letter "e", its a different highlight?

<img width="261" alt="screen shot 2018-02-20 at 3 59 37 pm" src="https://user-images.githubusercontent.com/439226/36449189-09102e56-1658-11e8-88ed-090108ba496e.png">

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (936b796aa8667de5edb536b00ce8a8e61fcebfb6, 2018-02-16T06:08:39.456Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron . .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
ng-template|Ang|0.1.9
vscode-markdownlint|Dav|0.13.0
EditorConfig|Edi|0.12.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.6
tslint|eg2|1.0.28
cpptools|ms-|0.15.0
angular2-inline|nat|0.0.17
vim|vsc|0.10.13
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
If this is only reproducible with extensions, then it is likely an extension causing this behavior. Can you narrow down which extension it is using these directions? https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled

**Comment by rajinder-yadav** [comment]
Thanks for the tip. Closing, it is probably one of the theme extensions. I'll open a bug with respect project.
