### ISSUE TITLE
Do you even have 'go to definition' in php?

### ISSUE THREAD

**Issue by TkIgor** [Microsoft/vscode#4406]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. 
2.

**Comment by egamma** [comment]
No sorry, but it is a valid feature request.

**Comment by felixfbecker** [comment]
Working on it

**Comment by wangroute** [comment]
When can support it？

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/issues/19

**Comment by Pikdo** [comment]
it is done?

**Comment by felixfbecker** [comment]
![](https://github.com/felixfbecker/vscode-php-intellisense/raw/master/images/definition.gif)

**Comment by oojacoboo** [comment]
This is fantastic - thank you!  I'm trying everything I can to get out of PHPStorm, which I do like quite a lot.  But the language flexibility of VSCode is far superior.  And one can't argue with the performance differences.

**Comment by roblourens** [comment]
This is covered nicely by the extension.

**Comment by Pikdo** [comment]
Hey, Excellent, thank you!!!

Ale

2017-05-05 19:28 GMT-06:00 Rob Lourens <notifications@github.com>:
