### ISSUE TITLE
Can't Edit User Settings

### ISSUE THREAD

**Issue by PointZeroSeven** [Microsoft/vscode#44077]
### Issue Type
Performance Issue

### Description

When I attempt to modify Default Settings, I get the following Error messag:

"Unable to write into user settings. Please open User Settings file to correct errors/warnings in it and try again."

I'm not sure what to change.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz (8 x 3100)|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.56GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

|pid|CPU|Memory (MB)|Name|
|---|---|---|---|
|800|22|82|code main|
|802|10|90|-- gpu-process|
|805|1|74|-- shared-process|
|820|8|205|-- window (settings.json)|
|821|0|98|---- extensionHost|
|822|0|41|------ electron_node cssServerMain.js |
|823|0|66|------ electron_node htmlServerMain.js |
|826|0|74|------ electron_node jsonServerMain.js |
|857|0|82|-- shared-process|
|861|30|57|-- shared-process|
|862|0|0|-- (ps)|
|863|0|0|-- /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=|

</details><details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
syntax-lookup|Syn|0.3.1
quokka-vscode|Wal|1.0.104
vscode-html-css|ecm|0.2.0
atom-keybindings|ms-|3.0.4

</details>
Reproduces only with extensions

**Comment by sandy081** [comment]
@PointZeroSeven Can you please open User settings file and see if there are any errors (red squiggles) there?

**Comment by PointZeroSeven** [comment]
None.

**Comment by sandy081** [comment]
@PointZeroSeven 

>When I attempt to modify Default Settings, I get the following Error messag:

Are you using the `pencil` icon to modify? Can you please provide the screenshot of complete editor when you do that?

**Comment by SheepDomination** [comment]
![code_settings](https://user-images.githubusercontent.com/6827459/37011966-630c1ad8-20c0-11e8-95c3-e1913c6e854d.png)
I've attached a screenshot of the editor with the pencil tool; as I'm experiencing the same problem.

**Comment by sandy081** [comment]
@SheepDomination Looks like the settings file is not syntactically correct. Last settings are outside the parenthesis `{...}`. Can you please move them inside and try.

Not sure how you got into this state where settings are outside.

**Comment by SheepDomination** [comment]
Hi, I've tried moving all settings inside the `{...}` but the error continues ?

**Comment by sandy081** [comment]
Do you see any red squiggles? You should fix all those red squiggles.

**Comment by SheepDomination** [comment]
I've sorted out the problem.  Make sure you have no errors and there are no syntax issues within the user settings.
