### ISSUE TITLE
Give a notice when something is wrong with flake8 settings

### ISSUE THREAD

**Issue by yanxyz** [Microsoft/vscode#44079]
### Issue Type
Feature Request

### Description

I met problem that pylint worked well but flake8 did not work, it just reported:

> No problems have been detected in the workspace so far.

I referred to this [issue](https://github.com/DonJayamanne/pythonVSCode/issues/838) but got no idea.

This problem troubled me a few days until I found out that I made a mistake in my settings:

```js
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": [
       //  "--max-line-length=120",
        "-max-line-length=120", 
    ],
```

If there is a notice when something is wrong with flake8 settings, this problem could be fixed soon.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

**Comment by RMacfarlane** [comment]
Thanks for reporting,  it would be good to have validation for this setting. Please open an issue in https://github.com/Microsoft/vscode-python instead. VS Code only knows that the setting is an array of strings, so it can't do any additional validation.
