### ISSUE TITLE
VS Code on Windows is case sensitive to file paths when opening files while Debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#44074]
### Issue Type
Bug

### Description

Currently we're working on a new debugger for the [Python Extension](https://github.com/Microsoft/vscode-python.git)

What we've idenfied is that when a breakpoint or exception is hit, VS Code opens another editor/copy for the same file on Windows.

Here's the scenario:
* Workspace = c:\Temp\python\debuggerTesting (note the upper case `T`s)
* File being debugged `one.py` with the following contents:
`print(x)` 
* Note: `x` is undefined hence we expect the debugger to break at that line (unhandled exception).
* Open the file `one.py` (pin it, so it stays opened)
* Debug using the new experimental debugger
Note: The debugger isn't public, hence you won't be able to replicate this. However we can provide the files through some other means.
* As soon as the debugger hits the breakpoint it opens another instance of the file `one.py`
Now we have two editors opened, for the same file.
* However, hovering over the title of the second `one.py` (opened by debugger) we can see the path is `c:\temp\python\debuggertesting\one.py`. 
Note: Everything is in lower case (yes this is what's being returned by our debugger over the protocol).

**Issue: VS Code on Windows, should realize the files are the same instead of opening a new editor.**

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
VS Code version: Code - Insiders 1.20.0-insider (eed7e193125f3d4cfebe2089d1b2a9c674388754, 2018-01-30T09:40:57.870Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (1.06GB free)|
|Process Argv|/private/var/folders/22/0kj01mp12l3dsd1vw9vhfs6c0000gn/T/AppTranslocation/C4B4AE97-B9C0-4154-ADC9-76D932802595/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (26)</summary>

</details>
Reproduces only with extensions: Specific to Python Extension

**Comment by weinand** [comment]
In general I agree: VS Code (on any platform) should ignore the case of a path when trying to map a path/URI to a workspace resource that lives on a case insensitive filesystem. 
However, with the advent of remote file system providers and remote debugging it is a bit difficult to figure out whether a resource lives on a case insensitive filesystem (and needs a case-ignoring file matching).

/cc @bpasero @jrieken opinions?

**Comment by isidorn** [comment]
This is a general workbench issue 
Duplicate https://github.com/Microsoft/vscode/issues/12448

As for the normalisation of paths going out to Debug Adapters, that will be tackled via https://github.com/Microsoft/vscode/issues/43959
