### ISSUE TITLE
XML in C# Intellisense comments

### ISSUE THREAD

**Issue by welkie** [Microsoft/vscode#44078]
- VSCode Version: 1.20.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Begin typing the name of a method to call, press tab to complete it and view comments for method in Intellisense
2. Observe the comment

Does this issue occur when all extensions are disabled?: Irrelevant, because disabling all extensions removes the C# Intellisense.

When viewing the comments for a method with the C# Intellisense, there are XML tags in the way, making it harder to read the text and potentially hiding the rest of the comment. Example:

![image](https://user-images.githubusercontent.com/7719209/36458211-ad2b0ba0-167b-11e8-8485-6a43dd373a25.png)

**Comment by RMacfarlane** [comment]
Since this is extension specific, please open the issue in the extension's repo (https://github.com/OmniSharp/omnisharp-vscode).
