### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by PointZeroSeven** [Microsoft/vscode#44076]
### Issue Type
Bug

### Description

Emmet is not performing automatic functions in HTML files.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz (8 x 3100)|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.60GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
syntax-lookup|Syn|0.3.1
quokka-vscode|Wal|1.0.104
vscode-html-css|ecm|0.2.0
atom-keybindings|ms-|3.0.4

</details>
Reproduces only with extensions

**Comment by ramya-rao-a** [comment]
@PointZeroSeven Please provide sample code and expected behavior

**Comment by PointZeroSeven** [comment]
What I'm reporting is that none of the behaviours expected of Emmet are
occurring. I'm on a Mac, running OSX Sierra 10.12.06.
Completing actions with a TAB only spaces the text content, but does not
complete the coding short form activity.

**Comment by ramya-rao-a** [comment]
The reason I asked for sample code and expected behavior is because I don't understand what "automatic functions in HTML files" means

**Comment by gingerbeardman** [comment]
Two things come to mind:
1. you need to position the cursor at the end of the abbreviation. See: https://docs.emmet.io/actions/expand-abbreviation/
2. you need to add the settings so that TAB triggers Expand Abbreviation
`"emmet.triggerExpansionOnTab": true`

**Comment by ramya-rao-a** [comment]
@PointZeroSeven Assuming that the issue here is that  none of the Emmet expansions are occurring when pressing tab key, @gingerbeardman is right. 

Please read [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet)
