### ISSUE TITLE
How to turn off a hint when hovering over a html tag?

### ISSUE THREAD

**Issue by GoodProject** [Microsoft/vscode#44071]
Hello.

How to disable this hint for .html files?

![image](https://user-images.githubusercontent.com/14226563/36455811-e98ca39c-16b2-11e8-8970-a8dd416efcbc.png)

**Comment by aeschli** [comment]
There's currently only hidden option to disable all hovers:
`"editor.hover": false`

duplicated of https://github.com/Microsoft/vscode/issues/30114
