### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by devangsolanki-blog** [Microsoft/vscode#44072]
### Issue Type
Bug

### Description

I have checked online, but I am not sure what details are you looking. Issue has been reproduce with opening visual studio code.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|7.91GB (1.04GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.0.2
Angular2|joh|2.13.0
java|red|0.19.0

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
Can you try disabling your extensions one by one to see if one of them is causing the problem?

**Comment by devangsolanki-blog** [comment]
I have resolved the issue with re-installing VSCode.
