### ISSUE TITLE
Missing HTML Language

### ISSUE THREAD

**Issue by jtmlmass** [Microsoft/vscode#44082]
### Issue Type
Bug

### Description

I can't find HTML language in Select Language mode. ANYWHERE. I find all the extensions to use it better but, can't find the option needing it a lot. 
I've tried to uninstall and install again. I went and watched vs code on other PC to confirm even.  

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
html-snippets|abu|0.2.1
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
vscode-languagetool-es|ada|3.8.0
Bookmarks|ale|0.18.1
html-class-suggestions|And|1.0.7
code-gnu-global|aus|0.2.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
lit-html|bie|1.2.0
compulim-vscode-closetag|Com|1.1.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
xml|Dot|1.9.2
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|1.4.2
code-runner|for|0.8.7
sml|fre|0.0.18
live-html-previewer|hdg|0.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
evermonkey|mic|2.4.4
HTML-Classes|mik|1.0.6
vscode-clang|mit|0.2.2
HTMLHint|mka|0.4.0
mssql|ms-|1.3.0
python|ms-|2018.1.0
wordcount|ms-|0.1.0
SystemVerilog|msh|0.0.17
veriloghdl|msh|0.2.0
prolog|reb|0.0.4
text-marker|ryu|0.11.0
html-preview-vscode|tht|0.1.1
python|tht|0.2.3
html-snippets|wge|0.1.5
jinja|who|0.0.8

(28 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by aeschli** [comment]
@sandy081 Is there a way to see disabled built-in extensions and to enable them again?

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/36493887-e5aa1696-1730-11e8-8ea5-01856bf94d39.png)

**Comment by jtmlmass** [comment]
I've tried that already. HTML is supposed to be installed by default and not as an extension. Just in case I used the "Enable All Installed Extensions" option. It didn't work either.

**Comment by aeschli** [comment]
Yes, html is a built-in extension. It would be a bug if you could disable it.

So you are saying that run the `Change Language Mode` command and type HTML and there is no entry?

![image](https://user-images.githubusercontent.com/6461412/36604192-4b094e52-18bd-11e8-9ede-e604fa30aa58.png)

Please disable all installed extensions and see if it still reproduces.
Also invoke 'Toggle Developer Tools' and check the console tab for anything suspicious.

**Comment by aeschli** [comment]
@jtmlmass Looks like the Django Template extension has taken over the 'html' language definition.
I'd suggest to uninstall the Django Template extension. 
This is already filed as https://github.com/iambibhas/vscode-django-template/pull/6
