### ISSUE TITLE
Resizing of VS Code's window makes terminal to act weird

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#44087]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

By resizing VS Code's window - second line of path is appearing.... and - you can, at least visually, erase some path folders.

![terminal - resize changes path](https://user-images.githubusercontent.com/24613274/36465513-0db9a9ec-16de-11e8-84d1-49f81626d7aa.gif)

Creating one more terminal:

![terminal - 2nd](https://user-images.githubusercontent.com/24613274/36465998-8d3064ac-16e0-11e8-9cec-bb2d1ea58b13.gif)

...

![terminal - 3rd](https://user-images.githubusercontent.com/24613274/36466007-97abc5a2-16e0-11e8-9f16-1864009442fc.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26375
