### ISSUE TITLE
Only "dependsOn" tasks get executed

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#44080]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create tasks.json:
```json
{
    "version": "2.0.0",
    "type": "shell",
    "command": "echo",
    "tasks": [
        {
            "label": "foo",
            "dependsOn": [
                "bar",
                "baz"
            ],
            "problemMatcher": [],
        },
        {
            "label": "bar",
            "problemMatcher": [],
        },
        {
            "label": "baz",
            "problemMatcher": [],
        }
    ]
}
```
2. Execute task "foo"

VSCode outputs: 

```
> Executing task: echo baz <

baz

Terminal will be reused by tasks, press any key to close it.
```
and in a separate terminal panel:
```
> Executing task: echo bar <

bar

Terminal will be reused by tasks, press any key to close it.
```
"foo" doesn't seem to be executed at all.

Also, I'd have expected all tasks to be ran in the same terminal, unless presentation.panel is set to "dedicated" or "new".

**Comment by dbaeumer** [comment]
All dependsOn task are executed in parallel in different terminal. If you want to execute them in sequence make foo dependOn bar and bar on baz. If foo should execute its own command you need to specify the command explicitly. Task with dependsOn don't inherit commands from the global scope.

Closing the issue. Please ping if things are unclear.

**Comment by vadimcn** [comment]
> Task with dependsOn don't inherit commands from the global scope.

I agree, this is how it works right now, but why does "dependsOn" imply "don't inherit commands from the global scope"?   There's no obvious relationship that I can see.

My mental model of tasks.json is: "VSCode takes global properties defined at the top level, merges them with individual task's properties, then executes the resulting task description".   Most of the time it works like that, but unfortunately not always.  This area of VSCode feels very under-specified, TBH.

**Comment by dbaeumer** [comment]
We made that decision because it is more likely that depensOn is used to group tasks and don't define their own. If we would honor global commands in dependsOn then we would need to have a flag to tell to not honor it. It seemed more logical to turn this since if you want to have a command with dependsOn you can simply but one.

I agree on that the documentation should make this more clear.

**Comment by vadimcn** [comment]
Could be as simple as `"command" : null`, no new flags needed.
I bet you are going to see more bugs filed about this...
