### ISSUE TITLE
"Notifications" issues

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#44083]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

1 notification**S** ?

![image](https://user-images.githubusercontent.com/24613274/36461047-3b43fd82-16c4-11e8-9200-2d9da4d88cae.png)

---------

I don't think, that message about "No updates are currently available" has to be stored at all.
It has no sense.

![no updates available](https://user-images.githubusercontent.com/24613274/36461538-bc35d6fc-16c6-11e8-968f-8130db1e5e39.gif)

----------

IMO, there are too many empty space:

![image](https://user-images.githubusercontent.com/24613274/36461710-bc382be0-16c7-11e8-80a2-e5fc1da20804.png)

-----------

X - should have hover effect by color, and a little background-color

![x - hover effect](https://user-images.githubusercontent.com/24613274/36461818-5660e018-16c8-11e8-978b-f70865da2fe7.gif)

also IMO - notification should be closed by click on any part of the notification.
cause users don't like to aim at the X.

------------

width exceeding issue:

![width issue](https://user-images.githubusercontent.com/24613274/36462051-bf71ec86-16c9-11e8-876e-e1b1d602fb17.gif)

------------

This "Hide notifications" text is redundant. And it makes to jump the whole set of the buttons at it's left.
Looks really clumsy.
Should be changed just to different icon, or different color, or to be darken while it's active.

![jumping](https://user-images.githubusercontent.com/24613274/36462133-3cfba85e-16ca-11e8-9c56-291fd176f2f4.gif)

------------

Also notifications should be hidden by themselves - when user already focused on the editor, or especially on the terminal.

**Comment by bpasero** [comment]
@user3323 thanks for the feedback, I fixed some of the issues. Please try again in tomorrows insiders build and then please please stay away from filing an issue with many issues within. You see the problem with that, I cannot even easily tell you what I fixed since this issue has so many parts.

Thanks.
