### ISSUE TITLE
Leverage notification progress support for progress API

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44090]
With the new notifications comes support for showing long running operations:

![before 1](https://user-images.githubusercontent.com/900690/36467075-5f0849ee-16dd-11e8-9bd6-4ef6dc81f215.gif)

We currently have an API where you can show global progress:

![before](https://user-images.githubusercontent.com/900690/36467005-fb83184a-16dc-11e8-8c3c-db22a0e1a7b6.gif)

One advantage of having this within progress is to free space from the status bar and also to indicate from which extension the progress is reported (because notifications always show their source). Another advantage is that we could provide a "Cancel" button to stop the operation.

We could move this into a notification as a first step and could offer additional APIs to:
* report more detailed progress on the progress bar
* provide additional actions ("Cancel" for example)

@jrieken thoughts?

**Comment by Tyriar** [comment]
@sean-mcmanus might find this useful for the C++ extension. Related: https://github.com/Microsoft/vscode-cpptools/issues/1160

**Comment by chrisdias** [comment]
@EricJizbaMSFT @fiveisprime this would be great for the Azure extensions which have long running processes creating resources...

**Comment by dragonwolf83** [comment]
This would be useful for the PowerShell Extension as well.

**Comment by jrieken** [comment]
Yeah, maybe another `ProgressLocation` is what we want. Something like `ProgressLocation.Prominent` and then add a cancellation token to the task-callback. An alternative approach would be to have a progress-message, tho it feels wrong

**Comment by bpasero** [comment]
@sean-mcmanus @EricJizbaMSFT @fiveisprime @dragonwolf83 @chrisdias this will be in stable API for our March release. You might want to create reminder issues to check it out next month. A sample to use it is:

```typescript
vscode.window.withProgress({
    location: vscode.ProgressLocation.Notification,
    title: "this is cool",
    // cancellable: true
}, (progress, token) => {
    token.onCancellationRequested(() => {
        console.log("CANCELED")
    });

    setTimeout(() => {
        progress.report({ percentage: 10, message: "still going..."});
    }, 1000);

    setTimeout(() => {
        progress.report({ percentage: 50, message: "still going harder..."});
    }, 2000);

    setTimeout(() => {
        progress.report({ percentage: 90, message: "almost there..."});
    }, 3000);

    var p = new Promise(resolve => {
        setTimeout(() => {
            resolve();
        }, 5000);
    });

    return p;
});
```

**Comment by agauniyal** [comment]
I hope the progress bar won't be so thin :confused:

**Comment by bpasero** [comment]
@agauniyal the UI did not change from what I showed in https://github.com/Microsoft/vscode/issues/44090#issue-298861132 and the size of the progress bar matches with any other progress bar we have in the UI.
