### ISSUE TITLE
Dev tools debugger breaks for non-git folders with dev tools open

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#44092]
I don't know if this is expected, since it says it's breaking on a promise rejection, but if I open dev tools then open any folder that is not a git repo, the debugger breaks:

![git config reject](https://user-images.githubusercontent.com/1078012/36469329-cd28e6da-16de-11e8-9077-afef4885a2ec.png)

This is kinda annoying if you have a workspace with 5 folders open (and have dev tols open eg. because working on an extension) and then you reload the window - you break 5 times.

I don't know if there's some setting to control this (I know there's a "break on promise rejects" in the Code debugger, but this is the Chrome dev tools). Despite what [this answer](https://stackoverflow.com/a/32755965/25124) suggests, I do *not* have "break on unhandled exceptions" ticked (as you can see in the screenshot).

**Comment by joaomoreno** [comment]
https://stackoverflow.com/questions/32755631/can-i-prevent-that-chrome-v45-pauses-on-promise-rejections

Promise rejections are considered errors. The only way you can avoid breaking on that is disabling the "Break on Exceptions" button.

![image](https://user-images.githubusercontent.com/22350/36470643-df1e66dc-16eb-11e8-81d3-9feb1c0ebe21.png)

**Comment by DanTup** [comment]
@joaomoreno If these are considered errors, could/should the Git code be changed not to do this on all non-Git folders? Turning off breaking on errors does not seem like a good fix if people are trying to debug their own code :(

**Comment by joaomoreno** [comment]
How do you know this is the Git code? Can you follow a stack trace to know who tried to open that file? Does it reproduce with `code --disable-extensions`?

Also, debugging VS Code is not a user-facing feature. Does this happen when you debug an extension?

**Comment by DanTup** [comment]
> How do you know this is the Git code? 

On the right side of my screenshot it shows the error is "File not found" for ".git/config" in each of the folders I have in the workspace.


> Can you follow a stack trace to know who tried to open that file? 

Unfortunately the call stack is a bit lacking:

![Stack](https://user-images.githubusercontent.com/1078012/36479705-867815a8-1701-11e8-8bee-a081bdbc7951.png)


> Does it reproduce with `code --disable-extensions`?

Yep.


> Also, debugging VS Code is not a user-facing feature. Does this happen when you debug an extension?

Yep, that's right. I'm working on an extension so I often have the console open. If I have them open during the loading of a workspace, I get thrown into the debugger here like this for each folder (and have to hit the continue button a bunch of times). It really breaks the flow when you're testing something, run `Reload Window` and then everything locks for several prompts :(

**Comment by joaomoreno** [comment]
Have you tried using the recommended way of testing/debugging extensions: <kbd>F5</kbd>? Is the experience bad there too?

cc @jrieken @bpasero for the break in `fileService.ts`

**Comment by DanTup** [comment]
I'm using `F5` for debugging the extension; I just often also have dev tools open (sometimes I see errors in the dev console that didn't break/log in the main window - though if this isn't expected I'll do some digging next time it occurs).

**Comment by joaomoreno** [comment]
Got it.

I found where the access is being done cc @ramya-rao-a @chrmarti 

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/stats/node/workspaceStats.ts#L141
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/stats/node/workspaceStats.ts#L325

We probably won't change anything, unfortunately. IMO Chrome should not break on _caught_ promise rejections unless the checkbox for `Pause on Caught Exceptions` is checked.

**Comment by DanTup** [comment]
Is it possible/reasonable to do an exists check somewhere so it just returns an empty collection of the file is missing without the exception (so the promise doesn't reject, but it gives the same empty results)?

It wouldn't be so annoying if it only happened once, but since it's for every folder in the workspace it gets a bit tiring :(

**Comment by bpasero** [comment]
Yeah I also find this annoying and think that the workspace stats should maybe do an exists check first.

**Comment by ramya-rao-a** [comment]
@DanTup I understand you see this when debugging an extension. Is the extension code not in git or the window that opens up (extension development host) has a workspace with folders that are not in git?

**Comment by DanTup** [comment]
The folders I'm opening in the extension dev host are not in Git; I'm just using them for testing (actually, that's a slight lie - they are in Git, but it's a few folders up - I'm opening subfolders of the repo).

**Comment by ramya-rao-a** [comment]
I cant repro it in either Insiders or Stable. 
@bpasero @joaomoreno Either of you see the same?

**Comment by bpasero** [comment]
@ramya-rao-a just open a folder and have the break on error on and you see hits in the file service originating from workspace stats.

**Comment by DanTup** [comment]
Not sure if it matters, but I am:

- Opening a workspace with two folders
- Both folders are descendants of a git repo (so there is a .git up the tree, but not in the path shown in the error)
- Running "Reload window" command (it's after the reload the errors trigger)

**Comment by DanTup** [comment]
LGTM in Insiders 👍
