### ISSUE TITLE
Vscode crashes on WindowsPE at opening files

### ISSUE THREAD

**Issue by logg-sar** [Microsoft/vscode#44094]
- VSCode Version: 1.20.1 Date 2018-02-12T 15:34:36:336Z
- OS Version: Windows PE based on Windows 10240

Steps to Reproduce:

1.Download VSCode-win32-x64-1.20.1.zip and unpack to x:\program files
2. start code.exe (its starting - yipee!)
3. press ctrl-o or ctrl-k /ctrl-o and it will crash

Does this issue occur when all extensions are disabled?: Yes

I found some Logs in X:\windows\temp which i´m attaching here.
[temp.zip](https://github.com/Microsoft/vscode/files/1743315/temp.zip)

I will try to reproduce this on a newer PE version, but not today.

*edit*
Same with Windows 10.0.17093.1000

**Comment by RMacfarlane** [comment]
I'm not familiar with WindowsPE, but from reading this https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-intro it seems it may not be suited for running VSCode. What's your use case?

Here's our wiki on collecting crash data: https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#windows

**Comment by logg-sar** [comment]
@RMacfarlane ; @bpasero 

on the winpe-intro-site is written:

**Install Windows by using apps or scripts from a network or a local drive.
Add your own custom shell or GUI to automate these kinds of tasks.**

Thats exactly what I´m doing. Until now the scripts was batch but Powershell is way more powerful.

For the moment i´m using notepad++. There i write the script mark one or more lines copy them to the powershell console and execute them. Yes, its working, but....

Also on the site you mentioned are some limitations of PE

**_.MSI installation files._**

I will try to install debug and diagnostic tool to provide an proper debug log, but....

**Comment by logg-sar** [comment]
Hi

as expected/feared the debug diagnostic tool isn´t working proper with the limitations of PE..

So i ´m not able to provide any additional and logs.

Now I don´t know - on one hand I have to use powershell, which is supported by ms. 
On the other hand working with Powershell on PE is quite annoying. There are some tools - also provided by MS - but none of this are working properly.

At this time i have an editor and have to copy line by line and function by function to the powershell window and execute them. This is sadly slow and annoying, but the only working way.

You decide if you want to close this issue - I would love to use VSCode for daily work, but its not in my capabilities to do this,

However - thanks!

**Comment by bpasero** [comment]
I am not sure what Windows PE is, but we do not officially support it. Closing.

**Comment by logg-sar** [comment]
Windows PE is Windows **P**reinstall**E**nvironment
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-intro?f=255&MSPPError=-2147217396
and thats the environment I _have_ to work.

But its ok to close it, because its a PE (or to be exact dotnet core issue) which will be fixed with dotnetcore 3. 

Maybe.

Probably.
