### ISSUE TITLE
Feature Request: Explorer File Search

### ISSUE THREAD

**Issue by DerHerrGammler** [Microsoft/vscode#44099]
- VSCode Version: 1.20
- OS Version: Win10

Actually I can search for files with `strg + p` for some files and open them in the editor. But I think it would be better if I can type the filename in a Searchbar in the explorer. Because of the following tree:
```
api
- load
--- data.js
- add
--- data.js
```
Id I search for my `data.js` I got two files and with `strg + p` its complicated to understand wich is the wrong file. If I can search in the Workspace folder and see the files in the directorys I see wich one is the right one. In Visual Studio 2017 it's implemented that I can search in my wokrspace for files.

**Comment by yume-chan** [comment]
@bpasero can you reference the duplicated issue please?

**Comment by DerHerrGammler** [comment]
ok no reference for us... sad life
