### ISSUE TITLE
Allow to pick working files via quick open

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#441]
There is a ctrl+tab feature right now, but it isn't among the working files, it is among the latest files, a feature I haven't really understood yet

**Comment by bpasero** [comment]
There are more commands to cycle between your working files (check command pallette). Ctrl+Tab is ment to navigate between any file you opened, not just working files.

**Comment by thewhitetulip** [comment]
Isn't this a bit of an overkill? al+tab since inception has been to cycle between working files

**Comment by bpasero** [comment]
Please give it a try for some time and then see if you still dont like it.

**Comment by thewhitetulip** [comment]
To be honest vscode is the only editor I have used since you guys released it and ctrl+tab feature annoys me since I can't cycle between the files, I have to always do a ctrl+shift+e and then open the file I want to open since I use in full screen and the sidebar is closed.

by design ctrl+tab shouldn't be kept for opening any historical file we can have some other shortcut for that!

i am using VSCode right now, and cycling between files is very very hard, the ctrl+K downkey is also non usable in my honest opinion

**Comment by bpasero** [comment]
Ok, lets reopen and treat as enhancement: You are asking for the same functionality as Ctrl+Tab but limited to working files. Maybe we could make this an option in the settings.

**Comment by thewhitetulip** [comment]
Yes, this will work fine! we can toggle through the settings, but honestly nobody is going to change the default setting if you set ctrl+tab to open working files :smile:

**Comment by bpasero** [comment]
Sure...

**Comment by bpasero** [comment]
Pushed for February release. Quick open special char is `~` and keybinding out of the box is `CtrlCmd+K CtrlCmd+P` but obviously can be reassigned to `Ctrl+Tab`.

![untitled](https://cloud.githubusercontent.com/assets/900690/12889642/2a41570c-ce80-11e5-94d7-b85912fdc24f.gif)

**Comment by thewhitetulip** [comment]
This is awesome! :+1:
