### ISSUE TITLE
Arguments tab always collapsed in Debug mode (Python)

### ISSUE THREAD

**Issue by Collederas** [Microsoft/vscode#44105]
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra 10.13.3

Steps to Reproduce:

1. Write a python function with one or more arguments
2. Place a breakpoint inside the function
3. Start debug mode and let the execution stop at your breakpoint
4. Look on the VSCode Debug panel. You will see the VARIABLES section. There are "Local" and "Arguments" subsections. "Arguments" contains the value of the arguments of your function. That tab is collapsed. Expand it.
5. Step over to the next line in the function using the Debug toolbar
6. The "Arguments" section is collapsed again!

This makes debugging pretty annoying.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Collederas** [comment]
Related to https://github.com/Microsoft/vscode/issues/32199

(It is actually the same issue)

**Comment by weinand** [comment]
I do not think that this problem occurs with all extensions disabled (because Python debugging would not be available at all).

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#843

**Comment by Collederas** [comment]
Yes of course I disabled everything except the python one. I thought it was kinda superfluous to state that.

**Comment by weinand** [comment]
With the extension question we want to help bug authors to think about whether it's a VS Code or an extensions issue (and file to the correct repository ;-)
