### ISSUE TITLE
Disable all extensions also disables built-in extensions

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#44104]
Version 1.21.0-insider
Commit 6309a7734b0b0876b263a6a9cb526fc281100089
Date 2018-02-20T10:23:21.993Z

- from the extensions viewlet drop down select 'Disable All Installed Extension'
- restart
- note that also all built-in extensions are disabled

**Comment by sbatten** [comment]
Reloading windows with disabled extensions now puts builtin extensions in a perpetual "reload to deactivate" state. 
![image](https://user-images.githubusercontent.com/6561887/36996952-f3103ece-206c-11e8-8659-305f647ef156.png)

**Comment by sandy081** [comment]
@sbatten What are the steps you followed to get into this state?

**Comment by sbatten** [comment]
@sandy081 
1. Open insiders and show built in extensions to see everything is normal.
2. Use command palette to reload window with extensions disabled.
3. Show builtin extensions. All will be enabled but have 'reload' buttons with hover text 'reload to deactivate'

**Comment by RMacfarlane** [comment]
The `Reload Window with Extensions Disabled` action uses the same switch as the `--disable-extensions` flag, so this can also be repro'ed just by lauching code-insiders with `--disable-extensions`.

**Comment by sandy081** [comment]
@sbatten Good catch. Provided a minimal fix - not to show reload action when `code` started with `--disable-extensions`. 

Implementation wise, it is not ideal. Created a follow up debt item for cleaner implementation -#45122
