### ISSUE TITLE
Snippet suggestions don't appear in menu in React prop arrow-functions

### ISSUE THREAD

**Issue by Nvveen** [Microsoft/vscode#44107]
- VSCode Version: 1.20.1
- OS Version: Linux localhost 4.15.3-2-ARCH #1 SMP PREEMPT Thu Feb 15 00:13:49 UTC 2018 x86_64 GNU/Linux

Steps to Reproduce:

1. Write a React component
2. Add an arrow function in a prop of a subcomponent
3. Open the suggestions window (ctrl+space) or add a snippet from the menu

Suggestions appear properly when writing normal functions and arrow functions, but since a few updates (I can't tell how far back), I will not get any snippet suggestions in arrow functions of React props. I do get Intellisense-suggestions, so the suggestions window does still work.

**Comment by mjbvz** [comment]
Please provide some example code that shows where snippet suggestions do no show up
