### ISSUE TITLE
Notifications: proper icons

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44108]
We are using icons for severity (info, warning, error) and I think they do not look great, maybe we can optimize them for notifications:

![image](https://user-images.githubusercontent.com/900690/36476390-16544786-16fe-11e8-97d4-efc8fdf7a9a6.png)

![image](https://user-images.githubusercontent.com/900690/36476395-195b02a8-16fe-11e8-8634-0062659985af.png)

We are also using these icons in the markers panel:

![image](https://user-images.githubusercontent.com/900690/36543283-9fdf5b7c-17e3-11e8-867a-6a335939c29e.png)

**Comment by bpasero** [comment]
@chryw hey, would this be something you could maybe help us out with?

**Comment by bpasero** [comment]
Thanks to @tlowdermilk I think we are good 👍

**Comment by chryw** [comment]
@bpasero those are same icons as in Visual Studio IDE. I'm open to feedback though. Do you have more specific info on what didn't work?

**Comment by bpasero** [comment]
@chryw now we settled on this:

![image](https://user-images.githubusercontent.com/900690/36579462-8202d7b6-1863-11e8-8970-9b1d7394a1a9.png)

![image](https://user-images.githubusercontent.com/900690/36579466-864126e8-1863-11e8-850b-96aedd8493fa.png)
