### ISSUE TITLE
Working Directory Changes appear duplicated in search

### ISSUE THREAD

**Issue by MeikTranel** [Microsoft/vscode#44102]
### Issue Type
Bug

### Description

When searching for words that are currently in the working directory diff, search returns 2 results.

Reproduction Steps:
- Open Workspace with underlying git repository
- Add random text "abcdef" in a random file
- search for "abcdef" in workspace search
- Search returns abcdef line twice as 2 seperate occurences

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (6309a7734b0b0876b263a6a9cb526fc281100089, 2018-02-20T10:24:00.306Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (4 x 1800)|
|Memory (System)|15.89GB (9.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
cake-vscode|cak|0.10.1
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.13.0
xml|Dot|1.9.2
gitlens|eam|8.0.2
beautify|Hoo|1.3.0
Ionide-Paket|Ion|1.9.1
vscode-kubernetes-tools|ms-|0.1.5
csharp|ms-|1.14.0
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.1.0
vscode-docker|Pet|0.0.24
vscode-icons|rob|7.20.0
msbuild-project-tools|tin|0.2.27
omnipascal|Wos|0.15.0
markdown-all-in-one|yzh|1.0.5

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
I don't see this. I don't think it should be searching diffs. Can you try again and show a screenshot?

**Comment by MeikTranel** [comment]
Currently can't reproduce it on my personal workstation either. I'm gonna check back tomorrow on the actual machine that i found this on.
