### ISSUE TITLE
Integrate the famous ed editor in the commandPalette

### ISSUE THREAD

**Issue by JACK-THINK** [Microsoft/vscode#44115]
### Feature Request
Now vscode is not good at **line-oriented text editing**. If you could integrate the famous line-oriented text editor **ed** in the commandPalette, vscode will become very powerful.

**Comment by svenax** [comment]
It is already integrated. Just open a terminal pane and run ed from there.

**Comment by JACK-THINK** [comment]
@svenax Perhaps I didn't make my point clear. if I can press Ctrl+Shift+P, fill a “:” in the blank, and use commands supported by ed editor like "<line number>s/<pattern>/<code>/g" to modify my scripts, vscode would be more powerful.
By the way, my vscode is installed on Windows 10 and I've tried to run ed many times, but I just couldn't run it anyway. Could you explain how to run ed editor in detail? Thanks a lot.
