### ISSUE TITLE
[Typescript][Feature] Automatically add inferred types to code

### ISSUE THREAD

**Issue by Alber70g** [Microsoft/vscode#44111]
_I'm not sure if I should place this here, but since I cannot find the specific repo for Typescript in VSCode, it seems to be the correct place_

When working with Typescript it's very nice that the compiler infers a lot of types for me. However, I usually add the return type to functions in order to preserve the signature when refactoring functions. This way I don't end up having a problem when I accidentally change the return type because I return something different. 

Would it be possible to add the return type automatically, since the AST knows what type I'm returning. 

This could be an option to do when doing _format code_ and optional for const's let's functions and others that infer types.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25141
