### ISSUE TITLE
Ability to change command line arg names to avoid arg name conflicts

### ISSUE THREAD

**Issue by tdbe** [Microsoft/vscode#44117]
VSCode's `-n` arg opens a new session of VS Code instead of restoring the previous session (default). 
In other software, `-n` means go to line number.

For example: If from the Unity game engine you doubleclick on a file, it will send the -n command and will open VSCode with a new session or close your existing open Workspace.

This for example does not happen with Visual Studio and Unity.

Could we please have a config to change what `-n` means?

Thank you.

**Comment by bpasero** [comment]
Sorry, I find that a request hard to justify. Closing as wontfix.

**Comment by tdbe** [comment]
You determined that large scale tools (like big game engines) need to implement a special case for your internal standard of command line args? From where I'm sitting I perceive that as lack of flexibility unfitting for VSCode's brand (and hard to justify).

I would at least mark it as a nice to have and just make it a line in an .ini file. 

Or give the uncaring public a good reason why they have a bad workspace UX in VSCode while in Visual Studio there's no friction.

**Comment by tdbe** [comment]
For everyone who has this problem, I've found an opening on another avenue: 
There's a trick to injecting custom command line args in Unity: https://stackoverflow.com/questions/49550056/unity-opens-multiple-workspaces-when-using-vscode-as-editor/49557370#49557370
