### ISSUE TITLE
Forward wordwise delete (Ctrl+Del) deletes whole line if performed at EOL? 

### ISSUE THREAD

**Issue by frevds** [Microsoft/vscode#4411]
Not a feature but an annoyance: 

I perform the following things rather often: 
Have code like this: 

    One Two Three
    Four Five Six

If I (efficiently) want to remove "Two Three" and join "Five Six" to result in: 

    One Four Five Six

I should have to perform only 4 repeated strokes of Ctrl+Del. 
I place the cursor before "Two" and repeatedly press Ctrl+Del, which works in most editors, except VS Code, where it works only until I end up at the end of the line. Wordwise deleting Two and Three is fine, but pressing Ctrl+Del at the end of the line deletes the whole line, which is IMHO not the intended effect of joining the contents of the following line (and removing leading whitespace). 
So instead of quickly joining contents I end up having to carefully pay attention and stop at the end of the line, release Ctrl and join the lines with Del only. This is suboptimal. 
I suspect this is not a feature, since deleting lines is usually not performed by placing the cursor at the end and pressing Ctrl+Del? 

Thanks for fixing this.

**Comment by alexandrudima** [comment]
Thank you for filing. Dup of #3882. Will be fixed in the March release.
