### ISSUE TITLE
Wrong File explorer updated position after file delete

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#44125]
- VSCode Version:1.20.1
- OS Version: Windows7

Steps to Reproduce:

1.Double click in the file explorer on a folder
2.Select a file
3. Delete the file
4. After refresh the file explorer is positionned on the last file edited and should had stay on the folder where we deleted the file. For deleting several files we have to go back and forth, that's not really practical

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is fixed in the latest vscode insiders https://code.visualstudio.com/insiders/.
It will be in vscode stable in about two weeks
