### ISSUE TITLE
Bug with js code highlighting

### ISSUE THREAD

**Issue by someden** [Microsoft/vscode#44124]
- VSCode Version: 1.20.1
- OS Version: macOS 10.13.3 (17D47)

Ok:
![screen shot 2018-02-21 at 16 54 17](https://user-images.githubusercontent.com/7009699/36483749-0c0b9840-1728-11e8-9691-8c544176bbd8.png)

Bug:
![screen shot 2018-02-21 at 16 54 00](https://user-images.githubusercontent.com/7009699/36483755-115947c0-1728-11e8-9d2e-ca0d88f5e4cb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by andy-ms** [comment]
Microsoft/TypeScript-TmLanguage#571

**Comment by mjbvz** [comment]
Thanks @andy-ms! Closing as upstream grammar issue
