### ISSUE TITLE
Go to File command should only open files from current workspace

### ISSUE THREAD

**Issue by ptrajkumar** [Microsoft/vscode#44126]
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra 10.13.2

Steps to Reproduce:

1. Setup two workspaces preferably clones of same git repo. Say there is a file called "foo.js" in both workspaces
2. open -a '\''Visual Studio Code'\'' $HOME/first.code-workspace
3. Go To File and search for foo and it will autocomplete to foo.js in first workspace
4.  Close Visual studio code
5. open -a '\''Visual Studio Code'\'' $HOME/second.code-workspace
6. Notice that when you search for foo it offers foo.js from another workspace.

Ideally it should only offer files from the current workspace. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@ptrajkumar weird, can you show a video of this issue in action? Unless foo.js is not in both workspaces, I would not expect foo.js to show up in second workspace.

**Comment by ptrajkumar** [comment]
foo.js is in both workspaces. The problem is once you open foo.js in first workspace and close that workspace and open the second workspace.  Doing quickopen and typing foo.js completes it to foo.js in first workspace and not the second workspace.

**Comment by bpasero** [comment]
@ptrajkumar and to be clear foo.js is in 2 different folders and you still get the folder from the other workspace? Can you please attach screenshots or a recording what you are doing.
