### ISSUE TITLE
Dismissed notifications are lost forever

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#44123]
*This is a follow-up to: #22388.*

**Summary**
The current notification model does not accurately represent the desired user actions. Currently, notifications are either "read (deleted)" or "unread". However, there should be a third state, "read (dismissed)". This would be used when a user would like to remove a notification from their screen, but come back to it later. This would also be required for a true notification center, where "dismissed" notifications would be acted upon.

**Comment by bpasero** [comment]
@mattacosta you can just press ESC when notification toasts are there to ignore them and they will still be in the notification center. Why do you need a third state? To my knowledge not even Windows has this?

**Comment by mattacosta** [comment]
You are technically correct, there is no need for a third state. Windows doesn't have it either because it forces applications to manage their notification history in all cases except one. I was thinking of a scenario where vscode would handle it, but that can be fixed with a better API, so I'll just leave it to #44121 instead.

**Comment by mattacosta** [comment]
From #44185:
>Maybe these unimportant notifications could go away entirely, or be in the notification center but without the alert in the status bar?

The second case also covers what I was thinking about here. Clicking "show notifications" should mark unread notifications as read and set the "new notifications" counter to 0. Currently, the only way get the counter back to 0, is to also delete the notification.

I'll add a picture to the summary to better describe the original use case too. I still think #44122 is a better fix though, so I'm keeping this issue closed. You guys can use the other issue if you want to fix it another way.
