### ISSUE TITLE
Improve notification APIs

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#44121]
**Summary**
The current notification API does not currently provide a distinction between notifications (these don't require user interaction) and prompts (these do require user interaction) or implement the required functionality for additional notification features that have been requested. This also results in instances where the wrong UI element is used, which hinders the workflow of some users.

**Proposal**

**Add a notification manager containing related notification methods to the `window` object.**
   Ex: `window.notifications.addError('Something bad happened.');`

   The manager would provide the following methods and events:
   - `addInfo()`: accepts a message and options parameters, returns a notification object
   - `addWarning()`: accepts a message and options parameters, returns a notification object
   - `addError()`: accepts a message and options parameters, returns a notification object
   - `getNotifications()`: returns a list of notifications
   - `onDidAddNotification`: event that invokes a callback that receives a notification object
   - `removeNotification()`: accepts a notification, tag, or extension id

   &nbsp;
   The `NotificationOptions` object would also contain the following properties:
   - `title`: string
   - `details`/`source`: markup?
   - `buttons`: array
   - `tag`/`group`: string
   - `isExpanded`: boolean (for backward-compatibility)

   &nbsp;
   The `Notification` object contains information about the added notification and an `onDismiss` event. This object would also be required for other features, such as #44122.

**Add a generic `showDialog` method to the `window` object.**

   // TODO: This method would... accept simple message parameters, or an object that implements an abstract `Dialog` class? Could these dialogs also show custom markup?

**Backwards compatibility**
The current APIs should be marked deprecated.

If desired, an "adapter" class or service could also redirect deprecated API calls to the most appropriate (notification or dialog box) action, thereby allowing use of updated UI elements by deprecated code in most cases.

**Comment by jrieken** [comment]
Well, there is a little known flag to make messages modal, so enforce user to act on them.

**Comment by ORESoftware** [comment]
I have a question - is there documentation on how to ping VSCode from another process on the same machine and tell VSCode to display a notification? Is VSCode listening on localhost?
