### ISSUE TITLE
Translation string with an extra space displayed

### ISSUE THREAD

**Issue by onecentlin** [Microsoft/vscode#44120]
I found a small issue in toolbar within `task` section.

Locale: `zh-TW`

In transifex translation string looks fine, however, VS Code displayed with an extra space.

![img_20180221005](https://user-images.githubusercontent.com/7122270/36481958-8504347c-174c-11e8-90b9-939cf25658ad.png)

**Comment by RMacfarlane** [comment]
Sorry, I'm not able to tell where the extra space is - could you highlight it?

**Comment by onecentlin** [comment]
1st item and 3rd item is aligned. BUT, second item (with red box) has one space different.

![img_20180222003](https://user-images.githubusercontent.com/7122270/36517576-9b702da8-17bd-11e8-8bd1-93b150490bbc.png)

**Comment by RMacfarlane** [comment]
@dbaeumer There's a space at the beginning of this string in the translations file: https://github.com/Microsoft/vscode/blob/master/i18n/cht/src/vs/code/electron-main/menus.i18n.json#L177 How is this file generated?

**Comment by dbaeumer** [comment]
The strings are maintained in Transifex (https://www.transifex.com/microsoft-oss/vscode-workbench/dashboard/). @danyeh can you help with this. The XLF file that we download from Transifex has already a space in the string this is why we have the space in the i18n.json

```
    <trans-unit id="miBuildTask">
      <source xml:lang="en">Run &amp;&amp;Build Task...</source>
      <target> 執行建置工作(&amp;&amp;B)...</target>
      <note>&amp;&amp; denotes a mnemonic</note>
    </trans-unit>

```

**Comment by danyeh** [comment]
Re-copied translation in Transifex.

**Comment by danyeh** [comment]
Re-copied translation in Transifex [fixed ](https://github.com/Microsoft/vscode/blob/master/i18n/cht/src/vs/code/electron-main/menus.i18n.json#L178)the issue. Look like there was something wrong in Transifex exporting logic.
-	"miBuildTask": " 執行建置工作(&&B)...",
+	"miBuildTask": "執行建置工作(&&B)...",
