### ISSUE TITLE
Typing a comma in argument list shows parameter hints in an object/array

### ISSUE THREAD

**Issue by marcoms** [Microsoft/vscode#44129]
When I type a comma inside a function argument list inside an object/array, the parameter hints are shown even before I have finished the argument.

E.g. in the following example, I am still on the 0th argument but the parameter hints are shown as if I'm moving on to the next one. Instead those hints are not relevant to me because I am still typing the same argument.

![thisone](https://user-images.githubusercontent.com/4211302/36485212-86fc181e-1713-11e8-8875-2e8e798bbe9c.gif)

This gets really inconvenient because I can't see the surrounding context of my code when I just type a comma, but the hints are actually useful when I finish an argument, so I wouldn't want to disable them.

**Comment by mjbvz** [comment]
Thanks! Opened https://github.com/Microsoft/TypeScript/issues/22106 to track this upstream
