### ISSUE TITLE
Extensions should be able to control their notification history

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#44122]
**Summary**
In certain scenarios it is possible for a notification to become invalid. In this case, the notification should not be displayed in the notification center.

![no_update_notification](https://user-images.githubusercontent.com/1007463/36482550-eafd979a-16d0-11e8-9a54-f41c61ec97cb.png)

or...

1. An extension displays a notification that a long-running operation has started.
2. This notification is hidden automatically and added to the notification center.
3. The extension displays a second notification that the long-running operation has finished.
4. The first notification should now be removed from the notification center by the extension.

**Comment by bpasero** [comment]
Imho this is unrelated to the notifications UX work. We should think about an API where you can programmatically remove the notification you brought up.

**Comment by jrieken** [comment]
Not a fan of that. When a message becomes visible it already grabbed the attention of the user. If now the extension decides to remove the message even more disturbance is caused. Extensions will never know when a good time to hide is because they don't "sync with the user's eyes".

**Comment by jrieken** [comment]
> The extension displays a second notification that the long-running operation has finished.

For long running operations *progress* should be used. Today, progress can be shown in the status bar and viewlet but we can different progress locations with ease and with different distraction levels.

**Comment by mattacosta** [comment]
>Not a fan of that. When a message becomes visible it already grabbed the attention of the user. If now the extension decides to remove the message even more disturbance is caused. Extensions will never know when a good time to hide is because they don't "sync with the user's eyes".

Huh? Extensions aren't responsible for displaying or animating the toasts, so that wouldn't even be possible. As for the notification center, visually it's no different than a user clicking the 'x' just before a new notification is added, *which is already something that can happen*.

This change would only affect the notification center; in the first scenario, this would happen:
- Extension triggers a toast.
  - If an extension tries to remove a notification now, it should throw an exception. Conceptually, it would be "active" and not yet in history (aka the notification center). Programmatically, the notification center would just be saying "no, it's still being shown, try again later" (using an `onDidAddNotification` event).
- Notification center is activated.
   - Is toast visible? Yes, immediately dismiss and move to notification center, extension can remove. No, it was automatically added to notification center already, extension can remove.

> For long running operations progress should be used. Today, progress can be shown in the status bar and viewlet but we can add different progress locations with ease and with different distraction levels.

This assumes that the only scenario is for "progress" type toasts. As shown by the image above, it is not, but if you want another use-case, consider an extension that allows collaboration between team members. It may want to send notifications when someone comes online, or when a message is received. The notification center shouldn't become a "chat history". Now, if you're thinking "lets just not add info-type messages to the notification center" well, error-type messages could also want this behavior too. For example, an extension may not want "not connected" error notifications to be logged either.

**Comment by DanTup** [comment]
Copying my comment from other case that was marked as a dupe so discussion is all in one place...

@jrieken 

> Not a fan. A notification is a strong distractor and once extensions show them they grab the attention of the user. Giving them the opportunity to hide them isn't something I'd like us to support because the worst would be notifications that come and go and keep distracting me.

I understand, but there are many places where we end up with a worse user experience.

For example, I was just implementing some refactors, like `Extract Method`. If the user tries to name their method with invalid characters, I show an error. The modal errors look terrible so I use this notification. If the user reads the notification in the corner of the screen then decides to just re-invoke the the refactor and give it a good name, they have a stale error message hanging around which is confusing.

I know there are shortcuts to get to the notifications, but many users won't know them, they'll just get annoyed that these error messages hang around after they've already dealt with them.

**Comment by jrieken** [comment]
> The modal errors look terrible so I use this notification.

Bad strategy - if something right looks/behaves wrong don't use another, wrong thing. Instead make us aware of those limitations, e.g. ugly model dialogs, limited input box, limited support for code actions that require input etc.

**Comment by DanTup** [comment]
Fair point, I'll raise an issue about that - though modals are still a bit of a usability issue. We wouldn't want to use them for "Do you want to restore packages?" prompt but we'd still want to hide that automatically if another action resulted in packages being restored.

**Comment by DanTup** [comment]
Opened #46646. It doesn't address the issue that some notifications that are best non-modal may become incorrect after being ignored for a while and that the ability to hide them would make sense. We can already do it using `withProgress` (though it'd be a terrible hack to use that here).

I appreciate comments about the user experience, but an extension author is better placed to make that call on a case-by-case basis than it being blocked for everything. Extensions can already provide poor user experiences in many ways; trying to stop that is futile. If we build something with a bad experience, we will get feedback from our users or they will stop using our extension.

I really love Code and how it enforces consistency across different languages, but it often feels that it becomes restrictive. We want to build the best experiences in Code so that more users will pick Code over the alternatives (it's not in our interest to build something shoddy or with bad UX); this works out best for both of us. If I start popping up modal dialogs to ask users non-critical questions just to avoid stale notifications hanging around, that will really suck.

**Comment by mattacosta** [comment]
> I appreciate comments about the user experience, but an extension author is better placed to make that call on a case-by-case basis than it being blocked for everything. Extensions can already provide poor user experiences in many ways; trying to stop that is futile.

QFT.

Also, what about a compromise, where the method gets added documentation along the lines of:
```ts
/**
 * Removes a previously delivered notification.
 *
 * Before using this method, consider the user's workflow and if the message
 * could be rephrased or should be a modal dialog instead.
 */
removeNotification(identifier: Notification | string): void;
```
