### ISSUE TITLE
Server 2016 - Intellisense Delay on Powershell Extension

### ISSUE THREAD

**Issue by clavrus** [Microsoft/vscode#44132]
- VSCode Version: 1.20.1
- OS Version: Server 2016
- PowerShell Extension 1.5.1
- PowerShell Version 5.1

**Steps to Reproduce:**

1. Open a new document with PowerShell as language
2. Type in 'Get-' (or any other command) and wait 4-10 seconds for Intellisense to complete

Does this issue occur when all extensions are disabled?: No - Related to PowerShell Extension, HTML intellisense works great

**System Info:** 
CPU: Intel (R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (4 x 2598)
Memory: 24.00GB (16.08GB free)
Process Argv: C:\Program Files\Microsoft VS Code\Code.exe
Screen Reader: no
VM: 100%

**Notes:**

1. It does not matter if I try any other command, or type in more of it so there's only one option for it.
2. PowerShell ISE intellisense is immediate
3. VSCode (same versions) on desktop works exactly how I'd expect it.
4. This was not introduced with a new version, been a problem since beginning.
5. I tried to use the issue reporter, the 'Preview On Github' button wasn't performing any actions.
6. It does not matter if it's the first time I try intellisense on a type of command.
[2018-02-21-1913-ProcMon.zip](https://github.com/Microsoft/vscode/files/1744354/2018-02-21-1913-ProcMon.zip)

**Comment by RMacfarlane** [comment]
Thanks for reporting. Since this is extension specific, please file the issue on the extension itself - I think https://github.com/PowerShell/vscode-powershell in this case. Are any other extensions seeing delays?

For the problem with the issue reporter, what browser are you using? Does a blank page open, or does nothing at all happen?

**Comment by RMacfarlane** [comment]
Is there anything in the dev tools console? `Ctrl+Shift+i` in the issue reporter window to bring it up

**Comment by clavrus** [comment]
![capture](https://user-images.githubusercontent.com/36702449/36558668-5c1bf218-17d1-11e8-90f4-84e8981b1fa2.JPG)

Note: I just discovered that I can submit a Bug Report or a Feature Request, the button is only broken on Performance Issue.

**Comment by RMacfarlane** [comment]
Thanks, that's very useful info! I've filed a separate issue to track it and will close this issue since you have moved the Powershell issue to the extension repository.
