### ISSUE TITLE
Remove suggest widget telemetry

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#4413]
We do not need it anymore.

fyi @egamma @joaomoreno

**Comment by alexandrudima** [comment]
Also quickFixWidget.

I would postpone this to April

**Comment by alexandrudima** [comment]
Also filePut

**Comment by alexandrudima** [comment]
I did not add this telemetry, so I will not take it out :)

**Comment by joaomoreno** [comment]
I'll do it!

**Comment by weinand** [comment]
Verified by code inspection
