### ISSUE TITLE
Make current item in a file search more visible

### ISSUE THREAD

**Issue by jpfortin** [Microsoft/vscode#44139]
When doing a search in a file, all the elements highlights but when navigating with previous and next arrows, there is not enough visual difference between all the elements and the current one. There should be a contour and/or at least a visual effect.

![img1](https://user-images.githubusercontent.com/3953181/36488696-1e5ad10e-16f2-11e8-82e3-7cc498aa6b23.png)

**Comment by usernamehw** [comment]
In Insiders build there is new color: `"editor.findMatchBorder"`.

**Comment by roblourens** [comment]
This should be handled theme-by-theme. I think it's good enough in the default themes but users can override individual theme keys if they prefer something else.
