### ISSUE TITLE
Inherited environmnet variables are reset

### ISSUE THREAD

**Issue by marak8** [Microsoft/vscode#44134]
- VSCode Version: 1.20.1
- OS Version: Arch Linux

This is related to https://github.com/dotnet/corefx/issues/26966 . `dotnet` can't build on platforms with ncurses >= 6.1 where `TERM=xterm-256color`. The workaround is to set `TERM=xterm` when running the `dotnet` tool.

Steps to Reproduce:
1. Start the VS Code with `TERM=xterm code` 
2. Try to build the C# project (F5)
3. Observe failure in the log caused by `TERM=xterm-256color`

This is because the `TERM` variable is reset for some reason in the VS Code. This is quite unexpected and it should be at least documented, that is why and how VS Code resets its environment. I guess other issues stem from this.

**Comment by Tyriar** [comment]
Good to know, looks like it's being handled on their end https://github.com/dotnet/corefx/issues/26966#issuecomment-367161783 https://github.com/dotnet/corefx/pull/27109
