### ISSUE TITLE
Module could not be loaded

### ISSUE THREAD

**Issue by KreciSie** [Microsoft/vscode#44133]
### Issue Type
Bug

### Description

When trying to run a command "Show-MVA_DSC_Slides" i am getting an error message:
"Show-MVA_DSC_Slides : The 'Show-MVA_DSC_Slides' command was found in the module 'MVA_DSC_2015_DAY1', but the module could not be loaded. For more information, run 'Import-Module MVA_DSC_2015_DAY1'.
At line:1 char:1
+ Show-MVA_DSC_Slides
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Show-MVA_DSC_Slides:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule"

Same command when run in ISE does launch slides. In Ise Slides are launched in Powerpoint. 
I did verified that module shows installed in ISE and in VSCode.

Thank you,
Mariusz

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|7.88GB (2.96GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.5.1
vscode-icons|rob|7.20.0

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
Please create the issue against https://github.com/PowerShell/vscode-powershell
