### ISSUE TITLE
Command Palette History (recently used) not populated when invoking commands programmatically

### ISSUE THREAD

**Issue by vazexqi** [Microsoft/vscode#44138]
- VSCode Version: Code-Insiders 1.20.0-insider
- OS Version: Darwin x64 17.4.0

Does this issue occur when all extensions are disabled?: Yes

## How did you encounter this problem? 

Commands that are executed via the right-click menu (using contributes.menu extension point) or `vscode.commands.executeCommand` do not show up in the command palette history (recently used).

Only commands invoked manually through the command palette show up.

## What steps do you need to perform to reliably reproduce the problem? 

1. Create a new extension that adds a command.
2. Create a new contributes.menu in package.json that invokes that command
3. Create a new command that invokes the command in  step `#1` using `vscode.commands.executeCommand`.

Notice that invoking the command via contributes.menu or `vscode.commands.executeCommand` doesn't put it on the command palette history.

## What did you expect to happen and what actually did happen?

Expected: Command palette is populated with the invocation of the command.

Actual: Command palette recently used list is not populated.

Is this the current design of the command palette history?

## What is your use case?

We are writing a test runner. We have added this as a code action. When the user invokes the code action, the command is executed. We would like that command to show up in the list of recently used so that the user can easily invoke Cmd  + Shift + P and then just see that the last invoked command is actually the test and can just run that again.

## Related issues

https://github.com/Microsoft/vscode/issues/13080
https://github.com/Microsoft/vscode/issues/17163
https://github.com/Microsoft/vscode/issues/29247

**Comment by bpasero** [comment]
I find it very weird that a recently used list would update without actually using that list. I am tempted to close this as designed unless someone has a scenario that convinces me.

**Comment by vazexqi** [comment]
@bpasero - Thanks for looking into this. 

I had an entry for our use in the initial issue:

> We are writing a test runner. We have added this as a code action. When the user invokes the code action, the command is executed. We would like that command to show up in the list of recently used so that the user can easily invoke Cmd + Shift + P and then just see that the last invoked command is actually the test and can just run that again.

I see two benefits to this: 

* The user can _discover_ that underneath the covers, what the code action did was just invoke this command so the user can re-invoke it even without the code action.
* Our particular command (re-run test) can be invoked outside the context of a code action. More concretely, if you ran the code action on FileA, then flip to FileB (since FileA has a dependency on FileB to fix the test), then whilst still on FileB, you can re-run the test easily through the palette through the last command.

But, I do agree that _if_ the design of the MRU  is _for the Command Palette_ then having commands not explicitly invoked through it show up is unintuitive.

**Comment by bpasero** [comment]
> But, I do agree that if the design of the MRU is for the Command Palette then having commands not explicitly invoked through it show up is unintuitive.

👍
