### ISSUE TITLE
Semicolon in PHP breaks indentation.

### ISSUE THREAD

**Issue by murgroland** [microsoft/vscode#44137]
- VSCode Version: 1.20.1
- OS Version: Windows 10

Hello,

I'm having a problem with the indentation breaking whenever i put a semicolon at the end of **endif**, **endwhile** or **endforeach** in PHP. It removes one or all the tabs and moves the code back one tab or at the beginning of the line.

![bug](https://user-images.githubusercontent.com/17927954/36488183-85ff8ab4-172b-11e8-84f9-1f1a28030da6.gif)

I have tried with all extensions disabled, and tried with a clean install on a different PC. Still the same.

Thanks.

**Comment by stacmv** [comment]
Did you find the bug? Are there any workarounds one can apply now?
This only bug makes me to desire more and more to switch Code for another editor. It's so sad.

**Comment by secretfork** [comment]
This is not windows 10 only, it happens on two different versions of Mac OS as well. Latest VS Code (1.25.1). It's rather irritating. I feel like this should affect everyone, unless it's because of the php-debug extension (only one i've installed).

**Comment by TylerBarnes** [comment]
@secretfork I'm on mac as well. One of my teammates who's also on mac doesn't use any php extensions and has this problem

**Comment by JacobDB** [comment]
Seems to be happening for HTML tags as well, at least in some cases.

![eo8eryxx9s](https://user-images.githubusercontent.com/1123997/50116058-b6222700-020e-11e9-8139-27f667c8211b.gif)

**Comment by siemano1** [comment]
Disabling "Auto Indent" option helped me solve this amazingly annoying issue

![image](https://user-images.githubusercontent.com/26684891/55093558-e2263180-50b4-11e9-82b7-6afc5f492074.png)

**Comment by manuman94** [comment]
Is this issue being continued?

It seems that PHP indenting and formatting is so annoying in VSCode. I migrate from Brackets for speed issues and other stuff but in this matter Brackets has a better editor.

**Comment by JacobDB** [comment]
@siemano1 thanks for that, that does help a bit, but doesn't really solve the underlying issue. It's just about half as annoying, but still annoying 😓

**Comment by mastahype** [comment]
It's strange this has been open for so long. There was a pull request referenced but I can't be certain it resolves this issue. It adds open and close handling for the php tag, but doesn't seem to address the outdenting for the semicolon on one-liners. I manually applied the configuration changes and didn't notice any difference.

**Comment by mwaterous** [comment]
It's now late July and this issue is still occurring in 1.36.1 on MacOS 10.14.5

**Comment by c-lawlz** [comment]
Ran into this same bug in 1.37.1, MacOS 10.14.6
