### ISSUE TITLE
All extension commands result in command '___________' not found

### ISSUE THREAD

**Issue by Glitched** [Microsoft/vscode#44148]
### Issue Type
Bug

### Description

Try to use any extension's command from the command palette, and be met with a command '--------' not found error

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vsc-material-theme|Equ|1.4.2
gc-excelviewer|Gra|2.0.17
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.2.3
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
vscode-styled-jsx|bla|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
jshint|dba|0.10.16
vscode-eslint|dba|1.4.6
githistory|don|0.4.0
es7-react-js-snippets|dsz|1.3.3
gitlens|eam|8.0.2
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
svg|joc|0.0.9
graphql-for-vscode|kum|1.9.0
MagicPython|mag|1.0.12
rainbow-csv|mec|0.1.0
metago|met|2.5.0
vscode-language-babel|mgm|0.0.12
vscode-clang|mit|0.2.2
cpptools|ms-|0.15.0
node-debug2|ms-|1.20.0
debugger-for-chrome|msj|4.1.0
indent-rainbow|ode|0.7.2
vscode-css-peek|pra|2.1.0
missinglineendoffile|ric|0.3.1
sass-indented|rob|1.4.8
preview-vscode|sea|1.4.2
stylelint|shi|0.32.0
vscode-spotify|shy|2.3.1
vim|vsc|0.10.13
vscode-react-native|vsm|0.6.1
join-lines|wma|0.2.2
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
When did you start seeing this issue? Have you installed any new extensions recently? What extensions commands have you tried running?

**Comment by Glitched** [comment]
Sorry to waste your time, but your comment was enough for me to resolve the issue. 
I installed "**Excel viewer**" this morning, and uninstalling it fixed the problem.

Some extensions that were broken was both beautify functions, anything in vscode-spotify, and Material Theme's options.

**Comment by RMacfarlane** [comment]
Thanks for reporting, it's useful to know that that "Excel viewer" has a problem

**Comment by 199621** [comment]
I apologize to anybody I may have upset this morning I’m having a real bad day and I have no reason to take it out on y’all thank you for everything that you have done
