### ISSUE TITLE
Scss nested namespaces error in vs-code.

### ISSUE THREAD

**Issue by okram69** [Microsoft/vscode#44147]
### Issue Type
Bug

### Description
Vs-Code highlight the nested css namespaces as errors:
For example:

.foo{
    margin: {
       left: 10px;
       right: 5px;
       bottom: 2px;
   }
}

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7400  @ 2.80GHz (2 x 2793)|
|Memory (System)|3.25GB (1.15GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-simpler-icons|dav|1.5.2
classic-asp|ili|0.0.2
classic-asp-html|jtj|0.1.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by RMacfarlane** [comment]
I haven't been able to repro 
![screen shot 2018-02-21 at 11 08 36 am](https://user-images.githubusercontent.com/3672607/36499936-96067442-16f7-11e8-9f97-3184668e22a9.png)
Does your file have the extension .scss? If it is just .css, the error is expected

**Comment by okram69** [comment]
Yes it does... but now I've seen were is the problem.
If you don't put a space between the colon and the open curly brace it fires the error.
It should't, am I wrong?

**Comment by RMacfarlane** [comment]
@aeschli Do you know if this space is required?

**Comment by aeschli** [comment]
It shouldn't matter if there is a space or not. Moving to https://github.com/atom/language-sass

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#249
