### ISSUE TITLE
Windows/Linux: Optionally disable the menu bar

### ISSUE THREAD

**Issue by SolarLiner** [Microsoft/vscode#44149]
### Issue Type
Feature Request

### Description

I very rarely use the menu bar in VS Code since all actions are either accessible via a button, shortcuts or the Command Palette. Since I can't get the nice global menu that was in Unity and features in macOS it just wastes space below the title bar.

My feature request is: add a setting to hide the menu bar, off by default.

I feel like I am not the only one who's keyboard-focused when working on code, and that would remove dead space.

Thanks!

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Ubuntu x64 Linux 4.13.0-32-lowlatency

**Comment by bpasero** [comment]
`window.menuBarVisibility`
