### ISSUE TITLE
Allow control over what extensions contribute to Problems list (and File Explorer)

### ISSUE THREAD

**Issue by thomthom** [Microsoft/vscode#44141]
I'm using a spell checker extension with VSCode with the intent of seeing the squiggly underlines in the editor for spelling issues.

However, these also get summarised under the Problems tab, and more recently they contribute to the error notation in the Folder view.

These warnings quickly gets noisy. I wish I could control which extensions contribute to these issue 
summaries. For spell checking I wish to see the squiggly underline in the editor, but not see them summarized elsewhere.

From what I can tell, my current options are either to disable the spell checker (not a solution) or disable the Folder view warnings (also not desirable as I want warnings from other sources.).

I originally filed a feature request with the extension itself: https://github.com/Jason-Rev/vscode-spell-checker/issues/186#issue-298956872

But I was told that it wasn't under the control of the extension and rather a feature of VSCode itself.

![image](https://user-images.githubusercontent.com/192418/36489576-aede9c7c-1726-11e8-8c46-20fe9ece2c92.png)

![image](https://user-images.githubusercontent.com/192418/36489579-b1a21b6e-1726-11e8-9cb7-f0b2d199de6f.png)

Is there any chance this could be made possible? Maybe a setting once can configure to disable certain providers for the Problems panel and Folder view warnings?

**Comment by jrieken** [comment]
I like.. Two option that I can think of: (1) we have a setting which spells out the extensions and the places in which they can show errors/warning or (2) we add a new property the diagnostics api to signal that a diagnostics is 'local', e.g only to be shown in the editor... I kind of prefer the latter but it needs buy-in from extension authors.

**Comment by thomthom** [comment]
I think both sounds like useful features;

(2) Is good to allow extension developers to provide sensible defaults. 
(1) Is good to allow the user to override the extension defaults when personal preference doesn't match with the developer's.

**Comment by jrieken** [comment]
Idea from #45436 is to show diagnostics with severity Hint only in the editor...

**Comment by thomthom** [comment]
So that would require the extension to update their diagnostics type to this new proposed type?

**Comment by jrieken** [comment]
The type isn't new, there already existed Error, Warning, Information, and Hint. Most extensions I have checked are already using Hint or Information, e.g. spell checkers, so it should be relatively smooth. First step will be not show Hint in the error panel nor the explorer.

**Comment by jrieken** [comment]
- [ ] only show errors/warnings maybe information? in the problems panel? @sandy081 
- [x] only show errors/warnings in explorer
- [x] only visit errors/warnings in F8
- [ ] adjust rendering for `Hint` in the editor (today we don't show a squiggle but the hover...)

**Comment by sandy081** [comment]
> only show errors/warnings/information? in the problems panel? @sandy081

Instead of not showing it completely, how about providing an option (check box) for showing types of problems. By default hints are deselected?

**Comment by jrieken** [comment]
Hm, unsure.... for information yeah but for hints I am unsure

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/44141#issuecomment-373026913 @DustinCampbell @stevencl how does VS show diagnostics with severity hint? Grey underline as @mjbvz suggests?

**Comment by sandy081** [comment]
Excluded `hints` from the Problems panel.

**Comment by jrieken** [comment]
ping @stevencl

**Comment by stevencl** [comment]
Sorry for the slow response. Here is an example. In the C# editor, I have a suggestion under this (the keyword is muted and there are three dots underneath).

![image](https://user-images.githubusercontent.com/1704059/37650052-b94e4c1a-2c2b-11e8-9ca7-bba699c1c2f2.png)

**Comment by jrieken** [comment]
Thanks

**Comment by alexandrudima** [comment]
@stevencl How does this look like for a large (real-life) piece of code? Is there an upper bound to the number of suggestions displayed? Is this the default experience in Visual Studio?

I am concerned that these suggestions might end up dominating the source code or interfering significantly with the source code coloring / presentation.

**Comment by jrieken** [comment]
Using a grey non-repeating squiggle 

<img width="335" alt="screen shot 2018-03-21 at 11 29 33" src="https://user-images.githubusercontent.com/1794099/37705108-30a1cccc-2cfb-11e8-81ac-0e528fd4cc3d.png">

**Comment by jrieken** [comment]
@mjbvz How will TypeScript use this? Will the whole document be full of severity hint diagnostics (basically for each and every applicable code action) or will TypeScript only use it for must-do code actions?

**Comment by stevencl** [comment]
Here is a completely made up, non real world example of a few suggestions in one method:
![image](https://user-images.githubusercontent.com/1704059/37705091-c6a8582a-2cf2-11e8-8827-12c5e54763b0.png)

Note that this is not the default experience - I changed a few settings so that it would offer suggestions for the likes of this. To get a better feel for it, go to the Tools Options in VS, choose Text editor, C#, Code Style, General and set the severity to Suggestion for a few styles.

I don`t know if there are any upper bounds.

**Comment by stevencl** [comment]
Note that in VS, there are 33 general style rules for C# that you can configure the editor to provide suggestions for. Of these, only 16 are set to provide a suggestion by default. The others aren't turned on.

**Comment by jrieken** [comment]
As discussed, using an ellipsis to show diagnostic severity hint. 


<img width="324" alt="screen shot 2018-03-23 at 13 26 54" src="https://user-images.githubusercontent.com/1794099/37829064-e136236e-2e9d-11e8-92c4-c971a32a9433.png">

**Comment by DustinCampbell** [comment]
Cool! cc @rchande

**Comment by jrieken** [comment]
@mjbvz see https://github.com/Microsoft/vscode/issues/44141#issuecomment-374895859, you might wanna add some config-settings for TypeScript/JavaScript suggestions

**Comment by thomthom** [comment]
Will there be further options to control what extensions contribute to the Problems/Explorer panel?

Asking because of this comment: https://github.com/Jason-Rev/vscode-spell-checker/issues/186#issuecomment-377597751

The poster used an insider version with the changes that hides Hints;

```
"cSpell.diagnosticLevel": "Hint",
```

That worked, but misspelled words then only have the `...` indicator in the editor instead of the desired squiggly lines;

![](https://user-images.githubusercontent.com/689204/38150015-f3c9d704-342a-11e8-88f5-ca75e01a1366.png)
