### ISSUE TITLE
Auto import does not work when last import is type import

### ISSUE THREAD

**Issue by thibmaek** [Microsoft/vscode#44150]
- VSCode Version: 1.20.1
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Have 2 imports where last import is a type import
2. Auto import from a file
3. Imports create syntax error

Does this issue occur when all extensions are disabled?: Yes

Before auto import:
```js
import * as SCREEN_IDS from '../../../config/screens/screenIds';
import type { TNavigationProps } from '../../navigation/NavigationHOC';
```

After auto import:
```js
import * as SCREEN_IDS from '../../../config/screens/screenIds';
import typeimport { SAVE } from '../../../config/screens/navigatorButtons';
 { TNavigationProps } from '../../navigation/NavigationHOC';
```

**Comment by mjbvz** [comment]
Type imports are a flow specific feature. Auto imports come from the TS/JS plugin so we don't offer built-in flow support

Try disabling auto imports by setting `"typescript.autoImportSuggestions.enabled": false`

**Comment by karlhorky** [comment]
For TypeScript it looks like this extension may be interesting (from a quick read through the features it seems like it supports types):

https://github.com/soates/Auto-Import
