### ISSUE TITLE
typescript: give access to outline spanes

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#44158]
Outline spans are the typescript server's abstraction for folding regions.
https://github.com/Microsoft/TypeScript/blob/70e9a5e6dc02e5eb01e8dac3e0235a096b4d232f/src/server/protocol.ts#L91

Can we add an accessor to use them on the client?

**Comment by mjbvz** [comment]
@aeschli Who needs access to the outline spans? Is this for the html extension or something else?

**Comment by aeschli** [comment]
I'm adding the capability for extensions to contribute folding ranges toallow syntax based folding. I'd like to hook up TS's outline spans with the new provider to validate this.

**Comment by aeschli** [comment]
See https://github.com/Microsoft/vscode/blob/fe352d0d38328068c7303b91f8d2b043331750cd/src/vs/vscode.proposed.d.ts#L419

**Comment by mjbvz** [comment]
Cool! I'll try scaffolding out something basic using that API this afternoon, mainly just adding the TS server call and type translation. Then you should be able to use that for validation

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/22133 to track TS work to expose `outliningSpans` as official API

dcf6559 adds a prototype implementation to vscode. Add `"typescript.enableExperimentalFolding": true` to your user settings and then restart VS Code to test it out

**Comment by aeschli** [comment]
@mjbvz Really cool, thanks!

**Comment by mjbvz** [comment]
Fixed by dcf6559.
