### ISSUE TITLE
Tweak undo behaviour when having commit characters

### ISSUE THREAD

**Issue by jVanZwieten** [microsoft/vscode#44155]
### Issue Type
Feature Request

### Description

The suggestions and suggestion widget of VSCode Intellisense is inaccessible to extension API. In order to capture the suggestion for later use, I must do the following:

        async function getSuggestion(): Promise<string>  {
            await vscode.commands.executeCommand('acceptSelectedSuggestion')

            const suggestionRange = document.getWordRangeAtPosition(editor.selection.active)
            const suggestion = editor.document.getText(suggestionRange)

            await vscode.commands.executeCommand('undo')
            return suggestion
        }

Which is silly, it should just be like:
`let suggestion = vscode.window.activeTextEditor.suggestionWidget.suggestion`

Furthermore, I can't check the type of suggestion. In my case, I'd like to defend against snippets and bypass my logic in that case.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T05:17:01.988Z)
OS version: Windows_NT x64 10.0.16299

**Comment by jrieken** [comment]
>  The suggestions and suggestion widget of VSCode Intellisense is inaccessible to extension API. In order to capture the suggestion for later use,

Yeah, that's the design of the API - define data contracts and interactions but don't mention the UI. This gives us freedom to redefine the UI without changing extensions and therefore it's unlikely this will happen any time soon. 

I wonder what you are trying to achieve and 'later use' is for? There might another way to achieve what you want. For instance a completion command could be used for this...

**Comment by jVanZwieten** [comment]
It's fair to abstract away the actual UI, but my suggestion is really not about the UI, it's about the auto-completion suggestions themselves. I want to identify the selectedSuggestion, for 2 reasons:
1. Save the suggestion to a variable, for later use
2. test if the suggestion is a snippet, method, property, etc, which of course I know VSCode knows because it has the different icons for each

In my case, I save the suggestion for later use in order to implement the accept and type character with an undo order like Visual Studio. That way the user can undo the accepted suggestion if they didn't want it, they actually wanted the key they typed (as in VS). You can see this at work in my [extension](https://github.com/jVanZwieten/punctual-intellisense). In order to get that 'proper' undo order, I have to type the accept character, and _then_ insert the suggestion, by which time VSCode's suggestion widget is no longer open.

Thanks for your consideration!

**Comment by jrieken** [comment]
> to implement the accept and type character with an undo order like Visual Studio

Hm... Isn't that very similar to the built-in feature of accept-characters? Check the `"editor.acceptSuggestionOnCommitCharacter": true`-setting and the [`CompletionItem#commitCharacters`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2983). Is there anything missing from the feature?

**Comment by jVanZwieten** [comment]
2 things missing from this feature:
1. It doesn't work the first time. I have to use `tab` for the first commit. So for example, if I were looking to type:
`vscode.window.activeTextEditor.suggestionWidget.suggestion`
I'd have to use `tab` to complete vscode, and the rest of the properties could be completed using `.`.
2. It gives the wrong undo order. Say I want to type `vscode.win.`, this would autocomplete to `vscode.window.`. As in VS, I should be able to immediately `undo` to get `vscode.win.` but instead I would get `vscode.window` since the `.` is on top of the undo stack.

**Comment by jrieken** [comment]
> vscode.window.activeTextEditor.suggestionWidget.suggestion
I'd have to use tab to complete vscode, and the rest of the properties could be completed using ..

@mjbvz This seems to be a bug in TypeScript/JavaScript

**Comment by jVanZwieten** [comment]
Hello,

Was there any information that was being waited on, or has this suggestion been rejected?

**Comment by jrieken** [comment]
Yeah, over-eager bot
