### ISSUE TITLE
Debugging Python code does not work

### ISSUE THREAD

**Issue by Joukahainen82** [Microsoft/vscode#44159]
### Issue Type
Bug

### Description

Just after downloading and installing the latest  update to VS Code I cannot debug my Python code. Everytime I get the message: 

Error
Debug adapter process has terminated unexpectedly

Before that last update debugging the same code ran fine. 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|7.80GB (1.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
django-snippets|bib|1.1.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
file-icons|fil|1.0.7
code-runner|for|0.8.7
vscode-csharp-snippets|jor|0.2.0
docomment|k--|0.0.17
MagicPython|mag|1.0.12
python|ms-|2018.1.0
csharp|ms-|1.14.0
vs-keybindings|ms-|0.1.7
vscode-icons|rob|7.20.0
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
jinja|who|0.0.8

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Does this problem still occur for you in the latest version?

**Comment by Tiancityrua** [comment]
This problem still occur for me in the latest version.I can't run any python code now!

**Comment by tsalinger** [comment]
Moved to the python repo. Please continue the discussion there: https://github.com/Microsoft/vscode-python/issues/1125

**Comment by Joukahainen82** [comment]
Strangely, for me the problem with debugging Python code had disappeard. Maybe it was some recent update I haven’t noticed but now it seems everything has got back to normal. 

Don’t know what you’ve done, guys, but it’s worked 😊 

Pete

Od: Tian
Wysłano: wtorek, 20 marca 2018 10:23
Do: Microsoft/vscode
DW: Joukahainen82; Author
Temat: Re: [Microsoft/vscode] Debugging Python code does not work (#44159)

This problem still occur for me in the latest version.I can't run any python code now!
