### ISSUE TITLE
ARM template variable copy block highlighting error

### ISSUE THREAD

**Issue by elentar** [Microsoft/vscode#44153]
### Issue Type
Bug

### Description

There is a syntax highlighting error in the azurerm-vscode-tools extension when editing ARM templates. In the following block in the variables section, the opening "copy": block is underlined green indicating that it is never used and all references to the name "generatedSecurityRules" are underlined red indicating that it is not defined. The template actually executes fine when run against the Azure API.

```
"copy": [
            {
                "name": "generatedSecurityRules",
                "count": "[length(parameters('appServiceRules'))]",
                "input": {
                    "name": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].name]",
                    "properties": {
                        "description": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].description]",
                        "protocol": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].protocol]",
                        "sourcePortRange": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].sourcePortRange]",
                        "destinationPortRange": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].destinationPortRange]",
                        "destinationPortRanges": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].destinationPortRanges]",
                        "sourceAddressPrefixes": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].sourceAddressPrefixes]",
                        "destinationAddressPrefixes": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].destinationAddressPrefixes]",
                        "access": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].access]",
                        "priority": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].priority]",
                        "direction": "[parameters('appServiceRules')[copyindex('generatedSecurityRules')].direction]"
                    }
                }
            }
        ],
        "securityRuleList": "[concat(variables('generatedSecurityRules'), parameters('denyInternetRule'))]"
```

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.69GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_3273503|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.5.1
team|ms-|1.122.0
azurerm-vscode-tools|msa|0.4.0

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
Since this is extensions specific, please open this issue on the extension itself: https://github.com/Microsoft/vscode-azurearmtools

Feel free to reopen this if you think the issue is with VS Code itself
