### ISSUE TITLE
AutoSave

### ISSUE THREAD

**Issue by sayeduzzamancuet** [Microsoft/vscode#44169]
### Issue Type
Bug

### Description

When I enable autosave feature, the cursor jumps to the end of the line automatically. This is very annoying and problematic. Please resolve this issue ASAP. Thank you.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

Reproduces only with extensions

**Comment by yume-chan** [comment]
Some poorly designed formatter extensions will cause this problem, because they just swapped the full content instead of applying small edits, so Code can not track your cursor position after a formatting.

Can you check your extensions or attach a list of your installed extensions?
