### ISSUE TITLE
Editor window becomes super-blurry

### ISSUE THREAD

**Issue by perryizgr8** [Microsoft/vscode#44168]
### Issue Type
Bug

### Description

Open VS code and maybe some other app. Don't interact with VS code for some time but don't put it in the background or minimize it. It becomes super blurry like the picture attached. If you bring it in focus then parts of the window will become sharp again. For example if I start typing in the editor the editor text will become sharp but other elements stay blurry until I mouse-over or click them.

In the attached picture, note how sharp the title bar is. That's how everything else looks. This issue doesn't seem to be related to monitor DPI or anything. It happens on my laptop (1600x900) and also on my external monitor (1600x1200). It happens when I have only my laptop screen, it happens when I have both displays enabled.

If I have the cursor blinking in a file, the text around the cursor remains sharp always. The blurriness starts a few lines above/below the current line. If I move the cursor everything becomes sharp again.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|Memory (System)|7.90GB (3.05GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0
cpptools|ms-|0.15.0

</details>
Reproduces without extensions
![screenshot 2018-02-22 09 13 46](https://user-images.githubusercontent.com/9302404/36519427-7d10bc9e-17b1-11e8-9950-c8accdbb6051.png)

**Comment by yume-chan** [comment]
![screenshot 2018-02-22 09 13 46](https://user-images.githubusercontent.com/9302404/36519427-7d10bc9e-17b1-11e8-9950-c8accdbb6051.png)

Fix the image link so you don't need to manually open it.

Seems it has been extremely upscaled.

**Comment by perryizgr8** [comment]
Thanks. As I noted before, the whole thing becomes sharp if I start interacting with it. That's why I don't think this is related to DPI/scaling at all.

**Comment by RMacfarlane** [comment]
A possible workaround suggested in a related issue is to run code with the `--disable-gpu` flag: https://github.com/Microsoft/vscode/issues/1896#issuecomment-269544361

**Comment by perryizgr8** [comment]
I tried `--disable-gpu` and it seems to fix the problem. Thanks!
