### ISSUE TITLE
Rename built-in JavaScript extension?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44166]
**Bug**
With #17068, the organization of our built-in extensions will now be exposed to users. The `JavaScript` extension's name is a confusing as this extension does not provide most of our javascript language support  (it instead comes from the `TypeScript` extension)

**Proposal**
- Move all JavaScript language and grammar code into the `TypeScript` extension, leaving just the `package.json` logic in the existing `javaScript` extension.

- Rename the remaining JavaScript extension to `packageJson` extension.

Any thoughts @dbaeumer?

**Comment by dbaeumer** [comment]
We had a discussion here today and to make things consistent with other languages we should have IMO two extensions:

- one that only contributes the grammars and snippets for both JS and TS
- one that brings the language smartness

This is for example what happens with all the other languages like C#, C++ where we only ship the grammar and the smartness comes with a second plugin.

However I have no idea how to name them. CCing @aeschli  since we discussed the same JSON, CSS, ... yesterday.

**Comment by mjbvz** [comment]
Ok, how about something like following then:

* Rename `typescript` to `TypeScript and JavaScript IDE`. Move syntax highlighting and snippets out of `typescript` to new `language basics` extension

* Move js/ts syntax and snippets to a new `TypeScript and JavaScript Language Basics` extension (or create two new "language basics" extension, one for JS and one for TS)

* Rename `javascript` to `Package.json Support`

**Comment by mjbvz** [comment]
8e0bdd6040ed9c2781e0ec6e68ad70adcbf68f5d  splits the package.json/bower specific logic out into a new `package-json` extension

**Comment by dbaeumer** [comment]
I like the split and the more explicit naming.

**Comment by aeschli** [comment]
@mjbvz Instead of a new `package-json` extension, lets use the `npm` extension

**Comment by mjbvz** [comment]
@aeschli Good idea.  ac5ed16 makes that change

e23c58b Creates a new `typescript-basics` extension which just has typescript syntax. I'll change the display name for the existing `typescript` extension to make it more clear that it is contributing intellisense

**Comment by aeschli** [comment]
@mjbvz Thinking aboud this more, I think it would cleaner use the id `vscode.typescript` for the basic language extensions, and use something like `vscode.typescript-language-service` (`vscode.typescript-language-support`) or for the language client.
`vscode.typescript` is what other extensions already use when they depend on the typescript language definition, and what they should continue to depend on, unless they extend the language service.
Also that way we stay consistent with the other language extension names.
I'll have to do the same for css and html.

**Comment by mjbvz** [comment]
@ramya-rao-a Will changing the built-in extension identifiers mess up telemetry?

**Comment by ramya-rao-a** [comment]
@mjbvz It's a mess that we can sort out. Folks looking at raw events will have to look for both old and new names. Our cooking jobs can be updated to consolidate both.
