### ISSUE TITLE
After update the Unity to Latest version,I cannot use the IntelliSense.

### ISSUE THREAD

**Issue by zhe13** [Microsoft/vscode#4416]
- VSCode Version:0.10.11 (0.10.11)
- OS Version:OS X 10.11.3
- Unity Version:5.3.4f1

I am sure that I am not faced with the OmniSharp problem cause my Code tells me it is running  with the x-sharp.sln.And I have update the vscode-unity plugin.
I can not get any of them -- Syntax Highlighting or Bracket matching or IntelliSense.

I have update home-brew and reinstall the mono.
How can I do next?

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#108
