### ISSUE TITLE
Post install fails behind a proxy

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#44160]
_From @tebeco on February 21, 2018 21:20_

Hello,
I just installed / reloaded and used VsLiveShare on a personnal computer
Seems fine 
The installation experience looks like this :
![normal_installation](https://user-images.githubusercontent.com/2266487/36505511-1202dbec-1754-11e8-9185-829415366f2a.gif)

Tried the same on a computer behind an NTLM Proxy + Firewall
![image](https://user-images.githubusercontent.com/2266487/36505726-abf618cc-1754-11e8-8637-09e080e4cc14.png)
The adventure stop there.
I got an error just after with a small segment of the URL trying to be reached but it tells it cannot download the package

* I have a windows proxy in OS Settings
* I have a proxy settings in VsCode that Extensions uses (like OmniSharp for updates)
* I cannot tried to manually download to check if it is a Firewall issue or Proxy issue since the log does not output full url

## Personnal Touch :
VsCode does not provide something like HttpClient PRE-CONFIGURED with the OS proxy settings.
VsCode Manage to use the proxy to Self update (from OS Settings), but can pre configure proxy for extensions. Having to set my password in clear in VsCode is not funny and i cannot guess who actually access.
This would solve this specific kind of annoying issue for Extension Developper

_Copied from original issue: Microsoft/vscode-docs#1450_

**Comment by gregvanl** [comment]
Hi @tebeco If you have already looked at https://code.visualstudio.com/docs/setup/network#_proxy-server-support and that information didn't help, then I don't think this is a VS Code documentation issue. I'll move this issue to the vscode product repo.

**Comment by joaomoreno** [comment]
Unfortunately we do not have a good extension proxy support: #12588

**Comment by vicpara** [comment]
Terminate Visual Studio Code , go in terminal and run `code  --ignore-certificate-errors` to start it ignoring ssl certificates. This solved my problem.
