### ISSUE TITLE
Extensions can't get through corporate proxy

### ISSUE THREAD

**Issue by adriantorrie** [Microsoft/vscode#44163]
Issue Type: Bug

I can install extensions fine from within VSCode, so it seems the application respects the `HTTP_PROXY` and `HTTPS_PROXY` env vars I have set for my user (Windows 7, domain user, on a domain).

However, all extensions that require "Login" or "Sign In" can't do so (which require https connections)

Guessing the extensions are blocked from reading the `HTTP_PROXY` and `HTTPS_PROXY` env vars?!

Here is one example of blocking that I've raised an issue with the extension repo:
https://github.com/Microsoft/vscode-azure-account/issues/27

However, given that this behaviour is happening across extensions, it leads me to believe  the VS Code app is the cause, and not the extensions themselves.

I have tried using version `2018.02` and the current Insiders build without any luck. Running from the command line doesn't change anything either. 

VS Code version: Code - Insiders 1.21.0-insider (efa33330fb0ab23b022bdff125311bdb21494b71, 2018-02-21T09:22:14.399Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2693)|
|Memory (System)|7.88GB (1.57GB free)|
|Process Arg

**Comment by joaomoreno** [comment]
#12588

**Comment by vicpara** [comment]
Terminate Visual Studio Code , go in terminal and run `code  --ignore-certificate-errors` to start it ignoring ssl certificates. This solved my problem.
