### ISSUE TITLE
compiled a.exe is not launching 

### ISSUE THREAD

**Issue by SPK-RPI** [Microsoft/vscode#44178]
### Issue Type
Bug

### Description

my root folder is in onedrive i have compiled a programe in c++ the generated a.exe file was launching in debugger before until now.the programe is running when i run outside vs code but not in it.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|Memory (System)|5.95GB (2.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-phpfmt|kok|1.0.18
vscode-JS-CSS-HTML-formatter|lon|0.2.3
cpptools|ms-|0.15.0

</details>
Reproduces only with extensions

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#1601
