### ISSUE TITLE
Mr Peter

### ISSUE THREAD

**Issue by Zeets** [Microsoft/vscode#44170]
![glitch](https://user-images.githubusercontent.com/16219758/36519919-2147f220-17c9-11e8-925a-deaeb66ed568.jpg)
### Issue Type
Bug

### Description

x syntax error, unexpected end of file

VS code is continuously showing this error when there is no code on the line.
It is a small red squiggle that shows under "problems"

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q9650  @ 3.00GHz (4 x 2999)|
|Memory (System)|4.00GB (0.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by roblourens** [comment]
Could you upload the full text of the file so I can try?
