### ISSUE TITLE
Bug? Editor text selection disappearing

### ISSUE THREAD

**Issue by martinandersen3d** [Microsoft/vscode#44186]
[Vscode - output - log.pdf](https://github.com/Microsoft/vscode/files/1747189/Vscode.-.output.-.log.pdf)
[vscode console.pdf](https://github.com/Microsoft/vscode/files/1747190/vscode.console.pdf)

- my editor text selection disappearing - See Gif.

- If i reboot vscode, everything works normal. But after some time it comes back. It is both mouse and keyboard selection.

- all the text in the gif where selected with mouse, draggin from bottom to top, but the selection inside the bracket is not showing up :( It might only be a bug related inside brackets [ ], but not on paranthese () and curlybrackets { }.
[vscode console.pdf](https://github.com/Microsoft/vscode/files/1747155/vscode.console.pdf)

- VSCode Version:
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
winindows 10 - ver 1709

Steps to Reproduce:
![gif](https://user-images.githubusercontent.com/19984581/36527858-79b75808-17b3-11e8-8493-518ab7ca9fb1.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
Does this happen when you run VSCode with `--disable-extensions`?
