### ISSUE TITLE
Quick open cant find all the files in the project

### ISSUE THREAD

**Issue by Froggi** [Microsoft/vscode#44183]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 17.10 (Kubuntu)

Steps to Reproduce:

1. Open Quick-open with CTRL+P
2. Search for a file who has not been open for a while
3. File is not found

I have a large code base with a lot of files.
This command "find . -type f | wc -l" say I have 94687 files. (Probably some node_modules files there)

Everyting worked perfectly until a few months ago, I'm guessing around november/december. I love the Quick open-functionality and hate that I have to go find the files in the browser now instead.

**Comment by Espyo** [comment]
Are you using git? Are the files that you cannot find modified in your working directory? Over here, quick open cannot find files that have been modified in my git working directory, unless I've open them manually, in which case they do appear, though under the "recently opened" category.

In my case, setting the option `search.useRipgrep` to false has also fixed the issue.

**Comment by roblourens** [comment]
> Over here, quick open cannot find files that have been modified in my git working directory

Please open a new issue @Espyo 

@Froggi can you do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by Froggi** [comment]
@roblourens 
I did what you asked. I did a search on "warx". There is a file called "WArxListener.php" in folder "wondr-workspace/wondr/app/Plugin/WArx/Lib/Event/".

Search results came up empty.

![image](https://user-images.githubusercontent.com/4819941/37079826-42b54442-21e4-11e8-84fc-302b495ebd87.png)

**Comment by roblourens** [comment]
I'm looking for the line after that which shows how we invoked ripgrep. Also whether there are any errors.

**Comment by Froggi** [comment]
Do you mean this line?

> [2018-03-07 18:53:47.486] [renderer1] [debug] SearchService#search rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' -g '!/wondr-docker' --no-ignore-parent --follow -- '.'
>  - cwd: /home/marcus/Dokument/Work/wondr-workspace
>  - Sibling clauses: {}

No errors that I can see.

**Comment by roblourens** [comment]
Does it work in other folders?

**Comment by Froggi** [comment]
I cant really find a pattern to what works and what doesnt work. My workspace has a few different main folders, and same problem in all of them. Mostly files I opened recently are found, but some others too.

I did add this line now in my settings as suggested by @Espyo.
"search.useRipgrep": false

And now the search works perfectly. Can it be some bug in ripgrep?

**Comment by roblourens** [comment]
Are the missing files covered by a gitignore file?

**Comment by Froggi** [comment]
No they are not. The files are tracked by git at all times.

**Comment by roblourens** [comment]
Sorry for dropping this @Froggi is it still an issue? Can you try in the latest release?
