### ISSUE TITLE
Extension viewlet scrolls when navigating with tab

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44181]
Steps to Reproduce:

1. have a list with elements inside that have a tab index
2. navigate to an item that is only partially visible

=> you can end up in a very bad state where the height of the list is no longer proper

![before](https://user-images.githubusercontent.com/900690/36524714-53a5b562-17a7-11e8-9668-6b939317dc99.gif)

**Comment by bpasero** [comment]
@joaomoreno another related issue is that the order of DOM elements in the list is not the same order as visible, so that navigation with tab key yields unexpected results. Would it be possible to add a setting to have DOM elements in order? I do not expect a lot of notifications to show up, so I would tolerate a degrade in performance there.

**Comment by joaomoreno** [comment]
@bpasero The bug is not in the list. Some element above the parent chain allows the scrolling to happen. We saw the very same thing yesterday in the notifications box.

![screen shot 2018-02-22 at 08 55 26](https://user-images.githubusercontent.com/22350/36526355-3b592a8c-17ae-11e8-98b5-5da1768761ec.png)

Maybe file another issue for the order?

**Comment by joaomoreno** [comment]
There were two fixes here:

- Remove the `height: auto`, introduced by @ramya-rao-a; make sure removing it doesn't break anything. The height of the list always needs to fill its container: `100%`.
- Prevent the `monaco-scrollable-element` from scrolling itself (it changes its own `scrollTop` property when navigating to hidden focusable elements) by resetting `scrollTop` to 0. @alexandrudima should this always be the case for the `ScrollableElement` class?

**Comment by bpasero** [comment]
@joaomoreno I created https://github.com/Microsoft/vscode/issues/44193 for the keyboard accessibility issue.

What is left for me to adopt to get this fix for the notifications? I guess some option to dock list items to the bottom instead of to the top?

**Comment by joaomoreno** [comment]
Yeah, sounds about right!

**Comment by alexandrudima** [comment]
@joaomoreno Yeah, this would happen when not scrolling using the regular `scrollTop`... 

Browsers try to desperately reveal elements that gain focus... `scrollTop` could be changed for any element in the parent hierarchy for the element which gains focus, until the focused element is no longer occluded. 

Here is my version of your listener: https://github.com/Microsoft/vscode/blob/93045738c3112e9b914581b038192b2cb3d4a453/src/vs/editor/browser/viewParts/editorScrollbar/editorScrollbar.ts#L87
