### ISSUE TITLE
Unimportant notifications should not need to draw attention from status bar

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#44185]
_Feedback to Improved notification UX #22388_

If I ignore non-important notifications and they go away after some time, I'd prefer if they didn't draw my attention from the status bar. For example, I invoke Check for Updates and get this notification:

![image](https://user-images.githubusercontent.com/101152/36527292-a0d75d5e-17b1-11e8-9d02-2cb34b6297b0.png)

Ok, nothing new, I continue working and the toast goes away after a while. However, I still see the notification notification (sic!) in the status bar:

![image](https://user-images.githubusercontent.com/101152/36527524-5eb8662e-17b2-11e8-9f6a-e7206a15568e.png)

To get rid of this, I need to click the icon and manually dismiss the info message. Maybe these unimportant notifications could go away entirely, or be in the notification center but without the alert in the status bar?

## Version info

Version 1.21.0-insider
Commit efa33330fb0ab23b022bdff125311bdb21494b71
Date 2018-02-21T09:22:14.399Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by yume-chan** [comment]
As opposite, I'd like to check all notifications no matter how important you think it is.

But I think it's too wide (too much space) and difficult to locate the small close button.

**Comment by borekb** [comment]
You can always check all notification via a command, and there is also "clear all", all I'd like to see is drawing less attention from the status bar if there is nothing important to deal with, like in the example above. I think that the "alert" icon should be reserved for notifications that actually require some attention.
