### ISSUE TITLE
Support relative paths as title variable

### ISSUE THREAD

**Issue by wellshsu** [Microsoft/vscode#44180]
Lua language src folder is embedded in project folder in many cases, such as:
[Unity]
![image](https://user-images.githubusercontent.com/27855350/36523735-fb5da2b6-17dd-11e8-8547-b8112d0330b2.png)

[Cocos]
![image](https://user-images.githubusercontent.com/27855350/36523916-df08c0fe-17de-11e8-9006-ae00ef90c49e.png)

As you see, if you have many same structure projects, then you really can not recognize this project by 
![image](https://user-images.githubusercontent.com/27855350/36524307-8302944a-17e0-11e8-85e8-c92d12f835ec.png)

So wish you guys could support relative path as window title, like
![image](https://user-images.githubusercontent.com/27855350/36524507-2f954cd4-17e1-11e8-823b-fd85c6ee5513.png)

Thanks a lot!

**Comment by bpasero** [comment]
@wellshsu can you try with the `activeEditorMedium` variable? That should be the relative path.

**Comment by wellshsu** [comment]
I've tried but 'activeEditorMedium' means file's relative path to workspaceFolder, it's not expected.
![image](https://user-images.githubusercontent.com/27855350/36525483-34d62bba-17e5-11e8-9c09-bea131b32608.png)
Here is what i expect:
Full Path: 'Zixi\Assets\Scripts\Lua'
WorkspaceRoot: 'Lua'
Display: Core.lua - Zixi - Visual Studio Code
Not: Core.lua - Lua - Visual Studio Code

Could you please give me an example, thanks.

**Comment by bpasero** [comment]
@wellshsu so you only want to see the workspace folder name?

**Comment by wellshsu** [comment]
yes.

**Comment by bpasero** [comment]
@wellshsu how about `{folderName}` then?

**Comment by wellshsu** [comment]
@bpasero if use folderName, the title will be 'Lua', same with current, but i want it be 'Zixi', full path is 
'Zixi\Assets\Scripts\Lua', and workspace is 'Lua'.Sorry for my bad expression😂

**Comment by bpasero** [comment]
@wellshsu so you want the name of the first folder in your absolute path?
