### ISSUE TITLE
closeActiveEditor doesn't consider "when" conditions

### ISSUE THREAD

**Issue by peppy** [Microsoft/vscode#44184]
Issue Type: Bug

- Add key binding config such as:
```
    {
        "key": "w",
        "command": "workbench.action.closeActiveEditor",
        "when": "textCompareEditorVisible && editorTextFocus"
    },
```
- Note that the "when" condition is ignored and it will always close the editor.

VS Code version: Code - Insiders 1.21.0-insider (efa33330fb0ab23b022bdff125311bdb21494b71, 2018-02-21T09:13:22.723Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|Load (avg)|5, 4, 4|
|Memory (System)|64.00GB (15.41GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_4420663|
|Screen Reader|no|
|VM|9%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
code-settings-sync|Sha|2.8.7
supersharp|cra|0.1.4
gitlens|eam|8.0.2
file-icons|fil|1.0.7
csharpextensions|jch|1.3.0
docomment|k--|0.0.17
csharp|ms-|1.14.0
mono-debug|ms-|0.15.8
vscode-paste-image|mus|0.9.5
snippet-creator|nik|0.0.4
subtle-brackets|raf|2.1.0
code-spell-checker|str|1.6.3

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by usernamehw** [comment]
Duplicate of #35225 ?

**Comment by peppy** [comment]
So it is. Search was of no help this time. Thanks!
