### ISSUE TITLE
List: row order does not match visual order which makes keyboard accessibility hard

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44193]
The list widget puts the rows not in the visual order into the DOM which makes keyboard accessibility using tab hard because for that elements have to be in order as they appear visually.

Maybe we could have a setting to disable this and have elements in order? The notifications list would benefit from this.

**Comment by joaomoreno** [comment]
Yeah we can attempt to solve this.

**Comment by joaomoreno** [comment]
Repro steps: in the extension viewlet, collapse the installed extensions view to a minimum, scroll all the way down, then _slowly_ all the way up. If you <kbd>Tab</kbd> into an action, it should always pick the first one.

Here's before:

![bad](https://user-images.githubusercontent.com/22350/36546820-a89b4d58-17ec-11e8-9809-b123581c4c0f.gif)

And after:

![good](https://user-images.githubusercontent.com/22350/36546841-b36c2e82-17ec-11e8-9c26-794717996796.gif)
