### ISSUE TITLE
Git spam in output log

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#44194]
I have a workspace open with two folders. Both of them are sub-folders of a git repro (so neither have a `.git` folder themselves, but 3-4 levels up the tree they do). My output window is frequently writing this:

```
git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
```

Sometimes it has extra lines with paths (they seem to start with colons - that colon is actually where the git repo root is):

```text
git rev-parse --show-toplevel
git show :pkg/analysis_server/test/services/correction/assist_test.dart
fatal: Not a git repository (or any of the parent directories): .git

git check-ignore -z --stdin
git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

git show :pkg/analysis_server/test/services/completion/dart/override_contributor_test.dart
git check-ignore -z --stdin
git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

git show :pkg/analysis_server/test/services/correction/assist_test.dart
```

Let me know if I can get more info to help debug.

**Comment by DanTup** [comment]
This seems to be the same as #43753 but I understand the response (why it's expected)?

**Comment by joaomoreno** [comment]
@DanTup Is there some feature which doesn't work? The output pane is there to know which commands are run. It is useful to trace stuff which doesn't work.

**Comment by DanTup** [comment]
@joaomoreno I haven't noticed anything not working, but since the message makes no sense (it in inside a Git repo) it makes me think something might not be functioning correctly?

**Comment by joaomoreno** [comment]
Do you have any other folder in your workspace?

**Comment by joaomoreno** [comment]
You can use [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to trace those `git rev-parse` calls and see what CWD it uses.

**Comment by DanTup** [comment]
@joaomoreno Aha! I had a text file open that's outside of the repo. Closing that has caused the messages to stop.

Should it be doing Git operations on open files that aren't in a workspace folder? (would they show in the Git pane?)

**Comment by joaomoreno** [comment]
Yeah, if a user opens a file within a repo, we show that repo in the SCM view.

**Comment by DanTup** [comment]
All makes sense, cheers!
