### ISSUE TITLE
Feature request: selectable in diff result

### ISSUE THREAD

**Issue by Too-Naive** [Microsoft/vscode#44199]
![](https://user-images.githubusercontent.com/16496671/36538734-7f892f48-180f-11e8-8723-c2a5aaa18e92.png)
I do not really like to re-type once I deleted but I still need something. I just like to copy and paste, can I change it like _Submit Text_ that can be modified?

**Comment by RMacfarlane** [comment]
Do you mean the diff view under source control? I'm able to copy and paste there. 
![diff view](https://user-images.githubusercontent.com/3672607/36556587-932dc522-17ba-11e8-8e69-f1f892a204b0.gif)
Or is this a different view?

**Comment by Too-Naive** [comment]
By click `git diff` field. I can select the things which I have added, but cannot select the deleted things.
