### ISSUE TITLE
Wrong syntax highlighting for TypeScript

### ISSUE THREAD

**Issue by boris-kolar** [Microsoft/vscode#44190]
- VSCode Version: 1.20.1
- OS Version: Ubuntu Desktop 17.10

Steps to Reproduce:

1. This code produces wrong color for the second "static" member (and more).
```ts
class Foo {
    static a(): void {
        let foo = true ? new String : ""
    }

    static b(): void {
        // wrong
    }
}
```

2. Comment the line `let foo = true ? new String : ""` and highlighting will be correct again

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#573
