### ISSUE TITLE
Misplaced Spell checker indicator

### ISSUE THREAD

**Issue by TheZoker** [Microsoft/vscode#44195]
Issue Type: Bug

First I thought it is a extensions issue, but after talking to the dev, he told me that this is a general issue in vceditor and I should report it. 
(Ref: https://github.com/Jason-Rev/vscode-spell-checker/issues/184)

![screenshot_2018 02 17_20h51m09s_002_](https://user-images.githubusercontent.com/1368405/36345055-6fb5c480-1424-11e8-9698-64dfb5c48dee.png)

The indicator should be above the word and not at the beginning of the line

VS Code version: Code - Insiders 1.21.0-insider (efa33330fb0ab23b022bdff125311bdb21494b71, 2018-02-21T09:22:14.399Z)
OS version: Windows_NT x64 10.0.17025

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|31.87GB (21.32GB free)|
|Process Argv|P:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.24.0
bracket-pair-colorizer|Coe|0.10.14
vscode-svgviewer|css|1.4.3
githistory|don|0.4.0
gitlens|eam|8.0.2
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|1.4.2
php-debug|fel|1.12.1
php-intellisense|fel|2.2.8
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
wordpress|hri|1.0.1
vscode-simple-icons|Lau|1.8.2
sftp|lix|1.0.4
code-beautifier|mic|1.7.2
easy-less|mrc|1.4.5
python|ms-|2018.1.0
debugger-for-chrome|msj|4.1.0
material-icon-theme|PKi|3.2.3
LiveServer|rit|3.2.1
code-settings-sync|Sha|2.8.7
code-spell-checker|str|1.6.3
code-spell-checker-german|str|0.1.2
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
> The indicator should be above the word and not at the beginning of the line

It goes above if there (white-)space. In your sample there no space anywhere (above, below, infront) and we pick the nearest I guess.

**Comment by TheZoker** [comment]
I checkout out, how it's done in intelij and they place the indicator also at the beginning of the line. 

But what they do different (and that's the important part): 
They allow pressing ALT+Enter and then the context menu is directly placed on top of the typo:
![screenshot_2018 02 26_13h03m59s_001_](https://user-images.githubusercontent.com/1368405/36669589-ad8f1de2-1af5-11e8-8eec-a7639db84b94.png)

Is there anything like ALT+Enter within vscode, that shows me the "issue dropdown" right on top of the actual issue?

**Comment by jrieken** [comment]
> Is there anything like ALT+Enter within vscode, that shows me the "issue dropdown" right on top of the actual issue?

Yeah, it's `cmd+.` for us

**Comment by jrieken** [comment]
Closing because we don't plan a code change here
