### ISSUE TITLE
Syntax Highlighting broken for multiline template strings

### ISSUE THREAD

**Issue by MelvIsntNormal** [Microsoft/vscode#44198]
Issue Type: Bug

Paste this code into a file with TypeScript syntax highlighting:

```typescript
function runQuery() {
    const query = createQuery<[number[]], Table<Columns>>(`
        some SQL here
    `)
    return database.execute(query)
}
```

Everything after the closing tick will be highlighted incorrectly. The issue is not present when the square brackets in front of `number` is omitted, or when `createQuery` is replaced with `new Query`. Interestingly, this doesn't work on GitHub either.

VS Code version: Code - Insiders 1.21.0-insider (efa33330fb0ab23b022bdff125311bdb21494b71, 2018-02-21T12:39:21.366Z)
OS version: Linux x64 4.15.3-2-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2606)|
|Load (avg)|4, 4, 4|
|Memory (System)|15.57GB (0.74GB free)|
|Process Argv|/opt/visual-studio-code-insiders/code-insiders|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-hie-server|ala|0.0.8
better-toml|bun|0.3.2
pgsql|dou|0.1.0
gitlens|eam|8.0.2
prettier-vscode|esb|1.1.3
vscode-ebnf|igo|1.0.3
language-haskell|jus|2.4.0
vscode-code-outline|pat|0.0.13
rust|rus|0.3.2
elm|sbr|0.16.0
code-spell-checker|str|1.6.3

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#575
