### ISSUE TITLE
Terminal sends the same lines twice

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#44192]
See https://github.com/Microsoft/vscode/issues/44018 for the discussion and the consequences.

To reproduce:

- install tsc 2.7.2
- create new folder
- change to folder
- tsc --init
- open VS Code
- create a HelloWorlds.ts
- Run Task > pick the watch task
- have auto save one
- change the HelloWorld.ts a couple of times. At some point the Building... in the status line doesn't disappear anymore.

The underlying reason is that the terminal sends lines twice confusing the tracking of the task output. 

<img width="899" alt="capture" src="https://user-images.githubusercontent.com/1931590/36532872-369fb1c8-17c2-11e8-9d12-7a7c16ab2fbf.png">

As you can see in the above screen shot the FIle change detected line at 11:13:12 is send twice resulting in the task to assume that two builds have started but only one compilation complete is send hence the building is kept.

**Comment by dbaeumer** [comment]
@Tyriar can you please have a look. This results in a regression with the tasks when using tsc 2.7.x which introduced clearing the terminal when a new compile run triggered through a file change starts.

**Comment by dbaeumer** [comment]
I tried to debug this but when debugging it doesn't reproduce. I was only able to track this down by adding console.log statements here https://github.com/Microsoft/vscode/blob/master/src\vs\workbench\parts\tasks\electron-browser\terminalTaskSystem.ts#L263

**Comment by dbaeumer** [comment]
@Tyriar can you please comment. IMO we need to address at least the original bug (even if we introduce some work arounds) for this milestone. It is a bad user experience.

**Comment by Tyriar** [comment]
I'm not really understanding why the problem matcher system doesn't handle this as the events are still being fired in order, just sometimes they can be duplicated? 

When the problem case happens, `tryBegin` and `tryFinish` are being called correctly, just `tryBegin` is being triggered twice. I would expect the second tryBegin to either be ignored or reset the current run.

**Comment by Tyriar** [comment]
Looking into it deeper, I'm assuming this is to allow problems to be matched on things like gulp tasks which can have multiple differenthave several tasks.

**Comment by dbaeumer** [comment]
@Tyriar I agree that we can prevent this in the problem matcher but shouldn't the terminal not send the lines twice. Or is the tsc compiler issuing them twice. 

I though that this would be better fixed in the terminal since others listen `onData` might be affected by this as well.

**Comment by dbaeumer** [comment]
Actually this is more complicated. It is not that the two identical lines come right after each other. There can be any blank lines in between as well and I am actually concerned that if the output contains errors they might interleave with the begin end as well. So deduping them might get more complicated on the matcher side.

**Comment by dbaeumer** [comment]
I releases a work around in the problem collector however that meant to capture quite some state.

**Comment by dbaeumer** [comment]
Closing. Dups #44018
