### ISSUE TITLE
German Keyboard - Shortcut Shift+Cmd+P not working

### ISSUE THREAD

**Issue by fabianhenzler** [Microsoft/vscode#44209]
### Issue Type
Bug

### Description

Hi,
the shortcut Shift+Cmd+P is not working on any of my macs :(

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (11.93GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.16
vscode-eslint|dba|1.4.6
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
debugger-for-chrome|msj|4.1.0
color-highlight|nau|2.3.0
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0
markdown-all-in-one|yzh|1.0.5

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment]
@fabianhenzler 

Does the keypress <kbd>shift</kbd>+<kbd>cmd</kbd>+<kbd>p</kbd> arrive in VSCode:

What does VS Code detect when you press the desired key combination? 
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by fabianhenzler** [comment]
I'm pressing "Shift+Cmd+P" but it's just not executed. It never arrives anywhere in macOS. "Shift+Cmd+B" or something works.

![vscode](https://user-images.githubusercontent.com/1168345/36778361-cd303a50-1c6c-11e8-9e71-1436c097c20e.gif)

**Comment by alexandrudima** [comment]
@fabianhenzler Here are some reasons why this would happen:
1. (most likely) you have a program running that eats up this keybinding. 
2. (less likely) you have configured a keyboard shortcut in the OS.
3. (least likely) your keyboard is broken and this key combination is not registered.

I will close for now, as there is nothing to do here for us.
