### ISSUE TITLE
Opennin files directly from an .zip file

### ISSUE THREAD

**Issue by maub55** [Microsoft/vscode#44207]
- VSCode Version: 1.20.1
- OS Version: Windows 7 Professional Service Pack 1

Steps to Reproduce:

1. Open Visual Studio Code
2. Open an .zip file (just double click, without extracting the content) and try to open some text file (i've tried .config and .sql), the file will open and close.
     2.a. If the VSCode is not open when you do that it works fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@maub55 try with `"workbench.editor.closeOnFileDelete": false`

**Comment by maub55** [comment]
The suggestion solved the problem.
