### ISSUE TITLE
Error parsing perl syntax: regex match with 'm' modifier

### ISSUE THREAD

**Issue by NorthboundTrain** [Microsoft/vscode#44204]
### Issue Type
Bug

### Description

1. open new editor window
2. switch to Perl mode
3. paste in the following syntax:

```
$foo =~ m/ff/i;
print "$foo is the name of the game\n";

$foo =~ m/ff/m;
print "$foo is the name of the game\n";

$foo =~ m{ff}i;
print "$foo is the name of the game\n";

$foo =~ m{ff}m;
print "$foo is the name of the game\n";
```
4. the code is formatted incorrectly; the trailing 'm' modifier in the regex match is not recognized and is therefor not end the regex formatting.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (2.25GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
code-settings-sync|Sha|2.8.7
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
project-manager|ale|0.24.0
vscode-simpler-icons|dav|1.5.2
permute-lines|ear|0.0.2
macros|ged|1.2.1
vsc-space-block-jumper|jmf|1.2.2
printcode|nob|2.0.4
remote-vscode|raf|1.1.0
rehydrate|Lla|0.0.1
vscode-dired|rru|0.0.4
vscode-workspace-switcher|sad|1.5.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by aeschli** [comment]
This issue was moved to textmate/perl.tmbundle#30
