### ISSUE TITLE
Inform when syntax highlighting or word wrap is turned off for large files

### ISSUE THREAD

**Issue by asjJRAutomation** [Microsoft/vscode#44206]
### Issue Type
Bug

### Description

Any XML-based file with a non-xml extension has no syntax highlighting, even if the Language Mode is set to XML. After changing the file extension to .xml without changing any file contents, syntax highlighting works correctly.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2904)|
|Memory (System)|31.94GB (14.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Source\JR\Personal\JR.CadTools\bin\Release\Deployment\product.wxs|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by RMacfarlane** [comment]
What extension did the file previously have before you changed it to .xml? Syntax highlighting for xml is being applied when a file has one of these extensions:
```
".xml",".xsd",".ascx",".atom",".axml",".bpmn",".config",".cpt",".csl",".csproj",".csproj.user",".dita",".ditamap",".dtd",".dtml",".fsproj",".fxml",".iml",".isml",".jmx",".launch",".menu",".mxml",".nuspec",".opml",".owl",".proj",".props",".pt",".publishsettings",".pubxml",".pubxml.user",".rdf",".rng",".rss",".shproj",".storyboard",".svg",".targets",".tld",".tmx",".vbproj",".vbproj.user",".vcxproj",".vcxproj.filters",".wsdl",".wxi",".wxl",".wxs",".xaml",".xbl",".xib",".xlf",".xliff",".xpdl",".xul",".xoml"
```
or the first line matches `(\\<\\?xml.*)|(\\<svg)|(\\<\\!doctype\\s+svg)`

**Comment by asjJRAutomation** [comment]
The extension is .wxs (WiX Installer XML), so it doesn’t match the predefined extensions.

The first line in the file is a standard XML declaration with encoding.
<?xml version="1.0" encoding="utf-8"?>

**Comment by asjJRAutomation** [comment]
I didn’t read the list close enough.. I guess it does have a match in the list, and the first line is valid as well.

From: Andrew Johnson
Sent: Thursday, February 22, 2018 6:18 PM
To: 'Microsoft/vscode' <reply@reply.github.com>; Microsoft/vscode <vscode@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Microsoft/vscode] XML Syntax Highlighting (#44206)

The extension is .wxs (WiX Installer XML), so it doesn’t match the predefined extensions.

The first line in the file is a standard XML declaration with encoding.
<?xml version="1.0" encoding="utf-8"?>

**Comment by aeschli** [comment]
That's strange: `.wxs` is already in the list of files associated to the `xml` mode.
So this just works for me:
- create a file `foo.wxs` with content `<abc></abc>`
- Open in VSCode. Editor mode shows XML, syntax highlighting works.

This also works for me:
- create file `foo.wxs1` with content `<abc></abc>`
- open in VSCode. Editor shows mode 'Plain text'
- switch mode to 'XML`. XML syntax highlighting works.

- create file `foo.wxs2` with content `<?xml version="1.0" encoding="utf-8"?><abc></abc>`
- open in VSCode. Editor shows mode 'XML'. XML syntax highlighting works.

@asjJRAutomation Can you give your steps? Please verify that no other extension redefines the XML mode.

**Comment by asjJRAutomation** [comment]
I originally thought I was having a problem with many files, but now I'm only able to recreate the problem with a particular file. The file I'm having an issue with is a .wxs file that was generated by the WiX heat.exe application. It generates a .wxs file from input files. I've attached the file (with a .txt extension, GitHub would not allow upload of .wxs)

It is a very large file (20MB). Maybe the file size is the issue?

[product.wxs.txt](https://github.com/Microsoft/vscode/files/1771449/product.wxs.txt)

**Comment by aeschli** [comment]
Oh, yes, there's a 20MB limit where tokenization will be disabled.
@alexandrudima We need to to at least print a warning to the console, even better some kind of notification to the users.

**Comment by alexandrudima** [comment]
Yes, now that notifications are not so invasive, we could add a passive notification informing about this, and also about the case of a very long line...

**Comment by alexandrudima** [comment]
To verify, try opening a very large file.
