### ISSUE TITLE
Dns behind a corporate proxy

### ISSUE THREAD

**Issue by Pingudiem** [Microsoft/vscode#44213]
- VSCode Version: 1.20.1
- OS Version: Linux Ubunut 16.04

When I run a script inside the integrated terminal I get a DNS Fail error:
```
Failure: The name server was unable to process this query. This means that the cache was not able to resolve the hostname presented in the URL. Check if the address is correct.
 <!-- ERR_DNS_FAIL -->
```

When I am running the same script, with the same kind of terminal outside of vsc the script works like a charm.

i have setup all proxy settings in vsc and everything except the DNS retrieval is functioning.

Is there any setting I can use to get full use of the integrated terminal?

**Comment by Tyriar** [comment]
@Pingudiem I'm guessing your terminal isn't running the right init script, you could try adding this to your settings and see if that fixes it:

``
"terminal.integrated.shellArgs.linux": [
  "-l"
]`
``
