### ISSUE TITLE
Mouse pointer disappears in main window

### ISSUE THREAD

**Issue by jasonshave** [Microsoft/vscode#44211]
### Issue Type
Bug

### Description

Open a file (I'm using PowerShell scripts/modules) and move the mouse to the window where your code is and my cursor disappears. It comes back when I move focus to the navigation bar to the left or the top title bar/menu bar.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2623 v3 @ 3.00GHz (4 x 2997)|
|Memory (System)|8.00GB (5.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.6.0
git-merger|sha|0.3.6

</details>
Reproduces without extensions

**Comment by jasonshave** [comment]
Changed the default pointer for Windows to get around it at the moment.

**Comment by RMacfarlane** [comment]
Can you check that your mouse drivers are up to date? Did this happen for other applications?

**Comment by ft3411** [comment]
For me the issue happens only in an RDP Session. As soon as the pointer is switched from the "normal select" pointer to the "text select" it disappears. After changing the pointer scheme a small line is visible as "text select" pointer which cannot be seen as such in the control panel.

**Comment by gi** [comment]
This just happened to me. It seems to only happen when the Color Theme is one of the dark or high-contrast themes. The issue is confined to the VS Code application.

The mouse pointer is invisible when in text select mode in the editor and the integrated terminal. Occasionally, it appears when double-clicking to select text, but as soon as the pointer is moved, it disappears.

System: Mac OS 10.13.4
VS Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1)

**Comment by johannespfeiffer** [comment]
Same here.

macOS 10.13.4 (17E199)
vscode 1.21.1 (1.21.1)

As a workaround changed to the "Light+" Theme

**Comment by mk-omnicar** [comment]
After upgrading OSX to the latest patch (now it's 10.13.4), I also started having this issue. The mouse cursor disappears when I'm running a dark theme, even when that theme uses a dark-blue background colour where the cursor should be at least partly visible.

Switching to a light theme seems to somehow keep the cursor visible.

**Comment by johannespfeiffer** [comment]
Seems it does not only affect vscode, other electron apps (like Atom) have the same problem.

**Comment by chrismcamp** [comment]
High Sierra did this to me!  You can work around it by increasing the cursor size a few ticks in System > Accessibility > Display > Cursor size

![image](https://user-images.githubusercontent.com/37677193/38813892-ce71f4c2-4155-11e8-838f-c5948d43e3da.png)

**Comment by chrismcleod** [comment]
High Sierra did this to me!  You can work around it by going to:

**System > Accessibility > Display > Cursor size**

and bump that up a little.

![image](https://user-images.githubusercontent.com/1134683/38814021-12354ee8-4156-11e8-9eaa-dae508a76264.png)
