### ISSUE TITLE
Recent changes greys out the code in C file, when they are under a macro and the macro is defined in a header file /.h file

### ISSUE THREAD

**Issue by pdp166** [Microsoft/vscode#44210]
### Issue Type
Bug

### Description

1.  create test.h with below code:
     #define MACRO11
2.  create test.c with below code:
     if defined(MACRO11)
     #include "test.h"
      
      int main()
      {
          //do something
      }
      #endif

3.   Observation:  Code in test.c is greyed out
      Expectation:   Code should not be greyed out

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|19.84GB (11.75GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
chmod|dle|1.0.0
status-bar-tasks|Gua|0.3.0
jlang-clang|l3d|0.0.8
cpptools|ms-|0.15.0
console|vil|0.0.6

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Moved issue to the [CPP repository](https://github.com/Microsoft/vscode-cpptools/issues/1636). Please continue this discussion there.
