### ISSUE TITLE
Php message error

### ISSUE THREAD

**Issue by EduardoMx0122** [Microsoft/vscode#44218]
### Issue Type
Bug

### Description

later when open vscode its show the error
phpcs: Request workspace/configuration failed with message: Unable to locate phpcs. Please add phpcs to your global path or use composer dependency man
when click the close button the error its show no more.

today its showing everytime im typing

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|Memory (System)|7.89GB (1.72GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
vscode-eslint|dba|1.4.6
php-debug|fel|1.12.1
php-intellisense|fel|2.2.8
php-pack|fel|1.0.1
phpcs|ika|1.0.3
ionic-preview|ion|0.0.15
material-icon-theme|PKi|3.2.3
cordova-tools|vsm|1.3.4

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
Thanks for reporting. Since this is an issue with an extension, it would be better to file it on the extension itself. In this case it sounds like it's the phpcs extension. It looks like there is already an open issue for this: https://github.com/ikappas/vscode-phpcs/issues/89
