### ISSUE TITLE
CTRL-C on no text should not add anything to the clipboard

### ISSUE THREAD

**Issue by markfaine** [Microsoft/vscode#44221]
Issue Type: Bug

CTRL-C on no content (emtpy string, blank line) should not add anything to the clipboard or overwrite what is already in the clipboard.

VS Code version: Code - Insiders 1.21.0-insider (efa33330fb0ab23b022bdff125311bdb21494b71, 2018-02-21T09:22:14.399Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|Memory (System)|15.88GB (8.04GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.10
vscode-tidyhtml|anw|1.8.0
angular2-snippets|dan|1.0.19
vscode-eslint|dba|1.4.6
regreplace|Dom|1.2.0
EditorConfig|Edi|0.12.1
mithril-emmet|Fal|0.6.1
coldfusion|ili|1.0.1
Angular2|joh|2.13.0
sublime-babel-vscode|jos|0.2.9
vscode-cfml|Kam|0.3.1
cf-filefinder|kev|0.0.2
code-beautifier|mic|1.7.2
LiveServer|rit|3.2.1
aspnet-helper|sch|0.6.4
open-in-browser|tec|1.1.0
asp|tro|0.0.1
cfml-comment-tags|trs|0.2.2
markdown-all-in-one|yzh|1.0.5

</details>
Reproduces without extensions

**Comment by usernamehw** [comment]
Just made an extension: https://marketplace.visualstudio.com/items?itemName=usernamehw.do-not-copy-empty
