### ISSUE TITLE
Disable Async File Error Indicator While Typing

### ISSUE THREAD

**Issue by uloga** [Microsoft/vscode#44220]
How can I disable file error indicator while typing. This is so annoying, it's constantly flashing while typing! 
![screen shot 2018-02-22 at 17 20 59](https://user-images.githubusercontent.com/3988672/36550270-2ecd6f16-17f5-11e8-9d55-3d2798fa9eb8.png)

**Comment by RMacfarlane** [comment]
To turn the file error indicators off completely, you can add`"problems.decorations.enabled": false` to your settings. There isn't a setting to delay when these show up, is that the behavior that you want?

**Comment by uloga** [comment]
I just wanted to turn the error indicator in file tree section. Don't want to turn it completely off.
Right now it's constantly flashing while I'm typing and I find it highly annoying, it shifts my focus away from what I'm supposed to do and makes me unproductive. IMO it should be like in other editors where on save file it should show errors in the file tree instead of on every keypress.

**Comment by uloga** [comment]
That seem to turn the error indicators completely off, even in the text editor itself. IMO it should be like in other editors where on save file it shows the tree file error indicator instead of on every keypress. I find it very annoying (constantly flashing on every keypress)  and it shifts my focus away from what I'm supposed to do.

**Comment by jrieken** [comment]
Not easy... Extension decided when they validate and they push errors/warning into the system (which then just displays them). We can think about a setting shows them only for saved resources but since the explorer doesn't show saved/unsaved users might be confused... Needs thinking

**Comment by uloga** [comment]
Duplicate? One creates an issue the other one creates another similar 7 months laters and the one created earlier is market as duplicated!?

**Comment by jrieken** [comment]
I know it's sometimes weird but some issues stick better with us because a crucial piece of information is in them.

**Comment by uloga** [comment]
Yeah but it gives me bad reputation :  "You can search for existing issues here. See also our issue reporting guidelines." like I create duplicated issues. Not gonna bother anymore wasting time on reporting anything.
