### ISSUE TITLE
Test Tour: C#

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4422]

**Comment by egamma** [comment]
@jrieken I think you did this last Friday. 

Any interesting findings to share?

Suggest to do it in the comments as is done here https://github.com/Microsoft/vscode/issues/3715#issuecomment-199242987

**Comment by jrieken** [comment]
No big surprises tbh. Editing features work well and also debugging is possible (tho it asks from admin rights). I have targeted a core clr app which the extension doesn't officially support yet (I know there is being worked on) so that on restore/run dnx comes into play.
