### ISSUE TITLE
Incredibly slow when stopping debugging also doesn't stop the terminal correctly when using integratedTerminal.

### ISSUE THREAD

**Issue by westacotta** [Microsoft/vscode#44226]
- VSCode Version: 1,20, 1.19.3, 1.19.2
- OS Version: Windows 7

Steps to Reproduce:

Debugging an Electron (2.0.0-beta.1) main process with the following configuration
        {
            "type": "node",
            "request": "launch",
            "name": "Electron: Main",
            "runtimeExecutable": "electron",
            "cwd": "${workspaceRoot}",
            "protocol": "inspector",
            "runtimeArgs": [
                "${workspaceRoot}/output",
                "--remote-debugging-port=9222"
            ]
            // ,"console": "integratedTerminal"
        },

Incredibly slow when stopping debugging.  Also it seems to leave the integratedTerminal hanging

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you explain some more about what's slow? And what you mean when you say the terminal is hanging? A config like this works fine for me.

I assume you're using it with the `console` like uncommented?

**Comment by westacotta** [comment]
Weirdly... it doesn’t do it me. 

What was slow was I would hit the stop button in the debugger and it would take several seconds for the process to stop. 

This was an electron main process I was debugging.

**Comment by westacotta** [comment]
Terrible typing....

Should be “It doesn’t do it anymore”
