### ISSUE TITLE
Debugger stopped working

### ISSUE THREAD

**Issue by afranzy** [Microsoft/vscode#44225]
### Issue Type
Bug: debugger suddenly stopped working

### Description
Cannot connect to runtime process, timeout after 10000 ms - (reason: Got a response from the target app, but no target pages found).

The launch.json is below
```json
{
    "version": "0.2.0",
    
	"configurations": [
		{
  "name": "Localhost Launch",        
		   "type": "chrome",              
		   "request": "launch",              
		   "url": "http://localhost:4200",//Change to whatever you homepage is             
		    "runtimeArgs": [                                     
			"--new-window", //Open in new window                                     
			"--user-data-dir=${workspaceRoot}/user", //Can be any directory. Makes chrome load in a different directory so that it opens in a new instance.
                        "--remote-debugging-port=9222" //Open in port 9222 (standard chrome debug port)                                 
			],            
		    "webRoot": "${workspaceRoot}/src/", //The directory that contains js, ts and map files            
		    "sourceMaps": true
        
		}
	]
}
```

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|Memory (System)|15.89GB (4.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe 
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.6
beautify|Hoo|1.3.0
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.1.0

</details>
Reproduces only with extensions

**Comment by isidorn** [comment]
Sorry for the slow response, this issue somehow fell under our radar.
Can you still reproduce this issue with latest vscode update?
