### ISSUE TITLE
Feature Request: More info when hovering over a Keyword or brace

### ISSUE THREAD

**Issue by andrey6498** [microsoft/vscode#44224]
- VSCode Version:1.20.1
- OS Version: Windows 10 Build 17101

Showing information like class names or other when hovering over keyword/tag/brace(especially on closing tag/brace) will help to determine on whichever container you're looking even if it's begining in hundreds of lines away from you.

**Comment by RMacfarlane** [comment]
Is this for a specific language? Can you give an example of the tags you mean?

**Comment by usernamehw** [comment]
I think it could be useful for any language with matching functionality (tags, brackets, ...)
#### html:
```html
<div class="something">
    <!-- a lot of content -->
</div><!-- hover over closing div should show `.something` -->
```
#### typescript:
```typescript
function something(a: string, b: string) {
    // a lot of content
}// hover over matching bracket should show `function something(a:string, b: string)`
```
#### scss:
```scss
.selector {
    // content
    .nested {
        // content
        .thing {
            // content
        }
    }
}// hover over matching bracket should show `.selector`
```
...

**Comment by andrey6498** [comment]
@usernamehw Thats exactly what i mean, Thank you for clarification!

**Comment by alexandrudima** [comment]
Let's track in #55075 (it has more upvotes at this time).
