### ISSUE TITLE
Intellisense suggestion not shown when cursor is between quotes

### ISSUE THREAD

**Issue by qutreson** [Microsoft/vscode#44222]
- VSCode Version: 1.21.0
- OS Version: Windows 10

I am trying to suggest: 'MyIntegrationEvent' (with quotes) from these contexts:
* `[EventSubscriber(ObjectType::Codeunit, Codeunit::MyCodeunit, '^', '', false, false)]` (where ^ represents my cursor position). 
* `[EventSubscriber(ObjectType::Codeunit, Codeunit::MyCodeunit, ^, '', false, false)]`

While it perfectly works for inserting it when there are no surrounding quotes: , it doesn't work in the first case. I am sending really similar text edit changes. You can find below their values and the results I get.

Is it a bug? 

**Without quotes:**
TextEdit = { NewText = "'MyIntegrationEvent'", Range = 25:65 - 25:65 }
![image](https://user-images.githubusercontent.com/31541422/36533301-697b6136-17c3-11e8-9dc3-948f8a44d35d.png)

**With quotes:**
TextEdit = { NewText = "'MyIntegrationEvent'", Range = 25:65 - 25:67 }
![image](https://user-images.githubusercontent.com/31541422/36533255-45b0f400-17c3-11e8-86bf-ac97b2aeaf71.png)

**Comment by mjbvz** [comment]
Please file this issue against your language extension. You also may be able to manually trigger intellisense using ctrl+space in the first case

**Comment by 199621** [comment]
This is Phillip they locked me out of my pc and all my apps so I can’t see the hard work you did but think you for every thing I’m video every thing they are doing hope later can help I just wanted what y’all fixed and my pc back I can’t even fix my drivers thanks any way

**Comment by 199621** [comment]
Sorry can’t see fine work you did but they locked me out of my pc and apps and every thing y’all fixed I can’t even see my own pics that was mine they have full control sorry but think you for all you have done let others know no sense working on something I never see

Sent from AOL Mobile Mail
