### ISSUE TITLE
Bug: Highlighting color in editor is different and unpredictable

### ISSUE THREAD

**Issue by petewulf** [Microsoft/vscode#44227]
- VSCode Version: 1.20.1
- OS Version: Win10

Steps to Reproduce:

1. Search for text in files and cycle through the results
2. Found occurences are highlighted in an unpredictable manner althouh the text is 1:1 the same

![highlight-bug](https://user-images.githubusercontent.com/6872322/36554258-0e99aa16-17ff-11e8-9461-a9455206d0bc.jpg)

When cycling between the results with F4 / Shift +F4 some elements get highlighted with different colors. In this case the first result is darker, all following colors are light as in the screen. 

its definitely not a theme problem as this is the same in whatever theme is selected.

**Comment by RMacfarlane** [comment]
Currently, all results are highlighted in one color, in this case yellow, and the current selection has a different highlight color, in this case grey.

**Comment by petewulf** [comment]
Yes, the strange thing is that the first occurence got the active focus and the following not when cycling through the results. I can't give you any further hints for reproducing the problem as the positions are changing in a random manner.

Here is another example: 
Line 79 the active and matched highlight, but there are also 4 lines more having the active color, this is just strange and not reproducible in any way:

![highlight2](https://user-images.githubusercontent.com/6872322/36562480-701eaee0-1817-11e8-986e-1ca9aeb98d0c.PNG)

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/11354
