### ISSUE TITLE
Add variable to tasks.json for cursor column number

### ISSUE THREAD

**Issue by elitree** [microsoft/vscode#44237]
- VSCode Version: 1.20.1
- OS Version: All

The [variables available](https://code.visualstudio.com/docs/editor/variables-reference) for tasks.json are very helpful. Unfortunately, while the line number is available in ${lineNumber}, there's no line column variable. 

The column number would be helpful for me because I have a script which can perform different actions based on where the cursor is.  If the cursor is on a function name, for example, it can launch a documentation program (outside of vscode) to show me the function documentation.  But I need both the cursor line and column passed to the script so it can determine (or at least guess) in what type of context the cursor is found.

Is there a way we could get a ${column} value to return the column number for use in tasks?  Thanks!

**Comment by alexr00** [comment]
To verify:
- Make a task that uses the new `columnNumber` variable. Example:
```
{
        "label": "My Task",
        "type": "shell",
        "command": "echo ${columnNumber}",
        "problemMatcher": []
       }
```
- Open an editor and put your cursor somewhere in it
- Run your task.
- Verify that the column number used by your task is correct.
