### ISSUE TITLE
Doesn't recognize include paths in sub-folders in a workspace

### ISSUE THREAD

**Issue by apattath** [Microsoft/vscode#44233]
### Issue Type
Bug

### Description

Opening a razzle project (with sources file) works fine only for the top-most directory. For all subfolders, vs code doesn't recognize the folder's c_cpp_properties.json file (even if it has all the correct include paths). It instead only looks for the json from the top-most folder in the workspace.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.17093

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
devinsights|Mic|0.9.5
cpptools|ms-|0.15.0
PowerShell|ms-|1.6.0
team|ms-|1.122.0

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
