### ISSUE TITLE
Terminal Issues for VS Code 

### ISSUE THREAD

**Issue by kevinhpinkerton** [Microsoft/vscode#44238]
When using the command line (bash) to compile and run code, I have been having issues when expanding the terminal. When expanding the terminal upwards, it drastically slows its functionality. Scrolling up and down becomes extremely laggy as does typing in the terminal. When the terminal is collapsed to its regular size, all functionality returns to its normal (and functional) state. This issue has made using the terminal in its expanded form nearly impossible. 

I have also had issues when outputting to the console, especially with multiline output. When I output something that has multiple lines, it can get cut off when I run the program again (revising it or not) and scroll up. All lines are shown when the program first runs, but if I run the program again and scroll back up to check the previous output (perhaps to compare the two outputs) it appears cut off, showing one to three lines instead of say the normal 10. 

Here is some info on my setup in case it helps: 
The only extensions I have are the two default c++ extensions for visual studio code. 
I use bash in the terminal (I downloaded Ubuntu in the app store to do so)
I code in c++.

Another wierd thing I've experienced seperate to the terminal is that, if I don't have Visual Studio Community downloaded, VS Code won't automatically link .h and other include files to the .cpp files. Instead, it encourages me to update the include path. However, If I do have Visual Studio Community Downloaded, VS Code seems to update the include path for me as all of my .h and include files are linked to the appropriate .cpp files and I don't need to touch the include path json file. 

Hope this helps you to improve this IDE. It is a very good one.

**Comment by MrXyfir** [comment]
I also have the issue with extreme lag when the terminal is expanded. It's been happening for probably a couple months now.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36913
