### ISSUE TITLE
extension API: vscode.Position.translate blows up rather than wrap to previous line

### ISSUE THREAD

**Issue by jVanZwieten** [Microsoft/vscode#44235]
### Issue Type
Bug

### Steps to Reproduce
1. cursor is at the beginning of a line (for example, let position=(25, 0))
2. position.translate(0, -1)

### Observed Result
Extension chokes and promise is rejected.

### Expected Result
Logic built into translate() sends the cursor to the end of the written line 24.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (6309a7734b0b0876b263a6a9cb526fc281100089, 2018-02-20T10:24:00.306Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.41GB (4.17GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\Dev\I4nG\project-mercury|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.6
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
node-modules-navigation|geg|0.0.2
vscode-postfix-ts|ipa|1.6.0
punctual-intellisense|joh|0.0.1
python|ms-|2018.1.0
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|4.1.0

</details>
Reproduces only with extensions

**Comment by jVanZwieten** [comment]
I personally worked around this case with the following:

        function previousPosition(position: vscode.Position): vscode.Position {
            if (position.character === 0)
                return document.lineAt(position.line - 1).range.end
            else
                return position.translate({ characterDelta: -1 })
        }

And I believe it could be trivial to implement.

**Comment by jrieken** [comment]
> Extension chokes and promise is rejected.

In what way? Is there an error or stacktrace on the console?

> Logic built into translate() sends the cursor to the end of the written line 24.

That won't happen because the position isn't wire back to the editor model but "a free" object. From you sample it seems like you trying to create new Position at (25 + 0, 0 + -1) which isn't allowed

**Comment by jVanZwieten** [comment]
No stack trace given, it just outputs to console that a promise was rejected:
`rejected promise not handled within 1 second                                                             console.pub.js:42`

Had to use step debugging to determine that translate() was causing it.

I'm not trying to create a new position at (25, -1) I'm trying to go back to the last character of the previous line, as my snippet achieves.

**Comment by jrieken** [comment]
You should always use this: `return document.lineAt(position.line - 1).range.end`. The position object itself doesn't know about the document and therefore cannot go to the end of the previous line, it just an object of two numbers
