### ISSUE TITLE
Copy + Paste on multiple files automatically opens them

### ISSUE THREAD

**Issue by ISInminkler** [microsoft/vscode#44231]
- VSCode Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:  Windows 10

Steps to Reproduce:

1. Shift + Click a number of files.
2. Cntrl + C to copy the files.
3. Click on a different folder in the workspace explorer
4. Cntrl + V to paste the files in the new directoty

Expected: Files are simply copied into the selected directory.

What actually happens:  Files are copied but also a new workspace tab is opened for each file that was copied.

At the very least this should not even be a default behaviour thing if it's a desired feature. When performing explorer operations I expect the explorer functionality to work similar to every generic file explorer released where copying and pasting files doesn't mean I also perform additional operations on those files.

**Comment by isidorn** [comment]
@ISInminkler I can not reproduce this behavior.
Do you see this with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by ISInminkler** [comment]
@isidorn - Yes.

**Comment by ISInminkler** [comment]
@isidorn - I even went in and disabled all plugins in my workspace and tried again. selecting multiple files in the explorer then pressing Ctrl + C to copy then selecting another folder and pressing Ctrl +V will paste the selected files but they will automatically open in the workspace.

**Comment by isidorn** [comment]
@ISInminkler can you please attach a video of this?
I can not reproduce what you are seeing. Do you have any keybindings in your keybinds.json?

**Comment by ISInminkler** [comment]
Also verified reproducible on my debian test VM, nothing special installed on it. Load up latest code:  1.20.1-1518535978. Ctrl + C to copy multiple files, create a new 'test' folder in another directory. Ctrl + V to paste, all files copied are automatically opened.

@isidorn - I don't have any video recording software.

**Comment by isidorn** [comment]
@ISInminkler when you say opened you mean opened inside vscode (as in a new vscode tab). Not that every file gets a new VSCode window?

**Comment by bpasero** [comment]
@isidorn that is probably some very old code from the time where you could drop files onto the explorer to import them. I would maybe check which cases we have and then decide what to do. Opening the file after an operation like this one seems OK to me because it is probably the intent to work on the files after copying them, no?

**Comment by isidorn** [comment]
@bpasero probably the intent -> not so sure, I would say 50%. What if you are just moving some code around. I checked the golden standard Visual Studio and they are not opening.
However nobody else complained for the previous 3 years so I am also not convinced this needs changing.
This paste file action is only used when pasting files and nowehere else, so there are no other cases except pasting via keyboard or mouse.

**Comment by bpasero** [comment]
@isidorn I also feel this is hard to judge and we didn't hear complaints so far. What is a bit ugly is that we open multiple files not just the last one, and since we now support multi-select it is more likely to happen that multiple unwanted files open. But then again, I bet we will get the opposite bug if we change this.

**Comment by isidorn** [comment]
@bpasero I could change the paste file to only open the focused file while copying.
But let's leave this open for now and wait for user feedback. If nobody else complains I suggest no action.

**Comment by ISInminkler** [comment]
@bpasero It wasn't something I really noticed until the multi-select. I will say though, opening the files being copied around automatically is a huge annoyance (even if it's only a single file). It's just less of an annoyance when it's only a single file as you can easily just close the single opened doc. I'm not sure why vscode breaks from other established conventions for file operations however.

**Comment by TheJim01** [comment]
This will sound like a "me too," but I wanted to agree that I didn't notice this behavior until multi-select became available. I copied a bunch of minified JavaScript files from a build folder into a mock-up deployment folder, and it opened all of them in all their minified glory--not only jarring, but also not useful.

I get that this behavior is useful when bringing in multiple files from outside the workspace, but--in the use-case described in this issue--the action is originating from within VSCode. Still, some users might like this.

I think the best option here is to add a setting to disable the feature, preferably when copying locally within the workspace, or--worst case--globally for all file-paste actions.

**Comment by Wallabeng** [comment]
I would also prefer a setting or disable it completely. I'm copying some files frequently and everytime I have to close them. So +1 for it.

**Comment by rsouthgate** [comment]
Yep, this is annoying purely in the case @TheJim01 mentioned. Frequently copy paste a bunch of large minified files and it opens them all... would love to be able to turn this off.

**Comment by TheFirsh** [comment]
This is still happening in 2019, very annoying :(

**Comment by WizliJamesAxe** [comment]
Этот баг работает даже у Русских в 2020. =)

**Comment by josedesigner** [comment]
Has a setting been added to disable this ongoing issue? Would really like to stop the tabs from opening on paste. Thanks!

**Comment by isidorn** [comment]
This works as expected. We no longer open files on paste
