### ISSUE TITLE
Rename folder collapses it

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#44230]
Issue Type: Bug

1.Rename folder

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9638156/36560164-167d5e68-1821-11e8-9b92-f1d336cb85ed.gif)
VS Code version: Code - Insiders 1.21.0-insider (efa33330fb0ab23b022bdff125311bdb21494b71, 2018-02-21T09:22:14.399Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by isidorn** [comment]
Code pointer https://github.com/Microsoft/vscode/blob/isidorn/searchPanel/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L208

**Comment by usernamehw** [comment]
`feature-request` - does it mean that this is the expected behavior?

**Comment by ntovas** [comment]
I m on it.

**Comment by isidorn** [comment]
@usernamehw it is always debatable if something is a feature-request or a bug. I guess this is more of a bug, but I took the artistic freedom and assigned feature-request.

**Comment by bpasero** [comment]
@isidorn it does not seem to restore the full expansion state, only the first level is that true?

**Comment by isidorn** [comment]
@bpasero yes, only the first level.
@ntovas could improve the PR and try to restore more.

**Comment by ntovas** [comment]
Yes, i can do that.

**Comment by isidorn** [comment]
@ntovas great, tree should have api to get the exapnsion state. And once the pr is ready just ping me on it.

**Comment by ntovas** [comment]
@bpasero  @isidorn  a good candidate is the refreshChildren() on treeModel:450 but its already too long.
Should i make 2 new methods, one to return all the expanded children as array and one to expand them again?

**Comment by sandy081** [comment]
@isidorn Is this ready for verification?

**Comment by isidorn** [comment]
@sandy081 @bpasero ben already verified and can add a verified label. There are some limitation which @ntovas will tackle in a pr for next milestone
