### ISSUE TITLE
Rename built-in syntax and snippet extensions to "Language Basics"

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44241]
**Problem**
Our builtin language extensions use the display name `X Language Features`. As the majority of these extensions only provide syntax and basic language support (i.e. no IntelliSense) I find the name `Language Features` to be confusing

**Proposal**
Rename built-in syntax/snippet only language extensions to `X Language Basics` or similar to make it clear that the extension only provides  basic language support and not full IntelliSense.

/ cc @Microsoft/vscode

**Comment by aeschli** [comment]
👍
