### ISSUE TITLE
Please reduce the update notifications

### ISSUE THREAD

**Issue by gauntface** [microsoft/vscode#44247]
During the day I may open code several times while switching between projects - the download update popup is annoying at best.

I understand it's desirable to encourage downloads - but **please** consider adding an option for "skip this release" or "remind me me next week" or "remind me tomorrow". The regular prompts throughout the day are slowly killing my :heart: for code.

> In case anyone wants to +1 this - please use the emotions instead of extra comments (Just to allow conversation)

**Comment by yvz5** [comment]
I think vscode needs an automatic updater. its 2018 and we still need to update manually...
