### ISSUE TITLE
VS Code freezes debugging program with many threads

### ISSUE THREAD

**Issue by rsalvador** [Microsoft/vscode#44248]
### Issue Type
Performance Issue

### Description

When using VS Code to debug a java program with many threads (~500) the UI becomes generally
unresponsive and sometimes freezes for about 10-20 seconds when hitting/continuing from a breakpoint.

The problem seems to be that VS Code tries to refresh the "Call Stack" very often
(and each refresh takes 100-200ms with that many threads)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (6.91GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Workspace Info</summary>

```
|  Window (HeaderController.java — core)
|    Folder (core): more than 20000 files
|      File types: java(12565) xml(1664) js(1072) json(925) class(430)
|                  txt(342) DS_Store(318) png(301) apex(242)
|                  html(234)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: java;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.6
tslint|eg2|1.0.28
prettier-vscode|esb|1.1.3
python|ms-|2018.1.0
debugger-for-chrome|msj|4.1.0
java|red|0.19.0
lwc-vscode|sal|0.11.2
perforce|sle|3.1.0
rewrap|stk|1.7.1
vscode-java-debug|vsc|0.6.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

VS Code example stack trace when freezing:
<img width="349" alt="stack-trace" src="https://user-images.githubusercontent.com/1301827/36579033-b3c200b8-1815-11e8-957c-1dbf19ddecf1.png">

[window.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1750535/window.cpuprofile.txt)

**Comment by isidorn** [comment]
@rsalvador once the insiders build is out on Friday you can try this out with your PR and let us know if all is good now - thanks

**Comment by rsalvador** [comment]
Will do, thx!

**Comment by rsalvador** [comment]
@isidorn tried with the 2018-03-09T05:17:20.534Z insiders build and it worked great

**Comment by isidorn** [comment]
@rsalvador great, adding verified label.
