### ISSUE TITLE
UX for git diff margin

### ISSUE THREAD

**Issue by argordmel** [Microsoft/vscode#44243]
- VSCode Version: 1.20.1
- OS Version: MacOS 10.3.3

The git diff margin should be most clear for the user experience, like a Netbeans. 

You can see only de previous version and select it. The dialog dissapear when you make click into the editor or when you select a revert. 

Thanks.

Image:
![image](https://user-images.githubusercontent.com/1320168/36570502-50426efc-1800-11e8-8f68-87d2e41f7d1e.png)

**Comment by joaomoreno** [comment]
Any suggestions?

**Comment by deivijt** [comment]
Yes, make sense @argordmel
