### ISSUE TITLE
Request: Visual Studio Code tied with Microsoft Account

### ISSUE THREAD

**Issue by jmsnavarro** [Microsoft/vscode#44246]
This is a feature request, not an issue.

Please include integration with Microsoft Account in Visual Studio Code for:

1. Hassle free syncing using different machines
2. Easy backup and restoring of settings and extensions

Cheers!
Joel

**Comment by RMacfarlane** [comment]
Thanks for the submission. One option for restoring settings and extensions on different machines is to check in `extensions.json` and `settings.json` files into a `.vscode` folder at a repository's root. When opening this repo on any machine, the settings there will be used by VS Code, and there will be a prompt asking if you want to install the extensions listed. https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

**Comment by jmsnavarro** [comment]
I can see my settings.json at C:\Users\<me>\AppData\Roaming\Code\User. But I cannot locate the extensions.json file on any of my .vscode folders. Though I can see the extension files at C:\Users\<me>\.vscode\extensions

Btw, I am not using Workspace feature, I just open each project folder.

**Comment by RMacfarlane** [comment]
The `extensions.json` file is not there by default, but can be added by running the `Extensions: Configure Recommended Extensions (Workspace)`.  This will work even if you're just opening folders and not something that has been saved as a VS Code Workspace.

**Comment by jmsnavarro** [comment]
Hi @RMacfarlane, 

That command is not available. I'm using version 1.20.1.

![image](https://user-images.githubusercontent.com/17264947/36626053-456f3016-1966-11e8-98c1-0dc08851ec9e.png)

@mjbvz, I'll look at Settings Sync. Thanks
