### ISSUE TITLE
Should we allow disabling built-in language basics extensions?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44242]
At Redmond sitdown today, @ramya-rao-a asked why we show our basic language extensions (those that only provide syntax highlighting and snippets) in the built-in extensions explorer. Given that marketplace extensions already can already override language basics, is there a use case for disabling a build-in basic language extension? If not, I propose that we don't show these in the built-in extensions view

/cc @Microsoft/vscode

**Comment by aeschli** [comment]
We had the same discussions here, I argued for the same.
Still there are some advantages to show the basic language extensions:
- Let's you study the contributions they do in the Contributions tab: language id and default associations.
- You can disable all languages you will never use for a shorter 'Configure Language' menu (@egamma mentioned that there are requests for that)

**Comment by egamma** [comment]
@Krzysztof-Cieslak I remember that you once complained that you could not disable a bundled extension. Is my memory correct? If yes, what was your scenario?

**Comment by Krzysztof-Cieslak** [comment]
Yes, I believe that I've complained about it. But it was while ago, so I don't really remember what I had in mind :)

I guess the main scenario was disabling/uninstalling built-in extensions that I never use, but thinking about it right now I think it doesn't really matter since extensions are activated lazily anyway

**Comment by alexandrudima** [comment]
IMHO it should be possible to disable all the built-in extensions, regardless of their feature-set. I agree that the extensions could be grouped to make it easier to skip over grammar-only or theme-only extensions, which typically do not cause any sort of problems.

**Comment by sandy081** [comment]
As suggested in above comment, built in extensions views show groups. 

Hence closing this.
