### ISSUE TITLE
TSX language service not showing suggestions in correct order

### ISSUE THREAD

**Issue by justinbc820** [Microsoft/vscode#44240]
### Issue Type
Bug

### Description

```
interface MyComponentProps {
	name: string;
	age: number;
}

class MyComponent extends React.Component<MyComponentProps> {
	render() {
		return <div></div>;
	}
}

class OtherComponent extends React.Component {
	render() {
		return (
			<MyComponent  $1  />
		);
	}
}
```

Place cursor at the $1 location inside the render method of OtherComponent. Hit ctrl + space to see suggestions of the props that MyComponent requires.

You will see that name and age are provided as suggestions, but they aren't at the top of the list like they should be and they are scattered in among keyword and other suggestions.

This used to work until the most recent update.

![tsx bug](https://user-images.githubusercontent.com/8052526/36568904-f4fef0c2-17e8-11e8-9fda-4e9d3e8ae505.gif)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.57GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.0.2
json-tools|eri|1.0.2
vscode-subword-navigation|ow|1.1.5
json-organizer|rin|0.0.3
nunjucks|ron|0.2.3

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/21844

Should already be fixed in `typescript@next` if you want to [give that a try in your workspace](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)
