### ISSUE TITLE
DAP: Adopt new "capabilities" event

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#44257]
We've introduced a new "capabilities" event (which ultimately will replace the unofficial way to update capabilities via a "launch" and "attach" response).

We need to add a handler to VS Code for this event that merges capabilities and updates the UI if possible. Initially it is sufficient to only support the reversed stepping actions.

**Comment by isidorn** [comment]
I have adopted the new `CapabilitesEvent`.

Please let me know when the chakra updates to the new event so I can remove the outdated code of looking at the response of `launch` and `attach` for `capaiblites`.

**Comment by weinand** [comment]
node-debug and node-debug2 will have to migrate to the new event.
I've created https://github.com/Microsoft/vscode-node-debug2/issues/171 to track node-debug2.
I've already migrated node-debug.
