### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mrc3** [Microsoft/vscode#44251]
Hello I have an error I would like to compile some codes in C and 
He does not recognize the ANSI C libraries what can I do?

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64

**Comment by RMacfarlane** [comment]
Can you please share what error you are seeing, how you are trying to compile your code, and what extensions you are using?
