### ISSUE TITLE
Feature: Preserve file extension when duplicating files

### ISSUE THREAD

**Issue by Epigene** [Microsoft/vscode#44254]
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra 10.13.2

**Needed behavior:**
When duplicating a file it would be nice to have it append the "-copy" just before the file extension.

**Current behavior:**
Duplication overrides file extension with "-copy".

**Discussion:**
As can be seen in the example image below, I choose to duplicate a file named "calendar.apib" and the default duplicate file-name is "calendar-copy" where "calendar-copy.apib" would be much more useful.

![bad_dup](https://user-images.githubusercontent.com/2983624/36584758-caea0970-1883-11e8-9fa5-6ea1aa3ac072.png)

**Comment by isidorn** [comment]
The duplicate action is contributed by an extension. Please file this issue in that extension github repository
