### ISSUE TITLE
Super slow intellillisense with powershell code

### ISSUE THREAD

**Issue by veepee78** [Microsoft/vscode#44253]
Issue Type: Bug

Intellisense is loading suggestions really slowly, it can take 30s to minute to get suggestions when hitting ctrl - space. This has been issue for longer time. Issue renders Code totally unusable.

Issue is present even if I disable all extensions, except of course powershell.

VS Code version: Code - Insiders 1.21.0-insider (efa33330fb0ab23b022bdff125311bdb21494b71, 2018-02-21T09:22:14.399Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|Memory (System)|15.85GB (5.30GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.0
PowerShell|ms-|1.6.0
team|ms-|1.122.0
vscode-docker|Pet|0.0.24
vscode-icons|rob|7.20.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
Since this is caused by an extension, please file it on the extension itself: https://github.com/PowerShell/vscode-powershell

Possibly related: https://github.com/PowerShell/vscode-powershell/issues/1205
