### ISSUE TITLE
Emmet results are always on top, even for very specific CSS properties

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#44256]
- VSCode Version: 1.20.1
- OS Version: Win10Pro-FCU

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/760112/36586592-66b54b52-18a8-11e8-9cf8-495cfdc1af70.png)

So, I will need to type out the whole `text-overflow: ellipsis` otherwise, whenever I hit tab before completing the whole property, emmet expands it to `text-emphasis:` which is nowhere related at all.

**Comment by ramya-rao-a** [comment]
@kumarharsh The fix for this will be out in tomorrow's [Insiders](https://code.visualstudio.com/insiders). Do give it a try.

**Comment by kumarharsh** [comment]
Thanks.
