### ISSUE TITLE
file content will not updated if the file was edited outside VSCode by other tools

### ISSUE THREAD

**Issue by tntljc** [Microsoft/vscode#44258]
### Issue Type
Bug

### Description

1. open a file
2. open the same file by notepad
3. edit the file in notepad
4. switch to Code, the context does not changed

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 3498)|
|Memory (System)|31.91GB (13.62GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.1.20
Go|luk|0.6.77
vscode-clang|mit|0.2.2
python|ms-|2018.1.0
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
perforce|sle|3.1.0
cmake|twx|0.0.17

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by tntljc** [comment]
The insider version doesn't have this issue, thanks guys, appreciate the great work!
