### ISSUE TITLE
Prevent quickOpen from using `search.exclude` setting

### ISSUE THREAD

**Issue by dorian-marchal** [Microsoft/vscode#44264]
I have a lot of files that are not part of my codebase (like todo files) and I don't want these files to be returned when I search for a specific term.
But, I still want to find them with the quickOpen fuzzy finder (Ctrl + P) to quick add something to them.

It would be nice to have separate settings for these two things (`search.exclude` and `quickOpen.exclude`, maybe).

**Comment by roblourens** [comment]
I don't really want to add new settings for these, it already can be confusing. I think a better solution would be a way to easily disable excludes for quickopen like we have in search - https://github.com/Microsoft/vscode/issues/15604
