### ISSUE TITLE
Different themes per window instance

### ISSUE THREAD

**Issue by bluetooth-mdw** [microsoft/vscode#44268]
I sometimes have more than one project open in different windows. I'd like to be able to select different themes for them. Right now if I go into File/Preferences/Color Theme and change the theme, all open Visual Code instances/windows change theme. I only want to affect the current window/instance. I don't know if this is a bug or the intended behaviour.

**Comment by RMacfarlane** [comment]
It's by design that all windows respond to a theme change, but perhaps we could add a setting for this.

**Comment by bluetooth-mdw** [comment]
That would be great if you could. I'm switching back and forth between windows containing similar code and having distinct colours would make it less likely I forget which is which :-)

**Comment by praveenpuglia** [comment]
This is already possible via workspace settings. For each workspace you can go to **Workspace Settings** from command palette and add the theme of your choice. Example : 

## WORKSPACE-1
```json
{
    "workbench.colorTheme": "Quiet Light"
}
```
## WORKSPACE-2
```json
{
    "workbench.colorTheme": "Monokai"
}
```

**Comment by bluetooth-mdw** [comment]
Thanks @praveenpuglia . How do you switch though? It seems as they I'd be forced to use workspaces, which currently I do not. I tried to do the same with source folder settings but it did not work. I was hoping for an easy to access theme switcher from the menu.... like we have now but for it to be applied to the current window instance only.

**Comment by praveenpuglia** [comment]
I think workspaces are built for that purpose. Switching will be the same as switching between two windows of same application.

It would definitely be nice if the command palette had an option like "Workspace Color Theme" which would work exactly like the default color theme picker but add that setting in workspace settings instead of user settings.

**Comment by deadcoder0904** [comment]
Would love Themes per instance 😍

I currently use [Peacock Extension](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) which adds unique colors in the status bar, title bar & activity bar.

Maybe if not on Global level, then it might be a good idea for that extension :)

**Comment by JoeEarly** [comment]
> Would love Themes per instance 😍
> 
> I currently use [Peacock Extension](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) which adds unique colors in the status bar, title bar & activity bar.
> 
> Maybe if not on Global level, then it might be a good idea for that extension :)

peacock looks great, thanks for sharing

**Comment by beastdestroyer** [comment]
Also, when I debug my theme extension, and I want to change theme in the extension-dev window, it keeps changing my normal instance instead of the debugging version (my extension supplies 2 themes)
