### ISSUE TITLE
VSCode uses all GPUs when debugging

### ISSUE THREAD

**Issue by Kongsea** [Microsoft/vscode#44260]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Write a program in python to use tensorflow
2. Debug the program

Does this issue occur when all extensions are disabled?: No need

I have two GPUs in my computer.
When I debug a deep learning program which uses tensorflow and GPU, the new version VSCode (since 1.20.x) uses all GPUs when debugging a program. But it only used the first GPU in the old version.
So I can run another program using the second GPU and debug a program in the old version since VSCode using just the first GPU. But now, if I run another program using the second GPU, an InternalError will be raised when I debug a program which used GPU.
The error is as bellow:
`InternalError: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY;`

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#880
