### ISSUE TITLE
Add a setting to ignore characters in quickOpen

### ISSUE THREAD

**Issue by dorian-marchal** [Microsoft/vscode#44266]
I would like to exclude some characters from the quickOpen fuzzy search.
These characters would act like spaces (currently, spaces are ignored in quickOpen).
For example, excluding `\` would help me to quickly find PHP files corresponding to a given namespace.

**Comment by roblourens** [comment]
Not sure I understand the use case. Does using a space there do what you want? Or do you want some other special behavior for `\`?
