### ISSUE TITLE
Comment a script tag in html

### ISSUE THREAD

**Issue by tim0991** [Microsoft/vscode#44267]
Does this bug fixed https://github.com/Microsoft/vscode/issues/11081?

How can i configure?  i have no idea

**Comment by aeschli** [comment]
Sorry, it's unclear what the bug is. Can you add an example and the steps to reproduce?

**Comment by tim0991** [comment]
![kapture 2018-02-24 at 13 59 13](https://user-images.githubusercontent.com/26053904/36626270-e96a04c6-196a-11e8-9d33-be28bb2dda4b.gif)

i use `cmd+/` to comment the code,  it works perfect in `html tag`, but don't works in `inline <script> tag`

**Comment by aeschli** [comment]
I can't reproduce

![44267](https://user-images.githubusercontent.com/6461412/36727396-5bcb8c34-1bbd-11e8-9ded-4ca209970197.gif)

- Is the editor in HTML mode (see lower right corner)
- If you can send me your sample, that would be great.
