### ISSUE TITLE
Easy way to add current file to git index

### ISSUE THREAD

**Issue by a-x-** [Microsoft/vscode#44263]
**feature request**

In vim ex one-line "editor" I can refer path of file in the current buffer via `%` sumbol.

I usually hit something like this: <kbd>:</kbd>`!chmod a+x %`

VS Code has no advanced intergation with git,
so I should 1) copy file path via `file: copy path` then 2) focus the integrated terminal <kbd>^\`</kbd><kbd>^\`</kbd> (twise, oh...) and 3) type something like `git add `<kbd>⌘V</kbd> eventually.

**What if VS Code would be exposing env variables like `$VSCODE_CUR_PATH` and `$VSCODE_REL_PATH`**. $cur is more convenient of course, but it's conflict prone a bit. So power users can apply shell completion: `$VS`<kbd>tab</kbd><kbd>tab</kbd>

Also, `copy relative path` does not work (Running the contributed command:'copyRelativePath' failed)

**Comment by Tyriar** [comment]
> VS Code has no advanced intergation with git

VS Code does have integration with git, it sounds like you want a "Add current file to git index" command @joaomoreno 

> What if VS Code would be exposing env variables like $VSCODE_CUR_PATH and $VSCODE_REL_PATH. 

While it's a cool idea, we give the environment to the shell and then the shell owns it. I don't think we can change it after that point.

> Also, copy relative path does not work (Running the contributed command:'copyRelativePath' failed)

Looks like copyRelativePath might be an extension

**Comment by joaomoreno** [comment]
Wait, what? The `Git: Stage Changes` command adds the currently opened file to the index.

**Comment by Tyriar** [comment]
Yeah I think that's it, I'll close since the original request for the terminal isn't going to happen.
