### ISSUE TITLE
Update to ripgrep 0.8.1

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44277]
As a follow-up to #43847 in which we reverted to ripgrep as shipped in 1.20.1.

**Comment by roblourens** [comment]
I can do this for Feb, should I?

Some explanation for the confusion in the other thread, I'm not shipping exact releases since they are so far apart, I'm building and releasing out of band, tagged with the previous release number and `-patch.x`.

**Comment by chrmarti** [comment]
No need to rush this from what I can see. Let's upgrade when you're back from vacation.

**Comment by roblourens** [comment]
Did this last month
