### ISSUE TITLE
VSCode is killing my X session while working on Go stuffs

### ISSUE THREAD

**Issue by colibrae** [Microsoft/vscode#44274]
- VSCode Version: Latest as on Arch AUR
- OS Version: Up to date version of Antergos Linux (basically Arch Linux)

Steps to Reproduce:

1. Open a folder with golang code, open up a couple of panes with the code.
2. No consistent pattern has been found yet causing this, though sometimes relating to saving files but not always, and being that it's killing X, other factors may be at play here:

a) In the background I am running a two miners (Claymore and DSTM) crunching equihash solutions that may have some role in this, as my suspicion it is causing some conflict with the accelerated rendering component of Electron. I have had other issues at times involving Chrome suddenly dying which could be the very same code going ping but not propagating the problem down to the X server.
b) I also have a pair of AMD cards, but only with the OpenCL installed but not amdgpu-pro full driver

I personally suspect this is an issue with the bundled version of Electron, and I also have plain Electron installed as a package, and I run Messenger, Discord, an Electron based cryptocurrency wallet and Chrome at the same time most of the time, but the most frequent time this happens is while I am editing code (using golang extensions), so I suspect very much the version of Electron, which I suspect is a different version than the ones the rest of my apps are using.

Does this issue occur when all extensions are disabled?: Yes/No

I have not tested this because I just want to be able to not have to restart ssh sessions and web browser or the unnerving sudden blanking of the screen, so I am going to start using Atom instead.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by colibrae** [comment]
Yes, in fact disabling the extensions caused it to occur immediately. It may be something to do with Electron and Nvidia driver... 

starting it with --disable-gpu solved the problem. It may well be related to the equihash solver running in the background as well. However, I am trying a downgrade to Nvidia driver 387, I will close the issue if this is the resolution.

**Comment by colibrae** [comment]
I can confirm that the issue is occurring also with Atom, and that it appears that this was the source of the issue. Closing the issue now.
