### ISSUE TITLE
Text in integrated terminal is invisible

### ISSUE THREAD

**Issue by troplin** [Microsoft/vscode#44273]
- VSCode Version: 1.20.1
- OS Version: Mac OS X 10.11.6

The integrated terminal remains empty, no matter what I do.
It actually works, i.e. I can type a command + enter and the command is executed, but the view remains empty. If the output of the command is long enough, the scroll bar appears, but still nothing visible and the text ist not selectable.

Does this issue occur when all extensions are disabled?: Yes
(BTW, is there a simpler way to accomplish that on Mac other than digging through the application bundle, finding the executable and launch it from the command line?)

**Comment by tlycken** [comment]
I've seen this too, sometimes; it usually helps hiding and showing the terminal again. Does that work for you too?

**Comment by troplin** [comment]
No, that doesn't seem to work.
And it doesn't just happen sometimes, it's always like that.

**Comment by Tyriar** [comment]
@troplin are you sure hiding and showing the panel again doesn't fix it? This sounds exactly like https://github.com/Microsoft/vscode/issues/42999

Could you test using Insiders to see if it still occurs https://code.visualstudio.com/insiders/

**Comment by troplin** [comment]
@Tyriar yes I'm sure and yes it also happens with the insiders build.

**Comment by troplin** [comment]
Starting a new terminal doesn't help either.

**Comment by Tyriar** [comment]
@troplin could you check the devtools console (Help > Toggle Developer Tools) and also share your settings.json file?

**Comment by troplin** [comment]
The settings.json im using with the Insiders build is empty.
The devtools console shows the following messages after showing the integrated terminal:
```
➋ Terminal.ts:2259 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
Terminal.ts:2259 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
Terminal.ts:2259 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
```

**Comment by troplin** [comment]
I've just noticed that all the text suddenly appears if I resize the terminal so that it shows less than 20 lines. As soon as it is bigger than 19 lines, the text disappears.
But this happens **only with the Insiders build**.

In the official version, the text remains invisible, regardless of the size of the terminal. But I've noticed a different effect:
If I resize the terminal to the minimal size (probably 2 lines, just before it disappears entierly), I can see the cursor. But only the cursor, no text.

**Comment by troplin** [comment]
That cursor thing only happens in the release build, if the terminal is resized to minimal size. This might not be relevant at all.

It's really easy to reproduce for me, there are no special steps involved:
1. Start VS Code (Today's Insider build, no extensions, no settings, no need to open a folder)
2. Enable integrated terminal
3. If Terminal is >=20 lines, Text is invisible, otherwise it's there.


![2018-02-28 20_50_52](https://user-images.githubusercontent.com/13793075/36809762-2bea513c-1cc9-11e8-90ba-3ac32f642712.gif)

**Comment by troplin** [comment]
@Tyriar It's still the same with today's version, the update didn't help.

**Comment by troplin** [comment]
@Tyriar Today I tried the newest Insider build and there's an interesting new effect.
A lighter rectangle shows up in the termial area with certain sizes. With some sizes it seems that the lighter rectangle is again partly covered by a rectangle with background color.
Here's a GIF:
![2018-03-25 19_26_33](https://user-images.githubusercontent.com/13793075/37877991-b400b0b4-3062-11e8-991b-8c6143b91322.gif)

Maybe this helps finding the problem?
Do you still need more information? I'm asking because there's still the "needs more info" tag.

**Comment by Tyriar** [comment]
@troplin try closing all windows and launching using `code --disable-gpu`

**Comment by troplin** [comment]
@Tyriar bingo!
With `--disable-gpu` the terminal behaves completely normal.

**Comment by Tyriar** [comment]
@troplin great we found the problem, you should be able to run with --disable-gpu with no issues. Could you tell me the model of your graphics card?

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/36913

**Comment by troplin** [comment]
NVIDIA GeForce GT 120 256 MB

Running the with `--disable-gpu` is unfortunately not really an option in the long run because on Mac you don't usually start programs on the command line.

**Comment by troplin** [comment]
Maybe related to #36913: Resizing the terminal uses 100% CPU on both cores, whether the GPU is active or not. It's an old machine though.

**Comment by Tyriar** [comment]
> Running the with --disable-gpu is unfortunately not really an option in the long run because on Mac you don't usually start programs on the command line.

@troplin it looks like there are options though when launching from the dock https://superuser.com/a/271697

> Resizing the terminal uses 100% CPU on both cores, whether the GPU is active or not. It's an old machine though.

That's interesting, could you take a performance timeline via devtools to reveal what functions are taking the most time? (Help > Toggle Developer Tools, Performance, hit the circle record button).

**Comment by troplin** [comment]
This is with `--disable-gpu`.
It's not exactly 100% but close. But as I said, it's not the fastest machine.
![bildschirmfoto 2018-03-28 um 20 36 11](https://user-images.githubusercontent.com/13793075/38049157-b9329838-32c7-11e8-946e-4b960093d729.png)
Or do you need a different view?

**Comment by troplin** [comment]
One thing that I noticed in the developer tools:
If I increase the size of the middle part (flame graph?) beyond a certain threshold, the content disappears, just like in the integrated terminal.

**Comment by micage** [comment]
It's the the same behavior on my machine:
OS X 10.11.6, Nvidia GTX 8800, 768MB RAM, Intel Q6600, 4GB RAM
Resizing the Integrated Terminal panel over a certain size (~10 lines) makes it invisible.
I think this has nothing to do with code. It seems to be a limitation on the underlying electron code base (webkit?). 

Why not introduce a new preferences option to disable GPU-rendering of Int. Terminal from there. This could be helpful for people on older/weaker hardware.

**Comment by troplin** [comment]
>  It seems to be a limitation on the underlying electron code base (webkit?).

You're probably right that it is ultimately a problem of the rendering engine.
But OTOH it worked flawlessly at some time and considering that there are other similar issues, there might be something odd in the terminal code.

**Comment by Tyriar** [comment]
> It's not exactly 100% but close. But as I said, it's not the fastest machine.

Ah I know why this is happening, when you resize the terminal it will resize the canvas which clears it and forces a full redraw. Since you're on a slow PC where the GPU doesn't play nicely with Chromium this takes longer than expected.

> Why not introduce a new preferences option to disable GPU-rendering of Int. Terminal from there. This could be helpful for people on older/weaker hardware.

It's become apparent over the last few months that we need a fallback here. Created https://github.com/Microsoft/vscode/issues/46954 to track.

---

I'll close this off as it's a more specialized case of https://github.com/Microsoft/vscode/issues/36913.

**Comment by troplin** [comment]
Just for the record:
I finally made the update to macOS 10.13 (although my machine is not officially supported) and this solved the problem.
The terminal is back to normal, even in the normal non-Insiders build.
