### ISSUE TITLE
Terminal breaks weblink for fish shell

### ISSUE THREAD

**Issue by sanyer** [Microsoft/vscode#44278]
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra 10.14.1

Steps to Reproduce:

1. Create task:
```json
{
  "label": "sample-bug-task",
  "type": "shell",
  "command": "echo https://eu-west-1.console.aws.amazon.com/cloudformation/home\\?region=eu-west-1#/stacks\\?filter=active",
  "problemMatcher": []
}
```
2. Execute the task.

Every second question mark symbol `?` gets substituted by `%3F` which breaks the link in Google Chrome.

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
Sounds more like a terminal problem.

**Comment by sanyer** [comment]
@dbaeumer yes, that's what title says.
I also tried it for bash and zsh shells - same result.

**Comment by Tyriar** [comment]
Isn't this the expected behavior for `?` within the query string to be encoded? Where abouts does the `%3f` appear first?

**Comment by sanyer** [comment]
Only every second occurence of `?` is being substituted by `%3f`.
And in this particular link `?` is a separator of query string, so it should not substituted.

Nothing should be substituted, actually. I'm just echoing string, so as it is being output exactly the same as put to tasks I expect it to be sent to browser in exact same form. If there will be anything to convert to percent-encoding, browser will handle it.

**Comment by Tyriar** [comment]
When I run this in the terminal:

```
echo https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks?filter=active
```

It will open this in the browser:

```
https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks%3Ffilter=active
```

This is correct as I believe every `?` after the first must be encoded. This is actually not so much to do with the terminal but how VS Code handles URIs as the terminal puts the string (with 2 `?` chars) into a vscode `URI` object and the encoding happens. I think browsers will do this automatically too.

Here are the vars when debugging into 

https://github.com/Microsoft/vscode/blob/c3d69b02bca9573b4b767dc292147cb043d0d1f8/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L173-L176

![image](https://user-images.githubusercontent.com/2193314/36795828-dc9a8aea-1c58-11e8-86d5-394e10641190.png)

Moving to @jrieken @bpasero who change uri.ts the most.

**Comment by jrieken** [comment]
> This is correct as I believe every ? after the first must be encoded. 

That. The format is `scheme:authority/path/?query#fragment` and every reserved character must be encoded otherwise it isn't clear if the first occurrence or ? is part of the path or the query part.

**Comment by sanyer** [comment]
Could you help me then to disable uri encoding in vscode? Let browser do it.

Although it works "as-designed", it's quite annoying as I simply can't make tasks do what I need while this command works in Terminal and other editors perfectly.

**Comment by Tyriar** [comment]
But browsers encode before making the request, they do the same thing 😕 

<img width="519" alt="screen shot 2018-03-02 at 6 32 47 am" src="https://user-images.githubusercontent.com/2193314/36903797-956cd6e6-1de3-11e8-82ee-9d41d518f14a.png">
<img width="509" alt="screen shot 2018-03-02 at 6 32 31 am" src="https://user-images.githubusercontent.com/2193314/36903800-97635d44-1de3-11e8-9ce1-85ace3e43ce0.png">

**Comment by Tyriar** [comment]
I'll leave this up to @jrieken as that's the class we use to generate valid links.
