### ISSUE TITLE
Terminal: split terminal fails and closes the terminal with error 259

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#44270]
Steps to Reproduce:

1. open the integrated terminal
2. type bash to enter wsl
3. use nano to open any text file
4. type `ctrl + shift + p` and use the `split terminal` function

Result: the bash terminal with nano is closed and this error appear in VSCode:

![image](https://user-images.githubusercontent.com/199648/36596155-12661a02-18a5-11e8-8841-10334d9d8df9.png)

I'm on Windows 10 Insiders (x64), and that's with VSCode Insiders:

> Version 1.21.0-insider
Commit ce13bb0dabd06981913c46b5a94456647864c2e0
Date 2018-02-23T05:19:18.064Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Tyriar** [comment]
I can't seem to repro. I can get nano's state to mess up which is kind of expected when resizing (this https://github.com/Microsoft/vscode/issues/26375). I can't get it to crash though. I wasn't testing on Windows Insiders though, maybe that's something to do with it?

**Comment by felipebraga** [comment]
The item on context menu in the terminal integrated Split is in the worst place ever.

**Comment by Tyriar** [comment]
@felipebraga I dunno about work place *ever*, this is pretty bad:

<img width="172" alt="screen shot 2018-03-09 at 7 02 00 am" src="https://user-images.githubusercontent.com/2193314/37213747-ce4c0070-2367-11e8-993a-d64ff6135ebb.png">

But yes I think I'll move it just under New Terminal 😄 https://github.com/Microsoft/vscode/issues/45410
