### ISSUE TITLE
'Go to definition' not working with local scope ($this)

### ISSUE THREAD

**Issue by x-wf** [Microsoft/vscode#44275]
Hello,

I'm currently using VSCode 1.20.1 to develop CakePHP 2 Web Apps, and I tend to use alot the function 'Go to definition' AKA 'CTRL+Left Click'.

This works perfect with all files and variables, except when I need to open a file which has a $this-> behind it.
For example, if I 'CTRL+Left Click' on a piece of code which doesn't contain the **$this** scope, it opens the desired file properly.

But if I try to open a file that contains the **$this** scope, it assumes the local file, and thus does not open.

![image](https://user-images.githubusercontent.com/18358292/36600877-72749666-18ab-11e8-901c-cad2b77636d5.png)
![image](https://user-images.githubusercontent.com/18358292/36600882-7607d55e-18ab-11e8-9c8e-6b844f329cd1.png)

So this is very annoying.
Is there any solution towards this?

Thank you.

- VSCode Version: 1.20.1 
- OS Version: Windows 7 Enterprise

**Comment by roblourens** [comment]
You are probably using a PHP extension, please file an issue on the extension.
