### ISSUE TITLE
formatOnType wrong tab/space format c#

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#4427]
- VSCode Version: 0.10.12
- OS Version: Windows

Steps to Reproduce:

1. set insertSpaces: true & tabSize: 2 & **formatOnType: true**
2. finish a line in c# tabs converted to wrong number of spaces

formatOnType:off
![1](https://cloud.githubusercontent.com/assets/962340/13884718/9e48694e-ed05-11e5-9b9e-7749d53f3daa.gif)

formatOnType:on
![2](https://cloud.githubusercontent.com/assets/962340/13884723/a646804a-ed05-11e5-842f-a762e66a332a.gif)

thanks!

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#113
