### ISSUE TITLE
syntax highlighting fails on large c++ files

### ISSUE THREAD

**Issue by huili80** [Microsoft/vscode#44282]
The files are fairly large, from about 500,000 to slightly over 1,000,000 lines. Cpptools intellisense appears to have no issue parsing these files, and i can click on "go to declaration/definition" and jump into these files. However, syntax highlighting seems to have failed completely on these files, no coloring at all, and i didn't find any process running at high cpu usage either so doesn't look like anything is even trying.

**Comment by RMacfarlane** [comment]
At this time, this is as designed. Certain features are turned off for files over 30MB or over 300K lines in order to reduce memory usage and be able to open those files.

Please see https://code.visualstudio.com/updates/v1_15#_large-file-support

> Any file that is over 30MB or over 300K lines will now be considered a large file and will be handled specially in some circumstances. By disabling certain features for large files, for example tokenization, line guides, and wrapping or folding, we were able to optimize memory usage, in some cases, by as much as 50%. Additionally, large files will never travel to our web worker, which computes diff information, link detection, or word based completions. This helps in reducing the memory pressure on the operating system.
