### ISSUE TITLE
editor.glyphMargin

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#4428]
> 	// Controls visibility of the glyph margin
> 	"editor.glyphMargin": false,

this option does not seem to do anything?

thanks

**Comment by joaomoreno** [comment]
@alexandrudima I just noticed this as well.

**Comment by alexandrudima** [comment]
hard coded to true @ https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/textEditor.ts#L121

I think it is for breakpoint setting reasons

**Comment by bpasero** [comment]
Yup, I think we want to always show the glyph margin to allow a user to set breakpoints. I think we should close as designed, but I forward to @isidorn to get his input.

**Comment by isidorn** [comment]
Yes, we always show the glyph margin for breakpoints setting.
@bpasero @alexandrudima Should we then hide this option from the `settings.json` so it is not bubbled up to the user?

**Comment by bpasero** [comment]
Yeah, if it cannot be changed it should also not be in the schema for settings from the editor 👍
