### ISSUE TITLE
vscode does not detect changes done externally by an SVN Update (for instance)

### ISSUE THREAD

**Issue by laperouse** [Microsoft/vscode#44284]
- VSCode Version: 1.20
- OS Version: win10

Steps to Reproduce:

1. Open file in VScode
2. Make changes in vscode
3. Close vscode (file will be stalled)
4. reopen vscode (file is still there with our changes but not yet saved)
5. Update local file with SVN to get changes done by others
6. Save file from vscode => vscode overwrites local changes and does not see it has been modified externally

This is the same issue as #41120 and should be reproducible with these steps. The key seems to be the fact that the file is stalled with changes.

**Comment by bpasero** [comment]
Yup this is https://github.com/Microsoft/vscode/issues/15749
