### ISSUE TITLE
False Scopes in SQL/String

### ISSUE THREAD

**Issue by petewulf** [microsoft/vscode#44290]
- VSCode Version: 1.20.1
- OS Version: Win10

If inline SQL-Strings have for example PHP-Variables inside, the scope afterwards is no more recognized as SQL:

![false-scopes fw](https://user-images.githubusercontent.com/6872322/36607956-8578ded0-18c8-11e8-8e80-5889eefd6568.png)

There should be only 2 cases which behave consistent: Wheter the SQL-Part inside a string should be treated as a string-scope or SQL-scope - not both.

Currently the first LEFT JOIN has scope **keyword.other.DML.sql** and on the next line **string.quoted.single.php**

**Comment by roblourens** [comment]
Filed upstream: https://github.com/atom/language-php/issues/318

**Comment by roblourens** [comment]
Since the upstream project has been archived, merging this into the general issue for a new SSH grammar. https://github.com/microsoft/vscode/issues/162707
