### ISSUE TITLE
Access to the Electron API for Extensions

### ISSUE THREAD

**Issue by DeepRobin** [Microsoft/vscode#44295]
Hey, I had the idea that extensions could have access to the Electron API. So that you can theoretically change the design of the title bar and the menu bar.

Yours sincerely,
Robin.

**Comment by mjbvz** [comment]
From the extension's point of view, electron is an implementation detail. Exposing the electron api to extensions would make adopting new versions of electron difficult for us, as we would always have to consider how any changes in the electron api may break extensions

I suggest that you file new issues for any extension API you would like. Then we can consider adding new VS Code APIs for these
