### ISSUE TITLE
Store workspace UI state also for empty workspaces

### ISSUE THREAD

**Issue by Stanzilla** [Microsoft/vscode#4429]
- VSCode Version: 0.10.11
- OS Version: Windows 8.1

Steps to Reproduce:
1. Open VS Code, toggle "Show Side bar" to enabled
2. Close VS Code
3. Double click a file that opens in VS Code

In that instance, the side bar will be disabled again.

**Comment by bpasero** [comment]
This is expected because we do not store any settings in empty workspaces. This would not happen when you open a folder.

**Comment by Stanzilla** [comment]
Yeah that is a bit counter intuitive

**Comment by kinshuk4** [comment]
Thank you for such a wonderful editor. Please provide this feature as it will be very useful 👍

**Comment by NitroG42** [comment]
While I can understand this behaviour, I'm disappointed there is no way to do that. Visual Studio Code seems awesome for use on Projects, but for single/multiple files editing in different context, not so much. 
I think fixing this would require deepchange in what a workspace is (not a folder but something more meta, with "empty workspace" becoming a workspace that can have files and folders, and then we would be able to have multiple workspace in VSC).
I'll stick to Sublime but I will check this issue from time to time hoping one day it will be fix !

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/207
