### ISSUE TITLE
spawn pidof ENOENT error #43128a

### ISSUE THREAD

**Issue by UTexas80** [Microsoft/vscode#44296]
Regarding error 43128 - 
Per suggestions, 

- Git Path was checked and it is a valid path
- I ran VS code with all extensions disabled .Problem did not resurfaced under this condition.
- When I re-enable the extensions the error code reappears.

**Comment by UTexas80** [comment]
Issue always occurs whenever I change the color theme.

**Comment by RMacfarlane** [comment]
Since there is an existing issue for this, I'm going to close this and reopen the old one.
