### ISSUE TITLE
Improve docs on how to debug VSCode in VSCode

### ISSUE THREAD

**Issue by humphd** [Microsoft/vscode#44291]
I am looking at a bug in vscode's search process, and want to debug code in that process.  Based on https://github.com/Microsoft/vscode/commit/2ae090cdf65c192247eed35bb0d3dc775ff8d60f and what's in `.vscode/launch.json`, I feel like starting `Search and Render processes` with Debugging should let me work; however, it's either timing out (see screenshot) or works but my breakpoints are never hit.

<img width="1313" alt="screen shot 2018-02-23 at 12 38 46 pm" src="https://user-images.githubusercontent.com/427398/36608058-a3d005f2-1896-11e8-8c4d-0e45432a767c.png">

I'm pretty sure the problem is just that I don't know how to do this correctly, and thus I'd like to see the debugging docs at https://github.com/Microsoft/vscode/wiki/How-to-Contribute#debugging get filled out a bit more.  Debugging the main UI is working well.  But beyond that, it would be good to know how to use these other launch configurations correctly.

I'd be happy to write the docs myself if someone could give some info in this bug.  Thanks for any help.  I think that this should be more clear for new contributors.

cc'ing @roblourens, since the commit I'm looking at was yours.

**Comment by roblourens** [comment]
The trick for the search process is that it doesn't start until you do a search. And with the timeout, you only have a short period to start it.

If you haven't already, try starting a search (like by just pressing cmd+p) immediately after launching.

If the 10s timeout is too slow on your machine, you can increase it in the launch config.

**Comment by humphd** [comment]
@roblourens, that's helpful, thank you.  It would be good to capture it in the docs.  I'll open a PR try to include this, and you can advise me there.

**Comment by humphd** [comment]
Filed https://github.com/Microsoft/vscode-wiki/pull/43
