### ISSUE TITLE
Intellisense suggestion doesn't remember my snippet preference.

### ISSUE THREAD

**Issue by imakou** [Microsoft/vscode#44305]
Hi,

I want to report a situation which I face after upgraded to 1.20.1.
The situation is the intellisense suggestion feature doesn't keep my snippets priority.

For example, 

I have two snippets, one created by myself and another one by an extension, both triggered by typing "log".  The first one is always not my preferred, even I've chosen the second one for many times.

In addition, I've set my perference as ""editor.snippetSuggestions": "top"" already.

- VSCode Version: 1.20.1
- OS Version: Mac OS

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
>  The first one is always not my preferred, even I've chosen the second one for many times.

Yeah, we do store only the label and the suggestion type which isn't enough in this case...
