### ISSUE TITLE
Cannot select text from notifications.

### ISSUE THREAD

**Issue by drproteus** [Microsoft/vscode#44301]
- VSCode Version: 1.21.0-insider (1.21.0-insider)
- OS Version: macOS 10.12.6 (16G1212)

Steps to Reproduce:
1. Get a notification
2. Try to select text from the body
Result: You cannot.

I switched to the insiders build to solve the command palette Revert File issue, and now I found I can't copy-paste PR # or commit hash from the Git blame notification as before. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
I pushed a change to allow for text selection as well as a "Copy Text" action when you right click on a notification.

**Comment by jrieken** [comment]
Selecting only works for me when the notification is expanded

![mar-01-2018 11-32-01](https://user-images.githubusercontent.com/1794099/36840121-32cc5e84-1d44-11e8-966e-45ad0c157121.gif)

**Comment by bpasero** [comment]
I pushed a fix so that any message text can be selected.
