### ISSUE TITLE
Cannot use scrollbar in split terminal with mouse

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#44300]
Issue Type: Bug

When I split a terminal I can not use the mouse to operate the scrollbar. I can do so in an unsplit terminal.

VS Code version: Code - Insiders 1.21.0-insider (ce13bb0dabd06981913c46b5a94456647864c2e0, 2018-02-23T06:08:53.779Z)
OS version: Darwin x64 16.7.0

Reproduces without extensions

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1284
