### ISSUE TITLE
Git: Support to automatically add large folders to .gitignore

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#44304]
### Issue Type
Bug

### Description
Is there any way to automatically add node_modules to .gitignore or ask the user?  I see this every time -

<img width="454" alt="image" src="https://user-images.githubusercontent.com/2301847/36619679-ab6a2708-18bd-11e8-8c0c-2f3fedf26f4b.png">
 

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (6309a7734b0b0876b263a6a9cb526fc281100089, 2018-02-20T10:16:08.796Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 9, 7|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.6
prettier-vscode|esb|1.1.3
python|ms-|2018.1.0

</details>
Reproduces only with extensions

**Comment by joshunger** [comment]
Negative Mr. Bot

**Comment by 199621** [comment]
Sorry can’t see your work they locked me out of every thing y’all fixed for me and my own Pc I just cant win Phillip please let others no

Sent from AOL Mobile Mail

**Comment by joaomoreno** [comment]
That's a great idea, would you like to submit a PR?

**Comment by joshunger** [comment]
I'll look into it.  Can you put some pointers in the bug?  What code files to look at?

**Comment by joaomoreno** [comment]
This is where that message is sent: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/repository.ts#L959

Here you have some API to add stuff to the ignore file: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/repository.ts#L825

You can use basic NodeJS fs stuff to find out whether the user has a `node_modules` folder in the root of the workspace folder.

**Comment by joshunger** [comment]
Thank you @Mrigank11 @joaomoreno
