### ISSUE TITLE
更新之后终端用不了了，怎么回事

### ISSUE THREAD

**Issue by zlkjzxj** [Microsoft/vscode#44310]
### Issue Type
Bug

### Description

更新之后终端用不了了，怎么回事

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|7.90GB (2.83GB free)|
|Process Argv|D:\software\vscode\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
quokka-vscode|Wal|1.0.104

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169
