### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by XAVI0911** [Microsoft/vscode#44316]
### Issue Type
Bug

### Description

代码实际应该有颜色区分，但更新至1.20.1版本vs code之后原先有颜色区分的代码现在呈现灰色。

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz (4 x 2993)|
|Memory (System)|3.91GB (0.47GB free)|
|Process Argv|D:\AppPlus\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.13.0
python|ms-|2018.1.0
cpptools|ms-|0.15.0

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
Can you provide a screenshot of the issue?
