### ISSUE TITLE
terminal sometimes  invisable when webpack building

### ISSUE THREAD

**Issue by zhuangzhuang** [Microsoft/vscode#44315]
- VSCode Version: 1.20.1
- OS Version: Microsoft Windows [版本 10.0.10240]

Steps to Reproduce:

![gif](https://user-images.githubusercontent.com/521058/36625218-98143c2c-1956-11e8-83ad-f4d6634aeb3e.gif)

#44273 

Does this issue occur when all extensions are disabled?: Yes

@Tyriar

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/42999
