### ISSUE TITLE
Allow to collapse an editor group to a small button to restore it when needed

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#44318]
When splitting a window pane, unless this has already bee requested.  I would like to be able to collapse a split window pane; specifically useful for example, if one pane has a few tabs and the other pane has settings you'd collapse the settings pane and un-collapse when ready to make your setting adjustments.

**Comment by bpasero** [comment]
@SheepDomination what does "collapsing" mean to you?

**Comment by SheepDomination** [comment]
Collapsing and docking to the left or right of the window as not to completely close but allow the pane to be
re-opened by un-collapsing.
