### ISSUE TITLE
File/Folder Watcher fails or out of sync in some cases, e.g. after `typings install something --ambient --save`

### ISSUE THREAD

**Issue by ceefour** [Microsoft/vscode#4431]
- VSCode Version: 0.10.11
- OS Version: Windows 10 Pro 64bit

Steps to Reproduce:

1. IntelliJ 2016.1 running in background
2. Run in Node.js command prompt: `typings install underscore --ambient --save`
3. Folder is updated in IntelliJ, but Visual Studio Code doesn't show it (until restart or other means)

![image](https://cloud.githubusercontent.com/assets/24123/13886975/1a36d822-ed6c-11e5-9111-f2c5596f23e1.png)

Other people also experience this: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8815939-add-refresh-button-for-files-and-folders

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/13888273/e63c528e-ed40-11e5-872c-7b8fc6a6c52e.png)

?

**Comment by bpasero** [comment]
Will be addressed in https://github.com/Microsoft/vscode/issues/3998
