### ISSUE TITLE
may i save the code settings on a server?

### ISSUE THREAD

**Issue by iRuxu** [Microsoft/vscode#44320]
I have a few computers . 
one is in the office , one is at home , one ..
i hope i can login a microsoft account,when i change my settings,like hotkey,ui,extends,and so on.
and the data can be saved on your server.
then when i change another computer,i have no need to reset for that.
thanks a lot

**Comment by ngmacha** [comment]
+1 for this feature! 
But maybe better if the settings can be saved in my own account, in OneDrive, for example, with profile setting allowing to enable/disable certain extensions/settings on certain computers/profiles... Is it too much to ask for?!

**Comment by agauniyal** [comment]
you can already do that, there are extensions in marketplace for that.
