### ISSUE TITLE
Cpp: Don't disable syntax highlighting when vscode doesn't find the macro definition.

### ISSUE THREAD

**Issue by zouyxdut** [Microsoft/vscode#44326]
I have some codes like following:

```
#ifdef A_MACRO
// some codes cannot be highlighted!!
#endif
```
How to enable syntax highlight for such code? I don't want this feature.

**Comment by aeschli** [comment]
@zouyxdut What extension do you use for C++? ms-vscode.cpptools?

**Comment by aeschli** [comment]
That's what I see without any extensions enabled:
![image](https://user-images.githubusercontent.com/6461412/36727239-d43bdad0-1bbc-11e8-9dc9-8ca44eeb7529.png)

Please give a more complete example to illustrate the problem.

**Comment by zouyxdut** [comment]
I installed ms-vscode.cpptools, when I disable this, the problem solved.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-cpptools#1623
