### ISSUE TITLE
Clarify how to configure format document

### ISSUE THREAD

**Issue by danielo515** [Microsoft/vscode#44329]
Hello,

The `format document` feature is nice, but it is too unpredictable, and there is no way to fine-tune it's behavior. The most important thing I'm missing is documentation about how format document takes rules in account. Seems that it takes some of eslint rules in account and ignore some others, this is not deterministic and with the same eslint configurations it takes different rules on account depending on workspaces. For example,  I have single quotes configured and sometimes format document changes double quotes to single quotes, and some other times it does the opposite.
This is happening to me o vue files for example, were the linter is correctly flagging the double quotes as invalid, and running format document changes single quotes by double quotes instead of doing the opposite. 
I have other repositories where quotes works fine, but spacing before functions does not, some places where format-document happily ignores quotes, and I can't tell why and I don't know how to change this. I am not asking for a solution to my particular problem, but I want to have documentation about how to properly configure vs-code to use the set of rules that I want it to use.

Regards

- VSCode Version: 1.20.1
- OS Version: MacOs

Steps to Reproduce:

1.  Configure some non standard eslint rules
2. Format a document and see how your rules are not taking in mind

Does this issue occur when all extensions are disabled?: Obviously not, but format does not work neither

**Comment by mjbvz** [comment]
Please file this issue/question against your eslint extension. Our built-in js and ts formatter does not take any eslint rules into account

**Comment by danielo515** [comment]
Hello @mjbvz ,
I can unserstand that. However seems that they are in conflict, and there is no documentation about how to deactivate the built-in formatter. Do they take in account the .editorconfig file ?

**Comment by mjbvz** [comment]
Set `"javascript.format.enable": false` and `"typescript.format.enable": false`

The built-in formatters only use the formatting settings from your user settings or from your workspace settings. They do not look at .editorconfig files directly or at estlint files

**Comment by danielo515** [comment]
Thank you. I'll try those suggestions and see how it goes.
Thanks again
