### ISSUE TITLE
C# Extension appears twice in Extension Marketplace sidebar

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#44327]
- VSCode Version: 1.20.0
- OS Version: Win 10

Steps to Reproduce:
1. Open a .sln file
2. VS Code prompts to view extensions for .sln files

![image](https://user-images.githubusercontent.com/2957173/36630082-f3a0653e-1960-11e8-961a-7406ee18ef6c.png)

**Comment by ramya-rao-a** [comment]
Duplicate of #43048
This is fixed in 1.20.1
