### ISSUE TITLE
tmux renders with wrong size when there are several terminals

### ISSUE THREAD

**Issue by Mellbourn** [Microsoft/vscode#44325]
I have the setup that was described by João Moreno (@joaomoreno) in his blog post https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41
Whenever I open a terminal tab in VS Code, i enter a tmux session (often attaching to an already present tmux session)
I love this setup! Among other things, it allows all the window control of tmux and it enables me to restart VSCode without losing my terminal session.

However, in the insiders edition (during my testing of #43683) I have experienced a new problem:

Whenever I have more than one Integrated terminal, and toggle visibility of the terminal window, the tmux window fills up with periods:

![Terminal window with tmux filled with periods](https://user-images.githubusercontent.com/1785727/36629965-7c0cc140-195e-11e8-881c-4739ff4c13cc.png)

Steps to Reproduce:

1. Start VSCode Insiders edition (even without extensions)
2. Open the integrated terminal with Cmd-Ctrl-`
3. A tmux window is shown in the terminal window, as expected
4. Create a new integrated terminal by pressing the `+` icon at the top right of the terminal window
5. I am automatically switched to this window, as indicated by the `2: sh` name of the terminal
6. In my setup, this actually shows the same tmux window as before, since the terminal window attaches to tmux when started. This is as expected in my environment
7. Hide the terminal window by toggling the panel, Cmd-J
8. Show the terminal again by toggling again, Cmd-J
9. Now, the tmux window shows a screen filled with “.” and in the lower right corner it says “(size 206x1 from a smaller client)” as if tmux was showing a much smaller window somewhere else (on the other “sh” tab?). 
10. If I switch back to the “1: sh” terminal tab, the problem goes away and tmux is rendered correctly again.

This problem recurs every time I hide the terminal and then show it again. Then the screen is again filled with “.” as if it was actively showing on a much smaller window. 
I have aggressive-resize turned on in tmux, but neither having it on or off makes any difference..

The problem also occurs if I resize Visual Studio Code while I have tmux visible and have two terminals.

You might well ask why I would create extra terminal windows, when tmux already has the functionality of multiple windows. The thing is that the debugger by default creates a new terminal (see #43683). So every time I start the debugger this problem occurs.

- VSCode Version: 1.21.0-insider ce13bb0dabd06981913c46b5a94456647864c2e0
- OS Version: macOS 10.13.3

This is a new problem for 1.21.0-insider. The release version 1.20.1 does not have this issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
@Tyriar 

https://github.com/tmux/tmux/blob/master/CHANGES#L141-L143 might be of your interest.

@joaomoreno 

> In my setup, this actually shows the same tmux window as before, since the terminal window attaches to tmux when started. This is as expected in my environment

I'm wondering if this is what you intended, or do you have an alternative setup. (Also I'm on tmux 2.6).
For me, this script breaks when you try to have more than 1 terminal:

```sh
#!/bin/bash
SESSION="vscode`pwd | md5`"
tmux attach-session -d -t $SESSION || tmux new-session -s $SESSION
```

The following works (dropped the `-d`), because when creating new terminal tabs it'll connect to the same session without dropping all others. If I have `-d` when creating second terminal, the first one will be detached and closed.
```sh
#!/bin/bash
SESSION="vscode`pwd | md5`"
tmux attach-session -t $SESSION || tmux new-session -s $SESSION
```

**Comment by Mellbourn** [comment]
I'm also on tmux 2.6.

> >This is as expected in my environment
>
>I'm wondering if this is what you intended,

I honestly didn't think of the `-d` parameter. I do sometimes run the same tmux window in different places, but I haven't actually used the fact that code starts two terminals with the same window, that's mostly confusing (until you realize what is happening). What I should have said was that I intended that a tmux window to be reattached rather than a completely new shell being started.

This is the script I'm using. It seems equivalent to your second one.
```sh
#!/bin/sh
SESSION="`pwd|sed "s#$CODE_DIR/##"|sed "s#$HOME/##"|sed "s#$HOME#~#"|sed "s#\.##"`-vscode"
tmux attach-session -t $SESSION || tmux new-session -s $SESSION
```

I actually think the `-d` version works pretty well. It destroys the original terminal when the debugger creates a new terminal, but the new terminal works. It also seems less prone to the problem of the periods.

**Comment by Tyriar** [comment]
I think there was a change in the way layout happens when splitting was introduced that was causing a bad layout to happen (cols = NaN).

**Comment by Tyriar** [comment]
Pushed to master and release/1.21
