### ISSUE TITLE
Sorting installed extensions

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4432]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. F1 -> Show installed extensions

Actual:
Extensions sorted by number of downloads

Expected:
Extensions sorted by name. If this is by design, it would be nice to have an option to sort them by name if possible.

**Comment by joaomoreno** [comment]
Closing for now. The current UI has sorting fixed. We will move to a new UI in which you'll be able to control the sorting.

**Comment by joaomoreno** [comment]
#637
