### ISSUE TITLE
Hitting `tab` with `alt` still down does not switch editors

### ISSUE THREAD

**Issue by Vict0rSch** [Microsoft/vscode#44328]
- VSCode Version: 1.20.1
- OS Version: macOS 10.13.2

Steps to Reproduce:

In `keybindings.json`: 

```
{
    "key": "alt+tab",
    "command": "workbench.action.openNextRecentlyUsedEditorInGroup"
}
```

Hitting `alt+tab` once does open the ordered list of editors in the group. However just like `cmd + tab` switches apps in macOS (or `alt + tab` on Windows), hitting `tab` again with `alt` still down should go to the 2nd most recently used editor in the group and so on. Doing so does not however do a thing.

Obviously the same holds for `alt+shift+tab` to go up the list and not down, again as to switch apps in OSs

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@Vict0rSch you will also need this:

```
{
  "key": "alt+tab",
  "command": "workbench.action.quickOpenNavigateNextInEditorPicker",
  "when": "inEditorsPicker && inQuickOpen"
}
```
