### ISSUE TITLE
Repeat login to github again and again

### ISSUE THREAD

**Issue by dg-cybersicherheit** [Microsoft/vscode#44323]
### Issue Type
Bug

### Description

If i want to synchronize with github every time i have to enter my github crendetials again and again.
after i submit my credentials it works for this job.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|Memory (System)|7.92GB (1.56GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by CoenraadS** [comment]
You need to update your credential manager: https://github.com/git-for-windows/git/releases

**Comment by cleidigh** [comment]
@joaomoreno 
This  seem so fundamental that maybe a notification within code might be good?

**Comment by joaomoreno** [comment]
@cleidigh This happened because GitHub deprecated algorithms in their services, leaving their credential manager < 1.16 broken: https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/

We'll try to notify people as best we can.

**Comment by darekf77** [comment]
![github](https://user-images.githubusercontent.com/7131693/36726721-0b39c076-1bbb-11e8-9c05-3d20abe33fc4.png)

Deletion of github credentials from credentials manager solved my problem.
