### ISSUE TITLE
add warning dialog when working powershell(and other integrated apps) and scripting not just opening and vscode is closing

### ISSUE THREAD

**Issue by abvaalgit** [Microsoft/vscode#44322]
Set terminal.integrated.confirmOnExit to true in the settings , is not good idea and always is shown when closing 
but i want just warnig when working and cloning or scripting ps ..not always ..
i want not to be shown dialog when ps is just open

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23808
