### ISSUE TITLE
How to make a pull request inside the VC Code from "work" to "master" branch?

### ISSUE THREAD

**Issue by BiosBoy** [Microsoft/vscode#44337]
- VSCode Version: 1.20.1
- OS Version: Win 10

Steps to Reproduce:

1. I had cloned one of my repo from GitHub to my local machine by GIT environment inside the VC Code.
1.1 The repo has a two branches with a similar files.  
2. Then I'm trying to make a pull request form VC Code to GitHub with a commited file that located in a "work" branch, and must be pulled into the "master" branch.  
3. I cannot figure out what is wrong, because a pull request between branchas does not complited. I want to admit, that a pull request on the current branch is work normally.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
VS Code doesn't yet support "pull requests". You can always run `Git: Merge` and `Git: Pull` commands to perform a pull request. You can also always resort to the command line when in doubt.
