### ISSUE TITLE
Incorrect markdown formatting when viewing marketplace inside VSCode

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#44334]
### Issue Type
Bug

### Description

When viewing the Bracket Pair Colonizer extension in marketplace inside VSCode, a line is formatted incorrectly (too large). It looks fine on the actual website though.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

![image](https://user-images.githubusercontent.com/5593825/36631824-a18f1f2e-197e-11e8-933d-23d68a601168.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Here's what it looks like now:
![screen shot 2018-04-05 at 3 52 13 pm](https://user-images.githubusercontent.com/12821956/38395770-6f66024e-38e9-11e8-819e-98095c919d4d.png)

@CoenraadS Did you change something in the release note to fix this?
