### ISSUE TITLE
Incorrect font on overall GUI on Japanese environment

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#4433]
- VSCode Version:
0.10.12-insider
- OS Version:
Windows 10 Build 14291
Steps to Reproduce:
-

Basically, VS Code does not use correct Japanese font on VS Code.
It's acceptable on the editor pane if we choose correct font-family.

But recent build introduces Japanese localization on the GUI and
it results in very very ugly look on the status bar and other UI parts.

Some of the glyphs are shown in serif (mincho) font and others are in san-serif (gothic)
and the cause is very apparent; the font is a chinese font, not Japanese one.

![image](https://cloud.githubusercontent.com/assets/1311400/13888018/43931224-ed82-11e5-8fde-3cafa885ad50.png)

We need some fix.
Or, there would be some kind of configuration to change the UI font (not editor font).

**Comment by Tyriar** [comment]
This could potentially be fixed by https://github.com/Microsoft/vscode/issues/4436 - some fonts contain glyphs for multiple locales but the one that is used is based on a few factors.

**Comment by be5invis** [comment]
Related #5260 
The fallback font shown here is SimSun, which is a **serif** **Simplified Chinese** typeface. For Japanese it is completely wrong.

**Comment by be5invis** [comment]
![](https://raw.githubusercontent.com/adobe-fonts/locl-test/master/resources/locl-example.jpg)
A image of @kenlunde’s LOCL test.
For Source Han Sans, enabling `locl` feature plus a language tag will perform correct characters for all languages, but since SHS is not installed on most computers, a specific fallback sequence for each language is a better choice.

**Comment by Tyriar** [comment]
@be5invis a good font fallback and setting `lang` on `<html>` should hopefully fix both issues. Currently it's set to `en-US` for all locales which means Chromium doesn't know which glyph to select.

**Comment by be5invis** [comment]
@Tyriar right.
There are two styles for Chinese is mentioned in #5260. I am not very familiar with Japanese typefaces so I cannot provide a good advice. Maybe you can ask @kenlunde.

**Comment by dbaeumer** [comment]
The html lang part is covered by #3841 for which I created a PR
The font part is in length discussed in #5260 

I therefore close this one.
