### ISSUE TITLE
Watch variables and tooltip variable hover info not available with breakpoint set in certain position

### ISSUE THREAD

**Issue by Seefer** [Microsoft/vscode#44339]
### Issue Type
Bug

### Description
```javascript
function makeGreeting(language) {
    return function (firstName, lastName) {
    if (language === "en") {
      console.log(`Hello ${firstName} ${lastName}`);
    }
    if (language === "es") {
      console.log(`Hola ${firstName} ${lastName}`);
    }
  }
}

var greetEnglish = makeGreeting("en");
var greetSpanish = makeGreeting("es");

greetEnglish("John", "Doe");
greetSpanish("John", "Doe");
```

In the code above I've set a breakpoint at the start of the code on the makeGreeting function definition line. It seems with the breakpoint set at this point, watch variables are shown as **not available** and hovering over variables in the source code shows no tooltip information while stepping through code in the integrated debugger.

If I set the breakpoint at any of the other lines below the MakeGreeting function, watch variables and mouse over tooltip variables info shows correctly whilst debugging. Is this intended behaviour?

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz (8 x 3074)|
|Memory (System)|11.99GB (7.82GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by Seefer** [comment]
Any way to add screenshots when reporting VS Code issues as, obviously, the source code text is horribly formatted despite using the code tag?

**Comment by weinand** [comment]
Please read the markdown styling tips below. 3 backticks followed by „typescript“ will do the tricks.

**Comment by Seefer** [comment]
Should the <> insert code button above not default to these 3 backticks? I only for one backtick. Is this only for single line code examples?

**Comment by roblourens** [comment]
This is the scenario you are in right?

![image](https://user-images.githubusercontent.com/323878/37065974-178d3054-2158-11e8-9a3b-c6d34747315b.png)

None of the other code has run, so watches and hovers won't show anything. Please include a screenshot if I misunderstand.
