### ISSUE TITLE
Can't change themes!

### ISSUE THREAD

**Issue by Tapudp** [Microsoft/vscode#44333]
- VSCode Version: 1.20.1
- OS Version: Windows 10 Version 1709 (OS build 16299.192)

Steps to Reproduce:

1. I try to change the theme and it never happens the change
2. Always shows the error stating "Unable to write into user settings. Please open User Settings file to correct errors/warnings in it and try again."
![screenshot 5](https://user-images.githubusercontent.com/8810813/36631760-9480a4a4-19a3-11e8-821b-c7e204a21198.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Your settings are invalid. Add a comma after the first property value.

**Comment by Tyriar** [comment]
When ever this happens just look for red the underline in the editor or the red in the scrollbar. You can also press F8 to jump to the problem.
