### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by Vectormike40** [Microsoft/vscode#44343]
### Issue Type
Bug

### Description

I installed some extensions and they didn't work

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.10.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz (4 x 1599)|
|Load (avg)|0, 1, 1|
|Memory (System)|3.66GB (0.27GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.4.2
beautify|Hoo|1.3.0
vscode-simple-icons|Lau|1.8.2
material-icon-theme|PKi|3.2.3
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
vscode-icontheme-nomo-dark|be5|1.3.5
django-html|bib|1.2.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.6
gitlens|eam|8.0.2
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
vscode-great-icons|emm|2.1.26
prettier-vscode|esb|1.1.3
php-debug|fel|1.12.1
php-intellisense|fel|2.2.8
php-pack|fel|1.0.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-colorize|kam|0.6.16
python|ms-|2018.1.0
color-highlight|nau|2.3.0
vscode-icons|rob|7.20.0
html5-boilerplate|sid|1.0.1
guides|spy|0.9.1
code-spell-checker|str|1.6.4
html-preview-vscode|tht|0.1.1
vim|vsc|0.10.13

(6 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
This sounds more like an extension related problem than VS Code specific.
But just to make sure: Could you please name some of the extensions that didn't work?

**Comment by tsalinger** [comment]
This sounds more like an extension related problem than VS Code specific.
But just to make sure: Could you please name some of the extensions that didn't work?

**Comment by tsalinger** [comment]
This sounds more like an extension related problem than VS Code specific.
But just to make sure: Could you please name some of the extensions that didn't work?

**Comment by kieferrm** [comment]
Closing since we did get any response.
