### ISSUE TITLE
Clear Terminal Option Disappeared

### ISSUE THREAD

**Issue by glixlur** [Microsoft/vscode#44346]
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra

**Steps to Reproduce:**

1. Open the integrated terminal.
2. Press ⌘K.

**Expected Result:**

The terminal is cleared.

**Actual Result:**

VSCode is waiting for a second keyboard combination (In French: _Touche (⌘K) utilisée. En attente de la seconde touche pour la pression simultanée..._)

**Comment by Tyriar** [comment]
This happens when you or an extension adds a chord keybinding. To work around this you need to add the cmd+k keybinding to the bottom of your keybindings.json
