### ISSUE TITLE
hi im not getting a cmd only a power shell

### ISSUE THREAD

**Issue by sonofvanu** [Microsoft/vscode#44347]
### Issue Type
Bug

### Description

hi im not getting a cmd only a power shell

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz (8 x 2926)|
|Memory (System)|7.94GB (2.80GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by RMacfarlane** [comment]
This is by design, PowerShell is the default terminal on Windows 10. You can override this with a setting, here are the instructions: https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration
