### ISSUE TITLE
Integrated terminal does not line wrap when prompt string contains emojis

### ISSUE THREAD

**Issue by martypdx** [Microsoft/vscode#44340]
This started with latest release

- VSCode Version: Version 1.20.1 (1.20.1)
- OS Version: OSX 10.13.3 (17D47)

Steps to Reproduce:

1. Open integrated terminal
2. Type text past the end of line and it wraps to same line.

Does this issue occur when all extensions are disabled?: Yes

![vscode-terminal-wrap-issue-original](https://user-images.githubusercontent.com/478864/36633155-2c44bf64-1945-11e8-84c0-acb7b07d2e83.gif)

**Comment by Tyriar** [comment]
@martypdx can you share your $PS1 variable? Run `echo $PS1` in the terminal to get it

**Comment by martypdx** [comment]
@Tyriar:

```console
📂 rehype-add-classes 🚀 echo $PS1
📂 \W 🚀
```

**Comment by martypdx** [comment]
It's the pictorial unicode 📂 🚀

**Comment by Tyriar** [comment]
@martypdx does this happen in an external terminal when the width is set the same? It looks like all the terminal is doing here is following instructions from bash, and bash is not saying to go the next line.

**Comment by martypdx** [comment]
@Tyriar works fine in external terminal. Worked in prior release of VSCode.

**Comment by Tyriar** [comment]
@martypdx hmm, maybe the shell thinks it's wider than the terminal for some reason then? If you keep typing will it eventually wrap?

Also you could try test it in Insiders as a lot has changed with regards to layout in the terminal since 1.20 due to the introduction of splitting. https://code.visualstudio.com/insiders/

**Comment by martypdx** [comment]
@Tyriar:

> If you keep typing will it eventually wrap?

Yes, the second time around it wraps and subsequent lines wrap correct. 

> could try test it in Insiders

Problem still exists in Insiders :(

**Comment by Tyriar** [comment]
I now there's an issue with emojis right now if you add one to the prompt and delete it, this could be related to that?

**Comment by martypdx** [comment]
@Tyriar Yeah, looks like if you paste an emoji and then hit backspace/delete it removes two characters. I have seen other off-by-one behavior like this as well.

![vscode-44340](https://user-images.githubusercontent.com/478864/37245070-a202d40e-2447-11e8-9750-88aba31400b8.gif)

**Comment by Tyriar** [comment]
This is a bug in https://github.com/xtermjs/xterm.js, I don't think there's a tracking issue currently.

**Comment by Tyriar** [comment]
The original report where there is an issue with wrapping I believe is a problem with bash. For backspace this is tracked in https://github.com/xtermjs/xterm.js/issues/1059
