### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Sadhan34** [Microsoft/vscode#44345]
### Issue Type
Bug

### Description

After installing arduino extension.
when I want to initilize it. show me below error
Cannot read property 'map' of undefined

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|Memory (System)|7.86GB (3.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0
vscode-serial|olb|0.0.2
vscode-arduino|vsc|0.2.10

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
Please file extension specific issues on the extension itself. I'll move this over to vscode-arduino.

**Comment by RMacfarlane** [comment]
This issue was moved to Microsoft/vscode-arduino#475
