### ISSUE TITLE
Stylus CSS support missing

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#44341]
Issue Type: Bug

When using a Stylus CSS file with the extension of '.styl', the following are missing:

1. Auto-suggestion, auto completion for CSS properties and values.
1. Colour box does not show to change colour values.

VS Code version: Code - Insiders 1.21.0-insider (ce13bb0dabd06981913c46b5a94456647864c2e0, 2018-02-23T06:08:53.779Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron . .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
ng-template|Ang|0.1.9
vscode-markdownlint|Dav|0.13.0
EditorConfig|Edi|0.12.1
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.28
angular2-inline|nat|0.0.17
vim|vsc|0.10.13
markdown-pdf|yza|0.1.7

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
VSCode doesn't ship with support for '.styl' files, please install an extension such as https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus for this support.
