### ISSUE TITLE
The keyboard shortcut for toggling editor layout in keybindings.json is inconsistent with that in keyboard-shortcuts-windows.pdf

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#44350]
### Issue Type
Bug

### Description

| version | command |  keybinding |
|---------|------------|---------------|
| 1.19.3 | workbench.action.toggleEditorGroupLayout | shift+alt+1 |
| 1.20.1 | workbench.action.toggleEditorGroupLayout | shift+alt+0 |

![key](https://user-images.githubusercontent.com/24318019/36639523-49d074c4-1a49-11e8-99df-5ca8fcd81bf8.png)
![key2](https://user-images.githubusercontent.com/24318019/36639524-51f51f06-1a49-11e8-83ba-478e9eaabe0b.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|7.89GB (2.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|2.7.0
vscode-eslint|dba|1.4.6
EditorConfig|Edi|0.12.1
vscode-icons|rob|7.20.0

</details>
Reproduces without extensions

**Comment by RMacfarlane** [comment]
This issue was moved to Microsoft/vscode-docs#1456
