### ISSUE TITLE
Make cursor "default", if "workbench.list.openMode" set to "doubleClick"

### ISSUE THREAD

**Issue by mkurnikov** [microsoft/vscode#44358]
### Issue Type
Feature Request

### Description

Intuitively, when I see hand cursor on the web (`cursor: pointer;`), I assume that element I'm pointing to is a hyperlink that will be opened after one click. Hand cursor gives a misimpression that file/folder will be opened in one click, but really it needs two. 

It would be great to either have a setting to disable `cursor: pointer;` for explorer, or set it to `cursor: default;` on `"workbench.list.openMode": "doubleClick"`. 

Atom and Intellij IDEA use `cursor: default; ` arrow as a cursor for explorer by default. 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux Mint 18.3, Linux x64 4.10.0-35-generic

**Comment by laibulle** [comment]
Hello, 

here is a proposal of how it could be handled: 
https://github.com/Microsoft/vscode/pull/47920

I just handle cursor in the TreeView but if you agree with the way it is done, we could use this option in other components.

Best regards

**Comment by liquidvisual** [comment]
The hand cursor just feels cludgy.
