### ISSUE TITLE
Support callstack with more than 20 stack frames

### ISSUE THREAD

**Issue by rick111111** [Microsoft/vscode#4435]
- VSCode Version: 0.10.11
- OS Version: Ubuntu 14.04, Window 10

In threads window, currently the depth/level of call stack is hard code limited to 20 frames in debugModel.ts, when there is a deeper call stack the threads window doesn't indicate there are more frames avaiable which is a confusing experience. Please consider:
1) Add some message on UI indicating there are more stack frames available
2) Make the stack depth limitation configurable by debugAdpater

**Comment by weinand** [comment]
Yes, we should indicate that there are more stack frames available (but this requires an addition to the debug protocol), and we need "debug settings" (like 'max number of stack frames') that apply to the the frontend.

**Comment by isidorn** [comment]
This has been fixed as part of #4792

**Comment by weinand** [comment]
@isidorn I suggest to show the 'Load more stack frames...' in italic to make it look different than normal frames.
