### ISSUE TITLE
pylint doesn't work 

### ISSUE THREAD

**Issue by phecht** [Microsoft/vscode#44359]
### Issue Type
Bug

### Description

I'm reporting this from vscode.  If it is in the wrong place, please let me know where the python extension forum is. 

It use to work, what I mean by that I would see the results of pylint on the current file.  Now I have to run it in terminal and get the results.  So, I don't get to click on it and go to the line.  

Here are my workspace settings:
{
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
    "python.pythonPath": "/home/peter/myvirtualpy/3.6/bin/python",
    "python.linting.pylintPath": "/home/peter/myvirtualpy/3.6/bin/pylint"

}
here are my user settings:
{
    "workbench.colorTheme": "Tomorrow Night Blue",
    "git.autofetch": true,
    "search.smartCase": true,
}

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2700)|
|Load (avg)|0, 0, 1|
|Memory (System)|7.67GB (0.36GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.0.2
Go|luk|0.6.77
python|ms-|2018.1.0

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
Please report this issue against vscode-python: https://github.com/Microsoft/vscode-python/issues
