### ISSUE TITLE
Can't find how to add Terminal icon to bottom bar?

### ISSUE THREAD

**Issue by serjyamp** [Microsoft/vscode#44354]
How to add it to blue bottom panel (where we have Git, Problems buttons)?
![image](https://user-images.githubusercontent.com/8271649/36640956-2db53870-1a39-11e8-9000-a16a08a2bb6d.png)

**Comment by Tyriar** [comment]
The only option right now is to use an extension for this https://github.com/Tyriar/vscode-terminal-tabs

**Comment by BrianArditoAGL** [comment]
https://marketplace.visualstudio.com/items?itemName=formulahendry.terminal
This extension adds a toggle icon there.

**Comment by Tyriar** [comment]
@BrianArditoAGL do probably shouldn't be using that extension. VS Code comes with a fully featured integrated terminal and you can run text with this command.

<img width="342" alt="screen shot 2018-03-07 at 9 50 52 am" src="https://user-images.githubusercontent.com/2193314/37108811-0d64b472-21ed-11e8-9ada-e4795c2a5011.png">

See https://github.com/formulahendry/vscode-terminal/issues/19
