### ISSUE TITLE
Feedback smiley position too low

### ISSUE THREAD

**Issue by scriptcoded** [Microsoft/vscode#44369]
### Issue Type
Bug

### Description

The feedback smiley in the lower right corner is slightly closer to the bottom of the bar than to the top. See image.

![Feedback smiley](https://i.imgur.com/Q6RibCp.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by bpasero** [comment]
It is perfectly centered as soon as I zoom in though:

![image](https://user-images.githubusercontent.com/900690/36655970-3ca39114-1ac6-11e8-80ad-eca40db8ed3f.png)

**Comment by scriptcoded** [comment]
It's odd, since I'm measuring 7 & 5 pixels on the top and bottom respectively. It should at least render 6 & 6, right? I'm assuming it has to do with the Chrome rendering engine?

**Comment by bpasero** [comment]
@scriptcoded maybe related to zooming. Do you zoom in?

**Comment by scriptcoded** [comment]
@bpasero no i didn't zoom in. I believe it has to do with downscaling or something like that. Judging by the measurements i made.

**Comment by bpasero** [comment]
If so then there is not much we can do.
