### ISSUE TITLE
Add feature deeper indexing symbols, methods and class.

### ISSUE THREAD

**Issue by makanbeling** [Microsoft/vscode#44366]
- VSCode Version: 1.20.1
- OS Version: Windows 8.1

 Whenever I wanted to  find Definition of some methods in PHP, I always get "no results". But when I opened it in sublime text, I could easily find the definition. I never met this problem before in Sublime Text.

Steps to Reproduce:

1. Put caret in methods
2. Find definition (F12)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Are you using a PHP extension? This isn't supported out of the box in vscode.
