### ISSUE TITLE
html lang attribute should be set to current locale

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4436]
The `<html>` `lang` attribute of the editor is set to `en` regardless of the locale the editor was launched in. [This can cause issues, particularly around CJK fonts](http://www.growingwiththeweb.com/2014/03/languages-and-chinese-characters-on-the-web.html).

**Comment by dbaeumer** [comment]
@egamma this is a dup of #3841 and no one was brave enough so far to do that change for March. So I proposed to due this for April to get some testing on it. Lets's discuss in standup today.

**Comment by egamma** [comment]
Revisit in April

**Comment by dbaeumer** [comment]
Dups #3841

**Comment by egamma** [comment]
:+1:
