### ISSUE TITLE
Alternative keys for moving around Quicklists work randomly

### ISSUE THREAD

**Issue by 3v1n0** [Microsoft/vscode#44365]
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Arch x64
OS: Ubuntu 16.04

Steps to Reproduce:

Add something like this to your `keybindings.json`:

```json
// Inserire i tasti di scelta rapida in questo file per sovrascrivere i valori predefiniti
[
    {
        "key": "alt+j",
        "command": "list.focusDown",
        "when": "inQuickOpen"
    },
    {
        "key": "alt+k",
        "command": "list.focusUp",
        "when": "inQuickOpen"
    },
    {
        "key": "tab",
        "command": "list.focusDown",
        "when": "inQuickOpen"
    },
    {
        "key": "shift+tab",
        "command": "list.focusUp",
        "when": "inQuickOpen"
    }
]
```

While something like that works properly when using a proper `when` clause for normal lists (like autocompletion ones), it doesn't work for the QuickLists at startup.

Once you edit your keybindings file a bit, adding and removing such stanzas a bit (I wasn't able to find a proper way to reproduce, sometimes removing and readding an object after saving work), it starts working, but only for the current workspace where this is applied.

Let me know if I can provide other debugging bits.

Using `workbench.action.quickOpenSelect{Previous,Next}` work instead

**Comment by bpasero** [comment]
@3v1n0 yes, the list commands only work if the list/tree has keyboard focus but for quick open it will never have keyboard focus, instead the input box has focus. That is why there are separate commands for quick open that you should use instead.
