### ISSUE TITLE
Absolute file paths in Problems tab lose their initial slash

### ISSUE THREAD

**Issue by krys-g** [Microsoft/vscode#44370]
- VSCode Version: 1.20.1
- OS Version: Linux

**Steps to Reproduce**:

1. Install the C/C++ IntelliSense extension.
2. Have a task/Makefile that invokes gcc with an absolute file path, e.g: ``/tmp/blah.c`` ; use the ``"problemMatcher": "$gcc"``, provided by the IntelliSense extension.
3. Have a warning or error in ``/tmp/blah.c``.
4. Build.
5. Open the Problems tab, the file is displayed as ``tmp/blah.c`` instead of ``/tmp/blah.c``. Trying to open the file will fail, because the editor cannot locate the non-existent file ``/home/krys-g/work/tmp/blah.c``.

Interestingly, clicking on the file link in the Terminal tab opens the file just fine. The problem lies only with the Problems tab, where the initial slash is dropped.

**Does this issue occur when all extensions are disabled?** N/A

The extension is required to get the ``$gcc`` problem matcher.
However, I reproduce the issue with all the other extensions disabled.

The pattern matching of ``$gcc``, as introduced by https://github.com/Microsoft/vscode-cpptools/issues/854, looks correct to me, therefore I believe the problem is with Visual Studio Code itself, not the extension.

```
  "pattern": {
      "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
```

**Comment by dbaeumer** [comment]
I think the reason for this is that the problem matcher defined by the vscode-cppptools extension assumes workspace relative paths. 

@krys-g if this is correct then there is nothing you can do to solve this right now except running make / gcc in a way that it produces workspace relative paths. But you need to double check with the cpptools extensions.

We do have a issue in VS Code that asks for autodetecting whether a path is relative or absolute (see https://github.com/Microsoft/vscode/issues/449)

**Comment by krys-g** [comment]
Thank you @dbaeumer, I will follow #449 then.
