### ISSUE TITLE
Syntax coloring is slow

### ISSUE THREAD

**Issue by torava** [Microsoft/vscode#44373]
### Issue Type
Bug

### Description

Syntax coloring is slow and I can see white text for a while. How come in Sublime Text I don't? Otherwise I like VSCode more.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz (4 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_127007|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
indent4to2|Com|0.1.2
vscode-eslint|dba|1.4.6

</details>
Reproduces only with extensions

**Comment by RMacfarlane** [comment]
To confirm, this reproduces only when extensions are enabled? If so, this is likely caused by an extension. How large/what type of file does this happen for?

**Comment by cnshenj** [comment]
I can repro easily. Open "tsc.js" from TypeScript node module (`npm install typescript`, "tsc.js" is located in "node_modules/typescript/lib"), then use "Ctrl+End" to jump the end. You'll see the code is not syntax highlighted. Wait about 1 minute, then the highlight shows up.

**Comment by rebornix** [comment]
Our current tokenization engine goes from the top to the bottom and this engine with a rich grammar (TypeScript) can be slow.

**Comment by mjbvz** [comment]
@rebornix Can we do anything about this on the TypeScript grammar side of things?

**Comment by rebornix** [comment]
@mjbvz right now the problem with our grammars is we only know the time is spent in Regex searching but we don't know which part

* Are the grammar regexes too flat, which make the regex matching fail too late?
* Are the grammar stacks too deep, which uses a bunch of time push/pop in the stack?
* Is there any hot path in typescript grammar matching? If there is one, can we increase the priority of that path a bit to reduce stacks?

Maybe we can try to add some tracing into vscode-textmate and find something interesting.

**Comment by optomux** [comment]
This is still not fixed. Try a 60k LOC C++ file. It takes 10 seconds to color it. Pathetic.

**Comment by xyproto** [comment]
For C++, could the line be colored gray if the line starts with `//` **before** the advanced syntax coloring system kicks in? When commenting in and out single lines is mainly when I notice the delay.

**Comment by jasonwilliams** [comment]
For anyone arriving, this is a dupe of https://github.com/microsoft/vscode/issues/64681
