### ISSUE TITLE
Feature request: streamline Git merge conflict resolution through editing

### ISSUE THREAD

**Issue by angelo-mollame** [Microsoft/vscode#44382]
**Feature Request**

Sometimes, in order to resolve a merge conflict:
1) I manually edit both sides, importing changes from one another, until the two sides are the same
2) I verify that they are the same by clicking on Compare Changes
3) If they are, I go back and click on "Accept Current Change" (which has the same effect of "Accept Incoming Changes")

This approach is sometimes easier, faster, and less-error prone than looking at the diff.

It would be great if I could do steps (2) and (3) with a single click, through a "Resolve If Equal" option or something.

It would be **awesome** if I could do steps (1), (2) and (3) in one shot, i.e. the conflict is automatically resolved as soon as I make the two sides the same!

**Comment by angelo-mollame** [comment]
I really needed this, so I wrote a VS Code extension for it: https://marketplace.visualstudio.com/items?itemName=angelomollame.conflict-squeezer

**Comment by chrmarti** [comment]
@angelo-mollame We are trying to keep the main product small. Extensions are the best way to add features.
