### ISSUE TITLE
This annoying issue came back again

### ISSUE THREAD

**Issue by rui-ktei** [Microsoft/vscode#44381]
Hi, thank you very much for keeping VS Code the best IDE in the world. Could you please give some guidance regarding this issue? I run command-line to start VS Code, but somehow it doesn't detach from the process where I started it. I don't want to keep this gitbash window open just to keep my VS Code alive.

This issue is REALLY annoying and it occurred to me before and then it disappeared for a while now it came back again.

![image](https://user-images.githubusercontent.com/12144265/36654955-e83b6f4a-1b13-11e8-8bbb-bf25bb13c0d0.png)

Thanks a million!

**Comment by joaomoreno** [comment]
Why did you completely ignore the issue template? Please do do that. I'll simply close the issue next time.

What is your Code version? What is your OS? What is your OS version?

What do you get by running `which code`?

**Comment by Jackbennett** [comment]
rui-ktei seems to refer to the code process being spawned as a child process of the console. Thus closing the console closes the editor;

![image](https://user-images.githubusercontent.com/791134/36679639-9df62e50-1b0b-11e8-9065-667af00c1604.png)

Reproduced on windows 10 1709, VSCode 1.19.3 and just updated to VSCode 1.20.1 with powershell, cmd and pwsh. I wasn't aware this behaviour was ever any different.

**Comment by rui-ktei** [comment]
@joaomoreno sorry about that. Here's the information you might need:

![image](https://user-images.githubusercontent.com/12144265/36699088-cb9ac872-1b9f-11e8-878e-06f95c80014e.png)

![image](https://user-images.githubusercontent.com/12144265/36699179-0d66f514-1ba0-11e8-8fcc-678e87417687.png)

```
$ which code
/c/Program Files/Microsoft VS Code/code
```

**Comment by joaomoreno** [comment]
Did you manually add `/c/Program Files/Microsoft VS Code` to your `PATH`? The right path to add is `/c/Program Files/Microsoft VS Code/bin`. That won't lock the command window.

**Comment by rui-ktei** [comment]
@joaomoreno Thanks. I changed it to /bin
