### ISSUE TITLE
Powershell intellisense really slow

### ISSUE THREAD

**Issue by ebmarquez** [Microsoft/vscode#44384]
### Issue Type
Bug

### Description

Using powershell extension, intellisense is super slow to respond.
type "function" and wait 3 seconds and it might respond with the code snip. :-(
Using firstparty hardware, sp4 pro 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.17107

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|Memory (System)|15.93GB (7.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
project-manager|ale|0.24.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
gitignore|cod|0.5.0
git-extension-pack|don|0.1.3
githistory|don|0.4.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
gitlens|eam|8.0.2
vs-code-xml-format|fab|0.1.5
docker-explorer|for|0.1.6
terminal|for|0.0.10
MagicPython|mag|1.0.12
prettify-json|moh|0.0.3
python|ms-|2018.1.0
azurecli|ms-|0.4.0
PowerShell|ms-|1.6.0
vs-keybindings|ms-|0.1.7
vsliveshare|ms-|0.2.163
vscode-docker|Pet|0.0.24
python|tht|0.2.3
vscode-ansible|vsc|0.1.4
jinja|who|0.0.8
vscode-open-in-github|ziy|1.3.1

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
Pls file the issue against the powershell extension [here](https://github.com/PowerShell/vscode-powershell/issues/new).
