### ISSUE TITLE
List: disposeTemplate is never called?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44389]
I am wondering about the lifecycle of `disposeTemplate`, I can never get it to be called. The notifications are using list widgets and I am disposing the list widget once the notification toast hides. I would expect that to trigger the templates to get disposed as well, otherwise each notification leaks.

**Comment by joaomoreno** [comment]
Wow, this just wasn't wired at all!

**Comment by bpasero** [comment]
@joaomoreno cool 👍
