### ISSUE TITLE
Report of RHEL7 crashing after around 10 seconds

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4438]
Investigate:

> FYI, the app only runs about 10 seconds before croaking and it fails 100% of the time.

**Comment by bpasero** [comment]
Please investigate but we decide based on that if there is action for GA or not.

**Comment by Tyriar** [comment]
I can't reproduce yet. Here are the screenshots from the report:

![screenshot from 2016-03-18 15-14-31](https://cloud.githubusercontent.com/assets/2193314/13959869/16bd2ca6-f013-11e5-8db3-20884d58c740.png)

![screenshot from 2016-03-18 15-15-22](https://cloud.githubusercontent.com/assets/2193314/13959897/322e96aa-f013-11e5-9c67-d4c759174ca0.png)

**Comment by Tyriar** [comment]
It looks like it's an issue with V8/Node.JS running out of memory. Not sure what could be causing this but it seems environment-specific.

Chrome seemed to work fine, as does Eclipse and IntelliJ.

**Comment by bpasero** [comment]
@Tyriar any extensions installed? it seems to crash in the extension host right.

**Comment by Tyriar** [comment]
@bpasero I'm told this was a clean launch, so no extensions other than the built-in ones.

**Comment by bpasero** [comment]
@jrieken did an extension that would profile the extension host, maybe he can send you instructions so that we get a heap dump of the process.

**Comment by Tyriar** [comment]
@bpasero I added you to the email thread

**Comment by jrieken** [comment]
@Tyriar This extension (need manual building on Linux) should print the heap usage onto the output channel: https://github.com/jrieken/vscode-extheap

**Comment by Tyriar** [comment]
Assigning to @joaomoreno as it seems to do with extensions.

**Comment by joaomoreno** [comment]
Just installed CentOS 7. All seems to work fine.

<img width="916" alt="screen shot 2016-03-30 at 11 09 36" src="https://cloud.githubusercontent.com/assets/22350/14137397/ef9c6fd2-f667-11e5-87df-3e588f1fbf57.png">

**Comment by Tyriar** [comment]
Deleting `.vscode` and `.vscode-insiders` seemed to fix the issue for the user.

**Comment by ra9r** [comment]
So this is same issues occurs to me running on Mac OS X 10.11.5.  I'm running VSC 1.1.1.  Initially I get an error "**Extension host terminated unexpectedly.  Please reload the window to recover.**"  Clicking "Reload Window" results in the error being generated again.  When I leave it sitting for a few seconds, a second message appears that says "**Error from the extension host: channel closed**".

**Comment by Tyriar** [comment]
@joaomoreno we have another issue open for @ra9r's problem right?

**Comment by joaomoreno** [comment]
Unfortunately, those are symptoms of a wide variety of maladies. @ra9r, let's follow this up in #7238.

**Comment by robfe11** [comment]
Getting the same issue on Mac OS X 10.11.1 with VSC 1.2.0, however, it fails as soon as I open it.

**Comment by rustanacexd** [comment]
same issue. using mac os x 10.11.5

**Comment by MarkusH** [comment]
Confirmed on current Arch Linux with version 1.4.0 of Visual Studio Code OSS. Deleting `~/.vscode` does *not* fix the issue for me.

```
$ visual-studio-code-oss 

<--- Last few GCs --->

    5977 ms: Mark-sweep 1230.5 (1357.1) -> 1230.5 (1357.1) MB, 6.2 / 0 ms [allocation failure] [GC in old space requested].
    5992 ms: Mark-sweep 1230.5 (1357.1) -> 1230.5 (1358.1) MB, 14.4 / 0 ms [allocation failure] [GC in old space requested].
    6004 ms: Mark-sweep 1230.5 (1358.1) -> 1230.5 (1352.1) MB, 12.0 / 0 ms [last resort gc].
    6016 ms: Mark-sweep 1230.5 (1352.1) -> 1230.5 (1346.1) MB, 11.8 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2145f58cba81 <JS Object>
    1: Join(aka Join) [native array.js:187] [pc=0x128e9d15786f] (this=0x2145f5804189 <undefined>,y=0x19a9a1e4a21 <JS Array[2]>,z=2,P=0x1487cb736f31 <String[1]: ,>,O=0x2145f58b6281 <JS Function ConvertToString (SharedFunctionInfo 0x2145f5850041)>)
    2: InnerArrayJoin(aka InnerArrayJoin) [native array.js:364] [pc=0x128e9d149f5b] (this=0x2145f5804189 <undefined>,P=0x1487cb736f31 <String[1]: ,>,y...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

**Comment by MarkusH** [comment]
I had a stale socket `/tmp/Code - OSS-24d9c7-1.4.0-shared.sock`. Terminating VS Code, removing the socket and restarting VS Code solved the issue for me.
