### ISSUE TITLE
VSCode insists on complaining on the top bar whenever it gets open

### ISSUE THREAD

**Issue by zivcaspi** [Microsoft/vscode#44388]
### Issue Type
Bug

### Description

Open VSCode. If dotnet cli is not on the path, VSCode complains (even if there's nothing related to dotnet open). If some extension has failed, VSCode complains. In many cases, the console pane opens up automatically for apparently no reason (and with no relations to what I want to do with VSCode).

When I open VSCode with some file, I want to edit that file. I'm not interested in reconfiguring my system of learning about all things that various extensions complain about. Get them outside the view.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|31.91GB (18.10GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
vscode-rust|kal|0.4.2
codeshell|Kip|0.2.2
vscode-antlr4|mik|1.2.9
python|ms-|2018.1.0
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Please continue this discussion here: https://github.com/OmniSharp/omnisharp-vscode/issues/2115
