### ISSUE TITLE
Bug: file contents not refreshed for error detection after git checkout

### ISSUE THREAD

**Issue by angelo-mollame** [Microsoft/vscode#44386]
- VSCode Version: 1.20.1
- OS Version: Windows_NT x64 10.0.16299
- Language: TypeScript

Steps to Reproduce:

1. Start on branch1
1. git checkout branch2
2. Open File1

If the code in File1 refers to a something in File2 that only exists in branch2, but didn't exist in branch1, I see an error in File1 complaining that thing doesn't exist. I need to open File2 and come back to File1 to make the errors disappear.

**Comment by joaomoreno** [comment]
What error do you see? Which language?

**Comment by angelo-mollame** [comment]
I see this in TypeScript.

I see the red squiggly over the code that is referenced the stuff that I brought in with the new branch. If I hover on it, For example I see the error "Object literal may only specify known properties, and "..." does not exist in type "...". The error will of course depend on the particular usage that I make of the referenced symbol.

I just noticed that after about a minute, the error disappears on its own, even if I don't open the other file. It's still a bit annoying, as it prompts to take unnecessary action to fix non-existent issues.

**Comment by joaomoreno** [comment]
Git checkout merely touches the disk, which should fire file events, which should trigger TypeScript recompilation. Moving to @mjbvz
