### ISSUE TITLE
Responsive integrated terminal

### ISSUE THREAD

**Issue by gs-eali** [Microsoft/vscode#44380]
### Issue Type
Feature Request

### Description

Reques to make the integrated terminal response so when we resize the vscode. The content of the terminal can read in any window size

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688
