### ISSUE TITLE
Class auto-complete doesn't work ((( why so??? 

### ISSUE THREAD

**Issue by sevast1an** [Microsoft/vscode#44391]
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra 10.13.1

Steps to Reproduce:

1. When I write sass styling in my style.sass file, class autocomplete doesn't work, why so? i should write every time from beginning 
2. I have attached file for proof 

Does this issue occur when all extensions are disabled?: Yes
![2018-02-26_09-47-06](https://user-images.githubusercontent.com/25949591/36658615-0c538b86-1ada-11e8-9acc-5fe22d65fcf6.png)

**Comment by RMacfarlane** [comment]
Currently, there is only intellisense for selectors, properties, and values in css. There is an existing feature request to add completions for class names, https://github.com/Microsoft/vscode/issues/28442. Closing this issue as a duplicate.
