### ISSUE TITLE
Feature request for Angular projects - to have "Show related Component.ts" for HTML-template file

### ISSUE THREAD

**Issue by dFarkhod** [Microsoft/vscode#44399]
VSCode Version: Any version
OS Version: Windows
Steps to Reproduce:
If a current project is type of Angular project,
to have "Show related Component.ts" context menu item if HTML-template file is open
and if Component.ts is open, to have "Show related HTML-template" menu item.

This will be easier to developer to locate necessary files.

**Comment by auchenberg** [comment]
@dFarkhod What would clicking on `Show related Component.ts` do? Trigger a search? Find references
?

This could probably be implemented by the Angular Language Service. https://github.com/angular/vscode-ng-language-service

**Comment by dFarkhod** [comment]
@auchenberg , it will somehow find that respective component.ts file and open it.
Behaviour should be similar to as if you right click on xaml-file and select **View code** in Visual Studio.

**Comment by auchenberg** [comment]
This issue was moved to angular/vscode-ng-language-service#288
