### ISSUE TITLE
Disallow content providers  to fire events for foreign schemas

### ISSUE THREAD

**Issue by karikera** [Microsoft/vscode#44398]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Pro

Steps to Reproduce:
1. I registered three TextDocumentContentProvider with different scheme(ftp/sftp/ftps)
2. fire onDidChange  with uri (ex: sftp://foo.bar/foo.html)
3. I received same event three times with same scheme (ex: sftp://foo.bar/foo.html  x3)

What I expect:
TextDocumentContentProvider.onDidChange suppress different scheme event
or registerTextDocumentContentProvider function receive multiple scheme
or registerTextDocumentContentProvider throw error if same provider is used

**Comment by jrieken** [comment]
Can attach a code sample?

**Comment by karikera** [comment]
I registered with same instance but different scheme three times

```ts
const ftpTree = new FtpProvider();

...

workspace.registerTextDocumentContentProvider('sftp', ftpTree);
workspace.registerTextDocumentContentProvider('ftp', ftpTree);
workspace.registerTextDocumentContentProvider('ftps', ftpTree);

...

ftpTree._onDidChange.fire(Uri.parse("sftp://foo.bar/foo.html"));

```

**Comment by jrieken** [comment]
Ok, please don't do that ;-) A code change on our side will likely throw an error because a provider registered for schema-foo shouldn't talk about schema bar.
