### ISSUE TITLE
vs code rollback version issue

### ISSUE THREAD

**Issue by LoveFishSoup** [Microsoft/vscode#44394]
- VSCode Version: 1.19.3
- OS Version: win7, 64bit

Steps to Reproduce:

1. I just restart vs code for new version
2. It installed then I chose to allow all operations of vs code
3. something went wrong
4. Then it rollbacks the last version
5. I tried to open VS code but failed, it shows several files missing 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
> It installed then I chose to allow all operations of vs code

What does this mean?

Can you fully reinstall VS Code?
