### ISSUE TITLE
Provide an option to keep quick open open on focus lost

### ISSUE THREAD

**Issue by sijad** [Microsoft/vscode#444]
when i try to switching between windows using `alt+tab` QuickOpen panel (which i opened with `f1`) close, it's a little annoying

**Comment by bpasero** [comment]
As designed, sorry.

**Comment by sijad** [comment]
but it close even a popup (other applications) opens, it should not be like this...

**Comment by bpasero** [comment]
Let's reopen, its a candidate for a configuration setting.

**Comment by bpasero** [comment]
Added `workbench.quickOpen.closeOnFocusLost` for August.
