### ISSUE TITLE
Git "Create new branch" option shows "$(plus)" when filtering

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#44402]
If I click the git branch in the bottom left status bar the picker has an option for "Create new branch" which has a plus next to it. If you start typing "plus" the plus icon changes to `$(plus)` (possibly the highlighting is messing up a placeholder for the icon?).

![plus](https://user-images.githubusercontent.com/1078012/36663272-fd1240f0-1ad8-11e8-971d-a7f2e45ee2fa.png)

**Comment by mikaoelitiana** [comment]
It seems to be already fixed in last master: 

![capture d ecran 4](https://user-images.githubusercontent.com/674667/36665068-d4a4175c-1ae6-11e8-8d69-a327506b4006.png)

**Comment by joaomoreno** [comment]
Thanks @bpasero!

**Comment by DanTup** [comment]
Ah, I did search but the original didn't mention Plus and I didn't realise it affected more. Thanks!
