### ISSUE TITLE
File indexer stays busy

### ISSUE THREAD

**Issue by crewone** [Microsoft/vscode#44415]
Issue Type: Bug

The explorer keeps "indexing" (or at least indicating it is busy) and no actual files are shown in the workspace pane. If I close the workspace and then add a folder, it works. Files are shown instantaneously. 

When clicking on some directories the spinner in front of them stays active without the directory ever showing data (they are small directories with maybe 10 files) Some directories do show data. 

Sometimes after reopening a previous project, the pane stays blank but busy.

This is new since last monday. The regular edition of VSC does not have this behaviour.

![vscode](https://user-images.githubusercontent.com/2951144/36672590-1e8e5cb0-1b00-11e8-99b8-74aa7b2d2645.gif)

VS Code version: Code - Insiders 1.21.0-insider (903169966590cd236c5016cdc774875215d31765, 2018-02-26T06:15:36.165Z)
OS version: Windows_NT ia32 10.0.17101

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz (4 x 2993)|
|Memory (System)|15.93GB (8.13GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
Seems like the file can not be resolved via the file service. Forwarding to @bpasero

**Comment by bpasero** [comment]
@isidorn well and the last one touching the fileservice was you with the lstat thing, I would bet its related.

@crewone can you see if something is logged to the console (Help > Toggle Developer Tools > Console).

**Comment by crewone** [comment]
I will check when I get home. For now I can tell you the files reside on an NFS mount, maybe that matters.

**Comment by crewone** [comment]
I see a bunch of these:

```
TypeError: Cannot read property 'isSymbolicLink' of null
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2863:540
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:271:1014
    at C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js:284:29
    at FSReqWrap.oncomplete (original-fs.js:114:15)```

**Comment by bpasero** [comment]
@isidorn seems related to your changes

**Comment by isidorn** [comment]
@bpasero yes, you were right, I will fix. Thanks

**Comment by isidorn** [comment]
This one has better steps https://github.com/Microsoft/vscode/issues/44543
@crewone let me know if blackobx is not a dangling symlink and I can reopen

**Comment by crewone** [comment]
Definitely not. In fact, the regular edition of vscode shows the contents of that directory just fine.

**Comment by crewone** [comment]
I can confirm this is fixed. Good job fixing what you broke @isidorn 👍 

(Jokes aside, thanks a lot for contributing to this awesome editor!)

**Comment by isidorn** [comment]
Thanks for letting us know this got fixed, adding verified label :)
