### ISSUE TITLE
Emmet: Make possible to add spacing before self-closing tag (e.g. in JSX) when using Emmet: Split/Join Tag

### ISSUE THREAD

**Issue by evenfrost** [Microsoft/vscode#44417]
It would be handy if there was an option for expanding Emmet tag abbreviation with spacing before closing (`/>`) bracket in self-closing tag. Right now it expands without spacing, which violates practices in some JS styleguides (e.g. [Airbnb's one](https://github.com/airbnb/javascript/blob/3c3074e502dc9ebc7dbdad372df474e49f52d512/packages/eslint-config-airbnb/rules/react.js#L352)), and we have to manually add spacing.

![peek 2018-02-26 17-46](https://user-images.githubusercontent.com/3055750/36676592-1f50dac0-1b1d-11e8-8834-da9e9655db01.gif)

- VSCode Version: 1.20.1
- OS Version: Ubuntu 17.10

**Comment by ramya-rao-a** [comment]
Add the below to your settings
```
"emmet.syntaxProfiles": {
    "jsx": {
        "self_closing_tag": "xhtml"
    }
}
```

For more on this, see https://docs.emmet.io/customization/syntax-profiles/

**Comment by evenfrost** [comment]
@ramya-rao-a Still not working while other `syntaxProfiles` options are working. Tested with following config (`tag_case` was added for checking if other options were working) :
```json
    "emmet.syntaxProfiles": {
      "jsx": {
        "self_closing_tag": "xhtml",
        "tag_case": "upper"
      }
    }
```
![peek 2018-03-05 16-22](https://user-images.githubusercontent.com/3055750/36977215-793c859c-2091-11e8-81d8-a9e3718e5b48.gif)

**Comment by ramya-rao-a** [comment]
I was under the assumption that you were looking for the extra space for the self closing html tags only. But it looks like you want this for custom tags as well when using the `Emmet: Split/Join Tag` which doesn't respect the syntaxProfiles setting

**Comment by evenfrost** [comment]
Sorry, I wasn't clear enough. Yeah, such option will be handy for JSX for aforementioned reasons (e.g. linting validation).

**Comment by gushuro** [comment]
I wonder if there's a problem with adding the space before the `/>` every time.
I'm not familiar with best practices in HTML, but from what I found online, browsers don't really care if there is a space or not.
@ramya-rao-a any thoughts?

**Comment by ramya-rao-a** [comment]
@gushuro We shouldnt add the space everytime. Browsers may not care about the space, this is more to suit coding standards

**Comment by evenfrost** [comment]
@gushuro It's all about [coding practices](https://github.com/airbnb/javascript/blob/3c3074e502dc9ebc7dbdad372df474e49f52d512/packages/eslint-config-airbnb/rules/react.js#L352), as I mentioned above.
