### ISSUE TITLE
Interactive terminal eats GB's of RAM when issuing commands

### ISSUE THREAD

**Issue by tlycken** [Microsoft/vscode#44416]
When I issue a command in my interactive terminal, VS Code stars eating crazy amounts of memory. After some 10 seconds it swings down to normal levels of a couple of hundred MB again.

![image](https://user-images.githubusercontent.com/1550920/36673825-634ea126-1b04-11e8-8287-47e6a693c78f.png)

I've tried to figure out if there are certain commands or terminal actions that trigger this behavior, but no luck so far; due to the nature of the problem (and my computer becoming quite unresponsive when it happens), I'm having a hard time figuring out exactly what is causing it, how long the delay is etc.

Closing the integrated terminal seems to release the memory and stop the swinging behavior.

- VSCode Version: 1.20.1
- OS Version: Windows 10 Pro (10.0.16299 Build 16299)

Does this issue occur when all extensions are disabled?: Yes

I managed to capture a couple of dump files from the process during high memory usage (but, I think, while on its way down, not up). They're available [here](https://drive.google.com/file/d/1KU9Cj9cHKEakLuz2_LLZtONqfh5aGSA7/view?usp=sharing) at least until someone from the team has said you have them locally, and/or you don't need them.

**Comment by Tyriar** [comment]
@tlycken can you run `code --status` and paste in the output during this state?

**Comment by tlycken** [comment]
I don't seem to be able to time it to capture memory usage when it's at its absolute worst - it swings back and forth between all my RAM and just a couple of hundred megs, but it consistently seems to be the `gpu-process` that eats the most. (It's probably coincidental, but I even get the feeling that triggering the status check can temporarily bring resource usage down...)

```
$ code --status
Collecting CPU and memory information. This might take a couple of seconds.

Version:          Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS Version:       Windows_NT x64 10.0.16299
CPUs:             Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2794)
Memory (System):  15.91GB (0.01GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:\Program Files\Microsoft VS Code\Code.exe

CPU %   Mem MB     PID  Process
    0        4   23924  code main
    0        0    7540     shared-process
    3     1894   10204     gpu-process
    0       19   19128     window (namerd.yml - bth (Workspace) - Visual Studio Code)
    0        0   14048       electron-crash-reporter
    0        1   16496       terminal
    0        1    2220         winpty-process
    0        2    5192           C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "& 'C:\Users\tomas\.vscode\extensions\ms-vscode.powe
rshell-1.6.0\scripts\Start-EditorServices.ps1' -EditorServicesVersion '1.6.0' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.6.0' -AdditionalModules @('PowerShellEd
itorServices.VSCode') -BundledModulesPath 'C:\Users\tomas\.vscode\extensions\ms-vscode.powershell-1.6.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\tomas\.vscode\extensions\ms-vscod
e.powershell-1.6.0\logs\1519654372-e79c5db3-dcf0-4267-aea4-e43dcb9b8bae1519654367829\EditorServices.log' -SessionDetailsPath 'C:\Users\tomas\.vscode\extensions\ms-vscode.powershell-1.6.0\sessions\PSES-VS
Code-23924-245555' -FeatureFlags @()"
    0        1   13688           console-window-host (Windows internal process)
    0        0   21220       extensionHost
    0        1    9280         electron_node server.js
    0        1   15196         electron_node server.js
    0        1   24900       watcherService

Workspace Stats:
|  Window (namerd.yml - bth (Workspace) - Visual Studio Code)
|    Folder (bth-backend): 35 files
|      File types: yml(10) js(5) json(3) sh(3) dtab(2) ps1(2) md(2)
|                  gitattributes(1) dockerignore(1) dockerfile(1)
|      Conf files: package.json(1)
```

**Comment by Tyriar** [comment]
@tlycken I can't seem to reproduce running `tree` on Windows. What sort of command are you running? Also do you know what type of GPU your computer has?

**Comment by tlycken** [comment]
@Tyriar I was working with the Azure CLI and with kubectl when I started noticing the problems, but I'm not sure if they're the only commands that cause them. I did notice though that I could keep using PowerShell and/or Bash on WSL outside of VS Code and stay in my workflow, so it's not _only_ the external command.

The computer where I've had problems is a Macbook Pro (early 2015) running Windows on Boot camp. It's at work (and I'm home) at the moment, so I'll investigate that more tomorrow, but I'll see if I can reproduce on my 2014 Lenovo Thinkpad Carbon X1 at home now. Will test more on the Macbook tomorrow and get back to you.

**Comment by tlycken** [comment]
@Tyriar This has happened now a number of times over the past week, with no common traits of the commands I've been using. Sometime's it's `docker` or `kubectl`, sometimes it's `git` or `dotnet`. Sometimes it takes a while (> 30 minutes) before I see it the first time, sometimes it begins with the first or second command I issue.

I realize this isn't much to go on, but I don't really know how to provide more information. Are there any more diagnostics I can run while it happens other than `code --status`? Let me know how I can help and I'll do my best.

**Comment by Tyriar** [comment]
@tlycken does any change happen when you close all windows and run `code --disable-gpu`?

Normally there are problems in VM but as I understand boot camp enables dual booting on a mac. My only guess right now is that it's another case of https://github.com/Microsoft/vscode/issues/36913, probably related to the integrated GPU somehow.

**Comment by tlycken** [comment]
Hum - I do tend to toggle the terminal size quite a lot when I work with it, and that seems to be a trigger in the linked issue. I'll try to use that to repro tomorrow, as well as testing if `--disable-gpu` makes any difference.

If it's related to running under boot camp, that would also explain why I can't reproduce on my laptop at home.

**Comment by tlycken** [comment]
@Tyriar [This comment](https://github.com/Microsoft/vscode/issues/36913#issuecomment-365761511) on #36913 led me to a way to reproduce this reliably on my Macbook:

1. Open a Code window
2. Open the integrated terminal
3. Maximize panel size (`View: Toggle Maximized Panel` in the command palette)
4. Type anything in the terminal

If I start `code --disable-gpu` the problem is gone.

**Comment by Tyriar** [comment]
@tlycken I think we can probably roll this into that issue then.
