### ISSUE TITLE
Please install [luacheck](https://github.com/mpeterv/luacheck

### ISSUE THREAD

**Issue by AnotherWTF** [Microsoft/vscode#44420]
### Issue Type
Bug

### Description

I see this error when opening a LUA file but this particular extension doesn't seem to be available in the recommended extensions. It was in the past because I had it installed before. I had to rebuild my system and lost my previous setup.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|7.98GB (4.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.1.5
vscode-luacheck|dwe|0.1.2
json-tools|eri|1.0.2
beautify|Hoo|1.3.0
Lua|key|0.0.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.14.0
vscode-lua|tri|0.11.0

</details>
Reproduces only with extensions

**Comment by ramya-rao-a** [comment]
@dbaeumer We dont recommend any extensions for lua.

I believe the error/notification is coming from one of the lua extension that the user has installed.

@AnotherWTF if you still see this error, please log the issue in the repo for the lua extensions that you use.
