### ISSUE TITLE
Ctrl+Del in Git Comment deletes from code editor

### ISSUE THREAD

**Issue by brianmorrison-me** [Microsoft/vscode#44425]
### Issue Type
Bug

### Description

If I am entering a comment to commit code, and I Ctrl+Del to delete per word, the comment isn't affected, yet the code in the editor where my cursor was last positioned starts to delete. Beginning to type again enters text into the commit comment field.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.88GB (7.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.6
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.3.0
output-colorizer|IBM|0.1.2
cisco|jam|1.0.0
vscode-colorize|kam|0.6.16
node-module-intellisense|lei|1.5.0
Angular-BeastCode|Mik|5.2.15
vscode-exec-node|mir|0.5.0
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
PowerShell|ms-|1.6.0
vs-keybindings|ms-|0.1.7
sqltools|mtx|0.12.0
material-icon-theme|PKi|3.2.3

(6 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
> Reproduces only with extensions

Try to figure out which extension does this by selectively disabling them one by one.
