### ISSUE TITLE
Add a post install script to remove the legacy symlink

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4442]
.deb: https://github.com/Microsoft/vscode/commit/b6486f7ddf812aa88ba5d2df961ff5d99029f2ad

Still need to do .rpm

**Comment by Tyriar** [comment]
How to: http://fedoraproject.org/wiki/How_to_create_an_RPM_package#Scriptlets

**Comment by joaomoreno** [comment]
Not sure how to verify this.

**Comment by Tyriar** [comment]
Verify by creating the symlink/file we previously recommended creating at `/usr/local/bin/code`, install the rpm and make sure `/usr/local/bin/code` no longer exists.
