### ISSUE TITLE
Unable to use debug configs within user settings

### ISSUE THREAD

**Issue by johnstew** [Microsoft/vscode#44423]
As the title suggests I am unable to use any of my debug configurations from within my workspace currently. Repro steps and screenshots below hopefully provide some context. Thank you!

- VSCode Version: 1.20.1
- OS Version: OS X 10.11.6 (El Capitan)

Steps to Reproduce:

1. Open VSCode Workspace
```
code my-ws.code-workspace
```
2. Open debugger and select a debug config from my user settings option.

Example: Attach to Node.js App
![screen shot 2018-02-26 at 10 38 39 am](https://user-images.githubusercontent.com/2146973/36679490-589ed5ac-1ae1-11e8-8c5f-cdca5fe9715c.png)

I get the following message:
![screen shot 2018-02-26 at 10 38 52 am](https://user-images.githubusercontent.com/2146973/36679538-740e4c6e-1ae1-11e8-878d-74cc700ab6e2.png)

Notes:
- Tried this outside of a workspace and it worked just fine.
- My workspace has 5 folders in it currently.
- If I create a `.vscode` folder and include a config there. It works just fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This should work with latest vscode insiders, please try it there and let us know if it works

**Comment by johnstew** [comment]
@isidorn I'll give this a try on vscode insiders and let you know. Thank you!
