### ISSUE TITLE
Not possible to use JS "let" keyword in debug console  when debugging Node

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#44427]
_From: https://www.reddit.com/r/vscode/comments/7zzie8/using_the_js_let_keyword_in_debugger_gives/_

What is the reason that the JS let keyword doesn't work in the VS Code debugger? I have just created a new file in an otherwise empty folder and placed a breakpoint on the first and only line in the app.js file.

As you can see in the screenshot below declaring variables with var works in the debugger. But not with the let keyword. Please note the ReferenceError in the screenshot.

https://imgur.com/7nCj5gB

For reference, let works correctly outside VS Code from the command line debugger (inspect) as shown here:

```
C:\temp2\test>node inspect app.js
< Debugger listening on ws://127.0.0.1:9229/3889c5f7-b722-401f-a1f8-2161d51d85cf
< For help see https://nodejs.org/en/docs/inspector
Break on start in app.js:1
> 1 (function (exports, require, module, __filename, __dirname) { var a = 1
  2
  3 });
debug> var b = 1
debug> b
1
debug> let c = 1
debug> c
1
debug>
```

Why goesn't let work inside the VS Code debugger? What can I do to make it work? I've tried with both Node v9.6.1 and the older LTS version.

Apparently this works for a friend in his VS Code. Am I doing something wrong?

**Comment by weinand** [comment]
I have no idea why "let" or "const" have no effect (but are not flagged as errors).
@roblourens do you have any idea?

**Comment by roblourens** [comment]
It's up to the runtime. Same in CDT. Works if you are not at a breakpoint. 

![image](https://user-images.githubusercontent.com/323878/36779111-39f78bbc-1cb2-11e8-9753-05bfee6227b8.png)

Very old issue I filed: https://bugs.chromium.org/p/chromium/issues/detail?id=655789&can=4&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

https://github.com/Microsoft/vscode-chrome-debug-core/issues/116

**Comment by weinand** [comment]
But it is still strange why it works in node's built-in debugger.

**Comment by johanrex** [comment]
Perhaps there is a difference when one places a breakpoint. The node example output was indeed from the debugger but not from a breakpoint.

**Comment by roblourens** [comment]
I don't think it works in `node inspect` either. When you just type code into the cli it's executing it in a new repl, not in the context of the program. You have to use `exec()`. If I use that, I get the same behavior.

```
$ node inspect app.js
< Debugger listening on ws://127.0.0.1:9229/d122593b-f7ce-446a-a770-4100eaad042a
< For help see https://nodejs.org/en/docs/inspector
< Debugger attached.
Break on start in app.js:1
> 1 (function (exports, require, module, __filename, __dirname) { var a = 1;
  2 });
debug> s
break in app.js:1
> 1 (function (exports, require, module, __filename, __dirname) { var a = 1;
  2 });
debug> s
break in app.js:2
  1 (function (exports, require, module, __filename, __dirname) { var a = 1;
> 2 });
debug> a
repl:1
a
^

ReferenceError: a is not defined
    at repl:1:1
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:120:6)
    at REPLServer.controlEval (node-inspect/lib/internal/inspect_repl.js:521:25)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:468:10)
    at emitOne (events.js:116:13)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
debug> exec('a')
1
debug> exec('let b = 2')
undefined
debug> exec('b')
ReferenceError: b is not defined
    at eval (eval at <anonymous> (/Users/roblou/code/vscode-node-debug2/testapp/app.js:2:1), <anonymous>:1:1)
    at Object.<anonymous> (/Users/roblou/code/vscode-node-debug2/testapp/app.js:2:1)
    at Module._compile (module.js:640:14)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
debug>
```
