### ISSUE TITLE
Allow search by workspace folder

### ISSUE THREAD

**Issue by xorbis** [Microsoft/vscode#44437]
This is a feature request to allow searching in a workspace's folder instead of having to retype ./myfolder in the "files to include" section of the search sidebar.

Probably a dropdown with recent and known search and workspace folders to quickly switch where the search will occur.

The issue appears when using a workspace with multiple folders and many files (even when node_modules is ignored). In order to make search faster, it is preferable to limit it to a subfolder.

![capture](https://user-images.githubusercontent.com/1229205/36692166-5dd10a58-1b05-11e8-872b-b8823deb97f5.PNG)

**Comment by roblourens** [comment]
You can right click on a folder in the File Explorer and use "Find in Files". Does that help?

Otherwise a dropdown or something similar would be covered by https://github.com/Microsoft/vscode/issues/20530

**Comment by xorbis** [comment]
Sorry for the duplicate and thanks a lot for the tip.
