### ISSUE TITLE
Windows are opening on the wrong display

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#44434]
Issue Type: Bug

This is regression.

I work with two displays. Display 1 is considered by the OS the primary display. When all workbench windows are open on Display 2 and I open a new workbench window, it is now opened on Display 1 rather than Display 2 (as it used to).

VS Code version: Code - Insiders 1.21.0-insider (903169966590cd236c5016cdc774875215d31765, 2018-02-26T06:08:49.568Z)
OS version: Darwin x64 16.7.0

Reproduces without extensions

**Comment by bpasero** [comment]
@kieferrm I cannot reproduce and there has been no code changes that I am aware of that could have an impact.

Here is what I do:
* open the lid of the macbook to have a second display
* the macbook display is the primary display
* move vscode to second display
* hit File > New Window
* window opens as expected on display 2
* move vscode window to primary display (laptop)
* hit File > New Window
* window opens as expected on display 1

What are you doing differently?

**Comment by kieferrm** [comment]
That seems to be the same. My setup:

<img width="333" alt="screen shot 2018-02-27 at 6 13 55 pm" src="https://user-images.githubusercontent.com/4674940/36766270-06f268b8-1bea-11e8-80aa-d2a3cdc083f4.png">

All windows open pinned with their top right corner to the top right corner of the built-in display.  No matter what I do. It's the same for `New Window` or when I restarted Code after I moved all windows to the large external display.

**Comment by bpasero** [comment]
@kieferrm time to debug, does it reproduce when you run "out of sources"?

**Comment by kieferrm** [comment]
When running from source everything is fine. I'll debug insiders to see what the difference is.

**Comment by bpasero** [comment]
Any luck?

**Comment by bpasero** [comment]
@kieferrm I can still not reproduce. Can you try to build a version of Code without minified sources, then we could start to add some console logs. Just run "`gulp vscode-darwin`" and wait until you get the drop in `VSCode-darwin` folder.

**Comment by kieferrm** [comment]
I don't expect you to be able to reproduce... Since I can only reproduce with insiders even with exactly the same source.

I created production insider builds with log information (pls see kieferrm/debugMain branch).

I ran the following experiment with insiders and from source:
- start both apps
- have exactly one workbench window in each app
- make the workbench windows the same size
- place them on the same location on the secondary display
- close both apps
- restart one after the other

Then I opened a new window in each app. (Since insiders opened the startup workbench window on the wrong display I moved it back to overlay with the workbench window from the source version before I opened the new window.)

Attached files show you the log output about window state and display. Same same in both... So it's not the information we pass into `new BrowserWindow`.

[source.txt](https://github.com/Microsoft/vscode/files/1823445/source.txt)
[insiders.txt](https://github.com/Microsoft/vscode/files/1823446/insiders.txt)

**Comment by bpasero** [comment]
@kieferrm you could add more logging around [`validateWindowState`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L708). That is basically the place where we take the state that was previously determined and validate that it makes sense. Maybe some of the validation logic thinks the bounds are wrong and falls back to the default state.

**Comment by bpasero** [comment]
@kieferrm that is weird, I have no explanation for that behaviour.

**Comment by bpasero** [comment]
@kieferrm interestingly I saw this issue on Windows just now and it was related to the fact that I had some code to compute the optimal position of the new window to open and that code was resulting in non-absolute numbers in cases where the monitor bounds are actually uneven. I fixed that via https://github.com/Microsoft/vscode/commit/96461c968cffb2f4d44679c156c6a52cf22f37b4. Maybe you could check your display bounds to see if this could be the same issue.

**Comment by kieferrm** [comment]
Not here. Everything looks even :-)
