### ISSUE TITLE
Markdown show preview to side to does re-show an existing preview

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44430]
Issue Type: Bug

1. Open markdown preview to side.
2. In second group, open a new editor so that the preview in a background tab
3. Back in the original md document, run open preview to side again

**Expected**
Shows the existing webview.

**Actual**
Does not. Preview remains in background tab

Broken by #44307 

VS Code version: Code - Insiders 1.21.0-insider (903169966590cd236c5016cdc774875215d31765, 2018-02-26T06:08:49.568Z)
OS version: Darwin x64 17.4.0

Reproduces only with extensions

**Comment by aeschli** [comment]
I still see the bug in Version 1.21.0-insider
Commit 9a04587cc6b42c332609a08bfd7e2dbeac592c21
Date 2018-03-01T06:47:39.037Z

![markdown-opentoside](https://user-images.githubusercontent.com/6461412/36855475-d7e4bc98-1d73-11e8-829d-87ed13bb4912.gif)

**Comment by mjbvz** [comment]
Fixed by 02bd0a10e52e5bc6e929585a506e2e3770ed7f5c
