### ISSUE TITLE
VS Code crashing

### ISSUE THREAD

**Issue by prodigynelson** [Microsoft/vscode#44439]
- VSCode Version: 1.20.1 (1.20.1)
OS Version: Mac OS X 10.12.6 (16G29)

Steps to Reproduce:
No idea. Hard to find reproducible pattern that causes crash.
[Potentially related issue](https://github.com/Microsoft/vscode/issues/43948)

Does this issue occur when all extensions are disabled?: Yes/No
Yes
[ Pastebin of error log](https://pastebin.com/MpnEhFQZ)

**Comment by tsalinger** [comment]
Please add the log to the issue that you are referring to.

**Comment by prodigynelson** [comment]
@tsalinger I added the log in the pastebin link, didn't want to clutter up the github issue
