### ISSUE TITLE
Mac: after native crash, sometimes application disappears from dock

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4443]
- VSCode Version: 0.10.12-alpha
- OS Version: MAC OS X EI captian (Version 10.11.2)

Steps to Reproduce:

1.  launch app and play around help menu to make application to be crashed (current behavior) or try to perform any action which makes VSCode to be crashed on MAC.
2. Once you get the alert window for crash click on "Reopen" button and verify application behavior.

Actual: 
1. VSCode re-launched successfully but it is not displaying in the active program list at the bottom right corner where all the active programs are listed.
![image](https://cloud.githubusercontent.com/assets/17735796/13892695/5bb66534-ed16-11e5-8756-78ae41f72e50.png)

2. Menu bar at the top is not changing according to VSCode so MAC is unable to recognize VSCode active session. Menu bar items are displaying for the last active window though the focus is on VScode. In my case it was "Safari".
Note: I am not certain if this is the common behavior on MAC for crashed app.

![image](https://cloud.githubusercontent.com/assets/17735796/13892624/e44c1f0c-ed15-11e5-9ee9-3a07fb016b82.png)
3. When I try to uninstall app, it is keep throwing pop-up that the app is running and can't trash. But there is no active session anywhere. I observed that the app stuck with Finder and user has to forcefully close finder first. After forcefully closing finder and re-launching VSCode , it is working as expected.

**Comment by bpasero** [comment]
Have seen this too, might be a bug in Electron/Mac.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4899
