### ISSUE TITLE
iTerm2 like images displaying on the integrated terminal

### ISSUE THREAD

**Issue by ebraminio** [microsoft/vscode#44436]
iTerm2 has a nice feature http://iterm2.com/documentation-images.html that can display images,

    printf "\n\033]1337;File=;inline=1:`cat a.png | base64`\a\n"`
![screen shot 2018-02-26 at 11 16 39 pm](https://user-images.githubusercontent.com/833473/36691672-389808c2-1b4b-11e8-8f47-ff094a020b54.png)

I am using the feature for the development of a library which is used on many different platforms including Chrome thus VSCode also, [harfbuzz](https://github.com/harfbuzz/harfbuzz/commit/6c844ae8e89f52f5f40eace66bb987544fc316e3), it would be nice if VSCode could provide the feature also :)

**Comment by DonJayamanne** [comment]
VS Code uses xterm.js to create the terminal. 
The same issue was raised in there https://github.com/xtermjs/xterm.js/issues/614

**Comment by ebraminio** [comment]
There is a patch for this here https://github.com/xtermjs/xterm.js/pull/1577/

**Comment by Tyriar** [comment]
Let's track this in the xterm.js repo
