### ISSUE TITLE
VSCE: support "Language Packs" category

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#44431]
per https://github.com/Microsoft/vscode/issues/43701 do we need to do anything in VSCE to support/validate the new `Language Packs` category in `package.json`?

**Comment by joaomoreno** [comment]
Nothing to be done in VSCE. But the change doesn't seem to be available in the service yet:

```
Error: The category 'Language Packs' is not available in language 'en-us'.
```

**Comment by chrisdias** [comment]
yes, the marketplace team knows about this.

cc @seanmcbreen
