### ISSUE TITLE
Come up with a better solution for sizing the terminal margins

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44435]
See https://github.com/Microsoft/vscode/issues/44154

@joaomoreno maybe we should have `SplitView` add `first-view` and `last-view` classes?

**Comment by joaomoreno** [comment]
Let's try to keep DOM order, so you would be able to use [`last-of-type`](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-of-type), would that work?

**Comment by Tyriar** [comment]
@joaomoreno that was my first solution, "type" here means element type though, and the order of the sashes and split view views is not fixed. Typically it is split view view, sash, split view view sash, but when you remove an item multiple sashes can be at the end.

**Comment by joaomoreno** [comment]
How about we put the views and the sashes into two different containers?

**Comment by Tyriar** [comment]
@joaomoreno that would work too :+1:
