### ISSUE TITLE
HTML within markdown is incorrectly highlighted as markdown

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4444]
Content within a HTML tag in markdown is HTML, not Markdown:

![image](https://cloud.githubusercontent.com/assets/2193314/13895465/ad6add6e-ed30-11e5-90e4-a96e60cbbeca.png)

**Comment by bpasero** [comment]
I doubt we still support this with our new markdown extension, but I let @kieferrm comment.

**Comment by Tyriar** [comment]
Fixed :+1: 

![image](https://cloud.githubusercontent.com/assets/2193314/16129743/e32a34ce-33ba-11e6-91b1-89f5c817ab9f.png)
