### ISSUE TITLE
Debugging with useWSL does not switch desired workspace folder

### ISSUE THREAD

**Issue by alanosman** [microsoft/vscode#44451]
Hello team,

I have been searching for the right way to set my project to start in a particular folder when I debug.  I used WSL and have my source code mounted through `/mnt/d/<source code folders>` and use symbolic linked directories from my home folder to get to the projects I work on from inside Ubuntu. 

For example, my home directory is `/home/aosman/` and a subfolder would be `elastc-workers`.  

When I run the debugger on a project that is in that subfolder, it fails to start because it cannot find the starting module. 

This is the error:
```
C:\WINDOWS\System32\bash.exe -ic 'node --inspect=40723 --debug-brk queue.js' 
Mon Feb 26 17:32:23 STD 2018
Enviornment is development
Debugger listening on ws://127.0.0.1:40723/b6382df1-49ce-4329-909c-6e7fdd4dc90c
Debugger attached.
(node:13082) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
module.js:559
    throw err;
    ^
Error: Cannot find module '/mnt/d/elastc-app/queue.js'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
Waiting for the debugger to disconnect...
Error: Cannot find module '/mnt/d/elastc-app/queue.js'
module.js:557
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
```

Here's my launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "name": "Run Worker",
            "localRoot": null,
            "program": "${workspaceFolder}\\queue.js",
            "useWSL": true,
            "outputCapture": "std",
            "sourceMaps": true
        }
    ]
}
```

my workspace settings are:
```
{
	"folders": [
		{
			"path": "elastc-workers"
		}
	],
	"settings": {}
}
```

I've tried using the `cwd` command but that did not do it.  How am I supposed to make it switch to the folder I need?

**Comment by weinand** [comment]
"useWSL" is not yet supported in multi-root workspaces.

**Comment by alanosman** [comment]
ah ha.. thanks @weinand! I got you twice in one day :-)   Anyway that would explain it.  Am I the first to request it or is it in the pipeline to get done?

**Comment by weinand** [comment]
Yes you are the first.

**Comment by alanosman** [comment]
Oh wow - I guess I am at the cutting edge.. :-)  thanks again.

**Comment by alanosman** [comment]
btw, if this is going in as a feature request, can I add a minor detail.  When using WSL and workspaceFolders, it would be grand if we could find a way to also launch the bash terminal in the same folder as defined by the workspace.

A simple issue of `cd ${workspaceFolder} would take care of that.

**Comment by lfurzewaddock** [comment]
I recently created a VS Code extension: [WSL workspaceFolder](https://marketplace.visualstudio.com/items?itemName=lfurzewaddock.vscode-wsl-workspacefolder), which may help.

**Comment by offero** [comment]
> I recently created a VS Code extension: [WSL workspaceFolder](https://marketplace.visualstudio.com/items?itemName=lfurzewaddock.vscode-wsl-workspacefolder), which may help.

@lfurzewaddock I am getting a similar error when attaching. I do have a multi-root workspace going.

launch.json:
```
        {
          "type": "node",
          "request": "attach",
          "name": "Attach to Process",
          "address": "localhost",
          "port": 5858,
          "localRoot": "${workspaceFolder}",
          "remoteRoot": "${command:extension.vscode-wsl-workspaceFolder}"
        }
```

I run `node --inspect-brk=5858 ./node_modules/jest/bin/jest` myself in WSL and when I try to attach I get...

`Running the contributed command:'extension.vscode-wsl-workspaceFolder' failed`

**Comment by G1itcher** [comment]
Would like to leave my vote here for a inbuilt VSCode solution to this. The extension linked above doesn't work at all for me. For now I'm making do with opening the projects I need to debug in their own VSCode instances, but that's hardly ideal.

**Comment by weinand** [comment]
With the arrival of the "Remote - WSL" extension the "useWSL" attribute is deprecated.
No further work will happen to address "useWSL" issues.
