### ISSUE TITLE
wrong spdlog build location in Pregenerated Javascript Extension builder

### ISSUE THREAD

**Issue by Kowus** [Microsoft/vscode#44458]
### Issue Type
Bug

### Description

pregenerated code returns error

    Error: Cannot find module '/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/spdlog/build/spdlog.node'
this seems quite old as VScode now uses the path

    '/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/spdlog/build/Release/spdlog.node'

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

**Comment by Kowus** [comment]
Issue is not covered in any of those links

**Comment by mjbvz** [comment]
Sorry, it is unclear how to reproduce this problem. Please provide step by step instructions that explain what triggers this error
