### ISSUE TITLE
Test Use Electron ASAR to optimize file system access

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#44455]
Test plan item for #36997

Complexity: 3

- [x] macOS: @Tyriar 
- [x] linux: @jrieken 
- [x] windows: @ramya-rao-a 

We have had several issues with using `node_modules.asar`. Please verify:
- the installation directory contains `node_modules.asar` and `node_modules.asar.unpacked` and no longer `node_modules`
- you can use VS Code functionality which involves native node modules or spawning processes with files included in node modules: e.g. winpty for terminal, rg for searching.

**Comment by alexandrudima** [comment]
@Tyriar I think we should close only once @ramya-rao-a also tests.

**Comment by Tyriar** [comment]
Opps :sweat_smile:
