### ISSUE TITLE
OSError: raw write() returned invalid length 44 (should have been between 0 and 22)

### ISSUE THREAD

**Issue by Box-Of-Hats** [Microsoft/vscode#44456]
- VSCode Version: 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows 10 (Build 16299.248)

Steps to Reproduce:

1. Output text to the terminal within VS Code (such as a print statement in python).
Occurs with both cmd and powershell.
Seems to occur randomly and with no particular strings triggering the issue. Occurs when running my own scripts (python 3) and when running other programs within the terminal. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I'm guessing this is related to https://github.com/Microsoft/vscode/issues/36630
