### ISSUE TITLE
Test: "runtimeVersion" support for "nvs" Node Version System

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#44452]
Ref https://github.com/Microsoft/vscode-node-debug/pull/171:

Complexity: 3

- [x] macOS: @kieferrm 
- [x] linux: @chrmarti 
- [x] windows: @mjbvz 

After adding "nvm" support in the last month, we now got a PR that added support for "nvs". 
If you are using "nvs" to manage your node.js versions it is now possible to specify a "runtimeVersion" attribute in a launch configuration for selecting a specific version of node.js.

Setup:
- Make sure to use "nvs" on your platform
- make sure to have those node.js versions installed that you want to use with the "runtimeVersion" attribute. E.g. run "nvs install 7.10.1" from the integrated terminal.

Verify that the specified version of node.js is correctly used for the launch session. 

Here is an example launch config:
```
{
	"type": "node",
	"request": "launch",
	"name": "Launch test",
	"runtimeVersion": "7.10.1",
	"program": "${workspaceFolder}/test.js"
}
```

**Comment by sandy081** [comment]
@weinand This is not tagged as `testplan-item` and was missed in assignments.

**Comment by weinand** [comment]
oops, sorry.

**Comment by weinand** [comment]
@sandy081 Could you please assign it? Thanks!

**Comment by sandy081** [comment]
Yeah doing so.

**Comment by chrmarti** [comment]
Cannot test due to #44640. I'll wait for a fix before continuing with testing.

**Comment by weinand** [comment]
@chrmarti you are not affected by #44640 because that's only a problem on Windows and not on linux.
You were probably affected by https://github.com/Microsoft/vscode/issues/44744 (Which should be fixed in the next Insiders).
The workaround for the current Insiders is to launch VS Code from the terminal.

**Comment by kieferrm** [comment]
Works like a charm on macOS.
