### ISSUE TITLE
VSCode SEARCH cannot work with regexp "([a-zA-Z]{1})[\n\r]\{"

### ISSUE THREAD

**Issue by SubmarineX** [Microsoft/vscode#44468]
### Issue Type
Bug

### Description

I just format C++ code that move '{' in the second line to end of the first line.
For example:
  class MyClass
  {
    // blablabla
  }
When use regexp "([a-zA-Z]{1})[\n\r]\{", the result should be: 
"s
{", rather than  "lass MyClas". 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

Reproduces only with extensions

**Comment by tsalinger** [comment]
This is not a VS Code specific issue. Please open an issue in the extension's [repository](https://github.com/Microsoft/vscode-cpptools/issues)

**Comment by SubmarineX** [comment]
It just is a VSCode specific issue. 
Reproduce it that:

1. create a text file
2. type some characters, for example:
 `abcd`
`{`
3. Search (open with Ctrl + Shift + F) with regular expression `[a-zA-Z][\n\r]\{`
You can find that:


![default](https://user-images.githubusercontent.com/2227182/36727089-f2a4bf66-1bf6-11e8-8505-6ae3bd1ea77f.png)
