### ISSUE TITLE
cursor position not correct when move

### ISSUE THREAD

**Issue by fthmko** [microsoft/vscode#44465]
### Issue Type
Bug

### Description

steps:
1.  a multiline doc,  with cursor at  line 1 and col 3(or any >1), like below
```
     1# ab|cdefg
     2# abcdefg
```
2.  press key UP, the cursor whill go to col 1, like below
```
     1# |abcdefg
     2# abcdefg
```
3. now press key DOWN, the cursor went to line 2 and col 3, not col 1 as expected
```
     1# abcdefg
     2# ab|cdefg
```

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.10.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|Load (avg)|0, 0, 1|
|Memory (System)|3.66GB (0.39GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-enhanced|shd|0.3.2

</details>
Reproduces without extensions

**Comment by dbaeumer** [comment]
@alexdima what is the expected behavior. It is not clear to me from the steps

**Comment by alexdima** [comment]
Verification steps:

1. Have something like:
![image](https://user-images.githubusercontent.com/5047891/78245306-8e300300-74e7-11ea-877d-92978aaa2c71.png)

2. Press up twice. It goes to the first column, but it remembers the horizontal offset, such that when you press down, it returns to the column 5:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/78245454-cdf6ea80-74e7-11ea-92c0-687fdcda7527.gif)

3. But if up is pressed 3 times, as in one more time, then the horizontal offset is reset:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/78245542-ef57d680-74e7-11ea-9738-3029c0e50361.gif)
