### ISSUE TITLE
终端无法唤起

### ISSUE THREAD

**Issue by l-ennon** [Microsoft/vscode#44467]
### Issue Type
Bug

### Description

终端无法输入，更新后就出现这个问题

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|7.88GB (2.78GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
stylus|Ala|0.0.4
vscode-javascript-snippets|cod|1.0.0
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
beautify|Hoo|1.3.0
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
vscode-icons|rob|7.20.0
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
Please describe exactly what is going wrong and the steps to reproduce this issue. Here are some suggestions on how to file an actionable issue: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests
