### ISSUE TITLE
In .gitignore: ".vscode/*.db" should be ".vscode/*.db*"

### ISSUE THREAD

**Issue by ssilverman** [Microsoft/vscode#44474]
VSCode Version: 1.120.1

The .gitignore file is modified to include ".vscode/&ast;.db". Instead, because of the ".browse.c_cpp.db-shm" and ".browse.c_cpp.db-wal" files, should the .gitignore contain ".vscode/&ast;.db&ast;"?

**Comment by tsalinger** [comment]
Please open an issue in the extension author's [repository](https://github.com/Microsoft/vscode-cpptools/issues)

**Comment by bobbrow** [comment]
@tsalinger, can you explain why you think this might be an extension issue?  Do extensions have any control over how the .gitignore is created?  We don't have any logic in the C++ extension that I'm aware of that does this.

**Comment by joaomoreno** [comment]
@ssilverman What `.gitignore` file? Is this a file in your repository? What makes you say this is an issue with VS Code? Didn't you author that file yourself?

**Comment by ssilverman** [comment]
It’s an existing file that VSCode modifies a certain way so that some .vscode config flies are ignored.

**Comment by joaomoreno** [comment]
As far as I know, VS Code doesn't modify that file in any way without it being the user's choice.

Please find out how you got that file generated and which application/extension did that. When you do, file that issue on that application/extension.

**Comment by ssilverman** [comment]
I generated a standard .gitignore file. VSCode always seem to add these lines:
```
.vscode/.browse.c_cpp.db*
.vscode/c_cpp_properties.json
.vscode/launch.json
```
The issue might be moot now, because I noticed that recently, it no longer adds `.vscode/*.db`. It now adds `.vscode/.browse.c_cpp.db*`.

**Comment by derSeddy** [comment]
I somewhat stumbled across this myself and I have PlatformIO installed, too, so I guess it has to do with that.
My original issue was that `.vscode/.browse.c_cpp.db*` is added automatically at every startup of vs code although I manually added `.vscode/.*`, which is quite annoying.

**Comment by joaomoreno** [comment]
Yes, it seems it is PlatformIO. https://github.com/platformio/platformio-vscode-ide/issues/30
