### ISSUE TITLE
Excluding files in a workspace (.code-workspace)

### ISSUE THREAD

**Issue by lostfields** [Microsoft/vscode#44476]
Is there any plans to support multi-folder workspace postfixing for file exluding? Right now, if I use "files.exclude" it will exclude all files of that type in all folders. It would be nice if we could hide files in one folder and keep them in another.

Maybe support postfixing of variables (like ${workspaceFolder:foldername}) in all places where those variables is used (may be like this allready but that may be extension specific?)

**Comment by bpasero** [comment]
@lostfields you can easily do that by configuring folder based settings. files.exclude is supported on that level.

**Comment by lostfields** [comment]
by adding it into .vscode folder? Problem is, that a workspace file (.code-workspace) may have settings that overrides global settings, and settings in .vscode folder overrides them again.

If I specify `"files.exclude": { "node_modules": true }` it will hide node_modules from all workspace folders. 

Postfixing with foldername like `"${workspaceFolder:<foldername>}/node_modules": true` doesn't work. It doesn't work using relative paths either, like `"<foldername path>/node_modules": true`

I hate check-in .vscode folders but again, yes, you support it, kind of... wish code-workspace was a true workspace-file.
