### ISSUE TITLE
Why the terminal can't be used after the update（终端更新无法输入）

### ISSUE THREAD

**Issue by swey01** [Microsoft/vscode#44473]
Issue Type
Bug

Description
更新之后终端用不了了，怎么回事
Why the terminal can't be used after the update

VS Code Info
VS Code version: Code 1.20.1 (f88bbf9, 2018-02-13T15:34:36.336Z)
OS version: Windows x64 10.0.14393

![qq 20180227142611](https://user-images.githubusercontent.com/30410341/36713795-436874ce-1bca-11e8-947b-c696652d3bbf.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169
