### ISSUE TITLE
Toggle terminal shortcut causes typing symbols

### ISSUE THREAD

**Issue by bam** [Microsoft/vscode#44477]
- VSCode Version: 1.20.1 (1.20.1)
- OS Version: macOS 10.13.3 (17D102)

Steps to Reproduce:

1. Focus in code editor, terminal is hidden
2. Press "option+`" to toggle integrated terminal
3. Integrated terminal is shown, but it has "`" pre typed
<img width="89" alt="screen shot 2018-02-27 at 10 35 11" src="https://user-images.githubusercontent.com/2446302/36716053-f9018e04-1ba9-11e8-98a8-767e1b76a315.png">

And vice versa:
1. Terminal is active
2. Press "option+`" to toggle integrated terminal
3. Terminal is hidden, but in code editor appears "`"
<img width="140" alt="screen shot 2018-02-27 at 10 37 27" src="https://user-images.githubusercontent.com/2446302/36716132-3bffea66-1baa-11e8-9c01-33c99393a73a.png">
4. If I continue press "option+`" right after that (no changing focus etc.) it will type "`" and don't toggle terminal until I click somewhere or move cursor
<img width="224" alt="screen shot 2018-02-27 at 10 50 37" src="https://user-images.githubusercontent.com/2446302/36716643-1b5841ee-1bac-11e8-9c3d-a8a138c88977.png">

(screenshot's taken with disabled extensions)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bam** [comment]
After startup the Code it is another test case. Because of focusing terminal for the first time: terminal is shown, no pre typed symbols there, but because of leaving the focus in editor back-tick is typed in editor (while terminal is open)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/41024
