### ISSUE TITLE
The encoding "TAB" missed when peeking a reference in Java source code

### ISSUE THREAD

**Issue by MengJueM** [Microsoft/vscode#44475]
- VSCode Version: 1.193
- OS Version: macOs 10.13.3

Steps to Reproduce:

1. Open a `Java+Maven` based project;
2. Use `command + click` to peek a reference which is located in a JAR and the the source is downloaded by maven automatically;
3. A file with `.class` extension is opened in the VS code;
4. Try to change the encoding by click the "encoding TAB" in status bar, but the "TAB" is not existing;

Does this issue occur when all extensions are disabled?: Yes

**Comment by MengJueM** [comment]
![image](https://user-images.githubusercontent.com/2742842/36715248-601346c0-1bd0-11e8-813e-a1d9ef1dbe99.png)

**Comment by tsalinger** [comment]
Please open an issue in the extension authors [repository](https://github.com/redhat-developer/vscode-java)
