### ISSUE TITLE
Alway open new window vscode when run code from command line

### ISSUE THREAD

**Issue by tdchien** [Microsoft/vscode#44470]
### Issue Type
Bug

### Description

I have a problem when run vscode cli. When run "code" command from cmd on window 10, it alway open new window of vscode.
![img](http://g.recordit.co/W1Vyaj0XN5.gif)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|15.88GB (5.73GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Program Files\Microsoft VS Code\bin\..\resources\app\out\cli.js -v|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by tsalinger** [comment]
I cannot reproduce this behavior on Windows 10.
`code -v` should not start the app. Instead it should show the version as depicted in your attempt with the insiders version.
