### ISSUE TITLE
Let "open editors" space be more extendable

### ISSUE THREAD

**Issue by user3323** [microsoft/vscode#44478]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

As many files are open - as much maximum space you would have in "open editors" workspace.

![open editors space](https://user-images.githubusercontent.com/24613274/36717416-ae25b0ac-1ba6-11e8-9b2f-8047e46f01bd.gif)

Well, I don't like this boundary.
Let the user expand this "open editors" space as much, as he wants.

**Comment by isidorn** [comment]
This should be fine now

**Comment by isidorn** [comment]
@user3323 my mistake. Let's reopen
