### ISSUE TITLE
Terminal: Cursor position gets off after splitting

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#44481]
Testing #44446

Elementary OS Loki

After splitting, I often observe that the cursor positions become invalid.
- split the terminal several time
- focus in one of the terminal parts. Observe that the cursor is in the middle of some text

![terminal-cursor](https://user-images.githubusercontent.com/6461412/36718535-746d283a-1ba2-11e8-91a9-651d73f351b7.gif)

**Comment by Tyriar** [comment]
@aeschli I've had a bad time reproing this sort of issue in the past as I think it's shell dependent, does it happen when you just resize the window with a single terminal as well?

**Comment by aeschli** [comment]
@Tyriar Yes, it also can happen with a single terminal.
With the splitting, it's just very easy to reproduce for me.

**Comment by Tyriar** [comment]
@aeschli one last thing :smile: can you try repro in an external terminal and share your `$PS1`?

**Comment by aeschli** [comment]
`\[\e]0;$(print_title)\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$`

I haven't seen that in the terminal from ElementaryOS, but when using tmux I see similar things

**Comment by Tyriar** [comment]
I think this had the same root cause as https://github.com/Microsoft/vscode/issues/44662
