### ISSUE TITLE
Formatting code  failed

### ISSUE THREAD

**Issue by q269384828** [Microsoft/vscode#44480]
### Issue Type
Bug

### Description

Create a new html page. Copy an HTML fragment that has been written from body to script tag.use " ' " wrap and trim line feed and whitespace as a string;Then, prompt  syntas error and    Formatting code  failed.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.89GB (2.12GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
vscode-html-css|ecm|0.2.0
tortoise-svn|fan|0.1.1
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
jquery-snippets|Hri|1.0.0
vscode-icon-rotation|kri|1.0.4
code-beautifier|mic|1.7.2
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.1.0
vscode-css-peek|pra|2.1.0
open-in-browser|tec|1.1.0
file-size|zh9|0.1.2
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by aeschli** [comment]
@q269384828 Can you please add a small sample of the code with the snippet to paste?

**Comment by aeschli** [comment]
Closing due to lack of information
