### ISSUE TITLE
Promote ´to profile extensions´ message should be modal.

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#44488]
This message should not be an info message that disappears after some period, but an modal dialog.

![image](https://user-images.githubusercontent.com/172399/36720996-eab05f06-1ba9-11e8-94e3-fd5b90c2ce6f.png)

**Comment by bpasero** [comment]
@egamma it seems to me we do support to run without providing a port (e.g. `code --inspect-extensions` works for me). If so, we could leave this a notification message but add an action to reload the window with additional command line arguments. I think it should be possible, we just did something similar for the issue reporter: https://github.com/Microsoft/vscode/commit/d367f2f2ae044d377e369e6c67feb245d88b8eb5

**Comment by egamma** [comment]
@bpasero adding an action would work for me.

**Comment by jrieken** [comment]
Yeah, we did discuss the restart-action but dropped it in the face of recovery-release presure
