### ISSUE TITLE
Why open Unity3d project aways 300%+ cpu usage?

### ISSUE THREAD

**Issue by fishg** [Microsoft/vscode#4448]
- VSCode Version: 0.10.11
- OS Version:OS X 10.11.3

Steps to Reproduce:

1. use vscode open a c# solution which created by Unity3D
2. open some c# file in vscode
Your will see cpu usage is more than 300% when first load,it's expect. But if your switch to new c# file in the same project,the backend mono process will use more than 300% cpu again.

![qq20160319-0 2x](https://cloud.githubusercontent.com/assets/1423545/13896615/43c31960-edcd-11e5-9afc-11f2539b0ccc.png)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#442
