### ISSUE TITLE
Terminal: jumpy content when resizing split terminal 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#44485]
Testing #44446

- split a terminal in 3, move it to the right
- resize the last terminal
- middle terminal starts adjusting

![jumpy-terminal](https://user-images.githubusercontent.com/6461412/36719168-8bff7410-1ba4-11e8-8f53-aff4c388349c.gif)

**Comment by gushuro** [comment]
I can still see the content jumping when adjusting the middle terminal size from the top.

![term](https://user-images.githubusercontent.com/5607882/36819049-94be28f0-1c9c-11e8-87cf-ff139b416b6c.gif)

**Comment by Tyriar** [comment]
@gushuro this is as designed as the non bottom-terminals are now anchored to the top, inverting it would go back to the original report's behavior
