### ISSUE TITLE
Extension host terminated unexpectedly. Code:  3221225477

### ISSUE THREAD

**Issue by qkrtmddml** [Microsoft/vscode#44486]
- VSCode Version: 버전 1.20.1
커밋 f88bbf9137d24d36d968ea6b2911786bfe103002
날짜 2018-02-13T15:34:36.336Z
셸 1.7.9
렌더러 58.0.3029.110
노드 7.9.0
아키텍처 x64
- OS Version: windows 10

Steps to Reproduce:

1. run vscode
2. /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4172 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null

Does this issue occur when all extensions are disabled?: No I think php and git has problem
![default](https://user-images.githubusercontent.com/28629589/36719899-b1857abe-1be9-11e8-9d5f-f23842ff1448.png)

**Comment by joaomoreno** [comment]
Just to confirm, does it reproduce when you run

```
code --disable-extensions
```

?

**Comment by TonganJedi** [comment]
I ran Code with the --disable-extensions switch and I still get the error message. I do not have any folders or files loaded. Just an empty editor on the Welcome page.

**Comment by TonganJedi** [comment]
So here's an interesting wrinkle: I just rebooted my computer and now I'm not seeing the error. I just installed Code and did not reboot before launching it. Could this be something as silly as pathing information not being in-place from the install? Should VS Code require a system reboot before launching the first time?

**Comment by joaomoreno** [comment]
@TonganJedi Good to know it works for you.

@qkrtmddml Let me know the answer to my question.

**Comment by e1337us3r** [comment]
Hi. I have a similar issue. If I install any kind of extension(including official ones), I get this error. I don't get any errors if I run --disable-extensions.

**Comment by joaomoreno** [comment]
@e1337us3r Try to figure out which extension causes it, by disabling extensions one by one.

@qkrtmddml Let me know the answer to my question.

**Comment by e1337us3r** [comment]
@joaomoreno I did what you said. Literally, any extension causes this problem. Only way to not get this error is to not install any extensions.

**Comment by joaomoreno** [comment]
@e1337us3r If you fully reinstall Code, does it get fixed?
