### ISSUE TITLE
Unable to switch applications when focus is on VS Code

### ISSUE THREAD

**Issue by rvavrik** [Microsoft/vscode#44482]
### Issue Type
Bug

### Description

1) Connect to the Ubuntu 14.04.5 LTS (Gnome Classic 3.8.4) remotely using the TurboVNC server
2) Open the VS Code and an arbitrary application (e.g. terminal)
3) Put the focus on the VS Code window
4) Use Alt+Tab shortcut to switch to the other application window or alternatively, click on the other application in the taskbar
Actual result:
The focus is still on the VS Code window
Expected result:
The focus is switched to the other application window

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.4.0-112-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz (32 x 1328)|
|Load (avg)|2, 2, 1|
|Memory (System)|251.80GB (246.24GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
project-manager|ale|0.24.0
path-intellisense|chr|1.4.2
githistory|don|0.4.0
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-cudacpp|kri|0.1.1
vscode-todo-parser|min|1.9.1
python|ms-|2018.1.0
cpptools|ms-|0.15.0
vscode-code-outline|pat|0.0.13

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3451

**Comment by rvavrik** [comment]
The workaround provided in #3451 is not working for me. When I start the VS code from terminal with --verbose. the output starts with:
`[22771:0228/164210.811464:ERROR:gl_surface_glx.cc(406)] glxQueryVersion failed
[22771:0228/164210.811523:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
[22771:0228/164210.813764:ERROR:gpu_child_thread.cc(324)] Exiting GPU process due to errors during initialization
[main 4:42:11 PM] Starting VS Code
...
`

**Comment by Tyriar** [comment]
@rvavrik we don't really support remoting software at the moment. These issues typically have their roots in Chromium, not VS Code, and are too difficult to diagnose and resolve unfortunately.
