### ISSUE TITLE
Updating VS Code app doesn't have an icon

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#44494]
The updater app shows the default app icon in the windows task bar. It should show the VS Code icon (green for insider and blue for stable).

**Comment by dbaeumer** [comment]
Checked this morning and noticed the following:

- insider update up as a blue icon. Should be green.
- the app still has no icon for the upper left corner

**Comment by joaomoreno** [comment]
I'm not going to have a separate icon per flavour. We do the same for the CodeHelper.exe.

The window icon is interesting.
