### ISSUE TITLE
Search: expando button not themed for light theme

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44493]
Testing #44215

I am not having a good idea on the colors, but this looks a bit weird:

![image](https://user-images.githubusercontent.com/900690/36721928-8c00e324-1bac-11e8-9b88-f72f32c9dcde.png)

**Comment by roblourens** [comment]
Fixed in https://github.com/Microsoft/vscode/commit/b497448a8d96c165de785ac3a20058ac411ec090
