### ISSUE TITLE
Moving search between panel and sidebar does not preserve all input field state

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#44491]
Testing #44215

It looks like the search result is preserved when moving the search view between side bar and panel, but not what I have typed in the input fields.

**Comment by sbatten** [comment]
For me, I experienced 2 cases:
1) Update the setting by manually typing the json in the settings file.
    >In this case, the search input is preserved per location. For example. If I search "hello" in the sidebar, move it to the panel, search "goodbye", and then move it back to the sidebar, the contents will be "hello". If I move it back to the panel, they will be "goodbye".

2) Update the setting by using the pencil icon.
    >In this case, I first followed the steps above using method 1. The input text was then "primed" with "hello" and "goodbye". Next, I moved the search back and forth using the pencil icon without changing the input text. After the first move, every consecutive move replaces the text with "sidebar" and "panel". Opened #44637 for this part.

**Comment by roblourens** [comment]
@isidorn I added the "Toggle search view position" context menu item which makes this much more noticeable.

Are there two instances of the search view? Do you know what the problem is here?

**Comment by isidorn** [comment]
@roblourens there are no two instances of the search view - only one. I do not know what the problem is but I can investigate tomorrow.

**Comment by roblourens** [comment]
Debugging, I think there are two instances. `create` is called twice and on different instances.

**Comment by isidorn** [comment]
This sounds like a debt item I should tackle not in endgame week -> april

**Comment by isidorn** [comment]
I checked and I confess that I create the Search View twice.
However fixing this would rape all my api panel / viewlet api. Since they are currently completely independent and it is quite hard to share an object between them
Also this happens when the search is moved, if it is in one location all the time only one instance will get created (which is the most common use case)

Due to the above pushing to the backlog
