### ISSUE TITLE
Cannot set function breakpoint

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44495]
Issue Type: <b>Bug</b>

Testing #43836

Following the documentation on this, the function breakpoint did not work. Also note that in the screenshot the function breakpoint is shown as resolved, but when I add it while the program is running, it is shown as unresolved.

![image](https://user-images.githubusercontent.com/9205389/36721895-7698dc12-1bac-11e8-8e8d-e6525905c541.png)

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:09:52.377Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir tmp/user --extensions-dir tmp/ext|
|Screen Reader|no|
|VM|20%|

</details>Extensions: none
Reproduces without extensions

**Comment by isidorn** [comment]
@weinand can you please investigate if the backend is providing the expected data.

**Comment by weinand** [comment]
Please be aware of the limitations of function breakpoints: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_function-breakpoints

**Comment by chrmarti** [comment]
Retried with v6.11.3 and it didn't work. (This time the function breakpoint was shown as unconfirmed when I started debugging.)

**Comment by joaomoreno** [comment]
This also didn't work for me.

**Comment by weinand** [comment]
node.js versions >= 8.0 no longer support function breakpoints.

**Comment by isidorn** [comment]
@weinand should the adapter then return function breakpoints as `unverified`. Or it already does that but the UI is not respecting it?

**Comment by weinand** [comment]
for node.js >= 8 the adapter does not support function breakpoints so "supportsFunctionBreakpoints" is falsy.
VS Code should not send any functionBreakpoints.

for node.js < 8 the DA sends back Breakpoint with the "verified" property set to true, see:
https://github.com/Microsoft/vscode-node-debug/blob/602790fc530a89825bcc779b2f4cfbb249c8a199/src/node/nodeDebug.ts#L2121-L2127

**Comment by isidorn** [comment]
In the latest we properly show that the breakpoint is not resolved no matter when it is added. So imho this behaves fine now 
![screen shot 2018-09-18 at 16 33 29](https://user-images.githubusercontent.com/1926584/45694972-c0298080-bb60-11e8-8673-6d8515a4e1b9.png)
