### ISSUE TITLE
Notify user that a language pack install requires a vscode restart

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#44501]
Refs: #44426

If a user installs a language pack, he is required to restart vscode in order for this langugae pack to take effect.
I notice that in locale.json we have a message that a restart is required, however a user can easily miss that.

I would expect that:
* Every time a locale.json value changes there is a notication with an action to restart vscode
* Every time a language pack is installed the same notificaiton shows up

**Comment by dbaeumer** [comment]
@sandy081 since we now ship the LP we should look into this for May. Can you look into the extension viewlet ?

**Comment by sandy081** [comment]
@dbaeumer Restart on language pack installation message is already implemented in last milestone.

**Comment by sandy081** [comment]
@dbaeumer Do you want to show the prompt when the user changes the locale in `locale.json` also?

**Comment by dbaeumer** [comment]
I tweak the content of the file to make it more obvious that a restart is required. I would right now not spend to much time on it since it is a very rare user action.

**Comment by dbaeumer** [comment]
Let me know what you think.

**Comment by sandy081** [comment]
Makes sense to me

**Comment by dbaeumer** [comment]
Closing then. @isidorn please speak up if you feel strongly about it. The locale.json will look like this:

```js
{
   "locale": "de" // Changes will not take effect until VS Code has been restarted. 
}
```

**Comment by dbaeumer** [comment]
One additional things to mention. When VS Code prompts to install a language pack and you do it automatically restarts. So that case is covered.
