### ISSUE TITLE
Allow to open notifications center if there are no notifications

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#44509]
Testing https://github.com/Microsoft/vscode/issues/44319

When there are no notification the notification button in the status bar is disabled. Instead I think we should open the notification UI and tell the user that there are no notification. Major reason is that there is no good visual indication that the button in the status bar is disabled.

**Comment by will-stone** [comment]
I'm looking for a way to see the notification center so I can theme it so this would be awesome. You don't happen to know how to force a notification, do you?

**Comment by fabiospampinato** [comment]
@will-stone somebody published an [extension](https://marketplace.visualstudio.com/items?itemName=svipben.notification-tester) that does just that.

**Comment by will-stone** [comment]
@fabiospampinato awesome! Thanks for the find.
