### ISSUE TITLE
Built in: do not show version

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44502]
Testing https://github.com/Microsoft/vscode/issues/44361

I think we should not show the version string for built in extensions as they typically never change and most of them are at 0.1.0 even though they have been like that for years:

![image](https://user-images.githubusercontent.com/900690/36722533-1019efb0-1bae-11e8-9869-45d808dc427a.png)

**Comment by sandy081** [comment]
We have built in extensions from market place like debug. So showing version is helpful in such cases. Ideally, all extensions should be similar to debug extensions. 

![image](https://user-images.githubusercontent.com/10746682/36723634-21699cd6-1bb1-11e8-873f-ed5a98234413.png)

**Comment by bpasero** [comment]
@sandy081 then at least we should bump them to 1.0 or something and not leave them as 0.1.0.

**Comment by sandy081** [comment]
Ok, I would add this request to the issue #43978
