### ISSUE TITLE
Second breakpoint set not revealed in Breakpoints view

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44503]
Issue Type: <b>Bug</b>

Testing #43836

The Breakpoints view resizes when adding the first breakpoint, but not when adding the second. Clicking in the view then resizes it.

![feb-27-2018 11-01-21](https://user-images.githubusercontent.com/9205389/36722624-4a46b2e0-1bae-11e8-8ec1-d5cc565609ac.gif)

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:09:52.377Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|5, 3, 2|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir tmp/user --extensions-dir tmp/ext|
|Screen Reader|no|
|VM|20%|

</details>Extensions: none
Reproduces without extensions

**Comment by isidorn** [comment]
@chrmarti can not repro. Do you see this always. 
Can you please put a breakpoint here and investigate if it is being hit 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/breakpointsView.ts#L177
Thanks

**Comment by chrmarti** [comment]
No longer reproduces. I saw it multiple times, but then reloaded the window for some other reason, maybe that got rid of it.

**Comment by isidorn** [comment]
I will close this for now, but when you hit it next time just put a breakpoint at that location and let me know what you see. I wil lalso keep my eyes open on this one.
