### ISSUE TITLE
Powershell PSScriptAnalyzer, error in PSUseDeclaredVarsMoreThanAssignments

### ISSUE THREAD

**Issue by ingemar-hn** [Microsoft/vscode#44500]
Issue Type: <b>Bug</b>

Error occurs in the below code:

```
$a = 0
foreach ($i in 0..3) {
        $a = 1
}
0..3 | ForEach-Object {
        $a = 1
}
$a
```

In the first loop it works as it should. In the second $a is reported to be assigned but never used.
I assume that there's no use in disabling extensions and retry since the Powershell handling is done in an extension.

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T09:01:48.555Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|Memory (System)|31.67GB (17.75GB free)|
|Process Argv|C:\MyPrograms\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
java|red|0.19.0
jenkinsfile-support|sec|0.1.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.2

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
Pls file the issue against the powershell extensions [here](https://github.com/PowerShell/vscode-powershell/issues/new). Thanks a ton for your help!

**Comment by bergmeister** [comment]
@kieferrm The better repo to report `PSScriptAnalyzer` issues is here: https://github.com/PowerShell/PSScriptAnalyzer/
