### ISSUE TITLE
List: multi select behaves weird when shift clicking

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44507]
![flicker_chrome58](https://user-images.githubusercontent.com/900690/36723034-740d3e22-1baf-11e8-9748-046c43ea8a5b.gif)

Happens in other lists as well. Not sure who added this though, /cc @joaomoreno

**Comment by isidorn** [comment]
I broke it via https://github.com/Microsoft/vscode/commit/5dc3c59343e1c573bb319cb867e3aac9c9ca1e10

**Comment by bpasero** [comment]
@isidorn thanks
