### ISSUE TITLE
Throttle notifications when someone spams many of them at the same time

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#44512]
Testing https://github.com/Microsoft/vscode/issues/44319

```
        for (let i = 0; i < 50; i++) {
            let base = 100 * i;
            setTimeout(() => {
                vscode.window.showInformationMessage('Hello World One');
            }, base);
            setTimeout(() => {
                vscode.window.showInformationMessage('Hello World Two');
            }, base + 50);
        }
```

**Comment by bpasero** [comment]
Yeah a bit ugly, the old solution had the same issue and so far was not reported:

![before](https://user-images.githubusercontent.com/900690/36745687-9884485e-1bf0-11e8-8e5f-4b2b575dee5b.gif)

I would like to stay away from introducing some odd debouncing logic.

**Comment by hamidatal** [comment]
java script
