### ISSUE TITLE
Function breakpoint icon disappears

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#44513]
testing #43836:

Use this code:
```ts
let i = 0;

func = function() {
	console.log("hello world: " + i++);
}

setInterval(x => {
	func();
}, 1000);
```

and this launch.json:
```json
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceFolder}/hello.js",
			"runtimeVersion": "7.10.1"
		}
```

- add a function breakpoint for "func"
- add a function breakpoint for "setInterval"
- F5

Observe: 
"setInterval" is hit and "func" loses its red triangle. 
I would expect that "func" gets an unverified icon.

**Comment by weinand** [comment]
"func" no longer looses its red triangle.
But now "setInterval" looses it.

To reproduce:
- same setup as above
- enable bot func breakpoints
- start session
- disable "func"

Observe: setinterVal looses icon

**Comment by weinand** [comment]
And after adding a regular breakpoint the disappearing function breakpoint is back:

![2018-03-01_16-55-12](https://user-images.githubusercontent.com/1898161/36854549-963800e0-1d71-11e8-9327-c799680aab43.gif)

**Comment by isidorn** [comment]
@weinand did you try with latest from source or vscode insiders?
Since the vscode insiders does not contain my fix and I would ask you to try again tomorrow please

**Comment by weinand** [comment]
Icons now work for function breakpoints.

However, if I use function breakpoints with node-debug2, I see an unexpected icon:

![2018-03-02_10-45-22](https://user-images.githubusercontent.com/1898161/36893013-e0502ff0-1e06-11e8-914c-51deca3d6f61.png)

I suggest that we always show the grey, hollow triangle for unverified function breakpoints.

**Comment by isidorn** [comment]
Thanks, that is covered via fcf3765e37
