### ISSUE TITLE
Native text selection appears in code editor

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#44517]
Testing #44293

Linux

- have the search view with some matches
- drag a line match to the editor
- the editor is strangely rendered

![image](https://user-images.githubusercontent.com/6461412/36724547-d214fdf8-1bb3-11e8-8d06-1d703249c1c8.png)

Same when dragging a git resource

**Comment by bpasero** [comment]
@alexandrudima I can reproduce in the editor by starting to drag from the find widget:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/36732797-0e1c72e8-1bcf-11e8-9063-4a4ace33d30d.gif)

I guess some `user-select` property is not set in the editor maybe for accessibility reason?

**Comment by alexandrudima** [comment]
The editor used `user-select: text` for Chrome. 

But it appears Chrome has fixed that in the meantime and it is only Safari that still needs `user-select: text` in order for `document.caretRangeFromPoint` to work correctly.

**Comment by bpasero** [comment]
@alexandrudima great
