### ISSUE TITLE
Handle disabling of the default theme extension

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44510]
Testing https://github.com/Microsoft/vscode/issues/44361

* Have any default theme as active theme
* Disable the default theme extension
* reload

=> the theme is still active

We should maybe be careful with allowing to disable our built in default themes. @aeschli could maybe comment on that

**Comment by sandy081** [comment]
I think this is only happening for default themes extension, others are behaving similar to market place extensions. 

@aeschli What is expected when a default themes extension is disabled when it is active?

**Comment by aeschli** [comment]
We currently expect the default themes to be present as they are the fallback.

**Comment by aeschli** [comment]
The fix makes sure that the default theme ('Default Dark+') is always available. If the extension is not present, a dummy is created, without syntax colors.
