### ISSUE TITLE
Manage Extension notification does nothing

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#44511]
Testing https://github.com/Microsoft/vscode/issues/44319

Clicking on the gear icon and selecting `Manage Extension` did nothing for me.

<img width="428" alt="capture" src="https://user-images.githubusercontent.com/1931590/36723728-6199218c-1bb1-11e8-8328-8c162cb77ac6.png">

**Comment by bpasero** [comment]
@dbaeumer you probably ran an extension out of sources via debugger? In that case the action is a no-op, it will only work with installed extensions. 

To test this you could try to trigger an error from GIT, e.g. try to commit a file with formatting errors.

**Comment by dbaeumer** [comment]
Yes, I ran it from source. Should we then remove the action ?

**Comment by bpasero** [comment]
@sandy081 actually maybe this is a bug, should it be possible to open the extension editor for an extension that is just debugged at the same time? This could be helpful to debug how an extension looks like based on the package.json contents.

**Comment by sandy081** [comment]
It is possible but not trivial as extensions workbench/management is not aware of such a thing called developing extension.

**Comment by bpasero** [comment]
@sandy081 is there a way to find out if the extension is running "out of sources"? then I could maybe not add the action.

**Comment by sandy081** [comment]
There is no direct API. 

But can get that information by using  [getExtensions](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/common/extensions.ts#L151)  to get the `IExtensionDescription` and check if [IExtensionDescription.extensionFolderPath`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/common/extensions.ts#L21) is same as [extensionDevelopmentPath](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/common/environment.ts#L102)
