### ISSUE TITLE
The flatpak gulp task forgets to replace all the placeholders

### ISSUE THREAD

**Issue by amtlib-dot-dll** [Microsoft/vscode#44519]
- VSCode Version: 1.20.1
- OS Version: Fedora 27

Steps to Reproduce:

1. Build the flatpak via `gulp vscode-linux-x64-flatpak`
2. The resulting `.desktop` file still contains placeholder `@@ICON@@`

Does this issue occur when all extensions are disabled?: Not Applicable

**Comment by Tyriar** [comment]
FYI I'll be removing the flatpak task soon https://github.com/Microsoft/vscode/issues/44578
