### ISSUE TITLE
[folding] strange folding with 'else'

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44526]
Testing #44445

Have this code:

```typescript
if (true) {
	console.log("yes");
} else {
	console.log("false");
}
```

Collapsed in insiders (syntax based):
![image](https://user-images.githubusercontent.com/900690/36724987-24aca696-1bb5-11e8-9d22-e0b1450fdd72.png)

Collapsed in stable (indentation based):
![image](https://user-images.githubusercontent.com/900690/36724994-2d5537f4-1bb5-11e8-91e0-cf302380da6c.png)

**Comment by mjbvz** [comment]
@aeschli Looks like typescript has the concept of folding to a specific character within a line. In this case, they tell us to fold to line 3, character 2. 

Any idea on how to map this back to the vscode folding API?

**Comment by aeschli** [comment]
In VSCode we normally don't fold the closing bracket.
I think best is test if the last character is a '}' and then reduce the end line by one.

**Comment by mjbvz** [comment]
Fixed for syntax aware folding.

For verification, make sure you have `typescript.experimental.syntaxFolding": true` and don't have `editor.foldingStrategy` set to `'indentation'`
