### ISSUE TITLE
Bad ux flow for pinning markdown preview 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#44529]
Refs: #44462

Currently there are two commands:
* `Markdown: Open Preview` 
* `Markdown: Open Pinned Preview to the Side`

These should not be two commands, but just one and the user should be able to pin the preview after the fact. How can he know if he wants to preview before he actually sees it.

I suggest the following:
* Remove `Markdown: Open Pinned Preview to the Side`
* Add a Pin Preview command in the elipses of the editor title area, beneath the "Refresh Preview"

**Comment by joaomoreno** [comment]
Actually I think the name pinned is even incorrect. We already use the pinning term in the workbench and we render unpinned file names in italic. I would not overload the term by making it mean something else. I think the term **lock** is a good alternative.

@mjbvz Have you thought about a little header or footer bar inside each markdown preview view, in which you could render a checkbox which would control this behaviour?

**Comment by isidorn** [comment]
Agree that pinned is a bad name since already taken.
Lock is good. Maybe also "track", by default it tracks, and you can disable that with a checkbox / action

**Comment by mjbvz** [comment]
Change the term to "locked" and added a command to toggle locking on a preview.

Not sure we can render a lock icon in the title currently (besides using an emoji). Current approach marks locked previews as `[Preview]`. Let me know if you have any suggestions for how to make more clear
