### ISSUE TITLE
Dragging from search result gives native selection

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#44525]
Testing #44293

* search for something
* drag from the search result

> Note: The same issue exists when dragging from a problem in the PROBLEMS view.

![kapture 2018-02-27 at 11 53 46](https://user-images.githubusercontent.com/5047891/36724936-f585cbb8-1bb4-11e8-9b4f-bd8ca2c4533b.gif)

**Comment by bpasero** [comment]
Same as https://github.com/Microsoft/vscode/issues/44517
