### ISSUE TITLE
[folding] collapsed region not preserved

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44524]
Testing #44445

* open vscode workspace
* open openAnythingHandler.ts
* reload window
* quickly fold something
* wait to see the folding region expand again

![flicker_chrome58](https://user-images.githubusercontent.com/900690/36724839-b4d86fc6-1bb4-11e8-9172-e3d4f8ce93d8.gif)

**Comment by bpasero** [comment]
@aeschli verified that the collapse button now do nothing until the language server is up. Not a very pleasant experience.

**Comment by aeschli** [comment]
@bpasero Thanks, created #46708
