### ISSUE TITLE
Folding: indentation based folding appears and then hides

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44520]
Testing https://github.com/Microsoft/vscode/issues/44445

* open vscode workspace
* open openAnythingHandler.ts
* reload window
* you see the folding regions right on startup and then disappear
* you have to wait 20 seconds at least until the TS language server has digested the project and then folding comes back

Maybe we leave the indentation based ones in until the language server is there at least?

**Comment by aeschli** [comment]
fixed in master
