### ISSUE TITLE
Open Recent should open in new window in some (or all) cases

### ISSUE THREAD

**Issue by alper** [Microsoft/vscode#44528]
Steps to Reproduce:

1. Have a workspace with Untitled (unsaved) files open (which is me pretty much always)
2. Go to File -> Open Recent -> Pick a recent workspace
3. vscode will now try to replace the window I have with the workspace I picked and prompt me to do something with the Untitled files.
4. The behaviour I would like to see (because it would create less friction) is vscode opening the selected workspace in a new window by default.

**Comment by alper** [comment]
Thanks @vscodebot but that's not a duplicate.

**Comment by bpasero** [comment]
`"window.openFoldersInNewWindow": "on"`

**Comment by alper** [comment]
Unbelievable. 😊

Ta.
