### ISSUE TITLE
Folding: editor slightly jumps from time to time

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44533]
Testing https://github.com/Microsoft/vscode/issues/44445

I am testing on Windows 10 and sometimes when I collapse/expand I see the editor area jumping a bit up. This seems to depend on the scroll position. I have zooming disabled:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/36725495-c35a61c4-1bb6-11e8-9913-964f5657c9ac.gif)

**Comment by aeschli** [comment]
@bpasero I'm not able to reduce. Tried on Linux and Windows with same file and location as you did, trying multiple scoll offsets.
If you can still see this, can you debug in `folding.ts`, line 351 (`revealPositionInCenterIfOutsideViewport`). Nothing should happen unless the cursor is off screen.

**Comment by bpasero** [comment]
@aeschli this method is called everytime I fold/unfold, is that expected?

**Comment by aeschli** [comment]
Yes. But the function should be a no-op unless the cursor moved to a hidden location

**Comment by bpasero** [comment]
@aeschli I can only reproduce if I scroll once. I can show you when you are in the office.

**Comment by bpasero** [comment]
Does not reproduce on my Windows machine, so I suspect some issue only in Windows VM. Not a big deal I think, closing.
