### ISSUE TITLE
Markdown preview scrolls even though I did not scroll in markdown file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#44534]
Refs: #44462
Windows

1. Open a large markdown file and open a preview to the side
2. Make some edits in the markdown file which do not introduce new lines, just simple changes on a line
3. Notice how the preview scrolls, I would expect the preview to stay still since only the changes on one line were applied

**Comment by mjbvz** [comment]
@isidorn Can you please test this in the next insiders build. I've made some fixes to this but am not sure they address your specific issue. 

If you still see this, please share the markdown file so that I can investigate this further

**Comment by isidorn** [comment]
This works better with the latest out of source. Thanks, closing
