### ISSUE TITLE
Folding: support imports and copyright header

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44535]
Testing #44445

It looks like with `"typescript.experimental.syntaxFolding": true` I cannot fold these regions that I would assume should be supported:
* copyright header (in vscode sources)
* imports

**Comment by bpasero** [comment]
Seems to not fully work:
* open `ben/editor` branch
* open `editorGroupView.ts`
* 🐛 the copyright on the top cannot be folded

**Comment by mjbvz** [comment]
@bpasero Opened https://github.com/Microsoft/vscode/issues/50899 to track this specific issues
