### ISSUE TITLE
[typescript] add type to #region fold ranges

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44530]
Testing https://github.com/Microsoft/vscode/issues/44445

I am not able to fold my regions when invoked from the command palette in TS files with `"typescript.experimental.syntaxFolding": true`

**Comment by bpasero** [comment]
@aeschli same seems to happen with folding block comments

**Comment by aeschli** [comment]
For folding to know which folding range represent a region, `FoldingRange.type` should be set to FoldingRangeType.Region.

Same for the 'fold comment' to work: FoldingRangeType.FoldingRangeType

**Comment by mjbvz** [comment]
Depends on https://github.com/Microsoft/TypeScript/issues/22419

If this issue is important enough, we could work around this in the vscode extension itself too by attempting to check the contents of the  folding range

**Comment by bpasero** [comment]
Seems to not fully work:
* open `ben/editor` branch
* open `editorGroupView.ts`
* fold all regions
* 🐛 the region `IEditorGroupView` is not folded

![image](https://user-images.githubusercontent.com/900690/40649973-73157aa0-6332-11e8-8c7b-44a76c5104ae.png)

**Comment by mjbvz** [comment]
Looks like an in-valid region (missing `#`). It needs to be with `//#region IEditorGroupView`
