### ISSUE TITLE
Peek definition shows import line with typescript and es6 style modules

### ISSUE THREAD

**Issue by mtrivolli** [Microsoft/vscode#4454]
- VSCode Version: 0.10.10
- OS Version: Debian Jessie

Steps to Reproduce:

- Create a simple typescript file using es6 style imports. For instance:
```typescript
import {Promise} from "es6-promise";

let a = new Promise<string>((resolve, reject) => {
    resolve("test");
});
```
- Right click on "Promise<string>" => peek definition. It shows `import {Promise}`

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7612
