### ISSUE TITLE
Help message is wrong when renaming

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#44548]
Testing #43968

* Have a file `c` in a folder `a/b`:
* Like this:
![image](https://user-images.githubusercontent.com/5047891/36726620-bae2ca28-1bba-11e8-8e36-2d5a297a07e3.png)
* Right click and rename `c`
* Type `d/c`
* Observe the message:
![image](https://user-images.githubusercontent.com/5047891/36726639-cb5bed94-1bba-11e8-8689-cc740664f7d9.png)
* That message is wrong, because pressing Enter will create a folder `d` and then move file `c` into it.

**Comment by DarkLite1** [comment]
I think that is by desing #31305

**Comment by alexandrudima** [comment]
> I think the message can be improved but the behavior is by design #31305

Yeah, that's what I'm trying to say, that the help message is wrong
