### ISSUE TITLE
Notification UI: Gear and close button not keyboard accessible

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#44541]
Testing https://github.com/Microsoft/vscode/issues/44319

I was not able to navigate to the two buttons using the keyboard on Windows.

**Comment by bpasero** [comment]
Steps: select a collapsed message and hit Tab, it does not move into actions probably because the actions hide when tabbing.

**Comment by bpasero** [comment]
@joaomoreno looks like a regression in the list to me, reproduces in the extensions list as well:

![before](https://user-images.githubusercontent.com/900690/36745263-3c4d622e-1bef-11e8-95c5-bcb688e7addd.gif)

Steps:
* select an item
* hit tab
* the action is no longer selected that is part of the item, instead the first one is navigated to

**Comment by joaomoreno** [comment]
I believe you implemented this back in the days by hijackign what <kbd>Tab</kbd> would do when there is a focused element, am I right?

**Comment by bpasero** [comment]
@joaomoreno sorry I do not recall that anymore. I would find it dangerous to overwrite what Tab key does because maybe there are other keys to trigger this?

**Comment by joaomoreno** [comment]
Turns out it never worked!

**Comment by bpasero** [comment]
Thanks dude!
