### ISSUE TITLE
Opening launch configs in user or workspace settings should reveal the "launch" section

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#44542]
Testing #44449:

If you have a default launch config in user or workspace settings and you press the gear icon in the debug viewlet, it opens the correct settings file but it does not reveal or highlight the "launch" section.

**Comment by isidorn** [comment]
This is a great idea, for that the [`OpenGlobalSettings`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/common/preferences.ts#L156) would need to take an additional option of being passed a setting name.
Assigning also to @sandy081 since he would need to provide that api or to give me some code pointers for that to happen or if our proposal make sense at all.

**Comment by sandy081** [comment]
You can provide the setting to edit using `editSetting` option.

Eg: `this.preferencesService.openGlobalSettings(true, { editSetting: <id> });`

**Comment by isidorn** [comment]
@sandy081 thanks, I just tried it. Even though this nicely opens the User setting on the correct location it also adds a new line and triggers the suggest widget. Which seems to be expected for the `editSetting` behavior. Here I do not really want to edit - I simply want that part revealed. Is there some api for that?

**Comment by sandy081** [comment]
Ah ok, I can add reveal setting option for your use case.

**Comment by isidorn** [comment]
Yeah, that would be great, thanks!

**Comment by isidorn** [comment]
@sandy081 friendly ping for this. Should we push it out to next milestone? Anything works for me.

**Comment by sandy081** [comment]
Will see if I can squeeze it in today, otherwise will move this on Monday. Hope that works.

**Comment by isidorn** [comment]
Anything works. Thanks!

**Comment by sandy081** [comment]
Added support for revealing the setting. Eg: 

`this.preferencesService.openGlobalSettings(true, { revealSetting: {key: '<id>'} });`

**Comment by isidorn** [comment]
@sandy081 works lovely, thanks!

**Comment by bpasero** [comment]
👏
