### ISSUE TITLE
Live validation is not good enough

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#44545]
Testing #43968

* Have a file `c` in the path `a/b`
* Like this:
![image](https://user-images.githubusercontent.com/5047891/36726519-4fb98142-1bba-11e8-8b70-5d34f33f91c1.png)
* Create a new file
* Type `a/b/c/d`
* No validation error is shown
* Press Enter
* Observe error:
![image](https://user-images.githubusercontent.com/5047891/36726538-67f37f4c-1bba-11e8-8240-7c4c74e852c0.png)

**Comment by tsalinger** [comment]
fixed by #46096
