### ISSUE TITLE
Cannot read property 'input' of null

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#44546]
1. Close the last open editor of an editor group

![image](https://user-images.githubusercontent.com/22350/36726549-6d2ca7fe-1bba-11e8-834f-f2ed20432539.png)

**Comment by isidorn** [comment]
This is coming from the mainThreadWebView
I pushed a fix, fyi @mattbierner 

![screen shot 2018-02-27 at 14 37 00](https://user-images.githubusercontent.com/1926584/36731685-b5bb35e2-1bcb-11e8-8b46-1969c202992d.png)
