### ISSUE TITLE
Ugly input box for function breakpoints

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#44557]
Testing #43836

When we create (or edit) function breakpoints, we already know its icon and its enablement status. Those two decorations should already be in the row and the input box should only take up as much space as the text label would.

![image](https://user-images.githubusercontent.com/22350/36726985-e3d6ff98-1bbb-11e8-9935-112b6499d160.png)

**Comment by bpasero** [comment]
Love it!
