### ISSUE TITLE
Allow to DND multiple root-folders

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44554]
Testing #29715

I see no reason why we would not support to DND multiple root folders. The API is easy enough to use, just splice the folders by removing all and then adding all in the right order. We do the diff and will only send the correct change event, you don't have to compute it.

**Comment by isidorn** [comment]
I justr tried writing this and it is not so trivial to put them in the right order -> will overcomplicate the code -> backlog.
And doing two of them seperatly produces an error -> seems like the workspace editing service can not handle two operations in parallel of changing roots.

Code pointer https://github.com/Microsoft/vscode/blob/b40e6492ab415347a86c3841c0437dba996db6ce/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L961

**Comment by bpasero** [comment]
@isidorn yeah I would not expect that 2 calls to the workspace editing service is clever, but if you call it once with the right order after the drop operation it should work, no? Can you not keep an array of workspace folders when the drag operation starts and when you drop you simply call the splice method on that array to reflect the change and then just give that array to the workspace editing service to replace them all?

**Comment by isidorn** [comment]
@bpasero in theory yes, in practice it is very tedious code. "Simply call the splice method" is not so trivial, I tried.

**Comment by bpasero** [comment]
@isidorn ok lets look into it next week when we are both in the office

**Comment by isidorn** [comment]
@bpasero I see you are very passionate about this. I can do a PR and then you will see how the code is clunky.

**Comment by bpasero** [comment]
@isidorn yeah, I am a little passionate about this feature, but more passionate about why the code is complex :). I am happy to check out a PR (even if prototypal) so understand the complexity.
