### ISSUE TITLE
Weird completion proposal for workbench color customizations

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44558]
I am not sure why we propose this:

![image](https://user-images.githubusercontent.com/900690/36727170-95289824-1bbc-11e8-8c90-89adc406e254.png)

Completes to this:

![image](https://user-images.githubusercontent.com/900690/36727181-9ad16166-1bbc-11e8-84d6-8878f52d60d4.png)

**Comment by aeschli** [comment]
It's just an example where you can see a change.
