### ISSUE TITLE
Can't press Space in function breakpoint input

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#44555]
Testing #43836

<kbd>Space</kbd> doesn't do anything. Probably, the list is eating it with the `list.toggleExpand` command, although the condition for that command is `listFocus && !inputFocus`. Works fine in the watch list.

**Comment by isidorn** [comment]
Uff this is very tricky. I put a breakpoint in the `inputFocus` context key and it is correctly set to `true`.

Watch expresions is different in how it usses the input box, every time I render the element I recreate the input box. While in the breakpoints list I always reuse the input box via the templates.

Might you have a tip on how to debug this and who else could be stealing the key?

**Comment by joaomoreno** [comment]
Sure man. Write it down in a post-it: `abstractKeybindingService.js#85`.

![image](https://user-images.githubusercontent.com/22350/36740605-3895c182-1be3-11e8-8381-b4f3b7bf9de2.png)

**Comment by joaomoreno** [comment]
Also don't forget `Developer: Inspect Context Keys`.

**Comment by isidorn** [comment]
@joaomoreno awesome thanks!
I remembered your inspect context keys, but in this case was not nice to use since the focus lost closes the input.
