### ISSUE TITLE
Propose to rephrase hit count breakpoint placeholder text

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#44559]
Testing #43836

I felt a bit lost when reading this:

![image](https://user-images.githubusercontent.com/22350/36727258-e5ad76de-1bbc-11e8-932e-93feb0d42dac.png)

The phrasing is a bit too generic and leaves room for interpretation on what should be input, when in fact the condition is a pure equality and the value should be a number. Here's a suggestion:

```
Break when hit X times. Please input a number, 'Enter' to accept, 'Escape' to cancel.
```

**Comment by isidorn** [comment]
This make sense to me.
I am wondering if some other debug adapters use the hit count in a different way thus we choose a more generic message.
@weinand what are your thoughts?

**Comment by weinand** [comment]
The syntax is not specified as it depends on the backend:
generic doc: https://code.visualstudio.com/docs/editor/debugging#_conditional-breakpoints
node.js doc: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_breakpoint-hit-counts

**Comment by joaomoreno** [comment]
That's too bad. I wonder if we should let the backend specify the message then?

**Comment by weinand** [comment]
Sure, I think we have already a feature request for this.

**Comment by isidorn** [comment]
Good job @vscodebot
fyi @chrmarti 

Duplicate of https://github.com/Microsoft/vscode/issues/14363

**Comment by joaomoreno** [comment]
@chrmarti In Reddit there's a feature in which people can say "good bot" and the bot takes that as a good job. Could we feed that into the learning?

**Comment by chrmarti** [comment]
Thumbs up might be the easiest and most intuitive way to do this. At the moment I don't have a way to feed that back to the duplicate detection because the main algorithm just compares vectorized representations of issues. Maybe we can still find a way to leverage that feedback (like simple evaluation).
