### ISSUE TITLE
Run task without showing Terminal panel

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#44564]
- VSCode Version: 1.20.1

Steps to Reproduce:

1. Click Tasks > Run Tasks... > npm start.
2. Terminal panel is shown.

I would like to be able to set the Terminal panel to not display.
This can be done using the additional parameter at task.

Why? Because I have to close it every time...
In addition, there is the "Show Running Tasks" icon that shows if the task is running. This is enough in most cases to know that the task has not been interrupted.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lukaszpolowczyk** [comment]
Sorry, property `presentation { reveal: never/silent}` in task doing this.
Issue is out of date.

**Comment by dbaeumer** [comment]
Yes, the setting you found is correct.
