### ISSUE TITLE
Allow configuring fuzzySearchMinScore for Emmet

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#44568]
Hi,

I don't know its a bug, feature or something, but its not great.
I think the most used value for `display` is `block` or `inline-block`, but definitely is not `inline`.

- VSCode Version: 1.20.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. In any CSS/SCSS file, start typing dis ... and hit tab
2. Instead of `display:`, we got `display: inline`

Does this issue occur when all extensions are disabled?: I don't know!

Thanks.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/36734381-a168403c-1bd3-11e8-8582-8ea0dd682f17.png)

**Comment by ramya-rao-a** [comment]
[Emmet](https://emmet.io/) fuzzy matches `dis` to `display: inline`  and that's what you see here.
If you are not a avid Emmet user, then you can stop Emmet from contributing to the suggestion list by adding the below in your settings file
```
"emmet.showExpandedAbbreviation": "never"
```

Its also a valid point that the fuzzy matching algorithm is too eager here. What we can do is expose the min score that Emmet uses to accept a match. The [vscode-emmet-helper](https://github.com/Microsoft/vscode-emmet-helper) hard-codes this to be 0.3. This can be made configurable

**Comment by dehghani-mehdi** [comment]
@ramya-rao-a I know that config and obviously I don't want to disable Emmet.

**Comment by ramya-rao-a** [comment]
@dehghani-mehdi From your initial issue description, it wasn't clear to me if you wanted Emmet or not, thus the suggestion on disabling it in case you didn't want Emmet.

**Comment by ramya-rao-a** [comment]
@dehghani-mehdi In the latest [Insiders](https://code.visualstudio.com/insiders), add the below setting 
```
"emmet.preferences": {
        "css.fuzzySearchMinScore": 0.4
    }
``` 
to get the issue fixed
