### ISSUE TITLE
vscode marketplace shows wrong installation instructions

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode#4456]
For example for my [debugging extension](https://marketplace.visualstudio.com/items?itemName=webfreak.debug) the vscode marketplace says I should do `ext install debug` but when entering that into the console it wants to install [some python extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) as it has `debug` in its description and is the most downloaded extension. Showing `publisher.extension` in the marketplace would make this more unique

**Comment by egamma** [comment]
You run this command from the command palette not on the command line, see the first sentence.

![image](https://cloud.githubusercontent.com/assets/172399/13899425/1e1fe0aa-edee-11e5-9e05-92baa56dd963.png)

@waderyan we should try to avoid this confusion.  I suggest to show this is a two steps
1) open command palette
2) run this command

**Comment by WebFreak001** [comment]
yeah I meant command palette instead of console but I actually did it in the command palette

**Comment by WebFreak001** [comment]
The issue is that if I run the command in the **command pallete** (ctrl-p) as it says on the vscode marketplace, it will search for the extension now but it will select the wrong extension. Currently when I run the command it gives me (`ext install debug`), it will show PHP Debug as first result. However this is not the extension I got the command for ([actual extension I would want to install](https://marketplace.visualstudio.com/items?itemName=webfreak.debug))

This isn't really a big issue now that it doesn't install the extension anymore but instead searches for it in the extensions dialog. However users who are new to vscode and want to install an extension they found on the internet could get confused why it isn't showing up in the results (you might need to scroll because the extension doesn't have 100k downloads but a very generic name)

**Comment by egamma** [comment]
This has been addressed by the support to install from the marketplace directly.
