### ISSUE TITLE
Nodejs Debugger skips first F11 after breakpoint on await/async function

### ISSUE THREAD

**Issue by apitenko** [Microsoft/vscode#44567]
- VSCode Version: 1.20.1
- OS Version: Windows 10 x64

Steps to Reproduce:
1) Write some async code (see example)

```
async function foo(num) {
    await new Promise(function (res) {
        setTimeout(res, 1000);
        console.log(num);
    })
}

(async function () {

    await foo(1); // set breakpoint here, then press F11 to step in
    await foo(2); // F11 doesn't work for a first line, but will work on next line
    await foo(3);
})()
```

2) Set breakpoint on await foo(1);
3) Start file with nodejs and debugger
4) When debugger stops on breakpoint, try to F11 into the function
5) F11 doesn't work, first line is skipped as if F10 was pressed
6) Second F11 works fine

- Only async functions affected.
- Help->Report issue doesn't work.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
What version of node are you using?

**Comment by weinand** [comment]
Cannot reproduce.
With node 8.9.3 on Windows 10 F11 steps into some internal node module:

![2018-02-27_14-25-45](https://user-images.githubusercontent.com/1898161/36731150-1e643dfc-1bca-11e8-804f-09a65929aba6.png)

This can be prevented by skipping internal modules like this:
```
  {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/test.js",
            "skipFiles": [
                "<node_internals>/**"
            ]
        }
```
Now the stepping works just fine:

![2018-02-27_14-27-45](https://user-images.githubusercontent.com/1898161/36731298-97ba70e0-1bca-11e8-879f-391c21869fda.gif)

**Comment by apitenko** [comment]
Thanks for quick response!
I was using Nodejs v8.2.1.
I've just updated it to Nodejs v8.9.4, and it works same as on your gifs. Although it's still not a perfect behavior, it doesn't miss breakpoints now.
Thanks!

**Comment by weinand** [comment]
What is not "perfect" about the behaviour?

**Comment by apitenko** [comment]
I guess, stepping to inner nodejs modules, but it doesn't do that while debugging my project, only on  example code.
And I don't know if VSCode is aimed to support older Nodejs versions, or that was a bug in Nodejs instead of VScode.

**Comment by apitenko** [comment]
upd. Sometimes while debugging my project, it drops into nodejs internal modules too.

**Comment by weinand** [comment]
If it does not step into internal nodejs modules in your project, then you might have configured your launch config for this behaviour. If not please file a bug and we will investigate.

VS Code node-debug supports older version of node.js back to 0.10.x (which is really old). But since there are lots of node.js versions, and quite a few have bugs, we cannot work around all those bugs. So you might see issues like this with the v8.2.1 version.
