### ISSUE TITLE
VSCode SEARCH cannot work with regexp "[a-zA-Z][\n\r]\{"

### ISSUE THREAD

**Issue by SubmarineX** [Microsoft/vscode#44565]
### Issue Type
Bug

### Description

It just is a VSCode specific issue.
Reproduce it that:

1. create a text file
2. type some characters, for example:
`abcd`
`{`
3. Search (open with Ctrl + Shift + F) with regular expression `[a-zA-Z][\n\r]\{`
You can find that:
![image](https://user-images.githubusercontent.com/2227182/36727669-1ba79698-1bf9-11e8-9c1f-c537357e5455.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.14.0

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
You are right, but this is a feature request in https://github.com/Microsoft/vscode/issues/13155
