### ISSUE TITLE
Deprecated setting that was not migrated?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#44563]
This setting is now showing a squiggle in my configuration options:

`markdown.preview.scrollPreviewWithEditorSelection`

![image](https://user-images.githubusercontent.com/5047891/36727502-c7205032-1bbd-11e8-8250-d261b5cff3d3.png)

Is this intentional? I wonder if this could have been migrated for me ...

**Comment by mjbvz** [comment]
The difference in behavior between the old setting and its replacement is significant enough that I'm not sure automatically migrating it makes sense. I'll add a `deprecationMessage`
