### ISSUE TITLE
Context menu not working on some input fields

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44576]
Steps to Reproduce:

1. right click into input fields like a rename input box in the explorer or the git commit box
2. no context menu shows up

This is how it should be:

![image](https://user-images.githubusercontent.com/900690/36732576-7026e776-1bce-11e8-93d0-ac63e407eefa.png)

@joaomoreno @isidorn I have no clue why this would not work anymore, if you have an idea. The trigger is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/window.ts#L259 via `window.document.addEventListener('contextmenu', e => this.onContextMenu(e));`

**Comment by joaomoreno** [comment]
@sandy081 

https://github.com/Microsoft/vscode/commit/d127e5777cc8d98e1033dd6b1dbe71837499d94a#diff-0e8eb65b1e0196a6cbe33ef94897c376R184

**Comment by sandy081** [comment]
My mistake, I should not stop the event if I am not handling it.
