### ISSUE TITLE
Webview is an editor-wannabe 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#44574]
re #44466

There is the `onDidChangeActiveEditor` vs `onDidChangeActiveTextEdtor` which is very confusing, then there is `Webview#editorType` which is also confusing and I don't understand why. Isn't a webview just a thing like a terminal or an output channel?

**Comment by jrieken** [comment]
Oh, it actually not `onDidChangeActiveTEXTeditor`...

**Comment by mjbvz** [comment]
See #43803 for the background and some of the other design options considered

**Comment by jrieken** [comment]
I believe it needs a new concept. Maybe something like `const activePart: TextEditor | Webview | TreeView | OutputChannel | any;`. We have similar requests already, folks want to know if focus is in a contributed tree, or they want to interact with an output channel. We should think about this in a wider scope.

**Comment by mjbvz** [comment]
Made this event private with 27a17935b824f3d7b40b2fbebf6f432667f38131.  #45994 tracks the other parts of the new webview api proposal
