### ISSUE TITLE
can't download the installer

### ISSUE THREAD

**Issue by Johnaka** [Microsoft/vscode#4457]
- VSCode Version: 10.11
- OS Version:  windows 10 pro 1511

Steps to Reproduce:

1.  can't download the installer 
2.  also could never update since 0.3 version
![screenshot 46](https://cloud.githubusercontent.com/assets/11838212/13899530/5d2f504a-ee12-11e5-8a4b-c2783adc29d1.png)

**Comment by Johnaka** [comment]
![screenshot 47](https://cloud.githubusercontent.com/assets/11838212/13917088/77580e20-ef80-11e5-9ce0-75a9ec4a9fb0.png)

this is no work also

**Comment by Johnaka** [comment]
oldnglsdknglskngflskdjnfslkfnsdlkfnsdlkfnsdkjfn

**Comment by joaomoreno** [comment]
Are you behind a proxy?

This is the URL, for reference:

https://az764295.vo.msecnd.net/stable/f291f4ad600767626b24a4b15816b04bee9a3049/VSCodeSetup-stable.exe

**Comment by Johnaka** [comment]
no i am not. i have tried with IE edge and mozila it didn't work i can download as regular it's just this one link is not working

**Comment by joaomoreno** [comment]
When you say *i can download as regular*, what do you mean by as regular?

**Comment by Johnaka** [comment]
i mean i just can download from different sites IE edge and chrome the browsers i use are fine but the vscode link is not working

**Comment by Johnaka** [comment]
changed my proxy it worked. so the link is not working in west asia

**Comment by joaomoreno** [comment]
Thanks for the information.

cc @chrisdias @seanmcbreen @waderyan @egamma
