### ISSUE TITLE
"markdown.preview.scrollPreviewWithEditor" has no effect

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#44577]
Testing  #44463 

The setting doesn´t have any effect, when I set it to false the preview still scrolls with the editor.

**Comment by gregvanl** [comment]
It looks like the settings don't take effect until a new preview pane is created. The settings don't update the behavior of an open preview. This is true for both synch settings scrollPreviewWithEditor and scrollEditorWithPreview.
