### ISSUE TITLE
Webview#show should come with #hide

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#44580]
re #44466

It's always sad to see `show` without `hide` also see various other panels for reference

**Comment by octref** [comment]
I actually wouldn't know what `hide` is supposed to do. If extension author wants the webview destroyed there is `webview.dispose`.

**Comment by jrieken** [comment]
Good question... Maybe we should rename `show` to `reveal` in that case

**Comment by mjbvz** [comment]
Ok, I like renaming show to `reveal`. I think `dispose` already covers `hide` though
