### ISSUE TITLE
A 1 is indicated in notification center when I expect 2

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44588]
VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.13.0-36-generic

---

#44319

Repro:

Launch an extension with the following:

```ts
let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
    vscode.window.showErrorMessage('one', 'a', 'b');
    vscode.window.showWarningMessage('two', 'c', 'd');
});
```

Run the command:

![image](https://user-images.githubusercontent.com/2193314/36735096-3990d0c6-1b8a-11e8-8164-41cf94e47e59.png)

Click notification center and press esc to dismiss.

![image](https://user-images.githubusercontent.com/2193314/36735134-4d4b5604-1b8a-11e8-81dc-e73bb9686227.png)

Run the command again, there's a 1 not a 2 next to the bell:

![image](https://user-images.githubusercontent.com/2193314/36735168-604ac0aa-1b8a-11e8-9fd1-1850e6b7eb06.png)

**Comment by bpasero** [comment]
The issue here was that notifications that replace an existing one would count as new, which is wrong. I am now not incrementing the counter if a notification appears again that was already showing in the notifications center.
