### ISSUE TITLE
"namespace" as a property name gets highlighted in JavaScript

### ISSUE THREAD

**Issue by JamesDonnelly** [Microsoft/vscode#4458]
- VSCode Version: 0.10.11
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create a new JavaScript file.
2. Enter `foo.namespace`.

The property `namespace` gets highlighted, however I don't believe `namespace` has any meaning in JavaScript.

![image](https://cloud.githubusercontent.com/assets/2203377/13899598/47d56630-edea-11e5-9e4a-6b019e7bfdb1.png)

**Comment by JamesDonnelly** [comment]
It seems the word `any` also gets highlighted like this as well.

    foo.any

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#131
