### ISSUE TITLE
Notification button in high contrast theme has bottom outline is cut off

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44599]
VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.13.0-36-generic

---

#44319

![image](https://user-images.githubusercontent.com/2193314/36736498-a18fe470-1b8d-11e8-86d7-0d9f5d0cfc80.png)

**Comment by bpasero** [comment]
Looks like https://github.com/Microsoft/vscode/commit/9118c5a02f3eefd35862259858ce2a3f741ac876 fixed this one as well 🙌
