### ISSUE TITLE
Git: Provide single shortcut for "Stage Changes"/"Unstage Changes"

### ISSUE THREAD

**Issue by birgersp** [microsoft/vscode#44592]
I personally prefer to use the same keyboard shortcut for both "Stage Changes" and "Unstage Changes".

If I set the same keyboard shortcut for both, only one of them (namely, "Stage Changes") is enabled.

**Comment by joaomoreno** [comment]
@birgersp How did you configure those keybindings? Can you show me your keybindings.json?

**Comment by birgersp** [comment]
@joaomoreno Thanks for getting back to me so quickly! I configured the keybindings by opening the keybindings editor with "File"->"Preferences"->"Keyboard Shortcuts".

Then I double-clicked the "Stage Changes" command, and pressed CTRL+T followed by ENTER to assign it. Did the same for "Unstage Changes".

My keybindings.json file looks like this:

```
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "ctrl+t",
        "command": "git.stage"
    },
    {
        "key": "ctrl+u",
        "command": "git.unstage"
    }
]
```

**Comment by joaomoreno** [comment]
Got it. What would prefer would happen if the file is both staged and unstaged?

**Comment by birgersp** [comment]
I am thinking wheter it should be staged or unstaged depends on the current selection. Meaning;

When the command is invoked, and
* If the file is selected among unstaged files: stage it
* If the file is selected among staged files: unstage it

For instance, pressing the keyboard shortcut here, would cause the file to be unstaged (since it is selected as a staged file):
![screenshot from 2018-02-28 09-43-33](https://user-images.githubusercontent.com/5260237/36778035-e3ab7200-1c6b-11e8-8d36-69a9e5eb1fe0.png)

**Comment by joaomoreno** [comment]
Notice that the command doesn't know about selection, only about the currently opened file. There's no current API to get a hold of that selection.

**Comment by birgersp** [comment]
Understood. Personally, I don't have any opinion as to what should happen if the file is both staged and unstaged.

**Comment by joaomoreno** [comment]
I suggest we just stage it.

**Comment by AB1908** [comment]
> I actually wanted to see whether there are hidden when clauses we could be used to detect which mode we are in, and set keybindings accordingly

@kumarharsh: Found anything about that `when` clause?

**Comment by kumarharsh** [comment]
Nopes ☹. The core team needs to answer this.

**Comment by joaomoreno** [comment]
@kumarharsh Maybe try something like `resourceScheme == git`.
