### ISSUE TITLE
findInFilesWithSelectedText 's functionality doesn't carry over to findInFiles

### ISSUE THREAD

**Issue by wba0** [Microsoft/vscode#44609]
- VSCode Version: 1.20.1
- OS Version:  High Sierra 10.13.2

Steps to Reproduce:

1. Select some text in an editor window.
2. Press shortcut for `workbench.action.findInFiles`. No search is triggered for finding the selected text in the workspace's files (as was the case with `workbench.action.findInFilesWithSelectedText` which was removed in latest version). 

Does this issue occur when all extensions are disabled?: Yes

Can the functionality of the old findInFilesWithSelectedText be provided somehow with the new findInFiles command or another workaround?

**Comment by roblourens** [comment]
That should work. Can you try in 1.21? (Releasing in a day or two, or try it in Insiders now)

**Comment by wbonneyache-carecloud** [comment]
Yes it works now, thank you.
