### ISSUE TITLE
Extensions viewlet in high contrast theme is not very high contrast when running in extension dev host

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44601]
VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.13.0-36-generic

---

I'm guessing they're greyed out because they're automatically disabled, some of the text is very difficult to read:

![image](https://user-images.githubusercontent.com/2193314/36736619-f2ac4772-1b8d-11e8-8238-3be5aac4d4bf.png)

**Comment by sandy081** [comment]
Added a new label `disabled` to the list item. Text is greyed out only in light and dark themes.

![image](https://user-images.githubusercontent.com/10746682/37464615-dba9aa8a-287e-11e8-908e-624d5858d6f5.png)


![image](https://user-images.githubusercontent.com/10746682/37464597-cc8b594a-287e-11e8-9299-685ea24c75c3.png)
