### ISSUE TITLE
Allow to theme the white color in the progress badge

### ISSUE THREAD

**Issue by tweakimp** [microsoft/vscode#44604]
![clock](https://user-images.githubusercontent.com/20489521/36736814-c46d0bde-1bd9-11e8-82ad-06762a65de53.png)

I am currently building a theme and want to change the color of the clock that is white inside the yelloq circle. It's color is `#ffffff` and i changed all colorsettings in my theme file that had that hexcode to a different color, but the clock stays at `#ffffff`.

There is a foreground color option for numbers (and text in general i suppose) that i already changed, it looks like this:

![oneoncircle](https://user-images.githubusercontent.com/20489521/36736997-41127142-1bda-11e8-913d-faba919d88f7.png)

**Comment by bpasero** [comment]
Happy for help if someone has ideas. The challenge is to make it possible to theme the white background of that progress icon (living in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/progress/browser/media/progressService2.css#L14). 

It should leverage the `activityBarBadge.foreground` for the color that is currently white and `activityBarBadge.background` for the color that is currently blue. 

/cc @aeschli

**Comment by tweakimp** [comment]
My proposal:
move away from an image to a unicode character like `U+1F552` 🕒

**Comment by raygervais** [comment]
Question, how does one make the clock icon appear from repo version of Code? I'm currently working on this, but I need to figure out how to visually see the icon. Ideas?

**Comment by bpasero** [comment]
@raygervais e.g. open a very large git repository and click refresh from the git viewlet. Or install an extension.

**Comment by tweakimp** [comment]
@raygervais You can also just check for updates and via right click on it and it will appear for a short time.

**Comment by svipben** [comment]
Also, you can download this extension [Notification Tester](https://marketplace.visualstudio.com/items?itemName=svipben.notification-tester) and use "Show Progress Badge" command.

**Comment by tweakimp** [comment]
Is this still being worked on? `"activityBarBadge.foreground"` is not doing anything as far as I know.

**Comment by balent** [comment]
I believe it should be possible with few steps:
1. Convert the SVG icon from base64 to text (xml)
2. Inline it into the HTML
    1. Maybe with something like `badge.innerHtml = "<svg><path fill="#fff""/></svg>"`
3. Use CSS "fill" property to change color of icon to the "activityBarBadge.foreground"

**Comment by misolori** [comment]
If anyone is interested, here is the code pointer to where the badge indicator is set:

https://github.com/microsoft/vscode/blob/af39a4d4fbfdc9864cddddfd8101c0f90b46448a/src/vs/workbench/browser/parts/compositeBarActions.ts#L212

https://github.com/microsoft/vscode/blob/af39a4d4fbfdc9864cddddfd8101c0f90b46448a/src/vs/workbench/services/progress/browser/media/progressService.css#L14-L17

**Comment by misolori** [comment]
Verification steps:

Install the [Notification Tester](https://marketplace.visualstudio.com/items?itemName=svipas.notification-tester) extension and run the `Start Progress Badge` command and modify the `activityBarBadge.foreground` color token via:

```jsonc
"workbench.colorCustomizations": {
        "activityBarBadge.foreground": "#ff0000"

}
```

The icon should now inherit the same color.
