### ISSUE TITLE
Using horizontal scroll with mouse breaks search text boxes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4461]
*Found in test tour https://github.com/Microsoft/vscode/issues/3719*

- VSCode Version: 0.10.12-alpha
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Find in files
2. Expand options
3. Use <kbd>shift</kbd>+`mouse wheel` to attempt to scroll "files excluded through settings text box"

Observe the truncated text is just shifted over, not scrolled correctly:

![image](https://cloud.githubusercontent.com/assets/2193314/13902126/000204ee-edf9-11e5-9e14-9230d21743ea.png)

**Comment by bpasero** [comment]
@Tyriar we are not doing the truncation but use CSS and Chrome, can you try to reproduce in Chrome by copying the CSS we use and file a bug against them in case you see it?

**Comment by Tyriar** [comment]
You're right, it's an upstream issue. Reported https://bugs.chromium.org/p/chromium/issues/detail?id=596804#

**Comment by bpasero** [comment]
:+1:
