### ISSUE TITLE
Discuss upper bound for color decorations

### ISSUE THREAD

**Issue by GlenCFL** [microsoft/vscode#44615]
I have an extension for item filters, [item-filter-code](https://github.com/GlenCFL/item-filter-code). Item filters are single file, with no concept of importing whatsoever. The most popular item filter is [Neversink](https://github.com/NeverSinkDev/NeverSink-Filter/releases/latest), which is nearing 5,000 lines. There are around 1,030 color decorations within this file.

The issue is that there seems to be a hard cap on the number of color decorations available within each editor. If you were to open Neversink with the extension installed, then the color decorations will cut off midway through the file. I believe that [this is the line](https://github.com/Microsoft/vscode/blob/1.20.1/src/vs/editor/contrib/colorPicker/colorDetector.ts#L20) where the limit is set to 500.

I realize that this is likely done for performance reasons. My first thought was just to figure out which lines were visible within the editor and filter color decorations based on that; however, I don't believe this is currently possible with the current API, as I couldn't really find a way to determine the visible lines within an editor.

**Comment by jrieken** [comment]
We have proposed api for visible ranges of an editor (see https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L642) but for *validation* purposes you really shouldn't use UI state but simply compute diagnostics and hand them over. You are right, the cap is done performance reasons because extensions could overload us. I wonder in what situations more than 500 diagnostics are actionable?

**Comment by jrieken** [comment]
@GlenCFL Yeah, we are discussion "semantic" highlights in this issue https://github.com/Microsoft/vscode/issues/51104. Do mind me closing this as dupe?

**Comment by GlenCFL** [comment]
@jrieken
Highlights would work so long as it does support color ranges, with the color picker and everything, so go ahead.

**Comment by jrieken** [comment]
For colors and to support the color picker we have [`DocumentColorProviders`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3384). With those, you can add color boxes and support the picker. Would that help you?

**Comment by GlenCFL** [comment]
That goes back to the original issue, where there is a hard cap of 500 decorations within each text editor. The `provideDocumentColors` callback that you provide when creating one of these providers isn't called whenever the user stops scrolling in the editor, so we cant update decorations appropriately.

**Comment by jrieken** [comment]
wow - yeah, this was a big mis-understanding... I figured this is about an upper-cap of diagnostics, not colors... Moving to @aeschli

**Comment by aeschli** [comment]
The [limit]([this is the line](https://github.com/Microsoft/vscode/blob/1.20.1/src/vs/editor/contrib/colorPicker/colorDetector.ts#L20) ) is in the editor code.

**Comment by GlenCFL** [comment]
As an update to this, that item filter now has 1,300 color values, with the cutoff being about 43% into the file. I'd expect this number to increase to around 1,500 over the next six or so months.
