### ISSUE TITLE
Intellisense not working with python

### ISSUE THREAD

**Issue by therobwn** [Microsoft/vscode#44614]
- VSCode Version:1.20.1
- OS Version: Windows 10 Home

I updated to 1.20.1 on VS Code and now my intellisense has stopped working with python files. I have looked at my settings and could not find anything wrong.

**Comment by tsalinger** [comment]
This does not seem to be a VS Code specific issue. Please open an issue in the extension's [repository](https://github.com/redhat-developer/vscode-java/issues).
