### ISSUE TITLE
first typed characters are lost when starting a new integrated terminal 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#44613]
My typical workflow for using the integrated terminal is this:
- I'm in the debug viewlet
- In the panel at the bottom the debug console is active
- I activate the terminal by clicking its tab and start immediately typing
- after pressing return some error occurs because the first 5-10 characters are lost because the terminal was not ready to accept them

It would be great if those typed characters could somehow be buffered so that they don't get lost.

**Comment by Tyriar** [comment]
There is actually already a buffer set up to do just this, could you be seeing https://github.com/Microsoft/vscode/issues/40416?

What platform are you on?

**Comment by weinand** [comment]
Yes, that could very well be a dup of #40416.
I'm seeing this on macOS.
