### ISSUE TITLE
Copy Lines Keyboard Shortcuts not working

### ISSUE THREAD

**Issue by aweebit** [Microsoft/vscode#44616]
- VSCode Version: 1.20.1
- OS Version: Windows 10 Version 1709 OS Build 16299.248

Steps to Reproduce:

1. Click into a text line
2. Press `Shift + Alt + DownArrow` or `Shift + Alt + UpArrow`

Does this issue occur when all extensions are disabled?: Yes

I want to use the `editor.action.copyLinesDownAction` (`Shift + Alt + DownArrow` ) and `editor.action.copyLinesUpAction` (`Shift + Alt + UpArrow`) keybindings. When I try to use them in the editor, nothing happens. (There're no shortcut conflicts.)

When I click "Define Keybinding" in keybindings.json ant try to enter the shortcuts there, I only see `shift+alt+` for some reason. It doesn't detect Down and Up arrows, but they are detected within other key combinations.

I don't want to change the keybindings though.

**Comment by alexandrudima** [comment]
@aweebit

That means that `shift+alt+downarrow` and `shift+alt+uparrow` do not reach VS Code.

Here are some reasons why this would happen:
1. (most likely) you have a program/driver/service running that eats up this keybinding. 
2. (less likely) you have configured a keyboard shortcut in the OS.
3. (least likely) your keyboard is broken and this key combination is not registered.

I will close for now, as there is nothing to do here for us. AFAIK there are certain GPU drivers out there that like to eat arrow keys to rotate the screen, but you can search online...
