### ISSUE TITLE
Dragging a sash with alt to the far side of the window causes the other sash to move

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#44621]
Testing #44127

Steps:

- Go into centered layout mode using the command `Toggle Centered Layout`
- Hold alt and drag a sash far to the side, beyond the window

Expected: Once the sash has reached the end of the window, continuing to drag will do nothing
Actual: The sash on the other side begins to move outward

![centered_drag](https://user-images.githubusercontent.com/3672607/36744895-d71d40d2-1ba2-11e8-99ed-0c224daa2d7a.gif)

**Comment by isidorn** [comment]
Pushed some code which brings back this behavior.
Reopening

**Comment by bpasero** [comment]
@isidorn maybe this should be looked at when doing the widget for https://github.com/Microsoft/vscode/issues/50936

**Comment by isidorn** [comment]
@bpasero makes sense, let me assign this to June

**Comment by isidorn** [comment]
This is fixed in latest with the new split view math - yeee
