### ISSUE TITLE
Polish built-in extensions 

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#44626]
- [x] Naming
   - correct classification into "Language Basics" and "Language Features"
  - JSON is wrong
- [x] Each extension should have a version number >= 1.0.0
- Each extensions needs a reasonable and correct description
   - [x] JSON
  - [x] emmet
  - [x] go
  - [x] php
  - ...
-  [x] Same icon for all language basics extensions
-  [x] Same icon for all color themes
-  [x] Separate icon for the SETI file icon theme @kieferrm 
- Branded icons for Language Features and full-fledged functionality (Can we reuse the SETI icons?)
	- [x] TypeScript @mjbvz 
	- [x] Emmet @ramya-rao-a
	- [x] HTML @aeschli 
	- [x] JSON @aeschli
	- [x] CSS @aeschli
        - [x] Markdown @mjbvz 
        - [x] php @kieferrm 
- [x] Sort by kind (meta info?)
- [x] Search by display name, not just extension id
- [x] Test contribution and details pages for each built-in extension
   - Configuration Editing - Contributions tab needs to be improved #44725

**Comment by aeschli** [comment]
I came up with some icons for CSS/JSON/HTML inspired by Microsofts C#/C++ extensions

![image](https://user-images.githubusercontent.com/6461412/36790182-4d2cc224-1c94-11e8-841a-8ece665c174c.png)

**Comment by ramya-rao-a** [comment]
Emmet done.

<img width="433" alt="screen shot 2018-02-28 at 11 23 01 am" src="https://user-images.githubusercontent.com/16890566/36808378-c53f27cc-1c79-11e8-8506-0e63997c3530.png">

**Comment by kieferrm** [comment]
Php and seti done.

**Comment by mjbvz** [comment]
@aeschli  Are you planning to split css/html/json into language features + language basics ? I've done this for markdown and TypeScript but don't know if people have been asking to be able to disable just the language features on any other languages

**Comment by ramya-rao-a** [comment]
@kieferrm Now that we support searching based on display text as well as having a single icon for all themes and a single icon for language basics, and the rest having different icons, we are at a much better place. I would suggest to move the sorting part to next iteration and close this issue

**Comment by ramya-rao-a** [comment]
Sorted to show themes in the end. That completes the final task on this list

**Comment by aeschli** [comment]
@mjbvz Yes, I will do that for the next release.
