### ISSUE TITLE
Feature Request: Open symlinked file in target language

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44627]
Testing #44097

Let's say you have a symlink `foo` -> `bar.js`. Would be great to detect target language and use it for opening up `foo`.

Not necessarily a bug just nice to have.

**Comment by isidorn** [comment]
This is a fair feature request.
@bpasero maybe you could provide a pointer where we detect file types? Or we do all of this based on `uri` and this would require more work?

**Comment by bpasero** [comment]
@isidorn good morning :D. yeah all of it is done via path mapping to languages. There is no notion of symlinks on that layer.
