### ISSUE TITLE
HTML path completions to folders.

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#44629]
Testing https://github.com/Microsoft/vscode/issues/44460

When autocompleting folders, I was expecting a '/' to be appended at the end. 
That's the behavior when typing in a terminal, I write the first letters of the folder, hit `tab`, and then start typing the next nested folder.

Also, I would suggest adding `..` as a completion item.

**Comment by octref** [comment]
This is as-designed. After tab people can type `/` for furthering completion or choose to end completion here.

The second suggestion might make sense. Let's see if other users submit feature request for it too. I personally wouldn't want it.
