### ISSUE TITLE
Add a command to go to previous or next panel item

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44625]
Add a command to go from Problems -> Output -> Debug Console -> Terminal and the reverse (or whatever panel item is active, in their order).

Ctrl+Q is not what I want. I do not want to press Ctrl+Q 10 times to do that when I want to switch between task/terminal.
I also don't want to assign 4 shortcuts for going directly to Problems / Output / Debug Console / Terminal.

This remains one of the few things in VS Code where I have to resort to mouse.

I hope the same command can be added to viewlets switching.

Related: https://github.com/Microsoft/vscode/issues/15262

**Comment by isidorn** [comment]
This is a fair feature request. Let's consider adding it if more users ask for it.

@octref can you elaborate how you would expect this command to work? If you are in a panel it swtiches to the next panel, if you are in a viewlet next viewlet. But what if you are focused in the editor?
Or you would expect two different commands?
What you expect a default keybinding, if yes then which one?

**Comment by octref** [comment]
I don't use the current Ctrl-Tab and Ctrl-Shift-Tab for switching between editors. I suggest having Ctrl-Tab and Ctrl-Shift-Tab go to next/previous editor/viewlet/panel-item when focused on different areas. This also aligns with Chrome/Sublime behaviors.

Behavior wise, using Cmd+J/B and then Ctrl+Tab and Ctrl+Shift+Tab is much easier to remember than 9 different Cmd+Shift+Something that pinpoint the 5 Viewlets and 4 Panels. Looking forward, if we start to allow more Viewlet / Panel Items the navigability will become worse.

To be honest one of the main things that block me from using any task is having no way to switch between terminal and task output without a mouse. If I just have terminal, I have bound Cmd+`[` and Cmd+`]` to switch to next/prev terminals so I can at least switch between different outputs without needing to reach for mouse. I've dropped tasks from all my extensions for this reason.

https://github.com/vuejs/vetur/commit/502017a7f9925cdb68c961d4b4d88478563b5a41#diff-7fde71560fa9376d2d93a25b42d719f5
https://github.com/octref/vscode-extension-template/commit/a517fa18079e31cdb98446ff2e742ec7c2d1fd65#diff-7fde71560fa9376d2d93a25b42d719f5
https://github.com/octref/polacode/commit/79f9f199b7a4b3a68fd62d7965ccd96520d09e68#diff-bbd9f4180a5ba17654247e78ef4c88e0

For similar reason I'm also trying to move away from Debug Console to Chrome Dev Tools.

**Comment by isidorn** [comment]
I agree having this would be nice to have, however changing the default behavior of ctrl+tab will break so many users muscle memory that I do not think it is smart to do.

Imho we shuold have a command that switches with no default keybinding.
PR that add this are welcome
code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/panel/panelActions.ts#L37

**Comment by octref** [comment]
I updated the PR at https://github.com/Microsoft/vscode/pull/59270 to fix this issue, thus reopening.

Once the PR is in, I'll open a new PR for the new ContextKeys, `panelFocus` and `sidebarFocus`.
