### ISSUE TITLE
vscode.commands.executeCommand('workbench.action.openEditorAtIndex1') does not resolve

### ISSUE THREAD

**Issue by arussellk** [Microsoft/vscode#44636]
**Version info:**
- VSCode Version: Version 1.20.1 (1.20.1)
- OS Version: macOS 10.13.3 (High Sierra)

**Summary of issue:**
When running an extension, the promise returned by `vscode.commands.executeCommand('workbench.action.openEditorAtIndex1')` does not resolve if there is an editor which corresponds to the given index. I noticed this behavior because I tried to `await` this command from some automated tests in the VSCodeVim repo.

I made a small extension to demonstrate the unexpected behavior: https://github.com/arussellk/vscode-workbench-action-openeditoratindex1-bug-repro

The relevant code and comments are in `src/extension.ts`.

**Steps to Reproduce:**
1. Open the above project in VSCode
2. Launch the extension with `Debug > Start Debugging` or `F5`
3. In the window that just launched, execute the editor command `Hello World` (for macOS users, `cmd+shif+P` then type `Hello World` and press enter)
4. View the debug console to see that `openEditorAtIndex1` was never logged

**Expected behavior:**
I expect the promise from the command to resolve or fail every time it is called. It appears that when there is an editor that corresponds to an index, that promise neither resolves nor rejects.

Does this issue occur when all extensions are disabled?: Yes

Let me know if you want any additional information.

Thanks! =)

**Comment by jrieken** [comment]
verified by review
