### ISSUE TITLE
Rendering Markdown preview slower if not visible in an editor group

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#44631]
- VSCode Version: 1.21.0 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open two markdown files
2. Open the markdown preview to the side in another editor group
3. Set focus back and forth between the two markdown files and see the markdown preview update quickly.
4. Now move one of the markdown files to the editor group with the preview so the preview is not visible.
5. Use the tabbed header to make the preview visible.
Notice that it takes about 1/2 a second to render the preview and you initially see a blank screen.
Found during testing #44463

**Comment by mjbvz** [comment]
Yes the second case is slower since we have to recreate the webview behind the scenes. The main question is: is the behavior in 1.21-insiders slower than it was in 1.20? After testing this, I don't think it is. @gregvanl Let me know if you think there is a regression over 1.20
