### ISSUE TITLE
Moving search with the pencil icon causes the search contents to be replaced

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#44637]
Testing #44215 

When you move the search between positions with the pencil icon, the new setting is highlighted in the editor. When the search panel is moved the highlighted text is used as the search input. This one is interesting though because the replacement happens on the current position, so you have to move it back and forth to see the results due to interaction with #44491

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/44491
