### ISSUE TITLE
Default theme not showing in Color Theme Preference in Command Palette

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#44644]
re #44361

* Open Workspace A
* Show builtin theme, disable Solarized Light
* Reload
* Open Workspace B or empty workspace
* Open Command Palette -> Preference: Color Theme
* Solarized Light is not there but it's not disabled for current workspace

Good part, if I search Solarized, I see Solarized Light again and I can choose it.

**Comment by sandy081** [comment]
@rebornix Did you disable the them globally or for workspace?

**Comment by bpasero** [comment]
Ping?

**Comment by rebornix** [comment]
I no longer see this issue anymore.
