### ISSUE TITLE
Alt-click on terminal for jumping to position should be diabled for shell 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44642]
Testing #44448

When doing alt-click on the terminal shell (not opening Vim/Nano/etc yet), the keypress sequences sent to terminal are some left -> some up -> some right.

This causes issue since in shell, the default behavior of up arrow is going back to previously entered command.

Alt-click should be disabled for this case.

**Comment by Tyriar** [comment]
I think we should detect whether a shell is active via a hardcoded list and _only_ do horizontal movement in that case. Need to figure out how to allow this nicely in xterm.js as only vscode knows about the process name.

**Comment by Tyriar** [comment]
Created upstream issue https://github.com/xtermjs/xterm.js/issues/1305

**Comment by richardfickling** [comment]
Is it possible to disable this feature entirely? It messes up tmux, which uses alt-click to select/copy text.

**Comment by Tyriar** [comment]
@richardfickling seems to work as expected in tmux (mac I'm presuming?), I could do both without issue in Insiders https://code.visualstudio.com/insiders

**Comment by richardfickling** [comment]
When i alt-click in tmux (insiders Version 1.22.0-insider (1.22.0-insider), mac), it still scrolls. See https://imgur.com/a/IztJn (I clicked on "require" and "function"). Is there anything I can add to help reproduce?

**Comment by Tyriar** [comment]
@richardfickling so alt+*click* will scroll, but alt+*drag* will select.

**Comment by richardfickling** [comment]
ah, yeah that would do it. I alt+doubleclick to select a single word in the terminal to copy. Not a huge issue, as I can just alt+drag to select the word instead.

**Comment by Tyriar** [comment]
@richardfickling that's a good point that it will break double/triple click selection. Maybe there should be a setting to drive this... @joaomoreno any opinions on this?

**Comment by joaomoreno** [comment]
I see the same _scroll_ behaviour. Maybe click shouldn't do anything, yet double and trip click should.

**Comment by Tyriar** [comment]
@joaomoreno as in wait to determine whether a click is single or double+ and then do the alt click cursor move after we're sure?

**Comment by joaomoreno** [comment]
Oh, single click moves the cursor. I wasn't aware of that! Nevermind that suggestion then.

**Comment by Tyriar** [comment]
Moved to https://github.com/Microsoft/vscode/issues/47201
