### ISSUE TITLE
Find matches not working in svg

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#44645]
Issue Type: <b>Bug</b>

When trying to find all matches of a string in an SVG file, either with "find matches" or using the fint/replace UI, obvious matches are not found:

<img width="1068" alt="screen shot 2018-02-27 at 2 48 38 pm" src="https://user-images.githubusercontent.com/835148/36751235-99f92a1a-1bcd-11e8-806d-92f9d5bc1e2f.png">

Sample code:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="141" height="136" viewBox="0 0 141 136">
  <g fill="none" fill-rule="evenodd" stroke-width="3" transform="translate(2 2)">
    <g stroke="#3E54A4" stroke-linecap="round">
      <path d="M0 68.4063448C0 30.6270345 30.6270345 0 68.4063448 0 80.6732414 0 92.186069 3.22868966 102.142207 8.88344828M43.1533793 132C28.5256552 126.185931 16.3786207 115.471172 8.7377931 101.884276M136.81269 68.4063448C136.81269 97.2066207 119.013931 121.849655 93.8171034 131.937793"/>
      <path d="M42.2961379 20.1307586C50.1281379 15.8536552 59.1117241 13.4215172 68.6642759 13.4215172 90.86 13.4215172 109.989379 26.5471724 118.715034 45.4595862M122.045379 82.185931C115.964276 105.997517 94.3708966 123.603586 68.6642759 123.603586 38.2390345 123.603586 13.5732414 98.9393103 13.5732414 68.5125517"/>
    </g>
    <g stroke="#3E54A4" transform="translate(35 32)">
      <path d="M47.2484138,33.389931 L65.2626207,51.4041379 C69.3424828,55.484 69.3424828,62.0961379 65.2626207,66.176 L65.2626207,66.176 C61.1827586,70.2558621 54.5706207,70.2558621 50.4907586,66.176 L33.2533793,48.9386207"/>
      <polyline stroke-linejoin="round" points="30.692 26.682 20.946 16.935 20.92 11.388 10.474 .942 .029 11.388 10.474 21.833 16.021 21.859 25.552 31.39"/>
      <path stroke-linecap="round" d="M46.4852414,47.3986207 L56.3336552,57.2470345"/>
    </g>
    <g stroke="#3E53A4" stroke-linecap="round" stroke-linejoin="round" transform="translate(33 30)">
      <path d="M39.5973,45.7504 C41.1023,44.2404 42.6203,42.7434 44.1203,41.2274 C47.1593,38.1544 48.0683,37.1064 50.0053,35.8374 C50.9053,35.2484 51.8113,34.7534 52.9793,34.4124 C54.4763,33.9774 55.7843,33.9764 56.6353,34.0404 C58.2723,33.9154 61.2083,33.4684 64.2553,31.6244 C65.6263,30.7954 70.3873,27.6474 71.9383,21.3404 C73.5033,14.9744 70.6753,9.9564 70.0793,8.9484 C66.8853,12.1484 63.6903,15.3484 60.4963,18.5484 C58.4383,20.2254 55.5363,19.9194 54.0953,18.1804 C52.9483,16.7964 52.8493,14.6544 53.9243,12.9394 C57.2233,9.5644 60.5223,6.1904 63.8223,2.8154 C62.9173,2.2794 57.4913,-0.8166 50.8113,1.1424 C44.6483,2.9494 41.7213,7.7974 40.8983,9.3204 C39.4663,11.9714 39.0553,14.4524 38.9223,15.9604 C38.9113,16.5184 38.8803,17.3044 38.7913,18.2424 C38.7323,18.8774 38.6653,19.5774 38.5443,20.1624 C38.3823,20.9414 37.9863,22.1694 36.8713,23.5704 C30.5803,29.8594 9.39083203,49.9803594 3.09983203,56.2683594 C-0.222167969,59.7763594 -0.190167969,65.2503594 2.95183203,68.5663594 C6.32083203,72.1193594 12.307832,72.1863594 15.902832,68.4433594 C15.902832,68.4433594 37.7353,47.6194 39.5973,45.7504 Z"/>
      <path d="M13.0935008,64.824 C10.8265008,66.275 7.98550079,65.71 6.71250079,63.895 C5.76050079,62.538 5.76450079,60.6 6.71250079,59"/>
    </g>
  </g>
</svg>
```

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:09:52.377Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.4.2
code-settings-sync|Sha|2.8.7
sort-lines|Tyr|1.4.1
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.1
project-manager|ale|0.24.0
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
prettier-vscode|esb|1.1.3
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.8.1
vscode-text-pastry|jkj|1.2.0
svg|joc|0.0.9
Angular2|joh|2.14.0
vscode-icon-theme|jtl|1.6.1
ecdc|mit|0.11.0
HTMLHint|mka|0.4.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
polacode|pnp|0.2.2
stylelint|shi|0.33.0
Align|ste|0.2.0
bootstrap4-vscode|the|4.0.0
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
We find two occurrences of `stroke="#3E54A4"` and that's the same as other editors. Can you elaborate more on why it's not working for you?

**Comment by smlombardi** [comment]
never mind, I see an error in the svg itself.  Those 3 colors should match, they are off my one digit.
