### ISSUE TITLE
Java Tutorial didn't work

### ISSUE THREAD

**Issue by ksnyde** [Microsoft/vscode#44649]
I have the latest version of modern versions of all Java deps:

JDK: `9.0.4`
Maven: `3.5.2`

I and am running on MacOS and cloned the gs-spring-boot as described. When I open a source file 
I am immediately given the error:

> Classpath is incomplete. Only syntax errors will be reported

With optimism flowing eternal, I hit F5 to see if it will compile. Nada. Sadness ensues. I having written a line of Java since the 1990's so I'm completely out of my element and was hoping that the hand-holding of this 101 tutorial would at least give me a "hello world" moment.

**Comment by ksnyde** [comment]
Oh also worth mentioning that I _do_ have the following plugins:

- Language Support Java(TM) by Red Hat (not the other Language Support module)
- Debugger for Java
- Maven for Java
- Java Etension Pack

I also shutdown vs-code and restarted hoping that might kick things into a higher gear.

**Comment by ChrisColeTech** [comment]
I can confirm this issue.

The Java tutorial on visualstudio.com must be missing a few steps, the app doesn't run if you are following the tutorial.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1462
