### ISSUE TITLE
Bad node runtimeVersion can get debugger stuck

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44643]
Testing #44452

Issue Type: <b>Bug</b>

**Steps to reproduce**
1. Install nvs
1. Run `nvs use 9.6`
1. Start vs code
1. Try launching a node program with ` "runtimeVersion": "8.9",`

**Bug**
See the error message:

```
Node.js version '8.9' not available via any Node.js version manager.
```

Then the debugger seems to get stuck. The progress indicator in the debug UI never goes aay

Also in developer console (perhaps unrelated):

```
log.ts:171   ERR Cannot read property 'indexOf' of null: TypeError: Cannot read property 'indexOf' of null
    at f (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:155:316)
    at ChildProcess.<anonymous> (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:156:84)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T09:01:48.555Z)
OS version: Windows_NT x64 10.0.17052

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz (6 x 1896)|
|Memory (System)|31.93GB (16.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe .|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces only with extensions

**Comment by weinand** [comment]
@isidorn after this error message I just return an `undefined` from `resolveDebugConfiguration`. This should abort the debug session (or prevent the session from being started).
I don't know what more I can do on my side.

**Comment by isidorn** [comment]
@weinand I suggest to try to return an `error` instead of `undefined`. if that does not work I can investigate in debt week.
Code pointer on vscode side to investigate what is going on 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L282

**Comment by isidorn** [comment]
This works great for me in latest. I get a nice error dialog saying
@mjbvz please try it with latest insiders and let me know if you still see it. Thanks

![screen shot 2018-03-14 at 12 54 04](https://user-images.githubusercontent.com/1926584/37400947-d1ca0242-2786-11e8-9f96-d9c2040db172.png)

**Comment by isidorn** [comment]
Closing as I can not reproduce. @mjbvz please let me know if you still see it and I will reopen
