### ISSUE TITLE
Unable to Copy and Paste

### ISSUE THREAD

**Issue by stanleykylee** [Microsoft/vscode#44655]
### Issue Type
Bug

### Description

Open Visual Studio Code and try to copy and paste. Using the right click menu or the shortcut keys also have the same problem. 

Copying from any external application does not allow pasting into Visual Studio Code either.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|Load (avg)|4, 6, 5|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/stanl/cbsupporthome/cases/58305|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-docker|Pet|0.0.24
markdown-preview-github-styles|bie|0.1.0
code-runner|for|0.8.7
markdown-shortcuts|mdi|0.8.1
python|ms-|2018.1.0
java|red|0.19.0
spellchecker|swy|1.2.13
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.2
markdown-all-in-one|yzh|1.0.5

</details>
Reproduces only with extensions

**Comment by stanleykylee** [comment]
Looks like it's related to #24112?

**Comment by mjbvz** [comment]
@stanleykylee Does this only happen when extensions are enabled? Can you try selectively disabling them to figure out which one may be breaking things

**Comment by leopoldkristjansson** [comment]
Just to provide more information. I had this same issue with VS Code January 2018 (version 1.20). I had none of the extensions that @stanleykylee had. However, when I disabled all of my extensions, "copy/paste" using keyboard started working again (using the mouse and right clicking to "copy/paste" never stopped working in my case). 

I systematically activated my extensions again one by one until I had activated all of them. No extension seemed to cause the issue again and now all works as expected.

**Comment by stanleykylee** [comment]
@mjbvz I did some testing finally on this and it looks like it only happens when I launch Visual Studio Code via the command line (execute `code .` from iTerm). I'm using iTerm and tmux at the same time.

However, when I launch Visual Studio Code via the MacOSX UI the problem doesn't appear. As long as there is a Visual Studio Code open I can then go back and execute the same command line with no issues.

**Comment by leopoldkristjansson** [comment]
After reading @stanleykylee last comment I can also say I used `code .` to open the folder where I had this happen. Never used `code .` before and also never had this happen before.

**Comment by Tyriar** [comment]
I have received reports of copy/paste being flaky in the terminals or only being about to paste within the window, not in another program, but could never reproduce.

**Comment by bpasero** [comment]
@stanleykylee are you running Code from a TMUX session?

**Comment by stanleykylee** [comment]
@bpasero yes. I use iTerm2 and run tmux. From the tmux session, I launch Visual Studio Code from the working directory via the command line `code .`.

@Tyriar is there anything I can do to try to help reproduce this? I can try this on another system with a fresh Visual Studio Code install and see if this happens again?
