### ISSUE TITLE
Search commands for cycling Include/Exclude Pattern in command palette do not work

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#44654]
Issue Type: <b>Bug</b>

The commands showPreviousExcludePattern, showPreviousIncludePattern, showPrevious as well as their next counterparts do not work from the command palette. Although minor, these should work as long as the search view is visible.

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T09:01:48.555Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by roblourens** [comment]
@sandy081 I see you added the line to only enable the actions when e.g. `PatternIncludesFocusedKey` is true. That should be set for the keybindings but I think the action itself should be enabled whenever the viewlet is visible. I'll change it, let me know if I've got it wrong.
