### ISSUE TITLE
Warn when using ${workspaceFolder} in a multiroot workspace

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44658]
Testing #44447

**Steps to Reproduce:**
1. In a multiroot workspace:

```
{
	"folders": [
		{
			"path": "/Users/matb/projects/a"
		},
		{
			"path": "/Users/matb/projects/b"
		}
	],
	"settings": {
		"launch": {
			"version": "0.2.0",
			"configurations": [
				{
					"type": "node",
					"request": "launch",
					"name": "Launch Program",
					"program": "${workspaceFolder}/index"
				}
			]
		}
	}
}
```

    (The settings were migrated automatically from my workspace settings)

1. Try debugging

**Bug**

![screen shot 2018-02-27 at 1 57 29 pm](https://user-images.githubusercontent.com/12821956/36757376-3ef6b526-1bc6-11e8-865b-37d835c89148.png)

This error makes sense but what you need to do to address it is not very clear. We should something in the message about needing to use `${workspaceFolder:X`} in multi-root workspaces 

Possibly related to #44449

**Comment by weinand** [comment]
This problem should never hit the debug adapter like this.
VS Code should prevent that launch configs with unresolved variables are started.

**Comment by isidorn** [comment]
Nice try bot
Duplicate of https://github.com/Microsoft/vscode/issues/44411
