### ISSUE TITLE
Zen mode restore setting restores only full-screen

### ISSUE THREAD

**Issue by mhxion** [Microsoft/vscode#44652]
- VSCode Version: 1.20.1
- OS Version: Linux Mint 18.3 Cinnamon 3.6.7 64-bit

**Steps to Reproduce:**

1. Set Zen mode as default opening mode (if the exit is also in Zen mode) in `settings.json` by `"zenMode.restore": true`
2. Close VS Code within Zen mode by `CTRL+W` or `CTRL+SHIFT+W`
3. Reopen VS Code, the VS Code is in full-screen mode, not the **expected Zen mode**. 

Does this issue occur when all extensions are disabled?: Yes.

**Comment by isidorn** [comment]
I can not reproduce this.
@mhxion please try with latest vscode insiders https://code.visualstudio.com/insiders/

If you can reproduce still please give us exact steps how you enter zen mode, when do you change the setting and do you explicitly enter full screen

**Comment by mhxion** [comment]
@isidorn  
**Does this issue also persist in the Insider version?** - Yes.

**Detailed Re-procedure:**

![vs-code-insider-zenmode-bug-001](https://user-images.githubusercontent.com/21981508/36841271-6b7d0bf2-1d0d-11e8-9027-3989bbce3c0b.gif)

1. Open VS Code Insider normally. Go to `settings.json`
2. Add `"zenMode.restore": true` to enable.

> a window should restore to zen mode if it was exited in zen mode

3. Toggle to Zen mode. Close vs code within zen mode (`CTRL+Q` or `ALT>File>Quit`)
4. Restart vs code. The vs code is not in the expected Zen mode but rather in full screen mode. 

> The result is the same also if everything was done by using shortcuts.

**Comment by isidorn** [comment]
This is a general issue that we are not storing UX state for the no folder workspace.

We are storing zen mode per workspace, which means you need to open a folder first in oreder for this to be respected..
I could also store zen mode per user storage.

@bpasero do you already have an issue to preserve state across no folder workspaces

**Comment by bpasero** [comment]
@isidorn we store UX state for empty windows too, e.g. you can have an empty window with some UI state (e.g. editor layout), quit and restart and it will be restored.

I cannot reproduce on macOS btw.

**Comment by mhxion** [comment]
@isidorn I first faced the issue while working with a folder in a workspace. But as @bpasero found, it's possible that it's just in Mint/Debian. Maybe configuring a whole new screen state same-as-zen-mode for start up could fix the issue. I'm a big fan of VS code's Zen mode even as a noob, hope this gets fixed in future. Thanks for the hard work.

**Comment by bpasero** [comment]
If this only reproduces on Linux, this could be https://github.com/Microsoft/vscode/issues/36964 (@Tyriar)

**Comment by isidorn** [comment]
Yup, @mhxion please comment on that issue as this is a duplicate. Thanks
