### ISSUE TITLE
Only first TreeView.reveal works

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#44657]
Testing #44364:

My reveal command just calls the TreeView.reveal:
```js
  processViewer.reveal(newItem);
```
- If I run this command for the first time, it works fine and it opens a collapsed node to show its child.
- then I collapse the parent node again
- If I now use the command a second time, the item is not revealed but I see this error:
  ![2018-02-27_22-53-46](https://user-images.githubusercontent.com/1898161/36757138-158ce9b2-1c11-11e8-82fc-6263a6dd844f.png)

This problem prevented me from using "reveal" in code that detects model additions and tried to reveal the newly created items.

**Comment by sandy081** [comment]
@weinand Can I try to reproduce this using your processes extension?

The error means that the system does not have the node with id `1/27493`. Can you check if you are returning this element when `getChildren` method on your data provider is called?
