### ISSUE TITLE
Provide syntax highlighting for .gitignore files

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4465]
_Found in test tour https://github.com/Microsoft/vscode/issues/3719_

Comments (lines starting with `#`) at the very least should be highlighted.

**Comment by CodeZombieCH** [comment]
I recently created an extension to assist in working with `.gitignore` files. The current version includes syntax highlighting as you requested. You can find the extension in the [marketplace ](https://marketplace.visualstudio.com/items?itemName=codezombiech.gitignore) and on [GitHub](https://github.com/CodeZombieCH/vscode-gitignore).

**Comment by Tyriar** [comment]
Nice @CodeZombieCH! I think we may want to integrate the [basic syntax highlighting](https://github.com/CodeZombieCH/vscode-gitignore/blob/master/syntaxes/gitignore.json) into the core editor.

**Comment by chris-c-thomas** [comment]
Not sure if this is still of interest but I'd love syntax highlighting for .gitignore / .gitattributes / .gitmodules and so on.

**Comment by Tyriar** [comment]
@mjbvz there is one of these files in nearly every git repo, should syntax highlighting be built in?
