### ISSUE TITLE
Opening Relatively Pathed Markdown Files

### ISSUE THREAD

**Issue by Weasnerb** [Microsoft/vscode#44651]
- VSCode Version: 1.20.1
- OS Version: Windows 10 Pro Version 1703

Steps to Reproduce:

1. In your file system create a folder with a name that has a space in it.(Example: Test Me)
2. Within the created folder make 2 markdown files (Example: Test1.md and Test2.md) that have relative markdown links to each other. (`[Test 2](Test2.md)` in Test 1 and` [Test 1](Test1.md)` in Test 2)
3. Preview one of the markdown files and click on the link to take you to the other markdown file.
4. Get error `File not found (file:///c:/Test%20Me/Test1.md).` If you create the file, it will be created inside a newly created folder with a %20 instead of a space in the name. (In our case it makes the file Test1.md in the folder named `Test%20Me`)

![capture](https://user-images.githubusercontent.com/24311514/36753581-c7f8e4be-1bc3-11e8-957b-71f83b2c4a68.JPG)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

NOTE: Simular to [https://github.com/Microsoft/vscode/issues/1615](https://github.com/Microsoft/vscode/issues/1615)

**Comment by BobDankert** [comment]
Also experiencing this issue. Does not look to be the same issue as the potential duplicate linked by vscodebot.

**Comment by ryanclarke** [comment]
This seems to be fixed on version 1.28.1 (user setup) with Windows 10 1809.

**Comment by Weasnerb** [comment]
Can confirm this has been fixed!
