### ISSUE TITLE
Issue reporter: icon for duplicate issues are not aligned 

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#44659]
re #44457 

![image](https://user-images.githubusercontent.com/876920/36757731-2fe8b48e-1bc7-11e8-8131-3a8c357b69c9.png)

Maybe we should align the left border of icons instead of center.

**Comment by bpasero** [comment]
I think there are still issues:

![image](https://user-images.githubusercontent.com/900690/36842749-f1e80810-1d4c-11e8-86ae-87b881b09df3.png)

* the default height should be good enough to not cut issues in half
* the summary of each issue should be aligned at the same vertical spot
* as such, I would make the open/closed badge equal width
