### ISSUE TITLE
Add setting to enable/disable signature help

### ISSUE THREAD

**Issue by michaelsobczak-qeexo** [Microsoft/vscode#44653]
Not sure if I'm missing a setting here or if the feature is actually unable to be disabled. Thanks for any help on this

- VSCode Version: 1.20.1
- OS Version: Mac OSX High Sierra

Steps to Reproduce:

1. In Python (suspect it happens with other languages) when you type parentheses after a function and the tooltip pops up of the documentation for it (other ways to activate this)
2. The problem is that this behavior is unable to be disabled

Does this issue occur when all extensions are disabled?: Yes

In case it is relevant, here are all the editor settings I've tried to use to disable it (ones at the bottom referencing editor):

```
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/*.pyc": true
    },
    "editor.renderWhitespace": "none",
    "files.trimTrailingWhitespace": true,
    "editor.rulers": [
        80,
        100,
        120
    ],
    "window.zoomLevel": 0,
    "python.pythonPath": "/usr/local/opt/python/bin/python2.7",
    "python.linting.enabled": false,
    "editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": false,
        "functions": false,
      },
    "editor.suggestOnTriggerCharacters": false,
    "editor.wordBasedSuggestions": false,
    "editor.quickSuggestionsDelay": 1000,
    "editor.parameterHints": false,
    "editor.snippetSuggestions": "none",
    "editor.hover": false,
    "editor.minimap.enabled": false,
    "editor.renderControlCharacters": false,
}
```

**Comment by pradeepmurugesan** [comment]
@jrieken I would like to work on this. Any code pointer would be great..

**Comment by pradeepmurugesan** [comment]
For javascript adding 
```
"editor.parameterHints": false
```
to the settings disabled the parameter suggestion.

**Comment by jrieken** [comment]
There you go: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts#L85. The delay is indication if signature help was triggered automatically (because of typing) or manually invoked. I would start with a setting that is about automatic triggered.

**Comment by pradeepmurugesan** [comment]
@jrieken , @michaelsobczak-qeexo  I am not able to repro the issue.. The setting 

```
"editor.parameterHints": false
```

turns off the signature suggestion. Tried with Python and Javascript

**Comment by jrieken** [comment]
Ops, that's embarrassing... Seems like we already have the setting - pardon me, it's code I have inherited.

**Comment by jrieken** [comment]
Closing this as question
