### ISSUE TITLE
Terminal: Add button acts on terminal group but Delete button acts on each terminal

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44667]
Testing #44446

- The plus action on the panel adds new terminal group
- Alt+Plus button on the panel splits the terminal i.e adds to current group
- Delete button deletes current terminal in the current group

The context on these 2 buttons should be consistent
Either both act on the group and the alt acts on individual terminals or the other way around

**Comment by Tyriar** [comment]
I'm going to move split to the left of the bin icon to help with this, will need some feedback from UX on this though.

**Comment by Tyriar** [comment]
Closing as designed since no other complaints are come through. The split button is next to the delete button now, plus I don't think we should have a kill group command.
