### ISSUE TITLE
Lines don't re-flow in a split terminal when the previous terminal is deleted

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44663]
Testing #44446 in Mac

In the below case, a terminal is split twice and the one in the middle is deleted. The 3rd terminal which now becomes the second terminal grows to occupy the space, but its contents do not reflow to occupy the space

![terminal-use-space](https://user-images.githubusercontent.com/16890566/36759011-e4ac747a-1bca-11e8-8680-15231ae15b5c.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688
