### ISSUE TITLE
Search in panel interacts poorly with settings sync extension

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#44664]
Issue Type: <b>Bug</b>

Testing #44215 
With the VS Code Settings Sync extension enabled and auto-upload on settings change turned on, moving the search pane to the panel causes it to show for a few seconds, then settings sync extension changes focus to its output channel. This is an unfortunate circumstance and other extensions could also cause similar behavior. Workaround is to enable `sync.quietSync` but you will lose the verbose output.

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T09:01:48.555Z)
OS version: Windows_NT x64 10.0.16299

Reproduces only with extensions

**Comment by isidorn** [comment]
This is true for may of our settings and there is nothing I can do here unles you have a suggestion and then I can fix it.
Consider filing this against the extension to see if they can do something on their side.
