### ISSUE TITLE
Gitignored files color in Explorer lacks of contrast

### ISSUE THREAD

**Issue by JonGarbayo** [Microsoft/vscode#44669]
- VSCode Version: 1.20.1 Stable

Hi VS Code team!

I'm a new to this editor, I come from Atom, and previously Sublime Text.

Here is a screenshot from the Atom tree-view with some Git coloration:
<img src="https://user-images.githubusercontent.com/11503863/36759820-fa9ad90e-1c18-11e8-9800-18b5b94089e5.png" height="600px" alt="atom_tree-view"/>

And here the same project but in the VS Code Explorer, with same color and icons theme:
<img src="https://user-images.githubusercontent.com/11503863/36759864-171a0884-1c19-11e8-8e31-e901cbc49288.png" height="600px" alt="vscode_file-explorer"/>

I find the grey color used for gitignored files too similar to the standard color. It's not as evident as in Atom, where a single glance suffice.

Is it possible to make it darker? It could also be cool if the folders colors was the same as text, in the Atom way :)

Thanks!

**Comment by jrieken** [comment]
You configure via settings or create your own theme. See https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme, https://code.visualstudio.com/docs/getstarted/theme-color-reference. The colors in question are defined here: https://code.visualstudio.com/docs/getstarted/theme-color-reference#_git-colors

**Comment by JonGarbayo** [comment]
Thanks!
I didn't find these pages during my research, and I thought these settings were not part of themes, as I tried all of mines just to see if it could change the git decorations.
