### ISSUE TITLE
Issue reporter closed/open icons are not vertically aligned

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44660]
#44457

![image](https://user-images.githubusercontent.com/2193314/36757782-49837cbc-1bc7-11e8-9128-db008525dd45.png)

**Comment by bpasero** [comment]
This is https://github.com/Microsoft/vscode/issues/44659 I think.

**Comment by Tyriar** [comment]
#44659 is about horizontal alignment, this is about vertical which is still a problem:

<img width="219" alt="screen shot 2018-03-06 at 12 46 32 pm" src="https://user-images.githubusercontent.com/2193314/37057494-6a6bbc3a-213c-11e8-9f25-00d387df8c92.png">

**Comment by RMacfarlane** [comment]
![screen shot 2018-03-08 at 3 53 58 pm](https://user-images.githubusercontent.com/3672607/37183067-2820634a-22e9-11e8-8ddc-b84fb12dd5f7.png)
