### ISSUE TITLE
Cannot add keyboard shortcuts from the UI

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#44661]
Issue Type: <b>Bug</b>

1. From settings gear, open keybindings.
2. Select a command which does not have keybinding and click the plus (+) icon.
3. Enter a keystroke and press enter.
4. Receive the following error notification.
Cannot read property 'getUserSettingsLabel' of null

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T09:01:48.555Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by sbatten** [comment]
As a clarification, *existing* keybindings **can** be *changed* from the UI.

**Comment by ethanmoffat** [comment]
I'm seeing the same error. Code version:

> Version 1.21.0-insider
> Commit 1a84a882737184488d965426747a05474f54a759
> Date 2018-02-27T09:01:48.555Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

This is a fresh install with no extensions.
