### ISSUE TITLE
Resizing of split terminal loses the padding on top

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44668]
Testing #44446 in Mac

- Split the terminal when the panel is on the right
- Notice the healthy padding between the first line of text in the second terminal and the line that divides the 2 terminals
- Resize the height of the second terminal
- Healthy padding lost :(

![terminal-healthy-padding](https://user-images.githubusercontent.com/16890566/36759938-d7973b6e-1bcd-11e8-9377-73659442ee3f.gif)

**Comment by Tyriar** [comment]
This is as designed as the bottom terminal pane is aligned to the bottom to reduce jumping around when resizing the window
