### ISSUE TITLE
createWebview with same id should error out

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44665]
Testing #44466

For this extension:

```ts
import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

export function activate(context: vscode.ExtensionContext) {
  const htmlPath = path.resolve(context.extensionPath, 'media/index.html');

  vscode.commands.registerCommand('extension.sayHello', () => {
    const wv = vscode.window.createWebview(vscode.Uri.parse('foo:bar'), vscode.ViewColumn.Three, {});
    wv.html = fs.readFileSync(htmlPath, 'utf-8');
    wv.title = 'hello'
  });
}
```

Running the command `sayHello` multiple times, you end up with multiple webviews open but only the first one being updated.

**Comment by octref** [comment]
Also try running the command for a few times consecutively. Webviews after the first editor are blank at first. You need to switch away from them and then focus them again to see any content.

**Comment by mjbvz** [comment]
No longer applicable with ea1fed9. Webviews are now private objects owned by the extension that creates them. It is up to the extension to manage their ids
