### ISSUE TITLE
Changing layout should make the text in split terminals reflow to use the space

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44671]
Testing #44446 in Mac

- Below we have a terminal split twice. Due to lack of horizontal space, the third terminal wraps earlier than the others
- Change layout. Now all 3 terminals have same horizontal space, but the 3rd still wraps too early

![terminal-relayout-on-change](https://user-images.githubusercontent.com/16890566/36760445-ba42f6a0-1bcf-11e8-8c9c-80c8477002a6.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688
