### ISSUE TITLE
localResourceRoots should include extension folder in addition to workspace folder

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44677]
Testing #44466 

Feel this is a saner default.

**Comment by mjbvz** [comment]
Already covered by the `vscode-extension-resource` scheme. The `vscode-extension-resource` resources are always available regardless of the `localResourceRoots` setting

**Comment by octref** [comment]
> `vscode-extension-resource`

Can we start a documentation for the Webview early? I'm happy to set up yet another preview server where the team can see early documentation and give feedback. It would be nice to see the API and the doc evolving together.

Now it seems impossible to figure out how to include external js/css files (the `<base>` thing we talked about and the CSP rules). I don't even know if @jrieken or @tsalinger were able to test including external js/css from extension folder.

**Comment by tsalinger** [comment]
@octref good point! I was trying to include external js but didn't succeed.
In the meantime, Matt gave me some feedback on it and I'll try again later today.

**Comment by tsalinger** [comment]
For the record: I didn't manage to include an external js file.
@mjbvz would be cool if you could add a minimal example on how to do it.
