### ISSUE TITLE
Notification not showing all the buttons if they overflow the notification size

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#44673]
Testing https://github.com/Microsoft/vscode/issues/44319
When a notification has buttons that overflow the notification toast size, the final ones are not shown.
On the old version, zooming out would solve the issue. But with the new one, the button showns remains the same.

Stable:
![Stable](https://user-images.githubusercontent.com/5607882/36760540-20c9b6e8-1bd0-11e8-8c76-3e0ffab21371.png)

Insiders: (fourth button not being shown)
<img width="1280" alt="insiders" src="https://user-images.githubusercontent.com/5607882/36760558-33711390-1bd0-11e8-9149-adb1cb9be04b.png">

**Comment by mattacosta** [comment]
Same as #44538?

**Comment by gushuro** [comment]
Yes, closing as its duplicate
