### ISSUE TITLE
Top/Down arrows shouldn't move focus in split terminals when panel is on the right

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44674]
Testing #44446 in Mac

In the horizontal layout (where split terminals are side to side), Alt+Cmd+Top/Bottom arrow shouldn't move focus between split terminals

In the vertical layout (where split terminals are one below the other), Alt+Cmd+right/left arrow shouldn't move focus between split terminals

**Comment by Tyriar** [comment]
As discussed this is as designed; it feels weird coming from other terminals and we'll likely eventually support horizontal splits in the terminal which will use the same keybinding.
