### ISSUE TITLE
Split terminals from another group all squashed when changing panel position

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44678]
Testing #44446 in Mac

- Split terminal twice to get 3 terminals
- Add new terminal group and split once
- Change panel position
- From the drop down choose the first group
- All squashed!!!

![terminal-squash](https://user-images.githubusercontent.com/16890566/36761075-51c3ec30-1bd2-11e8-8916-4470044901c7.gif)

**Comment by Tyriar** [comment]
Great find! I was doing an unnecessary layout with bad dimensions 0x0.
