### ISSUE TITLE
Changing panel layout causes content loss in split terminals

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44670]
Testing #44446 in Mac

- Split to have 5 terminals in the right panel. Mine has 3 lines of content each.
- Change panel layout. See that the first line is lost and prompt appears before the second line instead of after
- Change panel layout again. All text lost. Only prompt remains

![terminal-lose-line](https://user-images.githubusercontent.com/16890566/36760179-b03bd45c-1bce-11e8-8ece-d56965411d8a.gif)

**Comment by Tyriar** [comment]
Same as https://github.com/Microsoft/vscode/issues/44662; a line disappearing when resizing width down.
