### ISSUE TITLE
New line always starts at the beginning of line (Col 1)

### ISSUE THREAD

**Issue by ericguo** [Microsoft/vscode#4468]
- VSCode Version: Version 0.10.11 (0.10.11)
- OS Version: Mac OSX 10.11.2 (15C50)

Steps to Reproduce:

1. Typescript as an example, create an empty file and input "if {" 
2. Hit enter, the new line always start at Col1 instead of Col5 with correct margin on the left.

**Comment by mubaidr** [comment]
Cannot confirm this issue with the Vanilla JS, cursor starts at correct indent. Maybe it is just an issue related to typescript.

**Comment by jrieken** [comment]
should be fixed in recent versions

**Comment by dbaeumer** [comment]
This only happend with format on type on and got fixed in the March release.
