### ISSUE TITLE
Where I will find cs-cz (Czech) localization?

### ISSUE THREAD

**Issue by michalzobec** [Microsoft/vscode#44686]
Hello Team,

I would like help with translation of VS Code to Czech language. But cannot found localization files.

Please give me link to localization files and I will translate it.

Thank you.

Michal

**Comment by danyeh** [comment]
@michalzobec , please visit https://aka.ms/vscodeloc for instruction on how to contribute on localization.
Localization is hosted on [Transifex](https://www.transifex.com/microsoft-oss/) which allows contribution from multi community members. Once reach threshold of coverage. We pull translation from Transifex to [vscode-loc repo](https://github.com/Microsoft/vscode-loc) to build and publish language pack to Marketplace. Thank you for contributing!
