### ISSUE TITLE
Update: Updating VS Code should check for updates first.

### ISSUE THREAD

**Issue by gushuro** [microsoft/vscode#44685]
If I have an update pending and a new update comes, in order to get the latest version I need to update (and reload window), then check for updates and update again (reloading the window again).

Steps to Reproduce:

1. Open VS Code Insiders
2. Check for updates --> a little `1` appears.
3. Wait 24 hours
4. Click the gear
5. Find out there is no way to check for new updates until the previous update is installed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mattacosta** [comment]
In my case new insider builds come out super early in the morning and are promptly detected. Sometimes a second insiders build will then be released an hour or two later though, so when I finally get back to the editor I have to update multiple times. This would be a great quality-of-life improvement.

**Comment by rebornix** [comment]
I'd love to see this one being fixed, as I use Windows box in office and Mac at home, WFH in the middle of the week means I run into this issue twice a week ;(
