### ISSUE TITLE
Symlink to a non-existing target causes the explorer to hang

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#44689]
Issue Type: <b>Bug</b>

Testing #44097.

1) In a folder `f` run `ln -s non-existing void`.
2) Open `f` in code insiders

-> Explorer hangs

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.4.0-59-generic

Reproduces without extensions

**Comment by isidorn** [comment]
This is fixed in latest insiders.
