### ISSUE TITLE
Improve message shown when folder name has a trailing slash

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#44682]
Testing https://github.com/Microsoft/vscode/issues/43968

Create a folder with a trailing slash in the name

Since the trailing slash is ignored, the ** in the message shown is a bit weird. I would expect it to either behave as without a trailing slash and show no message in this case, or not show **.
![folder_with_trailing_slash](https://user-images.githubusercontent.com/3672607/36761619-c44d7e7c-1bd4-11e8-8f5e-2c5bd7ab6e2c.png)

**Comment by tsalinger** [comment]
Thanks, this is actually a duplicate of #43964
