### ISSUE TITLE
Rename and fine all references of Typescript's string literal values 

### ISSUE THREAD

**Issue by zivni** [Microsoft/vscode#4469]
Type script [string literals](https://github.com/Microsoft/TypeScript/pull/5185) allow to have a code such as 
```
//interfaces.d.ts
type Options = "option 1 " | "option 2" 

//file.ts
let myOption: Options = "option 1" // "option 3" will give us an error, right in the IDE.
```

It would be nice to be able to rename and find all references of a specific value. e.g. find/rename all occurrences of "option 1". Currently we can only find the references of the type itself.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7611
