### ISSUE TITLE
Missing directories/files from the explorer

### ISSUE THREAD

**Issue by allanchau** [Microsoft/vscode#44691]
### Issue Type
Bug

### Description

- [ ] Create a directory with `password` in the name.
- [ ] Verify you cannot see the directory.
- [ ] Open the project in another editor (Atom) and verify the directory exists.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|27%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-docker|Pet|0.0.25
sort-lines|Tyr|1.4.1
vscode-wakatime|Wak|1.1.22
html-css-class-completion|Zig|1.17.1
vscode-eslint|dba|1.4.7
docthis|joe|0.6.0
VS-code-vagrantfile|mar|0.0.7
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.1.0
color-highlight|nau|2.3.0
marko|pca|0.2.2
subtle-brackets|raf|2.1.0
sass-indented|rob|1.4.8
preview-vscode|sea|1.4.2
stylelint|shi|0.33.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Since this reproduces only with extensions, it's likely being caused by an extension. Can you narrow down which one it is by enabling them one at a time?
