### ISSUE TITLE
Incorrect handling of \ when creating a folder

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#44693]
Issue Type: <b>Bug</b>

Testing  #43968.

1) Start creating a new folder in the explorer
2) Type 'folder1\folder2'
3) Press Enter

Actual:
This creates folder1 and folder2 insider folder1. 

Expected:
One folder named 'folder1\folder2`. On Linux is't perfectly fine to have '\' in a folder name.  One could if I need to escape the '\' but this results in the same wrong folder hierarchy.

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.4.0-59-generic

Reproduces without extensions

**Comment by isidorn** [comment]
I acknowledge the issue but I have no plans to fix it -> closing
