### ISSUE TITLE
Typescript import paths are suddenly traversing upwards since upgrading from 1.19.3

### ISSUE THREAD

**Issue by alextreppass** [Microsoft/vscode#44699]
- VSCode Version: 1.20.1
- OS Version: OSX
- Does this issue occur when all extensions are disabled?: Yes

Given the following files:

- `src/some/path/to/consumer.ts`
- `src/some/other/path/util.ts`

When editing `consumer.ts` to import a member of `util.ts`, VSCode will suggest and import the following:

- In 1.19.3: `import { thing } from 'some/other/path/util';`
- In 1.20.1: `import { thing } from '../../other/path/util';`

In our codebase, we have the compiler option `baseUrl` set to `./src`. We have no other path-related settings.

Restrictions:
- I can't change the `baseUrl` as we don't want to see `src/` pre-pended to our imports,
- We need the full path (without `src/` prepended) for easy grepping and refactoring.

Is there a way to get the old behaviour back here? 

I've tried playing around with the `paths` and `rootDirs` compiler options but have had no luck.

Thanks,

**Comment by alextreppass** [comment]
It might be this commit upstream in tsc: https://github.com/Microsoft/TypeScript/commit/d333d889c1d42a98deceb81545ac5a9a57448abe

**Comment by alextreppass** [comment]
Confirmed that reverting https://github.com/Microsoft/TypeScript/commit/d333d889c1d42a98deceb81545ac5a9a57448abe brings back the desired import behaviour

**Comment by alextreppass** [comment]
Have opened https://github.com/Microsoft/TypeScript/issues/22249 for discussion

**Comment by mjbvz** [comment]
Thanks for looking into this @alextreppass! I'm going to close this issue as upstream. We'll continue discussion up on the TypeScript issue

**Comment by alextreppass** [comment]
Should be solved by https://github.com/Microsoft/vscode/issues/45948
