### ISSUE TITLE
Massive flickering in every single keystroke

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#44690]
Issue Type: <b>Bug</b>

Testing #43968.

1) Start creating a new folder in the explorer
2) Type 'folder1/'
-> once the '/' is in the input box every keystroke afterwards causes a full flicker of the information widget shown below the input box.

This also happens on other platforms.

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.4.0-59-generic

Reproduces without extensions

**Comment by tsalinger** [comment]
We need to debounce
