### ISSUE TITLE
Incorrect help text when renaming to a name containing \

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#44694]
Issue Type: <b>Bug</b>

Testing  #43968.

1) Have workspace that contains `folder1`
2) Start renaming `folder1` in the explorer
3) Type 'folder2\folder3'
-> Info messages says that `folder3` will be created in `folder2`. However, the action correctly renames `folder1` to  `folder2\folder3`.

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.4.0-59-generic

Reproduces without extensions

**Comment by isidorn** [comment]
I acknowledge the bug but I have no plans to fix it
