### ISSUE TITLE
Find All Reference from requiring file to module file works only if not default CommonJS exports

### ISSUE THREAD

**Issue by Hoishin** [Microsoft/vscode#44700]
> By "default CommonJS exports" I mean `module.exports = something`, rather than `module.exports.foo = something` or `module.exports = {foo: something}`

Might belong to https://github.com/Microsoft/vscode/issues/21507, but I thought it is a bit different.

- VSCode Version: 1.20.1
- OS Version: macOS High Sierra Version 10.13.3

Steps to Reproduce:

1. `module.exports` something
```js
const f = 1234;
module.exports = f;
```
2. `require` it
```js
const f = require('./above-file');
console.log(f);
```
3. The `f` in `console.log` doesn't show references across files in Find All References. You can find references across files if you Find All References from the module file.

However,
1. `module.exports.foo` something
```js
const f = 1234;
module.exports.foo = f;
```
2. `require` it
```js
const {foo} = require('./above-file');
console.log(foo);
```
3. The `foo` in `console.log` DOES show reference across files in Find All References. You can find references across files if you Find All References from the module file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22222
