### ISSUE TITLE
sometimes get a warning in the default settings.json

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/vscode#4470]
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.3

Steps to Reproduce:

1. Preferences > User settings.
2. sometimes get a warning in the default settings.json

![test](https://cloud.githubusercontent.com/assets/15059605/13903524/3d3f6614-eeba-11e5-8bea-05419a53cb64.png)

**Comment by aeschli** [comment]
This issue was moved to jakob101/RelativePath#4
