### ISSUE TITLE
Request: option to automatically start background updates installation

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#44704]
With #41676, vscode can update in background (on Windows). It is pretty nice!
(I already set `update.enableWindowsBackgroundUpdates` to `true`)

The problem is that we need more "click" operations now.
1. start vscode, it will automatically check updates and download
1. find a `1` on the gear icon
1. **click** the gear icon
1. **click** `install update`
1. wait for several seconds
1. **click** the gear icon
1. **click** `restart now`

It will be better to have an option to skip the first `install update` confirmation. So vscode can automatically start background updates and only notify user when everything is done.

**Comment by joaomoreno** [comment]
The problem with this is that there would be an admin prompt coming out of nothing. We don't want to do this. We're pushing towards having user installable packages. That way we can do the update automatically without asking for permissions.

/duplicate #534
