### ISSUE TITLE
Java Debug - Cannot open file after renaming folder

### ISSUE THREAD

**Issue by yhtsao** [Microsoft/vscode#44706]
- VSCode Version: 1.20.1
- OS Version: MacOS 10.12.6
- Language: Java
- Extensions: 
    Debugger for Java 0.6.0
    Java Extension Pack 0.3.0
    Java Test Runner 0.3.0
    Language Support for Java(TM) by Red Hat 0.19.0

I'm new to use VS code to develop Java. Everything goes fine when creating the simple java program, compiling and debugging. But when I rename the folder that contains java file and debug the java program, it comes an error that shows debugger cannot find java source file. The solution that I found by myself is closing folder and re-import folder again. I'm not sure if there is a bug or I miss some steps to update config in VS code?

Steps to Reproduce:

1. Here's my simple java program, and it works fine when first created
![image](https://user-images.githubusercontent.com/11153474/36774161-db006a26-1c97-11e8-83e9-23b1934e6d2b.png)

2. My task.json and launch.json for compile and debug
![image](https://user-images.githubusercontent.com/11153474/36774193-f7ae8978-1c97-11e8-89bf-b2f6f5ea0a69.png)

3. Then I rename the folder (SimpleJava -> Simple)
![image](https://user-images.githubusercontent.com/11153474/36774215-109a4a9e-1c98-11e8-9298-689c84a15da0.png)

4. Rebuild Hello.java and debug "Hello", it comes an error. 
    It seems that debugger wants to open the file with the previous folder name.
![image](https://user-images.githubusercontent.com/11153474/36774253-3799fb76-1c98-11e8-9f6d-145f86292829.png)

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-java-debug#242
