### ISSUE TITLE
Find In Selection can' work in regular expression

### ISSUE THREAD

**Issue by gaosjx** [Microsoft/vscode#44702]
### Issue Type
Bug

### Description

1. I select 3 lines, but Find In Selection match 5 lines, and Replace All has the same problem.
2. see the screenshot below
![image](https://user-images.githubusercontent.com/19669879/36772269-7e211de4-1c8f-11e8-8dca-149ae87a56e6.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|Memory (System)|7.88GB (1.28GB free)|
|Process Argv|E:\DevSoft\Microsoft VS Code\Code.exe -n|
|Screen Reader|no|
|VM|44%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6
tslint|eg2|1.0.28
markdown-shortcuts|mdi|0.8.1
debugger-for-chrome|msj|4.1.0
vscode-paste-image|mus|0.9.5
java|red|0.19.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.2
my-code-outline|wan|0.1.0

</details>

**Comment by gaosjx** [comment]
someone can fix that , please .. -0-0

**Comment by rebornix** [comment]
Already fixed in Insiders.
