### ISSUE TITLE
Git merge / commit -a / focus back the integrated terminal

### ISSUE THREAD

**Issue by aliev** [Microsoft/vscode#44703]
I'm using vscode for editing commit messages and merging:

.gitconfig

```
[diff]
    tool = default-difftool
[difftool "default-difftool"]
    cmd = code --wait --reuse-window --diff $LOCAL $REMOTE

[merge]
    tool = vscode
[mergetool "vscode"]
    cmd = code --wait --reuse-window $MERGED
```

After editing the commit and closing the commit editing / merge tab is it possible focus back the integrated terminal? I had the same feature in my vim

```
[mergetool "vimdiff"]
    cmd = mvim -f --nomru -c \"Gdiff | au VimLeave * !open -a Terminal\" $MERGED
    keepbackup = false
```

**Comment by Tyriar** [comment]
I'm not sure there is a nice way to do this, @bpasero any ideas?

**Comment by bpasero** [comment]
@Tyriar I am actually also hitting this quite often... not sure how to best fix this. We do have code in place [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L1062) to delete the `--waitMarkerFile`, so we are aware of the editor closing that was triggered via a `--wait` invocation.

But bottom line is that we would need to know that the operation was triggered from the integrated terminal to begin with...

**Comment by Tyriar** [comment]
@bpasero there's this:

```
❯ env | grep TERM_PROGRAM
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.21.0-insider
```

They may not be 100% reliable though as an external terminal could have been launched by the terminal or `code` could be run from `code-insiders` 😄. Maybe the off chance of one of those happening is worth forcing focus?

Another way you could do this is track the PID it was launched from on the CLI/main size and see if it's a child process of the terminal. Seems like a lot of work for such a small thing, we also only track the terminal process tree on Windows currently.

**Comment by bpasero** [comment]
@Tyriar it is a bit of a hack but the terminal could also listen to the editor closing and checking if the file closed was part of [`configuration.filesToWait`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L1022) and then just put focus back to the terminal if:
* the terminal is open
* the terminal just had focus (?)

**Comment by Tyriar** [comment]
@bpasero it's not so easy to know that the terminal launched the code CLI, it may be down the track when we track the process tree more though.

When an editor is closed that was launched via --wait, can we track the `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` and focus the terminal of the same renderer if they match?

**Comment by aliev** [comment]
to clarify what I mean - integrated terminal - terminal which is integrated to the editor

for example from vscode terminal:

git add .
git commit -a

<vscode opens commit message editor>

I'm editing a commit -> I'm pressing save and close the tab
Integrated terminal should be focused back

**Comment by bpasero** [comment]
@Tyriar yeah but this has to happen from the terminal layer, cannot happen from the workbench to avoid layer breakage. 

Are you saying that these environment variables are passed to the instance of VS Code that is starting from the integrated terminal? We would probably need to wire these in through lots of places on the main side to eventually reach the renderer.

**Comment by Tyriar** [comment]
@bpasero when code is launched via the CLI it inherits the environment of the shell which contains these vars.

Ok, let's go with listening to editor close and checking [`configuration.filesToWait`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L1022) as you suggest. That is definitely nicer than wiring the values through. The listening should probably be done in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts

**Comment by captainrdubb** [comment]
@bpasero @Tyriar Is it alright to watch for waitMarkerFile deletion, since workbench will delete the marker file to signal when editing is done? See [workbench.ts](https://github.com/Microsoft/vscode/blob/1c91b6ba4a6dece2c5d626bee6fbf772238723b5/src/vs/workbench/electron-browser/workbench.ts#L1063)

**Comment by bpasero** [comment]
@captainrdubb try to use `code.sh -r` that should force to reuse the last active instance. 

I think there are some things missing from your change:
* only do this listening if the marker file was opened from the integrated terminal
* handle the opening of the marker file within the running instance, in that case the request will come in via [`vscode:openFiles`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/window.ts#L190)

**Comment by bpasero** [comment]
@captainrdubb I think this is not as straight forward for a pull request so I went ahead to implement this via https://github.com/Microsoft/vscode/pull/45523

I took your idea about watching for the marker file to get deleted, thanks for that 👍

**Comment by captainrdubb** [comment]
@bpasero on to the next one :wink:
