### ISSUE TITLE
HTML folding findings

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44712]
Testing #44445

VS Code version: Code - Insiders 1.21.0-insider (3fec61014742dec894b3a31cdf8556bf533cb0e1, 2018-02-28T06:08:46.169Z)
OS version: Darwin x64 16.7.0

Comment misses folding region:

![image](https://user-images.githubusercontent.com/9205389/36776642-c94add9c-1c66-11e8-90c2-50c7f1512d79.png)

**Comment by chrmarti** [comment]
Extra closing tag throws folding regions off:

![image](https://user-images.githubusercontent.com/9205389/36776986-0052b0c0-1c68-11e8-8a9a-46d03506aa3b.png)

**Comment by chrmarti** [comment]
Folding region ends too early when #region markers don't follow tree structure:
![image](https://user-images.githubusercontent.com/9205389/36777127-8eb9b552-1c68-11e8-8e53-4d83025e4abf.png)

![image](https://user-images.githubusercontent.com/9205389/36777141-a42e1086-1c68-11e8-9f15-3a92817d7b5d.png)

**Comment by chrmarti** [comment]
No folding region for region marker starting on same line as other ends (works for tags):
![image](https://user-images.githubusercontent.com/9205389/36777622-7752ffd4-1c6a-11e8-84ce-03b3591d6fc7.png)

**Comment by chrmarti** [comment]
In the above something is thrown off, the head tag also misses a folding region:
![image](https://user-images.githubusercontent.com/9205389/36777729-eb30f866-1c6a-11e8-8477-2b999244629e.png)

**Comment by aeschli** [comment]
Note: Not supported: folding region for region marker starting on same line as other ends

**Comment by chrmarti** [comment]
Also: #region markers not following tree structure are ignored. I assume this is expected. Marking verified.
