### ISSUE TITLE
Git cannot pull error message should be a modal dialog

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#44715]
Suggest to change this error from a notification into a modal dialog.

![image](https://user-images.githubusercontent.com/172399/36777920-7d510ec0-1c6b-11e8-9e98-dfcc981242ee.png)

// CC @bpasero

**Comment by bpasero** [comment]
+1, this error can happen often. I think we should only show a modal dialog as a consequence of the user triggering this explicitly (e.g. not when this happens from some background operation).
