### ISSUE TITLE
file not found extHost1.log

### ISSUE THREAD

**Issue by atk** [Microsoft/vscode#44717]
https://github.com/Microsoft/vscode/blob/93681eb4391b9d365420b3544493fb3a880efd92/src/vs/workbench/api/node/extHostLogService.ts#L29

There seems to be a naming confusion that is only an issue for OSes that differentiate between upper and lower case in the file names; some process [renderer1] throws an error because it does not find extHost1.log, when in the line shown above the logging file is initialized as exthost1.log (small h instead of capital H).

**Comment by jrieken** [comment]
Still shows as `extHost...` when invoking `Open Log File`

<img width="388" alt="screen shot 2018-03-01 at 11 18 44" src="https://user-images.githubusercontent.com/1794099/36839411-50eb9a1c-1d42-11e8-8dd1-f20855cca0f2.png">

**Comment by sandy081** [comment]
Fixed by 1d4ace9ee0dc7d77f2f6dfc4fec1214a989f64fd

**Comment by mleduque** [comment]
I still have this problem.

**Comment by sandy081** [comment]
@mleduque Where do you have this problem?
