### ISSUE TITLE
Add functionality to cancel unsaved changes without closing the file.

### ISSUE THREAD

**Issue by LAITONEN** [Microsoft/vscode#44716]
- VSCode Version: 1.20.1
- OS Version: Sierra 10.12.6

Steps to Reproduce:
https://stackoverflow.com/questions/49024999/cancel-unsaved-changes-without-closing-the-files
Would be great to have it either as an icon in the right part of a file tab (where **x** and • are located) or get the option to cancel all the changes in a pop-up when clicked on the said **x** icon.

**Comment by bpasero** [comment]
@LAITONEN isn't that File > Revert File?

**Comment by LAITONEN** [comment]
@bpasero Thank you, sir! Will add it as an answer to Stackoverflow question.
