### ISSUE TITLE
`[ts] Cannot find module` when project rebuild

### ISSUE THREAD

**Issue by STayinloves** [Microsoft/vscode#44710]
- VSCode Version:
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:

Steps to Reproduce:

1. Clone https://github.com/Microsoft/Recognizers-Text
2. cd javascript path
3. run build script
4. edit a ts file `JavaScript/packages/recognizers-number/src/number/parsers.ts` for example
5. error `[ts] Cannot find module '@microsoft/recognizers-text'`.

reload vscode the error disappears.
```
rm -rf node_modules
npm run build
```
can also reproduce this bug.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22349
