### ISSUE TITLE
[pug] synthax highlighting vanishing with Preview extension

### ISSUE THREAD

**Issue by JhonnyJason** [Microsoft/vscode#44713]
- VSCode Version: Version 1.19.1
- OS Version: Xubuntu 16.04
- Node Version: Node 7.9.0

Steps to Reproduce:

1. Install and the Preview extension by Haixin Chen (searKing.preview-vscode)
2. Restart VS Code
3. Open any .pug file

Does this issue occur when all extensions are disabled?: No

Appears like something within the Preview extension by Haixin Chen (searKing.preview-vscode) is interfering with the native synthax highlighting of VS Code for pug.

Thanx!

**Comment by tsalinger** [comment]
This problem seems to be specific to that extension. Please open an issue in that extension's [repository](https://github.com/searKing/preview-vscode/issues).
