### ISSUE TITLE
No updates available notification should be a modal message

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#44714]
When I ask for updates and there are no updates available then this is now shown as a notification. I find a modal message box more appropriate.

//CC @bpasero

**Comment by bpasero** [comment]
+1. on top of that, if I ask for an update and there is one, I would also show a modal dialog to apply it.

**Comment by bpasero** [comment]
@joaomoreno maybe also prompt modal when the user checks for an update and there is one? I am not sure if there are platform differences (e.g. with Windows background updates), but would be cool to get a dialog that asks to restart to apply the update.

**Comment by joaomoreno** [comment]
But there is quite some time between clicking and getting that dialog: checking and downloading the update. That would make that dialog open out of the blue.

**Comment by bpasero** [comment]
@joaomoreno oke

**Comment by kieferrm** [comment]
Same concern as @joaomoreno. Checking if there is an update sometimes takes a while. So, I initiate the check and then move on. This usually puts me in a place at which when the dialogs opens I don't want to restart. I first want to finish what I just did.

On the entertaining side, when I check for updates and the no-update notification comes immediately, I have to move my mouse only a few pixels to close the notification. Power of the sidebar on the right.
