### ISSUE TITLE
Pressing ctrl+z closes editor tab

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#44723]
Continuation of https://github.com/Microsoft/vscode/issues/40936 (could not reopen)

recording: https://i.imgur.com/jGiChM8.mp4

- I opened a file, pressed "z", then I do "ctrl-z", as you can see it shows a close dialog. I cancel, remove the z with the back key, save using "ctrl-s", then I do "ctrl-z" again, now it closes it (since there's no pending changes

- Then I open 2 files, and press "ctrl-z" on each, both get closed

I launched vscode from desktop (but I don't think opening from desktop or from terminal `code .` changes anything there). I'm not able to launch it with `code --verbose` since with reopening vscode, the issue doesn't happen anymore.

I'll try to  run vscode in verbose mode sometime (but I'm not often using terminal to launch it because of https://github.com/Microsoft/vscode/issues/13189#issuecomment-368322383)

```
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:31:21.019Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by caub** [comment]
@bpasero I tried , (just after rebooting too, like it happened this morning) but can't reproduce (with `--disable-extensions` or not, it's just hard to produce that bug, last time I had it was a few weeks ago, on another laptop)


For record, my extensions are:
- Code Runner 0.8.7
- Docker 0.0.25
- EditorConfig fo VSCode
- ESLint 1.4.7
- JSON5 syntax 1.0.0
- npm 0.3.3
- npm intellisense 1.3.0
- Python 2018.1.0

**Comment by bpasero** [comment]
@caub so you could never reproduce when extensions are disabled? maybe some extension overwrites the keybinding for Ctrl+Z or you changed keybindings, can you check?

**Comment by caub** [comment]
@bpasero It happens very rarely, I don't know how to reproduce this error  

So it's not very annoying (except it loses you lose your edit history when it happens, since it close the file)

I just posted it, in case some other users experience it too (I would have added to my previous issue, but it was locked)

**Comment by caub** [comment]
It happened again this morning, I launch it with extensions of course, in the devtools I only saw 

```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] TypeDefinition null
```

after restarting it's working normally

**Comment by bpasero** [comment]
@caub can you see in the keybindings editor if any extension overrides this key combination?

**Comment by caub** [comment]
none do
![2018-03-14-095848_1335x230_scrot](https://user-images.githubusercontent.com/3134574/37392400-523cc004-276e-11e8-8544-64ba42912ccd.png)

**Comment by bpasero** [comment]
@caub does this still happen?

**Comment by caub** [comment]
I didn't have it since that last time 2 months ago
