### ISSUE TITLE
Contributions tab of Configuration Editing Extension not understandable

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#44725]
![image](https://user-images.githubusercontent.com/172399/36781652-c552a9f8-1c76-11e8-840c-5f0eb62eaa82.png)

**Comment by sandy081** [comment]
Best can be done is to show complete information `File Match` and `Schema` mappings.

![image](https://user-images.githubusercontent.com/10746682/36792701-8dcf17f8-1c9b-11e8-9a13-5296213608eb.png)
