### ISSUE TITLE
Restore focus to last workbench component that had focus after closing quick pick

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#44722]
Steps to Reproduce:

1. Open a new terminal and activate (focus) it
2. Press `ctrl+shift+p` to open the palette menu
3. Press `Esc` to close the palette

The focus is given to the editor instead of the terminal which previously got the focus.

This happens on Windows 10 and the latest insider build:

Version 1.21.0-insider
Commit 3fec61014742dec894b3a31cdf8556bf533cb0e1
Date 2018-02-28T05:17:16.839Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Tyriar** [comment]
This is the case for the whole workbench, not just the terminal.
