### ISSUE TITLE
Custom view: Inverted indent logic

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44726]
Issue Type: <b>Bug</b>

Testing #44364

It undents when I expand to children with icons:

![feb-28-2018 11-01-01](https://user-images.githubusercontent.com/9205389/36781714-fd3db150-1c76-11e8-9f5f-efe80c5d86cc.gif)

VS Code version: Code - Insiders 1.21.0-insider (3fec61014742dec894b3a31cdf8556bf533cb0e1, 2018-02-28T06:08:46.169Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.61GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir=tmp/user --extensions-dir=tmp/ext|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by sandy081** [comment]
Good catch

**Comment by chrmarti** [comment]
There is no indent anymore. I believe this is expected since you removed the placeholder?
![image](https://user-images.githubusercontent.com/9205389/36892396-e451be4a-1e04-11e8-9be4-5300483a34c6.png)

**Comment by sandy081** [comment]
Yes
