### ISSUE TITLE
If a debug session fails, show a modal error, not a notification

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#44720]
Prototypical case:
![2018-02-28_10-27-38](https://user-images.githubusercontent.com/1898161/36780075-364e964e-1c72-11e8-8dd2-f058c221eb6d.png)

**Comment by isidorn** [comment]
I have updated all of the debug error that happen when a session start to be modal.
This is a user inititated action so all of these should be modal.

Verifier:
1. Verify you get a modal dialog once you start a debug session with some invalid launch.json
2. Verify you get a modal dialog once you start a debug session with a launch.json with an invalid `type`
3. Verify you get a modal dialog if your prelaunch task produces errors
4. Verify all these dialogs provide actions which make sense

![error](https://user-images.githubusercontent.com/1926584/36782727-1a410970-1c7a-11e8-9ead-c6c55cce1116.gif)

**Comment by jeffhoye** [comment]
I sure wish this were configurable.  It's just one more step I have to do to close this modal before actually fixing the problem.  I can tell from the logs that there's an error.
