### ISSUE TITLE
javascript 对象数组报错【急】

### ISSUE THREAD

**Issue by webSongNO1** [Microsoft/vscode#44728]
### Issue Type
Bug

### Description

开发vue中，配置路由js里在“  {path:"/h",component:HelloC01}”提示应为表达式，它好像不能正确识别数组对象数组这样的定义。
export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'HelloWorld',
      component: HelloWorld,
      children:[
        {path:"/h",component:HelloC01}
      ]
    },
    {
      path:"*",component: HelloWorld
    }
  ]
})

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|Memory (System)|7.95GB (4.76GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.7
vetur|oct|0.11.7
LiveServer|rit|3.2.1

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Please explain the problem some more. If this is an issue with the Vetur extension, plese file an issue on that repo.
