### ISSUE TITLE
Issue reporter: size exceeds maximum for empty performance report

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#44733]
On windows:
- Open vscode workspace
- Help>Report Issue
- Select ´Performance Issue´
- Enter minimal description

-> size exceeded

![image](https://user-images.githubusercontent.com/172399/36785602-b1092816-1c83-11e8-8df0-97229abe6982.png)

This is caused by a large process listing. We should look into making it more compact.

![image](https://user-images.githubusercontent.com/172399/36785772-52c2e796-1c84-11e8-94b4-9fda63ef4264.png)

As a work around we could offer to copy the process list and tell the user to add it manually to the issue report.

**Comment by egamma** [comment]
Actually the process list differs from code-insiders --status and I also find the process list from code-insiders --status easier to read. The table formatting doesn´t add any value to me. How about just rendering the process list raw like this:

```
CPU %   Mem MB     PID  Process
    0      104   15108  code-insiders main
    0       72    2188     shared-process
    0       74   13488     shared-process
    0      324   13604     gpu-process
    0      177   18748     window (package.nls.json - npm - Visual Studio Code - Insiders)
    0       73    6592       extensionHost
    0       44    1876         electron_node jsonServerMain.js
    0       14    7400       watcherService
    0       10   21372         console-window-host (Windows internal process)
    0      189   19520     window (Running Extensions - vscode - Visual Studio Code - Insiders)
    0       14    7232       watcherService
    0       10   12228         console-window-host (Windows internal process)
    0       51   10024       extensionHost
    0       32   19896       terminal
    0        6   21088         winpty-process
    0       10    5152           console-window-host (Windows internal process)
    0        4   14024           C:\WINDOWS\System32\cmd.exe
    0       33   20384             electron_node cli.js
    0       52    5844               "C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" --status
    0       74    1788                 powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code - Insiders.exe' -MaxSamples 3}"
    0        7   13536                   console-window-host (Windows internal process)
    0       28    6780                 gpu-process
```

**Comment by RMacfarlane** [comment]
For addressing the size issue, I changed the behavior so that when the url is too long, the body of the issue gets copied into the clipboard and the issue preview opens with the text "We have written the needed data into your clipboard because it was too large to send. Please paste."
