### ISSUE TITLE
[Bug] Using the Tab key to indent messes the code

### ISSUE THREAD

**Issue by pedroassis** [Microsoft/vscode#4473]
- VSCode Version:  0.10.8 (0.10.8)
- OS Version: OS X EL Capitan 10.11

Steps to Reproduce:

1. Select the try block in following the code
2. Hit `tab`
3. Hit `Command+z`

Code:
```
function discoverTimeZone(lead, phone) {
    try {
        lead.timezone = timezoneHelper.getTimeZoneForNumber(lead[phone]);
    } catch (e) {
        lead.penalty = 1;
    }
}
```

This bug happens in other pieces of code, there is no way of undo the change with `Command+z` which makes it even worse. `Command+Shift+z` also does not help.

The workaround is to pray you saved the file in the right time, close the file from the recent files, pray once more, and open the file again.

![vsbug](https://cloud.githubusercontent.com/assets/4248124/13905674/74a85bb6-eea5-11e5-8a4e-7bb00e4027c0.gif)

Its even worse when the block of code is bigger, the code is left much more messed up. The above example you can still make sense of whats left of the code.

**Comment by Tyriar** [comment]
Updating vscode will fix this issue. I think it was this one: https://github.com/Microsoft/vscode/issues/2829
