### ISSUE TITLE
Proposed Webview API - Documentation

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#44739]
Testing #44466 

- The documentation is missing an example on how to receive messages in the webview like:
window.addEventListener("message", receiveMessage, false);
- The dispose() docs refer to a 'onDispose' function. Did you mean 'onDidDispose'?

**Comment by mjbvz** [comment]
First cut of documentation is here: https://github.com/Microsoft/vscode-docs/commit/d489410d156f058b560918e146ff951fd93f152b

Note that this is more tutorial documentation, not reference documentation. The reference documentation is generated from the API itself
