### ISSUE TITLE
Mac: Can't go to End/Home in suggest widget

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#44731]
It used to be possible to go to the first and last element of the suggest widget by pressing <kbd>Cmd Left</kbd> and <kbd>Cmd Right</kbd> respectively.

**Comment by ramya-rao-a** [comment]
According to history, the commands [selectFirstSuggestion](https://github.com/Microsoft/vscode/blob/e30a954dcc534d5e2310781f048e3d60940ba553/src/vs/editor/contrib/suggest/suggestController.ts#L451) and [selectLastSuggestion](https://github.com/Microsoft/vscode/blob/e30a954dcc534d5e2310781f048e3d60940ba553/src/vs/editor/contrib/suggest/suggestController.ts#L420) never had any default keybindings, so I dont see how Cmd Left/Right would have taken us to first and last element of the widget unless they were assigned directly to the list control.

Regardless, closing this as out of scope as there hasnt been any user activity for this issue.
