### ISSUE TITLE
autoAttachChildProcesses is not supported on extensionHost type 

### ISSUE THREAD

**Issue by maty21** [Microsoft/vscode#44737]
- VSCode Version:1.20.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. create new launch configuration with extensionHost type 
2. add autoAttachChildProcesses:true
3. property autoAttachChildProcesses is not allowed

Does this issue occur when all extensions are disabled?:not relevant

**Comment by weinand** [comment]
"autoAttachChildProcesses" is not supported in this case for various reasons.

**Comment by maty21** [comment]
can you explain why, please ? cos for me it seems like a really good feature

for example:

in my mocha sidebar extension, i'm loading node in other process cos I
don't want that the extension will relay on vscode node version.


currently, the debugging is really awkward (i have to attach the process
manually)

if I understood correctly extensionHost type, is actually a node.js
process. so I can't understand what is the reason for not allowing it on
this type

thanks a lot


Maty Z
