### ISSUE TITLE
Treat double braces like single ones

### ISSUE THREAD

**Issue by xemwebe** [Microsoft/vscode#44747]
I would like to edit *.html.tpl files as used by the go template library. These template files consists mostly of html (js code might be embedded) with one exception: double curly braces "{{" and "}}" are used to identify places where the go template library injects at run time further html data. 

I would like to use Visual Studio Codes syntax highlighting features, but using "html" as style does not work, because all section with double curly brace are split automatically on save, i.e.

`{{range .Types}}`

becomes

```
{
   {
       range .Types
   }
}
```

which can't be interpreted by the go template library anymore.

Is there any way to change this behaviour, e.g. customize code to tread double braces like single ones?

I use Visual Studio Code version 1.20.1 on Windows 7

**Addition:** This behaviour only occurs inside a javascript object definition, i.e. like in 
```
var objTypes = {
    {{range .ObjTypes}}
	{{.InternalName}}:{publicName:{{.PublicName}}, description:{{.Description}} },
    {{end}}
};
```

**Comment by ramya-rao-a** [comment]
@xemwebe I am not able to see the braces splitting

Below is the code I used in a file `test.html.tpl`
```
<!DOCTYPE html>
<html lang="en">

<body>
    {{range .Types}}
</body>

</html>

```

I changed the language mode to html


Is there anything else that I am missing?

**Comment by xemwebe** [comment]
Pure html is no problem, but embedded javascript is, see my addition to the original post. Here is the example code, which demonstrates the problem:
```
<!DOCTYPE html>
<html lang="en">
<script>
    var objTypes = {
        {{range .Types}}
    };
</script>
<body>
    {{range .Types}}
</body>

</html>
```

**Comment by ramya-rao-a** [comment]
Still not able to get a repro. Can you share your settings? And what do you mean by "using "html" as style" ?

**Comment by xemwebe** [comment]
Here is the (relevant) part of my User Settings:

```
{
    "files.associations": {
        "*.html.tpl": "html"
    },
    "[html]": {
        "editor.formatOnSave": false,
        "editor.detectIndentation":false
    },
    "[javascript]": {
        "editor.formatOnSave": false,
        "editor.detectIndentation":false
    },
}
```

With "using html as style" I refer to the setting "files.associations", which is set to html for *.html.tpl files.

The settings for [html] and [javascript] were intended to prevent this splitting of braces, but it doesn't work.

**Comment by ramya-rao-a** [comment]
After enabling format on save, I see that `{{range .Types}}` inside the `script` tag gets formatter to ` { { range.Types } }` i.e a space gets added. I dont see it being split to different lines though. Can you try again by running `code --disable-extensions` ?

**Comment by xemwebe** [comment]
Indeed, when I start code with extension disabled, a get the same behaviour as you. After checking the extensions, "JS-CSS-HTML Fomatter" and "Beautify" (where the former is a wrapper of the latter) caused the problem. 

Thanks for your help!

**Comment by ramya-rao-a** [comment]
Great! Happy Coding!
