### ISSUE TITLE
${workspaceRoot}: Scoping with non-existing root folder name

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#44749]
Testing #44449

>In a multi root workspace with multiple folders you can scope the variable (using the workspace name) in order to get it resolved.

Same setup as in #44748.

If you enter a non-existing root folder name, `${workspaceFolder}` is resolved to `proj1`.

**Comment by isidorn** [comment]
I will treat this as a duplicate of #44748 and fix it as part of that one.
Thanks
