### ISSUE TITLE
Debuger error: It loses the `this` context when destructuring a callback

### ISSUE THREAD

**Issue by anxolin** [Microsoft/vscode#44743]
Hi,

I found a strange behaviour when I run a node application in the debugger.

I've created a simple example that reproduce the case:
```js
class Test {
  constructor () {
    this.name = 'Foo'
  }

  doCall () {
    sayHi({
      callback: (msg) => {
        console.log(msg, this.name)
      }
    })
  }
}

function sayHi (options) {
  options.callback('hi')
  sayHei(options)
}

function sayHei ({ callback }) {
  callback('hei')
}

let test = new Test()
test.doCall()
```

Steps to Reproduce:

1. Set a breakpoint in console log line (line 9)
2. Debug the code
3. Check that the "hi" call: in the debuger console (or if you hover the `this` word), the value of `this` is fine
4. Check that in the "hei" call: Now the `this` **is undefined** 

Also, and less important, if you hover in step (2) over the `this.name` you should get `Foo`, but the popup don't shows up. 

I'm using VS Code version 1.20.1  (f88bbf9137d24d36d968ea6b2911786bfe103002) with MacOS Sierra 10.13.3

Just let me know if you need anything else.

**Comment by roblourens** [comment]
Works in node 10
