### ISSUE TITLE
Documentation: how import existing C++ code into a project

### ISSUE THREAD

**Issue by polomora** [Microsoft/vscode#44742]
VS Code: v 1.20.1

I cannot find explained in the documentation how to import an existing C++ codebase into a VSC project / workspace. There are lots of questions about this on SO and elsewhere. Also, the concept of workspace is not clearly explained in the documentation. Also, lots of questions about this. As fat as I can see, it is simply a way to maintain common user settings.

I want to move to VSC after trying out eclipse and netbeans, where the concept of importing existing code into a project is well established. Is VSC a fully-functional IDE?

Many thanks

**Comment by mjbvz** [comment]
Please file this issue against the C++ extension. They should be able to help you out

**Comment by polomora** [comment]
Many thanks,

Raised a new issue here:
https://github.com/Microsoft/vscode-cpptools/issues/1628
