### ISSUE TITLE
default echo task generates error

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#44750]
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS Windows 7

Steps to Reproduce:

1. create a new workspace
2. create the sample task

![sample task](https://user-images.githubusercontent.com/33490168/36796369-4e9b87b8-1c9d-11e8-989d-da09bd9e4925.PNG)

3. Tasks > Run Task ...
4. select 'echo'

![run task echo fail](https://user-images.githubusercontent.com/33490168/36796471-8d96ee76-1c9d-11e8-908a-23bee36514c7.PNG)

Expectation is that the sample task would run out of the box.

**Comment by dbaeumer** [comment]
This is on purpose to make users aware of the concept of problem matchers. Usually users edit the echo task doing something more useful (e.g. running a compiler).

I will close the issue since there are currently no plans to change this. After you have made a selection the task gets updated and no dialog appears on the second run.

**Comment by draeger-charles-wilson** [comment]
How is a new user to know which of the unexplained options to choose?

Please keep in mind that this is the example you are using to show people how to use you task system.

**Comment by dbaeumer** [comment]
From our perspective one of the most value features of tasks is that problem matcher. This is why we think having this step and making user aware of it is important.

**Comment by draeger-charles-wilson** [comment]
It's great that you have useful features.

My point is that your features are pointless if you don't direct people to where they will learn about them. If you have to drop someone into the basement the first time they try to use the task equivalent of 'hello, world', you've not considered where the user's knowledge is.

Take the top item option 'Continue without scanning the task output'. Why would a first time user expect that there would even be a need to scan the output of the sample task? If the sample task needed to be scanned, why isn't the scanner there? Why doesn't it just open onto a overly commented sample task or go to a web page explaining tasks? Any of those would be better than displaying a list of 15 items half of which have no apparent relevance.
