### ISSUE TITLE
Make tabs and the tabbar better... and reduce annoyances

### ISSUE THREAD

**Issue by XeonG** [Microsoft/vscode#44754]
Vscode single worst aspect is the tabbar.. its just garbage really.. 

-you can't configure the padding/margins of the tab to reduce wasted pixel space with the icon and text which could be better depending on theme.
-you can't use mousewheel over the tabbar to quickly cycle back/forth between open tabs.
-you can't click on a button near the end of the tabbar to see a drop down list of unseen tabs (like before the run code button... as demonstrated in various web browsers)
-you can't have tabs go onto a multiline bar instead of this crappy mousewheel requirement to scroll the tabbar..
-you can't configure the sizing of tabs like a maxsize and minsize and disable tabbar scrolling so tabs can be all be in view at least.
-you can't remove the wasted space taken up by the invisible close button, that is not need for any serious developer that just uses keyboard shortcut or [mmb] click with mouse over the tab(s) to be closed anyway.

so you end up with open tabs that go off the visible tab bar pretty quickly.... you end up having to rely on the explorer sidebar view..which is also shit because if you're in another sidebar, you pretty much have to go back just to work with open documents because the tabs implementation and features/customization for vscode is garbage (with exception of editor/tab coloring options but nothing too fancy)...  its like all the things that could be done to not have this shitty tab workflow and the mousewheel requirement for scrolling the tabbbar is avoided just so they can use the mousewheel to scroll the tabbbar...like the worst workflow and waste of mousewheel functionality for something that lame... just avoid giving users better customization options to make better use of the tabs, avoid not have multiline tabbar (which honestly is the last resort, I'd prefer better options to control width, padding etc)

And that isn't even getting onto giving tabs more features like (pinning, stacking,etc) that above rant is pretty much the basics of what any program with a tabbar should provide really.

Also who ever thought putting errors and other message notices aswel as the command palette etc ctrl+[shift]+p.. .. on the same position and line as the tabbar, thus blocking view.. is just stupid.

That stuff belongs just below the tabbar and position customizable for alignment preference.... its really the most annoying thing when you open vscode and you just want to find an opened tab document but some design by committee idiots I'm guessing figured blocking the view with often useless notices over the tabbar would be really best place for maximum user annoyance.... all that shit belongs just below the tabbar if has to be displayed like that, probably in another view window would be better and would be good for history checking log purposes..or at the bottom of the vscode window above the status bar....

**Comment by bpasero** [comment]
@XeonG after you calmed down, please file individual issues for each thing after checking for duplicates  (using this [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aworkbench-tabs)).
