### ISSUE TITLE
How to make vscode detect file type correctly?

### ISSUE THREAD

**Issue by serjyamp** [Microsoft/vscode#44756]
The problem is that I always have to manually specify JavaScript React file type. How to make vscode do it every time?
![image](https://user-images.githubusercontent.com/8271649/36801454-398856dc-1cc3-11e8-8635-e0d41aa7bfcc.png)

**Comment by bobber205** [comment]
You can do this in preferences under User Settings
Here's an example:
```
    "files.associations": {
        "*.jst": "html"
    },
```

**Comment by serjyamp** [comment]
alas it doesn't help. VS Code opens .js files as simple JS files, not as JS React, anyway

**Comment by mjbvz** [comment]
Just use `javascriptreact` in `files.associations`:

```json
    "files.associations": {
        "*.jst": "javascriptreact"
    }
```

**Comment by serjyamp** [comment]
thank you, but not .jst, correct form is .js

**Comment by bobber205** [comment]
Yeah my example was .jst files.
I figured people could put 2 and 2 together.
