### ISSUE TITLE
Leaf nodes now indent with empty placeholder always

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#44768]
Testing #44364 

Leaf nodes with no icons are now indented regardless of whether or not other leaf nodes have icons.

![image](https://user-images.githubusercontent.com/6561887/36810158-c4d561c0-1c7e-11e8-902d-02b2a8a07528.png)

This should instead have basic indentation and no placeholder.

**Comment by sandy081** [comment]
Closing this as the indentation is completely reverted
