### ISSUE TITLE
Python Debugging with pythonPath variables broken

### ISSUE THREAD

**Issue by adamweiss** [Microsoft/vscode#44765]
### Issue Type
Bug

### Description

Steps to Reproduce:

1. Change user settings to use Python venvs with the following config:
   "python.pythonPath": "~/venvs/${workspaceRootFolderName}/bin/python",
2. Click "Add Configuration" in the Debug panel and select Python
3. Launch Debug
4. Get the following error in Debug Console:

Error: spawn /Users/HOME_FOLDER/venvs/${workspaceRootFolderName}/bin/python ENOENT

Expectation is that ${workspaceRootFolderName} should be resolved properly in the config.

To fix it, I need to change launch.json from the default of

"pythonPath": "${config:python.pythonPath}",

to 

"pythonPath": "~/venvs/${workspaceRootFolderName}/bin/python",

If I had not clicked "Add Configuration", launching debug would have worked 

It appears that ${config:python.pythonPath} is not replacing variables, where it used to work just fine in previous releases.

I also tried the updated variable name ${workspaceFolderBasename} with the same results.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
githistory|don|0.4.0
gitlens|eam|8.0.2
vscode-html-css|ecm|0.2.0
ansible|haa|0.2.7
terraform|mau|0.0.20
python|ms-|2018.1.0
Ruby|reb|0.16.0
ansible-autocomplete|tim|0.0.2
vim|vsc|0.11.0
jinja|who|0.0.8
change-case|wma|1.0.0

</details>
Reproduces only with extensions (can't debug with extensions disabled)

**Comment by tsalinger** [comment]
This does not seem to be a VS Code specific issue. Please open an issue in the python extension [repository](https://github.com/Microsoft/vscode-python/issues).
