### ISSUE TITLE
Support chords while terminal is focused

### ISSUE THREAD

**Issue by apechimp** [microsoft/vscode#44764]
### Issue Type
Bug

### Description

1. Add a keybinding with a chord for a command that should skip the shell, e.g., 
```json
{
	"key": "ctrl+w j",
	"command": "workbench.action.terminal.focusNext",
	"when": "terminalFocus"
}
```
2. Ensure that command is in the `terminal.integrated.commandsToSkipShell` array in your configuration
3. Enter the keystroke from the terminal

Instead of focusing the next terminal, `j` is entered into the shell.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_65552|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
better-toml|bun|0.3.2
dep|car|0.1.0
gitlens|eam|8.0.2
launchdarkly|lau|1.1.0
Go|luk|0.6.77
vscode-cosmosdb|ms-|0.4.0
azure-account|ms-|0.3.1
duckduckgo|tai|0.0.3
vim|vsc|0.11.0
vscode-open-in-github|ziy|1.3.1

</details>
Reproduces without extensions

**Comment by apechimp** [comment]
Based on a cursory glance, it looks like `softDispatch` is missing [the chord handling that `dispatch` does](https://github.com/Microsoft/vscode/blob/7c1bb9f4effa6e1be92b2ace4ecc8c3c9d053d1c/src/vs/platform/keybinding/common/abstractKeybindingService.ts#L136-L146).

**Comment by apechimp** [comment]
It's kinda opaque to me the consequences of adding that to `softDispatch`, but I'm happy to put up a PR that does that if the approach seems reasonable.

**Comment by Tyriar** [comment]
@alexandrudima I can't remember if there a reason we don't do this or if it was an oversight when we did `softDispatch`?

**Comment by alexandrudima** [comment]
PR welcome, @Tyriar  I don't think it is something we needed at that time.

**Comment by u2berggeist** [comment]
Not to interrupt the more productive discussion, but I just wanted to say that I would like this feature. I was about to write an issue about it until I found this.

**Comment by eyaleizenberg** [comment]
Any update on this?

**Comment by Tyriar** [comment]
This should work in the next insiders build (v1.40), note that it has some quirks:

- A new setting `terminal.integrated.allowChords` has been added that defaults to `true`. When true this will allow any chord command to skip the shell (ignoring `commandsToSkipShell`), when false it will act as before.
- Whether or not chord mode is entered depends on the keybinding with the highest priority. Similar to how ctrl+k would just break before if you have an extension with a ctrl+k chord keybinding, this rule still applies.
