### ISSUE TITLE
Copying from Integrated Terminal intermittently doesn't work

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#44769]
- VSCode Version: 1.20.1
- OS Version: High Sierra

Steps to Reproduce:

This is an intermittent issue so I can't reliably create steps, but here is my experience:

In the *Terminal app*, I can run my end-to-end testing suite and successfully copy and paste errors from output to Chrome.

In the *Visual Studio Code Integrated Terminal*, occasionally I will end up in a state where copying inside the Integrated Terminal and pasting into Chrome does not work. Despite right-clicking a selection and choosing "Copy", the text pasted in Chrome will either paste previously copied text, or make an error sound.

This error will carry over to other text inside Visual Studio Code, e.g. when trying to copy a property from the settings menu, or code in an editor. After some experimenting with copying/pasting from/to different apps to narrow down the issue, it will inexplicably go away.

This issue didn't exist until the most recent update. And I agree it's hard to take action on this issue with the current details, but I'd be remiss if I didn't create an issue in case others are having this experience and can share any clarifying details.

Does this issue occur when all extensions are disabled?: Unknown

**Comment by Tyriar** [comment]
Can't reproduce unfortunately, have you tried to see if it still happens under the Insiders build? https://code.visualstudio.com/insiders/
