### ISSUE TITLE
Launch tasks defined in workspace settings fail

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#44760]
### Issue Type
Bug

### Description

I've defined the following launch task in my workspace settings:
```
"settings": {
	"launch": {
		"configurations": [
			{
				"type": "cppvsdbg",
				"request": "launch",
				"name": "Launch",
				"program": "${workspaceFolder:launcher}/bin/launcher32.exe",
				"cwd": "${workspaceFolder:lt}",
				"environment": [
					{ "name": "PATH",           "value": "%PATH%;${workspaceFolder:shared}/lib_win32" },
					{ "name": "_NO_DEBUG_HEAP", "value": "1" }
				],
			}
		]
	}
}
```

And when I run it I see `Cannot determine executable for debug adapter '{0}'.` Repeating this test in the Insiders edition more helpfully clarifies the '{0}' as 'cppvsdbg'. 

This same task copied and pasted into tasks.json in a workspace subfolder works correctly. This leads me to believe VS Code is not able to resolve the debugger type, which has been added through the official C++ extension.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.89GB (8.57GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Dev\Limit Theory\pr.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.3
tortoise-svn|fan|0.1.1
vsc-space-block-jumper|jmf|1.2.2
Lua|key|0.0.9
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
code-settings-sync|Sha|2.8.7
shader|sle|1.1.2
Align|ste|0.2.0
unity-debug|Uni|1.3.0
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by weinand** [comment]
The launch configuration looks fine and VS Code is able to resolve the debugger type (otherwise the error message would be different).
The error message "Cannot determine executable for debug adapter" originates from debugAdapter.ts.
@isidorn any idea what can go wrong if the launch config comes from a workspace setting?

**Comment by akbyrd** [comment]
I've just reproduced this in user settings as well.

**Comment by isidorn** [comment]
@akbyrd we have pushed a lot of fixes in this area please try it with latest insiders 

If you still see it in the latest insiders the error message is coming from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/node/debugAdapter.ts#L90)
So I would suggest to just open VScode, developer tools and put a breakpoint there. My best guess is that something does not get resolved properly.
If you would not like to debug it would be great if you can share your repository on GitHub so I investigate

**Comment by akbyrd** [comment]
Reproduced in Insiders, except is a dialog box instead of the notification.
>Version 1.21.0-insider
>Commit 9a04587cc6b42c332609a08bfd7e2dbeac592c21

Luckily, it easily repros in a new, trivial workspace. I've set it up loosely mirroring our current project workspace structure, but even more minimal cases will repro. Just open the workspace and hit F5.

[Workspace Launch Repro.zip](https://github.com/Microsoft/vscode/files/1771855/Workspace.Launch.Repro.zip)

**Comment by weinand** [comment]
@isidorn I've debugged this on Windows and the problem is that we are not calling the "adapterExecutableCommand" of the C++ extension because the "root" is undefined in the workspace case:

![2018-03-01_17-46-28](https://user-images.githubusercontent.com/1898161/36857806-c4f5f088-1d79-11e8-9afb-d3722d2c29c1.png)
 
After changing the code in the following way the executable could be determined correctly:
```js
// try deprecated command based extension API
if (this.rawAdapter.adapterExecutableCommand) {
	return this.commandService.executeCommand<IAdapterExecutable>(this.rawAdapter.adapterExecutableCommand, root ? root.uri.toString() : undefined).then(ad => {
		return this.verifyAdapterDetails(ad, verifyAgainstFS);
	});
}
```

**Comment by isidorn** [comment]
@weinand thanks for the investigation and a fix!
