### ISSUE TITLE
Introduce a setting to configure display of hover widget

### ISSUE THREAD

**Issue by ironcladlou** [Microsoft/vscode#4476]
- VSCode Version: 10.10.11
- OS Version: OSX 10.11.3

I am not able to find any setting which allows me to globally disable automatic tooltips generated by plugin `HoverProvider` implementations. I prefer to see `HoverProvider` information only when a modifier key is pressed (i.e. peek definition). I find automatic tooltips distracting, and there are also some [performance implications](https://github.com/Microsoft/vscode-go/issues/257) depending on how plugins gather information.

**Comment by ironcladlou** [comment]
There are also some performance benefits to disabling this feature, depending on the plugins in use (see https://github.com/Microsoft/vscode-go/issues/257).

**Comment by mjbvz** [comment]
Tracked by #30114 I believe
