### ISSUE TITLE
syntax highlighting in visual studio .sln files

### ISSUE THREAD

**Issue by rchande** [Microsoft/vscode#44761]
Copied from https://github.com/OmniSharp/omnisharp-vscode/issues/2056, a request for syntax highlighting in .sln files.

VS Code version: 1.20.1
C# Extension version: 1.14.0

## Steps to reproduce
Open the .sln file for your project

## Expected  behavior
To see syntax highlighting

## Actual behavior
All one color

**Comment by rchande** [comment]
I have confirmed that this bug is not related to the one suggested by vscodebot.

**Comment by aeschli** [comment]
this should come from an extension.
