### ISSUE TITLE
Problems with C++ syntax highlighting

### ISSUE THREAD

**Issue by mattlanser** [Microsoft/vscode#4477]
- VSCode Version: 0.10.11
- OS Version: Ubuntu 15.10 (64-bit)

Steps to Reproduce:
1. Enter 
`asm("movw $0x38, %ax; ltr %ax");	 `

Example:
![screenshot from 2016-03-20 21-08-40](https://cloud.githubusercontent.com/assets/12996728/13906801/fa879c4e-eedf-11e5-8a39-7c23dc8ba57f.png)

**Comment by aeschli** [comment]
This issue was moved to textmate/c.tmbundle#41

**Comment by aeschli** [comment]
Found the issue on our side. Duplicate of #4769
