### ISSUE TITLE
API: Method for intercepting TextDocument edits and modifying / formatting them

### ISSUE THREAD

**Issue by briankendall** [microsoft/vscode#44771]
* VSCode Version: 1.20.1
* OS Version: macOS 10.13.3

I'm working on an extension that implements the "indent to bracket" behavior available in Sublime Text and other text editors. This is a feature that has been requested before, and it's intended to work in any number of different languages and contexts. So far, my extension is mostly finished, but I don't believe I'm able to use the VS Code extension API to do precisely what I want.

Currently, I am listening for `workspace.onDidChangeTextDocument` events, detecting when the event indicates that a newline was typed, using a timeout to wait until VS Code has inserted the new line and any indentation, and then editing the current text document to adjust the indentation to the correct level.

Unfortunately, this has a major issue, which is that it creates two edits when you press the enter key. Not only does this create a visual discontinuity -- the insertion point quickly jumps between two locations -- but means that if I try to undo the newline, it will only undo the change to the indentation level rather than undoing the creation of the new line as well.

What I need is something akin to a `workspace.onWillChangeTextDocument` event, and to have it allow modifying or canceling the proposed edit.

Alternatively, a more specific API that allows hooking into newline creation and optionally overriding indentation behavior would be acceptable too.

The current code for my extension is available here: https://github.com/briankendall/vscode-indent-to-bracket

**Comment by jrieken** [comment]
> What I need is something akin to a workspace.onWillChangeTextDocument event, and to have it allow modifying or canceling the proposed edit.

There is *something like that* already in the available. It's the `type`-command and used by vim, tho I'd recommend using it. Your use case might be suitable for a 'format-on-type'-provider. Also circling @alexandrudima to decide if this is better done in the editor itself.

**Comment by alexandrudima** [comment]
We don't currently have a good story for participating in typing... A `format-on-type` provider might be the best thing here...

**Comment by briankendall** [comment]
@jrieken Ah, I didn't realize from reading through the extension docs that overriding the `type` command was an option. I just checked out the source code for the vim extension to see how they did it, and was able to implement it in my own extension. Now I've *almost* got the behavior I want.

The current problem is, on the instances where my extension does intercept a `type` command and uses `TextEditor.edit()` to insert a newline plus some whitespace, the undo / redo behavior is still not quite right:

Undoing works fine. However, if you undo and then redo, the insertion point remains at the end of the previous line, rather than moving to the end of the newly created line.

@jrieken or @alexandrudima : Could either of you confirm this is a bug that should have its own issue? If so, I'd be happy to create it. If not, any advice on how to get the behavior I want?

Regardless, I agree that adding something to the API like `format-on-type` or that's otherwise explicitly meant for applying code formatting would be a great idea. Not only would it give me a direct way of implementing my own extension without resorting to something of a hack, but it would open the door to numerous other formatting extensions. And while VS Code already has a few good formatting options, as you are no doubt aware developers are an opinionated bunch, and allowing extensions to provide the specific (and perhaps meticulous) formatting that people desire would almost certainly broaden the appeal of VS Code.

**Comment by briankendall** [comment]
Quick update: I found a work around for the undo/redo issue by executing two calls to `TextEditor.edit()`. The first one inserts the text I want while only creating an undo stop before the edit (but not after). The second inserts an empty string after the text inserted by the first edit, and it only creates an undo stop after.

**Comment by alexandrudima** [comment]
@briankendall Please create a new issue with a simple repro if undo-redo is somehow funky around `TextEditor.edit()`. i.e. cursor state not correctly captured or something...

**Comment by briankendall** [comment]
@alexandrudima Done #44995

**Comment by matklad** [comment]
For posterity, here's how "override type" is implemented: 

https://github.com/VSCodeVim/Vim/blob/0b161207a1e7ee785a88b6adf8a6c327397595c9/extension.ts#L204-L215

**Comment by zimonitrome** [comment]
I still think something like `workspace.onWillChangeTextDocument` would be useful. 

I am in a similar scenario to @briankendall, except I want to incept any document edits. Typing, backspacing, pasting (are there more?). Pretty much every possible edit (maybe except undo/redo).

`workspace.onDidChangeTextDocument` works well for detecting edits. I can even detect if it was an undo/redo/other. And then I can apply my own custom editd on top of the user edit.

But this effectively creates 2 edits per user action. So the user will need to undo twice for what is percieved to be just one edit.

Will I just need to override all text edit commands? How many are there? And even then I would need to re-implement the edit function of each one only to slightly alter the edit itself.

I made a StackOverflow post that describes this problem in a different way: https://stackoverflow.com/questions/71538839/combine-document-text-changes-or-anticipate-them

**Comment by zimonitrome** [comment]
@jrieken @alexdima any thoughts on re-opening this issue/feature request?

I have tried to find a solution to my above probelm for a couple of weeks now and maybe I just need some help. A possible solution could be to use a formatter but I want my extension to work alongside other formatters and on any document edit (type/paste/other?). If I were to use a formatter, I would need to store any formatting settings, set formatontype=true, maybe manually format if that does not create an extra action on the undo/redo stack, before resoting the user's formatting settings. [Something like this](https://stackoverflow.com/a/57617310/7829241).

That does not seem like the right way to go.

**Comment by zimonitrome** [comment]
My specific problem could be solved by passing `{undoStopBefore: false, undoStopAfter: false}` to the `editor.edit()` function.

https://stackoverflow.com/a/71787897/7829241
