### ISSUE TITLE
Git: fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44776]
Windows 10/Insiders

Repro:

1. Open a folder
2. Init git repo
3. Add files and do a commit
4. Undo last commit

![image](https://user-images.githubusercontent.com/2193314/36816406-847de6c4-1c92-11e8-80e9-8b319bdc4259.png)

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.13.2.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git init
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\Users\daimms.REDMOND\Documents\playground\t
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git add -A -- c:\Users\daimms.REDMOND\Documents\playground\t\script-1.bat
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git add -A -- c:\Users\daimms.REDMOND\Documents\playground\t\.vscode\tasks.json
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git commit --quiet --allow-empty-message --file -
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name --abbrev-ref master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git show -s --format=%H
%B HEAD
> git reset HEAD~
fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git show -s --format=%H
%B HEAD
> git reset HEAD~
fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by sergiorojasa** [comment]
@Tyriar and @joaomoreno I would like to work on this issue.

**Comment by Tyriar** [comment]
@sergiorojasa 👍

**Comment by sergiorojasa** [comment]
@Tyriar  I tried to fix the issue but I couldn't fix it.

**Comment by ryu1kn** [comment]
## Cause of the issue

We can reproduce this issue on macOS as well. Also we can get the same error message on terminal if we execute `git reset HEAD~` because Code is doing the same thing through `CommandCenter#undoCommit` (in `extensions/git/src/commands.ts`) ➡️ `Repository#reset` (in `extensions/git/src/git.ts`)

```sh
$ git reset HEAD~
fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

The error occurs because if the last commit is the initial commit (or no parents) of the repository, there is no `HEAD~`.

## Desirable outcome of "Undo Last Commit" (I think)

* When the last commit is **not** the initial commit
  * Keep the current behaviour. i.e. Bring the repository back to the clean (no uncommitted/staged files), previous commit state
* When the last commit **is** the initial commit
  * Bring the repository back to clean (no uncommitted/staged files), no commit state

## Solution to the issue (my suggestion)

To undo the last commit, we can do the following depending on the last commit.

* When the last commit is **not** the initial commit
  * No changes. i.e. Execute `git reset HEAD~`
* When the last commit **is** the initial commit
  * Execute `git update-ref -d HEAD` followed by `git rm -fr .` cf. [How to revert initial git commit?](https://stackoverflow.com/questions/6632191/how-to-revert-initial-git-commit)

To check whther the last commit is the initial commit, we can run `git rev-list` with `--parents` option.
If it gives the current commit followed by other commits (i.e. parents), we know the current commit is not the initial commit.

```sh
$ git rev-list --all --parents --max-count=1
43e1f4b00f3cdb5e8f280ce6ea29871e849cf047 53610b8ef24cb8ceba35a0c244cf841324ad1276
```

**Comment by ryu1kn** [comment]
Any thoughts on ⬆️, @joaomoreno?

**Comment by ryu1kn** [comment]
Thanks @andrewtomai for the pointer. I somehow misunderstood that "Undo Last Commit" not just reset the commit but bring `Bring the repository back to the clean (no uncommitted/staged files), previous commit state`. So the desirable outcome section is wrong, so is the solution (i.e. `git rm -fr .`)

**Comment by ryu1kn** [comment]
Updated my fix suggestion comment

**Comment by ryu1kn** [comment]
Actually, I can see if a commit has parents or not by extending `Repository#getCommit` (in `extensions/git/src/git.ts`) like this 5c139f7fe8b74cb553be422e3ac668607d9d8060. Updated the fix suggestion again.

**Comment by ryu1kn** [comment]
Oh wow, sorry I didn't notice that rebasing on my branch posted so many refs on this issue...

**Comment by joaomoreno** [comment]
The way to achieve this might be much simpler. Simply delete the branch and recreate it. Would that work?

**Comment by ryu1kn** [comment]
Hmm... do you mean something like this? 

```sh
# We want to reset the only commit on "master" branch
$ git checkout -b temporary       # we need to pick a branch name which doesn't conflict with others
$ git branch -D master
$ git checkout --orphan master
$ git rm --cached -r .
$ git branch -D temporary
```

I think the current way ⬇️is simpler.

```sh
# We want to reset the only commit on "master" branch
$ git update-ref -d HEAD
$ git rm --cached -r .
```

If you know the better way, I'm happy to revise the PR. Can you list the git commands like above in that case? 😃

**Comment by joaomoreno** [comment]
You're right! 👍

**Comment by paulsabandal** [comment]
@ryu1kn I tried your way. Works for me. Thanks!

**Comment by ryu1kn** [comment]
Thanks @paulsabandal , I've created a PR, #47578, and am wondering if someone in the code team can have a look at it...

**Comment by Pictor13** [comment]
@ryu1kn, I tried on shell your 

`git update-ref -d HEAD`
`git rm --cached -r .`

but it returns me an

> error: the following file has staged content different from both the
> file and the HEAD:
>    <directory_name_inside_my_project_root>
> (use -f to force removal)

I managed to get what I wanted with *force*. 

I know nothing of *vscode*, just passing from here :) , but I thought it could interest someone (maybe to specify it in `unstageAll`, if not implicit already).
