### ISSUE TITLE
Built-in extension publisher shouldn't be clickable in Extension Details pane

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#44774]
- VSCode Version: 1.21.0 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1.Show @builtin extensions in Extension View
2. Click an extension item to see Details pane
3. Hover over built-in extension publisher "vscode" (goes to hand icon)
4. Click the extension publisher results in 'publisher:"vscode"' query in the Extension view.

Built-in extension publisher shouldn't be clickable. 

Better yet the publisher row could be removed entirely for built-in extensions

**Comment by sandy081** [comment]
We have built in extensions coming from market place. So removing that might impact them. So fix is to disable clicking on extensions which do not exist in market place

**Comment by sandy081** [comment]
Fixed by 59a8ee17f6d98bfe2db11fc114d3aacb6bcce821
