### ISSUE TITLE
Search exclusions honoring .gitignore do not always work correctly

### ISSUE THREAD

**Issue by MartinFalatic** [Microsoft/vscode#44770]
### Issue Type
Bug

### Description

Given a repo with the following files:
```
./.gitignore
./foo/a
./foo/bar
./foo/c
./other
```

if .gitignore contains the following:

```
foo
!foo/bar
```

then only `bar` will be version controlled under `foo` (other items under `foo`, like `a` and `c` above, will be ignored).

However, when the gear icon for excluded files is selected (to honor .gitignore) VSCode search will completely ignore `foo/bar`. This is incorrect behavior.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.71GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
vscode-docker|Pet|0.0.25
multiline-find-and-replace|axl|0.0.1
vscode-custom-css|be5|2.7.0
vscode-svgviewer|css|1.4.3
gitlens|eam|8.0.2
vscode-semistandard|fle|1.1.2
githd|hui|1.1.1
Go|luk|0.6.77
python|ms-|2018.1.0
debugger-for-chrome|msj|4.1.0
rst-vscode|tht|2.0.0
pdf|tom|0.2.0

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
I think your gitgnore is wrong. https://stackoverflow.com/a/2820310/129895

With that setup, when foo/bar is not added to git, I get 

```
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitignore

nothing added to commit but untracked files present (use "git add" to track)
```

But with 

```
foo/*
!foo/bar
```

I get the expected result
