### ISSUE TITLE
Built-in extension name shouldn't be clickable in Extension Details pane

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#44772]
- VSCode Version: 1.21.0 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Show @builtin extensions in Extension View
2. Click an extension item to see Details pane
3. Hover over built-in extension name (goes to hand icon)
4. Click the extension name results in 404 on the Marketplace

Built-in extension names shouldn't be clickable.

**Comment by sandy081** [comment]
We have built in extensions coming from market place. So removing that might impact them. So fix is to disable clicking on extensions which do not exist in market place
