### ISSUE TITLE
Feature Request: Launch tasks similar to prelaunch, but do not await it's completion.

### ISSUE THREAD

**Issue by gavinunderdown** [Microsoft/vscode#44775]
Say you have a task that you want to run, for example, a task that SSH's into a remote, and you want to keep that task (and therefore the connection) running, but you also want to start the debugging of your code. 

Currently, if you define a prelaunchTask, then it just sits and hangs until that task ends. 

I would like to see something like "concurrentTask" that executes your before launching debug, but does not require completion to proceed. 

It would also be OK if you could define a maximum execution time for prelaunchTasks, after which it would proceed with the launch regardless of if the prelaunchTask completed (with a warning you could choose to ignore).

A more realistic example would be a shell script that you run from a task, which builds and sets up gdbserver on a remote, and you setup your launch.json to have a debugging server ready. 

Thank you!

**Comment by ShakenU** [comment]
Would also be nice if there was an option to kill the task if it was already running, and restart it.

**Comment by isidorn** [comment]
This feels like it should be a property of the task
I am closing as out of scope, @dbaeumer if you are passionate about this feel free to reopen
