### ISSUE TITLE
Turnoff code greying in case of #if <defined>

### ISSUE THREAD

**Issue by sumonto** [Microsoft/vscode#44780]
Mac OS High Sierra
Version: 1.20.1

Steps to Reproduce:

#if <defined> code is doing the wrong thing since the #defines are in a makefile
Thus code which should not be greyed out is being greyed out
Obviously there is no way for VSCode to know every single #define, wondering if I can turn off this smart feature 

"C_Cpp.intelliSenseEngine" : "Tag Parser" did not work

These #if <defined> are not related to Arch purely context based

Thanks

**Comment by tsalinger** [comment]
This does not seem to be a VS Code specific issue. Please open an issue in the extension's [repository](https://github.com/Microsoft/vscode-cpptools/issues).
