### ISSUE TITLE
Goto File Not Searching in Classes subfolder

### ISSUE THREAD

**Issue by sillysaint** [Microsoft/vscode#44786]
Quick Go To File (Command +p)is not searching in Classes subfolder (file extension ".cls"). I dont have any thing excluded in Settings and workspace.

- VSCode Version:  Version 1.20.1 (1.20.1)
- OS Version: Mac OS High Sierra (10.13.3)

Steps to Reproduce:

1. Create a folder hierarchy Project > src > classes
2. Inside classes folder create files with extension cls.
3. Search for these files using command+p in mac.

The .cls files wont show up in the list.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Are these files excluded by a `files.exclude` or `search.exclude` setting? Or are they in a .gitignore file?
