### ISSUE TITLE
Insiders version, can't update

### ISSUE THREAD

**Issue by RootKlawiter** [Microsoft/vscode#44799]
VS Code still works, but I get that one issue: 
![vscodeissue](https://user-images.githubusercontent.com/30440603/36833058-71e1da38-1d2e-11e8-88dc-37324891fade.PNG)

**Comment by joaomoreno** [comment]
Can you send us the log file?

**Comment by RootKlawiter** [comment]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1771697/vscode-inno-updater.log)
here is log file

**Comment by joaomoreno** [comment]
Can you send me `C:\Program Files\Microsoft VS Code Insiders\unins000.dat`?

**Comment by RootKlawiter** [comment]
github doesn't support that file type, here's that file on my GDrive: https://drive.google.com/open?id=1PDEBQcBe2kJ-enFfjVB-iS0F7XJJzJfy

**Comment by joemaffei** [comment]
Same issue here.

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1771889/vscode-inno-updater.log)

CPUs | Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)
-- | --
Memory (System) | 7.89GB (2.71GB free)
Process Argv | C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
Screen Reader | no
VM | 0%


Extension | Author (truncated) | Version
-- | -- | --
Bookmarks | ale | 0.18.1
project-manager | ale | 0.24.0
cucumberautocomplete | ale | 2.8.0
npm-intellisense | chr | 1.3.0
path-intellisense | chr | 1.4.2
vscode-eslint | dba | 1.4.7
githistory | don | 0.4.0
auto-close-tag | for | 0.5.6
sass-lint | gle | 1.0.1
vscode-firefox-debug | hbe | 1.1.0
vscode-styled-components | jpo | 0.0.16
vscode-postcss-sorting | mrm | 3.0.1
debugger-for-chrome | msj | 4.1.0
vscode-icons | rob | 7.20.0
trailing-spaces | sha | 0.2.11
sort-lines | Tyr | 1.4.1
gitblame | wad | 2.2.0

**Comment by RootKlawiter** [comment]
and if you need that, my specs are: 
i7 6700hq
gtx 960m
samsung evo 960 pro (something like that) 512Gb Nvme
16Gb DDR4 RAM

**Comment by joaomoreno** [comment]
@RootKlawiter That file appears to be empty. Is it empty on your system too? Zero bytes?

**Comment by RootKlawiter** [comment]
sorry, on my system that's empty too 😕 
I don't know what happened 😕

**Comment by joaomoreno** [comment]
OK that is interesting. You need to completely uninstall and reinstall VS Code.

**Comment by RootKlawiter** [comment]
okey, thanks for your help and your time 😃
