### ISSUE TITLE
venv problem with python3.6 and git-bash on win10

### ISSUE THREAD

**Issue by LanceLovereading** [Microsoft/vscode#44791]
- VSCode Version: 1.20.1(latest version on 2018-03-01)
- OS Version: win10

Steps to Reproduce:

I'm using win10 + vscode + python3.6 + venv + git-bash.

When I right click in editor and select "Run Python file in terminal", it shows the following:
source C:\Documents\Work_folder\venv\Scripts\activate
No such file: C:DocumentsWork_foldervenvScriptsactivate

All the backword slash in path dispear when the bash try to execute the file.

I try this on my other computer, it work as expected, the result is following:
source "C:\Documents\Work folder\venv\Scripts\activate"

I realized that the only difference is that I use "Work folder" as folder name rather than "Work_folder". It seems if the path of venv folder do not contain any space, it will omit the double quotation marks, and eventually lead this bug.

Any one have any idea?

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
> When I right click in editor and select "Run Python file in terminal"

I think this is coming from an extension, you need to report there. There are no terminal-related context menu actions in the editor by default.
