### ISSUE TITLE
Zen Mode content no longer displays at full screen width

### ISSUE THREAD

**Issue by morganwdavis** [Microsoft/vscode#44794]
Issue Type: <b>Bug</b>

New regression: The last two insider builds no longer show Zen Mode content at full width of the display, but instead centers the content with enormous margins on the side. This constrains the content area so small that you have to do a lot of side to side scrolling to see anything.

This is a high DPI laptop display (Dell XPS 13 with Quad HD screen).

VS Code version: Code - Insiders 1.21.0-insider (3fec61014742dec894b3a31cdf8556bf533cb0e1, 2018-02-28T05:17:16.839Z)
OS version: Windows_NT x64 10.0.17074

![image](https://user-images.githubusercontent.com/4434533/36829227-143971f8-1cd3-11e8-8520-303774acfb79.png)

**Comment by isidorn** [comment]
This is as desgined.
Use `"zenMode.centerLayout": false`

However with the tomorrow's vscode insiders it should not center so much, but in a nice golden ratio

**Comment by morganwdavis** [comment]
@isidorn I can see the designed behavior being nice on very large screens, so the added margin with centered content is great for focus. But on a laptop, I actually used zen mode for maximizing the amount of space available to see as much content as possible.  The "zenMode.centerLayout": false workaround is just what I needed. Thanks for the quick solution!

**Comment by isidorn** [comment]
In the future we should look at monitor size to decide if we should center or not
