### ISSUE TITLE
The code in some.C files is all grey

### ISSUE THREAD

**Issue by CaiHua1995** [microsoft/vscode#44792]
### Issue Type
Bug

### Description

The code in the ST Hal library .C file is all grey

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|7.70GB (3.54GB free)|
|Process Argv|C:\APP\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
aio-compiler|azt|1.0.2
GBKtoUTF8|buk|0.0.2
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.13.0
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.1.3
CppSnippets|har|0.0.13
vscode-cdecl|kae|1.0.0
vscode-clang|mit|0.2.2
cpptools|ms-|0.15.0
team|ms-|1.122.0

(6 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
Closing this as out of date. It seems to have magically popped into our issues.

If you are still effected by this, please open a new issue
