### ISSUE TITLE
The type or namespace name `Forms' does not exist in the namespace `System.Windows'. Are you missing `System.Windows.Forms' assembly reference?

### ISSUE THREAD

**Issue by dpMerchant** [Microsoft/vscode#4479]
- VSCode Version: - 0.1.0 
  OS Version: elementary OS 0.3.2 Freya (64-bit) (Built on Ubuntu 14.04)
Steps to Reproduce: 

1. After installing VSCode and Mono 4.2.3 I tried the "helloworld" samples.
2.  When I tried the Winforms sample I got these two error messages.

WinHello.cs(2,22): error CS0234: The type or namespace name `Forms' does not exist in the namespace `System.Windows'. Are you missing `System.Windows.Forms' assembly reference?
WinHello.cs(4,27): error CS0246: The type or namespace name `Form' could not be found. Are you missing an assembly reference?
Compilation failed: 2 error(s), 0 warnings

Here is a link to the sample code that you provided on your website.
http://www.mono-project.com/docs/getting-started/mono-basics/

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#443
