### ISSUE TITLE
inbuild console text is unreadable

### ISSUE THREAD

**Issue by nnIIInnjA** [Microsoft/vscode#44797]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.24
jsx|Twe|0.0.1
vscode-wakatime|Wak|1.1.22
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.28
vscode-clang|mit|0.2.2
cpptools|ms-|0.15.0
vetur|oct|0.11.7

---

Steps to Reproduce:

1. sometimes when i open my editor terminal, the text changes to some unreadable format. the only way to get rid of it is to restart the editor.

Reproduces without extensions: Yes/No

**Comment by praveenpuglia** [comment]
can you please post a screenshot?

**Comment by Tyriar** [comment]
This will be fixed in v1.21 which will come out in around a week.

**Comment by Tyriar** [comment]
Actually you may be seeing an issue that was fixed in 1.20, you should upgrade now.
