### ISSUE TITLE
thumbnail should match editor.minimap.enabled

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#44793]
Issue Type: <b>Settings Search Issue</b>

in settings search i searched for "thumbnail", which is a term used for the scrollbar/minimap.  `editor.minimap.renderCharacters` comes up first, but `editor.minimap.enabled`  comes up in the 16th position. i would expect them to be closer together.

VS Code version: Code - Insiders 1.21.0-insider (3fec61014742dec894b3a31cdf8556bf533cb0e1, 2018-02-28T05:17:16.839Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Results</summary>

Setting|Extension|Score
---|---|---
editor.minimap.renderCharacters|core|2.003
editor.overviewRulerBorder|core|1.512
editor.overviewRulerLanes|core|1.475
markdown.preview.scrollPreviewWithEditor|core|1.447
markdown.preview.fontSize|core|1.435
markdown.preview.scrollEditorWithPreview|core|1.322
markdown.preview.lineHeight|core|1.305
editor.minimap.side|core|1.280
markdown.preview.linkify|core|1.268
markdown.preview.doubleClickToSwitchToEditor|core|1.267
markdown.preview.fontFamily|core|1.264
markdown.preview.breaks|core|1.200
editor.minimap.showSlider|core|1.175
markdown.preview.markEditorSelection|core|1.144
editor.minimap.maxColumn|core|1.089
editor.minimap.enabled|core|1.083
workbench.editor.enablePreview|core|0.889
workbench.editor.enablePreviewFromQuickOpen|core|0.826
editor.hideCursorInOverviewRuler|core|0.331
markdown.previewFrontMatter|core|0.239

</details>

Query: thumbnail
Literal matches: 0

**Comment by roblourens** [comment]
Filed upstream.

@chrisdias Do you think `.enabled` settings should generally rank higher than others? Could add a general boost for settings that end in `.enabled`.l

**Comment by chrisdias** [comment]
today nothing comes up when searching for `thumbnail`. 

![image](https://github.com/microsoft/vscode/assets/1487073/242d0e99-5ba2-4fde-b8a1-ef514f665593)

Not sure we even do the Bing search anymore, and I assume something like this (very fuzzy search) would be subsumed by Copilot.

So, this issue can probably be closed.
