### ISSUE TITLE
Don't close Commands View on losing Focus

### ISSUE THREAD

**Issue by prasannavl** [Microsoft/vscode#448]
Closing Commands View on losing focus is annoying, particularly when installing or searching for extensions, and commands that are not instantaneous. 

Please stop the commands view from closing itself when the window loses focus.

**Comment by bpasero** [comment]
As designed, however we also see the issue that extensions should go into a more stable view and not quick open.

**Comment by prasannavl** [comment]
I see this as future solution to the extensions issue: https://github.com/Microsoft/vscode/issues/637

However, while I understand its "as designed", I really see no good reason why it is really designed that way. Is there a reason why the command window has to be closed when the window loses focus? 

I see this as something that seems to be inherited from Atom. The "ext install" is just one scenario that highlights this problem. But often switching between windows, and losing the command window is extremely frustrating. Just changing this design decision will not just enable the multi-taskers to work with ease, but also provide a temporary mitigation to the "ext install" problem until the new UI is designed (which I surmise will take quite a while looking at the state of things).

Could this be reconsidered?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/444

**Comment by bpasero** [comment]
This is coming for August via #444.
