### ISSUE TITLE
Pressing Ctrl + Z causes freeze on 'User settings'

### ISSUE THREAD

**Issue by raacker** [Microsoft/vscode#44805]
- VSCode Version: Latest codebase version, but happened on released version either
- OS Version: MacOS, Ubuntu

Steps to Reproduce:

1. Go to settings
2. Press Ctrl + Z

Does this issue occur when all extensions are disabled?: Yes

I figured out that Ctrl + Z on setting tab just caught an error 'Not supported' and setting tab gets froze. Even though it's not supporting Ctrl + Z, should not freeze. 

It seems like 'viewLineNumber' is being reset with Ctrl + Z and go to zero which makes crash. I'm looking into it but have no idea that this issue is intended or bug. Could anyone confirm that is bug or not?

![image](https://user-images.githubusercontent.com/12020398/36836968-3e3fd234-1d7e-11e8-806f-a2327d1fc620.png)

**Comment by raacker** [comment]
I found that keybinding is working well, don't allow Ctrl + Z. But only when I make a breakpoint at keybindingResolver. Seems to be thread problem.

**Comment by sandy081** [comment]
@alexandrudima Default settings is a readonly editor and do you think supporting undo on readonly editor is valid?

**Comment by raacker** [comment]
Found the problem. Yes, default settings is a readonly and 'undo' command doesn't work. But platform takes 'undo' as window supported command through

https://github.com/Microsoft/vscode/blob/b27a905d2dc537c5e853b08dbb9fd7e69ca766c1/src/vs/workbench/electron-browser/window.ts#L149

here.

**Comment by alexandrudima** [comment]
Finally a repro for #43732
