### ISSUE TITLE
Constantly updating file runs git and causes PC to freeze

### ISSUE THREAD

**Issue by bipin-nag** [Microsoft/vscode#4480]
- VSCode Version:
Version 0.10.8
Commit db71ac615ddf9f33b133ff2536f5d33a77d4774e
Date 2016-02-05T10:00:07.223Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

- OS Version: 
Ubuntu 15.10 64bit

Steps to Reproduce:

1. Setup a repository for git
2. Add a file, push it and open in git view
3. External program appends it (log) very quickly

It can be averted if I added the file in .gitignore. Still its a valid concern as I didn't expect VSCode to run git multiple times while it is being updated. The numerous git processes freeze the PC. There should be a timeout/backoff if too many git operations are run.

**Comment by bipin-nag** [comment]
gits are run as soon as file is updated repeatedly

bipin    12966 12252  4 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating
bipin    12967 12252  5 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating
bipin    12968 12252  4 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating
bipin    12969 12252  4 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating
bipin    12970 12252  4 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating
bipin    12971 12252  4 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating
bipin    12972 12252  4 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating
bipin    12973 12252  4 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating
bipin    12974 12252  4 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating
bipin    12975 12252  6 03:22 ?        00:00:00 git show HEAD:myfile/thatwas/updating

The offending process was vs code

bipin    12252  9893  7 03:10 ?        00:00:52 /home/bipin/Downloads/VSCode-linux-x64/Code /home/bipin/Downloads/VSCode-linux-x64/resources/app/out/bootstrap git /home/bipin/xyz/folder/open utf8 /home/bipin/Downloads/VSCode-linux-x64/Code

**Comment by jrieken** [comment]
@bipin-nag 
> Add a file, push it and open in git view

Do you mean viewing in the diff editor or just in the view?

**Comment by egamma** [comment]
@bipin-nag can you reproduce this in the latest version of Code.

**Comment by jrieken** [comment]
With latest alpha this seems not to happen

**Comment by joaomoreno** [comment]
I can't repro either. We do have a [delayer of `500ms`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitWorkbenchContributions.ts#L203) protecting against this.

**Comment by bipin-nag** [comment]
@egamma Yes, I upgraded to recent Version 0.10.11 and it is still there.

@jrieken  yes while viewing the diff editor. Just viewing file is fine. But when in diff mode editor gets stuck on Loading which I think is running git commands in background. PC freezes after few minutes.

@joaomoreno I assume delayer of 500 ms is functional because it doesn't freeze at first. But it still can fire 120 procs a minute and if each one lingers as more are added, your PC dies within minutes.

There should be a max of git processes spawned.

**Comment by joaomoreno** [comment]
This specific delayer is a [ThrottledDelayer](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/async.ts#L203). This means it won't fire a second request before the first one finishes. So I'm finding this quite weird.

**Comment by joaomoreno** [comment]
@bipin-nag Is this still a problem today?

**Comment by bipin-nag** [comment]
Doesn't seem to happen now.
