### ISSUE TITLE
Connect paths when separated only by words and spaces

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44808]
Issue Type: <b>Bug</b>

Verifying #42517

Spaces break the coloring:

![image](https://user-images.githubusercontent.com/9205389/36839587-c7f1b434-1d42-11e8-8daf-0109ed35ede6.png)

VS Code version: Code - Insiders 1.21.0-insider (9a04587cc6b42c332609a08bfd7e2dbeac592c21, 2018-03-01T08:09:20.917Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|5.98GB (2.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
azure-account|ms-|0.3.1
azurecli|ms-|0.4.0
cpptools|ms-|0.15.0
github-issues-prs|ms-|0.9.0
debugger-for-chrome|msj|4.1.0
vscode-open-in-github|sys|1.6.0

</details>
Reproduces only with extensions

**Comment by sandy081** [comment]
File paths are no longer highlighted as per https://github.com/emilast/vscode-logfile-highlighter/issues/50
