### ISSUE TITLE
ENOT notification when adding an invalid path to a workspace file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#44809]
* open a workspace
* open its config file
* add a path doesn't exist
* 🐛 an error notification shows

<img width="873" alt="screen shot 2018-03-01 at 11 27 25" src="https://user-images.githubusercontent.com/1794099/36839941-b571161e-1d43-11e8-9637-e10a6d805ddf.png">

**Comment by bpasero** [comment]
@isidorn this seems to originate from the explorer:

![image](https://user-images.githubusercontent.com/900690/36843583-ab535f78-1d4f-11e8-9438-74fa23259b8f.png)

**Comment by isidorn** [comment]
This is general error reporting when a folder can not be resolved.
However since for roots we already show this with an error decoration in the explorer there is no need to also use the notification service in this case.
