### ISSUE TITLE
Save As: Default file type should be *.*

### ISSUE THREAD

**Issue by mrudulp** [Microsoft/vscode#44819]
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new file
2. Save it
3. Give name hello.js

Actual:
It saves by name hello.js.txt

Expected:
File should be saved as "hello.js".
One needs to first select "All Files(*.*) or No Extension" 
At the moment it is very annoying to switch it back to "All files" everytime when creating new code files.

Other:
I haven't noticed this to be a problem when working with Mac

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@mrudulp I cannot reproduce, see:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/36843683-f6279f00-1d4f-11e8-94c2-edd22098481a.gif)

**Comment by mrudulp** [comment]
Ok, so digged in bit more, and realised it occurs for file types unknown to VSC
So try to save an untitled file with following name -- hello.typs and it will save it as hello.typs.txt
![visual_studio](https://user-images.githubusercontent.com/3527464/36967605-db1a1cb2-2068-11e8-84de-46d7f54f0a13.gif)
