### ISSUE TITLE
Markdown shows stylesheet with preview, but not with the compiled files?

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#4481]
Is there a(n easy) way to get the preview to become the compiled file, which would include the styling? Following the tutorial just creates the html (stub, since it's not a full page), and looking at the marked github page gives precious little info regarding how to include a stylesheet in the compiled file, except for a few items from 2013 (found via a Google search).

**Comment by bpasero** [comment]
@rhires you want to compile the MD file to the HTML file and save it somewhere?

**Comment by rhires** [comment]
Yes. I get that the command to turn the file from *.md to *.html is separate from vscode. But I also figure that if vscode can turn markdown into a pretty preview within the editor itself, turning it into html should not be that much more difficult. I do wonder if it's outside of the scope of the project, though, which would make the whole question moot.

**Comment by bpasero** [comment]
@rhires yeah it is a bit outside the scope of VS Code. Maybe an extension could provide this but the intent of VS Code (core) is not to convert from MD to HTML and save the file. I encourage to write an extension for this!
