### ISSUE TITLE
path completion: completing a folder should retrigger code completion

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#44815]
Testing #44460 

Version 1.21.0-insider
Commit 9a04587cc6b42c332609a08bfd7e2dbeac592c21
Date 2018-03-01T06:47:39.037Z

- create `foo.html`, `bar.html` in a folder 'a/b/c'
- in `foo.html' have
```
<a href="../../../"
```
and do code completion after `/`.
- pick `a`
- this should result in `<a href="../a/"`  (slash at the end) and reopen code completion again so that the user can continue completing

**Comment by octref** [comment]
I was modeling after TS's path complete, but I guess for html it's a bit different since you can import from folder and it defaults to index.js, and there is no such behavior in html.

**Comment by aeschli** [comment]
A folder path is also valid in HTML (once navigated there, it's up to the web server to decide what to return), but I'd think it's the less common case and it users would rather continue to enter a path.

**Comment by aeschli** [comment]
Think of the many keystokes necessary to enter a long path like aaa/bbb/foo.html

`a`, `ctrl+space` (code assist), `enter` to select *aaa*, `/`, `b`, `ctrl+space`, `enter` to select *bbb*, `/`, `f`, `ctrl+space`, `enter` to select `foo.html`

That's 11 keys to enter a path.

With the suggested change:
- `a`, `ctrl+space` (code assist) select *aaa*, `ctrl+space` (code assist) select *bbb*, `ctrl+space` (code assist) select *foo.html*

To stick with a folder path:
- `a`, `ctrl+space` (code assist) select *aaa*, `ctrl+space` (code assist) select *bbb*, `escape`

Let's be better than the extensions.
