### ISSUE TITLE
[html] path completion: no completion if clsoing quote is missing

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#44816]
Testing #44460

Version 1.21.0-insider
Commit 9a04587cc6b42c332609a08bfd7e2dbeac592c21
Date 2018-03-01T06:47:39.037Z

- create `foo.html`, `bar.html` in a folder
- in `foo.html' have
```
<a href='./b
```
and do code completion after `b`.

-> should show bar.html as a proposal

**Comment by octref** [comment]
The existing behavior is wrong too. If we want to fix this it needs to go in html language service to get correct replace range.

However I'm wondering if we should limit ourselves to only completing inside quotes as 

![wrong](https://user-images.githubusercontent.com/4033249/36862693-74dd1370-1d3c-11e8-866a-02280f089d31.gif)

**Comment by aeschli** [comment]
It's not wrong, how can we know whether`>/div` is inside the string or after.
But yes, we can improve the heuristic.

**Comment by octref** [comment]
I don't think there is any reasonable heuristics. For example, here is a common case:

```html
<div class='| id='foo'>
```

What is the reasonable replace range for this? Until next `>`, until next whitespace, or between the two single quotes?

I have not heard complaints about this. I think autoclosing + the existing path completion is good enough.
