### ISSUE TITLE
Debug does not detach when stoping it

### ISSUE THREAD

**Issue by felpin** [Microsoft/vscode#44829]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. In a node project, create a configuration to run the project, e.g.:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/server/server.js"
    }
  ]
}
```
2. Launch the application in debug mode (F5)
3. Stop the debug
4. Try to debug again. There will be an error "listen EADDRINUSE 0.0.0.0:3000"

Somehow the debug process is not ending when clicking the stop button in debug bar.

A workaround to resolve this is kill the debug process. First find it:
```bash
ps aux | grep "server/server.js"
```
result:
```bash
felipe   11063  2.2  1.4 1177660 116400 ?      Sl   10:22   0:03 node --inspect-brk=19866 server/server.js
felipe   11214  0.0  0.0  14232  1068 pts/19   S+   10:25   0:00 grep --color=auto server/server.js
```
Then kill the process:
```bash
kill 11063
```

Does this issue occur when all extensions are disabled?: No

Interesting that this may be caused by an extension. I'll try to reproduce this issue disabling the extensions one by one.

**Comment by weinand** [comment]
What version of node.js are you using?

**Comment by felpin** [comment]
I disabled every extension I could and the error continued to happen.
Well.. There was one extension I couldn't disable: Node Debug 2. When I try to disable it, I get the error "Cannot disable extension 'Node Debug 2'. Extension 'Node Debug' depends on this."

But... When running code with `--disable-extensions` I think it gets disabled.

**Comment by felpin** [comment]
@weinand I'm using node v9.5.0 through nvm

**Comment by weinand** [comment]
node-debug and node-debug2 are builtin and you cannot disable them (which makes sense because without them you couldn't do any node debugging).

Could you just add the following server as a "./server/server2.js" to your project:
```js
var http = require('http');
http.createServer(function (req, res) {
	res.writeHead(200, { 'Content-Type': 'text/plain' });
	res.end('Hello World\n');
}).listen(3000);
```
and then change the "program" in your launch config to "${workspaceFolder}/server/server2.js".

If you launch this and then stop it, does it terminate correctly?
If you launch it again you should not get any "listen EADDRINUSE 0.0.0.0:3000" error.

**Comment by felpin** [comment]
@weinand I still get the same error. The debug process is still running.

**Comment by weinand** [comment]
Does your linux have the "/usr/bin/pgrep" utility?

**Comment by felpin** [comment]
@weinand yes, it does

**Comment by weinand** [comment]
- Before stopping the debug session please open the Chrome Dev Tools via the "Toggle Developer Tools" action and then switch to the "Console" tab.
- Then stop your server.

Any errors showing up?

**Comment by felpin** [comment]
No, nothing shows up after I start the server nor when I stop it.

Tho... When I open the code, there are some initial errors and warnings. I don't know if they are relevant to this issue.

![selection_001](https://user-images.githubusercontent.com/22778265/36853963-9076ff80-1d4e-11e8-8841-9d0a39155246.png)

**Comment by weinand** [comment]
The first warning indicates that you are not using the built-in node debugger (node-debug2).
Since node-debug2 is responsible for killing your debuggee, there could be a problem with your overridden version.

**Comment by felpin** [comment]
But, isn't this extension already in vscode by default? How could I overwrite it?

**Comment by weinand** [comment]
Nothing prevents you to copy it manually from any VS Code version into your "~/.vscode/extensions" folder.
I suggest that you remove "~/.vscode/extensions/ms-node-debug2-1.19.0" at least temporarily and see whether this makes a difference.

**Comment by felpin** [comment]
Thank you... I deleted that extension folder and got no problems anymore.

I think my [Settings Sync extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) was installing it when synchronizing. I noticed that the version I was using was 1.19.0 and it is already in 1.21.1 version.

Thank you again...

**Comment by weinand** [comment]
Glad to hear that we found the issue!
