### ISSUE TITLE
checkJs and TypeScript - bulb supplementing the undeclared used argument and type

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#44824]
When I use the non-existing `sd` argument, the following function should appear in the bulb:
"Add` sd` to the arguments of Component 'or something that gives you the option to set this argument and the type of this argument.

```
/**
 * @augments {Component<{walc: string, dekiel: string}, {}>}
 */
class Binek extends Component {
	state = {};
	render() {
		const {walc, sd} = this.props;
		return (
			<div>
			{walc}
			</div>
		)
	}
}
```

Bulb will simply add `sd: `:
```
/**
 * @augments {Component<{walc: string, dekiel: string, sd: }, {}>}
 */
```
And set cursor after "sd: " and show intelliSense for types.

Analogously for TypeScripts.

**Comment by mjbvz** [comment]
Where are you getting the lightbulb? Is it coming from an extension?

**Comment by lukaszpolowczyk** [comment]
@mjbvz Bulb is build in vscode:
![cpp-lightbulb](https://user-images.githubusercontent.com/16800535/36867072-600fa824-1d94-11e8-9fee-db2ef5675331.png)
I do not know what's going on. Is it called differently?

**Comment by mjbvz** [comment]
Sorry, I misread your original post. I thought the lightbulb was already showing up in your example. I've labeled the issue properly

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/27163 to track this upstream
