### ISSUE TITLE
Corresponding HTML end tags can be highlighted as available in Notepad++

### ISSUE THREAD

**Issue by VivekmanikandanD** [Microsoft/vscode#44822]
Corresponding HTML end tags can be highlighted as available in Notepad++
This feature will be more useful.
Right now I am pasting the html code to notepad++ and finding which of my tags are not closed

**Comment by aeschli** [comment]
@VivekmanikandanD Can you add a screenshot that illustrates what you want?

**Comment by aeschli** [comment]
Note that we already highlight the corresponding end tag in HTML (but not in PHP, that's #2915)
![image](https://user-images.githubusercontent.com/6461412/36892411-eadc1558-1e04-11e8-872d-feae76e23ec4.png)
