### ISSUE TITLE
The Python terminal is not executed in the Visual Studio Code when I launch the command with the right button.

### ISSUE THREAD

**Issue by M0rryk** [Microsoft/vscode#44823]
### Issue Type
Bug

### Description

Any script in python is not launched in the integrated terminal, in practice with the right button throwing the stript by clicking on "run python file in terminal" the function recalls the terminal but when this goes to call up the file the stripping of the "\" and therefore does not find the file and generates an error[Errno 2] No such file or directory. The following is a copy of the terminal error message

$ C: /Users/ldelv/AppData/Local/Programs/Python/Python36/python. exe c:\GIT\Security\cve-news-update\main. py
C:\Users\ldelv\AppData\Local\Programs\Python\Python\Python36\python. exe: can't open file' c: GITSecuritycve-news-updatemain. py':[Enter 2] No such file or such file
directory

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
You must be using an extension for the right click to run a python file.
