### ISSUE TITLE
Cannot click last line when scrollBeyondLastLine = false

### ISSUE THREAD

**Issue by loicwolff** [Microsoft/vscode#44826]
### Issue Type
Bug

### Description

Set `editor.scrollBeyondLastLine = false` in the settings.

## To reproduice
- Open a long file
- Scroll to the bottom
- Hover and click on the last line

## Expected
On hover, the mouse cursor should change to a caret, 
On click, the cursor is moved to the last line

## Actual
On hover, the mouse cursor is still the arrow
On click, the cursor is not moved to the last line

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.86GB (7.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Sources\cosmoz3-frontend|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|0.18.1
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.7
xml|Dot|1.9.2
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.3
LogFileHighlighter|emi|2.1.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.8.7
rest-client|hum|0.17.0
output-colorizer|IBM|0.1.2
csharpextensions|jch|1.3.0
python|ms-|2018.1.0
csharp|ms-|1.14.0
polymer-ide|pol|0.6.0
elastic|ria|0.10.1

(3 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment]
@loicwolff I cannot reproduce:

![kapture 2018-03-02 at 10 42 11](https://user-images.githubusercontent.com/5047891/36892877-74b618ea-1e06-11e8-950b-4387cb8d7343.gif)

**Comment by loicwolff** [comment]
See the screenshots below, I've been able to reproduce with an empty line at the end and a line with text. Approximately half of the last row is not clickable.

![screen](https://user-images.githubusercontent.com/20514/36933822-affdd4f4-1edf-11e8-8cc0-b6101a51ec6f.png)

![screen2](https://user-images.githubusercontent.com/20514/36933866-57f57324-1ee0-11e8-8b90-1b55252b5dae.png)

**Comment by alexandrudima** [comment]
Aha, I see. 

That is where the horizontal scrollbar would paint itself. It used to be capturing mouse events even when it was invisible. This has been incidentally fixed recently by @joaomoreno in #42801 

The fix will come with the February release and is already available on the Insiders Channel.
