### ISSUE TITLE
Export Setings

### ISSUE THREAD

**Issue by AliBedaer** [Microsoft/vscode#44825]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by tsalinger** [comment]
Please add more information on what the problem is and with which steps it can be reproduced.

**Comment by myfairsyer** [comment]
If you just want to export settings: All the settings are already saved using [setting files](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations).
In the marketplace you can find lots of [extensions](https://marketplace.visualstudio.com/search?term=settings&target=VSCode) related to VSCode's settings for tasks such as syncing and importing.
