### ISSUE TITLE
Javascript syntax highlighting fails on certain code

### ISSUE THREAD

**Issue by decentaur** [Microsoft/vscode#44820]
### Issue Type
Bug

### Description

I have the following code:

```js
if (level.length > 0) image(level[0].image, windowWidth / w[0] * w[1], windowHeight / h[0] * h[1], windowWidth / (w[0] / 2), windowHeight / (h[0] / 2));
```
```js
if (level.length > 1) image(level[1].image, windowWidth / w[0] * w[2], windowHeight / h[0] * h[2], windowWidth / (w[0] / 2), windowHeight / (h[0] / 2));
```

The syntax highlighting gets confused and starts interpreting things wrong.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics     (4 x 2196)|
|Memory (System)|6.95GB (1.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
plsql-language|xyz|1.1.2

</details>

**Comment by kieferrm** [comment]
Confirmed. The grammar interprets `/ 2), windowHeight` as the beginning of a regex.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/580 to track this upstream
