### ISSUE TITLE
Bulb with suggestions to create for used not declared variable/function/class.

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#44837]
Bulb with suggestions "Create variable/function/class in scope" for used not declared variable/function/class.

Example:

```
function x () {
	const = var1 + 3;
}
```
Should be emphasize `var1` as not exist, and in bulb should be showed few position like:
 "Create variable in scope"
 "Create variable in closure"

And then click "Create variable in scope for `var1`":

```
const var1 = ;
function x () {
	const = var1 + 3;
}
```
with cursor set `const var1 = `, so this will created somting like snippet.

Or if click "Create variable in closure for `var1`":

```
function x () {
	const var1 = ;
	const = var1 + 3;
}
```

Other example:

```
const var = fun();
```

When click "create function (...) for `fun`"

```
function fun () {
	
}
const var = fun();
```

with set cursor in body of fun.

In addition, three would like to choose "const, let, var" and arrow function, etc.

**Comment by mjbvz** [comment]
I believe this flow is redundant with `extract to constant` / `extract to function`. Writing the expression inline and then extracting seems more natural as it involves less jumping around in the code

**Comment by lukaszpolowczyk** [comment]
@mjbvz " it involves less jumping around in the code"
On the contrary! there is more jumping in the code!

Declare the function (or its content) and so it must. But you must use it in a specific place too! So it will not be avoided.
And that's why I want this function to be created in one fell swoop.

Thanks to this jumping will be less. Because you counted "jumps" resulting from the use of the proposed function. But you skipped the "jumps" that you must do anyway, but by hand!
