### ISSUE TITLE
Bulk replace for a large number of files crashes VSCode

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/vscode#44836]
### Issue Type
Bug

### Description

I'm trying to bulk replace a single line in a large number of large text files (2800 files at ~700 KB / 18000 lines each). These are automatically generated input files for simulations, so I'd rather not recreate them or edit them by hand.

The replace preview works just fine, but when I press replace, VSCode attempts to open those files and crashes after a short while. I don't care about viewing the files, I just want to replace the search results.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|Memory (System)|7.93GB (4.15GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by roblourens** [comment]
I agree, we can do better. Maybe an extra option, "replace without opening"

![image](https://user-images.githubusercontent.com/323878/37066769-c93d7752-215b-11e8-969d-95e5c1a50b34.png)

Or just a threshold where we never try to open more than 100 or so files at a time.

**Comment by AlCalzone** [comment]
> Maybe an extra option, "replace without opening"

Sounds good!

**Comment by roblourens** [comment]
This is actually fixed in 14554
