### ISSUE TITLE
Terminal forever running

### ISSUE THREAD

**Issue by Espigah** [Microsoft/vscode#44831]
### Issue Type
Bug

### Description

Run: node [FILE].js but terminal never kill the  process

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz (8 x 3093)|
|Memory (System)|7.89GB (1.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Repositories\projeto-de-vida\dev\client\dev\src\tamboro\objects\tldc|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
jslint|ajh|1.2.1
vscode-standardjs-snippets|cap|0.7.5
Gradle|caz|1.1.2
jsrefactor|cms|2.11.6
toggle-excluded-files|eam|1.6.0
gc-excelviewer|Gra|2.0.20
vscode-favorites|how|1.3.0
vscode-postfix-ts|ipa|1.6.0
sublime-babel-vscode|jos|0.2.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|1.7.2
Angular-BeastCode|Mik|5.2.15
python|ms-|2018.1.0
debugger-for-chrome|msj|4.1.0
title|nil|0.1.0
indent-rainbow|ode|0.7.2
vscode-versionlens|pfl|0.19.1
typescript-hero|rbb|2.2.0
java|red|0.20.0
vscode-uppercase|rui|1.0.1
annotator|ryu|0.11.0
partial-diff|ryu|0.5.1
terminal-tabs|Tyr|0.1.1
ionic2-snippets|uqu|0.0.4
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.2
beauty|yhp|0.0.2

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
The terminal is not meant to kill a node process, it will exit when it's finished?
