### ISSUE TITLE
Tab name

### ISSUE THREAD

**Issue by Ibrahimhammani** [Microsoft/vscode#44835]
### Issue Type
Feature Request

### Description

Hi,

thank you for the greate editor,

It would be greate if we can rename tabs without saving the content to file.

In my case I modify a lot of scripts I copy them to the editor but I don't need to save them.

Best regards

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.13.0-32-generic

**Comment by bpasero** [comment]
@Ibrahimhammani to be clear, you want to rename those things in the editor that show up as "Untitled-1", "Untitled-2" etc?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/37414

**Comment by Ibrahimhammani** [comment]
@bpasero thank you for your reply ,I've not noticied taht it's duplicated, but thats good seems like a lot of people want this feature
