### ISSUE TITLE
Misplaced end tag when wrapping multiple lines with abbreviation

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44833]
Verifying #29898

![mar-01-2018 15-08-34](https://user-images.githubusercontent.com/9205389/36848775-84fa24b6-1d62-11e8-8220-ae65c30d7192.gif)

It can be worked around by not selecting the last newline. Selecting entire lines, including the newline, seems more natural.

**Comment by ramya-rao-a** [comment]
This is not a regression, but definitely a bug that needs to be fixed. Moving to March
