### ISSUE TITLE
feature request: provide a official vscode flatpak version in the flathub

### ISSUE THREAD

**Issue by Lvaskz** [Microsoft/vscode#44841]
Hello, everyone, this app is very powerful and great and should be available for many other distributions and with real-time updates from the original developers. That is why I would like to suggest you provide a universal package for linux distributions: flatpak Here we find everything related to the type of packaging and its advantages: https://flatpak.org/
  In addition, the package can be hosted on the flathub: https://flathub.org/apps/
  There is a version of VSCODE, but I understand that it is not official and hence the request, because the updates do not arrive if they are not reported, instead if you keep your own flatpak the updates will arrive at the same time for all the packages that you maintain. Consider it, since apparently, you can install in most distributions, a single package to maintain, or you could use snap, the problem is that it is not supported by RedHat, instead flatpak does.

A new world for application developers
Cross-distro

Create one app bundle and distribute it to the entire Linux desktop market.
Stable platforms

Runtimes provide stable sets of dependencies that can be used by applications.
Consistent environments

Develop and test your application in an environment that's identical to the one users have.
Control over dependencies

Dependencies that aren't in a runtime can be bundled as part of an application. Versions of the dependencies that are used can be fixed and patched.
Easy build tools

Flatpak's build tools are simple and easy to use, and come with a full set of documentation.
Future-proof builds

Runtimes are forward compatible, irrespective of distribution changes. Flatpak applications run on new Linux distribution versions as they are released.

**Comment by tomByrer** [comment]
Dup? https://github.com/Microsoft/vscode/issues/7112

**Comment by Tyriar** [comment]
We have no plans to officially distribute via flatpak, we already have 3 distribution methods for Linux and are investing in Snap. The more there are the more maintenance burden there is on the project.
