### ISSUE TITLE
Disabled breakpoints use different shade of grey

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#44849]
The triangle is darker:

![2018-03-01_16-52-04](https://user-images.githubusercontent.com/1898161/36854339-0a9062da-1d71-11e8-87b3-41ecab991539.png)

**Comment by isidorn** [comment]
Already mentioned this to @chryw

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/45253
