### ISSUE TITLE
Should JavaScript snippets automatically be made available to other JavaScript based languages (TypeScript, JavaScript React)

### ISSUE THREAD

**Issue by michael-wolfenden** [Microsoft/vscode#4484]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new JavaScript snippet, for example: 
```json
{
    "console.log": {
        "prefix": "cl",
        "body": [
            "console.log('${1:arg}', ${1:arg});"
        ]
    }
}
```

2) If you create a new file with the language set to `JavaScript`, enter `cl` and press tab, the snippet will expand.

3) If you create a new file with the language set to `TypeScript`, the`cl` snippet is not available.

The current solution is to re-implement the snippet in all of the JavaScript based languages but that means duplicating the snippet for JavaScript, JavaScript React, TypeScript and TypeScript React. This makes it difficult to build up a large body of JavaScript snippets.

Should JavaScript snippets automatically be made available to other JavaScript based languages?

**Comment by aeschli** [comment]
While it is some work for the user to copy/paste the snippets to the other languages, it gives the user full control over what snippets show up. 
One issue I see is that you don't always want JavaScript snippets show up in TypeScript, where you rather want snippets that include types.
