### ISSUE TITLE
Provide API commands to resolve codeLens, completion items ....

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#44846]
VS Code provides commands to provide these data types. However if they need to be resolved later (for example on user action) there is no API to do so.

**Comment by jrieken** [comment]
tricky

**Comment by srivatsn** [comment]
For completeness, `DocumentLinkProvider` also has a resolve method.

**Comment by dbaeumer** [comment]
@jrieken would it be easier if the API requires that the item passed to the resolve call is `===` to the item return from provide API command. At least for the `CompletionItem` the LSP provides a data slot so that items that travel over the wire can be re-associated.

**Comment by jrieken** [comment]
> would it be easier if the API requires that the item passed to the resolve call is === to the item return from provide API command.

The implementation usually does that, e.g the [`SuggestAdapter`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L603) has a cache for those items. The tricky bit is that the lifecycle which is managed by the UI...

**Comment by jrieken** [comment]
I have pushed a change to the `vscode.executeCompletionItemProvider`-command that allows to pass an extra argument which denotes the number of items to resolve. This large numbers a slowdown is to be expected. For a sample see: https://github.com/Microsoft/vscode/blob/8973bea2ed78d82722b5f0d61c6fd201bd4c12b7/src/vs/workbench/test/electron-browser/api/extHostApiCommands.test.ts#L445

**Comment by srivatsn** [comment]
Is there going to be a way to resolve the item separate from this? This may be ok in some cases but ideally we wouldn't want to resolve completion items (especially for live share where there's already latency for those requests).

**Comment by srivatsn** [comment]
Are you planning to add this max parameter to the executeCodeLens command as well? Right now, we get Undefined as the name of codelens and so this is more important for Codelens than completion for us. Would it be possible to specify resolve all items and we can pass that if we are calling it from non-perf sensitive path. For CodeLens for eg., the indicators showing up doesn't block users and so there we could say resolve all.

**Comment by jrieken** [comment]
Yeah, I can try to squeeze that in

**Comment by jrieken** [comment]
@srivatsn I have pushed a change that allows to resolve code lenses in a similar spirit. You can pass a number, the semantics are that only so many lenses are resolved and return, e.g. no unresolved code lens is return.

**Comment by srivatsn** [comment]
Why restrict it to a certain number instead of resolving all results (with the understanding that there's a perf cost which is fine probably acceptable if it's in the background)? I don't what a reasonable number would be to pick and based on that number the experience in the editor would feel arbitrary.

**Comment by jrieken** [comment]
> I don't know what a reasonable number

I don't know either, that's why I made it a parameter 😄 The restriction is because an unresolved code lens, so one with just a range but with a command, cannot be rendered a meaningful way.

**Comment by srivatsn** [comment]
Sorry I am not following. My suggestion is to take a boolean parameter called resolveCodeLenses and [here](https://github.com/Microsoft/vscode/commit/a8839f858e6c7001262d8219da7593dd28cbdcf9#diff-c6b0dc4a544c71864461b67b0dc93d09R80) change it to `else if(resolveCodeLenses)` - would that work?

**Comment by jrieken** [comment]
Wouldn't that be the same as using `Number.MAX_VALUE` just without flexibility?

**Comment by srivatsn** [comment]
Fair enough. My initial reaction was that a Boolean would be cleaner but on further thought this is fine.

**Comment by dbaeumer** [comment]
Verified coding up a small extension. However only did for completion items.
