### ISSUE TITLE
Leave waiting for second part of a chord state after some time

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#44847]
- trigger a chord (e.g. `cmd+k`)
- go drink coffee or focus out of VS Code
- VS Code should eventually (on its own) leave this state
- The rationale is that the user will have forgotten that a chord was triggered by the time they return.

**Comment by fabiospampinato** [comment]
That's a funny rationale, another one is that if you clear the terminal immediately on <kbd>cmd+k</kbd>, and 10ms later the user completes the chord shortcut, the user could find himself with a cleared-out terminal when maybe he just wanted to toggle the sidebar.

Thinking more about this I realized that there's no way to differentiate between <kbd>cmd+k</kbd> <kbd>cmd+b</kbd> (2 independent shortcuts) and <kbd>cmd+k cmd+b</kbd> (1 chord shortcut) with time alone, so I guess this won't be a perfect solution.

Another option would be to wait until <kbd>cmd</kbd> gets released, or the chord completed, when triggering <kbd>cmd+k</kbd>.

Another option would be mind reading, but I've no idea who to implement that, yet.

What do you think is the best option here, just to keep it the way it is and leave the user with an accidentally cleared-out terminal?

**Comment by alexandrudima** [comment]
@fabiospampinato

Without any keybinding customizations, without anything to do with the terminal, if you are focused in the editor and press <kbd>cmd</kbd>+<kbd>k</kbd>, the keybinding service will set a field (state) such that it enters into chord mode and the next keypress will be interpreted as a second part of a chord. This is reflected in the status bar message:

![image](https://user-images.githubusercontent.com/5047891/36895336-d4ec3e44-1e0e-11e8-9fb0-943559b04bc9.png)

This issue I have created here is about clearing that state after an amount of time or when focus leaves VSCode.
