### ISSUE TITLE
Intellisense in JS files broken if use JSdoc types from d.ts files

### ISSUE THREAD

**Issue by StanislavKharchenko** [Microsoft/vscode#44845]
- VSCode Version: 1.20.1
- OS Version: Windows 10 Pro 2017, x64

Steps to Reproduce:

1. Create 2 files, index.js and index.d.ts
2. Define types in d.ts file (e.g. some interface);
3. Using JSDOC, intellisense works ok in the JS file with reference on t.ds;
4. Use import statement in the t.ds;
5. Intellisense for types defined in d.ts doesn't work in JS file.

Does this issue occur when all extensions are disabled?: Yes

It seems this problem was already described here https://github.com/Microsoft/vscode/issues/38980
But proposed solution can't help in current version of VS Code.

**Comment by mjbvz** [comment]
Please share your code

**Comment by mjbvz** [comment]
Answered on SO https://stackoverflow.com/questions/49051278/intellisense-for-javascript-files-in-vs-code-from-type-definitions-which-have-im/49060557#49060557

**Comment by StanislavKharchenko** [comment]
index.d.ts file:
```
import { Request } from "express";

declare interface someInterface {
    prop1: Request;
    prop2: string;
}
```

index.js file:
```
/// <reference path="index.d.ts"/>

/**
 * @type {someInterface}
 */
let customRouter;
```

So, when I'm trying to initialize 'customRouter' as object I can't see it properties from intellisense which were defined in d.ts file.

If import statement will be removed, intellisense will work.

According to answer in SO by link described above, need to export interface, and then use at in the import statement in my JS file. But, what about node, where import is currently not available?

Thank you.

**Comment by xlfsummer** [comment]
Same problem, seems **only interface** declaration could not work correctly.

.d.ts file
```javascript
declare var _variable: string

declare interface _interface{
    someProperty: string
}

declare function _function(): string

declare class _class{
    someProperty: string
}
```

.js file

![image](https://user-images.githubusercontent.com/20750969/37225100-883dfd0a-2410-11e8-8a08-b469104b429d.png)

I think it's likely to be a bug.
