### ISSUE TITLE
Confirming "don't ask me again" with moving a file doesn't move the file

### ISSUE THREAD

**Issue by individual11** [Microsoft/vscode#44854]
### Issue Type
Bug

### Description

I accidentally created a file in a folder I didn't want it in. When I did a drag/drop to move it, it confirmed with me. I checked the box to not ask again and hit "confirm" and the file didn't move. I repeated the steps multiple times with the same result (so it didn't remember not to ask me either) until I finally didn't check the box to not ask me again, clicked "confirm" and it moved fine.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.74GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.12
vscode-markdownlint|Dav|0.13.0
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
auto-close-tag|for|0.5.6
serverless-vscode|fra|1.0.0
vscode-language-babel|mgm|0.0.12
HTMLHint|mka|0.4.0
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
heroku-command|pko|0.0.8
serverless-vscode-snippets|raf|0.0.4
vscode-todo-highlight|way|0.5.11
vscode-js-console-utils|wht|0.7.0
JavaScriptSnippets|xab|1.5.0
markdown-all-in-one|yzh|1.0.5

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
@individual11 I cannot reproduce, does it reproduce all the time?

**Comment by individual11** [comment]
Missed the above comment, sorry. Yes, every single time. Can do a vid if it helps, or run some stack trace if you point me where to look.
