### ISSUE TITLE
Can't switch between SCM providers

### ISSUE THREAD

**Issue by nefalstois** [Microsoft/vscode#44853]
- VSCode Version: 1.20.1
- OS Version: Windows 7

Steps to Reproduce:

1. Install TortoiseSVN with command line tools
2. Install SVN extension
3. On SCM view click on more options, only enable this option -->
![2018-03-01_17h26_47](https://user-images.githubusercontent.com/25529992/36856728-f8dcc9a6-1d76-11e8-8083-debefba55488.png)

This is my SCM providers extensions ->
![2018-03-01_17h27_05](https://user-images.githubusercontent.com/25529992/36856771-14946ce4-1d77-11e8-8f1b-35f07545922a.png)

VSCode is detecting git and svn ->
![2018-03-01_17h28_45](https://user-images.githubusercontent.com/25529992/36856797-301c911c-1d77-11e8-8d3c-42a21d85b3ff.png)
![2018-03-01_17h29_00](https://user-images.githubusercontent.com/25529992/36856800-31218950-1d77-11e8-8421-67683c575da6.png)

¿Someone can tell me how can i switch between git and svn?

**Comment by joaomoreno** [comment]
Code doesn't have a switch anymore. They can all work simultaneously. Just open a workspace with either a Git or SVN repository within and they will appear in the SCM view.
