### ISSUE TITLE
Duplicate items in contextmenu (TypeScript)

### ISSUE THREAD

**Issue by blendsdk** [Microsoft/vscode#44850]
- VSCode Version: 1.20.1
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Create a TypeScript project
2. Create an abstract class
3. Create a class that inherits from the abstract class above.
3.1 The IDE should provide you with a hint
4. Click on the hint and observe the context menu
[Please see screenshot here](https://truesoftware.net/blend/contextmenu.png)

**Comment by mjbvz** [comment]
Duplicate of #43181
