### ISSUE TITLE
Open editors: mulit drag and drop rearenges dranged items

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#44852]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

Want to drag'n'drop three files:

1) xxx.ts
2) xxx.html
3) xxx.css

![explorer - sorting order](https://user-images.githubusercontent.com/24613274/36855952-7d6d2782-1d7d-11e8-9fdb-ce732549a353.gif)

... after being drag'n'droped - the order is:

1) xxx.css
2) xxx.html
3) xxx.ts

So, it makes the files be sorted by their names.
Should be fixed.

**Comment by isidorn** [comment]
Good job bot!

**Comment by user3323** [comment]
@isidorn 

I don't get it. Do I need to add one more clause or it's already exists?

Cause, I don't see this type of bug out there.

**Comment by isidorn** [comment]
My mistake, this is an issue with dnd funcionality in the open editors view

**Comment by bpasero** [comment]
@isidorn isn't the fix quite simple, in [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/openEditorsView.ts#L582) just increment the index you are dropping to by 1 for each moved editor?

E.g. 

```typescript
this.transfer.getData(OpenEditor.prototype).forEach((oe, offset) =>
	this.editorGroupService.moveEditor(oe.editor, model.positionOfGroup(oe.group), positionOfTargetGroup, { index: index + offset, preserveFocus: true }));
```

**Comment by isidorn** [comment]
@bpasero you are correct, thanks for the fix.
I tried to fix it in a wrong way: by changing the order how they are written to the drag data, your sollution is correct and elegant.

**Comment by bpasero** [comment]
@isidorn awesome
