### ISSUE TITLE
Source Control - GIT 5K from atom 

### ISSUE THREAD

**Issue by andrewjholdun** [Microsoft/vscode#44859]
I installed vscode and am it is pulling in atom git package totaling 5k. 
I see I have options under git but am not sure what one to use. 
It's severe enough to make me not want to use vscode.
Any way to stop the madness?

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.16
vscode-eslint|dba|1.4.7
auto-close-tag|for|0.5.6
LiveServer|rit|3.2.1
vscode-icons|rob|7.20.0
open-in-browser|tec|1.1.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.open vscode
2.git loads to 5k automatically
<img width="1308" alt="screen shot 2018-03-01 at 10 41 27 am" src="https://user-images.githubusercontent.com/672396/36863122-a8fec256-1d3d-11e8-93bb-7436fc31131a.png">

<img width="1308" alt="screen shot 2018-03-01 at 10 41 27 am" src="https://user-images.githubusercontent.com/672396/36863192-deef76c6-1d3d-11e8-9dc1-e8694cd5b0cd.png">

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Add `.atom` to your [`.gitignore` file](https://git-scm.com/docs/gitignore).
