### ISSUE TITLE
[snippets] Allow snippets where the prefix ends with =

### ISSUE THREAD

**Issue by michael-wolfenden** [Microsoft/vscode#4485]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. Create the JavaScript snippets below

```json
    "var statement": {
        "prefix": "v",
        "body": [
            "var ${1:name}"
        ]
    },
    "var assignment": {
        "prefix": "v=",
        "body": [
            "var ${1:name} = ${2:value}"
        ]
    }
```

2. Create a new file with the language set to `JavaScript`

3. Type `v` then TAB and note that the `var statement` snippet expands

3. Type `v=` then TAB and note that the `var assignment` snippet DOES NOT expand

**Comment by enjoylife** [comment]
Thanks for bug fix.. :clap:
