### ISSUE TITLE
Keyboard focus trap in notifications center

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44857]
mac/insiders 9a04587cc6b42c332609a08bfd7e2dbeac592c21

Repro:

1. Trigger a notification, eg. `vscode.window.showErrorMessage('abc', 'a', 'b');`
2. shift+tab multiple times, focus is toggled between the notification and the first button.

If this was intentional because you can press esc, it's a bit weird that it allows you to continue beyond the end of the notifications.

**Comment by bpasero** [comment]
@Tyriar can you attach a video what you mean? I think I know what you mean, but want to make sure.

**Comment by Tyriar** [comment]
![kapture 2018-03-02 at 7 13 22](https://user-images.githubusercontent.com/2193314/36905852-3c64a28a-1de9-11e8-8ef4-e262caf2ab80.gif)

**Comment by bpasero** [comment]
@joaomoreno maybe a candidate, I think this is from your recent changes.

**Comment by joaomoreno** [comment]
Yeah that's pretty rough. Promoting as a candidate. cc @sandy081

**Comment by joaomoreno** [comment]
@bpasero Can you verify in dev?

**Comment by bpasero** [comment]
@joaomoreno yeah seems better now 👍
