### ISSUE TITLE
Vscode terminal graphic bugs 

### ISSUE THREAD

**Issue by anhmiuhv** [Microsoft/vscode#44855]
The terminal tab display color tiles. 
Like this https://imgur.com/a/csg92
Some time this also happen to the sidebar preview.

- VSCode Version: 1.20.1
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Ubuntu 16.04 LTS 
- Hardware : Dell Precision 5520

Steps to Reproduce:

1. Open the vscode
2. Sleep the laptop
3. Wake the laptop

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is an issue with Chromium, nothing we can do unfortunately.
