### ISSUE TITLE
Cursor not visible when status bar has line break

### ISSUE THREAD

**Issue by krokofant** [Microsoft/vscode#44863]
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. Use powershell
2. Use a theme with a status bar which takes up the whole line (examples in https://github.com/JanJoris/oh-my-posh)

With theme with line break:
![image](https://user-images.githubusercontent.com/5908498/36868278-27f3b148-1d98-11e8-8530-8670062ba468.png)
![image](https://user-images.githubusercontent.com/5908498/36868300-41854e5a-1d98-11e8-8899-e36fbe3669bc.png)

With theme without line break:
![image](https://user-images.githubusercontent.com/5908498/36868329-4fa00c3c-1d98-11e8-884c-67939ec24741.png)

**Comment by Tyriar** [comment]
I think this is fine now, I use a `\n` in my prompt and it works.

**Comment by Tyriar** [comment]
It could also be related to winpty as it's Windows which in that case is tracked in https://github.com/Microsoft/vscode/issues/45693
