### ISSUE TITLE
Drag to expand cursor shows but click and dragging has no effect

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44866]
Issue Type: <b>Bug</b>

**Steps to reproduce**

1. For a drag to expand panel (split editors for example)
2. Move slowly cursor until it just starts showing the drag cursor
3. Click to drag.

**Bug**
Nothing happens. Moving the cursor closer to the draggable edge allows dragging 

![mar-01-2018 13-09-02](https://user-images.githubusercontent.com/12821956/36869852-0bab9eba-1d52-11e8-88f0-12f21b1a0943.gif)

/cc @chrisdias 

VS Code version: Code - Insiders 1.21.0-insider (9a04587cc6b42c332609a08bfd7e2dbeac592c21, 2018-03-01T06:39:57.509Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_5973426|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by bpasero** [comment]
@isidorn I can reproduce when I start to drag to the far right of the sidebar-sash and it looks like the centered-editor-layout sash is actually in the editor even though centered editor mode is not enabled. I think the sash should be hidden completely unless centered editor mode is turned on.

![image](https://user-images.githubusercontent.com/900690/36885687-d379258e-1de8-11e8-89d2-b5edb1993893.png)

**Comment by mjbvz** [comment]
Tested in latest master. Split editors seem fixed but I still see this on the boundary between the editor and the sidebar

**Comment by isidorn** [comment]
@mjbvz good catch
@bpasero you were correct, they need to be hidden initialy. Somehow this slipped through my fingers.

**Comment by bpasero** [comment]
@isidorn thanks, I assume you also hide when leaving "Centered Editor" layout again?

**Comment by isidorn** [comment]
@bpasero yes

**Comment by isidorn** [comment]
@bpasero can you please verify?
