### ISSUE TITLE
xUnit warnings do not show up in problem matcher

### ISSUE THREAD

**Issue by alexriedl** [Microsoft/vscode#44868]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. C# project with xUnit package
2. Use $msCompile problem matcher in build task
3. Have a warning in one of the tests
4. Problem matcher does not grab the warning

Example class that would cause a warning:
```
namespace Tests
{
  public class MyTests
  {
    [Fact]
    public void Good()
    {
    }

    public void Warning() // <-- Warning xUnit1013: Public method 'Warning' on test class 'MyTests' should be marked as a fact.
    {
    }
  }
}
```

Possible fix:
Update mscompile regex from
```
/^(?:\s+\d+\>)?([^\s].*)\((\d+|\d+,\d+|\d+,\d+,\d+,\d+)\)\s*:\s+(error|warning|info)\s+(\w{1,2}\d+)\s*:\s*(.*)$/
```
to
```
/^(?:\s+\d+\>)?([^\s].*)\((\d+|\d+,\d+|\d+,\d+,\d+,\d+)\)\s*:\s+(error|warning|info)\s+(\w{1,5}\d+)\s*:\s*(.*)$/
```

The major difference between the output is the code. xUnit uses 5 characters instead of 2

**Comment by dbaeumer** [comment]
I would rather argue that there should be a special problem matcher for xUnit because there might be other differences. Such a problem matcher could be contributed by an extension.
