### ISSUE TITLE
Redo stack smaller than Undo stack?

### ISSUE THREAD

**Issue by MZdlynch** [Microsoft/vscode#44865]
After doing a bulk undo (holding Cmd+Z for a bit) I saw where I wanted to end up and stopped, tried to go "forward" with Redo, but it only went so far ahead and now changes are lost.

- VSCode Version: 1.20.1
- OS Version: OS X 10.12.1

Steps to Reproduce:

1. In a file with lots of edits, hold down Command+Z (Undo)
2. After a while, "reverse" and hold Command+Shift+Z (Redo) - it stops and doesn't go back to it's previous state.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
@MZdlynch  I could not reproduce. Are there perhaps more steps to it?
