### ISSUE TITLE
Autosave is not turning off

### ISSUE THREAD

**Issue by cacothi** [Microsoft/vscode#44864]
- OS Version: Windows 10
- VSCode:
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

# Issue
The Auto Save is saving the files even if it't not checked (and also not set on the user settings). I've noticed that as I'm developing an Angular Project and the file watch is running, and the browser kept refreshing even if I haven't saved the file. 

I could also noticed that behavior when I was on the browser and wasn't even editing the file, so somehow the vscode saved a file whic had triggered the auto-watch to refresh the browser.

In addition I noticed that on my workmates VS Code as well. I have turned off all the extensions and it happened again.

# Steps to Reproduce:

1. File > Auto Save (make sure it's not checked)
2. Change a file and alt+tab or change file tab or even wait a little bit.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@cacothi can you share your settings file (both User and Workspace if any)?

**Comment by cacothi** [comment]
Hi @bpasero , 

Please find below both settings:

## User Settings
```json
// Place your settings in this file to overwrite the default settings
{
    "editor.insertSpaces": false,
    "vsicons.projectDetection.autoReload": true,
    "terminal.external.windowsExec": "C:\\Users\\thiago.e.bernardes\\AppData\\Local\\Programs\\Git\\usr\\bin\\bash.exe",
    "terminal.integrated.shell.windows": "C:\\Users\\thiago.e.bernardes\\AppData\\Local\\Programs\\Git\\usr\\bin\\bash.exe",
    "editor.minimap.enabled": false,
    "workbench.panel.location": "right",
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressUpdateNotice": false,
        "suppressWelcomeNotice": true
    },
    "git.ignoreMissingGitWarning": true,
    "workbench.editor.tabSizing": "shrink",
    "window.zoomLevel": 0,
    "workbench.iconTheme": "vscode-icons",
    "files.autoSave": "off",
    "editor.formatOnSave": false
}
```

## Workspace Settings 
```json
{
}
```

**Comment by bpasero** [comment]
@cacothi yeah so the setting is correct, auto save is turned off. Maybe you have an extension installed that saves?

Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by cacothi** [comment]
@bpasero yeah, prior to open the issue, I did this test as per the post template suggested. So even with the Extensions Disabled I have ran into this issue.

I´m trying to find a free tool to record the screen and provide to you guys, do you have any suggestion?
I believe that would be better to give you an idea what's been happening.

Kind Regards,

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
