### ISSUE TITLE
Moving up/down follows neither visual or actual column now

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44878]
Issue: https://github.com/Microsoft/vscode/issues/22717
PR: https://github.com/Microsoft/vscode/pull/44259

The PR does not fix the issue and introduced more issues.

Repro

Have the following text:

```
一二三四五六七八九十
	一二12345678901234567890 // tab in beginning
一二三四五六七八九十
1234567890123456789
```

- Set font to `Inconsolata`
- Set `tabWidth` to 4
- Put cursor in last line after `1234. Now status bar col shows `5`
- Up arrow
- Now cursor is after `一二三四` and status bar col shows `9`
- 🐛 The cursor is **NOT** visually aligned with previous col position
  - If it works correctly, cursor should be after `一二`
- Regardless, you go up again
- Now cursor is after `	一二1` and status bar col shows `10`
- 🐛 The cursor is **NOT** visually aligned and **NOT** column-wise aligned with previous col position. 
  - If it's visually aligned moving, you should end up after `	一二` since 4x Chinese char are 8 spaces, and 1x tab + 2x Chinese char are also 8 spaces
  - If it's column aligned moving, you should end up after the initial tab since you have 4x Chinese char and `tabWidth` is 4.

**Comment by alexandrudima** [comment]
@octref Thank you for verifying, but I believe you have attempted to verify in a build that did not contain the fix (i.e. the behaviour you describe sounds a lot like what is on stable):

![kapture 2018-03-02 at 9 32 29](https://user-images.githubusercontent.com/5047891/36890024-b1a55c2a-1dfc-11e8-9512-22db1ec556c8.gif)

**Comment by octref** [comment]
@alexandrudima I verified by building on commit ba38492bfd5483375dddcce289fffd6060536e69 which has your fix 13 hours ago.

**Comment by alexandrudima** [comment]
@octref Hmm...
What am I doing differently? Can you reproduce in today's insiders ?

**Comment by octref** [comment]
And on the freshly built insiders too with d7dca142ad6051e6b1c7397ea73221feb0160f21

![edit](https://user-images.githubusercontent.com/4033249/36890441-b435895a-1db2-11e8-81ee-4e63acb57f91.gif)

**Comment by alexandrudima** [comment]
We chatted and the issue turned out to be with the vim extension.

**Comment by octref** [comment]
@rebornix Think we should let VSCodeVim know so the new release wouldn't break for Chinese/Japanese Vim users.

**Comment by octref** [comment]
This is working correctly in VS Code. Vim issue is tracked in #44958.
