### ISSUE TITLE
Json formatting can cause selection

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44870]
Issue Type: <b>Bug</b>

**Steps to reproduce**

1. For the json:

```
[
    {},{
    }
]
```

2. Postion cusrsor between the `{},{`, at the `|`:

```json
[
    {},|{
    }
]
```

3. Run format

**Bug**
A new selection is created

<img width="162" alt="screen shot 2018-03-01 at 2 00 10 pm" src="https://user-images.githubusercontent.com/12821956/36872074-e95c9862-1d58-11e8-8854-a490ea20d0f1.png">

VS Code version: Code - Insiders 1.21.0-insider (9a04587cc6b42c332609a08bfd7e2dbeac592c21, 2018-03-01T06:39:57.509Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
color-info|bie|0.5.0
emojisense|bie|0.4.0
lit-html|bie|1.2.0
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-mermaid|bie|0.1.1
markdown-preview-github-styles|bie|0.1.0
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.28
vscode-ts-tslintaa|eg2|0.0.1
rest-client|hum|0.17.0
vscode-styled-components|jpo|0.0.16
graphql-for-vscode|kum|1.9.0
mssql|ms-|1.3.0
python|ms-|2018.1.0
azure-account|ms-|0.3.1
csharp|ms-|1.14.0
vsliveshare|ms-|0.1.0-preview.251
debugger-for-chrome|msj|4.1.0
angular2-inline|nat|0.0.17
vscode-code-outline|pat|0.0.13
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.2

(16 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by aeschli** [comment]
The formatter does an insert edit at the cursor location.
