### ISSUE TITLE
VS Code is incorrectly rendering text with decorations after the lines are deleted

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#44872]
- VSCode Version: 1.21.0 Insiders
- OS Version: Windows

Steps to Reproduce:

1. Install the C++ extension.
2. Use code like
```
int main()
{
#ifdef foo
text should appear gray here
#endif
}
```
3. Select the entire main method and start typing something else.

Bug: The new code is gray even though the lines are deleted. VS code appears to not handle the case where decorations are set on lines but the lines are removed. Our code eventually sends new text decorations but it takes a while to process.

![image](https://user-images.githubusercontent.com/19859882/36872633-bb438da8-1d5a-11e8-9fc3-41bc7126b2ea.png)

**Comment by alexandrudima** [comment]
@sean-mcmanus 

You can control the behaviour of a text editor decoration via `DecorationRenderOptions.rangeBehavior` when creating it, which describes how the decoration should grow when inserting text at the edges of the decoration.

To be able to reproduce, can you please create a minimal code snippet which reproduces the problem for you. Like e.g. in https://github.com/Microsoft/vscode/issues/34004 , or in https://github.com/Microsoft/vscode/issues/37401

**Comment by sean-mcmanus** [comment]
Thanks a lot for informing us about rangeBehavior. We should've probably noticed that before. Yeah, setting the setting to ClosedOpen appears to fix the issue for us exactly how we want.
