### ISSUE TITLE
tsd and typings different?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#4487]
- VSCode Version: 0.10.11 stable, 0.10.12 alpha
- OS Version:Windows 8

Steps to Reproduce:

1. Go through the Node.js runtime walkthrough (/docs/runtimes/nodejs.md) to "adding a jsconfig.json file" step.
2. After adding jsconfig.json and restarting VS Code, try to get IntelliSense on `routes`. 

No Express.Router specific IntelliSense comes up.  This should be provided by:
    var routes = require('./routes/index');

This was initially reported by a customer through DocFeedback verbatim.

**Comment by egamma** [comment]
This works when using `tsd install node express`. It doesn't work when using `typings --ambient`.

We should mention this in the docs and describe the work around.

![image](https://cloud.githubusercontent.com/assets/172399/13912155/5f724622-ef3a-11e5-9572-dc968c0b6518.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-docs#241

**Comment by egamma** [comment]
@jrieken we can fix the docs and document the work around, but we should understand the reason. Can you look into this.

**Comment by jrieken** [comment]
yeah, I'll take a look and see what's the difference between tsd and typings

**Comment by jrieken** [comment]
@gregvanl @egamma difference is that `tsd` installs dependencies recursively, that is for _express_ `serve-static` and `express-serve-static-core`. Once I run the `typing i --ambient` command for them things work.

![screen shot 2016-03-21 at 11 32 12](https://cloud.githubusercontent.com/assets/1794099/13916059/94100068-ef58-11e5-9d22-d89437db1c38.png)

**Comment by jrieken** [comment]
this is the call to rule them all: ` typings install node express serve-static express-serve-static-core --ambient`
