### ISSUE TITLE
"go to definition" can not work on relative import

### ISSUE THREAD

**Issue by zjh1943** [Microsoft/vscode#44886]
- VSCode Version: 1.20.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/2500778/36882629-f460b970-1e0f-11e8-8f45-2983e5b26ff0.png)

As mentioned above, I have some files in folder `auth`. I'm editing file `auth/index.jsx`, the file content is above. 

When I cmd+click the the text `./authed_route` to go to definition of `authed_route.jsx`, it works well. The same goes with `auth.jsx`.
When I cmd+click the other imports in this file, it does not jump to the target file. Accurately, when cmd+mouseover these file names, it does not highlight.

There are lots of problems like this in my workspace.
My `jsconfig.js` is blow. Operation of `go to definition` on alias path works well.

```
{
  "compilerOptions": {
    "jsx": "react",
    "target": "es6",
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./",
    "paths": {
      "components_styles/*": ["./src/styles/*"],
      "components_scripts/*": ["./src/scripts/*"],
      "components_images/*": ["./src/images/*"],
      "components_svg_icons/*": ["./src/svg_icons/*"]
    }
  },
  "exclude": ["node_modules"]
}
```
 

Does this issue occur when all extensions are disabled?: 
I can not start vscode with command `code --disable-extensions`. It said `command not found: code`.

**Comment by mjbvz** [comment]
Can you try adding `"module": "commonjs"` to your `jsconfig` `"compilerOptions"`

**Comment by zjh1943** [comment]
@mjbvz thx for you help. But it does not work.

**Comment by mjbvz** [comment]
I can't reproduce this using your `jsconfig` in a simple setup. `"module": "commonjs"` fixes the problem for me

Can you please share a minimal project that demonstrates this problem
