### ISSUE TITLE
put locale:"zh-CN" in locale.json   run ./scripts/code.sh but result is software‘s menu not the Chinese language

### ISSUE THREAD

**Issue by unsilence** [Microsoft/vscode#44880]
put locale:"zh-CN" in locale.json   run ./scripts/code.sh but result is software‘s menu not the Chinese language

run ./scripts/code.sh --locale=zh-cn 
The result is the same.

**Comment by sandy081** [comment]
VS Code running from dev has not localization support. It comes only with built/shipped VS Code.
