### ISSUE TITLE
unsupported encoding:GB 2312

### ISSUE THREAD

**Issue by janvie** [Microsoft/vscode#44888]
### Issue Type
Bug

### Description

shift+command+F to search a key(eg: "onCreate") in my workspace.
alert a tips:unsupported encoding:GB 2312

PS: my workspace encoding is GB 2312, because of the encoding of all files is GB 2312.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-database|baj|1.5.0
svn-scm|joh|1.22.0
vscode-icon-theme|jtl|1.6.1
changeEncode|lan|0.0.8
Go|luk|0.6.77
vscode-clang|mit|0.2.2
mssql|ms-|1.3.0
python|ms-|2018.1.0
cpptools|ms-|0.15.0
debugger-for-chrome|msj|4.1.0
vim|vsc|0.11.0

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
This is not a standard encoding and we don't support it.
