### ISSUE TITLE
MSTest UnitTest file has "error" marks on testclass and method

### ISSUE THREAD

**Issue by jrbobc** [Microsoft/vscode#44883]
### Issue Type
Bug

### Description

From the command line create a unit test project with "dotnet new mstest".
Open the project folder, go to the UnitTest1.cs file that is auto generated.
See the red squiggles.

https://github.com/jrbobc/mstest-src

The cs file, and csproj file.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2820  @ 2.13GHz (2 x 2132)|
|Load (avg)|1, 1, 1|
|Memory (System)|3.68GB (0.15GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.28
mssql|ms-|1.3.0
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.1.0

</details>
Reproduces only with extensions
![image](https://user-images.githubusercontent.com/22580656/36880371-ec81caa0-1d8d-11e8-8566-563c025f0c1b.png)

**Comment by tsalinger** [comment]
This was moved to the [c# extension repository](https://github.com/OmniSharp/omnisharp-vscode/issues/2083).
