### ISSUE TITLE
Underscore not showing with suggestion when object have underscore in name 

### ISSUE THREAD

**Issue by BlackTango** [Microsoft/vscode#44882]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. have an object property name with under score "_"
2. type the object property name.

![screenshot from 2018-03-01 21-08-21](https://user-images.githubusercontent.com/15683321/36880111-06ffc07e-1d95-11e8-99c5-3264845dd97c.png)

the first suggestion have underscore, the second don't.  

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
I cannot reproduce. Do you have special settings for the suggestion font size et al?

<img width="479" alt="screen shot 2018-03-02 at 09 25 42" src="https://user-images.githubusercontent.com/1794099/36889770-b7f9f0dc-1dfb-11e8-8b5b-89816834c742.png">
