### ISSUE TITLE
 Mouse long copy of the information, a little move to move a lot of distance, the user experience is very poor

### ISSUE THREAD

**Issue by scarqin** [Microsoft/vscode#44884]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
auto-close-tag|for|0.5.6
beautify|Hoo|1.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
cpptools|ms-|0.15.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by tsalinger** [comment]
Does this occur when all extensions are disabled? (Go to the extensions tab (CTRL+SHIFT+X) click on `...` in the upper right and select `Disable all installed extensions`)

Please also add the exact steps required to reproduce this issue.

**Comment by scarqin** [comment]
I updated today,seems the problem is solved,thanks a lot
