### ISSUE TITLE
Lack of options when attaching to process?

### ISSUE THREAD

**Issue by puchodr** [Microsoft/vscode#44887]
In comparison to the options under a Launch configuration, Attach barely has anything useful. You can't change the externalConsole settings, you can pass gdb parameters on startup. Is there any particular reason why the Attach configuration options are so limited. If not, when do you guys plan on implementing the feature? 

- VSCode Version: 1.20
- OS Version: Ubuntu 14.10

**Comment by weinand** [comment]
Since Attach doesn't **launch** anything, it does not make any sense to be able to specify a "console" (which would be only used for a launch).
In the "attach" case the program was already launched somewhere and the debugger only needs to attach it.
