### ISSUE TITLE
quickpick should have the ability to select multiple items

### ISSUE THREAD

**Issue by mark-keaton** [Microsoft/vscode#44891]
Feature request for extension authoring:
showQuickPick could return an array of selected items. (Thenable<string | undefined>[])

It could use the traditional hotkeys to select.
#
Windows: 
Shift+Click for a range
Ctrl+Click for multi-select

Mac:
Shift+Click for a range
Cmd+Click for multi-select.

**Comment by chrmarti** [comment]
/duplicate #45589

This will be available in the upcoming VS Code release 1.22 as part of the work being done for #45589.
