### ISSUE TITLE
terminal screen is cut when window resize

### ISSUE THREAD

**Issue by Yang09701194** [Microsoft/vscode#44894]
### Issue Type
Bug

### Description

1. open the terminal
2. use Win+Left/Right to resize window
3. the termainal screen word is cut and never restore

![vscodeterminalscreencut](https://user-images.githubusercontent.com/23180780/36886981-ea904964-1e29-11e8-9f41-58d492fe3130.gif)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.77
highlight-words|rsb|0.0.7

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
Nothing we can do about this atm as it's how https://github.com/rprichard/winpty works
