### ISSUE TITLE
Explorer text color error

### ISSUE THREAD

**Issue by Houfeng** [Microsoft/vscode#4489]
- VSCode Version: 0.10.11
- OS Version: osx 10.11.13

Steps to Reproduce:

1. Open a file that already exists
2. Write some content
3. Rename this file in the left Explorer
4. Click "don't save"  in the pop-up dialog

Repeat several times

**Comment by bpasero** [comment]
@Houfeng can you attach a screenshot of what happens?

**Comment by Houfeng** [comment]
![Uploading error.png…]()
Repeated to a file rename, it will appear this problem

**Comment by Houfeng** [comment]
@bpasero 
Repeated to a file rename, it will appear this problem
<img width="317" alt="error" src="https://cloud.githubusercontent.com/assets/1432335/13918256/faac582e-efa0-11e5-8b2a-fa73adcc1dca.png">

**Comment by bpasero** [comment]
Ok this has been fixed for March!
