### ISSUE TITLE
JSX Indent wrong when use className

### ISSUE THREAD

**Issue by izcream** [Microsoft/vscode#44893]
- VSCode Version: 1.20.1
- OS Version: MacOs Sierra(10.13.3)

I have problem when use JSX with className. It's not indent when im press enter.

This example screentshot in my problem.

![mar-02-2018 13-18-20](https://user-images.githubusercontent.com/10282500/36885964-95b60de6-1e1c-11e8-983e-ed3b8877db93.gif)

How do i solve it?. 
Thanks

**Comment by usernamehw** [comment]
```json
"emmet.preferences": {
    "format.forceIndentationForTags": [
        "body",
        "div",
    ]
},
```

**Comment by tsalinger** [comment]
@izcream Does @usernamehw's solution work for you?

**Comment by izcream** [comment]
awesome. Thanks @usernamehw
