### ISSUE TITLE
选中打开桌面中的文件夹，总是会打开桌面。

### ISSUE THREAD

**Issue by aKaigege** [Microsoft/vscode#44892]
### Issue Type
Bug

### Description

选中打开桌面中的文件夹，总是会打开桌面。

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|Load (avg)|3, 5, 5|
|Memory (System)|8.00GB (1.70GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
EditorConfig|Edi|0.12.1
beautify|Hoo|1.3.0
html-snippets|abu|0.2.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.16
vscode-eslint|dba|1.4.7
vscode-atom-javascript-snippet|glu|0.2.1
vue-snippets|hol|0.1.5
docthis|joe|0.6.0
Go|luk|0.6.77
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
view-in-browser|qin|0.0.5
vscode-icons|rob|7.20.0
language-stylus|sys|1.9.1
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by itay-grudev** [comment]
You'll need to add better explanation and steps on how to reproduce the problem. Your description is extremely vague.
