### ISSUE TITLE
Markdown AutoParse Content

### ISSUE THREAD

**Issue by sulkhanp** [Microsoft/vscode#44896]
I hope it's possible to implement this feature. It's supported by Typora; the content is automatically parsed to MD as you write. 
For clarity:
https://typora.io/img/beta.mov

**Comment by mjbvz** [comment]
I feel this feature is out of scope. Typora comes at the problem from the content writer's perspective, whereas vscode is much for programmers. Anything that hides the underlying code (the actual markdown) would not be a good fit IMO
