### ISSUE TITLE
File commands have wrong arguments (e.g. Revert File)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44895]
Steps to Reproduce:

1. open a dirty file
2. add a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L244)
2. select File > Revert File
3. see how the second argument is typed as a `URI` but actually is not

@isidorn I suggest you make a pass over the file commands, there are probably more cases. I only noticed this issue because I wanted to revert a file and that failed and the error message was not bubbling up because the error message assumes the second argument is a URI.

I guess this would also happen if running a command via command palette.

**Comment by bpasero** [comment]
@isidorn actually it looks like you already fixed this issue sort of, I can no longer reproduce the error case. However, the command is still typed such as the second argument would be a URI which is dangerous because in this case where I run it from the menu the second argument is something else:

![image](https://user-images.githubusercontent.com/900690/36887246-90cbae48-1df0-11e8-8a83-4fb2d13b243d.png)

**Comment by bpasero** [comment]
@isidorn nicer than `{}` is to just write `object` as TypeScript type.

**Comment by isidorn** [comment]
Nice idea, fixed via 15e754ec3e
