### ISSUE TITLE
Investigate to increase the stacktrace frame limit

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44899]
As outlined in https://github.com/v8/v8/wiki/Stack-Trace-API

Thread: https://groups.google.com/forum/#!topic/v8-users/JsG6PgAuL0U

**Comment by bpasero** [comment]
I pushed this for the renderer and the extension host (100 instead of 10 frames). Let's see how it goes and then decide if we want to turn this on in more processes.

**Comment by rebornix** [comment]
@bpasero can you provide more info about how to verify this?

**Comment by bpasero** [comment]
@rebornix error telemetry, I would say:

1.21.1:

![image](https://user-images.githubusercontent.com/900690/38160077-4519f3be-34b7-11e8-85b0-39c26158bad3.png)

1.22.0:

![image](https://user-images.githubusercontent.com/900690/38160078-522260fa-34b7-11e8-9908-28e5da93a422.png)
