### ISSUE TITLE
.deb package cannot be authenticated

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44898]
Issue Type: <b>Bug</b>

Todays update:

```
~$ sudo apt-get install code-insiders
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  code-insiders
1 upgraded, 0 newly installed, 0 to remove and 387 not upgraded.
Need to get 44.7 MB of archives.
After this operation, 108 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  code-insiders
Install these packages without verification? [y/N]
```

VS Code version: Code - Insiders 1.21.0-insider (d7dca142ad6051e6b1c7397ea73221feb0160f21, 2018-03-02T06:16:11.117Z)
OS version: Linux x64 3.13.0-108-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2194)|
|Load (avg)|0, 0, 0|
|Memory (System)|3.86GB (1.38GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces without extensions

**Comment by Tyriar** [comment]
Works fine for me, did you run `sudo apt-get update` and install the key first?

**Comment by chrmarti** [comment]
Another `apt-get update` now fixed it. I had that run before, so I guess the repository's index (or what holds the checksums) must have updated since. Closing.
