### ISSUE TITLE
Default icons for built in extensions

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#44907]
- Use the following for language basics extensions

![image](https://user-images.githubusercontent.com/10746682/36893319-df87e378-1e07-11e8-8006-d25e301cc84d.png)

- Use the normal default otherwise

![image](https://user-images.githubusercontent.com/10746682/36893328-ebb6acb0-1e07-11e8-9cd7-b3d90d501801.png)

**Comment by joaomoreno** [comment]
Verified in dev.
