### ISSUE TITLE
Breakpoint not hit when debugging in WSL

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#44906]
OS: Windows

Simple node app
```
console.log('Hello World');
```
set break point on line 1
debug in WSL

Observe: breakpoint not hit.

**Comment by tan-90** [comment]
This still doesn't work and there's nothing about a possible fix?

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
