### ISSUE TITLE
vscode error warning on Django development

### ISSUE THREAD

**Issue by bodii** [Microsoft/vscode#44900]
- VSCode Version: 1.20.1
- OS Version: win7 and Ubuntu 17.10

Steps to Reproduce:

1.  I use Python to develop the web, the framework is Django (version 2.0.2). When editing code, when introduced into Django class library vscode reported error;

2. In fact, vscode's friendliness to Python support, Flask and Django's class libraries and views (html) templates is less than the one I used when developing the web. I really hope vscode can support Python code development work, which is very useful for Python development. Thank you!

3. Pylint (version 1.8).

![vscode_error](https://user-images.githubusercontent.com/17775161/36890029-637aade4-1e37-11e8-8efb-c5e17854f1de.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by tsalinger** [comment]
Moved to [python extension repo](https://github.com/Microsoft/vscode-python/issues/933).

**Comment by bodii** [comment]
1. I uninstalled Pylint and reinstalled it. (Not good at this time, probably for this reason)
2. Again in the file -> preferences -> settings, will be re-set python.pythonpath (at this time is not good)
3. Also installed a Djaneiro - Django Snippets extension (actually good at this time, but may not be credit for this extension, because I later uninstall vscode still did not report the error before)

**Comment by tsalinger** [comment]
Please continue this discussion in the newly created [issue](https://github.com/Microsoft/vscode-python/issues/933).
