### ISSUE TITLE
Center panel with centered editor

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#44903]
Issue Type: <b>Feature Request</b>

- maximize window
- change to centered mode
- hide sidebar
- show panel
- the editor now is easy to read, but it is awkward that I have to move my eyes to the left when I want to type in the terminal.

It would be great if at least the terminal would center itself in alignment with the editor.

VS Code version: Code - Insiders 1.21.0-insider (d7dca142ad6051e6b1c7397ea73221feb0160f21, 2018-03-02T06:08:36.701Z)
OS version: Darwin x64 16.7.0

**Comment by isidorn** [comment]
This is a fair feature request, let's keep it open and see if it generates some traction among users.
Would you expect all panels to be centered or just the terminal? I would expect all

**Comment by chrmarti** [comment]
I agree, all would make sense, the terminal maybe the most important.

**Comment by Tyriar** [comment]
This sort of goes against splitting that was just added; do you center if the user has 3 splits? Or if the user is running commands that generate very long output, like printing file links?. Messing with the terminal layout is asking for trouble imo as modifying dimensions of the terminal can change the content.

**Comment by chrmarti** [comment]
The editor can split too, but centered layout is still useful. Maybe it should be the panel area that centers as @isidorn suggests.

**Comment by Tyriar** [comment]
I don't use zen mode or this centered layout so I'm just guessing, but I would think that users would have the panel hidden when these are active if they want to avoid clutter. Forcing the terminal to size down will mess up the wrapping and cut off output on Windows (and mac/linux until we get https://github.com/Microsoft/vscode/issues/23688) and when the terminal is narrow it's significantly harder to use imo.

**Comment by octref** [comment]
I agree Panel should not be centered.

**Comment by forrestthewoods** [comment]
I don't understand this request. I think I might want the opposite? 

What I want is a perfectly centered file view and a right aligned terminal. Right now I have the **super** annoying issue of working primarily with my desired centered file view. But when I open the terminal it shifts my file view off center AND it shrinks the size! This is frustrating because there is enough margin space to perfectly fit the terminal without moving my file view a pixel. Which is what I want.

Zen, single file view, centered
![image](https://user-images.githubusercontent.com/8474974/50458174-063b7080-0916-11e9-934e-c172f88d9943.png)

Zen plus terminal
![image](https://user-images.githubusercontent.com/8474974/50458185-23703f00-0916-11e9-9220-24e14fd419ad.png)

**Comment by vishwa-raj** [comment]
Exactly what @forrestthewoods says

**Comment by forrestthewoods** [comment]
More control over Zen Mode layout seems like something that should at least be kept open? Even if it's not addressed in the near term?

**Comment by SidWorks** [comment]
Namaste 🙏

![image](https://user-images.githubusercontent.com/51191127/115213246-f7001280-a11e-11eb-9a14-c82fe19328dc.png)

**Comment by SidWorks** [comment]
I was doing a course by @pragdave, I loved the way he explained. I took me sometime to realise that it was much more easy to go with the flow as the terminal was in the centre, switching between code and terminal--caused less cognitive load. 
![image](https://user-images.githubusercontent.com/51191127/115214100-cec4e380-a11f-11eb-81b8-9995f8a22981.png)

But it seems that he was using emacs, 

![image](https://user-images.githubusercontent.com/51191127/115214800-82c66e80-a120-11eb-8b48-56a6e6e74bf3.png)

I wanted something like this in VSCODE, So I came up with something like this 
![image](https://user-images.githubusercontent.com/51191127/115214969-a984a500-a120-11eb-9bcb-b5fd78cff5b3.png)

It is not perfect, but it does the job! 
1. I have kept the terminal at bottom, 
2. shifted debug console to right and output to the left
3. Maximized the terminal for full screen by pressing on this button

![image](https://user-images.githubusercontent.com/51191127/115215316-041e0100-a121-11eb-8774-97f55cbcf47e.png)

You can align the terminal left and right padding with the editor terminal. Press **Ctrl + `** to switch to terminal.

![image](https://user-images.githubusercontent.com/51191127/115215539-3b8cad80-a121-11eb-9008-62db9e34924c.png)

This way the workflow is smooth, places less cognitive load and works for me. 
Give it a try @chrmarti  @forrestthewoods @vishwa-raj
