### ISSUE TITLE
Keep centered editor stable when showing sidebar

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44902]
Issue Type: <b>Feature Request</b>

- change to centered mode
- hide sidebar
- now show sidebar and notice the editor jumps

It would be great if it stayed where it was. The jump not only distracts, it also moves the editor off center (when the window is centered to the screen).

VS Code version: Code - Insiders 1.21.0-insider (d7dca142ad6051e6b1c7397ea73221feb0160f21, 2018-03-02T06:08:36.701Z)
OS version: Darwin x64 16.7.0

**Comment by isidorn** [comment]
I think this is personal preference as I could also say when I set my editor to be 80% of the size I always want it to take the size no matter the sidebar. or in other words: I would expect my editor to grow as the horizonal space increases.
Let's leave this open and see what users say when they try it out.

**Comment by chrmarti** [comment]
I don't set it to a percentage, I set it such that it is easy on my eyes in its absolute position. So I'd want it to stay there.

**Comment by isidorn** [comment]
Pushed 6e0ffe26fe
Which basicaly uses absolute numbers and not percentages. Note that the editor will still jump, but it will be centered and the same size as before.
Closing as there is not better way to solve this imho
