### ISSUE TITLE
Reopen Last Session with Ctrl + Shift + T

### ISSUE THREAD

**Issue by FatumFL** [Microsoft/vscode#44905]
Issue type: __Feature Request__

Most of the time there is no need to reopen the last closed session, so I set these two parameters in the user configuration file:
```
"window.restoreWindows": "none",
"workbench.startupEditor": "none"
```
Thus, application starts without any work spaces, open folders or editors. But sometimes the need arises and there is no way but to open all the necessary files and folders using __Open Recent__ command/menu.
In addition, we have __Reopen Closed Editor__ command that uses combination _Ctrl+Shift+T_, but it reopens only editors closed during current session.
Instead, the Chromium-based browsers-like functionality is preferable: _Ctrl+Shift+T_ combination in freshly opened browser reloads the whole previous session and after that behaves as usual - restores only the last closed window of current session.
Is it possible to do the same or at least add the __Reopen Last Session__ option to the command pallet?

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/46138
