### ISSUE TITLE
Inno updater should be more resilient to broken unins000.dat files

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#44911]

**Comment by RMacfarlane** [comment]
@joaomoreno what are the steps to verify this?

**Comment by joaomoreno** [comment]
@RMacfarlane Basically, the Windows background update should still succeed if the `uninst000.dat` file is broken. It used to simply err in such scenario, while now it simply logs that issue as a warning. I think a code review would be good in this case:

https://github.com/Microsoft/inno-updater/commit/3ad811a707d53a8a4d3b1ef0ceea5da01b0622d0
