### ISSUE TITLE
Dropdown: hardcoded knowledge about workbench.parts.statusbar

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44915]
There seems to be hardcoded knowledge in the custom dropdown around the [`workbench.parts.statusbar`](https://github.com/Microsoft/vscode/blob/ben/debt/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L398). This is not good because the widget lives in the base layer and not in workbench.

@cleidigh could we make this configurable somehow and pass in from the outside as option?

**Comment by cleidigh** [comment]
@bpasero 
If we make this configurable as an option does this mean we will allow overflow on top of the status bar
if the bottom clearance is less than the status bar height?
Would we have a hardcoded default that matches the current status bar height?

I do dynamically retrieve the height so it's not exactly hardcoded in case the status bar changes
I guess the element name is hardcoded and part of workbench.  

ControllingStatusBarOverlap was one of the original goals actually pointed out but you,  how can we prevent this if we can't query it?

**Comment by bpasero** [comment]
@cleidigh well I would keep the current behaviour that the dropdown does not go over the status bar by simply passing that 22px pixel value from the workbench.

Alternatively I am also fine if we hardcode this 22px to say that the dropdown is always having some spacing at the bottom of the window to look better.

**Comment by cleidigh** [comment]
@bpasero 
I think I'm going to pass in clearances and maximum height and width.
I will keep the status bar as I hardcode within select box to guarantee clearance with the status bar.

**Comment by bpasero** [comment]
@cleidigh feel free to assign me to review a PR on this and we can discuss the strategies there
