### ISSUE TITLE
Color picker: layer breaker in CSS

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44914]
I do not think the color picker should know about the monaco shell class:

![image](https://user-images.githubusercontent.com/900690/36895051-c49f3f9c-1e0d-11e8-964c-325499ff3cec.png)

**Comment by rebornix** [comment]
@bpasero nice catch, I'm wondering if we have other CSS pollution in monaco editor.

**Comment by bpasero** [comment]
@rebornix yeah there is indeed more:

![image](https://user-images.githubusercontent.com/900690/37015866-dbb24a68-2109-11e8-9dd6-f3e599bca659.png)

Filed as https://github.com/Microsoft/vscode/issues/44913
