### ISSUE TITLE
Layer breaker: simpleFindWidget knows about workbench

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44913]
...but lives in editor. I suggest to remove the explicit knowledge of workbench from that widget.
![image](https://user-images.githubusercontent.com/900690/36895020-a68f1306-1e0d-11e8-81a0-84a157816c26.png)

I am not sure who owns this though, starting with Matt.

**Comment by Tyriar** [comment]
I wasn't very involved in the PRs involved in this so I'll unassign myself

**Comment by rebornix** [comment]
Let's track it in https://github.com/Microsoft/vscode/issues/33264
