### ISSUE TITLE
VScode lags on powerful PC

### ISSUE THREAD

**Issue by OwenLearnsToCode** [Microsoft/vscode#44919]
- VSCode Version: 1.20.1
- OS Version: Windows 10 Home 64-bit

Steps to Reproduce:

It has occured since a first-time clean installation. Every action (Input, selection, scrolling) has a small but very noticeable amount of lag (approx. 0.5s lag) every 10 seconds or so. This occurs on newly created empty files as well. CPU usage is normal (<5%) and RAM usage is normal (250mb). 

PC Specs:
Intel Core i7-7700HQ 2.80GHz
8GB DDR4 RAM
Samsung 256GB SSD
(Nvidia GTX1060 GPU)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@OwenLearnsToCode 

Does this reproduce using the insiders version?

**Comment by OwenLearnsToCode** [comment]
@alexandrudima 

I installed the insiders version just now, and upon testing, it had significantly less lag spikes. But it does still occur, though rarely.

**Comment by alexandrudima** [comment]
@OwenLearnsToCode The insiders has the advantage that it is a fresh install of VSCode. Namely, it lacks your:
* settings
* keybindings
* user profile (history and such)
* extensions
* opened folders (i.e. it starts with an empty window).

Is it perhaps one of the things above that would cause the slowdown?

**Comment by OwenLearnsToCode** [comment]
@alexandrudima

Considering that I've been having the lag spikes ever since I freshly installed VS Code a few days ago, it shouldn't be one of those reasons. And speaking with my experience with other programs, usually performance issues don't result in sudden lag spikes.

**Comment by alexandrudima** [comment]
@OwenLearnsToCode Can you create a profile when you notice something is laggy:

To get a CPU profile of the renderer process:
* Run `F1 > Toggle Developer Tools`
* Go to the three dots burger menu
* Choose `More Tools > JavaScript Profiler`
* Start a new CPU profile
* Do the actions that lead to slowness
* Save the CPU profile to a file and attach it

![kapture 2017-10-21 at 13 02 25](https://user-images.githubusercontent.com/5047891/31851158-30fd860a-b660-11e7-9018-661394adb754.gif)

**Comment by OwenLearnsToCode** [comment]
[CPU-20180306T162417.zip](https://github.com/Microsoft/vscode/files/1784094/CPU-20180306T162417.zip)
Here. After I started the profile, I began randomly selecting, highlighting and scrolling. It lagged once right before I stopped the profile.

**Comment by alexandrudima** [comment]
@OwenLearnsToCode Thanks for the profile, but unfortunately I don't see any blocking activity taking more than 10 or 20ms. It all looks ... rather ... normal and boring. i.e. nothing stands out nor is blocking the UI thread...

So I am thinking the lag is not caused by the renderer process or, at least, not by our code running in the renderer process. I wonder if Chromium has compatibility issues with your GPU. Could you try launching `code-insiders --disable-gpu` ?

**Comment by OwenLearnsToCode** [comment]
@alexandrudima 

That might very well be the reason! The lag spikes were gone after disabling the gpu! Come to think of it, it's probably because of the dual GPU on my laptop. Is there a recommendation for a way of solving this? Meanwhile, I'll play with the GPU switching settings... Thanks so much

**Comment by alexandrudima** [comment]
@OwenLearnsToCode 

For GPU driver issues, it is best to seek help / report issues at https://bugs.chromium.org/p/chromium/issues/list . It is best if you can reproduce this lagginess in Chrome and report it there.

If you cannot reproduce in the latest Chrome, it could be that the incompatibility issues have already been resolved, as VS Code is on an oldish version of Chromium, v58.
