### ISSUE TITLE
HTML (twig) disappeared

### ISSUE THREAD

**Issue by Miralo** [Microsoft/vscode#44918]
### Issue Type
Bug

### Description

When on a HTML file I try to choose "select language mode" the Twig one semms disappeared.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|3.92GB (0.67GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe C:\Michele\Work\girasole.it\girasole|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
rest-client|hum|0.17.0
vue|liu|0.1.5
atom-keybindings|ms-|3.0.4
vscode-icons|rob|7.20.0
sass-indented|rob|1.4.8
expresssnippet|vla|0.2.3
html-css-class-completion|Zig|1.17.1

</details>
Reproduces only with extensions

**Comment by Miralo** [comment]
Sorry, you are right. That's caused by an extension, you can close this issue.
Sorry again.

**Comment by tsalinger** [comment]
No worries, thanks for taking your time to report a potential bug.
