### ISSUE TITLE
VSCode crash report, But the app can run. what's wrong?

### ISSUE THREAD

**Issue by chenxizhang** [Microsoft/vscode#4491]
- VSCode Version:0.10.11
- OS Version:Windows 7

Steps to Reproduce:

1. cd somefolder
2. code
![1](https://cloud.githubusercontent.com/assets/1996954/13914640/9c6c967c-ef8a-11e5-822f-001e12b1ae8e.png)
![2](https://cloud.githubusercontent.com/assets/1996954/13914641/9ca11514-ef8a-11e5-94c5-30ceceddceca.png)

**Comment by chenxizhang** [comment]
I found the code intellisence can not work well , This maybe a big bug

**Comment by bpasero** [comment]
@chenxizhang you seem to see lots of debug output from the code launch, where does "code" point to in your case? when you use the installer it should put "code" on the path and you will not get this output.

**Comment by chenxizhang** [comment]
I am already reinstall windows, and the problem is resolved
