### ISSUE TITLE
Search does not take *.txt documents that are not opened

### ISSUE THREAD

**Issue by muichkine** [Microsoft/vscode#44921]
- VSCode Version:  1.20.1
- OS Version:  Windows 10 Professionel 10.0.16299

Steps to Reproduce:

1. Open a folder with only text files
![image](https://user-images.githubusercontent.com/2428966/36901116-32f97e90-1e26-11e8-911e-eceb4ad1a884.png)

2. Go to search Tab and search for a string. Nothing shows up.
![image](https://user-images.githubusercontent.com/2428966/36901171-7bdda64a-1e26-11e8-95fe-5cd98004f7db.png)

3. Now open a file from the folder and search for the same string. Now results show up.
![image](https://user-images.githubusercontent.com/2428966/36901197-9bb24be2-1e26-11e8-9617-46c0d1ad6ae8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by muichkine** [comment]
I found the issue. It seems that if the folder is synced with OneDrive, vscode deosn't get access to the folder and hence cannot search of anything. If I move the folder to another directory, things work as expected.

An error for not being able to access the folder would be nice. :) Cheers and sorry for the noise.

**Comment by roblourens** [comment]
#35433 - will be fixed in the release later this week.
