### ISSUE TITLE
Brittle Smoketest: 'Everything Else Search searches for body & checks for correct result number'

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#44923]
One of the smoke tests failed on me multiple times on a Ubuntu VM.

Here's the error:
`1) Everything Else Search searches for body & checks for correct result number:
    Error: wait for active element: div[id="workbench.view.search"] .search-view .search-widget .search-container .monaco-inputbox input: Timed out after 20 seconds.`

My specs:
i7-4600U and 8gigs of RAM 
Windows 10, running Ubuntu with 3gigs in a VM.

**Comment by roblourens** [comment]
@isidorn Did any of the DOM here change from your work?

@tsalinger Did you happen to see whether the search viewlet was visible in vscode when this test was looking for it?

**Comment by isidorn** [comment]
@roblourens I did a lot of changes with regards to class names, however I have updated the smoke test to reflect that.
Namely I have renamed `search-viewlet` to `search-view`

If it was some dom change than the smoke test would also fail on my machine which is not the case - it passes nicely.

**Comment by tsalinger** [comment]
I reran the smoketest with the latest insiders and got stuck at a slightly different place:
![smoketestsfailing](https://user-images.githubusercontent.com/15158320/37136917-e46a5768-22a3-11e8-9119-07ef87d56919.gif)


```a@a-VirtualBox:~/Documents/vscode$ npm run smoketest -- --build /usr/share/code-insiders/ --stable-build /usr/share/code/ -f Search

> code-oss-dev@1.22.0 smoketest /home/a/Documents/vscode
> cd test/smoke && mocha "--build" "/usr/share/code-insiders/" "--stable-build" "/usr/share/code/" "-f" "Search"



*** Test data: /tmp/t7802zXc7msf5AMvB
*** Preparing smoketest setup...
*** Fetching keybindings...
*** Creating workspace file...
*** Cloning test project repository...
*** Running npm install...
added 198 packages in 4.86s
*** Smoketest setup done!

  Everything Else
    Search
      ✓ searches for body & checks for correct result number
      ✓ searches only for *.js files & checks for correct result number
      ✓ dismisses result & checks for correct result number
      1) replaces first search result with a replace term


  3 passing (47s)
  1 failing

  1) Everything Else Search replaces first search result with a replace term:
     Error: wait for active element: div.monaco-quick-open-widget[aria-hidden="false"] .quick-open-input input: Timed out after 20 seconds.
      at SpectronClient.<anonymous> (out/spectron/client.js:175:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/spectron/client.js:8:58)
      at <anonymous>



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-oss-dev@1.22.0 smoketest: `cd test/smoke && mocha "--build" "/usr/share/code-insiders/" "--stable-build" "/usr/share/code/" "-f" "Search"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the code-oss-dev@1.22.0 smoketest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/a/.npm/_logs/2018-03-08T06_34_16_969Z-debug.log```

**Comment by isidorn** [comment]
Welcome to the world of smoke tests
