### ISSUE TITLE
Error parsing regex in Search as negative lookahead

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/vscode#44927]
Apparently negative lookahead of RegEx is broken (or never has been working) in Search

- VSCode Version: 1.20.1 (1.20.1)
- OS Version: macOS 10.13.3 (17D102)

Steps to Reproduce:

1. Open "Search"
2. Enter `test\('(?!root)` which is a valid pattern for negating look ahead
3 Observe the error "Error parsing regex near..."

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
We use ripgrep for search, which doesn't support some regex features.

**Comment by aminpaks** [comment]
Yeah. Got it. Thanks.
