### ISSUE TITLE
VS Code Extension Management via CLI Silently Fails for Non-Elevated Privilege Accounts

### ISSUE THREAD

**Issue by DGDC** [Microsoft/vscode#44924]
# System Information
- VSCode Version: 1.20.1, x64
- OS Version: Windows 7 Enterprise Service Pack 1

# Steps to Reproduce:

## List Extensions
1. Open command prompt.
2. Enter  `code --list-extensions .`

![vs code extension management via cli silently fails- list extensions](https://user-images.githubusercontent.com/11006319/36902003-15950128-1df7-11e8-9f21-1832197bb500.png)

## Install Extension from Network
1. Open command prompt.
2. Enter `code --install-extension \\networkPath\extensionName.vsix .`

![vs code extension management via cli silently fails- network install](https://user-images.githubusercontent.com/11006319/36902008-18c794b4-1df7-11e8-95b8-b62d82965813.png)

## Install Extension from Local Drive
1. Open command prompt.
2. Enter `code --install-extension C:\localPath\extensionName.vsix`

![vs code extension management via cli silently fails- local install](https://user-images.githubusercontent.com/11006319/36901361-e07a4acc-1df4-11e8-924a-a6c00f073da5.png)

# Additional Information

Does this issue occur when all extensions are disabled? Not applicable, the point is to manage extensions.

Have attempted with and without the trailing "." and with multiple extensions.

The above actions are done with an account without elevated privileges. The above actions work for an account with elevated privileges.

Installation via the GUI works using non-elevated accounts for local and network stored extensions.

**Comment by sandy081** [comment]
@DGDC Do you get a confirmation message that the extension is installed when you try with an account with prvileges?

**Comment by DGDC** [comment]
@sandy081 Yes, when using an account with privileges there is confirmation that the extension is installed within the command shell. When requesting a list of installed extensions using a privileged account the list of extensions are displayed within the command shell. Thus I would expect failure errors to be displayed in the command shell for non-privileged accounts.

**Comment by sandy081** [comment]
@DGDC Sorry for responding back late. 

If I understand correctly, you are able to install an extension from UI but not from CLI using an user account **without** privileges?

@joaomoreno Both CLI and Renderer use the same extension management code behind, is there any difference how CLI process is started compared to launching of VS Code?

**Comment by joaomoreno** [comment]
@DGDC You seem to have `code.exe` in your PATH, when you should really have `code.cmd`, which is inside `bin` in VS Code's installation folder. What does your `PATH` variable look like?

**Comment by DGDC** [comment]
My issue was open for 90 days before @sandy081 and @joaomoreno most recently responded in June. @vscodebot closed it 10 days later. @vscodebot, I was on vacation, what do you have against vacations? Why are project owners not treated the same, such as taking it to the absurd of closing the projects when issues are open for more than 10 days. Abandonment is abandonment. Geesh. :P

@joaomoreno  , My current path variable is below. Note that it has been 100 days since I reported the issue, my organization's IT department has made many changes to my system, I have updated VS Code multiple times, and I work in a secure environment that is locked down. **Installation and updates require elevated permissions and installation are done with a different user account.**

C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Java\jre1.8.0_131\bin;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\McAfee\Solidcore\Tools\GatherInfo;C:\Program Files\McAfee\Solidcore\Tools\Scanalyzer;C:\Program Files\McAfee\Solidcore\;C:\Program Files\McAfee\Solidcore\Tools\ScGetCerts;C:\Program Files (x86)\Java\jre1.8.0_152\bin;C:\Program Files (x86)\Java\jre1.8.0_152\bin;C:\Users\drglover\AppData\Local\Programs\Fiddler;C:\Users\drglover\AppData\Local\Programs\Git\cmd;C:\Users\drglover\AppData\Roaming\npm

**Comment by joaomoreno** [comment]
@DGDC Oh I see, you don't have Code in the PATH, you simply `cd` to the installation directory and run `code`. Please use `bin\code` instead, or `cd bin` from that directory.
