### ISSUE TITLE
Typo in enter commit message dialog (german)

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/vscode#44922]
### Issue Type
Bug

### Description

1. try to commit a change without entering a commit message
2. This dialog pops up with a typo in the help text:
![unbenannt](https://user-images.githubusercontent.com/17641229/36901282-f0f874e6-1e26-11e8-8cbc-3de424f30b28.PNG)

`"Commit-Nachrichte"` should read `"Commit-Nachricht"` without "e".

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3403)|
|Memory (System)|15.96GB (8.73GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
RunOnSave|eme|0.0.16
auto-close-tag|for|0.5.6
prettify-json|moh|0.0.3
github-issues-prs|ms-|0.9.0
sass-indented|rob|1.4.8
vscode-coverage-gutters|rya|1.3.1

</details>
Reproduces without extensions

**Comment by lukaschal** [comment]
Fixed as suggested "Geben Sie eine Commit-Nachricht ein."

**Comment by danyeh** [comment]
[Fixed](https://github.com/Microsoft/vscode/commit/3bdf5c8aadb2c154580805ebd477fe70f5507d23#diff-ce8a67a17f1503e9ca5e1045fb6dc5f9)
