### ISSUE TITLE
Support console.table(...) in REPL

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#44926]
From @Avocher on Gitter:
Support `console.table(...)`. See https://developer.mozilla.org/en-US/docs/Web/API/Console/table

**Comment by weinand** [comment]
our debug console implementation is not able to support this

**Comment by octref** [comment]
Request to reopen this:

- Although https://github.com/microsoft/vscode/issues/12970#issuecomment-250388851 mentioned it's not on standard track, it seems to be on standard track now: https://developer.mozilla.org/en-US/docs/Web/API/Console/table
- Node also added it to its API: https://nodejs.org/api/console.html#console_console_table_tabulardata_properties
- I find it very useful.
- It should be implementable now.

For example, when I'm attaching to a Node process, Debug Console doesn't show the output but the Node process (CSS Language Server) does show its output:

![image](https://user-images.githubusercontent.com/4033249/60537942-77415380-9cbe-11e9-809b-b1f26011a376.png)

![image](https://user-images.githubusercontent.com/4033249/60537948-7a3c4400-9cbe-11e9-9352-32ec896fe2c0.png)

**Comment by isidorn** [comment]
Let's reopen and leave as a feature request.
The only way this could work is that the node debugger sends multiple strings which format to form a table.
fyi @roblourens

**Comment by weinand** [comment]
Most likely we would have to extend the DAP's "Output" event to support an array of objects.

**Comment by roblourens** [comment]
This is an example of what we get from the runtime:

```
{"method":"Runtime.consoleAPICalled","params":{"type":"table","args":[{"type":"object","subtype":"array","className":"Array","description":"Array(3)","objectId":"{\"injectedScriptId\":1,\"id\":214}","preview":{"type":"object","subtype":"array","description":"Array(3)","overflow":false,"properties":[{"name":"0","type":"string","value":"apples"},{"name":"1","type":"string","value":"oranges"},{"name":"2","type":"string","value":"bananas"}]}}],"executionContextId":1,"timestamp":1562168420835.384,"stackTrace":{"callFrames":[{"functionName":"","scriptId":"91","url":"","lineNumber":0,"columnNumber":8},{"functionName":"","scriptId":"54","url":"file:///Users/roblou/code/testapp-node2/test.js","lineNumber":1,"columnNumber":0},{"functionName":"Module._compile","scriptId":"46","url":"internal/modules/cjs/loader.js","lineNumber":755,"columnNumber":13},{"functionName":"Module._extensions..js","scriptId":"46","url":"internal/modules/cjs/loader.js","lineNumber":769,"columnNumber":9},{"functionName":"Module.load","scriptId":"46","url":"internal/modules/cjs/loader.js","lineNumber":627,"columnNumber":31},{"functionName":"Module._load","scriptId":"46","url":"internal/modules/cjs/loader.js","lineNumber":554,"columnNumber":11},{"functionName":"Module.runMain","scriptId":"46","url":"internal/modules/cjs/loader.js","lineNumber":823,"columnNumber":9},{"functionName":"","scriptId":"41","url":"internal/main/run_main_module.js","lineNumber":16,"columnNumber":10}]}}}
```

the DA doesn't handle it or send anything to vscode currently

**Comment by weinand** [comment]
@isidorn any suggestions how could could surface these tables in the UI and how we could support tables on the DAP level?

**Comment by isidorn** [comment]
My naive hope is that we can just get this to work with the debugger sending text to vscode, and everything just alligning perfectly to form a table.

If that naive approach is not possible my suggestion would be to first check if this or somthing similar can be done in other languages like pyhton and C#. And then we can try to find a common ground which would make sense for the DAP.

As for the UI, the only place where we can show this is in the debug console.
We could render a table in the UI as one element in the debug console in theory. So if the debug adapter would send the size of the table and the contents we could in theory render it. Each table line would have same height.

**Comment by octref** [comment]
This seems to be working already!

**Comment by isidorn** [comment]
Like when things just start working. Also works for me both with Node and pwa. So it seems my naive suggestion from previous coment seems to get the job done.
Good job @roblourens and @conno4312 if you fixed this on the extension side.

**Comment by connor4312** [comment]
Hah I think this is just something that Chrome eventually did (corrected?) we get the table as a string in addition to the raw vars and displaying that works fine

![image](https://user-images.githubusercontent.com/2230985/73297311-319b2980-41c0-11ea-8ef2-993210b7d4f2.png)


but sure I'll take credit for it 😈
