### ISSUE TITLE
Feature request: indents to space (from tabs)

### ISSUE THREAD

**Issue by LittleHamster** [Microsoft/vscode#44920]
I usually use tabs for indents but I like the file to save indents as spaces. 

In PhpStorm there is an option to convert indent to spaces: 

![image](https://user-images.githubusercontent.com/10330481/36900303-ca99fb5c-1df0-11e8-81ed-24ced1ae91e3.png)

Is it possible to add this option in future releases? if we can also auto save tabs to spaces that would be even better

**Comment by tsalinger** [comment]
Sorry for the late response.
I think this is already in the product: https://code.visualstudio.com/docs/editor/codebasics#_indentation:
![indentation-commands](https://user-images.githubusercontent.com/15158320/38780696-f40ecbe0-40da-11e8-92c2-918eb6a9af93.png)
Please let me know if this helps you.

**Comment by LittleHamster** [comment]
@tsalinger 
yeah I found that option, it is great. 
can we automate this on save? so whenever I open a file which tabs are used as indents, convert them to spaces and save? or something that can be run on the entire project

**Comment by SerafimC** [comment]
I think if we implement this to save replacing indentation by spaces, this should be set up somewhere.
