### ISSUE TITLE
Async message boxes flood my UI, blocking use

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vscode#44939]
The Issue Reporter in VS Code doesn't work (see #44938).

Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

When I Open Folder on our vs-platform repo (or any repo with hundreds of projects in it) VS Code can complain about "There are unresolved dependencies from 'projectname.csproj'. Please execute the restore command to continue.

These messages stack up to 5 high on my screen, blocking access to the top of my text files and some of the left panel. Dismissing them with Close doesn't help because there are hundreds that are waiting to be displayed as soon as I close each one.

![vscodedialogs](https://user-images.githubusercontent.com/3548/36914277-938a0eac-1e01-11e8-8548-c752c1518dd3.gif)

Please add a "Dismiss All" button, or (better yet) stop spamming me with the same message for each individual project in the first place!

**Comment by bpasero** [comment]
@AArnott this should be fixed with the work on the new notifications UX (https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_21.md#new-notifications-ui) but you might maybe also want to file a bug to the C# extension why they generate so many notifications in the first place.
