### ISSUE TITLE
Logo is hard to distinguish from VS logo as colorblind user

### ISSUE THREAD

**Issue by pj-martins** [microsoft/vscode#44931]
Being colorblind, the color of latest visual studio code looks exactly the same as the color of the visual studio 2017 icon, same shape too of course. Being a user of both, it is frustrating and time consuming to open the wrong one all the time, yes I know I can change their order in the taskbar but I'm not going to memorize which one's on the left and which is on the right. Yes the old green/orange one was ugly but at least I could tell the difference, for now I'll manually change the icon but would be nice for MS to cater to the colorblind a bit.

**Comment by bpasero** [comment]
@pj-martins I thought the shape was different, can you attach a screenshot?

**Comment by pj-martins** [comment]
![20180302_080310](https://user-images.githubusercontent.com/18081755/36908495-3a78ca80-1df0-11e8-8058-607c8ffd29ea.png)

**Comment by bpasero** [comment]
Yeah the shape is different on the left hand side but similar.

**Comment by Cirzen** [comment]
Even as a non-colourblind user, the icons are so similar that if I have Visual Studio open as well, I click on the wrong one all the time. 
I would fully support an amendment to the icon. Perhaps a large "C" in the background or something?

**Comment by igority** [comment]
This really pains me as a partially colorblind user. A clear distinction from vscode to visual studio has to be made, given the fact that the majority of vscode users are also visual studio users.
Even though a lot of users hated the orange icon, I was much happier with it, for these reasons.
I would like to see update on this.

**Comment by bpasero** [comment]
@misolori maybe follow up if this is still true with the new logo

**Comment by misolori** [comment]
We've addressed this in #71827
