### ISSUE TITLE
Feature Request - Open a package's README.md in markdown preview tab

### ISSUE THREAD

**Issue by shobhitchittora** [microsoft/vscode#44935]
VSCode currently allows a mouse hover to see a package's description in `package.json` file. It'd be great to have this feature to see the full README by right-clicking and selecting in a package from `package.json`. 

PS: Webstorm's latest allows for a shortcut to see README of a package.

**Comment by shobhitchittora** [comment]
Ping @tsalinger / @aeschli / @mattbierner.

**Comment by aeschli** [comment]
That could be part of the built-in npm extension, or also be implemented by an extension from the marketplace.

**Comment by shobhitchittora** [comment]
@mjbvz Any suggestions on how can I trigger a Markdown Preview window from `package.json` file ?
I want to send the markdown content as a string to the new window on `cmd + click` on a `package.json` entry.

**Comment by mjbvz** [comment]
You should be able to use the `markdown.showPreview` command. It takes a `vscode.Uri` so you must have a file on the disk.

```ts
import * as vscode from 'vscode';

vscode.commands.executeCommand('markdown.showPreview', vscode.Uri.file('/path/to/file.md'))
```

Try creating a temp file if you don't have one on disk already

**Comment by shobhitchittora** [comment]
@mjbvz Ideally the `showPreview` should work with a buffers. But yeah i'll try with making a temp file for now. Any idea on how to create a temporary file and how to remove it on close of the preview tab ?

**Comment by shobhitchittora** [comment]
@aeschli @mjbvz terribly stuck! 😅

**Comment by egamma** [comment]
There is an extension in the marketplace that supports this feature https://marketplace.visualstudio.com/items?itemName=bengreenier.vscode-node-readme
