### ISSUE TITLE
Cannot open files from a WSL terminal into VS Code

### ISSUE THREAD

**Issue by edDimensi** [Microsoft/vscode#44930]
- VSCode Version: 1.20.1
- OS Version: Windows 10 Pro 1709

Steps to Reproduce:

1. Try open file via code from wsl console
The file exists and has content, but vs code tries to create a file
![image](https://user-images.githubusercontent.com/11390039/36905170-a84054fe-1e43-11e8-9b4b-5f8e7d53e2ed.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
If someone wants to drill into this, here is how to run out of sources to debug: https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by 0xabu** [comment]
Random guess: the file you're trying to open is under /home, which by default uses lxfs (Linux-only filesystem) and is accessible only to WSL processes. Does opening a file under /mnt/c work?

**Comment by edDimensi** [comment]
Yes. I can't open dir too if is under wsl

**Comment by 0xabu** [comment]
WSL doesn't support what you're trying to do. I suggest checking https://docs.microsoft.com/en-us/windows/wsl/interop for details. You'll either need to place the files you want to edit under /mnt/c or similar, or change your drive mounts so that /home is a drvfs (not a volfs/lxfs) filesystem.

**Comment by edDimensi** [comment]
Does this mean I can not use vs code as an editor for git? What I can do?

**Comment by bpasero** [comment]
Closing as per https://github.com/Microsoft/vscode/issues/44930#issuecomment-370028160
