### ISSUE TITLE
Integrated Terminal freezes window when running endless output command

### ISSUE THREAD

**Issue by Servius-Prime** [Microsoft/vscode#44933]
### Issue Type
Bug

### Description

To Repro the Problem:
1) First Create an infinite loop in a C++ program, and add a cout statement so it prints something every time the loop iterates.

2) Compile using MinGW or whatever local C++ compiler you have for windows.

3) Run the executable in the integrated terminal.

Code:
``` Cpp
#include <iostream>

using namespace std;

int main() {
    unsigned long long x = 1;
    while(true) {
        cout << "X is = " << x++ << endl;
    }
}
```

It will typically hit anywhere between 1 and 500 iterations before the program freezes. It doesn't print anymore after the freeze and is unresponsive to input. The only way to get it out is to kill the process, Ctrl+C. This only seems to occur when I have lots of sequential cout statements, like printing out a large vector, etc.

Additionally, the external command prompt runs this program with no issues. Also an equivalent code in python executes in the integrated command prompt without issues, and I also ran "tree" in the C:\ Drive and it had no issues with freezing.

Picture:
![image](https://user-images.githubusercontent.com/21212871/36909960-134b8078-1e05-11e8-84bc-1474826603af.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|Memory (System)|15.89GB (8.44GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.1.0
cpptools|ms-|0.15.0
vscode-yaml|red|0.0.9

(3 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
Yes this will happen, it used to be *much* worse though. The real fix for this is to split more of the terminal's work out into a web worker so it doesn't block the renderer process. If you look at a perf profile while this happens it will show that parsing and drawing together take longer than the output takes to come from the C++ program.

**Comment by Servius-Prime** [comment]
Ok, I just want to make sure that it was clear that this doesn't only occur in a infinite loop. This occurs in any program that has about 10+ iterations of a loop with a cout statement in it. I just chose to give the infinite loop as an example because it is the most reproducible instance of the issue.

Also is there anything I can do to implement the "real fix" you mention or is that something that may become available in newer versions of the software. Thanks for your help!

**Comment by Tyriar** [comment]
@Servius-Prime if it's not just on loop you might be seeing https://github.com/Tyriar/node-pty/issues/170

As for the fix I mentioned, it's a pretty big architectural shift in https://github.com/xtermjs/xterm.js and would need a core maintainer to work on.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/42234
