### ISSUE TITLE
Select all leading to odd file corruption

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44942]
Issue Type: <b>Bug</b>

1. For a js file:

```js
// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

}// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

}// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

}// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;
}
// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

}// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

}// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

}// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;
}
// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

}// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

}// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

}// @ts-check
///<reference path="y.d.ts" />
{
    /**
     * @type {IRouter}
     */
    let customRouter;

```

2. Select all
3. Type a character to replace
     🐛 Inserts multiple copies of the new character
4. Hit undo
    🐛 Notice multiple line `96` in the gutter. The file model seems to be corruped

![mar-02-2018 10-38-38](https://user-images.githubusercontent.com/12821956/36915532-ed84d10e-1e05-11e8-9abc-48d1174ae36d.gif)

VS Code version: Code - Insiders 1.21.0-insider (9a04587cc6b42c332609a08bfd7e2dbeac592c21, 2018-03-01T06:39:57.509Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
emojisense|bie|0.4.0
lit-html|bie|1.2.0
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-mermaid|bie|0.1.1
markdown-preview-github-styles|bie|0.1.0
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.28
vscode-styled-components|jpo|0.0.16
graphql-for-vscode|kum|1.9.0
azure-account|ms-|0.3.1
debugger-for-chrome|msj|4.1.0
angular2-inline|nat|0.0.17
vscode-code-outline|pat|0.0.13

(16 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
A full restart (not just a window reload) seems to have fixed this? I'll see if I can reproduce this again

**Comment by rebornix** [comment]
Not sure if it's related to text buffer yet. The duplication of line number `96` is weird though.

**Comment by alexandrudima** [comment]
@mjbvz I cannot reproduce.

1. I create a file with the contents you indicate.
2. I select all
3. I press <kbd>a</kbd>

Everything appears to work ok. @rebornix can you reproduce? 

@mjbvz I would really like to get to the bottom of this one before we ship stable. I did some changes to the way events travel between the model and the view model. Can you please distill the steps further such that I can also reproduce ? 

![kapture 2018-03-05 at 11 52 55](https://user-images.githubusercontent.com/5047891/36971362-dbc44dd8-206b-11e8-97bc-d5d4d94b0b91.gif)

**Comment by mjbvz** [comment]
I haven't been able to reproduce it either. Very strange issue. I'll reopen this bug if it ever happens again
