### ISSUE TITLE
Add verification-steps-needed label

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44948]
During endgame verification process, I often find myself spending 15 minutes verifying some issue but at the end can't verify it, so I ping the owner for steps. However there is no visual indication of such issues and it keeps consuming everyone's time.

So I suggest we have a `verification-steps-needed` label. 

![image](https://user-images.githubusercontent.com/4033249/36919126-1a2bbafa-1e11-11e8-992d-8beac360a52c.png)

For verifiers, you add this label so others can skip verifying these issues until the owner has given steps for verifying and removed the label.
During each day of verifying, owners of these `verification-steps-needed` issues start by adding steps and removing the label before doing verification.

I have added the label but haven't updated wiki yet. If people don't have strong opinion against it I can update the wiki too.

@Microsoft/vscode What do you think?

**Comment by chrmarti** [comment]
Sounds good, although I'm wary of formalizing our process more than necessary.

**Comment by octref** [comment]
I have updated the wiki.
