### ISSUE TITLE
Shift+click selection behavior not as expected

### ISSUE THREAD

**Issue by inarius** [Microsoft/vscode#44947]
Issue Type: Bug

Using Shit+click in the Open Editors document explorer does not behave the same as other selection areas. When Shift+click is pressed, the selection occurs, but the selection Start is changed to the clicked item which should be the selection End. To reproduce:

1. Mouse-click to select an item in Open Editors
2. Hold Shift and mouse-click another item to select a range of items.
3. Hold Shift and mouse-click to select a different range of items. the new selections will be between the two latest items instead of the first and last items. SelectStart is being set incorrectly.

![sample](https://user-images.githubusercontent.com/4432847/36919030-b4c785ae-1e10-11e8-9bd9-05faaf0c9106.gif)

VS Code version: Code - Insiders 1.21.0-insider (903169966590cd236c5016cdc774875215d31765, 2018-02-26T05:18:08.801Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7650K Radeon R7, 10 Compute Cores 4C+6G  (4 x 3292)|
|Memory (System)|14.94GB (6.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.0.20
rainbow-csv|mec|0.2.0
mssql|ms-|1.3.0

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
@inarius I don't see this on mac, can you update your insiders and try again as your build is a few days old now.

**Comment by inarius** [comment]
Fixed apparently! It works now, sorry about that.
