### ISSUE TITLE
Feature request: Suggest namespace import for files with no default export

### ISSUE THREAD

**Issue by meyer** [Microsoft/vscode#44950]
- VSCode Version: 1.20.1
- OS Version: macOS 10.13.4 beta 17E160e

It’d be neat if the TypeScript `import` suggestion suggested namespace imports for TypeScript files with no default export.

**Comment by mjbvz** [comment]
Please provide some example code that explains the desired behavior

**Comment by meyer** [comment]
Sure thing.

Say there’s a file, `Settings.ts`, with the following content:
```ts
export function get(key: string) { /* ... */ }
export function update(key: string, value: any) { /* ... */ }
```

At the moment, VS Code will suggest importing the individual functions, but the way I use them everywhere is with a namespace import:

```ts
import * as Settings from './path/to/Settings';

// in use
Settings.get('thing');
```

Unless I’m mistaken, VS Code only suggests importing named exports and default exports. My feature request is for VS Code to suggest namespace imports as well. Suggesting namespaces imports for _every TS file_ would create far too much clutter, though, which is why I proposed only suggesting namespace imports for files with no default export.

**Comment by mjbvz** [comment]
Thanks. I believe that https://github.com/Microsoft/TypeScript/issues/19630 is already tracking this

**Comment by meyer** [comment]
ah yep, this is a dupe. Thanks!
