### ISSUE TITLE
Please don't re-arrange explorer location when file closed

### ISSUE THREAD

**Issue by VicoErv** [Microsoft/vscode#44959]
When i open node_modules folder, i want to take a look for another script there, i have too many tab opened, so i close and back far away from node_modules.

- VSCode Version: Visual Studio Code 1.20.1
- OS Version: Debian Stretch

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Set: `"explorer.autoReveal": false`
