### ISSUE TITLE
Multiple Monitors / Task View Performance Issue

### ISSUE THREAD

**Issue by rianquinn** [Microsoft/vscode#44955]
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Windows 10 1709

VSCode performance (especially with the terminal) degrades really bad when you create more than one window, and put the second window on a different monitor, or in a different Virtual Desktop. 

Steps to Reproduce:

1. Create a second window
2. Put that window on another Virtual Desktop or second Monitor
3. Try to run commands in the integrated terminal, performance should be degraded. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I think this is https://github.com/Microsoft/vscode/issues/36913
