### ISSUE TITLE
Adapt VSCodeVim to the new behavior of `cursorMove`

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44958]
Context: #44878

In this iteration, we changed the behavior of moving the cursor up/down from staying on the same column to staying on the same **visual** column. Visual means `tabWidth` and CJK characters (2 char width) are taken into consideration. Previously only `tabWidth` was taken into consideration.

For example,

```
12|
中国
	12 // one leading tab. tabWidth = 2
```

With the following code, running two `cursorMove` to go down produces different result.

```ts
vscode.commands.executeCommand('cursorMove', {
  to: 'down',
  select: false,
  by: 'line',
  value: 1
});
```

Stable

```
12|
中国|
	|12 // one leading tab. tabWidth = 2
```

Insider

```
12|
中|国
	|12 // one leading tab. tabWidth = 2
```

This might cause subtle behavior change for VSCodeVim when moving around in a document with CJK characters.
However, using this API might fix some other issues for VSCodeVim too. For example, now j/k moves diagonally in codebase with tab, between two lines of different numbers of leading tabs.
https://github.com/VSCodeVim/Vim/issues/842

**Comment by octref** [comment]
fyi @johnfn @Chillee @jpoon

**Comment by rebornix** [comment]
Let's just use the Vim issue to track.
