### ISSUE TITLE
Format Code fails for javascript depending on line breaks

### ISSUE THREAD

**Issue by HCanber** [Microsoft/vscode#4495]
- VSCode Version: __0.10.11 f291f4ad600767626b24a4b15816b04bee9a3049__
- OS Version: __OS X 10.11.3 (15D21)__

Steps to Reproduce:

- New document
- Paste:

``` javascript
function abc() {
const xyz = () => {
return 123 }
}
   var x
```
- Save as `test.js`
- Issue the command `Format Code`  (Spaces: 2)
- Nothing happens, which is _not_ expected behavior. I can understand if the function isn't formatted properly, but I expect `var x` (and the rest of the code in the document if there would have been any) to be formatted. _Ignoring commands_ is reported in Developer Tool's Console. 
- Insert linebreak (LF) after 123 so that `}` is on a separate line:

``` DIFF
function abc() {
const xyz = () => {
-return 123 }
+return 123 
+}
}
   var x
```

- Issue the command `Format Code`
- The code is reformatted correctly as:

``` Javascript
function abc() {
  const xyz = () => {
    return 123
  }
}
var x
```

This code can also be formatted:

``` javascript
function abc() {
const xyz = () => {return 123 }
}
   var x
```

After Format Code:

``` javascript
function abc() {
  const xyz = () => { return 123 }
}
var x
```

**Comment by dbaeumer** [comment]
This works for me on the upcoming Match drop
![bug](https://cloud.githubusercontent.com/assets/1931590/13932387/241042dc-efa8-11e5-8cb7-fb3643ff3ed7.gif)
