### ISSUE TITLE
Cannot open directory with spaces with the command line

### ISSUE THREAD

**Issue by tmattio** [Microsoft/vscode#44952]
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra 10.13.3

Steps to Reproduce:

```
mkdir test\ directory/
code test\ directory/
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by meyer** [comment]
@tmattio what shell are you using? The example you posted works for me in both bash and fish shells.

**Comment by tmattio** [comment]
I'm using bash, with bash-it for my bash_profile: https://github.com/Bash-it/bash-it

**Comment by joaomoreno** [comment]
What does `which code` return?
