### ISSUE TITLE
Respect TSServer quick info formatting

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#44953]
Currently, quick info tooltips provided from TSServer contain newlines which are not being respected by VS Code, instead being automatically wrapped by some logic in VS Code itself.

While this might be helpful in the general case, TypeScript is intentionally formatting declarations and types in a specific way. Would we be able to have that formatting respected?

CC @mhegazy

**Comment by mjbvz** [comment]
Do you mean the `displayString` property on `QuickInfoResponse`?

**Comment by DanielRosenwasser** [comment]
I believe so.

**Comment by mjbvz** [comment]
What is the expected behavior? We currently wrap if a line is too long but I believe that newlines are respected
