### ISSUE TITLE
Ignore problems on commented out line

### ISSUE THREAD

**Issue by ixixit** [Microsoft/vscode#44954]
### Issue Type
Bug

### Description

Hello!  In this powershell script, I've created an if block which is commented out, and has no statement block following it.  It is correctly detected as a comment line in the syntax, but the problem section reports it as an active problem, though it is not active in the script due to the # comment block.

```
# if ((Get-ChildItem -Path "$LogDir\$TempDir" -File -Recurse -Exclude '*.zip' | Measure-Object | ForEach-Object {$_.Count}) -ne 0)
if ((Test-Path -Path "$LogDir\$TempDir" -PathType Container) -And ((Get-ChildItem "$LogDir\$TempDir" -File -Recurse | Measure-Object | ForEach-Object{$_.Count}) -gt 1))
{
    $FileCount =  (Get-ChildItem -Path "$LogDir\$TempDir" -File -Recurse | Measure-Object | ForEach-Object{$_.Count})
}
```
Problems: [Powershell] Missing statement block after if (condition).

Secondly, if I create a second if line afterwards, and reverse the comment block, problems says there are no problems!

```
if ((Get-ChildItem -Path "$LogDir\$TempDir" -File -Recurse -Exclude '*.zip' | Measure-Object | ForEach-Object {$_.Count}) -ne 0)
# if ((Test-Path -Path "$LogDir\$TempDir" -PathType Container) -And ((Get-ChildItem "$LogDir\$TempDir" -File -Recurse | Measure-Object | ForEach-Object{$_.Count}) -gt 1))
{
    $FileCount =  (Get-ChildItem -Path "$LogDir\$TempDir" -File -Recurse | Measure-Object | ForEach-Object{$_.Count})
}
```
Problems: No problems have been detected in the workspace so far.

If I revert to the original condition, and remove the active if line, problems reports an unexpected else, which is correct, but not illustrated in this example..

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.79GB (10.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|57%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.6.0

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
This issue was moved to PowerShell/vscode-powershell#1253
