### ISSUE TITLE
Support for KEdit All command

### ISSUE THREAD

**Issue by hansker8** [microsoft/vscode#44963]
Hello, I would like consideration for re-opening [12331](https://github.com/Microsoft/vscode/issues/12331), which in my opinion is the most power editing feature that I have never seen in any other editor since.   So, basically in KEdit, you had a command line where you can type in `All / [keyword]` and what it would do is collapse all the lines and only show lines that included one or more matches of the keyword, hiding all other lines.  So you can quickly get a global view of all instances of that keyword match.  You could make any line the active row and toggle back & forth to display/hide all lines in the text file.  It was really cool.  

Another extremely powerful feature of KEdit was the change command, where on the command line with the syntax `ch / [old text] / [new text] * *` it would replace all instances of `[old text]` with `[new text]`.  However, in order to preview the scope of changes, what you could do is first apply the `All / [old text]` command to see where are all the instances that would be replaced prior to applying the change command.

**Comment by tsaiDavid** [comment]
I'd love to see this too - or at least something similar :)
