### ISSUE TITLE
Windows: Bash is not accessible in integrated terminal

### ISSUE THREAD

**Issue by x1unix** [Microsoft/vscode#44960]
- VSCode Version: 1.20.1
- OS Version: Windows 10 Pro 16299

Steps to Reproduce:

1. Open **VS Code**
2. Open integrated terminal
3. Type `bash` in terminal

Output:
```
C:\Users\User\Desktop>bash
'bash' is not recognized as an internal or external command,
operable program or batch file.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by tomjaimz** [comment]
Is Bash installed?
If it's installed, is it Ubuntu from the Microsoft Store, or the older version?
What happens if you open a command prompt and type 'bash'?

**Comment by x1unix** [comment]
@tomjaimz, yes. It's installed. Installed both versions (legacy beta and the new one).
Bash is accessible from command prompt.

**Comment by Tyriar** [comment]
I used to see this all the time but it went away, it might have something to do with the specific Windows version? You can try setting the terminal to launch as bash by default using the "Select Default Shell" command (F1).

@bitcrazed do you know what causes this?

**Comment by tomjaimz** [comment]
I would assume that you can run it by specifying the path for bash (i.e., `\windows\system32\bash` works?)

If that is the case perhaps your path could not be set correctly?  Does the `set path` command indicate that `c:\windows\system32`\ is in your path? Do you have anything path related in your "terminal.integrated.env.windows" user settings in VS Code?

**Comment by x1unix** [comment]
@tomjaimz, I was trying to start bash using full path:
```
> C:\Windows\System32\bash.exe
'c:\Windows\System32\bash.exe' is not recognized as an internal or external command,
operable program or batch file.
```

P.S - This file exists in specified path
