### ISSUE TITLE
Arduino Plugin Moves Terminal Connect Button

### ISSUE THREAD

**Issue by MZachmann** [Microsoft/vscode#44976]
### Issue Type
Bug

### Description

Enable/Initialize the Arduino Extension for this workspace.

Attempt to click the Serial Connect Button on the bottom status bar.

When you go to click it the button saying Win32 appears and the connect button moves to the left.

Click it to connect.

Click the mouse in the terminal window (important!) and the Win32 button will disappear, moving the disconnect button to the right.

Click the disconnect button and instead the Win32 button will appear and you will have to click again.

Unbelievably annoying.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|15.94GB (9.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Mark\OneDrive\Documents\Lora\Pytest|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
python|don|0.7.0
gitlens|eam|8.0.2
python|ms-|2018.1.0
cpptools|ms-|0.15.0
debugger-for-edge|msj|0.4.1
vscode-arduino|vsc|0.2.10
markdown-all-in-one|yzh|1.0.5

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Please continue the discussion of this vscode-arduino specific issue here:
https://github.com/Microsoft/vscode-arduino/issues/483
