### ISSUE TITLE
Warnings from 'explorer.newFile' command on launch or if Explorer is not mounted

### ISSUE THREAD

**Issue by jingchan** [Microsoft/vscode#44978]
- VSCode Version: 1.20.0
- OS Version: OS X 10.13.3

Steps to Reproduce:

1. Have 'explorer.newFile' bound to a keyboard shortcut.
2. Use shortcut to call 'explorer.newFile' immediately after launching VSCode. 

![screen shot 2018-03-04 at 12 35 48 am](https://user-images.githubusercontent.com/368061/36936848-5822605e-1f45-11e8-89d6-ef0a354b4b2f.png)
(This warning occurs whether or not Explorer is visible or hidden.  Pressing the 'New File' button on the Explorer works fine.  Functionality returns to as expected after the Explorer is first given focus.)

3. Use shortcut to call 'explorer.newFile' when side panel is hidden

![screen shot 2018-03-04 at 12 51 07 am](https://user-images.githubusercontent.com/368061/36936895-2b920020-1f46-11e8-88a5-09616b6ea313.png)

4. Use shortcut to call 'explorer.newFile' when a non-Explorer side panel is mounted instead

![screen shot 2018-03-04 at 12 51 45 am](https://user-images.githubusercontent.com/368061/36936901-3e919172-1f46-11e8-827d-01660ff4e444.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is fixed in the latest vscode insiders and will be available in the vscode stable release in a couple of days
