### ISSUE TITLE
collapse not work for multiple lines string variable

### ISSUE THREAD

**Issue by taina0407** [Microsoft/vscode#44979]
### Issue Type
Bug

### Description

Try to collapse functionA as bellow doesn't work, only collapse till the begin "`" character. Expected to collapse all function.

```javascript
const functionA = (options) => {
  const {variable, } = options;
  const config = `
#EXAMPLE CONFIG FILE

#EXAMPLE VARIABLE
VARIABLE=${variable}
`;
};
```
![image](https://user-images.githubusercontent.com/5900860/36937151-89eac364-1f41-11e8-8031-f8d01b3c1334.png)

![image](https://user-images.githubusercontent.com/5900860/36937145-7fc5a598-1f41-11e8-9d12-03ea48182751.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4201)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
vscode-eslint|dba|1.4.7
gitlens|eam|8.0.2
php-intellisense|fel|2.2.9
vscode-esformatter|how|1.5.2
azure-account|ms-|0.3.1
bash-beautify|sha|0.1.1

</details>
Reproduces without extensions

**Comment by aeschli** [comment]
Our folding is currently based on indentation only.
The request to add language aware folding capabilities is #3422
