### ISSUE TITLE
[HTML , Emmet , Angular] include suggest 2x, view 0x.

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#44974]
### Issue Type
Bug

### Description

emmet suggest 2x data-ng-include, doesn't suggest ng-view / data-ng-view

![screenshot_1](https://user-images.githubusercontent.com/31345346/36936262-43a73358-1f03-11e8-9fcb-961975af1d40.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.88GB (11.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by ramya-rao-a** [comment]
@Mlocik97-issues Those dont look like Emmet suggestions. Can you give a code sample that we can try on?

**Comment by Mlocik97-issues** [comment]
ng-view was fixed,... dana-ng-include is double only with C extension https://github.com/Microsoft/vscode-cpptools
