### ISSUE TITLE
Update notification repetition

### ISSUE THREAD

**Issue by chargingsleipnir** [Microsoft/vscode#44972]
### Issue Type
Bug

### Description

This isn't really something I can even try to reproduce. The issue is just that I keep getting notifications about the same update repeatedly. I've downloaded the January 2018 update at least 3+ times now, and it's like that for every new update. Every couple of weeks it says there's a new one, but it's just the same one I did previously; until it actually is new anyway.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|7.88GB (3.99GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.1.9
vscode-firefox-debug|hbe|1.1.0

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
We've been working heavily on improving the update experience lately.
Does this problem still occur for you in the latest release?
