### ISSUE TITLE
Terminal text randomly disappears

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/vscode#44973]
### Issue Type
Bug

### Description

While working, the text in the `Terminal` pane often disappears.  The terminal is still functional at this point--you can enter commands and they will run--but nothing is shown in the pane.  Switching to a different tab, e.g. `Problems` and back again seems to fix it but it's very annoying and I haven't been able to work out the cause of the issue yet.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|Memory (System)|15.96GB (11.28GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by Tyriar** [comment]
I think this is fixed in Insiders https://github.com/Microsoft/vscode/issues/44040
