### ISSUE TITLE
The "Launch Program" icon is ignored by statusBar.debuggingForeground 

### ISSUE THREAD

**Issue by stoberov** [Microsoft/vscode#44989]
Hey,

I am playing with the **workbench.colorCustomizations** settings and I've noticed that when an app is running in **debug mode**, the "Launch Program" icon gets ignored by the **statusBar.debuggingForeground** color.

For example, here's a sample with:
```
"statusBar.debuggingBackground": "#000",
"statusBar.debuggingForeground": "#e40808"
```
![Sample 1](https://i.imgur.com/yPO3XtE.png)

As expected, most of the icons turn red, but the "triangular play icon" is not affected - instead, it defaults to statusBar.foreground color (grey here). So, let's change it to something else:

`"statusBar.foreground": "#24c004"`

![Sample 2](https://i.imgur.com/dGa8a0d.png)

This could just be me, but I would expect everything should be treated the same way in debug mode with the debuggingForeground color.

**Comment by sandy081** [comment]
@isidorn This is what I see when I configure following colours

```json
"workbench.colorCustomizations": {
     "statusBar.debuggingBackground": "#000",
    "statusBar.debuggingForeground": "#e40808"
},
```
![image](https://user-images.githubusercontent.com/10746682/38076397-cae53496-3335-11e8-9f48-ecda5d129f27.png)

Doesn't it should be like this?

![image](https://user-images.githubusercontent.com/10746682/38076476-03b44fb4-3336-11e8-8de3-bdb70abd1c08.png)

**Comment by sandy081** [comment]
@isidorn Since you are on holiday, I am assuming this bug is not fixed correctly and reopening it and assigned to next milestone (as it is not critical). 

Please close it otherwise

**Comment by weinand** [comment]
looks fine now:

![2018-04-25_16-48-47](https://user-images.githubusercontent.com/1898161/39253628-8d678276-48a8-11e8-8694-62ba292ba44c.png)
