### ISSUE TITLE
Allow to close About dialog with cmd+W on macOS

### ISSUE THREAD

**Issue by gingerbeardman** [microsoft/vscode#44983]
- VSCode Version: 1.20.1
- OS Version: Mac OS X 10.13.3 (17D102)

Steps to Reproduce:

1. Click _Code_ menu
2. Click _About Visual Studio Code_
3. Press <kbd>cmd</kbd>+<kbd>W</kbd>
4. About dialog does not close.

Does this issue occur when all extensions are disabled?: Yes, but it's slightly different in that the File menu flashes when the key combo is pressed. I suspect because there are items in the menu that accept the shortcut.

**Comment by gingerbeardman** [comment]
@bpasero can you please let me know the number of the issue this is a duplicate of. Search was no help

**Comment by bpasero** [comment]
Cannot find it anymore, weird.

**Comment by gingerbeardman** [comment]
OK thanks

**Comment by gingerbeardman** [comment]
Closing valid issues continues to be an obnoxious way of dealing with them. It's a real 🖕 to people who spend their valuable time adding them.

cc @bpasero

**Comment by mjbvz** [comment]
Please read the linked to document on why we close issues as [out of scope](https://aka.ms/vscode-out-of-scope)

This bug will not be hit by users in their day-to-day workflows and is very easily worked around. It has also been open for a year and a half with only one other upvote. Considering these facts,  we will not be addressing this bug anytime soon and therefore closed it as out of scope in keeping with our issue tracking policies

**Comment by gingerbeardman** [comment]
I think the app should work as expected on the OS it is running on, bot being able to lose a dialog with the keyboard is unexpected and wrong. There should be scope for that.
