### ISSUE TITLE
Provide comments in jsconfig.json to guide people towards using tsd to install typings file

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#4498]
- VSCode Version: 0.10.12
- OS Version: Windows 10

Steps to Reproduce:

1. Create an ionic starter app with 'ionic start myIonicApp blank'
2. Open a js file
3. Click on the lightbulb in the status bar, then click the 'Create jsconfig.json' button in the prompt

Expected: A comment in the jsconfig.json file that describes how to use tsd to add typings file to the project in order to get the rich intellisense that was described in the prompt on step 3.

**Comment by jrieken** [comment]
We have a fwd link to a website which should explain all of that.

**Comment by jrieken** [comment]
@egamma Is the link you gave me already live?

**Comment by egamma** [comment]
@jrieken the link is live, but the content hasn't been updated yet, the new content will first be in the vnext branch.

**Comment by stevencl** [comment]
This is probably out of date now. As I understand it, Salsa will provide the intellisense for node modules, is that correct? Assuming that this is the case I'm going to close this but let me know if I am wrong.
