### ISSUE TITLE
Integrated Terminal Bash - backslashes instead of forward slashes

### ISSUE THREAD

**Issue by CalogeroMandracchia** [Microsoft/vscode#44987]
Hi! 
I have a very similar issue to #29926

- VSCode Version: 1.20.1
- OS Version: Windows 7 64 bit

Steps to Reproduce:

1. Drag and drop a file to the integrated terminal set in Bash

What happens?

The slashes are all backslashes thus making the path invalid (foo\bar\baz\qux becomes foobarbazqux)

What should happen?

There shoud be only forward slashes.
If i normally do this with the bash for Win( 4.4.12(1)-release ) then i get forward ones.
If the IT is set in "cmd" or powershell then everything works fine. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36897 (same root cause)
