### ISSUE TITLE
crash after file changed

### ISSUE THREAD

**Issue by jesseliu612** [Microsoft/vscode#44992]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. create an empty file, and name it `test.out`
2. use vscode to open it.
3. run the following c++ code in the current directory to write something into the file:
```c++
#include <bits/stdc++.h>
using namespace std;
int main () {
    freopen("test.out","w",stdout);
    for(int i=1;i<=100000;i+=1) {
        cout << i << endl;
        for(volatile int j=1;j<=100;j+=1) fflush(stdout);
    }
    return 0;
}
```
4. change `cout << i << endl` to `cout << 100000-i << endl`, and run it again.
5. vscode crashes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
If I understand right, you have opened an editor on a file that is modified at a quick rate.

**Comment by bpasero** [comment]
@jesseliu612 how large is the file getting over time when it crashes?

**Comment by jesseliu612** [comment]
@aeschli you're right
@bpasero not very large, only about 580KB.

**Comment by bpasero** [comment]
@jesseliu612  I changed your sample to this:

```cpp
#include <iostream>
#include <fstream>
using namespace std;
 
int main () {
  ofstream file;
  file.open ("codebind.txt");
  for(int i=1;i<=100000;i+=1) {
      file << 100000-i << endl;
        for(volatile int j=1;j<=100;j+=1) fflush(stdout);
    }
  
  file.close();
  return 0;
}
```

But cannot reproduce. What is your exact setup, do you have the parent folder of that file opened?  Can you reproduce with our insider release? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jesseliu612** [comment]
@bpasero fortunately it works fine when using the insider release. Next time I'll check the insider release before submitting an issue. Thanks again for your reply.

**Comment by jesseliu612** [comment]
upd:
Seems another problem turned out. It can be caused by an unexpected infinite loop.
run the following code:
```c++
#include <bits/stdc++.h>
using namespace std;
int main () {
    freopen("test.out","w",stdout);
    while(1) cout << "1" << endl;
    return 0;
}
```
while the program is running, vscode seems alright, but after about 10 seconds when I press Ctrl+C to terminate it, the system turned no responding, and I have to restart the computer in order to continue my work.

**Comment by bpasero** [comment]
@jesseliu612 the entire system turns frozen or only VS Code?

**Comment by jesseliu612** [comment]
@bpasero the entire system, even the cursor can't move, and Ctrl+Alt+Fx doesn't work. but it should be caused by VS Code.

**Comment by bpasero** [comment]
@jesseliu612 do you have the parent folder of the file opened or only a single file and nothing else? Can you show a screenshot when the file is opened?

**Comment by jesseliu612** [comment]
![2018-03-06 22-59-12](https://user-images.githubusercontent.com/13160806/37039320-20a38b90-2192-11e8-884f-ef91e10469b8.png)

**Comment by bpasero** [comment]
@rebornix this could be the thing you mentioned once where the diff is getting very expensive when I set the model after receiving a file change event. Have you thought about disabling this for larger files?

**Comment by bpasero** [comment]
@jesseliu612 can you try to reproduce this from a newer build with a newer Electron version?

Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)
