### ISSUE TITLE
Wrong indentation size auto-detection in python

### ISSUE THREAD

**Issue by Eugenii10** [Microsoft/vscode#44991]
### Issue Type
Bug

## Actual behavior
VS Code incorrectly determine indentation style as 8 spaces.
![actual](https://user-images.githubusercontent.com/26702097/36935694-8ca58152-1f46-11e8-8ee0-25d43c7b1e49.png)

## Expected  behavior
VS Code determine indentation style as 4 spaces.
![expected](https://user-images.githubusercontent.com/26702097/36935695-8e2faac0-1f46-11e8-87e6-2ce1710608da.png)

## Steps to reproduce:  
- Launch VS Code
- Open Untitled-1.py from the attached archive below
[project.zip](https://github.com/Microsoft/vscode-python/files/1777567/project.zip)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 2295)|
|Memory (System)|11.89GB (6.08GB free)|
|Process Argv|D:\Program Files\VSCode\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
orclapex-autocomplete|apn|0.0.2
open-html-in-browser|cod|0.1.21
bracket-pair-colorizer|Coe|1.0.15
xml|Dot|1.9.2
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.8.7
scoper|Gru|0.0.5
beautify|Hoo|1.3.0
python|ms-|2018.1.0
debugger-for-chrome|msj|4.1.0
python-docs|Muk|0.8.3
autodocstring|njp|0.2.0
vscode-code-outline|pat|0.0.13
java|red|0.20.0
guides|spy|0.9.1
open-in-browser|tec|1.1.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.2
vscode-todo-highlight|way|0.5.11
plsql-language|xyz|1.1.2
html-css-class-completion|Zig|1.17.1

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment]
Here is the file for easier copy-pasting:

```py
a = 10             # 0 space indent
b = 5              # 0 space indent
if a > 10:         # 0 space indent
    a += 1         # 4 space indent      delta 4 spaces
    if b > 5:      # 4 space indent
        b += 1     # 8 space indent      delta 4 spaces
        b += 1     # 8 space indent
        b += 1     # 8 space indent
# comment line 1   # 0 space indent      delta 8 spaces
# comment line 2   # 0 space indent
# comment line 3   # 0 space indent
        b += 1     # 8 space indent      delta 8 spaces
        b += 1     # 8 space indent
        b += 1     # 8 space indent
```

There are 2 deltas of 4 spaces, and 2 deltas of 8 spaces. The indentation detector should detect 4 spaces when there is a tie in the delta counts.
