### ISSUE TITLE
TypeScript Duplicate Function False Error

### ISSUE THREAD

**Issue by LilithTundrus** [Microsoft/vscode#44990]
- VSCode Version: 1.20.1
- OS Version:  Windows 10 Pro For Workstaions 1709

Steps to Reproduce:
1. Write a TypeScript enum and then write a function

Example that causes the issue:

```typescript
enum AlertLevel{
  info,
  warning,
  error
}

function getAlertSubscribers(level : AlertLevel){
  var emails = new Array<string>();
  switch(level){
    case AlertLevel.info:
       emails.push("cst@domain.com");
       break;
    case AlertLevel.warning:
       emails.push("development@domain.com");
       emails.push("sysadmin@domain.com");
       break;
    case AlertLevel.error:
      emails.push("development@domain.com");
      emails.push("sysadmin@domain.com");
      emails.push("management@domain.com");
      break;
    default:
      throw new Error("Invalid argument!");
  }
  return emails;
}

getAlertSubscribers(AlertLevel.info); // ["cst@domain.com"]
getAlertSubscribers(AlertLevel.warning); // ["development@domain.com", "sysadmin@domain.com"]

```

2. Save
3. Compile using `tsc`
4. Editor underlines functions and enums as being already declared

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@LilithTundrus Where does it say the duplicate symbol is located? You should be able to run `go to definition` to see both locations listed

**Comment by LilithTundrus** [comment]
`go to definition` does not point to anything except for the first definition. After attempting `go to definition` the issue disappears. It seems like it was pulling from another file that had the same function name but this file had been closed. Maybe something to do with the file still being 'open' to VS Code?

**Comment by mjbvz** [comment]
Do you expect there to be two separate files? Do you have a [`tsconfig`]( https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)?

**Comment by LilithTundrus** [comment]
`tsconfig`  was short enough to paste here:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "types": ["node"]
    }
}
```

**Comment by mjbvz** [comment]
Are there two or more ts/js files with definitions of `getAlertSubscribers` in your workspace?

**Comment by LilithTundrus** [comment]
In the folder VS Code has open but the file was close which shouldn't cause the error, correct?

**Comment by mjbvz** [comment]
No, a tsconfig causes all ts file in your workspace to be loaded eagerly into the same project.

Try setting up a `include` or `exclude` rule in your tsconfig to exclude one of the definitions: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
