### ISSUE TITLE
Undoing & redoing after call to TextEditor.edit() does not put the insert point in the correct place

### ISSUE THREAD

**Issue by briankendall** [Microsoft/vscode#44995]
- VSCode Version: 1.20.1
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Create a new typescript extension.

Use the following code for its activation function:

    export function activate(context: vscode.ExtensionContext) {
        let disposable = vscode.commands.registerCommand('extension.editBug', () => {
            let editor = vscode.window.activeTextEditor;
            let position = editor!.selection.active;
            
            editor!.edit((edit: vscode.TextEditorEdit) => {
                edit.insert(position, "test");
            }, {undoStopBefore: true, undoStopAfter: true});
        });

        context.subscriptions.push(disposable);
        
        disposable = vscode.commands.registerCommand('extension.editBugWorkaround', () => {
            let editor = vscode.window.activeTextEditor;
            let position = editor!.selection.active;
            
            editor!.edit((edit: vscode.TextEditorEdit) => {
                edit.insert(position, "test");
            }, {undoStopBefore: true, undoStopAfter: false}).then((success: boolean) => {
                if (success) {
                    let position = editor!.selection.active;
                    
                    editor!.edit((edit: vscode.TextEditorEdit) => {
                        edit.insert(position, "");
                    }, {undoStopBefore: false, undoStopAfter: true});
                }
            });
        });

        context.subscriptions.push(disposable);
    }

... and set the `contributes` field of its package.json file to the following:

    "contributes": {
        "commands": [{
            "command": "extension.editBug",
            "title": "editBug"
        },
        {
            "command": "extension.editBugWorkaround",
            "title": "editBugWorkaround"
        }]
    },
2. Run the extension in a Extension Development Host
3. Create a new file (i.e. Command+N or Control+N)
4. Open the Command Palette, type editBug, and select the editBug command. The text "test" should be inserted into the current document.
5. Undo -- the text "test" is removed
6. Redo -- the text "test" is put back again

Note though that the insertion point is *before* the text "test". It should be after. This is the bug. Further:

7. Create another new file
8.  Open the Command Palette, type editBugWorkaround, and select the editBugWorkaround command. The text "test" should again be inserted into the current document.
9. Undo
10. Redo. Note that this time the insertion point is now after the text "test"

This is because, as is demonstrated in the `editBugWorkaround` command, using two consecutive calls to `TextEditor.edit()` where:
1. The first call inserts the text, creates an undo stop before the edit, but *does not* create an undo stop after
2. The second call inserts an empty string, *does not* create an undo stop before the edit, but does create an undo stop after

... works around the bug demonstrated in steps 1-6.

**Comment by alexandrudima** [comment]
This shares the same root cause as #15761
