### ISSUE TITLE
Untitled Resource SaveAs should default to All Files (*.*)

### ISSUE THREAD

**Issue by jel-massih** [Microsoft/vscode#450]
Experienced on Windows

Its a minor nuisance that when saving a new file, it always defaults to "Untitled-[X].txt" with Save as type set to "Plain Text". Therefore if you specify an extension and dont change the dropdown to all files (or correct type) it will save it like SampleFile.js.txt.

Propose that untitled files default to just "Untitled-[X]" with no extension and save as type set to all files.

Appears to be as simple as removing the mime type suggesestion in [/src/vs/workbench/browser/parts/editor/untitledEditorInput.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/untitledEditorInput.ts#L78)

```javascript 
    public suggestFileName(): string {
		if (!this.hasAssociatedFilePath) {
			let mime = this.getMime();
			if (mime) {
				return suggestFilename(mime, this.getName());
			}
		}

		return this.getName();
	}
```

Currently electron autoappends * . * on "all files", although looks like it was fixed v0.34.2+
Workaround in the meantime is to show no default text

**Comment by jel-massih** [comment]
Alternatively,and preferrably, the save as dialog would function similar to Visual Studio, where the "Save as Type" is not authoritative and is only used when no extension is specified. If an extension is specified it saves it with the specified extension.

**Comment by bpasero** [comment]
+1 for not adding .txt when the untitled file is plain text. However, if you explicitly pick a mode for the untitled file from the status bar, the dialog should provide the picked extension by default.

Unfortunately due to bugs in Electron we need to pick up at least 0.34.2 in order for this to work.

**Comment by bpasero** [comment]
Fixed.
