### ISSUE TITLE
[folding] collapse multi single line comment shortcut

### ISSUE THREAD

**Issue by LanceLovereading** [Microsoft/vscode#45003]
#Hi there, I'm using vscode to write python code. I want to fold comments in editor, but it seems that vscode does not support folding comments of python, neither single line comments(using Ctrl+/) nor block comments(using ALT+SHIT+A).

I searched on the Internet and find this: https://github.com/Microsoft/vscode/issues/11524.
Therefore, I tried it on a JavaScript file. It works perfectly for block comments in JavaScript(/* */ style), but it does support single line comments(// style).

So, is it possible to support multi line single line comment folding for python(hopefully for all language) in future?
@aeschli

**Comment by LanceLovereading** [comment]
I think I find a way to work out this question.
I found this:https://github.com/Microsoft/vscode/issues/31966.
Where @aeschli said:
> The main reason is that our folding strategy is based on indentation only
So I can just add indentation to comments that I want to fold.

**Comment by aeschli** [comment]
Yes, the fold comment feature currently only works if the comment is a folding region based on the indentation.
