### ISSUE TITLE
Show large numbers (e.g. selected chars) with dot separator

### ISSUE THREAD

**Issue by bnbdr** [Microsoft/vscode#45004]
### Issue Type
Feature Request

### Description

The number of selected characters is illegible for long texts:

![image](https://user-images.githubusercontent.com/24456233/36944311-ee51f2cc-1fa1-11e8-99b9-7ee2b91d1e15.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

**Comment by alexandrudima** [comment]
This brings the question of locale. In certain locales, `,` is used as a thousands separator, in other locales, `.` is used.
