### ISSUE TITLE
Cannot set breakpoint on a line with 'await' expression

### ISSUE THREAD

**Issue by futurfutur** [Microsoft/vscode#45009]
VSCode 1.20.1
Windows 10
NodeJS 9.5.0

Starting app script: "nodemon --inspect src/server/index.js --exec babel-node"

Can place breakpoint anywhere in code except lines with  **await** expression.

**Comment by isidorn** [comment]
This is up to the debug adapter to allow breakpoints on some lines. Forwarding to @roblourens to decide if this is as designed

**Comment by roblourens** [comment]
You are transpiling with babel that probably does something weird with sourcemaps. I can look into it if you include a code sample that reproes the issue.
