### ISSUE TITLE
[HTML] server contains invalid implementation of applyEdit

### ISSUE THREAD

**Issue by idanarye** [Microsoft/vscode#45014]
The protocol has changed to define that [multiple edits can have the same position, and should be applied using the order inside the array](https://github.com/Microsoft/language-server-protocol/commit/005d12dc021b9ea087e4d1fe4915c43fe7860be8). The current implementation in VSCode, however, [is using unstable sort](https://github.com/Microsoft/vscode/blob/7a2065f582e14bd6ab4bc2ee86fcdbedf008a9b9/extensions/html/server/src/utils/edits.ts#L11) - meaning the order they will be applied in will be arbitrary.

Specifically, with one equivalence class TypeScript's current implementation of `sort` will reverse the array - which is exactly the opposite of what the specs specify.

To be compliant with the specs, VSCode must use stable sort on the edits.

**Comment by jrieken** [comment]
I believe this is @dbaeumer or @aeschli and not the extension api. Fyi, for stable sorting there is `arrays#mergeSort

**Comment by dbaeumer** [comment]
@idanarye VS Code offers API for extension to apply edits to an open buffer. When this API is called the editor itself sorts the array using a stable sort algorithm as defined in the LSP spec. 

See: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5556
