### ISSUE TITLE
large .TS file gets continuosly corrupted in the same way 

### ISSUE THREAD

**Issue by c69** [Microsoft/vscode#45013]
I have a large (over 9000 lines) typescript file, and it get corrupted like every 15 minutes :( without showing in `git status` that it was modified.

Some lines get replaced with junk character, ending is trimmed.
I suspect this might have something to do with TS plugin, but cannot prove it in any other way than - "when this file was .js for more that half a year - such things were not happening"

- VSCode Version:
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
Version	10.0.16299 Build 16299

Steps to Reproduce:
1. Wait 10-15 minutes.
2. Bam...

Does this issue occur when all extensions are disabled?: Not checked.

**Comment by mjbvz** [comment]
@c69 Please first try disabling all extensions to see if one of those is causing this issue

**Comment by c69** [comment]
ok, I tried with `code --disable-extensions`

Step 1:
save the file, close vs code

Step 2:
`git status` - no changes
`type file.ts` - looks good

Step 3:
launch `code --disable-extensions`
open file - it is corrupted.
`type file.ts` - corrupted
`git status` - no changes :(

**Comment by c69** [comment]
As a "counter example":

without launching VSCode - for several minutes
 `type file.ts` - all good
 launch application with `ts-node` - all good
`git status` no changes

**Comment by mjbvz** [comment]
What is the file encoding? Can you provide a screenshot of the file corruption?

**Comment by c69** [comment]
Encoding is utf-8, the error has not been reproducing for last 10 hours or so, but before it was lines of "black diamond with question mark" characters, like the ones below.

�����������

**Comment by c69** [comment]
ok, the issue is back.
there are 5 places in file where its corrupted.
in one place its 276 characters, in another - 414 broken characters added (all in same line).

<img width="615" alt="corrupted_file_ts_vscode" src="https://user-images.githubusercontent.com/2457462/37185022-521020fa-230c-11e8-877e-136dc5126d71.png">

**Comment by c69** [comment]
yes, I forgot to add that - most of the strings in this file are template literals (in order to simplify escaping of quotes).

**Comment by c69** [comment]
this stopped happening since updating to: 

Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by mjbvz** [comment]
Ok, please let me know if you start seeing this again
