### ISSUE TITLE
Windows - Integrated Terminal running Ubuntu resets white to blue (ansiBlue)

### ISSUE THREAD

**Issue by tomjaimz** [Microsoft/vscode#45015]
- VSCode Version: 1.20.1
- OS Version: Windows 10.0.16299.24

I have tried reinstalling VS Code several times and have also completely removed Bash and installed Ubuntu from the Microsoft Store.  I have wiped both my AppData\Roaming\Code and my .vscode directories.

Whenever my Bash terminal within the Integrated Terminal of VS Code encounters a colour and is supposed to return to white, it returns instead to blue.  Then anything that is supposed to be blue is white.  The only way around it I have found is to defined ansiBlue as a white colour in the user settings (which means that then my terminal cannot display blue correctly).

Running` echo -e "\e[37m"` will also get me back to white, but as soon as the system encounters another colour code, and then a reset, it's back to blue.  Most tellingly, `echo -e "\x1b[0m"` takes me from white to blue.

Here is a simple example:

![blue](https://user-images.githubusercontent.com/2597928/36947147-73ec68d8-1fc8-11e8-95df-e60190b4601a.png)

This does not happen when running Ubuntu/Bash from outside of VS Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/40327
