### ISSUE TITLE
Code navigation broken when using modules in index.js files

### ISSUE THREAD

**Issue by jarshwah** [Microsoft/vscode#45010]
### Issue Type
Bug

### Description

When modules are defined in `index.js` files, code navigation fails. You can't cmd+click to navigate to the defintion, or cmd hover to peek. Code navigation correctly works when the file name is used.

Please see [vscode-repro.zip](https://github.com/Microsoft/vscode/files/1778493/vscode-repro.zip), which is a standard create-react-app ejected, with an additional `src` folder, and that folder is added to webpack `resolve.modules`. I'm unable to cmd+click on `import Two` from within `One/index.js`.

The folder layout of components is like this:

<img width="199" alt="layout" src="https://user-images.githubusercontent.com/541083/36945951-67d5b860-2009-11e8-9d39-8b7ebef2baca.png">

The `jsconfig.json` file I'm using in its entirety (I've iterated on this file many times tonight) is:

```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "jsx": "react",
    },
    "include": [
        "src/**/*",
    ],
}
```

If I switch `compilerOptions.module` to `es6`, then code navigation works provided I change the import to reference the filename:

`import Two from 'components/Two/index`

Is there a way to make code navigation work, using absolute paths (as webpack allows) when components are defined in an `index.js` file? No incantation I can come up with or search for has worked.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.15
xml|Dot|1.9.2
gc-excelviewer|Gra|2.0.20
beautify|Hoo|1.3.0
Ionide-fsharp|Ion|3.17.2
swift|Kas|0.0.3
vscode-ios-common-files|Ort|1.0.4
vscode-docker|Pet|0.0.25
code-settings-sync|Sha|2.8.7
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.1
project-manager|ale|0.24.0
vscode-icontheme-nomo-dark|be5|1.3.5
npm-intellisense|chr|1.3.0
regex|chr|0.1.0
vscode-svgviewer|css|1.4.3
whitespace-plus|dav|0.0.5
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
pgsql|dou|0.1.0
gitlens|eam|8.0.2
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
git-project-manager|fel|1.4.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.0
add-new-line-to-files|jdf|0.1.1
saltstack|kor|0.0.5
restructuredtext|lex|51.0.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
python|ms-|2018.1.0
azure-account|ms-|0.3.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.1.0
vscode-icons|rob|7.20.0
partial-diff|ryu|0.5.1
final-newline|sam|0.3.2
whitespace|san|0.0.4
preview-vscode|sea|1.4.2
vscode-sql-beautify|sen|0.0.4
autoimport|ste|1.5.3
shellcheck|tim|0.3.0
org-mode|too|0.5.0
expand-selection-to-scope|vit|0.2.0
jinja|who|0.0.8
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Try setting your baseUrl to `"baseUrl": "./src/"`. This fixed the problem when I tested it

`"checkJs: true` is also useful for tracking down these sort of issues

**Comment by jarshwah** [comment]
Thank you @mjbvz I felt I'd tried that already. At first attempt it didn't work, but then reloading the file seems to pick up the change, and then navigation works correctly.
