### ISSUE TITLE
Bottom border of all tabs

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#45018]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

What rule do we have for bottom border of ALL TABS color customization?

I need to separate all the tabs from my editor:

![image](https://user-images.githubusercontent.com/24613274/36947816-d1a7279a-1fd9-11e8-9d3c-019fb35cdbf5.png)

And it seems, that we don't have such rule.
There are "active tab", "inactive tab", "focused tab", "unfocused tab", etc. etc...
But there is no rule for border of ALL tabs.

**Comment by bpasero** [comment]
`"editorGroupHeader.tabsBorder"`

**Comment by user3323** [comment]
@bpasero , thanks!

I think it would be good to create a topic in the VS Code's Guide, where all rules will be shown on screenshots or gifs. So the users wouldn't have a need to try everyone on themselves.
