### ISSUE TITLE
jump to declare error

### ISSUE THREAD

**Issue by stormzy** [Microsoft/vscode#45029]
### Issue Type
Bug

### Description

language: C;
ex.  :   
int main()
{
    int    a, b;  // this is the declaration
    while (some_bool) {
       b = 10;   // press F12 on b, cannot jump to the declaration
    }
}
 
in this condition,  when I press F12 in b, cannot jump to the declaration;
   
### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|Memory (System)|7.87GB (3.15GB free)|
|Process Argv|D:\Program Files (x86)\VSCode-win32-x64-1.20.1\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0

</details>
Reproduces without extensions

**Comment by kieferrm** [comment]
This is an issue with the C++ extension. Pls file the issue here: https://github.com/Microsoft/vscode-cpptools/issues Thanks a ton!
