### ISSUE TITLE
Intellisense not triggering after some emmet modifiers

### ISSUE THREAD

**Issue by pushqrdx** [Microsoft/vscode#45028]
I am trying to implement emmet functionality inside typescript template literals yet after certain emmet modifiers like `+`, `*` or `>` followed by anything Intellisense returns `no suggestions` *it doesn't show whatever the server returns*. Before i thought the issue is related to the typescript template server, _hence the issue here  #44994_, yet i have managed to encounter the same behavior regardless.

I have put together an [extension](https://github.com/pushqrdx/granular) that echoes whatever line the cursor is on so you can reproduce the behavior explained above with this code...

```
template() {
	return html`
		i am cool

		div*50
		div+li
		div>li
	`
}
```

notice how `ctrl+space` will trigger completion in case of first line, while not triggering if the cursor is placed at the end or after any of the modifiers. This affects enabling proper emmet completions in extensions.

Picture:

![image](https://user-images.githubusercontent.com/25884937/36957033-432f2416-203a-11e8-90f4-2a29ec618c82.png)

**Comment by mjbvz** [comment]
I believe your completion needs to include the range of the entire abbreviation, either:

```js
range: new vscode.Range(position.line, position.character - line.trim().length, position.line, position.character)
```

or by using the `textEdit` property on `CompletionItem`. Otherwise it will be filtered out in many cases for not matching the current word

**Comment by pushqrdx** [comment]
@mjbvz Well, This actually works, thanks so much for you attention. However, i have 1 more question please. in the same code i provided above why doesn't `provideCompletionItems` get called every keypress instead every 2 key presses ?, is there an explanation for that ?

You can replicate that by typing any text and watch the completion list updating every 2 key presses.

**Comment by ramya-rao-a** [comment]
> provideCompletionItems doesn't get triggered at all with numbers after the modifier.

If you want completions to be triggered after numbers, you need to add the numbers as trigger characters when registering the completion provider

**Comment by pushqrdx** [comment]
@ramya-rao-a What about `provideCompletionItems` getting called every two key presses, is there an explanation for that ?

**Comment by ramya-rao-a** [comment]
That is because you are returning an array of CompletionItems instead of a CompletionList.
See https://code.visualstudio.com/docs/extensionAPI/vscode-api#CompletionItemProvider

When you return an array of CompletionItems or a CompletionList with `isIncomplete` set to `false`, then VS Code doesnt call your completion provider for every keystroke. VS Code will only call your completion provider once it has filtered out the results you sent previously.

If you return a CompletionList with `isIncomplete` set to `true`, then VS Code will call your completion provider for every keystroke

**Comment by ramya-rao-a** [comment]
@pushqrdx I am closing this issue as your concerns have been addressed
