### ISSUE TITLE
VSCode Inserting Table of Contents for MD Files in the Middle of the File

### ISSUE THREAD

**Issue by rafidka** [Microsoft/vscode#45022]
I was writing the following a simple MD file using VSCode:

```md
# Angular
## Pros
- Full framework, including modules for HTTP, routing, etc.
- Material library seems to be good.
- Integrated with TypeScript.
```

By the time I add the word `Angular` before `Material` in the second point, the screen starts showing the text "Table of Contents (up to date)":

![image](https://user-images.githubusercontent.com/442447/36948377-eddc0f7a-1f8e-11e8-93a3-fe949bca71ee.png)

Once I click save, the text automatically changes to:

![image](https://user-images.githubusercontent.com/442447/36948391-0ea23fcc-1f8f-11e8-8912-a11bfd4ad5d4.png)

I ensured that the content got actually changed by catting the content in bash.

The problem seems to happen when I insert the word `Angular` only, so it seems related to the fact that the first heading is `#Angular`.

Hope this helps.

**Comment by mjbvz** [comment]
This is caused by one of your extensions, probably one of the markdown related ones. Please file the issue against them
