### ISSUE TITLE
launching the debugger in tmux never works first time

### ISSUE THREAD

**Issue by Mellbourn** [Microsoft/vscode#45025]
I have the setup that was described by João Moreno (@joaomoreno) in his blog post https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41
Whenever I open a terminal tab in VS Code, i enter a tmux session (often attaching to an already present tmux session)
I love this setup! Among other things, it allows all the window control of tmux and it enables me to restart VSCode without losing my terminal session.

Debugging has worked fine in this setup for a long time. With the setting "console": "integratedTerminal", the debugger starts inside the tmux shell, which is just what I want.

After 1.20.0, this stopped working for me.  When I start debugging by pressing F5, the debug command seems to flash briefly in the terminal tab, then it shows tmux. But the debugging never starts. 
This problem has been partially fixed by #43683!

However, even after this fix, the following problem remains in the insiders build:

Debugging never works the first time I try to run the debugger (when the integrated terminal has number “1” and is called “sh”), the only thing that happens then is a quick flash of the debug command and that another terminal is created (“2: Node Debug Console”).
Once the “2:Node Debug Console” exists, I can successfully run the debugger.

Thanks for an otherwise great product!

- VSCode Version: 1.21.0-insider 76a4a71434d6cdee69fa1d8bdc7533d09598d53 2018-03-02T11:45:30.531Z
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Have the tmux setup described in the blog post
2. Have a `launch.config` with `"console": "integratedTerminal"` (which worked previously)
3. Hit `F5`
4. A new terminal is created, but the debugger never starts. After a while, the debugging times out with the dialog `Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target.: connect ECONNREFUSED 127.0.0.1:5829).`
5. Dismiss the dialog by hitting `Cancel``
6. Hit `F5`
7. Debugging starts as ususal

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@could you please try the latest Insiders? 

BTW, I've filed https://github.com/Microsoft/vscode/issues/45300 for the blank drop down.

**Comment by Mellbourn** [comment]
@weinand Yes, now it works perfectly!

Thank you!

**Comment by weinand** [comment]
Thanks for verifying this. I'll add the "verified" label.
