### ISSUE TITLE
Npm script runner: file attribute not recognized

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#45023]
The task schema defined in the file and the one defined in the code mismatch.
![image](https://user-images.githubusercontent.com/172399/36948636-1184d714-1fde-11e8-8260-1880cff6e9c7.png)

**Comment by dbaeumer** [comment]
![capture](https://user-images.githubusercontent.com/1931590/37043596-5012491a-2161-11e8-9f9f-521b86b8b39a.png)
