### ISSUE TITLE
debug node is error

### ISSUE THREAD

**Issue by kingangelAOA** [Microsoft/vscode#45037]
- VSCode Version: 1.20.1 (1.20.1)
- OS Version: Mac 10.13 (17A405)

Steps to Reproduce:

1. debug node 
2. 
```js
"configurations": [
        {
            "name": "Ahri",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/bin/www",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/babel-node",
            "runtimeArgs": [ "--inspect" ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": true,
            "outFiles": ["${workspaceRoot}/dist"]
        }
    ]
```
3. Error: The module '/Users/kingangel/work/node/Ahri/node_modules/tcp-check/build/Release/tcpCheck.node'
module.js:691
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 59.

ps: zsh  is ok

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Forwarding to @roblourens and @weinand since this is a node issue
@kingangelAOA please provide more details on how to reproduce this. Is this even ar error or expected behavior? Can you share your repository so we can actually reproduce?

**Comment by weinand** [comment]
@kingangelAOA that's a problem with your program. You are using the node module "tcp-check" that contains native code that was built against a different version of node.

In addition: use of the "outFiles" attribute is wrong. It needs a glob pattern. So use something like `"outFiles": [ "${workspaceRoot}/dist/**/*.js" ]`.
