### ISSUE TITLE
Viewlet: header gets updated for each view within

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45033]
Steps to Reproduce:

1. add a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/selectBox/selectBox.ts#L69)
2. open the debug view

=> the selectbox is created 4 times for each view within

I find that weird, I would only expect the header of a viewlet to change when there is a transition from 1 view to many views or vice versa. And I would possibly not expect this on first creation time of the view where its already known how many views are being added.

**Comment by isidorn** [comment]
The issue here is `panelViewet` updates the title area whenever a split view is added.
However this is only needed for the explorer (as some actions can move to the title area).
So I have pushed a fix for this to be only done for the explorer viewlet
@sandy081 please reveiw

**Comment by sandy081** [comment]
@isidorn View headers and title area are updated depending on the number of views. They are a pair and to be invoked together. I think moving `updateTitleArea` away from it makes it disconnected and broken. 

[updateHeaders](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/panelViewlet.ts#L320) does it smarty by checking if there is a single view or not. `updateTitleArea` should also do the same.

I would suggest to combine them into single method and do the updates?

**Comment by isidorn** [comment]
@sandy081 thanks for feedback. 
I think `updateHeaders` and `updateTitleArea` can not be moved to a single method since `updateTitleArea` needs to be called when transitioning in and out of single view mode and that is not the case with `updateHeaders`. Still I think I covered some of your concerns with the attached commit.

Feel free to change it if you do not like my approach.

**Comment by sandy081** [comment]
@isidorn your argument makes sense. New change looks good to me.

**Comment by bpasero** [comment]
@isidorn the SelectBox is created each time I open the debug view but never disposed it seems. There maybe more things leaking when switching views in the title area, I have not checked.

**Comment by isidorn** [comment]
@bpasero yes that is because I am not caching my debug actions which I plan to tackle as part of this debt item https://github.com/Microsoft/vscode/issues/46867. However this is not related to the main issue thus closing this one
