### ISSUE TITLE
the Extension Icon is missing

### ISSUE THREAD

**Issue by zphhhhh** [Microsoft/vscode#45036]
- VSCode Version: 1.20.1
- OS Version: windows 10 64bit

![image](https://user-images.githubusercontent.com/17380627/36963144-0d672452-208d-11e8-92a8-fef13868504d.png)

Steps to Reproduce:

1. reinstall the vscode
2. open

Does this issue occur when all extensions are disabled?: Yes

By `Ctrl+Shift+P` and `Show installed extensions` the ext icon will come back, but click Exploror or Search, the icon will miss again.

**Comment by sandy081** [comment]
@zphhhhh I think you might have hidden the Extensions activity group. You can get it back permanently by doing as follows:

![image](https://user-images.githubusercontent.com/10746682/37025703-b7726b60-212c-11e8-8ccd-a057c8bd3198.png)
