### ISSUE TITLE
autocomplete suggest "colg" instead of "div.col"

### ISSUE THREAD

**Issue by IronGhost63** [Microsoft/vscode#45032]
- VSCode Version: 1.20.1
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. edit html file
2. type `div.col` autocomplete will suggest `colg` (emmet abbr) as first item instead of `div.col`
3. if you tab on colg, It got translated to `<div class="colg"></div>` which is also wrong.

`div.col` should be translated/suggest to `<div class="col"></div>` not `<div class="colg"></div>`

![screen recording 2018-03-05 at 12 09 pm](https://user-images.githubusercontent.com/7050540/36958464-94cd057a-206e-11e8-89b1-19212334aa41.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Thanks for reporting @IronGhost63!

Until we get a fix out for this, you can use a workaround which is to add the below in your settings
`"emmet.showAbbreviationSuggestions": false`

You will still get a single Emmet completion for what you typed, but the extra ones wont show up.

**Comment by ramya-rao-a** [comment]
@IronGhost63 The fix will be out on Monday's [Insiders](https://code.visualstudio.com/insiders) build
