### ISSUE TITLE
终端不能自动定位到项目所在的目录 

### ISSUE THREAD

**Issue by leiyinghao** [microsoft/vscode#45034]
### Issue Type
Bug

### Description

终端不能自动定位到项目所在的目录 
打开项目后下面的[终端]控制台无法跟随切换路径到项目的根目录

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_467058|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
solargraph|cas|0.12.0
ruby|gro|0.0.6
Go|luk|0.6.77
python|ms-|2018.1.0
azure-account|ms-|0.3.1
heroku-command|pko|0.0.8
Ruby|reb|0.17.0
vscode-lightning-linter|sza|0.7.0
python|tht|0.2.3
vscode-meteor|vuh|0.1.1

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
Sorry this issue seemed to have got lost somehow, it's super stale now so closing
