### ISSUE TITLE
.pylintrc "enable=..." has no effect

### ISSUE THREAD

**Issue by erikthorstenson** [Microsoft/vscode#45035]
- VSCode Version: 1.20.1
- OS Version: Xubuntu 16.04

Steps to Reproduce:

1. Putting "python.linting.pylintArgs": ["--enable=F,E,W,R,C"] in .vscode/settings.json has desired effect
2. Putting "enable=C,R,W,E,F" in local .pylintrc has **no effect**. (To make sure that the .pylintrc file is being used I tried doing "disable" of the same categories, which had the the desired effect.

In other words: "enable" statement in .pylintrc seems to be neglected of overruled by default parameters. Which is not in accordance with the following documentation; https://code.visualstudio.com/docs/python/linting

**Comment by tsalinger** [comment]
I moved this issue the to python extension's repo. Please continue the discussion there:
https://github.com/Microsoft/vscode-python/issues/949
