### ISSUE TITLE
[pug] [syntax highlight] buffered comment color

### ISSUE THREAD

**Issue by yukulele** [Microsoft/vscode#45044]
- VSCode Version: 1.20.1
- OS Version: MacOS 10.13.3

Steps to Reproduce:

1. use buffered block comment (`//`) in pug file (`string.comment.buffered.block.jade`)
2. color is the same as attribute value making reading difficult (tested with different themes)

Does this issue occur when all extensions are disabled?: Yes

Color should be the same as unbuffered color

**Comment by aeschli** [comment]
```
//- an unbuffered comment
// a buffered comment


input(
  type='checkbox'
  name='agreement'
  checked
)
```
![image](https://user-images.githubusercontent.com/6461412/37029191-ce16a3d6-2136-11e8-8821-4a2ee56dccf1.png)

@yukulele I would 'blame' the pug grammar here as 'string.comment.buffered.block.jade' matches to the string color in almost all the themes. But maybe they did that intentionally. Please file a change request here: https://github.com/davidrios/jade-tmbundle

Note, you can also customize the color in the settings:
```json
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": "string.comment.buffered.block.jade",
				"settings": {
					"foreground": "#0000FF"
				}
			}
		],
	}
```

**Comment by yukulele** [comment]
thanks
https://github.com/davidrios/jade-tmbundle/issues/88
