### ISSUE TITLE
cpptools extension load slowly

### ISSUE THREAD

**Issue by chongchai** [Microsoft/vscode#45041]
### Env 
- VSCode Version: 1.20.0
- OS Version: windows 7
- extension installed: ms-vscode.cpptools 0.14.6

### My Case
I open a c++ project and press F5 to debug. But after pressing F5,  it needs to wait 20 seconds to start debug process. So i check the startup performance and find the ms-vscode.cpptools use 20s to activate. I don't know whether it is normal.

### Startup Performance Measurement : 
 OS: win32 (6.1.7601)
 CPUs: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2394)
 Memory (System): 3.99GB (0.97GB free)
 Memory (Process): 199.38MB working set (199.45MB peak, 183.18MB private, 42.98MB shared)
 VM (likelyhood): 0%
 Initial Startup: false
 Screen Reader Active: false
 Empty Workspace: false
 
 
 | (index) | Topic | Took (ms) | 
 | -- | ----- | --- |
 | 0 | "[renderer] window.loadUrl() => begin to require(workbench.main.js)" | 423 |
 | 1 | "[renderer] require(workbench.main.js)" | 707 | 
 | 2 | "[renderer] create extension host => extensions onReady()" | 565 | 
 | 3 | "[renderer] restore viewlet" | 46 | 
 | 4 | "[renderer] restore editor view state" | 0 | 
 | 5 | "[renderer] overall workbench load" | 196 |
 | 6 | "------------------------------------------------------" | 
 | 7 | "[main, renderer] start => extensions ready" | 1726 | 
 | 8 | "[main, renderer] start => workbench ready" | 1350 | 

 | (index) | startup | codeLoadingTime | activateCallTime | activateResolvedTime | activationEvent | 
 | -- | ----- | --- | --- | --- | --- |
 | vscode.emmet | true | 147 | 6 | 0 | "*" |
 | vscode.git | true | 186 | 24 | 0 | "*" |
 | vscode.merge-conflict | true | 26 | 4 | 0 | "*" | 
 | ms-vscode.cpptools | true | 240 | 26 | 21300| "*" |

Steps to Reproduce:

1.  install ms-vscode.cpptools 0.14.6
2. open a cpp file
3. execute task "startup performance" to check the cpptools plugin activation stats

**Comment by tsalinger** [comment]
This sounds more like a cpp extension issue.
As I can see, you already opened an issue in their repository.
Please reopen this issue, if it should turn out to be VS Code specific.
