### ISSUE TITLE
Allow keybindings.json on .vscode folder.

### ISSUE THREAD

**Issue by eduardo-costa** [Microsoft/vscode#4504]
If I want to share some shortcuts in my project repository I can't configure them inside `.vscode` and commit to my team.
It would be nice to have the same behavior as `.vscode/settings.json`

**Comment by alexandrudima** [comment]
@eduardo-costa There are two reasons we don't do this and why I think we shouldn't:

 - keybindings are more "personal" than settings. Right now, we have user level settings and workspace level settings. Workspace level settings overwrite the user level settings. This mostly makes sense (when not abused :) ).

- `keybindings.json` is not cross-OS, nor cross-keyboard layouts. On the Mac, the modifiers `cmd+`, `ctrl+`, `shift+` and `alt+` are available, while on Windows the modifiers `ctrl+`, `shift+`, `alt+` and `win+` are available. I don't think it is worthwhile to complicate `keybindings.json` with alternatives for other OSes.

That being said, it is actually very easy to create a VS Code extension that contributes only `keybindings`, making it super easy to share a list of keybindings. See for example https://github.com/Microsoft/vscode-sublime-keybindings

**Comment by eduardo-costa** [comment]
Fair enough!
Thanks!
Em 21/03/2016 13:09, "Alexandru Dima" <notifications@github.com> escreveu:
