### ISSUE TITLE
How can I control the ordering of explorer trees?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45053]
I have an extension that contributes some trees in the explorer, some of which are much more important than others. I can't find a way to force the ordering of these - the "important" one always seems to come last.

I tried registering them in a different order but it didn't help. I tried hiding/showing one (using contexts) to see if that would force it to the bottom, but it didn't.

In my case, the "important" tree that I want above the others is hidden/shown based on some criteria, so I need to be able to hide it and then show it later without it having to be last.

**Comment by sandy081** [comment]
@DanTup A user can change the order by drag and drop. Currently there is no way for extension author to specify the order. They should come in the order they are registered. Let me know if you do not see this?

**Comment by DanTup** [comment]
@sandy081 Ah, didn't know the user could change them. When you say registered - you mean in Code and not in the `package.json`? I'll test again and let you know.

**Comment by DanTup** [comment]
Registration order in code doesn't seem to do it:

![Ordering](https://user-images.githubusercontent.com/1078012/37027316-e66793a4-2128-11e8-8df2-b3efb7d22950.png)

Though note that I use context values to toggle visibility of them (so dependencies was visible to the user before the outline).

**Comment by sandy081** [comment]
> When you say registered - you mean in Code and not in the package.json?

In Package.json

**Comment by DanTup** [comment]
@sandy081 The Flutter Outline view is already the first one in my packages.json:

```js
"views": {
	"explorer": [
		{
			"id": "dartFlutterOutline",
			"name": "Flutter Outline",
			"when": "dart-code:flutterProjectLoaded && dart-code:showFlutterOutline"
		},
		{
			"id": "dartPackages",
			"name": "Dependencies",
			"when": "dart-code:dartProjectLoaded && !dart-code:hidePackageTree"
		}
	]
},
```

**Comment by sandy081** [comment]
Ok, I will accept this as a bug to show the views in the order they are registered.

**Comment by DanTup** [comment]
@sandy081 Still seeing this the wrong way in Insiders dated today. Any ideas?

![bad](https://user-images.githubusercontent.com/1078012/37605559-57c06d66-2b8b-11e8-9d01-68dca1511eff.png)

**Comment by sandy081** [comment]
@DanTup Can you please do following:
- uninstall/disable the extension 
- Refresh VS Code to have explorer without those views
- Refresh VS Code again which will override the local storage
- Install/Enable the extension
- Check if the views are in the right order

**Comment by DanTup** [comment]
@sandy081 The extension isn't installed in my Insiders build, and the windows I tested in is the dev host. I tried:

- Closing all instances of Code
- Re-opened Insiders
- Confirmed the extension is not installed
- Opened extension source Code
- Pressed F5 to launch the dev host running the dev build of extension
- Verified order is still bad

Note: I'm registering and displaying the trees in the opposite order, but I wanted the Flutter Outline (shown later) to still appear above the dep tree (which is rendered early).

**Comment by sandy081** [comment]
> I'm registering and displaying the trees in the opposite order, but I wanted the Flutter Outline (shown later) to still appear above the dep tree (which is rendered early)

Order of the trees depend on how to register them in `package.json`. It does not matter when they are displayed.

@DanTup Can you please try it on insiders by installing the extension?

**Comment by DanTup** [comment]
@sandy081 Aha, installing from VSIX it worked!

![installed](https://user-images.githubusercontent.com/1078012/37641925-57071f04-2c13-11e8-986c-4bdae32c37c4.png)

Why does it behave different when running in the extension dev host?

**Comment by sandy081** [comment]
@DanTup I guess the local storage cached the order. May be clearing the local storage will help.

**Comment by DanTup** [comment]
@sandy081 Actually, looks correct now since I installed/uninstalled, so maybe that cleared something. Thanks for the help!
