### ISSUE TITLE
github 2fa broken in the latest update

### ISSUE THREAD

**Issue by aribornstein** [Microsoft/vscode#45058]
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. Try to push changes
2. Prompt for username and password or username and token
3. If password entered vscode push fails
4. If token entered push works but token is not saved meaning it has to be regenerated on every push

Does this issue occur when all extensions are disabled?: Yes

**Comment by tsalinger** [comment]
Duplicates #490
