### ISSUE TITLE
checkJs: true bug for paths from node_modules

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#45051]
#- VSCode Version:1.20.1

Steps to Reproduce:

1. Set checkJs: true in jsconfig.json
2. NOT install jquery
3. In *.js file write:
`import $ from 'jquery';`
4. VSCode does not underline the name of the module.
5. Intellisense does not suggest jquery path.

jQuery is dependence of another module.
vscode not underline each modules from package-lock.json but should.

Same situation, with *.ts file:
1. default config
2. NOT install jquery
3. In *.ts file write:
`import $ from 'jquery';`
4. VSCode underline the name of the module.
5. Intellisense does not suggest jquery path.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lukaszpolowczyk** [comment]
@mjbvz #28165 is about something else.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25280
