### ISSUE TITLE
Add ability to  "Find and Replace" in the selected text only

### ISSUE THREAD

**Issue by basilaiman** [Microsoft/vscode#45050]
In Visual Studio there is a feature to "Find an Replace" in the selected text in a file.
It would be very helpful to implement this feature in VS Code as well.

Thanks

**Comment by tsalinger** [comment]
`CTRL + H` --> select the `find in selection` icon (or `ALT+L`).
Does this work for you?

**Comment by mykolav** [comment]
Hi, @tsalinger 

> CTRL + H --> select the find in selection icon (or ALT+L)

No, this does not work.

Please take a look at the attached recording:
![vscode-issues-45050](https://user-images.githubusercontent.com/14280254/37043366-1faba78c-2169-11e8-82fd-e18a7882962a.gif)


Thank you.
Mykola.

**Comment by chojrak11** [comment]
Same here. 1.21.0. Reproducible in 100% cases. Setting "editor.find.autoFindInSelection": true doesn't help at all (the match count shows all occurrences in the document, Replace All replaces all occurrences in the document).

**Comment by rebornix** [comment]
Thanks for reporting this issue, it only happens when you run `Replace` while running `Find` is good.
