### ISSUE TITLE
External folder rename operation is not reflected in a workspace setup

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#45055]
- VSCode Version: Insiders 1.21
- OS Version: OS X

Steps to Reproduce:

1. Create a workspace with two folders, for instance.
2. Go to an integrated shell and rename one of the workspace folders.
-> Folder rename is not reflected in the Explorer viewlet. Git viewlet is not picking it up either. Navigating to any of the files under the old folder name through Explorer viewlet results in an error.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/29590
Hey Michele

**Comment by michelkaporin** [comment]
@isidorn hey! thought it's a duplicate for sure, but couldn't find it...

**Comment by isidorn** [comment]
@michelkaporin yeah I had a hard time finding it as well.
