### ISSUE TITLE
Expose API for highlighting a portion of the document (as used in document symbol list)

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#45059]
There's a request that I believe was for this at #540 however it's closed as done, but I think only one part of it was done.

When using the document symbol provider, moving through the items with the cursor keys "highlights" the range of that symbol in the editor in the background. I cannot find an API that allows me to provide this sort of highlight myself (outside of the symbol provider).

I have an explorer tree view which is a sort of outline of the code, and as the user moves around it I'd like to highlight the code (I've tried using `reveal` but since it doesn't highlight, it's a bit confusing to the user as the code moves but it's not clear where on the screen the relevant item is).

**Comment by jrieken** [comment]
This can be achieved with editor decorations and theme colors
