### ISSUE TITLE
"Check for updates" shows native dialog in every open window

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#45069]
- MacOS
- "Check for updates" when there are no updates available
- A native prompt ("There are no updates currently available") shows up in every open vscode window, which is annoying because every open window is focused when the dialog appears

This used to show a notification in every window which I think is better.

**Comment by joaomoreno** [comment]
Making it a dialog was @egamma's suggestion.

Showing it on every window is, of course, an issue, which I'll have to promote as a candidate.

**Comment by joaomoreno** [comment]
@roblourens I've pushed this to `release/1.21`. Can you verify the fix today, once a build is out?
