### ISSUE TITLE
Welcome: Overlay could mention new notifications location

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45061]
On this one:

![image](https://user-images.githubusercontent.com/900690/36978972-557bfe72-2086-11e8-9ad6-1294082fedf6.png)

Could put another arrow bottom right to point to notifications location.

**Comment by bpasero** [comment]
@chrmarti PR via https://github.com/Microsoft/vscode/pull/47134

**Comment by chrmarti** [comment]
Great, thanks!
