### ISSUE TITLE
Couldn't start clinet XXX server

### ISSUE THREAD

**Issue by XuVic** [Microsoft/vscode#45070]
### Issue Type
Bug

### Description

When I open JSON file or HTML file, there is error msg which show "Couldn't start clnet JSON/HTML server." Only Ruby client server can work.

Error: spawn C:\Program Files\Microsoft VS Code\Code.exe ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|3.88GB (0.62GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
solargraph|cas|0.12.0
path-intellisense|chr|1.4.2
githistory|don|0.4.0
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
beautify|Hoo|1.3.0
Angular-BeastCode|Mik|5.2.16
vscode-docker|Pet|0.0.25
Ruby|reb|0.17.0
slim|sia|0.1.2

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
Pls provide additional information or file the issue against the extension that causes the issue. Thanks a ton!
