### ISSUE TITLE
Support for updating extensions from CLI

### ISSUE THREAD

**Issue by adamsmith** [Microsoft/vscode#45072]
Similar to the `apm upgrade <package_name>` in Atom, there should be a way to update Marketplace extensions from the command line.

Currently there are `code --install-extension` and `code --uninstall-extension` commands, but no command for upgrading extensions.

**Comment by Thau** [comment]
Hello! I've been checking this issue to make a first contribution, but it seems that `--install-extension` already has that functionality! To test it, I installed an out of `rebornix.ruby` extension from the vsix file and then did this:

```
➜ ./scripts/code-cli.sh --install-extension rebornix.ruby
Found 'rebornix.ruby' in the marketplace.
Installing...
Extension 'rebornix.ruby' v0.17.0 was successfully installed!
```

So... Maybe we should just alias the command, or is this missing any functionality I'm not noticing?

Thanks!

**Comment by joaomoreno** [comment]
@Thau That's what I thought! Good to know. Yeah let's just have an alias for it.

**Comment by sandy081** [comment]
Hmm... Looking at the code, it seems we check if an extension is installed and return if it is.

https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/cliProcessMain.ts#L117

**Comment by Thau** [comment]
@sandy081, as I understand the code (very, very limited understanding!), and after the quick test I did, I would think that check for the extension being installed only returns true if the extension is up to date.

**Comment by sandy081** [comment]
@Thau I don't think so. 

```typescript
function getId(manifest: IExtensionManifest, withVersion?: boolean): string {
	if (withVersion) {
		return `${manifest.publisher}.${manifest.name}@${manifest.version}`;
	} else {
		return `${manifest.publisher}.${manifest.name}`;
	}
}
const isInstalled = installed.some(e => getId(e.manifest) === id);
```

There is no checks on version in the above code.

**Comment by Ankk98** [comment]
Anyone working on this feature?
I am a beginner but would like to work on this issue and contribute.

**Comment by joaomoreno** [comment]
@Ankk98 There's already a PR for it: https://github.com/Microsoft/vscode/pull/45533

**Comment by roblourens** [comment]
This works in a weird way for me -

- Install old version of extension from vsix
- Run `code-insiders --install-extension msjsdiag.debugger-for-chrome`
- `Extension 'msjsdiag.debugger-for-chrome' v4.8.1 is already installed, but a newer version 4.8.2 is available in the marketplace. Would you like to update? Yes(0) | No(1)`
- If I respond `y`, it cancels the install. I have to respond with `0` which is unusual

**Comment by joaomoreno** [comment]
Yeah unfortunately that's the current status of the dialog service in the CLI environment. Needs polish, feel free to file an issue for that.

**Comment by JBallin** [comment]
I'm unsure why this issue was closed @joaomoreno? What is the command to update ALL extensions from CLI (without code opening)? Something like `code --update-extensions`

**Comment by joaomoreno** [comment]
@JBallin This issue was about updating a single extension. Feel free to file an issue to support updating all extensions.

**Comment by JBallin** [comment]
Done. See #56578
