### ISSUE TITLE
Predefined snippet choices - in many lines cut intellisense prompt [bug]

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#45079]
Steps to Reproduce:

Write snippets like this:

	"case-of-reduser": {
		"scope": "javascript,javascriptreact",
		"prefix": "case-of-reducer",
		"body": [
			"case '${2|ACTION_TYPE, ACTION",
			"_TYPE2|}':",
			"return ${3}",
		]
	},

Or this:

	"case-of-reduser": {
		"scope": "javascript,javascriptreact",
		"prefix": "case-of-reducer",
		"body": [
			"case '${2|ACTION_TYPE, ACTION\n_TYPE2|}':",
			"return ${3}",
		]
	}

Where option of choice is in many lines or with `\n`.
When use this, intellicence show cut second prompt:
![snippet-predefined-choices-intellisence-bug](https://user-images.githubusercontent.com/16800535/36992386-08201ac6-20ab-11e8-9abb-7cd40b3b848b.png)

This additional line is added after selecting the second item. You just can not see her in intellisence.

I consider this a bug, because it is possible to create a multi-line predefined-choice in snippets, and intellisence does not adapt to it.

It's probably best that it displays like ... like whole snippets, in an extra field next to the intellisence list.

**Comment by pradeepmurugesan** [comment]
@jrieken I was able to repro the issue and would like to share what I understood as a solution from the above desciption. Let me know If I am getting it right.

Here is my visualization:
![visualization](https://user-images.githubusercontent.com/528317/37529878-8ac3f426-2938-11e8-95a4-f5f4ed45a90c.jpg)

Pradeep.

**Comment by jrieken** [comment]
Yeah, basically have to sanitise the view string before inserting into the DOM make sure the line breaks are replaced

**Comment by pradeepmurugesan** [comment]
Hi @jrieken I did some ground work and navigated to 
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestWidget.ts#L679

But couldn't find the actual place that I need to escape the suggestion content. Am I in the right direction.  Any code pointers would help. Thanks.

**Comment by jrieken** [comment]
Checkout this: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestWidget.ts#L155. That's the `render` function that is being called when an element is being rendered. There is some trickiness because some highlights have been computed already, and when replacing `\n` (the char code) with something longer the highlights need to be adjusted. So, you might find it easier to implement this in the [`HighlightLabel`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/highlightedlabel/highlightedLabel.ts#L52)

**Comment by pradeepmurugesan** [comment]
Hi @jrieken I am sorry, I am kind of confused. Why do we need the highlight here ? 

We planned to sanitize the string that contains the breaks and display it in the view. If I am not wrong
for the attached image we need to display 
```
ACTION
ACTION
  _TYPE2
PRADEE
```
since action ACTION_TYPE2 has a line break we will display the _TYPE2 in next line for the same choice number 2.

How will highlight help for this?  I see HightlightElement helps to match the suggestions as the user types.

Kindly let me know if I am missing something.

**Comment by jrieken** [comment]
> How will highlight help for this? I see HightlightElement helps to match the suggestions as the user types.

It will not help you but will make things more complicated. Based on the text left of the cursor highlights have already been computed (based on the string with newlines), highlights are positions inside the string, and when replacing characters inside that string those position need to be adjusted

**Comment by pradeepmurugesan** [comment]
Sorry @jrieken . I know I am asking too many questions for may be a simple thing, But I think I am kind of lost.. 
Is my assumption right regarding how to show the line breaks ?

```
ACTION
ACTION
  _TYPE2
PRADEE
```

**Comment by jrieken** [comment]
Yeah, I think is we have different things in mind. When a suggestion is having a newline character we *not* have an item with double/tripple/etc hight but should escape the newlines, e.g.

```
ACTION
ACTION\n_TYPE2
PRADEE
```

**Comment by pradeepmurugesan** [comment]
@jrieken Okay now I understand.. So when we replace the line break with \n then the highlight positions will get changed. 

```
data.highlightedLabel.set(suggestion.label, createMatches(element.matches));
```
The above [line](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestWidget.ts#L155) is where the matches are calculated and the highlight is set. 

So can't we pass the escaped string , something like 

```
data.highlightedLabel.set(suggestion.label.replace(/\n/, "\\n"), createMatches(element.matches));
```

Won't the above line calculate the highlight with the escaped position and insert the hightlight span in the correct places ?

P.S. Of course this is not the place to escape, May be we need to escape when we construct the ICompletionItem object. I don't know where is that done. But that might be a good place.

**Comment by pradeepmurugesan** [comment]
@jrieken So this is the problem you are talking about after escaping ?

![screen shot 2018-03-20 at 15 51 28](https://user-images.githubusercontent.com/528317/37662118-a236e174-2c56-11e8-81c8-e877bc2b6482.png)

It highlights from underscore(_) due to the \n..

**Comment by pradeepmurugesan** [comment]
Ah because the createMatches here is acting on the unescaped string taken directly from element. So  Probably escaping it in the ICompletionItem object constructor will get us what we want.
```
data.highlightedLabel.set(suggestion.label.replace(/\n/, "\\n"), createMatches(element.matches));
```
@jrieken Sorry I was thinking aloud.

Let me know your thoughts..

**Comment by jrieken** [comment]
> Won't the above line calculate the highlight with the escaped position and insert the hightlight span in the correct places ?

That's the correct place I would say. We don't want to escape the strings unless we render them (avoid waste). The highlights are already computed but stored in a compact array and only expanded before rendering. So, replace all newlines with `\n` write down the indices and then adjust match-indices that are larger.

**Comment by pradeepmurugesan** [comment]
@jrieken hmmm got it. 

So the complexity is if we have multiple line breaks then the highlighting value will change depending on how many line breaks before that.

**Comment by jrieken** [comment]
Even with one because newline characters have length 1 but an escaped newline character as length 2 - unless you find a single unicode character that prints `\n`.

**Comment by pradeepmurugesan** [comment]
@jrieken Ofcourse even with one.. Cool.. Will try to come up with a fix. Sorry for troubling you to understand the problem.

**Comment by pradeepmurugesan** [comment]
@jrieken I face a problem.. The pre-commit complains about some problem in formatting but not telling the exact problem.

How to get the detailed report ?

![screen shot 2018-03-21 at 17 07 27](https://user-images.githubusercontent.com/528317/37722227-c15279a8-2d2b-11e8-9dc2-0f5a710c71f4.png)

**Comment by prifio** [comment]
This issue related with #46266. 
If insert snippet in indented linet, suggestion.label have extra space and suggestion will like 
```
 ACTION\n    _TYPE2
```
![default](https://user-images.githubusercontent.com/16323654/37731694-e24da4a2-2d53-11e8-82d9-1a2997c84b0c.png)

Now suggestion.insertText equals suggestion.label. I think that it's bad and create "nice" suggestion.label before render - best way to solve this issue.

**Comment by jrieken** [comment]
Instead of rending a newline, the label uses the ⏎-symbol. `\u23CE`

<img width="308" alt="screen shot 2018-06-06 at 16 48 45" src="https://user-images.githubusercontent.com/1794099/41045847-87150aac-69a9-11e8-96f5-5823fb7809cc.png">
