### ISSUE TITLE
Resizing the panel changes the width of the split terminals

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#45074]
Issue Type: <b>Bug</b>

1) Split a terminal
2) Make one terminal much smaller than the other
3) Manually change the height of the panel
-> terminal jump back to be the same width

VS Code version: Code - Insiders 1.21.0-insider (b76a4a71434d6cdee69fa1d8bdc7533d09598d53, 2018-03-02T11:50:18.388Z)
OS version: Darwin x64 16.7.0

Reproduces without extensions

**Comment by Tyriar** [comment]
Pushed to master and release/1.21
