### ISSUE TITLE
Modal dialogs cause windows to seemingly randomly rearrange in z-order

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#45075]
Issue Type: <b>Bug</b>

1) Have a VS Code insider installed that is up-to-date.
2) Open multiple workbench windows and stack them behind each other
3) Use `Check for updates` from the gear in the activity bar

-> A modal dialog pops up with telling me that there is no update. That happens in all windows and the windows are seemingly randomly rearranged in z-order. I.e. the front most workbench window all of a sudden changed under me.

-> Also, I can't simply quit/restart VS Code anymore. I need to walk through all windows and close the modal dialogs because they abort the application shutdown.

VS Code version: Code - Insiders 1.21.0-insider (b76a4a71434d6cdee69fa1d8bdc7533d09598d53, 2018-03-02T11:50:18.388Z)
OS version: Darwin x64 16.7.0

Reproduces without extensions

**Comment by joaomoreno** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/45069.
