### ISSUE TITLE
Intellisense hangs / stops working

### ISSUE THREAD

**Issue by twistedinferno** [Microsoft/vscode#45073]
- VSCode Version: 1.20.1
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Work on react native javascript code for a few hours
2. Intellisense stops working (the 'Loading' tooltip shows of the intellisense but nothing else)

![image](https://user-images.githubusercontent.com/4139336/36983852-5c5a8862-208b-11e8-8294-5ecedbfd7bce.png)

Does this issue occur when all extensions are disabled?: Yes/No (usually it takes three hours of programming to encounter the error...programming react native with vs code without React Native Tools is almost impossible so I have kept that enabled but disabled everything else)

_(the last time it happened I was importing a couple of new libraries...possibly unrelated though)_

**Comment by twistedinferno** [comment]
_(the last time it happened I created a new file but I didn't import any new libraries...again possibly unrelated to the error)_

**Comment by mjbvz** [comment]
A few questions:

- Does this happen for all projects you open, or just one specifically?
- Have you set a custom `typescript.tsdk` value in your workspace or user settings?

Can you also please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by glauberfc** [comment]
I'm having the same problem. 

- Does this happen for all projects you open, or just one specifically? **Yes**
- Have you set a custom typescript.tsdk value in your workspace or user settings? **No**
- TypeScript server logs:
>[Info  - 4:11:43 PM] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 4:11:45 PM] TSServer log file: C:\Users\gferr\AppData\Roaming\Code\logs\20180312T161137\vscode.typescript-language-features_1\tsserver-log-5XNkj3\tsserver.log
[Info  - 4:11:45 PM] Forking TSServer
PATH: C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Android\android-sdk\tools;C:\Android\android-sdk\platform-tools;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Git\cmd;C:\Users\gferr\AppData\Local\Microsoft\WindowsApps;C:\Users\gferr\AppData\Roaming\npm;C:\Users\gferr\AppData\Local\Yarn\bin;;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Oracle\VirtualBox
[Info  - 4:11:45 PM] Started TSServer

**Comment by Wedvich** [comment]
This might be related to #43427 - adding `"typescript.quickSuggestionsForPaths": false` to my user settings worked for me as a temporary workaround.

**Comment by mjbvz** [comment]
@glauberfc Please share the `tssserver.log` file from that output: `C:\Users\gferr\AppData\Roaming\Code\logs\20180312T161137\vscode.typescript-language-features_1\tsserver-log-5XNkj3\tsserver.log`. That file has the verbose logs we need to investigate this issue

**Comment by glauberfc** [comment]
[tsserver.log](https://github.com/Microsoft/vscode/files/1808126/tsserver.log)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22695

**Comment by twistedinferno** [comment]
Hi, I don't use typescript so I doubt that typescript could be the problem?

**Comment by twistedinferno** [comment]
Yes, it does happen with every project (I only use vscode for react and react native based projects)
