### ISSUE TITLE
Custom HTML tag confused by P

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#45082]
Issue Type: <b>Bug</b>

When using an Angular component they often use a custom HTML tag.  

Prime NG, for example, uses `<p-table>` for their table component.

However, probably because of the opening `p`, the entire tag is not scoped as a tag: the `-table` part is mistakenly scoped as `meta.tag.block.any.html entity.other.attribute-name.html`

<img width="444" alt="screen shot 2018-03-05 at 2 56 10 pm" src="https://user-images.githubusercontent.com/835148/36996788-ad68966e-2085-11e8-9e71-6eaa205bdaf8.png">

```
<p-table [value]="people">
  <ng-template pTemplate="header">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Sales</th>

    </tr>
  </ng-template>
  <ng-template pTemplate="body"
               let-person>
    <tr>
      <td>{{person.firstName}}</td>
      <td>{{person.lastName}}</td>
      <td>{{person.gross_sales}}</td>

    </tr>
  </ng-template>
</p-table>
```

VS Code version: Code - Insiders 1.21.0-insider (b76a4a71434d6cdee69fa1d8bdc7533d09598d53, 2018-03-02T11:50:18.388Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.4.2
code-settings-sync|Sha|2.9.0
sort-lines|Tyr|1.4.1
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.1
project-manager|ale|0.24.0
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.8.1
vscode-text-pastry|jkj|1.2.0
svg|joc|0.0.9
Angular2|joh|2.14.0
vscode-icon-theme|jtl|1.6.1
ecdc|mit|0.11.0
HTMLHint|mka|0.4.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
polacode|pnp|0.2.2
stylelint|shi|0.33.0
Align|ste|0.2.0
bootstrap4-vscode|the|4.0.0
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Confirmed. This seems to be a problem in the html grammar. It only happens with `p`left of the dash.

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#79
