### ISSUE TITLE
launch.json's Add Configuration does not activate extension

### ISSUE THREAD

**Issue by WardenGnaw** [Microsoft/vscode#45089]
### Issue Type
Bug

### Description

The vscode-cpptools extension uses a ```completionItemProvider``` to provide launch configuration snippets dynamically per OS. See [here](https://github.com/Microsoft/vscode-cpptools/blob/bd181c3b8f882ba06c1713e3e86fd952582445d5/Extension/src/Debugger/configurationProvider.ts#L168). However, our extension needs to be activated for the provider to work. 

If the user decides to open VsCode without touching a 'c' or 'cpp' file and tries to add a configuration, it does not show the cpptools extensions provided initial configurations. 

We have onDebug as an activation event and we also tested the onDebugInitialConfigurations activation event, but those do not seem to activate the extension when an user selects ```Add Configuration...```. 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|31.92GB (12.99GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0

</details>
Reproduces only with extensions

**Comment by isidorn** [comment]
@WardenGnaw good catch. I have pushed a fix and you can try it out in our insiders build in a couple of days (probably on friday, since our insiders builds are temporarly frozen due to our upcoming stable release). Once you try it out let us know if this fixed the issue for you, thanks
