### ISSUE TITLE
Buggy UI 

### ISSUE THREAD

**Issue by benjamintoofer** [Microsoft/vscode#45087]
### Issue Type
Bug

### Description

The UI starts to flash and render boxes around the menu bar and vertical file tree when it is opened to full screen on mac OS. It's completely fine when it's not in full screen mode

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_4555864|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.28

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@benjamintoofer sounds a lot like https://github.com/Microsoft/vscode/issues/12473 which should be fixed by now. Can you show a screenshot how it looks?
