### ISSUE TITLE
chrome developer tools inside vscode

### ISSUE THREAD

**Issue by gogoIsComing** [Microsoft/vscode#45091]
- VSCode Version: 1.19.1
- OS Version: win 10 pro 64-bit

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No
hey guys i just want to know if there is any way to get google chrome developer tools inside vscode

**Comment by kieferrm** [comment]
Command Palette > Toggle Developer Tools.

**Comment by gogoIsComing** [comment]
@kieferrm thank you , but i don not see my HTML code :
![4](https://user-images.githubusercontent.com/33967218/37034461-06b8d2ac-2152-11e8-9d6f-e1ed9eec2da6.png)

**and i still can not see the errors like chrome**

error window on chrome :
![2](https://user-images.githubusercontent.com/33967218/37034390-be557952-2151-11e8-9e44-8ed633788c6e.png)

error window on vscode :
![3](https://user-images.githubusercontent.com/33967218/37034423-df57ed74-2151-11e8-8684-97464870652f.png)

**Comment by kieferrm** [comment]
I see, you want the CDT functionality inside VS Code for your own code. This is covered in #28263.

**Comment by gogoIsComing** [comment]
@kieferrm thank you , i got it
