### ISSUE TITLE
Do not search for git repositories in ignored directories

### ISSUE THREAD

**Issue by jd-carroll** [Microsoft/vscode#45098]
- VSCode Version: 1.20.1
- OS Version: Windows 10

It appears as though the current implementation of the git source provider will search any directory for child git repositories.  (prob as answer to #38203 & #37947)

The issue is that when I am hacking on a node module, I will often want to `npm link` that project into an other project.  As soon as I do this, the linked project will appear as a repo in the list of git repositories.

Ideally, whatever mechanism used to search for git repositories would also respect the `.gitignore` file.  Since the linked repository appears under `node_modules` this will avoid VS Code from picking up the linked repo in error.

(Admittedly, this is more of an annoyance)

**Comment by joaomoreno** [comment]
There is now a `git.ignoredRepositories` array you can configure.

**Comment by jd-carroll** [comment]
@joaomoreno is it possible to specify blob patterns in the ‘ignoredRepositories’?

**Comment by joaomoreno** [comment]
Not currently, no. Would that help?

**Comment by jd-carroll** [comment]
Yeah, because I will link / unlink projects all the time (randomly) as I’m
working on different projects. And I would like to just do something like:
ignoredRepositories: “node_modules/*”

**Comment by joaomoreno** [comment]
Created https://github.com/Microsoft/vscode/issues/59020
