### ISSUE TITLE
[sass] CSS functions are not being highlighted consistently in CSS and Sass

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4509]
From https://github.com/Microsoft/vscode/issues/1656#issuecomment-199324101

## Dark+

**CSS**
![5053a560-ef39-11e5-9b77-747e5472bbbd](https://cloud.githubusercontent.com/assets/2193314/13926378/4627b170-ef49-11e5-9074-2e3994703c9a.png)

**Sass**
![608fa49c-ef39-11e5-8ef0-553a43b5da0d](https://cloud.githubusercontent.com/assets/2193314/13926373/428b577e-ef49-11e5-82be-85e797179ddd.png)

## Light+

**CSS**
![a1ab8fea-ef39-11e5-8dba-05d26af67bc9](https://cloud.githubusercontent.com/assets/2193314/13926368/378a2e40-ef49-11e5-8561-dbeebef08f4f.png)

**Sass**
![9b5197fc-ef39-11e5-85e4-1f1914587d8c](https://cloud.githubusercontent.com/assets/2193314/13926365/362a1452-ef49-11e5-8bd9-98e7a1566a75.png)

**Comment by aeschli** [comment]
Fixed since scss switched to use the textmate grammar.
scss:
![image](https://cloud.githubusercontent.com/assets/6461412/17367922/434a4b26-5992-11e6-949f-1d6ba7ed25e4.png)
