### ISSUE TITLE
Allow to zoom only the current instance and not all

### ISSUE THREAD

**Issue by jkanchelov** [Microsoft/vscode#45094]
It would be good if you have opened more than one vscode instance and the zooming you've done on it shouldn't affect the other ones.

**Comment by jkanchelov** [comment]
I've tried it, but it would be easier if it comes straight without the need to declare it there. I have the habit to often move the instance from one monitor to another and if they are on different resolutions sometimes there is a need for me to zoom in / out often.

**Comment by vmaruthi** [comment]
Second this request, there are many scenarios where you may want different font size on Different Windows and Instances. Perhaps you can implement in Global as well as local Editor properties. Treat this like a Microsoft Office Document (Word etc) editor feature. Zoom on Window is local to that Instance/Window. If user wants a more permanent setting, it can be done through properties etc.

**Comment by Tchoupinax** [comment]
Hello, 

What are news about this feature ? Up ! :)

**Comment by jkanchelov** [comment]
It could come really handy when #10121 is implemented.

**Comment by mat-m** [comment]
@bpasero : could we reopen this one ? I have multiple monitors with different sizes. When I move an instance, I often zoom in/out to adapt, but I don't want the others to change.

**Comment by jkanchelov** [comment]
I can't agree this should be out of scope request :/

**Comment by TheJim01** [comment]
I actually encountered this just now, and would not have realized it if it had not caused poor zoom performance.

With one editor open, zoom (`Ctrl`+`+`) is snappy, even for large code files.

I opened another project in a separate editor to show something to a co-worker, and zoomed in to make the presentation easier. The editor lagged (I thought the keyboard shortcut had lost configuration for a moment) while it updated both instances.

I can't seem to replicate this with simple files (responsiveness seems to be okay). I also tested word-wrap, and that didn't seem to cause a problem. So maybe it's the explorer tree? It seems to lag a lot more when I had a large number of files in the explorer tree. That's just my observation though.

**Comment by KroanNL** [comment]
This is still an issue or people with different monitor sizes (ie I use my laptop plugged into a monitor. when having multiple editors open, I want to change their fontsize easily and idependently from each other)

**Comment by jkanchelov** [comment]
Its an issue, but once they tagged it with out-of-scope label I guess they won't look at it again 😐

**Comment by benjamin21st** [comment]
lol, `out-of-scope`? I just cannot possibly fathom why would anyone want to zoom all of the instances when they use keyboard shortcuts: if they want to increase size change permanently they can do so through the config. Using a keyboard "shortcut" is usually for quick-temporary actions. And when you have multiple editors open or during a CPU-intensive video conferencing presenting your code to your colleagues/clients, a zoom action can make it sooo slow that reflects badly on both the user and VS Code. 🐌 🐌 🐌 

I implore whoever is in charging of scoping to re-incorporate this into the scope 🙏 
It could enhance so many people's lives. 

Thank you so much and keep up the good work!

**Comment by DaveWelling** [comment]
For anybody that lands here when searching for this issue (as I did).  Go to >Settings>Workspace and search for 'zoom'.  You will find a checkbox called 'Editor: Mouse Wheel Zoom'  that might meet your needs.  It resolved this problem for me (changed editor zoom in one one workspace while leaving the others unaffected).

**Comment by Dophy6** [comment]
> For anybody that lands here when searching for this issue (as I did). Go to >Settings>Workspace and search for 'zoom'. You will find a checkbox called 'Editor: Mouse Wheel Zoom' that might meet your needs. It resolved this problem for me (changed editor zoom in one one workspace while leaving the others unaffected).

This works for me, thanks a lot!!

**Comment by NirajanWEB** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/69881638/95037186-d8d64600-06e9-11eb-9a84-aeddad7d1936.png)

**Comment by NirajanWEB** [comment]
It should work otherwise, Go for setting.js
