### ISSUE TITLE
debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by flyby21** [Microsoft/vscode#45109]
### Issue Type
Bug

### Description

print("hello") 
[-1520033610441.log](https://github.com/Microsoft/vscode/files/1783566/-1520033610441.log)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6200 Six-Core Processor              (6 x 3791)|
|Memory (System)|9.80GB (3.89GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
django-snippets|bib|1.1.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
MagicPython|mag|1.0.12
python|ms-|2018.1.0
jinja|who|0.0.8

</details>
Reproduces without extensions

**Comment by kieferrm** [comment]
Sorry for the trouble. What I see in the log is:
> Activating extension `ms-python.python` failed:  Cannot find module 'untildify'

Let's try if manually deleting the extension and reinstalling it helps.  
1) Quit Code.
2) Go to your home directory and there into `.vscode\extensions`. Delete the python extension.
3) Start Code.
4) Install the python extension.

**Comment by flyby21** [comment]
I went to C:\Program Files\Microsoft VS Code\resources\app\extensions the directory you gave me didnt seem to exist. deleted the python extension and then started code up. All the extensions were still installed. The glitch is still happening. I thought it was an issue with the workbench I noticed a few errors highlighted in the dev tools for it.

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2925 Debug adapter process has terminated unexpectedly

**Comment by flyby21** [comment]
This is a copy of the launch.json file in txt format not sure if i did something wrong. Please remember im very new to python. Deleting the json file only causes python to create a new one. Deleting individual programs in the json file causes errors and redownloading the extension does not fix the problem with being unable to launch the debugger.

[launch - Copy.txt](https://github.com/Microsoft/vscode/files/1799036/launch.-.Copy.txt)

**Comment by kieferrm** [comment]
The extensions for VS Code are installed in a path similar to `C:\Users\flyby21\.vscode\extensions`. Pls exchange the drive letter and the user name accordingly. Inside that directory you should see a directory for the ms-python extension. Delete the that directory (when VS Code is not running). Then restart VS Code. Then install the python extension again.

**Comment by flyby21** [comment]
Thanks very much.
