### ISSUE TITLE
cannot open more than one file at a time!!

### ISSUE THREAD

**Issue by mustafawm** [Microsoft/vscode#45101]
- VSCode Version: Version 1.20.1 (1.20.1)
- OS Version: 10.13.3

Steps to Reproduce:

1. open a project folder (multiple files
2. open one file (_file gets opened in tab_), try opening another file (_replaces first file/tab_)! 
**correction** it doesn't replace the previous tab(s), it just takes over (instead of coming next to them, which is the expected behavior)

Issue persists even when running `code --disable-extensions`

**Comment by mjbvz** [comment]
From the description, I suspect you are opening files in preview mode: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by mustafawm** [comment]
I'm not. I'm aware of the preview mode. I'm double-clicking the files to open them.

Moreover, when `cmd + 1` and `cmd + 2` it does switch between the files which means they are both open, but the tabs are placed under the focused one (instead of next to it).

**Comment by bpasero** [comment]
@mustafawm can you share a screencast or screenshot what you see?

**Comment by mustafawm** [comment]
Double clicking on `AdminController`, `Controller`, then `Home Controller` as you can see the last open file is positioned above the previous ones. 
After that, i'm `cmd + w`ing , and as you can, the previous ones start come to front which means they're open but being overridden by the last opened file.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13101565/37017396-a8a70860-2164-11e8-9bac-c4acca6066ba.gif)

**Comment by bpasero** [comment]
@mustafawm it looks like tabs are disabled, can you run this:

![image](https://user-images.githubusercontent.com/900690/37017860-6d0354e6-2112-11e8-89f0-3bbc7177403b.png)

**Comment by mustafawm** [comment]
That was it. 
> I search for 'tab' keyword in the settings (`cmd + ,`) but the tab visibility is not there
Thanks @bpasero
