### ISSUE TITLE
How to hide context menu commands from command palette?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45119]
I'm contributing some commands to a custom view via `view/item/context` in `packages.json`. As I understand it but they're showing up in the command palette. I had prefixed them with an `_` and also set the `when` condition in `menu/commandPalette` to `false` however they still appear in the command palette:

```
"menus": {
	"commandPalette": [
		{
			"when": "false",
			"command": "_flutter.outline.refactor.dart.assist.flutter.move.down"
		},
		{
			"when": "false",
			"command": "_flutter.outline.refactor.dart.assist.flutter.removeWidget"
		}
```

What's the correct way to hide an item from the palette (these commands are actions on a node in the contributed tree and don't make sense to execute without a node).

**Comment by jrieken** [comment]
> As I understand it but they're showing up in the command palette.

Yeah, that's the idea of global commands. Be prepared that your commands are invoked by whomever... You can use the when-trick but `false` isn't a good condition, use something that exists like `"when": "config.noExists"`

**Comment by DanTup** [comment]
@jrieken I don't quite understand what you mean. Do you mean to actually use the condition `config.noExists` or just some made up value? I thought `false` was the safest value that could never occur. Is there a better way to create internal commands that shouldn't be called/seen by users?

**Comment by jrieken** [comment]
> config.noExists or just some made up value?

half and half. `config` is the generic prefix to reach into a configuration/setting value which does not exist. Using `false` should also work but using a value as key might confuse our "parser". 

> Is there a better way to create internal commands that shouldn't be called/seen by users

That doesn't exist for us, every command is public and when-clauses are recommendations only, albeit very good recommendations.

**Comment by DanTup** [comment]
> That doesn't exist for us, every command is public and when-clauses are recommendations only

What about when there are arguments? (for ex. this one takes an argument that is a `TreeItem` so the user wouldn't be able to provide it). I do have other "private" commands but I think I don't declare them in `package.json` so they don't show up - however I'm forced to put this one there so I can declare the text for the context menu.

Let me know if there's a better way to do this!

**Comment by DanTup** [comment]
Doh - I had a copy/paste error. `false` is probably working; but I'd missed one of the commands from the `commandPalette` section and it was the one I was using to test. Apologies, and thanks for info!

**Comment by jrieken** [comment]
> What about when there are arguments? 

You need to always check them, ideally infer them when missing. We know that's hard... There are ideas about command-preconditions which will control the enablement state but we haven't narrowed down on it yet
