### ISSUE TITLE
TreeView: drag listener leaks

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45113]
Steps to Reproduce:

1. scroll the tree when there are items inside
2. add a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeView.ts#L244) and [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeView.ts#L236)

=> I never see the drag listener getting disposed

**Comment by joaomoreno** [comment]
Seems to be a false positive.
