### ISSUE TITLE
Some Extensions are missing unexpectedly.

### ISSUE THREAD

**Issue by paperant** [Microsoft/vscode#45111]
### Issue Type
Bug

### Description

Sometimes when I **launch the app** or just after I **click** the `Reload to update`, some of the extensions would be missing. 
For the first time, I lost my theme extension `Dracula Official 2.9.0`. I have nothing to do but try to search for it and **reinstall it manually**. And now I lost extensions `Code Runner 0.9.0` and `Language Support for Java(TM) by Red Hat 0.20.0`. Nothing works and I had to **reinstall it manually** again! 
I don't know when it comes to me for the third time that I have to reinstall some of my extensions. Maybe I have to reinstall all my extensions some day, who knows? 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.54GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dash|dee|1.8.0
code-runner|for|0.9.0
python|ms-|2018.1.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by kieferrm** [comment]
Sorry about the troubles. We had a bug that the restart for updating VS Code did not consider if extensions where in the process of being updated. This is fixed in the latest insider and will be fixed in 1.21 that we'll release in the next couple of days.

//duplicate of #41894
