### ISSUE TITLE
Font Ligatures

### ISSUE THREAD

**Issue by chabinot** [Microsoft/vscode#45120]
Hello,
- VSCode Version: 1.20.1
- OS Version: Windows 10
How can i activate font ligatures ?
In my font list, i have yet "Fira Code".
In the settings, i do this : 
{
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.fontSize": 18
}
It does'nt work.
Best regards

**Comment by vijaypushkin** [comment]
Did you install Fira Code in your computer?

**Comment by kieferrm** [comment]
Instruction how to install Fira code can be found here: https://github.com/tonsky/FiraCode/wiki. The settings you list, if those are your user settings, seem correct.
