### ISSUE TITLE
Support remote debug adapters

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45129]
- Introduce "Launch service" API for launching DAs somewhere
- make VS Code use "Launch service"
- provide "Launch service" implementation that runs DAs side by side with the EH

**Comment by isidorn** [comment]
Unassigning myself for now. @weinand please assign me back once some work is needed from my side or if I can help in any way. Thanks

**Comment by weinand** [comment]
The "EH DA" branch of VS Code supports this:

![2018-03-26_10-56-02](https://user-images.githubusercontent.com/1898161/37896540-4d13b9d2-30e4-11e8-8c35-8b75bf80b2dc.png)
