### ISSUE TITLE
Support language specific intellisense in breakpoints conditions and logMessage peek UI

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45127]
related issue (but not a duplicate): https://github.com/Microsoft/vscode/issues/11692

Additional info:
- turn current condition text box into an editor (so that we can use the Intellisense infrastructure),
- one way to get Intellisense is to programmatically trigger a completion command for the breakpoint's line and underlying file. From the resulting list of completion items you can extract interesting items (e.g. those with kind Variable) or use all,
- for the LogPoint's text box language Intellisense is only needed within the curly braces:
`{ Date.now() }: this is a log message with a variable value: { x }` 
Outside of the curly braces Intellisense could just suggest the curly braces.

Example from VS for Mac:

![2018-03-21_10-17-57](https://user-images.githubusercontent.com/1898161/37701986-5e6da32e-2cf1-11e8-9046-52e36f8dd918.png)

**Comment by isidorn** [comment]
Done via https://github.com/Microsoft/vscode/pull/46540
