### ISSUE TITLE
Allow to run Node from node_modules/.bin

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45126]
_From @GingerPlusPlus on February 20, 2018 20:56_

VSCode's Node debugger could add `./node_modules/.bin` to the beggining of PATH before running Node, which'd allow to use https://npmjs.com/node to easily use a version of Node different than the one installed on the system by running for example `npm i --no-save node@6`.

_Copied from original issue: Microsoft/vscode-node-debug2#168_

**Comment by weinand** [comment]
You can use the [new "runtimeVersion" attribute](https://code.visualstudio.com/updates/v1_20#_node-debugging) or something like:
```js
"runtimeExecutable": "${workspaceFolder}/node_modules/.bin/node"`
```

**Comment by weinand** [comment]
_From @GingerPlusPlus on February 22, 2018 21:3_

Thanks for your reply!

This is not what I asked for, but it'll do.

**Comment by weinand** [comment]
Please feel free to submit a PR.

**Comment by GingerPlusPlus** [comment]
Where in the repo is the relevant code located?

**Comment by weinand** [comment]
In the node-debug extension:
https://github.com/Microsoft/vscode-node-debug/blob/50b7e0def4c296d7e575b4408fa5ef3f0821c408/src/node/extension/configurationProvider.ts#L138-L206

**Comment by weinand** [comment]
Before submitting a PR please let us know what you are planning to do so that we can avoid disappointments if we cannot accept a PR.
