### ISSUE TITLE
Preview is bugged

### ISSUE THREAD

**Issue by venkovich** [Microsoft/vscode#45125]
### Issue Type
Bug

### Description

This preview page is totally bugged ... every time i open new file and click preview it start to flicker between my previous and the new one after every new click... 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3400)|
|Memory (System)|7.89GB (2.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
vs-code-css-comments|ash|1.0.3
vscode-custom-css|be5|2.7.0
vscode-html-css|ecm|0.2.0
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.3.0
font-awesome-codes-css|med|0.1.1
code-beautifier|mic|1.7.2
HTMLHint|mka|0.4.0
css-grid-snippets|oha|0.0.5
vscode-css-peek|pra|2.1.0
css-auto-prefix|spo|0.1.4
html-preview-vscode|tht|0.1.1
html-css-class-completion|Zig|1.17.1

</details>
Reproduces only with extensions

**Comment by sbatten** [comment]
@venkovich This issue seems to just have appeared in our inbox even though it is very old. I am going to close this issue due to its age, but feel free to open a new issue if the problem persists on newer versions.
