### ISSUE TITLE
vscode.executeCodeActionProvider results seem to be missing their `command` property

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45124]
I have a code action provider that returns code actions like this:

```ts
private convertResult(document: TextDocument, change: as.SourceChange): CodeAction {
	const title = change.message;
	return {
		command: {
			arguments: [document, change],
			command: "_dart.applySourceChange",
			title,
		},
		kind: CodeActionKind.Empty.append(change.id),
		title,
	};
}
```

In a contributed tree I call `vscode.executeCodeActionProvider` and filter to the CodeActions that have kinds:

```ts
const fixes = (await vs.commands.executeCommand(
	"vscode.executeCodeActionProvider",
	this.activeEditor.document.uri,
	range,
)) as Array<vs.Command | vs.CodeAction>;
```

However when I inspect the returned values, the (outer) `command` property is missing. I need this in order to invoke the code action.

(cc @mjbvz - not sure if maybe this is related to new CodeAction stuff?)

**Comment by jrieken** [comment]
Yeah, that's an oversight when receiving the result

**Comment by DanTup** [comment]
@jrieken Can you think of any reasonable workaround I could use in the meantime?

**Comment by jrieken** [comment]
Not really... But I'll push a test in a minute

**Comment by DanTup** [comment]
@jrieken Is it too late for this in 1.21?

**Comment by jrieken** [comment]
Yeah, I will cherry-pick the change to the release-branch. We have just release an 1.21 candidate as current insiders and this will likely go into an insiders-build this afternoon

**Comment by DanTup** [comment]
@jrieken Perfect - thanks very much!
