### ISSUE TITLE
Do not leak `--disable-extensions` into extensions actions

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#45122]
Extension management service should be the sole owner of disabled extensions. It should have all the knowledge of what extensions are disabled under given circumstances. For eg., when started with `--disable-extensions` only user extensions should be disabled and not system extensions. But user should be able to still disable/enable system extensions.

**Comment by rebornix** [comment]
Not sure if I tested correctly, but after running `code-insiders --disable-extensions`, I can't disable builtin extensions and they are labeled as `disabled`

![image](https://user-images.githubusercontent.com/876920/38148520-b3396cdc-340b-11e8-9093-ab0fbb1f960f.png)

**Comment by sandy081** [comment]
@rebornix I already have an issue for this case - https://github.com/Microsoft/vscode/issues/46951

This was a debt item to clean up some code and as part of it I wanted to fix #46951 but could not. 

Hence closing this.
