### ISSUE TITLE
Provide an option to not mix symbols and files in quick open

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#4512]
When pressing `ctrl+p` to open the quick open panel and typing a few letters to look for a file, the panel seems to show symbols matching my string first, then some files. Worse, it mixes files & symbols.

![quickopen](https://cloud.githubusercontent.com/assets/199648/13927121/a67e3274-ef8f-11e5-9f79-9960e656c953.png)

It makes it really difficult to quickly open a filename: I really need to be carreful when typing
And it seems to return too many matches too.

For example, typing `stenci` would return '**S**I**T**UATION_**E**CRA**N**_**C**LIENT' which is not even closer to "stencil".

I guess this kind of match should only work with captial letters found into camel case words, not in full uppercase.

What about having an option to only display files in Ctrl+P panel ? Isn't the Symbol panel there for showing symbols ?

- VSCode Version:0.10.12 insider
- OS Version: Win 10

**Comment by warpdesign** [comment]
It will also present:
Bar**r**e-d-**app**u**i**-**d**roite.jpg
before:
map.**rappid**.js
in the results.

**Comment by jrieken** [comment]
@bpasero can clarify but I'd say it's like that because it useful ;-)

**Comment by bpasero** [comment]
The idea is to open "anything" from the default quick open handler and so we put symbols and files together. There are times where I like that and times where I don't, but in most cases I like it.

Maybe this should be configurable or we need another handler for files only. 

@warpdesign feel free to open feature requests on this if you feel strong about it and a bug on the sorting is already known in another case.

**Comment by warpdesign** [comment]
@bpasero I really think this should be configurable (it returns some WebGL methods and I am not using opengl at all in my whole project).

Plus, the french translation reads "atteindre le fichier" in the menu which basically means "open a file": this is misleading.

I think that:

 - there is clear something wrong when Ba**r**re-d-**app**u**i**-**d**roite.jpg comes before map.*rappid*.js when looking for a file by typing `rappid`.
 - an option would be great for at least not mixing symbols / files in the panel (both could be returned, but separated)
 - an option to only show files would be great too

Where can I open a suggestion for that ?

Note that I am really considering using something else than Code right now, because this panel is one of the things I use the most in Code and as it is now, I cannot use it :(

**Comment by bpasero** [comment]
@warpdesign we can reuse this one for the option. I wonder from where you get the WebGL context. Can you share your workspace with us?

**Comment by warpdesign** [comment]
@bpasero clicking the WebGL symbol result opens the `lib.d.ts` file located in `C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib`.

**Comment by bpasero** [comment]
@warpdesign can you do Ctrl+Shift+P > Close File when you have lib.d.ts open and then see if symbols still show up from that file?

@aeschli I think we should not show symbols from d.ts files or provide an option to exclude them.

**Comment by warpdesign** [comment]
@bpasero If I do `Ctrl+Shift+P > Close File` after having opened lib.d.ts file, SVG symbols do not show up anymore.

**Comment by bpasero** [comment]
@warpdesign that is good, the question is how lib.d.ts ended up in there in the first place. I assume you never opened it. Do you maybe have a jsconfig.json or tsconfig.json that includes a folder with lib.d.ts?

**Comment by warpdesign** [comment]
@bpasero I never opened it. I don't think I have jsconfig.json/tsconfig.json files either: where should I find these files ?

**Comment by bpasero** [comment]
@warpdesign ok lets keep an eye on this, if you ever see symbols from lib.d.ts again without having this file opened, I suggest you file a bug. 

@dbaeumer fyi this seems similar to the issue that I saw with getting errors/warnings from lib.t.s in selfhost.

**Comment by bpasero** [comment]
Pushed as `search.quickOpen.includeSymbols` (disabled by default).
