### ISSUE TITLE
allow tc39 proposal-export-ns-from

### ISSUE THREAD

**Issue by fthebaud** [Microsoft/vscode#45139]
Currently the following Javascript export syntax is not considered valid by vscode:
`export * as actions from './Something.actions.js';`

![20180305_124241_code](https://user-images.githubusercontent.com/5389778/37034618-2dda0d90-214a-11e8-9739-a6228e83897f.png)
![20180305_123722_code](https://user-images.githubusercontent.com/5389778/37034627-3348ca14-214a-11e8-84c1-4d8c97ac523d.png)

This syntax is actually a stage 1 proposal and is supported by Babel.
https://github.com/tc39/proposal-export-ns-from

Would it be possible to support that syntax ? Maybe as a compiler option while the feature is in an experimental state ?

**Comment by mjbvz** [comment]
Thanks. Support for this is tracked upstream by https://github.com/Microsoft/TypeScript/issues/4813
