### ISSUE TITLE
File diff Ignore Trim Whitespace turn off if no difference found

### ISSUE THREAD

**Issue by SailorMax** [microsoft/vscode#45131]
- VSCode Version: 1.20.1
- OS Version: Windows 10 16299.248

Steps to Reproduce:

1. add or remove tab before any line of repository file
2. open SCM tab
3. open diff viewer with modified file

Expected: see changes
Actual: don't see any changes

Does this issue occur when all extensions are disabled?: Yes

**Comment by marcobeltempo** [comment]
@alexandrudima I'd like to take on this issue. Would you be able to point me in the right direction?

**Comment by danielfrankcom** [comment]
Initially I had the same behavior as you, but unless I'm mistaken, I've found a fix.

I've been hunting around for the source of this issue for a few hours now, and it led me to discovering that there's an explicit variable in the code called `_ignoreTrimWhitespace` which is causing this behavior. This is obviously slightly confusing, but I used Git to find the first introduction of this variable, and it seemed to have been made with a specific purpose in mind.

Eventually I realized that there is a button in the diff editor (looks like a paragraph mark), which when hovered over displays a tooltip that reads "Ignore Trim Whitespace". When I click this, it fixes this behavior for me, and I can now see the whitespace in the diff exactly as I would expect.

![image](https://user-images.githubusercontent.com/15225573/37443890-08fe49ae-27cc-11e8-922b-47f05db7a1ed.png)


Hopefully this fixes it for you too, but if it doesn't let me know and I can look into it further.

**Comment by SailorMax** [comment]
@danielfrankcom 
If VSCode show "file was changed", it has to show at least 1 difference when I trying to see it. If it doesn't - this looks like bug. "Ignore Trim Whitespace" button can show more or less difference, but not show or hide all of them.

**Comment by danielfrankcom** [comment]
When you add the tab, it shows up in the source control tab right? Even if the tab was the only thing that changed in the file?

Can you send me 2 screenshots of your diff with the 'whitespace button' on and off? Mine will still show the tab even if it's the only thing in the file. Perhaps I'm misunderstanding what you're saying, or perhaps it's much harder to reproduce than originally stated.

**Show whitespace:**
![image](https://user-images.githubusercontent.com/15225573/37467945-d5bb96de-281e-11e8-9e29-b4934864d39e.png)

**Ignore whitespace:**
![image](https://user-images.githubusercontent.com/15225573/37467981-f0f23930-281e-11e8-8ddf-f8778e2e5865.png)

As a side note, the whitespace button seems to have a different appearance now.

**Comment by SailorMax** [comment]
@danielfrankcom
In case with tabs + "Ignore Trim Whitespace" you have to parse string by your eyes to understand what the difference. But you can.
In case with changed newlines (CRLF -> LF), by eyes find the difference much more complicated.
In both cases easier to see difference as in your first screenshot, if this is only difference in the file. In this case you will think about "Ignore Trim Whitespace" only after some time... I think in this case VSCode can  turn it on automatically. We nothing lost from that.

**Comment by danielfrankcom** [comment]
Any other thought on this moderators? It would make sense to change the default view to me, considering Git shows spaces by default in its diff.

**Comment by alexandrudima** [comment]
* we have an option, `diffEditor.ignoreTrimWhitespace` that controls the diffing algorithm around trim whitespace.
* the option is true by default, i.e. to ignore trim whitespace. This should remain IMHO the default, as it produces diffs that are important and skips over whitespace (often called trivia in ASTs).
* there is a button in the diff editor, that looks like a paragraph sign, that reflects the state of the option. Clicking the button will toggle the option in user settings.

The above is all good and I wouldn't want to change anything. The problem occurs when:
* `diffEditor.ignoreTrimWhitespace` is true
* there are only whitespace changes or end-of-line changes
* the diff editor will not paint any diff

IMHO, the solution is to present a message saying "these files differ only in terms of whitespace, which is now ignored" or something along these lines.

**Comment by gjsjohnmurray** [comment]
@chojrak11 that's exactly what this button does:
![image](https://user-images.githubusercontent.com/6726799/56954234-37cb7f00-6b36-11e9-93ab-7696322e9512.png)

I think the tooltips on that button should be improved. At the moment, when the button symbol is pale (opacity 0.5) differences caused by leading or trailing whitespace don't get shown. The tip says "Show Trim Whitespace". Clicking it makes the symbol bold. The tip changes to "Ignore Trim Whitespace", and differences in leading/trailing whitespace show up.

I suggest the "Show Trim Whitespace" tip should be rephrased "Show Leading/Trailing Whitespace Differences", and the other tip become "Ignore Leading/Trailing Whitespace Differences".

Though longer, the new tips communicate better. This is what the caption of the `diffEditor.ignoreTrimWhitespace` setting reads:
![image](https://user-images.githubusercontent.com/6726799/56955110-62b6d280-6b38-11e9-9151-b524f329046f.png)


I also support the proposal that this setting should be automatically set to "Show" mode if the only differences between the two files are in leading/trailing whitespace.

**Comment by chojrak11** [comment]
@gjsjohnmurray thank you for the explanation and support of my proposal. Now, I don't think I'll be able to prepare the fix myself, so I hope a developer familiar with the code base or having sufficient time will jump in :)

**Comment by alexandrudima** [comment]
We will now render a click widget which hints when this happens:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/66691179-ba836900-ec94-11e9-84fa-c0fd4fda5d26.gif)
