### ISSUE TITLE
Autosave + trim trailing whitespace can change indentation for tabstops in snippets

### ISSUE THREAD

**Issue by JakeBecker** [Microsoft/vscode#45146]
### Issue Type
Bug

### Description

With settings:
```
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 1000,
  "files.trimTrailingWhitespace": true,
```

When using a snippet that has a tabstop following some whitespace, if you take long enough for autosave to kick in, it can remove the whitespace before the tab stop and affect its indentation. For example, in the snippet for an Elixir function definition:

```
def $1 do
  $0
end
```

If you wait for a second while focused on the `$1` tabstop, it will autosave and remove the whitespace before the `$0`. When you tab to it, the cursor will be all the way at the leftmost column.

PS. VS Code is fantastic and I am sorry to add another issue to your already huge pile.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.12GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>
(I did not check whether reproducible without extensions because it does not seem like an extension issue)

**Comment by bpasero** [comment]
Ping pong, but that command is not from me. I also think it needs some support from the editor to find out that a region is currently in snippet mode.

**Comment by JakeBecker** [comment]
Interestingly, I still seem to get this issue when I set `files.trimTrailingWhitespace` to `false`.

**Comment by alexandrudima** [comment]
The editor does not "know" that there is a snippet controller that adds markers and uses them as tab stops, as snippets are not a core editor concept. However, we could make some of the saving code ask `SnippetController2` if it is active...

**Comment by alexandrudima** [comment]
For verification, use:
```
    "files.autoSave": "afterDelay",
    "files.trimTrailingWhitespace": true
```

And insert a snippet like the `for` loop in JS.
