### ISSUE TITLE
Weird terminal splitting behaviour after VSCode restart 

### ISSUE THREAD

**Issue by nguyenhuyanhh** [Microsoft/vscode#45142]
Issue Type: <b>Bug</b>

The terminal does not split after VSCode is restarted.

If we kill the terminal and open it again, the issue disappears. Not really a big issue, but it's slightly annoying.

VS Code version: Code - Insiders 1.21.0-insider (d7dca142ad6051e6b1c7397ea73221feb0160f21, 2018-03-02T06:16:11.117Z)
OS version: Linux x64 4.13.0-36-generic

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.2.3
django-html|bib|1.2.0
rainbow-csv|mec|0.2.0
python|ms-|2018.1.0

</details>

Reproduces without extensions. Steps to reproduce:

1. Make sure the terminal is on
2. Close VSCode
3. Open VSCode again, switch focus to terminal and split the terminal

Screenshot:
![2018-03-06-233350_1366x768_scrot](https://user-images.githubusercontent.com/1654817/37041462-3fd7a302-2197-11e8-9501-f4c00d87ed31.png)

**Comment by nguyenhuyanhh** [comment]
I tried updating into the latest Insiders (a903bd38fbe9006c076d218ff69fe1ee0160f815, 2018-03-06T11:07:13.515Z) and the issue persists.

**Comment by Tyriar** [comment]
Can you share your settings file?

**Comment by nguyenhuyanhh** [comment]
Sure.

```json
{
    "workbench.startupEditor": "newUntitledFile",
    "editor.fontSize": 12,
    "window.zoomLevel": -1,
    "editor.wordWrap": "on",
    "workbench.iconTheme": "material-icon-theme",
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "git.confirmSync": false,
    "git.autofetch": true,
    "editor.formatOnSave": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "git.enableSmartCommit": true
}
```

Another thing to note, I think this only happens if terminal started during startup (i.e. terminal was on during previous session). I have updated the steps to reproduce.

**Comment by nguyenhuyanhh** [comment]
After the update to Stable, I cannot reproduce the issue anymore (and miraculously I also cannot reproduce that on Insiders despite using the same version).

I'm closing this for now so as to not distract you from the main work. Thanks a lot for this feature!

**Comment by Tyriar** [comment]
@nguyenhuyanhh glad it's fixed 👍
