### ISSUE TITLE
shell script wrong comment highlighting

### ISSUE THREAD

**Issue by yaroslavsadin** [Microsoft/vscode#45143]
- VSCode Version: 1.20.1
- OS Version: Windows 7

It seems VS code mistakingly implies a comment and dims the text when it sees hash symbol in the following case.

Steps to Reproduce:

1. Create new shell script and open in VS code
2. paste this:
`func="$(echo $i | gawk -F[#] '{printf ($1)}')"`
3. All after # symbol will be a "comment"

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#111
