### ISSUE TITLE
Indenting disappears after moving cursor away and back

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#45149]
This came in through https://github.com/Dart-Code/Dart-Code/issues/635 but I can repro it with a much simpler case.

Here, I type `one()` and then press `<enter>` inside the parens to split it into multiple lines. The line inserted in between is automatically indented (correctly). However, if I move away from that line (eg. to add a comma below, then when I return to it, the indenting is gone).

It seems to only happen in some situations (it seems consistent where it does/doesn't work).

Apologies for the weird GIF artifacts, not sure what happened there. Hopefully you can see the cursor. It's intially indented, but then the indent disappears after I move away to type the comma and then back.

My format provider doesn't work when there's syntax errors so is not executing at all here.

![indent_gone](https://user-images.githubusercontent.com/1078012/37046481-64ad68ba-2160-11e8-8f6e-6bea9f2fb399.gif)

**Comment by Timofeuz** [comment]
Probably related
https://github.com/Microsoft/vscode/issues/40115
