### ISSUE TITLE
quickOpen does not reveal file in side bar when a drive is opened

### ISSUE THREAD

**Issue by hunhejj** [Microsoft/vscode#45141]
### Issue Type
Bug

### Description

* _(map a folder to a drive)_
* File > Open folder > select a _drive_ as the root folder, e.g. `D:` _(or the one mapped in the prev step)_
* Open a file, e.g. `foo.bar` _with quickOpen_
=> issue: The correct file will be opened inside the Open editors, but it is not recognized as a file from the workspace, i.e. it won't get highlighted in the Explorer
* Open the same file using the _Explorer_ (side bar)
=> issue: It will be opened in another tab. The file will show up twice in the "Open editors" section. This time it is correctly highlighted in the explorer panel. The path of the two files is the same, e.g. `D:\foo.bar`.
* Open quickOpen and start typing the filename
=> issue: it will suggest twice the exact same file and depending which one you select you will land on tab1 OR tab2. Still tab1 won't be revealed in the Explorer while tab2 will.

### VS Code Info

VS Code version: Code 1.20.1
OS version: Windows_NT x64 6.1.7601

Reproduces without extensions

**Comment by bpasero** [comment]
@hunhejj could it be that the casing of the files differs?

**Comment by hunhejj** [comment]
It's just one single file. If I write in tab1, the changes are there in tab2.

**Comment by bpasero** [comment]
@hunhejj yes that is true because it is the same file on disk but it could still be a different casing used in VS Code. Can you copy the path of each files and compare them?

**Comment by bpasero** [comment]
@hunhejj I can reproduce, thanks!

**Comment by bpasero** [comment]
@roblourens @chrmarti this seems to be a regression with regards to the URIs that I get from the file search. Steps to reproduce:
* Windows 10
* create a subst drive (`subst H: <some dir>`)
* open H: in VS Code
* search for a file that is in the root
* open it
* click on explorer to open the same file
* it opens a second time

When I check for the results I get from the file search, it looks like each root file has an extra backslash:

![image](https://user-images.githubusercontent.com/900690/37050112-4acc25a4-2173-11e8-9ce3-79a4f26d9ca3.png)

**Comment by bpasero** [comment]
Wow I can actually reproduce this in 1.20, so maybe not a candidate after all then unless you have heard this before.

**Comment by roblourens** [comment]
@bpasero This line is the problem, https://github.com/Microsoft/vscode/blame/master/src/vs/workbench/services/search/node/rawSearchService.ts#L135, base is h:\

Why not path.join?

**Comment by bpasero** [comment]
> Why not path.join?

Yeah makes sense, but that would not result in any change, or does it?

**Comment by roblourens** [comment]
> but that would not result in any change, or does it?

path.join will only add a slash when needed, so there will not be a duplicated slash, like when using naive `join`. Or do I misunderstand your comment?

**Comment by bpasero** [comment]
@roblourens oh yeah totally, good catch!!

**Comment by chrmarti** [comment]
Must be old code, I would never do that. :)

**Comment by chrmarti** [comment]
Thanks @roblourens !

**Comment by hunhejj** [comment]
Thank you guys for fixing it!
