### ISSUE TITLE
Bad/Laggy scrolling randomly

### ISSUE THREAD

**Issue by JSzkup** [Microsoft/vscode#45150]
### Issue Type
Bug

### Description

While using a laptop with a windows precision touchpad (Dell XPS 13 9434) If alt + tab out of the program or use the task view scrolling becomes extremely laggy and choppy even with only a simple text file open. A quick fix is to resize the window, the issue however will come back as soon as task view is used again.

Expected outcome is consistently smooth scrolling.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|3.91GB (0.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0
cpptools|ms-|0.15.0
open-in-browser|tec|1.1.0
html-css-class-completion|Zig|1.17.1

</details>
Reproduces without extensions

**Comment by Oxyo78** [comment]
I got the same problem on my XPS 13 (9360) with a long code file , I think the problem from the default zoom screen of windows (150%), when I switch to 100% zoom screen, It's working fine. Intel GPU is not enought strong for zoom and vsc scrolling 👎. 
Resize the screen fix the problem temporarily, maybe desactivate the GPU in VSC ?
