### ISSUE TITLE
Automatically close diff editor when switching from Source Control to Explorer mode

### ISSUE THREAD

**Issue by lvillani** [microsoft/vscode#45151]
### Issue Type
Feature Request

### Description

I usually select files for diffing in the "Source Control" view. Sometimes I diff a lot of files. When I switch back to explorer I still have all those buffers lying around, that make tab switching harder.

It would be nice to have VSCode automatically close all those buffers when I switch back to the Explorer view for normal editing.

This is probably tangentially related to #41096

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

**Comment by IviIIani** [comment]
Go away

**Comment by HorstBaerbel** [comment]
I just want to add that a nice option would be to have only one diff tab, the one you have currently selected in the source tree. When you do not select anything, there is no tab. If you have, it should vanish when switching as suggested by Ivillani.

**Comment by mariusa** [comment]
Ping? Without this, it's simpler to use "git diff" in command line instead of vscode.

**Comment by gilescope** [comment]
That would be nice. If someone wants to try and implement this as an extension https://github.com/gkotas/vscode-restore-git-branch-tabs might be a good place to take soem ideas from...

**Comment by OneOfOne** [comment]
Bump

**Comment by drawcard** [comment]
Can confirm, this is driving me nuts, I spend a good part of my day just closing those tabs all the time.

**Comment by nmoreaud** [comment]
I would like to have a right-click, "close git diffs" option in context menu (like "close others").
That way, when I finish searching in the git annotations or reviewing my changes before committing ; I can close everything and keep only the source files.

**Comment by yury-kozlov** [comment]
As a workaround you may check option `workbench.editor.enablePreview`, so that only one diff window will be active.
