### ISSUE TITLE
Window with native dialog breaks when quitting

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#45157]
Mac

- Cause native dialog to be shown (eg start "attach" debug config when it will fail)
- Switch to another vscode window
- cmd+q
- All windows close except the one with the dialog open

Open extension viewlet, see that it can't load extensions or search. Also can't quit from the menu.

**Comment by bpasero** [comment]
Not a regression, but a good one we should fix, here is what happens:
* you hit Quit
* Electron starts to close all opened windows except the one with a modal dialog
* the shared process is a window and closes
=> nothing works anymore with regards to extensions management and telemetry

The shared process should override the close event and prevent it (see [here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/lifecycle/electron-main/lifecycleMain.ts#L165) how we do it for Code windows). It should only close upon explicit disposal from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/app.ts#L355).

**Comment by joaomoreno** [comment]
Great catch! Thanks @bpasero for the pointers!
