### ISSUE TITLE
Inconsistent Del behaviour with Find In Files + F4

### ISSUE THREAD

**Issue by garychapman** [Microsoft/vscode#45168]
### Issue Type
Bug

### Description

1. Do a Find In Files search that returns multiple results

2. Hit F4 to navigate to the first search result. The cursor appears in the edit pane. If I hit Del, the character under the cursor is deleted (as expected).

3. Hit F4 to navigate to the next search result. The cursor appears in the edit pane. If I hit Del this time, the search result is deleted from the results pane (not expected).

This seems to happen with every other time I do a F4 + Del combination, and I can reliably reproduce this.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|15.69GB (5.81GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by roblourens** [comment]
Looks like https://github.com/Microsoft/vscode/issues/42842

Please try in 1.21 (released in a day or two) or you can try in Insiders right now.

**Comment by garychapman** [comment]
@roblourens Apologies for the dupe! I did a search of existing issues, but obviously not thoroughly enough 😊 Anyway, Insiders 1.21.0 seem to fix it.
