### ISSUE TITLE
Opening some module can cause memory leak. 

### ISSUE THREAD

**Issue by haihao1881** [Microsoft/vscode#45165]
### Issue Type
Bug

### Description

Opening some module can cause memory leak. 
I pip install simpleitk(a really important medical segmentation module),when I invoke this modle, the memory surges and the whole system collapses. But when I use other modules except simpleitk,vsc runs smoothly. So I infer there is a bug that cause this problem like recursion. Really love this IDE, hope you team can fix it.
eg:
import SimpleITK as sitk
resample=sitk.ResampleImageFilter();

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (16 x 2095)|
|Memory (System)|7.90GB (5.02GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\haihao\Desktop\Git\Mask_RCNN\visualize.py|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter|don|1.1.4
nbpreviewer|jit|1.0.0
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.1.0
cpptools|ms-|0.15.0
vscode-yaml|red|0.0.9

</details>
Reproduces without extensions

**Comment by kieferrm** [comment]
Pls file the issue against the python extension. Here is the link: https://github.com/Microsoft/vscode-python/issues/new  Thanks!
