### ISSUE TITLE
Proxy not supported in IE11

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#45166]
Running Monaco from source in IE11 stops working as Proxy is available there https://github.com/Microsoft/vscode/commit/98ef6607e69415c2b7acfbc25585911c18e85c03#diff-4d603a807b45bfab3318078fb87daa6dR460 . Before we drop support for IE11, we may need shim for Proxy.

**Comment by sandy081** [comment]
Above change was partial. Later, I did remo the Proxy from core configuration model and it is only used in Extension host - 81f1deec2fb233b5e0da3739fea712f3f0a5cb82
