### ISSUE TITLE
Custom snippets not work in comments(annotations)

### ISSUE THREAD

**Issue by TonyGao** [Microsoft/vscode#45164]
- VSCode Version: 1.20.1
- OS Version: macOS

Steps to Reproduce:

1. Custom a code snippet
2. Use it in php comments
(For some situations it's called annotation, and it's a part of useful code)

Does this issue occur when all extensions are disabled?: Yes

![untitled](https://user-images.githubusercontent.com/1457819/37066905-5b55eea4-21e2-11e8-9084-bb4d970566b8.gif)

**Comment by jrieken** [comment]
please provide the snippet or snippets *and* the file in source

**Comment by TonyGao** [comment]
it's just a simple php snippet, no other things.

```
{
    "Annotation ORM Table": {
        "prefix": "@ORM\\Table",
        "body": [
            "@ORM\\Table(name=\"sunshine_organization_user\")"
        ],
        "description": "ORM Table"
    },
}
```

**Comment by jrieken** [comment]
What happens when you press F1 > Insert Snippet when inside the comment?

**Comment by TonyGao** [comment]
Well, it works with the command, but  the implementation with the key words is not work as well.

**Comment by chi-feng** [comment]
By default, quick suggestions are not shown inside comments and strings. You can change this behavior by setting `editor.quickSuggestions.comments = true`
