### ISSUE TITLE
Cannot restart after crash

### ISSUE THREAD

**Issue by astanciu** [Microsoft/vscode#45160]
- VSCode Version: 1.20.1
- OS Version: OSX 10.13.3

When VSCode crashes (not sure why), afterwards it won't start up, throwing this message:

>Another instane of Code is running but not responding

![image](https://user-images.githubusercontent.com/1675025/37063010-168cfd5c-2166-11e8-939e-603380510856.png)

I've `sudo kill`ed every code process I can find and still happens. Is there anything I can do to force it to start (some lock or PID file that can be deleted for ex) so I don't have to restart the whole computer?

**Comment by astanciu** [comment]
`htop` didn't show any processes for vscode after I force killed everything due to the crash.  Using a different user-data-dir did work fine. This was a good hint, I checked the default user data dir and noticed a couple of `.sock` files. After removing those, I was able to start it up with the default user data dir w/o having to reboot.

**Comment by bpasero** [comment]
I would assume the sock file to get deleted no matter how VS Code exits?

**Comment by joaomoreno** [comment]
@bpasero Not on macOS or Linux, the files stay around after exit. But if the socket file is there and no one is serving on it, Code should properly delete it and start up.

**Comment by bpasero** [comment]
@joaomoreno that is exactly what seems to happen, someone is still blocking that socket.

The dialog is from https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/main.ts#L189

@astanciu are you 100% sure there is no other code process running?

**Comment by astanciu** [comment]
@bpasero I can confirm no processes containing "Visual Studio" or "code" or "Code" in their name exist.

**Comment by bpasero** [comment]
> But if the socket file is there and no one is serving on it, Code should properly delete it and start up.

I am not sure we can distinguish between the file being there but nobody serving and the file being there with someone serving, I always assumed this file would go away when the one that serves ends.

**Comment by bpasero** [comment]
@astanciu can you run "`code --verbose`" from the command line and attach the output?

**Comment by astanciu** [comment]
I restarted my computer and lost my ability to reproduce crashes ( #45256 ). I will need to put this on pause until it crashes again on it's own (it's been happening around once a day or so). I'll update when I have something.
