### ISSUE TITLE
'MD File Preview' may rerender everytime navigate to the preview tab.

### ISSUE THREAD

**Issue by lssbq** [Microsoft/vscode#45170]
- VSCode Version: 1.20.1
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Open a Markdown Preview tab and a plain text(or code) file tab.
2. Navigate between the two tabs, and you can see the MD preview has a delay to render the MD preview content.

Does this issue occur when all extensions are disabled?: Yes

This may cause a bit time window delay to render the preview of the MD file content.
As the size of MD file increases, the latency can be significantly increases.

**Comment by mjbvz** [comment]
We get rid of the preview when it is no longer visible to conserve resources. When it becomes visible again, there will be a slight delay while we recreate it

How much of a delay are you seeing?

**Comment by lssbq** [comment]
In a Markdown file more than 1K lines, the delay about 1s. I guess MD file is being rendered in that 1 second because I saw my CPU usaeg has grown a bit, and a blank window is shown. 

Test in:
Windows 10 64bit 
Intel i7-6820HQ   16GB RAM with nvme-SSD
Same situation in Apple OSX 10.13

**Comment by mjbvz** [comment]
Can you share the md file. I see around a quarter section delay in general when first previewing the document
