### ISSUE TITLE
Feature request: popup a menu list to chose cmd/powershell/bash when click "new terminal"

### ISSUE THREAD

**Issue by shengdexiang** [Microsoft/vscode#45178]
- VSCode Version:1.20.1
- OS Version:10.0.16299.248

Steps to Reproduce:

1. open terminal
2. click New terminal
![image](https://user-images.githubusercontent.com/10177690/37077303-5775b958-2215-11e8-837f-6c77c18d55f9.png)
Here, I hope a menu list popup, then I can chose which terminal to open: **cmd, powershell or bash**.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/45444
