### ISSUE TITLE
OmniSharp no longer works on Linux

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4517]
- VSCode Version: Insiders candidate
- OS Version: Ubuntu 15.10

&gt;= Mono v4.0.1 seems to be required now

![image](https://cloud.githubusercontent.com/assets/2193314/13928428/c8070e08-ef52-11e5-95cf-b600f0233958.png)

It points me to [this page](https://code.visualstudio.com/docs/supporting/errors#_20001) which advises:

> Error: Cannot start OmniSharp because Mono version >=3.10.0 is required.

As well as this (another version??):

> Currently, debugging support of VS Code on Linux or OS X requires Mono version 3.12 or later.

And says install via `sudo apt-get install mono-complete`. The latest mono-complete registered in the default Ubuntu repository seems to be 3.2.8:

```
❯ mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

**Comment by jrieken** [comment]
4.0.1 has been a requirement since a while. The fwd-link needs updating, @Tyriar please coordinate with the folks from Omnisharp/omnisharp-vscode

**Comment by Tyriar** [comment]
I think it might be an issue with the documentation pointing people towards `mono-complete` when really it should be http://www.mono-project.com/download/

**Comment by jrieken** [comment]
closing this a dupe
