### ISSUE TITLE
Terminal font display problem.

### ISSUE THREAD

**Issue by Hideer** [Microsoft/vscode#45185]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Terminal font display problem.Terminal font display problem.Terminal font display problem.Terminal font display problem.    picture
![image](https://user-images.githubusercontent.com/31301552/37083233-e7686fb0-2229-11e8-81dc-903ebe0c7e72.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35681

**Comment by Hideer** [comment]
I set the terminal font for "terminal. Integrated. FontFamily" is still doesn't work, so that the terminal can make me look very pain

**Comment by Tyriar** [comment]
@Hideer you must not be setting it to a valid font.
