### ISSUE TITLE
QuickOpen cannot find files modified in git

### ISSUE THREAD

**Issue by Espyo** [Microsoft/vscode#45189]
### Issue Type
Bug

### Description

If a file is modified in my git working directory, it will not appear as a search result when using QuickOpen to search for that file. This only applies to the "file results" section of the QuickOpen results, as the "recently opened" section will still contain the file if I did open it recently. If not, then the file will not appear in the results at all. It will still appear in the workspace explorer, with modification status icons included.

Steps to reproduce:

1. Go to a git repository.
2. Using an external tool (like a text editor), modify a file that has never been opened in Visual Studio Code, but can be seen in its the workspace explorer.
3. Open Visual Studio Code using this repository as a workspace.
4. Open QuickOpen and search for the name of the file.
5. The file will not be found.

In addition to this, if the option "search.useRipgrep" is set to "false", the problem will not occur. Me and some other co-workers use Visual Studio Code on our company's project's repository, and all of us have this issue, on a different range of machines, operative systems (although all running on Linux environments), and versions of git.

By turning "Set log level" to "Trace" and trying the search again, the following is written in the trace output:

> `[2018-03-07 09:27:46.943] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"engine.sh","maxResults":512,"sortByScore":true,"cacheKey":"id#100","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}`

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:18.341Z)
OS version: Linux ia32 4.4.0-97-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2935)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.48GB (0.31GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by roblourens** [comment]
Weird issue, ripgrep doesn't care about a file's git status.

Could you also include the lines after that in the log? How `rg` was invoked and any extra messages that come after.

**Comment by Espyo** [comment]
Sure. I booted up VS Code, turned on the Trace logs again, did the search, and this is everything it ouput. The only other lines after this are the trace log for me hitting Ctrl+A, and then Ctrl+C.

<details>

> [2018-03-08 09:25:42.506] [renderer1] [trace] CommandService#executeCommand workbench.action.quickOpen
> [2018-03-08 09:25:42.508] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"","maxResults":0,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
> [2018-03-08 09:25:42.552] [renderer1] [debug] SearchService#search rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/build' -g '!**/dist' -g '!**/docs' -g '!/GPATH' -g '!/GRTAGS' -g '!/GTAGS' -g '!/games/*/common/**' -g '!/games/*/dist/**' -g '!/games/*/modules/**' -g '!/games/*/log/**' -g '!**/*.js~' -g '!**/*.cpp~' -g '!**/*.o' -g '!**/*.wav' -g '!**/node_modules' -g '!**/bower_components' --no-ignore-parent --follow -- '.'
>  - cwd: /home/andresilva/Projects/Engine/E5
>  - Sibling clauses: {}
> [2018-03-08 09:25:42.888] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"e","maxResults":512,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
> [2018-03-08 09:25:43.095] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"en","maxResults":512,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
> [2018-03-08 09:25:43.260] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"eng","maxResults":512,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
> [2018-03-08 09:25:43.451] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"engi","maxResults":512,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
> [2018-03-08 09:25:43.863] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"engin","maxResults":512,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
> [2018-03-08 09:25:43.908] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"engine","maxResults":512,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
> [2018-03-08 09:25:43.918] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"engine.","maxResults":512,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
> [2018-03-08 09:25:44.077] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"engine.s","maxResults":512,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
> [2018-03-08 09:25:44.222] [renderer1] [trace] SearchService#search {"type":1,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/andresilva/Projects/Engine/E5","external":"file:///home/andresilva/Projects/Engine/E5","path":"/home/andresilva/Projects/Engine/E5","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/build/":true,"**/dist/":true,"**/docs/":true,"GPATH":true,"GRTAGS":true,"GTAGS":true,"games/*/common/**":true,"games/*/dist/**":true,"games/*/modules/**":true,"games/*/log/**":true,"**/*.js~":true,"**/*.cpp~":true,"**/*.o":true,"**/*.wav":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","external":"walkThrough:/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page%22%7D","path":"/usr/share/code/resources/app/out/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page","scheme":"walkThrough","query":"{\"moduleId\":\"vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page\"}"},{"$mid":1,"fsPath":"/home/andresilva/.config/Code/User/settings.json","external":"file:///home/andresilva/.config/Code/User/settings.json","path":"/home/andresilva/.config/Code/User/settings.json","scheme":"file"}],"filePattern":"engine.sh","maxResults":512,"sortByScore":true,"cacheKey":"id#30","contentPattern":null,"useRipgrep":true,"disregardIgnoreFiles":false,"ignoreSymlinks":false}
</details>

**Comment by roblourens** [comment]
And you're sure the files aren't covered by a gitignore file or `search.exclude` or `files.exclude` pattern?

Can you try running the same ripgrep command just to check that it isn't returning them?

It will be something like `<path to code>/app/resources/node_modules/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/build' -g '!**/dist' -g '!**/docs' -g '!/GPATH' -g '!/GRTAGS' -g '!/GTAGS' -g '!/games/*/common/**' -g '!/games/*/dist/**' -g '!/games/*/modules/**' -g '!/games/*/log/**' -g '!**/*.js~' -g '!**/*.cpp~' -g '!**/*.o' -g '!**/*.wav' -g '!**/node_modules' -g '!**/bower_components' --no-ignore-parent --follow -- '.'`

**Comment by Espyo** [comment]
Indeed, I had written some old test rules in .git/info/exclude, and they were matching the files I was having trouble with. That said, I did try running rg standalone, with the snippet you provided, and it can find the troublesome files, _if_ they are not written as a rule in .git/info/exclude. It looks like ripgrep really is taking into account a file's git status...

**Comment by roblourens** [comment]
Oh interesting, I haven't thought of .git/info/exclude. Glad you found that.

That explains the issue, right?

**Comment by Espyo** [comment]
I suppose so, but that still means that files covered by .git/info/exclude will not be found by ripgrep, despite being found by QuickOpen if ripgrep is disabled. Don't know to what point that is a feature or a bug. Then again, I never quite understood the logic behind .git/info/exclude, so it may make sense. Either way, I suppose there's no problem on my end any more, and I trust this thread will help people from the future, so I'm fine with a close.

**Comment by roblourens** [comment]
Sounds like `.git/info/exclude` is basically a private gitignore, so it will probably also skip that if you set `"search.useIgnoreFiles": false`. That's only supported when using ripgrep, so I guess I would say this is by design.
