### ISSUE TITLE
Unhappy prompt to install extension after just installing it

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4518]
* run `ext install`
* find an extension and press the little install button and see how it shows progress
* press the readme-button which takes you the website
* :boom: returning to VS Code prompts me to (1) restart after installing X
 and (2) also if I want to install X

<img width="972" alt="screen shot 2016-03-21 at 18 52 58" src="https://cloud.githubusercontent.com/assets/1794099/13928577/8494c374-ef96-11e5-8f5a-e716b1c3d881.png">

**Comment by joaomoreno** [comment]
Ugh. Been like this for months. Wouldn't promote it to stable candidate.

**Comment by joaomoreno** [comment]
Fixed!
