### ISSUE TITLE
How to add an RTL layout for editing Hebrew & Arabic documents (Not code)

### ISSUE THREAD

**Issue by Aminadav** [Microsoft/vscode#45180]
I very like VSCode, and I want to use it for editing documents. (Like markdown).
Not only code.

VSCode for me is the best word processor.

Now the question:

When editing, Hebrew & Arabic documents, I would like the document will have an RTL

Like in Google Docs:

![image](https://user-images.githubusercontent.com/3584317/37081475-3beb4482-21f2-11e8-8b23-cb5c83865214.png)

How can I add this feature? What it the easiest way to change the CSS of VSCode. I thought of creating an extension, so there is an extension that does something similar that I can clone?

**Comment by Aminadav** [comment]
IT is not a duplicate.  Here speaks mainly about programming, to display the characters from right to left, inside a paragraph. This VSCode doing well.

I speaking about the paragraphs. That everything will start from right to left. Not just Hebrew chars in English code.

Here is a Photoshop I made. I'm want to make VSCode behave like this:

![image](https://user-images.githubusercontent.com/3584317/37081681-e741ddbe-21f2-11e8-98d0-c18902caa089.png)

**Comment by alexandrudima** [comment]
Let's track in #11770
