### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by yechen1993** [Microsoft/vscode#45187]
- VSCode Version: 1.18.1
- OS Version: windows windows 10 professional version

Steps to Reproduce:
Open VScode directly will happen

![image](https://user-images.githubusercontent.com/16095736/37083720-5dada5c2-222b-11e8-91d1-31de817c0148.png)

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by yechen1993** [comment]
Thank you !  I found a solution here, is indeed a plug-in problem, is looking for a specific plug-in
