### ISSUE TITLE
How to debug dependent extensions (eg. install both into extension dev host on F5)

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#45196]
I'm considering splitting my extension into two (Dart and Flutter). One will depend on the other and there will be some interactions between them that means some things will be developed in both extensions together.

The way that my `launch.json` is set up I'm not sure how I can make it so `F5` would launch a single dev host with both extensions installed into it. Is this possible?

(The two extensions would like both be in the workspace as their own roots).

**Comment by kieferrm** [comment]
@DanTup I haven't tried myself but here is what I think should work:
- create a workspace the contains one of your extensions
- add the second folder as a root folder using 'Add Folder to Workspace'
- in the debug viewlet, create a launch config for the workspace (not for one or the other folder). That launch config should look like a regular one for a single extension i.e. type is `extensionsHost` and args include "--extensionDevelopmentPath=${workspaceRoot}".

When you run this launch config, both extensions should be found.

@weinand pls chime in if I got this wrong.

**Comment by DanTup** [comment]
Won't `workspaceRoot` just pass the first folder through and load that single extension?

(I haven't actually created the second extension to test this yet, but expect to in the coming weeks).

**Comment by weinand** [comment]
See testplan item https://github.com/microsoft/vscode/issues/72500 for how to debug multiple extensions.
