### ISSUE TITLE
Suggestion: refactoring for destructuring

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#45199]
Often I need to refactor an object property lookup to use destructuring. For example, from:

``` ts
this.props.foo();
```

to

``` ts
const { foo } = this.props;

foo();
```

It would be great if VSCode could offer a refactoring for this. This could be available when the property was selected/highlighted.

Or do you think this belongs in an extension?

**Comment by mjbvz** [comment]
We already support :

1. Select `this.props.foo`

1. Extract constant:

```js
const bla = this.props.foo;
bla();
```

Creating a destructure seems like a more specific use case, although it does allow using the same symbol. We can look into this if there is enough interest

**Comment by mjbvz** [comment]
Closing since there has been no further feedback
