### ISSUE TITLE
workbench.editor.closeOnFileDelete doesn't work for files which have not been focused

### ISSUE THREAD

**Issue by JakubRimal** [Microsoft/vscode#45194]
### Issue Type
Bug

### Description

1. set workbench.editor.closeOnFileDelete to false in your settings
1. create two files: `test1` and `test2`
1. open only these two files in vscode and focus `test2` file
1. close vscode
1. run vscode, it will start with `test2` file focused
1. delete `test1` and `test2` files (outside of vscode)
1. vscode shows "(deleted from disk)" next to `test2` file name
1. **bug**: vsode shows nothing next to `test1` file name and when you try to focus it it shows "Unable to open 'test1': File not found (file:///home/usernamel/test1)." Content of file `test1` is lost.

Note: It works correctly when you focus file `test1` before step 6.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Load (avg)|2, 2, 1|
|Memory (System)|11.17GB (1.81GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-spell-checker|str|1.6.5
code-spell-checker-czech|str|0.1.0

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@JakubRimal what would you expect in this case, open the file empty and dirty?

**Comment by JakubRimal** [comment]
@bpasero The same behavior as it has when you first focus the file.

There is a typical use-case which is really annoying for me:
1. Run vscode with e.g. ten files opened.
1. Focus only some of these files.
1. git checkout somewhere where all opened files don't exist.
1. vscode closes all files which have not been focused (this is a different behavior than in the description and it looks like it's because it was deleted from git instead of file manager? I haven't figured it out yet.
1. git checkout back to the original location
1. I need to reopen all files again.

**Comment by bpasero** [comment]
@JakubRimal but that is not possible because we do not load the original file content until you click the file, so we could never restore the file contents before the file got deleted.

**Comment by JakubRimal** [comment]
@bpasero Ok, I got it, thanks for the explanation. I think that now we are close to the root cause: hot exit doesn't work for deleted files. If it would store all files the same way as edited files on exit, vscode wouldn't need to load files before they are focused - they could be loaded from the hot exit storage when they have focus. Maybe this should be a different issue/FR?

**Comment by JakubRimal** [comment]
Yeah, I really think that the problem is with hot exit: hot exit keeps all unsaved files after the restart of vscode but it doesn't restore files which have been deleted when vscode was not running.

**Comment by bpasero** [comment]
@JakubRimal this would require that hot-exit stores backups for each file that was ever opened even if not dirty, I think that is overkill for the scope of that feature...

**Comment by JakubRimal** [comment]
> each file that was ever opened

@bpasero what do you mean by ever opened? It would require that hot-exit stores backups of all _currently opened_ files and it should not be overkill IMO.

**Comment by bpasero** [comment]
@JakubRimal yeah but imagine you have 500 tabs opened and never close files, this would mean that we carry around backups of 500 files even though the user might only care about the few dirty ones.

**Comment by JakubRimal** [comment]
@bpasero That's why it should be configurable and it can be disabled by default. BTW for me this (hot exit stores everything) is an expected behavior (probably because I'm used to it thank's to Sublime Text which behaves like that by default).
Can we close this issue and create FR? Or it doesn't make sense because it will not be accepted anyway? :)

**Comment by bpasero** [comment]
@JakubRimal yeah maybe open a feature request to reflect what is meant.
