### ISSUE TITLE
Separator in window.title doesn't work after hard-coded name

### ISSUE THREAD

**Issue by lanzkron** [Microsoft/vscode#45195]
### Issue Type
Bug

### Description

Try configuring the window-title in the settings (either workspace or user settings) to include a hard-coded string. 
For example: 

      "window.title":"${dirty}SomeValue${separator}${rootName}${separator}${appName}"

The `${seperator}` after the hardcoded (_SomeValue_) is not shown and the next variable is adjacent to the hardcoded value.
The window title show up as:

> SomeValueTemp - Visual Studio Code

See screenshot (in this example `rootName` is **Temp**)

![ScreenShot](https://i.imgur.com/jUn9Cbd.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|Memory (System)|23.67GB (10.69GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe -n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
gitlens|eam|8.1.0
svn-scm|joh|1.22.0
Go|luk|0.6.77
okazukiplantuml|oka|0.2.2

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
@lanzkron yes the `${separator}` variable is meant to only work between two other variables and it will only show up if the two other variables are present, that was the initial idea of it.

If you want the separator you can always just add it as text, no? The value is: `—`

**Comment by bpasero** [comment]
Closing as designed, we call out to this from the settings description:

![image](https://user-images.githubusercontent.com/900690/37135395-6fc48ccc-229d-11e8-8aaf-0d2d5994e0b7.png)

**Comment by lanzkron** [comment]
That's a... _strange_ design decision, I agree with the **only shows when surrounded by ... values** but why _**variables**_ ?

Consider the case where the hard-coded value is penultimate and the last variable may be missing, e.g. `${dirty}SomeValue - ${rootName}` , if no file is open we have a trailing dash which is what `${separator}` is supposed to prevent.

**Comment by bpasero** [comment]
@lanzkron so to clarify, you would leave the separator out if one of the sides is a variable that is not defined?

**Comment by lanzkron** [comment]
@bpasero thanks for your responsiveness! 
I have to admit that I haven't formalized this in my head completely. I think that I would include the separator if it has non-empty values on both sides (and collapse consecutive separators).

**Comment by bpasero** [comment]
I pushed a fix for this, I think its fine to show the separator when surrounded by text (either from static text or from another variable).

**Comment by lanzkron** [comment]
@bpasero Wow! I wasn't expecting such quick response, thanks!!

BTW, you probably want to update the documentation string while you're at it.

**Comment by bpasero** [comment]
@lanzkron thanks I forgot that and I am on it :)
