### ISSUE TITLE
Multiline editor tabs #missing-feature-workaround

### ISSUE THREAD

**Issue by maks187** [Microsoft/vscode#45190]
For some who don't want to wait, till the feature [https://github.com/Microsoft/vscode/issues/32836](https://github.com/Microsoft/vscode/issues/32836) is implemented, one could use the following "workaround" to enable multiline editor tabs in vscode:

- install the vscode plugin "vscode-custom-css" [https://github.com/be5invis/vscode-custom-css](https://github.com/be5invis/vscode-custom-css)

- create for example in your documents directory the following two files:
the "vscode_custom_styles.css" file (it creates the multiline tab-list) replace the 105px entries with a multiply of 35px (3 lines = 35px*3=105px, 2 lines = 35*2=70 and so on..) if the space is overflow the available space, the tab-bar will start to be scrollable by mouse:
```
.monaco-workbench>.part.editor>.content>.one-editor-silo>.container>.title {
  height: 105px;
}

.monaco-workbench>.part.editor>.content>.one-editor-silo>.container>.title.tabs>.monaco-scrollable-element {
  height: 105px;
}

.monaco-workbench>.part.editor>.content>.one-editor-silo>.container>.title .tabs-container {
  height: 105px;
  display: block;
  overflow: auto !important;
}

.monaco-workbench>.part.editor>.content>.one-editor-silo>.container>.title .tabs-container>.tab.sizing-fit {
  float: left;
  margin-bottom: 1px;
  padding-top: 10px;
}
```
the "vscode_custom_scripts.js" file (it manages that on project-explorer tree selection, tab-adding and tab-closing, the view does scroll to the active tab; the check is done all 500ms..):
```
var lastTab = {};
var lastTabsCount = {};
window.setInterval(function() {
  var tabsLists = document.getElementsByClassName("tabs-container");
  for(var i=0;i<tabsLists.length;i++) {
    var tabsList = tabsLists[i];
    if(typeof tabsList !== 'undefined') {
      var role = tabsList.textContent;
      if(!(typeof lastTab[role] !== 'undefined')) {
        lastTab[role] = null;
        lastTabsCount[role] = -1;
      }
      var tabsCount = tabsList.children.length;
      var tabsCountChanged = (lastTabsCount[role] != tabsCount);
      lastTabsCount[role] = tabsCount;
      var tab = tabsList.getElementsByClassName("active")[0];
      if(typeof tab != 'undefined') {
        if(tab != lastTab[role] || tabsCountChanged) {
          var target = tab;
          target.parentNode.scrollTop = target.offsetTop - target.parentNode.offsetTop;
          lastTab[role] = tab;
        }
      }
    }
  }
}, 500);
```
- then open your vscode settings and extend it with (xxxx = your os-username):
```
"vscode_custom_css.imports": [ 
   "file:///C:/Users/xxxx/Documents/vscode_custom_styles.css",
   "file:///C:/Users/xxxx/Documents/vscode_custom_scripts.js"
],
```
- finally following the docs of the above mentioned plugin und restart/reload vscode and you should have a multiline editor tabs line

I hope someone can find some positive in this. For me I can finally delete atom from my system.. ;)

- VSCode Version: 1.20.1
- OS Version: Windows 10/MacOS

**Comment by bpasero** [comment]
I appreciate the hint, but we do not promote this kind of patching of VS Code.
