### ISSUE TITLE
Dialog to uninstall extension with dependencies is a bit weird

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45197]
![image](https://user-images.githubusercontent.com/900690/37090007-f853bb30-2202-11e8-9579-cc5a07f9a598.png)

Maybe put "Uninstall" to the button labels?

**Comment by camilogiraldo** [comment]
How can I contribute to this ? Any help around ?

**Comment by sandy081** [comment]
@camilogiraldo Here is the reference to the [code](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L556) from where this dialog comes from.

**Comment by camilogiraldo** [comment]
Thanks @sandy081,  here's what I purpose for button labels. What do you guys think ?

		const buttons = [
			nls.localize('uninstallOnly', "Extension only"),
			nls.localize('uninstallAll', "Uninstall all"),
			nls.localize('cancel', "Cancel")
		];

Can anyone point me on how can I reproduce the dialog above, I've tried with a couple extensions and just the _uninstallConfirmation_ (without dependencies) pops up

**Comment by sandy081** [comment]
@camilogiraldo Try uninstalling extension packs like `PHP Extension Pack`

**Comment by camilogiraldo** [comment]
@sandy081  I've tried downloading _PHP Extension Pack_ from marketplace and then installing manually and doesn't seem to work. How can I search for extensions in the development environment for installing them ? Or how that works in the dev env. 
Thanks in advance

**Comment by sandy081** [comment]
Dev environment does not have market place support and it is available only in main product. Sorry that I cannot let you know to enable the market place support in Dev. But, I can help you with other way.

- Install all dependencies of PHP Pack first and then install the pack
![image](https://user-images.githubusercontent.com/10746682/37450431-dd7e5e12-2853-11e8-93be-5d39b71a6f80.png)
- Now uninstall the pack

**Comment by Tyriar** [comment]
<img width="513" alt="screen shot 2018-03-30 at 10 52 48 am" src="https://user-images.githubusercontent.com/2193314/38147764-9075b7b2-3408-11e8-96a1-0bb76e465770.png">
