### ISSUE TITLE
Problem matcher severity handles "Note" and "Hint" as errors

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#452]
I'm using a problem matcher that handles compiler outputs. The messages can have the severities `Note`, `Hint`, `Warning`, `Error` and `Fatal`.
The last three are displayed correctly but the first two severities are displayed as errors two. Can I define a mapping for serverities anywhere?

**Comment by dbaeumer** [comment]
A problemMatcher has a severity property. The property will be used as a default value when no severity can be located in the message itself. In you case:

```json
			"problemMatcher": {
				...
				"severity": "warning"
				...
			}

```

Should do the trick.

**Comment by Wosi** [comment]
Thanks, but that's not a solution at all.
The severities `Note` and `Warning` are now handled correctly but `Fatal` has now the new default severity too.
Is there a way to declare my own mapping for severities?

**Comment by dbaeumer** [comment]
@Wosi currently not. I reopen the issue.
