### ISSUE TITLE
Auto imports from suggestions is unreliable

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#45205]
- VSCode Version: 1.20.1
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Start typing name of identifier
2. Suggestions automatically appear but missing info/option to auto import

![image](https://user-images.githubusercontent.com/921609/37093880-dd208504-2208-11e8-843e-865551828e00.png)

3. Continue typing and observe that info/option to auto import still does not appear
4. Close the suggestions and re-open them with `ctrl+space`
5. Suggestions appear with info/option to auto import

![image](https://user-images.githubusercontent.com/921609/37094001-4a16bbf6-2209-11e8-9936-fc4d40161945.png)

Does this issue occur when all extensions are disabled?: Yes

Notes: I haven't yet tried reproducing this in a small isolated project. I'm observing this in a reasonably sized TypeScript project.

**Comment by mjbvz** [comment]
Please share an example project if you are able to come up with a reliable repo. Also, make sure you are using VS Code 1.21 with TS 2.7.2. The TS update brought a few fixes for auto imports

**Comment by OliverJAsh** [comment]
Using either 2.6.1 or 2.7.2, I can't reproduce in a small project, but I can reliably reproduce it every time in a large project.

![image](https://user-images.githubusercontent.com/921609/37456980-91970d02-2838-11e8-9dd3-a17b4f0de2ec.png)
