### ISSUE TITLE
Selected launch configuration inconsistency

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45203]
VS Code 1.20.1

While trying to reproduce https://github.com/Microsoft/vscode/issues/45046 I was running into this inconsistency:

![2018-03-07_12-44-23](https://user-images.githubusercontent.com/1898161/37090750-d356ddaa-2205-11e8-9146-4472b4b3f6f2.png)

Note that a currently selected (and valid) launch config exists but the gear shows an error and F5 asks for creating a launch config (which should only happen if no launch,json exists).

After selecting node.js I got this:

![2018-03-07_13-46-11](https://user-images.githubusercontent.com/1898161/37092963-f96da2dc-220d-11e8-9e90-9ee530e0f8ab.png)
 
And after dismissing VS Code opens the User settings:

![2018-03-07_13-57-33](https://user-images.githubusercontent.com/1898161/37093410-88de7ad0-220f-11e8-87ff-91b5e10d4cf2.png)

This bug could actually explain https://github.com/Microsoft/vscode/issues/45046.

**Comment by weinand** [comment]
I am not able to reproduce this in Insiders (1.21.0)

**Comment by isidorn** [comment]
I made some refactoring around this at the start of this milestone.
This work is captured here https://github.com/Microsoft/vscode/issues/42630
Since you can no longer reproduce I will close
