### ISSUE TITLE
Integrated terminal content disappears when parent window resized

### ISSUE THREAD

**Issue by cemremengu** [Microsoft/vscode#45201]
I have a setup where laptop connected to a larger monitor as extended display. If I move vscode from the large screen to my laptop screen then resize, the terminal content disappears and becomes dark and unresponsive. 

I need to restart terminal after that.

Running on windows, v1.20.1

**EDIT:**

This actually happens on my large monitor as well, just noticed.

1) Maximize the screen, open integrated terminal

2) Make the screen smaller (either from top right button or dragging with mouse)

3) Maximize the screen again

![image](https://user-images.githubusercontent.com/1297759/37091033-c208deb0-2217-11e8-8ebc-a4067bc4ed40.png)

**Comment by zdiemer** [comment]
Seeing the same issue. I'm on Windows 8.1, running Visual Studio Code version 1.20.0. I move my windows across monitors a lot, and each time the terminal is cleared.

**Comment by Tyriar** [comment]
This is fixed in Insiders, should hit stable soon.
