### ISSUE TITLE
Extension Manifest (package.json) schema out of date

### ISSUE THREAD

**Issue by tboby** [Microsoft/vscode#45208]
The schema used to validate the `package.json` of VS Code extensions appears to be out of date.

The docs [Extension Manifest](https://code.visualstudio.com/docs/extensionAPI/extension-manifest) mention several fields such as `qna` and `engines` which are do not autocomplete nor have hover text.

It looks like the schema is defined [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/common/extensionsRegistry.ts), and is simply out of date. The [manifest in vsce](https://github.com/Microsoft/vscode-vsce/blob/master/src/manifest.ts) lists them all however.

- VSCode Version: 1.20.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open an extension's package.json
2. Hover over the json element with key "qna"

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
I don't know what `qna` means.

**Comment by tboby** [comment]
The attribute "qna" in the package manifest? E.g. hover over one of the attributes defined in the manifest, but not in the schema.
