### ISSUE TITLE
"developer" should not be localized

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#45206]
### Issue Type
Bug

### Description

![developer](https://user-images.githubusercontent.com/24318019/37094148-cfff8c28-224c-11e8-8715-d17c878a8771.png)
The marked place should not be localized.
1. Open the Command Palette
2. Enter "developer"
3. cannot find "Show Running Extensions"
![screen](https://user-images.githubusercontent.com/24318019/37094400-bd709b64-224d-11e8-9e7a-b4cf95637591.gif)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|7.89GB (4.12GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
debugger-for-chrome|msj|4.1.0
vscode-icons|rob|7.20.0

</details>
Reproduces without extensions

**Comment by danyeh** [comment]
@dbaeumer , that line of text should not pull from localized string. Is it a code issue?
Or let me know which one should be reverted. https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hans/$/112007860?q=Developer

**Comment by dbaeumer** [comment]
Not sure who owns it. Starting with @sandy081

**Comment by shizengzhou** [comment]
@dbaeumer , In https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensions.contribution.ts, I change "Show Running Extensions" to "Developer: Show Running Extensions" and rebuild vscode, then it is right. I think "Reinstall Extension..." should also be "Developer: Reinstall Extension...".
![developer](https://user-images.githubusercontent.com/24318019/37151322-f967c63e-230f-11e8-8e68-b9a028e843e2.png)
