### ISSUE TITLE
Remove automatic adding whitespace and semicolon with return statement

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/vscode#45217]
This is annoying especially as follows.

```ts
function f() {
  0
}
```

```ts
function f() {
  return ;0
}
```

With the plane code, this semicolon prevents to make a newline.

```ts
function f() {
  if (cond) return ;
  ;
}
```

It should be

```ts
function f() {
  if (cond) return
                  ^ cursor, no adding whitespace.
}
```
 or

```ts
function f() {
  if (cond) return;
                  ^ cursor, don't make duplicate semicolon as with closing brackets.
}
```

**Comment by kieferrm** [comment]
Can you pls provide concrete steps how to reproduce the problem? What file types do you work with? What are your settings? What extension do you use? It would be best if you use the Help>Report Issue to report your issue so that we have some context.

**Comment by falsandtru** [comment]
> Report Issue to report your issue so that we have some context.

I couldn't do that because that doesn't use my default browser.

- VSCode Version: 1.20.1
- OS Version: Win10 pro
- File type: .ts

```
// Place your settings in this file to overwrite the default settings
{
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Visual Studio Dark",
    "vim.ignorecase": false,
    "vim.useSystemClipboard": false,
    "typescript.tsdk": "./node_modules/typescript/lib",
    "typescript.locale": "en"
}
```

Steps to Reproduce:

1. Input `return` statement by autocompletion.
2. Autocompletion inputs `return ;` but it is not useful.


Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This likely is coming from one of your snippets, either snippets from an extension or one of your user snippets. Please try disabling all extensions to track down which one is causing this

**Comment by falsandtru** [comment]
VSCode displays only the vim in the installed extension list and I disabled it. *What else is there?*  Or unlisted builtin extension?

**Comment by falsandtru** [comment]
This is reported by vscode.

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vim|vsc|0.11.0


</details>

**Comment by mjbvz** [comment]
Actually there is a weird built-in TS only snippet for this. I'll remove them as they don't seem all that helpful
