### ISSUE TITLE
Find references don't reuse editors from the different editor group

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode#45213]
To reproduce:
- open an editor with a reference in one group
- open an editor with a declaration in another group
- run find references on the first editor and try to navigate to the declaration

A new editor will be opened in the first editor group instead of navigating to the second editor.

**Comment by akosyakov** [comment]
Could be related to https://github.com/Microsoft/vscode/blob/9389389e429454f9ad41d061269a65def73188d1/src/vs/editor/contrib/referenceSearch/referencesController.ts#L204-L214

**Comment by jrieken** [comment]
Yeah, that's the designed behaviour because didn't think jumping left and right is desired. You can always open a reference to the side with a alt/cmd+click
