### ISSUE TITLE
Add icon path to QuickPickItem class

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45214]
In https://github.com/Microsoft/vscode/issues/39132#issuecomment-347150077 I was advised to use my own picker in place of showWorkspaceFolderPick so that I could customise which folders appear. I'm now trying to do that but found that it only takes in a `string[]` so you can't achieve the same UI as the built-in one which puts the leaf folder name first:

![picker](https://user-images.githubusercontent.com/1078012/37102831-ab39b782-2220-11e8-9411-a13e8998399b.png)

It would be great if we could provide it some custom object with some properties for labels and then get the whole object back on selection (eg. so we don't have to look a complex object back up from the returned string).

**Comment by bpasero** [comment]
@DanTup I think you can do most things, e.g. pass in a [`QuickPickItem`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1495) that allows you to set both label and description.

The one thing missing though is support for showing folder icons:

![image](https://user-images.githubusercontent.com/900690/37241500-88144056-245a-11e8-92c6-b682e2f78e38.png)

That could probably be achieved by allowing to set some resource URI property for the quick pick item.

**Comment by DanTup** [comment]
@bpasero Oh, I somehow only saw `string[]` and not `QuickPickItem`! That does pretty much solve the problem I had (which was showing the leaf foldername separate to the path).

Having an icon path would be cool so I'll rename this, but it's of far less importance to me now I can use `QuickPickItem`. Thanks!
