### ISSUE TITLE
Provide debug adapter executable the arguments for the debug session

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45220]
I recently merged my two debuggers and started using `adapterExecutableCommand` to switch between my project types to allow debugging without a `launch.json`.

However, while trying to support projects in sub-folders (and unit testing, which works differently to debugging on the device) I've discovered that I need to know the `program` and/or `cwd` for the session being launched in order to know which of the debuggers to launch.

Currently, adapterExecutableCommand (and it's replacement, `DebugConfigurationProvider.debugAdapterExecutable`) are only provided the workspace folder.

Is it possible to provide more information about the session being started? I need it to support people that have projects in sub-folders of their root and for running tests.

**Comment by isidorn** [comment]
`debugAdapterExecutable` is still in preview so we could potentialy change it if we decide to.
Fowrading to @weinand since he is the author of that api

**Comment by DanTup** [comment]
It would be nice if we could bail out of this gracefully too. Currently if a user sets `program` to `${file}` and then hits F5 after switching to a json file or something, it gets through to the debug adapter. It'd be nice if we could handle this in the UI better (show a message that the current file is not valid for launching/debugging).

**Comment by weinand** [comment]
@DanTup your last request is covered by #44411

**Comment by DanTup** [comment]
@weinand The issue I noticed was actually for when the active file was the wrong file type, not that there was no active file. I noticed it because I switched to my launch.json and added `${file}` and then hit F5 again, and my debugger tried to run launch.json as a Dart script.

**Comment by DanTup** [comment]
I've raised a new case that I think would be a much better solution to my problem - which is allowing sub-folders in explorer to be WorkspaceFolders - see https://github.com/Microsoft/vscode/issues/45399

**Comment by DanTup** [comment]
I tried to workaround this issue by making a single debug adapter that could delegate to an adapter selected at `launchRequest` time. However, it seems like newing up my own instance of a `DebugSession` doesn't work, as it's not connected to the debugger client in the same way.

@weinand Is there an easy way to "proxy" a set of `DebugSession`s without having to rewrite them (eg. they make `super.xxxRequest` calls which don't work if I created the DebugSession myself).

**Comment by weinand** [comment]
You could run the debug adapter(s) completely on your own inside the extension. See section "Run a debug adapter inside the debug extension" in https://code.visualstudio.com/updates/v1_20#_debug-api. With that approach you can do anything.

**Comment by DanTup** [comment]
@weinand I was under the impression that was for debugging convenience, but is it reasonable/a good idea to do that for shipping to end users? And if so, is that API stable enough that it won't break on us?

**Comment by weinand** [comment]
There are already debug extensions out there that use this approach, e.g. Java.
What API? :-)

**Comment by DanTup** [comment]
Ok cool! Now I'm wondering why we had it in another process in the first place? That caused much complication, now I'm thinking we can simplify a huge bunch of things!

**Comment by weinand** [comment]
Many DAs are not written in JS/TS but in C# or C++. How do you want to run them in the extension host?
And better make sure that your DA frees up all resources properly. Running a DA for one session as a separate process is more fault tolerant than running it continuously as a server for a week...

**Comment by DanTup** [comment]
> Many DAs are not written in JS/TS but in C# or C++

I was actually wondering about writing ours in Dart, but wasn't sure if the over-the-wire protocol was well defined and how much logic there was inside the nodejs package. Is there info on the protocol somewhere I can read up?

> And better make sure that your DA frees up all resources properly

Yep, understood. We're mostly just proxying onto the Dart VM so there's only really one process for us to track, so this should be easy enough.

**Comment by weinand** [comment]
The wire protocol is defined [here](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json) and the corresponding [TS source](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts) is generated by this trivial [tool](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/src/generator.ts).
Other generators seem to exist for C# and Java. You could write one for Dart ;-) 

The TS library does not contain a lot of logic (see https://github.com/Microsoft/vscode-debugadapter-node/blob/master/adapter/src/debugSession.ts).

The only interesting thing might be the code that deals with the (legacy) JSON-RPC.

**Comment by DanTup** [comment]
@weinand Cool, thanks for all the info. In the short-term I'll see whether moving the DA in-process solves the original problem for me.

**Comment by weinand** [comment]
Or just launch it yourself but still run it as a separate process.

**Comment by DanTup** [comment]
How simple is that/ I had a look in the repo and found [this doCreateProcess method](https://github.com/Microsoft/vscode/blob/6c8b65d1e8735092c3dc6ceaacb06febb9b62fe0/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L848) but it seems to be doing a lot. Which is the correct part for me to copy/call from my resolveDebugConfig?

Thanks!

**Comment by weinand** [comment]
Noooooooo!

Just a `cp.spawn("node", [ "dart-debug.js" ])`.

**Comment by DanTup** [comment]
Oooh, gotcha! I'll give it a go - thanks! :)

**Comment by weinand** [comment]
Did you try to run your DA inprocess? 
Just move the `DartDebugSession.run(DartDebugSession);` line to a separate file (e.g. like I did for Mock: https://github.com/Microsoft/vscode-mock-debug/blob/master/src/debugAdapter.ts)

and in your `resolveDebugConfiguration` method adapt the code from https://github.com/Microsoft/vscode-mock-debug/blob/9cdbe95adad6fbecdc85055f286f0c7391539a65/src/extension.ts#L66-L76 to this:
```
			// start port listener on launch of first debug session
			if (!this._server) {

				// start listening on a random port
				this._server = Net.createServer(socket => {
					const session = new DartDebugSession();
					session.setRunAsServer(true);
					session.start(<NodeJS.ReadableStream>socket, socket);
				}).listen(0);
			}

			// make VS Code connect to debug server instead of launching debug adapter
			config.debugServer = this._server.address().port;
```

**Comment by DanTup** [comment]
It seems to launch, but fails with ENOENT spawning my VM - I wonder if it's the working directory? But I'm not sure how to set that from the code above?

By the way - why don't I have the `debugServer` property on my DebugConfig? I had to cast:

`(config as any).debugServer`

I've got my engine in package.json set to v1.21 and have run `npm install` to get latest, but it's not there (yet I can see your code assigning it?)

**Comment by DanTup** [comment]
Actually, I'm not sure it's working - debugger never seems to recieve the launch request. This is the code I have in my `resolveDebugConfiguration`:

```
// Start port listener on launch of first debug session.
if (!this.debugServer) {

	// Start listening on a random port.
	this.debugServer = net.createServer((socket) => {
		const session = new DartDebugSession();
		session.setRunAsServer(true);
		session.start(socket as NodeJS.ReadableStream, socket);
	}).listen(0);
}

// Make VS Code connect to debug server instead of launching debug adapter.
const c: any = config;
c.debugServer = this.debugServer.address().port;
return c;
```

Just seems to silently do nothing when run (this code does run, but nothing happens in the test extension host - debugger toolbar never appears, etc.). I've turned on All Exceptions and Promise Rejects in the debugger, but nothing.

**Comment by weinand** [comment]
If you are running the DA in-process, it is now trivial to debug your DA as part of the extension in VS Code.

Just "F5" and in the new window open a dart project and  start debugging with "F5".

Is your resolve method hit?
Is your DartDebugSession started correctly?
Does the returned launch config look right?

**Comment by DanTup** [comment]
It calls resolve, and everything looks good (except I had to do the weird cast mentioned above because `debugServer` is missing), however after I've stepped to the end of resolve, it never seems to hit launchRequest inside the DA and the extension host never seems to get into a debug session.

I can't see anything different to yours though.

This is the exact change:

https://github.com/Dart-Code/Dart-Code/commit/c3dd0c594b5f4fa7784f16135205389e0aa409c6

I tried both with DartDebugSession and FlutterDebugSession, but see same behaviour. I'll have to try debugging more tomorrow or next week.

**Comment by DanTup** [comment]
@weinand Ok, getting somewhere! My failure to launch was a typo - I had two variables, `config` and `debugConfig` and I was returning the wrong one (a wrapper over the settings!). The ENOENT was a bug I'd introduced recently (quoting calls to `spawn` and forgetting to set `shell: true` in one place).

So, everything is good except I don't understand why I need this cast and you don't:

```
(debugConfig as any).debugServer = this.debugServer.address().port;
```

My `debugConfig` only has name/type/request (and an indexer) but yours seems to have the `debugServer` property. I'm on 1.27 of debug adapter and debug protocol and 1.21 of vscode.d.ts. Any ideas?

**Comment by DanTup** [comment]
@weinand I have no need for this now, the above solution works fine, so feel free to close. I am still confused by thing mentioned in my last comment though; I'm not sure why I get a compile error and have to cast `DebugConfiguration` to `any` because it doesn't have a `debugServer` property, but yours seems to.

**Comment by weinand** [comment]
In the proposed API I've added a new method `provideDebugAdapter`:

https://github.com/Microsoft/vscode/blob/3193667fc47265a5605bc260be38de0ad432a461/src/vs/vscode.proposed.d.ts#L479-L500

The previous method `debugAdapterExecutable` is still available but we plan to remove it as soon as the new method gets approved.

The new method makes it possible to run a node.js based debug adapter "inline" in the extension with this:

```ts
private _server?: Net.Server;

provideDebugAdapter(session: vscode.DebugSession, folder: WorkspaceFolder | undefined, executable: vscode.DebugAdapterExecutable, config: DebugConfiguration, token?: CancellationToken): ProviderResult<vscode.DebugAdapterDescriptor> {

	// start port listener on launch of first debug session
	if (!this._server) {

		// start listening on a random port
		this._server = Net.createServer(socket => {
			const session = new MockDebugSession();
			session.setRunAsServer(true);
			session.start(<NodeJS.ReadableStream>socket, socket);
		}).listen(0);
	}

	// make VS Code connect to debug server instead of launching debug adapter
	return new vscode.DebugAdapterServer(this._server.address().port);
}
```

/cc @rodrigovaras @jasonramsay

**Comment by DanTup** [comment]
@weinand For DAs already spawning their own server in-process in the resolve method, is there value in moving that code to `provideDebugAdapter`?

**Comment by weinand** [comment]
@DanTup for the time being, the only value in moving that code to `provideDebugAdapter` is that you do not have to use the `debugServer` attribute to communicate the port number back to VS Code.
