### ISSUE TITLE
Warn users if the terminal font is not monospace

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#45226]
As a workaround for https://github.com/Microsoft/vscode/issues/35681, we could measure characters, maybe `i` and `w` and tell the user to use a monospace font if they differ.

**Comment by RubenMateus** [comment]
I would really like to help on this one has my first issue on vscode repo.

**Comment by Tyriar** [comment]
@RubenMateus that would be great!

To give you some pointers, there is an element used for measuring characters here:

https://github.com/Microsoft/vscode/blob/05b995dd9c99b709f41577ab04fe53740f67ccea/src/vs/workbench/parts/terminal/electron-browser/terminalConfigHelper.ts#L31

I see this as a new function on `TerminalConfigHelper` similar to `_measureFont` which checks the 2 characters and verifies they're the same width. This can be called by `TerminalPanel` when the font changes and show a notification (by adding `INotificationService` to constructor) if it's different:

https://github.com/Microsoft/vscode/blob/05b995dd9c99b709f41577ab04fe53740f67ccea/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L78-L82

**Comment by jay-khatri** [comment]
@Tyriar have there been any developments on this issue? I'd love to take a look!

**Comment by Tyriar** [comment]
@jay-khatri not yet, go for it 😃

**Comment by jay-khatri** [comment]
@Tyriar I took a look and wanted to clarify. I understand that the point of this is to confirm whether or not a font is monospace. With that being said, am I expected to render an actual html element and measure the difference among two separate letters? I'm now pretty familiar with the code organization, just a little confused as to how to approach measuring the font :slightly_smiling_face:

**Comment by jay-khatri** [comment]
Ping @Tyriar :grimacing: :slightly_smiling_face:

**Comment by a8t** [comment]
@jay-khatri  What do you think of this? https://github.com/atom/atom/issues/6055 (I haven't looked at the VSCode source at all ftr)

**Comment by Tyriar** [comment]
@jay-khatri yes, by utilizing `_charMeasureElement` which I believe has font assigned to it

**Comment by Tyriar** [comment]
#48028 adds the following notification when the terminal font is changed:

![image](https://user-images.githubusercontent.com/2193314/40556625-31f5d688-6002-11e8-9778-5e8b976d82d4.png)

**Comment by roblourens** [comment]
Works, but I don't see the notification if I have the terminal closed, then change the font setting, then open the terminal. I think it should be shown in that case too.

**Comment by Tyriar** [comment]
@rebornix any ideas on whether the editor has something to leverage here? Basically I need some element to measure the width of `w` and `i` to check if it's really a monospace font but it only works when the panel is visible. I don't really want to break out of the panel element and touch things that the terminal doesn't own.

**Comment by Tyriar** [comment]
I'm toying with the idea of supporting this in xterm.js by specifying a `measureContainer` element to do the measurements in https://github.com/xtermjs/xterm.js/issues/702. That would move the logic upstream, it would still be a little weird for me to put this element somewhere outside of the terminal panel though.

Ping @rebornix
