### ISSUE TITLE
Multi-root Workspace folder display names

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode#45227]
### Issue Type
Feature Request

### Description

I would like to be able to 'rename' root folders in a multi-root workspace. That is, I want to be able to set a 'display name', 'nickname', or alias for the roots. So if I have multiple root folders in my workspace all named 'Project', I can rename them to 'Project Libraries', 'Project Services', 'Project Client', etc.

Example:

* Workspace
  * Project
  * Project
  * Project

=> Run command to 'Set display name of workspace folder' (for each Project)

* Workspace
  * Project Libs
  * Project Services
  * Project Web App

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

**Comment by bpasero** [comment]
@firelizzard18 you can assign a `name` property to each root folder in the workspace file.
