### ISSUE TITLE
"configure locale" is very technical

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4522]
Today I was trying to find the action to change the language and was just searching for "language" and could not find it. I am not sure if "Locale" is something a user would typically search for. On Mac OS at least the setting is called "Language and Region" and on Windows 10 "Language". 

I think we:
* should call it "Change Language"
* keep it english and not translate it

@dbaeumer fyi

**Comment by dbaeumer** [comment]
+1 to chance this to Language. But lets wait until we do the Menu work and then change this once.

**Comment by bpasero** [comment]
Maybe at least do the nls change for March, I think that is low risk and helpful.

**Comment by dbaeumer** [comment]
@egamma what is your take on this?

**Comment by dbaeumer** [comment]
I mean I can change the sting so that the UI says Configure Language. The json file would still talk about locale.

**Comment by dbaeumer** [comment]
I opt to keep Configure Language to avoid any problem with Change Language Mode. In addition Change is currently hot. Configuring the language will never be.

**Comment by dbaeumer** [comment]
OK. I fixed this for March and pushed to release/1.0.0. 

Discussed the naming with @egamma  and we agreed on 'Configure Language'

**Comment by bpasero** [comment]
:+1:
