### ISSUE TITLE
Using relative operator for es6 import path isnt followed by vs-code.

### ISSUE THREAD

**Issue by roemhildtg** [Microsoft/vscode#45223]
### Issue Type
Bug or Feature Request?

### Description

I am working with Javascript es6. If I right click on an imported variable, and select to go definition, the file is correctly opened if the variable is exported from a node_modules module directory. However, if I try to import a variable from my relative project path, using the `~` operator, which means "this project's root" the same functionality does not work. Likewise, the auto suggest for import file paths doesn't work using the `~` operator.

For example:

```javascript
// not working:
import {liftOptionsList} from '~/models/utilities/sanitary/liftStationOptions';

// working
import DefineMap from 'can-define/map/map';
```

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3492)|
|Memory (System)|15.94GB (4.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
beautify|Hoo|1.3.0
vscode-icons|rob|7.20.0

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Did you configure the  `paths` in your `jsconfig.json`? (see [section on path mapping here](https://www.typescriptlang.org/docs/handbook/module-resolution.html))

**Comment by roemhildtg** [comment]
I hadn't tried that. After looking at these docs, it appears I may need a combination of baseUrl with paths perhaps in my config.

Here's some more information about this project. There are two directories with js code. One "server" and one "public". The files in "public" are written in es6 import statements. 

Directories:
```
server/
public/
--jsconfig.json
-- src/
---- components/
------ component1.js
---- config/
------ config.js
```

```javascript
//config.js
import Component1 from '~/components/componen1';
```

So, would I set my paths to be like this, I believe, which I have done. But this also does not appear to work with intellisense. 

```json
{
    "paths": {
        "~/*": ["./src/*"]
    }
}
```

**Comment by mjbvz** [comment]
These should be in `compilerOptions` and you'll need to set baseurl too:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
     "paths": {
        "~/*": ["./src/*"]
    }
  }
}
```
