### ISSUE TITLE
Clicking error indicator multiple times displays fewer errors each click

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4523]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Javascript project or file with a few errors
![6errorindicator](https://cloud.githubusercontent.com/assets/12900364/13930450/472c2c3c-ef5c-11e5-920e-5b3c5b305464.JPG)

2. Click the error/warning indicator at the bottom left (notice the error displayed count, mine says 6)
![6errors](https://cloud.githubusercontent.com/assets/12900364/13930255/8cad0fd4-ef5b-11e5-99c2-f954125e67cd.JPG)

3. Click the error/warning indicator again. The command window shows up again. There are now only 5 errors shown in the window with a blank space at the bottom (where error 6 should be)
![5errors](https://cloud.githubusercontent.com/assets/12900364/13930303/c64376ca-ef5b-11e5-9e95-ab6de156a499.JPG)

4. If you continue clicking the error/warning indicator the displayed errors will go down to only 2 showing (even though there are still 6 showing on the indicator) and empty space for the missing 4 bugs.
![2errors](https://cloud.githubusercontent.com/assets/12900364/13930381/19ad1456-ef5c-11e5-97d7-aa1532e3d643.JPG)

5. If you click it again, it sometime cycles back to show all six but usually shows 5 with a blank space at the bottom.

**Comment by jrieken** [comment]
@bpasero Any chance this is the leak-fix-issue you were talking about?

**Comment by bpasero** [comment]
Looks like it, will verify.

**Comment by bpasero** [comment]
Yes, fixed.
