### ISSUE TITLE
command 'markdown.extension.onEnterKey' not found

### ISSUE THREAD

**Issue by lengyingzi** [Microsoft/vscode#45234]
Issue Type: <b>Bug</b>

Cannot edit markdown file when click `Enter` key。

command 'markdown.extension.onEnterKey' not found

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.54GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.17
indent4to2|Com|0.1.2
vscode-qrcode|Com|0.2.0
vscode-markdownlint|Dav|0.13.0
xml|Dot|1.9.2
vscode-pandoc|Dou|0.0.8
minify|Hoo|0.3.0
latex-workshop|Jam|3.14.0
html-snippets|abu|0.2.1
vscode-caniuse|aka|0.5.3
markdown-emoji|bie|0.0.7
markdown-mermaid|bie|0.1.1
LinkCheckMD|bla|0.1.5
markdown-mail|ccc|1.1.2
regex|chr|0.1.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.7
vscode-faker|dee|1.2.1
prettier-vscode|esb|1.2.2
paste-image-to-qiniu|fav|0.0.1
shell-format|fox|1.1.1
mdmath|goe|2.1.0
live-html-previewer|hdg|0.3.0
vue-snippets-js-html-pug-razor|heb|0.0.3
paste-image-to-aliyun|jas|0.0.2
copy-markdown-as-html|jer|1.0.0
markdown-table-formatter|jos|0.2.3
vscode-xslt-snippets|mar|0.1.0
code-beautifier|mic|1.7.2
pandoc-format|mon|0.0.2
csharp|ms-|1.14.0
team|ms-|1.122.0
vetur|oct|0.11.7
indent-rainbow|ode|0.7.2
open-html-in-browser|pea|0.0.3
ant-tree-viewer|ped|0.3.2
java|red|0.20.0
chai-spec-generator|rin|0.4.0
vscode-icons|rob|7.20.0
preview-vscode|sea|1.4.2
vscode-table-formatter|shu|1.2.1
pdf|tom|0.2.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.2
gitblame|wad|2.2.0
markdown-index|yan|0.3.1
markdown-preview-enhanced|shd|0.3.2
qiniu-upload-image|imy|1.0.0
vscode-reveal|evi|2.0.2
markdown-all-in-one|yzh|1.0.5

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
This is caused by markdown-all-in-one. Please file an issue against this extension
