### ISSUE TITLE
Smoketest times out when running against stable

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45236]
So today me, @RMacfarlane and @sbatten were doing smoke tests, and the test timeed out on all platforms.

We ran the following scripts against latest stable extracted to Desktop.

```
npm run smoketest -- --build /Users/octref/Desktop/Visual\ Studio\ Code.app --stable-build /Applications/Visual\ Studio\ Code.app
```

However, when running without passing in `--build` and `--stable-build`, or passing in the path towards Insider build, the test ran fine.

We briefly looked into the test but did not identify the issue. At the end, we decided to run smoketest against the release branch built from source to not block the release.

**Comment by sbatten** [comment]
During a brief investigation, I found that it was hanging on calls to app.workbench.quickopen, but I stopped investigating when we switched to running from source.

**Comment by octref** [comment]
@joaomoreno Just going over old issues. I believe this is already fixed by you right?

**Comment by joaomoreno** [comment]
Not sure...
