### ISSUE TITLE
Documentation Request: Setup for cross-platform debugging

### ISSUE THREAD

**Issue by ShakenU** [Microsoft/vscode#45238]
I've had no luck at all trying to get VSCode setup to use the integrated debugger to target a remote ARM target (A Rpi).

A good documentation/wiki page would do wonders.

**Comment by isidorn** [comment]
fyi @weinand

**Comment by weinand** [comment]
@ShakenU VS Code does not support "remote debugging" by itself. Remote debugging is always a feature of the debug extension you are using. And whether a debug extension supports remote debugging and how it is set up, should be explained on the corresponding page in the Marketplace. See https://marketplace.visualstudio.com/search?target=VSCode&category=Debuggers&sortBy=Downloads

However, there is one exception: VS Code ships already with a Node.js debugger and it's remote debugging section lives here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging

**Comment by ShakenU** [comment]
Noted, thank you.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1502
