### ISSUE TITLE
The terminal process terminated with exit code: 2

### ISSUE THREAD

**Issue by WardenGnaw** [Microsoft/vscode#45239]
From @joe3524 at ‎Mar‎ ‎6‎, ‎2018‎ ‎6‎:‎19‎ ‎PM‎ ‎PST

I got this error message while building a C file using VSCode and gcc, not g++.

```
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `gcc /Users/joe/Documents/(programming)/[ C]/VSCode/example.c -o example  && ./example '
The terminal process terminated with exit code: 2
```

 This was when I tested a simple .c file with VSCode.

```
#include <stdio.h>

int main(int argc, char * argv[]) {
    printf("Hello World!");

    return 0;
}
```

 It's strange that when I build a cpp file with g++, it works. But it doesn't when I specifies 'gcc' in tasks.json file. 

Here is my tasks.json:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "compile and run C",
            "type": "shell",
            "command": "gcc ${file} -o ${fileBasenameNoExtension} && ./${fileBasenameNoExtension}",
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

I'm running macOS 10.13.3, VSCode 1.20.1.

Copied from original issue https://github.com/Microsoft/vscode-cpptools/issues/1645

**Comment by WardenGnaw** [comment]
I took a quick look. 

The call to gcc is failing due to the path ```Users/joe/Documents/(programming)/[ C]/VSCode/example.c```. I am not sure if ${file} is supposed to escape the escape characters ( e.g. '(' or ']' ) if its within a string, or is it up to the user to put double quotes around it themselves?

**Comment by joe3524** [comment]
No. I just didn't know well as I was new to VSCode yesterday. To my embarrassment.. actually I had to spend a whole day trying to solve this.. You made my day. Thank you!

**Comment by dbaeumer** [comment]
Dups #32400
