### ISSUE TITLE
Ignored keybinding for replacing "ctrl+p" with "alt+2"

### ISSUE THREAD

**Issue by vldmr-bus** [Microsoft/vscode#45230]
- VSCode Version: 1.20.1
- OS Version: Windows 10 

Steps to Reproduce:

1. Add the following entries to your keybindings.json:
```
    {
        "key": "alt+2",
        "command": "workbench.action.quickOpenNavigateNextInFilePicker",
        "when": "inFilesPicker && inQuickOpen"
    },
    {
        "key": "ctrl+p",
        "command": "-workbench.action.quickOpenNavigateNextInFilePicker",
        "when": "inFilesPicker && inQuickOpen"
    }
```
2. Save and try key combinations ctrl-p and alt-2: they still perform their original actions

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by alexandrudima** [comment]
@vldmr-bus

This works as expected AFAICT. We ship by default with two keybindings for `ctrl+p`:
```
{ "key": "ctrl+p",                "command": "workbench.action.quickOpen" },
{ "key": "ctrl+p",                "command": "workbench.action.quickOpenNavigateNextInFilePicker",
                                     "when": "inFilesPicker && inQuickOpen" },
```

The first one binds that <kbd>ctrl</kbd>+<kbd>P</kbd> opens the quick pick and the second one that it goes to the next file. Your edits have changed the second one to <kbd>alt</kbd>+<kbd>2</kbd>.

If you wish to change both, then you must change both.
