### ISSUE TITLE
Quick Open should default-select previous file

### ISSUE THREAD

**Issue by pekeler** [Microsoft/vscode#45232]
Issue Type: <b>Feature Request</b>

When using "Go to File..." (cmd-p on Mac), it shows a list of the recently opened files. The latest file is at the top and it is selected. I believe this would be more useful if the previous file was selected by default. It would allow for much faster back-forwards navigation. All I'd need to do it cmd-p+enter to go to the previous file.

Btw my proposed change is the default behaviour in TextMate.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

**Comment by kieferrm** [comment]
If you use Cmd+P while the file picker is open we keep moving in the file list and also open the editor without you to have to press Enter. So, Cmd+p Cmd+p gives you the previous file. Same number of key strokes you propose.

**Comment by pekeler** [comment]
OMG - thank you @kieferrm ! Yes, this is as good. Guess I can close this already.
