### ISSUE TITLE
Share ux state across machines

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#45242]
Issue Type: <b>Feature Request</b>

I'm loving the new centered layout https://github.com/Microsoft/vscode/issues/15684. I've been keeping two editor groups open even when I only need one to keep code closer to the center.

I'd like a couple of settings exposed so I can enable the centered layout and set its size in my settings.json. Something akin to the `centerMode.autoActivate` and `centerMode.size` proposed in https://github.com/Microsoft/vscode/pull/40757 would be great.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment]
@akbyrd for the size please just move the sashes.
autoActivate you have under zenMode.

What is your use case that is not coverd by what I mentioned above.

**Comment by CurtisBelt** [comment]
@isidorn 

For me the use-case not covered is syncing user settings between multiple computers to avoid as much manual setup as possible on a new computer.

@akbyrd 

I have found that the the Centered Layout toggle (as well as the left/right sizes) is persisting, even through restarts and project switches (Project Manager extension). It turns off for split views, but comes back for single view. Is it the same for you?

**Comment by isidorn** [comment]
@CurtisBelt syncing user settigns between multile computers is a seperate problem from this one which we plan to tackle.
And yes it is designed the way you mention. Preserved across projects, automatically goes off when you have more than 1 view side by side

**Comment by CurtisBelt** [comment]
@isidorn Ah I understand that. I'm on Linux and already sync my settings via dotfiles. What I meant to say is that since the options aren't available, it's just another thing you will have to setup manually on new systems (regardless of sync method). This is relatively minor of course, just wanted to clarify the use case. :+1:

**Comment by akbyrd** [comment]
@isidorn 
> What is your use case that is not coverd by what I mentioned above.

The issue is that the size and whether centered layout is active are hidden and saved globally. All my other settings are in settings.json and can be edited there. But toggling centered layout is the odd man out in that it has to be changed through the command palette.

The setting `zenMode.centerLayout` is not the same thing as `View: Toggle Centered Layout`.  The setting only affects zen mode (which I'm not using) while the command affects non-zen mode editing (which I am using).

For a concrete use case: I copy my settings.json to other machines when I use them. I want *all* my setup to be in my settings file so that I'm instantly good to go. Having other settings that can only be set through commands means I have to remember and run them when configuring a new machine, which defeats the purpose of having a settings file.

**Comment by isidorn** [comment]
Got it. @bpasero do we already have some issue for sharing ux state across machines?

**Comment by bpasero** [comment]
@isidorn we have for sharing settings across machines but I think not for UI state yet.

**Comment by akbyrd** [comment]
Why is `View: Toggle Centered Layout` considered state and not a setting? If things like `editor.minimap.enabled` and `editor.minimap.maxColumn` are settings, can we make a case for  `editor.centerLayout.enabled` and `editor.centerLayout.width`?

I'm not looking to tackle the larger, separate problem of sharing settings. Just the issue of exposing a couple specific settings.

**Comment by bpasero** [comment]
@akbyrd I think there are some things that we consider state that changes frequently, similar to the sidebar being hidden or not (or the panel). For these things a setting did not seem very practical to begin with.

**Comment by akbyrd** [comment]
That seems reasonable. Applied to this situation, 'is the editor currently centered' sounds like the state while 'should the editor be centered' seems like the setting. Whether the editor is currently centered will change frequently, as files are opened and closed. `Toggle Centered Layout` is unlikely to change frequently.

There's support for the toggle being a setting in 1) it's a configuration toggle that is persisted across sessions, 2) the original author and comments in the feature request considered settings to be a good idea, 3) it matches with other settings that decide whether specific behavior should be enabled or disabled, 4) it already has a setting for whether it's used in zen mode so it's unclear why it's a setting in zen mode and state in normal mode.

The width setting is a little fuzzier. On one hand I can see your argument for it being state, on the other we have existing settings for the sizes of things.

**Comment by Yajo** [comment]
I'm seeing this problem just in 1 machine. I like centered layout, but when I switch project (*File: Open recent...*), which I do all the time, each time I have to *Toggle Centered Layout*. It's disturbing.

**Comment by Yajo** [comment]
Let me explain my use case, in case it helps:

- Usually, I use a multi-monitor setup in the office, where I have big screens. There, I want centered layout.
- Sometimes, I unplug the laptop and work in its smaller screen. There, I want full layout.
- I switch from project to project usually.

Right now, it seems the setting is saved somehow as a hidden _project_ setting. IMHO, this should be a (hidden or not) _user_ setting. It's very unlikely that you want centered layout in one project and other layout in other project, since this is mostly an ergonomic setting, and depends on current user physical devices more than on some project-specific thingie.
