### ISSUE TITLE
Source map breaking points stop working after update 1.21.0

### ISSUE THREAD

**Issue by HitalloExiled** [Microsoft/vscode#45243]
Related to #45100

- VSCode Version:
1.21.0
- OS Version:
Windows 10
- Node Version:
v8.8.1

# Steps to Reproduce:

### folder structure
source/index.ts
source/modules/index.ts
source/tsconfig.json

### source/index.ts
```ts
import { text } from "./modules";

console.log(text); // breakpoint here - Works!!
```
### source/modules/index.ts
```ts
export const text = "Hello World!!!"; // breakpoint here - Don't work.
```

### source/tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true,
    "strict": true,
    "esModuleInterop": true
  }
}
```

### .vscode/launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/source/index.js"
        }
    ]
}
```

Does this issue occur when all extensions are disabled?: Yes

I ended up finding out that the problem is related to the outFiles property in launch.json.

It usually works by including the following line
```json
"outFiles": ["${workspaceFolder}/**/*.js"]
```

When the field has no value, the application does not seem to find the source map related to the breakpoint.

In version 1.20.1 this behavior did not occur.

**Comment by weinand** [comment]
@HitalloExiled  What version of node.js are you using?

Please there is an uppercase ".Js" in your outFiles attribute.

**Comment by HitalloExiled** [comment]
Info updated.

> Please there is an uppercase ".Js" in your outFiles attribute.

This was a typo. Fixed.

The real issue here is that the outFiles field was not required for the debug to work correctly in the previous version.

Since most of my settings did not specify this field,
it took me a while to figure out the real cause of the problem.

**Comment by roblourens** [comment]
I don't think that setting a breakpoint in a module besides the initial module, without outFiles set, would have ever worked. I just tried in 1.20 to confirm.

The problem is that without outFiles, we don't know where the sourcemap for that file is until it's loaded. When the breakpoint is set in code that runs immediately when that file is loaded, we don't have time to load the sourcemap before the code under the breakpoint runs.

**Comment by HitalloExiled** [comment]
I do not see the requirement of outFiles as a problem.
Just the fact of having a project that worked without it and stopped working after the update because the field was not informed that caught me off guard.

If the current behavior is intentional, we can give this issue as closed.

**Comment by nicojs** [comment]
I never used `outFiles` before and could always debug my files. Although I sometimes did run into a breakpoint not getting hit if I put it at the very top of the first file, but wrote it of as a fluke.

> I don't think that setting a breakpoint in a module besides the initial module, without outFiles set, would have ever worked. I just tried in 1.20 to confirm.

I can confirm that it did work earlier. After setting the outfiles in 1.21 I'm able to debug once again.

Thanks for this issue, it made my day!

**Comment by peacegiverman** [comment]
This is also an issue for web JS projects. Both Chrome and Firefox extensions fail to stop on breakpoints in 1.21.

**Comment by weinand** [comment]
Is anybody seeing this issue on Windows?

**Comment by weinand** [comment]
@HitalloExiled I try to reproduce this. How do you transpile your TypeScript (task, npm script, etc.)?

**Comment by peacegiverman** [comment]
@weinand Yes, it' happening to me on Windows.

**Comment by weinand** [comment]
I've compared the traces for VS Code 1.19.3, 1.20.1, 1.21.0:

without "outFiles" attribute:

1.21.0:
```
From client: setBreakpoints({"source":{"name":"index.ts","path":"/Users/weinand/MS/Projects/REPROS/bug45243/source/modules/index.ts"},"lines":[1],"breakpoints":[{"line":1}],"sourceModified":false})
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":1,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1000}]}}
From client: setExceptionBreakpoints({"filters":[]})
→ To target: "{\"id\":10,\"method\":\"Debugger.setPauseOnExceptions\",\"params\":{\"state\":\"none\"}}"
← From target: {"id":10,"result":{}}
To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
```

1.20.1:
```
From client: setBreakpoints({"source":{"name":"index.ts","path":"/Users/weinand/MS/Projects/REPROS/bug45243/source/modules/index.ts"},"lines":[1],"breakpoints":[{"line":1}],"sourceModified":false})
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":1,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1000}]}}
From client: setExceptionBreakpoints({"filters":[]})
→ To target: "{\"id\":10,\"method\":\"Debugger.setPauseOnExceptions\",\"params\":{\"state\":\"none\"}}"
← From target: {"id":10,"result":{}}
To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
```

1.19.3
```
From client: setBreakpoints({"source":{"name":"index.ts","path":"/Users/weinand/MS/Projects/REPROS/bug45243/source/modules/index.ts"},"lines":[1],"breakpoints":[{"line":1}],"sourceModified":false})
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":1,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1000}]}}
From client: setExceptionBreakpoints({"filters":[]})
→ To target: "{\"id\":10,\"method\":\"Debugger.setPauseOnExceptions\",\"params\":{\"state\":\"none\"}}"
← From target: {"id":10,"result":{}}
To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
From client: configurationDone(undefined)
→ To target: "{\"id\":11,\"method\":\"Debugger.resume\"}"
From client: threads(undefined)
To client: {"seq":0,"type":"response","request_seq":5,"command":"configurationDone","success":true}
```

The traces show no difference (and I see no behavioural differences: the breakpoint is not hit in these three versions).

**Comment by weinand** [comment]
But then I tried to change the last "variable" in the puzzle: I've varied the version of node.
And now the plot thickens:

If I use a node version < 8.0 I do hit the breakpoint even if there is no "outFiles" attribute.

@HitalloExiled could it be that you were using a node version < 8.0 when running your sample from above in version 1.20.1 ?

**Comment by weinand** [comment]
Question to all affected by this:

What version of node.js were you using when you did not had this problem?
What version of node.js are you using when you experience the problem?

The best way to find node's version is to run `process.version` in the debug console or to add a `console.log(process.version)` to your program.

**Comment by HitalloExiled** [comment]
> @HitalloExiled I try to reproduce this. How do you transpile your TypeScript (task, npm script, etc.)?
> What version of TypeScript?

Just tsc with Typescript 2.7.2.

> @HitalloExiled could it be that you were using a node version < 8.0 when running your sample from above in version 1.20.1 ?

It has been tested on node version 8.8.1.

**Comment by weinand** [comment]
Are you using "nvm-windows" or "nvs"?

**Comment by sarvaje** [comment]
I'm using node v9.5.0. And I haven't used `outFiles` ever. My problem start when I update the stable version to `1.21.0`. I was using the previous version and everything works fine, and in the same day, I updated to the latest version and it started happening.
In fact, I have both version installed (stable and preview), and a couple of days before the stable version update, I start noticing that problem in the preview.

**Comment by weinand** [comment]
I'm asking again: Are you using "nvm-windows" or "nvs"?

**Comment by sarvaje** [comment]
none of them, I have nodejs installed directly.

I also have to say that, `outFiles` doesn't work for me neither.

**Comment by weinand** [comment]
What value are you passing to outFiles?

**Comment by sarvaje** [comment]
`"outFiles": ["${workspaceFolder}/**/*.js"]`

**Comment by roblourens** [comment]
@weinand IIRC, if legacy node-debug doesn't have sourcemaps for a .ts file, it tries to change the extension to .js and set the BP there. This guessing logic was never implemented in node2. That would explain the difference between node <8 and >8.

If someone is still able to hit the BP without outFiles in 1.20, and using node 8+, could you set `"trace": true` in your launch config and upload the log here?

**Comment by HitalloExiled** [comment]
> Are you using "nvm-windows" or "nvs"?

None of them too.

In my case "outFiles": ["${workspaceFolder}/**/*.js"] worked fine.

**Comment by weinand** [comment]
@roblourens the strategy that you describe as available in "legacy" sounds more like a bug to me. I never implemented that deliberately ;-)
But I know that "legacy" will find the source maps for a given source if the generated JS and/or source map lives in the same directory. So it does not need the "outFiles" in that case. This is a more realistic explanation for the problem.
In the case at hand, source maps are generated because tsconfig.ts has a `"sourceMap": true`.

**Comment by roblourens** [comment]
> But I know that "legacy" will find the source maps for a given source if the generated JS and/or source map lives in the same directory.

I think that's what I was thinking of :)

**Comment by weswigham** [comment]
I believe I've been encountering the same issue; One of my launch configs for TypeScript is:
```js
{
            "type": "node",
            "request": "launch",
            "name": "Mocha Tests (currently opened test)",
            "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
            "args": [
                "-u",
                "tdd",
                "--timeout",
                "2000000",
                "--colors",
                "built/local/run.js",
                "-f",
                "${fileBasenameNoExtension}"
            ],
            "env": {
                "NODE_ENV": "testing"
            },
            "stopOnEntry": false,
            "sourceMaps": true,
            "console": "integratedTerminal",
            "preLaunchTask": "tests"
        },
```
which seemed to work well, and would always hit breakpoints until recently. After reading this thread, I can confirm that setting `"outFiles": ["${workspaceRoot}/built/local/run.js"]` causes it to function again, in my case.

**Comment by roblourens** [comment]
@weswigham I tried this in 1.20 and see the same as 1.21 - it works with outFiles, and doesn't work without outFiles, which is what I would expect.

Could you try in 1.20 again, and check whether it then works again without outFiles? If so, could you set `"trace": true`, run and see it work, then upload the log here?

Or someone else who has this issue, try the same thing. What I really need is a log from a run in the old version where this worked without outFiles.

**Comment by weswigham** [comment]
@roblourens I only got 1.21 today, so I'm _pretty sure_ I started having the issue on or before 1.20. In any case, how does one acquire old vscode versions?

**Comment by roblourens** [comment]
You may have gotten 1.21.1 today and 1.21.0 last week? Or, maybe it broke with 1.20.

https://vscode-update.azurewebsites.net/1.20.1/win32/stable

https://vscode-update.azurewebsites.net/1.19.2/win32/stable

**Comment by roblourens** [comment]
The previous one would theoretically work except that it would be very slow. 

This issue is probably https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464, there is a fix in Insiders.
