### ISSUE TITLE
Add `add keybinding` from keybinding-editor

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#45244]
Right now it's possible to Change/Remove/Reset keybinding from the GUI editor. 
But if you want to assign several keybindings to one command - you have to use `keybindings.json`.

**Comment by pabloyshi** [comment]
think it will be useful somehow

**Comment by sandy081** [comment]
Added `Add Keybinding` action 

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/10746682/99078143-2930a580-25be-11eb-8fb6-1c6da2640e84.png">

**Comment by bpasero** [comment]
I think the menu could get some polish: https://github.com/microsoft/vscode/issues/111598
