### ISSUE TITLE
Git UI and `git status` don't agree

### ISSUE THREAD

**Issue by patrickklima** [Microsoft/vscode#45248]
### Issue Type
Bug

### Description

When I use the VSCode Git UI to commit changes, they're not always reflected in the terminal's `git status`. After 6 or 7 commits, the two show very different states. It's hard to tell whether this difference is cosmetic or real, but it's confusing to know the actual status of the local repo. 

To reproduce: 
- create a project in vscode
- make some commits (about 6 or 7?) with the Git UI
- in bash: `git status`
- compare the Git UI to the terminal

I don't know if this is reproducible with extensions disabled. 

![image](https://user-images.githubusercontent.com/14130543/37129896-b37724ea-2246-11e8-959a-ce3bd0724d83.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2494)|
|Memory (System)|7.82GB (1.96GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.7
es7-react-js-snippets|dsz|1.3.3
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.6
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.1.1
theme-karyfoundation-themes|kar|17.0.0
vscode-github|Kni|0.27.1
vscode-exec-node|mir|0.5.0
vscode-cosmosdb|ms-|0.5.0
azure-account|ms-|0.3.1
debugger-for-chrome|msj|4.1.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.7.0

(7 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
What git version do you have installed?

**Comment by patrickklima** [comment]
git version 2.7.4

I synced up after I reported this bug yesterday, so I'm no longer experiencing the issue. I don't know if it would have shown up in the command prompt.

**Comment by joaomoreno** [comment]
OK, will close it then. Note that git is already on 2.16.2, I highly recommend updating.

**Comment by patrickklima** [comment]
More on this: https://github.com/Microsoft/vscode/issues/46007
