### ISSUE TITLE
Emmet completions doesn't work after paste

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#45258]
Hi,

- VSCode Version: 1.21.0
- OS Version: Windows 10 x64

Steps to Reproduce:

![vscode bug](https://user-images.githubusercontent.com/9152330/37135363-4010aa6e-22b2-11e8-985b-3908ff7c97a0.gif)

When I type `.demo`, emmet works fine, but if I copy/paste `demo`, emmet doesn't work. (_after paste if I delete `o` and re-type that emmet works_)

Does this issue occur when all extensions are disabled?: I don't know

BTW, it doesn't happens after update to latest version, it was before that too, but as it's boring, I decided to report that.

Thanks!

**Comment by ramya-rao-a** [comment]
Auto-completions do not get triggered on pasting text in general in VS Code. If you want to get Emmet completions on pasting text you can try the below:
- Press `Ctrl+Space` to trigger completions manually after pasting
- Or set `emmet.triggerExpansionOnTab` to `true` in your settings and press the TAB key after pasting the text.

**Comment by dehghani-mehdi** [comment]
`as-designed` label?! great design guys, time to switch to Atom!

@ramya-rao-a thanks, but your solution is not useful, btw.

**Comment by ramya-rao-a** [comment]
Sorry, my mistake. I assumed you were referring to the absence of the emmet in completion list after pasting the abbreviation.

In your case, adding `"emmet.triggerExpansionOnTab": true` in your settings will expand the pasted abbreviation when you press the tab key. Please read [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet) to understand more.

**Comment by dehghani-mehdi** [comment]
Don't worry,
That settings not really useful, yes, that will fix on paste emmet, but also makes tag on everything if you press tab key and it's not great solution.

**Comment by ramya-rao-a** [comment]
> but also makes tag on everything if you press tab key and it's not great solution.

Yes. That is the reason why that setting is not enabled by default.

In your gif, when you type the abbreviation, you can see the abbreviation expanded in the auto-completion list. This (showing the expanded abbreviation in the auto-completion list) is the default way of expanding Emmet abbreviations in VS Code. 

This is why I suggested pressing `Ctrl+Space` after pasting the text. `Ctrl+Space` is how we **manually** trigger auto-completion in VS Code. And auto-completions are not triggered automatically on paste. This is by design. 

About your comment on Atom, how is Atom any different in this case? I can see that you can paste an abbreviation and then press tab to get the abbreviation expanded. But, every word gets expanded when pressing tab key. That is the same experience you get in VS Code after adding the `"emmet.triggerExpansionOnTab": true` setting.

**Comment by dehghani-mehdi** [comment]
First of all I should mention I'm using VSCode since its very first version and it is already my main editor, I made my own theme, even customizing the file explorer (adding my own rules in workbench.min.css), I mean I like VSCode and switch to another editor is not my first option of course.

I prefer to remove the last char and retype and the hit tab key instead of using `Ctrl+Space`, but `as-designed` label was last thing I expected here, I think its really clear that its a bug.

Atom is great and was my fav. editor before VSCode, but I found VSCode better than Atom, so I switch to VSCode, I'm using Visual Studio a lot, I like see VSCode do that same (as VS), so I can write code faster. emmet on paste works in VS, so I expected the same in VSCode too.

Thanks for your time btw.

**Comment by ramya-rao-a** [comment]
Thank you for the kind words on VS Code.

> I prefer to remove the last char and retype and the hit tab key instead of using Ctrl+Space

That does sound better

> emmet on paste works in VS

Can you elaborate on this? Is there an extension for emmet in VS?

**Comment by dehghani-mehdi** [comment]
You're welcome

> Is there an extension for emmet in VS?
Yes, https://github.com/madskristensen/ZenCodingVS

> Also VS and VS Code are completely different products. We don't share any code in the editor space.
Yes, I know, by "I expected the same in VSCode too" I mean I like to see VS's good things in VSCode too.

> Can you elaborate on this?
How I can help?

**Comment by ramya-rao-a** [comment]
Does that extension work with VS 2015? I tried installing it, fails with 

![image](https://user-images.githubusercontent.com/16890566/37423726-cfa75c9a-277b-11e8-986a-6df623a3b553.png)

**Comment by dehghani-mehdi** [comment]
You need to install [Web Essentials](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebEssentials20153) for VS2015, emmet is part of that in that version

**Comment by ramya-rao-a** [comment]
Looks like what VS does is allow only valid html5 elements in abbreviations to be expanded when pressing the tab key. Where as in VS Code, to allow custom elements in abbreviations, we allow anything to be treated as an abbreviation and expand it when pressing the tab key (assuming `emmet.triggerExpansionOnTab` is set to `true`)

We are back to square 1. You can expand pasted abbreviations on tab, but that also puts you in danger of every tab trying to expand what was typed before. I dont see a good way out of this. I am all ears if you have any ideas.

**Comment by dehghani-mehdi** [comment]
Yes, that's true.
I think the solution is simple (of course maybe needs so refactoring in VSCode core), but tab key should always trigger emmet, no matter after typing or pasting. the only thing that should be check by VSCode is that prev chars before cursor (when press that tab key) is valid and should be expand (by emmet). not the only problem is that extra step (deleting the last chars and re typing that and press tab key) and I think the issue is tab key only trigger after some sort of typing.

**Comment by ramya-rao-a** [comment]
>  the only thing that should be check by VSCode is that prev chars before cursor (when press that tab key) is valid and should be expand (by emmet)

How do you suggest we do this given that we need to support custom elements?

**Comment by dehghani-mehdi** [comment]
I don't think so, custom elements means everything I guess and it can be done using `emmet.triggerExpansionOnTab:true`, so I think standard elements should be the goal of phase 1, then you can extend and support custom elements in proper way.

**Comment by ramya-rao-a** [comment]
> then you can extend and support custom elements in proper way

What would the proper way be?

**Comment by ramya-rao-a** [comment]
The problem is in figuring out what the custom/pre-defined elements are.

One thing that might help your case is to bind the `Emmet: Expand Abbreviation` command to a different keyboard shortcut altogether. This way, you can use your custom keybinding when you want to use emmet, either after typing or pasting text.
