### ISSUE TITLE
VSCode Crashes on saving java file

### ISSUE THREAD

**Issue by prasoonnaik** [Microsoft/vscode#45259]
Issue Type: <b>Bug</b>

when we create a new UNTITLED file and right click on it (located in right pallete) and save it by clicking Save As, after giving a name to the file and clicking SAVE. The IDE crashes. It is happening all the time.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|15.83GB (8.62GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.20.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.2

</details>
Reproduces without extensions

**Comment by rebornix** [comment]
Can you provide the file you are working on?

**Comment by prasoonnaik** [comment]
I created a new file - an untitled file - using code editor itself. and it
crashed. so I do not have a file working at hand

**Comment by rebornix** [comment]
@prasoonnaik sorry for coming back on this issue for too long. Can you still reproduce this issue?
