### ISSUE TITLE
Expose paths constants in API

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#4525]
From mail, from Erich:

> A nit, it currently only works in the `stable` product:
> 
> privateextensionsPath: string= path.join(os.homedir(), '.vscode', 'extensions');
> 
> we should provide some API/constants for the product specific paths so that extensions do not have
to do path-math and getting it wrong.

**Comment by jrieken** [comment]
a workaround would be to use `extensionPath` https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2672

**Comment by jrieken** [comment]
Plan is to encourage using `extensionPath`

**Comment by jrieken** [comment]
Instead of adding another API constant for this special case, I proposed to use the `extensionPath` to figure out the install location: https://github.com/webstp/extension-manager/issues/5
