### ISSUE TITLE
git have 5000 record，How should I close it?

### ISSUE THREAD

**Issue by monty086** [Microsoft/vscode#45250]
- VSCode Version:
- OS Version:

![image](https://user-images.githubusercontent.com/25164433/37131277-9c9cf534-22c2-11e8-8e75-c259502b8d6a.png)

git have >5000 record ,How should I close it?，Don‘t appear again next time

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by BeauAgst** [comment]
Is this not because you haven't added `node_modules/` to your `.gitignore`?

**Comment by joaomoreno** [comment]
@BeauAgst is correct.
