### ISSUE TITLE
_webview.openDevTools does not work with latest vscode

### ISSUE THREAD

**Issue by sriv** [Microsoft/vscode#45262]
Issue Type: <b>Bug</b>

I use `_webview.openDevTools` as suggested [here](https://github.com/Microsoft/vscode/issues/12818#issuecomment-250099171) to inspect custom html shown via `TextDocumentContentProvider`.

This command does not work after upgrading to vscode 1.21. Works with v1.20.

running the command gives an error `command '_webview.openDevTools' not found`.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.13.0-36-generic

Reproduces without extensions

**Comment by mjbvz** [comment]
There's now an official command for this: `workbench.action.webview.openDeveloperTools`
