### ISSUE TITLE
Can't custum markdown style

### ISSUE THREAD

**Issue by Takanashikoucha** [Microsoft/vscode#45260]
Issue Type: <b>Bug</b>
## this config worded before i update the new VScode version
` “markdown.styles”："G:\\DOC\\VScodeMarkdwonCSS\\OneDark.css"`

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|Memory (System)|15.89GB (10.80GB free)|
|Process Argv|C:\Microsoft VS Code\Code.exe C:\Users\koucha\Desktop\TestLab|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
django-snippets|bib|1.1.0
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.17
vscode-clock|Com|0.0.1
vscode-ipaddress|Com|1.0.0
python-snippets|cst|0.1.0
githistory|don|0.4.0
javadebugger|don|0.1.5
jupyter|don|1.1.4
LogFileHighlighter|emi|2.1.1
code-runner|for|0.9.0
vscode-mysql|for|0.2.3
output-colorizer|IBM|0.1.2
badges|idl|1.0.9
emoji-code|idl|0.7.0
MagicPython|mag|1.0.12
vscode-fileheader|mik|0.0.2
vscode-filesize|mkx|2.0.0
python|ms-|2018.1.0
cpptools|ms-|0.15.0
material-icon-theme|PKi|3.2.3
java|red|0.20.0
code-settings-sync|Sha|2.9.0
selectline-statusbar|tom|0.0.2
jinja|who|0.0.8
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|1.1.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Root cause: We now restrict the markdown preview to only loading resources inside the current workspace for security reasons. Workaround is to move the css file into your workspace or publish the css as a markdown extension extension 

I'm hesitant to relax this again even though it is a regression because the old behavior could be abused by a malicious workspace

I'll update the docs to note this restriction

**Comment by Takanashikoucha** [comment]
that's OK,thank you

**Comment by zacjordaan** [comment]
Does this mean that we cannot share _common_ css files amongst multiple projects? 

I have many projects that use my own markdown.css file and it would be tricky to copy that file into scores of .vscode subfolders, and then to update them all from time to time.

Any other workaround?

**Comment by mjbvz** [comment]
Current workaround would be creating [a simple extension](https://code.visualstudio.com/docs/extensionAPI/api-markdown#_changing-the-look-of-the-markdown-preview-with-css) or putting the stylesheets somewhere where you can access them over https

Other possibility on our side: only allow `markdown.styles` to be a user setting and don't allow it as a workspace setting. We can't really go back to the way things were though, even though it was more convenient

**Comment by zacjordaan** [comment]
Thanks for the quick response; I'll give the extension a try, just for fun and learning.

But actually, your suggestion of hosting my css on a web server makes the most sense, especially since it will soon be adopted by others in my department.

**Comment by zacjordaan** [comment]
By the way, the example you gave of using a simple extension, e.g. [Markdown Preview Github Styling](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles) doesn't actually work anymore... neither do other extensions that utilize custom styles.

**Comment by zacjordaan** [comment]
However, the issue appears to be resolved in Insiders 1.22.0

**Comment by mjbvz** [comment]
I'm closing this as-design. The documentation has now been updated and the loading of css from extensions has been fixed in 1.21.1

**Comment by rajinder-yadav** [comment]
So what if I were to place the file under ~/.vscode-insiders is that a security risk also?

**Comment by donnior** [comment]
1. "relative css style file for current workspace" ? why can't we use one global css style file? 
2. "load from https"  ? So I can't use my css style if I don't have WIFI ?

I don't understand why this is "as-designed"
