### ISSUE TITLE
关于  /**/    注释代码的的问题

### ISSUE THREAD

**Issue by ouyangshaolei** [Microsoft/vscode#45268]
Issue Type: <b>Feature Request</b>

 在js中
 当/**/ 注释符出现在 {  后面且二者之间没有空格，会导致所有代码被注释掉,而不仅仅只是注释中间的类容。
例如以下代码会被全部注释掉
const router = new VueRouter( { /* */ 
  routes: [{
    path: '/login',
    component: Login
  }, {
    path: '/user_info',
    component: UserInfo
  }]
})

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

**Comment by rebornix** [comment]
Can't reproduce this issue with vanilla vscode. Please try `code --disable-extensions` to see if it's controlled by some extension. Close for now but we can reopen if you still have this issue.
