### ISSUE TITLE
Typescript syntax highlighting misses instanceof

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#45263]
Not sure whether this is a VSCode or Typescript issue, but posting here to start.

Image is self-explanatory

![screen shot 2018-03-08 at 3 00 12 pm](https://user-images.githubusercontent.com/9585787/37139727-815a4ae6-22e1-11e8-8f43-531e02dd613f.png)

**Comment by mjbvz** [comment]
What is wrong?

**Comment by jpike88** [comment]
instanceof Attribute should have Attribute assume a green highlight

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#578
