### ISSUE TITLE
Cannot erase command properly in integrated terminal (Oh My Zsh)

### ISSUE THREAD

**Issue by AlexYeates** [Microsoft/vscode#45267]
If you use integrated terminal and type a command, and tab to navigate your project, and then try to erase the entire command, it will not erase the first letter.

**Comment by Tyriar** [comment]
How are you "erasing the entire command"?

**Comment by Tyriar** [comment]
If the first letter is just stuck there and isn't part of the next command that's run I think this is a zsh bug as I've repro'd it in other terminals.
