### ISSUE TITLE
Do not offer to push to Git if remote push URL is no_push

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#45271]
There seems to be no official way to prevent pushing to a remote in Git, but people often recommend setting the push URL of a remote to something invalid. (Can't clear it fully because Git would fallback to the fetch URL).

[`git remote set-url --push origin no_push`](https://stackoverflow.com/a/10260389/2715716)

It would be good if the VS Code Git SCM provider could check for `git:`, `ssh:` and `https:` URLs and if it finds an unsupported URL format, hide the Push part of the Sync button in the bottom bar. Pulling should continue to work.

In case white listing protocols is deemed too potentially disruptive (maybe people are using custom protocols?), a black list approach could be considered where `no_push` (and other values?) would cause the push icon to be hidden.

**Comment by joaomoreno** [comment]
I'd go for a blacklist of only `no_push`. PR welcome!

**Comment by TomasHubelbauer** [comment]
@joaomoreno Sounds good, I'll try to take a stab at that.

**Comment by roblourens** [comment]
Should the action item dropdown be hidden or disabled too?

![image](https://user-images.githubusercontent.com/323878/42003455-5e0ddfee-7a20-11e8-8c7b-7b7d7aae4111.png)
