### ISSUE TITLE
no relate .ts use same name interface notice error

### ISSUE THREAD

**Issue by Jesonhu** [Microsoft/vscode#45277]
- VSCode Version: 1.21.0 x64
- OS Version:  Win10

Steps to Reproduce:
1. a.ts 
```
interface Student {
  name?: string
  age?: number
}
```
2. b.ts
```
interface Student {
  name?: string
  age?: number
}
```
+ 1 not use module export
+ 2 a.ts and b.ts no relate only with a workspace
+ 3 can tsc translate to .js and no error

## why vscode notice has error but tsc can complie to js

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
What is the error? Please share the full error text

Also, this only occurs when extensions are enabled? Try tracking down which one causes this

**Comment by Jesonhu** [comment]
error notice: All declarations must have the same modifier.

**Comment by Jesonhu** [comment]
when i create new workspace and create a.ts and b.ts. all is well。so i must think twice. thx u help
