### ISSUE TITLE
Tree: cannot read property isFocused of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45278]
Seeing this in todays insider (not sure about stable): When I press `Cmd+S` to save I get an error:

![image](https://user-images.githubusercontent.com/900690/37146142-35717460-22c3-11e8-8bcf-a96888cc66ef.png)

When I drill into the tree element, it seems to originate from the "Find References" widget. 

Maybe another consequence of the `disposeTemplate` change?

**Comment by DuncanFaulkner** [comment]
Just also upgraded to 1.22 and now seeing this issue

**Comment by marvinhagemeister** [comment]
Found a workaround: Toggling the console seems to resolve this temporary.

**Comment by joaomoreno** [comment]
Fixed by @isidorn in cebb2f35892353b77b08db7f2a2967b6dbcae4bd

**Comment by isidorn** [comment]
I have pushed b8ad382b27 on top of the release branch
@joaomoreno please code reveiw
@bpasero please verify the bug is fixed once we have a stable candidate out

**Comment by isidorn** [comment]
False alarm, @bpasero and me verified this is not reproducable in stabler so I will revert my push on top of recovery.
In case something is seeing this in stable please speak out.
