### ISSUE TITLE
JS config assistent should not propose exclude rule if jsconfig has files section

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4527]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

See screen shot. The jsconfig has a files section which should result in only having the two files in the project. Suggesting exclude rules makes not much sense.

![capture](https://cloud.githubusercontent.com/assets/1931590/13933639/80698614-efae-11e5-945a-05800665ae45.png)

**Comment by jrieken** [comment]
It seems TypeScript told me that a lot more files are part of that project... @dbaeumer In what repo does that happen?

**Comment by dbaeumer** [comment]
I can't remember, but I think it happend in out repository. It suggested to exclude /vs/ folder.

**Comment by jrieken** [comment]
Ok, the problem is that the `files` section has an entry which doesn't exist and therefore the project won't exist.

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#8334
