### ISSUE TITLE
New Integrated terminal is closing when ELECTRON_NO_ASR is overriden in terminal.integrated.env.windows

### ISSUE THREAD

**Issue by ludorival** [Microsoft/vscode#45279]
Issue Type: <b>Bug</b>

I have noticed a regression since 1.21 version:
When the variable ELECTRON_NO_ASAR : 1 is set in the settings, any new opened terminal is automatically closing.
I tested with an empty folder with the current setting
`.vscode/settings.json`
```
{
    "terminal.integrated.env.windows": {
        "ELECTRON_NO_ASAR": "1"
    }
}
```

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.91GB (4.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

![reg_terminal](https://user-images.githubusercontent.com/663754/37146797-1d9b8b9e-22c5-11e8-9f1e-4371690a4735.gif)

**Comment by alexr00** [comment]
It looks like this is no longer happening. I can't reproduce from insiders or master.
