### ISSUE TITLE
Command palette do not remove renamed files properly

### ISSUE THREAD

**Issue by Josema** [Microsoft/vscode#45286]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
solidity|Jua|0.0.31
vscode-simple-icons|Lau|1.8.2
code-settings-sync|Sha|2.9.0
project-manager|ale|0.24.1
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
prettier-vscode|esb|1.2.2
file-icons|fil|1.0.7
vscode-styled-components|jpo|0.0.16
debugger-for-chrome|msj|4.1.0
vscode-icons|rob|7.20.0
vscode-import-cost|wix|2.6.2

(9 theme extensions excluded)

---

Steps to Reproduce:

1. Create a file: ERC20.js
2. Rename the file to: Erc20.js
3. Command + P and search for 'erc20'

Will show up both, and you can go to the file using both.

**Comment by bpasero** [comment]
@Josema can you share a video how you do this or provide more exact steps? This should work.

**Comment by Josema** [comment]
Any resource/software where I can record my screen and upload it easily?

**Comment by bpasero** [comment]
@Josema on macOS I use Licecap which is free

**Comment by Josema** [comment]
![vscode](https://user-images.githubusercontent.com/1819888/37359964-4079ce22-26ef-11e8-8d95-c27d1cd4e10d.gif)

At the end of the example I have three `.gitignore` files that I can select, when actually I only have one. Hope this is clear.

**Comment by bpasero** [comment]
@Josema I can reproduce and this seems to be an issue with our file watcher not recording this change properly.
