### ISSUE TITLE
Int Terminal set to Git on Win launches external window (in addition to integrated).

### ISSUE THREAD

**Issue by DevNicoT** [Microsoft/vscode#45284]
- VSCode Version: 1.21.0
- OS Version: Windows 10

Steps to Reproduce:

1. Within User settings, set "terminal.integrated.shell.windows" to the path of your Git bash executable and save.
2. Now launch the Integrated Terminal from within an open folder in the editor. It will open it both as an integrated terminal and as an external window.
3. Sorry, I edited because I just realized smth else: if you then (that is, once you have both opened) try to close the external window of Git bash, it will also close the integrated one.

Let me know if I can provide any help or any further info, etc.

Does this issue occur when all extensions are disabled?: Yes/No
Yes, confirmed.

**Comment by kieferrm** [comment]
The `git-bash.exe` is not a command processor. You need to use `bash`. You find it in the under C:\Program Files\Git\bin\bash.exe`.
