### ISSUE TITLE
Auto import /[NameOfComponent]/index.tsx

### ISSUE THREAD

**Issue by ConneXNL** [Microsoft/vscode#45289]
I am trying to get auto import to work with my react components using typescript running VSCode 1.21.0-insider. Things seem to work ok but whenever I wrap a react component with a HOC like mobx' observer or recompose' pure I loose the ability to auto import. Is this intended behavior?

**Note that all examples below enable correct VSCode type completion on the react props** ones the import statement is already there. However, example 2 does not work with auto import (to test this I am writing `<ChessI...` (and hit CTRL + Space) in another react component's render method:

**Example 1**
```
// The following works perfectly (auto-import + prop completion on react component)
// File: ChessIcon/index.tsx

import * as React from 'react';
import { observer } from 'mobx-react';

const ChessIcon = observer(class extends React.Component {

    render(){
        return <i/>
    }

});

export default ChessIcon;
```

**Example 2 (the broken one)**
```
// The following doesn't give you auto-import. 
// However, ones you add the import statement manually,
// you do get prop type completion on the react component
// (so VSCode knows which component you are using).
// File: ChessIcon/index.tsx

import * as React from 'react';
import { observer } from 'mobx-react';

class ChessIcon extends React.Component {

    render(){
        return <i/>
    }

};

export default observer(ChessIcon);
```

**Example 3**
```
// The following works perfectly (auto-import + prop completion on react component)
// File: ChessIcon/index.tsx

import * as React from 'react';
import { observer } from 'mobx-react';

class ChessIconClass extends React.Component<{
    doesAutoCompletionWork: boolean
}> {

    render(){
        return <i/>
    }

};

const ChessIcon = observer(ChessIconClass);
export default ChessIcon;

```

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/22447 to track this upstream
