### ISSUE TITLE
Vscode is missing file events

### ISSUE THREAD

**Issue by omaressameldin** [Microsoft/vscode#45280]
- VSCode Version:
1.21.0
- OS Version:
Ubuntu 17.10
Steps to Reproduce:

1. open a git project with vscode 
2. do any change 
3. the change is not seen in the git panel changes till you restart
4. if you press the + button even though it's showing you 0 changes the change will appear in the staged panel and unstaging it will make it appear in the unstaged panel
5. also undoing that change will not affect the panel and the file will still appear in the staged panel till you try to add it
Does this issue occur when all extensions are disabled?: Yes

**Comment by Oxicode** [comment]
+1

**Comment by joaomoreno** [comment]
Does the explorer reflect file system changes (eg if you delete a file, does it disappear from the explorer)? I'm interested in knowing whether file events work at all.

**Comment by omaressameldin** [comment]
it's like it's not auto refreshing anymore so if you try to do any action it updates but it's not doing it automatically

**Comment by omaressameldin** [comment]
@joaomoreno no if i delete a file from my file manager then go back to vscode the file is still there and when i click on it it says that it doesnt exist but it doesnt disappear from the explorer. also the inline git changes are still working in case that matters i mean if you edit a line in a file it's tagged with a blue line and M like it should be

**Comment by omaressameldin** [comment]
@joaomoreno so another update I cloned my repo into another directory and tried it and it works as expected. So not sure if it's a problem with just my directory (maybe permissions?) or just a problem with already existing repos

**Comment by bpasero** [comment]
@omaressameldin does it reproduce if you recreate the folder with same name from scratch?

**Comment by omaressameldin** [comment]
@bpasero no it only happens on that folder. I think it could be a permissions problem because whenever i create a new file in this project it requires root privileges to save, which shouldn't be the case, so maybe that's the problem

**Comment by bpasero** [comment]
@omaressameldin yeah that can very likely be the issue

**Comment by omaressameldin** [comment]
@bpasero alright then if that's the case I guess problem solved then :) 
@bpasero @joaomoreno  Thank you so much for the help!
