### ISSUE TITLE
Ctrl + click to follow link

### ISSUE THREAD

**Issue by yoffe** [Microsoft/vscode#45281]
Issue Type: <b>Bug</b>

Does Not work correctly for me

**I get this error:**

> Unable to open 'logo.jpg': File not found (file:///d:/ionic/DebtTracker/assets/imgs/logo.jpg).

![image](https://user-images.githubusercontent.com/2963687/37147194-c5c1e9b8-22ce-11e8-8351-865b60c7a42f.png)

**but the file is in the correct folder:**

![image](https://user-images.githubusercontent.com/2963687/37147273-07293708-22cf-11e8-9f97-890010deb2cd.png)

**and you can see that it is working: (-:**

![image](https://user-images.githubusercontent.com/2963687/37147177-b7f18fc8-22ce-11e8-9f8e-6da04452f871.png)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|15.94GB (8.04GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details>Extensions: none
Reproduces without extensions

**Comment by rebornix** [comment]
I'm not sure about the expected behavior of clicking urls like `/abc/def` as it's relative to the root folder of the server, which we don't know for sure.

**Comment by FabianLauer** [comment]
Seems to me like it URLs starting with `/` should be from the filesystem root and URLs starting with `./` should be local to the project.

Also, @yoffe are you sure the title of this issue is related to the bug you're actually reporting here?

**Comment by yoffe** [comment]
I think that it must be a relative link from the file in the project and not from the root of the server.
