### ISSUE TITLE
translations: Single quotes are replaced by double quotes in German translation

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4528]
Single quotes are replaced by double quotes in German translation:

```
"Cannot find runtime '{0}' on PATH.",
"Die Laufzeit \"{0}\" wurde in \"PATH\" nicht gefunden.",
"No se encuentra el runtime '{0}' en PATH.",
```

Is this intentional?

In addition the German translation seems to introduce quotes as for PATH above.
Is this intentional?

**Comment by johnliu2016** [comment]
Ported to loc for answer

**Comment by johnliu2016** [comment]
New DEU string: Die Laufzeit "{0}" wurde in PATH nicht gefunden. Linguistic confirmed DEU does not generally use single quotation marks
