### ISSUE TITLE
Expand Debug API with onDidReceiveDebugSessionEvent

### ISSUE THREAD

**Issue by blackmoron** [microsoft/vscode#45285]
vscode.debug exposes onDidReceiveDebugSessionCustomEvent which allows you to listen to custom DAP events only.

It would be nice to add new or modify the function above so it will be possible to listen to non custom events also (stopped etc.).

**Comment by weinand** [comment]
You can use the [DebugAdapterTracker](https://github.com/microsoft/vscode/blob/0bf0936b819aec3789ed9d95b6a1d34868f825db/src/vs/vscode.d.ts#L9085-L9110) API for this.
