### ISSUE TITLE
EACCESS error when running extension tests on Linux as of v1.21 release

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45287]
My tests have all started hanging on Linux since yesterday. I've tried forcing an old versions tag which had previously passed and today it fails on Linux. I believe this may be caused by the 1.21 upgrade.

The output is similar to mentioned in #38621 which was closed as a dupe of #38598 but that's supposed to be fixed.

Here's the broken output: https://travis-ci.org/Dart-Code/Dart-Code/jobs/345322915

Frustratingly it seems like Travis won't let me see the previous build for that branch after I told it to run again but it was green until I hit restart though (and had previously built about 13 days ago).

<details>
<summary>(output)</summary>
<code><pre>
### VS Code Extension Test Run ###
Current working directory: /home/travis/build/Dart-Code/Dart-Code
Downloading VS Code into "/home/travis/build/Dart-Code/Dart-Code/.vscode-test" from: https://vscode-update.azurewebsites.net/1.21.0/linux-x64/stable
Running extension tests: /home/travis/build/Dart-Code/Dart-Code/.vscode-test/VSCode-linux-x64/code /home/travis/build/Dart-Code/Dart-Code/out/test --extensionDevelopmentPath=/home/travis/build/Dart-Code/Dart-Code --extensionTestsPath=/home/travis/build/Dart-Code/Dart-Code/out/test
Xlib:  extension "RANDR" missing on display ":99.0".
Xlib:  extension "RANDR" missing on display ":99.0".
[main 11:32:06 AM] update#setState idle
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
%c[IPC Library: Search] %cspawn EACCES color: blue color: black
[ null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  [ null, { name: 'Error' } ] ]
</pre></code>
</details>

**Comment by bpasero** [comment]
@chrmarti @roblourens can we nail this down? seeing this more often lately...

**Comment by chrmarti** [comment]
This path might need to change to `node_modules.asar.unpacked`: https://github.com/Microsoft/vscode-extension-vscode/commit/029f7fe92b4d267d1b33778df2f6bbe4d2c207d4

**Comment by DanTup** [comment]
It may be worth setting up a CI that just has the template extension code running to help catch these earlier in future (and eliminate it being caused by any of the extensions own code, since some of us have custom scripts launching the tests to support multiple versions).

**Comment by DanTup** [comment]
Different error now :( Raised #45443
