### ISSUE TITLE
Show notification messages wider for larger resolutions

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45291]
Seems like the width of these should adapt a little to the size of the window. I have an Ultrawide screen and even running full screen many of these messages are unnecessarily truncated.

![wide](https://user-images.githubusercontent.com/1078012/37151700-90b85838-22ce-11e8-975c-0bf6cb4eebbd.png)

**Comment by bpasero** [comment]
This might deserve a setting (which is ugly) but just making them larger for everyone might result in the opposite bug (notifications are too long).

**Comment by DanTup** [comment]
Maybe it could scale between a minimum and maximum based on window size? It shouldn't get too long as it'd be awkward to read if it was like half my screen width, but certainly it could be bigger (maybe also could/should wrap a little before truncating?)
