### ISSUE TITLE
Emmet BEM filter doesn't work as expected

### ISSUE THREAD

**Issue by OlegIvaniv** [Microsoft/vscode#45297]
I'm trying to use bem filter with emmet. But I get modifiers instead of elements and other way around.

- VSCode Version:  1.21.0
- OS Version: OSX: High Sierra

Steps to Reproduce:

1.  Type `article.post>p.__title+.date.__date|bem` and press TAB to expand. From this I would expect following output:
```
<article class="post">
  <p class="post__title"></p>
  <date class="post__date"></date>
</article>
```

But instead I get:
```
<article class="post">
  <p class="post post--title"></p>
  <date class="post post--date"></date>
</article>
```

So it's clear that filter interprets `__` as a modifier and other way around. .

Does this issue occur when all extensions are disabled?: Yes

Thanks for checking this out :)

**Comment by ramya-rao-a** [comment]
@OlegIvaniv Can you share your the values you set for the `emmet.preferences` setting?

**Comment by OlegIvaniv** [comment]
@ramya-rao-a I don't haven any `emmet.preferences` setting.

**Comment by ramya-rao-a** [comment]
@OlegIvaniv You need to use `article.post>p.-title+date.-date|bem` to get 
```
<article class="post">
  <p class="post__title"></p>
  <date class="post__date"></date>
</article>
```

`bem.elementSeparator` and `bem.modifierSeparator` control what the class name should be in the expanded abbreviation. I believe you thought they referred to the operator/symbols used in the abbreviation

See https://docs.emmet.io/filters/bem/
