### ISSUE TITLE
Show apostrophe in zen mode with single tab

### ISSUE THREAD

**Issue by dracan** [Microsoft/vscode#45299]
Whilst it's nice having all the tabs except for the current one hidden when in zen-mode - it feels that the apostrophe to indicate if the file has been modified shouldn't be hidden. Or at least have an option to configure this. I keep on thinking that my files have been saved when I have outstanding modifications.

**Comment by bpasero** [comment]
@dracan it is till there, just all the way to the right

**Comment by dracan** [comment]
Oh yes - I hadn't spotted that. Seems an odd place for it to be fair.

**Comment by bpasero** [comment]
Ok, we have another issue reported to move it to the left so I will close this one.

**Comment by dracan** [comment]
@bpasero Do you have the issue number so I can subscribe?

**Comment by bpasero** [comment]
Yeah: https://github.com/Microsoft/vscode/issues/19531
