### ISSUE TITLE
PHP IntelliSense  

### ISSUE THREAD

**Issue by ctac22** [Microsoft/vscode#45293]
Issue Type: <b>Bug</b>

After restart the server, VS Code + **PHP IntelliSense**  fills up 2GB RAM and freezes the computer.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299
Server: Open Server 5.2.2 (PHP 7.1-x64 + Apache-PHP7-x64+Nginx-1.12)
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU        P6200  @ 2.13GHz (2 x 2128)|
|Memory (System)|3.68GB (0.95GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.2.2
php-intellisense|fel|2.2.9

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
@ctac22 when you are in this situation after restarting VS Code, what does `code --status` tell you about where the memory is consumed?

**Comment by ctac22** [comment]
TERMINAL:  code --status

> code: The term "code" is not recognized as the name of a cmdlet, function, script file, or
> Executable program. Check to see if you typed the name correctly, or if you included a path,
> Check that the path is correct and try again.
> Online: 1 Character: 1
> \+ code --status
> \+ ~~~~
>    CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
>    FullyQualifiedErrorId : CommandNotFoundException

DEBUG CONSOLE: code --status
> syntax error, unexpected '--' (T_DEC), expecting ';'

**Comment by kieferrm** [comment]
@ctac22 In Powershell pls use `code.cmd --status`. You can use tab completion once you have typed `code`. Thanks!

**Comment by ctac22** [comment]
@kieferrm The same error
Powershell: `code ` 

> code: The term "code" is not recognized as the name of a cmdlet, function, script file, or
> Executable program. Check to see if you typed the name correctly, or if you included a path,
> Check that the path is correct and try again.
> Online: 1 Character: 1
> \+ code
> \+ ~~~~
> CategoryInfo : ObjectNotFound: (code:String) [], CommandNotFoundException
> FullyQualifiedErrorId : CommandNotFoundException

Powershell: `code.cmd --status`
> code.cmd: The term "code.cmd" is not recognized as the name of a cmdlet, function, script file, or
> Executable program. Check to see if you typed the name correctly, or if you included a path,
> Check that the path is correct and try again.
> Online: 1 Character: 1
> \+ code.cmd --status
> \+ ~~~~
> CategoryInfo : ObjectNotFound: (code:String) [], CommandNotFoundException
> FullyQualifiedErrorId : CommandNotFoundException

**Comment by roblourens** [comment]
This is probably from the PHP Intellisense extension - there are some issues related to memory usage on that repo. Example https://github.com/felixfbecker/php-language-server/issues/479
