### ISSUE TITLE
How to get list of installed extensions?

### ISSUE THREAD

**Issue by greybax** [Microsoft/vscode#4529]
I've installed 4 extensions. How I can to see them?

**Comment by f111fei** [comment]
Open Command Palette (`Ctrl/Cmd + Shift + P`)

![1](https://cloud.githubusercontent.com/assets/7069719/13939898/d63ae492-f013-11e5-8ef6-81937b884535.png)

**Comment by greybax** [comment]
awesome! :tada: thanks @f111fei
