### ISSUE TITLE
add markdown outline

### ISSUE THREAD

**Issue by helmbold** [Microsoft/vscode#45304]
Navigation in larger Markdown documents would be easier with an outline containing the headings in the documents (like in Word). Please add a panel with such an outline to VS Code.

![outline](https://user-images.githubusercontent.com/5079980/37156899-a3365eba-22e7-11e8-8f13-a09f32e9c6bb.png)

**Comment by mjbvz** [comment]
Outline already exists with [go to symbol](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol)

Tree view outline tracked by  #5605

**Comment by helmbold** [comment]
Thanks. Just for the case someone comes to this issue looking for the outline feature: Here is an [outline plug-in](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) for the meantime.
