### ISSUE TITLE
Disappearing terminal session leaves drop down menu blank

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45300]
VS Code Insiders 1.22.0

- configure tmux following Joao's [blog post](https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41)
- open integrated terminal
- press "+" button

Observe: a second terminal appears for a brief moment but disappears quickly and leaves a blank entry in the drop down menu:

![2018-03-08_14-24-21](https://user-images.githubusercontent.com/1898161/37156009-1d147bf2-22e5-11e8-90d5-4f351efba51e.gif)

So the disappearing tmux session is correct and expected, but the blank drop down is not.

**Comment by Tyriar** [comment]
Might be related to https://github.com/Microsoft/vscode/issues/43475

**Comment by Tyriar** [comment]
I'll assume #43475 caused this
