### ISSUE TITLE
Code Helper high CPU usage

### ISSUE THREAD

**Issue by chrstntdd** [Microsoft/vscode#45301]
Issue Type: <b>Performance Issue</b>

Just regular usage. This was happening even before my recent upgrade to MacOS High Sierra. I thought upgrading would solve the issue. None of the built in source control features or plugins are working either.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (3.87GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   27	    98	 27949	code main
    7	    82	 28009	   gpu-process
   11	   262	 28047	   window (SeoBreadcrumbs.scss — hui-react)
   99	   131	 28051	     extensionHost
    0	    82	 28055	       electron_node server.js 
    0	    49	 28056	       electron_node server.js 
    0	   131	 28057	       electron_node electronForkStart.js tsserver.js 
    0	    49	 28084	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	   147	 28058	       electron_node eslintServer.js 
    0	    49	 28059	       electron_node cssServerMain.js 
    0	    66	 28066	       electron_node server.js 
    0	    16	 29889	       electron_node index.js 
    0	    49	 28052	     watcherService
    0	    49	 28063	     searchService
    2	    82	 28048	   shared-process
   71	    82	 30343	   shared-process
    0	     0	 30344	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (SeoBreadcrumbs.scss — hui-react)
|    Folder (hui-react): 1857 files
|      File types: html(584) jsx(251) scss(237) js(221) svg(208) jpg(134)
|                  png(81) snap(58) md(45) gif(10)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.17
vscode-markdownlint|Dav|0.13.0
vscode-docker|Pet|0.0.25
snapshot-tools|asv|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
gitlens|eam|8.1.0
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.2.2
svg|joc|0.0.9
theme-monokai-pro-vscode|mon|1.1.5
vscode-scss|mrm|0.6.2
color-highlight|nau|2.3.0
vscode-icons|rob|7.20.0
elm|sbr|0.16.0
code-spell-checker|str|1.6.5
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by chrstntdd** [comment]
@bpasero I looked into the performance processes, but came up empty handed. It seems that the issue has resolved itself though. Thank you for your help!
