### ISSUE TITLE
regex unresponsive to the point of 'close window' constantly appears

### ISSUE THREAD

**Issue by neilw73** [Microsoft/vscode#45309]
- VSCode Version: 1.20.1
- OS Version: 8.1

Regex on a large file takes forever, given it highlights in realtime as you type within the search text box, it freezes after every single character you type. It also takes a very long time to replace the same regex on a large file compared to Notepad++. 

Perhaps add a tickbox on search facility to toggle realtime showing to allow regex to be finalised (or even non-regex as this is slow on a large file), then fix your speed problem :)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Can you provide the regex you are using and a sample file that reproduces this issue?

**Comment by GeoSnipes** [comment]
For me, the file size is roughly a 100MB, but it only happens when I'm using the lookbehind implementation.

**Comment by rebornix** [comment]
Thanks! It's a duplicate of https://github.com/Microsoft/vscode/issues/30874

**Comment by neilw73** [comment]
Well, not really. That bug is about specific regex expressions. Mine is about performance on large files.
