### ISSUE TITLE
Cannot read property 'toCommandArgument' of undefined

### ISSUE THREAD

**Issue by wilfredinni** [Microsoft/vscode#45306]
Issue Type: <b>Bug</b>

The same bug of the last month when using the keyboard shortcut to excecute a script in the terminal.
![image](https://user-images.githubusercontent.com/23016174/37157418-94d45a0e-22c7-11e8-885f-4d732a3bb262.png)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2395)|
|Memory (System)|3.88GB (0.86GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Dropbox\Dropbox\projects\python\retwiBot|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.1.9
project-manager|ale|0.24.1
vscode-markdownlint|Dav|0.13.0
githistory|don|0.4.0
code-runner|for|0.9.0
output-colorizer|IBM|0.1.2
vscode-todo-parser|min|1.9.1
python|ms-|2018.1.0
material-icon-theme|PKi|3.2.3
code-settings-sync|Sha|2.9.0
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|1.1.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by tweakimp** [comment]
Issue Type: <b>Bug</b>

Same for me.

VS Code version: Code - Insiders 1.22.0-insider (24d376c2735bb1eff8993aae6b3ba5eec967b6db, 2018-03-08T05:17:47.706Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|15.93GB (12.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.27.1
python|ms-|2018.1.0
color-highlight|nau|2.3.0
vscode-code-outline|pat|0.0.13
vscode-sort-json|ric|1.11.0
vscode-icons|rob|7.20.0

(3 theme extensions excluded)

</details>
Reproduces without extensions (Except VS Python, which I need to run the file)

**Comment by wilfredinni** [comment]
it is the same as the last month, after a few days, not even the insiders build was working

**Comment by kieferrm** [comment]
Pls provide steps to reproduce. Thanks!
