### ISSUE TITLE
Comment toggle (CTRL+/) hotkey is active when terminal is focused

### ISSUE THREAD

**Issue by onionhammer** [Microsoft/vscode#45302]
- VSCode Version: 1.21.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new tab, change language mode to Markdown
2. Press CTRL+` to open a terminal (switches focus to terminal)
3. Press CTRL+/

A line of markdown in the non-focused tab is commented out

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
Some of the commands make it back to the workbench while others are consumed by the terminal. I agree that it's sometimes hard to distinguish.

**Comment by Tyriar** [comment]
Leaving it up to @alexandrudima whether we want to add when editorFocus to the comment command.

**Comment by alexandrudima** [comment]
The `editor.action.commentLine` action is registered with a restrictive enough `when` clause, but it appears in the menu and the menu decides to trigger it:
```
{ "key": "ctrl+oem_2",            "command": "editor.action.commentLine",
                                     "when": "editorTextFocus && !editorReadonly" },
```

Duplicate of #35225
