### ISSUE TITLE
VSCode calling node components in a non Node App

### ISSUE THREAD

**Issue by netofd84** [Microsoft/vscode#45313]
- VSCode Version: 1.21.0
- OS Version: Windows10

Steps to Reproduce:

1. By using SPTools in order to work with a SharePoint Folder I have noticed, by using fiddler, that vscode is trying to open bower_compoents, node_modules, bower.json, package.json, etc. When this application is only using simple javascript. The real problem is that it keeps going and never stops from making these calls to these files and folders. We got to the point that one of the server farms was so busy because of these multiple calls.

2. I have used the same vscode to build other applications outside of SharePoint but apparently the configuration for node and bower are still there, is there a way to disable this configuration and just work with plain javascript without calling these other elements?

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please check when these requests are triggered. Try closing all editors and then reloading the workspace. Are the requests triggered then? When you open the first file? Some other time?

Trying to narrow down if this is the npm built-in extension or `workspaceStats.ts`.

**Comment by netofd84** [comment]
These requests are being triggered only when I open a JS file, I don't even have ts files nor json files, and it happens on any folder, not only sharepoint folders, any remote folder that have js files within. It keeps looking for tsconfig.json, node_modules/, bower_components/.

As soon as open a js file and look at the code that's when it happens, if I look at the code of some HTML or css files everything is good, I feel like it's trying to run a compiler when I don't need it and it keeps trying and trying, it never stops.

![image](https://user-images.githubusercontent.com/3232676/37476176-e07e422a-284a-11e8-9c0f-6b9b1d7d0e54.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22846
