### ISSUE TITLE
Debugging a typescript extension is not applying source maps correctly - some js files in call stack

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45315]
Today (possibly since 1.21 upgrade) I'm seeing weirdness when debugging my extension (which is written in TS). I'm at a breakpoint here and the call stack has a bunch of js files in there. It even lists both `utils.ts` and `utils.js` - both of the highlighted functions are in the same file.

This makes navigating the call stack complicated, as it takes me to the js file sometimes.

![sourcemaps](https://user-images.githubusercontent.com/1078012/37162243-ac16fc2e-22ec-11e8-905a-e4d4971e9824.png)

Code I'm debugging is this:

https://github.com/Dart-Code/Dart-Code/commit/27e0e67d467da7898d5effa8dbc92601d0ae5a04

If you need to repro, I think you should be able to open that repo, breakpoint where I have, press F5 and in the extension dev host execute the `Flutter: New Project` command - this will activate the extension and should fall into this code (assuming you don't have Flutter installed an on your `PATH`!).

**Comment by DanTup** [comment]
I blew away my `node_modules` and `out` folders, did an `npm install` and then starter over, but still seeing the same issue; so I don't think it's a result of anything stale hanging around on disk.

**Comment by weinand** [comment]
Are you using a different version of TypeScript? This problem looks like a broken source map to me.

**Comment by DanTup** [comment]
@weinand I have 2.7.2 in my package.json (I did have before the update - see [here](https://github.com/Dart-Code/Dart-Code/blob/master/package.json)). Is there anything else that would affect this?

**Comment by weinand** [comment]
Since the concept of source maps does not leak outside of the DA, this problem could only originate from node-debug2.
@roblourens do you know any change on your side that could have affect this?

**Comment by roblourens** [comment]
I'll try it, but when using async/await with TS you can get .js entries where it goes through the unsourcemapped stuff that TS adds.

**Comment by DanTup** [comment]
I hadn't seen this before, but I have started using async/await more recently. If you think it's likely always been this way, let me know and I'll see if I can do the same in 1.20.

**Comment by DanTup** [comment]
Aha, didn't know about SmartStep, I'll turn that on! 👍
