### ISSUE TITLE
Request: Add filter for Import path quick suggestions 

### ISSUE THREAD

**Issue by Undistraction** [Microsoft/vscode#45319]
The Import path quick suggestions feature is really useful, however it often suggests multiple versions of the same import.

Example 1.

If I'm working on a lib that contains a `src` dir and builds to a `lib` dir, I get suggestions for the same import for e.g.

- src/example
- lib/example

Example 2.

If I'm using a package that contains a `lib` dir and `src` dir I get suggestions fro the same import for e.g.

- node_modules/example/src/example
- node_modules/example/lib/example

Given that some projects or modules can have other dirs (suchs as a `dist` containing untranspiled es6 files), it would be great to have two config settings. 

- One that allows a glob / regex to be supplied to limit where suggestions are pulled from locally (which could default to `src`).
- One that allows a glob / regex to be supplied to limit where suggestions are pulled from 3rd party libs (which could default to `lib`). 

Apart from being quite annoying this can introduce nasty bugs quite easily - for example if I have an old version of a transpiled file in `lib` and accidentally select that suggestion instead of the one from `src` I am compiling a stale file into the project without realising it.

**Comment by mjbvz** [comment]
Have you configured a `jsconfig.json` or `tsconfig.json`? You can use the [`include` or `exclude`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) to make sure that only non-compiled source files are part of the project

**Comment by Undistraction** [comment]
Thanks and sorry I missed your reply. You were correct. I didn't have a `jsconfig.json` configured.
