### ISSUE TITLE
Reindent selected lines [Keyboard Shortcut]

### ISSUE THREAD

**Issue by JE-DW** [Microsoft/vscode#45318]
- VSCode Version: 1.21.0

Hi,

I wanted to add a shortcut to Reindent Lines, but only those I highlighted. In the Shortcuts tool, I only see the command "Reindent Lines (editor.action.reindentlines)", but I'm searching for something like "Reindent Selected Lines (editor.action.reindentselectedlines)".
So I wanted to know if was possible to add this new shortcut command. I used it a lot on others IDEs as reindenting all file wrongly reindent some portions of code (specific coding style).

![image](https://user-images.githubusercontent.com/24585950/37163337-ce8570d2-22f7-11e8-9aee-db240e1dbebf.png)

EDIT:
I see that Formatting Selection (cmd+k, cmd+f) does exactly what I want, but it's not very explicit and I don't know if it's the primary purpose of this command...

Thanks !

**Comment by rebornix** [comment]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/876920/45188868-1dc9de80-b1eb-11e8-8ed1-c020914b57ac.png">

You can see this command in latest version ;)
