### ISSUE TITLE
PROBLEMS panel symlink error

### ISSUE THREAD

**Issue by bukshee** [Microsoft/vscode#45310]
- VSCode Version: 1.21.0
- OS Version: Linux, Debian 

Steps to Reproduce:

1. I'm doing Go development with the latest version of VSCode. Upon saving the file the PROBLEMS panel pops up with an error. I double click on the file and got:
> Unable to open 'main.go': File not found
> (file:///home/golang/golib/src/github.com/golib/src/github.com/bukshee/json/main.go).

Cause of error most probably is that symlinks not resolved properly. Linux prompt:
```sh
json » pwd
/home/golang/work/json
json » file main.go 
main.go: C source, ASCII text
json » pwd -P
/home/golang/golib/src/github.com/bukshee/json
json » ls -ld ~/work
lrwxrwxrwx 1 golang golang 28 Feb  3 15:26 /home/golang/work -> golib/src/github.com/bukshee

```
![screenshot_2018-03-08_16-53-11](https://user-images.githubusercontent.com/23742579/37160768-4219c978-22f1-11e8-8a7e-0ff24d646bb5.png)

Does this issue occur when all extensions are disabled?: No

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#1568
