### ISSUE TITLE
Hit breakpoint does not turn yellow

### ISSUE THREAD

**Issue by achawla5000** [Microsoft/vscode#45311]
Issue Type: <b>Bug</b>

Starting with the February 2018 release, when a breakpoint is hit, the red dot indicating the breakpoint does not show the yellow color inside the red dot; as a result, it is now very difficult to see which breakpoint is being hit.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.38GB (7.74GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe C:\Git\Issunc\Front End.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
file-templates|brp|1.2.0
vscode-great-icons|emm|2.1.27
json-tools|eri|1.0.2
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|2.14.0
mssql|ms-|1.3.0
debugger-for-chrome|msj|4.1.0
gitflow|vec|1.1.2

(2 theme extensions excluded)

</details>
Reproduces without extensions
<

**Comment by achawla5000** [comment]
![image](https://user-images.githubusercontent.com/11709568/37161822-b4d956f2-22c1-11e8-8221-b2fa917d631f.png)

**Comment by kieferrm** [comment]
We lost the gutter icon that indicates where the debugger stopped.

**Comment by isidorn** [comment]
This is a clear regression and candidate will fix for the recovery build.
However there is no data loss and the user can continue working -> removing important.

**Comment by isidorn** [comment]
@weinand please verify once we have the recovery build. Thanks.
The issue was that I was renaming some css and did not adopt it in all the places.

**Comment by weinand** [comment]
Verified fix for build ec656847ad69e2f604379f6e200405c4734e2fe4

**Comment by roblourens** [comment]
@isidorn Previously didn't it show the step indicator and the breakpoint decoration? Now it only shows the step decoration when execution is on a line with a breakpoint.

**Comment by weinand** [comment]
@roblourens that was a regression that is already fixed in the recovery build.
