### ISSUE TITLE
Copying a file from Windows explorer into same directory in VS Code removes all code

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4531]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project folder
2. Right click a file -> 'Reveal in Explorer'
3. Drag the file from Windows Explorer to the same directory it is already in
4. Click 'Replace'
5. Refresh the folder in VS Code
6. Go back to the file

Actual:
The file is now empty

Expected:
It would not overwrite the file with no data

**Comment by bpasero** [comment]
Can reproduce and will investigate if this is a regression.

**Comment by bpasero** [comment]
Not a regression, this happens because in fileService we first delete the file and then try to copy it, but delete removes the contents. Need to check in the copy-function that the path is really the same.
