### ISSUE TITLE
Centered mode doesn't work when views are split in horizontal mode

### ISSUE THREAD

**Issue by michaeljcalkins** [Microsoft/vscode#45323]
- VSCode Version: 1.21
- OS Version: Mac 10.12.16

Steps to Reproduce:

1. Split editor mode should be in vertical mode
2. Turn on centered layout with one tab, you should see it is centered
3. Change split editor mode to horizontal mode
4. The centered layout will no longer work until you switch back to vertical mode

Does this issue occur when all extensions are disabled?: Yes

**Comment by AskYous** [comment]
Thanks for figuring this out. I spent a while trying to figure out what the problem was. Thank to you, I changed splitting to vertical mode and now centered layout works.

I can affirm that this big is happening to me too. I'm on a mac as well.

**Comment by isidorn** [comment]
@SrTobi I would expect centered mode to work if I have horizontal layout and only one editor. I tried removing the check to simply also enable it for horizontal layout but somehow the layout gets broken in that case.

I plan to fix this in the following week but just to let you know that a PR is more than welcome :)

**Comment by SrTobi** [comment]
@isidorn I just let you know that money is more than welcome :smile: Just kidding... I run on fun xD you shall have your PR :) it has the number #45671.

The problem was, that the available size was calculated by using `silosSize[Position.ONE]` which holds the height and not the width of the editor when in horizontal mode.

As bonus I fixed two typos (one of whom I made myself :smile:)

**Comment by isidorn** [comment]
@SrTobi thanks a lot for your PR, I just merged it in 🍻 
I tried it out and it works nicely, also thanks for fixing typos.

For money feel free to apply for our internshipts if you are a student or to our open positions :)

**Comment by SrTobi** [comment]
@isidorn :smile: I'll finish university in 4 month... so... I might very well do that xD

**Comment by PoisonousJohn** [comment]
@isidorn, which version the fix should be shipped with?
