### ISSUE TITLE
Typo in settings "termianl"

### ISSUE THREAD

**Issue by KurtCattiSchmidt** [Microsoft/vscode#45327]
### Issue Type
Bug

### Description

Open settings and search for termianl. It should be "Terminal".

  // The font weight to use within the termianl for non-bold text.
  "terminal.integrated.fontWeight": "normal",

  // The font weight to use within the termianl for bold text.
  "terminal.integrated.fontWeightBold": "bold",

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.17115

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|31.79GB (22.26GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
githistory|don|0.4.0
gitlens|eam|8.1.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.1.0
vscode-icons|rob|7.20.0
ActiveFileInStatusBar|Ros|1.0.3

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
Already fixed in master & 1.21 😃
