### ISSUE TITLE
When launching extension tests, if another Code instance has a folder open used for tests, it silently does not open

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45328]
This one is a bit of a weird edge case. I was working on my tests and noticed that all of a sudden they weren't working right, and Code wasn't opening the folder it was told.

My launch config looks like this:

```js
{
	"name": "Launch Tests (General)",
	"type": "extensionHost",
	"request": "launch",
	"runtimeExecutable": "${execPath}",
	"args": [
		"${workspaceRoot}/test/test_projects/hello_world",
		"--extensionDevelopmentPath=${workspaceRoot}",
		"--extensionTestsPath=${workspaceRoot}/out/test/general"
	],
	"env": {
		"DART_CODE_DISABLE_ANALYTICS": "true"
	},
	"stopOnEntry": false,
	"sourceMaps": true,
	"outFiles": [
		"${workspaceRoot}/out/test/**/*.js"
	],
	"preLaunchTask": "npm: watch"
},
```

The problem turned out to be that I'd opened `"${workspaceRoot}/test/test_projects/hello_world"` in another Code window so I could modify the test project while working on the tests. With this open, when I run the tests, it spawns a Code window but that window silently does not open anything.

It would be nice if this could be handled in a better way than a silent failure, or if I could pass a flag in my `launch.json` to force Code to open a folder, even if it's already open in another window somewhere (after all, the folder is normally open anyway, it's just a sub-folder of my main Code window rather than having its own instance).

**Comment by isidorn** [comment]
No plan to fix this, also might be fixed in latest
