### ISSUE TITLE
Find in Folder with shortcut

### ISSUE THREAD

**Issue by GammaGames** [Microsoft/vscode#45329]
Just a suggestion.  
I think, with the option of the horizontal search panel, it would make sense to introduce a default shortcut to search in a folder if the file explorer is focused. Since the search and file explorer don't both live in the sidebar anymore it wouldn't be as confusing to the user, as it won't be replacing the file explorer and instead just opening a new tab in the panels.

(also komodo has this and it's really handy when you don't want to reach for your mouse)

I already added it to my keybindings

```javascript
    {
        "key": "ctrl+f",
        "command": "filesExplorer.findInFolder",
        "when": "filesExplorerFocus"
    }
```

**Comment by roblourens** [comment]
This is possible now 🎉

**Comment by GammaGames** [comment]
Is it a setting somewhere?

**Comment by roblourens** [comment]
You can add a keybinding like described in the original issue and it should trigger Find in Folder with the selected folder filled in.
