### ISSUE TITLE
Installing Extensions

### ISSUE THREAD

**Issue by Dovernh** [Microsoft/vscode#45335]
Issue Type: <b>Bug</b>

Any extensions needing updates or new extensions installation fails to install, offers download manually. Manual install fails from Code. Manual install outside code fails

SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
 
 	SignatureState     : Unsigned
 	Supported Products : 
 		Microsoft.VisualStudio.Code
 			Version : 
 
 	References         : 
 Signature Details...
 	Extension is not signed.
 
 Searching for applicable products...
 Found installed product - Global Location
 Found installed product - ssms
 Found installed product - Visual Studio Professional 2017
 VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed

VS Code version: Code - Insiders 1.22.0-insider (24d376c2735bb1eff8993aae6b3ba5eec967b6db, 2018-03-08T05:17:47.706Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 v3 @ 2.80GHz (4 x 2794)|
|Memory (System)|15.92GB (11.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by kieferrm** [comment]
Fix is coming in the next couple of hours.
