### ISSUE TITLE
Extension background border-radius is being toggled

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45338]
Issue Type: <b>Bug</b>

Actually same for terminal. 

![corner](https://user-images.githubusercontent.com/4033249/37174008-24cc2248-22ca-11e8-94af-e5060f945f79.gif)

VS Code version: Code - Insiders 1.22.0-insider (24d376c2735bb1eff8993aae6b3ba5eec967b6db, 2018-03-08T06:09:01.799Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.75GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_2626177|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.5.0
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.0
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
theme-monokai-pro-vscode|mon|1.1.5
vscode-slm|mrm|1.1.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
polacode|pnp|0.2.2
vim|vsc|0.11.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
Ok, it is a duplicate even though the bot can not find it
