### ISSUE TITLE
[css] Completions with the same input do not resolve

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45337]
Try completing here (`|` is cursor pos). Nothing happens after tab:

```css
.hello {
  font-feature-settings|: 'Courier New', Courier, monospace;
}
```

![completon](https://user-images.githubusercontent.com/4033249/37172962-392c8a46-22c7-11e8-9b8f-5da3b497bff0.gif)

I confirmed it's happening in 1.20 too, so it's not a regression.

VS Code version: Code - Insiders 1.22.0-insider (24d376c2735bb1eff8993aae6b3ba5eec967b6db, 2018-03-08T06:09:01.799Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.53GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_2626177|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.5.0
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.0
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
theme-monokai-pro-vscode|mon|1.1.5
vscode-slm|mrm|1.1.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
polacode|pnp|0.2.2

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by jrieken** [comment]
wow...

**Comment by jrieken** [comment]
This is actually the CSS completion which is telling suggest to retriever completion computations

<img width="1217" alt="screen shot 2018-03-09 at 08 39 46" src="https://user-images.githubusercontent.com/1794099/37196037-7ccb6af2-2375-11e8-82c3-245168752720.png">

**Comment by octref** [comment]
@jrieken Curious if there has been any request for adding a property to `CompletionItem` so choosing it re-triggers suggestion (or are there any other use for the `command` property than `editor.action.triggerSuggest`)?

I feel for incomplete `CompletionList`, such property would be needed (choosing certain item re-triggers suggest so the LS get a chance to update the `CompletionList`). I did not find related discussion in LSP repo.

**Comment by jrieken** [comment]
The ideas was that the `command` can be used for more scenarios, like suggesting a type and then download it's `d.ts`-file etc. Using it to retrigger is a special usage of it.

**Comment by octref** [comment]
Just saying there is a slight flickering when having the retrigger suggest. I don't like it but I can live ok with it.
