### ISSUE TITLE
Extension host crashes while opening large binary files with extension vscode-hexdump

### ISSUE THREAD

**Issue by Golrath** [Microsoft/vscode#45339]
Issue Type: <b>Bug</b>

* extension "vscode-hexdump" is installed
* Settings of displaysize and warnings are changed as follows

    "hexdump.sizeDisplay": 31457280,
    "hexdump.sizeWarning": 31457280

* open a folder with large binary files like raw picture (>25MB filesize)
* call command "Show hexdump" from the context menu of the file in the browser

result: Visual studio stops loading the file with the message "Extension host terminated unexpectedly."

awaited behavior: The file is loaded and displayed as hexdump

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|Memory (System)|31.88GB (24.09GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
githistory|don|0.4.0
python|ms-|2018.2.0
vscode-ai|ms-|0.1.7
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
team|ms-|1.122.0
vscode-docker|Pet|0.0.25
vscode-icons|rob|7.20.0
vscode-hexdump|sle|1.6.0

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
Pls file this against the vscode-hexdump extension. I'd suspect that the extension host crashes with out-of-memory due to exorbitant memory consumption in the extension. That's why we have an extension host, i.e. extensions can not bring down the core of VS Code if they misbehave. Thanks a ton!
