### ISSUE TITLE
can't navigate javascript with manual namespaces

### ISSUE THREAD

**Issue by chadbr** [Microsoft/vscode#4533]
I have large legacy codebase with "manual" style namespacing like this:

    //namespaces
    var my = my || {};
    my.app = my.app || {};

and "classes" declared like this:

my.app.Application` = (function () {
    var Application = function () {
...
    };
    return Application;
})();

I've tried several combinations of jsconfig.json parameters and none allow me to navigate this style of code. Should this work?

- VSCode Version: 0.10.11, 0.10.12-insider
- OS Version: OSX 10.11.3

Steps to Reproduce:

1. Open attached project or github repo https://github.com/chadbr/vscodeTestJS

[vscodeTestJS.zip](https://github.com/Microsoft/vscode/files/183295/vscodeTestJS.zip)

2. Open folder in vscode
3. open src/app/application.js 
4. try to go to declaration of my.app.SomeView() -- nothing happens.

**Comment by chadbr** [comment]
oh - and FWIW, WebStorm allows me to navigate these files...

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#7632
