### ISSUE TITLE
Split terminal should remain same width

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45331]
Issue Type: <b>Bug</b>

Currently, toggle sidebar or using a tool like https://www.spectacleapp.com/ to resize VS Code will both make terminal have unequal width.

VS Code version: Code - Insiders 1.21.0-insider (a903bd38fbe9006c076d218ff69fe1ee0160f815, 2018-03-06T10:59:55.398Z)
OS version: Darwin x64 17.3.0

![terminal](https://user-images.githubusercontent.com/4033249/37169234-32dec52e-22bc-11e8-813b-b9d8903a7f8a.gif)

**Comment by theigor** [comment]
Thumbs up for this. Terminals should have same relative width when you resize the window. If I have 3 terminals and resize the window, they should remain 33% width each. It would be acceptable (I think) if manual terminal width change should cancel this behavior until you get back down to 1 terminal. That is, if I have 2 terminals and manually resize them so one is 25% of the width, I don't expect vs code to figure out what that should mean if I resize the window. But if I close one, and then split again, it should spit to 50/50 and keep the relative % width if I resize.

**Comment by crhistianramirez** [comment]
I'm probably being picky but adding on to @theigor's post I think the manual resize scenario should be considered.

**Comment by theigor** [comment]
I'll add another tidbit - this is especially annoying when I drag vscode from one monitor to another. Not only does it bungle all my terminals, but it seems that some output is word wrapped but some isn't so the whole thing becomes a mess and even when I resize it back, not everything that was word wrapped restores back. I end up with things like this:

![image](https://user-images.githubusercontent.com/6673707/37777259-782063a2-2dbd-11e8-820a-1cfdec31b482.png)

**Comment by Tyriar** [comment]
@theigor if you're on mac/Linux this issue should fix the problem https://github.com/Microsoft/vscode/issues/23688, planning on working on that soon. It should work on Windows eventually but needs some changes inside Windows.

**Comment by theigor** [comment]
Sounds good. I'm seeing this on Windows right now.
