### ISSUE TITLE
Issue reporter should try to make people check "reproducible when extensions are disabled" 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45332]
Issue Type: <b>Feature Request</b>

As the title suggests. Currently there is nothing that urshes you to try checking disabling all extensions before submitting an issue. I suggest showing a warning sign near "Preview on GitHub" when this is not checked.

VS Code version: Code - Insiders 1.21.0-insider (a903bd38fbe9006c076d218ff69fe1ee0160f815, 2018-03-06T10:59:55.398Z)
OS version: Darwin x64 17.3.0

**Comment by RMacfarlane** [comment]
Closing this out as that checkbox no longer exists
