### ISSUE TITLE
Add search panel "search entry" history

### ISSUE THREAD

**Issue by sgarcia-dev** [Microsoft/vscode#45330]
Issue Type: <b>Feature Request</b>

Hi VS Code team,

VS Code is an amazingly powerful text editor, but if there is one last tiny thing missing to make this fully take over an IDE for me, is full search panel history. By this, I mean that while each field supports individual history, it'd be amazing if it could save the history for all these search fields as an individual search log entry, this way I could quickly go back and see previous search attempts without having to guess what field history log went with who. 

Thanks!

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 16.7.0

**Comment by Eccenux** [comment]
Would be even better if search result would also be saved. So that you could switch between to search tabs/items quickly. This is something Netbeans has and it's very useful for refactoring and rewritting.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/42350 and https://github.com/Microsoft/vscode/issues/17920
