### ISSUE TITLE
Macos High Sierra VSC syspolicyd high cpu

### ISSUE THREAD

**Issue by bugmenotits** [Microsoft/vscode#45336]
- VSCode Version: 1.21
- OS Version: MacOS 10.13.3

Steps to Reproduce:

1. Lauch Code and the syspolicyd will start
2.

Does this issue occur when all extensions are disabled?: Yes

Everytime I start VS Code the syspolicyd will maintain cpu usage of 55-60.

**Comment by kieferrm** [comment]
This is the only report have about this right now. Does the CPU usage calm down after a while? If so, how long? Thanks!

**Comment by bugmenotits** [comment]
No, the CPU is throlling away, and I was coding for a least 7 hours yesterday. And the syspolicyd was used 50-60% of CPU during that time.

**Comment by kieferrm** [comment]
Just to make sure we cover all the ground:
- When you quit Code syspolicyd CPU goes down?
- When you restart Code syspolicyd comes up?
- Same happens after your reboot your mac?
- Any entries in your system log? (When you use the Console app.)

Thanks a ton!

**Comment by bugmenotits** [comment]
When you quit Code syspolicyd CPU goes down?
Yes
When you restart Code syspolicyd comes up?
yes
Same happens after your reboot your mac?
Yes

This what I found in Console and used the term Visual Studio Code 

10:18:31.130300 +0100	Electron	Retrieve User by ID
10:18:31.131367 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:18:31.131565 +0100	Electron	Loading Preferences From User CFPrefsD For Search List
10:18:31.503148 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:18:31.503224 +0100	Electron	Loading Preferences From User CFPrefsD For Search List
10:18:31.584251 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:18:31.584322 +0100	Electron	Loading Preferences From User CFPrefsD For Search List
10:18:31.594500 +0100	Electron	Membership API: translate identifier
10:18:31.610357 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:18:31.616716 +0100	Code Helper	Retrieve User by ID
10:18:31.617865 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:31.618141 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:31.634631 +0100	Code Helper	Loading Preferences From User CFPrefsD
10:18:31.639157 +0100	Electron	Loading Preferences From User CFPrefsD
10:18:31.653933 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:31.654009 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:31.675483 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:31.675604 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:31.707295 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:31.707492 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:31.708768 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:31.708834 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:31.777160 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:31.777261 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:31.997026 +0100	Electron	Loading Preferences From User CFPrefsD
10:18:32.087009 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:32.087085 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:32.105307 +0100	Code Helper	Retrieve User by ID
10:18:32.106835 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:32.107393 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:32.225813 +0100	Code Helper	Retrieve User by ID
10:18:32.226925 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:32.227322 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:32.306648 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:18:32.306724 +0100	Electron	Loading Preferences From User CFPrefsD For Search List
10:18:32.318986 +0100	Electron	VBWAIT: announce remote view to VBA
10:18:32.327560 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:18:32.327632 +0100	Electron	Loading Preferences From User CFPrefsD For Search List
10:18:32.346745 +0100	Electron	Loading Preferences From User CFPrefsD
10:18:32.434110 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:32.433483 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:32.434243 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:32.433562 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:32.474816 +0100	Code Helper	Loading Preferences From User CFPrefsD
10:18:32.474439 +0100	Code Helper	Loading Preferences From User CFPrefsD
10:18:32.727253 +0100	Electron	Retrieve User by ID
10:18:32.728560 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:18:32.728922 +0100	Electron	Loading Preferences From User CFPrefsD For Search List
10:18:33.487218 +0100	Code Helper	Membership API: translate identifier
10:18:33.918832 +0100	Code Helper	Loading Preferences From User CFPrefsD
10:18:34.507750 +0100	Code Helper	Retrieve User by ID
10:18:34.509132 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:34.509489 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:34.936809 +0100	Code Helper	Retrieve User by ID
10:18:34.939792 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:34.943874 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:35.111194 +0100	Code Helper	Retrieve User by ID
10:18:35.112489 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:35.112823 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:36.402418 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:18:36.402494 +0100	Electron	Loading Preferences From User CFPrefsD For Search List
10:18:36.566763 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.759629 +0100	Electron	SecKeychainAddCallback
10:18:36.767465 +0100	Electron	Loading Preferences From System CFPrefsD
10:18:36.890070 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.893499 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.897496 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.902818 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.904857 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.906815 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.909504 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.912075 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.917206 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.919306 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.921171 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.923272 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.926596 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.931059 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.932963 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.935338 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.936683 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.940222 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.942451 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.945171 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.948601 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.950489 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.952072 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.954269 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.956107 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.960026 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.961793 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.964790 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.966859 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.968685 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.971312 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.975440 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.977942 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.981451 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.985947 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.987874 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.991220 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.996609 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:36.999442 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.001315 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.003103 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.005325 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.007178 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.010243 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.012245 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.014867 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.017787 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.019929 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.022799 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.025593 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.029348 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.032941 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.034954 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.036521 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.044076 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.045813 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.049922 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.055362 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.057993 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.060795 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.064908 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.070655 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.072539 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.077187 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.080626 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.082713 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.085677 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.087767 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.089482 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.091542 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.093933 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.097105 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.100840 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.102896 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.105541 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.108088 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.110744 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.114062 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.116874 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.119631 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.122136 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.124623 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.167703 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.170109 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.176224 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.178240 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.180439 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.182402 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.184332 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.186540 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.188302 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.189956 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.191575 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.193942 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.208772 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.210883 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.213158 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.215144 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.217118 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.218947 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.220935 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.222745 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.224594 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.226271 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.228347 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.229983 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.231747 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.233750 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.235830 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.237724 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.239698 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.241245 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.243118 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.244679 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.246276 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.248518 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.250438 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.253039 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.254603 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.256896 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.258823 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.260544 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.262094 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.263876 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.265574 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.267112 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.269011 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.270999 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.273012 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.274778 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.285954 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.287898 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.289699 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.292678 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.295044 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.297029 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.298926 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.300737 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.302587 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.304392 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.306440 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.307853 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.309237 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.310738 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.312090 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.313543 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.315200 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.316680 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.318143 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.319553 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.321061 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.322455 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.324098 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.325464 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.327102 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.328528 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.330445 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.332029 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.333657 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.335308 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.336912 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.339077 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.341192 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.344546 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.347342 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.351166 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.353700 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.356025 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.358362 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.360892 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.362454 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.364901 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.374926 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:37.588681 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:38.279599 +0100	Code Helper	Retrieve User by ID
10:18:38.280885 +0100	Code Helper	Loading Preferences From System CFPrefsD For Search List
10:18:38.281175 +0100	Code Helper	Loading Preferences From User CFPrefsD For Search List
10:18:38.418524 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:18:38.418599 +0100	Electron	Loading Preferences From User CFPrefsD For Search List
10:18:43.908831 +0100	Electron	SecTrustEvaluateIfNecessary
10:18:44.903010 +0100	Electron	SecTrustEvaluateIfNecessary
10:19:01.992428 +0100	Electron	Loading Preferences From User CFPrefsD
10:19:01.994559 +0100	Electron	Loading Preferences From System CFPrefsD For Search List
10:19:01.994632 +0100	Electron	Loading Preferences From User CFPrefsD For Search List
10:19:02.522120 +0100	Electron	SecTrustEvaluateIfNecessary
10:19:03.015366 +0100	Electron	SecTrustReportTLSAnalytics
10:19:03.227819 +0100	Electron	SecKeychainAddCallback
10:19:34.012104 +0100	Electron	SecTrustReportTLSAnalytics

**Comment by bpasero** [comment]
@bugmenotits To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by bugmenotits** [comment]
Hi, 

Sorry It was my mistake. I had chmod error

**Comment by bpasero** [comment]
@bugmenotits so, no more issues for you?

**Comment by bugmenotits** [comment]
Yes
