### ISSUE TITLE
Can't resize terminal panel up and down

### ISSUE THREAD

**Issue by DarqueWarrior** [microsoft/vscode#45346]
- VSCode Version: 1.21.0
- OS Version: Windows 10 Pro, Version 1709, Build 16299.248

Steps to Reproduce:

1. Ctrl + J (opens terminal)
2. Ctrl + \ (splits terminal)
3. Ctrl + Shift + Up Arrow (Noting happens)

Does this issue occur when all extensions are disabled?: Yes

I can size left and right just not up or down.  I can use Alt + Right or left to switch panes as well. The only issue is Resize Up and Down.

**Comment by kieferrm** [comment]
Same on macOS.

**Comment by Tyriar** [comment]
I thought I created an issue for this but it was just a TODO in code.

https://github.com/Microsoft/vscode/blob/05b995dd9c99b709f41577ab04fe53740f67ccea/src/vs/workbench/parts/terminal/electron-browser/terminalTab.ts#L70-L71

@isidorn is there a nice way to resize the panel up/down (or left/right when it's vertical) by a pixel amount?

**Comment by DarqueWarrior** [comment]
What is odd is it is showing in [the GIF for the feature and documented as working](https://code.visualstudio.com/updates/v1_21#_split-terminals). I think that is why it was labeled as a bug.

**Comment by Tyriar** [comment]
@DarqueWarrior the gif only shows resizing left and right, not up and down?

**Comment by isidorn** [comment]
@Tyriar this was added by @cleidigh try F1 > `View: Increase current view size`

**Comment by Tyriar** [comment]
@isidorn thanks, I'll look into how that's implemented.

**Comment by cleidigh** [comment]
@Tyriar 
I think this has to do with split Windows this is not potentially contemplated
by the increase and decrease commands.  When I initially created these commands
I don't think we could have a split fuel in the terminal .
for normal editor windows it has been a to do item to understand split editors.
right now I just expand or decrease the entire editor window.

would you like me to take this on?

**Comment by Tyriar** [comment]
@cleidigh so what the terminal commands should be doing is resizing up/down by 1 character height (when the orientation is horizontal). If you can programmatically resize the panel then you could do it that way. I won't have time to work on this any time soon.

It's a shame as mentioned in the other issues that these commands work a little differently to the editor one. Maybe we can make it consistent when implementing https://github.com/Microsoft/vscode/issues/14909?

**Comment by cleidigh** [comment]
@Tyriar 
I still have to verify that this is the issue with split panels.  The commands work with a panel and the terminals , but we do have different approaches that might be good to concatenate.  I would like to fix the other issue with the blank selects which I've determined is an issue in both parts of the code.  I can then look at addressing this issue.

**Comment by Tyriar** [comment]
> The commands work with a panel and the terminals

@cleidigh regardless of what is focused the increase/decrease view size commands seem to increase or decrease the horizontal space of the editor for me.

**Comment by cscherrer** [comment]
Unless I'm reading it wrong, the discussion seems specific to key bindings. Is there **any** way to do this? Whether mouse, menus, or keybindings, the only options I've ever seen are for the default size or "maximized". `View: Increase current view size` doesn't do anything  at all on my machine.
```
Version: 1.31.0
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-06T08:51:24.856Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.14-1-MANJARO
```

**Comment by wrightwriter** [comment]
Still not working

**Comment by khoitd1997** [comment]
@cleidigh Are you still working on this? otw, I may try to take shot at it.

**Comment by wrightwriter** [comment]
Thank you <3
