### ISSUE TITLE
Cannot auto generate

### ISSUE THREAD

**Issue by wphr2101** [Microsoft/vscode#45342]
Issue Type: <b>Bug</b>

When each time I was trying to create any C# classes, interfaces, and Angular Components by right clicking the folder and select. It gives me nothing. The system just ignored my commands.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3503)|
|Memory (System)|15.96GB (11.13GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.3.10
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.18
tslint|eg2|1.0.28
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|0.3.1
Angular-BeastCode|Mik|5.2.16
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.1.0
material-icon-theme|PKi|3.2.3
typescript-hero|rbb|2.3.1

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
What are the extensions for which that happens? What do you see in the developer tools console?

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
