### ISSUE TITLE
Bug - Inactive window scrolling

### ISSUE THREAD

**Issue by Koder31** [Microsoft/vscode#45344]
Issue Type: <b>Bug</b>

When VS Code window is open and is active and say a web browser is open beside it (but not as active window), the web browser does not respect scrolling which is set in windows settings. 

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by kieferrm** [comment]
Can you pls provide steps to reproduce the problem? An annotated screenshot would be great.
