### ISSUE TITLE
TypeError: Cannot read property 'verboseLogging' of undefined

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#4534]
- VSCode Version: 
  - Version: 0.10.12-insider 
  - Commit: ef2a1fcaa553d14d7731b284a5ac5e4a55c42936
  - Date: 2016-03-21T11:33:38.240Z
  - Shell: 0.35.6
  - Renderer: 45.0.2454.85
  - Node: 4.1.1
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. I opened a folder.  
   It's 100% reproduced on the folder. But it's not reproduced on another folder. I'm not sure what actual conditions are.

As a result of this error, the explorer area shows nothing.

![image](https://cloud.githubusercontent.com/assets/1937871/13938402/dcb931e6-f010-11e5-9213-5460d4e84c10.gif)
![image](https://cloud.githubusercontent.com/assets/1937871/13938296/d501716c-f00f-11e5-8713-13775809d612.png)

**Comment by bpasero** [comment]
@mysticatea would you be able to share this folder with me?

**Comment by bpasero** [comment]
Found the issue: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L709

**Comment by mysticatea** [comment]
Thank you!

I'm sorry, I cannot share that folder since some reasons.
But fortunately, after I modified [fileService.ts#L709](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L709) with `$this` (`f` in minified code), this issue was fixed.

VSCode seemed to try to open a removed junction folder (I had opened the folder before) when it was running on fileService.ts#L709.

**Comment by bpasero** [comment]
Thanks, we can fix this without further help. For now you will have to use the stable version at least on that folder.

**Comment by DickvdBrink** [comment]
Same issue here; on all my workspaces.
Is this issue there for a lot of people? Might want to create a new insider build if that is the case to get feedback.

**Comment by bpasero** [comment]
To verify, open a folder on Windows with permission denied error and verify that those with permission errors simply do not show up but do not cause other things to show in the explorer.

**Comment by isidorn** [comment]
Verified by opening C:\users, folders like administrator are simply not shown and other look fine
