### ISSUE TITLE
Markdown slow parsing

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#45352]
- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

It took Marked.js 2 seconds to parse below content. I use spaces everywhere so no tabs.

```
"node              node
/  \              /  \
a   b    <----   a    b
                    /
                   z"
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Fixed by c6b1114
