### ISSUE TITLE
[Uninstall] When user uninstall an app then system should delete all the VS code references, files and directories.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4535]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:

1.  Install VSCode alpha build.
2. Open app to verify successfully installation.
3. Close app and uninstall 
4. Verify "Microsoft VS Code Alpha" directory under "C:\Program Files (x86)\"

Actual: "Microsoft VS Code Alpha" is present under "C:\program Files(x86)\"
Expected: All directories, files and references should be deleted when user performed uninstall operation.

**Comment by joaomoreno** [comment]
Closing as won't fix. Inno Setup should handle this correctly.
