### ISSUE TITLE
Too high memory and cpu usage

### ISSUE THREAD

**Issue by ssstylish** [Microsoft/vscode#45357]
Issue Type: <b>Bug</b>

RAM usage is more than 3GB without any files open and CPU usage is 30-40%.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.14.24-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3467)|
|Load (avg)|2, 2, 2|
|Memory (System)|7.69GB (0.12GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by kieferrm** [comment]
Pls have a look at https://github.com/Microsoft/vscode/wiki/Performance-Issues. This helps us tracking down the problem.

**Comment by Parrryy** [comment]
I'm also getting this issue recently, the code helper uses almost 2GB of memory with one file open. This is with all the extensions disabled.
System: 
macOS High Sierra MacBook Pro (Retina, 13-inch, Early 2015)
CPU: 2.7GHz Intel Core i5
Memory: 8GB 1867 MHz DDR3

**Comment by alex20465** [comment]
Same issue here, after I open a JS file the extension sub-process "typescript-language-features" appears, which uses 2GB ram and >40% CPU usage.

Version 1.22.2
Date 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Ubuntu: 17.10
CPU: 2.20GHz Intel Core i7 
Memory: 8GB

**Comment by bpasero** [comment]
Closing, as https://github.com/Microsoft/vscode/issues/45357#issuecomment-371684450 was never answered. New issues should be filed as such.
