### ISSUE TITLE
Breakpoint not hit sometimes - Typescript file

### ISSUE THREAD

**Issue by achawla5000** [Microsoft/vscode#45351]
Issue Type: <b>Bug</b>

Starting with the Febrary 2018 release, occasionally a breakpoint is not being hit, which should be hit.  Additionally, I observed the following behavior - Let's say I set a single breakpoint on line 1369.  Then when the program is run, I see that this breakpoint is not hit.  Then I set a breakpoint on both lines 1352 and 1353 and again run the program.  Now, the breakpoints at lines 1352 and 1353 are hit as expected, and additionally, the breakpoint at line 1369 is hit.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.38GB (8.43GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe C:\Git\Issunc\Front End.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
file-templates|brp|1.2.0
vscode-great-icons|emm|2.1.27
json-tools|eri|1.0.2
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|2.14.0
mssql|ms-|1.3.0
debugger-for-chrome|msj|4.1.0
gitflow|vec|1.1.2

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by achawla5000** [comment]
I submitted both issues #45311 and this one (#45351).  These are different issues, and both exist.

**Comment by kieferrm** [comment]
Do you have sample code (code and launch config) that shows the problem?  We need additional information that helps us tracking this down.

**Comment by ghiscoding** [comment]
I also have this problem since couple weeks in both stable and insiders. In my case it's 2 different Angular App and they both have the problem. The main issue is that when I start the Chrome debugger, the breakpoints turn grey and never get hit, however if I click on any of the grey breakpoint and add another breakpoint then they all turn red in the same file. This issue is per file, if I get the breakpoint red (by doing the trick, click once and reclick it), then the next file will still have the grey breakpoint issue. Since I have problem with 2 Angular App, I would assume it's any Angular app.

**Comment by sarvaje** [comment]
I have the same problem. I know a couple of ways to get the breakpoints hit.
1. when you run the debugger, just start adding/removing breakpoints until your breakpoints turn red.
2. Add a `debugger` in some line, then when the `debugger` is reached, click on `desactivate all breackpoints` two times.

**Comment by roblourens** [comment]
@achawla5000 Are you debugging in Node or Chrome? Can you share your project or a sample that demonstrates the issue?

@ghiscoding Please open a new issue with as many details as possible. A sample project where this reproes would be very helpful

@sarvaje Will keep investigating with you in #45243

**Comment by achawla5000** [comment]
Sorry for the late response - I was busy with end-of-sprint tasks...
I am using the Debugger for Chrome extension for an Angular Typescript app.  Here is an example - Please note the breakpoint on line 1459 - In my first test I see that when I run the program, this breakpoint never gets hit.
![image](https://user-images.githubusercontent.com/11709568/37236869-5c6c2ad4-23da-11e8-9a8b-0a06de7795b9.png)
Then I click the "Deactivate Breakpoints" toggle button in the "Breakpoints" section of the Debugger to deactivate all breakpoints (line 1459 is the only breakpoint).  Then I click the "Deactivate Breakpoints" toggle button to re-activate all breakpoints.  Then I run the program again.  Now, the breakpoint on line 1459 gets hit.
I would like to mention, also, that I observed similar issues at least 10 to 20 times with different code in an Angular Typescript app, and in my view this is a serious new problem which significantly hinders productivity.

**Comment by roblourens** [comment]
Is the breakpoint in code that runs immediately when the page loads? 

> Then I run the program again

Do you mean you reload the page? Or restart debugging entirely?

**Comment by achawla5000** [comment]
@roblourens 
> Is the breakpoint in code that runs immediately when the page loads?

No.

> Do you mean you reload the page? Or restart debugging entirely?

I do not reload the page.  I click the stop button on the Debugger tool, resulting in Chrome closing automatically.  Then I click the "Deactivate Breakpoints" toggle button twice.  Then I click the play button on the Debugger tool to restart debugging entirely.

**Comment by roblourens** [comment]
I updated the Chrome debug extension on Friday, have you seen it with the latest version?

Can you share your project/some sample code that demonstrates the issue?

Or could you set `"trace": true` in the launch config, reproduce it, and upload the log here?

FWIW, deactivating/activating the breakpoints while debugging is not running should not have any effect.

**Comment by deepred5** [comment]
I have the problem too when I use typescript

**Comment by achawla5000** [comment]
@roblourens I have version 4.2 of the Debugger for Chrome extension, and I confirmed that the issue is reproducible with this version.  Also, I confirmed that clicking the "Deactivate Breakpoints" button (toggle on/off) does allow me to hit the breakpoint successfully in the manner described in my post above (from Friday 3/9).

> Can you share your project/some sample code that demonstrates the issue?

I shared sample code in my post above (from Friday 3/9) as well as the contents of my launch.json.  I'll try to create the trace log.

**Comment by ghiscoding** [comment]
Seems to be even worst since yesterday, and even the stable version which I just updated doesn't work anymore either. That means I now have 0 debugging working on my side. The trick or toggling the breakpoint doesn't work anymore :'(

**Comment by roblourens** [comment]
This is probably https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464, please try updating the Chrome extension and tell me whether that helps.

**Comment by rmvanmeeuwen** [comment]
I ran into this also on my Angular/Typescript project. It is really driving me mad... :(

**Comment by achawla5000** [comment]
@roblourens  I'm using vscode v1.21.1.  After updating the Debugger for Chrome extension to 4.2.1, I tested this morning on my Angular/Typescript project, and I no longer see the issue.  Thank you!

**Comment by rmvanmeeuwen** [comment]
I'm using VScode 1.21.1 and Debugger for Chrome Extension 4.2.1, but no luck for me :( Very frustrating I have to say...

**Comment by roblourens** [comment]
@rmvanmeeuwen please open a new issue at https://github.com/microsoft/vscode-chrome-debug/issues

And please set "trace": true in the launch config, reproduce it, and upload the log there.

**Comment by s-KaiNet** [comment]
Hey guys, I have exactly the same issue, however in nodejs project.   
I've created an extremely simple repro repository [here](https://github.com/s-KaiNet/ts-node-46):   
1. clone, npm i
2. Set debug config to `node`
3. F5 - break in index.ts is hit, in parser.ts - never hits.

**Comment by s-KaiNet** [comment]
It looks like it's related to #45657 
Please try repro steps from comment as well
