### ISSUE TITLE
Code Helper use much cpu (100%+) Sometimes

### ISSUE THREAD

**Issue by superlixun** [Microsoft/vscode#45361]
Issue Type: <b>Bug</b>

Code Helper use much cpu (100%+) Sometimes

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (10.75GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.0.2
vscode-great-icons|emm|2.1.24
Lua|key|0.0.9
Go|luk|0.6.77
python|ms-|2018.1.0
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
proto|pet|0.0.2

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
