### ISSUE TITLE
Support Chinese font alignment

### ISSUE THREAD

**Issue by zhang-shaoman** [Microsoft/vscode#45360]
Issue Type: <b>Feature Request</b>

Currently, if Chinese fonts are used in the file, column alignment is not possible, resulting in poor readability.
Hope to support Chinese font alignment, thanks.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.1.7601

**Comment by alexandrudima** [comment]
@zhang-shaoman We respect what the font does. There are some fonts, like `Inconsolata` which render CJK characters with the width of 2 latin characters.
