### ISSUE TITLE
editorActiveLineNumber.foreground doesn't work with breaks in line

### ISSUE THREAD

**Issue by user3323** [microsoft/vscode#45365]
- VSCode Version: 1.22.0-ins
- OS Version: win7x64

![active line number](https://user-images.githubusercontent.com/24613274/37188005-b47a6f54-2355-11e8-96d5-b350475c6175.gif)

**Comment by chiragbhansali** [comment]
I am facing this issue as well.

VSCode Version: 1.20.1
OS Version: win10x64

**Comment by usernamehw** [comment]
Possibly related to #36839

**Comment by rebornix** [comment]
@usernamehw you are right, that shares the same logic.
