### ISSUE TITLE
[Language Pack] tr is not supported to load "Turkish Language Pack"

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#45370]
- VSCode Version: 1.21
- OS Version: Windows 10

**Steps to Reproduce:**

1. Installer Turkish Language Pack version 1.21.1 from Extension
2. Set "locale": "tr" in locale.json
3. Re-launch vscode ->English UI

**Expectation:**
- Show Turkish UI

**Reference:**
- https://github.com/Microsoft/vscode-loc/issues/3
- Version 1.21.2 use trk as workaround. Work as expected.
- https://www.w3schools.com/tags/ref_language_codes.asp

**Comment by dbaeumer** [comment]
The language pack is publish with `trk` language id not `tr`. Transfex using 3 letter language ids where software (including VS Code) usually uses 2 letter language ids. 

For example Bulgarian is correctly published with the 2 letter language id `bg`.

**Comment by dbaeumer** [comment]
I am closing since fixing this is re-publishing the language pack using 2 letter ids.

**Comment by danyeh** [comment]
@dbaeumer , tr language pack v1.21.1 published as tr but didn't work which should work. This is the issue need to investigate. You can change language ID in package.json to tr to try. 
V1.21.2 uses trk as workaround. 
I expect tr can work to align with standard and the pull translation language id requirement.

**Comment by dbaeumer** [comment]
May be I am looking at the wrong file but the language pack 1.21.2 is still published with ID trk. See the attached screen shot.

<img width="495" alt="capture" src="https://user-images.githubusercontent.com/1931590/37273322-b2375fe6-25d9-11e8-91ab-c0b1d2f0444f.png">

I will close the issue again. @danyeh please ping if you still see the problem with a published language pack using 2 letter ids.

**Comment by dbaeumer** [comment]
Reopening

**Comment by dbaeumer** [comment]
Merged in 1.21

**Comment by dbaeumer** [comment]
To verify:

- use attached extension (rename zip extension to vsix)
[vscode-language-pack-tr-1.21.2.zip](https://github.com/Microsoft/vscode/files/1807069/vscode-language-pack-tr-1.21.2.zip)

- install
- start code using --locale=tr.

Ensure that code starts in Turkish

**Comment by dbaeumer** [comment]
@aeschli can you please verify this.

**Comment by aeschli** [comment]
Verified in
Sürüm 1.22.0-insider
Commit ec3c083444c084394ee0cd936074019c1bc0b321
Tarih 2018-03-14T06:14:24.748Z

**Comment by aeschli** [comment]
Also verified on
Sürüm 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Tarih 2018-03-14T14:46:30.761Z
