### ISSUE TITLE
Html Tag matching underline an colorized

### ISSUE THREAD

**Issue by chabinot** [Microsoft/vscode#45374]
Hello,
How can i configure VS Code for matching html tag like in sublime text 3 ?
I mean, when i select a tag in html file, the open and finish match tag is underline.
Regards

**Comment by aeschli** [comment]
Note that we already highlight the corresponding end tag in HTML (but not in PHP, that's #2915)
![image](https://user-images.githubusercontent.com/6461412/36892411-eadc1558-1e04-11e8-872d-feae76e23ec4.png)

Can you confirm whether you are in HTML or PHP? If in HTML, can you attach a sample that shows the problem?
