### ISSUE TITLE
Notifications: Icons in message with only secondary actions not rendered

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#45372]
Version 1.21.0-insider
Commit b76a4a71434d6cdee69fa1d8bdc7533d09598d53
Date 2018-03-02T13:48:32.486Z
OS: Windows 7

@bpasero 
I'm not sure if this is really a typical use case but I don't think completely out of the ordinary
regardless I think things should be rendered the same in both modes IMHO.

A notify message with only a  secondary action will not render the icons in the toast mode,
The same message will render correctly in the notification center mode.

Notify message to reproduce -

		this.notificationService.notify({
			severity: Severity.Info,
			message: 'Test Message\n - Single secondary action',
			actions: {
				secondary:
					[
						new Action('s setaction.1', 's action 1', null, true, () => {
							console.debug('action secondary one');
							return TPromise.as(true);
						}),
					],
			}
		});

Toast notification mode - icons not rendered

![image](https://user-images.githubusercontent.com/25272315/37190457-db70df54-2327-11e8-95f6-f80b5258b095.png)

Notification Center mode:  correctly rendered

![image](https://user-images.githubusercontent.com/25272315/37190224-b700c554-2326-11e8-9d33-750c1adeef21.png)

**Comment by bpasero** [comment]
@cleidigh that is intentional, the toolbar shows up when you hover or select:

![image](https://user-images.githubusercontent.com/900690/37193126-f70581d4-2368-11e8-896e-2013d30e28ba.png)
