### ISSUE TITLE
intellisense strange behaviour

### ISSUE THREAD

**Issue by git-tiger** [Microsoft/vscode#45386]
- VSCode Version: 1.21.0
- OS Version: Linux x64

Steps to Reproduce:
type 'import numpy as np'.
When typing np, intellisense lists 'numpy' and enter fills editor using 'numpy' instead of 'np'.
The intellisense should use 'np' as the search options, but separates 'n' and 'p' as search parameters.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
I'm guessing you talk about TypeScript?

**Comment by git-tiger** [comment]
I am using python.

**Comment by kieferrm** [comment]
Pls file the issue against the python extension [here](https://github.com/Microsoft/vscode-python/issues/new). Thanks!
