### ISSUE TITLE
Wrong cwd is used with multiple workspaces open. [Python]

### ISSUE THREAD

**Issue by Wattleninja** [Microsoft/vscode#45388]
Problem: The current working directory depends on the workspaces open instead of the file that's being executed.

- VSCode Version: 1.21.0
- OS Version: Windows 10

Extensions:
- ms-python.python

Steps to Reproduce:
1. Create two folders each with a single .py file both containing
```
import os
print(__file__)
print(os.getcwd())
```
and add them to your workspace `File -> Add Folder to Workspace`
![image](https://user-images.githubusercontent.com/13973361/37197041-d87f6c0a-23c4-11e8-883a-2f3cc6039186.png)

2. Run both files. Output is as follows
```
# file1.py
d:\demo\ws1\file1.py
d:\demo\ws1
```
```
# file2.py
d:\demo\ws2\file2.py
d:\demo\ws1
```

As you can see the current working directory is `ws1` in both cases instead of relative to where the file is located. The current working directory is decided by whichever one comes first in the Workspace Settings.
```
{
	"folders": [
		{
			"path": "D:\\demo\\ws1"
		},
		{
			"path": "D:\\demo\\ws2"
		}
	],
	"settings": { }
}
```
Or if at least one of the workspaces has a launch.json with a runable configuration then it will default to whichever one is selected.
![image](https://user-images.githubusercontent.com/13973361/37198131-fac38266-23c8-11e8-9d96-9f2d8d393e13.png)

Similar example is reproducible using cmd
After changing directory the file is executed using its absolute path from a directory (I've used the same directory as the workspace, but it can be any) the output is the same.
```
D:\demo\ws1>python D:\demo\ws1\file1.py
D:\demo\ws1\file1.py
D:\demo\ws1

D:\demo\ws1>python D:\demo\ws2\file2.py
D:\demo\ws2\file2.py
D:\demo\ws1
```
This example was demonstrated using two workspaces but this also applies to if a single file is open `File -> Open File` and a workspace is also open it will use the path of the workspace when executing the standalone file.

**Comment by kieferrm** [comment]
Thanks for the detailed report. Can you pls file the issue against the python extension [here](https://github.com/Microsoft/vscode-python/issues/new). Thanks a ton!
