### ISSUE TITLE
Extend CodeActionProvider to by queryable for all possibly actions to aid keybinding

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#45383]
We now have the ability for users to key-bind groups of quick-fixes, but there's no way for them to know what the IDs are without us documenting them. I've [documented them in my readme](https://github.com/Dart-Code/Dart-Code#refactoring-kinds) but the list is long and can actually change depending on the version of the SDK you have.

It'd be great if Code could ask a provider for all of their actions (returning a nice display name, and the CodeActionKind) and then aid the user in binding them, so the list was always up to date.

**Comment by jrieken** [comment]
Easier said than done because some language servers themselves are dynamic (think of TypeScript server plugins) That's why we define certain prefixes which should be extended...

**Comment by DanTup** [comment]
The same is true for Dart, but my plan if you'd do this is to request the server can provide me with its "full list" (they exist inside the server).

It's not a big deal, but as a Code user I'd much rather have auto-completion or something than have to go looking up external docs (there's no way to discover the IDs from seeing the refactor inside of the editor).

Another option is for Code to cache them as it seems them (maybe just for the session?) so the user can at least find the IDs of the ones they've seen. This might feel a bit weird though since it's not clear to the user why they only see a subset.

**Comment by mjbvz** [comment]
I believe this was partially addressed by #47702

Intellisense for `codeActionsOnSave` is tracked by #52846. The other place we could consider adding intellisense is for keybindings. As @jrieken notes though, this gets tricky if you want to setup a keybinding for an extension that has not yet been activated. We likely would want a new contribution point in the `package.json` for that
