### ISSUE TITLE
extended host terminated unexpectedly

### ISSUE THREAD

**Issue by lijq123** [Microsoft/vscode#45382]
Issue Type: <b>Bug</b>

When I open the .py file, the bottom right corner shows that the extended host terminated unexpectedly

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|7.95GB (3.27GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
vscode-caniuse|aka|0.5.3
autopx2rem|ale|0.0.4
Bookmarks|ale|0.18.2
px2rem|art|0.0.3
vs-code-css-comments|ash|1.0.3
GBKtoUTF8|buk|0.0.2
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.19
vscode-eslint|dba|1.4.7
vscode-faker|dee|1.2.1
jquerysnippets|don|0.0.1
Vue2|duc|0.1.3
gitlens|eam|8.1.0
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
vsc-material-theme|Equ|1.5.0
auto-rename-tag|for|0.0.15
terminal|for|0.0.10
minify|Hoo|0.3.0
rest-client|hum|0.17.0
output-colorizer|IBM|0.1.2
emoji-code|idl|0.7.0
autofilename|Jer|0.1.3
docthis|joe|0.6.0
auto-comment-blocks|kev|1.0.1
vscode-gutter-preview|kis|0.12.2
ftp-sync|luk|0.3.3
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
vscode-filesize|mkx|2.0.0
theme-monokai-pro-vscode|mon|1.1.5
easy-less|mrc|1.4.5
vscode-autoprefixer|mrm|2.1.2
mssql|ms-|1.3.0
python|ms-|2018.2.0
vetur|oct|0.11.7
vscode-versionlens|pfl|0.20.0
java|red|0.20.0
live-sass|rit|1.3.0
LiveServer|rit|3.2.1
vscode-icons|rob|7.20.0
sass-indented|rob|1.4.8
partial-diff|ryu|0.5.1
code-settings-sync|Sha|2.9.0
easysass|spo|0.0.6
guides|spy|0.9.1
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.3.0
vscode-maven|vsc|0.5.2
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0
vscode-preview-server|yui|1.0.1
markdown-all-in-one|yzh|1.1.0

(5 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
Pls try to isolate which of the extensions you have installed causes the issue on your python files. I only see ms-python, but there may be others that kick in. One way to do this, is to close all editors. Restart VS Code. From the command palette run "Developers>Show Running Extensions". You now see all activated extensions.  Then open a `py` file. See which additional extensions get activated. Disabled them one-by-one and see which one causes the problem.

Pls file the issue against the extension. Thanks a ton.
