### ISSUE TITLE
Support validation on RenameProvider

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#45384]
There's a new RenameProvider API coming to allow us to resolve the initial value in the rename box. It'd be good if we could also provide a validation method, so the box can go red if the user types characters that are not valid here in our language (similar to the window.showInputBox).

**Comment by jrieken** [comment]
I like the idea but lets' fold the discussion into #7340.

**Comment by jrieken** [comment]
Branching off from #7340 again
