### ISSUE TITLE
Do not close Command Palette dropdown when switching applications

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#45381]
- VSCode Version: 1.21
- OS Version: Mac OS 10.13.3

Steps to Reproduce:

1. Keep 2 applications open (example, Chrome & VSCode)
2. Press `Cmd+P` (it opens up a dropdown of files) in VSCode
3. Now switch to another application(example, Chrome) using `Cmd+Tab`
4. Switch again to VSCode (notice the dropdown of files is gone while the expected behaviour is it stays)

Does this issue occur when all extensions are disabled?: Yes

Now this is the issue which has caused me problems when using an extension called [Advanced New File](https://marketplace.visualstudio.com/items?itemName=patbenatar.advanced-new-file).

Checkout [this issue](https://github.com/dkundel/vscode-new-file/issues/46) for more info on that problem.

I have also made a GIF showing the above steps -

![screencast](https://user-images.githubusercontent.com/16436270/37193657-de1d9f6c-2390-11e8-84f9-25595e47fa73.gif)

In the GIF before switching to Safari, the dropdown of files is open & then when switching from Safari to VSCode it closes while it should remain open

**Comment by bpasero** [comment]
Try with: `"workbench.quickOpen.closeOnFocusLost": false`

**Comment by deadcoder0904** [comment]
Thanks man 🎉 

I wonder why it isn't set to `true` by default 🤔
