### ISSUE TITLE
Proposal for customization autocomplete sort priority

### ISSUE THREAD

**Issue by artalar** [microsoft/vscode#45385]
- VSCode Version: 1.20.1
- OS Version: elementary OS 0.4.1 Loki (Built on "Ubuntu 16.04.3 LTS")
- `code --disable-extensions`

Autocomplete - it's very useful option of IDE. But **vscode** do it sometimes not good.
First of all we need to improve autocomplete sort priority by default.

```javascript
const autocompleteSortPriority = [
    // example
    /* 1 */'possible reserved words' // `for`, `extends` etc, if it won't throw SyntaxError
    /* 2 */'lexical environment', // in current file
    /* 3 */'snipets',
    /* 4 */'global scope', // and auto exports
    /* 5 */'not need at all',
]
```

Current (wrong) behavior:

> ![image](https://user-images.githubusercontent.com/27290320/37197241-0f58a00a-238b-11e8-933b-2f1188310978.png)
Wrong order, 'lexical environment' not use at all.
# 
> ![image](https://user-images.githubusercontent.com/27290320/37197840-564a8ba2-238d-11e8-8f70-2fefe29ddd06.png)
Wrong order

> ![image](https://user-images.githubusercontent.com/27290320/37197863-699c4182-238d-11e8-9362-44c2ef3aea65.png)
"2" - not use at all

> ![image](https://user-images.githubusercontent.com/27290320/37198002-da11764e-238d-11e8-8b5f-dee307405ad5.png)
`extends_for_test_variable` must be after `eee_variable`.

The could be a lot of examples to add. So, it is possible to improve autocomplete sort priority by this simple ruls?

And much better, if we could customize `autocompleteSortPriority` in settings of possible ruls list.

**Comment by grant** [comment]
I had a `settings.json` error which caused bad autocompletion (`snippetSuggestions: top`).

Maybe check out these settings:

```json
"editor.snippetSuggestions": "bottom",
"editor.suggest.localityBonus": true,
"editor.suggest.filterGraceful": true,
"editor.suggest.snippetsPreventQuickSuggestions": true,
```

**Comment by randrade23** [comment]
Is this suggestion still being considered? Asking since we recently got a new feature for #45039 (also see #71084) and it's kind of related...

**Comment by htho** [comment]
I think this is still needed. Suggestions based on the scope are the most natural thing.

I like having text suggestions around, but they are the least interesting to me, so they should be put at the bottom of the list. There they can be ordered either alphabetically or by the localitybonus.

When get intellisense for properties of an object, they should be on top of the list.

On the other hand, in a string, string suggestions are more useful.

**Comment by tj** [comment]
Local scope should definitely get priority by default IMO, in Go's case you get a bunch of import suggestions for packages you're not even using before you get a local variable

**Comment by randrade23** [comment]
It's kind of disappointing that such a useful feature is not even considered for Backlog, to be honest.

**Comment by mjbvz** [comment]
For js/ts, we improved the default sorting order with https://github.com/microsoft/TypeScript/issues/15024

@jrieken I feel @randrade23 is correct that this feature request is similar to #45039 and could be handled in core VS Code in some way. Assigning back to you for more feedback

**Comment by simkessy** [comment]
How do I get object properties to the top of the suggestions? I'd rather get properties listed first than unrelated snippets from emmet

**Comment by jrieken** [comment]
This is mostly covered with #45039 - which we have shipped a while back

**Comment by gmaggio** [comment]
> This is mostly covered with #45039 - which we have shipped a while back

But I think the **priority ordering** part has not been covered, which I think is the main point here.

**Comment by nocker01** [comment]
> > This is mostly covered with #45039 - which we have shipped a while back
> 
> But I think the **priority ordering** part has not been covered, which I think is the main point here.

I agree!  I'm googling to try and figure out how to configure the order.  Personally I want all the methods together and all the snippets together etc. and to be able to order methods before snippets etc.

**Comment by KrestenHelstrup** [comment]
+1. As an embedded developer I would love to prioritize methods over defines.

**Comment by trojanj** [comment]
As for me, it would be great to be able to customize the order of import suggestions. Don't understand why this feature hasn't implemented yet

**Comment by earsnot** [comment]
I too would love to see some way of prioritizing methods over defines.

**Comment by dustinlacewell** [comment]
@trojanj I opened a request here: https://github.com/microsoft/vscode/issues/122281

**Comment by smolgumball** [comment]
Sorting order based on suggestion type (locals before word-based suggestions, etc.) is still needed and not covered by the feature introduced with #45039

**Comment by FMorschel** [comment]
@jrieken This issue has now more than 80 up votes (4 times the ammount asked on the docs above - vscodebot) and there have been four different new issues regarding this. Please reconsider reopening as I tagged you following the same docs instruction.

**Comment by dhowe** [comment]
Status? Please re-open
