### ISSUE TITLE
Review added tree API: collapseDeepestExpandedLevel

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#45397]
https://github.com/Microsoft/vscode/commit/263575c64cf73b8acfc9797087872b6293f856b4 introduced a [`collapseDeepestExpandedLevel`](https://github.com/Microsoft/vscode/blob/7f4507656846b62373da8acf8aba99c1e1d59a53/src/vs/base/parts/tree/browser/tree.ts#L111) API to the tree via https://github.com/Microsoft/vscode/pull/37451

I'm pretty sure that method's implementation can be achieved outside the tree itself. There are `getNavigator`, `isExpanded` and `collapse` methods on it. If so, please remove the API method and implement on the search usage side.

**Comment by roblourens** [comment]
This was added to the tree with the idea in mind that it would be useful elsewhere like the file explorer. And in fact I'd really like to have the same behavior on the file explorer. So moving it into search code is not the right thing to do but it could go into some TreeHelper class outside of the tree itself.

**Comment by joaomoreno** [comment]
No need to overload with classes. A simple `function collapseDeepestExpandedLevel(...)` util function would do.

**Comment by RMacfarlane** [comment]
@joaomoreno @roblourens I don't think this is actually achievable outside the tree itself with the current tree API. It needs to calculate the tree depth to collapse to, and the navigator from `getNavigator` just returns elements of the tree without the context of where they are in the tree.

IMO, it makes sense for this method to stay on the tree since it's coupled with the tree's data

**Comment by joaomoreno** [comment]
> It needs to calculate the tree depth to collapse to, and the navigator from `getNavigator` just returns elements of the tree without the context of where they are in the tree.

Good point.

But this is really only used for search. I don't really buy into the generic usefulness of this as an API call, which needs to be maintained for the entire tree's lifecycle.

As far as I am aware, search trees can only go 2/3 levels deep, depending on whether there are multiple folders in the workspace or not. That knowledge is kept in the search's tree user; the same entity knows exactly what it should collapse or otherwise. Can't it just call the right calls?
