### ISSUE TITLE
split terminal - kill window shortcut key

### ISSUE THREAD

**Issue by muscaiu** [Microsoft/vscode#45390]
I open/close terminal windows pretty often and want to know if there is a key shortcut to this.

![kill_terminal](https://user-images.githubusercontent.com/11426309/37198885-757aa78c-2388-11e8-9ef6-a12c39e88294.jpg)

Is such a feature available yet?

**Comment by usernamehw** [comment]
You can assign one:
1. Go to keybindings <kbd>Ctrl</kbd>+<kbd>k</kbd> <kbd>Ctrl</kbd>+<kbd>s
2. Search something like `termkill`
3. Assign a key

**Comment by Tyriar** [comment]
The challenge here is finding one that makes sense, I couldn't find one when the terminal was added. I use ctrl+shift+x but it shows the extension viewlet on Windows/Linux.

```js
{ "key": "ctrl+shift+x",    "command": "workbench.action.terminal.kill" }
```
