### ISSUE TITLE
[feature request] editor.wordHighlightBorderStyle et al.

### ISSUE THREAD

**Issue by will-stone** [microsoft/vscode#45396]
- VSCode Version: 1.21
- OS Version: macOS Sierra/HS

With the recent release, themers are able to add borders to highlighted words (thank-you for this). However, it'd be nice to be able change the style of the borders using something like: 

`"editor.wordHighlightBorderStyle": "solid"` / `"editor.wordHighlightBorder.style": "solid"`

Then provide `solid`, `dashed`, `dotted` as options.

**Comment by kanlukasz** [comment]
It could be merge with this -> https://github.com/microsoft/vscode/issues/46804

**Comment by rebornix** [comment]
Let's track in #19534
