### ISSUE TITLE
API for hiding characters in a file

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [microsoft/vscode#45393]
Following [a discussion](https://github.com/Microsoft/vscode-extension-vscode/issues/98) with @bpasero, I'm proposing an extensibility API here. I'm willing to work on a PR toward creating this API if someone points me at a starting direction.

## Use case

I want [my extension](https://github.com/keyvan-m-sadeghi/indented/) to parse `js` files and **hide** (not delete) the visual clutter of opening and closing braces (`{` and `}`) with a button located in the status bar (next to `TabSize`, etc.). I'd later want the extension to add any missing braces to the file based on the indent.

## API

I need to be able to tell VSCode to hide specified (line/column start + offset) characters or lines (line number) in a file open in the editor.

**Comment by jrieken** [comment]
cc @aeschli as this touches on folding

**Comment by aeschli** [comment]
We'd need the editor to support that. Currently, only full lines can be hidden.

**Comment by keyvan-m-sadeghi** [comment]
@aeschli what is the API for hiding full lines?

**Comment by aeschli** [comment]
It's an internal API, to be used only by folding, see https://github.com/Microsoft/vscode/blob/9b25468ef0dcc9c422bf919166de0dec95719611/src/vs/editor/contrib/folding/folding.ts#L242
