### ISSUE TITLE
Incorrect styling for razor files with curly and round braces pair

### ISSUE THREAD

**Issue by Kurira** [Microsoft/vscode#45403]
- VSCode Version: 1.21
- OS Version: Windows 7 Ultimate

Steps to Reproduce:

1. Create file `test.cshtml`
2. Paste code:
```HTML
<span>{</span>
    <span>(</span>
    <div></div>
<span>}</span>
```
3. Check styling after round opening brace `(`, in this case `</span><div></div><span>}</span>`.
![image](https://user-images.githubusercontent.com/14815898/37206195-5433870c-23a0-11e8-9656-672fd303ba6e.png)

Everything after opening brace switches to `text.html.cshtml` and stops being styled correctly.
It's strange that it doesn't occur in `.html` files (curly braces are just the part of html text and opening ones seems to trigger this behavior).

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
This issue was moved to demyte/language-cshtml#19
