### ISSUE TITLE
editor.stablePeek not working

### ISSUE THREAD

**Issue by Sumoa** [Microsoft/vscode#45404]
Issue Type: <b>Bug</b>

If i understood the setting "editor.stablePeek" correctly, if it is set to true, it should prevent preview tabs from closing, similar to the behavior, when double clicking the tab.

That is not the case on my system, even with all extensions disabled.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1606024|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.3.0
vscode-docker|Pet|0.0.25
lorem-ipsum|Tyr|1.2.0
Angular2|UVB|0.4.1
path-intellisense|chr|1.4.2
githistory|don|0.4.0
gitlens|eam|8.1.0
tslint|eg2|1.0.28
javac-linter|fau|1.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.1
code-python-isort|fre|0.0.3
rest-client|hum|0.17.0
docthis|joe|0.6.0
swagger-doc-viewer|mim|1.0.4
python|ms-|2018.2.0
debugger-for-chrome|msj|4.1.0
copy-json-path|nid|0.0.1
vscode-json-transform|oct|0.1.2
angular-component-extension|oni|0.0.13
java|red|0.20.0
json-organizer|rin|0.0.3
vscode-icons|rob|7.20.0
angular-follow-selector|san|1.1.1
expand-selection-to-scope|vit|0.2.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2
vsc-jsonsnippets|wmo|0.1.4

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by kieferrm** [comment]
@Sumoa  what you want is `"workbench.editor.enablePreview": false`. `stablePeek` is for the peek view that is used, for example, for Find All References.
