### ISSUE TITLE
[html] For auto close tag, after finish type the code, quick press 'tab' to move the cursor to the end of the close tag

### ISSUE THREAD

**Issue by baonguyenx** [microsoft/vscode#45402]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
@baonguyenx Can you add a code sample and the steps with the expected result?

**Comment by aeschli** [comment]
Closing as more information is needed.
