### ISSUE TITLE
Feature request: install local extensions

### ISSUE THREAD

**Issue by minggo** [Microsoft/vscode#4540]
Now can only install extensions into 

* **Windows** %USERPROFILE%\.vscode\extensions
* **Mac** $HOME/.vscode/extensions
* **Linux** $HOME/.vscode/extensions

I think it is more convenient if can install an extension in local project, then every project can have different extensions.

**Comment by felixfbecker** [comment]
Maybe something like an `.vscode/extensions.json`

**Comment by Thaina** [comment]
+1

Should be just check at /.vscode/extensions in project folder the same way as global extensions

**Comment by Thaina** [comment]
Oh this is duplicated to #347
