### ISSUE TITLE
Bug in intellisense

### ISSUE THREAD

**Issue by federicoviceconti** [Microsoft/vscode#45401]
- VSCode Version: 1.20.1
- OS Version: Win 10

Intellisense has a strange behaviour:
- When I work for a long time, helps doesn't appear (when I write or when I use CTRL+SPACE).
- CTRL+ Click combination doesn't work as well.

To solve I need to restart the editor.
Does this issue occur when all extensions are disabled?: No

--EDIT
This behaviour is met when I work with JS, Typescript and React projects.

**Comment by kieferrm** [comment]
Intellisense is provided by language specific plug-ins. Some of them we ship out of the box like javascript, typescript, css, html, json. Others are coming through extensions. If it's not a built-in extension, pls file the issue against the extension.
