### ISSUE TITLE
Some Java keywords missing in editor

### ISSUE THREAD

**Issue by SMadani** [Microsoft/vscode#45405]
- VSCode Version: 1.21.0
- OS Version: Windows 10 Enterprise v1607

Steps to Reproduce:

The following reserved keywords in Java are not highlighted and treated as plain text by the Java editor:

- instanceof
- goto
- const

Furthermore, Java 10 adds the context-sensitive "var" word which, in appropriate scenarios, should be highlighted as a keyword.

**Comment by kieferrm** [comment]
![screen shot 2018-03-09 at 9 20 44 am](https://user-images.githubusercontent.com/4674940/37220348-2f9e211a-237b-11e8-98b8-a7a9ff75b47e.png)

**Comment by SMadani** [comment]
I'm not sure what IntelliSense is or what it has to do with this problem, but I have the Java extension installed and still get this problem. Anyway, if I'm not mistaken, VS Code has/should have basic support for the languages it "recognises" like Java. Keyword highlighting is something fairly basic, and given most other Java keywords are supported, I don't see why these have been left out.

**Comment by kieferrm** [comment]
@SMadani the highlighting is our issue. That's why we keep the issue.

I thought I saw in your original comment that you said you don't get completions for those keywords. Thus, my comment above. But, since it's not in your original comment, I was mistaken.

**Comment by aeschli** [comment]
`instanceof` was missing in the default themes. I added it.

'goto' and 'const' are missing in the grammar in https://github.com/atom/language-java.
Do you mind filing the request there?

**Comment by SMadani** [comment]
Done, the issue can be found [here.](https://github.com/atom/language-java/issues/136)

**Comment by aeschli** [comment]
@SMadani Awesome, thanks!
