### ISSUE TITLE
IntelliSense get's out of it's position when list gets shorter at the end of the file

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#45408]
- VSCode Version: 1.21.0
- OS Version: macOS High Sierra (latest update)

In the new version, sometimes when typing intelliSense gets out of the position like this:

<img width="751" alt="screen shot 1396-12-18 at 5 30 03 pm" src="https://user-images.githubusercontent.com/2157285/37211274-a5677f78-23c0-11e8-9cf1-5281d8296d14.png">

For now I have seen it on Go, C++ and TypeScript. Also it happens time to time about 1/20.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @pmkary. This is a regression.

Root cause: https://github.com/Microsoft/vscode/commit/85ac36ee4c5eb9dd922af1265c6850d75448f6eb#diff-caac303ecc98a837b262c2c9a093026d

**Comment by pmkary** [comment]
Thanks a lot for fixing it and for such a quick investigation 👍

**Comment by faintsignal** [comment]
fyi: _gets_ / _its_
