### ISSUE TITLE
Debug icon polish

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#45406]
After merging in the new icons here is still things left to be done:
- [x] Breakpoint hint decoration takes priority over regular breakpoint decoration. If a user hover over breakpoint it should show that decoration, not the transaparent one. For this we would need the breakpoint-hint icon back, since otherwise it is hard for me to prioritize css rules usch that this one is not respected
- [x] Start icon in select box looks too big - compare it to debug toolbar
- [x] Breakpoints have increased in size, let's decrease their size a bit
- [x] Restart icon looks too large

![screen shot 2018-03-09 at 14 11 52](https://user-images.githubusercontent.com/1926584/37209012-d4c65f5e-23a3-11e8-978c-78d24e6a5e82.png)

fyi @chryw

**Comment by chryw** [comment]
@isidorn thanks!
I already have some of these fixed on my own fork. Just tackling some conflicts now. will keep you posted!

**Comment by isidorn** [comment]
@chryw awesome, thanks!

**Comment by isidorn** [comment]
- [ ] `current-and-brekapoint.svg` and `stackframe-and-breakpoint.svg` are not correct, since they only have the arrow, not the red breakpoint dot
- [ ] With the new breakpoint size the conditional breakpoint icon does not really work since the equality lines are too far apart (this can also be seen in your screenshot on the BREAKPOINTS view)
- [ ] The new breakpoint size makes the breakpoints looks more square like, and not like a perfect circle. I am not sure if this is just me or the shape of the breakpoint also changed, not only the size?
![screen shot 2018-03-13 at 10 00 47](https://user-images.githubusercontent.com/1926584/37331852-6db9ae88-26a5-11e8-91ce-ea2a632229ec.png)
- [ ] Pause buttton might need to have the two parallel lines closer - feels too strong now imho

**Comment by isidorn** [comment]
@chryw Everything is tackled except my comment about the conditional breakpoint - I still feel like the parallel horizontal lines are too far apart and bringing them closer would make it look more like an equality sign which is the point of the icon. What do you think?

![screen shot 2018-03-14 at 11 15 41](https://user-images.githubusercontent.com/1926584/37396392-0c9c692c-2779-11e8-8706-6c34c6452da6.png)

**Comment by isidorn** [comment]
@chryw this looks great! So yes yes

**Comment by isidorn** [comment]
@chryw we seem to have done everything on the list. Closing this item.
FYI one use so far complained that we reduced the breakpoint size, but let's wait for more feedback. Just so you know that it might happen that we have to bring back the old size some time next week if more poeple do not like it.

Thanks again for your great help
