### ISSUE TITLE
${workspaceFolder} does not convert correct path to gdb in WSL

### ISSUE THREAD

**Issue by ajssousa** [Microsoft/vscode#45418]
- VSCode Version: 1.21.0
- OS Version: Windows 10 1709

Hi.

I have the WSL using Ubuntu and want to use gdb installed on WSL through the VSC.
Evertything works fine if i use the full path like in WSL (e.g. /mnt/c/Users/..)

The problem is if i want to use relative paths, the VSC is not converting an passing right to gdb inside WSL.

Steps to Reproduce:
1. 
My setup:

            "name": "gdb using WSL bash",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/s3/S3IDMain",
            "args": [""],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}/s3/",
            "environment": [],
            "externalConsole": true,
            "pipeTransport": {
                "debuggerPath": "/usr/bin/gdb",
                "pipeProgram": "C:\\Windows\\sysnative\\bash.exe",
                "pipeArgs": ["-c"],
                "pipeCwd": ""
            },
            "sourceFileMap": {
                "/mnt/e": "e:\\"
            },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },

![image](https://user-images.githubusercontent.com/37220160/37216821-b2f7e7fc-23b3-11e8-8689-61180fcaac78.png)

It says Unexpected GDB output from command "-environment-cd"

Using the ${workspaceFolder} or even using the Linux relative paths (../) he is not converting correctly to send to gdb. If the put the full path as a Linux style, no problem (e.g. of full path that works: /mnt/e/edws/svn-edws/s3/S3Trunk/S3/S3Mains ).

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#1660

**Comment by weinand** [comment]
Today VS Code knows nothing about WSL. All WSL support must come from a debug extension.

**Comment by ajssousa** [comment]
Ok, the WSL is the final use of the debug but the problem is not WSL.

The ${workspaceFolder} variable is always converting to Win32 type path. This is correct since I'm in Windows.
But it is possible to have a path translation for the ${workspaceFolder} to a Linux or Windows path type, maybe using a "Linux" or "Win32" tags like cpptools extension is using for the include paths in cpp projects?

**Comment by weinand** [comment]
Node debugging supports a mapping from local paths to remote paths. This is used to map Windows paths to WSL paths. But as I said: this is a feature of Node debugging.

We are working on general support for remote scenarios.
