### ISSUE TITLE
Auto Update perpetual fail

### ISSUE THREAD

**Issue by sosensible** [Microsoft/vscode#45413]
Issue Type: <b>Bug</b>

The insiders has been claiming to be trying to update and it says "Visual Studio Code - Insiders 1.22.0-insider is being installe..", for two days. No change or restart of the app either.

VS Code version: Code - Insiders 1.21.0-insider (a903bd38fbe9006c076d218ff69fe1ee0160f815, 2018-03-06T11:09:37.589Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|15.91GB (2.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.13.0
vscode-eslint|dba|1.4.7
gitlens|eam|8.1.0
json2ts|Gre|0.0.6
vscode-cfml|Kam|0.3.1
ts-extension-pack|loi|0.0.1
vsliveshare|ms-|0.2.206
debugger-for-chrome|msj|4.1.0
commandbox|non|0.0.1
vscode-coldbox|ort|0.1.0
vscode-testbox|ort|0.1.1
tsimporter|pmn|1.2.14
move-ts|str|1.11.1

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
Does it reproduce if you fully uninstall and reinstall Code?

**Comment by sosensible** [comment]
Full reinstall worked. I have not seen an update after reinstalling as far as that goes.

**Comment by joaomoreno** [comment]
OK let me know if updates works now.

**Comment by sosensible** [comment]
It did this time.

**Comment by sosensible** [comment]
Wait... it appeared to ... but it still shows an update. Testing again.

**Comment by sosensible** [comment]
No, it still doesn't install. Sorry, when it restarted that first time it
was supposed to have installed it showed no updates then the (1) appeared.
:(

**Comment by joaomoreno** [comment]
So, walk me through the experience. You get a notification that there's an update available, you say "OK Let's do it", you get an admin prompt, you say "OK", then the progress indicator appears... and then what?

A screen recording would be best!

**Comment by sosensible** [comment]
OK, first I see the update (1) on top of the gear. Then I pick the gear by
clicking with the mouse. I select, "restart to update" and it seems to be
restarting and updating. (same road so far)

OK, now after the restart, wait longer than I did when I said... wahoo it
worked. Because there is that amazing notice again. Yes (1) floats over the
gear. This time the option is "Install Update". The notice showed and the
wait gear showed (1) again. The notification says that "Visual Studio Code
- Insiders 1.22.0-insider is being installe.." but over the gear again it
shows (1). Yes, the rest of the notice is there saying it is being
installed in the background. ... but is it? (the waiting game begins... and
if past is an indicator... the question is how long before I figure out it
is not going to update.)

Well, I could have rebooted windows, even windows 95 faster than this.
Still waiting. :(

Note: Visual Studio LiveShare is the renaissance developer's product of the
year.

**Comment by joaomoreno** [comment]
Please send me a video recording. It's very hard to understand your steps description.

**Comment by sosensible** [comment]
It did finally upgrade right, but it did not notify me when it was ready.
It set the gear to the (1) count but not a notice. It just looked like it
was trying to tell me the same thing again. I expected a popup. Good enough
for now.

**Comment by joaomoreno** [comment]
OK Great to know. We have an open issue to improve the notification, so I'll show it soon.
