### ISSUE TITLE
tsconfig.json "experimentalDecorators" was ignored in subfolder

### ISSUE THREAD

**Issue by nodejayes** [Microsoft/vscode#45411]
- VSCode Version: 1.21.0
- OS Version: Ubuntu Mate 17.10 x64
- the tsc can successfully compile the project
- i try the vscode(2.7.2) typescript version and the version installed by npm(2.7.1, 2.7.0, 2.0.0)

Steps to Reproduce:

1. create a new directory
2. install typescript 2.7.2
3. create a tsconfig.json in this directory with this content to enable experimental Decorators

```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "allowJs": true
    }
}
```
4. create an index. ts file with this content in the directory

```typescript
function testdec(constructor: Function) {

}

@testdec
class Test {

}
```
5. create a subdirectory and move the index. ts file to this directory

---

What happens if the type script file is located in the directory where the tsconfig. json is located, no warning will be displayed if not then a warning will be displayed, as if the settings of tsconfig. json are ignored.

![bildschirmfoto zu 2018-03-09 16-00-03](https://user-images.githubusercontent.com/19733045/37214289-e1c45790-23b4-11e8-9038-6c31b6958a15.png)

![bildschirmfoto zu 2018-03-09 16-00-18](https://user-images.githubusercontent.com/19733045/37214317-f37769fa-23b4-11e8-9a17-57b082f92ea9.png)

**Comment by mjbvz** [comment]
I can't repo this in a simple project. In `src/index.ts`, what happens if you run `TypeScript: Go to project configuration`?

**Comment by nodejayes** [comment]
@mjbvz i get the message "The file is not part of a type script project"

![bildschirmfoto zu 2018-03-10 11-21-20](https://user-images.githubusercontent.com/19733045/37241228-134b81d4-2456-11e8-9cc9-444418248cf7.png)

**Comment by mjbvz** [comment]
Two more things to try:

1. Add an `exclude` section to your `jsconfig.json`:

```
{
    "compilerOptions": {
        "allowJs": true,
        "experimentalDecorators": true
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

2. Try using `typescript@next` by following these instructions: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions This issue you reported sounds similar to https://github.com/Microsoft/TypeScript/issues/20023

**Comment by nodejayes** [comment]
I tried these two things but unfortunately without success.

I'm beginning to think it must be typescript, because I can reproduce the same error in the Atom Editor.

My used Typescript version is now 2.8.0-dev.20180318

**Comment by nodejayes** [comment]
Ok this is not an Error its my Fault.

When i add the src Folder to the include it works.

```json
{
    "compilerOptions": {
        "allowJs": true,
        "experimentalDecorators": true
    }
}
```

Thanks for your time.
