### ISSUE TITLE
Korean characters problem

### ISSUE THREAD

**Issue by wolfkang** [Microsoft/vscode#4541]
- VSCode Version: 0.10.11
- OS Version: Windows 7 64bit Home

Steps to Reproduce:

1. Turn on Korean
2. Type any Korean characters
For example, when I type '비', '주', '얼', '스', '튜', '디', '오' continuously, VS Code displays these in each typing.
비
비비주
비주비주얼
비주비주얼스
비주얼비주얼스튜
비주얼스비주얼스튜디
비주얼스튜비주얼스튜디오

Please check this out.

**Comment by alexandrudima** [comment]
Fixed by #5615
