### ISSUE TITLE
App uninstalled if machine restarted while there is pending updates

### ISSUE THREAD

**Issue by aliry** [Microsoft/vscode#45427]
Issue Type: <b>Bug</b>

Recenty background update is added for VSCode
However, I've noticed if there is pending updates (downloaded and waiting for vscode restart) and I restart my machine then the app is completly gone (uninstalled) and I have reinstall.

VS Code version: Code - Insiders 1.22.0-insider (3817c899cae312e0e989da8bfbc61308cfbf45f1, 2018-03-09T05:15:56.454Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (7.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|8.1.0
tslint|eg2|1.0.28
githd|hui|1.1.1
prettify-json|moh|0.0.3
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
git-merger|sha|0.3.7
addDocComments|ste|0.0.8
code-spell-checker|str|1.6.5
markdown-all-in-one|yzh|1.1.0

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
This has been fixed since. The updater should block shutdown until it is done.

Here's the updated experience:

https://www.youtube.com/watch?v=xFDq0P0zF4g
