### ISSUE TITLE
VSCode tooltips don't respect DPI scaling

### ISSUE THREAD

**Issue by rbirkby** [microsoft/vscode#45424]
- VSCode Version: 1.20.1
- OS Version: 1709 OS Build 16299.125

Steps to Reproduce:

1. Run multi-monitor with different DPI scalings on each monitor
2. Hover over a UI element to show a tooltip

Note: VSCode itself was set to default zoom.

This next screenshot is taken on a monitor with 200% dpi scaling:

![image](https://user-images.githubusercontent.com/203034/37219896-c5ee3c40-23bc-11e8-9219-125936c80f61.png)

Moving the same VSCode window to a 100% scaled monitor, the tooltip is sized correctly:
![image](https://user-images.githubusercontent.com/203034/37219962-fdc39c64-23bc-11e8-941d-777712f9b117.png)

**Comment by bpasero** [comment]
@rbirkby could you try with this newer build for Linux to reproduce: https://az764295.vo.msecnd.net/exploration/ed422f909ea470f79e3e3e39c948803d9b764919/code-exploration-1.22.0-1522303929_amd64.tar.gz

**Comment by rbirkby** [comment]
The issue is on windows, not Linux.

**Comment by bpasero** [comment]
@rbirkby there you go: https://az764295.vo.msecnd.net/exploration/ed422f909ea470f79e3e3e39c948803d9b764919/VSCode-win32-x64-1.22.0-exploration.zip

**Comment by rbirkby** [comment]
The behaviour is the same as v1.21.0, which is different to the screenshots above. The behaviour is that on the 100% scaled monitor, I get very large tooltips:

![image](https://user-images.githubusercontent.com/203034/38138149-15670d78-3421-11e8-980f-440f552516ed.png)

and on the 200% hidpi scaled monitor, I get nicely readable tooltips that "feel" the correct size:

![image](https://user-images.githubusercontent.com/203034/38138236-a2fc16f6-3421-11e8-89fa-7ea2545f0e42.png)

However, when I change the scaling on the hidpi monitor from 200% to 100% I get the same size tooltips when all other UI elements have shrunk. ie the tooltips are drawn too large relative to all other UI elements and tooltips from other apps:

![image](https://user-images.githubusercontent.com/203034/38138181-605f6488-3421-11e8-9e16-0dfaa19a2921.png)

**Comment by mterrel** [comment]
+1
I see this on 1.25.0, Win 10 Pro 1803, on a Surface Book with the built-in display at 200% scaling and external display at 100%.

**Comment by vyachkonovalov** [comment]
The issue still exists
