### ISSUE TITLE
Terminal is in insert mode (breaking some tooling)

### ISSUE THREAD

**Issue by AechDub** [Microsoft/vscode#45425]
- VSCode Version: 1.21.0
- OS Version: Win 10

Steps to Reproduce:

1. Use intergrated terminal
2. Notice insert mode is stuck on and does not respect turning off
2. Using an prompted command, you'll see unreadable highlighting

Does this issue occur when all extensions are disabled?: Yes

![terminal-ps](https://user-images.githubusercontent.com/2582870/37221327-5e63063e-237e-11e8-832e-5a446996680f.jpg)
![terminal-bash](https://user-images.githubusercontent.com/2582870/37221328-5e791668-237e-11e8-9bb5-7c8192457a94.jpg)

**Comment by AechDub** [comment]
np is an npm tool.  Regardless, it's doing this for any prompted commands.  

Top is powershell; bottom is a bash window.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/41195
