### ISSUE TITLE
`ERR undefined` in console when editing a large file

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#45421]
- have large JSON file (130'000 lines)
- make an edit every second
- note that `ERR undefined`  is printed to the console.

If I get this right, this is caused by https://github.com/Microsoft/vscode/blob/f2abadb1ac284774e18cdf5e6fb6ba1950aa5934/src/vs/workbench/api/electron-browser/mainThreadSaveParticipant.ts#L271

The timeout expires, the promise is rejected and then logged in
https://github.com/Microsoft/vscode/blob/f2abadb1ac284774e18cdf5e6fb6ba1950aa5934/src/vs/workbench/api/electron-browser/mainThreadSaveParticipant.ts#L317

**Comment by jrieken** [comment]
@aeschli is this with format on save enabled or do you have any other save participant?

**Comment by aeschli** [comment]
formatOnSave is disabled in my settings. Maybe
https://github.com/Microsoft/vscode/blob/master/extensions/configuration-editing/src/extension.ts#L42
is the participant?

**Comment by jrieken** [comment]
@aeschli Can you check the extension host log? When it a will-save-participant we should log an error

**Comment by aeschli** [comment]
No message in the extension host log. 
From debugging I saw that it was the setTimeout(reject, 1750) as I was playing around with bit test data keeping the language server busy for a long time.

**Comment by jrieken** [comment]
This underlying problem is that the JSON formatter isn't returning with 750ms. I have expressed that more clearly in the error messages (for both format-on-save and the onWillSave-event). @aeschli You might want to make sure formatting is faster or tweak the `editor.formatOnSaveTimeout` setting for JSON files
