### ISSUE TITLE
Changes to file on disk MUST NOT be loaded without user confirmation

### ISSUE THREAD

**Issue by hgroene** [Microsoft/vscode#45420]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Outside VSCode, copy file A to file B
2. Open file B in VSCode, make changes and save (do not close file B buffer)
3. Change view to not file B buffer.
4. [Accidentally] repeat step 1
5. Change view back to file B buffer.
6. See how all your changes in buffer B are destroyed when VSCode silently reloads file B
7. Cry over all the work you just lost. :-(

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@hgroene to be clear, you saved a file in VS Code and then you overwrote the contents with a copy operation outside of VS Code and then you say you lost your changes? But you intentionally overwrote the file outside VS Code, no?

**Comment by hgroene** [comment]
I saved a file in VSCode and then unintentionally overwrote the file outside of VSCode. The file was still open in VSCode but the contents were replaced with changed file.
