### ISSUE TITLE
File closes on save when working via gvfs

### ISSUE THREAD

**Issue by squarerootfury** [Microsoft/vscode#4542]
- VSCode Version:  0.10.10 (git 5b5f4db87c10345b9d5c8d0bed745bcad4533135)
- OS Version:Ubuntu 15.10, gvfs 1.24.2 (the os is freshly installed)

I'm mounting another linux machine via `gvfs-mount` to edit files. After several saves, the file closes and I have to reopen it.  The file was opened in the "working files" area of the explorer tree. 

I don't see any disconnection of the mounted connection. `dmesg` has no messages.

Steps to Reproduce:
(On another Ubuntu 15.10 machine, I can reproduce the issue exactly)

1. Save the file several (about 5 or more) times ("force saving" aka hammering `CTRL+S` or the save menu does **not** reproduce this issue)

**Comment by bpasero** [comment]
@squarerootfury maybe there is a delete file event being sent for some reason. Can you run `code --verbose` and look at the output in the developer console for file events when this happens?

**Comment by squarerootfury** [comment]
VS Code prints following output to the console, seems to be nothing suspicous.
```
### VSCode main.js ###
/home/sqf/Downloads/VSCode-linux-x64/resources/app { pathArguments: [],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined,
  disablePlugins: false,
  locale: undefined }
Lifecycle#unload() 1
IPC#vscode-workbenchLoaded

```
And here is the developer console output, VS Code seems to throw a deletion event.

```
Service Library: Watcher] [CHANGED] /run/user/1000/gvfs/sftp:host=host.tld,user=srf/path.file
service.cp.ts:140[Service Library: Watcher]  >> normalized [CHANGED] /run/user/1000/gvfs/sftp:host=host.tld,user=srf/path.file
service.cp.ts:140[Service Library: Watcher] [DELETED] /run/user/1000/gvfs/sftp:host=host.tld,user=srf/path.file
service.cp.ts:140[Service Library: Watcher]  >> normalized [DELETED] /run/user/1000/gvfs/sftp:host=host.tld,user=srf/path.file
```

**Comment by bpasero** [comment]
@squarerootfury that is an interesting path, can you attach a screenshot how the explorer looks like?

**Comment by squarerootfury** [comment]
@bpasero sorry, I forgot that I had to censor the paths and filenames, because it contained the full fqdn.

**Comment by bpasero** [comment]
@squarerootfury sure. so there is a file delete event and so it is expected that vs code as a result, removes the file from the working files section and closes it because it thinks it was deleted. any idea who deletes this file? does it come back later?

**Comment by squarerootfury** [comment]
The file isn't really deleted, it exists the complete time. Do you think this could be more a gvfs related problem than a VS Code one?

**Comment by bpasero** [comment]
@squarerootfury well, it could be that or an issue with our file watching library. something makes the library think that the file is deleted. are you sure there are no further events when this happens?

One theory I have is maybe that the order of events is flipped: E.g. I see a change followed by a delete. Some editors (like Sublime) tend to first delete the file and then change it, and the library's job is to normalize those events to a simple change event.

**Comment by squarerootfury** [comment]
@bpasero I cleared the dev console to get a clearer ouput and reproduced the issue, it prints still the same steps that the change event is followed by the deleted event. What does `>> normalized` mean?

```
[Service Library: Watcher] [CHANGED] /run/user/1000/gvfs/sftp:host=host.tld,user=srf/file
service.cp.ts:140 [Service Library: Watcher]  >> normalized [CHANGED]  /run/user/1000/gvfs/sftp:host=host.tld,user=srf/file
service.cp.ts:140 [Service Library: Watcher] [DELETED]  /run/user/1000/gvfs/sftp:host=host.tld,user=srf/file
service.cp.ts:140 [Service Library: Watcher]  >> normalized [DELETED] / /run/user/1000/gvfs/sftp:host=host.tld,user=srf/file
```

**Comment by bpasero** [comment]
The normalized indicates what happens when multiple events for the same file occur. E.g. a delete followed by a change gets normalized to a change.

Can you show timestamps in the console so that we understand how large the timespan is between those events?

In our next release you are able to explicitly disable the file watcher on certain folders. This would certainly help here.

**Comment by squarerootfury** [comment]
Can I explicit display timestamps? Or do you mean an start+end timestamp?
> In our next release you are able to explicitly disable the file watcher on certain folders. This would certainly help here.
nice to hear!

**Comment by bpasero** [comment]
![screen shot 2016-03-22 at 14 58 36](https://cloud.githubusercontent.com/assets/900690/13953909/96a4a57c-f03e-11e5-9bae-cf6d1733a590.png)
![screen shot 2016-03-22 at 14 58 40](https://cloud.githubusercontent.com/assets/900690/13953910/96aad64a-f03e-11e5-999f-6be234fdf178.png)

Click the configure button in the console and then "Show Timestamps".

**Comment by squarerootfury** [comment]
Thanks, here is the log with timestamp: 

```
2016-03-22 15.17:20.947 service.cp.ts:140 [Service Library: Watcher] [CHANGED] /run/user/1000/gvfs/sftp:host=host.tld,user=srf/file
2016-03-22 15:17:20.989 service.cp.ts:140 [Service Library: Watcher]  >> normalized [CHANGED] /run/user/1000/gvfs/sftp:host=host.tld,user=srf/file
2016-03-22 15:17:21.042 service.cp.ts:140 [Service Library: Watcher] [DELETED] /run/user/1000/gvfs/sftp:host=host.tld,user=srf/file
2016-03-22 15:17:21.145 service.cp.ts:140 [Service Library: Watcher]  >> normalized [DELETED] /run/user/1000/gvfs/sftp:host=host.tld,user=srf/file
```

**Comment by bpasero** [comment]
@squarerootfury ok the events are close to each other but their ordering is weird, I suspect the correct order would be a delete and change instead of the other way around. What tool is causing these events? Or do they happen out of nowhere.

**Comment by squarerootfury** [comment]
I can trigger them with saving in VS Code

**Comment by bpasero** [comment]
@squarerootfury ok that is weird, so you say just saving the file from VS Code causes the delete and change event. Seems like maybe gvfs is doing something weird. If you want to give our new files.watcherExclude feature a try, you could try our insiders release: http://code.visualstudio.com/insiders

Note however that disabling file events might have other consequences, specifically changes to settings.json, task.json and launch.json within the .vscode folder of the workspace will not be reflected until restart. Maybe you could scope it down to the one folder that is connected via gvfs.

**Comment by squarerootfury** [comment]
I'm using VS Code only for some "basic" development for my php files, so I'm should be fine with this. I will test it and then I will provide feedback!

**Comment by bpasero** [comment]
Sounds good.

**Comment by squarerootfury** [comment]
The issue is still present, the developer console still shows  2 "Changed" followed by 2 "Deleted" events

**Comment by bpasero** [comment]
@squarerootfury how does you exclude setting look like?

**Comment by squarerootfury** [comment]
@bpasero see above.

**Comment by bpasero** [comment]
@squarerootfury did you restart after making the change?

**Comment by squarerootfury** [comment]
Yes, but I saw that the debug information changed. Now, the message comes from `workbench.main.js:29` instead of `service.cp.ts:140`.

**Comment by bpasero** [comment]
Sorry, out of ideas here. Excluding a path should stop file events. And it seems gfvs is doing something weird. Maybe the path that our watcher receives from this setup is different. You can disable all file events with **/**: true but that will cause quite a bad experience.

**Comment by squarerootfury** [comment]
Well, then I have to find a new way for mounting the servers, but good to know this isn't a problem with VS Code but rather one of gvfs.

Regardless that the issue is still present, thank your very much for your help and your time!

**Comment by dchw** [comment]
Something similar seems to be happening to me, but not using gvfs. I save a file, and suddenly all open files are closed. This is on Windows 7, Code version 0.10.11.

Here are the relevant logs from when it happened last. File paths edited for confidentiality.

`[File Watcher] [CHANGED] c:\Users\Some.User\src\project\tslint.json
csharpWatcherService.ts:76 [File Watcher]  >> normalized [CHANGED] c:\Users\Some.User\src\project\tslint.json
csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\project\.git\index.lock
csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\project\.git\index.lock
csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\project\.git\index
csharpWatcherService.ts:76 [File Watcher] [DELETED] c:\Users\Some.User\src\project\
csharpWatcherService.ts:76 [File Watcher]  >> normalized [DELETED] c:\Users\Some.User\src\project\
csharpWatcherService.ts:76 [File Watcher]  >> normalized [ADDED] c:\Users\Some.User\src\project\.git\index.lock
csharpWatcherService.ts:76 [File Watcher]  >> normalized [ADDED] c:\Users\Some.User\src\project\.git\index`

**Comment by squarerootfury** [comment]
@dchw  I never had the editor in Split view, so this may be a different issue with smiliar result.

**Comment by dchw** [comment]
@squarerootfury I also get it when working with a single document, it just seems to happen more when working with multiple documents. Definitely more often when performing the scenario I mentioned in my last post, but its still there when not in split mode.

**Comment by dchw** [comment]
@squarerootfury The more I think about it, the more I realized you are right. If this does seem to be a more general issue, then its worth filing a more general bug. I'll go do that.
