### ISSUE TITLE
Drop `preLaunchTask` in `launch.json` and `npm run compile` in `test`

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45431]
https://github.com/Microsoft/vscode/blob/master/extensions/html/.vscode/launch.json#L21
and
https://github.com/Microsoft/vscode/blob/master/extensions/html/server/package.json#L30

It does not make sense to run the compilation each time when you are debugging, as the normal development work flow should be
- run `npm run watch` as a task / terminal command
- make changes
- launch extension to see behavior or run unit tests

Having the compilation step adds 5-10s time to the last step which I want to do as frequently as possible. Same for `/extensions/css`.

**Comment by aeschli** [comment]
Instead of relaunching, why not reloading [Extension Development Host] window? That's much faster.
Removing the prelaunch task just increases the chances that old JavaScript is used, or that the JavaScript is missing or doesn't compile.

**Comment by octref** [comment]
The main problem was launching the compound debug of Client/Server often time out because it's waiting for the build.

I have changed compile script from `&&` to `&` to parallelize the compilation, so it's done faster.
```
gulp compile-extension:html-language-features-client & gulp compile-extension:html-language-features-server
```

So at the end it's just using tasks or running the commands manually. I prefer the latter so I guess I'll just remove the prelaunchtask during development and not commit it.
