### ISSUE TITLE
Poor rendering on Plasma 5.10 (kubuntu beta 18.04)

### ISSUE THREAD

**Issue by daniel-loader** [Microsoft/vscode#45439]
- VSCode Version:
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:01:43.521Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
Kubuntu 18.04 Beta 

Steps to Reproduce:

1. Install OS fresh
2. Install debian package for vscode

https://i.imgur.com/66XC5bJ.png

Does this issue occur when all extensions are disabled?: Yes

**Comment by nathan-osman** [comment]
I'm seeing this in Ubuntu (Gnome) 18.04 as well:

![screenshot from 2018-03-16 19-04-12](https://user-images.githubusercontent.com/1253444/37550606-4b90f37a-294d-11e8-8f6a-85c4ce90df97.png)

**Comment by daniel-loader** [comment]
That's handy to know I guess, might not be anything specific to kubuntu then. Guess we'll need to wait until ubuntu and derivatives go live for 18.04 soon.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35675
