### ISSUE TITLE
Code No longer disconnects from parent shell process when launched from shell

### ISSUE THREAD

**Issue by mwhitis** [Microsoft/vscode#45438]
Issue Type: <b>Bug</b>

When launching code from a shell ie: cmd.exe or powershell.exe, the code.exe process launches as a child of the shell process instead of launching as a fully independent process.   This behavior seems to have changed with the February updates.  Previously, when doing a 'code .' from a folder, code would launch in its own process.  Now, I am seeing code logging printed to my console window, and, any change to the console process (ie: ctrl+c or closing the shell) causes the code window to terminate.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.86GB (7.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|0.24.1
open-html-in-browser|cod|0.1.21
gitignore|cod|0.5.0
supersharp|cra|0.1.4
vscode-markdownlint|Dav|0.13.0
vscode-simpler-icons|dav|1.5.2
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
xml|Dot|1.9.2
vscode-generate-getter-setter|DSK|0.4.2
gitlens|eam|8.1.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.28
vsc-material-theme|Equ|1.5.0
git-project-manager|fel|1.4.0
scaffold|fir|1.0.0
auto-rename-tag|for|0.0.15
code-runner|for|0.9.1
beautify|Hoo|1.3.0
path-autocomplete|ion|1.8.1
csharpextensions|jch|1.3.0
sharppad|jma|1.0.5
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|0.3.1
vscodeilviewer|jos|0.0.1
docomment|k--|0.0.17
csharpfixformat|Leo|0.0.64
MagicPython|mag|1.0.12
rainbow-csv|mec|0.2.0
mssql|ms-|1.3.0
python|ms-|2018.2.1
azurecli|ms-|0.4.0
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
node-debug2|ms-|1.19.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.1.0
printcode|nob|2.0.4
vetur|oct|0.11.7
open-html-in-browser|pea|0.0.3
material-icon-theme|PKi|3.2.3
Csharp-ASPNETCore|rah|1.0.5
classynaming|ref|1.1.1
vscode-icons|rob|7.20.0
aspnet-helper|sch|0.6.4
code-settings-sync|Sha|2.9.0
open-in-browser|tec|1.1.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2
html-css-class-completion|Zig|1.17.1
vscode-open-in-github|ziy|1.3.1

(12 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by mwhitis** [comment]
Example output in my cmd.exe window:
<img width="671" alt="example code output" src="https://user-images.githubusercontent.com/549271/37228120-8031d7ca-23ad-11e8-8404-d90419c89cda.png">

Process Explorer showing code still attached:
<img width="553" alt="example code still attached to cmd exe" src="https://user-images.githubusercontent.com/549271/37228122-8305c8c6-23ad-11e8-9521-52c135518bb0.png">

**Comment by mwhitis** [comment]
joao, path variable below from the session that generated the pasted text:

`Path=c:\tools\cmder
c:\tools\
C:\Program Files\Microsoft VS Code
C:\Program Files\Sublime Text 3
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin
C:\Python36\Scripts\
C:\Python36\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\Git\cmd
C:\Program Files\dotnet\
C:\Program Files\Java\jdk1.8.0_144\bin
C:\ProgramData\Oracle\Java\javapath
C:\Program Files (x86)\HID Global\ActivClient\
C:\Program Files\HID Global\ActivClient\
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\tools\apache-maven-3.5.0\bin
C:\Program Files\PuTTY\
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\Intel\WiFi\bin\
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\Program Files\Common Files\Intel\WirelessCommon\
C:\Program Files\Microsoft SQL Server\140\Tools\Binn\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\tools\instantclient_12_2
C:\Program Files\nodejs\
c:\tools
c:\tools\de4dot
C:\Users\210062539\AppData\Roaming\npm
C:\Program Files\Microsoft VS Code\bin`

**Comment by joaomoreno** [comment]
Can you remove `C:\Program Files\Microsoft VS Code` from it? The right one is `C:\Program Files\Microsoft VS Code\bin`, which you have further down.

**Comment by mwhitis** [comment]
Awesome, that fixed it!  Appreciate the assist.
