### ISSUE TITLE
Is darwinBundleDocumentTypes is out of date?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4543]
I noticed the `config` variable in https://github.com/Microsoft/vscode/pull/4483, there are some built-in extensions that contributes file extensions but aren't added here. Not sure exactly what this drives, but maybe it should be generated automatically?

**Comment by joaomoreno** [comment]
We can't have it dynamically, unfortunately. The user can always associate it himself though.

**Comment by joaomoreno** [comment]
We can't have it dynamically, unfortunately. The user can always associate it himself though.

**Comment by Tyriar** [comment]
@joaomoreno it's used as part of the build though, can't the file extensions be fetched from `./extensions/*/package.json`?

I'm still not entirely sure what the value does though.

**Comment by joaomoreno** [comment]
They can actually, but we can't make it update as you (un)install extension.
