### ISSUE TITLE
Don't show hint diagnostics in problems view?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#45436]
**Problem**
TypeScript is introducing new "suggest" diagnostics (#45378 + #45433) that seem to map to our `DiagnosticServerity.Hint` level. Example suggest diagnostic: convert a es5 class to an es6 class.

However these hint diagnostics still are still show in the problems view, which adds a lot of noise

<img width="574" alt="screen shot 2018-03-09 at 12 13 16 pm" src="https://user-images.githubusercontent.com/12821956/37227792-4c2a1f92-2393-11e8-917d-bc0018a70370.png">

**Proposal**
Don't show hint diagnostics in the problems panel. They are already not shown in the editor. Not sure if any extensions depend on the current functionality

**Comment by mjbvz** [comment]
If we are concerned about regressing extensions, two other options:

* Introduce a new, even lower severity diagnostic level that never shows in the UI

* Allow diagnostics or diagnostics collection themselves to say if they show in the UI or not

**Comment by sandy081** [comment]
@jrieken Since, we are planning to move F8 functionality being driven from editor to problems view, does it mean that F8 now will also navigate through all types of diagnostics?

How about adding a setting to exclude diagnostics by type which can be language overridden?

**Comment by jrieken** [comment]
We should always ignore `Hint` (the editor already does that today), the F8 likely doesn't...

**Comment by mjbvz** [comment]
We can discuss this at the UX sync but I think a good experience would be:

* By default, TS suggestion diagnostics such as `convert a es5 class to an es6 class` show as faint gray underlines in the editor. This would let users know where they can perform code actions. These diagnostics would not show in the problems view or participate in F8

* We provide an option this hide these suggestion diagnostics in the editor as well. TS is looking into per-error suppressions but I think we need global solution on the VS Code side as well

Not sure how these would map to our diagnostic severities

**Comment by jrieken** [comment]
This is somewhat the same as https://github.com/Microsoft/vscode/issues/44141
