### ISSUE TITLE
"Find in selection" does not function as expected

### ISSUE THREAD

**Issue by agm1984** [microsoft/vscode#45445]
- VSCode Version: 1.20.1
- OS Version: Win 10 Pro

Steps to Reproduce:

1. Open VS Code
2. Open a file with lots of HTML markup
3. Actually, here is some code you can use:
``` html
<div id="<?php echo 'tss_id'.$id; ?>" class="owl-carousel"  style='text-align:center;'>

  <?php

    $args = array (
      'post_type'      => 'tss_data',
      'category_name'  => get_post_meta( $id,'mpsp_posts_value', true ),
      'posts_per_page' => get_post_meta( $id,'mpsp_posts_visible', true ),
      'order'          => get_post_meta( $id,'mpsp_posts_order', true ),
      'orderby'        => get_post_meta( $id,'mpsp_posts_orderby', true ),
    );

    // The Query
    $the_query = new WP_Query( $args );

    while( $the_query->have_posts() ): $the_query->the_post(); ?>

    <div id='tss_wrapper'>
      <div id='tss_content'>
        <p class='tss_p' id='tss_testimonial'><?php echo get_post_meta(get_the_ID(),'tss_testimonial',true);  ?></p>
      </div>
      <div id='ts_img'>
        <p class='tss_p' id='tss_name'><?php echo get_post_meta(get_the_ID(),'tss_name',true);  ?></p>
        <p class='tss_p' id='tss_occupation'><?php echo get_post_meta(get_the_ID(),'tss_ocupation',true);  ?></p>
        </div>
    </div>

    <?php endwhile;?>
  </div>
</div>
```
4. Highlight the `'` characters  from `tss_wrapper` to `tss_testimonial`
5. Press CTRL + F
6. Press **Find in selection**
7. Observe how it highlights matches from outside the selected area

**Actual results:** Matches are found and highlighted outside the selection because they are on the same line as some of the selected area.

**Expected results:** Matches should only be found inside the selected area, hence "find in selection".

**Please continue reading:** there is one additional problem that is related.

8. Now that you have selected text, like this:
![vscode1](https://user-images.githubusercontent.com/17655219/37231554-67beea1e-23a0-11e8-816a-878cddd582e5.png)

9. Press Find in selection again

**Actual results:** Every matching result in the entire file is selected.

**Expected results:** I expect matches inside the selected area to be highlighted.

With VS Code acting this way, it is faster to manually replace because Find in selection is too unpredictable and causes time waste.

Here is a GIF of the first issue:
![find-in-selection1](https://user-images.githubusercontent.com/17655219/37231825-7d072d2c-23a1-11e8-85f7-855ea6a1e758.gif)

Here is a GIF of the second issue:
![find-in-selection2](https://user-images.githubusercontent.com/17655219/37231852-8c379052-23a1-11e8-8cc7-120eb6482bbd.gif)

**Optimal solution:** I would like VS Code to highlight matches inside the selected area when I press "Find in selection" in both cases that I have demonstrated.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ThubLives** [comment]
I run into this problem constantly.  "Find in selection" behaves poorly at the best of times, but single character searches are practically impossible in combination with this option.

To make multi-character searches work, you must start with the (rather hard to visually determine) option turned off, then highlight the file region, then turn it back on either with the button or the keyboard shortcut.  If you have a region highlighted and search text entered when you turn the feature off, your region selection will be changed in often unpredictable ways.

Single-character searches are basically impossible, making converting between single- and double-quotes, as well as Find-and-Replace raves a bit of a nightmare.

```
\o\  \o\  \o\   <---- y u no wave my arms???
 |    |    |
/ \  / \  / \

 ^----^----^--- Bummed out, motionless ravers
```

**Comment by mblandfo** [comment]
I think the steps listed above work now.

1. highlight a region
2. cmd+f
3. click "find in selection" (works)

But there is still a problem here: 

1. highlight a region
2. cmd+f
3. type something to find
4. now my selection is gone and I may have been jumped around in the file, so clicking "find in selection" at this point doesn't work

Ideally, if I have a region selected and I hit cmd+f, it should have "find in selection" turned on automatically. I'd be fine with this as a user setting.

Also, it's really hard to see if find in selection is turned on or not in the Dark (Visual Studio) theme.


VS Code 1.25.1
OS X 10.11.6

**Comment by ThubLives** [comment]
I agree that the Dark (Visual Studio) theme makes it frustratingly hard to discern the state of the button.  I don't know how many times I've lost my selection while I was guessing at the current state and twiddled the button.

Also, I think this behaviour as a default would Do The Right Thing(TM) in the majority of cases:  When find is activated (e.g. Ctrl+F), if current selection spans more than one line (i.e. selection includes one or more CRLF/LF), then automatically enable "find in selection".  Otherwise, use normal behaviour to put the current selection into the Find field.

This way, I can select one entire line (Shift + Down Arrow) and it will assume I want to search within this one line.  If I select a word, it will assume I want to search for other instances of that word.

Of course, a tri-state user setting will definitely be welcome to force the behaviour to the classic behaviour, always using "find in selection" if there is any text selected, or the automatic behaviour.

**Comment by agm1984** [comment]
I feel like it works better now than when I posted this originally, but it still acts weird. Here is another sample:

![find1](https://user-images.githubusercontent.com/17655219/43545818-c0311c46-958b-11e8-8350-169df38c6901.gif)

Steps to reproduce:
1. Press `CTRL+F` to open the search thing
2. Highlight an area
3. Type something into the find input

Actual results: selected area is dropped

Expected results: inputted search should be highlighted in the selected area

Here is another unexpected behaviour:

![find2](https://user-images.githubusercontent.com/17655219/43546120-a3b43318-958c-11e8-9ce9-39b6280f607d.gif)

Steps to reproduce:
1. Press `CTRL+F` to open the search thing
2. Input a find and a replace value
3. Highlight an area
4. Press Find in Selection
5. Highlight a different area
6. Press Find in Selection again

Actual results: all matches in file are selected

Expected results: only matches in the newly highlighted area should be highlighted

**Comment by rebornix** [comment]
The last use case described above is actually allowing to change the search scope while searching, which is not supported now.

**Comment by rebornix** [comment]
let's track this in https://github.com/microsoft/vscode/issues/95356.
