### ISSUE TITLE
VS Code does not recognize the currently active .net run-time.

### ISSUE THREAD

**Issue by brentarias** [Microsoft/vscode#4544]
When I use the VSCode command palette `dnx: run command` to execute my .NET Core C# console app, I'm given the error:

>current runtime target framework is not compatible.  
>Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'

This error is non-sensical, because I have the correct version selected globally.  I noticed a [Stackoverflow post where somebody else is experiencing the same problem](http://stackoverflow.com/questions/34708489/system-invalidoperationexception-the-current-runtime-target-framework-is-not-co).

- VSCode Version: 0.10.11
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Open new cmd prompt, and change to folder where I have a .NET Core C# console app.
2. Execute `dnvm list` to confirm that `1.0.0-rc1-update1 coreclr x86` is selected globally.
3. From the same cmd prompt, launch `code .`
4. Use the VSCode command palette to execute `dnx run`

At this point an error is produced, as already described.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#117
