### ISSUE TITLE
vscode with ai tools does not work

### ISSUE THREAD

**Issue by azeltov** [Microsoft/vscode#45449]
Issue Type: <b>Bug</b>

when i try to open the AI ML Sample Pallete i get this error: “command 'vscodeai.openGallery' not found” 

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (6.11GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
python|ms-|2018.2.1
vscode-ai|ms-|0.1.7
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.2.0

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
This is an issue with the extension. Please file the issue [here](https://github.com/Microsoft/vscode-tools-for-ai/issues/new). Thanks!
