### ISSUE TITLE
corrupted PHP Highlighting

### ISSUE THREAD

**Issue by JohnMagdy** [Microsoft/vscode#45441]
Issue Type: <b>Bug</b>

Hello sir, so iam facing some problems with the PHP Highlighting after upgrading to the latest VSCODE Version... 

most of the functions,... doesn't have any kind of hightlights (echo, isset, strcmp,....)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|2.64GB (1.07GB free)|
|Process Argv|D:\Proggrames\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
xml|Dot|1.9.2
apacheconf-snippets|eim|1.1.9
php-debug|fel|1.12.1
node-module-intellisense|lei|1.5.0
vscode-apache|mrm|1.1.1
material-icon-theme|PKi|3.2.3

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Can you include a code sample that reproduces the issue and a screenshot?

**Comment by JohnMagdy** [comment]
![sc1](https://user-images.githubusercontent.com/19735243/37677670-5fbf01cc-2c84-11e8-8223-a245382d55d5.JPG)
![sc2](https://user-images.githubusercontent.com/19735243/37677717-8023f38c-2c84-11e8-9b2d-e0143061dbad.JPG)

`	if($query->isOnline())
	{
       if(isset($aInformation['hostname'])) 
	   {
		  if(strcmp($configuration->general->servername, $aInformation['hostname']))
		  {
			 $configuration->general->servername = $aInformation['hostname'];
		  }
	   }
      }`

**Comment by JohnMagdy** [comment]
Theme: Linux Themes for VS Code (Installion Code: code --install-extension solarliner.linux-themes)
PHP File: sorry, do you have an email or smilliar things which i might send you the file through it as itsn't open source code and i couldn't share it in Public (Github)....

**Comment by roblourens** [comment]
You can send it to the email in my profile, or come up with a simpler sample that shows the issue.

**Comment by JohnMagdy** [comment]
its sent to you sir...

**Comment by roblourens** [comment]
It looks fine to me using the United Ubuntu theme. What problem specifically are you seeing?

**Comment by JohnMagdy** [comment]
sorry for late, i have changed my theme from 'Linux Themes for VS Code' Theme to 'Ubuntu Style' Theme but its the same as before nothing changed.... :(
