### ISSUE TITLE
Doesn't stop on breakpoints

### ISSUE THREAD

**Issue by manu-st** [Microsoft/vscode#45448]
Issue Type: <b>Bug</b>

Set a breakpoint and run. It does not stop anymore. I believe 1.20 and earlier worked, but not in 1.21.
This happens when running a test suite via jest is against code using TypeScript (v2.7.2) and using `ts-jest` (v21.2.4).

We use the following setting to start the app:
```
{
         "name": "Debug Tests",
         "type": "node",
         "request": "launch",
         "program": "${workspaceRoot}/node_modules/jest-cli/bin/jest.js",
         "stopOnEntry": false,
         "args": ["--runInBand", "--verbose", "--config=${workspaceRoot}/testing/jest.config.js", "Font"],
         "cwd": "${workspaceRoot}",
         "preLaunchTask": null,
         "runtimeExecutable": null,
         "runtimeArgs": [ "--nolazy" ],
         "console": "integratedTerminal",
         "sourceMaps": true,
         "smartStep": true
      },
```

When it starts it shows the following:
```
Debugger listening on ws://127.0.0.1:47917/38f2a3d9-1d82-493c-8582-589610f9ee52
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
```

As soon as I change `sourceMaps` to false, then it works but it is not perfect as when it stops I do not get the yellow arrow telling me on which breakpoint it actually stopped and the step by step or step into functionality do not work at all or partially.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|

|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by feafarot** [comment]
I have the same issue using sourcemaps and ts-node

**Comment by rcjsuen** [comment]
I've been having the same problem with TypeScript Mocha tests on Windows 10. It's very annoying.

**Comment by achawla5000** [comment]
#45351

**Comment by roblourens** [comment]
Can one of you share your project or some sample code?

Or, please set `"trace": true` in the launch config, reproduce the issue, and upload the log here.

**Comment by rcjsuen** [comment]
@roblourens I've attached my [debugadapter.txt](https://github.com/Microsoft/vscode/files/1802800/debugadapter.txt). Hope it helps.

**Comment by deepred5** [comment]
@jugglingthebits I meet the problem with ts-node too when updating to 1.21.

**Comment by taosdc** [comment]
add property to launch.json, should fix it.
"outFiles": ["${workspaceFolder}/**/*.js"]

**Comment by rcjsuen** [comment]
@taosdc I can confirm that that fixed the problem for me. Thank you so much!

**Comment by roblourens** [comment]
This is probably https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464, please see the comment there and try in the next Insiders build.

**Comment by rceballosdf** [comment]
Hi everybody, Im having the same problem with ts using the VS code from version 1.19 to 1.21.1
