### ISSUE TITLE
"Close unmodified editors" is gone in latest update

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#45440]
- VSCode Version: 1.21.0
- OS Version: macOS 10.13.3

The command `View: Close unmodified editors` was added in a recent version. In 1.21, this very useful command is gone entirely.

![screen shot 2018-03-09 at 15 27 10](https://user-images.githubusercontent.com/50314/37228380-6f3f04fa-23ae-11e8-887a-75230570a78e.jpg)

Does this issue occur when all extensions are disabled?: N/A

**Comment by bpasero** [comment]
@atombender it was renamed to "Close Saved Editors"
