### ISSUE TITLE
Terminal flashes when scrolling up on vim if its already on first line.

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#45452]
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T10:54:22.798Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Open a simple file with vim. 
2. Scroll to the end. Works fine
3. Scroll to the top. Keep on moving mouse wheel or touchpad to go up.
4. Seems terminal scrolls up and then down in janky motion. 

Expected: Scrolling should be smooth.

See [vscode-scrolling.zip](https://github.com/Microsoft/vscode/files/1798976/vscode-scrolling.zip) for video.

Does this issue occur when all extensions are disabled?: Yes

Fix should be that if terminal is in an alternate screen-buffer then it should only send up/down arrow commands. It shouldn't use native scrolling.

**Comment by Tyriar** [comment]
I noticed this recently as well, for some reason the scrollback buffer isn't going away when we enter the alt buffer. When I repro'd last I saw that it happened inconsistently. Created https://github.com/xtermjs/xterm.js/issues/1349

**Comment by Tyriar** [comment]
I haven't seen this for a while.
