### ISSUE TITLE
VSCode terminal does not send mouse commands for hover

### ISSUE THREAD

**Issue by nojvek** [microsoft/vscode#45454]
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T10:54:22.798Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. `git clone git@github.com:cronvel/terminal-kit.git`
2. Run `node ~/git/terminal-kit/sample/mouse-test.js` inside vscode terminal.

![image](https://user-images.githubusercontent.com/1018196/37237203-63966244-23c5-11e8-92df-a77044a1c6b3.png)

3. Mouse move should fire but it doesn't.
4. Expected: Mouse MOTION escape codes are sent regardless of whether mouse is pressed or not. This enables to build a great mouse experiences inside terminal apps.

In every developer's career, there comes a time when they need to build their own editor. This may seem like crazy, but I am scratching an itch to build a vscode like editor as a pure terminal app with great mouse and code completion support. Basically vim for 21st century. Since most vscode extensions are faceless and use language server and debugger protocol, it would be super cool to have a great editing/debugging experience without firing up electron. You can ssh into a server and use vscode in cli mode. Now wouldn't that be amazing?

**Comment by Tyriar** [comment]
@nojvek sorry about the response delay, I've had so many incoming notifications recently. This is being tracked upstream in https://github.com/xtermjs/xterm.js/issues/1062 and is marked as help wanted, we wouldn't even need a setting as it looks like it's an escape sequence switch. I won't have time to work on it but this would be a very value external contribution to have in xterm.js.

Also you may be underestimating the amount of effort it takes to create a text editor, it is certainly fun though 😄

**Comment by nojvek** [comment]
@Tyriar , may take a stab at it sometime. 

For the editor part, `all ideas have to start somewhere` 🕺

**Comment by nojvek** [comment]
Hey sorry. I’ve been on vacation. Haven’t had a chance to look at it yet.

**Comment by ddruker** [comment]
@nojvek No problem! Ok if I jump on it?

**Comment by ddruker** [comment]
@nojvek Im about to tackle another issue. If you feel that you can't get to this in the next week or so, I'm happy to jump in. 😄

**Comment by nojvek** [comment]
Feel free to grab it. I have plenty on my plate.

**Comment by Tyriar** [comment]
Let's track this in the upstream repo
