### ISSUE TITLE
Javascript Formatter mistakes < in Flow's Generics for a Binary Operator

### ISSUE THREAD

**Issue by cjduncana** [Microsoft/vscode#45450]
- ESLint Version: 1.4.7
- VSCode Version: 1.20.1
- OS Version: 10.11.6

# Steps to Reproduce:

1. Enable the following setting: `javascript.format.insertSpaceBeforeAndAfterBinaryOperators`
2. Write the following code:
```js
// @flow

const middle: number = 5;

export function range(beggining: number): number => Array<number> {
  return function _range(end: number): Array<number> {
    return [beggining, middle, end];
  };
}
```
3. Format document.

## Expected

The code in the page to stay the same.

## Actual

```js
// @flow

const middle: number = 5;

export function range(beggining: number): number => Array < number > {
  return function _range(end: number): Array<number> {
    return [beggining, middle, end];
  };
}
```

Notice how the formatter changed the Generic in line 5. Eventhough the type is identical to the one in line 6, the formatter treats it differently.

By flipping the setting, that problem is solved, but another one emerges:

```js
// @flow

const middle: number=5;

export function range(beggining: number): number => Array<number> {
  return function _range(end: number): Array<number> {
    return [beggining, middle, end];
  };
}
```

The equal sign in line 3 has the surrounding spaces removed, so flipping the setting is not a desired solution.

**Comment by cjduncana** [comment]
This issue is copied from Microsoft/vscode-eslint#419.

**Comment by mjbvz** [comment]
Our built-in js formatter doesn't support flow syntax. Please disable the built-in js formatter (`javascript.format.enable": false`) and install a flow formatter from the marketplace
