### ISSUE TITLE
Update the jsconfig.json schema descriptions

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4545]
![image](https://cloud.githubusercontent.com/assets/172399/13945230/ec5e3b0a-f00b-11e5-853c-676856fed4d5.png)

Remove
- locale (VS only currently)
- diagnostics (only for down-level compiling)
- maproot (only used for down-level compiling, and if we add maproot then we would have to add sourceMap, inlineSourceMap, etc)

**Comment by aeschli** [comment]
duplicate of #4554
