### ISSUE TITLE
Total commander like multi file replacement - feature request

### ISSUE THREAD

**Issue by fssrepository** [Microsoft/vscode#45456]
Info:
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:31:21.019Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

We can search in two ways for all occurrences:
1, click on main search icon, and search
2, find all occurences

The second option is not that convenient. The popup to edit something is nice and fancy, but it's opening all the files at some point without saving the modification, so you are not sure, what you have modified.

I think, when you change something and click on the next occurrence in a different file, you need to force some save before!

Many times i'm using the first option instead, but what i'm missing is a new text field where you can add replacement similarly how it's working for one file. (There is a place for it, and a big refactor it would be nice and handy)

1, search first
2, add the replacement and click on replace all, or separately jumping to the next file

**Comment by roblourens** [comment]
I don't quite understand. What do you mean by "find all occurences"?

>  but what i'm missing is a new text field where you can add replacement similarly how it's working for one file. 

You can do a find/replace in the text search viewlet

![image](https://user-images.githubusercontent.com/323878/37266957-d074e51e-257a-11e8-9f31-2d721c58e96e.png)

Is that not what you're talking about? It would be helpful if you can include screenshots or more clear steps on what you want to happne.

**Comment by fssrepository** [comment]
Somehow it was not there when i looked at, now it seems me available, o r i just missed it. Thanks.
