### ISSUE TITLE
tab glyph overwraps next character for editor.renderWhitespace

### ISSUE THREAD

**Issue by yh1224** [Microsoft/vscode#45457]
- VSCode Version: 1.21.0
- OS Version: Windows 10

Steps to Reproduce:

1. Enable editor.renderWhitespace
2. Use Japanese font
2. Place tab just before tab stop

![2018-03-10_12h32_53](https://user-images.githubusercontent.com/457327/37237986-bb977344-245f-11e8-8a96-acea8f269f61.png)

**Comment by yh1224** [comment]
Because current tab glyph "→" 'RIGHTWARDS ARROW' (U+2192) is full width in east asian.
Better to use "￫" 'HALFWIDTH RIGHTWARDS ARROW' (U+FFEB).

**Comment by rebornix** [comment]
I'm a noob on fonts, not sure how that will affect non-fixed-width fonts and our existing behavior. @be5invis any suggestion?

**Comment by be5invis** [comment]
In many fonts (mainly CJK) the advance width of arrow would be larger than one space.
In the other hand most of the Latin mono fonts does not have U+FFEB, so simply switching to FFEB is not a good idea.
cc. @ken_lunde

**Comment by yh1224** [comment]
@be5invis Thanks for review.
I think it might be better to draw tab visually instead of using some alternative character.

**Comment by alexandrudima** [comment]
After:
![image](https://user-images.githubusercontent.com/5047891/39534487-f66a62d2-4e31-11e8-8c2d-3aa85013c4a1.png)
