### ISSUE TITLE
Add "find all reassignments/mutations" feature

### ISSUE THREAD

**Issue by Zzzen** [microsoft/vscode#45464]
"find all references" is good, but I only care about reassignments/mutations to a property sometimes.

**Comment by jrieken** [comment]
closing as dupe of #74237

**Comment by sean-mcmanus** [comment]
For C/C++ we're tracking this with https://github.com/microsoft/vscode-cpptools/issues/4043 .

It's not really a "type" of reference, but an additional property/column that only applies to variable references, so I don't think https://github.com/microsoft/vscode/issues/74237 is really the same issue, i.e. in VS, the "type" and Read/Write are separate.
