### ISSUE TITLE
Ubuntu: Updater downloads TGZ instead of DEB package

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode#45465]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 17.10

**Steps to Reproduce:**

1. Help -> Check for Updates
2. Open the Settings icon in the left bottom corner
3. Download the new version (1.21)

**Expected result:**

- DEB package is downloaded

**Actual result:**

- TGZ package is downloaded (code-stable-code_1.21.0-1520420608_amd64.tar.gz)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43671
