### ISSUE TITLE
Limit shell history to the current project

### ISSUE THREAD

**Issue by cg-cnu** [Microsoft/vscode#45460]
Amazing work vscode team! 💯 👏 

Is there a way we can store the shell history for each project separately ? I mean, pressing the up arrow or `ctrl+r` search should be limited to **only the commands I used in current project**. It would a huge time saver, if my shell history is limited to just that project. I can run few commands on a project and after reopening it later I still have access to just those commands instead of me browsing through my entire shell history. Will be helpful in debugging as well.

Thanks for your awesome work! 😄

**Comment by Tyriar** [comment]
Shell history is 100% handled by the shell right now (eg. bash, tmux, powershell). You may be able to do this by tweaking arguments passed to the shell using the `terminal.integrated.<platform>.shellArgs` setting if it's supported but no plans to integrate sort of thing into the core.
