### ISSUE TITLE
[loc] Request to add Slovak language to VS Code

### ISSUE THREAD

**Issue by mlajtos** [Microsoft/vscode#45463]
There needs to be at least 3 language contributors.
Please vote by adding your Transifex account name here.

**Comment by kieferrm** [comment]
@mlajtos We have support for language packs now. See for example [Bulgarian](https://marketplace.visualstudio.com/search?term=bulgarian&target=VSCode&category=All%20categories&sortBy=Relevance).

Thus, I suspect you are looking for volunteers to work with you on a Slovakian language pack? 

I leave this issue open for now.

**Comment by mlajtos** [comment]
I read somewhere that I need to file an issue so the language can be added to the Transifex. That's why I opened this issue. Volunteers would be nice, but I can translate it myself.

So if I want to create a localization, I don't need to go through Transifex? Can I translate offline/locally?

**Comment by kieferrm** [comment]
You don't necessarily need a transifex project. It makes it easier for you to find people with the right language skills and it makes it easier for us to assess the quality of the translation without having the right language skills in the team. 

Run `npm install -g yo generator-code` to install yeoman and our yeoman extension.
Then run `yo code` and select 'language pack'. This generates the scaffolding for a new translation and the getting-started guide tells you how it works.

**Comment by mlajtos** [comment]
@kieferrm , thank you :)
