### ISSUE TITLE
Cannot submit changed files when CRLF to LF

### ISSUE THREAD

**Issue by MaleDong** [Microsoft/vscode#45469]
Issue Type: <b>Bug</b>

1) Create a file with a default format of CRLF in Windows, and submit this file to GitHub.
2) Sync the project of Git with your local one.
3) Double click to open the file, switch from CRLF to LF.
4) There you will see the changed list.
5) But when you click "Save all temporaily changed files" in Git Source Code Manager window, nothing is submitted. This means that for the next time, it always "CRLF" even if I set "files.eol = LF".

For simple steps, please refer the video below.
[45469.zip](https://github.com/Microsoft/vscode/files/1799281/45469.zip)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|Memory (System)|3.15GB (1.16GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.1.0
vscode-icons|rob|7.20.0

</details>

**Comment by joaomoreno** [comment]
Nevermind, saw the video. This is how git behaves.

https://help.github.com/articles/dealing-with-line-endings/
