### ISSUE TITLE
Smiley face not working.

### ISSUE THREAD

**Issue by MasonTang** [Microsoft/vscode#45462]
### Issue Type
Bug

### Description

When I hit save. It sometimes has the green smiley face but sometimes it does not. I created a new folder and it no longer has the smiley face.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.90GB (2.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sublime-keybindings|ms-|3.0.3
LiveServer|rit|3.2.1

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
@MasonTang can you share a screenshot of what green smily you mean?
