### ISSUE TITLE
Explorer: rename box focus off on the left hand side

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45468]
See:

![image](https://user-images.githubusercontent.com/900690/37240769-2f564a5e-2450-11e8-859f-7bc18612763e.png)

**Comment by isidorn** [comment]
Repro steps would be great.
Currently on blur I close the thing 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L323

**Comment by bpasero** [comment]
@isidorn 
* select a file
* press Enter (macOS)

**Comment by isidorn** [comment]
@bpasero does not repro for me.
Can you do some setInterval with printing out of focus
And put a console log here to check if the input box got the focus https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L286

I can also drop by your machine to investigate

**Comment by isidorn** [comment]
@bpasero not always, I am also selfhosting on latest electron and I can not reproduce.

**Comment by bpasero** [comment]
@isidorn oke

**Comment by isidorn** [comment]
@bpasero however I can always repro the following
Rename a symbol in explorer -> focus not in the input box

**Comment by bpasero** [comment]
@isidorn great catch 👍

**Comment by bpasero** [comment]
I am no longer seeing this even on the 2.x branch. Weird...

**Comment by isidorn** [comment]
@bpasero ok but note that with latest electron 2.0 out of source I still see the rename in editor issue I mentioned above.

**Comment by bpasero** [comment]
@isidorn I just pushed a fix for that

**Comment by isidorn** [comment]
@bpasero thanks
