### ISSUE TITLE
lots of suspicous wmic process after upgrading to 1.21

### ISSUE THREAD

**Issue by yingang** [Microsoft/vscode#45461]
Issue Type: <b>Bug</b>

I upgraded the vscode to 1.21 yesterday, then my laptop would start to respond slower and slower when vscode is ruuning. By checking task manager, I found that there are lots of wmic process like: wmic process 7416 get workingsetsize,usermodetime,kernelmodetime, in which the PID 7416 points to a python process: python completion.py.

After disable the python extension and restart the vscode, the problem won't happen again.

The Python extension (ms-python.python) I was using was released 2018.2.1, so I think it's a problem between the latest 1.21 release with the extension?

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|11.83GB (6.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0
team|ms-|1.122.0

</details>
Reproduces only with extensions

**Comment by yingang** [comment]
looks like there is already a similar issue reported in #44428

**Comment by kieferrm** [comment]
@yingang  do you have any node launch config that uses `"autoAttachChildProcesses": true`?  If not pls move this issue to the Python extension.

**Comment by zsquareplusc** [comment]
I see this here too, a WMI process launched every 5 seconds or so looking at the Python process.

In earlier versions I've seen the python process grow to 1.6GB RAM, this time is staying small at about 55MB but that new process periodically launching instead is not nice.

I just edit a few python files, txt and rst, no node or browser related debugging (no such extensions are installed, only python and c++)

**Comment by kieferrm** [comment]
Pls file the issue against the python extension [here](https://github.com/Microsoft/vscode-python/issues/new).
