### ISSUE TITLE
namiqnebiyev

### ISSUE THREAD

**Issue by namiqnebiyev** [Microsoft/vscode#45478]
@Issue Type: <b>Feature Request</b>

about

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by shobhitchittora** [comment]
Empty issue. Close this.

**Comment by namiqnebiyev** [comment]
about
