### ISSUE TITLE
Running Code On WSL Bash

### ISSUE THREAD

**Issue by AakashSasikumar** [Microsoft/vscode#45475]
Usually, when you wanna run a program, you would right click and choose run on terminal. This feature only works on powershell. Since bash (linux subsystems) are supported in Windows, it would be nice to have the run file in terminal button working on the bash shell as well.

**Comment by Tyriar** [comment]
@AakashSasikumar do you mean launching as in by right clicking in Windows Explorer and opening a terminal to run code.exe in it?

Related: https://github.com/Microsoft/vscode/issues/13138
