### ISSUE TITLE
namiqnebiyev

### ISSUE THREAD

**Issue by namiqnebiyev** [Microsoft/vscode#45477]
Issue Type: <b>Bug</b>

about

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5200  @ 2.50GHz (2 x 2499)|
|Memory (System)|1.94GB (0.44GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
team|ms-|1.122.0

</details>
Reproduces only with extensions

**Comment by shobhitchittora** [comment]
Empty issue. Close this.
