### ISSUE TITLE
"Debug adapter process has terminated unexpectedly"

### ISSUE THREAD

**Issue by Geilson76** [Microsoft/vscode#45472]
Issue Type: <b>Bug</b>

After new update, debug is broken.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E8500  @ 3.16GHz (2 x 3167)|
|Memory (System)|4.00GB (0.89GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
django-snippets|bib|1.1.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
vscode-great-icons|emm|2.1.28
vsc-material-theme|Equ|1.5.0
code-runner|for|0.9.1
nbpreviewer|jit|1.0.0
vscode-simple-icons|Lau|1.8.2
MagicPython|mag|1.0.12
vscode-language-pack-pt-BR|MS-|1.21.2
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.2.1
material-icon-theme|PKi|3.2.3
vscode-yaml|red|0.0.9
ayu|tea|0.14.0
python-extended-snippets|tus|0.0.1
jinja|who|0.0.8

(3 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
Please provide steps that allow us to reproduce the problem. Please see https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. If the issue is with an extension (as you indicate) please file the issue against the extension.

**Comment by weinand** [comment]
What debugger are you using?

**Comment by lindapescatore** [comment]
I'm getting this error as well.
