### ISSUE TITLE
Borders styles for selection and word highlight

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#45479]
- VSCode Version: 1.21
- OS Version: macOS

Currently border style for selection and word highlight are dotted. It's possible to make it like it's with `findMatchBorder` which is straight lines?

**Selection** (`editor.selectionHighlightBorder`)
<img width="36" alt="image" src="https://user-images.githubusercontent.com/10441177/37244690-83045cb4-2495-11e8-8bc6-09f258a98a23.png">
As you can see it's dotted.

**Word highlight** (`editor.wordHighlightBorder`/`editor.wordHighlightStrongBorder`)
<img width="264" alt="image" src="https://user-images.githubusercontent.com/10441177/37244720-e04c1948-2495-11e8-98a7-4cbd0e188b6d.png">
As you can see it's dotted.

**Find match** (`editor.findMatchBorder`)
<img width="64" alt="image" src="https://user-images.githubusercontent.com/10441177/37244696-969efbd0-2495-11e8-9e46-95ef012178c4.png">
As you can see border lines are straight, this is how it needs to look like in **selection** and **word highlight** borders.

**Comment by svipben** [comment]
Same problem is with `editor.findMatchHighlightBorder`. As I can see only `editor.findMatchBorder` is working as expected.

**Comment by MilyMilo** [comment]
Same issue on ubuntu 17.10, since the recent update (1.21) the styling's been broken.

**Comment by MilyMilo** [comment]
This issue is theme specific, doesn't exist on Monokai or other themes. I reckon this only concerns OneDark Pro.

**Comment by svipben** [comment]
@MilyMilo This doesn't exist in Monokai because Monokai theme doesn't use border for search since there's no such color specified in theme. As you can see in this issue I'm talking about new colors introduced in VS Code 1.21 which borders text, but the problem is border are dotted instead of straight line. So this isn't OS or theme specified, the problem is VS Code and only one color works properly (`editor.findMatchBorder`) which uses lines for border instead of dots.

**Comment by svipben** [comment]
https://github.com/Microsoft/vscode/blob/7de696a202a4808f8fb0429e4a665e9b7bc41c41/src/vs/editor/contrib/wordHighlighter/wordHighlighter.ts#L522

I found here it's `dotted`. Should I make a PR in proper places to change from `dotted` to `solid`?

/cc @kieferrm @alexandrudima

**Comment by svipben** [comment]
I also see `findMatchBorder` is `2px` while others are `1px`. Is that correct?
I would also like to suggest to use border solid for `findMatchHighlightBorder`.

**Comment by svipben** [comment]
![image](https://user-images.githubusercontent.com/10441177/37566717-b421bdba-2ac5-11e8-9912-ee23f78f2bc8.png)

With different border styles, we get this issue above in the screenshot. We definitely need solid style. Right now it looks like garland :D

**Comment by svipben** [comment]
@bpasero since you're working with colors, what do you think? The idea is from Atom with `highlight-selected` plugin. It's really weird to see the dotted or dashed border styles. If needed I can create a PR.

**Comment by alexandrudima** [comment]
We can do solid border styles for anything except high contrast. In the high contrast theme, the same color is used for all of these decorations and the only distinguishable trait is the border style.

**Comment by svipben** [comment]
@alexandrudima I'm very happy!!!

* What about `findMatchBorder` which have `2px`, it's correct?
* Also, you forgot to set `findMatchHighlightBorder` to `solid` too.

If you want I can create a PR.

**Comment by alexandrudima** [comment]
:+1: for a PR

**Comment by svipben** [comment]
@alexandrudima Thanks. I will start to work on it right now!

**Comment by svipben** [comment]
@alexandrudima Already done in https://github.com/Microsoft/vscode/pull/46956. Please review ☺️
