### ISSUE TITLE
SVG images are not shown in markdown preview with disabled security police

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [Microsoft/vscode#45476]
Issue Type: <b>Bug</b>

Even if Markdown Security Police is disabled,  `.svg` images are still not loading and warning of disabled content appears.

1. Turn off Markdown Security Police
2. Create markdown file with content
 ```md
 ![Alternative text](https://img.shields.io/badge/Super%20Cool-Badge-blue.svg)
 ```
3. Open Markdown Preview

**Expected Behavior**: ![Alternative text](https://img.shields.io/badge/Super%20Cool-Badge-blue.svg)
**Actual Behavior**: 
![Warning](https://i.imgur.com/rT6jqJO.png)
![Alternative text](https://imz.shields.io/badge/Super%20Cool-Badge-blue.svg) 

**VS Code version**: Code - Insiders 1.22.0-insider (3817c899cae312e0e989da8bfbc61308cfbf45f1, 2018-03-09T05:15:56.454Z)
**OS version**: Windows_NT x64 10.0.17115

<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.1.9
yandex-translate|air|1.0.5
Bookmarks|ale|0.18.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.13.0
gitlens|eam|8.1.0
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
gitlab-workflow|fat|0.6.0
vsc-figlet|fer|0.0.8
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.6
npm-dependency-links|her|1.0.0
rest-client|hum|0.17.0
discord-vscode|icr|2.2.1
vscode-insertdatestring|jsy|2.2.2
indentation-level-movement|kai|1.1.1
theme-karyfoundation-themes|kar|17.0.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-todo-parser|min|1.9.1
mono-debug|ms-|0.15.8
node-modules-resolve|nau|1.0.2
indent-rainbow|ode|0.7.2
vscode-icons|rob|7.20.0
MDTools|sea|1.0.1
code-settings-sync|Sha|2.9.0
gitconfig|sid|1.0.0
vscode-wakatime|Wak|1.1.22

</details>
Reproduces without extensions

**Comment by craxal** [comment]
Also encountering this issue with local files. Neither "Allow insecure content" or "Disable" options work.

```markdown
![alt](./Test.svg)
```

The workaround is to inline the SVG, but that's undesirable for larger SVG images.

**Comment by gabyx** [comment]
Have the same problem
