### ISSUE TITLE
The box of Information on hover gets strange when there's nothing to show.

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#45471]
- VSCode Version: 1.21.0
- OS Version: macOS High Sierra

When you hover on something and the language server won't send any info you'll get something like this little shape:

<img width="328" alt="screen shot 1396-12-19 at 2 57 06 pm" src="https://user-images.githubusercontent.com/2157285/37241740-6e4df608-2473-11e8-9a90-d76bd4caea88.png">

**Comment by kieferrm** [comment]
Please file the issue against the go extension [here](https://github.com/Microsoft/vscode-go/issues/new). Thanks!
