### ISSUE TITLE
Remove `editor.findMatchHighlightBorder` border from search panel

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#45480]
- VSCode Version: 1.21
- OS Version: macOS

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/10441177/37244801-c3314a12-2496-11e8-836d-2de212a9a058.png">

My suggestion is to remove border from search panel (left) and keep it only in editor (right) because it's really hard to read text when it gets bordered in search panel. But this feature is very good when you get bordered text in editor.

`editor.findMatchHighlightBorder`

**Comment by roblourens** [comment]
Why is it easy to read in the editor, but hard to read in the search results?

We can't just remove that without any other changes - it will break some themes that rely on it, like the high contrast theme.

**Comment by svipben** [comment]
@roblourens Maybe you're right, but at first it was really weird to see border in search panel, but since we will have search panel inside bottom widget I believe it makes sense if for e.g. long text will have the same keyword you're searching for.

When there's no other text in search panel it's very easy to find it, as you can see I have 4 "one" words, but inside editor panel, there's much more text that's why it makes sense to keep it only here.

**Comment by roblourens** [comment]
I think that more often than not, search will be matching just part of a line rather than the entire line, whether the search is in the sidebar or panel. 

I'm not really convinced on this one, and I'm worried about breaking existing themes.
