### ISSUE TITLE
Marketplace extension descriptions should style kbd tags

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4548]
Similar to on GitHub, the `<kbd>` tag should be styled. An example: https://marketplace.visualstudio.com/items?itemName=codezombiech.gitignore

**Comment by joaomoreno** [comment]
ping @pradeepna

**Comment by CodeZombieCH** [comment]
+1, would definitely increase readability

**Comment by joaomoreno** [comment]
Seems to be working now!
