### ISSUE TITLE
SourceMaps.loadSourceMapContents

### ISSUE THREAD

**Issue by macasas** [Microsoft/vscode#45489]
- VSCode Version: 1.21.0 February 2018
- OS Version: osx 10.12.6

Steps to Reproduce:

1. Open extension project in vscode
2. Start debugging

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Been building an extension using .js
VSCode started logging multiple sourcemap errors
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/9a199d77c82fcb82f39c68bb33c614af01c111ba/core/bootstrap.js.map
Then logs that extension has started.

**Every time the bot hits an error, VSCode locks up and hangs for about 30 seconds, then crashes and asks to be reopened.**

Not the most productive debugging experience.

There was a previous report talking about 1.20.1, so I updated to 1.21.0 but it is still doing it.

Is there are workaround, am I doing something wrong?
Is the app freezing related to the SourceMaps.loadSourceMapContents logs, or is this a red-herring?

I would just like to be able to debug, hit a breakpoint as normal.

**Comment by roblourens** [comment]
I haven't seen this. The loadSourceMapContents warning is probably unrelated to the crash.

If you are still seeing this in the latest insiders, could you set `"trace": true` in your launch config, run again, and upload the log from the file that it prints to the debug console?
