### ISSUE TITLE
Report issue button gets in the way

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#45485]
Issue Type: <b>Settings Search Issue</b>

![screen shot 2018-03-10 at 1 49 31 pm](https://user-images.githubusercontent.com/439226/37245689-fecd0584-2469-11e8-806c-f082ba37f1ca.png)

VS Code version: Code - Insiders 1.22.0-insider (3817c899cae312e0e989da8bfbc61308cfbf45f1, 2018-03-09T05:22:09.549Z)
OS version: Darwin x64 17.4.0

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.13.0
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.28
Go|luk|0.6.77
language-stylus|sys|1.9.1
vim|vsc|0.11.1
markdown-pdf|yza|0.1.7

</details><details><summary>Results</summary>

Setting|Extension|Score
---|---|---
editor.renderLineHighlight|core|6.112
editor.matchBrackets|core|5.076
markdown-pdf.highlight|yzane.markdown-pdf|1.749
editor.occurrencesHighlight|core|1.336
editor.selectionHighlight|core|1.291
markdown-pdf.highlightStyle|yzane.markdown-pdf|0.954
markdown-pdf.border.top|yzane.markdown-pdf|0.004
markdown-pdf.breaks|yzane.markdown-pdf|0.004
markdown-pdf.convertOnSaveExclude|yzane.markdown-pdf|0.004
markdown-pdf.styles|yzane.markdown-pdf|0.004
markdown-pdf.format|yzane.markdown-pdf|0.004
markdown-pdf.header.contents|yzane.markdown-pdf|0.004
markdown-pdf.header.height|yzane.markdown-pdf|0.004
markdown-pdf.border.bottom|yzane.markdown-pdf|0.004
markdown-pdf.outputDirectory|yzane.markdown-pdf|0.004
markdown-pdf.StatusbarMessageTimeout|yzane.markdown-pdf|0.004
markdown-pdf.emoji|yzane.markdown-pdf|0.004
markdown-pdf.footer.contents|yzane.markdown-pdf|0.004
markdown-pdf.footer.height|yzane.markdown-pdf|0.004
markdown-pdf.quality|yzane.markdown-pdf|0.004

</details>

Query: highlight
Literal matches: 9

**Comment by roblourens** [comment]
This is only to get feedback in insiders and I don't have a way to disable it right now. You'll have to work around it.

**Comment by rajinder-yadav** [comment]
the new way to report issue sucks, i end up going to github, so a -1 from me
