### ISSUE TITLE
Working Tree & Index diff view should remember scroll position

### ISSUE THREAD

**Issue by papb** [Microsoft/vscode#45483]
Issue Type: <b>Feature Request</b>

When using VSCode associated with git, we can see the diffs easily by double-clicking the changed files, which opens a new tab "myFile.txt (Working Tree)" or "myFile.txt (Index)". In both cases, it auto-scrolls to the first diff line, which is great at the first moment, but after switching tabs and coming back, it re-auto-scrolls to the first diff line, although it would be much better (IMO) if it remembered the scroll position, just like it does with normal file tabs.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.1.7601

**Comment by bpasero** [comment]
Covered via https://github.com/Microsoft/vscode/issues/10663 and https://github.com/Microsoft/vscode/issues/27684
