### ISSUE TITLE
Can't add breakpoints to JS files

### ISSUE THREAD

**Issue by madskonradsen** [Microsoft/vscode#45486]
- VSCode Version: Version 1.21.0 (1.21.0)

![image](https://user-images.githubusercontent.com/1265787/37246141-ea474ca2-24a3-11e8-8218-8b8d4d401071.png)

Steps to Reproduce:

1. Open .js file
2. No space in gutter for adding breakpoints

Does this issue occur when all extensions are disabled?: Yes

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

    {
        "type": "node",
        "request": "launch",
        "name": "Launch via NPM",
        "runtimeExecutable": "npm",
        "runtimeArgs": [
            "run",
            "dev"
        ],
        "port": 9229
    },
    ]
}
```

```json
{
  "name": "amd",
  "version": "1.0.0",
  "description": "",
  "main": "amd.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "node --inspect ./amd.js"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by shobhitchittora** [comment]
@madskonradsen Follow this guide to setup debugging in vscode. 

https://code.visualstudio.com/docs/editor/debugging

**Comment by madskonradsen** [comment]
Already did, several times with several different projects. Tried updating, tried disabling all plugins, but still the gutter don't have space for breakpoints as seen on the picture..

**Comment by kieferrm** [comment]
Do you see the same layout issue when you restart vscode and specify a new, empty directory as user data directory using `code --user-data-dir <your-dir>`?

**Comment by madskonradsen** [comment]
That seems to fix it! :S

**Comment by alexandrudima** [comment]
@madskonradsen  It looks like you have disabled the glyph margin via user settings? If you write `editor.glyphMargin: false` in user settings, then the glyph margin is hidden.
