### ISSUE TITLE
Cant Use Slices in GoLang After Last Update :(

### ISSUE THREAD

**Issue by iraqiDeveloper** [Microsoft/vscode#45494]
Issue Type: <b>Bug</b>

Cant Use Slices With Sprintf() After Last Update!

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2195)|
|Memory (System)|7.90GB (5.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\salih\Desktop\MustafasGoLangProjects\webloop\webloop.go|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
Go|luk|0.6.77

</details>
Reproduces only with extensions

**Comment by ramya-rao-a** [comment]
@ghost Please provide more details on the issue you are facing. Sample code and clear steps to reproduce the issue will help
