### ISSUE TITLE
Add me to Microsoft GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [Microsoft/vscode#45498]
Add me to bower Microsoft Org, Know about me https://yoginth.ml

**Comment by MishUshakov** [comment]
How many contributions you have?

**Comment by YoginthS** [comment]
![screenshot](https://user-images.githubusercontent.com/36839013/37253695-144cceca-255b-11e8-983e-9c25c5a89712.png)

**Comment by jens1o** [comment]
Lol? Why do you need to be in the organisation? Perhaps you want to apply for a job at Microsoft? https://github.com/Microsoft/vscode/issues/27092
