### ISSUE TITLE
调试适配器进程已意外终止

### ISSUE THREAD

**Issue by tangchi695** [Microsoft/vscode#45496]
Issue Type: <b>Bug</b>

不能调试nodejs程序，F5提示调试适配器进程已意外终止。

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|Memory (System)|15.93GB (9.80GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details>Extensions: none
Reproduces without extensions

**Comment by MaleDong** [comment]
Translated into English is:
**Cannot debug Nodjs, "F5" shows that the debug adapter process crashed by accident.**
The title is:
**Debug Adapter Process crashed by accident.**

**Comment by weinand** [comment]
What debugger are you using?

**Comment by tangchi695** [comment]
ms-vscode.node-debug2

**Comment by weinand** [comment]
What version of node are you using?
What is your launch config?
What kind of node program are you debugging?
Please open the Developer Tools ("Toggle Developer Tools") after the crash and post a screenshot of the output here.

**Comment by tangchi695** [comment]
node v8.9.4
launch config {
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "启动程序",
            "program": "${workspaceFolder}/HelloWorld.js"
        }
    ]
}

console.log("hello world"); 

![qq 20180312161051](https://user-images.githubusercontent.com/16055749/37272059-68695950-2610-11e8-93b7-d4e1a20734b1.png)

**Comment by roblourens** [comment]
Does this happen every time? Are there any errors in the Debug Console?

**Comment by tangchi695** [comment]
@roblourens  Yes, it happens every time I use it. 
ESLint error:     The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by qinyao7777** [comment]
I Hava the same issue...

**Comment by qinyao7777** [comment]
![image](https://user-images.githubusercontent.com/30612732/37439809-d18d3174-2834-11e8-9f3f-66f5a2e39b53.png)

**Comment by Anysomeday** [comment]
I met the same issue when I run the python code , how did you solve this problem? Thank you.

**Comment by qinyao7777** [comment]
i do not know how to handle it. reinstall is no use. later i used sublime3 . now i use a new PC. it can work.

At 2018-03-25 11:44:23, "Anysomeday" <notifications@github.com> wrote:


I met the same issue when I run the python code , how did you solve this problem? Thank you.

**Comment by org0000h** [comment]
same problem

**Comment by MadSummer** [comment]
Maybe some extension problems. I uninstall <node-debug2> to solve this problem.
if can't uninstall,go to <<C:\Users\YOU PC ACCOUNT\.vscode\extensions\>> ,find the node-debug2 folder and remove it

**Comment by tangchi695** [comment]
今天更新到1.22.1版本 ，这个问题就解决了，可以调试node了。
