### ISSUE TITLE
VSCode在滚动时总是自动打开输出面板

### ISSUE THREAD

**Issue by Rain120** [Microsoft/vscode#45495]
这个很是影响用户体验，我不需要这个时候打开，wohai我还在调试代码，代码都没写完，她就自动打开，我需要的是他是用户选择打开

**Comment by MaleDong** [comment]
@Microsoft : 
Translated into English is:
The output panel is always opening while debugging codes, and I didn't finish my codes yet.

@Rain120 ：
Would you mind making a record video and submit here for Microsoft members to make an analyse? And for the next time, please put down your ideas in English ;)

You can use something like: https://obsproject.com/, A free video maker.

**Comment by kieferrm** [comment]
You can control the behavior with the `debug.internalConsoleOptions` setting.
