### ISSUE TITLE
vs code cannot find module .vue and package.json

### ISSUE THREAD

**Issue by francoisromain** [Microsoft/vscode#45491]
- VSCode Version: 1.21
- OS Version: 10.13.3

With Visual Studio Code, and [automatic type acquisition][1] enabled, there are `[js] Cannot find module` errors:

- on .vue files imported in a .js file (example [here][2])
- on package.json imported in webpack.config.js (example [here][3])

How is it possible to fix that? 

(I asked on [stackoverflow](https://stackoverflow.com/questions/49201440/vs-code-cannot-find-module-vue-and-package-json) first, but didn't have success)

Thank you

  [1]: https://code.visualstudio.com/docs/languages/javascript#_automatic-type-acquisition
  [2]: https://github.com/francoisromain/camomile-ui/blob/master/src/app.js
  [3]: https://github.com/francoisromain/camomile-ui/blob/2a29c2e7a81415f55eb0c8fd7d1fbd0fcaadfbeb/build/webpack.config.dist.js#L11

**Comment by mjbvz** [comment]
Our built-in intelliesense doesn't support resolving vue files. Please try using vetur or a similar vue extension  

Support for importing json files is tracked by: https://github.com/Microsoft/TypeScript/issues/7071

**Comment by francoisromain** [comment]
@mjbvz Thank you for your answer. In the project linked above, I use Vetur already and still have errors
