### ISSUE TITLE
Could vs code supports ES6 in <script></script>?

### ISSUE THREAD

**Issue by g0ne150** [Microsoft/vscode#455]
I use Vue and webpack to build my webapp, which allows me to write a web component  like this:

```html
<style>
 /*the component's css goes here*/
</style>
<template>
  <!-- the component's html goes here-->
  <div></div>
</template>
<script>
  // the component's js goes here
  import Xx from 'xx'
  let xx = new Xx()
  xx(yy => {
    return 'Have a nice day'
  })
</script>
```

but, the problem is even I created a jsconfig.json file which sets the target to ES6. It just didn't work.

**Comment by joaomoreno** [comment]
Related to #337

**Comment by jrieken** [comment]
Done by having the default be ES6

**Comment by lordgreg** [comment]
@jrieken I don't understand your last comment on this issue? This is done by having the default be ES6? Where? Default what? You mean in tsconfig.json?

```
{
  "compilerOptions": {
    "target": "ES6",
```

**Comment by g0ne150** [comment]
@lordgreg It seems theres no needed jsconfig.json for ES6 syntax, ES6 in <script> tag nothing changed

**Comment by jrieken** [comment]
jsconfig never includes html files, but the default settings, even in absence of a config files are now set to ES6

**Comment by lordgreg** [comment]
So this is getting fixed in new update?

**Comment by jrieken** [comment]
With Dec15 the default for all JS will be ES6, however we have not tackled html-files and jsconfig

**Comment by arlair** [comment]
So shouldn't this or #559 be opened if it is not working in HTML files?
