### ISSUE TITLE
VS Code v1.21 in yumrepos 

### ISSUE THREAD

**Issue by codermantx** [Microsoft/vscode#45500]
VS Code v1.21 not available in yumrepos yet.

**Comment by toxinu** [comment]
Every time there is a new vscode release, rpm package arrived 3-7 days later.

This is really annoying to have vscode message which say there is a new release until we are able to install new rpm.

Is it possible to fix it?

**Comment by Tyriar** [comment]
I updated the docs to indicate that there may be a delay. This happens most months for various reasons that are generally out of our team's control https://github.com/Microsoft/vscode-docs/commit/edd77942d0a43d734ffed7aa51b0c13b98bc6744. We cannot automate this currently and rely on multiple internal teams and sometimes the delays are long or the tools don't work.

I've been working with the repo team to get this resolved after publishes silently failed.

**Comment by codermantx** [comment]
The version v1.21 is now available (https://packages.microsoft.com/yumrepos/vscode/).
Hence, closing this issue.

Now to wait for v1.12.1! :laughing:

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/45868
