### ISSUE TITLE
Unable to open browser 

### ISSUE THREAD

**Issue by saileshkush95** [Microsoft/vscode#45508]
Issue Type: <b>Bug</b>

When I Open live server after installing live server preview plugins, It starts live server but unable to open browser.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|3.92GB (0.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
php-debug|fel|1.12.1
php-intellisense|fel|2.2.9
php-pack|fel|1.0.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.1
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.3.0
vscode-phpfmt|kok|1.0.18
mssql|ms-|1.3.0
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.2.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
team|ms-|1.122.0
java|red|0.20.0
vscode-yaml|red|0.0.9
blank-line-organizer|rin|0.1.2
LiveServer|rit|3.2.1
vscode-icons|rob|7.20.0
bootstrap4-vscode|the|4.0.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
Please file the issue against the Live-share extension [here](https://github.com/MicrosoftDocs/live-share/issues/new).
