### ISSUE TITLE
backspace

### ISSUE THREAD

**Issue by shenzongyi1997** [Microsoft/vscode#45503]
### Issue Type
Bug

### Description

I cannot use Backspace now.It shows a warning:"command 'markdown.extension.onBackspaceKey' not found".

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz (4 x 2794)|
|Memory (System)|7.92GB (2.94GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe E:\FileRecv\ielts\xiaozhan\口语\3.5第一节课\第一次口语课笔记.md|
|Screen Reader|no|
|VM|36%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|tht|0.2.3
markdown-all-in-one|yzh|1.1.0

</details>
Reproduces only with extensions

**Comment by Mrigank11** [comment]
You need to upgrade to VS Code Version 1.21, see neilsustc/vscode-markdown#117
