### ISSUE TITLE
There is no way to use FindController in minified distro

### ISSUE THREAD

**Issue by novikov-alexander** [Microsoft/vscode#4550]
- VSCode Version: February
- OS Version: Win 10

Steps to Reproduce:

1. run "gulp editor-distro" in vscode folder.
2. try to force editor to open Find/Replace window. There is no same way

**Comment by novikov-alexander** [comment]
Straight using of FindController.ts may cause an error when FindController loads earlier than editor.main

**Comment by alexandrudima** [comment]
I think this is now obsolete, since the `monaco-editor` is on npm. If not, please open a new issue at https://github.com/Microsoft/monaco-editor
