### ISSUE TITLE
Pre and Post hooks for npm scripting

### ISSUE THREAD

**Issue by qiulang** [Microsoft/vscode#45505]
- VSCode Version: 1.21.0
- OS Version: macOS 10.13.3

When `npm run-script commands`. Pre and post commands with matching names will be run, e.g. when I run `npm start`, prestart & poststart scrips will be run, but if I run npm start from launch.json prestart & poststart scrips won't be run.

Steps to Reproduce:

1. Add prestart & poststart scrips in package.json
2. `Launch via NPM` from vscode, prestart & poststart scrips won't be run

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
This works fine for me.

I'm using this `package.json`:
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "prestart": "say pre",
    "start": "say start",
    "poststart": "say post"
  },
  "author": "",
  "license": "ISC"
}
```

and this `launch.json`:

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"runtimeExecutable": "npm",
			"runtimeArgs": [
				"run-script", "start"
			]
		}
	]
}```

After pressing F5 I can hear loud and clear: "Pre - Start - Post"

**Comment by weinand** [comment]
After closing this I noticed that you said 
> `Launch via NPM` from vscode

What extension are you using?
I've installed the ["npm"](https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script) and there it works too.

If you are using a different extension please file the issue against that one.

**Comment by qiulang** [comment]
No, I didn't use npm extension I launched npm via launch config as you showed here. But I found the reason why I thought `prestart` did not run, because I run `echo ...` and I didn't see the output at debug console. After `"outputCapture": "std"` to `launch.json` the problem solved.

Thank you for replying my issue.
