### ISSUE TITLE
top element cut off when hovering in debugger

### ISSUE THREAD

**Issue by lineus** [Microsoft/vscode#45509]
Issue Type: <b>Bug</b>

I'm currently running the debugger on a node process. When I hover over a variable the top section of the modal is cut off and for longer chunks of information it's unusable.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           E5462  @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|20.00GB (2.57GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_389215|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.5.1
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.2.4
vscode-eslint|dba|1.4.7
flow-language-mode|goz|0.0.2
docthis|joe|0.6.0
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
python|ms-|2018.2.1
atom-keybindings|ms-|3.0.4
PowerShell|ms-|1.6.0
vscode-icons|rob|7.20.0
sass-indented|rob|1.4.8
gitflow|vec|1.1.2

(10 theme extensions excluded)

</details>
Reproduces without extensions

![img_0638](https://user-images.githubusercontent.com/6015453/37253149-0d3b086a-2504-11e8-8310-1fff273a02cd.JPG)

**Comment by isidorn** [comment]
It does not seem to be cut of, but just badly centered.
Can you reproduce this all the time?
Can you try reproducing when disablling all extensions? Or simply try vscode inisders https://code.visualstudio.com/insiders/

**Comment by lineus** [comment]
Yes, it's like this all of the time. The picture I added was taken while extensions were off. I can select all of the text that's cut off by (triple?) clicking and I can copy paste it into another doc, the height of the container is the same whether it's one line or 50 and it isn't scroll-able. I'll give insiders a try at some point today. 

Thanks @isidorn !

**Comment by isidorn** [comment]
@lineus trying it out in insiders would be great
If it also does not work there than I would need you to debug this a bit on your machine, since I can not reproduce on my mac. Maybe you first try insiders and if it also does not work there I can give you some steps on how we can collect additional info for this.

**Comment by lineus** [comment]
insiders looks much better. Thanks for helping me out @isidorn :)
