### ISSUE TITLE
app doesnt react for a certain project only

### ISSUE THREAD

**Issue by NitsanBaleli** [Microsoft/vscode#45504]
Issue Type: <b>Bug</b>

starting the app in  a certain dir results in nothing working.
errors in console:
Cannot assign to read only property 'tabSize' of object '[object Object]'
etc.

VS Code version: Code - Insiders 1.22.0-insider (3817c899cae312e0e989da8bfbc61308cfbf45f1, 2018-03-09T13:53:26.466Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2593)|
|Load (avg)|2, 1, 1|
|Memory (System)|7.70GB (0.72GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.9.0
Bookmarks|ale|0.18.2
vscode-quick-select|dba|0.2.5
gitlens|eam|8.1.0
prettier-vscode|esb|1.2.2
macros|ged|1.2.1
search-node-modules|jas|1.3.0
code-beautifier|mic|1.7.2
vscode-autoprefixer|mrm|2.1.2
vscode-pugbeautify|mrm|1.0.2
sublime-keybindings|ms-|3.0.3
vscode-icons|rob|7.20.0

</details>
Reproduces without extensions

**Comment by NitsanBaleli** [comment]
emptying .vscode/settings.json helped, and app is now working

settings.json:

{
"prettier.tabWidth": 4,
    "editor.tabSize": 4,
    "[javascript]": {
        "editor.tabSize": 4,
        "editor.wordWrap": "off"
    },
    "search.exclude": {
        "**/node_modules": false,
        "**/bower_components": false
    },
    "search.useIgnoreFiles": false
}

**Comment by sandy081** [comment]
@NitsanBaleli Can you please provide the complete error stack trace you see in the console
