### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by simaipeter** [Microsoft/vscode#45507]
Issue Type: <b>Bug</b>

Removing the phone when running a debugger with nativescript makes it stuck 

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-5600K APU with Radeon(tm) HD Graphics    (4 x 3593)|
|Memory (System)|7.94GB (4.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tns-cli|pko|0.0.3
java|red|0.20.0
nativescript|Tel|0.7.3
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2

</details>
Reproduces without extensions

**Comment by kieferrm** [comment]
Please file the issue against the native script extension [here](https://github.com/NativeScript/nativescript-vscode-extension/issues/new). Thanks!
