### ISSUE TITLE
CANNOT RUN PYTHON FILE VIA TERMINAL FROM CONTEXT MENU IN VS CODE 1.21

### ISSUE THREAD

**Issue by Arpitx** [Microsoft/vscode#45517]
Issue Type: <b>Bug</b>

From vs code context menu, there is an option to run a given code snippet in terminal, but when I try to run the code as 'Run python file in terminal' or 'Run python file / selection file in terminal' nothing happens and there is no output for the code as simple as for eg:

```
x = 5
y = int(x)
print(type(y))

```
VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.89GB (2.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.1
python|ms-|2018.2.1
cpptools|ms-|0.15.0
sublime-keybindings|ms-|3.0.3
team|ms-|1.122.0
debugger-for-chrome|msj|4.2.0
material-icon-theme|PKi|3.2.5
vscode-icons|rob|7.20.0

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment]
Please file this issue against the python extension [here](https://github.com/Microsoft/vscode-python/issues/new). Thanks!
