### ISSUE TITLE
Ansi escape sequences are broken in Terminal.

### ISSUE THREAD

**Issue by Josar** [Microsoft/vscode#45516]
When using the openssh feature of win10 with VSCode the escape sequences from command line gets corruptet when passed to the terminal.

In the normal command line, bash or powershell the output is well formatted.
But no matter which is used to execute the ssh command in VSCode the terminal output is corrupted.

![grafik](https://user-images.githubusercontent.com/6164061/37254234-9479c47e-253b-11e8-9412-118283d5ffb4.png)

```
"terminal.integrated.shell.windows": 
"C:\\Cygwin\\bin\\bash.exe",
"C:\\WINDOWS\\System32\\cmd.exe"
"C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
```

Is there a way to fix this?

Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Tyriar** [comment]
I mentioned this in https://github.com/Microsoft/vscode/issues/45693, let's track it there.
