### ISSUE TITLE
Control Break hotkey is not handled by powershell

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#45510]
- VSCode Version: 1.21
- OS Version: win10

Steps to Reproduce:

1. run this in powershell `python -c "print('a =',input('input a: '))"`
2. press CTRL+BREAK
3. Nothing happens till you hit ENTER

By the way Ctrl+C behavior differs too. Powershel.exe handles Ctrl+C before hitting enter, but vs code blocks on stdin reading

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Tracking this in https://github.com/Tyriar/node-pty/issues/7 and https://github.com/Microsoft/vscode/issues/45693
