### ISSUE TITLE
"Select All Occurrences of Find Match" should respect current selection

### ISSUE THREAD

**Issue by balta2ar** [Microsoft/vscode#45519]
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:01:43.521Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64-
OS Version: ArchLinux

It's very convenient to create multiple cursors from the current pattern of Find Matches form. Unfortunately, if there is an active text selection, multiple cursors are still created in all the document.

![select-all-occurences](https://user-images.githubusercontent.com/340676/37254954-ad0133fe-2556-11e8-88cd-6752be60aca2.gif)

Could you please adjust "Select All Occurrences of Find Match" command to create multiple cursors only within the selection, if there is any, and in the whole document otherwise. Thanks.

Does this issue occur when all extensions are disabled?: Yes

**Comment by balta2ar** [comment]
It looks like the same goes for Find -> Replace All operation. I'd would be nice if it operated only within the selection.

**Comment by galich** [comment]
I just stumbled upon the same issue. I want to split my long literal into chunks of 64 chars. I'm selecting that literal and searching with regex `.{64}` in it, but then **Ctrl+Shift+L** selects everything in the document, when I'm expecting it to insert cursors inside my selection only.

**Comment by balta2ar** [comment]
It looks like in the latest release (Version 1.23.0 Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45 Date 2018-05-03T15:23:19.356Z) this functionality got broken. Specifically, "Select All Occurrences of Find Match" command now:

1. does nothing if no word can be selected at the cursor position.
2. replaces find match with the current word at the cursor, if it can be found. 
3. replaces find match with the visual selection (if it's present).

In all three cases it should use the latest find match pattern, IMHO. @rebornix  Could you please look into that?

**Comment by balta2ar** [comment]
@alexandrudima @kieferrm Sorry for being noisy, but should I open a separate bug report regarding my previous message? Could this be fixed (restored) in 1.23.1?

**Comment by ldexterldesign** [comment]
NO REPLY NECESSARY

Hey all,

Hope you're well

Thanks for highlighting this issue

The current workaround, for me, is to copy/paste the selected text into a separate file and run find/replace on that - by no means a solution but only occurred to me recently after many occasions of simply giving up and waiting for this to be fixed

Hope this is useful

Regards

**Comment by rebornix** [comment]
To do search/replacement in a selection, you can do

* Type in the query, for example `\d+` in regex mode
* Select the selection you want to run replacement
* Press Alt+L to toggle "Find in selection" or click the button before the close button in the find widget.
