### ISSUE TITLE
INPUT COMMAND IN VS CODE

### ISSUE THREAD

**Issue by Arpitx** [Microsoft/vscode#45513]
Issue Type: <b>Feature Request</b>

Can it be like just running the code normally including 'input' command from the user, and the input is taken from the terminal itself instead of going through debugger and integrated terminal option in vs code.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kieferrm** [comment]
Can you please describe your scenario in more detail? Thanks!

**Comment by Arpitx** [comment]
Something like:

```
x = input('Enter the value:')
print(x)

```
Now for this code to run, I have to go to either debugger section or run the code by running from terminal (from context menu), not like other IDE's where they ask for input in the terminal itself after running the code.

Similar scenario comes when I try to run the basic turtle program like:

```
import turtle
m = turtle.Turtle()
userTurnAngle = input("Enter the degree of the turn: ")
userLength = input("Enter the length of the line: ")
m.pencolor('red')
m.right(int(userTurnAngle))
m.forward(int(userLength)) 
```
so when I try to run this code normally, it gets stuck for the input only, so either I've to run the file in the debugger section (which is currently not working, with integrated terminal also), or run the selected file in terminal (from context menu).

**Comment by weinand** [comment]
You have to configure the debugger you are using to run the program in a terminal that supports reading from input. For "node.js" you would add `"console": "integratedTerminal"` to your launch config. 

@DonJayamanne can you help?

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#1035
