### ISSUE TITLE
caret position moves to the end of file on save

### ISSUE THREAD

**Issue by ropali** [Microsoft/vscode#45518]
Issue Type: <b>Bug</b>

I was working on basic html file with javascript.Whenever i press ctrl+s the screen flickers and caret position moves to the end of file.First i thought it was due to the extension prettier i installed but it is happening even if i disabled the extension.This is happening after the latest update.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-7210 APU with AMD Radeon R3 Graphics     (4 x 1797)|
|Memory (System)|6.91GB (3.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vsc-material-theme|Equ|1.5.1
javac-linter|fau|1.3.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
bem-expand|luk|0.1.4
atom-keybindings|ms-|3.0.4
material-icon-theme|PKi|3.2.5
java|red|0.20.0
java-imports-snippets|tus|0.0.1
vscode-terminal-here|Tyr|0.1.1
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by kieferrm** [comment]
What you describe happens when a formatter is activated on save and replaces the whole content rather than applying minimal edits.  I'd suspect the `vscode-JS-CSS-HTML-formatter` extension. Pls verify by disabling the extension.

**Comment by ropali** [comment]
Disabling vscode-JS-CSS-HTML-formatter extension worked for me.thanks
