### ISSUE TITLE
Allow to view Taskbar and clock in zen mode

### ISSUE THREAD

**Issue by Arpitx** [Microsoft/vscode#45528]
- VSCode Version: 1.21
- OS Version: Windows 10

I've enabled my taskbar to be hidden in desktop mode, but when I work on vs code in Zen Mode, I cannot view taskbar by hovering my cursor around the bottom portion. Can this feature be added as an optional feature to peek into taskbar in Zen Mode.

Also can clock be viewed in Zen Mode at user specified position like at bottom left or top right etcetc, that would be very helpful indeed (not asking too much as I know Zen Mode is used for distraction-free purpose.)

**Comment by isidorn** [comment]
Please use `"zenMode.fullScreen": false`
