### ISSUE TITLE
Laggy scroll

### ISSUE THREAD

**Issue by tomislavhren** [Microsoft/vscode#45522]
Issue Type: <b>Performance issue</b>

Sometimes it feels like scroll is a bit laggy. It feels like main thread is occupied and you can't scroll  for a few seconds. If I resize window it stops immediately, if not, it lasts for 3 or 4 seconds. I remember when before I installed 64bit version this wasn't the issue.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|15.84GB (7.42GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
vscode-flow-ide|gca|1.2.0
node-debug2|ms-|1.19.0
vscode-icons|rob|7.20.0
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.7.0

</details>
Reproduces without extensions

**Comment by kieferrm** [comment]
@tomislavhren are you an a laptop with a precision touch pad? If so this may be a dup of #13612. Or are you working with a high-res external display set you set to scale? Than this may be a dup of #9432.

**Comment by tomislavhren** [comment]
Yes, I have Lenovo Yoga 910 so it must be #13612
