### ISSUE TITLE
Keep scroll position stable when closing a tab in the tab well

### ISSUE THREAD

**Issue by LAITONEN** [Microsoft/vscode#45527]
- VSCode Version: 1.21.0
- OS Version: Sierra 10.12.6
 
Steps to Reproduce:
Basically, [this "bug"](https://github.com/Microsoft/vscode/issues/13001)  is still a thing. Can't comment there, thus creating a new issue.

**Comment by bpasero** [comment]
`"explorer.autoReveal": false`

**Comment by LAITONEN** [comment]
No, this does not help.

**Comment by bpasero** [comment]
@LAITONEN what do you see?

**Comment by LAITONEN** [comment]
@bpasero [This](https://github.com/Microsoft/vscode/issues/13001#issuecomment-250495286) when I have the leftmost tab open, scroll to the right and close rightmost tab.

**Comment by bpasero** [comment]
@LAITONEN when you say "Explorer" I assumed you mean the file explorer to the left. So you say when you close a tab, the tab-well scrolls? How do you close a tab?

**Comment by LAITONEN** [comment]
@bpasero My apologies, this was a silly mistake, rectified by now.
I close it by clicking the cross icon.

**Comment by bpasero** [comment]
@LAITONEN yes I see it, looks like a regression.

**Comment by bpasero** [comment]
Unfortunately our refactorings and repeated layout calls make this not as straight forward as I had hoped. I will have to leave this open until I found a better solution...

**Comment by LAITONEN** [comment]
@bpasero Thank you! That will work temporally.
