### ISSUE TITLE
Add keyboard shortcut to switch between editor and command terminal

### ISSUE THREAD

**Issue by stt106** [Microsoft/vscode#45524]
I just searched and it doesn't seem to exist yet; if it does please do shout out!

It would be nice to add a shortcut to switch between editor and terminal. When working on something like flutter, it needs constant switch between the editor and terminal (e.g. making changes in the editor then trigger hot reload to see the effect in the terminal then switch back to the editor to make more changes...).

**Comment by balta2ar** [comment]
I configured "Alt-\`" exactly for this purpose and it's very convenient! Give it a try! (keybindings.json):
```
    {
        "key": "alt-`",
        "command": "workbench.action.focusActiveEditorGroup",
        "when": "terminalFocus"
    },
    {
        "key": "alt+`",
        "command": "workbench.action.terminal.focus",
        "when": "!terminalFocus"
    },
```

**Comment by stt106** [comment]
@balta2ar It seems to work pretty work. Thanks!
For anyone else using a UK keyboard, the defined key is `alt + '`.
I am happy for this to be closed unless anyone else has more input on this!
