### ISSUE TITLE
How can I change encoding of integrated terminal?

### ISSUE THREAD

**Issue by Luberen** [Microsoft/vscode#45520]
I'm using Korean Windows 10, and its basic encoding option is CP949.
But encoding of VS Code's Output window is (probably) UTF-8 so if I add compile option "-fexec-charset=CP949" to gcc/g++, text printing error occurs.(I'm using Code Runner extension)

![vscode_enc](https://user-images.githubusercontent.com/26616056/37255109-0b5f611c-258b-11e8-9928-d2f3e573ea01.png)

I added `"terminal.integrated.shellArgs.windows": ["-NoExit", "/c", "chcp 949"],` in **User Settings**, but nothing has changed.

How can I change integrated terminal's encoding option to CP949?

**Comment by Tyriar** [comment]
This seems to fix most peoples encoding issues on Windows.

https://github.com/Microsoft/vscode/issues/19837#issuecomment-290843303

Let me know if that fixes your issue (maybe this should be in our terminal FAQ).

**Comment by Luberen** [comment]
It doesn't work at all.

**Comment by Tyriar** [comment]
@bitcrazed do you have any ideas on this? I don't know too much about encoding in the terminal on Windows but this might be another issue with winpty?

**Comment by bitcrazed** [comment]
@Luberen - could you run `chcp.exe` from your shell, what do you see?

Also:
* Which shell are you using? Cmd? PowerShell? Linux on WSL?
* Which build of Windows 10 are you using?
* You're using gcc/g++ - which platform are you targeting?
* If you're using cmd, try opening a Cmd prompt and running your app in various codepages.
* What font are you using for VSCode's terminal, and for your Console?

**Comment by Luberen** [comment]
@bitcrazed - I can't run chcp.exe in the shell.(`Error`: "chcp.exe" is not recognized as an internal or external command, operable program or batch file)

- I'm using Cmd.
- I'm using Windows 10 16299.309.
- Target platform is Windows
- The problem occurs only in 'Output' window of VSCode and it doesn't occur in Cmd.

**Comment by bitcrazed** [comment]
Sorry - corrected above - just run `chcp` (without `.exe`) from within Cmd and from within the Cmd instance attached to your VSCode's integrated terminal.

**Comment by bitcrazed** [comment]
You likely want this as your args setting:

    "terminal.integrated.shellArgs.windows": ["/k", "chcp 949"],

`/c` will execute the following command and exit. `/k` keeps the console connection open. Don't know what the `-NoExit` was for.
