### ISSUE TITLE
Unable to get intellisense from jquery IIFE functions

### ISSUE THREAD

**Issue by Umamaheswaran1990** [Microsoft/vscode#4553]
- VSCode Version: 0.10.11
- OS Version: Windows 7

Steps to Reproduce:

1. Create two files one with a.js and one with b.js
2. Create jsconfig.json with below content 

   ```json
    {
        "compilerOptions": {
            "module": "commonjs"
        }
    }
    ```   
3. In **a.js** add below code and install tsd jquery

    ```javascript
    (function() {
        
        function SomeMethod(){
            return "Im SomeMethod()";
        }
    })();
    ```

4. Now if you go to **b.js** and try typing Some... you will not see the intellisense.

Is it possible to get intellisense for the objects inside jquery IIFE?

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#7634
