### ISSUE TITLE
Error when opening VS Code after updating to latest version

### ISSUE THREAD

**Issue by yulybaseball** [Microsoft/vscode#45537]
Issue Type: <b>Bug</b>

I get this message every time I open VS Code. It started to happen after the last update. Working on Linux Mint.

"Visual Studio Code is running out of file handles. Please follow the instructions link to resolve this issue."

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.10.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2899)|
|Load (avg)|5, 3, 2|
|Memory (System)|11.61GB (4.47GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.2.1

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
@yulybaseball follow https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
