### ISSUE TITLE
Task `tsc: watch` fails to run when using Powershell Core

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/vscode#45540]
- VSCode Version: 1.21.0
- OS Version: Windows 10

Steps to Reproduce:

1. Add `"terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\6.0.1\\pwsh.exe"` on User Settings
 
2. Create a TypeScript project with `tsconfig.json`:

```json
{
    "compilerOptions": {
        "target": "es2017",
        "module": "commonjs",
        "strict": true
    }
}
```

3. Error occurs:

```
> Executing task: tsc --watch -p "c:\Users\sasch\Documents\GitHub\repro\tsconfig.json" <

The argument '/d' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
The terminal process terminated with exit code: 64

Terminal will be reused by tasks, press any key to close it.
```

Does this issue occur when all extensions are disabled?: Yes

@dbaeumer said in https://github.com/Microsoft/vscode/issues/42464 that I can set Workspace Settings to mitigate this but 1) it's painful to do it for every project I have/contribute 2) it's not really appropriate for general git repositories.

Setting it on User Settings does not help and even breaks Control+` integrated terminal.

I think adding ` || basename === 'pwsh.exe'` in line 434 is the most appropriate solution, what do you think?

https://github.com/Microsoft/vscode/blob/07b2c8015c265691393a4ef398a874365a3ad073/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L434-L447

**Comment by dbaeumer** [comment]
You can also add the shell to be used to execute to the tasks.json itself which will allow you to control the settings. However since pwsh is not uncommon I will add it.

**Comment by dbaeumer** [comment]
I added it.
