### ISSUE TITLE
Code [folder] hangs in batch scripts

### ISSUE THREAD

**Issue by Guthers** [microsoft/vscode#45543]
### Issue Type
Bug

### Description

I use a lot of on path batch scripts to open different groups of folders in vscode (as well as other things)

However it is annoying because about half the time the cmd window opened by the script hangs following the code "my folder path" command. It runs correctly and opens the vscode window, however the cmd prompt window remains, and closes when I exit out of the vscode window opened by the script.

Below is an example of a simple .bat script used
``` bash
code "C:\Users\User\my\folder\example"
```

Please let me know if I am doing something wrong, or if there is some way to force the command to return right away.

Thanks,
Harry

PS-I have looked to see if there was a similar issue already, apologies if this is a duplicate.
### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|7.98GB (1.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-motivational-gif|abe|1.0.1
swagger-viewer|Arj|1.5.0
jet|dio|0.0.1
python|ms-|2018.2.1
java|red|0.20.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-maven|vsc|0.5.2

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
Can you show me your `PATH` variable?

**Comment by Guthers** [comment]
C:\Users\User\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\User\AppData\Local\Programs\Python\Python36-32\;C:\Users\User\AppData\Roaming\Dashlane\4.6.6.23032\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Program Files\Microsoft VS Code\bin;C:\Users\User\AppData\Roaming\npm;C:\Users\User\AppData\Roaming\Dashlane\5.3.2.14186\ucrt;C:\Users\User\AppData\Local\GitHubDesktop\bin;C:\Users\User\workspace\bat scripts\path scripts;C:\Program Files\java\jdk1.8.0_131\bin;%M2_HOME%\bin;C:\curl\src;%DASHLANE_DLL_DIR%

The bat scripts I have put on the path exist in C:\Users\User\workspace\bat scripts\path scripts
