### ISSUE TITLE
Git分支远程更新vsCOde没有更新提示

### ISSUE THREAD

**Issue by Zhang-zhangyong** [Microsoft/vscode#45545]
### Issue Type
Bug

### Description

本地拉取远程git仓库代码后，远端仓库代码更新后，vscode左下角没有更新提示，用户体验很不好

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|7.90GB (2.82GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
stylus|Ala|0.0.4
px2rem|art|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-weapp-api|cod|0.1.8
vscode-wxml|cod|0.1.9
wpy-beautify|doi|2.0.10
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.1
we-app-vscode|eme|0.8.0
vscode-great-icons|emm|2.1.28
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
vscode-power-mode|hoo|2.1.0
docthis|joe|0.6.0
vscode-regexp-preivew|le0|0.0.3
node-module-intellisense|lei|1.5.0
debugger-for-chrome|msj|4.2.0
vetur|oct|0.11.7
vscode-wechat|qin|0.0.6
vscode-icons|rob|7.21.0
vue-vscode-snippets|sdr|1.3.0
indenticator|Sir|0.5.0
gitblame|wad|2.2.0
JavaScriptSnippets|xab|1.5.0

(4 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Google translate:
> After pulling the remote git repository code locally, after the remote repository code is updated, there is no update prompt in the lower left corner of the vscode. The user experience is very poor.

**Comment by joaomoreno** [comment]
Please set `"git.autofetch": true`.
