### ISSUE TITLE
Go extention can't do code complete any more

### ISSUE THREAD

**Issue by yuwgle** [Microsoft/vscode#45559]
Issue Type: <b>Bug</b>

Go extention can't do code complete any more

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.4.0-111-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3783)|
|Load (avg)|0, 0, 0|
|Memory (System)|7.75GB (3.21GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.28
Go|luk|0.6.77
python|ms-|2018.2.1
cpptools|ms-|0.15.0
vscode-icons|rob|7.21.0

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
This issue seems to be GO specific. It has been moved [here](https://github.com/Microsoft/vscode-go/issues/1575) for further discussion.
