### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45554]
From https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=58b08c6d-e50f-a6aa-f626-a7eac6214218

```
TypeError: Cannot read property 'length' of null
/vs/base/browser/ui/list/listView.ts#216:20 (length)
/vs/base/browser/ui/list/listWidget.ts#862:19 (length)
/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#266:28 (call)
/vs/base/common/event.ts#144:18 (fire)
/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#1156:30 (setVisible)
/vs/workbench/browser/parts/compositePart.ts#387:19 (hideActiveComposite)
/vs/workbench/browser/parts/sidebar/sidebarPart.ts#125:14 (hideActiveViewlet)
/vs/workbench/electron-browser/workbench.ts#828:30 (setSideBarHidden)
/vs/workbench/browser/actions/toggleSidebarVisibility.ts#33:26 (run)
/vs/workbench/common/actions.ts#114:38
```

**Comment by ramya-rao-a** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'length' of null<br />[TypeError: Cannot read property 'length' of null](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/srcTypeError: Cannot read property 'length' of null)<br />[/vs/base/browser/ui/list/listView.ts#L216:20 (length)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/browser/ui/list/listView.ts#L216:20 (length))<br />[/vs/base/browser/ui/list/listWidget.ts#L862:19 (length)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/browser/ui/list/listWidget.ts#L862:19 (length))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L271:29 (splice)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L271:29 (splice))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L262:73 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L262:73 (call))<br />[/vs/base/common/event.ts#L142:15 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L142:15 (fire))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L1096:20 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L1096:20 (call))<br />[/vs/base/common/event.ts#L144:18 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L144:18 (fire))<br />[/vs/workbench/services/scm/common/scmService.ts#L120:25 (registerSCMProvider)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/scm/common/scmService.ts#L120:25 (registerSCMProvider))<br />[/vs/workbench/api/electron-browser/mainThreadSCM.ts#L289:37 (apply)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/api/electron-browser/mainThreadSCM.ts#L289:37 (apply))<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'length' of null<br />[/vs/base/browser/ui/list/listView.ts#216:20 (length)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/browser/ui/list/listView.ts#L216:20 (length))<br />[/vs/base/browser/ui/list/listWidget.ts#862:19 (length)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/browser/ui/list/listWidget.ts#L862:19 (length))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#271:29 (splice)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L271:29 (splice))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#262:73 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L262:73 (call))<br />[/vs/base/common/event.ts#142:15 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L142:15 (fire))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#1096:20 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L1096:20 (call))<br />[/vs/base/common/event.ts#144:18 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L144:18 (fire))<br />[/vs/workbench/services/scm/common/scmService.ts#120:25 (registerSCMProvider)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/scm/common/scmService.ts#L120:25 (registerSCMProvider))<br />[/vs/workbench/api/electron-browser/mainThreadSCM.ts#289:37 (apply)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/api/electron-browser/mainThreadSCM.ts#L289:37 (apply))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#174:16](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L174:16)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'length' of null<br />[/vs/base/browser/ui/list/listView.ts#216:20 (length)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/browser/ui/list/listView.ts#L216:20 (length))<br />[/vs/base/browser/ui/list/listWidget.ts#862:19 (length)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/browser/ui/list/listWidget.ts#L862:19 (length))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#266:28 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L266:28 (call))<br />[/vs/base/common/event.ts#144:18 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L144:18 (fire))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#1156:30 (setVisible)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L1156:30 (setVisible))<br />[/vs/workbench/browser/parts/compositePart.ts#387:19 (hideActiveComposite)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/browser/parts/compositePart.ts#L387:19 (hideActiveComposite))<br />[/vs/workbench/browser/parts/compositePart.ts#124:22 (doOpenComposite)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/browser/parts/compositePart.ts#L124:22 (doOpenComposite))<br />[/vs/workbench/browser/parts/compositePart.ts#112:14 (openComposite)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/browser/parts/compositePart.ts#L112:14 (openComposite))<br />[/vs/workbench/browser/parts/sidebar/sidebarPart.ts#113:33 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/browser/parts/sidebar/sidebarPart.ts#L113:33 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1579:0](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1579:0)<br />
