### ISSUE TITLE
Error: Invalid index 26

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45550]
There is tons of issues like the one below (e.g. https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=b946efd8-3089-9156-aeb4-acc98dd70991) in error telemetry. Maybe another consequence of disposing the tree/list properly now?

```
Error: Invalid index 26
/vs/base/browser/ui/list/listWidget.ts#1072:10 (open)
/vs/base/browser/ui/list/listWidget.ts#510:14 (call)
/vs/base/common/event.ts#382:86 (call)
/vs/base/common/event.ts#374:73 (call)
/vs/base/common/event.ts#142:15 (fire)
/vs/base/browser/event.ts#116:25
```

**Comment by joaomoreno** [comment]
This sounds like the issue isidor has fixed, someone's using a disposed list.

cc @isidorn 

Can't do much without more stack context.

**Comment by bpasero** [comment]
@joaomoreno fyi this still shows up in builds from the 9th (e.g. https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=5777b83c-096a-5d26-49cc-bc9aa2af8d47) and the stack is actually still the same:

```
Error: Invalid index 19
/vs/base/browser/ui/list/listWidget.ts#1072:10 (open)
/vs/base/browser/ui/list/listWidget.ts#510:14 (call)
/vs/base/common/event.ts#382:86 (call)
/vs/base/common/event.ts#374:73 (call)
/vs/base/common/event.ts#142:15 (fire)
/vs/base/browser/event.ts#116:25
```
