### ISSUE TITLE
TypeError: Cannot read property 'empty' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45557]
From https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=76782e1c-306d-a7ba-4b77-09619c96442f

```
TypeError: Cannot read property 'empty' of undefined
/vs/workbench/browser/parts/compositebar/compositeBarActions.ts#213:21 (updateBadge)
/vs/workbench/browser/parts/compositebar/compositeBarActions.ts#277:8 (call)
/vs/base/common/event.ts#144:18 (fire)
/vs/workbench/browser/parts/compositebar/compositeBarActions.ts#96:25 (setBadge)
/vs/workbench/browser/parts/compositebar/compositeBar.ts#186:10 (updateActivity)
/vs/workbench/browser/parts/compositebar/compositeBar.ts#146:7 (showActivity)
/vs/workbench/browser/parts/activitybar/activitybarPart.ts#100:28 (showActivity)
/vs/workbench/services/activity/browser/activityService.ts#29:30 (showActivity)
/vs/workbench/services/progress/browser/progressService2.ts#161:36
```

**Comment by isidorn** [comment]
Not exactly sure when this can happen - looking that it only happens in 1.21 I can only assume it is related to the search to the panel change.
It seems that the activity service is trying to show progress for a composite which does not exist.

For now I could only add a null guard to not explode and silently not report any progress when trying to show progress for an unavailable composite.
