### ISSUE TITLE
Command Palette disappears when opened with "Rename Symbol" on screen

### ISSUE THREAD

**Issue by Hoishin** [Microsoft/vscode#45561]
- VSCode Version: 1.21.0
- OS Version: macOS High Sierra 10.13.3

Steps to Reproduce:

1. Press F2
2. Press F1
3. Command Palette appears for a moment and disappears

More generally,

1. Open "Rename Symbol"
2. Open Command Palette
3. Command Palette appears for a moment and disappears

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is the rename in the editor, not in the explorer -> forwarding to @jrieken 
I can repro.
