### ISSUE TITLE
Cannot save file without extension.

### ISSUE THREAD

**Issue by vinay87** [Microsoft/vscode#45560]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
blamer-vs|bea|0.2.0
path-intellisense|chr|1.4.2
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.7.1
vscode-html-css|ecm|0.1.8
vscode-svn|eli|0.1.0
vstortoise|flo|1.1.1
rest-client|hum|0.17.0
svn-scm|joh|1.18.1
restructuredtext|lex|52.0.0
Go|luk|0.6.77
MagicPython|mag|1.0.12
font-awesome-codes-css|med|0.1.1
HTMLHint|mka|0.4.0
python|ms-|2018.1.0
sublime-keybindings|ms-|3.0.2
vscode-docker|Pet|0.0.24
LiveServer|rit|3.2.1
vscode-icons|rob|7.21.0
jinja|who|0.0.8
markdown-pdf|yza|0.1.7
html-css-class-completion|Zig|1.15.0

---

Steps to Reproduce:

1. File > New
2. Save as "filename" without extension.

Reproduces without extensions: Yes/No

**Comment by tsalinger** [comment]
You are using an old version of VS Code. Please update to the [newest version](https://code.visualstudio.com/Download).
Does the problem still occur with the latest version?

**Comment by vinay87** [comment]
Just updated to the latest version. Still having problems.

**Comment by tsalinger** [comment]
Are you storing the file to a NAS device or to your local HD?
Please use the command 'disable all installed extensions' and restart VS Code.
If this fixes the issue, re-enable one extension after the other and check whether you can find the one that is causing this behavior.
