### ISSUE TITLE
Integrated terminal split breaks console output in cli progressbars (e.g. tqdm)

### ISSUE THREAD

**Issue by mhindery** [Microsoft/vscode#45567]
- VSCode Version: 1.21.0 (1.21.0)
- OS Version: MacOS High Sierra 10.13.3 (17D102)

Steps to Reproduce:

1. Start an integrated terminal with a progress bar. In my example, I'm running ipython with tqdm. Does its job.

```python
import tqdm
import time

for _ in tqdm(range(100)):
    time.sleep(1)
```

2. Split the terminal. The progress bar will now print a new line for each step instead of updating its
 line.
3. Close the second terminal. It works again as it should.

Example screencast: ![terminal_split](https://user-images.githubusercontent.com/8758073/37275992-de9a97e0-25e0-11e8-9243-2725795157d8.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@mhindery does this happen when you don't split but reduce the width of the window by about the same amount?

**Comment by mhindery** [comment]
Ah yes, it does. I never used it with my terminal window that small, so did not notice this before. It seems thus not be an issue with vscode specifically. A native terminal window can be a lot smaller before it happens than the integrated terminal, but eventually it's the same issue. Issue can be closed/deleted I guess?

**Comment by Tyriar** [comment]
Yeah it's an issue with the app you're running inside the terminal not wanting to make the progress bar work on such a small terminal then 😃
