### ISSUE TITLE
Dirty Code prompt deletes changes regardless of what you choose

### ISSUE THREAD

**Issue by Hurmeli** [Microsoft/vscode#45564]
- VSCode Version: 1.2.1
- OS Version: OS X 10.10.4

## **Summary:**

VS Code ability to detect if file you're saving over is newer is a total disaster.

I'm working on NAS and due to its nature, it asks me **every single time** to compare the files. This was bad enough on its own, but after the latest update the clicking the "check" mark to override the "newer" file no longer works and what is worse it actually deletes all the changes I've made in the file I'm editing. This means VS Code is totally unusable until this is fixed.

Also why on earth is there no option to disable this check? What the actual fuck? Pardon me if I'm wrong and there is such a setting, but after spending time going through the settings and googling about the issues, this seems to be the case. Perhaps let the user decide if they want to use this sort of thing or not, yes?

## **Steps to Reproduce:**

**1.  Open a file with some code inside, like this:**

if (using NAS) {
echo "Hello there!";
}

**2. Edit said file like this:**

if (using NAS) {
echo "Guess who is getting deleted soon!";
}

**3. Save the file, get asked if you want to write your changes because "the file on NAS is newer", confirm that yes you want to fucking save the file and watch what happens:**

if (using NAS) {
}

**4. What the actual fuck? Where did my code go? I guess VS code just decided to delete it anyway.**

This still sort of worked before the last update. Yes I would get asked if I want to override every single time, but VS code did not actually delete the lines I was editing.

**Does this issue occur when all extensions are disabled?: Yes**

**Comment by bpasero** [comment]
@Hurmeli great find, I can reproduce. Sorry for the dataloss, that should never happen.

@rebornix I think this is a regression from the PieceTable implementation, here are exact steps:
* create a file foo.txt with 2 lines
* open the file in VS Code and an external editor
* modify the second line in VS Code (e.g. add a exclamation mark at the end)
* modify the first line in external editor and save (e.g. also with exclamation mark)
* save in VS Code and get an error
* click the Compare action
* click the "Overwrite" action
=> the contents of the file is empty (see video)

The command that runs lives [`here`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/saveErrorHandler.ts#L311). I am using snapshots to update the model with the value as it is in VS Code and this value seems to be wrong.

![flicker_chrome58](https://user-images.githubusercontent.com/900690/37289826-ea8bb672-260a-11e8-9d08-d909f733edbc.gif)


/cc @alexandrudima

**Comment by rebornix** [comment]
@Hurmeli sorry for the trouble you run into and thanks for reaching out to us.

The root cause is the snapshot of Piece Tree is 100% readonly, but it should be. When building the piece tree, I tried to reuse objects as much as possible to reduce GC while snapshot is the exception. When users click `Overwrite`, following events happen

* We create snapshot from current piece tree
* Load content from disk, save to piece tree, send out revert event
* Read from the snapshot, compare with current piece tree
* Save changes to piece tree

As snapshot in the first step is dirty, which leads to a wrong result of comparison in the third step.

Again, this should not happen and sincerely sorry to @Hurmeli

**Comment by Hurmeli** [comment]
Sorry for the harsh language earlier guys. There was no big harm done on my side, just some frustration.

Is there any way to disable the check from settings and if not would be possible to add a way to do it? As I said, due to NAS I will always get asked if I want to overwrite the file and it gets old fairly fast.

**Comment by bpasero** [comment]
@Hurmeli currently not, but I have https://github.com/Microsoft/vscode/issues/13665 opened to improve that situation.
