### ISSUE TITLE
Window always scrolled down when return from another tab

### ISSUE THREAD

**Issue by Marbulinek** [Microsoft/vscode#45579]
Issue Type: <b>Bug</b>

I have always scrolled down my tab window when returned from another tab. It's really frustrating issue.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|7.70GB (0.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.5
bracket-pair-colorizer|Coe|1.0.20
vscode-eslint|dba|1.4.7
xml|Dot|1.9.2
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
vscode-diff|fab|1.1.1
vscode-npm|fkn|3.3.0
webpack|jer|2.0.2
Angular2|joh|2.14.0
Angular-BeastCode|Mik|5.2.17
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.2.0
tsimporter|pmn|1.2.14
vscode-css-peek|pra|2.1.0
vscode-wakatime|Wak|1.1.22

</details>
Reproduces without extensions

**Comment by tsalinger** [comment]
Please provide a step by step description on how to reproduce this issue.
Does this problem also occur when you have all extensions disabled?

**Comment by Marbulinek** [comment]
I was not able to simulate it again.
