### ISSUE TITLE
Double click debug variable causes rename widget to appear

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#45577]
1. Start debugging
2. Double click local variable
3. Scroll it out of view
4. Scroll it back to view

![kapture 2018-03-12 at 12 20 47](https://user-images.githubusercontent.com/22350/37281098-28378278-25f0-11e8-9a2f-21ff43bf1bcb.gif)

![kitty](https://media.giphy.com/media/hggg52hdGktgc/giphy.gif)

**Comment by isidorn** [comment]
Omg such a strange bug, might be an issue with the tree. Might be even more misterious than this cat showing up.

Notice that when you do context menu > set value the input box nicely appears.
And those actions are exactly the same, they are calling into [`setSelectedExpression`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugViewModel.ts#L76)
And for both those I get an event and I simply [refresh the tree at that element](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/variablesView.ts#L126)
Might it be that context menu stopping the world somehow does not show this behavior?

Any hints on how to fix are very welcome.

**Comment by joaomoreno** [comment]
So... what happens on double click?

**Comment by isidorn** [comment]
@joaomoreno sorry if I was not being clear, both the double click and the context menu call into setSelectedExpression.
So there is absolutely no difference between them, except the context menu showing up for the first (which works)

**Comment by joaomoreno** [comment]
Something else must be happening on one of the clicks of the double click. Some new global list handlers (open, etc) must be doing something.

**Comment by isidorn** [comment]
@joaomoreno ok that is a good idea, will investigate...

**Comment by isidorn** [comment]
@joaomoreno you suspicion was right on the money - good job. So I changed the variables controller to react ON_MOUSE_UP and that seems to fix it. I see that most tree clients react ON_MOUSE_UP and that @bpasero put comments everywhere to not change that to not break DnD. Why is that not the default behavior? And why does ON_MOUSE_DOWN miseriously break my tree refresh?

**Comment by isidorn** [comment]
p.s where does the guy keep that cat in that gif??

**Comment by bpasero** [comment]
@isidorn I think our fix is fine, this is mainly around perceived performance when clicking on an item that results in an editor opening. If you have DND it would be odd to first open the file and then you start DND, that is why I disabled it in these cases.

**Comment by joaomoreno** [comment]
![cat](https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif)
