### ISSUE TITLE
Integrated Terminal Not Working

### ISSUE THREAD

**Issue by WackyWesley** [Microsoft/vscode#45570]
- VSCode Version: 1.21.0
- OS Version: Windows 10 - 1709

Steps to Reproduce:

1. Launch VS Code
2. Launch Terminal (Ctrl+`)

Does this issue occur when all extensions are disabled?: Yes

Even after I launch Code after multiple re-installations (Using the .exe and zip) and after deleting VS Code files in AppData/Roaming, the integrated terminal does not work properly and I cannot type text into it. 

![image](https://user-images.githubusercontent.com/37066698/37277100-d468047c-2637-11e8-8244-fcd4342fb68a.png)

What do I do? I have looked at other forums that showed similar issues and followed their steps with no result. Even powershell does not work so how can I get the terminal working properly?

**Comment by WackyWesley** [comment]
This is not a duplicate of #43169 . Can you replicate it @Tyriar ?

**Comment by Tyriar** [comment]
@WackyWesley please check some things for me:

- Do you have compatibility mode on? (right click code.exe, properties, compatibility)
- Anything in the console? (Help > Toggle Developer Tools)
- What's your settings.json file?
- Did the terminal ever work? Do you know when it started? A Windows update or VS Code update?
