### ISSUE TITLE
Change desktop entry's category

### ISSUE THREAD

**Issue by msudgh** [Microsoft/vscode#45574]
I think `code` currently isn't a editor for just web development and it would be better to remove `WebDevelopment` category from `visual-studio-code.desktop ` file:
```bash
[Desktop Entry]
Exec=/opt/visual-studio-code/code %f
Icon=visual-studio-code
Terminal=false
Type=Application
Name=Visual Studio Code
Comment=Editor for building and debugging modern web and cloud applications
Categories=Development;WebDevelopment;IDE;Utility;TextEditor;
MimeType=text/plain;inode/directory;
StartupNotify=true
StartupWMClass=code
```

**Comment by Tyriar** [comment]
Ok I'm confused. It looks like it never had WebDevelopment 😕

https://github.com/Microsoft/vscode/blob/0a969c743c89459cd213fcd3cc2c8bd50449ab64/resources/linux/code.desktop#L10

**Comment by Tyriar** [comment]
I think you're using an unofficial package.

**Comment by msudgh** [comment]
Yeah, You're right.
