### ISSUE TITLE
Allow users to control quoting in tasks

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#45576]

**Comment by IAmHopp** [comment]
@dbaeumer Is there [or will there be, once it hits stable] any attribute I can use to enforce the old quoting strategy?

I'm having to include `\"` at the beginning and end of every command to get them to work in PowerShell, which is just weird.

I see you added "quoting" to "args", I don't know if that could fix it, but I'm talking about something at the "command" level.

Would appreciate some further guidance here.

**Comment by dbaeumer** [comment]
@IAmHopp yes, the new approach gives you a lot more control over what will happen in PowerShell and you will very likely don't need to do anything special anymore. For example if you want to execute `echo 'Hello World'` in a shell the task will look like this:

```
{
     "command": "echo",
     "args": [ "Helllo World" ]
}
```

and VS Code will detect that the args has space and will do a string quote. So the resulting powershell command will be `echo 'Hello World'`. You can control what we will do with the arg using a literal. So you can do as well:
```
{
     "command": "echo",
     "args": [ {
         "value": "Helllo World" 
         "quoting": "escape"
     ]
}
```

which will produce `echo Hello`` World`. You can also use weak quoting which will surround the argument with ".

**Comment by dbaeumer** [comment]
If the above example is executed in bash it will produce `echo Hello\ World` since bash uses a different escape character. So task partly abstract over the shell used. Otherwise users would need to provide different tasks not only for different OS but also for different shell uses.

**Comment by IAmHopp** [comment]
> the new approach gives you a lot more control over what will happen in PowerShell and you will very likely don't need to do anything special anymore

To be clear, I only needed to do something special [wrap commands in `\"`s] because of the new approach. In any case, the commit you pushed yesterday seems to have done what I was asking for here, which is enforce the old approach in some cases for backwards compatibility.

Can't wait to get to work and try it out.

**Comment by dbaeumer** [comment]
Yes, I broke it for yesterdays insider and fixed it for todays.
