### ISSUE TITLE
checkJs shows errors when comment does not match execution/definition

### ISSUE THREAD

**Issue by FurryX** [Microsoft/vscode#45573]
- VSCode Version: 1.21
- OS Version: Windows 8.1

Steps to Reproduce:

1. add checkJs true to jsconfig
2. make function like 
```
/**
 * @param {string} a
 * @returns {string}
 */
function fun(a){};

//and use:
fun();
```
3. get 2 errors: 
-first will be on @returns in comment because my function does not return string. I'd like to not see errors related to doc comments. It's important for me because I have a lot of functions stubs for just intellisence code completion. 
-second: usage of fun() without arguments is also marked as an error, but of course this works for javascript. I know that every function can have in doc @param(any=), which will get rid of this issue but better would be to disable this checker (also based on doc). Maybe there should be possibility to set them as a warning or even hide info?

**Comment by mjbvz** [comment]
Both of these are correct. All of the type info used by checkJS comes from JS docs so it does not make sense to disable errors related to them. For the second, if a property is optional, you must indicate this in jsdocs using `@param {string} [a]`. Usually failing to specify an argument is a mistake
