### ISSUE TITLE
Debug console not working with colors.js (node text colour library)

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#45572]
The first image is how it looks in the debug console

![screen shot 2018-03-12 at 5 20 59 pm](https://user-images.githubusercontent.com/9585787/37278276-c9568310-2619-11e8-8d97-3100eff4ad92.png)

The second image is how it looks in the VSCode integrated terminal (or normal OSX terminal)

![screen shot 2018-03-12 at 5 20 52 pm](https://user-images.githubusercontent.com/9585787/37278275-c8d8b76e-2619-11e8-8c34-183149f3b493.png)

**Comment by jpike88** [comment]
https://github.com/Marak/colors.js/issues/218

**Comment by isidorn** [comment]
Duplicate of some of https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+debug+console+colors

**Comment by jpike88** [comment]
@chrmarti would appreciate if you linked to the actual duplicate.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/21423
