### ISSUE TITLE
Integrate with OS Notification Center

### ISSUE THREAD

**Issue by jamessampford** [Microsoft/vscode#45578]
Love the new notification area, and while I cannot find another feature request nor a config option along these lines (though I'm sure someone must), but I think it would be even better if you could have a config option whether notifications should appear within VS Code, or, whether they should use the native OS notification system

**Comment by bpasero** [comment]
Unfortunately we cannot easily do this because there is no APIs to show buttons in notifications and we use notifications a lot as a replacement for modal dialogs. I have to close this.

**Comment by jamessampford** [comment]
Google Chrome can show buttons in Windows 10, and they also appear in the Windows 10 Notification List area with no problem. Can reproduce at https://tests.peter.sh/notification-generator

![image](https://user-images.githubusercontent.com/1376843/47637958-1ffa4a80-db55-11e8-912a-cf562f9f5d7d.png)

IMO if the OS doesn't support support notifications as well as buttons, then it should fall back to the internal VS Code notification system, rather than not supporting it period
