### ISSUE TITLE
Open preview to the side splits editor horizontally (wrong)

### ISSUE THREAD

**Issue by AmirSavand** [Microsoft/vscode#45581]
It doesn't work on my project:

![image](https://user-images.githubusercontent.com/4629328/37282544-dd5e9b36-2605-11e8-92c4-72d12cf1cea2.png)

But when I do it in a new window, it works :disappointed: 

- VSCode Version: 1.21.0
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Open a markdown file
2. Click on `Open Preview to the Side`

Does this issue occur when all extensions are disabled?: Yes

**Comment by AmirSavand** [comment]
It seems splitting vertically is impossible now...

**Comment by mjbvz** [comment]
You are using the [horizontal layout](https://code.visualstudio.com/docs/getstarted/userinterface#_horizontal-layout) so this is the expected behavior for side-by-side editing.

Support for more generic layouts is tracked by #14909

**Comment by AmirSavand** [comment]
I didn't know you can toggle it, anyway the icon was there and didn't work.
I toggled it and it works.
