### ISSUE TITLE
Setting to keep Sidebar and Panel open when toggling ZenMode

### ISSUE THREAD

**Issue by stoberov** [Microsoft/vscode#45582]
Hi Team,

This is probably related to #36888. 

I use Zen Mode quite a lot, and when I turn it on I find myself hitting the shortcuts to display Sidebar and Panel (as I need them most of the time). Some time later, I would exit Zen Mode, and then again turn it on a few seconds later. At that time, the Sidebar and Panel would not show up by default, even though I had them displayed the last time.

This could just be me, but I think some sort of **"zenMode.rememberLast": true** would be a nice touch.

Thanks!

**Comment by isidorn** [comment]
ZenMode is rembering the state when it entered. So if it hide the panel it will bring it back once you exit zen mode and same for Sidebar.

Please let me know what are the reproducable steps and how would you expect zen mode to behave?
Since what you are describing above sounds like designed behavior.

**Comment by stoberov** [comment]
Thanks for reply! I confirm I am happy with the existing "**exit zen mode**" behavior. My concern has to do with the "**re-enter zen mode**" behaviour.

Steps to reproduce:
1. Open VSCode (with or without a project, it is the same)
2. Enter ZenMode (F11)
3. At this point, only the editor part is displayed. Now, display the Sidebar (View: Toggle Side Bar) and then display the Panel (View: Toggle Panel). They appear as expected.
4. Exit ZenMode. Everything is how it was before entering ZenMode (expected behavior).
5. **Enter ZenMode again**. At this point, the Sidebar and Panel are no longer visible (even though they were turned on manually during the last ZenMode "session"). This could just be me, but I would expect there is some setting to keep the "**last ZenMode layout**", because personally I switch between ZenMode and "regular mode" very often - and I need to re-display the Sidebar and Panel.
 
Hope the above makes sense. It is not an issue per se, but would be a rather nice setting I hope.

**Comment by isidorn** [comment]
Thanks for the clarification. I understnad what you want, however zen mode sessions are independent in between and this was a design decision.
Will keep this open as a feature request for now

**Comment by ghost** [comment]
There is a setting for hideStatusBar, hideActivityBar, and hideTabs.  Is there a specific reason that an additional 'hideSideBar' setting cannot be implemented?  It would simplify my workflow as I also find myself opening the sideBar immediately after going into zen mode.
