### ISSUE TITLE
when I require pacakge in .ts file, there are not intellisence

### ISSUE THREAD

**Issue by WangPengJu** [Microsoft/vscode#45584]
app.ts
let a = require("http");

vocode remind me "a" is typeof "any"

app2.js
let a = require("http");

vscode remind me "a" is typeof "http"

it is confuse me. why .ts file have no intellisence with require().

**Comment by WangPengJu** [comment]
i want use "http" package in namspace with "amd". but typescript don't allow use import in namespace. so i use require(), but have no intellisence.

**Comment by mjbvz** [comment]
You need to install typings for node: `npm install --save-dev @types/node`
