### ISSUE TITLE
Suggestion: command to create new file *at root*

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#45588]
We already have a `explorer.newFile` command which allows you to create a new file in the currently focussed directory.

Since v1.21, [it is now possible to create a file/folder by entering a path](https://code.visualstudio.com/updates/v1_21#_create-multiple-folders-in-the-explorer).

With this new ability, I would like a command that works like `explorer.newFile` *but from the root of the project*, instead of the currently focussed folder.

We can then use the new ability to enter paths to create the file in any folder in my project.

Currently I have this workflow to do this:
1. `workbench.files.action.focusFilesExplorer`
2. `escape` to move focus from currently focussed folder to root
3. `explorer.newFile`
4. enter path

This new command should encapsulate steps 1-3.

**Comment by isidorn** [comment]
1 and 3 could be done via extension. The issue is that 2 can not be done using an extension afaik

**Comment by OliverJAsh** [comment]
There is an extension: https://github.com/dkundel/vscode-new-file. However, it seems a shame not just to use the existing functionality in VSCode, which is so close to being useful.

**Comment by isidorn** [comment]
Then I will have to close this as this is covered by the extension and we are trying to code vscode lean and clean
