### ISSUE TITLE
resolveDebugConfiguration is not passed the correct (closest) workspace folder when they are nested

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45580]
If you have a WorkspaceFolder inside a WorkspaceFolder, [I'm told](https://github.com/Microsoft/vscode/issues/45399#issuecomment-371860738) that `getWorkspaceFolder(Uri)` will always return the closest one.

As such, it seems reasonable to assume other APIs behave the same. However, if I hit `F5` with a file open that exists in multiple workspace roots, the debug configuration provider gets called with the top-level folder and not the closest one.

Eg.:

```
my_projects                   // WorkspaceFolder
  |- my_flutter_project       // WorkspaceFolder
    |- my_flutter_script.dart
  |- my_dart_project          // WorkspaceFolder
    |- my_dart_script.dart
```

When I press `F5` with `my_flutter_script.dart` open, I get given the `my_projects` WorkspaceFolder which means I don't detect that the project is a Flutter project.

**Comment by DanTup** [comment]
Fix looks good in Insiders to me! Is it too late/insignificant for the Feb recovery release? Solves a big issue for my users with debugging projects in sub folders; would be awesome if I could include the fix (which relies on this) in the next release.

**Comment by isidorn** [comment]
It will be included in the march release, not for frebruary recovery since it is too risky.
Thanks for verifying

**Comment by DanTup** [comment]
Understood; thanks for the quick response!
