### ISSUE TITLE
Problema con inspector código

### ISSUE THREAD

**Issue by pedami** [Microsoft/vscode#45586]
Issue Type: <b>Bug</b>

Hola, llevo algún tiempo queriendo dar el salto a VS Code, pero por unas cosas o por otras no aca de funcionar bien.
Este es un mensaje que se arroja al intentar hacer un "Ir a la definición o Go To" encima de una class css en un html, este es el error:

[Error - 13:27:02] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'offset' of null
  Code: -32603

Gracias, epero vuestros comentarios.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 x 3400)|
|Load (avg)|3, 3, 3|
|Memory (System)|24.00GB (3.32GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
beautify|Hoo|1.3.0
format-indent|Kas|1.3.0
ActiveFileInStatusBar|Ros|1.0.3
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.7
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.1
php-intellisense|fel|2.2.9
auto-rename-tag|for|0.0.15
vscode-mysql|for|0.2.3
local-history|gay|0.0.3
vscode-colorize|kam|0.6.16
theme-monokai-pro-vscode|mon|1.1.5
vscode-apache|mrm|1.1.1
mssql|ms-|1.3.0
csharp|ms-|1.14.0
laravel-blade|one|1.17.0
laravel-extension-pack|one|0.2.0
laravel5-snippets|one|1.4.0
vscode-css-peek|pra|2.1.0
vscode-icons|rob|7.21.0
ftp-kr|rua|1.3.16
laravel-artisan|rya|0.0.16
vscode-fileutils|sle|2.8.1
highlight-matching-tag|vin|0.4.4
JavaScriptSnippets|xab|1.5.0

(7 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Google translate:
> Hi, I've been wanting to make the leap to VS Code for some time, but for some things or for others, it's not working well.
This is a message that is thrown when trying to do a "Go to the definition or Go To" on top of a class css in an html, this is the error:

> [Error - 13:27:02] Request textDocument/definition failed.
Message: Request textDocument/definition failed with message: Cannot read property 'offset' of null
Code: -32603

> Thank you, I await your comments.

**Comment by aeschli** [comment]
Can you add a small code sample where you see this?

You say this only shows up when extensions are enabled.
Can you find out which extension is causing that?
My guess is `vscode-css-peek`

The issue should be filed against that extension.
