### ISSUE TITLE
Allow extensions to contribute ruler settings (to match configured line lengths)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45587]
Some extension have settings for line-lengths (eg. where to wrap when formatting). Currently it's not easy for them to contribute a ruler at that size. While we can contribute a default setting for `editor.rulers` in `configurationDefaults` it would overwrite any other rulers a user has set. It would be better if we could supplement them.

**Comment by DanTup** [comment]
@alexandrudima That's a good idea, but I don't think it solves this very well. I want (as an extension) to contribute a rule at a position that I know from my config. Eg. the user sets `dart.lineLength` in their settings and my extension causes a ruler to appear at that length (the user shouldn't need to go and configure rulers - most never will, but they would be happy if we show a ruler at the place where we automatically wrap when they save).

**Comment by alexandrudima** [comment]
@DanTup There are different philosophies. I personally belong to the camp of folks who want to be **in control** of every aspect. I don't want for an extension to make decisions on my behalf, as good and as well meaning these decisions appear.

Anyways, I suppose you could use configuration editing to edit on behalf of the user the user settings to add rulers for the language. It is considered polite to prompt the user before editing the settings... i.e.

```
"[dart]": { "editor.rulers": [ 80 ] }
```

**Comment by DanTup** [comment]
Yeah, I'm kinda in two minds about it myself. I thought it'd be nice to indicate to users where we'd automatically wrap and have them not have to maintain two values, but since it's unlikely to change maybe it's not a big problem.

There are a bunch of Code defaults that cause issues (or people to report bugs) so I was going to add a "recommended settings" page to our website listing the things we think people might want to turn off (letting them read and make the decisions) so maybe I'll just include this there and encourage new users to check it out on first run or something.

**Comment by sandy081** [comment]
@DanTup After going through the discussion I see there is no action to be taken on VS Code side. Hence closing this.
