### ISSUE TITLE
Input box: do not close when pressing ENTER on invalid input

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45583]
It's confusing that when `showInputBox` is given an invalid value that pressing `<enter>` just closes the box and returns `undefined`. I've had users that have said things are broken because they typed a value and pressed enter - their value was invalid and they didn't notice the prompt (because they typed and pressed enter quickly).

Either we should be able to tell when the user pressed `<enter>` on an invalid value, or they shouldn't be able to - the box should just stay visible with the validation error until the fix it or use `<esc>` to cancel.

**Comment by chrmarti** [comment]
This was fixed a while ago.

**Comment by DanTup** [comment]
Yep, works for me. Thanks :)
