### ISSUE TITLE
Terminal: environment variables must be strings

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#45590]
The [docs](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TerminalOptions) mentions that's possible to pass an object of environment variables to `vscode.window.createTerminal`. This seems to be working only if the values in that object are strings.

For instance if I pass this object:

```javascript
{
  "TEST_STRING": "string",
  "TEST_NUMBER": 123,
  "TEST_BOOL": false
}
```

And then I execute `env | grep "TEST_"`, I expect the output to be:

```
TEST_STRING=string
TEST_NUMBER=123
TEST_BOOL=false
```

But instead it's:

```
TEST_STRING=string
```

Basically non-string values are ignored. I think all the values should be wrapped into a `String ()` call.

**Comment by Tyriar** [comment]
👍 opening to PRs

**Comment by xamm** [comment]
Hi @Tyriar,
I would like to take on this issue as my first contribution to vscode.

**Comment by Tyriar** [comment]
As designed, see https://github.com/Microsoft/vscode/pull/45703#issuecomment-373465040 for details.

**Comment by Tyriar** [comment]
As mentioned in https://github.com/Microsoft/vscode/pull/45703#issuecomment-374242008, we can enforce this in settings on our side. We should do this for VS Code and @fabiospampinato's ext.
