### ISSUE TITLE
Inconsistent problem counters

### ISSUE THREAD

**Issue by rsalvador** [Microsoft/vscode#45592]
Issue Type: <b>Feature Request</b>

VSCode uses different conventions for the problem counters in the problems view  and in the status bar.
- The problems view displays: 1 2 ... 999 1K 2K ... 10K+ and the tooltip shows the actual number.
- The status bar displays:
  - for errors/warnings: 1 2 ... 99+ and the tooltip doesn't show the actual number.
  - for infos: 1 2 ... (always the actual number), the tooltip doesn't show the actual number.

<img width="118" alt="problems-view" src="https://user-images.githubusercontent.com/1301827/37289239-6f7228fc-25c6-11e8-8d84-ee697374e728.png">
<img width="108" alt="status-bar" src="https://user-images.githubusercontent.com/1301827/37289244-752ca04c-25c6-11e8-9290-ed1f9012049c.png">

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

**Comment by dbaeumer** [comment]
@sandy081 assigning to you. I personally would adopt the status bar to the problems view. Everything over 99 is not very informative anyways.
