### ISSUE TITLE
OSS Build - Failed to tokenize input error with certain languages

### ISSUE THREAD

**Issue by jel-massih** [Microsoft/vscode#456]
Certain laungauges syntax highlighting do not work for me running the OSS development build on Windows 7. The release build works fine with these languages however.

So far I have noticed it with XML, Clojure, VB, TypeScript and F#

Quite possibly is an issue with vscode-textmate or oniguruma.

Throws the following:

```
C:\[VSCODE_PATH]\node_modules\vscode-textmate\node_modules\oniguruma\build\Release\onig_scanner.node: Error: %1 is not a valid Win32 application.
C:\[VSCODE_PATH]\node_modules\vscode-textmate\node_modules\oniguruma\build\Release\onig_scanner.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\[VSCODE_PATH]\node_modules\vscode-textmate\node_modules\oniguruma\lib\oniguruma.js:4:17)
    at Object.<anonymous> (C:\[VSCODE_PATH]\node_modules\vscode-textmate\node_modules\oniguruma\lib\oniguruma.js:65:4)
    at Module._compile (module.js:434:26)
The mode has failed while tokenizing the input.
```

**Comment by joaomoreno** [comment]
Just looks like `onig_scanner.node` can't be loaded.

After a proper `git clean -xfd node_modules`, make sure your run `./scripts/npm.sh install` to compile the native node dependencies against the right version of v8. This will work. Reopen if it doesn't.

**Comment by jel-massih** [comment]
I did a fresh install and is still occuring.

The onig_scanner.node file does exist in the build/release folder, And I am using `scripts\npm install`

Doing identical install steps on a Windows10 PC and everything works fine.

@joaomoreno Unable to re-open

**Comment by joaomoreno** [comment]
Oh sorry about that, thought anyone could reopen stuff.

Do you have Visual Studio installed? Do you mind providing the output of `.\scripts\node.bat install`?

**Comment by jel-massih** [comment]
Yeah, I have VS 2012, 2013 and 2015 installed

Here is the output:
[output.txt](https://github.com/Microsoft/vscode/files/41793/output.txt)

**Comment by joaomoreno** [comment]
How did this go?

> I will try copying the build folder from an installation that does work.

**Comment by jel-massih** [comment]
Ok so using the `onig_scanner.node` from the release build fixed this issue....

Im fine with closing this out as it will be incredibly hard to reproduce, especially if nobody else is experiencing this.

**Comment by jel-massih** [comment]
I also tried building the onig_scanner.node file manually with VS2010 (v100) and VS2013 (v120) (using the binding.sln solution) and same issue happens with both versions.

**Comment by joaomoreno** [comment]
Pretty strange. The only thing that comes to mind is bit architecture, but we pretty much set 32 bits [all](https://github.com/Microsoft/vscode/blob/master/scripts/npm.bat#L6) [the](https://github.com/Microsoft/vscode/blob/master/build/gulpfile.vscode.js#L114) [way](https://github.com/Microsoft/vscode/blob/master/build/gulpfile.vscode.js#L114).

Closing it, hope you can still work in your Windows 10 box.
