### ISSUE TITLE
Something wrong with update :/

### ISSUE THREAD

**Issue by RootKlawiter** [Microsoft/vscode#45607]
hey, that's me again with 'the same' problem. After someone helped me and told I need to reinstall VS Code, I did it, but today I get a message to update a VS Code. I clicked 'Install now', because why not? And then started this... 
![msvsc](https://user-images.githubusercontent.com/30440603/37299983-20944fa8-2625-11e8-956f-f2f0648b259f.PNG)
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1803890/vscode-inno-updater.log)
here you are, error message and .log file

**Comment by joaomoreno** [comment]
@RootKlawiter Just to confirm, Code was running fine after that, correct?

**Comment by RootKlawiter** [comment]
Yeah, it was working fine, but the problem still occurred 🤐

**Comment by joaomoreno** [comment]
dupe of #44911
