### ISSUE TITLE
Linux: Changes to process.env from main are not reaching renderer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4560]
Related to #4558

We do a good job in getting the user environment and injecting that all the way to the renderer, but we fail to pick up the actual process.env as it exists on the main side.

The code is in: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/main.ts#L250

Imho if we want to make sure that process.env travels to renderer and its forked processes, we need to capture the environment as late as possible before opening a new window and merge both user environment and process.environment at that time.

@joaomoreno thoughts?

**Comment by bpasero** [comment]
This would also mean to revisit this change: https://github.com/Microsoft/vscode/pull/4559/files

**Comment by joaomoreno** [comment]
I don't understand. [The snippet you linked to](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/main.ts#L250) does exactly that: it merges the user's configured environment into the main process'. Renderer processes will inherit such environment.

**Comment by bpasero** [comment]
@joaomoreno here is an example where it does not work: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/index.html#L111

Why do you have to update process.env on the renderer when you say our patching works?

**Comment by bpasero** [comment]
Related: https://github.com/atom/electron/issues/3306

**Comment by joaomoreno** [comment]
Let's revisit this once we figure out a common configuration service.

**Comment by joaomoreno** [comment]
Just found #4558...

**Comment by bpasero** [comment]
Well that was the initial motivation to file this bug.

**Comment by joaomoreno** [comment]
The link would've been helpful. It is clear to me now.

**Comment by bpasero** [comment]
@joaomoreno ok sorry. yes, we do have some manual code here and there to workaround this issue, I think Dirk is not the only one there.

**Comment by joaomoreno** [comment]
Keeping the manual workaround code.
