### ISSUE TITLE
No launch.json: cannot find a program to debug 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#45603]
1. Open a folder with no launch.json
2. Open a javscript file and hit F5 -> notice the error "cannot find a program to debug"

It is coming from [here](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/configurationProvider.ts#L39)

This nicely works in stable.
Looking at the vscode side everything seems to behave as before thus assigning this first to you

**Comment by weinand** [comment]
@isidorn I cannot reproduce with Insiders

**Comment by isidorn** [comment]
Can no longer reproduce as well. Sorry for the false alarm.
Will keep my eyes open in case it happens again
