### ISSUE TITLE
Cannot launch Chrome Debugger after latest update

### ISSUE THREAD

**Issue by maxfurman** [Microsoft/vscode#45600]
Issue Type: <b>Bug</b>

I can no longer launch or attach to the Chrome debugger process after the latest VSCode update. When I open the dev tools I see the error `Activating extension 'msjsdiag.debugger-for-chrome' failed: Cannot find module '/Users/Max/.vscode/extensions/msjsdiag.debugger-for-chrome-4.2.0/out/src/extension'.`

I have tried uninstalling and reinstalling the extension multiple times.

Steps to reproduce:
1. Install the debugger-for-chrome extension
2. Add a launch.json file with the following:
```{
  "version": "0.2.0",
  "configurations": [
    {
    "name": "Chrome",
    "type": "chrome",
    "request": "launch",
    "url": "http://localhost:4000",
    "webRoot": "${workspaceRoot}/src",
    "sourceMapPathOverrides": {
      "webpack:///src/*": "${webRoot}/*"
    }
]}
```
3. Attempt to launch a chrome debugging session.
4. The notification "Debug adapter process has terminated unexpectedly" will appear.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.22GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
JSDocTagComplete|Hoo|0.0.2
jsx|Twe|0.0.1
clojure|avl|0.9.8
flow-for-vscode|flo|0.7.3
auto-rename-tag|for|0.0.15
ruby-linter|hoo|1.0.0
vscode-rust|kal|0.4.2
cpptools|ms-|0.15.0
debugger-for-chrome|msj|4.2.0
Ruby|reb|0.17.0
slim|sia|0.1.2

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Could you look at the contents of `/Users/Max/.vscode/extensions/msjsdiag.debugger-for-chrome-4.2.0/`?

Does `out/` exist, what's in out/src?

**Comment by maxfurman** [comment]
out/src does exist, and has three files in it: 

- extension.nls.zh-cn.json 
- extension.nls.zh-tw.json 
- utils.js

The first two look like Chinese localization files, which makes me think that the problem might be that the rest of the languages that should be included are missing somehow.

**Comment by roblourens** [comment]
There are a bunch of files missing. Those are the last 3 files in that folder alphabetically. I'm guessing the extension update process was interrupted as it was deleting the previous version. Also guessing this is related to the extension update, not the vscode update.

You should be able to reinstall the extension to fix it, but if you do that, I'd appreciate if you copy the `msjsdiag.debugger-for-chrome` folder somewhere else to help us investigate. 

Is `msjsdiag.debugger-for-chrome/package.json` still present? Which version does it have in it?

cc @joaomoreno

**Comment by roblourens** [comment]
Oh actually this is most likely another instance of https://github.com/Microsoft/vscode/issues/43813 which is fixed in Insiders. I was thinking it was windows-only but that is not true. Just try to reinstall the extension, no need to keep the old copy around.

**Comment by maxfurman** [comment]
I was able to get the debugger working again by `rm -rf`'ing that folder and then reinstalling through vs code. Thanks for the help!
