### ISSUE TITLE
SelectBox: height of 20px crops text (Windows)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45606]
Now:
![image](https://user-images.githubusercontent.com/900690/37299022-6850e228-2622-11e8-87ed-a239225bc3eb.png)

Ideal:
![image](https://user-images.githubusercontent.com/900690/37299032-6fdba29e-2622-11e8-8d4c-169596ac79ac.png)

I am not sure why, but I think this came in via https://github.com/Microsoft/vscode/commit/82b87c760d8cc79bdd93d4e7259310124882fe4d

**Comment by isidorn** [comment]
Didn't we start using a custom select box for windows in the meantime which should my 2 year old commit should not have any affect on.
Also assigning to @cleidigh

**Comment by bpasero** [comment]
@isidorn no, the selectbox is native. the only thing that is custom is the dropdown with the entries!

**Comment by isidorn** [comment]
I have removed the height, not sure why I added it - maybe so it gets a bid higher on the mac. However no need for that. I have also updated the margin to make sure it is still centered. Tried it on mac and win and seems fine now.
