### ISSUE TITLE
Debug launch error: Unexpected token { in JSON at position 8. Stopping the debug adapter.

### ISSUE THREAD

**Issue by stanf0rd** [Microsoft/vscode#45616]
Issue Type: <b>Bug</b>

Bug found in these versions of VSC:
1.21.0-1520420608 stable 
1.22.0-1520835382 beta

Steps to Reproduce:

1. Install VSC
2. Install ms-vscode.cpptools
3. Create launch.json
4. Compile your program (no matter how)
5. Press F5

VS Code version: Code - Insiders 1.22.0-insider (5450fdc79778b5a76a27ea7e5fd68e9ebbe44107, 2018-03-12T06:14:34.973Z)
OS version: Linux x64 4.15.0-10-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 870)|
|Load (avg)|0, 0, 1|
|Memory (System)|15.55GB (9.89GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0

</details>
Reproduces without extensions: No

**Comment by howientc** [comment]
Exactly the same issue. Running 1.21 on ubuntu.
cpp tools is version 0.15.0

**Comment by llisauskas** [comment]
Same issue, VSC 1.21, cpptools 0.15.0.
Just running under Ubuntu 18.04 beta.

Are there any issues with pevious versions of VSC? 
What was the most recent version that you had this working?

**Comment by isidorn** [comment]
Please file it here https://github.com/Microsoft/vscode-cpptools

fyi @sean-mcmanus @pieandcakes

**Comment by pieandcakes** [comment]
@isidorn is there any logging we can turn on in VSCode  to see what is being passed? We aren't able to duplicate this and the Json coming through seems to be fine from our side's logging. We have been getting reports of this from 1.21 and newer builds of VSCode only.

**Comment by isidorn** [comment]
@pieandcakes currently we do not log the communication between vscode and the adapter on the vscode side, but each adapter imlements this as it sees fit. For example @weinand implemented this for node. However in your c++ docs I see this https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md#logging so it seems to be possible by adding "logging": "trace" to the launch.json.
If that is not enough you have some users on this issue so feel free to interect with them directly.

For the future we can write this in vscode logs, for that please create a new feature request.
Thanks

**Comment by stanf0rd** [comment]
@isidorn 
I test it on VSCode version 1.20.0, error occures too.

**Comment by GlacierFox** [comment]
Problem persists on Version 1.21.1 , Ubuntu 18.04 beta.
There's a problem with libfreetype6 which was causing an error with how text is rendered in VS Code. I rolled it back to the previous version which fixed the problem but the debugging problem still persists.
[Unexpected token { in JSON at position 8. Stopping the debug adapter.]

I get the feeling the issue with the font rendering and the Json file may be related due to the way VSCode may be passing the Unicode characters or something, I don't know.

**Comment by stanf0rd** [comment]
I found a reason of that error - the new version of gnome-terminal (3.27). After downgrading to version 3.24 from Ubuntu 17.10 no error occures.

**Comment by GlacierFox** [comment]
How did you downgrade if you don't mind me asking? I can't seem to get the correct version. For some reason it's reverting me back to 3.21 which doesn't work for me.

**Comment by stanf0rd** [comment]
1) I removed gnome-terminal and gnome-terminal-data packages with apt
2) I installed both .deb packages (version 3.24.2) from
    - here: launchpad.net/ubuntu/artful/amd64/gnome-terminal/3.24.2-0ubuntu4
    - and here: launchpad.net/ubuntu/artful/amd64/gnome-terminal-data/3.24.2-0ubuntu4
3) Hold these packages in apt (sudo apt-mark hold <package_name>)

**Comment by GlacierFox** [comment]
Superb. Thanks for that!

**Comment by pieandcakes** [comment]
@GlacierFox Can you confirm that @stanf0rd's fix works for you when you try it? Also are you launching VS Code from gnome-terminal? I'm trying to see where/how gnome-terminal is causing this problem.

**Comment by GlacierFox** [comment]
@pieandcakes Yes I can confirm this works now. It seems to be the newest version of Gnome Terminal that is the problem which I was upgraded to when installing the 18.04 beta. Everything was fine earlier when running 17.04.

There's a closed report on the corrupted text issue but it's still apparent on my end. I have temporarily resolved it by downgrading libfreetype6 but has unfortunately caused errors in the text in other programs. (Thunderbird and Firefox).

**Comment by pieandcakes** [comment]
@GlacierFox So we were finally able to duplicate it with @stanf0rd 's instructions. It seems like gnome-terminal changed in 3.27 how they report their errors. In previous versions, their errors come through stderr which are eaten and not passed back to VS Code (by accident), but with 3.27, they started posting their error messages to stdout which was inadvertently being sent back to VS Code. The error you were getting was VS Code trying to parse an invalid protocol message as @wardengnaw and I found.

@isidorn , is it possible to have that error be more detailed so that figuring out this scenario would be easier? @wardengnaw will provide more info.

**Comment by WardenGnaw** [comment]
@isidorn 

When ```const rawData = JSON.parse(body)```, it only complains about the token it received. It would be helpful to also have logging about message body it received. 

This is in:
https://github.com/Microsoft/vscode/blob/ab1669f8987c585c260e824584e3bf79c82fc064/src/vs/workbench/parts/debug/node/v8Protocol.ts#L152

**Comment by isidorn** [comment]
@WardenGnaw makes perfect sense, I created a new issue to track that https://github.com/Microsoft/vscode/issues/46317
