### ISSUE TITLE
1.21 missing in RPM repo

### ISSUE THREAD

**Issue by tomassvoboda** [Microsoft/vscode#45619]
- VSCode Version: 1.21
- OS Version: Fedora 27

Steps to Reproduce:

1. Add RPM repository as advertised here: https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
2. `sudo dnf install code` installs 1.20 instead of 1.21

Does this issue occur when all extensions are disabled?: Yes

**Comment by tomassvoboda** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/45500

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/45868
