### ISSUE TITLE
Intrusive notifications

### ISSUE THREAD

**Issue by mojaveazure** [Microsoft/vscode#45613]
Issue Type: <b>Bug</b>

The new notification system sends excess notifications without any way to disable them.  They have all been marketing notifications, which are intrusive rather than helpful. There's no real steps to reproduce, one simply needs to use VSCode 1.21 and wait for a notification to happen. The ones I've seen are asking me to install extensions, both with and without extensions enabled. This new system needs to allow for an off-switch so that notifications aren't spamming users while people are trying to work.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2491)|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (0.52GB free)|
|Process Argv|/usr/share/code/code edityper/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.2.5
wdl|bro|1.0.0
python|ms-|2018.2.1
cpptools|ms-|0.15.0

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@mojaveazure can you share a screenshot of which notification you are referring to? If they come from us you should be able to stop them by clicking the little gear icon and selecting "Do not show again".
