### ISSUE TITLE
Hide the notifications center icon from the statusbar if there are no notifications

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#45612]
If there are no notifications, a "full" bell icon will still be displayed in the statusbar, it's not even clickable since there are no notifications to see.

As @bpasero [said](https://github.com/Microsoft/vscode/issues/38435#issuecomment-344685905):

> space in the status bar is already very limited, so I would not want to bloat that space anymore than needed

This icon, when there are no notifications, is completely unnecessary in my view, shouldn't we show it only when needed?

**Comment by bpasero** [comment]
We think that hiding the icon is not a good UX idea. Instead we will tackle https://www.github.com/Microsoft/vscode/issues/44509
