### ISSUE TITLE
VS Code Insiders installs always in the OS language despite of language selection during installation

### ISSUE THREAD

**Issue by carlosmunozrodriguez** [Microsoft/vscode#4561]
- VSCode Version: 0.10.12-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Download VS Code Insiders from https://code.visualstudio.com/insiders
2. Install using a different language than the OS. (Tested with selecting English and with a Windows 10 in Spanish)
3. Open VS Code Insiders. It will be on your OS language instead of the one you selected.

**Comment by dbaeumer** [comment]
The language selection dialog is currently only for the Setup wizard. The question is whether we should create a locale.json file based on this information. I opt to do so.

@chrisdias, @egamma  what is your opinion
@joaomoreno would that be possible from the InnoSetup installer.

**Comment by joaomoreno** [comment]
I suggest to set up Inno to automatically detect the language at installation time, just like what we do. The picker would only show up in ambiguous cases and it only has an effect in the setup itself.

**Comment by dbaeumer** [comment]
+1

I assign to you then.

**Comment by joaomoreno** [comment]
Closing as we track this in another repo.

**Comment by carlosmunozrodriguez** [comment]
Can I ask which repo?
Also a question: How will it detect the language? Which language? I have also installed regular English VS Code in a Spanish OS

**Comment by joaomoreno** [comment]
@carlosmunozrodriguez We have another repository in which we track the things that ultimately make VS Code into an MS branded product. This is one of those things. More information about this [here](https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005).

There are helpful links about understanding how language detection will happen:
- [Languages](http://www.jrsoftware.org/ishelp/topic_languagessection.htm)
- [LanguageDetectionMethod](http://www.jrsoftware.org/ishelp/index.php?topic=setup_languagedetectionmethod)
- [ShowLanguageDialog](http://www.jrsoftware.org/ishelp/index.php?topic=setup_showlanguagedialog)
