### ISSUE TITLE
File events: branch updates as well as working tree feature does not work since update a few weeks ago

### ISSUE THREAD

**Issue by kenguie** [Microsoft/vscode#45625]
- VSCode Version: 1.21.0
- OS Version:  Mac OS 10.13.3

Steps to Reproduce:

1. Make changes in file and save
2. Go to source control
3. Click on file to check working tree
4. Make a change to another file and save
5. Changes under source control does not update for a loooong time
6. When it does update, click to see the working tree
7. It does not show for a loooong time - sometimes 10 minutes. 
8. As added problem, right click on a file and try to discard changes. 
9. First one usually works fine.
10. Try to discard changes in another file, no prompt shows up as well as there is no way to discard changes for a loooong time (sorry, i didn't time it, it's always at least a few minutes)

I have been loading the Atom editor in order to discard changes and look over diffs because VS code cannot do this anymore. 
I have 2 macbooks and one imac, this problem extends through them all.

Does this issue occur when all extensions are disabled?: Yes/No

YES! Also found a new error, - opened 3 files and made changes to each of them sequentially. 
Saved after each change, under source control, under changes, nothing is registered. 
Waited 10 min and it still did not register any changes.

**Comment by joaomoreno** [comment]
Does the file explorer reflect file system changes? If you delete a file from your workspace, does it disappear from the file explorer?

If you run with `code --verbose`, do you see file events logged in there?

**Comment by kenguie** [comment]
Yep, that seems to work. Will check more today but seems to be improving with today’s update. I’ll have to verify

**Comment by kenguie** [comment]
Verified still not working. It registers the first change to the system but then if you change a second file, it does not show up in the file explorer. 

I usually have to close VS code and reopen to see the changes or I continue to use Atom to see my diffs and to discard changes.

**Comment by kenguie** [comment]
Seems that it may be a problem with the "code helper"? 
I tried --verbose and just got: 
[main 8:41:40 AM] Sending env to running instance...
[main 8:41:40 AM] Sent env to running instance. Terminating...
[main 8:41:40 AM] Lifecycle#kill()

After this though, code helper had 2 instances running and were taking over 100% of my resources, fans came on like crazy ! 

I actually could not get any updates to vs code ... it even said there were no source repositories (if i remember the wording right)

In order to calm my system down, I had to close VS code but also kill the code helpers. 

When I reopened VS code it showed my changes in files, but making changes to those files didn't get updated in the file explorer. 

This is really hampering my coding, hope you can find the issue.

**Comment by kenguie** [comment]
I don’t think it’s quite the same, this problem started only two or three weeks ago, since your duplicate issue was opened over a year ago, does that mean I need to find a new code editor?
