### ISSUE TITLE
Problem with string VS Code C++

### ISSUE THREAD

**Issue by Craix** [Microsoft/vscode#45622]
- VSCode Version: 1.20.1
- OS Version: 6.3.9600 Windows 8.1 

```
#include <iostream> 

using namespace std; 

int main()
{
    cout<<"Hello worlds"<<endl; // that works 

    string text = "Hi, worlds "; // here i have problem 

    cin.ignore();
    cin.get();
    return 0; 
}
```
Hello, it's first time when i try to use VS Code <normaly i use VS 2017>. Follow this tutorial "
https://code.visualstudio.com/docs/languages/cpp" i try to compile and debug my code but then i got error with "string variable". (i'm not sure about it, but programs works good without this and get error when i try add and use string variables). 

Error code: 
`
=thread-group-added,id="i1"
GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
=cmd-param-changed,param="pagination",value="off"
[New Thread 1040.0x1648]
gdb: unknown target exception 0xc0000139 at 0x77d8d572
ERROR: During startup program exited with code 0xc0000139.
The program 'C:\...\main.exe' has exited with code 0 (0x00000000).
`

**Comment by tsalinger** [comment]
Please continue the discussion in [this issue](https://github.com/Microsoft/vscode-cpptools/issues/1678) in the cpp repo.
