### ISSUE TITLE
Intellisense includePaths error

### ISSUE THREAD

**Issue by TheKingdomScribe** [Microsoft/vscode#45627]
Issue Type: <b>Bug</b>

When using C, after configuring the include paths with all the gcc libaries, whenever I use <ctype.h>, many functions get the same problem. I get red squiggles with the problem, "identifier "_ISupper" is undefined" for the functions isupper, islower and isdigit. I believe this happens for most functions available in this library as well. The program runs fine, though intellisense still thinks that part of the header is undefined even though it doesn't cause any problems. Just a slight bug I thought I'd mention.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.13.0-21-generic

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
This issue has been moved to the [cpp extension repository](https://github.com/Microsoft/vscode-cpptools/issues/1677). Please continue the discussion there.
