### ISSUE TITLE
Support setExpression request in Debug Adapter protocol

### ISSUE THREAD

**Issue by changsi-an** [Microsoft/vscode#45621]
- VSCode Version: 1.21.0
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Yes

We hope that the vscode debug adapter protocol can include the `setExpression` request that is described [here](https://github.com/Microsoft/VSDebugAdapterHost/wiki/Editable-'Watch'-Window-Values)

The main purpose of this request is to allow modifying a "watch" expression. Even though VS Code does not support modifying a watch expression today. Many other debugger clients who implement VS Code debug protocol involve business of modifying a watch expression. Eg. Visual Studio who can debug Node, Chrome and Edge using VS Code debug protocol.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-debugadapter-node#167
