### ISSUE TITLE
Google Japanese Input (IME) on Mac - Suggestions Overlap w/ Text

### ISSUE THREAD

**Issue by chibicode** [microsoft/vscode#45629]
- VSCode Version: 1.21.0
- OS Version: macOS 10.13.1

### Steps to Reproduce:

1. Install Google Japanese Input https://www.google.co.jp/intl/ja/ime/
2. Activate it
3. Open a new VSCode instance
4. Type `konnnichiha` on keyboard, then hit enter, and do it again a few times
5. Expected: the suggestions should never overlap w/ text. Actual: the suggestions overlap w/ text.

### See the GIF:

![screen recording 2018-03-12 at 08 03 pm](https://user-images.githubusercontent.com/992008/37320434-f050704a-2630-11e8-98ad-751e9846abb2.gif)

Does this issue occur when all extensions are disabled?: Yes

### Notes:

This is not an issue with the default Japanese IME that comes w/ macOS.

---

## Update (Sep 27, 2018): Workaround

This setting seems to [fix the issue](https://github.com/Microsoft/vscode/issues/45629#issuecomment-424568495). (You'll lose some functionalities)

![](https://user-images.githubusercontent.com/7225783/46054765-af41c600-c183-11e8-98bf-4f32c50a294a.png)

![](https://user-images.githubusercontent.com/876920/46108263-7b21d180-c192-11e8-945f-73d1f23b1a4e.png)

**Comment by Yamotty** [comment]
same here

**Comment by mashriq** [comment]
same here

**Comment by CM-Kajiwara** [comment]
Same Here

**Comment by ramya-rao-a** [comment]
@jrieken The suggestion box that shows up in this case is not the one for suggestWidget. This seems like a native control which I dont believe VS Code controls

cc @rebornix @octref

**Comment by rebornix** [comment]
I think it is probably caused by the position adjustment of the textarea, Google IME tries to put the candidate list at the proper position, but I don't have a stable reproduce yet.

**Comment by chibicode** [comment]
Sorry, I am a new user to VSCode so not sure if this is a regression.

**Comment by octref** [comment]
@rebornix I can repro it consistently.

![image](https://user-images.githubusercontent.com/4033249/37367627-32cb32d0-26c1-11e8-919a-1582e9aa8dac.png)

**Comment by chibicode** [comment]
Seems like the issue might be on CodeMirror:
https://github.com/codemirror/CodeMirror/issues/4089

**Comment by chibicode** [comment]
I also searched through Twitter, and people have been reporting this since April 2015. Definitely not a regression. @ramya-rao-a @rebornix 

https://twitter.com/shohaga/status/593568407301193728
https://twitter.com/hiedar83/status/593676327665860608
https://twitter.com/tyamaz/status/593728561392984064

**Comment by hiramatsu** [comment]
Same Here

@rebornix

![2018-08-24 12 03 06](https://user-images.githubusercontent.com/7225783/44562727-f52af900-a795-11e8-8c42-3f9a792f92f5.png)
![2018-08-24 12 03 35](https://user-images.githubusercontent.com/7225783/44562736-ffe58e00-a795-11e8-8abe-1321e7c68161.png)

**Comment by chibicode** [comment]
@rebornix @octref Is there anything I can do to help?

Also saw this reported on Teratail, a Japanese Stackoverflow clone
https://teratail.com/questions/143100

**Comment by hiramatsu** [comment]
※日本語で失礼します。

暫定的(temporary)な回避策(workaround)ですが、「Google 日本語入力 環境設定」の「サジェスト」タブの
・入力履歴からのサジェスト自動表示を有効にする
・リアルタイム変換を有効にする
のチェックを外せば被らなくなりました。(上記機能は失われますが…)
<img width="637" alt="2018-09-26 11 51 35" src="https://user-images.githubusercontent.com/7225783/46054765-af41c600-c183-11e8-98bf-4f32c50a294a.png">

**Comment by chibicode** [comment]
Translating what @hiramatsu said:

Temporary workaround: go to Google Japanese Input preferences,

<img width="271" alt="screen shot 2018-09-26 at 6 58 30 pm" src="https://user-images.githubusercontent.com/992008/46072789-2eec8680-c1be-11e8-8d97-b221af8e1833.png">

go to サジェスト ("suggest") and uncheck

- 入力履歴からのサジェスト自動表示を有効にする (disable suggestion from input history)
- リアルタイム変換を有効にする (disable live conversion)

Then it no longer overlaps.

**Comment by rebornix** [comment]
@hiramatsu @chibicode thanks for your help. This issue was caused by how we implement our editor (virtualize everything but has a tiny textarea around the virtual cursor) and Google IME doesn't work the same as the OS builtin IME. I don't have a good idea how to hint Google IME about the position but your solution works perfectly for this issue.

For anyone who is using English as system language, the preference with the workaround will look like below:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/876920/46108263-7b21d180-c192-11e8-945f-73d1f23b1a4e.png">

**Comment by chibicode** [comment]
@rebornix thanks for the follow-up!

Just for completeness: Google maintains "a subset of Google Japanese Input in the form of source code under OSS license without any warranty nor user support" at [google/mozc](https://github.com/google/mozc) ([more explanation](https://github.com/google/mozc/blob/master/docs/about_branding.md)), though they're [not accepting pull requests at the moment](https://github.com/google/mozc/blob/master/PULL_REQUEST_TEMPLATE.md).

**Comment by yujikuroki** [comment]
Same here

**Comment by jedipunkz** [comment]
same here

**Comment by zkwhandan** [comment]
same here,
 I am using windows 10, and same bug using different IME.
![无标题](https://user-images.githubusercontent.com/12523553/61586365-c1727200-aba4-11e9-8f16-04bbc85ec8cc.png)
