### ISSUE TITLE
Some ideas about rust-lang on VSCode

### ISSUE THREAD

**Issue by NateLing** [Microsoft/vscode#45628]
I have created an [issue](https://github.com/Microsoft/vscode/issues/42145) about rust-lang syntax highlight suggestion for VSCode. The rust-lang grammar based on  [zargony/atom-language-rust](https://github.com/zargony/atom-language-rust) project. The problem is that zargony look like not enough care about [Issues](https://github.com/zargony/atom-language-rust/issues) and [pull requests](https://github.com/zargony/atom-language-rust/pulls). I think the best way to upgrade rust-lang to official project, just like [vscode-go](https://github.com/Microsoft/vscode-go) project.

Rust-lang have an official [RLS](https://github.com/rust-lang-nursery/rls) implement , rust-analysis and other unofficial tools. So, could VSCode do that?

**Comment by mjbvz** [comment]
Rust support is already coming from the community. If there is a better grammar out there that we can use, please let us know
