### ISSUE TITLE
When environment memory pressure gets high, Intellisense crashes and never recovers

### ISSUE THREAD

**Issue by tigerhawkvok** [Microsoft/vscode#45624]
Issue Type: <b>Bug</b>

Running a python editor and training images increases memory pressure to almost 100 GB between physical and cached memory. 

This eventually crashes Intellisense, stopping code completion and documentation and more.

The only way to recover this is to restart the editor.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|31.91GB (15.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aga|0.5.0
bracket-pair-colorizer|Coe|1.0.20
empty-indent|Dmi|0.2.0
jupyter|don|1.1.4
gitlens|eam|8.1.1
vscode-html-css|ecm|0.2.0
LogFileHighlighter|emi|2.1.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.9
mdmath|goe|2.1.0
gc-excelviewer|Gra|2.0.20
cypher-query-language|jak|1.0.2
latex-workshop|Jam|3.14.0
nbpreviewer|jit|1.0.0
php-cs-fixer|jun|0.1.57
indentation-level-movement|kai|1.1.1
stata-enhanced|kyl|1.3.0
vscode-emacs-friendly|lfs|0.8.2
rainbow-csv|mec|0.2.0
code-beautifier|mic|1.7.2
vscode-apache|mrm|1.1.1
vscode-less|mrm|0.6.3
mssql|ms-|1.3.0
python|ms-|2018.2.1
cpptools|ms-|0.15.0
color-highlight|nau|2.3.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|2.9.0
stylelint|shi|0.34.0
vscode-autohotkey|sle|0.2.2
latex-support|tor|1.5.1
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by tsalinger** [comment]
This seems to be a python extension related problem.
Please continue the discussion [here](https://github.com/Microsoft/vscode-python/issues/1057).
