### ISSUE TITLE
suggestion: add "reinstall" to the extension command/gear menu

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#45626]
Suggest to add "Reinstall" to the list of commands when clicking on the gear for an extension.

![image](https://user-images.githubusercontent.com/1487073/37314484-93aee796-2611-11e8-8734-f3407761f2d3.png)

**Comment by sandy081** [comment]
@chrisdias `Reinstall` action is a developer action for trouble shooting. What is the need to show it in the UI?

**Comment by chrisdias** [comment]
I've seen this issue (a potentially corrupted install of an extension) show up so many times in the past couple of weeks that maybe this action should be more prominent.

**Comment by sandy081** [comment]
Yes, there is an issue with corrupt install and I provided a fix here - https://github.com/Microsoft/vscode/issues/43813. 

Once it is fixed, this action will be used only when there are issues (Troubleshoot). After that having that action in the UI will not be helpful.

**Comment by octref** [comment]
> Once it is fixed, this action will be used only when there are issues (Troubleshoot). After that having that action in the UI will not be helpful.

I agree. We should make uninstall-reinstall work as expected instead of introducing overlapping actions.

**Comment by chrisdias** [comment]
sounds good.
