### ISSUE TITLE
History Previous keybind description typo

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#45623]
Issue Type: <b>Bug</b>

Noticed a small typo at [debug.ts#37](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debug.ts#L37). There's an extra 'e' between first and debug. This also shows up in the Keyboard Shortcuts view under the "when" column for the `History Previous` keybind.

---

VS Code version: Code - Insiders 1.22.0-insider (5450fdc79778b5a76a27ea7e5fd68e9ebbe44107, 2018-03-12T05:15:51.483Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by isidorn** [comment]
@mattacosta thanks a lot. Next time also feel free to submit a PR.
