### ISSUE TITLE
Debug type case sensitive

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4563]
_From @rebornix on March 16, 2016 5:19_

While implementing a debug adapter, we need to declare what debug type it is like 

```
"contributes": {
		"debuggers": [
			{
				"type": "Ruby",
				"label": "Ruby Debugger",
                                ...
```

It works perfectly when user set type as `Ruby` in their launch config while it breaks when users type `ruby` with the lowercase `r`. It somewhat confuses users of my tiny plugin. 

Meanwhile if I attempt to change the type value from `Ruby` to `ruby`, my extension will never be backwards-compatible. Is there any solid reason that we make it Case-Sensitive or is there any workaround? You know that we are likely to name our debugger as the language name, `Python` for any python related code, `PowerShell` for ps code, but users might get blocked if they type `python` or `Powershell`.

_Copied from original issue: Microsoft/vscode-debugadapter-node#15_

**Comment by weinand** [comment]
I like the idea, but we have to make sure that no extension is already relying on case sensitive debug types.

**Comment by rebornix** [comment]
I just went through all debuggers available on marketplace, and make a brief summary of their debugging type:

* [Go](https://marketplace.visualstudio.com/items?itemName=lukehoban.Go): go
* [PowerShell](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell): PowerShell
* [Python](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python): python
* [Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome): chrome
* [PHP](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug): php
* [Cordova](https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools): cordova
* [ReactNative](https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native): reactnative
* [Unity](https://marketplace.visualstudio.com/items?itemName=Unity.unity-debug): unity
* [Debug](https://marketplace.visualstudio.com/items?itemName=webfreak.debug): gdb
* [Ruby](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby): Ruby
* [Mono](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug): mono
* [NativeScript](https://marketplace.visualstudio.com/items?itemName=Telerik.nativescript): nativescript
* [jsirdebugger](https://marketplace.visualstudio.com/items?itemName=muji.jsirdebugger): jsir

Others are not real debuggers actually. Existing debuggers won't have conflicts if we make the change. (lowercase is adopted by most of debugger writers however)

**Comment by isidorn** [comment]
Type is now case insensitive. Please note that a warning will still appear in user's `launch.json` if he enters a type with wrong casing. The reason for this is that our json schema currently do not support having a set of case insensitive values, only a set of values. I think this limitation is fine
