### ISSUE TITLE
can't debug with ts-node

### ISSUE THREAD

**Issue by deepred5** [Microsoft/vscode#45637]
- VSCode Version: 1.21.0
- OS Version: win10 
Today I update the  vscode， then I found the debug can't work with ts-node

`launch.json`
```
{
   
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "启动程序",
            "program": "${workspaceFolder}/start.js"
        }
    ]
}
```
`start.js`
```
require("ts-node/register");
require("./1.ts");
```

`1.ts`
```
var a = 1;
var b = 1;
console.log(a);
```
I can't debug in the 1.ts now.

**Comment by deepred5** [comment]
VSCode Version: 1.20.0 is ok , just the 1.21.0 doest't work well

**Comment by weinand** [comment]
What version of node.js are you using?

**Comment by deepred5** [comment]
@weinand  8.9.3

**Comment by deepred5** [comment]
I can't add breakpoint, but add `debugger` can works

**Comment by roblourens** [comment]
This is probably https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464, please see the comment there and try in the next Insiders build.
