### ISSUE TITLE
How to configure `checkJs` for configuration files in a TypeScript project

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode#45638]
Possibly a feature request.

I am aware of `javascript.implicitProjectConfig` options, but unfortunately I cannot configure options other than `checkJs` and `experimentalDecorators` (e.g. `noUnusedLocals` and `noUnusedParameters`).

Is there a way to add a `jsconfig.json` file to the TypeScript project that will work with Code?

**Comment by mjbvz** [comment]
`implicitProjectConfig` only applies if you don't have a jsconfig or tsconfig. Just add:

```json
{
	"compilerOptions": {
		"checkJs": true,
		"allowJs": true
     }
}
```

In your `tsconfig` to enable type checking in js files that are part of the project

**Comment by vilic** [comment]
@mjbvz Hi, the problem is that those configuration files does not belong to the TypeScript project (e.g. webpack config and scripts), so I cannot add them to `tsconfig.json`.

**Comment by mjbvz** [comment]
For that, create a [`jsconfig.json`](https://code.visualstudio.com/docs/languages/javascript#_javascript-project-jsconfigjson) instead that lives alongside your tsconfig. You'll also need to disable `allowJS` in the `tsconfig` or explicitly manage which files are in which project using [`include`, `exclude`, and `files`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)

**Comment by vilic** [comment]
@mjbvz Thanks for the reply but that was the first thing I tried, and it's not working.

![image](https://user-images.githubusercontent.com/970430/37498221-085a351c-28f8-11e8-86f1-d8b4c2f29dc9.png)
