### ISSUE TITLE
sigterm on nexus7

### ISSUE THREAD

**Issue by petervrichards** [Microsoft/vscode#45633]
Issue Type: <b>Bug</b>

Bog standard first flutter app. get a sigterm

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|15.43GB (6.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.10.0
fs-flutter-snippets|fra|0.1.3

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Please provide steps on how to reproduce this bug.
Also, which of your extensions is causing this?

**Comment by petervrichards** [comment]
Sorry, I thought you got logs on this. 

I am using completely bog standard Windows 10 professional. 

Standard implementation of Flutter install. Visual Code + Flutter extensions. Flutter doctor - no errors. Using Android Emulator Nexus 7 API 23. 
First Flutter App - no changes. Flutter run - I get the sigterm when the app tries to transfer the app to the emulator. No errors from output. 
I cannot find Android API24 emulator available for download. 

peter richards

**Comment by petervrichards** [comment]
more info re sigterm 
Resolving dependencies... 26.7s 
Running 'gradlew assembleDebug'... 4.9s 
Built build\app\outputs\apk\debug\app-debug.apk (24.6MB). 
Installing build\app\outputs\apk\app.apk... 10.1s 
I/FlutterActivityDelegate( 1233): onResume setting current activity to this 
E/flutter ( 1233): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(39)] Failed to setup Skia Gr context. 
D/skia ( 1233): [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened 
D/skia ( 1233): [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened 
Syncing files to device Nexus 10 KitKat... 4.0s 
same as android emulator 
this is a Bliss emulator 
peter richards

**Comment by tsalinger** [comment]
Thanks for the additional info!
I moved this thread to the dart-code repository.
Please continue the discussion [there](https://github.com/Dart-Code/Dart-Code/issues/690).
