### ISSUE TITLE
Pass "Visual Studio Code" as a new attribute "clientName" in the "initialize" request

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45647]
Implements DAP protocol addition https://github.com/Microsoft/vscode-debugadapter-node/issues/166 for VS Code.

**Comment by isidorn** [comment]
@weinand can you please ping me once you add clientName to the `InitializeRequestArguments`

**Comment by weinand** [comment]
@isidorn done

**Comment by isidorn** [comment]
Note that I am passing the product name which will be `Visual Studio Code` for insiders and stable, but when running out of source this will be `Code - OSS` which is correct as there might be other vscode distributions in theory.

**Comment by weinand** [comment]
Sounds good!
