### ISSUE TITLE
html tags being removed if it does not contains text

### ISSUE THREAD

**Issue by rolero** [Microsoft/vscode#45640]
- VSCode Version: 1.21.0
- OS Version: Windows 10

Steps to Reproduce:

1. Added  `<i class="fas fa-angle-double-down"></i>` in a html file
2. Save file
3. `<i>` tag disappears.
4. Added  `<i class="fas fa-angle-double-down">test</i>` in a html file
5. Save file
6. `<i>` tag stays.

This problem also occurs at other tags like `<div>`, `<span>`, etc.

Does this issue occur when all extensions are disabled?: No, but when I uninstall all extensions and run VS code it still does not work.

**Comment by aeschli** [comment]
I asume you have `"editor.formatOnSave": true` in your settings?

I'm not able to reproduce when [run without any extension](https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled).

> Does this issue occur when all extensions are disabled?: No, but when I uninstall all extensions and run VS code it still does not work.

What does not work when you uninstall all extensions and run VS code?
