### ISSUE TITLE
GIT login doesn't work anymore

### ISSUE THREAD

**Issue by RosiersRobin** [Microsoft/vscode#45649]
- VSCode Version: 1.21.0
- OS Version: Winows 10 Education (Version 1709, build 16299.248)

Steps to Reproduce:

1. Just make a file
2. Clone a git repo
3. Try to push to the repo

Does this issue occur when all extensions are disabled?: **Yes**/No

So,

I have a random Git issue with vs code. It pormpts for the password and email/username from github (giving the correct ones), it asks for it multiple times, but then it returns this error;

`fatal: HttpRequestException encountered.`

**Comment by joaomoreno** [comment]
What happens if you try to clone from the command line? `git clone ...`

**Comment by RosiersRobin** [comment]
It just continiously prompts my username and password now on a push... 

![img](https://image.prntscr.com/image/GjawqwGdT_C8zZOM4X-DHQ.jpeg)

It doesn't save the credntials

**Comment by joaomoreno** [comment]
What happens if you try to clone from the command line? `git clone ...`

**Comment by RosiersRobin** [comment]
it's fixed in the latest release, I don't know what it was, but now, it works again.

the `git clone ...` just works perfectly, it asks also for the username and pass.
