### ISSUE TITLE
Switching of Chinese input method is abnormal.

### ISSUE THREAD

**Issue by tingxuelouwq** [Microsoft/vscode#45641]
When I switch back to vscode from other pages, such as chrome, enter Chinese, the first character will be entered in English, and then the characters will be entered into Chinese.
![image](https://user-images.githubusercontent.com/12440829/37332413-9c3e07e0-26e1-11e8-950e-b563eda45051.png)

**Comment by Stone-Zeng** [comment]
The same problem for me. I use both rime and sogou IME.

**Comment by nomanous** [comment]
I use Microsoft IME and it also has this bug

**Comment by yelantingfeng** [comment]
same problem

**Comment by rebornix** [comment]
This is already fixed since we updated Electron.
