### ISSUE TITLE
Ctrl Shift O not working

### ISSUE THREAD

**Issue by Jazcash** [Microsoft/vscode#45646]
- VSCode Version: 1.21.0
- OS Version: Windows 10

Ctrl Shift O for the Go To Symbol bind used to work for me in VSCode, but now it does nothing. My friend is having the same issue (with no extensions installed). This appears to be similar to https://github.com/Microsoft/vscode/issues/40470

I'm using default bindings:

![binding](https://user-images.githubusercontent.com/1434248/37334717-91c2a524-26a4-11e8-9ff1-bfa01dac1ed6.PNG)

Nothing showing in the console either.

**Comment by aeschli** [comment]
It depends on the language mode of the editor that is currently open. Not all language support `Go To Symbol` out of the box. You might need an extension.

What's the language mode of the editor you have open?

**Comment by Jazcash** [comment]
Javascript

**Comment by mjbvz** [comment]
1. Does this repo when all extensions are disabled?
1. Does the `Go to Symbol in file` command work?

Also, please provide repo steps and some example code

**Comment by Jazcash** [comment]
1. Still occurs with all disabled
2. Yep, works fine

Actually I think I've just found something interesting. Using http://en.key-test.ru/, when I do `Ctrl + Shift + I` or `Ctrl + Shift + P`, the letter keys light up onInputDown but with `Ctrl + Shift + O` it only detects onInputUp. Same issue with `Ctrl + Shift + K` and `Ctrl + Shift + L` but most others seem to be fine.

Running Windows 10.0.14393

**Comment by mjbvz** [comment]
@alexandrudima Looks like this is keybinding related? Can you please take a look

**Comment by jeanp413** [comment]
I'm having the same issue in Windows 10 10.0.16299 with javascript and typescript files.
I have tested it on a Ubuntu VM and it works fine there.
I don't have any extensions installed.

**Comment by alexandrudima** [comment]
@Jazcash @jeanp413 

Can you please check:

1. That there are no other keybindings for "ctrl+shift+o" (ctrl+k ctrl+s and search for "ctrl+shift+o"):
![image](https://user-images.githubusercontent.com/5047891/38054501-74e2fd84-32d7-11e8-939b-188b6041af69.png)

2. What happens when you use the on-screen keyboard:
![kapture 2018-03-28 at 22 32 04](https://user-images.githubusercontent.com/5047891/38054661-ea9eecc2-32d7-11e8-8bb1-6cd614b8ad4c.gif)

3. What does VS Code detect when you press "ctrl+shift+o": 
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by jeanp413** [comment]
@alexandrudima 
1. Go to symbol in file is the only command bound to "ctrl+shift+o".
2. Using the on-screen keyboard doesn't get recognized either.
3. Pressing "ctrl+shift+o" on the Define Keybinding popup just detects "ctrl+shift+" using either the keyboard or the on-screen keyboard.

PS. "ctrl+shift+l" isn't being detected either.

**Comment by alexandrudima** [comment]
@jeanp413 If "ctrl+shift+o" shows "ctrl+shift+" in the keybinding input, it means that the keypress is not reaching VSCode. Most likely, something installed at the level of the OS is capturing this keybinding.

Are you able to use this keybinding successfully in other software on the same machine?

**Comment by jeanp413** [comment]
@alexandrudima you were right.
It was my amd gpu software (Radeon Settings) that was capturing those keybinding.
Thanks.

**Comment by alexandrudima** [comment]
@Jazcash do you also have an AMD gpu capturing ctrl+shift+o ?

**Comment by Jazcash** [comment]
Yep, seems like that's the issue!
