### ISSUE TITLE
sass-maps are showing errors and are incorretly highlighted

### ISSUE THREAD

**Issue by VitorLuizC** [Microsoft/vscode#4564]
- VSCode Version: 0.10.11
- OS Version: WIN10 x64 - Home

Steps to Reproduce:

1. Write a sass-map
![image](https://cloud.githubusercontent.com/assets/9027363/13957459/5a2e4cbe-f02b-11e5-8f9f-56ece966ac6a.png)

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/1758
