### ISSUE TITLE
Contributing a menu item to explorer/context only when right clicking a folder

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#45648]
As per title, is there a way to do that? Being the `when` thing practically undocumented I couldn't find any info on how to do this.

I this can't be done as of today, I think this should be implemented, there's no point in contributing a menu item to files if one's only targeting folders.

**Comment by JokerDan** [comment]
@fabiospampinato The 'when' clause is documented but it is a little hard to find.

https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

The when clause of 'explorerResourceIsFolder' may be what you are looking for.

**Comment by isidorn** [comment]
Yup `explorerResourceIsFolder`
We accept PRs that improve docs
@gregvanl fyi for documentation missing

**Comment by fabiospampinato** [comment]
@JokerDan nice, thanks! Has this been added recently? I'm pretty sure it was undocumented before.

**Comment by isidorn** [comment]
Was probably added with the multi select work in explorer a couple of milestones ago.
