### ISSUE TITLE
Node version not switched with runtimeVersion setting

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#45658]
We have a native module compiled with node v6.9.1. We use v8.9.4 in another project, so `nvm` is currently set to v8.9.4. I added in the `runtimeVersion` property to the launch configuration, and I get the error that the module was compiled for a different version of node - it doesn't appear to be attempting to switch versions with `nvm`. If I manually switch to v6.9.1 in the terminal and then launch the project, it runs as expected.

- VSCode Version: 1.21.0
- OS Version: Windows 10

Steps to Reproduce:

Launch config:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug All",
      "type": "node",
      "request": "launch",
      "runtimeVersion": "6.9.1",
      "protocol": "inspector",
      "args": [
        "--nolazy",
        "${workspaceRoot}/debugall.js"
      ],
      "cwd": "${workspaceRoot}/",
      "env": {
        "NODE_ENV": "development"
      },
      "sourceMaps": false,
      "console": "internalConsole",
      "outputCapture": "std",
      "skipFiles": [
        "<node_internals>/**",
        "**/node_modules/**"
      ]
    }
  ]
}
```

Error on launch:

```sh
Error: The module '\\?\C:\dev\project\node_modules\fast-xml2js\fast-xml2js\fast-xml2js.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
```

```sh
PS C:\dev\project> nvm ls

  * 8.9.4 (Currently using 64-bit executable)
    6.9.1
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Works for me. 

![2018-03-13_15-06-56](https://user-images.githubusercontent.com/1898161/37346670-3249f09e-26d0-11e8-9e68-7bc6db49c0fc.png)

With this launch config:
```ts
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "runtimeArgs": [ "--version" ],
            "outputCapture": "std",
            "runtimeVersion": "7.9.0"
        }
    ]
}
```

I get this:
![2018-03-13_15-07-54](https://user-images.githubusercontent.com/1898161/37346707-52a2cec4-26d0-11e8-8f53-37dbdab3b8f3.png)

What debug console output are you seeing?

**Comment by jdforsythe** [comment]
The problem appears to be `"protocol": "inspector"`.

Try this `launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      //"protocol": "inspector",
      "runtimeArgs": [
        "--version"
      ],
      "outputCapture": "std",
      "runtimeVersion": "7.9.0"
    }
  ]
}
```

It will work and display "v7.9.0" **but** if you un-comment the "protocol" line, it will display "v8.8.1"

**Comment by weinand** [comment]
Aha, you are running in this problem: https://github.com/Microsoft/vscode/issues/44640

This is fixed in Insiders.
