### ISSUE TITLE
Installing extension via .vsix no longer working.

### ISSUE THREAD

**Issue by JokerDan** [Microsoft/vscode#45651]
- VSCode Version:
Insider Build.
![image](https://user-images.githubusercontent.com/1098786/37337752-2e6230d6-26ad-11e8-8f36-f62f2eae2894.png)
- OS Version:
![image](https://user-images.githubusercontent.com/1098786/37337761-31e4bf80-26ad-11e8-9769-87a1806ec20e.png)

Steps to Reproduce:

1. Open VSCode (With/Without admin privileges.)
2. Attempt to install .vsix package

Does this issue occur when all extensions are disabled?: Yes

I am getting the following message, which at first I thought was a windows privilege issue but it is still occurring with VSCode launched on windows with escalated privileges. Company group policy settings has my user account set up as a local Administrator on any machine I log onto.

This is an extension I have built and just made changes to, once I had finished dev/testing of functionality I would create a package via `cmd> vsce package` - Install the package via the extensions and 'install from .vsix' option. This no longer seems to be working.

I have also tried renaming and then uninstalling the previous version of the extension in case it was an issue around the existing one. No dice.

`
EPERM: operation not permitted, rename 'C:\Users\username\.vscode-insiders\extensions\.companyName.extensionName-0.1.1' -> 'C:\Users\username\.vscode-insiders\extensions\companyName.extensionName-0.1.1'
`

**Comment by JokerDan** [comment]
Another thing to note, manually extracting the 'extension' folder, renaming and popping it into the extension directory manually works fine and the extension is working perfectly.

**Comment by sandy081** [comment]
Can you please double check the version on which this is happening? Because code that is causing this error is not there in version `1.21.0`. This is recent code and issue was occurring only in insiders and got fixed.

This issue is known (in insiders) - because of Windows Defender and fixed [here](https://github.com/Microsoft/vscode/issues/43813#issuecomment-372570381). Please update to latest insiders and try.

**Comment by JokerDan** [comment]
@sandy081 apologies I had attached the wrong version information.

Here;
![image](https://user-images.githubusercontent.com/1098786/37342000-44d73fce-26bb-11e8-8aa2-985817bfb615.png)

I had a pending update so I grabbed that, still happening.
![image](https://user-images.githubusercontent.com/1098786/37342097-7b241e30-26bb-11e8-9968-74c48a875f5a.png)

**Comment by sandy081** [comment]
I see. I think I know why. It is because the folder with same name exists and hence rename is failing. I should be deleting the folder (with same name) before rename.

**Comment by JokerDan** [comment]
@sandy081 Yes, so on the updated insider build, I deleted the extension completely and then installed from .vsix and it worked. So currently it is better than it was, but not fixed. Cheers!
