### ISSUE TITLE
The dockerfile editor shows the contextual help in a really annoying and aggressive way.

### ISSUE THREAD

**Issue by andrask** [Microsoft/vscode#45656]
Issue Type: <b>Bug</b>

The dockerfile editor pops up the contextual help dialog (e.g. for the RUN command) while typing.  This is annoying, it covers the text below and it moves with the cursor.  Just don't show this popup at all.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.4.0-116-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3549)|
|Load (avg)|0, 0, 0|
|Memory (System)|15.56GB (2.98GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
python|ms-|2018.2.1
java|red|0.20.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Please continue the discussion in [this thread](https://github.com/Microsoft/vscode-docker/issues/236) in the docker repository.
