### ISSUE TITLE
[sass] @error and !global are showing as errors

### ISSUE THREAD

**Issue by VitorLuizC** [Microsoft/vscode#4565]
- VSCode Version: 0.10.11
- OS Version: WIN10 x64 - Home

Steps to Reproduce:
1. Use `!global` or `@error` in a .scss file.
   ![image](https://cloud.githubusercontent.com/assets/9027363/13957751/5b1b204c-f02c-11e5-9d7c-787fc482734c.png)

**Comment by nicky-lenaers** [comment]
Any idea of when this would be fixed? Having the same issue.

**Comment by mrmlnc** [comment]
Now you can disable the SCSS validation use `"scss.validate": false` or offer your help (PR) to https://github.com/Microsoft/vscode-css-languageservice.

**Comment by MankalMR** [comment]
Same issue. Would like to see this fixed.
