### ISSUE TITLE
Highlight capturing groups when searching using regex

### ISSUE THREAD

**Issue by habovh** [microsoft/vscode#45665]
When searching using regex, I think it would be useful to differentiate highlighted parts that matches capturing groups in the search results.
This would allow for easier regex replace as well.

In addition to #42715, the captured values recalled using `$n` in the replace field could also benefit from some kind of highlight/color change, for even easier replace.

**Comment by thedonquixotic** [comment]
I'd like to +1 this.

**Comment by Ixohoxi** [comment]
Absolutely agree with this request. Being able to see each capture group within each match would be extremely helpful.

**Comment by RichardJFoster** [comment]
Agreed. I just ran into a scenario where this would have been wonderfully helpful. Instead, it's LinqPad to the rescue. :-)

**Comment by roblourens** [comment]
Unfortunately this isn't really feasible. Would need ripgrep support which is probably not likely.

**Comment by Hiestaa** [comment]
Sad to see this feature request won't be addressed, I was looking for a way to do this precisely. It would make vscode really useful to test and debug custom RegExps if you found a way to bring this feature to the product.

**Comment by StoryDevOffical** [comment]
we still need this tiny custom here

**Comment by Snailedlt** [comment]
Is this possible to implement as an extension perhaps?
