### ISSUE TITLE
Multicursor paste with matching number of clipboard lines doesn't behave as expected

### ISSUE THREAD

**Issue by mrwigster** [Microsoft/vscode#45660]
I would like multi-line paste within multiple cursors to behave the same as Sublime Text.
If the number of multi cursors == number of lines copied, paste 1 line per cursor.

I notice this is similar to this "solved" issue:
https://github.com/Microsoft/vscode/issues/16155

However, I think I actually want the outcome to be the opposite of the way it was fixed.

Current outcome:
![Image of multi cursor paste in VS Code](https://media.giphy.com/media/8w3iLkNo0qvL9I9kky/giphy.gif)
Desired outcome (Sublime Text3) :
![Image of multi cursor paste in Sublime Text](https://media.giphy.com/media/oVpu8IAGTv1oGTT2kr/giphy.gif)

- VSCode Version: (1.21.0)
- OS Version: 10.13.3

Steps to Reproduce:

1. Copy x number of lines
2. Paste into x number of cursors

Does this issue occur when all extensions are disabled?: Yes

**Comment by waroy** [comment]
+1

**Comment by alexandrudima** [comment]
Fixed via #46440
