### ISSUE TITLE
end keyword no longer inserted when defining methods in ruby methods and do...end blocks 

### ISSUE THREAD

**Issue by tylerchamberland** [Microsoft/vscode#45668]
- VSCode Version: 1.21.0
- OS Version: Windows 10, macOS High Sierra

Steps to Reproduce:

1. Open a file with Ruby file type (*.rb)
2. Define a method using `def method`
3. Press "enter"

Result: method body is indented, but the required end keyword is not inserted (it was inserted previously)

This also occurs when using `do...end` blocks - end is not inserted like before.
Does this issue occur when all extensions are disabled?: Yes

**Comment by tsalinger** [comment]
This seems to be a ruby specific issue.
Please continue this discussion here: https://github.com/rubyide/vscode-ruby/issues/300.
