### ISSUE TITLE
Webview API - css properties with partial or absolute url() don't work

### ISSUE THREAD

**Issue by rwnkl** [Microsoft/vscode#45669]
VSCode Version: 1.21
OS Version: Windows 10 Pro v.1709

Stylesheet loads properly with vscode-workspace-resource, but all relative URLs in the sheet (for example, background-image: url(pic.svg)) or absolute URLs with scheme vscode-workspace-resource do not work.

**Comment by mjbvz** [comment]
You need to set a [`<base href="vscode-workspace-resource:/path/to/workspace/">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base). We do not configure one by default
