### ISSUE TITLE
Gear button doesn't work for empty folder

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45662]
VS Code Insiders:
Windows (but might be problem on macOS as well)

- open empty folder in VS Code
- switch to debug viewlet
- press gear icon

Observe: nothing happens.

This error shows up in the dev console:

![2018-03-13_14-58-49](https://user-images.githubusercontent.com/1898161/37346305-455c11d6-26cf-11e8-9b54-0422123a6d11.png)

**Comment by isidorn** [comment]
Fixed on latest out of source a15c15d958
