### ISSUE TITLE
Support filing issues against extensions within the issue reporter

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#45673]
Add the ability to report issues with installed extensions

**Comment by DonJayamanne** [comment]
Would it be possible to provide some extension points to this. 
E.g. if a user is reporting an issue against extension `x`, then extension `x` can request additional information from the user.

This is very useful at least for the [Python Extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python), where we'd like to determine the version of Python the user has.

**Comment by RMacfarlane** [comment]
@DonJayamanne Yes, this would be a great place for extension points! Ideally the info sent from the reporter and even the UI should be extensible. I don't think the first pass of this feature will have this as there needs to be more planning on what the API looks like.

Do you have any other examples of additional information that would be useful?

**Comment by DonJayamanne** [comment]
These are some of the information we generally request. I believe all of the following are generic and would apply to all extensions (possibly making them optional).

* When debugging we ask users to upload their `launch.json`
* We ask users to upload their workspace settings `settings.json`
* We try to identify whether a user is working in a multi-root workspace
* We ask for errors that are displayed in the `console window` (`Help -> Toggle Developer Tools`)


Finally here are some questions specific to the Python extension:
* Python version (& distribution if applicable, e.g. Anaconda): XXX
* Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX 
* Relevant/affected Python packages and their versions: XXX
* Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

**Comment by brettcannon** [comment]
The stuff we currently request in our [issue template](https://github.com/Microsoft/vscode-python/blob/master/.github/ISSUE_TEMPLATE.md) covers what we typically ask for. Basically we ask for platform info, a bunch of Python-specific details, code that reproduces the issue, and then the usual Output and Console stuff. After that we often ask for a person's `settings.json` and `launch.json`. And finally after that sometimes a screenshot or video of what's occurring.

**Comment by RMacfarlane** [comment]
@DonJayamanne @brettcannon Thanks for the additional info! I've filed https://github.com/Microsoft/vscode/issues/46726 to track this.
