### ISSUE TITLE
No view in default application

### ISSUE THREAD

**Issue by cubbinj** [Microsoft/vscode#45672]
Issue Type: <b>Bug</b>

there is no view in default application. i might be doing it wrong though. can someone help me please?

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU N3350 @ 1.10GHz (2 x 1094)|
|Memory (System)|3.84GB (1.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by tsalinger** [comment]
To clarify, you launch VS Code and don't see an interface at all?
We need additional information to reproduce your problem. If possible, please provide reproduceable steps to your issue.
A [screen recording](https://www.cockos.com/licecap/) might be helpful in your case, too.
