### ISSUE TITLE
Find All References Broken For Live Share

### ISSUE THREAD

**Issue by dkduncan** [Microsoft/vscode#45677]
Issue Type: <b>Bug</b>

When I had someone connected to my live share session, he reported that Find All References just says loading and it keeps hanging.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|15.92GB (0.23GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Development\opie-js|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-npm-source|dku|1.0.0
gitlens|eam|8.1.1
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vsliveshare|ms-|0.2.206
debugger-for-chrome|msj|4.2.0
autoimport|ste|1.5.3
JavaScriptSnippets|xab|1.5.0

</details>
Reproduces only with extensions

**Comment by alexandrudima** [comment]
Moved to https://github.com/MicrosoftDocs/live-share/issues/171
