### ISSUE TITLE
Allow preLaunch task for compound list

### ISSUE THREAD

**Issue by guidobouman** [microsoft/vscode#45676]
Issue Type: <b>Feature Request</b>

Currently we can add a `preLaunchTask` prop to any launch setting. This works well when running a single project. But this get unworkable when using compounds.

When running multiple projects (website, API & CMS for example) in a compound launch task, triggering a `build` task from each `preLaunchTask` can throw an error about files being in use during buildtime. This happens when a buildable dependency is referenced from more than one project.

Can we allow compounds to have a `preLaunchTask` as well? Then we can trigger a global build and run all of the projects after the single build has succeeded. Much like the `start` command in Visual Studio on Windows works right now.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

**Comment by isidorn** [comment]
This is a fair feature request.
fyi @weinand

**Comment by isidorn** [comment]
This should be possible now that @alexr00 added global tasks.
So adding to this milestone so @alexr00 and me look into if something is missing here

**Comment by isidorn** [comment]
I have pushed support for this.
I have tried it out and it seems to work nicely..
Please try it out in vscode insiders from Wednesday and let me know how it beahves

**Comment by guidobouman** [comment]
@isidorn Thanks again for this! Brings VS Code one step closer to feature parity with (and ux triomph over) Visual Studio.
