### ISSUE TITLE
Language server startup failed

### ISSUE THREAD

**Issue by masyanru** [Microsoft/vscode#45670]
- VSCode Version: 1.21.0
- OS Version: macOS 10.13.3
ms-vscode.powershell 1.6.0

I reinstalled everything: vscode, pwsh and extensions, but when PowerShell Integrated Console tries to start I get this error "Failed to find an open socket port for either the language or debug service."

Full log with "powershell.developer.editorServicesLogLevel": "Diagnostic"

Transcript started, output file is /Users/a.mosyagin/.vscode/extensions/ms-vscode.powershell-1.6.0/logs/1520951380-7e027779-a3d9-4c85-b9ac-4503fa6a8dc81520951377615/Start-EditorServices.log
VERBOSE:
#-- Updated PSModulePath to: -------------------------------------------------
VERBOSE: /Users/a.mosyagin/.local/share/powershell/Modules
VERBOSE: /usr/local/share/powershell/Modules
VERBOSE: /usr/local/microsoft/powershell/6.0.1/Modules
VERBOSE: /Users/a.mosyagin/.vscode/extensions/ms-vscode.powershell-1.6.0/modules
VERBOSE:
#-- Check required modules available -----------------------------------------
VERBOSE: Testing module availability PowerShellGet
VERBOSE: Loading module from path '/usr/local/microsoft/powershell/6.0.1/Modules/PowerShellGet/1.6.0/PSModule.psm1'.
VERBOSE: PowerShellGet  found
VERBOSE: Testing module availability PowerShellEditorServices 1.6.0
VERBOSE: Loading module from path '/Users/a.mosyagin/.vscode/extensions/ms-vscode.powershell-1.6.0/modules/PowerShellEditorServices/PowerShellEditorServices.psm1'.
VERBOSE: PowerShellEditorServices 1.6.0 found
VERBOSE:
#-- Start up PowerShellEditorServices ----------------------------------------
VERBOSE: Importing PowerShellEditorServices
VERBOSE: Loading module from path '/Users/a.mosyagin/.vscode/extensions/ms-vscode.powershell-1.6.0/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'.
VERBOSE: Loading module from path '/Users/a.mosyagin/.vscode/extensions/ms-vscode.powershell-1.6.0/modules/PowerShellEditorServices/PowerShellEditorServices.psm1'.
VERBOSE: Exporting function 'Start-EditorServicesHost'.
VERBOSE: Exporting function 'Compress-LogDir'.
VERBOSE: Exporting function 'Get-PowerShellEditorServicesVersion'.
VERBOSE: Importing function 'Compress-LogDir'.
VERBOSE: Importing function 'Get-PowerShellEditorServicesVersion'.
VERBOSE: Importing function 'Start-EditorServicesHost'.
VERBOSE: Searching for available socket port for the language service
VERBOSE: Checking port: 21105, attempts remaining 10 --------------------
VERBOSE: Testing availability of port 21105 at address 10.60.72.128 / InterNetwork
VERBOSE: SocketException on port 21105: System.Net.Sockets.SocketException (0x80004005): Can't assign requested address
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at CallSite.Target(Closure , CallSite , Object )
VERBOSE: Port: 21105 is NOT available
VERBOSE: Checking port: 13182, attempts remaining 9 --------------------
VERBOSE: Testing availability of port 13182 at address 10.60.72.128 / InterNetwork
VERBOSE: SocketException on port 13182: System.Net.Sockets.SocketException (0x80004005): Can't assign requested address
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at CallSite.Target(Closure , CallSite , Object )
VERBOSE: Port: 13182 is NOT available
VERBOSE: Checking port: 24176, attempts remaining 8 --------------------
VERBOSE: Testing availability of port 24176 at address 10.60.72.128 / InterNetwork
VERBOSE: SocketException on port 24176: System.Net.Sockets.SocketException (0x80004005): Can't assign requested address
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at CallSite.Target(Closure , CallSite , Object )
VERBOSE: Port: 24176 is NOT available
VERBOSE: Did not find any available ports!!

but my ip - 10.60.32.22, not 10.60.72.128. Why did vscode do that? ;) I think this is a problem.

**Comment by dbaeumer** [comment]
@masyanru this comes form the PowerShell extension. Can you please report the problem here: https://github.com/PowerShell/vscode-powershell
