### ISSUE TITLE
Automatically generated tasks.json not functional on PowerShell

### ISSUE THREAD

**Issue by IAmHopp** [Microsoft/vscode#45681]
Issue Type: <b>Bug</b>

1. Define PowerShell as the default shell.
2. Create a new project or delete tasks.json on an existing project.
3. Select "Tasks: Run Task".
4. Follow the process to generate a new tasks.json file from one for the templates.
5. Choose "Maven".
6. Run any of the tasks created in the new file.

This is the output I'm getting, for example, running "test":

> > Executing task: 'mvn -B test' <
> 
> mvn -B test

Today's build did some work around quoting in tasks and, as a result, I can't get any task to work unless I add `\"` to the beginning and end of the command. Without it, it just echoes the command as the example above. I suppose this is expected and I should now change all of my personal tasks? Let me know if I'm wrong here.

In any case, I'm filling this issue because, due to this change, any new user with PowerShell that creates a new tasks.json from a template will have tasks that don't work right away, with no immediate instruction that a `\"`s need to be added. I don't believe this is optimal.

I tested with Maven but, since none of my personal tasks are working and for the exact same reason, I think any template would yield the same result.

VS Code version: Code - Insiders 1.22.0-insider (112670122d3acf863aa9542b1642d64c69be10bf, 2018-03-13T05:16:22.707Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|15.88GB (5.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.1.1
mssql|ms-|1.3.0
team|ms-|1.122.0
java|red|0.20.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2

</details>
Reproduces without extensions

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/45684. I broke that for yesterdays insider build. It is fixed in todays.
