### ISSUE TITLE
Adding support for virtualfish, virtualenv for fish shell.

### ISSUE THREAD

**Issue by anhdle14** [Microsoft/vscode#45680]
Version 1.22.0-insider
Commit 3817c899cae312e0e989da8bfbc61308cfbf45f1
Date 2018-03-09T13:53:26.466Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS Linux 4.15.6-300.fc27.x86_64 #1 SMP Mon Feb 26 18:43:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Prepared virtualfish, fishshell. [docs](https://virtualfish.readthedocs.io/en/latest/install.html)
2. Changed the user setting:
```json
    "python.venvPath": "$VIRTUALFISH_HOME",
    "python.envFile": "$VIRTUAL_ENV"
```
3. Select Python Interpreter.
4. Except base path: `/usr/bin/python3/ ` and `/usr/bin/python` could not find virtualfish list envs.

This is more than a future request than actual issues.

Does this issue occur when all extensions are disabled?: Yes

**Comment by tsalinger** [comment]
Moved to the python extension repo. Please continue discussion there.
https://github.com/Microsoft/vscode-python/issues/1071
