### ISSUE TITLE
translation: translate enum values 'stopped reasons' by considering their context

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4568]
The strings below are all the reasons why a debugger is stopped. The 'reason' will be embedded in the string: "Paused on {0}":

![2016-03-22 18-09-08](https://cloud.githubusercontent.com/assets/1898161/13960579/39ddc40c-f059-11e5-867b-7f1ab7d70f7b.png)

```json
	"reason.debugger_statement": "debugger statement",
	"reason.breakpoint": "breakpoint",
	"reason.entry": "entry",
	"reason.exception": "exception",
	"reason.step": "step",
	"reason.user_request": "user request",
```

In German there is an inconsistent dot at the end of:
```
	"reason.debugger.statement": "Debuggeranweisung.",
```

**Comment by johnliu2016** [comment]
Ported to loc for fix

**Comment by johnliu2016** [comment]
Loc team fixed the translation according to the context.
