### ISSUE TITLE
Variables with the same name do not show up in the Locals Pane

### ISSUE THREAD

**Issue by jramsay** [Microsoft/vscode#45683]
- VSCode Version: 1.21.0-Insiders (Also occurs in the latest stable)
- OS Version: Windows 10 (& Mac)

Steps to Reproduce (using VS Live Share extension)

1.  VS (host): Create a new JavaScript -> Blank Node.js Console Application and _Share_ it.
2. VS Code (guest): Join collaboration session
3. VS (host): set a breakpoint in app.js @ console.log('Hello world'); and F5
4. VS Code (guest) : wait until breakpoint Is hit and then step into console.log

Expected: VS code and VS locals windows both contain the same variables (namely: two entries called Closure)

Actual: VS Code only has one o the Closure variables

As per @weinand : yes, variables are identified by their name, so you cannot have two variables on the same level with the same name. Please file an issue against the debug adapter protocol.

**Comment by weinand** [comment]
I've create [DAP request](https://github.com/Microsoft/vscode-debugadapter-node/issues/168) for this.
