### ISSUE TITLE
The Powershell session has terminated due to an error, would you like to restart it

### ISSUE THREAD

**Issue by MuleDad** [Microsoft/vscode#45687]
Issue Type: <b>Bug</b>

Working on a script for SCCM when I run to test the terminal/debugger crashes. This seems to happen more and more. Here is a script that continues to crash for me. 

$Phases = @(0,4,3,4,3,4,3,4,3,4,3,4)
$SoftwareUpdateGroupName = "Workstations - 201803 - Critical"

Get-CMDeviceCollection | Where-Object { $_.Name -like "Workstations - Software Updates - Phase*" } | ForEach-Object {
    if ($_.Name -like "*No Reboot*")
    {
        $NoReboot += $Collection.CollectionId
        $NoReboot
    }
    else
    {
        $Reboot += $Collection.CollectionId
        $DeadlineDate = $DeadlineDate.AddDays($Phases[$Reboot.Count-1])
        $SoftwareUpdateGroupName + " - Phase 0"
        $DeadlineDate
        
    }
}

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|15.89GB (10.87GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.0
PowerShell|ms-|1.6.0

</details>
Reproduces only with extensions

**Comment by MuleDad** [comment]
I just ran the code in Powershell ISE and it's giving this:

You cannot call a method on a null-valued expression.
At line:13 char:9
+         $DeadlineDate = $DeadlineDate.AddDays($Phases[$Reboot.Count-1 ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull


So I guess what I'm asking, is instead of crashing VSCode, can we get the error output?

**Comment by MuleDad** [comment]
``

**Comment by Tyriar** [comment]
@MuleDad does it crash just the terminal (and close it) or does it crash the whole window?
