### ISSUE TITLE
Azure Account Sign in Button not working

### ISSUE THREAD

**Issue by glstream** [Microsoft/vscode#45699]
- VSCode Version: 1.21
- OS Version:Mac OSX 10.12.6

Steps to Reproduce:

1. Open VS Code, down load Azure Accoutn Sign In and Azure Data lake tools.
2. See warning that says "The binary dependencies are being downloaded, please wait until it completes".
3. Never can sign into Azure.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
@glstream Do you see the 'Azure: Sign In' command in the command palette? What happens when you run that? Is there anything logged to the console (Help > Toggle Developer Tools)?

**Comment by glstream** [comment]
After clicking the 'Azure: Sign In' in the command palette here is the
responses.

Here is the error in the program:

The binary dependencies are being downloaded, please wait until it completes

And here is the error in the console:


console.ts:136 [Extension Host] Error: self signed certificate in
certificate chain at TLSSocket.<anonymous> (_tls_wrap.js:1088:38) at
emitNone (events.js:86:13) at TLSSocket.emit (events.js:188:7) at
TLSSocket._finishInit (_tls_wrap.js:610:8) at TLSWrap.ssl.onhandshakedone
(_tls_wrap.js:440:38)


console.ts:136 [Extension Host] Error: Acquiring user code failed at
/Users/gstream/.vscode/extensions/ms-vscode.azure-account-0.3.2/out/src/azure-account.js:573:28
at Request._callback (
/Users/gstream/.vscode/extensions/ms-vscode.azure-account-0.3.2/node_modules/adal-node/lib/util.js:119:7)
at self.callback (
/Users/gstream/.vscode/extensions/ms-vscode.azure-account-0.3.2/node_modules/request/request.js:188:22)
at emitOne (events.js:96:13) at Request.emit (events.js:191:7) at
Request.onRequestError (
/Users/gstream/.vscode/extensions/ms-vscode.azure-account-0.3.2/node_modules/request/request.js:884:8)
at emitOne (events.js:96:13) at ClientRequest.emit (events.js:191:7) at
TLSSocket.socketErrorListener (_http_client.js:358:9) at emitOne
(events.js:96:13) at TLSSocket.emit (events.js:191:7) at emitErrorNT
(net.js:1283:8) at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:400
(anonymous) @ extensionHost.ts:213
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

**Comment by chrmarti** [comment]
Are you using a HTTP proxy with a self-signed certificate?

**Comment by glstream** [comment]
Christof, I am using VS code on my Mac to connect to azure, thats all I know man. I just downloaded the extensions, "Are you using a HTTP proxy with a self-signed certificate”, I have no idea what that means, I am using VScode and a connection to the internet. I have a team of analysts that need to run u-sql queries against our data lake using a mac. If not in Vscode please let me know how.

**Comment by chrmarti** [comment]
Can you check if you have the HTTP_PROXY or HTTPS_PROXY environment variables set? (Run `echo $HTTP_PROXY; echo $HTTPS_PROXY` from a terminal. Not that this could include a password, so don't just post the values here.)

**Comment by glstream** [comment]
Yes I have https proxy variables set up and all the dependencies.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-azure-account#49
