### ISSUE TITLE
Resolve commands in "terminal.integrated.env.*"

### ISSUE THREAD

**Issue by RichyHBM** [Microsoft/vscode#45692]
- VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
- OS version: Linux x64 4.15.0-10-generic

Steps to Reproduce:
1. set a settings variable to make use of a command
2. observe that command isnt resolved to its value

Does this issue occur when all extensions are disabled?: Yes

Example:
Having the Golang extension, or any other extension that provides commands:

```
{
    "go.inferGopath": true,
    "terminal.integrated.env.linux": {
        "GOPATH": "${command:go.gopath}"
    }
}
```

> $ env
> ...
> GOPATH=${command:go.gopath}
> ...

I believe this is similar to #34337 which was fixed in #40059 by @ramya-rao-a by processing the env: and config:, but it does not process commands

**Comment by Tyriar** [comment]
@ramya-rao-a do you know what it would mean to resolve commands? I think you could do this with `${env:GOPATH}`, no?

**Comment by ramya-rao-a** [comment]
@Tyriar 

`${env:GOPATH}` would point to the gopath in the env of the renderer process
The Go extension has in built logic to determine the go path (which can be different from `${env:GOPATH}`) which can be displayed to the user using the `Go: Current GOPATH` command

@RichyHBM 

I believe you are asking for a generic feature where you want to use the output of any command usable in the settings. cc @isidorn for thoughts on that

**Comment by RichyHBM** [comment]
@ramya-rao-a My precise use case is for the go extension, but yes this issue is regarding any command

**Comment by isidorn** [comment]
I believe you are asking for something like [interactive variables](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/electron-browser/configurationResolverService.ts#L272)
#6569

However debug is the only one supporting interactive variables. If I understand correctly this would be a feature request for the settings to support interactive variables fyi @sandy081

**Comment by sandy081** [comment]
There is a request already to support resolving env variables in settings - https://github.com/Microsoft/vscode/issues/2809
