### ISSUE TITLE
translation: translate enum values 'scopes' by considering their context

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4569]
The strings below are all variable scopes shown here:

![2016-03-22 18-04-59](https://cloud.githubusercontent.com/assets/1898161/13960435/abbfad66-f058-11e5-89d0-843eae1d2c14.png)

They should be translated as a whole.

``` json
    "scope.block": "Block",
    "scope.catch": "Catch",
    "scope.closure": "Closure",
    "scope.exception": "Exception",
    "scope.global": "Global",
    "scope.local": "Local",
    "scope.script": "Script",
```

**Comment by johnliu2016** [comment]
Ported to loc
These 'scopes' enum values seem syntax keyword, are they supposed to be localized?

**Comment by weinand** [comment]
@johnliu2016 only the 'catch' scope refers to the syntactic element 'catch' of the JavaScript language.
The other scopes are descriptive. Should I exclude 'scope.catch' from translation?

**Comment by johnliu2016** [comment]
Please lock the 'catch' scope enum value in corresponding lci commenting, loc will catch that and act accordingly.

**Comment by weinand** [comment]
@johnliu2016 how do I 'lock' the 'catch' scope enum value in corresponding lci commenting?

**Comment by johnliu2016** [comment]
@dbaeumer can you help update the commenting in https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization?path=%2Fcomponents%2Fvscode-node-debug%2Fout%2Fnode%2FnodeDebug.nls.resx.lci&version=GBmaster&_a=contents

**Comment by dbaeumer** [comment]
@weinand you need to put a comment into the localize call as you did for the node usage. The comment you have in the call will then be translated to the lci file referenced by @johnliu2016 in his last comment.

**Comment by johnliu2016** [comment]
All scopes enumeration values are translated except "catch".
