### ISSUE TITLE
Typed text appears in very fine print next to right scrollbar

### ISSUE THREAD

**Issue by rbroomhall** [Microsoft/vscode#45698]
Issue Type: <b>Bug</b>

all the text i type in appears on screen ok but it also shows up next to the right scroll bar in very fine print.
how do i remove it

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 x 3200)|
|Memory (System)|31.92GB (24.98GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.2.1
vscode-icons|rob|7.21.0

</details>
Reproduces only with extensions

**Comment by dougireton** [comment]
@rbroomhall you mean the [minimap](https://code.visualstudio.com/docs/getstarted/userinterface#_minimap-outline-view)?

The VSCode docs on MiniMap show you the setting to turn it off.
