### ISSUE TITLE
Center code vertically

### ISSUE THREAD

**Issue by jemhuntr** [Microsoft/vscode#45697]
![image](https://user-images.githubusercontent.com/6434778/37346648-d460f1f4-270a-11e8-9772-760883022ae5.png)

With the horizontal centering implemented on the latest version, perhaps we can make a vertically-centered editor too?

It's especially annoying on small files, where 80% of my screen would be empty vertically but the first line of code is literally 2 pixels away from the top tabs. This (sometimes) urges me to add an empty newline at the start of each file, but that, from a personal perspective, is a bad habit I would like to break to ensure formatting consistency.

**Comment by lukas-h** [comment]
Hi, 

I have a monitor in portrait mode and would really like to have this feature.

How can I configure this? Or is this even available?
