### ISSUE TITLE
Missing `outputFocus` context variable

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#45695]
I'm trying to set things up so that I can always close whatever pane I'm in with a `cmd+w`, I can do this for:

Problems:

`{ "key": "cmd+w", "command": "workbench.action.togglePanel", "when": "problemFocus" }`

Debug console:

`{ "key": "cmd+w", "command": "workbench.debug.action.toggleRepl", "when": "inDebugRepl" }`

Terminal:

`{ "key": "cmd+w", "command": "workbench.action.terminal.kill", "when": "terminalFocus" }`

But I can't do this for the `Output` pane, since there's no `outputFocus` context variable I can use.

Can you add this please?

**Comment by isidorn** [comment]
Please use the `inOutput` context key
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/output.ts#L62
