### ISSUE TITLE
Find and replace optimization for large files

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#45690]
When users run find in a single file, we will run regex line by line originally. Now we have a text buffer which stores content in chunks instead of lines, running regex on chunks directly can avoid the overhead of `getLineContent`.

Things to note while doing this optimization

* When a line sits across Piece Tree nodes/buffers, we fall back to `getLineContent` then search.
* When users search by multiline regex, we need to get the whole content and then search, like before.
* When users search by single line regex, but the regex contains `^`, `$` or similar, executing this kind of regex on chunks will miss matches when there are line breaks.

**Comment by rebornix** [comment]
Benchmark on 1GB file

*Line Array*
![image](https://user-images.githubusercontent.com/876920/37373527-245ad224-26d4-11e8-880b-68665833d9e3.png)

Search is slow, but deltaDecorations is just operating on the interval tree

**Comment by AlCalzone** [comment]
This is probably related, but feel free to open another issue if its not:
When opening a large log file (30k lines in my case), I can reliably freeze the window just using search. Steps to reproduce:
* Open large file
* Enter the following in the search box with regex enabled: `$\n`

As soon as the `n` is entered, VSCode freezes and asks me a couple of seconds later if I want to restart the current window.

**Comment by rebornix** [comment]
@AlCalzone we didn't optimize regex searching yet but it's on my palette.
