### ISSUE TITLE
Allow to choose the WorkspacePath from Split Terminal Command

### ISSUE THREAD

**Issue by pungggi** [Microsoft/vscode#45694]
This is a feature request.

The `New Terminal' Command (Plus Sign) asks, when working with multiple workspaces for wich workspace to open the path for.

The same is not true for the `Split Terminal` Command.
It would be nice to get the same prompt or better to open based on where the focus is (wich workspace) in the file explorer or the active open file without prompt

**Comment by Tyriar** [comment]
Opening this to PRs, for anyone who wants to pick this up you will need to make the split command work like this one:

https://github.com/Microsoft/vscode/blob/45bfe40a61af00eff2c03faaa63bf4656aff42c9/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts#L232

**Comment by kennyle1412** [comment]
Hello!

I'd like to work on this bug for my first issue.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/46461
