### ISSUE TITLE
Php autocomplete issue

### ISSUE THREAD

**Issue by anothergituser** [Microsoft/vscode#457]
Autocomplete stops working for php

```
workbench.main.js:1550 WARNING: Promise with no error callback:undefined
workbench.main.js:1550 Error: Promise did not implement oncancel(…)
```
This is how to reproduce.
Say you start writing ```array_chunk```, it autocompletes fine, as you are writing.
Then you open and close the parentheses and now you have this ```array_chunk()```. Now begin to delete what you just wrote, when you delete the parentheses and you get back to having just ```array_chunk``` again that's where that error shows up in the dev tools and autocomplete stops working for everything until you restart the editor. Of course this happens with any other function also not just array_chunk.

I tested this behavior on Fedora 22 and Windows 10 both 64bit

**Comment by jel-massih** [comment]
Looks like this was fixed in https://github.com/Microsoft/vscode/commit/c89555baaf13352799a9299a284ff261d3d68c34

**Comment by anothergituser** [comment]
Cool, but the last version i can download is still 0.10.1 that has the issue. Can i compile this thing from the repo?

**Comment by jel-massih** [comment]
Yeah there is instructions on the wiki
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by anothergituser** [comment]
Well it's fixed. Thanks.
I managed to run the thing after following the instructions, using ./scripts/code.sh
Do i need to run that every time i need to open the editor or can i build a binary like in the official archive?

**Comment by anothergituser** [comment]
Very cool. No issues with this latest build. Thanks.

**Comment by anothergituser** [comment]
I managed to run it using ./scripts/code.sh from inside the repo. Do i always run it like so or can i make a binary like in the official archive?
