### ISSUE TITLE
Searcherror: "Error parsing Glob'!

### ISSUE THREAD

**Issue by EliasOriley** [Microsoft/vscode#45708]
- VSCode Version: Newest
- Windows Version: 10

Steps to Reproduce:

1. Updated to newest Version
2. Search in Workfolder
3. Error occours:
"Error parsing Glob'!/Folder which i use/**/node_modules': invalid range; 'h' > 'M'"

Does this issue occur when all extensions are disabled?: Yes

I use vscode with default settings.

Sry, my english is not this good and im using vscode to edit SQF scripts.
Thanks for the quick answer.

**Comment by roblourens** [comment]
Please list which version you use (Insiders or stable?) and what do you put in the include/exclude boxes?
