### ISSUE TITLE
Merge include/exclude search pattern inputs

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#45702]
Related to https://github.com/Microsoft/vscode/issues/45063

We should combine the include/exclude inputs in the search view. It's a waste of vertical space and I doubt that people use them heavily enough to justify two separate inputs. This also would match other editors.

**Comment by roblourens** [comment]
Do we still even need the `...` menu?

**Comment by Abhijay** [comment]
How am I supposed to search for exclusive data types while ignoring certain folders?

e.g. 

include: *.js
exclude: /someFolderWithUnrelatedFiles/?

**Comment by roblourens** [comment]
I don't understand the problem, please open a new issue with more details.

**Comment by Crazy-P** [comment]
` I doubt that people use them heavily enough to justify two separate inputs.` That statement is rather unjustified in itself.
The idea for the merged field is nice - but might as well be considered poor UI/ UX. 20-30 extra pixels doesn't do much.
If this is necessary, then I/we would like to have the option to use either 2 inputs or just 1 input field.

Reasons why are explained in this issue: https://github.com/Microsoft/vscode/issues/46315

**Comment by acls** [comment]
Terrible idea. Please revert.
