### ISSUE TITLE
basic support for debugging MPI applications

### ISSUE THREAD

**Issue by davydden** [Microsoft/vscode#45707]
I am curious whether or not debugging MPI application is on the road map of VSC?
In the most simplest case one could get away by attaching a terminal to each process, i.e. manually running on macOS

```
mpirun -np 2 xterm -e lldb -f my_exec
```

I am not sure whether or not there are some tricks to achieve this with `launch.json`, but I think it would be great if one could at least setup breakpoints for all processes and run the executable.

p.s. AFAIK Eclipse PTP is the only free tool, but debugger is limited to Linux.

**Comment by isidorn** [comment]
https://code.visualstudio.com/docs/extensions/example-debuggers
