### ISSUE TITLE
Certain themes show UI artifacts over activity bar icons

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45700]
![glitch](https://user-images.githubusercontent.com/4033249/37372150-093dca3c-26cf-11e8-8e58-db5d59a8462c.gif)

I run into this glitch in a constant basis.

**Comment by bpasero** [comment]
@octref I have seen this too! What theme are you using?

**Comment by octref** [comment]
This one: https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme

**Comment by bpasero** [comment]
@octref can you reproduce this with our default dark or light theme? I do not see it in our light theme...

**Comment by octref** [comment]
Can't repro it on either default dark/light, but I can repro it in both Nord/Material themes.

**Comment by bpasero** [comment]
This seems to be related to setting a `background-color` on our activity bar icons that leverage `webkit-mask` to allow the color to shine through ([here](https://github.com/Microsoft/vscode/blob/tyriar/electron-2.0.x/src/vs/workbench/browser/parts/compositebar/compositeBarActions.ts#L144)). We use this as trick to be able to theme the activity bar icons. 

I could not find a related issue in Chrome for this so far :-/

**Comment by bpasero** [comment]
I pushed a workaround to not set this color on macOS and leave it at `#FFFFFF`.

**Comment by bpasero** [comment]
Credits to @MarshallOfSound for providing me with this property that seems to fix it. Even though we are using `--webkit-mask` in more places, I only set this for icons in the activitybar where I see the issue.

**Comment by octref** [comment]
@bpasero I think this has been fixed for activity bar icons, but not the gear icon lowerleft:

![flashing-30](https://user-images.githubusercontent.com/4033249/38947264-e81d07b2-42f0-11e8-94eb-6ba1fe8644a6.gif)

I'm on 88f500e805ecc4efd064f7886c1a5ce8a2a2c087

**Comment by bpasero** [comment]
@octref good catch, I will fix that
