### ISSUE TITLE
translation: translate 'node' as the software product 'node.js' and not as 'knot'

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4570]
Example: in "Request '{_request}' was cancelled because node is unresponsive." the word 'node' was translated to 'Knoten' (knot) in German. In the context of VS Code every occurrence of 'node' refers to the product 'Node.js'. I have changed the string in node-debug to use 'Node.js'.

**Comment by johnliu2016** [comment]
Ported this issue to loc. Once the string change gets into loc file, translation will be updated accordingly.

**Comment by johnliu2016** [comment]
@weinand source changes reflected to loc, instance of "node" in vscode-node-debug are modified to "Node.js"
