### ISSUE TITLE
Custom "when" contexts contribution in extension

### ISSUE THREAD

**Issue by rpeshkov** [Microsoft/vscode#45701]
VSCode has quite a lot of "when" contexts that may be used for defining keybindings, however, I didn't find anything whether extension may contribute its own contexts.

I currently work on extension to allow emacs-style text tables editing and it would be cool if I may define my own contexts and set keybindings according to this context. As an example, it would greatly simplify keybindings if I may introduce context like 'insideTable' and switch it on/off according to current cursor position.

**Comment by fabiospampinato** [comment]
You can do this today with [setContext](https://github.com/Microsoft/vscode/issues/10471), this is still undocumented though.

**Comment by rpeshkov** [comment]
@fabiospampinato sweet! Thanks for that!
