### ISSUE TITLE
Go-to-definition doesn't work with .native.js file extensions

### ISSUE THREAD

**Issue by megantracy93** [Microsoft/vscode#45715]
I'm working in a react + react-native project, so I have .jsx files for web components and .native.js for native components.  The problem is, ctrl+click only works for my .jsx files and none of my .native.js files.  Is there any way to add support for files with additional extensions like that?  Or is there an additional configuration I am missing to already support this?

- VSCode Version: 1.17.2
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Create a file with an extra extension, i.e. `src/components/Tester.native.js`
2. Import that Tester into another file via `./src/components/Tester`
3. Ctrl+click into the Tester component.  Note that it does NOT open the file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please link to a small example project or include code examples showing the project structure and imports

**Comment by klingat** [comment]
Also experiencing this, but across the editor in all files. 

Suddenly noticed that "Go to definition and peek definition" are gone when right clicking on the piece of code. Early last week I noticed it was gone, then by Friday it was back, now this Monday morning it is gone again. My coworker working on completely different code is using VS code as well and is experiencing the same issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kkrishnan90** [comment]
Yes its weird ! I have an iMac and Macbook which runs the same version of vscode ```Version 1.22.2 (1.22.2)```
Unfortunately, the peek definition and go to doesn't work on my Macbook, while it works on my iMac.
I am developing a react-native application on both. Seems to work with ```Cmd+Click``` on my iMac. The same key combination doesn't work on my Macbook.

P.S : I use ```Settings Sync``` and synced both my iMac and Macbook vscode settings. So ideally, nothing should have changed between them.

**Comment by mjbvz** [comment]
Ok, I undestand this issue better now. It is the same as https://github.com/Microsoft/TypeScript/issues/8328 / https://github.com/Microsoft/TypeScript/issues/21926 were TS needs to resolve `a.ts` to `a.native.ts`

Closing this as an upstream typescript issue
