### ISSUE TITLE
No way to dismiss error / warning dialogs displayed on the top of QuickPick

### ISSUE THREAD

**Issue by zikalino** [Microsoft/vscode#45711]
- VSCode Version: 1.20.1
- OS Version: Windows 10 latest
 
Steps to Reproduce:

1. F1 and use select a command that displays QuickPick
2. Unrelated warning or error dialog displayed on the top covering QuickPick
3. Press ESC (and i expect warnings to be dismissed)
4. QuickPick is dismissed first, warnings and errors stay.

Additional note: This is actually happening while debugging extension (warnings / errors are related to extension being launched), but i don't think that matters.

I think dialogs on the top should be dismissed first when pressing ESC.

**Comment by bpasero** [comment]
@zikalino I do not think this reproduces anymore because we changed our notification system in 1.21, an you update?

**Comment by zikalino** [comment]
Indeed just upgraded version to 1.21 and it's not an issue any more. Thanks @bpasero for a quick answer! 👍
