### ISSUE TITLE
[Electron 2.0] Different rendering of icons

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45712]
![image](https://user-images.githubusercontent.com/4033249/37374524-c2f7f8ae-26d8-11e8-90c0-bcbedd81b904.png)

Notice the start debug triangle, restart icon and disconnect icon.
Top is Exploration, bot is Insider.

**Comment by bpasero** [comment]
@octref I think this is just coincidence of how debug icons changed over the past days (@isidorn can confirm that).

Do you see other icons changing as well?

**Comment by octref** [comment]
Just the debug icons (I feel the non-uniform size of the new reconnect/disconnect does not make sense though). @isidorn

**Comment by isidorn** [comment]
@chryw and me changed icons. Please try the latest insiders where this is fixed.
Most of this work is tracked in prs by @chryw https://github.com/Microsoft/vscode/pulls?q=is%3Apr+author%3Achryw+is%3Aclosed
