### ISSUE TITLE
ef generated model requires restart

### ISSUE THREAD

**Issue by PeterWone** [Microsoft/vscode#45719]
Issue Type: <b>Bug</b>

To repro
-

Having generated an EF model from a MSSQL db using CLI as follows

```
dotnet ef dbcontext scaffold -f -c mydbDbContext -o Model "server=myserver;database=mydb;uid=myuser;pwd=mypwd" "Microsoft.EntityFrameworkCore.SqlServer"
```

Open the generated mydbDbContext.cs file and remove the warning pragma because one must move the connection string into config in order to deploy. 

## Observations
1. Immediately you edit, vast numbers of errors are reported because the generated myDbContext class can't see the entity classes.

2. Doing a build reports no errors but the problems pane is stoically unimpressed by this.

3. Closing VSCode and reopening it makes the problem go away.

4. If you repeat the experiment but omit `--output-dir Model` the problem does not occur, probably because all the classes are generated in the application namespace.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (9.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|0.10.0
mssql|ms-|1.3.0
csharp|ms-|1.14.0
team|ms-|1.122.0

</details>

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2109
