### ISSUE TITLE
Search view with horizontal scrolling

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#45717]
https://github.com/Microsoft/vscode/issues/15539

I like the horizontal scroll setting but it doesn't work well in the search view. If I have a search result in a long line of text, then I have to scroll very far to see the file count, or the `x` button, replace button, and file count.

![image](https://user-images.githubusercontent.com/323878/37376278-be69a1d6-26e0-11e8-8925-39af7ab28f16.png)

Ideally these would be fixed to the right side of the search view container and visible without scrolling. But we may also move them as part of https://github.com/Microsoft/vscode/issues/45063

cc @joaomoreno @isidorn

**Comment by joaomoreno** [comment]
That's exactly the problem with horizontal scrolling. Making the actions "float" is also not pretty since they would be overdrawn on top of the text. The same problem happens with explorer decorations.

Apart from perf this is the other reason why horizontal scrolling isn't enabled by default.

**Comment by isidorn** [comment]
This would also be potentially tackled by moving those actions to the left as they are in the open editors view.

**Comment by osortega** [comment]
This doesn't seem to exist anymore, closing
