### ISSUE TITLE
Autocompletions kick in when in snippet mode

### ISSUE THREAD

**Issue by dsthedev** [Microsoft/vscode#45716]
- VSCode Version: 1.21.0
- OS Version: macOS Sierra 10.12.6

I'm trying to create relatively complex snippets for emmet code, but pressing tab after changing an element or class name completes an emmet autocomplete prematurely before the snippet is done.

Steps to Reproduce:

1. Create a snippet for a complex emmet statement
2. Have certain tab completion highlights be html/emmet autocompletes (div, div.class, etc.)
3. Use the snippet and change an element or class then press tab

**Example**: `"${1:div}.grid-container>div.grid-x.grid-margin-x>(div.${2:large-12}.cell*${3:2})$4",
`

If `${1:div}` is changed to another tag like `section`, pressing tab will complete a section tag which breaks the rest of the snippet.

Technically I can get around this by using undo after the premature emmet completion, but that's a workaround.

I think all tab based autocompletion should be disabled while inside a snippet, it's a conflict of input.

Does this issue occur when all extensions are disabled?: Yes

**Comment by dsthedev** [comment]
This is not a duplicate issue.

**Comment by ramya-rao-a** [comment]
> I think all tab based autocompletion should be disabled while inside a snippet, it's a conflict of input.

cc @jrieken for thoughts on the above

**Comment by danawoodman** [comment]
Was about to submit this myself. There should be a config to disable autocomplete in snippets

**Comment by jrieken** [comment]
> I think all tab based autocompletion should be disabled while inside a snippet, it's a conflict of input.

Not sure if you mean tab-completion (`"editor.tabCompletion": true`) which expands snippets *without* the IntelliSense/Autocomplete widget showing or if you mean tab accepting the selected item in the IntelliSense/Autocomplete widget?

**Comment by dsthedev** [comment]
@jrieken Not sure if you read my issue thoroughly or attempted to reproduce the issue, but I'm not talking about the intellisense/autocomplete widget showing.

My issue is that while in the scope of using a snippet with a custom tab order, other autocomplete rules can trigger which defeats the purpose of controlling tab completion of a snippet in the first place.

Here's a gif to show what I mean:

![AutoComplete Issue](https://www.dsthedev.com/wp-content/uploads/2018/04/autocomplete-issue.gif)

As I mentioned in the original post, if I change `div` to `section` and press tab naturally, it creates a section tag instead of moving to the next tab stop defined in the snippet (`large-12`).

Also I tried changing the `"editor.tabCompletion"` setting just in case and it didn't seem to do anything.

**Comment by danawoodman** [comment]
Yeah, this effectively breaks snippets. Only way to prevent the completion is escaping out of the snippet, which means the snippet isn't usable. Quite annoying!

**Comment by jrieken** [comment]
> Not sure if you read my issue thoroughly or attempted to reproduce the issue, but I'm not talking about the intellisense/autocomplete widget showing.

In your gif, when typing `section` a widget shows. We call that [IntelliSense](https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features) and pressing tab inserts the selected item. You seem to refer to that as "tab based autocompletion" which can mean that but it can also mean snippet-expansion via tab (first paragraph [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets)). 

Agreed, the lingo we use is very special and I am not expecting you now the subtle differences but please answer questions when we ask them. Thanks.

**Comment by ramya-rao-a** [comment]
@jrieken 

What is being asked here is to disable the quick suggestions feature (auto triggering of suggestions) when in snippet mode.

In snippet mode, the user expects the tab key to let them traverse through the tabstops and placeholders in the snippet. In snippet mode, when changing the value of a placeholder, quick suggestions feature kicks in. The user has to press escape to get out of the suggest widget and then press to tab to resume traversing through the snippet. This is the problem.

If the suggestions do not get automatically triggered in snippet mode, the user is free to type in the placeholder value and press tab to go to the next tabstop.

**Comment by phiterf** [comment]
This happens in most contexts when you press tab. Same thing happens for snippets that generates a function body. When typing the name, it sometimes end up completing another snippet if it's part of the function name.

**Comment by ramya-rao-a** [comment]
This has been fixed a couple of releases ago.

**Comment by danawoodman** [comment]
@ramya-rao-a is there an option to disable them? If so, what is it? Thanks!

**Comment by ramya-rao-a** [comment]
@danawoodman Use the setting `editor.suggest.snippetsPreventQuickSuggestions`
