### ISSUE TITLE
vscode.executeCodeActionProvider returns nothing in cases where the editor shows a lightbulb

### ISSUE THREAD

**Issue by srivatsn** [Microsoft/vscode#45713]
Issue Type: <b>Bug</b>

With the "Language support for Java" extension installed, I have code like this:

```java
import java.io.Console;

public class foo {
    public static void main(String[] args) {
        Console c12;
    }
```

Normally if i click on c12, i get a lightbulb with a codeaction to remove the line. However , if i run 

```typescript
vscode.commands.executeCommand<vscode.Command[]>('vscode.executeCodeActionProvider', uri, range)
```

if `range` corresponds to a single point on the `c12` variable then we get back no codeactions. However if `range` is a range of more than one character then we get back the codeaction that is seen in the editor.

Note that in a C# file, I'm not seeing this problem. /cc @dbaeumer 

VS Code version: Code - Insiders 1.22.0-insider (112670122d3acf863aa9542b1642d64c69be10bf, 2018-03-13T05:16:22.707Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|Memory (System)|7.90GB (0.77GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.1.1
Go|luk|0.6.77
python|ms-|2018.2.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
vsliveshare|ms-|0.2.206
java|red|0.20.0
vscode-icons|rob|7.21.0

</details>
Reproduces only with extensions

**Comment by dbaeumer** [comment]
@jrieken is there anything special when this command gets executed. The LSP will simply take what the extension API gives it and forwards it to the Java LSP server.

**Comment by jrieken** [comment]
The range is used as given (not expanded or adjusted to a diagnostic etc) and most language brains don't return a result when being called with a simple position.

**Comment by srivatsn** [comment]
The editor is however showing a lightbulb when I simply click at a particular location though - is there some code that expands to a range from a simple position that's not executed with the `executeCommand`?

**Comment by jrieken** [comment]
>  is there some code that expands to a range from a simple position that's not executed with the executeCommand?

Yes, see: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/quickFix/quickFixModel.ts#L41

> I would expect the executeCommand at a position to behave exactly the same as clicking at that position in the editor.

That's the wrong exceptions as the commands are designed to work headless, e.g. with an editor or without controller logic. What they do is dispatch the request to all providers and to merge the result.
