### ISSUE TITLE
Glitch when tab sizing set to "shrink" and tab close button "off"

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45728]
@bpasero I think both of these issues are already fixed in Insiders, but can we pick them into recovery? These two tab issue drive me crazy.

1. `"workbench.editor.tabCloseButton": "off"`, shadow blocks rightmost character:

![image](https://user-images.githubusercontent.com/4033249/37383431-f8bff266-2705-11e8-94be-47c0edd1c00f.png)

2. `"workbench.editor.tabCloseButton": "right"`, spacing is really unbalanced because the close button on active editor is not shown:

Top is insider, bot is stable.

![image](https://user-images.githubusercontent.com/4033249/37383651-44e7bace-2707-11e8-9ef1-bb94847682b0.png)

**Comment by bpasero** [comment]
@Dari-K do you want to look into this through a PR?

**Comment by octref** [comment]
@bpasero Both issues are already fixed in Insider. I'm just suggesting that we cherry-pick those changes into the recovery build. But if you feel it's unnecessary it can go out on March too.

**Comment by octref** [comment]
@bpasero Strange, my Insider shows `x` on the editor tab and has correct padding on left (`10px` instead of `5px`). Also when I turn off tab close button there is no shadow overlay on the filename.

![image](https://user-images.githubusercontent.com/4033249/37389125-4a8bed38-2720-11e8-8d47-57f49ee55587.png)

![image](https://user-images.githubusercontent.com/4033249/37389135-54864f54-2720-11e8-9afa-284be2bd74c1.png)

**Comment by bpasero** [comment]
@octref you are confusing things, you have another setting `"workbench.editor.tabSizing": "shrink" `enabled in stable which is not enabled in insiders.

**Comment by Dari-K** [comment]
@bpasero yeah, I can look at it when I get home later

**Comment by bpasero** [comment]
@Dari-K thanks 👍

**Comment by bpasero** [comment]
Btw I think this issue shows up both for tab close button off and left if tabsizing shrink is on. We probably need the padding on the right hand side to show the shadow and that padding is only there when the close button is on the right.
