### ISSUE TITLE
Can I echo `Predefined variables` in somewhere ?

### ISSUE THREAD

**Issue by vikyd** [Microsoft/vscode#45722]
[Predefined variables](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables)

Can I echo  `${workspaceFolder}` in somewhere?

Because I want to confirm the Predefined variables works well.

**Comment by isidorn** [comment]
Sure, create a task that echoes the ${workspaceFodler}
More about tasks can be found here https://code.visualstudio.com/docs/editor/tasks
