### ISSUE TITLE
Emmet - why don't we have "Wrap with abbreviation" option in files different from .html ?

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#45720]
- VSCode Version: 1.22.0-ins
- OS Version: win7x64

I need some "Wrap with abbreviation" (Ctrl+Shift+A) in .ts file.
How can I do it? It seems like this option works only in .html files

PS: and how about to make possible to expand tags using Emmet "Tab" hotkey for tags, that are written between backticks? I don't know what to do with this problem. Everything written in backticks - is a "dead" text place.

**Comment by ramya-rao-a** [comment]
If you've mapped `typescript` to `html` in the `emmet.includeLanguages`, then you will be able to use `Emmet: Expand Abbreviation` and `Emmet: Wrap with Abbreviation` commands in ts files

If you have done the above and added the setting `"emmet.triggerExpansionOnTab": true` , the you should be able to expand tags using tab inside backticks in ts files

**Comment by user3323** [comment]
@ramya-rao-a , thanks!
Yes, it is pretty simple.
And yes, I did read the docs (https://code.visualstudio.com/docs/editor/emmet) before I created an issue. And I didn't find any info about "How to enable Emmet wrapping feature".

Here is ...
https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types
.. it says only about **_abbreviation expansion_**

But it's not the same. Can you add some words about wrapping feature out there?

And also, maybe add some more examples in 
```
"emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "vue-html": "html",
    "plaintext": "jade"
}
```

... like typescript :)

**Comment by ramya-rao-a** [comment]
All the docs are at https://github.com/Microsoft/vscode-docs. Feel free to send a PR :)

**Comment by user3323** [comment]
@ramya-rao-a 

what about combining things, so html and css could be used in typescript?

I cannot find the right syntax. Or it's not possible yet?
