### ISSUE TITLE
Refresh definition file (d.ts) after build on linked project 

### ISSUE THREAD

**Issue by moshfeu** [Microsoft/vscode#45738]
- VSCode Version: Version 1.21.0 (1.21.0)
- OS Version: OS X 10.11.6 (15G17023)

Steps to Reproduce:

1.  Open a project folder with link (`npm link`) to another local project.
2. The another project has `d.ts` file. So verify that you can go to definition of the project. (Click on <kbd>F12</kbd> on a function from the another project.  (You should be moved to the `d.ts` file in the `node_modules/another_project/dist/d.ts`)
3. Update the `d.ts` file (for example: change the code and let webpack to update the `d.ts`).

**Expected result:**

VScode will refresh its intellisense and errors detection. 

**Actual result**

It didn't. Even if I close and open the file. I need to close the vscode instance of my current project and open it again. Only then it count the updated `d.ts`.

Does this issue occur when all extensions are disabled?: Yes

Thanks!

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22656
