### ISSUE TITLE
Maximized panel should be fullscreen

### ISSUE THREAD

**Issue by Istanful** [Microsoft/vscode#45734]
# Make maximized terminal truly fullscreen
As of right now, when you maximize your terminal there will still be a gap at the top of the screen (in the case of actually having your terminal at the bottom). It would be great if it could actually hide all the open editor panels.

What it looks like:
<img width="1281" alt="Semi maximized terminal" src="https://user-images.githubusercontent.com/10728852/37388258-13dc79e8-2760-11e8-886a-907691473a76.png">

What I would like it to look like:
![example](https://user-images.githubusercontent.com/10728852/37388390-920e14e8-2760-11e8-8cc5-1dd861b746b5.png)

- VSCode Version: 1.21.0
- OS Version: macOS 10.12.6

Steps to Reproduce:
1. Open and maximize your terminal

**Comment by Istanful** [comment]
@isidorn I could not find a duplicate. My suggestion is merely about appearance of the maximized terminal. I could only find issues touching other subjects. Correct me if I'm wrong.

**Comment by Istanful** [comment]
@isidorn Could you link the duplicate issue? I remember finding none but would like to follow further progress on this.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/42149

**Comment by Istanful** [comment]
@isidorn thank you!
