### ISSUE TITLE
[REQ] files.exclude setting per project

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#45732]
Hi,

The `files.exclude` is great option, but it would be great to have some way (maybe some config file in root of project) to apply this option per solution/project too.

Thanks.

**Comment by bpasero** [comment]
@dehghani-mehdi you can, just configure "workspace" or "folder" settings.

**Comment by dehghani-mehdi** [comment]
@bpasero thanks, can you please provide documentation link, I didn't get you.

**Comment by bpasero** [comment]
@dehghani-mehdi https://code.visualstudio.com/docs/getstarted/settings
