### ISSUE TITLE
Cpp IntelliSense engine doesn't work with projects cloned by WSL git.

### ISSUE THREAD

**Issue by SidekickLx** [Microsoft/vscode#45739]
I happened to clone my c-lang repo via WSL and open it from VScode on windows. And I found that all of the intellisense hints was gone. No matter how I changed the configurations , I still can't get any quick info, code completions, squiggles(errors or warnings), quick tips(which above your mouse when it stops) and so on. Everything was just gone. 
However, if I tried to clone my project via PowerShell on windows itself, the engine just worked properly.
I thought it was about CRLF/LF issue, but when I changed it one by one files. It was not fixed.

- VSCode Version: 1.21.0
- OS Version: windows insider preview 17120 with WSL(ubuntu 16.04)

Steps to Reproduce:

1. clone a c/cpp repo via WSL
2. open it via vscode on windows itself

Does this issue occur when all extensions are disabled?: I dont know because it might caused by Code itself or c/cpp plugin.

**Comment by joaomoreno** [comment]
We don't currently support WSL: #9502

Regardless, in order to figure out what's wrong, just clone the same repository in the "regular" way and look for differences. That will lead you to the solution.

**Comment by SidekickLx** [comment]
I did, and the only difference is  carriage-return symbols. And I changed them to the same. The issue was still their.
I was confused because the editor just pass the code to language server and those work was done by language server.
The problem should not relate to wsl, in my opinion.
Thanks.

**Comment by joaomoreno** [comment]
@SidekickLx Maybe switching just one file doesn't work, maybe the extension requires it for all files.
