### ISSUE TITLE
Debugging Console freezes VSCode

### ISSUE THREAD

**Issue by SpiresAwake** [Microsoft/vscode#45748]
Issue Type: <b>Bug</b>

While debugging a NodeJS application, whenever I output a lot of text to the console, VSCode completely freezes at some point and requires a restart.
This only occures since after the latest update (1.21.0).

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|Memory (System)|15.88GB (6.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\node\pim|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.5
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.28
vsc-material-theme|Equ|1.5.1
vscode-npm|fkn|3.3.0
rest-client|hum|0.17.0
csharp|ms-|1.14.0
material-icon-theme|PKi|3.2.5
vscode-icons|rob|7.21.0

(4 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
@SpiresAwake can you please provide a reproducable application so we can also investigate this on our machines?
When you say console you mean the Debug Console in the bottom? You are sure this was working fine in vsoce 1.20?

**Comment by SpiresAwake** [comment]
Unfortunately, I cannot provide you with a sample application. I just tried to reproduce it with a simple loop and console.log inside it, but this only slows VS Code down. The application I'm working with outputs a lot of large objects etc. for debug-purposes.

I get the same behavior using the insiders build I just installed. Before 1.20, everything was working fine. Is there maybe some sort of log I can provide you with to help fix this?

**Comment by isidorn** [comment]
Unfortunetly there are no logs that can help me with this performance issue.
What you could do though is 
* F1 > open developer tools > Performance tab
* Click on the record button and now start your application which outouputs a lot of large objects
* Once you see vscode being slowed down a lot stop your application and stop the recording
* Drilling down into the recording can provide some information whati s taking the most time. If you do not want to drill down into the recording you can also send it to me via email to inikolic@microsoft.com

Maybe as a workaround you can set in your launch.json, which will make all the output go to the terminal. Try also "externalTerminal"
`"console": "integratedTerminal"`

**Comment by SpiresAwake** [comment]
I've tried doing performance recording. Unfortunately, when I press "stop recording" and the editor window is already frozen, it gets stuck at "Loading recording" and I don't get to see any report. ☹️ 

The "console"-option doesn't seem to be a valid option for  type "node" and request "attach". As a workaround, I used "internalConsoleOptions":"neverOpen" right now.

I guess this issue will remain a mystery?

**Comment by isidorn** [comment]
It will definetely not remain a mistery, more users will complain sooner or later if it is not specific to your machine.
You could also try to gently bombard the console such that it is not frozen completely.
Or try to create a reproducable sample which you could share.
