### ISSUE TITLE
Offer user a way to enter a workspace if detecting a workspace file

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45749]
I receive more and more issues where the reproducible steps assume a multi-root setup with a single folder and a workspace file in this folder.

Since the reproducible steps typically don't explain how to open the project in VS Code I just open the folder. As a consequence I'm missing all workspace settings and launch.configs which makes it difficult to reproduce the issue at hand.

After some interaction with the issue's author we figure out that I was supposed to open the project via the workspace file.

Could we add some smartness to VS Code's "Open Folder" action that warns about this situation and offers me to open the workspace file instead?
 
/cc @isidorn

**Comment by bpasero** [comment]
@weinand to be clear, you expect a warning to show up whenever a user opens a folder where there is 1-N workspace files top level in that folder?

**Comment by weinand** [comment]
I'm expecting a warning if a user opens a folder that contains a file "*.code-workspace"

**Comment by DanTup** [comment]
This is a similar request to discussed here:

https://github.com/Microsoft/vscode/issues/45399#issuecomment-372091066

I would love this. If someone has gone to the effort of maintaining a code-workspace in a repository (which is somewhat required for some debugging scenarios) it'd be nice if others opening the folder got a prompt about it.

I suggested it could exist in the `.vscode` folder but the placement isn't critical.

(FWIW, I don't think it should be a warning - just an offer, like the recommended extensions @bpasero mentioned in the comment linked above).

**Comment by weinand** [comment]
@bpasero https://github.com/Microsoft/vscode/issues/45657#issuecomment-372934546 is the latest case where I ran into this problem.

**Comment by bpasero** [comment]
I have renamed this, I think there are multiple cases where we could offer to open the workspace:
* user accidentally opens a workspace file as file and not as workspace
* user opens a folder with 1 workspace file inside
* user opens a folder with N workspace files inside (then we should show a picker)

**Comment by DanTup** [comment]
Sounds great to me :-)

**Comment by bpasero** [comment]
I decided to not do anything for now when the workspace file is opened explicitly. But for the other cases:

Single Workspace File
![image](https://user-images.githubusercontent.com/900690/45938784-82e44900-bfcd-11e8-86db-73adbb3d7a35.png)

Multiple Workspace Files:
![image](https://user-images.githubusercontent.com/900690/45938779-79f37780-bfcd-11e8-8663-bc80958fd8bf.png)

Happy for feedback on the wording.

**Comment by bpasero** [comment]
@DanTup yeah I forgot to mention: it only supports `code-workspace` files in the root currently. I was not aware that projects would also add workspace files in different places. Is that a pattern you have seen?

**Comment by DanTup** [comment]
I haven't seen many projects use workspaces yet (maybe in part because of the lack of this) but I have seen projects that try to avoid IDE-specific files (esp. if the maintainers use many different IDEs). It'd be much easier to have this extra file accepted if it was in the folder with all the other vscode files (I'd also have a personal preference to put mine in there because the root is already a bit bloated with Travis, AppVeyor, tslint, tscobfig, several npm files, etc! :(
