### ISSUE TITLE
EH debugging calls "postDebugTask" too early

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45741]
VS Code Insiders
macOS

- use a random extension project
- build project
- add these tasks:
```json
		{
			"label": "start",
			"type": "shell",
			"command": "say start"
		},
		{
			"label": "end",
			"type": "shell",
			"command": "say end"
		}
```
- In the launch.json set the "preLaunchTask" to "start" and set a "postDebugTask" to "end:
```json
  "preLaunchTask": "start",
  "postDebugTask": "end"
```
- press F5

Observe:
you hear "start" and "end" before the EH window opens. But there is still an active debug session.
After pressing "Stop" there is another "end" (without matching "start").

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/43516
