### ISSUE TITLE
Emmet slow in large files

### ISSUE THREAD

**Issue by SaniJasi** [Microsoft/vscode#45747]
I have a project on Shopify. And for developing I use files like this  `styles.scss.liquid`. 
And emmet working bad... 
For example, I want to create  `font-size: 20px;`
  I use `fz20` and press tab, but emmet generates `font-size: 2px;` but i need `font-size: 20px;`
And emmet working slow, please look this video:  [http://take.ms/kxnE](http://take.ms/kxnE6)

- VSCode Version: Latest
- OS Version: MacOS

Steps to Reproduce:

1. fz20 -> font-size: 2px; (this bug in all files `scss, sass, less, css`)
2. [http://take.ms/kxnE](http://take.ms/kxnE6)

Does this issue occur when all extensions are disabled?: No

**Comment by ramya-rao-a** [comment]
In your video, `fz20` gets expanded to `font-size: 20px` and not `font-size: 2px`. 
The slowness is due to the large size of your file. In the video, you have already crossed 10000 lines.
Do you see slowness in smaller files too?

**Comment by SaniJasi** [comment]
In my video, i recorded only slowness 
>Do you see slowness in smaller files too? - **No**

**Comment by ramya-rao-a** [comment]
Can you share a video that shows `fz20` expanding to `font-size: 2px` ?

**Comment by SaniJasi** [comment]
http://take.ms/wIbDE you can see this bug also in this issue [#38493](https://github.com/Microsoft/vscode/issues/38493)

**Comment by ramya-rao-a** [comment]
Looks like at second 8, we have `w10`

![image](https://user-images.githubusercontent.com/16890566/37485900-09d196d2-284a-11e8-8e56-9625cd0b0999.png)

You add the next 0 and you hit tab to select the completion item before the auto-completion gets updated (because it is slow)

Fixing the slowness will fix this as well.

**Comment by ramya-rao-a** [comment]
Will close this issue in favor of #43470

**Comment by ramya-rao-a** [comment]
@SaniJasi  This is fixed with https://github.com/Microsoft/vscode/commit/91416ffab8a59b6f5a52abef6ff7920a5d067c1f and the fix will be available in tomorrow's [Insiders](https://code.visualstudio.com/insiders) build.

**Comment by SaniJasi** [comment]
Great news! Thank you
