### ISSUE TITLE
Feedback request disappeared after update

### ISSUE THREAD

**Issue by lucianenache** [Microsoft/vscode#45743]
Issue Type: <b>Bug</b>

Hi,

I have opened vscode and been prompted to both complete a feedback survey and update the software.

I have clicked on update the software and planned to complete the feedback survey once the update was complete, but upon restart the feedback survey dialog disappeared and I was not been able to retrieve it anymore.

It would be nice to have a button in the help session where feedback surveys can be accessible with one click.

Maybe some people dislike software that asks for feedback or collects metrics but from my experience as a developer that is really valuable in providing better experiences.

Cheers
Lucian

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.21GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_508028|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
elixir-ls|Jak|0.2.17
halcyon-vscode|bri|0.0.9
scala|dal|0.0.5
vscode-scalafmt|gab|0.1.1
vscode-rust|kal|0.4.2
Go|luk|0.6.77
mssql|ms-|1.3.0
csharp|ms-|1.14.0
color-highlight|nau|2.3.0
java|red|0.20.0
LiveServer|rit|3.2.1
vscode-icons|rob|7.21.0
vscode-spotify|shy|2.3.2
ayu|tea|0.14.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2
markdown-all-in-one|yzh|1.1.0

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
That's too bad... Feedback survey are randomly presented to users. You lose the chance to report when you close the window. May I ask, what language do you usually write with VS Code?

**Comment by lucianenache** [comment]
For now I am using it as a quick editor for multiple languages (in no specific order: Elixir, Java, Scala, C#, Javascript)

**Comment by joaomoreno** [comment]
Here's two surveys you can go through:

- Java: https://www.research.net/r/vscodejava
- JavaScript: https://www.research.net/r/vscode-js

Thanks for your feedback!
