### ISSUE TITLE
Listen to file system events to show git differences faster

### ISSUE THREAD

**Issue by miniyou** [Microsoft/vscode#45752]
### Issue Type
Feature Request

### Description

I do some of my editing in other editors, but I still prefer to use the source control UI in VS Code. However, I always have to click `Refresh` in the source control tab to see the latest changes, whenever those were made outside of VS Code.

Would it be feasible to listen for file system events to trigger refreshing the source control UI when I later go back to VS Code?

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

**Comment by joaomoreno** [comment]
Do file events work in the File Explorer view?

**Comment by miniyou** [comment]
I spent some more time to find the trigger, and it turns out that it _does_ update just fine even for external changes **for files in the workspace**. So I guess the file-watcher is only enabled for the open workspaces, and **not for the folder of the git repository**? My use case is that I keep the web frontend's root folder open in VS Code, but make other concurrent changes to other parts of the monolithic repository.

With that knowledge it makes more sense to me, and I can predict when it will or won't refresh automatically, but I still think it would be useful to watch the entire repository as well. After all, the source control UI reflects the state of all files in the repository, and it sometimes refreshes automatically, so that's what I expected it to do in this case as well.

**Comment by joaomoreno** [comment]
Yeah! Good investigation. It's a known issue: 3025
