### ISSUE TITLE
JSDoc for object props

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#45759]
- VSCode Version: 1.21.0
- OS Version: macOS

I don't get correct type annotation in function parameters even if I do as http://usejsdoc.org/tags-param.html#parameters-with-properties

![image](https://user-images.githubusercontent.com/30043375/37404391-68fbc71e-279a-11e8-9503-18557fc58391.png)

As you can see it says `any` even if it's `boolean`.

**Comment by svipben** [comment]
@mjbvz I tested and seems if I write like this:

```js
// I get autocomplete in sheet which knows I have mapping as boolean
parseData(context, createRecord, row, sheet) {}
```

But if I do as shown in the picture above I don't get correct type annotation in `mapping` or any other variable. Seems working only if I use it as an object not the destructuring.

**Comment by mjbvz** [comment]
Thanks!

This is already tracked upstream by #https://github.com/Microsoft/TypeScript/issues/19645
