### ISSUE TITLE
Use Ctrl+K / Cmd+K by default to clear both integrated terminal and debug console

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#45755]
Feature suggestion: use <kbd>Ctrl+K</kbd> on Windows / <kbd>Cmd+K</kbd> on macOS keyboard shortcut by default to clear both integrated terminal and debug console.

**Comment by isidorn** [comment]
We already have a bunch of deafult keybindings and we are very carefull with introducing new ones.
This one does not seem to be used by the majority of the users and those which want to use can configure it.
Thus I am against this, however we can leave it open and see if it generates some traction.
Thanks for the suggestion though.

**Comment by Deilan** [comment]
@isidorn The problem with setting it by a user is that the user can't set a condition for it:

![image](https://user-images.githubusercontent.com/4777512/37479146-0152c40c-288d-11e8-8767-f9088cc57c2c.png)

This leads to overlapping, hence the user can't use it for both clearing terminal and debug console.

**Comment by isidorn** [comment]
@Deilan this is an issue with our keyboard input widget fyi @sandy081 
as a workaround please open the `keybindiigns.json` and manualy set the when clause.

**Comment by sandy081** [comment]
Updating when clause is treated advanced and hence not supported in the UI.

**Comment by isidorn** [comment]
@sandy081 for example you could open the keybindings.json at the correct position if a use clicks on the when clause.
