### ISSUE TITLE
Dragging a viewzone lags behind

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45764]
Steps to Reproduce:

1. open a find references view zone
2. drag it quickly up and down to resize

=> notice how the viewzone lags quit a bit in updating and even the editor text sometimes goes behind the viewzone

![flicker_chrome58](https://user-images.githubusercontent.com/900690/37406434-72c5c978-2797-11e8-9ca1-436bc5eb1738.gif)

**Comment by alexandrudima** [comment]
Root cause is:

https://github.com/Microsoft/vscode/blob/a8839f858e6c7001262d8219da7593dd28cbdcf9/src/vs/editor/contrib/referenceSearch/media/referencesWidget.css#L12:L16

```
.monaco-editor .zone-widget .zone-widget-container.reference-zone-widget.results-loaded {
	-webkit-transition: height 100ms ease-in;
	transition: height 100ms ease-in;
}
```

@jrieken Blame does not help, as it looks we've had this forever. Should we just remove this rule?

**Comment by bpasero** [comment]
This is very old:

![image](https://user-images.githubusercontent.com/900690/38999374-f41aa0f4-43f1-11e8-96b3-0610d4a1c80d.png)

**Comment by jrieken** [comment]
Yeah, lets nuke it
