### ISSUE TITLE
uninstalled extension keeps asking to be installed at every start-up

### ISSUE THREAD

**Issue by charlierobson** [Microsoft/vscode#45762]
Issue Type: <b>Bug</b>

install an extension
restart vs code
uninstall the extension
restart vs code
pop-up and tab appears asking if I want to install the extension

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1274167|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.14.0
mono-debug|ms-|0.15.8

</details>
Reproduces only with extensions

**Comment by jtth** [comment]
I had the same issue a week ago and solved it by manually deleting the extensions from "~/.vscode/extensions". For me only older extensions were at fault (in my case, ancient themes, years-old ports of Textmate themes).

**Comment by sandy081** [comment]
@ramya-rao-a How about remembering if the user has uninstalled the extension and do not show the recommendations pop up?

**Comment by ramya-rao-a** [comment]
@charlierobson Can you share a screenshot of the message asking you to install the extension? Did you install the said extension from the marketplace or from VS Code itself?

@sandy081 This might not be related to the recommendation pop up but actually related to the one that pops up when trying to install extension from marketplace
