### ISSUE TITLE
UI Improvement - Why you use recycle bin icon for killing task?

### ISSUE THREAD

**Issue by m-farahmand** [Microsoft/vscode#45765]
Hi,
I use vscode for developing angular 5 project but before it I used webstorm.
After that when I want to clear console messages I suddenly click on bin icon and my task being terminate by mistake.
Is there a way to customize theme and controls?

**Comment by dbaeumer** [comment]
@Tyriar this is the delete icon on the integrated terminal.

**Comment by Tyriar** [comment]
The bin icon in our UI means delete. You cannot customize currently, closing in favor of https://github.com/Microsoft/vscode/issues/8017
