### ISSUE TITLE
[css] intellisense no longer suggests justify-content: center

### ISSUE THREAD

**Issue by jsartelle** [Microsoft/vscode#45767]
Issue Type: <b>Bug</b>

Intellisense in CSS no longer offers "center" as a suggestion for "justify-content". Other suggestions appear to be correct.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.29GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_45067|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
selection-encase|Bra|0.0.2
bracket-pair-colorizer|Coe|1.0.20
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
save-without-format|Gru|0.0.1
csharpfixformat|Leo|0.0.64
material-icon-theme|PKi|3.2.5
code-settings-sync|Sha|2.9.0
indenticator|Sir|0.5.0
unity-tools|Tob|0.1.9
lorem-ipsum|Tyr|1.2.0
unity-debug|Uni|1.3.0
quokka-vscode|Wal|1.0.112
map-replace-js|Yuk|0.0.3
rebound-delete|aar|1.1.0
multiline-find-and-replace|axl|0.0.1
openmatchingfiles|bca|0.3.0
path-intellisense|chr|1.4.2
snippetier|daf|0.1.0
dakara-foldplus|dak|1.2.2
jshint|dba|0.10.17
gitlens|eam|8.1.1
vscode-eval|exp|1.2.1
vscode-open-in-application|fab|1.0.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.2
commander|giy|0.2.1
vscode-commandbar|gsp|0.2.20
vscode-text-pastry|jkj|1.2.0
vscode-csharp-snippets|jor|0.3.1
vscode-random|jre|1.3.2
center-editor-window|kai|2.1.1
unity-snippets-modified|lio|0.3.2
code-beautifier|mic|1.7.2
HTMLHint|mka|0.4.0
find-jump|mks|1.2.4
vscode-autoprefixer|mrm|2.1.2
vscode-postcss-sorting|mrm|3.0.1
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.2.0
vscode-css-peek|pra|2.1.0
qub-xml-vscode|qub|1.2.8
vscode-sort-json|ric|1.11.0
block-travel|sas|0.0.2
vscode-3dviewer|sle|0.1.0
rewrap|stk|1.8.0
ayu|tea|0.14.0
vscode-iconfont-preview|und|0.1.0
sensitive-replace|vil|0.1.1
vscode-todo-highlight|way|0.5.11
vscode-clock|yah|1.0.1
markdown-all-in-one|yzh|1.1.0
json-helper|zho|1.0.12
vartypes|zim|0.0.1

(26 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by fengcen** [comment]
Missing `center` property is really annoying.
