### ISSUE TITLE
Odd Explorer Behavior since most Recent Update

### ISSUE THREAD

**Issue by richjdsmith** [Microsoft/vscode#45769]
Issue Type: <b>Bug</b>

Since update, explorer pane seems to be losing things for lack of  a better way to phrase it.

 Folders are not showing all  files within them, (files are still there, a simple $ls shows that much), folders are not opening, file order is wrong and on occasion, files are out of heiarchy order (showing up in folder above the folder they are actually in),

 Almost as if it is running out of cache space to handle folders. 

Project size is normal (simple rails CRUD app). Well, I do have node_modules, so maybe there is half the weight of the sun in there :/

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.20
erb|Cra|0.0.1
beautify|Hoo|1.3.0
elixir-ls|Jak|0.2.17
vscode-wakatime|Wak|1.1.24
html-css-class-completion|Zig|1.17.1
ruby-on-rails-snippets|ate|0.0.1
spellright|ban|2.1.30
bulma|dem|0.0.4
githistory|don|0.4.0
auto-rename-tag|for|0.0.15
ruby|gro|0.0.6
path-autocomplete|ion|1.8.1
ruby-rubocop|mis|0.7.0
HTMLHint|mka|0.4.0
vscode-scss|mrm|0.6.2
python|ms-|2018.2.1
sublime-keybindings|ms-|3.0.3
color-highlight|nau|2.3.0
vetur|oct|0.11.7
sass-indented|rob|1.4.8
guides|spy|0.9.1
ayu|tea|0.14.0
highlight-matching-tag|vin|0.4.4
simple-ruby-erb|vor|0.2.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
Please disable all your extensions and try to reproduce.
If that does not help try with latest vscode insiders https://code.visualstudio.com/insiders/
