### ISSUE TITLE
Inconsistent driver letters in debugger and integrated terminal

### ISSUE THREAD

**Issue by IgorNovozhilov** [microsoft/vscode#45760]
Inconsistent driver letters in debugger and integrated terminal. `see Steps to Reproduce`
To work correctly, you need to bring both driver letters, to either lowercase or uppercase.
Otherwise, problems arise when importing modules in NodeJS debug mode, similar to this: https://github.com/webpack/webpack/issues/2362, is when the same module is imported twice and receives different instances executable code

- VSCode Version:
Версия 1.22.0-insider
Фиксация a716373aaaf50cbce3618688a645b324721b35dd
Дата 2018-03-14T05:15:41.910Z
Оболочка 1.7.9
Отрисовщик 58.0.3029.110
Узел 7.9.0
Архитектура x64

- OS Version: win7 pro

Steps to Reproduce:

1. run code `console.log(require('path').resolve('./test'));` in integrated terminal
![image](https://user-images.githubusercontent.com/3082812/37404175-23844fd2-27a2-11e8-8b5a-9c3f6c6000b5.png)

2. run code `console.log(require('path').resolve('./test'));` in debugger
![image](https://user-images.githubusercontent.com/3082812/37404206-4518a3e6-27a2-11e8-94fe-d238ed137c1d.png)

see:
https://github.com/nodejs/node/issues/6624

**Comment by IgorNovozhilov** [comment]
Repeated in VSCode
Версия 1.21.0
Фиксация 9a199d77c82fcb82f39c68bb33c614af01c111ba
Дата 2018-03-07T11:04:09.969Z
Оболочка 1.7.9
Отрисовщик 58.0.3029.110
Узел 7.9.0
Архитектура x64

**Comment by Tyriar** [comment]
I seem to recall it's this way in the terminal for a reason, because some tool was failing when lowercase was being used. @weinand any thoughts on this?

**Comment by weinand** [comment]
@Tyriar VS Code normalizes drive letters to lower case when converting paths into urls and vice versa.

And the VS Code debugger started to do the same in the last milestone (see https://github.com/Microsoft/vscode/issues/43959). So expanded variables use lower case drive letters.

But see my comment https://github.com/Microsoft/vscode/issues/43959#issuecomment-366640506 why this doesn't help in cases where the drive letter casing comes from outside of VS Code.

**Comment by Tyriar** [comment]
@weinand 

https://github.com/Microsoft/vscode/blob/1d026bbff95990e9ac381a2be85f54d2c7ba32d8/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L995-L1001

And I found the answer to why it's uppercase: https://github.com/Microsoft/vscode/issues/9448

**Comment by IgorNovozhilov** [comment]
Here's another example where the behavior is different
![2018-03-16_07h55_02](https://user-images.githubusercontent.com/3082812/37504466-97cd9b5c-28ef-11e8-9b00-dab5d3b2410f.png)
![2018-03-16_07h55_59](https://user-images.githubusercontent.com/3082812/37504468-9954e020-28ef-11e8-81c8-5efc3432a9c5.png)

**Comment by DonJayamanne** [comment]
@Tyriar @weinand 	
Not sure whether this is the right place, but didn't want to create a separate issue:
* Users use the token `${workspaceFolder}` in our `launch.json`
* This gets translated by VSC to upper case drive letters
* When adding breakpoints, VSC uses lower case drive letters
* This is causing problems in the Python Debugger.

I've traced the problem to the faact that the `ConfigurationResolverService` is inheriting the `AbstractVariableResolverService` which in turn normalizes the drive letters to `uppercase` using code from `labels.ts`. I.e. we're resolving variables with logic used for display purposes.

**Work around in Python Extension**
* The only temporary solution we have for the python extension is to create a hook for the `resolveDebugConfiguration` and replace all `${workspaceFolder}` tokens manually with a lower case drive letter.

**Comment by weinand** [comment]
@DonJayamanne please create a new issue for this.
