### ISSUE TITLE
How can I restart the extension host (to reactivate my extension)?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45774]
There are a couple of places where I tell the user they need to `Reload Window` and give them a button that executes `workbench.action.reloadWindow` because we need to re-run all startup code and reset state (eg. they change the current SDK version they're using).

Recently in https://github.com/Microsoft/vscode/issues/45399#issuecomment-371886850 @bpasero mentioned that adding workspace folders only "restarted the extension host", which is much less disruptive.

I can't find any API or commands to do this myself; but it would be a much better experience if I could just do that in the background rather than prompting the user to do a full Window Reload.

Is it possible?

**Comment by DanTup** [comment]
Possibly - it might need some refactoring though. There's a lot of state and a lot of code in `extension.activate()` (we spawn all processes and all sorts). It wasn't really written with restarting in mind so I'm not confident we currently put everything we should into `subscriptions`.

If you don't want to expose this, I'm happy to investigate that though - reloading the extension without restarting the extension host would be even better; I guess I was just looking for an easy way out (thinking it might already exist and it would be a quick change from prompting for Reload).

**Comment by jrieken** [comment]
> reloading the extension without restarting the extension host would be even better;

This is unlikely to ever happen as we cannot unload the V8 context you are in, that means we don't control the scope and cannot reset state of other scripts, e.g. stateful npm modules

> thinking it might already exist and it would be a quick change from prompting for Reload

It exists, but mostly to recover from extension host crashes and when switching between single and multiple workspace folder. I am not comfortable to expose this as API (or API-like-command) because it's the big hammer and the last resort.

**Comment by DanTup** [comment]
Understood. I've opened https://github.com/Dart-Code/Dart-Code/issues/694 to investigate doing silently reload internally.

**Comment by jrieken** [comment]
OK, closing for now, please come back to this issue if internally reloading needs support from our side.

**Comment by DanTup** [comment]
I added a command that calls `deactivate`, then `dispose()` on everything in `subscriptions` and then calls `activate` again. Seems to be working OK (with some minor supporting changes).

```ts
context.subscriptions.push(vs.commands.registerCommand("_dart.reloadExtension", (_) => {
	deactivate();
	for (const sub of context.subscriptions) {
		try {
			sub.dispose();
		} catch (e) {
			console.error(e);
		}
	}
	activate(context);
}));
```

I don't think it'd be a bad thing to have an API to wrap it up, but this is all good for me for now! 👍
