### ISSUE TITLE
Feature request: Open a file in a new window. (multiple monitor)

### ISSUE THREAD

**Issue by Domvel** [Microsoft/vscode#45771]
Feature request: Open a file in a new window. Helpfully for muliple monitors. Just hit "open in a new windows" (like atom has) and snap the window with aero snap to the next monitor. 
Or is there already a way to do this? Maybe it will help, if the vs code editor can have mutliple instances.

Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Datum 2018-03-07T11:04:09.886Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur ia32
OS; Windows 10 Pro 64-bit

**Comment by Domvel** [comment]
Ok a workaround is to open a new instance with `CTRL` + `Shift` + `N` and open the same project / folder.
But maybe it's better by click on a file or tab and choose `Open in a new window`

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/37411412-0708e222-27a3-11e8-927b-1635f87247fd.png)

**Comment by Domvel** [comment]
Thanks! But perhaps this should also available in tab context menu. shouldn't?
