### ISSUE TITLE
auto import only shows suggestions for current folder in multi-root workspace

### ISSUE THREAD

**Issue by marcelh-gh** [Microsoft/vscode#45778]
VSCode Version: 1.21.0
TypeScript Version: 2.7.2
OS Version: Window 10 (1709)

**Comment by mjbvz** [comment]
Please provide an example

**Comment by marcelh-gh** [comment]
two folder muli-root workspace: **folder1** & **folder2**...

**folder1**

**_A.ts:_**

```
export function alpha() {
    return "alpha";
}
```

**folder2**

**_B.ts_**

```
export function beta() {
    return "beta";
}
```

**_C.ts_**

```
console.log(alpha()); // no suggestion for alpha
console.log(beta()); // suggestion for beta & import statement generation work fine
```

@mjbvz thanks for the quick reply. please let me know if you need more info.

**Comment by marcelh-gh** [comment]
@mjbvz do you know how the native VS Code auto import compares to the extension "Auto-Import" ?
The VS Code team reached out to the maintainer last October...  [see this post](https://github.com/soates/Auto-Import/issues/71)
Unfortunately, as far as I can tell, the multi-root workspace support has the same issue (version 1.5.3).

**Comment by mjbvz** [comment]
This is the correct behavior.

You can think of folders more like "projects" in this context. If your projects have dependencies, you should declare these in the `package.json`

**Comment by marcelh-gh** [comment]
@mjbvz ok, thank you! :-)
