### ISSUE TITLE
Syntax highlighting is broken after line breaks in markdown files

### ISSUE THREAD

**Issue by robinparisi** [Microsoft/vscode#45777]
- VSCode Version: 1.21.0
- OS Version: macOS Sierra

Steps to Reproduce:

1. Create a markdown file (ex: test.md) 
2. Insert the following markup

```html
<main>
    <div>
       <a href="/test.html" class="plop">Sit Condimentum Porta</a>
    </div>

    <div>
       <a href="/test.html" class="plop">Sit Condimentum Porta</a>
    </div>
</main>
```

The syntax highlighting doesn't seems to work after line break:

![line-break](https://user-images.githubusercontent.com/570975/37413812-1c9eca2a-27a8-11e8-9057-f216398e4037.png)

The same with no line break:

![capture d ecran 2018-03-14 a 16 51 27](https://user-images.githubusercontent.com/570975/37413748-fa76c5ba-27a7-11e8-8dc6-b6479956cd60.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The syntax highlighting is correct. Html tags generally cannot contain blank lines in markdown. Just try it in github or with the [commonmark dingus](http://spec.commonmark.org/dingus/):
<img width="994" alt="screen shot 2018-03-14 at 9 00 03 am" src="https://user-images.githubusercontent.com/12821956/37414340-2039df7c-2766-11e8-96c6-b82cce2c44b4.png">
