### ISSUE TITLE
missing 1.21 package as RPM

### ISSUE THREAD

**Issue by raytracer-dreamwalker** [Microsoft/vscode#45781]
Steps to Reproduce:
Go to: https://packages.microsoft.com/yumrepos/vscode/
Latest release is "code-1.20.1-1518536126.el7.x86_64.rpm"

**Comment by joshsleeper** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/45500

just hard to find that one with github search because neither "yum" nor "rpm" find it.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/45868
