### ISSUE TITLE
No terminal console when running VScode as user

### ISSUE THREAD

**Issue by meichthys** [Microsoft/vscode#45786]
Issue Type: <b>Bug</b>

I haven't been able to test this on other computers, but when running VSCode in a regular user account, the integrated terminal is blank. Clicking the '+' button just opens another blank terminal with no interactive prompt. I've tried rebooting, disabling all extensions, reinstalling vscode, resetting my settings to default, and checking the developer tools console. I'm seeing all the same things as @mtpultz saw in issue #40175.
Related to: #45570

Everything works as expected when running as Admin.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz (8 x 2893)|
|Memory (System)|31.94GB (25.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

The only error that shows up in the Debug console after trying to open integrated terminal:
![untitled](https://user-images.githubusercontent.com/10717998/37422347-7599130e-2791-11e8-8daf-5498b855134b.png)

**Comment by mtpultz** [comment]
Thanks for the mention, this is still an issue on my desktop, but it doesn't seem to be resolved itself when running VSCode as an admin.

**Comment by meichthys** [comment]
This issue is still manifest after the latest update to v1.12.1

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169

**Comment by mtpultz** [comment]
@tyriar 43169 is a duplicate of 40175 which is the same issue that was force closed with no resolution 3 months ago

**Comment by Tyriar** [comment]
@mtpultz Windows_NT x64 6.1.7601 is Windows 7 so he's definitely seeing #43169

**Comment by mtpultz** [comment]
Hi @Tyriar that message was actually for you indicating that #43169 regardless of OS is actually a duplicate of #40175 that was unresolved, closed, and eventually locked since I've been thinking for 3 months I was the only one with this issue
