### ISSUE TITLE
Don't request codefixes if errors are out of date

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#45785]
See the discussion at https://github.com/Microsoft/TypeScript/issues/21607#issuecomment-363988238. It may happen that:

* Errors are sent.
* The user types some things.
* VSCode requests code fixes for the old errors -- but the locations are all wrong, we land on a node of an unexpected type, and we throw an exception (which gets logged in telemetry as a bug).

We've spent some time searching for the obvious cases and aborting without an error, but ideally we would not receive such requests and could go back to casting to the correct node type and treating something else as an error. (That way we don't silently fail when there's a legitimate bug.)

**Comment by roblourens** [comment]
@mjbvz Verification steps?

**Comment by mjbvz** [comment]
See https://github.com/Microsoft/TypeScript/issues/21607

To verify, confirm that no errors are print in the typescript output window for that case
