### ISSUE TITLE
VS code treats copy as an undoable action which prevents redoing.

### ISSUE THREAD

**Issue by alexwilli** [Microsoft/vscode#45793]
- VSCode Version: 1.19.1
- OS Version: Ubuntu 16.04.4

Steps to Reproduce:

1. Make a change
2. Undo the change
3. Copy something
4. Try redoing. Nothing happens.

Copy is being treated as an undoable action. If you copy and then undo, nothing happens. You have to undo a second time to undo the last change you made.

**Comment by rebornix** [comment]
I didn't see this issue in latest version, @alexwilli can you help confirm that?

**Comment by alexwilli** [comment]
Just upgraded to 1.26. Seems to be fixed. Thanks for letting me know!
