### ISSUE TITLE
Selection find all similar strings but with case insensitive

### ISSUE THREAD

**Issue by ueeieiie** [Microsoft/vscode#45791]
- VSCode Version: 1.21.0
- OS Version: Windows 10 Pro x64

**Steps to Reproduce:**

 create 2 variables with the same string value, and select 1 of them: 

1.  in CamelCase
1.  in lowercase

notice it highlight both of them even though they aren't the same.

**Does this issue occur when all extensions are disabled?:**  Yes

![case insensitive bug](https://user-images.githubusercontent.com/20313819/37425864-98b4c720-27cd-11e8-85bf-6222bd664021.jpg)

**Comment by rebornix** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/43190 .
