### ISSUE TITLE
[json] schema downloader should support NODE_EXTRA_CA_CERTS

### ISSUE THREAD

**Issue by jhr007** [microsoft/vscode#45792]
Same as #27209
> file: 'file:///c%3A/path/to/jsconfig.json'
> severity: 'Warning'
> message: 'Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/jsconfig.json': Unable to load schema from 'https://schemastore.azurewebsites.net/schemas/json/jsconfig.json': Unable to connect to https://schemastore.azurewebsites.net/schemas/json/jsconfig.json. Error: self signed certificate in certificate chain'
> at: '1,1'
> source: ''
> code: 'undefined'

**Steps to Reproduce:**
1. Be Behind a corporate SSL man-in-the-middle firewall 
2. Trigger vscode to download a jsonschema, in my case jsconfig.json

I'm trying to avoid using `strictSSL` to disable SSL. Knowing me, I might turn it off and never remember to turn it back on. 

I've fought private SSL Certificate Authority issues with npm and [nvs](https://github.com/jasongin/nvs/) and got various self signed certificate in chain errors. This led to the discovery of the node's environment variable `NODE_EXTRA_CA_CERTS` that I set to point to a .pem file containing my corporate CA. 

This `self signed certificate in certificate chain` message reminds me of nvs's message, which I believe originates from node's `http(s)` library. 

I haven't had any problem downloading extensions, its just the jsonschema downloader. 

**Help->about:** 
Windows 10
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by zspitz** [comment]
@jhr007 How did you set environment variables for Node when used from VS Code?

**Comment by jhr007** [comment]
I set the environment variable using windows. It was for npm/node being used from cmd line before installing VS Code.

I never found a certificate authority key in the VS Code settings, but `http.proxyStrictSSL` alludes to something in the comments.

Windows Start menu 
-> type “Edit env”
-> click “Edit environment variables for your account”
->  click new under variables for your_username
-> name: NODE_EXTRA_CA_CERTS
-> value: c:\certs\cacert.pem


```
{
  "resource": "/c:/path/to/the_project/jsconfig.json",
  "owner": "_generated_diagnostic_collection_name_#0",
  "code": "undefined",
  "severity": 4,
  "message": "Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/jsconfig.json': Unable to load schema from 'https://schemastore.azurewebsites.net/schemas/json/jsconfig.json': Unable to connect to https://schemastore.azurewebsites.net/schemas/json/jsconfig.json. Error: self signed certificate in certificate chain",
  "startLineNumber": 1,
  "startColumn": 1,
  "endLineNumber": 1,
  "endColumn": 2
}
```

**Comment by shamsup** [comment]
I'm getting a similar error on macOS 10.13 behind a corporate MITM firewall when viewing a `package.json` file:

```
Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json':
Unable to load schema from 'https://schemastore.azurewebsites.net/schemas/json/package.json':
Unable to connect to https://schemastore.azurewebsites.net/schemas/json/package.json.
Error: unable to get local issuer certificate
```

I have tried setting the environment variable prior to running VSCode in various ways (inline on command line, exporting on command line, `.bashrc`), but it doesn't appear that setting the `NODE_EXTRA_CA_CERTS` environment variable works for me. 
(note: it does work when running node programs that use HTTPS connections)

When viewing the developer console in VSCode, I can see that the variable is set in the `process.env` object:

```
> process.env.NODE_EXTRA_CA_CERTS
< "/Users/username/extra-certs.pem"
```

Is there another way to force this for VSCode? I am definitely trying to avoid disabling SSL verification.

**Comment by TillFProtzek** [comment]
I hope this get resolved.
Setting http.proxyStrictSSL to false is working, but this can't be a permanent solution.
VSCode needs a setting either to include a self signed root-ca, or a setting to ignore self signed certificate errors.

**Comment by rebornix** [comment]
Not sure how this got assigned to me, sorry for not responding for a while. @aeschli assigned to you first as it's about json schema.

**Comment by aeschli** [comment]
We now use the proxy settings and certificates known to Electron/Chromium which gets it from the OS.
Please reopen if this is still an issue.
