### ISSUE TITLE
Help > View License not redirecting properly

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4579]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Help -> View License

Actual:
Redirects to http://www.microsoft.com/en-us/

Expected:
Redirect to https://code.visualstudio.com/license#vscode

**Comment by chrisdias** [comment]
I think what is going on is that we removed the #vscode from the licenseURL in product.json which means code is now calling http://go.microsoft.com/fwlink/?LinkID=533485, appending `?lang=en`.  It should use & instead of ?.  So, we should append &lang=en instead of ?lang=en.

**Comment by egamma** [comment]
@dbaeumer can you verify this on a clean German machine. When I tried to verify it on my hybrid version I still got the hybrid version.

**Comment by dbaeumer** [comment]
I will.

**Comment by dbaeumer** [comment]
Here is what I see: Clicking on 'Lizenz anzeigen' opens a browser with the URL https://code.visualstudio.com/license?lang=de

which I think is correct. The page stills shows an English pre license so.

**Comment by chrisdias** [comment]
yes, this is correct url. when we push a new build of the website it will redirect to the localized page.
