### ISSUE TITLE
Release 1.21 isn't available via yum

### ISSUE THREAD

**Issue by lnunno** [Microsoft/vscode#45796]
Really looking forward to using the new version on Centos, but it's not currently available.

The release 1.21 isn't available via yum.

VSCode Version: 1.21
OS Version: Centos 7.3
Steps to Reproduce:

yum update
the last version available is 1.20.1
Reproduces without extensions: N/A

Thanks!

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/45868
