### ISSUE TITLE
default lauch.json for new node app has empty configurations

### ISSUE THREAD

**Issue by curtw** [Microsoft/vscode#458]
Using VS Code 0.10.1 on Mac OS 10.10.5
1) create and cd into a new project directory
2) invoke "npm init" and specify "entry point" file (i.e. "main" in package.json)
3) create the entry point file (i.e. index.js)
4) invoke "code ."
5) switch to debug view and click the gear icon or press "run"

Expect result:  launch.json should include configurations for "Launch index.js" and "Attach" with "type":"node" and other needed parameters.

Actual result: launch.json configurations is [], an empty array, i.e.

	{
		"version": "0.2.0",
		"configurations": []
	}

**Comment by isidorn** [comment]
After step 5) do you see a list of debug environments in the quick pick ui? Do you pick NodeJS here?

![screen shot 2015-11-23 at 09 42 37](https://cloud.githubusercontent.com/assets/1926584/11332515/95680842-91c6-11e5-91e6-38fda96e616b.png)

We only generate an empty array if you do not pick anything in this quick pick ui.

**Comment by curtw** [comment]
I tested again, saw the list of debug environments, and verified that selecting Node.js here creates launch.json correctly.

However, it is very easy to miss the prompt for debug environments because it is visually disconnected from the click that initiated it.  One stray click and you are stuck with an empty configurations array.  I think many people will face this issue.

As a quick fix, how about adding "Empty" to the list of environments and continue to re-prompt for the environment until one is explicitly selected.  This would avoid case where missing it the first time puts you into a bad state.

**Comment by isidorn** [comment]
We improved this experience a bit. Now whenever a user has an empty configuration, or a really broken launch.json we show the debug environment picker again. So if you miss it for the first time we will prompt until one is explicitly selected. This way we hope to make it more discoverable.

This will be availble in our next monthly release, so check it out then and let us know what you think.
