### ISSUE TITLE
 this._xterm.setHypertextLinkHandler is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#45805]
Issue Id: <b>525d7efc-c78d-977c-3588-6f4f781d681a</b><br /><br />*Versions* <br />- 1.21.0<br />-  c63189deaa8e620f650cc28792b8f5f3363f2c5b<br />-  f88bbf9137d24d36d968ea6b2911786bfe103002<br />*Stack* <br />TypeError: this._xterm.setHypertextLinkHandler is not a function<br />[/vs/workbench/services/configuration/common/configurationModels.ts#239:9 (self)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/configuration/common/configurationModels.ts#L239:9 (self))<br />[/vs/base/common/platform.ts#120:25 (selectionStartLineNumber)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/platform.ts#L120:25 (selectionStartLineNumber))<br />[/vs/editor/common/commonCodeEditor.ts#449:4 (revealPositionInCenterIfOutsideViewport)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/commonCodeEditor.ts#L449:4 (revealPositionInCenterIfOutsideViewport))<br />[/vs/editor/common/commonCodeEditor.ts#391:8 (VK_RIGHT)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/commonCodeEditor.ts#L391:8 (VK_RIGHT))<br />[/vs/workbench/services/keybinding/common/windowsKeyboardMapper.ts#606:2 (ResizePaneRightTerminalAction)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/keybinding/common/windowsKeyboardMapper.ts#L606:2 (ResizePaneRightTerminalAction))<br />[/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#452:95 (KEYBINDING_CONTEXT_TERMINAL_FOCUS)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#L452:95 (KEYBINDING_CONTEXT_TERMINAL_FOCUS))<br />[/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#455:3 (define)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#L455:3 (define))<br />[/vs/base/common/winjs.base.raw.js#1483:0 (len)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1483:0 (len))<br />[/vs/base/common/winjs.base.raw.js#382:0 (error)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L382:0 (error))<br />[/vs/base/common/winjs.base.raw.js#1105:0](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1105:0)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: this._xterm.setHypertextLinkHandler is not a function<br />[/vs/workbench/services/configuration/common/configurationModels.ts#239:9 (self)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/configuration/common/configurationModels.ts#L239:9 (self))<br />[/vs/base/common/platform.ts#120:25 (selectionStartLineNumber)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/platform.ts#L120:25 (selectionStartLineNumber))<br />[/vs/editor/common/commonCodeEditor.ts#449:4 (revealPositionInCenterIfOutsideViewport)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/commonCodeEditor.ts#L449:4 (revealPositionInCenterIfOutsideViewport))<br />[/vs/editor/common/commonCodeEditor.ts#391:8 (VK_RIGHT)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/commonCodeEditor.ts#L391:8 (VK_RIGHT))<br />[/vs/workbench/services/keybinding/common/windowsKeyboardMapper.ts#606:2 (ResizePaneRightTerminalAction)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/keybinding/common/windowsKeyboardMapper.ts#L606:2 (ResizePaneRightTerminalAction))<br />[/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#452:95 (KEYBINDING_CONTEXT_TERMINAL_FOCUS)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#L452:95 (KEYBINDING_CONTEXT_TERMINAL_FOCUS))<br />[/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#455:3 (define)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#L455:3 (define))<br />[/vs/base/common/winjs.base.raw.js#1483:0 (len)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1483:0 (len))<br />[/vs/base/common/winjs.base.raw.js#382:0 (error)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L382:0 (error))<br />[/vs/base/common/winjs.base.raw.js#1105:0](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1105:0)<br />

**Comment by Tyriar** [comment]
I believe this is fixed, there are no more references to `setHypertextLinkHandler` in vscode or xterm
