### ISSUE TITLE
Selecting multiple lines with the Option key (Feature request)

### ISSUE THREAD

**Issue by Josema** [Microsoft/vscode#45800]
This example is from Sublime:
![vscode](https://user-images.githubusercontent.com/1819888/37432452-a84f1a0e-27d8-11e8-866f-c4436cfec109.gif)

**Comment by yume-chan** [comment]
The default shortcut for square selection is <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Mouse Left Drag</kbd> on Windows, should also be a equivalence on macOS.

**Comment by tsalinger** [comment]
This feature already exists and is documented here: https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_multi-cursor-selection
