### ISSUE TITLE
Please make the debug toolbar moveable.

### ISSUE THREAD

**Issue by dzearing** [Microsoft/vscode#4580]
![image](https://cloud.githubusercontent.com/assets/1110944/13966295/e6fd1a6e-f02e-11e5-887c-971abd7bbd41.png)

- VSCode Version: 0.10.11
- OS Version: mac

Steps to Reproduce:

1. Start debugging something
2. Try to read the filename that the debug toolbar is covering up
3. Try to move the toolbar
4. Hold your temper in when you accidentally stop your debugging process

Expected: some gripper that lets me move it to the side so i can see the filename
Resulted: can't move, even it were just positioned to the far right, then at least i could see the filename it's currently covering up.

**Comment by stevencl** [comment]
As we discussed in the UX meeting, we should also consider a design where the toolbar slides in and out of view. Initially it would be in view but would then animate (slide upwards) until only the bottom edge of the toolbar was visible. When the mouse is moved to hover over the area it slides down.

If this doesn't work well we then suggested we should explore the ability to drag the toolbar horizontally.

**Comment by isidorn** [comment]
@stevencl we got a very strong feedback in the standup today that the skype animation box is very painful to use. So we decided to first try with the horizontal move and if that does not work then try the animation.

**Comment by jan-zajic** [comment]
+1 it's very annoying

**Comment by cdaringe** [comment]
i. am. SO EXCITED about this! @isidorn, you rock man

**Comment by yunnysunny** [comment]
The problem exists now.

vs code version : 1.9.1
os version : win10

![The debug bar can not been moved](http://silian.whyun.com/images/error_vs_debug.png)

I can't move the debug bar. The problem annoys me seriously

**Comment by isidorn** [comment]
@yunnysunny sorry about that, here's the issue with a workaround https://github.com/Microsoft/vscode/issues/20298
You can also switch to vscode insiders which has this fixed or wait a couple of days for a new stable version which contains a fix.
