### ISSUE TITLE
MacOS touchbar support for debugger no longer works

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#45801]
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T10:54:22.798Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

![image](https://user-images.githubusercontent.com/1018196/37432707-89fbd782-2796-11e8-949f-938378c53562.png)

The touchbar keys don't show up while debugging anymore. Only `esc` key shows up.

Tested for both nodejs and python debugging

**Comment by isidorn** [comment]
@nojvek in the picture aboe you are not in a debug session. So I do not see anything invalid, there is only the start button, once you touch that more buttons should appear.
Or am I getting this wrong @bpasero

**Comment by nojvek** [comment]
After restarting my mac, it seems things started to work fine. I can't repro it anymore 😮
