### ISSUE TITLE
Clicking on File in Explorer no longer goes to new tab after update

### ISSUE THREAD

**Issue by wcalvert88** [Microsoft/vscode#45817]
Issue Type: <b>Bug</b>

After I updated my VSC now when I click on files in my project folder it only opens two tabs and the second one disappears if I click a third file unless I drag it into the tabs section.

I know up until an hour ago I click on a file in the explorer and it would open it up most of the time in a new tab so I could leave them all open easier.  Is there a fix?

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-3500M APU with Radeon(tm) HD Graphics (4 x 1497)|
|Memory (System)|7.48GB (1.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tidyhtml|anw|1.10.0
bracket-pair-colorizer|Coe|1.0.20
auto-rename-tag|for|0.0.15
mssql|ms-|1.3.0
vetur|oct|0.11.7

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
@wcalvert88 any chance you can share a screencast of what you see?

**Comment by wcalvert88** [comment]
I figured it out it only does it if there are no changes to the file.  If the file gets modified it will add a new tab when clicking a different file

**Comment by bpasero** [comment]
@wcalvert88 demo please. it is true however that a dirty file will not change its contents if changed outside because otherwise your contents are getting lost.

**Comment by wcalvert88** [comment]
![visualstudiocodeappjs](https://user-images.githubusercontent.com/34796868/37522450-4f8dadb8-28fa-11e8-9636-bf0528dbda40.jpg)

So in the first picture I clicked on app.js and it pulls it up in the tab.
![visualstudiocodeindexjs](https://user-images.githubusercontent.com/34796868/37522475-68435560-28fa-11e8-9159-c03b21c3e5b4.jpg)

in the second picture I click index.js and want them up at the same time but instead it just takes over app.js in the tabs.
![visualstudiocodebothonlycausechange](https://user-images.githubusercontent.com/34796868/37522481-6d18e6fe-28fa-11e8-97f5-495c6297b557.jpg)

in the last picture I put a semicolon in app.js didn't save and clicked index.js and it opened index.js in a new tab.   What I was wanting and what I thought used to happen was I just click and it brings it up in a new tab with or without changes being done to the already open file.

**Comment by bpasero** [comment]
Ok got it, you want to configure:  `"workbench.editor.enablePreview": false` to leave tabs fully opened when other tabs open.

**Comment by wcalvert88** [comment]
Thank you! That's exactly what I wanted.
