### ISSUE TITLE
The cursor sometimes is thick and sometimes is thin.

### ISSUE THREAD

**Issue by IIInsomnia** [Microsoft/vscode#45819]
![image](https://user-images.githubusercontent.com/6582246/37441622-52e7b962-283d-11e8-9188-b1fb951162a1.png)

![image](https://user-images.githubusercontent.com/6582246/37441627-593c6a9c-283d-11e8-9213-4157ec9e3866.png)

**Comment by alexandrudima** [comment]
@IIInsomnia Are you using a non 0 value for `window.zoomLevel` ?
