### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#45812]
Issue Id: <b>ae36a14a-f150-19d5-e279-f541a9791e74</b><br /><br />*Versions* <br />- 1.21.0<br />-  a903bd38fbe9006c076d218ff69fe1ee0160f815<br />-  d7dca142ad6051e6b1c7397ea73221feb0160f21<br />-  b76a4a71434d6cdee69fa1d8bdc7533d09598d53<br />*Stack* <br />TypeError: Cannot read property 'id' of undefined<br />[/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#420:53](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L420:53)<br />    at Array.map (native)<br />[/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#419:27 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L419:27 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1183:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#865:0 (enter)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L865:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#1081:0 (_run)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1081:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#1049:0 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1049:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1183:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#865:0 (enter)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L865:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#1081:0](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1081:0)<br />

**Comment by sandy081** [comment]
Duplicate of #45811
