### ISSUE TITLE
Wrong highlighting when using tag interpolation. Pug

### ISSUE THREAD

**Issue by lucasdavidferrero** [Microsoft/vscode#45814]
- VScode version: 1.21.1
- OS: Ubuntu 16.04.4 LTS
- Architecture: x64
- Extensions: open-in-browser, VScode Great Icons

Description: When I use tag interpolation in Pug and add some text to it, the editor highlights the content as if this were an element. I think you'll better see this in the following image:
![image](https://user-images.githubusercontent.com/15804058/37436741-3b1d1c48-27c8-11e8-8480-ab9a66674c3a.png)

It's just a tiny issue but It'd be nice if someone could fix it.
Regards!

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
@lucasdavidferrero I dont know anything about pug.. can you elaborate on what the issue here is?

> editor highlights the content as if this were an element

In your screenshot which text is getting highlighted  as element? And how should it look like otherwise?

**Comment by lucasdavidferrero** [comment]
@ramya-rao-a  Hi, I'm using tag interpolation in Pug, you can read more [here](https://pugjs.org/language/interpolation.html#tag-interpolation). The issue is that VScode highlights with an element's color (blue in this case) text content of an <a> and a <div>, as is shown in the screenshot. It should be treated as plain text (i.e the "dummy div" text) so in this case, It must be white.
Of course, this is purely stylistic and nothing affects the output but I just wanted to express this tiny issue.

This could help you:
#[htmlElement(class="nice-class") textContent]
The text content is just plain text and It's highlighted as if it were an element. When I say highlighted I mean the color of the text.

**Comment by aeschli** [comment]
This issue was moved to davidrios/jade-tmbundle#92

**Comment by davidrios** [comment]
The example works perfectly fine on Sublime Text:

![screenshot from 2018-03-16 10-08-46](https://user-images.githubusercontent.com/1418372/37522321-52e49cf8-2902-11e8-98b7-0572675fbc5a.png)
![screenshot from 2018-03-16 10-09-08](https://user-images.githubusercontent.com/1418372/37522322-5312f350-2902-11e8-9c78-44509ea27024.png)
![screenshot from 2018-03-16 10-09-22](https://user-images.githubusercontent.com/1418372/37522323-533b1088-2902-11e8-8604-4cceecff434f.png)
![screenshot from 2018-03-16 10-09-59](https://user-images.githubusercontent.com/1418372/37522325-536e9c82-2902-11e8-90bf-d6dc97daab5b.png)

Please note that the bundle does not officially support VSCode.
