### ISSUE TITLE
Unnecessary asterisk when typing 'Enter' in yield function

### ISSUE THREAD

**Issue by huarse** [Microsoft/vscode#45818]
![qq20180315-092355-hd](https://user-images.githubusercontent.com/3724927/37439413-f85419f0-2832-11e8-801b-01890e770cc7.gif)

- VSCode Version: 1.21.0
- OS Version: MacOS 10.13.3

Does this issue occur when all extensions are disabled?:  Yes

**Comment by mjbvz** [comment]
Duplicate of #43469
