### ISSUE TITLE
Character displaying IME disappears

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#45823]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Type any Japanese characters using japanese IME
2. Switch to another window without closing the candidate list (without determining the character from the candidate  list)
3. Return to VSCode window
4. bug

![bug](https://user-images.githubusercontent.com/8474118/37442715-2e75cc5a-284b-11e8-9abf-55ea96aab881.gif)

VS Code version: Code - Insiders 1.22.0-insider (a716373aaaf50cbce3618688a645b324721b35dd, 2018-03-14T05:15:41.910Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|Memory (System)|7.95GB (3.07GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

Reproduces only with insiders

**Comment by EbXpJ6bp** [comment]
I can still repo this in editor and input area in DEBUG CONSOLE.

**Comment by alexandrudima** [comment]
@rebornix Could this be a regression from 4e3383f15d925e350a33167665eb2aaf0f84c8ac or 2b941e427c38ee786e7ced495afd7c5dc5538eb3

**Comment by rebornix** [comment]
thanks @alexandrudima , yes it's a regression from that change.

Reverted that commit and I'll work on that issue for Monaco.
