### ISSUE TITLE
Auto save "onFocusChange" and saving as admin is hard

### ISSUE THREAD

**Issue by OpportunityLiu** [Microsoft/vscode#45827]
Issue Type: <b>Bug</b>

1. Open VSCode as normal user
2. Set "files.autoSave" as "onFocusChange"
3. Open a system file, for example `host`
4. Make some changes
5. Move focus out of editor, for example, click status bar, the notification of "Retry as admin" will popup
6. Click the document to move focus back
7. Click anywhere of the notification, a new notification will popup repeatly.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|7.83GB (2.51GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
xml|Dot|1.9.2
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
matlab|Gim|0.8.0
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
code-settings-sync|Sha|2.9.0
gitblame|wad|2.2.0
vscode-cil-complete|wk-|0.0.5

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
I can reproduce, not on macOS though. Seems like the timing on Windows is worse that you cannot click the button because it always goes away when you click.
