### ISSUE TITLE
Unable to build typescript

### ISSUE THREAD

**Issue by ankugarg** [Microsoft/vscode#45824]
### Issue Type
Bug

### Description

Terminal output:
Executing task: tsc -p "c:\users\OneDrive - ORG\vscode\mytasks\tsconfig.json" <

error TS5023: Unknown compiler option '-'.
The terminal process terminated with exit code: 1

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.90GB (2.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by ankugarg** [comment]
Works fine when hyphen is removed.

**Comment by dbaeumer** [comment]
This got fixed and improved for the next stable release.
