### ISSUE TITLE
[json] proposals include true and false for boolean type regardless of enum

### ISSUE THREAD

**Issue by castwide** [Microsoft/vscode#45821]
This issue was discovered in https://github.com/rubyide/vscode-ruby/issues/295.

Add a configuration contribution to an extension's package.json that accepts both `boolean` and `string` types, but give it an enum that doesn't include one of the boolean options:

```
"ruby.codeCompletion": {
  "type": ["boolean", "string"],
  "enum": [false, "rcodetools"],
  "default": false,
  "description": "Method to use for code completion. Use `false` if another extension provides this feature."
}
```

When editing the configuration in User Settings, the completion items include `true` despite the enum:

![image](https://user-images.githubusercontent.com/3704922/37442882-0c3899c2-27df-11e8-9ae9-e3b334c3ad0b.png)

**Comment by sandy081** [comment]
@aeschli I think it is related to JSON
