### ISSUE TITLE
[Feature Request] Any Plans for the Nodejs's upgration to 8.9.X？

### ISSUE THREAD

**Issue by MaleDong** [Microsoft/vscode#45826]
It seems that VSC is based on Nodejs, and this version is 7.9.X, which is a testable one and never maintained (for details, please see: https://github.com/nodejs/Release#release-schedule).

![45826](https://user-images.githubusercontent.com/6959154/37445297-2f88fd68-2852-11e8-941d-1e73df55a118.PNG)

Any other plans to upgrade this to 8.9.X?

**Comment by mjbvz** [comment]
Covered by #45542
