### ISSUE TITLE
Files pane remains darkened after rename, enter key

### ISSUE THREAD

**Issue by jcward** [Microsoft/vscode#4582]
- VSCode Version: 0.10.11
- OS Version: Ubuntu 14.04 x64

Steps to Reproduce:

1. Right-click a file (or folder)
2. Select rename
3. Change the name of the file (I just added a prefix)
4. Press 'Enter'

Notice that the file is renamed successfully, but the files pane remains in the darkened state:

![image](https://cloud.githubusercontent.com/assets/2192439/13966624/fe0e124e-f038-11e5-8287-d2223472838f.png)

Workaround:
- To restore the files pane colorization, repeat steps 1) and 2), but then just click out.

Notes:
- The files pane is still usable, just in the darkened display state.
- If you mouse-click-out of the rename input (as opposed to pressing Enter), the bug is avoided.
- If you don't actually change the file name, and press Enter, the bug is avoided.

**Comment by bpasero** [comment]
Fixed for March.

**Comment by bpasero** [comment]
You can try the fix in http://code.visualstudio.com/insiders
