### ISSUE TITLE
the function for format code does not work

### ISSUE THREAD

**Issue by niujingliang** [Microsoft/vscode#45835]
Issue Type: <b>Bug</b>

the function for format code does not work

VS Code version: Code - Insiders 1.22.0-insider (02def72023c9c03907884d7298a3e042c16975c7, 2018-03-15T06:10:26.102Z)
OS version: Darwin x64 17.4.0

Reproduces only with extensions

**Comment by mjbvz** [comment]
Please post steps to reproduce the problem

**Comment by niujingliang** [comment]
open a js file, and select a block of code, and ⌘ + K + F or click the ContextMenu @mjbvz

**Comment by mjbvz** [comment]
But only when extensions are enabled?

**Comment by niujingliang** [comment]
no

**Comment by mjbvz** [comment]
Please provide the information requested here: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests

**Comment by sessio** [comment]
I too have not been able to get prettier to work after insiders update today, was ok in the previous version

**Comment by nschurmann** [comment]
I have a fresh install of VS Code, still not working.
