### ISSUE TITLE
Running npm tasks locks file. Can't do git checkout

### ISSUE THREAD

**Issue by giridharangm** [Microsoft/vscode#45838]
Issue Type: <b>Bug</b>

When I run npm tasks on the background using tasks, it seems it blocks the user to do git operations like `checkout` etc. All I'm getting is a permission denied error. 

VS Code version: Code - Insiders 1.22.0-insider (02def72023c9c03907884d7298a3e042c16975c7, 2018-03-15T06:16:25.881Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|Memory (System)|7.86GB (2.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
gitlens|eam|8.1.1
prettier-vscode|esb|1.2.2
python|ms-|2018.2.1
cpptools|ms-|0.15.0
debugger-for-chrome|msj|4.2.0
vscode-icons|rob|7.21.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by dbaeumer** [comment]
I can't reproduce this. In general tasks simply spwan a shell and execute the task. What happens when you execute the same command in a terminal and then try to do the git checkout.

For which files are you gettting the permission denied error.

**Comment by giridharangm** [comment]
> What happens when you execute the same command in a terminal and then try to do the git checkout  

It worked perfectly fine.  

But it looks like this issue got fixed in the latest commit. I'll close this  one.
