### ISSUE TITLE
Can't launch debug config with runtimeExecutable that has a space in the path

### ISSUE THREAD

**Issue by KevinSnyderCodes** [Microsoft/vscode#45832]
This is a duplicate of #40301, which was locked.

- VSCode Version: 1.21.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a `launch.json` config with a `runtimeExecutable` that has spaces in the path
2. Run the configuration

Example launch config:

```json
{
    "type": "node",
    "request": "launch",
    "name": "Mocha",
    "cwd": "${workspaceFolder}",
    "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/mocha.cmd",
    "windows": {
        "runtimeExecutable": "${workspaceFolder}\\node_modules\\.bin\\mocha.cmd"
    },
    "runtimeArgs": [
        "${workspaceRoot}/test/**/*.js"
    ],
}
```

You can also write out the `windows.runtimeExecutable` path yourself:

```json
    "windows": {
        "runtimeExecutable": "C:\\Users\\Kevin Snyder\\Documents\\Projects\\Killer Queen\\kqstats\\node_modules\\.bin\\mocha.cmd"
    },
```

Debug console output:

```
C:\Users\Kevin Snyder\Documents\Projects\Killer Queen\kqstats\node_modules\.bin\mocha.cmd 'C:\Users\Kevin Snyder\Documents\Projects\Killer Queen\kqstats/test/**/*.js'
'C:\Users\Kevin' is not recognized as an internal or external command,
operable program or batch file.
```

I get the same error running the same command in PowerShell or the Command Prompt.

PowerShell:

```
PS C:\Users\Kevin Snyder\documents\projects> C:\Users\Kevin Snyder\Documents\Projects\Killer Queen\kqstats\node_modules\
.bin\mocha.cmd 'C:\Users\Kevin Snyder\Documents\Projects\Killer Q
ueen\kqstats/test/**/*.js'
C:\Users\Kevin : The term 'C:\Users\Kevin' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ C:\Users\Kevin Snyder\Documents\Projects\Killer Queen\kqstats\node_mo ...
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Kevin:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Command Prompt:

```
C:\Users\Kevin Snyder\Documents\Projects\Killer Queen\kqstats\node_modules\.bin\mocha.cmd 'C:\Users\Kevin Snyder\Documents\Projects\Killer Queen\kqstats/test/**/*.js'
'C:\Users\Kevin' is not recognized as an internal or external command,
operable program or batch file.
```

However, if I wrap the path to `mocha.cmd` in double quotes, the execution is successful:

Command Prompt:

```
"C:\Users\Kevin Snyder\Documents\Projects\Killer Queen\kqstats\node_modules\.bin\mocha.cmd" 'C:\Users\Kevin Snyder\Documents\Projects\Killer Queen\kqstats/test/**/*.ts'
Debugger listening on ws://127.0.0.1:17393/345f6b35-06f7-480c-85f2-34358dcb600a
For help see https://nodejs.org/en/docs/inspector
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
The bug is that we are quoting the executable path with a space with single quotes instead of double quotes. Windows command prompt doesn't like that.

But this should not block you because the recommended way for a mocha launch config does not have this problem.

You can easily create it by pressing the big "Add Configuration..." button in the launch.json editor:
```json
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha Tests",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": [
                "-u", "tdd",
                "--timeout", "999999",
                "--colors",
                "${workspaceFolder}/test"
            ],
            "internalConsoleOptions": "openOnSessionStart"
        }
```
Using this on a project that has a space in the path works fine for me.

Comment for your launch config:
- you don't have to use backslashes as path separators on Windows
- you don't have to introduce a Windows specific path that adds the ".CMD". We do this automatically.
- don't use glob patterns in launch configs because there is not always a shell that will expand them       (e.g. "${workspaceRoot}/test/**/*.js" is not expanded in your case)
- even if there is shell (e.g. when using `"console": "integratedTerminal"`), a "**" does not do what you expect.

**Comment by weinand** [comment]
@roblourens I've added this [workaround](https://github.com/Microsoft/vscode-node-debug/commit/eedb234b99f6f943988a84bcec44f0db533149e7) to "legacy".

**Comment by KevinSnyderCodes** [comment]
Thanks for the follow up. Yeah my configuration is an odd one without context. There were originally more options as I was trying to debug TypeScript unit tests using [ts-node](https://github.com/TypeStrong/ts-node). Recently breakpoints stopped working with the traditional configuration, so I was fiddling around trying to find a fix. I removed the additional options to provide a minimum reproducible configuration and rule out other issues.

I'll be sure to take note of your comments as I continue finding a workaround. Many thanks :)

**Comment by roblourens** [comment]
Added the same workaround

**Comment by roblourens** [comment]
I don't think we expect to be able to do anything else here, so I'll close this.
