### ISSUE TITLE
Menu keys on Windows require holding Alt whereas native apps only require a press

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45837]
This catches me out quite a lot... With native Windows apps, I can press `Alt` (then release it) then `F` to open the file menu. In VS Code, `Alt` needs to be held during the pressing of `F` for the menu to activate (eg. `Alt` doesn't "toggle" selecting the menu bar).

I know there are a lot of issues opened lately about the handling of Alt, but I think they are different (and related to keeping hold of Alt).

To reproduce:

- Open Notepad
- Press and release `Alt`
- Observe that the menu is highlighted and pressing `F` will open the `File` menu

- Open Code
- Press and release `Alt`
- Observe that the menu bar flickered with focus only for the duration of holding down the `Alt` key

**Comment by DanTup** [comment]
Actually, looks like Electron's issue:

https://github.com/electron/electron/issues/2504

**Comment by bpasero** [comment]
@DanTup there is a lot more... ([query](https://github.com/Microsoft/vscode/labels/workbench-menu)).
