### ISSUE TITLE
Terminal is blank and cannot enter commands

### ISSUE THREAD

**Issue by liushuhui** [Microsoft/vscode#45833]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.Terminal is blank and cannot enter commands
2.
![image](https://user-images.githubusercontent.com/26155477/37447977-6450d464-285f-11e8-95b6-6277c4e9b36a.png)

**Comment by keshav68** [comment]
Same issue

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169
