### ISSUE TITLE
Intellisense becomes very slow with Ionide F# extension

### ISSUE THREAD

**Issue by halcwb** [Microsoft/vscode#45836]
Issue Type: <b>Bug</b>

In any F# project of significant size the intellisense becomes unworkable slow.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.99GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|3.17.3
vscode-docker|Pet|0.0.25
language-haskell|jus|2.4.0
csharp|ms-|1.14.0

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
This is a F# specific issue.
Moved to https://github.com/ionide/ionide-vscode-fsharp/issues/741. Please continue the discussion there.
