### ISSUE TITLE
go to definition does not work anymore.

### ISSUE THREAD

**Issue by davidesantangelo** [Microsoft/vscode#45843]
I recently upgraded VScode to Version 1.21.1 on OSX High Sierra. Since then my cmd + click on functions, definitions, etc, does not work anymore. It does not do anything in fact.

Steps to Reproduce:

upgrade to Version 1.21.1
try cmd click on function

**Comment by mjbvz** [comment]
Please  provide a code example and description of your project structure

**Comment by davidesantangelo** [comment]
my project is a rails application. With previous versione i of VS code it works, with all the extensions enabled.

**Comment by mjbvz** [comment]
Please file this issue against your ruby / rails extension

**Comment by davidesantangelo** [comment]
no it doesn't work also with other projects and extensions disabled. Is not caused by rails extension.
