### ISSUE TITLE
SCM: Allow to use window.title": "${activeEditorLong}" for SCM files

### ISSUE THREAD

**Issue by benny-medflyt** [microsoft/vscode#45848]
- VSCode Version: Version 1.21.0
- OS Version: Ubuntu

I changed my settings and added:

    "window.title": "${activeEditorLong}"

It works great and window title shows the full path to a file when editing it:

    ~/cool-project/src/File.c

But if I click the "Open Changes" button, then the window title changes to just the filename, without the full path:

    File.c (Working Tree)

I expect it to show:

    ~/cool-project/src/File.c (Working Tree)

**Comment by bpasero** [comment]
@benny-medflyt yeah these variables currently only work for normal files not SCM resources.

/cc @joaomoreno it would probably be possible for you to support these settings and come up with a better name

**Comment by EdwinSaenz** [comment]
Hello, I’d like to work on this as my first issue. 

Can I get some pointers on how to go about fixing this?

Thanks

**Comment by bpasero** [comment]
@joaomoreno yes it needs a new concept. Currently editors can only provide their label for tabs but not for the title. It would not be clever to change it for the tabs imho.

**Comment by EdwinSaenz** [comment]
So, should I wait for a plan of action?

**Comment by njkevlani** [comment]
@EdwinSaenz, Have you started working on this? If not, I'm willing to take this issue and solve it.

**Comment by njkevlani** [comment]
@joaomoreno, There must be some file that handles `window.title` for regular tabs(files). For keeping code uniform, we must use that code or at least keep coding style similar. So which file contain function for returning title of regular tabs(files).
