### ISSUE TITLE
Search: placeholder color too strong in default light theme

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#45841]
Placeholder color is same as input box color which makes it hard to differentiate between the two.

**Comment by bpasero** [comment]
@isidorn @roblourens I might have fixed this with https://github.com/Microsoft/vscode/commit/1dcdaccbcce51e4dd90287c5a5a80535446136d4 already

**Comment by roblourens** [comment]
I think it looks fine now

![image](https://user-images.githubusercontent.com/323878/37880321-349b7614-303b-11e8-81a1-a1537ec093a0.png)

**Comment by isidorn** [comment]
Yeah it is good now -> verified
