### ISSUE TITLE
Unclear compilerOptions documentation

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#45840]
Looking at https://code.visualstudio.com/docs/languages/jsconfig#_using-the-include-property

The example shows:

![image](https://user-images.githubusercontent.com/1658949/37453082-e32ec936-2836-11e8-96ec-b52c04d7825d.png)

Just below that we have https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options

This does not list `ES6` as a valid value:

![image](https://user-images.githubusercontent.com/1658949/37453109-fa3af078-2836-11e8-9c27-bba00adc67eb.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-docs#1496
