### ISSUE TITLE
Visual studio code getting slow while working on large projects [tab] not work and live scss stop works also intellisense get lazy

### ISSUE THREAD

**Issue by hassanbinsafdar** [Microsoft/vscode#45847]
Its happening with me alot of time when my project getting bigger vsc code stops working tab is not working intellisense not working and live scss watcher stops working its saving files so slow i am attaching the video for better understanding.
![vsc](https://user-images.githubusercontent.com/13061479/37457188-120e3292-2863-11e8-9bde-3e26347d0e51.gif)
when i restart vsc its start working fine but when its open for sometime its doing things like this.

**Comment by aeschli** [comment]
The scss watcher is provided by an external extension. Can you find out if the slowness is caused by that extension by disabling all extensions?
