### ISSUE TITLE
Ctrl+K S opens shortcut dialog, does not "Save All"

### ISSUE THREAD

**Issue by jakrams** [Microsoft/vscode#45845]
Issue Type: <b>Bug</b>

Modify multiple documents, press Ctrl, then K, then S. It opens the shortcut window, it does not execute "Save All" as the main menu claims.

The shortcut dialog says that the shortcut for opening it is "Ctrl+K, Ctrl+S" and save all is "Ctrl+K S". I have tried various ways of pressing the keys simultaneously etc., all open the shortcut window.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 3492)|
|Memory (System)|31.89GB (21.04GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
sdhelp|Cra|0.1.1
EditorConfig|Edi|0.12.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@jakrams what is the "Shortcut Dialog"?

**Comment by jakrams** [comment]
Seriously? It's literally in the bug description how to open it.

Screenshot of the shortcut window / dialog / preference thing, with the duplicate shortcut in question:

![shortcuts](https://user-images.githubusercontent.com/36191331/37511620-cb35574a-28ff-11e8-8898-5e14cf69a487.png)

**Comment by bpasero** [comment]
@jakrams sorry, got it 👍

**Comment by bpasero** [comment]
I am closing this "as designed". You have to press `Ctrl+K` (release keys) and then `S` to save all.

**Comment by jakrams** [comment]
Fair enough. Though I have never seen this kind of key combination method in any other application before, it is very unintuitive, you may want to rethink using such combinations in the default configuration (if someone configures them for himself it's fine).
