### ISSUE TITLE
VS Code 'Reindent Lines' is not working properly

### ISSUE THREAD

**Issue by delowar64** [Microsoft/vscode#45849]
StackOverflow link: https://stackoverflow.com/questions/49296811/vs-code-reindent-lines-is-not-working-properly

- VSCode Version: 1.19.3
- OS Version: MacOS 10.13.3 

I've tried to re-indent some large HTML files using VS Code, but it cannot re-indent my files properly. But when I try to re-indent small files, it works. How can I fix this issue?

<img src="https://media.giphy.com/media/fdAbda2ZL8JlDE7d0D/giphy.gif" />

Does this issue occur when all extensions are disabled?:  Yes

**Comment by rebornix** [comment]
Reindent command is using 4 indentation rules to adjust the indentation and that's not always accurate. When reindenting a large content, we will recommend using formatters which ensure the correct output. For more details, please see https://github.com/Microsoft/vscode/issues/19140.
