### ISSUE TITLE
Show the name of the extension that triggered a window reload

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#45842]
related to #45774 

Apparently extension use the `workbench.action.reloadWindow`-command to reload the window. Since that's big hammer we should show the extension-name calling the command and ask for confirmation.

**Comment by DanTup** [comment]
@jrieken I'm already prompting the user, so this will result in two prompts:

```ts
export async function promptForReload(message: string) {
	const reloadAction = "Reload Window";
	if (await window.showInformationMessage(message, reloadAction) === reloadAction) {
		commands.executeCommand("workbench.action.reloadWindow");
	}
}
```

If I remove the prompt now, then people won't get it until you release the fix.

Is it possible you can either gives us a way to know whether a prompt will be shown (so I can conditionally show mine), or hold off while I investigate if I can eliminate all of those calls to do a silent "reload" internally?

**Comment by bpasero** [comment]
I think its fine as long as extensions are showing a notification asking the user. If we find an extension that just blindly reloads the window, we should approach that extension to show a notification instead.

**Comment by DanTup** [comment]
There were details in the other case, but it was basically a way of re-initialising everything after some changes that affected a lot of setup (for example, the user changes their SDK so we needed to reset everything). Turns out it wasn't that hard to just re-run my activate method as below (maybe there should be a built-in API for an extension to request a reload like this?).

So, as of vNext, as long as no serious bugs I found that I can't fix, I won't be reloading Window (and the user experience is so much better than the prompt and visible reload!).

```ts
	context.subscriptions.push(vs.commands.registerCommand("_dart.reloadExtension", (_) => {
		deactivate();
		for (const sub of context.subscriptions) {
			try {
				sub.dispose();
			} catch (e) {
				console.error(e);
			}
		}
		activate(context);
	}));
```

**Comment by bpasero** [comment]
@DanTup thats good, thanks for that 👍

**Comment by jrieken** [comment]
> Nevertheless: imho there should be NO reason for an extension to ever reload the window. What is the actual use case for that?

There is around 100 references to that command - just saying...

**Comment by bpasero** [comment]
@jrieken that sucks, but then again we are typically not adding any confirmation dialogs for when an extension uses our API. We had the same discussion when I added the multi-root workspace API when I remember correctly.

**Comment by DanTup** [comment]
Maybe it's worth writing to the logs, so at least if a user comes along saying "Why does my window keep reloading" they have some way of identifying the offender?

**Comment by bpasero** [comment]
I would argue we could do that for any command that gets executed. Whenever an extension runs a command programmatically we could log the extension identifier that triggered it.
