### ISSUE TITLE
Search: transition include and exclude patterns to new combined input

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#45844]

**Comment by roblourens** [comment]
@jrieken It should migrate the excludes/includes that were persisted in the input box, but not the history because I don’t know which includes/excludes go together. What exactly were you missing?

**Comment by jrieken** [comment]
It migrated but didn't negate them. Before

```
include: ''
exclude: '**/.vscode-api/**, **.d.ts'
```

and after migration it was (w/o exclamation marks)

```
include/exclude: '**/.vscode-api/**, **.d.ts'
```

**Comment by roblourens** [comment]
The negation was missing in the first build that went out but should be fixed now. I just tested migrating from stable to insiders.
