### ISSUE TITLE
Enable colorDecorators in any file

### ISSUE THREAD

**Issue by josemigallas** [Microsoft/vscode#45852]
- VSCode Version: 1.21.0 (1.21.0)
- OS Version: macOS Sierra (10.13.3)

This is a suggestion for a feature. As a React Native developer I work with HTML/CSS/JS all in .js files and I can't use VSCode's color decorator. The setting `"editor.colorDecorators"` falls under the `editor` settings but it simply does not work outside of style sheet files.

And not only JS but any other platform/language that handles colors would benefit from this.

![screen shot 2018-03-15 at 12 00 28](https://user-images.githubusercontent.com/11672286/37459485-8824c4f2-2848-11e8-809c-59aa2674b275.png)

**Comment by mjbvz** [comment]
The color decorators are contributed by extensions (the ones for css and html just are contributed by built-in html and css extensions). Try looking in the marketplace for one that may work for your use case
