### ISSUE TITLE
HTML inline comments are  automatically moved to the next line

### ISSUE THREAD

**Issue by nanaasumadu** [Microsoft/vscode#45855]
Issue Type: <b>Bug</b>

HTML inline comments against elements are automatically moved to next line.

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Document</title>
    </head>

    <body>
        <div class="test">

        </div>
         (This line was automatically moved from the div above)
    </body>

</html>

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

Extensions disabled
Reproduces without extensions

**Comment by nanaasumadu** [comment]
When I add an inline comment to any element and save, it automatically gets move to the next line.  This is not desirable.  Is there a setting to disable this??

The desired effect will be
`    <div class="test">

    </div>****`

**Comment by aeschli** [comment]
We use [jsbeautify](http://jsbeautifier.org/) as the underlying formatter. To my knowledge, there is no setting for the handling of comments.
Please file a request against https://github.com/beautify-web/js-beautify
