### ISSUE TITLE
Auto jump to next conflict

### ISSUE THREAD

**Issue by johnjacobkenny** [Microsoft/vscode#45853]
When trying to resolve multiple conflicts in a file, currently we need to manually scroll ([or use a shortcut](https://stackoverflow.com/questions/46125244/isnt-there-a-way-to-jump-between-conflicts-in-vscode)) to the next conflicted area to be able to resolve the next conflict. It would be easier if the editor could automatically jump to the next conflicted section in the same file.

- VSCode Version: 1.21.1
- OS Version: Windows 10

Steps to Reproduce:

1. Update code.
2. Open a file with multiple conflicts.
3. Click on _accept current/incoming/both_ etc.
4. Editor does not jump to next conflict.

Does this issue occur when all extensions are disabled?: Yes

**Comment by johnjacobkenny** [comment]
This is similar to [this comment](https://github.com/Microsoft/vscode/issues/38321#issuecomment-371459777)

**Comment by chrmarti** [comment]
I often find myself edit the result of the action I chose. In these cases jumping to the next conflict would get in my way.

**Comment by andrewtomai** [comment]
I've worked on this and added a pull request in the case that it is decided that this feature should be added.  I would like to note that I've set it up such that it is a modifiable user setting, so the user can easily disable this feature if they so choose.
