### ISSUE TITLE
VS Code adds single quotes to program arguments  ( *args* for *program* in launch.json )

### ISSUE THREAD

**Issue by Voliki** [Microsoft/vscode#45854]
- VSCode Version: 1.20.1

Hello, I have a problem, I can not run tests with the possibility of debugging, 
due to the fact that VS Code puts single quotes in arguments for a program
```
{
            "name": "Mocha tests",
            "type": "node",
            "request": "launch",
            "stopOnEntry": false,
            "program": "${workspaceRoot}\\node_modules\\mocha\\bin\\_mocha",
            "args": [
                "${workspaceRoot}/tools/startTest.js", 
                "--require ts-node/register",
                "--watch-extensions ts,tsx", 
                "--require babel-register",
                "--watch-extensions js",
                "tests/**/*.spec.*"
            ],
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": null,
            "protocol": "inspector",
            "env": {
                "NODE_ENV": "dev"
            },
            "port": 43587
}
```

In debug console it becomes:

`node node_modules\mocha\bin\_mocha C:\dev\Study\TestReactProjects\cra-ts-antd/tools/startTest.js '--require ts-node/register' '--watch-extensions ts,tsx' '--require babel-register' '--watch-extensions js' tests/**/*.spec.* `

Without single quotes in the command line, the tests are run and everything works fine, 
please tell me how to remove single quotes in arguments.

To get it like this: 
`node node_modules\mocha\bin\_mocha C:\dev\Study\TestReactProjects\cra-ts-antd/tools/startTest.js --require ts-node/register --watch-extensions ts,tsx --require babel-register --watch-extensions js tests/**/*.spec.*`

**Comment by DTasev** [comment]
I've a similar configuration, but mine doesn't seem to add any quotes and runs successfully. The only difference that I can see is that you are specifying multiple arguments on one line here:
```
 "--require ts-node/register",
"--watch-extensions ts,tsx", 
"--require babel-
"--watch-extensions js",
```
If you separate them like this it should work:
```
 "--require",
"ts-node/register",
"--watch-extensions",
"ts,tsx", 
"--require",
"babel-register",
"--watch-extension",
"js"
```
Just for reference my config in `launch.json` look like this:

```
{
    "type": "node",
    "request": "launch",
    "name": "Mocha Current Test",
    "env": {
        "TS_NODE_COMPILER_OPTIONS": "{\"module\": \"commonjs\"}"
    },
    "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
    "args": [
        "-u",
        "tdd",
        "--compilerOptions",
        "--require",
        "ts-node/register",
        "--require",
        "jsdom-global/register",
        "--timeout",
        "999999",
        "--colors",
        "${file}"
    ],
    "internalConsoleOptions": "openOnSessionStart",
    "protocol": "inspector"
}
```

**Comment by isidorn** [comment]
@DTasev thanks for providing a workaround.
The node debug adapter seems to be massaging the quotes, thus forwarding to @weinand and @roblourens

**Comment by weinand** [comment]
Passing multiple arguments (e.g. `--require babel-register`) as one array element is just wrong.

So instead of 
```json
           "args": [
                "${workspaceRoot}/tools/startTest.js", 
                "--require ts-node/register",
                "--watch-extensions ts,tsx", 
                "--require babel-register",
                "--watch-extensions js",
                "tests/**/*.spec.*"
            ],
```
do this:
```json
           "args": [
                "${workspaceRoot}/tools/startTest.js", 
                "--require", "ts-node/register",
                "--watch-extensions", "ts,tsx", 
                "--require", "babel-register",
                "--watch-extensions", "js",
                "tests/**/*.spec.*"
            ],
```

In addition I'm not sure that the last argument `"tests/**/*.spec.*"` will work because there is no shell that can actually expand the '*' wildcards.

And you don't have to use backslashes on Windows. 

@DTasev's launch config looks perfect.

**Comment by DTasev** [comment]
At least on Windows with Powershell I can confirm that `"${workspaceFolder}/src/test/**/*.test.ts"` in `launch.json` expands to find all test files, in every folder inside `${workspaceFolder}/src/test` directory.

**Comment by weinand** [comment]
Yes, that must be a mocha feature.
A launch configuration that doesn't use the "console" attribute uses the node.js "spawn" API without a shell.

**Comment by Voliki** [comment]
Thanks, it helped me. I also had a problem, did not work out the debugger in the tests. I decided this by removing the port.
now it looks and works fine
```
{
            "name": "Mocha tests",
            "type": "node",
            "request": "launch",
            "stopOnEntry": false,
            "program": "${workspaceRoot}\\node_modules\\mocha\\bin\\_mocha",
            "args": [
                "${workspaceRoot}/tools/startTest.js", 
                "--require", 
                "ts-node/register",
                "--watch-extensions", 
                "ts,tsx", 
                "--require", 
                "babel-register",
                "--watch-extensions", 
                "js",
                "tests/**/*.spec.*"
                
            ],
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": null,
            "protocol": "inspector",
            "env": {
                "NODE_ENV": "dev"
            }
}
```

**Comment by weinand** [comment]
And if you want to have it neat, short, simple, and cross platform:
```json
{
            "name": "Mocha tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
            "args": [
                "${workspaceRoot}/tools/startTest.js", 
                "--require", 
                "ts-node/register",
                "--watch-extensions", 
                "ts,tsx", 
                "--require", 
                "babel-register",
                "--watch-extensions", 
                "js",
                "tests/**/*.spec.*"
            ],
            "env": {
                "NODE_ENV": "dev"
            }
}
```
