### ISSUE TITLE
Renaming files that was moved by drag-and-drop makes the sidebar grey

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#4585]
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.3

Steps to Reproduce:

1. Move a file to another folder using drag and drop
2. Hit enter to rename the file that you just moved
3. Rename the file and hit enter

File names in the file browser in sidebar becomes all grey

Video: https://gfycat.com/RemorsefulMixedIchneumonfly

Edit: updated video

**Comment by bpasero** [comment]
Fixed for March. You can try the fix in http://code.visualstudio.com/insiders
