### ISSUE TITLE
Allow custom locations/anchors for showInputBox

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#45869]
Currently the only input box provided by vscode to extensions is via the `showInputBox` api (not counting the SCM input since AFAIK that isn't accessible for general use). Given some use-cases such as triggering `showInputBox` from a statusbar item, a command in a custom view, etc &mdash; having it only be able to appear top/center of the screen can feel a bit jarring and disconnected. It would be great if there were other options for how to position it.

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/29193
