### ISSUE TITLE
on terminal window, output is often truncated, like if a flush was missing

### ISSUE THREAD

**Issue by pypaolo** [Microsoft/vscode#45860]
Issue Type: <b>Bug</b>

Usually in python debugging

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|15.90GB (11.99GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.0.12
python|ms-|2018.2.1
cpptools|ms-|0.15.0
java|red|0.20.0
python|tht|0.2.3
vscode-java-debug|vsc|0.7.0

</details>
Reproduces only with extensions

**Comment by pypaolo** [comment]
Even with all Java and MagicPython extensions disabled, the issue persists... 


This is an example :
------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 1319, in _on_timer
    ret = func(*args, **kwargs)
  File "c:/PyProjects/CH/MAIN.py", line 1787, in update_figure
    self.add_X()
  File "c:/PyProjects/CH/MAIN.py", line 1043, in add_X
    self.add_x(1)
  File "c:/PyProjects/CH/MAIN.py", l
PS C:\PyProjects\CH>
------------------------------------------------------------------------------------------------------

what to do ? 
thanks

**Comment by isidorn** [comment]
Step 1 read how to file nice issues https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
