### ISSUE TITLE
Mac: Watcher fails on folders with glob characters in name

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode#4586]
- VSCode Version: 0.10.11
- OS Version: OS X 10.10.5 Yosemite

I don't know how to reproduce it, but a jsconfig.json file that was created on a plugin activation script didn't appear on VS Code, yet it did appear when I run ls on the folder.
After I went to the workspace settings in VS Code, something refreshed, and the file finally appeared.

**Comment by digeff** [comment]
I think it might be related to a folder name. Try this on a workspace on a folder:
/Users/workspaces/tests/myNewApp% $$ @! Tabs app/testsblah/ (This is a valid folder on my Mac)

**Comment by bpasero** [comment]
This is: https://github.com/paulmillr/chokidar/issues/300

**Comment by digeff** [comment]
Would it be possible to automatically escape glob characters, so this would work as expected as in, instead of asking to watch:
/Users/workspaces/tests/myNewApp% $$ @! Tabs app/testsblah/ 
ask to watch something like:
/Users/workspaces/tests/myNewApp% \$\$ @! Tabs app/testsblah/

If this is not supported, could you at least show a warning when this happens:
* Sorry, but VS Code doesn't work well with this folder because etc.... So the user will understand what's happening?

**Comment by bpasero** [comment]
+1 for a warning, the escaping needs to be supported in chokidar

**Comment by roblourens** [comment]
Still not working with these steps:

- Open a folder named `myNewApp% $$ @! Tabs app`
- Run `echo "hi" > foo.txt` in the terminal to create a file `foo.txt`
- It doesn't show up in the file explorer until I press Refresh

If I do the same steps in a folder without special characters, the file shows up in the explorer right away.

**Comment by bpasero** [comment]
![panel-red](https://cloud.githubusercontent.com/assets/900690/26751796/77921590-4842-11e7-8623-cb8b7e3e0241.gif)

Works for me, what are you doing differently?

**Comment by roblourens** [comment]
Ok, that scenario works when I open the parent folder of 'myNewApp ...'. It doesn't work when I open 'myNewApp' itself. Should it?

![jun-03-2017 14-47-26](https://cloud.githubusercontent.com/assets/323878/26757258/9b14914a-486b-11e7-83bc-546ba1072066.gif)

**Comment by chrmarti** [comment]
Confirmed, reopening.

**Comment by bpasero** [comment]
We should get rid of chokidar...

**Comment by bpasero** [comment]
...we did.
