### ISSUE TITLE
Numbers don't stop auto-completion

### ISSUE THREAD

**Issue by Sleen** [Microsoft/vscode#45861]
Issue Type: <b>Bug</b>

![completion](https://user-images.githubusercontent.com/6940265/37463949-c4678ad2-2891-11e8-9d4e-5f4af72c39e0.gif)

1. Use `^+space` to trigger suggestions manually.
2. Enter some numbers. The suggestion window does not disappear.
3. Press `Enter`

Expected: Wrap line instead of auto-completion

---

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Users/Sleen/Downloads/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_6292992|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.10.0
output-colorizer|IBM|0.1.2
solidity|Jua|0.0.31
mist|Sle|0.2.19
language-pde|Tob|0.1.21
tmlanguage|Tog|0.8.5
html-css-class-completion|Zig|1.17.1
jshint|dba|0.10.17
vscode-eslint|dba|1.4.7
vscode-dash|dee|1.8.0
githistory|don|0.4.0
jquerysnippets|don|0.0.1
gitlens|eam|8.1.1
tslint|eg2|1.0.28
LogFileHighlighter|emi|2.1.1
code-runner|for|0.9.2
json-escaper|jos|1.0.1
TypeScriptImport|kev|1.17.0
svgpreview|kis|0.2.0
vscode-gutter-preview|kis|0.12.2
vscode-antlr4|mik|1.3.0
prettify-json|moh|0.0.3
python|ms-|2018.2.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.2.0
polacode|pnp|0.2.2
java|red|0.20.0
merge|ron|0.0.3
RustyCode|sav|0.19.1
preview-vscode|sea|1.4.2
shader-toy|ste|0.4.1
json-schema-validator|tbe|0.1.0
cmake|twx|0.0.17
cmake-tools|vec|0.10.4
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by jrieken** [comment]
What language is this?

**Comment by Sleen** [comment]
I'm writing an extension for a json-like template language and supporting suggestion for it.

This issue can be reproduced in json files with json schema, like `package.json`. An example is as follow:
 
![](https://user-images.githubusercontent.com/6940265/37507292-b6720c76-2928-11e8-82cf-e77257484113.gif)

**Comment by jrieken** [comment]
Nice find, the problem is that we don't cancel intellisense when we 'think' that it was explicitly triggered by the user. I have now changed the logic to treat sessions triggered by a previous suggestion as 'automatic'.
