### ISSUE TITLE
"Go to definition" opens the same file twice

### ISSUE THREAD

**Issue by tafelito** [Microsoft/vscode#45879]
Hi, as I just pointed out in issue #17068, I just installed the new vscode version 1.21.0 that allows you to disable builtin extensions. I disabled the TypeScript extension but I'm still having issues with the intellisense when using flow.

If I open a file from the explorer, and then from a different file I do "Go to definition" to the same file, that files opens twice.

![image](https://user-images.githubusercontent.com/5973652/37474864-be07d7d6-2847-11e8-8264-7762f116ef9e.png)

![image](https://user-images.githubusercontent.com/5973652/37474843-b7384080-2847-11e8-8886-d11c356041cb.png)

![image](https://user-images.githubusercontent.com/5973652/37474829-b132f748-2847-11e8-9b0a-72a5be9cfb1a.png)

If I remove // @flow then it doesn't do anything when trying to go to definition

Do I have to add any extra config?

Thanks

**Comment by jrieken** [comment]
This is likely the workbench not knowing when paths are equal

**Comment by bpasero** [comment]
@tafelito can you copy the path of both files and see if there is any casing difference?

**Comment by tafelito** [comment]
@bpasero @jrieken I updated vscode to 1.21.1  and this seems to be working fine now If the ts built-in extensions are disabled and // @flow is present or @flow is not used and ts extensions are enabled. 
If ts extensions are enabled and also //@flow, it shows 2 definitions for the same file

**Comment by tafelito** [comment]
@bpasero Is there anyway to prevent that when having both TS and Flow extensions to don't duplicate the definitions? The problem is that if I disabled TS and use Flow everything is fine, but if I have a file that doesn't use flow, then I can't navigate to the definition and the editor keeps trying to find it  showing the progress bar indeterminate

![image](https://user-images.githubusercontent.com/5973652/37718933-3ae9fd54-2cfa-11e8-8217-54c928ae21ef.png)

**Comment by tafelito** [comment]
@bpasero There is also another issue related to this. If TS is disabled, the RN intellisense stops working too. I tried to setup it up to work with flow as it says [here](https://github.com/Microsoft/vscode-react-native/blob/master/doc/intellisense.md) but still not working.
