### ISSUE TITLE
New terminal resize keyboard shortcuts override default behavior

### ISSUE THREAD

**Issue by mlucic** [Microsoft/vscode#45876]
Issue Type: <b>Bug</b>

The new terminal shortcuts for resizing the split panes are ctrl+shift+arrow, which previously were used for full token selection. In order to restore the terminals original behavior I had to replace the new resize terminal shortcuts.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|Memory (System)|15.88GB (9.17GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by Tyriar** [comment]
@mlucic what do you mean by full token selection?

**Comment by mlucic** [comment]
@Tyriar In a powershell/cmd terminal, ctrl+shift+right/left arrow will result in selection of the full token/word next to the cursor in the direction of the arrow. The new keyboard shortcuts override the intended terminal behavior for that keyboard combination.

**Comment by Tyriar** [comment]
@mlucic I didn't think this ever worked within the VS Code terminal... Did it work before? :confused:

**Comment by mlucic** [comment]
@Tyriar Yes, these are shortcuts I use heavily. Removing the new mappings (resize terminal) recovers the original intended behavior.

**Comment by Tyriar** [comment]
@mlucic can you show me a screenshot of the selection? I can't get it to work using Windows 10 FCU with powershell.exe or the powershell extension set.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/45940
