### ISSUE TITLE
ESLint server will not be restarted.

### ISSUE THREAD

**Issue by bluezeze** [Microsoft/vscode#45875]
Issue Type: <b>Bug</b>

The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted.

VS Code version: Code - Insiders 1.22.0-insider (a716373aaaf50cbce3618688a645b324721b35dd, 2018-03-14T05:15:41.910Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|7.88GB (3.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.7
vscode-html-css|ecm|0.2.0
vetur|oct|0.11.7
vuehelper|oys|0.1.0
vscode-icons|rob|7.21.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by dbaeumer** [comment]
Any additional information in the ESLint output channel. Usually there would be some tracing information.

**Comment by bluezeze** [comment]
@dbaeumer I don't know why the request failed.GIFIframe by IllusionWing.

[Trace - 17:46:47] Sending notification 'textDocument/didOpen'.
[Trace - 17:46:47] Received request 'workspace/configuration - (0)'.
[Trace - 17:46:47] Sending response 'workspace/configuration - (0)'. Processing request took 2ms
[Info  - 17:46:48] Connection to server got closed. Server will restart.

**Comment by dbaeumer** [comment]
Can you share the project on which this happens. Best as a clonable GitHub repository. I guess something goes wrong with the configuration that is read from VS Code. That is the last request that succeeds. Is there anything special with our workspace / user settings for this project.

**Comment by dbaeumer** [comment]
@silencyXiao dups https://github.com/Microsoft/vscode-eslint/issues/437

**Comment by silencyXiao** [comment]
Thanks so much， I reinstalled nodejs，now It's ok，but I don't know why，Maybe It is affected by some of the configuration of the nodejs. I'm not sure.
