### ISSUE TITLE
Add to Watch allows the same variable more than once

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4587]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows

Steps to Reproduce:

1. Start debugging a Node.js project
2. Right click on any variable -> Add to Watch
3. Repeat step 2 on the same variable

Actual:
The same variable is added to the watch list as many times as you want

Expected:
It is only added to watch once

**Comment by isidorn** [comment]
Adding the same variable multiple times makes sense, if it is a complex variable and you want to have different expension setup at the same time.
Other debuggers also allow this (e.g chrome tools)

Closing as degined
