### ISSUE TITLE
Breakpoints are not hit

### ISSUE THREAD

**Issue by CraigHead** [Microsoft/vscode#45878]
Issue Type: <b>Bug</b>

Open any typescript file. (In our case we are using electron + angular4). 
Set a breakpoint. 
Run. 

Expected: Break point is hit. 
Actual: No break point is hit. Logging statements near the break point shows break point line was executed. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.83GB (8.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.28
docthis|joe|0.6.0
csharp|ms-|1.14.0
vsliveshare|ms-|0.2.206
debugger-for-chrome|msj|4.2.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
This is probably https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464, please see the comment there and try in the next Insiders build.
