### ISSUE TITLE
Prompt user to change the language of the UI after the installation of a localization pack

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode#45872]
If a beginner user installs a localization pack from the extension manager viewlet, they must read the description of the extension to find out how they can activate it. It would be great if there would be an easy mechanism to activate the extension (change the required value in `locale.json`).

**Comment by dbaeumer** [comment]
@sandy081 this makes sense to me. Is this something you can do on installing a language pack. We could ask the user to make it the default UI language and the simply update the locale.json file in the user settings directory.

**Comment by dbaeumer** [comment]
I set this to March since it would be something we should do to round the LP story.

**Comment by sandy081** [comment]
@dbaeumer Yes, can be done. What if an extension has multiple languages? If not urgent, I would postpone it to April?

**Comment by qcz** [comment]
@sandy081: Why not handle the case where the package contains only one language for starters? Language packs generated from the community provided translations on Transifex are all single language packages. The user experience for activating them is currently not beginner friendly.

**Comment by sandy081** [comment]
Makes sense. I can add this support as a stretch 💪

**Comment by sandy081** [comment]
@dbaeumer Does the following prompt makes sense?

![image](https://user-images.githubusercontent.com/10746682/37697055-9a8c13b8-2d00-11e8-8e97-983451af6a60.png)

May I know if I can test this while running out of the dev? Updating the language in the `locale.json` file and restarting is not running the dev build with update locale.

**Comment by sandy081** [comment]
Tested this in the generated build
