### ISSUE TITLE
Key Binding not honored when cursor in search or replace box

### ISSUE THREAD

**Issue by DanAtShenTech** [Microsoft/vscode#45883]
Issue Type: <b>Bug</b>

Set up user keybindings with Ctrl+shift+S to execute the Save All command in place of the default keybinding.  Do a Find in Files and, with the cursor in the search field, press Ctrl+shift+S.  The Save As dialog appears rather than saving all open files.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz (8 x 2195)|
|Memory (System)|7.90GB (1.22GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.1
html-class-suggestions|And|1.0.7
django-html|bib|1.2.0
vscode-eslint|dba|1.4.7
python|ms-|2018.2.1
code-settings-sync|Sha|2.9.0

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
Does your keybinding have a `when` clause? Can you post the keybinding here?

**Comment by DanAtShenTech** [comment]
```
// Place your key bindings in this file to overwrite the defaults
[
    { "key": "ctrl+shift+d",            "command": "editor.action.deleteLines",
                                            "when": "editorTextFocus" },
    { "key": "ctrl+alt+shift+d",        "command": "workbench.view.debug" },
    { "key": "ctrl+shift+up",           "command": "editor.action.moveLinesUpAction",
                                            "when": "editorTextFocus" },
    { "key": "ctrl+shift+down",         "command": "editor.action.moveLinesDownAction",
                                            "when": "editorTextFocus" },
    { "key": "ctrl+d",                  "command": "editor.action.copyLinesDownAction",
                                            "when": "editorTextFocus" },
    { "key": "ctrl+alt+shift+b",        "command": "workbench.action.toggleSidebarVisibility" },
    { "key": "ctrl+b",                  "command": "editor.action.addSelectionToNextFindMatch",
                                            "when": "editorFocus" },
    {"key": "ctrl+shift+s",             "command":
    "workbench.action.files.saveAll",
                                            "when":
                                            "editorFocus" },
    {"key": "ctrl+k",                   "command":
    "workbench.action.files.saveAs",
                                            "when":
                                            "editorFocus" },
]
```
Ah, I see.
