### ISSUE TITLE
Debugging mocha tests with ts-node no longer working

### ISSUE THREAD

**Issue by k2snowman69** [Microsoft/vscode#45885]
- VSCode Version:
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.886Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows 10

Steps to Reproduce:
1. git clone https://github.com/EnterpriseJSTutorial/vscode-ts-node-debugging
2. Open repo in VS Code
3. Open `src/__tests__/person.tests.ts `
4. Set a breakpoint within the file
5. Launch the task "Current TS Tests File"

Expected:
The break point to be hit

Actual:
You get a message "Unverified breakpoint" when hovering over the breakpoint and the breakpoint is not hit.

Other background:
There is an issue in the vscode-ts-node-debugging that suggests something has changed in vs-code which likely made this break.
https://github.com/EnterpriseJSTutorial/vscode-ts-node-debugging/issues/9

I have also tried this with my own personal repo and upgraded all dependencies and it still occurs. This does seem to be something regarding vscode and something that has changed in the last 2-3 versions.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Assigning to @roblourens and @weinand though sounds like a duplicate to me

**Comment by k2snowman69** [comment]
Possibly a duplicate but considering some of the issues you linked to do not have easy repro environments nor dedicated to debugging this exact scenario (which the repo I linked to is only for just getting this scenario to work) hopefully it will help speed up the resolution process.

On Mar 15, 2018 10:32 AM, Isidor Nikolic <notifications@github.com> wrote:

Assigning to @roblourens<https://github.com/roblourens> and @weinand<https://github.com/weinand> though sounds like a duplicate to me

**Comment by weinand** [comment]
Most likely this is a drive letter case mismatch.
(I just saw "ts-node" mentioned in #9448).

**Comment by leodinas-hao** [comment]
I had the same issue by using ts-node debugging mocha tests. VSCode (v1.21.1) gave me message "Unverified breakpoint" and wouldn't stop at any breakpoints. However, by downgrading VSCode to v1.20.1, the issue is gone and debugging became normal again.

I'm more than happy to share more details if required. Thanks.

**Comment by roblourens** [comment]
This is probably https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464, please see the comment there and try in the next Insiders build.

**Comment by Neutrino-Sunset** [comment]
I'm don't see what makes people think this is that same issue as #45657. In the repo linked in the OP the lanuch configuration 'Current TS File' works. If you place a breakpoint in a TS file and run, the breakpoint is hit. Placing a breakpoint in unit test file instead and using the launch configuration 'Current TS Tests File' doesn't work.

Doesn't that suggest this is a Mocha specific issue?

**Comment by roblourens** [comment]
ts-node (where `outFiles` can't be used) is the common thread in many of these issues. Can you try Insiders to see whether it's any better?
