### ISSUE TITLE
Tabbing after a PHP variable turns the var into <1var></var>

### ISSUE THREAD

**Issue by paperworknz** [Microsoft/vscode#4588]
- VSCode Version: 0.10.11
- OS Version: Windows 8.1 Pro x64

Steps to Reproduce:

1. Write $variable_name
2. Press the TAB key
3. Instead of tabbing, it turns the variable into <1variable_name></variable_name>

Super frustrating as I often tab after variable names for ease of reading (when there are a list of variables)

**Comment by aeschli** [comment]
It's the emmet completion

**Comment by felixfbecker** [comment]
But emmet should not trigger inside `<?php ?>` blocks, only in the HTML sections

**Comment by egamma** [comment]
This appears to be standard emmet expansion behaviour, reproduced in other emmet integrations like sublime.

It would help to give users control to not bind emmet to the TAB key.

**Comment by egamma** [comment]
Added a setting to disable emmet triggering on Tab `"emmet.triggerExpansionOnTab": false`.

**Comment by ramya-rao-a** [comment]
@paperworknz @felixfbecker 


With the new Emmet improvements in VS Code 1.15, this is no longer a problem

Tab will no longer trigger Emmet, instead Emmet abbreviations will show up in suggestion/auto-completion list.

Please read more on what else is new at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

@felixfbecker About triggering emmet only outside `<?php >`, please see https://github.com/Microsoft/vscode/issues/29354
