### ISSUE TITLE
vc can't regonize includePath ?

### ISSUE THREAD

**Issue by GMA-216** [Microsoft/vscode#45880]
- VSCode Version: Version 1.21.0
- OS Version:16.04.1-Ubuntu

Hi

I updated  the includePath in " c_cpp_properties.json ", but header file still not recognized by "C/C++ for Visual Studio Code" extension. 

any idea?

Thank you 

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Please try asking on stackoverflow or filing the issue against the c++ extension

**Comment by GMA-216** [comment]
Ok, thank you
