### ISSUE TITLE
"Find" text highlighting is shown even when UI is dismissed

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#45884]
Version 1.22.0-insider
Commit a716373aaaf50cbce3618688a645b324721b35dd
Date 2018-03-14T05:15:41.910Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Write a file with content "foo bar baz".
2. CTRL + F for "foo".
3. Dismiss "Find" UI (Escape).

Expected result: "foo" is no longer highlighted in the file.
Actual result: "foo" is still highlighted in the file, and I have to open "Find" UI and clear input to make it go away.

**Comment by rebornix** [comment]
![find-dismiss](https://user-images.githubusercontent.com/876920/37504546-41ad2dee-289c-11e8-9a5c-e52529adae76.gif)

@martellaj are you still seeing this issue, based on the

**Comment by martellaj** [comment]
For sure. I'll make my own GIFs when I get into the office! 👍

**Comment by martellaj** [comment]
Hm. I swear it was staying highlighted even after clicking away and I had to clear the text in the "find" UI for it to go away, but I can't repro. I've updated since creating the issue, so maybe it was specific to that version (or maybe I was just mistaken). Closing.

**Comment by rebornix** [comment]
@martellaj I fixed a severe find highlighting related issue yesterday so that might be why (see #45770). Now it's already fixed but still thank you for your help.
