### ISSUE TITLE
VScode refresh/flicker after typing

### ISSUE THREAD

**Issue by wiltwitt** [Microsoft/vscode#45882]
Issue Type: <b>Bug</b>

I have the latest version 1.21.1

A page on VScode will refresh/flicker as soon as I am done typing a word or even putting '.' after an object.   Cursor will move all the way down to the bottom of the page.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|31.94GB (16.79GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
dart-code|Dar|2.10.0
vscode-markdownlint|Dav|0.14.0
jshint|dba|0.10.17
githistory|don|0.4.0
gitlens|eam|8.1.1
EditorConfig|Edi|0.12.1
git-project-manager|fel|1.4.0
code-runner|for|0.9.2
fs-flutter-snippets|fra|0.1.3
beautify|Hoo|1.3.0
vstsbuildstatus|jep|0.7.1
vstsservicestatus|jep|1.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.14.0
notepadplusplus-keybindings|ms-|1.0.2
team|ms-|1.122.0
java|red|0.20.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0

</details>
Reproduces without extensions

**Comment by tsalinger** [comment]
Please disable all extensions and attach a [screen recording](https://www.cockos.com/licecap/) of your issue.

**Comment by wiltwitt** [comment]
sure here you go.  I am not sure about the java error when I disable the plugins but don't think that's the issue.
[Recording #1.zip](https://github.com/Microsoft/vscode/files/1819319/Recording.1.zip)

**Comment by jrieken** [comment]
> A page on VScode will refresh/flicker as soon as I am done typing a word or even putting '.' after an object.

What is your definition of flicker? See squiggles come and go, is that your flicker?

**Comment by wiltwitt** [comment]
it's more like refresh.  you can see with that screen recording.  It seems to refresh the page when it tries to format the page.  Cursor will move down to end of the page while I am trying to type.

**Comment by jrieken** [comment]
> you can see with that screen recording

Sorry, I actually do not see that.

**Comment by wiltwitt** [comment]
you don't see it?  this happens, in the video, while I was typing "var test = " and it will move my cursor down to the "});" which is the last line of the code.  You can see that it tries to format while I am trying to type.

**Comment by jrieken** [comment]
> You can see that it tries to format while I am

Ok, please don't call it flicker. And yes it took me 5 times watching the video to figure. Please use words, attach sources and btw you need to press those 'Reload' buttons to actually run without extensions.

**Comment by wiltwitt** [comment]
Oh, I see.  So I tried that and found the problem extension, "code Runner".

Yes, I guess I never really ran it without the extensions then.  Sorry about that.  IDE is fine, it was "code runner"

Thanks for your help

**Comment by jrieken** [comment]
Ok, thanks
