### ISSUE TITLE
Visual Studio Code will not install

### ISSUE THREAD

**Issue by bwhite71** [Microsoft/vscode#45889]
Was attempting to re-install VSCode.  During installation I receive errors stating "the following applications are using files that need to be updated by Setup".  The only applications is lists are all Visual Studio Code and it is listed6 times.  If I choose the option to "Automatically close the application", I get an Error that "Setup was unable to automatically close all application".  Attempt Retry does not work.  If I instead choose "Ignore", I get a different error referencing "DeleteFile failed; code 5.  Access is denied.

I have since moved to VSCode [Insiders.[](url)](url
![error3](https://user-images.githubusercontent.com/25447868/37477165-5620e620-284d-11e8-8cc6-1c5a052beb66.PNG)
![error2](https://user-images.githubusercontent.com/25447868/37477166-5634fd9a-284d-11e8-9165-2c53bf717424.PNG)
![error1](https://user-images.githubusercontent.com/25447868/37477167-5659254e-284d-11e8-97e3-f5f923f0c5c1.PNG)

)

**Comment by Carlosps** [comment]
It also did happen to me when I was trying to update my VS Code. The solution that worked to me was delete the Microsoft VS Code folder under Program Files and download a new VS Code installer.

**Comment by joaomoreno** [comment]
Restart the machine to make sure those processes are dead and retry installing.
