### ISSUE TITLE
invalid RegEx search crashes the whole Application

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#45894]
1.21.1, Win10x64
![](https://drive.google.com/uc?id=1g10I3hHpQ-yJcDI2_YDMg-dBEjEInX_-)
I was in the process of making this query a valid regex, hit ")" at the cursor location and the whole window just froze to death. I.e. I got "The window is no longer responding, You can reopen or close the window or keep waiting." after some time. Keeping to wait doesn't help, only restart. Can stably repro. 

Steps:

1. Have a file with content
```
t({phrase: 'mail_text_q', locale: 'ru-RU'}, mailCtx)+'\n'+
t({phrase: 'mail_text_m', locale: 'ru-RU'}, mailCtx)+'\n'+
```
2. call search widget
3. set to RegEx
4. input ``(.*+'\n'+``
5. try to add ``)`` after the third character
```
(.*
   ^
```

**Comment by rebornix** [comment]
Let's track it in https://github.com/Microsoft/vscode/issues/30874
