### ISSUE TITLE
Find fails with "cannot read property 'node' of undefined"

### ISSUE THREAD

**Issue by serprex** [Microsoft/vscode#45892]
Issue Type: <b>Bug</b>

Cannot get any search results, error appears regardless of input value

VS Code version: Code - Insiders 1.22.0-insider (509b8084d46b82ec5851447903cebd914e4535a5, 2018-03-15T09:31:27.063Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|Memory (System)|15.84GB (6.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
flow-for-vscode|flo|0.7.3
graphql-for-vscode|kum|1.9.0
vim|vsc|0.11.2

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
Do you see more details in the `Log (Window)` output pane?

Can you describe more what you are trying, are you using search (ctrl+shift+f) or the editor find widget (ctrl+f)

**Comment by serprex** [comment]
ctrl+f

Unfortunately I'ven't the logs. The issue seems to've resolved itself. Will remember to include log output in the future

**Comment by roblourens** [comment]
No worries, I was able to repro. The problem seems to happen when an empty file is open.
