### ISSUE TITLE
--locale switch incorrect for Simplified Chinese, should be zh-cn not zh-ch

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#4589]
- VSCode Version:0.10.12 alpha
- OS Version:Windows 10

Steps to Reproduce:

1. Try code-alpha --locale zh-cn
2. VS Code will not launch.  Doesn't not even fallback to English.

Looks like due to commit https://github.com/Microsoft/vscode/commit/42d87350424917e56b62af0a2b0ddea8fba3944a

**Comment by dbaeumer** [comment]
Need to check if this is covered by the fixing we did today.

**Comment by dbaeumer** [comment]
There seems to be a typo when converted from upper case to lower case with commit https://github.com/Microsoft/vscode/commit/42d87350424917e56b62af0a2b0ddea8fba3944a

**Comment by gregvanl** [comment]
Also affects `locale` attribute in locale.json.  If you set it to 'zh-cn', VS Code will not start.

**Comment by dbaeumer** [comment]
OK. I found the problem which is two folded:

- the typo I made. I fixed it and it works now
- and update installation doesn't clean any files. So you still have an old zh-CN file there which makes it fail when that locale is used. 

Need to talk to Joao what we need to do to clean up an installation.

**Comment by dbaeumer** [comment]
Merged.
