### ISSUE TITLE
Can't double click to edit variable on windows

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#45897]
- On Windows, debug node, hit breakpoint
- Double click variable

It should turn into an input box to edit, but nothing happens. The context menu option works. This is weird, thought it might be a VM issue, but it works on 1.20 in the VM.

Related to https://github.com/Microsoft/vscode/issues/45896?

**Comment by isidorn** [comment]
Works with latest insiders on windows. Duplicate of https://github.com/Microsoft/vscode/issues/45577
