### ISSUE TITLE
Wrong counter in ctrlf find occurence of text

### ISSUE THREAD

**Issue by fniquet** [Microsoft/vscode#45891]
Issue Type: <b>Bug</b>

When searching for text in a file, counter 1 of x is wrong.
It says 1 of x occurances while there are y occurences of text, with y < x  (exemple 1 of 67 with 4 real occurances)
Iterating among occurances works and counter says 1 of x then 14 of x etc ... 

Seems it's not exactly the same than #43186, though it could be the same root cause

VS Code version: Code - Insiders 1.22.0-insider (509b8084d46b82ec5851447903cebd914e4535a5, 2018-03-15T09:31:27.063Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|11.70GB (7.53GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.1.1
vscode-npm-script|eg2|0.3.3
backspace-plusplus|jri|0.0.17
vscode-mlfi|Nev|0.0.1
join-lines|wma|0.2.2

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by rebornix** [comment]
Dup of #45770. Already fixed in latest insider.
