### ISSUE TITLE
Auto import partially broken

### ISSUE THREAD

**Issue by roelkok** [Microsoft/vscode#45902]
- VSCode Version: 1.20 & 1.21
- OS Version: Windows 10

Steps to Reproduce:

In my javascript project, auto importing classes from [THREE.js](https://www.npmjs.com/package/three) stopped working. Prior to VS Code 1.20 I could type `const cam = new Persp` and the intellisense would suggest to auto import the `PerspectiveCamera` class from THREE.

I guess the way the typings for THREE are defined breaks the auto import in 1.20. Auto import does work for my own classes in the project. It also does work with other packages like [core-decorators](https://www.npmjs.com/package/core-decorators).
Although it seems to be a problem specific with THREE, it appears to be a bug with VS Code as it used to work prior to 1.20.

[Typings definition for THREE](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bd5a9a9abe00923b889b0a99c047051c39d8c6b5/types/three/index.d.ts)

My jsconfig:
```
{
    "compilerOptions": {
        "baseUrl": "./src",
        "target": "es2015",
        "experimentalDecorators": true,
        "module": "commonjs"
    },
    "include": [
        "src"
    ]
}
```

**Comment by mjbvz** [comment]
How are you including the three.js typings in your project?

**Comment by roelkok** [comment]
I don't add the typing explicitly. VS Code pulled them in itself. If I hover the import it shows the following:

`module "C:/Users/Roel/AppData/Local/Microsoft/TypeScript/2.6/node_modules/@types/three"`

Note that I downgraded to 1.19 to keep my work flow going, but if my memory serves me correctly, it shows the same in the latest version.

**Comment by mjbvz** [comment]
Can you try explicitly adding the typings in your `jsconfig`:

```
{
    "compilerOptions": {
        "baseUrl": "./src",
        "target": "es2015",
        "experimentalDecorators": true,
        "module": "commonjs"
    },
    "include": [
        "src"
    ],
    "typeAcquisition": {
        "include": [
            "three"
        ]
    }
}
```

Also, if do you see a quick fix lightbulb a file with the contents:

```js
// @ts-check

var a = new THREE.PerspectiveCamera()

var b = new PerspectiveCamera()
```

**Comment by roelkok** [comment]
Adding "typeAcquisition" doesn't seem to make much of a difference. Also I've added the above contents to a file, but I don't see a quick fix light bulb. Just a red squiggly line under `PerspectiveCamera()` in the second statement.

This is tested on VS Code 1.21

**Comment by mjbvz** [comment]
In the example, if you run `go to definition` on `THREE` or `PerspectiveCamera` in `THREE.PerspectiveCamera` , does it open the `three.d.ts` file?

**Comment by mjbvz** [comment]
Do you still see this problem in the latest vscode insiders builds?
