### ISSUE TITLE
runtimeExecutable passing wrong argument in different version of node.js (nvm)

### ISSUE THREAD

**Issue by Josema** [Microsoft/vscode#45901]
Issue Type: <b>Bug</b>

This is my configuration to run a different version of node.js:
```
        {
            "name": "node v4",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "/Users/enzo/.nvm/versions/node/v4.8.3/bin/node",
            "program": "${workspaceRoot}/${relativeFile}",
            "cwd": "${workspaceRoot}"
        }
```
And this is the output for it:
```
/Users/enzo/.nvm/versions/node/v4.8.3/bin/node --inspect=3574 --debug-brk test/computeds.js 
/Users/enzo/.nvm/versions/node/v4.8.3/bin/node: bad option: --inspect=3574
```

This is the output when running the default version without problems:
```
node --inspect-brk=48115 test/computeds.js 
Debugger listening on port 48115.
Warning: This is an experimental feature and could change at any time.
...
```

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_5178608|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
solidity|Jua|0.0.31
vscode-simple-icons|Lau|1.8.2
code-settings-sync|Sha|2.9.0
project-manager|ale|0.24.1
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
prettier-vscode|esb|1.2.2
file-icons|fil|1.0.12
vscode-styled-components|jpo|0.0.16
debugger-for-chrome|msj|4.2.0
vscode-icons|rob|7.21.0
vscode-import-cost|wix|2.6.2

(9 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by weinand** [comment]
@Josema node v4.8.3 does not support the inspector protocol (but VS Code does not know this).
To help VS Code please add `"protocol": "legacy"` to your launch config.

BTW, instead of specifying the full path to a node version, you can just set the "runtimeVersion" attribute to a version number. This should work for you:
```json
        {
            "name": "node v4",
            "type": "node",
            "request": "launch",
            "runtimeVersion": "4.8.3",
            "protocol": "legacy",
            "program": "${workspaceRoot}/${relativeFile}",
            "cwd": "${workspaceRoot}"
        }
```
