### ISSUE TITLE
Quality-Of-Life Feature: When pressing < in XML, make it only print < and not <>

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#45905]
Essentially, when in XML mode, the main annoying difference is the fact that printing out <> creates an annoying bug with one of my extensions: Auto Rename Tag. When creating a nested the element, typing the exact same name (and casing) of the parent element, then adding/removing characters also edits the closing tag of the parent element, since the <> seems to make the extension think that the newly created opening tag is the parent's opening tag.

I have disabled that specific extension, and all extensions, and it doesn't seem to happen, howeverI lose the ability to be able to rename opening and closing tags for languages.

I am using VSCode Insiders , Windows 10 1709 - 16299.309

**Comment by aeschli** [comment]
Please file this against the [auto close extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag). Maybe they can improve that experience.

The request to make autoclosing pairs user configurable is https://github.com/Microsoft/vscode/issues/38352
