### ISSUE TITLE
Split html, css and json to basic and language feature extensions

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45900]
- [x] html
- [x] json
- [x] css

**Comment by aeschli** [comment]
The new extensions are named `html-language-features` and `json-language-features`, matching 'markdown-language-features' and 'typescript-language-features'.
I also named the folders in the repo the same way (`extensions/html-language-features`). That's not consistent with markdown and typescript but I prefer keeping extension name and folder the same. @mjbvz What do you think, can we do the same for markdown and typescript?

**Comment by mjbvz** [comment]
I'll rename them too. I was originally concerned that it would mess up localization
