### ISSUE TITLE
JSDocs @template does not work as expected if all param types do not match

### ISSUE THREAD

**Issue by yo1dog** [Microsoft/vscode#45913]
- VSCode Version: 1.21.1
- OS Version: 10.10.5

When using JSDocs to describe a function using `@template`, Intellisence does not correctly infer the template type if one or more of the given parameter values do not match the function's signature.

## Case 1
All given parameter values have types that match `doSomething`'s signature.

```javascript
/**
 * @template T
 * @param {T} item
 * @param {string} str
 * @return {T}
 */
function doSomething(item, str) {
  return item;
}

doSomething(Buffer.alloc(1), 'hello');
```

Intellisence output when hovering over `doSomething(...)`:
```
function doSomething<Buffer>(item: Buffer, str: string): Buffer
```

Works as expected. Intellisence knows the template type is `Buffer`.

## Case 2
A `number` is given for the `str` parameter instead of a `string`.

```javascript
/**
 * @template T
 * @param {T} item
 * @param {string} str
 * @return {T}
 */
function doSomething(item, str) {
  return item;
}

doSomething(Buffer.alloc(1), 123);
```

Intellisence output when hovering over `doSomething(...)`:
```
function doSomething<T>(item: T, str: string): T
```

Does not work as expected. Expected same result as Case 1.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22699
