### ISSUE TITLE
Undoing completions affects search

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#45914]
Issue Type: <b>Bug</b>

* Open an empty TypeScript file.
* Ctrl-shift-f to open search window.
* Type `abc` and hit enter.
* This will automatically use the completion for `AbortController`. Ctrl-Z to undo.
* Repeat this a few times.
* The search window will get out of sync with the document.

In attached image there are more search results than the document has:

![shot](https://user-images.githubusercontent.com/19274678/37489446-e370ddd0-2854-11e8-80ee-0d75b95cdf14.jpg)

You can even delete everything in the document and the search results will remain.

VS Code version: Code - Insiders 1.22.0-insider (ec3c083444c084394ee0cd936074019c1bc0b321, 2018-03-14T06:14:24.748Z)
OS version: Linux x64 4.4.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (1.03GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders src|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by andy-ms** [comment]
Is the duplicate detection just noticing that my system info is identical in both scenarios? Otherwise these are separate issues, but the issue text will be mostly identical as a percentage due to the boilerplate.

**Comment by rebornix** [comment]
I tried multiple times but can't reproduce, @andy-ms any idea how to do a stable reproduce? BTW can you reproduce if you have auto save turned on?

**Comment by andy-ms** [comment]
Can't reproduce any more.
