### ISSUE TITLE
Ruby Go To Definition is not working

### ISSUE THREAD

**Issue by jxdx** [Microsoft/vscode#45915]
Issue Type: <b>Bug</b>

I have the latest version of VS Code and the Cmd + Click Go to definition is not working. It is not working for my co-worker as well.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.89GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by jxdx** [comment]
This is working with the insiders build.

**Comment by jxdx** [comment]
Changing the following setting fixes the issue:
`"ruby.intellisense": "rubyLocate",`

**Comment by mltsy** [comment]
Thank you! 🏆  (although Ctrl+Click still isn't working for me, but at least right-click shows the option)
