### ISSUE TITLE
Stylelint is flagging css errors in html files

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#45918]
Issue Type: <b>Settings Search Issue</b>

In the past week, Stylelint has been flagging "errors" in my HTML files.  Of course, it should not be checking HTML at all (there is no CSS in these files, they are simple Angular templates).

Things like  "string-no-newline" and "max-empty-lines".  I _do_ want these rules enabled for CSS/SCSS, but not in HTML.

I updated the local copy of stylelint in my project to 9.1.3 and prettier-stylelint to 0.4.2, but this was happening before these updates.

VS Code version: Code - Insiders 1.22.0-insider (509b8084d46b82ec5851447903cebd914e4535a5, 2018-03-15T09:25:17.428Z)
OS version: Darwin x64 17.4.0

<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.5.1
code-settings-sync|Sha|2.9.0
Bookmarks|ale|0.18.2
project-manager|ale|0.24.1
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.8.1
svg|joc|0.0.9
ecdc|mit|0.11.0
HTMLHint|mka|0.4.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
vscode-versionlens|pfl|0.20.0
stylelint|shi|0.34.2
rewrap|stk|1.8.0

</details><details><summary>Results</summary>

Setting|Extension|Score
---|---|---
stylefmt.configBasedir|mrmlnc.vscode-stylefmt|0.018
stylefmt.config|mrmlnc.vscode-stylefmt|0.017
stylefmt.useStylelintConfigOverrides|mrmlnc.vscode-stylefmt|0.017
stylefmt.showErrorMessages|mrmlnc.vscode-stylefmt|0.001

</details>

Query: styleli
Literal matches: 8

**Comment by aeschli** [comment]
@smlombardi Can you add a small sample code?
If the errors come from style lint, you will have to file the issue against that extension.

**Comment by smlombardi** [comment]
```
<div class="home-hero-main">

  
</div>




<div class="container">
  <div class="row">
    <div class="col-md-12">

    </div>

  </div>
</div>
```

![2018-03-16_08-45-51](https://user-images.githubusercontent.com/835148/37521277-8a3642d0-28f6-11e8-9d10-728868de25e8.jpg)

**Comment by aeschli** [comment]
Yes, looks like a stylelint issue. Please file against the extension you are using.

**Comment by ritcheyer** [comment]
I'm experiencing this same issue. @smlombardi did you log this against the Stylelint project? If so, where?

**Comment by smlombardi** [comment]
https://github.com/stylelint/stylelint/issues/3221

They renamed it and closed it, but I have no idea if they fixed it.  Feel free to log another issue.
