### ISSUE TITLE
Can't detect git repository by opening a symlink to a file within it

### ISSUE THREAD

**Issue by phosphoer** [Microsoft/vscode#45919]
Our Unity project utilizes symlinks which point to folders within submodules in order to avoid having extra source code in the Unity Assets folder. Now that submodules are no longer all automatically loaded, we are seeing an issue where opening a file within a submodule through the symlink does not trigger the submodule to be loaded. 

- VSCode Version: 1.21.1
- OS Version: Windows 10 Insiders

**Steps to Reproduce:**
- Create a symlink somewhere in your project which points to a folder within a submodule. 
- Press `Ctrl-P` and enter the name of a file within the submodule, observe two entries are listed, the path directly within the submodule, and the path through the symlink. 
- Open the path through the symlink, and observe that the relevant submodule is not loaded into the source control provider list. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is probably not related to submodules but to symlinks to files within git repositories. I doubt the repository would get detected.
