### ISSUE TITLE
[TS]Getting duplicate error message in editor without adding linter extension for typescript.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4591]
OS Version: Windows10
VSCode version: 0.10.12-alpha

Steps:
1. launch app and open a folder which contain .TS file.
2. Verify any error message is showing up.

Expected: If there is not extensions installed for TS lint then error should not be highlighted in editor.

Actual:
While verifying bug #4107 with "Express Node.js typescript" project. I observed that there are two error messages showing up in my .ts file and when I closely watched, I found there is no extension installed for TS lint. I also removed extension for ESlint as well and restarted app.

I observer that still it is showing two errors messages in the editor and when I hover over on it, it is displaying : 
 1. [ts] cannot find module 'http'
 2. [ts] Cannot find name process.

But when I clicked on error icon from the status bar then could see in the pop-up (in command palette) it is showing up duplicate error message like below.
![image](https://cloud.githubusercontent.com/assets/17735796/13971529/2f31fdd0-f04e-11e5-8f07-09289b9c3997.png)

Questions:
 1. When there is no linter installed for TS or ES then why it is displaying red mark in the code.
 2. Is there any reference left for the TSLint in the system after removing extension which is causing this issue.
![image](https://cloud.githubusercontent.com/assets/17735796/13971525/22ca61b8-f04e-11e5-9c5e-c2bb0e4efce8.png)

I also verified in the extension directory and didn't find any reference of TS or ES lint extension.
![image](https://cloud.githubusercontent.com/assets/17735796/13971518/1508270e-f04e-11e5-80ed-cfda052d5f96.png)

**Comment by egamma** [comment]
The linters generate markers and these markers survive when a linter is uninstalled.

A linter should remove the diagnostics it generated in the extensions deactivate call.

Not critical for March.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-languageserver-node#29

**Comment by dbaeumer** [comment]
This should be done in the LanguageServerClient in deactivate.
