### ISSUE TITLE
Ubuntu apt-get : Writing more data than expected (285222 > 281970)

### ISSUE THREAD

**Issue by gurolayanlar** [Microsoft/vscode#45917]
- VSCode Version: 1.20.1
- OS Version: Ubuntu 16.04.4 LTS

Steps to Reproduce:

1. sudo apt-get update
2. E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages  Writing more data than expected (285222 > 281970)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by TingluoHuang** [comment]
+1 i also hitting this on Ubuntu 16.04 by running `Apt-get update`

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/45868
