### ISSUE TITLE
[HTML][Angular] suggestions are duplicated (2x)

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#45910]
- VSCode Version: 1.21 
Windows
---

look on:

https://github.com/Microsoft/vscode/issues/44974

this happend with all "data-ng-" atributes when you already had writen in another tags.

```
...
<body data-ng-app="">
    <div id="first" data-ng-include=" 'firstdoc.html' "></div>
    <div id="second" inc|></div>
                        ^
</body>
...
```

at `^` (cursor `|`) position it suggest (I think emmet) 2x data-ng-include,... this happend with a lot of other Angular attributes (directives) like ngCloack, ngController, etc.

**Comment by ramya-rao-a** [comment]
suggestions for attributes are not related to emmet, so updated the title

**Comment by Mlocik97-issues** [comment]
Ok, my bad

**Comment by aeschli** [comment]
@Mlocik97-issues Do you have an Angular extension installed?

**Comment by Mlocik97-issues** [comment]
No I haven't...

**Comment by Mlocik97-issues** [comment]
It do also when I had all extensions disabled.
