### ISSUE TITLE
Breakpoints automatically deactivated immediately after launching debugger

### ISSUE THREAD

**Issue by achawla5000** [Microsoft/vscode#45923]
I started to observe this issue after installing vscode v1.21.1 - I'm using the Debugger for Chrome extension.  My app is Angular Typescript.  This issue is reproducible 100% of the time when I launch the debugger for this type of app. 

**Steps to Reproduce**:
1) Set a breakpoint in a typescript file.  Look at the section of the DEBUG window in vscode labeled "BREAKPOINTS", and note that the breakpoint which was set is currently active (i.e., not deactivated).
2) In the vscode DEBUG window click the play button labeled "Launch localhost with sourcemaps (_myappname_)"
**Actual Behavior**: After Chrome is launched, look at the section of the DEBUG window labeled "BREAKPOINTS", and note that the breakpoint which was set in step 1 above has been deactivated.  It remains deactivated thereafter, and therefore, the breakpoint cannot not be hit during the debugging process, unless the developer intervenes and clicks the toggle button to re-activate the breakpoint.
**Expected Behavior**:  After clicking the play button labeled "Launch localhost with sourcemaps (_myappname_)", the breakpoint which was set in step 1 above should not be deactivated, unless the developer intervenes by clicking the toggle button to deactivate the breakpoint. 

Here are the contents of the launch.json -
`{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "Launch localhost with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3001",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "userDataDir": "${workspaceRoot}/.vscode/chrome"
        }
    ]
}`

**Comment by roblourens** [comment]
This is could be https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464, please update the Chrome extension and let me know if that fixes it.

**Comment by achawla5000** [comment]
I confirmed that using vscode v1.21.1 with the Debugger for Chrome extension version 4.2.1, I'm not able to reproduce this issue.

**Comment by roblourens** [comment]
Thanks for confirming.
