### ISSUE TITLE
Support sloppy focus

### ISSUE THREAD

**Issue by masiulaniec** [Microsoft/vscode#45926]
I am used to not having to click around to change focus from one editor pane to another. Same goes for terminal panes and for switching between editor and terminal. In the Linux world, this feature is called focus-follows-mouse/"sloppy focus" and is implemented by almost all window managers. It would be great if VSCode supported it natively or at least made it possible to implement as an extension.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/44214
