### ISSUE TITLE
Should --locale command line setting override locale.json?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#4592]
- VSCode Version:0.10.12 alpha
- OS Version:Windows 8

Steps to Reproduce:

1. Set a locale in locale.json e.g. `fr`
2. Launch VS Code specifying a different locale code-alpha --locale=de

I would expect the command line argument to win and override the user setting.

**Comment by Tyriar** [comment]
I think it should, the main use case is probably testing now that the setting was added. If `--locale` wins it also allows multiple locales to launch at once.

**Comment by gregvanl** [comment]
Running multiple instances of VS Code with different locales is not supported according to Won't Fix https://github.com/Microsoft/vscode/issues/4596.

**Comment by dbaeumer** [comment]
It should win and it does win (tested on latest). But please note that if there is a running code then the command line arg is ignored due to the discussionin #4596.
