### ISSUE TITLE
Extension management via CLI opens editor instead of performing operation

### ISSUE THREAD

**Issue by stephenwhittle** [Microsoft/vscode#45927]
Issue Type: <b>Bug</b>

Steps:
1. Download latest stable or Insiders build of VSCode (I have tested with both)
2. Execute code --list-extensions
3. Observe main Code window opens 

Expected: Code prints list of extensions, doesn't open main window

Same occurs with --install-extension as well - no installation occurs and the main window opens. Running the command with the verbose option shows that list-extensions is being correctly detected as an argument:
` 'list-extensions': true,`

The issue occurs both with extensions installed, and without. It also happens regardless of the 
--user-data-dir --extensions-data-dir --extensionHomePath options. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3298)|
|Memory (System)|15.91GB (5.04GB free)|
|Process Argv|J:\toolchain-test\cmder\vendor\vscode\code.exe --verbose --list-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by joaomoreno** [comment]
Can you show me your `PATH` variable?

**Comment by stephenwhittle** [comment]
I'm normally launching vscode from inside a MSYS2 bash shell, so PATH looks like the folllowing:

`PATH="/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"`
`
MSYS2 converts the Linux style paths to Windows ones on-the-fly. This allows Code to detect executables like CMake, Git etc, that have been installed in MSYS2.

However, your comment prompted me to test in a standard cmd prompt as well - there was no change in the erroneous behaviour, I still don't get a list of extensions printed to the command line. Here's the PATH from CMD, 

`Path=D:\Dropbox\Electronics\toolchain\cmder\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Java\jdk1.8.0_161\bin;C:\Tizen\tools\ide\bin;C:\Users\Stephen\AppData\Local\Microsoft\WindowsApps;C:\intelFPGA\17.0\modelsim_ase\win32aloem
`

**Comment by joaomoreno** [comment]
I don't see Code anywhere the path. Is it `C:\Tizen\tools\ide`? What's inside `C:\Tizen\tools\ide\bin`?

**Comment by stephenwhittle** [comment]
It's a portable install, so I'm launching Code via an absolute path and using --user-data-dir --extensions-data-dir --extensionHomePath - though removing those options made no difference to the behaviour. 

`%CMDER_ROOT%/vendor/vscode/code.exe --user-data-dir %CMDER_ROOT%/vendor/vscode --extensions-data-dir %CMDER_ROOT%/vendor/vscode/data --extensionHomePath %CMDER_ROOT%/vendor/vscode/extensions" --list-extensions`

**Comment by joaomoreno** [comment]
Got it. You must use the `code.cmd` or `code.sh` scripts inside the `bin` folder for that to work. So, try:

```
%CMDER_ROOT%/vendor/vscode/bin/code.cmd --user-data-dir %CMDER_ROOT%/vendor/vscode --extensions-data-dir %CMDER_ROOT%/vendor/vscode/data --extensionHomePath %CMDER_ROOT%/vendor/vscode/extensions" --list-extensions
```

**Comment by stephenwhittle** [comment]
No difference at this end, unfortunately. However, you left a stray double-quote there that made me try 

`"%CMDER_ROOT%/vendor/vscode/bin/code.cmd" "--user-data-dir %CMDER_ROOT%/vendor/vscode" "--extensions-data-dir %CMDER_ROOT%/vendor/vscode/data" "--extensionHomePath %CMDER_ROOT%/vendor/vscode/extensions" --install-extension vector-of-bool.cmake-tools`

and it worked! 
After a little further testing, it seems quoting each argument as I've done here is the key. This surprises me, as the CMDER_ROOT variable has no spaces in it, and it only works with quotations around either each indivdual argument as above, or quoting the arguments together like this
`%CMDER_ROOT%/vendor/vscode/bin/code.cmd "--user-data-dir %CMDER_ROOT%/vendor/vscode --extensions-data-dir %CMDER_ROOT%/vendor/vscode/data --extensionHomePath %CMDER_ROOT%/vendor/vscode/extensions" --list-extensions`

Quoting the paths on their own like this means I get the AppData installed extensions instead (ie the data-dir arguments have no effect).
`%CMDER_ROOT%/vendor/vscode/bin/code.cmd --user-data-dir "%CMDER_ROOT%/vendor/vscode" --extensions-data-dir "%CMDER_ROOT%/vendor/vscode/data" --extensionHomePath "%CMDER_ROOT%/vendor/vscode/extensions" --list-extensions`

I can't see anything in the documentation that indicates quoting the arguments is necessary, though.

**Comment by joaomoreno** [comment]
Quotes are relative to the shell which launches programs, it has nothing to do with VS Code.

I'm glad it works now.
