### ISSUE TITLE
terminal not showing underline on linux

### ISSUE THREAD

**Issue by sombriks** [Microsoft/vscode#45925]
Issue Type: <b>Bug</b>

the integrated terminal does not show underlines. see print screen.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.15.8-300.fc27.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 1500)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (0.50GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.20
Bookmarks|ale|0.18.2
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
systemd-unit-file|coo|1.0.0
prettier-vscode|esb|1.2.2
easy-icons|jam|0.3.1
Go|luk|0.6.77
cpptools|ms-|0.15.0
vetur|oct|0.11.7
java|red|0.20.0
vscode-icons|rob|7.21.0
vue-vscode-extensionpack|sdr|0.1.2
vue-vscode-snippets|sdr|1.3.0
ayu|tea|0.14.0
html-preview-vscode|tht|0.1.1
vscode-status-bar-format-toggle|tom|1.3.0
pdf|tom|0.2.0
vscode-java-debug|vsc|0.7.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.5.0

(13 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by sombriks** [comment]
https://www.dropbox.com/s/4cgv11sppcwuoui/Captura%20de%20tela%20de%202018-03-15%2019-47-21.png?dl=0

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
