### ISSUE TITLE
Recent insiders build (~last night) broke find and replace

### ISSUE THREAD

**Issue by BillyONeal** [Microsoft/vscode#45931]
Issue Type: <b>Bug</b>

1. Find and replace content in a document.
2. Change the find and replace string to something else, after doing a find and replace.
3. Find and replace starts matching things like line endings that have nothing to do with with the input.

This broke just recently in an insiders nightly build.

VS Code version: Code - Insiders 1.22.0-insider (509b8084d46b82ec5851447903cebd914e4535a5, 2018-03-15T09:31:27.063Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor  (32 x 3394)|
|Memory (System)|31.89GB (25.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0
sort-lines|Tyr|1.5.0

</details>
Reproduces without extensions

**Comment by BillyONeal** [comment]
Screenshot of match of line endings:
<img width="1056" alt="2018-03-15_17-54-29" src="https://user-images.githubusercontent.com/1544943/37498192-2757fbe4-287a-11e8-82ed-2b95f7375e2c.png">

Video demonstration:
[VS Code Bug.zip](https://github.com/Microsoft/vscode/files/1817580/VS.Code.Bug.zip)

**Comment by dlong500** [comment]
I've noticed the same thing.  It also seems, after doing a replace, to match locations of where the replaced data used to be.  Very strange...

**Comment by eamodio** [comment]
Yeah you don't even have to do a find/replace, just making edits (delete a word) and then select that same word elsewhere in the doc and it will still highlight the characters from the deleted word.

**Comment by rebornix** [comment]
@eamodio do you have a stable reproduce for this issue?

**Comment by eamodio** [comment]
@rebornix 
![highlight-issue](https://user-images.githubusercontent.com/641685/37505108-3cd8068c-28b9-11e8-8aba-47812da80f36.gif)

**Comment by rebornix** [comment]
@eamodio thanks, I successfully reproduced locally and fixed it. Let me know if you still see it once you get the new Insider.

**Comment by rebornix** [comment]
Dup of #45770, already fixed in current insider.
