### ISSUE TITLE
Reorder Project Structure using Drag & Drop

### ISSUE THREAD

**Issue by dimwell-git** [Microsoft/vscode#45936]
- VSCode Version: 1.21.1
- OS Version: macOS High Siera Version: 10.13.2

Steps to Reproduce:

1. Open any project that contains couple of files and folders.
2. Try to reorder the structure according to project logic using Drag & Drop.

Does this issue occur when all extensions are disabled?: Yes

It would be great if it would be possible to reorder project structure according specific needs using drag & drop. 

It looks like currently VS Code sorts project structure according to alphabetic order. 
In large project more often than not  alphabetic ordering does not make sense. 
It would give a great benefit if user, could organise files and folders structure according to some logic.

**Comment by bpasero** [comment]
@dimwell-git we do support DND in the explorer, what do you mean specifically? Can you attach a screenshot what you are trying to achieve?

**Comment by isidorn** [comment]
We support DnD, if you want sorting in explorer checkout "explorer.sortOrder" setting. If you want more sorting options there is already a fetaure requst for that.
If it is something else, please clarify and I will reopen
