### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by kimkimson** [Microsoft/vscode#45938]
Issue Type: <b>Bug</b>

i can not debug JS on vs code 
this is msg : Debug adapter process has terminated unexpectedly
thanks for help

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1596)|
|Memory (System)|3.91GB (1.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.2.1
JavaScriptSnippets|xab|1.5.0

</details>
Reproduces only with extensions

**Comment by topchyalexey** [comment]
The same issue. No logs, no debug info. WHere I can find it?
>react-native run-ios 
runs Ok
...
** BUILD SUCCEEDED **


System info:
CPUs | Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)
-- | --
Load (avg) | 2, 2, 2
Memory (System) | 16.00GB (0.26GB free)
Process Argv | /Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_65552
Screen Reader | no
VM | 0%

debugger-for-chrome | msj | 4.2.1
-- | -- | --
vscode-react-native | vsm | 0.6.5

**Comment by edchapel** [comment]
I am getting the same issue and I think it is due to the debugger-for-chrome 4.2.1.

4.2.0 is still installed in my extensions folder. When I remove 4.2.1, the debugging works again.

**Comment by roblourens** [comment]
@kimkimson @topchyalexey are you debugging Chrome or Node?

**Comment by kimkimson** [comment]
I'm debugging JavaScript with vscode. I dont understand what going on here
now. Help me, please.

Vào Th 7, 17 thg 3, 2018 lúc 01:27 Rob Lourens <notifications@github.com>
đã viết:

**Comment by roblourens** [comment]
Could you post your launch config (from the launch.json file)?

**Comment by topchyalexey** [comment]
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug iOS",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "target": "iPad Air",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
 
    ]
}

**Comment by roblourens** [comment]
Please file an issue on the React native extension repo

**Comment by kimkimson** [comment]
this is launch.json file

this is notification


help me. plese

2018-03-17 22:27 GMT+07:00 Rob Lourens <notifications@github.com>:

**Comment by Paari** [comment]
@kimkimson I was also facing the issue and it is now fixed, if you update the React Native Tools extension everything should work fine.

**Comment by roblourens** [comment]
@Paari that extension isn't included in the OP so I think @kimkimson has a different issue.

@kimkimson please post your launch.json file here.

**Comment by pieandcakes** [comment]
@roblourens @weinand I'm seeing this on the C++ extension too. I've had to reinstall the extension to get the error to go away. I don't know what would be causing it but I also have an end-user complaining about it:
https://github.com/Microsoft/vscode-cpptools/issues/1719

@wardengnaw

**Comment by roblourens** [comment]
These issues could also be from corrupt extension installs like in https://github.com/Microsoft/vscode/issues/43813

**Comment by lindapescatore** [comment]
I'm getting this for a .py program.

**Comment by weinand** [comment]
@lindapescatore then please file this issue against the Python debugger extension. This Issue is about JS.

**Comment by roblourens** [comment]
Is this still an issue? There's a confusing mix of messages here. Haven't had a report in awhile, so closing.
