### ISSUE TITLE
[TS] 'require' function should be highlighted same as reserved keywords as it is provided by CommonJS compliant system.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4593]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:

1.  Launch app and open any folder which contains .ts file.
2. Add below code in the file and compare it with Visual studio.

Actual: 'require' is not highlighted.
Expected: As 'require' is provided by CommonJS compliant system so it should be highlighted with blue color.

 import http = require('http');
var port = process.env.port || 1337
http.createServer(function (req, res) {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('Hello World\n');
}).listen(port);

![image](https://cloud.githubusercontent.com/assets/17735796/13972337/104b0e0a-f055-11e5-961d-e193466dcfc3.png)

**Comment by aeschli** [comment]
Moving to the TS team to consider.
I personally would not colorize require as a keyword. We also don't highlight other library functions like keywords.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#135
