### ISSUE TITLE
Javascript Syntax Highlighting Bug

### ISSUE THREAD

**Issue by alek5k** [Microsoft/vscode#45933]
- VSCode Version: 1.16.0
- OS Version: Windows 10

![syntax highlighting fail](https://user-images.githubusercontent.com/20435565/37499856-3f7a9d44-291a-11e8-85a9-83729c29b9a5.PNG)

Steps to Reproduce:

1. Set syntax highlighting to javascript
2. Type in the following failure case:

`if (startDragXOffset < cornerDistanceThreshold && startDragYOffset > (shapeWidth - cornerDistanceThreshold))`

3. Compare with the following success case:

`if (startDragXOffset < cornerDistanceThreshold && startDragYOffset >= (shapeWidth - cornerDistanceThreshold))`

I have a feeling the regex check is looking for the "> (" combination which is used with arrow functions, eg:

(ctx) => ({ctx})

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#584
