### ISSUE TITLE
Custom shorcut for git.unstageSelectedRanges not working

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#45942]
Issue Type: <b>Bug</b>

I'm trying to set the following shortcut keys, but `ctrl+u` for `git.unstageSelectedRanges` doesn't seem to work.

```json
{
    "key": "ctrl+s",
    "command": "git.stageSelectedRanges",
    "when": "editorTextFocus && isInDiffEditor && !editorReadonly"
},
{
    "key": "ctrl+u",
    "command": "git.unstageSelectedRanges",
    "when": "editorTextFocus && isInDiffEditor && !editorReadonly"
}
```

I've even tried adding this first:
```json
{
    "key": "ctrl+u",
    "command": "-cursorUndo"
},
```

VS Code version: Code - Insiders 1.22.0-insider (509b8084d46b82ec5851447903cebd914e4535a5, 2018-03-15T09:31:27.063Z)
OS version: Windows_NT x64 10.0.17120

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|31.93GB (16.86GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by eamodio** [comment]
FYI, it isn't just `ctrl+u` either, I tried other keys and it still doesn't work

**Comment by joaomoreno** [comment]
But when you run `unstageSelectedRanges` aren't you in the index diff editor? If so, the right-hand side editor will be readonly, so `!editorReadonly` is probably a bad idea.

**Comment by eamodio** [comment]
@joaomoreno I'm an idiot, you are correct -- thank you. I swear I tried it without the readonly, but apparently not.
