### ISSUE TITLE
Doc Request: Where is the all available 'when' condition values of Contribution Points ?

### ISSUE THREAD

**Issue by ayqy** [Microsoft/vscode#45943]
Yes, but something related to the lack of extension document is the common case, not a certain question about my own projects.

- VSCode Version:NA
- OS Version:NA

Steps to Reproduce:

1.Search on the [official docs website](https://code.visualstudio.com/docs/extensionAPI/extension-points)
2.No related results found

Does this issue occur when all extensions are disabled?: Yes/No
Yes

FYI, related question is [here](https://stackoverflow.com/questions/38267360/vscode-extension-api-identify-file-or-folder-click-in-explorer-context-menu), but any update or official docs ?

**Comment by eamodio** [comment]
@ayqy I doubt that this is the full list, but here is what is documented today: https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

**Comment by ayqy** [comment]
@eamodio Thanks for your response.

>  Contribute a menu item for a command to the editor or Explorer. The menu item definition contains the command that should be invoked when selected and the condition under which the item should show. The latter is defined with the when clause which uses the key bindings [when clause contexts.](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts)

Link in above doc is what I missed then, maybe it would be a bit more conspicuous. eg. A separate section or just move the existing full list (at GET STARTED/Key Bindings) to the extension API page.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1503
