### ISSUE TITLE
Failed to install VS Code Insiders update

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#45947]
![2018-03-16_07h46_03](https://user-images.githubusercontent.com/3082812/37504360-db470e50-28ee-11e8-97cc-742d5e8b675e.png)

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1817953/vscode-inno-updater.log)

- VSCode Version:
Версия 1.22.0-insider
Фиксация 02def72
Дата 2018-03-15T06:16:25.881Z
Оболочка 1.7.9
Отрисовщик 58.0.3029.110
Узел 7.9.0
Архитектура x64

- OS Version:
win7 pro

Steps to Reproduce:

1. reinstall vscode

**Comment by joaomoreno** [comment]
@IgorNovozhilov Does this happen constantly when you get an update, or just this one time?

**Comment by IgorNovozhilov** [comment]
this error is repeated every 3-4 updates, today updated was a success.

**Comment by joaomoreno** [comment]
What are the specs of your machine?

**Comment by IgorNovozhilov** [comment]
win7 pro x64 RU-ru sp1
i5-4570 RAM 16Gb
HDD 500Gb WD5000

**Comment by IgorNovozhilov** [comment]
2 days without incident.
`Mar 20 22:48:07.090 INFO Update was successful!`
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1830969/vscode-inno-updater.log)

**Comment by IgorNovozhilov** [comment]
`Mar 23 07:28:45.866 INFO Update was successful!`
@joaomoreno, looks like it was a temporary problem.

**Comment by IgorNovozhilov** [comment]
The error happened again `Apr 06 16:45:09.890 ERRO Failed to get process file name`
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1884191/vscode-inno-updater.log)

**Comment by IgorNovozhilov** [comment]
something new
`Apr 17 09:37:08.000 ERRO Папка не пуста. (os error 145)`
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1918374/vscode-inno-updater.log)

**Comment by IgorNovozhilov** [comment]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1931914/vscode-inno-updater.log)

**Comment by IgorNovozhilov** [comment]
Now something new.
![image](https://user-images.githubusercontent.com/3082812/41641987-b2525442-746f-11e8-85a7-0ef31f214542.png)
```
Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	inno_updater.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	5ae08b0b
  Имя модуля с ошибкой:	inno_updater.exe
  Версия модуля с ошибкой:	0.0.0.0
  Отметка времени модуля с ошибкой:	5ae08b0b
  Код исключения:	c000001d
  Смещение исключения:	00010b61
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	0a9e
  Дополнительные сведения 2:	0a9e372d3b4ad19135b953a78882e789
  Дополнительные сведения 3:	0a9e
  Дополнительные сведения 4:	0a9e372d3b4ad19135b953a78882e789

Ознакомьтесь с заявлением о конфиденциальности в Интернете:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419

Если заявление о конфиденциальности в Интернете недоступно, ознакомьтесь с его локальным вариантом:
  C:\Windows\system32\ru-RU\erofflps.txt
```

**Comment by IgorNovozhilov** [comment]
logs
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2118186/vscode-inno-updater.log)

**Comment by IgorNovozhilov** [comment]
It looks like the application can not be completed normally and remains to hang the process. It remains even if you close all open vscode applications.
However, the installer cannot automatically complete it either.
![image](https://user-images.githubusercontent.com/3082812/41642523-2feb1ef6-7471-11e8-96d6-c504a1d2c1ab.png)

**Comment by joaomoreno** [comment]
This specific issue should be fixed by now. Can you confirm @IgorNovozhilov ?

**Comment by IgorNovozhilov** [comment]
@joaomoreno. Yes, for the latest updates I no longer received this error. Thanks.
