### ISSUE TITLE
Combination key in Teminal (Powershell) is not working

### ISSUE THREAD

**Issue by jonathangc** [Microsoft/vscode#45940]
Issue Type: <b>Bug</b>

In last update, the terminal (powershell) lost the functionality of the key combination (Ctrl + Shift + Left or Right  arrow).

Windows 10 64bits.  

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|Memory (System)|7.89GB (1.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
pgformatter|bra|1.3.0
jshint|dba|0.10.17
vscode-eslint|dba|1.4.7
xml|Dot|1.9.2
language-polymer|jon|1.0.4
sublime-keybindings|ms-|3.0.3
vscode-docker|Pet|0.0.25
java|red|0.20.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
@jonathangc can you clarify what this did before?

You can get the old behavior by unbinding the resize keybindings. Add this to your keybindings.json:

```js
{ "key": "ctrl+cmd+left",         "command": "-workbench.action.terminal.resizePaneLeft",
                                     "when": "terminalFocus" },
{ "key": "ctrl+cmd+right",        "command": "-workbench.action.terminal.resizePaneRight",
                                     "when": "terminalFocus" },
```

**Comment by jonathangc** [comment]
@Tyriar 
With the combination of keys:
**_ctrl+shift+right or left_** I could select the word in the console. 
**_ctrl+backspace_** I could delete the word.

The functionality of this combination was replaced by resizePaneLeft and resizePaneRight.

**Comment by Tyriar** [comment]
@jonathangc @mlucic can you show me a screenshot of the selection? I can't get it to work using Windows 10 FCU with powershell.exe or the powershell extension set.

**Comment by mlucic** [comment]
@Tyriar 

![selection_example](https://user-images.githubusercontent.com/14261997/37615900-ba42dec6-2b84-11e8-8a74-38277d1fc7f3.JPG)

**Comment by jonathangc** [comment]
Without resizePaneLeft shortcut (**ctrl+shift+left**)
![combination_1](https://user-images.githubusercontent.com/16901604/37618406-c43d6062-2b7b-11e8-892d-e7290aeb2c7b.gif)

(**ctrl+delete**) is not working in VS Code.

**VS Code**
![combination_2_vscode](https://user-images.githubusercontent.com/16901604/37618531-2ae04a8c-2b7c-11e8-82a3-7fda48c071a8.gif)

**PowerShell**
![combination_2_powershell](https://user-images.githubusercontent.com/16901604/37618532-2b050318-2b7c-11e8-8587-7a3354e12929.gif)

**Comment by Tyriar** [comment]
Thanks all, I got it working. I'm going to remove the resize keybindings on Windows as it appears cmder and conemu both use apps+shift+arrow. Our keybindings system doesn't support apps as a modifier (which is really weird) so I think we'll just leave it unbound by default on Windows.

**Comment by Tyriar** [comment]
I removed the keybinding, selection in PS now works with the defaults.
