### ISSUE TITLE
Repeated module.exports expressions are erroneously flagged as problematic

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/vscode#4594]
- VSCode Version: (0.10.11) f291f4ad600767626b24a4b15816b04bee9a3049
- OS Version: OS X 10.10.5

Steps to Reproduce:

![js snippet](https://cloud.githubusercontent.com/assets/829827/13972386/aca5a152-f06e-11e5-84b8-dde7bfefcff6.png)

This code is perfectly fine, and should not be flagged as an error. The error message is:

> Duplicate identifier 'export='.

**Comment by jrieken** [comment]
This will work with the March release (insiders build already available).

![screen shot 2016-03-23 at 09 18 29](https://cloud.githubusercontent.com/assets/1794099/13979363/37cdc5fc-f0d8-11e5-8325-f80dd19da987.png)
