### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by riturajbarhgoojer** [Microsoft/vscode#45957]
Issue Type: <b>Bug</b>

I am getting error Debug adapter process has terminated unexpectedly
after updating my node version 6.** to 8.** . kindly help in this 

My Launch.js file
```json
{
  "version": "0.2.0",
    "configurations": [
         {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\server.js"
        }
    ]
}
```

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q8400  @ 2.66GHz (4 x 2660)|
|Memory (System)|6.96GB (0.92GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.17
vscode-eslint|dba|1.4.7
xml|Dot|1.9.2
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
node-version|fiv|0.0.1
beautify|Hoo|1.3.0
sublime-babel-vscode|jos|0.2.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.14.0
node-debug2|ms-|1.19.4
team|ms-|1.122.0
debugger-for-chrome|msj|4.2.1
react-beautify|tai|0.3.0

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Is there any output in the debug console? Can you set `"trace": true` and see whether it writes a log file path to the debug console?

@isidorn I see a few of these, any tips to get more info from the crash?

**Comment by isidorn** [comment]
@roblourens https://github.com/Microsoft/vscode/issues/41190

**Comment by riturajbarhgoojer** [comment]
i am getting this

![image](https://user-images.githubusercontent.com/21983723/37591636-311f4b26-2b92-11e8-8ccd-6ffe2793d68c.png)

**Comment by riturajbarhgoojer** [comment]
No logs, no debug info. WHere I can find it?

**Comment by riturajbarhgoojer** [comment]
but i am able to debug same project in webstrom

**Comment by jmarandet** [comment]
:+1: 
I am experiencing the same error message,  with VSCode 1.21 and after an update to 1.23 the issue is still here.
In my case the message shows up with chrome Debug extension (launch request on a simple url) on a Windows 7 desktop.

**Comment by guw** [comment]
@weinand Sorry for hijacking the issue. I'm also investigating an error like this. In my case everything works when running in hosted mode, i.e. extension host from source. However, when I have Code (or Code Insider) with the extension installed from vsix the debug adapter fails immediately - no output logged anywhere. All my code is within try/catch so I wonder how to debug the issue. I suspect a dependency issue because we identified the commit that broke it.

**Comment by roblourens** [comment]
@riturajbarhgoojer is this still an issue?

Better logs for this error should have come with #41190. If you see any more error info now, please let me know.
