### ISSUE TITLE
Extension backward compatibility lost

### ISSUE THREAD

**Issue by SAKryukov** [Microsoft/vscode#45956]
## Summary

Backward compatibility of extension API lost starting with v. 1.21.

- VSCode Version:
    * 1.21.0
    * 1.21.1
- OS Version:
Windows 7

## Steps to Reproduce:

1. Install Visual Studio Code 1.21.0 or 1.21.1
1. Install extension [Extensible Markdown Converter](https://marketplace.visualstudio.com/items?itemName=sakryukov.convert-markdown-to-html)
1. Create file `.md`
1. In editor control, activate context menu.
1. Activate one of the following items: "Markdown: *", for example "Markdown: Convert to HTML".
1. Alternatively, click on one of the toolbar images which show the commands "Markdown: Convert to HTML" or "Markdown: Open Preview (Ctrl+Shift+V)"
1. Observe "Command not found" error message.
1. Install Visual Studio Code 1.20 and observe that the extension works.
   It also works with Install Visual Studio Code versions 1.14.1 to 1.20.

See also: [Extension GitHub repository](https://github.com/SAKryukov/vscode-markdown-to-html), [https://github.com/SAKryukov/vscode-markdown-to-html.git](https://github.com/SAKryukov/vscode-markdown-to-html.git)

Does this issue occur when all extensions are disabled?: No :-)

**Comment by mjbvz** [comment]
Please file an issue against that extension
