### ISSUE TITLE
Ctrl+P

### ISSUE THREAD

**Issue by AmitPoojary** [Microsoft/vscode#45955]
Issue Type: <b>Bug</b>

Go to File (Ctrl+P) not working. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|Memory (System)|7.92GB (2.86GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
debugger-for-chrome|msj|4.2.1

</details>
Reproduces only with extensions

**Comment by aeschli** [comment]
Please give some more information. What do you see on Ctrl + P and what do expect.
Screenshots and/or animated gif can also be useful.

**Comment by apieceofbart** [comment]
I am having similar issues. 

Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Hitting Ctrl+P does nothing. Other shorcuts seem to work fine, e.g. Ctrl+Shift+P opens "Show All Commands" dialog and Ctrl+Tab allows me to switch list of opened files as expected.
Runnig `code --disable-extenstions` doesn't help. I also disabled all extensions - no effect.

Is there a debug mode I can try?
