### ISSUE TITLE
viewing files causes them to jump / force scroll about 10 lines down

### ISSUE THREAD

**Issue by HawkenKing** [Microsoft/vscode#4595]
- VSCode Version: Version 0.10.10 (0.10.10)
- OS Version: Yosemite / El Capitan

Steps to Reproduce:

1. click on any file in the explorer
2. view jumps to line 10 or 12

Expected functionality would be that the file opens with line 1 visible.

**Comment by bpasero** [comment]
@HawkenKing we restore the last used scroll position when you reopen a file. Could it be you left the file at the position before?

**Comment by HawkenKing** [comment]
it does it with every file, any file, tested on 3 different macs. Unity + C#

**Comment by HawkenKing** [comment]
Can confirm last used scroll position works. This is for un-viewed (1st time) files and files that have been scrolled to line 1 then re-viewed.

**Comment by bpasero** [comment]
@alexandrudima any idea?

**Comment by rakkarage** [comment]
same as this? https://github.com/Microsoft/vscode/issues/3458

**Comment by HawkenKing** [comment]
Looks like the same issue.

**Comment by HawkenKing** [comment]
As far as I can tell something like this is happening on c# files:

document opens
displays starting at line 1
"references" fade in above variables & functions
document force scrolls down

**Comment by bpasero** [comment]
Marking as duplicate then: #3458
