### ISSUE TITLE
Coffeescript debugger breakpoints on none entry scripts do not trigger 

### ISSUE THREAD

**Issue by caoool** [Microsoft/vscode#45959]
- VSCode Version: 1.21.1
- OS Version: 10.13.3

Hi,
Thanks in advance for reading and helping.

Here is the situation, I found it to be a little glitchy when debugging coffee script
When I put break points in index.coffee (entry), it will stop and debug properly
but if I import another coffee script file, it will treat that file as standard js syntax
for instance, in index.coffee
```
import './a.coffee'
```
then in a.coffee
```
console.log 'hi'
```

It will print unexpected string error, but if I change it to
```
console.log('hi')
```
it will then work as expected (partially, because stop points still not working on files except index.coffee)

here is some configurations

<img width="500" alt="screen shot 2018-03-16 at 1 15 56 am" src="https://user-images.githubusercontent.com/6248237/37510253-c2af3ec6-28b7-11e8-99e8-3590df7278f3.png">
<img width="619" alt="screen shot 2018-03-16 at 1 16 17 am" src="https://user-images.githubusercontent.com/6248237/37510274-d1f30aa2-28b7-11e8-9095-19d1362c5c17.png">
<img width="302" alt="screen shot 2018-03-16 at 1 16 30 am" src="https://user-images.githubusercontent.com/6248237/37510289-d3d0be8c-28b7-11e8-8ac6-736746743e05.png">
<img width="274" alt="screen shot 2018-03-16 at 1 16 39 am" src="https://user-images.githubusercontent.com/6248237/37510297-dcde3bbc-28b7-11e8-8a89-71e449b8cddc.png">
<img width="269" alt="screen shot 2018-03-16 at 1 16 47 am" src="https://user-images.githubusercontent.com/6248237/37510301-df04e7ec-28b7-11e8-8d0a-2e9cbdd8bc0e.png">
<img width="1024" alt="screen shot 2018-03-16 at 1 16 53 am" src="https://user-images.githubusercontent.com/6248237/37510308-e142fc9c-28b7-11e8-90e0-a7b3deb91d4e.png">

For instance
<img width="435" alt="screen shot 2018-03-16 at 1 20 35 am" src="https://user-images.githubusercontent.com/6248237/37510449-5211c50c-28b8-11e8-971c-ad8fc10a3490.png">

If I put a break point here in `a.coffee`, it cannot be triggered, but in `index.coffee`
<img width="1455" alt="screen shot 2018-03-16 at 1 22 47 am" src="https://user-images.githubusercontent.com/6248237/37510515-9224dc2e-28b8-11e8-9225-99918d909d83.png">
Break points works just fine.

**Comment by roblourens** [comment]
Can you check whether it works in Insiders? Could be https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464 although you already have outFiles set which is good.

If not please set `"trace": true`, try again and upload the log from the debug console here.
