### ISSUE TITLE
keybindings with multiple conditions in when clause doesn't work

### ISSUE THREAD

**Issue by webmandman** [Microsoft/vscode#45951]
**Issue Type:** Bug

**VS Code version:** Code - Insiders 1.22.0-insider (a716373aaaf50cbce3618688a645b324721b35dd, 2018-03-14T05:15:41.910Z)
**OS version:** Windows_NT x64 10.0.10586

**System Info**
CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)
Memory (System): 23.88GB (15.68GB free)
Process Argv: C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
Screen Reader: no
VM: 0%

**Extensions:**
xml(Dot) 1.9.2
coldfusion(ili) 1.0.1
vscode-journal(paj) 0.5.0
vim(vsc) 0.11.2
vscode-jumpy(wma) 0.3.1

**How to reproduce:** 
Install the extensions mentioned above, specially Vim emulation for Visual Studio Code aka vscodevim. 

Then create these keybindings. In my opinion these shortcuts will be awesome to focus on various parts of the IDE without a mouse. I intend to create more with <space>.

[
    {
        "key": "space r",
        "command": "workbench.action.reloadWindow",
        "when": "vim.mode != 'Insert Mode' && !inQuickOpen && !editorTextFocus && !terminalFocus"
    },

    {
        "key": "space f",
        "command": "workbench.action.focusFirstEditorGroup",
        "when": "vim.mode != 'Insert Mode' && !inQuickOpen && !editorTextFocus && !terminalFocus"

    },
    {
        "key": "space g",
        "command": "workbench.action.focusSecondEditorGroup",

        "when": "vim.mode != 'Insert Mode' && !inQuickOpen && !editorTextFocus && !terminalFocus"
    },
    {
        "key": "space h",
        "command": "workbench.action.focusThirdEditorGroup",
        "when": "vim.mode != 'Insert Mode' && !inQuickOpen && !editorTextFocus && !terminalFocus"
    },
    {
        "key": "space tab",
        "command": "workbench.action.openNextRecentlyUsedEditorInGroup",
        "when": "vim.mode != 'Insert Mode' && !inQuickOpen && !editorTextFocus && !terminalFocus"
    },
    {
        "key": "ctrl+tab",
        "command": "-workbench.action.openNextRecentlyUsedEditorInGroup"
    },
    {
        "key": "space t",
        "command": "workbench.action.terminal.toggleTerminal",
        "when": "vim.mode != 'Insert Mode' && !inQuickOpen && !editorTextFocus && !terminalFocus"
    },
    {
        "key": "ctrl+`",
        "command": "-workbench.action.terminal.toggleTerminal"
    }
]

**Comment by alexandrudima** [comment]
@webmandman I don't understand what the problem is or what, in your opinion, is not working?
