### ISSUE TITLE
Debug Console: "Copy All" results in [object Object] in the buffer

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#45967]
- VSCode Version: Insiders Latest
- OS Version: Mac OS

Steps to Reproduce:

1. Debug any program that prints something in the debug console (e.g. `console.log("test");` in JS)
2. Right click the console, do "Copy All"
-> List of `[object Object]` is in the buffer instead of the actual console output.

If text is manually entered in the console (not when debugging), it is copied in the buffer correctly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@michelkaporin great catch, thanks!

**Comment by dbaeumer** [comment]
Verified but opened https://github.com/Microsoft/vscode/issues/46919
