### ISSUE TITLE
TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45966]
**Steps to Reproduce:**

1. trigger a notification with button (see example below)
2. open notification center
3. click the button (the notification disappears)

**Stack:**

```
  ERR Cannot read property 'element' of undefined: TypeError: Cannot read property 'element' of undefined
    at ListView.toMouseEvent (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:348:68)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:269:130
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:327:72
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:103:38)
    at HTMLDivElement.fn (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/event.js:9:48)
```

**Trigger Notification:**
Create a HTML file and follow the link:
```html
<link rel="stylesheet" href="qunit/qunit22.css" type="text/css" media="screen" />
```

**Comment by bpasero** [comment]
Reproduces in stable as well. I was hoping this is the reproducible case for the tons of `Invalid Index` issues we are seeing in error telemetry, but does not seem so...

**Comment by joaomoreno** [comment]
I can't reproduce it in dev or insiders... is there any other detail you can think of?

**Comment by bpasero** [comment]
@joaomoreno ![before](https://user-images.githubusercontent.com/900690/37607719-1bac94c2-2b99-11e8-9027-e9a1db71debb.gif)

**Comment by joaomoreno** [comment]
@bpasero There must be a difference between the notification center and the lighterweight popups, since it doesn't reproduce in the latter.

**Comment by bpasero** [comment]
@joaomoreno yup that is true

**Comment by joaomoreno** [comment]
@bpasero Your were missing `stopPropagation` and `preventDefault` calls. That button class sure deserves a rewrite. ✏️ 😆

**Comment by bpasero** [comment]
@joaomoreno thanks! But it uses the builder, why rewrite that ;)

**Comment by joaomoreno** [comment]
One must not touch perfection
