### ISSUE TITLE
Set the _GTK_THEME_VARIANT X11 property on top-level window to use "dark" theme on Gnome

### ISSUE THREAD

**Issue by Paviluf** [Microsoft/vscode#45968]
Hello,

On Gnome with the default theme Adwaita, the titlebar is very bright an hurt your eyes. Adwaita have a dark variant and  for Vs Code to use it, it just need to set the _GTK_THEME_VARIANT X11 property on top-level window to use "dark" theme.

![27779206-bbb46458-5fc1-11e7-987c-57260b02ed8f](https://user-images.githubusercontent.com/17159065/37516851-cf863534-290f-11e8-8f02-26b0c2b14c01.png)
![27779210-c1da4e10-5fc1-11e7-8cd1-f0161d14d16c](https://user-images.githubusercontent.com/17159065/37516861-d286166e-290f-11e8-8bca-79de03098f08.png)

Can it be added please ? It's a very little modification but with great impact on usability on Gnome.

Thanks !

https://gitlab.gnome.org/GNOME/gtk/issues/99

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/16363

With Electron 2.x we can play around with adding a setting for this, since that comes with GTK3 support.
