### ISSUE TITLE
Test: Log Points

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#45962]
Refs: #45128

- [x] anyOS @alexandrudima 
- [x] anyOS @RMacfarlane 

Complexity: 3

In this milestone we've added support for LogPoints. A LogPoint is basically a breakpoint that does not result in a "break" in the debugger but instead "logs" a message to the console. A Log Point is represented by a "diamond" shaped red icon. The "log message" is the text that gets logged. Expressions within curly brackets are evaluated and their (string) result replaces the curly brackets in the log message. 
Example:
```
   this log message shows the actual value of the variable 'x': { x }
```
LogPoints support the "condition"  and the "hit count expression" too.

Verify:
* You can add log points via the glyph margin context menu and via the command palette
* You can transform an existing breakpoint to a log point by adding a log message
* You can edit the log message of a log point
* Once you start a debug session which does not support log points they show up as unsupported
* When running a program with LogPoints with Node Debug (both protocols), LogPoints does not result in a break in the debugger but instead log the message to the console
* Add a condition and/or hit count expression to a LogPoint and verify that the log message only appears if the condition evaluates to true and the hit count condition is reached.
* You get simple inteli-sense when inside the currly brackets {}. Or when adding conditions to a conditional breakpoint

**Comment by DanTup** [comment]
FWIW, I think there may be an issue with the variable substitution in TypeScript (I've opened #49039).

**Comment by isidorn** [comment]
Thanks, I have forwarded the issue to @roblourens so he can investage more closely on the debug adapter side.
