### ISSUE TITLE
--locale command line switch as no effect if there is already a running VS Code instance

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#4596]
- VSCode Version:0.10.12 alpha
- OS Version:Windows 10

Steps to Reproduce:

1. in one folder: code-alpha .           to start an English instance
2. in another folder: code-alpha . --locale=fr

The new instance is also in English.

3. Shutdown first code-alpha instance.  
4. code-alpha . --locale=fr 

Now VS Code comes up in french.

**Comment by bpasero** [comment]
We had a bug like this and decided that this scenario cannot be and is not supported.
