### ISSUE TITLE
Broken syntax highlight when pasting markdown code (regression)

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#45961]
Issue Type: <b>Bug</b>

With this insider build, the syntax highlight of pasted markdown code is broken.
I did more test and found these
- v1.21.1 stable build is fine (for both markdown and js code)
- for this insider build, js is fine, markdown is not.
- can reproduce with default theme

stable build
![image](https://user-images.githubusercontent.com/7588612/37512080-0a8d1900-293c-11e8-89e9-128e54b3853f.png)
insider build
![image](https://user-images.githubusercontent.com/7588612/37512119-26754c96-293c-11e8-86fd-503fefcaeb63.png)

One more detail is that I'm pasting with [Snipaste](https://www.snipaste.com/).
When pasting into browser (e.g. mail app), it seems to work well.

VS Code version: Code - Insiders 1.22.0-insider (9160e85b1ab0333dfe697032f90da494f1f81fd4, 2018-03-16T06:17:01.718Z)
OS version: Windows_NT x64 10.0.17120

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|7.91GB (2.13GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|36%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
statusbar-commands|anw|0.1.0
spellright|ban|2.1.30
path-intellisense|chr|1.4.2
log-wrapper-for-vscode|chr|1.0.2
githistory|don|0.4.0
jupyter|don|1.1.4
vsc-material-theme|Equ|1.5.1
vscode-todo-plus|fab|1.9.0
latex-workshop|Jam|3.14.0
vscode-regexp-preivew|le0|0.0.3
ftp-sync|luk|0.3.3
python|ms-|2018.2.1
LiveServer|rit|3.2.1
vscode-todo-highlight|way|0.5.12
dictionary-completion|yzh|0.6.0
markdown-all-in-one|yzh|1.1.0
memento|yzh|0.0.1
vscode-remark|yzh|0.0.1

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
@neilsustc This only happens when extensions are enabled? Can you try tracking down which one may be causing this

**Comment by neilsustc** [comment]
I just test on my laptop and everything is ok.
But I can still reproduce on another machine although I think there is no difference between them...
So now I think it might not be an issue of vscode. And if I find more info later I will go back here.
Thanks.
