### ISSUE TITLE
Allow extension language-specific commands

### ISSUE THREAD

**Issue by mhchem** [Microsoft/vscode#45969]
Please allow extensions to contribute command just for specific languages.
The mechanism for this exists (e.g. most command with "markdown" are only available in editors with markdown file). But there is no (documented) way to define that in the package.json, just

```json
"contributes": {
    "commands": [{
        "command": "extension.sayHello",
        "title": "Hello World",
        "category": "Hello"
    }]
}
```
(https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands)

**Comment by jrieken** [comment]
>  (e.g. most command with "markdown" are only available in editors with markdown file).

Not sure what that means?

**Comment by JokerDan** [comment]
I think @mhchem is referring to what the document states here;

https://code.visualstudio.com/docs/extensionAPI/extension-points#_context-specific-visibility-of-command-palette-menu-items

Adding a 'when' clause to having a command show in the command palette.

**Comment by mhchem** [comment]
> Not sure what that means?

A1. Open a markdown file (or new file > Change Language Mode > markdown)
A2. press Ctrl+Shift+P
A3 type: markdown
A4. you will see **5** commands listed

B1. Open a new file (plaintext)
B2. press Ctrl+Shift+P
B3 type: markdown
B4. you will see **1** commands listed

That means, 4 of these commands are only available when the language mode is markdown.
I want to have the same thing, the commands of my extension should only be available for a specific language mode.

**Comment by mhchem** [comment]
@JokerDan Ah, now I understood the concept! Thanks!

So this changes this issue into a suggestion to improve the documentation.
I would suggest an additional sentence in the `contributes.commands` section.

> When registering commands this way, they will automatically be shown in the Command Palette (`Ctrl+Shift+P`). For more control over when they appear there or to add them to other menus, use `contributes.menus`.

**Comment by mhchem** [comment]
So, was the documentation improved?
