### ISSUE TITLE
Problem with copy/paste on Windows

### ISSUE THREAD

**Issue by glauberfc** [Microsoft/vscode#45965]
If I copy something to clipboard, press shift + delete and I try to paste from clipboard, VScode will not pastes the thing copied.

- VSCode Version: 1.21.0
- OS Version: Windows 10

Steps to Reproduce:

1. Copy any line of code to clipboard.
2. Press shift + delete;
3. Try past from clipboard.

Does this issue occur when all extensions are disabled?: Yes

**Comment by pchug** [comment]
I am experiencing this same issue on MacOS.

- `Version 1.21.0`
- OS version: Sierra `10.12.6`

Observed behaviour:
- Keyboard shortcuts do not work
- Copy/paste from Edit menu doesn't work


🤔 This issue happens quite frequently with VSCode... why is there no test for this?

**Comment by mcrapts** [comment]
For me copy/paste also has been broken. Tried disabling extensions, didn't do anything. Version: 1.21.1, OS: Windows 10.

**Comment by mcrapts** [comment]
I resolved this issue by deleting my .vscode/extensions folder and reinstalling my extensions.

**Comment by glauberfc** [comment]
This don't work for me.

**Comment by alexandrudima** [comment]
@glauberfc

On Windows, Shift+Delete is another keybinding for cut. So Shift+Delete writes to the clipboard!

![kapture 2018-03-28 at 23 40 05](https://user-images.githubusercontent.com/5047891/38057949-66b6df1e-32e1-11e8-9c6b-454c0a9dca28.gif)

If you do not like that running cut and having no selection writes to the clipboard, you can turn it off via 
```js
 // Controls whether copying without a selection copies the current line.
  "editor.emptySelectionClipboard": true
```

So, AFAICT, this all works fine...

**Comment by mayeranalytics** [comment]
Same here, suddenly paste is broken. 
Is this the same as  [#13366](https://github.com/Microsoft/vscode/issues/13366)?

**Comment by glauberfc** [comment]
@alexandrudima sorry for the delay in give you a feedback, but `"editor.emptySelectionClipboard"` didn't work for me. VSCode continues to copying the element that I had deleted with `shift + del`.

**Comment by alexandrudima** [comment]
@glauberfc Sorry, I don't understand your issue.

Here are the complete steps I am doing:
1. I copy a line 
2. I use Shift+Delete on a different line 
3. I paste; I get the line placed in the clipboard at step 2.

This is expected behaviour! Please let me know what you think the problem is.

![kapture 2018-04-09 at 15 37 24](https://user-images.githubusercontent.com/5047891/38500912-fd795dcc-3c0b-11e8-91fd-b9b74a493df7.gif)

**Comment by glauberfc** [comment]
Sorry, @alexandrudima, only now I understood that the function of `shift + delete` is delete the line and make a copy to the clipboard, but if I want only delete the line without make a copy I should use `ctrl + shift + k`. I did't know this shortcut.

Thanks by help me.
