### ISSUE TITLE
[typescript] folding regions for multi-line comments

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#45975]
It would if great if typescript would provide folding ranges for
- multiline comments (`/* ... */)
- sequent, full-line, single line comment

see https://github.com/Microsoft/vscode/blob/1cec53cedd4cbab9f528c788b4cd79e9990991f3/extensions/html/server/src/test/folding.test.ts#L178
as an example

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/22732 to track this upstream
