### ISSUE TITLE
Seek for Text marks strange points in Code

### ISSUE THREAD

**Issue by Raydir** [Microsoft/vscode#45986]
![grafik](https://user-images.githubusercontent.com/17499573/37528160-2e291d26-2934-11e8-9f62-1009f594086e.png)

- VSCode Version: 1.22.0-insider
- OS Version: Windows 10

Steps to Reproduce:
1. Seek for a string
2. check "other" markers that are found
3. change the text of one of the found positions
4. seek the SAME text as in step 1

The "last position" of the seeked String is also colored...?
Seems to be a bug... Could be a feature?

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
FYI @tsalinger most of these search issues coming in can go to @rebornix since he's been working on that lately

**Comment by rebornix** [comment]
This issue was fixed already. Feel free to reopen if you run into it again.
