### ISSUE TITLE
Add feature to open documentation panels in new tab or window

### ISSUE THREAD

**Issue by reyou** [Microsoft/vscode#45982]
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Install ms-python.python extension and correlated add-on plugins.
https://marketplace.visualstudio.com/items?itemName=ms-python.python
2. Mouse-over any framework method, and see the documentation panel. Even if this panel gives pretty useful information, there is no way to navigate from here to online resources (python.org) in new default browser window, or I cannot drag & drop it somewhere where I can partially copy / paste pieces of it.

This feature comes in [PyCharm](https://www.jetbrains.com/pycharm/) with Ctrl+Q button bound to it, and it would be great to have in VS Code, not only for Python, for all other languages supported.

Please see screen shot below:

![image](https://user-images.githubusercontent.com/6571483/37526232-33048a6c-2905-11e8-9ecb-a45246c341b5.png)

This is how it looks like in PyCharm, and pretty easy to read through, without loosing window in case of mouse-out event etc.

![image](https://user-images.githubusercontent.com/6571483/37526722-84efae0a-2906-11e8-9052-bf78ffb33b8f.png)

**Comment by joaomoreno** [comment]
This is already supported in the API although not with that extra UI.

A hover message is a `MarkedString`, which suports [`MarkdownString`](https://github.com/Microsoft/vscode/blob/634d73f9de07884f6dc2b3d3fd4a8c74f17231c5/src/vs/vscode.d.ts#L2142). This allows you to have links in the docs which execute commands, which can open editors.

https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namemarkdownstringaspan-classcodeitem-id614markdownstringspan
