### ISSUE TITLE
An extension's default plain object setting is displayed as [object Object]

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#45987]
Plain objects are not properly converted to strings:

<img width="1105" alt="screen shot 2018-03-16 at 16 39 28" src="https://user-images.githubusercontent.com/1812093/37530006-dc9f84d6-2938-11e8-8797-e587eb25b87a.png">

Instead I think we should detect plain objects and convert them to strings with something like `JSON.stringify ( obj, undefined, 2 )`

**Comment by sandy081** [comment]
Duplicate of #23627
