### ISSUE TITLE
[folding] add language aware folding to LSP

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#45983]
Publish the LSP interfaces for the language aware folding in either `vscode-languageserver-protocol` or a separate node module

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1501

**Comment by gregvanl** [comment]
Oops, moved wrong vscode-docs issue. Apologies.

**Comment by aeschli** [comment]
Created a node module https://www.npmjs.com/package/vscode-languageserver-protocol-foldingprovider

**Comment by aeschli** [comment]
Verified as it is used in the product.
