### ISSUE TITLE
[folding] finish language-aware folding

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#45981]
Finish the work on the HTML and JSON folding providers:
- handle cancellation
- limit the number of ranges transmitted
- support multi-line comments
- stable ranges while editing

Investigate:
- custom folding decorations (...) (for #31966)

**Comment by DanTup** [comment]
@aeschli I noticed this is in the release notes for March but currently only a proposed API - is this planned to ship as a stable API in this release? (If so, will it be moved to vscode.d.ts in advance? dev is simpler when things aren't proposed 😁)

**Comment by aeschli** [comment]
Yes, this is planned to go to vscode.d.ts once we have enough confidence and reviews.

**Comment by DanTup** [comment]
@aeschli I'm slightly confused - the top of the release notes say there's language-aware folding, but further down it says the API is proposed. It's unclear whether I can actually implement and ship this yet?

**Comment by DanTup** [comment]
> These are the built-in extensions from VSCode

Ah, didn't realise they could use them, all makes sense now!

I was trying to figure out if I could put them in my release towards the end of the month but I guess it'll need to wait. If I get chance after completing the stuff for this release I'll wire this up on a branch and ensure it all works for us. Thanks!
