### ISSUE TITLE
colorpicker opacity bar not working

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#45999]
original css:
.header {
   height: 95vh;
   background-image: linear-gradient(to right, 
   #7ed56f, #26af82),
      url(../img/hero.jpg);
   background-size: cover;
   background-position: top;
}

1) Placing mouse over color #73ed56 correctly shows scrollbar
2) Scrolling down no longer changes  hex to rgba and does not change opacity.
3) Instead it changes the hexcolor like using the first scrollbar on the left

**Comment by rebornix** [comment]
![color-picker](https://user-images.githubusercontent.com/876920/45313599-359fac00-b4e4-11e8-99dc-55da66da622f.gif)

No longer see this issue in latest version, close it for now but we can always reopen the issue if it shows up again.
