### ISSUE TITLE
Changing indentation character moves cursor on line

### ISSUE THREAD

**Issue by calebsander** [Microsoft/vscode#45996]
Issue Type: <b>Bug</b>

When changing between tabs and spaces, the cursor remains at the same character position on the line rather than the same column position. For example, if you have the line `\tabc` and your cursor is between `b` and `c`, converting indentation to 2 spaces moves the cursor to between `a` and `b`, since the indentation takes 2 characters instead of 1. Converting back moves the cursor one character to the right. With larger tab sizes (e.g. 4 or 8), the distance moved is even more pronounced.

Steps to reproduce:
1. Create a new file
2. Set indentation to tabs with tab size of 4
3. Insert a tab character (so cursor is now at column 5)
4. Convert indentation to spaces
5. The cursor is now at column 2 instead of column 5 (although the column number in the bottom bar still says 5)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.87GB (8.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
latex-workshop|Jam|3.14.0
language-haskell|jus|2.4.0
java|red|0.21.0
code-spell-checker|str|1.6.5
ayu|tea|0.14.0

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
Still happening in 952b2a641da89a6c7bc28387474bc8afd47f0d2f on mac:

Before:

<img width="160" alt="screen shot 2018-03-29 at 12 15 35 pm" src="https://user-images.githubusercontent.com/2193314/38108835-f0547b8c-334a-11e8-8609-5d9817d0f3ef.png">

After:

<img width="156" alt="screen shot 2018-03-29 at 12 15 40 pm" src="https://user-images.githubusercontent.com/2193314/38108838-f1bc5dfa-334a-11e8-9a83-dd22a1d26081.png">

**Comment by alexandrudima** [comment]
The last case from @Tyriar is very much different than the initial case. In the last case, the cursor sits within the edited range.
