### ISSUE TITLE
MutableToken potentially leaks listeners

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45990]
It looks like [`MutableToken`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/cancellation.ts#L38) has an event emitter that you can subscribe to but it lacks a `dispose()` method to free that emitter.

**Comment by jrieken** [comment]
Fix find

**Comment by bpasero** [comment]
@jrieken found by thinking about what to do with my new [`CancellationTokenSource`](https://github.com/Microsoft/vscode/blob/ben/notification-progress-api/src/vs/workbench/api/node/extHostProgress.ts#L34) for notification progress. 

I am still not sure if I should call `CancellationTokenSource.dispose()` when the progress has finished because that seems to trigger [`cancel`](https://github.com/Microsoft/vscode/blob/ben/notification-progress-api/src/vs/base/common/cancellation.ts#L81) and possibly event listeners in extensions. 

Is there a way for me to dispose my `CancellationTokenSource` without actually cancelling the token but still freeing resources?

**Comment by jrieken** [comment]
> not sure if I should call CancellationTokenSource.dispose() when the progress has finished because that seems to trigger cancel 

You shouldn't do that.

> Is there a way for me to dispose my CancellationTokenSource without actually cancelling the token but still freeing resources?

Yeah, `myTokenSource = null` shouldn't do it

**Comment by bpasero** [comment]
> Yeah, myTokenSource = null should do it

What if my extension does: `token.onCancellationRequested(() => ...)` and forgets to dispose the returned disposeable. If the token is never `canceled` nor `disposed`, the GC could never garbage collect the cancellation token as long as this listener is not disposed?

**Comment by jrieken** [comment]
Yeah, generally I would say should be safe to dispose the token source when the underlying operation has signalled completeness. In that situation the operation shouldn't listen on cancel anymore but it's fair to ask for dispose/cancel without cancellation.
