### ISSUE TITLE
Curly braces in string literal in function call causes wrong syntax highlinting 

### ISSUE THREAD

**Issue by vrabcak** [Microsoft/vscode#4599]
- VSCode Version: 0.10.11
- OS Version: Windows 7

Steps to Reproduce:

1. Enter function call `fn("{};");` anywhere in a C++ file
2. Syntax higlighting for the rest of the file gets confused - the string is not ended correctly

However string literal in an expression works fine, e.g. `a = "{}";`

![image](https://cloud.githubusercontent.com/assets/996834/13977709/9d06a9d2-f0cb-11e5-846f-d909eb02fffb.png)

**Comment by vchegwidden** [comment]
+1

- VSCode Version: 0.10.10
- OS Version: Windows 7 & OS X El Capitan

![capture](https://cloud.githubusercontent.com/assets/717457/13977917/9858af52-f0d5-11e5-902f-527ac43e18d4.PNG)

**Comment by aeschli** [comment]
This issue was moved to textmate/c.tmbundle#42

**Comment by aeschli** [comment]
Duplicate of #4769
