### ISSUE TITLE
Invalid workbench search entries for modified file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#45991]
Issue Type: <b>Bug</b>

1. Open `vscode.proposed.d.ts`
1. Do a workbench search for `createWebview`
1. Look at one result in `vscode.proposed.d.ts`
1. Now add some blank lines before the definition for `createWebview`. **Do not save the file**

**Bug**
Invalid entries start showing in the workbench search results

<img width="409" alt="screen shot 2018-03-16 at 9 21 55 am" src="https://user-images.githubusercontent.com/12821956/37532183-8a11e7be-28fb-11e8-8a26-dd108b224e9f.png">

VS Code version: Code - Insiders 1.22.0-insider (9160e85b1ab0333dfe697032f90da494f1f81fd4, 2018-03-16T06:10:31.571Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|11, 7, 4|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_22381911|
|Screen Reader|no|
|VM|20%|

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
Dumb bug that went out in yesterday's Insiders but is fixed in the version you have. However that string will be in your history for each window until you delete it.
