### ISSUE TITLE
Disabling telemetry before first run does not work

### ISSUE THREAD

**Issue by joliss** [Microsoft/vscode#46]
If I edit `product.json` as recommended in the [instructions for disabling telemetry on OS X](https://code.visualstudio.com/Docs/supporting/FAQ#_how-to-disable-telemetry-reporting) before running  VS Code for the first time, I get the following error message upon opening it:

<img width="420" alt="monosnap rpzk7" src="https://cloud.githubusercontent.com/assets/524783/11246186/83c9d7a2-8e0e-11e5-8123-37ec637a2793.png">

If I download VS Code, run it once, quit it, and *then* edit `product.json`, it works fine.

This is on OS X Yosemite 10.10.5.

**Comment by SofianHn** [comment]
Good catch! We [updated](https://code.visualstudio.com/Docs/supporting/FAQ#_how-to-disable-telemetry-reporting) the docs to mention this workaround. 

![screen shot 2015-11-18 at 10 03 13 am](https://cloud.githubusercontent.com/assets/2146228/11249442/a8d51ed6-8ddb-11e5-97ba-bb88b4cf7e20.png)

Another workaround is to change your security settings as described [here](https://support.apple.com/kb/PH18660?locale=en_US).
