### ISSUE TITLE
Blinking cursor

### ISSUE THREAD

**Issue by anothergituser** [Microsoft/vscode#460]
Any option to disable cursor blinking?
Also, how to increase the font size for the file explorer.

**Comment by egamma** [comment]
Please do not combine multiple issues into a single.

It is currently not supported to increase the font size of the file explorer, you can zoom in the entire workspace.

Cursor blinking is not supported.

**Comment by alexandrudima** [comment]
cursor blinking can now be disabled thanks to #500 from @Protectator 

@anothergituser Please create a new issue for the other half (font size of explorer) or use zoom in.
