### ISSUE TITLE
stdout of spawned child process is truncated or gone. Extension doesn't get the output of the command.

### ISSUE THREAD

**Issue by juanfe-google** [Microsoft/vscode#46002]
- VSCode Version:
Version 1.21.1 (1.21.1)
- OS Version:
OSX 10.13.3 (17D102)

The root of the issue is in nodeJS: https://github.com/nodejs/node/issues/6379

Steps to Reproduce:
1. Use child_process.spawn, or any other child process function in nodejs.
2. See the output of stdout in the extension.

Example:
`const proc = require('child_process').spawnSync('git', ['status']);
console.log(String(proc.stdout));`

**Comment by kenny-y** [comment]
Not sure this is gonna help or not: AFAIK, `console.log()` won't be able to write too much data in a short amount of time, and it's async (on pipes). Use `process.stdout.write()` and when it returns `false`, you'll have to wait on `drain` event before you can write more data.

**Comment by alexandrudima** [comment]
@juanfe-google 

We are using `spawn` and `exec` in our own built-in git extension like [here](https://github.com/Microsoft/vscode/blob/dcc822dac11fa3fe3720739bfff703e6c15ad5fc/extensions/git/src/git.ts#L77) or [here](https://github.com/Microsoft/vscode/blob/dcc822dac11fa3fe3720739bfff703e6c15ad5fc/extensions/git/src/git.ts#L86) and AFAIK that works fine for us.

So perhaps it is a problem with `spawnSync` ? (which is a horrible variant to use, as it blocks the entire EH process)

**Comment by juanfe-google** [comment]
@alexandrudima In the tool I'm working on uses spawn instead of spawnSync (which was chosen to simplify the example).

The issue is specific to nodeJS running on OSX. https://github.com/nodejs/node/issues/2360

**Comment by alexandrudima** [comment]
ping @joaomoreno 

Is there some magic sauce you're using when spawning git such that you always get the entire output?

**Comment by joaomoreno** [comment]
No, not really... Just regular old spawn.

**Comment by alexandrudima** [comment]
@juanfe-google I cannot reproduce the problem you are describing. I'm using an extension with the following contents:

* `package.json`
```json
{
    "publisher": "alex",
    "name": "46002",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}

```

* `index.js`
```js
const cp = require('child_process');
const vscode = require('vscode');

const proc = cp.spawnSync('git', ['status'], {
    cwd: vscode.workspace.rootPath
});
console.log(String(proc.stdout));
```

And I see the entire output of `git status` in the console.

**Comment by juanfe-google** [comment]
@alexandrudima what Mac OS X version are you running?

**Comment by alexandrudima** [comment]
I am using macOS High Sierra, Version 10.13.4. Would this be something that reproduces only on certain macOS versions?
