### ISSUE TITLE
Attributes with all numbers and starting with zeros show with zeros truncated in the console

### ISSUE THREAD

**Issue by rohitsud** [Microsoft/vscode#46004]
- VSCode Version: 1.21.0
- OS Version: Mac OS X

Steps to Reproduce:

1. In the debug console type the following
2. var r = {}
s = "007"
r[s] = 1
r

Expected

Object {007: 1}

Actual

Object {7: 1}

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by isidorn** [comment]
This data is coming for the debug adapter, forwarding to @roblourens and @weinand

**Comment by weinand** [comment]
This is a problem when using the "legacy" protocol:
![2018-03-19_10-28-23](https://user-images.githubusercontent.com/1898161/37587672-499319c6-2b60-11e8-8312-d486bfa0640c.png)

It works fine with "inspector" protocol:
![2018-03-19_10-25-02](https://user-images.githubusercontent.com/1898161/37587693-51d8c630-2b60-11e8-989d-14c0637abad6.png)


Either use a node.js version >= 8.0 or add a `"protocol": "inspector"` to your launch config.
