### ISSUE TITLE
VSCode's Git UI caused uncommitted changes

### ISSUE THREAD

**Issue by patrickklima** [Microsoft/vscode#46007]
Same OS info as [this issue](https://github.com/Microsoft/vscode/issues/45248). The observed behavior might be related as well. 
VS Code Info
VS Code version: Code 1.20.1 (f88bbf9, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

System Info
Item	Value
CPUs	Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2494)
Memory (System)	7.82GB (1.96GB free)
Process Argv	C:\Program Files\Microsoft VS Code\Code.exe
Screen Reader	no
VM	0%
Extensions (16)
Extension	Author (truncated)	Version
npm-intellisense	chr	1.3.0
path-intellisense	chr	1.4.2
vscode-eslint	dba	1.4.7
es7-react-js-snippets	dsz	1.3.3
vscode-npm-script	eg2	0.3.3
auto-close-tag	for	0.5.6
search-node-modules	jas	1.3.0
react-vscode-extension-pack	jaw	0.1.1
theme-karyfoundation-themes	kar	17.0.0
vscode-github	Kni	0.27.1
vscode-exec-node	mir	0.5.0
vscode-cosmosdb	ms-	0.5.0
azure-account	ms-	0.3.1
debugger-for-chrome	msj	4.1.0
JavaScriptSnippets	xab	1.5.0
ReactSnippets	xab	1.7.0
(7 theme extensions excluded)

Steps to Reproduce:

1. clone [this repo](https://github.com/AnnAllan/FantasyBitcoin/)
2. enter the following bash commands: 
- git status (confirm there are no uncommitted changes)
- git checkout -b origin/pdk/coin-index
- git status (confirm there are no uncommitted changes)
- git checkout -b origin/pdk/master
- git status (once again, confirm there are no uncommitted changes)
3. Repeat the branch-switching operations above ^ using the VSCode Git UI. (in the bottom-left corner, use the UI link to switch branches).
4. Observe there are uncommitted changes created by switching branches. 

Does this issue occur when all extensions are disabled?: Don't know

**Comment by joaomoreno** [comment]
What are the uncommitted changes? When you click them, what comes up? Is your repository in some network share, special folder?

Please try running Code with `code --disable-extensions` in order to disable all extensions. Does the issue still reproduce?
