### ISSUE TITLE
API to access terminal content

### ISSUE THREAD

**Issue by zikalino** [Microsoft/vscode#46008]
It would be extremely useful to access output from the terminal / receive appropriate events.
Currently it's only possible to send something to the terminal, but no way to read output from issued commands.

I wonder if this is perhaps against some Vscode rules, but i think it would be extremely useful.

If it's ok to add such functionality i can assign this issue / feature request to myself and submit pr.

**Comment by Tyriar** [comment]
This is covered in https://github.com/Microsoft/vscode/issues/13337, feel free to join the discussion over there.
