### ISSUE TITLE
Debugger on MacOS touchbar doesn't show all keys.

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#46005]
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T10:54:22.798Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

This is what debugger button bar looks like. All actions are possible and they work fine on UI.

![image](https://user-images.githubusercontent.com/1018196/37544491-6254cdc8-2922-11e8-9bec-647dab4383fc.png)

Touch bar shows only first action, the rest seem cut off. 

This happens fairly often. Play changes into pause but rest of actions are not shown on touch bar.  Or esc would get cut off.

 
![image](https://user-images.githubusercontent.com/1018196/37548079-b873221c-2932-11e8-8a96-16fce810a9e7.png)

**Comment by bpasero** [comment]
There was no change in code in this area for a while and it looks very much like an upstream issue to me (we would not be able to cause that issue through a programming error, I am quite sure).

**Comment by bpasero** [comment]
@nojvek I assume it looks fine when you try with [touchbar simulator](https://github.com/sindresorhus/touch-bar-simulator)?

**Comment by nojvek** [comment]
yeah touchbar simulator was fine. In fact with touch bar simulator on, I couldn't even repro the problem. May the touch bar simulator is somehow making a force refresh of the touch bar UI or something not sure.

@bpasero  Is there a way to tell touch bar to re-draw once debugger state changes ?

**Comment by bpasero** [comment]
@nojvek that is no API Electron provides as far as I know to redraw
