### ISSUE TITLE
Automatic Type Acquisition Error

### ISSUE THREAD

**Issue by emzero** [Microsoft/vscode#46000]
Issue Type: <b>Bug</b>

I've created a simple react starter using the following: https://github.com/egoist/create-poi-react-app

I'm trying to get ATA to work with react and other common used libraries but with no luck. I've searched some issues on this here and did the following based on the suggestions:

1) Set `"typescript.tsserver.log": "normal"` in settings
2) Restart VS Code
3) Run `TypeScript: Open TSServer log` and look in the numbered file. [Here](https://gist.github.com/emzero/e9f3b5066852964d49753f4948d921d0#file-ti-20432-log) are the contents of it.

This is the error logged there:
```
    Failed. stdout:
    
    stderr:
    npm ERR! code ETARGET
    npm ERR! notarget No matching version found for @types/builtin-modules@ts2.7
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Emiliano\AppData\Roaming\npm-cache\_logs\2018-03-16T20_24_52_262Z-debug.log
```
And the contents of that npm-cache log file are [here](https://gist.github.com/emzero/e9f3b5066852964d49753f4948d921d0#file-2018-03-16t20_24_52_262z-debug)

It seems it cannot find the types for `builtin-modules@ts2.7`. I know that aborting everything on error o avoid a dirty state is usually the best practice in software, but I don't think this applies here. I'd prefer to have at least some types installed if it cannot find one, rather than not having anything...

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3997)|
|Memory (System)|15.94GB (3.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Desktop\react\poi-cra|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
auto-close-tag|for|0.5.6
todo-tree|Gru|0.0.29
vscode-react-typescript|inf|1.0.13
dotenv|mik|1.0.1
azure-account|ms-|0.3.3
debugger-for-chrome|msj|4.2.1
syncing|non|1.5.3
vscode-icons|rob|7.21.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22693
