### ISSUE TITLE
Panel: overflow behavior for title bar actions

### ISSUE THREAD

**Issue by shivammittal99** [microsoft/vscode#46017]
Issue Type: <b>Bug</b>

1. Open an integrated terminal
2. Move terminal to right
3. Click restore panel size button
4. The Maximize panel, Move to Bottom and Close buttons become hidden without any indicator. If I click at edge of window, I am able to perform the Maximize panel action. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2800)|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (9.82GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
python|ms-|2018.2.1
cpptools|ms-|0.15.0
debugger-for-chrome|msj|4.2.1

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
@shivammittal99 can you provide a screenshot of what you mean? I'm guessing it's about the lack of a proper overflow menu for panel actions.

**Comment by isidorn** [comment]
Yes this is due to the fact that terminal panel has lot of actions and we do not have nice action overflow behavior. Renaming and treating as a feature request. Since showing those actions with an overflow is the only solution

**Comment by mengesb** [comment]
Oh man; I even tried uninstalling and re-installing the terminal extension and I still can't get it to move back. How do we move it back in the meantime ?

**Comment by isidorn** [comment]
Right click in composite bar -> hide some panels you do not use -> should get space

**Comment by mengesb** [comment]
heh, in other words I'm stuck unless I uninstall vscode? or will that even solve it?

**Comment by isidorn** [comment]
![help](https://user-images.githubusercontent.com/1926584/43419536-6db3bcd0-9441-11e8-937d-4093ba6c7752.gif)

**Comment by mengesb** [comment]
Hiding isn't my issue - i'm unable to move it back to the bottom is my issue - which forwards to this. Looks like the only way to get that back is to wait until it's patched

**Comment by mengesb** [comment]
OK found it; it wasn't re-drawing right.

**Comment by aaronortiz** [comment]
The only think that worked for me is dragging the little ">" button from the right panel back to the bottom panel, next to one of the other tabs. A little line hover, showed me that it working?
