### ISSUE TITLE
[ts lint] unable to find module references in TS project.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4601]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:

1. Create "Started Node.js Express3" Type script project from Visual studio and build it.
2. Launch VS code and open the same folder to get node.js TS project.
3. Verify app.ts, express.d.ts and other files under script folder.

Actual: TS lint is highlighted red with message "Cannot find the module".
Expected: TS lint should find the references of modules and  should not flag red and green.

![image](https://cloud.githubusercontent.com/assets/17735796/13979299/b7f1c060-f094-11e5-9153-d76349766e7f.png)

![image](https://cloud.githubusercontent.com/assets/17735796/13979309/cd7e5614-f094-11e5-82ad-8e1d6d357e5b.png)

Note: I tied with C# class library project and reference to the function from one namespace to other under different projects are working fine and no error message.

**Comment by jrieken** [comment]
@v-pavanp Is this the tslint extension or the typescript tools that are bundled with vs code? please attach the reading of the diagnostics message

**Comment by v-pavanp** [comment]
It is TS: Under app.ts.

![image](https://cloud.githubusercontent.com/assets/17735796/13979863/792c7380-f098-11e5-9845-e0cde0df44d3.png)

Also tslint is showing message like below under: express.d.ts

![image](https://cloud.githubusercontent.com/assets/17735796/13979911/bcd93302-f098-11e5-8b32-991364c0366a.png)

**Comment by jrieken** [comment]
@v-pavanp Please not that `tslint` and `ts` are different project and that it would be helpful if you file your bugs accordingly (https://github.com/Microsoft/vscode-tslint,https://github.com/Microsoft/vscode)

**Comment by egamma** [comment]
The module reference error do not come from tslint, tslint only reports warnings.

**Comment by v-pavanp** [comment]
I am closing this issue as I realized that I didn't add the reference in .ts file for external modules.

/// <reference path="Scripts/typings/node/node.d.ts" />
/// <reference path="Scripts/typings/stylus/stylus.d.ts" />
/// <reference path="Scripts/typings/express/express.d.ts" />

After adding above references there is no error in my .ts file.
