### ISSUE TITLE
Compulsory restarting the app if I want to load all referenced libraries completely after creating a new file.

### ISSUE THREAD

**Issue by khiemnd777** [Microsoft/vscode#46016]
Issue Type: <b>Bug</b>

In while creating a new file, then all referenced libraries will be not loaded completely, so I must be compulsory restarting the app.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.25GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/kandy/Projects/TheEngineer/Source -r -g /Users/kandy/Projects/TheEngineer/Source/Assets/Scripts/Blocks/BlockBehaviour/Entities/EntityAnd.cs:1|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-tools|Tob|0.1.9
unity-debug|Uni|1.3.0
vscode-togglecodelens|cml|1.0.3
code-runner|for|0.9.2
MagicPython|mag|1.0.12
csharp|ms-|1.14.0
mono-debug|ms-|0.15.8
vs-keybindings|ms-|0.2.0
python|tht|0.2.3

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
What language are you using? You probably need to file this against the language extension.

**Comment by khiemnd777** [comment]
I use vscode with Unity.
When any c# files added into, VScode can't detect the involved libraries immediately. I must compulsory restarting, then it worked normally.
Therefore, I need a confirmation where did this issue come from?
Thanks.

**Comment by dbaeumer** [comment]
Can you please report the issue against the C# extension here: https://github.com/OmniSharp/omnisharp-vscode They own the C# support.

Thanks.
