### ISSUE TITLE
Debug Dropdown: New items added can have hover select disabled

### ISSUE THREAD

**Issue by elucidsoft** [Microsoft/vscode#46011]
- VSCode Version: 1.21.0
- OS Version: Windows 10 Redstone 4 180302

Steps to Reproduce:

1. In launch.json create a configuration type:

` {
      "type": "node",
      "request": "launch",
      "name": "Stuff",
      "program": "${workspaceFolder}\\Stuff\\run.js"
    },`

2. Click Save
3. Observe correct behavior in drop down where you can select that item.
4. Add the exact same item (change only the program path, leave name the same) as a second configuration. 
` {
      "type": "node",
      "request": "launch",
      "name": "Stuff",
      "program": "${workspaceFolder}\\Stuff2\\run.js"
    },`
5. Observe your new item missing in drop down because you used same name.
6. Correct same name, by changing "Stuff" to "Stuff2"
` {
      "type": "node",
      "request": "launch",
      "name": "Stuff2",
      "program": "${workspaceFolder}\\Stuff2\\run.js"
    },`
7. Observe your new config shows up but you can not select it. (Hover over does not highlight item, clicking does not select item)
8. Restart VSCode
9. Observe correct behavior.

Does this issue occur when all extensions are disabled?: Yes

**Comment by cleidigh** [comment]
@isidorn 
working on this.  fairly certain it's related to  terminal disposal and issue #43475 
drop-down options get updated before the instance count is changed.  non- atomic from select box view.  It would be very helpful for your review once I have something finalized , I think the order of execution is very critical here.

**Comment by isidorn** [comment]
@cleidigh thanks for looking into this.
We can verify if that is the same issue by @elucidsoft opening F1 > developer tools and checking the debug console for potential errors.

**Comment by cleidigh** [comment]
@elucidsoft 
I was able to partially reproduce your issue.  While I did not have a problem with two debug configurations with the same name, I did see the hover issue.  It it appears that you can still select the item with the keyboard so it's actually probably a misplaced disable class within the CSS.  It is also still possibly related to another index problem with a twist on the results.  StayTuned.

![image](https://user-images.githubusercontent.com/25272315/37635351-7e105f58-2bd1-11e8-9b7c-87146c541900.png)

**Comment by elucidsoft** [comment]
One thing I left out that I should have mentioned is I also have
configurations spanning mutiple workspaces. This issue was in a single
workspace, however I have multiple configs which it merges together.

**Comment by cleidigh** [comment]
@elucidsoft 
cc:  @isidorn 
I can reproduce this in several ways.  It appears to be an odd "sticky" class label within the list.  I have a fix , I would consider the work around.  I will commit tomorrow with comments to at least avoid the problem for now.  @elucidsoft  do you use insiders to check after I merge?

**Comment by elucidsoft** [comment]
I do not currently, but I can, I'll check it after the merge and let you
know.

**Comment by cleidigh** [comment]
@elucidsoft 
Merged into master.  Should be a next insiders.
I am not closing this issue as I still think this is a workaround.
