### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Abhinickz** [Microsoft/vscode#46019]
Issue Type: <b>Bug</b>

1. Open VSCode and after 2-5 seconds, This Error Message appears:
"Extension host terminated unexpectedly".
2. Even when try to run this without any extension or reinstall VSCode.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz (4 x 2694)|
|Memory (System)|7.91GB (2.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.1
perl-html-template|bia|1.1.5
beautify|Hoo|1.3.0
Go|luk|0.6.77
perl-debug|mor|0.4.1
python|ms-|2018.2.1
cpptools|ms-|0.15.0
perlcritic|sfo|0.1.0
vscode-wakatime|Wak|1.1.24

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
Can you reproduce this if you disable all extensions?
My guess is that some extension is misbehaving, and by enabling/  disabling them you can find out which one and file a bug against that extension repository

**Comment by Abhinickz** [comment]
I Checked again with provided information and Wakatime is misbehaving producing this error.
