### ISSUE TITLE
Same table markdown code in VSCode preview and Github renders differently.

### ISSUE THREAD

**Issue by liamse** [Microsoft/vscode#46023]
- VSCode Version: 1.21
- OS Version: `Mac Os Sierra  10.12.6`, and `Windows 7`

Steps to Reproduce:

1. If you write this:
```
|Name| Type|
|:-----:|:---------:|
|`attribute`| `{Boolean \|\| String}`|
```
in VSCode preview you see something like this:

|Name| Type|
|:-----:|:---------:|
|`attribute`| `{Boolean \\|\\| String}`|

But Github shows you:

|Name| Type|
|:-----:|:---------:|
|`attribute`| `{Boolean \|\| String}`|

2. If you write this:
```
|Name| Type|
|:-----:|:---------:|
|`attribute`| `{Boolean || String}`|
```
in VSCode preview you see this:

|Name| Type|
|:-----:|:---------:|
|`attribute`| `{Boolean \|\| String}`|

But Github render this:

|Name| Type|
|:-----:|:---------:|
|`attribute`| `{Boolean || String}`|

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I think this is a bug on the github side actually. They render:

`{Boolean \|\| String}`

as

![screen shot 2018-03-19 at 10 53 24 am](https://user-images.githubusercontent.com/12821956/37612910-c485827e-2b63-11e8-863f-cc9edbc23f3b.png)

The rendering of the inline code in these two cases (normal and inside table cell) should not be any different

For reference, we use [markdown-it](https://github.com/markdown-it/markdown-it) for the markdown preview

**Comment by liamse** [comment]
Github use [Markdown](https://daringfireball.net/projects/markdown/) that always escape pipe char even it is in backticks (`).
e.g. in Github two following example escape pipe chars:
```
|Name| Type|
|:---:|:----:|
|`attribute`| {Boolean \|\| String}|

|Name| Type|
|:---:|:----:|
|`attribute`| `{Boolean \|\| String}`|

```
In other hand, VSCode or [markdown-it](https://github.com/markdown-it/markdown-it) renders as following, first without backticks:
```
|Name| Type|
|:---:|:----:|
|`attribute`| {Boolean \|\| String}|
``` 
render as 

|Name| Type|
|:---:|:----:|
|`attribute`| {Boolean \|\| String}|

And with backticks: 

```
|Name| Type|
|:---:|:----:|
|`attribute`| `{Boolean \|\| String}`|
```
render without escaping:

|Name| Type|
|:---:|:----:|
|`attribute`| `{Boolean \\|\\| String}`|

This is completely fine, but after push your markdown to github, you need to check it one more time.
