### ISSUE TITLE
Font rendering looks weired on Linux

### ISSUE THREAD

**Issue by mrv90** [Microsoft/vscode#46021]
Issue Type: <b>Bug</b>

Font rendering is too bad ! It's so difficult and weired to read titles and text of vs code !

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.6.0-kali1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3240 @ 3.10GHz (2 x 3100)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (2.53GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by tsalinger** [comment]
duplicates #46022
