### ISSUE TITLE
Add theme coloring option for border that splits windows and explorer

### ISSUE THREAD

**Issue by valleybay** [Microsoft/vscode#46020]
- VSCode Version: Version 1.21.0 (1.21.0)
- OS Version: High Sierra

The grey border separating the split between windows, and the grey border between the explorer and mainview should have a theming option. I would like to remove these borders completely.

![image](https://user-images.githubusercontent.com/10939013/37554846-bfe9ef4c-29de-11e8-900e-a565f5239a75.png)
![image](https://user-images.githubusercontent.com/10939013/37554848-c58d3648-29de-11e8-8ba7-10e3c9fbb841.png)

**Comment by bpasero** [comment]
That would be `"sideBar.border"` and `"editorGroup.border"`

**Comment by valleybay** [comment]
I already use those, and those do not change it at. There's a second border. In the attached screenshots, I have highlighted these by making them dark, to the left you will see that border remains.

![image](https://user-images.githubusercontent.com/10939013/37555096-82bcc974-29e2-11e8-90df-18ad57974194.png)
![image](https://user-images.githubusercontent.com/10939013/37555097-85fc9678-29e2-11e8-8c64-64bcf2e6e09a.png)

**Comment by valleybay** [comment]
@bpasero Please consider reopening this.

**Comment by bpasero** [comment]
@valleybay whats your color config looking like?

**Comment by valleybay** [comment]
```"workbench.colorTheme": "One Dark Pro Vivid",
"workbench.colorCustomizations": {
  "scrollbar.shadow": "#282C34",
  "editorGroup.border": "#282C34",
  "sideBar.border": "#282C34"
}```

**Comment by bpasero** [comment]
@valleybay there is neither a border for the sidebar for me nor between editors:

![image](https://user-images.githubusercontent.com/900690/37563223-40eb8fc2-2a7c-11e8-810e-380bc4459162.png)

**Comment by valleybay** [comment]
@bpasero It seems it might be an issue with the border of the scrollbars, because I hide my scrollbars:

```
"editor.scrollbar.vertical": "hidden",
"editor.scrollbar.verticalScrollbarSize": 1,
"editor.scrollbar.horizontal": "hidden",
"editor.scrollbar.horizontalScrollbarSize": 1,
```

**Comment by valleybay** [comment]
It seems that I have made a mistake here, keeping the verticalScrollbarSize: 1, when it should in fact be 0.

Thank you for your assistance @bpasero.
