### ISSUE TITLE
strange "%" mark in every line of integrated terminal

### ISSUE THREAD

**Issue by spyshow** [Microsoft/vscode#46036]
- VSCode Version: 1.21.1
- OS Version: windows 7 

hi all :

i am using zsh as my terminal ( i'm using windows 7) and it's working 
great but in vscode a strange "%" character appear before every line  as in picture ... any body know how to remove it ? 
![1](https://user-images.githubusercontent.com/188788/37559164-d8dc1ca0-2a29-11e8-8f4c-eb370d11a591.png)

**Comment by Tyriar** [comment]
What's your settings.json look like?

Does the same thing occur when using insiders? http://code.visualstudio.com/insiders
