### ISSUE TITLE
Breakpoints don't appear in editor even though they get hit on execution

### ISSUE THREAD

**Issue by ripras** [Microsoft/vscode#46035]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.13.0
vscode-standardjs|che|1.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-npm-script|eg2|0.3.3
flow-for-vscode|flo|0.7.3
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
debugger-for-chrome|msj|4.2.1
Ruby|reb|0.17.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|2.0.0

---

Steps to Reproduce:
Not sure. I rebooted my Mac and it started happening. I tried launching as 'code --disable-extensions' as per another bug logged on this issue, but that didn't fix things for me.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
First of all please update to latest vscode.
Second please try reproducing your issue with latest vscode insiders https://code.visualstudio.com/insiders/
In case you can reproduce with latest vscode insiders please let us know of the exact steps to reproduce your problem. Thank you
