### ISSUE TITLE
Terminal stops output after random number of characters

### ISSUE THREAD

**Issue by MJJBennett** [Microsoft/vscode#46037]
Issue Type: <b>Bug</b>

Simple piece of test code here:

```
#include <iostream>

int main() {
    for (int i = 0; i < 300; i++) {
        std::cout << i << std::endl;
    }
}
```

Output's failure may look like this:

```
1
2
3
[...]
40
41
4
```

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|Memory (System)|15.95GB (9.91GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions: Yes. Please note - I saw that a prior issue with this exact same problem had been closed because it was caused by extension(s) (Issue #43280); in order to avoid that, I uninstalled every extension I had installed, tested, and the issue persisted. (With no extensions showing up under @installed)

**Comment by MJJBennett** [comment]
It appears that this bug also occurs in CLion's integrated terminal, which leads me to believe it might be a bug with whatever system is used to create integrated terminals on Windows 10. Feel free to close this issue if this indicates it's not something that Visual Studio Code could fix.

**Comment by Tyriar** [comment]
I think this is the same root cause as https://github.com/Microsoft/vscode/issues/42847
