### ISSUE TITLE
Incorrect single line comment highlighting in jsx

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#46033]
Issue Type: <b>Bug</b>

For the jsx:

```js
const a = <button 
      // disabled={false}
    />
```

**Bug**

`//` comments are highlighted incorrectly:

<img width="123" alt="screen shot 2018-03-17 at 11 57 29 am" src="https://user-images.githubusercontent.com/212305/37558991-9010c01a-29da-11e8-9133-af2d9b1ec61a.png">

VS Code version: Code - Insiders 1.22.0-insider (9160e85b1ab0333dfe697032f90da494f1f81fd4, 2018-03-16T06:10:31.571Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Load (avg)|2, 2, 2|
|Memory (System)|40.00GB (11.07GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_421991|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#585

**Comment by peterschussheim** [comment]
When is this fix going to land in `insiders`?

**Comment by mjbvz** [comment]
@peterschussheim Are you still seeing this issue in the latest insiders?

![screen shot 2018-03-27 at 11 17 50 am](https://user-images.githubusercontent.com/12821956/37986507-7f988212-31b0-11e8-98c8-a0a1350cb259.png)

If so, please share some example code

**Comment by peterschussheim** [comment]
Hi Matt,

Yes, I am on `1.22.0-insider (1.22.0-insider)`.   Please have a look at the screen capture and let me know if you need more detail.

Demo: 
![gif](http://g.recordit.co/lZFFoES2mm.gif "screen capture")

**Comment by mjbvz** [comment]
Do you mean the comment style or the highlighting being broken after you comment the line?

**Comment by peterschussheim** [comment]
🤦‍♂️  My bad...yes I meant the comment style `{/*<Jsx></Jsx>*/}`.

I will look around for an existing bug report.

**Comment by mjbvz** [comment]
Yes using `//` is by-design when you are commenting the outermost tag of jsx. Within the tag itself, we should use  `{* ... *}`style comments
