### ISSUE TITLE
Intellisense stop working after run the command "dotnet new"

### ISSUE THREAD

**Issue by DiegoGFritz** [Microsoft/vscode#46039]
- VSCode Version: 1.21.1 (x64)
- OS Version: Microsoft Windows 10 Enterprise x64 version 1709 (OS build 16299.309)

Steps to Reproduce:

1. Create a workspace with many projects
2. Create a new folder in somewhere
3. Run the command "dotnet new classlib -n xxxx -o yyyyyy (use the folder created in item 2)
4. try to use intellisense

After restarting Visual Studio Code, intellisense works fine. The problem is in restarting each time the aforementioned command is executed

Thanks.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by tsalinger** [comment]
Does this problem only occur when you use the C# extension?
If so, please open an issue at their [repo](https://github.com/OmniSharp/omnisharp-vscode/issues).

**Comment by DiegoGFritz** [comment]
Okay. I only use C # as a programming language
Thank you very much for the reply.
