### ISSUE TITLE
"editor.suggestSelection": "recentlyUsed" should not pre-select when there is no prefix

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#46047]
I've seen this a few times, and it's been mentioned to be many more. See https://github.com/Dart-Code/Dart-Code/issues/703 for an example.

The default setting of `suggestSelection` is `recentlyUsed` and it seems to trigger without any prefix (even a leading `.`). This means if completion is invoked for the user to pick from a list, there's a seemingly random item selected by default:

![completion](https://user-images.githubusercontent.com/798935/37559882-63ddc86a-2a36-11e8-9e32-d5d065b9f42b.gif)

Here, the user is expecting completions on the named args (which are correctly at the top of the list) but code is pre-selecting the snippet further down that they previously used. I've seen this before where it was pre-selected class names here.

I think this behaviour should not trigger when there are zero characters matching and no characters immediately proceeding where completion was invoked (eg. a `.`, only indenting). If a user invokes completion with no prefix, it's very likely they're looking for a full list of items rather than the last thing they typed.

**Comment by DanTup** [comment]
@jrieken Which case do you consider this a dupe of? The one linked above is asking for an API for pre-selection, but this case is about the default behaviour (selecting something when the only prefixing text is whitespace).

**Comment by jrieken** [comment]
#43429

**Comment by DanTup** [comment]
> but there is plans to skip the memory when on an empty line

Perfect, I'll subscribe there. Thanks! :)
