### ISSUE TITLE
JS Code hints not smart

### ISSUE THREAD

**Issue by dagger9527** [Microsoft/vscode#46041]
Issue Type: <b>Bug</b>

The code is as follows :

var a
init()
function init() {
    a = document.createElement('canvas')
}
# Variable A is created in the method body, a has no code hint outside the method body

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|7.89GB (2.95GB free)|
|Process Argv|E:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|57%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
vscode-eslint|dba|1.4.7
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
beautify|Hoo|1.3.0
python|ms-|2018.2.1
debugger-for-chrome|msj|4.2.1
vscode-icons|rob|7.21.0
open-in-browser|tec|1.1.0
vim|vsc|0.11.2

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
You need to give `a` a type when you declare it:

```js
/** @type {HTMLCanvasElement} */
var a;
...
```
