### ISSUE TITLE
Delete forward lag (v1.21.1)

### ISSUE THREAD

**Issue by greg-wolff** [Microsoft/vscode#46045]
When using delete forward keyboard shortcuts, vscode freezes up completely, and hangs for a few seconds before performing the action. This wasn't a problem until one of the last few updates.

- VSCode Version: v1.21.1
- OS Version: MacOS High Sierra 10.13.3

*Note: I'm using a MacBook Pro 2017, so there is no 'delete' key, rather, holding `fn + backspace` simulates the delete key (which normally deletes characters in front of the cursor) on MacOS. And thus `fn + alt + backspace` deletes words in front of the cursor. For the rest of this issue, I will refer to the key as 'delete', because that's how it's printed on the MacBook keyboard.*

Steps to Reproduce:
1. Position cursor in front of a word
2. Use any `deleteRight` command shortcut such as `fn + alt + delete` (delete word forward or `executeCommand deleteWordRight`) or `fn + delete` (delete character forward or `executeCommand deleteRight`)

**EDIT: Additional Details**
For the 'delete word forward' shortcut (`fn + alt + delete`) holding `fn` before `alt` while performing the keyboard shortcut will produce the lag/hang, while holding `alt` before `fn` will not. For the 'delete character forward' shortcut (`fn + delete`) however, there's no way around the lag/hang.

Freeze checklist:
- [x] it reproduces with extensions disabled (code --disable-extensions from the command line - NOT the integrated terminal of Code)
- [x] it was not happening in the previous stable release
- [x] there is no suspicious output when running from the command line (code --verbose)
- [x] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- normal output as shown: `TRACE CommandService#executeCommand deleteWordRight`
- [x] it reproduces after deleting <appdata>/User/keybindings.json and <appdata>/User/settings.json
- [x] it reproduces when opening empty (code -n from the command line)
- [x] it reproduces opening any folder
- [x] it reproduces opening any file
- [x] it reproduces when only having a single window open
- [x] it reproduces from a workspace that is not under Git version control
- [x] it reproduces when running with GPU disabled (code --disable-gpu)
- [x] it reproduces when being offline
- [x] it reproduces when disabling the file watching (set files.watcherExclude to "**/**": true)

**Comment by greg-wolff** [comment]
Update: This also happens in another Electron app named [notion.so](http://notion.so), perhaps it's an issue with Electron rather than VS.

**Comment by alexandrudima** [comment]
Thank you for the detailed issue. I am sorry, but I cannot reproduce. I am trying on a MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) also on MacOS High Sierra 10.13.3

I am doing `fn`, then `alt`, then `delete`, as well as `fn`, then `delete`, but I am not experiencing any problems.

![kapture 2018-03-28 at 22 54 13](https://user-images.githubusercontent.com/5047891/38055791-fec92d72-32da-11e8-86a0-5f185959bac4.gif)

For me, when I press `fn`, the touchbar redraws and paints F keys. I wonder if that is somehow related, or if you can reproduce this with an external keyboard ?

**Comment by greg-wolff** [comment]
With an external keyboard, I only can do `delete` and `alt + delete` actions because I don't have an external keyboard with the `fn` key. I also use [BetterTouchTool](http://bettertouchtool.net/) to use trackpad gestures and some touchbar buttons, but even after completely disabling it, the lag still occurs.

**Comment by alexandrudima** [comment]
@greg-wolff You could always try with something like a guest account to try to rule out `BetterTouchTool`. Also, you could try if Chrome also suffers from this lagging (as Electron is based on Chromium)...

**Comment by greg-wolff** [comment]
You can see me reproducing the lag here. Interestly enough, when I use the accessibility keyboard to record my keystrokes, the lag will actually happen sporadically. When the accessibility keyboard is not on, it happens everytime.

https://giant.gfycat.com/AchingWebbedGoa.webm

The lag does not occur in Chrome.

**Comment by lupuselit** [comment]
I'm having the same problem with VS Code, it also lags on Atom, but all the other apps I've tested it doesn't happen anything.

**Comment by alexandrudima** [comment]
@lupuselit Can you please consider filing an issue against Electron at https://github.com/electron/electron
