### ISSUE TITLE
Network connections is banned when searching extensions after updated to 1.21.1

### ISSUE THREAD

**Issue by gemmi** [Microsoft/vscode#46052]
- VSCode Version: 1.21.1
- OS Version: win7

Steps to Reproduce:

1. update from 1.20 to 1.21.1 automatically by following vscode message
version info (in chinese):
版本 1.21.1
提交 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
日期 2018-03-14T14:46:47.128Z
Shell 1.7.9
渲染器 58.0.3029.110
Node 7.9.0
架构 x64
2. open extension menu and type any charactor into search dialog to search extensions and a error dialog popup from bottom right, in chinese "出现未知错误。有关详细信息，请参阅日志。" but cannot find logs as there is no link.
3. I didn't set proxy in user settings and i can search extensions well in vscode version 1.20 

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@gemmi Can you please provide logs (from console / output)

Console: Open dev tools 
Output: Open output panel and see window logs

**Comment by gemmi** [comment]
@sandy081 
i update from 20 to 21 again and find no ouput in ouput-panel , open dev tools and open "Header" tab to see that the request is blocked as "Provisional headers are shown" error

and console print as follows:

workbench.main.js:4810 
POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_PROXY_CONNECTION_FAILED

workbench.main.js:2207 出现未知错误。有关详细信息，请参阅日志。
e.onDidNotificationChange @ workbench.main.js:2207
(anonymous) @ workbench.main.js:2206
e.fire @ workbench.main.js:165
e.notify @ workbench.main.js:2199
e.error @ workbench.main.js:3004
(anonymous) @ workbench.main.js:3004
e.error @ workbench.main.js:3004
t.onError @ workbench.main.js:4623
(anonymous) @ workbench.main.js:4621
done @ workbench.main.js:150
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_chainedError @ workbench.main.js:149
n @ workbench.main.js:147
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_error @ workbench.main.js:149
(anonymous) @ workbench.main.js:184
done @ workbench.main.js:150
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_error @ workbench.main.js:149
a @ workbench.main.js:155
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_chainedError @ workbench.main.js:149
n @ workbench.main.js:147
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_error @ workbench.main.js:149
a @ workbench.main.js:155
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_chainedError @ workbench.main.js:149
n @ workbench.main.js:147
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_error @ workbench.main.js:149
(anonymous) @ workbench.main.js:183
done @ workbench.main.js:150
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_error @ workbench.main.js:149
l @ workbench.main.js:153
(anonymous) @ workbench.main.js:153
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_error @ workbench.main.js:149
a @ workbench.main.js:155
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_chainedError @ workbench.main.js:149
n @ workbench.main.js:147
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_error @ workbench.main.js:149
a @ workbench.main.js:155
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_chainedError @ workbench.main.js:149
n @ workbench.main.js:147
then @ workbench.main.js:150
enter @ workbench.main.js:147
_run @ workbench.main.js:150
_setCompleteValue @ workbench.main.js:149
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_chainedError @ workbench.main.js:149
n @ workbench.main.js:147
v @ workbench.main.js:145
enter @ workbench.main.js:148
_run @ workbench.main.js:150
_error @ workbench.main.js:149
t.xhrRequest.n.TPromise.t.onerror @ workbench.main.js:4809

**Comment by sandy081** [comment]
> workbench.main.js:4810
POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_PROXY_CONNECTION_FAILED

@joaomoreno Looks like a proxy issue.

**Comment by joaomoreno** [comment]
Not much more than https://code.visualstudio.com/docs/setup/network
