### ISSUE TITLE
Can't click buttons on new notifications with a touch screen

### ISSUE THREAD

**Issue by Juanmabs22** [Microsoft/vscode#46055]
Issue Type: <b>Bug</b>

Hello!
On the new notification system i cannot press any button with the touch screen, I have to use a mouse.

I have a Chuwi hi13 wi the last version of Windows 10 and last stable VS Code 64bits edition.

Thanks fot make this amazing tool better each day!

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU N3450 @ 1.10GHz (4 x 1094)|
|Memory (System)|3.40GB (0.30GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

---
Update: You can only close the notification 
![gif](https://media.giphy.com/media/dQuX8OBm6wMxNLqJ0U/giphy.gif)

**Comment by Juanmabs22** [comment]
Maybe this could fix:
[Add support to confirm messages shown at the top with the keyboard #5538 ](https://github.com/Microsoft/vscode/issues/5538)

**Comment by bpasero** [comment]
@isidorn can you give this https://github.com/Microsoft/vscode/commit/c4e45c4dc6cd0343d77141c2f734a5d945f2961f a quick look if I use the `Gesture` thing correctly? Interestingly the button in the empty explorer responds to touch even before that change, unclear to me why it does not work in the notifications though...

**Comment by isidorn** [comment]
@bpasero yes looks great. You first let the Gesture now that it should take your element into account for for forwarding touch events and then you listen on the event.
