### ISSUE TITLE
JavaScript Validation Misses Identifier Expected Error

### ISSUE THREAD

**Issue by Vitzkrieg** [Microsoft/vscode#46051]
Issue Type: <b>Bug</b>

There is no error indicated for the code below although it breaks in the browser. The comma needs to be removed or another variable declared.

	var targetIndex,
		target, ;

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|63.88GB (44.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Projects\2018\AMNA\FlashtoV5Conversion.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-npm-source|dku|1.0.0
vscode-npm-script|eg2|0.3.3
vscode-npm|fkn|3.3.0
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.3.0
docthis|joe|0.6.0
node-debug2|ms-|1.19.1
debugger-for-ios-web|msj|0.1.2
tsimporter|pmn|1.2.14
vscode-icons|rob|7.21.0
vscode-react-native|vsm|0.6.5
JavaScriptSnippets|xab|1.5.0
local-history|xyz|1.6.2

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22691
