### ISSUE TITLE
File no longer watched after being deleted and recreated

### ISSUE THREAD

**Issue by AndersZhang4** [Microsoft/vscode#46058]
Issue Type: <b>Bug</b>

After the open file is deleted, the other tools regenerate the same name file again, and do not automatically load the file, just show that the file is deleted. But Sublime can automatically load new files.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

Reproduces without extensions

**Comment by bpasero** [comment]
@AndersZhang4 can you share a screenshot or video what you mean?

**Comment by AndersZhang4** [comment]
config: "workbench.editor.closeOnFileDelete": false,
TestCase: 1. open a file "d:\a.txt"(a.txt is in existence). 2. then move "d:\a.txt" to "c:\a.txt", and edit  "c:\a.txt". 3.   then  move "c:\a.txt" to "d:\a.txt"。VSCode can't auto load a.txt, but Sublime-text can automatically load the file and can display the newest content.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28432
