### ISSUE TITLE
php validation not working when folder is open in explorer

### ISSUE THREAD

**Issue by dmxd5** [Microsoft/vscode#46054]
- VSCode Version: 1.21.1
- OS Version: Windows 10 Pro Build 16299.309

Does this issue occur when all extensions are disabled?: Yes

When I open a php file with errors in php syntax, it is validated correctly (example 1). However, when I have any folder opened in vscode explorer, the same php file is not being validated at all (example 2), so are not any files, even if they don't belong to the opened folder.

example 1:
![ex1](https://user-images.githubusercontent.com/10746393/37565485-00c9d516-2ab3-11e8-8956-348f62b3091c.PNG)

example 2:
![ex2](https://user-images.githubusercontent.com/10746393/37565474-c89527e0-2ab2-11e8-987c-2227d31a634d.PNG)

The php version 7.2.3 is located in my OS at `C:\php`

VSCode settings contain the following configuration related to php validation:

```
{
    "php.validate.executablePath": "c:/php/php.exe", 
    "php.validate.run": "onType",
}
```

**Comment by dmxd5** [comment]
This issue appears to be happening on the latest Windows 10, because I encountered it as soon as I downloaded and installed a fresh copy of Windows 10 on my desktop.

I've just tested VSCode (v1.21.1) php validation on my laptop with 4-month-old windows 10 Pro and it all worked fine. However, once I've downloaded and installed the latest version of Windows 10 Pro on this laptop today, and istanlled VSCode (v1.21.1) on the fresh installation, the same issue appeared - the php validation won't work when a folder is opened in vscode explorer.

**OS Name:** Windows 10 Pro
**Version:** 1709
**OS Build:** 16299.309

**Comment by roblourens** [comment]
This works for me, on Windows 10 Pro, basically the same build as you.

Could you open the developer tools (Help > Toggle Developer Tools) and check for errors?

Could you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by dmxd5** [comment]
VSCode insider edition php validation doesn't work either.

The issue seems to be occurring on the new installation of windows that is currently available for download via `MediaCreationTool.exe` at microsoft.com. When I try it on my laptop where Windows was installed four month ago, VSCode php validation works fine there, even though that Windows has the same build through updates.

Could you please try to download the new installation of Windows 10 (64-bit), install it on virtualbox, and test VSCode php validation with a folder opened.

I unpack the following php: **_VC15 x64 Non Thread Safe (2018-Mar-01 06:44:57)_** (https://windows.php.net/download/) to `C:\php`.

At VSCode install I check all "open with", "file association" options.

**Comment by roblourens** [comment]
I'll try it when I have time but I doubt that it's related to how windows was installed. The PHP validation is very simple and doesn't really do anything differently based on whether a folder is open or not. Do any of the PHP extensions like PHP Intellisense work for you instead?

Could you open the developer tools (Help > Toggle Developer Tools) and check for errors?

**Comment by dmxd5** [comment]
Yes, PHP Intellisense works. I'm not saying it is related to how windows was installed, I'm saying that it appears to be related to the copy of windows that is currently downloaded from microsoft.com

I had VSCode php validation working fine, then last week I installed a fresh copy of Windows, which I downloaded from microsoft.com, and after I installed vscode on the fresh windows, php validation wouldn't work when a folder was opened. Then I tried vscode on my laptop where I had installed windows about 4 moths ago, and vscode php valdiation works absolutely fine there. Then I downloaded windows again and installed two more copies Windows 10 Home and Windows 10 Pro on two virtual boxes, and on neither copies VSCode php validation works when a folder is opened. So I concluded that the problem occurs in the latest windows file that is downloaded from microsoft.com

**Comment by dmxd5** [comment]
I've tested numerous times - php validation does not work when folder is opened in vscode explorer. The issue occurs on the windows 10 (64-bit) that is currently up for download at microsoft.com

**Comment by roblourens** [comment]
If the PHP Intellisense extension works, can you use that as a workaround? It also provides validation, and does a better job of it than the very simple builtin PHP validation.

**Comment by dmxd5** [comment]
I'm not sure what you mean by using Intellisense as workaround.

**Comment by roblourens** [comment]
When the PHP Intellisense extension is installed, it also does validation (better than the builtin validation which is not working here)

**Comment by dmxd5** [comment]
Yes, PHP Intellisense extension php validation works. Thanks for the advice. I'd still like the issue to be verified and fixed in the future though.

**Comment by dmxd5** [comment]
Will the issue be fixed? I'm still encountering it, even on vscode 1.22. Have you been able to recreate it (see steps below)? Installing non-native PHP Intellisense is a workaround, not a fix.

1. Install brand new Windows 10 downloaded from microsoft.com.
2. Download php for windows and unpack to `c:\php`.
3. Install vscode.
4. Open folder in vscode explorer.
5. Create/open php file with a php syntax error in it.
6. See if the problem occurs: the syntaxt error will not be reported by VSCode if a folder is opened.

**Comment by roblourens** [comment]
Sorry for the delay, I had time to try it. I see similar behavior, did you install the VC++ redistributable? I install the same version of PHP as you (VC15 x64 Non Thread Safe) and it requires the VC15 redist and isn't totally functional until then. Sure enough, if I run PHP from the command line with the bad .php file, it doesn't output anything.

I think it works when a folder isn't open, because then it's spawned effectively with vscode's folder as CWD and it picks up the one next to Electron. But we can't depend on that.

**Comment by roblourens** [comment]
@aeschli I think it's resolved?

**Comment by aeschli** [comment]
oh, sorry, it seemed to me that it bot overeagerness.
