### ISSUE TITLE
MacOS Touch Bar Support

### ISSUE THREAD

**Issue by odonckers** [Microsoft/vscode#46059]
I'm an iOS Developer and a Web Developer, so I switch between Xcode and Visual Studio Code a lot. But the issue is, that I have gotten so used to having these three touch bar buttons on Xcode:
<img width="1085" alt="touch bar shot 2018-03-18 at 8 28 32 am" src="https://user-images.githubusercontent.com/11579289/37566419-dfc5e570-2a86-11e8-8603-a1a9d6740fb7.png">

The comment button and peek button are especially useful. Could this be feature in a future update for the MacOS version?

**Comment by bpasero** [comment]
@odonckers we do support that extensions provide commands for the touchbar (e.g. check out this [query](https://marketplace.visualstudio.com/search?term=touchbar&target=VSCode&category=All%20categories&sortBy=Relevance)). I suggest you look there.
