### ISSUE TITLE
selecting to the next word is unexpected

### ISSUE THREAD

**Issue by zhulika** [Microsoft/vscode#46050]
Issue Type: <b>Bug</b>

Navigating using the keyboard is inconsistent with other Microsoft applications, and all other editors that I use, including the browser that I'm using right now. I'm not sure if this is a deliberate change but it is unexpected and makes the Visual Code editor rather distracting to use.

For example, ``Ctrl-Right`` in Visual Code jumps to the end of the current word, whereas in every other editor that I use, it will jump to the start of the next word. So, to delete the current word in VSCode, I must do something like type ``Ctrl-Right`` twice, followed by one ``Ctrl-Left`` followed by ``Delete``.

Please make it consistent with all other Microsoft applications and, from my possibly limited experience, every other text editor out there. :)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by alexandrudima** [comment]
Please use issue search

https://github.com/Microsoft/vscode/issues/41620
https://github.com/Microsoft/vscode/issues/3577
https://github.com/Microsoft/vscode/issues/35366
https://github.com/Microsoft/vscode/issues/34457
https://github.com/Microsoft/vscode/issues/31910

**Comment by zhulika** [comment]
Dear Alexandru,

Thank you for your email. I did search a couple of times but the possible queries are too many and I don’t have time to spend fixing bugs in your stuff – there are too many bugs in my own code!

If you fix the problems more quickly, you’re going to get fewer people sending you duplicate reports.

Yours,

Dan

**Comment by alexandrudima** [comment]
Hi Dan,

Please, in the future, ask questions on StackOverflow. Word navigation behaving differently than Notepad or Visual Studio is not a bug, it is an intentional choice.

All the best,
Alex

**Comment by zhulika** [comment]
Dear Alex,

OK, I’ll use SO instead. It seemed like a bug to me, as I am used to Microsoft products behaving the same way in Windows. That’s one of the founding features that made Windows so successful and restricted Linux to back-office specialist systems.

Yours,

Dan
