### ISSUE TITLE
peek definition not closed

### ISSUE THREAD

**Issue by mvkorobkov** [Microsoft/vscode#46065]
Issue Type: <b>Bug</b>

open Peek Definition window and  then update code inside there - after this window can`t be closed

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz (4 x 1333)|
|Load (avg)|2, 1, 1|
|Memory (System)|7.64GB (0.35GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
search-node-modules|jas|1.3.0
debugger-for-chrome|msj|4.2.1
java|red|0.21.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/45182
