### ISSUE TITLE
Debugging a renderer process doesn't work when DevTools are opened in the Electron app

### ISSUE THREAD

**Issue by Septh** [Microsoft/vscode#46062]
I long hesitated before opening this issue because I'm really not sure it is a VS Code problem. Could very well be caused by Electron or even Chrome itself. Nevertheless, I made some testing and thought I'd share my findings.

As many people out there, I've been facing the _"Breakpoint ignored because generated code not found (source map problem?)"_ problem. In my case, this is while working on an Electron app. This app is 100% pure HTML/JavaScript - no transpiling, no minifying, no concatenating sources, no nothing. Hence, no sourcemaps either.

At this point, I must say that I haven't been working on this app for maybe 2 or 3 months and I remember having no issues back then. Now, the issue surfaces after many updates (VS Code, npm, Node.js and Electron) took place. Here's my current setup:

- VSCode Version: 1.21.1
- OS Version: Windows 10 64bit 1709 (16299.309)
- Node 8.2.1, Electron 1.8.4, Chrome 59.0.3071.115

So I googled a bit and found many comments about changing the `launch.json` file, for example by adding `"sourceMaps": false` to the `attach` profile. I tried them all but none worked. 

I then experimented myself. After many, many tries, here's what worked for me:
1. Started with a **fresh**, out of the box VS Code install (no extensions, all settings to their default values)
2. Followed word for word this recipe: https://github.com/Microsoft/vscode-recipes/tree/master/Electron
3. Replaced `${workspaceRoot}` with `${workspaceFolder}` (as I read that _root_ was deprecated in favor of _folder_) everywhere in `launch.js`
4. Commented out line 26 in `main.js` : `mainWindow.webContents.openDevTools()`

Voila! Using the `Electron: All` profile, the app finally stopped at line 6 in `renderer.js` after I hit `ctrl+r` and I then could run it step-by-step right in VS Code!

So I switched back to my own app, commented out the `openDevTools()` call and I could debug my app _almost_ as before. (see below why I'm saying "almost").

So it turns out that the VS Code debugger can't properly connect to Chrome if the DevTools console is opened. Furthermore, if I manually open the DevTools (`ctrl+shift+i`) _after_ the breakpoint is hit, the connection seems to be lost: the debug session does not end but VS Code can no longer step into the code --meaning I can't watch the DOM in Chrome and at the same time debug the code in VS Code.

Sorry for the long read. As I said, I'm not sure whether this issue is related to VS Code, Electron or Chrome and I just wanted to give as many insights as possible for someone to understand what's happening here.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@roblourens seems to be Debugger for Chrome related.

**Comment by roblourens** [comment]
Thanks for the tip on `${workspaceRoot}` in the recipes, we never updated the references in that repo, I just fixed them.

As for your real issue with using devtools and vscode at the same time, this is a limitation of Chrome/Electron, it only supports a single debug connection at a time.

Chrome the browser does support multiple connection debugging, but this hasn't made it to Electron yet.

**Comment by codebude** [comment]
@roblourens thanks for your comment. Really! I googled hours and started to doubt myself, because in each and every debug/launch.json tutorial i found, nobody mentioned this fact. (Neither in the ones which especially focused electron...) But your answer clarifies things. Thanks for that! :+1:
