### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by nicolasparada** [Microsoft/vscode#4606]
The scrolling behavior is not smooth when you do it with the mouse wheel. It has been fixed in chromium 49 that comes since electron 0.37.x
So, could you update to the last version of electron?
- VSCode Version: 0.10.12-insider
- OS Version: Windows 10

I left a [video](https://youtu.be/N8GcV3K6EP0) showing the difference with electron 0.37.x

**Comment by mquandalle** [comment]
I haven’t look at Chromium49 smooth scrolling yet, but it seems to me that this wouldn’t help VSCode scrolling that is managed using CSS `transform3D` and absolute positioning.

**Comment by NicolasParada** [comment]
Well then, eliminate these approach and use the native scroll behavior in chromium >= 49.

**Comment by jhasse** [comment]
Just tried out latest master: This is indeed not fixed in VSCode simply by updating to electron 0.37.5.

**Comment by alexandrudima** [comment]
@mquandalle is correct, we own the scrolling from JS.

We need to distribute the scrolling from point X to point Y through multiple frames in our code. Definitely a nice thing to have.

**Comment by BeginnerForLife** [comment]
...So, are we going to get smooth scrolling?

**Comment by alexandrudima** [comment]
I think this is a good opportunity for a PR:
* the [`ScrollableElement`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L57) should get a new option `smoothScrolling` or equivalent that can be exercised from [the editor](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewLayout/scrollManager.ts#L38)
* This option can be passed to the [`Scrollable`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L62)
* The [`Scrollable.updateState`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/scrollable.ts#L86) could use this option to update its `scrollTop` and `scrollLeft` in `n` frames, according to some math function.

**Comment by hediet** [comment]
Why not using the CSS property "transition-duration" for that? Seems to work quite well at first glance - if the lines that get invisible wouldn't disappear before the transition-duration is over.
I am not sure how important smooth scrolling is when translate3d is not used (and thus transition-duration has no effect).

**Comment by darkon5** [comment]
Is this issue still active?

**Comment by JD342** [comment]
@darkon5 I tried the latest master. Smooth scrolling seems to be working with the touchpad now (wohoo), but it still does not seem to work with the mouse wheel (tested on SP4 running Debian Stretch).

**Comment by JD342** [comment]
I submitted a pull request that should fix this.

![untitled2](https://cloud.githubusercontent.com/assets/11964463/25461629/4e308418-2aea-11e7-9ac2-2750add66329.gif)

**Comment by darkon5** [comment]
@JD342 HERO! <3
