### ISSUE TITLE
Unexpected creating multi-root workspace when moving file

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#46061]
For this kind of file structure

```
parentFolder/
├ childFolder/
└ file
```

Steps to Reproduce:

1. Open `parentFolder` with vscode, the explorer shows
   ```
   childFolder/
   file
   ```
2. Move `file` into `childFolder` (drag and drop within explorer)
3. A untitled workspace is created automatically, and explorer view becomes
   ```
   parentFolder/
   └ childFolder/
     └ file
   ```

However, I just want to move a file into or out a folder...

VSCode v1.22.0 insider
Windows 10 build 17120

**Comment by isidorn** [comment]
@neilsustc this is a great find, thank you very much
