### ISSUE TITLE
Text added at bottom of file in another app gets selected in VSC

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46073]
If I have a file in VSC, and it has some text, then I add text in the same file but in another editor, then the new text that I added will be selected.

I don't want the text to be selected, I just want the cursor to appear at the end of the file, after the new text.

Is the current behavior intentional, and if so, how can I change it to how I want?

![text selected](https://user-images.githubusercontent.com/343940/37574944-aceb7362-2afa-11e8-98bf-debe60538880.gif)

**Comment by alexandrudima** [comment]
I can reproduce this in 1.21, but I can no longer reproduce this (on master), so I believe it got fixed in the meantime.

I'm not sure what change led to the fix precisely. In the meantime, you can use https://code.visualstudio.com/insiders/ to benefit from the fix.

**Comment by garyking** [comment]
I'll report back when stable gets upgraded, perhaps in about 1-2 weeks?
