### ISSUE TITLE
Terminal is blank and cannot enter commands

### ISSUE THREAD

**Issue by liushuhui** [Microsoft/vscode#46078]
Issue Type: <b>Bug</b>

Terminal is blank and cannot enter commands

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|3.90GB (1.33GB free)|
|Process Argv|F:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

![image](https://user-images.githubusercontent.com/26155477/37578870-4fda3d76-2b76-11e8-87ad-a1558611dbfa.png)

**Comment by brunosserrao** [comment]
The terminal turn into black screen after computer returning from screensave mode.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169
