### ISSUE TITLE
square brackets swapped because of existence of (inactive) second-language RTL keyboard

### ISSUE THREAD

**Issue by finetype** [Microsoft/vscode#46076]
- VSCode Version: 1.21.1
- OS Version: Debian 9

Steps to Reproduce:

0. Have Hebrew enabled as an alternate keyboard in Debian 9.
1. Just try to use the universal <kbd>ctrl</kbd> + <kbd>]</kbd> / <kbd>ctrl</kbd> + <kbd>[</kbd> indentation hotkeys. They are inverted. (Is this intended behavior? It looks like it's the default setting, which is strange to me.)
2. Try to fix in shortcuts. Notice that when you type a bracket there, it picks up as the opposite facing bracket.
3. Sanity check: yes, indeed, when typing _code_, the brackets face the way you'd expect, they're only inverted when entering the hotkey into the appropriate pop-up field.
4. Type them "wrong" but so that they display "right", and yup, the shortcut then works as desired.
5. Realize that the problem is actually Hebrew... and decide whether this is a deal breaker. It probably is, this will likely cause other issues with hotkeys as well. :/

Extra info: I had no clue what this was, and as I was poking things to find more clues while typing this up, I noticed that when I typed <kbd>;</kbd> in the hotkey enter popup, I saw it described as a hebrew character that is on that key in the hebrew keyboard layout.
See: https://imgur.com/a/2O2Nv

Then it was obvious. It's an RTL language, so brackets are swapped in that layout.

For some reason, VScode picks up some stuff from my inactive second hebrew keyboard layout, seemingly in this context only. As I described above, within the editors, there is no such funny business. Seems like maybe some code reuse that should be happening, isn't?

To confirm, while I had VScode open and producing the error, I removed Hebrew from my OS languages while VScode was still running. Error still produced. Then I restarted VScode. Error no longer produced, nor secondary symptom that brought it to my attention.

This is not a viable solution, since I type Hebrew daily on my computer. 

Does this issue occur when all extensions are disabled?: Yup, still happens.

Other: incidentally, I had issues with caps lock swapped with control as well... switched settings in OS so that caps lock was just 'another control'. That solved that issue. There's already an issue or two floating around relating to that, though, so I commented there and moved on since it didn't seem to be a show stopper for me.

This is manageable, but I might abandon the app over it. This is two buggy behaviors I didn't have in sublime, not a good impression on me as a new user. :/

**Comment by alexandrudima** [comment]
@finetype Have you seen our self-help keyboard troubleshooting page https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

![image](https://user-images.githubusercontent.com/5047891/38040280-6f2ad8f8-32af-11e8-9084-42eeeb0b33cb.png)

**Comment by finetype** [comment]
Sorry, I had not seen that page. Sounds plausible, but somehow sublime manages.
I get 
```
rules:      evdev
model:      pc105
layout:     us,il,us
variant:    ,,
options:    compose:lctrl,altwin:prtsc_rwin,caps:ctrl_modifier
```

In other words, `us` looks like the correct first one, though I'm not sure why there are two `us`--I only have two keyboards enabled in my keyboard setting. (I used to use three keyboards, I don't anymore though.)
