### ISSUE TITLE
some \t display error in the output plane

### ISSUE THREAD

**Issue by deepkolos** [Microsoft/vscode#46074]
Issue Type: <b>Bug</b>

i use this button run the code

![2018-03-19_103152](https://user-images.githubusercontent.com/12824616/37575207-e0fffa86-2b60-11e8-9e93-4adfbb45665a.png)

![runcode tab](https://user-images.githubusercontent.com/12824616/37575160-a44dca96-2b60-11e8-8428-01ba01f7f069.png)

![runcode compare](https://user-images.githubusercontent.com/12824616/37575158-a4034be2-2b60-11e8-9dcb-2a216c1ae582.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|Memory (System)|7.93GB (2.38GB free)|
|Process Argv|D:\Program files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.7
xml|Dot|1.9.2
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
javac-linter|fau|1.3.1
php-debug|fel|1.12.2
php-intellisense|fel|2.2.9
php-pack|fel|1.0.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.2
beautify|Hoo|1.3.0
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.1.1
vscode-attrs-sorter|mrm|2.1.0
cpptools|ms-|0.15.0
vuejs-extension-pack|mub|1.0.2
vetur|oct|0.11.7
material-icon-theme|PKi|3.2.6
java|red|0.21.0
code-settings-sync|Sha|2.9.0
vscode-nginx|sha|0.5.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
vscode-react-native|vsm|0.6.5
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|2.0.0

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
This is the code-runner extension.
