### ISSUE TITLE
Question: is it possible to launch debugger from extension ?

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode#4607]
Hello,

I can't find an example on how to launch the debugger using the name in configuration.
Is it possible to achieve this ? If so, could you write a little snippet.

Thanks in advance for your help.

**Comment by jrieken** [comment]
maybe with a command?

**Comment by isidorn** [comment]
Yes, please try executing the command `workbench.action.debug.start`
[This call](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2879) should do the trick

**Comment by Alphapage** [comment]
That's working but I don't know how to set the name of the configuration. It is launching the default or selected one. Could you help me a little more to be able to start the debugger with the configuration name I want to impose ?

**Comment by isidorn** [comment]
That is currently not supported - this command will just launch the currently selected one.
If you want to launch a configuration with a specifc name please create a new feature request issue.
