### ISSUE TITLE
$global:options['CustomArgumentCompleters'] in Powershell hosted in VS is $null...but it's false outside

### ISSUE THREAD

**Issue by shanselman** [Microsoft/vscode#46079]
Issue Type: <b>Bug</b>

In a PowerShell window, run:

`$global:options['CustomArgumentCompleters'] -eq $null`

and note that it's TRUE

Now run the same command in a regular PowerShell window and note that it's FALSE.

This prevents a number of scripts from running within VS Code's PowerShell, including the popular "z" replacement for changing directories.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.17123

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       X 980  @ 3.33GHz (12 x 3373)|
|Memory (System)|24.00GB (15.42GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
vs-kubernetes|bre|0.0.9
xml|Dot|1.9.2
gitlens|eam|8.1.1
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|3.17.3
Ionide-Paket|Ion|1.9.1
kubernetes-snippets|ipe|0.1.9
python|ms-|2018.2.1
azure-account|ms-|0.3.3
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
vsliveshare|ms-|0.2.206
vscode-docker|Pet|0.0.25
vscode-icons|rob|7.21.0
vscode-arduino|vsc|0.2.11

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
i think this is something that needs to be handled on the PowerShell extension side, please create an issue against https://github.com/PowerShell/vscode-powershell :smiley:
