### ISSUE TITLE
Angular - auto-import feature (tslint error)

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#46077]
- VSCode Version: win7x64
- OS Version: 1.22.0-ins

Auto-import shows that it will import pipe using single quotes ' '
But instead - makes it using double quotes.
Not critical? Ok, tslint disagrees.

![ng - auto import](https://user-images.githubusercontent.com/24613274/37578160-ac128210-2b3f-11e8-8fe6-183cf65651a6.gif)

**Comment by mjbvz** [comment]
Tracked by https://github.com/Microsoft/TypeScript/issues/22342
