### ISSUE TITLE
do not show stackframe line information if source is missing

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4608]
while verifying https://github.com/Microsoft/vscode/issues/4027:

if a stackframe has no source, it does not make sense to show the source line:
![2016-03-23 12-20-35](https://cloud.githubusercontent.com/assets/1898161/13983836/8a97dfec-f0f2-11e5-9c40-278ea602b009.png)

**Comment by isidorn** [comment]
The source line in the call stack pane in debug viewlet? Screenshot?

**Comment by weinand** [comment]
@isidorn showing an empty badge looks a bit strange:

![2016-05-02 12-18-47](https://cloud.githubusercontent.com/assets/1898161/14952461/b70ac4a8-1060-11e6-8349-3f52b9b27576.png)

I suggest to show 'unknown source' right aligned instead. Please make sure that the string is nls'ed (currently it is not):
