### ISSUE TITLE
Access older Insider builds

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#46089]
Would it be possible to make available the older Insider builds, for testing purposes? For example, debug breakpoints are currently not working (#45657), it would be useful to try in three different VSCode versions and I'd much prefer to do it in the Insiders version, not in my main installation.

Maybe it's already kept on some CI server, just the URLs are not publicly known? At least I couldn't find them.

**Comment by joaomoreno** [comment]
You can check out all insider version numbers here:

https://vscode-update.azurewebsites.net/api/releases/insider

Then you can download the latest released build per version number like this:

https://vscode-update.azurewebsites.net/1.20.0-insider/darwin/insider

Just switch the version number in the URL.

For all other purposes, setup the VS Code development environment and use git to go back to old versions.

**Comment by borekb** [comment]
Cool, thanks. For reference, for Windows, the URL will be like:

https://vscode-update.azurewebsites.net/1.20.0-insider/win32-x64/insider

Also, there's this older issue: Publicly accessible previous versions of VS Code #11796 (I missed that previously).
