### ISSUE TITLE
Add a configuration option to disable preview for diff editors only

### ISSUE THREAD

**Issue by ryenus** [Microsoft/vscode#46088]
**Expected**: there should be a configuration to make diff editors keep open by default
**Actual**: one always need to turn on "Keep Open" to avoid diff editors closed automatically

- VSCode Version: 1.21.1
- OS Version: macOS 10.13

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`

**Comment by ryenus** [comment]
@bpasero thanks, setting `workbench.editor.enablePreview` to `false` 
works somehow, but I think there's a problem with the granularity here,
this options disable preview for all editors, meanwhile I'd like to 
disable it only for diff editors.

What about having something like below?

	diffEditor.enablePreview: false
