### ISSUE TITLE
Plant UML Diagram

### ISSUE THREAD

**Issue by JannLee** [Microsoft/vscode#46086]
Issue Type: <b>Bug</b>

After update to VisualStudio Code 1.21.1

I cannot show plant uml diagram in preview panel.

How can I solve it?

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.84GB (4.44GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Desktop\프로젝트 회의.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.5.5
markdown-preview-enhanced|shd|0.3.4

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
This issue has been moved to the plantuml repo. Please continue the discussion there.
https://github.com/qjebbs/vscode-plantuml/issues/107
