### ISSUE TITLE
run code不会根据python解释器切换 --> 'Will not switch according to python interpreter'

### ISSUE THREAD

**Issue by kev123456** [Microsoft/vscode#46082]
Issue Type: <b>Bug</b>

The python interpretercode of run code is incompatible with the setting

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|7.89GB (3.09GB free)|
|Process Argv|G:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.2
python|ms-|2018.2.1

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
Please provide us with a reproducible list of steps on how to trigger this bug.
