### ISSUE TITLE
When I set the column of the stack frame to 0 in the StackTraceResponse, the UI doesn't show an exception.

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#46080]
Issue Type: <b>Bug</b>

When I set the column of the stack frame to 0 in the `StackTraceResponse`, the UI doesn't show an exception.

When the column is greater than 0, it is correct.
I set it to 0 because the stack frames list on the UI will ignore the column.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 10.0.16299

Reproduces only with extensions

**Comment by isidorn** [comment]
This is expected behavior as most debug adapters do not support columns so they pass `undefined` or 0. Why would you expect an exception to be shown to the user if a debug adapter says column: 0?

fyi @wein

**Comment by actboy168** [comment]
I mean the exception of the debug target.
![1](https://user-images.githubusercontent.com/1836844/37592762-aab6c136-2baa-11e8-81c1-466ddf306e51.png)

**Comment by weinand** [comment]
I do not understand this issue.

**Comment by actboy168** [comment]
When the debug target throws an exception, I need to have vscode show the UI of an exception. I will send StoppedEvent and set reason to "exception". If everything is fine, you will see
![image](https://user-images.githubusercontent.com/1836844/37593185-160b6576-2bac-11e8-95e3-511a203391d8.png)

The location of this UI depends on the first stack frame in the StackTraceResponse I sent later (hopefully I didn't understand it). If the column in the stack frame is greater than 0, everything is fine. If it is equal to 0, then this UI will not be displayed.

**Comment by weinand** [comment]
There are two places where the exception information is shown:

![2018-03-19_13-06-36](https://user-images.githubusercontent.com/1898161/37594768-776280b0-2b76-11e8-82ad-b028ba974eec.png)

1. in the CALL STACK view
2. in the Exception peek UI

The "StackTraceRequest" is only used for 1).
For 2.) a new "ExceptionInfoRequest" is used. Please see https://code.visualstudio.com/updates/v1_11#_more-detailed-exception-experience and https://code.visualstudio.com/updates/v1_11#_debug-extensions

**Comment by actboy168** [comment]
The ExceptionInfoRequest only determines what to show, and it cannot decide where to show it, right?

I simply implemented ExceptionInfoRequest, only exceptionId, description, breakMode. But still can not see the UI, when the column is equal to 0.

**Comment by isidorn** [comment]
@actboy168 then do not send column 0, but column 1 or column undefined. Try that please

**Comment by actboy168** [comment]
Still not working, if column undefined.

In addition, according to protocol, column is a required parameter.
https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json#L2535

**Comment by actboy168** [comment]
`OutputEvent` has the same problem. In the `OutputEvent` column is an optional parameter, but if it is undefined, clicking the output message can not locate the source code.

**Comment by weinand** [comment]
@actboy168 please file a new bug for the `OutputEvent` issue with detailed steps.

**Comment by actboy168** [comment]
@weinand #46165

**Comment by remss** [comment]
It should be documented somewhere in the protocol that if the column is not defined then the exception Peek UI is not displayed

**Comment by weinand** [comment]
@isidorn why do we handle column 0 differently?

**Comment by isidorn** [comment]
@weinand the zone widget does not allow to be shown at column 0 (since our editor starts columns from 1)
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L426

I could do a fix to show at column 1 if no column or column 0 is passed

**Comment by weinand** [comment]
@actboy168 you are only allowed to use a column value of 0 if the frontend says that it starts columns at 0. VS Code columns start at 1. 
So using column value 0 is not supported.
