### ISSUE TITLE
Create new local branch and publish to git is VS code is not completed

### ISSUE THREAD

**Issue by eldhoabe** [microsoft/vscode#46087]
- VSCode Version: Version 1.21.0
- OS Version: Windows 10 

Steps to Reproduce:

1. Create a new local branch 
2. Click on Publish Changes icon next to branch switch
3. The git start running the progress bar 
4. Never end the process even after a 10-15 mints.
5. After that changes on file is not detected in Git changes view.
![vs issue](https://user-images.githubusercontent.com/4771705/37583452-d8982c06-2b6a-11e8-94ce-80d0a13c0b7c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you show me what appears in the `Git: Show Git Output` during the publish process?

**Comment by eldhoabe** [comment]
The git output 

Looking for git in: C:\Users\eab\AppData\Local\Programs\Git\mingw64\libexec\git-core\git.exe
Using git 2.15.0.windows.1 from C:\Users\eab\AppData\Local\Programs\Git\mingw64\libexec\git-core\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\Logisoft.Web\Logisoft.Angular
> git status -z -u
> git symbolic-ref --short HEAD
> git show :src/app/createbooking/booking-create.component/booking-create.component.ts
> git rev-parse testbranch
> git rev-parse --symbolic-full-name --abbrev-ref testbranch@{u}
fatal: no upstream configured for branch 'testbranch'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git show :src/app/createbooking/booking-create.component/booking-create.component.ts
> git push -u origin testbranch

**Comment by joaomoreno** [comment]
And what happens when you run `git push -u origin testbranch` from the command line?

**Comment by eldhoabe** [comment]
It works when i push it from the command line.
But the icon of git which will be still that same and changes to files is not detecting.

After i restart vs code it works fine

**Comment by joaomoreno** [comment]
After you restart, I assume you then see the sync icon, instead of the publish icon, right?

When you click publish, can you double check there is no authentication dialog box behind VS Code?

**Comment by eldhoabe** [comment]
Yes I have the publish icon after restart.
I don't find any authentication box. 

I have able to push using IDE after synced from the terminal

**Comment by joaomoreno** [comment]
@eldhoabe Is this still an issue for you?

**Comment by eldhoabe** [comment]
I haven't tried this with latest version. I will try and update you

**Comment by petevo** [comment]
I am still getting the error `fatal: no upstream configured for branch` with latest vscode (1.36.1)

**Comment by joaomoreno** [comment]
@petevo That's not an error, just a warning. All features should work.

Closing this.
