### ISSUE TITLE
Cannot open XML file

### ISSUE THREAD

**Issue by michaelnemtsev** [Microsoft/vscode#46081]
Issue Type: <b>Bug</b>

Opening an XML file throwning an error "the file will not be displayed in the editor because it's either binary, very large or uses an unsupported text encoding"

However, the file opens successfully in notepad and in a browser

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.17123

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (5.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\michaeln\OneDrive\ID PT rules Pack v1.6.xml|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.0
python|ms-|2018.2.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.2.1
vscode-docker|Pet|0.0.25
vscode-icons|rob|7.21.0
partial-diff|ryu|0.5.1
vscode-sql-beautify|sen|0.0.4

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
You mention that this problem only occurs with extensions enabled. Please disable all extensions (CTRL+SHIFT+P --> 'Disable all installed extensions') and restart VS Code.
Then check if the problem still persists. If not, try to find which one causes the trouble by enabling one extension after the other.

If the problem is not caused by an extension, please provide us with a reproducible list of steps that cause this behavior. Also, if possible, provide the xml file that is causing problems.

**Comment by michaelnemtsev** [comment]
I’ve disabled all extensions as per recommendations, restarted the VS Code, but the issue persists and I cannot open that XML file

**Comment by alexandrudima** [comment]
@michaelnemtsev I believe we end up identifying the XML file as a binary file. Can you perhaps share the file or one which is very similar (if the original cannot be publicly shared) that reproduces the problem?

**Comment by alexandrudima** [comment]
Thank you for the file @michaelchiche . I have forwarded it internally to @bpasero . The file is only 5.3KB, so it is most likely detected as binary.

**Comment by bpasero** [comment]
@michaelnemtsev the file seems to be UTF-16 without BOM which we do not support. If you add a BOM it will work.

**Comment by michaelnemtsev** [comment]
seems to be strange not having this support. the file opens well in other editors
Any reasons why we don't support it?
