### ISSUE TITLE
Bugreport: Icon

### ISSUE THREAD

**Issue by NF997** [Microsoft/vscode#46095]
First, I would like to say that I love VS Code. There is no comparable editor with so much valuable plugins.
But still I have to report a bug in the icon.
Unfortunately, you simply forgot a vertical line.

![vscodeicon](https://user-images.githubusercontent.com/23374308/37587644-344a22b2-2b60-11e8-9efc-07f32aa812d4.PNG)

Thanks in advance!

**Comment by bpasero** [comment]
@NF997 this is as designed to distinguish VSCode from VS.

**Comment by NF997** [comment]
I do understand and appreciate, that you care about colorblind people, but for me it's just simply a pain looking at this two icons side by side having not the exact same shape.
