### ISSUE TITLE
Honour "preserveFocusHint" attribute of StoppedEvent

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#46098]
Please see https://github.com/Microsoft/vscode-debugadapter-node/issues/147.

I've added a `preserveFocusHint` to the StoppedEvent.

VS Code should honour this attribute by not changing the focused thread if the attribute has the value true.

**Comment by isidorn** [comment]
@weinand I do not see this attribute in the latest debugProtocol.d.ts in vscode. Can you please ping me once you add it there. Thank you

**Comment by weinand** [comment]
@isidorn sorry, forgot to push. Done!
