### ISSUE TITLE
Describe how to use proposed api

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode#46090]
I wanted to use proposed api for folding, but I struggled understand how to use it.
[The link](https://code.visualstudio.com/updates/v1_21#_proposed-extension-apis) says that I have to copy the file and add `"enableProposedApi": true`.
I did it, but I couldn't use api because it couldn't be found.
After 4 hours struggling I asked people on Gitter and they said that I should have been copied declaration of proposed api I'm interested in to vscode.d.ts
I think it should be mentioned somewhere.
I'd suggest giving it a separate section: [here](https://code.visualstudio.com/updates/v1_21) (in the end for an example) and [here](https://code.visualstudio.com/docs/extensions/overview) (in the end for an example). It also should mention that I have to use dev.

What do you think?

**Comment by rcjsuen** [comment]
Please write the directions directly in the `vscode.proposed.d.ts` file. People that are looking at the new API will then easily know how to give it a spin in their own extension.

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/issues/33358

**Comment by KalitaAlexey** [comment]
It's not a duplicate since what I'm suggesting is to document how to use it, not to add autocomplete to package.sjon.
