### ISSUE TITLE
Search does not update after change

### ISSUE THREAD

**Issue by d4nyll** [Microsoft/vscode#46091]
Version 1.22.0-insider
Commit 9160e85b1ab0333dfe697032f90da494f1f81fd4
Date 2018-03-16T13:43:08.367Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Linux 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I was looking to replace all instances of `this.hash` with `this.digest` inside my code. It found 2 instances of `this.hash` and so I replaced them both with `this.digest`. Afterwards, when I search for `this.hash` I still get results for `this.digest` at the location where the two instances of `this.hash` used to be, and the first four characters of `digest` is highlighted (see below)

![screenshot from 2018-03-19 16-34-51](https://user-images.githubusercontent.com/9997953/37585438-0be59598-2b94-11e8-8a9a-c0c96e3751bb.png)

If I search for `this.has` instead, the first 3 characters of `digest` is highlighted.

Restarting Code Insiders resolved this issue and thus cannot be reproduced.

**Comment by roblourens** [comment]
Was that file open when you got the stale results? @rebornix?

**Comment by d4nyll** [comment]
@roblourens Not sure if the file was opened. I have restarted the editor and that fixed the issue but it also means I don't know how to reproduce it. If I come across it again, I will add to this thread.

**Comment by rebornix** [comment]
@d4nyll there is one issue with model searching which I already fixed days ago. So let's close this first and if you run into any issue later, we can reopen it.
