### ISSUE TITLE
Retry as admin authentication dialog doesn't appear if the file has focus

### ISSUE THREAD

**Issue by flurbius** [Microsoft/vscode#46093]
Issue Type: <b>Bug</b>

note - I am running a debian based distro of linux, and I have files set to be saved when the editor loses focus.

1.  Edit a file that requires admin permissions to save.
2.  Leave the cursor in the editor view (ie don't click your mouse anywhere else, make sure it's blinking to be sure).
3.  press ctrl-s, Retry as admin Dialog is shown.
4.  Select 'Retry as admin'
5.  **Authentication dialog should show but it doesnt**, Retry as .. dialog persists or is re-shown.
6.  Now click somewhere outside the editor view to change focus (eg empty area on tab bar or choose a different part of the workbench such as debugger, SCM, extensions or click in the statusbar or in the workbench)  make sure the cursor stops blinking
7.  Select 'Retry as Admin' 
8.  Authentication dialog is shown. password can be entered and file will be saved.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.14.0-deepin2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2830  @ 2.16GHz (2 x 2159)|
|Load (avg)|1, 1, 2|
|Memory (System)|7.68GB (0.52GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@flurbius this sounds like https://www.github.com/Microsoft/vscode/issues/42424 which got fixed in insiders meanwhile. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by flurbius** [comment]
You are correct this has been fixed/can't reproduce in insiders :-)
