### ISSUE TITLE
Support resizing editor panes with keyboard shortcuts (similar to terminal panes).

### ISSUE THREAD

**Issue by IzakMarais** [Microsoft/vscode#46100]
This is a feature request. Hopefully the title is descriptive enough.

I really appreciate it when keyboard shortcuts are consistent between the terminal and the editor. It is great to be able to resize the terminal panes using keyboard shortcuts. It would be even better if I could use those same keyboard shortcuts to resize editor panes. 

(PS: not sure if I still need to add the VSCode version to a feature request. It is 1.21.1.)

**Comment by Tyriar** [comment]
These are the (Linux) keybindings being referred to FYI:

```
{ "key": "ctrl+shift+down",       "command": "workbench.action.terminal.resizePaneDown",
                                     "when": "terminalFocus" },
{ "key": "ctrl+shift+left",       "command": "workbench.action.terminal.resizePaneLeft",
                                     "when": "terminalFocus" },
{ "key": "ctrl+shift+right",      "command": "workbench.action.terminal.resizePaneRight",
                                     "when": "terminalFocus" },
{ "key": "ctrl+shift+up",         "command": "workbench.action.terminal.resizePaneUp",
                                     "when": "terminalFocus" },
```

There is some discussion as to whether there is a conflict with powershell https://github.com/Microsoft/vscode/issues/45876

**Comment by cleidigh** [comment]
@IzakMarais 
You should note that there are also two other commands:
Increase/Decrease View

They do not have preset shortcuts, you can see the commands in the command pallet and assign your own.

They work slightly differently than the terminal commands for the panel.  From anywhere, the sidebar, any editor or the panel, you can use these commands.  They expand or contract the current focused window/pane along the main access.  For instance if you had focus in the sidebar and used increased V
it would expand the sidebar and contract to the editor windows.  Opposite if you have an editor focused.
If you have the panel focused and in horizontal mode Increase would shift the sash up.  One form that is not yet supported is a split editor like the user settings view.  Multiple editor windows are supported.

**Comment by IzakMarais** [comment]
Aah, I see thanks.

It is a bit unfortunate that these conceptually similar actions behave so differently between the terminal and the rest of the application.

**Comment by bpasero** [comment]
I am closing this per https://github.com/Microsoft/vscode/issues/46100#issuecomment-374429027
