### ISSUE TITLE
Javascript syntax highlight gone

### ISSUE THREAD

**Issue by zhouhao27** [Microsoft/vscode#4610]
My js file syntax highlight suddenly gone in version osx 0.10.10. It's still the same in 0.10.11. So I delete my app and configuration file and redownload and install. But the problem exists.

<img width="746" alt="2016-03-23 9 26 16" src="https://cloud.githubusercontent.com/assets/8099731/13986411/46eef83e-f13d-11e5-919f-9592b3f3dc88.png">

There is no problem for other files such as html, css, ts, etc.

**Comment by jrieken** [comment]
@alexandrudima maybe an issue with onig?

**Comment by aeschli** [comment]
@zhouhao27 Can you paste the code here that doesn't highlight?

**Comment by zhouhao27** [comment]
Any js script syntax is not highlighted. Here is another sample:

```
(function(){
  'use strict';

  angular.module('MyApp')
    .directive('articleList',ArticleList);

  function ArticleList() {
    var directive = {
      restrict: 'AE',
      templateUrl: 'templates/article-list.html'
    }

    return directive;
  }

})();

```

But I build the latest **Code - OSS** from source code. It's no problem at all.

**Comment by aeschli** [comment]
Very strange. I tried your snippet in a 0.10.10 release, and all worked fine.
Are you using a custom color theme?
Also, can you open the Dev tooks (F1 -> Toggle Developper Tools), go to the console tab and see if there is anything special?

**Comment by aeschli** [comment]
Closing for now. You can try a March release preview at https://code.visualstudio.com/insiders
