### ISSUE TITLE
CancellationTokenSource.dispose() should not cancel()

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46101]
To allow to dispose() without firing the cancel event listener.

**Comment by dbaeumer** [comment]
@bpasero can you please clarify why we did this change. See https://github.com/Microsoft/vscode-languageserver-node/issues/466

**Comment by bpasero** [comment]
@dbaeumer see discussion in https://github.com/Microsoft/vscode/pull/46102

**Comment by dbaeumer** [comment]
@bpasero thanks
