### ISSUE TITLE
Workspace: Can't add folder to workspace

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#46109]
Seen on macOS

1. Open a folder
2. Try to add another folder to the workspace. `Cancelled` error appears
3. Try it again. `Cancelled` error appears
4. Quit Code
5. Open Code
6. Two windows open, exact copies of each other in terms of workspace folders!

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/commit/b1bc9a59646fd37eebb389e392f480a6145cc927
