### ISSUE TITLE
[Feature request] Allow json schemas to be read from Javascript files for better programmability

### ISSUE THREAD

**Issue by bary12** [Microsoft/vscode#46105]
- VSCode Version: 
- OS Version:

Currently JSON schemas are static JSON files themselves, which makes it hard to make the JSON validation dependent on external files. Here is an example of why this might be useful

```javascript
const fs = require('fs');
const path = require('path');
module.exports = {
  type: 'object',
  properties: {
    main_file: {
       type: 'string',
       enum: fs.readdirSync(path.resolve('my/directory'))
    }
  }
};
```
This does not require changing the JSON schema v-04 draft, only allowing reading the schemas from javascript files. in the configuration it could look the same:
```JSON
{
  "json.schemas": [{
    "url": "myschema.schema.js",
    "fileMatch": ["**/myfilename.json"]
  }]
}
```

I can think of a few more cases where this will be useful for many existing schemas. For example, the .eslintrc schema could read the installed plugins from package.json and add support for their rules. Currently only native rules are supported in the schema, and this list has to be updated every time a new rule is added.

**Comment by aeschli** [comment]
JSON schemas are identified by URIs, and its a service that serves that URL. Can be from a static content, but can be generated by JavaScript.
We already do that for the schemas that drive the JSON setting files. They use URI's in the form of 'vscode://settings/...' which is served by a document provider.

**Comment by bary12** [comment]
@aeschli Is there a way of doing this locally over file:///?

**Comment by aeschli** [comment]
No, not through ``file://``

**Comment by bary12** [comment]
This does not help me then, as it can't depend on things happening in the file system.

**Comment by aeschli** [comment]
JSON schemas are static by nature. I think you are pushing in the wrong direction here. Tyically, schemas are provided from a server URL, they are cached and they also can't contain validation rules based on a local setup.
If you are a VSCode extension and want to improve code completion for e.g. `eslint` files, why not providing a completion processor that can provide proposals based on the local file system?
There are several examples in the VSCode codebase that do that. E.g. check out the https://github.com/Microsoft/vscode/blob/master/extensions/extension-editing/src/extension.ts#L116
That adds proposals to 'package.json', on top of what the package.json schemas provide.

**Comment by bary12** [comment]
I'm not looking to improve .eslintrc (I gave it as an example for how this can be used), I need this feature for my project which uses quite complex json files, and we want to have our schemas validated based on things happening in the file system. Making an extension would be a waste of time as we are barely 10 people in the project, and the only other option we currently have is to add a build process to the schemas, which is very tedious. I tried making a plugin that loads the schemas from JS files but was unable to integrate it with the existing vscode json schema support.

**Comment by aeschli** [comment]
Note that you can also pass the schema directly in the settings:
```
{
  "json.schemas": [{
    "url": "foo://myschema/schema",
    "fileMatch": ["**/myfilename.json"],
    "schema" : {
        "type": "string"
    }
  }]
}
```
Your code (in an extension) could set the schema like that.

**Comment by aeschli** [comment]
Closing as there are no plans to implement the initial suggestion. See my alternative suggestions.
- provide the schema through settings
- provide the schema through a document provider
