### ISSUE TITLE
Can we not flag comments in ARM JSON files as errors?

### ISSUE THREAD

**Issue by erictorbenson** [Microsoft/vscode#46114]
I'm doing a lot of work with Azure Resource Manager templates, and tend more towards the Ops side of DevOps. Over on our side of the fence, reading infrastructure-deploying JSON files would be much easier with inline comments, since we're building longer-lived IaaS stuff with them and tend to human-edit them more.

Can we have a setting where JSON comments in ARM templates aren't flagged as illegal? The ARM parser does strip them out if you submit a template with comments. I know you can add a "description" or "comment" element, but when you're reading 1000 lines of template it's nice to see a comment that clearly states "change this parameter for Behavior X" in a distinct color the way you might do in a traditional XML or config file.

**Comment by aeschli** [comment]
You have to associate your file with the 'jsonc' language mode. You can do that in the status bar (on the language mode), and also in the user settings.

**Comment by erictorbenson** [comment]
That works, thank you!
