### ISSUE TITLE
No way to change input.selectionBackground because option does not exist

### ISSUE THREAD

**Issue by jcready** [Microsoft/vscode#46113]
There does not appear to be a way to change the selection background color of inputs such as the find/replace input. In my case it makes it very difficult to tell when/which characters are selected:

`Not selected:` ![Unselected](https://user-images.githubusercontent.com/358876/37601249-ed098924-2b5f-11e8-8e99-a40e16e17615.png)  
`All selected:` ![Selected](https://user-images.githubusercontent.com/358876/37601376-408a1fb4-2b60-11e8-9a3c-cb1b36d9d7ea.png)

- VSCode Version: 1.21.1
- OS Version: OSX 10.12.6

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
It looks like this is possible via https://css-tricks.com/overriding-the-default-text-selection-color-with-css/

/cc @aeschli

**Comment by usernamehw** [comment]
`"selection.background": "#ff000080",`

**Comment by jcready** [comment]
@usernamehw Thanks, that's exactly what I was looking for. Seems weird to put that setting under "Base Colors" instead of with the rest of the [input control settings](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_input-control), but maybe that's just me.
