### ISSUE TITLE
Notifications should expand automatically when clicking on them

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#46119]
When I clicked on this notification, it just "selected" it. I had to click the small little expand icon to see the full text. I think it would be better if it expanded automatically if you clicked on/selected it.

![expand](https://user-images.githubusercontent.com/1078012/37604928-015cb7aa-2b8a-11e8-9032-b713c9c19882.png)

**Comment by bpasero** [comment]
@DanTup doubleclick will expand. I am closing this as wontfix because it is perfectly fine to select a notification just to get focus and then maybe you want to keep the view state stable.

**Comment by DanTup** [comment]
@bpasero Thanks; didn't realise I could double-click - I'm fine with that :)
