### ISSUE TITLE
<none> needs to be localized

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4611]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L71

**Comment by isidorn** [comment]
<none> is shown in the debug viewlet configuration dropdown when there is no `launch.json` present

**Comment by weinand** [comment]
@isidorn do we have a better word than "none"?
It will be difficult for the translators to find good a translation without any additional context.
What's about "create launch config".

**Comment by isidorn** [comment]
@weinand it has to be short in order to fit in the select drop down nicely. create launch config is too wide for that. I am open for suggestions

**Comment by vsccarl** [comment]
@isidorn Are translations available for this yet? Still showing `<none>` for all langs in commit [7f7c50af30205e0f3d62866dd758f6fddb63f3c0](https://github.com/Microsoft/vscode/commit/7f7c50af30205e0f3d62866dd758f6fddb63f3c0)

**Comment by isidorn** [comment]
@vsccarl I have just pushed the translations which means the next alpha will have them

**Comment by weinand** [comment]
@isidorn '<none>' shows now as '<keine>' in German which looks very silly...
My proposal for better wording would be: 'no configurations' which would become 'keine Konfigurationen' in German.

**Comment by isidorn** [comment]
@weinand instead of <none>, we are no whosing No Configurations.
I believe this solution now works because the select drop down automatically gets wider, so most of the time 'No Configuraitons' is not clipped
