### ISSUE TITLE
vscode connects to microsoft link each time i open

### ISSUE THREAD

**Issue by Manuyashchaudhary** [Microsoft/vscode#46111]
- VSCode Version:1.20
- OS Version:Ubuntu 16.04

Whenever I open VSCode in Ubuntu it connects to the documentation page. This is annoying. Does anyone have solution for this?

**Comment by vyzboy92** [comment]
Same issue here....help needed ASAP!!!

**Comment by bpasero** [comment]
@Manuyashchaudhary @vyzboy92 are you both on VSCode 1.20? There is 1.21 meanwhile.

**Comment by vyzboy92** [comment]
I am on 1.20.

**Comment by bpasero** [comment]
@vyzboy92 can you update and then try again?

**Comment by vyzboy92** [comment]
Thank you for the quick reply....
I will try updating it and see if that fixes this issue.....

**Comment by Tyriar** [comment]
@bpasero when you open VS Code on a clean install it will open the welcome page on the website, it's always kind of bugged me but it's meant to help people get started.

**Comment by bpasero** [comment]
@Tyriar oh yeah I know that, but this issue seems about the URL being opened all the time
