### ISSUE TITLE
Python: Can't debug/break on breakpoints when using virtual environment / pythonpath

### ISSUE THREAD

**Issue by TitaneBoy** [Microsoft/vscode#46116]
- VSCode Version: 1.21.1
- OS Version: Windows 7
- Python version: 3.6.3

Hi. I'm using virtualenv to create virtual environments for my python projects.
To create a virtual environment with virtualenv, we must go on our current project directory (with terminal/console) and execute the command: `virtualenv .`  (Of course, virtualenv must be already installed)
This command will create some folders for the virtual env and in the folder "Scripts", we can see the python.exe executable with others files

![image](https://user-images.githubusercontent.com/15614466/37604113-99adece6-2b66-11e8-9933-ddc746b08ad6.png)

So in order to use the python of my virtual environment,  I use this in my "settings.json" config:
`
{
  "python.pythonPath": "${workspaceFolder}\\Scripts\\python.exe"
}
`
To debug my project, in my launch.json, I have this:

```
{
      "name": "Launch Program",
      "type": "python",
      "request": "launch",
      "stopOnEntry": false,
      "pythonPath": "${config:python.pythonPath}",
      "program": "${workspaceFolder}/main.py",
      "cwd": "${workspaceFolder}",
      "env": {},
      "envFile": "${workspaceFolder}/.env",
      "debugOptions": [
        "RedirectOutput"
      ]
    }
```

But when I am launching the debug, it nevers breaks on any breakpoints, even if I set "True" for the "stopOnEntry" option in launch.json.

Is there something I'm missing or there is here a true issue in vscode ?

Also, I know that in order to "activate" virtual environment with virtualenv, we must launch the activate(.bat) script located in the "Scripts" created folder.

Of course, If I remove the settings.json file, it will breaks on my breakpoints, but it will not use the python from the virtual environment.

Thanks for your help

**Comment by tsalinger** [comment]
Moved to https://github.com/Microsoft/vscode-python/issues/1112
