### ISSUE TITLE
Allow to theme inactiveListFocusBack/Foreground

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#46129]
- VSCode Version: 1.21.1
- OS Version: macOS

The `list.inactiveFocusForeground` is not working. I checked source code and it's only defined here: https://github.com/Microsoft/vscode/blob/ab1669f8987c585c260e824584e3bf79c82fc064/src/vs/platform/theme/common/colorRegistry.ts#L196

**Comment by bpasero** [comment]
True, I will remove it.

**Comment by svipben** [comment]
@bpasero Also, I found it in documentation: https://code.visualstudio.com/docs/getstarted/theme-color-reference

So to be 100% sure, it will be removed and do not use it?

**Comment by bpasero** [comment]
@svipben yes I could not find it used anywhere in the code and it also makes sense: the focused item is never showing up when focus is out of the tree, only the selection is showing. I will also remove it from the documentation.

**Comment by svipben** [comment]
@bpasero Thanks. So `inactiveFocusForeground` will be removed, but it have also this `inactiveFocusBackground` which works, it will also be removed or no?

**Comment by bpasero** [comment]
@svipben good point, I take it back. It looks like `inactiveFocusBackground` is actually supported in lists only (not trees). So I think the issues are:
* `inactiveFocusBackground` should probably be supported by the tree as well
* `inactiveFocusForeground` should either be removed or supported in tree and list

**Comment by svipben** [comment]
@bpasero I suggest supporting `inactiveFocusForeground`. Because `inactiveFocusBackground` is working and it's kinda weird when you can set the background color, but foreground will be different and you can't control it.

So as far as I understand it will be fixed and these colors will not be dropped?

**Comment by bpasero** [comment]
@svipben yes I think the colors should not be dropped if we can support them. It seems to me though that we never supported the focused element of a tree to show any color when the tree itself did not have focus. Can you confirm that you see this color only working for lists but not trees?

**Comment by svipben** [comment]
@bpasero If the list is sidebar when yes, it works for me only in `OPEN EDITORS` and only if I drag for e.g. `Explorer` button from left side to the `OPEN EDITORS`.

To show better I take this screenshot to represent how it looks like:

<img width="261" alt="screenshot at mar 20 08-54-15" src="https://user-images.githubusercontent.com/10441177/37640005-49ee29bc-2c1c-11e8-9810-d39ed9baabda.png">

As you can see I'm dragging `Explorer` to the `OPEN EDITORS` and color is blue which is good, because I set it, but there's no foreground even if I defined it.

**Comment by bpasero** [comment]
@svipben this color should actually only be used in this case:
* click on an entry in the "Open Editors" view
* arrow down (this will "focus" the entry below)
* click into the editor

=> now the focused entry should get the `inactiveFocusBackground` color

**Comment by svipben** [comment]
@bpasero can you please show gif? Thanks!

**Comment by bpasero** [comment]
@svipben ![flicker_chrome58](https://user-images.githubusercontent.com/900690/37651443-6ebbb3b0-2c38-11e8-8974-2f3a0498cbc6.gif)

**Comment by svipben** [comment]
@bpasero `list.invalidItemForeground` is not working too. So `list. inactiveFocusForeground` and `list.invalidItemForeground` is not working at all. And also checked `invalidItemForeground` is only defined here: https://github.com/Microsoft/vscode/blob/ab1669f8987c585c260e824584e3bf79c82fc064/src/vs/platform/theme/common/colorRegistry.ts#L201

**Comment by bpasero** [comment]
@isidorn did you introduce `list.invalidItemForeground`?

**Comment by isidorn** [comment]
@bpasero yes

**Comment by bpasero** [comment]
@isidorn if the color is not being used, just remove it (also from the docs)

**Comment by svipben** [comment]
@bpasero @isidorn Maybe I'm wrong. To be sure I'm correct, how do you test `invalidItemForeground` color?

**Comment by isidorn** [comment]
@bpasero but the color is being used here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerDecorationsProvider.ts#L39

**Comment by svipben** [comment]
@isidorn as I said I was wrong about `invalidItemForeground` I misunderstood how it works. So currently we have only this color not working properly: `list.inactiveFocusForeground`

**Comment by bpasero** [comment]
@isidorn sorry, I think my search was broken, I did not see it before.

**Comment by bpasero** [comment]
To be consistent between tree and list I have pushed a change to not support this color anymore for list (via https://github.com/Microsoft/vscode/commit/04ab6d103c13c9cbdd9d98dec18553bf046df8d7).

**Comment by svipben** [comment]
@bpasero thank you very much!

**Comment by bpasero** [comment]
@svipben yes I did that but this change will only go live once we have released

**Comment by svipben** [comment]
@bpasero I saw your last commit https://github.com/Microsoft/vscode/commit/b670f87518ccd4165206e18c40c76d94b053e5c6 was bringing back `list.inactiveFocusBackground`. Why?

**Comment by bpasero** [comment]
@svipben I realised that our new multi-select picker is actually using it, I might only be able to remove this color next milestone once we figured it out.

**Comment by svipben** [comment]
@bpasero good to know, thanks for explaining it. 👍

**Comment by svipben** [comment]
@bpasero Hi, any news about this? Maybe I can help you somehow?
