### ISSUE TITLE
Toggle Line Comment CTRL+/

### ISSUE THREAD

**Issue by piterog** [Microsoft/vscode#46125]
- VSCode Version: Version 1.21.1
- OS Version: W10
- Keyboard: Brazilian Keyboard ABNT

Steps to Reproduce:

1. Open Keyboard Shortcut
2. Search for "toggle line comment"
3. Double Click
4. Press CTRL+/
5. Show on input "ctrl+abnt_c1"
6. Press ENTER
7. Nothing Happens

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
@piterog thanks for the report, please provide the following info:

- What type of file were you editing at the time? Does ctrl+/ work for other languages?
- Contents of your settings.json file
- Contents of your keybindings.json file

**Comment by alexandrudima** [comment]
@piterog I cannot reproduce. I do not have access to an ABNT keyboard, but here I am using the on-screen keyboard with your steps. I rebind `Toggle Line Comment` to <kbd>Ctrl</kbd>+<kbd>/</kbd> (which is ctrl+VK_ABNT_C1, see #23685) and then I can successfully use it to toggle the comment and the top of the keybindings file:

![kapture 2018-03-21 at 9 26 04](https://user-images.githubusercontent.com/5047891/37700041-5d90cd66-2cea-11e8-9719-7760f698d4ca.gif)
