### ISSUE TITLE
Crash save as pressing esc to clear windows explorer filter

### ISSUE THREAD

**Issue by Giois93** [Microsoft/vscode#46121]
- VSCode Version: 1.21.0
- OS Version: Windows 7 Pro SP2

Steps to Reproduce:

1. open VS code (some files automatically opens due to the fact they were opened when I closed VS code)
2. save a file that has never been saved before (or "save as")
3. "save as"-like dialog appears
4. use windows explorer filter
5. press esc (x3 until the dialog closes)
VS code stop working
[ScreenCapture_19-03-2018 17.23.43.zip](https://github.com/Microsoft/vscode/files/1825878/ScreenCapture_19-03-2018.17.23.43.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I can actually not reproduce on my Windows 7.

Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
