### ISSUE TITLE
Debug Extension Failing for Electron App

### ISSUE THREAD

**Issue by GitFlip** [Microsoft/vscode#46128]
Issue Type: <b>Bug</b>

Followed Electron Forge instructions for creating a new test application:

```
npm install -g electron-forge
electron-forge init my-new-project
```

Added a `launch.json` file to `.vscode`:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron-forge-vscode-nix",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron-forge-vscode-win.cmd"
      },
      //"console": "integratedTerminal",
      "outputCapture": "std",
      "cwd": "${workspaceRoot}"
    }
  ]
}
```

Try to launch and receive this error: https://i.imgur.com/1NFM5l0.png

Note: This looks to be similar to this issue: https://github.com/Microsoft/vscode/issues/40501
Note: I can only reliable reproduce this for my current test app.
Note: I have a much more advance Electron App that I've been developing for 4 months now and it works just fine.
Note: I have this test app in a git repo, my teammates cannot reproduce the issue - they are running Windows 10 I am running Windows 7.
Note: Running from the command lines (no debug extension) launches the test app just fine.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.88GB (0.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.21.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0

</details>
Reproduces only with extensions

**Comment by GitFlip** [comment]
Update:

Uncommenting `"console": "integratedTerminal"` fixes my issue. Seems like that is part of the problem, at least with Window's 7. I found this other issue that helped me: https://github.com/Microsoft/vscode-node-debug2/issues/130

**Comment by Tyriar** [comment]
I think you're hitting https://github.com/Microsoft/vscode/issues/43169
