### ISSUE TITLE
Zoom does not work

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#4612]
- VSCode Version: 0.10.11
- OS Version:Microsoft Windows [Version 10.0.10586]

Steps to Reproduce:

Try zooming using keyboard, mouse, or menu. No effect.

**Comment by bpasero** [comment]
@leegee we do not allow to zoom out below 0, maybe this is what you try?

**Comment by leegee** [comment]
I'm not sure -- but I can't zoom in or out.

**Comment by bpasero** [comment]
Can you attach a video showing this problem?

**Comment by leegee** [comment]
Good question - when I tried, I found that you were right, in that I could
not make my text smaller because 12pt (I guess) is as small as it gets, but
I *can* zoom in using the keyboard shortcuts and the menu command.

Although the whole windows is zoomed, you know about that in another ticket.

I cannot use CTRL+mouse wheel, though -- is that by design, or should we
re-title this ticket?

Thanks for your quick response -- I love the editor!

**Comment by bpasero** [comment]
You can use the window.zoomLevel setting to zoom out more, but the ad-hoc zooming does not support that.

**Comment by leegee** [comment]
So, mousewheel-scrolling would be a feature request?

**Comment by bpasero** [comment]
Yeah, thats a valid one.
