### ISSUE TITLE
Issue reporter duplicates can cause jump when first updated

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46124]
Issue Type: <b>Bug</b>

1. Open issue reporter
2. Start typing in main text box

**Bug**
When duplicates are loaded, there is an initial jump that pushes the input box down

![mar-19-2018 11-11-40](https://user-images.githubusercontent.com/12821956/37613966-a92f1cee-2b66-11e8-9547-c897bbd2df37.gif)

VS Code version: Code - Insiders 1.22.0-insider (3a70cdfd8f84136e858b3d39e5a709e637fc35e7, 2018-03-19T06:10:23.916Z)
OS version: Darwin x64 17.4.0

**Comment by RMacfarlane** [comment]
I think what's especially jarring in this example is the amount of empty space in the similar issues section. I've changed the css to specify `max-height` instead of `height` so it only moves down enough to show that link. Let me know if there are other ways you think this could be improved
