### ISSUE TITLE
Don't complete Jquery in exten path

### ISSUE THREAD

**Issue by thanhchuongitc** [Microsoft/vscode#46122]
Issue Type: <b>Bug</b>

Don't complete Jquery in exten path

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|7.90GB (3.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|80%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
php-debug|fel|1.12.2
php-intellisense|fel|2.2.9
vscode-mysql|for|0.3.0
beautify|Hoo|1.3.0
mysql-syntax|jak|1.3.1
mssql|ms-|1.3.0

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
Please provide repo steps
