### ISSUE TITLE
Add Option for "Distraction-Free" or "Minimalistic Layout"

### ISSUE THREAD

**Issue by rockerest** [microsoft/vscode#46120]
This is *not* solved by Zen mode (and in fact the problem is partially present in Zen mode, too).

I'd like an option to remove a bunch of the buttons and/or chrome from VSCode.

That is, I'd like to never (ever) see:
1) The Activity bar (this is currently possible with ( right-click or View menu ) > Hide activity bar)
    a) The horizontal layout for the activity bar demoed [in this Mac-specific post](https://github.com/Microsoft/vscode/issues/12377#issuecomment-248674424) may alleviate a lot of this concern, but I'd also like to reduce the impact with that design (e.g. I don't need an icon tab *and* a full horizontal bar with "Explorer", "Search" etc.
2) The buttons on the Open Editors panel
3) The buttons on the Folders panel
4) The buttons on the editor panel

Images of the above (excluding 1 because it's very tall and obvious what it is):

2) ![editors](https://user-images.githubusercontent.com/277023/37607851-b3569920-2b5e-11e8-9202-6e9d64d136cd.PNG)
3) ![explorerbuttons](https://user-images.githubusercontent.com/277023/37607868-bc2031f6-2b5e-11e8-93f6-4802d90bc8b1.PNG)
4) ![editor](https://user-images.githubusercontent.com/277023/37607880-c2258100-2b5e-11e8-9558-aed5cd81f017.PNG)

These are just the ones I want to purely remove in my theoretical "Minimalistic" mode. I'm also a bit turned off by the number of visual signifiers on things like the search panel: 
![search](https://user-images.githubusercontent.com/277023/37608076-2cb03bbe-2b5f-11e8-9424-d38a63be78e6.PNG)

Here, however, I don't have a good solution offhand for how I would prefer this.

Any chance we can get a "Minimalistic Mode" in future versions of VSCode?

**Comment by fabiospampinato** [comment]
Rather than having another _non-customizable_ mode I would rather prefer if VSC added support for loading an external CSS file. 

@rockerest in case you don't already know about this, there's an [extension](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) that does just that. I'm using it for uncluttering the UI and it's working fine for me.

**Comment by rockerest** [comment]
@fabiospampinato Thanks for the recommendation, I'll check it out.

I agree that full customizability would probably be preferable, but I'm also vaguely concerned about the inability to easily onboard new users. For example, my colleagues and I often recommend editors (and accompanying settings) and it may result in decreased uptake if tweaking the UI means editing a CSS file (or something similar). I know this sounds absurd in an editor built for software developers, but that's been my experience.

Perhaps the right solution is a compromise where all of the available settings are available in a UI, but are eventually boiled down to a `user.[css|js]` file? Much like the way the user settings are represented as JSON.

This way, new users can simply be instructed "Ah, you don't want that? Just go into [this menu] and toggle the checkbox there." While power users are still able to write completely custom stylesheets and scripts.

**Comment by octref** [comment]
Left is NeoVim, right is VS Code.

I would really appreciate it if I can hide both the editor actions and the tab

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4033249/48917233-93cd0180-ee3a-11e8-850c-447d1de8a871.png">

**Comment by usernamehw** [comment]
There's this issue about hiding tabs #33607. Not sure if it's supposed to work with zen or not.

**Comment by octref** [comment]
If there's a setting and [Zen Mode speicfic setting](https://github.com/Microsoft/vscode/issues/45617) then we can make everyone happy.

**Comment by isidorn** [comment]
Closing as dup of Zen Mode specific setting and out of scope since we do not want to introduce more minimalistic layouts appart from zen mode
