### ISSUE TITLE
LogPoints action missing in command palette

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#46136]
**Expected:** 
Command to `Add LogPoints` to be presented in command palette

**Actual:**
None.

<img width="1552" alt="screen shot 2018-03-19 at 8 52 12 am" src="https://user-images.githubusercontent.com/173559/37621156-5c13f384-2b7b-11e8-98a8-2e1ff6a27f3e.png">

**Comment by weinand** [comment]
Yep, currently "Add Log Point" is only available in the gutter.
