### ISSUE TITLE
UI Issue: VS Code icon not legible when choosing apps to open unknown file types

### ISSUE THREAD

**Issue by SOM-fermonte** [Microsoft/vscode#46130]
Issue Type: <b>Bug</b>

As the subject says, if I try to open an unknown file type and select "Open with" in windows 10, the VS Code icon shows as a blu-ish box, not really recognizable.

I can send a screenshot, but this is easily reproducible. Again, this is on Windows 10

1. Create a test file, for example, called test.sha256 (it can be empty)
2. In File Explorer, locate the file and right-click it
3. Select "Open with" in the context menu
4. Scroll down in the list of apps shown in the pop-up and locate VS Code. The icon is not legible.

Finally, I believe this does not happen if the user has customized her/his Windows 10 colors. I am viewing it with the stock blue background.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|Memory (System)|7.91GB (3.99GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
oracle-plsql|myc|1.0.3

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@SOM-fermonte yes please attach a screenshot

**Comment by SOM-fermonte** [comment]
![vscode_screenshot](https://user-images.githubusercontent.com/24226837/37652823-2d9703f0-2c13-11e8-8d17-4d8c030c9b47.png)
The image above is how the icon appears with stock Windows 10 colors. As I suspected, if the user changes the accent colors for windows, the situation improves
![vscode_screenshot_after](https://user-images.githubusercontent.com/24226837/37653188-60b91b14-2c14-11e8-9a40-0004444a4849.png)

**Comment by bpasero** [comment]
@SOM-fermonte I think a full uninstall and reinstall should help here, we fixed the color a while ago but it needs an installation it seems to propagate.

**Comment by SOM-fermonte** [comment]
@bpasero ¡Gracias!
Unfortunately, I uninstalled, rebooted, downloaded, and re-installed, but no joy. Same exact result as before.
One more thing that might be a factor here. I am using a corporate PC. It has Win 10 1703.
I haven't checked this at home. I have a machine with Win 10 Insiders, I will check and report tomorrow.
Also, this machine was originally Windows 7 and I have had Code installed since version 1.0. The machine at home had it earlier.

**Comment by bpasero** [comment]
@SOM-fermonte ok, this is how it should look like:

![image](https://user-images.githubusercontent.com/900690/37662913-5e98241c-2c58-11e8-838e-13a9b34ea5c8.png)

I am closing this issue as this seems to be VS Code unrelated, rather Windows specific.
