### ISSUE TITLE
Allow to reopen recently closed windows

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46138]
Please make it possible to restore recently closed windows, with all the tabs that they contained, if they were closed with `File > Close Window`. I usually close workspaces this way, and sometimes I'd like to restore them quickly.

**Comment by bpasero** [comment]
@garyking wouldn't this be possible via File > Open Recent > More... ?

![image](https://user-images.githubusercontent.com/900690/37874783-e193fbda-3035-11e8-8a66-eb19922f56b9.png)

**Comment by garyking** [comment]
@bpasero Not exactly. When I open something with that menu, it replaces my current window, when I don't want to do that.

**Comment by bpasero** [comment]
@garyking you can hold `Ctrl/Cmd`-key to force open into a new window.

**Comment by garyking** [comment]
Oh okay, that'll do it.

**Comment by garyking** [comment]
I'm re-opening this, because I notice that the method suggested only works if I'm re-opening a closed workspace. But if the window is not a workspace, then I can't restore it with the tabs that it had open.
