### ISSUE TITLE
"Open in Terminal" does not work when window has no folders

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46139]
The "Open in Terminal" does nothing when the current window has no folders. 

Instead, if there are no folders, it should open a Terminal window in the same directory as the current file.

**Comment by garyking** [comment]
I'm using `Command Palette` > `Open New Terminal` while I have a saved file focused in VSC.

**Comment by Tyriar** [comment]
That command opens the active workspace folder currently. Maybe we should fallback to the active file if there is no folder open? Open to PRs

**Comment by mkavidas** [comment]
I would like to work on this as my first bug. Could I get some advice on how I should go about fixing this?

**Comment by Tyriar** [comment]
@mkavidas Great! All the external terminal code is located in the "execution" part https://github.com/Microsoft/vscode/tree/master/src/vs/workbench/parts/execution

You change will be in here:

https://github.com/Microsoft/vscode/blob/45bfe40a61af00eff2c03faaa63bf4656aff42c9/src/vs/workbench/parts/execution/electron-browser/execution.contribution.ts#L117-L120

Utilizing the `IWorkspaceContextService` (see [this](https://github.com/Microsoft/vscode/blob/45bfe40a61af00eff2c03faaa63bf4656aff42c9/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L136) for how to pull it into that file).
