### ISSUE TITLE
Find&Replace bar: Replace textbox is not resized 

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [microsoft/vscode#46135]
Issue Type: <b>Bug</b>

Steps to reproduce the bug:
In a vertically split editor invoke Find bar (smth like Ctrl+F), then move the vertical separator between two tabs of the editor to shrink one of the tabs to the minimum possible width, which leads to Find bar being resized. Than, click on the arrow to open Replace field. Now Find field and Replace field are of the same size. Change back the size of the editor's tab by dragging the vertical separator. The Find field grows in size as the tab's width grows. However, the Replace field does not grow. See attached images.

If at the beginning before resizing tab the Replace field is opened, then it behaves properly and resizes alongside the Find field. 

![1](https://user-images.githubusercontent.com/8782986/37620011-235cd73a-2bcc-11e8-8a81-caf6ec8ae773.JPG)
![2](https://user-images.githubusercontent.com/8782986/37620017-272b9874-2bcc-11e8-91e4-4b661307da2c.JPG)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|5.89GB (1.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|3.14.0
csharp|ms-|1.14.0
code-spell-checker|str|1.6.5
pdf|tom|0.2.0

</details>
Reproduces without extensions

**Comment by rebornix** [comment]
Already fixed.
