### ISSUE TITLE
LogPoint halts script execution for Node

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#46137]
<img width="1552" alt="screen shot 2018-03-19 at 8 54 48 am" src="https://user-images.githubusercontent.com/173559/37621212-848db804-2b7b-11e8-8110-b81296f12562.png">

LogPoint set on line 16(notice the red logpoints logo). Get's hit and execution stops

**Comment by roblourens** [comment]
Can you give me a log? (You'll have to set `"logFilePath": "/tmp/logfile1.txt"` because I broke the trace option in today's insiders).

**Comment by auchenberg** [comment]
Working in todays insiders.
