### ISSUE TITLE
Schema for locale.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4613]
Provide a schema for `locale.json`, that way the user experience will be nicer when he wants to input a language and might not know the shortcut.
I think this will especailly help since there is confusion between 2 and 3 letter language accronyms, eg DE or DEU

**Comment by dbaeumer** [comment]
@aeschli the locale.json file is living in ~/AppData/Roaming/Code - Alpha/User. Can I register a shema for this location?

**Comment by dbaeumer** [comment]
When I discussed this with @egamma and @chrisdias we actually thought a menu would be nicer. I opened #5503 to track the menu option

**Comment by isidorn** [comment]
Our menus might be getting cluttered. I would still prefer to have schema validation as this keeps a consistent story across all our settings.

**Comment by aeschli** [comment]
@dbaeumer Check out `vscode/extensions/json/package.json`: There we register `settings.json` to a schema:
```json
   {
       "fileMatch": "%APP_SETTINGS_HOME%/settings.json",
        "url": "vscode://schemas/settings"
},
```

In the case of 'settings.json' the schema is provided by the vscode schema content provider, which gets the schema from the IJSONContributionRegistry (`platform.Registry.as(jsonContributionRegistry.Extensions.JSONContribution)`).

But the url can also be a relative location in the extension or a remote HTTP url.

**Comment by dbaeumer** [comment]
@aeschli thanks.

**Comment by dbaeumer** [comment]
@aeschli I tried to get this to work but failed. Could you have a look here and advice: https://github.com/Microsoft/vscode/tree/dbaeumer/4613

**Comment by aeschli** [comment]
@did you try to add a entry to `contributes/jsonValidation` in `extensions/json/package.json` ?
