### ISSUE TITLE
HTML path quick suggestion do not trigger when typing a letter

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46145]
Steps to Reproduce:

1. In a project:
```
index.html
src/
    a.js
```

2. With `index.html`:

```js
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script src="./"></script>
</body>
</html>
```

3. In the script `src`, type `s` to create `'./s'`

**Bug**
No quick suggestions

**Comment by mjbvz** [comment]
This has the same root cause as #46142. The attribute value is considered a string so normal quick suggestions are disabled.

You can override the token type using the new `tokenTypes` grammar contribution: 95a406bd2ae73065e1f4277b6a909792aa38e87d

**Comment by octref** [comment]
Somehow I cannot load css languages after splitting the folders. Once @aeschli help me out on this I can test adding the tokenTypes for css too and close the issue.

**Comment by mjbvz** [comment]
You may want to scope 581000a to just tags where quick suggestions should be active (namely those for paths). Not sure if treating all tag values as `other` instead of `string` will cause any problems

**Comment by octref** [comment]
@mjbvz Thanks for fixing it.
I did it for css, but couldn't for less and scss.

@mjbvz For less

![image](https://user-images.githubusercontent.com/4033249/37691039-5216e214-2c6c-11e8-86ed-10adeb66dde5.png)

This does not work, still marked as `String`.
```
"tokenTypes": {
  "support.function.any-method string.quoted": "other"
}
```
This marks it as `Other`.
```
"tokenTypes": {
  "support.function string.quoted": "other"
}
```
I thought the dash was causing the problem, but I saw you are having `entity.name.function.tagged-template.js.jsx`. Any thoughts?

@aeschli SCSS grammar does not have a token type for URL function. Should I just forget about SCSS?

![image](https://user-images.githubusercontent.com/4033249/37691121-ca243464-2c6c-11e8-8ff5-af10466b897a.png)

**Comment by aeschli** [comment]
@octref I think the better fix is to add that to the package.json:
    "configurationDefaults": {
      "[html]": {
        "editor.quickSuggestions": {
          "strings": true
        }
      }
    }

Same for css.
It's not that URL are not strings. They are. It's that we also have good proposals inside strings.

**Comment by aeschli** [comment]
Look how string literals are used in HTML and CSS. They all represent values. In these values, quick suggestions should work.
I'm not a fan of word based suggestions and snippet suggestions either, but there's no reason that these do not show up in such values.

**Comment by octref** [comment]
I found these suggestions very noisy:

![image](https://user-images.githubusercontent.com/4033249/37789723-e4105604-2dc1-11e8-8675-2581fd298037.png)

> I'm not a fan of word based suggestions and snippet suggestions either, but there's no reason that these do not show up in such values.

We can leave that to the user to config. The current fix limits its scope to only string literals.
