### ISSUE TITLE
Ctr + /

### ISSUE THREAD

**Issue by lenotc** [Microsoft/vscode#46146]
Issue Type: <b>Bug</b>

after update a ctr + / not working any more

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|Memory (System)|15.89GB (11.64GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.20
LiveServer|rit|3.2.1
JavaScriptSnippets|xab|1.5.0

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
@lenotc I'm assuming you're using JavaScript?

**Comment by mjbvz** [comment]
Please provide repo steps and some example code

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/46125

**Comment by lenotc** [comment]
Yep :D
