### ISSUE TITLE
Expose found git path via the api provided by the Git extension

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#46144]
VSCode does a bunch of searching to find the git executable, and it would be great if that didn't need to be replicated if an extension wanted to also use the git executable -- for example GitLens. 😄 

Currently the Git extension provides an API, so my proposal would be to add a `gitPath` property to it.

//cc @joaomoreno

**Comment by joaomoreno** [comment]
Yeah man, this is a good first step.

But eventually, we should actually discuss exposing actual methods (#31103). Why don't we start sketching what that would look like?

**Comment by jrieken** [comment]
verified in code
