### ISSUE TITLE
With several files opened in a window with no folders, adding a folder removes all files from the window

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46140]
I have several files open in a window, and the window has no folders. I then add a folder to that window. All the files I had opened disappear. 

Instead, when adding a folder to a window, the files should remain.

**Comment by bpasero** [comment]
@garyking how do you add that folder to the window?

**Comment by garyking** [comment]
@bpasero I open the Explorer Sidebar, then I click on Open Folder.

**Comment by bpasero** [comment]
@garyking you can use File > Add Folder to Workspace to add without doing the context switch:

![image](https://user-images.githubusercontent.com/900690/37669698-cf11b56e-2c67-11e8-92d3-6d0033453f67.png)

As for the other actions, they intentionally close the window and open just that folder.

**Comment by garyking** [comment]
@bpasero Okay thanks, I suppose "Open folder" will replace the window, and "Add folder" just adds to it. The wording is understandable, then.
