### ISSUE TITLE
Feature request. Expose a RPC server to build other UI.

### ISSUE THREAD

**Issue by laibulle** [Microsoft/vscode#46147]
As a linux/mac user, I would use Visual Studio Code to edit code in Windows Subsystem for Linux and be productive in a Windows environment.

Electron apps do not work with remote X11 servers so I can't use Visual Studio Code with VcXsrv.

A solution could be to use VS code as an UI agnostic backend and build a native or web UI with it or even use a remote VS code backend instance from a local VS code installation.

I don't know if it could be done, but an RPC server could be a very nice feature.

Thank you for reading.

**Comment by mjbvz** [comment]
We just announced remote development with VS Code, check out the [blog post](https://code.visualstudio.com/blogs/2019/05/02/remote-development) for details
