### ISSUE TITLE
vscode.startDebug should take debug configuration json as argument

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode#4615]
Hello,

This request is related to https://github.com/Microsoft/vscode/issues/4607.

I need to be able to start the debugger using a configuration with a specific name.
For now, vscode can only launch the default or selected configuration.

I hope you will take my request into consideration and it will enhance vscode.

Thanks in advance for your feedback.

**Comment by Alphapage** [comment]
It would be great if we could give a json config directly, something like this:
```js
workbench.action.debug.start('{
			"name": "LaunchCustom",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/index.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"preLaunchTask": null,
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		}
');
```

And some events like:
``` 
workbench.action.debug.onDidStart((launchName)=>{});
```
-
``` 
workbench.action.debug.onDidStop((launchName)=>{});
```

**Comment by jcansdale** [comment]
Yes, being able to take a json config directly would be ideal!

**Comment by isidorn** [comment]
We have tackled this issue as part of #3789
I will leave this one open for being able to take a json config directly - which we do not support at the moment.

**Comment by isidorn** [comment]
Ok, we now allow both
`vscode.commands.executeCommand('vscode.startDebug', 'MyConfigurationName')` and something like
```
vscode.commands.executeCommand('vscode.startDebug', {
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/hello.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"preLaunchTask": null,
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null,
			"internalConsoleOptions": "openOnFirstSessionStart"
		});
```

Notice that if the passed argument is a string we will try to find the launch configuration in launch.json, if the passed argument is an object we will try to use it as a launch configuration.

Try it out on the alpha channel and let me know what you think - thank!

**Comment by jcansdale** [comment]
I'm confused about the example code above. What is the 'vscode.startDebug' command? The command I was expecting to see is called 'workbench.action.debug.start'. Was that a typo?

What my extension needs is a way to 'run' rather than 'start' the debugger with a custom configuration object. For example:

vscode.commands.executeCommand('workbench.action.debug.run', {
            "name": "Launch",
            "type": "node",

Any chance it could be tweaked so that I can do this? Your example is tantalizingly close to being perfect, but unfortunately I can't use it like that. :(

Thanks!

**Comment by isidorn** [comment]
Hi @jcansdale we have changed the name of the command to conform to our naming patterns in the API. You are not able to use it yet in the stable VSCode since this is not released yet.
But once our May release is out - some time in May you will be able to use the code snippet you wrote with just changin the command name.

Hope that makes sense

**Comment by jcansdale** [comment]
Will I be able to use it with 'workbench.action.debug.run' as well as 'workbench.action.debug.start'?

I was hoping to try it using the VS Code 'Insiders' version, see it is only currently on the 'alpha channel'. I'll give the alpha version a try. :)

**Comment by jcansdale** [comment]
I see the insiders channel is being retired. Where can I find 'Alpha' channel builds?

Thanks!

**Comment by isidorn** [comment]
Alpha channel will be announced soon. @chrisdias can provide more info

**Comment by jcansdale** [comment]
Thanks, I'll ping @chrisdias. What about support for 'workbench.action.debug.run' (as opposed to '...debug.start')? That is the major issue for me.

**Comment by isidorn** [comment]
No, `workbench.action.debug.run`is not public api and should not be used.
Why don't you just use a different string?

**Comment by jcansdale** [comment]
I'm confused. How do you mean it's not public api? It's the command that is by default associated with "ctrl+f5". Are you saying there is a way to get similar behavior to "ctrl+f5" by passing a string to another command?

**Comment by isidorn** [comment]
Sorry for the confusion, I misread the string you posted.
I can also look into adding `vscode.startDebugWithoutDebugging`, created #6425

**Comment by Alphapage** [comment]
I tested vscode.startDebug and it is working great, but I found only 2 little problems:
- you can't restart the configuration submitted when using a custom one which is not listed in launch.json
- the debug panel is not enabled, so you need to click and enable debug console manually

Do you plan to implement those features ?
Thankyou very much anyway for the api.

**Comment by isidorn** [comment]
When you say restart what do you mean - clicking on the restart button does not restart the session - if that is the case then it is a bug and please file a seperate issue.
The debug panel behavior has changed in the latest release, we have intoduced an options to control this, please check it out
https://code.visualstudio.com/Updates#_debugging

**Comment by atian25** [comment]
@isidorn 
how could I get `startDebug` state? 
get notification when the debug process is dead. So I can restart it.

**Comment by isidorn** [comment]
@atian25 can you please provide more details? What are you trying to do - are you writing an extension? Your extension can be activated on event: 'onDebug:TYPE' where TYPE is for instance `node`. Currently we do not have any notifications when the debugged process dies, for that please file a feature request so we consider to add this in the future.

**Comment by atian25** [comment]
just want to find workaround for cluster debug.

our framework will start 3 process, named master/agent/worker, and worker will reload when file change.

so I want to write an extendsion to auto detect worker's new debug port and auto attach to it.

**Comment by isidorn** [comment]
This sounds like a scenario which we do not support at the moment. Please create a new issue with the feature request - extension should be able to react on debuggee terminated
