### ISSUE TITLE
Undoing several newlines should  undo them all together (or whichever was added at the same time)

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#46152]
In a document, add several line breaks with `Enter`. Then hit `Cmd-Z` to undo them. They will undo one at a time, but they should instead all be removed at once.

**Comment by alexandrudima** [comment]
Thank you for the suggestion, but I don't agree. I believe that the current behaviour (where <kbd>Space</kbd> and <kbd>Enter</kbd> introduce undo/redo stops) is better than the one proposed (where <kbd>Enter</kbd> would not introduce undo/redo stops).

**Comment by garyking** [comment]
What about a middle ground, where multiple Enters in a row would act as a single undo step?
