### ISSUE TITLE
Run all unit test files

### ISSUE THREAD

**Issue by saadshams** [Microsoft/vscode#46157]
vs code only runs Program.fs in unit tests

Using VS Code to run .net core app and ms unit tests.  I've couple of unit tests files along with default Program.fs thats provided as default file. If I put breakpoint on this line, it works but not in any of the other unit test files.

`module Program = let [<EntryPoint>] main _ = 0`

Output:

> The program '[3910] MyProject.Tests.dll' has exited with code 0 (0x0).

Seems like vs code only executes one unit test file, Program.fs in this case. In my fs proj I've references to the other files as well, how can I have the other unit test files run as well.

 <ItemGroup>
    <Compile Include="AuthenticationTests.fs" />
    <Compile Include="Content\EntityTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

- VSCode Version: 1.21.1
- OS Version:  Mac 10.13.3

Steps to Reproduce:

1. Create couple of test files within .net core project f#
2. Run tests. vs code only runs Program.fs in unit tests

Does this issue occur when all extensions are disabled?: NA

**Comment by Tyriar** [comment]
This is up to the F# extension to do this.
