### ISSUE TITLE
I am getting this "A JavaScript error occurred in the main process" whenever i am trying to start Visual Studio Code. Help me out in resolving this.

### ISSUE THREAD

**Issue by abhisaa** [Microsoft/vscode#46159]
![capture](https://user-images.githubusercontent.com/37569611/37638087-1808c58c-2c31-11e8-8426-6cdaf9625de9.JPG)

Please help me.

**Comment by bpasero** [comment]
@abhisaa try to fully uninstall and reinstall VSCode
