### ISSUE TITLE
File open from Sidebar always overrides current opened file

### ISSUE THREAD

**Issue by mayurm-virtueinfo** [Microsoft/vscode#46158]
Issue Type: <b>Feature Request</b>

Hi,
Whenever i open file from side bar and click to any file, current already opened file is closed and opens clicked file from side. That should not be happened. Follow Android Studio Concept for this.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 3.13.0-139-generic

**Comment by bpasero** [comment]
Try with: `"workbench.editor.enablePreview": false`
