### ISSUE TITLE
Please uninstall the 32-bit version of Code while installing this 64-bit version

### ISSUE THREAD

**Issue by rzhou10** [Microsoft/vscode#46155]
Trying to reinstall VSCode after it failed to update, and now it says that I have the 32 bit installed even though I don't have it

- VSCode Version: Latest? Trying to re-install it.
- OS Version: Windows 7

Steps to Reproduce:

1. Attempted steps in here: https://github.com/Microsoft/vscode/issues/37584
2. After that did not work, attempted to delete any folders/reference to VSCode
3. Tried to reinstall VSCode (64 bit), still claims that 32 bit is installed

**Comment by joaomoreno** [comment]
Do a full search in your Registry for `F8A2A208-72B3-4D61-95FC-8A65D340689B`. Can you find it?

**Comment by rzhou10** [comment]
Deleting it worked, thanks.
