### ISSUE TITLE
Couldn't input Chinese in Ubuntu16.04 with fcitx

### ISSUE THREAD

**Issue by chengsluo** [Microsoft/vscode#46151]
Issue Type: <b>Bug</b>

It's ok in previous version

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.73GB (1.10GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.14.0
beautify|Hoo|1.3.0
vscode-docker|Pet|0.0.25
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
scala|dal|0.0.5
vscode-eslint|dba|1.4.7
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.3
code-runner|for|0.9.3
mdmath|goe|2.2.1
Scala|itr|0.1.7
search-node-modules|jas|1.3.0
intellij-idea-keybindings|k--|0.2.21
node-module-intellisense|lei|1.5.0
Go|luk|0.6.77
python|ms-|2018.2.1
cpptools|ms-|0.15.0
debugger-for-chrome|msj|4.2.1
java|red|0.21.0
python|tht|0.2.3
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|1.1.0

</details>
Reproduces without extensions

**Comment by karataliu** [comment]
Could you please also provide your fcitx version?
Does fcitx work in other applications, such as browsers and editors?

**Comment by chengsluo** [comment]
my input software if Sougou Pinyin actually.
my fcitx version is 4.2.9.1.
input method can work in other applications normally.

**Comment by chengsluo** [comment]
when I install google pinyin : 
```
Start-Date: 2018-03-21  13:34:32
Commandline: apt-get install fcitx fcitx-googlepinyin im-config
Requested-By: chengs (1000)
Install: fcitx-googlepinyin:amd64 (0.1.6-3), libgooglepinyin0:amd64 (0.1.2-4, automatic)
End-Date: 2018-03-21  13:34:33
```
and set fcitx seting again by:
```
im-config
```
just do normal process ,and all input methods could use again.

I think just need use 'im-config' set again could solve the problem.

This issue could be closed.
