### ISSUE TITLE
Debug REPL lost coloring for escape sequences

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4616]
I no longer see the REPL coloring output nicely. E.g. for the extension test run. 

Before:

![screen shot 2016-03-23 at 15 19 35](https://cloud.githubusercontent.com/assets/900690/13988092/b67fc47c-f10a-11e5-8157-84afa52a0efe.png)

After:

![screen shot 2016-03-23 at 15 19 31](https://cloud.githubusercontent.com/assets/900690/13988098/bca80ee0-f10a-11e5-9a36-b449304453cf.png)

**Comment by isidorn** [comment]
Due to #3006 I was removing all ansi escape codes, now I am no longer doing that.
There is a workaounrd for #3006 - use an external console so I decided to not remove any ansi escape code now

**Comment by bpasero** [comment]
Yeah, don't remove them all, we support the colors at least!

**Comment by isidorn** [comment]
It was a stupid regression - maybe I should push this on top of 1.0 branch since it is a regression and it is a low risk fix?

**Comment by bpasero** [comment]
I think its not a 1.0 candidate since the user does not loose anything from the regression.

**Comment by bill-mybiz** [comment]
@bpasero I am not sure what y'all mean when you say a 1.0 candidate. I noticed this currently in the insiders release. Will this be fixed before the next actual release after 0.10.11?

**Comment by bpasero** [comment]
@bill-mybiz will be fixed post 1.0 release, end of March likely.

**Comment by bpasero** [comment]
And you can always configure to use an external console in the launch.json to get the full ASNI support in.

**Comment by bill-mybiz** [comment]
@bpasero It sounds like it will be fine to use the external console. I'm still at a loss as to the 1.0 timeline...VS code is going from 0.10.11 to 1.0? Also, you are aware it is the end of March already? :-O 

Regardless, I really appreciate all of the VS Code team's hard work and actively addressing issues such as these. :+1:

**Comment by bpasero** [comment]
@bill-mybiz sorry, I meant to say "end of April". We plan to release 1.0 (our next release) later in April, but have closed already for fixes.

**Comment by amejias101** [comment]
is it me or is this still an issue? I see that it is closed but I still experience it, even with the current nightly version

**Comment by isidorn** [comment]
Just checked and this particular issue seems to work fine. Though VSCode debug console has issues regarding the colorizing of ansi characters - you can search previous bugs to find more details regarding [this](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20debug%20console%20color%20).
