### ISSUE TITLE
Cannot attach debug process to node 8.1 but can with 6.11

### ISSUE THREAD

**Issue by rsouthgate** [Microsoft/vscode#46167]
Issue Type: <b>Bug</b>

Using the following launch.json:

```
{
      "type": "node",
      "request": "attach",
      "address": "192.168.99.100",
      "name": "Attach to Minikube xxx service",
      "port": 30006,
      "localRoot": "${workspaceFolder}/xxx",
      "remoteRoot": "/usr/src/app",
      "protocol": "inspector"
    },
    {
      "type": "node",
      "request": "attach",
      "address": "192.168.99.100",
      "name": "Attach to Minikube yyy service",
      "port": 30007,
      "localRoot": "${workspaceFolder}/yyy",
      "remoteRoot": "/usr/src/app"
    },
}
```
The first service is in a docker container (on minikube) from Node 8.1.3. This second is a docker container from Node 6.11.4.

The pod logs for the first show node starting:
```
[nodemon] starting `node --inspect=5898 ./bin/www`
Debugger listening on ws://127.0.0.1:5898/b74965a0-8a0a-4dc1-be0c-f05697b41de5

```
The second:
```
[nodemon] starting `node --inspect=5898 ./bin/www`
Debugger listening on port 5898.
```

I have tried with and without the inspector protocol explicitly set in launch.json.
In both deployments port 5898 is configured to route to 30006 and 30007. The only change is the node version.

I maybe wrong but I'm assuming the random UUID that node now adds to the debug endpoint is preventing the connection... the docs seem to indicate it is available on /json/list though I'm not sure how of if VS Code is attempting to retrieve it. 

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-commitizen|Kni|0.5.0
vscode-docker|Pet|0.0.25
vscode-eslint|dba|1.4.7
php-debug|fel|1.12.2
local-history|gay|0.0.3
ginfuru-vscode-jekyll-syntax|gin|0.0.5
vscode-jekyll-snippets|gin|0.8.7
vscode-styled-components|jpo|0.0.16
vscode-todo-parser|min|1.9.1
vscode-extension-auto-import|mop|1.3.3
python|ms-|2018.2.1
debugger-for-chrome|msj|4.2.1
language-liquid|nei|0.0.3

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
What happens when it fails to attach? Do you see an error messages?

Can you set `"trace": true`, run the config that fails, and upload the log here?

**Comment by rsouthgate** [comment]
Error is 
`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 192.168.99.100:30006).`

And verbose log seems to indicate it is trying to discover the UUID from the /json/lists:

```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.23.0
18:00:03, 2018-3-21
node-debug2: 1.21.2
From client: initialize({"clientID":"vscode","adapterID":"node2","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"clientRequest/initialize","data":{"requestType":"request","successful":"true","timeTakenInMilliseconds":"1.589179"}}}
From client: attach({"type":"node2","request":"attach","address":"192.168.99.100","name":"Attach to Minikube User / Agent / Teacher service","port":30006,"localRoot":"/Users/robin/Documents/Workspaces/Substiteach/substiteach/backend/services/user","remoteRoot":"/usr/src/app","protocol":"inspector","trace":true,"cwd":"/Users/robin/Documents/Workspaces/Substiteach","logFilePath":"/Users/robin/Library/Application Support/Code/logs/20180313T202509/ms-vscode.node-debug_1/debugadapter.txt","__sessionId":"61dcffb9-c132-4292-8ca4-7b6dc347ddca"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"request":"attach","args":["type","request","address","name","port","localRoot","remoteRoot","protocol","trace","cwd","logFilePath","__sessionId","sourceMapPathOverrides","showAsyncStacks","sourceMaps"]}}}
Discovering targets via http://192.168.99.100:30006/json/list
HTTP GET failed: Error: connect ECONNREFUSED 192.168.99.100:30006
(last 2 lines repeated for the 10 seconds)
```

Would appear to not be an issue with VS Code and something upstream since that endpoint is inaccessible via curl just as VS Code states. Unless this screams something to you feel free to close this as I'm assuming the issue is upstream.

**Comment by roblourens** [comment]
If you can't load `http://192.168.99.100:30006/json/list` in a browser (or with curl), then the debug adapter can't access it either. Thanks for trying curl. I would assume that the port is not accessible or the IP address is wrong, or something else like that.

**Comment by rsouthgate** [comment]
For anyone who stumbles across this...

Node has changed inspector bindings from 0.0.0.0 to 127.0.0.1 which means when going via a container running in something like minikube you can't reach the debug port. Solution is to use --inspect=0.0.0.0:portNumber as opposed to just --inspect=portNumber and node-inspector will bind as before.

**Comment by roblourens** [comment]
Thanks for the follow up!
