### ISSUE TITLE
NodeBB + VSCode Debugging - Breakpoints not working

### ISSUE THREAD

**Issue by reliasn** [Microsoft/vscode#46160]
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

NodeBB is a Node.js forum platform. To extend it, you can add plugins to its ``node_modules`` folder, for example, ``node_modules/nodebb-plugin-mychat``.

When I place a breakpoint on NodeBB's ``app.js``, it breaks fine. But if I place a breakpoint on my ``node_modules/nodebb-plugin-mychat/library.js``, it doesn't work. I remember I had this issue in the past and that I had to mess with the ``launch.json`` file in order to get it working. I simply couldn't find the solution again so if someone could help me out on this, I'd appreciate it. This is my ``launch.json``:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\app.js",
            "console": "integratedTerminal"
        }
    ]
}
```

Some console logs:
```
PS D:\Desktop\openshift\NodeBB> cd 'd:\Desktop\openshift\NodeBB'; & 'node' '--inspect-brk=4648' 'app.js'
Debugger listening on ws://127.0.0.1:4648/228491de-ee5a-4d9c-ab0b-218864a27f3f
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
2018-03-20T06:53:37.550Z [561032] - info: NodeBB v1.8.0 Copyright (C) 2013-2018 NodeBB Inc.
```

**Comment by lostfields** [comment]
#45657

**Comment by reliasn** [comment]
I remembered what I had done. Fixed the issue with [this](https://github.com/Microsoft/vscode/issues/9158#issuecomment-292140375).

Basically my NodeBB plugin is a junction symlink:
![](https://i.imgur.com/Jq29DZM.png)

So I had to add the following to my ``launch.json``:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\app.js",
            "console": "integratedTerminal",
            "runtimeArgs": [
                "--preserve-symlinks"
            ]
        }
    ]
}
```
Debugging works well now.
