### ISSUE TITLE
Ctrl+Shift+O should not sort imports

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#46168]
That keyboard short cut is already bound to Go to Symbol in File and we shouldn't break this.

**Comment by mjbvz** [comment]
Yes, missed that this is already bound on windows. Will change to alt+shift+o which is similar to format's  shift+alt+f

**Comment by mjbvz** [comment]
Java already has a keybinding for this and doesn't set a `when` clause. I'll open an issue against them
