### ISSUE TITLE
Debug Adapter process has unexpectedly terminated

### ISSUE THREAD

**Issue by Tiancityrua** [Microsoft/vscode#46166]
- VSCode Version:1.21.1
- OS Version:Windows_NT x64 10.0.14393.1480

Steps to Reproduce:

1.when I run a python program
2.vscode show me "Debug Adapter process has unexpectedly terminated"

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python
