### ISSUE TITLE
vscode.ViewColumn doesn't work as expected

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode#46161]
- VSCode Version: 1.21.1
- OS Version: Microsoft Windows [Version 10.0.16299.248]

Steps to Reproduce:

1. install [Visual Studio Code Tools for AI](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-ai)
2. Ensure no document open
3. Execute `AI: Open Azure ML Sample Explorer` twice
4. Two Azure Machine Learning Sample Explorer will open

![snipaste20180320_142354](https://user-images.githubusercontent.com/1621293/37638938-59d637a6-2c4a-11e8-8371-6401cd6f5039.png)

Does this issue occur when all extensions are disabled?: N/A

---

This issue is cause by `vscode.ViewColumn.Two`. When we want to open a document in the second column, the first column should exist, and if there is no column, the document will open in the first column, even if we are clear to open it with `vscode.ViewColumn.Two`. I believe this is as design, but it doesn't make sense.

What I expect is, when there is not column, the document will also open in the second column, and the first column is hidden, but not replace the second column with the first one.

**Comment by jrieken** [comment]
> What I expect is, when there is not column, the document will also open in the second column, and the first column is hidden, 

Not sure what that means? Do you want an empty first column?

**Comment by jrieken** [comment]
> When I open a document in the second column vscode.ViewColumn.Two, then it should really open in the second column.

The workbench currently cannot do that as columns are not static but dynamically added while editors are opened. 

You should be looking at #45994 which is about improving the webview-api and which will let you know in which column the webview currently shows. 

Assigning @bpasero for the static workbench layouts

**Comment by bpasero** [comment]
Allowing arbitrary editor layouts is covered in https://github.com/Microsoft/vscode/issues/2755

**Comment by Sneezry** [comment]
Emmm, I do not agree this issue is duplicate with #2755. As an extension developer, I cannot ask my users to change their vscode config to make the extension work as expected.
