### ISSUE TITLE
background插件与vscode不兼容

### ISSUE THREAD

**Issue by Svip9** [Microsoft/vscode#46164]
Issue Type: <b>Bug</b>

安装vscode后下载并安装background插件，然后vscode报内部文件损坏。

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by imba-tjd** [comment]
![image](https://user-images.githubusercontent.com/24759802/37656823-1899fe32-2c84-11e8-8176-9b5b33a92fb5.png)

It's not a Bug. The author had already told you what would happen. Modify VSC is deprecated.

**Comment by Tyriar** [comment]
@Svip9 as @imba-tjd mentioned, this is as designed, you corrupted the install. You should reinstall VS Code.

**Comment by Svip9** [comment]
非常感谢你们的解答！
