### ISSUE TITLE
Unable to Reopen after crash

### ISSUE THREAD

**Issue by rajsharma1612** [Microsoft/vscode#46173]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
![screen shot 2018-03-20 at 19 48 39](https://user-images.githubusercontent.com/11499534/37650275-d48bd866-2c77-11e8-93d4-b5a352f034d7.png)

2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
@rajsharma1612 what happens when you run `code --verbose` from the command line to launch?
