### ISSUE TITLE
Terminal does not display expo qr code

### ISSUE THREAD

**Issue by Goodmedalist** [Microsoft/vscode#46178]
Issue Type: <b>Bug</b>

When running a react native app using npm start, it generates a qr code for the expo app. This code is visible when running in a normal command window, but is just an empty space when started in the integrated terminal window. I suspect that the qr code is ascii art. Can you fix this or is this something expo must fix?

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A12-8800B R7, 12 Compute Cores 4C+8G    (4 x 2096)|
|Memory (System)|15.42GB (8.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-eslint|dba|1.4.7
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.15
node-debug2|ms-|1.22.3
color-highlight|nau|2.3.0
prettier-vscode-with-tabs|pas|1.1.0
vscode-icons|rob|7.21.0
code-settings-sync|Sha|2.9.0
vscode-react-native|vsm|0.6.6

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/32648
