### ISSUE TITLE
Typescript intellisense dies when recreating a file

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#4617]
- VSCode Version: 0.10.12-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder with a typescript file in it.
2. Verify the full range of completion options.
3. Delete the file.
4. Create a new file with the exact same name.
5. The completion popup only contains basic keywords or `No suggestions` now, depending on cursor placement.

Here's a sample file to copy/paste:
```typescript
// fruit.ts

'use strict';

class Fruit {
  protected name: string;
  public getName() {
    
  }
}
```

**Comment by dbaeumer** [comment]
I can reproduce this. Debugging shows that the tsserver returns:

"Error processing request. Cannot read property 'lineCount' of undefined"

VSCode when deleteing the file send a close request to the server. On recreating we send a open with an empty content and when pasting in the content a content change event.

Moving to TS.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7668
