### ISSUE TITLE
Uri.file(x).fsPath lowercases drive letter

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#46172]
This code:

```ts
console.log(Uri.file("M:\\Test").fsPath);
```

outputs:

```text
m:\Test
```

There have been a lot of cases over the last few months about casing of Windows driver letters breaking things and the conclusion was generally that things should be normalised to uppercase. I don't know if that's valid here, but it should at least preserve the casing of the drive letter from the input.

**Comment by jrieken** [comment]
Yeah, we made that (arguable arbitrary) choice and it's too late to change it now. If I remember correctly we did that because of Omnisharp and how drive letter are normalised there.

**Comment by DanTup** [comment]
@jrieken What about some opt-in way of not messing with it? Since drive letters are being normalised to uppercase elsewhere, this puts quite a burden on extension devs - if our path gets converted to a Uri at any point and then we read the `fsPath` back, we've got a path that's not the same (I know ideally all path-comparisons should be case-sensitivity aware, but that's another can of worms).

I'd happily call an overloaded Uri.file() to preserve this.

Alternatively, given the other changes to normalise to uppercase, maybe Omnisharp devs may have a different opinion about this now? It seems weird to normalise in two different directions within Code's code.

(again, I'm not saying you need to normalise to uppercase, just preserving the input you were given would be fine IMO.. let the user deal with *all* of the normalisation and just keep what you get)

**Comment by DanTup** [comment]
To be fair, I now see this behaviour is quite explicitly called out in the docs on the fsPath property! ;(
