### ISSUE TITLE
"Open Folder" dialog is prefilled with non-existent "lib" folder

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#46174]
This has been bugging me for days and I can't figure out where it's coming from. I'm debugging my extension in the dev host and when I click "Open Folder" it defaults to the last folder I opened, but the box at the bottom is prefilled with `lib` (which doesn't exist). This means I can't just hit `<enter>` but have to clear the text first.

I tried clearing my recent list but it still persists.

![lib](https://user-images.githubusercontent.com/1078012/37650499-04f2e846-2c2d-11e8-8051-d508b51851a0.gif)

**Comment by bpasero** [comment]
@DanTup I have no clue what could trigger this other than suspect a Windows issue.

**Comment by bpasero** [comment]
@DanTup actually we seem to prefill a default path, can you add a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/actions/workspaceActions.ts#L59) and see what the default path resolves to?

**Comment by DanTup** [comment]
@bpasero What's the correct way to do that? I tried opening dev tools, finding it in the file and adding breakpoints (I added a bunch) but they don't seem to be hit.

![bps](https://user-images.githubusercontent.com/1078012/37658409-5b94e72c-2c45-11e8-9de6-110979b39eab.png)

**Comment by bpasero** [comment]
@DanTup that is weird, maybe a different action gets executed, we can start one level before here maybe: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/emptyView.ts#L63

**Comment by DanTup** [comment]
Not hitting that either :( I opened emptyView.ts using Ctrl+P and when I added a breakpoint there, it jumped me over the the JS (where I'd already placed a BP), so seems it's not hitting them set from JS or TS. Breakpoints are definitely active :/

I tried searching through Local Storage in the dev tools and found lots of paths around this folder, but none that have `lib` directly have flutter (with either slash, single or doubled). Do you know where it's intended to get it from?

**Comment by bpasero** [comment]
@DanTup did you maybe disable sourcemaps in dev tools? For me the breakpoint gets hit once I click on the button:

![image](https://user-images.githubusercontent.com/900690/37662833-3fe87fbc-2c58-11e8-9f0e-ca254849b894.png)

**Comment by DanTup** [comment]
Aha, I think prettifying the JS view was breaking it - opening the .ts file first worked.

Here's the path that's being passed - this path does not not exist anymore - I guess it's using the last part of it still!

![lib path](https://user-images.githubusercontent.com/1078012/37665498-50cdc074-2c55-11e8-8959-9256742fd984.png)

And here's a search through local storage for `hhhhhhhh`.. This doesn't show on the File -> Open recent list though.

![storage](https://user-images.githubusercontent.com/1078012/37665535-66ba9524-2c55-11e8-82c3-2e93ec110b6a.png)

I guess a fix could be to ensure paths exist before using them as default locations for the Open dialog?

**Comment by bpasero** [comment]
@DanTup can you open a file and then run these steps again? I think we have some code that uses a path based on the last active file that was opened. That could be it.

**Comment by DanTup** [comment]
Yeah, I opened another file then closed gracefully and it's stopped happening. I guess mostly the dev host just gets terminated by my hitting Restart/Stop in the main Code instance so it doesn't update.

**Comment by bpasero** [comment]
I pushed a fix to check for existence of the dialog default path before showing the dialog and otherwise not setting the path at all.
