### ISSUE TITLE
The comment in locale.json does not change from Chinese to English after changing locale from "zh-cn" to "en"

### ISSUE THREAD

**Issue by shizengzhou** [microsoft/vscode#46179]
Issue Type: <b>Bug</b>

1. Configure language, change locale from "zh-cn" to "en"
2. Restart vscode
![locale](https://user-images.githubusercontent.com/24318019/37655526-93bfe0c6-2c80-11e8-943a-78fb411d01a0.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|7.89GB (1.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by dbaeumer** [comment]
@shizengzhou any reason why you closed the issue and the PR

**Comment by shizengzhou** [comment]
@dbaeumer In the latest VS Code Insiders, I find there is no comment in locale.json, so I think the issue and the PR are no longer needed.
![locale](https://user-images.githubusercontent.com/24318019/39218044-288272c4-4855-11e8-95af-a534ce0fc1f6.png)

**Comment by dbaeumer** [comment]
@shizengzhou could it be that you deleted the comments. We still generate it when we create the file for the first time. See here:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/localizations/electron-browser/localizationsActions.ts#L23

**Comment by shizengzhou** [comment]
@dbaeumer Yeah, I saw the code. My latest VS Code Insiders is a new installation, I didn't delete the comments. I will reopen the issue and the PR.

**Comment by blackmarkCH** [comment]
so,your issue is solved?now,i can't change "en" to "zh-cn".
=.=b 
My ver is 1.27.1.

**Comment by bpasero** [comment]
We no longer surface this file to the user, closing.
