### ISSUE TITLE
Excessive file activity in appInsights-node

### ISSUE THREAD

**Issue by evil-shrike** [microsoft/vscode#46189]
I noticed lots of file in my user profile inside.
It turned out that all these files are created by VSCode:
![image](https://user-images.githubusercontent.com/1203230/37665813-227f65fa-2c6f-11e8-9b6f-ff10c781a1a2.png)

I just left VSCode opened for a couple of days and it poluted 650MB!
![image](https://user-images.githubusercontent.com/1203230/37665854-3a26ad58-2c6f-11e8-89ea-56b43ca3949d.png)

**Comment by sbatten** [comment]
either no longer an issue or fixed upstream
