### ISSUE TITLE
c++ debugger not working json error 1.21.1

### ISSUE THREAD

**Issue by mortinger91** [Microsoft/vscode#46185]
Issue Type: <b>Bug</b>

main.cpp file containing c++ "hello world" c/c++ official extension. create default build task.json containing command "g++ main.cpp" and lauch.json with command "{$workspacedir}/a.out". build works, debug fails with "json error at line 5 {". Also using "Native Debug" extension but bug happens anyway if if uninstalled.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.15.0-1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD E1-2500 APU with Radeon(TM) HD Graphics (2 x 928)|
|Load (avg)|1, 0, 0|
|Memory (System)|7.24GB (0.47GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.2
php-intellisense|fel|2.3.0
php-pack|fel|1.0.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
cmake|twx|0.0.17
cmake-tools|vec|0.10.4
debug|web|0.21.2

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
