### ISSUE TITLE
End Key moves cursor in IntelliSense instead of in the editor

### ISSUE THREAD

**Issue by lafe** [Microsoft/vscode#46182]
- VSCode Version:
```
Version 1.22.0-insider
Commit 5be9e9e7eef715539efd5341fdbc8ec5840cfc56
Date 2018-03-20T06:17:19.168Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
- OS Version: Windows Server 2008 R2

Steps to Reproduce:

![end key issue](https://user-images.githubusercontent.com/4070008/37655844-a78756a0-2c46-11e8-959d-2f13c7a048f8.gif)

1. Open a TypeScript file
2. Write a null check for a variable (`if(abc == null)`) by first writing `if()` and then filling the condition
3. When the inner statement (`abc == null`) is complete, IntelliSense still displays suggests auto-complete elements for null
4. Pressing END on the keyboard to jump to the end of the line, does jump to the end of the IntelliSense list instead of to the end of the line

Normal expectation for me is that the editor dismisses the IntelliSense menu when the END key is pressed and jumps to the end of the line. This behavior was the default in previous versions of VS Code (tested with an older Insider version of 1.21) and is also the same in Visual Studio 2017. Furthermore, it is muscle memory, so I am constantly running into this issue.
I suspect that #43511 is the reason for this new behavior. I hope that the old behavior can be restored or that the behavior is configurable.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I think this is as designed?

**Comment by lafe** [comment]
In my opinion this is not as designed as the behavior has been introduced with #43511 (which was not marked as a bug by @jrieken but as a feature request). It is also not consistent with the experience of the full Visual Studio where the "end" key also does not trigger anything in the IntelliSense dialog.
For me, this issue is currently very frustrating and the opposite of the "Happy Coding" goal that is stated on the Roadmap page, as VS Code interrupts the normal coding experience with an unintuitive and uncommon behavior. In my opinion, the best approach would be to make this setting configurable through the keybindings, so that users can configure IntelliSense as they like.

**Comment by jrieken** [comment]
>  In my opinion, the best approach would be to make this setting configurable through the keybindings, so that users can configure IntelliSense as they like.

Yes, you can unbind the keybinding. 

I have closed this as dupe to have the discussion in one place - IMO it makes sense bring pro-people and con-people onto the same issue. Leaving the default untouched as long as not too many people complain.
