### ISSUE TITLE
Python3 write to file encoding

### ISSUE THREAD

**Issue by elmcrest** [Microsoft/vscode#46186]
Issue Type: <b>Bug</b>

```Python
unicode_string = """
hello visual studio code 😎😆😱
"""

with open("testfile.txt", "w") as output:
    output.write(unicode_string)
```
leads to
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-28: ordinal not in range(128)
```

if you add the encoding type to the file context, it works. `with open("testfile.txt", "w", encoding="utf-8") as output:`

If you run the snippet from your regular terminal outside of visual studio code, python defaults as expected to "utf-8" as the encoding.

so I'm not really sure if the Python Extension does this wrong somehow, but it's reproducible so I guess it's worth to become an Issue :)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.10.0
xml|Dot|1.9.2
tslint|eg2|1.0.28
RunOnSave|eme|0.0.16
python|ms-|2018.2.1
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.2.1
sass-indented|rob|1.4.8
latex-support|tor|1.5.1

</details>

**Comment by Tyriar** [comment]
@DonJayamanne do you think this is related to the Python extension?

**Comment by DonJayamanne** [comment]
@elmcrest 
* How are you running the above block of code?
* What version of Python have you configured for use in VS Code
    * Open a python file
    * The version of python used by VS Code will be displayed at the bottom left (status bar)

**Comment by elmcrest** [comment]
hey @DonJayamanne 

I've setup to use my virtualenv Python, so Python 3.6.4 in this case - and that's also what VS Code displays at the bottom left

I run the code via the debugger config "current file (venv)"

let me know if I can help any further

**Comment by DonJayamanne** [comment]
@Tyriar 
This is a python extension issue.

**Comment by elmcrest** [comment]
ok sure

@DonJayamanne https://github.com/Microsoft/vscode-python/issues/1130
