### ISSUE TITLE
Replace all in selection

### ISSUE THREAD

**Issue by RolandLeFranc** [Microsoft/vscode#46184]
Issue Type: <b>Feature Request</b>

Replace all in selection is missing.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
You can enable "Find in selection" with the button on the find widget, then do a replace all, and it will only take effect within the selection. Provide more details if that's not what you mean.
