### ISSUE TITLE
The width of the panel item is incorrect

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#46180]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Set `"workbench.tree.horizontalScrolling": true` in settings
2. Show PROBLEMS and then open a file that has any problems
3. bug

![bug2](https://user-images.githubusercontent.com/8474118/37657108-6688bb7a-2c8d-11e8-83fc-846015438945.gif)

VS Code version: Code - Insiders 1.22.0-insider (5be9e9e7eef715539efd5341fdbc8ec5840cfc56, 2018-03-20T06:17:19.168Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|Memory (System)|7.95GB (2.30GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\Csoft\Desktop\test|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
HTMLHint|mka|0.4.0
markdown-preview-enhanced|shd|0.3.4

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by EbXpJ6bp** [comment]
@vscodebot
that problem was opened by me :)

**Comment by bpasero** [comment]
@joaomoreno so it begins!!!
