### ISSUE TITLE
Enhanced support for rest params

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#4618]
I'd look to add better support for rest params and need some guidance. This would be my first contribution to the code base. It looks like Intellisense only works for the first param. Say I have the following interface:

```
declare module 'bar' {
  /**
   * Only shows rest params.
   * @param params Optional params.
   */
  export function foo(...params: any[]): void;
}
```

And use it like this:

```
import * as bar from 'bar';

bar.foo(1, 2);
```

For `1` I'd get a correct hint showing the documentation `...params: any[] Optional params.`. For `2` I'd expect to get the same hint, but nothing shows up currently.

**Comment by jrieken** [comment]
Assigning @dbaeumer  to see if we do anything wrong here. It might be the TypeScript language server we use

**Comment by dbaeumer** [comment]
Here is what I see on latest:

![bug](https://cloud.githubusercontent.com/assets/1931590/14012363/993dfad2-f1a5-11e5-91d2-2bf1c76fce34.gif)

So it looks the that params hints come correctly from the tsserver however our highlighting is off since it doesn't know anything about ...

Moving to @joaomoreno who owns the widget.

**Comment by donaldpipowitch** [comment]
It isn't just the highlighting, but the description text, too. I don't know if it boils down to the same feature. This this will be solved internally...?

**Comment by joaomoreno** [comment]
@donaldpipowitch This would definitely make for a great first contribution!

**Comment by donaldpipowitch** [comment]
Thanks. Could you give me some hints or big picture where I should look at?

**Comment by joaomoreno** [comment]
Sure. But now that I took a closer peek, this feels like it will go to the TypeScript people.

The parameter hints provider should be returning to us an [`IParameterHints` object](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/parameterHints/browser/parameterHintsModel.ts#L78) which contains information about the signature as well as [the current parameter](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes.ts#L420).

I have a feeling that TS is returning something like *this method got 1 (rest) argument and you're on the third parameter*. Which would be wrong. It should return something like *this method got 1 (rest) argument and you're on the first parameter*.

As one adds more parameters to a rest argument, the `currentParameter` should not change, IMO. Do you agree @dbaeumer?

**Comment by dbaeumer** [comment]
@joaomoreno: actually the TS protocol contains the information about rest arguments. They have a isVariadic property on the SignatureHelpItem. May be we should expose something like this in our API. Simply saying we are on the first parameter is not correct from a caller perspective.

**Comment by dbaeumer** [comment]
We could for example extend ParameterInformation in the vscode.d.ts with the variadic property. Then the UI could handle cases like too many parameters and rest parameters when rendering the signature help.

**Comment by dbaeumer** [comment]
@jrieken what is your take on this?

**Comment by jrieken** [comment]
Yeah, needs thinking but why not. Assigning to me and adding the API tag

**Comment by jrieken** [comment]
Actually, I don't think this is an API request but an issue with TypeScript. With sample below is says the active signature has three parameter but the it also says the fourth is the active one.

```
function aaa(b: boolean, n: number, ...more: any[]) {

}


aaa(true, 1, ddd, <CARET>)
```

![screen shot 2016-04-22 at 10 07 18](https://cloud.githubusercontent.com/assets/1794099/14735602/117faaa8-0872-11e6-8a42-7b74cdef06ec.png)
