### ISSUE TITLE
Hide links from search results or at least identify them 

### ISSUE THREAD

**Issue by spkane** [Microsoft/vscode#46188]
- VSCode Version: 1.12.1
- OS Version: Mac OS X 10.13.2

Steps to Reproduce:

1. Search for something from a file in your project that is linked in multiple places
2. You will get multiple hits for the same file.

Does this issue occur when all extensions are disabled?: Yes

It would be nice if the new decorations for links were also used in the search pane. 

It would great, if the duplicates were simply removed from the results pane altogether.

**Comment by roblourens** [comment]
You mean symlinks right? If you set `"search.followSymlinks": false`, then search will not follow symlinks. Does that work for you?

**Comment by spkane** [comment]
@roblourens Yeah. That setting is probably fine. 

It still might be useful to use the decorator when people have this enabled, but in my case, I can simply turn off followSymlinks for search. Guess I need to get better about searching through all the preferences first.

Thank you!
