### ISSUE TITLE
Sublime Style Multi-Cursor Select

### ISSUE THREAD

**Issue by janniks** [Microsoft/vscode#46187]
Issue Type: <b>Feature Request</b>

#### Requested Functionality

There is still no functionality for only holding `alt` (or any other configured key) and dragging to create multiline cursors _(without a selection box)_.

At the time of writing Visual Studio Code can be used to create a selection box when `shift+alt` is held while dragging, but not only cursors. A workaround is to put the cursor in the target column and then start dragging the multiline selection box from that point while staying in the same column._

#### Sublime Text Example

_The shown GIF uses Sublime Text and `alt` is being held while dragging._

![guess](https://user-images.githubusercontent.com/6362150/37661461-2d4e8066-2c55-11e8-8a1e-d7cfb867551c.gif)

<img width="620" alt="screen shot 2018-03-20 at 15 46 08" src="https://user-images.githubusercontent.com/6362150/37661883-0fccae04-2c56-11e8-9f3a-69e16fcf2d11.png">

_Keyboard shortcuts (for macOS). `alt` + dragging is not being used as of yet. (Reference taken from [Keyboard Shortcuts Visual Studio Code macOS](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf))_

---

**VS Code version:** Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
**OS version:** Darwin x64 17.4.0 - macOS 10.13.3 (17D102)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/5402
