### ISSUE TITLE
Do not auto import relative paths ever

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46194]
Please do not auto import relative paths ever, this is constantly in the way of my productivity.

Steps to repro:
1. Accept as a suggestion an unimported class in a Typescript file
2. The class is automatically imported as accepted, however the import is relative

This is easily reproducible anywhere in vscode.

p.s if I trigger a quick fix to import I am presented both options to import as relative or absolute. Which I guess is fine, but on suggest accept we should import in the style that most imports in the file are.

**Comment by mjbvz** [comment]
Duplicate of #43575
