### ISSUE TITLE
Fixed Size Terminal Control

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#46191]
Issue Type: <b>Feature Request</b>

Fixed size terminal control

VS Code version: Code - Insiders 1.21.0-insider (9a04587cc6b42c332609a08bfd7e2dbeac592c21, 2018-03-01T08:09:20.917Z)
OS version: Windows_NT x64 10.0.16299

Today integrated terminal auto-fits the window and changes its cols count when user resizes the window. Our extension needs to be able to start a terminal with the fixed column count which we would specify on terminal creation, and which won't change when the terminal window resizes.

This could be achieved by adding `rows?: number | undefined` member to `vscode.TerminalOptions`.
The behavior may be that if this `rows` is set, the terminal control has fixed width. When terminal window is wider than the terminal control with fixed width, the the empty space is filled with background color. When the terminal window is smaller, we can either clip the control, or show a horizontal scroll bar.

**Comment by Tyriar** [comment]
This is captured in the API for https://github.com/Microsoft/vscode/issues/46192
