### ISSUE TITLE
Insiders build not launching in Ubuntu 14.04

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#46193]
- VSCode Version: code-insiders 1.22.0-1521559263
- OS Version: Ubuntu 14.04.5 LTS

Steps to Reproduce:

1. After the upgrade, I'm unable to launch insiders anymore. I dont see any logs even in the `~/.config/Code Insiders/logs`
2. I was unable to launch insiders from the last two builds

Does this issue occur when all extensions are disabled?: Yes

**Comment by thekalinga** [comment]
Only the new logs directory is getting created, but without any log file

**Comment by bpasero** [comment]
@thekalinga what is the output when you run "`code-insiders --verbose`" from the command line?

**Comment by thekalinga** [comment]
```
/usr/share/code-insiders/code-insiders --verbose: relocation error: /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

**Comment by joaomoreno** [comment]
https://askubuntu.com/questions/777803/apt-relocation-error-version-glibcxx-3-4-21-not-defined-in-file-libstdc-so-6

Does this fix it for you?

**Comment by thekalinga** [comment]
Thanks for the update.

vscode regular release (not insiders) launches properly even now in my laptop. So I suspect insiders must be the culprit rather than any ubuntu library specific issue

Here is the version of vscode I'm able to launch
```

Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:30.761Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

This issue was not there in the previous version of insiders. Something has changed in the last 3-4 releases within insiders

**Comment by thekalinga** [comment]
Plus, Sorry, I have not tried the changes suggested in the askubuntu post as it suggested to reinstall some system libraries. I'm not comfortable in reinstalling system libraries

**Comment by joaomoreno** [comment]
We definitely changed build machines recently. This could affect all 14.04 users.

**Comment by darkvertex** [comment]
I hope you guys can restore the builds to a similar level of minimum requirements from before.

At my employer we're on Linux CentOS 7 and its latest glibc available in the official Cent7 rpm repos is 2.17: https://centos.pkgs.org/7/centos-x86_64/glibc-2.17-196.el7.x86_64.rpm.html
and that one does not support the new GLIBCXX_3.4.20+ requirement (formerly 3.4.19 if I'm not mistaken, which is covered by the rpm linked and the reason the stable "code" build currently works for me and my coworkers.)

Furthermore, the industry I'm in (film/tv visual effects) collectively agreed to follow a standardized set of common libraries, refreshed yearly here: https://www.vfxplatform.com
and glibc-2.17 is the agreed current standard for us for now, so unfortunately for me I don't have the luxury of being on the latest and greatest.

Thank you for your time.

**Comment by JimSuplizio** [comment]
@joaomoreno Does this mean that tomorrow's build (or whenever the next insiders build comes out) should have your update?

**Comment by darkvertex** [comment]
I confirm that the latest _insiders_ build (`code-insiders-1.22.0-1522148162.el7.x86_64`) works for me on my CentOS7 once again! :tada: :balloon:

Thank you so much for the quick response on this, @joaomoreno. Much appreciated.

**Comment by RMacfarlane** [comment]
Verified by users

**Comment by RobertoMalatesta** [comment]
Problem still present or resurfacing with actual *.tar.gz nightly builds.

My last _working_ one is:
code-insider-1.22.0-1522148010_amd64.tar.gz

--R

**Comment by darkvertex** [comment]
Noooooooooo... :(

Latest build (`code-insiders-1.22.0-1522420781.el7.x86_64`) is re-broken as it was before...

```
> code-insiders -s
{ errorCode: 'load',
  moduleId: 'spdlog',
  neededBy: [ 'vs/platform/log/node/spdlogService' ],
  detail: 
   Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
       at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
       at Object.Module._extensions..node (module.js:598:18)
       at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at n (/usr/share/code-insiders/resources/app/out/vs/loader.js:15:513)
       at bindings (/usr/share/code-insiders/resources/app/node_modules.asar/bindings/bindings.js:81:44)
       at Object.<anonymous> (/usr/share/code-insiders/resources/app/node_modules.asar/spdlog/index.js:3:35)
       at Object.<anonymous> (/usr/share/code-insiders/resources/app/node_modules.asar/spdlog/index.js:21:3)
       at Module.i._compile (/usr/share/code-insiders/resources/app/out/vs/loader.js:15:731)
       at Object.Module._extensions..js (module.js:580:10)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at t.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:16:56)
       at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:587)
       at i (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:777)
       at Object.errorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:898)
       at e.triggerErrorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:952)
       at /usr/share/code-insiders/resources/app/out/vs/loader.js:13:657
       at ReadFileContext.callback (/usr/share/code-insiders/resources/app/out/vs/loader.js:16:267)
       at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13) }
```

Did someone touch the build servers again? This had been fixed.

**Comment by joaomoreno** [comment]
Yep the build definition wasn't running `git clean` before building. This causes issues in the old build agents. Builds should be fine from now on.

**Comment by joaomoreno** [comment]
Verified by looking into the build log: the repo is now perfectly clean before running `yarn`.

**Comment by darkvertex** [comment]
Thanks! Just updated to `code-insiders-1.22.0-1522758456.el7.x86_64` and it is running properly once again here. :+1:

**Comment by RobertoMalatesta** [comment]
Again working with `code-insider-1.22.0-1522758299_amd64.tar.gz`
Thank you,

--R

**Comment by joaomoreno** [comment]
Thanks for keeping an open eye, guys!

**Comment by RobertoMalatesta** [comment]
@joaomoreno since I basically download the tar.gz of VSC every other day, it would be nice to have a direct link to the latest nightly build, so I can crontab my updates and always have the latest nightly auto-installed.

Is this possible?

Thank you, and keep the darn good work up !

-- Rob

**Comment by joaomoreno** [comment]
@RobertoMalatesta Sure, there ya go: https://vscode-update.azurewebsites.net/latest/linux-x64/insider

**Comment by RobertoMalatesta** [comment]
:top: @joaomoreno
