### ISSUE TITLE
How extension store persist key-value data

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#46195]
- VSCode Version: 1.21
- OS Version: Mac OS 10.13.3

I am writing an extension.

need to store a key-value map data.

And ``globalState`` and ``workspaceState`` can be persistent? 

I have tried it. but it seems not support

```typescript
// first time should get undefined, next time bootstrap should find it.
console.log(context.workspaceState.get(storageKey)) // undefined

// set state, in the next bootstrap, It should can get the value
context.workspaceState.update(storageKey, "hello world");
```

Even reboot the vscode or upgrade extension. The data should be found in next bootstrap.

**Comment by bpasero** [comment]
@axetroy if you are using `workspaceState` you have to reopen that exact same workspace to get the value. Does it work if you try `globalState` instead?

**Comment by axetroy** [comment]
@bpasero 

I don't know why it doesn't work before

I try again with ``globalState``.  It works now.

Thanks for your time.

btw, can I set the icon of the menus context? I have set the command's icon. but it doesn't work.

should I open other issues or now it does not support?
