### ISSUE TITLE
Automatically start debugger when adding a breakpoint

### ISSUE THREAD

**Issue by garygreen** [Microsoft/vscode#46197]
When you add a breakpoint, it would make sense for the debugger to automatically start.

This could be provided thru a new config option to `launch.json` which specifies which debugger to start when adding a breakpoint in the file:

```json
"autoStartWhenBreakpointAdded": {
    "php": "Listen for XDebug",
    "js": "Launch Chrome"
}
```

I know there is a keyboard shortcut to start the debugger (F5 by default), but this saves that extra step and aligns more closely with Chrome where when you add a breakpoint it automatically "starts" - no need to start it manually.

**Comment by weinand** [comment]
We do not plan to implement this (but you can author an extension that does this).
