### ISSUE TITLE
Merging search includes/excludes removes functionality unnecessarily

### ISSUE THREAD

**Issue by Abhijay** [Microsoft/vscode#46205]
With the new merged include exclude, I can no longer search for exclusive data types while ignoring certain folders.

e.g. 

include: \*.js
exclude: /someFolderWithUnrelatedFiles/\*

**Comment by roblourens** [comment]
Why not? `*.js, !someFolderWithUnrelatedFiles` will be equivalent to the old way split into two input boxes. Please describe the problem with more details

**Comment by Abhijay** [comment]
Didn't see the note with the '!' syntax. That resolves my issue.
