### ISSUE TITLE
settings.json deleted again and requests

### ISSUE THREAD

**Issue by nancym** [Microsoft/vscode#46202]
Issue Type: <b>Bug</b>

This just happened for the THIRD time so I'm reporting it. I was using VS Code to edit a file and my settings.json (in C:\Users\username\AppData\Roaming\Code\User) was deleted or corrupted and all of a sudden I was looking at the default config of vscode (white-on-black text etc.). Has anyone else experienced this? If not, I'm guessing it's one of my extensions that's causing this. This problem happens randomly so it's hard for me to debug it. If it's an extension that's causing this, it might be the AsciiDoctor or Gist extension because I think this never happened before I installed those extensions. Here are my requests:

* VS Code should automatically keep backups of settings.json (without using an extension)

* Allow settings.json to "include" or "source" settings. This way I could keep some of my settings in a Dropbox or Sync folder

Thank you!

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|Memory (System)|7.92GB (0.50GB free)|
|Process Argv|C:\Program Files\MicrosoftVSCode-x64-1.15.0\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
asciidoctor-vscode|joa|0.3.8
vscode-gist|ken|1.2.0
color-highlight|nau|2.3.0
code-clip-ring|Sir|0.0.4
vscode-fileutils|sle|2.8.1
vim|vsc|0.11.2

</details>
Reproduces only with extensions

**Comment by sandy081** [comment]
@nancym Thanks for reporting this. Not sure why the settings file was deleted, as you speculate could be due to extensions. Please let us know if you get more information.

Since your request is to provide automatic back up, we have already an issue open for it https://github.com/Microsoft/vscode/issues/44141
