### ISSUE TITLE
Add option to disable rendering of problems in scrollbar

### ISSUE THREAD

**Issue by josh-tepper** [microsoft/vscode#46201]
Issue Type: <b>Feature Request</b>

The "problems" generated by the language extension are rendered as green/orange/red rectangles in the scrollbar on relevan files.  I'd like the option to disable this.  In my case, I'm editing code that already has many "problems" and they polute the scrollbar and make it hard to see the other contributions in the scrollbar, e.g., the file diff.  This is the case even though they are in different "columns" of the scrollbar.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

**Comment by usernamehw** [comment]
```json
"editor.scrollbar.verticalScrollbarSize": 30,
"workbench.colorCustomizations": {
    "editorOverviewRuler.errorForeground": "#0000",
    "editorOverviewRuler.warningForeground": "#0000",
}
```

**Comment by josh-tepper** [comment]
Oh, clever.  Still there should probably be a setting for this

**Comment by dsteg** [comment]
+1
Rendering of problems / errors should be optional, especially since most (all?) spellcheck extensions produce large amounts of nonsensical warnings when editing complex files (say Latex documents).

**Comment by alexandrudima** [comment]
The solution is the one proposed by @usernamehw -- https://github.com/microsoft/vscode/issues/46201#issuecomment-374720926

**Comment by inwardmovement** [comment]
```
"editor.scrollbar.verticalScrollbarSize": 30,
"workbench.colorCustomizations": {
    "editorOverviewRuler.errorForeground": "#0000",
    "editorOverviewRuler.warningForeground": "#0000",
}
```

None of these work for me, I still have spelling mistakes ("infos" type problems) decorated in the ruler:
```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

![image](https://user-images.githubusercontent.com/9438102/68295318-6b153a80-0092-11ea-82ec-aec98ac8236e.png)

Cannot there simply be an option to disable them?
