### ISSUE TITLE
Error Ctrl + alt + )

### ISSUE THREAD

**Issue by klickl** [Microsoft/vscode#46209]
Issue Type: <b>Bug</b>

Hello, 

I just installed your latest version, but on windows with AZERTY keyboard layout, I'm not able  to display this symbol  " ] ", which can be create by this shortcut Alt Gr + ). 

To solve the problem I removed in the shortcut the default Ctrl + alt + ), defined to group code inside block. 

I think it would be great on next versions to remove this default key binding. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|Memory (System)|7.89GB (3.22GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.13.0
rails-snippets|Hri|1.0.6
vscode-duplicate|mrm|1.2.0
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.4
Ruby|reb|0.17.0
vscode-icons|rob|7.21.0
simple-ruby-erb|vor|0.2.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by alexandrudima** [comment]
@klickl One of the extensions you have installed is causing this, most likely atom-keybindings.

The default installation of VSCode does not bind this keybinding and typing `]` is possible:
![kapture 2018-03-28 at 17 28 55](https://user-images.githubusercontent.com/5047891/38039433-8e64125e-32ad-11e8-8bd3-043d29b08f7f.gif)

**Comment by klickl** [comment]
Ok, I thought I disabled all extensions like asked in the form.

Cordialement,
Brunet Thibault


2018-03-28 17:31 GMT+02:00 Alexandru Dima <notifications@github.com>:

**Comment by auchenberg** [comment]
This issue was moved to Microsoft/vscode-atom-keybindings#49
