### ISSUE TITLE
[xml] provide syntax aware code folding

### ISSUE THREAD

**Issue by jerryhanel** [Microsoft/vscode#46200]
Issue Type: <b>Bug</b>

Open XML file with :
&lt;?xml version="1.0"?&gt;
&lt;MyXml specVersion="2.09"&gt;
    &lt;Header&gt;
            &lt;Comment type="SpecialInstructions"&gt;NON STACKABLE

JEAN CALLED IN&lt;/Comment&gt;
    &lt;/Header&gt;
&lt;/MyXml&gt;

Note that it won't collapse the whole XML because of the newline(s) in the "comment" block. Even when wrapped in &lt;![CDATA[ ... ]]&gt;, this fails.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 v3 @ 2.80GHz (4 x 2794)|
|Memory (System)|31.93GB (16.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe \\lyn-pfile-01\StageGUI Files\MGFiles\Processed\MBL255536586674.xml|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-html-css|ecm|0.2.0
rainbow-csv|mec|0.2.0
csharp|ms-|1.14.0
team|ms-|1.122.0
sqltools|mtx|0.12.1

</details>
Reproduces without extensions

**Comment by aeschli** [comment]
This is something an XML extension should provide that has a proper parser.
I created https://github.com/DotJoshJohnson/vscode-xml/issues/230 and https://github.com/microclimate-devops/xml-language-server/issues/23 against two of the most popular XML extensions. If you have another favorite, please file as an issue there as well.

**Comment by aeschli** [comment]
From https://github.com/microclimate-devops/xml-language-server/issues/23#issuecomment-421830477

> please try https://github.com/angelozerr/lsp4xml/ which implements LSP foldingRangeProvider API

**Comment by fbricon** [comment]
XML node folding is available as part of [XML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml), the extension built by Red Hat on top of [LSP4XML](https://github.com/angelozerr/lsp4xml/).
