### ISSUE TITLE
Installing extensions does not report progress

### ISSUE THREAD

**Issue by saravanaj** [Microsoft/vscode#4621]
- VSCode Version: 0.10.11
- OS Version: Windows 8.1

Steps to Reproduce:

1. Install a big extension that is likely to take some time
2. Navigate away from VS Code and come back
3. No progress bar/indication if the extension is installing

#3341 deals with something similar to this but only a message was added as part of 83f1fe7f20b7c099246a8a8d62fd829bbf6d4840

**Comment by joaomoreno** [comment]
This is coming in March.
