### ISSUE TITLE
Feedback StatusBarItem (Smiley) not visible while building from master

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#46210]
- VSCode Version: Master Branch. Commit 344e93c6
- OS Version: Win 10 Pro

Steps to Reproduce:

1. Clone the repo, do `yarn && yarn run watch`, then run `./scripts/code.bat`
2. Observe no smiley on the right hand side
![image](https://user-images.githubusercontent.com/760112/37679182-33d7ced2-2ca6-11e8-855a-688259c55d92.png)

Even changing the setting for smiley (`workbench.statusBar.feedback.visible`) has no effect even on restart of the development version of vscode

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by kumarharsh** [comment]
No, Its not a duplicate dear bot.

**Comment by joaomoreno** [comment]
The smiley is disabled in dev. Add this to the root level product.json:

```
"sendASmile": {
		"reportIssueUrl": "https://fakeurl",
		"requestFeatureUrl": "https://fakeurl"
	}
```
