### ISSUE TITLE
Can't debug using workspace file launch config

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46212]
- Clone https://github.com/lostfields/express-ts-router
- Open the code-workspace file
- Run "Launch mocha tests" config
- Target selector opens, as if I was running with no launch configs

Also, if I press esc it reappears a second time. When I press esc a second time, it is hidden properly.

**Comment by isidorn** [comment]
The issue was in the initial start when there is no select launch config. I was falsy taking the one belonging to the folder even though it does not have any configurations.
Please try it in tomorrow's insiders and let me know how it works. Thanks a lot
