### ISSUE TITLE
Incorrect use of absolute path in /usr/local/bin/code-insiders shell script under mac

### ISSUE THREAD

**Issue by laughingrice** [Microsoft/vscode#46211]
Issue Type: <b>Bug</b>

This is a refile of bug #46123 as it was incorrectly closed due to being mistakenly  attributed to the vscode-python extention.

This bug is not related to any extention and is a bug in the core vscode package, and specifically the script linked into

    /usr/local/bin/code-insiders

from

    /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code
under osx (and I presume also for the non-insiders version). The script seems to be different under linux so this is an osx specific issue as far as I can tell.
__Note that there is a proposed fix bellow__

The said  script calls python using an absolute path, which is a mistake.
This may work in most cases, but for users with a PYTHONPATH variable set for python 3 (to account for locally compiled packages), /usr/bin/python exits with an error:

    Your PYTHONPATH points to a site-packages dir for Python 3.x but you are running Python 2.x!

The said script should at best call python and not /usr/bin/python
although calling python is an overkill and a better fix is to call to readlink -n

As a side problem, the script gets overwritten with every update (almost daily) although it is not changed, so a local fix does not last

The script content is as follows, the first line after the opening comments is the bug and the first two lines should just be replaced with

    CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(readlink -n "$0")")")")")"

#

    #!/usr/bin/env bash
    #
    # Copyright (c) Microsoft Corporation. All rights reserved.
    # Licensed under the MIT License. See License.txt in the project root for license information.

    function realpath() { /usr/bin/python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }
    CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
    ELECTRON="$CONTENTS/MacOS/Electron"
    CLI="$CONTENTS/Resources/app/out/cli.js"
    ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
    exit $?

VS Code version: Code - Insiders 1.22.0-insider (3a70cdfd8f84136e858b3d39e5a709e637fc35e7, 2018-03-19T06:10:23.916Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|Load (avg)|7, 4, 4|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.14.0
matlab|Gim|0.8.1
cmake-clangd-helper|Har|0.1.0
code-gnu-global|aus|0.2.2
togglehs|bbe|0.1.2
codecpp-minimum|dod|0.0.1
jupyter|don|1.1.4
code-runner|for|0.9.3
CppSnippets|har|0.0.13
cmake-tools-helper|mad|0.1.1
vscode-clang|mit|0.2.2
python|ms-|2018.2.1
cpptools|ms-|0.15.0
markdown-preview-enhanced|shd|0.3.4
cmake|twx|0.0.17
cmake-tools|vec|0.10.4
markdown-all-in-one|yzh|1.1.0

(3 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
I reopened the other issue
