### ISSUE TITLE
Does not focus terminal when pressing Alt + F12

### ISSUE THREAD

**Issue by pavilion** [Microsoft/vscode#46222]
- VSCode Version:
![image](https://user-images.githubusercontent.com/3165436/37689921-cd3a8d78-2c9f-11e8-9ed5-c6e07a64f284.png)

Basically I only have  [Alt + F12] shortcut for toggling the terminal
![image](https://user-images.githubusercontent.com/3165436/37690015-573170fa-2ca0-11e8-9bc7-0b39d256232b.png)

And it does not toggle (it used to). All extensions are disabled. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Works fine on macOS, what platform are you on @pavilion?

**Comment by Tyriar** [comment]
@pavilion hmm, seems to work fine for me. Could you paste in your settings.json file and and let us know what your keyboard layout is?

**Comment by alexandrudima** [comment]
@pavilion This also works fine for me when I use the following in `keybindings.json`:

```
[
	{
		"key": "alt+f12",
		"command": "workbench.action.terminal.focus",
		"when": "!terminalFocus"
	},
	{
		"key": "alt+f12",
		"command": "workbench.action.terminal.toggleTerminal",
		"when": "terminalFocus"
	}
]
```

**Comment by pavilion** [comment]
Hi. The problem was actually in Nvidia Geforce Experience shortcuts. They have ALT + F12 set it up for toggling fps show on/off. I believe a lot of Windows 10 users may be having the same problem as that shortcut is set by default, so the way to change is to:
-Open NVIDIA GeForce Experience GUI.
-Go to settings-> General -> In-Game overlay->Settings
-Search for ALT + F12 shortcut and delete it.

**Comment by Tyriar** [comment]
@pavilion thanks for letting us know 😃
