### ISSUE TITLE
MiniMap scrolling inaccurate with word wrap off

### ISSUE THREAD

**Issue by PLogFinder** [Microsoft/vscode#46224]
- VSCode Version: 1.21.1
- PowerShell extention Version:  1.6.0
- OS Version: Win 7 SP1 64-bit
Editing a PS1 (PowerShell script)

Steps to Reproduce:

1. Word Wrap off - minimap scrolling is inaccurate - lines in minimap area are different to lines in my actual editor view
2. Word wrap ON - minibar scrolling is accruate to the line, in sync with my actual editor view.

To Fix: Please make MiniMap accurate with word wrap status either way?

Does this issue occur when all extensions are disabled?: Yes

**Comment by PLogFinder** [comment]
On a different, much larger file, the opposite was happening - and since I toggled word wrap back and forth, it seems to have normalised itself and is more accurate both ways.

**Comment by alexandrudima** [comment]
@PLogFinder I am sorry I don't understand what exactly you mean when you say that minimap scrolling is inaccurate... The minimap slider should accurately reflect (+/- 1 line) what is rendered in the viewport:

![kapture 2018-03-28 at 16 50 27](https://user-images.githubusercontent.com/5047891/38036951-255546d4-32a8-11e8-81aa-83aa57e58eea.gif)
