### ISSUE TITLE
Vscode has been repeatedly updated

### ISSUE THREAD

**Issue by tulevaisuus** [Microsoft/vscode#46223]
- VSCode Version:1.21
- OS Version:

Steps to Reproduce:
After each update to the 1.21 version, the computer is started on the second day to open the vscode, the current version is displayed as 1.20, and a new version is updated after the next few minutes. After the update is completed, the version is displayed as 1.21. Every day, I don't know if it's a problem with my setup.

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
> OS Version

We need these details.

Also it might help to provide some screenshots of the problem(s).

**Comment by tulevaisuus** [comment]
First of all sorry, the problem has been found.
Maybe it's because the quick launch icon I fixed on the taskbar is the previous version, resulting in each open being a previous version of the software. Then I changed the icon again and it is now normal.

**Comment by dbaeumer** [comment]
@tulevaisuus good to hear that you fixed it. Closing the issue.
