### ISSUE TITLE
searching for "console.log" doesn't take into account exclude settings

### ISSUE THREAD

**Issue by alvipeo** [Microsoft/vscode#46228]
Issue Type: <b>Bug</b>

I have a setting that excludes node_modules from searches. And this works most of the time. Except when I try to search for "console.log" (using *.ts file pattern). In this case it shows me all the .ts files from everywhere!

VS Code version: Code - Insiders 1.22.0-insider (5be9e9e7eef715539efd5341fdbc8ec5840cfc56, 2018-03-20T06:17:19.168Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz (16 x 2999)|
|Memory (System)|15.93GB (7.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.2
ng-template|Ang|0.1.9
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
docthis|joe|0.6.0
angular-essentials|joh|0.3.2
Angular2|joh|2.14.0
json-to-ts|Mar|1.5.4
code-beautifier|mic|1.7.2
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.2.1
angular2-inline|nat|0.0.17
remote-vscode|raf|1.1.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Is the "Use Excludes and Ignore Files" button toggled on?
![image](https://user-images.githubusercontent.com/323878/35752446-e01ea914-0810-11e8-8d1e-9877a751c5ca.png)

**Comment by alvipeo** [comment]
no, but I have this in my settings:

    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true
    }

**Comment by roblourens** [comment]
The button must be toggled on, otherwise the exclude settings are ignored.

**Comment by alvipeo** [comment]
Why??? If I set these settings it's on purpose!

**Comment by roblourens** [comment]
The button is toggled on by default, and it exists so you can easily disable those for searches in the whole workspace.

**Comment by alvipeo** [comment]
Then the UI is not intuitive. At least to me.

**Comment by roblourens** [comment]
If you set the settings, and never touch the button, then the settings should be applied.

What do you expect to see?

**Comment by alvipeo** [comment]
Make those states (enabled/disabled) with different colors please. So it's clearly visible - enabled/disabled.

**Comment by roblourens** [comment]
You are not the first person to mention this, can I ask which theme you're using?

**Comment by alvipeo** [comment]
dark one.
