### ISSUE TITLE
Suggestion: Please upgrade current find feature(CRTL+F) for directory search(multi-sub directories/files search and filter feature*)

### ISSUE THREAD

**Issue by macxfadz** [Microsoft/vscode#46232]
Say we opened **VSCode** with a directory(folder) which consists with lot of sub-directories and files and we opened a file there and we want to search  keyword within entire opened folder structure and their sub items(folders/files).
Right now **VSCODE** has no such feature it's only searching within current document opened and also has no **_filtering feature_** exists in **notepad++**:
![gt](https://user-images.githubusercontent.com/3683121/37698165-28c33512-2cd9-11e8-9e67-684ad6984388.PNG)

This **multi-sub directories/files search and filter feature**  is really useful and necessary feature for Developers.
Thank you hope you guys pay attention on this requirement.

**Comment by erihanse** [comment]
`Search: Find in all files`: `Ctrl-shift-f` lets you do this.

**Comment by macxfadz** [comment]
@erihanse  Got it thank you.It works for find file,but do we have any shortcut key for to do filtering stuff?

**Comment by erihanse** [comment]
Yeah, `Ctrl-shift-j` :)

**Comment by erihanse** [comment]
If you haven't already, I suggest you have a look at https://code.visualstudio.com/docs/editor/codebasics#_search-across-files, maybe you'll find other handy features in the document as well.

**Comment by macxfadz** [comment]
@erihanse  Thank you very much,That's what I really want.
