### ISSUE TITLE
Disable the new javascript IntelliSense in html...again

### ISSUE THREAD

**Issue by extrame** [Microsoft/vscode#46233]
I try to refer to some golang template variable in script part of html like :

```
<script>
    var lastDaysAmount = {{.LastDaysAmount}};
</script>
```

It is normal in golang template, because golang template will render this to 

```
<script>
    var lastDaysAmount = 14;
</script>
```

But formatter think it is a double pair of {}, it reformat it like 

```
<script>
    var lastDaysAmount = {
        {.LastDaysAmount
        }
    };
</script>
```

How to disable it...

I tried these lines but not work:

    "html.format.contentUnformatted": "pre,code,textarea,script",
    "html.format.unformatted": "wbr,script",
    "javascript.format.enable": false,
    "html.format.enable": false,
    "typescript.validate.enable": false,
    "javascript.validate.enable": false,

**Comment by aeschli** [comment]
`"html.format.unformatted": "wbr,script"` should work if you use the built-in html formatter (no other formatter installed)

**Comment by extrame** [comment]
got it , it is a problem of using JS-CSS-HTML Formatter
