### ISSUE TITLE
Syntax highlighting with PHP broken

### ISSUE THREAD

**Issue by wayheming** [Microsoft/vscode#46234]
Issue Type: <b>Bug</b>

VSCode Version: 1.21.1
OS Version: Windows 10 

http://prntscr.com/iu687t

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.89GB (8.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
php-autocomplete|bsc|0.4.2
jquerysnippets|don|0.0.1
vscode-great-icons|emm|2.1.30
vsc-material-theme|Equ|1.5.1
php-debug|fel|1.12.2
php-intellisense|fel|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
material-icon-theme|PKi|3.2.6
wordpress-snippet|tun|1.1.2

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This is part of https://github.com/Microsoft/vscode/issues/20488
