### ISSUE TITLE
setTimeout() snippet behaves weird

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46230]
Steps to Reproduce:

1. use the `setTimeout` snippet in JS or TS
2. press enter in the first edit location (where you put the timeout)

=> you get a newline at this location
=> I would expect that my cursor moves into the body of the method and I am quite sure this used to work like that

![before](https://user-images.githubusercontent.com/900690/37696816-79491182-2cd9-11e8-92b2-e0bce9122ce3.gif)

In general when I am in an edit-location within a snippet I would expect that pressing enter leaves snippet-mode and does not put a newline. It should move the cursor to the final edit location of the snippet.

/cc @jrieken

**Comment by jrieken** [comment]
> In general when I am in an edit-location within a snippet I would expect that pressing enter leaves snippet-mode and does not put a newline

Wrong expectation ;-) Entering a new line is the behaviour of Textmate (the snippet reference) and Sublime. To cancel snippet mode on enter re-bind the `acceptSnippet` and/or `leaveSnippet` command.
