### ISSUE TITLE
Suggestions load very slowly

### ISSUE THREAD

**Issue by silverphoenix1110** [Microsoft/vscode#46231]
Issue Type: <b>Bug</b>

Suggestions load very slowly when I open multi projects

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.60GB (7.41GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.0
alignment|ann|0.3.0
scanner-js-twain-wia-javascript-browser-scan|asp|2.0.2
vscode-database|baj|1.5.1
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
compulim-vscode-dictionary|Com|0.0.5
cake-cored|Crh|1.1.2
vue-peek|dar|1.0.2
githistory|don|0.4.0
jquerysnippets|don|0.0.1
gitlens|eam|8.1.1
php-intellisense|fel|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
html-tag-wrapper|hwe|0.2.3
sftp|lix|1.1.3
Go|luk|0.6.77
sqltools|mtx|0.12.1
php-docblocker|nei|1.3.3
vetur|oct|0.11.7
vscode-code-outline|pat|0.0.13
subtle-brackets|raf|2.1.0
pdf|tom|0.2.0
vscode-wakatime|Wak|1.1.24
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by ramya-rao-a** [comment]
What language are you working on?

**Comment by silverphoenix1110** [comment]
@ramya-rao-a They are php files (my project is using cakePHP 2. it have about ~700 files)

**Comment by ramya-rao-a** [comment]
Do you have the `php.suggest.basic` setting enabled or disabled?

**Comment by silverphoenix1110** [comment]
@ramya-rao-a  php.suggest.basic is enabled. I'm using https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense. Do they conflict?

**Comment by ramya-rao-a** [comment]
@roblourens can answer that

**Comment by roblourens** [comment]
There are some perf-related issues open on that extension, like https://github.com/felixfbecker/php-language-server/issues/274, please see those
