### ISSUE TITLE
To hide item from panel uses a 2-step procedure

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#46237]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Set `"search.location": "panel"` in settings
2. Select SEARCH in the panel
3. Right click on the panel tab area
4. Following the "Hide Side Bar" menu, select menu is shown.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|Memory (System)|7.95GB (1.02GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe D:\WorkingSpace FAST\Visual Studio Code\Git\vscode|
|Screen Reader|no|
|VM|50%|

</details>
Reproduces without extensions

**Comment by EbXpJ6bp** [comment]
@vscodebot Hi again! (https://github.com/Microsoft/vscode/issues/46180#issuecomment-374589948)
I think vscodebot doesn't has to suggest issue that created by same author.

**Comment by isidorn** [comment]
The issue here is that this [method](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/viewlet.ts#L36) in Viewlet always returns `Hide Sidebar`.
Search is a viewlet, so it should override this method and return more precise actions based on its location.

@roblourens I do not think you introduced the notion of a search location inside the `SearchView`. Correct?
Do you plan to add that the [`SearchView`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchView.ts#L67) is aware if it is a panel or viewlet?

**Comment by isidorn** [comment]
Also @sandy081 I belive has added the `getContextMenuActions` to the `Viewlet` via https://github.com/Microsoft/vscode/commit/d127e5777cc8d98e1033dd6b1dbe71837499d94a

And that code is not written in mind that a View can be also in a panel.

@sandy081 the issue with your approach is that in compoistePart [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/compositePart.ts#L461) you are getting context menu actions for composites (viewlets and panels). And for panels this contradicts with the composite bar which is in the title area which provides context menu behavior.

Imho this should not be done on composites but only on viewlets -> assigning also to @sandy081

**Comment by roblourens** [comment]
> Do you plan to add that the SearchView is aware if it is a panel or viewlet?

I don't plan to add that.

**Comment by sandy081** [comment]
@isidorn 

> I belive has added the getContextMenuActions to the Viewlet via d127e57
And that code is not written in mind that a View can be also in a panel.

Those viewlets extends/implement base viewlet classes are assumed to be viewlet not panels. I think its not right to assume a viewlet (Search Viewlet) extending viewlet classes can also be a panel. Not sure if the Search viewlet is composed properly into Viewlet (Container) and View. If it is properly composed, only view should be moved across and not the viewlet. 

> Imho this should not be done on composites but only on viewlets -> assigning also to @sandy081
I do not think so, As I explained above compositePart just exposes an api to provide `titleAreaContextMenuActions`. It is up to the sub classes like `Viewlet` or `Panel` to provide the actions or not. At present viewlets only provide such actions.

**Comment by sandy081** [comment]
Removing myself from this based on above response.

**Comment by isidorn** [comment]
Change is a bit larger, assigning to April since we alread yshipped like this.

**Comment by isidorn** [comment]
I felt like the context menu on title area is very specific to the `sidebarPart` thus I moved that code there. Since we do not have this behavior in the `panelPart` (title there is a `compositeBar`)
