### ISSUE TITLE
contextValue for TreeItem support string and object

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#46236]
- VSCode Version: 1.21.1
- OS Version: Mac OS 10.13.3

I some case, I need to custom when the context for treeItem should show.

Here are 2 contexts for ``star`` and ``unstar``

when star project, ``star context`` hide, ``unstar context`` show
when unstar project, ``unstar context`` hide, ``star context`` show

Here is what I define in ``view/item/context``

```json
               {
                    "command": "gpm.unstarProject",
                    "group": "context",
                    "when": "viewItem.type == project && viewItem.stared == true"
                },
                {
                    "command": "gpm.starProject",
                    "group": "context",
                    "when": "viewItem.type == project && viewItem.stared == false"
                }
```

 But unfortunately, ``contextValue?: string;`` not support object

**Comment by sandy081** [comment]
@axetroy `contextValue` on `TreeNode` does not refers to the menu location `view/item/context`

```typescript
```

**Comment by axetroy** [comment]
@sandy081 
> contextValue is the value your provide in the when property. In the above example folder is the contextValue

I knew it. but ``contextValue`` is only accept string type. isn't it?

How about support an object?

**Comment by sandy081** [comment]
contextValue is always a string and is used internally and in extensions.

What is the purpose of supporting an object?

**Comment by axetroy** [comment]
@sandy081 

> What is the purpose of supporting an object?

For more complicated conditions, control the command/context when to show.

and support an object, should be more scalable

**Comment by sandy081** [comment]
@axetroy Can you please be more specific about complicated conditions? Currently `and`, `not` and `regex` conditions are supported.
