### ISSUE TITLE
Allow to go to file relative to the currently active filed

### ISSUE THREAD

**Issue by chbdetta** [microsoft/vscode#46242]
- VSCode Version: 1.21.1
- OS Version: macOS 10.13.1

Can we have relative path support for [go to file] command?

**Comment by bpasero** [comment]
@chbdetta can you explain what you mean?

**Comment by chbdetta** [comment]
The file search box appears when pressing `cmd` + `p` key or by clicking the menu `Go` - `Go to File...`. Now it only supports file name/ file path matching in the scope of workspace.

Can we have the ability to navigate file relative to currently editing file? e.g. when I am editing file `A.js` inputing `./B.js` will show the file `B.js` in the same directory with `A.js`

**Comment by chrmarti** [comment]
@mrkev This looks like a variation of the absolute path matches. Maybe this could be added in a similar way to that: https://github.com/Microsoft/vscode/blob/27797381c52aba1d5afb0c5004b22472dc672520/src/vs/workbench/parts/search/browser/openFileHandler.ts#L164

**Comment by mrkev** [comment]
If I have a spare minute this weekend I'll set up vscode for development and delve in. Thanks for the pointer!

**Comment by RedBaron97** [comment]
I am currently working on this issue and expect to have it solved by the end of the week! Thanks
