### ISSUE TITLE
I think VS Code deleted my Git history after a file rename

### ISSUE THREAD

**Issue by yoizfefisch** [Microsoft/vscode#46244]
Issue Type: <b>Bug</b>

I can't reproduce it but here is what happened:

After a few weeks of inactivity on a local Git repository, I opened VS Code on 3/20/18, updated to the latest release and renamed my index.html and style.css files to indexold.html and styleold.css respectively. I also edited the HTML file to point to the same CSS file with the new name. Then I reconsidered and named it back to the original name.
I made no commits, branches or any Git changes at this point.

Next day, I open VS Code and wanted to create a new branch. I click on the branch button on the bottom-left corner and I see there are no branches to checkout.
Not realizing this means the branch is blank, I clicked on Create new branch and named it "Cleaner". Then I go to Git Checkout again looking for the master branch. Now I see it's not there and I realize everything was lost. I tried to run git reflog and other online suggestions but only got fatal errors.

The Git repository is blank after a few weeks of inactivity and only changing file names with VS Code.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-4500M APU with Radeon(tm) HD Graphics    (4 x 1896)|
|Memory (System)|3.46GB (0.64GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Documents\Coding\Portfolio.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|3.2.1

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
Without reproducible steps, I find it hard to keep this issue open. Code won't simply delete your data.

Let me know if it happens again.
