### ISSUE TITLE
How to modify/improve debugger UI in Visual Studio Code?

### ISSUE THREAD

**Issue by tarunbansal11** [Microsoft/vscode#46241]
I am looking for ways to create my own window to show different threads and other information in a different way. I found following is written at https://code.visualstudio.com/docs/extensions/overview

" Debug Adapter#

VS Code implements a generic debugger UI and relies on debugger extensions and so called "debug adapters" to connect the debug UI to a real debugger or runtime. A debug adapter is a dedicated process that communicates with VS Code through the VS Code Debug Protocol and can be implemented in any language. "

Can someone guide me if it can be done by extension or by modifying the source code of VS code itself ?

**Comment by isidorn** [comment]
This is not open to extension, so an extension can not do this.
You can contribue a new debug view to the debug viewlet, and this is currently done by node-debug to add a scripts view https://github.com/Microsoft/vscode-node-debug

You can always locally change vscode any way you want but we will not take those changes in.
