### ISSUE TITLE
Full uninstall does not remove installed extensions

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4624]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Have some extensions installed
2. Uninstall VS Code
3. Delete VS Code %appdata% folder since it is not removed during uninstall
4. Re-install VS Code
5. Check installed extenstions

Actual:
There are left over installed extensions

Expected:
There are no installed extensions

**Comment by vsccarl** [comment]
In addition, it will hold on to the previous language until you start debugging.
After changing locale to Russian:
![zh-cntorussiantranslation](https://cloud.githubusercontent.com/assets/12900364/14001523/9260b22e-f103-11e5-907a-b1f791c67969.JPG)
Then it is updated after running the debugger.

**Comment by joaomoreno** [comment]
Extensions are installed in `%HOME%\.vscode\extensions`, not `%APPDATA%`.

**Comment by iamsurajbh** [comment]
how can i uninstall vs code compltly to install it again from scratch??

**Comment by proclaim** [comment]
I just did it and here are the steps
https://medium.com/@jimkang/complete-uninstall-remove-vscode-mac-5e48bef3bdec
