### ISSUE TITLE
Markdown Preview: Images are not rendered when size is specified

### ISSUE THREAD

**Issue by randomnote1** [Microsoft/vscode#46249]
Issue Type: <b>Bug</b>

The code `![image.png](.\image.png =100x)` should display the file named `image.png` with a width of 100px. Instead, the Markdown Preview displays the line of code exactly as typed.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (8.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-formatter|cym|1.0.2
vscode-markdownlint|Dav|0.14.1
xml|Dot|1.9.2
gc-excelviewer|Gra|2.0.20
mssql|ms-|1.3.0
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
team|ms-|1.122.0
azurerm-vscode-tools|msa|0.4.0
gitconfig|sid|1.0.0
vscode-arduino|vsc|0.2.11
markdown-pdf|yza|0.1.7

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
The built-in markdown preview targets commonmark. Extensions can contribute support for syntax beyond that, see: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-image-size
