### ISSUE TITLE
Typing global.document doesn't show autocomplete for document object such as getElementById

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#46252]
Issue Type: <b>Bug</b>

![mar-21-2018 06-18-54](https://user-images.githubusercontent.com/2301847/37709431-cd05a3da-2ccf-11e8-8212-9062398139f2.gif)

 

VS Code version: Code - Insiders 1.22.0-insider (31c30b99345e65fffdc33066726d0962dfbecfa3, 2018-03-21T06:10:19.319Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron ./|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.5.0
vscode-eslint|dba|1.4.7
prettier-vscode|esb|1.2.2
python|ms-|2018.2.1
vscode-fileutils|sle|2.8.1

</details>
Reproduces only with extensions

**Comment by joshunger** [comment]
lol

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22818
