### ISSUE TITLE
macOS keybinds using Option require Fn now

### ISSUE THREAD

**Issue by jkcclemens** [Microsoft/vscode#46253]
Issue Type: <b>Bug</b>

Press Cmd+Opt+F. This used to bring up the replace dialog, but now it does nothing. The solution is to press Fn+Cmd+Opt+F, because Fn+Opt produces Alt, which is what the keybind says when hovered over.

Attempting to change the keybind does not work. Cmd+Opt show up when pressed, but "+F" does not show up unless Fn is held down, as well.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.75GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_14818849|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.14.1
EditorConfig|Edi|0.12.1
gc-excelviewer|Gra|2.0.20
vscode-docker|Pet|0.0.25
code-settings-sync|Sha|2.9.0
rtf|ale|0.3.0
vscode-color|ans|0.4.5
vagrant|bbe|0.5.0
better-toml|bun|0.3.2
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
githistory|don|0.4.0
javadebugger|don|0.1.5
tslint|eg2|1.0.28
rest-client|hum|0.17.0
hjson|lak|0.3.0
Kotlin|mat|1.6.0
rainbow-csv|mec|0.2.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
python|ms-|2018.2.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
indent-rainbow|ode|0.7.2
quicktype|qui|9.0.22
java|red|0.21.0
vscode-icons|rob|7.21.0
sass-indented|rob|1.4.8
rust|rus|0.4.0
vscode-nginx|sha|0.5.0
vscode-hexdump|sle|1.6.0
vscode-lldb|vad|0.8.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
vscode-proto3|zxh|0.1.3

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment]
@jkcclemens I cannot reproduce. Plus, I am confident we haven't changed anything in this area. I believe you might have changed something in your environment, like installed a new keyboard layout, changed OS settings, or perhaps a new physical keyboard. Have you tried with other physical keyboards? 

<kbd>Command</kbd>+<kbd>Option</kbd>+<kbd>F</kbd> brings up the replace in file dialog for me.
![kapture 2018-03-28 at 16 47 33](https://user-images.githubusercontent.com/5047891/38036775-c08ae22c-32a7-11e8-8e45-52be814f10ef.gif)

**Comment by jkcclemens** [comment]
Hm, interesting. It persisted across restarts of VS Code, but at some point the machine itself had a reboot, and it appears to work normally again.

Must've been a fluke somewhere! Sorry about that.
