### ISSUE TITLE
local eslint (not a global) stops work on windows 10

### ISSUE THREAD

**Issue by artzhy** [Microsoft/vscode#46259]
Issue Type: <b>Bug</b>

Not sure about global installation of eslint, but eslint setted up as dev dependency stops working even with disabled plugins,  so if you make mistake and save changes - eslint doesn't show an error 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|Memory (System)|15.95GB (6.19GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by Tyriar** [comment]
@artzhy don't you need the ESLint extension installed for any ESLint errors to be surfaced in the editor? https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by artzhy** [comment]
previously it was working without additional extension

**Comment by dbaeumer** [comment]
@artzhy ESLint live validation always needed the ESLint extension. You can always define a task that does the ESLint validation but the task must be triggered by hand. I am closing since there is nothing that needs to be fixed in my opinion. Please ping if you think otherwise.
