### ISSUE TITLE
[python] Update on PTVS in VS Code?

### ISSUE THREAD

**Issue by victorhooi** [Microsoft/vscode#4625]
@smortaz mentioned on HackerNews last year that PTVS (Python Tools for Visual Studio) would be coming to VS Code this year (2016):

https://news.ycombinator.com/item?id=10589451

Is there perhaps any updates to the timeline? Or any updates you guys are able to share?

I did find another issue related to Python syntax highlighting in VS Code - but I assume this is unrelated to the effort to port PTVS to VS Code?

https://github.com/Microsoft/vscode/issues/2208

**Comment by smortaz** [comment]
@victorhooi - no specific updates to share yet.  hopefully we can get going on this in not too distant a future.  we'll likely build something that combines the best of what PTVS has along with what the OSS community has already produced.  the PTVS part requires untangling some very VS specific code so it can be used in both environments.

cheers.

**Comment by egamma** [comment]
Closing - answer has been provided.
