### ISSUE TITLE
VSCode Won't Quit - Icon is Gone, Application Still Open

### ISSUE THREAD

**Issue by sguthals** [Microsoft/vscode#46255]
- VSCode Version: 
- OS Version: Mac OS X 10.13.3

Steps to Reproduce:

1. Open VS Code and leave open for a few days....
2. VS Code crashes, right-click force-quit the application
3. The black VS Code Window is still open on desktop, with the menu, but the icon is gone
4. The menu cannot be clicked into

Does this issue occur when all extensions are disabled?: Yes/No
Unsure, still trying to figure out how to shut it down so I can re-start it for the VSCode version. I also don't know how to test this again.

**Comment by bpasero** [comment]
@sguthals Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by sguthals** [comment]
👋 @bpasero 
I cannot find any crash report 😞 
<img width="619" alt="screen shot 2018-03-21 at 6 18 21 am" src="https://user-images.githubusercontent.com/1314285/37711956-b27a2a5e-2ccf-11e8-80c5-e85526e80182.png">

I'm sorry, I know this isn't super helpful. Especially since the bug isn't super reproduce-able. 

Interestingly, I needed to update my Mac, I just did so (thinking it might also get VSCode to close). After all of the applications had shut down in prep for the restart, and the screen went black, the VSCode Window (just blacked out) was still there. Took an extra few seconds for it to disappear and the computer to shut down.

**Comment by bpasero** [comment]
@sguthals no worries, so do you see it reproducibly?

**Comment by sguthals** [comment]
I will try opening it again today and leaving it open for a few days to see if the problem happens again 👍

**Comment by bpasero** [comment]
Ok
