### ISSUE TITLE
Search panel fails to render any content

### ISSUE THREAD

**Issue by rorysedgwick** [Microsoft/vscode#46254]
Issue Type: <b>Bug</b>

Accessing the Search panel in the workbench left sidebar renders a blank panel. There is no search input field, and no area to render output from a search:
![screen shot 2018-03-21 at 12 23 38](https://user-images.githubusercontent.com/10106219/37709645-cac61496-2d02-11e8-96eb-a017f17f3aba.png)

This occurs when selecting a folder in the Explorer view and clicking 'Find in folder', as well as when pressing the 'search multiple files' shortcut (on  OSX, cmd + shift + F). Using cmd + F to search within a file works as expected.

There are no errors in the Developer console, and on inspecting the components the following elements exist:

![screen shot 2018-03-21 at 13 44 08](https://user-images.githubusercontent.com/10106219/37713214-1a0d8650-2d0e-11e8-8cf4-3440de4e22b9.png)

I have tried disabling all extensions, and reinstalling VSCode but the problem persists.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|Load (avg)|3, 5, 4|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|/private/var/folders/74/wkn9tw4n40b3r89kg7n_tyt4wlk_n7/T/AppTranslocation/1510CA3B-AB82-4E80-B85C-67AF740BEA9D/d/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_385118|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by isidorn** [comment]
If I open the developer console do you see some errors?

**Comment by rorysedgwick** [comment]
@roblourens i'll give that a try tomorrow. My `search.location": "sidebar"`

@isidorn see the second screenshot in the first post, no errors

**Comment by isidorn** [comment]
@rorysedgwick if I see correcly you do not have the console open in the second screenshot. Press escape to open it or click on the debug console tab in dev tools

**Comment by rorysedgwick** [comment]
@isidorn sorry you are correct, but if there are any errors in the console you get a red cross mark in the top right, along with a number showing how many errors - e.g.

![screen shot 2018-03-22 at 09 59 37](https://user-images.githubusercontent.com/10106219/37763730-c4c3ae5e-2db7-11e8-827a-fcb004fbea79.png)

Interestingly, I now see the following errors when selecting the search icon in the side panel:

![screen shot 2018-03-22 at 10 02 34](https://user-images.githubusercontent.com/10106219/37763898-35e8d988-2db8-11e8-94dc-a5d03381aba7.png)

**Comment by isidorn** [comment]
@rorysedgwick thanks that is a useful stack trace. It seems like `this.tree` is not yet defined here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchView.ts#L650

Leaving to @roblourens to put some null guards there as some timing on this machine is probably off.

**Comment by roblourens** [comment]
There should be no timing issue here, the tree should be created immediately when the CompositePart calls create. I think that it failed to do that, so adding null checks won't help.

I think it probably persisted some bad UI state data and is confused about whether the search view has been created yet. Maybe it's even related to #46368 which I just saw.

If you try running code with fresh user data (like `code --user-data-dir=/tmp/codeuserdata`), does it work?

**Comment by rorysedgwick** [comment]
@roblourens passing the temporary `user-data-dir` opens the editor with search functioning correctly, good call. Does that mean that there is some user preferences or something else that I have specified which is causing the UI state to fail parsing?

**Comment by roblourens** [comment]
I never saw other reports of this, so I'll close it, even though we aren't sure what happened...
