### ISSUE TITLE
watcherService slowing down code-insider to a crawl

### ISSUE THREAD

**Issue by RobertoMalatesta** [Microsoft/vscode#46258]
- VSCode Version:

Version:          Code - Insiders 1.22.0-insider (31c30b99345e65fffdc33066726d0962dfbecfa3, 2018-03-21T06:14:55.070Z)

- OS Version:
OS Version:       Linux x64 4.4.0-92-generic

```
CPU %   Mem MB     PID  Process
   10       98   11390  code-insiders main
    0       28   11392     zygote
    1       83   11433       shared-process
   19      220   11546       window (ConvolutionalModel.ts - deepLearningTS - Visual Studio Code - Insiders)
    2       71   11584         extensionHost
   11      185   11705           electron_node electronForkStart.js tsserver.js 
    0       47   11726             electron_node typingsInstaller.js tsserver.js typesMap.js 
    1       51   11793           electron_node jsonServerMain.js 
  100     1360   11621         watcherService
    0       43   11631         terminal
    0        4   11646           /bin/bash
    1       47   11915         searchService
    9      122   11417     gpu-process
```

Does this issue occur when all extensions are disabled?: Yes, It happens as well if all extensions are _wiped out_

Thanks for your time,

--R

**Comment by bpasero** [comment]
@RobertoMalatesta is that a very large folder you open by any chance?

**Comment by RobertoMalatesta** [comment]
@bpasero 

70Mb with 55Mb of node_modules and 14Mb of .git.
(rather thin if you use node.js :P)
VSCode < 18 had no problems with 1Gb+ projects.

--Roberto

**Comment by RobertoMalatesta** [comment]
@bpasero 
Blame it on me.
My fault.
Inside the root project I had a symbolic link to a 4.2 Gb directory full of JS files.
I'll have a look on how to hide it from watcherService kde/baloo-like hunger.

I think we can close the issue.

--R
