### ISSUE TITLE
Make Ctrl-Hover available with keyboard

### ISSUE THREAD

**Issue by mbenkmann** [microsoft/vscode#46257]
- VSCode Version: 1.21.1
- OS Version: Linux

Currently VS Code offers "editor.action.showHover" for keyboard accessibility of the mouse hover. It would be useful to offer the hover popup that is shown when the Control-key is held while the mouse is hovering over a symbol. In fact I see no reason not to make "editor.action.showHover" show that hover all the time. At least in Python context the Ctrl-Hover seems to be always preferable as it seems to show everything the normal hover shows PLUS additional information.

**Comment by alexandrudima** [comment]
Workaround: peek definition via <kbd>Alt</kbd>+<kbd>F12</kbd>, go to definition via <kbd>F12</kbd>

**Comment by mbenkmann** [comment]
I know these functions, but they're not as nice as the hover.

**Comment by TeChn4K** [comment]
Ctrl + hover to trigger the showHover action would be awesome!

**Comment by lucask42** [comment]
I would also like this feature, is there a possibility this PR will get revived? https://github.com/Microsoft/vscode/pull/59260

**Comment by sbatten** [comment]
Verification Steps:
1. Use the new command `Show Control Hover`.
2. Compare with *Control + Mouse Hover*.
3. Try using both.

**Comment by josedh** [comment]
So I'm assuming, once this is verified, that it will be released on a near future release of vscode?

**Comment by sbatten** [comment]
@josedh this is actually in [VS Code Insiders](https://code.visualstudio.com/insiders/) today.
