### ISSUE TITLE
Edit different files across several tabs

### ISSUE THREAD

**Issue by mlapeyre3** [Microsoft/vscode#46265]
Issue Type: <b>Bug</b>

I can not open a file in a new tab anymore !
Now each time I edit a file #1 and open a new file #2 to edit it, the file #2 is **over** file #1 instead of a new tab.

I don't know if I have made myself understandable, all I can say is that this is a different behavior than a few days ago.

Thanks !

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.89GB (1.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
featurehighlight|Blo|1.4.1
gitlens|eam|8.1.1
auto-rename-tag|for|0.0.15
gc-excelviewer|Gra|2.0.20
vue-snippets|hol|0.1.5
printcode|nob|2.1.0
vetur|oct|0.11.7
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|1.1.0

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@mlapeyre3 can you share screenshots or screencast?

**Comment by mlapeyre3** [comment]
@bpasero sure !

[2018-03-21_18h50_15.zip](https://github.com/Microsoft/vscode/files/1834547/2018-03-21_18h50_15.zip)

As you can see, I open fileA (and edit it). When I open fileB, it covers fileA editor.

**Comment by bpasero** [comment]
@mlapeyre3 it looks like you somehow managed to disable tabs. You can get it back by using this command (Ctrl+Shift+P):

![image](https://user-images.githubusercontent.com/900690/37732001-002f58c2-2d44-11e8-9baa-b5b50e899a3a.png)

**Comment by mlapeyre3** [comment]
Thank you @bpasero, you just make my day awesome!
