### ISSUE TITLE
Terminal split restore error

### ISSUE THREAD

**Issue by garysan** [Microsoft/vscode#46267]
- VSCode Version: 1.21.1
- OS Version: Windows 7, x64

Steps to Reproduce:

1. Maximize VSCode 
2. Press, Windows+left arrow
3. Press, Windows+up arrow

Captured error: 
![2018-03-21_09h34_42](https://user-images.githubusercontent.com/211511/37716545-c5db3044-2cec-11e8-9ea0-3f72afc32594.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/45331
