### ISSUE TITLE
"Files to include/exclude" require full path for workspace folders

### ISSUE THREAD

**Issue by MrTravisB** [Microsoft/vscode#46268]
I have a workspace with multiple folders from different locations on disk. When I do a global search, I expected that "Files to include/exclude" would let me just specify the folders using the workspace name but instead it requires the full path.

For instance, I have a folder `foo` that on disk is located at `/opt/projects/foo`. In the workspace explorer it shows as just `foo`. To do a search in my workspace and only search those files, I have to include `/opt/projects/foo/**/*`. It would be better if I could just include `foo/**/*`.

This is the way it works if I only open a single folder in VSCode rather than multiple folders in a workspace.

**Comment by roblourens** [comment]
If `foo` is one of the folders you have open, then you can search with that folder in a workspace like `./foo`.

Just `foo` would search `**/foo/**` in all open folders, which isn't what you want.

If I understand your scenario, it would basically work the same when you have a single folder open. If you've just opened `foo/`, then `foo` would search _inside_ that folder.

**Comment by MrTravisB** [comment]
Ahhh, didn't realize I needed the `./` in front of the folder name since just searching `foo` works when I have only opened `foo`'s parent folder.

Closing this as non-issue.
