### ISSUE TITLE
Indentation issue with choice elements that span multiple lines

### ISSUE THREAD

**Issue by prifio** [Microsoft/vscode#46266]
- VSCode Version: 1.21.1
- OS Version: Ubuntu 16.04

When I use snippet with multi-line suggestion and insert it, the next line has incorrect indention.
Steps to Reproduce:
1. Add multi-line snippet suggestion.
```json
{
	"case-of-reducer": {
	"prefix": "case-of-reducer",
	"body": [
		"case '${2|ACTION_TYPE, ACTION",
		"_TYPE2|}':",
		"return ${3}",
	]
	}
} 
```
2a Insert snippet when cursor is located at not indented line:
```
case ' ACTION
_TYPE2':
return
```
2b Insert snippet when cursor is located at indented line:
```
    case ' ACTION
        _TYPE2':
    return
```
2c If indent of the original line was 8 spaces:
```
        case ' ACTION
                _TYPE2':
        return
```

Note the strange indent of the _TYPE2':
It is definitely not an expected behavior.

**Comment by jrieken** [comment]
Can you be a little more precise? What of the cases is unexpected?

**Comment by prifio** [comment]
I created another example.
```json
"double-line-suggetion": {
	"prefix": "double-line-suggestion",
	"body": [
		"for (int i = 0; i < n; ++i) {",
		"    ${1|a[i] = b[i] = 0;,a[i] = i;\nb[i] = -i;|}",
		"}"
	]
	}
``` 
Current behavior:
![bad](https://user-images.githubusercontent.com/16323654/37831211-c0e6fe72-2eb5-11e8-97c4-0af4229bd43a.png)
I expect:
![vnice](https://user-images.githubusercontent.com/16323654/37831217-c33cf172-2eb5-11e8-82af-3fb945e3c298.png)
or:
![nice](https://user-images.githubusercontent.com/16323654/37831245-d24bf71c-2eb5-11e8-9277-ceaf8dbd2e0c.png)
