### ISSUE TITLE
Error no controlated when opening VS Code while updating the tool

### ISSUE THREAD

**Issue by ravelus** [Microsoft/vscode#46260]
Issue Type: <b>Bug</b>

When there's an update available, accept the request and update VSCode.

In the meantime, try to open VSCode.

An error message box is displayed: "A JavaScript error ocurrerd in the main process".

![image](https://user-images.githubusercontent.com/1321113/37714928-7ed03f16-2cf9-11e8-90b1-0e797ce81138.png)

I understand that binary files are being replaced in the process, but a proper error message should be displayed instead of this apparently unhandled exception.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

Reproduces without extensions

**Comment by joaomoreno** [comment]
Totally right, but we're likely not going to dedicate resources on improving the message. Much more likely to simply not let you open Code at that point at all.
