### ISSUE TITLE
Search shows excluded files

### ISSUE THREAD

**Issue by JulianMar** [Microsoft/vscode#46269]
- VSCode Version: 1.22.0-insider
- OS Version: macOS High Sierra

Steps to Reproduce:

In the search tab excluded files are shown aswell.
![search](https://user-images.githubusercontent.com/29117090/37720096-d24ce37e-2d26-11e8-90f0-24fe25b56ead.png)

If I manualy remove it in the files to include/exclude it obviously gets removed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It looks like you've deselected the gear icon button. When that button is toggled off, exclude settings are not used.

**Comment by JulianMar** [comment]
Yes that was the Issue.
