### ISSUE TITLE
Folder deletion freezes VSCode

### ISSUE THREAD

**Issue by 100Errors** [Microsoft/vscode#46262]
- VSCode Version: 1.21.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode
2. Delete a folder with VSCode which contains many subfolders and files

VSCode freezes until the deletion is the completed

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@100Errors do you have a single folder or multiple folders open?

**Comment by 100Errors** [comment]
A folder in VSCode: (for example) "myproject": "node_modules" is one of the subfolders in it.. if I delete  this folder (node_modules) VSCode freezes

**Comment by Tyriar** [comment]
@bpasero are you familiar with this issue where deleting a large folder will freeze VS Code on Windows until the delete finished? Looks like this is using the C# file watcher.

**Comment by bpasero** [comment]
@Tyriar well if the deletion is slow we may produce a lot of delete events per file that end up spamming our event listeners. I think we wait fo 50ms to try to fold multiple delete events into one if we can find a common parent. 

@100Errors if you run `code --verbose` and check the console for the output, do you see many file delete events there?

**Comment by 100Errors** [comment]
Just two:
```
[main 18:56:45] windowsService#showMessageBox 1
[16336:0323/185708.531:INFO:CONSOLE(2851)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/
resources/app/out/vs/workbench/workbench.main.js (2851)
[16336:0323/185708.531:INFO:CONSOLE(2851)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/
resources/app/out/vs/workbench/workbench.main.js (2851)
```

**Comment by bpasero** [comment]
@100Errors interesting. 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by 100Errors** [comment]
I have already tried this when I created this issue but I retried: Same result (it freezes until it deleted the folder)

**Comment by bpasero** [comment]
@100Errors how large is that folder? how many files?
