### ISSUE TITLE
"Search: Find in files"-function fails to find result.

### ISSUE THREAD

**Issue by erihanse** [Microsoft/vscode#46279]
- VSCode Version:1.21.1
- OS Version:Windows 10

Steps to Reproduce:

1. Ctrl-Shift-F
2. Search for a file in a subdirectory, which is not currently open in an editor view

Does this issue occur when all extensions are disabled?: Yes

So this is a problem which I haven't experienced before. When I try to search in files for some content I know is present, it says "No results found". If I open the file however, then it will find it. Is there som limit to the amount of files the search function parses? The open folder is a java project with >1000 source files, is this too big to be supposed to handle?

**Comment by roblourens** [comment]
Could you turn off the "Use Exclude Settings and Ignore Files" button and try again, to make sure it isn't covered by a gitignore file or exclude setting?

(Bottom right)
![image](https://user-images.githubusercontent.com/323878/37731115-8973c3d4-2cfe-11e8-9aab-2bba18fddfde.png)

**Comment by erihanse** [comment]
You,re right, that did the trick. I've tried the button before, but didn't know if it was on or off, since it's hard for me to see whether "Use exclude settings and Ignore files" are on or off. I guess I'll have to dig up what's ignoring the file.

**Comment by roblourens** [comment]
> since it's hard for me to see whether "Use exclude settings and Ignore files" is on or off

This seems to be a common issue, and I'm wondering how to make it more clear. Are you using one of the built-in themes?

**Comment by erihanse** [comment]
Monokai. But yeah, with high-contrast for instance there's a box around the icon.

**Comment by roblourens** [comment]
There is with Monokai too, and the icon is brighter when it's toggled on. But the border may be hard to see.
