### ISSUE TITLE
[TS] error in json files

### ISSUE THREAD

**Issue by iAvinashVarma** [Microsoft/vscode#46275]
Recently I have upgraded the Visual Studio code, since then I am facing [TS] errors in json files. I have checked multiple json files and this is happening in all of them even though having a valid json format.

Here is one of the issue:

![image](https://user-images.githubusercontent.com/10095031/37726236-e46df226-2d5a-11e8-92ca-38600fd0b11c.png)

Here is Visual Studio Code version details

![image](https://user-images.githubusercontent.com/10095031/37726365-33b4470e-2d5b-11e8-9d01-efc05959c00e.png)

I am able to exclude json files from [tslint] errors as show in the issue, but unable to exclude json files from [ts] errors.

I feel this as a bug, it would be great if this issue is resolved or atleast provide a way to exclude the TS errors in specific file formats.

**Comment by mjbvz** [comment]
You seem to have the language mode for the file set  to `typescript`. Please [make sure it](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file) is `json`.

**Comment by iAvinashVarma** [comment]
Thank you @mjbvz, the issue is resolved 👍
