### ISSUE TITLE
Allow to drop folders into the explorer from the desktop to copy them

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4627]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Launch app and open any folder.
2. Try to drag and drop files and folders from windows explorer to VSCode explorer.

Actual: User able to move only files. For folder there is no action or error message.
Expected: If this feature is not supported then it should not show the Copy icon while performing drag and drop for folder. It should display some no action or invalid operation icon (how Visual studio is showing up) for drag and drop.

![image](https://cloud.githubusercontent.com/assets/17735796/14001701/ae1cda32-f104-11e5-9079-f5d35a150642.png)

**Comment by bpasero** [comment]
Closing, we will not support this.
