### ISSUE TITLE
RegExp Highlighting fails with the s flag in a javascript file

### ISSUE THREAD

**Issue by CxRes** [Microsoft/vscode#46285]
- VSCode Version: 1.21.1
- OS Version: Windows 10 x64

Steps to Reproduce:
1. Write a non-trivial RegExp with the `s` flag in a `.js` file.
  You shall find that the RegExp is colored in blue and white instead of the usual orange and red. The problem disappears when the `s` flag is removed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#587
