### ISSUE TITLE
Korean translation for Uncaught Exceptions incorrect

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4628]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Change locale to Korean
2. Check the debugging window exceptions

![koreanexceptions](https://cloud.githubusercontent.com/assets/12900364/14002154/46f4c826-f107-11e5-87d6-2b39bd11d4d2.JPG)

I get a few conflicting results when translating it elsewhere but it should likely be:
"캐치되지 않는 예외" (or "uncaught 예외")

**Comment by Tyriar** [comment]
This might be better: "잡히지 않은 예외들", the literal translation is "exceptions not caught yet (but can be)". Might not be the real programming term though.

**Comment by sunglim** [comment]
Native Korean, Here I come!

`[ ] Uncaught exceptions`  => `처리 되지않은 예외` looks natural. 

https://msdn.microsoft.com/ko-kr/library/ac9f67ah.aspx uses same word.

**Comment by Tyriar** [comment]
Thanks @sunglim! :+1:

**Comment by jrieken** [comment]
@dbaeumer unsure who the nls contact is

**Comment by dbaeumer** [comment]
@johnliu2016

**Comment by johnliu2016** [comment]
ported to loc

**Comment by johnliu2016** [comment]
Per loc team - 
_
"In UI strings there is frequently used following translations:
Catch되지 않은 예외
확인할 수 없는 예외
Suggested translations are not used frequently.  If it has be to be fully translated, then I suggest ‘확인할 수 없는 예외’.
The translation is changed to '확인할 수 없는 예외'_

**Comment by sunglim** [comment]
Frankly speaking, I can't accept newly translated string from Loc team :(

Anyway it's already done. let's close this issue.
