### ISSUE TITLE
Request: Support different indentation modes for different syntaxes in same file

### ISSUE THREAD

**Issue by simonhaenisch** [Microsoft/vscode#46287]
- VSCode Version: 1.21.1
- OS Version: macOS High Sierra 10.13.3

Steps to Reproduce:

1. Set indentation mode to tabs in config
2. Using the "Jekyll Syntax Support" extension, open an `html` file with `yaml` frontmatter as "Jekyll HTML"
3. The extension sets the syntax to `yaml` for the frontmatter, but the syntax-specific indentation settings (`"editor.insertSpaces": true`) for `yaml` don't apply

Tab indentation is invalid syntax in `yaml`. A temporary workaround is to manually switch the indentation mode when editing the frontmatter.

Related issue: https://github.com/ginfuru/vscode-jekyll-syntax/issues/3

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
The insert tabs / insert spaces setting (`editor.insertSpaces`) is indeed currently implemented as a setting for the entire buffer and not per buffer region.

**Comment by simonhaenisch** [comment]
Still keen to have this resolved by making the buffer-region aware of the indentation settings for that language...

For example with this `.editorconfig`:

```cfg
[*]
indent_style = tab
indent_size = 2

[*.yaml]
indent_style = space
```

I would hope that e. g. a `yaml` region within a `html` file (front-matter) would take the `yaml` language-specific indent setting rather than the global one.
