### ISSUE TITLE
Add keyboard shortcut to increase/decrease CSS/SCSS/LESS number values

### ISSUE THREAD

**Issue by dev-nicolaos** [Microsoft/vscode#46284]
My apologies if a similar feature request already exists. I searched and could not find one.

The idea here would be to replicate the behavior found in modern browser's dev-tools. When inspecting the styling rules for a web page, if you select a numeric value for a rule, pressing the up/down arrow keys will usually increase/decrease the value by one.

![devtools-increase-decrease-css-value](https://user-images.githubusercontent.com/29005473/37733989-189725d0-2d07-11e8-8558-b3ed748a3e3b.gif)

It would be great if this ability could be bound to a pair of keyboard shortcuts (one for increasing and one for decreasing) when a numeric value in a CSS, SCSS, or Less file was in focus.

After a quick browse of the keyboard shortcuts pdf, I wouldn't mind seeing the current CTRL + Up/Down shortcut (scroll by line) replaced with this feature in the specified file types. This could also be made optional via a user setting, or maybe we could find a better key combo that is currently unused.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=nmsmith89.incrementor

**Comment by Tyriar** [comment]
@ramya-rao-a I think emmet can do this too?

**Comment by ramya-rao-a** [comment]
@dev-nicolaos You can add your own keybindings for the below commands from Emmet 

![image](https://user-images.githubusercontent.com/16890566/37803445-f5325034-2deb-11e8-975c-ba6fb5d62cde.png)
