### ISSUE TITLE
search.exclude doesn't work with "when" property

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#46280]
- VSCode Version: 1.21.1
- OS Version: Windows 10 x64

![search-exclude](https://user-images.githubusercontent.com/8441956/37730472-070c9016-2cfd-11e8-8272-fe1408e575a1.PNG)

From the screenshot it's clear that the "gear" toggle is on, meaning respect search.exclude setting.
If I remove "when" and just use "true" then it works. "when" works fine in files.exclude.

**Comment by roblourens** [comment]
Works for me - Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by roblourens** [comment]
Actually, I can repro, the issue is with two patterns in 'when' that match a file. But the fix is not straightforward.

A better way to match two patterns in 'when' is tracked here: https://github.com/Microsoft/vscode/issues/1214

**Comment by roblourens** [comment]
Use #1214 for this
