### ISSUE TITLE
'Bash on Ubuntu (on Windows)' terminal not working after updating VSCode Insider.

### ISSUE THREAD

**Issue by dharmic** [Microsoft/vscode#46283]
- VSCode Version: 1.22.0-insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Setup Ubuntu terminal on windows. (Skip this if you already have it.) https://docs.microsoft.com/en-us/windows/wsl/install-win10
2. Add/Update "terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe" in User Settings file.
3. Try to open new terminal tab in VSCode Insider.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@dharmic what does the terminal look like? Could you take a screenshot when this happens?
