### ISSUE TITLE
Vscode cannot search globally

### ISSUE THREAD

**Issue by genius-ye** [Microsoft/vscode#46297]
- VSCode Version: 1.21.1
- OS Version: win10

Steps to Reproduce:
Vscode can only search currently open files, unable to search the entire project
I tried to reinstall vscode or did not solve the problem
![1521681447 1](https://user-images.githubusercontent.com/5753805/37745907-74690c60-2db2-11e8-8227-b1dabe0cb735.jpg)

- 

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No yes

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by roblourens** [comment]
- Does it work if you toggle off the "Use exclude settings and ignore files" button? (gear icon in your screenshot)
- Does it work in other folders? Does it work in a folder on the C drive?

**Comment by genius-ye** [comment]
I just tried it when you said, still can't search!
![1521696089 1](https://user-images.githubusercontent.com/5753805/37752668-22ee11b0-2dd4-11e8-9b15-740fbea5497f.jpg)

**Comment by roblourens** [comment]
Both of your screenshots show a search in progress with a progress bar... is it possible that the search is just running slowly?

**Comment by genius-ye** [comment]
Already searched for ten minutes still searching

**Comment by roblourens** [comment]
If you open Task Manager, is there an rg.exe process using lots of CPU? Is there a MsMpEng.exe process using lots of CPU? Or, which processes are busy?

**Comment by genius-ye** [comment]
None of the processes you are talking about, this is the screenshot
![1521699911 1](https://user-images.githubusercontent.com/5753805/37754528-da072b40-2ddc-11e8-82ee-4e4774650ae1.jpg)

**Comment by roblourens** [comment]
Hm, something is not right.

Do you see any errors in the developer tools console? (Help > Toggle Developer Tools)

**Comment by genius-ye** [comment]
I get some errors in the developer tools console when I searhed:

![1521767733 1](https://user-images.githubusercontent.com/5753805/37806403-c8519b08-2e7a-11e8-900a-a6368644af9f.jpg)

**Comment by genius-ye** [comment]
![1521768436 1](https://user-images.githubusercontent.com/5753805/37806773-b36a8ce8-2e7c-11e8-8ce8-6e3c8f6459ed.jpg)

**Comment by roblourens** [comment]
Can you check if that path for `rg` is correct?

Also, does search work in other folders? Does it work in a folder on the C drive?

**Comment by genius-ye** [comment]
It works well on the c drive, but my system is on the I drive, why it can't work on the other drive？

**Comment by roblourens** [comment]
Could you try invoking rg manually from the command line to see whether it gives any other error?

Using the command from this screenshot

![1521685328 1](https://user-images.githubusercontent.com/5753805/37747589-ecb1e4d2-2dba-11e8-90f7-b2e36828b444.jpg)

in the second log message, starting with `rg --hidden --heading...` but replace the `rg` with the full path in the error message (`i:\Users\genius-ye\Desktop...\rg`)
