### ISSUE TITLE
Feature Request: Search Facility (include/exclude fields to handle regex usage and history for fields)

### ISSUE THREAD

**Issue by LordHog** [Microsoft/vscode#46294]
Hello,

  I have a couple feature request for the search facility within VSC.

1) Be able to using regex for specifying files.  For example, one of the common search filters I have is "*.c,*.h,*.py", but I would like to use the form of "*.(c|h|py)".

2) Each of the fields needs to have a history of previous entries and can be configurable to list how many entries I would like to store.

3) Having the ability to specify and store common filters that I use and toggle between.  As of now, I need to keep my filter expressions in a text file since there is no history and no way to store frequently used filters.

Regards,
Mark

**Comment by roblourens** [comment]
1. You can do something like this with glob patterns, like `.{c,h,py}`. Regex is not likely to happen.
2. You can access the history for each field with alt+up/down arrow.
3. Besides the history, I don't know of an existing feature request for this one

**Comment by LordHog** [comment]
@roblourens given the command sequence was not obvious, would it still be possible to place little chevrons to indicate to the user they can cycle through them.  Still, I much rather see a drop down list than having to cycle through each one individually and have the ability to specify how many entries I want to have.

**Comment by roblourens** [comment]
I am tracking the request for something like a dropdown here - https://github.com/Microsoft/vscode/issues/23099

**Comment by LordHog** [comment]
@roblourens Thanks.  I had did a search looking for the keyword "search", but didn't see anything.  Seems the term used for this item is "find".  I guess I should had used that keyword also.  Glad to see there is an action item already for it and hopefully it gets implemented (though this request is now a year old).

**Comment by LordHog** [comment]
I am very sad not to see this feature be considered as it would aid to searching the code base much easier.
