### ISSUE TITLE
HTML Highlighting for Angular Syntax in HTML

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#46290]
_From @hgundogdu on March 19, 2018 15:41_

Hi ,
I'm using vs code with angular.
Is there a any way to colorize angular syntax in html. 

For example;

"< p >{{ ' Welcome '+username }}</ p >
< button class="btn btn-primary" [disabled]="username ===''" (click)="username=''">Reset< / button >"

" Welcome [different color], username [different color], 
[disabled] [different color], username ===' '  [different color],
(click)  [different color],username=' '  [different color] " 

sorry fo rmy bad english.

_Copied from original issue: Microsoft/vscode-docs#1507_

**Comment by gregvanl** [comment]
Hi @hgundogdu This looks like a VS Code product question so moving to the vscode repo.

**Comment by gregvanl** [comment]
Duplicate of #46289

**Comment by hgundogdu** [comment]
hi @gregvanl i'm new here i didn't understand. Why did you close both issues ? There is no solution yet.

**Comment by gregvanl** [comment]
Hi @hgundogdu I ported the vscode-docs issue to the vscode product repo. When I saw that you had also entered an issue there, I closed the ported issue. #46289 is still open.
