### ISSUE TITLE
"Tab moves focus" disabled, but tab still moves focus and cannot insert tabs

### ISSUE THREAD

**Issue by terminalstderr** [Microsoft/vscode#46293]
Issue Type: <b>Bug</b>

**Synopsis**:
Regardless of "Tab moves focus" being enabled or disabled, tab never inserts tab-or-space characters and instead always "moves focus".

**Steps to reproduce**:
1. <Ctrl+n> to open new file
2. Press tab key to attempt to insert tab character
3. <Ctrl+m> to switch "Tab moves focus" mode
4. <Ctrl+n> to open new file
5. Press tab key to attempt to insert tab character

**Expected**:
One of step 2 or step 5 should insert a tab character

**Observed**:
Neither of step 2 or 5 produce tab. Both of step 2 and step 5 "Move focus" from the editor view to the  "Problems" view

**Details**:
[inspect-key-mapping-output.txt](https://github.com/Microsoft/vscode/files/1835286/inspect-key-mapping-output.txt)
****

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Memory (System)|31.89GB (19.80GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
code-runner|for|0.9.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
vscode-icons|rob|7.21.0
cmake-tools|vec|0.10.4
JavaScriptSnippets|xab|1.5.0

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment]
@terminalstderr I'm sorry I cannot reproduce. It appears you are on an English/US keyboard layout. <kbd>Tab</kbd> can be broken by:
- extensions which override what <kbd>Tab</kbd> does
- user keybindings that override what <kbd>Tab</kbd> does

The easiest is for you to try the [insiders variant](https://code.visualstudio.com/insiders/) which should be in a clean state.

**Comment by terminalstderr** [comment]
@alexandrudima installing the insider's addition is a good workaround. Thanks!
 
I was unable to verify if Tab reaches VSCode (from the OS). I've also uninstalled the non-insiders VSCode so am unable to reproduce the issue anymore.
