### ISSUE TITLE
how to focus cursors from extension api?

### ISSUE THREAD

**Issue by 74th** [Microsoft/vscode#463]
I want to move a cursor from a extension. I wrote below codes.

```
var p = new vscode.Position(line,char);
var s = new vscode.Selection(p, p);
vscode.window.activeTextEditor.selection = s;
```

The cursor moves, but when it move to outside of a window, the window does not focus it.
How to focus cursors from a extension api?

**Comment by alexandrudima** [comment]
@74th would TextEditor.revealRange with no/default revealType work for you?

**Comment by 74th** [comment]
Thank you! It works!
