### ISSUE TITLE
Emmet snippet "iframe" is higher than "if"

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#46305]
- VSCode Version: 1.22.0-ins
- OS Version: win7x64

![image](https://user-images.githubusercontent.com/24613274/37749164-5f065102-2d8f-11e8-8ef0-20f84fbfd45b.png)

**Comment by ramya-rao-a** [comment]
Is the `if` here a js/ts snippet here?

**Comment by user3323** [comment]
@ramya-rao-a 

happens in **_.ts_**

snippet `if` is from - **_TypeScript Language Basics_** 

![iframe if](https://user-images.githubusercontent.com/24613274/37858579-52a15e26-2f0f-11e8-8f0a-aa006dca66ac.gif)

so, it happens because of "including rule" in the settings:
```
"emmet.includeLanguages": {
    "typescript": "html"
  }
```
it's good that we can have Emmet snippets in the .ts files, but not good that Emmet push all it's snippets to the top, regardless of basic alphabetic order.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @user3323!
The fix will be available in tomorrow's Insiders build.

Note to verifier:
Add the below settings to repro the issue in 1.21 stable
```
"emmet.includeLanguages": {
    "typescript": "html"
  }
 "emmet.showSuggestionsAsSnippets": true,
    "editor.snippetSuggestions": "top"
```
