### ISSUE TITLE
Powershell crash?

### ISSUE THREAD

**Issue by inemtsev** [Microsoft/vscode#46306]
Issue Type: <b>Bug</b>

Hi,

This issue is somewhat random, but happens very often. I open my simple VueJS+babel+node project. Start working, open terminal run any command (here it has 50/50 chance of crashing, sometimes just opening terminal crashes it) . Error looks like this person's I found online: 
https://user-images.githubusercontent.com/23094645/30272291-444ee39c-970d-11e7-9ac2-e4a761f79589.png

Then it is stuck in infinite error loop, because restarting the app causes the console and this error to come up immediately. The only way I figured out to stop it is to press Ctrl+` to close console split second before the error pops up on restart of app. 

Hopefully this can be replicated somehow. I dont have any extension except VueJS, but disabling it didnt help. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|31.96GB (19.99GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by Tyriar** [comment]
@inemtsev could you try get a performance profile before the crash happens using devtools (Help > Toggle Developer Tools)?

**Comment by inemtsev** [comment]
Not sure what I'm looking for but here is the screenshot of the result
![capture_p](https://user-images.githubusercontent.com/15311236/37806670-9c48b810-2e17-11e8-9452-cfc6dba43cba.PNG)

**Comment by Tyriar** [comment]
@inemtsev hmm, I'm a little stumped on this one. Could you try reproducing in the Insiders build which is built from the latest code? https://code.visualstudio.com/insiders/

**Comment by inemtsev** [comment]
This is interesting indeed, I uninstalled my VS Code and installed from the link you provided...The crash still happens

**Comment by Tyriar** [comment]
@inemtsev some more follow ups:

- Could you clarify the characteristics of the crash?
  - Does a dialog come up saying the window is not responding?
  - Is the UI responding but just laggy? 
  - Is it just the powershell process that's crashing?
- Does it happen when you run powershell.exe outside of VS Code?
- Does it happen when you set the default shell to cmd.exe inside VS Code?
