### ISSUE TITLE
Ubuntu red squiggles headers even when cpp_properties has been updated. And its supposed to find recursivley anyway.

### ISSUE THREAD

**Issue by chuckeng-isp** [Microsoft/vscode#46308]
Issue Type: <b>Bug</b>

Place header in sub folder "public/mysdk/header.h".
Ensure cpp_properties are set.
Include the header in a cpp file with angle brackets <mysdk/header.h> as you would with an sdk header.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|0, 0, 0|
|Memory (System)|15.55GB (9.18GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.14.1
vscode-m3u|af4|1.0.0
code-gnu-global|aus|0.2.2
githistory|don|0.4.0
Go|luk|0.6.77
vscode-clang|mit|0.2.2
python|ms-|2018.2.1
azure-account|ms-|0.3.3
cpptools|ms-|0.15.0
vscode-arduino|vsc|0.2.11

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
> Reproduces without extensions

We don't ship any C++ support out of the box, there should not be any squiggles in these files unless you have extensions.

**Comment by Tyriar** [comment]
You can report against the cpp extension here https://github.com/Microsoft/vscode-cpptools/issues
