### ISSUE TITLE
Scrolling left and right on Mac trackpad

### ISSUE THREAD

**Issue by redzt** [Microsoft/vscode#46301]
Issue Type: <b>Performance Issue</b>

When scrolling left and right on Mac trackpad, the page always moves up and down a little bit (instead of moving only horizontally). Since one cannot always move the fingers in a perfect horizontal line on the trackpad, ignoring the vertical jitters of the track when scrolling left and right will help a lot.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

**Comment by alexandrudima** [comment]
I have removed all of the massaging we were doing, we should now get what the OS sends our way.
