### ISSUE TITLE
Notification Buttons do not respond to Touchscreen Tap events

### ISSUE THREAD

**Issue by johnbindel** [Microsoft/vscode#46304]
- VSCode Version: 1.21
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Trigger a notification event that has buttons
2. Tap on the buttons

Does this issue occur when all extensions are disabled?: Unknown- I don't know how to trigger a notification without an extension.

Where the registration for click but not tap occurs:
https://github.com/Microsoft/vscode/blob/4ea13164247f4f008a517344d90f7612d09e5c9f/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L437-L446

Where the ActionBar is created:
https://github.com/Microsoft/vscode/blob/4ea13164247f4f008a517344d90f7612d09e5c9f/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L221-L237

Example of how to trigger on tap and click:
https://github.com/Microsoft/vscode/blob/6ad67e2af55e2cefa0aafbff1748151da2508048/src/vs/base/browser/ui/dropdown/dropdown.ts#L55-L57

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/46055
