### ISSUE TITLE
"An update is ready to install" issue. VSCode asks admin permission

### ISSUE THREAD

**Issue by lebed2045** [Microsoft/vscode#46302]
- VSCode
<img width="453" alt="screen shot 2018-03-21 at 6 48 35 pm" src="https://user-images.githubusercontent.com/36878097/37746785-18672268-2d39-11e8-92c1-49e15b52e07d.png">
 Version: 1.21.0 
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Install VSCode to ~/Applications
2. wait for an update

Does this issue occur when all extensions are disabled?: Yes/No
Not sure. 
I've seen this issue was since 2016, so apparently, it wasn't fixed. 
Problems: 
0) there is no feedback info which update/helping tool exactly
1) It *never* should ask admin permissions. 
Thanks

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
