### ISSUE TITLE
[json] provide intellisense for version in bower.json dependencies

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4630]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Create Asp .net core empty project in visual studio.
2. Add some directories under wwwroot folder for client code like JS.
3. Add new item to manage client lib and add bower.json file.
4. Add some client side lib in to bower.json under dependency section like below:

> ![image](https://cloud.githubusercontent.com/assets/17735796/14002399/19404f8e-f109-11e5-85fe-0b25c3b8b733.png)

Actual: Not getting intellisense for version #.
![image](https://cloud.githubusercontent.com/assets/17735796/14002646/7e2e6d58-f10a-11e5-9226-ab2c86dcef4d.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/17735796/14002621/5ec5c966-f10a-11e5-818b-b9ec5c42f49e.png)

**Comment by aeschli** [comment]
I just haven't found a server API yet that would give me all versions. bower/registry#26 is talking about that.

**Comment by vincenzkoop** [comment]
https://github.com/bower/registry/issues/26 I think all referenced issues are closed now and you could try to fix it again. I'm quiet sure that it was working for a short time but now i'm getting just the "latest" proposals.

**Comment by aeschli** [comment]
Still no server APIs for the versions and bower is being replaced by yarn and webpack. No action planed.
