### ISSUE TITLE
[html] Autoclose of tags plain not working

### ISSUE THREAD

**Issue by ecbrodie** [Microsoft/vscode#46310]
- VSCode Version: 1.21.1
- OS Version: 10.13.3

Autoclose of HTML element are just plain not working in VSCode. I discovered this specifically in a JSX file, but it also seems to not be working in HTML files too. As in, I will type `<div>FooBar</` and the `</div>` will not autocomplete. Also, typing `<div>` will not automatically insert a `</div>`. I would expect at least one of these functionality to work out of the box in VSCode. Nope, not working for me.

I have tried reading through as many GH issues related to my problem as I can, including #34307. I have also tried launching VSCode with all extensions disabled. Still not working.

**Comment by aeschli** [comment]
JSX and HTML are different code bases. Please file separate issues.
I'm replying for HTML here, where we automatically add `</div>` both when typing `<div>` as well as `</`.
![autoclose](https://user-images.githubusercontent.com/6461412/37907436-69a3a3ac-3105-11e8-8201-39ac40502be4.gif)

If this doesn't work for you, check that `"html.autoClosingTags": true` is configures.
If this is not the problem, please add a small code sample that shows the problem.

**Comment by ecbrodie** [comment]
I decided to nuke my VSCode configuration and start from scratch. I installed the autoclose tag and rename tag plugins, and those seem to work fine for both HTML and JSX.

Thank you for the reply, but I don't think there's further action to pursue here, so I'll just go ahead and close.
