### ISSUE TITLE
search.exclude not working for node modules when set to "true" explicitly

### ISSUE THREAD

**Issue by mandar24** [Microsoft/vscode#46316]
Issue Type: <b>Bug</b>

I needed to search node modules folders/files in my project. To do so i changed user/workspace settings as 
"search.exclude": {
        "**/node_modules": false
    }
but still its not searching.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|15.91GB (6.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.7
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.2.1
java|red|0.21.0
vscode-icons|rob|7.22.0
perforce|sle|3.1.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
As a test, are they searched if you toggle off the "Use Exclude Settings and Ignore Files" button (bottom right)?

![image](https://user-images.githubusercontent.com/323878/37785522-9b4d3162-2db7-11e8-9011-5ca513e789b9.png)

**Comment by mandar24** [comment]
They are not searched when i toggle off the "Use Exclude Settings and Ignore Files" button.

**Comment by mandar24** [comment]
They are not searched when i toggle off the "Use Exclude Settings and Ignore Files" button.

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by mandar24** [comment]
![image](https://user-images.githubusercontent.com/22298109/38189347-5fde2112-367d-11e8-9796-97fd3a77bf30.png)

**Comment by roblourens** [comment]
It should be searching node_modules. It is not excluding them. Does it search the rest of the folder correctly?

**Comment by mandar24** [comment]
It searches other folders except node_modules files/folders.

**Comment by roblourens** [comment]
Are they covered by a .gitignore file?

**Comment by mandar24** [comment]
Yes.

**Comment by roblourens** [comment]
Then they will be excluded by default. You can disable that with `"search.useIgnoreFiles": false` or by toggling off the "Use Exclude Settings and Ignore Files" button.
