### ISSUE TITLE
Recommend Extensions only offering ESLint

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4631]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. F1 -> ext recommend
2. Shows only ESLint as recommended extensions, without having any extensions installed

If you install ESLint there are no recommendations given even though it is the only installed extension.

**Comment by jrieken** [comment]
@egamma fyi

**Comment by RReverser** [comment]
@vsccarl I think recommendations are based on type of files you were working with. If you didn't work with any projects yet, then there is nothing VS Code can recommend to you.

**Comment by ramya-rao-a** [comment]
What @RReverser said above is right.
At the moment the recommendations are based on the type of files you have worked with.
