### ISSUE TITLE
Find in folder doesn't work

### ISSUE THREAD

**Issue by silverphoenix1110** [Microsoft/vscode#46319]
Issue Type: <b>Bug</b>

"Find in folder" doesn't work. It just find in files, which are opening, not with all files in the folder

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.60GB (7.29GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.0
alignment|ann|0.3.0
scanner-js-twain-wia-javascript-browser-scan|asp|2.0.2
vscode-database|baj|1.5.1
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
compulim-vscode-dictionary|Com|0.0.5
cake-cored|Crh|1.1.2
vue-peek|dar|1.0.2
githistory|don|0.4.0
jquerysnippets|don|0.0.1
gitlens|eam|8.1.1
php-intellisense|fel|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
html-tag-wrapper|hwe|0.2.3
sftp|lix|1.1.4
Go|luk|0.6.77
sqltools|mtx|0.12.1
php-docblocker|nei|1.3.3
vetur|oct|0.11.7
vscode-code-outline|pat|0.0.13
subtle-brackets|raf|2.1.0
pdf|tom|0.2.0
vscode-wakatime|Wak|1.1.26
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Does it work when a different folder is open?

Are the missing files covered by search.exclude settings or .gitignore files?

**Comment by silverphoenix1110** [comment]
Hi, @roblourens
There aren't missing files covered by search.exclude settings or .gitignore files. 
It works when a different folder is open.
This bug sometimes happens, not always.  As I see, It happens when I using "split editors" and close other files

**Comment by roblourens** [comment]
> It works when a different folder is open.

If so, are you sure there aren't exclude settings involved? You can double check by toggling off the "Use Exclude Settings and Ignore Files" button (bottom right)

![image](https://user-images.githubusercontent.com/323878/37785522-9b4d3162-2db7-11e8-9011-5ca513e789b9.png)

**Comment by camflint** [comment]
I can reproduce this issue consistently within a workspace. Only files that are opened are searched, instead of the expected behavior of all files on disk within the search scope. The exclude filter and "search.exclude" are not involved. Turning ripgrep on/off does not make a difference.

**Comment by roblourens** [comment]
Can both of you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders
