### ISSUE TITLE
directory belong to wrong project

### ISSUE THREAD

**Issue by yqjdcyy** [Microsoft/vscode#46318]
Issue Type: <b>Bug</b>

# import several projects into workspace
# click the project and check the detail
# then maybe
- ![微信截图_20180322151156.png](http://otzm88f21.bkt.clouddn.com/c2d9a895-d505-4d43-b7a6-04834c207972.png)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|Memory (System)|15.92GB (7.28GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-table-prettify|dar|2.0.0
vscode-eslint|dba|1.4.7
python|don|0.7.0
Go|luk|0.6.77
python|ms-|2018.2.1
emoji|Per|0.0.3
python|tht|0.2.3

</details>
Reproduces only with extensions

**Comment by isidorn** [comment]
Please follow this instructions on https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
And provide reproducable steps
Also try reproducing with vsocde insiders https://code.visualstudio.com/insiders/
