### ISSUE TITLE
Typescript matchers doesn't recognize tsc output with `pretty` option enabled

### ISSUE THREAD

**Issue by kijowski** [Microsoft/vscode#46324]
- VSCode Version: 1.21.1
- OS Version: Windows 10

Steps to Reproduce:

1. Install tsc 2.7.2
2. Create fresh project with `tsc --init`
3. Create `HelloWorlds.ts`
4. Edit tsconfig.json file and add `"pretty": true`
4. Write some invalid code e.g. `const x: number = 1 + "1";` . There should be a problem reported in problems tab.
5. Close the `HelloWorlds.ts` editor window. Error from problems tab disappear.
6. Run Task > pick the build task
7. After compilation ends there are no problems in the problems tab.
8. Run Task > pick the watch task
9. Compilation ends but `Building...` in the status line doesn't disappear.

Does this issue occur when all extensions are disabled?: Yes

It seems that enabling `pretty` option in `tsconfig` breaks `$tsc` and `$tsc-watch` problem matchers. Enabling this option changes the output of typescript compilation (e.g. timestamp are in square brackets) and this is probably confusing above-mentioned matchers.

There is a connected bug report #44018 but the resolution there went in other direction (multiple lines from terminal #44192).

**Comment by dbaeumer** [comment]
Fixed by tweaking the problem matcher
