### ISSUE TITLE
Auto search - option to search while typing

### ISSUE THREAD

**Issue by liesislukas** [microsoft/vscode#46326]
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: macOS 10.13.3 (17D102)

Steps to Reproduce:

1. open workspace
2. type something in search - it will not execute search till click of Return/Enter or mouse click

Does this issue occur when all extensions are disabled?: Yes

While for some workspaces with tens of thousands of files it would be performance killer for smaller workspaces I would like to have the option to search "live". When I don't know the exact name of the file I could just start typing and search would make it's job.

**Comment by JokerDan** [comment]
If implemented, could it be toggled with a workspace setting and defaulted to 'False' ?

I agree that it could be a nice feature for smaller workspaces.

**Comment by liesislukas** [comment]
in settings :

`search.autoSearch = auto | afterTimeout | off`

**auto** = turn autoSearch to **afterTimeout** if project has <10000 files. Not sure how many files are considered as many for this algorithm. Probably file size is doing impact too.

**afterTimeout** = auto search when "done" typing
Also `search.autoSearchTimeout = 300`
It would mean: if no character input for 300ms - do the search.

**off** = user has submit search input manually like it is now.

**Comment by Sco768** [comment]
I feel like we have opposite experience with search:
1) I open a large file
2) I start typing in a search field and the file starts scrolling automatically to a match of my incomplete query

This is very distracting, especially when I'm trying to construct a search query based in what I see.
And I don't see a search.autoSearch setting anywhere to turn this off.

**Comment by codeitcody** [comment]
I've really been longing for this feature after coming over from WebStorm or IntelliJ!

I had no idea how helpful it was until I didn't have it. It can be a life saver to see search results populate live as you type because you often can't remember the full term or there are many similar terms.

I'd love to see live search come to VS Code too!

**Comment by jbwyme** [comment]
Would love to see this feature as well, it's the biggest reason I'm considering dropping vscode. 

https://nuclide.io/blog/2017/08/31/Code-Search/

**Comment by benyamini** [comment]
This would be great to have. Even after weeks of using vscode I forget that it doesn't autosearch and I will highlight text then do CMD+Shift+F expecting to immediately be shown the results. Hitting the Enter key just doesn't want to get saved in my muscle memory :'(

**Comment by mykolav** [comment]
It would also be great if we could enter the search term into command palette/Quick-Pick's input field and get live results in its list.  

Something like this:  

![image of atom-fuzzy-grep package](https://i.github-camo.com/7819d532ad92f98c1391e464c70d0248f7111b5b/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f67656b73696c6c612f61746f6d2d66757a7a792d677265702f6d61737465722f64656d6f2e676966)

**Comment by arbaes** [comment]
Landed here after searching for how to enable this feature. It seems it's my turn to finally drop the classic `Any news on this ?`

**Comment by lucasvazq** [comment]
```Any news on this ?```
