### ISSUE TITLE
[json] support JSON schema draft 7

### ISSUE THREAD

**Issue by MartyIX** [Microsoft/vscode#46322]
Issue Type: <b>Feature Request</b>

Hi,

I'm watching JSON schema specification progress for a few months as it is adding a great feature: `"if", "then", "else"` support.

I have noticed Draft-07 of JSON schema specification was released a few days ago: http://json-schema.org/draft-07/json-schema-release-notes.html

I hope that Draft-07 will be supported in VS Code in future :-)

Regards,
Martin

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

**Comment by aeschli** [comment]
The schema validation happens here:
https://github.com/Microsoft/vscode-json-languageservice/blob/131bfca1bf2ad90616ea6ecf720a27d01ca58e0a/src/parser/jsonParser.ts#L423

**Comment by aeschli** [comment]
Here's an example of a test:
https://github.com/Microsoft/vscode-json-languageservice/blob/131bfca1bf2ad90616ea6ecf720a27d01ca58e0a/src/test/parser.test.ts#L435

The easiest is to develop this using the tests. 
- check out the `vscode-json-languageservice` repo, `npm install` 
- `npm run test` to compile and run tests
- to debug, open the folding in VSCode and run the `Unit Test` launch config

**Comment by MetaFight** [comment]
Excellent, thanks :)

**Comment by shawnmclean** [comment]
Seems like you guys are writing your own schema validation. Why not use a library like ajv (https://github.com/epoberezkin/ajv-errors)

**Comment by aeschli** [comment]
@shawnmclean We also use it to drive code completion

**Comment by Levertion** [comment]
This appears to have been started in:

Microsoft/vscode-json-languageservice#24.

which was merged in 8229aed327630e8aa3c2f6ac84cdae0ee1fd1d2d. I don't know what other features were added.

**Comment by MartyIX** [comment]
Does it mean that IF/THEN/ELSE part of Draft-07 is supported now?

**Comment by aeschli** [comment]
added for august
