### ISSUE TITLE
[c#] Builtin types not being highlighted in editor

### ISSUE THREAD

**Issue by jamesqo** [Microsoft/vscode#4633]
- VSCode Version: 0.10.11
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. Open VSCode
2. Copy and paste this snippet in:

  ```cs
  using System;
  using System.Collections.Generic;
  using System.Linq;

  namespace FooBar
  {
      public static class Quux
      {
          public static char GetBlah()
          {
              var thing = default(string);
          }
      }
  }
  ```

The keywords `var`, `char`, and `string` will not be highlighted.

Here's an image from my local machine:

![builtins-syntax](https://cloud.githubusercontent.com/assets/9159214/14006971/b938aeb6-f148-11e5-949e-83f27419e92b.PNG)

**Comment by aeschli** [comment]
There's a fix for this in the coming March release.
The Dark/Light (Visual Studio) now show these keywords blue, Dark+/Light+ turquoise (color used for type references).
(It's questionable if 'var' should be considered a type reference, but that's the decision of the C# grammar. To file an issue against the grammar
