### ISSUE TITLE
Issue reporter unresponsive for several seconds

### ISSUE THREAD

**Issue by waldyrious** [Microsoft/vscode#46335]
I thought this had to do with some sort of initial download, but I can reproduce this multiple times. When I click the Help > Report Issue menu entry, the Issue Reporter window starts out blank for several seconds, and the network activity graph (shown as yellow in my system monitor widget) starts spiking:

![screenshot from 2018-03-22 11-56-57](https://user-images.githubusercontent.com/478237/37769429-dc990fd6-2dc8-11e8-83c9-b70655e6ebf9.png)

When the window finally is able to display some content (note from the timestamp at the top that it took about two minutes!), it's noticeable that the network activity also ceases:

![screenshot from 2018-03-22 11-58-05](https://user-images.githubusercontent.com/478237/37769445-eedc3a24-2dc8-11e8-979e-a9b1e1f4793d.png)

From the title, I suspect this might be related to #44736 or #45163, but I'm not sure it's the same issue as either.

I'm on Ubuntu 16.04 LTS, using the Gnome Shell, if it matters.

- VSCode Version: Code 1.21.1 (79b44aa70, 2018-03-14T14:46:30.761Z)
- OS Version: Linux x64 4.13.0-36-generic

**Comment by RMacfarlane** [comment]
Thanks for reporting! I've also been able to reproduce on Ubuntu - for me there's about a 1-2 second delay on load. I've made a change to the loading js that speeds it up.

If you're curious, you can open the dev tools in that window with ctrl + shift + i. 
![screen shot 2018-03-23 at 2 26 51 pm](https://user-images.githubusercontent.com/3672607/37854212-239972fc-2ea7-11e8-9dce-e808d002269c.png)

**Comment by waldyrious** [comment]
That was fast :)

**Comment by waldyrious** [comment]
@RMacfarlane actually, upon further testing I verified that this only happens if I open a folder (File > Open Folder) for a remote directory mounted locally via SFTP (using the system's graphical file browser, in case it matters).

I just tested with fully local folders, and the delay is quite tolerable (barely noticeable, even). On the other hand, with such remote folders the issue reporter window consistently takes several *minutes* to open.

I'm not sure how this new information affects the change you made, in particular whether it would still solve this issue. I can always open a separate issue for the SFTP-related delay, it that would make more sense at this point.

**Comment by RMacfarlane** [comment]
@waldyrious Ah, thanks for the additional info! I don't think my changes will fix that scenario. The reporter collects some metadata information about what types of files are in your workspace for reporting performance issues, so my suspicion is that that process is taking longer for remote files and unintentionally blocking rendering. I'll reopen this.

**Comment by waldyrious** [comment]
Thanks, and sorry for the misleading initial description. Hopefully the commit was an improvement nevertheless :)

Let me know if there's anything I can do to assist in resolving this.

**Comment by RMacfarlane** [comment]
@waldyrious The issue reporter was requesting data about the workspace that was calculated synchronously. This data is only needed for performance issues, so I made a change to only fetch it when actually needed (https://github.com/Microsoft/vscode/commit/f3ba8606e1d3134523cb4a95341dabc491c98f63), and to calculate it asynchronously (https://github.com/Microsoft/vscode/commit/220bf3608e3515e5276c9f77fa94ba348b956fd5). The first change made it into our next release which should be out tomorrow, so the issue should be fixed there for bug reports.
