### ISSUE TITLE
ctrl+z/clrl+y after block mode edit does not follow the (multi-line) cursor to follow the undo/redo steps

### ISSUE THREAD

**Issue by GerbenJdeBoer** [Microsoft/vscode#46332]
Issue Type: <b>Bug</b>

create dummy text1
do block mode edit inside text1
create more dummy text, preferably so much you dont see text1 any more
ctrl + z

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
gc-excelviewer|Gra|2.0.20
python|ms-|2018.2.1
vscode-docker|Pet|0.0.25

</details>
Reproduces only with extensions

**Comment by rebornix** [comment]
@GerbenJdeBoer can you help me understand what's block mode?

**Comment by GerbenJdeBoer** [comment]
https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection

**Comment by alexandrudima** [comment]
Let's track in #6995
