### ISSUE TITLE
Console text not expanding when split containers resized

### ISSUE THREAD

**Issue by dinindu-d** [Microsoft/vscode#46330]
Issue Type: <b>Bug</b>

Open console.
Split it.
Do something for log some data for those consoles.
Resize them.

As below,
![screen shot 2018-03-22 at 4 23 09 pm](https://user-images.githubusercontent.com/34679086/37768090-6c532a02-2df2-11e8-8024-38ccd7052a1f.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.34GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_200753|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-nsp|ada|1.0.1
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
vscode-eslint|dba|1.4.7
vscode-great-icons|emm|2.1.30
auto-rename-tag|for|0.0.15
gdscript|jjk|0.0.2
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
mssql|ms-|1.3.0
cpptools|ms-|0.15.0
cmake|twx|0.0.17
licenser|ymo|1.1.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/23688
