### ISSUE TITLE
Problems browser should try harder to find files

### ISSUE THREAD

**Issue by NeilMacMullen** [Microsoft/vscode#46337]
Please note - this is NOT extension-specific although it's particularly easy to demonstrate when using C++ with GCC as the compiler..

Some build systems have the annoying habit of not emitting the full path of files in their warning/error output.  For example, GCC will only emit the filename rather than the path for warnings.

For example...
`[Warning] ATParser.cpp@245,31: comparison between signed and unsigned integer expressions [-Wsign-compare]`

If these 'bare' filenames are fed to the "PROBLEMS" window (via a ProblemMatcher) they will be displayed but are assumed to be relative to the workspace root(1).  Clicking on the warning then prompts the user to _create_ a file of that name in the workspace root.

It would be preferable if the PROBLEMS window was able to use the same logic that "Goto File/CTRL-P" uses since that seems to have no problem locating the file when I supply the filename.

(1) *Edit* - the behaviour is a little different from what I said - it's not the workspace root that is used but a different folder.  It's a little unclear but perhaps the containing folder of the first file that generates a problem is used?

**Comment by zfields** [comment]
I'm also experiencing this problem. If this feature worked, it would massively help me workflow. Thanks for such an awesome product!

**Comment by sandy081** [comment]
@NeilMacMullen May I know who is generating these problems? Are they coming from an extension or tasks?

**Comment by NeilMacMullen** [comment]
@sandy081  I'm using a VS-Code build task which invokes gcc to build C++ files.  The compiler often emits warnings such as 
Warning: foo.cpp (86,3): unsafe cast …… 
I use a regex-based Problem Matcher in the build task to parse the build output and pass it to the 'Problems' tab in the VS-Code window.

**Comment by dbaeumer** [comment]
Marking as dup of https://github.com/Microsoft/vscode/issues/11663

**Comment by NeilMacMullen** [comment]
@dbaeumer   I looked at the 'duplicate ' issue.  The discussion there seems to focus on various (ugly) ways to try and extract the actual path from the build output.    That is not the intent of this suggestion which is that VS-Code should be able to use the same logic it employs for 'Goto File' to resolve relative path names that have been passed by the problem matcher to the Problems tab.

I respectfully suggest this is not a duplicate.

**Comment by dbaeumer** [comment]
I see your point however I think that every build system provides enough information to detect the correct path to the file that contains the error and we should find ways to leverage this.

I will reopen the issue. Assigning back to @sandy081 since the guessing needs to happen in the problems view.

**Comment by sandy081** [comment]
@dbaeumer Are you saying that Problems view should compute the absolute path from the relative path and open the file? But how will the Problems view know that the given path is relative or absolute? Are there any heuristics?

**Comment by dbaeumer** [comment]
@sandy081 he is basically asking that if the path is not absolute we take the file name and look in (Ctrl+P) if we find a match and suggest that file.

I sill think as commented [here](https://github.com/Microsoft/vscode/issues/46337#issuecomment-376638444) that the system that creates the problem should have enough information to determine the correct path. 

So I am fine if we close this as out of scope.

**Comment by NeilMacMullen** [comment]
@dbaeumer   I don't disagree that the target build system _should_ provide absolute path info but in this case it doesn't! (mbed based on cmake with GCC).  When there's only one file in the project called "brokeness.c" it's a rather frustration user experience when clicking on the problem report gives you an "Unable to open"  dialog (with a rather surprising option to create a file in the root folder).  Ctrl-P _does_ find (and open) the file based on the filename but of course then you don't get the jump-to-line behaviour.

**Comment by sandy081** [comment]
So you want a fall back mechanism in Problems view when a file is not found, open file quick pick to open the file.

**Comment by NeilMacMullen** [comment]
@sandy081 I don't understand your suggestion I'm afraid. The whole point of this feature request is that it should be possible to navigate directly to a file _and line number_ by clicking on the problem report even when the filename is not an absolute path.

**Comment by NeilMacMullen** [comment]
Understood - thank you.
