### ISSUE TITLE
Improve discoverability of search filters in the extensions sidebar

### ISSUE THREAD

**Issue by waldyrious** [Microsoft/vscode#46333]
I am having trouble figuring out / remembering which @-filters I can use in the search box of the extensions sidebar. Some of the options are automatically filled by selecting one of the entries in the "..." menu (e.g. "Show Installed Extensions" auto-fills the search box with `@installed`), which is great; but AFAIK I can't type an `@` and then hit tab or some other key combination, and have a list of possible completions show up.

The ["Search for an extension"](https://code.visualstudio.com/docs/editor/extension-gallery#_search-for-an-extension ) section of the documentation only mentions the `@recommended` filter; the only other filter mentioned in that page is `@outdated`, in the "Update an extension" section. Perhaps there are other pages in the documentation that cover this? If so, they should be linked from the extension marketplace page (I'd be happy to submit a PR for that).

But even with adequate documentation, IMHO some sort of completion mechanism in the extension sidebar's search field would be the ideal resolution to this issue.

- VSCode Version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
- OS Version: Linux x64 4.13.0-36-generic

**Comment by ramya-rao-a** [comment]
As a first step, we can definitely update the documentation.

**Comment by ramya-rao-a** [comment]
The docs have been updated to include all the filters. See https://code.visualstudio.com/docs/editor/extension-gallery?pub=HookyQR&ext=beautify#_extensions-view-filters
