### ISSUE TITLE
folder name with special char was hidden in the side bar. 

### ISSUE THREAD

**Issue by bondBo** [Microsoft/vscode#46336]
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: mac 10.3.3

Steps to Reproduce:

1.  Special char was hidden , i forget how to write the special char. maybe "?" 

snapshot:
![image](https://user-images.githubusercontent.com/2473926/37768087-5d4c4420-2e07-11e8-9413-ddb7023b82d8.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
This works fine on my mac.
Can you reproduce this issue with vscode insiders https://code.visualstudio.com/insiders/
