### ISSUE TITLE
Output tab should not automatically steal focus from integrated terminal tab

### ISSUE THREAD

**Issue by emveeoh** [Microsoft/vscode#46343]
- VSCode Version:
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:30.761Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:
Ubuntu 16.04x

Steps to Reproduce:

1. Php Validation runs and sends output to the OUTPUT tab in VS CODE. This steals the focus away from the INTEGRATED TERMINAL tab for the duration of the output. In some cases, this can last for minutes, which makes it impossible to use the TERMINAL until it finishes.

Ideally, this would not happen. Instead, there should be a notification indicator on the OUTPUT tab upon new output. However, focus would remain on the currently-active tab. 

Alternatively, a user setting could be added to override the automatic tab focus switching.

Thank you!

**Comment by Tyriar** [comment]
I agree, this sort of thing also annoys me. You should file an issue against the PHP extension.
