### ISSUE TITLE
IntelliSense is jumping out of window, when editing multiple occurrences, after "."

### ISSUE THREAD

**Issue by Jusys** [Microsoft/vscode#46342]
- VSCode Version: 1.21.1
- OS Version: Windows 7 32bit

Steps to Reproduce:

0. JavaScript code.
1. select all occurrences of some item in your code (ctrl+F2 or ctrl+D or ctrl+shift+L). try to replace them,
while positioning cursor not on the first occurrence.
2. try to replace these occurrences with some JS Object. see how IntelliSense window jumps to the first occurrence, when selecting object's property.
3. really annoying when first occurrence is not visible.

Does this issue occur when all extensions are disabled?: I have no extensions installed

Active line:
![1](https://user-images.githubusercontent.com/30110941/37772172-80b1ba14-2de2-11e8-9ea1-1079b3f9895b.jpg)

Selected all occurrences (ctrl+f2), active line has not changed:
![2](https://user-images.githubusercontent.com/30110941/37772178-851ea9ea-2de2-11e8-9bbd-7e33fff75940.jpg)

Starting to replace - IntelliSense's position is good, active line has not changed:
![3](https://user-images.githubusercontent.com/30110941/37772389-2756dea8-2de3-11e8-94d1-cb811d8de790.jpg)

After dot "." suddenly IntelliSense window jumps to the first occurrence and active line changes:
![4](https://user-images.githubusercontent.com/30110941/37772529-92ef0668-2de3-11e8-987b-ef87732d8814.jpg)

When first occurrence is not visible, IntelliSense is not visible too:
![5](https://user-images.githubusercontent.com/30110941/37772953-f27653b0-2de4-11e8-9c70-e11ff952a2de.jpg)

**Comment by ramya-rao-a** [comment]
I can repro this in the stable but not in the Insiders. Can you try the latest [Insiders](https://code.visualstudio.com/insiders) ?

**Comment by Jusys** [comment]
Tested latest Insiders (1.22.0):

IntelliSense window does not change position anymore - it's working correctly.
But after selecting a suggestion from instellisense window by pressing [tab], active line still changes:
![7](https://user-images.githubusercontent.com/30110941/37823178-5f51366a-2e91-11e8-9524-b36cd8f97341.jpg)

**Comment by ramya-rao-a** [comment]
That seems to happen even when doing a multi-cursor edit.
cc @jrieken

**Comment by alexandrudima** [comment]
To the verifier: Use ctrl+D from the last `parent` and then accept a suggestion. The current line highlight should stay on the last `parent`:

```

function blabla()
{
    let human = parent.alert;
    //some code
}

function blabla2()
{
    let human = parent.alert;
    //some code
}

function blabla3()
{
    let human = parent.alert;
    //some code
}
```

![kapture 2018-03-28 at 12 31 01](https://user-images.githubusercontent.com/5047891/38023961-ea4830fc-3283-11e8-91c2-528c43306a91.gif)
