### ISSUE TITLE
vscode does not honor http_proxy and https_proxy environment variables on Linux

### ISSUE THREAD

**Issue by certik** [Microsoft/vscode#46348]
- VSCode Version: 1.21.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Run `code`
2. Click on "Source Control" (Ctrl-Shift-G)
3. More -> Install Additional SCM Providers...

An error will pop up "An unknown error occurred. Please consult the log for more details.".

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

### Workaround

Start `code` as follows:
```
code --proxy-server="http=$http_proxy;https=$https_proxy"
```
Then everything works.

I think this is a bug, as `code` should honor the `http_proxy`, `https_proxy` (and also `no_proxy`) variables automatically just like every other program that is launched from the command line like `wget`, `apt-get`, etc.

**Comment by certik** [comment]
Until this is fixed, a solution for me is to put this into the `~/.bashrc`:
```bash
alias code="code --proxy-server=\"http=$http_proxy;https=$https_proxy\" --proxy-bypass-list=\"localhost;127.0.0.1;*CORPORATE_DOMAIN\""
```
(Change `CORPORATE_DOMAIN` for your company domain.)

Now everything seems to be working. Simply use `code` or `code <path>` from the command line.

The option `--proxy-bypass-list` unfortunately expects the addresses in a different format than the linux `no_proxy` environment variable uses, so that's why one has to specify those by hand.

**Comment by joaomoreno** [comment]
Docs: https://code.visualstudio.com/docs/setup/network

**Comment by certik** [comment]
@joaomoreno I used those docs to figure out a workaround above, but those docs are insufficient to determine the answer to this bug report. I am happy to submit a PR improving the docs, but in order for me to do that, can you please confirm, that the below is correct:

* vscode will only support proxy settings via Chromium setup
* vscode will not support `http_proxy`, `https_proxy` and `no_proxy`, unless Chromium itself supports it

**Comment by joaomoreno** [comment]
@certik That is correct.
