### ISSUE TITLE
Wrong documentation window size when using Markdown with base64 images

### ISSUE THREAD

**Issue by qutreson** [Microsoft/vscode#46349]
- VSCode Version: 1.22.0-insider
- OS Version: Win10

We recently moved in our extension to using MarkupContent in order to display our intellisense documentation as specified on the Language Server Protocol [specs](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md).

We did it in order to display images in our completion item documentation. We are doing this by using Markdown and base64 images `![MyImage](data:image/png;base64,myImageValueInBase64)`. However, as you can see below, the size of the documentation panel is not correct when displaying the image the first time (when visiting the second time, this is fixed).

![vscoderesizing](https://user-images.githubusercontent.com/31541422/37781637-607b24e2-2df1-11e8-8b46-f3373b0d5d06.gif)

Steps to Reproduce:
1. Send a Markdown Documentation containing a base64 image as CompletionItem documentation.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Do you have this extension published? If so, can you share the details so that I can get a repro?
