### ISSUE TITLE
React JSX code completion unfiltered

### ISSUE THREAD

**Issue by wolfgangmeyers** [Microsoft/vscode#46345]
- VSCode Version: 1.21.1
- OS Version: Mac OSX 10.13.3
Typescript version 2.7.2

Steps to Reproduce:

1. Author a react component in a .tsx file
2. use ctrl+space to trigger code completion

Only react component properties should show, but many others show as well.

**Comment by wolfgangmeyers** [comment]
![image](https://user-images.githubusercontent.com/1783800/37774194-d1b3da00-2d9c-11e8-93f6-806adfbed14f.png)

**Comment by mjbvz** [comment]
Duplicate of #43812
