### ISSUE TITLE
Hover on path doesn't show which part of path is broken when typo in path

### ISSUE THREAD

**Issue by liesislukas** [Microsoft/vscode#46341]
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: macOS 10.13.3 (17D102)

Steps to Reproduce:

NodeJS project.

Require a file:
`const foo = require('./../some/path/to/file/foo');`
If path is **all** correct i can hover on any path element and see content preview of final file + hovered path element is highlighted.

If the path is **not** all correct - I can't hover any path elements and get hint of which part of the path is bad.

e.g. there is a typo: `const foo = require('./../some/bad_path/to/file/foo');`

I expect to hover `..` and `some` words and see highlighted words meaning that folder is found.
I expect to hover on `bad_path` or any following elements and not see a highlighted word which means file/folder not found.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22837
