### ISSUE TITLE
Output Panel constantly pops up with error when accessing files

### ISSUE THREAD

**Issue by tschofen** [Microsoft/vscode#46344]
Issue Type: <b>Bug</b>

Whenever I open quickselect to open a file (cmd-T), the output panel pops up with the following error:

[Error - 08:32:24] Request workspace/symbol failed.
  Message: Request workspace/symbol failed with message: Cannot read property 'offset' of null
  Code: -32603 

Is there any way I can stop the output panel from opening up? On a small screen it's especially annoying.

I have a variety of workspaces that I use and all show the same issue.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by bpasero** [comment]
@tschofen what file extension is the file you open? can you share a screenshot?

**Comment by tschofen** [comment]
Working on a standard web project with .js, .html, .less, .css…). However, I’m not typing extensions.
It seems to happen regardless of file type

**Comment by tschofen** [comment]
Aha…it looks like CSS Peek is the reason for those errors.

Odd that disabling the extensions from within Code didn’t show the same results.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
