### ISSUE TITLE
Terminal memory leak

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#46356]
Terminal references are retained on the renderer side after being destroyed

Upstream: https://github.com/xtermjs/xterm.js/issues/1341

**Comment by gengjiawen** [comment]
I don't know if it is related, when I clone https://github.com/JakeWharton/butterknife.git, and run `.\gradlew assembleAndroidTest`, vs code will not responding after some time, happens every time.

**Comment by Tyriar** [comment]
@gengjiawen definitely not related to this issue, this is a fairly small memory leak where the terminal JS objects aren't being released when a terminal is *killed*.

**Comment by Tyriar** [comment]
It's more likely a problem with the file watcher https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-watcher

**Comment by Tyriar** [comment]
This should be fixed now, you can verify using the heap profiler in devtools, see https://github.com/xtermjs/xterm.js/issues/1341#issue-306690923

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/commit/f6e82b7ce8f802e93819467ef961188589789c71, the majority of the work for this was done upstream https://github.com/xtermjs/xterm.js/pull/1525

**Comment by Tyriar** [comment]
To clarify on repro steps:

1. Open several terminals
2. Open devtools
3. Go to memory tab
4. Record a snapshot
5. Search the snapshot for "Terminal", you should see an entry named "Terminal"
6. Close all the terminals
7. Record another snapshot
8. Search the snapshot for "Terminal", you should **not** see an entry named "Terminal"
