### ISSUE TITLE
Extension host terminated unexpectedly. Code: 3221225477 Signal: null vscode how to fix

### ISSUE THREAD

**Issue by ebotchway** [Microsoft/vscode#46359]
Issue Type: <b>Bug</b>

****The problem is the python extensions and the git-lens and git supercharge extensions please have a look at them. When i took those extensions off it is much better now but i need the python especially******

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|Memory (System)|5.94GB (2.02GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.1
php-debug|fel|1.12.2
php-intellisense|fel|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
beautify|Hoo|1.3.0
phpcs|ika|1.0.5
MagicPython|mag|1.0.12
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
vscode-apache|mrm|1.1.1
debugger-for-chrome|msj|4.2.1
vetur|oct|0.11.7
vscode-icons|rob|7.22.0
code-settings-sync|Sha|2.9.0
guides|spy|0.9.1
code-spell-checker|str|1.6.5
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
You should report to the problem extensions, the extension authors should fix the issues.

https://github.com/Microsoft/vscode-python
https://github.com/eamodio/vscode-gitlens
