### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by RandallFlagg** [Microsoft/vscode#46355]
Hi, After working for some time the CPU starts to work at 100%.
Attached is the cpuprofile.

[CPU-20180322T170458.675Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1838560/CPU-20180322T170458.675Z.cpuprofile.txt)

Currently Running Processes:

pid | CPU % | Memory (MB) | Name
-- | -- | -- | --
7736 | 0 | 79 | code main
1104 | 1 | 63 | -- shared-process
1120 | 0 | 186 | -- window (Running Extensions - TestsLibrary - Visual Studio Code)
3112 | 47 | 129 | ---- extensionHost
6588 | 0 | 24 | ------ electron_node htmlServerMain.js
8476 | 0 | 5 | ------ electron_node jsonServerMain.js
10772 | 0 | 35 | ------ electron_node eslintServer.js
12272 | 0 | 626 | ------ electron_node electronForkStart.js tsserver.js
9376 | 1 | 3 | -------- electron_node typingsInstaller.js tsserver.js typesMap.js
3340 | 0 | 11 | ---- searchService
11916 | 0 | 4 | ---- watcherService
14232 | 0 | 1 | ------ console-window-host (Windows internal process)
12888 | 0 | 0 | ---- electron-crash-reporter
3916 | 0 | 83 | -- gpu-process
5448 | 0 | 44 | -- shared-process
5764 | 1 | 72 | -- powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'code.exe' -MaxSamples 3}"
11568 | 0 | 7 | ---- console-window-host (Windows internal process)

My Workspace Stats:

|  Window (Running Extensions - TestsLibrary - Visual Studio Code)
|    Folder (TestsLibrary): 4221 files
|      File types: js(1190) flat(1101) xml(277) json(256) png(238) html(209)
|                  less(180) scss(133) css(94) edge(72)
|      Conf files: package.json(11) launch.json(1) settings.json(1)
|                  jsconfig.json(1)

My Extensions:

Extension | Author (truncated) | Version
-- | -- | --
vscode-css-formatter | aes | 1.0.1
vscode-caniuse | aka | 0.5.3
project-manager | ale | 0.24.1
html-class-suggestions | And | 1.0.7
vscode-processes | and | 0.0.5
vscode-color | ans | 0.4.5
vscode-refresh-html | baj | 0.0.2
regex | chr | 0.1.0
jsrefactor | cms | 2.11.6
vscode-svgviewer | css | 1.4.3
vscode-eslint | dba | 1.4.7
gitlens | eam | 8.1.1
vscode-html-css | ecm | 0.2.0
EditorConfig | Edi | 0.12.1
vscode-npm-script | eg2 | 0.3.3
vscode-great-icons | emm | 2.1.27
json-tools | eri | 1.0.2
vscode-solution-explorer | fer | 0.2.8
auto-close-tag | for | 0.5.6
auto-rename-tag | for | 0.0.15
live-html-previewer | hdg | 0.3.0
svgeditor | hen | 1.0.0
beautify | Hoo | 1.3.0
adonisjs-snippets | Hri | 1.0.2
output-colorizer | IBM | 0.1.2
ilspy-vscode | ics | 0.3.0
relativepathrefactor | jak | 0.9.0
vscode-nuget-package-manager | jmr | 1.1.6
svg | joc | 0.0.9
uiflow | kex | 0.4.2
typelens | kis | 1.5.0
refactorix | kri | 0.3.6
vscode-simple-icons | Lau | 1.8.2
vue | liu | 0.1.5
edge | luo | 0.1.4
dotenv | mik | 1.0.1
vscode-less | mrm | 0.6.3
vscode-scss | mrm | 0.6.2
debugger-for-chrome | msj | 4.2.0
debugger-for-edge | msj | 0.4.1
color-highlight | nau | 2.3.0
vetur | oct | 0.11.7
laravel-blade | one | 1.17.0
vscode-code-outline | pat | 0.0.13
material-icon-theme | PKi | 3.2.3
show-offset | ram | 0.0.3
searchdocs | rob | 0.0.3
MDTools | sea | 1.0.1
git-merger | sha | 0.3.7
code-settings-sync | Sha | 2.9.0
markdown-preview-enhanced | shd | 0.3.2
vscode-csstree | sme | 0.6.0
terminal-tabs | Tyr | 0.1.1
vscode-todo-highlight | way | 0.5.11

- VSCode Version: 1.20.1 x64
- OS Version: Windows 10 x64 -1703

Steps to Reproduce:
Don't know.
It happens to me after some time of working.

Does this issue occur when all extensions are disabled?: Don't know
I have no idea if this can be reproduced without extensions as it is happening at random times and I tried a few times.

The process also stays in memory with the same CPU usage even after exiting the VSCode app.

**Comment by Tyriar** [comment]
> 3112 | 47 | 129 | ---- extensionHost

This means that an extension is causing the slow down. You will probably have to selectively disable them to find the problem extension.

**Comment by RandallFlagg** [comment]
@Tyriar can you provide a way to hunt the faulty extension or my best shot is a binary search?

**Comment by Tyriar** [comment]
@RandallFlagg I think binary search is the best way right now unfortunately since all extensions are run in a single process.

**Comment by RandallFlagg** [comment]
Thanks
