### ISSUE TITLE
Gaps on the ruler when adding new lines

### ISSUE THREAD

**Issue by spywhere** [Microsoft/vscode#4635]
- VSCode Version: 0.10.11 (0.10.11) [f291f4ad600767626b24a4b15816b04bee9a3049]
- OS Version: El Capitan 10.11.3 (15D21)

Steps to Reproduce:
1. Set the editor settings to show ruler (in my case is 80)
2. Open a new window or file
3. Try adding a lot of new lines
4. There is a gap on the ruler

![vscode](https://cloud.githubusercontent.com/assets/1087399/14009173/edddf842-f1bb-11e5-9d18-9bd40b81530b.png)

**Comment by alexandrudima** [comment]
This has been fixed in the meantime.
