### ISSUE TITLE
auto import of index files appends 'index' to the filepath

### ISSUE THREAD

**Issue by mike-robertson** [Microsoft/vscode#46354]
- VSCode Version: 1.21.1
- OS Version:

Steps to Reproduce:

1. use auto import to import something that comes from a file named `index.ts`/`index.js`
2. The import statement will look like `import { blah } from './path/to/file/index;' instead of 'import { blah } from './path/to/file`

Is it possible to at least provide a configuration to allow you to not append `index` to the filepath? Or maybe there already is one and I am just missing it.

**Comment by mjbvz** [comment]
What does your `jsconfig` / `tsconfig` look like?

**Comment by mike-robertson** [comment]
@mjbvz Here's my tsconfig:
```json
{
    "compilerOptions": {
        "outDir": "./dist/",
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "module": "es2015",
        "moduleResolution": "node",
        "target": "es5",
        "jsx": "react",
        "sourceMap": true,
        "lib": [
            "es2015",
            "dom"
        ],
        "allowJs": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

For what it's worth, I did need to make my moduleResolution `node` to even find `index` files. I'm using webpack to bundle, so it bundled fine, but typescript itself would have errors on its own trying to resolve those modules.

**Comment by mjbvz** [comment]
This appears to be fixed in the latest VS Code versions. Note that you do need to set the baseUrl in the `tsconfig.json`:

```json
{
    "compilerOptions": {
        "outDir": "./dist/",
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "module": "es2015",
        "moduleResolution": "node",
        "target": "es5",
        "jsx": "react",
        "sourceMap": true,
        "lib": [
            "es2015",
            "dom"
        ],
        "baseUrl": ".",
        "allowJs": true
    },
    "exclude": [
        "node_modules"
    ]
}
```
