### ISSUE TITLE
[css] CSS fonts module level 4 support

### ISSUE THREAD

**Issue by robmck-ms** [Microsoft/vscode#46365]
Please add support for syntax-validation and completion for the CSS fonts module level 4 (https://www.w3.org/TR/css-fonts-4/), including new properties like font-variation-settings and font-optical-sizing.

**Comment by connorshea** [comment]
All of these are in mdn/data, and I'm getting completions for them in VSCode, so I think this is complete?

They don't provide validation or value suggestions, though.

**Comment by octref** [comment]
I believe after the recent update, these are available now. @robmck-ms Do you need more or can I close this issue?

![image](https://user-images.githubusercontent.com/4033249/47463719-e06de000-d79b-11e8-96a5-379f0ac5ff6c.png)

![image](https://user-images.githubusercontent.com/4033249/47463726-e5cb2a80-d79b-11e8-869b-0a274064fe0b.png)

**Comment by connorshea** [comment]
@octref I guess this can be closed?

**Comment by octref** [comment]
The feeling of shipping features without yourself knowing 🤣
