### ISSUE TITLE
macOS: Provide a richer path hierarchy when command-clicking the window title

### ISSUE THREAD

**Issue by dnicolson** [Microsoft/vscode#46361]
- VSCode Version: 1.21.0
- OS Version: macOS 10.13.3 (17D102)

In native Carbon/Cocoa apps command-clicking the window title shows a path hierarchy with proper names and icons. While it may not be possible within an Electron app, the path names could be improved along with icons.

As an example, here is how it appears in Sublime Text:
<img width="186" alt="screen shot 2018-03-22 at 20 03 56" src="https://user-images.githubusercontent.com/2276355/37793676-9e8a69dc-2e0f-11e8-8ae7-3d952da1fff9.png">

And VSCode:
<img width="98" alt="screen shot 2018-03-22 at 20 04 19" src="https://user-images.githubusercontent.com/2276355/37793678-9ea4a5c2-2e0f-11e8-96c0-ea468c1dfa33.png">

**Comment by bpasero** [comment]
This is unlikely to happen due to missing support in Electron, but as a workaround you can configure: `"window.titleBarStyle": "native"`
