### ISSUE TITLE
Support  "moving" a tab to (or opening a new file in) a new split.

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/vscode#46369]
### Issue Type
Feature Request

### Description

After "Split Editor" creates a new split, it leaves the original tab open so you have the file open twice.  That'se useful if you want to edit two parts of the same file at the same time without flipping between tabs.  However, there are two use cases for splits where leaving the original tab open results in extra work:

* move a tab to a split so you can edit it and a different tab at the same time without flipping between tabs
* similarly, open a file in a new split (again to avoid flipping between tabs)

Currently, respectively:

* you have to manually close the old tab manually (I keep having to do this)
* you have to open the file manually after splitting and then close the tab that was created by the split 

FWIW, my experience with splits comes from vim.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.4.0-116-generic

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/37844669-d0031068-2ec8-11e8-9a71-0a0a6f607093.png)
