### ISSUE TITLE
Add an obvious way to create a workspace for a new project.

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/vscode#46363]
### Issue Type
Feature Request

### Description

While using VSCode, I wanted to start a new project.  I did not see an obvious option in the "File" menu to support this.  "New File" did not sound right because the editor did not know about any workspace folder yet.  "Open *" and "Add folder to workspace" had the same problem, plus I hadn't created any folder for the project yet.  In the end I left the editor, manually created the folder, and then back in the editor used "Add folder to workspace".

If I had seen "New Workspace" in the "File" menu then I would have used it immediately and would have had 0 confusion (assuming it simply created the folder for me).   That was the first thing I looked for.  The second thing I looked for was a "Create Folder" in the "Add folder to workspace" dialog.  That was missing as well.

While this is a minor thing, I bring it up because it stood out to me as a new VSCode user, particularly in contrast to an otherwise seamless experience.  Thanks for the hard work!

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.4.0-116-generic

**Comment by bpasero** [comment]
> In the end I left the editor, manually created the folder, and then back in the editor used "Add folder to workspace".

I think that is about the right kind of flow for VS Code. We would probably not introduce any more heavyweight ways to create workspaces.

**Comment by ericsnowcurrently** [comment]
While I recognize the desire to keep VSC lean and focused, I'll argue that in this particular case the status quo is insufficient.  I also don't mean to blow this out of proportion. :)  If adding a "New Project" option (IMO the most effective solution) is off the table then at least offer a "New Folder" button in the file dialog that pops up for "Add folder to workspace".  Also consider adding something like the following on the start page:

    To create a new workspace first create the workspace folder manually and then "Add folder to workspace".

The alternative (the status quo) is that new users are immediately confused when they want to create a new workspace.  That's pretty early in their experience with VSC to be leaving a bad impression.

FWIW, I was in a training session yesterday where several other people had the same reaction that I did when they went to create a new workspace.
