### ISSUE TITLE
Inconsistent Webpack config file icon

### ISSUE THREAD

**Issue by fab1o** [Microsoft/vscode#46366]
The icon displaying the type of file for webpack config is not consistent.

- VSCode Version: 1.22.0-insider
- OS Version: Windows 10

![files](https://user-images.githubusercontent.com/6663243/37799366-e5da3016-2df5-11e8-9ffd-e92a9b687843.jpg)

**Comment by fab1o** [comment]
1.22.0-insider

**Comment by fab1o** [comment]
Closing this as I realized it is not vscode but [seti ui](https://github.com/jesseweed/seti-ui/issues/486)

**Comment by aeschli** [comment]
The seti theme is derived from https://github.com/jesseweed/seti-ui.
Please make a request against that repository.

**Comment by fab1o** [comment]
for ref: https://github.com/jesseweed/seti-ui/issues/486
