### ISSUE TITLE
[Feature Request] Add different key for workbench.action.terminal.focusNext for split terminals

### ISSUE THREAD

**Issue by nicolinux** [Microsoft/vscode#46364]
Right now the key `workbench.action.terminal.focusNext` is used for both, switching the focus to the next terminal *and* (f available) switch to the next split terminal.
It would be great if these would be different so one can key bindings for switching between terminals and in addition between split terminals.

**Comment by Tyriar** [comment]
@nicolinux `workbench.action.terminal.focusNext` is unbound by default, is the conflict coming from your keybindings.json file?

**Comment by nicolinux** [comment]
@Tyriar 
The problem is that this key triggers both, switching to the next terminal (the terminal was created by clicking on the + button on the terminal status bar) *and* switching to the next split terminal if the actual terminal has two split terminals.
I have this in my keybindings.json file:

```
    {
        "key": "alt+cmd+right",
        "command": "workbench.action.terminal.focusNext",
        "when": "terminalFocus"
    },
```
Ideally I'd like to be able to switch to another terminal with one key combo and if the actual terminal has two split terminals, switch between the split terminals with another key combo.

**Comment by Tyriar** [comment]
@nicolinux you can unbind default keybindings by prefixing the command with `-`:

```js
{ "key": "alt+cmd+down",          "command": "-workbench.action.terminal.focusNextPane",
                                     "when": "terminalFocus" },
{ "key": "alt+cmd+right",         "command": "-workbench.action.terminal.focusNextPane",
                                     "when": "terminalFocus" },
```

**Comment by nicolinux** [comment]
Thanks for the hint. Just for reference (if you happen to land here after googling it). I have configured the following behaviour in my `keybindings.json`:
1. ctrl+tab switches between editor and integrated terminal
2. shift+tab switches between split terminals
3. cmd+alt+right/left switches between integrated terminals

```
    {
        "key": "ctrl+tab",
        "command": "workbench.action.focusActiveEditorGroup",
        "when": "terminalFocus"
    },
    {
        "key": "ctrl+tab",
        "command": "workbench.action.terminal.focus",
        "when": "editorTextFocus"
    },        
    {
        "key": "shift+tab",
        "command": "workbench.action.terminal.focusNextPane",
        "when": "terminalFocus"
    },
    {
        "key": "alt+cmd+right",
        "command": "workbench.action.terminal.focusNext",
        "when": "terminalFocus"
    },
    {
        "key": "alt+cmd+left",
        "command": "workbench.action.terminal.focusPrevious",
        "when": "terminalFocus"
    },

```
