### ISSUE TITLE
I see two search views

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46368]
![image](https://user-images.githubusercontent.com/323878/37800401-e6a16bf6-2ddf-11e8-867a-86605c0a172f.png)

I don't know how this happened. I have been switching search.location often lately, it's currently set to the default, so the sidebar one is the "real" panel. Reloading the window doesn't fix it.

My guess is that the search panel was persisted as the active panel, or something?

I get errors in devtools when showing or hiding either one, but no other useful errors.

Hiding panel or sidebar:

```
TypeError: Cannot read property 'id' of undefined

t (compositeBarActions.ts:60)
t (panelActions.ts:160)
t.create (types.ts:166)
e._createInstance (instantiationService.ts:120)
e.createInstance (instantiationService.ts:73)
getActivityAction (panelPart.ts:83)
e.toAction (compositeBar.ts:380)
(anonymous) (compositeBar.ts:306)
e.updateCompositeSwitcher (compositeBar.ts:306)
e.layout (compositeBar.ts:505)
t.layoutCompositeBar (panelPart.ts:251)
t.layout (panelPart.ts:239)
e.layout (layout.ts:674)
(anonymous) (workbench.ts:863)
then (winjs.base.js:1581)
e.setSideBarHidden (workbench.ts:851)
t.run (toggleSidebarVisibility.ts:33)
(anonymous) (actions.ts:114)
```

**Comment by isidorn** [comment]
I have pushed a probably fix for this that the remove composite also makes sure it is properly deactivated.
To verify: please make sure you can not reproduce this behavior by changing panel position. And make sure changing panel / viewlet location still keps the active viewlets / panels shown in composite bars

@roblourens you might still be in bad shape after the fix, for that clear storage of `workbench.panel.pinnedPanels` and `workbench.activity.pinnedViewlets`
