### ISSUE TITLE
Caret move to the end of html document on save, instead of staying at its current location

### ISSUE THREAD

**Issue by alfgaar** [Microsoft/vscode#46360]
Caret move to the end of html document on save, instead of staying at its current location

**Comment by garyking** [comment]
Works fine for me. 

![html](https://user-images.githubusercontent.com/343940/37795379-ae2ef198-2dea-11e8-82cc-7cdcc283a4e5.gif)

**Comment by Tyriar** [comment]
I suspect it's an extension you have installed that's causing the issue as many extensions format on save.
