### ISSUE TITLE
Parsing error on template string

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#4636]
- VSCode Version: 0.10.11
- OS Version: OS X 10.10.5

https://github.com/unional/tslint-config-unional/blob/master/gulpfile.js#L25
![image](https://cloud.githubusercontent.com/assets/3254987/14010122/a3caf0b4-f14f-11e5-977c-efedb8e0d1f0.png)

**Comment by jrieken** [comment]
@unional I assume this is with the tslint extension, right?

**Comment by unional** [comment]
Doesn't seems like it. If it is linter, it would have prefix with `[eslint] ...`. Let me double check.

**Comment by unional** [comment]
Argh... it is. `tslint` prefix with `[tslint]...` but `eslint` does not. The `eslint` for `atom` does prefix. Will file TWO issues there. 

Sorry for the invalid issue.

**Comment by unional** [comment]
https://github.com/Microsoft/vscode-eslint/issues/58
https://github.com/Microsoft/vscode-eslint/issues/59

**Comment by jrieken** [comment]
Thanks for getting back to me

**Comment by unional** [comment]
Thanks for listening to my mumbo....to the wrong group! :rose:
