### ISSUE TITLE
Remove unneeded space(lead to trailing space) when insert multi new lines

### ISSUE THREAD

**Issue by Treri** [Microsoft/vscode#4637]
- VSCode Version: 0.10.11
- OS Version:
OS X 10.11.2
Steps to Reproduce:

If I have these
![image](https://cloud.githubusercontent.com/assets/2631733/14012046/09d6eaaa-f1de-11e5-9458-3b000bbe04e4.png)

Then I insert multi new lines. because Code auto indent, so I get multi trailing space.
![image](https://cloud.githubusercontent.com/assets/2631733/14012112/9ea637f8-f1de-11e5-9762-3705ec04ab8c.png)

The expected output is below
![image](https://cloud.githubusercontent.com/assets/2631733/14012125/ae2d9c98-f1de-11e5-9676-9f84d280bd7c.png)

In Sublime Text, if I insert multi new line, only current line will have trailing space. like this

![image](https://cloud.githubusercontent.com/assets/2631733/14012096/79ba8fb6-f1de-11e5-8785-5a12c90284db.png)

**Comment by jrieken** [comment]
@Treri For that there is a setting to remove trailing whitespace on save

**Comment by Treri** [comment]
@jrieken Year, I know this setting.

But Suppose we are editing a very simple markdown file. Two trailing space will make a new line(will create  a `<br />` tag).
If we set Code to remove trailing space on save, the wanted trailing spaces will also be removed.

**Comment by outcoldman** [comment]
@jrieken this usually is not want you want, as people will start hating you for that.

Assume that you are working with legacy code, where a lot of trailing spaces left, or maybe you have plenty folks on the team who do not care about left spaces. Also imagine that you are modifying Nk lines file. If you will kill all trailing spaces at once - you will cause a lot of confusion in git blame, plus people will start to hate you for a lot of merge conflicts.

**Comment by alexandrudima** [comment]
Thanks to @outcoldman this has now landed with PR #5423 . It will most likely come out with the May release in about a month.
