### ISSUE TITLE
tsc watch output is not scrollable in integrated terminal

### ISSUE THREAD

**Issue by patrickhulce** [Microsoft/vscode#46375]
Issue Type: <b>Bug</b>

1. Open an integrated terminal on a typescript project
2. Run `tsc -w`
3. Save a file to trigger re-compilation
4. Attempt to scroll up with mousewheel to see the output of the last compilation

Expected: The terminal scrolls up

Actual: The terminal is not scrolled

Apologies if this isn't the right place to be filing as it's the intersection of multiple libs at play here, but it works in iTerm ~~and Mac terminal~~. Seems to be an interplay with tsc's 2.7 new stick to bottom terminal clearing and the integrated terminal. I couldn't find an xtermjs issue about it, but not 100% sure how to try xtermjs in isolation.

## What I've tried
* Using bash instead of zsh
* Scrolling using various combinations of arrow keys + modifiers
* Using VSCode Insiders
* Editing typescript config to add `diagnostics: true` compiler option. 

The last attempt (`diagnostics: true`) was actually a moderately successful workaround as it dumps lots of extra output that does not stick-to-bottom; **however,** it does not fix the issue when I run multiple `tsc -w` with lerna which is my ultimate goal since the compilation of the last package clobbers the errors of all the others :)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.92GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by patrickhulce** [comment]
It seems like https://github.com/Microsoft/TypeScript/pull/21303 is what I need, but it'd be nice to get this working on older versions of typescript too :)

**Comment by Tyriar** [comment]
@patrickhulce how does the behavior differ in iTerm2/Terminal.app?

**Comment by patrickhulce** [comment]
> how does the behavior differ in iTerm2/Terminal.app?

It differs in that I can successfully scroll up and view the previous output.

![http://g.recordit.co/HDbR9MSqCW.gif](http://g.recordit.co/HDbR9MSqCW.gif)

**Comment by Tyriar** [comment]
@patrickhulce hmm, not sure why iTerm2 would be behaving differently.

I'll close this off as the fix is to use `--preserveWatchOutput`
