### ISSUE TITLE
Feature Request: Git stage/unstage/revert selected ranges on mouse context menu

### ISSUE THREAD

**Issue by venomDeved** [Microsoft/vscode#46377]
- VSCode Version: 1.21.1
- OS Version: Linux Mint

I would like to see the 3 menu options for git stage, unstage and revert selected ranges appear on the right click mouse context menu when in the (Working Tree) editor view of a file. The menu items only appear in the far top right corner and could appear as the first 3 options on the context menu to be a quicker way to add or remove changes before committing.

![current-menu](https://user-images.githubusercontent.com/29271148/37805780-3b93c990-2e8c-11e8-9ba4-3eb918eb6e61.png)
Current menu in top right corner

![context-menu](https://user-images.githubusercontent.com/29271148/37805784-3f8eb258-2e8c-11e8-802f-0e05722f9a52.png)
Example mouse context menu

**Comment by joaomoreno** [comment]
This was merged this month

![image](https://user-images.githubusercontent.com/22350/37910210-40085404-310d-11e8-8169-d3c19cba7647.png)
