### ISSUE TITLE
syntax highlighting is wrong for SQL statement containing alias with []

### ISSUE THREAD

**Issue by chowkf** [Microsoft/vscode#46378]
Issue Type: <b>Bug</b>

for example:
SELECT [Student's Name] = StuName
FROM StudentTable

all the charaters after ' will highlighted as VARCHAR

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|7.89GB (1.61GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.0
team|ms-|1.122.0
iRule|yig|1.2.0

</details>

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-mssql#1075
