### ISSUE TITLE
terminal.external.windowsexec setting shows with "undefined" drive letter on macos

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46379]
Should this setting be shown on non-windows? Some other platform-specific settings are not. Or should it default to 'C:' when it can't find the drive letter?

![image](https://user-images.githubusercontent.com/323878/37806053-02a15c4c-2dfb-11e8-8b71-02c1719a63c8.png)

**Comment by Tyriar** [comment]
@roblourens removing the setting would cause errors on settings files that are synced between machines. I've added a fallback to `C:` 👍
