### ISSUE TITLE
How to disable the unit auto-completion in CSS ？

### ISSUE THREAD

**Issue by zphhhhh** [Microsoft/vscode#46382]
Can i disable the unit auto-completion in CSS ? I think it has no more effect.

- VSCode Version: 1.21.1
- OS Version: macOS 10.13

Steps to Reproduce:

1. type some number like 10 in CSS

Does this issue occur when all extensions are disabled?: Yes

![wechatimg2451](https://user-images.githubusercontent.com/17380627/37808631-66aa1d7e-2e86-11e8-9ea2-8d5d87a74104.jpeg)

**Comment by aeschli** [comment]
Press escape to close the completion window, or just continue with `:` to ignore the suggestions.

Disabling just css code complete is not possible, but you can disable the full css extension in the next release.

**Comment by zphhhhh** [comment]
Got it, thx.
