### ISSUE TITLE
vscode progressive lag and freezing when using split terminal and resizing snapped windows

### ISSUE THREAD

**Issue by e-ht** [Microsoft/vscode#46386]
Possibly related to #46374 and #46356

- VSCode Version:

> Version 1.21.1
> Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
> Date 2018-03-14T14:46:30.761Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

- OS Version:

> Distributor ID:	Ubuntu
> Description:	Pop!_OS 17.10 (Artful Aardvark)
> Release:	17.10
> Codename:	artful

- Kernel:

> Linux bloombergh 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- `printf 'Desktop: %s\nSession: %s\n' "$XDG_CURRENT_DESKTOP" "$GDMSESSION"
`
> Desktop: pop:GNOME
> Session: pop

Steps to Reproduce:

1. Open vscode and open a terminal (Ctrl-Shift-`)
2. Split into one or two additional terminals
3. Play with resizing the window. Snap window to to different desktop positions. Resize co-snapped windows. 

Easy to trigger when windows are snapped together and resize in tandem.
At some point using the terminals begins to lag and will freeze for significant amounts of time.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@e-ht I fixed an issue similar to this recently. Could you try reproduce on the latest version of Insiders? https://code.visualstudio.com/insiders/

**Comment by e-ht** [comment]
@Tyriar I spent some time trying getting it to reproduce on Insiders; everything ran great. It's a pleasure to use Terminal again. Thank you for your work.

**Comment by Tyriar** [comment]
@e-ht great! It should hit stable in the next week or 2.
