### ISSUE TITLE
`code --list-extensions` doesn't work for VSCode installed by uzipping from a VSCode zip package

### ISSUE THREAD

**Issue by cateyes99** [Microsoft/vscode#46385]
- VSCode Version: 1.21.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Download a **zip package** of VSCode for Windows
2. Unzip it into a fold `c:\vscode`.
3. Open a command line console, and go to that fold by `cd c:\vscode`
4. Run `code --list-extensions` from that **command line console**
5. It **just** opens a new **VSCode** instance **without** listing all the extensions on the console if there is no VSCode instance running, or bring the **VSCode** to the front still **without** listing all the extensions on the console if there is one already running. In short, `code --list-extensions` doesn't work for VSCode installed by unzipping from a VSCode zip package.

I would expect it still work same as for a VSCode installed from a VSCode **installer** as shown below
![vscodelistextensions](https://user-images.githubusercontent.com/19678455/37809466-670bb02e-2eb4-11e8-8590-181d165aa8cd.png)

**Comment by Tyriar** [comment]
You need to run `<vscode_path>\bin\code`
