### ISSUE TITLE
install project error,please help me ,thanks

### ISSUE THREAD

**Issue by unsilence** [Microsoft/vscode#46384]
system:mac os

localhost:vscode unsilence$ nvm use v8.10.0
Now using node v8.10.0 (npm v5.6.0)
localhost:vscode unsilence$ nvm use v8.10.0
Now using node v8.10.0 (npm v5.6.0)
localhost:vscode unsilence$ yarn
yarn install v1.5.1
$ node build/npm/preinstall.js
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info windows-foreground-love@0.1.0: The platform "darwin" is incompatible with this module.
info "windows-foreground-love@0.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-mutex@0.2.0: The platform "darwin" is incompatible with this module.
info "windows-mutex@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.1.6: The platform "darwin" is incompatible with this module.
info "windows-process-tree@0.1.6" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/14] ⠄ gc-signals: /Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:
[6/14] ⠄ native-watchdog: CXX(target) Release/obj.target/watchdog/src/watchdog.o
[3/14] ⠄ keytar: CXX(target) Release/obj.target/keytar/src/async.o
[4/14] ⠄ native-is-elevated: CXX(target) Release/obj.target/is-elevated/src/is-elevated.o
error An unexpected error occurred: "/Users/unsilence/Documents/vscode/node_modules/native-is-elevated: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/unsilence/Documents/vscode/node_modules/native-is-elevated
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/unsilence/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/unsilence/Documents/vscode/node_modules/native-is-elevated/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/unsilence/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/unsilence/.node-gyp/iojs-1.7.13/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/unsilence/.node-gyp/iojs-1.7.13',
gyp info spawn args   '-Dnode_gyp_dir=/Users/unsilence/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/unsilence/.node-gyp/iojs-1.7.13/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/unsilence/Documents/vscode/node_modules/native-is-elevated',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/is-elevated/src/is-elevated.o
In file included from ../src/is-elevated.cc:1:
In file included from /Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:42:
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:1506:3: error: unterminated /* comment
  /**
  ^
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:15:2: error: unterminated conditional directive
#ifndef INCLUDE_V8_H_
 ^
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:1449:17: error: missing '}' at end of definition of 'v8::Message'
class V8_EXPORT Message {
                ^
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:80:1: note: still within definition of 'v8::Message' here
namespace node {
^
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:105:29: error: incomplete type 'v8::Isolate' named in nested name specifier
  return ErrnoException(v8::Isolate::GetCurrent(),
                        ~~~~^~~~~~~~~
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:82:7: note: forward declaration of 'v8::Isolate'
class Isolate;
      ^
In file included from ../src/is-elevated.cc:1:
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:116:26: error: incomplete type 'v8::Isolate' named in nested name specifier
  return UVException(v8::Isolate::GetCurrent(),
                     ~~~~^~~~~~~~~
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:82:7: note: forward declaration of 'v8::Isolate'
class Isolate;
      ^
In file included from ../src/is-elevated.cc:1:
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:245:43: error: no member named 'Template' in namespace 'v8'; did you mean 'template'?
inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
                                      ~~~~^~~~~~~~
                                          template
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:245:51: error: expected unqualified-id
inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
                                                  ^
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:245:43: error: no member named 'Template' in namespace 'v8'; did you mean 'template'?
inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
                                      ~~~~^~~~~~~~
                                          template
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:245:51: error: expected unqualified-id
inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
                                                  ^
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:245:43: error: expected ')'
inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
                                          ^
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:245:28: note: to match this '('
inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
                           ^
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:248:30: error: incomplete type 'v8::Isolate' named in nested name specifier
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
                         ~~~~^~~~~~~~~
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:82:7: note: forward declaration of 'v8::Isolate'
class Isolate;
      ^
In file included from ../src/is-elevated.cc:1:
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:250:43: error: incomplete type 'v8::FunctionTemplate' named in nested name specifier
  v8::Local<v8::FunctionTemplate> t = v8::FunctionTemplate::New(isolate,
                                      ~~~~^~~~~~~~~~~~~~~~~~
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:77:7: note: forward declaration of 'v8::FunctionTemplate'
class FunctionTemplate;
      ^
In file included from ../src/is-elevated.cc:1:
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:251:65: error: use of undeclared identifier 'callback'; did you mean 'calloc'?
                                                                callback);
                                                                ^~~~~~~~
                                                                calloc
/usr/include/stdlib.h:148:7: note: 'calloc' declared here
void    *calloc(size_t __count, size_t __size) __result_use_check __alloc_size(1,2);
         ^
In file included from ../src/is-elevated.cc:1:
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:252:39: error: incomplete type 'v8::String' named in nested name specifier
  v8::Local<v8::String> fn_name = v8::String::NewFromUtf8(isolate, name);
                                  ~~~~^~~~~~~~
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:103:7: note: forward declaration of 'v8::String'
class String;
      ^
In file included from ../src/is-elevated.cc:1:
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:252:68: error: use of undeclared identifier 'name'
  v8::Local<v8::String> fn_name = v8::String::NewFromUtf8(isolate, name);
                                                                   ^
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:253:4: error: member access into incomplete type 'v8::FunctionTemplate'
  t->SetClassName(fn_name);
   ^
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:77:7: note: forward declaration of 'v8::FunctionTemplate'
class FunctionTemplate;
      ^
In file included from ../src/is-elevated.cc:1:
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:254:3: error: use of undeclared identifier 'recv'
  recv->Set(fn_name, t);
  ^
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:260:33: error: no type named 'FunctionCallback' in namespace 'v8'
                            v8::FunctionCallback callback) {
                            ~~~~^
/Users/unsilence/.node-gyp/iojs-1.7.13/src/node.h:261:30: error: incomplete type 'v8::Isolate' named in nested name specifier
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
                         ~~~~^~~~~~~~~
/Users/unsilence/.node-gyp/iojs-1.7.13/deps/v8/include/v8.h:82:7: note: forward declaration of 'v8::Isolate'
class Isolate;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/is-elevated/src/is-elevated.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/unsilence/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command \"/Users/unsilence/.nvm/versions/node/v8.10.0/bin/node\" \"/Users/unsilence/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/unsilence/Documents/vscode/node_modules/native-is-elevated
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2

**Comment by unsilence** [comment]
this’s a new problem

**Comment by yume-chan** [comment]
@unsilence don't care about the bot.

I think there is something wrong with your compiler that it doesn't understand the syntax from v8 (one of dependencies of Electron, which is one of dependencies of Code).
