### ISSUE TITLE
When selecting next find match, something appears

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#46395]
Issue Type: <b>Bug</b>

![next](https://user-images.githubusercontent.com/24318019/37815747-16d49dae-2eab-11e8-824a-9d28b4a2d886.png)

1. ctrl+f, open the findwidget
2. esc, close the findwidget
3. ctrl+d, the thing in the picture appears

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|7.89GB (2.15GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
asset|shi|0.0.1
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.7
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|4.2.1
vscode-icons|rob|7.22.0
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by yume-chan** [comment]
This toolbar helps you checking and changing searching options of <kbd>Ctrl</kbd> + <kbd>D</kbd>, what's wrong with this?

**Comment by shizengzhou** [comment]
@yume-chan 因为如果刚打开vscode，按Ctrl+D，不会出现这个toolbar，连按两次才会出现，所以我以为是一个bug。既然不是bug，我会关了这个issue。

**Comment by yume-chan** [comment]
<kbd>Ctrl</kbd> + <kbd>D</kbd> 是选中下一个搜索结果，如果什么都不选择直接按 <kbd>Ctrl</kbd> + <kbd>D</kbd> 会选中光标所在的单词，的确是不会出现。有选中的时候再按就会出现。
