### ISSUE TITLE
Add platform detect functions in keybindings.json for `when` field

### ISSUE THREAD

**Issue by Wyntau** [Microsoft/vscode#4639]
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.2

I use vscode both in OS X and Linux. And I want to backup my configs via github. So I can soft link **settings.json** and **keybindings.json** to corrent directory.

Suppose I want to map `cmd+y`(OSX ) or `ctrl+y`(Linux) to `redo` in **keybindings.json**

Now I have to create two files. `keybindings.osx.json` and `keybindings.linux.json`. The only difference is in **keybindings.osx.json** I map `cmd+y` to `redo`, and in **keybindings.linux.json** I map `ctrl+y` to `redo`.

Can I mix these configs in just one file `keybindings.json`, and use platform detect function to decide which map rule work?

Just like below or something else?

``` json
[
  {
    "key": "cmd+y",
    "command": "redo",
    "when": "os.isDarwin"
  },
   {
    "key": "ctrl+y",
    "command": "redo",
    "when": "os.isLinux"
  }
]
```

**Comment by mucsi96** [comment]
+1

**Comment by mucsi96** [comment]
@Treri Is VSCode reading from keybindings.osx.json file directly? Or you have to rename it manually to keybindings.json on OSX?

**Comment by Treri** [comment]
@mucsi96 I just soft link **keybindings.osx.json** to **keybindings.json**

**Comment by mucsi96** [comment]
I see.Thanks @Treri

**Comment by usernamehw** [comment]
/duplicate

I'll just slowly close this.
