### ISSUE TITLE
Looooosing intellisense

### ISSUE THREAD

**Issue by Legends** [Microsoft/vscode#46393]
- VSCode Version:
- OS Version: win10 x 64
![image](https://user-images.githubusercontent.com/966368/37813156-228697ca-2e64-11e8-9f9c-d9849305bccb.png)

Steps to Reproduce:
Who knows....

**Comment by Tyriar** [comment]
You'll need to provide more information on the issue you're experiencing.

**Comment by Legends** [comment]
The only thing I can tell is, that I have worked with *.js files, if you need more info, I am here...

```
var fs = require('fs')     // --> no intel...
var path = require('path')
```

Sometimes it's gone and after soem time it comes back.

**Comment by mjbvz** [comment]
1. Does this happen when you disable all extensions and restart vscode?
1. What does your workspace look like? Do you have a `jsconfig.json` file? A `package.json`?
1. Please describe where specifically intellisense does not work. When typing `fs.` for example?

**Comment by Legends** [comment]
1.) This happens sporadically, I would have to work in safe mode all the time to check this out.
2.) tsconfig.json, package.json
3.) Yes when typing `fs.`. Now it works again, I think I had also restarted VsCode, but it didn't bring back intellisense. And after some time it was there again...

**Comment by mjbvz** [comment]
[Automatic type acquisition](https://code.visualstudio.com/Docs/languages/javascript#_automatic-type-acquisition) is disable if you are in a typescript project (using a `tsconfig.json`). Try manually installing the types: `npm install --save-dev @types/node`

**Comment by Legends** [comment]
Sorry, it was actually a project without `tsconfig.json`.

**Comment by mjbvz** [comment]
Are you writing js or ts? You can still try installing `@types/node` in either case to see if that fixes the issue

And please run with extensions disabled to determine where the error is coming from. Also try using the current VS Code insiders build to make sure you have the latest fixes

**Comment by Legends** [comment]
`js`. But closing this for now, as I don't have this issue anymore...
