### ISSUE TITLE
Cut/paste in files ruins formatting (removes linebreaks)

### ISSUE THREAD

**Issue by xmxstudio** [Microsoft/vscode#46398]
Issue Type: <b>Bug</b>

I'm modifying a line of sass and cutting a piece of style code and pasting it elsewhere. when pasting, the entire fucking file is minified and all newlines are eliminated. Effectively destroying the sass file.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.10.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3407)|
|Load (avg)|3, 3, 3|
|Memory (System)|15.55GB (0.82GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.2.6
terminal-tabs|Tyr|0.1.1
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
jshint|dba|0.10.17
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.3
code-beautifier|mic|1.7.2
sublime-keybindings|ms-|3.0.3
seti-icons|qin|0.1.3
sass-indented|rob|1.4.8

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by yume-chan** [comment]
You have stated that this issue only reproduce with extensions, so it might be caused by extensions.

Can you check your extensions (especially ones that relate with formatting)?

**Comment by xmxstudio** [comment]
Forgot to check that box. Does it with extensions disabled and uninstalled.
Reboot fixed it. This is on Ubuntu 17.04 running i3wm.
