### ISSUE TITLE
Setting language specific tab size gets reset

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#46394]
Issue Type: <b>Bug</b>

Yaml files have 2 spaces indent
Go to settings and change editor 
[yaml]": {
    "editor.tabSize": 4
  },
yaml files do not update
Reload window
yaml files do update
when fully reloaded tabSize resets to 2 spaces

VS Code version: Code - Insiders 1.22.0-insider (b75321329388d74e34f79dcfcb789246e31836a8, 2018-03-22T06:11:18.197Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_2958034|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.26
EditorConfig|Edi|0.12.1
beautify|Hoo|1.3.0
php-namespace-resolver|Meh|1.0.2
material-icon-theme|PKi|3.2.6
vscode-docker|Pet|0.0.25
code-settings-sync|Sha|2.9.0
vscode-file-peek|abi|1.0.1
Bookmarks|ale|0.18.2
numbered-bookmarks|ale|0.11.1
vscode-processes|and|0.0.4
folder-indexing|ast|0.2.0
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.7
gitlens|eam|8.1.1
vscode-html-css|ecm|0.2.0
vscode-phpmd|eco|1.0.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
php-debug|fel|1.12.2
php-intellisense|fel|2.3.0
php-pack|fel|1.0.1
sass-lint|gle|1.0.1
vscode-firefox-debug|hbe|1.1.3
vscode-dimmer|hoo|2.1.0
phpcs|ika|1.0.5
smarty|imp|0.2.0
docthis|joe|0.6.0
puppet-vscode|jpo|0.9.0
php-cs-fixer|jun|0.1.59
graphql-for-vscode|kum|1.9.1
twig-language-2|mbl|0.3.1
vscode-scss|mrm|0.6.2
vsliveshare|ms-|0.2.260
debugger-for-chrome|msj|4.2.1
color-highlight|nau|2.3.0
vscode-journal|paj|0.5.0
vscode-code-outline|pat|0.0.13
webstorm-icons|pms|0.0.3
vscode-yaml|red|0.0.10
sass-indented|rob|1.4.8
sockscode-vscode|shy|1.0.1
flowmaker|spe|1.2.0
vim|vsc|0.11.2

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
By default vscode will try to guess the tab size for files, you'll also have to set `"editor.detectIndentation": false` to disable that to force it to use editor.tabSize instead.

**Comment by bm-stschneider** [comment]
I already have the detect indentation disabled.

**Comment by roblourens** [comment]
You indicated that this only reproduces with extensions, do you know which extension is interfering with it?

**Comment by bm-stschneider** [comment]
Sadly I have no idea which extension causes this.

**Comment by bm-stschneider** [comment]
vscode-yaml is the only one I can exclude because that was my initial guess.

**Comment by yokujin** [comment]
The same happens to me. 
Looking through the list of extensions I found that both of us use the same extension: `EditorConfig`.
When I disabled it and reloaded window everything went back to normal. After enabling it back tab settings got screwed again. So it looks like `EditorConfig` extension resets settings at some moment.

**Comment by fish520** [comment]
I've met the same problem, but I have nothing affecting the tab settings like `.editorConfig` in my project !

**Comment by rebornix** [comment]
Please file issues against EditorConfig. Thanks!
