### ISSUE TITLE
Latest update has narrow editor window when only one view is open

### ISSUE THREAD

**Issue by jossgb** [Microsoft/vscode#46391]
Issue Type: <b>Bug</b>

This update of visual studio code appears to shrink the editor window when operating in single editor mode to an 80 width centered column. In previous builds, the width of the editor would be the width of the main window. Switching to 2 or three editors yeidls the expected width for each editor.

To reproduce:

1. Start a new instance of VS code
2. Create a new file

Expected result:
  - New editor window is created that has a width filling the workspace area 

Actual Result:
  - New editor window is created that is approximately 80 colums wide and cetered in the workspace area 

<img width="1136" alt="screen shot 2018-03-23 at 05 08 19" src="https://user-images.githubusercontent.com/1741803/37812632-ddcc2d1c-2e58-11e8-93b5-1629259bc3be.png">
<img width="1513" alt="screen shot 2018-03-23 at 05 12 26" src="https://user-images.githubusercontent.com/1741803/37812633-dde4b940-2e58-11e8-9e55-ecbaf70eca4e.png">

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.36GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
swift|Kas|0.0.3
gitlens|eam|8.1.1
vscode-todo-plus|fab|1.10.0
vscode-perl|hen|1.14.4
svn-scm|joh|1.26.0
Go|luk|0.6.77
python|ms-|2018.2.1
csharp|ms-|1.14.0
gradle-language|nac|0.2.3
smartpaste|reb|0.0.3
java|red|0.21.0
vscode-icons|rob|7.22.0
vscode-hexdump|sle|1.6.0

</details>
Reproduces without extensions

**Comment by ssjtux** [comment]
Just simply drag one of the edges.
That'll probably solve your problem.

**Comment by isidorn** [comment]
@jossgb you are probably in zenMode. Use this setting
`  "zenMode.centerLayout": false`

Also use the command to get out of centered layout: F1 > "View: toggle centered layout"

**Comment by patoezequiel** [comment]
Thanks @isidorn, that setting was the one causing this behavior.
