### ISSUE TITLE
Ctrl + _ not working in terminal

### ISSUE THREAD

**Issue by sreevisakh** [Microsoft/vscode#46399]
Issue Type: <b>Bug</b>

in nano that last line can be reached by Ctrl + _ & Ctrl + V,
I am unable to type this in terminal even though terminal is focused, it is executing some command in editor.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 7, 11|
|Memory (System)|16.00GB (0.70GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_45067|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
jest-snippets|and|1.1.1
rails|bun|0.5.4
solargraph|cas|0.13.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.11.6
vscode-eslint|dba|1.4.7
ruby|gro|0.0.6
vscode-react-typescript|inf|1.0.13
sftp|lix|1.1.5
vscode-language-babel|mgm|0.0.12
debugger-for-chrome|msj|4.2.1
Ruby|reb|0.17.0
react-beautify|tai|0.3.0
bootstrap4-vscode|the|4.0.0
bootstrap-3-snippets|wcw|0.1.0
change-case|wma|1.0.0
ReactSnippets|xab|2.0.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
You'll need to unbind the "Go Back" command so it's passed to the shell:

```
{ "key": "ctrl+-",                "command": "-workbench.action.navigateBack" }
```
