### ISSUE TITLE
not working key-binding with JIS Keyboard

### ISSUE THREAD

**Issue by 74th** [Microsoft/vscode#464]
I make VIM-style key-binding plugin ( https://github.com/74th/vscode-vim ).
I use keybinding with JIS keyboard on MacOSX, bellowing keys not work.

* no key hits
   * ```shift+2```
   * ```shift+7```
   * ```shift+[```
   * ```shift+;```
   * ```'```
   * ``` ` ```
   * ```space```
* a number of keys hits ( key-bind -> JIS Key )
   * ```-``` -> ```-```,```_```
   * ```shift+=``` -> ```=```,```+```
   * ```[``` -> ```[```,```@```
   * ```shift+'``` -> ```"```,```'```
   * ```shift+` ``` -> ```~```,```` `
* strange keys hits
   * ```shift+-``` -> ```shift+_```
   * ```=``` -> ```^```

I am happy to be able to use ```:``` and ```"``` for key-binding setting , instead of ```shift+;``` and ```shift+2```.

**Comment by alexandrudima** [comment]
@74th the nasty problem here is that the keyboard dispatching happens in the browser "keydown" event which doesn't hint whatsoever to what a follow-up "keypress" would produce. It literally only gives the key code in the form of a number (numbers which of course vary across browsers and OSes :)). 

That is what makes supporting `:` and `"` very difficult. 

Will try all the other combos you mention, most likely there's some issues with the tables in https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/keyboardEvent.ts . I will check them and follow up

**Comment by alexandrudima** [comment]
@74th I didn't get yet to try out the keyboard combos you mention with the JIS keyboard on MacOSX (need help from some colleagues to do that), but please check out #713 in the meantime for an explanation of what's going on.

**Comment by alexandrudima** [comment]
@74th 

Please see https://github.com/alexandrudima/vscode-vim if you are authoring a vim emulation extension for VS Code - it shows how to capture typed characters (not through keybinding rules).
