### ISSUE TITLE
Explorer View Icon Disappears

### ISSUE THREAD

**Issue by ozkanaltuner** [Microsoft/vscode#46405]
Issue Type: <b>Bug</b>

I turn on Explorer on View menu. Whenever I click an icon (other than file explorer), it disappears, and I have to enable it on View menu, again.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.86GB (7.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.2.9

</details>
Reproduces without extensions

**Comment by yume-chan** [comment]
You might have hide the Explorer view. Please try to right click on the empty place of the Activity Bar (the vertical bar contains view buttons and the gear button), then make sure the `Explorer` menu item is checked.
