### ISSUE TITLE
Allow hiding the buttons in the tab bar line and in the panel title bar

### ISSUE THREAD

**Issue by costincaraivan** [microsoft/vscode#46403]
A small change related to the buttons in the tab bar line:

* Open Changes
* Split Editor
* Close

and to the buttons in the panel title bar:

* New Terminal
* Split Terminal
* Kill Terminal
* Maximize Panel Size
* Move to Bottom
* Close Panel

For users who have already memorized the keyboard shortcuts for these commands (and considering the existence of Ctrl-p and Ctrl-Shift-p), the buttons are kind of redundant. It would be nice to have an option to hide them as almost everything in the UI already can be hidden. I know about Zen mode, but Zen mode also centers the text in the editor, hides the panel/terminals, makes Visual Studio Code full screen and all sort of other things which might not be desirable.

As a note related to this, Vim and Emacs users generally tend to hide the UI. Funnily enough, even the beast that is IntelliJ IDEA allows it 😆

**Comment by ewohlken** [comment]
Any update on this? Love vscode but its UI is way too busy for my taste

**Comment by kirkstrobeck** [comment]
This is referring to these buttons, right?

<img width="362" alt="screen shot 2018-08-08 at 09 27 17" src="https://user-images.githubusercontent.com/241963/43850625-44bd5036-9aed-11e8-8551-59e758917431.png">

**Comment by ashrafhadden** [comment]
@kirkstrobeck It's css class name is `editor-actions`

<img width="399" alt="editor actions screenshot" src="https://user-images.githubusercontent.com/32565770/43869236-8abf945c-9b3f-11e8-9b4b-47c3c42ccaea.png">

**Alternative Solution**
\- https://stackoverflow.com/questions/47266613/vscode-hide-top-right-icons
Using [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css)

> `.editor-actions .actions-container > .action-item > .action-label.icon:not(.textdiff-editor-action) {
>     display: none !important;
> }`

**Comment by costincaraivan** [comment]
Yup, @kirkstrobeck I was referring to that area. I guess I could make an extension for it? I'd need to read up how to make an extension, though.

**Comment by lacostenycoder** [comment]
Oh please, is there a way to hide this stupid shits besides Zen mode???

![screen shot 2018-11-17 at 4 48 46 pm](https://user-images.githubusercontent.com/6077905/48666089-cb2d5e00-ea88-11e8-940e-5c7ec469feb7.jpg)

**Comment by jmcannon** [comment]
Please let users remove these. It takes up significant real estate that I'd rather use for my open tabs.

**Comment by lacostenycoder** [comment]
This feature seems to be under `View > Appearance > Hide Activity Bar`

**Comment by kube** [comment]
This would be cool for screenshots where you want to focus on content.

**Comment by kube** [comment]
@usernamehw Thanks, it seems a really nice extension and .

But in my current case, I want to record a GIF, show completions, and error linting:

![2018-12-03 14 55 10](https://user-images.githubusercontent.com/2991143/49378489-037d9f00-f70d-11e8-8218-257814920aea.gif)

**Comment by edporteous** [comment]
Various extensions add buttons to this toolbar making it take up more real-estate. It would be great to be able to hide it.

**Comment by jabacchetta** [comment]
This feature request becomes even more appealing when taking into account:
- split editors, where available tab bar space is further reduced
- duplication of the `...` icon across every editor group
- extensions (which add their own icons and require additional settings to remove)

The Custom CSS and JS Loader extension (as mentioned above) does work in removing the icons, but it's a hack that requires maintaining a css file and also requires permanently silencing the "corrupt installation" message.

**Comment by jonathan-holm** [comment]
Bump! All actions from these icons are available to perform elsewhere. They are needless clutter.

**Comment by ronjouch** [comment]
Extension-less workaround that might be good enough for folks who like me start VSCode at most once every few days:

1. Pop open the Dev Tools. I like to bind them to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> like in a browser: add `{ "key": "ctrl+shift+i", "command": "workbench.action.toggleDevTools" }` to your `keybindings.json`.
2. In the console, `document.querySelectorAll('.editor-actions')[0].style.display = 'none'`
3. :tada:

**Comment by hesting15** [comment]
So, what about second part of the question?

> and to the buttons in the panel title bar:
>* New Terminal
>* Split Terminal
>* Kill Terminal
>* Maximize Panel Size
>* Move to Bottom
>* Close Panel

![vscode1](https://user-images.githubusercontent.com/22618607/53477257-f870ab80-3a7c-11e9-89c7-4962750b60d6.png)

If I simply do 
```
.monaco-workbench .part.panel .title {
	display: none;
}
```
The search results panel goes up, it doesn't stretch to the whole area, and I have an empty spot in the bottom:

![vscode2](https://user-images.githubusercontent.com/22618607/53477447-64531400-3a7d-11e9-9d2f-9589d72724b7.png)

**Comment by bpartridge** [comment]
Based on @ronjouch's suggestion, if you have multiple panes and want to hide actions for all of them, use this in the dev tools instead:

    [...document.querySelectorAll('.editor-actions')].map(a => a.style.display = 'none')

I understand why #459 is locked and why giving extensions deep abilities to execute JS/edit CSS is unhealthy and counter to performance goals, but this is exactly the type of thing that userscripts would be perfect for, caveat emptor.

**Comment by curliq** [comment]
+1

**Comment by JamesGreenaway** [comment]
+1

**Comment by curliq** [comment]
For people wanting to particularly hide the Gitlens icons, you can use these settings
```
    "gitlens.menus": {
        "editorGroup": {
            "blame": false,
            "compare": false
        },
    },
```

**Comment by ronjouch** [comment]
To an eventual implementer for this feature request: Firefox's "Overflow Menu" seems like a UX good inspiration. See how it lets users choice over which addons 

![firefox-overflow-menu](https://user-images.githubusercontent.com/522085/54320595-e25a0380-45c3-11e9-81a1-18454b4c40a1.gif)

**Comment by AbakumovAlexandr** [comment]
VSCode Team, could you provide an ETA for this, please?

**Comment by buncismamen** [comment]
I hope I could modify it because its kinda annoying 
the only things that I wanted is I could disable this feature for some extensions because sometimes is annoying an blocking my tab
just like this 
![image](https://user-images.githubusercontent.com/14258779/60027227-444bfe00-96c7-11e9-9534-2ca0810b7792.png)

**Comment by craigcosmo** [comment]
yep, that sh*t takes to much space. Gotta hide it.

**Comment by craigcosmo** [comment]
<img width="1056" alt="Screen_Shot_2019-07-20_at_12_48_05_PM" src="https://user-images.githubusercontent.com/538657/61574662-fae7a680-aaec-11e9-8422-db88f5930d82.png">

**Comment by jabacchetta** [comment]
For those still looking for a better solution until this feature gets added natively:

- Install the [Customize UI extension](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui)
- Add the following to your `settings.json` file: `"customizeUI.stylesheet": { ".editor-actions": "display: none !important;", },`. For more options, refer to @ashrafhadden [comment here](https://github.com/Microsoft/vscode/issues/46403#issuecomment-411604090).

**Comment by xhat** [comment]
@craigcosmo 
`    "customizeUI.stylesheet": {
        ".monaco-toolbar": "display: none !important;",
    },`

**Comment by ataiya** [comment]
yes, many of us moves to vscode to have a super-clean UI.
Extensions should not be allowed to pollute it without our permission!
+1 to this → and yes, customizeUI is an "ok" temporary fix

**Comment by AbakumovAlexandr** [comment]
I guess the top reason why commercial devs move to VSCode is not because of its 'super-clean UI', but rather because technologies they have to use at work are targeted VSCode (like Angular, etc.).
Also, if you don't like how an extension X would pollutes VSCode UI, the most obvious solution would be not using that extension.

**Comment by luizfzarco** [comment]
As already pointed by many, we already have easy access to those functionalities. Especially when using split view, these buttons at the tab take too much space we want for our tabs. **Definitely should at least be optional** (if not removed all together).

**Comment by patrickgilmour** [comment]
+1 for a native VS Code option to hide the editor actions

**Comment by mikelyons** [comment]
I want to pile on here and say that it would be nice if you could move these buttons off the tab bar or disable them natively somehow. It seems obvious to me that the tab bar already gets mega cluttered when you have lots of files open.

**Comment by bionicles** [comment]
these buttons suck and should die

**Comment by torchlard** [comment]
> 
> 
> I guess the top reason why commercial devs move to VSCode is not because of its 'super-clean UI', but rather because technologies they have to use at work are targeted VSCode (like Angular, etc.).
> Also, if you don't like how an extension X pollutes VSCode UI, the most obvious solution seems to be not using that extension X.

Disagree. We need those extensions, but we don't need an icon from it placed in title bar. I don't understand why this simple UI change being ignored for long time, it should be very easy implement, just hide all in 3 dots ...

**Comment by sytelus** [comment]
This page needs update to show "Editor Actions": https://code.visualstudio.com/docs/getstarted/userinterface

On Ubuntu, this area is over the tabs instead of along the same line as menus.

**Comment by 3nuc** [comment]
While you're at it, you can also go full rice mode and remove the side bar titles
![obraz](https://user-images.githubusercontent.com/5359825/71446446-ba3b2b80-2723-11ea-9a4a-33341e38cd61.png)
to
![obraz](https://user-images.githubusercontent.com/5359825/71446488-37ff3700-2724-11ea-95f4-fc8b4b22db72.png)


```javascript
  "customizeUI.stylesheet": {
    ".title-label": "display: none !important;", 
  },
```

You can change `.title-label` to `.composite.title` to remove the empty space but then you won't be able to right click the top bar to hide accordion items like the outline view etc. Or you could change "display: none" to some height changing class

![obraz](https://user-images.githubusercontent.com/5359825/71446511-6d0b8980-2724-11ea-8d1b-0edde5e29011.png)

**Comment by sytelus** [comment]
This issue has become very critical given so many extensions now pollute editor actions. On Ubuntu, this renders vscode almost unusable now. Hope it can be fixed very soon!

**Comment by KentoNishi** [comment]
Any updates on this? 
A simple checkbox-style action menu toggle (like that of the left shortcuts bar) would be enough.

**Comment by KarlRamstedt** [comment]
How has this not been fixed yet? It's been over a year and these useless buttons still plague our existence.
I'd understand if a more thorough overhaul is being worked on. Something along the lines of what Firefox allows with buttons that can be relocated and hidden at will would be amazing.

**Comment by KarlRamstedt** [comment]
I should add that I couldn't get [@ashrafhadden's solution](https://github.com/Microsoft/vscode/issues/46403#issuecomment-411604090) to work (pretty sure I did everything correctly; VSCode complained about corruption).
I did get [@jabacchetta's solution](https://github.com/Microsoft/vscode/issues/46403#issuecomment-523286973) to work though. It's also a much less fiddly solution.

**Comment by gatspy** [comment]
action-items on the tab annoys me!!!

**Comment by nqf** [comment]
action-items on the tab annoys me!!! me too

**Comment by jrend** [comment]
Following the workaround that worked for me -- [thanks jabacchetta!](https://github.com/Microsoft/vscode/issues/46403#issuecomment-523286973) -- I just want to share an option that hides things more selectively instead of hiding all the buttons. An example of hiding the GitHub extension buttons:
```json
    "customizeUI.stylesheet": {
        "a[title^=\"Git: View History\"]": "display: none !important;",
        "a[title^=\"Open Changes\"]": "display: none !important;",
        "a[title^=\"Show Revision Details\"]": "display: none !important;",
        "a[title^=\"Toggle File Blame Annotations\"]": "display: none !important;"
    },
```

**Comment by ShiftyMcCool** [comment]
> Following the workaround that worked for me -- [thanks jabacchetta!](https://github.com/Microsoft/vscode/issues/46403#issuecomment-523286973) -- I just want to share an option that hides things more selectively instead of hiding all the buttons. An example of hiding the GitHub extension buttons:
> 
> ```json
>     "customizeUI.stylesheet": {
>         ".editor-actions a[title^=\"Git: View History\"]": "display: none !important;",
>         ".editor-actions a[title^=\"Open Changes\"]": "display: none !important;",
>         ".editor-actions a[title^=\"Show Revision Details\"]": "display: none !important;",
>         ".editor-actions a[title^=\"Toggle File Blame Annotations\"]": "display: none !important;"
>     },
> ```

Obviously a native solution would be preferable, but THIS works just fine until then. Love that it's selective, I still use the buttons in diff view but all the Git buttons while editing was getting to be a bit much.  Thanks!

**Comment by nikitavoloboev** [comment]
Super annoying that you can't hide these icons. Can the devs suggest which area contributors should look into into making this change so one can send a PR?

Thank you.

**Comment by mkxbl** [comment]
almost two years, why so hard?

**Comment by rodrigobravenewcoin** [comment]
I need this right now!

**Comment by meteorsh** [comment]
> For those still looking for a better solution until this feature gets added natively:
> 
> 1. Install the [Customize UI extension](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui)
> 2. Add the following configuration to your `settings.json` file ([additional CSS selectors referenced here](https://github.com/Microsoft/vscode/issues/46403#issuecomment-411604090)):
> 
> ```js
> "customizeUI.stylesheet": {
>   ".editor-actions": "display: none !important;",
> },
> ```

It works for me👍. Thanks for solving my preblem.

**Comment by nikitavoloboev** [comment]
I don't want to install an extension running in the background just to hide one piece of UI. :(

**Comment by sobolevn** [comment]
I have tried [CustomizeUI solution](https://github.com/microsoft/vscode/issues/46403#issuecomment-523286973) but I agree with @nikitavoloboev that it is really strange to setup a monkeypatched version of VSCode just to hide several icons. It should configurable by default.

Currently, it is the only thing that bothers me in [my setup](https://github.com/sobolevn/dotfiles):
<img width="1392" alt="Снимок экрана 2020-03-26 в 11 14 10" src="https://user-images.githubusercontent.com/4660275/77624666-39264700-6f53-11ea-926b-3bdd7adabdad.png">

I would love to see a fix!

**Comment by Frittoss** [comment]
> <img alt="Screen_Shot_2019-07-20_at_12_48_05_PM" width="528" src="https://user-images.githubusercontent.com/538657/61574662-fae7a680-aaec-11e9-8422-db88f5930d82.png">

Using [@jabacchetta's solution](https://github.com/microsoft/vscode/issues/46403#issuecomment-523286973) you can also remove the icons from within your explorer menu:

```js
"customizeUI.stylesheet": {
    ".actions-container": "display: none !important;",
 },
```

**Comment by jasonbuckboyer** [comment]
I think [@ronjouch's suggestion](https://github.com/microsoft/vscode/issues/46403#issuecomment-472642154) is the best so far to balance minimalism with quick access to common actions.

That suggestion, along with an option to completely hide the menu, would provide the ideal functionality overall.

**Comment by gehringf** [comment]
+1 for a native VS Code option to hide the editor actions

**Comment by berfubuyukoz** [comment]
I  am relieved to see I am not alone by being annoyed by these buttons. It gets even worse when you have work on a single PC screen and split the screen into two. I see only one tab at once in that case.

**Comment by RobinTournemenne** [comment]
This issue entered the backlog list of issue on 23 Oct 2019. It is a list of issue without any due date. It should be in the On Deck list of issues since it reduces a lot VS code usability when having a lot of editors opened.

**Comment by mritalian** [comment]
And it's like the simplest option to add, seriously what gives?  customizeUI is a bit of a hack.

**Comment by icetbr** [comment]
To hide the `Split Editor Right` button, you might need something like this to escape the `backslash`

```css
[title='Split Editor Right (Ctrl+\\\\)'] {
  display: none !important;
}
```

I'm using the [Custom UI](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) extension. It looks easier to install and maintain. I installed it, activated with CTRL + P, "Enable Monkey Patch".

Then add this to settings.json (use Help -> Toggle Developer Tools to find out other selectors)

```js
"customizeUI.stylesheet": {
    "[title='Open Changes']": "display: none !important;",
    "[title='Split Editor Right (Ctrl+\\\\)']": "display: none !important;"
},
```

**Comment by uribalb** [comment]
Up !

**Comment by ilteris** [comment]
Please give us a setting to disable those icons

**Comment by Robin-Law** [comment]
Agree with all the above. This is a maddening bit of chrome that I would like to get rid of. The tab bar is for tabs!

**Comment by dan-dr** [comment]
Came here to put a +1 on the OP but man are people here entitled.

> And it's like the simplest option to add, seriously what gives?

> I don't want to install an extension running in the background just to hide one piece of UI. 

> I need this right now!

> almost two years, why so hard?

> How has this not been fixed yet? It's been over a year and these useless buttons still plague our existence.

Y'all are programmers and this is open source software, if it's THAT important maybe you can put some effort into fixing it for yourself and others.

**Comment by ataiya** [comment]
It is "funny" are you are pointing out people being aggressive yet your post is likely more condescending the all the ones above *combined*. 

And as to your observation... for somebody that knows intimately the vscode internals this should indeed be a trivial change, but to somebody that is not, even a simple change like this comes with a large overhead (learning curve).

Anyhow...

**Comment by dan-dr** [comment]
Is it possible to call out people's behavior without sounding condescending? I'm not sure.
It could have been said in a "nicer" way, but they are acting entitled, which is the opposite kind of behavior you want in open source. I think it's important to call it out.

> And as to your observation... for somebody that knows intimately the vscode internals this should indeed be a trivial change, but to somebody that is not, even a simple change like this comes with a large overhead (learning curve).

I don't know if it's trivial or not. How do you know that it's trivial? Maybe it's trivial for both?

In any case It is not "trivial" to maintain a 5000+ issue and 200+ PR's project.
![image](https://user-images.githubusercontent.com/6669808/85017534-4af34100-b174-11ea-9d7e-fbf6e7dcfbbc.png)

Do you suggest prioritizing a feature because someone said "I need this right now!" ?

**Comment by paolomangiadev** [comment]
"trivial change" making an option to hide a couple of buttons from a chromium based application... big lol

**Comment by ianmcateer** [comment]
if you just want to hide everything, i had to target the aria label specifically because otherwise the action items on the left menu bar would get removed

```
  // hide top right icons
  "customizeUI.stylesheet": {
    ".actions-container[aria-label='Editor actions']": "display: none !important;"
  }
```

**Comment by loosechalk** [comment]
Is there a similar console input to @ronjouch's extension-less [workaround](https://github.com/microsoft/vscode/issues/46403#issuecomment-462935343) (using the Console in Developer Tools) to hide these five icons in the integrated terminal?

![image](https://user-images.githubusercontent.com/50847261/87700842-3b0b5480-c754-11ea-95e6-17e271cd5dd6.png)

**Comment by heartacker** [comment]
hi, there is an another effective way to solve the problem of compressed tabs by action icon.
*Move editor actions into the window title to free up space* #104738 
![image](https://user-images.githubusercontent.com/1876302/90325496-e5be9f00-dfae-11ea-82f5-f5d04bade1d6.png)

I think it can be a better way to solve the problem than hide action-icon. even be an new innovations an UI.
PLEASE `+1` 👍 if you are agree #104738

**Comment by astier** [comment]
@heartacker I think your request addresses a different issue. Many people here just want to remove the icons so they don't have to see them. More space for tabs is a benefit but not the main-goal. Moving them to the titlebar doesn't solve the issue for me because I still can see them. Your suggestion is maybe good for people who need the icons and want to safe space for tabs but not for people who just don't need the icons.

**Comment by bedge** [comment]
To remove entirely, this works on startup, no manual action needed once setup:
https://github.com/iocave/customize-ui/issues/63

**Comment by AllanDaemon** [comment]
I have to disable many extensions because when enabled they add soo many icons there that makes the tab selector disappear.

This means that this issue renders *VSCODE* with extensions unusable. It seems this should be an urgent fix.

**Comment by rocke2020** [comment]
I indeed hope to sove this issue: allow hide the eidtor icon. thanks!!

**Comment by welcometochristown** [comment]
Would also like this feature please.

**Comment by jaredbaszler** [comment]
Please add this as a toggle setting or something.  It doesn't seem like it would be that hard to add.

**Comment by adamsoutar** [comment]
@icetbr 's suggestion didn't quite work for me, but adapted into

```json
"customizeUI.stylesheet": {
  ".editor-actions": "display: none !important;"
},
```

it seems to successfully hide these buttons

**Comment by ssmooncoder** [comment]
Well, we are rolling into 2021 and this *still* isn't implemented.

Also, "Zen Mode" makes no sense at its current state.

1. I want to focus on the editor contents. Leaving the tab bar is not only wasted space, its a duplicate of the filename with extra padding as the titlebar also displays the current file.
2. Chrome has had a toggleable "Always Show Toolbar in Full Screen" for a really long time.
3. We have to jump through hoops to recover the wasted space, yet it isn't added natively. There isn't even a setting to reduce the vertical padding.

**Comment by xixixao** [comment]
In case you stumble on this, I combined advice here, on StackOverflow and on Reddit, into a setup that allows you to execute a single command to get the UI without the top bar UI:

https://stackoverflow.com/a/65876039/1526986

<img width="1167" alt="Screen Shot 2021-01-24 at 13 24 40" src="https://user-images.githubusercontent.com/1473433/105643938-f3ece180-5ea3-11eb-9045-f865a3af60f0.png">

Would be great to have this as a simple option to the Zen Mode.

**Comment by twome** [comment]
<img width="1152" alt="Screen Shot 2021-03-05 at 06 10 37" src="https://user-images.githubusercontent.com/1880526/110037642-a94f6680-7d79-11eb-96ed-71db27a218e8.png">
<img width="1158" alt="Screen Shot 2021-03-05 at 06 09 50" src="https://user-images.githubusercontent.com/1880526/110037665-afddde00-7d79-11eb-93ad-827f70d9c84e.png">
UIs could be so much calmer when you assume users have a keyboard and design accordingly. The window corners allow resizing as per normal, and the empty space in the tab bar can be used to drag the whole window around.

**Comment by nosed1ve** [comment]
Any progress on this?

**Comment by narze** [comment]
I adapt the code a bit to hide all editor action icons except the last one with three dots.

```
"customizeUI.stylesheet": {
  ".actions-container[aria-label='Editor actions'] .action-item .action-label:not([title='More Actions...'])": "display: none !important;"
}
```

![image](https://user-images.githubusercontent.com/248741/115750057-f509ae00-a3c1-11eb-9986-90ca682c70ed.png)

**Comment by kt-unzner** [comment]
@narze How can it be managed in this way to hide all icons exept some chosen ones? (or to select which icons to hide)

**Comment by narze** [comment]
@kt-unzner My css is to hide all except the ones in `:not()` pseudo selector. If you want more than one icons to be excluded from hiding, I think you can chain them like this ([Ref.](https://css-tricks.com/css-not-with-multiple-classes/))

```
:not([title='More Actions...']):not([title='Split Editor Right (Ctrl+\\\\)'])
```

For selecting icons to hide is is way easier since you can select them one by one, see above comments.

> To hide the `Split Editor Right` button, you might need something like this to escape the `backslash`
> 
> ```css
> [title='Split Editor Right (Ctrl+\\\\)'] {
>   display: none !important;
> }
> ```
> 
> I'm using the [Custom UI](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) extension. It looks easier to install and maintain. I installed it, activated with CTRL + P, "Enable Monkey Patch".
> 
> Then add this to settings.json (use Help -> Toggle Developer Tools to find out other selectors)
> 
> ```js
> "customizeUI.stylesheet": {
>     "[title='Open Changes']": "display: none !important;",
>     "[title='Split Editor Right (Ctrl+\\\\)']": "display: none !important;"
> },
> ```

**Comment by kt-unzner** [comment]
>I think you can chain them like this (Ref.)
>:not([title='More Actions...']):not([title='Split Editor Right (Ctrl+\\\\)'])

Ok that was the trick that was missing, thanks! :+1: 

I also have had a look on your earlier comments, but that was not working for me.
No I figured out that it was just because I have a different keyboard shortcut for that function, so the button text differs :see_no_evil:

**Comment by narze** [comment]
You can use *= instead of = to match substring. `:not([title*='Split Editor Right'])`

**Comment by tjx666** [comment]
any official progress?

**Comment by Kenobi-the-2nd** [comment]
As one poster mentioned, the ability to hide buttons is available in most places in the UI. I would appreciate having this same functionality for the action toolbar.

**Comment by IcedNet** [comment]
Bump

**Comment by emileber** [comment]
@sbatten could this issue be locked to avoid all the spam ☝️

Thanks you 🙏

**Comment by ericb-summit** [comment]
Yeah, all the "me too" and "any update?" are annoying.  Kind of like seeing the same pointless buttons for every tab when trying to split the screen n ways.

Just playing of course, I appreciate the dev team efforts.

**Comment by Galionix** [comment]
in my case this worked
![image](https://user-images.githubusercontent.com/39463178/125135751-33d21900-e112-11eb-9ec4-e7ee054f0489.png)
`"customizeUI.stylesheet": {
    ".part.editor.has-watermark > div.content":"height: 100vh !important;",
    "#workbench.parts.editor > div.content":"height: 100vh !important;",
    "body > div.file-icons-enabled.monaco-workbench.windows.chromium.nosidebar.vs-dark.vscode-theme-defaults-themes-dark_plus-json.nopanel > div.monaco-grid-view > div > div > div.monaco-scrollable-element > div.split-view-container > div:nth-child(3) > div > div > div.monaco-scrollable-element > div.split-view-container > div.split-view-view.visible > div > div > div.sash-container > div.monaco-sash.horizontal.maximum" : "top: unset !important; bottom: 5px;",
    "body > div.file-icons-enabled.monaco-workbench.windows.chromium.vs-dark.vscode-theme-defaults-themes-dark_plus-json.nopanel > div.monaco-grid-view > div > div > div.monaco-scrollable-element > div.split-view-container > div:nth-child(3)": "top: 0 !important;",
    "body > div.file-icons-enabled.monaco-workbench.windows.chromium.nopanel.vs-dark.vscode-theme-defaults-themes-dark_plus-json.nosidebar > div.monaco-grid-view > div > div > div.monaco-scrollable-element > div.split-view-container > div:nth-child(3) > div > div > div.monaco-scrollable-element > div.split-view-container > div.split-view-view.visible > div > div > div.monaco-scrollable-element > div.split-view-container > div:nth-child(3)":"top:unset !important; bottom: 0 !important;",
    ".titlebar-drag-region":"width: 238px !important; left: unset !important; right: 0 !important",
    ".editor-actions": "display: none !important;",
    ".window-appicon": "display: none !important;",
    ".editor-container": "margin-top: 28px;",
    "body > div.file-icons-enabled.monaco-workbench.windows.chromium.nosidebar.vs-dark.vscode-theme-defaults-themes-dark_plus-json.nopanel > div.monaco-grid-view > div > div > div.monaco-scrollable-element > div.split-view-container > div:nth-child(3)":"height: 100vh !important;",
    "body > div.file-icons-enabled.monaco-workbench.windows.chromium.nosidebar.nopanel.vs-dark.vscode-theme-defaults-themes-dark_plus-json > div.monaco-grid-view > div > div > div.monaco-scrollable-element > div.split-view-container > div:nth-child(3)":"top:0 !important;",
},`

**Comment by Tyriar** [comment]
I created a duplicate of this (https://github.com/microsoft/vscode/issues/132555) with an additional requirement that I'd like to create builtin entries that are hidden by default (due to clutter concerns), but could be easily toggled on if the users wants them. For example clear terminal (https://github.com/microsoft/vscode/issues/130636).

**Comment by gatspy** [comment]
use customizeUI extension cause tab wraps can't work.

**Comment by icetbr** [comment]
Updating my fix to hide the Split Editor Right button. Note the `^`, which will match for a a `contains string`

```js
[title^='Split Editor Right'] {
  display: none !important;
}
```

**Comment by omer-g** [comment]
So, I get that the constant questions about this issue are annoying, but is there anything specific that makes it difficult to implement or holding it back? Having the option to remove these buttons would be great.

**Comment by imthenachoman** [comment]
Has there been any consideration to adding a new menu bar? Kind of like how browsers can have an optional favorites bar? Then users can control if they want the menu bar visible and what icons/buttons it shows? I realize VS Code loves keyboard shortcuts but at some point you start drowning in shortcuts.

**Comment by twome** [comment]
4 years and counting! 🎉🥳 Bets are now open at 1:1 odds on whether the total number of people who have *ever* clicked any of these buttons is greater or lesser than the number of people who've participated in this thread.

**Comment by yakamoz423** [comment]
Need this !!!

**Comment by tjx666** [comment]
@jrieken

**Comment by albert-ying** [comment]
The best I can get:
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/59846322/174460700-61eafb8f-4490-412c-8894-b6a12bfe42d1.png">

```
  "customizeUI.stylesheet": {
    // Hide title actions in Zen-mode
    "div.monaco-split-view2.horizontal.separator-border div.title-actions": "display: none !important;",
    // Hide border lines
    ".monaco-split-view2.separator-border.horizontal>.split-view-container>.split-view-view:not(:first-child):before": "width: 0px",
    // Hide decorations over vertical scrollbar *
    ".decorationsOverviewRuler": "display: none !important;",
    // Hide scrollbar slider *
    "div.monaco-split-view2.horizontal.separator-border .slider": "display: none !important;",
    // Attempt to hide vertical borders (not working yet)
    "div.monaco-sash.vertical": "visible: hidden",
    // Hide File and title actions bar
    ".monaco-workbench .part.editor>.content .editor-group-container>.title>.label-container": "display: none !important;",
    // Center vertically the text editor and reduce its height
    "div.monaco-split-view2.horizontal.separator-border > div.split-view-container > div:nth-child(2) > div > div": "top: 25%; height: 50%",
    ".editor-actions": "display: none !important;",
    ".actions-container[aria-label='Editor actions'] .action-item .action-label:not([title='xxxxxxxx...'])": "display: none !important;",
    ".actions-container[aria-label='Panel actions'] .action-item .action-label:not([title='xxxxxxxx...'])": "display: none !important;",
    "[title*='Terminal']": "display: none !important;",
    "[title*='Panel']": "display: none !important;",
    "[title*='Launch Profile']": "display: none !important;",
    "[title*='zsh']": "display: none !important;",
    // ".monaco-workbench .part.panel .title": "display: none !important;",
    "canvas.minimap-decorations-layer": "display: none !important;",
    "#asvetliakov\\.vscode-neovim[aria-label=\"-- INSERT --\"]": "background-color: #98971a !important;",
    "#asvetliakov\\.vscode-neovim[aria-label=\"-- VISUAL --\"]": "background-color: #b16286 !important;",
    "#asvetliakov\\.vscode-neovim[aria-label=\"-- VISUAL LINE --\"]": "background-color: #c16286 !important;",
    "#asvetliakov\\.vscode-neovim[aria-label=\"-- VISUAL BLOCK --\"]": "background-color: #d16286 !important;",

  },
```

**Comment by YutingYou** [comment]
This annoying toolbar is unfriendly to users who use a small screen.

Disappointed with the fact that this issue has existed for 4 years. 😔

**Comment by matthewelmer** [comment]
> > This is a certified crikey moment... Honestly just remove that cr*p from the source code. No one uses it anyways.
> 
> Remove what, specifically?

Remove whatever this is: https://github.com/microsoft/vscode/issues/46403#issuecomment-411468248

**Comment by matthewelmer** [comment]
I kinda feel bad for the vscode devs, since vscode is the singular good Microsoft product, and they prolly get a lotta heat from threads like this. If you're out there vscode devs, we appreciate your efforts! Sorry that you work for such a smelly company 😔

**Comment by imthenachoman** [comment]
> > > This is a certified crikey moment... Honestly just remove that cr*p from the source code. No one uses it anyways.
> > 
> > 
> > Remove what, specifically?
> 
> Remove whatever this is: [#46403 (comment)](https://github.com/microsoft/vscode/issues/46403#issuecomment-411468248)

I happen to use and love those buttons. I bet many others do. I do think there should be an option to remove it for users that don't use/need/want it.

**Comment by YutingYou** [comment]
@imthenachoman Those buttons can be replaced with keyboard shortcuts, agree with the idea to add an option to remove it though.

**Comment by imthenachoman** [comment]
> @imthenachoman Those buttons can be replaced with keyboard shortcuts, agree with the idea to add an option to remove it though.

Not everyone can or does use keyboard shortcuts. Software must meet the needs of its users with special/disability needs. And sometimes, especially if your hand is already on the mouse, it's way faster to move the mouse and click then move your hand back to the keyboard to enter a shortcut.

**Comment by gjsjohnmurray** [comment]
Take a look at what #154804 has recently brought to Insiders.

**Comment by gimbo** [comment]
> Not everyone can or does use keyboard shortcuts. Software must meet the needs of its users with special/disability needs. And sometimes, especially if your hand is already on the mouse, it's way faster to move the mouse and click then move your hand back to the keyboard to enter a shortcut.

That's probably why this issue is called "Allow hiding the buttons..." not "Remove entirely the buttons...", and as [the original comment said](https://github.com/microsoft/vscode/issues/46403#issue-307956856):

> It would be nice to have an option to hide them as almost everything in the UI already can be hidden.

**Comment by Biakiss** [comment]
For me it would be enough to change the color to that of my background. Can you please tell me which element would i need to modify in colorCustomizations.

![image](https://user-images.githubusercontent.com/107933013/182001732-dbc24aa9-4b11-403a-8239-0347f8f73072.png)

**Comment by eduardmavliutov** [comment]
> For those still looking for a better solution until this feature gets added natively:
> 
> 1. Install the [Customize UI extension](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui)
> 2. Add the following configuration to your `settings.json` file ([additional CSS selectors referenced here](https://github.com/Microsoft/vscode/issues/46403#issuecomment-411604090)):
> 
> ```js
> "customizeUI.stylesheet": {
>   ".editor-actions": "display: none !important;",
> },
> ```

Thank you sooooo much!

Hope that the proper checkbox in the VS Code settings will appear soon 🤞

**Comment by gjsjohnmurray** [comment]
> Take a look at what #154804 has recently brought to Insiders.

This will arrive in the next release, expected next week. See #161802 for info, and try it now on Insiders.

**Comment by beorn** [comment]
So it's supposed to be in 1.72.0 as per the release notes, but (on a mac at least) I'm unable to make it work!  Right-clicking just triggers the action instead of opening the context menu for hiding.  I tried disabling/uninstalling customizeUI as well to make sure it wasn't conflicting.  Can someone confirm that it works?

**Comment by hansu** [comment]
I can only confirm that it works under Linux and Windows.

**Comment by beorn** [comment]
I found a way to workaround the issue on macOS, but it's clearly a bug: basically if I right-click two times without moving the mouse in-between each time, then I get the "Hide" menu the second time.  Any moving of the mouse position means the next click will result in triggering the action instead.

**Comment by costincaraivan** [comment]
I'm going to resolve this, @beorn you should probably file that as a separate bug ;)
