### ISSUE TITLE
Allow to open all files at once from quick open

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#46409]
Issue Type: <b>Feature Request</b>

When searching for a file (Ctrl+P), it would be nice if there was a way to open all files in one step.

Especially in a workspace, I often find myself looking for an approach to this.

![image](https://user-images.githubusercontent.com/1658949/37828681-88b1d5b8-2e9c-11e8-8548-d13494087c92.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by usernamehw** [comment]
You can probably achieve this with extension:

https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-multiple-files

**Comment by oliversalzburg** [comment]
A quick repetition of hitting the Right Arrow and Down Arrow keys also works quite well.
