### ISSUE TITLE
Feature request: Add options "Select for compare" and "Compare with selected" to opened files tabs

### ISSUE THREAD

**Issue by Somnium7** [Microsoft/vscode#46408]
To compare two opened files now I need to switch to Explorer view and click those options there, which is inconvenient, because I need to switch view back to previous (git or search).

Generally, I don't understand at all, why files in explorer's "open files" and in tabs have different options, however, I mostly care only about "Select for compare" and "Compare with selected".

**Comment by bpasero** [comment]
You can use this:

![image](https://user-images.githubusercontent.com/900690/37845186-35aa312a-2eca-11e8-881f-148e37fffeb6.png)
