### ISSUE TITLE
Terminal cmd click links truncates when url spans multiple lines

### ISSUE THREAD

**Issue by raldred** [Microsoft/vscode#46417]
Issue Type: <b>Bug</b>

Have some output in the terminal spit out a link that spans mutliple lines.
CMD + Clicking the link only takes the first line.

![image](https://user-images.githubusercontent.com/2193314/37844049-d10a1924-2e83-11e8-8234-042ed3e0459e.png)

In this screenshot, you can see a `t` wrapped from the previous line, it should be part of the link ending `date-input`

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
project-manager|ale|0.25.0
vscode-color|ans|0.4.5
better-toml|bun|0.3.2
solargraph|cas|0.13.0
vscode-quick-select|dba|0.2.5
gitlens|eam|8.1.1
rspec-snippets|kar|0.0.3
Go|luk|0.6.77
dotenv|mik|1.0.1
vscode-scss|mrm|0.7.0
python|ms-|2018.2.1
azure-account|ms-|0.3.3
debugger-for-chrome|msj|4.2.1
rails-run-spec-vscode|nok|0.1.0
heroku-command|pko|0.0.8
vscode-css-peek|pra|2.1.0
Ruby|reb|0.17.0
sass-indented|rob|1.4.8
Align|ste|0.2.0
vscode-import-cost|wix|2.6.2

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28746

**Comment by raldred** [comment]
Apologies for dup and thank you for fixing!
