### ISSUE TITLE
Windows 10 VSCode icon has black background in many places

### ISSUE THREAD

**Issue by sleutho** [microsoft/vscode#46415]
Issue Type: <b>Bug</b>

Not always, but most of the time VSCode icon shows with black background, instead of transparent background. It doesn't look too good.

The Shell extension icon is not affected, but others are as seen in the screenshot.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
![black icon](https://user-images.githubusercontent.com/1581639/37830506-ccef6322-2e78-11e8-8c42-70259946fc63.png)

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|Memory (System)|31.85GB (24.23GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Public|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.2.1
cpptools|ms-|0.15.0
vscode-icons|rob|7.22.0
hyperworks|sle|0.1.0
optistruct|sle|0.1.0
radioss|sle|0.1.0
tcl|sle|0.2.0
templex|sle|0.1.1

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
Please reopen if you still see this with our upcoming stable release. See https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#updated-visual-studio-code-icon
