### ISSUE TITLE
Feature request: Import file from `Go to File...` in currently opened editor.

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode#46413]
1) Open a file in the editor
2) Open `Go to File...` or `Ctrl+P` and find another file
3) `<invoke some action here>`
4) **Result:** Selected file will get imported with correct path in the currently opened editor

![image](https://user-images.githubusercontent.com/2313018/37829024-bd7f2132-2e9d-11e8-92f7-de4270f6b6c8.png)

Ad 3) version 1
- The open dialog could introduce new icon (next to "Open to the Side" icon) with hover text "Import in current file"
- Some keyboard shortcut will dismiss the dialog and import the file (similar to pressing Enter)

Ad 3) version 2
- Introduce new command `Import File...` that looks similar to `Go to File...`, but pressing Enter imports the file instead of opening a new editor

Ad 3) version 3
- Introduce a modifier key combination `Ctrl+I`. Pressing this combination while `Go to File...` is opened will change it to `Import File...`

**Comment by bpasero** [comment]
Assuming this is about SCSS language.

**Comment by mjbvz** [comment]
JS/TS already has [auto-imports](https://code.visualstudio.com/Docs/languages/javascript#_auto-imports). What use case do these not cover currently?

**Comment by ackvf** [comment]
I was in the middle of a huge folder restructuring and needed to refactor all relative imports. The `auto-import` you suggested was not as helpful as my suggested method would be. Moreover it indeed only handles JS/TS files and some general method for capturing the relative path of a selected file (not requiring to use mouse - _Copy relative path_ from Explorer) would be handy. Though I did eventually fall back to using `auto-import` and did the rest by hand.

**Comment by mjbvz** [comment]
Can you provide a concrete example that shows what you are trying to achieve. My understanding of the proposed flow for js/ts is:

1. Know that I want to use a symbol from a specific file
1. Trigger command that adds the import. This would add a `import * as x from 'x'` style import
1. Then use the import somewhere (but how do you know the namespace name `x` in this example?)

Auto imports on the other hand:

1. Know that I want to use some symbol.
1. Start typing and select the import from the correct file.
1. Import added. 

This seems preferable in my opinion . It also plays nicely with the new `Organize Imports` feature, which will remove any unused imports

**Comment by ackvf** [comment]
There are cases (also in js) where you need to import whole file without a symbol or where you simply need the path as a string. Perhaps the suggested method `Import file...` is an overkill. There is an option in the context menu in Explorer to "Copy Relative Path" - but in my understanding, it's a project root relative path. Having another option to copy file-to-file relative path would be great. ...and then, if we could invoke this command from the command palette - without the need to actually find the file in the Explorer would be even better.

**Comment by mjbvz** [comment]
I'm not convinced this makes sense for core VS Code, but an extension could certainly add this functionality 

Closing as extension candidate
