### ISSUE TITLE
Can the means of choosing separation be improved?

### ISSUE THREAD

**Issue by neilw73** [Microsoft/vscode#46411]
It seems that you can only have one field separator active at a time (comma, semi-colon, etc) and the only way to toggle is through manually editing the configuration. If I'm opening CSV files with different separators, which I do a lot, it's a very clunky interface.

Is there not a better way to support this? e.g. through the F1 key (similar to 'change language' letting you pick from a list)

thanks.

**Comment by bpasero** [comment]
@neilw73 what do you mean with separator, in the editor?

**Comment by neilw73** [comment]
Sorry, I meant comma, semi-colon, pipe, etc.

Changing from one to the other is a bit clunky. Would be nice to somehow make it easier. For example if you look at changing the language of a file, after you press F1 then select 'change language' you get a dropdown of items given to you.

**Comment by bpasero** [comment]
@neilw73 are you using an extension to improve editing CSV files and this issue should maybe be filed against that extension?
