### ISSUE TITLE
from PIL import ImageDraw, ImageFont does not work in vscode, please help

### ISSUE THREAD

**Issue by JayaParmar** [Microsoft/vscode#46416]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
You're going to need to provide more information about the issue. If PIL is referring to Python you would be better off creating an issue at https://github.com/Microsoft/vscode-python
