### ISSUE TITLE
Provide a setting to change the font used for markdown preview

### ISSUE THREAD

**Issue by zcyzcy88** [Microsoft/vscode#4641]
- VSCode Version: 0.10.11
- OS Version: Windows 7 64bit

![image](https://cloud.githubusercontent.com/assets/15178410/14016135/12ba6f00-f1f9-11e5-865a-a216acdf7b43.png)
![image](https://cloud.githubusercontent.com/assets/15178410/14016139/1cdd5326-f1f9-11e5-88e5-c7924673d2ee.png)

**Comment by bpasero** [comment]
I think this should be a separate setting because a font that works for code might not work for reading text.

**Comment by Reanmachine** [comment]
@bpasero Correct me if I'm wrong, but isn't this already covered by the markdown styles setting?

**Styles.css**

    body {
        /* Default Font, should inherit all the way down */
        font-family: "Ume P Mincho";
    
        /* Consistent background color */
        background-color: #efefff;
    }

**settings.json**

    {
        "markdown.styles": [
            "Styles.css"
        ]
    }

Result:

![Resulting Markdown Preview](http://i.imgur.com/0omOU3w.png)

Do we really need a setting to inject a default font?

**Comment by bpasero** [comment]
@Reanmachine good point, however enabling this setting for markdown (markdown.styles) disables any other style being used for markdown preview. 

@zcyzcy88 fyi this is a workaround for the problem, you could actually create a CSS file that contains the font style.

**Comment by Reanmachine** [comment]
Well if we support overriding the default styles piecemeal like suggested wouldn't we end up with settings for many things? Here's a list I can think of off the top of my head:

* font-family
* font-size
* line-spacing
* background-color
* ... etc

This non-exhaustive list would just start cluttering the configuration, perhaps the default stylesheet should be exposed so minimal tweaking can occur? Perhaps this could be solved with a command / extension to dump the default stylesheet into `.vscode/markdown.css` and add it to the styles? Then anyone can make their minimal tweaks without losing all the default styling?

**Comment by bpasero** [comment]
For reference, the CSS we use is in https://github.com/Microsoft/vscode/blob/master/src/vs/languages/markdown/common/markdown.css

**Comment by Huachao** [comment]
And I think if we could support this for the `vscode.previewHtml` command?
