### ISSUE TITLE
Gpg-agent support

### ISSUE THREAD

**Issue by holms** [Microsoft/vscode#46412]
# Env

* VSCode Version: 

```
1.22.0-insider
b75321329388d74e34f79dcfcb789246e31836a8
x64
```

* OS Version: Debian 9

# Steps to Reproduce

1. Enable git commit signing globally
2. Enable git commit signing in UserSettings
3. Create gpg paraphrased key and set it as default to use
4. Try to commit in git, and you will get error message form git which says it's failed to sign

Does this issue occur when all extensions are disabled?: Yes

# Comment

Well this also happens when GPG_AGENT doesn't know which TTY to use, so by setting wrong TTY agent in terminal it will fail too with exactly the same message, because you need to enter passphrase in ncurses window which will be opened only when you commit. By entering this passphrase, there's no need to enter it for next ~10 minutes I think. 

I remember that with passphrased ssh keys Vscode been able to throw a window to enter a passphrase. Can we do this for gpg-agent too?

**Comment by holms** [comment]
Ok seems to be solved, this is all dependent on gpg-agent setup. There's a need to specify a time for caching passphrase, an app to use for entering passhprase when prompted (by default it fall back to curses, so it's failing in X apps), and to specify that you allow to store password at all in agent (this is optional)

~/.gnupg/gpg-agent.conf

```
default-cache-ttl 46000 # optional
pinentry-program /usr/bin/pinentry-gtk-2
allow-preset-passphrase # optional

```

**Comment by NatoBoram** [comment]
That did not resolve my problem. I still have the same error.
```Bash
gpg: cannot open tty `/dev/tty': No such device or address
```
```Bash
git config --global commit.gpgsign
true

cat ~/.gnupg/gpg-agent.conf
default-cache-ttl 46000
pinentry-program /usr/bin/pinentry-gtk-2
allow-preset-passphrase
```
VSCode-Insiders config : 
```JSON
{
	"git.enableCommitSigning": true,
}
```

**Comment by holms** [comment]
@NatoBoram have you installed `pinentry-gnome3` package?

**Comment by holms** [comment]
When you commit from cli, you should have GUi window popup for entering password. If this doesn't happen and you're called back to ncurses input, then it's not a problem of vcode.
