### ISSUE TITLE
ERB missing indentation onEnter

### ISSUE THREAD

**Issue by tyler-boyd** [Microsoft/vscode#46426]
- VSCode Version: 1.21.1 (1.21.1)
- OS Version: MacOS High Sierra 10.13.3 (17D102)

See #28145, it's the same issue but for ERB instead of JS.

Steps to Reproduce:

1. Open an erb file
2. Type `<div></div>`, and have your cursor between the opening and closing tags
3. Press enter
4. Observe that the new line isn't autoindented
<img width="172" alt="screenshot 2018-03-23 10 49 18" src="https://user-images.githubusercontent.com/4432772/37836241-66c274d0-2e88-11e8-8cf4-172841b8edfa.png">

Does this issue occur when all extensions are disabled?: Yes

I have a fix at https://github.com/Microsoft/vscode/commit/75f5cc0259cf77661f9ec3e3182e5c78b740fc87, but I'm not sure if this is the supported way to do it. I see it's how handlebars works.

Thanks

**Comment by nicbet** [comment]
Same issue. 

FYI, applying change in 75f5cc0 manually to the March 2018 update (`/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/package.json`) does not fix the problem for me.

**Comment by Mavvie** [comment]
@nicbet Does manually modifying files like that work normally? I applied that patch and then manually built the `Code - OSS.app` following the instructions in the wiki, and it fixed the issue for me.

I'm very unfamiliar with the codebase and build process here, so it's possible that my fix doesn't work with the March 2018 update.

**Comment by heycalaway** [comment]
Has anything become of this? Tried to manually edit the file as well, but no results.

**Comment by nicbet** [comment]
As of VSCode 1.26.1 problem still exists.

**Comment by nicbet** [comment]
See also #49210, #47288

**Comment by rebornix** [comment]
Just relealized that we have an early issue https://github.com/Microsoft/vscode/issues/39128 talking about the same problem and potential solutions. Let's track it there.
