### ISSUE TITLE
Why can't I automatically hide the search bar? When I clicked on a search result.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#46429]
_From @DebugLyu on March 23, 2018 2:24_

vscode 一切都好，就是这个搜索栏非常 反感，不像 sublime也行 跟 notepad++ 显示在下面 按两下esc关闭 也行啊，这个 常驻左侧，很麻烦，也不美观 还需要 ctrl + b隐藏掉，对我们这些两列编辑的 简直太难受了

_Copied from original issue: Microsoft/vscode-docs#1523_

**Comment by roblourens** [comment]
I don't understand the problem. Please include some more details about what you want.

**Comment by rebornix** [comment]
What @DebugLyu was saying is he doesn't like having the search bar on the left always (unlike Sublime which puts the search bar in the bottom) and he would expect auto hide after clicking on search results. 

I think it's not valid anymore as we can have search viewlet in the panel.

**Comment by roblourens** [comment]
@DebugLyu Please check out the `search.location` setting which might help. But I'm not expecting to autohide the sidebar or anything like that.
