### ISSUE TITLE
Can't allow javascript execution in markdown preview.

### ISSUE THREAD

**Issue by SeongHub** [Microsoft/vscode#46424]
Issue Type: <b>Bug</b>

Hi
sorry for my English.

I want to use the javascript function 'document.write'.

in 1.21.1 version.
although I change security level to allow script execution in markdown preview window, there is no change.
after disable security, still there is no string that witten with 'document.write' function.

if I change the security level in markdown 'editor' window (not preview window), it works.
in this case, I can see string that written with 'document.write' script function
It does not matter whether the preview window is turned on or off.

but change security level in markdown editor window is difficult. because whenever I make new document, I have to press 'ctrl+shift+P' and find the command to allow script execution.

I can change security level to execute javascript in markdown preview window in 1.20.1 version.
but it is impossible in 1.21.1. so I think it is bug.

thank you.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
I can't repro this issue. Please explain the exact steps you are taking, including:

1. How did you open the markdown file? Is it part of a workspace.
1. How are you clicking on the security selector? The popup in the preview, using the the menu bar ,a command?

**Comment by SeongHub** [comment]
I'm sorry.  

---  

This is **answer.**  

> 1. How did you open the markdown file? is it part of a workspace  

I open individual file by pressing ctrl+O  

> 2. How are you clicking on the security selector?  

- I tried both and it was same result in case doing this in preview. popup in the preview and menu button (...) on the top right in the preview.  

---  

and This is **how to Reproduce.**  

1. markdown file content is like below.  
    > <script>document.write("hello");</script>  

1. open the markdown file by pressing ctrl+O.  

1. open preview by pressing ctrl+shift+V.  

1. click popup in the preview. and change security level to execute script.  
    I think when it is first time to open the document. security level is strict. change it to Disable.

1. still I can't see the string "hello".

---  

I can enable javascript executing like this in previous version.

and if change security level like below step. I can execute javascript.

this is **how to execute javascript in this version**(1.21.1).

1. open markdown file by pressing ctrl+O.

1. open preview by pressing ctrl+shift+V.

1. in edit window. press ctrl+shift+P.

1. open "Change Preview Security Setting" and disable security.

1. I can execute javascript. I can see the string "hello".

---  

thank you.

**Comment by mjbvz** [comment]
Thanks @SeongHub! I was able to reproduce the problem with the additional information you provided. Looking into a fix now
