### ISSUE TITLE
code navigateBack and navigateForward does not work on Ubuntu

### ISSUE THREAD

**Issue by s-a** [Microsoft/vscode#46420]
- VSCode Version:
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Datum 2018-03-14T14:46:30.761Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

- OS Version:

Steps to Reproduce:

1. Add the following lines to `keybindings.json`
```javascript
{ "key": "ctrl+alt+left",              "command": "workbench.action.navigateBack" },
{ "key": "ctrl+alt+right",             "command": "workbench.action.navigateForward" }
```
2. Navigate to different code positions in same or different code files.
3. Press <kbd>ctrl+left</kbd> or <kbd>ctrl+right</kbd>

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
It's been like this from the beginning, you can assign a custom keybinding to it pretty easily. it may be unbound on other display managers and changing it would likely cause more problems than fix as we'd break people.
