### ISSUE TITLE
Add support to filter js.map files generated from ts files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4642]
- VSCode Version: 0.10.12
- OS Version: Windows

Steps to Reproduce:
1. Compile TS -> JS including source maps
2. Try to filter the js.map file if a corresponding TS file exists

Wasn't able to do so. Tried:

``` json
"**/*.js.map": { "when": "$basename($(basename)).ts"}
```

**Comment by bpasero** [comment]
@dbaeumer this is currently not supported but I find the notation of 2-times $(basename) interesting. As a workaround for now I suggest you just use `**/*.js.map: true`

**Comment by bpasero** [comment]
@dbaeumer the alternative idea i had was to introduce something like $(filename) that is really the portion of a file without extension.

**Comment by bpasero** [comment]
The easy workaround for anyone hitting this is to just exclude with **/*.js.map: true

**Comment by connelhooley** [comment]
Old post but If it's any help I use the following:

```json
"**/*.js": {
    "when": "$(basename).ts"
},
"**/*.map": {
    "when": "$(basename)"
}
```

It hides map files if there's a matching JS file and hides JS files if there's a matching TS file, leaving you with just TS files. Thought it was a little neater hiding all map files

**Comment by CreepGin** [comment]
+1 on the `$(filename)`. 

I'd like to add that doing a general `**/*.js.map: true` is not the way to go because deleting the corresponding `.ts` file will not reveal the `.js.map` file. I believe this should be the reason why `when` is desired in the first place.

**Comment by cnshenj** [comment]
+1.

There is no way to exclude generated `.min.css` and `.d.ts` now.
An exclude rule without `when` is not a workaround because `.d.ts` files may come from `typings` or `@types` so they don't have a source file and should **not** be excluded.

**Comment by cnshenj** [comment]
`$(filename)` may not be good enough. For example: `my.test.ts` is compiled to `my.test.js` and `my.test.d.ts`. Since `$(filename)` is the name without **any** extension, `$(filename).ts` becomes `my.ts`.

What we need is something like `$(relativeBasename)` that just strip the portion after `*`. `$(relativeBasename)` of `my.test.js.map` is `my.test`, when the rules is `**/*.d.ts`. If we change rule to `**/*.map`, then `$(relativeBasename)` becomes `my.test.js`.

**Comment by whitecolor** [comment]
Any news on this? Need to be able to hide *.d.ts and *.map.js the same way as ".js" that lay near ".ts".

**Comment by whitecolor** [comment]
Hey, ".d.ts" was fixed, but not ".js.map" kind of strange? 😃

**Comment by isidorn** [comment]
I see there are some workarounds.
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
