### ISSUE TITLE
German user can't installed extensions due to localized paths

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#46432]
From email:

```
Hi Dear VS-Code team
I Can't install extensions: e.g.
extension: Bootstrap 4, Font awesome von Ashok Koyi:
Error (german):
Fehler beim Installieren von "thekalinga.bootstrap4-vscode". à Error during the installation  "thekalinga.bootstrap4-vscode".
VS-Code tells me that he can't rename C:\Users\m-o\.vscode-insiders\extensions\something...
My Windows is in german so the path is different: not C:\User: I have C:\Benutzer:
C:\BENUTZER\m-o\.vscode-insiders\extensions
 
not sure if this is the error, but it seems that I can't install any extensions at the moment.
Thanks Marco
```

**Comment by auchenberg** [comment]
More info requested from user.

**Comment by auchenberg** [comment]
More info from user:

![image001](https://user-images.githubusercontent.com/173559/37867427-b5fbaa80-2f55-11e8-9b3c-1a03d2e70919.png)
![image002](https://user-images.githubusercontent.com/173559/37867428-b747ead4-2f55-11e8-9607-e832a52b785b.jpg)

**Comment by sandy081** [comment]
@auchenberg May I know if the user has Defender enabled?  And does it work if Defender is disabled?

**Comment by auchenberg** [comment]
Emailed the customer and added you on the thread @sandy081

**Comment by auchenberg** [comment]
User re-installed and stuff works. Closing for now.
