### ISSUE TITLE
File picker: support pattern with line/column number in <path>(ln,col) syntax

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4643]
Should be able to open a path like the following with line/col information:

/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/parts/search/browser/openAnythingHandler.ts(199,42)

**Comment by isidorn** [comment]
@bpasero Works fine, but if I put a whitespace between the line and column it does not work.

**Comment by bpasero** [comment]
Much drama.
