### ISSUE TITLE
Task exit code is set to 1 regardless of problem severity

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#46439]
Issue Type: <b>Bug</b>

`terminalTaskSystem.ts` has a section of code that sets the `exitCode` of a task to `1` purely based on whether or not the problem matcher has any matches:

https://github.com/Microsoft/vscode/blob/9de24bfa5bcd2a7cb5bf4e3f6bf711bc9f20290e/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L366-L369

This seems incorrect, as the `severity` of those matches also has to be considered - this check should only trigger if at least one of the matches has `MarkerSeverity.Error`. In this case, a single warning is enough to trigger it (severity 4):

![](https://i.imgur.com/85AeUXO.png)

Which means the debugger isn't launched if such a task is used as a `preLaunchTask`, despite there not being any errors:

![](https://i.imgur.com/ldfrs1H.png)

This was originally reported to us at the Haxe extension here: https://github.com/vshaxe/vshaxe/issues/180

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by dbaeumer** [comment]
The underlying problem is deeper than this. The terminal itself doesn't always report the correct exit code. I will recheck what the current status with the terminal is.

**Comment by dbaeumer** [comment]
To verify:

- check that the code mentioned here https://github.com/Microsoft/vscode/issues/46439#issue-308152754 doesn't exist anymore
- git clone https://github.com/Microsoft/vscode-languageserver-node
- open workspace
- open task.json
- change the presentation.reveal property to `silent` for the compile:types task.
- put an error into types/src/main.ts
- close
- run the compile:types task. 
- Ensure that the terminal pops to front.
- do the same for the watch:types task.
- Ensure that if a watch run produces errors the terminal comes to front.
