### ISSUE TITLE
Allow to restore the contents of any opened tab even if deleted

### ISSUE THREAD

**Issue by JakubRimal** [microsoft/vscode#46431]
Issue Type: <b>Feature Request</b>

This is a follow-up to #45194.

Setting option `workbench.editor.closeOnFileDelete` to `false` solves some common problems with deleted files but there are still two problems which are not covered:

1. It doesn't work for files which have not been focused.
1. It doesn't work for files which have been deleted when vscode was not running.

When the second problem will be solved it would solve the first one as well.

Basically it means that hot-exit feature should store backups for each file that is currently opened (even if they are not "dirty").

**Motivation:**
Problem number 1:
You open your project in vscode where you have opened some files and then (without focusing other than the currently focused file) you switch to another git branch where files which you have opened don't exist. All (except currently focused) your previously opened files will be closed by vscode as they don't exist in this branch. You switch back to the original branch and you need to reopen all files you have opened at the beginning.

Problem number 2:
You have opened some files in vscode and then you close vscode. After that you switch to another git branch where files which you had opened doesn't exist. You want to have a look at some file in this branch so you open it in vscode. All your previously opened files are closed as they don't exist in this branch. You switch back to the original branch and you need to reopen all files you have opened at the beginning.

**Another motivation:** It can save your work when you accidentally delete some file(s) you have opened in vscode. All you need to do is to focus tab with your deleted file and press Ctrl + S.

I think that the behavior described above is the one which is expected by users which have set `workbench.editor.closeOnFileDelete` to `false` and it is very useful. The current behavior is very unpredictable (at least unless you know that it depends whether a file has been focused after vscode start or not).

Thank you for considering this FR.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

**Comment by bpasero** [comment]
@JakubRimal 

> Thank you for considering this FR.

Very unlikely to do because I do not see any efficient way of implementing what you are proposing. A file that is not activated in VS Code is not loaded so in order to preserve a such a file we would have to keep each and every tab that is opened in memory just for the case that the file gets deleted. The same applies for when VS Code is not running and you change branches and then start again.

If you have an idea how this could be done efficiently, let me know, otherwise I will close this as wontfix as I see no way how to implement this.

**Comment by JakubRimal** [comment]
@bpasero I think that there is only one thing vscode should do and that is to save a backup of all currently opened files when vscode exits. This would cover both cases described above and even unexpected force-close of vscode because the backup of each file was saved on the last vscode exit or it is already covered by hot-exit feature. There is only one (very uncommon) use-case which it doesn't cover: you have some newly opened file, then vscode is force-closed, then that file is deleted and then the vscode starts again.

There is no need for extra start-up time as the loading of backup of deleted file can be done once the tab is focused.

So I guess that it's all about saving the backup of all currently opened files to disk when vscode exits - why it is not efficient? How many tabs has an average user opened and what size it is in total?

**Comment by bpasero** [comment]
> How many tabs has an average user opened and what size it is in total?

I think that is the underlying problem, this number can be a) very large and b) potentially span large files. Since files can change between VS Code restarts we would have to constantly poll for the contents of these files to restore them.

Is it really VS Code's responsibility to track all files that you opened to potentially restore their contents when the file ever gets deleted? I am not convinced, imho that goes beyond the role of a text editor. I would rather think that this should be the job of a SCM like Git.

**Comment by JakubRimal** [comment]
The main reason why I've created this FR is that the current behaviour is inconsistent. Vscode already stores all dirty files and recovers them even if they are deleted. I suggest the same for all opened files, there is no need to poll - vscode would save the last seen state as it already does with dirty files.

> Is it really VS Code's responsibility to track all files that you opened to potentially restore their contents when the file ever gets deleted? I am not convinced, imho that goes beyond the role of a text editor. I would rather think that this should be the job of a SCM like Git.

Of course it's not but it could be a nice feature. The main reason for this FR is not to recover deleted files but to keep tabs opened (which is really handy while you use Git you've mentioned).

As I already said above, the main problem (which is a bug in my eyes BTW) is inconsistent behaviour which depends on things like "was the tab focused" and "is the file dirty". Everything else is nice to have but I would say that this consistency is essential.
