### ISSUE TITLE
We shouldn't provide CSS Emmet completions inside comments

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#46434]
Steps to Reproduce:

1. Open a stylesheet file
2. Add a comment /* */
3. Start typing `m5` --> Emmet provides completions
4. Hit backspace --> Emmet provides completions for `m`

The `m` character doesn't trigger completions, but the numeric ones do.

**Comment by ramya-rao-a** [comment]
@jrieken numbers are trigger characters for emmet completion provider. Looks like even when `editor.quickSuggestions.comments` is `false`, typing a trigger character inside comments does trigger completions.

**Comment by ramya-rao-a** [comment]
I have pushed a fix for emmet getting triggered inside comments in stylesheets.
But this is a generic problem. 
Consider the below content in a php file
```
<div class="parent">
    <!--<div class="child">  
        ul*
    </div>-->
</div>
```

Type a number next to `ul*` and see emmet completions getting triggered.

@jrieken Is it expected that trigger characters trump the `editor.quickSuggestions.comments : false` setting?

**Comment by jrieken** [comment]
> Is it expected that trigger characters trump the 

yes

**Comment by ramya-rao-a** [comment]
Thanks @jrieken 
Closing this as fixed for stylesheets and html files
