### ISSUE TITLE
tasks.json Environment Variable Expansion Broken When Variable is Not Defined

### ISSUE THREAD

**Issue by beufordy3k** [Microsoft/vscode#46436]
- VSCode Version: 
Version 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:09:39.780Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows 10 Enterprise x64
```
Major  Minor  Build  Revision
-----  -----  -----  --------
6      2      9200   0
```

Steps to Reproduce:

1. Create a task in tasks.json using latest 2.0.0 format
2. Add an environment variable to the args parameter string
3. If variable is present, value will be properly expanded
3. If variable is **not** present, value will incorrectly use the literal environment variable name

Does this issue occur when all extensions are disabled?: Yes

This worked in vs code 1.19.3 and broke in 1.20.0 and is still broken in the latest version 1.21.1.

Issue is reproduced here, https://github.com/beufordy3k/vscode-tasks-environment-issue

### Task Output from 1.19.3
```
> Executing task: dotnet build <

Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 38.05 ms for C:\tmp\projects\vscode-tasks-environment-issue\vscode-tasks-environment-issue.csproj.
  vscode-tasks-environment-issue -> C:\tmp\projects\vscode-tasks-environment-issue\bin\Debug\netcoreapp2.0\vscode-tasks-environment-issue.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.33

Terminal will be reused by tasks, press any key to close it.

> Executing task: C:\tools\CustomTool.exe server=localhost;database=CustomDatabase;Trusted_Connection=Yes;Connection Timeout=15; <
```

### Task Output from 1.20.0
```
> Executing task: dotnet build <

Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 53.19 ms for C:\tmp\projects\vscode-tasks-environment-issue\vscode-tasks-environment-issue.csproj.
  vscode-tasks-environment-issue -> C:\tmp\projects\vscode-tasks-environment-issue\bin\Debug\netcoreapp2.0\vscode-tasks-environment-issue.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.04

Terminal will be reused by tasks, press any key to close it.

> Executing task: C:\tools\CustomTool.exe server=localhost${env:MyCustomVar};database=CustomDatabase;Trusted_Connection=Yes;Connection Timeout=15; <
```

**Comment by dbaeumer** [comment]
@isidorn assigning to you since I remember us talking about this for the configuration resolver service. Didn't we discuss to use the variable name only for VS Code variables lile $file. For env we should do the same as a normal shell does which evaluates missing envs to empty string. Please move back if there is something I need to do.
