### ISSUE TITLE
ошибка кодировки UTF-8 в Python при выводе в консоль

### ISSUE THREAD

**Issue by Mihail-D** [Microsoft/vscode#46437]
Issue Type: <b>Bug</b>

Python code, (string) in Cyrillic is displayed with rhombs with question marks inside. How to fix it? UTF-8 encoding does not work

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7400  @ 2.80GHz (2 x 2800)|
|Memory (System)|8.00GB (4.62GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.3
python|ms-|2018.2.1

</details>
Reproduces without extensions

**Comment by dbaeumer** [comment]
Can you please provide a screen shot showing where the test is not rendered correctly.

**Comment by dbaeumer** [comment]
This is a know issue with tasks and the old Output runner. Please use the new 2.0.0 version of tasks. There is also a section in the doc explaining how to do with character encodings and tasks: https://code.visualstudio.com/docs/editor/tasks#_changing-the-encoding-for-a-task-output
