### ISSUE TITLE
Auto indent after comments ignores indent of previous comment line.

### ISSUE THREAD

**Issue by ahinkle** [microsoft/vscode#46444]
Issue Type: <b>Bug</b>

This little bug has been bothering me for quite some time.. decided to make a note about it.
1. Write a section such as `// note`
2. Hit Enter
3. Hit Tab
4. It will move over 3 tab spaces instead of once.

I've noticed this won't happen every time but still fairly often.

![Bug](https://media.giphy.com/media/5e1Siu5oUVRqqpZAWl/giphy.gif)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-wakatime|Wak|1.1.26
better-comments|aar|1.2.1
laravel-docs|aus|1.0.2
ghlink|dt|0.0.6
vscode-great-icons|emm|2.1.30
php-intellisense|fel|2.3.0
vue-snippets|hol|0.1.5
vetur|oct|0.11.7
laravel-blade|one|1.17.0
laravel5-snippets|one|1.4.0
advanced-new-file|pat|1.1.0
vscode-fileutils|sle|2.8.1
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment]
Full repro:

![kapture 2018-03-27 at 23 16 35](https://user-images.githubusercontent.com/5047891/37995488-eec912a0-3214-11e8-9d69-850fcb854e22.gif)

The root cause is the editor auto-indent feature. Workaround is to disable `"editor.autoIndent"`

**Comment by rebornix** [comment]
This is due to the inability to know whether we should ignore the indentation of comments (as it can be different) or it should honor the comments' indentation (see it as part of the code structure). We currently don't have proper way to fix this issue through auto indentation rules, so recommend to set `editor.autoIndent` to `advanced`.
