### ISSUE TITLE
"Go to next problem" ignores "Info" level severity markers

### ISSUE THREAD

**Issue by quackingduck** [Microsoft/vscode#46442]
- VSCode Version: 1.22.0-insider
- OS Version: macOS 10.13.3 (17D102)

Steps to Reproduce:

1. Open a document with an "Information" level marker. Probably the easiest way to do this is to install the cSpell extension then misspell a word
2. Press `f8` or invoke the "go to next problem" action

Does this issue occur when all extensions are disabled?: Yes

I've worked around this by upgrading the severity level of cSpell markers from "Information" to "Error" ... and perhaps that's the recommended approach, but in that case the issue is that the action is mislabeled because it currently says "Go to Next Problem (Error, Warning, _Info_)"

https://github.com/Microsoft/vscode/blob/a9761fbbe5defce26af05a122355043f2fc0a3b9/src/vs/editor/contrib/gotoError/gotoError.ts#L365

But only Error and Warning markers are scanned

https://github.com/Microsoft/vscode/blob/a9761fbbe5defce26af05a122355043f2fc0a3b9/src/vs/editor/contrib/gotoError/gotoError.ts#L309

This is the first time I've filed an issue a against this project. I read the contributing guidelines but if I've missed something please let me know.

**Comment by jrieken** [comment]
Nice catch...
