### ISSUE TITLE
Git: gpg: cannot open tty `no tty': No such file or directory

### ISSUE THREAD

**Issue by OGNova** [Microsoft/vscode#46447]
When attempting to commit files with gpg signing, VSCode will show an error which is `Git: gpg: cannot open tty `no tty': No such file or directory` I believe that this is slightly related to issue #5065

This issue occurs on version 1.21.1, Windows 10 Version 1709. This does still occur with all extensions disabled.

**Comment by holms** [comment]
Check this one: https://github.com/Microsoft/vscode/issues/46412
Might solve your issue it's all about gnu-agent setup.

**Comment by joaomoreno** [comment]
#43809
