### ISSUE TITLE
Feature Request: provide search button for Search panel

### ISSUE THREAD

**Issue by devuxer** [microsoft/vscode#46449]
The Search panel lacks an actual search button. As best I can tell, the only way to execute a search is to put the cursor in the search box and press Enter. If the cursor is not currently in the search box and my hand is already on the mouse, this is a bit of a pain.

The refresh button can already serve the purpose of a search button, but it is only available when results from a prior search are showing. If you clear the results (or if the VSCode window is newly opened), the refresh button is dimmed/unavailable.

So, one possibility would be to make the refresh button available for the scenario where something is in the search box but no results are currently showing.

Another possibility, which I think would be a little more intuitive (though at the expense of an extra button), would be to put a dedicated button next to the search box (which aligns with the replace all button next to the replace box). I'm not sure what the best icon to use for "find all" would be, but here's a possibility:

![execute search button](https://user-images.githubusercontent.com/1298521/37857123-e421b3fa-2eb5-11e8-80bd-84af5aa1983a.png)

**Comment by roblourens** [comment]
> If the cursor is not currently in the search box and my hand is already on the mouse, this is a bit of a pain.

Wouldn't you have just typed the search query, and so your hands are on the keyboard? Or is this about muscle memory from other editors that have 'search' buttons?

**Comment by devuxer** [comment]
I actually had to think about that. I think it is a muscle memory thing in some cases. I may be anticipating that I want to use the mouse to step through the results and grab it the before I execute the search. Sometimes, I might verify my search term in a code file before I execute it. All I know is, I do sometimes wish I could just hit a button.

If it is a muscle memory thing, the within-file find dialog does nothing to encourage this, as it has a button not only for forward search but for backward search as well.

**Comment by misolori** [comment]
There are several places where we use the keyboard to execute a command (source control, console, terminal) so that means we'd need to look at adding buttons in those areas. I'm personally not a fan of that because using your keyboard is the most efficient way to run a command.

I could see us improving the search experience by either showing placeholder text that explicitly tells you to hit enter (like in the scm view):

<img width="50%" src="https://user-images.githubusercontent.com/35271042/45499453-50b32b80-b731-11e8-9a63-af25c5181afa.png">

Or providing search suggestions as you type (like GitHub):
<img width="50%" src="https://user-images.githubusercontent.com/35271042/45499503-688aaf80-b731-11e8-9a3f-090134f95026.png">

**Comment by devuxer** [comment]
Using a keyboard to execute a command is not necessarily the most efficient way to execute the command. That's only true if (1) your hands are already on the keyboard and (2) you have memorized the command and are well practiced at executing it.

As I said above, there are cases where your hands might not be on the keyboard, and given that the within-file find dialog _does_ have buttons, the UI is inconsistent.

**Comment by misolori** [comment]
Given that this would require us to place buttons in all input areas (Git, Find and Replace, Extension, Filter, etc.) I don't think this is something we will tackle soon. With that said, I'll be closing this issue as `out-of-scope` and if we ever re-visit this idea we can re-open the issue. Thanks.

**Comment by devuxer** [comment]
OK...thanks for considering it.
