### ISSUE TITLE
Completion box appears in wrong place

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#46446]
When having suggestions without documentation, I've seen the completion box appear in a different place than the expected. Most of the times, where the last suggestion was triggered (or beginning of the document if it's the first time).

Here's an example on a CSS document, though I could reproduce in JSON and HTML as well.

![completions](https://user-images.githubusercontent.com/5607882/37855156-254f8812-2eab-11e8-9ac7-28bc5879749c.gif)

This happens in 1.21 as well as in today's Insiders

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Should be fixed with https://github.com/Microsoft/vscode/commit/a9761fbbe5defce26af05a122355043f2fc0a3b9#diff-caac303ecc98a837b262c2c9a093026d. Please try again in the Insiders on Monday
