### ISSUE TITLE
Different absolute path resolution for imgs in markdown preview

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#46448]
Steps to Reproduce:

1. For a workspace:

    ```
    docs/
        readme.md
    images/
        cat.gif
    ```

1.  With `readme.md`:

    ```md
    <img src='/images/cat.gif' />
    
    ![](/images/cat.gif) 
    ```

1. Open markdown preview of `readme.md`

**Bug**
First image using `img` tag not loaded. This is because it is resolved to `vscode-resource:/images/cat.gif`

<img width="982" alt="screen shot 2018-03-23 at 3 52 26 pm" src="https://user-images.githubusercontent.com/12821956/37856716-3a56c934-2eb3-11e8-9e79-ee043ba872c4.png">

**Comment by joselcvarela** [comment]
@mjbvz can you explain why you marked this as out-of-scope?
I am experiencing this issue too. While it works with relative paths, it would be super useful if it works with absolute paths too 👍
