### ISSUE TITLE
Builtin extension in installed extensions directory

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46453]
Some time ago, @mjbvz and I both saw old versions of the node2 extension installed next to marketplace extensions on our machines.

Investigating https://github.com/Microsoft/vscode/issues/45657 (via email), we found that @lostfields had the same issue.

I don't know how it's possible for this to happen without explicitly installing node2 via a vsix or something else unusual.

@sandy081 can you point me towards the code that should skip builtin extensions when autoupdating extensions? Is it possible that it could install node2 from the marketplace when it shouldn't?

**Comment by sandy081** [comment]
@roblourens Here is the [code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L563) that triggers auto update.

But, we only auto update extensions from user extensions folder and not those coming from internal extensions folder.

**Comment by roblourens** [comment]
🤷‍♂️
