### ISSUE TITLE
Can not Align each column of words by using TAB.Proof of IMG

### ISSUE THREAD

**Issue by netldds** [Microsoft/vscode#46456]
- VSCode Version:1.21.1
- OS Version:WIN 10

Steps to Reproduce:

1.Type words in first row and next,BUG occurs when trying Align them to same column.
[show the issue](https://imgur.com/a/7CWf7)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@netldds Please use a font (e.g. Inconsolata) where CJK characters are always rendered with the width of two latin characters.
