### ISSUE TITLE
No IntelliSense for default export of static member in TypeScript.

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#46450]
- VSCode Version: 1.21.1
- OS Version: Windows 10 x64

Steps to Reproduce:
"foo.ts"
```
export class Foo {
    public static instance = new Foo();
    public bar: string = "Jack";
}

export default Foo.instance;
```

"test.ts"
```
import foo from "foo";
function test() { console.log(foo.bar); }
```

In "test.ts", when you type `.` after `foo`, there is no IntelliSense suggestion. Also, hovering over symbol `foo` doesn't show any type information.

If I change "foo.ts" export statement to the following, then it works:
```
const foo = Foo.instance;
export default foo;
```

TypeScript compiler can compile both versions without any error.

This could be a TypeScript issue instead of VSCode issue, please triage.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22885
