### ISSUE TITLE
The clicked view does not focus when Code is brought to front via click

### ISSUE THREAD

**Issue by dvdsgl** [Microsoft/vscode#46454]
- VSCode Version: 1.21.1 `79b44aa` x64
- OS Version: macoS 10.13.3

Steps to Reproduce:

![2018-03-23 19 45 18](https://user-images.githubusercontent.com/108197/37859565-de9f1770-2ed2-11e8-8106-d70a79c6b498.gif)

1. Open Code with an unfocused editor, pane, terminal, or any view that can receive input.
2. Switch to another app so Code goes into the background.
3. Click the unfocused view in the Code window.
4. Notice that Code comes to the front, but the clicked view does not receive focus.
5. Begin typing and see input received by the view that was focused at #2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@dvdsgl that is standard macOS behaviour. For an option to change this, we have https://github.com/Microsoft/vscode/issues/24634

**Comment by dvdsgl** [comment]
I think it's worth considering that Xcode behaves this way. Apparently Apple engineers felt that this was a default behavior appropriate for a developer tool.
