### ISSUE TITLE
Test: window.openWithoutArgumentsInNewWindow setting

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46460]
Refs: https://github.com/Microsoft/vscode/issues/48

- [x] Windows @sandy081 
- [x] Linux @aeschli 
- [x] macOS @mjbvz 

Complexity: 2

A new setting `window.openWithoutArgumentsInNewWindow` was added to control if running code without arguments should open a new empty window or not. 

**Verify macOS**
* this setting is OFF by default and running the Code executable (from the command line) focuses the last active window
* changing this setting to ON will instead open a new empty window

**Verify Windows/Linux:**
* this setting is ON by default and running the Code executable (e.g. from the command line or by double clicking on desktop) opens a new empty window
* Windows: shift+click or middle-mouse-click on the taskbar icon should open a new empty window when Code is already running
* changing this setting to OFF will instead focus the last active window

**Comment by aeschli** [comment]
Talked to @bpasero, the setting is only used when `code` is ran a second (or more) time, when there's already a code window open.
