### ISSUE TITLE
vscode jsdoc import module type def not imported

### ISSUE THREAD

**Issue by shivshankar3578** [Microsoft/vscode#46463]
@vscode:1.21
@node: 8.10

mod.js

```js
/**
 *  @module mod
 */

/**
 * @typedef {Object} foobar
 * @property {String} foo
 * @property {Boolean} [bar] - Optional value
 */

/**
 * 
 * 
 * @param {string} foo 
 * @param {string} bar 
 * @return {foobar} 
 */
function doSomething (foo, bar) {
  console.log(foo, bar);
  // do something
  return {
	foo : foo,
	bar : bar
  }
}

let n = doSomething('a', 'b');

module.exports  = doSomething;
```

jsdoc.js

```js
const mod = require('./mod');
let n = new mod('a', 'b'); 
console.log(n)
```
pic-1 n:foobar

[![pic-1][1]][1]

then why n:any here

[![pic-2][2]][2]

while  imported module have foobar return type

[![pic-3][3]][3]

  [1]: https://i.stack.imgur.com/RtfVu.png
  [2]: https://i.stack.imgur.com/TnFxS.png
  [3]: https://i.stack.imgur.com/o8x6s.png

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22884
