### ISSUE TITLE
Keep terminal usable after "code ."

### ISSUE THREAD

**Issue by kallebornemark** [Microsoft/vscode#46462]
Issue Type: <b>Feature Request</b>

1. Run `code .` in some folder from terminal
2. Terminal is now actively running Code:
```
$ code .
[main 11:42:15 AM] update#setState idle
```
... and terminating the process closes Code, hence rendering that terminal window/tab unusuable.

What I would prefer is the way Sublime handles this. Running `subl .` opens Sublime in the current folder, without actively using up the terminal window. This allows you to continue using that terminal window, and you don't have to keep a terminal instance running just to keep Code open.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3300)|
|Memory (System)|7.97GB (4.31GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
line-jumper|ale|0.1.0
vscode-custom-css|be5|2.7.0
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
scaffold|fir|1.0.0
vs-color-picker|lih|0.7.0
theme-monokai-pro-vscode|mon|1.1.5
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.2.1
vetur|oct|0.11.7
sass-indented|rob|1.4.8
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|2.9.0
vscode-fileutils|sle|2.8.1
react-beautify|tai|0.3.0
ayu|tea|0.14.0
sensitive-replace|vil|0.1.1
markdown-all-in-one|yzh|1.1.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
What does `which code` return?

**Comment by kallebornemark** [comment]
My `PATH` includes the folder in which I have VS Code installed (`C:\Program Files\Microsoft VS Code`).

Is the behavior I explained not the intended one?

**Comment by joaomoreno** [comment]
You should add `C:\Program Files\Microsoft VS Code\bin` instead, where there's a launcher script which will do the right thing.

**Comment by kallebornemark** [comment]
Thank you, much appreciated. Is this documented somewhere, and I just missed it?

**Comment by TheyCallMeAlexander** [comment]
Thanks a lot **joaomoreno** !!!

**Comment by yoxalld** [comment]
I am having this same issue and I have `C:\Program Files\Microsoft VS Code\bin` in my $PATH. Any help on this would be wonderful. It's very annoying to have to open vscode manually and find files/folders when I'm used to just opening them from a terminal since I'm working in a terminal more often than not.

Thanks!
