### ISSUE TITLE
Debugger - skipFiles wildcard does not work

### ISSUE THREAD

**Issue by adyz** [Microsoft/vscode#46472]
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: MacOS High Sierra 10.13.3 (17D102) (Happens on windows too)

Steps to Reproduce:

1. Install Chrome debugger
2. install and init create-react-app: `npm install -g create-react-app` and `create-react-app`
3: cd into the new app and eject the app from the create-react-app `npm run eject`
4: install any custom package (I tried underscore): `npm install underscore --save`
5: create a new function that will use underscore `_.each([1, 2, 3], console.log('i am under');`
6:
Add this config: 
```
{
            "name": "Launch localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/src",
            "disableNetworkCache": true,
            "sourceMaps": true,
            "skipFiles": [
                "${workspaceRoot}/**/gica.tsx",
                "${workspaceRoot}/node_modules/underscore/*.js"
            ],
            "sourceMapPathOverrides": {
                "webpack:///./src/*": "${webRoot}/*"
              }
        },
```
7: run `npm start`
8: set a breakpoint on the new created function
9: launch the debugger

Now with the config above all works very nice (does not go in the underscore library when I `Step Into`. I love this feature in vscode a ton!

But, since this app uses tons on node_modules, I would like to be able to skip all the node_modules with a wildcard like so `"${workspaceRoot}/node_modules/**/*.js"` unfortunately this does not work even if most of the documentation I read says it should. (Wildcard even in a non node_modules folder fails to skip too)

Am I doing something wrong?

I want to mention that I noticed this on a personal project, but thought that this might be because of my project setup so that is why tried with a new create-react-app and it's the same issue.

Thanks a ton!

**Comment by adyz** [comment]
I added this question on stackoverflow too: https://stackoverflow.com/questions/49468689/visual-studio-code-debug-create-react-app-without-stepping-into-node-modules-o

Recording on the unwanted behaviour: http://recordit.co/3s0eddwZMn

**Comment by roblourens** [comment]
This is a gap in the Chrome debug extension resolving skipFiles... for files without sourcemaps, you will have to set the path relative to the webroot.

`"/node_modules/**/*.js"` works fine for me. I'll move this to the chrome-debug repo for fixing.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug#634
