### ISSUE TITLE
babel plugin transform export extensions

### ISSUE THREAD

**Issue by aprilmintacpineda** [Microsoft/vscode#46479]
<img width="535" alt="screen shot 2018-03-25 at 11 11 58 am" src="https://user-images.githubusercontent.com/21032419/37871297-5d0506d8-301d-11e8-9a6c-cb1eaab6acf4.png">

I tried to search for an extension that supports the syntax above but I can't find any.

- https://babeljs.io/docs/plugins/transform-export-extensions
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: macOS Sierra 10.12.6

**Comment by dbaeumer** [comment]
@mjbvz any help ?

**Comment by mjbvz** [comment]
The built-in js/ts support already allows:

```js
export { default as TextField } from './component/TextField';
```

Support for the `export TextField from` syntax is tracked by https://github.com/Microsoft/TypeScript/issues/4813
