### ISSUE TITLE
"Go to definiton" can't work intermittently and Restarting VScode instance works again.

### ISSUE THREAD

**Issue by deng4437** [Microsoft/vscode#46485]
- VSCode Version:1.18.1
- OS Version:Windows7 x64

I've been using vscode for building React application with lots of npm packages.
One thing that gets me mad is **Get to definition** is often not able to work intermittely somehow either by **F12** or **ctrl+click**. at the same time, **FindAllReference** and **PeekDefinition** all can't work.

Steps to Reproduce:
1: Say we have a statement `import React from "react" ` in the editor

2: **Ctrl+click** or **F12** at **React**  both fail to work , and you will see a **blue bar** on the top of the vscode window keeps moving from left to right again and again.

3:This happens intermittely and I really have no idea about it , so weired.

4:To work around this problem , currently I have to restart that VSCode instance.  This way turns out to work!!

**Comment by mjbvz** [comment]
@deng4437 Can you test this on the latest VS Code version (1.21). Also, please try disabling all extensions to see if one of these is causing issues
