### ISSUE TITLE
MacOS - opening file in file explorer not possible only with keyboard

### ISSUE THREAD

**Issue by Hurtak** [Microsoft/vscode#46489]
There does not seem to be a way to open file from inside the file explorer only with keyboard, on MacOS.

I have only found commands for opening file in new editor window and for opening MacOS native open file dialog.

cmd+o, which is usually how you open files in finder with keyboard, opens the MacOS open file dialog, it should probably open the selected file when I have file explorer focused.

**Comment by bpasero** [comment]
@Hurtak `Cmd+ArrowDown`

**Comment by Hurtak** [comment]
Thanks for help. 

Would modifying the default keybindings to something like this make sense?
```
  {
    "key": "cmd+o",
    "command": "list.select",
    "when": "filesExplorerFocus"
  }
```
