### ISSUE TITLE
Add a new section next to"Open Folders" which lists the files with an errors to be fixed

### ISSUE THREAD

**Issue by laconstituante** [Microsoft/vscode#46484]
- VSCode Version: All
- OS Version: All

The problem

1. On an existing Typescript project, if you make breaking changes, you need an easy way to go through all the affected files to make the change. 
Currently the file explorer changes the files color to red so that you know something is wrong there.

The suggestion:

It would be nice if we can add a new tab called something like "Files that need fixing" where we can easily see all the files that need some more attention, eventually unit test to be rewritten.. which gives a quick overview of the amount of work necessary to make a breaking change.

**Comment by isidorn** [comment]
This can curretnyl be seen by F1 > view toggle problems
This is our designed solution for looking at the list of files that have issues - this should not be a part of the open editors view or the explorer, thus closing this as designed.
If you have suggestions on how to improve the problems view please file a new feature request. fyi @sandy081
