### ISSUE TITLE
Neo keyboard layout: How do I map "Ctrl+ä"? How do I use "Ctrl+["?

### ISSUE THREAD

**Issue by krux02** [microsoft/vscode#46481]
I use this keyboard layout. It is not standard, but it is very good and it gains a lot of popularity.

http://neo-layout.org/grafik/druckvorlage/neo-druckvorlage.png

The problem I have is with binding keys on that keyboard layout.

For example that keyboard layout has a specific undo key (AltGr+Z). VSCode completely ignores that key. I can't map it to undo.

Since I have a few keys that no other keyboard has, I thought I could use them to bind them to functions and therefore avoid conflicts. For example the keyboard shortcut `Ctrl+ü`. But VSCode here maps `ü` (without my permission) to what the us keyboard would have at that position, which is `z`. And now I get `Ctrl+z`. This is not what I wanted, because that is already mapped to undo.

And then there are keyboard bindings predefined, for example `Ctrl+[`. `[` is on the same key as `L`, but I have to press a modifier with it. But VSCode here thinks again. The modifier is completely filtered out and and instead of `Ctrl+[` VSCode thinks I pressed `Ctrl+L`. There is no way I can type `Ctrl+[`.

As a result I am not able to use all predefined keyboard shortcuts and I can't remap those shortcuts to the extra keys that I do have.

**Comment by krux02** [comment]
I am not sure if `feature-request` is the right tag here. I am not asking for a specific feature here at all. All I am asking is that I can use and map basic keyboard shortcuts.

**Comment by fdietze** [comment]
I agree, In my opinion, this should be a bug instead.
