### ISSUE TITLE
[codelens] Uncaught TypeError: Cannot read property 'symbol' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#4648]
Issue Id: <b>fdb03a15-a09e-dd31-745c-e8e3f026de5c</b><br /><br />*Versions* <br />- 0.10.12-insider<br />*Stack* <br />TypeError: Cannot read property 'symbol' of undefined<br />    at e.computeIfNecessary (out/vs/workbench/workbench.main.js:62:9185)<br />    at out/vs/workbench/workbench.main.js:62:14388<br />    at Array.forEach (native)<br />    at e._onViewportChanged (out/vs/workbench/workbench.main.js:62:14360)<br />    at e.runner (out/vs/workbench/workbench.main.js:62:11552)<br />    at e.onTimeout (out/vs/workbench/workbench.main.js:28:12113)<br />

**Comment by bpasero** [comment]
Stack:

```
/vs/editor/contrib/codelens/browser/codelens.ts#298:17 (symbol) 
/vs/editor/contrib/codelens/browser/codelens.ts#605:24 (computeIfNecessary) 
/vs/editor/contrib/codelens/browser/codelens.ts#604:15 (forEach) 
/vs/editor/contrib/codelens/browser/codelens.ts#427:8 (_onViewportChanged) 
/vs/base/common/async.ts#566:8 (runner) 
```
