### ISSUE TITLE
Unable to include specific file after excluding its file format in workspace settings

### ISSUE THREAD

**Issue by iAvinashVarma** [Microsoft/vscode#46493]
In my case, I would like to exclude all *.js files in my workspace, but include a specific file protractor.report.js. Tried with below workspace settings but it's not working.

![includespecificfilevscode](https://user-images.githubusercontent.com/10095031/37876054-0a0ff2ce-3065-11e8-8fbd-8b4122d684b8.gif)

It seems that this feature is not available in the VSCode, it would be great if this feature is enabled.

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/869

**Comment by iAvinashVarma** [comment]
I am sorry for the duplicate, #869 helped me.

Below setting worked in my scenario.

`"**/*.js": {
            "when": "$(basename).ts"
        }`
