### ISSUE TITLE
code serach not working for large directory , not able to index files on fresh open.

### ISSUE THREAD

**Issue by cs-akash** [Microsoft/vscode#46494]
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: mac os 10.13.3

Steps to Reproduce:

1.open any directory in visual code, which has not been before opened in visual code.
2.try to do any code search in the fresh directory, it does not show any results nor any errors.
I tried with a directory for more than 3,000 items. 

Does this issue occur when all extensions are disabled?: Yes/No
No
<img width="298" alt="screen shot 2018-03-25 at 19 42 16" src="https://user-images.githubusercontent.com/36440805/37876103-94d0508e-3065-11e8-97d0-e9968bf7e70c.png">

**Comment by cs-akash** [comment]
found the issue 
<img width="421" alt="screen shot 2018-03-25 at 19 54 22" src="https://user-images.githubusercontent.com/36440805/37876182-81e054c8-3066-11e8-94cf-b3369864eb8e.png">
if exclude file filter is selected and not given any inputs the it ignors all file.
if unslected works fine .
docs should mention this part.

**Comment by roblourens** [comment]
It should not ignore all files. It should be skipping files covered by the files.exclude/search.exclude settings, or a .gitignore file. Are either of those present?

**Comment by cs-akash** [comment]
my setting config for search is 
"search.exclude": {
    `"**/node_modules":` true,
    `"**/bower_components":` true
  },
but it still search in bower_components
<img width="520" alt="screen shot 2018-03-26 at 10 26 28" src="https://user-images.githubusercontent.com/36440805/37887689-cf72b9f4-30e0-11e8-9b96-1c690711373d.png">

**Comment by roblourens** [comment]
In that screenshot the toggle button is toggled off, so it ignores the search.exclude setting. It only uses that setting when the button is toggled on.

**Comment by cs-akash** [comment]
you are right just verified search.exclude setting are active only when the button is toggled on. but the other issue is still there, you can see for this case it does not show any search result if exclude search button is on and not given any input in exclude file field.
![image](https://user-images.githubusercontent.com/36440805/37890887-cc3f0f8a-30ef-11e8-8605-f65c3f4302ef.png)

**Comment by roblourens** [comment]
The missing files that you are expecting to see results in - are you sure they aren't covered by the search.exclude setting or a gitignore file?

**Comment by cs-akash** [comment]
they are not covered in search.exclude setting . heres my .gitignore file content
````
.DS_Store`
/ngdocs
/node_modules/*
/public/bower_components/*
/dist/
npm-debug.log
```

**Comment by cs-akash** [comment]
you can close the issue as it, not that high severity.

**Comment by roblourens** [comment]
If you are not getting some search results that you expect to get, then I want to figure out whether there's a bug :)

Your screenshot shows that the search is only looking in the `./public` subfolder. Where are the files that you are missing results from?

**Comment by cs-akash** [comment]
in `./public` folders only, outside public are all conf files and dist folders etc.

**Comment by roblourens** [comment]
Can you search anywhere else in this project? Are you missing lots of files or just a few particular ones in public?
