### ISSUE TITLE
Quickopen: can't filter files by their root folder name in a multi-root workspace

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#46492]
My use case:

- I have 4 folders under the same workspace: `foo`, `bar`, `baz` and `qux`
- I want to open `foo/package.json` via the quickopen
- I can't find it with `foopackage`

I think the name of the root folder is not included in the filterable part of file path.

This forces me to type `package` into the quickopen, but if all other roots have a `package.json` file in them I now have to find the one I'm looking for manually. This is definitely not "quick".

**Comment by fabiospampinato** [comment]
This issue is similarly worded to the one found by the bot, but they are actually about 2 different things.

**Comment by roblourens** [comment]
Have you opened a workspace with 4 folders added, including foo? If so, it's the same as #32444.

Or, did you open a single folder with 4 subfolders? In that case, that should work.

**Comment by fabiospampinato** [comment]
> Have you opened a workspace with 4 folders added, including foo?

Yes.

> If so, it's the same as #32444.

Is it? You mentioned `'f1/foo.txt' is some file in 'foo'` so I thought you meant you can't file files with the same name of a root folder, my issue is that if all my root folders have a `package.json` file, or something, in their root, there's no way to uniquely filter the one I'm actually looking for it in the quickopen.

**Comment by roblourens** [comment]
That sentence is an example of what does work - searching folder names that are subfolders of a root folder. I guess I confused the scenario by introducing a second thing called 'foo', I'll change the example
