### ISSUE TITLE
Cannot override Win+ hotkeys in Win10

### ISSUE THREAD

**Issue by tsaiid** [Microsoft/vscode#46499]
- VSCode Version: Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Win10 Pro (1709) (16299.309)

Steps to Reproduce:

1. Edit `keybindings.json`
2. Set a win+ hotkey, ex:

```
[
    {
        "key": "win+a",
        "command": "editor.action.selectAll"
    },
    {
        "key": "ctrl+a",
        "command": "cursorHome",
        "when": "editorTextFocus"
    }
]
```

3. Win+ hotkey always trigger the global windows hotkey rather than the custom setting. And the other keybindings work well. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@tsaiid Have you been able to override `win+a` using other software? (perhaps it is something that cannot be overriden?)

**Comment by tsaiid** [comment]
Yes. Currently, I use an AutoHotKey script to do this. 

```ahk
#a::
    Send ^a
Return
```

It can capture the Win+a and then send Ctrl+a to do selectAll.

**Comment by alexandrudima** [comment]
Well, AutoHotKey is a very special piece of software that registers global keypress handlers. What I mean is, I believe regular software that does not use global keypress handlers cannot override `win+a`. 

In VSCode, we are not registering global keypress handlers, we are just dispatching the keypresses that reach us. If the OS eats that up, that is outside of our control. Also, we do not want to register global keypress handlers, as that would interact poorly with other software like e.g. screen readers.
