### ISSUE TITLE
VSCode button styles are inconsistent in some places

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#46490]
- VSCode Version: 1.21.1
- OS Version: Win10Pro

A. The feedback button has a 4px wide border, and the space around button's icon is not balanced at all. The font size of the button is `12.1px` (🤔)
![image](https://user-images.githubusercontent.com/760112/37874617-f717d142-304f-11e8-9aed-eb7a4684a961.png)

B. Whereas the "Report an Issue" window has wildly different styles for the button:
1. Padding is much lesser than Tweet button.
2. Font size is 16px.
3. Space is balanced, but no icon is there.
4. Border radius is `0.25rem` (which evaluates to 4px, but why in `rem` here, or vice-versa?)
![image](https://user-images.githubusercontent.com/760112/37874654-a8e3bada-3050-11e8-9dea-0e50fe09e11c.png)

Plus, the inputs in the issue reporter form (at least) is very different from the rest of the vscode UI - round borders and bigger font-sizes all around.

**Comment by kumarharsh** [comment]
ok. on it.

**Comment by kumarharsh** [comment]
It seems like the `<Button>` element doesn't have a way to access the Builder object. From what I've seen in the code, the Builder is a much more powerful and easy-to-use wrapper over the HTMLElement. It might be quite useful in this case to expose the underlying Builder object from the Button (Button.$el). Just a thought...

I've made the PR.

**Comment by RMacfarlane** [comment]
@bpasero no, the issue reporter isn't using the `Button` widget either

**Comment by bpasero** [comment]
@RMacfarlane moving the reminder to you then
