### ISSUE TITLE
workspace.findFiles doesn't work with absolute globs

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#46498]
Let's say I have two roots in my workspace, `foo` and `bar`, and I want to find all files under `foo/src`, If I call `workspace.findFiles` with a relative glob like `src/**/*` all files under `foo/src` and `bar/src` are returned, and if I use an absolute glob like `/absolute/path/to/foo/src/**/*` nothing gets returned.

Why is there this limitation?

**Comment by bpasero** [comment]
@fabiospampinato see https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#new-helpful-api around `RelativePattern` to limit a search to a specific `WorkspaceFolder`.
