### ISSUE TITLE
Markdown image doesn't show correctly

### ISSUE THREAD

**Issue by moyamoyarua** [Microsoft/vscode#46497]
- VSCode Version: `1.21.1`
- OS Version: `Windows 10 1709`

Steps to Reproduce:

1. file tree
    ![](https://i.imgur.com/0MwXfM9.png)
2. img.md
    ![](https://i.imgur.com/6YICrtm.png)
3. Preview
    ![](https://i.imgur.com/eb6vh5S.png)

Does this issue occur when all extensions are disabled?: `Yes`

**Comment by mjbvz** [comment]
Duplicate of #46448
