### ISSUE TITLE
Integrated Terminal scrolls to top after file save

### ISSUE THREAD

**Issue by wilsonpage** [Microsoft/vscode#46491]
- VSCode Version: 1.21.1 (1.21.1)
- OS Version: OSX 10.13.3

Steps to Reproduce:

1. Open terminal
2. Make sure terminal has some scroll back history
3. Toggle close terminal
4. Save a file
5. Toggle open terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@wilsonpage can you see if this reproduces on Insiders? I believe it's fixed already https://code.visualstudio.com/insiders/
