### ISSUE TITLE
Split editor vertically and to more rows / columns

### ISSUE THREAD

**Issue by javagg** [Microsoft/vscode#465]
Complex layout is more powerful when displaying non-editor panels in workspace. the workspace in Atom can be split vertically and horizontally .

**Comment by bpasero** [comment]
Currently not supported. We might allow to horizontaly lay out the output window and debug repl in the near future though.

**Comment by egamma** [comment]
Reopening - this is a valid feature request

**Comment by jamlen** [comment]
:+1:

**Comment by halfabench** [comment]
:+1:  (just like good old vim?)

**Comment by parliament718** [comment]
+1 please allow splitting into rows

**Comment by vlad-saling** [comment]
That would be helpful indeed!

**Comment by nfloersch** [comment]
Related to #1749

**Comment by bpasero** [comment]
Looks like #1749 has a bit more discussion.
