### ISSUE TITLE
[feature request] one-to-many relationship between debugger and process

### ISSUE THREAD

**Issue by davydden** [Microsoft/vscode#46500]
according to [this comment](https://github.com/Microsoft/vscode-cpptools/issues/1723#issuecomment-375488151), currently debug adapter can be attached to one process only. This excludes possibility to debug distributed memory parallel programs (i.e. build with `MPI`). 

It would be great if the generic debug UI in VS Code support this. Then one could further develop adapters to cover this use case.

p.s. This is relevant to C/C++/Format, perhaps other languages.

**Comment by weinand** [comment]
The VS Code debugger support supports multiple processes. See https://code.visualstudio.com/updates/v1_20#_node-debugging.
The animated gif shows VS Code debugging a master process and 5 child processes.

**Comment by davydden** [comment]
@weinand thanks for the prompt reply!

**Comment by davydden** [comment]
@weinand on the second look, this might not be exactly the needed feature, although very close! 

In the link above it's mentioned: 

> ...mechanism that tracks all subprocesses of a debuggee and tries to automatically attach to those processes that are launched in debug mode.

In this case, however, as far as I understand MPI, there is no single process which spawns child subprocesses. To given an exmaple, if one to debug such applications manually, you would typically attach a debugger to each process via

```
mpirun -np 2 xterm -e lldb -f my_executable
```

I must admit I have no idea about internal implementation of the only free parallel debugger [Eclipse PTP](https://www.eclipse.org/ptp/), it very well might be that they do some extra tricks to make each of those processes child of the single one, which would make VS Code, at least in theory, already suitable for such tasks.

**Comment by weinand** [comment]
Running multiple debug sessions concurrently by attaching to multiple process manually is always possible.

Every session (or every process) shows up automatically in the CALLSTACK view. This view gets additional thread- or process-levels on the fly (and only if there is more than one thread or process).

**Comment by weinand** [comment]
There is no requirement for "as if they are spawned by a single process".
All debug sessions are independent and they can either be launched manually or there could be some code (as a separate extension or as part of an existing debugger), that finds the relevant processes and launches debug sessions for them.

**Comment by davydden** [comment]
>  there could be some code (as a separate extension or as a part of an existing debugger), that finds the relevant processes and launches debug sessions for them.

great! 

I suppose one will also be able to switch between each debug sessions in the same way as depicted on that gif:

![screen shot 2018-03-26 at 14 49 16](https://user-images.githubusercontent.com/8023934/37907361-1d9222b8-3105-11e8-8ad4-61672da5cd12.png)

**Comment by weinand** [comment]
Yes, that's the standard VS Code UI and behaviour. You can try this already yourself by starting a second debug session.
