### ISSUE TITLE
Feature request: Add support for line and column numbers in the Go To File feature

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#4650]
A lot of times I use the Go to File feature I'm copy pasting the file from another source (for example errors from TSLint or TypeScript) which in my case are of the format:
src\test\folder\other_folder\my_file.ts(9,9)

If I could paste that directly into the Go to File field, and I'd take me first to the file and then to the line (and maybe slightly highlight the line or something so I focus on that line directly) it'd be very useful.

Given that the way to specify line and column is probably dependent on the source, you'd probably need to either have some smart logic, or provide some setting in the user settings where I can define a regexp to match my case like:
[ { pattern: "\((\d+),(\d+)\)$", lineAppearsFirst: true }]

**Comment by bpasero** [comment]
This is some nice coincidence, I noticed this today as well and fixed for post-GA release: https://github.com/Microsoft/vscode/issues/4643

**Comment by digeff** [comment]
@bpasero: Great minds think alike :+1:

**Comment by aeschli** [comment]
@bpasero Test plan tem?

**Comment by bpasero** [comment]
@aeschli assigned to Isidor as bug, don't think it needs a full test plan item.

**Comment by aeschli** [comment]
@bpasero  ok
