### ISSUE TITLE
code abre el navegador al iniciar

### ISSUE THREAD

**Issue by Jonathandelacruzp** [Microsoft/vscode#46502]
Issue Type: <b>Bug</b>

code abre el navegador al iniciar con la pagina de descarga de visual code , es molesto cuando abro el visual y el browser se pone en brente incluso cuando abro nueva ventana.

arreglen o den la cofiguracion para detener este incidente.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|15.93GB (11.98GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.14.0
html-css-class-completion|Zig|1.17.1

</details>
Reproduces without extensions

**Comment by dbaeumer** [comment]
@Jonathandelacruzp can you please provide the description in English.

**Comment by Jonathandelacruzp** [comment]
Visual Code opens the browser when starting with the visual code download page as a popup, It is annoying when I open the visual and the browser gets in front even when I open a new window.

some solution to avoid the start pop-up window.
Thanks.

**Comment by dbaeumer** [comment]
@chrmarti not sure if this is you. Starting because of Welcome page.

**Comment by chrmarti** [comment]
The website should only open on the very first startup right after install.

@Jonathandelacruzp What files and with which "Date modified" do you have in `C:\Users\YOUR_USER\AppData\Roaming\Code\Local Storage`?

/cc @bpasero @Tyriar for ideas (we have a similar report in #46111)

**Comment by bpasero** [comment]
@Jonathandelacruzp does this happen all the time or just once?
