### ISSUE TITLE
Consider maintaining own Razor syntax files as opposed to file from demyte/language-cshtml

### ISSUE THREAD

**Issue by austincummings** [Microsoft/vscode#46510]
Razor colorization support in VS Code is very poor, so I've rewritten the `cshtml.tmLanguage.json` file from scratch to fix many of the issues around syntax colorization. Now I'm not sure how to get the changes into VS Code proper for others to benefit from.

The syntax file for Razor is updated from [demyte/language-cshtml](https://github.com/demyte/language-cshtml). However it seems that repo isn't very active and so updates to VS Code's Razor support are blocked by a third-party. In order to get my changes into VS Code I need to go through this repo first and while I'm attempting to do that, I think it would be good to allow updates to this syntax file directly via a pull request to VS Code itself.

**Comment by aeschli** [comment]
I'm happy to use your repo as input instead of demyte/language-cshtml. if you are willing to maintain the grammar for a while. This means getting all issue requests assigned to that repo.
You can still make a pull requests to demyte/language-cshtml and hope they merge again.

**Comment by austincummings** [comment]
I'd be willing to maintain the grammar. I'd first like to see if demyte/language-cshtml will accept the pull request I've made. If it isn't merged by this Friday (2018-03-30) I'll set up a repo with the grammar and ping you so you can do what it is you have to do.

Thank you!

**Comment by aeschli** [comment]
@austincummings Thanks a lot for your efforts!

**Comment by aeschli** [comment]
Closing. Please ping me if you have a new repo
