### ISSUE TITLE
Adding files to project do not cause workbench to refresh

### ISSUE THREAD

**Issue by z2x** [Microsoft/vscode#46517]
Issue Type: <b>Bug</b>

手动往项目文件夹中添加文件，vs code工作区不能实时刷新

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.27
react-native-react-redux|EQu|1.7.3
beautify|Hoo|1.3.0
html-snippets|abu|0.2.1
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.7
jquerysnippets|don|0.0.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
live-html-previewer|hdg|0.3.0
vscode-filesize|mkx|2.0.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.22.0
sass-indented|rob|1.4.8
markdown-preview-enhanced|shd|0.3.4
easysass|spo|0.0.6
guides|spy|0.9.1
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|2.0.0
markdown-pdf|yza|0.1.8

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by dbaeumer** [comment]
Can someone please help translating this? (@octref @rebornix)

**Comment by octref** [comment]
@dbaeumer He's saying adding files to project do not cause workbench to refresh (I'm guessing he's referring to the file explorer).

@z2x Please use English to file issues. Can you post a screenshot or gif (using https://www.cockos.com/licecap/) to illustrate your problem?

**Comment by dbaeumer** [comment]
@bpasero assigning to you assuming he is referring to the file explorer.

**Comment by bpasero** [comment]
@z2x 
VS Code is using different file watching strategies depending on your OS and your setup. 

First thing to check:
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)

To find out more about this issue, please first answer this:
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?

Then please answer the following depending on your setup:
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

Thanks for taking the time to fill out this questionnaire.
