### ISSUE TITLE
Emmet bem filter problem when child uses multiple classes

### ISSUE THREAD

**Issue by roamn** [Microsoft/vscode#46511]
- VSCode Version: 1.21.1
- OS Version: Windows 10/64

Steps to Reproduce:

Abbreviation to expand included modificator name
`.l-layout>.-container.container>.-row.row>.-col_some_modif_name.col-xs-12`

**Result in VSC**

![2018-03-26_01-49-43](https://user-images.githubusercontent.com/5599071/37880930-bcb1cdca-3098-11e8-980d-a8571e62613e.png)

Expected result

**Result in Sublime Text**

![2018-03-26_01-50-42](https://user-images.githubusercontent.com/5599071/37880941-e34f94ee-3098-11e8-8519-e04800075478.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Thanks for reporting @roamn 
I have logged an upstream issue for the same. https://github.com/emmetio/html-transform/issues/12

**Comment by ramya-rao-a** [comment]
I have submitted a PR upstream to fix this, but it is unlikely that it will make it in time for the March release though. Pushing this bug to the next milestone

**Comment by ramya-rao-a** [comment]
There are 2 issues here.

- The child of `<div class="l-layout">` should have the class `l-layout__container container` and not `container__container container`. Upstream Issue: https://github.com/emmetio/html-transform/issues/12
- The inner most element should have the class `l-layout__col l-layout__col_some_modif_name col-xs-12` and not `col-xs-12__col col-xs-12__col_some col-xs-12__col_modif col-xs-12__col_name col-xs-12`. Upstream Issue: https://github.com/emmetio/html-transform/issues/14

**Comment by roamn** [comment]
Thanks.

**Comment by ramya-rao-a** [comment]
The fix for this will be available in tomorrow's [Insiders](https://code.visualstudio.com/insiders)

**Comment by mjbvz** [comment]
@ramya-rao-a Here's the result I see in the current insiders:

```html
 <div class="l-layout">
         <div class="-container container">
             <div class="-row row">
                 <div class="-col_some_modif_name col-xs-12"></div>
             </div>
         </div>
```

Which doesn't match the sublime example

**Comment by ramya-rao-a** [comment]
@mjbvz You need to either add `|bem` in the end or add the below setting
```
"emmet.syntaxProfiles": {
        "html": {
            "filters": "bem"
        }
    }
```
