### ISSUE TITLE
界面又卡住了 

### ISSUE THREAD

**Issue by SmileXia123456** [Microsoft/vscode#46515]
Issue Type: <b>Bug</b>

界面再次卡住了，这已经是第5次了，我不知道是不是因为插件的原因。

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.91GB (3.69GB free)|
|Process Argv|D:\SoftWare\Develop Tools\Microsoft VS Code\Code.exe D:\SoftWare\AppServ\www\thinkphp5.0|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
php-intellisense|fel|2.3.0
vscode-javac|geo|0.0.47
mdmath|goe|2.2.1
crane|Hvy|0.3.8
evermonkey|mic|2.4.5
python|ms-|2018.2.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
markdown-pdf|yza|0.1.8
markdown-all-in-one|yzh|1.1.1

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by Sneezry** [comment]
可以试着禁用扩展，看看问题是否依然存在。

You may try to disable all extensions to see if issue remains.

**Comment by dbaeumer** [comment]
@SmileXia123456 can you please provide the description in English.

Automatic translation:
