### ISSUE TITLE
Every new window I open shows an extension's install page

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46513]
There's a bug, where after I install a VS Code extension, then I open a new window in VSC with File > New Window, I'll see an extension's install page.

To reproduce: I open the page of an extension in the VS Code Marketplace in Chrome (it was [ES Lint at the time](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)), I click Install, it opens up the page in VSC. I click Install on the extension, then Reload, then I close the extension page. Since then, whenever I open a new window, the extension page appears. This stops when I restart VSC.

**Comment by sandy081** [comment]
@joaomoreno Is it could be due to the opening vscode from market place functionality?
