### ISSUE TITLE
Search: badges are no longer aligned

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46519]
Seeing this today:

![image](https://user-images.githubusercontent.com/900690/37888762-537cfe84-30c9-11e8-99ea-800a7ff0cea2.png)

**Comment by roblourens** [comment]
This was by design. Looks much better in a very wide search view. But maybe they should remain right-justified in a narrower search view?

**Comment by bpasero** [comment]
@roblourens if this is about optimizing for the wide search view then please only do it there. In general I do not think that this is a good idea.
