### ISSUE TITLE
The console background color is blue

### ISSUE THREAD

**Issue by Sunday96** [Microsoft/vscode#46514]
Issue Type: <b>Bug</b>

I open the console and run npm run dev, the console background color will change, I do not want any change in the background color

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|Memory (System)|7.87GB (2.68GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-caniuse|aga|0.5.0
Bookmarks|ale|0.18.2
project-manager|ale|0.25.0
html-class-suggestions|And|1.0.7
path-intellisense|chr|1.4.2
cssrem|cip|0.0.3
vscode-markdownlint|Dav|0.14.1
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.30
vsc-material-theme|Equ|1.5.1
php-intellisense|fel|2.3.0
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
easy-icons|jam|0.3.1
docthis|joe|0.6.0
node-module-intellisense|lei|1.5.0
vscode-ariatemplates-highlighter|max|0.2.2
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
vscode-filesize|mkx|2.0.0
easy-less|mrc|1.4.5
vscode-autoprefixer|mrm|2.1.2
vetur|oct|0.11.7
vuehelper|oys|0.1.0
vue-beautify|pea|2.0.4
material-icon-theme|PKi|3.2.6
vscode-css-peek|pra|2.1.0
vscode-icons|rob|7.22.0
code-settings-sync|Sha|2.9.0
markdown-preview-enhanced|shd|0.3.4
php-formatter|Sop|0.2.4
open-in-browser|tec|1.1.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.17.1

(11 theme extensions excluded)

</details>
Reproduces only with extensions

![tim 20180326130510](https://user-images.githubusercontent.com/20500528/37887795-5c6c463a-30f6-11e8-93e2-071eb65f6405.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/40327
