### ISSUE TITLE
Not responding after every switch to app

### ISSUE THREAD

**Issue by ivankadukrs** [Microsoft/vscode#46524]
Issue Type: <b>Bug</b>

After every switch to the editor it not allow to edit anything. Then after some time it starts to work fine. It's hard to work in that way.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.17025

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|Memory (System)|15.89GB (4.45GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by bpasero** [comment]
@ivankadukrs does it reproduce if you run with "`code --disable-gpu`" from the command line?

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/28709

**Comment by ivankadukrs** [comment]
@bpasero Sorry for long reply. Your advice works better. Thank you!
