### ISSUE TITLE
GIT problem

### ISSUE THREAD

**Issue by ronymuliana** [Microsoft/vscode#46523]
Issue Type: <b>Bug</b>

Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.16.2.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2389)|
|Memory (System)|3.74GB (1.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
missinglineendoffile|ric|0.3.1
LiveServer|rit|3.2.1
code-settings-sync|Sha|2.9.0
lorem-ipsum|Tyr|1.2.0

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
