### ISSUE TITLE
C/CPP - Settings only apply to first folder in workspace

### ISSUE THREAD

**Issue by jsgoller1** [Microsoft/vscode#46522]
Issue Type: <b>Bug</b>

I have two different codebases with C code, call them `A` and `B`. Both of them have the following in `settings.json`:
```
{
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "C_Cpp.clang_format_fallbackStyle": "Google",
    "C_Cpp.clang_format_path": "/usr/local/bin/clang-format",
    "files.insertFinalNewline": true
}
```

For some reason, when I add both to a workspace, only the first folder has the settings applied to it - if I open A first, then add B to the workspace, and then save `A/src/main.c`, it will be formatted correctly with `clang-format`, but when I save `B/src/main.c`, no formatting occurs. Oppositely, if I start by opening B and then adding A to the workspace, `B/src/main.c` formats correctly on save but not `A/src/main.c` . This occurs even when I add the above settings to my workspace setting, or remove the individual project settings and have only workspace settings. Even stranger, if I start with just workspace settings, observe the above behavior, and remove the workspace settings, then no formatting occurs (which is expected), but if then _add_ the workspace level settings again, the above behavior occurs again.

EDIT: In the above, if I open just A or B as a single folder with the above settings in `settings.json`, formatting occurs correctly. There is some issue here with adding them to a common workspace.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3397)|
|Load (avg)|1, 1, 1|
|Memory (System)|31.33GB (25.65GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
