### ISSUE TITLE
Need Better Support For Ruby & Rails

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#46521]
It's better to have a support for Ruby and Rails. Hard to find a better Extensions.

**Comment by chrisdias** [comment]
there are a quite a few [ruby extensions in the marketplace](https://marketplace.visualstudio.com/search?term=ruby&target=VSCode&category=All%20categories&sortBy=Relevance).  if there are issues, please do submit an issue with the extension you are using.
