### ISSUE TITLE
editorActionInvoked telemetry event is reporting localized name instead of id 

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vscode#4652]
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/commonCodeEditor.ts#L556

We need to be reporting the action id, since the label is localized.

**Comment by SofianHn** [comment]
@egamma @seanmcbreen, I think we might need this to be picked into the GA release

**Comment by bpasero** [comment]
LGTM, pushed to release/1.0.0.
