### ISSUE TITLE
EMMET功能很难用

### ISSUE THREAD

**Issue by jws2003** [Microsoft/vscode#46520]
Issue Type: <b>Feature Request</b>

EMMET功能很难用啊，如果纯输入是没问题的（比如div.box），如果复制粘贴的样式名(div.粘贴文字)，使用快捷键是没反应的。这个BUG很严重哦，请尽快解决，或者有其他方法可以弄的。谢谢！

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

**Comment by xuejianxianzun** [comment]
我没有遇到这个问题，你可以先禁用其他插件，排除下是不是插件的问题

**Comment by jws2003** [comment]
我下载下来，没装任何插件的，全部是默认的设置和插件。

**Comment by xuejianxianzun** [comment]
你在正常情况下可以展开缩写是用的tab键吗？

**Comment by jws2003** [comment]
是的。

**Comment by xuejianxianzun** [comment]
你在首选项里加一条设置试试：
`"emmet.triggerExpansionOnTab": true`

**Comment by jws2003** [comment]
谢谢，貌似可以了。

**Comment by shizengzhou** [comment]
@jws2003 你的问题解决了，就可以关闭这个issue了。
