### ISSUE TITLE
Text wrapped in left terminal if using multi-terminal feature

### ISSUE THREAD

**Issue by reflash** [Microsoft/vscode#46525]
Issue Type: <b>Bug</b>

1. Open terminal window
2. Create second terminal
3. Click Move to Right
4. Click Move to Bottom

In the result - left panel will contain wrapped text

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

Reproduces only with extensions

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26375
