### ISSUE TITLE
When I add a folder to the workspace, it crashes

### ISSUE THREAD

**Issue by panglongqi** [Microsoft/vscode#46532]
Issue Type: <b>Bug</b>

explorer->workspace->folder。 When I add a folder to the workspace, it crashes。The name of the folder is Chinese, The files in the folder are also Chinese

在资源管理器的工作区中添加文件夹会崩溃，路径和文件名都是中文。

![timline 20180326163757](https://user-images.githubusercontent.com/5959230/37896003-662760aa-3115-11e8-9335-07b93eca552d.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|7.54GB (2.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.0
python|ms-|2018.2.1

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by panglongqi** [comment]
I reproduced it with nightly insider builds！

![_20180327175323](https://user-images.githubusercontent.com/5959230/37960462-499d3800-31e8-11e8-8866-933ff39da438.png)

**Comment by bpasero** [comment]
@panglongqi can you share the exact absolute path that you are trying to add?

**Comment by panglongqi** [comment]
@bpasero 

E:\正式工作\庞龙起\开放数据平台\销售管理-国际供应链

![1](https://user-images.githubusercontent.com/5959230/37961625-6c455c7c-31eb-11e8-91c2-051a0678b551.png)

**Comment by bpasero** [comment]
@panglongqi weird I cannot reproduce on my Windows 7 nor Windows 10. Does this happen for all folders or just this one?

Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by panglongqi** [comment]
@bpasero all folders。

[Code - Insiders__PID__3856__Date__03_28_2018__Time_09_47_25AM__915__Log.txt](https://github.com/Microsoft/vscode/files/1854316/Code.-.Insiders__PID__3856__Date__03_28_2018__Time_09_47_25AM__915__Log.txt)

**Comment by bpasero** [comment]
@panglongqi even a folder that has no chinese letters in it but just ASCII?

**Comment by panglongqi** [comment]
@bpasero When an **.xls** file and a **.xlsx** file are in the same path, it crashed。no matter the folder  is Chinese letters or ASCII。

![3](https://user-images.githubusercontent.com/5959230/38014048-d09a138a-3299-11e8-9ad7-9f9df87d0f9c.png)

**Comment by bpasero** [comment]
@panglongqi even if that file is empty? This sounds a lot like this other issue we had where I never got an answer: https://github.com/Microsoft/vscode/issues/29813 and https://github.com/Microsoft/vscode/issues/40930

**Comment by panglongqi** [comment]
@bpasero no matter the file is empty or not , it crashed. Try it yourself.

**Comment by bpasero** [comment]
@panglongqi I do on Windows 7 and cannot reproduce. The 2 linked issues were also not very helpful. I have no idea what this is. 

Does it reproduce from this version of VS Code that is using a much newer UI framework version: https://az764295.vo.msecnd.net/exploration/c52be1294047741be296c2ced817b8246ab9942f/VSCode-win32-x64-1.22.0-exploration.zip

**Comment by panglongqi** [comment]
@bpasero  VSCode-exploration still crashes。

The 2 linked issues use Windows7 Chinese version,i use Windows7 Chinese version too.  I guess it is caused by character encoding。do you have a PC with Windows7 chinese-simplified? 

I will try to reproduce this problem in the English version of the operating system at night . I will tell you the result tomorrow，Whether or not I reproduce this problem

**Comment by bpasero** [comment]
@panglongqi that would be great thanks

**Comment by panglongqi** [comment]
@bpasero I didn't reproduce the problem with another computer last night。o(╥﹏╥)o

**Comment by bpasero** [comment]
So it seems to be only happening in Chinese locale, weird :-/
