### ISSUE TITLE
Test: CSS/LESS/SCSS language aware folding

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#46535]
Refs: 45899

- [x] any os @alexandrudima 
- [x] any os @ramya-rao-a 

Complexity: 1

Language aware folding has been added to css/scss/less. Try:
- Wrong indentation does not affect folding regions
- Comments show as folding regions
- Nested folding regions (postcss nesting, scss/less nesting, media query, keyframe query, etc)

**Comment by ramya-rao-a** [comment]
Tested out of source as the Insiders had this issue : https://github.com/Microsoft/vscode/issues/46640
