### ISSUE TITLE
Unable to stage separate lines in git

### ISSUE THREAD

**Issue by holms** [Microsoft/vscode#46545]
- VSCode Version:

```1.22.0-insider
a918e7b3ef2feaf2c9fbf003e936084eaaf53f76
x64
```

- OS Version:

```
holms@debian ~> uname -a
Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
holms@debian ~> cat /etc/debian_version 
9.4
```

Steps to Reproduce:

1. Edit multiple lines in some file which is in git repository
2. Go to diff view of that file
3. Select lines you want to stage
4. Right click -> Stage selected ranges
5. Git error pop's up: `Git: Illegal value for 'line'`

There's nothing in git log window.

![vscode-git-partial-bug](https://user-images.githubusercontent.com/280958/37904178-9b5c5ff8-3103-11e8-9e89-64b962f83a14.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ameerthehacker** [comment]
Hi @joaomoreno I would like to take up this issue can you suggest me the file in which I should start looking for fixing this issue

**Comment by shobhitchittora** [comment]
@joaomoreno Can't replicate the issue on OSX.

**Comment by holms** [comment]
I'm closing this, after I've updated code-insiders today it's not an issue anymore, but before that this was like for every file, and staging for lines wasn't working at all.
