### ISSUE TITLE
Test reference search result navigation

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46553]
Test for #44414
Complexity: 1

- [x] linux  @dbaeumer 
- [x] win  @isidorn 

You can navigate reference search result item via F4 and Shift+F4. Test that

* you can navigate results in both directions
* you can navigate results also when having find/search-viewlet results
* focus stays in the editor when coming from the editor and focus stays in the references-tree when coming from there

**Comment by dbaeumer** [comment]
Closing item.
