### ISSUE TITLE
Test selective diagnostics display

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46555]
Test for #44141
Complexity: 1

- [x] Any OS  @roblourens 
- [x] Any OS  @chrisdias 

Have an extension that adds diagnostics of all severities and test that

* errors/warnings are shown in the explorer
* errors/warnings/infos are shown in the problems panel and via F8
* errors/warnings/infos and hint are shown in the editor

**Comment by chrisdias** [comment]
LGTM, tested on MacOS
