### ISSUE TITLE
Consider removing type and label from IRawEnvAdapter

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46550]
Also check whether some debug extension is actually using the `type` and `label` as platform specific in their `package.json`.

If not we might want to consider to move "type" and "label" to "IRawAdapter" (where other non-platform specific attributes live).

**Comment by weinand** [comment]
The `IRawAdapter` got renamed to `IDebuggerContribution` and the code that deals with platform specific package.json attributes neither handles 'type' or 'label'.

**Comment by isidorn** [comment]
@weinand I have remove the type and label from the IPlatformSpecific interface. Note that I have added some return types to methods because I like to always explicitly write them even for void. And I prefer destructured imports so I also changed that a bit.
