### ISSUE TITLE
Extend Snippets to others

### ISSUE THREAD

**Issue by jrock2004** [Microsoft/vscode#46558]
Coming from Vim and it snippet managers, you can define to to `extend` other snippets. For example, in my `sass` snippet file, on the top, I can define `@extend css` and then when I am in my sass file I get all the snippets for css stuff as well. Thoughts on adding this feature?

**Comment by jrieken** [comment]
In vscode you would store your snippet in a `code-snippets`-file and define a scopes to target css and sass, see https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets
