### ISSUE TITLE
git commit fails when vscode is already open

### ISSUE THREAD

**Issue by jaromey** [Microsoft/vscode#4655]
- VSCode Version: 0.10.11
- OS Version: Windows 7

Steps to Reproduce:

1. Set vscode as your editor in git config.
2. Open vscode.
3. Using Git Bash, run git commit.
4. An error in Git Bash returns which states "Aborting commit due to empty commit message."
5. A new vscode Window opens with COMMIT_EDITMSG to enter the commit message.

When using Visual Studio Code, I use Git Bash to do all my git work including commits, though commits can be done using vscode itself but I think it is just a single line commit. The issue is that I can't commit from Git Bash (unless I use the -m option) while vscode is open.

**Comment by Tyriar** [comment]
Git integration is on its way and is available now in the insiders build which can be [downloaded here](code.visualstudio.com/Download). See https://github.com/Microsoft/vscode/issues/4006 for more information

**Comment by jaromey** [comment]
Thanks. I tried finding a related issue before opening this one but I missed that one I guess.

**Comment by Tyriar** [comment]
No problems, I do the same sometimes :smiley:
