### ISSUE TITLE
Intellisense stops working

### ISSUE THREAD

**Issue by innroot** [Microsoft/vscode#46557]
Issue Type: <b>Bug</b>

some times when you press Ctrl+Space intellisense stops working, it keeps loading...

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|8.1.1
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
php-debug|fel|1.12.2
flow-for-vscode|flo|0.8.0
code-runner|for|0.9.3
beautify|Hoo|1.3.0
crane|Hvy|0.3.8
mssql|ms-|1.3.0
python|ms-|2018.2.1
node-debug2|ms-|1.20.0
typescript-javascript-grammar|ms-|0.0.38
debugger-for-chrome|msj|4.2.2
java|red|0.21.0
vscode-icons|rob|7.22.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
vscode-react-native|vsm|0.6.6
html-css-class-completion|Zig|1.17.1

</details>

**Comment by isidorn** [comment]
Please follow these steps to file a proper issue
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
