### ISSUE TITLE
[json] Launch.json recommending properties before defining launch/attach

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4656]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open launch.json file
2. Add another debug configuration with name and type

Actual:
It is suggesting adding program and cwd properties before it knows what configuration you'll choose.
![launchjson](https://cloud.githubusercontent.com/assets/12900364/14029733/13876cb8-f1c1-11e5-9eb5-132ad7a5687a.jpg)

Expected:
Only suggests adding request property until you have defined request and does not show launch/attach specific properties.

**Comment by isidorn** [comment]
This is a feature request against our json schema which currently does not support his.
Forwarding to @aeschli

**Comment by aeschli** [comment]
This is pretty tricky to implement in the schema validator.

**Comment by aeschli** [comment]
closing as won't fix
