### ISSUE TITLE
Test: running DA in extension host

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#46566]
Test for #45129: 

**Please note**: since we do not ship this feature in March there is no need to have this tested by more than one dev.

- [ ] anyOS: @isidorn

Complexity: 3

Testing:
- Checkout the "cleanupDA" branch and build
- run VS Code from branch
- verify that debugging works correctly for both values of the user setting `debug.extensionHostDebugAdapter`.
- try this for the C++ or Python debug extension

**Comment by isidorn** [comment]
I have verified that debugging works for our vscode smoke test express and for a simple hello world python app. For both values of `debug.extensionHostDebugAdapter`
