### ISSUE TITLE
Test: proposed Task API

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#46569]
Tests https://github.com/Microsoft/vscode/issues/45980

Complexity: 3

- [x] anyOS: @egamma 
- [x] anyOS @sbatten 

Write and extension that makes use of the new Task API to query and execute tasks.

## Fetch all available tasks

```ts
workspace.fetchTasks(): Thenable<Task[]>
```

Ensure that this returns all tasks in the task system including contributed tasks (for example TypeScript auto detected build and watch tasks) and the once from the tasks.json

## Execute a task

```ts
workspace.executeTask(task: Task): Thenable<TaskExecution>
```

Ensure that you can execute a task that you queried using the above `fetchTasks` call. The returned `TaskExecution` allows you to terminate the task. Ensure that this works as well.

## Task start / end events

```ts
workspace.onDidStartTask: Event<TaskExecution>
workspace.onDidEndTask: Event<TaskExecution>
```

Ensure that these event fire for task executed through the task menu and using the new API. @

**Comment by egamma** [comment]
I´ve tested the API by implementing an explorer for npm scripts and the API covered this scenario well.

![image](https://user-images.githubusercontent.com/172399/38013757-8fe7676c-3266-11e8-81a8-efae00c67f49.png)
