### ISSUE TITLE
Command tracking should show glyphs next to rows and flash lines when navigating

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#46561]
Follow up for https://github.com/Microsoft/vscode/issues/45435

cmd+up/down on macOS should show some indication of the line that was scrolled to.

This will need some upstream changes.

**Comment by chrisdias** [comment]
if i have a few empty lines such as this:

![image](https://user-images.githubusercontent.com/1487073/37994068-3ca9e95e-31c5-11e8-91d4-4bdf56972266.png)

pressing `cmd+up` appears to do nothing

**Comment by Tyriar** [comment]
@chrisdias yeah I would have liked to get this in but was a bit randomized this iteration.

**Comment by Tyriar** [comment]
Blocked on https://github.com/xtermjs/xterm.js/issues/1852

**Comment by Tyriar** [comment]
Brought this to UX sync with a focus border outline that fades to 0 opacity over 2 seconds. But after it occurred to me that navigating the a symbol in the editor is the exact idea we're trying to get across which flashes a focus border briefly without animating. So going with that to align, we can change both if we want to tweak it:
![Recording 2022-03-16 at 10 31 04](https://user-images.githubusercontent.com/2193314/158651632-2cca068c-ae44-4b55-bf55-11d39ed0a973.gif)

**Comment by Tyriar** [comment]
Using 350ms:

https://github.com/microsoft/vscode/blob/12e6b0b3043f19d0cf1730eb3c213d3930310053/src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts#L214-L222
