### ISSUE TITLE
Open file as administrator, the vscode icon takes the full screen (Kubuntu)

### ISSUE THREAD

**Issue by alex-min** [microsoft/vscode#46560]
The icon is way to big on the open as administrator window so it takes a full screen making the prompt difficult to see. 
![screenshot_20180326_212749](https://user-images.githubusercontent.com/1898825/37912349-8e5a6eec-313c-11e8-91ed-42de26c4f4fb.png)

- VSCode Version: 1.21.1
- OS Version: Linux 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - Kubuntu 17.10

Steps to Reproduce:
1.  Open any file as administrator on KDE/Kubuntu.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Paviluf** [comment]
I have the same issue and since my screen is only 720p I can't even see the password field.

**Comment by Paviluf** [comment]
KDE developer Nate Graham told me that no software should use kdesudo. It's a legacy way to request elevated privileges. The correct way to do it is by using PolicyKit.

> There *might* be an issue with kdesudo, but no software should be using it in the first place, so it’s not worth filing a bug. The correct way to request elevated privileges is using PolicyKit, not via kdesudo, gksudo, or any other legacy methods that blindly execute code as root. This information should be communicated to the developers.

https://pointieststick.wordpress.com/2018/03/24/this-week-in-usability-productivity-part-11/comment-page-1/#comment-843

**Comment by justalemon** [comment]
Can repro:

![Repro](https://user-images.githubusercontent.com/11861253/38078790-c5dffa7a-3313-11e8-884b-a8cf7fb843e5.png)

VS Code version: Code - Insiders 1.22.0-insider (952b2a641da89a6c7bc28387474bc8afd47f0d2f, 2018-03-29T05:13:04.457Z)
OS version: Debian GNU/Linux 9.4 (stretch) x64 4.9.0-6-amd64

**Comment by Paviluf** [comment]
@bpasero should I open a new issue to make Vs Code use PolicyKit ?

**Comment by pdecat** [comment]
Had this on ubuntu where kdesudo was installed as a dependency to another package.

Uninstalling the kdesudo package resolved the issue as sudo-prompt [tries kdesudo first then falls back on pkexec](https://github.com/jorangreef/sudo-prompt/blob/ad291f7bd00bba09a01b7e4ce93dfa547f35f22d/index.js#L148).

Note: I'm on ubuntu, not kubuntu. Doing the same on kubuntu where it may be a vital component would probably have undesired side effects.

**Comment by bpasero** [comment]
We are using https://github.com/jorangreef/sudo-prompt for this feature, so I suggest to start the discussion over there.
