### ISSUE TITLE
Go to definition: add mainFields to go to es6 code

### ISSUE THREAD

**Issue by dmk255** [Microsoft/vscode#46563]
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: Sierra 10.12.6 (16G1114)

## Steps to Reproduce:

1. Add a package with both a `main` and `module` or `jsnext:main` field. (ex. ` yarn add react-table`)
1. Import the package in a js file. Command click an import. This will go to the import under the `main` field.

## Desired Behavior:
The ability to configure which fields to resolve to (e.g.[ webpack's mainFields implementation](https://webpack.js.org/configuration/resolve/#resolve-mainfields)).

## Desired configuration: 
```
{
    "compilerOptions": {
        "mainFields": ["module", "main"]
    }
}
```

## Reasoning:
1. If you are resolving `module` during webpack build, it would be helpful to jump to the code you are actually executing.
1. This will help support monorepos (e.g. lerna based)  so that you can jump to the source code definition rather than the compiled code. This will also help with peek / proptypes since they won't be compiled out.

I'm happy to provide more details!

**Comment by mjbvz** [comment]
Thanks!

Looks like this is already tracked upstream by https://github.com/Microsoft/TypeScript/issues/21423
