### ISSUE TITLE
Debugging: Program path issue, ignores __ in the path

### ISSUE THREAD

**Issue by sahas-** [Microsoft/vscode#4657]
- VSCode Version:0.10.11
- OS Version:Mac

Steps to Reproduce:

Here is my project folder structure

![screen shot 2016-03-24 at 3 09 56 pm](https://cloud.githubusercontent.com/assets/10361685/14029858/849f4e28-f1d2-11e5-900f-3f6dd7849903.png)

Below is my config in launch.son

		{
			"name": "Run mocha",
			"type": "node",
			"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha  --opts ${workspaceRoot}/__tests__/setup/mocha.opts",
			"stopOnEntry": false,
			"args": ["__tests__/specs/tests/google_search_test.js"],
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": null,
			"env": { "NODE_ENV": "production"}
		}   

When try to debug the test, getting this error.. looks like underscore before and after my folder gets lost (__tests__)

![screen shot 2016-03-24 at 3 03 21 pm](https://cloud.githubusercontent.com/assets/10361685/14029913/db2859ec-f1d2-11e5-8180-ff8e52bca940.png)

The same works fine, if i rename the folder to be test123 ..

**Comment by isidorn** [comment]
@weinand might you be massaging the paths in some special way? If not please give the bug back to me, though I do not think I am doing something special that would cause this

**Comment by weinand** [comment]
@sahas- the launch config attribute 'program' must be a path. Specifying additional arguments in 'program' does not work and results in the error message you are seeing.
Please add '--opts /Users/...' as two additional for the 'args' attribute.

**Comment by sahas-** [comment]
Thanks, that works.
