### ISSUE TITLE
Only show launch configurations for the "active workspace" not for all

### ISSUE THREAD

**Issue by ggb667** [Microsoft/vscode#46574]
The debug configurations set for a workspace should only show for the workspace of the currently open file.  If I have 23 repos, 23 x number of configurations in .vscode/launch.json of the same thing in the drop down is daunting to sort through.

In addition, debug breakpoints should only show for the workspace**s** of currently open files.  With 23 sets worth of debug breakpoints the ones I am working with are quickly lost.  Ideally the workspace would be a line seperating groups of active breakpoints instead of a mixed alphabetically sorted list.

Also, there does not seem to be a way to make .vscode pick up the multi-workspace-root launch configurations and use those for all open workspaces.  Thuis causing identical configurations to need to be duplicated and maintained in each workspace.

**Comment by isidorn** [comment]
Filtering down the list is a fair feature request thus I can keep this open.

As for .vscode picking up a launch configuration to use for all open workspaces please checkout the launch configurations in a workspace configuraiton file https://code.visualstudio.com/updates/v1_20#_improved-debugging-support-for-multi-root-workspaces
