### ISSUE TITLE
Expose electrons app.getPath() to extension API (or equivalent)

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#46573]
I am working on an extension, and am using `showOpenDialog` to display an open dialog to my users. I want to make this folder by default point to `~/Documents`. When I was writing in electron, I had access to `app.getPath('documents')`, however I don't see an equivalent API either in raw node, or the vscode extension API. Could a function like that be added to the vscode extension API?

**Comment by eamodio** [comment]
I'm not 100% this is what you are after but [`ExtensionContext`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameextensioncontextaspan-classcodeitem-id1180extensioncontextspan) in the vscode api, has properties and methods for dealing with paths. Specifically `asAbsolutePath(relativePath: string): string`

Hope that helps.

**Comment by ThadHouse** [comment]
That's not exactly. That won't help me get a system path, just get absolute if I already had a relative path (I don't have either )

**Comment by eamodio** [comment]
Ah, sorry about that -- should have looked into electron's `getPath` first.

**Comment by tetchel** [comment]
Hi ThadHouse,

Node's `os` module has [a function for getting the user's home directory](https://nodejs.org/api/os.html#os_os_homedir)

Does that solve your problem?
