### ISSUE TITLE
Smartselect grow and shrink fail for certain documents

### ISSUE THREAD

**Issue by leanderr** [Microsoft/vscode#46576]
Issue Type: <b>Bug</b>

Those two don't produce any result on a few of my longer Typescript files.
Tried resettings, rebooting... 

editor.action.smartSelect.grow
editor.action.smartSelect.shrink

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|7.87GB (3.21GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.1
ng-template|Ang|0.1.9
turbo-console-log|Cha|1.2.5
path-intellisense|chr|1.4.2
angular-productivity-pack|dev|1.7.1
vscode-generate-getter-setter|DSK|0.4.2
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
auto-rename-tag|for|0.0.15
angular2-switcher|inf|0.1.6
vscode-angular2-emmet|jak|2.0.3
Angular-BeastCode|Mik|5.2.23
angular2-inline|nat|0.0.17
vscode-html-scss|P-d|0.0.42
vscode-css-peek|pra|2.1.0
vscode-icons|rob|7.22.0
guides|spy|0.9.1
addDocComments|ste|0.0.8

(7 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by dbaeumer** [comment]
@leanderr can you please provide a TS file sample that show the problem with steps on how to best reproduce.

**Comment by leanderr** [comment]
It now works on the file. I dont know how and why and cannot reproduce. Sorry :-(

**Comment by dbaeumer** [comment]
Closing then.
