### ISSUE TITLE
Unable to stage file if path contains a space

### ISSUE THREAD

**Issue by urbantrout** [Microsoft/vscode#46579]
- VSCode Version: 1.21.1
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Open git project with a path that contains a space, e.g. `/Users/user1/Projects/My Project`
2. Add or modify file
3. Stage this file
4. VSCode show error message:
   ```git: fatal: /Users/user1/Projects/My Project/somefile.txt: '/Users/user1/Projects/My Project/somefile.txt' is outside repository```

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
I can't seem to reproduce. How are you staging the file?

**Comment by urbantrout** [comment]
My apologies. I accidentally used the wrong space when creating the "My Project" folder.
The problem was that I didn't just press the space bar but also the option key which inserts a non-breaking space. Staging files on command line works. But not in VSCode.

**Comment by joaomoreno** [comment]
Is it still desirable that we fix this for non-breaking spaces? Or let's close it?

**Comment by urbantrout** [comment]
I mean, I know that I can fix my problem by renaming the folder. So it is no issue for me any more.

Don't know how many people have clumsy fingers when typing in folder names...

**Comment by joaomoreno** [comment]
Closing it. 👍
