### ISSUE TITLE
Rendering errors while searching

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#46575]
Issue Type: <b>Bug</b>

Error reproduces while searching in a large text file. The error is not reliable and goes away after a few seconds even if I don't touch anything. I can only reproduce this in insiders.
If it helps, the file is https://github.com/Microsoft/TypeScript/blob/master/src/services/pathCompletions.ts .

![rendering](https://user-images.githubusercontent.com/19274678/37921827-b6e7fff8-30df-11e8-9338-d5a8b22ad64b.jpg)

VS Code version: Code - Insiders 1.22.0-insider (a918e7b3ef2feaf2c9fbf003e936084eaaf53f76, 2018-03-26T13:16:09.094Z)
OS version: Linux x64 4.4.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2619)|
|Load (avg)|0, 1, 1|
|Memory (System)|7.64GB (1.03GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders src|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by andy-ms** [comment]
Looks like those are only flagged as duplicates because I filled them out using the issue reporter, thus the exact same system info is included. The issue *bodies* are separate.

**Comment by alexandrudima** [comment]
@andy-ms Have you experienced this in the past too or is it a recent font rendering regression?

It might be caused by Electron 1.7.12 ... https://github.com/Microsoft/vscode/issues/35675#issuecomment-373614960

**Comment by bpasero** [comment]
@andy-ms do you see this also in our new builds that leverage Electron 2.0.x? [Download Link.](https://az764295.vo.msecnd.net/exploration/cf078a8a932cd399f9e475b5ad4226bbc93543ab/code-exploration-1.22.0-1522130024_amd64.tar.gz)

**Comment by andy-ms** [comment]
My computer broke yesterday after an update (unable to open applications, then after restarting, unable log in) and I had to reinstall Mint. Now I can't reproduce the error at all, so it was probably the OS's fault.
