### ISSUE TITLE
Terminal window does not resize with container

### ISSUE THREAD

**Issue by osstekz** [Microsoft/vscode#46577]
Issue Type: <b>Bug</b>

Generate output exceeding terminal view area.
Drag container panel top does not vertical-resize terminal window.

VS Code version: Code - Insiders 1.22.0-insider (a918e7b3ef2feaf2c9fbf003e936084eaaf53f76, 2018-03-26T13:16:09.094Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Dual  CPU  E2200  @ 2.20GHz (2 x 2200)|
|Load (avg)|0, 0, 0|
|Memory (System)|3.84GB (0.13GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders -n --inspect-extensions|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vala-code|oss|0.0.6
vala-debug|oss|0.21.3

</details>
Reproduces only with extensions

**Comment by jtsom** [comment]
FYI, This happens on all platforms - Mac OS, Windows, Linux
