### ISSUE TITLE
TypeScript: When you rename a file you get "Duplicate identifier" error and need to restart vs code to fix it

### ISSUE THREAD

**Issue by AltekkeE** [Microsoft/vscode#4658]
- VSCode Version: 0.10.11
- OS Version: OSX 10.11.3

Steps to Reproduce:

1. create file: MyClass.ts 
```class MyClass {
}```
![screen shot 2016-03-24 at 1 12 37 pm](https://cloud.githubusercontent.com/assets/11259864/14029965/6f9e29d2-f1c2-11e5-8ce0-e6cd3b85ddb4.png)

2. rename file to MyOtherClass.ts
![screen shot 2016-03-24 at 1 12 57 pm](https://cloud.githubusercontent.com/assets/11259864/14029966/6fcaf05c-f1c2-11e5-9930-4d3657c8e2d4.png)

3. MyClass is now underlined in Red
4. Error goes away if you restart vsCode

**Comment by Tyriar** [comment]
Does not repro in 0.10.12-alpha, looks like it's fixed.

**Comment by AltekkeE** [comment]
Looks like it came back in 0.10.13 ??

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7744

**Comment by dbaeumer** [comment]
We are closing the original file MyClass.ts and open the new file MyOtherClass.ts in terms what we send to the tsserver. Since the error is reported by the tsserver moving to TS project.
