### ISSUE TITLE
terminal console present some string from old command 

### ISSUE THREAD

**Issue by saarlevin** [Microsoft/vscode#46580]
Hi ,
when i running command with few lines of code , 
and i want to see command history (up boton) some string "stick" to the screen .

any option to fix this ?

thanks .

**Comment by Tyriar** [comment]
@saarlevin do you use zsh?

**Comment by saarlevin** [comment]
no , ps is terminal .

**Comment by Tyriar** [comment]
@saarlevin do you mean powershell or posh? Are you on Windows? Could you post a screenshot or better yet a gif/video demonstrating the issue?

**Comment by saarlevin** [comment]
sure , thanks .
https://ufile.io/cxaa6

**Comment by Tyriar** [comment]
I'm going to merge this one into https://github.com/Microsoft/vscode/issues/45693, thanks for the report
