### ISSUE TITLE
First character gets ignored when filling out completions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46586]
Refs: #45962

1. Glyph margin -> add conditional breakpoint
2. Start typing, notice that the inteli-sense is ignoring the first character

If I first do ctrl + space and then type, inteli-sense properly respects every character

@jrieken Might you have some hints as to what I am doing wrong?
code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/breakpointWidget.ts#L219

![bug](https://user-images.githubusercontent.com/1926584/37932072-d7c5611c-3147-11e8-9e11-25d6a541f77a.gif)

**Comment by jrieken** [comment]
Need to see this live

**Comment by isidorn** [comment]
@jrieken I am not in Zurich. Screen share after standup or when you have time?
