### ISSUE TITLE
Allow new WebView to be placed in its own sidebar activity

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#46585]
This request is similar to https://github.com/Microsoft/vscode/issues/43049 but I feel it is different enough to warrant this request.

To reiterate from https://github.com/Microsoft/vscode/issues/43049#issuecomment-372918050

While having webviews as editors is great, depending on the use-case, they can end up being the only mechanism for an extension to provide richer behaviors and interactions (think of chat integration) which can lead to a compromised experience. Because now the editor/tab needs to be managed, positioned, etc by the user.

I am currently bringing the https://codestream.com/ experience from Atom to vscode and really need to be able to provide the chat stream functionality seen here (on the right rail):

![image](https://user-images.githubusercontent.com/641685/37929872-12fdefa8-310f-11e8-9615-84a388e7c058.png)

With a webview hosted in its own sidebar activity, I should be able to provide a similar (much less compromised) experience. None of the other alternatives provide anywhere close to the desired experience.

While I can definitely appreciate (and largely agree) with vscode strict api and not wanting to allow the proliferation of webviews, I would argue that allowing a single webview in a sidebar activity shouldn't really change that vs an editor -- especially since only 1 activity can be visible at a time. But it makes a huge difference to the user experience. In the example above, if the webview must be in an editor tab, it now causes lots of edge case issues, requires user positioning, tab management, etc. All of which are much less than ideal for the user.

EDIT: In addition, I would equally love it if a webview could be hosted in a (bottom) panel too.

Thanks for the consideration.

//cc @jrieken @mjbvz @lostintangent

**Comment by GordonSmith** [comment]
For my use case I would like to host a WebView as a Bottom Panel.  Think of the scenario where a user is submitting SQL from the editor and wants to see the results (ideally in the bottom panel).

**Comment by pelmers** [comment]
@jrieken I noticed this is not scheduled in a milestone, are you willing to accept pull requests to resolve this issue? I would like to use this feature for an extension I am working on.

**Comment by jrieken** [comment]
> are you willing to accept pull requests to resolve this issue?

Sorry, this is rather large and touches too much code from various owners that a PR would be feasible.

**Comment by BinaryBen** [comment]
Is there any indication on if/when this will be possible? Extensions shouldn't use my editor space to display things that would make much more sense in a bottom panel/sidebar (I already have enough things open that I am actually trying to edit). I also would like to make a few extensions that would use this as well.

**Comment by usernamehw** [comment]
I regret so much subscribing to issues...

**Comment by BinaryBen** [comment]
Sorry for causing regret

**Comment by royaction123** [comment]
I released a color-picker/palette extension yesterday. This feature would be very welcome ...
https://marketplace.visualstudio.com/items?itemName=RoyAction.color-manager

**Comment by Favna** [comment]
How many votes are required for picking this up MS dev team? It's on 50 right now.

**Comment by ShMcK** [comment]
@eamodio any chance you could share which solution you went with? https://github.com/TeamCodeStream/CodeStream seems to use a functional side panel

**Comment by kaleidawave** [comment]
@ShMcK It seems CodeStream uses WebView in a normal editor window but tiled. Although it looks its in a side panel it isn't. The tutorial for doing that https://code.visualstudio.com/api/extension-guides/webview . Not sure how you force tiling though.

This issue / thread here is about allowing the WebView in the sidebar to provide similar experiences to search and source control. You could do CodeStreams way but it's a bit of a hack and less user friendly than if the vscode allowed more advanced controls than just treeview in the sidebar panel.

**Comment by venkatzhub** [comment]
Any information on when this would be added to a milestone? Based on the comments and similar issues opened, it looks like there is a lot of interest and need for this. We are also desperately looking for this capability for a feature we added in our VScode extension. Initial comments from our customers are indicating that they would like the web view as a bottom panel. 

Any information on this would be highly appreciated.

**Comment by mjbvz** [comment]
Yes, it uses the same [`views` contribution point](https://code.visualstudio.com/api/references/contribution-points#contributes.views) as the tree view api.

To put the webview view in the panel, add a custom viewContainer and contribute the view to it:

```json
 "contributes": {
    "viewsContainers": {
      "panel": [
        {
          "id": "my-fancy-view",
          "title": "Fancy View",
          "icon": "fancy.icon"
        }
      ]
    },
    "views": {
      "my-fancy-view": [
        {
          "type": "webview",
          "id": "my-webview",
          "name": "Webview"
        }
      ]
    }
  }
```

<img width="712" alt="Screen Shot 2020-08-24 at 8 52 35 AM" src="https://user-images.githubusercontent.com/12821956/91066966-2e95d980-e5e7-11ea-8846-c31f56511369.png">

**Comment by GordonSmith** [comment]
...and there was much merriment...  Thanks for this!!!

(now who can I nag about:  https://github.com/microsoft/vscode/issues/77138)??

**Comment by mjbvz** [comment]
[Extension sample](https://github.com/microsoft/vscode-extension-samples/tree/master/webview-view-sample) showing how the use the API. It requires the latest VS Code insiders to work

**Comment by GordonSmith** [comment]
@mjbvz When the webview is hosted in a "panel" how does call `show()` to bring it to the top (show it)?

With a terminal, I have a "show" method.

**Comment by RandomFractals** [comment]
.@mjbvz I have not checked out the code behind all this yet, but are there options to pin or specify where thse side bar webviews show up in vscode panels layout? Tree view was a good example.

Can we show them on the left or right side of debug panel? 

How would that api call & setup look like?

**Comment by mjbvz** [comment]
@GordonSmith I added a `show` method for #106028 

You don't need a panel serializer. All webview views are implicitly serialized (although your extension can chose never to save any state if it doesn't need to).  You can access the persisted state either inside the webview itself (this is what [the extension sample does](https://github.com/microsoft/vscode-extension-samples/blob/master/webview-view-sample/media/main.js#L8)) or from [`context.state`](https://github.com/microsoft/vscode/blob/a1e2114347e2cce9eb5e3065ea8027b1092649fd/src/vs/vscode.proposed.d.ts#L2151) during resolve

**Comment by mjbvz** [comment]
@RandomFractals Webview views are contributed the same way as normal tree views which can either go into the side bar or panel by default.

This api does not enable showing views in any new locations. Open separate feature requests if you want to see that supported

**Comment by RandomFractals** [comment]
.@mjbvz there are already many requests open for that show view in other places like #26777 I linked above, with over 500 thumbs up. Not sure me opening another one will make a difference. Maybe you can do that next after this addition.

Thanks!

**Comment by GordonSmith** [comment]
@mjbvz is it just me or did the proposed API never make it into the official vscode.d.ts file?
