### ISSUE TITLE
Test folding improvements

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#46588]
Test for #45981:

- [x] win @dbaeumer (JSON)
- [x] anyOS @bpasero  (HTML)

Complexity: 3

Cancellation with folding providers and limiting the number of transmitted regions to 5000.

- open a very large JSON file 
- collapse some regions
- observe the folding ranges while typing. 
   -> the collapse regions should never unfold
   -> no slowness can be observed, no old regions applied 
- enable tracing for the JSON language server ("json.trace.server": "messages") to see which folding requests go through. 

Multi-line comments
- test multi line comments in JSON and HTML and verify that they can be folded

**Comment by bpasero** [comment]
I noticed some slowdown on a 50k HTML file when I typed and immediately expanded a node below. Not sure if this should be looked at @aeschli
