### ISSUE TITLE
Test: Filing issues on extensions within issue reporter

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#46595]
Test for https://github.com/Microsoft/vscode/issues/45673

- [x] macOS @kieferrm 
- [ ] windows @auchenberg    
- [x] linux @mjbvz 
- [x] macOS @joaomoreno 

Complexity: 2

The issue reporter now has an option for filing against an extension instead of VSCode. Verify that you can select an extension to file against and are directed to the extension's repository.
- The extension version should be in the submitted data included along with the OS and VSCode versions.
- The reporter should not let you preview until you've made selections for all of the form fields.
- Similar issue search should be done against the extension's repository

**Comment by kieferrm** [comment]
This is currently blocked because of #46727.

**Comment by kieferrm** [comment]
@auchenberg  @mjbvz New insider builds are available for download.

**Comment by kieferrm** [comment]
👍
