### ISSUE TITLE
VSCode prevents OS suspension (Ubuntu) when a file or folder stored on a VM (VirtualBox) mounted using sshfs is open

### ISSUE THREAD

**Issue by mdziekon** [microsoft/vscode#46599]
Issue Type: <b>Bug</b>

Other useful details:
- Problem persists for a long time now, so it's not a regression in current insider version of VSCode

Steps to reproduce:
1. Start a VM (VirtualBox, Debian Jessie) and mount it using sshfs
2. Open a file/folder/workspace stored on a VM / mounted via sshfs in VSCode
3. Try to suspend the system

Expected result:
1. System suspends properly

Actual result:
1. System won't suspend, showing two subsequent messages about being "Unable to freeze tasks", each displayed on TTY after 20 seconds
2. System will come back just like nothing has happend (except it locks the user account, so you have to unlock it again) with it's GUI after about 40 seconds
3. Closing VSCode or closing "remote" file/folder/workspace solves the issue

VS Code version: Code - Insiders 1.22.0-insider (b75321329388d74e34f79dcfcb789246e31836a8, 2018-03-22T06:13:39.168Z)
OS version: Ubuntu 17.10, Linux x64 4.13.0-32-generic (also reproducible using Ubuntu 17.04)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1920X 12-Core Processor (24 x 2200)|
|Load (avg)|7, 4, 2|
|Memory (System)|31.34GB (26.51GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
latex-workshop|Jam|5.0.3
material-icon-theme|PKi|3.2.6
vscode-docker|Pet|0.0.25
vscode-multi-line-tricks|big|0.0.3
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
vscode-firefox-debug|hbe|1.1.3
prettify-json|moh|0.0.3
vscode-json5|mrm|1.0.0
python|ms-|2018.2.1
cpptools|ms-|0.15.0
debugger-for-chrome|msj|4.2.2
todotasks|san|0.5.0
trailing-spaces|sha|0.2.11
json-schema-validator|tbe|0.1.0
transpose|v4r|0.0.5
highlight-matching-tag|vin|0.4.4

(3 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@mdziekon does it happen with any folder you open?

**Comment by mdziekon** [comment]
@bpasero if you ask any folder on my machine, including local folders, then no - looks like regular folders and files do not cause this problem. I've even tried opening a folder stored on a remote computer (a laptop connected to my home network, mounted using sshfs) and I was not able to reproduce the problem.

However, every folder or file that is stored on a VM causes the problem. I've tried opening folders that both have and don't have git repos in them, but it seems like this does not matter.

**Comment by foormea** [comment]
I confirm that this is happening.

**Comment by FlyingPumba** [comment]
Still happening.

**Comment by schworak** [comment]
Still an issue.

**Comment by systemofapwne** [comment]
Something similar happens to me:
- Mount remote (does not need to be a VM) via sshfs to local filesystem
- Open that mountpoint in vs code
- Suspend the system
--> System tries to suspend, fails, and just comes back right after. Closing VSCode solves the issue (while still having the mounts present)

**Comment by xuancong84** [comment]
The bug is still happening to me everyday now but the issue is closed. Are the developers going to ignore this bug?

**Comment by xuancong84** [comment]
One workaround is to prepare an executable script `/etc/acpi/laptop-lid.sh` with the following content:
```
#!/bin/bash

killallbyname() {
        if [ $# == 0 ]; then
                echo -e "Usage: ${FUNCNAME[0]} proc-search-pattern [-N]
This kills all processes having a command line matching the \033[1;31mgrep\033[0m pattern.
N: signal for the kill
0 - ? 
1 - SIGHUP - ?, controlling terminal closed, 
2 - SIGINT - interupt process stream, ctrl-C 
3 - SIGQUIT - like ctrl-C but with a core dump, interuption by error in code, ctl-/ 
4 - SIGILL 
5 - SIGTRAP 
6 - SIGABRT 
7 - SIGBUS 
8 - SIGFPE 
9 - SIGKILL - terminate immediately/hard kill, use when 15 doesn't work or when something disasterous might happen if process is allowed to cont., kill -9 
10 - SIGUSR1 
11 - SIGEGV 
12 - SIGUSR2
13 - SIGPIPE 
14 - SIGALRM
15 - SIGTERM - terminate whenever/soft kill, typically sends SIGHUP as well? 
16 - SIGSTKFLT 
17 - SIGCHLD 
18 - SIGCONT - Resume process, ctrl-Z (2nd)
19 - SIGSTOP - Pause the process / free command line, ctrl-Z (1st)
20 - SIGTSTP 
21 - SIGTTIN 
22 - SIGTTOU
23 - SIGURG
24 - SIGXCPU
25 - SIGXFSZ
26 - SIGVTALRM
27 - SIGPROF
28 - SIGWINCH
29 - SIGIO 
29 - SIGPOLL 
30 - SIGPWR - shutdown, typically from unusual hardware failure 
31 - SIGSYS" >&2
                return 0
        else
                ps aux | grep "$1" | sed '/grep/d' | awk '{print $2}' | xargs kill $2
        fi
}

source $HOME/.Xdbus
grep -q closed /proc/acpi/button/lid/LID0/state
if [ $? = 0 ]; then
    # close action
        killallbyname "code/code" "-s SIGSTOP"
    systemctl suspend
else
        killallbyname "code/code" "-s SIGCONT"
fi
```

And add it into ACPI event listener by creating a new file `/etc/acpi/events/laptop-lid` with the following content:
```
event=button/lid.*
action=/etc/acpi/laptop-lid.sh
```

I hope this can be implemented by Linux/Ubuntu by generalizing to all processes that prevent system suspend.
