### ISSUE TITLE
'switch' not matched as '.keyword.control'

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#4659]
- VSCode Version: 0.10.11 and recent Insiders version
- OS Version: Mac OS X

Steps to Reproduce:

```
function check(n) {
  switch(n) {
    case 1:
      console.log('one');
      break;
    default:
      console.log('other');
      break;
  }

  if (n === 1) {
    console.log('one');
  } else {
    console.log('other');
  }

  return n;
}

check(1);
```

`case`, `break`, `default`, `if`, `else` and `return` are matched as `.keyword.control`, but not `switch`. Tested with JavaScript and TypeScript.

I'd like to fix this myself, but would need some guidance to find the correct code.

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#138
