### ISSUE TITLE
Test: Terminal Command Navigation

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#46594]
#45435 

- [ ] macOS @chrisdias 
- [x] Any OS @kieferrm 

The terminal now allows navigating and selecting between commands run inside the terminal. This is done by guessing where a command is based on when enter is pressed, specifically if the line length is 2 characters or more.

See https://github.com/Microsoft/vscode/issues/45435#issuecomment-375035299 for keybindings/commands to test. On Windows or Linux you will need to setup custom keybindings or test using the command palette.

**Comment by kieferrm** [comment]
Great feature 👍.

**Comment by chrisdias** [comment]
yep, great feature. #46561 is the biggest issue i see on Mac. i have no idea where I am when scrolling.
