### ISSUE TITLE
VS Code unresponsible at random times while editing text

### ISSUE THREAD

**Issue by heuripedes** [Microsoft/vscode#46598]
Issue Type: <b>Performance Issue</b>

**When did this performance issue happen?**

Started happening after the 1.21.x release. I tested March 25's Insider and it is also present in it.

*Does it occur on startup or after a specific series of actions?*

Most of the time it happens while typing text into the editor regardless of the filetype/syntax in use. It also happens while editing settings.

**Extra comments:**

* There are no CPU, RAM or Disk usage spikes when this happens.
* Focusing a different window and returning to Code fixes the issue temporarily.
* Happens in a clean install (removed `~/.vscode` and `~/.config/Code`).
* Sometimes it only affects code editor widget (i.e. I can still interact with the menus or the sidebar).

**Extra data**

* User settings: https://pastebin.com/YY2b8ZvN
* Verbose console output: https://pastebin.com/Hjat66pu

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.15.11-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3700)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.57GB (2.99GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	   132	  1859	code main
    0	    23	  1861	   zygote
    0	    93	  1904	     shared-process
    7	   263	  2094	     window (settings.json - mcdjango - Visual Studio Code)
    0	    85	  2122	       extensionHost
    0	   101	  2272	         electron_node htmlServerMain.js 
    0	    77	  2463	         electron_node jsonServerMain.js 
    0	    85	  2130	       watcherService
    0	    77	  2350	       searchService
    1	   178	  2212	     shared-process
    0	    85	  2737	     shared-process
    2	    77	  1886	   gpu-process
    0	     0	  2754	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (settings.json - mcdjango - Visual Studio Code)
|    Folder (mcdjango): 7853 files
|      File types: pyc(2221) py(1964) mo(1172) po(1172) h(143) html(129)
|                  js(78) so(70) txt(51) svg(25)
|      Conf files: settings.json(1) makefile(1);
```

</details>
Extensions: none
Reproduces without extensions

**Comment by alexandrudima** [comment]
@heuripedes I am sorry, but I cannot reproduce.

I could take a look at what we are executing when you are typing. Can you please take a CPU profile when the slowness occurs?

To get a CPU profile of the renderer process:
* Run `F1 > Toggle Developer Tools`
* Go to the three dots burger menu
* Choose `More Tools > JavaScript Profiler`
* Start a new CPU profile
* Do the actions that lead to slowness
* Save the CPU profile to a file and attach it

![kapture 2017-10-21 at 13 02 25](https://user-images.githubusercontent.com/5047891/31851158-30fd860a-b660-11e7-9018-661394adb754.gif)

**Comment by heuripedes** [comment]
It took a long time to trigger the issue, check the the last 30s or so. This time in particular it happened when I was typing in a Python file and the completion popup was on screen, something like the picture attached:

1.  I typed `self.` and the popup appeared.
2. I started typing `object` but only the `o` was visible, the code editor was already unresponsive and I typed random things.
3. I focused the calculator window I had opened previously
4. I went back to Code and it was now displaying `self.objectahsdfuhasdlkfjasldkfjlk`

Picture: ![screenie](https://user-images.githubusercontent.com/59172/38000643-f1ea4e2e-31fe-11e8-9c58-c42ef3abfcc3.png)

Cpu profile: [CPU-20180327T202909.cpuprofile.gz](https://github.com/Microsoft/vscode/files/1854117/CPU-20180327T202909.cpuprofile.gz)

**Comment by heuripedes** [comment]
Another big profile, check the last 15s of this one.

This time it happened when I was scrolling on a HTML file. After focusing a different window and returning to Code the problem was gone.

[CPU-20180327T212548.cpuprofile.gz](https://github.com/Microsoft/vscode/files/1854179/CPU-20180327T212548.cpuprofile.gz)

**Comment by alexandrudima** [comment]
Unfortunately, in both CPU profiles there is nothing fishy at all. All the stack traces I see keep the UI thread busy for at most 10ms-20ms at a time, and then yield... This is normal...

![image](https://user-images.githubusercontent.com/5047891/38015889-8ab951d6-326d-11e8-89f4-56cb873ee2af.png)

I don't really know what could be wrong here... You could try to disable the GPU process (`code --disable-gpu`). The only fishy thing I see is from the process info where there are 3 shared processes running. Did you try killing all code processes? Perhaps they cause the main process to freeze....

```
CPU %	Mem MB	   PID	Process
    4	   132	  1859	code main
    0	    23	  1861	   zygote
    0	    93	  1904	     shared-process
    7	   263	  2094	     window (settings.json - mcdjango - Visual Studio Code)
    0	    85	  2122	       extensionHost
    0	   101	  2272	         electron_node htmlServerMain.js 
    0	    77	  2463	         electron_node jsonServerMain.js 
    0	    85	  2130	       watcherService
    0	    77	  2350	       searchService
    1	   178	  2212	     shared-process
    0	    85	  2737	     shared-process
    2	    77	  1886	   gpu-process
    0	     0	  2754	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

**Comment by joaomoreno** [comment]
@alexandrudima I don't really trust those 3 shared process labels. Here's what I get from my machine:

```
CPU %	Mem MB	   PID	Process
   17	    98	 13976	code-insiders main
    4	    82	 13977	   gpu-process
    3	    82	 13980	   shared-process
    6	   311	 91185	   window (sharedProcessMain.ts — vscode)
    0	    98	 91188	     extensionHost
    0	    82	 91196	       electron_node tslintServer.js 
    0	   508	 91197	       electron_node electronForkStart.js tsserver.js 
    0	    49	 91218	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    49	 91239	       electron_node jsonServerMain.js 
    0	   131	 91189	     watcherService
    0	    66	 91191	     searchService
   68	    82	 91247	   shared-process
    0	     0	 91248	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

I for sure don't have two shared processes running.

[This](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/ps.ts#L95) tells me that pretty much every renderer which doesn't have `--disable-blink-features=Auxclick` appears as the shared process. That is definitely not true. Filed https://github.com/Microsoft/vscode/issues/46818.

**Comment by heuripedes** [comment]
Updates:

- I cannot reproduce the issue when the "Performance" tab profiler is active (I can still reproduce with "Javascript Profiler").
- I cannot reproduce it with `--disable-gpu`.

**Comment by alexandrudima** [comment]
@heuripedes Then please launch `code --disable-gpu`. Unfortunately, that is something outside of our control (VS Code). Rendering is something implemented/executed by Chromium, on top of which Electron is built (our runtime framework).

The way forward (to get this improved/resolved) is:
* try to find some sort of website/repro using Chromium/Chrome
* file an issue or find one at https://bugs.chromium.org/p/chromium/issues/list
