### ISSUE TITLE
Trim trailing whitespaces on line with cursor when explicitly saving

### ISSUE THREAD

**Issue by gwynjudd** [Microsoft/vscode#466]
I have this set in my settings.json:

![image](https://cloud.githubusercontent.com/assets/314188/11328824/c1e909cc-91f6-11e5-94a0-3687d1b02c08.png)

But after saving a file containing some trailing whitespace, it doesn't get trimmed:

![image](https://cloud.githubusercontent.com/assets/314188/11328829/e300064c-91f6-11e5-8fda-75e8680f0561.png)

**Comment by gwynjudd** [comment]
A better screenshot:

![image](https://cloud.githubusercontent.com/assets/314188/11328840/0973beb8-91f7-11e5-80e9-ffc650ec110d.png)

I expected it would remove the whitespace after the ';' at the end of the line.

**Comment by bpasero** [comment]
It works but not on the line the cursor is on because in that case we do not know if you want to continue typing after the whitespace.

**Comment by thegiantbeast** [comment]
@bpasero so shouldn't the editor have one more option to define that?

**Comment by bpasero** [comment]
@thegiantbeast we cannot really offer such an option because when auto save is enabled, the save can kick in anytime (currently 1 second after making a change) and you would not be able to type whitespace after the end of a line and continue typing.

**Comment by thegiantbeast** [comment]
That doesn't sound complex, as long as you differentiate a save from auto save (where the white spaces are not trimmed) and when the user actually saves a file, no?

It's because it's really annoying that I have to remember to delete the spaces in the line that I'm in.

**Comment by bpasero** [comment]
@alexandrudima fyi

**Comment by alexandrudima** [comment]
@bpasero :+1: 
I like the idea: an explicit `ctrl+s` should trim everything, a background auto-save should keep doing what its doing now.

**Comment by alexandrudima** [comment]
:+1: This is great! Thank you!

**Comment by bpasero** [comment]
:heart:
