### ISSUE TITLE
Tab indentation is wrong when copy-pasting

### ISSUE THREAD

**Issue by westwick** [Microsoft/vscode#46605]
Fresh install, no plugins. Observe: http://g.recordit.co/2O4lTECCeG.gif

![](http://g.recordit.co/2O4lTECCeG.gif)

The `formatOnPaste` setting is not a good option for me, because if for example I have an `<i>` inside of a `<p>`, e.g. `<p><i class="material-icons">radio</i></p>`, the auto-formatting splits the `<i>` onto a new line, making it inconsistent with the line I just copied.

I know this issue has been discussed before but I have not found a good answer that doesn't require using a plugin, and this is honestly such a simple and basic feature that getting indentation correct should be default behavior out of the box. This is my one and only major annoyance with vscode that is seriously making me rethink my editor choice.

**Comment by alexandrudima** [comment]
This is a case for `editor.autoIndent` going wrong.

Reduced repro:

![kapture 2018-03-27 at 15 44 12](https://user-images.githubusercontent.com/5047891/37971233-bb7a200e-31d5-11e8-8659-862ddcf368d7.gif)

**Comment by rebornix** [comment]
Thanks all for your feedback, let's track this issue in https://github.com/Microsoft/vscode/issues/32320 , which talks about similar bug (indentation adjustment when pasting, moving, entering) in HTML/PHP like language. All your input will be considered when we tackle this issue. 

For you now if the indentation adjustment makes pasting worser, you can turn this off by setting `editor.autoIndent` to `false`. Thanks again for your help!
