### ISSUE TITLE
VS Code node.js project misses *.d.ts files located in project-level node_modules

### ISSUE THREAD

**Issue by Tarocco** [Microsoft/vscode#46601]
Typescript is getting its type declarations from Automatic Type Acquisition, but in my case, the declarations for material-ui are from `"@types/material-ui": "^0.21.1"` in `%appdata%/Microsoft/TypeScript/2.7/package.json`. (That is the latest version of the @types/material-ui package as of today).  VS Code is handling this for me, but the problem is that I am using a newer version of material-ui. In my `project.json` file I have `"material-ui": "^1.0.0-beta.38"`, and I have material-ui in my `node_modules` folder after running `npm install`. The material-ui 1.0.0-beta.38 package includes .d.ts and .js.flow files with its .js files.

VS code is pulling in completion and type declarations from the `@types` modules _but not the project modules._ I am also seeing duplicate entries in the completion list, but I think that is a separate issue altogether.

Is this expected behavior? Everything I can find tells me that VS Code should be able to find these type declaration files in the workspace as well. Otherwise, how can I instruct VS Code to import all the *.d.ts files in my project's `node_modules` directory?

```js
// material-ui 1.0.0-beta.38
// Missing from completion
// Compiles
// From ./node_modules/material-ui/Typography/index.d.ts
import Typography from 'material-ui/Typography'

// material-ui 0.21
// Missing from completion
// Compiles
// From %appdata%\Microsoft\TypeScript\2.7\node_modules\@types\material-ui\index.d.ts
import { Typography } from 'material-ui' 

// material-ui 0.21
// Included in completion
// Does not compile
// From %appdata%\Microsoft\TypeScript\2.7\node_modules\@types\material-ui\index.d.ts
import Typography from 'material-ui' 

// material-ui 0.21
// Included in completion
// Does not compile
// From %appdata%\Microsoft\TypeScript\2.7\node_modules\@types\material-ui\index.d.ts
// "typography" in module, "Typography" in completion:
// declare module 'material-ui/styles' {
// ...
//   export import typography = __MaterialUI.Styles.Typography;
// ...
// }
import { Typography } from 'material-ui/styles';
```

GIF screenshot illustrating the issue, and showing manually importing a module:
![2018-03-26_16-22-13](https://user-images.githubusercontent.com/16038281/37938397-7bf59bde-3112-11e8-8102-838ca0c2aeb5.gif)

_PS: Honestly, this could be an issue with TypeScript but I'm not sure, I don't know._

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22927
