### ISSUE TITLE
Workspace: Open Workspace Configuration File is not working in single folder workspace

### ISSUE THREAD

**Issue by benyaminl** [Microsoft/vscode#46609]
- VSCode Version: 1.21.1
- OS Version: Windows 7 Ultimate x64

Steps to Reproduce:

1. Open Ctrl+shift+P  > Choose these.
![image](https://user-images.githubusercontent.com/2817332/38038441-27c4398e-32d5-11e8-936d-424bd6c8da77.png)
2. It do nothing on my VSC... 

Does this issue occur when all extensions are disabled?: Yes (On or off)

**Comment by sandy081** [comment]
@benyaminl May I know if you are performing this command inside a workspace or in empty window? Do you see any errors in the console?

**Comment by benyaminl** [comment]
@sandy081 I run in on a workspace, it doesn't work. No error or signs of it on developer tools console. It's been around but I wait that could be a possible fix, But until now, it's not fixed anyway.

**Comment by sandy081** [comment]
@benyaminl Is it just this command not working ? Or also `Preferences: Open User Settings`?

**Comment by benyaminl** [comment]
@sandy081 Surprisingly the `Preferences: Open Workspace Settings` is working and `Preferences: Open User Settings` working too. I think I need to edit again the question, the `Workspaces: Open Workspace Configuration File` not working, i done nothing, such that. Sorry for confused between it. 
![image](https://user-images.githubusercontent.com/2817332/38038441-27c4398e-32d5-11e8-936d-424bd6c8da77.png)

**Comment by sandy081** [comment]
@benyaminl `Open Workspace Configuration File` command works only in the context of Multi folder Workspace and not in Single Folder Workspace.

**Comment by benyaminl** [comment]
@sandy081 I think the best practice would be hide the option when it's not on multi folder project. I think. Just suggesting, because I'm confused with it. Thanks for clarifying.

**Comment by sandy081** [comment]
@benyaminl Yes that's going to be the fix

**Comment by benyaminl** [comment]
Thanks






Sent from My Asus Pegasus X005



Pada tanggal Kam, 29 Mar 2018 13.28, Sandeep Somavarapu <
notifications@github.com> menulis:
