### ISSUE TITLE
Flutter exmples

### ISSUE THREAD

**Issue by petervrichards** [Microsoft/vscode#46606]
Issue Type: <b>Bug</b>

Flutter examples does not appear to be configured with the current version.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.12GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.10.0
vscode-markdownlint|Dav|0.14.1
async-switch|Eme|0.5.0
fs-flutter-snippets|fra|0.1.3

</details>
Reproduces only with extensions

**Comment by dbaeumer** [comment]
@petervrichards can you please provide more information. Flutter examples were never something that worked out of the box.

**Comment by petervrichards** [comment]
here's the get packages errors 
[flutter_gallery] flutter packages get 
Running "flutter packages get" in flutter_gallery... 
Package collection has no versions that match 1.14.5 derived from: 
- async 2.0.6 depends on version ^1.5.0 
- barback 0.15.2+15 depends on version ^1.5.0 
- boolean_selector 1.0.3 depends on version ^1.5.0 
- crypto 2.0.2+1 depends on version ^1.0.0 
- flutter 0.0.0 depends on version 1.14.5 
- flutter_gallery depends on version 1.14.6 
pub get failed (1) 
exit code 1 
and build.gn 

# Copyright 2017 The Fuchsia Authors. All rights reserved. 
# Use of this source code is governed by a BSD-style license that can be 
# found in the LICENSE file. 

import("$flutter_root/build/flutter_app.gni") 

assert(is_fuchsia) 

flutter_app("flutter_gallery") { 
main_dart = "lib/main.dart" 

disable_analysis = true 

deps = [ 
"../../packages/flutter", 
"//third_party/dart-pkg/pub/url_launcher", 
] 

# TODO(chinmaygarde): Assets must be packaged in the FLX. 
}

**Comment by petervrichards** [comment]
here's the bug file 
peter richards

**Comment by dbaeumer** [comment]
@petervrichards this looks like a problem with Flutter itself and nothing that is related to VS Code. I would recommend that you file the issue against the Flutter project.

**Comment by petervrichards** [comment]
Will do. 
peter richards
