### ISSUE TITLE
Resize the sidebar and editor pannels by double-clicking on their border

### ISSUE THREAD

**Issue by mquandalle** [Microsoft/vscode#4660]
Both Sublime Text and Atom have the ability to resize the sidebar to its “optimal width” (*ie*: the minimum width that is large enough to display every element inside) by double clicking on its border:

![resize-sidebar](https://cloud.githubusercontent.com/assets/1730702/14068197/3871b3b8-f47c-11e5-8786-2f08751370a2.gif)

I’m opening the feature request to have something similar on VSCode.

**Comment by mquandalle** [comment]
This should also be implemented to resize the editor panes in the split view. In that case double-clicking would make to panes of equal width.

**Comment by Tyriar** [comment]
@bpasero not sure who the owner for this should be, reassign if necessary.
