### ISSUE TITLE
Terminals opening up blank

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46608]
Today, I've seen new terminals open completely blank several times but I don't have consistent repro steps.

A couple times when starting a build task. Once when using the context menu item, "Open in terminal".

Switching the active panel doesn't fix it, but switching terminals with the dropdown does fix it.

Existing issue for this?

**Comment by cleidigh** [comment]
@roblourens 
There is an outstanding issue I am working on that exists in both the terminal and new drop-down code.
When  terminal instances are added in particular disposed , the instance count can end up not matching
the index passed to setOptions .  This can cause a couple different problems including a blank select.  

While you mentioned that the drop-down appears to work I wonder if this is still related.  I'm adding myself to track or help with this

**Comment by Tyriar** [comment]
@roblourens is it just the dropdown or whole terminal? You should show me today :slightly_smiling_face:

**Comment by roblourens** [comment]
The whole terminal. I can't get it to repro right now but I'll watch out for it today.

**Comment by roblourens** [comment]
Been trying to get this to repro again but I haven't seen it.
