### ISSUE TITLE
Changing encoding in diff editor only changes it on the right hand side

### ISSUE THREAD

**Issue by fx72516** [Microsoft/vscode#46619]
Issue Type: <b>Bug</b>

命令行使用 code -diff "" "" 比较两个文本文件，中文字符乱码，更改编码重新打开，只用一个文件文本编码正确，另一个文件中文字符还是乱码；

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|15.89GB (3.57GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe --diff 新建文本文档 (3).txt 新建文本文档 (4).txt|
|Screen Reader|no|
|VM|67%|

</details>Extensions: none
Reproduces without extensions

**Comment by dbaeumer** [comment]
@fx72516 please provide the description in English.

Automatic translation:

The command line uses code-diff      to compare two text files, the Chinese characters garbled, change the encoding to reopen, only one file text encoded correctly, another file of characters or garbled

**Comment by bpasero** [comment]
@fx72516 file a new issue in english please

**Comment by bpasero** [comment]
**Verify:** changing the encoding (Reopen with encoding) changes the encoding for both sides if 2 files are compared. Still works as before for single files.

**Comment by fx72516** [comment]
I'm sorry and thanks.

**Comment by navono** [comment]
I update VS Code to `1.22.2`, but the bug still exists.
![garbled](https://user-images.githubusercontent.com/3746639/39292006-652d2b2a-4967-11e8-8dff-cb979eeb3f7f.PNG)

>版本 1.22.2
提交 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
日期 2018-04-12T17:28:16.777Z
Shell 1.7.12
渲染器 58.0.3029.110
Node 7.9.0
架构 ia32
