### ISSUE TITLE
Not getting any option on UI to terminate running task ("Run task" for Grunt.)

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4661]
- VSCode Version:0.10.12-alpha
- OS Version:windows10

Steps to Reproduce:
1. launch app and open any folder which has a project with gruntfile.js.
2. Press F1 and enter >task run and select option for run task like below and choose "serve" task from the list.
![image](https://cloud.githubusercontent.com/assets/17735796/14033531/488c19e2-f1d8-11e5-99f6-bcada8bc3ef3.png)

3. Verify VScode output window and it should launch a browser for with proper URL.
4. Verify in the status bar you a stick rotating icon should be displayed till task is running.
5. Try to terminate running task.

Actual: 
1. When user clicks on icon from status bar which is indicating running task, we are expecting some kind of notification or pop-up to take further action on running task.
2. I didn't find any option to terminate current running task from UI, except when I fire other command or type "terminate running task" from command palette.

Expected: There should be some UI control to terminate current running task. or when user click on icon showing running task  status should display pop-up like below:
![image](https://cloud.githubusercontent.com/assets/17735796/14033569/a618ceb6-f1d8-11e5-9262-0f3aaa6cc541.png)

**Comment by Tyriar** [comment]
Looks like a command is available to do this: `workbench.action.tasks.terminate` (F1 -> type "term"). It's not very discoverable though, being one of the keybindings with no default binding.

Let's track a UI button to terminate the task in this issue, and a default keybinding in https://github.com/Microsoft/vscode/issues/214

**Comment by dbaeumer** [comment]
Closing if favour of #214
