### ISSUE TITLE
Wrong indent - copy / paste if there is a comment

### ISSUE THREAD

**Issue by shizengzhou** [microsoft/vscode#46618]
@rebornix 
Issue Type: <b>Bug</b>

![paste](https://user-images.githubusercontent.com/24318019/37951168-0f67064e-31ce-11e8-8322-3c1c9a4683a5.gif)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|7.89GB (3.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
asset|shi|0.0.1
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.7
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|4.2.2
vscode-icons|rob|7.22.0
open-in-browser|tec|1.1.0

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Closing due to lack of further user interest in this issue over the past two plus years

Try enabling format on type and format on paste, which should both provide much more consistent indentation
