### ISSUE TITLE
KDE Plasma 5.12.2 Global menu not working with VsCode

### ISSUE THREAD

**Issue by asierralozano** [Microsoft/vscode#46614]
- VSCode Version: 1.21.1
- OS Version: Fedora 27

Steps to Reproduce:

1. Add the Global Menu Widget to any panel in your KDE desktop
2. The menu bar will still appear on VSCode, but not in the Global Menu widget

**Comment by bpasero** [comment]
@asierralozano please check if https://github.com/Microsoft/vscode/issues/34510 has steps to fix it for you

**Comment by asierralozano** [comment]
Ok, sorry, I installed the wrong rpm.
Now it's working perfectly!
