### ISSUE TITLE
only use indent of 4 spaces error message

### ISSUE THREAD

**Issue by jasoncodingnow** [Microsoft/vscode#46616]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. I am writing solidity code
2. and I change setting to : "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "editor.detectIndentation": false,

and it keep shows "only use indent of 4 space"
what's going on?

**Comment by alexandrudima** [comment]
@jasoncodingnow Have you tried to disable all extensions?

**Comment by ads1018** [comment]
You can configure the Solhint linter in your vscode user settings:
```
"solidity.linter": "solhint",
"solidity.solhintRules": {
  "avoid-sha3": "warn"
}
```

**Comment by tacticalfinance** [comment]
if you are using JuanBlanco.solidity extension, Solium is the default linter supported by the extension  and you can configure it using the following user settings:

    "solidity.linter": "solium",
    "solidity.soliumRules": {
        "quotes": ["error", "double"],
        "indentation": ["error", 2]
    }
