### ISSUE TITLE
Extension API cursorMove with multiple selections 

### ISSUE THREAD

**Issue by austenc** [Microsoft/vscode#46613]
Issue Type: <b>Bug</b>

Hello! I'm working on an extension that automatically adds some spaces between template tags such as the one seen here: `{{ | }}`. When two `{{` are typed, I'm basically adding two spaces, and then trying to move the cursor back one character. Using `cursorMove` works great unless I have multiple selections. Is this intended functionality? I've posted a quick animation below (first example works, second with 3 cursors does not)

Here's my code:
```
        editor.selections.forEach(selection => {
            let pos = selection.active;
            let line = editor.document.lineAt(pos.line).text;
            let before = line.slice(Math.max(pos.character - 2, 0), pos.character);
            let after = line.slice(pos.character, pos.character + 2);

            if (before === '{{' && after === '}}') {
                editor.edit(edit => {
                    edit.insert(pos, '  ');
                });                

                commands.executeCommand('cursorMove', {to: 'left', by: 'character'})
            }
        });
```

![code](https://user-images.githubusercontent.com/575421/37946564-51dc44de-3143-11e8-81a9-92bc6125de2a.gif)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|Load (avg)|2, 3, 3|
|Memory (System)|4.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
activitusbar|Gru|0.0.7
vscode-paste-and-indent|Rub|0.0.8
amvim|aui|1.24.0
laravel-docs|aus|1.0.2
tailwind-docs|aus|1.0.1
npm-intellisense|chr|1.3.0
laravel-blade|cjh|1.1.2
tslint|eg2|1.0.28
php-debug|fel|1.12.2
sublime-keybindings|ms-|3.0.3
vetur|oct|0.11.7
laravel-blade|one|1.17.0
laravel5-snippets|one|1.4.0

</details>
Reproduces only with extensions

**Comment by alexandrudima** [comment]
@austenc When in the gif you have 3 selections, I believe you end up invoking `cursorMove` 3 times, so you are moving all 3 cursors to the left 3 times by 1 character.
