### ISSUE TITLE
Non consistent bug - debugger not starting

### ISSUE THREAD

**Issue by xameeramir** [Microsoft/vscode#46621]
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a node project
2. Press F5 or Click play button from debugger pane

Does this issue occur when all extensions are disabled?: Yes

A few times I have noticed that the debugger does not start in Visual Studio. Please fix this.

**Comment by isidorn** [comment]
Please update to latest vscode version, you are on 1.13.1 which is a year old.

**Comment by xameeramir** [comment]
@isidorn @vscodebot The issue still persists with latest 1.21.1 tool

**Comment by isidorn** [comment]
Then please read this how to file a quality bug https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
