### ISSUE TITLE
March Endgame

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#46620]
## Endgame Schedule
- *March 26th*, Code freeze for the endgame
- *March 30th*, Endgame done

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

### Monday

- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items are created (with "complexity" but not necessarily with full description) by 5pm PT
- [x] All test items contain comprehensive test descriptions by 10pm PT
- Update your availability for testing here - https://vscode-tools.azurewebsites.net/

### Tuesday

- [x] [Test plan items](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Atestplan-item+milestone%3A%22March+2018%22) assigned
- [x] [All closed feature-requests without either verification-needed or on-testplan tag](https://github.com/Microsoft/vscode/issues?q=label%3Afeature-request+-label%3Aon-testplan+-label%3Averification-needed+-label%3A%2Aduplicate+is%3Aclosed+milestone%3A%22March+2018%22)
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+label%3Averification-needed+is%3Aclosed+milestone%3A%22March+2018%22)

### Wednesday

- [x] Remind team members to assign issues that they intend to fix to the February milestone
- [x] Testing
- [x] [Fixing](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A%22March+2018%22) (self-assigned, milestone assigned)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+label%3Averification-needed+is%3Aclosed+milestone%3A%22March+2018%22)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+-label%3Averified+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aerror-telemetry+-label%3Aas-designed+is%3Aclosed+milestone%3A%22March+2018%22+-label%3Atestplan-item+-label%3Aon-testplan+-label%3Averification-needed+-label%3Adebt+-label%3Aplan-item+sort%3Aupdated-desc+)

### Thursday & Friday
- [x] [Fixing last issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22March+2018%22)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+label%3Averification-needed+is%3Aclosed+milestone%3A%22March+2018%22)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+-label%3Averified+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aerror-telemetry+-label%3Aas-designed+is%3Aclosed+milestone%3A%22March+2018%22+-label%3Atestplan-item+-label%3Aon-testplan+-label%3Averification-needed+-label%3Adebt+-label%3Aplan-item+sort%3Aupdated-desc+)
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@sandy081**
  - [x] node-debugadapter-node **@weinand**
  - [x] node-debug **@weinand**
  - [x] node-debug2 **@roblourens**
- [x] Check translations (check `i18n` folder git history for latest translations, then build locally and see the amount of untranslated strings) **@dbaeumer**
- All release notes updated - release notes are collected in a file named *`v1_22.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). This includes new features and notable fixes.
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [ ] @ramya-rao-a
  - [x] @rebornix
  - [ ] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [ ] @tyriar
  - [x] @weinand
- Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section:
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [x] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [ ] vscode-jscs **@chrisdias**
  - [x] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [x] vscode-recipes **@auchenberg**
  - [x] localization **@danyeh**
  - [x] vscode-github-issues-prs **@chrmarti**
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
  - do not forget to update the `distro` attribute in the package.json with the commit ID of the distro repo.
  - Create list for team members to enter new OSS usage into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **endgame master**
- Register new components in [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows
  - [x] OS X
  - [x] Linux
- When done fixing/verifying and there are changes since last build at the end of day PT
  - Trigger new insider build and publish it manually **change author**
- [x] Disable continuous `insider` builds - **endgame master**
- [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
- [x] Bump up the version in `package.json` - **endgame master**
- [x] Announce master is open for business **endgame master**

### Monday week 2
- If not done on Friday
  - [x] Disable continuous `insider` builds - **endgame master**
  - [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
  - [x] Bump up the version in `package.json` - **endgame master**
  - [x] Announce master is open for business **endgame master**
- [x] Polish release notes **@gregvanl**

### Monday week 2 - Wednesday week 2
- [x] Polish release notes **@gregvanl**
- Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **change author**
- Build `Insider` from `release/<x.y>` **endgame master**
- Manually release `Insider` **endgame master**
- Documentation updated
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [ ] @ramya-rao-a
  - [x] @rebornix
  - [ ] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [ ] @tyriar
  - [x] @weinand

### Thursday/Friday week 2
- [x] Merge translations PR (if it makes it in time) **endgame master**
- [x] Build stable for all platforms **endgame master**
- [x] Make rpm signing request **@tyriar**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer **@owner**
    - [x] zip **@owner**
  - [x] OS X - **@owner**
  - [x] Linux
    - [x] deb package 64-bit **@owner**
    - [x] deb package 32-bit **@owner**
    - [x] rpm package 64-bit **@owner**
    - [x] rpm package 32-bit **@owner**
    - [x] archives **@owner**
- [x] Publish website **@gregvanl**
- [x] Publish to stable **@owner**
- [x] Publish deb and rpms to repositories manually **@tyriar**
- [x] Add version with symbols to HockeyApp **@tyriar**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` **endgame master**
- [x] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@seanmcbreen**

**Comment by borekb** [comment]
Out of curiosity, what does "Endgame done" date mean? I think that during the past few iterations, it has always been at the end of week 1 while the endgame always seems to be planned to last two weeks.

Awesome release documentation BTW :)

**Comment by Tyriar** [comment]
@borekb at the top it's referring to the team's test/verification week. The following week we refer to as debt week and we focus on technical debt reduction and fix any remaining issues with the build that pop up. More info here https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration 😄

**Comment by borekb** [comment]
Hmm, that wiki also seems to assume a single-week endgame which I don't think I've ever seen :)

But overall, I could measure month's progress just by looking at the GitHub Milestone progress bar, it's extremely impressive how predictably you deliver VSCode in a relatively large and distributed team. 🙇

**Comment by egamma** [comment]
>Hmm, that wiki also seems to assume a single-week endgame which I don't think I've ever seen :)

@borekb the endgame is one week and the 'Endgame Done' date refers when the engineering work for the release is done. This date is different from when we ship the release. As @Tyriar explains above, after 'Endgame done' we let the release sit. We freeze the insiders channel so that we all test the latest bits and watch for critical issues. We review the critical issues daily. If there is a critical fix we wait for another 24 hours. Therefore the release date is during the week after the endgame, but we never release on a Friday.  I´ll update the wiki with more detail. Given this I cannot remember an endgame that lasted longer than a week :muscle:, but glad to see your interest into our planning!

**Comment by egamma** [comment]
Closing 1.22 has shipped.
