### ISSUE TITLE
PHP linguaggio non presente

### ISSUE THREAD

**Issue by Roby98Luce** [Microsoft/vscode#46625]
Issue Type: <b>Feature Request</b>

Non permette più di salvare i file con estensione .php e inoltre aprendone uno esistente non interpreta il codice visualizzandomelo come testo normale e non come codice PHP.
It no longer allows you to save files with the extension .php and also opening an existing one does not interpret the code by displaying it as normal text and not as PHP code.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
Could an extension be causing this? Can you launch vscode with `--disable-extensions` and check whether it reproes?

**Comment by Roby98Luce** [comment]
I don’t have any extension installed.
 
Da: Rob Lourens [mailto:notifications@github.com] 
Inviato: martedì 27 marzo 2018 18:55
A: Microsoft/vscode <vscode@noreply.github.com>
Cc: Roby98Luce <roberto@microlan.it>; Manual <manual@noreply.github.com>
Oggetto: Re: [Microsoft/vscode] PHP linguaggio non presente (#46625)
 
Could an extension be causing this? Can you launch vscode with --disable-extensions and check whether it reproes?

**Comment by roblourens** [comment]
> It no longer allows you to save files with the extension .php

What happens exactly?

**Comment by Roby98Luce** [comment]
This happens (img attached)
 
Da: Rob Lourens [mailto:notifications@github.com] 
Inviato: mercoledì 28 marzo 2018 17:24
A: Microsoft/vscode <vscode@noreply.github.com>
Cc: Roby98Luce <roberto@microlan.it>; Manual <manual@noreply.github.com>
Oggetto: Re: [Microsoft/vscode] PHP linguaggio non presente (#46625)
 
It no longer allows you to save files with the extension .php
What happens exactly?

**Comment by roblourens** [comment]
I don't see the image, I don't think that works over email

**Comment by Roby98Luce** [comment]
ok now I will try to explain, in practice the <?php and ?> tags, including all the code inside, are not interpreted and are not colored as functions or queries. Also on the bottom right where the type of text format is shown appears to me (plain text) and not anymore (PHP). excuse me for the waste of time. 
 
 
Da: Rob Lourens [mailto:notifications@github.com] 
Inviato: mercoledì 28 marzo 2018 18:24
A: Microsoft/vscode <vscode@noreply.github.com>
Cc: Roby98Luce <roberto@microlan.it>; Manual <manual@noreply.github.com>
Oggetto: Re: [Microsoft/vscode] PHP linguaggio non presente (#46625)
 
I don't see the image, I don't think that works over email

**Comment by roblourens** [comment]
Can you change it to PHP if you click on Plain Text?

Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by Roby98Luce** [comment]
Thank you very much now with insiders version i see tags color and the extenction PHP are now avaiable!
Regards Roberto Luce 
 
Da: Rob Lourens [mailto:notifications@github.com] 
Inviato: giovedì 29 marzo 2018 17:24
A: Microsoft/vscode <vscode@noreply.github.com>
Cc: Roby98Luce <roberto@microlan.it>; Manual <manual@noreply.github.com>
Oggetto: Re: [Microsoft/vscode] PHP linguaggio non presente (#46625)
 
Can you change it to PHP if you click on Plain Text?
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders
