### ISSUE TITLE
Icon to show running task in the status bar is not displaying all the time.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4662]
- VSCode Version:0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1. launch app and open any folder which has a project with gruntfile.js.
2. Press F1 and enter ">task run" and select option for run task like below and choose "serve" task from the list.
![image](https://cloud.githubusercontent.com/assets/17735796/14033888/4d3afd70-f1db-11e5-9977-da8b08836f97.png)
3. Verify status bar and make sure icon should be displayed to indicate running task
4. If icon is showing up then terminate the current task and fire other task and verify status bar.

Actual:
1. Icon is not displaying all the time (in my case build task).
2. Once user terminate the current task (in my case serve task) and fire the same task again then icon is not displaying in the status bar.
![image](https://cloud.githubusercontent.com/assets/17735796/14033975/0d4710d6-f1dc-11e5-842d-cc682b1c2887.png)

**Comment by dbaeumer** [comment]
@v-pavanp I tried to reproduce this but failed. Can you point me to the example you used.

**Comment by dbaeumer** [comment]
Moving to May.

**Comment by dbaeumer** [comment]
I looked into it again and the behavior is actually expected. The task that got started is a watching task. We only show the spinner when the watching task is actually doing work. If it is waiting on file events we don't. There is no 'started task' indication in the status line.
