### ISSUE TITLE
vsts-vscode is slow and hard to configure why there is no such built-in service for tfs as git

### ISSUE THREAD

**Issue by hasanShaddad** [Microsoft/vscode#46624]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
