### ISSUE TITLE
typescript.tsserver.pluginPaths seems to ignore value

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#46633]
Testing #46443

It doesn't seem to matter what the string value for `typescript.tsserver.pluginPaths` actually is. In the example of #46443, I always get intellisense, no matter what the value is. Even:

```json
    "typescript.tsserver.pluginPaths": [
        "what"
    ]
```

**Comment by joaomoreno** [comment]
I was using Code's version.

![image](https://user-images.githubusercontent.com/22350/38015841-68449f7a-326d-11e8-8a4c-a050c70defcc.png)

**Comment by duki994** [comment]
@joaomoreno 

I can confirm this bug. 
tslint-language-service isn't started

I hacked away vscode by installing it directly into extensions folder where vscode's shipped typescript version is.

typescript.tsserver.pluginPaths is just ignoring value

**Comment by duki994** [comment]
@mjbvz 
Any new info on this?

VS2017 community can load workspace plugins easily. ThoughTypeScript SDK for Visual Studio 2017 is a different implementation AFAIK.

For now it seems that Code's bundled TS is searching only under global node_modules.

**Comment by mjbvz** [comment]
@duki994 You do not need this setting. Just install the plugin into node_modules, add it to your `tsconfig` and switch to using the workspace version of typescript
