### ISSUE TITLE
Progress API: Can't create multiple progress notifications with the same title

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#46637]
Testing #46458

The title seems to be used for equality comparisons, so if I issue a new notification with the same title, the previous one gets cancelled, even if I say `cancellable: false`.

This is too implicit, especially considering that I can always change the notification title by later calling `report({ message: 'title' })`, finally getting several notifications with the same title.

**Comment by bpasero** [comment]
Pushed a change to always treat notifications with progress different, independent from any other property.
