### ISSUE TITLE
reference search result navigation skips over an entry when going back

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46631]
Refs: #46553
Win

1. Open VSCode repo, `debug.ts` file
2. Find all references on `IReplElement`
3. do F4 four time - notice how you are nicely navigating over references
4. Shift + F4 - notice that you go back two items, instead of one

Other shift+F4 work fine, just this one skips over a beat

**Comment by dbaeumer** [comment]
Same happens under Linux. I recognized that always the first match in a file is skipped when going backwards.

**Comment by isidorn** [comment]
Works fine with latest out of source -> verified
