### ISSUE TITLE
Problems rendering adjacent bold and italics

### ISSUE THREAD

**Issue by tedhudek** [Microsoft/vscode#4663]
- VSCode Version: 0.10.11
- OS Version: Win10

Steps to Reproduce:
1. Render this text in VS Code:
   Methods are named **Abc**_ObjectAction_, where _Object_ describes the object and _Action_ indicates what the function does. For example, [**AbcDeviceCreate**](http://msdn.microsoft.com) creates a device object.
2. Compare to GitHub rendering.  Having bold adjacent to italics causes Code to stay in italics mode after the closing italics marker.

**Comment by Tyriar** [comment]
Reproduces in latest

![image](https://cloud.githubusercontent.com/assets/2193314/14063768/f1b787be-f394-11e5-9e7a-37042f327781.png)

**Comment by tedhudek** [comment]
Examples to test: (note that they all render correctly on GitHub)

*italics***bold**

**bold***italics***bold***italics*

**bold***italics*

****bold****

**Comment by Tyriar** [comment]
![image](https://cloud.githubusercontent.com/assets/2193314/14084502/ddeef726-f4cf-11e5-897d-104baa080a3b.png)

**Comment by gregvanl** [comment]
Using _ for italics works fine:
_italics_**bold**
**bold**_italics_**bold**_italics_
**bold**_italics_
**_bold_**

**Comment by Tyriar** [comment]
It looks like the specific issue is that the current markdown parser does not consider adjacent `*` styles. See how the breakage first occurs  in `***` styles, treating `**bold***...` as ``**bold**\*...`

The last one is the exception to this, it would seem as though `**` takes precedence over `***` for some reason.

**Comment by bpasero** [comment]
I cannot reproduce with our new markdown extension.

**Comment by Tyriar** [comment]
Some more problem cases:

```markdown
****bold italics****
****bold italics****
****bold italics****


\*\*\**italics****
```

Output on GitHub:

****bold italics****
****bold italics****
****bold italics****

\*\*\**italics****

VS Code @ 93e65224d7598017bfa0b188a0d82b66a2ee9698:

![image](https://cloud.githubusercontent.com/assets/2193314/16129989/10d0ce0a-33bc-11e6-8c55-c3abea58f98b.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#7
