### ISSUE TITLE
emmet-helper getEmmetCompletionParticipants should be typed

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#46634]
emmet-helper getEmmetCompletionParticipants returns an any, and in the HTML code it is assumed to match the HTML and CSS perticipants.
That's very fragile. 

I also want to avoid the `any[]` in https://github.com/Microsoft/vscode/blob/666e95e8e7f679e23c0e42d86864cba4f2e00025/extensions/html-language-features/server/src/modes/languageModes.ts#L38 

Idealy, each mode (CSSMode, HTMLMode) interacts separately with the emmet helper.
Let each mode do the caching and pass in the triggerKind to the mode.
IMO for HTML we don't really need to do the caching. And in the long term I'd like to avoid the caching by improving the CSS parser.

**Comment by ramya-rao-a** [comment]
The move of emmet for css completions to the css extension didn't work out. See https://github.com/Microsoft/vscode/issues/29113#issuecomment-383453793 to learn more.

So now we have just the html extension providing emmet completions outside of emmet extension. See https://github.com/Microsoft/vscode/issues/28545#issuecomment-383453951 on why this isn't much useful.

Reverting the move of emmet html completions from html extension with https://github.com/Microsoft/vscode/commit/c314388da21720d893e7a36345e1cac36d1cfd5f

Enabling css emmet completions in embedded css parts in html files with https://github.com/Microsoft/vscode/commit/79a2512769762928f089e4fd0b84764e37a1ce0d
