### ISSUE TITLE
[css] path completion "./" only suggests "." files/folders

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#46639]
1.22 insiders on Mac. Testing #46537.

I expected all folders/files to show:

![image](https://user-images.githubusercontent.com/9205389/37957979-8f9c3326-31af-11e8-98ad-6b0f60ab55eb.png)

**Comment by aeschli** [comment]
Likely, the filter string must be set to include the beginning of the edit.

**Comment by aeschli** [comment]
Can this be related to #46638?
