### ISSUE TITLE
Incorrect rendering of ascii escape sequences in REPL

### ISSUE THREAD

**Issue by eightvans** [Microsoft/vscode#4664]
- VSCode Version: 0.10.11
- OS Version:Windows 10 version 1511

Steps to Reproduce:
1. Write to the REPL window using a string with an ascii escape sequence indicating both color and boldness as parameters e.g. '\u001b[35;1mmagentabold'
2. Either bold or text color work separately but they do not work together.  Nor are the escape sequences properly removed from the output.

A repo showing the problem can be seen here https://github.com/eightvans/asciiescape
A comment in replViewer.ts references this link http://ascii-table.com/ansi-escape-sequences.php showing how the sequence should be parsed.

**Comment by daviwil** [comment]
Do escape sequences for text colors currently work?  I was under the impression that this wasn't implemented yet.

**Comment by isidorn** [comment]
@daviwil yes we support escape sequences. This issue demonstrates that we do not support 2 escape sequences applyied to the same token at once.
@eightvans the issue is that we do not respect ';' in anscii escape codes. The code is a bit tricky and I will add this feature if more users ask for it
