### ISSUE TITLE
reference search result navigation make more discoverable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#46641]
Refs: #46553

Currently the navigate forward and back in find all references is very hard to discover. Here's what we discussed in the call:

* Add an forward / backward arrow in the find all references title area
* Hover over the arrow should show keybdingins

**Comment by jaywick** [comment]
This is apparently what the new [1.22](https://code.visualstudio.com/updates/v1_22#_error-and-reference-navigation-across-files) is meant to do, but can't seem to get it to work
