### ISSUE TITLE
Organise imports should be a refactoring/code action

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46647]
re #46589

After the investment in code actions, the refactoring menu, and code action keybindings I was quite surprised to see that organise imports isn't a code action but a normal command. I think that makes it harder to discover and also encourages homegrown code action instead of the more stream lined approach.

**Comment by mjbvz** [comment]
This was my initial proposal too. However I now think that command makes more sense as organize imports is a file wide action (and will eventually be triggered on save) 

However we could also surface this as a code action to improve discoverability. I've opened https://github.com/Microsoft/TypeScript/issues/22909 to track this

**Comment by jrieken** [comment]
How is this upstream? It us surfacing the command and us to sell it - either as code action or as command?

The approach taken is wrong and reminds me of the formatting-via-command-story (not as provider)  for which we went great lengths to educate users. Now we set the same bad sample and even today things aren't working properly: in my install I have the Java extension which uses the same anti-pattern (mostly likely because code action weren't ready yet) and the assign keybinding *always* runs the Java-command, never the TypeScript command

<img width="712" alt="screen shot 2018-03-28 at 09 26 07" src="https://user-images.githubusercontent.com/1794099/38014795-25c98014-326a-11e8-8129-f5d09bfef110.png">

**Comment by jrieken** [comment]
> formatting-via-command-story (not as provider) for which we went great lengths to educate extension authors.

For reference - we [blogged about this](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices) and tracked down every single formatter-command-extension with issues/PRs

**Comment by mjbvz** [comment]
I’m still not convinced that code actions are the right ux. The intended usage of organize imports is very much like format in that it is independent of cursor position and run on the entire current document. And format—whether implemented using providers or actual commands—is a command from the user’s perspective.

I’ve already submitted a pr against java for this. I agree that having an organize imports command per lanague is not scalable but think we should look at other approaches, such as a new  provider type, if this ends up being a problem

**Comment by jrieken** [comment]
> I’m still not convinced that code actions are the right ux. The intended usage of organize imports is very much like format

Well, it will allow us to have something like `Context Menu > Refactor > Organise Imports`. I'd say that makes the feature way discoverable than the command palette with duplicate entries in which I need to scan language-prefixes (that hopefully exist, everybody could just call things 'Organise Imports'). 

> And format—whether implemented using providers or actual commands—is a command from the user’s perspective.

Yes - everything is a command even IntelliSense but the point of well-know-thanks-to-api-commands is better UX integration. Now we have picked the worst in the face of a generic code actions infrastructure that would allow for better UI. What don't we add a new code action kind which about 'sugar', e.g. Format, Sort Members, Organise Imports, Align Whitespaces, Insert Copyright Header, etc.?

**Comment by jrieken** [comment]
@johnnyreilly The lightbulb is controlled by the Omnisharp/C#-extension, so ultimately that must change. This issue is about show-casing how organise imports et all can be integrated into VS Code best. E.g. similar to how it is done in Eclipse (have a source and refactor menu)

<img width="928" alt="screen shot 2018-03-28 at 12 05 31" src="https://user-images.githubusercontent.com/1794099/38488378-9136d950-3be3-11e8-8cfb-8e541d2ad74a.png">
