### ISSUE TITLE
Memoize should only be used in functions with zero parameters

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46643]
![image](https://user-images.githubusercontent.com/900690/37958355-96b01c62-31b0-11e8-9f73-c4991665efb0.png)

From: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/browser/menuItemActionItem.ts#L53

**Comment by isidorn** [comment]
@bpasero I fixed the warning, however the ugly part remains that I have to depend on the contextMenuService to know when a user entered a context menu. I tried listening on a window global event "oncontextmenu" but that only gets fired inside the editor.
Hopefully async context menu will make my life easier

Basically all I want to know is if the alt is released while a context menu is shown.

**Comment by bpasero** [comment]
@isidorn if you want to play around with async context menu, the branch `tyriar/electron-2.0` has it all. Still I think you cannot rely on the DOM events here because we open a native context menu.
