### ISSUE TITLE
Improve look of modal info/warning/error messages

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#46646]
Modal dialogs are currently handed off to the OS:

<img width="586" alt="screen shot 2018-03-27 at 10 22 48" src="https://user-images.githubusercontent.com/1078012/37958613-e2121f8c-31a8-11e8-9af1-eae9826b9d20.png">

On Windows they look really bad.

It would be much better if they were styled like the notifications you get with `modal: false` and just appeared in the centre of the screen blocking access to what's behind.

**Comment by bpasero** [comment]
@DanTup you should report this issue to the OS you think the modal dialog looks bad if you think this can be improved. 

Closing, modal dialogs will not go away with some custom implementation anytime soon.

**Comment by DanTup** [comment]
I was advised to raise this https://github.com/Microsoft/vscode/issues/44122#issuecomment-376455082

The problem isn't that the OS dialogs are ugly, it's that they don't fit in with Code. Notifications look great if you set `modal:false` and totally different for `modal:true`. Since we won't be given an API to hide non-modal notifications we now have to decide between ugly disruptive modals, or notifications that hang around and can be incorrect/stale/misleading. Neither of these seem like a great option.
