### ISSUE TITLE
Modal message box when Auto Attach failed because process was terminated

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#46658]
1.22 insiders on Mac. Testing #46570.

- Enable Auto Attach
- Launch Node (v7.10.1) in debug mode: `node --inspect hello.js` with:
```js
setInterval(() => {
    console.log('hi!');
}, 1000);
```
- Quickly Ctrl+C the Node process
- After a while the below message is shown.

It would be better to detect that the process is gone before showing an error message for expected behavior.

![image](https://user-images.githubusercontent.com/9205389/37960870-03f97290-31b7-11e8-836d-5f00d296fbfe.png)

**Comment by chrmarti** [comment]
`node --inspect=foo hello.js` also triggers that dialog. It would make sense to not show the dialog in this case either. The user might simply have a typo on the command line and Node will complain and refuse to start.

**Comment by weinand** [comment]
Since the August 2018 release unsuccessful auto attach attempts are no longer shown.
