### ISSUE TITLE
Fold block comments doesn't work

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46653]
re #46597

* open `/src/vs/base/common/arrays.ts`
* select F1 > Fold Block Comments
* 🐛 block comments aren't folded

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/22732

**Comment by mjbvz** [comment]
Whoops, duplicated the wrong issue. This one is about  the `Fold Block comment command`

**Comment by mjbvz** [comment]
Fixed by e628e8e7b26ad628763671d1f4b6190ae6e7f9a4. Currently also requires a build from TS master. We will pick up a TS insiders with the fix tomorrow.
