### ISSUE TITLE
If I want to have a preselected item I need to provide a description

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#46657]
Tests #46587 

So far the simple single picker allowed me to have a list of single labels. If I want to have a pre-selected item this is not possible anymore since the `QuickPickItem` item type forces me to provide a description. We should either make the description optional or make a more complicated OR type which allows to have the description optional if `selected` true.

**Comment by chrmarti** [comment]
Good catch. We should make `QuickPickItem.description` optional. /fyi @jrieken
