### ISSUE TITLE
Can not fold multiline parenthesises

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46656]
re #46597 

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestController.ts#L91 uses the following pattern (which is quite common in our code base) which TS/JS folding doesn't support:

```ts
constructor(
		private _editor: ICodeEditor,
		@ICommandService private readonly _commandService: ICommandService,
		@IContextKeyService private readonly _contextKeyService: IContextKeyService,
		@IInstantiationService private readonly _instantiationService: IInstantiationService,
	) {
```

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/22915 to track this upstream
