### ISSUE TITLE
No hint that postDebugTask doesn't exist

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46659]
re #45305

* configure a post debug task that doesn't exist (mistype the name)
* debug till termintation
* 🐛 there is no hint that the post debug task didn't work (while we have something very prominent for pre debug task)

**Comment by isidorn** [comment]
This is a fair request, assigning to April to tackle then.

**Comment by weinand** [comment]
@why are you reporting a missing "preLaunchTask" differently (modal) than a "postDebugTask" (non-modal)?

**Comment by isidorn** [comment]
Because I felt like the `postDebugTask` is not something that is blocking. Your debug session start depends on `preDebugTask`, but nothing depends on `postDebugTask`. I can change it for consistency if you prefer that.

**Comment by weinand** [comment]
That explanation makes sense to me.
