### ISSUE TITLE
option to relaunch the build task

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode#4665]
- VSCode Version: 0.10.12 (git)
- OS Version: Arch Linux (4.4.5-1) amd64

I have a task to compile my go app and run it, however to restart the app I have to terminate it first then start it again.

Maybe add a "restart build task" option where it'd kill the current running task and start it again, or is that currently possible?

**Comment by isidorn** [comment]
As far as I understand there is not `launch.json` invovled here, you do not have `preLaunchTask` set, you are just launching a task from `tasks.json`.
Thus forwarding to @dbaeumer

**Comment by dbaeumer** [comment]
Dups #6578.

There is also a Restart Running Task action.
