### ISSUE TITLE
Multi select Quick-Pick: keyboard shortcuts to select and deselect all would be great

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#46665]
Tests #46587

Ctrl+A to select All. No good suggestion for deselect All. May be Ctrl+Shift+A.

**Comment by chrmarti** [comment]
That will work when the focus is on the list. When the focus is in the text field, I would expect Ctrl+A to select all text in the text field.

**Comment by dbaeumer** [comment]
Agree. Still short cuts for select / deselect all would be nice.
