### ISSUE TITLE
Auto Attach tricked by --debug-port / --inspect-port

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#46664]
1.22 insiders on Mac. Testing #46570.

Using `--debug-port` or `--inspect-port` without a corresponding `--inspect` or `--debug` tricks Auto Attach into trying to connect to the debug port although that port is not open.

**Comment by weinand** [comment]
The semantics of a standalone `--debug-port`or `--inspect-port` is to specify the debug port to use when the running node process is brought into debug mode via the SIGUSR1 signal. 

So the issue was that the SIGUSR1 signal was not sent.

**Comment by weinand** [comment]
fixed with https://github.com/Microsoft/vscode-node-debug/commit/352bd30c5957f87444e225835bc82389666be2b0

**Comment by chrmarti** [comment]
It now complains that it can not put the process in debug mode. (Node v8.9.4, v7.10.1, v9.10.0)

![image](https://user-images.githubusercontent.com/9205389/38083734-c30e0bf2-334a-11e8-9e6f-9a610684658e.png)

**Comment by weinand** [comment]
I had fixed this issue for the "Attach to Node Process" action instead of "Auto Attach"...
Applied same fix here.
