### ISSUE TITLE
Multi Quick-Pick: bad performance with many items

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#46666]
Tests #46587

- create a list with 9999 items all preselected
- open the list
- unselect all. This takes seconds :-)
- same for select all.

**Comment by dbaeumer** [comment]
The performance is also very bad when filtering the list by typing into the text field especially if the provided filter matches many items.

**Comment by Tyriar** [comment]
I also hit this. I notice that a full search is happening even when you could just filter on the existing results (narrowing the search by adding a char to the start or end).

**Comment by gushuro** [comment]
Just ran across this as well. 50k items + click on select all --> vscode crashes.
