### ISSUE TITLE
Allow to ask for input in the context of an editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#46660]
When implementing code actions the need to ask for and validate input often arises - we have a custom UI solution for rename with the inplace-input-field. We have something similar for showing messages in context (e.g. hit F12 on a keyword in a TS file). Extensions cannot use these widgets and are stuck with `showInputBox` and the `showXYZMessage`-functions. That's undesirable and leads to various workarounds. I believe we should expose (improved) versions of the inplace-inpute/messages to extensions for an overall better experience in the area of code actions.

/cc @DanTup

**Comment by jrieken** [comment]
One idea is to improve the existing `showInputBox`-function. The `InputBoxOptions` could optionally specify an editor and range. That would be minimal API but still support validation, in context UI, etc

**Comment by DanTup** [comment]
@jrieken This is a great idea, but will you let me invoke my own code when the user hits `F2` so I can use it for renames?

**Comment by jrieken** [comment]
No, rename is its separate flow. This is for things like rewriting imports et al

**Comment by DanTup** [comment]
@jrieken Ok, at the moment I wouldn't be able to use this, as I can't tell the difference. My language server exposes rename functionality that handles things like `class` but I can't (reliably, without hacks) tell when that's the case (or send a request to find out whether it would be valid to show an "add alias for import"/whatever fix).
