### ISSUE TITLE
Post debug task runs too early

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46677]
#re #45305

* have the below configuration (hello world extension)
* hit F5
* 🐛 the postDebugTask runs while the debuggee is still open/running

<img width="1133" alt="screen shot 2018-03-27 at 14 21 35" src="https://user-images.githubusercontent.com/1794099/37966951-2eea1172-31ca-11e8-93db-0d16e9af9f17.png">

**Comment by sandy081** [comment]
I see this too on Mac

**Comment by isidorn** [comment]
Good catch but dup of https://github.com/Microsoft/vscode/issues/45741
