### ISSUE TITLE
Allow to temporarily or permanently disable (snooze) all notifications

### ISSUE THREAD

**Issue by Adiqq** [microsoft/vscode#46676]
Hi!

I have a suggestion for feature that would sometimes be useful.
Option to temporarily easily disable all notification, e.g. I have to edit configuration in many projects, but if I open .NET Core project, it notifies me about restoring dependencies, which don't really interest me in this use case.

**Comment by satyapramodh** [comment]
+1 i am just getting started with a project and that means i am reading through a lot of code. i keep getting distracted by notifications on each new file i open. like some autoformatter wants to install. i dont currently need those in this session and i wish we had an ability to disable notifications for x hours or this session

**Comment by tigoe** [comment]
+1 for this. Notification toasts are not often usable by screen readers, in particular VoiceOver on the MacOS, and get in the way of getting things done.

**Comment by babakness** [comment]
How to hack this temporarily; cmd-p, enter '> developer'  choose 'toggle developer tools'. Chrome inspector opens. To disable all toasts set the style `.notifications-toasts` to `display: none`.

**Comment by rightfold** [comment]
In addition to temporarily disabling them it should also be possible to permanently disable them, via a setting in settings.json.

**Comment by sherief** [comment]
I would be fine with Clippy coming back if I get the ability to disable notifications because if I took a shot for every distracting notification I had to dismiss I'd be, well, dead by now (and it's only around 2 PM).

**Comment by QGB** [comment]
> .notifications-toasts

Array.from(document.querySelectorAll('.notifications-toasts'))
    .forEach(function(val) {
        val.style.display = 'none';
});

**Comment by QGB** [comment]
.notifications-toasts{
	display:none;
}

**Comment by babakks** [comment]
@QGB Sorry, but you should mention @babakness. 😎👍

**Comment by worldbeater** [comment]
An option to completely disable all those notifications would be highly appreciated. Sometimes I just want to read Visual Studio Code's terminal output, and those guys always irritate me saying `boo hoo there is an extension for this file`, or something else. I don't care what they say, completely. Most time I just want to parse the terminal output while editing files, without getting disturbed. It is nice to have the ability to apply a workaround like `display: none;`, but... Seriously?

**Comment by zwhitchcox** [comment]
So, I'd like to add I think a good approach would be to allow the user to just disable the "popup" feature of notification, which is the most annoying, and make the notification bell more prominent.

Right now, you wouldn't really notice that you have a notification, but maybe when you get a notification, it could blink and then the little dot that indicates a notification could be yellow, so you could easily visually see that you have notifications.

And sometimes you get notifications, and you know what they are going to be, so you wouldn't look when you get one of those, but other times you could just click on the notification bell and see your notifications.

But this would just be an option, the standard behavior could function as is.

**Comment by atheaos** [comment]
> then the little dot that indicates a notification could be yellow, so you could easily visually see that you have notifications.

That is a good idea. It could go into the Activity Bar that already has those highlights/counters, and it would be appropriate because most notification are asking for activity.

**Comment by ameltzerMSFT** [comment]
Sometimes I open large projects because VSCode makes it really easy to explore and consume them and then I have to deal with a constant barrage of notifications telling me something is wrong. I just want it to shut up and leave me alone so I can concentrate on the the problem I'm trying to solve. All the distractions and interruptions are simply not relevant to what I'm trying to do, and all they are doing is making my job harder. 

Applications these days are simply too noisy and constantly asking for attention, especially when it's not entirely necessary.

**Comment by shu-ming** [comment]
the notifications are really annoying

**Comment by RussKie** [comment]
I'm building a solution in a terminal... Like, seriously????
![vscode-popup](https://user-images.githubusercontent.com/4403806/123880559-45832600-d986-11eb-901d-829857c37f26.gif)

**Comment by ameltzerMSFT** [comment]
Almost 4 years later and this is still an issue. :(

**Comment by satyapramodh** [comment]
Idea: a notification central where all current and previous notifications exist per project. now u can snooze notifications per session or for x hours or forever for each project and can always go to the notification central page and manage each when you have the time. This would be really ideal.

**Comment by Lantianyou** [comment]
I cannot believe this is still an issue

**Comment by itsdmd** [comment]
Just copy-paste the notification disable option you have for Zen Mode to normal mode and boom, everyone is happy. How can it be more simple than that?

**Comment by DanielFredriksson** [comment]
Bump. Please add a setting to disable these.

**Comment by itsdmd** [comment]
I'm still waiting for this simple patch.

**Comment by HadesArchitect** [comment]
Bump.

**Comment by BrentBoyMeBob** [comment]
Bump. I'm using vscode.dev as an editor for my companion Chromebook Duet with 16 different extensions (including an Emacs keymap), and as such, errors are prone to happen since the editor is more gimped and isn't native, but they appear REALLY OFTEN. It gets annoying to the point that it completely distracts me, even if they are mostly minor errors that do not hinder the experience.

Sucks that it's been 4 years and this is still not addressed.

**Comment by joshkg** [comment]
bump!

**Comment by EmperorEarth** [comment]
Ironically, decision makers were able to mute this thread's notifications.

**Comment by AndyJado** [comment]
bump!

**Comment by sztomi** [comment]
I'm having the same problem. Many notifications have a "don't show again" button that unfortunately doesn't seem to function.

**Comment by Adiqq** [comment]
For anyone still interested in solution, seems like there's finally Do Not Disturb mode: https://github.com/microsoft/vscode/issues/144324 , https://code.visualstudio.com/updates/v1_69#_do-not-disturb-mode
