### ISSUE TITLE
Changing language mode of a file does not persist

### ISSUE THREAD

**Issue by csreddy** [Microsoft/vscode#4667]
- VSCode Version:   0.10.11 
- OS Version: OSX El Capitan 10.11.3 (15D21)

Steps to Reproduce:
(I have files with .sjs extension which need to treated as Javascript)
1. Switch language mode of a file to different language 
2. Go to a different file
3. Come back to previous file, the language is reset

**Comment by Tyriar** [comment]
You can add an extension to a colorizer by following these instructions: https://code.visualstudio.com/docs/customization/colorizer#_common-questions

**Comment by Tyriar** [comment]
This is a nicer way of doing it and is coming in the March release https://github.com/Microsoft/vscode/issues/3612

You can see this in action in the insiders build http://code.visualstudio.com/Download

**Comment by csreddy** [comment]
Cool, thanks. Looking forward to it.
