### ISSUE TITLE
"convert to a ES6 module" code action doesn't preserve type of quotes

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#46679]
testing #46596:

- create file.js with this contents:
  ```
  var path = require('path');
  ```
- execute the code action to convert this into a ES6 module.

Observe: the resulting `import path from "path";` uses different quotes than the original require.

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/22921 to track this upstream
