### ISSUE TITLE
Run organise imports on save

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46678]
re #46589

It should be possible to configure organise import (read code actions in general) so that they run on save.

**Comment by mjbvz** [comment]
Yes, currently the feature is not reliable enough for me to feel confident triggering it on save but next iteration we should hook this up

**Comment by mjbvz** [comment]
Depends on #42092

**Comment by uloco** [comment]
A better option imho would be to make it configurable to be run when formatting, rather than on save. At least I would expect auto format to handle such things, rather a file save...

**Comment by mjbvz** [comment]
Enabled by #48086,

```json
	"editor.codeActionsOnSave": {
		"source.organizeImports": true
	}
```

This is not enable by default currently
