### ISSUE TITLE
Add onClick event to QuickPickItem

### ISSUE THREAD

**Issue by grzegorzjudas** [Microsoft/vscode#46673]
- VSCode Version: 1.20.0
- OS Version: MacOS Sierra 10.12.6

It seems there's currently no way to pass click event for QuickPickItem elements. The only event there is is onDidSelect, which triggers every time selection changes - but that's not what I'm after.

Looks like such basic usecase I'm really surprised it's not implemented already.

**Comment by jrieken** [comment]
Not really sure what you mean because clicking an item terminates quick pick and returns the 'clicked'-item.

**Comment by grzegorzjudas** [comment]
Ah, I just discovered that showQuickPick returns a promise... Nevermind me 👍 thanks for support!
