### ISSUE TITLE
Organise Imports should use resolved paths

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46681]
re #46589

* running TypeScript 2.9dev20180327
* run organise imports on https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostTypeConverters.ts#L24
* 🐛 the sorting happens on the path literals and not on the actual path

<img width="977" alt="screen shot 2018-03-27 at 14 36 33" src="https://user-images.githubusercontent.com/1794099/37967788-ab2b7076-31cc-11e8-8149-984bfdeb3969.png">

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#22926
