### ISSUE TITLE
Attach to port doesn't show port

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#46685]
Testing #46582

elementary OS 0.4.1 Loki
Built on "Ubuntu 16.04.2 LTS"

node v8.9.1

- create foo.js
```js
setInterval(() => {
    console.log('ssss');
}, 1000);
```
- in the integrated terminal run 
`node --inspect ./foo.js` and `node --inspect=5445 ./foo.js`
- add a launch config
```
		{
			"type": "node",
			"request": "attach",
			"name": "Attach to Process via pid or port",
			"processId": "${command:PickProcess}"
		  }
```
- launch the launch config

Dialog shows:
![image](https://user-images.githubusercontent.com/6461412/37969627-8477931a-31d1-11e8-8e26-2c1b9488afbc.png)

-> no port is shown

**Comment by weinand** [comment]
fixed by https://github.com/Microsoft/vscode-node-debug/commit/a4a2e1c89a4ba5bd654b8c80432294e9be71640e

![2018-03-27_16-19-26](https://user-images.githubusercontent.com/1898161/37973401-ab0de890-31da-11e8-8e02-fdbb18142a8e.png)
