### ISSUE TITLE
Unatendet changed char in comment 

### ISSUE THREAD

**Issue by jafkuijpers** [Microsoft/vscode#46680]
Issue Type: <b>Bug</b>

When I modify and save a file it modifies charaters unattendent e.g. Daniël is changed into  Dani�l what is not correct (even if it inside a comment).

I do not know if it is related to an extention.

Regards Jeroen

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|Memory (System)|15.96GB (5.57GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
xml|Dot|1.9.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.15.0
csharp|ms-|1.14.0

</details>
Reproduces only with extensions

**Comment by dbaeumer** [comment]
@jafkuijpers have you set the correct Encoding for that file. There is an encoding switcher in the status bar in the lower right corner.

**Comment by dbaeumer** [comment]
@alexandrudima starting with you since the character got rendered correctly in the first place.

**Comment by bpasero** [comment]
@jafkuijpers 
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
