### ISSUE TITLE
postDebugTask is not called when the debug session is stopped

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#46688]
Testing #45305

- Clone vscode smoke test repo
- Create following task
```json
{
            "label": "start",
            "type": "shell",
            "command": "say start",
            "identifier": "start"
        }
```
- Add the above task as `postDebugTask` to the launch `Launch Program`
- Start Debugging and Stop Debugging

Post debug task `start` is not executed

**Comment by isidorn** [comment]
This works fine for me
What happens if you simply run the task via Run Task command?
On what platform are you? Can you reproduce always?

![screen shot 2018-03-27 at 15 32 23](https://user-images.githubusercontent.com/1926584/37970599-28cf3b28-31d4-11e8-8285-fd67a82a5ecc.png)

**Comment by sandy081** [comment]
> What happens if you simply run the task via Run Task command?
Works for me

> On what platform are you? 
Mac

> Can you reproduce always?
Yes

> Are you doing something special?
I do not think so. I also tried debugging a simple JS file and it didn't work for me

**Comment by isidorn** [comment]
@sandy081 can you please put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L1001) and let me know if it gets hit?
Or ping me when we can skype call so I debug this on your machine since I can not repro.

**Comment by sandy081** [comment]
Sure. Will ping you tomorrow

**Comment by sandy081** [comment]
Assigning myself and to March for investigation tomorrow

**Comment by isidorn** [comment]
This is happening because the VS live share extension seems to overwrite the launch.json and remove the postDebugTask from it.
VS Live share extension should respect the `postDebugTask` and not remove it

@rodrigovaras can you please open a VS live share issues so you can track this please.

**Comment by isidorn** [comment]
@rodrigovaras actually I just filed https://github.com/Microsoft/vscode-cascade/issues/60

**Comment by lostintangent** [comment]
@sandy081 This has been resolved in the latest Live Share extension release. Let us know if this repros after you update. Thanks again for reporting it!
