### ISSUE TITLE
User markdown-it or remarkable to replace marked for markdown render

### ISSUE THREAD

**Issue by Treri** [Microsoft/vscode#4668]
Should we use [markdown-it](https://github.com/markdown-it/markdown-it) or [remarkable](https://github.com/jonschlinkert/remarkable) to replace marked for markdown preview?

It seems that marked had beed dead for a long time(see [issue](https://github.com/chjj/marked/issues/724)), and many issues and PRs are not responsed.

From above issue, it seems that markdown-it is better than remarkable. see [here](https://github.com/markdown-it/markdown-it#authors)

Such as, marked now not support table in lists, but markdown-it and remarkable does.

**Comment by bpasero** [comment]
:+1: , we should look into this when we make markdown a real extension.

**Comment by jrieken** [comment]
This will happen with #7656
