### ISSUE TITLE
Organise Import should differentiate between files and folders

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46684]
re #46589

* running TypeScript 2.9dev20180327
* run organise imports on https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostExtensionActivator.ts#L7
* 🐛 imports to `vs/nls` (file) and `vs/base/...` (folder) are treated equal so that `vs/nls` is mixed in-between `vs/base/...` and `vs/workbench/...`

**Comment by mjbvz** [comment]
Opened discussion upstream: https://github.com/Microsoft/TypeScript/issues/22911
