### ISSUE TITLE
Organise imports creates many blank lines

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46683]
re #46589

* running TypeScript 2.9dev20180327
* run organise imports on https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostTask.ts#L26
* :bug: there are now four blank lines below the imports

<img width="472" alt="screen shot 2018-03-27 at 14 45 53" src="https://user-images.githubusercontent.com/1794099/37968106-8f7bf962-31cd-11e8-9649-d7f10550b9b1.png">

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/22914 to track this upstream
