### ISSUE TITLE
Cannot open file with \ in name on Linux

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#46686]
Testing #46328

* create a file with a `\\` in the name, e.g. `echo hi>hi\\a.txt`
* this will create a file called `hi\a.txt`
* the file is presented as `a.txt` in the explorer and it cannot be opened

![image](https://user-images.githubusercontent.com/5047891/37969549-5022f64a-31d1-11e8-9661-15bc13f5ddd5.png)

**Comment by bpasero** [comment]
Very likely an issue with using `path.join` and that method normalizing the slashes/backslashes. I dont think we ever supported that.

**Comment by isidorn** [comment]
Yeah I will double check with stable, if it is not working will push it out of march. Thanks

**Comment by bpasero** [comment]
Possibly related: https://github.com/Microsoft/vscode/issues/22899

**Comment by isidorn** [comment]
Unfortunetely did not have time to look deeper into this one. Pushing out to april since it feels like a corner case.
@bpasero if you have time tomorrow maybe give it a look, thanks

**Comment by bpasero** [comment]
@isidorn its imho fine to push out as it is not a regression as far as I know.
