### ISSUE TITLE
Slow typing in a large file where the content got copied from a clipboard

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#46694]
Steps:

- Get a large file (mine was 500000 lines). I created it using https://www.json-generator.com/ by repeating 10000 times.
- In the web copy to clipboard
- create a new text file in VS Code
- paste the content
- start typing at the beginning.

Observer: typing is slow

If you close the file and reopen it typing speed is normal.

**Comment by rebornix** [comment]
@dbaeumer nice catch, thank you!

The lag is caused by following code paths

* As it's JSON file, we will run bracket matching against the whole content, which would take hundreds of ms in this case
* While we build the undo/redo stack, we tried to access the changed buffer, which is tens of MB in this case , operations on such a string is slow.

**Comment by dbaeumer** [comment]
Just to clarify: I say the slowdown as well when I pasted the file into a buffer that had plain text language. So it is unrelated to the JSON language service.

**Comment by alexandrudima** [comment]
@rebornix The slowdown is in typing (not bracket matching or undoing) when typing in a file which starts empty and contains a single very very large insert string. JavaScript's `substring` is slow on the very very large string.

Processing a keystroke takes sometimes more than 100ms
![image](https://user-images.githubusercontent.com/5047891/38020845-972df648-327b-11e8-8c6f-7895b85341de.png)
[CPU-20180328T113151.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1855331/CPU-20180328T113151.cpuprofile.zip)

---

A bit easier steps
1. Create a file called `new.txt`
2. In a different software, open the attached file and select all and copy:
[large.txt.zip](https://github.com/Microsoft/vscode/files/1855332/large.txt.zip)
3. In VSCode, paste in the `new.txt` file
4. In VSCode, start typing.

Observe the insane lag:
![kapture 2018-03-28 at 11 35 35](https://user-images.githubusercontent.com/5047891/38021065-2c5e8ba6-327c-11e8-86e1-576560f85ef3.gif)

**I suggest we workaround this v8 weirdness by breaking up a very very large insert string into multiple pieces.**

**Comment by rebornix** [comment]
Now large content will be splitted to small chunks like what we did with file loading.

**Comment by dbaeumer** [comment]
I tried to verify from source and it still feels lagggy. @alexandrudima can you give it a try as well.

**Comment by alexandrudima** [comment]
@dbaeumer I could still feel lagging. But it is not caused by the text buffer anymore (typing takes <2ms for me). It is caused by the suggest contribution sorting word suggestions. I have created #46930 to track that.
