### ISSUE TITLE
TextDocument.setText

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#4669]
There is a `TextDocument.getText()` method but there isn't a `TextDocument.setText()` method. The reason I (think) need this is for my [final-newline](https://github.com/SamVerschueren/vscode-final-newline) extension. It adds a final newline when the page is saved. But if the user presses `Save All` from the menus, it doesn't work because it only performs the action on the current active text editor document.

I listen to the `onDidSaveTextDocument`, which calls a listener with the `TextDocument` as parameter. From there on I can get the text, save the document, etc. but I cannot manipulate the document. Is this something that should be done differently?

**Comment by jrieken** [comment]
You can only edit a `TextDocument` with an editor and its `edit`-method. Today there is no `onWillSaveTextDocument` event, so you could use the [`visibleTextEditors`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2908) or `onDidChangeActiveTextEditor `

**Comment by felixfbecker** [comment]
editorconfig already has this implemented (insert final new line)

**Comment by SamVerschueren** [comment]
I know, I'm core contributor of the EditorConfig plugin but my plugin was created when extensions were still closed beta. And it seems that still some people prefer to not have a config file for this feature.
