### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by twajr** [Microsoft/vscode#46691]
- VSCode Version: 1.21.1
- OS Version: Windows 10 Enterprise - 1709

Steps to Reproduce:

1. Install VSCode on Windows 10 Enterprise
2. Launch It

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2207 Extension host terminated unexpectedly.
e.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2207

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@twajr can you provide the log of the Extension Host. Go to Output > Channel Log (Extension Host)

**Comment by twajr** [comment]
[2018-03-28 07:16:03.430] [exthost1] [info] extension host started
[2018-03-28 07:16:03.507] [exthost1] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2018-03-28 07:16:03.508] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet\out\extension
[2018-03-28 07:16:03.807] [exthost1] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2018-03-28 07:16:03.807] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\git\out\main
[2018-03-28 07:16:04.234] [exthost1] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2018-03-28 07:16:04.234] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict\out\extension
[2018-03-28 07:16:04.309] [exthost1] [info] eager extensions activated

**Comment by twajr** [comment]
![image](https://user-images.githubusercontent.com/29104218/38028994-39b7d14e-325a-11e8-9d6c-fc2a7ebb3f79.png)

**Comment by dbaeumer** [comment]
@twajr these exception don't explain why the extension host should crash and they are all generated by extensions. In the description you said it occurs even if all extensions are disabled. Is this true? If not could you try to find out which one causes the crash.

**Comment by twajr** [comment]
It DOES occur with extensions disabled. If I launch via: code --disable-extensions

I get the exact error shown above. Does the above NOT disable extensions as it says?

![image](https://user-images.githubusercontent.com/29104218/38051616-731df460-3294-11e8-8c90-b9e688f152f9.png)

**Comment by twajr** [comment]
Another way to verify:
![image](https://user-images.githubusercontent.com/29104218/38052099-bb4e9874-3295-11e8-8d29-023e3717c359.png)

**Comment by dbaeumer** [comment]
@twajr I misinterpreted the screen shots in https://github.com/Microsoft/vscode/issues/46691#issuecomment-376869954.

**Comment by dbaeumer** [comment]
@alexandrudima moving to you the interesting stuff is in comment https://github.com/Microsoft/vscode/issues/46691#issuecomment-377007516

**Comment by alexandrudima** [comment]
@twajr We are using named pipes for communicating between processes. Perhaps something is broken in this environment (i.e. named pipes get closed by some security policy?). The only real error you caught was about "Channel has been closed", so that's what makes me think named pipes might be broken.

To check if the renderer process can communicate with the extension host process, you can use `code --disable-extensions --logExtensionHostCommunication` and attach the developer tools output.

**Comment by twajr** [comment]
@dbaeumer, @alexandrudima , Thanks for the help on this. It's probably true about some sort of security issue as they have us using BeyondTrust to 'launch elevated' to get access to things. No real admin access on the machine, etc. 

I'm attaching what I think you're asking for:

 WARN Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:    24] Array(24)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:    25] Array(25)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:     1] Array(1)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:     9] Array(9)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:     9] Array(9)0: "{"type":3,"id":"25"}"1: "{"type":3,"id":"26"}"2: "{"type":3,"id":"27"}"3: "{"type":3,"id":"28"}"4: "{"type":3,"id":"29"}"5: "{"type":3,"id":"30"}"6: "{"type":3,"id":"31"}"7: "{"type":3,"id":"32"}"8: "{"type":3,"id":"33"}"length: 9__proto__: Array(0)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:    63] Array(63)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:    61] Array(61)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:     1] Array(1)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:     7] Array(7)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:     7] Array(7)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:    56] Array(56)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:    56] Array(56)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:     1] Array(1)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:     1] Array(1)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:     1] Array(1)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:     2] Array(2)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:     2] Array(2)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:     2] Array(2)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:     2] Array(2)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:   110] Array(110)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:   110] Array(110)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Extension → Window][len:    13] Array(13)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:    13] Array(13)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2831 [Window → Extension][len:     1] Array(1)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2830 Extension host terminated unexpectedly. Code:  0  Signal:  null
O._onExtensionHostCrashed @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2830
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2207 Extension host terminated unexpectedly.
e.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2207

**Comment by alexandrudima** [comment]
This last trace shows that the renderer and the extension host are initially communicating properly, until, at one point, the extension host decides to crash.

Given that, I wonder if any of the built-in extensions that eagerly activate are somehow causing the crash. From your [log](https://github.com/Microsoft/vscode/issues/46691#issuecomment-376867803), here are the extensions that are built-in and are eager activated:
* vscode.emmet
* vscode.git
* vscode.merge-conflict

Could you launch `code --disable-extensions`, and then disable these built-in extensions via the Extensions viewlet, then on the 3 dots, Show Built-in Extensions and then for each one Disable:
- Emmet - Emmet support for VS Code
- Git - Git SCM integration
- Merge Conflict - Highlighting and commands ...

Then, restart the window. I would put my money on Git, as it will try to spawn git processes...

**Comment by twajr** [comment]
Hmmm, okay, and I did install GIT-for-Windows early on so I agree with  you. I did try a few things around git, but didn't make any progress. Here's my current issue. Even though I'm launching 'elevated' I do not have the ability to enable or disable extensions, all options are grayed out.

**Comment by alexandrudima** [comment]
@sandy081 Why would the disable buttons be grayed out?

**Comment by sandy081** [comment]
Enablement actions are not enabled when started with `--disable-extensions`. It used to be the behaviour before supporting enabling/disabling extensions. This should be changed for built in extensions.

**Comment by sandy081** [comment]
As a workaround user can try disable all installed extensions action in the extensions view and disable the built in extensions.

**Note**: This will change the disablement state of all extensions and after enabling all, user have to manually disable those extensions which he/she had before disabling all.

**Comment by twajr** [comment]
Okay, there is no 'disable built in extensions' I tried 'disable installed extensions' but that had no effect, as it only affects the two I have installed that aren't the issue.

**Comment by twajr** [comment]
@alexandrudima So, are we giving up?

**Comment by sandy081** [comment]
@twajr Did you tried 
- disabling all installed extensions from extensions view
- reload
- open extensions viewlet and  show built in extensions
- disable git extension
- reload

**Comment by twajr** [comment]
@sandy081 Yes, behavior is the same:
![image](https://user-images.githubusercontent.com/29104218/38308230-08777d1e-37dc-11e8-8d92-eda0d3e95900.png)

**Comment by twajr** [comment]
It took awhile, but I have now disabled ALL built-in extensions (only Themes remain), and problem is exactly the same.

**Comment by twajr** [comment]
@alexandrudima  Thanks, agree, I'm about to call it as well. Did get an exception in debugger but that directory doesn't even exist. I guess I can keep debugging...
![image](https://user-images.githubusercontent.com/29104218/38376111-7c31bd28-38bd-11e8-89a3-6172f4509a8f.png)

**Comment by twajr** [comment]
@alexandrudima The debugger reports lots of exceptions, some about directories not existing, some about files already existing, etc. It's not easy for me to tell what is 'interesting', so I'm done. Thanks for trying. Most software issues are 'environmental'... Logging should at least point to a root cause, IMO.

**Comment by antarzerrougui** [comment]
hello. i have this issue even after fresh installation of the lastest vs code.
any idea.
i am on windows 10.
![capture](https://user-images.githubusercontent.com/23158121/39080042-b16f5ea6-451e-11e8-99b6-59d889d159d8.JPG)
