### ISSUE TITLE
Command 'TypeScript: Organize Imports' resulted in an error.

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46698]
#46589

OS X

1. vscode repo, open `modes.ts`
2. Delete the `{ IMarkerData }` import
3. Trigger Organize imports command -> you get an error

If I bring back the import removed in step 2 everything works fine

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/22924 to track this upstream
