### ISSUE TITLE
尚無安裝適用於 'php' 檔案的格式器

### ISSUE THREAD

**Issue by kanneg881** [Microsoft/vscode#46692]
Issue Type: <b>Bug</b>

please help me why I coudn't format with alt + shift + F
The issue has happened in install editorconfig plugin.
I have already removed editorconfig  plugin still not working.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|Memory (System)|14.91GB (11.66GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.2
php-intellisense|fel|2.3.0
php-pack|fel|1.0.1
composer|ika|0.7.1
phpcs|ika|1.0.5

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
VS Code doesn't support PHP formatting out of the box, you will have to use an extension.
