### ISSUE TITLE
Copy and copy message have no effect on related diagnostics

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46707]
Refs: #46564

1. Clone my related diagnostic extensoin from https://github.com/isidorn/diagnostics
2. Run the hello world command to activate the extension and open some editors
3. Try the Copy or the Copy Message context menu actions on related diagnostics -> they have no effect

I would expect these messages to behave simlar to when they are executed on the main diagnostic, just scoped to the related diagnostic. If that is not possible they should at least be disabled

fyi @jrieken

**Comment by sandy081** [comment]
Copy and Copy message actions are meant for main diagnostics only. These being shown was a bug  #46307 and got fixed.

I will introduce it If users want a copy action on the related diagnostics

**Comment by sandy081** [comment]
Reconsidering

- Copy action on main diagnostic will copy the complete diagnostic
- Show a copy message action on related diagnostic
