### ISSUE TITLE
editor.mouseWheelScrollSensitivity set as 0 will disable scrolling completely

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#46702]
https://github.com/Microsoft/vscode/issues/46578

We should probably only allow values > 0

Related: https://github.com/Microsoft/vscode-sublime-importer/issues/14

**Comment by alexandrudima** [comment]
Values < 0 are often used to simulate an OS feature, namely inversed scrolling. So I suppose we could ignore just the value 0.
