### ISSUE TITLE
Organize imports not connected with auto import

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46700]
Refs: #46589

I feel like the organize imports is disconnected from auto import which is a code action.
Also the organize imports does not auto import. Why is that? I feel like this should at least be configurable such that I have one action which I can always run which just does everything

**Comment by mjbvz** [comment]
Do you mean the `add missing imports` quick fix? This often requires user import to select which import you intended

**Comment by isidorn** [comment]
@mjbvz aha I understand, and then it becomes cumbersome if there are a lot of impots, thus you can not do this for all.

Still I feel like my first statement holds, and that these two actions are very connected in what they do but live in completely different places. Not sure how to bring them together but that would be a UX discussion.

**Comment by mjbvz** [comment]
Closing for now. If you have any specific ideas about how we can make these two more connected, please let me know
