### ISSUE TITLE
[folding] Fold all comments in a file

### ISSUE THREAD

**Issue by DeadEye0112** [Microsoft/vscode#4670]
I'd like to be able to fold all the comments in a file with a shortcut, something like `editor.foldAllComments`.
This is probably linked to this issue : [folding] language-aware folding #3422

The idea, is to make it easier to transform a file like this :
![2016-03-25 at 10 26](https://cloud.githubusercontent.com/assets/11258498/14041732/0e4db802-f274-11e5-8de9-1ee7d977f1cc.png)
To this :
![2016-03-25 at 10 27](https://cloud.githubusercontent.com/assets/11258498/14041751/30ba7c4a-f274-11e5-98c4-44113866288d.png)

**Comment by aeschli** [comment]
To implement what you suggest we would have to get an understanding on what a comment is.
#3422 is the first step for this.
