### ISSUE TITLE
Diagnostic could show a number of related diagnostics

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46710]
Refs: #46564

1. Clone my related diagnostic extension from https://github.com/isidorn/diagnostics
2. Run the hello world command to activate the extension and open some editors
3. Notice that the Problems panels show how many errors there are, then each file shows how many errors it has. To follow this logic I would expect that every diagnostics shows how many related diagnotics it has (if this number is greter than zero)

![screen shot 2018-03-27 at 16 30 29](https://user-images.githubusercontent.com/1926584/37974057-2c6e32fe-31dc-11e8-8f56-5cc35061338d.png)

fyi @jrieken

**Comment by jrieken** [comment]
unsure...

**Comment by sandy081** [comment]
Showing number of problems in each file is helpful whereas for related information I think it does not. I would wait to see how this feature will be implemented by users in different languages and revisit if the number makes sense.
