### ISSUE TITLE
Related information hover message background should not differ

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46713]
Refs: #46564

I like that the relatedInformation message has a nice different verbatim font and that makes it differ well enough, I suggest to not use a different background as imho the effect does not look that nice and we do not do it anywhere else to my knowledge. Also in the F8 we do not use a special background

![screen shot 2018-03-27 at 16 37 43](https://user-images.githubusercontent.com/1926584/37974439-3b4ca002-31dd-11e8-9e40-64dfe07c1754.png)

**Comment by jrieken** [comment]
Yeah, it's the default rendering we have for markdown. Not sure I have change that without making people sad...

**Comment by ramya-rao-a** [comment]
Also, the bullets do not appear in the Problems pane or when F8. Why have them here?
