### ISSUE TITLE
search.exclude does not work for searching symbols across a workspace

### ISSUE THREAD

**Issue by imdadahad** [microsoft/vscode#46718]
- VSCode Version: Code Insiders Version 1.22.0-insider (1.22.0-insider)

Steps to Reproduce:

1. Open a javascript project with a node_modules folder (couple packages installed)
2. Search for a symbol across the project
3. It will show results from the `node_modules` directory even if you have added the following your user/workspace settings:

```
"**/node_modules": true,
"node_modules": true
```

**Comment by roblourens** [comment]
Is the "Use Exclude Settings and Ignore Files" button toggled on? (bottom right)

![image](https://user-images.githubusercontent.com/323878/37785522-9b4d3162-2db7-11e8-9011-5ca513e789b9.png)

**Comment by imdadahad** [comment]
This is related to the Symbol search option (https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name), not the find in all files as you've shown above.

1.

![image](https://user-images.githubusercontent.com/5855115/38043982-6137453c-32b0-11e8-9895-c33f65c27cad.png)

2.

![image](https://user-images.githubusercontent.com/5855115/38043989-690ff59c-32b0-11e8-8917-11e9ff4f9435.png)

As shown it seems to retrieve results from `node_modules` despite having included the following in `search.exclude`:

```
"**/node_modules": true,
"node_modules": true
```

**Comment by roblourens** [comment]
Those settings don't impact symbol search. Not sure whether symbol search is supposed to include node_modules stuff

**Comment by imdadahad** [comment]
Oh really, would've thought anything that included `node_modules` would raise alarm bells given that indexing that folder is super slow. It would explain why it's noticeably slower to search for a symbol compared to Sublime.

**Comment by mjbvz** [comment]
@imdadahad Do you have a [jsconfig.json file](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson)? If not, try creating a simple one at the root of your project:

```json
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by imdadahad** [comment]
Yes, I have this already.

**Comment by garyking** [comment]
Per my issue at #47918, does your workspace file have a space in it?

**Comment by priezz** [comment]
I have exactly the same issue. Results from 'node_modules' are shown when doing the symbol search. How to exclude specific directories?

**Comment by imdadahad** [comment]
Any update on this, curious to know whether it's an actual bug/issue with config maybe?

**Comment by dkozickis** [comment]
Any update please?
Same behavior on VSCode 1.28.2 / Windows 7

**Comment by bernatfortet** [comment]
Any updates on this?
Searching workspace symbols is an amazing feature but seeing all the stuff from node_modules makes it less usable.

Thanks!

**Comment by dkozickis** [comment]
@mjbvz @roblourens 

A kind ping/reminder - if you could have a look and provide direction/comment?

**Comment by roblourens** [comment]
Sorry I don't know what the intent is or whether this has been considered, @mjbvz?

**Comment by dkozickis** [comment]
A kind ping @mjbvz :)

**Comment by mjbvz** [comment]
@roblourens I feel workspace search should probably respect `search.exclude` but I don't think TS should be the one to determine this. If we to enable this, one option is to:

* Make VS Code filter the returned results.
* And also encourage providers to consult the `search.exclude` so that they don't return results that will be filtered out

**Comment by roblourens** [comment]
Yeah if there is a max result count, then the provider definitely has to do the filtering. Hopefully eliminating results saves more time than it costs to do the glob matching.

**Comment by patelnav** [comment]
Sorry for the bump!
But symbol search is quite painful without filtering out excluded libs. 
This is **such** a crucial feature that everybody uses, and so frequently. 

Are there any PR's in the pipeline addressing this?

**Comment by parkerault** [comment]
I'm having this issue as well; I can't think of any reason why you wouldn't want the symbols search to honor the search exclusions. I can't find the symbols I'm looking for in my project because the results get spammed by node_modules and hit the max results limit.

![image](https://user-images.githubusercontent.com/78856/69892508-ba364000-12cb-11ea-8730-311e25817751.png)

**Comment by w0nche0l** [comment]
Am really running into this issue hard, especially for commonly used function/variable names. I would really appreciate the sorting functionality mentioned above as a fallback. 

![image](https://user-images.githubusercontent.com/3719829/72846773-3e26fb80-3c6f-11ea-8423-a1f410a8d8b1.png)

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/commit/0e48f6227991e21244efd6dd3964a5ea12cac687 I added support to apply `files.exclude` and `search.exclude` to the workspace symbols picker. There is a catch though so I think we should not close this too early:
* imho extensions should respect this setting when resolving the symbols so that they do not even travel back into the picker
* glob patterns are typically not absolute (e.g. our default is to exclude `**/node_modules`) which works fine in the file explorer where we can exclude folders on that level, but for symbols the glob pattern is matched against the absolute path. that means you will have to craft patterns such as `**/node_modules/**` to make this work properly for symbols

**Comment by sean-mcmanus** [comment]
Is anyone able to get this to work? I'm not seeing it working on the latest Insiders. I've tried "**/src" and "**/src/**" with a TypeScript project.

Should search.exclude also be checked for Find All References, Rename, etc. results?

**Comment by bpasero** [comment]
@sean-mcmanus should have made clear, this requires the new quick open to be used, not the old one. The new is F1 > Quick Access > `#`. It will be enabled by default over coming days.

**Comment by jrieken** [comment]
> Should search.exclude also be checked for Find All References, Rename, etc. results?

@sean-mcmanus Why do you need a UI filter when these things can be configured in project definitions. E.g just tell TypeScript (tsconfig.json) to exclude folder X or Z so that it doesn't even compute these results. I find tackling this in the UI a backwards and misleading

**Comment by sean-mcmanus** [comment]
@jrieken I don't think I was asking for a UI filter. Where is the thread on UI? My question in regards to Find All References and Rename was in regards to what our C/C++ extension should do (we currently do no filter using search.exclude for those, but we do for files.exclude).

**Comment by jrieken** [comment]
Ok - thanks for clarifying. If you ask me what a language extension should do, then I would recommend to rely on a project config, not on vs code config, esp in the name of LSP and potentially different front ends

**Comment by ppittle** [comment]
Is this fix slated for a specific release?  Excited to get my hands on it!

**Comment by dwelle** [comment]
@bpasero 
> should have made clear, this requires the new quick open to be used, not the old one. The new is F1 > Quick Access > #. It will be enabled by default over coming days.

Instructions unclear. I don't have any `Quick Access` in latest insiders.

**Comment by bpasero** [comment]
I should have posted here, the feature was pulled out, currently `search.exclude` is NOT being used for workspace symbol search.

**Comment by peterldowns** [comment]
I think it makes sense for the language server plugins to be able to resolve those symbols, but also that when quick-searching for symbols, to allow users to say "i don't want to be able to quick-resolve to symbols deep in my node_modules tree".

**Comment by samuliasmala** [comment]
Is there any workarounds to exclude `node_modules` from _Go To Symbol in Workspace_? Now the feature is not very useful when you have a large amoun to packages installed in the project.

**Comment by kbysiec** [comment]
I was suffering the same and decided to develop an extension for easy navigation among workspace files and symbols. Hope it helps somebody.

It is fully customizable so the user can easily decide which folders are included/excluded from the currently opened workspace/project.

https://marketplace.visualstudio.com/items?itemName=kbysiec.vscode-search-everywhere

Enjoy.

**Comment by muyiwaolu** [comment]
Does anybody know the status of this?

**Comment by ddadon10** [comment]
+1 on this, I would to be able to exclude folder from symbol search

**Comment by CarinaChenot** [comment]
+1 as well, this feature is not usable as it is without being able to exclude node_modules from results

**Comment by ZeWaka** [comment]
bumping this, this is extremely annoying for JS projects we bootstrap in

**Comment by imdadahad** [comment]
Would've had more luck buying BTC than having this resolved 😒 

P.S. Still using PyCharm...

**Comment by timlau** [comment]
Any news on this one ?
(`**/build/**` in seach exclude )
![vscoude_symbol_search](https://user-images.githubusercontent.com/283985/124346549-bbce9500-dbdf-11eb-846f-cf462fb19346.png)

**Comment by nvthuong1996** [comment]
I would to be able to exclude folder from symbol search

**Comment by CodePhilanthropist** [comment]
It appears to have occurred as a result of the installation of a **strange extension**. I was able to remedy the issue by **disabling** all of the extensions one by one.

**Comment by selrond** [comment]
I'd also love to see this implemented, as many others before me. 
Although it's been 2 years since @dkozickis broke it down, it seems like a low-hanging fruit that’d bring great value. 

@mjbvz could you provide some insight into this?

**Comment by selrond** [comment]
If it’s reasonable for a first-time contributor to this repo, I’d try my hand at it

**Comment by alexn-s** [comment]
are there any news on this subject?
i think its an important feature for vscode

**Comment by EcksDy** [comment]
Goto symbol is unusable when it's showing results from dist/out/nodemodules etc. 
Will this setting be implemented?

**Comment by mitsukuri** [comment]
This bug is unresolved for 3 years, 10 months, 3 weeks, 1 day.

**Comment by mitsukuri** [comment]
This issue is 3 years, 10 months, 3 weeks, 6 days old today.

**Comment by timbrownsf** [comment]
This is the main thing keeping me from switching from Pycharm to vscode - this is table stakes.
