### ISSUE TITLE
Language-specific file tokenization optimization

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#46714]
#46603 

It seems to work pretty well, only in TypeScript since the class is not parsed it's missing that scope. I wonder if we could check if the start of the chunk of text we're parsing starts with public, private or protected and add the class scope manually in this case. Maybe this is tightly coupling things too much but it's one way we could fix this likely very common TS issue.

![image](https://user-images.githubusercontent.com/2193314/37974358-98bd8f90-3191-11e8-934c-3d07818e6dc7.png)

Expected:

![image](https://user-images.githubusercontent.com/2193314/37974448-d104916e-3191-11e8-8843-260003c3c8b7.png)

**Comment by rebornix** [comment]
I'm labeling it as won't-fix as it's limited by the current design (based on heuristics like indentations of first line of the viewport).
