### ISSUE TITLE
[Ember] Intellisense dont work for this.[methodName]

### ISSUE THREAD

**Issue by atcq1** [Microsoft/vscode#4671]
- VSCode Version:0.10.11
- OS Version:ubuntu 14.04 x64

Intellisense\autocomplete not work to call methods and property through this.methodName () / this.propertyName.

Steps to Reproduce:
1. Create route:
```
import Ember from 'ember';

export default Ember.Route.extend({
    property1: 'text',
    model(params) {
        return {};
    },
    firstMethod()
    {
        //test1
    },
    secondMethod()
    {
        //test2        
    },
    thirdMethod()
    {
        //Intellisense
        secondMethod(); //work
        this.secondMethod(); //do not work
        //Autocomplete
        property1; //work
        this.property1; //do not work
    }
});
````
2 Enter `this.second` or `this.prop` in `thirdMethod(){}`:

**Comment by egamma** [comment]
I don't think that Salsa supports this pattern, moving to TypeScript for comment.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#8133
