### ISSUE TITLE
[Loc] Request to add Norwegian (no-nb) language to Transifex VS Code project

### ISSUE THREAD

**Issue by steinrl** [Microsoft/vscode#46711]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by danyeh** [comment]
According to [steps and criteria to add language to Transifex](https://github.com/microsoft/localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project), need three contributor votes before enable a language.
We count:
https://www.transifex.com/user/profile/steinrl/
https://www.transifex.com/user/profile/lars.magnus.herland/
https://www.transifex.com/user/profile/andreona/

Now Norwegian Bokmål (nb) is enabled in Transifex for three VS Code projects.
