### ISSUE TITLE
[css] Using [alt]+arrow to shift blocks could result in not working CSS

### ISSUE THREAD

**Issue by fabianhenzler** [Microsoft/vscode#46721]
Issue Type: <b>Bug</b>

I shifted a CSS code block upwards above another code block. The CSS file looked ok, but the class wasn't used, because there seamed to be an invisible char included.
After deleting the blank between the class name and the { braces - it worked. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-markdownlint|Dav|0.14.1
EditorConfig|Edi|0.12.1
vscode-docker|Pet|0.0.25
code-settings-sync|Sha|2.9.0
html-css-class-completion|Zig|1.17.1
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
vscode-power-mode|hoo|2.2.0
Angular2|joh|2.15.0
vscode-scss|mrm|0.6.2
vscode-azureappservice|ms-|0.6.1
vscode-azurefunctions|ms-|0.7.0
vscode-azurestorage|ms-|0.2.0
vscode-cosmosdb|ms-|0.5.1
azure-account|ms-|0.3.3
azurecli|ms-|0.4.1
vscode-node-azure-pack|ms-|0.0.2
azurerm-vscode-tools|msa|0.4.0
debugger-for-chrome|msj|4.2.2
angular2-inline|nat|0.0.17
vscode-icons|rob|7.22.0
stylelint|shi|0.35.0

</details>
Reproduces without extensions

**Comment by aeschli** [comment]
Any idea how the invisible character got inserted. Is it related to the 'shift up' (did you use the 'move up' command?

A sample with detailed steps would be helpful.
