### ISSUE TITLE
Selected terminal output not visible

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#46724]
Testing #46594.

1) Ensure there is a couple of commands that have been out of the view port
2) Move to the top command using <kbd>Cmd+ArrowUp</kbd>
3) Select the output of this command using <kbd>Cmd+Shift+ArrowDown</kbd>
-> Terminal scroll so that the top of the next command is the top of the viewport. What I just selected is not visible.

**Comment by Tyriar** [comment]
The full fix for this is the visual feedback captured in https://github.com/Microsoft/vscode/issues/46561 and focusing the command in the center of the terminal. I held off on the latter because it might be tough to find the command, but maybe it's worth it for the copying case.

**Comment by Tyriar** [comment]
@kieferrm I changed it so both selectTo commands always move the command to the middle, much easier to see what's selected now 👍

**Comment by roblourens** [comment]
Verified but is there supposed to be some feedback when I use cmd+up but it doesn't cause a scroll? Like when there are many commands visible in the viewport? Would be nice to see a "cursor" or something flash there to know where I am

**Comment by Tyriar** [comment]
@roblourens captured in https://github.com/Microsoft/vscode/issues/46561
