### ISSUE TITLE
Cannot jump to required JSON file

### ISSUE THREAD

**Issue by mfulton26** [Microsoft/vscode#46720]
Issue Type: <b>Bug</b>

```js
const json = require('./path/to/json-file.json');
```

try to jump to the file (Ctrl+Click, F12, etc.), it won't work, but it would work if it were a .js file but it is a .json file which NodeJS supports as well as .js (it may support others too, not sure)

Thank you.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by mjbvz** [comment]
Thanks. This is tracked by https://github.com/Microsoft/TypeScript/issues/7071
