### ISSUE TITLE
Command navigation should respect current scrolling position

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#46729]
Testing #46594.

1) Manually scroll up, so that at least one command is scrolled off the bottom of your terminal
2) <kbd>Cmd+ArrowUp</kbd>

-> The last command before the prompt is revealed, i.e. the terminal scrolls down. I'd expect it to scroll up.  The reason here is a predictable workflow. I can use command navigation to reveal a command. Then I refocus on something else. Then I come back to the terminal and use <kbd>Cmd+ArrowUp</kbd>. Now, the terminal scroll up while when I scrolled manually before it doesn't. However, the time elapsed between those two steps can be substantial.

**Comment by Tyriar** [comment]
We should do https://github.com/Microsoft/vscode/issues/46561 before tackling this one.

**Comment by Tyriar** [comment]
To verifier: Experiment with jumping around commands, scrolling and jumping around more. Note that the scroll position navigation only applies when you do not have an active selection from the select to commands (cmd+shift+up/down).
