### ISSUE TITLE
Provide a means to hide proxy user and password in settings.josn

### ISSUE THREAD

**Issue by varnk** [Microsoft/vscode#46725]
Issue Type: <b>Feature Request</b>

The http.proxy value provides a means to specify a proxy if behind a firewall, but since my corporate proxy requires Userid and Password to access the proxy I have to enter that into the http.proxy setting.  Doing this makes uerid and password viewable in the clear within the settings.json file.  It would be desirable to somehow specify the password as an encrypted value or have the proxy setting not be stored in the clear within the settings.json file.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.14393

**Comment by joaomoreno** [comment]
This won't happen any time soon, unfortunately. We don't have a safe way of doing so.
