### ISSUE TITLE
env variables broken on OS X

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4672]
In the VS Code alpha 51209bba91f1e0bb7caed8ea6db9a2ac3bdc9e91 
task are no longer working:

![2016-03-25 14-24-14](https://cloud.githubusercontent.com/assets/1898161/14044884/4920ea14-f295-11e5-86d5-1886cd2a15b1.png)

Reverting the latest commit related to env vars (4cd1c0f) seems to fix this problem.

On OS X the env command does not support a `--null` option:

![2016-03-25 14-11-34](https://cloud.githubusercontent.com/assets/1898161/14044903/6d112a6a-f295-11e5-80e3-b9e2363608a3.png)

**Comment by Tyriar** [comment]
Thanks for reverting @weinand, looking at this now.

**Comment by Tyriar** [comment]
The problem with not using `--null` is that multi-line vars can always break the system. Consider the following:

```
export TEST_ENV_VAR="Multi
LINE=string"
```

Which is output in `env` or `printenv` as:

```
TEST_ENV_VAR=Multi
LINE=string
```

**Comment by Tyriar** [comment]
Lists all environment variables *names*: `compgen -A variable`
