### ISSUE TITLE
When I do something to a file from another file or command line the ide / file doesn't update to new content

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/vscode#4673]
- VSCode Version: Version 0.10.11 (0.10.11)
- OS Version: Mac OS X

Steps to Reproduce:

1. Run a TypeScript command in console
2. view .js file and it has old content.  The new file is not refreshed with new data.  

It doesn't always happen but it does happen many of the times.

**Comment by unional** [comment]
Also noticed the folder panel does not get updated automatically when files are add, remove, or renamed.

**Comment by xtianus79** [comment]
Yes @unional thanks for the addition of that issue.

**Comment by bpasero** [comment]
@xtianus79 @unional if you see issues with the file watcher, can you run "code --verbose" from the command line and open dev tools console to see the raw file events printed? once you see something not updating, check the console for the output please.

**Comment by xtianus79** [comment]
I don't why was this closed? nobody else has this issue?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
