### ISSUE TITLE
Coloring of active line number

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#46732]
This color was introduced in 1.21: https://code.visualstudio.com/updates/v1_21#_coloring-of-active-line-number and it's missing in theme color reference: https://code.visualstudio.com/docs/getstarted/theme-color-reference

**Comment by aeschli** [comment]
Added doc.

Note, I just fixed #46848, so the color is now named `editorLineNumber.activeForeground`

**Comment by svipben** [comment]
@aeschli Thank you very much, I guess it can be closed?
