### ISSUE TITLE
Terminal API to get child process IDs

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#46737]
Node debug and Python both have use cases to enable auto attach.

**Comment by weinand** [comment]
Node-debug determines the child process IDs based on our own xplat getProcessTree and filters by the '--type=terminal' argument. See https://github.com/Microsoft/vscode-node-debug/blob/e1f63c924fd3c881048eb3e8abdcd50f4d20806e/src/node/extension/nodeProcessTree.ts#L116-L118

Yes, the `wmic` based Windows implementation will be replaced by the windows-process-tree ASAP.

**Comment by Tyriar** [comment]
@weinand because it's a native node module you can't ship it with the extension though (afaik), so an API for this would allow you to sit on public API.

**Comment by weinand** [comment]
Oh, right.

IMO we have two options:
- surface the module (and the linux and macOS counterparts) as extension API (ideally independent of terminal because the process pickers provided by node-debug and others need to enumerate all processes and not only child processes of a terminal). 
- turn the node module into a Windows-only standalone utility that can be used as a (faster) replacement for `wmic`.

**Comment by Tyriar** [comment]
> ideally independent of terminal because the process pickers provided by node-debug and others need to enumerate all processes and not only child processes of a terminal

@weinand well that blows this idea of a terminal specific solution then if you need other processes, I'll close this off 😃

**Comment by weinand** [comment]
@Tyriar you didn't reply to my option 2 from above:
> turn the node module into a Windows-only standalone utility that can be used as a (faster) replacement for `wmic`.

Does this make sense? How big would that be?

**Comment by Tyriar** [comment]
@weinand as in ship an exe with VS Code? A better option might be to ship the binaries with the node module so extensions can use it directly?

**Comment by weinand** [comment]
I meant "shipping an exe with node-debug".
 
Shipping an exe within an node module is another option.

But in my case I have already code that deals with macOS, linux, and Windows (see https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/processTree.ts). 
So just replacing the spawning of `wmic` by your fast replacement tool would probably the smallest change...

Or are you planning to offer a cross-platform solution of the process-tree module?
