### ISSUE TITLE
Ctrl-C doesn't terminate process in tmux inside VSCode terminal

### ISSUE THREAD

**Issue by Mellbourn** [Microsoft/vscode#46731]
I have the setup that was described by João Moreno (@joaomoreno) in his blog post https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41

However, it seems to me that Control-C does not work as good as it used to.

It is particularly noticeable when I run `nodemon`. When I run it in tmux in `iTerm`, I can exit the run without problem by using Control-C. If I run `nodemon` inside tmux inside VSCode, I cannot. Instead it just renders `^C` in the terminal window.

Strangely, the problem is intermittent. Restarting VSCode sometimes help.

- VSCode Version: 1.21.1 and 1.22.1-insiders b75321329388d74e34f79dcfcb789246e31836a8
- OS Version: MacOS 10.13.3

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@joaomoreno @bpasero have you noticed ctrl+c not being responsive?

**Comment by bpasero** [comment]
@Tyriar no never, works fine.

**Comment by joaomoreno** [comment]
Same here.

**Comment by Tyriar** [comment]
@Mellbourn for macOS we just send the shell (tmux) ^C (SIGINT) and let it handle it how it sees fit. Perhaps this is something related to your environment since @bpasero and @joaomoreno both run this setup and see no issues?

**Comment by Mellbourn** [comment]
@Tyriar strange. Ok, I'll try to investigate further on my own, to figure out why it is happening. Thanks for your time!

**Comment by Tyriar** [comment]
@Mellbourn let us know if you find out more info.
