### ISSUE TITLE
Visibility of Replace/ReplaceAll inconsistency

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#46735]
Re #46604

* Have search in the panel
* Search for something, expand replace box
* Right click on items, we can see *Replace/ReplaceAll* as the replace box is visible.
* Toggle search position
* Right click on search results in sidebar, the replace box is hidden but we can still see *Replace/ReplaceAll*

**Comment by roblourens** [comment]
I think this is essentially https://github.com/Microsoft/vscode/issues/44491
