### ISSUE TITLE
Broken config for mixed TS/JS project

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode#46741]
Issue Type: <b>Bug</b>

I am working on a project that uses both JavaScript and TypeScript. I am trying to configure the JavaScript language features to allow decorators. When I run the command, "Go to Project configuration", I get an error, "File is not part of a JavaScript project".

jsconfig.json
```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "target": "ES6"
  },
  "include": [
    "src/**/*.js"
  ]
}
```

tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "dist",
    "sourceMap": true,
    "target": "es5",
    "module": "system",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "lib": ["es2015", "dom"],
    "baseUrl": "./",
    "paths": {
      "app:*": ["src/app/*"],
      "env:*": ["src/env/*"],
      "ur:*": ["src/ur/*"]
    }
  },
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./typings/index.d.ts",
    "./custom_typings/**/*.d.ts",
    "./jspm_packages/**/*.d.ts"
  ],
  "exclude": [
    "node_modules",
    "jspm_packages",
    "dist",
    "build",
    "./src/**/*.js"
  ],
  "atom": {
    "rewriteTsconfig": false
  }
}
```

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|31.89GB (16.90GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Source\Ouranos\Services\Callisto\.vscode\callisto.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|1.0.3
better-toml|bun|0.3.2
vscode-opennewinstance|chr|0.0.4
vscode-eslint|dba|1.4.8
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
vsc-material-theme|Equ|1.5.1
dotnet-test-explorer|for|0.2.1
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.0.17
Go|luk|0.6.77
HTMLHint|mka|0.4.0
mssql|ms-|1.3.0
python|ms-|2018.2.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.2.2
debugger-for-edge|msj|0.4.1
vscode-docker|Pet|0.0.25
material-icon-theme|PKi|3.2.6
gitconfig|sid|1.0.1
code-spell-checker|str|1.6.5
shell-launcher|Tyr|0.1.6
sort-lines|Tyr|1.5.0

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
You can't have a `jsconfig` in the same directory as a `tsconfig` currently: https://github.com/Microsoft/TypeScript/issues/15869

Tsconfig projects can include js files though. Just add `"allowJs": true` in the compiler options and remove the exclusion for js files

**Comment by firelizzard18** [comment]
@mjbvz In that case, how do I specify different compiler options for the two? I'm using babel to transpile my JS, hence why I want separate configs.
