### ISSUE TITLE
'Create file In' explorer notification does not update/dismiss after you delete path separator in new name

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46744]
Testing #46328

- VSCode Version: Version 1.22.0-insider (1.22.0-insider)
- OS Version: MacOS 10.13.3 

**Steps to Reproduce:**

1. Create a new file in the explorer
2. In new file input, type a forward slash then delete the slash

**Bug**
The 'create file in' notification is still showing but no longer updates

![mar-27-2018 11-29-07](https://user-images.githubusercontent.com/12821956/37987289-99b89784-31b2-11e8-9091-c829426966d5.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
@mjbvz this is a good catch, forawrding to Till to investigate since he owns this feature.
Also assigning to April since it is nothing critical
