### ISSUE TITLE
Progress API percentage is ambiguous

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#46743]
Re #46458 

Based on the code sample 

```
    setTimeout(() => {
        progress.report({ percentage: 10, message: "still going..."});
    }, 1000);

    setTimeout(() => {
        progress.report({ percentage: 50, message: "still going harder..."});
    }, 2000);

    setTimeout(() => {
        progress.report({ percentage: 90, message: "almost there..."});
    }, 3000);
```

I would think the `percentage`  here represents the overall progress of the task while after reading the documentation (and watched the real behavior), the `percentage` value will actually be summed up.

**Comment by bpasero** [comment]
Yes, this is as designed. There are two main reasons:
* we do not want to allow to show negative progress (e.g. you jump from 80% to 20%)
* more importantly we think that absolute progress is much harder to implement if you have two independent running tasks that finish in any order you need to synchronise somehow to know how much progress to report

**Comment by bpasero** [comment]
Maybe part of the confusion is the name percentage that seems to indicate an absolute value. @jrieken should we rename this to `worked` instead or some other name that makes the relative progress more clear?

**Comment by jrieken** [comment]
Yeah, discussed that with @joaomoreno yesterday and came to the same conclusion. I would go for `increment` because that leave no room for interpretation...

**Comment by bpasero** [comment]
Verify: I renamed `percentage` to `increment` to report progress increments.
