### ISSUE TITLE
Goto definition doesn't work on a standalone C++ Header (after installing the C++ VSIX)

### ISSUE THREAD

**Issue by aku911** [Microsoft/vscode#4674]
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version 0.10.11
Commit f291f4ad600767626b24a4b15816b04bee9a3049
Date 2016-03-11T17:10:35.304Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

Steps to Reproduce:

1. Open standalone header with some classes defined
2. Find a member variable
3. Goto definition
4. It doesn't jump to the member variable

**Comment by gregvanl** [comment]
This is an issue with the C++ extension.  If this issue still reproduces, please enter an issue at https://github.com/Microsoft/vscppsamples/issues
