### ISSUE TITLE
Path separators in file name shown as colon instead

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46746]
Testing #46328

- VSCode Version: Version 1.22.0-insider (1.22.0-insider)
- OS Version: MacOS 10.13.3 

**Steps to Reproduce:**

1. Open a folder that has a file with a slash in the name, such as `a/b.c`

**Bug**
This is shown as `a:b.c` in the VS Code UI

![screen shot 2018-03-27 at 11 36 22 am](https://user-images.githubusercontent.com/12821956/37987473-1f514ee0-31b3-11e8-8029-5c830fc8c9e7.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is a good catch, however we have always behaved like that (also in stable).
Pushing to backlog for now.
fyi @bpasero

**Comment by bpasero** [comment]
Even though "/" might be supported as filename character from the file system, macOS actually does not and so I think it returns back ":". 

@mjbvz how did you create such a file?

**Comment by isidorn** [comment]
@bpasero I could create it using the mac finder

**Comment by bpasero** [comment]
Might be a node.js issue then.

**Comment by isidorn** [comment]
Closing as will not fix / upstream
