### ISSUE TITLE
Css Emmet completions arent triggered when selector has interpolation

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#46745]
In a scss file with more than 1000 lines, add the below
```
/* each statement */
@each $animal in puma, sea-slug, egret, salamander {
  .#{$animal} {
    background-image: url('/images/#{$animal}.png');

  }
}
```

Try an emmet abbreviation after the `background-image` above. Observe that no completions are provided 

Reproducible only in Insiders and not in Stable

**Comment by gushuro** [comment]
The same happens in this case:
```
.foo
// }
{
    dn|
}
```
We need to improve how to look for the selector of a rule.
