### ISSUE TITLE
"Log points not supported for this debug type" shown when using expression with log point

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#46756]
Testing #45962

I'm testing using the VSCode repo and "Launch VS Code" task. I haven't edited `launch.json`.

Steps to repro:
1. Add a log point
2. Add an expression to the log point
3. Start debugger

Point in gutter shows message that log points are not supported, however log point is still hit and printed to the debug console

![log_point_not_supported](https://user-images.githubusercontent.com/3672607/37988773-9acc3c30-31b6-11e8-9dc5-132c028d38ac.gif)

**Comment by isidorn** [comment]
I belive you are using the chrome debug adapter. Assigning to @roblourens please add [`supportsLogPoints`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1164) to your capabilities
