### ISSUE TITLE
C# class colorization wrong in most themes

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4675]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10
- Theme: Light (Visual Studio)

Steps to Reproduce:

1. Add some c# code
2. Change theme to a Visual Studio theme (I used Light VS)

Example in VS Code:
![c color](https://cloud.githubusercontent.com/assets/12900364/14049705/370834c0-f274-11e5-8c7f-1022372b377e.JPG)

Task and Console classes are not colored the same as they are in Visual Studio.

Example in VS 2015
![c colorvs](https://cloud.githubusercontent.com/assets/12900364/14049749/7d05ece2-f274-11e5-9402-03da00d9ef5c.JPG)

Even using a default theme, they aren't quite right:
System is blue vs black, <int> is green vs blue
![c colordefault](https://cloud.githubusercontent.com/assets/12900364/14049784/ae4e8606-f274-11e5-9ea7-646fe7ef5f9e.JPG)

**Comment by aeschli** [comment]
I think it's rather inconsistent what VS does here. No plans to adopt the coloring of type declarations and some type references.

**Comment by JLeybovich** [comment]
Any chance this can be put back on the plate? Lot's of devs use C# with VSCode and this would make our lives easier. Ideally maybe a visual editor to customize code styles for different languages as well? But if not just addressing these discrepancies mentioned above would be enough, there are a lot and in the current state themes for C# are close to useless.
