### ISSUE TITLE
Very large files issues

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46759]
Testing https://github.com/Microsoft/vscode/issues/46600

![image](https://user-images.githubusercontent.com/323878/37988591-271762c4-31b6-11e8-94d5-239979fc2455.png)
 
- Open large file
- Copy/paste many times to make it 270 MB
- "File: Save as"
- Crashes with "invalid string length" :bug:
- Also, select all contents and press backspace
- Crashes with same stack shown in screenshot

As discussed offline @rebornix

**Comment by rebornix** [comment]
The root cause is our undo/redo stack now works on string instead of chunks.

**Comment by rebornix** [comment]
This issue will be mitigated once we have Electron 3.0.

**Comment by rebornix** [comment]
Shares the same root cause (the string length limit) as https://github.com/Microsoft/vscode/issues/51625 and can be mitigated when we adopt Electron 3.
