### ISSUE TITLE
Counter badge shifts panel labels (depending on number length)

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#46757]
![counter-label](https://user-images.githubusercontent.com/9638156/37989840-2d197c78-320d-11e8-99c6-5ad27b2977fd.gif)

**Comment by usernamehw** [comment]
In my experience, issues without labels are simply lost and forgotten. Maybe this one is `as-designed` and should be closed, so ... cc @isidorn

**Comment by isidorn** [comment]
Thanks for filling hits, however this is as designed as we always keep the constant width between items(including their badge).
This is just more flexible as the problems badge in theory could have a large number that takes a lot of width.

Also I do not think th shifting is that bad, thus closing as designed.
