### ISSUE TITLE
macOS: reckless ownership change of /usr/local/bin

### ISSUE THREAD

**Issue by lloeki** [Microsoft/vscode#46754]
Issue Type: <b>Bug</b>

Installing command line tool changes ownership of `/usr/local/bin` away from `root:wheel` to `$USER:staff`. Also, `code` symlink is created as owned by `$USER:staff`.

Please don't do that: not everyone is using Homebrew.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2600)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.57GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.13.0
Ruby|reb|0.17.0
slim|sia|0.1.2
ayu|tea|0.14.0

</details>
Reproduces without extensions

**Comment by dbaeumer** [comment]
@lloeki how did you install VS Code ?

**Comment by lloeki** [comment]
Straight from the official `VSCode-darwin-stable.zip`, on a fresh new (re)install of macOS. Since I knew about the behaviour beforehand I checked the status at each step so as to open this issue:

- unzip `VSCode-darwin-stable.zip`
- move `Visual Studio Code.app` to `/Applications`
- start `Visual Studio Code.app`
- at this point there are no changes: `/usr/local/bin` is still `root:wheel`
- `CMD`+`P` then `Shell Command: Install 'code' command in PATH`
- a warning dialog shows up about launching an AppleScript through `osascript` which will need elevated privileges, hence ask for authentication
- provide authentication when asked
- at this point, `/usr/local/bin/code` has been installed and `/usr/local/bin` ownership has been altered

Expected behaviour:

- preserve `/usr/local/bin` ownership
- install `/usr/local/bin/code` inheriting ownership of `/usr/local/bin`

**Comment by joaomoreno** [comment]
It's a good catch, though I was expecting this issue to come up much much earlier. This has been working this way for 2 years and I believe it's the first time someone has mentioned it. I'll accept a PR to fix it.
