### ISSUE TITLE
Wrong syntax highlighting for property following nested properties

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#46753]
- VSCode Version: 1.21
- OS Version: Any

Steps to Reproduce:

1. Have the below content in a scss file. Observe the last property is in white

![image](https://user-images.githubusercontent.com/16890566/37988531-fd376f8a-31b5-11e8-9f87-751b06539cec.png)

**Comment by aeschli** [comment]
@ramya-rao-a Please always paste the sample code to speed up the investigations.
```
/* nested properties */
.funky {
  font: 2px/3px {
    family: fantasy;
    size: 30em;
    weight: bold;
  }
  color: black;
}
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#250
