### ISSUE TITLE
Large file notification doesn't show when opening fresh Code

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46765]
Testing https://github.com/Microsoft/vscode/issues/46602

- Close all instances of vscode
- Run `code-insiders myLargeFile.txt`
- Empty code window opens, no file or notification

**Comment by sbatten** [comment]
After investigation, this looks to be caused because the partService is not ready in doHandleSetInputError in editorPart.ts … I think we may be needing to check the notificationService instead. Assigning to @bpasero
