### ISSUE TITLE
Tokenizer is slow when pasting text and autoindentation is on

### ISSUE THREAD

**Issue by gushuro** [microsoft/vscode#46760]
When pasting text in this small JSON file, first attempt at adding colors fails, and it only gets alright after a second.
When Undoing twice (first the auto-indentation and then the paste), the coloring fails again.

![slowtokenizer](https://user-images.githubusercontent.com/5607882/37993826-9e8a2a40-31c4-11e8-87eb-ff3c658cfaa3.gif)

**Comment by rebornix** [comment]
This is due to the limitation of regex based auto indentation. You can change `editor.autoIndent` to `advanced` to workaround it.
