### ISSUE TITLE
Wrong limit size in large file notification, when size is configured

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46767]
Testing https://github.com/Microsoft/vscode/issues/46602

- Set `"files.maxMemoryForLargeFilesMB": 3`
- Open a large file
- See notification saying the limit is 4096 + the value of the setting

![image](https://user-images.githubusercontent.com/323878/37996608-1e64432e-31cd-11e8-9edb-5a0a6b8a1808.png)

**Comment by rebornix** [comment]
I love this one, bitwise operator is fun.
