### ISSUE TITLE
OSX bundle id collides with base electron app, making basic applescript automations open the Electron starter app. 

### ISSUE THREAD

**Issue by Sschumac** [microsoft/vscode#46762]
Attempting to automate windows with applescript causes the base electron app on the system to run, making it difficult to make VSCode an active window. VSCode shares a bundle ID with the base electron app "com.github.electron", which causes OSX System Events to be confused with which app to activate. 
- VSCode Version: 1.21.1
- OS Version: High Sierra 10.13.3

Steps to Reproduce:

1.  Have a project with electron in its node_modules somewhere on your system. 
2. Start VSCode
3. Run this applescript which gets processes, and checks for windows. The variable appa gets set to the bundle ID "Electron" which confuses OSX. 
```


on getWindows(appa)
	tell application appa
		set idList to null
		set nameList to null
		try
			set idList to the id of every window
		end try
		try
			set nameList to the name of every window
		end try
	end tell
	return idList & nameList
end getWindows

tell application "System Events"
	set openApps to {name, unix id, title} of (processes where background only is false)
end tell

set processList to item 1 of openApps
repeat with i from 1 to length of item 1 of openApps
	set item i of processList to {|name|:item i of processList, title:item i of item 3 of openApps, pid:item i of item 2 of openApps, |windows|:getWindows(item i of processList), id:id of application (item i of processList)}
end repeat
processList

 ```
Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
The Application we ship has this in its Info.plist:

```
    <key>CFBundleIdentifier</key>
    <string>com.microsoft.VSCode</string>
```

**Comment by Sschumac** [comment]
Hmm you are correct. 
the applescript snippet: 
```
id of application "Visual Studio Code"
```
returns the correct "com.microsoft.VSCode"

but when getting all running non-background processes with 
```
tell application "System Events"
	set openApps to application (processes where background only is false)
end tell
```

VSCode is reported as 
``` 
application process "Electron"
```
with the id 

```
"com.github.electron"
```

This is the only electron app on my system that exhibits this behavior.

**Comment by Sschumac** [comment]
I noticed that other electron apps list the executable file as their app name, while VSCode simply uses "Electron"

**Comment by joaomoreno** [comment]
Got it, we can change that.

**Comment by joaomoreno** [comment]
Risky changes for endgame. Created branch, needs review next week.

**Comment by joaomoreno** [comment]
Unfortunately I'm going to have to close this as I can't get a successful update flow working with Squirrel after renaming the executable. I do want this fixed, but not at the cost of breaking the updates for every macOS user. It's too late. :cry:

**Comment by deepak1556** [comment]
Closing as we haven't got more issues with renaming the executable and it is not worth breaking the update flow.
