### ISSUE TITLE
Missing quoting in tasks.json makes all other tasks disappear

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#46764]
Testing #46567 on Mac

The below tasks.json is missing the `quoting` property in the args. There are no errors which would make you think that there is a default value for this property

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo",
            "args": [
                {
                    "value": "hello"
                }
            ]
        }
    ]
}
```

Now run the command `Tasks: Run Task`. You get:

<img width="628" alt="screen shot 2018-03-27 at 2 25 09 pm" src="https://user-images.githubusercontent.com/16890566/37995869-aceeee12-31ca-11e8-8378-8d2b3f12f0d6.png">

Even if there are tasks from task providers or other tasks, they won't show up

**Comment by dbaeumer** [comment]
We should provide and error and may be fall back to strong quoting if the value is missing.

**Comment by dbaeumer** [comment]
Fixed two things:

- if a value is missing the quoting then I use strong as default
- made both value and quoting mandatory
