### ISSUE TITLE
Git: Support an ignored repository list setting

### ISSUE THREAD

**Issue by szhu** [Microsoft/vscode#46763]
Issue Type: <b>Bug</b>

I keep all my dotfiles and settings in [a repo](https://github.com/szhu/important-things), and my `settings.json` is symlinked into that repo. Whenever I open Preferences > Settings, my repo is added to the source control sidebar.

Steps to reproduce on Mac:

0. Quit VSCode
1. `mv "$HOME/Library/Application Support/Code/User" "$HOME/mysyncedusersettings"`
2. `cd mysyncedusersettings; git init`
3. `ln -ns "../../../mysyncedusersettings" "$HOME/Library/Application Support/Code/User"`
4. Open VSCode. The app can be in any state (a project may or may not be open).
5. Cmd-,

The settings UI opens -- I would expect opening my settings panel to do only that. What actually happens is that in `mysyncedusersettings` gets added to the source code panel in the sidebar. Sometimes it doesn't appear immediately, but it will always appear after a window reload.

I understand that this can be desirable behavior (and it sometimes is for me actually), but I feel like there should be an option to turn it off, or to open Preferences in a new window so that it doesn't affect the state of the existing window's Git sidebar.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (2.07GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_50491428|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by joaomoreno** [comment]
Maybe we need an ignored repositories list setting?

**Comment by szhu** [comment]
That sounds like a good option to me that can be extensible for other use cases as well.

Also, since there is already a way to manually remove repos from the source control tab (Right click -> "Close repo"), it would be great if there could be:
- an option to turn off the auto-populating of repos altogether
- an option to manually add repos, or to specify which repos to open in the workspace settings.

**Comment by wmb0117** [comment]
Hi! I'm new to the code and would like to give this a shot, assuming no one is currently working on it?

If I'm understanding the requirements correctly, you would like for there to be:

- a setting in the Git section of Default Settings containing a list of repositories to ignore
- an option in User Settings to prevent the application from automatically populating the Source Control tab with repos 
- an option in the Source Control tab to manually add new repos
- an option in Workspace Settings containing a list of repos to open.

Is my understanding of this correct? Also, if you could please give some pointers so I know where to start, that would be a big help! Thanks in advance!

**Comment by szhu** [comment]
A potential alternate solution to my original problem that a bit extensible is to prevent "guest" files (files outside the root directory in the Explorer pane) from adding any VCS paths to the list.

I think we still might want to an option to prevent adding certain repos as VCS paths, but the use case might be more for workspace-specific settings.
