### ISSUE TITLE
Suggestion: Allow line selection in terminal

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#46761]
testing #46594

Suggestion: Allow selecting a line at a time while navigating in terminal line by line.

With #46594 I can use `CMD+UpArrow` `CMD+DownArrow` to navigate, and can press `Shift+CMD+UpArrow` and `Shift+CMD+DownArrow` to select a block of text in the terminal (between commands).  This is cool for selecting blocks of text that are the output of a command.

But, what if I want to select a single line at a time?  Since I can use `CMD+ALT+PageUp` and `CMD+ALT+PageDown` to navigate line by line in the terminal, perhaps `Shift+CMD+ALT+PageUp` and `Shift+CMD+ALT+PageDown` could be used for that.

**Comment by Tyriar** [comment]
Opening to PRs, this will involve adding 2 new commands "terminal.integrated.selectToNextLine`/`selectToPreviousLine` and handling it within `TerminalCommandTracker`.

**Comment by ddruker** [comment]
@Tyriar Mind if I tackle this? I was just in the integrated terminal code so this code be a good issue for me.

**Comment by Tyriar** [comment]
@ddruker sure! This will probably involve having some additional state in `TerminalCommandTracker` to tell whether it's a command or a line focused.

https://github.com/Microsoft/vscode/blob/3fbfccad359e278a4fbde106328b2b8e2e2242a7/src/vs/workbench/parts/terminal/node/terminalCommandTracker.ts#L25-L26

We probably want to create a new marker whenever the line is changed (if the previous line is not a command), if we just track it with a `number` it might be invalid when lines are trimmed off the top of the terminal.

**Comment by ddruker** [comment]
@Tyriar I'm assuming this would only be previous line selection and only one line can be selected at a time using the proposed commands. Does that sound right?

Also, would the UX be similar to line by line navigation, where the terminal window always scrolls? For example, the terminal window does not need to scroll unless the line is out of view.

**Comment by Tyriar** [comment]
> I'm assuming this would only be previous line selection and only one line can be selected at a time using the proposed commands. Does that sound right?

Next should be added as well to mirror the existing commands. Users could for example go one line too far and want to go back.

> Also, would the UX be similar to line by line navigation, where the terminal window always scrolls? For example, the terminal window does not need to scroll unless the line is out of view.

@ddruker for the `selectTo*` commands, the 'focused' line is always in the middle of the viewport.

**Comment by ddruker** [comment]
Very good. Thank you! 🙏

**Comment by Tyriar** [comment]
Commands added in https://github.com/Microsoft/vscode/pull/47991

**Comment by isidorn** [comment]
Select to previous line works great.
However I was not able to get anything useful from the select to next line since I always have the last line focused in my terminal. Even if I select some text in the middle of the terminal select to next 
 line simply jumps back to last line. What am I missing here?

**Comment by Tyriar** [comment]
@isidorn select next command/line need to be used after select previous command/line.

**Comment by isidorn** [comment]
@Tyriar ok, adding verified even though I find it a bit unintuitive.
I would expect that the select next line would work even if I have 3 lines manualy selected.
