### ISSUE TITLE
Syntax highlighting of conditional breakpoint expression

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46769]
**Feature Request**
With #2268, we now have IntelliSense for conditional breakpoints. However there is no syntax highlighting:

![screen shot 2018-03-27 at 2 48 08 pm](https://user-images.githubusercontent.com/12821956/37996864-03058894-31ce-11e8-87b0-6a0df68235d9.png)

**Comment by isidorn** [comment]
This is a fair request and something we can experiment with in the future since this is now an editor
