### ISSUE TITLE
Process Picker: Newer processes should be on top of the list

### ISSUE THREAD

**Issue by gushuro** [microsoft/vscode#46766]
Testing #46582

I have older processes showing before new ones (see PIDs)

<img width="598" alt="sort" src="https://user-images.githubusercontent.com/5607882/37996035-3701df92-31cb-11e8-8eea-474d5984af56.png">

Steps to reproduce:
1. `Yarn run watch` on vscode repo
2. Launch node app
3. Attach to process --> it shows the watch process first

**Comment by weinand** [comment]
This is on macOS?

**Comment by gushuro** [comment]
Yes
