### ISSUE TITLE
[Integrated Terminal] multiline links break on reflow

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46778]
Issue Type: <b>Bug</b>

Probably part of #23688

**Steps**
1. With a small terminal width
2. Print an link that will span multiple lines
3. Expand the terminal size
4. Click on link

**Bug**
Only the visible part of the link on the first line is opened. For example:

![screen shot 2018-03-27 at 3 44 32 pm](https://user-images.githubusercontent.com/12821956/37999097-2ccd68e2-31d6-11e8-8837-566c5aa90841.png)

Opened `https://example.com/?abcdefghijklmnopqrs` instead of the full link

VS Code version: Code - Insiders 1.22.0-insider (5fbcfff69a9af92efd823f18e4c9f4b8c4dbdf2a, 2018-03-27T20:55:46.655Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.69GB free)|
|Process Argv|/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/03D24729-1C16-49B5-801F-6914290FC331/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by Tyriar** [comment]
> Probably part of #23688

Yep 😄
