### ISSUE TITLE
Wrong keyboard shortcuts suggestions

### ISSUE THREAD

**Issue by mauromazzaro89** [Microsoft/vscode#4677]
- VSCode Version: 0.10.11
- OS Version: Ubuntu 15.10

Italian keyboard.

Steps to Reproduce:
1. Open keyboard shortcuts
2. Go to key ctrl+/ for example
3. The suggestion for my italian keyboard is Ctrl + - instead of Ctrl + ù
4. This happens also for others special characters like [ and so on

![screenshot](https://cloud.githubusercontent.com/assets/10836228/14051683/2383f8ca-f2c5-11e5-83d0-daf7691b89e3.png)

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in tomorrow's Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24261011/dfe89996-0ff5-11e7-92b1-1079cf4fdb4f.png)


---
### Analysis of default keybinding for `editor.action.commentLine`
* `editor.action.commentLine` is bound by default to the key code binding `` ctrl+/ ``
* `` / `` can be produced through one scan code combination: `` Shift+[Digit7] ``. i.e.:
![image](https://cloud.githubusercontent.com/assets/5047891/24261067/0f848c00-0ff6-11e7-80aa-b5d031113cf9.png)
* therefore, the key code binding `ctrl+/` is mapped to the scan code binding `Ctrl+Shift+[Digit7]`. The `F1` list now correctly reflects this:
![image](https://cloud.githubusercontent.com/assets/5047891/24261107/2f9307ce-0ff6-11e7-83a6-ae0e76822196.png)
![image](https://cloud.githubusercontent.com/assets/5047891/24261128/41fb2716-0ff6-11e7-9507-f25453632337.png)
* That is unfortunate, but correct. We don't ship with keyboard layout specific default keybindings, that is something you can upvote in #1240

---
This makes me believe the fix in PR #22894 aka #17521 resolves this issue.
