### ISSUE TITLE
Fold all regions not working for VSCode

### ISSUE THREAD

**Issue by imdadahad** [Microsoft/vscode#46776]
- VSCode Version: Code-Insiders
- OS Version:

Steps to Reproduce:

1. Create a javascript file with some contents and specify a region e.g.:

```
test.js
// #region
import { React } from "react-native"
// #endregion
```

2. Select command to 'Fold All Regions' and notice that the region does _not_ collapse as it should

**Comment by aeschli** [comment]
duplicate of #44530
