### ISSUE TITLE
With no file in focus, "Reveal in Finder" should open the workspace's folder

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46785]
With no file in focus, if I use the Command Palette and choose "Reveal in Finder", then the workspace's folder should be opened. If it's a workspace, of course.

**Comment by isidorn** [comment]
This is a fair feature request.
PR that fix this are welcome code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L393

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/47090
