### ISSUE TITLE
Search in all files with a regex with .* and a trailing space doesn't work

### ISSUE THREAD

**Issue by sparecycles** [Microsoft/vscode#4678]
- VSCode Version: 0.10.11 ( f291f4ad600767626b24a4b15816b04bee9a3049 )
- OS Version: Mac OSX 10.10 Yosemite

Steps to Reproduce:

1. Search for ".* " in all files (with regex), only matches will be for literal dot-star-space sequences in text.
2. Search for ".* " in a single file (with regex), appears to work correctly.

**Comment by sparecycles** [comment]
More simply, it appears that including a trailing space turns off regex matching in all (?) cases.

**Comment by bpasero** [comment]
@jrieken I traced this down to https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchViewlet.ts#L1137

We seem to treat a regex pattern input by the user as non-regex-pattern if it has leading or trailing spaces. Do you remember why we do that?

**Comment by jrieken** [comment]
No clue, not even sure if I wrote that code...
