### ISSUE TITLE
[html] Don't show .files in html path completion

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46780]
Issue Type: <b>Bug</b>

**Steps to reproduce**
1. In a new folder with a git repo
1. In an html file, trigger path completions

**Bug**
Suggestions for `.git` and `.DS_Store` files and folders are shown. I think path completions should exclude all `.*` files by default:

![screen shot 2018-03-27 at 4 11 50 pm 3](https://user-images.githubusercontent.com/12821956/38000004-5d5f4b84-31da-11e8-90c1-2a1465390461.png)

VS Code version: Code - Insiders 1.22.0-insider (5fbcfff69a9af92efd823f18e4c9f4b8c4dbdf2a, 2018-03-27T20:55:46.655Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv|/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/03D24729-1C16-49B5-801F-6914290FC331/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by aeschli** [comment]
Hm, I disagree. 'Show hiden files' is normally the first thing I enable in my file explorers. It's just too confusing if you really look for such a folder.
Surely, the `.` entries clutter the suggestions here, but you would go on by typing and filtering your proposals.

**Comment by mjbvz** [comment]
How often do you use paths in html files that include dot files or folders though? I’m sure it is done but is it really common enough to outweigh .DS_Store showing up as the first entry every time I trigger completions for a new path segment?
