### ISSUE TITLE
Не работает ввод в терминале после просмотра git diff

### ISSUE THREAD

**Issue by Postnov** [Microsoft/vscode#46796]
Issue Type: <b>Bug</b>

После просмотра данных в терминале, сообщенных мне git diff, я нажимаю ctrl + c для выхода из просмотра, после этого не удается ничего ввести в терминал, курсор есть, но символы не вводятся. После удаления и создания терминала заново, все работает как надо

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X2 240 Processor (2 x 2813)|
|Memory (System)|10.00GB (7.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Data transfer system\danya\FrontEnd\HTML,CSS (create-webpage)\Projects\In-work\dev-postnov|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
css-minify|Die|0.0.4
path-autocomplete|ion|1.8.1
easy-icons|jam|0.3.1
vscode-gist|ken|1.2.0
wrapSelection|kon|0.6.8
sublime-keybindings|ms-|3.0.3
quokka-vscode|Wal|1.0.116

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment]
Tracked in https://github.com/Microsoft/vscode/issues/45693
