### ISSUE TITLE
Don't localize command names on the command palette

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#4679]
- VSCode Version:
バージョン 0.10.12-insider
コミット ef2a1fcaa553d14d7731b284a5ac5e4a55c42936
日付 2016-03-21T11:33:38.240Z
シェル 0.35.6
レンダラー 45.0.2454.85
ノード 4.1.1

Even Japanese people, typing Japanese words are very painful and time-consuming because of IME composition problems.
We expects that the commands are all in English.
For example, if I want to execute git pull, I will type "git pull"; not "git プル".

Hope you can understand our situation.

![image](https://cloud.githubusercontent.com/assets/1311400/14054201/b8673f88-f31a-11e5-9b62-070c47d86350.png)

**Comment by espresso3389** [comment]
I found that the incremental search anyway does not work for IME composed texts. If I correctly type "Git: プル" it is highlighted, but "git pull" does not find anything.

![animation](https://cloud.githubusercontent.com/assets/1311400/14060227/eea0c49e-f3a0-11e5-9726-32dff53190f6.gif)

**Comment by Tyriar** [comment]
Related to this, it would be good to introduce aliases to some commands in the command palette. For example "Reload Window" could have the alias "Restart Window" to improve discoverability.

**Comment by Tyriar** [comment]
@espresso3389 which IME are you using? And which version of Windows?

**Comment by espresso3389** [comment]
I'm on Windows 10 and the IME is ATOK; a Japanese thirdparty IME.

**Comment by espresso3389** [comment]
I totally agree with @Tyriar. What we really need is "command alias" in the case. With such aliases, I don't want to stop Japanese localization.

**Comment by Tyriar** [comment]
@expresso3389 I moved the IME bug over to https://github.com/Microsoft/vscode/issues/4691, this issue can discuss whether or not the command palette should be translated and to what extent.

**Comment by dbaeumer** [comment]
Not translation the command names doesn't make too much sense to me. Why only the command names? IMO we need to fix the filtering tracked in #4691. And aliases would only help if they are user definable since Restart Window would be translated as well. 

In general I think the command palette filtering should be improved where the command provide can provide additional search and filter strings.

@bpasero I move this to you to consider improving the command palette with additional filter / search strings.

**Comment by bpasero** [comment]
I would suggest that we do not mix english strings together with other language strings but rather ask our users to change the language to english for the entire application (F1 > Configure Language). 

I leave this decision up to our PM @chrisdias

**Comment by Tyriar** [comment]
@bpasero remember though that "mixing languages" may be natural depending on the language. I imagine typing `git pull` is far more natural to Japanese programmers than `git プル` which requires an extra effort to type due to the ime change.

**Comment by bpasero** [comment]
Yeah, I see the issue for commands that are really close to their terminal counter parts.

**Comment by bpasero** [comment]
Maybe we should just document for those NLS strings that they should not get translated at all?

**Comment by yanxyz** [comment]
I have just installed VS Code Insiders and found all the commands are translated. eg. when installing an extension instead of typing `ext` I have to type: 

![image](https://cloud.githubusercontent.com/assets/737120/14163219/d334fd0a-f725-11e5-8570-1176c23a29ba.png)

My Windows language is Chinese. I have to guess which Chinese word I should use when referring to the VS Code Docs, however which word should be used is decided by the translator. And as you can see it's too boring to input EAST Asia words.  There is a Chinese idiom 过犹不及 which means too much of a good thing.

p.s. [Change VS Code locale （修改 VS Code 的语言）](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md#localization)

**Comment by lychichem** [comment]
As a Chinese user who do l10n work for Mozilla Firefox, I strongly suggest you DO NOT translate command strings in command panel. I have to try to translate all the command I want to use to Chinese exactly identical to your translation, that is very painful. You can just give out an explanation which is shown when mouse is on the command name and just translate the explanation.

**Comment by showerying** [comment]
BTW, there should be a "UI language" in the User Settings, instead of only showing in the language which is the running OS' default UI language.

**Comment by chrisdias** [comment]
@showerying you can set the locale from the command line or in a `locale.json` file, see here: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md#localization

**Comment by be5invis** [comment]
A better solution should be show the translated version and the original version side-by-side and search the command using the original one.

**Comment by lychichem** [comment]
Have you ever considered the length of a string and the width of the command palette? If both versions are shown we need to solve this problem so our users can see a full string.

**Comment by be5invis** [comment]
@lychichem I think for most commands we have enough space to show both of them.
![image](https://cloud.githubusercontent.com/assets/240091/14535767/043ed6fa-02a2-11e6-8776-b12f95ee81e7.png)

**Comment by ZClive** [comment]
Please have this fixed.

It's **okay not to **localize the anything,
but it's** not okay to **localize the commands.

**Comment by kurehajime** [comment]
Probably,Most user would not want the localized command .
I want to display the localized description next to the command .

**Comment by yukotan** [comment]
> @kurehajime 
> Probably,Most user would not want the localized command .
> I want to display the localized description next to the command .
@bpasero 
me too. I hope strongly it.

**Comment by bpasero** [comment]
The current thinking is that we will introduce keywords for all actions that allow you to find a command in addition to the label it has. These keywords would be english and not translated but they would not show up anywhere in the UI.

**Comment by Tyriar** [comment]
Some v1.0 feedback from people on Twitter regarding this issue: (some translated with bing)

https://twitter.com/dowonkang/status/720846374783193088

> VS Code was subject to localized command palette 1.0 after the update, the command you want from the search, you need to try Korean search ... At the moment man whoosh ... Select the configure the command palette > language > locale property value to "en-US" to change the resolution ... via @code

https://twitter.com/fanny_wu_ch/status/720840368514670593

> I am used chinese lanuage version , but i can not use command with english  #HappyCoding 来自 @code

https://twitter.com/chwentao/status/720836888714616832

> Where can I change my menu into English, after today's update will become Chinese. From @code

https://twitter.com/FmtWeisszwerg/status/720800326731698176

> What's the fuck!? Too BAD! Command palette should NOT be localized :-< @code 

https://twitter.com/ichiohta/status/720800156304613377

> @code You guys seem to have over-localized command strings for ja-jp, which is unusable. 

https://twitter.com/mattn_jp/status/720779497008603136

> the vscode Japan language support! It is having in Japan Japanese is good for the CTRL-SHIFT-P far, I made extension installation with install following do not enter "advanced features" is, I want to go back.

**Comment by espresso3389** [comment]
@bpasero I think we need both of localized text and keyword shown on the UI. If only localized one is shown, how do I know the keyword for it?

**Comment by be5invis** [comment]
@espresso3389 @bpasero 
Yeah, that's what I mean. Display the translated version with the “untranslated” one together. The command palette **HAS** enough space to display **both** of them.

**Comment by espresso3389** [comment]
@be5invis I see. Thanks.

**Comment by kurehajime** [comment]
English-speaker may wonder.
It is difficult for the Japanese user to type accurately the command of the Japanese language.

>Debug:Toggle Breakpoint

This command can be translated this way.

>*  デバッグ: ブレークポイントの切り替え
>*  デバッグ: ブレークポイントの切替え
>*  デバッグ: ブレークポイントの切替

All correct. as Japanese language.

And,It would mistake once a days.

>* デバッグ: ブレークポイントの切り**替**え
>* デバッグ: ブレークポイントの切り**換**え    <- Not exactly

And,Fullwidth symbol has been plagued us.

>:
>：

Until include Cortana in VSCode, Japanese command would be difficult.

**Comment by bpasero** [comment]
Well we just looked at other areas where this issue comes up. For example the Windows start menu allows you to find commands by english label but you would still see the translated label. They do not show mixed languages in the UI ever.

**Comment by xiaolongyuan** [comment]
+1

**Comment by anatoo** [comment]
VS code is great editor. But no one want this localization feature. 
First of all, VS code should just stop localize command names.

**Comment by appetizermonster** [comment]
+1

**Comment by bpasero** [comment]
Pushed a change that introduces a new keyword property for workbench and editor actions. Command palette filters on either the action label (translated) or these keywords (english) to show results. We do not show the keywords in the UI anywhere. Feedback (in our next insider build) is welcome.

**Comment by Treri** [comment]
> @bpasero I think we need both of localized text and keyword shown on the UI. If only localized one is shown, how do I know the keyword for it?

vote for above

**Comment by bpasero** [comment]
@chrisdias @stevencl @bgashler1 what do you suggest? should we show the keywords after each command maybe only for some languages?

**Comment by Treri** [comment]
To everyone

For now, I didn't even know why should we **must** locallize all commands? I think the command should be **accurate english**, so we can know what we should input without changing IME.
If we want to add localized description, we can show localized desc after the accurate command.
rather than now, the command is localized, and the description is a little fuzzy compare to the real command.
I think the result is a little inverse.

**Comment by dbaeumer** [comment]
@bpasero is there anything I need to do. If so please assign back to me and let me know what I can do.

**Comment by bpasero** [comment]
@dbaeumer sorry, I only assigned this to you to verify this issue since my intent was to close it.

The general issue of not being able to find commands using english in other languages is fixed. Wether to show keywords within the UI or not translate the commands at all is up for discussion.

**Comment by LearnShare** [comment]
Update to Insiders 1.0.1 now, and changed "locale" from "zh-CN" to "en-US", and then to "zh-CN", the command works now:

![image](https://cloud.githubusercontent.com/assets/3265208/14696016/242c7168-07aa-11e6-9610-950a660cae58.png)

But I think we still shouldn't translate the words, just show what we types:

![image](https://cloud.githubusercontent.com/assets/3265208/14696092/ce3b52c8-07aa-11e6-9ccf-5f35ef534166.png)

**Comment by Treri** [comment]
@LearnShare 

Yes, I agree to you. I think the command labels shouldn't be translated.
If VSCode team think the command descriptions are necessary, maybe the localized command descriptions should appear following the english commands.

Anyone agree to me?

**Comment by espresso3389** [comment]
@bpasero
You were talking about other GUIs like Windows start menu.
In this area, we (Japanese) also have same pain on searching programs.
On Windows start menu, there are many *undocumented* keywords for the pre-installed tools, calc for "電卓", feedback for "Windows フィードバック", paint/pbursh for "ペイント" and so on.
We memorize many of them to deal with the problematic Windows GUI; the start menu is anyway not a good example of successful GUI.

So, anyway, for command line tools like git, we want the command names in English. We, Japanese developers usually use pull/push/fetch in normal operation and, are very familiar to these English commands.
And, for basic editor operations like open, edit, find,... They should be shown as English commands with Japanese explanation (like hint/tooltip).

**Comment by bpasero** [comment]
Reopening this given the discussion that happens.

**Comment by bpasero** [comment]
@egamma @chrisdias I would appreciate if a decision could be made by either PM lead or Dev Lead how we should handle this issue and then plan with the team how we do the adoption (if needed).

**Comment by be5invis** [comment]
@bpasero @egamma @chrisdias My suggestion is to display both English command and translated command together, but I prefer translate first, then English.

**Comment by bpasero** [comment]
Some ideas on the UI (ignore the fact that both show up as english - we just have to decide which comes first english or translated):

<img width="634" alt="screen shot 2016-04-21 at 11 29 23" src="https://cloud.githubusercontent.com/assets/900690/14706073/8303bc50-07b4-11e6-9a31-6a5b1e819600.png">
<img width="630" alt="screen shot 2016-04-21 at 11 30 21" src="https://cloud.githubusercontent.com/assets/900690/14706074/8304ba42-07b4-11e6-8b48-a30a3c872040.png">

**Comment by bpasero** [comment]
I actually like the second option and would probably show english first and then the translation.

**Comment by be5invis** [comment]
@bpasero Second one looks good. You can simply replace the keyword line with English commands (and also, reduce text size)

**Comment by bpasero** [comment]
@be5invis so you would prefer to see translated commands first and the english values below?

**Comment by be5invis** [comment]
@bpasero My preference is translated first, but some people may prefer English first.
Make it configurable?

**Comment by bpasero** [comment]
What about other places where we show commands in quick open. Would you expect this to be consistent everywhere where you can search for something?

![image](https://cloud.githubusercontent.com/assets/900690/14706358/f561b328-07b5-11e6-8c7a-7965b9a9be9a.png)

**Comment by be5invis** [comment]
@bpasero I think the two-line configuration is universal, this UI pattern can be used on all of these interfaces, including commands, file jump, or something else.

**Comment by be5invis** [comment]
@bpasero Or maybe display translated and English commands in one line, but right-align the secondary item, together with the shortcut keys.

**Comment by bpasero** [comment]
@be5invis how would this be needed for the file jump quick open that is not talking about commands?

**Comment by be5invis** [comment]
@bpasero Perhaps second line for directory?

**Comment by bpasero** [comment]
@be5invis that seems to me unrelated to this CJK issue.

**Comment by espresso3389** [comment]
@bpasero 
I prefer English (untranslated) first.

At least for Japanese, for command typing purpose, we will *never* type translated ones to execute commands.
There are two major reasons why we don't want to see the translated commands first are:
- Typing Japanese is anyway painful and time consuming
- Wording order in Japanese sometimes disturbs programmers thinking

The Japanese wording order is typically completely opposite to English.
For example, "Insert Line Below" is translated as "行を下に挿入", on which, 行を(line) 下に (below) 挿入(insert). But if I type "line below insert", the command does not match.
Anyway programmers normally start with verbs like function names so we anyway needs verbs first even though Japanese language does not do so.

So, the order default should have language specific default?

**Comment by be5invis** [comment]
@bpasero Agree with @espresso3389 .
So design like this?

* UI: Display both translated and English
* Matching: Translated, English and keyword list

**Comment by Treri** [comment]
@bpasero Agree with @espresso3389 too

I prefer English (untranslated) first.

**Comment by bpasero** [comment]
Well if we put english as first label then I would also do the sorting based on english labels. We would put the translated ones below or to the side, would still allow to match on them. I would probably ditch the concept of keywords altogether if we keep the english label. I do not think we should have both keywords and english label.

**Comment by lychichem** [comment]
I don't care the order, just make me see the full text of en-US command and zh-CN command at the same time is okay. Or make me see the command with tool tip is also okay.

**Comment by espresso3389** [comment]
@bpasero 
> Well if we put english as first label then I would also do the sorting based on english labels. We would put the translated ones below or to the side, would still allow to match on them. I would probably ditch the concept of keywords altogether if we keep the english label. I do not think we should have both keywords and english label.

For me (and possibly all the Japanese people), everything seems OK.

**Comment by Treri** [comment]
1. the translated ones order is not important, just based on english labels
2. the translated ones are just explanation to english command. match or not match is okay.

**Comment by egamma** [comment]
Thanks for trying out the Insider build and for providing great feedback. We will discuss in the UX team and come back with the outcome from this discussion.

**Comment by be5invis** [comment]
@bpasero Keywords may be helpful since it contains synonyms of English label words. I think when the user chooses to display translated label as primary, keywords should be enabled.

**Comment by bpasero** [comment]
@be5invis agree, keywords can be a useful concept in cases where you can describe the command with different words. I am fine leaving that in for matching but I would not show keywords anywhere in the UI.

**Comment by be5invis** [comment]
@bpasero But if you decide to display English label as primary, then the keywords is less useful, but I think it is still worth preserving.

**Comment by bpasero** [comment]
To be clear, the keywords currently are english and are not translated. If we decide to keep keywords, the interesting challenge is that you would probably need to have both translated keywords and english. Hence I am thinking of not keeping keywords (we never had them and imho they are separate from the discussion here and just nice to have).

**Comment by be5invis** [comment]
@bpasero My main idea is that, if users can directly see the English label clearly (which means that the primary label is in English, not translated), then the English keywords are less important. However, if what they directly see is translated, then they may come up with synonyms of the English command, and the keywords are very useful now.
Translated keywords are unnecessary.

**Comment by bpasero** [comment]
Well I propose to show english **always** and the translated label below less prominent, hence we both agree that keywords are not needed.

**Comment by be5invis** [comment]
@bpasero Agree with you.

**Comment by chrisdias** [comment]
Thanks everyone for the great discussion on this topic. We appreciate all of the feedback and especially the insight on how you use the tool in both english and native languages. This was valuable input into our UX design meeting @egamma mentioned above, so I wanted to share with you the results of our conversation. 

Here is what we decided:

- always show the english label
- show the translated label below the english label IF the language is !== en-US
- allow search on both english and translated labels
- remove the keywords, the above experience makes these unnecessary

We only have a small window to get this into the current iteration and given the feedback here, we think we've got the right design, so we're going to push forward with this plan.

We expect to do another Insiders drop early next week and then ship this in the April release. From there, we can then make modifications to the experience in the next iteration (if necessary!).

Thanks again, we think we will have a much better and much more natural experience because of your input.

**Comment by Treri** [comment]
Happying ending 😄

**Comment by bpasero** [comment]
Pushed.

**Comment by bpasero** [comment]
We did a decision today in the team to show the localized command first and the english one below. @stevencl @bgashler1 @chrisdias fyi

**Comment by be5invis** [comment]
@bpasero So, re-enable keywords?

**Comment by bpasero** [comment]
No, you can still search for english labels:

![image](https://cloud.githubusercontent.com/assets/900690/14819476/a05dfc5e-0bc2-11e6-96a6-86343a27054c.png)

**Comment by be5invis** [comment]
Oh translated and English is in same size
That's good

**Comment by bpasero** [comment]
The rationale for this change was to emphasize the fact that the UI is translated to a certain language. Showing the english labels enables to find and memorize the english commands for faster typing but the UI is otherwise consistently translated. Showing the english label first would draw the wrong impression about the primary language of VS Code.

**Comment by espresso3389** [comment]
@bpasero
Personally, I don't totally agree to the final decision (Translated first) but anyway I appreciate VS Code team's effort to understand our situation. Thanks so much!

**Comment by bgashler1** [comment]
@espresso3389 is it that you want the translation below?  Or would you prefer to disable the translation completely and just use English.  If so, we do allow you to turn it off.

**Comment by be5invis** [comment]
@bgashler1 Make it configurable will be better

**Comment by espresso3389** [comment]
@bgashler1 
> is it that you want the translation below?

Yes, it would be better "for me" if I can choose which one comes first.
But not so important so far.

**Comment by Tyriar** [comment]
Considering that the English version is the "primary" one, at least for CJK languages, I think it makes sense for that to come first. This may not be the same for languages that don't use an IME though.

**Comment by WhiteCat6142** [comment]
By the way,can I change font sizes?
I want to make primary keywords bigger than secondary ones.

**Comment by espresso3389** [comment]
Agree with @WhiteCat6142.
The current gray color is not enough to tell the actual commands from the translations.
If the translations (or, for some case, the actual commands) are smaller, it's easier to see what are on the palette.
