### ISSUE TITLE
Add loading indicator for first terminal open

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46799]
Issue Type: <b>Bug</b>

**steps**

1. With panels view hidden.
2. Restart vscode.
3. Press ctrl+` to launch integrated terminal

**Bug**
1-2 second delay before terminal launches with no indication that something is happening. Opening the terminal after the first time is quick

VS Code version: Code - Insiders 1.22.0-insider (5fbcfff69a9af92efd823f18e4c9f4b8c4dbdf2a, 2018-03-27T20:55:46.655Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/03D24729-1C16-49B5-801F-6914290FC331/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by Tyriar** [comment]
@mjbvz the terminal should be launching near instantaneously, it's likely your shell is running a bunch of init scripts which take a while. To verify you can comment out your `.bashrc`/`.bash_profile`/etc files and see how fast it is. Let me know if it's still slow after that.
