### ISSUE TITLE
Feature request: snippets inside of tagged template literals

### ISSUE THREAD

**Issue by hollandThomas** [Microsoft/vscode#46792]
I'd like to suggest a feature, if possible. When working with [styled-components](https://github.com/styled-components/styled-components), you often find yourself writing things like `${props => props.theme.colors.gray.dark};` inside of a tagged template literal kinda like this:

```javascript
const Wrapper = styled.div`
  color: ${props => props.theme.colors.gray.dark};
`;
```

For that I made a snippet. Unfortunately one cannot seem to invoke snippets inside of tagged templates or any string for that matter. 

Is adding a feature that allows for working with snippets inside of strings/stringish things like tagged template literals possible? Or would that violate the expected behavior for pressing tab with the cursor being inside of a sting?

Thanks for looking into this!

**Comment by jrieken** [comment]
Please share the snippet and the language the snippet is configured for. Also use F1 > Inspect TM Scopes to see what language is used inside the tagged string

**Comment by hollandThomas** [comment]
Thanks the fast reply. You are right. I configured the snippet for Babel JavaScript but it needs to be configured for styled-css. For completion and anyone interested, this is the snippet:

```javascript
"theme": {
    "prefix": "thm",
    "body": [
        "${props => props.theme.${1:property}};"
    ],
    "description": "Styled Components theme selector"
},
```
