### ISSUE TITLE
pylint moudle has no member

### ISSUE THREAD

**Issue by Loovelj** [Microsoft/vscode#46798]
- VSCode Version:1.21.1
- OS Version:Win10

Steps to Reproduce:

1.I write python , and I hava the moudle opencv2,  when I write 
import cv2
cv2.imread('lena.jpg')

the pylind let the cv2 red ,and note 
'[pylint] E1101:Module 'cv2' has no 'imread' member
module cv2
Python wrapper for OpenCV.'

but I can run the code

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by laixintao** [comment]
That's not a issue of vscode, maybe your pylint and opencv2 are not in the same virtualenv.
