### ISSUE TITLE
Extension host terminated unexpectedly when open python files

### ISSUE THREAD

**Issue by Xusine1131** [Microsoft/vscode#46791]
I have encountered this issue when using VSCode(not insider version) and I try to reinstall it but nothing enhanced. So I try to using Insider version and it performs well at first but this problem repeats today.

- VSCode Version: 1.22.0-insider
- OS Version: Windows 10 Pro x64 10.0.16299

Steps to Reproduce:

1.Open a py file using VSCode
2.Extension host terminated unexpectedly.

I have installed these extensions:
* Beautify
* C/C++
* Code Runner
* Graphviz Markdown Preview
* hexdump for VSCode
* HTML Snippets
* JavaScript(ES6) code snippets
* Markdown All in One
* Markdown Emoji
* Markdown Preview Enchanced
* Markdown Preview Mermaid Support
* Markdown TOC
* Markdown+Math
* Python
* SVG Editor
* vscode-icon

Does this issue occur when all extensions are disabled?: No
And when I disable Python-extension I find it works well but I can't finish my work without python-extension.
I think It might be the wrong interaction between extensions but when I just enable python-extension only the problem stays still.

**Comment by Xusine1131** [comment]
Oh I make a typo.. 
Does this issue occur when all extensions are disabled?: No
So sorry..

**Comment by dbaeumer** [comment]
@Xusine1131 when this happens can you go to the Output Channel and select the Log (Extension Host) channel and provide the output.

Since you open a py file I suspect this might be caused by the Python extension. Does everything work if you disable that extension. If so please report the issue against the extension.

**Comment by Xusine1131** [comment]
@dbaeumer Thank you for your suggestion! And I use Developer Tools and Output channel and finally I find the question is caused by JavaScript(ES6) Snippets and when it was removed(must be removed not disabled) everything went well.  Thank you anyway!
