### ISSUE TITLE
Markdown preview render error 

### ISSUE THREAD

**Issue by movsb** [Microsoft/vscode#46794]
Issue Type: <b>Bug</b>

The following markdown text will not be redered properly:

markdown:

```md
a**(**
```

preview:

```
a**(**
```
expect parenthesis to be bold.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_9767248|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.14.1
spellright|ban|2.2.0
php-debug|fel|1.12.2
phpcs|ika|1.0.5
Go|luk|0.6.77
python|ms-|2018.2.1
vim|vsc|0.11.2
markdown-all-in-one|yzh|1.1.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
The markdown preview is correct here. The text is not bold since the `**` is inside of a word.

The bug is the editor shows `a**(**` as bold

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#12
