### ISSUE TITLE
Emmet abbreviation suggestions suddenly stop showing up in JSX files

### ISSUE THREAD

**Issue by JCaraballo113** [Microsoft/vscode#46793]
Issue Type: <b>Bug</b>

Open a jsx file, use emmet abbreviations. At some point, it's random the abbreviation suggestions menu dissapears and you can no longer autocomplete html tags in .jsx files.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.33GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.27
erb|Cra|0.0.1
react-native-react-redux|EQu|1.7.3
EditorConfig|Edi|0.12.1
vsc-material-theme|Equ|1.5.1
beautify|Hoo|1.3.0
vscode-todo|Mat|0.8.0
vscode-jest|Ort|2.6.4
vscode-react-native-storybooks|Ort|2.5.1
material-icon-theme|PKi|3.2.6
code-settings-sync|Sha|2.9.0
unity-debug|Uni|1.3.0
vscode-wakatime|Wak|1.1.26
vscode-caniuse|aka|0.5.3
react-pure-to-class-vscode|ang|1.1.3
vscode-color|ans|0.4.5
vscode-icontheme-nomo-dark|be5|1.3.5
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.1.1
vscode-exports-autocomplete|cap|0.5.4
solargraph|cas|0.13.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
gitlens|eam|8.1.1
vscode-npm-script|eg2|0.3.3
flow-for-vscode|flo|0.8.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
css2react|got|0.0.6
CppSnippets|har|0.0.13
webpack|jer|2.0.2
sublime-babel-vscode|jos|0.2.9
vscode-styled-components|jpo|0.0.16
docomment|k--|0.0.17
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
python|ms-|2018.2.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
node-debug2|ms-|1.19.0
PowerShell|ms-|1.6.0
team|ms-|1.122.0
debugger-for-chrome|msj|4.2.2
color-highlight|nau|2.3.0
vetur|oct|0.11.7
seti-icons|qin|0.1.3
Csharp-ASPNETCore|rah|1.0.5
Ruby|reb|0.17.0
vscode-icons|rob|7.22.0
sass-indented|rob|1.4.8
autoimport|ste|1.5.3
addDocComments|ste|0.0.8
vscode-react-native|vsm|0.6.6
vscode-todo-highlight|way|0.5.12
bootstrap-3-snippets|wcw|0.1.0
vscode-import-cost|wix|2.6.2
JavaScriptSnippets|xab|1.5.0

(7 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
You have set:

```json
"emmet.includeLanguages": {
  "javascript": "javascriptreact"
},
```

and the file mode is `javascript react`?
