### ISSUE TITLE
Replace does not work on mac

### ISSUE THREAD

**Issue by lzantal** [Microsoft/vscode#468]
Hi,

I am trying to use Replace but it does nothing when I select it from the menu or use the shortcut.
Mac version 10.11

**Comment by alexandrudima** [comment]
@lzantal 

Would love to get more steps here. Did you open a text file before trying to replace in it? Other folks at the office use mac and it works for them.

**Comment by lzantal** [comment]
Hi,

I checked it on another mac and it works there. So I deleted it and reinstalled it and now it works.
Not sure what was going on, but it appears to be working now, including the shortcut.

**Comment by alexandrudima** [comment]
Thank you!
