### ISSUE TITLE
Weird black line shown under macOS menu bar when vscode is focused

### ISSUE THREAD

**Issue by hjkcai** [Microsoft/vscode#46805]
- VSCode Version: 1.12.1
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Uncheck 'Use dark menu bar and Dock' option in system preference
2. Open a new vscode window
3. Switch it to fullscreen
4. Switch it back and you will see the black line under the menu bar

![image](https://user-images.githubusercontent.com/731326/38011041-53e14102-328e-11e8-826c-a2a6bff6700a.png)

5. Move focus out of vscode and the black line will disappear

![image](https://user-images.githubusercontent.com/731326/38011066-6f26df44-328e-11e8-8ee6-4e84e5481891.png)

It looks sooooooooooo weird!

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@bpasero not sure if this is us or the default with Electron.

**Comment by bpasero** [comment]
@hjkcai does it reproduce with this build of VSCode that is using a newer Electron version: https://az764295.vo.msecnd.net/exploration/c52be1294047741be296c2ced817b8246ab9942f/VSCode-darwin-exploration.zip ?

**Comment by hjkcai** [comment]
@bpasero Yes. It reproduces by following my steps.

![image](https://user-images.githubusercontent.com/731326/38022737-e53e8f8c-32b2-11e8-9163-55b1e54487c0.png)

**Comment by hjkcai** [comment]
Seems it is a bug of Electron. I will open another issue on Electron. Thanks for your help.
