### ISSUE TITLE
Search term navigation stop working when assigning same shortcut to compare editor

### ISSUE THREAD

**Issue by LeThiHyVong** [Microsoft/vscode#46808]
Issue Type: <b>Bug</b>

I assigned `Alt+Up` to `workbench.action.compareeditor.previouschange` and `Alt+Down` to `workbench.action.compareeditor.nextchange`.
Then Alt+Up and Alt+Down in search (Ctrl+F and Ctrl+Shift+F) stop working.

How can it be?

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|Memory (System)|3.42GB (1.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
Bookmarks|ale|0.18.2
bracket-pair-colorizer|Coe|1.0.27
githistory|don|0.4.0
gitlens|eam|8.1.1
git-project-manager|fel|1.4.0
macros|ged|1.2.1
gc-excelviewer|Gra|2.0.20
CppSnippets|har|0.0.13
output-colorizer|IBM|0.1.2
vscode-colorize|kam|0.6.16
auto-comment-blocks|kev|1.0.1
python|ms-|2018.2.1
cpptools|ms-|0.15.0
gitpatch|par|0.2.1
material-icon-theme|PKi|3.2.6
reloaded-cpp|rel|0.1.6
partial-diff|ryu|0.5.1

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
Did you set a `when` clause for your new keybindings? Try `"when": "editorTextFocus"`

**Comment by LeThiHyVong** [comment]
Thank you very much. It works.
