### ISSUE TITLE
Code following a single line comment appears like commented

### ISSUE THREAD

**Issue by AmnArora** [Microsoft/vscode#46802]
Hi, 

After I recently updated VS Code, I am facing an issue wherein the code following a single line comment like /* 3*/ appears to be commented but isn't.

![selection_003](https://user-images.githubusercontent.com/16914455/38009301-2a83d29c-3271-11e8-85d9-840c33abdbb4.png)

But this gets fixed if we move the comment to next line.

![selection_004](https://user-images.githubusercontent.com/16914455/38009326-54973862-3271-11e8-95cb-09cf3fea303c.png)

I am not really sure if this issue presented after the latest update or was present earlier also since I am just starting on a new existing project.

**Comment by aeschli** [comment]
@AmnArora With which language is this? Can you paste the code snippets as well?

**Comment by AmnArora** [comment]
@aeschli  I am using javascript. I've already included the code snippets. I can't put up more code since its my company's project.

**Comment by mjbvz** [comment]
@AmnArora I can't repo this in VS Code insiders. Please test this in insiders with all extensions disabled.

If you still see the problem, please share a minimal code snippet that demonstrates this highlighting issue. You don't need to post the whole file

**Comment by AmnArora** [comment]
Hi @mjbvz  Thanks for looking into it. Like you suggested I disabled the extensions one by one and found that sublime babel plugin was causing the issue. 

anyway thank you for your help.
