### ISSUE TITLE
Cannot zoom editor window after opening issue reporter

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46801]
Issue Type: <b>Bug</b>

**Steps**
1. Open issue reporter
2. Click back on main vscode window
3. Press cmd + to zoom in or cmd - to zoom out

**Bug**
No zoom

Seems to start working again after switching back to issue reporter and then back to editor window again 

VS Code version: Code - Insiders 1.22.0-insider (5fbcfff69a9af92efd823f18e4c9f4b8c4dbdf2a, 2018-03-27T20:55:46.655Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.17GB free)|
|Process Argv|/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/03D24729-1C16-49B5-801F-6914290FC331/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by ramya-rao-a** [comment]
I cant repro this in 1.22.2
