### ISSUE TITLE
设置  json   launch 太难了

### ISSUE THREAD

**Issue by EsqerYasen** [Microsoft/vscode#46800]
Issue Type: <b>Feature Request</b>

设置那些东西太难了  我两台你一直在设置  但是还是没有成功  我需要帮助。 这个得到用户权限以后自己去匹配相应的path不好吗? 老是出问题   问题没有中文提醒   如果你可以帮助我  联系我  我的微信 askary

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by hjkcai** [comment]
为啥不百度一下？
Why don't you google it?

**Comment by EsqerYasen** [comment]
I did , but  couldn't find the answer that matches my problem

Sent from my iPhone

On 28 Mar 2018, at 1:39 PM, Jingkun Hua <notifications@github.com<mailto:notifications@github.com>> wrote:


为啥不百度一下？
Why don't you google it?

**Comment by dbaeumer** [comment]
@EsqerYasen can you please provide the description in English.

**Comment by yume-chan** [comment]
Translation:

> **It's too hard to configure launch.json**
>
> It's too hard to configure this, I have tried on two PCs without success, I need help.
> Can't you make everything magically done with users' permission?
> The error messages are not in Chinese.
> If you can help me, contact me by WeChat account "askary"

LMAO
