### ISSUE TITLE
'Keep Open' menu entry should show disabled when editor is pinned

### ISSUE THREAD

**Issue by Antisunny** [microsoft/vscode#46807]
when 'keep Open' a tab, there is no indicator that show its status (this tab has been kept open)

- VSCode Version: Version 1.21.1 (1.21.1)
<img width="315" alt="capture 2018-03-28 at 14 02 57" src="https://user-images.githubusercontent.com/2398514/38011695-041b3ac6-3291-11e8-8e3c-143c63572e8f.png">

- OS Version: macOS 10.13.3

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
Why is this menu option still a choice on non-preview tabs? AFAICT it doesn't have any effect other than to turn a preview tab into a real one. Although it would be great if this option DID have an effect to support something like: https://github.com/Microsoft/vscode/issues/12622
