### ISSUE TITLE
Can't change the “git path”

### ISSUE THREAD

**Issue by PmuYi** [Microsoft/vscode#46813]
well I can't sign in stackoverflow at this time. Maybe there are some question with my computer.

I am a beginer. and I can't find the answer though the help. And I try to search the answer though the internet, the way they show can't hlpe me .
- VSCode Version:1.21.1
- OS Version: win 10

Steps to Reproduce:

1.look the picture below,when I change the var of the "git path" in user's setting
2.The defult setting didn't change, And  when I restart the vscode and the computer , "git path" remain null at last .

Does this issue occur when all extensions are disabled?: Yes/No
![default](https://user-images.githubusercontent.com/22147594/38014731-39e87c12-329c-11e8-9025-74d91eb2d294.png)

**Comment by joaomoreno** [comment]
The default setting never changes. What changes is the user setting. Also, you should point to `git.exe`, not the folder where `git.exe` is located.
