### ISSUE TITLE
Output Scroll Lock shouldn't be reset on quit

### ISSUE THREAD

**Issue by lsnch** [microsoft/vscode#46819]
So I use Code Runner a lot, and usually most interesting part of output is the first several lines. There's a button (Toggle Output Scroll Lock) to keep it from scrolling down, but it gets reset every time I relaunch. Is it possible to have a setting for this?

**Comment by isidorn** [comment]
The scroll lock should be preserved across vscode reloads. I will treat this as a bug

**Comment by isidorn** [comment]
After closer analysis I figured out that this was the actual behavior from day 1.
So I will treat this as a feature request, that scroll lock is stored for each outout channel across vscode seassions.
Code pointer https://github.com/Microsoft/vscode/blob/ffd91480d7c8cdc38bec9f3476a82a0dc0c507d1/src/vs/workbench/parts/output/browser/outputActions.ts#L73

**Comment by thernstig** [comment]
I also struck this today, using Code Runner. I set have the `Toggle Output Scroll Lock` unlocked. Sometimes it goes back to being locked for no apparent reason. I figured it is the same as this issue?
