### ISSUE TITLE
Code PS: Shared process appears many times

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#46818]
When running `code -s` I get:

```
CPU %	Mem MB	   PID	Process
    0	    98	 13976	code-insiders main
    0	    82	 13977	   gpu-process
    0	    82	 13980	   shared-process
    0	   229	 91185	   window (ps.ts — vscode)
    0	    98	 91188	     extensionHost
    0	    98	 91196	       electron_node tslintServer.js
    0	   557	 91197	       electron_node electronForkStart.js tsserver.js
    0	    49	 91218	         electron_node typingsInstaller.js tsserver.js typesMap.js
    0	    49	 91239	       electron_node jsonServerMain.js
    0	    49	 91189	     watcherService
    0	    49	 91191	     searchService
    0	    82	 91247	   shared-process
```

Notice that there are two shared processes listed. This was also causing some confusion in #46598.

There are renderers which are neither the workbench nor the shared process. We should be able to unequivocally distinguish them, not based on the `--disable-blink-features=Auxclick` heuristic. Maybe we pass in extra flags which are ignored by Chrome, but we could later detect them?

**Comment by bpasero** [comment]
@joaomoreno is this the issue reporter maybe?

**Comment by bpasero** [comment]
This issue applies for:
* dev tools opened
* issue reporter opened

We do some weak check for the window type [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/ps.ts#L95)

I would accept a reasonable PR if someone has a better idea how to identify different windows from the command line 👍

**Comment by RMacfarlane** [comment]
There's an `additionalArguments` option when creating browser windows in Electron 2.0 that could be used to add something to distinguish between them: https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

**Comment by bpasero** [comment]
Unfortunately it does not look like `additionalArguments` shows up in the command line for the renderer, so we cannot easily leverage that.
