### ISSUE TITLE
Programmatically update .tmLanguage scope match string

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#4681]
Is there a way of doing that? Let's say I have an entry in my .tmLanguage:

```xml
<dict>
	<key>match</key>
	<string>\b(MyFunction_First|MyFunction_Second|SpecialStuff)\b</string>
	<key>name</key>
	<string>keyword.SCARDOC.userfunction</string>
</dict>
```

And I'd like to populate that match with a list of function names I have ripped from workspace files.
I'm currently using `completionItemProvider` and `signatureHelpProvider` to auto-complete these user functions, and the final step would be to give them a distinguishable color (with my separate theme, that would just refer to `keyword.SCARDOC.userfunction`, of course).

**Comment by aeschli** [comment]
@Janne252 Our grammars can not have dynamic content. But what you can do is contribute decorations from your extension. You'd still have the grammar file. It would provide the basic colors (comments, strings...), but on top of that you could color your special identifiers using decorators.
It's not something we do ourselves, but it's worth trying out. 
To see decorators in action, check out the [decorator sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/decorator-sample)
