### ISSUE TITLE
Welcome page background color

### ISSUE THREAD

**Issue by icokk** [Microsoft/vscode#46816]
Welcome page's background is always set to editor background, while welcome page foreground colors depend on the theme (dark foreground for light theme, light foreground for dark theme). This makes welcome page unreadable in case that you have dark editor background with light theme. The same problem happens for extension documentation page.

Would it be possible to add a setting for welcome page background (it can also apply to extension documentation page and other embedded web pages)? To maintain background compatibility, it can default to editor background when not set.

Examples:

![image](https://user-images.githubusercontent.com/491482/38016402-2cf7df8e-326f-11e8-9431-8e2e87a218c8.png)

![image](https://user-images.githubusercontent.com/491482/38016715-288c9d62-3270-11e8-86f7-a76ed21bb550.png)

**Comment by audoralc** [comment]
I'd be happy to take a look into this 👍

**Comment by chrmarti** [comment]
@audoralc Yes, should be a small change from what I see. Next to and similar to the button colors here: https://github.com/Microsoft/vscode/blob/d1571770ce9f6fdb98e8ee19d7711498a35bfdd0/src/vs/workbench/parts/welcome/page/electron-browser/welcomePage.ts#L590

**Comment by defaults** [comment]
@audoralc have you already started on this or can i take this up?

**Comment by audoralc** [comment]
@defaults I have already started
