### ISSUE TITLE
Issue reporter - show notification that running with extensions disabled

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#46817]
Testing #46595
When selecting the link to run with disabled extension then we do everything automatically, even reloading the window (which is great). However, it is almost to transparent and @joaomoreno suggested to show a notification inside the workbench that VS Code is now run with extensions disabled..

**Comment by joaomoreno** [comment]
Actually, the notification should always appear, regardless of whether it due to the issue reporter.

**Comment by joaomoreno** [comment]
Also, maybe there should be an action in that notification to revert the process.
