### ISSUE TITLE
Can't see lodash (underscore ) in Integrated terminal

### ISSUE THREAD

**Issue by Lev09** [Microsoft/vscode#46811]
Issue Type: <b>Bug</b>

Open the terminal and type underscore (lodash) you will not see it.
I know this issue was reported somewhere in 2017, but it seems to come back again

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.8.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3600)|
|Load (avg)|0, 0, 0|
|Memory (System)|11.61GB (0.52GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
laravel-goto-view|cod|1.2.0
vscode-eslint|dba|1.4.8
gitlens|eam|8.1.1
vetur|oct|0.11.7
laravel-blade|one|1.17.0
laravel-5-snippets|sac|2.0.1

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
