### ISSUE TITLE
Lag issue when cursor on text

### ISSUE THREAD

**Issue by LordLafayette** [Microsoft/vscode#46810]
Issue Type: <b>Bug</b>

program lag somethime  then when i unfocus program to another programe,
it fix this issue.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|11.89GB (6.78GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.7.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
expand-region|let|0.1.2
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.2.2
bootstrap-3-snippets|wcw|0.1.0
vscode-proto3|zxh|0.1.3

</details>
Reproduces only with extensions

**Comment by LordLafayette** [comment]
it not lag it freeze.

**Comment by dbaeumer** [comment]
@LordLafayette can you provider more details please. I assume this happens in the editor. Does it reproduce with a special file. If so, can you attach that file.

And does it reproduce if all extensions are disabled?
