### ISSUE TITLE
Intellisense API could support a transient input string on top of document

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#46827]
To provide Intellisense in a text box (e.g. for a watch expression or breakpoint condition), we use the `provideCompletionItems` method at the current cursor location in the underlying text document.

This works fine for the first completion (which does not need any input from the text box) but it fails as soon as new input is typed in the text box. In this case `provideCompletionItems` is not aware of the new text and returns bogus items.

To fix this, we could add the text entered in the textbox to the underlying text document so that the `provideCompletionItems` always sees the "full picture" and returns correct completions. The problem is that this would modify the underlying text document which would get saved and trigger other mechanisms e.g. error markers etc.

A better and simpler approach would be if `provideCompletionItems` could take an optional "overlay" string which is appended at the given location in a transient way before the completions are determined.

**Comment by jrieken** [comment]
Unsure about that... For VS Code the truth is in the documents and adding another truth on the side a slightly confusing.
