### ISSUE TITLE
Log point should have dirty indicator

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#46825]
Testing #45962

* create a log point with the message `I am in fib function`
* edit the log point and add `I am in fib function {nr}`
* do not close the log point and press F5

Observe, it is not clear why the number was not logged. Turns out I need to accept the new message via Enter in order for it to be applied. But in this case, this should be depicted via a dirty indicator or the input should close by itself (like the rename in the explorer) if it is not confirmed... Or when the focus is lost...

![image](https://user-images.githubusercontent.com/5047891/38019244-5b6ccda4-3277-11e8-9642-83167e37016b.png)

**Comment by isidorn** [comment]
We decided to make the breakpoint widget more stable than the rename, thus it does not close on focus lost. However we could provide a dirty indicator -> leaving this as a feature request for that
