### ISSUE TITLE
Launch from terminal gives errors

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4682]
- VSCode Version: 0.10.12-alpha
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Follow the guidelines in the Linux install steps to launch from terminal
2. sudo ln -s /vscode/path/code-alpha /usr/local/bin/code-alpha

Actual:
Gives some errors about the process which holds the terminal window and any action will automatically close the open instance of VS Code.

![launch from terminal issue](https://cloud.githubusercontent.com/assets/12900364/14055485/b1fa4e18-f29f-11e5-9714-9f2b0a87d309.png)

Expected:
No errors and able to use terminal window without closing the current instance of Code

**Comment by Tyriar** [comment]
This is fixed in insiders, the advice to create the symlink will be removed as the bin command will be installed via deb/rpm packages.
