### ISSUE TITLE
F11 full screen problem | F11全屏的问题

### ISSUE THREAD

**Issue by violetice** [Microsoft/vscode#46820]
- VSCode Version: 1.21.1
- OS Version: Windows7 x64 NT6.1 7601

### EN
F11 full screen, The bottom is cover by the windows7 taskbar.
Difficult to reappear, This is a performance problem for PC, Instead of 100% will appear.
It may be the problem of Windows 7.
It does not affect use, but it is recommended to optimize.

### zh_CN
F11全屏，VScode的底部会被windows7的任务栏覆盖。
难以复现，这是PC的性能问题，并不会100%的出现。
也有可能是Window 7的问题，我按下截图热键，任务栏就消失了。
不影响使用，但是建议优化

**Comment by isidorn** [comment]
This is regular chrome beahvior. Closing as designed

**Comment by dbaeumer** [comment]
Not sure if @isidorn  or @bpasero. Might be the default of Chrome.
