### ISSUE TITLE
Git: Wrong encoding detection for referenceSearch.ts

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#46826]
![image](https://user-images.githubusercontent.com/22350/38019955-4d4f102c-3279-11e8-958f-2258c0b45972.png)

cc @jrieken

**Comment by alexandrudima** [comment]
Same here:

![image](https://user-images.githubusercontent.com/5047891/38024525-9d9753bc-3285-11e8-89e5-bbdfab18f468.png)
