### ISSUE TITLE
Debug console in NodeJs does not display value returned via util.inspect.custom or toString

### ISSUE THREAD

**Issue by leoseccia** [microsoft/vscode#46829]
## Environment details
- VSCode Version: 1.21.1
- OS Version: Win7 x64
- Does this issue occur when all extensions are disabled?: Yes

## Steps to Reproduce

1. Create the following javascript file in VSCode

```
const util = require('util');

class SomeObject{
    constructor(){
        this._varA = "some text";
        this._varB = 12345;
        this._varC = "some more text";
        this._varD = true;
        this._varE = 0.45;
    }

    [util.inspect.custom](depth, options) {
        return this.toString();
    }

    toString(){
        return "custom textual rapresentation of my object";
    }
}

var array = [];

array.push(new SomeObject());
array.push(new SomeObject());
array.push(new SomeObject());

console.log(array);
```
2. Run the code in debug mode and look at the debug console

## Actual
This is displayed
![](https://i.stack.imgur.com/obIn9.png)

## Expected
In my opinion, this is not quite right. The inspect method is invoked as you would expect but the debug textual representation for the object instance is not shown to be the custom return string value.

Ideally, I believe the debug console should show the summary value of the object as: `SomeObject { "custom textual rapresentation of my object" }` while still providing the ability to drill down into the object (as it already does).

## Additional Info
This started as a question on StackOverflow: https://stackoverflow.com/questions/49365663/how-to-change-string-representation-of-objects-in-nodejs-debug-console-view

**Comment by roblourens** [comment]
Calling util.inspect to generate the preview when the object has overridden util.inspect.custom is a good idea.

I don't think we want to use it for every preview. Our preview should give a short high level view of the properties of an object, but util.inspect recurses and writes out every property of the object, and returns a multiline string where in the debug console, we can only show a single line.

**Comment by leoseccia** [comment]
@roblourens - anyway to override that one line would be great... I was not sure about inspect either. Maybe hooking on a toString() method if it exists would work better. _I think_ that is the way it works in .NET + VisualStudio

**Comment by sveitser** [comment]
I'm wondering if anyone has found a way/workaround for this. I'm debugging code that uses `bignumber.js` and hard to read the unformatted representations.

![image](https://user-images.githubusercontent.com/1040871/54976310-f0048580-4fd4-11e9-9786-e124a17a0a9b.png)

**Comment by blitzmann** [comment]
Also looking for a solution. As a Python turned TypeScript dev, I'm sorely missing Python's `__repr__` magic method and PyCharms ability to display that as the textual representation of an object, if available. Having something similar in VSCode would be greatly beneficial for objects that have a bunch of properties, but there's a way to format some of them to give a good high-level view of what it is. When I have an array of over 200 object, this would be invaluable.

Perhaps a setting in VS Code that allow VSCode to call the toString method on an object to display in that one line?

**Comment by weinand** [comment]
please see the related item https://github.com/microsoft/vscode/issues/26234 which we plan to investigate in the August timeframe.

**Comment by isidorn** [comment]
I believe this works fine with latest vscode insiders.
If you still see this not working please let me know and I will reopen

**Comment by weinand** [comment]
@connor4312 our investigation in #26234 showed that Custom Object Formatters need to be implemented by individual debug extensions. Therefore I'm reopening this issue for JavaScript.

**Comment by connor4312** [comment]
Thanks for the tag. Merging this into https://github.com/microsoft/vscode/issues/102181 which is being revived by backlog issues.
