### ISSUE TITLE
[loc]Request to add Malay (Malaysia)  language to VS Code

### ISSUE THREAD

**Issue by janbaltus** [microsoft/vscode#46835]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by janbaltus** [comment]
We expect at least **three language contributors sign up** and product team sign off before adding new language to Transifex. Please **vote** by adding your **Transifex account name** here in this issue (request).
How to request guide: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by danyeh** [comment]
We don't have plan to enable additional language for VSCode in MLCP in near term. Hence close the request here.
New request should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)
