### ISSUE TITLE
extensions suddenly stopped work

### ISSUE THREAD

**Issue by alexsoares** [Microsoft/vscode#46836]
Issue Type: <b>Bug</b>

None specials step, just open vscode

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.4.0-109-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3756)|
|Load (avg)|2, 2, 2|
|Memory (System)|7.74GB (0.39GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
rails-snippets|Hri|1.0.6
html-snippets|abu|0.2.1
ruby-on-rails-snippets|ate|0.0.1
rails|bun|0.5.5
solargraph|cas|0.13.0
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
php-debug|fel|1.12.2
ruby-rubocop|mis|0.7.0
mssql|ms-|1.3.0
vscode-ruby-ctags|oto|1.4.1
remote-vscode|raf|1.1.0
Ruby|reb|0.17.0
simple-ruby-erb|vor|0.2.1

</details>
Reproduces without extensions

**Comment by dbaeumer** [comment]
@alexsoares can you please provide more details. Which extension stopped working?
