### ISSUE TITLE
[cpp] syntax highlighting in type declarations

### ISSUE THREAD

**Issue by codebreaker93** [Microsoft/vscode#46831]
Issue Type: <b>Feature Request</b>

I've noticed that for C++ source codes, the color formatting of the 'Type' in declarations (e.g. string x; User_defined_type y; etc. etc) is the same as the default font styling. 

```cpp
#include <string>

using namespace std;

int main() {
	string x;
}
```

I've posted this question on StackExchange (https://stackoverflow.com/questions/49528920/visual-studio-code-c-color-formatting-in-type-declarations#49528920), but have yet to receive a solution.

Is there a way to resolve this? 

Thank you. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.3.9600

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#266
