### ISSUE TITLE
PHP validation not working on latest Windows 10 .ISO/USB when folder is opened

### ISSUE THREAD

**Issue by dmxd5** [Microsoft/vscode#46834]
- VSCode Version: 1.21.1
- OS Version: Windows 10 Pro (64-bit)

Steps to Reproduce:

1. Download latest Windows 10 (64-bit) from microsoft.com and install it.
2. Download PHP for windows (VC15 x64 Non Thread Safe (2018-Mar-01 06:44:57)) and unpack it to `C:\php`.
3. Install VSCode, open settings and point `"php.validate.executablePath"` to your `php.exe`.
4. Create a folder and open it in VSCode. Create php file and write some PHP code with a syntax error. You will see that php validation does not report that error. Then close the folder [Ctrl+K F] and open the same php file, you will see that now, when there's no folder opened in vscode, php validation reports the error just fine.

Does this issue occur when all extensions are disabled?: Yes.
Are there any errors in Developer Tool?: No.
Does built-in IntelliSense work?: Yes.
Does this issue occur on older installs of Windows 10?: No.

**Comment by roblourens** [comment]
Replied in #46054
