### ISSUE TITLE
Native menu action gets selected if menu appears under the mouse cursor

### ISSUE THREAD

**Issue by yinzhixin** [Microsoft/vscode#46833]
Issue Type: <b>Bug</b>

1.click SCM tag
2.click button "more", then the menu flashing, can not select option
 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2904)|
|Memory (System)|7.30GB (1.94GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
open-html-in-browser|cod|0.1.21
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
vscode-html-css|ecm|0.2.0
code-runner|for|0.9.3
vscode-javac|geo|0.0.47
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
MagicPython|mag|1.0.12
vs-deploy|mkl|13.0.0
python|ms-|2018.2.1
vscode-icons|rob|7.22.0
python|tht|0.2.3
jinja|who|0.0.8
vscode-proto3|zxh|0.1.3

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
Can you show me what you mean with a screenshot?

**Comment by yinzhixin** [comment]
![vdcode](https://user-images.githubusercontent.com/14174333/38031916-f53a501c-32ce-11e8-940a-0a8f617dfba3.png)

**Comment by joaomoreno** [comment]
Can you record a video? Does the same happen for other menus?

**Comment by yinzhixin** [comment]
[video.zip](https://github.com/Microsoft/vscode/files/1858462/video.zip)

**Comment by yinzhixin** [comment]
It's normal before the upgrade

**Comment by bpasero** [comment]
@yinzhixin can you try to reproduce from this newer build: https://az764295.vo.msecnd.net/exploration/ed422f909ea470f79e3e3e39c948803d9b764919/VSCode-win32-x64-1.22.0-exploration.zip

**Comment by yinzhixin** [comment]
@bpasero The problem still exists

**Comment by bpasero** [comment]
@yinzhixin are other menus flashing as well?

**Comment by yinzhixin** [comment]
@bpasero other menus are normal， I record a video
[video02.zip](https://github.com/Microsoft/vscode/files/1862815/video02.zip)

**Comment by joaomoreno** [comment]
@yinzhixin I can't open that video, can you send another formt?

**Comment by yinzhixin** [comment]
@joaomoreno can you open the first video I provided？

**Comment by yinzhixin** [comment]
bug fixed on version 1.25.0, you can close this issue

**Comment by joaomoreno** [comment]
This will be fixed with custom menus, but I will only close once we change the default to that.

**Comment by bpasero** [comment]
Happend.
