### ISSUE TITLE
JavaScript autocompete not working when TypeScript extension disabled

### ISSUE THREAD

**Issue by zhukmj** [Microsoft/vscode#46837]
- VSCode Version: 1.21.1 (1.21.1)
- OS Version: macOS High Sierra 10.13.3 (17D47)

Assuming I have two files in my project: `one.js` and `two.js`

Steps to Reproduce:
1.  Disable the builtin `TypeScript and JavaScript Language Features` extension
2. When typing in `one.js`

![no autocomplete](https://www.evernote.com/l/AbV9fVkbVs1A65Wwevaxuvd7kgGlWG7HOdEB/image.png)

With TypeScript extension enabled it works fine
![working autocomplete](https://www.evernote.com/l/AbVxDFFHzV1GzpqqaJbTm9X_jpLo2TTuU9YB/image.png)

Does this issue occur when all extensions are disabled?:  No

**Comment by mjbvz** [comment]
The `TypeScript and JavaScript Language Features` extension is what provides TypeScript and javascript intellisense

**Comment by zhukmj** [comment]
@mjbvz okay, but how can I disable TypeScript only? I use `flow` in my project and I don't need TypeScript. Having TypeScript suggestions along with Flow (when I don't use TypeScript) is annoying.

**Comment by mjbvz** [comment]
What you are seeing are the JavaScript suggestion from the `TypeScript and JavaScript Language Features` extension. They are not TypeScript specific.

The flow extension should provide all suggestions on its own. If you don't see that, please consider opening an issue against that extension
