### ISSUE TITLE
Path not clickable in terminal when wrapped on multiple lines

### ISSUE THREAD

**Issue by marvinroger** [Microsoft/vscode#46830]
- VSCode Version: 1.21.1
- OS Version: Windows 10 Pro 1709 (x64)
- Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Open a terminal and make it print a path that wraps on multiple lines
2. You cannot click on that link

![multiline path issue](https://user-images.githubusercontent.com/990773/38022003-a7b60246-327e-11e8-8a8c-84474253280d.png)

In the picture, the first path is clickable, the second one is not since it is wrapped on multiple lines.

Also, try with a very long URL: 

```bash
echo http://google.fr/iamaverylongpathiamaverylongpathiamaverylongpathiamaverylongpathiamaverylongpathiamaverylongpathiamaverylongpathiamaverylongpathiamaverylongpathiamaverylongpathiamaverylongpathiamaverylongpath
```

You'll notice that the first line *is* clickable, but it only contains the text that is on the first line. I guess the behavior is the same with file paths, but since the first line is not a valid path, VSCode does not make it clickable.

**Comment by yume-chan** [comment]
Relates to #28746, #23688

**Comment by marvinroger** [comment]
Crap, I searched for an open issue. Should I close this, as a duplicate?

**Comment by Tyriar** [comment]
This should be fixed as part of https://github.com/Microsoft/vscode/issues/28746, you can test it out now in Insiders https://code.visualstudio.com/insiders

**Comment by yume-chan** [comment]
@Tyriar I can confirm now it works well, except that when I shrink the window width, the underline became off. I think I have seem this issue being reported somewhere but I cannot find it now.

**Comment by Tyriar** [comment]
@yume-chan yes that's a known issue as it will get fixed once we do https://github.com/Microsoft/vscode/issues/23688
