### ISSUE TITLE
Compare changes does not highlight line changes

### ISSUE THREAD

**Issue by Jollym** [Microsoft/vscode#46847]
Issue Type: <b>Bug</b>

I just cleaned up some files and on some lines i removed the trailing spaces and these changes are not highlighted in the compare changes view.

i feel that these changes should have been highlighted as white space changes as opposed to no changes.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7560U CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|15.80GB (3.82GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by alexandrudima** [comment]
@Jollym  Please click the "Ignore Trim Whitespace" button:

![kapture 2018-03-28 at 15 52 37](https://user-images.githubusercontent.com/5047891/38033334-1cf16750-32a0-11e8-8864-fb493858029d.gif)
