### ISSUE TITLE
visual studio code is flashing 

### ISSUE THREAD

**Issue by DevAspirant** [Microsoft/vscode#46842]
Issue Type: <b>Bug</b>

some time when I write an html/css document the ide is flashing & can not write any code 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz (4 x 2400)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (6.25GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
empty-indent|Dmi|0.2.0
beautify|Hoo|1.3.0
vscode-eslint|dba|1.4.7
auto-close-tag|for|0.5.6
vs-color-picker|lih|0.7.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2018.2.1
indent-rainbow|ode|0.7.2
html5-boilerplate|sid|1.0.1
open-in-browser|tec|1.1.0
highlight-matching-tag|vin|0.4.4
vscode-todo-highlight|way|0.5.12

</details>
Reproduces only with extensions

**Comment by dbaeumer** [comment]
@DevAspirant does this also happen if you disable all extensions?
