### ISSUE TITLE
How to Build and Publish a C# Web API to IIS? 

### ISSUE THREAD

**Issue by dennisaubrey** [Microsoft/vscode#46859]
What are the complete steps to Build and Publish a C# Web Service API using the IIS Web Site.

**Comment by dennisaubrey** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc#add-support-for-entity-framework-core

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/38037096-226c7320-3276-11e8-8af8-1f47a1d2f524.png)

**Comment by gregvanl** [comment]
Hi @dennisaubrey I think you want to open an issue in the https://github.com/aspnet/Docs repo which has the documentation source for the page you've referenced.
