### ISSUE TITLE
Do not expand files/folders when you close an active editor

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#46850]
Let's say I have multiple editors open and then I quit VSCode. When I open it again it's because I will probably work on a different project. First I need to close the files I had opened previously. But every time I close an open editor the file explorer navigates to that location and leave it open, basically making me go through everything and close it manually.

1. Could we have an option that when closing editors it doesn't navigated to that file? After all we're closing it, no need to show us where it is.

2. Alternative: an option to close all editors when existing the program

**Comment by bpasero** [comment]
@moseleyi you could configure `"explorer.autoReveal": false`

**Comment by moseleyi** [comment]
Thank you @bpasero, I'll test it out

**Comment by isidorn** [comment]
Yeah autoReveal: false is our current solution for this.
Closing as we do not plan to add another option similar to this one
