### ISSUE TITLE
After update embedded bash went broken

### ISSUE THREAD

**Issue by Riconec** [Microsoft/vscode#46855]
Issue Type: <b>Bug</b>

After updating to Version 1.21.1 my embedded bash stopped to work. 
It is completely blank, doesn't respond to any command. If I change it to windows command line - it works, but returning back to bash give no changes.
Disabling extentions, reloading doesn't help either.
Bash works fine outside of VScode

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
easy68k|dsi|0.0.2
python|ms-|2018.2.1
cpptools|ms-|0.15.0
vscode-docker|Pet|0.0.25

(3 theme extensions excluded)

</details>
Reproduces without extensions

![image](https://user-images.githubusercontent.com/10697866/38034320-b2afbc42-32aa-11e8-8528-76a62017e764.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169
