### ISSUE TITLE
stdin within editor randomly refuses input

### ISSUE THREAD

**Issue by Dowwie** [Microsoft/vscode#46858]
Problem:  While typing in VSC editor, programming in Rust, my stdin will eventually cease to work-- anything I type isn't entered.  I am using the vim extension and RLS.  I tried to reinstall the extension but that doesn't help.  This is a show-stopper bug for me.

- VSCode Version:   1.21.0
- OS Version:  Debian 9

Steps to Reproduce:

1.  typing in editor, random occurrence

Does this issue occur when all extensions are disabled?: Yes/No

NO.  The issue *seems* to clear when all extensions are disabled.

These are my extensions: 
DavidAnson.vscode-markdownlint
HookyQR.beautify
JPTarquino.postgresql
PKief.material-icon-theme
alefragnani.Bookmarks
donjayamanne.jupyter
fabiospampinato.vscode-todo-plus
idleberg.icon-fonts
magicstack.MagicPython
ms-python.python
nonylene.dark-molokai-theme
rust-lang.rust
ryu1kn.partial-diff
sleistner.vscode-fileutils
vscodevim.vim
yzhang.markdown-all-in-one

**Comment by dbaeumer** [comment]
@Dowwie this sound like a bug in the vscode.vim extension since the extension intercepts all keyboard input. Can you please report the issue here: https://github.com/VSCodeVim/Vim

If you are able to reproduce with all extension disabled, please ping here again.
