### ISSUE TITLE
Allow for multiple windows of VSC to access the same folder

### ISSUE THREAD

**Issue by UIDvlpr** [Microsoft/vscode#46856]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open a project folder with visual studio code
2. (windows) right click VSC on the taskbar and select new window
3. If you try to open the same folder that is currently open, you can't.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dbaeumer** [comment]
Dups #2686
