### ISSUE TITLE
Do not trigger TreeItem.command if tree item is selected through API

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#46857]
As [requested here](https://github.com/Microsoft/vscode/issues/46526#issuecomment-376903343).

With the new `reveal` API on TreeView we can programatically select nodes from the treeview. However we can't tell whether the selection was gone programatically or by the user. This makes it hard to implement an outline view that highlights the correct node in the tree for where the user is while also allowing the user to select a node to move the editor there, as they get stuck in a loop - when the user moves in the editor, we select a node, which then fires the command to move in the editor.

**Comment by sandy081** [comment]
@DanTup What is the behaviour you expect, when you select a node programatically?

**Comment by DanTup** [comment]
@sandy081 Just for the tree node to be selected/visibly highlighted. The idea is to keep the tree and the editor in sync. The code builds the UI (it's similar to React) and it's useful to see a tree of the widgets and the selection helps to know where in the tree the code you're editing relates to.

![screen shot 2018-03-28 at 15 52 28](https://user-images.githubusercontent.com/1078012/38037133-1e62d7d6-32a0-11e8-8071-e531d4ddfc75.png)

And of course, clicking on the tree takes you to that code in the editor.

**Comment by sandy081** [comment]
@DanTup I would rather not call the commands if the selection is done by api

**Comment by DanTup** [comment]
@sandy081 Totally fine be me; I wasn't sure if this way would be more flexible, but do feel free to rename. I guess it makes sense - if you're selecting programatically you already have the ability to run other code, so no real reason to pass it on as an arg.

**Comment by DanTup** [comment]
Perfect, I'll try it out in Insiders tomorrow :)

I don't suppose there's any chance of avoiding the collapse-on-click behaviour any time soon? I think it's the only serious issue that would stop us from being able to ship our outline with the next Code release.

**Comment by sandy081** [comment]
> I don't suppose there's any chance of avoiding the collapse-on-click behaviour any time soon? 

@DanTup No plans for this release.
