### ISSUE TITLE
Menu action Toggle Render Whitespace is a no-op if editor does not have focus

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4685]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:
I think related to #2110 possibly a regression
1. Open a project folder with cursor not in the editor
2. View -> Toggle Render Whitespace

Actual:
Toggle does not show whitespace dots until the cursor is placed in the editor window regardless of how many times you toggle.

Expected:
Cursor does not need to be in the editor to toggle whitespace

**Comment by Tyriar** [comment]
I can reproduce, to clarify "cursor" is talking about the text cursor, not mouse cursor.

**Comment by alexandrudima** [comment]
This works now. I am opening a file, then clicking in the git commit box and pressing alt+z
