### ISSUE TITLE
Distinguish debug output from multiple processes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#46861]
https://github.com/Microsoft/vscode/issues/46414#issuecomment-376815368

There should be a way to filter the output in the debug console when debugging multiple processes. Currently it is all mixed in together.

I'd prefer a model where I can still see it all at once, but can also filter out the output from different processes when needed.

**Comment by weinand** [comment]
@roblourens would support for multiple debug consoles address this issue for you?

**Comment by roblourens** [comment]
I think so, but I think that being able to see the output from multiple processes simultaneously and in order would be useful in some cases.

If I'm debugging two things at the same time, they must be closely related, like a server and a website, or a renderer process and main electron process. I might want to see an error in any process immediately without switching consoles, or I might want to see logs related to making a request, handling the request, and the response all at once.

One problem is that logs can be out of order depending on how quick the different debug adapters happen to be in handling log messages.

**Comment by isidorn** [comment]
This is fixed now, there are multiple debug consoles
