### ISSUE TITLE
MacOS - File saved when "Don't save" is selected via keyboard

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#46869]
Issue Type: <b>Bug</b>

1. Open a file and modify it
2. Cmd + W to close the file
3. Dialog opens, "Don't save" is highlighted by default. Press enter

Expected behavior: File isn't saved
Actual behavior: File is saved

![saved_file](https://user-images.githubusercontent.com/3672607/38045695-623d7cd2-3272-11e8-9262-31d9fa94c688.gif)

This happens both in latest insiders and in stable. It doesn't repro when clicking the "Don't save" option, only when using the keyboard. It also doesn't repro on Windows, didn't check Linux.

VS Code version: Code - Insiders 1.22.0-insider (95b0cffe72a9d32e6ef3780dcc050a336e7b2968, 2018-03-28T05:10:13.290Z)
OS version: Darwin x64 17.4.0

**Comment by bpasero** [comment]
As designed, the default action will be executed which is saving upon enter. The blue focus ring is for keyboard navigation in the dialog (arrow keys).
