### ISSUE TITLE
Git: Delete branch notification should be modal

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#46860]
The new notifications pop open at the lower right corner of the editor.  Some command palette actions pop these up with a button that I need to click on to proceed.  In these cases, I have to move my mouse from the top center of the window down to the bottom right corner of the window.

One such example is the "Git: Delete branch" command.  I have to click on the branch I want to delete from the drop down selector, then click the notification button far away in the corner to confirm the delete.  If I am deleting multiple branches at a time (because I'm finally cleaning up my local state 😜) I have to move the mouse back and forth a ton of times so now I use a terminal for this task instead.

It would be nice to have an option that lets me decide where I want the notifications to appear.  I would choose the top right corner to reduce mouse movement.

**Comment by joaomoreno** [comment]
I'll narrow this issue down to make the delete branch popup a modal one, which it should be anyways.

**Comment by brightsquare** [comment]
I'm trying to repro, but don't get any such popup after selecting a branch to delete. The branch is instantly deleted. I'm on Mac OS X 10.11.16, vscode version 1.21.1
