### ISSUE TITLE
Add restart option to menu

### ISSUE THREAD

**Issue by Ermish** [Microsoft/vscode#46864]
Hey, Team!

A great feature would be to have a `restart` option in the menu! 
It's available when there's an update, but I would love it if that option stuck around.

**Comment by bpasero** [comment]
@Ermish why would you need to restart?

**Comment by Ermish** [comment]
In all honesty, it's biggest value is alleviating side-effects of extensions. I've encountered various random situations that I would want to restart such as:

- C# Intellisense suddenly stops working
- File status changes don't properly show up when doing a git branch switch
- I want to install extension updates later
- some extensions are useful, but are resource intensive and seem to have memory leaks that are cleared with restarting vs code
