### ISSUE TITLE
Snippets list - extension's snippets have higher priority than all others

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#46863]
- VSCode Version: 1.22.0-ins
- OS Version: win7x64

file: .ts
when I type "form" - I expect to see "form" being №1 snippet in the list... but instead see dozens of Bootstrap snippets first...

![form snippet](https://user-images.githubusercontent.com/24613274/38042569-663e4794-32bd-11e8-9c60-a758bbd82cb9.gif)

here is the extension:
![image](https://user-images.githubusercontent.com/24613274/38042741-dd512842-32bd-11e8-8c27-c1aaaebf7717.png)

So, is it the VS Code's problem? Or extension's priority bug?

**Comment by jrieken** [comment]
Can you share your settings with us? Also please copy/paste the source file in which this happens

**Comment by user3323** [comment]
@jrieken 

it happens in order of using the setting:

`"editor.snippetSuggestions": "top"`

**Comment by jrieken** [comment]
Closing as that's the design of `"editor.snippetSuggestions": "top"`.
