### ISSUE TITLE
[themes] When exiting High Contrast, restore previous color theme

### ISSUE THREAD

**Issue by furgat** [Microsoft/vscode#46862]
- VSCode Version: 1.21.1
- OS Version: Windows 10 - Version 1709 - Build 16299.309

Steps to Reproduce:

1. Open VS Code and select a custom color theme
2. Activate High Contrast ( I used Shift + Alt + PrintScn )
3. Observe VS Code has changed to High Contrast color theme
4. Deactivate High Contrast ( I used Shift + Alt + PrintScn )
5. Observe VS Code now shows the default color theme instead of the selected color theme
5a. Restarting VS Code will restore it to the selected color theme

Does this issue occur when all extensions are disabled?: No.  With extensions disabled, VS Code switches from the default color theme to high contrast, and back to default color theme.  This issue only occurs with a custom color theme selected.

It appears as though VS Code only reverts to the default color theme when leaving High Contrast, rather than to the user selected color theme.  I'd expect it to revert to the color theme I chose.

**Comment by aeschli** [comment]
The previous theme is not remembered and what you see is the expected result.
Question: Is that a common workflow?

**Comment by furgat** [comment]
It is pretty common for me as a Front-End developer.  Part of my task is ensuring new pages/elements/styles are accessible, part of which is High Contrast testing, so I activate and deactivate HC multiple times a day typically.
