### ISSUE TITLE
Importing scoped npm modules without scope name

### ISSUE THREAD

**Issue by sasidhar** [Microsoft/vscode#4687]
- VSCode Version: 0.10.10
- OS Version: Ubuntu 15.10

This is a question.

We have some private NPM packages using npmjs' private repository. Assume

- scope name : `@scope`
- private package name as : `private-package`

When we install this NPM package using 
```npm install @scope/private-package``` 

It is installed to : ```./node_modules/@scope/private-package```

In VSCode, to import some thing from this package, we need to do
```import {SomeThing} from '@scope/private-package'```

Is there anything in TypeScript configuration or VSCode settings that we can re-map
```@scope/private-package``` to ```private-package``` 
so that we can use like 
```import {SomeThing} from 'private-package'``` instead of adding`@scope`?

**Comment by sasidhar** [comment]
Accidentally I closed this issue. Re-opened now.

**Comment by Tyriar** [comment]
This is probably a question for [Microsoft/TypeScript](https://github.com/Microsoft/TypeScript) rather than vscode.

**Comment by sasidhar** [comment]
Posted @ https://github.com/Microsoft/TypeScript/issues/7695

Closing it here.
