### ISSUE TITLE
Omnisharp unable to load project

### ISSUE THREAD

**Issue by jtleaming** [Microsoft/vscode#46873]
- VSCode Version: 1.21.1 79b44aa704ce542d8ca4a3cc44cfca566e7720f1 x64
- OS Version: Windows 10

Steps to Reproduce:

1. Open up C# project
2. Error message appears on bottom of screen 
3. Open output window
4. See this error message 

Does this issue occur when all extensions are disabled?: Yes/No
No. Enabling the C# extension does cause an error though.

![](https://media.giphy.com/media/1rSq07V3LafCy9Ud2G/giphy.gif)

**Comment by jtleaming** [comment]
<iframe src="https://giphy.com/embed/1rSq07V3LafCy9Ud2G" width="480" height="258" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/1rSq07V3LafCy9Ud2G">via GIPHY</a></p>

**Comment by dbaeumer** [comment]
I can not read the message in the screen cast. It is simply to little.

Since this is related to a C# project I am pretty sure that the error is related to the C# extension. Can you please report the error there (https://github.com/OmniSharp/omnisharp-vscode) or provide a screen cast that is more readable.

**Comment by jtleaming** [comment]
@dbaeumer Sorry, I was so excited about including the GIF I forgot to paste the error message :/ 
This is the failing message I receive:

`[fail]: OmniSharp.MSBuild.ProjectLoader
        The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

**Comment by dbaeumer** [comment]
@jtleaming this comes from the C# extension. Please report the issue here: https://github.com/OmniSharp/omnisharp-vscode
