### ISSUE TITLE
zenMode.centerLayout does nothing

### ISSUE THREAD

**Issue by komali2** [Microsoft/vscode#46872]
Issue Type: <b>Bug</b>

In linux, on latest stable release, change "user settings" "zenMode.centerLayout" to `false`. Close all open editors, open a single file/editor. See file in the middle of your screen. Close vsCode, open again, see same situation. Try changing to `true` just in case, see same situation. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.9.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2920)|
|Load (avg)|2, 2, 1|
|Memory (System)|7.49GB (0.47GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
vetur|oct|0.11.7

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@komali2 are you in zen mode? This setting only controls centered editor layout when entering zen mode.

**Comment by ucirello** [comment]
Even in zen mode. The centered layout does not start.

**Comment by komali2** [comment]
yes, I am in zen mode.

**Comment by isidorn** [comment]
@komali2 all zenMode settings are designed to change the behavior of what happens while you enter zenMode.
So if you are in zenMode, and you change `zenMode.showTabs: true` the tabs will only show if you exit and re-enter zenMode.
If this is the best behavior is debatable and I accept feature reqeusts for this.

The zenMode.centerLayout behaves the same way. It will only take effect if you exit zenMode and re-enter it again. Or if you simply restart vscode.

Can you please try with latest vscode insiders and let me know if something is not behaving as I just explained. Thank you very much
https://code.visualstudio.com/insiders/

**Comment by komali2** [comment]
I have confirmed that exiting and re-entering zenMode, as well as restarting vsCode, does not affect the behavior of the setting. 

I will try with insiders later this evening.

**Comment by isidorn** [comment]
@komali2 yes, please try with insiders, thank you

**Comment by komali2** [comment]
Confirmed broken in insiders. 

Confirmed still broken most recent update.

**Comment by isidorn** [comment]
@komali2 let me get your steps straight

1. You have no settings in user settings except
`"zenMode.centerLayout": false`
2. You have 1 file open which is not centered and now enter zen mode
3. File is centered -> it should not be centered

Did I get your steps correct? Becuase following them does not reproduce the issue for me.
Thansk

**Comment by isidorn** [comment]
@komali2 this feature is not OS dependent imho, though I can not repro both on Ubutnu and OS X.
I am using insders.

Since nobody seems to reproduce except you, let's place some breakpoints on your machine to get more details.
F1 > Open developer tools > Source > wait a couple of seconds and open `editorGroupsControl.ts`, put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorGroupsControl.ts#L2146) and figure out why `doCentering` is `true` for you.

Also make sure you do not have some folder or workspace settings which might overwride your user setting.

**Comment by komali2** [comment]
`this.partService.isEditorLayoutCentered() === true`

`(this.stacks.groups.length === 1) === true`

`this.visibleEditors[Position.ONE]` resolved to an "position is undefined" error. 

Debugger paused on line 2149, `doCentering` resolved to undefined error, not sure if I'm misunderstanding how dev tools works in an electron app. 

`this.centeredEditorActive` resolves to `false` on line 2149

Hmm, does this help? Thanks for showing me how to open editor tools, I never could figure that out before. 

BTW I've updated to 1.23.1 and still have the issue.

**Comment by isidorn** [comment]
Basically this is the issue `this.partService.isEditorLayoutCentered()`
You might be in some weird vscode state. 
Do F1 > developer tools > Application > Local Storage > search for `centerededitorlayout` and remove all those storage keys

If that still does not fix your issue we are introducing a grid layout soon which will make us re-write the centered editor handling which will definetely fix it for you :)
