### ISSUE TITLE
"Close to the Right" Sometimes Tries to Close Unsaved Files to the Left

### ISSUE THREAD

**Issue by sebmarkbage** [Microsoft/vscode#46887]
- VSCode Version: 1.21.1
- OS Version: macOS 10.13.3

I can't consistently reproduce it but it is possible to get into a bad state where newly created and unsaved files (Untitled-#) has this issue. The newly created unsaved files are lined up on the left after reopening the project (e.g. after an upgrade) and other files to the right of them.

After trying to close a set of files to the right using "Close to the Right". The view switches to one of the unsaved files to the left and a popup asks me to save them. It was trying to close files that I didn't intent to close and then I'm forced to cancel. Which leaves me with all files still open.

**Comment by bpasero** [comment]
@sebmarkbage can you show a screenshot when this happens or a video?

**Comment by sebmarkbage** [comment]
![vscodebug](https://user-images.githubusercontent.com/63648/38119391-416f9cba-3376-11e8-8d53-ee34e41b902d.gif)

**Comment by bpasero** [comment]
@sebmarkbage I am having a hard time to see an issue in your gif

**Comment by sebmarkbage** [comment]
@bpasero See how when I click "Close to the Right", it tries to close the tab to the left (Untitled-8). It shouldn't try to close any of the tabs to the left.

**Comment by bpasero** [comment]
@sebmarkbage I see, yes that looks like a bug. But I tried to reproduce this and I cannot, no matter what I try. So there must be steps involved that I am not doing. Can you try to reproduce this from our insider release (nightly builds) and if you can, remember what exact steps you did?

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by aleksijuvani** [comment]
I'm hitting this as well, both on the insider build (6b4d53cdab8bcae1eaaa4934d93c077319b573db) and the latest stable (1.21.1).

Here are the steps to repro:

1. Open a new window (Ctrl + Shift + N)
2. Close the welcome tab (Ctrl + W)
3. Open 3 new files (Ctrl + N)
4. Left-click on "Untitled-1" and type something in it
5. Right-click "Untitled-2" and select "Close to the Right"
7. Open a new file (Ctrl + N)
8. Right-click on "Untitled-2" and select "Close to the Right"
9. Bug will trigger here!

**Comment by bpasero** [comment]
@aleksijuvani thanks for the steps, I can reproduce that.
