### ISSUE TITLE
Diagnostic optional fields should be marked with ?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46880]
https://github.com/Microsoft/vscode/issues/46564

`relatedInformation` is not marked as optional with `?`, so after I construct a Diagnostic, I might expect it to be an empty array.

Side note, is it missing from `toJSON`?

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostTypes.ts#L757

**Comment by jrieken** [comment]
Nice find

**Comment by dbaeumer** [comment]
Verified in source.
