### ISSUE TITLE
Installer of VS Code Insiders show dupleciate message

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/vscode#4688]
- VSCode Version: 0.10.12 Insiders
- OS Version: Windows10
- Locale: Japanese

see following image:
![japaneseinstaller](https://cloud.githubusercontent.com/assets/9623009/14057467/be56fce8-f343-11e5-8b64-4ac07e160783.png)

**Comment by felixfbecker** [comment]
![image](https://cloud.githubusercontent.com/assets/10532611/14059539/96315de8-f344-11e5-9ac9-3cfdb7b29e42.png)

**Comment by joaomoreno** [comment]
Fixed.
