### ISSUE TITLE
Keyboard shortcut to scroll errors, parameter hints, and suggestions

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#46892]
Please add a shortcut to scroll lint errors, parameter hints, and suggestions windows, when they are too long. I can use my mousewheel to scroll them, but otherwise, it doesn't seem to be possible with the keyboard. I tried several keys, like Down Arrow, Page Down, Tab, etc.

**Comment by dbaeumer** [comment]
@jrieken not sure if you or @joaomoreno

**Comment by jrieken** [comment]
> scroll lint errors, ..., and suggestions windows,

We just did that for the upcoming release

**Comment by noinkling** [comment]
I'm seconding this, there doesn't seem to be any way to scroll through the description other than mousing over and using the scroll wheel.

![vscode](https://user-images.githubusercontent.com/4338251/42365115-ab9a8e14-8151-11e8-9632-117ce573721e.gif)

Am I crazy or was there a way to do this before?

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

**Comment by masaeedu** [comment]
@jrieken What combination of buttons should be pressed to cycle through the overloads when I'm in the situation below?

![image](https://user-images.githubusercontent.com/3674056/48175087-8d864380-e2d8-11e8-8e66-30b64e547136.png)
