### ISSUE TITLE
Codelens Freezes when double clicking in the codelens view.

### ISSUE THREAD

**Issue by rodolphito** [Microsoft/vscode#46893]
Issue Type: <b>Bug</b>

Open any project that has language support for reference counting and codelens, click on one of the `2 references` (or any number) links to open a Codelens view. Edit something in the codelens view (like add a comment, or anything really) and do not save. Now double click in the codelens view, to go to the file in full view mode.

Expected results: takes you to the file, leaving codelens.

Actual result: codelens glitches out and stops being interactable, cannot be closed, and often glitches out line numbers in the reference display. It also prints this in the corner if I try to close the codelens view clicking a reference count link:

`Cannot read property 'getStartPosition' of null.`

and if I press escape:

`Cannot read property 'getStartPosition' of null`

Doing a vs-code soft reload (reload command) fixes the bugged out codelens view, but the line number references are all garbled and highlight non-matching things, not the actual references. This persists past saves and soft reloads, the only way to fix is to actually quit the app and open it again. I did not file separate issues for these two problems (window being frozen, and line numbers being off) because they seem to have the same root cause: codelens not working properly with unsaved file modifications.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (18.28GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
haskelly|UCL|0.4.29
idris-highlighting|arc|0.0.2
code-runner|for|0.9.3
language-haskell|jus|2.4.0
python|ms-|2018.2.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
shader|sle|1.1.2
cmake|twx|0.0.17
cmake-tools|vec|0.10.4
Idris|zjh|0.9.8

</details>
Reproduces only with extensions

**Comment by jrieken** [comment]
Can you attach the stack trace that printed onto the console (F1 > Developer Tools > Console) or *even better*, select 'Break on all errors' in F1 > Developer Tools > Sources and provide the full trace and source (screen shot is enough) when this happens. Thanks

**Comment by rodolphito** [comment]
Here it is:
<img width="518" alt="screen shot 2018-03-29 at 12 07 33 pm" src="https://user-images.githubusercontent.com/11307157/38108561-16a6d72c-334a-11e8-97fa-4c144087c49f.png">
<img width="795" alt="screen shot 2018-03-29 at 12 08 30 pm" src="https://user-images.githubusercontent.com/11307157/38108562-16b93c32-334a-11e8-9fb6-0dc4ec3f849b.png">
Thanks

**Comment by jrieken** [comment]
Thanks. That's a good stack trace but it seems to come from the suggest widget... In your original comment you mentioned `getStartPosition` is called on `null`. Can you also reproduce that?

**Comment by rodolphito** [comment]
Sure! Im not sure what the suggest widget is, but if I hit resume execution it immediately errors again and yields the stack trace you are looking for:
<img width="414" alt="screen shot 2018-04-03 at 12 33 21 am" src="https://user-images.githubusercontent.com/11307157/38235688-d80a8762-36d6-11e8-87d1-b4ce668ad4f5.png">
<img width="536" alt="screen shot 2018-04-03 at 12 33 38 am" src="https://user-images.githubusercontent.com/11307157/38235693-da9e32b2-36d6-11e8-962c-06a3dd0b8dc8.png">

**Comment by jrieken** [comment]
Thanks.

**Comment by jrieken** [comment]
I was able to reproduce but I have pushed code to prevent the `getStartPosition` error from happening. Please try soon again with insiders. Leaving the suggest widget to @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@rodolphito I can repro this only in Stable 1.21 but not in Insiders. Can you try the latest [Insiders](https://code.visualstudio.com/insiders)?

@jrieken You were able to repro this in stable or insiders?

**Comment by jrieken** [comment]
Ops, should have said 'I was *not* able to reproduce'... I just added some fail-safe code without reproducing...

**Comment by rodolphito** [comment]
I can confirm it does not happen anymore in the latest insiders build. Thanks!

**Comment by jrieken** [comment]
Ok, tanks
