### ISSUE TITLE
Text of the Info Bounces when Typing by it

### ISSUE THREAD

**Issue by besteman** [Microsoft/vscode#46891]
- VSCode Version: 1.22
- OS Version: Windows 10

Steps to Reproduce:

1. Start typing
2. Text bounce on the info shown

![alt-text](http://besteman.io/3P1K3z230J21/Screen%20Recording%202018-03-28%20at%2010.28.34%20AM.gif)

**Comment by alexandrudima** [comment]
I could not reproduce:

![kapture 2018-03-29 at 17 48 11](https://user-images.githubusercontent.com/5047891/38098872-6416b12e-3379-11e8-8710-16a36a23ffc5.gif)
