### ISSUE TITLE
Column logpoints and column conditional bps

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46899]
According to https://github.com/Microsoft/vscode/issues/14784#issuecomment-269337531, this used to work, but now it doesn't seem possible to create a column BP or conditional BP at a certain column.

- Run "Add conditional breakpoint" from command palette
- Breakpoint is always not column specific 🐛 
- Add a column breakpoint
- "Edit breakpoint", add condition
- Breakpoint becomes not column specific 🐛

**Comment by isidorn** [comment]
I have fixed the second issue.
The first issue is as designed as we decided to have a special add column breakpoint action to make this explicit. Since F9 does not add a column, it does not make sense that the add conditional breakpoint adds a column imho
