### ISSUE TITLE
Installed git not recognized

### ISSUE THREAD

**Issue by kyberias** [Microsoft/vscode#4690]
- VSCode Version: 0.10.11
- OS Version: Windows 8

Steps to Reproduce:

1. Install Git for Windows (from https://git-scm.com/download/win, 64-bit)
2. Make sure it's in path. (Open cmd.exe, type git and verify it works.)
3. Install Vscode
4. Vscode complains that "It looks like git is not installed on your system."

**Comment by joaomoreno** [comment]
Can you tell me under which path git is installed?

You can always set the path to `git.exe` using the `git.path` configuration setting.

**Comment by kyberias** [comment]
C:\Users\jaakk_000>where git
C:\Users\jaakk_000\AppData\Local\Programs\Git\cmd\git.exe

**Comment by joaomoreno** [comment]
Can you show me what is in your `PATH` variable?

**Comment by tjpeden** [comment]
I'm having a similar problem. My git was working and then it stopped working and constantly says "Failed to execute git". I've tried settings git.path with no success.

**Comment by joaomoreno** [comment]
@kyberias @tjpeden Can you run `echo %PATH%` and show me the result?

**Comment by tjpeden** [comment]
What is it you're looking for?

**Comment by kyberias** [comment]
I'm not going to paste my full %PATH% here but at the end there's:

C:\Users\jaakk_000\AppData\Local\Programs\Git\cmd;C:\Program Files (x86)\Microsoft VS Code\bin

Does a 32-bit (?) VS Code work with 64-bit git?

**Comment by joaomoreno** [comment]
Sure. Which version of git do you have installed?

Does it work when you specify git's path exactly in the `git.path` configuration setting? In @kyberias's case, it would be `C:\Users\jaakk_000\AppData\Local\Programs\Git\cmd\git.exe`.

**Comment by kyberias** [comment]
I've installed the latest 64-bit version of Git from the above link at the time of opening this issue. As you can see from the installation directory, I've probably installed it only for my user account in Windows.

Look, I'm not looking for tips to workaround this issue. I've reported enough information to reproduce it. I don't think you need more information. **Have you tried reproducing it?** 

I could poke around in the source code and find the bug for you but I guess it should be easier for you to do it if you think this bug is important enough to be fixed.

**Comment by kyberias** [comment]
Also I think @tjpeden's issue here is a totally different one. It even has a different error message. Don't mix the two.

**Comment by joaomoreno** [comment]
No need to poke, [here it is](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/electron-browser/electronGitService.ts#L94). As you can see, we do look for it in some predefined folders, but ultimately we also simply try to execute it straight from the `%PATH%`.

Now, for some reason, in your system, `spawn('git'...)` doesn't seem to work. Meaning, `git` is definitely not in the `PATH` variable that Code.exe runs with.

Let's try something. Hit <kbd>Ctrl Shift P</kbd>, type `developer` and select `Developer: Toggle Developer Tools`. In there, go the Console and type `process.env.PATH`. Does the path under which `git.exe` is appear in that?

**Comment by tjpeden** [comment]
@joaomoreno the default path from that code you linked is where my git is at.

**Comment by joaomoreno** [comment]
@tjpeden Your issue is definitely different. If the default path is where your git is, and Code tells you `Failed to execute git`, then something is wrong in your system. Have you tried running some git commands from the command line? I'd suspect a broken config file, or a broken installation directory.

@kyberias ping

**Comment by solthoth** [comment]
Hello, I have a similar issue. I do have git installed and I overwrote the git.path setting to point to my program files directory, however once I did that I still get the issue. Side note, I am sure this may be the culprit, but my company recently installed security software to run unknown apps in sandbox mode and I know git & git-bash falls into this category. This is of course if they are executed directly from explorer.

**System info:**

*  Windows 7 **64-bit**
*  VSC Version **1.2.1**
*  Git Version: **2.7.1.Windows.1**
*  Git Path: *C:\Program Files\Git\cmd\git.exe*
*  Git Path (as shown in user settings - *override*): 
```json 
{
  "git.path": "C:\\Program Files\\Git\\cmd\\git.exe"
}
```

**Comment by joaomoreno** [comment]
@solthoth That is surely dues to the security restrictions.

Closing this issue.
