### ISSUE TITLE
`git commit` from WSL Bash with `code --wait` as editor opens COMMIT_EDITMSG in incorrect location

### ISSUE THREAD

**Issue by tlycken** [Microsoft/vscode#46908]
I have `git config --global core.editor 'code --wait'`, and a repository somewhere under C:\.

If I, from WSL Bash, do `git commit`, VS Code is launched or focused with a file called `COMMIT_EDITMSG` as expected, but it's in an incorrect location. Instead, of, as expected, opening `C:\path\to\repo\.git\COMMIT_EDITMSG`, it opens `C:\mnt\c\path\to\repo\.git\COMMIT_EDITMSG`. As a result, the workflow is broken - the commit message is never persisted, and `git commit` never exits.

As a workaroud, I have to make sure to `git commit` from PowerShell or CMD, which open the correct paths.

Not sure if this is a problem with `git`, with WSL or with VS Code.

**Comment by joaomoreno** [comment]
#9502
