### ISSUE TITLE
Horizontal progress is not stopping

### ISSUE THREAD

**Issue by mayurm-virtueinfo** [Microsoft/vscode#46901]
![vcs_bug](https://user-images.githubusercontent.com/25951058/38072190-e57426a2-3342-11e8-9433-d7263be09bee.png)
Issue Type: <b>Bug</b>

When i commit and push from Visual Studio Code from Source Control GIT. Even pushed successfully to my repository but horizontal progress bar  in SOURCE CONTROL : GIT which is placed above "Commit Message Textfield" is not Stopping.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 3.13.0-139-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X3 425 Processor (3 x 2700)|
|Load (avg)|2, 1, 1|
|Memory (System)|7.55GB (0.17GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
ignoregit|And|1.0.1
package-watcher|Gre|0.0.2
beautify|Hoo|1.3.0
elixir-ls|Jak|0.2.19
material-icon-theme|PKi|3.2.6
vscode-elixirc-mix-linter|PTD|0.0.3
html-snippets|abu|0.2.1
gitkit|alb|0.1.1
project-manager|ale|0.25.0
vscode-color|ans|0.4.5
vscode-hex-pm-intellisense|ben|0.1.1
git-easy|bib|1.9.1
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
jshint|dba|0.10.17
vscode-eslint|dba|1.4.8
git-extension-pack|don|0.1.3
githistory|don|0.4.0
gitlens|eam|8.1.1
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
vs-code-xml-format|fab|0.1.5
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
fs-flutter-snippets|fra|0.1.3
vscode-flatland-icon-theme|geb|0.0.6
gitattributes|has|0.4.1
live-html-previewer|hdg|0.3.0
elixirlinter|iam|0.4.1
easy-icons|jam|0.3.1
Angular1|joh|0.2.0
vscode-icon-theme|jtl|1.6.1
gitignore|mic|1.0.1
vscode-elixir|mjm|1.1.0
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.3.0
seti-icons|qin|0.1.3
java|red|0.21.0
sass-indented|rob|1.4.8
git-add-remote|sam|0.0.2
git-common-commands-suite|sam|0.2.2
git-pull-upstream|sam|0.0.7
ignore-gitignore|stu|1.0.1
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
cordova-tools|vsm|1.3.8
gitblame|wad|2.4.0
angular1-snippets-shark|yan|0.1.4
vscode-open-in-github|ziy|1.3.1

(8 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
Can you use a process explorer a see which git processes are running while the progress bar is running?
