### ISSUE TITLE
Feature: Show git output in notifications

### ISSUE THREAD

**Issue by eladcandroid** [Microsoft/vscode#46903]
To make it easy to see if the push has succeed or not.. (for example)
With an option to toggle this feature on settings

**Comment by joaomoreno** [comment]
Wouldn't this just be annoying?

**Comment by eladcandroid** [comment]
@joaomoreno Maybe can show a short success or failure with click for more details to take to the output itself..

**Comment by joaomoreno** [comment]
Still, a notification every time you'd run a git action would just overpopulate the notifications area.

**Comment by joaomoreno** [comment]
I'm really not convinced about this one, sorry @eladcandroid

**Comment by joaomoreno** [comment]
Yeah, there sure is. 👍

**Comment by eladcandroid** [comment]
@joaomoreno Notification on a git error? can you show me please when it shows up?

**Comment by joaomoreno** [comment]
Well, disconnect from the Internet and try the Pull action.
