### ISSUE TITLE
Issue Reporter and non-English Issues

### ISSUE THREAD

**Issue by justalemon** [Microsoft/vscode#46914]
Issue Type: <b>Feature Request</b>

The issue reporter should add a note that the issues are accepted only on English, even if the UI is localized on your current language.

VS Code version: Code - Insiders 1.22.0-insider (952b2a641da89a6c7bc28387474bc8afd47f0d2f, 2018-03-29T05:13:04.457Z)
OS version: Debian GNU/Linux 9.4 (stretch) x64 4.9.0-6-amd64

**Comment by RMacfarlane** [comment]
@justalemon There should already be a message displayed at the top when the UI is set to a non-English language:

![screen shot 2018-03-29 at 9 11 20 am](https://user-images.githubusercontent.com/3672607/38100093-40f23abc-3331-11e8-924b-fb99e5295892.png)

Do you not see this?

**Comment by justalemon** [comment]
My VS Code install is on Spanish but the windows is not localized yet:

![Repro](https://user-images.githubusercontent.com/11861253/38127281-dadd09e6-33cb-11e8-85f6-d65fe1fc8ceb.png)

**Comment by RMacfarlane** [comment]
Interesting, I haven't been able to reproduce. If I run `Configure Language` and set it to Spanish and relaunch VS Code, the issue reporter window is localized with the rest of the UI:

![screen shot 2018-03-30 at 10 59 02 am](https://user-images.githubusercontent.com/3672607/38147984-66c0f386-3409-11e8-8cb1-d80932699d1c.png)

Do you remember how you set the language?

**Comment by justalemon** [comment]
locale.json:
```javascript
{
	// Define el lenguaje para mostrar de VSCode.
	// Consulte https://go.microsoft.com/fwlink/?LinkId=761051 para obtener una lista de idiomas compatibles.
	// Al cambiar el valor se requiere reiniciar VSCode.
	"locale":"es"
}
```

Just updated and upgraded with apt:
![Repro](https://user-images.githubusercontent.com/11861253/38163030-8daf16de-34c3-11e8-8a67-76be93fc3d8e.png)

The system is still the same.

**Comment by RMacfarlane** [comment]
Thanks for the additional info! I've prepared a fix

**Comment by roblourens** [comment]
@RMacfarlane how do I verify this? Does it have to be the first launch?

**Comment by RMacfarlane** [comment]
@roblourens Yes, first launch with OS language set to something other than English
