### ISSUE TITLE
APT-based distros are not using the system tools to update VS Code

### ISSUE THREAD

**Issue by justalemon** [Microsoft/vscode#46911]
Issue Type: <b>Feature Request</b>

If you are using an APT based Linux distro (Debian, Ubuntu and derivates) and you try to install updates from the bottom-left side of the corner, VS Code will open the download page.

The editor can use `sudo apt-get update code` or `sudo apt-get update code-insiders` for the updates on the integrated terminal.

VS Code version: Code - Insiders 1.22.0-insider (952b2a641da89a6c7bc28387474bc8afd47f0d2f, 2018-03-29T05:13:04.457Z)
OS version: Linux x64 4.9.0-6-amd64

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43671
