### ISSUE TITLE
Markdown preview hotkey conflicts with paste

### ISSUE THREAD

**Issue by SkeLLLa** [Microsoft/vscode#46915]
- VSCode Version: 1.21
- OS Version: Linux

Steps to Reproduce:

1. Hit Ctrl+Shift+V in a terminal window

Expected behavior:
Text from the clipboard is pasted into the terminal window.

Actual behavior:
Popup `command 'markdown.extension.togglePreview' not found` is shown.

Does this issue occur when all extensions are disabled?: Yes

Proposition: remove default keybinding from system-wide `Ctrl+Shift+V` or replace it with something else

**Comment by Tyriar** [comment]
@SkeLLLa I think you may have a custom keybinding defined. The default in 1.21.1 on Linux is this:

```
{ "key": "ctrl+shift+v",          "command": "markdown.showPreview",
                                     "when": "editorLangId == 'markdown'" },
```

And it does not cause any issues when a markdown file is opened and the terminal has focus.

**Comment by SkeLLLa** [comment]
It looks like an old markdown extension that was deleted long time ago left its remains in keybindings.

**Comment by iwaseyusuke** [comment]
Sorry for jumping in to closed issue.

Please let me note how to solve the similar issue.

1. Open Keyboard Shortcuts Editor; File > Preferences > Keyboard Shortcuts. (Code > Preferences > Keyboard Shortcuts on Mac). See [Visual Studio Code Key Bindings].(https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor)

2. Search command(s) which caused an issue (in my case, command 'markdown.extension.togglePreview' was not found.

3. Right click and remove that keybinding.

This works fine for me! Thanks!
