### ISSUE TITLE
does issues 11081 fix now?

### ISSUE THREAD

**Issue by tim0991** [Microsoft/vscode#46918]
A question from https://github.com/Microsoft/vscode/issues/11081, but i don't know how to fix it

**Comment by aeschli** [comment]
Yes, #11081 is fixed now. 
Can you fill in the description what is still not working for you? Samples code and reproducible steps will be very helpful.

**Comment by tim0991** [comment]
vscode in windows is ok, but in mac till not work,

mac: 10.11.2 
vscode: 1.21.1 (1.21.1) 2018-03-14T14:34:33.071Z

**Comment by tim0991** [comment]
![kapture 2018-04-01 at 9 40 23](https://user-images.githubusercontent.com/26053904/38169021-b8ae28e8-3590-11e8-80e9-ca771f5f4dcb.gif)

**Comment by aeschli** [comment]
Can you run VSCode with extensions disabled? I tried to reproduce, but don't see what you see.
![html-comment](https://user-images.githubusercontent.com/6461412/38242650-a1a0b354-3735-11e8-8ce0-4d63215d24e3.gif)

**Comment by tim0991** [comment]
sorry, i forgot the extensions, and it is extension's bug
