### ISSUE TITLE
Surveys: listen to model save events instead of generic file events

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46917]
I would like to reduce our dependency to file events as much as possible and one client seems to be [`languageSurveys.contribution.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/surveys/electron-browser/languageSurveys.contribution.ts#L47). Instead of listening for each updated file I suggest to listen to model save events from the [`ITextFileEditorModelManager`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textfiles.ts#L155).

**Comment by isidorn** [comment]
@bpasero can you please review my change
fyi @joaomoreno

**Comment by bpasero** [comment]
@isidorn lgtm thanks
