### ISSUE TITLE
Original Type definition not navigable anymore when a type is augmented locally

### ISSUE THREAD

**Issue by lorthirk** [Microsoft/vscode#46910]
Issue Type: <b>Feature Request</b>

I needed to augment a type coming from an external module (namely `@uirouter/angularjs` so that an interfaces could have an optional parameter, otherwise I was receiving an error from the TypeScript compiler. So I went for my augmentation in a file:

```
import { Ng1StateDeclaration, Ng1ViewDeclaration, _Ng1StateDeclaration, StateProvider } from "@uirouter/angularjs";

declare module "@uirouter/angularjs" {
  interface Ng1StateDeclaration extends _Ng1StateDeclaration, Ng1ViewDeclaration {
    breadcrumb?: string;
  }

  class StateProvider {
    state(name: string, definition: Ng1StateDeclaration): StateProvider;
  }
}

```

The augmentation works fine, so that now the method call that has an Ng1StateDeclaration as parameter accepts an optional property `breadcrumb`:

```
import * as uiRouter from "@uirouter/angularjs";

$stateProvider: uiRouter.StateProvider;

$stateProvider.state("app.roles", {
  breadcrumb: "Roles",
  url: "/roles",
  views: {
    "view@state": {
      template: require("./views/roles-list.html"),
      controller: "RolesListCtrl as vm"
    }
  }
})
```

However, now if I cmd+click on `Ng1StateDeclaration` or `StateProvider.state()` anywhere in my code (both in the `type.extentions.ts` file and in the files that calls the method) I always get redirected to the symbols in `type.extentions.ts`, and I have no other ways to open the original type declarations.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

Steps to reproduce:

1. Create a new file TypeScript file to augment an interface exported in another module, using [TypeScript Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)
2. Go To / Show definition (or cmd+click on Mac)

Expected outcome: Both the original declaration and the augmented one are shown, or at least a dialog letting me choose which one to show

Current outcome: only the augmentation is showing, thus preventing me to check the original definition

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25742
