### ISSUE TITLE
Multi Quick Pick: onDidSelectItem fires for first item if Multi Quick Pick opens although the item is not selected.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#46916]
Steps

- multi select box with onDidSelectItem listener
- open

Observe: an event fires for the first item although the item is not selected.

**Comment by chrmarti** [comment]
I think the firing of an event is consistent with the single-select picker. Need to check why the first item is not shown as selected/focused.

**Comment by chrmarti** [comment]
The focused element in the list widget is not rendered as focused when the list does not have focus. That seems to be different from QuickOpen.

@bpasero This seems to have changed in the past two days.

**Comment by bpasero** [comment]
@chrmarti I pushed a fix for that, good catch.
