### ISSUE TITLE
Cmd-Q won't quit the editor 

### ISSUE THREAD

**Issue by predawnang** [Microsoft/vscode#46920]
- VSCode Version: 1.21.1
- OS Version: 10.13.3

I can't quit vscode on mac, I press on command + shift + esc to force quit it, and it seems didn't work. the gui still black

**Comment by dbaeumer** [comment]
Not sure if this is you @bpasero

**Comment by bpasero** [comment]
@predawnang I believe you are in a untypical state where VS Code is entirely frozen and this does not reproduce all the time?

**Comment by predawnang** [comment]
sorry so late. I am a novice for programing, I just downloaded vscode yesterday. And  I wanna use it for writting some code about scheme .I have installed some packages and themes.I want to ask whether this picture is helpful? 
<img width="1108" alt="1" src="https://user-images.githubusercontent.com/37857978/38095809-e26772b4-33a3-11e8-9bdf-7869126b32b1.png">

**Comment by predawnang** [comment]
thank you so much

**Comment by bpasero** [comment]
@predawnang can you run from the terminal: `code --verbose` and attach the output and see if it still freezes?

**Comment by predawnang** [comment]
it seems as if I am wasting your time. I am sorry about that. I've restarted the computer after I ask the questions about half hour. thank you so much

**Comment by predawnang** [comment]
if it happens again, I'll do it. thank you again

**Comment by bpasero** [comment]
Ok lets reopen when you can reproduce then.

**Comment by predawnang** [comment]
ok
