### ISSUE TITLE
Adding a custom emmet filter to vscode 

### ISSUE THREAD

**Issue by midgethoen** [Microsoft/vscode#46922]
Im trying to add a custom emmet filter to vscode, however im having some trouble figuring this out. 
 
So im trying to change the jsx className behavior of emmet using custom filters;
[see my former issue in the emmet repo](https://github.com/emmetio/emmet/issues/533)

Ive tried doing this by following the [customization section ](https://docs.emmet.io/customization/) in the emmet docs. However this is not possible because vscode does not interpret the extensionsPath directory as described there, as it does not load *.js files.

Looking further into how to extend emmet in vscode specifically, I end up at the `vscode-emmet-helper` package, but this is quite overwelming to me. 

I will continue looking into this. Some pointers to examples or anything I missed would be really helpful.

**Comment by matchu** [comment]
I'm trying to do something similar, and having the same confusion 😅

**Comment by midgethoen** [comment]
unfortunately, I never came around to figuring this out.

**Comment by ramya-rao-a** [comment]
Emmet in VS Code doesnt support any of the programmatic customizations listed in the [customization section ](https://docs.emmet.io/customization/) in the emmet docs.

Emmet in VS Code uses the [expand-abbreviation](https://github.com/emmetio/expand-abbreviation) module which is v2 of the existing emmet library

You can log an issue in the repo for the above module and ask @sergeche for guidance on how to add filters. For example: The `comment` filter is implemented in the [markup-formatters](https://github.com/emmetio/markup-formatters) module where as the `bem` filter is implemented in the [html-transform](https://github.com/emmetio/html-transform) module.

Ideally, you will be creating a module that is pluggable to the [expand-abbreviation](https://github.com/emmetio/expand-abbreviation) module via options.

Once you have that ready, I can help with integrating it in VS Code.

Hope that helps and sorry for taking so long to reply
