### ISSUE TITLE
Multi select: focus lost when clicking an item?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46926]
![flicker_chrome58](https://user-images.githubusercontent.com/900690/38085305-460b8f20-3350-11e8-8f56-66f37536ce43.gif)

It looks like once I click into an item focus is neither in the list nor in the input field?

**Comment by chrmarti** [comment]
The focus ends up on the checkbox. 🤔

**Comment by bpasero** [comment]
@chrmarti ah I did not see that, maybe it should just jump back to the input field?

**Comment by chrmarti** [comment]
That works for mouse operation. You can still tab through all checkboxes, which might or might not be expected given that the list already has a focus cursor to move through all elements. Do you understand the accessibility side of this?

**Comment by gushuro** [comment]
There's still an issue if you click and release the button outside the item.
Focus goes to the item clicked and typing doesn't work. Furthermore, if I navigate using arrow keys the item keeps its decoration.

![multipickdrag](https://user-images.githubusercontent.com/5607882/38157100-7f08fbe4-3438-11e8-9978-fbefdab9d8a8.gif)

**Comment by chrmarti** [comment]
Fixing this by clearing the selection. There is still the corner case where the list keeps the focus when the mouse button is released outside the item. That would need more investigation into the order of events to fix.
