### ISSUE TITLE
Multi select: use same color for item as quick open

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46924]
Compare this:

![image](https://user-images.githubusercontent.com/900690/38085237-150b255c-3350-11e8-887c-662c22376575.png)

To quick open:

![image](https://user-images.githubusercontent.com/900690/38085248-1b026e84-3350-11e8-93ef-621c2ad5c99e.png)

I think I would expect the same color in both cases even if quick pick is not focused.

**Comment by bpasero** [comment]
This actually uncovers a greater issue we have: many themes do not provide a color for the inactive focused element and so e.g. it looks weird in other themes:

![image](https://user-images.githubusercontent.com/900690/38085550-38f3d2b0-3351-11e8-8f7e-f17329ef2296.png)

**Comment by bpasero** [comment]
It looks like in quick open we set an option [`alwaysFocused`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L241) to get this. The list widget does not support this option and instead uses `:focused `selectors to determine the state of being focused. 

@joaomoreno would you be opposed if we added an option `alwaysFocused` also for the list and use a similar way by toggling a `focused` class instead of relying on the pseudo element?

**Comment by joaomoreno** [comment]
Sure.

**Comment by chrmarti** [comment]
Current solution seems to work fine. Will need to pay attention to this when moving the single-select QuickPick over.
