### ISSUE TITLE
Saving file with name that starts with dot fails 

### ISSUE THREAD

**Issue by tomi** [Microsoft/vscode#4693]
- VSCode Version: 0.10.12-insiders (ef2a1fcaa553d14d7731b284a5ac5e4a55c42936)
- OS Version: OSX El Capitan 10.11.3 (15D21)

Steps to Reproduce:

0. Open a folder
1. Open new untitled file (cmd+n)
2. Type any content
3. Save the file (cmd+s)
4. Name the file ".editorconfig"
5. In the prompt "Names that begin with a dot “.” are reserved for the system.", select 'Use "."'

New file is not created and VS Code behaves very slowly and strangely after this

**Comment by bpasero** [comment]
@tomi can you attach screenshots how this behaves? does it behave like that in other apps too? you seem to use the native file dialog of Mac OS X and not something VS Code specific?
