### ISSUE TITLE
High CPU usage from multiple instances of WMIC.exe on Windows 7

### ISSUE THREAD

**Issue by pybokeh** [Microsoft/vscode#46933]
Hello, below is my VSCode version on Windows 7:
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

After launching VSCode, I noticed my laptop fans would come on for extended amount of time.  So I checked the CPU usage and was shocked to find multiple WMIC.exe running and taking up a lot of CPU usage. I don't know what WMIC.exe is, but when I shutdown VSCode, the WMIC.exe instances are gone and my fans are no longer running feverishly and CPU usage is back to normal.

**Comment by Tyriar** [comment]
@pybokeh can you list the extensions you use? Also have you use debugger auto attach functionality?

This may be: https://github.com/Microsoft/vscode/blob/ab1669f8987c585c260e824584e3bf79c82fc064/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L60

@dbaeumer you should use windows-process-tree to prevent this.

/cc @RMacfarlane @weinand

**Comment by Tyriar** [comment]
Could also be https://github.com/Microsoft/vscode-python/issues/1036

**Comment by pybokeh** [comment]
@Tyriar I am only using the Python, VIM, and VSCode icons extensions.  Debugger auto attach functionality?  No.

OK, I just tried this:
Not sure if this matters, but I am using Python 32-bit environment, but my VSCode is 64-bit.  To see if things would improve, I then used 32-bit version of VSCode and now my CPU usage isn't as bad as before, but still averaging around 30-40%.  At least my fans aren't running like crazy!

Here is my user settings json file:
```json
{
    "python.pythonPath": "d:\\my_path\\python.exe",
    "telemetry.enableTelemetry": false,
    "editor.fontSize": 14,
    "editor.renderWhitespace": "all",
    "extensions.ignoreRecommendations": true,
    "extensions.showRecommendationsOnlyOnDemand": true,
    "workbench.iconTheme": "vscode-icons"
}
```

So maybe this is the fix for me for now.  I'll have to wait for longer session to see if my CPU usage does go crazy again, but so far ok.

**Comment by weinand** [comment]
@Tyriar I'm not aware of any evidence that the wmic problems occur with VS Code's builtin "status" feature or Node Debug's auto-attch feature.

So I'm pretty sure this is https://github.com/Microsoft/vscode-python/issues/1036

**Comment by Tyriar** [comment]
@pybokeh looks like it's the Python extension issue which should probably be fixed soon

**Comment by pybokeh** [comment]
@Tyriar Ok thanks.  Just wanted to report, my CPU usage briefly (a few minutes) went back to high again (fans kicked on) after letting my VSCode session run for a while, but then back to low (fans went back to normal speed).  So not sure what I did was really a fixed and so maybe it is the Python extensions issue.
