### ISSUE TITLE
Cannot remove PHP IntelliSense and PHP Debug exstensions

### ISSUE THREAD

**Issue by Coul92** [Microsoft/vscode#46931]
Issue Type: <b>Bug</b>

After click on Remove button on any of these extensions I click Restart button and PHP IntelliSense and PHP Debug extensions installs again 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|Memory (System)|7.88GB (0.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
php-debug|fel|1.12.2
php-intellisense|fel|2.3.0
auto-close-tag|for|0.5.6
csharp|ms-|1.14.0
team|ms-|1.122.0

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Can you uninstall other extensions?

**Comment by Coul92** [comment]
The problem solved after rebooting of PC. I've just installed a vs code and got that problem.

чт, 29 мар. 2018 г., 19:18 Rob Lourens <notifications@github.com<mailto:notifications@github.com>>:

Can you uninstall other extensions?
