### ISSUE TITLE
File "Collapse All" should only collapse selected folder

### ISSUE THREAD

**Issue by jakrams** [Microsoft/vscode#46937]
Issue Type: <b>Feature Request</b>

In the Explorer panel the "Collapse All" button simply collapses the entire tree. It would be nicer, if it would restrict this to the selected folder (and of course recursively all folders inside that one).

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

**Comment by usernamehw** [comment]
I think you can do that with <kbd>alt</kbd>+<kbd>Click</kbd>

**Comment by jakrams** [comment]
Oh nice, that works indeed.
