### ISSUE TITLE
Sorting word suggestions causes 500ms stalls

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#46930]
1. Create a file called `new.txt`
2. In a different software, open the attached file and select all and copy:
[large.txt.zip](https://github.com/Microsoft/vscode/files/1855332/large.txt.zip)
3. In VSCode, paste in the `new.txt` file
4. In VSCode, start typing.

Observe stalls caused by sorting word suggestions:
![image](https://user-images.githubusercontent.com/5047891/38085604-711e7a5a-3351-11e8-98f3-81d78e214a56.png)

[CPU-20180329T130255.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1859784/CPU-20180329T130255.cpuprofile.zip)

I wonder if we could sort the suggestions on the web worker side or perhaps limit them.

**Comment by jrieken** [comment]
> I wonder if we could sort the suggestions on the web worker side or perhaps limit them.

Well, they potentially come from different sources which make this complex... I could cheat and not sort them when there is only one provider...

**Comment by jrieken** [comment]
Apart from capping the ~60000 suggestions we could be smarter with sorting. Today, we use `strings#compareIgnoreCase` but later, when filtering we lower-case all strings anyways... We could do that upfront and use the operator-based compare.
