### ISSUE TITLE
Git commands are still running in the background when working with the built-in terminal

### ISSUE THREAD

**Issue by fredizzimo** [microsoft/vscode#46934]
Since https://github.com/Microsoft/vscode/issues/901 is closed for comments, I can't add new information there. 

I have been running with the built-in GIT completely disabled in order to not run into the issues reported by that bug. Since everything should now be fixed, I decided to try enable it again, but there are still problems.  I believe background updates are correctly disabled now when Visual Studio code is not focused.

But there are definitely still problems when running git commands in the built in terminal. All GIT commands should be disabled when the terminal is focused too. Ideally there should also be a fairly long timeout (a couple of minutes) until the next status update is made automatically, to prevent issues when accidentally focusing the editor. 

For now I will still have to run with `git.enabled: false`, `git.autorefresh: false` and `git.autofetch: false` to avoid running into problems.

Edit: ~~I just noticed that I  did have`git.autorefresh: false` and `git.autofetch: false` when it happens, but `git.enabled:true`~~
Edit2: Ignore the edit above. That was something else.

**Comment by joaomoreno** [comment]
We now use `GIT_OPTIONAL_LOCKS`, which should prevent these issues: https://github.com/Microsoft/vscode/issues/35513

Do you have a recent version of git?

What problems exactly do you notice?

**Comment by fredizzimo** [comment]
I'm running into the same locking issues as #901 describes. 

It's very easy to reproduce with Visual Studio Code 1.21.1, and the integrated terminal. On this computer I'm using Msys2 with Git version v2.16.2. But I previously reproduced on the terminal running WSL, I don't know which Git version that had.

Just open a decently sized project (a copy with it's own git clone of course), and open an integrated terminal. Then run `git rebase --force HEAD~100`, it takes at most a few tries to trigger this error:
```
fatal: Unable to create '/d/vscodegittest/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

I did some more testing now, and I managed to trigger it with an external terminal too, but just once. It might have been that I tried to run the command too soon after putting vscode out of focus. Anyway in the general case, vscode doesn't seem to be running git commands when not in focus anymore, because the blue icon doesn't flash, it still flashes when running commands from the integrated terminal though.

**Comment by joaomoreno** [comment]
@fredizzimo Is this still an issue for you? Do you simply run with disabled git due to it?

**Comment by wmakley** [comment]
I am seeing a similar issue with remote editing through WSL. I frequently cannot execute git commands, and get this error:

```
fatal: Unable to create '/d/vscodegittest/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

It also breaks every other Git tool viewing the repo, such as Sourcetree, IntelliJ, you name it.

**Comment by joaomoreno** [comment]
@wmakley Thanks for the update. I'll close this old issue since it's not WSL related.

What you have reported is https://github.com/microsoft/vscode-remote-release/issues/903
