### ISSUE TITLE
Multi select: should focus stay in input box when arrowing up/down?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46949]
Maybe this was an explicit design decision but imho it would be nice if focus would stay in the input box when I arrow up or down in the same way this works for quick open picker.

**Comment by bpasero** [comment]
Related: If you arrow down once from multi select, nothing visually happens. I guess what I would expect - similar to quick open - that the next item is selected in the list. But the moving of focus is very subtle.

**Comment by chrmarti** [comment]
We need to move the focus because we use Space to toggle checkboxes and Space is already taken in the filter text field for adding the space character. The workaround for #46924 has removed the distinction between active and inactive focus, that might need more thought.

**Comment by chrmarti** [comment]
I'll revert the workaround for #46924. The list needs to be able to have focus because Space works on both the checkboxes and the input field and not having a visual indication when the list has focus makes things worse.

**Comment by bpasero** [comment]
@chrmarti what happened to allowing to use `Ctrl+Space` and giving the user a hint?

**Comment by chrmarti** [comment]
@bpasero I think we should get it to work well without hints first.

**Comment by bpasero** [comment]
@chrmarti maybe then by default we should not select the first entry? It should get selected when I arrow down for the first time right?

**Comment by chrmarti** [comment]
That makes sense and seems to work well.

**Comment by chrmarti** [comment]
One problem with `Ctrl+Space` in the filter field toggling the currently focused item was that to make it work well you have to keep the focus in the filter field on arrow-up/-down and just move the focus in the list. That is hard to work with when you don't know `Ctrl+Space` making the discussed hint mandatory for the most basic keyboard operation.
