### ISSUE TITLE
Protractor breakpoints are not active until toggled off/on

### ISSUE THREAD

**Issue by asinitson** [Microsoft/vscode#46948]
Issue Type: <b>Bug</b>

### Steps to reproduce

1. Use this protractor configuration from [Microsoft/vscode-recipes/Angular-CLI/](https://github.com/Microsoft/vscode-recipes/tree/master/Angular-CLI)
```
    {
      "name": "ng e2e",
      "type": "node",
      "request": "launch",
      "program": "${workspaceFolder}/node_modules/protractor/bin/protractor",
      "protocol": "inspector",
      "args": ["${workspaceFolder}/protractor.conf.js"]
    }
```
2. Set breakpoint(s) in Visual Studio Code
3. Start debugging
4. All breakpoint(s) will be inactive. Hovering over them displays this message:
`Unverified breakpoint, Breakpoint ignored because generated code not found (source map problem?).`
5. Breakpoints are not hit

### Workaround steps

1. ...the same
2. ...the same
3. Add `debugger` statement somewhere before the breakpoints
4. Debugging will pause on `debugger` statement
4. **Toggle any of the breakpoint off/on**
5. All breakpoints become active and work as intended in this session
6. Restarting debugging disables breakpoints again and if you repeat the procedure they start working again

The same result is achieved if you toggle breakpoint off/on when protractor is running the .spec, but that's very fiddly, since you have to do it fast (otherwise you miss the breakpoint).

### Version details and configuration details

Node version: 8.10.0
Protractor version: 5.1.2

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|23.88GB (10.49GB free)|
|Process Argv|M:\home\bin\vscode\Code.exe -n|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

Tests are written in TypeScript and default Angular CLI configuration is used
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/e2e",
    "baseUrl": "./",
    "module": "commonjs",
    "target": "es5",
    "types": [
      "jasmine",
      "jasminewd2",
      "node"
    ]
  }
}
```
And here is `tsconfig.json`:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

A similar sounding issue was fixed in Insiders this month.

**Comment by asinitson** [comment]
Works correctly with Insiders' release. Thanks for the quick reply!

Any estimate when 1.22 will be out? I see that Insiders' release does not pickup my settings by default (I guess it does not by design).

For the reference Insiders' version details which works correctly:
VS Code version: Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T05:16:39.261Z)
OS version: Windows_NT x64 6.1.7601

**Comment by roblourens** [comment]
Great, thanks for following up. It will be released this week.

Insiders keeps a separate user data directory but you can copy your settings over if you want.
