### ISSUE TITLE
Expand selection

### ISSUE THREAD

**Issue by scottbickell** [Microsoft/vscode#46945]
Issue Type: <b>Bug</b>

Selection > Expand Selection doesn't work right. Please see IntelliJ Phpstorm for an example of expected behavior.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3200)|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (3.84GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
vsc-material-theme|Equ|1.5.1
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.2.6
html-css-class-completion|Zig|1.17.1
project-manager|ale|0.25.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
vscode-quick-select|dba|0.2.5
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.3
vscode-icons|rob|7.22.0
sass-indented|rob|1.4.8
ayu|tea|0.14.0
open-in-browser|tec|1.1.0

(4 theme extensions excluded)

</details>
Extensions don't impact behavior. Feature doesn't work, with or without extensions.

**Comment by roblourens** [comment]
Please explain the problem some more with repro steps.

Or see whether your issue is covered by any of the existing Expand Selection issues like https://github.com/Microsoft/vscode/issues/4795

**Comment by scottbickell** [comment]
Here's how it is supposed to work:
![ny-screenshot](https://user-images.githubusercontent.com/6173095/38701876-4d08c0ce-3e5c-11e8-9527-4a0ec8b6ef21.gif)

**Comment by roblourens** [comment]
I think it's tracked by https://github.com/Microsoft/vscode/issues/4795#issuecomment-346622659
