### ISSUE TITLE
Cannot click on line with inline decoration

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#46942]
- Run the extension
- Open a document with an empty 1st line
- Run the below command from the command palette
- Click anywhere on the line that has the decorator
- Attempt to type in the document

```typescript
const vscode = require('vscode');

exports.activate = function () {
    vscode.commands.registerCommand('inline_decorator_1st_line', () => {
        placeInlineDecoratorOn1stLine();
    });
};

function placeInlineDecoratorOn1stLine() {
    // Make sure the 1st line is empty to repro the issue
    const editor = vscode.window.activeTextEditor;
    const range = new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0));
    const decorationType = vscode.window.createTextEditorDecorationType({
        before: {
            contentText: "b",
            color: "yellow",
            textDecoration: "none; position: absolute;",
        }
    });
    editor.setDecorations(decorationType, [range]);
}
```

**Comment by Priya91** [comment]
@alexandrudima How does the added commit fix the issue? How should we use that API?

**Comment by alexandrudima** [comment]
@Priya91 What do you mean? This commit does not add new API, it fixes a case where clicking on an empty line with an inline decoration would not focus the editor.

**Comment by Priya91** [comment]
@alexandrudima I was looking at the referenced commit https://github.com/Microsoft/vscode/commit/150b85b2cd7b9adab34cabd2f72537f1fed2270a and misunderstood that this was the fix, so got confused. The second commit clarifies, thanks.
