### ISSUE TITLE
Is that possible to check the number of files that file watcher currently handles?

### ISSUE THREAD

**Issue by sgon00** [Microsoft/vscode#46943]
OS: Arch Linux

I am wondeirng how I can know whether or not `files.watcherExclude` setting works as expected. I think the easiest way is to check the number of files that vscode file watcher currently handles. But I failed to find a way to check this. I asked in gitter and search in google. but so far I don't find anything useful. 

I am very sorry if this is already documented somewhere.

**Comment by bpasero** [comment]
There is no way currently but we plan to improve file watching so that this is no longer needed.
