### ISSUE TITLE
Can't expand to check the data of a Variable when debugging pytorch code

### ISSUE THREAD

**Issue by rardz** [Microsoft/vscode#46950]
for the pytorch Variable object listed in the debug panel, expand to see its **data** part shows no tensor which suppose to have in a pytorch Variable, and among the items in **data**, there is another nested **data** part which have endless nested **data** part in it. 

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.1-gentoo
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.2.1
vscode-ai|ms-|0.1.7
cpptools|ms-|0.16.0
rust|rus|0.4.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please file an issue against the Python extension.
