### ISSUE TITLE
Pipe command

### ISSUE THREAD

**Issue by alexreg** [Microsoft/vscode#46957]
Could we get a command to pipe the current selection (or current file) through a shell command, and replace it with the output? This is a very useful feature that e.g. TextMate has.

**Comment by bpasero** [comment]
@alexreg you can do that already, e.g. `ps aux | grep code | code -`

**Comment by alexreg** [comment]
@bpasero No, you misunderstand. I want to pipe the current selection/file, from within the UI. It should be a feature of the VSCode app, not the CLI. See TextMate for a reference.

**Comment by ryu1kn** [comment]
@alexreg I’ve just happened to find this issue and wonder if what you’re looking for is what i developed as an extension...

https://marketplace.visualstudio.com/items?itemName=ryu1kn.edit-with-shell

**Comment by alexreg** [comment]
@ryu1kn Very handy, thank you. I probably should have guessed someone would develop an extension. I feel this sort of feature should be in-built, but am quite happy to use a well-made extension like this.
