### ISSUE TITLE
Option to treat external file opening as "selection" not as "split"

### ISSUE THREAD

**Issue by fgarcia** [Microsoft/vscode#46958]
- VSCode Version: 1.21.1
- OS Version: 10.13.3

It would be something similar to what MacVim already does by default. Opening a file from outside causes the app to relocate the cursor AND focus in the app, not to change the layout

Whenever I split a file I want two views of the same file, however if I click a file link from an external app (like a terminal file link) VSCode thinks I want a new Split, when actually I just want to select the working space and move my cursor to the error line I clicked.

The current UX assumes the user is using a laptop, but people with multiple monitors most likely will have 3-4 tabs with key files. While testing my apps I have two external terminal apps reporting errors, if I click an error in a stack trace I want to select the line of the tab with the file, not to destroy my workspace.

![bildschirmfoto 2018-03-29 um 19 57 16](https://user-images.githubusercontent.com/253157/38105119-77c9679a-338b-11e8-8bb8-35c3f8518ec0.png)

**Comment by roblourens** [comment]
Not sure I'm following your scenario. Are you saying that when you open a file from outside vscode, it opens in a new split editor?

**Comment by fgarcia** [comment]
the screenshot might be missleading because it has the word "split" and vim has the concept of "buffer".

Currently if I open a file outside vscode (ie: clicking on an test/error stack trace) a new tab will open within the last split that had focus. However if the file is open and visible within other split "and" the user was working in that split, then and only in that case vscode will focus and move the cursor to the line of the file. 

Focus or opening a new tab depends on the last active split. My previous UX was "focus" if the file was already open in all cases. However vscode tends to open new tabs, which destroys the screen layout I arranged for working (like one view for code and one view for tests).

**Comment by fgarcia** [comment]
Here is a screenshot of my normal workflow.

I have an external console that runs tests each time I save a file. 

With MacVim if I click on the stack trace with the file+line number the default is to focus on the tab already open. 

With VSCode a new tab is created on the lower split randomly (depending if that split had focus when I clicked outside)

In cases like this, normally I want to always view the code and the test. VSCode forces the user to constantly clean the redundant tabs or constantly concentrate in which part of the application is active

![bildschirmfoto 2018-04-01 um 09 40 44](https://user-images.githubusercontent.com/253157/38170995-c43b5f82-3590-11e8-9773-119092eac7c5.png)

**Comment by bpasero** [comment]
@fgarcia is that you want to force a file that opens to take the space of the last active file so that you prevent creating multiple tabs when opening files from outside within VS Code?

**Comment by fgarcia** [comment]
@fgarcia yes

By "split" I mean what happens after clicking on the "Split Editor" button.

In my screenshot if I am editing the lower split with the file MessageBus.js and I click on the external stacktrace file line, VSCode will open a new tab in the lower split, not selecting and moving the cursor of the upper split

**Comment by bpasero** [comment]
@fgarcia try with configuring `"workbench.editor.revealIfOpen": true`

**Comment by fgarcia** [comment]
that's it!

hopefully my issue will help others to find this setting
