### ISSUE TITLE
Emmet dont work

### ISSUE THREAD

**Issue by allanseleguim** [Microsoft/vscode#46955]
Issue Type: <b>Bug</b>

Emmet dont work, the extension ins correctly installed

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2365M CPU @ 1.40GHz (4 x 1397)|
|Memory (System)|5.89GB (2.40GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
mithril-emmet|Fal|0.7.1
php-intellisense|fel|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.3.0
vscode-css-peek|pra|2.1.0
LiveServer|rit|3.2.1
vscode-icons|rob|7.22.0
code-settings-sync|Sha|2.9.0
ionic3-snippets|sit|1.0.1
javascript-typescript|sou|0.0.5
autoimport|ste|1.5.3
bootstrap4-vscode|the|4.0.0
html-css-class-completion|Zig|1.17.1

</details>
Reproduces only with extensions

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent gotten any more details to work on
