### ISSUE TITLE
Performance issue reporter should pull in GPU features

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#46960]
Electron has an API that fetches the Chromium GPU-related flags [`app.getGPUFeatureStatus`](https://electronjs.org/docs/api/app#appgetgpufeaturestatus). This information would be very useful in determining whether the performance issue was caused by hardware acceleration being disabled.

FYI @bpasero

**Comment by RMacfarlane** [comment]
Added GPU feature status to the existing "My System Info" block
![screen shot 2018-04-03 at 9 46 04 am](https://user-images.githubusercontent.com/3672607/38263275-89ad7d56-3724-11e8-8889-ffd20b696fa6.png)

and also to `code --status`
![screen shot 2018-04-03 at 9 54 59 am](https://user-images.githubusercontent.com/3672607/38263500-1ff7b556-3725-11e8-9cbf-72792496af79.png)
