### ISSUE TITLE
ps-win.ps1 errors when running code --status

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#46963]
Extracted from https://github.com/Microsoft/vscode/issues/43169#issuecomment-377349218

```
Collecting CPU and memory information. This might take a couple of seconds.
[main 3:39:47 PM] Error: Get-WmiObject : Invalid class "Win32_Process"
At C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\base\node\ps-win.ps1:114 char:19
+ foreach ($item in Get-WmiObject Win32_Process -Filter "name = '$ProcessName'") {
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCom
   mand

Get-WmiObject : Invalid class "Win32_Process"
At C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\base\node\ps-win.ps1:117 char:19
+ foreach ($item in Get-WmiObject Win32_Process -Filter "name = 'codeHelper.exe'") ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCom
   mand

Get-WmiObject : Invalid class "Win32_Process"
At C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\base\node\ps-win.ps1:121 char:19
+ foreach ($item in Get-WmiObject Win32_Process -Filter "name Like '%'") {
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCom
   mand


    at ChildProcess.<anonymous> (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main
\main.js:157:375)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

It might make sense to transition to [windows-process-tree](https://github.com/Microsoft/vscode-windows-process-tree) v0.2.0 instead of fixing this. /cc @RMacfarlane

**Comment by dbaeumer** [comment]
@RMacfarlane does windows-process-tree offer CPU information as well ?

**Comment by Tyriar** [comment]
@dbaeumer it does as of about a week ago, you'll want to use these calls https://github.com/Microsoft/vscode-windows-process-tree/blob/bf4a0a2d2edf30acf7f2d856b0ed876a11475f23/typings/windows-process-tree.d.ts#L49-L62

**Comment by RMacfarlane** [comment]
@dbaeumer @Tyriar I also have https://github.com/Microsoft/vscode/issues/46433 tracking this as I want to reuse this same code path in the process explorer. I went ahead and made a PR for the change, @dbaeumer it would be great if you could take a look: https://github.com/Microsoft/vscode/pull/47152

The only issue I've run into with the `windows-process-tree` module so far is that the length limit on the commandLine property, 512 chars, sometimes results in the ends of arguments getting cut off for extHost processes. This throws off matching to calculate a better display name:
![image](https://user-images.githubusercontent.com/3672607/38260626-fcdd9a16-371c-11e8-98ac-e8514fccef92.png)

https://github.com/Microsoft/vscode-windows-process-tree/issues/23 is tracking that

**Comment by dbaeumer** [comment]
@RMacfarlane thanks a lot for providing the PR. I will have a look!

**Comment by RMacfarlane** [comment]
I updated the `windows-process-tree` module to have a length limit of 4096 for commandLine, have now merged in the changes to use it when listing processes, https://github.com/Microsoft/vscode/commit/6b62365d3812b19aab38c39cf6d9ed725166fa83

**Comment by dbaeumer** [comment]
@RMacfarlane +1 for merging that in.
