### ISSUE TITLE
Git-FR: Add `force push` option

### ISSUE THREAD

**Issue by dmstern** [Microsoft/vscode#46965]
- VSCode Version: 1.21.1
- OS Version: Windows 10

Sometimes you have to force push some commits. Unfortunately, you have to use the terminal for this. It would simplify the workflow if we had an option to do that via the UI.

*Suggestion 1:*
(Like `amend`): display the command in the source control context menu and command palette.

*Suggestion 2:*
When the user triggers the `push` command, show a modal dialog with a list of the commits the user is about to push and show a checkbox `force` in this dialog.

**Comment by joaomoreno** [comment]
Given the destructive power of this operation, I'd rather keep this a manual task.

**Comment by vn-ki** [comment]
Please reopen this. Atom supports this by ctrl clicking push button. It asks for confirmation too.

**Comment by dmstern** [comment]
The problem is, that if you use `rebase` instead of `merge` (or pull) to update your local feature branch onto a master or development branch (which is a very common git workflow), that you *have* to force push because you get an error every time you want to push your changes.

Since probably most people use `git force --push` in the terminal (which is a very powerful and sometimes dangerous operation, I agree with you, @joaomoreno ), maybe VSCode could implement such an option as 

```
git push --force-with-lease
```

to prevent accidentally overriding other people's work. (See [here](https://stackoverflow.com/a/37460330/1205127))
