### ISSUE TITLE
Issue to debug code in nodejs

### ISSUE THREAD

**Issue by renatoleite** [Microsoft/vscode#46967]
I have an issue to debug my server application in nodejs,  a some days ago the vscode was working fine, but without reason the debug stopped to work. Now, when I debug the code, vscode seems start the debug, but the application not launch the server.

To solve the problem, I tried many things, like:
- Restarted the computer.
- Reset the package.config
- Run vscode like administrator.
- Remove all extensions.

But unfortunately nothing works, someone can help with this issue?

VS Code Version 1.21.1
Shell 1.7.9
Node 7.9.0
Architecture x64

**Comment by renatoleite** [comment]
Node version: v8.10.0

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\server.js"
        },
        //RUN TESTS
        {
            // Name of configuration; appears in the launch configuration drop down menu.
            "name": "Debug tests",
            // Type of configuration. Possible values: "node", "mono".
            "type": "node",
            //Type of request
            "request": "launch",
            // Workspace relative or absolute path to the program.
            "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
            // Automatically stop program after launch.
            "stopOnEntry": false,
            // Command line arguments passed to the program.
            "args": [
                "./test/*.js",
                "--no-timeouts",
                "--colors"
            ],
            // Workspace relative or absolute path to the working directory of the program being debugged. Default is the current workspace.
            "cwd": "${workspaceRoot}",
            // Workspace relative or absolute path to the runtime executable to be used. Default is the runtime executable on the PATH.
            "runtimeExecutable": null,
            // Environment variables passed to the program.
            "env": {
                "NODE_ENV": "testing"
            }
        },
        {
            // Name of configuration; appears in the launch configuration drop down menu.
            "name": "Debug merge schema tests",
            // Type of configuration. Possible values: "node", "mono".
            "type": "node",
            //Type of request
            "request": "launch",
            // Workspace relative or absolute path to the program.
            "program": "${workspaceRoot}/lib/schema-merger/node_modules/mocha/bin/_mocha",
            // Automatically stop program after launch.
            "stopOnEntry": false,
            // Command line arguments passed to the program.
            "args": [
                "./lib/schema-merger/tests/**/*.js",
                "--no-timeouts",
                "--colors"
            ],
            // Workspace relative or absolute path to the working directory of the program being debugged. Default is the current workspace.
            "cwd": "${workspaceRoot}",
            // Workspace relative or absolute path to the runtime executable to be used. Default is the runtime executable on the PATH.
            "runtimeExecutable": null,
            // Environment variables passed to the program.
            "env": {
                "NODE_ENV": "testing"
            }
        }
    ]
}`

**Comment by JeffZen** [comment]
I am experiencing a similar problem as the above..

Have this defined in my file:
      "env": {
        "ENV": "local",
        "HOST": "localhost",
        "PORT": "5001"
      },

Terminal shows:
env "ENV=test" "HOST=localhost" "PORT=5001"

No matter what change I make to launch.json ENV does not update. 

If I change this to:
"ENV1": "local" - it will adds it but nothing I try passing ENV to terminal.

**Comment by weinand** [comment]
@JeffZen your Python problem is completely unrelated to the original node.js problem. Please file the issue against the Python extension.
