### ISSUE TITLE
References view shouldn't move scrollbar when clicking on a reference

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#46971]
Issue Type: <b>Feature Request</b>

* Paste: 
```ts
const a = 0;
a + 1;
a + 2;
a + 3;
a + 4;
a + 5;
a + 6;
a + 7;
a + 8;
a + 9;
a + 10;
a + 11;
a + 12;
a + 13;
a + 14;
a + 15;
a + 16;
a + 17;
a + 18;
a + 19;
```
* Find all references on `a`.
* Scroll to a reference that requires scrolling to (for me the first one is `a + 13`) and click.
* Now we want to view the next reference. It's hiddenScroll down and click on `a + 14`.
* Now we want to view the next reference, that's `a + 15`. We've scrolled down twice already, but when we click on a reference the editor has scrolls up to make it the bottom reference. The effect is that every time we want to click on the next reference we have to scroll down all over again. I think would be better if the scroll wasn't affected at all, or at least if it moved the reference to the center instead of to the bottom.

VS Code version: Code - Insiders 1.22.0-insider (952b2a641da89a6c7bc28387474bc8afd47f0d2f, 2018-03-29T15:50:12.706Z)
OS version: Linux x64 4.13.0-37-generic

**Comment by jrieken** [comment]
Thanks - nice find

**Comment by jrieken** [comment]
This is a regression from https://github.com/Microsoft/vscode/issues/46650
