### ISSUE TITLE
Unable to detect matching braces if part of comment

### ISSUE THREAD

**Issue by sumonto** [Microsoft/vscode#46975]
- VSCode Version: 1.21.1
- OS Version: Mac High Sierra

Steps to Reproduce: (with all extensions disabled)

int main(void) {
    int var = 0;

    switch (var) {          // <--- Select this, and cmd+shift+\
    //     case 0: {
    //         break;
    //     }
    //     case 1: {
    //         break;
    //     }
    //     case 2: {
    //         break;
    //     }
    // }                             <--- correct location (A)
}                                    <--- VS finds this one (B)

1) Should find (A)
    Instead finds (B)
2) VI does finds (A), shift+%

This is very useful while debugging a large code base, especially monolithic and legacy. So please don't punt it as not useful :)

**Comment by roblourens** [comment]
Well, that code is invalid, right? It seems much more useful that it would ignore braces in comments...

**Comment by roblourens** [comment]
You could implement an extension to do brace matching like this, but I don't think it's useful for VS Code itself.
