### ISSUE TITLE
When using vim extension, cursor navigation with keyboard doesn't trigger matching symbol highlights

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46978]
- Install Vim extension (I don't think an extension should be able to break this, so filing it here)
- Enter insert mode (or not)
- Move the cursor over a symbol in a TS file
- Matching symbols should be highlighted, but they are not
- If I click somewhere on the same symbol, then matches are highlighted

![mar-29-2018 17-52-34](https://user-images.githubusercontent.com/323878/38119907-04d2951a-337a-11e8-92e0-437ac9762707.gif)

**Comment by nerdmax** [comment]
+1

**Comment by diescake** [comment]
+1

**Comment by nerdmax** [comment]
I found a workaround! If you just want to highlight the current word, you can use `#` or `*` command to navigate previous or next matched word.

**Comment by forrestbaer** [comment]
Would nice to at least get typical mouse cursor functionality with a keypress, so i hover over a word or linter error or whatever and hit a key and I get the same effect as if I had hovered in that location.

**Comment by alexandrudima** [comment]
@rebornix Not sure 100% what you mean, but I think the problem here is that we lose the information that the cursor was moved due to a direct interpretation of a keypress (i.e. not like jump to definition or undo, etc)... Would be good if we would have a way to distinguish the vim case from the rest of the users of `TextEditor.selections`

**Comment by rebornix** [comment]
This issue was moved to VSCodeVim/Vim#3044

**Comment by rebornix** [comment]
I added a command for triggering the word highlight if there is no word highlighting available in the document (meaning the word highlighting feature is enabled but there are no decorations for current word). The Vim extension can decide when to call this command to run the word highlighting.

**Comment by mjbvz** [comment]
@rebornix Anything to verify on this or is it an upstream issue now?

**Comment by rebornix** [comment]
@mjbvz it's an upstream now, we added a command `editor.action.wordHighlight.trigger` now to trigger the highlight programatically so if that command works for you always, then it's valid.
