### ISSUE TITLE
Documentation for Keybinding Customisation should list `when' predicates

### ISSUE THREAD

**Issue by stephenmartindale** [Microsoft/vscode#4697]
- VSCode Version: 0.10.11
- OS Version: Microsoft Windows 10

Steps to Reproduce:

1. Visit the documentation at https://code.visualstudio.com/docs/customization/keybindings
2. Observe the truly excellent coverage of 'key' and 'command' and other concepts, particularly the "Accepted Keys" and "Keyboard layouts" subheadings.
3. Observe that there is no table of predicates that may be used for `when' attributes - there is not even a note about the use of logical operators.

Inside VS Code, when the default keyboard shortcut definitions are open, you can discover a few of the predicates by reading existing definitions. For example, without scrolling down, I can see that `editorTextFocus`, `inReferenceSearchEditor` and `editorHasSelection` all exist and that they can be combined with the `&&` operator. The only one that is mentioned in the documentation is `editorTextFocus`.

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/vscode-docs#249

**Comment by stephenmartindale** [comment]
Thank you. I'll make sure that I log issues re. docs with vscode-docs in the future. (Perhaps a note in the guide for contributions would be in order.)

**Comment by Tyriar** [comment]
@stephenmartindale no worries. It doesn't happen too often and is easy to move using https://github-issue-mover.appspot.com/ when it does. I'm a little hesitant to make the setup/contributing section any more busy.
