### ISSUE TITLE
Don't autosave when replacing in single file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#46983]
In #14554 we changed replace to autosave and not open all the files, which makes sense when a replace happens in tons of files. But I think that the old behavior is better for replacing a single entry, or replacing all matches in a single file, and we should keep it.

**Comment by sandy081** [comment]
There are following actions

- Replace all in current workspace
- Replace all in the folder
- Replace all in the file
- Replace a single entry

Except for the last, rest are bulk actions. If we go by edits, only last one should not be autosaved which I think will confuse the user.

**Comment by roblourens** [comment]
I think that single entry and file go together in that they both just operate on the one file that I'm currently editing, and the others can operate on lots of files. I guess it will be slightly arbitrary if we try to slice that list at all.

**Comment by roblourens** [comment]
Anyway I'll leave it up to yo

**Comment by sandy081** [comment]
I am kind of convinced to separate between file and multiple files. Will wait for the user feedback to proceed further.

**Comment by mgesmundo** [comment]
There is a new option to enable/disable the autosave behavior at all?

**Comment by sandy081** [comment]
@mgesmundo There is no option.

**Comment by jstarks** [comment]
Could you add an option? I very much dislike the new behavior.

**Comment by BroFox86** [comment]
+1 . The new behaviour is quite inconvenient with a small bunch of files. I still can't get used to it to the full.

**Comment by jstarks** [comment]
Is there a way to undo a find-replace with the new behavior?

**Comment by Alber70g** [comment]
Would it be useful to have two buttons: one being replace-on-disk and another one replace-in-editor?

**Comment by vSanjo** [comment]
Has there been progress on @jstarks or @Alber70g's idea? I can't seem to find an option for it anywhere. Sometimes a replace-all is much quicker than manual processing them, but I still expect errors in a few files. It'd be nice them not saving and ruining the workflow, just merely letting me work through the files that are broken within the editor.

**Comment by starball5** [comment]
Related to the requests for the ability to be able to access the older behaviour: [How to prevent auto saving files after 'Replace all' in Visual Studio Code?](https://stackoverflow.com/q/77124931/11107541)
