### ISSUE TITLE
shift+tab or tab doesnt seem to work in confirm dialog on MacOS

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#46987]
From twitter:

"@code When I close a workspace, a prompt asks me if I'd like to save it. I can hit esc to cancel or enter to save. Why can't I hit shift+tab or tab to highlight and then select "don't save"? This is on MacOS. I ❤️ VS Code by the way! You guys are doing great work."

https://twitter.com/LoganHoup/status/979072735283433472

**Comment by hu0p** [comment]
Hi there! That's my tweet. Please let me know if you need any additional information.

**Comment by roblourens** [comment]
I think those buttons are typically not tabbable on MacOS right? I see the same thing on some other dialogs.

**Comment by hu0p** [comment]
Wow. I can't believe I've never noticed that. After triggering similar dialogs elsewhere in MacOS, I don't think that's natively supported. That's unfortunate. Aside from that event, I can do almost everything without reaching for a mouse in VS Code.

**Comment by roblourens** [comment]
You can use cmd+d to trigger "don't save" (weird shortcut but works on all similar dialogs on MacOS)
