### ISSUE TITLE
Column selection in Ubuntu

### ISSUE THREAD

**Issue by cossio** [Microsoft/vscode#46980]
In Ubuntu, (Shift + ) Alt + Click drags a window. This conflicts with column selection. Perhaps the default key binding should be different in Linux?

**Comment by roblourens** [comment]
Does the `"editor.multiCursorModifier"` setting help? You can change it from alt to ctrl. Otherwise, https://github.com/Microsoft/vscode/issues/3130 for customizing mouse shortcuts.

**Comment by cossio** [comment]
@robertohuertasm  Perhaps the default key binding should be different in Ubuntu?
