### ISSUE TITLE
The problem of breakpoint debugging (node.js)

### ISSUE THREAD

**Issue by snoopy83101** [Microsoft/vscode#46984]
- VSCode Version:1.21.1
- OS Version:

Steps to Reproduce:

1.
require('babel-register'); 
require('./server/index.js')
2.
The breakpoint was originally on a line
When debug starts, jump to other lines

![image](https://user-images.githubusercontent.com/24613784/38122009-27d70a7e-3405-11e8-8a0f-69bb4ee311c1.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by zhiqiang21** [comment]
I have the same problem.

**Comment by roblourens** [comment]
@snoopy83101 I see you are using async/await with babel. Most likely, you are using babel to downcompile async/await. In that case, the sourcemaps that babel outputs are not very good.

If I'm wrong, or if chrome devtools handles this much better than vscode does, then please let me know or share your project with me.

Others, please open your own issues with as many details as possible.
