### ISSUE TITLE
Bug in version control tool.

### ISSUE THREAD

**Issue by OsvaldoAlc** [Microsoft/vscode#46982]
- VSCode Version: 1.21.1
- OS Version: Windows 10 version 1709

Steps to Reproduce:

1. In a project with a git repo make a change to one or more files and save.
2. The change will be reflected in the version control sidebar
3. Click the arrow to discard all changes the confirmation modal will show up, click accept.
4. The change/s will be discarded but the version control side bar will keep displaying that there are changes to be commited and the diff too will not show any difference in the files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is very likely a problem with your git line endings configuration. This is what happens when you undo all changes:

```
git reset -q HEAD -- .
```

If you run that command manually, does `git status` still return changes?

**Comment by OsvaldoAlc** [comment]
It was a git problem indeed.
