### ISSUE TITLE
Multiple Folders within code-workspace

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#46981]
When opening the `.code-workspace` file after creating a *workspace* if I have multiple folders within my workspace should they not appear within the `.code-workspace` file ? If so, I'm only seeing one folder, rather then two folders as seen within the visual code explorer workspace.

**Comment by roblourens** [comment]
You should see the same folders in the .code-workspace file that you see in the explorer.

Can you explain in more detail what you did and what you are seeing?

**Comment by SheepDomination** [comment]
I open the _projects_ `code-workspace` file within Visual Studio Code; and there is only one folder listed, rather then two as seen within the `workspace` of _explorer_ ?

**Comment by roblourens** [comment]
You will have to add that folder using the "Add folder to workspace" command, try that.

**Comment by SheepDomination** [comment]
I've already Added the folder to the workspace using the command.  It's not showing up within the `code-workspace` file ?

**Comment by SheepDomination** [comment]
There is only one `code-workspace` file regardless how many folders are within the workspace, correct ?

**Comment by roblourens** [comment]
Yes, unless you saved one somewhere else.

Can you share screenshots of what you are seeing, just so I am clear?

**Comment by SheepDomination** [comment]
![workspace_capture](https://user-images.githubusercontent.com/6827459/38183525-fbd2e5cc-360e-11e8-81a2-6006b20ebd7c.png)

**Comment by roblourens** [comment]
And what's in the code-workspace file?

**Comment by SheepDomination** [comment]
The only folder listed in the `code-workspace` file is the _something_ folder; along with it's path ?

**Comment by bpasero** [comment]
@SheepDomination can you attach it?

**Comment by SheepDomination** [comment]
This is the `code-workspace` file.
[Code_Projects.zip](https://github.com/Microsoft/vscode/files/1871439/Code_Projects.zip)

**Comment by bpasero** [comment]
@SheepDomination I can see two entries in that file though:

```json
{
	"folders": [
		{
			"name": "something",
			"path": "C:\\Python[Exercises]"
		},
		{
			"path": "."
		}
	],
	"settings": {}
}
```

**Comment by SheepDomination** [comment]
The path is more or less blank `.` and the `name` is non-existent for the second folder ?

**Comment by roblourens** [comment]
Name is optional, and `.` typically means "this folder". So this is working as designed.

**Comment by SheepDomination** [comment]
If `.` means the current folder; how do switch between folders and will this be reflected within the `code-workspace` file ?

**Comment by roblourens** [comment]
It means the folder that the code-workspace file is in.

**Comment by SheepDomination** [comment]
> It means the folder that the code-workspace file is in.
I understand, can one switch between folders and this will be shown in the `code-workspace` file.  In other words instead of showing the current folder represented by `.` I want to show the other folder in the current workspace and have this be shown in the `code-workspace` file ?

**Comment by roblourens** [comment]
You can add folders and remove folders. You can add absolute paths to folders or you can add relative paths (like `.`). I recommend experimenting with it.
