### ISSUE TITLE
No icons for files and folders in explorer view

### ISSUE THREAD

**Issue by OlivierHokke** [Microsoft/vscode#46996]
Issue Type: <b>Bug</b>

Since today, I am not getting any icons in my explorer view, so it is much harder to navigate my files. I don't have this issue with my other computer, but I can't really figure out why that is. It started before I updated to the February update, but after updating it did not fix anything. 

I tried this:
http://www.thewindowsclub.com/icons-not-showing-visual-studio-code
but my content-type value was already set to the correct value.

They started permanently breaking after I opened a second vs code window with an angular project, while the one already opened was a php project. Maybe these details help, but it may just as well mean nothing at all and be an unrelated issue.

Also, it doesn't matter if I enable or disable all extensions.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|15.91GB (7.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.1.9
path-intellisense|chr|1.4.2
vscode-simpler-icons|dav|1.5.2
angular-extension-pack|dog|1.0.2
vscode-generate-getter-setter|DSK|0.5.0
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.1
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
output-colorizer|IBM|0.1.2
angular2-switcher|inf|0.1.6
vscode-angular2-emmet|jak|2.0.3
docthis|joe|0.6.0
Angular2|joh|2.15.0
refactorix|kri|0.3.6
json-to-ts|Mar|1.5.4
Angular-BeastCode|Mik|5.2.23
csharp|ms-|1.14.0
typescript-javascript-grammar|ms-|0.0.38
material-icon-theme|PKi|3.2.6
tsimporter|pmn|1.2.14
ionic2|Tha|3.0.2
cordova-tools|vsm|1.3.8
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.17.1

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
Which file icon theme are you using?

**Comment by OlivierHokke** [comment]
unfortunately I haven't been on my home pc for a while, so I am not able to check at this point. I will get back to you when I can

**Comment by roblourens** [comment]
Please update if you can get more details, thanks.
