### ISSUE TITLE
Find match and selection highlight borders overlap

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#46995]
- VSCode Version: 1.21.1
- OS Version: macOS

![image](https://user-images.githubusercontent.com/10441177/38133345-766880f2-3417-11e8-9f02-566f9a6dee21.png)

2 custom border styles are applied, but correct is only the first one I pointed with an arrow.

`.monaco-editor .currentFindMatch` is applied if the currently selected word matches your selection in search widget. Which is correct.

`.monaco-editor .selectionHighlight` is applied also to currently selected word from search widget which is wrong that's why it doubles borders and you can't see `findMatchBorder`.

The expected behavior is to simply keep that `.selectionHighlight` but only if it's not selected word from search widget like I did with 2nd "one" word which has right now 2 different borders and they overlap each other, but last is `.monaco-editor .selectionHighlight` which is applied.

As a workaround, if I move `div.cdr currentFindMatch` to the end it works and it looks like this (which is correct):

![image](https://user-images.githubusercontent.com/10441177/38133499-33d68620-3418-11e8-8f2b-04fea4105034.png)

**Comment by roblourens** [comment]
Did you set findMatchBorder and selectionHighlightBorder, something like

```
"workbench.colorCustomizations": {
        "editor.findMatchBorder": "#ff0000",
        "editor.selectionHighlightBorder": "#00ff00"
}
```

? If not please provide more clear repro steps

**Comment by svipben** [comment]
@roblourens Yes.

```
"workbench.colorCustomizations": {
        "editor.findMatchBorder": "#528bff",
        "editor.selectionHighlightBorder": "#dddddd"
}
```

**Comment by alexandrudima** [comment]
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/38359344-64611616-38c8-11e8-8549-6ff3b33507c1.png) | ![image](https://user-images.githubusercontent.com/5047891/38359367-7abdeaba-38c8-11e8-82cd-cde3c6e0f86c.png) |
