### ISSUE TITLE
Keyboard binding for `ctrl+pausebreak' is impossible

### ISSUE THREAD

**Issue by stephenmartindale** [Microsoft/vscode#4699]
- VSCode Version: 0.10.11
- OS Version: Microsoft Windows 10

Steps to Reproduce:

1. Create a keyboard binding with `"key": "ctrl+pausebreak"`
2. Save file.
3. Observe that the command does not execute when the key combination is pressed.

For example, the following binding does not work:
`{ "key": "ctrl+pausebreak",
      "command": "workbench.action.tasks.terminate" },`

Bindings for `pausebreak` on its own and `shift+pausebreak` do appear to work. Additionally, the _define keybinding_ widget exhibits behaviour that is consistent with this bug.

`pausebreak` pressed on its own:

![2016-03-27 vs code ctrl pausebreak 1](https://cloud.githubusercontent.com/assets/6370145/14066807/8a0ccb90-f454-11e5-93e4-79d673d40c33.png)

`shift+pausebreak` pressed:

![2016-03-27 vs code ctrl pausebreak 2](https://cloud.githubusercontent.com/assets/6370145/14066808/8c93d99e-f454-11e5-97bd-5deca7c621f9.png)

`ctrl+pausebreak` pressed:

![2016-03-27 vs code ctrl pausebreak 3](https://cloud.githubusercontent.com/assets/6370145/14066809/8df9ee7c-f454-11e5-9618-6e91e2e703a8.png)

**Comment by alexandrudima** [comment]
I can confirm, it looks like we get a `keyCode = 3` when pressing `ctrl+pausebreak`, while for `pausebreak`, `shift+pausebreak` we get a `keyCode = 19`.

**Comment by alexandrudima** [comment]
Ok, looks like `ctrl+pausebreak` sends a `keyCode = 3` which gets its own virtual key named `cancel`.

I can only assume there were or there are some keyboards on the wild that might have a special `cancel` key and the OS? decided to make `ctrl+pausebreak` be the equivalent of the `cancel` key.

I can add support for a new `cancel` key code in our world.

From https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731%28v%3Dvs.85%29.aspx
```
VK_CANCEL    0x03    Control-break processing
```

**Comment by alexandrudima** [comment]
Should now work e.g.:
```
{
        "key": "ctrl+pausebreak",
        "command": "actions.find",
        "when": "editorTextFocus"
    }
```

**Comment by bpasero** [comment]
Sorry, I think I do not have this key on my keyboard.

**Comment by alexandrudima** [comment]
@aeschli Do you have this key on your keyboard? :)

**Comment by alexandrudima** [comment]
@bpasero That's because they wasted all the space on `F13`-`F16` :)

**Comment by bpasero** [comment]
:)
