### ISSUE TITLE
Markdown preview refuses to load badges from vsmarketplacebadge.apphb.com

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#46993]
Issue Type: <b>Bug</b>

The new security measures for the markdown preview are too strict and refuse to render badge images from the vscode market place:

<img width="1043" alt="bildschirmfoto 2018-03-30 um 11 38 38" src="https://user-images.githubusercontent.com/2398704/38133298-ea593b40-340e-11e8-9d32-bde179c9cd86.png">

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
Please try this in the latest insiders:

![screen shot 2018-04-02 at 11 04 02 am](https://user-images.githubusercontent.com/12821956/38208329-90d5a9b0-3665-11e8-89f6-cf15c049683e.png)

**Comment by mike-lischke** [comment]
Sorry for comming back so late, had to release a product myself. Thanks for fixing that, works now in Insiders.
