### ISSUE TITLE
Commenting using ctrl+k,ctrl+c does not work for JSX files

### ISSUE THREAD

**Issue by jpierson** [Microsoft/vscode#47]
Block commenting using ctrl+k,ctrl+c does not work for JavaScript React JSX files.

**Comment by jpierson** [comment]
To clarify, none the commands in the following list work form when working with jsx files with a jsx syntax.
![image](https://cloud.githubusercontent.com/assets/1467146/11246573/35ccf37c-8de6-11e5-8650-d10501368106.png)

Version 0.10.1
Commit df352367df2efcfa9d602d471e4e2f42140a0f05
Date 2015-11-17T15:25:33.342Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1

**Comment by tpai** [comment]
Version <= 0.10.1

Same here.

**Comment by egamma** [comment]
It was an oversight that we didn't add the a `language.configuration.json` definition for .jsx files.

**Comment by jpierson** [comment]
Is this something that we could work around by changing a configuration locally until the fix is officially released? I'm looking through the changes now and trying to figure out how that maps to the installed product on Windows.

**Comment by egamma** [comment]
These are no code changes and only configuration changes, so you can patch your installation with these changes. 

In the installed product the corresponding folder is `resources\app\extensions\javascript`.

**Comment by tpai** [comment]
That's great! Thanks @egamma, it has bother me for few days.
