### ISSUE TITLE
Font for PowerLine in terminal

### ISSUE THREAD

**Issue by marc31** [Microsoft/vscode#47003]
VSCode Version:newest
    OS Version: Os X
    zsh

I have a problem to display font for PowerLine in terminal.

To solve this I had read this (https://github.com/Microsoft/vscode/issues/15119#issuecomment-259248159) and  I put this in my config file.

"terminal.integrated.fontFamily": "MYFONTNAME"

But actualy to find MYFONTNAME was pretty hard.

Here is my solution :
1) Open font Book.app
2) Select your font (for me it was "DejaVuSansMono Nerd Font Livre")
3) click on the "i" on the left part of the window
![image](https://user-images.githubusercontent.com/14980392/38138645-31a36634-342c-11e8-966d-330482f64d02.png)
4) The MYFONTNAME is equal to PostScriptName.
![image](https://user-images.githubusercontent.com/14980392/38138700-890b4fa4-342c-11e8-8a53-fcc01a6751bc.png)

I hope it could be help.

**Comment by Tyriar** [comment]
Created https://github.com/Microsoft/vscode-docs/issues/1534 to add a FAQ entry on the website.
