### ISSUE TITLE
Hello World Extension example error

### ISSUE THREAD

**Issue by shepelevstas** [Microsoft/vscode#47001]
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:47:13.351Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

Following instructions from here: https://code.visualstudio.com/docs/extensions/example-hello-world

```
npm up -g yo generator-code
yo code
cd testhelloworld
code .
<F5>
```
`yo` and `generator-code` are just updated as they were already installed

Error:
Cannot connect to runtime process, timeout after 10000 ms - (reason: Response from the target seems invalid: ...
![untitled](https://user-images.githubusercontent.com/14919836/38136896-abc6f010-344b-11e8-8321-76de04c3be8f.png)

**Comment by roblourens** [comment]
This is another instance of https://github.com/Microsoft/vscode/issues/40501.

The suggestion from upstream was

> It looks like that user has a non-utf8 compliant path to VSCode.exe (this absolute path is what would be in the title on Windows).

Where do you have VS Code installed?

**Comment by shepelevstas** [comment]
I have vs code installed in the path suggested by setup: `c:\Program Files (x86)\Microsoft VS Code\`

**Comment by roblourens** [comment]
Ok. There aren't really any other suggestions from upstream. I'll try to work around this on our end...

**Comment by shepelevstas** [comment]
It it can help: the problem is present on my work desktop win7 + vs code 32bit version, but not on my other two PCs: desktop with win8.1 + vs code 64bit and laptop with win8.1 + vs code 64bit. All vs code apps are version 1.21.1

**Comment by shepelevstas** [comment]
Version 1.23.0-insider
Commit 6d7bb1a174f588360366af26a2ec8f27064ca110
Date 2018-04-26T05:16:57.657Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

All works OK!

**Comment by roblourens** [comment]
So now there's no error? Well I didn't do anything to fix it...

I'll close this since there's nothing I can do right now but please let me know if it pops up again.
