### ISSUE TITLE
can i use emmet in .vue and .blade file

### ISSUE THREAD

**Issue by izcream** [Microsoft/vscode#4700]
- VSCode Version: 0.10.11
- OS Version: Windows

Can i use emmet zen coding html in laravel blade file and vuejs .vue file

i try to search how to resolve but not found any resolve way

Thanks.

ps. sorry for my bad english

**Comment by egamma** [comment]
In the latest  [insiders build](https://code.visualstudio.com/download?insiders=true) you can associate file extensions to languages and the association is persisted, pls see: https://code.visualstudio.com/download?insiders=true. 

Could you try to associate the file types above with the html language to get emmet support?

**Comment by izcream** [comment]
thanks i gonna try this

**Comment by izcream** [comment]
i try to add files "files.associations": {"*.blade.php": "html" }
emmet working with tab but my blade syntax hilighting is not working

how to fix this problem

**Comment by mrmlnc** [comment]
See #9500.

@izcream or @egamma close this issue, please.

**Comment by egamma** [comment]
duplicate of #9500
