### ISSUE TITLE
Prevent autocomplete from importing random stuff from beyond root directory!!!!

### ISSUE THREAD

**Issue by techsin** [Microsoft/vscode#47005]
- VSCode Version: 1.21.1
- OS Version: Win10 64

Steps to Reproduce:

1. write `impf` and press Tab.

Does this issue occur when all extensions are disabled?: Yes

Problem is that I'm trying to trigger a snippet. So I type something that I THINK would trigger that snippet. Something like impf for `import ... from ....;`. But it goes ahead and find 50 random functions from node_modules and if you press tab it also goes and include it at the top. Not sure why it never does so for my modules, which would be very convenient, but it always does for node_modules. 

I don't understand under which scenario I'd need to add individual methods from node_modules. Usually node_modules contain whole package/libraries that you use not individual functions.

Is there a way to prevent this???

![](https://i.imgur.com/mDxev27.jpg)

**Comment by mjbvz** [comment]
Please share your `jsconfig.json`.

**Comment by techsin** [comment]
```
{
	"compilerOptions": {
		"target": "es6"
	},
	"exclude": [
		"node_modules",
		"../../node_modules",
		"**/node_modules/*"
	]
}
```

**Comment by mjbvz** [comment]
Where is the `jsconfig` within your project?

**Comment by techsin** [comment]
`frontend/src/jsconfig.json`

this is also where all frontend scripts are

frontend folder is at root of project along package.json, app.js, webpack.config.js, etc.

**Comment by mjbvz** [comment]
Try creating another jsconfig in the root of your project with: 

```json
{
	"exclude": [
		"node_modules",
		"**/node_modules/*"
	]
}
```

I don't think the one in the subdirectory can exclude `node_modules` using `../../node_modules`

**Comment by techsin** [comment]
tried starting with `code --disable-extensions` same result

**Comment by techsin** [comment]
moved `jsconfig.json` to root of project, no effect either

**Comment by techsin** [comment]
on windows 10 btw

**Comment by mjbvz** [comment]
Please try the current insiders build. 

If you still see this issue in that, please try collecting the tsserver log:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Run the `TypeScript: Open TS Server log` command. This should open a folder with a `tsserver.log` file. Open that file

Look for where the files from `node_modules` are being referenced. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by techsin** [comment]
I noticed if I delete local node_modules folder it doesn't show suggestions from global node_modules folder ../../AppData/......... weird..
[tsserver.log](https://github.com/Microsoft/vscode/files/1881105/tsserver.log)

**Comment by mjbvz** [comment]
Thank @techsin! I've moved the issue upstream to get this issue more attention: https://github.com/Microsoft/TypeScript/issues/23230

Can you please also test this using the just release VS code 1.22 and follow up on the upstream issue

**Comment by techsin** [comment]
My version updated to 1.22.1 yesterday. No difference.
