### ISSUE TITLE
git file status sometimes empty for modified files

### ISSUE THREAD

**Issue by MG55** [Microsoft/vscode#47008]
Issue Type: <b>Bug</b>

Sometimes files with modifications are not marked with "M" in git viewlet. I can't find a pattern to differentiate when this bug happens and when id doesn't; I'm using a workspace with single GIT root.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
material-icon-theme|PKi|3.2.6
quokka-vscode|Wal|1.0.116
html-css-class-completion|Zig|1.17.1
project-manager|ale|0.25.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
vscode-instant-markdown|dba|1.4.1
githistory|don|0.4.0
gitlens|eam|8.1.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
sass-lint|gle|1.0.1
vscode-esformatter|how|1.5.2
docthis|joe|0.6.0
angular-essentials|joh|0.3.2
Angular1|joh|0.2.0
Angular2|joh|2.15.0
vs-color-picker|lih|0.7.0
python|ms-|2018.3.1
debugger-for-chrome|msj|4.3.0
angular2-inline|nat|0.0.17
java|red|0.21.0
partial-diff|ryu|0.5.1
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
gitblame|wad|2.4.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by MG55** [comment]
![Sample of bug.](https://user-images.githubusercontent.com/13221616/38142752-dd82e9d2-343d-11e8-9285-ba999377228e.png)
Rows with no status indicator should have "M"

**Comment by jrieken** [comment]
Can you share the readings from 'F1 > Output > Git'. Thanks

**Comment by MG55** [comment]
As soon as it happens again I'll attach them ;)

**Comment by MG55** [comment]
Ricerca di git in: /usr/bin/git
Uso di GIT 2.15.1 (Apple Git-101) da /usr/bin/git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /Users/mg/hsbc/project.hsbc.wam-js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git show :src/app/modules/overview/overview.module.js
> git rev-list --left-right master...refs/remotes/origin/master
> git check-ignore -z --stdin
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/app/modules/overview/overview.module.js
> git show :src/app/modules/overview/overview.module.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/modules/overview/overview.module.js
> git show 0eb32e6ab009b847f23acae9f84996deef4f242e
> git show HEAD:src/app/modules/overview/overview.module.js
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/modules/overview/overview.html
> git show e79e30443057e662315aa0c292c8d7cae2f46693
> git show HEAD:src/app/modules/overview/overview.html
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/modules/overview/overview.controller.js
> git show d3fc11f402ab74633fa81c4c931e233ef91145ee
> git show HEAD:src/app/modules/overview/overview.controller.js
> git show :src/app/modules/overview/overview.module.js
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git show :src/app/app.module.js
> git show :src/app/components/breadcrumb/breadcrumb.component.js
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git show :src/app/components/components.module.js
> git show :src/app/app.module.js
> git check-ignore -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/app/services/userData/userData.js
> git check-ignore -z --stdin
> git show :src/app/services/websocket/websocket.provider.js
> git check-ignore -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git show :src/app/services/viewData/viewDataObserver.service.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/services/userData/userData.service.spec.js
> git show :src/app/services/userData/userData.service.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :package.json
> git show :webpack.config.js
> git check-ignore -z --stdin
> git show :config.json
> git show :webpack.config.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/services/websocket/websocket.js
> git check-ignore -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/services/websocket/websocket.js
> git show :src/app/services/userData/userData.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/services/viewData/viewDataObserver.service.js
> git show :src/app/services/websocket/websocket.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/services/userData/userData.service.js
> git show :src/app/services/userData/userData.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/services/websocket/websocket.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/app/app.module.js
> git show :src/app/services/services.js
> git show :src/app/app.module.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/app.module.js
> git show :webpack.config.js
> git show :src/app/app.module.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/services/websocket/websocket.js
> git show :src/app/app.module.js
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git show :mock-websocket/server.js
> git show :src/app/app.module.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/app/services/websocket/websocket.provider.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :config.json
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :webpack.config.js
> git show :src/app/services/userData/userData.service.spec.js
> git show :src/app/app.module.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :mock-websocket/server.js
> git show :src/app/app.module.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/app.module.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/app/services/websocket/websocket.provider.js
> git show :npm-shrinkwrap.json
> git show :package.json
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :mock-websocket/server.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/app/services/websocket/websocket.provider.js
> git show :mock-websocket/server.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git show :node_modules/ws/lib/WebSocketServer.js
> git show :src/app/services/userData/userData.service.spec.js
> git show :webpack.config.js
> git show :node_modules/ws/lib/WebSocketServer.js
> git show :mock-websocket/server.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :node_modules/ws/lib/WebSocketServer.js
> git show :src/app/services/websocket/websocket.provider.js
> git show :src/app/services/websocket/websocket.js
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/services/userData/userData.service.spec.js
> git show 17562d2abc70f2103f7af17e00c86c4414a3b854
> git show HEAD:src/app/services/userData/userData.service.spec.js
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/services/services.js
> git show e6ca2094d659d42e1986ec406dc2661bb326c0c9
> git show HEAD:src/app/services/services.js
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/modules/overview/overview.module.js
> git show 0eb32e6ab009b847f23acae9f84996deef4f242e
> git show HEAD:src/app/modules/overview/overview.module.js
> git checkout -q -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/modules/overview/overview.module.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/modules/overview/overview.controller.js
> git show d3fc11f402ab74633fa81c4c931e233ef91145ee
> git show HEAD:src/app/modules/overview/overview.controller.js
> git show HEAD:src/app/modules/overview/overview.controller.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git checkout -q -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/modules/overview/overview.controller.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show HEAD:src/app/modules/overview/overview.controller.js
> git status -z -u
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/modules/overview/overview.html
> git symbolic-ref --short HEAD
> git show e79e30443057e662315aa0c292c8d7cae2f46693
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git show HEAD:src/app/modules/overview/overview.html
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git checkout -q -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/modules/overview/overview.html
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/src/app/app.module.js
> git show 089c10a9bc53def3d7ed5ad66f828a0316cacd23
> git show HEAD:src/app/app.module.js
> git show HEAD:src/app/app.module.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :mock-websocket/server.js
> git ls-tree -l HEAD -- /Users/mg/hsbc/project.hsbc.wam-js/webpack.config.js
> git show 90c6992d366cecab7a0a0d99eadfc99c61081bae
> git show HEAD:webpack.config.js
> git show :mock-websocket/server.js


This output was catched with the following git status screenshot; in this case the not marked files are not the Changed ones but some of the Untracked ones.

![Untracked files not marked](https://user-images.githubusercontent.com/13221616/38550895-000ffbca-3cb8-11e8-904b-f30581c88f73.png)
