### ISSUE TITLE
Indent guides mismatch if statements without braces

### ISSUE THREAD

**Issue by svilenmarkov** [microsoft/vscode#47006]
Issue Type: <b>Bug</b>

Whenever you have an if statement which does not have braces the indent guides keep going forward rather than stopping after the first line underneath.

**edit**: the same issue exists with loops and switch statements. For the case of switch statements, the indent guide should stop after the `break;`. 

Example below is in PHP, however it appears to be the same in other languages which allow for braceless if statements. 

First image shows how it currently is, second image shows how it should be. 

![demo](https://user-images.githubusercontent.com/7613769/38141126-b0df9e16-342e-11e8-85d3-264c53e6f63e.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by hediet** [comment]
Indentation guides are language agnostic and only depend on the indentation (nothing else).

Thus, this also has to work:

![image](https://user-images.githubusercontent.com/2931520/137481931-f2c026dc-06fb-4d66-b420-a618d7626038.png)

In this screenshot, it does not make sense to interrupt the line from begin to end.

However, by just looking at the indentation, your example matches the example in the screenshot.

![image](https://user-images.githubusercontent.com/2931520/137482229-e97198b3-1fed-42ca-9276-2b647a2b1850.png)
