### ISSUE TITLE
C# syntax highlighting error

### ISSUE THREAD

**Issue by tristan957** [Microsoft/vscode#47009]
- VSCode Version: 1.21.1
- OS Version: macOS 10.13

Steps to Reproduce:

1. Create following code in C#
```csharp
unchecked // Overflow is fine, just wrap
{
    ...
}
```

2. Look at the comment highlighted in plain text

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#104
