### ISSUE TITLE
Ctrl + . (auto import in typescript) no longer works

### ISSUE THREAD

**Issue by ayyash** [Microsoft/vscode#47002]
Issue Type: <b>Bug</b>

Ctrl + . shortcut to add missing imports in typescript no longer works

VS Code version: Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T05:16:39.261Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|Memory (System)|15.93GB (8.98GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
scss-scan|aar|0.1.67
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
vscode-stylesheet-formatter|dba|0.2.0
githistory|don|0.4.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
auto-rename-tag|for|0.0.15
vscode-npm-dependency|how|1.2.0
Angular2|joh|2.15.0
code-beautifier|mic|2.0.3
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
mssql|ms-|1.3.0
azure-account|ms-|0.3.3
csharp|ms-|1.14.0
sass-indented|rob|1.4.8
bootstrap4-vscode|the|4.1.1
vscode-todo-highlight|way|0.5.12

</details>

**Comment by roblourens** [comment]
Please include some more details about your project

**Comment by mjbvz** [comment]
@jrieken I believe this was broken by df7ee603cb897a2edec4e45868321f00a200a020. I'll check-in a fix and take it into 1.22. Please quickly review my fix to make sure it makes sense for the original issue that df7ee603cb897a2edec4e45868321f00a200a020 targeted

**Comment by mduu** [comment]
Still having this issue in v1.22.2.

**Comment by mingzepeng** [comment]
Still having this issue in v1.22.2. windows 10
while I'm using  jsx, auto imports could not works well
`
let foo =  <TypeInfoSelect  />
`
ctrl+.  on **TypeInfoSelect**   ,  auto imports could not work
