### ISSUE TITLE
Task doesn't fail when command is a path that doesn't exist

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#47010]
While verifying https://github.com/Microsoft/vscode/issues/39720

Have a task like 

```
{
	"label": "My Task",
	"type": "process",
	"command": "${workspaceFolder}/doesNotExist.exe",
	"problemMatcher": []
}
```

Run the task. It says `> Executing task: C:\project\doesNotExist.exe  <` and never does anything. I would expect running that command to fail.

**Comment by roblourens** [comment]
Then if I terminate the task and try to start it again, I get "Terminal with ID 4 doesn't exist" cc @Tyriar. I can only repro that one in this one case, not when running a working task, so I'm guessing it's not a separate bug.

**Comment by Tyriar** [comment]
Might be https://github.com/Microsoft/vscode/issues/31301?

**Comment by dbaeumer** [comment]
Yes, looks like a dup of #31301
