### ISSUE TITLE
VS Code doesn't mark indentation changes in a Git repo

### ISSUE THREAD

**Issue by Eggbertx** [Microsoft/vscode#47019]
Issue Type: <b>Bug</b>

If I change the indentation style (from spaces to tabs) with the Ctrl+Shift+P option of a file in a Git repository, the file shows up in the list of modified files (as it should), but when I click to open them for comparison, I can see the change since I have editor.renderWhitespace set to "boundary" but there is no marker/indication.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.15.13-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3441)|
|Load (avg)|1, 0, 1|
|Memory (System)|15.60GB (7.38GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.3
Go|luk|0.6.77
cpptools|ms-|0.16.1
java|red|0.21.0
beeb-vsc|sim|0.0.6
vscode-hexdump|sle|1.6.0
vscode-java-debug|vsc|0.7.0
vscode-maven|vsc|0.6.0
markdown-all-in-one|yzh|1.1.1

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
`diffEditor.ignoreTrimWhitespace` is the setting you're looking for.

Or this button:

<img width="337" alt="screen shot 2018-04-03 at 10 47 18" src="https://user-images.githubusercontent.com/22350/38239227-6a70dc96-372c-11e8-839b-13e52d7927b5.png">
