### ISSUE TITLE
Ability to increment prefix when duplicating file/folder

### ISSUE THREAD

**Issue by iCyberon** [Microsoft/vscode#47014]
- VSCode Version: 1.22.0-insider
- OS Version: macOS 10.13.3

Currently VSCode increments suffix when copying a file. Copying `file.1.ext` makes `file.2.ext`. But there are cases when the `version` is specified in prefix not suffix, for instance when dealing with migrations we have files like `001-name.ext`, copying this results in creating a file named `001-name.1.ext` which is not the desired result. 

It would be great if VSCode could detect and increment the prefix if needed. It also requires minimal changes to `incrementFileName` method to add the functionality.

```ts
function incrementFileName(name: string, isFolder: boolean): string {

	// file.1.txt=>file.2.txt
	if (!isFolder && name.match(/(.*\.)(\d+)(\..*)$/)) {
		return name.replace(/(.*\.)(\d+)(\..*)$/, (match, g1?, g2?, g3?) => { return g1 + (parseInt(g2) + 1) + g3; });
	}

	// file.txt=>file.1.txt
	const lastIndexOfDot = name.lastIndexOf('.');
	if (!isFolder && lastIndexOfDot >= 0) {
		return strings.format('{0}.1{1}', name.substr(0, lastIndexOfDot), name.substr(lastIndexOfDot));
	}

	// folder.1=>folder.2
	if (isFolder && name.match(/(\d+)$/)) {
		return name.replace(/(\d+)$/, (match: string, ...groups: any[]) => { return String(parseInt(groups[0]) + 1); });
	}

	// file/folder=>file.1/folder.1
	return strings.format('{0}.1', name);
}
```

**Comment by iCyberon** [comment]
Testing something like `/^(\d+)(.*)(\..*)$/` should be enough to handle the case.

**Comment by isidorn** [comment]
If there is a simple PR to handle this case we would be happy to merge it in

**Comment by iCyberon** [comment]
Great, I'll make the changes and create PR

**Comment by roblourens** [comment]
This caused https://github.com/Microsoft/vscode/issues/50822 which we should take for May
