### ISSUE TITLE
VSCode icon doesn't look good in file chooser dialog

### ISSUE THREAD

**Issue by notandrew** [microsoft/vscode#47013]
Issue Type: <b>Bug</b>

1) In File Explorer, find a file that has no association with Code
2) Right-click on the file
3) Select 'Open With...'
4) Select 'Choose another app'
5) observe VS Code icon looks not that great in list of programs.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.17627

**Comment by roblourens** [comment]
Is this what you mean?

![image](https://user-images.githubusercontent.com/323878/38170276-f7b91a12-3535-11e8-8065-582dfc09f354.png)

**Comment by notandrew** [comment]
Yep. And it looks worse when your accent/theme color is blue...

**Comment by bpasero** [comment]
via https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#updated-visual-studio-code-icon
