### ISSUE TITLE
Dropdown in issue reporter has wrong border color

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#47012]
Issue Type: <b>Bug</b>

Check the image below:

![image](https://user-images.githubusercontent.com/16890566/38149532-b15a41d0-340f-11e8-9d62-526b22bacbdc.png)

VS Code version: Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T05:16:39.261Z)
OS version: Windows_NT x64 10.0.15063

**Comment by RMacfarlane** [comment]
Closing this as a duplicate of https://github.com/microsoft/vscode/issues/47012
