### ISSUE TITLE
Reference of syntax highlighting options

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#47018]
Is it possible to find a complete list of scopes of textMate scopes. I would like to change colours of particular types but can't find any comprehensive references?

**Comment by roblourens** [comment]
There isn't a standardized list. I think the best documentation is here: https://manual.macromates.com/en/language_grammars

Besides that, you can look at what other themes are using.

**Comment by moseleyi** [comment]
I don't really understand much from that page, how do I use it to change the syntax of certain types for certain languages?

**Comment by roblourens** [comment]
I recommend using the "Developer: Inspect TM Scopes" command to see what scopes are in effect in different places.

**Comment by roblourens** [comment]
Scopes usually contain the language id, so you can write rules that just target one.
