### ISSUE TITLE
Filelist shifts down when selecting files

### ISSUE THREAD

**Issue by xeor** [Microsoft/vscode#47015]
- VSCode Version: 1.21.1
- OS Version: osx

Steps to Reproduce:

1. Open a folder inside vscode
2. Select a file

The file selected is opened and the file become visible in the list at the very top of the navigation pane. This makes the files in the list "jump" one down, so the selected file is not under the cursor anymore.

This is annoying for multiple reasons:
  * I often want to look at the file, then doubleclick to pin it if it's the correct one.
  * I often need to open multiple files that is located near eachother. This is hard when they jump.

It would be much better if, when clicking a file, the top panel would glide over the project panel, instead of the project panel as a whole getting moved down.

**Comment by isidorn** [comment]
There are already issues around this (feel free to search)
As a workaround you can
1. Hide open editors section
2. Set a smaller number to 	`"explorer.openEditors.visible"`
3. 	"workbench.editor.enablePreview": false,
