### ISSUE TITLE
VS Code is suppressing parenthesis

### ISSUE THREAD

**Issue by propellingbits** [Microsoft/vscode#47017]
- VSCode Version: 1.17.1
- OS Version: macOS High Sierra 10.13

Steps to Reproduce:

1. Locate\Write a bit long expression similar to this one - if((check_car_s > car_s) && (check_car_s-car_s < min_front_dist*1.3))
2. Add a parenthesis ['('] on left side of above expression.
3. Scroll to extreme right side of the expression and make sure a parenthesis is highlighted and not a starting brace ('{')
4. VS code will suppress your keystroke when you will try to add a parenthesis [')'] on right side

Does this issue occur when all extensions are disabled?: Yes/No
Not applicable

**Comment by roblourens** [comment]
1.17.1 is a bit old. 
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders
