### ISSUE TITLE
editor.action.selectAll ctrl+a keybinding should only apply "when": "editorTextFocus"

### ISSUE THREAD

**Issue by charleswhchan** [Microsoft/vscode#4701]
- VSCode Version: 0.10.11
- OS Version: Linux Mint 17

Steps to Reproduce:
1. Open a node project vscode. (Note: project file includes app.js)
2. Click on app.js. --> File is open in editor.
3. Use Ctrl + A to select all text. --> Text in app.js highlighted.
4. Press Delete. 

Expect: All text in file to be deleted.
Actual: Are you sure you want to delete `app.js`?

Seems like a UX issue with context. It appears in step 3, the editor has the context; while in step 4, the explorer has context. 

In order to actually delete all of the text, I have to click in the editor window, select all text and press Delete.

**Comment by Tyriar** [comment]
I cannot reproduce this in Ubuntu 15.10

**Comment by charleswhchan** [comment]
According to https://en.wikipedia.org/wiki/List_of_Linux_Mint_releases, Linux Mint 17 is based on Ubuntu 14.04. Not sure if that makes a differences (or if the issue is specific to Mint)

Also, I should mention I am using the MATE edition in VirtualBox.

**Comment by Tyriar** [comment]
I wouldn't think it's to do with the OS. Is it 100% reproducible?

**Comment by charleswhchan** [comment]
Hi @Tyriar, I just try again and it is still reproduceable (at least on my machine :smile:)

Here's a screencast:
![vscode](https://cloud.githubusercontent.com/assets/679475/14234302/f9441776-f994-11e5-9a1b-a6e0a6b941b3.gif)

**Comment by Tyriar** [comment]
Ok so the problem is this keybinding:

```json
{ "key": "ctrl+a",                "command": "editor.action.selectAll" },
```

It doesn't feature `"when": "editorTextFocus"` meaning, it's a global shortcut. It definitely feels a little weird to me when the focus is on the explorer, not sure the reason this was done. This also applies to <kbd>ctrl</kbd>+<kbd>c</kbd>/<kbd>x</kbd>/<kbd>v</kbd>

/cc @alexandrudima

**Comment by bgashler1** [comment]
I've tried to reproduce but cannot in Ubuntu 14.03 LTS using VS Code 0.10.13-insider build.

**Comment by bgashler1** [comment]
However I absolutely agree that if this is actually happening that it's not the way it should be.  If the editor has focus, then a delete key should delete the text not the file.  Only the file deletion modal dialogue should appear when the explorer has context.

**Comment by Tyriar** [comment]
@bgashler1 it should be happening on all platforms, not just Linux.

**Comment by bgashler1** [comment]
I cannot reproduce on any platforms.
@charleswhchan would you try installing the latest [insiders build](https://code.visualstudio.com/Download#insiders) and seeing if that works?

Also, can you try this again on another OS?

**Comment by bgashler1** [comment]
Never mind, I misunderstood and was able to reproduce (I deleted my old, irrelevant comments to declutter).

Yes, @Tyriar you're right, this as global shortcut doesn't make sense to me either.  It's getting the `activeEditor` and selecting text when it doesn't have focus; I can't think of why we would want that.

## Proposed Solution
I noticed that on click of a file Sublime sets focus on their active editor.  We should do that as well.  And then it would make sense to also change the global shortcut to the `"when":"editorTextFocus" that @Tyriar proposed.

**Comment by Tyriar** [comment]
@bgashler1 that would make initiating explorer keyboard navigation impossible with the mouse (click + <kbd>&uarr;</kbd>).

**Comment by bgashler1** [comment]
@Tyriar actually Sublime and Atom both change the focus to the editor immediately (but both are able to use keyboard navigation as well).  In in both competing editors, if you click again on the explorer, focus returns to the explorer and remains.  Then you can use keyboard focus.  I actually think this method works quite well.

**Comment by Tyriar** [comment]
@bgashler1 it used to not focus the editor in 1.5.x. It looks like that's the default now and no setting in atom/tree-view to configure it.

**Comment by alexandrudima** [comment]
This works as designed. `selectAll` is a global shortcut due to its implementation: under OSX native inputs do not have a default select all behaviour. The `selectAll` command will therefore cover this case.
