### ISSUE TITLE
Open multiple instance of  dolphin in Linux

### ISSUE THREAD

**Issue by romanlex** [Microsoft/vscode#47027]
- VSCode Version: Версия 1.21.1
- OS Version: Linux, Plasma 5

Steps to Reproduce:

1. Select multple files ifrom one folder in resource tree
![image](https://user-images.githubusercontent.com/3369304/38163012-6eee20fa-34f5-11e8-9cec-4572afe8816f.png)

2. Open folder `Alt+Ctrl+R`
![image](https://user-images.githubusercontent.com/3369304/38163017-85749bec-34f5-11e8-88e8-cacec8d629d8.png)

3. Dolphin opened for each file

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Are you saying it opens an instance for each file incorrectly, or it should open multiple instances, and isn't?

**Comment by romanlex** [comment]
@roblourens I think what if i'm trying to open multiple files from one directory when it should open one instance

**Comment by roblourens** [comment]
I still don't understand

> Are you saying it opens an instance for each file incorrectly, or it should open multiple instances, and isn't?

**Comment by romanlex** [comment]
See https://youtu.be/aLGwkNBR7js
On this video you can see that opening the selected files inside one directory(!!!) leads to the opening of a multiple instance of Dolphin

**Comment by roblourens** [comment]
Thanks. It opens a single instance of Finder on Mac, I assume that's the expected behavior on Linux too.

**Comment by romanlex** [comment]
@roblourens  why this issues is closed? I think what I send all needed info

**Comment by isidorn** [comment]
Just tried and this works fine in Ubunto
We would probably accept a simple PR that fixes this for linux plasma
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L391
