### ISSUE TITLE
Slow Format Document / Go To Definitions with multiple folders open

### ISSUE THREAD

**Issue by PrzemyslawKlys** [Microsoft/vscode#47022]
- VSCode Version: 1.21.1
- OS Version: Windows 10 

Steps to Reproduce:

1. Open Visual Studio Code
2. Load a folder (with loads of scripts) - i have around 300 scripts scattered around 
- C:\Support\Scripts\Automated 
- C:\Support\Scripts\Includes
3. Try to use Go to definition or Format Document on .PS1 script
4. It will take a long time before anything happens. It's like both Format Document and Go to definition are jumping outside of the file and until they are done scanning everything nothing will happen. And by slow i mean 1minute+ slow. If i open just one folder it will be quick. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
This issue was moved to PowerShell/vscode-powershell#1254
