### ISSUE TITLE
Terminal shows previous commands behind git interactive rebase

### ISSUE THREAD

**Issue by valtism** [Microsoft/vscode#47028]
Issue Type: <b>Bug</b>

The following bug occurred when I previously used `git log`, then performed a `git rebase -i`. You can see that all of the characters that were not updated with rebase info are not cleared.

![bug](https://user-images.githubusercontent.com/1286001/38163086-e0e375a4-3539-11e8-9ce7-4393c575895e.png)

I assume this has to do with the performance improvements made to the terminal a few released ago. I am not sure if this is reproducible in a certain terminal display mode, or only in interactive git rebase.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.87GB (10.61GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
Looks like a generic winpty problem, tracking in https://github.com/Microsoft/vscode/issues/45693
