### ISSUE TITLE
Issue #7198 is closed but Im stillexperiencing the issue

### ISSUE THREAD

**Issue by siran** [Microsoft/vscode#47037]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Described in #7198

Does this issue occur when all extensions are disabled?: Yes

**Comment by siran** [comment]
This is not a duplicate

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/20876 https://github.com/Microsoft/vscode/issues/14298 https://github.com/Microsoft/vscode/issues/23107
