### ISSUE TITLE
Viewport colorization issues

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#47039]
A few times in the past week, I have seen issues that seem to be related to the viewport colorization changes.

After switching to a new file, I see a colorization issue, and if I scroll up I see  that it starts exactly where the viewport starts.

This time, the first white `public` was at the top of the viewport:
![image](https://user-images.githubusercontent.com/323878/38166978-317f6020-34e2-11e8-94fd-6b8e410106b1.png)

Switching tabs again doesn't fix it. Closing the file and reopening it does fix it. How can I help debug next time it happens?

**Comment by rebornix** [comment]
It's a limitation of the design as we render the viewport by heuristics (guessing by indentation).
