### ISSUE TITLE
Terminal produces repeated information when resizing

### ISSUE THREAD

**Issue by imba-tjd** [Microsoft/vscode#47034]
- VSCode Version: 1.21.1
- OS Version: Windows 10/7
- Terminal Type: PS/cmd

Steps to Reproduce:

1. open terminal and drag side bar as small as possible.

![qq 20180331234145](https://user-images.githubusercontent.com/24759802/38164844-36287084-353d-11e8-9697-8e4186bc2bbe.png)

2. input a long string.

![image](https://user-images.githubusercontent.com/24759802/38164856-760f6cac-353d-11e8-85dd-6e085b6448a6.png)

3. drag side bar to right.

![image](https://user-images.githubusercontent.com/24759802/38164900-18d3e986-353e-11e8-913d-5ba94b85f51a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26375
