### ISSUE TITLE
main window's close button.

### ISSUE THREAD

**Issue by Nareshgadri2** [Microsoft/vscode#47038]
Issue Type: <b>Bug</b>

Sometimes main window's(main frame) close button doesn't work properly.
Sometimes it takes too much time to close the window.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|Memory (System)|7.92GB (4.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by roblourens** [comment]
Can you give some more details about what you try and what happens?

**Comment by Nareshgadri2** [comment]
After finishing my work in visual studio code. i want to close visual studio code .when i click on close button that is located at right top of the window.that close button doesn't work properly .
i have to click 4 to 5 times but it may work of not.
sometimes i have to close visual studio forcefully.

**Comment by dbaeumer** [comment]
@bpasero I do see a little lag under Windows as well. But this is only in the range of < 100ms I would say.

**Comment by bpasero** [comment]
@Nareshgadri2 when you click once does it close eventually or not at all? how long does it take after you click once?

**Comment by Nareshgadri2** [comment]
sometime it takes too much time .i have to close forcefully.
i tried to close  and i pressed close button .i waited more than a minute but it didn't work today.

**Comment by Nareshgadri2** [comment]
when i close immediately after starting  it works but after doing some
 work it doesn't work.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
