### ISSUE TITLE
FETCH_HEAD duplicates with git client when repo on OneDrive

### ISSUE THREAD

**Issue by abrud** [Microsoft/vscode#47032]
- VSCode Version:  1.22.0-insider
- OS Version:  Windows 10 - Version 10.0.16299.309

Steps to Reproduce:

1.  Open in Code a OneDrive based folder containing a git repo 
2.  After a while a windows notification appears about FETCH_HEAD duplicate file
![image](https://user-images.githubusercontent.com/12251466/38164055-be567f5a-34d4-11e8-8a36-7919175969b7.png)
3. The notification repeats itself every few minutes
4. In the repo home folder, .git subfolder contains FETCH_HEAD duplicate files.
![image](https://user-images.githubusercontent.com/12251466/38164080-1b301402-34d5-11e8-9fb2-455e36367328.png)

This issue is the same as issue #523 of the project Microsoft/sqlopsstudio:
https://github.com/Microsoft/sqlopsstudio/issues/523

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Please don't use git repositories inside OneDrives. It's just asking for trouble.

Also, this is irrelevant to VS Code.

**Comment by abrud** [comment]
Thanks for your help!

Corneliu Popescu
+56 9 94527007
________________________________
