### ISSUE TITLE
[string].Format(String Template, Object Parameters())

### ISSUE THREAD

**Issue by dwneder** [Microsoft/vscode#47035]
There are tons of string manipulation tools already available directly as subclasses from the String class: Replace, SubString, Trim, etc., etc.

I suggest adding an additional one: Format.

This would work identically to String.Format() except that it would derive directly from the string itself. Example:

Dim myString As String = ""
Dim myFormat As String = "{0} is another way of {1} strings"

myString = myString.Format(myFormat, ".Format", "loading")

Console.Print myString

Result: 

.Format is another way of loading strings

**Comment by roblourens** [comment]
It sounds like you are trying to suggest a feature for VB or .NET. This is the repo for vscode the text editor.
