### ISSUE TITLE
Update VS Code offline<feature request><update>

### ISSUE THREAD

**Issue by CroftLuke** [Microsoft/vscode#47030]
#update VS Code offline
Due to some information security reasons, in my company, working computers cannot connect to the Internet, so the vs code in these computer cannot update. It's so bad! but our local desktops can access network, so **I wonder if we can download a update pack, like a zip file or anything, then apply it to the vs code to update it offline?**
Thanks!

**Comment by roblourens** [comment]
You could just download the installer and install vs code each time there's an update. Your user data and extensions will be left alone. You may have to uninstall it first though.

**Comment by joaomoreno** [comment]
No need to uninstall. Just install it over.
