### ISSUE TITLE
VSCode Markdown Parser Bug for Extensions README.md

### ISSUE THREAD

**Issue by ahmadawais** [Microsoft/vscode#47033]
I am about to launch a new theme next week, called [Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple).

The issue is that the README.md file is being parsed completely fine at GitHub and at VSCode Marketplace. But inside VSCode the markup is not being parsed :( 

Take a look at this screenshot.

![image](https://on.ahmda.ws/qY8s/c)
![image](https://on.ahmda.ws/qY6u/c)

- VSCode Version: 1.21.1

```
Environment:
  OS: macOS Sierra 10.12.6
  CPU: x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.7.1
  Watchman: Not Found

Browsers:
  Chrome: 65.0.3325.181
  Chrome Canary: Not Found
  Firefox: 57.0.1
  Firefox Developer Edition: 57.0
  Firefox Nightly: Not Found
  Safari: 11.0
  Safari Technology Preview: Not Found

```

**Comment by mjbvz** [comment]
Bug in marked library. Opened https://github.com/markedjs/marked/issues/1195 to track this upstream

**Comment by UziTech** [comment]
A quick fix would be to put new lines after the end of closing tags. [demo](https://marked.js.org/demo/?text=%3Ctable%3E%3C%2Ftable%3E%0A%3Cbr%2F%3E%0A%0A%23%20heading%0A%0A%3Ctable%3E%3C%2Ftable%3E%0A%0A----------------------------%0A%0A%3Ctable%3E%3C%2Ftable%3E%0A%0A%3Cbr%2F%3E%0A%0A%23%20heading%0A%0A%3Ctable%3E%3C%2Ftable%3E)

**Comment by ahmadawais** [comment]
Thanks @UziTech for the tip. I did that so the issue is resolved for now but Markedjs could really be improved by this.

**Comment by UziTech** [comment]
Thanks. We are currently trying to [raise marked from the dead](https://github.com/markedjs/marked/issues/1106). Any help would be appreciated. 😁

**Comment by ahmadawais** [comment]
@UziTech I'll see what I can do apart from sharing it with my network 👍

**Comment by mjbvz** [comment]
Fixed by picking up a new copy of marked.

For verification, create an extension that has this `README.md`: https://raw.githubusercontent.com/ahmadawais/shades-of-purple-vscode/2828bb0c51ba950790cf3e084475d125205a1921/README.md

Some headers and other content used to show up raw, i.e. as `### header` in the output. This should not happen in fixed vscode versions
