### ISSUE TITLE
Editor scrolls to end after reverting change using inline control

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#47041]
- Have file with just one change
- Click git decoration to bring up inline diff
- Revert change
- Editor scrolls to the very end

**Comment by pradeepmurugesan** [comment]
![no-repro](https://user-images.githubusercontent.com/528317/38258395-a434bc00-3762-11e8-8593-828f8faf45a8.gif)

Hello I am not able to repro the issue.. Let me know if I am missing something.

**Comment by pradeepmurugesan** [comment]
@joaomoreno I looked in the code where we revert the changes https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L750

But looks like the issue is with the inline diff. When I revert one it navigates to show the next diff and eventually reaches the end of file if there is only one change.. 

Can you guide me with the code pointer where the inline diff module is located. I am not able to find it.

**Comment by shobhitchittora** [comment]
@pradeepmurugesan According to my findings, this is reproducible in Code Insiders only. Probably due to a recent change. Can you confirm this ?

**Comment by pradeepmurugesan** [comment]
@shobhitchittora Yes its reproducible in master.

**Comment by shobhitchittora** [comment]
the `index` param is always `0` as per my investigation. Please verify.
https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L718

**Comment by pradeepmurugesan** [comment]
I think my first finding was wrong. 

If there are multiple changes in a file, the cursor position is set to the end of the file when the revert happens for the first time..

**Comment by shobhitchittora** [comment]
@pradeepmurugesan  these are my findings while running Code-OSS ( debugging the latest master ) -

1. Make 2 changes ( a few lines apart ).
2. Revert the 1st one ( inline diff view ) -> the cursor moves to the end and then jumps the Inline diff view for the 2nd change.
3. Revert the 2nd change -> the cursor moves to the end and stays there.

**Comment by pradeepmurugesan** [comment]
yeah.. The first revert causes the cursor to go down.. The second revert is optional.. Even if you close the second inline diff, the cursor is staying down.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/528317/38298916-ff32a61c-37f8-11e8-90bb-88297c00a900.gif)

**Comment by pradeepmurugesan** [comment]
I tried logging the edit object that we are applying in the [line](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L772) 

The edit object contains the new contents (after revert).. So my guess is, the editor rewrites the new file contents from top to bottom which leaves the cursor at the end.

**Comment by pradeepmurugesan** [comment]
@joaomoreno  Are we going in the right direction ?

**Comment by joaomoreno** [comment]
> So my guess is, the editor rewrites the new file contents from top to bottom which leaves the cursor at the end.

Sounds good.

It will be tough to fix... maybe the fix should go in the Git extension, which is the one causing the model change. Maybe record the position before and reset it after the change?

**Comment by pradeepmurugesan** [comment]
@joaomoreno yeah that was the idea I had in my mind.. But couldn't find the interface to set the cursor position.

Can you give some pointers there ?

**Comment by joaomoreno** [comment]
That would be here: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1077

**Comment by pradeepmurugesan** [comment]
Great. thanks..
