### ISSUE TITLE
Typescript generics on arrow functions break syntax highlighting for rest of file

### ISSUE THREAD

**Issue by MarkKahn** [Microsoft/vscode#47049]
Issue Type: <b>Bug</b>

```js
function foo<T>(n:T): T { return n; }
function foo(){}
const foo = <T>(n: T): T => n;
function foo(){}
```

yields:

![image](https://user-images.githubusercontent.com/320562/38170249-8f89d472-35b2-11e8-868a-f04989b1d8af.png)

Notice that syntax highlighting is broken on the last line (and every line that follows).  There are several issues that already report this for flow (e.g. #35478, #33205, #45450), but the exact same issue occurs with TypeScript code

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 1400)|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (1.30GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
quokka-vscode|Wal|1.0.116
wallaby-vscode|Wal|1.0.79
vscode-custom-css|be5|2.7.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
prettier-vscode|esb|1.2.2
flow-for-vscode|flo|0.8.0
theme-monokai-pro-vscode|mon|1.1.5
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.3.0
language-stylus|sys|1.9.1
markdown-all-in-one|yzh|1.1.1
vscode-proto3|zxh|0.1.3

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
Is the language mode of your file `Typescript` or `TypeScript React`?
