### ISSUE TITLE
Slow like hell

### ISSUE THREAD

**Issue by gmak123** [Microsoft/vscode#47046]
it is really a good App, implement it in a diffrent technology than javascript, because it is slow.

**Comment by roblourens** [comment]
If there is something specific that is slower than it should be, we can try to figure out whether it's a bug. But we are not likely to switch from javascript.

**Comment by gmak123** [comment]
No nothing specific other than the UI and loading big files, and i don't think that there is some bug somewhere, it is just a common feature among electron Apps.
thanx anyway.
