### ISSUE TITLE
Language nested syntax

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#47043]
Is it allowed to separately configure syntax highlighting of another language within another language?
Sometimes I have to use 

$q = "SELECT * FROM table";

and I would like VSCode to apply the same styling as it would have for any other SQL file. Can it be configured automatically?

**Comment by roblourens** [comment]
I do see this for PHP strings that start with SELECT

![image](https://user-images.githubusercontent.com/323878/38170213-d345c22c-3533-11e8-8a54-851b08cf5833.png)

But it may not work in every theme. Which theme are you using?

**Comment by moseleyi** [comment]
I'm using Egoist One but ideally I want to create my own. Can this be enabled in different themes?

**Comment by roblourens** [comment]
I see this in Egoist One too. Maybe a found a different version of that theme. 

![image](https://user-images.githubusercontent.com/323878/38175868-be04d294-3598-11e8-88c9-bb44530bde37.png)

But in any case, you can do this with other themes too, just use the "Inspect TM Scopes" command to see which theme rules are being activated.
