### ISSUE TITLE
Closing VS Code dev tools often crashes the app

### ISSUE THREAD

**Issue by MarkKahn** [Microsoft/vscode#47050]
Issue Type: <b>Bug</b>

Open VS Code's dev tools, type something in the console, close dev tools.  I've had it crash twice on me today doing this.  I'm using the console to just have a JS scratchpad.  I'm not sure if this is better off being reported to Electron, please advise.

<details>
<summary>Recent crash log from console: </summary>

```
Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
    __TEXT                 000000010ac5b000-000000010ac5c000 [    4K] r-x/rwx SM=COW  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
       0x10ac5b000 -        0x10ac5bff7 +com.microsoft.VSCode (1.21.1 - 1.21.1) <1A780387-B9CC-365B-9D6C-C38A9E714A15> /Applications/Visual Studio Code.app/Contents/MacOS/Electron
       0x10ac6d000 -        0x10ebd2f53 +com.github.electron.framework (0) <17080568-3795-340B-847D-40DA0A9EADD1> /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x10f213000 -        0x10f22dfff +com.github.Squirrel (1.0 - 1) <0A9F60FF-F2D2-364A-962A-65137E68760E> /Applications/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x10f25e000 -        0x10f2c1ff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Applications/Visual Studio Code.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x10f33f000 -        0x10f353fff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Applications/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x10f373000 -        0x110285fff +libnode.dylib (0) <36766918-904C-37B0-A301-190BEEE62DEB> /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
       0x11055f000 -        0x110695fe7 +libffmpeg.dylib (0) <A0D48A33-D074-375A-BD69-2800DF97C14E> /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
       0x115c32000 -        0x115c34fff +keymapping.node (???) <B9B741A2-1286-34E2-83A8-CD04640EFDCD> /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/native-keymap/build/Release/keymapping.node
       0x116fa0000 -        0x116fbafff +spdlog.node (???) <695F171A-CB02-3F27-80B7-1C8DC496E430> /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node
```
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 1400)|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (2.09GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
quokka-vscode|Wal|1.0.116
wallaby-vscode|Wal|1.0.79
vscode-custom-css|be5|2.7.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
prettier-vscode|esb|1.2.2
flow-for-vscode|flo|0.8.0
theme-monokai-pro-vscode|mon|1.1.5
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.3.0
language-stylus|sys|1.9.1
markdown-all-in-one|yzh|1.1.1
vscode-proto3|zxh|0.1.3

(2 theme extensions excluded)

</details>
Reproduces only with extensions

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.2.0

**Comment by roblourens** [comment]
I've seen the same thing, and it looks like an issue with electron or the chrome devtools themselves. Not sure there's anything we can do to improve it.
