### ISSUE TITLE
vim mode not work

### ISSUE THREAD

**Issue by willtuna** [Microsoft/vscode#47057]
Issue Type: <b>Bug</b>

After reinstall vim extension,
it still doesn't work

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1400 Quad-Core Processor            (8 x 3194)|
|Memory (System)|15.93GB (9.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\embarc_osp12\README.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
cpptools|ms-|0.16.1
veriloghdl|msh|0.2.0
makefiles-support-for-vscode|nae|0.0.3
python|tht|0.2.3
spice|xua|0.0.4
markdown-all-in-one|yzh|1.1.1

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Please open an issue on the Vim extension repo with more details.
