### ISSUE TITLE
markdown.styles can't open CSS file

### ISSUE THREAD

**Issue by mvolkmann** [Microsoft/vscode#47055]
Why is #8287 closed? It seems many people, including me, still can't get "markdown.styles" to work.
I've tried absolute paths and file: URLs, but neither works.
I can copy the URL I'm attempting, paste in a web browser, and it opens fine.

**Comment by mjbvz** [comment]
Please share the paths you are trying to use. Absolute paths are not supported (see #45260)

**Comment by mvolkmann** [comment]
Ah, I thought I could use an absolute path. I'll follow the advice in #45260. Thanks!
