### ISSUE TITLE
python format error

### ISSUE THREAD

**Issue by xieguangtai** [Microsoft/vscode#47054]
Issue Type: <b>Bug</b>

```
 def __str__(self):
        return '{{0}({1})}'.format(self.node, self.ip)
```
There is some highlighten error.
When I wrote '{{0}({1})}', 
the '{{' is blue, the '0}(' is orange,
the '{1}' is blue, and the ')}' is orange.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|Load (avg)|2, 2, 2|
|Memory (System)|15.55GB (0.40GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-docker|Pet|0.0.25
html-snippets|abu|0.2.1
Go|luk|0.6.77
python|ms-|2018.3.1
debugger-for-chrome|msj|4.3.0
vetur|oct|0.11.7
vim|vsc|0.11.3
jinja|who|0.0.8

</details>
Reproduces only with extensions

**Comment by jakeydoodle123** [comment]
I just tested it on my machine (I'm running mac os) and had the same bug. I disabled all the plugins, I was using and had the same result. So it's not anything to do with the any plugins.

**Comment by aeschli** [comment]
This issue was moved to MagicStack/MagicPython#130
