### ISSUE TITLE
Any shortcuts or keybindings to navigate multiple views in explorer

### ISSUE THREAD

**Issue by jkryanchou** [Microsoft/vscode#47051]
I have installed several extensions which could provide multiple views in explorer. While I was migrated from vim to vscode, used to operate the editor by keyboards through shortcuts. I found that it's hard to navigate the views in explorer by shortcuts, and have searched for a long while got nothing solutions on issues. Is there any keybindings could help me out with the issue? 

And try to navigate between the views like those red arrows in screenshot.

![image](https://user-images.githubusercontent.com/1206342/38170867-6101211e-35c1-11e8-8a4f-d7d2ee8c7617.png)

- VSCode Version: 1.21.1
- OS Version:MacOSX 10.12.4

Steps to Reproduce:

1. `cmd + shirt + e` to focus on explorer.
2. try to set shortcut to navigate multiple views in the explorer.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jkryanchou** [comment]
like this https://github.com/Microsoft/vscode/issues/1363#issuecomment-190330472. Just focus on the panel(view) header to cycle around the (panel)views.

**Comment by jkryanchou** [comment]
I used vim-keymap. I don't know whether it was affected by vscode-vim?

**Comment by isidorn** [comment]
Currently you can navigate between views using the tab key
There are also commands to focus into explorer, or to focus into open editors group
However there is no command to navigate between contributed views -> assigning this to @sandy081 to decide if he wants to add this

**Comment by jkryanchou** [comment]
@isidorn @sandy081 Thanks, Wish it could be added into new version of vscode-vim. It will accelerate our vim-workflow on vscode.

**Comment by sandy081** [comment]
@jkryanchou There exists two commands to navigate among views

![image](https://user-images.githubusercontent.com/10746682/38815694-d91edc48-4194-11e8-9341-25027284983c.png)

`Quick Open View` command allow you to navigate by typing `ctrl+q` and the other command will stay and you can select using mouse.

Please try out and let us know if they are good enough

**Comment by jkryanchou** [comment]
@sandy081 I know this functionality to quick open the view in explorer. While it is not directly. I wish i could use ctrl+w switch windows like vim. Is it hard to implement this functionality?

**Comment by sandy081** [comment]
@jkryanchou What do you mean by `I wish i could use ctrl+w switch windows like vim` ?

**Comment by jkryanchou** [comment]
@sandy081 Sorry, my reply was not clear. I mean the keymap `ctrl-jklm  changes to that split`.

**Comment by sandy081** [comment]
@jkryanchou Are you asking for an action to navigate views in the viewlet?

**Comment by jkryanchou** [comment]
@sandy081 Yeah. Navigate the views in explorer cannot work.

**Comment by sandy081** [comment]
@bpasero @octref I think this is related to navigating panels, viewlets.
