### ISSUE TITLE
Search Provider extension API

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#47058]
I looked into what it will take to run search in the extension host using extension APIs.

- Ripgrep search
    - Just need to port ripgrepTextSearch.ts and ripgrepFileSearch.ts
    - Currently it downloads the correct ripgrep binary at build time. A builtin extension in the core repo can still do that. A marketplace extension would have to ship all binaries and pick one at runtime.
    - Dependencies
        - Has lots of trivial dependencies from vs/base/common. It's ok to copy them, move to native node versions, or native ES versions
        - glob.ts, but we should get rid of that dependency. It's only used for sibling clauses and those should be handled on the frontend
    - API
        - Doesn't expose all features that builtin search needs
            - Whether to use gitignore file
            - Follow symlinks
            - Max filesize
            - Encoding (can be read from files.encoding, do we expect all 
extension authors to think of that?)
            - Result limit count (handled by frontend using CancellationToken?)
        	- Searching outside of the workspace
			- Smart case (front end)
			- wordSeparators (front end)
            - Cache search (for file search)
            - Sort by score (for file search)
			- Multiroot search (change it to search per single folder)
        - Need to read RelativePattern, instead of the current IFolderQuery
    - Logging
        - Use extensionhost logger and output pane
    - Frontend changes - SearchService just need to talk to search provider API
- Non-rg search is harder
    - Need glob.ts, and all of its dependencies
    - Mime
    - Iconv and the stuff we have built around it
    - IPC stuff from core for spawning worker processes
    - All of the dependencies would have to be moved to a separate node module so they can be shared with search. We probably don't want to do that.

**Comment by roblourens** [comment]
We also need an activation event for search

**Comment by jrieken** [comment]
In the `TextSearchOptions` how does `folder` and `includes` work together? Is the former an implicit prefix for all include-patterns?

**Comment by roblourens** [comment]
Yes that's what I'm imagining, and I think includes/excludes maybe should actually just be strings of globs relative to `folder`, rather than GlobPatterns, which can be relative to some other absolute path, since I'm not sure how to interpret that along with `folder`.

Was the original intention to have the extension read `workspaceFolders`, or to include the folder in `includes`? I think it's easier for implementors to separate "folder to search in" and "glob patterns to apply" and to have all the relevant info on the query object.

This also doesn't handle searching in extra open files. I'm not sure how to express that.

```
folder?: Uri;
files?: Uri[];
```

where just one of those is set.

Or maybe they don't need to be differentiated.

```
searchTargets?: Uri|Uri[];
```

**Comment by roblourens** [comment]
```ts
export interface SearchProvider {
	provideFileSearchResults?(query: string, progress: Progress<Uri>, token: CancellationToken): Thenable<void>;
	provideTextSearchResults?(query: TextSearchQuery, options: TextSearchOptions, progress: Progress<TextSearchResult>, token: CancellationToken): Thenable<void>;
}

export interface TextSearchQuery {
	pattern: string;
	isRegExp?: boolean;
	isCaseSensitive?: boolean;
	isWordMatch?: boolean;
}

export interface TextSearchOptions {
	folder: Uri;
	includes: string[]; // paths relative to folder
	excludes: string[];
	maxFileSize?: number;
	disregardIgnoreFiles?: boolean; // or useIgnoreFiles?
	ignoreSymlinks?: boolean; // or followSymlinks?
	encoding?: string;
}

export interface TextSearchResult {
	uri: Uri;
	range: Range;
	preview: { text: string, match: Range };
}
```

- How to express searching files vs folders?
- Multiple matches per line
	- New API lets us handle long lines better, but if there are many matches on a line, we will still send lots of duplicate line texts
	- Could allow multiple matches on a line in one TextSearchResult
- File search - extHost will handle fuzzy matching with the search string, sorting, etc. The extension just returns all files in the folder.
- Need extension activation event for search

**Comment by roblourens** [comment]
Need to decide whether the search provider API options include maxResults.

When maxResults is hit, the expensive search should terminate as quickly as possible, so it makes sense for the provider to know about it. Especially important in the workspaceContains case where maxResults = 1.

But the search service needs to know whether maxResults would have been exceeded, so it can show a warning in the text search viewlet. (What else do we use `limitHit` for?)

We could pass maxResult+1 to the provider so we know whether the provider has exactly 10,000 results, or would have produced more. Not good for the maxResults=1 case because some providers may have an optimization for just finding whether a pattern exists.

So, we could pass maxResults=1 in that case and maxResults+1 in all other cases. This is assuming `limitHit` doesn't really matter when maxResults=1.

**Comment by jrieken** [comment]
Meeting notes

```ts
interface FileIndexProvider {
  provideFileIndex(options, callback, token): Thenable<Uri[]>
}
interface FileSearchProvider {
  provideFileSearchResults(query, options, token): Thenable<Uri[]>
}
interface TextSearchProvider {
  provideTextSearchResults(query, options, callback: Progress<R>, token): Thenable<void>
}
```

**Comment by chrmarti** [comment]
My findings when optimizing for QuickOpen were that sending a lot of data between node processes doesn't perform well and that large repositories can cause the search process to stay busy just computing the ranking for a single search value for long enough to be noticed in the UI. The fixes were to do all filtering in the search process and to yield during ranking, such that, cancellation from new search values could occur.

If this still holds, `FileIndexProvider` might show performance issues because it assumes the full index can be hold and processed in the (shared) extension host process. Can we implement our own QuickPick using `FileSearchProvider` in a separate process given that it doesn't have the old cache support?

I'm not arguing that we need to use a separate process from the outset, but I wonder if the current proposal allows for it in the future without amending the proposal (or how to amend it).

**Comment by roblourens** [comment]
Without explicit cache support, we can get close by assuming the cache is stale after some timeout. Maybe it can use a FileSystemWatcher for hints too.

**Comment by chrmarti** [comment]
Using an unconditional timeout (assuming no explicit cache support) can have undesired side effects. E.g., when one part of the code creates a file and another part of the code then searches for it, such a cache introduces nondeterministic behaviour.

Watching an entire large repository might not perform well on all platforms and filesystems (if it does we should do it).

Let's throw the switch and run our own search in the extension host so we get a better understanding of the performance impact that has before we commit to the API.

**Comment by roblourens** [comment]
We could investigate using a node worker to not block the rest of the EH when filtering results: https://nodejs.org/api/worker_threads.html

**Comment by chrmarti** [comment]
The costs of sending the index between worker and EH might be too high. We'd have to try, but there is a chance this has similar performance as sending data between separate processes.

We've moved up a few Node versions since I did the performance measurements. The best approach might be to use search in the EH without committing to an API that limits us performance-wise and collect feedback.

**Comment by bolinfest** [comment]
As someone in the `FileSearchProvider` camp, I would also be concerned about performance for those who implement the `FileIndexProvider` API. Alternatively, if there were a good client library that made it possible to implement the `FileSearchProvider` API relatively easily (that handled the file watching, ranking, etc.), then perhaps everyone could use the `FileSearchProvider` API (avoiding the dual APIs).

**Comment by bolinfest** [comment]
From e69e4d3a477de5acd64802ac355ad6563a248ed6, it appears that it was a recent+deliberate change to no longer make `provideFileSearchResults()` a streaming API. The asymmetry with `provideTextSearchResults()` seems a little strange.

**Comment by roblourens** [comment]
That's correct, but this is because provideFileSearchResults is expected to return results in order sorted by relevance, and are only displayed when the full result set has loaded, but text results are always sorted by file path and displayed incrementally. I think that this makes the intent of how these are supposed to use more clear, even though the asymmetry bugs me too.

**Comment by roblourens** [comment]
re: FileIndexProvider - Did some basic perf testing and realized that URI-ifying every file in the workspace is... very expensive. I've always thought of this as a string-based API.

Can we change it to return strings of relative paths? I think it's justifiable even if we usually use URIs to refer to files. We are in a clear context of asking for files in a particular folder.

**Comment by jrieken** [comment]
> Can we change it to return strings of relative paths?

No - the API uses `Uri`

**Comment by sebastian-lenz** [comment]
Playing around with the insider build, I just noted that the results returned by a `FileSearchProvider` are filtered by VS Code against the include and exclude patterns. Also open text editors seem to emit search results on their own bypassing the implementation in a custom search provider. I think both behaviors are quite limiting when implementing a custom search.

In my current project the language internally organizes files into virtual folders, it does this as the language allows files to appear at multiple locations within a virtual tree. I was hoping to implement a custom search that allows filtering by include / exclude, but as VS Code always filters the results based on the uri which does not reflect this structure, I always end up with empty result sets.

**Comment by roblourens** [comment]
This issue is old and a bit stale, I am closing it and opening more specific issues.
