### ISSUE TITLE
Add functionality for bulk extension handling

### ISSUE THREAD

**Issue by crash5** [Microsoft/vscode#47053]
Please add and option to run actions on all selected extensions like uninstall, enable, disable.

For example: There is a lot of default installed extension that i don't need and it's very annoying to disable one by one by hand on every PC.

(Maybe add a config option to the user settings file to easily transfer disabled extension list to another PC?)

**Comment by krokofant** [comment]
There is a command line option to install or uninstall a single extension. Perhaps this could be extended to install multiple extensions.
> code --install-extension

There are some workarounds for this https://stackoverflow.com/questions/35773299/how-can-you-export-vs-code-extension-list

**Comment by ramya-rao-a** [comment]
/duplicate of #27147

Please add your upvotes to #27147
