### ISSUE TITLE
Html intellicense

### ISSUE THREAD

**Issue by markzolotoy** [Microsoft/vscode#47059]
Issue Type: <b>Feature Request</b>

I type <html in, no intellicense. Is that how it works? I have downloaded all kind of extenssions.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.17133

**Comment by xAegir** [comment]
• Try configuring the extensions you have downloaded
• Try restarting your vs code

**Comment by aeschli** [comment]
The built-in html support has code completion for tags, e.g. on `<ht`
See https://code.visualstudio.com/docs/languages/html#_intellisense

If you are in a PHP file and looking for code completion on html tags, please install the 'Intelephense' extension (issue #670)

**Comment by aeschli** [comment]
Closing, missing additional information
