### ISSUE TITLE
print is not working with errno 9.

### ISSUE THREAD

**Issue by gkyh0805** [Microsoft/vscode#47067]
I have running the python code for deep learning.

However, after several reboot due to the gpu problem, the print function is not working.

When I run the code, the vscode calls the command through the terminal.

(I cannot remember perfectly, however, before the problem, the vscode directly use the debug console, only, not terminal.)

and my code is immediately closed without the error code.

I found that print causes the close and call print function in the debug console.

the debug console saids 
[
print
IOError: [Errno 9] Bad file descriptor
]

when i use the sys.stdout.write or sys.stderr.write, both are not working with error.

I think this is a problem between the vscode and python in output redirection.

How can I solve this problem?

python code
![image](https://user-images.githubusercontent.com/34022221/38181224-95e96aa6-35e6-11e8-9783-d9d3eb4fc520.png)

python error
![image](https://user-images.githubusercontent.com/34022221/38181239-a6191f5c-35e6-11e8-9214-7e4de229bd3a.png)

python teminal
![image](https://user-images.githubusercontent.com/34022221/38181254-b303cf1e-35e6-11e8-961c-ba77fceb265f.png)

python launch.json setting
![image](https://user-images.githubusercontent.com/34022221/38181264-c2df5570-35e6-11e8-819f-a9a52ddddbd0.png)

**Comment by chienjchienj** [comment]
I got same error when i print something....

**Comment by weinand** [comment]
Please file this issue against the Python extension your are using.
