### ISSUE TITLE
API for retrieving the current position of the panel

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#47062]
Since a few releases it has been possible to move the bottom panel (the one containing `problems`, `terminal` etc.) to the side.

I want to add [support for split terminals](https://github.com/fabiospampinato/vscode-terminals/issues/9) to an extension of mine, and once 2d splits are implemented I would need to know the position of the panel in order to implementing this properly, because one would probably want to split a terminal in different directions depending on the position of the panel.

**Comment by Tyriar** [comment]
I'd say we can tackle this problem when we get there.
