### ISSUE TITLE
复制黏贴问题

### ISSUE THREAD

**Issue by percy622** [Microsoft/vscode#47065]
Issue Type: <b>Feature Request</b>

复制有的时候没法成功，光标变粗，需要通过insert 键还原

VS Code version: Code - Insiders 1.21.0-insider (b76a4a71434d6cdee69fa1d8bdc7533d09598d53, 2018-03-02T13:48:32.486Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
Can you give detailed steps of what you tried, and what happened?

Also, it looks like you are using an old version of insiders. Please update to the latest version and try again.
