### ISSUE TITLE
[html] provide (auto) rename of tags

### ISSUE THREAD

**Issue by Ahmed-Hussein-Karam** [microsoft/vscode#47069]
- VSCode Version: 1.21.1

## Description:
In order to rename an HTML/XHTML/XML tag we have to modify tag start, then modify tag end.

## Steps to Reproduce:
1. Disable all visual studio code extensions
1. Create element: &lt;div&gt;Hello&lt;/div&gt;
2. Modify tag start: &lt;label&gt;Hello&lt;/div&gt;
2. Modify tag end &lt;label&gt;Hello&lt;/label&gt;

## Suggestion:
I suggest that when tag start is modified, the corresponding tag end should be automatically modified **and vice versa**.

## Benefits:
1. **Make it easier to avoid typos,** especially in XHTML/XML when we modify a _custom tag_ where auto-complete is not available
2. **Avoid scrolling to tag end** when element content is very large

**Comment by roblourens** [comment]
You could probably write an extension to do this

**Comment by Ahmed-Hussein-Karam** [comment]
It will be better to add it as a feature rather than an extension, especially for new users because when they notice the problem, they will usually think that this is a limitation. Besides, they may not even know that there are extensions available

**Comment by aeschli** [comment]
The extension for this is:
https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag

**Comment by michaeljota** [comment]
I have used several extension that does this, but I have to say that, neither works as you would expect. Sometimes they work well, sometimes they don't. I think that if VSCode have this integrated, it would deliver a better experience in a more consistent way.

**Comment by otijhuis** [comment]
I'd love to see this feature in vscode as well. While there are a few extensions, they are very unreliable. Auto Rename Tag does not work with multi-line tags and tags with dashes (like you'd use for components). So for angular development you might as well not use it at all. It's one of those webstorm features that I really miss in vscode.

**Comment by grantnorwood** [comment]
Adding an extension for every basic piece of functionality an IDE should already do _(e.g., updating start/end HTML tags, or dragging/dropping text, and such)_ is why I don't use Atom.  I'm surprised I don't have to install an Atom extension to use capital letters!

All kidding aside, this is both an obstacle for new users, and an unnecessary hurdle for developers who already use VS Code.

**Comment by SCPCOEXR** [comment]
I agree with @shankarsridhar  
Also tag wrapping should be apart of the core of VS Code.

**Comment by digeomel** [comment]
Agree with everyone else, this is so basic and annoying, it shouldn't be left to extensions.

**Comment by zzdumeng** [comment]
If you use the `vim` extension, you can enable surrounding and use trigger stroke sequences `cstt` -> enter tag you want to change -> press `<enter>`. It will rename the tag while reserve attributes.

**Comment by leye0** [comment]
@zzdumeng 😨
It's almost faster to rename tags manually 😆

**Comment by JonathanTR** [comment]
Speaking as a `vim` user, this is actually incredibly quick and just what I needed. Thanks for saving me the extra package, @zzdumeng!

**Comment by gezquinndesign** [comment]
Just adding my support for this feature....

**Comment by michael-letcher** [comment]
Please add this! The extension mentioned in this ticket doesn't work properly if at all.

**Comment by El4a** [comment]
Can't believe its a YEAR and this superduper basic thing is still left wanting... The plugin mentioned indeed does not seem to work properly anymore. Can say about brackets what you will, but at least it had that.

**Comment by OogieBoogieInJSON** [comment]
Emmet has edit functions for tags. Click on your tag and using the command panel type _update tag_. An input box will appear and type your new tag. You can bind this to a shortcut as well. Stop being lazy 🐻

**Comment by MrCroft** [comment]
😆 @OogieBoogieInJSON this was never about being lazy, it's about being productive
Simply typing while the closing tag changes automatically to match, is faster than having to press a key combination first, and then type. And this is an action you need to do very often if you work with html :), not just a few times a day.
I think this request is more than fair, especially in lack of a good extension (existing extensions fail me when I have more than a few layers of nested tags, ending up not auto renaming the end tag or renaming the wrong end tag)

**Comment by OogieBoogieInJSON** [comment]
@MrCroft I was suggesting an alternative that already comes built in with the editor.

**Comment by kyro38** [comment]
Man, the absence of this feature is frustrating. Should be built-in !

**Comment by bmewburn** [comment]
Would it be appropriate to implement this as a rename provider (ie `F2` then rename)? Or as an additional text edit when selecting a completion suggestion?

**Comment by nazarkryp** [comment]
I support this as well. Implement this auto rename tag in vscode. You guys provide so many useless features to vscode in each release. implement something more useful that colors in terminal
Please do not adwise extension "auto rename tag" as it sucks and makes intellisense crush.

**Comment by OogieBoogieInJSON** [comment]
@nazarkryp it already exist, look for my previous comment. Anyways, it's very rude saying "so many useless features". If you are not using them it doesn't mean they are useless. You should be more grateful, vscode is not something you are paying for. We are using this piece of software for free while it's being built with the free time and money of others.

**Comment by MrCroft** [comment]
@OogieBoogieInJSON My heart stated racing for a bit, when I read "it already exists" :smile:
Unfortunately, it's not what we need: while typing/editing the open tag, the close tag should change accordingly (and vice versa).
I've just realized recently that intelisense doesn't work because of the auto rename tag extension, or if it works it's extremely slow. Simply by guessing, deactivating autorename tag extension 🤦🏻‍♂️
Really hope this will be built in soon, really seems like the type of behavior that should be built in, not through an extension

**Comment by nazarkryp** [comment]
@OogieBoogieInJSON it doesn't have. Emmet is not what people want as it's not handy at all. I recall similar tickets have been already created. 
p.s: do not use my words against me. I'm also part of development community and i appreciate this product. I care about making it better and encourage people to focus on things matter. (in this case each vscode alternative has it. so why we can't have simple auto rename tag in runtime)

**Comment by octref** [comment]
I added F2 to rename tag. It's not as good as auto-rename, but it should help a bit.

![kap](https://user-images.githubusercontent.com/4033249/69178220-07413780-0abe-11ea-8236-161728f26f9b.gif)

I'll look into auto-rename.

**Comment by michaeljota** [comment]
@octref Thanks! I think this is way better than auto-rename!

**Comment by wizcas** [comment]
@octref Thank you! I love the rename feature so much! In which version will it be released?

**Comment by octref** [comment]
@wizcas You should already be able to use it in latest https://code.visualstudio.com/insiders/

**Comment by octref** [comment]
Out of consideration for performance, extension compatibility (esp Vim extension and language extensions that would use HTML document), discoverability, usability, here is what I have come down to: auto selecting the matching tag's position. You can opt-out by turning off `html.autoSelectingMatchingTags`.

Benefits are:
- This is just normal multi-cursor mode, so:
    - Shift + alt + left/right to do multiple selection works
    - Alt + delete to delete word, or Cmd + delete to delete line works
    - Cmd + left/right can get you to beginning/end of the line, so you can easily do line selection as well.
- Changes are emitted in one edit. That means undo/redo can remove both changes at opening/closing tags together. Currently, auto-rename-tag extension's approach wouldn't enable this.
- Auto completion of tag name works.
- Instead of letting an extension modify the file without you being aware, this offers a more easily understandable behavior, as user already understands multi-cursor.

![auto-selection](https://user-images.githubusercontent.com/4033249/69450026-0e13b880-0d11-11ea-8505-9fbc2a8fc6ba.gif)

The only two special cases, where I'm making edit to the document are:

- When you type space in `<div|></div|>`, the second cursor's space is removed
- When you position cursor to `</div>` and type a space, the space is added to the opening tag, and leave you at the opening tag position

This is to let you change attributes easily:

![image](https://user-images.githubusercontent.com/4033249/69450998-3ef4ed00-0d13-11ea-9361-f5ae63b512a4.png)

And finally, this should not interfere with Vim much. Enjoy that `cw` to change both opening and closing tag.

Multi-cursor with Cmd + Option + down should also work if you have your tags well aligned.

![image](https://user-images.githubusercontent.com/4033249/69451295-e2de9880-0d13-11ea-95f4-aaf0c8181992.png)

**Comment by octref** [comment]
Updates:

> When you position cursor to </div> and type a space, the space is added to the opening tag, and leave you at the opening tag position

This behavior was removed.

And now, ESC would temporarily remove the mirroring cursor until you move cursor again.

**Comment by ultraGentle** [comment]
Hello, excited about this feature -- however, it does not seem to exist for me, using latest insiders.  

Positioning cursor within a tag (either via click or keyboard navigation), does not select matching tag, nor is typing mirrored in the matching tag.  

Retried with all extensions disabled; still nothing.  

There was also not `html.autoSelectingMatchingTags` setting shown in the settings UI.  

If I'm doing something wrong, please let me know -- eager to have access to this feature and ditch the buggy rename- and highlight-matching-tag extensions!

Mac OS X 10.13.6
Version: 1.41.0-insider
Commit: a747d264d668a947eeacd3492b60df6ce8dee6b4
Date: 2019-11-23T11:08:24.747Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

**Comment by octref** [comment]
@ultraGentle Try today's insiders should have it. Give it a try.

**Comment by ultraGentle** [comment]
Yes!  Works like a charm.  Much obliged.

**Comment by fbricon** [comment]
@octref any way to expand the scope of that feature to XML tags? Or at least give some pointers on how to achieve a similar behavior for XML (See https://github.com/redhat-developer/vscode-xml/issues/130)

**Comment by AndrePu** [comment]
It doesn't look good for xaml code. How can I disable it?

![image](https://user-images.githubusercontent.com/30782193/71175483-5a024080-2270-11ea-8577-b31153ff7eb1.png)

**Comment by octref** [comment]
@AndrePu xaml support is implemented by vscode-xml extension, so open an issue there.

**Comment by xorye** [comment]
Hi. Heavily inspired by the code in: https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/client/src/mirrorCursor.ts, I made a different implementation of mirrorCursors [here](https://github.com/xorye/vscode/blob/mirror/extensions/html-language-features/client/src/mirrorCursor.ts) for a PR to vscode-xml: https://github.com/redhat-developer/vscode-xml/pull/213.

Most (if not, all) of the logic was transferred over. (ie, the logic for [`onDidChangeTextEditorSelection()`](https://github.com/microsoft/vscode/blob/2bcb83de0f131b4d63a9db8d8793d164dee823ff/extensions/html-language-features/client/src/mirrorCursor.ts#L52) exists in [`updateCursors()`](https://github.com/xorye/vscode/blob/5e6fae04de1a81a06293baca238a99382fc648cf/extensions/html-language-features/client/src/mirrorCursor.ts#L230))

The main reason for this implementation was to immediately dispose the `vscode.window.onDidChangeActiveTextEditor`  and `vscode.window.onDidChangeTextEditorSelection` listeners when the html.mirrorCursorOnMatchingTag is turned off.

The structure of the code is a bit different:
When `html.mirrorCursorOnMatchingTag` is turned on, an instance of `MirrorCursors` is responsible for managing an instance of `CursorUpdater` and `CursorUpdater` is responsible for updating the cursor(s) in an html/handlebars file.
When `html.mirrorCursorOnMatchingTag` is turned off, the `MirrorCursor` and `CursorUpdater` instances are "thrown away" and its listeners are disposed of.

@octref What do you think about this implementation?

**Comment by octref** [comment]
I think that's ok. Most of the corner-case handling is in `mirrorCursor.ts` so you want to update it from time to time.
