### ISSUE TITLE
Text rendering (code+chrome) is glitchy under Ubuntu 18.04 beta

### ISSUE THREAD

**Issue by ronjouch** [Microsoft/vscode#47060]
Issue Type: <b>Bug</b>

See screenshot below; all across Code (menus, help text, code), text rendering is strangely glitchy (little extraneous pixels near characters). Here's a screenshot with a fresh new profile and no extensions:

![vscode-1 21 1_text-rendering-glitchy](https://user-images.githubusercontent.com/522085/38176964-a1d44d38-35c6-11e8-96a6-bc0f9d0e8b29.png)

Maybe some component in Ubuntu 18.04 (currently in beta) causes this? I'm running the default Ubuntu font, default antialiasing, default fontconfig.

- On the same 18.04 machine, no such problem in Chrome.
- And on another Arch machine, no such problem in Code.

Feel free to ask for more information and sorry if the issue is already known, I couldn't find an existing report.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.15.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3140)|
|Load (avg)|1, 0, 0|
|Memory (System)|15.25GB (8.24GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by migueldemoura** [comment]
Duplicate #35675. Workarounds are there, and a fix is will be on the next version afaik.

**Comment by roblourens** [comment]
Thanks @migueldemoura
