### ISSUE TITLE
Php file does NOT recognize php code

### ISSUE THREAD

**Issue by DeveloperJF** [Microsoft/vscode#47061]
![falla_codigo](https://user-images.githubusercontent.com/37987294/38178075-75b8010e-35d0-11e8-869a-ef8e2e30a356.jpg)
![falla_codigo2](https://user-images.githubusercontent.com/37987294/38178076-75f4ff96-35d0-11e8-8592-84c6c2b8c0f5.jpg)

Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.

**Comment by xAegir** [comment]
Download PHP Extensions from the Extensions/Plugins Manager.

**Comment by roblourens** [comment]
If you click "HTML" in the lower right corner, can you change the language mode to PHP?

**Comment by DeveloperJF** [comment]
Thanks for your help. But it is not that; because I've already tried placing it by investing in the lower part of the language and I also have the extensions and it's not working for me. I appreciate if you can give me other options.
![falla_codigo3](https://user-images.githubusercontent.com/37987294/38182052-4b3500f4-35fc-11e8-94ac-8f7b1a584658.jpg)

**Comment by roblourens** [comment]
That should be uppercase PHP, not lowercase. 
![image](https://user-images.githubusercontent.com/323878/38182145-53ce462c-35ec-11e8-8f0f-77cd7fa8e572.png)

Is there an option that says PHP? Can you try starting with --disable-extensions to see if one of the extensions is interfering?

**Comment by DeveloperJF** [comment]
Thanks for helping me. I tell you, 4 days ago I had looked at that possibility; but I did not see change. Anyway, I'll do it again, and i send you a screenshot where I disable the all extensions.
![falla_codigo4](https://user-images.githubusercontent.com/37987294/38182465-3ec38a9a-35ff-11e8-9909-a4acdd95bb1e.jpg)

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by DeveloperJF** [comment]
Good morning, Excuse me was in other personal things and that's why I had not answered. I told them that I uninstalled the program again and it remains the same; but I downloaded the VS Code insider and that did work for me.
Why does that happen? Can you comment?
What's different about VS Code Insiders / VS Code ??
![falla_codigo5](https://user-images.githubusercontent.com/37987294/38560946-6cbedafa-3c9c-11e8-9177-0f4a3e38b88a.jpg)
![vscodeinsiders](https://user-images.githubusercontent.com/37987294/38560947-6ce11f70-3c9c-11e8-930b-99f0cc308ebe.jpg)
![vscodeinsiders1](https://user-images.githubusercontent.com/37987294/38560948-6d03eb2c-3c9c-11e8-9141-4f4d1712189d.jpg)

**Comment by roblourens** [comment]
Is stable updated to the latest version (1.22.1)? If not then Insiders is just the latest code.
