### ISSUE TITLE
Pressing esc key doesnt clear signature help widget

### ISSUE THREAD

**Issue by AlexWang-16** [Microsoft/vscode#47064]
- VSCode Version: 1.21.1 
- OS Version: MacOS 10.13.4

Not sure if I'm naming these terms correctly, so please correct me if I've misused the terms.

Sometimes intellisense suggestions box obstructs the view of code I want to look at. It would be nice if it is possible to press **esc** to hide the suggestion box such that I can invoke it at a later time using ctrl + space.

Example:

![screen shot 2018-04-01 at 8 47 36 pm](https://user-images.githubusercontent.com/13398997/38179219-93b021e6-35ee-11e8-8a2a-715d9e6cbbca.png)

There's currently no way to clear that box on the screen when it pops up other than moving the keyboard cursor to another spot.

**Comment by roblourens** [comment]
esc will hide it if focus is in the editor

**Comment by ramya-rao-a** [comment]
@AlexWang-16 What you have shared is called the signature help or parameter hints widget which shows up when typing parameters in a function call. It does get hidden when esc key is pressed, unless you have removed the keybinding that binds the esc key to the `closeParameterHints` command.

Can you check your keybindings file? Run the command `Preferences: Open Keyboard Shortcuts File`

**Comment by AlexWang-16** [comment]
Thanks for your response. I do see the key map for CloseParameterHints  using the escape key. It works most of the time but sometimes it fails to work. I guess it could be my editor window being unfocused.

**Comment by ramya-rao-a** [comment]
In that case I'll close this issue.
If you see this happening when the editor has focus, feel free to log another issue.

Happy Coding!

**Comment by AlexWang-16** [comment]
Hey @ramya-rao-a, it looks like the issue has returned.

![issue](https://user-images.githubusercontent.com/13398997/38984778-9eb764b4-4395-11e8-9c19-c8daa3842a4a.gif)

The clock looking symbol are my attempts of pressing the escape key.

**Comment by ramya-rao-a** [comment]
@AlexWang-16 Can you share any changes you'e made to keybindings? You can get this from running the command `Preferences: Open Keyboard Shortcuts File` and sharing the contents of the right side of the editor.

Do you see this consistently? Do you see this with extensions disabled? Run `code --disable-extensions`.

**Comment by AlexWang-16** [comment]
To my knowledge, I haven't changed any of my key bindings. [My keybindings](https://git.io/vpqU2).

It happens every time the signature help appears. I noticed that I can press "esc" to make intellisense suggestions disappear, but not the signature help.

After disabling all extensions, I was able to cancel signature help using escape.

**Comment by ramya-rao-a** [comment]
> After disabling all extensions, I was able to cancel signature help using escape.

The chances are that one of the extensions you have is interfering with the esc key.
You will have to enable the extensions one by one to figure out which one is causing this issue and then log the issue in the repository corresponding to that extension
