### ISSUE TITLE
Extension view in browser failed

### ISSUE THREAD

**Issue by Devdatta03** [Microsoft/vscode#4706]
- VSCode Version:0.10.11
- OS Version:Windows 7

Steps to Reproduce:

1. Running the contributed command:'extension.viewInBrowser' failed
2.

**Comment by Tyriar** [comment]
This issue was moved to hellopao/view-in-browser#1

**Comment by hellopao** [comment]
@Devdatta03  i can't reproduce this , did you set  focus on the editor?
