### ISSUE TITLE
The "Courier New" font (with normal font weight) looks thinner than in other IDEs on Windows

### ISSUE THREAD

**Issue by pdliu** [Microsoft/vscode#47079]
The "Courier New" font (with normal font weight) looks thinner than in other IDEs on Windows. 
I want "Courier New" font to appear normal, not that slim.

**Comment by alexandrudima** [comment]
This is caused by the font rendering library used by Chromium. Unfortunately, there is no way to customize this and Chromium will not go back to GDI fonts instead of DirectWrite. (https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/WzivQg8_drw)

**Comment by pdliu** [comment]
Thanks for your time and effort.
