### ISSUE TITLE
Add fossa.io to badge providers

### ISSUE THREAD

**Issue by dantman** [Microsoft/vscode#47072]
Example badge:
```md
[![FOSSA Status](https://app.fossa.io/api/projects/git%2Bgithub.com%2Fnode-facebook%2Ffacebook-node-sdk.svg?type=shield)](https://app.fossa.io/projects/git%2Bgithub.com%2Fnode-facebook%2Ffacebook-node-sdk?ref=badge_shield)
```
[![FOSSA Status](https://app.fossa.io/api/projects/git%2Bgithub.com%2Fnode-facebook%2Ffacebook-node-sdk.svg?type=shield)](https://app.fossa.io/projects/git%2Bgithub.com%2Fnode-facebook%2Ffacebook-node-sdk?ref=badge_shield)

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode-vsce/commit/017d92a31bd24bc6b5de61ab053b08b0182acc17

cc @viradhamMS @pkuma-msft Could we enable this `fossa.io` domain on the server side too?

**Comment by pkuma-msft** [comment]
Sure, will take care of this

**Comment by pkuma-msft** [comment]
@joaomoreno On the marketplace side we need to whitelist the exact domain, so should I whitelist just app.fossa.io ?

**Comment by joaomoreno** [comment]
@pkuma-msft Yeah, maybe that's better. I'll change it as well for vsce.

**Comment by pkuma-msft** [comment]
This change is now applied on Marketplace.

**Comment by joaomoreno** [comment]
@pkuma-msft Thanks!
