### ISSUE TITLE
Auto Sync Visual Studio Code

### ISSUE THREAD

**Issue by Vaibhav2103** [Microsoft/vscode#47074]
Issue Type: <b>Feature Request</b>

Auto Sync Visual Studio Code With extension Like Chrome with its extension.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.10586

**Comment by svipben** [comment]
1. You can create your own private or public extension pack.
2. You can use this extension: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by Vaibhav2103** [comment]
@svipben I am not talking about Github sync. I want to sync my VSCode settings like all installed extensions, font size, theme, icons and etc.

**Comment by bsvipas** [comment]
@Vaibhav2103 try this extension: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync it does what you want it just stores your all settings/themes, etc in Gist.
