### ISSUE TITLE
When use chinese input method, the first key press will be missed.

### ISSUE THREAD

**Issue by yelantingfeng** [Microsoft/vscode#47070]
- VSCode Version: 1.21.1
- OS Version: Windows 10 Pro 1709 16299.334

Steps to Reproduce:

1. Open pdf viewer in vscode new tab. ( I am using extension latex-workshop)
2. Use Alt+Tab to switch to another app. (or other way to focus on somewhere outside the vscode)
3. Use Alt+Tab to switch back to vscode. (or other way to focus on vscode but not by clicking the editor in vscode)
4. Then I try to input some chinese characters ‘’你好” so that I pressed 'n','i','h','a','o'. However, the first key press is not catched by my input method, it is just regarded as a English letter 'n' and typed into the text, while the following 'ihao' are catched by the input method.

Does this issue occur when all extensions are disabled?: No
But that's because I cannot find a way to open pdf viewer in vscode when extensions are disabled.

**Comment by roblourens** [comment]
Which IME?

**Comment by Stone-Zeng** [comment]
Possible duplicate: #45641

**Comment by rebornix** [comment]
It's duplicate of #26527, let's track it there.
