### ISSUE TITLE
Feature-Request: Explorer navigation

### ISSUE THREAD

**Issue by Legends** [Microsoft/vscode#47082]
In VS I can focus an entry in the file explorer, press a/some character(s) on my keyboard and explorer will focus the first file whose filename starts with the characters pressed.

But this does not work in VsCode.

**Comment by Legends** [comment]
![image](https://user-images.githubusercontent.com/966368/38196955-099dcc36-3686-11e8-9f89-0129e6bdb646.png)

**Comment by Legends** [comment]
Which release will fix this?

**Comment by bpasero** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/10026
