### ISSUE TITLE
[package.json] `repository` field does not need to be an object

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#4708]
- VSCode Version: `0.10.11`
- OS Version: `OS X 10.11.3`

Steps to Reproduce:

1. Create a valid `package.json` file
2. Add a `repository` field with the values `Microsoft/vscode` (or whatever repository)

It looks like VS Code is complaining about the `repository` field not being an object. This is not entirely correct as per the [documentation](https://docs.npmjs.com/files/package.json#repository).

> For GitHub, GitHub gist, Bitbucket, or GitLab repositories you can use the same shortcut syntax you use for npm install:
> 
> ```
> "repository": "npm/npm"
> 
> "repository": "gist:11081aaa281"
> 
> "repository": "bitbucket:example/repo"
> 
> "repository": "gitlab:another/repo"
> ```

![screen shot 2016-03-28 at 13 06 44](https://cloud.githubusercontent.com/assets/1913805/14076895/2f0ef762-f4e6-11e5-9130-6b1bd9357e4b.png)

**Comment by egamma** [comment]
Code is using the schemas from scheamstore.org and http://json.schemastore.org/package defines repository to be an object.

**Comment by SamVerschueren** [comment]
@egamma added a PR to fix this https://github.com/SchemaStore/schemastore/pull/129

**Comment by egamma** [comment]
@aeschli until the PR is accepted, could we use your schema override mechanism to fix this?

**Comment by SamVerschueren** [comment]
@egamma @aeschli PR got accepted!

**Comment by egamma** [comment]
great thanks & closing.

**Comment by SamVerschueren** [comment]
Is this automatically being picked up by VS Code?

**Comment by egamma** [comment]
We fetch the schema dynamically whenever possible. I've just checked and this seems to be the case

![image](https://cloud.githubusercontent.com/assets/172399/14111788/61927c40-f5cc-11e5-9536-98ed48d66254.png)

**Comment by sindresorhus** [comment]
npm does a lot of normalizations of package.json, meaning it supports a lot of shortcuts. Someone should probably go through this list https://github.com/npm/normalize-package-data#what-normalization-currently-entails and ensure it's all supported.

**Comment by SamVerschueren** [comment]
@sindresorhus Thanks for pointing to the docs. Will add it to my todo.
