### ISSUE TITLE
Integrated Terminal glitched output with docker push

### ISSUE THREAD

**Issue by hassanselim0** [Microsoft/vscode#47088]
- VSCode Version: 1.21.1
- OS Version: Windows 10 Pro Version 1709

Steps to Reproduce:

1. Run `docker push` on the integrated terminal while it's small (enough to not show all the layers)
2. Attempt to scroll while the layers are being uploaded
3. Notice that lines (with layer progress change) get duplicated

Screenshot: (notice how the `c041efd84434` line is duplicated)
![image](https://user-images.githubusercontent.com/1431770/38200503-f09592fa-3694-11e8-8901-d8b047841b4e.png)

I don't believe that this is related to #36630 because I don't get that io error and the push completes successfully, but the progress bars glitch in this way.
This issue might apply to other CLI tools that modify previous lines in the console, not just `docker push`, but I haven't encountered any of these myself so I can't confirm.

Note: I'm using cmd in the integrated terminal, I haven't tested with Powershell.

Does this issue occur when all extensions are disabled?: Probably

**Comment by Tyriar** [comment]
This is one of the issues caused by winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

**Comment by hassanselim0** [comment]
@Tyriar I'm not sure which of the linked issues in that meta-issue is the duplicate.
My line duplication issue doesn't happen when resizing, it happens when scrolling then a line gets updated (like the progress bar).

**Comment by Tyriar** [comment]
@hassanselim0 I edited the issue to call this one out explicitly.
