### ISSUE TITLE
Slow sluggish editor after sometime

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#47085]
Version 1.22.0-insider
Commit 6c22e21cdcd6811770ddcc0d8ac3174aaad03678
Date 2018-03-30T05:16:39.261Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Use the editor for a while, having two separate windows opened
2. Toggle Developer Tools

Right now the editor is using 3 cores of my 4 cores, almost maxing them out (75%). Using a lot of memory as well (1.5GB)

![image](https://user-images.githubusercontent.com/461084/38199197-3fbd509a-3666-11e8-9847-16db73595c3c.png)

the log has the repeating errors:

![image](https://user-images.githubusercontent.com/461084/38199205-4da5f4f0-3666-11e8-971a-68ee8af6c88f.png)

Other than that, it's just sluggish to type, having to close and open it again to make it more responsive again

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you use `code-insiders --status` to see which processes are using CPU?
