### ISSUE TITLE
TextDecoration width/height does not apply to contentIconPath

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#47086]
Based on the code in #11055 I would've expected this to work:

<img width="641" alt="screen shot 2018-04-02 at 15 12 32" src="https://user-images.githubusercontent.com/1078012/38199353-6e8d6866-3688-11e8-8cd6-fd78256c917c.png">

However the image is much better than 10px:

![screen shot 2018-04-02 at 15 12 44](https://user-images.githubusercontent.com/1078012/38199367-77f8e5ec-3688-11e8-8e25-44b530a2e1e8.png)

**Comment by aeschli** [comment]
I quickly tried and the size seems to be correctly applied.
Did you use the dev tools to see what's happening? Maybe something special with the SVG? I tried with http://image.flaticon.com/icons/svg/188/188918.svg (downloaded and referenced like in your example).

Maybe you can create a github repository with the sample code.

**Comment by DanTup** [comment]
![screen shot 2018-04-04 at 09 23 44](https://user-images.githubusercontent.com/1078012/38296654-e2f29250-37e9-11e8-986b-2e41b6e6f1b4.png)

Apparently, the width/height don't work for images set in content like this:

> https://css-tricks.com/almanac/properties/c/content/#article-header-id-2
> Note that you cannot change the dimensions of the image when inserted this way. You could also insert an image by using an empty string for the content, making it display: block in some way, sizing it, and using background-image. That way you could re-size it with background-size.

So if the width/height are expected to apply to images, it might need tweaking how the image is applied? (changing the image dimensions isn't a great solution - one of the advantages of using vector graphics is to have a single image that works at any size).

**Comment by aeschli** [comment]
That's not what I see:
![image](https://user-images.githubusercontent.com/6461412/38299110-71f24d42-37f9-11e8-91a6-aa304940909a.png)

Also try this in Chrome: See http://jsfiddle.net/Ld5th53c/3/

**Comment by aeschli** [comment]
On the sizes: Using `em` is the right thing to do (not `px`)

**Comment by aeschli** [comment]
Closing, it seems to me not an issue in our code but svg related.
