### ISSUE TITLE
Bug using references

### ISSUE THREAD

**Issue by danilocecilia** [Microsoft/vscode#47083]
Issue Type: <b>Bug</b>

There is this bug when using references, not able to close it. Need to restart VS Code.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|Memory (System)|15.92GB (6.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
vscode-map-preview|jum|0.4.2
debugger-for-chrome|msj|4.3.0
java|red|0.21.0
ionic2|Tha|3.0.2
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
html-css-class-completion|Zig|1.17.1

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by jrieken** [comment]
Please provide reproducible steps and the readings from the console

**Comment by ryanoshea** [comment]
I can reproduce this. I'm not sure what the bare minimum of steps needed is, so I can just list my situation:

1. Open a folder with a .tsconfig project
2. Find all references for a TypeScript class name
3. From inside the peek references panel, edit the contents of one of the referenced files.
4. While editing the file inside the references panel, use the auto-import feature.
5. Attempt to close the references panel via the X button.
6. Panel will not close, and occasionally a notification will appear reporting a null reference error, something like "cannot find destroy on null".

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2294)|
|Memory (System)|7.89GB (0.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
cobol|bit|1.7.8
jshint|dba|0.10.17
tslint|eg2|1.0.28
mssql|ms-|1.3.0
csharp|ms-|1.14.0
debugger-for-ios-web|msj|0.1.2


</details>
Have not tested with extensions disabled.

**Comment by jrieken** [comment]
Can you try this with insiders: https://code.visualstudio.com/insiders? Thanks

**Comment by ryanoshea** [comment]
Tested with insiders, can't reproduce the issue. Tried with no extensions and with all of my original extensions installed (except `debugger-for-ios-web`, which I couldn't find on the marketplace).

**Comment by ryanoshea** [comment]
However, I don't seem to be able to reproduce it on the stable build anymore, so my inability to repro on insiders might not mean much. Hopefully the stack trace is helpful.

**Comment by ryanoshea** [comment]
Haven't encountered this issue yet in 1.22. Thanks for following up!
