### ISSUE TITLE
Distinguish multi root folders better in quick pick result list

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#47080]
As you can see, it's quite difficult to easily determine which files are from the client folder and which are from the server folder. We need a clearer way to distinguish the results.

![screen shot 2018-04-02 at 6 55 01 pm](https://user-images.githubusercontent.com/9585787/38195370-61c2cbde-36a7-11e8-8e44-9540f856c3b7.png)

**Comment by bpasero** [comment]
This happened:

![image](https://user-images.githubusercontent.com/900690/45428479-99bb9f00-b6a1-11e8-836a-c06a8e391b12.png)
