### ISSUE TITLE
io.read() (Lua)

### ISSUE THREAD

**Issue by Pablobun** [Microsoft/vscode#47084]
I am using lua but it does not recognize the data input per user. that is, io.read (). Could you tell me what extension to install to solve this problem? thanks

**Comment by roblourens** [comment]
I don't understand the problem, can you explain some more?

**Comment by Pablobun** [comment]
I am testing the Lua language in visual code and I do not recognize the io.read () sentence, which is the one used to receive data from user. 
example:
---------------------------------
io.write ("Name?")
a = io.read ()
io.write ("Hi" ..a)
----------------------------------------------------
in this case the code is not executed because when the code arrives where the user should enter the name does not recognize the sentence. Thank you

**Comment by Pablobun** [comment]
![image](https://user-images.githubusercontent.com/38007140/38205619-945b97f8-367d-11e8-8d7b-e0d3b8a2ef2b.png)

**Comment by roblourens** [comment]
I don't know Lua but this sounds like it might be a problem with your program?

**Comment by Pablobun** [comment]
NO, es un problema con la plataforma no reconoce la sentencia, en cualquier tutorial para principiantes de lua se puede ver estas mismas lineas de codigo, pero lo ejecutan con "scite"

**Comment by dbaeumer** [comment]
@Pablobun are you using an extension for the LUA support. If so, please report the issue to them. VS Code doesn't have any LUA support in the box.

**Comment by Pablobun** [comment]
I know. I have already tried extensions but none activate data entry. That is why I ask by this means if they know which is the correct one. Thank you

**Comment by DeNlck** [comment]
I also have this problem. Someone decided it?
