### ISSUE TITLE
디버그 어댑터 프로세스가 예기치 않게 종료되었습니다.

### ISSUE THREAD

**Issue by lmyounghun** [Microsoft/vscode#47087]
Issue Type: <b>Bug</b>

디버그 어댑터 프로세스가 예기치 않게 종료되었습니다.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1500X Quad-Core Processor           (8 x 3493)|
|Memory (System)|11.93GB (8.89GB free)|
|Process Argv|E:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
python|tht|0.2.3

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Can you post your launch config?
