### ISSUE TITLE
Strange text selection behavior on mouse-click

### ISSUE THREAD

**Issue by inarius** [Microsoft/vscode#47099]
Issue Type: <b>Bug</b>

When using Shift + mouse click while selecting text, the begin and end selection positions seem to change at unexpected times. I can't fully describe the circunstances that cause this, but it appears to happen most when clicking inside of a pre-existing selection. 

The selection end position sometimes swaps to the end, and the final selection is not what I expect. My steps to reproduce were:

1. Use Shift+left arrow to select text
2. Use Shift+mouse click within the selection to change it
3. Instead of the selection end position changing, the selection start changes, and the right-most text which was initially selected is no longer selected

Any selection with an end position that is further left than the end position seems to reproduce this behavior for me.

![vscode](https://user-images.githubusercontent.com/4432847/38212353-52f12f40-3672-11e8-8edd-eaea1340fdfe.gif)

VS Code version: Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T05:16:39.261Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7650K Radeon R7, 10 Compute Cores 4C+6G  (4 x 3292)|
|Memory (System)|14.94GB (4.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.0.20
rainbow-csv|mec|0.2.1
mssql|ms-|1.3.0

</details>

**Comment by inarius** [comment]
@vscodebot This was a similar issue, but the behavior is different, and this one is not fixed in the latest build.

**Comment by alexandrudima** [comment]
I can reproduce when `editor.dragAndDrop` is true.

![kapture 2018-04-05 at 9 39 10](https://user-images.githubusercontent.com/5047891/38352949-36b76b7e-38b5-11e8-8795-9235bd9403e9.gif)

**Comment by ADTC** [comment]
Confirming this bug. I expected the "end" to always be the last-clicked position, not the actual end of selection. This seems to be a non-standard behavior, as probably every other application behaves as expected. **Any update on a fix?**

Interestingly, the swap only occurs if you click inside the selection (to subtract from it). It behaves normally when clicked outside (to add more to the selection).
