### ISSUE TITLE
Go to File not finding newly-added files

### ISSUE THREAD

**Issue by glenn-barnett** [Microsoft/vscode#47094]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Add a new javascript library to my project, such as patternomaly.js
2. Cmd-P or File > Go to File...
3. Type "patternomaly"

Expected result:
* patternomaly.js listed as a navigable option

Actual result:
* "No results found"

Note: if I open patternomaly.js in code first, then it will be found under "recently opened", but it will not be found in "file results".

Note 2: my files.exclude setting is:
```
    "files.exclude": {
        "**/migrations/**": true,
        "venv/**": true,
        "db.sql*": true,
        "lib/**": true,
        "logs/**": true,
        "**/__pycache__/**": true
    },
```

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by roblourens** [comment]
- Can you find any other files (besides in "recently opened")?
- Does it work in other folders?
- Is that file covered by one of the files.exclude patterns?
- Is it covered by a .gitignore file?

**Comment by glenn-barnett** [comment]
I can find other files via Go to File - python files, django html templates, text files.

Any attempt to go to .js or .css will only show results in the "Recently Opened" subpanel.

There is a .gitignore file but it does not cover the .js or .css files.

**Comment by chrmarti** [comment]
@glenn-barnett Does the Explorer viewlet show the file? Do get text search (`Cmd+Shift+F`) results for that file?

**Comment by glenn-barnett** [comment]
The results do show in explorer.

I do not get text search results for these files (tried all variants of case sensitivity, whole word, and regex).

**Comment by chrmarti** [comment]
What is the path of the file relative to the workspace folder? Do you have the `search.exclude` setting set?

**Comment by roblourens** [comment]
There is no index, it will search fresh each time.

Another way to debug is to toggle the "Use Exclude Settings and Ignore Files" button (bottom right)

![image](https://user-images.githubusercontent.com/323878/37785522-9b4d3162-2db7-11e8-9011-5ca513e789b9.png)

Then you can do a text search without using any of the .exclude settings or .gitignore file, just to make completely sure.

**Comment by glenn-barnett** [comment]
OK.  I copied `jquery-1.10.2.min.js` out of `/static` and into another folder `/ops`:

* Cmd-P was able to find `/ops/jquery-1.10.2.min.js` under file results, but not the copy in `/static`
* Cmd-shift-F (search) was able to find both

Same result with plugins enabled and disabled.

**Comment by chrmarti** [comment]
Have you checked your `search.exclude` setting?

**Comment by glenn-barnett** [comment]
I have - I haven't specified any `search.exclude`.

**Comment by roblourens** [comment]
You said it works in search, is that with "Use Exclude Settings and Ignore Files" toggled on or off? Just checking because earlier you said search didn't find them.

**Comment by glenn-barnett** [comment]
OK, I didn't understand the "Use Exclude Settings and Ignore Files" previously.  Here's the update:
* With the search gear icon inactive (no blue border), I can locate `jquery-1.10.2.min.js` via Search, but NOT via Go to File
* With the search gear icon active (blue border shown), I cannot locate `jquery-1.10.2.min.js` via Search nor by Go to File

**Comment by roblourens** [comment]
Ok, that means that the file is covered by a .exclude pattern or .gitignore file. Make sure you check workspace settings. You can set `"search.useIgnoreFiles": true` to disable gitignore checking to narrow it down.

That button only affects search, not quickopen.

**Comment by glenn-barnett** [comment]
I added `"search.useIgnoreFiles": true` to my user settings, and did not observe a change - search still does not find the file with the gear blue border active, but it does with the gear blue border inactive.

There are no other search configuration entries in user settings nor workplace settings.

**Comment by glenn-barnett** [comment]
Update - I set `"search.useIgnoreFiles"` to **`false`**, which made search find the file with both search exclude(gear) settings.

So if Go to File is using the same exclude rules, I should be able to find an exclude/ignore rule somewhere that's omitting my .js files in static - so far I've been unable to find such a rule.

**Comment by roblourens** [comment]
Sorry, false is correct. Sounds like it's covered by a pattern in a gitignore file then.

**Comment by glenn-barnett** [comment]
I found it - it was not in `.gitignore`, but rather an `.ignore` file that my colleague had set up for his emacs setup.

Thanks for your help on this.
