### ISSUE TITLE
Add Snippet Shortcut Maker

### ISSUE THREAD

**Issue by JLChamberlain** [Microsoft/vscode#47095]
I really love creating snippets in VSCode for making my coding easier & quicker but I find the normal way of creating a snippet a little unnecessary!, having to put it all in manually & making sure it is all correct is slightly annoying. I have used extension [like this](https://marketplace.visualstudio.com/items?itemName=nikitaKunevich.snippet-creator) but they seem to no longer work & I was wondering if there was anyway if you could implement a similar feature to VSCode or make an official extension for it.

Having the ability to just select the text you want as a snippet & then right click & select the option "Create New Snippet" & then go through the process of naming the snippet, shorcut command & description is alot easier. Any chance of this happening?

I would also just like to say thanks to everyone who works on developement of VSCode since its my go to tool for all my coding needs & makes learning code easier for me a begginer so it's greatly appreciated. Thanks

**Comment by usernamehw** [comment]
Duplicate of #26706 ?

**Comment by JLChamberlain** [comment]
Seems #26706 is somewhat the same idea. I will close this issue since it’s basically the same idea.
