### ISSUE TITLE
Terminal colours show as escape sequences for python

### ISSUE THREAD

**Issue by ztolley** [Microsoft/vscode#47097]
**vscode:** 1.21.1
**OS:** Windows 10 1803 17133.1

Does this issue occur when all extensions are disabled?: **Yes**

### Steps to reproduce in terminal:

1. Install python 3.5,x
2. Install Django (pip install django)
3. Create a django project (django-admin startproject test)
4. Open the project in vscode
5. Open a powershell integrated terminal and enter `python manage.py`

**Expected**
The list of admin commands should be displayed with section headings in red, surrounded by brackets. 

In the native PowerShell terminal, the text stays all white and the colours are ignored. In conemu in a PowerShell terminal, the colours are shown. 

**Actual**
The list of commands is displayed but before and after the brackets an escape sequence is shown. This is the code used to tell the terminal to use red.

e.g. ?[31m[django]?[0m

![terminal1](https://user-images.githubusercontent.com/56056/38210697-1067b7d2-36b0-11e8-8f8d-cb6125596790.PNG)

**Comment by Tyriar** [comment]
Tracked in  https://github.com/Microsoft/vscode/issues/45693
