### ISSUE TITLE
Expose Electron's clipboard API to extensions

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/vscode#47093]
When writing extensions right now we have to use a node module such as `copy-paste` in order to access the clipboard. This leads to issues such as https://github.com/Microsoft/vscode-mssql/issues/1059 and https://github.com/Microsoft/vscode-mssql/issues/1036 since it is not closely integrated with VS Code.

For extension authors it would be helpful if VS Code exposed some or all of [Electron's `clipboard` API](https://electronjs.org/docs/api/clipboard) since it would make it much easier to get copy/paste working in a way that integrates nicely with VS Code and Electron.

**Comment by jrieken** [comment]
see #217

**Comment by octref** [comment]
#217 is reopened :)
