### ISSUE TITLE
Support for project subfolders with their own git repo

### ISSUE THREAD

**Issue by slothbag** [Microsoft/vscode#4710]
My project has one root folder with a bunch of related projects in subfolders each with their own git rep attached.

In Xamarin Studio it shows each project/subfolder with a description of which branch each repo is on.. i.e. "master". So instantly I can see each project is its own repo and which branch they are currently set to.

I deliberately avoided git submodules for other reasons.

Is it possible for VSCode to support different subfolders each with their own git repo?

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/396

**Comment by joaomoreno** [comment]
Yeah, closing as duplicate of #396
