### ISSUE TITLE
Marketplace category "Languages" changed to "Programming Languages"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#47103]
The Marketplace has changed the "Languages" category to "Programming Languages" (to differentiate the category from "Language Packs")

The vscode extension package.json schema needs to be updated,  (src\vs\workbench\services\extensions\common\extensionsRegistry.ts) as well as the vscode-generator-code ext-language template.

There may be other changes required.

**Comment by roblourens** [comment]
Should it be fixed for 1.22 @gregvanl?

**Comment by aeschli** [comment]
I pushed some changes to master (1.23).
Now there's a validation error if you still use 'Languages' in categories.
So for a better user experience, we should push the change to 1.22 as well.

I will update the vscode-generator-code as soon as the change is in a stable build.

**Comment by aeschli** [comment]
I pushed a improvement that 'Languages' get a deprecated warning (not an error). So no need to rush this in 1.22.

**Comment by aeschli** [comment]
Also pushed changes to our yeoman generator.

Marking as fixed. @gregvanl Do you coordinate the other changes?
That's what I imagine:
In the marketplace: Covert all published extensions that use 'Languages' to use 'Programming Languages' 
Give good error feedback when trying to publish an extension still using 'Languages'

**Comment by gregvanl** [comment]
@aeschli I having been coordinating this, I just heard from @seanmcbreen about the change with respect to the docs and figured we'd need to change the product to match.

**Comment by aeschli** [comment]
Verifiers:
Create an extension that uses the old keyword ('Languages') and verify that you get a warning.
