### ISSUE TITLE
CompletionList should be able to point to best suggestion

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#47102]
Issue Type: <b>Bug</b>

(Recommended completions were added in Microsoft/TypeScript#20020.)
Test with:
```ts
enum E { A, B }
const e: E = 
```
Hit ctrl-space to get completions after the `=`. `E` will be put at the top of the completions list instead of sorted by name. The problem is, the completion list is immediately focused on `console`, leaving `E` offscreen where it will probably never be seen. It would be better to immediately focus on `E`, and leave it sorted by alphabetically.

VS Code version: Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T14:36:39.526Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.63GB (1.66GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders src|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jrieken** [comment]
use `"editor.suggestSelection": "first",`

**Comment by andy-ms** [comment]
@mjbvz Could you reopen this? Based on our discussion yesterday, the editor should prioritize the currently recommended completion over reusing a previous completion.

**Comment by mjbvz** [comment]
@jrieken We'd like a way for extensions to flag a suggestion as `recommended` so that it takes priority over the suggestion history

**Comment by jrieken** [comment]
We have this as `preselect`: https://github.com/Microsoft/vscode/blob/769013834ce9824ecf7768965eecb08dd4308e7d/src/vs/vscode.d.ts#L3211
