### ISSUE TITLE
[Improvement] Declare Method to create new method below the one currently in

### ISSUE THREAD

**Issue by sommerper** [Microsoft/vscode#47105]
- VSCode Version: 1.21
- OS Version: Windows 10 and MacOS

Steps to Reproduce:

1. Call an undeclared method
2. Ctrl+. and select "Declare Method"

Currently when I use VSCode to declare a new method it ends up at the top of the class. I'm probably not the only one who would never declare a new method up there but rather right below the method I'm currently in.

If I'm declaring the new method from another class I'd prefer it to end up at the bottom.

Thanks for reading.

**Comment by mjbvz** [comment]
Thanks. Tracked upstream by https://github.com/Microsoft/TypeScript/issues/22674
