### ISSUE TITLE
Need the file path to be shown at somewhere in VS Code editor

### ISSUE THREAD

**Issue by Prasool** [Microsoft/vscode#47106]
Issue Type: <b>Feature Request</b>

It will be helpful if you could add a feature by default show the path of current active file in editor. May be at VS Code title bar or  at bottom. Should be able to copy that as well.
I know the path shows when you hover the file name. It is helpful to show path, especially when using two monitor, and dont have to hover.

Thanks!

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

**Comment by mjbvz** [comment]
See the `window.title` setting. The full path is under `${activeEditorLong}`

**Comment by jasonpezzimenti** [comment]
What about an extended tooltip that shows filename and file path when
hovering over the files list item and a context menu item to copy the file
path?

**Comment by adsingh14** [comment]
Need of full path in title bar.
