### ISSUE TITLE
textDocument/formatting and /onTypeFormatting behave strangely when an edit ends at the cursor position

### ISSUE THREAD

**Issue by JakeBecker** [Microsoft/vscode#47107]
Issue Type: <b>Bug</b>

For a `TextEdit` returned by `textDocument/formatting` and `textDocument/onTypeFormatting`, if the edit range starts before the current cursor position and ends at the cursor position, I expected the text to be inserted before the cursor. This seems to happen unless the text ends in whitespace, and the behavior is different for `formatting` and `onTypeFormatting`.

For example, I made a language server return the following response to any format request:

```json
[  
   {  
      "newText":"x\n  ",
      "range":{
         "start":{
            "line":0,
            "character":0
         },
         "end":{  
            "line":1,
            "character":0
         }
      }
   }
]
```

Starting with the following document, with `renderWhitespace` set to `"all"` and the cursor placed as shown:

![screen shot 2018-04-02 at 2 19 59 pm](https://user-images.githubusercontent.com/547940/38217466-59d78b72-3683-11e8-9538-03c6b8dd1ffe.png)

Immediately after doing a `textDocument/formatting` request, this is the result:

![screen shot 2018-04-02 at 2 20 37 pm](https://user-images.githubusercontent.com/547940/38217487-72163e04-3683-11e8-8a8c-e33fed5e3a0f.png)

As you can see, the `newText` was inserted before the cursor, but the two spaces following the `\n` are highlighted automatically for some reason, so if I begin typing, it replaces those spaces with what I type. I can't think of any use case in which I'd want `textDocument/formatting` to highlight part of the document for me.

If I do a `textDocument/onTypeFormatting` request from the same starting document, I get the following:

![screen shot 2018-04-02 at 2 41 44 pm](https://user-images.githubusercontent.com/547940/38217689-20cddbbe-3684-11e8-831c-c8631b3a7247.png)

In this case, the `x\n` was inserted before the cursor, but the two spaces were inserted after the cursor.

I can't find any way to make `onTypeFormatting` increase the indentation before the cursor, no matter what I try. I would like to add support for `onTypeFormatting` to the Elixir Language Server which I maintain, but the current behavior makes that impossible. I recommend adding a property to the return value for `onTypeFormatting` to specify the cursor position.

Thanks!

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.86GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>
I can't test whether this is reproducible without extensions because it requires a language server. I did, however, try removing all auto-indentation rules from the language configuration and this did not solve the problem.

**Comment by dbaeumer** [comment]
@jrieken @alexandrudima any comments. The LSP hands these edits one to one over to the VS Code API.

**Comment by alexandrudima** [comment]
I can no longer reproduce the first problem. I believe 3f205ed5d7071651e30625c0c2b0cc448e4bd737 also fixed it. I have tried with the following extension:

* `package.json`:
```js
{
    "publisher": "alex",
    "name": "47107",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```

* `index.js`
```js
const vscode = require('vscode');

exports.activate = function () {
	vscode.languages.registerDocumentFormattingEditProvider('plaintext', {
		provideDocumentFormattingEdits: (document, options) => {
			return [vscode.TextEdit.replace(new vscode.Range(0, 0, 1, 0), 'x\n  ')];
		}
	})
}
```

* `47107.txt`
```
a
|

```

`|` indicates the cursor position when I execute format document.

---

I can still reproduce the second problem with the following steps:

* `package.json`:
```js
{
    "publisher": "alex",
    "name": "47107",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```
* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {
	vscode.languages.registerOnTypeFormattingEditProvider('plaintext', {
		provideOnTypeFormattingEdits: (document, position, ch, options) => {
			return [vscode.TextEdit.replace(new vscode.Range(0, 0, 1, 0), 'x\n  ')];
		}
	}, '\n');
}
```
* `47107.txt`:
```
a|

```
plus using `"editor.formatOnType": true` and then pressing <kbd>Enter</kbd>.

@jrieken The format on type code goes through an `EditOperationsCommand` and through `editor.executeCommand` and not through `editor.executeEdits`. The `EditOperationsCommand` goes back to before the first public vscode release and has some weird massaging for the way in which it tracks selection. Perhaps it could also use `editor.executeEdits`.

**Comment by dbaeumer** [comment]
@alexandrudima thanks for looking into this.

**Comment by JakeBecker** [comment]
I verified the fix in the Insiders build, but unfortunately, it breaks existing behavior in the Elixir Language Server.

Before, I was relying on the existing behavior where edits that begin and end at the cursor position are inserted immediately after the cursor. I was using this to automatically close code blocks.

For example, starting from the following document with the cursor placed as shown:

<img width="219" alt="start" src="https://user-images.githubusercontent.com/547940/39659120-57a87a2a-4fd6-11e8-875d-884036116d59.png">

`onTypeFormatting` triggers on `"\\n"`, and it inserts `"\\nend"` resulting in the following document, where the cursor is correctly positioned:

<img width="216" alt="good" src="https://user-images.githubusercontent.com/547940/39659132-89111162-4fd6-11e8-9a9c-e19920d480e6.png">

Now, though, the same edit is inserted before the cursor, resulting in the following:

<img width="220" alt="bad" src="https://user-images.githubusercontent.com/547940/39659138-a4dcd390-4fd6-11e8-8c97-3eaeaf6dcb08.png">

This is a problem with having the cursor behavior in `onTypeFormatting` behavior be undefined in the Language Server Protocol. ElixirLS is relying on this behavior in production, and as far as I can tell, there's no way to achieve it using the new behavior in the Insiders build.

I'm not the only one who's been confused by the unspecified cursor behavior. Here's one issue, and I know there are more: https://github.com/Microsoft/TypeScript/issues/11074 . I stand by my previous recommendation that you add a field to the return value for `onTypeFormatting` to specify the new cursor position.

@jrieken should I open a new issue for this?

**Comment by JakeBecker** [comment]
Actually, I can work around this by crafting the edits to clear everything after the cursor on the line it's on, and inserting `end` plus whatever would have followed after that on the next line. It's a hack, and it won't work if you're editing the last line of the file, but it should preserve the previous functionality most of the time.

Really, though, it shouldn't require this much hackery to get the cursor to end up where I want it. Please consider adding cursor position as a field on the return value.

**Comment by jrieken** [comment]
>  I stand by my previous recommendation that you add a field to the return value for onTypeFormatting to specify the new cursor position.

Well, there can always be more than one cursor, so please keep that in mind...

> Before, I was relying on the existing behavior where edits that begin and end at the cursor position are inserted immediately after the cursor. I was using this to automatically close code blocks.

Can you describe that with a real code sample and the exact edits your are sending?

**Comment by JakeBecker** [comment]
Sure. In the example I screenshotted in the previous comment, the text when the user hits enter and the `onTypeFormatting` request is sent is:
```
Enum.each([], fn ->
  )
```

The cursor position is `{1, 2}` (immediately before the rparen on the second line). The server returns the following:

```
[
  {
    "newText": "\nend",
    "range": {
      "end": {
        "character": 2,
        "line": 1
      },
      "start": {
        "character": 2,
        "line": 1
      }
    }
  }
]
```

As you can see, the `"\nend"` is inserted at the cursor position. VS Code used to insert it immediately after the cursor, but now it inserts it immediately before the cursor.

The crux of the problem is that before, it was impossible to insert text immediately before the cursor, and now it's impossible to insert text immediately after the cursor. If the insert position is at the cursor, then it's ambiguous in the protocol whether it should go in front or behind. That's why I think there should be an additional field, something like `"cursorHint"` that specifies where the cursor should end up. If there are multiple cursors, it would probably make sense to apply the hint to whichever one is at the position that the request was sent from.
