### ISSUE TITLE
Add command line completion in zsh for the "code" command

### ISSUE THREAD

**Issue by Mellbourn** [Microsoft/vscode#47101]
Feature request:

I think it would be nice if vscode included zsh command line completions for the `code` command. So I've implemented that in this script https://github.com/Mellbourn/dotfiles/blob/master/.zsh-personal-completions/_code. 
This implementation gives completion for all documented parameters and has specialized completion for parameters that don't take filenames as parameters, for example `--add` only take directories as arguments.
I have tested that it works well on macOS and Windows Subsystem for Linux (Ubuntu).

I will gladly submit this file as part of a pull request.

However, this file needs to be in the `PATH` or `fpath` environment variable if it is to take effect in zsh. Unfortunately I have no good idea how to implement the deploy mechanism to achieve that.

I am very open to suggestions on how to proceed.

**Comment by joaomoreno** [comment]
@Mellbourn We suggest to provide this as an external tool.

**Comment by Mellbourn** [comment]
@joaomoreno makes sense. I'll submit it to https://github.com/zsh-users/zsh-completions, that is a large library of completions for zsh.

**Comment by joaomoreno** [comment]
That'd be awesome!
