### ISSUE TITLE
JSX file formatting modifies tag contents

### ISSUE THREAD

**Issue by THemming** [Microsoft/vscode#4711]
- VSCode Version: 0.10.11
- OS Version: Max OS 10.11.4

Steps to Reproduce:

1. Create a JSX file with the following contents:
  ```jsx
  import React from 'react';
  
  export default ({message}) => {
      return (
          <li>{message}. Something else.</li>
      )
  }
  ```
2. Format the code (shift-alt-f)

Notice that the space between the full-stop and "Something" gets removed.

Expected:
Text content within JSX tags should not be modified.

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#140
