### ISSUE TITLE
Column Selection not working with editor.multiCursorModifier: ctrlCmd on macOS

### ISSUE THREAD

**Issue by elado** [Microsoft/vscode#47111]
- VSCode Version: 1.21.1
- OS Version: macOS 10.13.3

### Steps to Reproduce:

With default `editor.multiCursorModifier` (which is `alt`), alt+shift+click+drag works, and allows column selection

With `"editor.multiCursorModifier": "ctrlCmd"`, it doesn't work anymore. Neither does alt+shift+cmd+click+drag.

**Comment by alexandrudima** [comment]
On OSX,

when `editor.multiCursorModifier` is `alt` (the default), then:
* `cmd+click` opens links or goes to definition
* `alt+click` adds cursor
* `alt+shift+click/drag` does column selection

when `editor.multiCursorModifier` is `ctrlCmd`, then:
* `alt+click` opens links or goes to definition
* `cmd+click` adds cursor
* `cmd+shift+click/drag` does column selection
