### ISSUE TITLE
TSX attribute autocompletes incorrectly

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#47112]
```ts
class MyComponent extends React.Component<{ abc: number }> {
}

<MyComponent
    key="hi"
    
/>
```

- Cursor on the line after `key`
- ctrl+space
- Pick `abc`
- It inserts `abc` 👍 
- Delete that. Type `abc`
- Pick `abc` from the suggestion list
- It inserts `{abc}` 🐛 

Seems to only happen after another attribute which is why `key` is there

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23099
