### ISSUE TITLE
Got "The category 'Languages' is not available in language'en-us'" When publishing extension

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode#47114]
Screenshot:
![image](https://user-images.githubusercontent.com/6193897/38224152-32071f42-3721-11e8-8d7b-9192016d712d.png)

My defined categories:
```
"categories": [
    "Languages",
    "Azure",
    "Other"
],
```

**Comment by roblourens** [comment]
This has been changed to "Programming Languages", ref #47103

@gregvanl Seems like we should support backwards compatibility rather than breaking everyone's extension publish, who can I ask about this?

**Comment by jdneo** [comment]
@roblourens Thanks for the information.

**Comment by roblourens** [comment]
I tested and was able to upload an extension with the "Languages" category. I think they are trying to support it for backcompat. On the vscode side it is only deprecated until next month.
