### ISSUE TITLE
PHP Language Mode Somehow Gone

### ISSUE THREAD

**Issue by JCCasey** [Microsoft/vscode#47110]
- VSCode Version: Version 1.21.1
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Click language mode
2. PHP option no longer available
3. I uninstalled and reinstalled VS Code
![no-php](https://user-images.githubusercontent.com/5806732/38219323-0c25d35a-36a3-11e8-8645-a9d712bd16b7.png)
 option no longer available

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by JCCasey** [comment]
@roblourens  That works! What;s the deal?

**Comment by roblourens** [comment]
I don't know, but the next release will be out in a couple days, and we made some changes to the PHP extension which must have fixed it...

**Comment by JCCasey** [comment]
Sweet. Thank you.
		
		

		Best Regards,
Justin Casey978-836-8956
	




On Mon, Apr 2, 2018 at 8:11 PM -0400, "Rob Lourens" <notifications@github.com> wrote:












I don't know, but the next release will be out in a couple days, and we made some changes to the PHP extension which must have fixed it...
