### ISSUE TITLE
Lines with non-ASCII characters are always marked as changed when encoding is changed

### ISSUE THREAD

**Issue by yuba** [Microsoft/vscode#47119]
- VSCode Version: 1.21.1
- OS Version: OS X 10.12.6

Steps to Reproduce:

1. Create a text file with non-utf8 encoding, such as EUC-JP or SHIFT-JIS.
2. git add/commit the file.
3. Open it with VSCode using appropriate encoding.
4. Lines which have non-ASCII characters are marked as changed.

![2018-04-03 13 25 10](https://user-images.githubusercontent.com/927850/38229185-84a98c3c-3742-11e8-834c-149e361c3fa8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/21146#issuecomment-376512907
