### ISSUE TITLE
Use different layouts for different Markdown Heading Headline levels.

### ISSUE THREAD

**Issue by feluxe** [Microsoft/vscode#47113]
- VSCode Version: 1.21.1
- OS Version: Arch Linux

Hi there!

The Spacemacs markdown layer has a cool feature, which I miss a lot in VSCode.

It uses different font sizes/colors for displaying the different heading levels:

![headings](https://user-images.githubusercontent.com/6545589/38223683-69336e1a-36ec-11e8-927d-4c0498f01369.png)

This becomes extremely useful when your file has nested sections like in this example:

![headings_sm](https://user-images.githubusercontent.com/6545589/38223795-0b834118-36ed-11e8-96e1-5fca50ccb27b.png)

In VSCode it's difficult to distinguish each section and it becomes more confusing with each level:

![headings_vs](https://user-images.githubusercontent.com/6545589/38223825-44b1aa88-36ed-11e8-99f1-9f7442019ad9.png)

Any love for this?

**Comment by vr8hub** [comment]
Speaking generically, it would be nice to be able to specify the CSS for the editor portion of a Markdown file just like we can for the Preview portion of a Markdown file. Then we could format it however we wanted to.

**Comment by mjbvz** [comment]
This should come from themes but we don't provide heading level specific scopes.

If someone wants to look into this, here's where the markdown grammar lives: https://github.com/Microsoft/vscode-markdown-tm-grammar

The required fix would would be similar to what language-markdown does: https://github.com/burodepeper/language-markdown/blob/master/grammars/repositories/blocks/headings.cson

**Comment by mjbvz** [comment]
To verifier: try using a setting such as

```json 
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "heading.2.markdown",
                "settings": {
                    "foreground": "#ff00ff",
                }
            }
        ]
    }
```

to change heading styles. We should support heading levels 1-6

**Comment by kellpossible** [comment]
https://github.com/Microsoft/vscode-markdown-tm-grammar/pull/13 doesn't entirely address this feature request because it doesn't alter the heading font size per level right?

**Comment by vr8hub** [comment]
Correct.
