### ISSUE TITLE
Git ignore is not working 

### ISSUE THREAD

**Issue by Sasicumaar** [Microsoft/vscode#47127]
Issue Type: <b>Bug</b>

Git ignore is not working 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|Memory (System)|15.89GB (8.38GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe D:\Develop\PestBusters|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
html-class-suggestions|And|1.0.7
ignoregit|And|1.0.1
materialcolorsnippets|bru|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
compulim-vscode-closetag|Com|1.1.0
angular2-snippets|dan|1.0.19
gitlens|eam|8.2.0
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.3.0
mssql|ms-|1.3.0
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.3.0
vscode-material-design-lite-snippets|smk|0.0.1
ignore-gitignore|stu|1.0.1
html-snippets|wge|0.1.5
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
