### ISSUE TITLE
Scrolling down slowly with a touch pad doesn't work

### ISSUE THREAD

**Issue by saitam1** [microsoft/vscode#47124]
- VSCode Version 1.21.1
- OS Version Ubuntu 16.04
- Notebook: XPS13

Steps to Reproduce:
1. Open any file
2. scroll down slowly

`Scrolling down slowly` doesn't work. Also tried pressing harder on the touch pad, doesn't work. The sheet is just not moving. I don't have this issue when `scrolling up` or using another editor e.g. `Atom`

**Comment by alexandrudima** [comment]
@saitam1 

Can you please try the insiders version, perhaps things are improved with our updating to Electron 2.0 -- https://code.visualstudio.com/insiders/
