### ISSUE TITLE
TextEditorEdit support normalization of '\t'

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#47129]
Issue Type: <b>Feature Request</b>

As per documentation:

```
	export interface TextEditorEdit {
		/**
		 * Replace a certain text region with a new value.
		 * You can use \r\n or \n in `value` and they will be normalized to the current [document](#TextDocument).
		 *
		 * @param location The range this operation should remove.
		 * @param value The new text this operation should insert after removing `location`.
		 */
		replace(location: Position | Range | Selection, value: string): void;
```

`TextEditorEdit` supports normalizing carriage returns. It'd be great to also normalize tabs (`\t`). 

Related VSCodeVim issue (https://github.com/VSCodeVim/Vim/issues/2501) where users try to do a search in replace which internally uses a `TextEditorEdit` but instead of seeing a tab, they see the literal `\t`.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by jrieken** [comment]
Can you give me an extension snippet and document that shows how this should work? I do believe that we normalise indentation

**Comment by jpoon** [comment]
Here is what I was trying

```
     const regex = new RegExp(",","g");
     const originalContent = "abc,abc,abc";
     const newContent = originalContent.replace(regex, "\tabc\n");
     const range = vscode.window.activeTextEditor!.selection;

     vscode.window.activeTextEditor.edit(builder => {
         builder.replace(new vscode.Range(0, 0, 0, originalContent.length), newContent);
    });
```

Interestingly, this works on my mac. Wasn't working last night on my Windows machine; will double-check later and see if I was doing something funky last night.
