### ISSUE TITLE
F12 stopped working if the definition belongs to some other class

### ISSUE THREAD

**Issue by kaushikpathak** [Microsoft/vscode#47125]
- VSCode Version: 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows 10

Steps to Reproduce:

1. Create a class say class A.
2. Create a function say f1 inside class A.
3. Create another class B.
4. Import class A here in B (import A from './A').
5. Create a function f2 in class B.
6. Call function f1 inside f2 (A.f1()).
7. Now press f12 on f1.
8. You will not be navigate to the function f1 and you will get a message "No definition found for 'f1'".
9. The same will work fine when trying to call function of same class. Previously it was working as expected.

**Comment by kaushikpathak** [comment]
Anyone looking into this issue? This issue is causing lot of trouble while navigating towards the definition of the function.

**Comment by mjbvz** [comment]
Seems fixed in the latest VS Coe insiders in my testing:

`a.js`
```js
//@ts-check
export default class A {
    f1() {}
}
```

`b.js`
```js
//@ts-check
import A from './a'

class B {
    f2() {
        new A().f1()
    }
}
```
