### ISSUE TITLE
Tooltip not displayed properly first time you pass the mouse over it

### ISSUE THREAD

**Issue by daniglezad** [microsoft/vscode#47135]
Issue Type: <b>Bug</b>

Just pass the mouse over any icon that automatically pops up info in a black square and you will see how the text is not displayed (moved downwards). It is only when I pass it a second time that I can see the text displayed properly in its black bounding box.
Didn't check if this happens with or without extensions.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

**Comment by dbaeumer** [comment]
@daniglezad can you attach a screen cast showing this. I have problems understanding where exactly this is happening.

**Comment by daniglezad** [comment]
Fiirst pass:

![bug_a](https://user-images.githubusercontent.com/16767300/38251781-5136bf7a-374a-11e8-8f28-d1cd16728f3b.png)

Second pass:
![bug_b](https://user-images.githubusercontent.com/16767300/38251791-5b327866-374a-11e8-9e5c-bccf47149075.png)

**Comment by dbaeumer** [comment]
Looks like the file explorer.
