### ISSUE TITLE
Preserve relative size of debug view sections

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#47131]
Issue Type: <b>Feature Request</b>

**Steps to reproduce:**
1. Start with a minimized window. Note the line next to the "Breakpoints" section.
2. Maximize the window.
3. Resize the call stack section below the line noted in step 1.
4. Minimize the window. Sections get moved up.
5. Maximize the window. Call stack is now extra large.

I would expect that each section would maintain the same percentage of space used.

VS Code version: Code - Insiders 1.22.0-insider (5b893c1525c8504845d15a5c2d76b7975e0ac4c2, 2018-04-03T06:33:55.219Z)
OS version: Windows_NT x64 10.0.16299

Extensions: none

**Comment by isidorn** [comment]
This is a general issues of the split view, forwarding to @sandy081 and @joaomoreno

**Comment by bpasero** [comment]
Isn't this working now after the changes we did for grid?

**Comment by isidorn** [comment]
Yeah this works nicely now thanks @joaomoreno closing
