### ISSUE TITLE
Error when (git) staging lines in submodule

### ISSUE THREAD

**Issue by JensMadsen** [Microsoft/vscode#47133]
- VSCode Version: Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:30.761Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: ubuntu 17.10

Steps to Reproduce:

1. open file under git version control which resides in a submodule with changes in "working tree"
2. select lines and "stage selected lines"
3. error: Git: illegal value for 'line'

**Comment by joaomoreno** [comment]
Are you sure this is related to the submodule? I can't reproduce. If you open that submodule as a single repository, does it still reproduce?

Can you show me the file and the **exact** change you performed in it?

**Comment by lsim** [comment]
I too am seeing this. I can no longer 'stage selected ranges' nor 'unstage selected ranges' without getting stopped by this same error. Will see if I can spot a pattern in which files are affected and which (if any) are not.

Note that this issue bears a remarkable resemblance to #32681 (which is closed an locked).

**Comment by lsim** [comment]
Having had a closer look, I am only having this problem with one file. The diff of that file ends with the following:

```
-</Project>
+</Project>
\ No newline at end of file
```

The bug only occurs for me when the diff involves removing the last line. This again seems similar to the repro steps of #32681, where the first line was deleted to trigger the issue. 

More of what fixed that issue to fix this one?

**Comment by lsim** [comment]
Yup - deleting a trailing newline in any file seems to trigger the bug.

**Comment by joaomoreno** [comment]
@lsim Great job narrowing that down!

@JensMadsen Can you confirm if you have the same issue?

**Comment by lsim** [comment]
Bad bot! :)

There is definitely actionable information on this issue. The only remaining question is whether OP was in the same corner case as me. It should be very easy to fix the one known cause for the breakage this ticket concerns. 

Whether other corner cases can lead to it remains to be determined.
