### ISSUE TITLE
Auto import suggestions create invalid imports when re-exporting with aliases

### ISSUE THREAD

**Issue by gsteacy** [Microsoft/vscode#47139]
- VSCode Version: 1.21.1
- OS Version: Windows 8.1 x64

Steps to Reproduce:

Given the following files:

module1.ts
```ts
export function myFunction() { };
export default myFunction;
```

index.ts
```ts
export { myFunction as func1 } from "./module1";
```

1. In another file, type "myFunction" and you'll see the following:

![image](https://user-images.githubusercontent.com/6236395/38246863-79ee3308-3786-11e8-8dc2-e70b4d357680.png)

2. Select either option and the following invalid import will be added:

```ts
import { myFunction } from ".";
```

The quick fix list will have the correct suggestions and will create the correct import:

![image](https://user-images.githubusercontent.com/6236395/38247289-0f53f90e-3788-11e8-85b4-be7fb4d5fc81.png)

This behaviour also occurs if re-exporting the default export with an alias.

4. In the new file, type "func1" and no suggestions will be given. The quick fixes list will have the correct suggestions and will create the correct import:

![image](https://user-images.githubusercontent.com/6236395/38247330-3d017cdc-3788-11e8-9c93-47f9bb6c3a5d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23186

**Comment by octref** [comment]
Verified. But @gsteacy I guess your `index.ts` should probably be `import` instead of `export`, right?
