### ISSUE TITLE
Workspace: running out of file handles

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#47138]
I have this notification, only when using workspaces

    Visual Studio Code is running out of file handles. 
    Please follow the instructions link to resolve this issue.

If I use 2, or more instances of vscode I won't get it

And I'm definitely under the default 8192 handle limit. and have maximum 20 files opened

Maybe `"files.watcherExclude"` is not respected when using workspaces (I added `"**/dist": true, "**/build": true` to the defaults) but that's was not the issue

Version 1.21.1
OS: Linux (Lubuntu 17.10)

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/45295 as we want to go away from requiring so many open file handles.
