### ISSUE TITLE
Pass extention id in command line for extension host process

### ISSUE THREAD

**Issue by abdulkareemnalband** [Microsoft/vscode#47136]
Issue Type: <b>Feature Request</b>

On windows task manager I can see a extension host is taking lot of resources but, it is difficult to know which extension is associated with that, so pass extension id in command line for extension host process like `--ext-id=extension-id`  so that it is easy to disable/report that issue against particular extension

![image](https://user-images.githubusercontent.com/3139353/38246126-577ff86a-375e-11e8-862a-37c06c24a7aa.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by dbaeumer** [comment]
There is only one extension host per VS Code workspace window. The extension host servers multiple extensions. There is a Command to show the running extensions of a extension host. It is 

<img width="462" alt="capture" src="https://user-images.githubusercontent.com/1931590/38251179-05ce9cf4-3751-11e8-8032-bf3ba7b6c95b.png">

Closing the issue.
