### ISSUE TITLE
Go to symbol only works for JS

### ISSUE THREAD

**Issue by chwentao** [Microsoft/vscode#4713]
- VSCode Version:0.10.11
- OS Version:win7

Steps to Reproduce:

1. 
2.

**Comment by Tyriar** [comment]
Translates to: Lookup functions are only valid for JS

**Comment by Lonefy** [comment]
this translation is almost right. I guess “查找函数”  means “go defination”？Could you give more details ，such as operation steps or shortcuts @chwentao？

**Comment by Tyriar** [comment]
If it's about Go to Definition (<kbd>f12</kbd>) not working in another language, which language(s) in particular would be good.

**Comment by chwentao** [comment]
![qq 20160329093605](https://cloud.githubusercontent.com/assets/13378254/14095325/aec8b9e2-f591-11e5-9c19-1a4a06338a66.png)

go to symbol and f12  function, only work in js language.

**Comment by Tyriar** [comment]
I believe go to symbol generally requires an extension to work, for example the C# extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

Closing this, feel free to open a new issue if you have a particular language you're concerned about. It will likely be up to extensions to add this behavior though.
