### ISSUE TITLE
ImportError: No module named module (but when I enter Python, I can import it)

### ISSUE THREAD

**Issue by ronaldgreeff** [Microsoft/vscode#47146]
- VSCode Version: 
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows 10 Pro, 1709, 16299.309

Steps to Reproduce:

1. pip install module
2. create file.py in VSCode
3. right click in VSCode and 'Run python file in terminal"
4. Error on line 1: Cannot import module.
5. Type Python into terminal.
6. Import the module succesfully

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
