### ISSUE TITLE
Allow to show folder name below tab title in a secondary row

### ISSUE THREAD

**Issue by pixmaster** [Microsoft/vscode#47142]
In some projects I have the same file names in different folders. And I see following
![image](https://user-images.githubusercontent.com/3305295/38248964-c3f6b350-3752-11e8-8768-358587f93217.png)
I propose this for resolve my issue and it can fix long paths
![image](https://user-images.githubusercontent.com/3305295/38249144-61075c8a-3753-11e8-9da6-344705da3146.png)
In this case `workbench.editor.labelFormat` will assign only for second line or for compatibility create new `workbench.editor.secondlabelFormat`, first line will always file name.
And proposed structure with format handler
```javascript
"workbench.editor.labelFormat" = {
 "default": "short",
 "src/parent/": "medium",
 "src/parent1/parent2/": "(path)=>(path.split('/').splice(2).join('/')))"
}
```

**Comment by bpasero** [comment]
I would argue this can be done now using breadcrumbs feature. @pixmaster can you:
* download and install insiders release (https://code.visualstudio.com/insiders/)
* enable breadcrumbs via settings

![image](https://user-images.githubusercontent.com/900690/42744925-2a7da754-88d0-11e8-8c00-8d84c2a2dbfd.png)

You should end up with something like this:

![image](https://user-images.githubusercontent.com/900690/42744932-3a26d7a2-88d0-11e8-9442-df803daa8c94.png)

**Comment by pixmaster** [comment]
@bpasero `breadcrumbs` is perfect, I like it, but it little bit different what I meant. Main aim was show differences on inactive tabs, where file placed, especially when files have identical name.

**Comment by bpasero** [comment]
I would merge this into https://github.com/Microsoft/vscode/issues/43806. This would enable you to put the folder name as mandatory thing even for inactive tabs.
