### ISSUE TITLE
results print on integrated terminal

### ISSUE THREAD

**Issue by weqopy** [Microsoft/vscode#47143]
- VSCode Version: 1.21.1
- OS Version: macOS High Sierra 10.13.4

Steps to Reproduce:

1.run a .py file, start debugging or without debugging 
2.the result print on  integrated terminal rather than  debug console
It was OK few days ago and I don't know how it comes to this.
There are screenshots below:
<img width="331" alt="1" src="https://user-images.githubusercontent.com/10494196/38251126-2e2be472-3783-11e8-8509-b1d1bba629a9.png">
<img width="1004" alt="2" src="https://user-images.githubusercontent.com/10494196/38251137-326a9c0e-3783-11e8-8750-bc97ac8fa65a.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by tchapin** [comment]
results print in both debug console AND integrated terminal, but the terminal becomes active every time the program is run. Would prefer to keep the active window the same, for me I want to see debug console every time I run without having to select it.

**Comment by weqopy** [comment]
> results print in both debug console AND integrated terminal, but the terminal becomes active every time the program is run. 

Yeah, it's w when ruright 'start debugging'.
But when 'start without debugging', it only print in integrated terminal, just like what I showed in the first screenshot which is nothing print.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
