### ISSUE TITLE
workspace.textDocuments includes closed documents

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#47140]
In #10304 I was advised that `workspace.textDocuments` was the correct way to get open files; however I'm trying to write tests that rely on documents being closed and finding that they still exist in there despite being closed (I can see in the extension host there there are no open editors).

Here's a sample test:

```ts
it.only("test", async () => {
	// Open two files
	await vs.workspace.openTextDocument(emptyFile);
	await vs.workspace.openTextDocument(everythingFile);
	console.log(`There are ${vs.workspace.textDocuments.length} documents`);

	// Close all files
	while (vs.window.activeTextEditor) {
		await vs.commands.executeCommand("workbench.action.closeActiveEditor");
	}
	console.log(`There are ${vs.workspace.textDocuments.length} documents`);

	// Wait a short period just in case...
	await new Promise((resolve) => setTimeout(resolve, 1000));
	console.log(`There are ${vs.workspace.textDocuments.length} documents`);
});
```

This outputs:

```text
There are 2 documents
There are 2 documents
There are 2 documents
```

**Comment by DanTup** [comment]
Also weird, the `while` loop seems to only execute once.

**Comment by jrieken** [comment]
> however I'm trying to write tests that rely on documents being closed and finding that they still exist in 

You cannot assume the opposite and closing an editor doesn't mean that we close the document too.

**Comment by DanTup** [comment]
@jrieken Then the answer to my original question is not satisfied :( How do I get a list of the documents that are open? I want to provide my language server with a list of priority documents, which are first the visible text editors, and then any editors that are open but not visible.
