### ISSUE TITLE
Add ability to ignore specific exception types while debugging

### ISSUE THREAD

**Issue by Huck** [Microsoft/vscode#47149]
Please add the last missing killer feature of vscode:  the ability to ignore specific exception types while debugging (and/or to break only on specific exception types).

Its sometimes useful to catch all exceptions (handled and unhandled) in the debugger, but it would be nice to be able to tell the debugger to ignore certain annoying exception types. Visual Studio has this feature and it is very useful.  perhaps an exclusion list in the settings would be enough.  Right now it seems to be all or nothing.

thanks!

**Comment by weinand** [comment]
This feature depends on the specific debugger extension.
For what language do you need the feature?

My mono-debugger supports this: 
![2018-04-03_17-47-50](https://user-images.githubusercontent.com/1898161/38260155-29b4dc30-3767-11e8-8ac1-2b736ee808cd.png)

**Comment by Huck** [comment]
I use omni-sharp and C#.  I was not aware of the mono debugger. Should I report this feature to omni-sharp instead?  thank you and sorry if I posted this in the wrong place.  the work you do on vscode is fantastic.

**Comment by Huck** [comment]
oh I see, it seems to be for mono only. I am using dotnet core and omni-sharp. Should I report it there?

**Comment by Huck** [comment]
im sorry, and thank you for your time
