### ISSUE TITLE
Don't ask for confirmation when deleting new empty file

### ISSUE THREAD

**Issue by granteagon** [Microsoft/vscode#47145]
Issue Type: <b>Bug</b>

If I create a new file with the wrong name, and the file has no content, don't ask me to confirm the delete.  I know this is a small issue, but it works in Sublime.  Not a high priority, obviously.

Thanks

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.88GB (5.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
close-all|ben|1.0.2
npm-intellisense|chr|1.3.0
refactorix|chr|0.3.7
vscode-eslint|dba|1.4.8
gitlens|eam|8.1.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
vscode-relative-line-numbers|ext|0.0.5
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
beautify|Hoo|1.3.0
docthis|joe|0.6.0
dotenv|mik|1.0.1
python|ms-|2018.2.1
team|ms-|1.122.0
debugger-for-chrome|msj|4.2.2
typescript-hero|rbb|2.3.1
markdown-preview-enhanced|shd|0.3.4
addDocComments|ste|0.0.8
vim|vsc|0.11.2

(5 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by bpasero** [comment]
@granteagon how do you create the new file in the first place?

**Comment by granteagon** [comment]
@bpasero I right-click on a folder and select New File.
