### ISSUE TITLE
TreeView.reveal is not working if id is not provided to the TreeItem

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#47147]
Steps to reproduce:

Use the Custom view sample [here](https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample)
- Run this extension
- Open the FTP Explorer
- Open `.message` file 
- Collapse the FTP Explorer
- Run the command `Reveal In FTP View`

Expected: .message node should be revealed and selected
Actual: `Error: Cannot resolve tree item for element`

Alternatively you can build your own custom view to reproduce:

- Register a custom view in `package.json`
- Create the custom view using `window.createTreeView` API
- Make sure you do not provide `id` value to the `TreeItem` in your `TreeDataProvider`
- Expand the tree to show the node that we would like to reveal in next step
- Reveal the node using `TreeView.reveal` api

Expected: Requested node should be revealed
Actual: `Error: Cannot resolve tree item for element`

**Comment by pltrant** [comment]
Thanks, @sandy081.  I could have wrote the bug, but wasn't sure if it was just a required component or a bug.  Thanks for the fix!
