### ISSUE TITLE
files.associations php not found

### ISSUE THREAD

**Issue by silentkang** [Microsoft/vscode#47148]
Issue Type: <b>Bug</b>

언어 식별자 목록에 php가 보이지 않습니다.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz (4 x 2659)|
|Memory (System)|7.99GB (3.91GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.2
php-intellisense|fel|2.3.0
php-pack|fel|1.0.1
ftp-simple|hum|0.6.2

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by silentkang** [comment]
![image](https://user-images.githubusercontent.com/26637653/38324584-ade16216-387b-11e8-87a6-9cc31ed6ae23.png)

php not found;

**Comment by roblourens** [comment]
If you search for `@builtin` in the extensions search bar, do you see a builtin PHP extension in any of the sections?

**Comment by silentkang** [comment]
thx

**Comment by roblourens** [comment]
Did you find a solution? What was it? :)
