### ISSUE TITLE
Color Themes do not recognize multi-line variable declarations in JavaScript

### ISSUE THREAD

**Issue by theorphan** [Microsoft/vscode#4714]
- VSCode Version: 0.10.11
- OS Version: Windows 7 Ultimate N

Steps to Reproduce:

1. Open a JavaScript file (.js)
2. Enable the Dark+ color theme through the File > Preferences > Color Theme menu
3. Make a variable declaration, ending in a comma
4. On the next line, make a second variable declaration, ending in a semicolon.

Example: 

```javascript
var a = 0, // This variable will be stylized
    b = 0; // This variable will be not be stylized
```

**Comment by Tyriar** [comment]
This appears to be fixed in master :fireworks: 

![image](https://cloud.githubusercontent.com/assets/2193314/14084942/00cf2b7e-f4d2-11e5-9fe0-d742f6313f2c.png)
