### ISSUE TITLE
Duplicate quick fixes

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/vscode#47159]
Issue Type: <b>Bug</b>

When opening the quick fix dialog for errors reported by TSLint, specifically the ordered imports quick fix, the entries are shown twice:
![unbenannt](https://user-images.githubusercontent.com/17641229/38268715-1b90f82e-377f-11e8-9b22-8305f048b30f.PNG)
Sorry if this report is better posted at the TSLint repo, I'm not sure if that's an extension issue or VSCode related.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3403)|
|Memory (System)|15.96GB (11.68GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.28
java|red|0.21.0
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
Please file an issue against the tslint extension
