### ISSUE TITLE
View Assembly while editing

### ISSUE THREAD

**Issue by LindaC2031** [Microsoft/vscode#47156]
Say I have this code:

char * pReflowFileListIn[kMAX_LIST];
...  
if ((pReflowFileListIn[0] >= 0xFE) && (pReflowFileListIn[1] >= 0xFE))    
       nOffset++;

While editing it would be nice to be able to expand or hilight a section of code and then say view assembly.  Having to compile an entire project and then run the app, take steps so this particular line of code will be executed is a very time consuming process.   If there were some way to have the IDE recompile this module and then expand the dll or exe, etc to view this segment of code with out actually running the app, or reference a previous build this would be fantastic!

Linda

**Comment by roblourens** [comment]
VS Code doesn't offer any support for assembly or C++ out of the box, but this is a good candidate for an extension (or there might already be one). Or the C++ extension might have something to help with this.
