### ISSUE TITLE
"new" after "new" isn't highlighted in javascript

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/vscode#4715]
VSCode Version: 0.10.11
OS Version: Windows 10

![new_new_screenshot](https://cloud.githubusercontent.com/assets/7000710/14084090/7b63ee0a-f519-11e5-9336-c36d595d25b7.jpg)

In this screenshot I was using the Dark+ theme, but the issue can be reproduced with any theme.

**Comment by Tyriar** [comment]
Isn't this invalid JS as `new` is not a constructor?

**Comment by nicolo-ribaudo** [comment]
If the first argument of `Proxy` is a constructor, it returns a constructor.

Try to run this code in Edge/Chrome/Firefox, they will log `fn`:
```js
new new Proxy(function fn() {
    console.log(this.constructor.name);
}, {});
```

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#139
