### ISSUE TITLE
TreeView.reveal on new TreeView

### ISSUE THREAD

**Issue by pltrant** [Microsoft/vscode#47153]
- VSCode Version: 1.22.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Use `createTreeView` in the activate function of an extension
2. Immediately try to use `reveal` on the returned view (while also in the activate function)

Is there a clean way to immediately use `reveal` on a just created `TreeView`?  Specifically, in the activate function of my extension, I have:

```javascript
function activate(context) {
    myView = vscode.window.createTreeView(
        'myView',
        {treeDataProvider: new treeDataProvider()}
    );
    myView.reveal({label: someValue});
}
exports.activate = activate;
```

The problem is that myView is immediately returned and you can call reveal without an error, but it actually doesn't work because the view hasn't been created in the UI yet.  How can I detect when the view has been created in the UI, then call reveal?  I can't even rely on logic in the treeDataProvider constructor due to the same issue (view hasn't been created in the UI yet, so calling reveal from there doesn't work and doesn't generate an error).

**Comment by dakaraphi** [comment]
This is also an issue when updating the treeview and then immediately calling `reveal`.

**Comment by pltrant** [comment]
Is this bug still going to make it for 1.24?  It's the one issue that has prevented me from updating my extension to make use of `reveal`.

**Comment by Gama11** [comment]
You could work around it with a short delay: https://github.com/vshaxe/vshaxe/commit/d340f7d61faac381829eb54a95a09daa748ae047

**Comment by sandy081** [comment]
@dakaraphi Calling reveal after updating a tree view was fixed.
