### ISSUE TITLE
Investigate implications of upgrading to GTK3

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#47158]
- What distro/versions are being left behind? https://github.com/Microsoft/vscode/issues/36218#issuecomment-378253634
- Update requirements https://code.visualstudio.com/docs/supporting/requirements
- Update deb and rpm packages with dependencies on gtk 3.10+

**Comment by Tyriar** [comment]
It was said in https://github.com/Microsoft/vscode/issues/36218#issuecomment-378253634 that CentOS 7.1 (~Fedora 24) could not update to GTK 3.10. This Chromium support page says Fedora 24+ is supported https://support.google.com/chrome/a/answer/7100626?hl=en, however looking at the rpm dependency list only Fedora 25+ is defined https://cs.chromium.org/chromium/src/chrome/installer/linux/rpm/dist_package_provides.json

**Comment by Tyriar** [comment]
@bpasero yeah the plan is to add gtk3 as a hard dependency for both the rpm and deb

**Comment by cannonfodda** [comment]
Hi @Tyriar @bpasero. I didn't mean to say that it's not possible to upgrade on Centos 7.1. The reason that we can't run the test related to #36218 is that we are running on a corporate system and I can't update GTK without falling foul of corporate IT.

Is that why #36218 was closed ?

**Comment by Tyriar** [comment]
We will declare gtk3 as a dep in the packages.

**Comment by bpasero** [comment]
@Tyriar I reverted your change for GTK3 btw because I took out the Electron update.

**Comment by Tyriar** [comment]
ctrl+shift+e doesn't work as it's now meant to be the global emoji picker https://github.com/Microsoft/vscode/issues/48480

**Comment by roblourens** [comment]
@Tyriar anything to verify here?

**Comment by Tyriar** [comment]
@roblourens not really, verification would be done in the Electron 2 test item
