### ISSUE TITLE
Integrated Terminal Window becomes active

### ISSUE THREAD

**Issue by tchapin** [Microsoft/vscode#47150]
Issue Type: <b>Bug</b>

When running a Python script in debugger, the Terminal window receives focus every time, regardless of what window previously had focus.

To reproduce:
1) select "DEBUG CONSOLE"
2) run program
3) Observe that TERMINAL has focus. To see the content in DEBUG CONSOLE you have to click to activate that window.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|Memory (System)|15.91GB (8.49GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
python|ms-|2018.3.1
vscode-code-outline|pat|0.0.13
open-in-browser|tec|1.1.0

</details>
Reproduces without extensions

**Comment by rivasd** [comment]
In my case, not only does it receive focus but an actual terminal session is started as "Python Debug Console", essentially duplicating what is in the Debug Console. This happens at every reload which creates a lot of Terminal tabs. This is quite a bug

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/ /cc @DonJayamanne
