### ISSUE TITLE
Please add "Save Copy As"

### ISSUE THREAD

**Issue by Greengecko19** [Microsoft/vscode#47163]
Issue Type: <b>Feature Request</b>

Especially for newbies unfamiliar with saving code to a repo, it would be useful to add a "Save Copy As" function, so that the user can save the current working version of a file, in case edits get lost during git pulls, etc.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/38287705-541a9a90-37cc-11e8-9c7c-189d811e4b82.png)
