### ISSUE TITLE
Vim Extension very slow when use 'x' to delete

### ISSUE THREAD

**Issue by TrCaM** [Microsoft/vscode#47168]
Issue Type: <b>Performance Issue</b>

Just happenned today. Everytime I pressed x or dd to delete char/line it takes 2 seconds to to the job. It is very annoying and slow me down alot

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|Memory (System)|11.89GB (6.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   106	  1180	code main
    0	    75	  7344	   powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
    0	     7	  8012	     console-window-host (Windows internal process)
    0	    75	 10264	   shared-process
    0	    69	 12568	   gpu-process
    0	   243	 12604	   window (● readme.txt - Assignment4 - Visual Studio Code)
    0	    11	  7584	     watcherService 
    0	    10	  5988	       console-window-host (Windows internal process)
    0	   141	 12168	     extensionHost
    0	    40	  2752	       electron_node cssServerMain.js 
    0	    48	  2828	       electron_node electronForkStart.js tsserver.js 
    0	    34	  3008	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    33	  2900	       electron_node eslintServer.js 
    0	    10	  3812	       C:\tools\neovim\Neovim\bin\nvim.exe -u NONE -N --embed
    0	    10	  6076	         console-window-host (Windows internal process)
    0	    54	  4776	       electron_node htmlServerMain.js 
    0	    34	  7316	       electron_node tslintServer.js 
    0	    10	  8020	       C:\tools\neovim\Neovim\bin\nvim.exe -u NONE -N --embed
    0	    10	  2372	         console-window-host (Windows internal process)
    0	    75	  8500	       electron_node jsonServerMain.js 
    0	    71	 14308	       electron_node server.js 
    0	    10	 15996	       C:\tools\neovim\Neovim\bin\nvim.exe -u NONE -N --embed
    0	    10	  9536	         console-window-host (Windows internal process)
    0	    36	 14928	     searchService
    0	    74	 16376	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● readme.txt - Assignment4 - Visual Studio Code)
|    Folder (Assignment4): 5 files
|      File types: txt(2) rkt(2) pdf(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vsc-prolog|art|0.8.13
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-clock|Com|0.0.1
angular2-snippets|dan|1.0.19
vscode-markdownlint|Dav|0.14.1
jshint|dba|0.10.17
vscode-eslint|dba|1.4.8
xml|Dot|1.9.2
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.5.0
code-runner|for|0.9.3
vscode-javac|geo|0.0.47
githd|hui|1.1.3
angular2-switcher|inf|0.1.6
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|2.16.1
racket|kar|0.0.3
auto-comment-blocks|kev|1.0.1
code-beautifier|mic|2.0.3
Angular-BeastCode|Mik|6.0.3
theme-monokai-pro-vscode|mon|1.1.5
vscode-scss|mrm|0.6.2
python|ms-|2018.3.1
cpptools|ms-|0.16.1
debugger-for-chrome|msj|4.3.0
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.2.6
typescript-hero|rbb|2.3.1
java|red|0.21.0
vscode-icons|rob|7.22.0
autoimport|ste|1.5.3
ayu|tea|0.14.0
pdf|tom|0.2.0
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0
vim|vsc|0.11.3
gitblame|wad|2.4.1
vscode-todo-highlight|way|0.5.12
html-css-class-completion|Zig|1.17.1

(5 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by dbaeumer** [comment]
@sandy081 assigning to you since you worked on VIM for a while. Not sure if there is a better owner.

**Comment by sandy081** [comment]
Its @rebornix who owns VIM issues.

**Comment by rebornix** [comment]
You may want to follow https://github.com/VSCodeVim/Vim/issues/2021
