### ISSUE TITLE
Rendering breaks when resizing integrated terminal to a very large size

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#47162]
Issue Type: <b>Bug</b>

Whenever I resize my terminal to a large size, rendering breaks. I'm using a 4K monitor, and since I believe the terminal is using WebGL internally, it _could be_ that it's failing to acquire textures of a certain size (e.g. 2048x2048) due to an implementation limit in Chromium.

![image](https://user-images.githubusercontent.com/418473/38274455-3655340a-3765-11e8-8640-18165e9f4867.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|31.92GB (24.39GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.5
better-toml|bun|0.3.2
vscode-togglecodelens|cml|1.0.3
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
vsc-material-theme|Equ|1.5.1
vscode-icon-theme|jtl|1.6.1
mads|mir|0.0.5
vscode-scss|mrm|0.6.2
PowerShell|ms-|1.6.0
vscode-code-outline|pat|0.0.13
rust|rus|0.4.1
shader|sle|1.1.2
vscode-autohotkey|sle|0.2.2
json-schema-validator|tbe|0.1.0
JavaScriptSnippets|xab|1.5.0

(6 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
@coreh do you know of such a limit? I don't see this when stretched across 2 1080p monitors (~3840px wide) and maximized.

Related: https://github.com/Microsoft/vscode/issues/36913

**Comment by Tyriar** [comment]
Also could you try with our Electron 2 build? See https://github.com/Microsoft/vscode/issues/36913#issuecomment-378683014

**Comment by coreh** [comment]
Nevermind, it looks like the Chromium texture limits are [way higher than I thought](https://user-images.githubusercontent.com/418473/38324691-67022b64-3817-11e8-9f85-4ad65ccc2aa3.png).

Just tested with the Electron 2 exploration build, and can no longer reproduce the issue. Looks like that indeed fixes it! 🎉

**Comment by Tyriar** [comment]
@coreh so glad to hear that, I get notifications constantly about these perf issues on Windows 😄

I'll merge this issue into #36913

**Comment by Tyriar** [comment]
@coreh I recommend jumping on the Insiders build if you haven't yet, it should be on Electron 2 within the next few days. https://code.visualstudio.com/insiders
