### ISSUE TITLE
OS X: why does 'Open Recent' menu show separator line?

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4716]
- VSCode latest alpha
- OS Version: OX 10.11.4

![2016-03-28 19-40-42](https://cloud.githubusercontent.com/assets/1898161/14084878/3054f32e-f51d-11e5-9246-e955cb198a07.png)

**Comment by bpasero** [comment]
@weinand we do this already on other platforms: to distinguish opened files from opened folders. The motivation for the change came from https://github.com/Microsoft/vscode/issues/4167

One issue I do see is that you now have duplicates in the list, so I have to take care of the fact that previously we had files and folders in the list below the separator and now files below and folders above. 

See for example how it looks for me now:

![image](https://cloud.githubusercontent.com/assets/900690/14098786/a10c4f56-f57f-11e5-9aff-270b89553087.png)
