### ISSUE TITLE
Uninstall/Install has no effect for extensions without restarting VS Code before the Install

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#47164]
1.21.1/Windows.

1. Change some file in the extension folder (some extensions have data files that are modifiable for users, that aren't exposed through more user-friendly settings, such as the C/C++ `.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/msvc.json` file).
2. Do an Uninstall/(Reload)/Install/(Reload) to try to restore the extension to an unmodified state.

Bug: It doesn't work and there's no warning that no uninstall/install actually took place. The workaround is to close/restart VS Code after the uninstall, but this wasn't necessary previously.

I suspect this is a regression to fix the problem when an extension is using the files still when an uninstall occurs, I would assume the correct fix would be to delete the folder after the extension has deactivated or the reload occurs.

**Comment by roblourens** [comment]
I don't think this is new, we can't delete an extension when another window is still using it.

**Comment by sean-mcmanus** [comment]
I only have 1 VS Code instance/window open and no workspace is even open. I'm pretty sure this is a regression. I see a .obsolete file get created but the extension folder is not removed after the uninstall (until VS Code is restarted).

**Comment by sandy081** [comment]
@sean-mcmanus Previously we try to delete the extensions on uninstall. But this is causing to multiple issues as the extension might be still active in other windows. Hence, we delete the extension only after VS Code restart. Even if there is one instance of VS Code window is open some extensions might be running the processes and hold onto some of the files in the extension. Hence we do not want to delete then.

I think the right fix here is when user installs it again, it should be delete and install.

**Comment by sandy081** [comment]
There will not be issues if newly installed is a different version. Then we will not delete the existing version because every version has different folders. So other windows will run with old version until they reload.

But, If newly installed is the same version as before, then deleting existing version might have an impact on other windows. So either Delete only if there is just one window or delete always. In either case, if delete fails, user has to be notified to restart VS Code to install.

**Comment by sean-mcmanus** [comment]
Yeah, delete on install or a notification that a restart is required would be fine if required -- the main issue was that I was relying on uninstall/install being clean for testing purposes and it wasn't, and other users have reported using uninstall/install to fix corrupt download/installs as well.

**Comment by sandy081** [comment]
@sean-mcmanus We have a command to re-install an extension for such corrupt cases which can be also used for testing too. `Developer: Reinstall Extension`.

If it is for testing / fixing purposes I would use the above command and not to go with any fixes unless it is needed for real purposes.

**Comment by sandy081** [comment]
@sean-mcmanus Can you please provide the real user case as requested above. Thanks.

**Comment by sean-mcmanus** [comment]
The use case is that we sometimes tell users special workarounds to modify our extensions' behavior via modifying msvc.json files next to our binary (e.g. to enable warnings, and may give undesirable results due to the experimental/unsupported nature of the features) -- a user who does this modification and then wants to revert back to the shipping version would normally try to do an uninstall/reinstall -- but then it unexpectedly doesn't have any effect. The Developer: Reinstall extension hits the previous issue in that it doesn't cause the currently running extension to exit, so it usually easier to just uninstall/restart/install, which is an acceptable workaround -- it's really just an issue with unexpected behavior. A "repair" button would be nice.

The 2nd user scenario, is when the extension's installation is corrupted due to a failed download/install of OS-specific components -- many users report to us that they previously used to uninstall/install to fix the issue, but that doesn't work if the uninstall never happens. Fortunately, I think we fixed our download/install code to not hit this anymore (or at least we haven't heard any recent complaints).

**Comment by sandy081** [comment]
Thanks for the reply. 

I see restart VS Code is necessary in the first case if other windows are hanging on to the extension. Second case is a trouble shooting case and Reinstall action was provided just for that.

I will wait for more reports with scenarios.
