### ISSUE TITLE
Add Java to "Tools and Languages" section of the welcome page

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode#47169]
![image](https://user-images.githubusercontent.com/16755094/38286245-f2cd9578-37f6-11e8-91ee-a57d77360f13.png)

Can we also add Java among other entries to improve awareness?

We have relatively complete Java support in VS Code with an extension portfolio that covers lots of things:
- [Java Language Support](https://marketplace.visualstudio.com/items?itemName=redhat.java)
- [Java Debugger](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug)
- [Java Test Runner - JUnit](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test#overview)
- [Maven for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test#overview)
- [Spring Boot Extension Pack](https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-boot-dev-pack)
- [Tomcat for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test#overview)

Java also deserves its place in that list.

**Comment by chrmarti** [comment]
Would be nice if the list could show more entries on a wide screen. Currently the number of entries is somewhat limited to display well on a not-so-wide screen.

**Comment by akaroml** [comment]
In VS Code, the default recommendation for java files is the [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack). The pack contains extensions to support everyday Java dev works.

When Java appears in welcome page, it can lead users to install the Java Extension Pack just like what the Python link does.
