### ISSUE TITLE
Add API for reading existing DebugConfigurations

### ISSUE THREAD

**Issue by stephtr** [Microsoft/vscode#47165]
At the moment when calling `vscode.debug.startDebugging` one has to either supply a full `DebugConfiguration` or the name of one registered in the launch.json file. However in my opinion it would be quite useful to have an API for getting an array of all debug configurations, maybe filtered by debug type, without having to deal with manually finding and parsing the launch.json file. One then would have the ability to start an existing debugging task based on its type.

**Comment by weinand** [comment]
You can access the debug configurations via the settings API.
We do not plan to add more API on top of this.
