### ISSUE TITLE
Show configured tasks in the "Tasks" menu

### ISSUE THREAD

**Issue by gulshan** [Microsoft/vscode#47172]
It will be very helpful if the configured tasks in `tasks.json` files are shown in the "Tasks" menu. Then users will be able to run a task from the menu by selection.

**Comment by alexr00** [comment]
Can you give an example? Is the request that tasks defined in tasks.json show up in the npm script explorer?

**Comment by gulshan** [comment]
When this request was made, there was a menu named "Tasks". It was renamed to "Terminal". The intent behind this request was, when there are some tasks defined in `tasks.json` file for some opened folder/project, it will be very natural to expect those tasks being available in the "Tasks" menu. Then these configured tasks would be dynamic menu items under the "Tasks" menu. Due to the name change to "Terminal", the intended situation is not that much natural now.

**Comment by alexr00** [comment]
Thank you for the background info. Closing since this isn't a natural flow now.
