### ISSUE TITLE
high cpu usage When adjust the system time slower

### ISSUE THREAD

**Issue by zuldee** [Microsoft/vscode#47177]
Issue Type: <b>Bug</b>

When vscode is opening,
if adjust the system time slower, vscode getting High CPU usage;
but if adjust the system time faster, it is fine;

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|Memory (System)|7.97GB (2.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
beautify|Hoo|1.3.0
proto|pet|0.0.2
JavaScriptSnippets|xab|1.5.0

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by zuldee** [comment]
it's simple，
1，open vscode
2，Adjust system time to the previous day

it is about 98% cpu usage

**Comment by dbaeumer** [comment]
@zuldee can you run code --status after doing this can paste the output here. Then we know which process starts to consume CPU cycles. Thanks.

**Comment by dbaeumer** [comment]
Was able to reproduce. Here a screen shot of the processes:

<img width="1808" alt="capture" src="https://user-images.githubusercontent.com/1931590/38316276-9f48a508-382a-11e8-8897-af290b863058.png">

Might be a file watching issue

@bpasero starting with you since the renderer is on top.

**Comment by sandy081** [comment]
Is this a dup of #42752?

**Comment by joaomoreno** [comment]
Sounds a lot like it.
