### ISSUE TITLE
python 模块不能使用啦

### ISSUE THREAD

**Issue by zhaojinxi** [Microsoft/vscode#47173]
Issue Type: <b>Bug</b>

python 模块不能使用啦

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|31.96GB (27.60GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1

</details>
Reproduces only with extensions

**Comment by dbaeumer** [comment]
@zhaojinxi can you please provide a description in English.

**Comment by yume-chan** [comment]
Translation:

> **Python module stops working**
>
> (same as title)

I don't know what "Python module** means, maybe he is referring to the Python extension.

是 Python 扩展不能用了吗？能详细描述一下你的问题吗？你在进行什么操作的时候，出现了什么不符合你预期的情况？期间有显示任何错误信息吗？
