### ISSUE TITLE
text mouse cursor missing, 4k external monitor, mac os high sierra (2560x1440)

### ISSUE THREAD

**Issue by retrojorgen** [Microsoft/vscode#47179]
Issue Type: <b>Bug</b>

Occurs on Mac Os high sierra. Was not an issue before upgrade from Sierra.
The cursor is visible in the application (files tree etc..) but disappears as soon as I hover over the actual editor.

The cursor is visible when I select "Looks like 1920x1080" or "looks like 3840x2160" in system preferences -> display -> scaled, but is not visible in either of the options in between.

The ironic part is that if I use quicktime to screen record, the cursor is there in the recording.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
vscode-color|ans|0.4.5
vscode-eslint|dba|1.4.8
json-tools|eri|1.0.2
vscode-language-babel|mgm|0.0.14
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.3.0
vscode-import-cost|wix|2.6.2

</details>
Reproduces without extensions

**Comment by florin-machedon** [comment]
can be reproduced on Atom, iTerm, VSCode on dark themes.
like retrojorgen said:
"The cursor is visible when I select "Looks like 1920x1080" or "looks like 3840x2160" in system preferences -> display -> scaled, but is not visible in either of the options in between."

**Comment by dbaeumer** [comment]
Might be an Electron problem then. @bpasero

**Comment by JochemWarmenhoven** [comment]
@bpasero, i just tested your new build, and the issue is still the same

**Comment by weinand** [comment]
@dbaeumer I've never experienced this issue on my 5k display.

**Comment by florin-machedon** [comment]
increasing the cursor size a tiny bit fixed the issue for me, if it's normal size then it disappears.
go to System Preferences > Accessibility > Display > Cursor size.

**Comment by retrojorgen** [comment]
@florin-machedon works :)

**Comment by alexandrudima** [comment]
Let's merge discussions with #47076
