### ISSUE TITLE
光标位置

### ISSUE THREAD

**Issue by sht819175141** [Microsoft/vscode#47176]
Issue Type: <b>Bug</b>

我鼠标选中一个位置，输入结束2秒左右过后，鼠标自动跑到html标签的结尾处，不能够继续向下编写代码，总是自行跳转至html标签的结尾处，回车以后，也存在相同问题

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Memory (System)|15.93GB (7.03GB free)|
|Process Argv|D:\软件工具\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.9
markdown-emoji|bie|0.0.7
solargraph|cas|0.13.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.27
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.2.0
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.30
vsc-material-theme|Equ|1.5.1
prettier-vscode|esb|1.2.2
php-intellisense|fel|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
terminal|for|0.0.10
vscode-javac|geo|0.0.47
vscode-firefox-debug|hbe|1.1.3
live-html-previewer|hdg|0.3.0
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
emoji-code|idl|0.7.0
path-autocomplete|ion|1.9.0
autofilename|Jer|0.1.3
docthis|joe|0.6.0
vscode-colorize|kam|0.6.18
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|2.0.3
HTMLHint|mka|0.4.0
vscode-filesize|mkx|2.0.0
vscode-autoprefixer|mrm|2.1.2
vscode-scss|mrm|0.6.2
mssql|ms-|1.3.0
python|ms-|2018.3.1
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.3.0
syncing|non|1.5.3
emoji|Per|0.0.3
vscode-versionlens|pfl|0.20.0
material-icon-theme|PKi|3.2.6
view-in-browser|qin|0.0.5
Ruby|reb|0.17.0
java|red|0.21.0
vscode-icons|rob|7.22.0
sass-indented|rob|1.4.8
code-settings-sync|Sha|2.9.0
html5-boilerplate|sid|1.0.1
vscode-java-debug|vsc|0.8.0
vscode-maven|vsc|0.6.0
JavaScriptSnippets|xab|1.5.0
vue-style-beautify|xig|0.1.9

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by MaleDong** [comment]
Would you mind offering a video to re-produce it?

**Comment by yume-chan** [comment]
Translation:

> **Cursor position**
>
> 2 seconds after I typed something, the cursor jumps to the end of file automatically, makes it unusable. It also happens after I pressed the <kbd>Enter</kbd> key.

Seems another bad formatter issue.

似乎又是一个格式化扩展的问题。

**Comment by alexandrudima** [comment]
@sht819175141 You have 62 installed extensions and one of them is causing this. Can you please figure out which extension is causing this. You can narrow your search down by using `F1 > Developer: Show Running Extensions`. Please check on what file type this occurs and what extensions target that file type. Once you identify (by selectively disabling) and narrowing down the possible extension, please create an issue straight against that extension...
