### ISSUE TITLE
Wrong code colors with specific template and macro code

### ISSUE THREAD

**Issue by maxco2** [Microsoft/vscode#47170]
Issue Type: <b>Bug</b>
![wrongcolors](https://user-images.githubusercontent.com/11772699/38286855-27d02b34-37fa-11e8-98d1-58216665c5b4.png)

```
#pragma once

#include <type_traits>

#define IsPointDef(...) \
	template<> \
	struct IsPoint<__VA_ARGS__> \
		{\
		static const bool isPoint = true;\
				}

#define ArrayBasedPointDef(T) \
	IsPointDef(T); \
	template<> \
	struct IsArrayBasedPoint<T>:public std::true_type \
		{};



#define XYBasedPointDef(T) \
	IsPointDef(T); \
	template<> \
	struct IsXYBasedPoint<T>:public std::true_type \
{};

#define TypeTAndUIsPoint \
	template<typename T, typename U, class = typename std::enable_if<IsPoint<T>::isPoint>::type, class = typename std::enable_if<IsPoint<U>::isPoint>::type>

namespace Navigation
{
	namespace Utils
	{
		template<typename T>
		struct IsPoint
		{
			static const bool isPoint = false;
		};

		template<typename T>
		struct IsArrayBasedPoint
		{
			static const bool value = false;
		};

		template<typename T>
		struct IsXYBasedPoint
		{
			static const bool value = false;
		};

	}
}

```
VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.17133

Extensions: none
Reproduces without extensions

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#267

**Comment by maxco2** [comment]
@aeschli
I tested Atom v1.25.1 which use the same textmate grammar as vscode(v1.21/1.22). Everything works fine.
![atom](https://user-images.githubusercontent.com/11772699/38462518-0d0151ba-3b1b-11e8-821e-40781fd14037.png)

This bug can only reproduce on vscode.
I also checked c++/c.cson( v0.59.3) and cpp/c.tmLanguage.json(vscode v1.22) briefly.
Did‘t find crucial difference.
