### ISSUE TITLE
我想使用SVN但是在咱们的，不知如何使用

### ISSUE THREAD

**Issue by liushuai512** [Microsoft/vscode#47175]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.我已经下载好了插件，但是不知道如何使用，（webstorm中双击文件夹就可以了）
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment]
Translation:

> **I want to use SVN but I don't know how**
>
> I have downloaded the extension, but don't know how to use (in WebStorm I just double-click on a folder)

Which extension does you download? It should provide information about the opened folder in the Source Control panel.

你下载了哪个扩展？在 Code 中打开文件夹后应该会在“版本控制”侧边栏里提供相关的文件修改信息
