### ISSUE TITLE
Perf: improve performance of filtering large folders in the explorer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#47187]
The explorer filter can be very expensive because for each file we need to resolve the list of actual sibling names. This results in quadratic complexity and we should revisit this to not always have to do this.

Code pointer: https://github.com/Microsoft/vscode/blob/a8f068a5400b6b7907fa9763615e13e6de7f195d/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L691

**Comment by isidorn** [comment]
We were focused on grid this milestone, next week I am on vacation, this is not for endgame -> June

**Comment by bpasero** [comment]
@isidorn I looked a bit into this, some findings:
* the tree is calling the `isVisible` method twice (filed https://github.com/Microsoft/vscode/issues/51601)
* we could save a lot of time if the stat was keeping a Map of children names for explorer items that are folders, would that be possible? We could even compute that lazily when needed and I could wire this all the way through to the glob matching to make this fast
* something for the future maybe: @joaomoreno any chance that the tree could not call isVisible for each item even if not visible in the viewport? That of course has the biggest perf impact

**Comment by joaomoreno** [comment]
@bpasero No chance, because that affects the tree's content height.

**Comment by isidorn** [comment]
@bpasero yes we could add a lazy map of children directories to the `ExplorerItem`.
Would you expect something like 
`item.isChildDirectory(name: string): boolean`
Which when first called constructs the map and then all subsequent calls return in O(1)?

**Comment by bpasero** [comment]
@isidorn the glob library actually needs to have a way to know if a specific filename is part of a folder, so currently what it is doing is `string[].indexOf(filename)`

**Comment by isidorn** [comment]
> Specific filename is part of a folder

then why not `stat.parent.getChild(fileName)` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L729)

I guess I am missing something, feel free to drop my desk to discuss.

**Comment by bpasero** [comment]
@isidorn that looks very promising indeed, I could try that. The only worry I have is that it calls `toLowerCase` each time for the file name it seems.

**Comment by isidorn** [comment]
@bpasero great, please try that. Yes it calls `toLowerCase` each time on non-linux platforms. There is nothing better we can do than to call `toLowerCase`

**Comment by bpasero** [comment]
The `glob.ts` code is so insanely complicated and tweaked that I am not able to make a change where `siblingsFn?: () => string[] | TPromise<string[]> `could change to something like `hasSinlingsFn?: (name: string) => boolean | TPromise<boolean>` without knowing what is going on, so I will have to defer this to @chrmarti who I believe added these optimizations to glob.ts to see if it is feasable to make this change. The idea is to just provide this function instead of having to compute the siblings. Clients can still decide to behave as we did before by doing an `indexOf` check in the array of sibling names, but others like the explorer can implement a potentially faster check by going directly to the model.

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/53994

**Comment by bpasero** [comment]
**Verify**
* files.exclude setting works as before for the explorer
* also test with complex expressions like `"**/*.js": { "when": "$(basename).ts" }`
