### ISSUE TITLE
Breakpoints unreliable with .ts files

### ISSUE THREAD

**Issue by notenoughneon** [Microsoft/vscode#4718]
- VSCode Version: 0.10.11
- OS Version: OS X 10.10.5
- Typescript: 1.8.9
- Node: 5.9.0

Possibly related to #2157, #1384

After upgrading typescript from 1.6 to 1.8.9, and node from 0.12 to 5.9.0, I noticed breakpoints no longer working and other strange behavior.
* Debugger fails to stop at breakpoints in .ts file
* Debugger shows .js file instead of .ts when attaching to node --debug-brk
* Double entries for same breakpoint appear in "breakpoints" pane

Its been difficult to produce a good test case for this bug due to nondeterministic behavior. I've seen symptoms appear or disappear after:
* Commenting/uncommenting parts of the code and recompiling
* Copying the .ts file to an identical copy and debugging

Possible causes that have been ruled out:
* "outDir" setting (separate outDir or not makes no difference)
* "typescript.tsdk" 1.8.9 mismatch (tried setting to installed version of typescript vs bundled 1.8.2)
* Code with promises or callbacks (issue was produced in case with only console.log())
* Breakpoint being on first line (breakpoints throughout entire code may fail)

Steps to Reproduce:

test.ts:
```typescript
import fs = require('fs');
var cb1 = function(err, stats) {
    console.log('break here 1');
};
fs.stat('.', cb1);

var cb2 = function() {
    console.log('break here 2');
}
setTimeout(cb2, 1000);
```

tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true
    }
}
```

launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "request": "attach",
            "type": "node",
            "port": 5858,
            "sourceMaps": true
        }
    ]
}
```

1. tsc
2. node --debug-brk test.js
3. Set breakpoints in ts file and attach to process
4. Commenting/uncommenting the top or bottom section and retrying causes the breakpoint issue to manifest eventually

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/vscode-node-debug#58
