### ISSUE TITLE
Cannot escape strings properly in launch.json's "args" list.

### ISSUE THREAD

**Issue by bandzaw** [Microsoft/vscode#47189]
- VSCode Version: 1.21.1
- OS Version: Ubuntu 16.04.1
- C/C++ extension Version: 0.16.1

In order to debug my application I added a launch configuration (version 0.2.0) of type cppdbg. In it, I specify my command line argument that is to be passed to my program I'm about to debug.

The problem I have is that the argument that is received within the program is not the expected command line argument that I specified in the launch.json file.

In launch.json I specify the command line argument (a string within a string) as:
`"args": ["{\"key\":42}"]`

That is, I wan't to pass a simple JSON object with its key as a string, which I therefore escape within quotation marks. But what I receive in my program is: "{key:42}", that is, a key without its quotation marks, which is not what I want. I also tried using single quotation marks: "args": ["{'key':42}"] but the end result was the same.

Of course, passing the same argument directly from the command line (not using vscode/debug) as:
`./myapp "{\"key\":42}"`
works as expected, i.e. within myapp I receive my key as a string within the string: "{"key":42}".

I have tried to find information how I otherwise should specify my string within a string as command line arguments in launch.json but have not found anything useful, I therefore file this as a bug.

**Comment by weinand** [comment]
This works fine when (mis-)using node-debugging with the "echo" command:

![2018-04-04_15-04-16](https://user-images.githubusercontent.com/1898161/38309140-7b4ae7a8-3819-11e8-89cc-32fe0b9e1f83.png)
