### ISSUE TITLE
Workbench couldn't find message for key chrome.targetTypes.description

### ISSUE THREAD

**Issue by talamaska** [Microsoft/vscode#47186]
I'm getting this warning in the debug console 
```
Couldn't find message for
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2842 Couldn't find message for key chrome.targetTypes.description.
```

- VSCode Version: 1.21.1
- OS Version: Windows 10

Steps to Reproduce:

1. just lanch the vs code

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
If the issue does not occur when all extensions are disabled, then it is not a bug with VS Code but some extension. Please file against that extension (maybe the Debugger for Chrome).

**Comment by talamaska** [comment]
@weinand it's disabled , the issue still appears
