### ISSUE TITLE
Run command in terminal on project startup.

### ISSUE THREAD

**Issue by raksa** [Microsoft/vscode#47191]
Hi, every time I open my project folder I need to go to terminal and type `npm start` to start testing.

If possible VSCode should have option in config file to run the custom command after project folder opened.

**Comment by Tyriar** [comment]
This extension should cover your needs https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

**Comment by raksa** [comment]
i got it, thanks
