### ISSUE TITLE
Terminal window freezes VS Code when scrolled

### ISSUE THREAD

**Issue by dkent600** [Microsoft/vscode#47196]
Issue Type: <b>Bug</b>

1. run a command that produces some output, 100 lines or so.  I'm not sure whether any particular type of output matters, but I've seen it happen with a simple "dir" command.  It is possible it is most likely to happen when the output contains colored text.
2. increase the vertical height of the terminal window to try and view lines that have scrolled off the top.
3. or, try scrolling up using the vertical scrollbar.

RESULT:
VS code totally hangs for anywhere from a few seconds to a minute or two.

I've tried with the regular Windows console shell and with PowerShell, same results.

I'm not sure when this started, but for sure it has been happening for several months-worth of versions of VSCode.

It happens pretty much every time when the text is colored.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|31.86GB (20.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\dkent\Documents\Projects\GitHub\DAOStack\Vanille|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.2
aurelia|Aur|1.0.3
Aurelia|beh|1.2.2
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
auto-rename-tag|for|0.0.15
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
solidity|Jua|0.0.37
markdown-shortcuts|mdi|0.8.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
typescript-javascript-grammar|ms-|0.0.38
debugger-for-chrome|msj|4.3.0

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
Tracked in https://github.com/Microsoft/vscode/issues/36913

**Comment by dkent600** [comment]
When running as `code --disable-gpu` the problem for me goes away.  I have a 4K monitor.

**Comment by Tyriar** [comment]
@dkent600 great, seems like the same problem then. I'm hoping it'll be fixed in 1.23
