### ISSUE TITLE
Create headless "VS Code Server" that can be connected to to allow editing remote code within it's environment

### ISSUE THREAD

**Issue by joslarson** [Microsoft/vscode#47199]
When ssh-ing into a server using Vim (or Emacs) to edit code, Vim users can copy their configurations there and get the same linting and code completion experience they have locally. With VS Code the best I can do is mount an external drive or use something like rmate with the rafaelmaiolla.remote-vscode extension. But with those solutions, I loose access to the environment the code is running in.

With the introduction of Visual Studio Live Share it looks to me like we've got a lot of the pieces in place to answer this use case for VS Code users in a much bigger way.

I have no idea how this would end up being integrated, but right now I'm imagining ssh-ing into my server, running `code .` in my project root with my environment activated, and getting back a Live Share link to open the project in a local VS Code window with access to all the goodness VS Code provides.

And the best part: I'll finally have something to say to my Vim friends when they say "yeah but I can use Vim over ssh" 🎉

**Comment by roblourens** [comment]
This is something we are thinking about, there is an issue you can follow here https://github.com/Microsoft/vscode/issues/29194
