### ISSUE TITLE
Dragging folder out of file explorer sidebar does not allow it to be copied/moved/aliased

### ISSUE THREAD

**Issue by gingerbeardman** [Microsoft/vscode#47190]
- VSCode Version: 1.21.1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Drag folder out of file explorer sidebar
2. Hold <kbd>option</kbd>
3. Drop on Desktop

Expected:
- Should copy/move/alias folder depending on which modifier keys you press and hold during the drag

Actual:
- Zero byte file with same name as folder is created

Notes:
- Files can be copied this way, but cannot be moved or aliased 

Does this issue occur when all extensions are disabled?: Yes

**Comment by gingerbeardman** [comment]
If so that's a real problem 😔

**Comment by bpasero** [comment]
@isidorn yes you are right

**Comment by gingerbeardman** [comment]
Yet another waste of users time. You really are turning a good relationship bad here
