### ISSUE TITLE
No suggestions in Debug console

### ISSUE THREAD

**Issue by dps999** [Microsoft/vscode#47194]
- VSCode Version: 1.21.1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. use Unity
2. While debugging never saw a suggestion in the console

Does this issue occur when all extensions are disabled?: Yes/No
I can't disable Unity debug extension

**Comment by weinand** [comment]
Suggestions in the debug console must come from the debug extension you are using. Please file this issue against Unity.
