### ISSUE TITLE
Rename symbol opens same file by alternate path (multi-folder project with symlink)

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#47198]
- VSCode Version:1.21.1
- OS Version:Win 10

Steps to Reproduce:

1.  Create multi-folder project 
2. In 2nd folder, create symlink to a "shared" directory in 1st folder
3. In 2nd folder settings, use "files.exclude" to exclude symlink directory
4. Open file from shared directory in 1st folder 
5. Rename a symbol in the file
6. Note that a 2nd instance of the file is opened via the 2nd folder path

Other comments
* sometimes symbol rename modifies multiple files.  I'll open new ticket if I can reproduce

![rename](https://user-images.githubusercontent.com/3818866/38317962-e4cbad8c-37f3-11e8-981a-d7f5251b300c.gif)

**Comment by mjbvz** [comment]
Possibly #40682 

Can you please right click on the two version of that file and use `copy path` to compare their paths. Are the two paths the same? Are there any casing differences?

**Comment by mfrost66** [comment]
Yes, the question was already answered in the OP.  If you can't reproduce,
let me know.

The core issue is you are searching folders excluded via "files.excudes".
I have no idea why a function param rename triggers a multi-file
search/replace.

**Comment by mjbvz** [comment]
Please share the results of `copy path`

**Comment by mfrost66** [comment]
I guess that's one approach to closing tickets.  

If a video capture of the bug and reproduction details aren't enough to inspire you to investigate it, I don't know how else to help

Happy Slacking!

**Comment by mjbvz** [comment]
Please share the results of `copy path`, as in: run `copy path` on both files and paste up text that is copied
