### ISSUE TITLE
Find in folder should have same alt shortcuts for options as find in file

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4719]
Steps to Reproduce:

1. <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd>
2. <kbd>alt</kbd>+<kbd>c</kbd>, <kbd>alt</kbd>+<kbd>w</kbd> and <kbd>alt</kbd>+<kbd>r</kbd> should toggle "Match case", "Match whole word" and "Use regular expressions" respectively.

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
@alexandrudima can you point me to where you setup these keybindings?

**Comment by alexandrudima** [comment]
Sure, here I do it for the find widget: `src\vs\editor\contrib\find\common\findController.ts`

But if I understand correctly, this issue is about the Find in Files, so not sure how that helps you.

**Comment by bpasero** [comment]
@alexandrudima just as input what key-codes to use, thanks.

**Comment by Tyriar** [comment]
Thanks @sandy081, I've been waiting for this :smile:

**Comment by bpasero** [comment]
Verified on Mac the keys are working when pressed with Cmd+key pressed.
