### ISSUE TITLE
Warn before quitting main window when a terminal is running

### ISSUE THREAD

**Issue by cig0** [Microsoft/vscode#47203]
- VSCode Version: Version 1.21.1 (1.21.1) 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Close the last editor or close main window
2. If there's an open terminal running any tasks, that terminal will be closed leading to a potential corruption of the tasks being executed inside.

Does this issue occur when all extensions are disabled?: Yes

A way to workaround this issue would be to run a screen multiplexer inside, but sometimes it isn't an optimal solution.

**Comment by Tyriar** [comment]
Right now you can set `"terminal.integrated.confirmOnExit": true`. Currently this will warn on *any* terminal existing, not a terminal with sub-processes as you might expect (tracked in https://github.com/Microsoft/vscode/issues/23808)

**Comment by cig0** [comment]
Thank you!
