### ISSUE TITLE
No Error on use of undeclared variables

### ISSUE THREAD

**Issue by bushra376** [Microsoft/vscode#47202]
Issue Type: <b>Bug</b>

// Actual Code gives No error on use of undeclared variable "nums" in the return statement
function doSomething(num){
     return nums + 1;
}

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (6.35GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
This is by-design for javascript since `nums` may be a global

Try enable strict checks in your js to have this reported as an error: https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files
