### ISSUE TITLE
jsonValidation support yml and other

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#47207]
For example: 

``.travis.yml``
``appveyor.yml``

[schemastore](http://schemastore.org) have a lot of schema file. including ``json`` and ``yml``.

How about supporting it with the built-in feature?

Just need to write a script to download schema files and set it to config

**Comment by aeschli** [comment]
There are already extensions out there that provide yaml support including validation using schemas:
https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml
