### ISSUE TITLE
Cannot run extension using vscode 1.21 build

### ISSUE THREAD

**Issue by Divni** [Microsoft/vscode#47205]
Steps to Reproduce:

1. Build vscode-oss
2. Create an extension as per the instructions here: https://code.visualstudio.com/docs/extensions/example-hello-world
3. Run the extension using .build/electron/code-oss /path/to/ext

Expected:

code-oss will run with the extension installed

Actual:

Following error:
```
App threw an error during load
Error: Cannot find module 'vscode'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/divni/Projects/vscode/.build/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/divni/Projects/vscode-ext-hello/out/extension.js:5:16)
    at Object.<anonymous> (/home/divni/Projects/vscode-ext-hello/out/extension.js:28:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```

**Comment by weinand** [comment]
@Divni what exactly are you trying to do?
Your steps from above have nothing to do with debugging.

Why do you build vscode-oss?
This is not needed if you just want to debug an extension.

**Comment by Divni** [comment]
Renamed, I had confused it with debugging because F5 runs the debugging interface.

I am experimenting with modifying vscode-oss API's and trying to test those modified API's with an extension.

**Comment by weinand** [comment]
`.build/electron/code-oss /path/to/ext` does not run an extension.
Run `code-oss --help` to learn about the options you can use with extensions.

Or just copy the hello world extension folder to your  `~/.vscode-oss-dev/extensions` folder

**Comment by Divni** [comment]
As per the instructions here:

https://code.visualstudio.com/docs/extensions/example-hello-world#_running-your-extension

When you press F5 it tells me to run the command above. Note when I run this command using the latest stable release of vscode it does work (so `code /path/to/ext`).

**Comment by weinand** [comment]
`code /path/to/ext` does not **run** the extension but it **opens** the extension project in VS Code.

**Comment by Divni** [comment]
It seems I miss-diagnosed the issue. Your suggestion gets to the root of it, I can now run the extension using a custom vscode build. Thank you @weinand !

**Comment by weinand** [comment]
@bpasero how could we simplify EH debugging when running out of source? Every now and then someone runs into the issue of the missing path to VS Code.

**Comment by bpasero** [comment]
Maybe @joaomoreno has an idea

**Comment by joaomoreno** [comment]
There doesn't seem to be a good idea for this. Maybe just have two debug targets?

**Comment by weinand** [comment]
We could supply the additional argument behind the scenes (e.g. in the debugger) but for that we would have to know that we are running out of source.
