### ISSUE TITLE
Files are not in same folder being opened in new window

### ISSUE THREAD

**Issue by SaitDev** [Microsoft/vscode#47215]
- VSCode Version: 1.21.1
- OS Version: Window 10 1709

Steps to Reproduce:

1. Start VS Code, open a folder
2. Open a file from another folder with File Explorer (by double click or right click Open With Code)
3. VS Code opens the file in a new window and the parent folder of the file

Expected behaviour: 
`window.openFilesInNewWindow` is `off` I expected the file should be opened in the last actived window instead of creating new window

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@SaitDev we fixed that as far as I know, can you try the same scenario with our insiders build (you will have to configure this setting again for that build): https://code.visualstudio.com/insiders/

**Comment by SaitDev** [comment]
Works as expected with insider build
