### ISSUE TITLE
Jumping when returning to window

### ISSUE THREAD

**Issue by SingHo2016** [Microsoft/vscode#47214]
If I am searching for string "A" in VS Code, then navigate to a different app like Chrome and search for string "B", upon re-focusing on VS Code, I will lose my place in the file because VS Code will jump to the first instance of string "B"

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.0
csharp|ms-|1.14.0
sublime-keybindings|ms-|3.0.3
vscode-input-sequence|tom|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
You can disable this by setting `"editor.find.globalFindClipboard": false`
