### ISSUE TITLE
Shorter Folder name replaced with ellipsis

### ISSUE THREAD

**Issue by eazrael** [Microsoft/vscode#47212]
Not a big bug, just some weirdness. In the explorer tab the name of folder gets partially replaced by an ellipsis, while longer names on the same level are not abbreviated.  meta-oe gets replaced with meta-... while  meta-multimedia or meta-filesystems will not be shortened. 

![vsc-explorer](https://user-images.githubusercontent.com/7374919/38335642-4d159bda-385f-11e8-8a07-bdef91ebae37.png)

- VSCode Version: 
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:30.761Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Ubuntu 16.04 LTS with XFCE.

Steps to Reproduce:

1. Honestly: No idea, have a rather deep directory hierarchy?

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this.
Do you also see this behavior with the latest vscode insiders https://code.visualstudio.com/insiders/
