### ISSUE TITLE
Folder title shouldn't be converted to all uppercase

### ISSUE THREAD

**Issue by JPJofre** [Microsoft/vscode#47213]
- VSCode Version: 1.21.1 (1.21.1)
- OS Version: macOS 10.12.6 (16G1212)

In IX/UX and Mac OS, casing is important.
By displaying the folder name all in uppercase in the editor explorer is wrong.
<img width="803" alt="screen shot 2018-04-04 at 2 30 29 pm" src="https://user-images.githubusercontent.com/1279045/38336007-3aae2d80-3815-11e8-847a-7ece11ae8be9.png">

**Comment by bpasero** [comment]
Closing as designed, we decided to show any view title in uppercase. This is consistent with views across the UI.
