### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AniruddhPurohit** [Microsoft/vscode#47216]
A good intellisense is expected for all kind of JavaSript files.
Git Panel should be added like Atom which can create new github repository right from the editor.
ESLint window is also very good in Atom that shows linting errors in interactive way.

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
