### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by honeyjills** [Microsoft/vscode#47218]
Issue Type: <b>Bug</b>

I am not able to access the extensions. It is showing "Unknown error occurred".
Kindly help.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 2801)|
|Load (avg)|4, 556, 724|
|Memory (System)|15.55GB (6.56GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces only with extensions

**Comment by roblourens** [comment]
Could you show a screenshot, and tell us exactly what you do when you see the error?
