### ISSUE TITLE
Add glTF extension to list of recommended extensions

### ISSUE THREAD

**Issue by emackey** [Microsoft/vscode#47211]
When a user opens a `*.gltf` or `*.glb` file, can VSCode automatically recommend the [glTF extension](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode)?  It appears to do this for several other file types.

/cc https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/100

**Comment by ramya-rao-a** [comment]
Opening a gltf file results in the below notification which then shows the gltf extension

![image](https://user-images.githubusercontent.com/16890566/45390872-c1453580-b5d5-11e8-9040-edcaf00d851c.png)

As for the glb file, I am guessing that any project using this file would also use gltf files. And the above notification for the latter should do the job.
