### ISSUE TITLE
Add code portal feature

### ISSUE THREAD

**Issue by calebh** [Microsoft/vscode#47210]
Feature request:

Add code portals which allow inline editing of code spanning multiple files in a single window. The code portal concept was created by Alexander Breckel and Matthias Tichy (so credit goes to them), although it does bare some similarities to code peeking and code bubbles. Here are some demo videos:
https://www.youtube.com/watch?v=okvoj2DXOg8
https://www.youtube.com/watch?v=NQ5h2Ibw6ck

I am unsure whether or not VS Code has the capabilities in place to make such an extension.

**Comment by roblourens** [comment]
This sounds similar to what we do with "Peek Definition" and "Find All References" and sort of related to what the `"debug.inlineValues"` setting enables.
