### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sayemon10** [Microsoft/vscode#47217]
**Inline Editor**
Can we have the ability of writing CSS in .css file in .html file via a _short-command._
I know it's _kinda_ tricky, but it takes time to find out the _proper_ **css-tree** of an _element_ when we are coding a **deadline** project..

But hope, cause it's **_Productivity_** Feature, we will have it soon 🙂

**Comment by aeschli** [comment]
We are aware of this request. We have #27892 for this.
