### ISSUE TITLE
Clean changes dialog box is non-modal on Linux

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4722]
- VSCode Version: 0.10.12-alpha
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Initialize a git repo or clone an existing one
2. Modify a file
3. Go to Git tab and Clean changes

Actual:
Clicking clean more than once brings up more than one 'Are you sure' dialog. 
![linuxcleanchanges](https://cloud.githubusercontent.com/assets/12900364/14089306/292e7b30-f4e9-11e5-9bc8-960f9c57fa1e.png)

Expected:
In Windows, only one dialog box is shown and clicking again just redirects to the already open one.

**Comment by Tyriar** [comment]
To rephrase: The dialog is not modal on Ubuntu like on Windows. Reproduced.

**Comment by Tyriar** [comment]
Upstream issue:

- https://github.com/atom/electron/issues/2566
- https://code.google.com/p/chromium/issues/detail?id=286441

**Comment by vsccarl** [comment]
@Tyriar Looks like some other changes fixed the modal issue. But now if you click more than once, the dialog will only show one at a time, but will continue to pop up how ever many times you click clean regardless of choosing clean or cancel.

**Comment by Tyriar** [comment]
@vsccarl sounds fixed to me, it's typically not worth adding the state to avoid clicking multiple times like that imo.
