### ISSUE TITLE
How to use vscode debug cocos2d-lua ?

### ISSUE THREAD

**Issue by cSingleboy** [Microsoft/vscode#47221]
I create a project with cocos2d-x(language: lua), build with Visual Studio 2015, then generate x.exe;
now, i want to use vscode to debug lua by x.exe;
how to config launch.json of vscode ?
////////////////////////////////////////////////////////////////////////////////////////////
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "launch process",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": true,
            "runtimeExecutable": "${workspaceRoot}/../simulator/win32/CocosLuaTest4.exe",
            "runtimeArgs": "-workdir ${workspaceRoot}/../",
            "program": "${workspaceRoot}/main.lua",
            "cwd": "${workspaceRoot}/../",
            "console": "utf8"
        }
}
////////////////////////////////////////////////////////////////////////////////////////////
then, launch by Ctrl + F5, is OK;
but, launch by F5, is error:  Debug adapter terminated unexpectedly;

**Comment by dbaeumer** [comment]
@cSingleboy can you please provide the description / title in English.
