### ISSUE TITLE
Debug jumps to terminal screen instead of debug since update 

### ISSUE THREAD

**Issue by SjoerdHoekstra** [Microsoft/vscode#47227]
Issue Type: <b>Bug</b>

Since the update every time i press debug the lower screen jumps to terminal instead of debug console. What can I do about this?  Because I find it much more conveniant to have this on the debug screen. This has been since the update since a week or so. 

Thanks for the help! 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|Memory (System)|7.91GB (2.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1

</details>
Reproduces only with extensions

**Comment by weinand** [comment]
I assume that your problem occurs for Python. Please file this issue against the Python extension.

**Comment by Kongsea** [comment]
Yes, I encountered the same problem.
Please check and fix it.
And please be careful to update vscode.

**Comment by Kongsea** [comment]
Yes, it occurs for Python.
