### ISSUE TITLE
Settings: a wild comma appears!

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#47228]
Have these settings:

```json
{
    "editor.formatOnSave": true,
    "files.autoSave": "afterDelay",
    "git.autofetch": false
}
```

Then type this:

```json
{
    "editor.formatOnSave": true,
    "files.autoSave": "afterDelay",
    "":
    "git.autofetch": false
}
```

Then this happens automatically:

```json
{
    "editor.formatOnSave": true,
    "files.autoSave": "afterDelay",
    "":
    "git.autofetch",: false
}
```

![kapture 2018-04-05 at 10 59 15](https://user-images.githubusercontent.com/22350/38356623-7e6ba8ee-38c0-11e8-97c9-df6d9194aa1d.gif)

**Comment by aeschli** [comment]
@roblourens  That's from the autoFixSettingsJSON save action

**Comment by roblourens** [comment]
Solution: don't type that...

**Comment by joaomoreno** [comment]
@roblourens You mean workaround? I was simply typing JSON...

**Comment by roblourens** [comment]
Yes, workaround. I think the best fix is to detect this case specifically. I can look for a colon following the "missing comma" parse error. Or assume that it's rare to put a string value on a different line from its key and don't add the comma in that case.

**Comment by joaomoreno** [comment]
Yeah I think some heuristics like those are the way forward.
