### ISSUE TITLE
Opening a new folder generates a new window.

### ISSUE THREAD

**Issue by sstaub** [Microsoft/vscode#47229]
Issue Type: <b>Bug</b>

When I open a new window (File / New Window) and then I open a 'folder' (File / Open..) there is a new window with folder content exactly over the 'new' window.
This doesn't happens when I open a single file.
Opening a folder should not generate a new window.

VS Code version: Code - Insiders 1.22.0-insider (6b4d53cdab8bcae1eaaa4934d93c077319b573db, 2018-04-04T13:45:40.906Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
file-templates|brp|1.2.0
doxdocgen|csc|0.3.1
gitlens|eam|8.2.0
CppSnippets|har|0.0.13
cortex-debug|mar|0.1.18
vscode-todo-parser|min|1.9.1
cpptools|ms-|0.16.1
vscode-code-outline|pat|0.0.13
platformio-ide|pla|0.14.0
vscode-icons|rob|7.22.0
vscode-todo-highlight|way|0.5.12
debug|web|0.22.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Have you set the `"window.openFoldersInNewWindow"` setting /

**Comment by sstaub** [comment]
Thank you, however it was set 'on'.
