### ISSUE TITLE
Inline Update Feature Request

### ISSUE THREAD

**Issue by aligoren** [Microsoft/vscode#47220]
- OS Version: Ubuntu 17.04

Hi there! I'm using Visual Studio Code on Ubuntu. Everything is great. But I hate to update VSCode. Because I have to download VSCode again in every update.

Couldn't you add a feature to inline update?

I mean it could be like below. (Sorry for this bad sketch. But this is my color scheme). If you're using Telegram Desktop application you know what I'm saying. For example, when I click on Update Code button. VSCode will restart to update itself. 

![image](https://user-images.githubusercontent.com/4205423/38348315-bed914e6-38a9-11e8-991e-369edba6ad32.png)

I already know it could update with the system update. But If you add the inline update, update operations will be easier.

**Comment by Tyriar** [comment]
There are various issues already tracking similar improvements: https://github.com/Microsoft/vscode/issues/5458, https://github.com/Microsoft/vscode/issues/43671, https://github.com/Microsoft/vscode/issues/21651
