### ISSUE TITLE
Markdown Scroll Sync Problem

### ISSUE THREAD

**Issue by datfinesoul** [Microsoft/vscode#47223]
Issue Type: <b>Bug</b>

Markdown scroll sync seems to consistently in any markdown file I load, just get stuck at the bottom of the preview screen.  The last few paragraphs show.  Scrolling inside the markdown preview, properly syncs back to the markdown file, but scrolling inside the marklardown file, does not properly reflect inside the Preview.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.80GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by mjbvz** [comment]
Can you please share the source of a markdown file that has this problem

**Comment by datfinesoul** [comment]
Every larger markdown file has that issue for me.  You can use https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md as an example, it has the problem as well for me.

**Comment by mjbvz** [comment]
I can't reproduce this with this example file or with much larger ones. How are you scrolling?
