### ISSUE TITLE
Commit Amend destroys Signed-off-by (and potentially other fields) in commit message

### ISSUE THREAD

**Issue by guw** [Microsoft/vscode#47224]
- VSCode Version: 1.21.1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Do a **Commit All (Signed Off)**
2. Do a **Commit All (Amend)**

On step 2 the commit message is collapsed into a single line. This is wrong. Any line breaks must be preserved because the the `Signed-of-by` field (as well as any other) needs to be separated from the commit message text by an empty line.

**Comment by guw** [comment]
Might be the same issue as #40295 (depending on the fix there)

**Comment by joaomoreno** [comment]
Definitely!
