### ISSUE TITLE
Out of box extension search/installation on mac OS fails

### ISSUE THREAD

**Issue by prasanthj** [Microsoft/vscode#47222]
Issue Type: <b>Bug</b>

Version 1.21.1 (1.21.1)
79b44aa704ce542d8ca4a3cc44cfca566e7720f1

Downloaded the current stable release of visual code on mac OS and am unable to see any extensions in the marketplace. All I am getting is a popup that says "An unknown error occurred. Please consult the log for more details." when I tried searching anything on the marketplace. This also happens when I click on popup that recommends to install extension (go lang extension for example). 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (1.54GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by sandy081** [comment]
@prasanthj Can you open the logs and see what is there in it. You can see logs in the output panel. Interesting would be Current window logs.

**Comment by prasanthj** [comment]
This is no longer an issue. The cause of this issue is related to https://twitter.com/prasanth_j/status/964213017587064832 where only chrome browser was able to connect to internet but none of the other browsers/applications can. Although it would be good to show the error in the popup that it's not able to connect to internet. Closing this is as not an issue.
