### ISSUE TITLE
Feature Request: "Pin" Terminal with alert if close

### ISSUE THREAD

**Issue by reggi** [Microsoft/vscode#47236]
I'd love some way to "Pin" a terminal just as chrome has a way to "Pin" a tab. If you close the tab that is pinned accidentally it will alert / message the user to prevent closing processes that shouldn't be closed.

I'd also love a way to name a given terminal so I can better differentiate different processes running.

**Comment by Tyriar** [comment]
There is already a rename terminal command (F1, "rename"). Also with an alert there is a setting confirmOnExit which will do this for all terminals, we eventually want this to show the dialog only when the shell process has a sub-process https://github.com/Microsoft/vscode/issues/23808
