### ISSUE TITLE
File not found error when drag and drop from a zip file

### ISSUE THREAD

**Issue by ysnjzl** [Microsoft/vscode#47232]
- VSCode Version: 1.21.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open a zip file
2. Drag and a drop a file from the zip to the VSCode window
3. Unable to open 'setup.xml': File not found (file:///c:/Users/YELGUZ~1/AppData/Local/Temp/7zE8FA66FD2/setup.xml).

=> The folder 7zE8FA66FD2 
![new issue microsoftvscode - google chrome](https://user-images.githubusercontent.com/20207644/38357690-93bc002e-38c3-11e8-8259-172c6e0ae358.png)
doesn't exist !

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
@ysnjzl does it help if you configure `"workbench.editor.closeOnFileDelete": false`?

**Comment by ysnjzl** [comment]
Hi,
No it does not solve the issue.
Please find the reproduction's GIF attached.
Thanks & Best regards
![reproduce-issue](https://user-images.githubusercontent.com/20207644/38407588-5a187c3c-397a-11e8-94b8-690e16027cf7.gif)

**Comment by bpasero** [comment]
@ysnjzl I suspect that the zip program is not fast enough providing this file when you drag and drop. I suggest you file an issue to them.

**Comment by ysnjzl** [comment]
@bpasero 
Hi,
I am using 7zip as a default program, and I tried also with winrar and I have the same issue.
Please note that I am a new user of VsCode and I don't have this issue with : 
- SublimeText
- Notepadd++
- Atom
So my guess, it has nothing to do with the zip program, as it is working for the other editors...

Hope is clarifies,
Thanks & Best regards.
