### ISSUE TITLE
Request: mouse wheel scroll sensitivity setting for the explorer

### ISSUE THREAD

**Issue by Otrebus** [Microsoft/vscode#47230]
Issue Type: <b>Feature Request</b>

The existing editor.mouseWheelScrollSensitivity setting doesn't affect the mouse wheel scrolling speed for the explorer, so a separate setting like explorer.mouseWheelScrollSensitivity would be nice.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
Duplicate of #37727
