### ISSUE TITLE
[themes] add peekViewEditor.matchHighlightBorder

### ISSUE THREAD

**Issue by mbenkmann** [Microsoft/vscode#47233]
- VSCode Version: 1.21.1
- OS Version: Linux

This should have been part of #43761 but was missed:
When Peek Definition is used on an a variable, the border around the identifier is not affected by the new colors introduced with #43761. Even worse when Peek Definition is used on a function, the whole function body has the border which really impairs readability. See this screenshot:

![http://www.winterdrache.de/data/peekdefinition.jpg](http://www.winterdrache.de/data/peekdefinition.jpg)

**Comment by aeschli** [comment]
The screenshot shows a problem with the language service returning a result range that goes over multiple lines. It should only be the range of a references symbol such as a name.

**Comment by aeschli** [comment]
Added new color `peekViewEditor.matchHighlightBorder`
