### ISSUE TITLE
Show tooltips for labels that get truncated

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4723]
- VSCode Version:0.10.12-alpha
- OS Version: WIndows10

Steps to Reproduce:
1. Launch app and open any folder which has long name.
2. Adjust editor view area so that text under explorer should be truncated with ...
3. Mouse hove on folder name in explorer window,

Actual: No tooltip is displaying.
![image](https://cloud.githubusercontent.com/assets/17735796/14091461/48336124-f4f5-11e5-8d9c-1ef9284a6612.png)

Expected: User should be able to see full name when hover over on folder or file truncated with ellipsis. Similar to visual studio.
![image](https://cloud.githubusercontent.com/assets/17735796/14091310/607c189e-f4f4-11e5-9562-2c8a07b87edf.png)

**Comment by bpasero** [comment]
I think this is a general issue with any label that gets truncated.

**Comment by Tyriar** [comment]
To work around the ugliness of doing this only when truncated, it looks like atom just adds `title` all the time.
