### ISSUE TITLE
Allow to run multiple instances as admin

### ISSUE THREAD

**Issue by Legends** [Microsoft/vscode#47237]
When I click on my task bar shortcut for VsCode it opens in admin mode (I've configured it under properties).
Now if I want multiple other instances of VsCode to open in admin mode, how to accomplish this?
Because `right-click --> new window` will not start it in admin mode!

**Comment by bpasero** [comment]
@Legends are you saying no window opens or that window is actually not in admin mode?

**Comment by Legends** [comment]
It does not start in admin mode when clicking on "New Window".

But now I get this:

![image](https://user-images.githubusercontent.com/966368/38405566-ca43a702-3970-11e8-9e6d-32ab197bdbac.png)

And why should I close the other instance?

**Comment by bpasero** [comment]
@Legends got it, this is a known issue. Things work fine if you do File > New Window from the one instance. This issue only shows up when you run a new instance outside of VS Code.

//cc @joaomoreno

**Comment by Legends** [comment]
ah yes, just tried it, thank for the info!
