### ISSUE TITLE
Typing library in Python causing formatting / intellisense fail

### ISSUE THREAD

**Issue by cal58** [Microsoft/vscode#47245]
Issue Type: <b>Bug</b>

Using Any, Dict, List or Tuple from the typing library removes syntax highlighting and intellisense from my code.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|Memory (System)|15.93GB (6.22GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.14.1
code-runner|for|0.9.3
vscode-codemetrics|kis|1.15.0
MagicPython|mag|1.0.12
python|ms-|2018.3.1
vscode-ai|ms-|0.1.7
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
team|ms-|1.122.0
vscode-docker|Pet|0.0.26
code-settings-sync|Sha|2.9.0
python|tht|0.2.3

</details>
Reproduces only with extensions

**Comment by roblourens** [comment]
Can you provide a code sample?

**Comment by cal58** [comment]
Sure.
Code sample: 
`from typing import Any, Dict, List, Tuple

class Foo(object):

    @property
    def bar(self) -> int:
        return 1

    @property
    def baz(self) -> None:
        return

    def hello_world(self):
        print("Hello world")
        return -1

    def broken_hello(self) -> int:
        print("Hello world")
        this_is_not_a_method()
        return -1
    `

Attached a screenshot of the lack of syntax highlighting (or error!)
![capture](https://user-images.githubusercontent.com/7880348/38486652-8dcbda8a-3bd5-11e8-997b-33fda8c8933b.PNG)

**Comment by aeschli** [comment]
This issue was moved to MagicStack/MagicPython#131
