### ISSUE TITLE
[folding] Closing fold not being shown when folding

### ISSUE THREAD

**Issue by etiennejcharles** [Microsoft/vscode#47240]
When I fold I like to see my last character, but in visual studio code insiders I can't :(
It works in Visual Studio stable version. (Version 1.21.1)

![example](https://user-images.githubusercontent.com/2872476/38370180-7c1b028c-38b7-11e8-94dd-788cbcb48887.gif)

- VSCode Version: Version 1.22.0-insider (1.22.0-insider)
- OS Version: Mac OS HIGH Sierra 10.13.3

Steps to Reproduce:

1. Open Visual Studio Code Insiders.
2. Set language to javascript. 
3. Paste some javascript code.
4. Try to fold some code

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by aeschli** [comment]
@mjbvz I wonder if we should disable the syntax aware folding again for the stable rebuild. There will many duplicates of this issue and we don't want tell everybody to turn off the experimental folding

**Comment by ywang04** [comment]
The same issue for jsx codes in React.
