### ISSUE TITLE
Intellisense stops returning anything in js project

### ISSUE THREAD

**Issue by andreasgruenh** [Microsoft/vscode#47248]
- VSCode Version: 1.21.1
- OS Version: Win 10 pro

Steps to Reproduce:

1. Initiate a create-react-app project (I cannot reproduce the error in a blank project)
2. Add a jsconfig.json with the content: `{}`
3. Open src/App.js
4. Hover and Intellisense (triggered by ctrl + space) should work
5. Create a new file "src/x.js"
6. Intellisense should still work
7. Type `import React from 'react';`
8. Test if intellisense is still working (if not, delete the file and go back to step 5 and use another filename)

After looping 3-6 times, the error occurs and Intellisense and hover information are broken and will only come back when the tsserver is restarted.

Does this issue occur when all extensions are disabled?: Yes

I uploaded the log when this occured here: https://gist.github.com/andreasgruenh/95dfe15dd23d3dfdb547db088199fdbd

Here is a gif of the reproduction: https://gfycat.com/LavishMasculineDuckbillplatypus
The Window has been reloaded directly before the start of the gif and the bug occurs after the 4th file has been created.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23183

**Comment by byteskw** [comment]
me to, im using react native for my vscode, after 2 minutes - 10 minutes always infinite loading my intellisense vscode,

please fix this
