### ISSUE TITLE
Auto close curly brackets for placeholders in template literals JS/TS

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#47244]
Issue Type: <b>Feature Request</b>

```javascript
let str = `$|`;
```

1. Type `{` where the cursor is.
2. No closing bracket

Not sure if it's a duplicate of #25314. This one is about template literal (\`), already typed `$` and, after that, brackets.

**Comment by mjbvz** [comment]
Duplicate of #25314
