### ISSUE TITLE
Visual Studio won't format my HTML code any more.

### ISSUE THREAD

**Issue by webmaestro** [Microsoft/vscode#47246]
Visual Studio's Format Selection also doesn't work.

Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Windows 10 Pro

Steps to Reproduce:

1. View HTML and/or JS document
2. Try to format code using Ctrl+K, Ctrl+F

Does this issue occur when all extensions are disabled?: I think so... In 15 minutes of searching the interweb can't tell if extensions are turned off?

Although it was *difficult* to figure out how to run VS w/o extensions. It's possible one of my HTML extensions gets in the way if they're not OFF?

FEATURE REQUEST(s):
- Have a common method for turning temporarily off Visual Studio Extensions on Startup (e.g., hold 'Shift' key while starting?)
- Update 'About' box to indicate whether or not Extensions are on or off
- Execute one shortcut (e.g., Ctrl+Shift+F or Ctrl+Alt+F or Ctrl+Win+F) instead of two?
- BONUS: add the shortcut to a menu (probably the Edit menu?), w the corresponding 'Format Code' Shortcut highlighted on the right so I don't have to visit Stackoverflow to figure out how to format code?
- add a page describing how to launch Visual Studio Code w/o extensions.
- Change the BAR color to indicate SAFE MODE or EXTENSIONS OFF.

https://docs.microsoft.com/en-us/vsts/marketplace/how-to/uninstall-disable-extensions-tfs?view=vsts
- Don't change the method of temporarily turning off Extensions from one version to the next

Can you ping me when this is fixed and/or explain what I need to do to fix it?

**Comment by roblourens** [comment]
To launch with extensions disabled, you just need to start with the --disable-extensions flag. That link is for vsts, not vscode.

When they are disabled, they will all show as disabled in the extension viewlet: 

![image](https://user-images.githubusercontent.com/323878/38383913-96caeab0-38c2-11e8-97a9-c6925461097e.png)
