### ISSUE TITLE
"Select all occurrances" doesn't work with keyboard shortcuts

### ISSUE THREAD

**Issue by Linxflasher** [Microsoft/vscode#47242]
Hi everyone,

With latest great updates to VS code I'm no longer able to "select all occurances" command with the keyboard shortcut "Ctrl + Shift + L".

I do a lot of HTML + CSS stuff and use this shortcut rather often.

In my current version of VS code this shortcut doesn't work. I have it assigned in my keyboard shortcuts preferences. It's also visible in the top menu -

 "Selection > Select all occurances"

![1](https://user-images.githubusercontent.com/5371882/38373041-eb6be520-38f8-11e8-8a4d-f5b3ea17b0f5.jpg)

When I press "Ctrl + Shift + L", nothing happens:

![2](https://user-images.githubusercontent.com/5371882/38373137-309f39da-38f9-11e8-80b7-5ab0e5f30a46.jpg)

If I perform command with "Ctrl + Shift + P" or go to top menu "Select > Select all occurrances", everything works fine:

![3](https://user-images.githubusercontent.com/5371882/38373260-82637c90-38f9-11e8-8c91-eb16b0ccd8ff.jpg)

I'm using:

Windows 10
VS Code version 1.21.1 x64

Has anyone faced the same problem and how to solve it?

**Comment by roblourens** [comment]
Most likely there is another keybinding taking its place, possibly from an extension.

- Can you try by starting with --disable-extensions?
- You can also open the keybindings editor and search "ctrl+shift+l" to see if there's a conflict
