### ISSUE TITLE
[Linux] Showing duplicate theme items for Dark+ and Light+

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4724]
- VSCode Version: 0.10.12-alpha
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Open themes menu

Actual:
Showing duplicate options for Dark+ and Light+ and there is no difference between them.
![linuxdupetheme](https://cloud.githubusercontent.com/assets/12900364/14091692/91d30b44-f4f6-11e5-88dc-a3a86aff80c9.png)

**Comment by Tyriar** [comment]
Does it happen after restarting and/or reinstalling vscode?

**Comment by vsccarl** [comment]
Restarting VS Code and restarting the machine don't seem to fix it. Downloading a new copy and running that instance does not repro. I'm not sure the steps to reproduce since I've been using that instance for a while.

**Comment by pflannery** [comment]
@vsccarl looks like the older default theme folder is still in the extensions folder. 
Have a look for `{App-Install-Path}/resources/app/extensions/theme-colorful-defaults`. 
If it is in there then move the `theme-colorful-defaults` folder out and check to see if the duplicates are gone.

**Comment by Tyriar** [comment]
Closing off as it would probably fix itself during an update.
