### ISSUE TITLE
Format Document Ignore String

### ISSUE THREAD

**Issue by mathamarante** [Microsoft/vscode#47241]
How ignore string in Format Document( Shift + Alt + F  ) ?

**Comment by roblourens** [comment]
I don't understand what you're asking, please be specific and give an example

**Comment by mathamarante** [comment]
Something like this:

before Shift + Alt + F:
`
var string = 
                        "<li>" +
                            "<div></div>" +
                        "</li>";

`

after Shift + Alt + F:
`
var string =
                "<li>" +
                "<div></div>" +
                "</li>";
`
There is some way to ignore string in Format Document( Shift + Alt + F ) ?

**Comment by mjbvz** [comment]
Those are multiple strings. The built-in formatter has no way to know you are writing html string and want the inner tag body indented. I'm not sure if any formatters offer this option actually

Try writing a template string instead or structuring your code another way if you need this indentation
