### ISSUE TITLE
debug.internalConsoleOptions "neverOpen" is ignored.

### ISSUE THREAD

**Issue by chriseaton** [Microsoft/vscode#47249]
- VSCode Version: 1.21.1
- OS Version: Fedora 27 Linux 4.15.10-300.fc27.x86_64

Steps to Reproduce: 

1. Open user settings.
2. Set: "debug.internalConsoleOptions": "**neverOpen**",
3. Expect the debug console to **not** be switched to when debugging starts. But instead it switches.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
What debugger are you using?

**Comment by chriseaton** [comment]
.NET Core 2 project
Build Engine version 15.6.82.30579 for .NET Core

**Comment by chriseaton** [comment]
Nevermind. I see there's an internalConsoleOptions in the launch.json that was overriding the value. My fault.
