### ISSUE TITLE
"Check for update" button disappeared

### ISSUE THREAD

**Issue by AKachan0v** [Microsoft/vscode#47254]
Issue Type: <b>Bug</b>

Hi guys,

It looks like that for this moment VSCode supports 2 updating scenarious:
1. Fully automated
Requirement: the "update.channel" is set to "default"
- VSCode automatically checks for updates, download and install them.
- VSCode renders "Check for Updates" button (not sure why since it does automatic check)

2. Fully manual
Requirement: the "update.channel" is set to "none"
- VSCode doesn't do automatic check for updates
- VSCode hides "Check for Updates" button, which means that in case user want to update he/she required to go to VSCode website, download and install new VSCode

My scenario is that I don't want automatic updates, but I would like to easy update VSCode in case I need it, so if you wouldn't remove the button in the second scenario it will make users life much easier

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

Reproduces without extensions

**Comment by joaomoreno** [comment]
We don't allow to customize whether updates are automatic or otherwise. Just whether they are enabled or otherwise.

In your very specific scenario, you can always switch `update.channel` to `default` and restart. You'll get an update. Then switch it back.

**Comment by Cirno9** [comment]
I have to update vscode via vpn. I think this button is necessary, or can you add a command? I notice that there is a check update command for extensions.

**Comment by mrmivo** [comment]
It isn't an unusual scenario that a user wants to manually check for updates (which is the function of the "Check for Updates" menu item), but doesn't want to allow the software to have automatic, unscheduled access to the net and download data regardless of what else the connection may be currently used for. Automatic updates and manual updates are not the same.

Could the "update.channel" setting gain a third option that only disables automatic downloading, but does still allow manual checking? (e.g.   "update.channel": "manual")
