### ISSUE TITLE
 Cannot read property 'contributes' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#47258]
Issue Id: <b>6d67ceef-538f-0a8c-754e-5359a90d0433</b><br /><br />*Versions* <br />- 1.21.1<br />-  9a199d77c82fcb82f39c68bb33c614af01c111ba<br />-  a903bd38fbe9006c076d218ff69fe1ee0160f815<br />-  b76a4a71434d6cdee69fa1d8bdc7533d09598d53<br />*Stack* <br />TypeError: Cannot read property 'contributes' of undefined<br />[/vs/workbench/parts/preferences/electron-browser/preferencesSearch.ts#48:32](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/workbench/parts/preferences/electron-browser/preferencesSearch.ts#L48:32)<br />    at Array.filter (native)<br />[/vs/workbench/parts/preferences/electron-browser/preferencesSearch.ts#48:5 (onComplete)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/workbench/parts/preferences/electron-browser/preferencesSearch.ts#L48:5 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1183:0 (_notify)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#865:0 (enter)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L865:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#1081:0 (_run)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1081:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#1049:0 (onComplete)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1049:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1183:0 (_notify)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#865:0 (enter)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L865:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#1081:0](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1081:0)<br />

**Comment by ramya-rao-a** [comment]
@sandy081 I dont see how an extension would not have a manifest, but a user in #47200 has the same error

**Comment by sandy081** [comment]
@ramya-rao-a Since we have a user reported related issue.. let's ask user how many extensions are there in the extensions folder and in the shared process log we can see how many extensions are scanned. We can also add logs to see which extension is causing this.

**Comment by ramya-rao-a** [comment]
@sandy081 #47200 got closed as the user cleared out .vscode/extensions and we now cannot know what extensions were installed.

**Comment by sandy081** [comment]
Not sure how we can get into this state. 

@roblourens I would leave it to you if you would like to put null checks or use telemetry.
