### ISSUE TITLE
[cpp] highlighting issue after #if

### ISSUE THREAD

**Issue by nebulaM** [Microsoft/vscode#47255]
- VSCode Version: 
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows 10, Version 1703

Steps to Reproduce:

Please see attached image.

1. Add conditional compilation(#if) to a function's input.
2. Observe that all lines after that have variables highlighted in red, because VS code thinks the bracket is not closed. 

Does this issue occur when all extensions are disabled?: No. The issue may be caused by extension(s) "One Dark Pro 2.13.4" and/or "C/C++ 0.16.1".

![vs_bug](https://user-images.githubusercontent.com/13920963/38389293-d3ce3f56-38d2-11e8-9fd2-95ee27c6ac63.PNG)

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#269
