### ISSUE TITLE
[c#] Syntax highlighter not recognizing strings

### ISSUE THREAD

**Issue by jamesqo** [Microsoft/vscode#4725]
- VSCode Version: 0.10.11
- OS Version: Windows 10.0.10586

The VSCode editor sometimes doesn't recognize strings in C# source files, leading it to highlight code as strings and other strings as code. Here's an example of what I mean:

![vscode-grammar](https://cloud.githubusercontent.com/assets/9159214/14094590/b8c3bd8c-f525-11e5-8ecb-9ddcc714256f.PNG)

The source for the repro can be found here:

https://github.com/dotnet/corefx/blob/b55b8085528d0199bd14fb417d3b764e643b8533/src/System.Runtime.Extensions/tests/System/Runtime/Versioning/FrameworkName.cs

Since GitHub seems to be choking on this as well, I'll also be opening an issue in Atom's [C# grammar repo](https://github.com/atom/language-csharp), but I thought it would be good to let you guys know.

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#134
