### ISSUE TITLE
Ruby wrong hightlighting 

### ISSUE THREAD

**Issue by KinIcy** [Microsoft/vscode#47261]
Issue Type: <b>Bug</b>

my code: https://pastebin.com/6pPea2gj
![image](https://user-images.githubusercontent.com/10891866/38394220-42af9fd0-38f3-11e8-920e-9745e89fbb0e.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|7.89GB (2.66GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Jason\My Games\RPGVX\Installers\Advanced Chest System v1.0\Data\Scripts.rvdata|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.14.1
vscode-eslint|dba|1.4.8
vetur|oct|0.11.7

</details>
Reproduces without extensions

**Comment by aeschli** [comment]
This issue was moved to textmate/ruby.tmbundle#117
