### ISSUE TITLE
Electron 2.0.x: Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by rwatts3** [Microsoft/vscode#47264]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by rwatts3** [comment]
Actually after checking the extension host log files, I was able to see that the last extension to attempt a start was the VS Live Share extension. After disabling the extension the errors go away. 

Please note this is specifically in reference to the insiders build. I'm not sure if this is the same effect on the production build.

**Comment by marvinhagemeister** [comment]
@rwatts3 Can confirm. Uninstalling the `VS Live Share` extension fixed it for me.

**Comment by IPyandy** [comment]
disabling VS Live Share also fixed, extension host would crash immediately upon VS Code Insider's starting up.

**Comment by bpasero** [comment]
@rwatts3 @marvinhagemeister @IPyandy are you using VSCode 1.23 insiders or the 1.22 release?

**Comment by bpasero** [comment]
I reverted the Electron update, let's continue over in https://github.com/electron/electron/issues/10905
