### ISSUE TITLE
Stuck in debug mode when getting error for prelaunch task.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4726]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:

1. Launch app and open any folder which has .ts, .less. and .JS files.
2. Make sure build tool Grunt should be configured for opened directory.
3. Verify Gruntfile.js should be placed in root directory or create manually.
4. configure tasks.json file from command palette for Grunt.
5. Verify task name in the generated tasks.json file. (in my case "build" and "test")
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "grunt",
	"isShellCommand": true,
	"args": ["--no-color"],
	"showOutput": "always",
	"tasks": [
		{
			"taskName": "build",
			"args": [],
			"isBuildCommand": true,
			"isWatching": false,
			"problemMatcher": [
				"$lessCompile",
				"$tsc",
				"$jshint"
			]
		},
		{
			"taskName": "test",
			"args": [],
			"isTestCommand": true
		}	
	]
}
6. Go to debug section and select Node option to generate launch.json.
7. Update launch.json property for "preLauchTask" and provide task name "build" or "test".
"preLaunchTask": "build",
8. Select launch option and start debugging.
9. Debugging started with error message "The prelaunchTask "Build" terminated with exit code 99".
![image](https://cloud.githubusercontent.com/assets/17735796/14094949/e604b618-f50f-11e5-9e2d-9afcc4897de9.png)

Actual:
1. On the error pop-up user is getting two options "Continue" and "Close" when user clicks on "Close" then debugging should be stopped (This is same behavior like in visual studio when we get build error it asks for continue or close) but I observed when user clicks on close then the error pop-up closed but application remain in debugging mode forever.
2. When user tries to terminate the debug session by clicking on Stop button then nothing is happening.
![image](https://cloud.githubusercontent.com/assets/17735796/14094824/c72715a2-f50e-11e5-9ea8-e34cfad258c3.png)

**Comment by isidorn** [comment]
Good catch.

To verify, have a prelaunchTask that produces an error. Try to debug, after an error is detected close action should stop debugging, continue action should start debugging.
