### ISSUE TITLE
Annoying beep from keystroke

### ISSUE THREAD

**Issue by brandondrew** [Microsoft/vscode#47260]
- VSCode Version: Version 1.21.0 (1.21.0) 9a199d77c82fcb82f39c68bb33c614af01c111ba
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Open VS Code
2. Put cursor in editor
3. Type ⌃⌘↓

I have this keystroke bound to `editor.action.moveLinesDownAction` (as seen below) but that is not necessary to make the annoying beep—it's only the reason that I'm experiencing it.   Even if I remove the configuration below, it still beeps at me, and even if I disable all extensions.  And the keystroke is not bound to anything else, nor does VS Code give any indication (a menu lighting up) that there is any built-in command with that binding hard-coded.

```
  {
    "key": "ctrl+cmd+down",
    "command": "editor.action.moveLinesDownAction",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "alt+down",
    "command": "-editor.action.moveLinesDownAction",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "ctrl+cmd+up",
    "command": "editor.action.moveLinesUpAction",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "alt+up",
    "command": "-editor.action.moveLinesUpAction",
    "when": "editorTextFocus && !editorReadonly"
  },
```

Does this issue occur when all extensions are disabled?: Yes
Even with all extensions disabled, I still experience this behavior.

**Comment by roblourens** [comment]
This is an issue upstream, https://github.com/Microsoft/vscode/issues/44070
