### ISSUE TITLE
Simple, out of the box C++ compilation - READY to GO - so close, it's within reach!

### ISSUE THREAD

**Issue by gerudobomb** [Microsoft/vscode#47266]
Issue Type: <b>Feature Request</b>

I'd love to be able to write a 'main()' function and hit run. That would be a dream. Please, without needing to edit 45 'include' paths, make this a realtiy! You've got an AWESOME thing going here with VS Code, so much potential! If I were on the development team, I'd hit this one out of the park - this feature right here.

Make it 'easy as pie', 'so easy a 5 year old could do it', 'type "int main() {} - and go!" and you'll own earth.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
This isn't something we'd include out of the box, you should look at C++ extensions for C++ support.
