### ISSUE TITLE
Leaving code open and suspending Linux Mint should not give weird UI glitch

### ISSUE THREAD

**Issue by E1337Kat** [Microsoft/vscode#47267]
Issue Type: <b>Bug</b>

## Issue ##
I am running Linux Mint on a laptop. After I logged in from waking up from suspension, code was open and had weird glitches.

## Repro ##

1. Open vs-code 
2. Close laptop lid (put computer to sleep/suspend)
3. After the PC is fully suspended, Open the lid (wake up computer)
4. Login to account
5. Notice the graphical glitch in the integrated shell area.

## Results ##
Graphical glitch affecting the integrated shell

## Expected ##
No graphical glitches.

## Notes ## 
I first noticed this with all extensions enabled, but it was slightly different. [Screenshots](https://imgur.com/a/a6z7E) show both with and without extensions. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2900)|
|Load (avg)|1, 1, 1|
|Memory (System)|11.60GB (7.88GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
solargraph|cas|0.14.1
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
tslint|eg2|1.0.28
code-runner|for|0.9.3
ruby-rubocop|mis|0.7.0
python|ms-|2018.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.3.0
Ruby|reb|0.17.0
java|red|0.22.0
vscode-icons|rob|7.22.0
vscode-spotify|shy|2.4.0
vscode-apielements|vnc|0.6.7

</details>
Reproduces without extensions

**Comment by Tyriar** [comment]
This is a bug in Chromium where canvas textures get corrupted when you sleep the computer. Duplicate https://github.com/Microsoft/vscode/issues/30292
