### ISSUE TITLE
Color theme is change

### ISSUE THREAD

**Issue by jinmarcus** [Microsoft/vscode#47269]
- VSCode Version: 1.21.1

User settings 
Change the setting to true
```
{
    "javascript.implicitProjectConfig.experimentalDecorators": true
  }
```

Color theme is change

I'm use  Dark+ (default dark)

It's a strange color.

Please check:

http://wx4.sinaimg.cn/large/82c9caaegy1fq2mtui8w5j20ip0ist9s.jpg

**Comment by mjbvz** [comment]
Are you sure those are the repo steps? That setting has nothing to do with syntax coloring

**Comment by jinmarcus** [comment]
@mjbvz 
I don't know

I deleted the C:\Users\Administrator\.vscode
and
The configuration changed to normal

**Comment by mjbvz** [comment]
Ok, sounds like your settings file got corrupted somehow

Please let me know if this issue happens again and the exact sequence of steps that caused it
