### ISSUE TITLE
Can't use the Integrated Terminal

### ISSUE THREAD

**Issue by youyinnn** [Microsoft/vscode#47273]
see at pic
![image](https://user-images.githubusercontent.com/23525754/38400049-b1629e9a-3980-11e8-9482-726165b068f8.png)

the cursor was wrong and i can't type anything on it

i've try launch vscode with administrator mode, and it still won't work for me

- VSCode Version:  1.21.1
- OS Version: win10

Steps to Reproduce:

1. click the terminal icon on the statu bar
2. trying to type something 

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
> click the terminal icon on the statu bar

There is no terminal icon in the status bar, you must be using an extension to add it. What extension?

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/43169
