### ISSUE TITLE
Node LogPoints shows up as the VM source in debug console

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#47274]
Per conversation https://github.com/Microsoft/vscode-node-debug/pull/174

Node LogPoints shows up as a virtual source, and not a real source from where the LogPoint is set.

Example:

<img width="1179" alt="screen shot 2018-04-05 at 7 20 29 pm" src="https://user-images.githubusercontent.com/173559/38400750-88501a5c-3906-11e8-94fb-d08204d9a946.png">

**Comment by roblourens** [comment]
The log event from Node contains the full stack, but the top frame is in an eval context. So I just have to identify a message from a logpoint and knock off the top frame.

I could do this by adding an extra argument to the end of the console.log that we send to the runtime with some identifiable string that identifies this log event as belonging to a logpoint. It's simple but the magic string would show up if you attach Chrome devtools at the same time. 

Or I could look at the stack and check whether it comes from a line that we have an active logpoint on.

**Comment by weinand** [comment]
Your approach works fine for the debug console but in the integrated terminal it shows this:

![2018-04-25_16-18-42](https://user-images.githubusercontent.com/1898161/39251808-72f58acc-48a4-11e8-85c4-f2dc595963fb.png)

**Comment by roblourens** [comment]
Dang... I'm worried that using special characters could cause weird issues somewhere. But it would be easier.

I could also use sourceURL on the script to tag it as ours.

**Comment by roblourens** [comment]
If you add a special comment to the end of an evaluated script, `//# sourceURL="myscript"` then it will be reported as having a url of `myscript`. F12 did this with all evaluated scripts so they could be filtered from the UI, I have an issue somewhere to do the same.

**Comment by auchenberg** [comment]
@roblourens Doesn't this change make all logpoints showup coming from the same file, and not the original?

**Comment by auchenberg** [comment]
@roblourens Roger
