### ISSUE TITLE
Organize imports in ES6 JSX removes React import

### ISSUE THREAD

**Issue by Mehemmed** [Microsoft/vscode#47287]
Issue Type: <b>Bug</b>

In ES6 file containing JSX markup press Shift+Alt+O, and VSCode will remove React as if it is not used.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|7.86GB (2.58GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.27
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
es7-react-js-snippets|dsz|1.3.3
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.16
csharp|ms-|1.14.0
node-debug2|ms-|1.19.2
debugger-for-chrome|msj|4.3.0
material-icon-theme|PKi|3.2.6
ayu|tea|0.14.0
vscode-react-native|vsm|0.6.6

</details>

**Comment by mjbvz** [comment]
Please share some example code. How are you importing react?

**Comment by Mehemmed** [comment]
As simple as:
import React from "react";

As you know this import is required in files where you are using JSX syntax. React should be in scope. But you are not actually using this React explicitly. I think this is a special case where this kind of import should be exluded from inspection by vscode import organizer.

**Comment by mjbvz** [comment]
@Mehemmed Is that the entire file contents? I only see the react import removed when there are no jsx elements in the file or when I use a different alias, such as `import Deact from "react"`

Also, do you have a `jsconfig.json`?

**Comment by Mehemmed** [comment]
Here is the full content of file:
`AppRouter.js`
`import React from "react";
import { Switch, Route, Redirect } from "react-router-dom";
import { defaultRoute } from "config";
import asyncComponent from "utils/AsyncFunc";

export default () => (
  <Switch>
    <Redirect exact from={`/`} to={`/${defaultRoute}`} />
    <Route
      exact
      path={`/recaps`}
      component={asyncComponent(() => import("views/Recap.List"))}
    />
    <Route
      exact
      path={`/recaps/create`}
      component={asyncComponent(() => import("views/Recap.Create"))}
    />
    <Route
      exact
      path={`/recaps/:id/edit`}
      component={asyncComponent(() => import("views/Recap.Edit"))}
    />

    <Route
      exact
      path={`/shippingOrders`}
      component={asyncComponent(() => import("views/ShippingOrder.List"))}
    />
    <Route
      exact
      path={`/shippingOrders/create`}
      component={asyncComponent(() => import("views/ShippingOrder.Create"))}
    />
    <Route
      exact
      path={`/shippingOrders/:id/edit`}
      component={asyncComponent(() => import("views/ShippingOrder.Edit"))}
    />

    <Route
      component={asyncComponent(() => import("views/Common/404"), false)}
    />
  </Switch>
);`

**Comment by Mehemmed** [comment]
Also, my `jsconfig.json`:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": ["*", "src/*"]
    }
  }
}
```

**Comment by mjbvz** [comment]
Try adding `"jsx": "react"` to your `jsconfig`:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "jsx": "react",
    "paths": {
      "*": ["*", "src/*"]
    }
  }
}
```

This helps vscode understand that `React` is implicitly referenced by the jsx elements in your file.

I agree the current behavior is confusing and have opened https://github.com/Microsoft/TypeScript/issues/23287 upstream to discuss how we can make this experience better
