### ISSUE TITLE
Possible to use .es6 file extension?

### ISSUE THREAD

**Issue by giannico** [Microsoft/vscode#4728]
- VSCode Version: 0.10.11
- OS Version: OSX 10.10

Is it possible to use the .es6 file extension, and still have the editor enable intellisense appropriately? For instance, I have some projects that use the ".es6" extension, and keywords like "module" have red lines under them, and the file isn't processed in the same way that a .js file is. Renaming the file to .js fixes the issues (but isn't always an option, due to internal project reasons).

**Comment by egamma** [comment]
In the latest  [insiders build](https://code.visualstudio.com/download?insiders=true) you can associate file extensions to languages and the association is persisted, pls see: https://code.visualstudio.com/download?insiders=true
