### ISSUE TITLE
The output error

### ISSUE THREAD

**Issue by smile-xy** [Microsoft/vscode#47295]
Issue Type: <b>Bug</b>

Automatic output error when the CSS property name is half input.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.86GB (10.75GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by smile-xy** [comment]
This is not an issue before this update.So I reinstalled the old version.

**Comment by roblourens** [comment]
Please give some details of the code and the error.

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
