### ISSUE TITLE
マウスポインタが後ろに隠れる

### ISSUE THREAD

**Issue by sml-tokuoka** [Microsoft/vscode#47294]
Issue Type: <b>Bug</b>

マウスの矢印が後ろに回ってしまうため、見えなくなりすごく使いにくいです。

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sml-tokuoka** [comment]
Mouse pointer hides behind the screen.

**Comment by roblourens** [comment]
I don't understand the problem. Can you include enough details for us to reproduce the issue?

**Comment by roblourens** [comment]
Can you give a screenshot to help explain the problem?

**Comment by EbXpJ6bp** [comment]
@sml-tokuoka 外部モニターにつないでるときに問題が起きましたか? もしそうなら macOS の問題かもしれません https://applech2.com/archives/20180406-mouse-cursor-disappear-after-macos-10-13-4-update.html (日本語リンク)

(Did you occur this issue on an external monitor? In this case, the problem may be upstream in macOS.)

similar https://github.com/Microsoft/vscode/issues/47076

**Comment by EbXpJ6bp** [comment]
@sml-tokuoka 外部モニターにつないでるときに問題が起きましたか? もしそうなら macOS の問題かもしれません https://applech2.com/archives/20180406-mouse-cursor-disappear-after-macos-10-13-4-update.html (日本語リンク)

(Did this issue occur on an external monitor? In this case, the problem may be upstream in macOS.)

similar https://github.com/Microsoft/vscode/issues/47076

**Comment by sml-tokuoka** [comment]
It came to be visible.
I was very sorry.

**Comment by roblourens** [comment]
Sorry @sml-tokuoka I don't understand
