### ISSUE TITLE
Batch Script syntax highlighting issues

### ISSUE THREAD

**Issue by Kroc** [Microsoft/vscode#47297]
Issue Type: <b>Bug</b>

There are a handful of highlighting issues with Windows Batch files:

- [ ] `ECHO:` is not recognised, when `ECHO.` is; `ECHO:` is faster as it does not do a file lookup! -- see: https://ss64.com/nt/echo.html

- [ ] The `OFF` in `ECHO OFF` is not highlighted

- [ ] The following code gets highlighting confused (the `"$...` seems to throw it off)
    
    ![vscode_batch_syntax](https://user-images.githubusercontent.com/142650/38409862-5b96b4ee-3983-11e8-8f80-7bdf130f0b8a.png)

- [ ] No space between `GOTO` and the label name does not highlight correctly; i.e. `GOTO:EOF`

- [ ] `CLS` keyword is not highlighted

- [ ] `EQU` / `NOT` and other comparison operators are not highlighted

- [ ] `IN` & `DO` are not highlighted

- [ ] command concatenator `&`, and the pipe operators `>`, `|` are not highlighted nor pipe numbers for redirection, e.g. `>NUL 2>&1` (a common way to suppress all output)

- [ ] error-suppressor `@` is not highlighted in any way; this needs to be highlighted when used with a command, but not within 'strings' (which may or may not be quoted, according to command used)

- [ ] `ENABLEEXTENSIONS` / `DISABLEDELAYEDEXPANSION` etc. not highlighted along with `SETLOCAL`

- [ ] Syntax break-down here: (looks like the quoted paren-escape failed to be noticed)

    ![vscode_batch_syntax2](https://user-images.githubusercontent.com/142650/38410563-35c6524a-3985-11e8-8117-58e0af6e328c.png)

---

Aside: What would be the best way to broach a discussion on using a PEG-based parser, rather than the regex-infused TextMate system for VSCode? Windows Batch files happen to be one of the best examples of extremely complex mode-like behaviour that would be easily and elegantly handled by a real state machine based approach using PEG/EBNF grammars. Grammar based parsing would also be readily shareable between language servers and other external software.

---

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

Extensions: none

**Comment by aeschli** [comment]
This issue was moved to mmims/language-batchfile#26

**Comment by mmims** [comment]
Fixes for these issues (https://github.com/mmims/language-batchfile/commit/6235c491be4dff49cd3966b50142874d7f79580a) are ready to be merged.
