### ISSUE TITLE
300,000 lines for bookmarks extension and no more

### ISSUE THREAD

**Issue by wolf-pro** [microsoft/vscode#47290]
- VSCode Version: 1.21.1
- OS Version: Windows 6.3 (build 9600)

Steps to Reproduce:

1. Install alefragnani.Bookmarks extension
2. Load any text file with 300,001 lines or more
3. Try to toogle bookmark.
4. Bookmark not toggled and message "Open a file first to toggle bookmarks" is displayed.

Probably related to:
https://github.com/Microsoft/vscode/issues/3147

I'm working with large files, I do not need coloring or syntax checking but I really need some bookmarks working and limit 300,000 lines for extension is insufficient.

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
@rebornix is this still by design, with the work done for larger files?

**Comment by rebornix** [comment]
@radim-moric I have a feeling this warning is from the extension, can you help confirm that?

**Comment by radim-moric** [comment]
@rebornix  don't understand, I have installed alefragnani.Bookmarks extension and according the issue linked below it looks that "large files are invisible to extensions", so warning is from extension but looks like based on "no Active Text" message from VSCode.
[Extremely large files display error "Open a file to toggle bookmarks](https://github.com/alefragnani/vscode-bookmarks/issues/31)

**Comment by qcz** [comment]
See #31078.
