### ISSUE TITLE
Any way of going back to having 2 boxes for include/exclude files for search?

### ISSUE THREAD

**Issue by Poimen** [Microsoft/vscode#47293]
Having just upgraded to v1.22.1 of vscode the release comes with:
> The boxes for include and exclude patterns in the Search view have been combined into a single box.

When working on large directory structures with multiple project roots, with multiple file types, etc., having 2 boxes to include/exclude files was very useful.

Now the exclude/include box looks like:
> .js, !File1.xml, !file1.txt, !**/*.min.js, !**/obj/*, !**/Working/*, !**/Archive/*, !**/BusinessApp/*, !**/coverage/*, !**/OLD/*, !**/TestAuto/Automation.Test/*, !**/Legacy/*,!when_*,!*.spec.js

I search through `.js` files, or `.less`, or `.cs` files regularly and now having a single long string to edit is going to be painful. Previously it was easy - just edit a single box. If I want to remove something from the search - edit a single box. If I want to add something - edit a single box.

Now I'll have find it in a very long string.

I know it is a pretty small gripe but I search quite often during a single day over a number of different file types and cluttering a single box with exclude types is bothersome.

Is there any way of going back to having 2 boxes for these? Hopefully a setting....

Thanks.

**Comment by roblourens** [comment]
Would some of those patterns make sense in your `search.exclude` setting, or are you constantly tweaking all of them?

**Comment by Poimen** [comment]
Some of them are quite set - e.g. `!file1.txt` and `!File1.xml`

Others (like test files) change often. I tend to search through production code separate to tests as it tends to clutter the results. Hence the `spec`*, `when*`,`Test*` change often. 

Also the different directories change often depending on the project, shared projects, etc. that I'm working in. We run a monorepo for the vast majority of our production projects so switching between them is important as you want to exclude projects you're not interested in.

**Comment by roblourens** [comment]
I'll fold this into https://github.com/Microsoft/vscode/issues/46315 for discussion
