### ISSUE TITLE
Precommit hook doesnot work

### ISSUE THREAD

**Issue by IgorTurko** [Microsoft/vscode#47307]
- VSCode Version: 1.21.1
- OS Version: Win10

Steps to Reproduce:

1. Do changes in repo
2. Add message
4. Click on icon commit
5. "precommit": "pretty-quick --staged" does not executed

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Where did you see that that would work?

**Comment by IgorTurko** [comment]
I use this package https://www.npmjs.com/package/pretty-quick for code formatting.
And it should run prettier for all changed files before commit.
We use this hook in package.json "precommit": "pretty-quick --staged"
If our changes marked as CHANGED and not STAGED then vsc skip this precommit hook. I think problem is that we do commit of CHANGED files directly without moving them to STAGED and that is why this "pretty-quick --staged"  can not find any STAGED files. If we can firstly move CHANGED to STAGED automatically then COMMIT then PRECOMMIT should be able to find STAGED files

**Comment by joaomoreno** [comment]
And do you use husky?

When you commit unstaged changes in VS Code, what happens is Code will stage the changes first and then commit them. So that's not the problem.

**Comment by IgorTurko** [comment]
No I do commit directly without manual moving to STAGING. If I move all CHANGED to STAGED then it will work.

Yes you are right from command line: git commit -a -m it also dos not work. So you have always to add CHANGED to STAGED manually. Its not a bug. Its better to ask this npm package to add new flag "--changed" rather then "--staged"

**Comment by joaomoreno** [comment]
Got it, thanks.
