### ISSUE TITLE
Allow to scroll to the top when clicking in the title area of editor

### ISSUE THREAD

**Issue by durdevic** [Microsoft/vscode#47303]
Click again on the open tab to **scroll you back to the top of the document** in goal not to use minimap or shortcuts to reach the top. 

Practically the same thing Opera and Yandex browsers are using e.g.
![image](https://user-images.githubusercontent.com/2753836/38414541-1609a81c-398f-11e8-82f7-67970d9a15d7.png)

I guess it's not to complicated to implement because there are no current action on double tap on the tab.

Cheers!

**Comment by yume-chan** [comment]
> I guess it's not to complicated to implement because there are no current action on double tap on the tab.

Actually, there is one, to exit preview mode.

**Comment by bpasero** [comment]
I find this a bit weird to have because there maybe many reasons to click into the title of an editor (to focus the contents) where you do not want to loose the current position. I feel like we would not implement this, even though it is a nice thing to have for touch devices and browsers.
