### ISSUE TITLE
Cannot connect to runtime process when debugging with auto attach on

### ISSUE THREAD

**Issue by disyam** [Microsoft/vscode#47304]
- VSCode Version: 1.22.1
- OS Version: Fedora 27

Does this issue occur when all extensions are disabled?: Yes

![selection_008](https://user-images.githubusercontent.com/10344921/38415460-cc57e2ba-39bb-11e8-90d9-8f83acce7acc.png)

- i turn on `Debug: Toggle Auto Attach`
- dialog showing when i run `mocha --inspect-brk test/some-test.js`
- dialog not showing when i run `mocha  --inspect-brk`
- my test still run normal
- when i turn off `Debug: Toggle Auto Attach` everything is normal

launch.json:
`{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 9229
    }
  ]
}
`

**Comment by weinand** [comment]
should be fixed now.
