### ISSUE TITLE
Unable to remote debug Electron WebViews in VSCode but Chrome inspect can.

### ISSUE THREAD

**Issue by westacotta** [Microsoft/vscode#47302]
- VSCode Version: 1.22 Insiders
- OS Version: Windows 7

Steps to Reproduce:

1. Create and load an electron app with renderers that themselves host a WebView
2. Open Chrome (in this case  65.0.3325.181)
3. Navigate to chrome://inspect/#devices

You will see something like the following:
Calculator Demo
file:///C:/development/blachs/output/example/calculator/index.html
inspect

container.view.html
file:///C:/development/blah/output/container/container.view.html
inspect

in this case _container.view.html_ is the renderer process and _Calculator Demo_ is the WebView.

you can now click inspect on the webview and debug as normal with typescript source maps etc etc.

4. Open the VSCode project 
5. Create a launch config
        {
            "type": "chrome",
            "request": "attach",
            "name": "Electron: Renderer",
            "port": 9222,
            "sourceMaps": true,
            "timeout": 2000
        }
**6. Launch
    If you have multiple renderers you will be presented with a similar list to chrome BUT it will not show the webview instances so you are unable to debug this code from with Vs Code.**

I've tried specifying the _URL_ config option with the same webview path as Chrome shows to see if it can force it to debug it but it doesn't work either.

Any ideas?   With this working it would give a pretty complete debug experience to match Chrome

Note: Debugging of renderers themselves works great.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug#642
