### ISSUE TITLE
`ctrl + a` should behave exactly like `cmd + arrow left`

### ISSUE THREAD

**Issue by kompot** [Microsoft/vscode#47319]
- VSCode Version: 1.22.1
- OS Version: macOS

Right now `ctrl + a` puts cursor to 0 position of the current line.
`Cmd + left arrow` puts cursor to first non white space position and second `cmd + left arrow` press puts it to 0 position.

To me the latter is the proper case and `ctrl + a` should do the same.

**Comment by roblourens** [comment]
You can customize the keybinding if you want, and bind ctrl+a to `cursorHome`.
