### ISSUE TITLE
nls - jsconfig.json guidance comment is not externalized

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4731]
![image](https://cloud.githubusercontent.com/assets/172399/14100940/47264d86-f591-11e5-94c2-00b19f97d453.png)

**Comment by jrieken** [comment]
**verifier**: unsure if we have new nls files already, if not check the code

**Comment by isidorn** [comment]
We have new nls files - I updated it yesterday evening and I see new debug strings transalted. However this is still in english for me. I do not think critical -> moving to may

**Comment by jrieken** [comment]
@isidorn Do you expect me to make another except for this: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/utils/projectStatus.ts#L198

**Comment by jrieken** [comment]
Assigning to your for clarification. Unsure when and how the translations happen for extensions. 

fyi @isidorn who did the nls input

**Comment by isidorn** [comment]
@dbaeumer did the input to the translation team before he left for vacation. I picked up the input and consumed it inside vscode and vscode-node-debug

**Comment by dbaeumer** [comment]
The input to the translation team contains extension as well. You can always check if the string got translated by checking the content in the i18n folder. Looks like this one didn't.

@jrieken moving back. Feel free to close and assume that the string will come back in the next translation round if correctly externalized.
