### ISSUE TITLE
Can't use long commands in tasks. Used to work in previous release.

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#47317]
Can't long command in tasks. On the previous release I could do:
"command": "",
      "args": [
"(echo %DATE% %TIME%)",
"&"
" < build command >"
"&"
" <another build command >"

I can't find a way of doing this with the latest version. This has broken all my tasks, which means I can't run any builds from with VS Code. This is causing major pain.

**Comment by dbaeumer** [comment]
You can still use args but if they shouldn't be quoted they should not contain any spaces. I could add support for non quoting args if they have spaces.

**Comment by BillDenton** [comment]
I'm not sure I understand your comment. This was my original setup running in Windows:
"command": "",
"args": [
  "(echo %DATE% %TIME%)",
   "&",
   "(scons build1",
   " || ${workspaceFolder}\\.vscode\\beepbeepbeep.bat)",
   "&&",
   "(scons build2",
   " || ${workspaceFolder}\\.vscode\\beepbeepbeep.bat)",
   "&&",
    "( echo %DATE% %TIME% & ${workspaceFolder}\\.vscode\\beep.bat )"
Note: "build1" and "build2" are long and there would be more builds. How would I do this with the new system?

**Comment by dbaeumer** [comment]
OK. Now I see. I this case it would result in a lot of args since you need to split
```
"(echo",
"%DATE%",
"%TIME%",
...
```
which I understand is very cumbersome. Alternatively you can write a small shell script and pass ${workspaceFolder} as a argument or as said build one command line. I will look into adding support to ask for non quoting for args but that would then fail for you if ${workspaceFolder} would contain spaces. This is one reason why we added improved quoting support and fixed bugs around it since resolving these variable and passing them on always failed if the resolved value had spaces.

**Comment by BillDenton** [comment]
For some tasks, I have written a Windows batch file, but I find for build tasks where I often edit the parameters it easier to have it in tasks.json. It would be good to have non-quoting for args so that I can restore my original setup. I don't have any spaces in my paths, I may just a create a very long list for now.

**Comment by BillDenton** [comment]
I've got it working by quoting each part. By grouping related items on the same line it is reasonably readable, but a little tricky to edit. So it's working again.

**Comment by dbaeumer** [comment]
Good to hear. I thought more about it and instead of having args with spaces without quoting we should offer to allow a string[] for a command which the task system the combines to one line.

**Comment by BillDenton** [comment]
@dbaeumer Could you give an example for your proposed change. Then this issue could be used to track when this would be implemented. Thanks.

**Comment by dbaeumer** [comment]
```
{
    "type": "shell",
    "command": [
        "(echo %DATE% %TIME%) ",
        "& ",
        "(scons build1 ",
        ....
    ]
}
```

**Comment by BillDenton** [comment]
That looks good and is the same syntax as used to be supported for "args". What's the plan for implementation?

**Comment by dbaeumer** [comment]
I will look into doing this for April. But no promise yet. Have quite some things on my plate.

**Comment by BillDenton** [comment]
Thanks "Have quite some things on my plate." I know that...

**Comment by dbaeumer** [comment]
I have not started working on this. Please see my comment https://github.com/Microsoft/vscode/issues/47317#issuecomment-379733890

**Comment by freedom5566** [comment]
Thank you!I am looking forward.

**Comment by dbaeumer** [comment]
I need to move this out. Starting as soon as possible...

**Comment by dbaeumer** [comment]
To verify write a shell task where the command is a string array. The actual command is the joined string element with a space. An example is:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "eslint",
			"type": "shell",
			"command": [
				"node_modules\\.bin\\eslint.cmd",
				"."
			],
			"problemMatcher": "$eslint-stylish"
		}
	]
}
```
