### ISSUE TITLE
Suggestion - File Directory Explorer - collapse empty directories avoiding indentation

### ISSUE THREAD

**Issue by joewood** [Microsoft/vscode#47318]
The VS Code File Directory tree explorer should skip empty directories that only contain a single sub-directory in the same way as Github's website works. 

So, an existing directory:
```
/ root
   / subdir1
      / sub-subdir
          / sub3dir
              # file1.java
              # file2.java
              # file3.java
  / subdir2
```

Should be shown like this:
```
/ root
   / subdir1/sub-subdir/sub3dir
      # file1.java
      # file2.java
      # file3.java
  / subdir2
```

This would be very useful for Java developers, where drilling down the directory tree and losing horizontal space is a problem for deeply nested package namespaces.

**Comment by yume-chan** [comment]
Duplicate of #41627

**Comment by joewood** [comment]
Yup, dupe - sorry.
