### ISSUE TITLE
[BUG] Incorrect comment style within JSX tag

### ISSUE THREAD

**Issue by peterschussheim** [Microsoft/vscode#47329]
Issue Type: <b>Bug</b>

The following example demonstrates how VSCode should (and used to, up until a week or two ago) apply comment style when user calls 'comment' command (`CMD + /` or `CTRL + /`) within `JSX`.

```jsx
import React from 'react'

class Main extends React.Component {
  render() {
    return (
      <div>
        <h1>
          <input type="button" value="test" />
          {/* <h2>
            <a href="">TEST</a>
          </h2>
          <aside>
            <button disabled="disabled">Cool</button>
          </aside> */}
          <p />
        </h1>
      </div>
    )
  }
}

export default Main
```

## Display current behavior

![screencapture](http://g.recordit.co/mg67DvJikq.gif)

VS Code version: Code - Insiders 1.23.0-insider (95101bf3f6d00105621cdddb639ea62b95ea2468, 2018-04-06T09:59:42.933Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1639570236|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
vscode-docker|Pet|0.0.26
sort-lines|Tyr|1.6.0
vscode-node-readme|ben|3.0.2
emojisense|bie|0.4.0
markdown-checkbox|bie|0.1.1
markdown-preview-github-styles|bie|0.1.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
vscode-dash|dee|1.8.0
vscode-npm-source|dku|1.0.0
es7-react-js-snippets|dsz|1.3.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.2.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
vscode-todo-plus|fab|1.10.3
flow-for-vscode|flo|0.8.0
auto-close-tag|for|0.5.6
RelativePath|jak|1.3.0
flow-ls|jba|0.0.5
vscode-rust|kal|0.4.2
auto-comment-blocks|kev|1.0.1
graphql-for-vscode|kum|1.9.1
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.5
cpptools|ms-|0.16.1
sublime-keybindings|ms-|3.0.3
vsliveshare|ms-|0.2.307
debugger-for-chrome|msj|4.3.0
syncing|non|1.5.3
vscode-code-outline|pat|0.1.0
convert-css-in-js|pau|1.0.0
vscode-versionlens|pfl|0.20.0
polacode|pnp|0.2.2
vscode-icons|rob|7.22.0
partial-diff|ryu|0.5.1
vscode-fileutils|sle|2.8.1
vscode-hexdump|sle|1.6.0
flowmaker|spe|1.2.0
guides|spy|0.9.1
vscode-status-bar-format-toggle|tom|1.3.0
babelrc|wad|1.0.0
licenser|ymo|1.1.1
markdown-all-in-one|yzh|1.1.2

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this repo with all extensions disabled?

**Comment by peterschussheim** [comment]
This does not reproduce with all extensions disabled...I discovered using the dev tools that the [vscode-babel extension](https://github.com/dzannotti/vscode-babel) was the cause. [Here is one issue in the ext repo](https://github.com/dzannotti/vscode-babel/issues/19).  I am going to close this, apologies for jumping the gun ;)
