### ISSUE TITLE
Terminal print additional " when executing task

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#47322]
OS: Windows

Task to execute:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "echo",
			"type": "shell",
			"command": "echo (%DATE% %TIME%) world",
			"problemMatcher": [],
			"options": {
				"shell": {
					"executable": "cmd.exe",
					"args": [
						"/d", "/c"
					]
				}
			}
		}
	]
}
```

You get the following output (observe the extra ")

<img width="365" alt="capture" src="https://user-images.githubusercontent.com/1931590/38424119-4e58e0cc-39b0-11e8-87bb-84a9d6653635.png">

Here is the Shell configuration I pass to the terminal

<img width="1193" alt="capture" src="https://user-images.githubusercontent.com/1931590/38424084-379fdea8-39b0-11e8-8c38-cb8a4b018195.png">

**Comment by dbaeumer** [comment]
This seems to only happen in insider. 1.22 seems to be fine.

**Comment by Tyriar** [comment]
Might be the same as https://github.com/Microsoft/vscode/issues/47314?

**Comment by dbaeumer** [comment]
Couldn't reproduce running from source this morning
