### ISSUE TITLE
React autocomplete stops

### ISSUE THREAD

**Issue by yuritoledo** [Microsoft/vscode#47326]
- VSCode Version: Version 1.21.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Install any lib (SemanticUI) or create any component stateless with react, and you will not have the autocomplete component props neither it documentation (type / usage)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

This issue start on last week. I try to use VScode insiders and in another fresh linux installation.

![captura de tela de 2018-04-06 11-05-31](https://user-images.githubusercontent.com/18474538/38425619-c3e34ff6-398a-11e8-8952-161bfbdbd330.png)
![captura de tela de 2018-04-06 11-05-43](https://user-images.githubusercontent.com/18474538/38425620-c4487bb0-398a-11e8-9211-d039d434b804.png)

**Comment by mjbvz** [comment]
Please share a small example project or some example code (not just screenshots)

**Comment by yuritoledo** [comment]
https://codesandbox.io/s/k388w8mmpo

![image](https://user-images.githubusercontent.com/18474538/38439805-6b7949b2-39b5-11e8-8944-fab8d1e21b3c.png)

**Comment by mjbvz** [comment]
I can't repo this in vscode 1.22. Can you please test this on 1.22 with all extensions disabled

**Comment by yuritoledo** [comment]
in 1.22 works normally.

Thanks
