### ISSUE TITLE
All UI state was lost after todays update

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#47320]
- VSCode Version: 1.23.0-ins
- OS Version: win7x64

12 hours ago was an update from 1.22.0-insiders to 1.23.0-insiders.... everything was OK.

But now, after one more update ...

```
Version 1.23.0-insider
Commit 95101bf3f6d00105621cdddb639ea62b95ea2468
Date 2018-04-06T08:49:48.798Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Does this issue occur when all extensions are disabled?: Yes/No
```

... all open editors just disappeared. Instead of them - a "Welcome" page.

![image](https://user-images.githubusercontent.com/24613274/38422008-de5b77a6-39b1-11e8-880c-867f35ac5325.png)

Hm.

PS: it really can be because of **_laggy frozen downloading error_** of the new updates.
So, the problem is when you try to check updates - clock appears on the gear icon ...

![image](https://user-images.githubusercontent.com/24613274/38422251-b53d55fa-39b2-11e8-86bb-2db9a1df4f3b.png)

... and it gets frozen. No reaction at all. If you hover cursor - it will say "Update is downloading....".
And that's it. So, the only way to bring it back to life is to restart VS Code by closing it. Maybe it causes the damage of the workspace files. I don't know.

**Comment by user3323** [comment]
@bpasero , thanks for reaction!

Yes, it worked.

And a little remark about renaming process...

![image](https://user-images.githubusercontent.com/24613274/38424268-2cc5b8aa-39b9-11e8-89a9-e116605ea69d.png)

... in the case, that new `localstorage`'s files already exist - first you need to delete those.

**Comment by bpasero** [comment]
@user3323 great to hear this recovery worked, I have updated the steps to make sure to delete the existing files first.

**Comment by bpasero** [comment]
Closing, will point other users to this in case we have more.

**Comment by eamodio** [comment]
I saw the same thing in that extension enabled/disabled state was lost. The recovery above fixed it.
