### ISSUE TITLE
TS: make it easier for a node.js user to leverage typescript

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#47321]
I recently went through the process of writing a new node module and I gave it a try using TypeScript. Even though I am a developer on VSCode I had to leave Code to search for a solution how to get Intellisense to work for the built in node modules.

**Steps:**
* create a fresh folder
* add a simple `package.json`
* add a simple `index.ts` file (see contents below)
* notice an error around the import
* find no advice how to fix it

The actual fix was to add `@types/node` as a dependency but we should offer this to the user when we detect that a built in node module is being used. It is especially weird because we seem to offer this for other 3rd party modules that you add later on.

`index.ts`
```typescript
var fs = require("fs");
```

**Result:**
![image](https://user-images.githubusercontent.com/900690/38423433-34ec12f0-39ae-11e8-9052-a2a4ea4f45bf.png)

I am tempted to mark this "important" because I think a lot of users will stop trying TypeScript after they went as far as I did without searching for the solution. And I think node.js with TypeScript users are one of our main target audience. 

It could well be that this issue has to move to the TypeScript repo, but I start here.

**Comment by kieferrm** [comment]
I agree that we should be more helpful here. Particularly when you compare this with the experience you have when you do the same in JavaScript. Then, there is nothing for you to do, it just works.

**Comment by mjbvz** [comment]
Yes I think it's fairly safe to assume that when we see a module called `fs` or a `require` statement, the user wants to install `@types/node`. I've opened two issues to track improving this:

- https://github.com/Microsoft/TypeScript/issues/23224 
- https://github.com/Microsoft/TypeScript/issues/23224
