### ISSUE TITLE
Diagnosing why my terminal process exited

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#47328]
Issue Type: <b>Bug</b>

So I'm trying to fix an extension I wrote, and I know I've done something wrong. When I run the debug task (Launch Client), I get an error saying:

The terminal process terminated with exit code: 1. 

So I tried to find that process to see what went wrong, and I can't find more details *anywhere*. If I open dev tools, I see an error reported from workbench.main.js, but it doesn't provide more details.

For the heck of it, I tried with a non-Insiders VSC, and it has the *exact* same issue, except the code is 2.

So I'm not asking yall to fix my extension of course, but mainly, how do I get more details to figure out the real issue here?

Screen shots:
![image](https://user-images.githubusercontent.com/393660/38426655-d9772efe-397c-11e8-8f6a-9fbf839fa867.png)

![image](https://user-images.githubusercontent.com/393660/38426661-de163798-397c-11e8-9705-7ccd4fe9e931.png)

VS Code version: Code - Insiders 1.23.0-insider (95101bf3f6d00105621cdddb639ea62b95ea2468, 2018-04-06T08:49:48.798Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (3.62GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.2
copy-relative-path|ale|0.0.2
spellright|ban|2.2.6
markdown-preview-github-styles|bie|0.1.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.27
prettier-vscode|esb|1.2.2
apiconnecttools|IBM|0.0.5
coldfusion|ili|1.0.1
wordcounter|kir|1.2.2
dotenv|mik|1.0.1
vetur|oct|0.11.7
polacode|pnp|0.2.2
CSSLint|ray|0.0.5
htmlescape-vscode-extension|ray|0.0.4
vue-vscode-extensionpack|sdr|0.1.2
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|2.9.0
vscode-status-bar-format-toggle|tom|1.3.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

</details>

**Comment by cfjedimaster** [comment]
If I do the build task, I get the same error (with the same lack of details).

**Comment by cfjedimaster** [comment]
Ok, I think I see it- hopefully this pastes well:

TRACE terminalInstance#ctor (id: 3) Object {name: "Task - watch:client", executable: "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe", args: "-Command npm run watch:client", waitOnExit: false, initialText: "[1m> Executing task: npm run watch:client <[0m↵"…}
log.ts:153 DEBUG Terminal process launching (id: 3) Object {env: Object, cwd: "c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\terminal\node"}
log.ts:147 TRACE terminalInstance#ctor (id: 4) Object {name: "Task - watch:server", executable: "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe", args: "-Command npm run watch:server", waitOnExit: false, initialText: "[1m> Executing task: npm run watch:server <[0m↵"…}
log.ts:153 DEBUG Terminal process launching (id: 4) Object {env: Object, cwd: "c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\terminal\node"}
log.ts:153 DEBUG Terminal process ready (id: 4, processId: 768)
log.ts:153 DEBUG Terminal process message (id: 4) Object {type: "pid", content: 768}
log.ts:153 DEBUG Terminal process message (id: 4) Object {type: "title", content: "powershell.exe"}
log.ts:153 DEBUG Terminal process ready (id: 3, processId: 19316)
log.ts:153 DEBUG Terminal process message (id: 3) Object {type: "pid", content: 19316}
log.ts:153 DEBUG Terminal process message (id: 3) Object {type: "title", content: "powershell.exe"}
log.ts:153 DEBUG Terminal process message (id: 4) Object {type: "data", content: "[0m[0K"}
log.ts:153 DEBUG Terminal process message (id: 3) Object {type: "data", content: "[0m[0K"}
log.ts:153 DEBUG Terminal process message (id: 4) Object {type: "data", content: "[0;31;91m-Command : The term '-Command' is not re…xception[0m[0K
↵[0;31;91m [0m[0K
↵[0K[?25h"}content: "[0;31;91m-Command : The term '-Command' is not recognized as the name of a cmdlet, [0m[0K[?25l
↵[0;31;91mfunction, script file, or operable program. Check the spelling of the name, or [0m[0K
↵[0;31;91mif a path was included, verify that the path is correct and try again.[0m[0K
↵[0;31;91mAt line:1 char:1[0m[0K
↵[0;31;91m+ -Command npm run watch:server[0m[0K
↵[0;31;91m+ ~~~~~~~~[0m[0K
↵[0;31;91m    + CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandNot [0m[0K
↵[0;31;91m   FoundException[0m[0K
↵[0;31;91m    + FullyQualifiedErrorId : CommandNotFoundException[0m[0K
↵[0;31;91m [0m[0K
↵[0K[?25h"type: "data"__proto__: Object
log.ts:153 DEBUG Terminal process message (id: 3) Object {type: "data", content: "[0;31;91m-Command : The term '-Command' is not re…xception[0m[0K
↵[0;31;91m [0m[0K
↵[0K[?25h"}
log.ts:153 DEBUG Terminal process exit (id: 3) with code 1
log.ts:153 DEBUG Terminal process exit (id: 3) state 5
log.ts:147 TRACE terminalInstance#dispose (id: 3)
notificationsAlerts.ts:39 The terminal process terminated with exit code: 1

This seems to be it:
[0;31;91m-Command : The term '-Command' is not re…xception[0m[0K
↵[0;31;91m [0m[0K
↵[0K[?25h"}
content
:
"[0;31;91m-Command : The term '-Command' is not recognized as the name of a cmdlet, [0m[0K[?25l
↵[0;31;91mfunction, script file, or operable program. Check the spelling of the name, or [0m[0K
↵[0;31;91mif a path was included, verify that the path is correct and try again.[0m[0K
↵[0;31;91mAt line:1 char:1[0m[0K
↵[0;31;91m+ -Command npm run watch:server[0m[0K
↵[0;31;91m+ ~~~~~~~~[0m[0K
↵[0;31;91m    + CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandNot [0m[0K
↵[0;31;91m   FoundException[0m[0K
↵[0;31;91m    + FullyQualifiedErrorId : CommandNotFoundException[0m[0K
↵[0;31;91m [0m[0K
↵[0K[?25h"
type
:
"data"

Forgive all the ugly characters but that's what I'm seeing in console as well. I just did a right click, store as global var, then copy,a nd this seems cleaner:

{
  "type": "data",
  "content": "\u001b[0;31;91m-Command : The term '-Command' is not recognized as the name of a cmdlet, \u001b[0m\u001b[0K\u001b[?25l\r\n\u001b[0;31;91mfunction, script file, or operable program. Check the spelling of the name, or \u001b[0m\u001b[0K\r\n\u001b[0;31;91mif a path was included, verify that the path is correct and try again.\u001b[0m\u001b[0K\r\n\u001b[0;31;91mAt line:1 char:1\u001b[0m\u001b[0K\r\n\u001b[0;31;91m+ -Command npm run watch:server\u001b[0m\u001b[0K\r\n\u001b[0;31;91m+ ~~~~~~~~\u001b[0m\u001b[0K\r\n\u001b[0;31;91m    + CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandNot \u001b[0m\u001b[0K\r\n\u001b[0;31;91m   FoundException\u001b[0m\u001b[0K\r\n\u001b[0;31;91m    + FullyQualifiedErrorId : CommandNotFoundException\u001b[0m\u001b[0K\r\n\u001b[0;31;91m \u001b[0m\u001b[0K\r\n\u001b[0K\u001b[?25h"
}

**Comment by Tyriar** [comment]
Looks the same as https://github.com/Microsoft/vscode/issues/47314

Inside the "Terminal process launching" log, could you also share on #47314 all of the environment variable starting with "PTY"?

**Comment by cfjedimaster** [comment]
Ok - this may be a duplicate, but to my initial question, should the problem have been visible? I mean w/o --log trace?

**Comment by cfjedimaster** [comment]
And remember, I also had issues with the non-Insider release. It was a different code, but still no visible detail.

**Comment by cfjedimaster** [comment]
Finally (sorry for all the comments ;) - running "set" in cmd.exe and I don't see any env vars that being with PTY.

**Comment by Tyriar** [comment]
@cfjedimaster so I think I solved https://github.com/Microsoft/vscode/issues/47314, not sure what's going on with the stable build though, I suspect it's a different issue.

**Comment by cfjedimaster** [comment]
Alright - I'll test in the next release. Thanks for your help!
