### ISSUE TITLE
File sorting in Open Editors and Edit Pane

### ISSUE THREAD

**Issue by FritzHerbers** [Microsoft/vscode#47330]
Finding files in the Editor Pane is not usable, only 5 files are shown and the files are sorted in the wild.
The files in the Open Editors are sorted as they are sorted in the Editor Pane. Rearranging them is tedious, and the focus on which files have to be edited changes many times during the day.

- It would be nice to have a sort on filename in the Editor Pane.

With many files open and during a given time some 4-5 files are used. However, depending when these files have been opened they can be at the beginning or at the end. Scrolling to search the given file is not an option. The Editor Pane is not sort able, so you have to search yourself.

- It would be nice the Open Editors have a possibility to sort on LRU.

- It would be nice the Open Files in the Edit Pane are LRU and sort to the beginning. 
A new opened file is always at the beginning.
An opened file which is clicked in the Explorer or the Open Editors is moves to the beginning.
A file which is edited moves to the beginning or can stay as long as it was visible in the Editor Pane tab.

**Comment by bpasero** [comment]
Try with the `"workbench.editor.openPositioning"` setting, e.g. `"workbench.editor.openPositioning": "first"`

**Comment by FritzHerbers** [comment]
How can I sort filenames in the Open Editors pane
-  on LRU 
-  filename
