### ISSUE TITLE
Debug stuck when removing breakpoint

### ISSUE THREAD

**Issue by bogdanac** [Microsoft/vscode#4733]
- VSCode Version: 0.10.11
- OS Version: W10

Steps to Reproduce:

1. Insert breakpoint somewhere in the code
2. Start debug
3. Erase breakpoint before it gets to it
4. The debug stops at the erased breakpoint (cannot go forward, it's stuck there). I am sure it stops there because of the logging my code has.

:)

**Comment by weinand** [comment]
@bogdanac what version of node are you using? Do you have a small code snippet that shows the problem?

**Comment by weinand** [comment]
@bogdanac most likely this is the same as https://github.com/Microsoft/vscode/issues/4966. If you can reproduce could you please confirm that this only occurs in "inlined source". You can find this information at the top of the editor:

![2016-04-05 17-12-28](https://cloud.githubusercontent.com/assets/1898161/14287060/a8a24734-fb51-11e5-9e8a-67d873e0e75e.png)
