### ISSUE TITLE
git file-decorations do not show till switch to git tab and back

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#47334]
- VSCode Version: latest insiders
- OS Version: win 10

Steps to Reproduce:

1. open git folder, no git decorations in explorer
2. switch to source control and back, git decorations in explorer

Does this issue occur when all extensions are disabled?: Yes

thanks

**Comment by rakkarage** [comment]
git log from before switching

`Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.16.2.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: d:\code\itch.io\Ease
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
`
after does not change

**Comment by jrieken** [comment]
Log looks good, can still not reproduce
