### ISSUE TITLE
Git child process count out of control

### ISSUE THREAD

**Issue by jd-carroll** [Microsoft/vscode#47336]
- VSCode Version: 1.21.0
- OS Version: Windows 10

- Reproducible with all extensions disabled: Yes

On my work desktop we have observed **30,000** git.exe child processes be spawned from running VSCode.  This has been happening on & off since ~v1.19 and it is difficult to recreate.  Lately (v1.21.0) it has been happening more consistently and seems to occur the days after I perform a full restart (n+>=1).  (Meaning the day I restart it is fine, but any day after is not)

I would say that this is consistent with the issues reported in #42819 and #44759.

Screen shot of task manager:
![sample screen shot](https://user-images.githubusercontent.com/1885864/38430574-9fe5113e-398f-11e8-953a-d0bf0d681b28.png)
Note: When I say clicked into VSCode, I literally mean I clicked into an open editor and the CPU spiked to 100%.  The drop you see is when I clicked back into Outlook.

We didn't realize what was happening until recently when someone from our security team shared the following screen shots from CarbonBlack:
![carbon-black-task-list](https://user-images.githubusercontent.com/1885864/38430636-cea420a0-398f-11e8-9296-0deb367eebbc.png)
![carbon-black-task-tree](https://user-images.githubusercontent.com/1885864/38430639-d100e43c-398f-11e8-8d02-924e7ba2bb61.png)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (4 x 2395)|
|Memory (System)|16.00GB (8.17GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   105	 12664	code main
    0	   153	  5672	   powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
    0	     8	 12720	     console-window-host (Windows internal process)
    0	   305	 10144	   window (settings.json - weos (Workspace) - Visual Studio Code)
    0	    81	 12088	     extensionHost
    0	    63	  8620	       electron_node jsonServerMain.js 
    0	    23	  9092	       electron_node tslintServer.js 
    0	    20	 11164	       electron_node eslintServer.js 
    0	    65	 13240	       electron_node electronForkStart.js tsserver.js 
    0	    19	 10092	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    19	 12984	     terminal
    0	     6	  1940	       winpty-process
    0	     6	  7388	         C:\Windows\System32\cmd.exe
    0	    10	 12440	         console-window-host (Windows internal process)
    0	    31	 13964	     watcherService
    0	    19	 18828	     searchService
    1	   146	 11836	   gpu-process
    0	    78	 12524	   shared-process
    1	    73	 22376	   shared-process
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.14.1
vscode-eslint|dba|1.4.8
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.3.0
vscode-apache|mrm|1.1.1
cpptools|ms-|0.16.1
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.3.0
vscode-docker|Pet|0.0.26

</details>

**Comment by joaomoreno** [comment]
Can you should me the full command line of one of those git.exe processes?

**Comment by jd-carroll** [comment]
How would I do that? Not sure CarbonBlack gives us that info. Is it logged
some where?

**Comment by joaomoreno** [comment]
You can use ProcessHacker to get that info.

**Comment by joaomoreno** [comment]
VS Code spawns git in order to know which state the git repository is at. Spawning many times is OK. They should just not all be running at the same time. Are they?
