### ISSUE TITLE
ES6 refactoring is deleting the comments above

### ISSUE THREAD

**Issue by pen-mb** [Microsoft/vscode#47337]
Issue Type: <b>Bug</b>

When the lines above the code that is subject to ES6 refactoring are comments, VSC deletes them. If there is actual code, followed by comments, followed by code subject to ES6 refactoring, the comments inbetween are deleted as well.

[Example image](https://i.imgur.com/1jlg3yH.png)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|5.91GB (2.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Documents\Kod\Web Dev\Resources\html5-boilerplate6.0.1\doc\html.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
auto-rename-tag|for|0.0.15
python|ms-|2018.3.1
vscode-code-outline|pat|0.1.0
vscode-icons|rob|7.22.0
sass-indented|rob|1.4.8
code-settings-sync|Sha|2.9.0
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Thanks! Opened https://github.com/Microsoft/TypeScript/issues/23236 to track this upstream
