### ISSUE TITLE
Bottom left branch name should show current file's branch

### ISSUE THREAD

**Issue by acburigo** [Microsoft/vscode#47332]
Issue Type: <b>Bug</b>

Open a file from one repository that is in your open folder;
Open a file from another repository that is in your open folter;
Bottom left branch name should be referring to the current file's repository branch name, but it is not.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|31.86GB (24.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
I suggest to enable this as a setting.

**Comment by gioragutt** [comment]
@joaomoreno is it worth PRing this?

**Comment by D-Jones-1** [comment]
If there's anything I can do to fix the bug and someone can explain the work to be done, I'd be happy to.

**Comment by infa-stopiwal** [comment]
@joaomoreno this is so awesome. This bug kept me from using VS Code for the longest time. Any idea about which version this fix would become available in? Please and thank you for fixing this!

**Comment by joaomoreno** [comment]
1.28 should be available around the first week of October. Don't thank me, thank @egamma and @kieferrm for planning an issue reduction milestone!
