### ISSUE TITLE
1.22 won't run shell tasks with args

### ISSUE THREAD

**Issue by mikeygnyc** [Microsoft/vscode#47335]
- VSCode Version: 1.22 
- OS Version: OS X 10.13.4

Steps to Reproduce:

1. Create shell task with command args:

```json
{
        "label":"clean build",
        "type":"shell",
        "command":"tsc && rm",
        "args": ["-f", "./logs/*"],
        "presentation": {
          "echo": true,
          "reveal": "always",
          "focus": false,
          "panel": "shared"
         }
}
```
2. Run the task.

Does this issue occur when all extensions are disabled?: Yes

## Expected output:

> > Executing task: tsc && rm -f ./logs/* 
> Terminal will be reused by tasks, press any key to close it.

## Actual output:

> > Executing task: 'tsc && rm' -f ./logs/* <
>
>/bin/bash: tsc && rm: command not found
>The terminal process terminated with exit code: 127

***
This appears to be a new issue in 1.22. The task ran in 1.21

Changing it to this (integrating the command args into the command) works:

```json
{
        "label":"clean build",
        "type":"shell",
        "command":"tsc && rm -f ./logs/*",
        "presentation": {
          "echo": true,
          "reveal": "always",
          "focus": false,
          "panel": "shared"
         }
}
```

**Comment by dbaeumer** [comment]
We fixed bugs and added better support for quoting shell commands and args tasks in 1.22 (see https://code.visualstudio.com/docs/editor/tasks#_custom-tasks and https://code.visualstudio.com/updates/v1_22#_tasks). It was a long wanted support. For a while tasks issued warnings that args with spaces aren't supported and that they should be folded into the command itself. But  forgot about the use case you use of having a combined command with &&. I apologize for this. You must either use one command or use args without spaces. In our case:

```
"command":"tsc",
"args": [
   "&&", "rm", "-f", "./logs/*"
]
```

I again apologize for not warning about your case. But reverting this and not having proper quoting support is a step backwards. 

Is it OK for you to close the issue?

**Comment by mikeygnyc** [comment]
That works for me. Thanks for the clarification!
