### ISSUE TITLE
duplicate  plugin by different versions

### ISSUE THREAD

**Issue by foxundermoon** [Microsoft/vscode#47339]
- VSCode Version: 1.21.1
- OS Version: mac os 10.12.6

i  found the issue  when i  uninstall a extension but still there after reload.

![image](https://user-images.githubusercontent.com/2764106/38432860-6ff216ae-39fb-11e8-831c-cb534e6b7fc4.png)

![image](https://user-images.githubusercontent.com/2764106/38432967-c5fc3dc2-39fb-11e8-9fbc-59f6ab50cad2.png)

![image](https://user-images.githubusercontent.com/2764106/38432983-d30530be-39fb-11e8-909c-6812ca3d3741.png)

almost all extension will

**Comment by sandy081** [comment]
Not sure what is the issue you are seeing. When you install an extension are you seeing older version of extension being loaded?

**Comment by sandy081** [comment]
Please reopen the issue with the requested information
