### ISSUE TITLE
Disable source control providers

### ISSUE THREAD

**Issue by rogierlommers** [Microsoft/vscode#47348]
Please see screenshot below. Is it possible through user prefs to get rid of the "source control providers"-section? To be honest, I never use it and it confuses me. I only want to see the changes in the current project.

<img width="375" alt="get-rid-of-this" src="https://user-images.githubusercontent.com/3907131/38439157-e4f55066-39dc-11e8-9833-d0bbb9678e5c.png">

**Comment by yume-chan** [comment]
There are two situations when the Source Control panel displays multiple entries:

1. You have a workspace with multiple Git repositories open
2. The folder you opened have at least one Git submodule

I don't think you can only show one entry for situation 1.

For situation 2, set `git.detectSubmodules` settings to `false` to disable it.

**Comment by rogierlommers** [comment]
Well I think situation one is going on here. I have one repo (without submodules) open. Then I click on a function from a package which I'm including. The package file then opens and is also a repo. It would be great if this repo (from the package) was not listed in the `source control`-panel.

**Comment by joaomoreno** [comment]
I suggest a boolean setting `git.detectRepositoriesFromOpenEditors`.

**Comment by shobhitchittora** [comment]
@joaomoreno I'd like to work on this. Any suggestions / code pointers ?

**Comment by rogierlommers** [comment]
Hey @shobhitchittora , thanks!!!!!!

**Comment by joaomoreno** [comment]
Oh we actually already have such a setting: `git.autoRepositoryDetection`. 😆
