### ISSUE TITLE
Feature Request:  Regex support for look around

### ISSUE THREAD

**Issue by SvdSinner** [Microsoft/vscode#47340]
Please provide full regular expression support (or at minimum support similar to other Microsoft products -- Visual Studio IDE, SSMS, etc.)  Features like Look Ahead and Look Behind assertions need to be supported.

- VSCode Version: 1.22.1
- OS Version:  Windows 10

Steps to Reproduce:

1.  Open search widget
2.  Enable Regular Expressions for the search
3.  Attempt to search files for a regular expression with look ahead/behind clauses
4.  They don't work.  :(

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Search is powered by the ripgrep tool which doesn't support those advanced regex features.
