### ISSUE TITLE
Clear Output issues

### ISSUE THREAD

**Issue by wdscxsj** [Microsoft/vscode#47342]
- VSCode Version: 1.22.1
- OS Version: Windows 10

**Issue 1**: Clear Output with Output closed triggers an error.

Steps to Reproduce:

1. With the Output window closed, Ctrl+Shift+P to run "View: Clear Output".
2. An error notification pops up saying "Cannot read property 'focus' of null." This notification should not happen. The good part is the output content (if any) has been cleared in the background.

**Issue 2**: If the Output window is open, Clear Output inappropriately gives it focus. There should be an option to avoid this.

Do these issues occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
fyi @sandy081 I have changed the clear output action to not focus the output
Reason being that the output just got cleared and there is no reason for the user to be focused there since it is read only
