### ISSUE TITLE
Debug status bar item has visual glitch

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#47349]
![image](https://user-images.githubusercontent.com/323878/38439885-204b53de-3994-11e8-85c1-13fef3d74e5e.png)

It only shows up in some windows, but survives reloading. Inspected it with devtools and didn't see an obvious problem.

**Comment by isidorn** [comment]
Can not reproduce this. And actually does not look that bad
Do you have some steps on how to end up in this state?
When inspecting did you check the width of the item? Is there some border which should not be there?
Could you see the glitch for other status bar items?

**Comment by roblourens** [comment]
I was seeing this consistently for at least a couple days but I haven't seen it again recently 🤷‍♂️

**Comment by isidorn** [comment]
Might be some unrelated status bar work. Anyways if you see it again just try to inspect more and let me know how it looks
