### ISSUE TITLE
Log Point not working if no {} section

### ISSUE THREAD

**Issue by guycnicholas** [Microsoft/vscode#47343]
Issue Type: <b>Bug</b>

I add a Log Point with no curlies such as "I am here" and no text will get output to the console as I pass the point. If I change the text to "I am here {myVar}" then I get output to the console.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/VS_Code/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_7919501|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.27
duk-debug|Har|0.4.1
vscode-docker|Pet|0.0.26
logcat|abh|0.0.7
android-dev-ext|ade|0.4.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
vscode-npm-script|eg2|0.3.3
flow-for-vscode|flo|0.8.0
rest-client|hum|0.18.1
mdhelper|jos|0.0.11
sublime-babel-vscode|jos|0.2.9
azure-account|ms-|0.4.0
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.3.0
vscode-code-outline|pat|0.1.0
java|red|0.22.0
vscode-icons|rob|7.22.0
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0

</details>

**Comment by weinand** [comment]
I cannot reproduce this:

![2018-04-06_19-49-38](https://user-images.githubusercontent.com/1898161/38436009-bc0a1d66-39d3-11e8-895f-13b5cf2755c8.png)

**Comment by guycnicholas** [comment]
I am running this as such, my configuration setting
 ```
 {
	"name": "Run Tracking-Server",
	"protocol":"inspector",
	"type": "node",
	"request": "launch",
	"console": "integratedTerminal",

	// Works if you open in VS Code the folder that contains all cchome repos
	"runtimeExecutable": "${workspaceRoot}/node.sh",
	"program": "${workspaceRoot}/src/app.js"
},
```

my node.sh file
```
#!/bin/bash
source ~/.bash_profile
nvm run $*
```
and finally my .nvmrc
```
7.10.1
```

**Comment by guycnicholas** [comment]
Ah, I just changed my .nvmrc file to set it to 8.9.4 and it works there, but when I switch it back to 7.10.1 it fails.

**Comment by weinand** [comment]
Thanks, I can reproduce with node.js < 8.0.

BTW, if you are using **nvm**  you can just add `"runtimeVersion": "7.10.1"` to your launch config to delect the node.js version to use.

**Comment by guycnicholas** [comment]
Thanks for the tip...I am not sure where I came across the other, but your way is far simpler.
