### ISSUE TITLE
... hint indicator should only show on first line of suggestion

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#47346]
**Steps to reproduce**

For the JS:

```js
module.exports = function() {
    
}
```

**Bug**

![screen shot 2018-04-06 at 11 16 07 am](https://user-images.githubusercontent.com/12821956/38437335-f53eeb7c-398b-11e8-91ed-a3eaf8262e0c.png)

`...` shown on all lines. It should only show on the first line

**Comment by jrieken** [comment]
We can fix that in the editor, maybe ;-)

**Comment by nagarjun** [comment]
@jrieken 👏 Is this going to make it to the next release? It's SUPER annoying.

**Comment by jrieken** [comment]
Yep, should be in insiders today and with be part of the 1.22.2 recovery release.

**Comment by unlucio** [comment]
it would be grate if this was opt-in rather than confusing out of the box :)

**Comment by jrieken** [comment]
@unlucio  it is, see https://code.visualstudio.com/updates/v1_22#_suggestion-code-actions-for-javascript-and-typescript

**Comment by jrieken** [comment]
@alexandrudima reviewed the change, @mjbvz Can you verify please, thanks
