### ISSUE TITLE
Error to push to a singular branch '+(branch_name)'

### ISSUE THREAD

**Issue by vvbv** [Microsoft/vscode#47347]
- VSCode Version: 1.22
- OS Version: Debian 9

Steps to Reproduce:

1. Create a branch with a plus in first position of the name, for example, +-FIX-some
2. Try to push to that branch using VSCode

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by joaomoreno** [comment]
> Try to push to that branch using VSCode

And then what happens? Error? A little screenshot would help.

**Comment by vvbv** [comment]
<img src="https://i.imgur.com/CVez28t.png"/>

**Comment by laurinenas** [comment]
I get the same results using git in terminal.
TIL, leading [plus symbol in refspec has a special meaning in git](https://git-scm.com/docs/git-push).

It would be nice if you could you tell what is expected behaviour and what are we testing here?

**Comment by joaomoreno** [comment]
> TIL, leading plus symbol in refspec has a special meaning in git.

Interesting.

My two cents: just don't create such branches.

**Comment by vvbv** [comment]
GitHub has no problem pushing to such branches, you can see the commits log of this branch https://github.com/vvbv/test/tree/+-TEST
