### ISSUE TITLE
Hint dots are very distracting and not ignorable

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#47344]
- VSCode Version: 1.22.1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Open a .js file that uses `module.exports = function() {}`

Does this issue occur when all extensions are disabled?: Yes

See screenshot attached. It would be nice to have an "Ignore" option in the menu, to ignore this particular suggestion forever.

![image](https://user-images.githubusercontent.com/12532733/38435635-da20bc1a-3997-11e8-9274-add08641935d.png)

**Comment by mjbvz** [comment]
Add `"javascript.suggestionActions.enabled": false`  to your user settings to disable these. We'll be looking into suppressing individual types of suggestions in the future
