### ISSUE TITLE
DebugAdapter bin folder not found on path xxx

### ISSUE THREAD

**Issue by minggo** [Microsoft/vscode#4735]
- VSCode Version: 0.10.11
- OS Version: Windows 7 Ultimate

I am writing a debug adapter, and deploy it by coping needed files into 
* Windows: `%USERPROFILE%\.vscode\extensions`

When i want to debug the program, then i met the error said `DebugAdapter bin folder not found on path C:/Users/elin/.vscode/extensions/cocos-debug/out/cocosFXDebug.js.`. But it works ok on Mac OS X. package.json is 

```
{
	"name": "cocos-debug",
	"displayName": "Cocos Debug",
	"version": "0.0.1",
	"publisher": "chukong technology",
	"description": "Debugger for cocos JSB programs",
	"author": {
		"name": "Chukong technology"
	},
	"engines": {
		"vscode": "^0.10.1"
	},
	"categories": [
		"Debuggers"
	],
	"private": true,
	"dependencies": {
		"vscode-debugadapter": "1.6.0-pre12",
		"vscode-nls": "^1.0.4"
	},
	"devDependencies": {
		"typescript": "^1.6.2",
		"mocha": "^2.3.4"
	},
	"scripts": {
		"prepublish": "tsc -p ./src",
		"watch": "tsc -w -p ./src"
	},
	"contributes": {
		"debuggers": [
			{
				"type": "cocos",
				"label": "Cocos-JSB",
				"enableBreakpointsFor": { "languageIds": [ "javascript" ] },
				"program": "./out/cocosFXDebug.js",
				"runtime": "node",
				"configurationAttributes": {
					"attach": {
						"properties": {
							"port": {
								"type": "number",
								"description": "Debug port to attach to. Default is 5086.",
								"default": 5086
							},
							"cwd": {
								"type": "string",
								"description": "Absolute path to the working directory of the program being debugged.",
								"default": "${workspaceRoot}"
							},
							"address": {
								"type": "string",
								"description": "The TCP/IP address of the port (remote addresses only supported for node >= 5.0). Default is 'localhost'.",
								"default": "localhost"
							},
							"timeout": {
								"type": "number",
								"description": "Retry for this number of milliseconds to connect to the cocos JSB program. Default is 10000 ms.",
								"default": 10000
							}
						}
					}
				},
				"initialConfigurations": [
					{
						"name": "Cocos-Debug",
						"type": "cocos",
						"request": "attach",
						"port": 5086,
						"address": "localhost",
						"cwd": "${workspaceRoot}"
					}
				]
			}
		]
	}
}
```

**Comment by minggo** [comment]
@weinand Could you please take a look? Is there anything specific requirements on Windows?

**Comment by weinand** [comment]
@isidorn the package.json looks good to me. Do you have an idea what's wrong here?

**Comment by minggo** [comment]
@isidorn Is there any clue of this issue? Please let me know if you need any more information. Thanks.

**Comment by isidorn** [comment]
@minggo @weinand package.json looks good to me as well. Our node debugger is using the same principal and all works fine.
There are no specific requirments on Windows.

Are you sure that path exists on your machine?
What happens if you open command prompt and do the following
```
node
fs.exists('C:/Users/elin/.vscode/extensions/cocos-debug/out/cocosFXDebug.js', (exists) => console.log(exists))
```

**Comment by weinand** [comment]
@iamchenxin  who generates the message `DebugAdapter bin folder not found on path`? This makes no sense because why should a 'bin' folder on the path?

**Comment by minggo** [comment]
Sorry, it is my fault. Because my Windows machine hide file types, so i copied `cocosFXDebug.js.map` into extension.

**Comment by isidorn** [comment]
@weinand we generate that message on the vscode side. I agree we should improve the message, how about
`Debug adapter not found on the following path: {0}`

**Comment by weinand** [comment]
@isidorn "not found on the path" is misleading because it sounds like "not found on the search PATH that you should configure in your profile". We should just say: `Debug adapter executable '{0}' not found`
