### ISSUE TITLE
Checkboxes in Search Panel instead dissmis "x" buttons

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#47351]
I propose add checkboxes in Search Panel instead dissmis "x" buttons.

When you click "x" there is no return, just a slight mistake.
Checkboxes would give much more control.

Alternatively, you can give both: "checkboxes" and "x" buttons.

**Comment by roblourens** [comment]
I think the main benefit of the 'x' is that it actually hides the result so you can focus on the remaining ones. I think checkboxes wouldn't be as useful.

I'd prefer being able to undo the 'x' button with cmd+z. What do you think about that?

**Comment by lukaszpolowczyk** [comment]
@roblourens This is true, but simultaneously it causes a problem, because you can not undo such a thing.

So to preserve the advantages of both, you can give the left checkboxes and the right x buttons (as it is).

Everyone will benefit from what is more convenient to him at the moment.

**Comment by roblourens** [comment]
I'm not convinced, I think checkboxes would be noisy and only useful for a small number of people.

**Comment by roblourens** [comment]
Which editors have a feature like this?

**Comment by lukaszpolowczyk** [comment]
@roblourens Brackets. I think I saw it in some other one too.
![zrzut ekranu z 06-04-2018 23_37_47](https://user-images.githubusercontent.com/16800535/38445364-91c3efbc-39f3-11e8-8df8-c083d26952ab.png)

**Comment by roblourens** [comment]
I'll leave it open as a UI idea but I'm not crazy about it.
