### ISSUE TITLE
Buttons to hide errors and/or warnings and/or infos in Problems Panel  - like in browsers devTools console

### ISSUE THREAD

**Issue by lukaszpolowczyk** [microsoft/vscode#47354]
I propose buttons to hide errors and/or warnings and/or infos in Problems Panel - like in browsers devTools console.

**Comment by moocat** [comment]
I've started using VS Code with Java, which displays TODOs as infos, so an ability to easily hide the infos in the Problems Panel would indeed be extremely helpful.

**Comment by fatfatson** [comment]
+1

**Comment by HarveyTvT** [comment]
NEED THAT TOO!
currently im working on java projects with vs code, but it keeps warning me (600+ times) that a class does not declare serialVersionUID...

**Comment by Mike-the-one** [comment]
I need this too!!!!

**Comment by Matix-Media** [comment]
Me too ^-^

**Comment by nbarbettini** [comment]
Working on a big C# codebase with a similar situation: plenty of warnings I'll eventually clean up, but for now I want to filter/hide those and only see errors. Visual Studio has separate toggles for info, warning, error - that would be a nice pattern here.

**Comment by ppmadalin** [comment]
I am looking forward to have this!!

**Comment by ezekielcodisto** [comment]
This feature is useful also if you are working on legacy code. In my case, I'm adding E4X code in my Javascript file and errors just pop up even though the code is really working upon running it.

**Comment by lfarkas** [comment]
this would be VERY useful and without it it's almost impossible to work on a large project

**Comment by plus2047** [comment]
This is very helpful for some python project with special tricks, which cannot be understood by IntelliSence.

**Comment by JettChenT** [comment]
need this too.

**Comment by sandy081** [comment]
One of the approaches to filter by type is shown below. Thanks @tfenster for the PR. Please try it out and provide us the feedback.

![image](https://user-images.githubusercontent.com/10746682/68393798-0549b100-016d-11ea-88d6-ff30740fda57.png)

**Comment by MeikTranel** [comment]
Is it possible to have specific buttons for Errors, Warnings and Infos instead of a dropdown?

As seen below on a "regular" 16:9 1080p monitor theres a lot of unused screenspace left to work with and specific button with a visible toggle state for each type would help avoid missing messages because one has forgotten to reenable all options for this. Visual Studio does do a great job with their implementation.
![image](https://user-images.githubusercontent.com/6466560/69217766-a6723780-0b6f-11ea-83f7-19f69816f6cc.png)

**Comment by sandy081** [comment]
Well, thought about that but not got approved in our UX.

**Comment by tfenster** [comment]
@sandy081 as you know, I would also prefer separate buttons. Would an implementation with a setting "show separate buttons" (default false) have a chance to get past your UX team?

**Comment by sandy081** [comment]
I would probably wait for the feedback before rushing/

**Comment by tfenster** [comment]
sure, I wouldn't done anything before knowing whether it has a chance or not

**Comment by escape0707** [comment]
But this filter won't affect errors / warnings / infos counter, which is still pretty annoying.
Btw, I'm using imported classes source files from a book's website which their codebase have some deprecated usage of language standard libraries APIs.
