### ISSUE TITLE
integrated terminal crashes clang

### ISSUE THREAD

**Issue by EvanMcGorty** [Microsoft/vscode#47352]
Issue Type: <b>Bug</b>

compiling c++ code that has errors with clang 6.0 in the integrated terminal often causes clang to start printing garbage from memory and crash. this only happens with the integrated terminal. when the c++ code compiles correctly with gcc or msvc, clang works fine. i suspect this problem has to do with my small amount of ram.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.93GB (4.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
language-haskell|jus|2.4.0
vscode-clang|mit|0.2.2
python|ms-|2018.3.1
cpptools|ms-|0.16.1
java|red|0.22.0
rust|rus|0.4.1
gitconfig|sid|1.0.1
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0

</details>

**Comment by Tyriar** [comment]
This is likely the same root cause as https://github.com/Microsoft/vscode/issues/36630
