### ISSUE TITLE
[Proposal] Source Control panel - filter and Tree view mode

### ISSUE THREAD

**Issue by pmunin** [Microsoft/vscode#47358]
**PROBLEM:**
There is often a need to commit one particular folder with changes, but it's not easy to find it in Source Control panel when I have a lots of other changes

There should be a easy way to perform source control operations (e.g. staging changes) on a specific folder in a repository.

**Suggested solution:**
Here are the desired features sorted by the need:
- (must have) in Source Control panel: filtering list of changed files by full path
- (must have) in Source Control - tree view mode, that shows changed files as a tree with folders (instead of listview)
- (nice to have) in File Explorer: integrate source control actions (e.g. staging) on changed files and folders with those files into Context Menu (like in Solution Explorer in Visual Studio)

**Comment by joaomoreno** [comment]
- #30199
- #14582

Please open a new issue for the third one. Please keep separate issues for separate feature requests/bugs.
