### ISSUE TITLE
Trouble to Edit or write new code

### ISSUE THREAD

**Issue by vernypv** [Microsoft/vscode#47357]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by vernypv** [comment]
I’m having trouble when I try to edit or just write a new code. Have I install any extension in order to be able to edit or write a new line of code? Could you please help with this issue?

**Comment by roblourens** [comment]
Please include as many details as possible about exactly what you are trying to do.
