### ISSUE TITLE
Symbol lookup error: _ZN6icu_588ByteSink15GetAppendBufferEiiPciPi

### ISSUE THREAD

**Issue by igorvolnyi** [Microsoft/vscode#47365]
- VSCode Version: 1.22.1 official, 1.23 insiders (code-insider-1.23.0-1523004716_amd64)
- OS Version: Arch Linux (x86_64)

Steps to Reproduce:

1. /path/to/project $ code .
2. Error displayed immediately:
/opt/visual-studio-code/bin/../code-insiders: symbol lookup error: /opt/visual-studio-code/bin/../code-insiders: undefined symbol: _ZN6icu_588ByteSink15GetAppendBufferEiiPciPi

The symbol ByteSink::GetAppendBuffer is defined in libicuuc.so (v61.1 at the moment).
When I launch
$ ldd /opt/visual-studio-code/code-insiders
there is no /usr/lib/libicuuc.so in the list. Looks like the program is linked without libicuuc, though I don't understand how it could happen.

Does this issue occur when all extensions are disabled?: Yes

Version 1.21.1 didn't have this issue.

**Comment by igorvolnyi** [comment]
Looks like the problem is SOLVED. There was a rogue installation of nwjs in /opt on my system. Removed /opt/nwjs and all work again. My bad. Sorry.

**Comment by roblourens** [comment]
Glad you figured it out, thanks for the follow up.

**Comment by Pranz** [comment]
I have this exact same issue, except I don't have an install of nwjs.

**Comment by igorvolnyi** [comment]
It is not necessarily nwjs. Probably somewhere in your system (more specifically in $LD_LIBRARY_PATH) there's some other dynamic library that does not contain the symbol.
Of course I'm talking about Linux.
