### ISSUE TITLE
Option to Disable Save All on Search/Replace

### ISSUE THREAD

**Issue by chyndman** [Microsoft/vscode#47366]
Issue Type: <b>Feature Request</b>

Would like to be able to disable the recently-added ability to save all on search/replace. In my case this is because files in my workspaces are read-only by default.

VS Code version: Code 1.22.0 (6b4d53cdab8bcae1eaaa4934d93c077319b573db, 2018-04-05T17:27:42.363Z)
OS version: Windows_NT x64 10.0.15063

**Comment by roblourens** [comment]
Why are you trying to do a search/replace if the files are readonly?

**Comment by jiayihu** [comment]
I'm asking for the same feature but for different reasons. Before saving the changes I'd like to check all the replacements, specially because there's no way (AFAIK) to undo the replace-all action.
