### ISSUE TITLE
Intellisense doesn't work on installed Python libraries

### ISSUE THREAD

**Issue by julKali** [Microsoft/vscode#47360]
It seems that Intellisense does recognize pip-installed libraries itself and if you do the following:

``import matplotlib.[press ctrl-space to trigger Intellisense]``

it loads a moment and then provides correct subpackages.

But if I try to use the lib in my code like this:

``matplotlib.[press ctrl-space to trigger Intellisense]``

it doesn't show anything except for the usual stuff it generates from the file's content

Weirdly, if I hover above matplotlib, it does show me information about the module...

Note that I use vscode insider:

- VSCode Version: 
1.22.0-insider
6c22e21cdcd6811770ddcc0d8ac3174aaad03678 (<- not sure if this is the version commit, it show up in ``vscode-insider --version``)
x64
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Create py file
2. ``import matplotlib/numpy/scipy``
3. no Intellisense shows up when trying to access methods

Does this issue occur when all extensions are disabled?: No (ofc, it needs at least the Python extension)

Glad about any help/information about how to fix this issue!

**Comment by gate3** [comment]
Intellisense is not actually working in general after the latest update on my end

**Comment by julKali** [comment]
Okay so it doesn't seem to be a problem of misconfiguration, that's nice to hear! Do you know when this will be fixed?

**Comment by mjbvz** [comment]
Can you please file this issue against the python extension
