### ISSUE TITLE
backup my extensions : 

### ISSUE THREAD

**Issue by gogoIsComing** [Microsoft/vscode#47364]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

hey guys : 
i just want to know if there is any way to backup my vscode extensions in case i uninstalled vs code

**Comment by ImKK-000** [comment]
You can try to use [settings-sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) on vscode extensions. You can upload and download your settings from secret gist or public gist.
