### ISSUE TITLE
Formatting JSON removes blank lines

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode#47361]
This is a copy of #37422.

Installing prettier doesn't solve the problem and using `"json.format.enable": false` removes the option to format the document.

You can easily test it with the settings file.

// edit using beautify also is the same, except you can manually select beautify file.

**Comment by OneOfOne** [comment]
Using prettier now, `"prettier.jsonEnable": [ "json", "jsonc" ],` fixes the problem.

**Comment by roblourens** [comment]
I think that using prettier is the best solution.
