### ISSUE TITLE
[javascript]wrong syntax highlight in ternary operator

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#47377]
Issue Type: <b>Bug</b>

The colons  should be the same highlight, but in the following picture they are different.
![javascript](https://user-images.githubusercontent.com/24318019/38452794-cd3f0f74-3a7d-11e8-8557-21824d939371.png)

VS Code version: Code - Insiders 1.23.0-insider (95101bf3f6d00105621cdddb639ea62b95ea2468, 2018-04-06T08:49:48.798Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.3.0

</details>

**Comment by roblourens** [comment]
I see it in Dark+

```ts
function f() {
    return foo ? { a: true } : { b: false }
}
```

**Comment by roblourens** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#595
