### ISSUE TITLE
Add 'scroll past the end' feature for the integrated terminal

### ISSUE THREAD

**Issue by abhishekBM4576** [Microsoft/vscode#47373]
It really sucks when I have to type commands on the bottom of terminal and I can't really see the outputs clearly. Scroll past the end feature in the terminal will make it easy to use, just like the editor.

**Comment by Tyriar** [comment]
AFAIK no terminals act like this, I think there's also a good reason for this as applications can modify the entire viewport, not just the last line. No plans to implement now.
