### ISSUE TITLE
When using integratedTerminal with bash (WSL) vscode fail to detect directory

### ISSUE THREAD

**Issue by VicoErv** [Microsoft/vscode#47378]
- VSCode Version: 1.21.1
- OS Version: Windows 10 1709

Steps to Reproduce:

1. set integratedTerminal to bash
2. set up launch.json with windows path
3. debug

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
We are working on this...

**Comment by DarthSpock** [comment]
Would Microsoft/vscode@2e76670 help with this (assuming this is still an issue)

**Comment by weinand** [comment]
How does the launch config look like?
