### ISSUE TITLE
Allow column selection to be manipulated after other actions

### ISSUE THREAD

**Issue by cpmcgrath** [microsoft/vscode#47372]
Issue Type: <b>Feature Request</b>

If I have say 4 rows selected with column selection, then i do something with them, let's say just hit the right arrow to move all selections one char over, and then I use shift ctrl alt down, it would be great if this expanded the selected columns so that 5 rows were selected. Instead it currently just acts like the existing column selection isn't there, starts again and results in 2 columns being selected.

Example:
Start State:
![image](https://user-images.githubusercontent.com/1791243/38450557-4112d52c-3a63-11e8-8bc4-f499761947cf.png)
Current State after move caret right and a cursorColumnSelectDown:
![image](https://user-images.githubusercontent.com/1791243/38450573-a8bf8260-3a63-11e8-84de-9d52b19598b6.png)

Proposed state after move caret right and a cursorColumnSelectDown:
![image](https://user-images.githubusercontent.com/1791243/38450576-bdfd6426-3a63-11e8-8b0b-5c2da6257838.png)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by alexandrudima** [comment]
The problem is that pressing arrow right means `cursorRight` will execute, which is implemented to wrap in edge cases (such as when being at the end of a line). This goes against the way column selection works, which never wraps to the next lines. Therefore, the `cursorRight` command resets the internal column selection state.

A workaround would be to use regular multicursor (not column selection) i.e. add cursors via `editor.action.insertCursorBelow` and then use `cursorRight` as usual.

**Comment by cpmcgrath** [comment]
The cursorRight was really just an example with the simplest case I could think of.

A more real example would be you have a list of words, one per line, which you want to turn into a quoted list of strings. you do the column select at the start, press " hit the end key to get to the end of the line, hit " again, then you want to add a comma on all but the last, so you do a cursorColumnSelectUp, expecting it to just lose the last, and it instead changes the selection to the first and the line before it.

Yes, the cursor column can wrap, but I don't think that really changes anything. The program should have the "Most active" cursor instance (the last place it was expanded to) and if the up down moves away from the selection it should expand the selection to include the row below at the cursor location of the last instance, if it moves towards the selection it should remove the most active from the selection. 

This just makes the feature feel much more fluid, instead of having to restart whenever you want to slightly change the selection.
