### ISSUE TITLE
Please make code folding for c languages take up only 1 line

### ISSUE THREAD

**Issue by Shadowblitz16** [Microsoft/vscode#47371]
please make code folding only take up 1 line when folding with c languages
so something like this..
`if (condition)
{
    stuff
}`

looks like this when folded
`if (condition) {...}`

**Comment by roblourens** [comment]
It does fold to a single line, right? Which language are you trying?

**Comment by Shadowblitz16** [comment]
action/angel script but it uses c style {} code blocks

**Comment by roblourens** [comment]
Can you post a code example? Are you using an extension for that language?

**Comment by Shadowblitz16** [comment]
no its just c syntax, just a sec
this is what it looks like..
`
if (condition)
{...

}
`

**Comment by aeschli** [comment]
duplicate of #3352
