### ISSUE TITLE
Can't split to the side

### ISSUE THREAD

**Issue by ChacaS0** [Microsoft/vscode#47389]
Issue Type: <b>Bug</b>

When I try to put a tab on the side, I just can't any more. It is only possible to split horizontally.

*Demo:*
![Can't split vertically - demo](https://image.ibb.co/mgET2H/bug_split_to_the_side.gif)

**[+] (Using VirtualBox)**

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.15.14-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (2 x 2399)|
|Load (avg)|2, 1, 1|
|Memory (System)|3.86GB (0.29GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.5.1
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.2.6
vscode-docker|Pet|0.0.26
go-test-outline|Rom|0.2.0
better-comments|aar|1.2.1
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.2
vscode-color|ans|0.4.5
toml|be5|0.0.3
emojisense|bie|0.4.0
vscode-remind-me|cg-|0.0.3
vscode-svgviewer|css|1.4.3
jquerysnippets|don|0.0.1
gitlens|eam|8.2.0
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.5.1
php-debug|fel|1.12.2
php-intellisense|fel|2.3.1
vsc-travis-ci-status|fel|1.1.0
auto-close-tag|for|0.5.6
docker-explorer|for|0.1.6
docker-extension-pack|for|0.0.1
terminal|for|0.0.10
vscode-git-tags|how|1.3.1
vscode-circleci|jva|0.5.0
iris|kat|0.0.4
git-indicators|lam|2.1.1
ftp-sync|luk|0.3.3
Go|luk|0.6.78
prettify-json|moh|0.0.3
mssql|ms-|1.3.0
makefiles-support-for-vscode|nae|0.0.3
java|red|0.22.0
todotasks|san|0.5.0
jenkinsfile-support|sec|0.1.0
git-merger|sha|0.3.7
bootstrap4-vscode|the|4.1.1
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0
vscode-todo-highlight|way|0.5.12
bootstrap-3-snippets|wcw|0.1.0

(4 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
Editor can only be split horizontally **or** vertically and it remembers current mode. 
`workbench.action.toggleEditorGroupLayout` command toggles it. 
(`View: Toggle Editor Group Vertical/Horizontal Layout` from command palette)

**Comment by ChacaS0** [comment]
Ty I'm so dumb :joy_cat:

**Comment by usernamehw** [comment]
It's not entirely obvious now. Hopefully it will be better after #14909 is implemented.
