### ISSUE TITLE
[jade] comments have string color

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4738]
1. Open a .jade file (e.g. there is one in our vscode smoke test repo) 
2. Comment out a line - notice the comments are blue or orange (dark theme) which are usually the colors we use for strings
3. I would expect green, the same we use for other languages

This behavior is like this for a while, so I do not think it is important.

**Comment by aeschli** [comment]
Jade uses scope `string.comment.buffered.block.jade` for these comment, so it's rather random if this is a string or a comment. 
I also think it's minor so for now I would not start customizing our theme for Jade.

**Comment by aeschli** [comment]
This issue was moved to davidrios/jade-tmbundle#88
