### ISSUE TITLE
Add indeterminate progress display

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#47387]
Thanks for the new progress indicator implementation, it's a very welcomed feature. However, I'm missing an indeterminate style for operations that cannot give progress pings (like running an external Java tool). Can you please add that yet?

**Comment by yume-chan** [comment]
I think if you never call `progress.report` it will display as indeterminate style?

**Comment by mike-lischke** [comment]
It would be good to use a different indicator style too, like a spinning wheel or similar, instead of style used for normal progress indicators.

**Comment by bpasero** [comment]
Yes, just never report the progress with percentage and the progress will be intermediate.

**Comment by mike-lischke** [comment]
Can you at least add a note to the documentation about this fact? Thanks.
