### ISSUE TITLE
Improve colorization of TypeScript generics

### ISSUE THREAD

**Issue by feafarot** [Microsoft/vscode#47385]
Issue Type: Improvement

Add the generic type parameter exclusive scope to make able to correctly colorize generic type parameters.
I'm trying to achieve separate generic type parameters color like it is in Visual Studio for C#. now it seems impossible to do so because tokens are the same for actual types and generic types (in method and class definitions).

Actual behavior:
![Generic Type](https://user-images.githubusercontent.com/2183846/38454268-7a95c062-3a6c-11e8-9226-72dcaa261202.png)
![Existing Type](https://user-images.githubusercontent.com/2183846/38454269-7ab2691a-3a6c-11e8-8511-3148f9bdc100.png)
Where `A` is actual class defined in the file above.

Same applies to methods and functions declarations.
![Generic Type](https://user-images.githubusercontent.com/2183846/38454292-077ac6b2-3a6d-11e8-9ac3-ed36fb098f46.png)
![Existing Type](https://user-images.githubusercontent.com/2183846/38454293-0796c54c-3a6d-11e8-8474-073f36927c2d.png)

With existing scopes in given situation, it's impossible to split colors between generic types and actual types.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#596
