### ISSUE TITLE
workspace.findFiles throws an error in there are no opened folders

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#47388]
Running the following:

```typescript
await vscode.workspace.findFiles ( '**/*' )
```
in a new window without opened folders throws the following error:

```
TypeError: Cannot read property 'map' of undefined
```

I guess `findFiles` is probably not handling properly the case where there are no folders opened.

This is breaking existing extensions: https://github.com/fabiospampinato/vscode-diff/issues/1.

An empty array should be returned instead.

**Comment by kennyle1412** [comment]
Sorry for the spam. I forgot my commits reference this issue. :x

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostWorkspace.ts#L365 `data` can be undefined from https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadWorkspace.ts#L103, not sure which is wrong.

**Comment by kennyle1412** [comment]
Yes it's findFile that's not accounting for undefined data. https://github.com/Microsoft/vscode/blob/3fbfccad359e278a4fbde106328b2b8e2e2242a7/src/vs/workbench/api/node/extHostWorkspace.ts#L365

My `!workspace` 'fix' just let the function run and build a not-undefined search haha. I knew something was wrong with it.

**Comment by kennyle1412** [comment]
@melMass `return result.then(data => !data ? [] : data.map(URI.revive));`Is that what you mean? If you're talking about a workaround in the extension without a fix in findFiles then I'm not really sure. Maybe have a if statement to check if folders exist beforehand or not.
