### ISSUE TITLE
Please add select word shortcut under cursor (Ctrl+W in vs)

### ISSUE THREAD

**Issue by lferrao** [Microsoft/vscode#47391]
I know this can be achieved by the best finger acrobats among us by CTRL LEFT SHIFT CTRL RIGHT, but for anyone else it would be nice to have this feature. It's the equivalent of double clicking a word.

**Comment by usernamehw** [comment]
`editor.action.addSelectionToNextFindMatch` ? <kbd>Ctrl</kbd>+<kbd>D</kbd>

**Comment by lferrao** [comment]
Not the same but I guess this could do the trick, I'll try using it for a few days

**Comment by roblourens** [comment]
I think this is essentially what ctrl+d does, or try "expand select".
