### ISSUE TITLE
Flag to have extension host tag global variables by extension

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#47396]
- VSCode Version: 1.22.1  
- OS Version: Windows 10  

Steps to Reproduce:

1. Two extensions define the same global variable name
2. Everything breaks

When debugging this problem I would like to be able to see which extension created the other variable, I thought maybe some debug flag could be added which would make the extension host inject the extension name into all global variables. 

A better solution would be to have all global variables scoped per extension, but im not sure that is possible in the current architecture

**Comment by weinand** [comment]
@CoenraadS instead of using variables, you can just use commands (which typically use ids that are fully qualified by the extension id).

**Comment by CoenraadS** [comment]
I'm not sure I understand, allow me to elaborate my situation:

Extension foo:

`import * as prism from 'prismjs';`

Extension bar:

```
const Prism = require('prismjs/components/prism-core.js');
const loadComponents = require('prismjs/components/index.js');
```

If I try accessing `Prism` in extension `bar`, I get the object from `foo`.

I solved it my moving the requires from `bar` into a class which then scoped correctly, but it was still a hard problem for me to solve because I never expected my code to be affected by other extensions.

**Comment by weinand** [comment]
Oh, I misunderstood your problem.

**Comment by roblourens** [comment]
I tried this and I don't see exceptions from Bracket Pair Colorizer. I see some warnings `"No editors associated with document: ..."`

Why do you think they are sharing variables? Those are not global variables in Node, they are inside the module defined by the file. The extensions are not sharing variables or node_modules or anything.

**Comment by CoenraadS** [comment]
@roblourens 

Could you please verify you have auto-update extensions disabled.

I can reproduce this 100% with BracketPair 1.0.21 linked above and subtle match brackets 2.1.1

![image](https://user-images.githubusercontent.com/5593825/38481705-67930072-3bcc-11e8-8702-a7024cdda051.png)

Many of my users hit this also: https://github.com/CoenraadS/BracketPair/issues/98

**Comment by roblourens** [comment]
Ah you were right about extension autoupdate. It seems to be because the two extensions include different versions of the Prism node module, but I can't figure out why that's a problem. It loads scripts that look like

```js
Prism.languages.javascript = Prism.languages.extend('clike', {
[...]
```

And `Prism` is like a global, but I didn't think that was possible in Node - it should have to require or export something explicitly. I don't understand how Prism is being shared between files...

**Comment by roblourens** [comment]
Oh, it's just that they assign it to `global`: https://github.com/PrismJS/prism/blob/gh-pages/prism.js#L561

And then any reference to `Prism` uses that version, even if it isn't explicitly referencing `global.Prism`.

PrismJS should not do that. I don't know whether it's even possible for us to work around it...

**Comment by jrieken** [comment]
Yeah, but it is too late for that change.

**Comment by roblourens** [comment]
Why? It shouldn't break anyone. I guess there might be a perf impact.

**Comment by jrieken** [comment]
> Why? 

Because there might be extensions relying on the shared nature of node-modules. Knowing or unknowingly.

**Comment by roblourens** [comment]
:(

@CoenraadS I don't think we can do anything, I hope you can follow up with the PrismJS maintainers to not use global state.
