### ISSUE TITLE
Unable to load anything inside the VS Insiders window

### ISSUE THREAD

**Issue by noopman** [Microsoft/vscode#47397]
My VS Insiders window loads, but then nothing. I can't get any dialogue when I say "open folder", "new file" does nothing, etc. It's like I only get an empty window and nothing more. I have tried reapplying the installer, uninstalling/reinstalling, rebooting. Nothing is happening at all in my program. I get the main window, empty, and nothing more.

- VSCode Version: 1.23.0-insider
- OS Version: 10.0.16299 N/A Build 16299

Steps to Reproduce:
1. I just start VS Code Insiders and... nothing.

Does this issue occur when all extensions are disabled?: How do I launch insiders with extensions disabled?

**Comment by roblourens** [comment]
- Did you just install it? Did it work before?
- Can you give a screenshot?
- Do you see any errors in the developer tools (Help > toggle developer tools)

**Comment by noopman** [comment]
Right, forgot to say, sorry. VS Code Insiders has been working on my machine for a long time and I have updated it frequently. The screen shot does not make for very interesting viewing. It's the program frame and no content. (attached) No matter how I start the program now this is the only result I can get.

![2018-04-08_01-45-30](https://user-images.githubusercontent.com/300622/38461393-9e4486f8-3ace-11e8-9bb8-5b3fa4c24604.png)

**Comment by roblourens** [comment]
- Do you see any errors in the developer tools (Help > toggle developer tools)
- If you start from the command line with --verbose do you see any errors?

**Comment by noopman** [comment]
Yup there are errors, 14 of them, in the developer tools window.
When I launch with --verbose I get some funny messages:

C:\Users\Magnus>
[main 2:25:36 AM] Sending env to running instance...
[main 2:25:36 AM] Sending some foreground love to the running instance: 19148
[main 2:25:36 AM] Sent env to running instance. Terminating...
[main 2:25:36 AM] Lifecycle#kill()

**Comment by roblourens** [comment]
> Yup there are errors, 14 of them, in the developer tools window.

Well what are they? :)

**Comment by roblourens** [comment]
You can send it to the email in my profile or redact it however you wish.
