### ISSUE TITLE
CSS Colon expected inside style attribute

### ISSUE THREAD

**Issue by ShlomiRex** [Microsoft/vscode#47398]
![untitled](https://user-images.githubusercontent.com/17744127/38458700-c3102cb4-3aa9-11e8-92cc-94699e5c1f59.png)

I have problem with the vscode showing error at style attribute in div element.
I currently have 0 extensions.

**Comment by usernamehw** [comment]
Maybe you wanted to use `type` attribute?

**Comment by roblourens** [comment]
The 'style' attribute expects CSS, so I thin you meant `type` or something else.
