### ISSUE TITLE
No autocompletion from .d.ts files inside node_modules for JavaScript projects

### ISSUE THREAD

**Issue by Mitko-Kerezov** [Microsoft/vscode#474]
Autocompletion from .d.ts definition files placed in node_modules directory works just fine for TypeScript projects (projects which have a .tsconfig file).
It even works for JS-based projects if one has .d.ts files inside the project. However if the definition files are placed inside node_modules directory in a JS-based project VS Code doesn't seem to pick them up.

**Comment by jrieken** [comment]
As we now ship with project Salsa this should work.
