### ISSUE TITLE
Code folding no longer works by indentation

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#47404]
- VSCode Version: 1.22

After updates to code folding, now it is not possible to use indentation level folding.
This is still very useful as I have written an extension around the original behavior which provides a much better experience to code folding.
https://marketplace.visualstudio.com/items?itemName=dakara.dakara-foldplus

However, this extension is now broken.
I see potential options:

- Provide an option to still use indentation level folding
- Provide additional API's that would allow my extension to work with syntax folding.  It would require API's to know the level of any particular line and the folding region.

**Comment by yume-chan** [comment]
There is a new setting `"editor.foldingStrategy": "indentation"` to get back the old behavior.

**Comment by T-Specht** [comment]
I really like the idea of having syntax-aware folding, but I think it's important to keep some of the "indentation folding logic" as well.
If you have a look at ES6 template strings, for example, they cannot be folded with the new strategy which is a no-go in my opinion and the reason I am switching back to the old strategy. 
Ideally, the syntax-aware folding should go on top of of the indentation based one, so indentation based folding works the same as always with the added bonus of the syntax-aware folding.

**Comment by dakaraphi** [comment]
In regards to the setting `editor.foldingStrategy`, thanks this is helpful; however, in #46944 it seems this may only be temporary.  I would like to see some clarification if indentation folding will continue to be supported.

@T-Specht Supporting combined strategies would be great; however, not sure if that is possible.  What happens when you have a conflict? Indentation folding for a line might fold differently than the folding defined for the language of the same line.

I think for my extension, I will add a command toggle to make it faster and easier to switch between the folding strategies.

**Comment by dakaraphi** [comment]
@T-Specht Thinking more about the combined strategies, I'm thinking it might actually be better if there was a new commands introduced called something like `Fold By Structure` instead of fold by level.  This would signify using the language defined folding.  Then both could be used at the same time.

**Comment by aeschli** [comment]
`"editor.foldingStrategy": "indentation"` is not going away.

API to access the folding level at a given line is currently not planed.
