### ISSUE TITLE
Application insights warnings in console

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4740]
- VSCode Version: 0.10.13-insider
- OS Version: Linux

Steps to Reproduce:

1. open vscode, work a bit on a repo (e.g smoke test)
2. notice application insights warnings in console

@egamma you mentioned that the telemtry seems to be broken, is this related?

![screen shot 2016-03-29 at 15 23 48](https://cloud.githubusercontent.com/assets/1926584/14109452/643b9080-f5c2-11e5-8d18-196f4a2619a7.png)

**Comment by Tyriar** [comment]
@seanmcbreen you mentioned there was some issues with telemetry too, do you think this could be related?

**Comment by Tyriar** [comment]
Haven't seen this personally since then, closing.
