### ISSUE TITLE
Fold All working only on some lines

### ISSUE THREAD

**Issue by andrewloable** [Microsoft/vscode#47409]
Issue Type: <b>Bug</b>

After updating to this latest version, whenever I do a Fold All (ctrl k ctrl 0), it seems vs code only folds the code under lines 1523. Anything above it is not folded and the fold markers on the left does not show up at all.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

![capture](https://user-images.githubusercontent.com/10375300/38461564-81437ce8-3b06-11e8-879d-535283fee643.PNG)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3600)|
|Memory (System)|15.93GB (9.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
dart-code|Dar|2.11.2
Go|luk|0.6.78
vscode-clang|mit|0.2.2
cpptools|ms-|0.16.1
java|red|0.22.0
html-preview-vscode|tht|0.1.1
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0

</details>

**Comment by mjbvz** [comment]
Please share a complete code example, not just a screenshot

**Comment by xlfsummer** [comment]
create a js file:
```javascript
() => {
    if (true) {
        //a
    } else {
        //b
    }
    //c
}
```

when move cursor to position "a", hit ctrl + shift + [
```javascript
() => {
    if (true)  { ...
        //b
    }
    //c
}
```

then move cursor to position "b", hit ctrl + shift + [
```javascript
() => { ...
```

what I expect is:
```javascript
() => { 
    if (true) { ...
    //c
}
```

**Comment by mjbvz** [comment]
Here's the folding I now see in vscode insiders:

<img width="260" alt="screen shot 2018-04-12 at 8 57 19 am" src="https://user-images.githubusercontent.com/12821956/38689105-8a4e1b28-3e2f-11e8-9f1a-18b1f5cca9fb.png">

Which looks correct to me. Folding the top level `if` only folds that block, not the entire if/else state

Try insiders and let me know if something still looks off
