### ISSUE TITLE
Searching installed extensions, doesn't use display name

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#47405]
I've got the [Ruby](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) and [Ruby Solargraph](https://marketplace.visualstudio.com/items?itemName=castwide.solargraph) extensions installed.

When I search with `@installed Ruby`, only Ruby appears, but Solargraph does not. Yet searching for `Ruby` (across the marketplace) shows both.

![ruby](https://user-images.githubusercontent.com/343940/38460658-532d60e6-3a8c-11e8-80a2-45e62e67dc95.png)

![solar](https://user-images.githubusercontent.com/343940/38460659-567cf306-3a8c-11e8-8fb3-2158f718c6c4.png)

![marketplace](https://user-images.githubusercontent.com/343940/38460664-6e10f97c-3a8c-11e8-9206-528eed90b3be.png)

**Comment by ramya-rao-a** [comment]
Note to verifier:
Also test the @outdated, @enabled and @disabled views
