### ISSUE TITLE
Right Click in Terminal Stops Updating Terminal Output

### ISSUE THREAD

**Issue by conman124** [Microsoft/vscode#47407]
Issue Type: <b>Bug</b>

(in linux)
Execute the command `sleep 5`.  Within 5 seconds, right click in the terminal.

Expected behavior:
After 5 seconds from the time you execute `sleep 5`, the prompt should reappear.

Actual behavior:
The prompt does not reappear after 5 seconds.  It appears as soon as you dismiss the right click menu.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor (6 x 2000)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.74GB (0.47GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.16.1

</details>
Reproduces with and without extensions

**Comment by Tyriar** [comment]
This is tracked in an issue already, it's related to Electron.
