### ISSUE TITLE
"Rename (F2)" operation should be invoking "git mv" if the file is versioned with Git

### ISSUE THREAD

**Issue by VioletGiraffe** [Microsoft/vscode#47402]
The "Rename (F2)" operation in the file explorer should be implemented as `git mv <old name> <new name>` if the file is under Git. Currently, the history of changes for this file breaks on rename - the old name is treated as deleted file and the new name as added file. `git mv` provides uninterrupted versioning history for renamed files or folders.

**Comment by mrchief** [comment]
AFAIK, this is a git issue, not editor's. See this [answer](https://stackoverflow.com/a/2641227/244353) for detailed explanation.

**Comment by VioletGiraffe** [comment]
An interesting note, but I'm not convinced. I did "Rename" in VS Code, and my Git GUI displayed the file as removed and added. I did not commit it, only looked at the status (but I cannot say which specific command the GUI uses for fetching the status). Then I reverted the changes, ran `git mv`, and the GUI immediately displayed the file as renamed.

**Comment by mrchief** [comment]
You just need a better GUI that displays the status properly. SmartGit does this now and so does Github, Gitlab etc. I'm sure others do too. 

GIT doesn't care about renames, nor does it matter. Once you stage the files, `git status` will also show the file as renamed, so as far as versioning history is concerned, there is no real concern. 

Rest is up to the authors...

**Comment by joaomoreno** [comment]
> Currently, the history of changes for this file breaks on rename

`git mv` renames and stages both changes. @VioletGiraffe Try renaming in VS Code, then staging the two changes.

Staging changes by renaming the file is not a good idea, it has been explained in other closed duplicate issues.
