### ISSUE TITLE
cmd+E (action.findWithSelection) does not work with multiple line selections

### ISSUE THREAD

**Issue by andyperlitch-turnto** [microsoft/vscode#47400]
- VSCode Version: 1.22.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Make a selection with a line break in it
2. Press `cmd+e` to invoke `action.findWithSelection`
3. Rather than fill the find field with text, it just puts focus on that field with whatever value was there before. **Note that when the selection does NOT span across a line break, `cmd+e`/`action.findWithSelection` works as expected.

Does this issue occur when all extensions are disabled?: Yes

![thing](https://user-images.githubusercontent.com/35234390/38460094-25843d64-3a68-11e8-8a09-38b465f20e4c.gif)

**Comment by rebornix** [comment]
IMO the problem here is we don't have a plain text multiline search support (other than regex) in the Find Widget, let's track it in https://github.com/Microsoft/vscode/issues/15727 .

**Comment by rebornix** [comment]
Verifier:

Firstly, test the existing behavior of `cmd+f` is not regressed. Create a text file with following text

```
const a = 0;

if (true) {
	const a = 0;	
}
```

* Make sure you have setting `"editor.find.autoFindInSelection": "never"`
* Move cursor to Line 1 Column 2, `cmd+f` should open the find widget, and the input is `const`
* Change setting `"editor.find.autoFindInSelection": "multiline"`
* Select all text in the document, `cmd+f` should have Auto Find In Selection turned on, and the input is still `const`
* Dismiss the find widget, run `cmd+e`, the find widget should be the same as before
* Change setting `"editor.find.autoFindInSelection": "never"`
* Select text of the first two lines
* `cmd+e` should open the find widget and the input is the text of the first two lines.

**Comment by rebornix** [comment]
The fix went in pretty late in this iteration, even though it fixes this issue, it leads to #109756 and it's not trivial to make it all correct. So I'll revert my fixes and look deep into this next iteration.

**Comment by rebornix** [comment]
Fixed via 6acc9ff1eeb155b66d0a1548c2eba395846b0802 with unit tests.
