### ISSUE TITLE
C# - Static class not recognized as accessible to newly created classes until VS Code is restarted.

### ISSUE THREAD

**Issue by keithdfox** [Microsoft/vscode#47414]
Issue Type: <b>Bug</b>

Example  static class:

`public static class Globals {
	
	public static class InputVals
	{
		public static bool overUI = false;
	}
	
}`

Now create a new class and attempt to access overUI:

`if (Globals.InputVals.overUI) { }`

**Globals** will then be underlined in red with the error:

> The name 'Globals' does not exist in the current context [Assembly-CSharp-firstpass, Assembly-CSharp-Editor-firstpass]

I can reproduce this 100% of the time.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|Memory (System)|7.89GB (3.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-power-mode|hoo|2.2.0
csharp|ms-|1.14.0
unity-debug|Uni|1.3.0

(12 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2161
