### ISSUE TITLE
Memory occupation is excessive

### ISSUE THREAD

**Issue by EricWong1992** [Microsoft/vscode#47415]
Issue Type: <b>Performance Issue</b>

My laptop only have 8G memory. Memory usage increased from 50% to about 70% when I opened my project. Hope you can solve this problem.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.85GB (1.15GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	 23192	code main
    0	    86	  6408	   shared-process
    0	    84	  6564	   powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
    0	     7	 23056	     console-window-host (Windows internal process)
    0	    85	  6840	   powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
    0	     7	 23300	     console-window-host (Windows internal process)
    0	    62	  7424	   shared-process
    0	   131	 19800	   gpu-process
    0	   141	 20208	   window (GameConst.lua - Documents - Visual Studio Code)
    0	    10	 12436	     watcherService 
    0	     5	 13788	       console-window-host (Windows internal process)
    0	    20	 15836	     searchService
    0	    10	 19860	     electron-crash-reporter
    0	    49	 22248	     extensionHost
    0	    21	 17012	       electron_node jsonServerMain.js 
    0	   184	 21760	   window (VMCity.lua - SLG - Visual Studio Code)
    0	    11	  6232	     watcherService 
    0	    10	 16468	       console-window-host (Windows internal process)
   14	   402	  9040	     extensionHost
    0	    38	 20596	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (GameConst.lua - Documents - Visual Studio Code)
|    Folder (Documents): 1672 files
|      File types: lua(810) svn-base(388) png(222) docx(60) csv(55) xlsx(35)
|                  dll(29) json(10) atlas(8) plist(8)
|      Conf files:
|  Window (VMCity.lua - SLG - Visual Studio Code)
|    Folder (SLG): more than 20000 files
|      File types: svn-base(16845) h(1124) cpp(918) lua(527) class(129) c(50)
|                  java(39) mk(37) mm(36) cmake(35)
|      Conf files: cmake(35) sln(2) makefile(2);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.14.1
beautify|Hoo|1.3.0
svn-scm|joh|1.28.0
python|ms-|2018.3.1
sublime-keybindings|ms-|3.0.3
guides|spy|0.9.1
vscode-todo-highlight|way|0.5.12
luaide-lite|wel|0.1.5

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
The extensionHost process on VMCity.lua stands out as using lots of memory. Is it better if you start with `--disable-extensions`? You might be able to figure out which extension is using lots of memory and see whether they have ideas. That workspace seems to have tons of files so you may not be able to improve it.

**Comment by EricWong1992** [comment]
I have checked all my extensions, and found that luaide-lite 0.1.5 takes a lot of memory for parsing all my lua files.  Memory usage reduced from 16% to 7% when I disable this extension. Thank you guys.
