### ISSUE TITLE
Make quick open start from last file (not current)

### ISSUE THREAD

**Issue by andybergon** [Microsoft/vscode#47413]
- VSCode Version: 1.22.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Open file `a` and then file `b`
2. Trigger `quickOpen` (`workbench.action.quickOpen`)
3. The cursor will be on the last opened file (`b`) that is you current file (but the most probable file you want to open is the last one, `a`)

This is the behaviour in IntelliJ and probably the most useful as you can go to your last open file doing `quickOpen` and `Enter`. The order of the list remains the same, the only thing that changes is that the starting cursor will be on the second element (last file).

Now:
![image](https://user-images.githubusercontent.com/5220825/38462920-36954fd4-3ae6-11e8-9fdf-92026339294b.png)

Expected:
![image](https://user-images.githubusercontent.com/5220825/38462924-3965d2b0-3ae6-11e8-8bec-9d8ea1ac06d1.png)

Is this achievable with a specific configuration or is it something that can be made configurable?

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We have another command (with id `workbench.action.quickOpenPreviousEditor`) for that, e.g. configure this in keybindings to use it:

```json
{
	"key": "ctrl+i",
	"command": "workbench.action.quickOpenPreviousEditor"
}
```

**Comment by andybergon** [comment]
Ok, perfect! Thank you so much, this was exactly what I was looking for.

I just wonder if this should be the default action for the quick open shortcut but probably this is just a personal preference coming from IntelliJ.
