### ISSUE TITLE
Duplicate outline entries for JS top-level functions

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4741]
![image](https://cloud.githubusercontent.com/assets/22350/14109628/2eb381c4-f5c3-11e5-940e-a99f173f245e.png)

JS outline always shows duplicate entries for top level functions.

**Comment by egamma** [comment]
Moving to TypeScript for investigation

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7725
