### ISSUE TITLE
"workbench.action.showAllSymbols ctrl+t", it doesn't work

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#47412]
"workbench.action.showAllSymbols ctrl+t", it doesn't work

**Comment by midGitub** [comment]
![snipaste_2018-04-08_11-23-04](https://user-images.githubusercontent.com/20261416/38463106-3b039302-3b25-11e8-875c-0bd586d7ad91.png)

**Comment by roblourens** [comment]
Are you using a C# extension? This isn't provided out of the box. Please open an issue on the extension if it isn't working as expected.
