### ISSUE TITLE
Extended development, escape error when sending command in cmd.exe terminal

### ISSUE THREAD

**Issue by FishOrBear** [Microsoft/vscode#47411]
- VSCode Version:1.22.1
- OS Version: Windows10,Cmd.exe

I am trying to fix a jest debug problem
[jest-issues](https://github.com/jest-community/vscode-jest/issues/294)

I found that powershell and cmd.exe seem to have different results when the terminal sends a command line.

powershell:
![image](https://user-images.githubusercontent.com/19372111/38462610-8ec6d746-3b1c-11e8-825f-5d4420819324.png)

cmd.exe
![image](https://user-images.githubusercontent.com/19372111/38462615-af498414-3b1c-11e8-96ab-6c4a67172bd6.png)

The generation of command line results does not seem to be extended control.

**Comment by Tyriar** [comment]
How are you sending/generating the command line?

**Comment by FishOrBear** [comment]
I'm very sorry, I need some time to read the source code.
