### ISSUE TITLE
Organize Imports removes alias

### ISSUE THREAD

**Issue by evanfuture** [Microsoft/vscode#47419]
- VSCode Version: 1.22.1
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Given a file with these inputs:
```
import { Component } from '@angular/core';
import { AppState } from './app';
import * as application from 'tns-core-modules/application';
import { init as advancedWebviewInit } from 'nativescript-advanced-webview';
```

2. Run Typescript: Organize Inputs

3. What results is
```
import { Component } from '@angular/core';
import * as application from 'tns-core-modules/application';
import { AppState } from './app';
```

Not that the `import * as application` works fine, but `import { init as advancedWebviewInit }` is removed entirely.  Yikes!

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Duplicate of #47362
