### ISSUE TITLE
Cannot properly rename a file starting with space in its name

### ISSUE THREAD

**Issue by deepeeess** [Microsoft/vscode#47416]
- VSCode Version: `Version 1.22.1 (1.22.1)`
- OS Version: `MacOS 10.13.3`

Steps to Reproduce:

1. Create a new file with a name starting with a space (using MacOS Finder)
2. Try to rename the file by removing the space at the beginning of the file name (using the VS Code explorer).

Does this issue occur when all extensions are disabled?: Yes/No
`Yes`

**Comment by JoshuaKGoldberg** [comment]
Confirmed on Windows too..
