### ISSUE TITLE
Option to turn off JSON comment warnings

### ISSUE THREAD

**Issue by hkcorac** [Microsoft/vscode#47418]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make new JSON file.
2. Add some comments.
3. Comments are displayed with red underlines as warnings.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Could you please add option to disable JSON comment warnings? Some JSON binding libraries have "easy mode" when parsing JSON content, which allows comments. I searched settings but couldn't find one to disable those warnings.

I notice the settings have comments in there, and no warnings are shown.

Thanks,

**Comment by yume-chan** [comment]
Temporarily, you can set language mode (<kbd>F1</kbd> - `Change Language Mode`) to "jsonc" which allows comments.

Permanently, you can map files to "jsonc" mode by their names, by adding entries to the "files.associations" settings (in your user settings or workspace settings), for example mapping all json files (not recommanded):

```` json
"files.associations": {
    "*.json": "jsonc"
},
````

Some file name pattern:

```` json
"files.associations": {
    "babelrc.json": "jsonc"
},
````

**Comment by roblourens** [comment]
That's the correct answer, thanks @yume-chan
