### ISSUE TITLE
'run code' shows "No module named 'bs4'" even though it works with 'run python file in terminal'

### ISSUE THREAD

**Issue by anurag00** [Microsoft/vscode#47428]
Issue Type: <b>Bug</b>

i cannot run my program by clicking 'run code'. It keeps showing error 'no bs4 module' but if right click and select 'Run file in python terminal' there is no error. 

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|7.89GB (3.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
php-debug|fel|1.12.2
code-runner|for|0.9.3
Go|luk|0.6.78
python|ms-|2018.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
python|tht|0.2.3

</details>

**Comment by Tyriar** [comment]
I think this is related to the code-runner extension
