### ISSUE TITLE
Use fuzzy match in `Select Language Mode` picker

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#47424]
It now uses some poor kind of logic: takes in consideration only first letters of words (and UPPERCASED).

#### JavaScript:
`jsc`=> ✅ 
`jscpt` => ❌
`jpt` => ❌
`jcp` => ❌

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/34088
