### ISSUE TITLE
折叠代码

### ISSUE THREAD

**Issue by Lpbzzz** [Microsoft/vscode#47420]
Issue Type: <b>Bug</b>

折叠代码后不能打开，也没有 + 的标志

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|15.95GB (9.53GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\wamp\www\xchw-v3|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.1
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.2
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.27
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
gitlens|eam|8.2.0
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.1
vscode-npm-script|eg2|0.3.3
vscode-element-helper|Ele|0.5.2
vscode-great-icons|emm|2.1.30
prettier-vscode|esb|1.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
beautify|Hoo|1.3.0
output-colorizer|IBM|0.1.2
docthis|joe|0.6.0
code-beautifier|mic|2.0.3
dotenv|mik|1.0.1
vscode-fileheader|mik|0.0.2
mssql|ms-|1.3.0
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.3.0
color-highlight|nau|2.3.0
vetur|oct|0.11.7
vuehelper|oys|0.1.0
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|3.2.6
code-settings-sync|Sha|2.9.0
guides|spy|0.9.1
ayu|tea|0.14.0
open-in-browser|tec|1.1.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|2.0.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please include more details about your problem.

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
