### ISSUE TITLE
debugging problem

### ISSUE THREAD

**Issue by SPK-RPI** [Microsoft/vscode#47423]
Issue Type: <b>Bug</b>

i cant make a configuration file to debug python and c++ is not debugging

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|Memory (System)|5.95GB (2.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
dart-code|Dar|2.11.2
php-intellisense|fel|2.3.1
fs-flutter-snippets|fra|0.1.3
vscode-phpfmt|kok|1.0.18
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2018.3.1
cpptools|ms-|0.15.0
vscode-arduino|vsc|0.2.11

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
Please file this issue against the C++ extension: https://github.com/Microsoft/vscode-cpptools
