### ISSUE TITLE
Search in settings is nonfunctional

### ISSUE THREAD

**Issue by Neutrino-Sunset** [Microsoft/vscode#47427]
Issue Type: <b>Bug</b>

Press ctrl+shift+p
Type settings
Select the command entry to open the settings file in an editor.
In the search/filter box enter "scrollbar" (without quotes)

Expected Behaviour
The list should be filtered to only show those entries containing "scrollbar"

Actual Behaviour
The list is filtered to display what at first glance appears to be a random subset of entries none of which contain "scrollbar".

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.10.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3453)|
|Load (avg)|0, 0, 1|
|Memory (System)|15.52GB (7.50GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
code-settings-sync|Sha|2.9.0
html-css-class-completion|Zig|1.17.1
path-intellisense|chr|1.4.2
vscode-togglecodelens|cml|1.0.3
vscode-great-icons|emm|2.1.30
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.3.0
vscode-css-peek|pra|2.1.0
subtle-brackets|raf|2.1.0
indent-one-space|use|0.2.3

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
The thing is that none of the settings have the word "scrollbar", so we show settings that people often are looking for when they search "scrollbar". For example, minimap and "overview ruler" settings.

**Comment by Neutrino-Sunset** [comment]
But you don't show the setting "editor.scrollbar.vertical" which needs to be set to "visible" to stop the scrollbars from completely disappearing if the mouse cursor is not over the editor.

The logic you have in place is not remotely useful. If there are no settings containing the specified word you would be better off displaying nothing than a load of stuff that has no obvious relation to what was searched for. There is such a thing as trying to do too much, I would say this logic is a classic case of that.

**Comment by roblourens** [comment]
What is `editor.scrollbar.vertical`? I don't think that's a setting we have.

**Comment by roblourens** [comment]
Maybe it used to work, it doesn't seem to do anything now. In any case, unofficial settings won't show up in search.

**Comment by usernamehw** [comment]
Works for me 😐

**Comment by Neutrino-Sunset** [comment]
It works for me too. Like I said before, it is needed to stop the scrollbars from disappearing when the mouse cursor is not over the editor, (which incidentally I have to say is a pretty idiotic feature to have enabled by default in an editor that is designed to be fully usable via the keyboard).
