### ISSUE TITLE
Explicitly mention Visual Studio 2017 in "How to Contribute"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/vscode#47433]
Is wiki/How-to-Contribute#build-and-run-from-source not updated since 2017 came out, or is it just not supported? :)

**Comment by roblourens** [comment]
At one point I think 2017 didn't work without more fiddling. I think the windows-build-tools npm module is probably the recommended solution, maybe that should come first in the list.

@sbatten I'm guessing that you were the most recent to get set up on Windows, are you using VS 2017?

**Comment by shizengzhou** [comment]
I use VS 2017 to build VS Code on Windows 8.1 and Windows 10.

**Comment by sbatten** [comment]
I was using the npm module, but I tested with VS 2017 on a fresh machine and didn't run into any issues. @chrisdias can you update with correct links? It seems that none of the VS links are working right now.

**Comment by chrisdias** [comment]
the how to contribute page mentions vs 2017 and the link takes you to a download page.  not sure what needs to be changed, please reopen if something is still incorrect.
