### ISSUE TITLE
[icon themes] seti theme should associate also to non build-in language modes (elm, caml, nunjucks..)

### ISSUE THREAD

**Issue by ShalokShalom** [Microsoft/vscode#47432]
- VSCode Version: 1.22
- OS Version: KaOS

Steps to Reproduce:

1. Set `files.defaultLanguage": "elm",`
2. Open new file
3. Check if the logo of the language appears left of its file name in the tab bar. 
4. Repeat this for a couple of other languages

The issue happens randomly. 
When it applies fine, does this count for all created files. 
The issue appears, when you change the setting. 
So, the issue is obvious, that it fails to apply randomly. 
In ALL cases get the correct language displayed in the status bar. 

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by roblourens** [comment]
Do you have some extension installed that contributes Elm? Does it appear in the language mode picker?

**Comment by ShalokShalom** [comment]
Yes, the Extension is installed and it appears in the status bar, if thats it, what you call language mode picker.

**Comment by roblourens** [comment]
Which extension?

**Comment by ShalokShalom** [comment]
The only one?

https://marketplace.visualstudio.com/items?itemName=sbrink.elm

**Comment by roblourens** [comment]
Works for me. When you open the new file, what language mode does it use instead?

**Comment by ShalokShalom** [comment]
Untitled document, so a plain text document, I guess.

**Comment by roblourens** [comment]
Does it say "Plain text" in the status bar or something else?

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/38513089-0640e936-3be2-11e8-9655-095074e87486.png)

The popup that you get when you click that is what I mean by language mode picker.

**Comment by ShalokShalom** [comment]
Yeah, I thought so. In the status bar, as I mean.

It shows Elm. 

And I just reproduced the issue with ocaml:

ocaml in the settings, ocaml in the status bar and plan text document. 

This work fine yesterday, so it appears seemingly randomly and is independent of the language. 

Hnn?

**Comment by roblourens** [comment]
So to confirm, it shows the correct language in the status bar, but it doesn't use the correct syntax highlighting?

**Comment by ShalokShalom** [comment]
And it does not show the correct format in the tab bar. :slightly_smiling_face:

**Comment by roblourens** [comment]
What do you mean "the correct format in the tab bar"?

The syntax highlighting works for me. When you save the file, does it become highlighted correctly?

**Comment by ShalokShalom** [comment]
No. And when you look into the tab bar, where the open files are listed, can you see the specific logo and the correct file name ending in the correct case. :slightly_smiling_face:

**Comment by roblourens** [comment]
If it doesn't get highlighted when you save it, then this isn't specific to opening a new file, you're just missing Elm highlighting entirely right?

Can you include a screenshot of it in this state so we're clear on what the problem is?

**Comment by ShalokShalom** [comment]
No, because it works always, when I create a specific .elm file. 

I reworked the comment above.

**Comment by ShalokShalom** [comment]
As you can see, is the elm extension in the first tab working. In a newly opened file with the files.default.language setting does it sometimes apply and sometimes not. This is independent from the file type. I already had ocaml files correctly created by files.default.language. It is clearly a mechanism behind the setting itself, imho. And this seems to fail randomly. So what can cause this?

https://vimeo.com/263954339

**Comment by aeschli** [comment]
I assume you use the Seti icon theme.

The reason is the way our Seti icon theme associates the icons. The elm icon is contributed to all files with file extension '.elm', for for the language mode elm.

That can be improved, but IMO it's not most urgent. I hope you agree.

**Comment by ShalokShalom** [comment]
Oh I see. The OCaml mode also showed sometimes the logo and sometimes not, when created by the files.default.language setting.

**Comment by aeschli** [comment]
To verify:
- set seti theme
- install a language extension, e.g. elm
- create an untitled file, set the language to `elm`
- verify that the icon is the elm icon
