### ISSUE TITLE
Don't show plugin logo in plugin menu

### ISSUE THREAD

**Issue by izac1** [Microsoft/vscode#47439]
Dont show plugin logo in plugin menu
![image](https://user-images.githubusercontent.com/6692451/38469758-26219c1a-3b5a-11e8-83c0-9ebe325745bd.png)
![image](https://user-images.githubusercontent.com/6692451/38469766-4078a644-3b5a-11e8-9d59-cb8c7e42e44f.png)

 
- VSCode Version: 1.22.1
- OS Version: Win 10

Steps to Reproduce:
1.Install new version from official site
2. Click plugin button or cntrl+shift+x 

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It is hidden when the extension viewlet is narrow. It should be shown if you drag the viewlet to be a little wider.
