### ISSUE TITLE
infinite the window has crashed dialogs

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#47431]
VS Code version: Code - Insiders 1.23.0-insider (fc389d2, 2018-04-05T05:10:30.542Z)
OS version: Darwin x64 17.4.0

![apr-08-2018 06-59-55](https://user-images.githubusercontent.com/2301847/38467777-790a6674-3afa-11e8-936a-26c99542a0e2.gif)

Steps to Reproduce:

1. Unclear.  Let me know if I can upload a crash log.

Does this issue occur when all extensions are disabled?: No

I wonder if this is eslint?  Can you please use this bug to just avoid the infinite dialogs?  That would be a core vscode issue right?

This would be greatly appreciated -
![image](https://user-images.githubusercontent.com/2301847/38467843-f8a6aed8-3afa-11e8-8b46-5575750d7f14.png)

**Comment by roblourens** [comment]
- Why do you suspect eslint? 
- Did this just start happening recently or did it always happen?

**Comment by joshunger** [comment]
How do I check?  I think eslint crashed for what is it 5 times before you see a dialog?  Just started happening. I started code with disabled extensions and then started code with extensions enabled and it disappeared.

**Comment by roblourens** [comment]
So you see a message that eslint crashed, then you see the window crash?

>  and then started code with extensions enabled and it disappeared.

So when you start with extensions disabled, it doesn't crash?

**Comment by joshunger** [comment]
If you can just tell me how to get you a dump we can save back and forth time.  Within the hour previous, I saw the window that eslint crashed x times.  It does not crash now either way.

**Comment by roblourens** [comment]
Directions here: https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#macos
