### ISSUE TITLE
Visual Studio code lag with dell integrated graphics

### ISSUE THREAD

**Issue by afalahi** [Microsoft/vscode#47438]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

1. Using Dell Precision 5510 with Nvidia quadro 1000
2. Noticed it happens in vscode and not in chrome
3. Switched to Nvidia GPU instead of integrated and that fixed my issue

Does this issue occur when all extensions are disabled?: Yes/No
Extensions are unrelated.

**Comment by roblourens** [comment]
What lags? Can you give more details?
