### ISSUE TITLE
Option to add logo / icon to activity bar based on workspace

### ISSUE THREAD

**Issue by rubiesonthesky** [microsoft/vscode#47436]
I have multiple projects that I shuffle between, so I have noticed that adding different colors to activity bar (the vertical column with files, search, extensions etc. views) is good way to identify the right window of VS code windows. I would like to have a little more customisation though. Since most my projects are angular / web projects they all have favicons. I was thinking that adding that favicon as logo on top of the activity bar would tell me instantly what project I'm working with. Making this more universal it could be just option to add path to any image you like.

This is maybe more an extension idea than thing to add default editor.

Shorter:
1. add option to specify icon to represent workspace / project
2. add that icon above other icons in activity bar. or replaces files icon with it.

**Comment by lazysergey** [comment]
@rubiesonthesky I also came up with this way to differentiate 5-6 windows/projects that I have open simultaneously. would be nice to have option to set this at least via settings.json

**Comment by vincentfiestada** [comment]
This sounds interesting as well. But I agree that it should be an extension instead. 

It would be even more useful if the window icon also changes, but I imagine that would be even more complicated and is better addressed by window/desktop management systems.

**Comment by ajmcgarry1608** [comment]
Have you tried the Peacock plugin. Doesn't do icons, but does allow you to change the colours of the VSCode Chrome

**Comment by tylersticka** [comment]
I'd love this, too.

In the meantime, I've resorted to customizing `window.title` in workspaces ([more info](https://code.visualstudio.com/updates/v1_10#_configurable-window-title)) using emoji. Here's an example that adds a little lightning bolt (⚡) to a workspace's title:

```
{
  "window.title": "⚡️ ${activeEditorShort}${separator}${rootName}"
}
```
