### ISSUE TITLE
Encodings for Chinese

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#47440]
There are several encodings used for Chinese——
GB2312, GBK, GB 18030.
GB2312 was born in 1980, and it had been superseded by GBK.
https://en.wikipedia.org/wiki/GB_2312
While GBK was born in 1995, which was used to supersed GB2312.
https://en.wikipedia.org/wiki/GBK_(character_encoding)
But GBK had been superseded by GB 18030-2000 then, which was born in 2000 as the name.
https://en.wikipedia.org/wiki/GB_18030
In 2005, GB 18030 was updated by a new version named GB 18030-2005.
So right now, GB 18030-2005 is the newest standard for Chinese encoding, and it can be compatible with GB 2312 and GBK also. GB 2312 and GBK has been out.
So, VS Code need include so many codings. GB 18030-2005 is the only one what we need.

**Comment by byyxx128** [comment]
I have checked, that issue is different from mine.
I mean there are too many duplicate and outdated encodings, and the new encoding has supersed old ones.

**Comment by roblourens** [comment]
Legacy encodings can still be used by people and it's useful for editors to support them. We basically support the list from https://encoding.spec.whatwg.org/#names-and-labels
