### ISSUE TITLE
Visual Studio Code opens when I plug in a thumb drive

### ISSUE THREAD

**Issue by polycopter** [Microsoft/vscode#47444]
Issue Type: <b>Bug</b>

step 1. plug in a USB thumb drive
... VS Code always opens. Why? This is terrible.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.4.0-101-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6410 APU with AMD Radeon R5 Graphics (4 x 2000)|
|Load (avg)|2, 0, 0|
|Memory (System)|6.77GB (1.67GB free)|
|Process Argv|/usr/share/code/code --unity-launch /media/andrew/Lexar|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
husarion|hus|1.5.8
python|ms-|2018.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
cmake|twx|0.0.17

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
This is probably something that windows is configured to do. It's not something that vscode does by itself.

https://superuser.com/questions/401073/change-default-action-on-connecting-a-usb-device

**Comment by weinand** [comment]
@roblourens this problem occurred on linux, not Windows.
