### ISSUE TITLE
[html] problems with html style comments in embedded code

### ISSUE THREAD

**Issue by Jack-Punter** [microsoft/vscode#47448]
Issue Type: <b>Bug</b>

I have some computer generated HTML with some inline javascript and within the javascript, the code has generated HTML style comments, if I then format the file using Format Document (Shift+Alt+F) the formatter adds a space between the < and ! causing the file to error when attempting to load in a browser. I understand if you don't fix this as really you shouldn't use HTML style comments in your javascript. I have attached 2 files, one before and one after formatting, of a trivial example case. (rename these to .html)
[Issue Broken.txt](https://github.com/Microsoft/vscode/files/1888001/Issue.Broken.txt)
[Issue Working.txt](https://github.com/Microsoft/vscode/files/1888002/Issue.Working.txt)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3100)|
|Memory (System)|15.94GB (6.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Jack\Desktop\PUBGAPI|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gotemplate|cas|0.2.0
Go|luk|0.6.78
python|ms-|2018.3.1

</details>

**Comment by aeschli** [comment]
```html
<html>

<head>
    <script type="text/javascript">
        <!-- This is an HTML comment inside javascript -->
            alert("Hello");
    </script>
</head>

<body>
    HTML body
</body>

</html>
```

https://stackoverflow.com/questions/28842628/does-html-comment-act-as-a-single-line-comment-in-javascript-and-why

**Comment by UwUeeb** [comment]
if this is still an ongoing issue, i would like to take a look, mind guiding me to where the code for this is at?

**Comment by aeschli** [comment]
The formatting of the HTML file happens here: https://github.com/microsoft/vscode/blob/9d64b75dea4136fc997e5ba5fa20c11a2541f39b/extensions/html-language-features/server/src/modes/formatting.ts#L58

The HTML formatter first formats the whole content, and then for each embedded content (e.g. JavaScript), a specific formatter is used (`mode.format`). The problem is that the embedded content also contains the HTML style content.
Maybe the fix would be to first replace `<!` with `/*` and `->` with `*/` or blank it out. 
Tests are here: https://github.com/microsoft/vscode/blob/9d64b75dea4136fc997e5ba5fa20c11a2541f39b/extensions/html-language-features/server/src/test/formatting.test.ts#L59

**Comment by UwUeeb** [comment]
my diff looks something like this :
```diff
diff --git a/extensions/html-language-features/server/src/modes/javascriptMode.ts b/extensions/html-language-features/server/src/modes/javascriptMode.ts
index 0c199571dd7..b5d18b8b6aa 100644
--- a/extensions/html-language-features/server/src/modes/javascriptMode.ts
+++ b/extensions/html-language-features/server/src/modes/javascriptMode.ts
@@ -41,7 +41,13 @@ function getLanguageServiceHost(scriptKind: ts.ScriptKind) {
 			getScriptSnapshot: (fileName: string) => {
 				let text = '';
 				if (fileName === currentTextDocument.uri) {
-					text = currentTextDocument.getText();
+					if (fileName.endsWith('html')) {
+						text = currentTextDocument.getText().replace(`<!--`, `/*`);
+						text = text.replace(`-->`, `*/`);
+					}
+					else {
+						text = currentTextDocument.getText();
+					}
 				} else {
 					text = libs.loadLibrary(fileName);
 				}
 ```
 works fine for now, but i think this can be better, any suggestions are welcome
