### ISSUE TITLE
vscode-update.azurewebsites.net/api may be providing incorrect SHA256

### ISSUE THREAD

**Issue by coreygo** [Microsoft/vscode#47446]
- VSCode Version: Latest Insiders
- OS Version:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199
```

Steps to Reproduce:

1. https://vscode-update.azurewebsites.net/api/update/darwin/insider/VERSION
2. Note `"sha256hash":"ca47a2626eb2d017600a3d06b66c80d333b6c7d815a26c5b7defb315c9252194"`
3. Download ZIP via curl and Chrome.
4. Check SHA256 locally on both copies of the ZIP.
5. Mis-match…
```
$ shasum -a 256 visual-studio-code-insiders--1.23.0,95101bf3f6d00105621cdddb639ea62b95ea2468.zip | awk '{ print $1 }'
a4335f2b8680c84c37f6b108bf453451b6f535b3fa1e775da15ed6956d058762
```
6. Confirm on a different Windows 10 (17639) download of the ZIP…
```
 Get-FileHash .\VSCode-darwin-insider.zip -Algorithm SHA256

Algorithm       Hash
---------       ----
SHA256          A4335F2B8680C84C37F6B108BF453451B6F535B3FA1E775DA15ED6956D058762
```

See additional details on a Homebrew cask-repair request:
https://github.com/caskroom/homebrew-versions/pull/5482

**Comment by coreygo** [comment]
Updated caskroom/homebrew-versions#5482 to reflect push of `1.23.0,49…6e71`, the SHA256 hashes now mesh locally, with Homebrew's TravisCI, and the insider/VERSION URL above.

Cheers.

**Comment by joaomoreno** [comment]
I'm confused. We didn't change anything. Hash seems fine from here. Closing since https://github.com/caskroom/homebrew-versions/pull/5482 says it's fixed.
