### ISSUE TITLE
color strings are parsed and colored in commented code

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#47442]
![image](https://user-images.githubusercontent.com/1451847/38470390-0ad9f7d8-3b30-11e8-9571-5258c699d8e7.png)

I've been through this code a few times prior to installing the March update and didn't *notice* these strings being colorized, but it may have happened. I definitely noticed today after picking up March update.

**Comment by roblourens** [comment]
Is there an extension doing this? Does it happen if you start with `--disable-extensions`?

**Comment by ericblade** [comment]
i just went to check that out, and it didn't do it on a computer that had no extensions installed... and now it also isn't doing it on the one that does have extensions.  i didn't realize that i have an extension installed that performs this, i thought it was native, but it's also not triggering on these strings anymore, since the first start after the upgrade.. so i'm going to close it.  Apologies for the mis-report!
