### ISSUE TITLE
Improve `Run [Build] Tasks` command and dialog

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#47449]
Issue Type: <b>Feature Request</b>

When it comes to executing `Tasks: Run [Build] Tasks`, instead of putting the message, `Fetching [build] tasks...` in the status bar (where I often don't notice it) and waiting for all tasks to be available before showing anything, I would like the dialog to pop up immediately, with that message at the top, and populate as tasks are found.

As a rough example (please pardon my [lack of] ms paint skills):

![vscode issue 47449](https://user-images.githubusercontent.com/879055/38473412-89788370-3b44-11e8-8d53-2ee1101b409c.png)

When I execute `Tasks: Run Build Task` just after opening VSCode, or after VSCode has been inactive for quite a while, the `Fetching build tasks...` job takes a fair bit of time to complete. It completes slightly faster for a single-root workspace than for a multi-root workspace, but it still take an annoyingly long time to complete.

I would guess that tasks from `tasks.json` do not take very long to fetch, and the main holdup is waiting for tasks from extensions and from gulp. Since I often want to run a task from `tasks.json`, it would be wonderful to not have to wait for all of the other tasks to populate before I can run one of those.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by alexr00** [comment]
Related to #32467

**Comment by alexr00** [comment]
Showing a dialog is much more intrusive than the status bar info. We will leave it as is.
