### ISSUE TITLE
Suggestion: Organise Imports should sort by import name instead path

### ISSUE THREAD

**Issue by PooperPig** [Microsoft/vscode#47447]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

1. Press Alt-Shift-O
Does this issue occur when all extensions are disabled?: Yes

More of a suggestion than a bug...

When organising Imports, I don't really care where about the location of the import, it would be more sensible to sort by the names; When I'm looking through Imports, I'm usually looking for (for example) 'Constants' and not 'cs/editor/common/core.'...

When importing '* as zzz' it would be sensible to sort by the 'zzz' rather than the '*' or path imported from.

e.g. in the example shown in the release notes, the sorted results would be better (IMHO) as

```
{ Constants }
{ FontInfo }
* as nls
* as platform
{ ScrollbarVisibility }
{ USUAL_WORD_SEPARATORS }
* as zoom
```
as this makes it easier to find an import and makes more sense than using the location of a particular file as the sort order.

Also, the option to remove unused imports should maybe be an option rather than unavoidable behaviour?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23279
