### ISSUE TITLE
Adding an asterisk in a regex de-indents the line in JS

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#47450]
Code:

```javascript
function foo() {
  bar.match(/^./)
}
```

GIF to show that adding an asterisk de-indents the line:

![vsc js de-indent](https://user-images.githubusercontent.com/343940/38474615-07e051f0-3b6f-11e8-9ddf-4aa981942473.gif)

**Comment by rebornix** [comment]
Thanks for your feedback, let's track it in https://github.com/Microsoft/vscode/issues/38886 .
