### ISSUE TITLE
Hide panel, sidebar and activity on editor tab double click

### ISSUE THREAD

**Issue by lascarayf** [Microsoft/vscode#47453]
Issue Type: <b>Feature Request</b>

Like "Eclipse" 

Double click on editor tab **->** hide sidebar, activity and panel.
Double click again **->** restore previous state.

Double click on panel tab **->** maximize panel size.
Double click again **->** restore panel size.

**Comment by bpasero** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/16927
