### ISSUE TITLE
Search in files with ripgrep never completes

### ISSUE THREAD

**Issue by daveorourke** [Microsoft/vscode#47459]
Issue Type: <b>Bug</b>

Same symptoms as this issue:  https://github.com/Microsoft/vscode/issues/30630

Repro steps:
1. "search.useRipgrep" : true
2. Search for something => The search never completes.

The Developer Console shows this:
/E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [IPC Library: Search] Uncaught Exception:  Error: spawn e:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg ENOENT

Notes:
- I do not have a C: drive.  Windows is on the E: drive.
- If I set "search.useRipgrep" : false, search works as expected.

From Help > About:
Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T02:26:57.615Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|Memory (System)|15.63GB (8.60GB free)|
|Process Argv|E:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.6.0

</details>

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by daveorourke** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/8958899/38500474-807cc1ca-3bd8-11e8-9d40-d1fdbef320cf.png)

**Comment by roblourens** [comment]
Oh, I think that since I set a cwd of 'c:/' by default

> I do not have a C: drive.

will cause a problem. I will fix that...

**Comment by daveorourke** [comment]
> Oh, I think that since I set a cwd of 'c:/' by default
> 
> will cause a problem. I will fix that...

Yep, that sounds like the culprit.  Thanks @roblourens

**Comment by roblourens** [comment]
This should be fixed by enabling the new experimental search by setting the `searchRipgrep.enable` setting (then reloading the window).

It's tricky to fix in the default search so I'll consider it fixed with that.
