### ISSUE TITLE
Debugging : current line get one more indent

### ISSUE THREAD

**Issue by olivierchatry** [Microsoft/vscode#47464]
- VSCode Version: 1.22.1
- OS Version: Fedora 27

Steps to Reproduce:

1. start debugging javascript code using node
2. current debug line get indented with one tab

Does this issue occur when all extensions are disabled?: Yes

![01](https://user-images.githubusercontent.com/1267483/38486049-2d5aaa3a-3bdc-11e8-9d34-4618a59d7d0e.png)
![02](https://user-images.githubusercontent.com/1267483/38486053-2f572b10-3bdc-11e8-83a4-99391e02a793.png)

Edit : Looking at the screenshot, it seems the spacing is different between normal line and current line.

**Comment by olivierchatry** [comment]
This seems to be font related. If I use the default font ( on Fedora, not sure about the name ), then it does not do that. The font I was using is Inconsolada, size 18 :
```

**Comment by isidorn** [comment]
I can not reproduce this.
Can you reproduce if you use latest vscode insiders https://code.visualstudio.com/insiders/
Can you reproduce if you 	`"debug.inlineValues": false`
