### ISSUE TITLE
Working tree opened file doesn't update after commit changes

### ISSUE THREAD

**Issue by holms** [Microsoft/vscode#47460]
- VSCode Version:
```
1.23.0-insider
4ba9ac40f14730c7fae2ff07a84dde2cd9c4ee56
x64
```
- OS Version:
```
Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
```
Steps to Reproduce:

1. Go to Source Control
2. Open file which you want to stage
3. Highlight couple of lines and from right click menu choose "stage"
4. Now commit changes

File is not updated, everything that's just been committed stayed. But if you close and open file again, you'll see different picture, committed changes will  be gone. So probably file should be update right after commit happened..?

Does this issue occur when all extensions are disabled?: Yes

**Comment by holms** [comment]
This is not duplicate :) it's different issue.

**Comment by joaomoreno** [comment]
> File is not updated, everything that's just been committed stayed.

What do you mean? Can you show me a recording?

**Comment by holms** [comment]
It means that when file is opened in working tree mode (diff of the file, when opened from version control tab), and then you select lines you want to stage, and they you commit what's staged, working thee view hasn't changed at all, you need to close a file and open it manually, and even in that situation I've ended up doing this twice before I could see newest diff in working tree view.

**Comment by joaomoreno** [comment]
Got it. So it's the diff which doesn't change, not the file itself. This is a file event issue.

Do you get file events normally in the file explorer? If you delete a file outside Code, for example, does Code reflect that change?
