### ISSUE TITLE
Provide a method of matching TaskExecution objects

### ISSUE THREAD

**Issue by alpaix** [Microsoft/vscode#47465]
#### Problem
The extended task API introduced a new concept of task executions. When `executeTask` method is called it returns a `TaskExecution` instance I'd wanted to keep for later. Then after the task terminates it raises `onDidEndTask` event with another `TaskExecution` instance attached to it which I cannot match against the first instance I kept as they are not ===. 

#### Suggestion
Provide a method of matching task execution objects or giving it a unique ID or similar.

**Comment by alpaix** [comment]
One more request is to provide a query to fetch all task executions. Is it possible to add to the API?

**Comment by dbaeumer** [comment]
@alpaix I will look into making the task execution object `===`. 

Can you please open another issue for the query. Makes it easier for me to track and close.

**Comment by dbaeumer** [comment]
Tested via LiveShare team.
