### ISSUE TITLE
Send a Tweet reports bad maximum length

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4746]
Due to `#HappyCoding` being appended to it

![image](https://cloud.githubusercontent.com/assets/22350/14110427/ac5b90b4-f5c6-11e5-9b97-bdfaa4264166.png)

**Comment by eklavyamirani** [comment]
this looks like a good place to start off, is this something I can help with?

**Comment by Tyriar** [comment]
@eklavyamirani :+1: it's marked help wanted which probably means @joaomoreno won't get to it any time soon.

**Comment by joaomoreno** [comment]
@eklavyamirani Go for it, this is a great issue to start contributing to Code. Let me know if you need any help.

**Comment by eklavyamirani** [comment]
Awesome, I am on it! :)

**Comment by eklavyamirani** [comment]
@joaomoreno Please review :)

Couldn't find any unit tests for this, did I miss it?
