### ISSUE TITLE
VS Code missing code hints for JavaScript when the node_modules folder exists

### ISSUE THREAD

**Issue by lycheelee** [Microsoft/vscode#47479]
### How to  ignore the 'node_modules' folder  in vs code?

My vs code and os version like this:

- VSCode Version: the latest version
- OS Version: Ubuntu 16.04

I have try this [Running VS Code on Linux#](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc), Unfortunately, it doesn't work.

* Code hints doesn't work in the **.js** flies, when the folder '**node_modules**' exists.
* When remove the folder '**node_modules**', code hints works!

So, is there some methods to ignore 'node_modules' in vs code,  or some methods to make it work well ?

I need help please, I tried a variety of methods but failed.

**Comment by mjbvz** [comment]
Do you have a [jsconfig.json](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson)?

**Comment by mjbvz** [comment]
Does this happen when all extensions are disable?

Also, please reproduce the problem and then share the output of running `$ code --status`  in a separate terminal
