### ISSUE TITLE
VSCode test only support 32bit native module

### ISSUE THREAD

**Issue by timoxue** [Microsoft/vscode#47472]
- VSCode Version: 1.21.1
- OS Version: win 10

I was using a native module in vscode extension development, when use ./node_modules/vscode/bin/test to run test, it occurs the error 

```
failed: %1 is not a valid Win32 application.
```
but under my production environment, I use a 64bit vscode, it seems I need to keep re-compiling the module between remote and local tests.

 does the test only support 32bit module?

**Comment by bpasero** [comment]
Please report to https://github.com/Microsoft/vscode-extension-vscode
