### ISSUE TITLE
.gitattributes autocompletion: uppercase vs. lowercase

### ISSUE THREAD

**Issue by AlphaGit** [Microsoft/vscode#47488]
Issue Type: <b>Bug</b>

.gitattributes settings currently allow for eol=LF and eol=CRLF (autocomplete feature), but the correct versions are in lowercase.

Autocomplete will suggest eol=LF but the uppercase version does not have the desired effect.

PS: I would have sworn it should work with upper and lowercase versions, but git would replace line endings when using the uppercase value, it would not (desired effect) when using the lowercase version.

Tested with git version 2.16.1.windows.1

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|15.90GB (5.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
postgresql|JPT|0.0.2
python|ms-|2018.3.1
vscode-docker|Pet|0.0.26

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
Are you sure Code has autocomplete for this file type?

**Comment by AlphaGit** [comment]
To be honest, I thought it was probably an extension, but when reporting the issue, VSC asked me to reproduce with all extensions disabled — I did and got the same behavior. Is that enough proof, or is there anything else I would need to try?

**Comment by joaomoreno** [comment]
If I open `.gitattributes` in my VS Code, I see no autocompletion there. Can you show me a screenshot?
