### ISSUE TITLE
[Suggestion] New Settings Page?

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#47482]
Issue Type: **Suggestion**

This idea is aimed to improve the settings experience, targeted at the April Iteration Plan. 

The current settings page is pretty cool, however I feel that the User Experience could be improved drastically. Instead of opening the Settings in a new window/tab, it would open a new screen (in the same window?) with Categories on the left and the settings for the categories on the right (from what I've seen, this is similar to Atom). Below, I created some dummy images representing what this screen could look like

**PLEASE NOTE: These Images are rough sketches of my vision of Settings 2.0; Based off my theme: One Dark Pro Vivid**
![settings2](https://user-images.githubusercontent.com/30497573/38493930-db2dd344-3beb-11e8-94ff-8f4b56e90695.png)

_Note: I made this rough sketch on Inkscape, don't judge pls_

What this contains:
On the left: Sidebar of settings, not all settings are there as this is concept, but it will be scrollable to accomodate the others, and they are collapsible

The rest of the screen, the area in which you actually customize settings, using selectors (true/false), textboxes for custom values and dropdowns for a range of fixed values.
Hopefully you understand where I'm going with this (ehem Atom) and I hope you'll consider my idea, thanks and have a great day!

**Comment by roblourens** [comment]
@beastdestroyer thanks for the ideas! This was well-timed, I am actually working on something like this. I posted a mockup at https://github.com/Microsoft/vscode/issues/3355, let me know what you think.

**Comment by roblourens** [comment]
I have experimented with a similar list, but my problem is that the category list is pretty long and a bit overwhelming. Grouping them together seems nice but they overlap in different ways and there isn't a perfect way to do that. Plus it's not always clear what the categories mean and why a setting is in one and not another.

But, I'm still experimenting with different types of category navigation aids.

**Comment by beastdestroyer** [comment]
Ah yes, the Settings is kinda clustered (Personally, I feel someone should take the time and kinda sort out all of these settings in the back-end or something), but in terms of 'category navigation aids', what about "bookmarks" to different categories then? 

For example, in my sidebar, I mentioned a more organised system for setings, if that cannot happen without some magic, then what about just replacing them with all the current setting categories, and clicking on one of these buttons will either scroll/show those settings only:

Example in Action:
1. I have a button called "CSS Language Settings" (it will point to VSCode's current CSS Category)
2. Click it.
3. Settings for CSS show up automatically (preferably scrolled animation so no one has to deal with hide/show events for every button)

**Also, I had this suggestion for a while but keep forgettign to mention: everytime a user switches to a different editor and comes back to settings, it keeps resetting to the top, please fix that; with the amount of settings that VSCode, coupled with extensions, a constant resets to the top gets annoying!**

**Comment by roblourens** [comment]
I agree that we should do a better job of persisting the view state, but it's hard to fix for technical reasons. :(
