### ISSUE TITLE
Multiple language file association

### ISSUE THREAD

**Issue by kaushall** [Microsoft/vscode#47480]
Currently file association supports only single language, Can devs of VS Code extends it to multiple languages?

`"files.associations": {}`

What I need is basically is I can define multiple files associations for a language if it's possible.

For eg,
`"files.associations": {
"*.php": "html, blade, php"
}`

Because it makes writing code easier if it supports multiple languages.

**Comment by joaomoreno** [comment]
You can only specify a single language obviously. Now, that language can have support for _embedded_ languages, but that's up the language's developer.
