### ISSUE TITLE
HTML formating problems

### ISSUE THREAD

**Issue by bledar** [Microsoft/vscode#47498]
Issue Type: <b>Bug</b>

The html format can not be disabled. After save the collapsed code is automatically expanded in html.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|7.90GB (3.00GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.6
sass-lint|gle|1.0.1
sublime-babel-vscode|jos|0.2.9
ftp-sync|luk|0.3.3
dotenv|mik|1.0.1
vscode-html-format|moh|0.0.1
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.3.0
vetur|oct|0.11.7
indent-rainbow|ode|0.7.2
LiveServer|rit|3.2.1
vscode-icons|rob|7.22.0
code-settings-sync|Sha|2.9.0
html5-boilerplate|sid|1.0.1
highlight-matching-tag|vin|0.4.4
markdown-all-in-one|yzh|1.1.2

(3 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
@bledar Can you add more details, code sample with steps how to reproduce, maybe some screenshots?
You have folded code, then you save and that uncollapses the ranges again?

**Comment by bledar** [comment]
This problem does not appear in all HTML documents.
I think this problem appears in some documents when the code is not structured as it should and VC tries to fixit but in fact does it worse.
Anyway, when I disable HTML formatting, the code should not change onSave.
I think the collapse problem is related with HTML formatting.  
![formating_problem](https://user-images.githubusercontent.com/4134276/38546255-741c7b58-3cac-11e8-8a82-6720fd4ef87b.jpg)

![collapsing problem](https://user-images.githubusercontent.com/4134276/38545509-7cca9840-3caa-11e8-9d99-b97504738e6a.gif)

**Comment by aeschli** [comment]
Please paste the code sample and steps.

**Comment by bledar** [comment]
## Before saving
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  <link rel="apple-touch-icon" sizes="57x57" href="%PUBLIC_URL%/favicons/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="%PUBLIC_URL%/favicons/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="%PUBLIC_URL%/favicons/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="%PUBLIC_URL%/favicons/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="%PUBLIC_URL%/favicons/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="%PUBLIC_URL%/favicons/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="%PUBLIC_URL%/favicons/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="%PUBLIC_URL%/favicons/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="%PUBLIC_URL%/favicons/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="%PUBLIC_URL%/favicons/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="%PUBLIC_URL%/favicons/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="%PUBLIC_URL%/favicons/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="%PUBLIC_URL%/favicons/favicon-16x16.png">
  <meta name="msapplication-TileColor" content="##4A81B4">
  <meta name="msapplication-TileImage" content="%PUBLIC_URL%/favicons/ms-icon-144x144.png">
  <meta name="theme-color" content="##4A81B4">
  <link rel="manifest" href="%PUBLIC_URL%/favicons/manifest.json">
  <link rel="shortcut icon" href="%PUBLIC_URL%/favicons/favicon.ico">
  <title>Gestionale React</title>
</head>
<body id="body">
  <noscript>
    You need to enable JavaScript to run this app.
  </noscript>
  <div id="root"></div>
</body>
</html>`
---
## After saving
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
    <meta name="theme-color" content="#000000">
    <link rel="apple-touch-icon" sizes="57x57"
      href="%PUBLIC_URL%/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60"
      href="%PUBLIC_URL%/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72"
      href="%PUBLIC_URL%/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76"
      href="%PUBLIC_URL%/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114"
      href="%PUBLIC_URL%/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120"
      href="%PUBLIC_URL%/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144"
      href="%PUBLIC_URL%/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152"
      href="%PUBLIC_URL%/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180"
      href="%PUBLIC_URL%/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"
      href="%PUBLIC_URL%/favicons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32"
      href="%PUBLIC_URL%/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96"
      href="%PUBLIC_URL%/favicons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16"
      href="%PUBLIC_URL%/favicons/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="##4A81B4">
    <meta name="msapplication-TileImage"
      content="%PUBLIC_URL%/favicons/ms-icon-144x144.png">
    <meta name="theme-color" content="##4A81B4">
    <link rel="manifest" href="%PUBLIC_URL%/favicons/manifest.json">
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicons/favicon.ico">
    <title>Gestionale React</title>
  </head>
  <body id="body">
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <div id="root"></div>
  </body>
</html>>`

**Comment by bledar** [comment]
## After saving
````<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
    <meta name="theme-color" content="#000000">
    <link rel="apple-touch-icon" sizes="57x57"
      href="%PUBLIC_URL%/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60"
      href="%PUBLIC_URL%/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72"
      href="%PUBLIC_URL%/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76"
      href="%PUBLIC_URL%/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114"
      href="%PUBLIC_URL%/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120"
      href="%PUBLIC_URL%/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144"
      href="%PUBLIC_URL%/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152"
      href="%PUBLIC_URL%/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180"
      href="%PUBLIC_URL%/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"
      href="%PUBLIC_URL%/favicons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32"
      href="%PUBLIC_URL%/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96"
      href="%PUBLIC_URL%/favicons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16"
      href="%PUBLIC_URL%/favicons/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="##4A81B4">
    <meta name="msapplication-TileImage"
      content="%PUBLIC_URL%/favicons/ms-icon-144x144.png">
    <meta name="theme-color" content="##4A81B4">
    <link rel="manifest" href="%PUBLIC_URL%/favicons/manifest.json">
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicons/favicon.ico">
    <title>Gestionale React</title>
  </head>
  <body id="body">
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <div id="root"></div>
  </body>
</html>````

**Comment by bledar** [comment]
I have found the problem. This problem was caused by a extension  [HTML Format](https://marketplace.visualstudio.com/items?itemName=mohd-akram.vscode-html-format).
