### ISSUE TITLE
Tasks return /bin/bash: exit code: 127 when "args" has values

### ISSUE THREAD

**Issue by GerardHH** [Microsoft/vscode#47493]
Hallo vscode developers,

It would appear that the newest version of vscode introduces a bug. Currently when I try to run a task with Ctrl+p -> Task task-name I get:
  ```
/bin/bash: autoreconf -i && ./configure: No such file or directory
  The terminal process terminated with exit code: 127
```
However tasks that have absent "args" keys seems to work though. The issue that most resembles this is https://github.com/Microsoft/vscode/issues/28489. This issue made me try a task without an "args" key.

Side note: I have a SDK that "sources" some environment variables. However v1.21.1 worked fine for me.

- VSCode Version: 1.22.1 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd x64
- OS Version: openSUSE Leap 42.3

Steps to Reproduce:

1. Run a task with an "args" key and filled in value (array with values).

Does this issue occur when all extensions are disabled?: Yes

My tasks.json:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "configure",
            "type": "shell",
            "command": "autoreconf -i && ./configure",
            "args": [
                "${CONFIGURE_FLAGS}",
                "--with-init-system=systemd",
                "--prefix="
            ],
            "problemMatcher": []
        },
        {
            "label": "build",
            "type": "shell",
            "command": "make install",
            "args": [
                "-j", "4",
                "DESTDIR=$PWD/build"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        },
        {
            "label": "clean",
            "type": "shell",
            "command": "make clean",
            "problemMatcher": []
        },
        {
            "label": "clean-untracked",
            "type": "shell",
            "command": "git clean",
            "args": [
                "-x",
                "-d",
                "-f"
            ],
            "problemMatcher": []
        }
    ]
}
```

**Comment by dbaeumer** [comment]
@GerardHH we fixed bugs around quoting of args which contain special characters like space. Since the comand you use with a shell has args we assume that the command needs to be quoted since it contains spaces. To fix this simply fold the commands into one command line doing:

```
"command": "autoreconf -i && ./configure ${CONFIGURE_FLAGS} --with-init-system=systemd --prefix="
```

I warned for awhile when an arg for a shell command had spaces to be folded into the command but sadly I mised the `&&` shell case. I apologize for this. Since handling spaces correctly was a long wanted request I would like to ask you to change your command to make it work again.

Please note that the same applies for your `clean-untracked`.

Ok for you to close ?

**Comment by GerardHH** [comment]
Yes! @dbaeumer you're completely right! 

Thank you for your time and I love the work all of you do with vscode!

**Comment by dbaeumer** [comment]
Thanks!
