### ISSUE TITLE
the update 1.22 vs code not working in Ubuntu 16.04

### ISSUE THREAD

**Issue by marciokuroki** [Microsoft/vscode#47496]
Does anybody knows if this version of vs code has any problem on Launching?

- VSCode Version: code_1.22.1-1522974421_amd64
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Update by download page.
2. Install by double clicking in .deb.
3. Try to lauch the vs code and it doesn't work. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
@marciokuroki what happens when you run `code --verbose` or `code --log debug` from a terminal?

**Comment by marciokuroki** [comment]
I'll try to run `code --verbose` or `code --log debug` and I'll put the log here

**Comment by marciokuroki** [comment]
Well, I've tried to reinstall the version of vs code and simply it works!
So I have to close this issue...
Thanks anyway, I really have no idea why didn't worked before.
If it happens again I'll try to be more detailed as possible.

**Comment by marciokuroki** [comment]
I installed again, but passing some days it happens again. Now I run `code --verbose` and it show this:
[1733:0418/155912.245117:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 15:59:12] Sending env to running instance...
[main 15:59:12] [ 'TypeError: Cannot convert undefined or null to object',
  '    at Function.keys (<anonymous>)',
  '    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:37:233',
  '    at Array.forEach (native)',
  '    at Object.t.assign (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:37:199)',
  '    at e.openInBrowserWindow (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:406:461)',
  '    at e.doOpen (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:400:880)',
  '    at e.open (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:397:176)',
  '    at e.startOpenWindow (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:297:283)',
  '    at e.start (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:296:711)',
  '    at e.call (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:295:280)',
  '    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:140:713)',
  '    at e.onMessage (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:140:549)',
  '    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:140:342',
  '    at e.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:94:344)',
  '    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:148:536)',
  '    at emitOne (events.js:96:13)',
  '    at Socket.emit (events.js:191:7)',
  '    at readableAddChunk (_stream_readable.js:178:18)',
  '    at Socket.Readable.push (_stream_readable.js:136:10)',
  '    at Pipe.onread (net.js:560:20)' ]
[main 15:59:12] Lifecycle#kill()

**Comment by marciokuroki** [comment]
@Tyriar, any help?! :smile:

**Comment by Tyriar** [comment]
I think this may have been fixed in the latest, could you try on the Insiders build? https://code.visualstudio.com/insiders/

**Comment by marciokuroki** [comment]
@Tyriar apparently now it is working fine! Since I've tried this version the problem didn't happen anymore.
Thanks!
