### ISSUE TITLE
Source control providers are not automatically removed when file closed

### ISSUE THREAD

**Issue by Wehrdo** [Microsoft/vscode#47495]
- VSCode Version: 1.22.1
- OS Version: Windows 10 Pro, Version 1709

Steps to Reproduce:

1. Open a workspace that is a git repository (repository A). As expected, repository A shows up in the "Source Control Providers" list.
2. Open a file from a different git repository (repository B), either through the "File > Open File..." menu, or by dragging onto the window. Now both repository A and repository B are listed as source control providers.
3. Close the newly opened file.
    **Expected behavior:** Repository B will be removed from the source control providers list, since no folders/files from that repository are open.
    **Actual behavior**: Both repositories remain listed, until a restart of Visual Studio Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by pedzed** [comment]
I find this very annoying. Have you found a solution?

Actually, I do not want another repository to open at all. When I `CTRL + O` (open file), I expect to open a single file. Not the entire repository it is associated with.
