### ISSUE TITLE
autoAttachChildProcesses does not work with Node running on WSL

### ISSUE THREAD

**Issue by fxlemire** [Microsoft/vscode#47497]
- VSCode Version: 1.22.1
- OS Version: Windows 10 Pro 1709, Build 16299.309

Problem: It does not seem possible to have the VS Code debugger attach itself to forked processes with Node running on WSL.

Steps to Reproduce:

1. Create the following script (taken from [release notes](https://github.com/Microsoft/vscode-docs/blob/master/docs/nodejs/nodejs-debugging.md#automatically-attach-debugger-to-nodejs-subprocesses)):

```js
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length / 2;

if (cluster.isMaster) {
  console.log(`Master ${process.pid} is running`);

  // Fork workers.
  for (let i = 0; i < numCPUs; ++i) {
    cluster.fork();
  }

  cluster.on('exit', (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
} else {
  // Workers can share any TCP connection
  // In this case it is an HTTP server
  http.createServer((req, res) => {
    res.writeHead(200);
    res.end('Hello world\n');
  }).listen(8000);

  console.log(`Worker ${process.pid} started`);
}
```

2. Add the following `.vscode/launch.json`:

```js
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Cluster",
      "program": "${workspaceFolder}/test.js",
      "autoAttachChildProcesses": true,
      "useWSL": true
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach Cluster"
      // "localRoot": "${workspaceFolder}",
      // "remoteRoot": "/mnt/c/Users/MYUSERNAME/Documents/test"
    }
  ]
}
```

3. Run with the `Cluster` config.

Result:

Only `Master XYZ is running` will print to the console. If you run from WSL, `Worker XYZ started` outputs properly, but attaching also isn't possible unless you specify the port (but then you can only attach to one instance).

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Yes, this feature is not supported for WSL.

**Comment by fxlemire** [comment]
Oh that's a bummer. Thanks for the amazingly quick reply. Will stay on the lookout for the next releases :+1:

**Comment by DarthSpock** [comment]
@weinand Any new update for this?

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
