### ISSUE TITLE
can i perform a vscode command in task.json

### ISSUE THREAD

**Issue by JasonLearning** [Microsoft/vscode#47499]
like perform "workbench.action.tasks.task1" after some task end

**Comment by JasonLearning** [comment]
maybe I did't express clearly. I mean if I want to execute some commands which depends on extensions like "cpp.task", how can I write task.json?

**Comment by dbaeumer** [comment]
@JasonLearning you can achieve this using `dependsOn`. See https://github.com/Microsoft/vscode-languageserver-node/blob/master/.vscode/tasks.json for an example.

OK to close.
