### ISSUE TITLE
ShellArgs preppended to task command

### ISSUE THREAD

**Issue by IAmHopp** [Microsoft/vscode#47492]
Issue Type: <b>Bug</b>

Hi,

Ever since I first set up my Code for personal use, I defined terminal.integrated.shellArgs.windows with a couple arguments for PowerShell. It was working fine up until friday's build.

PowerShell still loads fine if I start a new terminal but, more importantly, every time I try to run a task, the arguments from shellArgs are preppended to the command and, as a result, the task fails. [since they're just arguments, I'm getting the "is not recognized as the name of a cmdlet etc." error]

<hr />

Steps to reproduce:

1. Define some arguments in terminal.integrated.shellArgs.windows.
2. Start up a new terminal.
3. Run a task.

Expected results:

ShellArgs are used when opening the terminal, with the task running only the command specified.

Actual results:

ShellArgs are used when opening the terminal, but they're also getting preppended to the command of the task.

VS Code version: Code - Insiders 1.23.0-insider (95101bf3f6d00105621cdddb639ea62b95ea2468, 2018-04-06T08:49:48.798Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.2.0
mssql|ms-|1.3.0
team|ms-|1.122.0
java|red|0.22.0
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by chestertonic** [comment]
I also have noticed this issue. Using cmd.exe as integrated terminal and adding something like "/K init.bat" to shellArgs will prevent a task executed in the shell from happening. Also using the same version of Code Insiders as above.

**Comment by Tyriar** [comment]
This sounds like https://github.com/Microsoft/vscode/issues/47314, can you try on the latest version of Insiders?
