### ISSUE TITLE
The issue reporter can generate a GitHub issue to the wrong repository under some circumstances

### ISSUE THREAD

**Issue by teo-tsirpanis** [Microsoft/vscode#47508]
Issue Type: <b>Bug</b>

1. Open Issue Reporter
2. Select to file a Bug Report or a Performance Issue on an extension.
3. Without doing anything else, select to file a Feature Request.
4. Click "Preview on GitHub".
5. You will see an issue submission form on the repository of _the extension_, instead of this repository, despite there is no choice on _where_ to file Feature Requests.

I know this is an edge case. I discovered it while I was filing #47505. I mistakingly filed [VSCodeBeautify/#218](https://github.com/HookyQR/VSCodeBeautify/issues/218) during the process because I was very curious ~~again~~. 😛

My suggestion is to show the "File on" dropdown even on feature requests, to streamline the process for extensions as well.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by RMacfarlane** [comment]
@teo-tsirpanis Thanks for reporting! Changed to show the "File on" dropdown on feature requests.
