### ISSUE TITLE
Apply proper formatting without the need to save the file first

### ISSUE THREAD

**Issue by GuybrushX** [Microsoft/vscode#47509]
- VSCode Version:
Version 1.23.0-insider
Commit 95101bf3f6d00105621cdddb639ea62b95ea2468
Date 2018-04-06T08:49:48.798Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows 10 x64, ENG

Steps to Reproduce:

1. Create a new file, Untitled-1
2. Paste some HTML (probably the same for all source code in general)
3. No formatting gets applied

Expected behaviour:
Be able to change the file name in the Explorer from "Untitled-1" to "Untitled-1.html" or "Untitled-cs" etc. without saving it first. That way it would be possible to apply formatting to pasted source code without the need to save everything first.

This is useful if you just want to use VS Code for editing and formatting different HTML/code snippets.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by aeschli** [comment]
You don't need to save. Just change the editor mode to HTML (at to bottom, in the status bar on the right). Then open the context menu and choose format.
