### ISSUE TITLE
VSCode window sections blank or flashes

### ISSUE THREAD

**Issue by chryton** [microsoft/vscode#47503]
Issue Type: <b>Bug</b>

## Steps to Reproduce:

1. Launch VSCode (either fullscreen or in a window)
2. Notice flashing
3. Resize Window (up or down, fullscreen or not)
4. Notice it fixes it as some window sizes.

Flashing Example: https://t.co/iNkWeV9oBz

Referred here from my Twitter discussion with support: https://twitter.com/chrytonbaine/status/979424800945922048

**Does this issue occur when all extensions are disabled?:**
Unsure. It is difficult to reproduce already with extensions enabled. In the 5 times I tried running with extensions disabled it seemed to work correctly but the same can be said for stopping and restarting the application 5 regularly times in a row sometimes.

## Other Notes:

This has been happening for several months now, some days are worse than others. I've tried watching for extension updates that could be causing it but I haven't caught one yet that once disabled is the culprit consistently. This is also happening on both an iMac and a rMBP that I own; both of which have slightly different workspace setups.

Similar to #46842

---

VS Code version: Code - Insiders 1.23.0-insider (4971d889244a2e569ff03b7211c50e2a159e6e71, 2018-04-09T05:10:32.140Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-markdownlint|Dav|0.14.1
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.3.0
code-settings-sync|Sha|2.9.0
sort-lines|Tyr|1.6.0
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
Bookmarks|ale|0.18.2
project-manager|ale|0.25.0
alignment|ann|0.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
vue-snippets|hol|0.1.5
svg|joc|0.0.9
docthis|joe|0.6.0
vscode-liquid-snippets|kil|1.1.0
vue|liu|0.1.5
sublime-keybindings|ms-|3.0.3
language-liquid|nei|0.0.3
vuehelper|oys|0.1.0
vscode-css-peek|pra|2.1.0
magento-snippets|raf|0.1.3
sass-indented|rob|1.4.8
vue|sea|0.4.2
stylelint|shi|0.36.0
vscode-fileutils|sle|2.8.1
guides|spy|0.9.1
Align|ste|0.2.0
ayu|tea|0.14.0
wordpress-snippet|tun|1.1.2
twig|wha|1.0.2
JavaScriptSnippets|xab|1.5.0

(10 theme extensions excluded)

</details>

**Comment by gregcotten** [comment]
This happens to me as well!
