### ISSUE TITLE
Clarify how to exit disabled extension state from issue reporter

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#47506]
Currently, after using the `Reload Window with Extensions Disabled`, the `--disable-extensions` flag is persisted on subsequent `Reload Window` actions, so the state can only be exited by relaunching VSCode. If possible, this should be changed so that the flag persists only for that load. Regardless, how to revert back to old extension state is not explained in the UI.

In current insiders there is a notification shown when this state is entered, improve this to have a button to revert.

In the extensions viewlet, it would also be good to have the same button or text explaining the current state and how to revert to old extension state.

**Comment by x4m3** [comment]
yes please, i reloaded vscode with extensions disabled and now i can't get out of it.....

**Comment by borekb** [comment]
Also, the UI uses three methods to say that the extension is disabled, at the same time :)

![image](https://user-images.githubusercontent.com/101152/38688407-eabf6c78-3e70-11e8-9489-25d3e4d4289a.png)

Maybe the tooltip could be used to say that the extension will be re-enabled after reload (if that's the case).

**Comment by RMacfarlane** [comment]
Changed the behavior so that the flag isn't persisted when reloading, and now have an explanatory notification:

![screen shot 2018-06-07 at 4 43 34 pm](https://user-images.githubusercontent.com/3672607/41131808-433b4dea-6a72-11e8-9891-1060db8f07a0.png)

**Comment by borekb** [comment]
Very nice, @RMacfarlane!
