### ISSUE TITLE
Support proposed DecorationProvider api on custom views

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#47502]
Currently it looks like the DecorationProvider api, only applies to the explorer file tree. Can this be expanded to apply to custom view trees as well?

Maybe expand to include an optional viewId
```ts
registerDecorationProvider(provider: DecorationProvider, viewId?: string): Disposable
```

The `DecorationProvider.provideDecoration` will also need to be updated to support TreeItem (or the item element itself?) 
```ts
provideDecoration(uriOrTreeItem: Uri | TreeItem, token: CancellationToken): ProviderResult<DecorationData>;
```

Also while its probably not ideal, I did wonder if setting a `resourceUri` on a TreeItem would trigger the decoration, but it doesn't either.

/cc @sandy081

**Comment by jrieken** [comment]
Yes, plan is to make the `DecorationProvider` api public. However, but its nature it decorates URIs wherever they show. Things we should do IMO

* allow tree view item to be decorated
* make the decoration provider api general available

**Comment by eamodio** [comment]
Hrm, showing decorations where ever a URI is seems like it *could* be very undesirable in many cases. If I have a custom view that I want to decorate items with (that represent files) and my decorations would now show everywhere they would now conflict with the scm/git decorations and vice versa. If that was still the desired behavior, it would be nice if the custom view (or custom view item) could opt-in (or out) of global decorations.

Will there be a way to decorate custom tree items then (that would not affect anything outside a specific tree)? Maybe those decorations could be applied directly on the custom tree item itself (i.e. props or something provided to the TreeItem)?

For example, I am definitely looking for ways of bolding, italicising, coloring, badging tree items for the [CodeStream](http://codestream.com) extension I am currently working on.

**Comment by sandy081** [comment]
I see there are two kinds of requests here from a custom view perspective.

1. Apply the file decorations also to custom view if it is based on URIs. This can be opted out by user using settings just like how it is now.
2. Allow extensions to decorate custom view items.

First one looks sensible but there are no plans yet to support second one.

**Comment by eamodio** [comment]
I think so, but #1 is more nuanced imo.

I honestly was more thinking about #1 as a way to get #2 -- use "custom" uris (`foo://whatever`) to attach to the resourceUri and then use the `DecorationProvider` to only respond to those custom uris. Which would in theory provide decorations for the custom view. But the flip side to this, is that would make all of the explorer decorations automatically apply to all custom views (if they were using real file uris) and that may or may not be desirable.

Maybe an alternative would be to add  a way (property or something) on the custom view to opt-out of decorations if they wanted.

**Comment by sandy081** [comment]
Adding to July as stretch item.

**Comment by sandy081** [comment]
Added support for resource based decorations in custom views. Decorations are shown automatically when a resource uri is provided and there are decorations for that resource. These can be controlled by user using the existing following setting

```json
```
