### ISSUE TITLE
Do not prompt the user to "Select a task to show its output" when there is only one task running

### ISSUE THREAD

**Issue by teo-tsirpanis** [microsoft/vscode#47505]
Issue Type: <b>Feature Request</b>

(I think the title is descriptive enough)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by alexr00** [comment]
To verify, start one task (such as the Build VS Code task). Then run the Tasks: Show Running Tasks command. Verify that the terminal for the task you started just shows without you having to select from another quick pick.
