### ISSUE TITLE
IntelliSense suggestions for values in .SASS files doesn't work 

### ISSUE THREAD

**Issue by Korlic85** [Microsoft/vscode#47516]
- VSCode Version: 1.22.1 

When I use intelliSense in .scss files everything work as desire, vscode display automatic suggestions for values after I choose a property, but when I choose to work in a .sass file format, autocomplete works only for properties but not for values.  vscode show suggestions for values only when I start witting.  

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
We have no built-in support for Indented SASS, you need to find an extension.

**Comment by Korlic85** [comment]
Any plans for adding built-in support for Indented SASS?
