### ISSUE TITLE
Code hints use npm on yarn projects

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#47515]
- Have a project with yarn.lock.
- Have some code that shows a `...` to install the @types file. In my case, `import { Provider } from 'react-redux';`
- Run the code hint
- A package-lock.json is added to my project

Is it possible for it to detect npm vs yarn and pick the correct one?

**Comment by mjbvz** [comment]
Thanks. This is already tracked upstream by https://github.com/Microsoft/TypeScript/issues/23231 and https://github.com/Microsoft/TypeScript/issues/19997
