### ISSUE TITLE
Spanish and French translations mistranslate the spacing in global actions

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4751]
[The string that adds a category to an action label](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/quickopen/browser/commandsHandler.ts#L266
) to be displayed in the global command palette is mistranslated by the Spanish and French translations.

**Spanish** - removes the space in front of the `:`

![image](https://cloud.githubusercontent.com/assets/22350/14111824/84f81c80-f5cc-11e5-8a77-c9d1911b2203.png)

**French** - adds a space before the `:`.

![image](https://cloud.githubusercontent.com/assets/22350/14111877/c8a493b4-f5cc-11e5-9d14-50cc59c4dc83.png)

**Comment by joaomoreno** [comment]
Setting to `important` to catch your eye.

**Comment by dbaeumer** [comment]
@johnliu2016 can you cycle that back to the translation team?

**Comment by johnliu2016** [comment]
Cloned this issue to translation team for loc fix.

**Comment by dbaeumer** [comment]
@johnliu2016 thanks!

**Comment by johnliu2016** [comment]
@joaomoreno missing space in ESN build is fixed, while the standard rule in French is a space before a colon.
