### ISSUE TITLE
Build 1.22.1 breaking Platform IO build tasks

### ISSUE THREAD

**Issue by fmuntean** [Microsoft/vscode#47514]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

1. Upgrading the VScode to this version 
2. Build any existing platform IO project 
3. The build task gets stuck and no progress is displayed nor the task finish.

This build tasks were working fine just before the update. (minutes before)

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/47350
