### ISSUE TITLE
Telemetry is enabled by default

### ISSUE THREAD

**Issue by aloshka** [Microsoft/vscode#47513]
Telemetry should be opt in not opt out after an update.

**Comment by joaomoreno** [comment]
Telemetry is opt out. Once you do, it is always off, though, regardless of whether you get an update.

**Comment by TankTheFrank** [comment]
@joaomoreno I wander how this "opt out" policy will play out with GDPR for us european users.

Gotta love the double speak though, when on a payroll of a large corporation is "opt out telemetry" when not is "unauthorized access".

What exactly is this "usage data" that you collect, send to your servers and store for an unspecified period of time?

Do you send when I start it up and when I close it? My OS and hardware details? My user name? My email? My name? The contacts from my address book? My credit card information? When I type and how fast I type? What I type? The complete homemade recipe for venereal diseases I just finished writing using VS Code as editor?

**Comment by joaomoreno** [comment]
Here's a bit more information on telemetry and VS Code:

- https://privacy.microsoft.com/en-us/privacystatement
- https://code.visualstudio.com/Docs/supporting/faq#_how-to-disable-telemetry-reporting

If you want to dig deeper, simply search our sources of `__GDPR__`: https://github.com/Microsoft/vscode/search?utf8=%E2%9C%93&q=__GDPR__&type=
