### ISSUE TITLE
ctrl+k does not clear terminal in 1.22.1

### ISSUE THREAD

**Issue by nathanwinder** [Microsoft/vscode#47519]
Issue Type: <b>Bug</b>

# Steps
1. With no custom key bindings in keybindings.json
2. In the termial enter a command e.g. "> dir"
3. With focus on the terminal "ctrl+k"
4. Actual: "^K" appears on terminal
5. Expected: Terminal should clear, "ctrl+k" is mapped to "workbench.action.terminal.clear" when "terminalFocus" in Default Keybindings.

# Workaround
6. Open keybindings.json and add: { "key": "ctrl+k" ,"command": "workbench.action.terminal.clear", "when": "terminalFocus" }
7. Save changes
8. Go back to terminal and "ctrl+k" 
9: Actual/Expected: Terminal clears

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|15.80GB (2.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\repos\bdd-docs\Perficient.Tools.BddDocs\readme.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.0
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
githd|hui|1.1.3
vscode-styled-components|jpo|0.0.16
auto-comment-blocks|kev|1.0.1
dotenv|mik|1.0.1
csharp|ms-|1.14.0
team|ms-|1.122.0
debugger-for-chrome|msj|4.3.0
vscode-jest|Ort|2.6.4
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0
vscode-todo-highlight|way|0.5.12
markdown-all-in-one|yzh|1.1.2

</details>

**Comment by Tyriar** [comment]
This is by design, see "Q: Why is Cmd+k/Ctrl+k not clearing the terminal?" in https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions
