### ISSUE TITLE
V 1.22: Go To Definition Not Working (Javascript) 

### ISSUE THREAD

**Issue by fouadmasoud** [Microsoft/vscode#47524]
Issue Type: <b>Bug</b>

Right-click on Javascript method of class
Select Go-To-Defintion
UI reports definition doesn't exist.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|3, 1, 1|
|Memory (System)|16.00GB (5.45GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vsc-material-theme|Equ|1.5.1
solidity|Jua|0.0.37
material-icon-theme|PKi|3.3.0
vscode-docker|Pet|0.0.26
sort-lines|Tyr|1.6.0
react-pure-to-class-vscode|ang|1.1.4
snapshot-tools|asv|0.0.7
vscode-custom-css|be5|2.7.0
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.1.1
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
prettier-vscode|esb|1.2.2
shell-format|fox|1.1.1
css2react|got|0.0.6
terraform|mau|0.0.23
dotenv|mik|1.0.1
vscode-fileheader|mik|0.0.2
chai-snippets|nwh|0.1.0
indent-rainbow|ode|0.7.2
vscode-journal|paj|0.5.0
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.6.2
JavaScriptSnippets|xab|1.5.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please share some example code or small example project

**Comment by mjbvz** [comment]
Does this still happen if you disable all extensions?

**Comment by yoisel** [comment]
@mjbvz I am facing a very similar issue, and it does happen with all extensions disabled.
I am not using react, I am using angularjs with es6 (no modules, just ES6 classes and babel).
Doing go-to-definition only works for me if the file that contains the target symbol is already open in vscode, if it is not open, it will not find it.

**Comment by mjbvz** [comment]
@yoisel Try creating a [jsconfig.json](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) file at the root of your project

**Comment by fouadmasoud** [comment]
My issue was because I had disabled TypeScript and JavasScript Language Features built in extension so that I can work with FlowType. But good to know about jsconfig.json thank you :).
