### ISSUE TITLE
Snippet Body - Odd escape \\ behavior

### ISSUE THREAD

**Issue by linux4life798** [Microsoft/vscode#47529]
# Problem
Maybe I'm missing something, but it seems that the literal char `\` is not being translated properly in the body of markdown snippets.

I would expect `\\` in the snippet body would always yield one literal `\`.
Four backslashes (`\\\\`) should yield `\\`, and six backslashes (`\\\\\\`) should yield `\\\`.
Instead, I see that six backslashes(`\\\\\\`) in the body yields only two `\\`.

This is relevant to my snippets for latex inside my markdown files.

# Environment
- VSCode Version: 1.23.0-insider
- OS Version: Debian GNU/Linux testing (buster) - amd64

# Test
Steps to Reproduce:
1. Launch `Preferences: Configure User Snippets` from the `Command Palette`
2. Select a new markdown or an existing `markdown.json`
3. Add the following snippet:
```json
"Test_Escape": {
		"prefix": "tesc",
		"body": [
			"\\\\\\"
		],
		"description": "Tests Snippet Escape"
	}
```
4. Open a markdown file and trigger the snippet.
5. Note that it only shows two `\` chars, not three

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
See https://github.com/Microsoft/vscode/issues/33933#issuecomment-328793257
