### ISSUE TITLE
Set default Emmet unit?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#47522]
Issue Type: <b>Feature Request</b>

Right now, as it always has, Emmet defaults to `px`, so typing `ml5` will get you `margin-left: 5px;`

I realize it will use any unit if I include a unit, as in `ml5rem`

Is it possible to have a Workspace setting for what the default unit is?  In a particular project we might be using `rem`s everywhere.  Others the default `px` is fine.

just a thought.

VS Code version: Code - Insiders 1.23.0-insider (4971d889244a2e569ff03b7211c50e2a159e6e71, 2018-04-09T05:10:32.140Z)
OS version: Darwin x64 17.5.0

**Comment by ramya-rao-a** [comment]
You can use the `emmet.preferences` setting to set `css.unitAliases`, `css.intUnit`, or `css.floatUnit`.

The various emmet preferences supported by VS Code are documented on the [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration) page

The documentation of each of these preferences is in [Emmet Preferences](https://docs.emmet.io/customization/preferences/)
