### ISSUE TITLE
Terminal selection is drawn above foreground

### ISSUE THREAD

**Issue by AndreasBackx** [microsoft/vscode#47523]
Issue Type: <b>Bug</b>

When selecting text in the terminal, the text is behind the selection background. If the value for the selection background is opaque, then the text is invisible. I'd expect it to be behind the text like it is in the editor's color configuration.

With an opaque color:
![Screenshot](https://i.imgur.com/oHi1R29.png)

With a more transparant color:
![Screenshot](https://i.imgur.com/3HKpgMg.png)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.15.14-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 2575)|
|Load (avg)|1, 1, 1|
|Memory (System)|15.68GB (4.89GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.0
python|ms-|2018.3.1
sublime-keybindings|ms-|3.0.3

</details>

**Comment by tweakimp** [comment]
Maybe it is supposed to be this way, just the tooltip that this color needs to be opaque is missing. Compare with `editor.selectionHighlightBackground`

**Comment by AndreasBackx** [comment]
@tweakimp `editor.selectionHighlightBackground` places the foreground above the background as expected.

![Screenshot](https://i.imgur.com/tx0g8UG.png)

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/720

You need to use a transparent selection color currently which is less than ideal.

**Comment by GlenPerkins** [comment]
Yes, eventually this "background" really needs to be in the background, not painted on top of everything else. As it is, the best you can do with it is to use transparency to make it look as if you've put colored plastic tape over your selection, which dulls it and changes its foreground color.

**Comment by luxcium** [comment]
is it possible to transition from "selection" to

**Comment by Tyriar** [comment]
@luxcium we probably do want selection foreground eventually be customizable as well, that way the user can choose their preferred style as set fg/bg colors has some great accessibility benefits. But we probably shouldn't move on this issue until the canvas renderer is removed (and replaced with https://github.com/xtermjs/xterm.js/pull/1790)

**Comment by tweakimp** [comment]
@Tyriar any news on this issue? [The one you linked is merged](https://github.com/xtermjs/xterm.js/pull/1790), but this issue is still a problem.

**Comment by Tyriar** [comment]
@tweakimp we're not using the webgl renderer yet

**Comment by Tyriar** [comment]
This issue is blocked on the webgl renderer being stabilized, see the issue query: https://github.com/xtermjs/xterm.js/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Faddon%2Fwebgl

**Comment by marvingreenberg** [comment]
Just a note, this breaks any customization of terminal selection color, but maybe that's obvious.

![selection](https://user-images.githubusercontent.com/216707/68952403-ca0f3980-078d-11ea-9c42-703076f1156b.png)

**Comment by Tyriar** [comment]
@marvingreenberg see https://github.com/microsoft/vscode/pull/84440
