### ISSUE TITLE
Webview with retainContextWhenHidden does not receive messages while not focused

### ISSUE THREAD

**Issue by Marus** [microsoft/vscode#47534]
- VSCode Version: 1.23.0-insider
- OS Version: macOS 10.3.4

If you have created a web view using the new vscode.window.createWebview api, with retainContextWhenHidden set to true any messages that are sent to the web view using the webview.postMessage method will not be received (either while it is in the background - or when it regains focus).

To me this seems to limit the usefulness of the API - as you cannot send data to your webview if you cannot guarantee it is currently visible.

For example, in the extension that I develop (Cortex-Debug - https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug) , one of the features is an SWO decoding and graphing tool for use when debugging ARM Cortex-M microcontrollers. This data can be received at any time during the debug process. My intention is to use the new webview functionality to be able to present these graphs within the VSCode interface.

Current releases use the existing previewHTML method, and I create a WebSocket server to communicate in real-time between the html preview and the extension - but this has several drawbacks (extra complexity of running said WebSocket server; preview HTML is not persistent when in background, etc). While the new method is an improvement for the communication between the extension and the HTML view; not being able to communicate while the HTML webview is not visible is less than stellar - as it still essentially means having to load all data that occurred since it was last visible (this can be 10s if not 100s of messages being backlogged every second on faster target devices) which is not much better than a full refresh.

**Comment by mjbvz** [comment]
This is by-design. `retainContextWhenHidden` does not guarantee that the webview content itself will be kept alive when a webview is in the background, only that it will be correctly restored when the webview becomes visible again

Does your webview need to be stateful?

**Comment by Marus** [comment]
It would certainly be better for it to be stateful (and even better were it able to receive messages while in the background). With the current versions I end up storing all of the data collected in memory and when the previewHTML content is reloaded as it always is I reconnect to the WebSocket server I create in the extension and it reloads, processes and graphs all the data that has been collected from the external target. This can be very slow, as there can be very large amounts of data for it to process. (In extreme cases the debug probe can be collecting up to about 1MB of raw data per second, this is of course even larger once I have parsed the raw bitstream and it has been converted into JavaScript values that I am using in the extension and webview). This can lead to a poor user experience as if there is a lot of data it will often take several seconds to actually redraw things in the webview as it has to wait to load and process very large amounts of data.

What makes it even more inconvenient for my purposes is that when debugging (which is while my extension is being used) you often get moved away from your webview automatically - as VSCode will automatically switch focus to other editors.

The current proposed API would be an improvement (I would only need to load and process the data that has been received since it was last put into an inactive state once it becomes active again). For my purposes though the ideal situation is that the webview would be kept alive with its JavaScript still running (the actual redrawing and things like requestAnimationFrame would not need to run of course).

Either way though - I do think this is a big improvement on the status quo with the previewHTML command.

**Comment by mjbvz** [comment]
Yes we may relax this at some point but it is far easier to add features/functionality than take it way.

**Comment by mjbvz** [comment]
To verify using cat coding:

* Enable `retainContextWhenHidden` [here](https://github.com/microsoft/vscode-extension-samples/blob/29d5a0ee71fcb759ac7d7c1f5b40663f624b2f4d/webview-sample/src/extension.ts#L69)
* When the webview [is created](https://github.com/microsoft/vscode-extension-samples/blob/29d5a0ee71fcb759ac7d7c1f5b40663f624b2f4d/webview-sample/src/extension.ts#L106), add a `setInterval` loop that posts messages of some sort to the webview
* [In the message handler](https://github.com/microsoft/vscode-extension-samples/blob/29d5a0ee71fcb759ac7d7c1f5b40663f624b2f4d/webview-sample/media/main.js#L30), `console.log` these messages.

Then run cat coding and confirm that when the webview is hidden (but not closed) messages can still be posted to it

**Comment by eamodio** [comment]
@mjbvz I'm guessing it is because of these changes, but both GitLens' Welcome & Settings, and  CodeStream's webview no longer works at all in today's insiders.

**Comment by mjbvz** [comment]
Will investigate. It was not broken by this change

**Comment by alexr00** [comment]
Verification blocked by https://github.com/microsoft/vscode/issues/74568
