### ISSUE TITLE
powershell run script error

### ISSUE THREAD

**Issue by xiemms** [Microsoft/vscode#47539]
Issue Type: <b>Bug</b>

i use cmd to run 'set  EGG_SERVER_ENV=stage  && npm run dev' . it's ok
but i use vscode  powershell to run this script it's wrong
![github1](https://user-images.githubusercontent.com/16432738/38534943-99395e0e-3cb3-11e8-9dbc-003971a2aa89.png)
![github2](https://user-images.githubusercontent.com/16432738/38534950-abf675f4-3cb3-11e8-8648-c8e932c622bd.png)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|Memory (System)|11.91GB (3.07GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
eggjs|ati|0.3.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
python|ms-|2018.3.1
cpptools|ms-|0.16.1
debugger-for-chrome|msj|4.3.0
vetur|oct|0.11.7
vscode-wechat|qin|0.0.6

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment]
The first example uses cmd. The second is power shell. `&&` does not work in powershell

**Comment by xiemms** [comment]
thx. 
the  ‘power shell’ Chinese translation like ‘cmd’ 
I didn't notice
