### ISSUE TITLE
markdown preview cannot differentiate same header

### ISSUE THREAD

**Issue by AlanWalk** [Microsoft/vscode#47537]
Hi, I'm the author of [Markdown TOC](https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-toc).
I have a issue In my repository, Do you have any idea?
Issue link: https://github.com/AlanWalk/markdown-toc/issues/37

**Comment by mjbvz** [comment]
Repo:

1. For the markdown:

```md
<!-- TOC -->

- [Test](#test)
- [Test](#test-1)

<!-- /TOC -->

## Test

## Test
```

1. Open the markdown preview
1. Click on the second `test` link in the preview

**Expected**
Scrolls to second `Test` header

**Actual**
Noop
