### ISSUE TITLE
No color theme on typescript files

### ISSUE THREAD

**Issue by pajarraco** [Microsoft/vscode#47535]
Issue Type: <b>Bug</b>

I update to versions 1.22.1 on Mac ox10.13.4

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 x 3400)|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (5.75GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-generate-getter-setter|DSK|0.5.0
EditorConfig|Edi|0.12.1
minify|Hoo|0.3.0
vscode-docker|Pet|0.0.26
ejs-language-support|Qas|0.0.1
code-settings-sync|Sha|2.9.0
html-snippets|abu|0.2.1
project-manager|ale|0.25.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.8
git-extension-pack|don|0.1.3
githistory|don|0.4.0
gitlens|eam|8.2.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
php-debug|fel|1.12.2
php-pack|fel|1.0.1
auto-rename-tag|for|0.0.15
search-node-modules|jas|1.3.0
typoscript|jig|0.0.2
angular-essentials|joh|0.3.2
Angular2|joh|2.16.1
vscode-scss|mrm|0.6.2
mssql|ms-|1.3.0
debugger-for-chrome|msj|4.3.0
angular2-inline|nat|0.0.17
sass-helper|ram|0.0.2
vscode-icons|rob|7.22.0
sass-indented|rob|1.4.8
guides|spy|0.9.1
code-spell-checker|str|1.6.6
vscode-angular-support|vis|0.1.4
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0
vscode-open-in-github|ziy|1.3.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
What is the language mode of the file (shown in the lower right corner of the status bar)? Does this happen when you disable all extensions?

**Comment by pajarraco** [comment]
Hi, is fixed now, I disabled all extensions and I put it back up again and it fixes.

Thanks
