### ISSUE TITLE
Super annoying message, please leave me alone

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#4754]
Saw this 3 times today. Please add a leave me alone button.

![image](https://cloud.githubusercontent.com/assets/5047891/14114163/4d197bc4-f5d6-11e5-9ac3-42f5613fc978.png)

**Comment by joaomoreno** [comment]
I'll add it. But we want it to be annoying, [because](https://github.com/msysgit/msysgit/releases).

**Comment by alexandrudima** [comment]
I like how you use because :). Because internet :).
