### ISSUE TITLE
VSCode Insiders after 1.23.0-insider upgrade

### ISSUE THREAD

**Issue by battewr** [Microsoft/vscode#47542]
Issue Type: <b>Bug</b>

Note: Same configuration works on 1.22.1 (main line).
Note: Same configuration worked before upgrade to 1.23.0-insiders

1. Project with NPM run task as build commnd
2. Upgrade to 1.23.0
3. Build command no longer functions

Terminal Log during build command (ctrl-shift-b):
> Executing task: npm run build <

-Command : The term '-Command' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:1 char:1
+ -Command npm run build
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

My Build Task:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "Backend\\tsconfig.json",
            "option": "watch",
            "problemMatcher": [
                "$tsc-watch"
            ]
        },
        {
            "type": "typescript",
            "tsconfig": "Backend\\tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ]
        },
        {
            "type": "npm",
            "script": "build",
            "path": "UX/",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "promptOnClose": true,
            "problemMatcher": []
        }
    ]
}

VS Code version: Code - Insiders 1.23.0-insider (95101bf3f6d00105621cdddb639ea62b95ea2468, 2018-04-06T08:49:48.798Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (5.23GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
typelens|kis|1.5.0
code-beautifier|mic|2.0.3
python|ms-|2018.3.1

</details>

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/47314
