### ISSUE TITLE
 Cannot read property 'node' of null

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#47548]
Issue Id: <b>63596b68-0dcc-c826-1b35-9dd3ab1dd1f5</b><br /><br />*Versions* <br />- 1.22.1<br />-  6c22e21cdcd6811770ddcc0d8ac3174aaad03678<br />-  6b4d53cdab8bcae1eaaa4934d93c077319b573db<br />*Stack* <br />TypeError: Cannot read property 'node' of null<br />[/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.ts#478:20 (getValueInRange2)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.ts#L478:20 (getValueInRange2))<br />[/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.ts#460:19 (getValueInRange)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.ts#L460:19 (getValueInRange))<br />[/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBuffer.ts#94:25 (getValueInRange)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBuffer.ts#L94:25 (getValueInRange))<br />[/vs/editor/common/model/textModel.ts#752:22 (getValueInRange)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/common/model/textModel.ts#L752:22 (getValueInRange))<br />[/vs/editor/contrib/multicursor/multicursor.ts#198:34 (create)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/contrib/multicursor/multicursor.ts#L198:34 (create))<br />[/vs/editor/contrib/multicursor/multicursor.ts#743:26 (_createState)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/contrib/multicursor/multicursor.ts#L743:26 (_createState))<br />[/vs/editor/contrib/multicursor/multicursor.ts#707:38 (_update)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/contrib/multicursor/multicursor.ts#L707:38 (_update))<br />[/vs/editor/contrib/multicursor/multicursor.ts#691:9 (call)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/contrib/multicursor/multicursor.ts#L691:9 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/editor/common/commonCodeEditor.ts#994:37 (call)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/common/commonCodeEditor.ts#L994:37 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/editor/common/controller/cursor.ts#397:21 (_emitStateChangedIfNecessary)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/common/controller/cursor.ts#L397:21 (_emitStateChangedIfNecessary))<br />[/vs/editor/common/controller/cursor.ts#194:7 (setStates)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/common/controller/cursor.ts#L194:7 (setStates))<br />[/vs/editor/common/controller/cursor.ts#325:7](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/editor/common/controller/cursor.ts#L325:7)<br />    at t.executeEdits (out/vs/workbench/workbe<br />

**Comment by rebornix** [comment]
We haven't seen the error for a long time, closing as obsolete.
