### ISSUE TITLE
 Cannot read property 'removed' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#47551]
Issue Id: <b>162a6711-1692-02dd-422c-623072aa4a1a</b><br /><br />*Versions* <br />- 1.22.1<br />*Stack* <br />TypeError: Cannot read property 'removed' of undefined<br />[/vs/workbench/parts/debug/electron-browser/breakpointWidget.ts#76:28 (call)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/debug/electron-browser/breakpointWidget.ts#L76:28 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/workbench/parts/debug/common/debugModel.ts#860:32 (setExceptionBreakpoints)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/debug/common/debugModel.ts#L860:32 (setExceptionBreakpoints))<br />[/vs/workbench/parts/debug/electron-browser/debugService.ts#906:15 (onComplete)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L906:15 (onComplete))<br />[/vs/base/common/winjs.base.js#1185:0 (_notify)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L1185:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0 (_run)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L1083:0 (_run))<br />[/vs/base/common/winjs.base.js#1051:0 (completeDispatch)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L1051:0 (completeDispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#51:5 (clb)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/debug/node/v8Protocol.ts#L51:5 (clb))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#136:6 (dispatch)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/debug/node/v8Protocol.ts#L136:6 (dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#104:11 (handleData)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/debug/node/v8Protocol.ts#L104:11 (handleData))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#41:8](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/debug/node/v8Protocol.ts#L41:8)<br />    at emitOne (events.js:96:13)<br />    at Socket.emit (events.js:191:7)<br />    at readableAddChunk (_stream_readable.js:178:18)<br />    at Socket.Readable.push (_stream_re<br />

**Comment by weinand** [comment]
workaround is kludgy.
A proper fix would live on the receiving side.

**Comment by isidorn** [comment]
Makes sense, let me fix that.
