### ISSUE TITLE
Task Runner: Define multiple commands

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#4756]
- VSCode Version: 0.10.11
- OS Version: Mac OS X El Capitan

I would like to be able to specify multiple commands in a Task Runner. Right now, only one command is supported. Is the best way to do this with a shell script?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/981
