### ISSUE TITLE
问题面板的bug

### ISSUE THREAD

**Issue by qiujie8092916** [Microsoft/vscode#47568]
Issue Type: <b>Bug</b>

问题面板能记录当前工作区的项目用了eslint等代码规范工具时，当前打开文件的一些错误，但是当当前文件关闭时，问题面板不能及时地隐藏已经关闭的文件的问题。
当我关闭了所有选项卡时（未打开文件），问题面板依然还记录着之前打开的文件检查到的问题

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_18710999|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.5.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
jquerysnippets|don|0.0.1
gitlens|eam|8.2.0
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.2.2
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.9.0
vscode-fileheader|mik|0.0.2
vetur|oct|0.11.7
html-snippets|wge|0.1.5

</details>

**Comment by dbaeumer** [comment]
@qiujie8092916 can you please provide the description in English and provide steps on how to reproduce this. I don't see the problems with the ESLint extension. Errors are gone when closing files, except the ESLint errors where produce by the ESLint task.

**Comment by navono** [comment]
brief description:
> Use ESlint tool in project, and when opened file failed to follow some rules, the `Question` panel show the errors. When close the file, the errors in `Question` panel didn't disappear, event when all file closed.

I think this is not a problem, I also met this situation.

**Comment by dbaeumer** [comment]
How did you get the errors in the first place. By running a ESLint task or by opening the file and closing it.

**Comment by qiujie8092916** [comment]
after opening the file and closing it
@dbaeumer

**Comment by dbaeumer** [comment]
Not good. Can you provide me with a GitHub repository I can clone and steps on how to reproduce. It doesn't reproduce for me locally.

**Comment by qiujie8092916** [comment]
Is due to the config of my project?
