### ISSUE TITLE
Make debugger respect "files.exclude"

### ISSUE THREAD

**Issue by tsando** [Microsoft/vscode#47567]
Hi,

Similar to the close issue here https://github.com/Microsoft/vscode/issues/3215, I don't seem able to make the debugger respect the `files.exlcude` list I have in my Workspace settings:

```
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/node_modules": true,
    }
}
```

When I start debugging, the call stack shows a lot of entities which are inside the node_modules as shown below:

![screen shot 2018-04-10 at 10 27 54](https://user-images.githubusercontent.com/13929456/38548486-db14a766-3ca9-11e8-9460-6c98d11c8760.png)

Would appreciate if you have any ideas how I can fix this. Thanks!

**Comment by weinand** [comment]
Please see https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome for how to to skip files you are not interested in.
