### ISSUE TITLE
Can't enable column delecting mode

### ISSUE THREAD

**Issue by bskydive** [Microsoft/vscode#47560]
Issue Type: <b>Bug</b>

assign to "columnSelecting" shift+alt+ins (like in webstorm)
erase all other assigned actions to shift+alt+ins
try to hit them in editor
shows popup warning in right down corner:
Cannot read property 'lineNumber' of undefined

disabling all extensions, assigning another keys won't help.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.4.120-45-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G (4 x 2700)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.27GB (1.39GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.27
awesometypescriptproblemmatcher|Jua|0.3.0
code-settings-sync|Sha|2.9.0
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
copy-relative-path-and-line-numbers|ezf|0.2.8
vscode-npm|fkn|3.3.0
vscode-jetbrains-keybindings|isu|0.1.5
Angular2|joh|2.16.1
camelcasenavigation|map|0.3.42
debugger-for-chrome|msj|4.3.0
bracketeer|pus|1.1.0
gitlink|qez|0.4.2
subtle-brackets|raf|2.1.1
vscode-icons|rob|7.22.0
autoimport|ste|1.5.3
language-stylus|sys|1.9.1

(1 theme extensions excluded)

</details>

**Comment by bskydive** [comment]
![default](https://user-images.githubusercontent.com/4169563/38542506-b47377b2-3caa-11e8-96bb-66084dbab4c8.png)

**Comment by bskydive** [comment]
I've try many variants. Column selecting mode just won't work on any key bindings.

[keybindings.zip](https://github.com/Microsoft/vscode/files/1908770/keybindings.zip)

my full settings can be loaded by https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
https://gist.github.com/bskydive/8878b3d6d3e679358935d34983d9ffe1

**Comment by alexandrudima** [comment]
@bskydive `columnSelect` is unfortunately not a command that can be bound via `keybindings.json`. That command is invoked by the mouse handling code when doing a specific mouse gesture.

These are, for example, commands that can be used in the `keybindings.json`:

```
{ "key": "shift+alt+cmd+down",    "command": "cursorColumnSelectDown",
                                     "when": "textInputFocus" },
{ "key": "shift+alt+cmd+left",    "command": "cursorColumnSelectLeft",
                                     "when": "textInputFocus" },
{ "key": "shift+alt+cmd+pagedown", "command": "cursorColumnSelectPageDown",
                                     "when": "textInputFocus" },
{ "key": "shift+alt+cmd+pageup",  "command": "cursorColumnSelectPageUp",
                                     "when": "textInputFocus" },
{ "key": "shift+alt+cmd+right",   "command": "cursorColumnSelectRight",
                                     "when": "textInputFocus" },
{ "key": "shift+alt+cmd+up",      "command": "cursorColumnSelectUp",
                                     "when": "textInputFocus" },
```

**Comment by bskydive** [comment]
Thanks, I will search the pluginfor that.
