### ISSUE TITLE
Provide an API to fetch running task executions

### ISSUE THREAD

**Issue by alpaix** [Microsoft/vscode#47563]
Our extension needs to determine which tasks are running at any point in time. Is it possible to add a query to return a list of active task executions?

**Comment by dbaeumer** [comment]
The API no provides a getter for taskExecutions. This returns all active task executions.

@alpaix please note that I did another change to the API. Reason being that the task system has old `0.1.0` tasks and new `2.0.0` tasks. The old once are executed in the Output panel and therefore not remotable right now and might never be :-). For LiveShare we can IMO argue that only the 2.0.0 tasks are remotable. However to make the API consistent it return all tasks. But you can now pass in a filter to `fetchTasks` which filters the result. TO only get the new task call

```
vscode.workspace.fetchTasks({ version: "^2.0.0" }).then(...)
```
