### ISSUE TITLE
Impossible to fold my case

### ISSUE THREAD

**Issue by clementjolliet** [Microsoft/vscode#47579]
Hello everyone,
I'm having an issue with VS Code since the last update I guess (yesterday approximately). It is not impossible to me to fold the case in my switch case. As I am coding a chatbot which works with a big switch case structure, it is very annoying. As you can see in the screenshot, the "-" is not there anymore.

Sorry for my bad english. Have a nice day !

![folding_impossible](https://user-images.githubusercontent.com/9590102/38554578-6a82b8b6-3cc3-11e8-9866-620d059cdd52.PNG)

- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a switch case
2. Try to fold a case

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/23380 to track this upstream

Set `"typescript.experimental.syntaxFolding": false` to go back to the old indentation based folding
