### ISSUE TITLE
golang debug

### ISSUE THREAD

**Issue by XieXiaomei-ptr** [Microsoft/vscode#47571]
- VSCode Version:1.22.1
- OS Version:OSX 10.13.3 (17D102)

Steps to Reproduce:

1.All of go extensions are installed.
2.F5 to start debugging, then

2018/04/10 17:26:07 server.go:73: Using API v1
2018/04/10 17:26:07 debugger.go:98: launching process with args: [/Users/xiexiaomei/go/src/test/debug]
could not launch process: EOF
Process exiting with code: 1

**Comment by weinand** [comment]
Please file this issue against the go debugger.
