### ISSUE TITLE
Task Runner: Define array of tasks

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#4757]
- VSCode Version: 0.10.11
- OS Version: Mac OS X El Capitan

The documentation for Task Runners doesn't indicate how to define more than one task in the `tasks.json` file. How do I define more than one? The default `tasks.json` file that gets auto-generated only has one task definition. I tried creating a JSON array, but received error messages about the file format.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/vscode-docs#250
