### ISSUE TITLE
Cannot text search in workspace settings files

### ISSUE THREAD

**Issue by breathe** [Microsoft/vscode#47577]
Issue Type: <b>Bug</b>

1. Open a workspace file or vscode settings file (.vscode/settings)
2. cmd-f to do a text search
3. Search filters the default settings view but cannot be used to search the actual settings file

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.34GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron ./ai_services.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.0.20
quokka-vscode|Wal|1.0.117
wallaby-vscode|Wal|1.0.81
project-manager|ale|0.25.0
snapshot-tools|asv|0.0.7
npm-intellisense|chr|1.3.0
regex|chr|0.1.0
vscode-eslint|dba|1.4.8
jupyter|don|1.1.4
gitlens|eam|8.2.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
path-autocomplete|ion|1.9.0
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|0.0.16
vscode-regexp-preivew|le0|0.0.3
python|ms-|2018.3.1
cpptools|ms-|0.16.1
debugger-for-chrome|msj|4.3.0
advanced-new-file|pat|1.1.0
vscode-versionlens|pfl|0.20.0
gitlink|qez|0.4.2
vscode-import-cost|wix|2.6.2

</details>

**Comment by roblourens** [comment]
You can still access it through the command palette, or remove the keybinding if you prefer:

```json
{
        "key": "cmd+f",
        "command": "-settings.action.search",
        "when": "inSettingsEditor"
}
```
