### ISSUE TITLE
Cannot search in opened folder

### ISSUE THREAD

**Issue by TsuchiyaMasahiro** [Microsoft/vscode#47570]
Issue Type: <b>Bug</b>

1. Open an folder 
2. Ctrl+Shift+F
3. Serach any word

but I can't serach the word in the opend folder.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.93GB (1.82GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\tsuch\OneDrive\MYドキュメント\aws\photobook2\laravel\resources\views\mypage\print\printorder.blade.php|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by usernamehw** [comment]
This doesn't look like the latest vscode version.

**Comment by TsuchiyaMasahiro** [comment]
In VS Code version:1.22.1, it was fixed.  Thank you !
