### ISSUE TITLE
show error when add function use prototype

### ISSUE THREAD

**Issue by builden** [Microsoft/vscode#47574]
use prototype to dynamic add function, typescript default check invalidate 

- VSCode Version: 1.22.1
- OS Version: Win7 x64

![image](https://user-images.githubusercontent.com/9499016/38550276-9acc901c-3ce8-11e8-88a3-950362b327b4.png)

**Comment by mjbvz** [comment]
Yes, this is by design. The type system doesn't allows the prototype to be augmented dynamically like this

**Comment by builden** [comment]
but i want add fun to class dynamically, how can i do?
