### ISSUE TITLE
Hanging and not responding to mouse clicks, but showing the output if I switch to other app and come back.

### ISSUE THREAD

**Issue by mallikarjunece** [Microsoft/vscode#47572]
Issue Type: <b>Bug</b>
Frustating issue:

Not responding, if I use ALT+TAB then it is showing the output.

Kindly let me know, how to overcome this.....

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by bpasero** [comment]
@mallikarjunece you are jumping to another app and then back to VS Code and it freezes? Which app?
