### ISSUE TITLE
Add drop down list for "files to include" in search window

### ISSUE THREAD

**Issue by KUGA2** [Microsoft/vscode#47583]
This is a feature request:

Please add a drop down list with the latests inputs (maybe 10?) in the search window. The inputs should be saved over restart or update.
This is especially important in the _files to include_ testfield. With the drop down list, you can faster switch between file types like Makefiles (`Makefile,*.mak`) and Source files (`*.c,*.cpp,*.h`). The sting might be longer and also errors may occur from retyping all the time.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/23099

**Comment by KUGA2** [comment]
Thanks for the information. Nevertheless, this feature should be enhanced.
The list(s) should be visible and sorted by last use.
