### ISSUE TITLE
Highlight breaks with #error or #warning directive in C using apostrophe

### ISSUE THREAD

**Issue by beckerzito** [Microsoft/vscode#47582]
- VSCode Version: 1.21.1
- OS Version: Windows 7 Professional 64-bits

Steps to Reproduce:
1. Write a code in C using the directive #error or #warning
2. Use an apostrophe with these directives
3. See highlight

How it looks like:
![image](https://user-images.githubusercontent.com/26304432/38556564-7cf1b63c-3ca0-11e8-8b7f-ae5e9265ff95.png)

How it should look like:
![image](https://user-images.githubusercontent.com/26304432/38556582-918d437c-3ca0-11e8-8b78-f9e9836bfd17.png)

Does this issue occur when all extensions are disabled? Yes

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#270
