### ISSUE TITLE
Improve presentation of function signature hints

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#47593]
Version 1.22.0-insider (1.22.0-insider)
6c22e21cdcd6811770ddcc0d8ac3174aaad03678

Don't think such hint is useful to anyone.

![ts](https://user-images.githubusercontent.com/4033249/38567630-96808df8-3c9b-11e8-8890-a0d45b199f40.gif)

**Comment by mjbvz** [comment]
@octref Please share the complete example, specifically the `./properties` file so we can investigate this. Looks like a bunch of either types?

**Comment by octref** [comment]
It's this file: https://github.com/mdn/data/blob/master/css/properties.json

**Comment by mjbvz** [comment]
Test code:

```ts
function foo(f: typeof import('./properties.json')) { }
```

We've improved sighelp:

![screen shot 2018-12-14 at 5 56 51 pm](https://user-images.githubusercontent.com/12821956/50037784-baa9ce00-ffc9-11e8-9d50-f5ae598b9b72.png)

And quickinfo/intellisense:

![screen shot 2018-12-14 at 5 57 16 pm](https://user-images.githubusercontent.com/12821956/50037798-d9a86000-ffc9-11e8-9015-2a008b722b4c.png)


Both cases now use `...` if the type becomes too big
