### ISSUE TITLE
Hangs on Terminal tab if repeat http-server

### ISSUE THREAD

**Issue by avatarsystems** [Microsoft/vscode#47599]
Issue Type: <b>Bug</b>

1) Click on "Terminal" tab
2) type      http-server
3) wait a second for this to resolve
4) type again        http-server

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|23.96GB (14.68GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
csharp|ms-|1.14.0
team|ms-|1.133.0
debugger-for-chrome|msj|4.3.0

</details>

**Comment by Tyriar** [comment]
What shell are you using? Are you hitting tab after `http-server`?
