### ISSUE TITLE
Build errors are not highlighted in editor when performing build operation with CTRL+SHIFT+B

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4759]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:

1. Launch app and open any folder which contains .ts file.
2. Setup the task.json and tsconfig.json.
3. Now perform the build operation with CTRL+SHIFT+B
4. Verify output and editor window.

Actual: Getting errors in the output window but there is no red flag in the editor.

![image](https://cloud.githubusercontent.com/assets/17735796/14115991/7a6dc8ee-f592-11e5-836a-d856466caff1.png)

**Comment by egamma** [comment]
Do you have a problem matcher defined for the task? 
Can you pls add you tsconfig.json and task.json.

**Comment by dbaeumer** [comment]
@v-pavanp from the screen shot it looks like the tsconfig.json file sits inside the .vscode folder. It must sit in the root in this example.

**Comment by dbaeumer** [comment]
@v-pavanp please ping if moving the tsconfig.json to the workspace folder doesn't solve the problem. Then please attach the workspace folder.

**Comment by v-pavanp** [comment]
I tried by moving tsconfig.json to the workspace folder but still getting the same result. Also I observer that the default tasks.json setting is not able to identify tsconfig.json file and I need to pass files name with args[] explicitly like below:

{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"args": ["test.ts","helloworld.ts"],
	"showOutput": "silent",
	"problemMatcher": "$tsc"
}
**
The Default setting looks like this.**
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"args": ["-p", "."],
	"showOutput": "silent",
	"problemMatcher": "$tsc"
}

![image](https://cloud.githubusercontent.com/assets/17735796/14270096/7b54694a-fa9f-11e5-88dc-c247ba361efb.png)

**
My Tasks.json file look like below:**
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true
    },
    "files": [
        "helloworld.ts",
        "test.ts"
    ]
    
}

**Comment by dbaeumer** [comment]
You have configured the tsc compiler to output absolute paths (I think by listing the files in the files sections). If you do this then you have to tell the problem matchers to match absolute pathes as well. You can do so by changing the tasks.json as follows:
```json
	"problemMatcher": {
		"base": "$tsc",
		"fileLocation": "absolute"
	}
```

![capture](https://cloud.githubusercontent.com/assets/1931590/14345013/12004546-fcab-11e5-8404-23f20c029ef0.png)
