### ISSUE TITLE
Can't debug Issue Reporter

### ISSUE THREAD

**Issue by oriash93** [Microsoft/vscode#47598]
Hey,

I am trying to debug the Issue Reporter but none of the break points I set in `issueReporterMain.ts` stop.
Is it running somewhere else? Am I doing something wrong?

Thanks for your help!

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.3.0
vscode-icons|rob|7.22.0

</details>

**Comment by oriash93** [comment]
@RMacfarlane, I guess I was wrong. I followed your steps and now I can debug the Issue Reporter. Thanks!

Is there any documentation or guidance for cases like this? I would've never known it's a separate process.

**Comment by RMacfarlane** [comment]
@oriash93 Glad that worked!

There's a small section in https://github.com/Microsoft/vscode/wiki/How-to-Contribute on debugging but it only describes how to debug the main renderer process and the extension host process. It would be good to have more information about the other processes there
