### ISSUE TITLE
it still does not work

### ISSUE THREAD

**Issue by DeveloperJF** [Microsoft/vscode#47590]
Good morning, Excuse me was in other personal things and that's why I had not answered. I told them that I uninstalled the program again and it remains the same; but I downloaded the VS Code insider and that did work for me.
Why does that happen? Can you comment?
What's different about VS Code Insiders / VS Code ??

![falla_codigo5](https://user-images.githubusercontent.com/37987294/38565154-37749574-3ca6-11e8-9b90-21f85578340b.jpg)
![vscodeinsiders](https://user-images.githubusercontent.com/37987294/38565156-379cb644-3ca6-11e8-8233-deb847e9a83c.jpg)
![vscodeinsiders1](https://user-images.githubusercontent.com/37987294/38565157-37d4d1b4-3ca6-11e8-99dd-e4c297ddaa59.jpg)

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
