### ISSUE TITLE
Explorer context menu shows up again on rename/delete

### ISSUE THREAD

**Issue by kolbma** [Microsoft/vscode#47604]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

1. Left click in an editor or empty replacement
1. Right click in Explorer on file or directory
1. Context menu shows up
1. Select Rename
1. Context menu shows up again
1. Select Rename
1. Context menu goes away and file/directory can be renamed

Does this issue occur when all extensions are disabled?: Yes

The error is only that context menu comes back to view a 2nd time.  
The rename/delete thing is called, because if you do press escape on 2nd menu show, the menu goes away and you can rename the file.

It has also something to do with focus. If you select the file 2 times (no double click) with left button and then call context menu with right button, it works, too.

**Comment by isidorn** [comment]
@kolbma I can not reproduce this.
Can you please try it with latest vscode insiders https://code.visualstudio.com/insiders/
If you can still repro with insiders can you please attach a video of the actual problem. Thanks

**Comment by kolbma** [comment]
https://youtu.be/fxHgF0t2Jjk

**Comment by isidorn** [comment]
@kolbma thanks for the great video. However I still can not repro both on my os x and win.
@bpasero do you have any idea if this might be some electron issue?

**Comment by kolbma** [comment]
The original problem seems to be gone with

Version 1.23.0-insider
Commit dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b
Date 2018-04-16T05:17:45.591Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

**But** now the context menu closes immediately after right button click sometimes. So it only pops up for under a second. Same as before, not always but reoccurring.

**Comment by bpasero** [comment]
Btw I can neither reproduce the original issue nor the newly reported one so you must either have some setting enabled in Windows or a special mouse that triggers this.

**Comment by kolbma** [comment]
Mmh. Don't know about special settings which create problems like this.
My mouse is a standard USB cable mouse with Windows driver.
I don't have any problems in other applications.

**Comment by kolbma** [comment]
But i will try different mouse.

**Comment by kolbma** [comment]
Somehow it is working now. Got a driver update by windows update.
