### ISSUE TITLE
Files toggles visibility

### ISSUE THREAD

**Issue by dean992008** [Microsoft/vscode#47608]
Bug in file list: when I open/close dir file in parent dir files toggles visibility.
http://joxi.ru/BA0vgOguJOOdMm
http://joxi.ru/Grqg3K3cQLLV12

- VSCode Version: 1.22.1
- OS Version: Windows 10 1709 build 16299.334

Steps to Reproduce:

1. Open Wordpress Theme dir as project
2. Open/Close some dir. 
3. function.php and index.php toggle visibility. 

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
I can not reproduce this issue.
Can you reproduce this with the latest vscode insiders https://code.visualstudio.com/insiders/
If you can, can you share a repository on github for which you always see this issue?

**Comment by dean992008** [comment]
Look like a bug was fix in the last release. Thank you.
