### ISSUE TITLE
ctrl-shift-h followed by ctrl-shift-f doesn't revert back to find-all

### ISSUE THREAD

**Issue by manbearian** [Microsoft/vscode#47600]
Issue Type: <b>Bug</b>

`ctrl-shift-h` followed by `ctrl-shift-f` doesn't revert replace-all window back to find-all window

1. `ctrl-shift-f ` -> open find-all pane
2. `ctrl-shift-h` -> changes find-all into replace-all
3. `ctrl-shift-f` -> does nothing

i would expect (3) to change replace-all UI to find-all UI (i.e. hide the "Replace" field)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|Memory (System)|31.94GB (18.80GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.16.1

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
This was fixed recently, is fixed in Insiders or the 1.23 release
