### ISSUE TITLE
Screen Freeze Issue

### ISSUE THREAD

**Issue by eiarhabi** [Microsoft/vscode#47605]
- VSCode Version: 1.23.0 Insiders
- OS Version: Windows 10 17133.1

Steps to Reproduce:

1. Open VS Code Insiders
2. Do regular jobs

Does this issue occur when all extensions are disabled?: Yes

This issue occurs when VS Code is running and would freeze the display of any items except the mouse cursor. Sleep and re-wakeup computer could solve this issue. Occurs in both Insiders and stable version.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
