### ISSUE TITLE
Task Runner: Alternate version number not accepted in tasks.json

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#4760]
- VSCode Version: 0.10.11
- OS Version: Mac OS X El Capitan

Steps to Reproduce:

1. Define a task in `tasks.json`
2. Change the version number to something other than `0.1.0`

<img width="539" alt="screen shot 2016-03-29 at 10 58 44 am" src="https://cloud.githubusercontent.com/assets/466713/14116556/915400e0-f59d-11e5-872b-689c25fbae06.png">

<img width="565" alt="screen shot 2016-03-29 at 11 01 40 am" src="https://cloud.githubusercontent.com/assets/466713/14116574/a88dd24a-f59d-11e5-820c-3f56bdfa2188.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by dbaeumer** [comment]
This is expected since the task runner currently only support 0.1.0 format of that file. There is no 0.2.0
