### ISSUE TITLE
Track user focus across editor and integrated terminal

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#47615]
Issue Type: <b>Feature Request</b>

Right now only active text editor can be tracked with `window.activeTextEditor`. Though users can focus other UI elements, like integrated terminals, there is no way to tell when user switches focus from the text editor to the integrated terminal, or from one terminal to another.

Because of that user tracking in our extension cannot tell when user has changed focus to an integrated terminal, or switched active terminals.

We'll need something like `window.activeTextEditor`, but more generic, e.g.
`activeWindow: TextEditor | Terminal | .... | undefined`

**Comment by Tyriar** [comment]
@IlyaBiryukov why do you need to know what's focused?

**Comment by IlyaBiryukov** [comment]
@Tyriar one of features of our extension is following user through the IDE. We already can do this for editor, but not other windows.

**Comment by Tyriar** [comment]
> one of features of our extension is following user through the IDE

@IlyaBiryukov what does this mean exactly? What happens as a result of the user clicking in the terminal panel or the explorer?

**Comment by IlyaBiryukov** [comment]
@Tyriar If this "follow" mode is turned on, and the user clicks on a (shared) terminal, we want other users to get the corresponding shared terminal focused. Clicking on the explorer (the folder view) won't make the following users to activate their explorers though. We're interested in following the user to places where others can contribute or see what the user is changing.

**Comment by jrieken** [comment]
> We'll need something like window.activeTextEditor, but more generic, e.g.
activeWindow: TextEditor | Terminal | .... | undefined

We have kind of decided against this, esp when it comes to webview or tree views which are entirely private to extensions. Also there are UI pieces, like the release notes editor, which take focus but for which we don't have plans to expose in the API.

**Comment by IlyaBiryukov** [comment]
Ok, how about just the active terminal window?

**Comment by jrieken** [comment]
@Tyriar Is something like `activeTerminal` in reach?

**Comment by IlyaBiryukov** [comment]
@Tyriar when do you think you can do this?

**Comment by Tyriar** [comment]
@IlyaBiryukov you also need a `onDidChangeActiveTerminal: Event<Terminal>` as well don't you?

**Comment by IlyaBiryukov** [comment]
Yep

**Comment by Tyriar** [comment]
I'll include this with the big PR for #46192
