### ISSUE TITLE
intellisense for relative CommonJS modules

### ISSUE THREAD

**Issue by ferrao** [Microsoft/vscode#47619]
- VSCode Version: 1.22.1
- OS Version: OSX El Capitan 10.11.6 

Steps to Reproduce:

Project with following structure:

```
jsconfig.json
lib
| - modules
     | - module1
     | - module2
```

Intellisense does not work for `require('module1');`

I have read the VSCode documentation on Javascript language features, have gone through all the multiple issues that keep getting closed regarding this, have tried all `baseUrl`, `paths`, `mapRoot` and `rootDir` options and suggestions on such issues, all without success.

VSCode is a fantastic code editor and I have never looked back since I switched from Atom, but now that I got used to it, I have to choose between not having Intellisense (just like Atom...) or have absolute `../../../../../module` paths in my require statements which are hard to read and error prone.

I very kindly ask and hope for this issue not to be closed like all the others regarding the same problem without an explanation/fix on how to use anything other than `node_modules` for relative paths.

**Comment by mjbvz** [comment]
Try using `"module": "system"` in your `jsconfig.json`:

```json
{
    "compilerOptions": {
        "module": "system"
    }
}
```

**Comment by ferrao** [comment]
Amazing, after so much trouble, having that simple `jsconfig.json` file actually makes it work!!!!! @mjbvz, can you explain why?

**Comment by mjbvz** [comment]
[Here's more info](https://www.typescriptlang.org/docs/handbook/module-resolution.html), and specifically the `Module Resolution Strategies` part. Using `system` enables the classic resolution strategy that supports resolving module names such as `'moduleB'`

**Comment by ferrao** [comment]
Got it! This bit is the relevant one:

> For non-relative module imports, however, the compiler walks up the directory tree starting with the directory containing the importing file, trying to locate a matching definition file

It just feels a bit strange configuring `system` for triggering the classic strategy, which according to the docs is present for backwards compatibility only, when in reality, I am actually using `NodeJS` with a `NODE_PATH` environment variable set.

It is working for me now, so no more complains here, I am one happy customer now, but I guess this is one of the reasons why so many issues and confusion exist regarding this problem.
