### ISSUE TITLE
TypeScript React component props IntelliSense lists irrelevant things

### ISSUE THREAD

**Issue by tugberkugurlu** [Microsoft/vscode#47612]
- VSCode Version: Version 1.21.1 (1.21.1) 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
- OS Version:

![image](https://user-images.githubusercontent.com/328122/38580679-8313122e-3d02-11e8-810a-b689cbe9434c.png)

Steps to Reproduce:

1. Open up a react-typescript application, for example created by https://github.com/wmonk/create-react-app-typescript
2. Create a component
3. Try to use that component and type `s` when you want to start adding props.

You will see bunch of junk suggested through IntelliSense which is really annoying. 

![image](https://user-images.githubusercontent.com/328122/38580871-08d79f06-3d03-11e8-9b83-c18b8887fef5.png)

I believe this started out with a recent update. I don't recall seeing this previously.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ramya-rao-a** [comment]
@tugberkugurlu Those suggestions are coming from emmet. Either you are working on a file with extension jsx or you have changed the file mode to "JavascriptReact"

Emmet suggestions show up to aid with the html component of jsx files.

If you dont want the emmet features in jsx files, add the below to your settings:
```
"emmet.showExpandedAbbreviation": "inMarkupAndStylesheetFilesOnly"
```

Read [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet) if you want to learn more about emmet.

The particular case you have shared is a bug though. When typing an attribute of an html tag, emmet suggestions shouldnt show up. But this isnt a regression, I see the same behavior in previous versions 1.20 and 1.21

I'll push a fix for this case and the fix will be available in tomorrow's [Insiders](https://code.visualstudio.com/insiders)
