### ISSUE TITLE
Can't select warning messages to copy to clipboard

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#4761]
- VSCode Version: 0.10.11
- OS Version: Mac OS X El Capitan

Steps to Reproduce:

1. Create a file that has an error or warning in it (eg. an improperly formatted JSON file)
2. Make sure the appropriate language mode for the file is selected
3. Use `F8` keyboard shortcut to navigate between warnings and errors
4. Try to select, and copy-paste text from a warning or error message.
5. Notice that the text selection cursor appears, when hovering over the message, but you cannot actually select the text. This prevents the standard "copy" command from being invoked (`CMD + C`)

<img width="455" alt="screen shot 2016-03-29 at 11 04 15 am" src="https://cloud.githubusercontent.com/assets/466713/14116639/fedc3592-f59d-11e5-8cfb-3ebd4cf92403.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by alexandrudima** [comment]
@jrieken fyi - you were in that code recently

**Comment by jrieken** [comment]
@alexandrudima You mean `Cmd+C` or the widget itself? I recently made changes in both. Tho, trying this, I cannot even get the text selected... Is this the default zone behaviour?

**Comment by jrieken** [comment]
We saw this - the editor put the view zone behind the lines and thus user events never reach it. Unsure if  changing the dom order will break other things?

**Comment by alexandrudima** [comment]
@jrieken I thought that was a zoneWidget = viewZone + overlayWidget (where the overlayWidget is clickable, selectable, etc.)

**Comment by jrieken** [comment]
true story...
