### ISSUE TITLE
Support TypeScript 2.9 disableSuggestions preference

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#47617]
From https://github.com/Microsoft/TypeScript/pull/23283

Support the `disableSuggestions` preference for typescript. You can already hide these errors with  `"javascript.suggestionActions.enabled": false` and `"typescript.suggestionActions.enabled": false`. This feature would just hook these settings up to typescript so that we don't compute the suggestions if they are not enabled

**Comment by mjbvz** [comment]
For verification, create a file with an unused variable and try triggering quick fixes for it. None should be returned when `javascript.suggestionActions.enabled` is false

**Comment by roblourens** [comment]
I still see this, is it wrong?

![image](https://user-images.githubusercontent.com/323878/40737771-92af967e-63f6-11e8-9b72-2f0f0015b079.png)

**Comment by mjbvz** [comment]
That's a quick fix instead of a suggestion because there's a warning. Try this in a project that does not have `noUnusedLocals` set
