### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by pedritin91** [Microsoft/vscode#47611]
I'm trying to install the .vsix since the recommended one on vscode extensions panel isn't working either. Neither of the two ways is working for me.

VSCode 1.22.1

**Comment by octref** [comment]
Duplicate of #42229.

**Comment by joaomoreno** [comment]
@pedritin91 Can you open the .vsix file using a ZIP program? Can you upload the exact .vsix file somewhere and send it to me?

**Comment by octref** [comment]
@joaomoreno This one: https://github.com/vuejs/vetur/releases

**Comment by joaomoreno** [comment]
I downloaded `vetur-0.11.8.vsix`. It seems like a working ZIP file. I can also install it with the `Install from VSIX...` action.

```
$ shasum vetur-0.11.8.vsix
1d08cf963496cc524f3b19109230d11f63c774e5  vetur-0.11.8.vsix
```

Do you get the same hash?

@octref Can you reproduce the issue?

**Comment by octref** [comment]
Same hash and I cannot repro.

**Comment by joaomoreno** [comment]
@pedritin91 Can you check the hash of your vsix file?
