### ISSUE TITLE
Language syntax highlighting does not work as expected

### ISSUE THREAD

**Issue by ustc-zzzz** [Microsoft/vscode#47614]
Issue Type: <b>Bug</b>

The problem was found when I tried to create an extension to add syntax highlighting support for a new language.

* Use `yo code` to generate an extension template by selecting `New Language Support`
* I'm now developing a syntax highlighter for hocon so I set almost everything to `"hocon"`
* Write the following code into `language-configuration.json`:
```json
{
    "comments": {
        "lineComment": "#"
    },
    "brackets": [
        ["{", "}"],
        ["[", "]"]
    ]
}
```
* Then write the following code to `hocon.tmLanguage.json` (I have tried my best to reduce the size of the code):
```json
{
  "fileTypes": ["conf"],
  "name": "HOCON",
  "patterns": [{
    "include": "#list"
  }],
  "repository": {
    "list": {
      "begin": "\\[",
      "end": "\\]",
      "patterns": [{
        "include": "#string"
      }]
    },
    "string": {
      "begin": "\"",
      "end": "\"",
      "name": "string.quoted.double.hocon"
    }
  },
  "scopeName": "source.hocon"
}
```
* Create a new file and set the language mode to HOCON

Then I wrote `["a" "b"]` in the file and an error was thrown:
![image](https://user-images.githubusercontent.com/8004211/38583291-1dd0cba2-3d45-11e8-93b7-c07735b304ba.png)
However, if I add any special character between the two strings, such as `["a", "b"]`, `["a"! "b"]`, etc. the error will not exist.

I'm not sure if there are something wrong with the steps I made for the extension. Do I need to set up the separator (from comma or something to an empty string) somewhere?

I've packed the extension to an archive so that everybody can reproduce this bug by downloading and installing it: <https://1drv.ms/u/s!An4chGuCAHPTnmwc4cP3wHhTo6rz>

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.13.0-1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|Load (avg)|2, 1, 1|
|Memory (System)|11.61GB (1.02GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by aeschli** [comment]
There must be an other extension that creates these error markers.
What you defined is only used for editing (language-configuration.json) and for syntax highlighting (hocon.tmLanguage.json)

**Comment by ustc-zzzz** [comment]
I disabled and re-enabled all the extensions, and the error no longer appears.
Sorry for disturbing you.
