### ISSUE TITLE
enableProposedApi is not respected

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [Microsoft/vscode#47628]
Setting `"enableProposedApi": true` in `package.json` has no effect (outside of debug), but using `--enable-proposed-api` works.

- VSCode Version: ~1.22.1~ 1.23.0 insiders
- OS Version: Windows 10

Steps to Reproduce:
1. Create brand-new typescript extension.
2. Add `"enableProposedApi": true` to `package.json` as described [here](https://code.visualstudio.com/updates/v1_21#_proposed-extension-apis)
3. Use new webview api in `extension.ts`:
```ts
let webview = vscode.window.createWebview('my-id', 'Hello', vscode.ViewColumn.Two, { });
webview.html = "Hello";
```
4. ~Hit `F5` to open up extension host.~ In insiders build `"enableProposedApi": true` in `package.json` truly allows proposed api usage for the debug session.
5. Compile and copy the extension to `%USERPROFILE%\.vscode-insiders\extensions`
6.  Call command `HelloWorld`, you'll see error in the console:
> Extension 'my.extension.id cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)

Running vscode with `--enable-proposed-api=my.extension.id` allows to run the extension.

- Expected:
`"enableProposedApi": true` in `package.json` should allow running the extension.

I also uploaded the sample project:
https://github.com/OrkhanAlikhanov/vscode-enable-proposed-api-bug

**Comment by OrkhanAlikhanov** [comment]
Updated the issue for 1.23.0 insiders build.

**Comment by mjbvz** [comment]
@jrieken Should `enabledProposedApi` also be respected if you are debugging an extension using vscode?

**Comment by OrkhanAlikhanov** [comment]
@mjbvz Actually, it's respected when I hit `F5` to start debugging, but when I install the extension `enabledProposedApi` has no effect. I have to enable it with `--enable-proposed-api=extension.id`

**Comment by mjbvz** [comment]
This is correct behavior then. We intentionally do not let installed extensions use proposed apis because vscode updates will break them

**Comment by OrkhanAlikhanov** [comment]
I see now. Why then we have `enabledProposedApi` at all? It doesn't make sense to me. I guess proposed api access, by default, needs to be granted to the development extension when I hit `F5`. What do yo think @mjbvz?

**Comment by mjbvz** [comment]
So that extensions have to be very intentional about consuming proposed apis and to prevent devs from publishing extensions that use them

**Comment by OrkhanAlikhanov** [comment]
Well, we can't explicitly use them without adding `vscode.proposed.d.ts` to the project, at least for typescript extension. Also note that a warning about use of proposed api is logged, which devs will see.
