### ISSUE TITLE
Opening Code in .vscode directory doesn't load the folder  [1.22]

### ISSUE THREAD

**Issue by sulkhanp** [Microsoft/vscode#47622]
Before 1.22 editing any file in a .vscode directory would automatically open folder in that directory for you (https://i.imgur.com/jcWZDia.png). However, with 1.22, it is no longer the case:
https://i.imgur.com/VYaSWDU.png

**Comment by sulkhanp** [comment]
After further investigation I see that:
code . --verbose 
manages to successfully load the folder while in the same folder:
code lab07.cpp --verbose
will not load the folder

**Comment by sulkhanp** [comment]
@Tyriar Why doesn't auto-assign bot work?

**Comment by Tyriar** [comment]
> Why doesn't auto-assign bot work?

Because your description wasn't specific enough to automatically categorize the issue into a label. Normally the inbox tracker will pick up the issue, ideally don't ping people as we get enough notifications already for relevant topics.

I think this was done by design, @bpasero will know.

**Comment by sulkhanp** [comment]
If this was a design change, I really hope there's a way to re-enable the previous design.

**Comment by bpasero** [comment]
Yes by design, we no longer open folders automatically when there is a `.vscode` folder because it often caused us to open a huge directory that the user actually did not want to open.

If you want to open a folder, point VS Code to that folder.

/cc @chrmarti

**Comment by chrmarti** [comment]
No, not at the moment. See #45121 for the changes that removed it.
