### ISSUE TITLE
Highlight current lines with multiple cursors

### ISSUE THREAD

**Issue by mostafaabobakr7** [microsoft/vscode#47625]
![vscodemultilinecolor](https://user-images.githubusercontent.com/27288406/38592951-419884b8-3d3f-11e8-9231-3dafe5ecdb1f.jpg)

- VSCode Version: 1.22.1
- OS Version: windows10 x64

# Make all line's numbers colored

**Comment by alexandrudima** [comment]
We now render multiple line highlights, but only in the case where they are rendered with a background color (not with a border), i.e.

![image](https://user-images.githubusercontent.com/5047891/67501852-44fc9d00-f685-11e9-9e53-b7cc82bf54cb.png)

vs

![image](https://user-images.githubusercontent.com/5047891/67501889-534ab900-f685-11e9-9b73-44350c6d5183.png)

**Comment by mostafaabobakr7** [comment]
How to enable it ?

![image](https://user-images.githubusercontent.com/27288406/67502644-83468c00-f686-11e9-912b-d245aa71a0c4.png)

**Comment by alexandrudima** [comment]
@mostafaabobakr7 You can build VS Code from source or wait for tomorrow's Insiders build
