### ISSUE TITLE
Using console.time() and console.timeEnd() still results in 2 messages printed

### ISSUE THREAD

**Issue by wyckster** [Microsoft/vscode#47624]
- VSCode Version: 1.21.1
79b44aa704ce542d8ca4a3cc44cfca566e7720f1
x64
- OS Version: Windows 10 64-bit

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Create the following app.js file
```
console.time('a');
console.endTime('a');
```
2. Create a debug configuration that launches node with app.js.  Excerpt:
```
    {
      "type": "node",
      "request": "launch",
      "name": "App",
      "program": "${workspaceFolder}\\app.js"
    },
```
3. Start Debugging (F5)

### Actual output
It shows two messages.
```
a: 0.206300999969244ms
a: 0.480ms
```

### Expected output
Just one message.  Maybe something like:
```
a: 0.480ms
```

### More info
This does **not** reproduce when launching node from the command line.  e.g.:
```
node app.js
```
...just shows the expected output.
```
a: 0.480ms
```
So it only occurs when running in the debugger.

The two times are different and it's not clear which one is the real time.  (Although one is formatted to 3 digits after the decimal places, so I'm guessing that's the real one.)

### Related issue

I see #38376. Conversation in that issue makes the claim that this only happens when debugging an extension.  However, in my case, **no extension** is installed or enabled or being debugged.  So I feel the issue is worth re-opening.  Furthermore, that issue is locked and I cannot comment on it.

**Comment by weinand** [comment]
duplicate of #38376

**Comment by wyckster** [comment]
This is not a duplicate of #38376.  Did you read my comment why?  I believe it is not a duplicate because you claim that #38376 only occurs because you are debugging an extension.  This is reproducible when you are not debugging an extension.

Can you please clarify rather than just close it?
