### ISSUE TITLE
Typescript: Code action implement inherited abstract class will override the class body 

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode#47623]
- VSCode Version:  1.22
- OS Version: Windows 10 

Steps to Reproduce:

1.  Typescript code: 
```typescript
abstract class Base {
    abstract getProperty() : void;
}


class Subclass extends Base {
    // This is comment
}
```
2. Select the SubClass and trigger the code action, invoke it 

Expected:  The new code should insert after the comment or other existing code

Actually: The existing code is overwrote. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23333
