### ISSUE TITLE
Dynamic tasks with variables support in label

### ISSUE THREAD

**Issue by IevgenSobko** [Microsoft/vscode#47639]
I have created the custom task to run our custom test runner as rake job with the active file as parameter task to run  
```
   {
      "label": "Jet Run on Stage",
      "type": "shell",
      "command": "rake",
      "args": [
        "jet:run",
        {
          "value": "test=$(echo ${file} | sed 's#.*/jet/tests/##')",
          "quoting": "weak"
        },
        {
          "value": "params={:timeout => 120, :log_output => [:console, :html]}",
          "quoting": "weak"
        }
      ],
      "group": "test",
      "presentation": {
        "reveal": "always",
        "panel": "new"
      },
  }
```
We have some pretty long running tests(1 hour for instance).
When I run some tests with such long duration it is not possible to run the same task on a different file. Is there a way to run the same task with the different file while the same task is running with another file?
What I actually thought it would be great to add variables support to task label so in that case tasks depending on different files will have unique names and won't create uniqueness collision and will allow running the same task on different files.

**Comment by dbaeumer** [comment]
This is currently not possible with the tasks.json file but I do have a feature request to support this. 

What you can do is the following: you can write an extension that has a task provider which provides a different task for each open file which you then can run. An example for a task provider is here: https://github.com/Microsoft/vscode-extension-samples/blob/master/task-provider-sample/src/extension.ts#L1

I mark it as a dup of https://github.com/Microsoft/vscode/issues/40027. If you need help with the extension please ping.
