### ISSUE TITLE
Wrongly commented out if I quickly input slash, paste, slash

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#47637]
Issue Type: <b>Bug</b>

1. Do below *quickly*:
    1. Type <kbd>/</kbd> key.
    2. Type <kbd>Ctrl</kbd>+<kbd>C</kbd> to paste a certain string (e.g. a RegExp pattern).
    3. Type <kbd>/</kbd> key.

![comentted-out](https://user-images.githubusercontent.com/1937871/38600851-9da2b2a4-3da0-11e8-95bd-8469000ff272.gif)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|15.93GB (7.31GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by roblourens** [comment]
You are probably triggering ctrl+/ which is a shortcut to comment out the current line. You can disable that keybinding if you don't want it.
