### ISSUE TITLE
Silent terminal doesn't pop up if problem occurs. 

### ISSUE THREAD

**Issue by elpixo** [Microsoft/vscode#47636]
I have a build task that has "presentation.panel" = "new"

When I build, it creates a new terminal for the task's output; but it does not activate it (so you have to manually select it in the drop-down list)

Also, the terminal that it does create seems to be very narrow (wrapping all the text)

This is a regression from version 1.21

**Comment by dbaeumer** [comment]
@elpixo this works for me using 1.22.

Which OS are you on ?

**Comment by elpixo** [comment]
Linux.

**Comment by elpixo** [comment]
More info; it seems that switching "reveal" to "always" makes the panel pop up.

So perhaps the error lies with the problem matcher.

Here's the first part of my tasks.json - the script calls clang++ to compile.

```
 "tasks": [
      {
         "label": "Build",
         "type": "shell",
         "group": {
            "kind": "build",
            "isDefault": true
         },
         "command": "${workspaceRoot}/build.sh",
         "presentation": {
            "reveal": "silent",
            "panel": "new"
         },
         "problemMatcher": {
            "owner": "Build",
            "fileLocation": [
               "absolute"
            ],
            "pattern": {
               "regexp": "^([^:]+):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
               "file": 1,
               "line": 2,
               "column": 3,
               "severity": 4,
               "message": 5
            }
         }
      },
```

Just to be clear; I'm expecting it to pop up when there is a problem (I can confirm that even when there is a problem shown in the "problems" view - the terminal does not pop up)

**Comment by dbaeumer** [comment]
@elpixo now I see. And I agree that 'silent' should make it pop up when an error occurs.

**Comment by alexr00** [comment]
I can't find the duplicate, but `silent` now does this.
