### ISSUE TITLE
WebviewOptions.localRootResource does not default to something

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [Microsoft/vscode#47631]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:
1. Create webView with empty options.
2. Try to access a file in extension install directory inside webview.

Although it says for [`localRootResource` in the `WebviewOptions`](https://github.com/Microsoft/vscode/blob/1.22.1/src/vs/vscode.proposed.d.ts#L551-L558):
> Defaults to the root folders of the current workspace plus the extension's install directory.

This wrong information took my nearly 4 hours :/
I thing it would be better to log something about access denial. Debugging the webview needs to be improved.

Sample code or [check out the repo](https://github.com/OrkhanAlikhanov/vscode-webview-localRootResource-bug):
```ts
let webview = vscode.window.createWebview('my-id2', 'Hello', vscode.ViewColumn.Two, {
    // ommiting localResourceRoots does not set default uris as specied in the docs
    // localResourceRoots: [vscode.Uri.file(context.extensionPath)]
});

let imgPath = vscode.Uri.file(path.join(context.extensionPath, 'media', 'vscode.png')).with({
    scheme: "vscode-resource"
}).toString();
webview.html = `<img src="${imgPath}"/>`;
```

**Comment by mjbvz** [comment]
Thanks, I missed that line. I can repo this in 1.22 but not in 1.23 insiders. This may be because of environment differences or the bug may have been fixed. Will take a look to see

**Comment by OrkhanAlikhanov** [comment]
I'll test this in 1.23 insiders and report back soon.

**Comment by mjbvz** [comment]
Yes I believe this was fixed by dd21d3520a3708360c264d12864173fadd71e142 which we did not take into 1.22

**Comment by OrkhanAlikhanov** [comment]
Yep, I confirm it's working with 1.23.0 insiders.

**Comment by OrkhanAlikhanov** [comment]
I have a suggestion:
instead of writing:
`<img src="vscode-resource://dynamically/generated/url/to/extension/install/directory/logo.png">`
It would be better to introduce something like `vscode-extension-dir://` scheme which would be resolved into `vscode-resource://extension/path`, so that we could write
`<img src="vscode-extension-dir://logo.png">`

What do you think @mjbvz? Is it worth opening an issue?

**Comment by OrkhanAlikhanov** [comment]
Or defaulting base ref of the webview to the extension install directory so that we can use:
```html
<img src="logo.png">
```
@mjbvz

**Comment by mjbvz** [comment]
The original webview draft  actually did have a separate scheme for extension resources but it turned out to confuse people so we merged them. This merger also lets webviews disable access to their local resources by setting `localResourceRoots: []` which was not possible when we had the separate protocols.

Using `<base>` is interesting but better left up to the extension in my opinion (I don't think it will actually work because of how the `vscode-resource` uris works but you can try)

**Comment by OrkhanAlikhanov** [comment]
Maybe an option to intercept the requests coming out of the webview? So that we can tamper the request.
something like:
```ts
webview.onRequestMade((request) => {
  if (request.uri.scheme == 'media') {
     request.uri.scheme = 'vscode-resource';
     request.uri.path = path.join(extensionPath, request.uri.path);
  }
  return request;
});
```

```html
<img src="media://logo.png">
```

**Comment by OrkhanAlikhanov** [comment]
@mjbvz ^

**Comment by OrkhanAlikhanov** [comment]
@mjbvz, setting base href just works :+1: . I am really happy that it works, because I needed to show images in the webview from the workspace.

```ts
let mediaPath = vscode.Uri.file(path.join(context.extensionPath, 'media')).with({
    scheme: "vscode-resource"
}).toString() + '/';

webview.html = `<!DOCTYPE html>
<html>
<head>
    <base href="${mediaPath}">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<img src="vscode.png"/>    
</body>
</html>`;
```
