### ISSUE TITLE
Folder / Workspace doesn't persist after relaunch vs code.

### ISSUE THREAD

**Issue by ntnbst** [Microsoft/vscode#47638]
- VSCode Version: 1.22.1
- OS Version: MacOS 10.12.4

Steps to Reproduce:

1. Launch VS code open any folder
2. Close VS code 
3. Previously opened folder supposed to be there, but Its not.

I have to open folder each time when I launch vs code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sulkhanp** [comment]
I reported the same issue.

**Comment by bpasero** [comment]
@ntnbst are you opening VS Code and then closing the window by clicking the X button in the window?

**Comment by ntnbst** [comment]
Yes, I am closing it by clicking the X. I have used vs code on Windows and Ubuntu but that kind of thing never happened.

**Comment by ntnbst** [comment]
Oh, Yup!! Thanks.
