### ISSUE TITLE
Allow to style background of active editor & terminal

### ISSUE THREAD

**Issue by djrenren** [microsoft/vscode#47633]
It would be really helpful to allow me to style the background of my currently focused editor and terminal, as it can often be difficult to tell when there's a lot open.

Current APIs support styling the active tab and active line, but the whole editor background. This would allow the creation of subtle themes that draw attention to the correct panel like so:

<img width="1071" alt="screen shot 2018-04-10 at 11 30 54 pm" src="https://user-images.githubusercontent.com/634666/38599944-3d816516-3d17-11e8-82f0-0049e9e805bb.png">

To get this result, I had to color several elements, namely: the sidebar, the editor, and the header.

I'm unsure what granularity would be good to expose, but this seems like a helpful feature.

**Comment by cig0** [comment]
Same here: I use a light theme for my editor panes and would love to be able to use a dark theme for my terminal/debugging pane.
Thanks!

**Comment by dmolin** [comment]
any update on this feature request? bump.

**Comment by dmolin** [comment]
@cig0 , @djrenren, a bit late to the party, but I've pushed a couple of PRs that should partially satisfy your requirements. Hopefully they'll make it through.
See here: 
- https://github.com/microsoft/vscode/pull/73973 **Making the active editor background (and gutter) customizable**
- https://github.com/microsoft/vscode/pull/73848 **Controlling the background color of the active tab in an unfocused editor group**

**Comment by cig0** [comment]
Well, better late than never, right? Thanks @dmolin

**Comment by aeschli** [comment]
We like the idea but unfortunately this causes a lot of ripples. There are many other colors that are based on the editorBackground or have the editorBackground as default: e.g. the breadcrumb view, the editor widgets (e.g. find/replace. hover, code complete), editor selection colors, the editor tabs, even token color. All these colors need to go well together. Done correctly, it would mean to also introduce a 'active' color variant for these colors.

So this becomes all quite a bit of work, opens a new box, which we don't want to commit at this time. I hope you understand.
