### ISSUE TITLE
indexing php source files is not stopping

### ISSUE THREAD

**Issue by raju12974** [Microsoft/vscode#47640]
Issue Type: <b>Bug</b>

I cannot perfectly work with PHP. It is not even giving me any auto completion suggesions.
and also in source control, no files are showing.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|3.90GB (0.86GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
vscode-intelephense-client|bme|0.8.8
php-autocomplete|bsc|0.4.2
compulim-vscode-closetag|Com|1.1.0
githistory|don|0.4.0
php-intellisense|fel|2.3.1
gc-excelviewer|Gra|2.0.20
crane|Hvy|0.3.8
smarty|imp|0.3.0
php-import-checker|mar|0.0.3
python|ms-|2018.3.1
ionic3-snippets|sit|1.0.1
php-formatter|Sop|0.2.4

</details>

**Comment by roblourens** [comment]
Our built in PHP intellisense is very limited so you should try an extension for that. But can you explain this problem some more?

> and also in source control, no files are showing.

Please give exact steps and if it would help, a screenshot.
