### ISSUE TITLE
Pasting a text removes the line

### ISSUE THREAD

**Issue by allicanseenow** [Microsoft/vscode#47649]
Issue Type: <b>Bug</b>

_Cannot replicate the issue!_

There is a minor bug where if I paste a text into a file, the text vanishes, then the line where I place the text is also removed. 

This is similar to having a controlled form using react where you set the value of the form to some states but you forget to provide an onChange() function.

The bug forces me to restart the app in order to resolve the issue.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|Memory (System)|3.90GB (0.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Firefly\Desktop\a.sql|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
plsql|cas|0.0.3
githistory|don|0.4.0
gitlens|eam|8.2.0
vsc-material-theme|Equ|1.5.1
git-tree-compare|let|1.2.1
mssql|ms-|1.3.1
atom-keybindings|ms-|3.0.4
java|red|0.22.0
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0
plsql-language|xyz|1.2.2

</details>

**Comment by allicanseenow** [comment]
It is a java file. The plugins I use for java syntax highlighting can be found in my original post.

**Comment by joaomoreno** [comment]
The behaviour is related to one of the extensions. Try to narrow down which one it is and then file an issue on its repository page.
