### ISSUE TITLE
findFiles but instead of a glob language:markdown like in onLanguage actiovation event

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#47645]
Hey, I'd like to get all MarkDown files in a workspace for my extension so I can index them and enable my extension's functionality based on the index. Currently I am using `workspace.findFiles` followed by `workspace.openTextDocument` to get the contents. This works fine, however:

To get all MarkDown files using `findFiles`, I have to use a glob like `**/*.md`. This will not capture all files for which VS Code would trigger the `onLanguage:markdown` activation event, because VS Code will recognize even MarkDown files with extensions like `.markdown` and others.

I would like to propose extending the `findFiles` API in a way which allows filtering by the detected language, not just a file glob. In my view something like `findFiles('language:markdown')` would be a good proposed API, but maybe an overload or a different method will have been found to be a better choice.

I know I can extend my glob to include multiple extension, all of which VS Code will detect the MarkDown language for, but I think it would be better to have this set in one place and it already is in the API, so it makes sense to reuse it.

**Comment by roblourens** [comment]
I don't know if there are enough general usecases for this to consider it as API. Users can associate any file extension to a language with "files.associations" which might be unexpected.

What do you think @jrieken?

**Comment by TomasHubelbauer** [comment]
@roblourens can you revisit this in relation to #48674?

**Comment by roblourens** [comment]
I'm not sure what you mean.

**Comment by TomasHubelbauer** [comment]
What I am suggesting is that adding an overload with either the aforementioned syntax `language:markdown` or even an actual `DocumentSelector` could be a solution for avoiding BC in the ticket I mentioned.

**Comment by TomasHubelbauer** [comment]
Sorry, you are right.
I got my issue mixed up, because I would benefit from both mentioned in my workaround for the other issue.
