### ISSUE TITLE
prompt user when deleting breakpoint with condition or log message

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#47643]
from twitter: https://twitter.com/raymondcamden/status/983758857490108416

We should prompt the user when a breakpoint with condition and/or logMessage is removed from the gutter by clicking on the icon. Any other means of deletion should not prompt.

The prompt should offer to disable or to really delete.

**Comment by isidorn** [comment]
Not a big fan of this, since then the prompt should also have an option to never ask again.
Feels a bit too heavy for me, the worst thing is that you have to re-enter the condition if you remove a bp by accident.

Do VS and VS for mac prompt?

**Comment by weinand** [comment]
I've discussed this with Erich and we both agreed that we want this.

**Comment by isidorn** [comment]
Would you expect and "never prompt again" check or not?
If yes, would you write this in the user settings or in local storage? We usually write these things in settings so users can edit them, in case we decide to do that we need a name, for example `debug.confirmBreakpointRemove` which by default is true.

**Comment by cfjedimaster** [comment]
I'd say write to settings so it's easy to reverse later on.

**Comment by isidorn** [comment]
![bpdialog](https://user-images.githubusercontent.com/1926584/38936661-943b8930-4321-11e8-808e-cb0481c12e3a.gif)

**Comment by roblourens** [comment]
I like this prompt because I've made this mistake before. The wording "valuable condition" threw me off at first because I thought, there's nothing extra special about the condition...

You might want to just say "has a condition"

**Comment by isidorn** [comment]
@roblourens thanks. I am fine with changing the wording however I will let @weinand decide

**Comment by weinand** [comment]
I'm fine with Rob's suggestion
