### ISSUE TITLE
#region myTitle - is not collapsing after update.

### ISSUE THREAD

**Issue by churkinv** [Microsoft/vscode#47647]
Issue Type: <b>Bug</b>

Hi, it used to collapse, but after today`s update not anymore:

//#region Test
// function PersonFunction() {
//     this.name = "BatmanFunction";
//     this.surname = "Robinson";
// }
//#endregion

But if I use simple region without title, it works properly:
//#region 
// function PersonFunction() {
//     this.name = "BatmanFunction";
//     this.surname = "Robinson";
// }
//#endregion

Thanks,

**Comment by mjbvz** [comment]
Duplicate of #44530 

Setting `"typescript.experimental.syntaxFolding": false` will disable the new syntax based folding and should fix this issue.
