### ISSUE TITLE
Python cycle() debugging results in a runaway process that crashes the system

### ISSUE THREAD

**Issue by glubsy** [Microsoft/vscode#47642]
- VSCode Version: 1.21.1
- OS Version: Antergos (Arch Linux based) kernel 4.14.32-1-lts

Steps to Reproduce:

1. Create a cycle() in a python script
2. Start debugging
3. Hover the mouse cursor above the cycle object instance
4. Click "items" to expand the details view
5. VSCode will allocate memory ad infinitum and crash the entire system.

Does this issue occur when all extensions are disabled?: don't know yet, haven't tried (it's scary).

Since the crash I have upgraded to VSCode 1.22. I wasn't sure whether to report this to the python extension or not.

**Comment by weinand** [comment]
please report to Python extension.

**Comment by glubsy** [comment]
Reported to Python extension: https://github.com/DonJayamanne/pythonVSCode/issues/1410

Thank you.
