### ISSUE TITLE
"File is a directory" on preforming an action like opening settings.

### ISSUE THREAD

**Issue by StefanPahlplatz** [Microsoft/vscode#47659]
- VSCode Version: 1.22.1 (with the .deb file) and 1.20.1 (with the snap package)
- OS Version: Ubuntu Bionic Beaver (development branch) x86_64
- Node Version: 

I can't perform actions like changing the theme, settings an icon theme, opening settings. It all gives me the error "File is a directory".

Steps to Reproduce:

1. Be on Ubuntu Bionic Beaver (development branch) x86_64
1. Install VSCode with the .deb file or via snap.
2. Open settings from File -> Preferences -> Settings.

Does this issue occur when all extensions are disabled?: Yes

Error details:
With .deb installation:
```js
notificationsAlerts.ts:39 File is directory
e.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.error @ notificationService.ts:61
(anonymous) @ actions.ts:93
```

With snap installation:
```js
messageService.ts:126 File is directory: Error: File is directory
    at new t (file:///snap/vscode/27/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1258:989)
    at m (file:///snap/vscode/27/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2786:654)
    at file:///snap/vscode/27/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2787:215
    at callback (/snap/vscode/27/usr/share/code/resources/app/node_modules/graceful-fs/polyfills.js:128:19)
    at FSReqWrap.wrapper [as oncomplete] (original-fs.js:629:17)
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous) @ actions.ts:94
```

**Comment by roblourens** [comment]
Can you try launching with `--user-data-dir` and some tmp user data dir?

Or try opening a different folder?

**Comment by StefanPahlplatz** [comment]
```sh
mkdir ~/temp
code . --user-data-dir ~/temp
```
Fixes the problem for that instance of vscode.

**Comment by bpasero** [comment]
@StefanPahlplatz can you check if `/home/<user>/.config/Code/User/settings.json` is a folder for you maybe?
