### ISSUE TITLE
Webview is disposed even if retainContextWhenHidden is true

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [Microsoft/vscode#47653]
- VSCode Version: 1.23.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Create `webview` with `retainContextWhenHidden: true` option.
2. Close the webview editor.
3. Try to reveal `webview` again.

```ts
webview = window.createWebview("id", "Hello", ViewColumn.Two, {});
webview.onDidDispose(() => {
   // webview is dispsoed but it shouln't be since we've set `retainContextWhenHidden: true`
});
```

Another thing is that there is no way to know if a `webview` is disposed or not except listening to the `onDidDispose` event. It would be better to add `isDisposed` property, I think.

I see that retainContextWhenHidden option is used in `releaseWebview()` method but it's bypassed it somehow.

https://github.com/Microsoft/vscode/blob/8150982b205cbab9ac1be19fd687386b5d18d391/src/vs/workbench/parts/webview/electron-browser/webviewEditorInput.ts#L198-L207

-----------
#### Edit

Well regardless of `retainContextWhenHidden`, webview is never disposed. Checking the [`(webview as any)._isDisposed`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostWebview.ts#L22) shows that it's not disposed.

It seems its handle is just removed when `WebviewInput` is disposed. See 

https://github.com/Microsoft/vscode/blob/d855ec8060247c7bccb1835e4c53a43ba3ec19e4/src/vs/workbench/api/electron-browser/mainThreadWebview.ts#L174-L184

https://github.com/Microsoft/vscode/blob/52c293a05038d865604c2284aa8698bd087915a1/src/vs/workbench/api/node/extHostWebview.ts#L200-L207

**Comment by OrkhanAlikhanov** [comment]
https://github.com/Microsoft/vscode/blob/1b33eb37d5df3b74d373bde1f8b6446fa4df88e5/src/vs/workbench/api/node/extHost.protocol.ts#L366-L367

There is a typo `Weview` should be `WebView` apparently :)

**Comment by mjbvz** [comment]
You are confusing the context with the webview.

The context is the actual iframe like element that shows the html. This is what `retainContextWhenHidden` keeps around even when the webview editor becomes hidden.

A webview itself is a representation of content that will be rendered as html. This webview may or may not have a context (iframe) depending on its visibility and the value of `retainContextWhenHidden`.

**Comment by OrkhanAlikhanov** [comment]
Well, when does exactly the context get disposed? Like when the visible tab is changed? I still don't get it.

**Comment by mjbvz** [comment]
Here's the normal flow:

- Webview editor becomes visible -> context created from webview state
- Webview editor becomes hidden  -> context destroyed
- Webview editor closed -> destroyed events fired 

With `retainContextWhenHidden`:

- Webview editor becomes visible -> context created from webview state
- Webview editor becomes hidden  ->  context keep in background
- Webview editor becomes visible again -> same context put back into foreground
- Webview editor closed -> destroyed events fired

**Comment by mjbvz** [comment]
1. That is by-design. You must listen to `onDidDispose`. This is the same pattern other disposables follow
2. Don't access private state. It may or not be what you expect

**Comment by OrkhanAlikhanov** [comment]
Thank you for your response. Just wanted to make sure that there is no memory leak, lol
