### ISSUE TITLE
Search (Ctrl+Shif+F) does not support lookaheads

### ISSUE THREAD

**Issue by Vinno97** [Microsoft/vscode#47657]
Issue Type: <b>Bug</b>

**description:**
VSCode does not support lookaheads when searching through the workspace files (Ctrl+Shift+F). Normal search (Ctrl+F) **does** support lookaheads.

**Steps to reproduce:**

1. Press `Ctrl+Shift+F`
2. Enter `foo(?=bar)` (for a positive lookahead) or `foo(?!bar)` (for a negative lookahead)
3. Notice the error `Error parsing regex near `foo(?=bar)` at character offset 5: Unrecognized flag: '='. (Allowed flags: i, m, s, U, u, x.)

**Installation summary:**

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU G550 @ 2.60GHz (2 x 1829)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.77GB (0.31GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-docker|Pet|0.0.26
vscode-eslint|dba|1.4.8
dotenv|mik|1.0.1
vscode-yaml|red|0.0.11

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This isn't supported right now because the search tool we use, ripgrep, doesn't support these regex features.

**Comment by mysticatea** [comment]
@roblourens Would you reopen this issue as a feature request?
