### ISSUE TITLE
snippet too slow

### ISSUE THREAD

**Issue by vortechron** [Microsoft/vscode#47655]
im new to vscode and want to try out snippet for php:

this is my php.json:
```json

{
	"pubfunc": {
		"prefix": "pubfunc",
		"body": [
			"public function $1()\r",
			"{\r",
			"\t$2",
			"}"
		],
		"description": "create public method"
	}
}

```

it takes a very long time for my snippet suggestion to popup. the only temporary fix is to set 
"editor.tabCompletion": true

i have a lot of snippet in my sublime, and it take a second for snippet suggestion to popup. please optimize the snippet suggestion.

**Comment by jrieken** [comment]
Please try with extensions and please provide the language in which this happens. Also, how many snippets do you have configured?

**Comment by vortechron** [comment]
@jrieken sorry for lack on info.

Language: PHP
Snippet: only 1
Installed Extension: intelelephense & intellisense

**Comment by jrieken** [comment]
Ok, please try without extensions... It's likely that an extension computes suggestion slowly and that snippets have to wait for that to finish. Only once all providers have computed a result, they are displayed

**Comment by vortechron** [comment]
@jrieken 

without extensions seems to fix my issues, so is this mean that i need to disable my extensions?

**Comment by bmewburn** [comment]
Try enabling the extensions one at a time to narrow it down.

**Comment by vortechron** [comment]
@bmewburn time delay for snippet suggestion has reduce from 5 sec to 3 sec.
