### ISSUE TITLE
Custom problem matcher "kind": "file" doesn't matches

### ISSUE THREAD

**Issue by IevgenSobko** [Microsoft/vscode#47652]
For the following console output 
```
[ i ] PROCESS SUITES/TESTS RESULTS ...
-------------------------------------------------------------------------------
 Suite: inline_files_list (1 tests)
-------------------------------------------------------------------------------
 failed: 1
-------------------------------------------------------------------------------
| 00:00:05 |    failed | w/o browser@Manjaro Linux | nogui/fs_sands_profile.rb
-------------------------------------------------------------------------------
 Suite start time  : 12:41:09
 Suite end time    : 12:41:20
 Suite elapsed time: 00:00:11
-------------------------------------------------------------------------------
[ ! ] Failed tests list was stored in 'inline_files_list_failed' suite.
```
custom problem matcher works with following pattern matcher
```json
        "pattern": [
          {
            "regexp": "^(\\|.*failed\\s+\\|.*\\|(.*))$",
            "file": 2,
            "location": 0,
            "message": 1
          }
        ]
```
but I dont need location so I read in documentation that there is _"kind": "file"_ field to avoid location to be in problem so I changed matcher to 
```json
        "pattern": [
          {
            "kind": "file",
            "regexp": "^(\\|.*failed\\s+\\|.*\\|(.*))$",
            "file": 2,
            "message": 1
          }
        ]
```
but this doesn't match problem with the same console output.
I would expect it is matched as error

**VSCode Version:**
Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T00:24:49.616Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
**OS Version:**
System:    Host: DzirT-LT Kernel: 4.9.92-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.12.3 
           Distro: Manjaro Linux 17.1.7 Hakoila 
Machine:   Type: Laptop System: Dell product: XPS 15 9550 v: N/A serial: N/A

**Comment by dbaeumer** [comment]
Fixed for next build
