### ISSUE TITLE
Organize Imports: Make spaces in imports configurable

### ISSUE THREAD

**Issue by MichaelRBond** [Microsoft/vscode#47654]
Organize imports is a welcome feature. 

However, it does not match the style that JetBrains Webstorm currently uses. Webstorm auto imports with the style: `import {Foo} from "bar";` ... note the lack of spaces in the brackets. 

Unfortunately this leads to a lot of churn in git Pull Requests when a team has a mix of Webstorm and VS-Code users. 

Suggest making import style configurable, per project via `.vscode/settings.json`, to include or exclude the spaces in the imports.

**Comment by mjbvz** [comment]
Try setting: `"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false` or `"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false `
