### ISSUE TITLE
[1.22.1]cursor jump to end line after code format

### ISSUE THREAD

**Issue by niltor** [Microsoft/vscode#47666]
Issue Type: <b>Bug</b>

Update to 1.22.1，when I edit a .html file，press  shift+alt+f，the codes will be formatted, and the cursor will move to the end line!
Befor update,this is not a problem!

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:27:19.487Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|15.90GB (9.61GB free)|
|Process Argv|d:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
Angular-BeastCode|Mik|6.0.9
csharp|ms-|1.14.0
quicktype|qui|10.0.24
vscode-angular-support|vis|0.1.4
html-css-class-completion|Zig|1.17.1

</details>

**Comment by ramya-rao-a** [comment]
@niltor Do you see the same after running `code --disable-extensions` or in the latest [Insiders](https://code.visualstudio.com/insiders)?

**Comment by ramya-rao-a** [comment]
@niltor The fix is currently available in the [Insiders](https://code.visualstudio.com/insiders) build of 1.23. The fix will also be shipped in stable VS Code version 1.22.2 in a few days

**Comment by niltor** [comment]
@ramya-rao-a   Thanks for your answer!  I'll wait next  update!

**Comment by hihahihahoho** [comment]
i have the same problem but  the cursor jumps to the end of file instead

**Comment by ramya-rao-a** [comment]
The fix is now out in the latest release 1.22.2
