### ISSUE TITLE
Feature request: Highlight code block surrounded by selected brackets with vertical line

### ISSUE THREAD

**Issue by Somnium7** [Microsoft/vscode#47665]
Please implement block highlighting with vertical line like this:
![fr1](https://user-images.githubusercontent.com/23244522/38622528-0a4511da-3dac-11e8-9eea-762a369d1687.png)

You can find such functionality in Notepad++ for example. It makes it more easier to work with large code blocks. Feature should be available for all bracket types (also user-defined in language settings).

For misaligned brackets, highlight by left-most bracket, it will help to identify misaligned code (Notepad++ in this case highlights nothing, which is not useful in my opinion). Like this:
![fr2](https://user-images.githubusercontent.com/23244522/38622879-e4957f82-3dac-11e8-9821-c5c34daf145f.png)

**Comment by roblourens** [comment]
You can see the https://marketplace.visualstudio.com/items?itemName=byi8220.indented-block-highlighting extension which is similar.

**Comment by Somnium7** [comment]
That extension does different thing - it highlights whole block, which in my opinion is less useful, it does not provide info about indentation level.

**Comment by roblourens** [comment]
We have this issue tracking it with another extension link: https://github.com/Microsoft/vscode/issues/14017

**Comment by Somnium7** [comment]
Thanks, installed [Identicator](https://marketplace.visualstudio.com/items?itemName=SirTori.indenticator), it precisely what I needed, it's a shame though that it's not core feature.

**Comment by Somnium7** [comment]
Found a lot better alternative - [Bracket Pair Colorizer](https://github.com/CoenraadS/BracketPair), it accurately finds current block (and highlights it even if indentation is incorrect), plus it colorizes brackets. Downside - it works for limited range of languages.
