### ISSUE TITLE
Keyboard shortcut to quickly switch workspace

### ISSUE THREAD

**Issue by akshah123** [Microsoft/vscode#47668]
_This is a feature request_
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce: N/A

I have multiple workspaces setup on my machine.  It would be great if there was a keyboard shortcut that would allow me to quickly switch between different workspaces.

Sort of like how sublime lets you using: ctrl + alt + p

**Comment by roblourens** [comment]
ctrl+r by default is "open recent", is that like what you're looking for?

**Comment by akshah123** [comment]
That totally works.  I feel a little stupid not realizing it.  

Thanks for quick response and suggestion.
