### ISSUE TITLE
Why removing the 2 boxes include/exclude ?

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#47662]
I cannot figure out why this feature was removed. It's very usefull to "semi"-permanently (depending on what you are working on) exclude some folder from searching in a repository, and just include specific ones when you specificly search on something.

![image](https://user-images.githubusercontent.com/5599375/38622094-a762eac8-3da2-11e8-8897-e0fd33cacf22.png)

I don't get the point of removing functionnalities.

**Comment by roblourens** [comment]
The functionality is the same - you can still exclude folders, using `!`. I have https://github.com/Microsoft/vscode/issues/46315 for more discussion on this.

If you want to exclude them long term I recommend using the search.exclude setting.

**Comment by CoeusCC** [comment]
Man, totally blindsided by that one. I like that the answer is already here, and I do like the change, but that certainly seems like an "opt-in" change via settings.

**Comment by DavidBabel** [comment]
It brokes totally when it's used with "search in this folder"

![image](https://user-images.githubusercontent.com/5599375/39578284-07a3d42c-4ee4-11e8-98df-6932ef69ae00.png)


Since it erase everything in your include/exclude field.
