### ISSUE TITLE
New updated version doesn't allow to collapse non-functions block of codes

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#47667]
I updated VSCode this morning and suddenly I can't collapse blocks of code that aren't wrapped in curly brackets.

- VSCode Version:1.22.1
- OS Version: Ubuntu 16.4
 
For example: 

```
var test = createTest(
    anotherFunction(
        param1,
        param2
    )
);
```

before I was able to collapse it as I don't want it in one line. 

Same with JavaScript string using ticks:

```
var string = `test
    test
    test
    test`;
```

Used to let me collapse it, but not anymore, also if within that string I have curly brackets I can't collapse them either:

```
var string = `test
    test {
        something
        something2
    }
    test`;
```

**Comment by mjbvz** [comment]
Try setting: 

```
    "[javascript]": {
        "editor.foldingStrategy": "indentation"
    },
```

I've opened https://github.com/Microsoft/TypeScript/issues/23382 to track enabling folding of multiline template strings when using syntax aware folding
