### ISSUE TITLE
F12 and CTRL + space for PHP functions and variables of classes written by me

### ISSUE THREAD

**Issue by darcome** [Microsoft/vscode#4766]
I'd really like to have intellisense and code completion (did I use the right words?) for php classes written by me and not only for the standard ones

Thanks in advance

**Comment by felixfbecker** [comment]
Working on it

**Comment by darcome** [comment]
Is there any way I can help you? maybe testing your work?

**Comment by Tyriar** [comment]
We defer to extension developers for rich PHP development right now, closing this off.
