### ISSUE TITLE
Generated JSDoc does not generate typings for TypeScript

### ISSUE THREAD

**Issue by Divni** [Microsoft/vscode#47675]
- VSCode Version: 1.22.o-insiders
- OS Version: Arch

Steps to Reproduce:

Use code:

```
create(emmetStr: string): string {

}
```

1. Write `/**` above a function definition with defined types and hit enter

Expected:

```
    /**
     * 
     * @param {string} emmetStr 
     *
     * @return {string}
     */
```

Actual:

```
    /**
     * 
     * @param emmetStr 
     */
```

**Comment by mjbvz** [comment]
This is by-design. The types are already in your code and typescript ignores the jsdoc types. You only need to use jsdocs to add descriptions
