### ISSUE TITLE
Outline View remain expanded

### ISSUE THREAD

**Issue by granteagon** [Microsoft/vscode#47672]
Issue Type: <b>Feature Request</b>

It would be nice if the outline view would remember what I had expanded when I change between files.  It's tedious to keep having to expand the sections I want to see simply because I changed window focus to a different file.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.15063

**Comment by roblourens** [comment]
What do you mean by "outline view" here?

**Comment by granteagon** [comment]
The Code Outline that appears in the explorer pane.

**Comment by sandy081** [comment]
@roblourens This view is coming from an extension and Please file the feature request against it. Thanks.
