### ISSUE TITLE
Import orginization doesn't honor tslint line length rules

### ISSUE THREAD

**Issue by MichaelRBond** [Microsoft/vscode#47679]
Issue Type: <b>Bug</b>

If imports are broken up across multiple lines, to honor tslint line length limits, running `Organize Imports` will merge imports onto a single line causing a tslint error.

Reproduce:
* split imports across multiple lines
* run `Organize Imports`

Expected result:
* import lines do not exceed TSLint line length

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_3691397|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.14.1
todo-tree|Gru|0.0.31
JSDocTagComplete|Hoo|0.0.2
vscode-todo|Mat|0.8.0
vscode-docker|Pet|0.0.26
cform|aws|0.0.10
solargraph|cas|0.15.0
tslint|eg2|1.0.28
json-tools|eri|1.0.2
vscode-emacs|hir|0.1.1
ruby-linter|hoo|1.0.0
terraform|mau|0.0.23
prettify-json|moh|0.0.3
python|ms-|2018.3.1
azure-account|ms-|0.4.0
dust|nem|0.0.1
Ruby|reb|0.18.0
java|red|0.22.0
vscode-icons|rob|7.22.0
code-spell-checker|str|1.6.6
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.6.0
vscode-todo-highlight|way|0.5.12

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23381
