### ISSUE TITLE
VSCode 1.22 reads incorrect environment variables

### ISSUE THREAD

**Issue by markeissler** [Microsoft/vscode#47673]
As of __VSCode 1.22__, GOPATH is no longer set correctly from the environment when using the __vscode-go__ extension. Restoring __VSCode 1.21.1 fixes the problem.__ I'm not sure if this is a VSCode bug or API change that needs to be reflected in vscode-go, but have also opened an issue on the [vscode-go](https://github.com/Microsoft/vscode-go) project:

[GOPATH from environment broken with VSCode 1.22 #1621](https://github.com/Microsoft/vscode-go/issues/1621)

In summary, what appears to be happening is that __VSCode__ is changing into a different directory and/or spawning a new shell first before reading environment variables. Even if I set `$GOPATH` manually from the cli, then launch VSCode with `code .` in the project directory (as I always have done) the `$GOPATH` is reset (as reported by running the `Go: Current GOPATH` command in __VSCode__.

Rolling back to __VSCode 1.21.1__ and loading the exact same extensions resolves the problem entirely. (As an aside: it would be super convenient if an archive of VSCode previous releases was made available for when stuff like this happens.)

**Comment by joaomoreno** [comment]
> Even if I set $GOPATH manually from the cli, then launch VSCode with code . in the project directory (as I always have done) the $GOPATH is reset (as reported by running the Go: Current GOPATH command in VSCode.

That is odd. @ramya-rao-a, can you check whether this is something specific to the `GOPATH` variable?

**Comment by markeissler** [comment]
In the meantime, I will continue to work with __VSCode 1.21.1__. At least I have that as a work around.

For anyone that runs into this problem (on macOS) you can rollback with:

[VSCode 1.21.1 - macOS](https://vscode-update.azurewebsites.net/1.21.1/darwin/stable)

**Comment by markeissler** [comment]
I'm closing this issue as I'm not able to replicate 24hrs later. Not sure what's going on here although I did notice 1.22.2 has been released in the meantime, and auto-installed on my system.
