### ISSUE TITLE
High cpu usage MacOS

### ISSUE THREAD

**Issue by l41lt0n** [Microsoft/vscode#47676]
Hello everyone.

The last days ( later last release ) VS code is using a lot of CPU.

What is it?
<img width="493" alt="screen shot 2018-04-11 at 14 01 08" src="https://user-images.githubusercontent.com/32529405/38631972-a7fe6176-3d91-11e8-8d16-a06cffedffac.png">

Someone can help?

**Comment by l41lt0n** [comment]
Hi @roblourens,

<img width="1458" alt="screen shot 2018-04-12 at 14 26 51" src="https://user-images.githubusercontent.com/32529405/38693815-6dfb3346-3e5e-11e8-9e7c-822b4792b7aa.png">

So, the problem is with the extension?

**Comment by roblourens** [comment]
Yes, please file an issue on that extension's repo
