### ISSUE TITLE
TS defs intellisense broken for vanilla JS in latest update

### ISSUE THREAD

**Issue by Jazcash** [Microsoft/vscode#47670]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

1. Add dot after local variable that is `/** @type {Phaser.Game} */ var game;`
2. Intellisense for Phaser.Game no longer appears

Does this issue occur when all extensions are disabled?: Yes

Me and a friend are having this issue only since updating to 1.22.1

If I do Ctrl+Space after typing my variable it sometimes gets stuck saying "Loading..." in the tooltip.

**Comment by mjbvz** [comment]
Please share an example project or at least code showing where `Phaser` is defined and how it is imported into the current file

**Comment by Jazcash** [comment]
It's a global set by RequireJS, but that shouldn't matter because of the `/** @type {Phaser.Game} */` declaration on `var game;`, right? At least, it worked in all previous VSCode versions

**Comment by mjbvz** [comment]
Please share example code. What does the `Phaser` object look like? How is `Game` defined on it?

**Comment by Jazcash** [comment]
https://github.com/photonstorm/phaser-ce/blob/a5b1f59746c5577e40349f8c36387b8b53f7146a/typescript/phaser.d.ts#L1502

**Comment by mjbvz** [comment]
I can't repo this:

![screen shot 2018-04-13 at 2 39 45 pm](https://user-images.githubusercontent.com/12821956/38758992-882db85e-3f28-11e8-8013-1c2d5769874b.png)

Please share more info about your project structure, or better yet a sample sample project. Do you have a jsconfig.json for example?

**Comment by Jazcash** [comment]
Huh, how strange. Here's mine:

![example](https://user-images.githubusercontent.com/1434248/38767793-056b5e2c-3fe0-11e8-9d42-875c571ecac5.jpg)

And my jsconfig.json:

```
{
    "compilerOptions": {
        "checkJs": false
    }
}
```

**Comment by Jazcash** [comment]
Actually, Intellisense in general is being really weird for only this project in general. It's randomly extremely slow or flat-out won't work at all, other times it works fine. Willing for this issue to be closed under the assumption it's just some weird bug with requirejs or some other config mucking it up...

**Comment by mjbvz** [comment]
Try adding an exclude section to your `jsconfig` just to make sure extra files aren't being picked up:

```
{
    "compilerOptions": { },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

When you notice the slowdown, also try running `code --status` from the command line. This should say which code process is using the most memory and cpu

**Comment by Jazcash** [comment]
Output when intellisense hangs:

```
CPU %   Mem MB     PID  Process
    0       62    9152  code main
    0       51    9384     gpu-process
    0       33    9840     shared-process
    0       79   12412     window (game.js - examplegame - Visual Studio Code)
    0       13    3848       watcherService
    0        5    3076         console-window-host (Windows internal process)
    0       25    7436       extensionHost
    0       22    3124         electron_node electronForkStart.js tsserver.js
    0       18    9624           electron_node typingsInstaller.js tsserver.js typesMap.js
    0       19   10276         electron_node eslintServer.js
    0       21   10628         electron_node jsonServerMain.js
    0       19   10952         electron_node tslintServer.js
    1      155   16072     window (ÔùÅ game.js - coolproject-gdm - Visual Studio Code)
    0       60   15904       extensionHost
    0       25    9900         electron_node eslintServer.js
    0       32   12784         electron_node jsonServerMain.js
    0       25   16416         electron_node tslintServer.js
   26     1062   16788         electron_node electronForkStart.js tsserver.js
    0       32    5972           electron_node typingsInstaller.js tsserver.js typesMap.js
    0       13   16168       watcherService
    0        9   16156         console-window-host (Windows internal process)
```

**Comment by mjbvz** [comment]
@Jazcash Please try the latest VS Code insiders build. If that doesn't work, try upgrading to TypeScript@next in your workspace by following these instructions: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions
