### ISSUE TITLE
Outline View in Minimap section

### ISSUE THREAD

**Issue by granteagon** [Microsoft/vscode#47671]
Issue Type: <b>Feature Request</b>

I would like to see an outline of my files where the minimap typcially appears.  That would help me see at a glance if the file needed refactoring, as well as reading the available properties and methods.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.15063

**Comment by roblourens** [comment]
mega-issue here: https://github.com/Microsoft/vscode/issues/5605
