### ISSUE TITLE
Highlight of syntax in the buckets of Laravel

### ISSUE THREAD

**Issue by osmanc777** [Microsoft/vscode#47686]
Hi, I wanted to take advantage of this opportunity to inform you that in the last 2 updates released, I am in conflict with the syntax highlighting in the larave blades, and it is not the issue that I have installed since I have changed themes to see if that was the problem but it was not, it looks like a plain text and it does not highlight the html and blade labels, in the .blade.php format and when it is only .html there if I highlight everything normally.

In version 1.18.1 of vs code if syntax highlights in a correct way in the .blade.php I hope you can fix it soon :) since now this is my favorite edited since I work a lot with Laravel, Angular, Ionic etc. ..

mi sistema operativo es Windows 10

Screens:
## Version 1.18.1
![version 1.18.1](https://pagalocash.com/wp-content/uploads/2018/04/screen-last-version.png)

## New Version
![new version](https://pagalocash.com/wp-content/uploads/2018/04/screen-previous-version.png)

**Comment by roblourens** [comment]
Are you using an extension to provide Laravel highlighting?

**Comment by roblourens** [comment]
It sounds like all of those extensions are contributing syntax highlighting for blade files. If you can figure out which one is doing it wrong, please file an issue on that extension.
