### ISSUE TITLE
custom snippet added twice + not the first entry

### ISSUE THREAD

**Issue by Cipa** [Microsoft/vscode#47681]
custom snippet added twice + not the first entry

- VSCode Version:1.22.1
- OS Version: 10.13.4

Steps to Reproduce:

1. add 

```
"if": {
		"prefix": "if",
		"body": [
			"<?php if ('$1'): ?>",
			"<?php else: ?>",
			"<?php endif; ?>"
		],
		"description": "if else",
	},
```

to html.json

2. see image
you can see 3 if, first is empty the second 2 are the same

<img width="563" alt="screen shot 2018-04-11 at 11 13 02 am" src="https://user-images.githubusercontent.com/293377/38635160-58b5d846-3d79-11e8-85d9-2505127c3c0a.png">

Does this issue occur when all extensions are disabled?: Yes/No

One of the if(second or third) comes from an extension(or is duplicated by an extension, but I can't seem to find which one, as now I disabled most of them, that might be related and I get only one good if item)
when all are disabled the first if is still there when it shouldn't as it does nothing.

**Comment by jrieken** [comment]
The first is  a keyword suggestion, see the differences in the icons

**Comment by roblourens** [comment]
Yes and the other snippet is a builtin `if` snippet.

**Comment by Cipa** [comment]
For the sake of faster coding shouldn't the keyword suggestion be second if exact snippets are found, or something like that
