### ISSUE TITLE
Split window in rows (not only in columns)

### ISSUE THREAD

**Issue by pacovalverde** [Microsoft/vscode#47682]
Hello, I see this option:
// Controla cómo se deben ajustar las líneas. Pueden ser:
  //  - "off" (deshabilitar ajuste),
  //  - "on" (ajuste de ventanilla),
  //  - "wordWrapColumn" (ajustar en "editor.wordWrapColumn") o
  //  - "bounded" (ajustar en la parte mínima de la ventanilla y "editor.wordWrapColumn").
  "editor.wordWrap": "off",

I would like editor.wordWrapRow for multiples windows en multiples rows. Only there is split the window in column, not in rows.

Kind regards.

**Comment by joaomoreno** [comment]
#14909
