### ISSUE TITLE
Proxy environment variables not inherited in integrated terminal when VSCode is launched from Taskbar

### ISSUE THREAD

**Issue by samherrmann** [Microsoft/vscode#47684]
- VSCode Version: 1.22.1
- OS Version: CentOS 7

Steps to Reproduce:

1. Open the **Network** GUI from the task bar under **Applications** -> **System Tools** -> **Settings** 
2. In the Network GUI, select _Network proxy_ on the left.
3. Set **HTTP Proxy**, **HTTPS Proxy** and **Ignore Hosts**.
4. Restart computer (not actually needed to reproduce the problem, but to exclude the possibility that the solution to the problem is a restart).
5. Open a terminal (bash) and type `env | grep -i proxy`.
Output:
```
NO_PROXY=...
http_proxy=...
https_proxy=...
HTTPS_PROXY=...
no_proxy=...
HTTP_PROXY=...
```
Where `...` is the value you entered for each field in the Network GUI.
6. Launch VSCode through the terminal (type `code` and enter).
7. Open an integrated terminal (default is also bash) in VSCode.
8. Again type `env | grep -i proxy` in the integrated terminal. Same output as in step 5 should be observed. So far so good.
9. Now open VSCode either through the taskbar (**Applications** -> **Programming**) or through a Files context menu (right click on folder and open with VSCode).
10. Repeat steps 7 and 8. This time, the output of the command is empty. The expected output is the same as in step 5 and 8.

Consequence:

Commands such as `npm install` that make network requests and depend on the proxy settings fail in the integrated terminal when VSCode was opened through the Taskbar. The command succeeds if VSCode was opened through the terminal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
> Now open VSCode either through the taskbar

When you do that, can you open the Developer Tools and see if there's a warning in the Console?

**Comment by samherrmann** [comment]
The developer tools console is empty, no warnings.

**Comment by joaomoreno** [comment]
And what do you get when running `process.env`?

**Comment by samherrmann** [comment]
I get the same result: I.e. the output of `process.env` contains the proxy environment variables if VSCode was opened through a terminal, but it does not include them if VSCode was opened through the taskbar. If you need to know the exact output then let me know, I'll have to go through a corporate process to get the information out of the lab.

Another discovery:
If I open VSCode through a terminal, and then I open another instance of VSCode through the taskbar (while the first instance is still running), then both instances will contain the proxy env variables. If I reverse the order (first instance opened through taskbar and second instance opened through terminal), then the taskbar instance does not contains the proxy env variables while the terminal instance does. Perhaps this is an expected behaviour? If VSCode is opened through terminal, then its env variables are inherited from the terminal no matter if another instance is already running or not. If VSCode is opened through taskbar, then if another instance is already running its env variables are inherited from the first instance?

**Comment by joaomoreno** [comment]
What if you run `process.lazyEnv.then(r => console.log(r), err => console.error(err))`?

**Comment by samherrmann** [comment]
I get the same result: i.e. `r` is an object that contains the env variables if VSCode was opened with terminal, and `r` is an object that does not contain the env variables if VSCode was opened from taskbar.

**Comment by joaomoreno** [comment]
And is  `process.env['SHELL']` your regular shell?

**Comment by samherrmann** [comment]
Yes, in both cases `process.env['SHELL']` contains the value `/bin/bash`

**Comment by samherrmann** [comment]
It looks like this is a GNOME specific thing. Take a look at [this](https://developer.gnome.org/ProxyConfiguration/). I confirmed that with the following commands I can pick up the proxy settings:
```
gsettings get org.gnome.system.proxy.http host
gsettings get org.gnome.system.proxy.https host
gsettings get org.gnome.system.proxy ignore-hosts
```
How do other applications do it?
When I open a bash terminal through the taskbar, it launches `gnome-terminal` (see `/usr/share/applications/Terminal.desktop` . So perhaps `gnome-terminal` calls `gsettings` at startup? I am by no means a Linux/GNOME/CentOS expert :)

**Comment by joaomoreno** [comment]
I believe it is more universal to set the HTTP_PROXY variables in your `.bashrc`.
