### ISSUE TITLE
Windows: GitBash terminal showing escaped(?) characters

### ISSUE THREAD

**Issue by InquisitiveDevelopment** [Microsoft/vscode#47688]
Issue Type: <b>Bug</b>

Using `php artisan` for a Laravel project is displaying escaped (I believe) characters. This happens when using the GitBash terminal.

i.e.
```
?[33mpackage?[39m
  ?[32mpackage:discover?[39m     Rebuild the cached package manifest
 ?[33mqueue?[39m
  ?[32mqueue:failed?[39m         List all of the failed queue jobs
  ?[32mqueue:failed-table?[39m   Create a migration for the failed queue jobs database table
  ?[32mqueue:flush?[39m          Flush all of the failed queue jobs
  ?[32mqueue:forget?[39m         Delete a failed queue job
  ?[32mqueue:listen?[39m         Listen to a given queue
  ?[32mqueue:restart?[39m        Restart queue worker daemons after their current job
  ?[32mqueue:retry?[39m          Retry a failed queue job
  ?[32mqueue:table?[39m          Create a migration for the queue jobs database table
  ?[32mqueue:work?[39m           Start processing jobs on the queue as a daemon
 ?[33mroute?[39m
  ?[32mroute:cache?[39m          Create a route cache file for faster route registration
  ?[32mroute:clear?[39m          Remove the route cache file
  ?[32mroute:list?[39m           List all registered routes
 ?[33mschedule?[39m
  ?[32mschedule:run?[39m         Run the scheduled commands
 ?[33msession?[39m
  ?[32msession:table?[39m        Create a migration for the session database table
 ?[33mstorage?[39m
  ?[32mstorage:link?[39m         Create a symbolic link from "public/storage" to "storage/app/public"
 ?[33mvendor?[39m
  ?[32mvendor:publish?[39m       Publish any publishable assets from vendor packages
 ?[33mview?[39m
  ?[32mview:cache?[39m           Compile all of the application's Blade templates
  ?[32mview:clear?[39m           Clear all compiled view files
```

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.88GB (5.09GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.0
react-pure-to-class-vscode|ang|1.1.4
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.8
vscode-new-file|dku|4.0.2
gitlens|eam|8.2.1
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
php-debug|fel|1.12.2
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.15
vscode-php-snippets|jar|0.0.9
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.1.1
generate-react-component|jos|0.2.1
vscode-styled-components|jpo|0.0.17
graphql-for-vscode|kum|1.10.0
php-namespace-resolver|Meh|1.0.5
azure-account|ms-|0.4.0
node-debug2|ms-|1.19.0
php-docblocker|nei|1.6.0
laravel-blade|one|1.18.0
vscode-react-native-storybooks|Ort|2.5.1
vscode-docker|Pet|0.0.26
material-icon-theme|PKi|3.3.0
laravel-artisan|rya|0.0.17
code-settings-sync|Sha|2.9.0
addDocComments|ste|0.0.8
code-spell-checker|str|1.6.6
theshukran-react-utils|the|1.0.2
vscode-react-native|vsm|0.6.6
vscode-meteor|vuh|0.1.1
quokka-vscode|Wal|1.0.117
wallaby-vscode|Wal|1.0.81
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.6.2
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|2.0.0

</details>

**Comment by Tyriar** [comment]
git bash has some issues related to winpty, these are being tracked in https://github.com/Microsoft/vscode/issues/45693
