### ISSUE TITLE
Error count is not showing up in the status bar when building TypeScript node.js project.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4768]
- VSCode Version: 0.10.12-alpha
- OS Version: WIndows10

Steps to Reproduce:
1. Create a TypeScript->Node.js->BlankConsoleApp in Visual Studio.
2. Launch VSCode and open project folder.
3. Configure tasks.json by selecting typescript setting.
4. Keep the default setting for tasks.json and compile the project with: CTRL+SHIFT+B.
5. Verify error message in the output window and status bar.

Actual: Status bar is showing 0 error.
![image](https://cloud.githubusercontent.com/assets/17735796/14121212/5489b804-f5ab-11e5-82a3-b9130e76bb76.png)

**Comment by dbaeumer** [comment]
There aren't any compile errors reported from the task that's why the count is still 0. The error comes from starting the compiler. If this happens we open the console. In your example you are simply missing the tsconfig.json file.
