### ISSUE TITLE
Slow performance when opening binary file in UTF-16LE encoding

### ISSUE THREAD

**Issue by NN---** [microsoft/vscode#47683]
Use VSCode 1.23
Open any dll file ~400KiB.
Continue with opening it
Reload it with UTF-16LE encoding.
Cursor navigation is very slow.

**Comment by bpasero** [comment]
@NN--- can you attach the file?

**Comment by NN---** [comment]
Just open any dll file with encoding UTF-16LE.
For instance download and extract here: https://www.nuget.org/api/v2/package/DotNetZip/1.10.1
Scrolling file is slow.

**Comment by rebornix** [comment]
Tracked in https://github.com/microsoft/vscode/issues/62430 .
