### ISSUE TITLE
Is it normal to have so many `Code.exe` instances?

### ISSUE THREAD

**Issue by Legends** [Microsoft/vscode#47690]
- OS Version: win10 x64

![image](https://user-images.githubusercontent.com/966368/38640974-184a2a52-3dd6-11e8-9143-818717f6a542.png)

I restarted my laptop and opened a single instance of VsCode.
My laptop fan was working like hell,so I checkout task manager, unfortunately cpu usage dropped to zero before I could make the screenshot...

**Is it normal to have so many `Code.exe` instances?**

![image](https://user-images.githubusercontent.com/966368/38640949-057661de-3dd6-11e8-8410-7df860ab4eb0.png)

**Comment by joaomoreno** [comment]
Can you use Process Hacker to list the processes, show the `Command Line` column and show me a screenshot of that?

**Comment by Legends** [comment]
![image](https://user-images.githubusercontent.com/966368/38665546-ee30da6a-3e3c-11e8-89c4-cfb6cf0e7eba.png)

**Comment by joaomoreno** [comment]
Yeah... unfortunately that's expected behaviour.

**Comment by Legends** [comment]
Thanks!

**Comment by jasonpezzimenti** [comment]
Why is this the case? (just curious)
