### ISSUE TITLE
Autocomplete is inserting selection after typing period

### ISSUE THREAD

**Issue by cperryk** [Microsoft/vscode#47696]
Autocomplete is inserting the selected suggestion after the user types a period. This is not mentioned in the [User Guide](https://code.visualstudio.com/docs/editor/intellisense), which says `Pressing Tab or Enter will insert the selected member.`, and there appears to me to be no clear way to disable this via the keymap. I suspect this is a behavior that some users may expect, but it would be nice if there was some way to disable it, as it makes for a frustrating experience to type out property names that Intellisense is _not_ suggesting.

- VSCode Version: 1.22.1
- OS Version: macOS 10.13.1
- Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Create a Javascript file `test.js`
2. Type `window`
3. Type `.`

Because the first suggestion is `addEventListener`, the result will be `window.addEventListener`.

**Comment by cperryk** [comment]
Similar issue: https://github.com/Microsoft/vscode/issues/6913

Unfortunately, I don't see any keybinding in the default keybindings that attaches `acceptSelectedSuggestion` to `"."` and adding the following to my custom key bindings no longer appears to disable this behavior:

```
{
        "key": ".",
        "command": "-acceptSelectedSuggestion"
}
```

**Comment by mjbvz** [comment]
JavaScript and TypeScript treat `.` as a commit character that accepts the current suggestion. This helps you write dot accessors more quickly.

To disable this behavior, set:

```json
  "editor.acceptSuggestionOnCommitCharacter": false
```
