### ISSUE TITLE
VS Code debugger doesn't exit after program run with Nativescript

### ISSUE THREAD

**Issue by djom20** [Microsoft/vscode#47694]
Hi VSCode Team,

Currently I'm working with NativeScript, when I'm debugging the application and I get any error either in the code or any service, the debugger show me the track and doesn't exit after this.

In other case if I close the application on my Android phone, so the debugger try to close the task but can't do it and doesn't exit after this.

![image](https://user-images.githubusercontent.com/1834808/38641572-108b2e6c-3d9d-11e8-9867-eb6c7114a589.png)

So I need to close the VS Code to run again the debugger, because in this state doesn't allow me stop it or re-start it.

Details:
- VSCode Version: 1.22.1
- OS Version: MacOX High Sierra

**Comment by weinand** [comment]
Please file this issue against the NativeScript extension.
