### ISSUE TITLE
Tab is incorrectly completing snippets

### ISSUE THREAD

**Issue by joncalhoun** [Microsoft/vscode#47692]
Issue Type: <b>Bug</b>

In my settings I have `"editor.tabCompletion": false,`, yet despite this setting tab is expanding all snippets. As far as I can tell this started occurring in the March build.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
minify|Hoo|0.3.0
output-colorizer|IBM|0.1.2
material-icon-theme|PKi|3.3.0
vscode-docker|Pet|0.0.26
code-settings-sync|Sha|2.9.0
sort-lines|Tyr|1.6.0
html-css-class-completion|Zig|1.17.1
better-toml|bun|0.3.2
gotemplate|cas|0.2.0
markdown-table-prettify|dar|2.0.0
githistory|don|0.4.0
prettier-vscode|esb|1.2.2
auto-rename-tag|for|0.0.15
fontsize-shortcuts|fos|1.4.0
rest-client|hum|0.18.1
diff-tool|jin|0.0.1
wordcounter|kir|1.2.2
Go|luk|0.6.78
sublime-keybindings|ms-|3.0.3
color-highlight|nau|2.3.0
vscode-code-outline|pat|0.1.0
gitlink|qez|0.4.2
quicktype|qui|10.0.24
vscode-icons|rob|7.22.0
iferrblocks|rst|1.1.1
gi|rub|0.2.11
code-spell-checker|str|1.6.6
gotimeformat|v4r|1.0.1
change-case|wma|1.0.0

(9 theme extensions excluded)

</details>

**Comment by joncalhoun** [comment]
I'm not really sure why this feels sudden. I don't recall running into this issue before, but it appears to be repeatable in 1.21 as well so it isn't likely that the most recent release caused the issue.

After some digging it looks like disabling the `acceptSelectedSuggestion` and `insertSnippet` keyboard shortcuts that were mapped to tab fixed the issue, but I'm not 100% sure which of these does what exactly.

**Comment by ramya-rao-a** [comment]
@joncalhoun 
- Does this happen only in certain languages or all file types?
- Do you have quick suggestions feature disabled or enabled by customizing the `editor.quickSuggestions` setting?
- Just before you see this issue, is there a suggestion/auto-completion list open?

**Comment by joncalhoun** [comment]
- I only tested Go and haven't had a chance to test anything else.
- `editor.quickSuggestions` are all defaults
- Yes, there is a list open.

**Comment by ramya-rao-a** [comment]
- `editor.tabCompletion` only controls the expansion of snippets by pressing tab in the absence of the suggestion/auto-completion list
- When suggestion/auto-completion list is open, pressing tab or enter, chooses the pre-selected item from the list.

What is your exact scenario? Do you not want snippets to show up in the completion list? Or you want the other items in the list to appear before the snippets?
