### ISSUE TITLE
box-shadow on Preferences and Keyboard Shortcuts doesn't match theme

### ISSUE THREAD

**Issue by djrenren** [Microsoft/vscode#47693]
Version: 1.22.1
Platform: macOS

It's odd that Preferences and Keyboard Shortcuts utilize a box-shadow between their editors when this is not the behavior elsewhere. It seems the divider should match the styling used on an editor split.

Editor Split:
![screen shot 2018-04-11 at 1 41 03 pm](https://user-images.githubusercontent.com/634666/38642278-72efce0a-3d8e-11e8-8d04-c985c54a27b4.png)

Preferences:
![screen shot 2018-04-11 at 1 39 02 pm](https://user-images.githubusercontent.com/634666/38642285-79419d74-3d8e-11e8-8139-cb555ee516aa.png)

Expected Behavior:
![screen shot 2018-04-11 at 1 40 05 pm](https://user-images.githubusercontent.com/634666/38642291-8017e6d0-3d8e-11e8-85db-958aa3fde101.png)

**Comment by shobhitchittora** [comment]
@sandy081 I want to use `Themable` to use `getColor` and get `EDITOR_GROUP_BORDER` out of it. 

How can I do that as in the class `Widget` is already extended ? 

https://github.com/Microsoft/vscode/blob/3a24b12179474e2b32b4fa6ee24a245c7c0044a3/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L736

**Comment by sandy081** [comment]
@aeschli Can you please help in answering above question?

**Comment by aeschli** [comment]
@shobhitchittora No `Themable` needed. Check out https://github.com/Microsoft/vscode/blob/3a24b12179474e2b32b4fa6ee24a245c7c0044a3/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L795,

**Comment by shobhitchittora** [comment]
Hey @aeschli ! Thanks for the pointer. But the issue is that as the solution to the problem I want to do something like - 

```
this.editablePreferencesEditorContainer.style.borderLeft = `1px solid {borderColorFromTheme}`;
```

I think the border color should change when the theme change. Is it correct ?

**Comment by aeschli** [comment]
Yes, that's what the code I pointed to does for you.
`attachStylerCallback` takes a map of colors and a function that is called every time one of the colors changes. -> Add your color there and add the code to the function.

**Comment by sandy081** [comment]
Closing this in favour of new settings editor.
