### ISSUE TITLE
"Paste" of code ignoring spaces and tabs

### ISSUE THREAD

**Issue by user3323** [microsoft/vscode#47698]
- VSCode Version: 1.23.0-ins
- OS Version: win7x64

If my line is quite long, and it's gonna be much more longer because of adding some methods - I want to break a line for each of method and make some spaces (tabs) ...

![ignoring tabs](https://user-images.githubusercontent.com/24613274/38644508-665bfea6-3de9-11e8-9d22-76962f78fae1.gif)

... but VS Code ignores all spaces and tabs, and moves pasted code in the straight line with the overhead code.

**Comment by user3323** [comment]
@alexandrudima , it looks like setting `"editor.autoIndent"`, when you test by "pasting" only one line. But try more.

And `"editor.autoIndent"` actually is not about "Paste" thing, it's about moving lines up and down, between different blocks:

`"editor.autoIndent": true`:
![autoindent - true](https://user-images.githubusercontent.com/24613274/38758724-077c65ea-3f7b-11e8-9230-93c4354e3015.gif)

`"editor.autoIndent": false`:
![autoindent - false](https://user-images.githubusercontent.com/24613274/38758760-3536bcd8-3f7b-11e8-96e0-bd8af2fd4a1c.gif)

--------------------------------------

following examples recorded with `"editor.autoIndent": false`

"Paste" of column-grouped methods:
![paste methods - with tab](https://user-images.githubusercontent.com/24613274/38759102-d72f4e82-3f7c-11e8-991d-94624012c13c.gif)

"Paste" of tree-like numbers:
![paste numbers](https://user-images.githubusercontent.com/24613274/38759693-d5db8a8e-3f7f-11e8-8a23-0d9fb49e6f22.gif)

Do you really think, that every time, when the user is "pasting" that kind of blocks, also should correct wrong behavior of VS Code by infinite pressing "Tab" key on these 2-nd, 3-rd, and all other... lines?

**Comment by alexandrudima** [comment]
@user3323 `editor.autoIndent` runs auto-indentation when moving lines and when pasting. There is a single flag to turn it on or off for both features. I will let you discuss now with @rebornix who implemented and maintains this feature 👍

**Comment by rebornix** [comment]
@user3323 thank you for listing all the scenarios above.

The auto indentation feature is implemented by regex based indentation rules together with some heuristics, that means it is not really semantic or aware of users' intention. Also it doesn't support multi code style. Considering how it is implemented, it's never going to be perfect so for now we recommend you to use a formatter and turn on `editor.formatOnPaste` and `editor.formatOnSave` if you want a consistent experience when typing, moving lines or pasting.
