### ISSUE TITLE
git.path in user settings

### ISSUE THREAD

**Issue by xied75** [Microsoft/vscode#477]
I have portable git on my Windows 10. In VS Code you can set user settings for this section:

```
	//-------- Git configuration --------

	// Is git enabled
	"git.enabled": true,

	// Path to the git executable
	"git.path": null,

	// Whether auto fetching is enabled.
	"git.autofetch": true,
```

So I set "git.path": "c:\tools\git\bin" and restart, it still can't find git install.

Later I set System Env Path to include git, then it's happy; seems setting above doesn't really change anything?

Best,

Dong

**Comment by joaomoreno** [comment]
`git.path` should contain the *path to the git executable*: `git.exe`. Not its parent directory.

**Comment by xied75** [comment]
@joaomoreno You are absolutely right. In case others got same misunderstanding, this should be:

```
// Path to the git executable
    "git.path": "c:\tools\git\bin\git.exe"

```

**Comment by joaomoreno** [comment]
:+1:
