### ISSUE TITLE
CodeLens at top of file keeps getting scrolled out of sight (regression in 1.22.1 from 1.21.1)

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#47703]
Issue Type: <b>Bug</b>

1) Install from extension VSIX from https://azcode.blob.core.windows.net/vscode-cosmosdb/saw/codelens/1414/vscode-cosmosdb-0.6.0.vsix
2) In explorer, open "Azure Cosmos DB" and click on the "New Mongo Scrapbook" icon in its titlebar
!) the "Connect to a database" CodeLens at the top is completely hidden
3) Scroll it into view
4) Type something
!) it hides again
6) Scroll it into view
7) Delete the line you typed in #4 and press ENTER
!) it hides again

etc.

NOTE: This also repros with other extensions, e.g. donjayamanne.jupyter

This started in 1.22.1, does not repro in 1.21.1.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31230 @ 3.20GHz (4 x 3193)|
|Memory (System)|15.96GB (6.83GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
mongogo|bag|0.1.2
regex|chr|0.1.0
vscode-markdownlint|Dav|0.14.1
githistory|don|0.4.0
tslint|eg2|1.0.28
vscode-bump|fab|1.4.1
docthis|joe|0.6.0
vscode-antlr4|mik|2.0.2
azure-account|ms-|0.4.0
csharp|ms-|1.14.0
azurerm-vscode-tools|msa|0.4.0
vscode-versionlens|pfl|0.20.0
yo|sam|0.9.3
extension-api|spy|0.2.0
python|tht|0.2.3
code-lens-roundup|wad|1.0.0

</details>

**Comment by StephenWeatherford** [comment]
![1 22 1 b](https://user-images.githubusercontent.com/6913354/38649231-460a8da0-3daa-11e8-87f1-53f9e204a2c7.gif)

**Comment by jrieken** [comment]
@alexandrudima Did something change here?

**Comment by Jarrio** [comment]
Not sure if this is related, but in the current version of vscode this also happens to me: 
![gif](https://user-images.githubusercontent.com/748557/38687597-fe62de1a-3e6e-11e8-8044-a05a1f24332e.gif)

**Comment by alexandrudima** [comment]
@Jarrio Can you please create a separate issue where you can maybe provide in textual form the typescript file which would reproduce the issue.

**Comment by alexandrudima** [comment]
Yes, 7a3204ce57da60afba584629a801c897608329e1 which changes the revealing strategy to maintain/reveal the top most line in the viewport when code lens change (it used to be the centered line in the viewport).

We can bring up the check that if the original `scrollTop` is `0`, then don't do anything.

**Comment by Jarrio** [comment]
@alexandrudima I am actually using a language called Haxe, is this a bug with the language extension or vscode?

**Comment by StephenWeatherford** [comment]
Works in Insiders, thanks!
