### ISSUE TITLE
Built-in TS support incorrectly reporting problems on fetch headers.set()

### ISSUE THREAD

**Issue by nickdepinet** [Microsoft/vscode#47701]
Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T02:26:57.615Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS: windows 10
Steps to Reproduce:

I have a typescript project using the es6 fetch apis. In certain files I use the following:

![image](https://user-images.githubusercontent.com/2041026/38647142-b0c2cff0-3d9f-11e8-8c80-c10eee27ca8c.png)

The code builds and runs correctly, but vscode reports problems in the files

![image](https://user-images.githubusercontent.com/2041026/38647251-231f83ea-3da0-11e8-94d0-4fdfb020b248.png)

Digging down in it appears that code is only checking the first possible type on HeadersInit:

![image](https://user-images.githubusercontent.com/2041026/38647308-6f5e38e6-3da0-11e8-82b9-f49fc3078039.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23383
