### ISSUE TITLE
Fuzzy search to open file doesn't show most relevant suggestion first

### ISSUE THREAD

**Issue by andersekdahl** [Microsoft/vscode#4770]
- VSCode Version: 0.10.11
- OS Version: Windows 8.1

![fuzzy](https://cloud.githubusercontent.com/assets/163637/14121605/7c85ea38-f5f8-11e5-8d02-cd2d1bd2f297.png)
As you see in the image, I've searched for `overlay/index` but the file I'm looking for is not the first suggestion even if there is only one file whose path fully matches what I've written. Changing `/` to `\` doesn't seem to matter.

Both Atom and Sublime have really great implementations of this, would be great to have it in VS Code as well.

**Comment by bpasero** [comment]
@andersekdahl I would be interested in getting access to the workspace for me to reproduce this, if possible?

**Comment by andersekdahl** [comment]
I don't think that possible unfortunately. I'll see if I can create an isolated workspace to reproduce it and share that.

**Comment by bpasero** [comment]
@andersekdahl thanks. I just pushed a fix for our scorer and was wondering if it fixes this issue too. That would help me to verify quickly.

**Comment by andersekdahl** [comment]
I can't seem to reproduce it in another workspace. Can I get access to a build with your fix to test if it solves the issue?

**Comment by andersekdahl** [comment]
Is it this commit 914716033fb45fd437b89008bad1ecd0b5a38bf8? Building from source on that commit now.

**Comment by bpasero** [comment]
@andersekdahl yes, that one will boost scores higher for consecutive matches. I would assume "Overlay" to be #1 after that change.

**Comment by andersekdahl** [comment]
Can't build from source unfortunately, I have VS 2015 but I'm missing `cl.exe` and don't have a VS setup file to run to install it. Could you comment on this issue when your commit is in a public release?

**Comment by bpasero** [comment]
@andersekdahl building a version of it now that I can share to you.

**Comment by bpasero** [comment]
@andersekdahl try with https://az764295.vo.msecnd.net/alpha/e261525aad152779f5fda7c253a0f62d92a529ff/VSCodeSetup-alpha.exe

**Comment by andersekdahl** [comment]
That seems to fix it, thanks!

There are still some other things though. Typing `overlayindex` (without slash) gives me the same behaviour as the image I posted. And searching for just `overlay` gives me matches for two files named `overlay.xxx` but no match at all for files in the folder `Overlay`. The search seems to heavily promote search hits in file names and not the paths.

**Comment by bpasero** [comment]
@andersekdahl that is totally true yeah. actually I am running the scorer first over the file name and then over the file path to naturally promote file matches over path matches.

**Comment by bpasero** [comment]
@andersekdahl I am still wondering why you would not get any match in "overlay" though for files that live in that folder. 

E.g. in this workspace I have a folder "lib" and can search for files within:

![image](https://cloud.githubusercontent.com/assets/900690/14139673/c0331892-f674-11e5-8708-82e17b4ecd13.png)

**Comment by andersekdahl** [comment]
Yeah it's hard to tell. Like I said, I couldn't reproduce it in a test workspace. Could it have something to do with the size of the workspace?

**Comment by bpasero** [comment]
@andersekdahl good point, there is an actual limit of results in quick open.

**Comment by bpasero** [comment]
Marking as closed, given the initial report seems fixed.

**Comment by andersekdahl** [comment]
Fine by me, I'll see if I can create test cases for the other things I mentioned and open new issues if I can.

**Comment by andersekdahl** [comment]
Thanks for the quick replies btw!

**Comment by bpasero** [comment]
np :+1:
