### ISSUE TITLE
How to debug VS Code debugger

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#47705]
I'd like to diagnose an issue we're having with the debugger of the [Python Extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python)

For some reason the output sent from the output events are not being displayed in the console window (when run in non-debug mode). I've wanted to diagnose few similar issues in the past, however never managed to get VS Code working properly. This is something I've managed in the past. Either something has changed or I have missed some crucial configuration step in VS Code.

I've followed the instructions on page https://github.com/Microsoft/vscode/wiki/How-to-Contribute, but am unable to debug the debugger services (src/vs/workbench/parts/debug/electron-browser/debugService.ts)

Any help here would be appreciated.

**Comment by DonJayamanne** [comment]
Oh one more thing, I'm getting the following message when attempting to launch an extension from within the debug version of VS Code:
<img width="811" alt="screen shot 2018-04-11 at 6 35 29 pm" src="https://user-images.githubusercontent.com/1948812/38651638-302ab548-3db7-11e8-87b8-9dd2cdf84e5a.png">

**Comment by roblourens** [comment]
To debug an extension with Code - OSS, you need to change the runtimeExecutable in that launch config to the path to code.sh

**Comment by DonJayamanne** [comment]
@roblourens 
Thanks, How about debugging vscode itsef? (In particular the debug service)

**Comment by roblourens** [comment]
The repo has a launch.json, check out the "Launch VS Code" launch config.

**Comment by DonJayamanne** [comment]
I have tried that, but vscode just hangs and does absolutely nothing.

**Comment by roblourens** [comment]
The window that you are debugging hangs, or the window you are launching from?

**Comment by weinand** [comment]
@DonJayamanne when running VS Code from source and you want to debug an extension, you have to modify the extension launch config in the following way to avoid the generic Electron message from above. Add the path to your VS Code workspace folder as the first argument to the "args" attribute:

```js
		{
			"type": "extensionHost",
			"request": "launch",
			"name": "Extension",
			"runtimeExecutable": "${execPath}",
			"args": [
				"/Users/JohnDoe/src/vscode",
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [ "${workspaceFolder}/out/**/*.js" ]
		},
```

**Comment by weinand** [comment]
Since I was tired of explaining this "magic" with the additional VS Code workspace path argument every second day, @bpasero and I looked into this and came up with the following fix:

If VS Code runs out of source, node-debug2 automatically adds the path to the VS Code workspace as the first argument to the argument list (iff the user hasn't done that already).
