### ISSUE TITLE
Version 1.22.1 (1.22.1) just updated but .js folding no longer works

### ISSUE THREAD

**Issue by macasas** [Microsoft/vscode#47700]
- VSCode Version: Version 1.22.1 (1.22.1)
- OS Version: OSX 10.12.6 Sierra

Steps to Reproduce:

Auto updated to 1.22.1
1.Open .js file
2.Try to click folding + - symbols

Does this issue occur when all extensions are disabled?: Yes

Does not fold correctly.

Works in markdown, but not in .js file

CMD-K-J to fully unfold everything
![screen shot 2018-04-12 at 00 26 06](https://user-images.githubusercontent.com/910082/38646403-1b6da332-3de8-11e8-8dc7-83aedce3b9cb.png)

Watch how when I collapse 426, it collapses to 431, 1 code line after next else statement
![screen shot 2018-04-12 at 00 26 20](https://user-images.githubusercontent.com/910082/38646406-200dee9c-3de8-11e8-8e6a-a73a5d984d93.png)

This is not being caused by debugging line containing { }, does the same thing if expanded into different lines.

Only just started doing this after auto update and app restart. Was working fine before.

**Comment by mjbvz** [comment]
Please share the source code for a minimal example that demonstrates this problem, not just screenshots

**Comment by macasas** [comment]
Here is the section I am showing
```
            } else if (line.indexOf("# Listening") >= 0) {
                if (debugging) { console.log("## Listening"); }
                currentSection = "Listening";

            } else if (line.indexOf("# Speaking") >= 0) {
                if (debugging) { console.log("## Speaking"); }
                currentSection = "Speaking";

            } else if (line.indexOf("# Conversations") >= 0) {
                if (debugging) { console.log("## Conversations"); }
                currentSection = "Conversations";
```

Here is the same section modified to be correct standing on its own.
```
            if (line.indexOf("# Listening") >= 0) {
                if (debugging) { console.log("## Listening"); }
                currentSection = "Listening";

            } else if (line.indexOf("# Speaking") >= 0) {
                if (debugging) { console.log("## Speaking"); }
                currentSection = "Speaking";

            } else if (line.indexOf("# Conversations") >= 0) {
                if (debugging) { console.log("## Conversations"); }
                currentSection = "Conversations";
            }
```

Its doing it on every indentation, not just if else

Is that what you mean?

**Comment by mjbvz** [comment]
Thanks! I believe this has been fixed in vscode insiders:

<img width="580" alt="screen shot 2018-04-12 at 8 45 44 am" src="https://user-images.githubusercontent.com/12821956/38688459-005d8a3a-3e2e-11e8-90ff-0d14b5784917.png">
