### ISSUE TITLE
After I stop a task with shared panel presentation, it can't run the task again because it throws an error -> Terminal with ID 1 does not exist (has it already been disposed?)

### ISSUE THREAD

**Issue by Immac** [Microsoft/vscode#47707]
Issue Type: <b>Bug</b>

After I stop a task with which has  

```
"presentation": {
                "panel": "new"
            }, 
```

I can't run the task again because it throws an error -> Terminal with ID 1 does not exist (has it already been disposed?)
Terminal with ID 1 does not exist (has it already been disposed?)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|Memory (System)|7.98GB (2.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.9.3
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
cmake|twx|0.0.17

</details>

**Comment by dbaeumer** [comment]
This works for me using the following task

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo Hello",
            "presentation": {
                "panel": "new"
            }
        }
    ]
}
```

Any additional steps on how to reproduce this?

**Comment by Immac** [comment]
Actually it's when the panel is shared, I copied the wrong task, my bad.

**Comment by dbaeumer** [comment]
This works for me as well for "shared" tasks. Any additional steps you can provide. Best would be a GitHub repository that I can clone that demos the problem.
