### ISSUE TITLE
Can't set escape as keybinding for close panel

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#47710]
Can't set `escape` for close panel because pressing `Escpae` will close the keybindingWidget. By the way, why these commands have two keybindings?
![keybindings](https://user-images.githubusercontent.com/24318019/38654933-4c9eda28-3e44-11e8-81ba-69bd217bcd87.png)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|7.89GB (2.46GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
svn-scm|joh|1.29.0
debugger-for-chrome|msj|4.3.0
vscode-icons|rob|7.22.0

</details>

**Comment by sutt** [comment]
I think you can work around this.
At the top of Keyboard Shortcuts view there should be a line that say: 'For advanced customizations open and edit keybindings.json'. Click this. Now you'll get to json's to open: 'Default Keybindings' and 'keybindings.json'.
The keybindings.json is where you'll place your esc binding. It shows a hover dialog which says 'Define Keybinding (ctrl+k ctrl+k)' and you're right that after bringing up the key binding dialopg, with ctrl+k command, simply pushing esc will exit this dialog and won't create a element. So try: "shift+escape". Then hit enter. This will create the following test in keybindings.json:
{
    "key": "shift+escape",
    "command": "commandId",
    "when": "editorTextFocus"
},
Now, just text edit and remove the 'shift+' text, and add the command you want. This will fire when you press esc.

**Comment by shizengzhou** [comment]
@sutt Thank you.

**Comment by alexandrudima** [comment]
Yes, for binding commands which involve `escape` or `enter`, you need to edit the `keybindings.json` file directly. Sorry about that, but we had to keep those for the most common use-case and, to be fair, they are pretty rarely edited by users.

As to the second question, we also bind `shift+escape` for everything for Screen Reader software. In some Screen Reader software, Escape is something that influences the way the Screen Reader software works (e.g. it goes from editing mode to reading mode) and so we are shipping with Shift+Escape for everything too such that those folks using Screen Reader software can use Shift+Escape.
