### ISSUE TITLE
[html] code completion very slow on long HTML document.

### ISSUE THREAD

**Issue by luanft** [Microsoft/vscode#47712]
Issue Type: <b>Performance Issue</b>

I'm writing a long html document(8533 lines, almost it is javascript code). I see that the suggestion box for javascript code shows very slow(about 10s). But it work well on short documents.
Does anyway to speed it up?

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.43GB (2.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    98	 16748	code main
    0	   204	  2560	   window (view_design_detail_simple.html - python - Visual Studio Code)
    0	    12	 13440	     watcherService 
    0	     5	 11376	       console-window-host (Windows internal process)
    0	     9	 13668	     electron-crash-reporter
    0	    63	 18076	     extensionHost
    0	   122	  5304	       electron_node htmlServerMain.js 
    0	    27	  9040	       electron_node electronForkStart.js tsserver.js 
    1	    20	 16448	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    1	    95	  7208	   gpu-process
    0	    68	  8324	   powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
    0	     8	 12984	     console-window-host (Windows internal process)
    1	    74	 10740	   shared-process
    0	    48	 16192	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (view_design_detail_simple.html - python - Visual Studio Code)
|    Folder (python): 3491 files
|      File types: js(810) gif(783) png(364) pyc(358) py(278) html(229)
|                  css(185) scss(55) less(55) php(54)
|      Conf files: package.json(3) settings.json(1);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1

</details>

**Comment by ramya-rao-a** [comment]
This is most likely due to the time taken by the html language server in providing completions

**Comment by luanft** [comment]
Hi @ramya-rao-a,
There is any solution for this problem?

**Comment by aeschli** [comment]
@luanft Any chance you can share that document?

**Comment by luanft** [comment]
Yes. Please find the attachment. I hope it is useful
[view_design_detail_simple.zip](https://github.com/Microsoft/vscode/files/1906135/view_design_detail_simple.zip)

**Comment by aeschli** [comment]
@luanft Sorry for the delayed answer. I tried your code sample but don't don't see any slowness. Is it everywhere in the code, or at some at a particular location?
