### ISSUE TITLE
Emmet completions shouldnt show up inside if conditions

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#47719]
@ramya-rao-a 

Issue Type: <b>Bug</b>

Set
```
"emmet.includeLanguages": {
        "javascript": "javascriptreact"
 }
```
If there is `!`, there is a wrong item in the suggestions.
![suggestion1](https://user-images.githubusercontent.com/24318019/38661123-59029f02-3e62-11e8-8c75-41f99cdc1729.png)
![suggestion2](https://user-images.githubusercontent.com/24318019/38661127-5e170b68-3e62-11e8-8881-a7e8da4e2221.png)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|7.89GB (2.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
svn-scm|joh|1.29.0
debugger-for-chrome|msj|4.3.0
vscode-icons|rob|7.22.0

</details>

**Comment by ramya-rao-a** [comment]
Good catch, thanks for reporting. Will push a fix soon

**Comment by shizengzhou** [comment]
![emmet](https://user-images.githubusercontent.com/24318019/38981944-291cd5c8-43f3-11e8-9885-31efb5485def.png)
What's this?

**Comment by ramya-rao-a** [comment]
You can get the fix in tomorrow's [Insiders](https://code.visualstudio.com/insiders) build
