### ISSUE TITLE
JavaScript syntax highlighting not working

### ISSUE THREAD

**Issue by patridge** [Microsoft/vscode#47713]
- VSCode Version: 1.22.1
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Follow along with these [vscode+React tutorial steps](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial)
2. After `create-react-app my-app` step, open **index.js**

I was expecting syntax highlighting matching the [tutorial screenshots](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_syntax-highlighting-and-bracket-matching)…

![](https://code.visualstudio.com/assets/docs/nodejs/reactjs/bracket-matching.png)

…but only `import`, `from`, and strings are getting syntax highlighting.

<img width="510" alt="screen shot 2018-04-11 at 22 00 05" src="https://user-images.githubusercontent.com/713665/38655768-b807cdc2-3dd3-11e8-815a-f3ed3c6db90b.png">

The same applies to JavaScript code in the generated **App.test.js** file and **App.js** (though maybe React-flavored JS requires a special extension).

Does this issue occur when all extensions are disabled (C#, Cake)?: Yes

**Comment by mjbvz** [comment]
The screenshot is the `Dark+` builtin theme. You are using the regular `Dark` one

**Comment by patridge** [comment]
That did it. Thank you, @mjbvz! I didn't realize the theme could make that much impact on things.

(Now I just need to investigate why IntelliSense isn't working as shown in the next `React.createClass` step, but that's a different issue.)
