### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by venkatrjv** [Microsoft/vscode#47716]
Issue Type: <b>Bug</b>

All plugins are not working including intellisense.. :-(

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:27:19.487Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.81GB (3.53GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.30
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
beautify|Hoo|1.3.0
angular2-switcher|inf|0.1.6
vscode-angular2-emmet|jak|2.0.3
docthis|joe|0.6.0
Angular2|joh|2.16.1
comment|kar|5.0.2
auto-comment-blocks|kev|1.0.1
Angular-BeastCode|Mik|6.0.10
python|ms-|2018.3.1
debugger-for-chrome|msj|4.3.0
vscode-docker|Pet|0.0.26
vscode-icons|rob|7.22.0
addDocComments|ste|0.0.8
code-spell-checker|str|1.6.6

</details>

**Comment by joaomoreno** [comment]
Can you provide more details? Pick a language, like TypeScript. Do you get Intellisense there?

**Comment by venkatrjv** [comment]
On a heavy load . Intellisense is not working.
And in some unknown cases.

**Comment by joaomoreno** [comment]
I'm trying to get you to give me more details. Please provide as many details as you can.

What language, specifically? Can you send me a screen recording of the behaviour?

**Comment by venkatrjv** [comment]
I am using TypeScript,Html

**Comment by joaomoreno** [comment]
OK let's focus on TypeScript.

**Comment by mjbvz** [comment]
Does this issue reproduce if you disable all extensions? Please share some example code and repo steps.
