### ISSUE TITLE
can't breakpoint on "if (xxxx)" before

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#47718]
- VSCode Version:1.22
- OS Version:macos 10.13.4

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/3990411/38661291-e7bb253e-3e62-11e8-9749-961e310ce28c.png)

i can't create a breakpoint before if ,please help me .

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by zhiqiang21** [comment]
this is javascript

when i add breakpoint  then click 'F5' start debug 。i hover  breakpoint ,it.s show this  then the breakpoint miss.
 
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/3990411/38665398-e14fa894-3e6e-11e8-94e4-090c09239f3b.png">

**Comment by zhiqiang21** [comment]
when i config .vscode/launch.json    `sourceMaps: false `  when i start program then breakpoint not miss , but program not stop on this .  so i set `sourceMaps: true ` the problem is still.

**I write nodejs  not use typescript. please help me .**

**Comment by zhiqiang21** [comment]
@rebornix

**Comment by roblourens** [comment]
- Are you using Babel?
- Can you share the project here?

**Comment by zhiqiang21** [comment]
i use bable compile my react directory, not compile nodejs directory. so i guess it's not effect nodejs debug.
this's my office code,  i can't share my code here. i'm so sorry.

**Comment by roblourens** [comment]
Do you have some other transpile step with sourcemaps? This problem usually happens when there are issues with sourcemaps.

**Comment by zhiqiang21** [comment]
i'm very sorry .today i find my nodejs code  use babel run . so when i debug my breakpoint will change position .

my app use these code run :

```javascript
require('babel-core/register');
require('babel-polyfill');
require('./app/index.js');
```

when i  config .babelrc config sourcemap:'inline' and  in .vscode/launch.json config  sourcemap :true .   the brekpoint will miss and position change other.

**Comment by zhiqiang21** [comment]
when i add config to my `.babelrc` this  . then debug is good.

```
  "sourceMaps": "inline",
 // Retain line numbers. This will lead to wacky code but is handy for scenarios where you can't use source maps. NOTE: This will obviously not retain the columns.
  "retainLines": true
```

**Comment by zhiqiang21** [comment]
although i config  sourcemap and retainlines in my .baberc 。I met the same problem again today。I recorded a video 。i did't know why.

https://www.dropbox.com/s/0b60hua1gctosgc/QQ20180516-162606-HD.mp4?dl=0

**Comment by roblourens** [comment]
There are some issues with babel async/await sourcemaps. There's probably nothing we can do to improve this, unless it works better in chrome devtools than vscode.
