### ISSUE TITLE
Copy lines from search result view

### ISSUE THREAD

**Issue by quentindaniel** [Microsoft/vscode#47728]
It would be usefull -at least in my case- to be able to select multiple lines and copy them from the search result, instead of having to go in each file.

For example : 
![image](https://user-images.githubusercontent.com/27276553/38666686-ced68e78-3e3f-11e8-9611-f7abeaef6ec6.png)

Not sure how to handle duplicate lines cause by multiple match. Either manualy deleting them from result view or copy them only once...

**Comment by roblourens** [comment]
This is actually implemented in the Insiders version. Please try it out!
