### ISSUE TITLE
auto formar when press save all

### ISSUE THREAD

**Issue by Razor164** [Microsoft/vscode#47723]
Issue Type: <b>Bug</b>

sometimes when i pressed ctrl+s (save all documents for me) - auto formatt work incorrect

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|Memory (System)|7.87GB (0.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
docthis|joe|0.6.0
vscode-simple-icons|Lau|1.8.2
code-beautifier|mic|2.0.3
Angular-BeastCode|Mik|6.0.10
vscode-cosmosdb|ms-|0.6.0
azure-account|ms-|0.4.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.3.0
rxjs-snippets|pko|0.0.2
sonarqube-inject|sil|2.1.0

</details>

**Comment by joaomoreno** [comment]
You can always disable format on save. If a formatter is incorrect, please narrow it down to which language. Then, file an issue on that language's project repository.
