### ISSUE TITLE
When switching branches after creating a file in one, the file still appear in the older branch

### ISSUE THREAD

**Issue by DevNicoT** [Microsoft/vscode#47729]
- VSCode Version: 1.22.1
- OS Version: Windows 10
Steps to Reproduce:

1. From branch master of your project (for example), checkout to a new branch.
2. Within that branch create a new file, let's say Test.js.
3. Now, if you switch back to master, the new file also appears there and if you make any modification, it's still there.
4. Also, if you make git status, it doesn't matter in which branch you are, you'll still get the new file under 'untracked files'.
5. Also, if you make any new modifications on a file within a certain branch, (let's say App.js in master), and now you make git status in master you'll find them and also the visual M in the explorer. And then if you checkout into the other branch and make git status in there, you also have the same changes and the explorer also reflect them as if they were done in such branch.
6. If I remove the file and/or modifications, then both the explorer and git status come back to normal (although the problem is it does so _on both branches_)

I'm not sure that's the intended behavior, and also glad to help fixing if I can in anything.
It seems like smth could be off with the branching in VSC? Appreciate any pointers! Thanks.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by DevNicoT** [comment]
Yup, checked those and it's not an exact duplicate, though some of them also seem related to branching but are not the same issue.

Also, glad to provide any other info if needed?

**Comment by DevNicoT** [comment]
To be honest, I'm not sure either if this is a bug in VSC or in Git itself. Appreciate any hint from your end. Thank you!

**Comment by joaomoreno** [comment]
That is how git works. https://git-scm.com/book/en/v2/Getting-Started-Git-Basics
