### ISSUE TITLE
Not found PHP in new version

### ISSUE THREAD

**Issue by Kobe29** [Microsoft/vscode#47721]
- VSCode Version: 1.22
- OS Version: Windows 10 (Last version)

Steps to Reproduce:

1. When I upgrade to the new version, I do not recognize any PHP file

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
- Can you explain exactly what you see?
- If you search `@builtin php` in the extensions viewlet, what do you see?
