### ISSUE TITLE
Usability: Moving files in a large structured project with drag and drop can be quite painful.

### ISSUE THREAD

**Issue by dannystaple** [Microsoft/vscode#47725]
Issue Type: <b>Feature Request</b>

When you have a large structured project - in this case a documentation project, with folders with many files, moving a file from one folder to another becomes extremely fussy with drag and drop.

Could other options like a "Move file" command be present which will move files in a way that VSCode and the Source control plugins are aware of be considered?

Moving them in the command line makes the editor think the file is gone, whereas drag and drop in the editor keeps the editor aware that it is the same file just moved.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.15063

**Comment by isidorn** [comment]
Also moving it via command line should be detected by vscode, in case it is not it seems like we are missing file events and feel free to open a new issue regarding that with exact steps.
