### ISSUE TITLE
Add extension deprecation and redirection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#4772]
Allow extensions to specify they are deprecated in their `package.json`, with an optional alternative extension(s) field. This setting can inform the user of the deprecation in-product, and if specified, potentially update to the new extension automatically without informing of the deprecation?

Related: https://github.com/Microsoft/vscode/issues/3670

**Comment by be5invis** [comment]
Any progress? I'd like to rename my extension `be5invis.julia` into `be5invis.syntax-julia`, but the old one cannot be removed.

**Comment by joaomoreno** [comment]
cc @egamma This could be an alternative for renaming.

**Comment by egamma** [comment]
@joaomoreno yes, but this would still have the statistics issue in that the download count is now accounted to 2 extensions. For a not yet popular extension this is not an issue, but for a popular one it is. So I still think we need support for this from the market place.

**Comment by joaomoreno** [comment]
@modigrv Is there any concept of deprecation?

**Comment by modigrv** [comment]
Forwarded the request to Marketplace PM

**Comment by hamenon** [comment]
@joaomoreno We don't have the concept of deprecation yet in the Marketplace. But we do intend to support it soon. The fact the extension is deprecated will be added to the extension properties. And the current plan is to not show deprecated extensions on the marketplace in searches etc, to prevent future installs. Will work with Wade on how to handle it on the client side.

**Comment by Tyriar** [comment]
@waderyan @hamenon any movement here?

**Comment by waderyan** [comment]
There has been some work here. https://github.com/Microsoft/vscode/issues/10551

**Comment by Tyriar** [comment]
Oh cool, is it planned to look into a deprecated extension automatically installing another extension that supersedes it? These are the use cases I'm aware of:

- Abandoning an extension (could also use `vsce unpublish`?)
- An extension is deprecated in favor of another publisher's (`chrisdias.vscodeEditorConfig` -> `EditorConfig.EditorConfig`)
- An extension being renamed within the same publisher (`be5invis.julia` -> `be5invis.syntax-julia`)

It's not clear after skimming https://github.com/Microsoft/vscode/issues/10551 whether users are informed  about the deprecation of they're just hidden from search.

**Comment by waderyan** [comment]
We punted on the use cases you described for now. We had to get the filter in for the search query, but should look at solving the cases you describe.

**Comment by bergmeister** [comment]
@Tyriar Are you aware of any (good) workarounds for migrating a setting to its new value (use case: functionality of a setting was split into more settings)? I am thinking
- Change user's setting and remove this custom code after a few months. Not sure how well this works in the various settings levels (user, workspace, codespace or synced) but I think an extension can change at least the user's settings
- Have a code internal redirect, which has the disadvantage that the old setting itself still has to be exposed for that.

**Comment by Jaimeloeuf** [comment]
Hello, been some time, just wanted to check what is the status of this if anyone is kind enough to give some feedback? Thanks!

**Comment by RandomFractals** [comment]
much needed with the number of deprecated extensions in vscode marketplace growing and getting in the way of search and filtering.

We need 20 upvotes for this issue to get added to the backlog and be revisited by the vscode team.

**Comment by Jaimeloeuf** [comment]
@RandomFractals seems like more then 20 upvotes already for sometime it seems but nth much from core team, this would be really good to have!

**Comment by RandomFractals** [comment]
@Jaimeloeuf well, I did my job rallying the ext. dev troops in dev community slack to get us over 20 upvotes for this to be added to backlog.

The rest is up to @eamodio & vscode team to decide on when this gets implemented and released.

There are a lot of 'deprecated' extensions in vs marketplace that just get in a way of search & other things just confusing devs trying to find good extensions to use.

**Comment by jasonwilliams** [comment]
Man do we really need this!
I need to move an old extension to a new organisation (as the former maintainer left and want to use a new name/user). But sadly I can’t do it looks like I’m going to have to duplicate it. The issue with that is the old one will still be top for probably years🙁

It also means the marketplace is mess.

**Comment by Tyriar** [comment]
FYI @isidorn, this would help get rid of the extensions with titles containing "deprecated" in searches.

**Comment by chgill-MSFT** [comment]
Thanks for the feedback everyone!

Right now the Marketplace team is engaged in an effort to completely rebuild the backend infrastructure. This will entail positive changes to organization management, extension ownership, deprecation experiences, and more.

While it's difficult to give a firm delivery date - we can expect the ability to deprecate extensions will be an outcome of this effort in the near future.

To get an idea of how this might look in the future, you can see the [nuget.org package deprecation docs](https://docs.microsoft.com/nuget/nuget-org/deprecate-packages).

To build on what @Tyriar said, the goal of deprecation would be the following:
1. Make it clear to users which packages are up-to-date and actively maintained
2. Enable publishers to suggest alterative extensions

At this time, it's still unclear how deprecation may factor into search ranking or how indicators may appear in the VS Code client - however I'll be happy to use this thread to review ideas and get community feedback 🙂

**Comment by isidorn** [comment]
Thanks for jumping in @chgill-MSFT 

Upstream issue https://github.com/microsoft/vsmarketplace/issues/23
Though this one has more details. fyi @prashantvc

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/145210509-7b30c952-0e98-4f35-bdad-c2b156d2adfd.png)

@chgill-MSFT FYI a common reason I deprecate extensions is because the functionality becomes built into core like with https://marketplace.visualstudio.com/items?itemName=Tyriar.terminal-tabs

**Comment by RandomFractals** [comment]
@Tyriar just catching up here. Where is that UI from? Is that available in vs marketplace now when updating an extension, or did you have to add the `(deprecated)` part to your extension name and republish it?

**Comment by Tyriar** [comment]
@RandomFractals from this link https://docs.microsoft.com/nuget/nuget-org/deprecate-packages mentioned in https://github.com/microsoft/vscode/issues/4772#issuecomment-988294741

**Comment by isidorn** [comment]
As @chgill-MSFT nicely explained [above](https://github.com/microsoft/vscode/issues/4772#issuecomment-988294741) the Marketplace support for deprecated extensions will not come soon. Until this is available we have decided that the information for what extension are deprecated will come internally from VS Code. Downside of this approach is that those extensions will not get rendered as deprecated by the Marketplace, upside is that all the UX work we do on the VS Code side will be reused once Marketplace starts supporting this.

So assigning to April for an initial exploration. Based on how this goes, we will now more when this lands.

In the meantime, if you have any extensions that are deprecated feel free to share them in this issue.

**Comment by jasonwilliams** [comment]
Hi @isidorn, could you clarify the scope of what you're planning to achieve internally in VSCode? Are you just focusing on showing that something is deprecated, or also handling redirection to another extension too? How do you plan to "gain" this information? is this something people will need to input? or you will be infering it somehow.

> In the meantime, if you have any extensions that are deprecated feel free to share them in this issue.

`jpoissonnier.vscode-styled-components` is deprecated and should now be `styled-components.vscode-styled-components`. It's been a hassle migrating our users. We still need to [tell users](https://github.com/styled-components/vscode-styled-components/issues/343#issuecomment-991763451) who raise issues that they're using the old version.

**Comment by isidorn** [comment]
@jasonwilliams thanks for raising this great questions. We are thinking there are two cases:
* Extension is deprecated and there is an alternative. We will look into guiding the user to the alternative extension
* Extension is deprecated but there is no alternative. Then we should just make sure the user is aware that the extension is no longer maintained

We will gain this information by working with extension authors so they let us know which extensions are deprecated.
Also I plan to manually go through a list of extensions that have not been updated in last 2 years and reaching out to their authors. If one of those extensions truly appears deprecated and the authors does not reply in a couple of weeks we might go ahead and mark it as deprecated on our own.

Hope that makes sense. I have added your extension to our list.

**Comment by isidorn** [comment]
@RandomFractals thanks for sharing your concern, we will make sure to give extension authors enough time to reply. Possibly even a whole month.
We are doing this because a lot of extensions are in a really abandoned state = so the extension authors are no longer checking their email associated with the extension. So if we had to wait on confirmation of extension authors a lot of deprecated extensions we could not mark as such.
We will of course use this approach responsibly.

**Comment by fwouts** [comment]
> In the meantime, if you have any extensions that are deprecated feel free to share them in this issue.

[zenclabs.reactpreview](https://marketplace.visualstudio.com/items?itemName=zenclabs.reactpreview) is deprecated in favour of [zenclabs.previewjs](https://marketplace.visualstudio.com/items?itemName=zenclabs.previewjs) :) Thanks!

**Comment by burkeholland** [comment]
Browser Preview is deprecated : https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview

**Comment by isidorn** [comment]
Thanks to the great work done by @sandy081 this is now done.

Try it out in VS Code insiders and let us know what you think. 
Also please comment here if there are any deprecated extensions which we did not mark as deprecated yet. Thanks!

I still plan to update our extension author docs to explain extension deprecation.

Here's an example of how this looks like:

![Screenshot 2022-05-23 at 14 02 03](https://user-images.githubusercontent.com/1926584/169815013-3a58bb64-ece9-46fd-a9e6-2c0aaa7dc753.png)

**Comment by lnicola** [comment]
@isidon small nit: that message at the bottom should probably say "Use _the_ Live Preview extension instead.".

**Comment by isidorn** [comment]
@lnicola thanks! I am not 100% convinced - but I am not a native English speaker :)
Maybe "Use Live Preview instead". So we remove "extension" part

@sandy081 what do you think?

**Comment by Tyriar** [comment]
@isidorn the current sentence sounds wrong to me but either proposal sounds natural. I'd go with `Use Live Preview instead` since "extension" is mentioned in the previous sentence already.

**Comment by mjbvz** [comment]
@isidorn Are there any plans to (gently) alert users who already have a deprecated extension installed? Right now I find it easy to miss unless you are explicitly looking for it

**Comment by isidorn** [comment]
@mjbvz yes, more details here https://github.com/microsoft/vscode/issues/150011
@Tyriar thanks, I see Sandy has pushed a change with your proposal.

**Comment by isidorn** [comment]
@RandomFractals thanks for the idea. Something to consider.
Though right now we are leaning towards having everything in the extensions viewlet / extension details scope.

**Comment by RandomFractals** [comment]
@isidorn my suggestion was mainly for the scenario @mjbvz described as many devs, us included, have and use many extensions and unless we go to extension view to review latest changes & updates, finding good up to date alternatives will be hidden. Could be another feature as you iterate on this ext. deprecation implementation later. I like the described experience so far. Thanks for taking it on!
