### ISSUE TITLE
After formatting document, previous cursor location is lost

### ISSUE THREAD

**Issue by BartolomeSintes** [Microsoft/vscode#47731]
- VSCode Version: 1.22.1
- OS Version: Windows 7

Steps to Reproduce:
1. write an unindented html document 
2. format the document using Shift+Alt+F 
3. if VSCode changes the document (adding or removing spaces, for instance), the previous location of the cursor is lost. You have to click on the document to get back the cursor.  I would say that in previous versions of VSCode the cursor remained in the same place.

Does this issue occur when all extensions are disabled?: Yes

**Comment by zfeher** [comment]
The same happens with javascript files as well. The cursor disappears and if you press up/down arrow around the saving it may jump to the end of the file which is really annoying. Here we are using prettier which worked with previos version well.

**Comment by BartolomeSintes** [comment]
It works now in VSCode 1.22.2.

**Comment by alexandrudima** [comment]
Duplicate of #47382
