### ISSUE TITLE
Undo mangles unicode characters

### ISSUE THREAD

**Issue by overengineered** [Microsoft/vscode#47733]
- VSCode Version: 1.22.1
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. Open a file containing text '👁' (with quote characters)
2. Select the first quote character
3. Press `"` - the selected character gets replaced with "'"
4. Perform undo: "'" is replaced back to ', but also the unicode eye is replaced with error character

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@rebornix Here is another case where `getLineCharCode` is broken. It looks like the problem is either in `nodeAt2` or the way it is used in `getLineCharCode`. I have pushed a temporary fix for it, but can you please take a look.

**Comment by rebornix** [comment]
My bad, `getNodeAt2` returns node near the cursor but it might be the end of the node. `getNodeAt2` should be explicit about whether returning the node ending with the index or starting with the index. For inserting content, the former is better while for getting char code, the later is a must. Created https://github.com/Microsoft/vscode/issues/48012 to track this and `getCharCode` should be tested in random tests as well.
