### ISSUE TITLE
Failed to save 'filename.jade': A system error occurred 

### ISSUE THREAD

**Issue by Yogeeshvh** [Microsoft/vscode#47736]
Failed to save 'filename.jade': A system error occurred (UNKNOWN: unknown error, open 'c:\Users\user_1\node_apps\DO\ng\views\filename.jade')
Unable to save files after performing search (Ctrl+Shift+F) and modifying contents
This is occurs very often. I stopped using vscode because this issue is really irritating  
- VSCode Version:1.22.1
- OS Version: 1709 build 16299.309

Steps to Reproduce:

1. Search whole project (Ctrl+Shift+F)
2. Make bunch of changes while navigating search results

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Does it happen randomly to different files, or just particular files?

**Comment by Yogeeshvh** [comment]
it happens randomly to different files and also for multiple projects. I had to use different editor just to save the file by copying and pasting

**Comment by bpasero** [comment]
@Yogeeshvh are you running as a different user than the files where created with, e.g. as admin?

**Comment by Yogeeshvh** [comment]
@bpasero No, I was running as same user all the time(not Admin)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Yogeeshvh** [comment]
I tried reproducing with insider builds but I couldn't, also stable build is working fine right now. I don't know what was the issue

**Comment by bpasero** [comment]
OK closing until more steps can be provided.
