### ISSUE TITLE
Word forward (Ctrl+RightArr) does not work in prompt boxes

### ISSUE THREAD

**Issue by theREALdebater** [Microsoft/vscode#47732]
Issue Type: <b>Bug</b>

With Git as VCS, type several words into commit message. Ctrl+RightArr does nothing. Same for other prompt boxes. Expect cursor to move to next word.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|Memory (System)|15.87GB (11.36GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.1
vscode-yarn|gam|1.6.0
mssql|ms-|1.3.1
csharp|ms-|1.14.0
node-debug2|ms-|1.19.0
PowerShell|ms-|1.6.0
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.3.0
vscode-react-native|vsm|0.6.6

</details>

**Comment by joaomoreno** [comment]
Can you reproduce with `--disable-extensions`?
