### ISSUE TITLE
Constant cpu usage on windows caused by electron_node typingsInstaller.js tsserver.js typesMap.js

### ISSUE THREAD

**Issue by zfeher** [Microsoft/vscode#47735]
- VSCode Version: 1.22.1
- OS Version: Windows 10 1709 16299.371

Steps to Reproduce:

This happens when I am opening our repo. I need to wait a while max 1-2 minutes and the process will be there and it will cause 10-17% constant cpu usage. My telemetry settings are turned off completely.

Opening an empty code instance doesn't produce this behavior.

The exported status: [vscode-status.txt](https://github.com/Microsoft/vscode/files/1902951/vscode-status.txt)

The command line of the process:
```
"C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/zfeher/AppData/Local/Microsoft/TypeScript/2.8 --enableTelemetry --typesMapLocation "c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js/../typesMap.json" 
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23390
