### ISSUE TITLE
Collab mode to invite friends and work on the same file together. Like Teletype for ATOM!

### ISSUE THREAD

**Issue by reyesjl** [Microsoft/vscode#47741]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by V-ed** [comment]
Take a look at Visual Studio Live Share : https://code.visualstudio.com/blogs/2017/11/15/live-share

Still in limited private preview.

**Comment by reyesjl** [comment]
Thanks!
