### ISSUE TITLE
Extension's Integrationtests fail on Travis CI since vscode release 1.21.0

### ISSUE THREAD

**Issue by HaaLeo** [Microsoft/vscode#47744]
- VSCode Version: >= 1.21.0
- OS: linux x-64

I am a contributor of the [vscode-logfile-highlighter](https://github.com/emilast/vscode-logfile-highlighter).  
Since VSCode Release 1.21.0 our Integrationtests started failing on TravisCI as can be seen in this build's log ([line 475 following](https://travis-ci.org/HaaLeo/vscode-logfile-highlighter/jobs/351793125#L475)). I hoped that Issue #45287 would fix it, but the error still occurs with Release 1.22.1 (as can be seen in this [log](https://travis-ci.org/HaaLeo/vscode-logfile-highlighter/jobs/351806000#L475)). Also Using GCC 4.8 as suggested in issue #45443 does not fix it ([here](https://travis-ci.org/HaaLeo/vscode-logfile-highlighter/jobs/365623865#L445) is the corresponding build).  
However the integration tests run just fine on Travis when I specify  the environment variable `CODE_VERSION=1.20.1` ([corresponding log](https://travis-ci.org/HaaLeo/vscode-logfile-highlighter/jobs/352883445#L476)). They also pass locally on my windows machine using VSCode version 1.22.1.

Steps to Reproduce:

1. Trigger Travis build with the [vscode-logfile-highlighter](https://github.com/emilast/vscode-logfile-highlighter) extension.

Does this issue occur when all extensions are disabled?: I guess yes, because when VSCode is downloaded on travis, there are no preinstalled extensions?

**Comment by bpasero** [comment]
Assuming the error originates from ripgrep.

**Comment by HaaLeo** [comment]
Maybe I should also have mentioned that we **do not** use the built in mocha test runner, but wrote a custom runner using the [jasmine](https://github.com/jasmine/jasmine) framework v2.9.0.

**Comment by roblourens** [comment]
I see that CI is green on that repo right now, are the tests disabled? I'd like to try it myself in Travis so let me know how I can get them to run.

**Comment by roblourens** [comment]
Oh I see that you're setting that environment variable in the travis file.

**Comment by roblourens** [comment]
Actually you just need to update your version of the "vscode" package to actually get the fix :)
