### ISSUE TITLE
Git branch name still displayed when folder is removed from workspace.

### ISSUE THREAD

**Issue by spooality** [Microsoft/vscode#47743]
- VSCode Version: 1.22.1
- OS Version: Windows 7 Enterprise SP1 x64

Steps to Reproduce:

1. Open folder tracked by git in VSCode by File > Add Folder to Workspace
2. See current branch displayed in lower left corner.
3. Remove folder from workspace by right clicking on folder icon and selecting "Remove Folder From Workspace".
4. Branch is still displayed in lower left corner when no folder is open.

![capture](https://user-images.githubusercontent.com/18753796/38682383-92722fd2-3e30-11e8-93c6-d06f52a3f75f.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Great bug!

**Comment by chenhowa** [comment]
@joaomoreno I'd like to take a look at this, but I'd need help getting started. Where would I find the code executed when folders are added to and removed from the workspace? Where would I find the classes responsible for reaching out to execute the git extension functions?
