### ISSUE TITLE
VS Code can't debug Python when a launch.json for node.js exists

### ISSUE THREAD

**Issue by andybantly** [Microsoft/vscode#47754]
- VSCode Version: 1.22.1
- OS Version: Version 6.1 (Build 7601: Service Pack 1)

Steps to Reproduce:

1. Create a new node.js file
2. Create launch.json
3. Save the files and exit
4. Load VS Code
5. Create a new Python file
6. Create launch.json
7. VS Code loads the node.js launch.json

Can't debug any Python files unless the launch.json is manually edited to remove the node.js configuration

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
A launch.js can contain any number of configurations for any type of debugger, So your launch.json could have one for node.js and one for Python.
