### ISSUE TITLE
Transpose action affects editor line even when another text input has focus

### ISSUE THREAD

**Issue by gwk** [Microsoft/vscode#47757]
- VSCode Version: 1.23.0-insider (1.23.0-insider) fe9d9532ea6264152c144bd2ba3a6db2cd1732e3 2018-04-12T05:05:41.502Z

- OS Version: macOS 10.13.5 Beta (17F35e)

Steps to Reproduce:
1. Open a text file for editing (new/untitled works).
2. Type "ab" then place cursor between "a" and "b".
3. Open the command palette or enter the "rename file" mode to get text input focus on a text field element.
4. Type "xy" in the text field, then place the cursor between "x" and "y".
5. Hit `ctrl-t` or whatever your transpose characters keybinding is.

Expected results: the text field should now display "yx".
Actual results: the text field is unaltered, but the underlying editor now displays "ba".

Note that this bug does not appear to affect the integrated terminal. If you focus on the editor window, then the integrated terminal, then the text input, then hit `ctrl-t`, the editor window still receives the transpose action.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
I could not reproduce, when I hit <kbd>ctrl</kbd>+<kbd>T</kbd> in the rename input text field I get the characters swapped in the input text field:

![kapture 2018-04-13 at 15 00 51](https://user-images.githubusercontent.com/5047891/38736180-87032f9c-3f2b-11e8-9965-47e20b2a6b87.gif)

**Comment by gwk** [comment]
The two input fields I reproduced with were:
* command palette
* file explorer rename

Can you please try those? Thank you,
George

**Comment by alexandrudima** [comment]
@gwk I cannot reproduce

Did you perhaps install an extension that binds `Ctrl+T` or perhaps you have edited your `keybindings.json` ?

![kapture 2018-04-16 at 18 42 33](https://user-images.githubusercontent.com/5047891/38823182-fb17ea72-41a5-11e8-8301-d225d9f5de6e.gif)

![kapture 2018-04-16 at 18 43 55](https://user-images.githubusercontent.com/5047891/38823248-2938106c-41a6-11e8-8408-5c2f15af5f2b.gif)
