### ISSUE TITLE
Find in Folder Search

### ISSUE THREAD

**Issue by NoashX** [Microsoft/vscode#47751]
Issue Type: <b>Bug</b>

Before the most recent update, I could click on Find in Folder..., then 3 input boxes would appear: a search box, a folder path to include box, and a files to exclude box. Now there are only 2: one for the search box, and one called files to include/exclude, which is confusing and not as functional for my task at hand. It seems I can only either include or exclude, which makes no sense to me. I must be doing something wrong. How do I exclude certain files from my path search in a specific folder now?

Thanks!

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:27:19.487Z)
OS version: Windows_NT ia32 10.0.14393

**Comment by roblourens** [comment]
You can still include and exclude by entering the same patterns as before and using ! to mark the exclude patterns. See https://github.com/Microsoft/vscode/issues/47751
