### ISSUE TITLE
Tab's dirty state indicator invisible when hovering tab

### ISSUE THREAD

**Issue by fmal** [Microsoft/vscode#47752]
- VSCode Version: 1.22.1
- OS Version: mac OS 10.13.4 

The visual indicator for dirty tabs get's overriden by theme's or custom `tab.hoverBackground`. The quick workaround is to add `!important` to the following rules: 
https://github.com/Microsoft/vscode/blob/2d686ce94bd8b79dcd02f483af4bf650a689dc36/src/vs/workbench/browser/parts/editor/media/tabstitle.css#L214
https://github.com/Microsoft/vscode/blob/2d686ce94bd8b79dcd02f483af4bf650a689dc36/src/vs/workbench/browser/parts/editor/media/tabstitle.css#L219

![cgnae3zhzd](https://user-images.githubusercontent.com/927591/38685570-7f25fbba-3e72-11e8-81e9-1b348b27f390.gif)

Steps to Reproduce:

1. set custom `tab.hoverBackground` in `workbench.colorCustomizations` and hover over dirty editor tab

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@fmal good catch, want to do a PR to fix this?

**Comment by fmal** [comment]
@jzr1991 turns out you need to also set `workbench.editor.tabCloseButton` to `off` to reproduce, by default dirty indicator background is applied to `a.close-editor-action`, but when you disable close button it's set directly on the tab element and thus get's overriden. I will open up a PR.
