### ISSUE TITLE
.vscode/launch.json can't be moved

### ISSUE THREAD

**Issue by andybantly** [Microsoft/vscode#47753]
- VSCode Version: 1.22.1
- OS Version: Version 6.1 (Build 7601: Service Pack 1)

Steps to Reproduce:

1. Create a new node.js file
2. Create launch.json
3. Save the files and exit
4. Load VS Code
5. Create a new node.js in a different folder and location
6. Create launch.json

VS Code loads the launch.json from step 2
No matter what VS Code, won't change the location of launch.json.  This applies to other program languages like Python.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
VS Code creates the launch.json in the ".vscode" folder which lives in the workspace folder.
A user is not supposed to create the launch.json.
If you need another launch.json in a different location, you will have to create a new workspace folder and let VS Code create the .vscode folder and the launch.json.
