### ISSUE TITLE
How do I remove recently opened projects/files in Mac dock?

### ISSUE THREAD

**Issue by aligajani** [Microsoft/vscode#47750]
As shown in the image below. 

![image](https://user-images.githubusercontent.com/1730778/38684836-848399e6-3e68-11e8-9826-f49b567383b8.png)

**Comment by bpasero** [comment]
@aligajani this list should reflect the contents of File > Open Recent. You can remove recently opened individual entries from the picker (Ctrl+Shift+R) but it might require a restart. Can you try?
