### ISSUE TITLE
Support typescript's fixName code action property

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#47760]
Add support for the new `fixName` property ts is adding to code actions https://github.com/Microsoft/TypeScript/pull/23350

**Comment by isidorn** [comment]
@mjbvz please provide verifications steps. thanks

**Comment by mjbvz** [comment]
Thanks for taking a look. This was only for telemetry and I just verified that the `fixName`property is being sent properly myself:

```
RawEventsVSCodeExt 
| where EventName contains 'typescript'
| where EventName contains 'quickfix'
| project Fix = tostring(Properties['fixname'])
| summarize count(Fix) by Fix
```
