### ISSUE TITLE
New Feature: Is any plan for terminal version?

### ISSUE THREAD

**Issue by titaneric** [Microsoft/vscode#47765]
Hi,
I know vscode is cross-platform GUI editor, but is possible to provide a terminal version of vscode?
Based on my own experience, I am more familiar with vscode shortcuts than vim's, so it is more efficient to write code for me.
Also, I really like the feature of vscode like split the window, multiple line edit, light weight debug etc. I really really want to see the vscode appearing on the terminal!!
P.S. I know vim+tmux+vundle can do the similar things, but I want the full support from officials.

Thank you.

**Comment by Tyriar** [comment]
No this is not really doable, at least not without an enormous amount of work. Every single UI element would need to be reimplemented for the terminal and many keyboard shortcuts would no longer work as terminals have some restrictions on hotkeys.
