### ISSUE TITLE
Convert to ES6 Module Not Being Offered with Hint/Suggested Code Action

### ISSUE THREAD

**Issue by clarkio** [Microsoft/vscode#47772]
- VSCode Version: Version 1.23.0-insider (1.23.0-insider)
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. I have this project opened in the editor: https://github.com/clarkio/ttv-chat-light
2. In `src/index.js` I see the ellipsis show up on line 1 for the `tmi.js` module and the hint indicates it can be converted to an ES6 module. However, the editor doesn't always show the light bulb to make the change for me when I click my cursor to that area of code.

Ellipsis showing up:
![image](https://user-images.githubusercontent.com/6265396/38696879-6affeec0-3e5e-11e8-93b9-905007ceb235.png)

Hint with no light bulb option:
![image](https://user-images.githubusercontent.com/6265396/38696899-73b8e058-3e5e-11e8-914b-5b3cd211ed09.png)

Does this issue occur when all extensions are disabled?: Yes, I tried with this option and had the same results

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/23387 to track this upstream
