### ISSUE TITLE
Need a way to get logs from the DA when there is no explicit launch config

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#47774]
There is no way to set 'trace' when there is no launch config set, like when using auto attach. I can always have the user create a launch config for debugging, but it would be easier if they could set a setting which would enable tracing.  

cc @weinand

**Comment by isidorn** [comment]
This makes sense.
I started to look into this, and propose the following setting:
`debug.trace`. IMHO this should be a string, however not sure about the potential values.
We could try to be consistent with our log levels. Default value would be `off`.

However this would not be consistent with our `trace` setting in `launch.json`. Currently that one is a `boolean` or a `string` which I find confusing. It also does not specify all the potential string values, just mentions "verbose".

![screen shot 2018-05-02 at 22 46 42](https://user-images.githubusercontent.com/1926584/39548416-d4d533ee-4e5a-11e8-8f01-1736d00a0a40.png)

**Comment by isidorn** [comment]
I have pushed an initial version of this. Try it out and we can work on the naming / possible values

**Comment by roblourens** [comment]
Thanks, I wonder if it should actually just be based on the vscode Log Level though? I didn't think of that at first, and it could actually just be done inside the extensionhost.

In the debug adapter I only use `"trace": true` because I've never needed to narrow it down by level, and I think that's simpler.

**Comment by roblourens** [comment]
Well I guess the difference with the global Log Level is that the default for the debug adapter should be "off" but the default for the Log Level is info.

I wonder if it's confusing to have this other place to set a log level though.

**Comment by roblourens** [comment]
Maybe it's ok for the default to be "info". If vscode and other extensions are logging at level "info", then the debug adapter can be too. I would have to change the levels of some messages because I haven't been precise with them, but that's ok. An adapter is free to say every log message is "verbose" if it doesn't want to log them by default.

It wouldn't log to the debug console, it would only write to a file. Where to direct the logs is a separate dimension but that's up to the adapter.

Maybe the property should be `logLevel` to match language elsewhere, including how this is exposed through the extension API.

And I have no idea how this would affect other adapters, we can look at whether any are using these properties already.

**Comment by isidorn** [comment]
`trace` is contributed by the node debug adatper so no other extension can depend on this.
So the proposed work is the following:
* VSCode always appends `logLevel` to the launch configuration with a string value equal to what is configured via logging in vscode. Unles user has already manualy set `logLevel` in `launch.json`
* VSCode starts supporting `logLevel` in the `launch.json` schema 
* nodeDebug starts handling `logLevel` on its side properly
* nodeDebug no longer contributes `trace` schema
* nodeDebug continues supporting `trace` for a milestone
* we let all the debug adapter authors know of this new feature so they can act on it

@weinand @roblourens if you agree let me know and I will do the work on the vscode side.

**Comment by roblourens** [comment]
Sounds good to me!

**Comment by isidorn** [comment]
Let me reopen this then

**Comment by isidorn** [comment]
@roblourens ok I have pushed the work needed on the vscode side.
Leaving up to you for the required nodeDebug work.

Once that is done and @weinand gives a thumbs up I can notify debug adatper owners.

**Comment by weinand** [comment]
Adding a new attribute `logLevel` to a launch config comes a bit to late if we want to support to log the initialization phase too. (yes, DAs could still do it by always buffering a log and then throwing it away if the launch config does not contain a `logLevel` attribute but this makes logging a bit harder).

In addition node-debug's `trace` attribute is not something I want to drop (and it is already documented here https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes).

Why are we not adding a `logLevel`attribute to the DAP `initialize` request similar to the `locale` attribute? See https://github.com/Microsoft/vscode-debugadapter-node/blob/f1b40de22101d8c97df1bab70d28fe0ae22198aa/debugProtocol.json#L593

This is still not at the very beginning of the DA but it is earlier than the `launch` request and it can not collide by accident with any identical named attribute in the launch config.

@isidorn did you already modify something to support a `logLevel` attribute?

**Comment by isidorn** [comment]
@weinand yes we are already appending `logLevel` to every launch configuraiton [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L782).
From my point of view we could add it to the `initialize` request instead - I agree that it makes sense to send it to the DA as soon as possible.

I can change this for this milestone if we all agree.

**Comment by weinand** [comment]
Adding this to the `initialize` request requires a DAP change (which I will not do on the last development day).

I suggest to revert the appending of the `logLevel` attribute for this milestone and we continue the discussion in June.

**Comment by weinand** [comment]
Thanks and there was no other change related to this, right?

**Comment by isidorn** [comment]
@weinand oops forgot to remove it from the schema - now I have also done that. So no other changes on the vscode side.

**Comment by isidorn** [comment]
@weinand I believe we have no plans to do add this to the DAP on the last day. Thus moving this to July. Assign back to me once we have added it to the protocl - thanks!

**Comment by weinand** [comment]
I don't think that we need a generic logging flag in VS Code to support DA logging for special cases like the "no explicit launch config" case. If a debug extension supports such a feature, it can make a "logging" setting available and pass this to its DA with whatever mechanism necessary.

Closing.

**Comment by roblourens** [comment]
js-debug does actually already have a way to do this through configuration 👍
