### ISSUE TITLE
The preLaunchTask 'build' terminated with exit code 0. Why do I get this?

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#4777]
- VSCode Version: 0.10.11
- OS Version: Windows 10 Enterprise

Why do I see this? Isn't 0 a "successful" exit code?

Steps to Reproduce:
I'm not sure how to reproduce it.
![image](https://cloud.githubusercontent.com/assets/14098140/14124165/f597f050-f5b8-11e5-95f6-05a6b23ef966.png)

**Comment by isidorn** [comment]
Looking at the code [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L557). This should be immposible on latest.
Can you please try to reproduce this on latest insiders - 0.10.13-insider.

If you can please find repro steps I will gladly reopen this bug
