### ISSUE TITLE
Auto-import not prompt with node packages and new classes

### ISSUE THREAD

**Issue by RKopczynski** [Microsoft/vscode#47773]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

Working on Angular project. Recently when create new file/class and trying to reference it in another module or whatever, shortcut CTRL + Space show absolutely nothing reasonable:
![image](https://user-images.githubusercontent.com/11996103/38696706-3c618ad8-3e90-11e8-9194-b1e299e2b0d3.png)

Same goes to npm modules. When trying to include (4 example) some @angular/core dependency like @Component, auto-complete cannot find it (example class: GameComponent from image above):

![image](https://user-images.githubusercontent.com/11996103/38696398-49456248-3e8f-11e8-81a4-d8382910b33f.png)

Does this issue occur when all extensions are disabled?: Yes

This worked well before latest update. I tried to reinstall app, remove some extensions or all, but nothing was helpful. 

**UPDATE**
Ok, GameComponent could resolve @angular/core dependencies when I add it to some module, however before that I needed to manually add import to GameComponent in module.

**Comment by mjbvz** [comment]
Which typescript version are you using?
