### ISSUE TITLE
Drag minimap slider with touch

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#47771]
Issue Type: <b>Feature Request</b>

When using a touch screen, I want to be able to interact with VSCode in an intuitive manner.

When I touch the minimap, I expect the document to scroll immediately on touch-down, not on touch-up. Mouse-up makes sense for a mouse, but not for a touch.

When I touch and drag the minimap, I expect the minimap to scroll with my finger.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Rophuine** [comment]
I haven't PR'd vscode before, if anyone who cares about this issue has tips on getting my PR ^^ merged and released I'm happy to put more work into it. I find it very frustrating not having touch-scrolling on the minimap, as I'm so used to it working in old-school Visual Studio!
