### ISSUE TITLE
Cannot move tab from one pane to another via drag and drop

### ISSUE THREAD

**Issue by bobderrico** [Microsoft/vscode#47780]
- VSCode Version: 1.22.2
- OS Version: macOS Siera 10.12.6

Steps to Reproduce:

1. Open a file in the editor
2. Drag the tab of the file to the desired group (for example, moving it into the right group)
3. Release the mouse button. State does not change after releasing mouse button (ie, cursor still show tab under it, file does not move to next group). The only way out of this state is to hit escape. This started this afternoon after I updated to 1.22.2. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@bobderrico can you record a screencast how that works for you?

**Comment by bobderrico** [comment]
Oddly enough, this seems to be working fine this morning. I will close the issue.
