### ISSUE TITLE
code.exe is deleted while update from 1.22.1 to 1.22.2

### ISSUE THREAD

**Issue by alakameljebali** [Microsoft/vscode#47786]
- VSCode Version: 1.22.1
- OS Version: Windows 7 SP1 x64

Steps to Reproduce:
1. Update Microsoft VS Code from the menu
2. Waiting the update process to complete
3. Restart Microsoft VS Code
4. code.exe is deleted while update from 1.22.1 to 1.22.2

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
Can you fully reinstall Code?

**Comment by subbuatgithub** [comment]
hi , i had same issue when i updated it, i think i work around i see is to copy all the content of 'C:\Program Files (x86)\Microsoft VS Code\_' to 'C:\Program Files (x86)\Microsoft VS Code\' (overwrite)

after upgrade i see code.exe is there in the strange folder '_' (underscore)

now i see vs code is up and running version is also point to 1.22.2 

there must be a fix for this , but i see this as workaround for now

**Comment by alakameljebali** [comment]
@joaomoreno 
1. Sorry but I didn't remember the error code but I'll try to reproduce it!
2. Yes I can fully reinstall Code.

**Comment by joaomoreno** [comment]
OK Let me know.
