### ISSUE TITLE
Can't Refactor C# Member Variable

### ISSUE THREAD

**Issue by otri** [Microsoft/vscode#47789]
Issue Type: <b>Bug</b>

I can't seem to refactor (F2) any of my C# class member variables in this release.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (13.38GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
unity-tools|Tob|0.1.9
unity-debug|Uni|1.3.0
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
vscode-icons|rob|7.22.0
vscode-nginx|sha|0.5.0
markdown-all-in-one|yzh|1.1.2

</details>

**Comment by otri** [comment]
I get this odd thing on the OmniSharp Log:
```
Starting OmniSharp server at 2018-4-12 17:07:07
    Target: /Volumes/SecureHDDAaron/Projects/Occipital/communicator-mvp/CommunicatorUserX/CommunicatorUserX.sln

OmniSharp server started wth Mono
    Path: /Volumes/SPD-otri/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/OmniSharp.exe
    PID: 20847

﻿[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Volumes/SecureHDDAaron/Projects/Occipital/communicator-mvp/CommunicatorUserX/Temp/bin/Debug/Assembly-CSharp.dll'
```

**Comment by otri** [comment]
Seems related to this bug report:
https://github.com/OmniSharp/omnisharp-vscode/issues/1793

**Comment by weinand** [comment]
Please file this issues against the C# extension.
