### ISSUE TITLE
Flickering Screen on 1.22.2

### ISSUE THREAD

**Issue by arb** [Microsoft/vscode#47787]
- VSCode Version: 1.22.2
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Start 3 instances of VSC

Does this issue occur when all extensions are disabled?: *Yes*/No

When I have 3 instances of VSC open at a time; the screen starts flickering like crazy. I have attached a gif demonstrating the behavior. This just started after the update today to 1.22.2.

![vsc](https://user-images.githubusercontent.com/1591483/38708452-53e92c80-3e84-11e8-9135-ab72d4ea6540.gif)

Going out of full screen seems to stop the issue, but is hardly a solution.

**Comment by bermanboris** [comment]
I experience the problem even **without** full screen.

**Comment by arb** [comment]
*UPDATE* now it's happening even with a single instance open

**Comment by vityas-off** [comment]
Try this https://github.com/Microsoft/vscode/issues/45492#issuecomment-375744415

**Comment by jlmaners** [comment]
This only happens for me on my external, HiDPI display. Only work around I've found so far is to run my HiDPI display in native resolution. That stops the flickering but isn't ideal.

macOS 10.13.4, mid-2015 15" MBP with AMD Radeon R9 M370X, Dell 4K display

**Comment by dinvlad** [comment]
This started happening to be again as well on the built-in MBP screen :( Prior to that, the setting `"editor.disableTranslate3d": true` temporarily solved the issue. Looks like that no longer works :(

**Comment by selipso** [comment]
@vityas-off great find. Going to add `code-insiders . --ignore-gpu-blacklist` to my bash alias now.

**Comment by enkia** [comment]
I get this while playing video (via an Epichrome 'app')

macOS 10.13.4, iMac (Retina 5K, 27-inch, 2017), with the video running on external LG 27UD58-B 27-Inch 4K UHD display.

**Comment by stevarino** [comment]
Just upgraded to 1.23.1 on macOS 10.13.4 (15 inch 2015 model) today and this behavior started. 

Disabled all extensions and it still occurs. Single instance of vscode is enough. 

Strangely the behavior does not happen at initial launch but seems to be triggered by scrolling behavior in the terminal window:

 - start vscode, observe normal behavior.
 - press enter repeatedly in the terminal docked at the bottom of the screen. Notice flicker upon scroll.
 - move mouse over code, notice flicker.
 - move mouse over explorer pane, notice flicker.
 - only area not affected by flicker that i have found is the release notes view

**Comment by studentIvan** [comment]
iMac (Retina 5K, 27-inch, 2017)
Mac OS High Sierra 10.13.5 (17F77)
VS Code version 1.23.1
Same problem, --ignore-gpu-blacklist helped from terminal but it doesn't look like a good way

**Comment by bpasero** [comment]
@arb (or anyone) do you still see this in our insiders release?  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by eedwards-sk** [comment]
I have not encountered this issue recently on the last couple releases.

**Comment by studentIvan** [comment]
@bpasero seems it's already fixed

**Comment by bpasero** [comment]
Great.
