### ISSUE TITLE
Need contributors for Settings Sync Extension

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#47782]
This is not an issue but might help the visitors here whoever want to contribute on extensions.

I'm looking for contributors for my Extension "Settings Sync".

To make it one solution, there is still alot of pending work needs to be done like integration with GitLab like Github, backup/ restore using file system and much more.

If anyone wants to contribute, do let me know we can have skype session to improve the extension.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/wiki/Feedback-Channels

Please try Gitter, Slack or Twitter for this.

**Comment by shanalikhan** [comment]
I think i need invitation for both Slack rooms
Can you send me invitation at shanalikhan@hotmail.com
