### ISSUE TITLE
Editing a folder and make it a nested folders

### ISSUE THREAD

**Issue by aaaaeinai** [Microsoft/vscode#47791]
I suggest editing `src` folder and rename it to `src/main/java/hello`:

from
```
└── src
```

to
```
└── src
    └── main
        └── java
            └── hello
```

Currently these are what I got

![edit-folder](https://user-images.githubusercontent.com/27877342/38711607-468d4a6a-3ef9-11e8-977e-7402d37ebbd5.png)

![unable](https://user-images.githubusercontent.com/27877342/38711629-650e6884-3ef9-11e8-92e2-2e4c472bf82b.png)

**Comment by tsalinger** [comment]
@aaaaeinai thanks for reporting this.
It's currently not possible to do this with the rename command.
Use the 'New Folder' command instead.
