### ISSUE TITLE
Image editor is not centered in Centered Layout

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#47799]
- Toggle Centered Layout
- Open an image
- It is narrow and pushed to the left. Should be centered, or immune to Centered Layout

**Comment by isidorn** [comment]
I have solved this by not centering the binary editor.
@bpasero notice that I have moved all the editor type ids from `files.ts` to `editor.ts`
Currently they were spread in those two files which felt a bit shaky to me (I might ahve introduced this initially).
Let me know if you do not like them in editor.ts and we can figure out a different way to determine the type of an editor.

**Comment by bpasero** [comment]
@isidorn the preferences, file and binary file editor are being contributed to the workbench from `vs/workbench/parts`. Moving knowledge of them into `editor.ts` (which is a core workbench piece) is a layer breaker we should try to avoid. The following IDs should move out again:
* `PREFERENCES_EDITOR_ID`
* `TEXT_FILE_EDITOR_ID`
* `FILE_EDITOR_INPUT_ID`
* `BINARY_FILE_EDITOR_ID`

If we need to check on some property to decide to do something (like centering or not), we could have another method on editor input similar to [`supportsSplitEditor`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor.ts#L254) to answer that.

**Comment by isidorn** [comment]
@bpasero makes sense. I have made the changes to move this back into it's appropraite layer, however now I seem to be hitting the following issue
1. Open an editor, go into center mode
2. Open preferences editor
3. Layout is called -> I need to figure out if I should center, however the preferences editor still does not have input asociated with it - it is null. Thus I can not ask the input if it supports centered editor

**Comment by bpasero** [comment]
@isidorn you could also move this method to the [`BaseEditor`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/baseEditor.ts#L26)
