### ISSUE TITLE
emmet conflict？

### ISSUE THREAD

**Issue by zzh3319** [Microsoft/vscode#47798]
i input  div  use emmet    it auto change to  <i class="devicons devicons-vim"></i>  

how can i  input div  it atuo change to <div><div> ?

**Comment by ramya-rao-a** [comment]
@zzh3319 There isnt enough details in your bug description. Can you add more information to what you did and what you expected to happen?

Read [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet)

**Comment by ramya-rao-a** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
