### ISSUE TITLE
there are not active source control provides

### ISSUE THREAD

**Issue by GanLuo96214** [Microsoft/vscode#47802]
Issue Type: <b>Bug</b>

when i first time install vscode (i don't install xcode or command line tools at that time), I opened a GIT extension (and it doesn't show on extension list),I disable it. How did I enable it. 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
project-manager|ale|0.25.0
GBKtoUTF8|buk|0.0.2
gitlens|eam|8.2.1
Go|luk|0.6.78

</details>

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/38721395-50a88bbc-3efa-11e8-80e8-f762088e6ec6.png)
