### ISSUE TITLE
按键查找

### ISSUE THREAD

**Issue by Corps-Yan** [Microsoft/vscode#47806]
Issue Type: <b>Feature Request</b>

在资源管理器里为什么没有按字母查找文件的功能呢，文件很多时，没有这个功能很头痛啊啊啊啊

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
