### ISSUE TITLE
Easier to navigate to files

### ISSUE THREAD

**Issue by Corps-Yan** [Microsoft/vscode#47809]
Issue Type: <b>Feature Request</b>

Ctrl+P is too trouble , i need navigate through explorer by typing start of file/folder name!!!

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

**Comment by usernamehw** [comment]
Duplicate of #10026 ?
