### ISSUE TITLE
Adding node_modules folder to .vscode directory causes hang

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4781]
- VSCode Version: 0.10.12-alpha
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Open a Node.js project
2. If you haven't already, run npm install to generate the files under node_modules
3. In VS Code drag the node_modules directory to move it under .vscode directory
4. Wait a few seconds then the window will hang.

**Comment by Tyriar** [comment]
Can't reproduce, anymore details on a repro?

**Comment by Tyriar** [comment]
Closing off as cannot reproduce
