### ISSUE TITLE
Source Control:Git and Git in Terminal out of Sync.

### ISSUE THREAD

**Issue by DanielFloris** [Microsoft/vscode#47810]
- VSCode Version:1.22.2
- OS Version:Windows 7 Pro

Steps to Reproduce:
I don't know how to reproduce, I've set up a new local git repo with 4 files. Using terminal, git status says up to date. Source control reports all 4 files are modified. Committing using Source Control makes Git in the Terminal report that all files are modified. 

Switching branches in the Terminal is correctly reflected in the bottom left.  Discard all changes doesn't do anything.  Git:output doesn't give me much insight.

Does this issue occur when all extensions are disabled?: Yes
Disabling extensions doesn't change the situation

**Comment by joaomoreno** [comment]
Let me know once you can reproduce.

**Comment by DanielFloris** [comment]
I have an example right in front of me, it there no suggestions of something I can check?
