### ISSUE TITLE
Editor built-in linter complains about non empty rulesets

### ISSUE THREAD

**Issue by pke** [Microsoft/vscode#47818]
I am reporting a bug where it claims an empty rule set, when it is not empty but contains dynamic prop replacement.

![](https://user-images.githubusercontent.com/164625/38709759-034670f6-3ebd-11e8-95b7-987491c10c37.png)

Stylelint does not complain on the command line about this.

> What CSS is needed to reproduce this issue?

```jsx
<style jsx>{`
  .hero {
    background-image: url(${image});
  }
`}</style>
```
What stylelint configuration is needed to reproduce this issue?

I am using the default configs:

"stylelint-config-standard": "^18.2.0",
"stylelint-config-styled-components": "^0.1.1",
"stylelint-processor-styled-components": "^1.3.1",
"stylelint": "^9.2.0",

The error is shown in combination with [style-jsx](https://github.com/zeit/styled-jsx)

Visual Code Version Info:
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by aeschli** [comment]
@pke What's the language mode the editor is in? HTML or JavaScript React? Can you paste a complete sample? 

I tried the sample of https://github.com/zeit/styled-jsx#getting-started, and that doesn't show errors (as we don't validate css in jsx).

**Comment by pke** [comment]
The editor is in JavaScript mode.
I have the feeling it not always happens. Today it seems to be gone. Need to investigate more.

Thats the complete file:

```es6
import React from "react"
import PropTypes from "prop-types"

const Hero = ({ image, children }) => (
  <section className="hero" image={image}>
    <style jsx>{`
      .hero {
        height: 320px;
        color: black;
        background: no-repeat 50% 50%;
        background-size: cover;
        position: relative;
      }
    `}</style>
    <style jsx>{`
      .hero {
        background-image: url(${image});
      }
    `}</style>
    {children}
  </section>
)
Hero.propTypes = {
  image: PropTypes.string.isRequired,
  children: PropTypes.node,
}
export default Hero
```

**Comment by octref** [comment]
@pke I guess this is an error thrown by https://marketplace.visualstudio.com/items?itemName=AndrewRazumovsky.vscode-styled-jsx-languageserver.

If the error happens again, try disable that extension. If the error is gone, report issues to that extension. If not, feel free to reopen to create a new issue.
