### ISSUE TITLE
Spell check etc. for working with Markdown

### ISSUE THREAD

**Issue by Deepfat** [Microsoft/vscode#47813]
we have a lot of documentation to write up in Markdown and it is a real challenge to use VSCode as an editor.  Of course I coule just use Word but then.  I see that a company has developed [Writage](http://www.writage.com/) to do this in Word but it feels more sensible to augment VSCode to do this as we'll be using VSCode for everything else in a project

**Comment by David-Else** [comment]
I highly recommend https://marketplace.visualstudio.com/items?itemName=ban.spellright

**Comment by coliff** [comment]
I highly recommend: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker.
