### ISSUE TITLE
Feature request: paste and select pasted text

### ISSUE THREAD

**Issue by gsbelarus** [microsoft/vscode#47814]
Reason: sometimes there is a need to copy a block of text within the same file and replace some words within copied block. 

Ctrl-Shift-V would be a good combination for the command.

**Comment by gsbelarus** [comment]
Also consider opening Replace window with Selected text option active. i.e. the command will do three actions in one:

1. paste block
2. select it
3. open window for a search-replace values

**Comment by zhangfeiran** [comment]
Many times after I paste a block of text and find indent is needed, and I have to re-select this pasted block and press tab. So this feature could be very useful to me!

**Comment by haifengkao** [comment]
I think we can make selected pasted text by modifying [paste-and-indent](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-paste-and-indent)  and remap the paste key.

We only need a brave hero to implement it

**Comment by TheSench** [comment]
I often have the opposite use-case, where I want to highlight some text and then paste it multiple times to duplicate it.  This workflow would be broken with this suggestion.  This functionality should be toggle-able.

**Comment by TheSench** [comment]
I wonder if this also has implications on mutli-cursor highlighting and pasting over top of the selection.

**Comment by TheSench** [comment]
Another issue I'm running into with this behavior:
Highlight a block of text, paste in a replacement, and start typing to add on to the end of it.

**Comment by borsboom** [comment]
@TheSench I don't think anyone is suggesting changing the normal paste behaviour.  This would be an additional action.

**Comment by TheSench** [comment]
@borsboom I would hope so.  Unfortunately, the current version of the insider's release was behaving this way today.  I originally ended up here from #59881 which did seem to be advocating for changing the default paste behavior.  I think I may have mixed that issue up with this one (which is very clearly advocating for an additional "paste-and-highlight" action.

**Comment by Palidino** [comment]
I ended up here for a similar issue. Unless I'm remembering wrong, pasting over selected text didn't use to select the now pasted text. Is there a way to toggle this off?

**Comment by FlamingFlowair** [comment]
The fix proposed in [issue 82802](https://github.com/microsoft/vscode/issues/82802) worked for me.

**Comment by ccidral** [comment]
Changing the default paste behavior would be quite disruptive. It makes more sense to add a new command and let users configure their own key bindings.

**Comment by haifengkao** [comment]
If you guys are using vim, just 
1. installs VSCodeVim plugin
2. add the setting "nnoremap gp \`[v\`]"
3. in normal mode, type gp to selecte pasted text
