### ISSUE TITLE
[loc]Request to add Slovak language to VS Code

### ISSUE THREAD

**Issue by janbaltus** [Microsoft/vscode#47822]
We expect at least three language contributors sign up and product team sign off before adding new language to Transifex. Please vote by adding your Transifex account name here in this issue (request).
How to request guide: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by wptom** [comment]
https://www.transifex.com/user/profile/wptom/

**Comment by Camatius** [comment]
https://www.transifex.com/user/profile/Camatius/

**Comment by airen29** [comment]
https://www.transifex.com/user/profile/airen29/

**Comment by juozhe** [comment]
A note from a fellow translator. The transifex profiles that are listed above are not visible to me, perhaps the profiles are still private. If Microsoft wants to verify the profiles, you can make them public.

**Comment by s4muel** [comment]
made mine not private

**Comment by airen29** [comment]
Hello Juozhe, 
 I did change settings and my profile is now public. Thanks

**Comment by airen29** [comment]
Hello. What is the current state?

**Comment by s4muel** [comment]
@danyeh or @janbaltus - any news, please?

**Comment by danyeh** [comment]
@shawndon , could you please triage the request? Thanks!

**Comment by shawndon** [comment]
Hi Folks,

Thanks for using the Transifex platform. however, as of January 1, 2019, Microsoft has discontinued the use and now has migrated to the Microsoft Localization Community Platform (MLCP).

Please see the following Wiki page for more information

How to request guide: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project
