### ISSUE TITLE
suggestion : add a  keyword list of search history

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#47821]
keep a  keyword list of search history and make it easy to turn to the previous search keyword state.

**Comment by roblourens** [comment]
You can use alt+up/down to access your previous search terms. Is that what you're looking for?

**Comment by b00f** [comment]
I think he is looking for more obvious like a combo box or something like that...

**Comment by roblourens** [comment]
I have https://github.com/Microsoft/vscode/issues/23099 to track that

**Comment by b00f** [comment]
I think you can close this bug
