### ISSUE TITLE
Promblem in Mavensmate: refresh file

### ISSUE THREAD

**Issue by cacioffolo** [Microsoft/vscode#47829]
Issue Type: <b>Bug</b>

when in a salesforce class I make some changes, if wrong, when I do Mavensmate: Refresh File, the one I wrote is not deleted but I have to close the class and open it again.
it's something that bothers me a lot.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|Memory (System)|7.88GB (2.04GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
mavensmate|Dav|0.15.0
vscode-eslint|dba|1.4.8
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
apex|Joh|0.0.2
visualforce|Joh|1.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
sublime-keybindings|ms-|3.0.3
angular2-inline|nat|0.0.17
salesforcedx-vscode|sal|42.11.0
salesforcedx-vscode-apex|sal|42.11.0
salesforcedx-vscode-apex-debugger|sal|42.11.0
salesforcedx-vscode-core|sal|42.11.0
salesforcedx-vscode-lightning|sal|42.11.0
salesforcedx-vscode-visualforce|sal|42.11.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by joaomoreno** [comment]
https://github.com/joeferraro/MavensMate/issues
