### ISSUE TITLE
Documents created in VS Code don't appear in Open Recent

### ISSUE THREAD

**Issue by bcmn** [Microsoft/vscode#4782]
- VSCode Version: 0.10.11
- OS Version: Windows 7 

Steps to Reproduce:

1. Create a new file, save, and close.
2. Navigate to File > Open Recent. The newly-created file is not shown. Opening a second time  will cause it to be shown.

I may be pedantic, but this seems unintuitive.

**Comment by bpasero** [comment]
The list of "File > Open Recent" is being populated from interactions from outside VS Code into vs code (e.g. drag and drop, terminal, open with) or using the native file dialog, not from actions within vs code. I assume the second time you open the file you used the native file dialog to open the file.

**Comment by bcmn** [comment]
I see. Yeah, I was using the file dialog to open the file. To clarify -- the issue wasn't with the method of opening the file, but that saving a new, from-scratch file through the file dialog doesn't add to the Open Recent list.

**Comment by bpasero** [comment]
@bcmn I am not sure I can follow, if in Sublime Text I save an untitled file, it does not appear under File > Recently opened.

**Comment by bcmn** [comment]
@bpasero Okay, its an arbitrary UI choice, then! Up to you. Displaying under Open Recent would seem most common (enough that I assumed it was an issue), and certainly more consistent with other Microsoft programs -- Visual Studio, Office suite, etc.

(I did say it was pedantic!)

**Comment by bpasero** [comment]
@bcmn ok I am not familiar how Visual Studio behaves here. We do show recent files you open within VS Code in quick open (Ctrl+P) as well as quick navigate (Ctrl+Tab), maybe you could get used to that?
