### ISSUE TITLE
Bad user experience when installing incompatible extension version using VSIX

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#47828]
- VSCode Version: 1.21
- OS Version: Any

Steps to Reproduce:
1. Make an extension which specifies minimum required VSCode version 1.22
2. Build extension and install from VSIX using VSCode 1.21

Expected: a UI notification saying that Extension XXX requires VSCode version 1.22 or higher.

Actual result: no error/warning is shown in the VSCode UI telling the user that the extension requires a newer VSCode version.
Extension is just shown as not loaded, clicking "Reload" button reloads the UI, but nothing changes.

This is how it looks:
![image](https://user-images.githubusercontent.com/16953692/38732640-381292ee-3f1f-11e8-8c6f-eaa6cbe3f6a1.png)

**Comment by RMacfarlane** [comment]
@sandy081 The notification shows as expected, but I think it would be good to include the required engine version in the error message

**Comment by sandy081** [comment]
@RMacfarlane Not sure if that is helpful to the user because we do not support downgrading of VS Code. Since user knows the current version of VS Code, user can file an issue against extension that it is not getting installed with given version.
