### ISSUE TITLE
Add command to command palette from keybindings

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#47839]
It would be nice to be able to do something like this:
```json
{
    "command": "editor.action.insertSnippet",
    "label": "cleanup",
    "args": {
        "snippet": "💄"
    },
}
```
After that, command palette would have new item with text `cleanup`. The main goal is to be able to add actions(and using args) in command palette.

**Comment by jrieken** [comment]
Where are you doing this? In keybindings.json?
