### ISSUE TITLE
The most specific keybinding does not win

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#47831]
I bind `Escape` for `Close Panel`.
- Open the editor
- Press `Ctrl+F`
- Press `Escape`
The find widget is not be closed. I think it should be closed.
- Open the terminal and focuse it
- Press `Ctrl+F`
- Press `Escape`
The panel is closed. I think the find widget should be closed rather than the panel is closed.

VS Code version: Code - Insiders 1.23.0-insider (fe9d9532ea6264152c144bd2ba3a6db2cd1732e3, 2018-04-12T05:17:00.120Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
debugger-for-chrome|msj|4.3.0
java|red|0.22.0

</details>

**Comment by Tyriar** [comment]
The keybindings work on order rather than the specificity of the `when` clause. You will need to redefine the find close keybinding with a `when` clause _after_ escape to close panel

**Comment by shizengzhou** [comment]
@Tyriar Thank you.
