### ISSUE TITLE
Hover quickly disapears

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#47834]
1. Open `editorGroupsControl.ts`
2. Add the following import
`import { BINARY_FILE_EDITOR_ID } from 'vs/workbench/parts/files/common/files';`
3. Notice there is a warning, hover over the warning, hover quickly disapears and I can not read it

**Comment by mjbvz** [comment]
@isidorn I can't reproduce this issue. What TS version is active in your workspace? Do you have other extensions active such as tslint?

**Comment by isidorn** [comment]
I can not reproduce it anymore, though on Friday I saw it all the time.
Next time I see it I will try to disable ts lint and let you know what I see.
