### ISSUE TITLE
[loc][VSCode] Translation "Forward" in "zh_TW"

### ISSUE THREAD

**Issue by alantea** [Microsoft/vscode#47830]
File name:
src/vs/code/electron-main/menus:English (en):plaintext:miForward

Source:
vs_code

Query:
This word is translated into "轉寄", but "轉寄" means in Chinese is usually used to send mail or send letter.
This should be translated as "下一步" would be better.

**Comment by danyeh** [comment]
@alantea , thank you for the feedback! I agree "轉寄" is wrong in context.
Here is about go back or forward in the code editor. So I suggest you to add a translation suggestion of 前進 or 向前.

**Comment by alantea** [comment]
Hello @danyeh:
前進 or 向前 are the good choices in Simplified Chinese. but it's not intuition in Traditional Chinese.
I think "forward" can be translated into "下一頁".
Some web browser (Edge, chrome) also use 上一頁 and 下一頁 to represent back and forward

**Comment by terrysheng** [comment]
@alantea 
Thanks so much for your feedback. Yes, in Traditional Chinese product, e.g. IE, we usually translate it as 下一頁 in similar context. I agree with your suggestion :)

**Comment by danyeh** [comment]
Please take a look at these two. You may want to make them consistent.
https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hant/$/111043565?q=text%3Aforward

**Comment by danyeh** [comment]
These inconsistence still exist. https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hant/$/111043565?q=text%3Aforward.
I close the issue here because original issue was fixed and further action should be taken in Transifex.
