### ISSUE TITLE
System error after trying to move a folder out of .vscode directory

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4783]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. With a Node.js project, drag the node_modules folder to be under the .vscode directory
2. Try to move it back under the root folder

![directorymoveerror](https://cloud.githubusercontent.com/assets/12900364/14126283/b4fc1d44-f5c4-11e5-9007-b48aef028741.JPG)

**Comment by Tyriar** [comment]
This might be to do with node hitting the max path length on Windows.

**Comment by bpasero** [comment]
@vsccarl can you check for the max path length? can you give me access to the workspace? did you run any task in the background or in vs code that could lock the node modules folder?

**Comment by vsccarl** [comment]
@bpasero The max path that I found is 146 characters. I uploaded the project here [https://github.com/carltosc/nodejsSample.git](url) with the folder 'stuck' in .vscode. There weren't any tasks running that should have locked the folder. I can give you access to my machine if you need also.

**Comment by bpasero** [comment]
@vsccarl and when you restart vscode, can you move the folder around? I cannot reproduce...

**Comment by vsccarl** [comment]
@bpasero I installed the latest alpha updates and it was still reproducible. Restarting after allowed me to move it out of the .vscode directory. But now trying to move it to another directory gives the same issue.

**Comment by bpasero** [comment]
@vsccarl maybe the move operation is not fully finished when you try a second time? can you run with ProcMon to see when the file operations are done and then do the move after it is done?

**Comment by vsccarl** [comment]
@bpasero I'm not hitting this issue with the latest alpha.

**Comment by bpasero** [comment]
k

**Comment by bpasero** [comment]
@vsccarl actually this bug sounds very similar to this one here: https://github.com/Microsoft/vscode/issues/4578

**Comment by bpasero** [comment]
@vsccarl I see this now as well, lets continue in #4578

**Comment by riona2** [comment]
but guys i tried Long Path Tool to clean this mess and it worked properly
