### ISSUE TITLE
Auto attach messes up when multiple windows are open

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#47843]
macOS/Insiders

I have the following windows open:

Tyriar/xterm.js (status bar says auto attach on)
Microsoft/vscode (status bar says auto attach off)

When I run `npm run test-debug` in the terminal of the xterm.js window, the debugger stops in gulp.js in the Microsoft/vscode window:

<img width="931" alt="screen shot 2018-04-13 at 11 05 25 am" src="https://user-images.githubusercontent.com/2193314/38750690-97c31dc2-3f0a-11e8-87d9-a5d1ae0a1b57.png">

I then get this error in the Tyriar/xterm.js window:

<img width="446" alt="screen shot 2018-04-13 at 11 06 30 am" src="https://user-images.githubusercontent.com/2193314/38750745-bc56891c-3f0a-11e8-853c-a465a9e2274a.png">

See https://github.com/xtermjs/xterm.js/pull/1388 for npm run test-debug, it does the following:

```
node --inspect-brk node_modules/.bin/gulp test
```

**Comment by Tyriar** [comment]
I'm noticing even with a single window and auto attach set to off, it's still auto attaching 😕 even after a window reload.

**Comment by auchenberg** [comment]
@roblourens Don't we resume execution if there's no pending breakpoints?

**Comment by weinand** [comment]
This should be fixed in VS Code 1.27
