### ISSUE TITLE
Expose 'Use Excluded Settings and Ignore Files` on SearchProvider

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#47840]
Issue Type: <b>Feature Request</b>

Expose _'Use Excluded Settings and Ignore Files'_ for `Search Provider`.
Currently there is no such property on either `TextSearchQuery` or `TextSearchOptions`

Should the `SearchProvider` implementation assume this options is always ON? How does VSCode apply it for custom registered search providers?

**Comment by IlyaBiryukov** [comment]
cc @jrieken

**Comment by roblourens** [comment]
When that option is turned off, internally, the frontend just doesn't include the exclude patterns in the query, and it doesn't set the option to use the gitignore file. We'll have to figure out how this should be expressed in the SearchProvider API.

**Comment by roblourens** [comment]
This is supported by the API now
