### ISSUE TITLE
envVars: command not found

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#47848]
_From @goonode on April 13, 2018 7:5_

## Environment data

- VS Code version: code-insider-1.23.0-1523510016
- Extension version (available under the Extensions sidebar): XXX
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: N/A

When i press F5 for debugging debug starts but python exit with "envVars: command not found" error
and 

_Copied from original issue: Microsoft/vscode-python#1391_

**Comment by DonJayamanne** [comment]
_From @vsimon on April 13, 2018 19:16_

Just ran into this as well. w/code-insider, ubuntu 16.04, python 3.5, virtualenv.

**Comment by DonJayamanne** [comment]
_From @vsimon on April 13, 2018 19:20_

This commit and line change from vscode 2 days ago as of now, looks suspect https://github.com/Microsoft/vscode/commit/b578dc2bd124ce3cfee770151f369057783b7dbd#diff-af270f3e366fdcd571c5700682acdb27R196

I tried downgrading back to VS Code 1.22.2 (latest release) and in there debugging python works.

Workaround: Use the latest release.

**Comment by vsimon** [comment]
At a cursory glance, looks like a "typo" kind of line change... @weinand would know for sure if that's the case.
