### ISSUE TITLE
Debugger fails to launch with environment variables (integrated terminal)

### ISSUE THREAD

**Issue by samrg472** [Microsoft/vscode#47844]
- VSCode Version: 1.23.0-insider (76c2e560)
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. Create a launch configuration
2. Set `console` to `integratedTerminal`
3. Configure environment variables

Does this issue occur when all extensions are disabled?: Yes

The following command is executed:
```
cd <snip> ; envVars "TYPEORM_OVERRIDES=<snip>" "CONFIG=<snip>" /usr/local/bin/node --inspect-brk=33504 out/index.js
```
Results in:
```
bash: /usr/sbin/envVars: Permission denied
```

I use the fish shell as my primary shell, in which case it says "command not found" (presumably because of the lack of executable permissions). Previously, bash and fish used to work in 1.23.0-insider.

The envvars script has been generated by `envvars-std` for use by apachectl.

**Workaround:**
Create your own envVars script somewhere on your `$PATH` (must be before /usr/sbin) with:
```
#!/usr/bin/env bash
eval "$@"
```

**Comment by weinand** [comment]
duplicate of #47848
