### ISSUE TITLE
Debugger is throwing error while trying to run prelaunch task from launch.json.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4784]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10
Setup:
Launch.json:
"program": "${workspaceRoot}/app.js",
			"preLaunchTask": "build",

Steps to Reproduce:
1. Create a Typescript node.js console app in Visual studio.
2. Launch VS code and open root directory.
3. Configure task.json with below entries and refer created task into launch.json.
      {
        "version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"args": [],
	"showOutput": "always",
	"tasks": [
		{
			"taskName": "build",
			"isBuildCommand": true,
			"args": ["app.ts"],
			"problemMatcher": "$tsc"
		}
	]
}
4. Start debugger and verify output.

Actual:
1. Getting error pop-up and error message contents in output window is not matching with actual error.
![image](https://cloud.githubusercontent.com/assets/17735796/14128536/97034ce2-f5d6-11e5-9a45-b92754bb5066.png)

![image](https://cloud.githubusercontent.com/assets/17735796/14128405/80568604-f5d5-11e5-95e7-031decc7722b.png)
2. Getting error pop-up for preLaunchTask and when user click on continue everything works perfectly.
![image](https://cloud.githubusercontent.com/assets/17735796/14128484/1574f37e-f5d6-11e5-892d-6c15e9f87153.png)
3. Looks like task got failed but .js file generated successfully.
![image](https://cloud.githubusercontent.com/assets/17735796/14128388/520d7f6e-f5d5-11e5-8008-f5829225c2e5.png)
4. Sometime showing multiple error messages in the output window.
![image](https://cloud.githubusercontent.com/assets/17735796/14128422/af89af96-f5d5-11e5-8a75-01bb3f0d7fdd.png)

**Comment by isidorn** [comment]
This behavior is as expected, for some reason you preLaunchTask exited with error code 1 - which means there was an error. Though in some cases you might still be able to debug, thus we present the `Continue` action.

You probably tried running the task multiple times - thus there are two entries in the output.

If you want to understand the true cause of your issue, you should investigate why your task returns error code 1. Try running it isolated - outside of vscode and you will see the same error you see in the output.
