### ISSUE TITLE
Debug hover context menu

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#47849]
The original post was with the C/C++ debugger, but this looks like a more general issue (https://github.com/Microsoft/vscode-cpptools/issues/1824 ).

I can't copy values from the debugger's hover view (no right click) and instead need to locate/add the value in the Watch window. I mostly want this for C++ debugging when I need to copy string values (paths, etc.). Typescript debugging seems to have the same limitation.

I would assume other people have complained about this already but I couldn't find any feature requests for this.

**Comment by isidorn** [comment]
Currently you can select text and copy using the shorcut keys in the debug hover tree.
However we do not support the context menu in the debug hover. Leaving this open as a feature request to add a context menu to the debug hover.
Though in our regular non debug hover we do not support a context menu as well atm.

**Comment by sean-mcmanus** [comment]
Oh, thanks a lot -- that work around of select/paste works -- I didn't think of doing that because the mouse cursor is a hyperlink pointer instead of the normal pointer. I don't know a reason I would need the right-click menu now.

**Comment by isidorn** [comment]
Ok, then closing this and will reopen if we find some other use case for the context menu
