### ISSUE TITLE
show fixes icon (light bulb) disappear when code folded

### ISSUE THREAD

**Issue by richywalls** [Microsoft/vscode#47842]
Issue Type: <b>Bug</b>

Wirite the following js code: 
```
// @ts-check
const test = {
}
this is an error
```
the `this is an error` line causes an error, this shows a little light bulb (show fixes)
![image](https://user-images.githubusercontent.com/2954965/38748277-f6df4470-3f23-11e8-90db-9a6420000c54.png)

if the previous line is the end of a folded content, then the light bulb no longer appears.
![image](https://user-images.githubusercontent.com/2954965/38748342-29464e2c-3f24-11e8-83f7-6ce6c6473cc7.png)

the issue still appears after disabling all extensions

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.4.0-116-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3805)|
|Load (avg)|1, 1, 0|
|Memory (System)|15.62GB (0.50GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.6.0
xml|Dot|1.9.2
latex-workshop|Jam|5.1.0
awesometypescriptproblemmatcher|Jua|0.3.0
vscode-docker|Pet|0.0.26
vscode-wakatime|Wak|1.2.0
latex-preview|ajs|0.5.1
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
vue-snippets|hol|0.1.5
Go|luk|0.6.78
code-beautifier|mic|2.0.3
vscode-todo-parser|min|1.9.1
vscode-pugbeautify|mrm|1.0.2
vscode-kubernetes-tools|ms-|0.1.7
python|ms-|2018.3.1
vsliveshare|ms-|0.2.307
debugger-for-chrome|msj|4.3.0
vetur|oct|0.11.7
swaggitor|qns|0.1.1
vscode-yaml|red|0.0.11
sass-indented|rob|1.4.8
vscode-sql-beautify|sen|0.0.4
language-stylus|sys|1.9.1
tizentv|tiz|1.0.1
vscode-apielements|vnc|0.6.7
gitblame|wad|2.4.2
vscode-proto3|zxh|0.2.1

</details>

**Comment by alexandrudima** [comment]
@jrieken A content widget painted on a folded line will not be rendered.

The next question is how was it possible to fold the `}` away like that. @aeschli is that a bug ?

**Comment by aeschli** [comment]
@alexandrudima Yes, a known bug in the TypeScript folding provider.

**Comment by mjbvz** [comment]
The TS folding bug was fixed a few months back

@jrieken The lightbulb widget still doesn't render in this case however:

```
// @ts-check
const test = {

} this is an error
```

when `test` is folded the the cursor is over `error`.

**Comment by jrieken** [comment]
> A content widget painted on a folded line will not be rendered.

Seems to be an editor thing...

**Comment by jrieken** [comment]
We now check if a line is folded and show the lightbulb above/below or iff possible inline. There can still be a case in which it doesn't show...

**Comment by jrieken** [comment]
*top line folded, use line below*
<img width="117" alt="screen shot 2018-09-11 at 15 13 43" src="https://user-images.githubusercontent.com/1794099/45362503-4aa83800-b5d5-11e8-8908-fa85911fcd50.png">

*use line above when possible*
<img width="111" alt="screen shot 2018-09-11 at 15 13 36" src="https://user-images.githubusercontent.com/1794099/45362505-4b40ce80-b5d5-11e8-92b0-45707e918b26.png">

*no line below, no line above, but inline space*
<img width="112" alt="screen shot 2018-09-11 at 15 13 29" src="https://user-images.githubusercontent.com/1794099/45362506-4b40ce80-b5d5-11e8-9a2c-fc0724b1369a.png">

*no line below, no line above, no inline space -> no lightbulb*
<img width="150" alt="screen shot 2018-09-11 at 15 13 21" src="https://user-images.githubusercontent.com/1794099/45362507-4b40ce80-b5d5-11e8-8daa-2550ccf3a37c.png">
