### ISSUE TITLE
Drag 'n drop root-folders doesn't work when moving a root folders that are ancestors or descendents of another

### ISSUE THREAD

**Issue by forivall** [Microsoft/vscode#47852]
Since I implemented the dnd root folder reordering in atom, i was curious when i saw it mentioned in the change notes for vs code. And I found a bug!

Issue Type: <b>Bug</b>

Open a workspace with root folders such as
```json
{
  "folders": [
    {
      "path": "."
    },
    {
      "path": "a"
    },
    {
      "path": "b"
    }
  ]
}
```

Folders `a` and `b` are fairly easily moved around each other, but `.` cannot be moved and `a` and `b` can not be moved when dropped over `.`.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_2019821|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
indent4to2|Com|0.1.2
racket|Dmy|1.2.0
xml|Dot|1.9.2
graphviz-preview|EFa|0.0.4
EditorConfig|Edi|0.12.1
gc-excelviewer|Gra|2.0.20
beautify|Hoo|1.3.0
awesometypescriptproblemmatcher|Jua|0.3.0
material-icon-theme|PKi|3.3.0
dot|Ste|0.0.1
quokka-vscode|Wal|1.0.117
sort-imports|ama|5.1.0
previewseqdiag-vscode|ari|0.1.0
vscode-refresh-html|baj|0.0.2
spellright|ban|2.2.12
vscode-icontheme-nomo-dark|be5|1.3.5
unique-lines|bib|1.0.0
markdown-checkbox|bie|0.1.1
markdown-preview-github-styles|bie|0.1.2
vscode-raml|blz|3.0.1
box-comment|can|0.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.8
chmod|dle|1.0.0
githistory|don|0.4.0
gitlens|eam|8.2.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.5.1
abnf|for|1.0.0
pegjs-syntax|fut|0.1.1
rest-client|hum|0.18.1
vscode-ebnf|igo|1.0.3
launcher|ili|0.0.4
docthis|joe|0.6.0
json-escaper|jos|1.0.1
fuzzy-definitions|jri|0.0.3
racket|kar|0.0.3
rainbow-csv|mec|0.2.1
vscode-duplicate|mrm|1.2.1
mssql|ms-|1.3.1
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.16.1
team|ms-|1.133.0
vscode-mscgen|msc|1.1.0
debugger-for-chrome|msj|4.3.0
editorconfiggenerator|nep|0.2.1
vetur|oct|0.11.7
vscode-code-outline|pat|0.1.0
open-html-in-browser|pea|0.0.3
vscode-template-literal-editor|pli|0.9.0
typescript-mono-repo-import-helper|q|0.0.5
java|red|0.22.0
npm-link-status|rob|0.0.3
nunjucks|ron|0.2.3
linter-xo|sam|2.1.3
vscode-zipexplorer|sle|0.3.1
vscode-odata|sta|0.1.0
rewrap|stk|1.8.1
html-preview-vscode|tht|0.1.1
pdf|tom|0.2.0
vscode-sourcemaps-navigator|vlk|0.0.3
vscode-apielements|vnc|0.6.7
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.1

(4 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Omg you have 67 extensions.
Thanks for the report, we accept PRs that fix this - especailly if they are not complex
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L979

@bpasero I believe that workspaceEditiingService should handle this case, right?

**Comment by bpasero** [comment]
@isidorn yes the workspace editing service should work with any combination of folders.

**Comment by shobhitchittora** [comment]
@bpasero @isidorn I don't really understand the bug here. Is it possible to create a dir with name `.`, which already exists btw ? What am I missing here ?

**Comment by forivall** [comment]
@shobhitchittora with absolute paths, this could look something like
```
{
  "folders": [
    {
      "path": "/home/forivall/my-project"
    },
    {
      "path": "/home/forivall/my-project/a"
    },
    {
      "path": "/home/forivall/my-project/b"
    }
  ]
}
```
It's impossible to make a directory with the name `.`, and it just means the same folder that the `example.code-workspace` file is in. Hopefully that clears it up.

**Comment by jeanp413** [comment]
I'll take this up.

**Comment by isidorn** [comment]
Now this is disabled.

**Comment by bpasero** [comment]
I verified the issue as described in https://github.com/Microsoft/vscode/issues/47852#issue-314263301
