### ISSUE TITLE
Focus keeps shifting away from my group

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#47858]
I'm coding primarily in Python and Ruby. I usually code with two groups open.

I'm typing in group 1, then I move focus to group 2. Focus is then forced back to group 1, when a tooltip appears for whatever I just typed. This is a problem, because for Python and Ruby, the tooltips will often have some delay because they are slow to load. For Python for instance, I've had tooltips appear 5 seconds after the last character was entered.

This only started happening a few days ago, about 5 days ago from this date, if I had to guess. It was fine the month before that.

Please either stop letting tooltips take focus away from the group I'm in, or stop tooltips from appearing in groups that are not in focus.

**Comment by joaomoreno** [comment]
What do you mean by "tooltip appears"? Can you share a screenshot?

**Comment by garyking** [comment]
It's hard to reproduce because I need to get a tooltip that has a delay before it loads. Then when I switch to another tab, it will finally load, and take focus away.
