### ISSUE TITLE
Provide Option to enable File-Save prompts in extension development mode

### ISSUE THREAD

**Issue by grork** [microsoft/vscode#47856]
Issue Type: <b>Feature Request</b>

When debugging an extension, the file save prompt in editors is automatically responded to with 'don't save'. When debugging issues related to saving in an extension (e.g. opening a workspace, or closing), this makes it impossible to test without building your own Code install.

The offending line is:

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/electron-browser/textFileService.ts#L75

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17133

**Comment by bpasero** [comment]
We have this since a while now via `--extension-development-confirm-save`
