### ISSUE TITLE
No Network during truffle compile

### ISSUE THREAD

**Issue by lodnocneib** [Microsoft/vscode#47854]
Issue Type: <b>Bug</b>

When compile, showing no network in new install.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2397)|
|Memory (System)|8.00GB (4.83GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
solidity-extended|bea|3.0.2
jshint|dba|0.10.18
vscode-eslint|dba|1.4.8
beautify|Hoo|1.3.0

</details>

**Comment by joaomoreno** [comment]
Can you provide a screenshot?
