### ISSUE TITLE
The auto-completion can't work when i use the editor for a while

### ISSUE THREAD

**Issue by TangiDing** [Microsoft/vscode#47859]
Issue Type: <b>Bug</b>

It just occurs in recent versions of vs code, i mean both of version 1.22.2 and last version happen this problem in my computer. the situation is that when i use the editor for a while, the auto-completion doesn't work. in this situation i can't get any information of completion when i input some abbreviation, like ims or  reletive path. it make me inefficiency. i hope this issue can help the product more perfect.

steps:
1. open some project use webpack.
2. start the project with webpack dev server.
3. just write code using auto-completion for a while.
4. auto-completion doesn't work.
5. when i open the console of devTool, It seem occur a exception infomation like these: 

/D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1306   ERR 出现未知错误。有关详细信息，请参阅日志。 

it means unknown mistake happened, in order to get more detail info, please read the logs.

My English is poor, i hope this helpful.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|7.90GB (2.78GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
fileheadercomment|doi|0.0.3
es7-react-js-snippets|dsz|1.4.0
webpack-snippets|gog|0.0.4
webpack|jer|2.0.2
code-beautifier|mic|2.0.3
open-in-browser|tec|1.1.0

</details>

**Comment by mjbvz** [comment]
A few questions:

1. Can you please test this in vscode insiders with all extensions disabled.

1. Does this happen in any javascript project you open or just this one?

1. Is there something specific that causes the intellisense to stop working? Does this always happen in one file or when trying to complete a specific object for example?

1. Does that project have a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson)?

1. Are you using cnpm?

Thanks
