### ISSUE TITLE
Wordwrap lost when going to another tab and come back

### ISSUE THREAD

**Issue by lepinekong** [Microsoft/vscode#47868]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

1. Toggle Wordwrap to active
2. Go to another document tab
3. Come back: wordwrap no more

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
@lepinekong I cannot reproduce. Is there something more to it ?

![kapture 2018-04-16 at 14 59 47](https://user-images.githubusercontent.com/5047891/38810381-e3dbfafc-4186-11e8-903d-6e7d57418d03.gif)
