### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by zhaojuntao** [Microsoft/vscode#47869]
Not find in stackoverflow platform.

- VSCode Version: 1.22.1
- OS Version: Windows 10 15063.608

Problem Description: 
1. When using the search function, there are sometimes infinite waits or no search. Problems usually appear after the software has been running for some time. 

2. Workspace can not achieve function jump, progress bar infinite refresh. 

Steps to Reproduce:

1. Open two vscode windowat
2. Open folders separately
3. Waiting for a period of time, maybe an hour, or longer
4. Then use `search function` and `function jump` function

Everything is normal after restart, problems will occur after some time.

Does this issue occur when all extensions are disabled?: Yes

**Comment by zhaojuntao** [comment]
https://stackoverflow.com/questions/tagged/vscode

**Comment by zhaojuntao** [comment]
![](https://note.youdao.com/yws/public/resource/222acf56941a290f06755362b5baeb1f/xmlnote/9C68E8D12280468EBDFC05E015AB7785/18310)

**Comment by roblourens** [comment]
What do you mean by `function jump`?

**Comment by roblourens** [comment]
- Are you searching in a large folder with lots of files?
- In Task Manager, do you see a process running called `rg.exe`?

**Comment by zhaojuntao** [comment]
- Are you searching in a large folder with lots of files?  
Yes，contains git management.

- In Task Manager, do you see a process running called rg.exe?  
do not find `rg.exe`

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)
