### ISSUE TITLE
GPU task hangs the window for 5-60 seconds

### ISSUE THREAD

**Issue by xobs** [Microsoft/vscode#47862]
Issue Type: <b>Bug</b>

1. Use the editor
2. Scroll the window
3. Type some stuff

Expected results: The editor should remain responsive

Observed results: The editor hangs for anywhere from 5-60 seconds.  The window cannot be resized.  This occurs regardless of where in the editor I am, and occurs both in the text editor, and within this "Issue Reporter" window.

The program is not using a high amount of CPU, and the system is not heavily loaded.  The system has plenty of RAM.  Extensions are disabled.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (9.26GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --disable-extensions .|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by bpasero** [comment]
@xobs does it reproduce if you run "`code --disable-gpu`" from the command line?

**Comment by tbergeron** [comment]
it happens to me when scrolling the terminal, hangs for a very long time! without any extensions :-/
