### ISSUE TITLE
Failed to install VS Code update.

### ISSUE THREAD

**Issue by GEeKkk** [Microsoft/vscode#47866]
- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:
- vscode-inno-updater.log
Apr 14 15:29:29.358 INFO Starting: E:\Microsoft VS Code\Code.exe, false
Apr 14 15:29:29.358 INFO Checking for running Code.exe processes... (attempt 1)
Apr 14 15:29:29.358 INFO Code.exe is running, wait a bit
Apr 14 15:29:29.873 INFO Checking for running Code.exe processes... (attempt 2)
Apr 14 15:29:29.873 INFO Code.exe is not running
Apr 14 15:29:29.873 INFO Starting update, silent = false
Apr 14 15:29:29.904 INFO do_update: "E:\\Microsoft VS Code\\Code.exe", _
Apr 14 15:29:29.904 INFO move_update: "E:\\Microsoft VS Code\\unins000.dat", _
Apr 14 15:29:29.904 INFO Delete: ".git" (attempt 1)
Apr 14 15:29:29.967 INFO Delete: ".git" (attempt 2)
Apr 14 15:29:30.170 INFO Delete: ".git" (attempt 3)
Apr 14 15:29:30.623 INFO Delete: ".git" (attempt 4)
Apr 14 15:29:31.436 INFO Delete: ".git" (attempt 5)
Apr 14 15:29:32.701 INFO Delete: ".git" (attempt 6)
Apr 14 15:29:34.513 INFO Delete: ".git" (attempt 7)
Apr 14 15:29:36.977 INFO Delete: ".git" (attempt 8)
Apr 14 15:29:40.180 INFO Delete: ".git" (attempt 9)
Apr 14 15:29:44.242 INFO Delete: ".git" (attempt 10)
Apr 14 15:29:49.257 INFO Delete: ".git" (attempt 11)
Apr 14 15:29:49.257 ERRO 拒绝访问。 (os error 5)

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
Why do you seem to have a `.git` repository in `E:\Microsoft VS Code`?
