### ISSUE TITLE
Allow starting a debug session while another one is initializing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#47863]
Forked from https://github.com/Microsoft/vscode/issues/45798

This kind of goes with the fact that we can't kill a session while it's initializing. I might have filed an issue for that in the past. I would take that over this. My main scenario is accidentally starting an attach session, then having to sit for 10s for it to timeout before I can start the one I intended.

> However people are filing the oppoiste requets, that no session should be started during intiailisation so no 2 sessions are started by accident

We don't allow starting the same config twice, so I don't see a problem.

**Comment by isidorn** [comment]
I will first look into making it possible to terminate an initialising session.

**Comment by isidorn** [comment]
@roblourens now it is possible to stop an initialsing session.
Try it out and let me know if you still need this feature - I believe it might not be needed

**Comment by roblourens** [comment]
This is perfect, thanks! I need this at least once a day, I think it's needed.

**Comment by roblourens** [comment]
Oh by "this feature" you meant "Allow starting a debug session while another one is initializing".

My personal use case is satisfied by the change you already made to allow killing a session before it initializes. I think that "Allow starting a debug session while another one is initializing" would still be useful, but I don't feel too strongly about it, you can wait to see if someone else asks for it if you want.

**Comment by isidorn** [comment]
@roblourens thanks for clarifying, I will wait then.
