### ISSUE TITLE
Windows: Integrated terminal displays incorrect background color after ANSI attribute reset code

### ISSUE THREAD

**Issue by wavebeem** [Microsoft/vscode#47878]
Issue Type: <b>Bug</b>

- Start Visual Studio Code on Windows 10 with `bash` installed
- Open the integrated terminal
- Run `bash`
- Run `echo -e "\033[0m"`

## Expected output

The terminal looks the same

## Actual output

All text has a strange background color now

## NOTE

This seems reproducible across every theme I've used, but in particular the default "Light+" theme is incredibly hard to read after this bug occurs

I have not found any workarounds for the bug yet besides "Kill Terminal"

![image](https://user-images.githubusercontent.com/176815/38771169-f5db2d32-3fd2-11e8-990f-9de2b63d7401.png)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Memory (System)|15.93GB (7.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\w\pkmn.help|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-simpler-icons|dav|1.5.2
vscode-eslint|dba|1.4.8
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.3.0
vscode-simple-icons|Lau|1.8.2
python|ms-|2018.3.1
PowerShell|ms-|1.6.0
sublime-keybindings|ms-|3.0.3
vscode-sort-json|ric|1.11.0
trailing-spaces|sha|0.2.11
rewrap|stk|1.8.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Tracked in https://github.com/Microsoft/vscode/issues/45693
