### ISSUE TITLE
Code folding does not appear if code is not properly formatted

### ISSUE THREAD

**Issue by TeamGoTango** [Microsoft/vscode#4787]
- VSCode Version:0.10.11
- OS Version: Windows 7 Enterprise, Service pack 1

Steps to Reproduce:

//paste this code ( GO ), code folding stops working for all code after it.
func recursiveSum(array []int) int {
	return sumRecursive(array, 0, len(array)-1) //no space before and after -
}

//code folding starts to work if re-written as [ notice the space after len(array) ]
func recursiveSum(array []int) int {
	return sumRecursive(array, 0, len(array) - 1 ) //space after -
}

**Comment by egamma** [comment]
This is as designed, the code folding is based on indentation.

Semantic based/AST based code folding is on the backlog

// @aeschli

**Comment by DmitryEfimenko** [comment]
I think it'll be an often inconvenience for developers. A common example is to disregard indentation when specifying an inline html template in a javascript file. Here is an example from angular app::
```javascript
export function componentDirective(): ng.IDirective {
    return {
        template: `
<div>
	<p>There's going to be a lot of html here and having its indentation start from the beginning is helpful in this case</p>
</div>
`,
        scope: true,
        controllerAs: '$ctrl',
        bindToController: true,
        controller: componentController
    }
}
```

**Comment by aeschli** [comment]
We have issue #3422 for adding semantic folding.
