### ISSUE TITLE
Unexpected encoding change when autoGuessEncoding is enabled

### ISSUE THREAD

**Issue by mRcfps** [Microsoft/vscode#47872]
- VSCode Version: 1.21.1
- OS Version: macOS High Sierra 10.13.3

Steps to Reproduce:

1. Enable `files.autoGuessEncoding` in User Settings.
2. Create a new file with non-ASCII characters (Chinese characters here), and save it with UTF-8.
![image](https://user-images.githubusercontent.com/23410977/38768269-904a7aee-4023-11e8-95ad-60c240337615.png)
3. Reopen this file, and vscode will guess its encoding as **Windows 1252**, and Chinese characters will become unrecognizable due to inappropriate encoding.
![image](https://user-images.githubusercontent.com/23410977/38768284-df095114-4023-11e8-93e9-4db755ccabf6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@mRcfps you will have to save with "UTF-8 with BOM" to ensure we reopen this as UTF-8 when auto guess encoding is on.

**Comment by mRcfps** [comment]
@bpasero When I reopen this file (previously saved with **UTF-8 with BOM**), its encoding remains the same but that's not the desired result for most users sticking to **UTF-8** like me. Actually I'm talking about handling unexpected encoding change in terms of files with **UTF-8**, not **UTF-8 with BOM**, which is strongly Windows-flavored and not friendly to users on UNIX-like systems.

**Comment by bpasero** [comment]
@mRcfps if you configure auto guessing of encoding there is no guarantee that the file will be detected as UTF-8. I suggest you disable this setting if you want a more deterministic behaviour. Encoding guessing is always a guess and can likely produce wrong results.
