### ISSUE TITLE
Allow hover hints to wrap after :

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#47873]
With the Haxe extension, we sometimes get awkward wrapping in hover hints in the middle of words like this (`Arr`-`ay`):

![](https://i.imgur.com/wuVwEBS.png)

It looks much better if we manually add a space after `:`.

![](https://i.imgur.com/kZ1bzmV.png)

However, this isn't really a common code style in Haxe (as opposed to TypeScript, where it seems to be the "default style"), so I'd prefer to keep that as-is. I realize a similar issue (#35223) has already been closed as as-designed, but it seems like this specific case could be improved by allowing line breaks after `:` characters?

This is the string from the Haxe Language Server for the first screenshot:

````markdown
 ```haxe
function(params:DocumentSymbolParams, token:CancellationToken, resolve:Array<SymbolInformation>->Void, reject:ResponseError<NoData>->Void):Void
```
````

I also use a non-default text size (`"editor.fontSize": 12`).

**Comment by joaomoreno** [comment]
Yeah this is the sad consequence discussed in #35223. Unfortunately that's unlikely to change in the near future.

It's not as simply to say "allow to wrap after :". It's more about prohibiting to break words in the middle. And we can't do that in the current form of the widget, given the justification in #35223.

**Comment by Gama11** [comment]
Fair enough, thanks for clarifying!
