### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ikennobunga** [Microsoft/vscode#47875]
Is it possible to have a **visual** tool for **padding** and **margin** as well as for **fonts** styling? I really struggle with this little details and end up wasting time adjusting to the right positions.

**Comment by joaomoreno** [comment]
What do you mean? Are you coding in a specific language?

**Comment by ikennobunga** [comment]
what I mean is take webflow.com for example on the right side of the panel they have this ui tool in the layout panel for adding padding and margins by clicking and dragging to your desired size. I would love to see a similar tool implemented on vsc.
