### ISSUE TITLE
RegEx only matching last match when capturing with *

### ISSUE THREAD

**Issue by jns42** [Microsoft/vscode#47877]
Issue Type: <b>Bug</b>

SETUP
Using the following text as a sample:
`OnPerformTask(Int32 x, Int32 y, Int32 z, string name)`

Open the "Replace" tool window, and enter the following as a RegEx pattern:
`On(\w+)\((\w+, )*[\w]+ (\w+)`

Enter the following as the replacement pattern:
`$1($2$3`

EXECUTION (Round #1)
After the first replacement, the text should read as follows in the editor:
`OnPerformTask(x, Int32 y, Int32 z, string name)`

EXECUTION (Round #2)
After the second replacement, the text should read as follows in the editor:
`OnPerformTask(x, y, Int32 z, string name)`

EXECUTION (Round #3 - !!! Here is where the bug lies !!!)
After the first replacement, the text should read as follows in the editor:
`OnPerformTask(y, Int32 z, string name)`

Revisting the RegEx pattern:
`On(\w+)\((\w+, )*[\w]+ (\w+)`

The second capture: `(\w+, )*`

I believe this bug is being caused because `x, ` and `y, ` are both being captured, but only the last capture is being retained for use in `$2` for the replacement text.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2594)|
|Load (avg)|20, 18, 18|
|Memory (System)|3.74GB (0.10GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
beautify|Hoo|1.3.0
vscode-docker|Pet|0.0.26
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
php-debug|fel|1.12.3
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.0.18
python|ms-|2018.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
mono-debug|ms-|0.15.8
typescript-javascript-grammar|ms-|0.0.39
vs-keybindings|ms-|0.2.0
cs-script|ole|1.3.5
vscode-arduino|vsc|0.2.12

</details>

**Comment by roblourens** [comment]
Isn't this because in `(\w+, )*` the `*` is outside the group? The group is what's captured so you only keep the last instance.

![image](https://user-images.githubusercontent.com/323878/38825479-93ebb9da-4161-11e8-9518-37460a8bc8bd.png)

**Comment by jns42** [comment]
After posting this, I tried to find a few editors with RegEx support, and they all confirmed the behavior is not incorrect. The behavior I was expecting would seem to require an outer capture group in order to retain all of the matches, although that seems to be elusive as well - in all of the aforementioned editors. Perhaps it's just a logic hole in RegEx, itself.

Either way, this ticket may be closed. I appreciate your time.
