### ISSUE TITLE
VSCode fails to detect the workspace when opening a single file after update 1.22

### ISSUE THREAD

**Issue by qjzTreeZ** [Microsoft/vscode#47887]
- VSCode Version: 1.22.2
- OS Version: Windows 7 x64 / macOS High Sierra 10.13.4

Steps to Reproduce:

1. Update VSCode to version 1.22.x
2. Open a single file with a `.vscode` folder in its parent directory

Does this issue occur when all extensions are disabled?: Yes

VSCode 1.21.1 works fine on Windows 7 x64 / macOS High Sierra 10.13.4 / Ubuntu 16.04 LTS 64-bit

**Comment by bpasero** [comment]
@qjzTreeZ we changed this intentionally, if you want to open a workspace, pick "Open Folder" instead.
