### ISSUE TITLE
HTML Closing tag does not preserve indentation

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#47889]
When coding an HTML page I open the tag

```
<div>
    <div>
        ...cursor is here
</div>
```

Then the cursor automatically goes inside the div, which is expected, but if I enter closing tag instead of this:

```
<div>
    <div>
    </div>
</div>
```

I'm getting thise:

```
<div>
    <div>
</div>
</div>
```

Upon completion of a closing tag it goes back to the beginning of the line, not the right indentation of the object.

- VSCode Version: 1.22.2
- OS Version: Microsoft Windows 10 Home

**Comment by aeschli** [comment]
I can't reproduce that with a bare VSCode. Do you have any extensions or installed? Maybe format-on-save enabled?

**Comment by moseleyi** [comment]
Hi,

Format-on-save is definitely false. 

Extensions I have:

AgolaDark Theme
Apache Conf
Apache Conf Snippets
Egoist One
ESLint
Git Indicators
hihglight-matching-tag
IntelliSense for CSS class names
mssql
Paper-tmTheme
PHP Debug
PHP Extension Pack
PHP IntelliSense
PL/SQL
SQL Formatter
Stary any shell

but I haven't installed anything particular

**Comment by aeschli** [comment]
Please try to reproduce with all extensions disabled and see if the issue reproduces:
See here for more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled
