### ISSUE TITLE
This window is no longer responsive (on paste of 300 lines)

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#4788]
- VSCode Version: 0.10.11
- OS Version: Microsoft Windows [Version 10.0.10586]

This is more of a crash report than a bug report. Perhaps it should be a feature request for optional automated crash reporting...?

I have a Node JS project open, running smoothly for a week or so, loving the editor.

7 'working files', all small.

Pasted 350-odd lines of console output into a new, blank document, and the workspace window went blank (background colour) and all (pasted) text vanished. 

The whole program became unresponsive.

A dialog opened: 'This window has become unresponsive.'  Close or wait? Wait.

The dialog re-opened: 'This window has become unresponsive.'  Close. 

Please find a copy of the pasted text (saved via Sublime....!)

[dump2+.txt](https://github.com/Microsoft/vscode/files/195002/dump2.txt)

**Comment by bpasero** [comment]
I am not able to reproduce. Can you try with our latest insider build?

**Comment by alexandrudima** [comment]
@leegee I also cannot reproduce.

**Comment by alexandrudima** [comment]
I would love it if we're able to reproduce the crash, if you have any futher steps or details I would very much appreciate it!

**Comment by leegee** [comment]
I am sorry, I can no longer reproduce.

I have not changed anything in my set-up/the editor.

I guess it was an accumulation of things: having used the editor for about 10 hours a day for a couple of weeks or so, I rarely see a problem, but yesterday I found it frequently unresponsive, and had to pskill it several times.

Will open another ticket if it happens again and I can offer more info on how to reproduce it.

**Comment by egamma** [comment]
@leegee also we fixed some memory leaks that are available in the insider build https://code.visualstudio.com/download?insiders=true

**Comment by leegee** [comment]
Excellent! I'm getting it now, thanks!
