### ISSUE TITLE
auto attach does not work when using '--inspect-brk' in node env variable

### ISSUE THREAD

**Issue by sandangel** [Microsoft/vscode#47897]
- VSCode Version: 1.22.2
- OS Version: MacOS HS

Steps to Reproduce:

0. Turn on Auto attach node debug
1. `NODE_OPTIONS='--inspect-brk' ng test library` (or any node binary)
2. terminal show 
`Debugger listening on ws://127.0.0.1:9229/0b77ab53-e968-48ab-88bd-d6e0294e6bf9
For help see https://nodejs.org/en/docs/inspector`

But vscode debugger does not auto attach to that node process

Does this issue occur when all extensions are disabled?: Yes/No: Yes

**Comment by sandangel** [comment]
I think this is not a duplicate because I use NODE_OPTIONS env var while he's using mocha --inspect-brk

**Comment by weinand** [comment]
@sandangel NODE_OPTIONS based debug flags are not yet supported.

**Comment by sandangel** [comment]
@weinand Hi, thanks for replying. I think it would be nicer if we can call node binary directly and provide NODE_OPTIONS="--inspect-brk" instead of having to call node --inspect-brk /path/to/bin.js

**Comment by weinand** [comment]
Please feel free to submit a pull request since we do not plan to work on this.

**Comment by brian-mann** [comment]
@weinand 	if you could point me in the right direction I could look into whipping up a PR for this. I believe that `NODE_OPTIONS` needs to be scanned the same way you scan for other CLI flags to auto access the processes.

**Comment by Sytten** [comment]
I just ran into the same problem, passing it in NODE_ENV starts both the debugger and the inspector causing the whole thing to crash.
