### ISSUE TITLE
CSS color box incorrect for rgba 255 when opacity < 1.0

### ISSUE THREAD

**Issue by chocolatkey** [Microsoft/vscode#47895]
- VSCode Version: 1.22.2
- OS Version: Windows 10 1709 x64
Does this issue occur when all extensions are disabled?: **Yes**

# Steps to Reproduce:
1. Create a CSS file, make sure CSS highlighting is enabled for it
2. Inside the selector for any type of element (so far) add a color, background or backgrounf-color property.
3. Use any `rgba` value of the following format: `rgba(255,255,255, X)` where X is an opacity value less than 1.0.
Wrong color in the box:
![image](https://user-images.githubusercontent.com/13407784/38775459-008ef078-4038-11e8-9e81-dabcdf9f4f76.png)
but if I decrease any of the rgb by one I get a correct color:
![image](https://user-images.githubusercontent.com/13407784/38775465-1e903eec-4038-11e8-8ba8-990b958868ae.png)
or set opacity to 1.0:
![image](https://user-images.githubusercontent.com/13407784/38775468-2a36a830-4038-11e8-8105-0a6a46f8d23c.png)

**Comment by aeschli** [comment]
@rebornix I verified that the css server sends back the correct rgba. It looks like the decorator does not update the :before-stylesheet if only the opacity is changed.

**Comment by chocolatkey** [comment]
Sorry about closing and reopening, pressed the wrong button
