### ISSUE TITLE
Wrong alert message when deleting multiple directories

### ISSUE THREAD

**Issue by prajapati-parth** [Microsoft/vscode#47892]
- VSCode Version:
1.22.2
- OS Version:
macOS High Sierra 10.13.2

Steps to Reproduce:

1. Hold `Cmd` and select more than one directories in VSCode Explorer.
2. Press `Cmd + delete` to delete them.
3. The popup alert confirms to delete **files** not **directories**. 

Expected message: 
_Are you sure you want to delete the following 2 directories?_

Actual message:
_Are you sure you want to delete the following 2 files?_

Screenshot:
<img width="438" alt="screen shot 2018-04-15 at 10 00 09 am" src="https://user-images.githubusercontent.com/17194534/38775011-dd40e750-4093-11e8-84b3-7d1d1c046170.png">

Does this issue occur when all extensions are disabled?:
Yes

**Comment by isidorn** [comment]
Yes this message can be improved.
We accept PRs that fix this
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L636

**Comment by prajapati-parth** [comment]
WOW! Thanks for the code pointer. Will send a PR for this. Keep it for me. 👍 
Thanks.

**Comment by pradeepmurugesan** [comment]
@prajapati-parth Sorry.. I didn't leave a message that I was already on it..

**Comment by isidorn** [comment]
Verified the message is good now, just polished the grammer in massage (changed 'its' to 'their'
