### ISSUE TITLE
Source code management functions

### ISSUE THREAD

**Issue by HOU-GOD** [Microsoft/vscode#47908]
Issue Type: <b>Feature Request</b>

There is a problem with your source code management function, and you have encountered an error when submitting to github

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.10586

**Comment by yume-chan** [comment]
Please provide more details about what you want to do and what goes wrong.

**Comment by joaomoreno** [comment]
> Please provide more details about what you want to do and what goes wrong.

Ditto
