### ISSUE TITLE
golang multiline string syntax highlighting issue

### ISSUE THREAD

**Issue by breezechen** [Microsoft/vscode#47907]
Issue Type: <b>Bug</b>

```golang
var ms []byte = []byte(`-----BEGIN PUBLIC KEY-----
-----END PUBLIC KEY-----`)
```

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|Memory (System)|7.56GB (1.90GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\go\src\mytest|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.78
python|ms-|2018.3.1
cpptools|ms-|0.16.1
vscode-glide|vit|1.0.2

</details>

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.
