### ISSUE TITLE
Vscode should support login feature so that the user can syncronize all the settings, Themes, Commands

### ISSUE THREAD

**Issue by talhamansoor786** [Microsoft/vscode#47901]
Hello,
I am going to setup my new machine and I stumbled upon a situation in which I need to sync all my previous machine vscode settings, Themes, Custom commands which I have made on my old PC.
Could you please add this feature so that the users could easily synchronize.

**Comment by faelribeiro22** [comment]
Hello, there is an extension that can help in this if it is called Settings Sync.

**Comment by talhamansoor786** [comment]
The process of Settings sync is very lengthy and not suitable for users who don't have account in github. I think the easiest way to sync the settings is providing login by which each users can easily sync their settings.
