### ISSUE TITLE
Starts to lag after editor-widget with large content pops up

### ISSUE THREAD

**Issue by emiljohansson** [Microsoft/vscode#47909]
- VSCode Version: 1.22.2
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. I am using JSS (9.0.0) in the screenshot example.
2. When adding a comma at the end of the line, within the `createStyleSheet` call, an element with the class name `editor-widget` pops up. The content of the box is 10001 characters long. It seems to be cut of after that, ending with `"revert" | "unset…`. Let me know if you want me to paste the content.

In the screenshot, the cursor start to lag when I navigate back and forth. Same when I navigate between editors.

Does this issue occur when all extensions are disabled?: Yes

![kapture 2018-04-15 at 8 15 46](https://user-images.githubusercontent.com/1788399/38779427-6f15a904-4085-11e8-8540-cd9d4cf57f8a.gif)

**Comment by emiljohansson** [comment]
I wanted to add that if I close the widget, the lag remains going between editors, but the cursor lag seems to go away.

I also tested setting the `end` variable to 500 and that removed the lag: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts#L394

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23453
