### ISSUE TITLE
Translation issue in German (Terminal split)

### ISSUE THREAD

**Issue by ShalokShalom** [Microsoft/vscode#47912]
- VSCode Version: 1.22.1
- OS Version: KaOS (rolling)

Steps to Reproduce:

1. Move over the 'split terminal' icon in the German translation
2. Wonder yourself. :)

![screenshot_20180415_180645](https://user-images.githubusercontent.com/6344099/38780501-ce47a240-40d7-11e8-8163-208cc2b10bf2.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by johnliu2016** [comment]
@lukaschal Please take a look

**Comment by lukaschal** [comment]
On review.

https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#de/$/135093841?q=translation_text%3Asuchein

**Comment by lukaschal** [comment]
Please, is it possible to provide us more context about this string ? Both "split" and "terminal" have several translations in German and the context image is not meaningful. Ideally, you could provide an explanation of which concepts both forms refer to and what the command actually does.

**Comment by ShalokShalom** [comment]
You can find the German string in Transifex.

**Comment by lukaschal** [comment]
Linguist need to know what the command actually does or what source "Split Terminal". Maybe ENU/DEU screenshot of whole dialog/screen could be useful as well.

**Comment by ShalokShalom** [comment]
It should be 'Terminal verdoppeln'

**Comment by lukaschal** [comment]
Fixed as suggested.
