### ISSUE TITLE
Issue with function highlight using typescript generics and complex return type

### ISSUE THREAD

**Issue by DStoyanoff** [Microsoft/vscode#47910]
Hello,
I have an issue with syntax highlighting which I cannot find myself. As you can see on the picture, I have two generic functions, one of which is correctly formatted and one is not.

![image](https://user-images.githubusercontent.com/5079334/38780207-af364268-40db-11e8-8e03-1fe760138ca9.png)

What I've tried so far and made it work:
- Removed generic parameter
- Returned simple Promise

As the type "IKeyValuePair" is also generic, I think there is some issue there. Any help is appreciated.

Build is passing without issues, so it is just visual.

- VSCode Version: 1.23.0-insiders
- OS Version: Win 10

**Comment by DStoyanoff** [comment]
Hi @mjbvz,
here is a simplified version:

```
interface IKeyValuePair<K, V> {
    key: K;
    value: V;
}

enum Entity {
    Song
}

export const getByKind = async <T>(kind: Entity, props?: Array<keyof T>, namespace?: string): Promise<IKeyValuePair<number, T>[]> => {
    return Promise.resolve([]);
};
```

**Comment by mjbvz** [comment]
Thanks! Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/601 to track this upstream

**Comment by mjbvz** [comment]
Should be fixed in the next insiders build
