### ISSUE TITLE
Translation issue in German (Deactivate all installed plugins)

### ISSUE THREAD

**Issue by ShalokShalom** [Microsoft/vscode#47913]
This suggests that it uninstalls all plugins, while it essentially deactivates them: 
![screenshot_20180415_201637](https://user-images.githubusercontent.com/6344099/38781735-260d4c5c-40ea-11e8-818f-17f191b16384.png)

**Comment by ShalokShalom** [comment]
Thanks bot, this one here is unique.

**Comment by danyeh** [comment]
@janbaltus , please take a look. https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#de/$/111041991?q=text%3A'Disable+All+Installed+Extensions'

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

Source: Disable All Installed Extensions
New Target: Alle installierten Erweiterungen deaktivieren
