### ISSUE TITLE
If file isn't visible in sidebar, then don't search it

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#47917]
I am hiding some folders and files in the sidebar, like `node_modules`. Yet when I search all files, results appear from files in `node_modules` still. For some reason, this is only happening in one of my workspaces.

To elaborate, I've got a long list of folders in `files.exclude`, and am not using `search.exclude`. I assume that `search.exclude` inherits from `files.exclude`, yet I'm not experiencing this. Especially for `node_modules`, as I said.

**Comment by roblourens** [comment]
Is it searching files that are open?
