### ISSUE TITLE
If workspace file has a space, then search.exclude is ignored.

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#47918]
Create a folder, like `app`, which has files that are part of `search.exclude`. For instance, install an NPM package, like `react`, to create the `node_modules` dir.

Create a workspace for this `app` folder. Ensure the name of the workspace file has a space, so it's like `My App.code-workspace`.

Open the workspace file to open the workspace. Search for `export` across all files. Results will appear from `node_modules`. If you remove the space from the workspace file, and re-open it, then run the search again, then `node_modules` will not appear, which is preferred.

**Comment by roblourens** [comment]
This doesn't seem likely because the workspace file name isn't used or known by any code involved in search. Are you sure those things are connected?

**Comment by garyking** [comment]
I change the name and open it, then the problem happens immediately.
