### ISSUE TITLE
Not getting intetllisense for custome react component props

### ISSUE THREAD

**Issue by chungweileong94** [Microsoft/vscode#47924]
I'm not getting intetllisense for react props, even i already define the propTypes. I able to get the autocomplete on webstorm, I which to have this feature, so that I can fully using vscode. The language that I use is JavaScript.

- VSCode Version: 1.22.2
- OS Version: Windows 10 (16299.371)

Steps to Reproduce:

1.  Create a react component with `propTypes`
2.  Create the component and `ctrl + space` to trigger the intellisense.

Does this issue occur when all extensions are disabled?: Yes

**Comment by flaviocarmo** [comment]
Me too. Happened after 1.22.2 update. My environment is the same.

**Comment by mjbvz** [comment]
We don't support proptypes based intellisense out of the box. An extension may be to add this

See https://github.com/Microsoft/TypeScript/issues/15251#issuecomment-294986145 for an example of how to declare the `props` and `state` of a react component using jsdocs

**Comment by chungweileong94** [comment]
Sadly, I hope vscode could support this feature :(
