### ISSUE TITLE
VSCODE Directory Messy

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#47927]
VSCODE is a great working partner；
In project development, as the project expands, more and more folders are added, and the current deficiencies in the VSCODE directory UI are also found（Directory Too messy）.

Suggest：Above folder, below is the corresponding   ##file（Reference：EIDTPLUS）
![002](https://user-images.githubusercontent.com/20437381/38789109-9fc8d54a-416a-11e8-94b9-91b9807a5113.png)
 
VSCODE UI（the folders and the subfiles are all together，development process is too upset。）
![003](https://user-images.githubusercontent.com/20437381/38789236-965c0562-416b-11e8-8640-b8dbb32c5ad5.png)

This kind of directory layout can have a good display of the files in the folder, it will not reflect the efficiency problems caused by the large number of folders.

#

**Comment by jatarga** [comment]
#17777

**Comment by lihua06** [comment]
#17777 Beautify the directory, did not really improve the confusion of catalog files

**Comment by bpasero** [comment]
@lihua06 thanks for the suggestion but I do not think we would change our file explorer to the UI you presented. However, extensions are free to contribute their own file explorers to improve this.
