### ISSUE TITLE
Move menubar to the left

### ISSUE THREAD

**Issue by unknown-1** [Microsoft/vscode#47929]
Hello,

I've just installed VSCode and without changing anything in the settings I get the Menubar on the right side. This is bothering me alot.
<img width="293" alt="default" src="https://user-images.githubusercontent.com/22024246/38792570-49827c18-4156-11e8-9ff0-7aa8a584a825.png">

Is there a way to move it to the left side? I've looked at the settings and there appears to be no option to change this.

Any help would be appreciated.
Thanks

**Comment by bpasero** [comment]
@unknown-1 what version are you on (check Help > About and copy the details)?

**Comment by unknown-1** [comment]
Hi, sorry about that.
<img width="281" alt="default" src="https://user-images.githubusercontent.com/22024246/38799498-54e82118-416d-11e8-8172-32d6958c09e5.png">

**Comment by bpasero** [comment]
@unknown-1 it looks like more things are right-to-left aligned, e.g. this dialog as well. I can only speculate that you configured some Windows settings that caused it so I suggest you try to revert that back. There is nothing VS Code can do it seems.
