### ISSUE TITLE
Copy C/C++ code from vscode will lose spaces and indents

### ISSUE THREAD

**Issue by wdc596933938** [Microsoft/vscode#47925]
Issue Type: <b>Bug</b>

When I copy C/C++ code from _vscode_ to _one note_ or any web, the spaces and indents will lose. Is there any way to keep them?

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|7.83GB (2.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
cpptools|ms-|0.16.1

</details>

**Comment by yume-chan** [comment]
What's *onnote*?

**Comment by kylef000** [comment]
@yume-chan I assume Microsoft One Note

**Comment by wdc596933938** [comment]
Forgive my broken English, this exactly a spell mistake
