### ISSUE TITLE
 Duplicate object key  

### ISSUE THREAD

**Issue by zh-ngk-i** [Microsoft/vscode#47939]
Issue Type: <b>Bug</b>

why settings.json Prompt " Duplicate object key   "

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|5.69GB (1.15GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.8.0
vscode-eslint|dba|1.4.8
vscode-javac|geo|0.1.1
python|ms-|2018.3.1
vscode-spring-boot|Piv|0.2.0
java|red|0.22.0
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0
vscode-spring-initializr|vsc|0.2.0
JavaScriptSnippets|xab|1.5.0

</details>

**Comment by zh-ngk-i** [comment]
![tim 20180416154142](https://user-images.githubusercontent.com/3607715/38796006-b285b4b0-418c-11e8-9a69-001894d3e936.png)

**Comment by sandy081** [comment]
@zh-ngk-i Can you please open settings and do you see these as two entires in the Default settings also?
