### ISSUE TITLE
GIT merge conflict resolution lens not visibile on first line of the file

### ISSUE THREAD

**Issue by carlobonamico** [Microsoft/vscode#47934]
Issue Type: <b>Bug</b>

1. create a git conflict on the first N lines of a file
2. open the file in the changes view
3. the conflict resolution lens ("Accept Incoming / Accept Current Change ...") is not visible
(Picture 1/A)

If I add an empty line at the beginning of the file, the lens does appear
(Picture 1/B)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.4.0-119-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2400)|
|Load (avg)|3, 3, 2|
|Memory (System)|7.66GB (0.14GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
vscode-devskim|MS-|0.2.2
vscode-docker|Pet|0.0.26
simontest|Sim|0.18.1
cucumberautocomplete|ale|2.9.0
god|bas|0.0.47
regex|chr|0.1.0
githistory|don|0.4.0
gitlens|eam|8.2.1
tslint|eg2|1.0.28
auto-close-tag|for|0.5.6
vscode-angular-components-intellisense|ipa|0.7.3
docthis|joe|0.6.0
Angular1|joh|0.2.0
Angular2|joh|2.16.1
vscode-codemetrics|kis|1.15.0
hg|mrc|1.2.3
mssql|ms-|1.3.1
python|ms-|2018.3.1
vscode-ai|ms-|0.1.7
azure-account|ms-|0.4.0
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
team|ms-|1.133.0
debugger-for-chrome|msj|4.3.0
vscode-versionlens|pfl|0.20.1
java|red|0.22.0
jenkinsfile-support|sec|0.1.0
cucumber|ste|0.11.5
vscode-angular-support|vis|0.1.4
vscode-java-debug|vsc|0.8.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0
vscode-ansible|vsc|0.1.5
vscode-todo-highlight|way|0.5.12

</details>

**Comment by carlobonamico** [comment]
![image](https://user-images.githubusercontent.com/475561/38794672-4140d4d2-4156-11e8-8a8d-2a533c25902d.png)

**Comment by chrmarti** [comment]
Cannot reproduce. Could you retry when starting with `code --disable-extensions` to see if this is triggered by some other extension?
