### ISSUE TITLE
Could not create new file

### ISSUE THREAD

**Issue by NateLing** [Microsoft/vscode#47931]
- VSCode Version: 1.23.0
- OS Version: mac os 10.13.4

Steps to Reproduce:

1. open right menu
2. click new file menu item
 nothing happened

Does this issue occur when all extensions are disabled?: Yes

**Comment by fenglinzeng** [comment]
same here, macOS

**Comment by pharrisee** [comment]
same here, although using the File>New menu works, as does Ctrl-N

**Comment by isidorn** [comment]
Thanks for reporting. Fixed via 62f3ebeb0f
