### ISSUE TITLE
Allow "Alt+Shift+C" to copy path of opened file in the editor

### ISSUE THREAD

**Issue by dylanwind** [Microsoft/vscode#47947]
Issue Type: <b>Bug</b>

Try to copy path of an opened file,  the short cut does not work in editor, only work in Explorer.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|15.88GB (7.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
python|ms-|2018.3.1
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.3.0
vscode-docker|Pet|0.0.26

</details>

**Comment by ramya-rao-a** [comment]
Same goes for the keyboard shortcut for `Reveal in Finder/Explorer`

**Comment by alexandrudima** [comment]
This command is registered to work only when the explorer has focus, i.e. keybinding dispatching respects the `when` condition that is used by the keybinding registration.

https://github.com/Microsoft/vscode/blob/f373a15de059b7ed4918797172eeea224a7a939c/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L431:L443

**Comment by alexandrudima** [comment]
The find widget has 3 toggles:
* match case - cmd+alt+C
* match whole word - cmd+alt+W
* use regular expression - cmd+alt+R

* `revealFileInOS` steals cmd+alt+R
* `copyFilePath` steals cmd+alt+C

**Comment by isidorn** [comment]
tried to steal a keybinding, got caught 😭
as you suggested now I registered my keybindings when the focus is not in the editor

**Comment by sandy081** [comment]
@isidorn cmd+alt+c is not copying the path for me either in editor or in file explorer. Am I missing something?

**Comment by isidorn** [comment]
@sandy081 works for me in the file explroer.
It should not work in the editor.
Make sure you do not have some keybdining clash

**Comment by sandy081** [comment]
Yeah, I have another application stealing that.
