### ISSUE TITLE
type definition

### ISSUE THREAD

**Issue by lym152898** [Microsoft/vscode#47949]
Issue Type: <b>Bug</b>

Go to the type definition is always show loading

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.13.0-041300-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2700)|
|Load (avg)|4, 2, 1|
|Memory (System)|7.70GB (2.15GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.9.0
lua-debug|act|0.2.8
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
sublime-babel-vscode|jos|0.2.9
luaide|kan|0.6.1
Lua|key|0.0.9
ftp-sync|luk|0.3.3
python|ms-|2018.3.1
cpptools|ms-|0.16.1
java|red|0.22.0
vscode-yaml|red|0.0.11
open-in-browser|tec|1.1.0
vscode-lua|tri|0.12.3
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0
vscode-todo-highlight|way|0.5.12

</details>

**Comment by ramya-rao-a** [comment]
On which file type are you seeing this?
