### ISSUE TITLE
EvaluateArguments.context is undefined for "Copy value" context menu action

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#47945]
My debugger currently returns a truncated string for evaluate requests which is fine for the watch window (etc.), especially as Code also truncates - however I'd like to provide the full value when a user clicks "Copy value" on the context menu from the variables window(etc.).

Currently it seems that populating the `Copy value` action from the variables list passes `undefined`.

Is it possible to have this action provide a specific context so I can fetch the full string only on that action? (while I could do it based on `undefined`, this isn't ideal as I don't know what else might not pass a context, now, or in future).

**Comment by DanTup** [comment]
This may be specifically for the Variables list, as it seems like Copy value always copies the provided value - it doesn't seem to call evaluateRequest again for the Watch window, so I need to provide the un-truncated version for watch anyway.

So, are there any guidelines on when to fetch the full untruncated string?

**Comment by isidorn** [comment]
Yes, you need to support evaluateName for the copy value to do the evaluate.
Code pointer https://github.com/Microsoft/vscode/blob/isidorn/nonDebugHovers/src/vs/workbench/parts/debug/electron-browser/electronDebugActions.ts#L29

**Comment by DanTup** [comment]
Aha, this was probably raised before I resolved my evaluateName request issues. Tested today and it seems to be calling it fine. Thanks!

**Comment by DanTup** [comment]
(Closed this because I think the request was mis-guided, evaluateRequest should just return the untruncated value).
