### ISSUE TITLE
Typing with the cursor before an emoji types backwards

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/vscode#47940]
Issue Type: <b>Bug</b>

Typing with the cursor before an emoji types backwards. See the screenshot below.

![image](https://user-images.githubusercontent.com/172594/38796037-18e29254-4152-11e8-8ecd-6825bae5ab05.png)

VS Code version: Code - Insiders 1.23.0-insider (e6b61067f22fd94718f7c427d9caded5514761f4, 2018-04-11T05:17:47.288Z)
OS version: Windows_NT x64 10.0.17133

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.60GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.3.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
beautify|Hoo|1.3.0
PowerShell|ms-|1.6.0

</details>

**Comment by mikemaccana** [comment]
Nope @vscodebot, nothing to do with the integrated terminal, and not a duplicate of those issues.

**Comment by dtkelch** [comment]
I'm seeing this on OS X as well.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.76GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
Bookmarks|ale|0.18.2
solargraph|cas|0.16.0
vscode-eslint|dba|1.4.8
definition-jumper|dan|0.0.1
gitlens|eam|8.2.2
tslint|eg2|1.0.28
javascript-unit-test-snippet|iZD|1.0.0
graphql-for-vscode|kum|1.10.0
MagicPython|mag|1.0.12
code-beautifier|mic|2.0.3
graphql|mqu|0.1.2
vscode-scss|mrm|0.6.2
python|ms-|2018.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
node-debug2|ms-|1.19.0
Ruby|reb|0.18.0
vscode-icons|rob|7.22.0
unittest-navigate|rob|0.0.2
vim|vsc|0.11.4
vscode-react-native|vsm|0.6.9
gitblame|wad|2.4.2
change-case|wma|1.0.0
ReactSnippets|xab|2.1.0

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@mikemaccana @dtkelch I could not reproduce. Is there something more to it?

![kapture 2018-05-16 at 8 34 43](https://user-images.githubusercontent.com/5047891/40100392-05369f30-58e4-11e8-9a05-42859941cc7a.gif)

**Comment by dtkelch** [comment]
@alexandrudima I cannot reproduce anymore on VSCode version 1.23.

**Comment by mikemaccana** [comment]
I (original submitter) can't reproduce anymore either on 1.24-insider. What about you @dtkelch ?

**Comment by dtkelch** [comment]
@mikemaccana I'm no longer able to reproduce the issue. I vote that this issue could be closed, as it appears to have been fixed.

**Comment by alexandrudima** [comment]
Thank you for confirming! :heart:
