### ISSUE TITLE
Missing icons in activity bar

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#47942]
Moved from https://github.com/Microsoft/vscode-cpptools/issues/1840, originally by @Baozi2

version 1.22.2
os mac
this is new , the search、git disappear. All extension disabled
![new](https://user-images.githubusercontent.com/5621510/38794669-8a0dc580-4188-11e8-9c8f-d349eed60ad2.png)

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/38798540-2bd1acaa-4162-11e8-9792-42ae54b8904e.png)

**Comment by Baozi2** [comment]
thank you sou much @joaomoreno @sean-mcmanus
