### ISSUE TITLE
Crash after updating VS

### ISSUE THREAD

**Issue by thosanmaytinh** [Microsoft/vscode#47950]
Issue Type: <b>Bug</b>

Help to review.
1_ I click on menu update vs.
2_ I saw small popup tell me install now or not. I hit button No. I dont want update right now.
3_ I click on close to quit the Application.
4_ I meet issue cannot open VS.
Thank you and sorry for my bad english.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

**Comment by cwasp** [comment]
I have similar problem with the new v. 1.22.2 (Mac OS 10.12.6) and had to roll back to v. 1.22.1

**Comment by joaomoreno** [comment]
@thosanmaytinh What's the issue when you try to open VS Code?

**Comment by tHesTx** [comment]
My crashing occurs when I have 2 tabs with ".js" files opened(with split editor or not)
