### ISSUE TITLE
Multiple shells stop working properly

### ISSUE THREAD

**Issue by iruletheworld** [Microsoft/vscode#47952]
Issue Type: <b>Bug</b>

Hi, 

I just updated to the following version of VSCODE:

Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Before upgrade, I was using git bash with anacoda prompt as my shells with no problem. After the latest upgrade, git bash is no longer working as an integrated shell and I get a exit code "127" error.

The setting code worked before is the following:

    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",

    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",

    "terminal.integrated.shellArgs.windows":["/K", "C:\\ProgramData\\Anaconda3\\Scripts\\activate.bat C:\\ProgramData\\Anaconda3"
        
    ],

I then found out that, the latter "terminal.integrated.shell.windows" seems to overwrite the former one.

If I make the code as the following, then I could only have the cmd as my shell and no git bash (if I try add more shells, they would just be cmds):

     "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",

     "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|15.62GB (7.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
gitconfig|sid|1.0.1

</details>

**Comment by Tyriar** [comment]
This was never meant to work, you should use an extension if you switch shells a lot:

- https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
- https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals
