### ISSUE TITLE
关于jQuery，能否像Visual Studio 里面使用一样强大

### ISSUE THREAD

**Issue by hulang** [Microsoft/vscode#4796]
在使用Visual Studio 10+写js代码使用jQuery非常方便
目前需要扩展才能使用，能否不扩展，默认支持。。

**Comment by Tyriar** [comment]
I'm assuming this is talking about jQuery intellisense support, I think this would be best left up to an extension.

**Comment by egamma** [comment]
@hulang actually all you need is to install the jquery.d.ts from the definitly typed repository, pls see https://code.visualstudio.com/docs/languages/javascript#_snippets-for-javascript.
