### ISSUE TITLE
BUG: create new file on the file explorer Not working

### ISSUE THREAD

**Issue by NTPLThavarajan** [Microsoft/vscode#47965]
Issue Type: <b>Bug</b>

In the file explorer new file icon, new folder icon and 
the contextmenu new file  and new folder  are not even working

VS Code version: Code - Insiders 1.23.0-insider (dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b, 2018-04-16T05:17:45.591Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570T CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (1.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe .|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
https://www.github.com/Microsoft/vscode/issues/47937
