### ISSUE TITLE
VSCode not creating new file

### ISSUE THREAD

**Issue by Avsinacio** [Microsoft/vscode#47961]
Issue Type: <b>Bug</b>

I tried to create a new file and a new folder via right click and it didn't create neither.
Clicking on the the shortcut in the bar where it is the main folder's name didn't work either.

[https://imgur.com/5hb14hG](https://imgur.com/5hb14hG)

VS Code version: Code - Insiders 1.23.0-insider (dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b, 2018-04-16T05:17:45.591Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.36GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|1.0.3
Aurelia|beh|1.2.2
vscode-eslint|dba|1.4.8
code-beautifier|mic|2.0.3
debugger-for-chrome|msj|4.3.0
material-icon-theme|PKi|3.3.0

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/47937
