### ISSUE TITLE
Auto Update Failing

### ISSUE THREAD

**Issue by sosensible** [Microsoft/vscode#47977]
Issue Type: <b>Bug</b>

The requester said to send this log info.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|15.91GB (4.19GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.2
jenkins-status|ale|0.6.1
project-manager|ale|0.25.0
vscode-json|and|1.3.2
vscode-twig-pack|baj|1.0.0
gitignore|cod|0.5.0
git-extension-pack|don|0.1.3
githistory|don|0.4.0
gitlens|eam|8.2.1
restore-editors|eam|0.2.1
vscode-great-icons|emm|2.1.31
vscode-postman|eri|0.5.2
json-tools|eri|1.0.2
vscode-git-tags|how|1.3.1
rest-client|hum|0.18.1
jenkins-declarative-support|jmM|0.1.0
vscode-cflint|Kam|0.2.4
vscode-cfml|Kam|0.3.1
vscode-jira|Kni|0.6.0
dotenv|mik|1.0.1
mssql|ms-|1.3.1
vsliveshare|ms-|0.2.307
vscode-coldbox|ort|0.1.0
vscode-testbox|ort|0.1.1
vscode-code-outline|pat|0.1.0
git-merger|sha|0.4.1
slack|soz|0.0.14
cfml-comment-tags|trs|0.2.2
shell-launcher|Tyr|0.1.6
terminal-tabs|Tyr|0.1.1
vscode-todo-highlight|way|0.5.12
vscode-open-in-github|ziy|1.3.1

</details>

The popup said to send you this log info.

Apr 16 11:28:02.557 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
Apr 16 11:28:02.558 INFO Checking for running Code.exe processes... (attempt 1)
Apr 16 11:28:02.561 INFO Code.exe is running, wait a bit
Apr 16 11:28:03.061 INFO Checking for running Code.exe processes... (attempt 2)
Apr 16 11:28:03.064 INFO Code.exe is running, wait a bit
Apr 16 11:28:03.564 INFO Checking for running Code.exe processes... (attempt 3)
Apr 16 11:28:03.568 INFO Code.exe is running, wait a bit
Apr 16 11:28:04.070 INFO Checking for running Code.exe processes... (attempt 4)
Apr 16 11:28:04.073 INFO Code.exe is running, wait a bit
Apr 16 11:28:04.573 INFO Checking for running Code.exe processes... (attempt 5)
Apr 16 11:28:04.576 INFO Code.exe is running, wait a bit
Apr 16 11:28:05.076 INFO Checking for running Code.exe processes... (attempt 6)
Apr 16 11:28:05.079 INFO Code.exe is running, wait a bit
Apr 16 11:28:05.579 INFO Checking for running Code.exe processes... (attempt 7)
Apr 16 11:28:05.583 INFO Code.exe is running, wait a bit
Apr 16 11:28:06.083 INFO Checking for running Code.exe processes... (attempt 8)
Apr 16 11:28:06.086 INFO Code.exe is running, wait a bit
Apr 16 11:28:06.586 INFO Checking for running Code.exe processes... (attempt 9)
Apr 16 11:28:06.589 INFO Code.exe is running, wait a bit
Apr 16 11:28:07.089 INFO Checking for running Code.exe processes... (attempt 10)
Apr 16 11:28:07.092 INFO Code.exe is running, wait a bit
Apr 16 11:28:07.592 INFO Checking for running Code.exe processes... (attempt 11)
Apr 16 11:28:07.595 INFO Code.exe is running, wait a bit
Apr 16 11:28:08.095 INFO Checking for running Code.exe processes... (attempt 12)
Apr 16 11:28:08.098 INFO Code.exe is running, wait a bit
Apr 16 11:28:08.598 INFO Checking for running Code.exe processes... (attempt 13)
Apr 16 11:28:08.601 INFO Code.exe is running, wait a bit
Apr 16 11:28:09.101 INFO Checking for running Code.exe processes... (attempt 14)
Apr 16 11:28:09.104 INFO Code.exe is running, wait a bit
Apr 16 11:28:09.604 INFO Checking for running Code.exe processes... (attempt 15)
Apr 16 11:28:09.608 INFO Code.exe is running, wait a bit
Apr 16 11:28:10.108 INFO Checking for running Code.exe processes... (attempt 16)
Apr 16 11:28:10.112 INFO Code.exe is running, wait a bit
Apr 16 11:28:10.612 INFO Checking for running Code.exe processes... (attempt 17)
Apr 16 11:28:10.615 INFO Code.exe is running, wait a bit
Apr 16 11:28:11.115 INFO Checking for running Code.exe processes... (attempt 18)
Apr 16 11:28:11.118 INFO Code.exe is running, wait a bit
Apr 16 11:28:11.618 INFO Checking for running Code.exe processes... (attempt 19)
Apr 16 11:28:11.622 INFO Code.exe is running, wait a bit
Apr 16 11:28:12.122 INFO Checking for running Code.exe processes... (attempt 20)
Apr 16 11:28:12.125 INFO Gave up waiting for Code.exe to exit
Apr 16 11:28:31.417 ERRO Failed to get process file name

**Comment by ramya-rao-a** [comment]
Auto update of what is failing? VS Code or the extensions?

**Comment by sosensible** [comment]
Sorry, when VS Code restarts it announces it failed to update. It suggests
a reinstall of VS Code.
