### ISSUE TITLE
"Starting Visual Studio Code" window

### ISSUE THREAD

**Issue by UWbadgers16** [Microsoft/vscode#47973]
- VSCode Version: 1.22.2
- OS Version: Ubuntu Mate 16.04

Steps to Reproduce:

1. Open Visual Studio Code
2. Instance of "Starting Visual Studio Code" starts alongside Visual Studio Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Can you provide a screenshot?

**Comment by UWbadgers16** [comment]
![](https://i.imgur.com/ClWGuo3.png)

**Comment by Tyriar** [comment]
I've seen this before, I think it's the display manager though. Will keep tracking other reports.
