### ISSUE TITLE
An unknown error has occurred

### ISSUE THREAD

**Issue by zh-ngk-i** [Microsoft/vscode#47970]
Issue Type: <b>Bug</b>

When I enter any character in the search box of the extension store, the bottom right corner of the character prompts "An unknown error has occurred"

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 1903)|
|Load (avg)|1, 1, 1|
|Memory (System)|5.51GB (1.21GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.22.0
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0

</details>

**Comment by ramya-rao-a** [comment]
Can you provide a screenshot for when this happens?
Also share any errors from Help -> Toggle Developer Console -> Console
