### ISSUE TITLE
[bug] Code collapsing not based on indent not working

### ISSUE THREAD

**Issue by TheDutchCoder** [Microsoft/vscode#47979]
- VSCode Version: 1.22.2
- OS Version: High Sierra 10.13.4

Steps to Reproduce:

1. Copy code from screenshot example
2. Hover in the gutter to see the collapse mark in the wrong place

Does this issue occur when all extensions are disabled?: Yes

### Clarification
The latest version of VScode is supposed to have collapsing markup based on actual markup and not indentation, but that doesn't seem to be the case.

### Screenshot
![image](https://user-images.githubusercontent.com/1668207/38820736-aefff37a-416c-11e8-8db0-6c625d34e500.png)

**Comment by mjbvz** [comment]
This feature was disable by default in master due to a important bugs. Set `"typescript.experimental.syntaxFolding": true` to re-enable it. However jsx folding will not work due to https://github.com/Microsoft/TypeScript/issues/23273
