### ISSUE TITLE
Word Wrap isn't working on very long lines.

### ISSUE THREAD

**Issue by henry-kr** [Microsoft/vscode#4797]
- VSCode Version: .10.11
- OS Version: Win 8 (6.1.7601)

Steps to Reproduce:

1. open a .txt file where the lines are wrapping.  The lines are very long (between 1,000 chars and 1,500 chars).
2. click on toggle word wrap.  you'll see nothing happens whereas I'd expect the wrapping to stop happening.

**Comment by alexandrudima** [comment]
This is caused by some performance protection code the editor has. If a file is "dominated by long lines", then word wrapping is always chosen. You can use the `editor.wrappingColumn` setting and use a large number to force no wrapping.

**Comment by holzbrenner** [comment]
Using large number in `editor.wrappingColumn` doesn't work. If I use a large number (above 300; e.g. 1000 or 30000) for this setting, lines are always wrapped and `Alt+Z` (or menu/palette command) doesn't do anything. I think that the problem occurs if you have lines longer than 300 characters in the file you're editing (300 is the default `editor.wrappingColumn` setting). Whatever setting (above 300) I use here, I can't unwrap lines once they're wrapped.

The only thing which partially works is `"editor.wrappingColumn": -1` (I think this setting means "never wrap"). In this case, lines (including very long lines) are always unwrapped when you start the editor, but as soon as you wrap them, they usually remain wrapped (that is, `Alt+Z` only works the first time, to wrap the lines from the initial, unwrapped state). In some cases, you can unwrap them again, but any lines longer than 300 characters remain wrapped at column 300. I would say that this default number (300) is still somehow involved somewhere.

The version I'm using is 0.10.11 and all this is easy to reproduce. I'm using VSCode for making manual edits of some generated scripts with very long lines and would be quite happy to have the ability to wrap and unwrap lines with 500+ characters. Another use case would be viewing and searching log files which often have very long lines (with VSCode you can open, view and search entire directory tree of such log files).

**Comment by alexandrudima** [comment]
@bpasero For verification please open a file dominated by long lines and toggle word wrap.
