### ISSUE TITLE
Line Markers

### ISSUE THREAD

**Issue by nove1398** [Microsoft/vscode#47986]
I see line markers in javascript but not for css files. That would be a really good feature.

**Comment by ramya-rao-a** [comment]
Can you elaborate on what you mean by "line markers"? A screenshot would help

**Comment by nove1398** [comment]
![vsc](https://user-images.githubusercontent.com/2650410/39054395-26c97464-4477-11e8-805d-f2f91ae8f123.jpg)
That red dot in the screen shot, it is not available when editing certain file types, like CSS

**Comment by ramya-rao-a** [comment]
The red dot represents breakpoints used during debugging which is not applicable for CSS files and so are not available there.
