### ISSUE TITLE
double-width characters alignment issue

### ISSUE THREAD

**Issue by ryenus** [Microsoft/vscode#47983]
- VSCode Version: 1.22.2
- OS Version: macOS 10.13.4
- Font Family: Consolas, Microsoft YaHei
- Editor/Terminal Font Size: 14

In terms of font/text rendering, the main editor is apparently different from the integrated terminal, the screenshot is about the same file opened in the main editor and the integrated terminal using vim at the same time, there're several issues here:

1. double-width character alignment is different, the main editor cannot correctly align, or slightly narrower.
2. it seems the Chinese characters are not strictly rendered as double-width, maybe that's a problem with the actual font, but at least this is done right in the integrated terminal.
3. though the font size of both the editor and the integrated terminal are set to `14`, the text in the terminal seems smaller, at least the height is smaller, causing a little bit at the top of the Chinese characters missing.

<img src="https://user-images.githubusercontent.com/610161/38822860-4b4f04b8-41d7-11e8-9088-7cc83a401315.png" width="100%"/>

**Comment by alexandrudima** [comment]
@ryenus Perhaps try with a font that renders wide characters as 2 latin characters e.g. Inconsolata

**Comment by ryenus** [comment]
Indeed, the alignment is correct with Inconsolata, so Consolas seems to be the culprit?

<img width="513" alt="image" src="https://user-images.githubusercontent.com/610161/38904165-6b1fc9bc-42db-11e8-8626-8754b224efb4.png">

**Comment by alexandrudima** [comment]
The terminal and the editor have different rendering implementations. I think the terminal will always try to render wide characters in the space of two latin characters, but in the editor, we end up rendering the characters with the width specified by the font itself (by using Chromium's font rendering).

**Comment by alexandrudima** [comment]
unfortunately not at this time. The only solution is to use a different font than Consolas. The reason is that in the editor we want to be able to render RTL text, bi-di text, complex scripts, etc.

**Comment by yinrong** [comment]
This is a serious problem. what's the fix now??
![image](https://user-images.githubusercontent.com/4221569/152473614-fce5e818-fbc2-4715-8506-e5cf83da7e7c.png)

**Comment by yinrong** [comment]
> unfortunately not at this time. The only solution is to use a different font than Consolas. The reason is that in the editor we want to be able to render RTL text, bi-di text, complex scripts, etc.

render wide chars as width=2 is a unified behavior. Could vscode respect this?
