### ISSUE TITLE
infer recursive type (Typescript)

### ISSUE THREAD

**Issue by MikkelSnitker** [Microsoft/vscode#47984]
Hi. 
I'm not sure if this is a bug/feature in vscode or in typescript, but recursive types resolves to any?
Giving the code below TestType3 resolves to: 

```TypeScript Type<{prop1: Type<String>,prop2: Type<any>}>``` 
and not as i expected
```TypeScript Type<{prop1: Type<String>,prop2: Type<{subprop: Type<String>}>```

I'm not sure if this is a typescript issue, but the compiler catches the error if prop2 does not contain a string property with the name subprop.
```TypeScript
type Constructor<T> = { new(...args: any[]): T }
type Type<T> = T & { validate?: (value:any)=>boolean};
type InferTest<T> = T extends Constructor<infer T1> ? Type<T1>: 
T extends Array<Constructor<infer T1>> ? Array<Type<T1>>:
Type<{[K in keyof T]: InferTest<T[K]> }> 

declare function Test1<T>(o: T): InferTest<T>;

const TestType1 = Test1(Number) // Type<Number>;
const TestType2 = Test1([Number]) // Type<Number>[];
const TestType3 = Test1({
    prop1: String,
    prop2: {
        subprop: String
    }
}) // Type<{prop1: Type<String>,prop2: Type<any>}> 

var test4: typeof TestType3 = {
    prop1: "Hello World!",
    prop2: { 
        subprop: 4 
    }
}
```

- VSCode Version: 1.22.1
- OS Version: 10.13.3

Does this issue occur when all extensions are disabled?: Yes

Regards Mikkel

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23433
