### ISSUE TITLE
Intellisense and problem highlighting(Red line under code) stopped working

### ISSUE THREAD

**Issue by Sarvjeetkaur** [Microsoft/vscode#47980]
Issue Type: <b>Bug</b>

Intellisense and problem highlighting(Red line under code) in VS Code IDE stopped working. If anyone have solution please advice me. 

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment]
Does this happen when you disable all extensions? What language are you using?

**Comment by Sarvjeetkaur** [comment]
I am using C# language. I did not disable  any extension  after my computer restarted it stopped working.

**Comment by mjbvz** [comment]
Please report this against the C# extension if you see it again

**Comment by joaquintoral** [comment]
Same thing is happening on my end.
