### ISSUE TITLE
[C#] typing a period in a triple-slash (XML-doc) comment opens auto-complete popup

### ISSUE THREAD

**Issue by chronicgamedev** [Microsoft/vscode#47993]
- VSCode Version:
Version 1.23.0-insider
Commit dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b
Date 2018-04-16T05:17:45.591Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

- OS Version:
Windows 10 64

Steps to Reproduce:

1.  Open a .cs file in vscode
2.  enter a comment line beginning with a triple slash: ///
3.  end the comment with a period

![vs-code-xml-comment-auto-complete-bug](https://user-images.githubusercontent.com/22398672/38829493-10ff4304-416e-11e8-970c-d4ba437448dc.png)

observed:
the autocomplete window opens and pressing the spacebar inserts the suggested text

expected:
typing a period and then space bar in a comment results in a period and a space.  Note that the bug does not occur with an double slash comment, only with a triple-slash comment.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Please log this issue in the repo for the C# extension that you are using which provides the completions
