### ISSUE TITLE
How do I disable hints?

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#47998]
VSC v1.22 added support for hints:

<img width="98" alt="screen shot 2018-04-16 at 22 07 18" src="https://user-images.githubusercontent.com/1812093/38832360-9eb06e54-41c2-11e8-9fb3-23957c0f4c98.png">

The release notes says:

> However, some users might not want to display hints in the editor so also include support for disabling them.

You guessed it right. How do I disable hints? I see no options whatsoever for this.

**Comment by mjbvz** [comment]
`"javascript.suggestionActions.enabled": false` from https://code.visualstudio.com/updates/v1_22#_suggestion-code-actions-for-javascript-and-typescript
