### ISSUE TITLE
Regular Expressions in Replace-window

### ISSUE THREAD

**Issue by KargJonas** [Microsoft/vscode#47996]
Allow to use regular expressions in "Replace" (Ctrl + H) window for complex, code modification.

**Comment by roblourens** [comment]
It is allowed. You just have to toggle it on with the `.*` button:

![image](https://user-images.githubusercontent.com/323878/38847073-9d0c6412-41b4-11e8-832f-8fbf64b882c0.png)

**Comment by Agarwal-Nikhil** [comment]
@roblourens The question is about replace window and not find window. I have the same issue. See #50306
