### ISSUE TITLE
Integrated terminal eats character next to emoji

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#47999]
Issue Type: <b>Bug</b>

Any emoji printed will eat the next character (they will overlay). The cursor is technically still in the right place, but then appears shifted one character.

Content of the shell:
```
✔ ~
> echo 1234🍺56789
1234🍺56789
✔ ~
> echo 1234🍺56789
```

![image](https://user-images.githubusercontent.com/10532611/38833071-558d28c8-4179-11e8-96d7-2f328db3b403.png)

macOS terminal (correct behaviour):

![image](https://user-images.githubusercontent.com/10532611/38833131-83a64be0-4179-11e8-81f2-f0dbabf46432.png)

This issue has been around for a while but I only now got around to file it.

It's especially annoying if your prompt character is an emoji because it will always eat the first character of every command.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-commitizen|Kni|0.5.0
vscode-docker|Pet|0.0.26
vscode-wakatime|Wak|1.2.0
html-css-class-completion|Zig|1.17.1
vscode-base64|ada|0.0.1
yaml|ada|0.0.9
vscode-icontheme-nomo-dark|be5|1.3.5
emojisense|bie|0.4.0
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.0
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
vscode-solution-explorer|fer|0.2.11
svg|joc|0.1.0
docthis|joe|0.6.0
graphql-for-vscode|kum|1.10.0
Go|luk|0.6.79-beta.1
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
vscode-kubernetes-tools|ms-|0.1.7
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.3.0
java|red|0.22.0
vscode-yaml|red|0.0.11
vscode-coverage-gutters|rya|1.3.1
vscode-nginx|sha|0.5.0
sourcegraph|sou|1.0.10
rewrap|stk|1.8.1
msbuild-project-tools|tin|0.2.33
gitblame|wad|2.4.2
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by bluenex** [comment]
I'm so happy to find out that I'm not alone 😬

**Comment by kvrmd** [comment]
This isn't just in the terminal. This is the same with any font I use. However it looks better with larger font-sizes.

![image](https://user-images.githubusercontent.com/24406097/39032944-91e16a66-4424-11e8-8140-52a4831eb708.png)

![image](https://user-images.githubusercontent.com/24406097/39032965-b497fb6a-4424-11e8-96c2-8ed9fab3adf1.png)

**Comment by Tyriar** [comment]
Tracked in https://github.com/xtermjs/xterm.js/issues/1059
