### ISSUE TITLE
Folder-level settings in a multi-root environment are unusable

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#47995]
_If there is already an issue about this I wasn't able to find it_

I have a folder/project inside a multi-workspace VSC window, this folder/project needs to provide a setting for an extension that it uses. Opening its `.vscode/settings.json` I see:

<img width="443" alt="screen shot 2018-04-16 at 21 17 47" src="https://user-images.githubusercontent.com/1812093/38830158-a4844028-41bb-11e8-95c9-bad59749ad1e.png">

Sounds alright. I've added the setting and now I see:

<img width="530" alt="bug" src="https://user-images.githubusercontent.com/1812093/38830320-360d08b8-41bc-11e8-8ec2-f272d9c57040.png">

What does this even mean?

For what reason isn't the configuration object constructed like this?:

```
config = merge ( globalConfig, userConfig, workspaceConfig, rootConfig (this should change depending on which file I currently have the focus on) )
```

Unless I'm missing something obvious this seems **badly** broken to me, I basically can't use multi-root workspaces if I need to provide folder/project-specific settings to extensions, which is something I do need.

**Comment by ramya-rao-a** [comment]
Please read https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings

If you want to provide folder/project-specific changes to settings from an extension, please log an issue in the repo for the said extension to make those settings resource specific.

**Comment by fabiospampinato** [comment]
@ramya-rao-a Thanks for the reply. I wrote the extension in question, and I see no mention on how to mark a setting as a "resource" setting in the link you provided, nor [here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration), where is this documented?

**Comment by ramya-rao-a** [comment]
@fabiospampinato  Its here: https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#settings

@gregvanl The above is linked only from [Sept 2017 Release Notes](https://code.visualstudio.com/updates/v1_17#_multi-root-guide-for-extension-authors). We should probably link it from other docs as well.

**Comment by fabiospampinato** [comment]
@ramya-rao-a Thanks for the link. I think every piece of information that's written in there should also be available in the [docs](https://code.visualstudio.com/docs), otherwise what's the point of having docs if they only provide partial documentation.

**Comment by gregvanl** [comment]
There is a link under https://code.visualstudio.com/docs/editor/multi-root-workspaces#_extensions for extension authors. The wiki is mostly for migration (a one time event) but we'll look into porting any missing content into the main docs.

**Comment by fabiospampinato** [comment]
@gregvanl I think a link under "User Guide" would be hard to find for extensions developers, I would expect to find that info under "Extensibility Reference" instead.
