### ISSUE TITLE
Slow behavior after transiting betwen workspaces

### ISSUE THREAD

**Issue by alvaropfn** [Microsoft/vscode#47997]
Issue Type: <b>Bug</b>

* use two or more workspaces windows 10
* open vscode
* install the Live Server extension
* start a project with a simple html, css, javascript files
* start programing any thing and go to other workspace to see your results  and get back some times
* some slowness will be detectable when you try to scroll up and down in your project with the touchpad

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.87GB (8.30GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\alvar\Workspace\playground\Dart|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.2
vagrant|bbe|0.5.0
dart-code|Dar|2.11.2
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
code-runner|for|0.9.3
beautify|Hoo|1.3.0
Angular2|joh|2.16.1
restructuredtext|lex|58.0.0
python|ms-|2018.3.1
debugger-for-chrome|msj|4.3.0
material-icon-theme|PKi|3.3.0
LiveServer|rit|3.2.1

(1 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
@alvaropfn This seem to be caused by the Live Server extension itself. Please log the issue in the repo for the Live Server extension first. If there it is determined that the problem is indeed with the core, we can take a look then.
