### ISSUE TITLE
add cusor bug: ctrl+alt+up/down conflict with windows shortcut.

### ISSUE THREAD

**Issue by fish520** [Microsoft/vscode#480]
As mentioned in the title, the add cursor shortcut conflict with the windows shortcut to flip screen Since I'v updated my os to windows 10 th2 pro, all is ok when I was using the family version.

**Comment by alexandrudima** [comment]
@fish520 

AFAIK these keybindings are "stolen" at a very low level by some display driver: http://superuser.com/questions/279756/how-to-disable-the-screen-orientation-hotkeys-in-windows-xp

So you can:
* disable the hot keys from your display driver if you don't use them;
* or change the VSCode keyboard shortcuts for add cursors (e.g. binding them to `Ctrl`+`Arrow`):
```
{ "key": "ctrl+up",           "command": "editor.action.insertCursorAbove",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+down",         "command": "editor.action.insertCursorBelow",
                                     "when": "editorTextFocus" },
```

**Comment by fish520** [comment]
got it, thanks.
