### ISSUE TITLE
Cursor jumps to the end of the file while editing HTML

### ISSUE THREAD

**Issue by Tusshu** [Microsoft/vscode#48002]
- VSCode Version:1.22.2
- OS Version:macOS High Sierra version 10.13.4

Steps to Reproduce:

1. Create HTML file and start typing
2.Move cursor in middle of file and edit text

Does this issue occur when all extensions are disabled?: No

**Comment by ramya-rao-a** [comment]
- Do you have either formatOnSave or formatOnType enabled?
- Does this happen with formatOnSave and formatOnType disabled?
- Does this happen when you run code without extensions? Run `code --disable-extensions`?
- Does this happen in the previous version of VS Code (https://code.visualstudio.com/updates/v1_21)?

**Comment by Tusshu** [comment]
code --disable-extensions  works fine. So I removed some HTML related extensions and ran code normally. The problem seems to disappear.
Thanks for your feedback.
