### ISSUE TITLE
VS Code Update install fail

### ISSUE THREAD

**Issue by SwingCoder911** [Microsoft/vscode#48000]
- VSCode Version: 1.22.1.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open visual studio code
2. Click gear at the bottom left
3. Click "install updates"
4. Click "Update vs code" popup at the bottom right

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1917140/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
Did you attempt to start Code while the update was running?

**Comment by mrchief** [comment]
I had the same issue on my Windows PC. For me, there were background Code processes which refused to shutdown. After manually killing them, and running the latest installer (not from within vscode), the update succeeded.
