### ISSUE TITLE
Extensions broke by themself after a while

### ISSUE THREAD

**Issue by mstfymrtc** [Microsoft/vscode#48003]
Some of the extensions I use with VSCode are disabled after a while by themself while I use VSCode.
For instance, Prettier and React-native/react/Redux snippets for ES6/ES7 broke continously.

Installed extensions:
![xx](https://user-images.githubusercontent.com/5208454/38834364-efd08fcc-41d0-11e8-9494-fe9b6087cd9a.jpg)
- VSCode Version: 1.22.2
- OS Version: Windows 10
Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment]
You can see built-in extensions by clicking `...` in the extensions view and click on `Show Built-in Extensions`.

May I know how are you getting into this state and are there any steps you follow to reproduce this?

**Comment by sandy081** [comment]
What do you mean extensions broke automatically? Do they get disabled without reloading the window?
