### ISSUE TITLE
Support strict-null in monaco.d.ts

### ISSUE THREAD

**Issue by nikeee** [Microsoft/vscode#48006]
- VSCode Version: Current master branch

I am developing an application that relies on Monaco and have the `strictNullChecks` tsc-flag enabled.
When implementing a `HoverProvider`, for example, [this interface](https://github.com/Microsoft/vscode/blob/3a14fde91d1fd0b3060b9eefb0780dd8d8b80e18/src/vs/editor/common/modes.ts#L236-L247) has to be implemented:

```
export interface HoverProvider {
	/**
	 * Provide a hover for the given position and document. Multiple hovers at the same
	 * position will be merged by the editor. A hover can have a range which defaults
	 * to the word range at the position when omitted.
	 */
	provideHover(model: model.ITextModel, position: Position, token: CancellationToken): Hover | Thenable<Hover>;
}
```

This is fine, except that I cannot return nothing (`null` or `undefined`), since the compiler gives me an error about that. This problem exists on other providers as well. Some are not affected since they require to return an array, that may just be empty. When looking at the calls to `provideHover`, the return value always seems get checked if it exists.

The language server protocol has a [very similar API](https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/main.ts#L1165-L1170) for this (the second type parameter specifies the return type):
```
	/**
	 * Installs a handler for the `Hover` request.
	 *
	 * @param handler The corresponding handler.
	 */
onHover(handler: RequestHandler<TextDocumentPositionParams, Hover | undefined | null, void>): void;
```
One can return `null` or `undefined` in this API.

Is there just missing `| null | undefined` on some return values or was it intentionally made different?

**Comment by jrieken** [comment]
We do the same of the extension API which defines a `ProviderResult`. The *monaco*-api isn't using strict-null-checks because it originates from our own compile which doesn't use strict-null. While we can add the `ProviderResult`-type it is unlikely that we'll become strict-null correct with that API.

**Comment by alexandrudima** [comment]
We are now using `ProviderResult` in `monaco.d.ts`.
