### ISSUE TITLE
Cannot create new file in the VS Code Explorer

### ISSUE THREAD

**Issue by BitwiseGuy** [Microsoft/vscode#48005]
Creating a new file appears to have broken in the latest build. Unable to create a file anywhere in a project's folder structure while in VS Code. If you create the file in File Explorer it shows up in the VS Code Explorer, but unable to create directly in VS Code.

**Comment by pharrisee** [comment]
Strangely, this was fixed on my Linux box in work but is still broken on my Windows 10 box at home.

As previously reported creation of files and directories fails when using the right click and option header icon methods.  You can still create a newfile/dir by using the File>New menu item, or pressing Ctrl-N.

![capture](https://user-images.githubusercontent.com/121816/38839674-bab7675e-41d3-11e8-9946-05680076ce56.PNG)

**Comment by BitwiseGuy** [comment]
File>New doesn’t work for me. It creates a new file tab, but no way to name it and it doesn’t show up on the file structure.

**Comment by pharrisee** [comment]
@BitwiseGuy You can name it by subsequently saving the file (even an empty one)

**Comment by Tylertron1998** [comment]
I also have this issue

**Comment by LouieK22** [comment]
Yep, this issue is getting quite annoying now.
