### ISSUE TITLE
code command not working in macos

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#48009]
- VSCode Version: 1.22
- OS Version: macOS High Sierra 10.13

Steps to Reproduce:

1. Open VS Code
2. Close VS Code (CMD+Q)
3. Try to re-open VS Code via command prompt `code`
4. nothing happens

Does this issue occur when all extensions are disabled?: Yes

There is no output when running `code --verbose --disable-extensions`.

This seems to be since the latest update.  I manually downloaded and replaced the installed version, during troubleshooting, I removed `~/.vscode` and `~/Library/Application\ Support/Code` .. doesn't seem to help the issue.

It will launch from Finder in the Applications directory, but not via the command prompt... even manually running the following isn't working...

```
ELECTRON_RUN_AS_NODE=1 /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/cli.js
```

----

Okay, I have no idea how/why but it seems to be working now... I did try `. code ./` ... which did launch once, but not again, and now it seems to be working normally... I'm not sure if this will re-present itself, but it's weird to say the least.  It's now running `1.22.2`, so not sure if this was an update to fix a prior bug that was quickly done.

**Comment by bcbcarl** [comment]
@tracker1 Have you tried to uninstall 'code' command and install it again?

See [Launching from the Command Line][launching-from-the-command-line] for more info.

[launching-from-the-command-line]: https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

**Comment by ramya-rao-a** [comment]
@tracker1 Closing this issue for now, as the issue seems to be resolved for you in 1.22.2
If you see this re-surfacing, feel free to re-open this issue

**Comment by tracker1** [comment]
Please re-open...

In the office, we have a paired workstation with 4K displays...  when I am connected/disconnected from that dock on my mac, it's like VS Code's UI thread crashes...  and the behavior re-surfaces unless I kill all VS Code tasks, or open via the `Visual Studio Code.app` icon via finder (or the dock).

The `code` command at the terminal just doesn't run.  VS Code seems to be the only app that does this, by reference, Chrome doesn't.  I'm not sure if there is code in chrome to deal with this, but it's a tough bug.  Chrome does sometimes wind up with windows pinned over the screen edges though.  But there's no UI indication either in the dock, or on screen showing any displays actually open.

For reference, I run the following to kill all code instances.

```bash
ps -A | grep Visual\ Studio\ Code | awk '{print $1}' | xargs kill -9
```

**Comment by bpasero** [comment]
@tracker1 maybe some environment variable you have causes this. Can you run it from the terminal like this: `env -i ./Visual\ Studio\ Code - Insiders.app/Contents/MacOS/Electron`

**Comment by tracker1** [comment]
@bpasero won't be able to get to it until weds... I'm away from work (moving) and won't be back in the office until then.   Doesn't happen on my personal macbook, but I don't use that as much, or in the same ways.

**Comment by bpasero** [comment]
@tracker1 ping

**Comment by tracker1** [comment]
Haven't seen the issue in a few weeks, should be safe to close.
