### ISSUE TITLE
无法创建文件夹

### ISSUE THREAD

**Issue by SpanielMan** [Microsoft/vscode#48017]
Issue Type: <b>Feature Request</b>

无法创建文件夹，请您尽快帮我解决一下，谢谢

VS Code version: Code - Insiders 1.23.0-insider (dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b, 2018-04-16T05:17:45.591Z)
OS version: Windows_NT x64 6.1.7601

**Comment by MaleDong** [comment]
Can you write your steps to re-produce this issue in English?

**Comment by NateLing** [comment]
fixed already, check and update your vscode.

**Comment by SpanielMan** [comment]
Thank you for your reply.It's the reason of the version. I have solved it. Thank you.
