### ISSUE TITLE
Git bash in integrated terminal line height issue

### ISSUE THREAD

**Issue by jaywick** [Microsoft/vscode#48010]
Issue Type: <b>Bug</b>

Git bash in my integrated terminal handles wrapped lines strangely. It seemingly adds a new line (see screenshot)

![image](https://user-images.githubusercontent.com/3955052/38841262-ef3f923c-4226-11e8-880a-6a8287585226.png)

<details>
<summary>User Settings</summary>

```json
{
    "workbench.colorTheme": "Gloom",
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontFamily": "Hasklig",
    "editor.fontLigatures": true,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "terminal.external.windowsExec": "C:\\Program Files\\Git\\git-bash.exe",
    "npm.packageManager": "yarn",
    "npm.autoDetect": "off",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "yarn.runInTerminal": true,
    "editor.minimap.renderCharacters": false,
    "window.zoomLevel": 0,
    "editor.lineHeight": 20,
    "javascript.referencesCodeLens.enabled": true,
    "extensions.ignoreRecommendations": true,
    "git.confirmSync": false,
    "explorer.openEditors.visible": 0,
    "git.enableSmartCommit": true,
    "explorer.confirmDelete": false,
    "editor.smoothScrolling": true,
    "html.autoClosingTags": true,
    "files.associations": {
        "*.js": "javascriptreact"
    },
}
```
</details>

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|15.82GB (9.22GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-yarn-script|car|0.0.1
LogFileHighlighter|emi|2.2.0
vscode-yarn|gam|1.6.0
debugger-for-chrome|msj|4.3.0
vscode-subword-navigation|ow|1.2.0
material-icon-theme|PKi|3.3.0
vscode-autohotkey|sle|0.2.2

(1 theme extensions excluded)

</details>

**Comment by jaywick** [comment]
Sorry @vscodebot, it's not related

**Comment by Tyriar** [comment]
I think this is caused by winpty's emulation, tracking in https://github.com/Microsoft/vscode/issues/45693
