### ISSUE TITLE
Please reply as soon as possible - very bad bug

### ISSUE THREAD

**Issue by Tylertron1998** [Microsoft/vscode#48014]
Issue Type: <b>Bug</b>

Can't create files or folders - only way is to do File => Create New File, then saving the file in the location I want.

VS Code version: Code - Insiders 1.23.0-insider (dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b, 2018-04-16T05:17:45.591Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 3991)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (11.40GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
klasa-vscode|bdi|0.2.2
vscode-eslint|dba|1.4.8
discord-vscode|icr|2.2.4
vsliveshare|ms-|0.2.307

</details>

**Comment by Tyriar** [comment]
This is fixed in today's build
