### ISSUE TITLE
Express4 not workable from "/bin/www" but "/bin/www.js"

### ISSUE THREAD

**Issue by wcchh** [Microsoft/vscode#48013]
- VSCode Version: 1.22.1, 1.22.2
- OS Version: Ubunto16

Steps to Reproduce:

1. Create Express4 javascript project
2. Add launch.json
4. Run and Abort!

Does this issue occur when all extensions are disabled?: Yes

It will be workable if we duplicate the file from "www" to "www.js" and update the launch.json.
At launch.json :
		{
			"type": "node",
			"request": "launch",
			"name": "啟動程式",
			"program": "${workspaceFolder}/bin/www.js"
		}

**Comment by weinand** [comment]
@roblourens I've fixed that for legacy with commit 34741ac452acd47babb805288d8a63585ed33699
