### ISSUE TITLE
Pythong F5 is slower

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/vscode#48011]
Issue Type: <b>Bug</b>

It takes much longer to do Pythong F5 to first breakpoint, it takes a full 5 seconds to even see this command line appear in the Terminal window (on a very powerful desktop PC):

PS D:\temp\ELL\build\tools\importers\CNTK\test> cd 'd:\temp\ELL\build\tools\importers\CNTK\test'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'python' 'C:\Users\clovett\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_launcher.py' 'd:\temp\ELL\build\tools\importers\CNTK\test' '2848' '34806ad9-833a-4524-8cd6-18ca4aa74f14' 'RedirectOutput,RedirectOutput' 'd:\temp\ELL\build\tools\importers\CNTK\test\cntk_to_ell_importer_test.py'

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17133

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 2095)|
|Memory (System)|31.92GB (17.41GB free)|
|Process Argv|d:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
python|ms-|2018.3.1
azurecli|ms-|0.4.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
code-spell-checker|str|1.6.7
vscode-arduino|vsc|0.2.12

</details>

**Comment by weinand** [comment]
Hi Chris, I've will move this issue to the python extension's repository.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#1412
