### ISSUE TITLE
Allow autosuggest the importing of .html files in VSCode when using TypeScript

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#48025]
- VSCode Version: 1.22.2
- OS Version: macOS Sierra

Steps to Reproduce:

1. Try to import an html file (e.g. import blah from './blah.html')
2. There is no autosuggest

```
declare module '*.html' {
    const value: string;
    export default value
}
```

Also, the file is not checked against its path so I don't know if its correct or not (probably a TS issue)

**Comment by mjbvz** [comment]
Closing this as an upstream TypeScript issue
