### ISSUE TITLE
the file will not be displayed in the editor because it is either binary

### ISSUE THREAD

**Issue by gabriel216** [Microsoft/vscode#48026]
Issue Type: <b>Bug</b>

the file will not be displayed in the editor because it is either binary. Why it's happen? because in my before version it was working correctly

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz (4 x 2095)|
|Memory (System)|3.91GB (0.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
@gabriel216 the file possibly contains a 0-byte character and we think it is binary or it is using UTF-16. Can you share it?
