### ISSUE TITLE
[feature request]pwd for new split terminal

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#48027]
- VSCode Version: 1.22.2
- OS Version: Ubuntu

Steps to Reproduce:

1. Open terminal, cd to some random dir
2. `Ctrl+\` the pwd of new split terminal is not that random dir.

If there is a new command of split terminal that keep the pwd of the recent used terminal, then I will bind it to a hot key `Ctrl+Shift+\`, and the world will be more peaceful :rocket:

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/48447
