### ISSUE TITLE
JsDoc @this Doesn't work for callback function

### ISSUE THREAD

**Issue by Cow258** [Microsoft/vscode#48021]
I am doing a class library and some function like jQuery.each().  
  
I am trying to define [this] in callback function.  

But it doesn't work...  
  
### Input code

```js
/** 
 * @this {Car} 
 * @type {function(Car):boolean} 
 */
var callback_tips = function () { }
var Cars = [];
class Car {
    constructor(name) { this.name = name; this.x = 0; }
    Forward(step) { this.x += step; }
    
    /** @param {callback_tips} callback */
    static Each(callback) {
        for (let car of Cars) { callback.apply(car, car); }
    }
}
(function main() {
    Cars = [new Car('A'), new Car('B'), new Car('C')];
    console.log(Cars);
    // <!-- BUG HERE
    Car.Each(function (car) { this.name += this.name; this.Forward(5); }); 
    // BUG HERE -->
    console.log(Cars);
})();
```

### Debug output

```js
[ Car { name: 'A', x: 0 }, Car { name: 'B', x: 0 }, Car { name: 'C', x: 0 } ]
[ Car { name: 'AA', x: 5 }, Car { name: 'BB', x: 5 }, Car { name: 'CC', x: 5 } ]
```

### JSDoc configuration

Default VSCode configuration

### Expected behavior
**Showing up tips about Car class when typing [this].**  
<img width="497" alt="vscode2" src="https://user-images.githubusercontent.com/14261588/38846381-a3a9680e-422e-11e8-8451-74ad8f161e6e.png">

### Current behavior
> Bug? callback -> this -> *:any .   
  
**Normal callback tips is working** . 
<img width="520" alt="vscode1" src="https://user-images.githubusercontent.com/14261588/38846371-9b8a2b5e-422e-11e8-8944-0393b102bc7a.png"> . 
**But [this] do not work** . 
<img width="497" alt="vscode2" src="https://user-images.githubusercontent.com/14261588/38846381-a3a9680e-422e-11e8-8451-74ad8f161e6e.png">

### My environment

| Software         | Version
| ---------------- | -------
| VSCode         |1.22 (March 2018)
| JSDoc            |???
| Node.js          |9.10.1
| npm              |5.6.0
| Operating system |MacOS 10.12.6

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23474
