### ISSUE TITLE
Punctuation leads to incorrect rendering in markdown when word wrapping is off

### ISSUE THREAD

**Issue by alexdevero** [Microsoft/vscode#48029]
This issue might be related. Punctuation sometimes causes wrong syntax rendering, or coloring. For example, dot (`.`) can cause that text in italic is rendered as plain text. This issue seems to occur when word wrapping is off.

With dot (`.`):
![md-bad](https://user-images.githubusercontent.com/4237724/38812147-c0215274-418b-11e8-9043-e94c6827d0cc.JPG)

Without dot (`.`):
![md-good](https://user-images.githubusercontent.com/4237724/38812138-b8666b0a-418b-11e8-95ed-0d42ef44c8ab.JPG)

- OS Version: Win 10 (1709)
- VSCode Version:
Version 1.23.0-insider
Commit dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b
Date 2018-04-16T05:17:45.591Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the source text from those screenshots

**Comment by alexdevero** [comment]
`*Side note: If you don't want to use the div element, you don't have to. Instead, you can use [React Fragment] to wrap all the components we want to render. Then, it is no longer necessary to use any redundant HTML element just because you need a wrapper. What will be rendered when we use React `Fragment`? Nothing. Or, the content of the `Fragment`, but without the `Fragment` or any other element. DOM will contain only the elements nested inside the `Fragment`. Let's do that and strip away that non-essential div element.*`

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#15

**Comment by mjbvz** [comment]
Should be fixed in the next insiders build

**Comment by alexdevero** [comment]
Thank you @mjbvz.
