### ISSUE TITLE
左侧"资源管理器"的不好体验

### ISSUE THREAD

**Issue by wanghairong-i** [Microsoft/vscode#48033]
Issue Type: <b>Bug</b>

当我关掉“打开的编辑器”后，我的项目名字会放到“资源管理器”的后面，如果左侧资源管理器展开的不够大就会造成以下问题：
当我打开了多个编辑器时，我如果想确定当前所在的是哪个项目时，我必须得扩大资源管理器的宽度才行，很不好的体验，还望重视，谢谢！

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.59GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_36873|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.1.1
vscode-eslint|dba|1.4.8
react-redux-react-router-snippets|dis|0.4.29
tslint|eg2|1.0.28
types-autoinstaller|jvi|2.3.1
sublime-keybindings|ms-|3.0.3
team|ms-|1.133.0
debugger-for-chrome|msj|4.3.0
tsimporter|pmn|1.2.14

(2 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
The root folder that is displayed in the title bar of VS Code as well. Are you referring to be able to view the immediate parent of the file opened in the current editor?

**Comment by MaleDong** [comment]
@wanghairong-i : Can you reproduce ths issue by using a video-recorder and submit it here with a zip file package?

**Comment by shizengzhou** [comment]
@wanghairong-i 在最新的insider版本中，已解决此问题。
![insider](https://user-images.githubusercontent.com/24318019/39026892-fa1cc438-4481-11e8-9f10-8d3aa5b7f164.png)
![version](https://user-images.githubusercontent.com/24318019/39026894-fd5990ae-4481-11e8-9713-0b937d87efa3.png)

**Comment by wanghairong-i** [comment]
![image](https://user-images.githubusercontent.com/13896347/39079485-5463c3ca-454e-11e8-83b1-37585e56caf6.png)

![image](https://user-images.githubusercontent.com/13896347/39079498-a70c0f42-454e-11e8-8922-89b7b66c26eb.png)

@ramya-rao-a  
@MaleDong 

I uploaded a picture to explain my problem
我上传了图片来说明我的问题

**Comment by wanghairong-i** [comment]
@shizengzhou 
The question you're talking about is not a problem I've met.
你说的这个问题不是我遇到的问题。

**Comment by shizengzhou** [comment]
@wanghairong-i 我知道你说的问题，你仔细看我传的图，我关闭了“打开的编辑器”，项目名“VSCODE”不会跑到资源管理器那，而是留在原来的位置

**Comment by wanghairong-i** [comment]
@shizengzhou 
My Chinese editor version is 1.22.2, which is now the latest version.
After the 1.23.0 version is released, I will verify it. Thank you!
我的中文版编辑器版本是 1.22.2，目前已是最新版本。
等1.23.0版本发布后，我会验证下，谢谢！

**Comment by shizengzhou** [comment]
@wanghairong-i 不好意思，是我搞错了，VS Code团队没有改变这里，是插件Gitlens造成的。当侧边栏中有2个以上的split-view时，关闭“打开的编辑器”，项目所在的那个split-view就会被保留。
![sidebar](https://user-images.githubusercontent.com/24318019/39082190-a304887e-4581-11e8-98c2-12c583561a35.png)

**Comment by wanghairong-i** [comment]
@shizengzhou 
 it doesn't matter. Then wait for the VS Code team to solve it.
了解了，没关系，那就等VS Code团队解决吧。

**Comment by bpasero** [comment]
@isidorn when I understand https://github.com/Microsoft/vscode/issues/48033#issuecomment-383260781 correctly, the complaint here is that we do not show the folder name fully when the available space is little in the view header.

**Comment by isidorn** [comment]
This is designed behavior as we give priority to showing actions titles.
Why should the name have priority, imho the actions are more important and the name can be arbiterarly long. Closing as designed
