### ISSUE TITLE
Open folder using URI from command line not working in V1.22.1

### ISSUE THREAD

**Issue by The-Experimentalist** [Microsoft/vscode#48036]
Issue Type: <b>Bug</b>

Opening a folder using the URL/URI from command line stopped working for me in version 1.22.1

This was working without issue in previous versions.

From the command line using this format:
<Install Path>\Code.exe  --open-url -- vscode://folder/_**Path to folder**_

e.g. 
"C:\Program Files\Microsoft VS Code\Code.exe" --open-url -- vscode://folder/C:\MyCode

As a work around I am using:
"**_Install Path_**\Code.exe" "**_Path to folder"_**

e.g. 
"C:\Program Files\Microsoft VS Code\Code.exe" "C:\MyCode"

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3475S CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|3.89GB (1.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --open-url -- vscode://folder/<Removed>
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
scad|efb|1.0.1
reg|ion|0.0.2
Runner|mat|0.1.14
mssql|ms-|1.3.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
st|rca|0.0.10
vscode-autohotkey|sle|0.2.2
StructuredText|Smo|0.1.1

</details>

**Comment by ramya-rao-a** [comment]
I just tried the same on my Windows 10 machine, and it works as expected.
Do you see any errors in the console?
Does code open at all (and it doesnt open using the given url) or nothing happens?

**Comment by The-Experimentalist** [comment]
Process Explorer info when using context menu:

![image](https://user-images.githubusercontent.com/9028834/38891909-a871d6d8-427d-11e8-87b2-7001b9ebb25d.png)

**Comment by The-Experimentalist** [comment]
Process Explorer info when using URI:

![image](https://user-images.githubusercontent.com/9028834/38891972-de6448fc-427d-11e8-83bd-9dbb672cdc6b.png)

**Comment by The-Experimentalist** [comment]
If i close all folders and then use the URI command in the second image I just get the welcome screen.

Before closing:
![image](https://user-images.githubusercontent.com/9028834/38892174-6939d01e-427e-11e8-95ac-d9e208ece060.png)

After opening:
![image](https://user-images.githubusercontent.com/9028834/38892203-7e7bdc2e-427e-11e8-9b43-a20ecf240204.png)

**Comment by ramya-rao-a** [comment]
My mistake, the folder I tried was the last folder that was opened in VS Code before I closed all instances of it, and so I didnt see any issues.

The documentation on [Opening VS Code with URLs](https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls) doesnt mention the use of "folder".  I tried using `vscode://folder` in 1.21, it doesnt work there either. You can use `vscode://file/` for folders though.

**Comment by joaomoreno** [comment]
Yes, you should be using `file`, not `folder`.

**Comment by The-Experimentalist** [comment]
Thanks for the info I think I must have had the same issue with the folder I tried was the last folder that was opened in VS Code before I closed all instances of it, and so I didn't see any issues, like ramya-rao-a above.
