### ISSUE TITLE
Fail to update vscode to latest version

### ISSUE THREAD

**Issue by froron** [Microsoft/vscode#48030]
I have version 1.22.1 of VSCode, on windows 10, and was trying to install the latest update.
Got an error with instructions to report the issue and attach the file I have attached.

Steps to Reproduce:
- Open visual studio code
- Click gear at the bottom left
- Click "install updates"
- Click "Update vs code" popup at the bottom right

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1918397/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
@froron Did an admin prompt come up at any point? Can you retry again and check what those `Code.exe` processes are doing (their full command line)?
