### ISSUE TITLE
Configure settings outwith user profile

### ISSUE THREAD

**Issue by alex7751** [Microsoft/vscode#48044]
Hi I am trying to get VS code put on our machines. Having some issues about configuring it.

I need to disable it from pining the updates server. Currently this needs to be done via the user settings, this means that every user would have to implement this. Is there a way this can be achieved form a settings file in its install directory.

Secondly is it possible to changes the plugin install location from $USER_HOME/.vscode to a custom location outwith the user profile.

**Comment by ramya-rao-a** [comment]
> Is there a way this can be achieved form a settings file in its install directory.

At present you can have User level and Workspace level settings. So if the same repo is being used in all the machines, adding a Workspace level setting can help.

> is it possible to changes the plugin install location from $USER_HOME/.vscode to a custom location outwith the user profile.

Try the `--user-data-dir` flag when running Code from the terminal

cc @sandy081 for more on settings and @joaomoreno for installation

**Comment by joaomoreno** [comment]
> I need to disable it from pining the updates server. Currently this needs to be done via the user settings, this means that every user would have to implement this. Is there a way this can be achieved form a settings file in its install directory.

Not currently possible. Although you can theoretically modify `product.json` and remove the following line from it:

> 	"updateUrl": "https://vscode-update.azurewebsites.net",
