### ISSUE TITLE
Unable to install themes using.vsix

### ISSUE THREAD

**Issue by thakurankit** [Microsoft/vscode#48040]
Due to some network restrictions i'm unable to install themes from the extensions tab in the editor, so for now i'm downloading the .vsix format from the marketplace and installing them manually , in most of themes I have tried it gives the error

![image](https://user-images.githubusercontent.com/34708279/38860307-8cd19e66-424d-11e8-88b2-639e1a2c5382.png)

VS Code:
![image](https://user-images.githubusercontent.com/34708279/38860356-a537b15c-424d-11e8-8037-6a508bd4e176.png)

OS: Windows 10 Pro.

Any suggestions?

**Comment by sandy081** [comment]
Looks like you have pretty old version of VS Code. Can you please update and try again?

**Comment by thakurankit** [comment]
Hey thanks, updating VS Code worked.
