### ISSUE TITLE
Word selection doesn't work as usual

### ISSUE THREAD

**Issue by JakubRimal** [Microsoft/vscode#48046]
Issue Type: <b>Bug</b>

VS Code works differently than it is common everywhere else if words are separated by some other character than space (e.g. with dot).

**Steps to reproduce**

1. Type few words separated by dots, e.g. `deep.object.property`.
1. Press and hold Ctrl + Shift together, then press Left Arrow key twice.

**Result (bug/unexpected behaviour)**

`.property` is selected.

**Expected result**

`object.property` is selected.

**Because of that:**

1. User has to press arrow key twice more to select words.
1. User is frustrated as it is different behaviour than user is used to.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 1975)|
|Load (avg)|1, 1, 1|
|Memory (System)|11.17GB (0.44GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.6.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.1
flow-for-vscode|flo|0.8.0
path-autocomplete|ion|1.9.0
docthis|joe|0.6.0
debugger-for-chrome|msj|4.3.0
ungit-tab|rv1|0.0.9
code-spell-checker|str|1.6.7
code-spell-checker-czech|str|0.1.0
local-history|xyz|1.6.2
markdown-all-in-one|yzh|1.1.2

</details>

**Comment by JakubRimal** [comment]
@alexandrudima Amazing, thanks! Just to be sure, does it solve both directions (I see that it looks like there already is a code for that in `moveWordRight` but in the current version of VS Code this problem is with both directions)?

**Comment by alexandrudima** [comment]
Yeah, I changed `moveWordRight` 12 days ago via 20e3ed229773b9fc3b478f0b5a565d485f75c59a and forgot to change `moveWordLeft` too. Your issue was a good reminder, so thanks for that!
