### ISSUE TITLE
Unable to format CSS code files

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/vscode#4804]
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Open any CSS file.
2. Press `Shift` + `Option` + `F`

**Comment by aeschli** [comment]
There is an extension for css formatting.

**Comment by jmurphzyo** [comment]
what about for scss?

**Comment by aeschli** [comment]
I haven't tried these but there seem to be at least 2 extensions that promise to format sass:
https://marketplace.visualstudio.com/search?term=sass&target=VSCode&sortBy=Relevance

**Comment by gertcuykens** [comment]
Still think css formating should work out of the box if formatting is build in for html js and typescript?

**Comment by xeoneux** [comment]
@gertcuykens Definitely! It's one of the features that you expect to be already there! HTML CSS JS
