### ISSUE TITLE
After formatting JSON you need to scroll left to see the formatted result

### ISSUE THREAD

**Issue by mackaaij** [Microsoft/vscode#48051]
Issue Type: <b>Bug</b>

After formatting text as JSON, the small preview in the top right shows the JSON neatly formatted. The main window is empty but does show line numbers.

Workaround: Scroll left or switch back and forth between screens to see the formatted JSON.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.3.0
githistory|don|0.4.0
mssql|ms-|1.3.1
python|ms-|2018.3.1
PowerShell|ms-|1.6.0
team|ms-|1.133.0

</details>

**Comment by jrieken** [comment]
> the small preview in the top right shows the JSON neatly

Do you mean the mini-map?

**Comment by jrieken** [comment]
Also, can you share the file with us and does this reproduce when running with extensions?

**Comment by mackaaij** [comment]
Yep the mini-map in the top right. I can't reproduce it with just a tiny line of JSON. How can I send you a longer string that I don't want to send via GitHub?

**Comment by jrieken** [comment]
You could mail it to me, but before that. How large (in MB) is that file? Is it hitting our limits?

**Comment by jrieken** [comment]
Ok, please send to jrieken[at]microsoft.com. Thanks

**Comment by mackaaij** [comment]
Done!

**Comment by jrieken** [comment]
Hm, works for me. After hitting format I see that the file as 58 lines, the only slightly *weird* thing is that most content is scrolled horizontally and line 19 is mostly visible. Scrolling left shows all content for me..

**Comment by mackaaij** [comment]
Ah that seems to be a better description indeed. I don't see line 19 but indeed, if I scroll left I see all content. So no refresh is needed but something like scroll left and top would be nice.

**Comment by jrieken** [comment]
@alexandrudima Could this also be related to the `replaceMove` change? Or the opposite?

**Comment by alexandrudima** [comment]
No, it is not related to that.

The editor will try as much as possible to maintain the previous scroll position. I guess the formatter should call one of the `.reveal*` methods on the editor. But I'm not sure what should be revealed... perhaps the range that was formatted or the last edit range ?

**Comment by lordcheeto** [comment]
Same issue here (1.23.0). I would describe it as the scrollbar not updating on formatting. Specifically, when pasting a large amount of minified content like JSON into VS Code, it comes in as one long line and the horizontal scrollbar handle is very small compared to the track. When the document is formatted, the scrollbar isn't updating to fit the now normal width content.

While you can scroll left all the way to see the content, the scrollbar remains too large. Switching to another tab, and back again forces the scrollbar length to update, which has the side effect of forcing the content back into view.

**Comment by brandber** [comment]
I'm also encountering this behavior. If specific examples are desired, please advise and I'll scrub some examples to share.
