### ISSUE TITLE
saving to SharePoint-doclibs via WebDAV not working anymore

### ISSUE THREAD

**Issue by Bit-Buster** [Microsoft/vscode#48050]
Issue Type: <b>Bug</b>

I have just updated from the previous version and now I can't save via WebDAV (loading from SharePoint via WebDAV works). When saving back I get the message, that I need an admin-account ... but even this does not work. With the last versions it always worked just fine. What has changed?! Could you please fix this?!!

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.90GB (8.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.1
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
csharp|ms-|1.14.0
vscode-todo-highlight|way|0.5.12

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@Bit-Buster can you share the error message, maybe a screenshot when this happens?
