### ISSUE TITLE
No "auto import" lightbulb in TSX markup

### ISSUE THREAD

**Issue by briman0094** [Microsoft/vscode#48058]
In the most recent versions of VSCode (if I remember correctly, this last worked for sure in 1.19 or 1.20 for me), I'm not getting TypeScript auto-import light bulbs for JSX tags. I get a lightbulb for the same class in a non-JSX tag, and I get an "auto-import from" IntelliSense suggestion when typing the name out in a JSX tag, but no lightbulb. The images below demonstrate the behavior I'm observing.

Non-component class as TS type: https://i.imgur.com/sNm9Mb0.png (correct behavior)
Component class assigned to variable: https://i.imgur.com/GXhRzgx.png (correct behavior)
Same class as JSX element, auto-import in IntelliSense: https://i.imgur.com/v0QRX45.png (correct behavior)
Same place, no lightbulb: https://i.imgur.com/Qy8uXv6.png (***incorrect*** behavior)

Using the suggestion in the third screenshot results in the correct import added to the `material-ui` import list:

```typescript
import { Popover, Menu } from "material-ui";
```

- VSCode Version: 1.2.2.1
- OS Version: Windows 10 x64 version 1709

Code to reproduce:

```typescript
import * as React from "react";

import { Popover } from "material-ui";

interface Props {
    items?: React.ReactNode;
}

export type ContextMenuProps = Props;
export default class ContextMenu extends React.Component<Props> {
    render() {
        let { items } = this.props;
        let contextMenuPopoverProps: PopoverProps = {};
        const Test = Menu;
        
        return <Popover { ...contextMenuPopoverProps }>
            <Menu>
                { items }
            </Menu>
        </Popover>;
    }
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please try this in vscode insiders as well. Here's what I'm seeing in insiders: 

![screen shot 2018-04-17 at 10 09 55 am](https://user-images.githubusercontent.com/12821956/38885337-844b675c-4227-11e8-97df-af88c6bf45c0.png)

If it still doesn't work, what version of `material-ui` do you have installed?

**Comment by briman0094** [comment]
I do indeed get the lightbulb in the Insiders build. It looks like the Insiders build is using a later version of TypeScript (2.8.2 insiders, versus 2.8.1 in my project)...is this a change in TS or in VSCode?

**Comment by mjbvz** [comment]
yes, we are using the 2.8.3-insiders build of TS which fixed a number of issues that could have been causing the lightbulb not to show up.

Please let me know if you see this again in insiders

**Comment by briman0094** [comment]
Actually, I just answered my own question...it looks like this is a fix in the insiders version of ***TypeScript***, as it worked in the non-insiders build of VSCode after I updated my project to use `typescript@insiders`.
