### ISSUE TITLE
[Vcxproj] All text within `<Command>` node should be highlighted as .bat (.cmd) code.

### ISSUE THREAD

**Issue by DmitrySokolov** [Microsoft/vscode#48057]
Issue Type: <b>Bug</b>

All text within this node
```
<Command>
echo Text
for /L %%A in (1,1,10) do echo %%A
<Command>
```
is a valid .bat code. And it should be highlited appropriately.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz (4 x 2675)|
|Memory (System)|8.00GB (3.64GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe -r C:\Dev\Projects\ITC\Icad\trunk\IntelliCAD\Source|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
hg|mrc|1.2.3
vscode-fileutils|sle|2.8.1
cmake|twx|0.0.17

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by ramya-rao-a** [comment]
What is the file extension on the file where you have this code?

**Comment by DmitrySokolov** [comment]
It's a well known Microsoft Visual Studio [project files](https://msdn.microsoft.com/en-us/library/2208a1f2.aspx).

**Comment by ramya-rao-a** [comment]
vcxproj files use the builtin xml extension. The xml grammar is not aware of any other embedded languages  and so cannot provide the appropriate highlighting.

@aeschli Are there any existing feature requests for supporting syntax highlighting of embedded languages as a generic feature?

**Comment by aeschli** [comment]
@ramya-rao-a There are requests for generic solutions, but I don't think there is a generic solution. 

To get better support for vcxproj, someone should come up with specific support for that file type.
That means implementing a TextMate grammar for vcxproj which can be based on the XML one.

**Comment by ramya-rao-a** [comment]
@aeschli 

> There are requests for generic solutions, but I don't think there is a generic solution

I was hoping to get a link to one such feature request so that @DmitrySokolov can understand all the discussions we've had in this topic till now

**Comment by ramya-rao-a** [comment]
@DmitrySokolov #1751 #670 #46133 #47288 cover most of the discussions in this area
