### ISSUE TITLE
Timeout when debugging powershell script

### ISSUE THREAD

**Issue by denisky** [Microsoft/vscode#48054]
Issue Type: <b>Bug</b>

Getting error message when debugging a powershell script.

![image](https://user-images.githubusercontent.com/38464498/38870819-fd4737ea-421c-11e8-8a65-850337ffe27a.png)

"Timed out waiting for the PowerShell extension to start."

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|Memory (System)|15.77GB (4.09GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Powershell|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
mssql|ms-|1.3.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
team|ms-|1.133.0
vscode-docker|Pet|0.0.26

</details>

**Comment by weinand** [comment]
Please file this issue against the PowerShell extension (as this is not a builtin part of VS Code).

**Comment by jkavanagh58** [comment]
Wasn't the issue because of duplicate detection. Either way sorry.
