### ISSUE TITLE
Feature Request: Option to auto-collapse other folders during autoReveal

### ISSUE THREAD

**Issue by KristjanTammekivi** [Microsoft/vscode#48053]
Feature: auto-collapse folders on file open/editor tab change that aren't a parent to the current file.

Use case: I jump around between files constantly and due to autoReveal it reveals the file in the explorer (which I like and I don't want to disable). The problem is that after a short amount of time most of the folders are open, and that makes it difficult to scroll around.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/45362
