### ISSUE TITLE
Git clean with a large amount of files causes hang

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4805]
- VSCode Version: latest alpha
- OS Version: Windows 10

Steps to Reproduce:
1. After working through this #4783 I removed then re-added my node_modules folder from .gitignore
2. Go to the Git tab and clean all (266 files in my case)

Actual:
Caused VS Code to hang

**Comment by joaomoreno** [comment]
What git version are you using?

**Comment by vsccarl** [comment]
@joaomoreno Version 2.7.2

**Comment by joaomoreno** [comment]
@vsccarl Do you still see this hanging?

**Comment by vsccarl** [comment]
@joaomoreno Its slow with a large clean but it is not crashing anymore.

**Comment by joaomoreno** [comment]
Large still means ~200 files?

**Comment by vsccarl** [comment]
Yes. I was using the build node_modules folder.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
