### ISSUE TITLE
React javascript to typescript

### ISSUE THREAD

**Issue by SyedAskari** [Microsoft/vscode#48059]
Issue Type: <b>Bug</b>

It's taking too long to use intellisence after the latest update.

Extension version: 1.10.0
VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|15.89GB (8.41GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Please provide more information about the problem. What are the steps to reproduce it? What does your project structure look like?

**Comment by SyedAskari** [comment]
It's a react app with web-pack. It can be reproduced by creating a simple react app with typescript and then using intellisense for any purpose like writing "this.  " and it will take 10 seconds before anything shows up. I have reverted back to the previous version and now everything is working fine again.

**Comment by mjbvz** [comment]
Do you see this in the current [VS Code insiders build](https://code.visualstudio.com/insiders/)? Does the issue still occur when you disable all extensions?
