### ISSUE TITLE
Option to filter git changes to active workspace

### ISSUE THREAD

**Issue by Jswk1** [Microsoft/vscode#48052]
**Feature request**

Hi. Would it be possible to add new option to vscode settings that would filter displayed git changes to active workspace?
 Let's imagine following scenario: I have a parent directory with git repository and few folders which are separate projects. When I open any project in vscode I'd like to see git changes only for this project.

As far as I know this behaviour existed before  multi workspaces were introduced (#37547). Is it possible to make it opt-in functionality, for example in vscode user/workspace settings?

Edit:
Working example implementation at 93a0a27

**Comment by joaomoreno** [comment]
Filtering is usually a bad idea. A user might think he's committing X files, when in fact he's committing X+Y files since there are Y files hidden away. I'd like us to not be in that position.

If we could render the SCM view as a tree, the experience would be much less painful: #14582

**Comment by pankleks** [comment]
This is very painful. 

I agree filtering only is bad idea. 

But there should be an option for VS to observe only files from work space and below.

I currently have 1 repo with following folders:
- App
  - Client
  - Backend

I run separate VS codes for both Client / Server (multiple workspaces does not work for me as code is too big and VS code is slow).

When I'm in Client VS code sees changes in both Client and Backend (which is confusing).

Please consider adding option to watch and (add / commit) only from current work-space.

**Comment by joaomoreno** [comment]
@pankleks I totally agree with you. But I still think the way forward is to be able to show the SCM changes in a tree-like form.
