### ISSUE TITLE
[html] Prevent single line auto-formatting for html attributes

### ISSUE THREAD

**Issue by parliament718** [Microsoft/vscode#4806]
Is there any way to prevent Visual Studio form auto-formatting html onto one line? 

For example

```
<div ng-repeat="item in items"
     ng-class="item.classes"
     ng-init="i = $index">
</div>
```

Gets auto-formatted to:

```
<div ng-repeat="item in items" ng-class="item.classes" ng-init="i = $index">
</div>
```

This seems unreasonably opinionated, especially since many frameworks these days take advantage of element attributes. It's not nice to have 5+ attributes on one line and is the reason I've avoided auto-formatting my html, as much as I would REALLY like to be able to.

**Comment by Tyriar** [comment]
@parliament718 here is a list of the options available for the formatter https://github.com/Microsoft/vscode/issues/4066

**Comment by aeschli** [comment]
We're currently using the HTML formatter from https://github.com/beautify-web/js-beautify. Maybe you can file your request (which I think is reasonable) there as well.

**Comment by aeschli** [comment]
duplicate of #2204
