### ISSUE TITLE
hi .in this application some shortcut key's  don't work correctly . i cant use Ctrl+c for copy and so on ...  

### ISSUE THREAD

**Issue by rezaei** [Microsoft/vscode#48060]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@rezaei You are on a very old version of VS Code (1.16.1). The latest version is 1.22.2. Can you upgrade and try again?

If you still have issues, please list the exact keyboard shortcuts that do not work for you as well as the list of extensions you have installed

**Comment by ramya-rao-a** [comment]
In that case run `code --disable-extensions` first. That will run VS Code with all your extensions disabled. Now try to copy/cut text and see if that works

**Comment by rezaei** [comment]
yes, you are right.
now everything is ok
OK, now how I can find that extension?

2018-04-17 23:21 GMT+04:30 Ramya Rao <notifications@github.com>:

**Comment by ramya-rao-a** [comment]
Unfortunately, the only way to do that is for you to enable the extensions one by one and see which one causes the issue.
Once you find that extension, please log an issue in the repository for that extension
