### ISSUE TITLE
Keymap to change language for file

### ISSUE THREAD

**Issue by ethamitc** [Microsoft/vscode#48066]
It would be nice if `Ctrl+Shift+L` Would open the bar to change the files language, like atom.

**Comment by ramya-rao-a** [comment]
Currently the command `Change Language Mode` is bound to `Ctrl+K+M`

![image](https://user-images.githubusercontent.com/16890566/38887564-0bc6e2c8-422e-11e8-969e-9abb92a60001.png)

You can change it to your choice of keybinding. See [Key Bindings for VS Code](https://code.visualstudio.com/docs/getstarted/keybindings).

You can also give the atom keymap extension a try. See https://marketplace.visualstudio.com/items?itemName=ms-vscode.atom-keybindings
