### ISSUE TITLE
Emmet suggests disabled for the fieldset tag

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#48068]
Issue Type: <b>Bug</b>

Begin typing "fieldset" in an HTML file.

Emmet suggests `fieldset:d`  and `fieldset:disabled`, which both expand to 
`<fieldset disabled="disabled"></fieldset>`

There's no way to get a fieldset without the disabled attribute.

<img width="756" alt="screen shot 2018-04-17 at 1 42 26 pm" src="https://user-images.githubusercontent.com/835148/38886969-827e51b4-4245-11e8-9897-c592523663e3.png">

VS Code version: Code - Insiders 1.23.0-insider (ab56a0952b9c2ff7add6404f80ebf9398cf8ae51, 2018-04-17T05:10:56.728Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_9423100|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.3.0
code-settings-sync|Sha|2.9.0
sort-lines|Tyr|1.6.0
Bookmarks|ale|0.18.2
project-manager|ale|0.25.0
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.0
path-autocomplete|ion|1.9.0
svg|joc|0.1.0
Angular2|joh|2.16.1
ecdc|mit|0.12.0
HTMLHint|mka|0.4.0
theme-monokai-pro-vscode|mon|1.1.6
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.20.1
stylelint|shi|0.36.0
rewrap|stk|1.8.1
bootstrap4-vscode|the|4.1.1
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
I'll look into why `fieldset` is not one of the completion items. Until then, `fst` will give you `fieldset`

![image](https://user-images.githubusercontent.com/16890566/38889497-c09c2802-4233-11e8-86fc-e1c397d34880.png)

**Comment by ramya-rao-a** [comment]
You can get the fix in tomorrow's [Insiders](https://code.visualstudio.com/insiders) build
