### ISSUE TITLE
Windows download link isn't working

### ISSUE THREAD

**Issue by KumarVivek** [Microsoft/vscode#48067]
I am unable to download Visual Studio Code. This site is not reachable: https://vscode-update.azurewebsites.net/latest/win32-x64/stable

**Comment by octref** [comment]
@kumarharsh This site is working for me though -- are you using any VPN?

**Comment by octref** [comment]
@joaomoreno I can repro when using the Microsoft VPN on macOS.

**Comment by KumarVivek** [comment]
So, I used the download from my personal PC, and it works fine. So, looks like the issue is only occurring when downloading using Microsoft VPN.

**Comment by m3Lith** [comment]
I can't download from the official site either – Firefox shows "The connection has timed out" error. No VPN, Lithuanian ISP.

**Comment by joaomoreno** [comment]
Could've been this: https://azure.microsoft.com/en-us/status/history/

Does it work now?

**Comment by m3Lith** [comment]
Ah, probably that. It works now.

**Comment by octref** [comment]
I can download VS Code correctly now using Microsoft VPN. @kumarharsh Can you check again if your issue has been resolved?

**Comment by kumarharsh** [comment]
Why is everyone tagging me?

**Comment by octref** [comment]
@kumarharsh Oops sorry. I meant @KumarVivek. I typed `@kumar` and GitHub suggested you first even though you are not in the thread. Seems they need to improve their completion scoring algorithm...
