### ISSUE TITLE
Unable to update vscode.WorkspaceConfiguration in a test

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#48071]
I'm trying to write an integration test for the C/C++ extension which edits the extension's settings, but the changes don't appear to stick.

As an example, the test launches the extension host, activates the extension, and eventually does this:

```
let s: vscode.WorkspaceConfiguration = vscode.workspace.getConfiguration("C_Cpp", rootUri);
let d: any = s.inspect("loggingLevel");
s.update("loggingLevel", "Warning", vscode.ConfigurationTarget.WorkspaceFolder);
d = s.inspect("loggingLevel");  // "Warning" should be set for d.workspaceFolderValue, but it's not
```

Is there some other magic I'm missing to make this work?  The globalValue is already set and I can validate I get the right thing for that since I'm testing on my local machine.  So I can read settings, but I can't seem to change them in the context of my test.

**Comment by sandy081** [comment]
@bobbrow Couple of questions

- Is this in a single folder (not multi-root) ?
- Does the effective value changed after update?

**Comment by bobbrow** [comment]
Yep, single folder.
No, the effective value is not ever changed.

I'm thinking about maybe writing the .vscode/settings.json file for that folder myself and then reloading the window, but I would really like to have a test that changes the value in the same session.

**Comment by sandy081** [comment]
Ok, this is a known issue - #47730

When there is no change in the effective value, change event is not triggered and hence the inspect shows the old value.

**Comment by sandy081** [comment]
@bobbrow the fix is to trigger the change event when the value is changed in settings file irrespective of effective value is changed or not. Model on the extension host side gets updated on listening to this change. So, I think your issue should be fixed with this. Can you please try out the fix and let me know if it worked?
