### ISSUE TITLE
Allow block comments characters to have new line in them

### ISSUE THREAD

**Issue by Gimly** [microsoft/vscode#48074]
Issue Type: <b>Bug</b>

Create an extension with a language configuration containing the following types of comments (it's coming from the [VSCode Matlab extension](https://github.com/Gimly/vscode-matlab/) :

```JSON
"comments": {
    "lineComment": "%",
    "blockComment": [ "\n%{\n", "\n%}\n" ]
},
```
Run in debug mode and try to create a block comment. 

The block comment should correctly be added, but when you try to remove it with the same key combination, it will add new block comments instead of removing the existing ones.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|Memory (System)|7.91GB (1.15GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-markdownlint|Dav|0.14.1
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
fortran|Gim|0.2.0
matlab|Gim|0.8.1
Angular2|joh|2.16.1
solidity|Jua|0.0.38
ftp-sync|luk|0.3.3
HTMLHint|mka|0.4.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
team|ms-|1.133.0
debugger-for-chrome|msj|4.3.0
debugger-for-edge|msj|0.4.1
vscode-docker|Pet|0.0.26
yo|sam|0.9.3

</details>

**Comment by ramya-rao-a** [comment]
How are you adding the block comments? What keybinding are you using to add and remove the comment?

**Comment by CelsoReyes** [comment]
On a Mac, it's   `shift-alt-A`.  
Here's where I [originally reported it in the extension](https://github.com/Gimly/vscode-matlab/issues/31).  MATLAB-style block comments must exist on their own lines, but may be surrounded by whitespace
ex.
```matlab
  %{
      a block comment with leading whitespace
  %}

  myfunction(); % end of line comment
```
```matlab
%{  mistake. because of text on this line, it is treated like an end-of-line comment
   uncommmented_function_although_intent_was_to_comment_it();
%}

**Comment by tikkanz** [comment]
I have the same issue in the language extension for the J language.
I can add the new line chars to the start and end character sequences, and they are correctly inserted. 
However the same sequences don't appear to be identified/matched when attempting to toggle off the block comment and instead an additional set of start and end sequences are inserted.
