### ISSUE TITLE
VSCode now launching/working in Ubuntu 18.04

### ISSUE THREAD

**Issue by Synaxis** [Microsoft/vscode#48079]
Hello , i've download VSCode from Snap software , and it's not launching

**Comment by ksmithut** [comment]
I'm able to install it and run it on Ubuntu 18.04. Probably need more details

**Comment by DooMachine** [comment]
I downloaded it with anaconda first. No start. Then deleted it and installed it with deb package and still not starting, without errors.

**Comment by Tyriar** [comment]
@Synaxis the snap package is third party currently (and is an old version of VS Code), use the deb package/apt repo instead https://code.visualstudio.com/docs/setup/linux

@DooMachine feel free to create a new issue for your issue, please include the output of `code --verbose`
