### ISSUE TITLE
Cannot download VS Code

### ISSUE THREAD

**Issue by rocha6464** [Microsoft/vscode#48072]
I get the following error when I try to download the VS Code  (specifically 64-bit stable Windows version 1.22):

_az764295.vo.msecnd.net took too long to respond._

I get the same result using Chrome and Edge. I am not running behind a proxy.  Running Windows Network Diagnostics returns the following information:

_resource (az764295.vo.msecnd.net) is  online but isn't responding to connection attempts. | Detected |  
The remote  computer isn’t responding to connections on port 443, possibly due to firewall  or security policy settings, or because it might be temporarily unavailable.  Windows couldn’t find any problems with the firewall on your computer._

I am located in Uganda. Any hints?

Thanks and Regards.

**Comment by rocha6464** [comment]
Hmmm....eventually downloaded. Must have been a glitch of some sort. Apologies for the trouble.....

**Comment by octref** [comment]
@rocha6464 Just for record, here is the issue: https://azure.microsoft.com/en-us/status/history/. Also see #48067.
