### ISSUE TITLE
[Latest alpha] Debug loading indefinitely after creating launch.json for node.js

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4807]
- VSCode Version: Latest alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Using the latest alpha, clone https://github.com/heroku/node-js-sample.git
2. Run npm install
3. Open folder in VS Code
4. Go to Debug tab and generate the Node.js launch file

Actual:
Debug shows loading bar underneath and cant debug until restarting VS Code

**Comment by isidorn** [comment]
Good catch.
