### ISSUE TITLE
Close button for sidebar

### ISSUE THREAD

**Issue by ShalokShalom** [Microsoft/vscode#48080]
I am really wondering, that I seem to be the first one who suggests a simple close button for the sidebar, is it really common to simply pull and drag that every time or click on the icon in the activity bar?

**Comment by ramya-rao-a** [comment]
Ctrl+B is the keyboard shortcut to toggle the side bar
You can do the same using the command `View: Toggle Side Bar Visibility` as well

**Comment by ShalokShalom** [comment]
This is nice. I still consider this as open, since this is something else as a close button. 

Thy
