### ISSUE TITLE
auto-complete is always show loading

### ISSUE THREAD

**Issue by XiangDeMei** [Microsoft/vscode#48089]
- VSCode Version: code_1.22.1-1522974421_amd64.deb
- OS Version: ubuntu 17.10

Steps to Reproduce:

1. when I use the auto-complete function, it always show loading
![image](https://user-images.githubusercontent.com/16175984/38907574-e6aa3e1a-42ee-11e8-8cd1-fd87fa4a2769.png)

Does this issue occur when all extensions are disabled?:  No

**Comment by mjbvz** [comment]
Do you see this in the current [VS Code insiders build](https://code.visualstudio.com/insiders/)? Does the issue still occur when you disable all extensions?
