### ISSUE TITLE
[javascript] generator method autocomplete causes star to be added to next line

### ISSUE THREAD

**Issue by Jamesernator** [Microsoft/vscode#48084]
- VSCode Version: 1.23.0-Insider (also happens on stable)
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Try creating a generator method in an object literal or class
2. Pressing enter causes another star to be added on the next line causing a syntax error

Does this issue occur when all extensions are disabled?: Yes

Image (line 4 shouldn't get an extra star):

![vscode-issue](https://user-images.githubusercontent.com/8518303/38905295-e9a3ed18-4303-11e8-8a0e-b0f7e2946923.gif)

**Comment by mjbvz** [comment]
Duplicate of #43469
