### ISSUE TITLE
Folder fold or expand by clicking on the folder in the sidebar (Explorer)

### ISSUE THREAD

**Issue by mumeiyamibito** [Microsoft/vscode#48087]
- VSCode Version: 1.22.2
- OS Version: LinuxMint 18.3

Steps to Reproduce:
1. Open explorer on sidebar.
2. Click folder (not right triangle mark).
3. Folder fold or expand.

Does this issue occur when all extensions are disabled?: Yes

Desired behavior: Folder is only focused by clicking the folder. And folder fold or expand by clicking right triangle mark.

When creating a new file in a folder on the sidebar, the folder is focused and folded / expanded at the same time by clicking, so operability is bad.

**Comment by isidorn** [comment]
This is just the designed behavior, we currently have no plans of changing this thus closing as out of scope
