### ISSUE TITLE
Custom select box on mac shows as default select when not focused

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#48081]
Issue Type: <b>Bug</b>

The select box shown at the top of the terminal and output panels changes styles on Mac based on whether it's focused. When unfocused, it shows as the default Mac select with rounded corners. On Windows, the select box styling doesn't change on focus and always has sharp corners

![custom_select](https://user-images.githubusercontent.com/3672607/38899102-bfb9b13a-424b-11e8-809c-43462e55a238.gif)

VS Code version: Code - Insiders 1.23.0-insider (7c62e560a2e494a1b0b4d39561dc5c1d837a5263, 2018-04-13T05:10:35.779Z)
OS version: Darwin x64 17.4.0

**Comment by cleidigh** [comment]
@RMacfarlane 
The selects/DropDowns on OS X utilize the "native" HTML select while Windows and Linux now use the
selectBoxCustom implementation based on a list.  This was a design decision.  The end result
is that OS X controls the rendering you are referring to that does not happen with the custom select.

**Comment by RMacfarlane** [comment]
@cleidigh Thanks, that makes sense! I still think it's strange that the styling of the select changes when its focused instead of maintaining the same height and rounded edges of the native control.

**Comment by cleidigh** [comment]
@RMacfarlane 
I agree the behavior is a bit odd, but I'm not exactly a huge OSx fan and I don't like that the select is so different than the other platforms.

Actually there is no problem using the selectBoxCustom on OS X.  If you remove or disable the platform conditional at the beginning of selectBox.ts you can force it to use the custom select on all platforms.

It was decided early on when I was doing this to maintain the native select on OS X to follow the platform feel.

Can we close this?

**Comment by RMacfarlane** [comment]
@cleidigh Yes, thanks for the info!
