### ISSUE TITLE
[Advice] About the design of "combine  include/exclude patterns"

### ISSUE THREAD

**Issue by szyhf** [Microsoft/vscode#48090]
- VSCode Version: 1.22.2
- OS Version: macOS

In release 1.22.2, a new design is approve : 

```markdown
# Search include/exclude patterns

The boxes for include and exclude patterns in the Search view have been combined into a single box. The functionality is exactly the same, except that an exclude pattern must be prefixed with !. For example, !*.js will skip searching files that have a .js extension.
```

That case some problem, in most cases, what user want to exclude is more stable, like `.vscode`, `.git`, but what user want include is changing frequently.

While combine in the same box, every time user use right click on folder and chose `search in ...` will clear all patterns inside search box, especially the exclude patterns.

I know the setting of `files.exclude` but it‘s not visualized, sometimes that will case some lost of search results in special cases.

How about adding a setting to set if combine include/exclude patterns .

Thanks for reviewing.

**Comment by roblourens** [comment]
> While combine in the same box, every time user use right click on folder and chose search in ... will clear all patterns inside search box, especially the exclude patterns.

What if it would only replace the include patterns when you do that, and leave the exclude patterns in the box? Would that help?

> I know the setting of files.exclude but it‘s not visualized, sometimes that will case some lost of search results in special cases.

Do you mean lost search results, because people don't realize that the results are excluded by files.exclude and search.exclude?

**Comment by szyhf** [comment]
Tanks for replying ! 

---

>> While combine in the same box, every time user use right click on folder and chose search in ... will clear all patterns inside search box, especially the exclude patterns.

> What if it would only replace the include patterns when you do that, and leave the exclude patterns in the box? Would that help?

I'm wondering its difficult to deal with patterns of complex like `!*.a,*.A,!*.b,*.B`, the UI logic looks little wired.

---

>> I know the setting of files.exclude but it‘s not visualized, sometimes that will case some lost of search results in special cases.

> Do you mean lost search results, because people don't realize that the results are excluded by files.exclude and search.exclude?

Yes, user might ignore the exclude in setting, especially setting of vscode has multi-level.

---

I think setting is working for some stable usage. In search, some exclude is stable like `./.git`, but some are not deal to the project struct. The former can use the setting, but the latter might not suitable.

While searching for something, I think display the condition deal to the project clearly is important, but patterns might not easy to recognize.

---

In my opinion, I felt that the combine patterns makes user easier to copy and paster there setting, although I don't know the reason of combine it.

Actually I think to read and modify a little bit long patterns in one-line box is easy to make mistake.

So if it's really need to combine, how about make the input box of patterns can be a multi-line box. And user can type in multi-line to satisfy there require of search, for example:

```
!./.git,!./.vscode,!./.idea,
./server/model,./server/config,
!./server/rpc_msg,
./server/
```

Then while using `search in ...`  in right click of folder, just replace the include patterns and leave the exclude patterns, for example: 

```
!./.git,!./.vscode,!./.idea,
!./server/rpc_msg,
./server/new/path/include
```

Very pleasure to receive your reply, thank you ~

**Comment by roblourens** [comment]
Thanks for the feedback. I think a multiline box would help but wouldn't solve all the issues that people have with the new layout. I've moved back to split include/exclude boxes for now, you can try it out in the next Insiders build. More discussion at https://github.com/Microsoft/vscode/issues/46315
