### ISSUE TITLE
matchOnDescription allow me to open Visual Studio Code as CrhomeBrowser

### ISSUE THREAD

**Issue by DracotMolver** [Microsoft/vscode#4809]
- VSCode Version: 0.10.10
- OS Version: Linux - Distro. Elementary OS

Steps to Reproduce:

I'm learning about **showQuickPick**. So I set the option **MatchOnDescription**.
So the code is like follow:
```javascript
vscode.window.showQuickPick(['rgb', 'hex'], {
      matchOnDescription:true
 });
```
When I run this code to taste it and I hit down F1 to type down the command line, it shows me the list 
 'rgb', 'hex' but when I type down any word from my keyword, the editor change and display me the Inspector element by Chromium and the editor is like an HTML.

![screenshot from 2016-03-30 23 36 52](https://cloud.githubusercontent.com/assets/13334764/14163886/52bf4a4a-f6d0-11e5-93e6-e1b4e352fe3b.png)

is this a right behavior?, because the description about **MatchOnDescription** doesn't say something like this is going to happen.

**Comment by Tyriar** [comment]
It might be showing the dev tools because an error occurred? Try looking at the errors by clicking on the red `x` in the top-right.

**Comment by bpasero** [comment]
Hm, we might indeed bring up dev tools automatically if an error occurs. @DracotMolver please click on the ">>" in the toolbar to the right to reveal the "Console" and click that.

You can also share the code with me so that I can have a look?

**Comment by bpasero** [comment]
@DracotMolver I can reproduce this issue, nevermind. There is a bug in our end but you are also using the API in a way we did not think about: "matchOnDescription" only makes sense if the labels you pass in have a description. To create a pick entry with label, you need to pass in an object that implements the QuickPickItem interface: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1155

**Comment by DracotMolver** [comment]
So, is it a new feature when it opens the web browser?. Because all the errors are displayed in the console debugger. ooh...Sorry if I use the API in a wrong way :P. I thought that the parameters were optionals.
Ok I solve it doing this. - It was something awful as a code...but it works as a test lol.
```javascript
var items = [];
var addItems = function(item : vscode.QuickPickItem){
    items.push(item);
};

 addItems({label:'rgba', description:'colores en formato decimal con alpha'});
 addItems({label:'hex', description:'colores en formato hexadecimal'});

vscode.window.showQuickPick(a, {
    matchOnDescription:true
}).then((data) => {
    console.log(data);
});
```
Now I realized that this should be obvious because it says matchOn**Description**, so it has to be a description...but the documentation about showQuickPick says for its parameters:  _An array of strings, or a promise that resolves to an array of strings._
Thanks guys for your time. This is the answer and solution for me...but you decided if it is a bug or not :)
