### ISSUE TITLE
Extension api problem: vscode.workspace.createFileSystemWatcher

### ISSUE THREAD

**Issue by chongchai** [Microsoft/vscode#48092]
- VSCode Version:  1.22.1
- OS Version: Windows 7

Steps to Reproduce:

1. In my extension, I use the `createFileSystemWatcher `api to watch the file changes. code is below:
```
	let fileSystemWatcher = vscode.workspace.createFileSystemWatcher('**');
	context.subscriptions.push(fileSystemWatcher.onDidChange((filePath) => {
		console.log(filePath + " changed!");
		if (monitorFileExt.indexOf(path.extname(filePath.fsPath)) !== -1) {
			//do something
		}
	}));
```
2. Lauch the extension and open a folder which contains test.cpp.
3. Open and modify file test.cpp in VsCode. The watcher is correct to say `test.cpp changed`
4. But when I just open the the test.cpp in notepad++ or Visual Studio. The watcher says `test.cpp changed`.

So in other editors except for VsCode, open a file will fire the event "file change" ???

**Comment by bpasero** [comment]
@chongchai it could well be that these editors touch the file when opening or do anything that triggers the file event. I do not think this is under our control.
