### ISSUE TITLE
PHP: hash in SQL string breaks syntax highlighting

### ISSUE THREAD

**Issue by neerolyte** [microsoft/vscode#48096]
- VSCode Version: 1.22.2
- OS Version: Ubuntu 16.04.4 LTS

Steps to Reproduce:

This code:

```php
<?php
$sql = 'SELECT \' #\' || fieldid FROM sometable';
```
Highlights like so:

![image](https://user-images.githubusercontent.com/1070702/38912265-aacdb682-4317-11e8-9d6b-b53a22d0660f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by neerolyte** [comment]
> PHP Syntax broken by PHP->CSS->PHP embedding (#38275)

This is a different syntax problem.

**Comment by roblourens** [comment]
Upstream: https://github.com/atom/language-php/issues/327

**Comment by sergiolch** [comment]
I also have a similar issue with SQL:

```php
class test2 {
    public function method1($txt)
    {
        $q = "SELECT b2.*
            FROM
            (SELECT users
            ORDER BY id DESC) as b2";
        return $this->query($q);
    }
    public function method2()
    {
        return true;
    }
}
```

but it looks like this:

![Screen Shot 2019-07-16 at 3 33 53 PM](https://user-images.githubusercontent.com/273710/61320308-8a384580-a7df-11e9-9933-ae2d9442296f.png)

**Comment by misterHippo** [comment]
I have a similar issue while checking for SQL injection segments.

`"SELECT /*!"` is in an array, and the syntax highlighting is all green (comments) after it, even though it's within quotes. If I make it a lower case `select`, then it fixes itself

Alternatively, if I put /* ? */ after it, everything changes to that burnt orange colour (string?)

Interestingly, `"SELECT USER()"`, `"SELECT SUBSTRING(user_password`", `"' or 1=1/*"` and `["/*! MYSQL Special SQL *"` don't bring about the same outcome.

**Comment by wjonkerhulst** [comment]
I have a similar problem. This database has column names with a #. These columns break the syntax highlighting.  
![image](https://user-images.githubusercontent.com/54948500/69323084-53b77f00-0c46-11ea-8190-405be78aa2c5.png)

**Comment by DABugh** [comment]
Similar (PHP):

![image](https://user-images.githubusercontent.com/9809423/97275137-8e854800-1803-11eb-8a57-fa57443862ed.png)

This only happens for me when the string begins with syntax which is interpreted as being part of an SQL query (e.g. "AND"), there is a variable concatenated between two double-quoted strings each containing one single-quote, and the variable outside of the string has two levels of encapsulation.

In the screenshot, "**->value**" is the wrong color, as are the two concatenation periods on either side of the variable expression.

**Comment by roblourens** [comment]
Since the upstream project has been archived, merging this into the general issue for a new SSH grammar. https://github.com/microsoft/vscode/issues/162707
