### ISSUE TITLE
Place multiple cursors on found places

### ISSUE THREAD

**Issue by csicky** [Microsoft/vscode#48099]
Hi VS Code team, 

this is a feature request.

I have now many files with JSX full of some attributes I don't need anymore. Like this: ` <h4 data-translate="almostThere">` I want to remove them with as little effort as possible. I can start by searching for them using this `data-translate="` and I get all of them, this is OK. Now I have to go one by one and remove them by hand. 

Would be great if I could have all the found elements in the file, have a cursor at the begging of the found string. I could then just navigate with keyboard and select all of them at once and delete them. (I am talking about the search in file component, the one which appears on top right when you press `Ctrl+F`.)

- VSCode Version: 1.22.2
- OS Version: Windows 10

**Comment by burtek** [comment]
JFYI:
1. There is "Search in all files" function (`Ctrl+Shift+F`)
2. when you select `data-translate`, you may press [`Ctrl+D`](https://code.visualstudio.com/docs/getstarted/keybindings#_basic-editing) multiple times which will add next match to selection. You may then edit all those places at once

**Comment by csicky** [comment]
Thank you, I didn't know about this. It is almost as I imagined :) Super!
