### ISSUE TITLE
Uninstalled VSCode while Updating

### ISSUE THREAD

**Issue by Avinashachu007** [Microsoft/vscode#48100]
Issue Type: <b>Bug</b>

When I update the Vscode to the April 1.2.2, The update process breaks in the middle. The VSCode was uninstalled. I have to Download an install manually via vscode website.

Steps to Reproduce
1.Click 'Help' in the File menu.
2.Click 'Update'
3.If it Asks for Admin premission Click 'Yes'

While installing it shows the error screen 'Manually Download and Install VScode'

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Dual-Core AMD Opteron(tm) Processor 1214 (2 x 2194)|
|Memory (System)|3.00GB (0.46GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ci-snippets2|Ani|1.0.0
vscode-intelephense-client|bme|0.8.8
path-intellisense|chr|1.4.2
githistory|don|0.4.0
gitlens|eam|8.2.1
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.31
vsc-material-theme|Equ|1.6.0
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
vscode-git-tags|how|1.3.1
rest-client|hum|0.18.2
html-tag-wrapper|hwe|0.2.3
debugger-for-chrome|msj|4.3.0
vscode-paste-and-indent|Rub|0.0.8
bootstrap-3-snippets|wcw|0.1.0

(5 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Did it create a log file? Can you send me that?
