### ISSUE TITLE
TypeScript auto suggestion of anonymous function this in class not working

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#48104]
Example:

```
class foo {

   static bar(){}

   static test(){
      bar();
   }

   static test2(){

      someFunction( () => { bar(); } )

   }

}
```

Auto suggestion for the 'bar' in test() correctly suggests whether I meant this.bar().

But auto suggestion for bar() in the anonymous function under test2() does not, it instead says:

"Cannot find name 'bar'. Did you mean the static member 'foo.bar'?

Technically that message is incorrect, while I do want the static member, I really want this.bar...

And on top of that, there is no little yellow tip lightbulb to autocorrect it.

**Comment by mjbvz** [comment]
Yes there should be a quick fix. Opened https://github.com/Microsoft/TypeScript/issues/23519 to track  upstream

`foo.bar()` works too and is more explicit so I don't think the error message itself is incorrect. We can see what people on the TypeScript think about this
