### ISSUE TITLE
update too quickly

### ISSUE THREAD

**Issue by sunryy** [Microsoft/vscode#48101]
Issue Type: <b>Bug</b>

it's not good to update so many times in a very short time!!!

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.16299

**Comment by burtek** [comment]
@sunryy unless there are critical bugs in previous versions that need to be fixed ASAP ;)

**Comment by ramya-rao-a** [comment]
Thanks @burtek :)

We do not release patches unless there are regressions in the product which do not have a workaround. You can see the [issues](https://github.com/Microsoft/vscode/milestone/68?closed=1) that got fixed in the latest patch in the Release Notes
