### ISSUE TITLE
Saving workspace names with dot (.) removes the last dot

### ISSUE THREAD

**Issue by sveinse** [microsoft/vscode#48103]
If I save a workspace using filenames with dot (.) in it, then vscode removes the last dot from the workspace filename. E.g. if I save workspace as "release-6.4" (without the suffix), then vscode removes the ".4" and saves the file as "reelase-6.code-workspace". However, if I in the save dialog specifies full filename, "release-6.4.code-workspace", then it will be saved as is.

Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS: Ubuntu 18.04 (preview)

**Comment by bpasero** [comment]
@sveinse does this happen only for workspace files or any files in general?

**Comment by sveinse** [comment]
It does not happen on generic editor files, no. I think this might be because there is no predetermined suffix in the save process. E.g. Saving a workspace without any suffix will automatically add '.code-workspace' to the filename. I think it is in that process that the last '.*' is being removed from the filename.

**Comment by bpasero** [comment]
This seems to be an issue in Electron with the fact that we set a filter on the dialog (which we are not doing anywhere else). If someone has energy and ideas to look into this, welcome.

**Comment by bpasero** [comment]
@sveinse as a workaround if you just fully type the name it seems to work fine, e.g. enter "foo.bar.code-workspace" works for me.
