### ISSUE TITLE
Smoketest: Implement Terminal smoketest

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48109]
Our [smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) involves at least opening a terminal and running a simple command such as `ls`.

The automated smoketest is missing all the terminal tasks. Let's bring that back!

The terminal-related files were removed at some point but here they are for reference:

- https://github.com/Microsoft/vscode/blob/225d7e5a21371583d8eb7fb3012f7c501c7b26ed/test/smoke/src/areas/terminal/terminal.ts
- https://github.com/Microsoft/vscode/blob/225d7e5a21371583d8eb7fb3012f7c501c7b26ed/test/smoke/src/areas/terminal/terminal.test.ts

We should take that code and port it over to the new automated smoketests.

**Comment by joaomoreno** [comment]
@Tyriar I got the old test working again. Can you go through the code and make sure it makes sense? The way I was able to get input into the terminal was to fake a `paste` event on the textarea. This won't test that the terminal indeed gets keyboard events (due to keybinding service, or others)... but maybe that's enough? I leave it up to you if you want to improve the smoketest here.

**Comment by Tyriar** [comment]
@joaomoreno thanks for doing this :smiley:

**Comment by isidorn** [comment]
When running the smoke test locally I do not see the terminal tests being run. Why is that?
![screen shot 2018-04-26 at 15 39 56](https://user-images.githubusercontent.com/1926584/39309358-1598fef8-4968-11e8-8a26-c195dfa75f3f.png)

**Comment by joaomoreno** [comment]
@isidorn #48396

**Comment by isidorn** [comment]
Then adding verified since you imlemented it, the issue that it does not work is caputerd in taht one :D

**Comment by joaomoreno** [comment]
@isidorn It was working when this was closed. It broke since, due to changes in the terminal.
