### ISSUE TITLE
The window is no longer responding,can't reopen/keep waitting/close

### ISSUE THREAD

**Issue by xianghongai** [Microsoft/vscode#4810]
hi,@alexandrudima
- VSCode Version:0.10.11
- OS Version:windows 10 x64
![](https://cloud.githubusercontent.com/assets/2075006/14057991/16968754-f34c-11e5-9ecd-cfff4f649270.png)<br>
open many js/html/css document,<br>
vscode prompt appears"HTML CSS Class Completion:Fetching CSS rules frome CSS files,please wait",<br>
 will trigger **"The window is no longer responding"** ,<br>
can't reopen/keep waitting/close. <br>
chinese meaning：没反应，卡死,<br>
kill vscode process,restart vscode still the same problem,must change last time folder or file name,<br>
plugin is [HTML CSS Class Completion](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion),<br>

company windows 7 x64 is ok,
home windows 10 x64 this problem may occur,<br>

It is like this.

**Comment by alexandrudima** [comment]
Hi @xianghongai Thank you for filing this issue.

Can you please point me to a set of files (a zip archive) or a github repository that reproduces this for you?

I have tried opening a bunch of html/css/js files with this plugin installed, but I am not seeing the hang.

**Comment by Dragod** [comment]
I think this is related to an extension https://github.com/Zignd/HTML-CSS-Class-Completion as I had same problem with a big html file where I had same error: "HTML CSS Class Completion:Fetching CSS rules frome CSS files,please wait". Unistalling the extension solved it

**Comment by xianghongai** [comment]
May be the compatibility is not good enough...

**Comment by Dragod** [comment]
Anyway they should check extension before adding them to the market.

**Comment by alexandrudima** [comment]
I'd like to reopen this to try to reproduce myself. If you have any more pointers on how to repro, please let me know. My concern is that a bad extension should not lead to an unresponsive window, it should at most crash the extension host.

**Comment by xianghongai** [comment]
windows7 not appear this problem, there may be reason windows10 system, we let this issues: let it go, let it go ...
