### ISSUE TITLE
Push strings for standalone editor to Transifex.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#48108]
See https://github.com/Microsoft/monaco-editor/issues/822

**Comment by dbaeumer** [comment]
Closing.

**Comment by joechung-msft** [comment]
Is this fixed?  Why is this being closed?

**Comment by dbaeumer** [comment]
I closed this in favor of Microsoft/monaco-editor#822. This is nothing we can address in the vscode repository since it would add knowledge to the vscode repository about the monaco-editor repository. The strings that need translation in the monaco editor and are not part of the VS Code push need to be pushed by the editor. I VS Code we would only have the option to push all or nothing which doesn't seem to be the right approach.

Sorry for not making this clear when closing.

**Comment by joechung-msft** [comment]
Ah, that makes sense.  Thank you for the explanation.
