### ISSUE TITLE
Smoketest: strange timeout in debug tests

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48110]
@isidorn In the smoketest, we start debugging byby pressing <kbd>F5</kbd> and waiting for some DOM changes. That wait involves waiting for the pause button to appear as well as the status bar to change to the debug state.

During the latest refactorings I was hitting a strange issue in which the pause button would appear but the status bar wouldn't change at all. I could reproduce it maybe 50% of the time on my macOS machine (maybe you can too).

I was able to get around it with this timeout:

https://github.com/Microsoft/vscode/blob/52007064712fb8e74e8b7dd00903beaabcd79648/test/smoke/src/areas/debug/debug.test.ts#L51

With the smoketest refactorings, everything got a bit faster... so the difference might be that we go through the `configure launch json` and `breakpoints` steps faster and immediately start debugging. This might cause some sort of race condition within Debug land, which I think to be worth investigating.

To attempt to reproduce, simply comment out the timeout and run the tests:

```
yarn smoketest -f Debug
```

**Comment by isidorn** [comment]
Ok, I can look into it next week since I do not expect many bugs for endgame.
