### ISSUE TITLE
Debug Console Array Expand Not Expanding

### ISSUE THREAD

**Issue by akinozgen** [Microsoft/vscode#48115]
Issue Type: <b>Bug</b>

When i debug a typescript node.js app, debug console not expanding logged array value.

![VSCode Issue](https://i.imgur.com/llQQWlE.png"")

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1700)|
|Memory (System)|5.92GB (1.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\.dev\CurrentProjects\yemeksepetix|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.11.2
vscode-great-icons|emm|2.1.31
todotasks|san|0.5.0

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
You can only expand data structures (i.e. arrays) if a debug session is active.

**Comment by akinozgen** [comment]
yes i did. still not works

**Comment by roblourens** [comment]
We can't do this because once the program has terminated, we can't ask for the contents of the object. We can't even inspect the object proactively because there will be a race between the program terminating and it responding to our request to examine the contents of the object.
