### ISSUE TITLE
Resizing the terminal causes CPU, GPU and memory usage to spike

### ISSUE THREAD

**Issue by costincaraivan** [Microsoft/vscode#48114]
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Extra info:
Windows 10
```
    "terminal.integrated.shell.windows": "C:\\cygwin\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": [
         "/bin/xhere",
         "/bin/zsh"
    ],
```

Steps to Reproduce:

1. Use the terminal normally.
2. Click the resize arrow.
3. CPU usage instantly for VS Code 30% (i5-7200U @ 2.5 GHz), memory usage increases by 300+MB, GPU usage goes to 30% (Intel HD Graphics 620).
4. VS Code becomes laggy and unusable, it takes a few seconds for any keypress to be reflected.

Does this issue occur when all extensions are disabled?: Yes

I can provide additional debugging information if you tell me what you need 😉

**Comment by Tyriar** [comment]
This is what it looks like on my Windows 10 machine:

![image](https://user-images.githubusercontent.com/2193314/38947363-4a98f5d6-42f1-11e8-9492-edebfd5aa3ff.png)

It takes around 3ms to resize the terminal. Could you do a perf profile in devtools so we can compare? (Help > Toggle Developer Tools)

Also could you try closing all the windows and launching via `code --disable-gpu` and see if that makes a difference?

**Comment by Tyriar** [comment]
I think your problem will be solved by https://github.com/xtermjs/xterm.js/issues/1360 which I'll likely be working on soon. Since Chromium appears to have issues rendering with your GPU we will allow you to fallback rendering in the DOM.

**Comment by costincaraivan** [comment]
@Tyriar As far as I remember Electron has recently bumped the Chromium version. Has VS Code picked up the latest Electron or is it planning to do it soon? Maybe that could help with the hardware acceleration issues?
