### ISSUE TITLE
Powersave mode (Reduce RAM & CPU usage)

### ISSUE THREAD

**Issue by alex20465** [Microsoft/vscode#48119]
Finally vscode can use a lot of resources depending of project source-code size. CPU and RAM usage can be intense. I would like to suggest a powersafe mode switch, in which vscode disables all language-services and auto-completion suggestions.

The enabled powersave mode should reduce RAM and CPU usage at maximum level.

**Comment by ramya-rao-a** [comment]
> I would like to suggest a powersafe mode switch, in which vscode disables all language-services and auto-completion suggestions.

Can you not do this at present by disabling the extensions that provide the language-service?
