### ISSUE TITLE
[folding] Allow to specify if decorator should hide in collapsed region

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#4812]
When you define `decorators` for an editor (`activeEditor.setDecorations`), you must define a `Range`, which can be a specific line where you want to add that decorator (an image with `gutterIconPath` for instance).

But if you **Fold** the lines where this decorator is defined, the icon is not hidden with the lines, but instead, it is shown in the line where the folding starts.

I didn't find anything in `line` or `decorators` that could be used to _detect if the line is folded_, so I think that the folding engine should be taking care of that, right?

Thanks in advance

**Comment by aeschli** [comment]
What you see is what's expected. The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand fucntions and their decorations, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.

**Comment by aeschli** [comment]
@alefragnani If you could add also a code snippet that would be great. That way I can use this as test once we add language agnostic folding.
Thanks a lot!

**Comment by alefragnani** [comment]
Hi @Tyriar , I will post a code snippet latter, when I go back to my home :smile: , but in the meantime you could see the same behavior using **breakpoints**. 

If you set a **breakpoint** inside a function and fold the entire function, the **breakpoint** is presented in the folding line.

If that is the expected behavior, than it's ok... I just thought it should suppress the icon.

Thanks

**Comment by alefragnani** [comment]
Hi @aeschli ,

The code is fairly simple. I just create a `TextEditorDecorationType` and assign it to the `vscode.window.activeTextEditor` with an array of `Range`, which each element defines a line in the text.

* Creating the decoration 
```typescript
    var bookmarkDecorationType = vscode.window.createTextEditorDecorationType({
        gutterIconPath: pathIcon,
        overviewRulerLane: vscode.OverviewRulerLane.Full,
        overviewRulerColor: 'rgba(21, 126, 251, 0.7)'
    });
```

* Defining the lines that will show the decoration. Each `activeBookmark.bookmarks` element is a `number` that represents a line number in the text
```typescript
        var books: vscode.Range[] = [];
        for (var index = 0; index < activeBookmark.bookmarks.length; index++) {
            var element = activeBookmark.bookmarks[index];
            var decoration = new vscode.Range(element, 0, element, 0);
            books.push(decoration);
        }
```

* Adds the set of decorations to the `activeTextEditor`
```typescript
    vscode.window.activeTextEditor.setDecorations(bookmarkDecorationType, books);
```

As you can see, the decoration is defined to individual lines, to display the icon in the `Gutter` (like _breakpoints_). But then, when the code is folded, the icon is shown in the folding line. Take a look at the GIF below.

![bookmarks-folding](https://cloud.githubusercontent.com/assets/3781424/14194900/9915fe26-f789-11e5-89cd-7c88a71bf113.gif)


Thanks for your help

**Comment by aeschli** [comment]
@alefragnani Ah, now I understand. Ignore my first comment (I removed it).
There's no API for you to find out if a line is visible or not. We actually try to avoid that.
Would it make sense that you could specify if your annotation should hide for a folded region?
@alexandrudima Alex, FYI.

**Comment by alefragnani** [comment]
@aeschli No problem. In fact it was my fault, because I should have added this GIF right in the first post :smile: 

About your suggestion, I totally agree :+1: . 

Thanks again

**Comment by aeschli** [comment]
For the May release I added a new setting so that the fold controls stay always visible:
`"editor.showFoldingControls": "always"`

**Comment by xttn** [comment]
Hi @aeschli , fold controls avaiable on version 1.12.1 ??
`"editor.showFoldingControls": "always"`

**Comment by aeschli** [comment]
It will be in 1.13

**Comment by aeschli** [comment]
Sorry, I closed the wrong issue.

**Comment by martin77s** [comment]
"editor.showFoldingControls": "always"
stopped working in 1.17

**Comment by aeschli** [comment]
Thanks @martin77s, I created #35885

**Comment by aeschli** [comment]
Since 1.18, decorations inside folded regions are hidden for performance reasons. They are no longer shown in the gutter.
There are no plans to make this configurable.
