### ISSUE TITLE
Escape to close panel

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#48122]
- VSCode Version: 1.22.2
- OS Version: macOS

You can't close by default panel with `esc`. My suggestion is to add keybind by default to close panel with `esc`.

**Comment by bsvipas** [comment]
As a solution, I added this keybind.

```
  {
    "key": "shift+escape",
    "command": "workbench.action.closePanel"
  },
```

Because if I use `escape` it doesn't close all other widgets and `when` clause will be too long.

**Comment by Tyriar** [comment]
@ramya-rao-a well there's `terminalFocus`. Doing this is probably more work than it looks like to get all the cases right:

- Escape in terminal when find widget is up should hide find widget
- Escape in terminal when find widget is not up has the keystroke sent to the shell - this will always be the default behavior as apps like vim need this

I'm 👎 on making this the default.

**Comment by isidorn** [comment]
We will not change the default behavior, user can configure the keybindings for this if he wants to.
All panels have a when clause, so a user could in theory add for each panel a keybinding for esc to close it.

I believe esc to close panel was the default when panel was introduced 2 years ago but we decided against it

**Comment by bsvipas** [comment]
Thanks for explaining it guys, I appreciate that. I'm using SHIFT+ESC to close panel and it works good for me :)
