### ISSUE TITLE
Git Display name

### ISSUE THREAD

**Issue by lostarchitect** [Microsoft/vscode#48125]
Issue Type: <b>Bug</b>

For some reason my git pushes (to the company's internal repo) authenticate with my company credentials but the display name and email are that of my GitHub user, though I've wiped github desktop out of my machine :(

1) Install GitHub desktop (for Windows), and sign into it
2) Install Visual Studio Code
3) Install Git for Windows
4) Clone a non-github repo (such as Microsoft TFS) and find that it says your github displayname and email :(

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.87GB (7.90GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
gitlens|eam|8.2.1
git-project-manager|fel|1.5.1
PowerShell|ms-|1.6.0

</details>

**Comment by joaomoreno** [comment]
> it says your github displayname and email

Where does it say that? Can you show me a screenshot?

**Comment by lostarchitect** [comment]
Sure, it says it on the Microsoft TFS web interface...
![git weirdness](https://user-images.githubusercontent.com/18385102/39008084-9e4b802c-43ff-11e8-8a11-42ad9abc9a66.png)

To be honest I have no idea if this is a Microsoft TFS bug or a Visual Studio Code bug, or possibly even a Git for Windows bug.  But on account that I login to TFS with the work credentials I feel it could be more likely that side, but then again it wouldn't have knowledge of the github displayname and email.

**Comment by lostarchitect** [comment]
Yes, that's what I mean, so when I push a commit that commit has my Github display name and (fake) email on it in TFS.

Thanks, James.

**Comment by joaomoreno** [comment]
James, you need to configure your local git user name and email. https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
