### ISSUE TITLE
Suggestions to improve the code, break it instead

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#48132]
Issue Type: <b>Bug</b>

Since the recent update, I constantly get the suggestion "[js] File is a CommonJS module; it may be converted to an ES6 module.".

Just like with #38773, I feel this has been again enabled by default prematurely.

As others have brought up in #47299, this is counter-productive. The fact that it is enabled by default is a bug IMHO.

If a context for the current code can't be established without any doubt, then no assistence features should be enabled that would break the code if applied in an incompatible environment.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|15.80GB (4.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe landslide/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
vscode-esformatter|how|1.5.2
vscode-docker|Pet|0.0.26

</details>

**Comment by mjbvz** [comment]
Tracked by https://github.com/Microsoft/TypeScript/issues/23391

Set `"javascript.suggestionActions.enabled": false` to disable these
