### ISSUE TITLE
Clicking tab area under title bar causes Folder to close

### ISSUE THREAD

**Issue by Shaggy13spe** [Microsoft/vscode#48135]
![vscode_bug](https://user-images.githubusercontent.com/630205/38939820-bfbd0dd4-42f6-11e8-91de-5cc445aa635e.gif)

Issue Type: <b>Bug</b>

With a folder loaded, click on the tab area just below the title bar. Causes VS Code to close the current working folder.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1364301|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitflow4code|Gre|1.1.0
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
gitlens|eam|8.2.1
mssql|ms-|1.3.1
debugger-for-chrome|msj|4.3.0
java|red|0.23.0
code-spell-checker|str|1.6.7
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0

</details>

**Comment by bpasero** [comment]
This probably is https://github.com/Microsoft/vscode/issues/35361

As a workaround, configure `"window.nativeTabs": false`

**Comment by Shaggy13spe** [comment]
I already had that configuration set to false, but it still does it
