### ISSUE TITLE
[loc][Query] Context and better support for plurals

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48144]
For string below community member asked to provide context for placeholder, and also support for plurals in different languages. As it is probably difficult to translate in current state.

**Original comment**
BG ISSUE - What are the variables? Also, needs support for plurals.
by lyubomirv, 5 months ago
PL ISSUE - This needs better support for plurals to be translated nicely.
by wojtekmaj, 5 months ago

**Context**
src/vs/editor/browser/widget/diffReview:English (en):plaintext:header

**Resource**
vs_editor

**String Hash**
6434f4fde2ca6a67bdc0778b3406a765

**String text**
Difference {0} of {1}: original {2}, {3} lines, modified {4}, {5} lines

**Comment by alexandrudima** [comment]
I've extracted the plural to separate nls calls and I've added explanations:

```js
header.setAttribute('aria-label', nls.localize({
	key: 'header',
	comment: [
		'This is the ARIA label for a git diff header.',
		'A git diff header looks like this: @@ -154,12 +159,39 @@.',
		'That encodes that at original line 154 (which is now line 159), 12 lines were removed/changed with 39 lines.',
		'Variables 0 and 1 refer to the diff index out of total number of diffs.',
		'Variables 2 and 4 will be numbers (a line number).',
		'Variables 3 and 4 will be "no lines", "1 line" or "X lines", localized separately.'
	]
}, "Difference {0} of {1}: original {2}, {3}, modified {4}, {5}", (diffIndex + 1), this._diffs.length, minOriginalLine, originalChangedLinesCntAria, minModifiedLine, modifiedChangedLinesCntAria));
```

**Comment by josefhosek** [comment]
@alexandrudima Thanks! We just got one additional comment where this change to your comment was suggested:
Current: Variables 3 and **4** will be "no lines", "1 line" or "X lines", localized separately.
Fix: Variables 3 and **5** will be "no lines", "1 line" or "X lines", localized separately.

Can you please confirm this? Thanks!
