### ISSUE TITLE
[loc][Query] Localizability question for "Command"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48141]
For string below community members have been discussing whether it is localizable or not. Can you please confirm what's the correct approach? Thanks!

**Original comment**
NL ISSUE - This refers to the Command-key on a Mac keyboard (see Context), so it should not be translated. by brmlmn, 3 months ago
TA - Cannot Translate Because its a Key name in Keyboad by AvinashRavi, 6 months ago
CA_ES I'm not quite sure of the typical transaltion of 'Command' key to Catalan as I don't use Mac OS. by JaumeFerrarons, 8 months ago

**Context**
src/vs/base/common/keybindingLabels:English (en):plaintext:cmdKey.long

**Resource**
vs_base

**String Hash**
7a2d237749013f545d5e5236697232d8

**String text**
Command

**Comment by alexandrudima** [comment]
I've added the following comments:

```
ctrlKey: nls.localize({ key: 'ctrlKey', comment: ['This is the short form for the Control key on the keyboard'] }, "Ctrl"),
shiftKey: nls.localize({ key: 'shiftKey', comment: ['This is the short form for the Shift key on the keyboard'] }, "Shift"),
altKey: nls.localize({ key: 'altKey', comment: ['This is the short form for the Alt key on the keyboard'] }, "Alt"),
metaKey: nls.localize({ key: 'windowsKey', comment: ['This is the short form for the Windows key on the keyboard'] }, "Windows"),


ctrlKey: nls.localize({ key: 'ctrlKey.long', comment: ['This is the long form for the Control key on the keyboard'] }, "Control"),
shiftKey: nls.localize({ key: 'shiftKey.long', comment: ['This is the long form for the Shift key on the keyboard'] }, "Shift"),
altKey: nls.localize({ key: 'altKey.long', comment: ['This is the long form for the Alt key on the keyboard'] }, "Alt"),
metaKey: nls.localize({ key: 'cmdKey.long', comment: ['This is the long form for the Command key on the keyboard'] }, "Command"),

ctrlKey: nls.localize({ key: 'ctrlKey.long', comment: ['This is the long form for the Control key on the keyboard'] }, "Control"),
shiftKey: nls.localize({ key: 'shiftKey.long', comment: ['This is the long form for the Shift key on the keyboard'] }, "Shift"),
altKey: nls.localize({ key: 'altKey.long', comment: ['This is the long form for the Alt key on the keyboard'] }, "Alt"),
metaKey: nls.localize({ key: 'windowsKey.long', comment: ['This is the long form for the Windows key on the keyboard'] }, "Windows"),

```

I don't know if they should be localized or not, I am sorry I am not an expert. I do believe in some languages they like to localize certain things. e.g. in German they use `STRG` instead of `CTRL`

![image](https://user-images.githubusercontent.com/5047891/38981473-cbf999cc-43bf-11e8-8bf0-1eda2ae14c01.png)
