### ISSUE TITLE
Build task removes slashes in path

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#48149]
Issue Type: <b>Bug</b>

After I updated to the current version, when running a task I am now getting an error saying the path doesn't exist because the `\` have been removed.

I have no `.vscode/tasks.json` file set up. All I have is a `tsconfig.json`, and that is what I am telling the editor to watch. Before, it would run the task, now it is removing the slashes when running the task.

![run task](https://user-images.githubusercontent.com/1571806/38949012-c2a29400-4306-11e8-8909-cb9e5cead235.png)

```
Executing task: tsc --watch -p c:\Users\rnaddy\Documents\vscode\projects\red5\tsconfig.json <

error TS5058: The specified path does not exist: 'c:UsersrnaddyDocumentsvscodeprojectsred5tsconfig.json'.
The terminal process terminated with exit code: 1
```

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz (8 x 2794)|
|Memory (System)|15.69GB (6.77GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|0.25.0
vscode-intelephense-client|bme|0.8.8
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
lualinter|dcr|1.0.3
vscode-hasher|dee|1.0.1
githistory|don|0.4.0
vscode-html-css|ecm|0.2.0
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.15
vscode-lua|gcc|0.1.2
minify|Hoo|0.3.0
html-tag-wrapper|hwe|0.2.3
composer|ika|0.7.1
docthis|joe|0.6.0
docomment|k--|0.0.18
Lua|key|0.0.9
gml-support|lia|1.4.4
translatorplus|lky|1.1.2
Go|luk|0.6.78
HTMLHint|mka|0.4.0
vscode-apache|mrm|1.1.1
vscode-pugbeautify|mrm|1.0.2
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.3.0
php-docblocker|nei|1.6.0
indent-rainbow|ode|7.2.2
laravel-blade|one|1.18.0
vscode-code-outline|pat|0.1.0
material-icon-theme|PKi|3.3.0
java|red|0.23.0
vscode-icons|rob|7.22.0
sass-indented|rob|1.4.9
bash-debug|rog|0.2.0
laravel-artisan|rya|0.0.17
yo|sam|0.9.3
code-settings-sync|Sha|2.9.0
shader|sle|1.1.2
laravel-goto-controller|ste|0.0.2
Align|ste|0.2.0
code-spell-checker|str|1.6.7
html-preview-vscode|tht|0.1.1
vscode-lua|tri|0.12.4
vscode-todo-highlight|way|0.5.12
markdown-all-in-one|yzh|1.1.2

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@TheColorRed this works for me without problems. Which shell do you have configured for the terminal?

**Comment by TheColorRed** [comment]
@dbaeumer I am using git bash for my terminal

**Comment by MattConrad** [comment]
I have the same issue, running on Win 10 x64, and I am also using Git Bash as a terminal.

**Comment by dbaeumer** [comment]
This is a know issue when using bash. Dups https://github.com/Microsoft/vscode/issues/35593.

Currently the task engine assumes that when running under Windows the path separator is `\`. However this is not true for bash implementations.
