### ISSUE TITLE
JSDoc tags lost in IntelliSense documentation for import alias 

### ISSUE THREAD

**Issue by wordofchristian** [Microsoft/vscode#48148]
- VSCode Version: 1.22.2
- OS Version: macOS 10.13.3

I have a utils.js file with the following exported function

```javascript
// utils.js

/**
 * Given a word, this function will return the word with the correct indefinite article (a/an) prepended
 * @example ```
 *  indefinitize('banana'); //=> "a banana"
 * ```
*/
 export function indefinitize() {
}
```

When I type the name of the function  in another file I get the expected intellisense popup with examples listed:

![capture d ecran 2018-04-18 10 30 27](https://user-images.githubusercontent.com/555044/38948170-99f67d4a-42f3-11e8-9a9d-0dcf9a1f9594.png)

but as soon as I import the function intellisense breaks and only shows the description:

![capture d ecran 2018-04-18 10 35 35](https://user-images.githubusercontent.com/555044/38948374-44c1fc4a-42f4-11e8-8ac2-fc53c5011dca.png)

Is this a problem with intellisense or is there another way to write the jsdoc comments to keep the information attached? 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23518
