### ISSUE TITLE
Computer freezes while update installer runs

### ISSUE THREAD

**Issue by immersivegamer** [Microsoft/vscode#48143]
- VSCode Version: 1.22.1 and previous
- OS Version: Windows 10 Enterprise (64-bit)

Steps to Reproduce:

1. Click install update notification. 
2. Enter admin credentials when prompted if not already elevated.
3. At a certain point during while the installer is running the screen freezes for the whole computer. Only for a short while, < 30s, and not for the whole installation. Occurred with the new back ground installer in my update attempt from 1.22.1 > 1.22.2

Does this issue occur when all extensions are disabled?: n/a

**Comment by joaomoreno** [comment]
No application works when that update runs?

**Comment by immersivegamer** [comment]
Correct. No applications update their outputs and inputs to applications and OS are unresponsive.

Just to be extra clear it does not happen during the whole update, only during one of the operations. So the update will start and run for a while and applications and inputs work fine. Then a freeze happens where both applications and inputs stop. This lasts for under 30 seconds (I have not timed it). Then the freeze stops and the update continues.

Mostly a minor issue with manual updates as I run the update and start other work and then a freeze happens halfway through typing or clicking where I have to wait for it to end. It is going to be more puzzling when it happens with the background updater as I won't have a installer window to show that an update is happening to confirm the source of the freeze.

I have been able to reproduce the freeze in the past, so if I need to turn on any logging I can. One issue might be that my work's Win 10 build is slightly different than the standard. I will see if I can reproduce on my personal machine.

Let me know if you have any questions or would like me to test anything.

**Comment by joaomoreno** [comment]
> my work's Win 10 build is slightly different than the standard

What does this mean?
