### ISSUE TITLE
Improve support for #region in javascript code

### ISSUE THREAD

**Issue by fab1o** [Microsoft/vscode#48154]
Support for #region is buggy. It only works for the first region but the second region cannot be folded.

- VSCode Version: 1.23.0-insider
- OS Version: Both Windows 10 and macOS High Sierra

Steps to Reproduce:

1. Create a new javascript file
2. Copy and paste the code below

```js
class Testing {
    // #region prop
    get prop() {
        return 0;
    }
    set prop(p) {}
    // #endregion

    // #region prop2
    get prop2() {
        return 0;
    }
    set prop2(p) {}
    // #endregion
}
```

Result:
![capture](https://user-images.githubusercontent.com/6663243/38956611-1aa98da6-4326-11e8-9f1b-9a54df701604.JPG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Same root cause as https://github.com/Microsoft/TypeScript/issues/23270
