### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by arjunkharbanda** [Microsoft/vscode#48159]
Issue Type: <b>Bug</b>

Python extension is crashing Idk why 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.89GB (2.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1

</details>

**Comment by ramya-rao-a** [comment]
Please log the issue in the repo for the python extension
