### ISSUE TITLE
Tab in Makefile should use tab character, not spaces

### ISSUE THREAD

**Issue by prashantv** [Microsoft/vscode#4815]
- VSCode Version: Version 0.10.13-insider (0.10.13-insider)
- OS Version: OSX 10.11.4

Steps to Reproduce:
1. Open Makefile
2. Press "tab", spaces are inserted.

**Comment by Tyriar** [comment]
It seems make is the inverse of yaml in the respect http://stackoverflow.com/a/2131227/1156119

**Comment by mschuckmann** [comment]
To add insult to injury on this one when I set the tab style to tabs it keeps reverting back to spaces every time I switch to another file and then back to the Makefile.

**Comment by shuffle2** [comment]
This is still a problem, on Windows too.
Selecting "indent using tabs" or "detect indentation from content"(assuming you have some content in the Makefile already, of course) fixes it, but it's not clear what this is actually doing. After selecting one of those settings, the behavior changes but I do not see any changes to settings files.

**Comment by rmunn** [comment]
This should be fixable by the new language-specific settings possible in VS Code 1.9 (currently in Insiders build, scheduled for release in early February). Details here: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_9.md#language-specific-settings

This will allow you to set indentation to tabs for Makefiles, while still keeping it as spaces in other languages if you normally prefer to indent with spaces.

**Comment by sandy081** [comment]
Closing this as new language based settings fixes this.

**Comment by Tyriar** [comment]
@sandy081 is it possible to add a default language specific setting for this since spaces are invalid here (and the opposite for yaml)?

**Comment by sandy081** [comment]
Default language settings are not yet supported and might get planned for February

**Comment by Tyriar** [comment]
@sandy081 created https://github.com/Microsoft/vscode/issues/19733 to further the discussion (wasn't sure if we had an issue).
