### ISSUE TITLE
Flashing in completion details

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#48156]
Issue Type: <b>Bug</b>

Type:
```ts
const abcdefghijklmnop = 0;
```

* Then start typing `abcdefghijklmno` one character at a time.
* The completion details popup (the right half that shows `const abcdefghijklmnop: 0`) will continually flash on and off every time a character is typed.
* This seems to be because it is repeating the completionDetails request every time I type a character. (Another fix would be to avoid deleting the old details until the new details are ready, although those details shouldn't change while you're typing an identifier so maybe better to avoid the repeated request.)

VS Code version: Code - Insiders 1.23.0-insider (88f500e805ecc4efd064f7886c1a5ce8a2a2c087, 2018-04-18T05:12:32.564Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.63GB (2.10GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders src|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
typescript-javascript-grammar|ms-|0.0.39

</details>

**Comment by ramya-rao-a** [comment]
Closing in favor of #48619
