### ISSUE TITLE
"Peek Declaration" doesn't work from the "Peek" popup

### ISSUE THREAD

**Issue by jovere** [Microsoft/vscode#48155]
Issue Type: <b>Bug</b>

When trying to select "Peek Declaration" from the "Peek" popup menu, nothing happens.  I see that there are multiple issues specifically asking for the feature, originally opened in #6857.  However, if the menu option is there and nothing happens, it should be listed as a bug.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:27:19.487Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2793)|
|Memory (System)|23.67GB (14.60GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
yuml|Jai|2.14.0
vscode-clang|mit|0.2.2
cpptools|ms-|0.16.1
perforce|sle|3.1.0
vscode-hexdump|sle|1.6.0
vscode-multiclip|sle|0.1.3
cmake|twx|0.0.17
cmake-tools|vec|0.11.0

</details>

**Comment by ramya-rao-a** [comment]
Can you provide a screenshot? Are you trying to choose the `Peek Declaration` menu option from inside another peek view?

**Comment by ramya-rao-a** [comment]
On which file type did you try this?

**Comment by jovere** [comment]
It's on any C/C++ files.

In the following file, I can right click on "lock" and select "peek declaration".  When I do it from the popup, as shown in the image, *nothing* happens.  If I do it from the regular window (the last line on the screen) it works just as expected.

![contextmenu](https://user-images.githubusercontent.com/10420943/38991482-92e0ef6c-43a3-11e8-9955-d08ac17672a8.png)

**Comment by ramya-rao-a** [comment]
Please log this issue in the repository of the C/C++ extension you are using.
