### ISSUE TITLE
Command editorScroll not working when code is folded

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#48161]
Issue Type: <b>Bug</b>

Reproduced with no extensions.

I have the following keybindings set so I can scroll the editor in line increments than 3:
```
{
    "key": "ctrl+up",
    "command": "editorScroll",
    "args": {
      "to": "up",
      "by": "line",
      "revealCursor": true,
      "value": 10
    }
  },
  {
    "key": "ctrl+down",
    "command": "editorScroll",
    "args": {
      "to": "down",
      "by": "line",
      "revealCursor": true,
      "value": 10
    }
  },
```

When I use ctrl+down in a Lua file without any code folded it behaves as expected: the editor scrolls down 10 lines at a time all the way until the last line of the file is at the very top of the screen.

When I use ctrl+down in a Lua file with all the code collapsed (using `editor.foldAll`) as the editor approaches the end of the file sometimes it only scrolls by a few lines (e.g. 3-4) and eventually it just stops scrolling down entirely, usually long before the last line of the file reaches the top of the screen.

Unfolded code (correct behavior)
![good](https://user-images.githubusercontent.com/484784/38960529-77616c22-432a-11e8-8f05-11e74a6be5b5.gif)

Folded code (incorrect behavior)
![bad](https://user-images.githubusercontent.com/484784/38960539-7f6fcf94-432a-11e8-8fcd-fd7036035bba.gif)

Notice in the last gif how the top line in the editor goes from 31 to 38 (only moving 7 lines instead of 10), then to 48, and that's where it gets stuck. Attempting to scroll down from there with the keybinding does nothing.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.89GB (8.68GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexandrudima** [comment]
A bit weird, but after reverse engineering what that code does, it appears that `"by": "line"` means a buffer line. i.e. as they are painted in the line numbers area.

You can also use "view lines", or how this command calls them, "wrapped lines":
```
[
    {
        "key": "cmd+up",
        "command": "editorScroll",
        "args": {
            "to": "up",
            "by": "wrappedLine",
            "revealCursor": true,
            "value": 10
        }
    },
    {
        "key": "cmd+down",
        "command": "editorScroll",
        "args": {
            "to": "down",
            "by": "wrappedLine",
            "revealCursor": true,
            "value": 10
        }
    }
]
```

The code is at https://github.com/Microsoft/vscode/blob/01169b16171dd381816f08daec793792be7d9151/src/vs/editor/browser/controller/coreCommands.ts#L1074:L1103 and was authored by @sandy081
