### ISSUE TITLE
PowerShell: Non-standard verb causes squiggly lines throughout entire function

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#4816]
- VSCode Version: 0.10.13-insider
- OS Version: Windows 10 Version 1511

Steps to Reproduce:

1. Install PowerShell Extension
2. Write a function that uses an "unapproved" verb
3. Notice the excessive squiggly lines

@daviwil 

![image](https://cloud.githubusercontent.com/assets/466713/14167538/2dcc1a84-f6d9-11e5-9a3e-3a967dd37871.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by egamma** [comment]
Hi @pcgeek86 the warning ranges are produced by the powershell extension.

**Comment by egamma** [comment]
I've tried to move it for you using (https://github-issue-mover.appspot.com/), but I ran into an error, sorry about that

**Comment by pcgeek86** [comment]
Let's see how @daviwil wants to handle it.

**Comment by daviwil** [comment]
Which version of the PowerShell extension are you using? This was fixed recently in Script Analyzer so you shouldn't see it in version 0.5.0 of the PowerShell extension.

**Comment by pcgeek86** [comment]
Here's the version I'm using. Looks like 0.5.0.

![image](https://cloud.githubusercontent.com/assets/466713/14183868/a4c2849c-f72f-11e5-926d-be7218ed3ec3.png)

**Comment by daviwil** [comment]
That's weird, not sure why it's marking the whole thing for you.  Here's what I see:

![image](https://cloud.githubusercontent.com/assets/79405/14184945/86956ed8-f72c-11e5-8849-53c251f1a2ee.png)

Can you try uninstalling/reinstalling the PowerShell extension?  Not sure if that will help, just trying to track down how you could be using an out-of-date Script Analyzer.  I'm shipping it bundled with the extension for now so the PSScriptAnalyzer you might have installed from the Gallery shouldn't affect this.

**Comment by daviwil** [comment]
Also "ext install" may not be the best way to verify the version you have installed, it just shows you the latest version.  Try running the "Extensions: Show Installed Extensions" command to find the actual version that's installed.

**Comment by pcgeek86** [comment]
Here's the output from "Extensions: Show Installed Extensions"

![image](https://cloud.githubusercontent.com/assets/466713/14192834/7bd31e56-f75d-11e5-95ff-9a73b73b26f2.png)

I'll try re-installing it. Where's the best place to track this bug in an open state?

**Comment by daviwil** [comment]
File it over on the vscode-powershell repo if you don't mind.  I might have to get some logs from you to see what's going on.
