### ISSUE TITLE
ES6 import paths starting with "/" should be relative to the web root, not filesystem

### ISSUE THREAD

**Issue by rconnamacher** [Microsoft/vscode#48168]
- VSCode Version: 1.22.2
- OS Version: macOS 10.13.4

In an ES6-native project (using web browser module resolution), all module paths must begin with "." or "/", and paths starting with "/" are relative to the root of the web server that's serving them.

However, Visual Studio Code interprets all paths starting with "/" as relative to the _filesystem root_. So if you type `import "/`, it will begin autocompleting such root filesystem directories as "/dev", "/etc", "/usr", etc. And once entered, Code has no idea where such files as `import App from "/src/js/App.js"` are located.

I've tried setting the `rootDir` and `baseUrl` parameters in this project's `jsconfig.json`, but it does not appear to make any difference.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23547
