### ISSUE TITLE
Less intellisense information for Typescript in VSC due to Arrow Function

### ISSUE THREAD

**Issue by shiba-sama** [Microsoft/vscode#48160]
Issue Type: <b>Bug</b>

I find that when I export a declared function vs an arrow function, it will change whether VSC will display full intellisense information for JSDoc comments.

1. Create a bare-bones TypeScript project, like [this bare-bones example on Github](https://github.com/shiba-sama/bug-report-example). It features two functions: (1) an exported function, and (2) an exported constant with an arrow function assigned to it. The two functions are exported via an index file. Additionally, there is a `tsconfig.json` and a `package.json` file to specify output locations.

2. Publish it to NPM (perhaps not necessary).

3. Create an empty folder and an empty typescript file inside.

4. Add your package via npm, e.g.: `yarn add edc`. (This is an actual working example from the provided Github link.)

5. Add the import statements for your two functions in your newly created blank typescript file.

6. Observe difference in intellisense hoverover information as you type the two functions.

### Expected Result
![expected](https://user-images.githubusercontent.com/37882842/38960179-5c24155c-4318-11e8-9945-a9447eca564c.png)
### Unexpected Result
![unexpected](https://user-images.githubusercontent.com/37882842/38960180-5c3d8db6-4318-11e8-8bb6-90188b252fbc.png)

VS Code version: Code 1.22.2
OS version: Linux x64 4.13.0-38-generic

Extensions: none

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23529
