### ISSUE TITLE
Breakpoint set but not yet bound

### ISSUE THREAD

**Issue by btushar** [Microsoft/vscode#48172]
Issue Type: <b>Bug</b>

Version of VS code is 1.22. When I am trying to debug the code, debug points turns into gray and debugging is not possible at the point. When hovering on gray debug point it shows tooltip error as "Brakpoint is not valid, Breakpoint set but not yet bound"

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|7.89GB (2.62GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
gitlens|eam|8.2.1
tslint|eg2|1.0.28
Angular2|joh|2.16.1
debugger-for-chrome|msj|4.3.0

</details>

**Comment by weinand** [comment]
What debugger are you using?
