### ISSUE TITLE
Markdown Preview Theme Switcher

### ISSUE THREAD

**Issue by BinaryBen** [Microsoft/vscode#48174]
The `"markdown.styles": []` settings appears to allow multiple entries.

I am uncertain how multiple entries currently affects the output to be honest, but is it possible to provide some sort of switching mechanism to choose between different preview styles?

**Comment by mjbvz** [comment]
`"markdown.style"` is a list of all stylesheets to load in the preview, not a list of selectable styles.

Extensions can contribute custom markdown styles and you can use this to change the markdown style per-worskpace. There no plans for a markdown theme selector
