### ISSUE TITLE
Attempting to improve spelling of strings relating to nls.localize()

### ISSUE THREAD

**Issue by jsoref** [Microsoft/vscode#48171]
nls.localize() generally involves human visible output.
Technically there are 2-3 arguments and the main human facing one is the second.
The first argument is often treated as an "opaque" string, but in most systems, it's used to communicate to localizers, so, to some extent, there is value in not having misspellings there either.

I can split out the identifiers if requested...

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@jsoref can you provide me with more details about this. We use Transifex to translate our strings and the system contains both the value and the key.
