### ISSUE TITLE
Win7: Update Failed, Rollback?

### ISSUE THREAD

**Issue by ehmad11** [Microsoft/vscode#48175]
Latest updated failed, it removed code.exe and other files from **Microsoft VS Code** directory, but there was another folder created "**_**" as backup i guess and i am able to run Code.exe from there

log file: [vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1926697/vscode-inno-updater.log)

- Version 1.22.2
- Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
- Date 2018-04-12T16:38:45.278Z
- Shell 1.7.12
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64
- Windows 7
- Installation path: C:\Program Files\Microsoft VS Code

Steps to Reproduce:

1. Start code.exe
2. Click update from notification 

Does this issue occur when all extensions are disabled?: Doesn't matter

**Comment by menadaxdev** [comment]
just checked version 1.22.2 is the latest version so _ folder has the updated files not backup
