### ISSUE TITLE
Cannot read property panel of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48176]
Steps to Reproduce:

1. run `code.sh --user-data-dir <empty folder>`
2. click on extensions viewlet
3. click on the "..." and pick "Show popular extensions"

=>` Cannot read property 'panel' of undefined`

![image](https://user-images.githubusercontent.com/900690/38973099-51ec4d16-43a4-11e8-88e8-4a6f0bded9a8.png)

**Comment by sandy081** [comment]
Fixed by 2ad75aa47bb4ff53c13acf28491c86ac5e1db554
