### ISSUE TITLE
'Updating VS Code...' dialog doesn't use ClearType

### ISSUE THREAD

**Issue by Quppa** [Microsoft/vscode#48178]
- VSCode Version: 1.22.2
- OS Version: Windows 10 1709 (16299.371)

Steps to Reproduce:

1. Update from Visual Studio Code 1.22.1 to 1.22.2.
2. Observe 'Updating VS Code...' dialog box.

![2018-04-19 vs code](https://user-images.githubusercontent.com/2142963/38975454-3b3910de-43f1-11e8-86ba-6177d19dd96c.png)

Does this issue occur when all extensions are disabled?: Yes

Somewhat related to https://github.com/Microsoft/vscode/issues/24957, but this dialog doesn't look to be part of the main UI (I can't actually find where it's defined in the code).

Additionally, is 'VS Code' correct here? My feeling is that the dialog should use the unabbreviated 'Visual Studio Code'.

**Comment by joaomoreno** [comment]
This is OK.
