### ISSUE TITLE
Updating IntelliSense never stops, code naviagtion can't work when it happens

### ISSUE THREAD

**Issue by pansila** [Microsoft/vscode#48177]
Issue Type: <b>Bug</b>

I'm using Visual Studio Code for my C/C++ project, IntelliSense works well when I just open the project, but after a while with some modifciatons, the updating intenllisense icon on the right bottom bar will show up and seems never to stop. It makes the code navigation fail to work (Go to definition - F12). I have to reopen the project to stop the updating, but soon the problem comes back again.
![](https://i.loli.net/2018/04/19/5ad82d83dc3e6.jpg)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G4400 @ 3.30GHz (2 x 3312)|
|Memory (System)|7.91GB (3.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|0.1.1
vscode-hexo|cod|1.0.1
vscode-eslint|dba|1.4.8
jupyter|don|1.1.4
gitlens|eam|8.2.1
vscode-npm-script|eg2|0.3.3
docthis|joe|0.6.0
python|ms-|2018.3.1
cpptools|ms-|0.16.1
embrace|myc|1.0.0
vetur|oct|0.11.7
vuehelper|oys|0.1.0
vscode-journal|paj|0.5.0
vscode-code-outline|pat|0.1.0
code-settings-sync|Sha|2.9.0
code-spell-checker|str|1.6.7
rf-intellisense|Tom|2.0.0
vim|vsc|0.11.4
markdown-all-in-one|yzh|1.1.2

</details>

**Comment by mjbvz** [comment]
Please file this against the cpptools extension
