### ISSUE TITLE
Quicksuggestions inside snippets break tab-stops

### ISSUE THREAD

**Issue by NiekPas** [Microsoft/vscode#48187]
- VSCode Version: 1.22.2 (`3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9`)
- OS Version: Ubuntu 16.04.4 LTS

Steps to Reproduce:

1. Create a .js file (or set Language Mode to `JavaScript`).
2. Type `for`.
3. Press <kbd>TAB</kbd> to expand the `for` loop snippet.
4. Press <kbd>i</kbd> to set the counter variable to `i` (as is standard in many languages).
5. Press <kbd>TAB</kbd>.

**Expected behavior**: <kbd>TAB</kbd> causes cursor to move to next tab stop, i.e. the name of the `array` variable.

**Actual behavior**: <kbd>TAB</kbd> causes `if` snippet to expand.

Does this issue occur when all extensions are disabled?: Yes

I realize this happens because **I have `editor.quickSuggestions` set to `true`**, and indeed the issue goes away if i set this to `false`, but that's far from an ideal solution.

**Comment by ramya-rao-a** [comment]
This is being discussed in #45716
