### ISSUE TITLE
Translations are missing key SelectStartMenuFolderBrowseLabel for file Default.isl

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4818]
The translations are missing a proper translation for the key SelectStartMenuFolderBrowseLabel in file vscode-distro\build\tfs\win32\i18n\Default.resx.lcg. The item is still in English in all translations.

**Comment by dbaeumer** [comment]
@johnliu2016 can you please forward this to the translation team.

**Comment by johnliu2016** [comment]
@dbaeumer ported loc team

**Comment by dbaeumer** [comment]
@johnliu2016 Thanks!

**Comment by dbaeumer** [comment]
@johnliu2016 this is fixed in the latest translation I received today. Feel free to close.

**Comment by johnliu2016** [comment]
@dbaeumer Double confirmed with loc team. Thanks
