### ISSUE TITLE
Terminal is slow on the latest version of insiders

### ISSUE THREAD

**Issue by PooLP** [Microsoft/vscode#48182]
Hi,

The terminal, when performing a gulp or webpack task is extremely slow on the latest version of insiders.

Do you have the same problem?

- VSCode Version: 1.23-insiders
- OS Version: Windows 10 Pro 1709 - 16299.371

Does this issue occur when all extensions are disabled?: Yes

Thanks,
PooLP

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/48193 then.
