### ISSUE TITLE
Allow to hide progress icon while checking for updates in the background

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#48185]
- VSCode Version: 1.22.2
- OS Version: Windows 10

VS Code regularly checks for updates in the background. While that's awesome I don't really want to know about it. Currently, while it is doing that, the progress icon appears on the cog on the lower left side:
![image](https://user-images.githubusercontent.com/530988/38981175-adf78992-43b6-11e8-9583-22f964a02432.png)
And it grabs my attention for no reason and steals 1-2 seconds from me.

My suggestion: Only display the progress icon when an update check is manually triggered by the user.

**Comment by burtek** [comment]
My suggestion: let the user decide whether or not he want the icon visible

**Comment by letmaik** [comment]
Sure, the question is: what's the default? And for what reasons would users need to know that an automatic update check happens? In my opinion, there should only be an icon after update checking if it turns out that extensions got updated and VS Code needs to restart to apply them -- it's up to the user to do it now or later. The existing notifications for VS Code montly updates are fine as they are.

**Comment by burtek** [comment]
> And for what reasons would users need to know that an automatic update check happens?

ell, having all the things going on with privacy (Facebook, data leaks etc) I guess people want to know whenever application does something behind their back...

**Comment by letmaik** [comment]
Definitely, but it's like the initial info and opt-out option for telemetry. Once it's enabled you don't get an indication each time a telemetry event is sent to Microsoft.
