### ISSUE TITLE
Heavy CPU and Memory usage

### ISSUE THREAD

**Issue by ajayns** [Microsoft/vscode#48184]
- VSCode Version: 1.22.2
- OS Version: Ubuntu 16.04

Heavy Memory usage (about 2-3GB) and CPU (25-50%) constantly by code as I simply start it. It seems to persist even extensions disabled. 

Below screenshot is a few seconds from starting up code

![image](https://user-images.githubusercontent.com/20743219/38992824-895b48be-43ff-11e8-9e0b-1da026d68192.png)

Steps to Reproduce:

1. Launch VS Code
2. Wait for a while

Does this issue occur when all extensions are disabled?: Yes

**Comment by ajayns** [comment]
Adding on, this happens way faster when extensions are not disabled and also persists after I close code as these processes persist in the background even after closing.

**Comment by ajayns** [comment]
Okay it doesn't seem to be happening for all projects. There was this one project which I used `yarn link` and the tester inside itself used `yarn link <project-name>` so I assume Code was going through an endless loop, causing this issue as it symlinked to itself.

**Comment by ssteinerx** [comment]
@ajayns If a `yarn link` causes an endless loop, that is a real bug and should be filed with a test case.

**Comment by bpasero** [comment]
@ajayns 
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by ajayns** [comment]
What basically happened is I used `yarn link` on a folder and then within that folder in another project I `yarn link <project-name>`. So basically it cause some sort of infinite symlink loop? It's persists even when I have disabled extensions and only happens in this specific case. So I believe this infinite loop I caused by mistake could be the reason?

Maybe it's a mistake from my side doing so, but then, there should be some fix for Code so that it doesn't glitch away like this.

**Comment by bpasero** [comment]
@ajayns
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by mjbvz** [comment]
@ajayns Please try upgrading to typescript@next in your workspace by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions Some similar problems have been fixed in typescript@next

**Comment by mjbvz** [comment]
Closing as we have not heard back on this issue
