### ISSUE TITLE
Source Control hangs

### ISSUE THREAD

**Issue by nadeem-abbasi** [Microsoft/vscode#48196]
Issue Type: <b>Bug</b>

Start visual studio and try to commit something after a while. the source control panel won't respond. 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.14.1
composer-support-client|Hyp|0.16.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.3.1
php-intellisense|fel|2.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
angular1-code-snippets-johnpapastyle|lpe|0.1.0
vscode-icons|rob|7.22.0
JavaScriptSnippets|xab|1.6.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
@nadeem-abbasi Can you record a video recording of the behaviour?
