### ISSUE TITLE
Test: Stack frame paging

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4819]
- [x] win - @alexandrudima 
- [x] mac - @joaomoreno 
- [x] linux - @v-pavanp 

Previously we only supported showing 20 stack frames in the call stack pane in debug viewlet. Now if a call stack has more than 20 stack frames it is possible to load the additional stack frames. Verify:
* If there are more than 20 stack frames the call stack view shows this and makes it possible to load additional stack frames.
* If there are less than 20 stack frames or if all stack frames are loaded the call stack view does not allow to load additional stack frames

**Comment by joaomoreno** [comment]
Thanks for the sample script...

**Comment by isidorn** [comment]
```javascript
function fib(t) {

    if (t < 2) {
         return 1;
    }

    return fib(t - 1) + fib(t - 2);
}

fib(50)
```

**Comment by joaomoreno** [comment]
Thanks!
