### ISSUE TITLE
Update to 1.22.2 Failure

### ISSUE THREAD

**Issue by bhelyer** [Microsoft/vscode#48199]
Windows 10, 64 bit. Updating from 1.22.1 (I think) to 1.22.2 gave this message, and now I have to reinstall Code.

![capture](https://user-images.githubusercontent.com/24411/38987499-1dea50f0-4424-11e8-8535-323c86ccbe87.PNG)

The log:

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1927785/vscode-inno-updater.log)

**Comment by DanielMurker** [comment]
Receiving a similar issue attempting to update to the same version.

Win10 64 bit, Enterprise Edition
Attempted to reboot?: Yes.
Running VS Code as administrator?: Yes.

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1929057/vscode-inno-updater.log)
