### ISSUE TITLE
What would it take to enable MarkDown link local file path suggestions?

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#48194]
I like how VS Code autocompletes paths for things like JS `import` statements, HTML `src`, `href` attributes etc. I would like the same to happen for MarkDown links, so this is in part a feature request and a call for help when it comes to figuring out how to enable it in VS Code so I can contribute a PR for this, and in part (if the feature request is not approved or just to bridge the gap before it lands) a call for help when it comes to figuring out how to enable this in a VS Code extension - whether it is possible at all, what APIs to use and whether it is possible without enumerating the files myself but instead using VS Code to give the list of suggestions the same way it does currently for the scenarios above.

**Comment by jrieken** [comment]
Even better - VS Code is built to allow this to achieved with an extension. Check out this sample: https://github.com/Microsoft/vscode-extension-samples/blob/master/completions-sample/src/extension.ts. You wanna do something like 

```ts
vscode.languages.registerCompletionItemProvider({ scheme: 'file', language: 'markdown'}, {
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
			
        // figure the context using document and position and compute siblings
    }
});

```

**Comment by TomasHubelbauer** [comment]
This doesn't seem like a complete solution. I want to achieve parity in behavior with existing code feature of suggesting local path to complete at points where it makes sense, but my extension's completion provider was never called for me except for when pressing `Ctrl+.`. (I am using your example code.)

I know there is some sort of ranking involved thanks to #20870.

Unless I am able to influence when the suggestion list should definitely show up (every time you enter the `[` area of the MarkDown link), this extension doesn't make any sense as it will not provide the desired behavior.

Is there a way to influence the score so that when I am in that region, I make VS Code display that suggestion list no matter what? (Like it does for HTML and JS currently out of the box.)

**Comment by jrieken** [comment]
>  (every time you enter the [ area of the MarkDown link)

It's called trigger character which you can provide when calling vscode.languages.registerCompletionItemProvider `

**Comment by TomasHubelbauer** [comment]
Thank you for all your help, @jrieken. I have developed this extension and published it to the Visual Studio Code marketplace:

[MarkDown Link Suggestions](https://marketplace.visualstudio.com/items?itemName=TomasHubelbauer.vscode-markdown-link-suggestions) VS Code extension
