### ISSUE TITLE
[mitigated] Electron 2.0.x: integrated terminal gets slower after some usage 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48193]
From @cra0zy 

> Integrated terminal is bugged a bit, the more text it has the slower it gets, To repro it just type in help and try to use it, it becomes very unresponsive. (This was tested on Fedora 27 x64)
> Tested on another Linux device and the same thing occurs there, so its a global Linux x64 problem it seems.

This seems to be the Linux manifestation of electron/electron#12042 then.

**Comment by Tyriar** [comment]
For anyone experiencing this problem, try running this to workaround:

```
code-insiders --ignore-gpu-blacklist
```

**Comment by cra0zy** [comment]
Yup, that solves it for me.

**Comment by dhirschfeld** [comment]
I've noticed a huge performance hit recently in the terminal on win7 x64. Could this be the same issue? It  makes the terminal pretty unusable for me.
```
Version 1.23.0-insider
Commit c1cd4378c5e5dc434ed959e13556d05240a8ca18
Date 2018-04-20T05:17:25.189Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64
```

**Comment by Tyriar** [comment]
One way we can work around this is to fallback to a DOM renderer when 2d canvas hardware acceleration is disabled https://github.com/xtermjs/xterm.js/issues/1360

**Comment by OnlyLys** [comment]
@Tyriar Interestingly enough I think it may really be due to some GPU driver blacklist. I updated my Intel iGPU's drivers (even though I have VS Code running on my dedicated Nvidia GPU) and performance increased significantly. The slowdown due to large amounts of text being on screen is gone.

**Comment by Tyriar** [comment]
This is now fixed/mitigated after https://github.com/Microsoft/vscode/issues/36913. Whenever you're having GPU problems it's a good idea to update your drivers, other than that if the terminal is renderer really slowly now VS Code should suggest moving to the fallback DOM renderer which doesn't use canvas. You can also do this manually with this setting:

```
"terminal.integrated.rendererType": "dom"
```
