### ISSUE TITLE
Provide an action to collapse all views except the focussed view

### ISSUE THREAD

**Issue by yulihGit** [microsoft/vscode#48201]
Issue Type: <b>Feature Request</b>

I've currently got the "open editors", "Folder map" and "Code map" and "Gitlens" open. Everything is very cramped. Would be nice if the left panel sub windows would dynamically "reveal/open up" upon mouse hover and revert once curser leave the left panel.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

**Comment by ramya-rao-a** [comment]
You can collapse these sections at the moment. Doesnt that help?

**Comment by yulihGit** [comment]
@sandy081 Hi, sorry for the bad description. So when I click ctrl+shift+E I reveal the Explorer in vscode. In this panel/side bar I normally have 4 sections. Starting from the top, "Open Editors", "Folder/Workspace name", "Code outliner", "Gitlens" and some times "Maven projects" etc. If one would like to quickly navigate in these sections, it could be nice to have the separate sections "open up" (stretch out vertically), when one hover over the section title name, e.g "Gitlens". And then once you move your curser out of the side-bar the sections returns to their original size.

@ramya-rao-a On a laptop or a smaller monitor with multiple sections one has to do quite a few clicking and dragging. I feel like this could be avoided with "dynamic" sections. I'll try to give an explanation, imagine having four sections enabled. If you wanted to have the second section from the top to be "stretched out", you would have to manually drag it and then reset it in order to return to the original setup, or you could click/collapse the third section followed by the fourth section. Then, if you wanted and to return back to previous state, you've had to re-click them at the bottom of the side-bar. Maybe not a big issue really, just something I thought would be nice and possible prevent the interruption of the workflow.

**Comment by sandy081** [comment]
@yulihGit Thanks for the explanation. I do not think this requirement will be implemented as is. But I see your issue of space constraints that lot of views are packed up. Probably an action to collapse all views except the focussed view might be helpful?

**Comment by yulihGit** [comment]
@sandy081 Yeah, interesting thought. Or maybe a behaviour similiar to the following commands:
"command": "workbench.action.maximizeEditor"
"command": "workbench.action.evenEditorWidths"

**Comment by dakaraphi** [comment]
@yulihGit @sandy081 
Having all of these views in the same panel is always going to add additional actions required by the user to manage the layout and I'm not sure there is anything significant that can be done as long as they exist in the same space.

I would prefer this solution of separating these views
https://github.com/Microsoft/vscode/issues/41686

**Comment by sandy081** [comment]
@dakaraphi Agreed distributing views helps a lot. At the same time having some view actions might be handy.

FYI Last milestone I implemented to support contributing view containers in activity bar thereby you can contribute views to the view containers (#43645).
