### ISSUE TITLE
Custom Theme sometimes doesn't load on a fresh start of VSC

### ISSUE THREAD

**Issue by atif089** [Microsoft/vscode#48204]
VSCode Version: 1.22
OS Version: Windows 10 / Mac

This happens randomly when I open the editor. I'm using the Material Theme here https://github.com/equinusocio/vsc-material-theme which sometimes doesn't load when I open the editor. And when this happens I have to perform a lot of steps to get it back.

Is there a way I can debug what's causing this?

Steps to Reproduce:

1. Open VS Code
2. The current theme is not Material theme anymore, but instead the default VS Code theme
3. When I switch to any other theme nothing happens for a few seconds after which I see this
https://i.imgur.com/R3LugOh.png , only then after reloading, I can see the new theme applied.
4. I then have to repeat the last step again to get back Material Theme

Does this issue occur when all extensions are disabled?: Cannot reproduce without extensions.

**Comment by atif089** [comment]
Cross post https://github.com/equinusocio/vsc-material-theme/issues/158

**Comment by bpasero** [comment]
@atif089 can you check when this happens if maybe other UI state is lost. We store the colors in a local storage and maybe that one is broken and does not persist from time to time.

**Comment by equinusocio** [comment]
@atif089 Make sure when you activate a theme the settings file is closed in all vsc windows.

Anyway, i will release a major update next days that should fix any issue of this kind, activating all the theme variants through vsc and no more through a custom menu.

**Comment by aeschli** [comment]
Closing as the material theme pushed a fix (see https://github.com/equinusocio/vsc-material-theme/issues/158#issuecomment-383674153)
