### ISSUE TITLE
Obscured files and folders icons/

### ISSUE THREAD

**Issue by snowstroom** [Microsoft/vscode#48203]
Issue Type: <b>Bug</b>

1) Open folder
2) Click button "Create new file"
3) Click button "Create new file" again
Result: icons folders and files remain obscure.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.4.0-119-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2787)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (0.14GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
beautify|Hoo|1.3.0
Angular-BeastCode|Mik|6.0.12
tslint|eg2|1.0.28
Angular2|joh|2.16.1
python|ms-|2018.3.1
cpptools|ms-|0.16.1
debugger-for-chrome|msj|4.3.0
vscode-icons|rob|7.22.0
python|tht|0.2.3
pdf|tom|0.2.0

(3 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
Can you provide a screenshot to elaborate on what you mean by "obscure"?
Does this happen with extensions disabled? Run `code --disable-extensions`

**Comment by snowstroom** [comment]
Yes, after disable extensions the problem still exists.

![2018-04-20 00-17-08](https://user-images.githubusercontent.com/17876627/39008035-be169342-4431-11e8-9c01-8b8c4f8227c0.png)

**Comment by isidorn** [comment]
Also fixed in latest insiders and will be avaialble in the next stable release
