### ISSUE TITLE
Composite bar: non-pinned view/panel not hiding after going to another view/panel

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48207]
Steps to Reproduce:

1. hide a view (e.g. extensions)
2. open another view
3. show the extensions view again by e.g. View > Extensions
4. click on another view

=> previously this would hide the "Extensions" view again because the user did not actively mark the view as visible again (see the "Keep" action in the context menu)
![image](https://user-images.githubusercontent.com/900690/38993072-db66c8bc-43e2-11e8-96b4-8fbd22c332fa.png)

=> now the view remains even though it should hide

This concept is similar to the preview editor we have in the editor area where a file is only "pinned" when e.g. it becomes dirty.

Not sure if this broke with the introduction of the composite bar or with Sandeeps recent changes.

**Comment by sandy081** [comment]
I will take it up. Moreover I am the one who discovered this issue 😉

**Comment by bpasero** [comment]
@sandy081 all yours then :D
