### ISSUE TITLE
[loc][Query] Localizability for "right" and "left"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48206]
For string below community members are asking if 'right' and 'left' are localizable in this case? Can you please confirm? Thanks!

**Original comments**
IT - @Transifex_CNE_DEU very good question - they have been translated in other languages but it could be that they are not localizable. asking...
by AldoD, 2 months ago
DE ISSUE - We assume that "right" and "left" are translatable. Please check.
by Transifex_CNE_DEU, 2 months ag

**Context**
src/vs/editor/common/config/commonEditorConfig:English (en):plaintext:minimap.side

**Resource**
vs_editor

**String Hash**
b710c4b1b1ccc7b934ecbfb0c41f6351

**String text**
Controls the side where to render the minimap. Possible values are 'right' and 'left'

**Comment by alexandrudima** [comment]
I have changed the string to remove possible values. Possible values come via JSON schema.
