### ISSUE TITLE
[loc][Query] Context needed for strings "%1 Source File"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48215]
For string below community member is asking about the context? Can you please help? Thanks!

**Original comments**
BG ISSUE - Context, please. What is %1 here?
by lyubomirv, 4 months ago

**Context**
build/win32/i18n/messages:English (en):plaintext:SourceFile

**Resource**
setup_messages

**String Hash**
5118cc0fbbe51dc93d364d793829d96b

**String text**
%1 Source File

**Comment by joaomoreno** [comment]
%1 is a programming language / file type

Examples:

- JavaScript Source File
- TypeScript Source File
- Python Source File
