### ISSUE TITLE
Renaming file marks for git delete but not git add

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#4821]
- VSCode Version: 0.10.13-insider
- OS Version: Microsoft Windows [Version 10.0.10586]

Steps to Reproduce:

1. Open a folder of a project using git version control
2. In VCS 'Explorer', right-click file in the folder view (under Working Files) and rename it
3. Switch to Git view.
4. Notice that old name of the file is marked D for delete, and the new name is U for untracked.
5. Outside of VCS, use `git mv` to rename a file, and see VCS correctly picks up the change as 'R' (presumably for 'renamed').

**Comment by joaomoreno** [comment]
This is expected.

If you do the rename using the Windows Explorer and run `git status` they will also show as deleted and added files. Once you commit, rename detection will occur and it everything will be logged as renames by git.

**Comment by leegee** [comment]
Sorry my report was not clear enough.
*Please look again at step 4,* and compare it with your observation of 'just how git works.'
Currently, your product dose not reflect the way git operates, and from your response, I gather that is not the intention.

**Comment by joaomoreno** [comment]
That only works because you are calling `git mv` which automatically stages your files.

The correct analogy to what Code does, that is without the staging, is to run `mv foo bar` instead of `git mv foo bar`.

**Comment by leegee** [comment]
Exactly -- that's why I filed a bug report, because Code mishandles version-controlled files.

**Comment by joaomoreno** [comment]
Code doesn't mishandle version-controlled files. Code works (and should work) just like the Windows Explorer here. It works just like you'd rename a file regardless of git. It works just as you'd run `mv foo bar` in the command line. All of these will make git detect a **delete** and an **add**.

Once you **stage** both those operations, [git will detect that as a **move**](http://stackoverflow.com/questions/7938582/how-does-git-detect-similar-files-for-its-rename-detection).

`git mv foo bar` does these two steps at once: it moves the files and then stages the **delete** and the **add**.

Code shouldn't do that automatically. Let me give you a simple situation why that is:

1. make changes to `foo`
2. stage those changes
3. rename `foo` to `bar`

After those steps, Code will still let you commit the initial changes to `foo` without committing the rename. If Code would automatically stage the move, you'd be stuck with the combination of the file changes and the rename in your staging area, which might not be what you wanted.

**Comment by leegee** [comment]
I do not think it is a question of 'what [I] want' but what I expect.

As I said, I do not expect renaming a file to remove it from version
control.

I am not a regular user of Windows Explorer, so my expectations do not come
from that domain. I am a regular user of git and Linux, so am used to
moving files to rename them.

I'll give up on this issue now -- I am sure someone else will raise it in
the future. Very disappointed to VS Code so obstinate on what seems to be a
straight-forward usability issue.

**Comment by joaomoreno** [comment]
I don't know how else to put it: Code shouldn't stage on move, in the same way that it doesn't stage on file creation and deletion.

**Comment by leegee** [comment]
It's the 'should not' that I am querying -- why should it not? What is Code trying to be? Is there a mission statement...?
I agree that newly created files should not be staged, because I have never met anyone who would expect a new file to automatically be considered as version-controlled.
However, when an operation is performed upon a file that is under version control, I **suppose** most people would expect the operation to effect the state in version control. Thus, when I use code to delete a file under version control, I expect to see it marked as deleted in version control -- and it is. Naturally, then, when I use Code to rename a file, I expect....etc.
We don't know if my supposition is correct, nor if yours is, and since I have not seen a formal objective for Code, I cannot comment further without chasing my own tail.
Perhaps a new ticket, "More Integration with VCS: context menu add/remove/delete/rename" :-)

**Comment by joaomoreno** [comment]
It's not a question of a lack of a mission statement, it's about consistency.

I explained the reason: because the user doesn't necessarily wants to stage a rename when he's just performed it. The same way that the user doesn't want to stage the creation of a file as soon as he does it. Or a deletion. Or a text edit. Or any other operation.

When you add a file it appears as an untracked file in git. And Code shows it as deleted. But it's not staged. Yet, Code is nice and still lets you commit that without staging, by typing in a message and pressing `Commit`.

When you delete a file it appears as a missing file in git. And Code shows it as added. But it's not staged. Yet, Code is nice as still lets you commit that without staging as well.

When you move a file, it appears as a delete and an add in git. And Code shows it as an add and a delete. This is because, similarly to the previous cases, it is not staged. Yet, Code is nice and still lets you commit that without staging. And it will appear in history as a rename.

**Comment by leegee** [comment]
That's nice. That's what I'm talking about. Probably quicker to implement it than write all those excuses above.

/Thank you/.

![image](https://cloud.githubusercontent.com/assets/512816/15772198/b0eff686-2967-11e6-8cf3-04d24a8dc54a.png)
