### ISSUE TITLE
[loc][Query] Context for "Quick picker color for grouping labels."

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48212]
For string below community member is asking about the context, can you please check? Thanks!

**Original comments**
BG ISSUE - What is a 'quick picker color'?
by lyubomirv, 5 months ago

**Context**
src/vs/platform/theme/common/colorRegistry:English (en):plaintext:pickerGroupForeground

**Resource**
vs_platform

**String Hash**
22622b86f29794ad75012e01854e037d

**String text**
Quick picker color for grouping labels.

**Comment by bpasero** [comment]
@josefhosek see this example:

![image](https://user-images.githubusercontent.com/900690/39058349-d90614a4-44bb-11e8-8585-812c2315932e.png)

A quick picker provides fast access to a list of items. Multiple items can be grouped together and separated. The quick pick group color is the blue color for grou plabels on the right.
