### ISSUE TITLE
Telemetry tracking should be opt-in, not opt-out

### ISSUE THREAD

**Issue by elharo** [Microsoft/vscode#48218]
- VSCode Version: 1.2.2
- OS Version: Mac OS X 10.13.3

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/1005544/38997882-736809b8-43bc-11e8-9e74-ae32929e87ed.png)

**Comment by ramya-rao-a** [comment]
This has been answered in detail in https://github.com/Microsoft/vscode/issues/17790#issuecomment-270695861
