### ISSUE TITLE
[loc][Query] Context need for "File on"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48217]
For string below community members are discussing context? Can you please help decide what it is? Thanks!

**Original comments**
ES - I think that string is used on a composited phrase like "File on %d not encountered", so the "%d not encountered" part may be another string entry or from a variable used on the dialog.
by AleksSyntek, 9 days ago
BG ISSUE - What is this?
by lyubomirv, 9 days ago

**Context**
src/vs/code/electron-browser/issue/issueReporterPage:English (en):plaintext:issueSourceLabel

**Resource**
vs_code

**String Hash**
72059e8de65d27dd9e494c05ee66fe1d

**String text**
File on

**Comment by RMacfarlane** [comment]
@josefhosek This is a label for a select that has options "Visual Studio Code" and "An Extension", so the full phrase would be "File on Visual Studio Code" or "File on an extension"

![screen shot 2018-04-19 at 8 57 23 am](https://user-images.githubusercontent.com/3672607/39003439-b811ac34-43af-11e8-8ac9-8db96ce93e3e.png)

**Comment by AleksSyntek** [comment]
Thanks @RMacfarlane for the explanation on this string, so I will maintain the upvote on the translation suggested by default for Spanish.

**Comment by AleksSyntek** [comment]
Also thanks @josefhosek for the escalation help.

**Comment by lyubomirv** [comment]
@RMacfarlane I still don't fully get it. What does it mean for a file to be 'on' something, be it Code or Extension?
