### ISSUE TITLE
William

### ISSUE THREAD

**Issue by acerbill** [Microsoft/vscode#48219]
We have written the needed data into your clipboard because it was too large to send. Please paste.
I can't execute File:New:Project in Visual Studio, because I can't get the option for a new project.
What is wrong?

**Comment by ramya-rao-a** [comment]
VS Code doesnt have the concepts of projects. It works on folders and files. 
Please go through [Getting Started](https://code.visualstudio.com/docs) and [Multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces)
