### ISSUE TITLE
svn status changes on macOS

### ISSUE THREAD

**Issue by cixuuz** [Microsoft/vscode#48229]
- VSCode Version: 1.22.2
- OS Version: macOS High Sierra 10.13.4
- subversion Version: 1.10.0 

The issue is while opening the folder in vs code, the svn status of files in the folder changes. I guess the vs code must touch something part of these files which is captured by svn. 

Steps to Reproduce:

1. svn status
![image](https://user-images.githubusercontent.com/26782336/39013198-af10e246-43e4-11e8-87ac-fe0d918b639b.png)

2. open the folder in vs code, then do svn status again
![image](https://user-images.githubusercontent.com/26782336/39013334-11398752-43e5-11e8-9009-d1cdaa3a5ad2.png)

Does this issue occur when all extensions are disabled?:  Yes

**Comment by joaomoreno** [comment]
What are the effective changes svn reports on those files?

**Comment by cixuuz** [comment]
After fully investigation, I found the issue is raised by Google Drive File Stream. Sorry for this mistake.
