### ISSUE TITLE
Debugger get lost on C++ source files when they have the same name but different paths (shows breakpoint on the wrong one)

### ISSUE THREAD

**Issue by leogcorrea** [Microsoft/vscode#48228]
Issue Type: <b>Bug</b>

Create a project with 2 C++ source files with the same name and extension but in different paths. I'm using the GDB as the debugger. A breakpoint set in one of the source files (/src/file.cpp) when triggered shows the other one (/otherpath/src/file.cpp) as if the breakpoint was set in this second file instead of on the first one.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (4 x 3127)|
|Load (avg)|0, 1, 1|
|Memory (System)|15.61GB (4.21GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
githistory|don|0.4.0
gitlens|eam|8.2.2
python|ms-|2018.3.1
cpptools|ms-|0.16.1
java|red|0.23.0
cmake|twx|0.0.17
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0

</details>

**Comment by weinand** [comment]
Please file this issue against the C++ extension (cpptools).
