### ISSUE TITLE
Can we have multiple language servers per workspace

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#48227]
Is it possible to somehow have multiple language servers per workspace?

I believe I know the answer (due to the simple fact that the stdin/stdout streams would end up being used by multiple lsps and this could be a problem).

**Comment by dbaeumer** [comment]
Yes, even if the server uses stdio for communication. Every server can have its own stdio the client reads and writes from. 

Do you see any problems. 

On a normal web workspace you have a html, css, json, TS/JS and ESLint server running.

Closing the issue. Please ping if something is still unclear.

**Comment by DonJayamanne** [comment]
@dbaeumer 
Sorry but I should have been more specific.
Can we have multiple language servers for the same language in the same workspaces folder?

**Comment by DonJayamanne** [comment]
> In principal yes, but you would need to route the request to the right server using `patterns' for the document selector / filter

Hmm, let me lay it out better.
Our plan is to use a .net language server to provide intellisense, and a python language server to provide some other functionality such as linting (providing a list of problems). This means that both language servers will be working on the same workspace, and same files, but only responding to different messages in the protocol.

Anyways, from what you've told me, we should just try this out.
**Our primary concern was whether this is NOT supported, even if it were to work.**

**Comment by dbaeumer** [comment]
@DonJayamanne that should actually work since you are simply dispatching different requests to different servers.
