### ISSUE TITLE
Make "window.newWindowDimensions" default to "inherit"

### ISSUE THREAD

**Issue by ranolfi** [Microsoft/vscode#48223]
If a window is already active and maximized, opening an existing file will "restore" the window size and position.

The expected behavior would be to maintain whatever window state was in use.

This was addressed in #10864:

@bpasero 2017-01-17
> A new setting `window.newWindowDimensions` allows to control how new windows should open. By default, a new window will open in the center of the screen with small dimensions. If you change this setting to `inherit`, the new window will get the same dimensions as the last active one. Setting it to `maximized` or `fullscreen` will always open new windows either maximized or in fullscreen.

In this new setting's description, it says:

> (...) By default, a new window will open in the center of the screen with small dimensions. (...) Note that this setting does not have an impact on the first window that is opened. The first window will always restore the size and location as you left it before closing.

I believe it's reasonable to change the default value of this setting to be consistent with the behavior of the first window that is launched.

--
- VSCode Version: 1.21.0
- OS: Linux, Windows 10

**Comment by marc2377** [comment]
Wrote a little bit about this here: https://gitlab.com/ranolfi/opensource-todo-list/issues/68
