### ISSUE TITLE
Indenting creates selection when cursor next to first non-whitespace character

### ISSUE THREAD

**Issue by jpotterm** [microsoft/vscode#48221]
### Environment
- VSCode Version: 1.22.2
- OS Version: macOS 10.13.4
- Does this issue occur when all extensions are disabled?: Yes

### Steps to Reproduce

Create a file with the contents:

```
a
```

Put the cursor at the beginning of the file and press `Cmd+]`. The line will indent correctly but the whitespace will be selected when it shouldn't be.

This only happens if the cursor is next to the first non-whitespace character of the line. And only when using `Cmd+]`, not with `Tab`. See screencast:

![ezgif-4-3bb06f8900](https://user-images.githubusercontent.com/134310/39002555-cbd2d65a-43c6-11e8-8d7e-3fa7e8a28024.gif)

**Comment by ramya-rao-a** [comment]
I cant repro this...
Does this occur with extensions disabled? Run `code --disable-extensions`

**Comment by jpotterm** [comment]
Yes, all extensions are disabled and my user settings file is empty. I just tried it on a fresh install of VSCode on a Windows laptop that has never had VSCode on it before and it happened there too. I also tried it on VSCode Insiders and I can reproduce it there as well.

**Comment by ramya-rao-a** [comment]
I see it now when using the keybinding, thanks!

**Comment by jpotterm** [comment]
This is still an issue I run into a few times a week. I'm surprised no one else seems to be annoyed by it, but maybe my usage is unusual. I know you guys are busy so no worries; I just wanted to make sure this doesn't get auto closed due to inactivity.

**Comment by jpotterm** [comment]
Looks like this is fixed in version 1.40.0. Thanks VSCode team!
