### ISSUE TITLE
Show hover on launch config gear

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4822]
- VSCode Version: alpha
- OS Version: OS X 10.11.4

I had a syntactically broken launch.json without being aware of it. It showed up in VS Code like this:

![2016-03-31 11-46-28](https://cloud.githubusercontent.com/assets/1898161/14172008/4bfa27aa-f736-11e5-96c9-9bd2ae227e70.png)

The gear icon showed a red dot which I hadn't seen before and I didn't know what it means.
Hovering over it did not show anything.
I did not spot the tiny squiggly on the opening brace '{'.
I was stuck!

At least we should show a hover on the gear that clearly states that the launch.json is fundamentally broken.

And showing errors more prominently in the json would help too... Why is the squiggly green and not red? It has a fatal error that cannot be ignored.

**Comment by isidorn** [comment]
I agree we should add a hover to make the user experience nicer.

As for the squiggly being green and not red the JSON schema does not allow me to do this.
Please create a feature request against @aeschli 
I know Martin's point is that he is not showing this in red becuase the JSON syntax is not broken.
