### ISSUE TITLE
VS Code Intellisense breaks constantly

### ISSUE THREAD

**Issue by gabrielruss** [Microsoft/vscode#48224]
- VSCode Version: 1.22.2
- OS Version: Windows 10

Steps to Reproduce:

1. Try to import a file multiple layers deep
2. After doing step 1 a few times, Intellisense will break and you will need to restart in order to get it back.

Does this issue occur when all extensions are disabled?: Yes

![2018-04-19 13_14_34](https://user-images.githubusercontent.com/8887997/39007438-d09bae48-43d3-11e8-9154-2c525755d640.png)

**Comment by mjbvz** [comment]
Can you please test upgrading to `typescript@next` in your workspace by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by gabrielruss** [comment]
1. Updated global typescript package with `npm install -g typescript@next`
2. opened VSCode `code --disable-extensions .`

Issue remains

![broke](https://user-images.githubusercontent.com/8887997/39024776-0bd51dae-4411-11e8-941a-e585026e9972.gif)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23556
