### ISSUE TITLE
Missing option for disabling the "Auto Attach" statusbar item

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#48236]
- VSC: v1.22.2

Executing the `Debug: Open launch.json` command makes the "Auto Attach" statusbar item show up:

<img width="106" alt="screen shot 2018-04-20 at 01 39 48" src="https://user-images.githubusercontent.com/1812093/39023577-d12ffb26-443b-11e8-8e90-41a2fe0910bc.png">

And the only way of removing it, that I'm aware of, is reloading the window.

I think this statusbar item has no reason to exist, I see there's already a `Debug: Toggle Auto Attach` command in the command palette, this thing is just wasting a considerable amount of space for toggling a setting. There are already [multiple](https://marketplace.visualstudio.com/items?itemName=anweber.statusbar-commands) [extensions](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands) for adding statusbar items that trigger commands if one really wanted this. @bpasero wouldn't you consider this a poor use of space?

**Comment by weinand** [comment]
The "debug.node.autoAttach" setting got a "disabled" value (which is the default).
