### ISSUE TITLE
VSCode and Vim Emulator/Git Extension Pack problem

### ISSUE THREAD

**Issue by VladaZ** [Microsoft/vscode#48230]
- VSCode Version:1.22.2
- OS Version: 4.9.90-1-MANJARO

Steps to Reproduce:
1. Start VSCode with Vim (0.11.4) and Git extension (0.1.3)
2. After some time, VSCode will become very slow. So the typing letters will appear after a few or more than 10 seconds.

Does this issue occur when all extensions are disabled?: No

**Comment by rebornix** [comment]
Vim will slow down if other extensions are doing heavy work. You can keep an eye on https://github.com/VSCodeVim/Vim/issues/2021 to see if the performance  is being improved there.
