### ISSUE TITLE
Vscode mixed writing ,php to html

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#48238]
version：1.23.0-insider;
theme:dark+(def dark);
question1: set files.associations, HTML does not add the PHP code hints we want;
question2: when HTML writes PHP, the former < symbol is red;

![002](https://user-images.githubusercontent.com/20437381/39025025-1eb13a78-4477-11e8-8c33-df43c530de62.png)

![001](https://user-images.githubusercontent.com/20437381/39024970-b3023bba-4476-11e8-8309-8924b9da7e91.png)

**Comment by roblourens** [comment]
> question1: set files.associations, HTML does not add the PHP code hints we want;

What do you mean code hints? Please be specific about what the problem is.

> question2: when HTML writes PHP, the former < symbol is red;

It looks like you didn't set files.associations for that screenshot. It will work if you set it.

**Comment by lihua06** [comment]
question1: PHP intellisense in HTML file
question2:HTML file Write PHP code < symbol is red,so it's thought to be BUG.This problem appears in most theme.Does this effect have a special effect?
![01](https://user-images.githubusercontent.com/20437381/39090417-00e108e8-4611-11e8-9949-8df5fad8684a.png)

**Comment by lihua06** [comment]
@roblourens these are habits problem, if the vscode team can change is the best.thank you

**Comment by roblourens** [comment]
> question1: PHP intellisense in HTML file

This works for me. Are you using the builtin PHP intellisense, or an extension?

question 2: This is expected unless you set files.associations in this case, did you?

**Comment by lihua06** [comment]
@roblourens  files.associations is set up,Use of builtin PHP intellisense.I hope these can help you

**Comment by roblourens** [comment]
Does the status bar say "HTML" or "PHP" on the bottom right side?

**Comment by lihua06** [comment]
@roblourens display "HTML"

**Comment by roblourens** [comment]
Ok, then the files.associations setting is not being applied. Is that in your user settings? Is it being overridden by a setting in workspace settings?

Can you check whether it's applied when you start with `--disable-extensions`?

**Comment by lihua06** [comment]
@roblourens disable all extensions,has no effect
yes,user settings;open  workspace settings no reaction，interface still displays user settings, and no workspace settings files are visible.
![004](https://user-images.githubusercontent.com/20437381/39101252-a6fb7a34-46c9-11e8-941b-74c85b3af6b4.png)

**Comment by roblourens** [comment]
Can you make sure that the builtin PHP extension is functional by manually changing the language mode to PHP? Click on HTML in the status bar and make sure PHP is in the list that appears, and select PHP.

**Comment by lihua06** [comment]
manually changing PHP file， PHP intellisense normal work

**Comment by roblourens** [comment]
I must be missing something because it seems unlikely that there's a bug in this area. 

Could you open developer tools (Help > Toggle Developer Tools) and check for errors in the console?

**Comment by lihua06** [comment]
@roblourens  errors in the console
![007](https://user-images.githubusercontent.com/20437381/39166204-184f1230-47bb-11e8-892a-d7f996a29c75.png)

**Comment by roblourens** [comment]
Does that show up when you open the php file? What if you set `"php.validate.enable": false`?
