### ISSUE TITLE
Exception when run my extension with other extension

### ISSUE THREAD

**Issue by iHuahua** [Microsoft/vscode#4823]
- VSCode Version:0.10.11
- OS Version:Windows 7

Steps to Reproduce:

1. ext install cpptools
2. yo code 
3. F5

it will stop on :
path.js:line 8
throw new TypeError('Path must be a string. Received ' + util.inspect(path));

**Comment by jrieken** [comment]
@iHuahua What do mean by `yo code`? do you create a new extension that you want to run? What is the _full_ reading of the console?

**Comment by iHuahua** [comment]
@jrieken yeah, i want to create a new extension, everything is right until i run the new extension by F5. Than i had installed the "cpptools" before. 

![qq 20160405101023](https://cloud.githubusercontent.com/assets/2878674/14269404/e265a4ce-fb16-11e5-87d1-bd660740193d.jpg)

**Comment by jrieken** [comment]
this is an node-internal module. what's it the call stack from your code that leads to this?

**Comment by iHuahua** [comment]
@jrieken i had removed cpptools. can you try it by youself?

**Comment by jrieken** [comment]
`yo code` should not install anything related to cpp. Please report the top of the stack as I believe this is then something with the `cpp tools`

**Comment by iHuahua** [comment]
I am sorry to later for reply.
I am a cpp developer, so I had install extension `cpptools` before. I have not modify anything about .vscode.

![stack](https://cloud.githubusercontent.com/assets/2878674/14305264/241b8fb0-fbed-11e5-93ce-62af4ff1feb7.jpg)
![setting](https://cloud.githubusercontent.com/assets/2878674/14305265/242e2c60-fbed-11e5-80b2-11dbffa7316f.jpg)

**Comment by iHuahua** [comment]
@jrieken If I have not reply in time, please email to me, ihuahua#live.com, # => @

**Comment by jrieken** [comment]
Thanks, that's helpful. @delmyers Can you help? This seems to be an issue with the cpp-extension.

**Comment by delmyers** [comment]
This looks like an exception in the language service for the extension. I'll get someone to look at it.

**Comment by delmyers** [comment]
I am having trouble with the GitHub issue mover @egamma, can you help? I keep getting an exception: Cannot call "ez" on null.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscppsamples#4

**Comment by egamma** [comment]
>I am having trouble with the GitHub issue mover @egamma, can you help? I keep getting an exception: Cannot call "ez" on null. 

@delmyers I could move it. I did it from Chrome. I remember I saw the "ez" null error, but I cannot remember whether I saw this error in Chrome or IE.
