### ISSUE TITLE
Bug in VSCode web Marketplace:  wrong repository link at Rainbow CSV plugin page.

### ISSUE THREAD

**Issue by mechatroner** [Microsoft/vscode#48247]
Hello!
I didn't know where to submit this bug, so if you can tell me where I can redirect my request this would be useful too. So for some reason at the Rainbow CSV plugin page ( https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv ) in "Project Details" section there are 3 links to a wrong repository. 
The first link to the repo is correct ( https://github.com/mechatroner/vscode_rainbow_csv ) but it has wrong title which says "mechatroner/vscode" whereas it should be "mechatroner/vscode_rainbow_csv". And the rest of the links are just incorrect.

The repository link in the extension package.json config explicitly points to the right location:

```
    "repository": {
        "type": "git",
        "url": "https://github.com/mechatroner/vscode_rainbow_csv"
    }   
```

Please, help!

**Comment by bpasero** [comment]
@egamma maybe you know

**Comment by egamma** [comment]
I´ve informed the marketplace team.

**Comment by mechatroner** [comment]
Thanks!

**Comment by Hardhik** [comment]
Thanks for reporting :D please feel free to close this issue.

**Comment by mechatroner** [comment]
Thank you very much, @Hardhik !
