### ISSUE TITLE
Code coloring incorrect for 'implements' when 'extends' is also used

### ISSUE THREAD

**Issue by baloodevil** [Microsoft/vscode#4824]
- VSCode Version:0.10.11
- OS Version:Windows 10 Pro

Steps to Reproduce:

1. Add class with signature like:
`export class MyClass extends MyBaseClass implements MyInterface`
2. See that `implements` is incorrectly colored green instead of blue (at least in the default color scheme).  If you remove `extends MyBaseClass`, then `implements` is properly colored blue.

**Comment by Tyriar** [comment]
This is fixed in master, thanks for the report.
