### ISSUE TITLE
WebViewPanel.reveal doesn't focus the tab if already visible

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#48246]
When I have a WebViewPanel open and visible but not active in ViewColumn.Three and I call `WebViewPanel.reveal(ViewColumn.Three);` the panel doesn't become the active editor.

/cc @mjbvz 

Originally from https://github.com/Microsoft/vscode/issues/43713#issuecomment-382902190

**Comment by eamodio** [comment]
While not directly related I also noticed while listening for `WebViewPanel.onDidChangeViewState` it never fires when it becomes visible when it was hidden behind another tab but doesn't become active.

For example, you have 2 tabs in column 1 -- tab 1 (hidden) is the webview, and tab 2 (visible) is another file, and then you have a tab in column 2 that is currently active. If you click the close X on tab 2, which will cause the webview to become visible, but not become active, because the tab in col 2 is still active. No event gets fired.

**Comment by mjbvz** [comment]
I can't repo this in the latest insiders: 

![apr-20-2018 12-02-11](https://user-images.githubusercontent.com/12821956/39068870-b4d9b550-4492-11e8-9d40-91319a2c5031.gif)

```
import * as vscode from 'vscode';
import { join } from 'path';

const catCounterViewType = 'catCounter';

export function activate(context: vscode.ExtensionContext) {
    const cat = vscode.Uri.file(join(context.extensionPath,'media', 'cat.gif')).with({ scheme: 'vscode-resource' })

    let panel: any;

    let disposable = vscode.commands.registerCommand('cat.startCounting', () => {
        if (!panel) {
            panel = (vscode.window as any).createWebviewPanel(catCounterViewType, 'Cat Counter', vscode.ViewColumn.Three, { });
        }
        panel.reveal(vscode.ViewColumn.Three);
        panel.webview.html = contentFor(cat, 0);
    });

    context.subscriptions.push(disposable);
}

function contentFor(cat: vscode.Uri, count: number) {
    return `
        <img src="${cat}" width="200" />
        <b id='counter' style="font-family: 'Comic Sans MS'; font-size: 96px; color: hotpink;"></b>

        <script>
            const counter = document.getElementById('counter');
            let count = ${count};

            setInterval(() => {
                const c = count++
                counter.innerText = c;
                window.parent.postMessage({ count: c }, '*');
            }, 100)
        </script>`;
}
```

The webview always becomes active/focused after `reveal`. Please share some example code

**Comment by eamodio** [comment]
When I run that exact same code on the latest insiders I don't see the behavior you see. What OS are you on? I'm on Windows 10.

**Comment by mjbvz** [comment]
Ok, I was testing on macos. Let me test on windows again.

I also just pushed some fixed for view state events not being fired too. Those should be in the next insiders build

**Comment by mjbvz** [comment]
I just tested this on windows in the latest insiders build. All appears to be working now. Let me know if you still see this issue with the latest insiders
