### ISSUE TITLE
Linux: "window.newWindowDimensions: inherit" ignored if window is minimized

### ISSUE THREAD

**Issue by ranolfi** [microsoft/vscode#48249]
I've got `window.newWindowDimensions` set to `inherit`. It mostly works, unless the editor window was minimized prior to opening an existing file from the file manager. In that case, if it was previously maximized, it'll restore to the default position and state.

**Steps to reproduce:**

1. Have VS Code open and maximized

2. Have `window.newWindowDimensions` set to `inherit`

3. Minimize the window OR click the "Show desktop" button in your Desktop Environment OR use the keyboard shortcut <kbd>Ctrl</kbd> + <kbd>D</kbd> to achieve the same effect

4. From your file manager, open an existing file (by double-clicking if it's associated with VS Code by default; or via "Open with..." otherwise)

- VSCode Version: 1.21.0
- OS: Arch Linux with Cinnamon 3.6.7 and GTK 3.22.30.
Also with Cinnamon 3.8.0 (and Nemo 3.8.0)

**Comment by bpasero** [comment]
@marc2377 can you share a screencast how this looks for you?

**Comment by marc2377** [comment]
Sure.

Now, I did notice it only happens when the Code window is minimized, either by clicking the minimize button or by using the "Show desktop" button in the DE (or, alternatively, using the <kbd>Ctrl</kbd> + <kbd>D</kbd> shortcut)

![2018-04-20 vs code - issue 48249](https://user-images.githubusercontent.com/8507649/39063826-a6593676-44a2-11e8-8cef-d24551f9eb1b.gif)

**Comment by bpasero** [comment]
@marc2377 I cannot reproduce from our insiders release, can you try?  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by marc2377** [comment]
I'll try it, on Thursday probably. Will let you know.

**Comment by bpasero** [comment]
I did that.

**Comment by marc2377** [comment]
Strange.

I'm gonna set up a virtual machine and try a desktop environment other than Cinnamon then.

**Comment by bpasero** [comment]
Any update?

**Comment by ranolfi** [comment]
Not yet but I'll check this weekend and report back
