### ISSUE TITLE
Up Arrow can not move to previous settings-group-title-widget

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#48248]
1. Press <kbd>Down</kbd> to move to next settings-group-title-widget
2. Press <kbd>Down</kbd> to move to next settings-group-title-widget
3. Press <kbd>Up</kbd> to move to previous settings-group-title-widget
Pressing <kbd>Up</kbd> can't move to previous settings-group-title-widget, but pressing <kbd>Up</kbd> twice will move to the previous previous one.
![settings](https://user-images.githubusercontent.com/24318019/39029790-3f71deac-4490-11e8-97b9-830e9b817c70.gif)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|7.89GB (2.91GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|2.7.0
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
svn-scm|joh|1.29.0
debugger-for-chrome|msj|4.3.0

</details>

**Comment by sandy081** [comment]
We are planning to build a new Settings UI and hence marking this out of scope.
