### ISSUE TITLE
Wrong suggestion for padStart in JS

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#48243]
It seems like the suggestion is wrong for `padStart` in JS? Definition is [here](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es2017.string.d.ts)?

Shouldn't the first field be `length`? Per [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)

![padstart](https://user-images.githubusercontent.com/343940/39026219-d69980e0-4419-11e8-9f1d-c95a9324612e.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23555
