### ISSUE TITLE
Case-sensitivity and file system providers

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#48258]
Today we seems to have hardcoded logic to know when paths should be compared case-sensitive or not, e.g. callers of [`isEqualOrParent`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/resources.ts#L15) or [`isEqual`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/resources.ts#L27) and likely many more...

With https://github.com/Microsoft/vscode/commit/b0ede6c91bd6786c8589f062310a2dec9222fa48 I have added a file system provider flag/capability to signal that it is case-sensitive (default is case-insensitive). We need to come up with a strategy to communicate that information to consumers, e.g. the explorer or file events so that we do the correct thing. 

A sample of failure is part of the memos-sample which creates to files that only differ in casing: https://github.com/Microsoft/vscode-extension-samples/blob/58ea8617190ee5566e001b9875b8b2c25a983857/fsprovider-sample/src/extension.ts#L30

**Comment by bpasero** [comment]
I guess we would need some service that can compare resources which has all the knowledge of the capabilities of the file system. Possible inputs to this service are the capabilities of the remote file system, and then for `file://`, the OS and possibly smarter things like having a real understanding of the file system. As a first step we could have a stupid logic in the service for `file://` where we simply assume Linux is case-sensitive and the others are not.

**Comment by isidorn** [comment]
Introducing such a service makes sense but could it also be a part of the `FileService`?
I could look into adding this once we decide where this should belong. And I like the idea of starting with stupid logic which respects what we currently have.

**Comment by jrieken** [comment]
> Introducing such a service makes sense but could it also be a part of the FileService?

Plus one for adding this the FileService, it is somewhat similar to [`canHandleResource`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L52)

**Comment by bpasero** [comment]
We can start adding it there. The challenge will be to get access to this service from all places where we need to compare `URIs`. Also, I guess comparing 2 resources with different schemes should not be supported at all.

**Comment by isidorn** [comment]
Assigning to May so we investigate next milestone.

**Comment by jrieken** [comment]
> Also, I guess comparing 2 resources with different schemes should not be supported at all.

Well, not supported as they are inequal by definition. So, compare `scheme`, then `authority` (both always case-insensitive according to my knowledge), and then compare path (case-sensitive or not) and optionally compare query and ignore fragment.

**Comment by isidorn** [comment]
We were focused on grid this milestone, next week I am on vacation, this is not for endgame -> June

**Comment by isidorn** [comment]
I plan to start investigating into this tomorrow by:
* updating the `IFileService` to have `areEqual(first: uri, second: uri): boolean`
* Implementing this in our `FileService` to simply respect the current platform
* adopt all the path comparisons to use the `IFileService` for comparison - it might happen that some clients of this will not have an instance of the `IFileService` as @bpasero pointer out - but we see

**Comment by jrieken** [comment]
Maybe a more portable `Comparator` would help, e.g. `fileService.getUriComparator(): (a: URI, b: URI) => number`. Once acquired we can pass the comparator around and use it in other places

**Comment by isidorn** [comment]
Did not have time this milestone -> July

**Comment by isidorn** [comment]
Does not seem like this will happen in the last couple days of the milestone -> september

**Comment by isidorn** [comment]
I have pushed the changes in the Explorer such that the Explorer will now respect the FileSystemProvider case sensitive capability. Explorer also reacts on the change of this capability.
I now that this does not solve all the issues, but should in theory help with many issues as @aeschli suggested.
So let's try it out with insiders from tomomrrow and for now closing this issue.
