### ISSUE TITLE
Allow provideCompletionItems to return IterableIterator and AsyncIterableIterator

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#48255]
Hey, I think [`provideCompletionItems`'](https://code.visualstudio.com/docs/extensionAPI/vscode-api#CompletionItemProvider.provideCompletionItems) return value should extend to include `IterableIterator` and `AsyncIterableIterator`.

That way in case the completions take a while to generate (like when workspace files are being consulted for suggestions, the items can start popping in ASAP as opposed to taking a while to all get dumped in at once.

An alternative extension developers can use today is to keep a workspace index and cache the intermediate data used to fuel the suggestion list, so this is not strictly necessary, but I think it would simplify extension development a little bit without too much impact. (Albeit I am incapable of assessing how much impact would it have for the core to actually support it.)

Maybe there are other API candidates which could benefit from this, too.

**Comment by jrieken** [comment]
The "streaming results"-discussion isn't new (we have discussed this for reference search for instance) but the unsolved challenge is in the UI. Showing results and updating them at the same time isn't a nice user-experience. There are two options and both aren't good:

* new results are always added to end of the suggestions list which means potentially good results are never prominently shown
* new results are intermixed with existing results which means confusion, esp when this happens at the exact moment in which you select an item

**Comment by TomasHubelbauer** [comment]
Yeah. I guess this is a pretty well known UX challenge, I personally have found a way which works for me in my projects and have received zero complaints about: append it suggestion list is hovered over, order if it isn't (keyboard selection is fine, it will just move, no biggie). Of course one missing component to this is touch, which I don't think is a problem for VS Code really, but my solution to that is just to fall-back to append-only on touch devices and potentially reorder only between touch down and up events in different places (knowing touch isn't and won't be occurring in the suggestion list during that time). Still, one problem is left, which is multi-touch, someone can still tap the suggestion list with their other finger while tapping something with their first finger, but that was always an edge-enough case for me to not have to worry about.
