### ISSUE TITLE
Integrate import suggestion logic into core for TS

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#48250]
https://marketplace.visualstudio.com/items?itemName=steoates.autoimport

This is such a critical plugin for ANY TS/TSX enabled workspace. I think it makes sense to integrate this as a piece of core functionality.

**Comment by mjbvz** [comment]
This is already integrated: https://code.visualstudio.com/docs/languages/typescript#_auto-imports

If you don't see it working in some cases, please open an issue with some example code
