### ISSUE TITLE
Autosuggest of 'this' not working on anonymous function

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#48251]
I've included the extra promise/async syntax to reproduce the exact scenario I have. Probably doesn't work in simpler scenarios.

```
class foo {

   constructor(private bar){}

    async test() {
        return await new Promise(async (resolve, reject) => {
           var a = (await bar.someAsyncMethod()).someResult;
        });
    }
}
```

Autosuggest does not suggest that bar use this.bar... it just says cannot find name 'bar'

**Comment by jpike88** [comment]
@mjbvz probably worth showing you this one too

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/23580 to track this upstream
