### ISSUE TITLE
Feature request in Zen Mode!

### ISSUE THREAD

**Issue by Yash-Pal** [Microsoft/vscode#48256]
- VSCode Version: 1.22.2
- OS Version: Windows 10 Pro

Feature Request:

1. Most of the time I work in **Zen Mode**. But I am missing the opened files tabs in top screen. I can use **Show opened Editors** or other functions/commands to show the opened files but it is a little awkward for me. If you could make the **Opened Editors** visible on **Zen Mode** like this (http://prntscr.com/j7p2mu) I will be glad to have such a amazing editor in my PC.

**Comment by isidorn** [comment]
Please use the following settings
`"zenMode.hideTabs": false`
