### ISSUE TITLE
Find in file 

### ISSUE THREAD

**Issue by etienne-cochard** [Microsoft/vscode#48257]
Issue Type: <b>Bug</b>

Find in files only search in opened files & in c:\\<username>\\appdata\roaming\code\user

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-7700K Radeon R7, 10 Compute Cores 4C+6G (4 x 3394)|
|Memory (System)|15.92GB (9.92GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.2
project-manager|ale|0.25.0
vscode-eslint|dba|1.4.8
vscode-instant-markdown|dba|1.4.1
php-debug|fel|1.12.3
beautify|Hoo|1.3.0
JSDocTagComplete|Hoo|0.0.2
easy-less|mrc|1.4.5
python|ms-|2018.3.1
cpptools|ms-|0.16.1
debugger-for-chrome|msj|4.3.0
ejs-language-support|Qas|0.0.1
vscode-hexdump|sle|1.6.0
debug|web|0.22.0

(3 theme extensions excluded)

</details>

**Comment by etienne-cochard** [comment]
vs code insider is ok on the same machine.

**Comment by roblourens** [comment]
Make sure you don't have settings (search.exclude or files.exclude) or a gitignore file which are affecting your search. If it works find in Insiders though, I will close this...
