### ISSUE TITLE
Download update/ installing update should show progressbar.

### ISSUE THREAD

**Issue by sanket-bhalerao** [Microsoft/vscode#48254]
Issue Type: <b>Feature Request</b>

click on check for update

VS Code version: Code - Insiders 1.23.0-insider (1fdf60b882f0edc6753fc964b253783eb46d56ef, 2018-04-19T13:37:07.476Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (3.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
jshint|dba|0.10.18
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.2
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
python|ms-|2018.3.1
PowerShell|ms-|1.6.0
typescript-javascript-grammar|ms-|0.0.39
vscode-react-native|vsm|0.6.8

</details>

**Comment by joaomoreno** [comment]
We won't show a progress bar, since most users don't really care. They just want to be notified when the update is ready.
