### ISSUE TITLE
tslint single quotes not respected by autocomplete adding "imports" in .tsx

### ISSUE THREAD

**Issue by mduu** [Microsoft/vscode#48253]
We have written the needed data into your cl
Issue Type: <b>Bug</b>

Our projects (React + TypeScript) have tslint.json configuration set to single-quote:

```
{
    "rules": {
      "quotemark": [
        true,
        "single"
      ],
...
```

If VSCode's autocomplete adds the first "import" statement (using Ctrl+.) it always uses double quotes - no matter that's in tslint.json and therefore builds invalid code what one needs to fix first.

On the other hand: if there are already "import" statement with single-quote the autocomplete will add additional "import" statement with correct single-quote.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|Memory (System)|15.69GB (6.91GB free)|
|Process Argv|...|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
markdown-preview-github-styles|bie|0.1.2
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.14.1
jshint|dba|0.10.18
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
xml|Dot|1.9.2
gitlens|eam|8.2.2
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.31
json-tools|eri|1.0.2
git-project-manager|fel|1.5.1
auto-run-command|gab|1.5.0
beautify|Hoo|1.3.0
vscode-react-typescript|inf|1.0.13
diff-tool|jin|0.0.1
guid|kos|0.0.1
camelcasenavigation|map|0.3.42
json-to-ts|Mar|1.5.4
vscode-less|mrm|0.6.3
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.3.0
autotrim|Nat|1.0.6
material-icon-theme|PKi|3.3.0
typescript-hero|rbb|2.3.2
partial-diff|ryu|1.0.0
code-spell-checker|str|1.6.7
move-ts|str|1.11.3
react-beautify|tai|0.3.0
wallaby-vscode|Wal|1.0.82
markdown-pdf|yza|0.1.8
file-size|zh9|0.1.2

(3 theme extensions excluded)

</details>

**Comment by mduu** [comment]
Just recognize this is maybe an issue of the extension "TypeScript Hero". Not sure yet.

**Comment by mjbvz** [comment]
We don't use tslint rules for the built-in js/ts formatter. 

Being able to configure the quote style is tracked by https://github.com/Microsoft/TypeScript/issues/22342. We'll pick up support for it in May
