### ISSUE TITLE
代码支持太少了

### ISSUE THREAD

**Issue by luofengchen** [Microsoft/vscode#48265]
Issue Type: <b>Feature Request</b>

代码支持太少，做微信或者支付宝小程序的 功能进度没有那么快

VS Code version: Code - Insiders 1.23.0-insider (dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b, 2018-04-16T05:17:45.591Z)
OS version: Windows_NT x64 6.1.7601

**Comment by ramya-rao-a** [comment]
According to Google Translate,
The title translates to: `Too little code support`
The description translates to: `The code support is too small, and the progress of doing WeChat or Alipay applets is not as fast`

What does WeChat or Alipay have to do with Visual Studio Code?
What kind of code support are you referring to?

**Comment by oDoraemon** [comment]
我所知道的, 微信或者支付宝小程序,前端是基于 javascript的一些集成, 会有自己的方法调用规则. 它们本身还在进化中,  后面很多方法接口都会有变更. 编辑器平台是不会针对小程序做适配的, 要做适配也只是插件级别, 与编辑器无关. 
小程序的后端, 不管你用的是node.js/python/php还是java, VS Code的支持都是足够的.
另外, 这个ISSUE我理解的更多的是抱怨, 而不是功能需求. 建议你能描述更具体的需求, 比如 '我希望vscode能增加对小程序的语法支持.'  光抱怨马跑的不够快, 别人只会建议你换一匹马. 
VS Code不是国人开发的软件. 如果是英文表达有困难, 你可以多在微信或支付宝开发平台寻求建议, 看看别人是如何做的. 如果论坛里的人不能帮你, 你可以再过来提问.
=== human translation ===
As I know, WeChat or Alipay Little App's front-end is a variant derived from javascript. They do a lot of encapsulation on js and have their's own syntax and ways to make function call. They are evolving themself and would be unstable in a long time. Generic editor won't support Little App rules and syntax for a minor variant. It's not the editor's issue, it's an extension level demand.
VS Code is power enough for your post-end dev, no matter what language u choose to launch your Little App,  node.js/python/php or java.

Besides, I take this issue more than a complaint nor a feature demand. I recommand to descripe a more specific demand. Like 'I hope u to add Little App syntax support'. Complaint about the horse not fast engouh , people would suggest to find a faster one. 
VS Code is not developed  by Chinese. If u have problem with expressing yourself in English,  u can look for suggestion on WeChat or Alipay dev-platform first, see what the other guys dealing with the issue. If it still bother u then, u can list your issues here.
