### ISSUE TITLE
Suggesting; make "files.exclude" to have ${workspaceFolder:<foldername>} prefix for multi-root workspace

### ISSUE THREAD

**Issue by lostfields** [Microsoft/vscode#48262]
- VSCode Version: 1.22

I would love to have more flexibility in "files.exlude" for multi-root workspace. I've tried relative paths but that doesn't work since "files.exclude" is applied to each folder. If I'm hiding folder "build" I don't want to hide it from all folders.

I know I can have .vscode/settings.json but I don't want to check these files into my source control

```
"folders": [
		{
			"name": "root",
			"path": "."
		},
		{
			"name": "website",
			"path": "./app"
		},
		{
			"name": "api",
			"path": "./src"
		}
	],
	"settings": {
		"files.exclude": {
			"**/.git": true,
			"**/.vscode": true,
			"${workspaceFolder:root}/build": true
		}
	}
}
```
Hides `build` in folder `root` but still showing it in folder `website`

**Comment by roblourens** [comment]
I wonder whether we want to be able to set settings in general for a particular folder in a workspace file, without adding it to that folders' settings.json. @sandy081? Of course that would just make settings editing more complicated.

Otherwise I'm not opposed to this.

**Comment by sandy081** [comment]
I do not think it is related to folder/workspace settings. In this scenario, it is up to the setting `files.exclude` to decide if they want to support variables or not. This is pretty similar to how MR workspace debug configurations support root variables. So, I would leave this to owner of that particular setting.

@bpasero @isidorn FYI

**Comment by sandy081** [comment]
Not exactly, because how does the configuration knows what to resolve. In this case it is a key that has to be resolved.

**Comment by roblourens** [comment]
@sandy081 What I'm getting at is, we could solve it without variables by having a way to set files.exclude in a normal way, just scoped to one folder. That would work in general for all settings. I don't know whether that's been discussed before. But I'm lukewarm on adding a 4th settings scope.

**Comment by lostfields** [comment]
I'm not aware of everything or how thing should work, but I'll try to throw something in.

What if all paths in `files.exclude` can be both relative and absolute? Absolute paths were applied to all folders (`/build`), and relative paths were applied to folders that matches the relative location of workspace file (`./build`)?

I was thinking this since `folders[].path` can be both relative and absolute when referering workspace folders

**Comment by sandy081** [comment]
@roblourens 

`we could solve it without variables by having a way to set files.exclude in a normal way, just scoped to one folder` 

Do you mean folder settings in MR workspace or support settings in every folder? 

IMO this makes sense supporting by `files.exclude` setting as it is very specific to it.

**Comment by roblourens** [comment]
> Do you mean folder settings in MR workspace

Yeah, specifying folder settings in the workspace file.

> IMO this makes sense supporting by files.exclude setting as it is very specific to it.

Maybe - this one case just involves files.exclude but I can imagine someone having the same request for other settings. If this ability is useful, I don't know why it would only be useful for files.exclude and no other setting.

**Comment by lostfields** [comment]
One thing I may want to mention, I have problems with https://marketplace.visualstudio.com/items?itemName=maty.vscode-mocha-sidebar when defining the path (mocha.files.glob) of test-files in a workspace. The path is relative to the first folder in "folders" so I can't rearrange the folders in the workspace-file.

**Comment by cloph** [comment]
requiring a separate settings.json in one of the folders is a workaround at best, but not a real solution.

**Comment by dfoverdx** [comment]
> requiring a separate settings.json in one of the folders is a workaround at best, but not a real solution.

I don't disagree, but I do believe it's the dev team's intended solution.
