### ISSUE TITLE
Sort 'Add import to existing' before 'Import additional module' code actions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#48264]
Issue Type: <b>Feature Request</b>

Having the 'Add' entry before the 'Import' entries would make sense because the user is more likely to reference something from an existing import:

![image](https://user-images.githubusercontent.com/9205389/39045661-bee838a4-4493-11e8-925c-c47443b3b6ea.png)

VS Code version: Code - Insiders 1.23.0-insider (1fdf60b882f0edc6753fc964b253783eb46d56ef, 2018-04-19T13:30:25.297Z)
OS version: Darwin x64 16.7.0

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23579
