### ISSUE TITLE
Typescript: remove unused import (fix all) removes copyright header

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48267]
From here

![image](https://user-images.githubusercontent.com/22350/39048380-8a8a20ae-449d-11e8-9cba-f6695d50a400.png)

to here

![image](https://user-images.githubusercontent.com/22350/39048390-907ca2ca-449d-11e8-95aa-9d2e0cd7b57c.png)

**Comment by mjbvz** [comment]
@joaomoreno Do you have reliable repo steps for this? I tried removing a bunch of code in various vscode src files and then running organize imports but was unable to reproduce the problem

Also, please make sure that typescript 2.8.3 is active in your workspace

**Comment by joaomoreno** [comment]
Steps:

1. Open `webview.contribution.ts`.
2. Delete everything but the first non-import statement (lines 30-90)
3. Run the `Remove import (Fix all in file)` quick fix.

**Comment by mjbvz** [comment]
Thanks, confirmed this issue still exists in 2.8.3. Will open an upstream typescript issue

**Comment by mjbvz** [comment]
Looks like it is already tracked by https://github.com/Microsoft/TypeScript/issues/20902
