### ISSUE TITLE
How to escape the pipe character in Markdown?

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#4826]
- VSCode Version: 0.10.11
- OS Version:Win 10

After doing some searching, I was unable to find how to escape the pipe character - if I include it in my table, it throws off all my formatting.

**Comment by SamVerschueren** [comment]
How is this even related to VS Code? This is just simple markdown editing... Google -> https://github.com/gitlabhq/gitlabhq/issues/1238#issuecomment-10022918

**Comment by rhires** [comment]
I saw the thread you posted, and it did not solve the issue. It's related to VS Code b/c vscode purports to support Markdown, and when it fails using this editor in this way, it's worth reporting.

**Comment by Tyriar** [comment]
Yes please let us know anyway you feel we can improve the product :)

This is what I see in 0.10.12 (not yet released):

![image](https://cloud.githubusercontent.com/assets/2193314/14191249/bc09ccde-f74b-11e5-931d-faa7c44ae6ea.png)

Seems fine, now at least.
