### ISSUE TITLE
Unstaging ranges leaves out whitespace changes

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#48268]
- VSCode Version: 1.22.2
- OS Version: Windows 10

Steps to Reproduce:

1. Make a bunch of changes to a file, along with only whitespace changes to some lines
2. Stage the whole file
3. Select a range in the staged file which has whitespace changes, and "Unstage Selected Ranges".
4. The whitespace changes are kept in the index, but the rest of the range is unstaged, causing weird mix of old and new.

This issue is fixed if the **Ignore Trim Whitespace** setting is **ON** when I'm doing hunk-based staging/unstaging, although it's not very obvious at the beginning why this is happening.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

![image](https://user-images.githubusercontent.com/760112/39048913-d753662e-44bc-11e8-80ed-f41d3fe77682.png)

unstaging with ignore trim whitespace disabled:

![image](https://user-images.githubusercontent.com/760112/39048951-fbaf8d9a-44bc-11e8-83fc-524692b360ce.png)

**Comment by evgenyKozlov1996** [comment]
I'd like to try to fix this issue.

**Comment by dylmye** [comment]
Is this still an issue? Can't repro either in 1.28.2.

**Comment by kumarharsh** [comment]
Yeah, I think has been fixed. Should i close?
