### ISSUE TITLE
Suggest the user to set up a proxy when ECONNREFUSED occurrs

### ISSUE THREAD

**Issue by grairdon88** [Microsoft/vscode#4827]
- VSCode Version: 0.10.11
- OS Version: Windows 8.1 Pro

Steps to Reproduce:

1. Open Visual Studio Code
2. Open Command Palette
3. Type ext install PowerShell (really, any extension).
4. Error happens: Error: connect ECONNREFUSED

**Comment by joaomoreno** [comment]
Make sure you configure your [proxy explicitly](https://code.visualstudio.com/docs/supporting/faq#_proxy-server-support).

**Comment by grairdon88** [comment]
Thanks! Did not know that, sorry!

**Comment by pavelthebest** [comment]
The same problem here.
- VSCode Version: latest, downloaded on 04.04.2016, shown as:
Version 0.10.1
Commit df352367df2efcfa9d602d471e4e2f42140a0f05
Date 2015-11-17T15:21:23.766Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1
- OS Version: Linux 64bit
- Settings:
	"http.proxy": "http://proxy........:81",
	"https.proxy": "http://proxy.........:81",
	"http.proxyStrictSSL": false,

Steps to Reproduce:

    Open Visual Studio Code
    Open Command Palette
    Type ext install mason (really, any extension).
    Error happens: Error: connect ECONNREFUSED

**Comment by joaomoreno** [comment]
I will implement a message to indicate that you should consider set up a proxy, whenever this happens.

**Comment by pavelthebest** [comment]
Is the current Linux version 1.10.1 (built on 2015-11-17) and the current windows version 1.10.11? Should it work in Linux version at all?
When I grep for strictSSL in VSCode directory I find nothing.

**Comment by joaomoreno** [comment]
@pavelthebest What are your settings exactly?

**Comment by pavelthebest** [comment]
AS s you can see in my post before:

`	"http.proxy": "http://proxy.....:81",
	"https.proxy": "http://proxy.....:81",
	"http.proxyStrictSSL": false,
`
I have replaced a part of our proxy by '....'.

**Comment by pavelthebest** [comment]
Sorry, it was my fault, for some reason I have downloaded wrong version, 1.10.1 instead of 1.10.11. I take everything back. Sorry.

**Comment by joaomoreno** [comment]
No problem! Thanks for taking the time to try to fix it, nevertheless. :+1:

**Comment by ravimittal16** [comment]
I am getting the same error at my work environment
