### ISSUE TITLE
[loc][Query] Context needed for "contribution point"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48277]
For string below community members are asking about more context? Can you please help? Thanks!

**Original comments**
BG ISSUE - This is unclear. And what do the 'contribution point' and 'conributed' mean here?
by lyubomirv, 6 hours ago
ES - @johosek , can you help me to understand on what means "contribution point" in the file source in https://github.com/Microsoft/vscode/raw/master/src/vs/workbench/api/browser/viewsContainersExtensionPoint.ts line: 44
Thanks.
by AleksSyntek, 11 hours ago

**Context**
src/vs/workbench/api/browser/viewsContainersExtensionPoint:English (en):plaintext:vscode.extension.contributes.views.containers.id

**Resource**
vs_workbench

**String Hash**
bb64f8d530c8baeb8d85950114a52101

**String text**
Unique id used to identify the container in which views can be contributed using 'views' contribution point

**Comment by josefhosek** [comment]
Same concern about "contribution" applies to next string from the same file.

**String** - '{0}' contribution is only available when running out of dev or with the following command line switch: --enable-proposed-api {1}
**Comment** - What is 'contribution' here? by lyubomirv, 6 hours ago

**Comment by sandy081** [comment]
Contribution refers to those that an extension contributes to VS Code.

**Comment by lyubomirv** [comment]
@sandy081 I'm sorry but it's not clear. I still do not understand what is a 'contribution POINT'?

And for the other concern - '{0}' contribution. What does this mean? What could {0} be replaced with?

**Comment by sandy081** [comment]
@lyubomirv Contribution point is an extension point in `package.json` to which extensions contribute to. For eg:

```
"contributes": {
	"viewsContainers": {
		"activitybar": [
                        {
			    "id": "azure",
			    "title": "Azure",
			     "icon": "resources/azure.png"
		        }
                  ]
	},
        "views": {
		"azure": [
			{
				"id": "cosmosdb",
				"name": "Azure Cosmos DB"
			},
                         {
				"id": "docker",
				"name": "Docker"
			}
		]
	}
}
```

In the above example `viewsContainers` and `views` are contribution points.

I just updated the message to replace {0} directly with `viewsContainers` because it should not be translated.

**Comment by AleksSyntek** [comment]
Thanks @sandy081 for the explanation on that. I will recheck the translation item.

**Comment by lyubomirv** [comment]
@sandy081 Thank you!
