### ISSUE TITLE
IDE Hang

### ISSUE THREAD

**Issue by ktri-camelot** [microsoft/vscode#48273]
Issue Type: <b>Bug</b>

Hi Team,

While editing the source code, multiple times the IDE gets hang and get recover after few seconds. This is annoying at time of development. Kindly resolve.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.86GB (9.41GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
xml|Dot|1.9.2
vs-code-xml-format|fab|0.1.5
Go|luk|0.6.78

</details>

**Comment by aeschli** [comment]
Do you still see this?
If yes, can your run `code --status` while that happens, to find out more what's going on?

**Comment by aeschli** [comment]
closing as more information is needed

**Comment by ktri-camelot** [comment]
Ok, Thanks. Maybe it was the version-specific issue. After updates, I have not come across this issue.
