### ISSUE TITLE
[loc][Query] Possible typo in "The locations of the font."

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48278]
For string below community member is asking if source text should really contain "locations" and not singular "location"? Can you please confirm? Thanks!

**Original comments**
BG ISSUE - Is "locations" really meant to be plural, or is this a typo?
by lyubomirv, 3 months ago

**Context**
src/vs/workbench/services/themes/common/fileIconThemeSchema:English (en):plaintext:schema.src

**Resource**
vs_workbench_services_themes

**String Hash**
e5f28b628db8ed6138841964e6fe4bac

**String text**
The locations of the font.

**Comment by aeschli** [comment]
Yes, you are right, should be singular `location`

**Comment by dbaeumer** [comment]
Verified in code.
