### ISSUE TITLE
More smart code folding

### ISSUE THREAD

**Issue by VBagmut** [Microsoft/vscode#48276]
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

I fold all sections with shortcut "CTRL+K CTRL+0", but then I want to unfold all levels in only selected code. When I select code and press "CTR+K CTRL+J" all code is unfolding, that I don't need. And when I press "CTRL+SHIFT+]" code unfolds only one level of nesting, but I need to unfold all levels of nesting in only selected code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
To unfold only certain ranges you can set the cursor at the range to unfold and use `Unfold recursively Ctrl+K Ctrl+]`
You can even unfold multiple ranges by setting multiple cursors.

Please reopen if this does not solve your problem.

**Comment by VBagmut** [comment]
@aeschli Thank you, it's helped. It'll be good if you add this shortcut in Code Folding section in the Interactive Playground.

**Comment by aeschli** [comment]
I clarified the description in the playground.
