### ISSUE TITLE
[loc][Query] Context for placeholder needed

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48281]
For string below community members are asking about the placeholder, as they need to know with what it will be replaced with? Can you please confirm? Thanks!

**Original comments**
BG - @Transifex_CNE_ITA @agriffard I would say this is an event type, by looking at the code here: https://github.com/Microsoft/vscode/blob/7d34e22d3fb7f9a4dc4f80ac6b6a0e8a73bac138/src/vs/workbench/parts/extensions/electron-browser/runtimeExtensionsEditor.ts#L319
But maybe someone from the VS Code team should give more details.
by lyubomirv, 3 months ago
IT ISSUE - Does the placeholder refer to a date?
by Transifex_CNE_ITA, 4 months ago
FR - Is it about the date on which it has been activiated?
by agriffard, 4 months ago

**Context**
src/vs/workbench/parts/extensions/electron-browser/runtimeExtensionsEditor:English (en):plaintext:workspaceGenericActivation

**Resource**
vs_workbench_parts_extensions

**String Hash**
e5b4ea304f776a978acb882713c63758

**String text**
Activated on {0}

**Comment by alexandrudima** [comment]
I've added the following comment:

```
	title = nls.localize({
		key: 'workspaceGenericActivation',
		comment: [
			'The {0} placeholder will be an activation event, like e.g. \'language:typescript\', \'debug\', etc.'
		]
	}, "Activated on {0}", activationTimes.activationEvent);

```
