### ISSUE TITLE
[loc][Query] Context needed for placeholders

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48284]
For string below community member is asking about context for placeholders? Can you please help? Thanks!

**Original comments**
BG ISSUE - I think {0} is either Log Point or Breakpoint (is it?), but what is {1}?
by lyubomirv, 7 hours ago

**Context**
src/vs/workbench/parts/debug/electron-browser/debugEditorContribution:English (en):plaintext:breakpointHasCondition

**Resource**
vs_workbench_parts_debug

**String Hash**
8a082bd6cf474d84b79f63930a837ce8

**String text**
This {0} has a valuable {1} that will get lost on remove. Consider disabling the {0} instead.

**Comment by isidorn** [comment]
{0} is either "Log Point" or "Breakpoint".
{1} is either "message" or "condition"
