### ISSUE TITLE
Increase the size of the search/replace history buffer

### ISSUE THREAD

**Issue by costincaraivan** [Microsoft/vscode#48282]
Steps to Reproduce:

1. Search/Replace 20 things.
2. Alt-Up about 20 times.

Expected results:

1. You find the first search string.

Actual result:

1. After about 10 Alt-Ups, no more search strings, you can only reach the 11th search string.

Is it possible to make the buffer configurable and provide a user setting for it? Or at least to increase it to a huge amount? I just lost a long regexp... 😞 

To explain the workflow, I'm used to using Vim's :search/:s command many times. Sometimes I'm pre/post processing some documents or data files. I could make macros or write scripts but in many situations the time investment is not worth it so I just search/replace and then repeat the commands on several of these documents or data files.

On a related note, I could make another ticket, could you make a dropdown with past searches? To see what I mean, fire up Notepad++'s Find dialog.

**Comment by roblourens** [comment]
@sandy081 What's the limitation, just the space storing the history? I would just change it to 100 + a command to clear the history.

I have https://github.com/Microsoft/vscode/issues/23099 for UX

**Comment by sandy081** [comment]
Feel free to increase it.

**Comment by roblourens** [comment]
Increased from 10 to 100 and added the "Clear search history" command.

**Comment by sandy081** [comment]
@roblourens This only works in Search and not in other places like editor find?

**Comment by roblourens** [comment]
@rebornix should we do the same for the find widget? And I wasn't sure about clearing it - would that operate on the open file, the whole workspace, and using the same command or a new one, etc...

**Comment by costincaraivan** [comment]
@roblourens I'm far from an expert, but I guess the user expectation is that it runs on the previous selection?
