### ISSUE TITLE
[loc][Query] Typo in source text for "Activated because file {0} exists in your workspace"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48280]
For string below community member reported possible typo in source? Can you please check? Thanks!

**Original comments**
FR ISSUE - 'file {0}' should be 'a {0} file'?
by agriffard, 5 months ago

**Context**
src/vs/workbench/parts/extensions/electron-browser/runtimeExtensionsEditor:English (en):plaintext:workspaceContainsFileActivation

**Resource**
vs_workbench_parts_extensions

**String Hash**
602ab75a907953691af9591637ec0f3e

**String text**
Activated because file {0} exists in your workspace

**Comment by alexandrudima** [comment]
I have pushed a change to clarify the meaning of `{0}` in the two strings:

```
title = nls.localize({
	key: 'workspaceContainsGlobActivation',
	comment: [
		'{0} will be a glob pattern'
	]
}, "Activated because a file matching {0} exists in your workspace", fileNameOrGlob);

title = nls.localize({
	key: 'workspaceContainsFileActivation',
	comment: [
		'{0} will be a file name'
	]
}, "Activated because file {0} exists in your workspace", fileNameOrGlob);

```
