### ISSUE TITLE
Ctrl + F2 Not Selecting All Occurances

### ISSUE THREAD

**Issue by stekelh** [Microsoft/vscode#48283]
Issue Type: <b>Bug</b>

I finding that when I press Ctrl + F2 it does not "select all occurances" but  instead it will bring up the menu as if you had right clicked somewhere. 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|Memory (System)|15.93GB (9.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.2
Bookmarks|ale|0.18.2
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.37
vscode-eslint|dba|1.4.8
vscode-faker|dee|1.3.0
xml|Dot|1.9.2
gitlens|eam|8.2.2
vscode-html-css|ecm|0.2.0
vscode-nupkg|eri|0.0.8
vscode-reveal|evi|2.0.3
git-project-manager|fel|1.5.1
vscode-solution-explorer|fer|0.2.11
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
vscode-pigments|jas|0.0.5
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.0.18
vs-color-picker|lih|0.7.0
rainbow-csv|mec|0.2.1
vscode-clang|mit|0.2.2
mssql|ms-|1.3.1
python|ms-|2018.3.1
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
team|ms-|1.133.0
debugger-for-chrome|msj|4.3.0
Csharp-ASPNETCore|rah|1.0.5
LiveServer|rit|3.2.1
vscode-icons|rob|7.22.0
nunjucks|ron|0.2.3
aspnet-helper|sch|0.6.4
open-in-browser|tec|1.1.0
JavaScriptSnippets|xab|1.6.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by iepoch** [comment]
@rebornix since it wasn’t answered 5 months ago. Yea I am good forgot to close this out. It been fixed since the latest updates. Thanks for asking.

**Comment by rebornix** [comment]
@iepoch sorry for not responding in time and thanks again for your feedback!
