### ISSUE TITLE
[DebugAdapter] Return Object instead of plain string in evaluateRequest

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#4829]
- VSCode Version: 0.10.11
- OS Version: Mac OS

When we implement our own debug adapter, we need to override `evaluateRequest` functionality. For now the return result is simply a string per definition

```
/** Response to "evaluate" request. */
    interface EvaluateResponse extends Response {
        body: {
            /** The result of the evaluate. */
            result: string;
            /** If variablesReference is > 0, the evaluate result is structured and its children can be retrieved by passing variablesReference to the VariablesRequest */
            variablesReference: number;
        };
    }
```

However if we inspect objects when we debug TypeScript project, we can get a TRUE object 

![image](https://cloud.githubusercontent.com/assets/876920/14177672/fd2bf870-f789-11e5-8a12-973eb761eade.png)

Maybe I miss something, is this possible for custom debug adapters?

Moreover, as it's plain string and it can't produce multiline output as OutputEvent does, we fail to do the right evaluation for ruby `inspect` override (see https://github.com/rebornix/vscode-ruby/issues/14). Let's say we have such a Class called Person and its `inspect` is override as `"hello \n #{@name}"`, you will get following results in `irb`

```
> person = Person.new("Peng")
 => hello
 Peng
> person
 => hello
 Peng
> person.inspect
 => "hello \n Peng"
```

In current `EvaluateResponse`, the result is always `"hello \n Peng"`. I don't see any workaround for this.

**Comment by isidorn** [comment]
Yes this functionality is avialble to all debug adapters. Go, powershell and others use it.
The `variablesReference` from the response is the key here, if that is greater than zero vscode will treat it as a complex object. Once the user tries to expand the object VSCode will try to get all the children of that variable using the reference. 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L429

**Comment by rebornix** [comment]
@isidorn thanks for pointing out the usage of variableReference. 

Just one more question, is multiline output possible? We've raised the same question in https://github.com/Microsoft/vscode/issues/255 .

**Comment by isidorn** [comment]
@rebornix multiline output should be possible using the [output event](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L119). If each line ends with a `\n` we will nicely split them on the vscode side.

If it does not work as expected feel free to create a new issue
