### ISSUE TITLE
Side markdown preview doesn't line up when headings are collapsed

### ISSUE THREAD

**Issue by tigerhawkvok** [Microsoft/vscode#48299]
Issue Type: <b>Bug</b>

1. Open a large-ish markdown file.
2. Collapse some headings
3. Scroll around

It should keep aligned, but they actually misalign.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|31.91GB (12.06GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aga|0.5.0
sqlformatter|bre|0.0.7
bracket-pair-colorizer|Coe|1.0.37
vbscript|Dar|1.0.4
vscode-markdownlint|Dav|0.14.1
empty-indent|Dmi|0.2.0
githistory|don|0.4.0
jupyter|don|1.1.4
gitlens|eam|8.2.2
vscode-html-css|ecm|0.2.0
LogFileHighlighter|emi|2.2.0
vsc-material-theme|Equ|1.6.0
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
vscode-mysql|for|0.3.0
mdmath|goe|2.2.1
gc-excelviewer|Gra|2.0.20
mysql-syntax|jak|1.3.1
cypher-query-language|jak|1.0.2
latex-workshop|Jam|5.3.0
nbpreviewer|jit|1.0.0
php-cs-fixer|jun|0.1.62
indentation-level-movement|kai|1.1.1
stata-enhanced|kyl|1.3.0
vscode-emacs-friendly|lfs|0.8.2
rainbow-csv|mec|0.2.1
code-beautifier|mic|2.0.3
vscode-apache|mrm|1.1.1
vscode-less|mrm|0.6.3
mssql|ms-|1.3.1
python|ms-|2018.3.1
cpptools|ms-|0.16.1
PowerShell|ms-|1.6.0
color-highlight|nau|2.3.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|2.9.0
stylelint|shi|0.36.0
vscode-autohotkey|sle|0.2.2
vba-snippets|spe|1.0.1
latex-support|tor|1.5.1
markdown-pdf|yza|0.1.8

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
The preview lines up with the top of the editor screen. This means that as you scroll past any collapsed section in the editor, the preview it will rapidly jump past it. Is this what you see? If not, please provide a gif or photo of the problem
