### ISSUE TITLE
TypeScript Proxy problem with 'https://schemastore.azurewebsites.net/schemas/json/package.json'

### ISSUE THREAD

**Issue by nathansantanna** [Microsoft/vscode#48298]
I'm using VS Code on my work and my proxy settings were fine, then when i tried to modify my 'tsconfig.json' from my TypeScript project i got the following error.

**{
	"resource": "/c:/Program Files/Microsoft VS Code/resources/app/extensions/typescript-basics/package.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "undefined",
	"severity": 4,
	"message": "Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': Unable to load schema from 'https://schemastore.azurewebsites.net/schemas/json/package.json': Unable to connect to https://schemastore.azurewebsites.net/schemas/json/package.json. Error: connect ETIMEDOUT 168.62.224.13:443",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}**

I saw some posts with the same problem and even a issue here, and the proposed solution most of the time was set "http.proxyStrictSSL": false, wich i didn't like it, and made no sense only 1 URL not pass on my proxy. So i started searching, and i found this [Issue ](https://github.com/SchemaStore/schemastore/issues/12)on SchemaStore site from azure. After seeing this i concluded that my proxy was getting some problem with the certificate and authentication. What i did was change all "https" to "http" in the following session of package.json file(Mine was on this path: C:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-basics\package.json). 

```
"jsonValidation": [
  {
    "fileMatch": "tsconfig.json",
    "url": "http://schemastore.azurewebsites.net/schemas/json/tsconfig.json"
  },
  {
    "fileMatch": "tsconfig.json",
    "url": "./schemas/tsconfig.schema.json"
  },
  {
    "fileMatch": "tsconfig.*.json",
    "url": "http://schemastore.azurewebsites.net/schemas/json/tsconfig.json"
  },
  {
    "fileMatch": "tsconfig.*.json",
    "url": "./schemas/tsconfig.schema.json"
  },
  {
    "fileMatch": "typings.json",
    "url": "http://schemastore.azurewebsites.net/schemas/json/typings.json"
  }
]
```
I saw that more files use this URL to get the schema, and more people that has a proxy can have this problem working behind a firewall.

- VSCode Version:1.22.2
- OS Version:Windows10 build 1607

Steps to Reproduce:

1.Try to Edit 'tsconfig.json' with i firewall without  "http.proxyStrictSSL": false

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
We switched to use https for schemas because of https://github.com/Microsoft/vscode/issues/40736.

If you don't want to use `"http.proxyStrictSSL": false` maybe you have to install a root certificate that certifies your proxy?

**Comment by aeschli** [comment]
Closing this issue as changing the particular schemas location from https to http is just a workaround.

**Comment by asrar7** [comment]
I also face almost the same problem but slightly different as follows;
Please help me as i spent a week solving it but didn't solve yet.


![image](https://user-images.githubusercontent.com/39076095/40095258-8ed749a6-58fd-11e8-8c56-145c8957e366.png)

**Comment by aeschli** [comment]
@asrar7 You problem looks like more like the location is not resolvable. If you are behind a proxy, have you configured the "http.proxy" setting

**Comment by Ahipeau** [comment]
Je suis confrontée au meme probleme : {
	"resource": "/c:/Users/Mukaram Ahipeau/Desktop/node js/livredor/package.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': Unable to load schema from 'https://schemastore.azurewebsites.net/schemas/json/package.json': Unable to connect to https://schemastore.azurewebsites.net/schemas/json/package.json. Error: getaddrinfo ENOTFOUND schemastore.azurewebsites.net schemastore.azurewebsites.net:443",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}

**Comment by aeschli** [comment]
@asrar7 You problem looks like more like the location is not resolvable. If you are behind a proxy, have you configured the "http.proxy" setting
