### ISSUE TITLE
settings.json shows when debugging

### ISSUE THREAD

**Issue by sheepy928** [Microsoft/vscode#48292]
Issue Type: <b>Bug</b>

I am coding with python. every time I press F5 and click on python, the setting.json appears. I can't debug at all even I have reinstalled the vscode and extension published by Microsoft for python or repaired python 3.6.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.85GB (2.59GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
python|tht|0.2.3
pygame-snippets|tus|0.0.1

</details>

**Comment by isidorn** [comment]
Can you reproduce this issue with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you share your launch.json and where is the location of it? Or eve better can you share your python repository for which you can always reproduce this?

**Comment by sheepy928** [comment]
actually i am working on a single .py file, it seems that there's no launch.json

**Comment by sheepy928** [comment]
Package            Version
------------------ -----------
altgraph           0.15
astroid            1.6.2
backcall           0.1.0
beautifulsoup4     4.6.0
bleach             2.1.3
bs4                0.0.1
certifi            2018.1.18
chardet            3.0.4
colorama           0.3.9
cycler             0.10.0
decorator          4.2.1
easygui            0.98.1
entrypoints        0.2.3
et-xmlfile         1.0.1
flake8             3.5.0
future             0.16.0
html5lib           1.0.1
idna               2.6
ipykernel          4.8.2
ipython            6.3.0
ipython-genutils   0.2.0
ipywidgets         7.2.0
iso8601            0.1.12
isort              4.3.4
jdcal              1.3
jedi               0.11.1
Jinja2             2.10
jsonschema         2.6.0
jupyter            1.0.0
jupyter-client     5.2.3
jupyter-console    5.2.0
jupyter-core       4.4.0
jupyterthemes      0.19.1
kiwisolver         1.0.1
lazy-object-proxy  1.3.1
lesscpy            0.13.0
lxml               4.2.1
m3u8               0.3.5
macholib           1.9
MarkupSafe         1.0
matlab             0.1
matplotlib         2.2.2
mccabe             0.6.1
mistune            0.8.3
nbconvert          5.3.1
nbformat           4.4.0
notebook           5.4.1
numpy              1.14.2
openpyxl           2.5.1
pandocfilters      1.4.2
parso              0.1.1
pefile             2017.11.5
pickleshare        0.7.4
pip                10.0.0
ply                3.11
prompt-toolkit     1.0.15
pycodestyle        2.3.1
pycryptodome       3.5.1
pyflakes           1.6.0
pygame             1.9.3
Pygments           2.2.0
pyinstall          0.1.4
PyInstaller        3.3.1
pylint             1.8.3
PyMySQL            0.8.0
pyparsing          2.2.0
pypiwin32          223
PyQt5              5.10.1
pyreadline         2.1
python-dateutil    2.7.2
python-docx        0.8.6
pytz               2018.3
pywin32            223
pywinpty           0.5.1
pyzmq              17.0.0
qtconsole          4.3.1
requests           2.18.4
Send2Trash         1.5.0
setuptools         39.0.1
simplegeneric      0.8.1
sip                4.19.8
six                1.11.0
terminado          0.8.1
testpath           0.3.1
tornado            5.0.1
traitlets          4.3.2
urllib3            1.22
wcwidth            0.1.7
webencodings       0.5.1
widgetsnbextension 3.2.0
wrapt              1.10.11
xlrd               1.1.0
xlutils            2.0.0
xlwt               1.3.0
yapf               0.21.0
ykdl               1.5.5
you-get            0.4.1040
youtube-dl         2018.3.26.1

**Comment by isidorn** [comment]
When you file this to the python extension tell them they should support debugging files without a launch.json
