### ISSUE TITLE
Open link: open folder

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#48297]
Issue Type: <b>Feature Request</b>

Following file path works as expected: 
```javascript
file:///C:/vscode/package.json
```
I want the ability to follow path to folder:
```javascript
file:///C:/vscode/
```
The behavior should be probably under a setting: (open folder in vscode | open folder in OS file explorer)

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls

**Comment by usernamehw** [comment]
@joaomoreno, does it work inside vscode?

**Comment by joaomoreno** [comment]
You mean with URL detection? Very likely not.

cc @alexandrudima

**Comment by alexandrudima** [comment]
@joaomoreno The OP talks about `file` URLs. Our URL detector does not detect `vscode` URLs. This is something that can be added, but is not implemented at this time.
