### ISSUE TITLE
On-hover button-icons for Source Control "changes" can be easily mis-clicked

### ISSUE THREAD

**Issue by Kroc** [Microsoft/vscode#48294]
Issue Type: <b>Bug</b>

The buttons that appear on the changes list (Source Control panel), are shifted to the right by other decorations; this makes it very easy to miss-click on Stage or Discard buttons.

![image](https://user-images.githubusercontent.com/142650/39063031-806d79bc-44c1-11e8-8b0a-9b005537f3a5.png)

VS Code version: Code - Insiders 1.23.0-insider (1fdf60b882f0edc6753fc964b253783eb46d56ef, 2018-04-19T13:37:07.476Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.86GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.2.16
vscode-icontheme-nomo-dark|be5|1.3.5
unique-lines|bib|1.0.0
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.14.1
EditorConfig|Edi|0.12.1
vscode-apache|mrm|1.1.1
material-icon-theme|PKi|3.3.0
gitconfig|sid|1.0.1
ignore-gitignore|stu|1.0.1
ayu|tea|0.14.0

(4 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
you mean they are shifted to the left, correct?

**Comment by Kroc** [comment]
By the change count, yes

**Comment by jrieken** [comment]
> are shifted to the right by other decorations

Do you mean shifted by the error decoration (the +9)? Iff so, know that uou can turn that off via `"problems.decorations.enabled": false`

@joaomoreno what's the bug here?

**Comment by joaomoreno** [comment]
@jrieken Good tip. I believe the bug is that the user often misclicks the actions.

**Comment by jrieken** [comment]
We should discuss this with UX folks
