### ISSUE TITLE
Windows update failure

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#48293]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1932795/vscode-inno-updater.log)

Cannot remember anything special at the time I did the auto update.

**Comment by egamma** [comment]
When I re-install I get the error that setup is already running

![image](https://user-images.githubusercontent.com/172399/39062113-5ae05e6c-447b-11e8-859d-a1c17e8726a5.png)

**Comment by joaomoreno** [comment]
@egamma Using Process Hacker, show me the full command line of the running `Code` processes.

**Comment by egamma** [comment]
will do so next time. closing the issue
