### ISSUE TITLE
File explorer sidebar reopens

### ISSUE THREAD

**Issue by str** [Microsoft/vscode#48307]
- VSCode Version: 1.22.2
- OS Version: Ubuntu Linux 17.10

Steps to Reproduce:

1. Open a file. The file is shown in the right side
2. Collapse the file explorer.
3. Click with the mouse anywhere inside the file windown
4. The file explorer sidebar reopens.

Does this issue occur when all extensions are disabled?: Yes/No

After I closed and reopened both with --disable-extensions and without it, It didn't happen again. BUT after some time of working with the IDE it happens again.

**Comment by isidorn** [comment]
This is caused by an extension.
Disable your extensions one by one and try to figure out which one is doing this pesky behavior. Once you find that out file a bug against that extension. Thanks
