### ISSUE TITLE
Go: "content on disk is newer" warnings whenever saving file to disk and formatter runs

### ISSUE THREAD

**Issue by CameronAckermanSEL** [Microsoft/vscode#48308]
Every time I save a file in VS Code, I get the "Content on disk is newer..." warning, and it forces me to open up a diff view to resolve the conflict before the changes are actually saved. 

I don't really care about the files on disk being newer than the content I want to save. I would really like a setting to disable this warning because it's immensely distracting and makes using this editor profoundly unpleasant.

- VSCode Version: 1.22.2
- OS Version: Ubuntu LTS 

Steps to Reproduce:

1. Use VS Code
2. Try to save a file (helps when there's some auto formatter in play)
3. Observe warning that VS Code did not save the file because content on disk was newer
4. Clicking compare displays diff
5. Warning says use the editor toolbar to fix problems, but I have no idea what that means.
  5.1. Now that I understand what it means, I still don't want to even have to SEE this diff in order to save the file. Please just save it when I ask.
6. CTRL+S still doesn't save the file even though I just want it to save.
7. Close the diff, VS Code nukes work because it didn't save.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@CameronAckermanSEL this error should pop up rarely and not for each file. Would like to understand how you get into this state all the time. Is there some external tool running on the file after you touch it? Does it reproduce if you run without extensions (run `code --disable-extensions` from the command line)?

**Comment by CameronAckermanSEL** [comment]
@bpasero  after staring at this all day, I think what's happening is
1. I save the file when it has a formatting error,
2. VS Saves the file
3. VS for some reason corrects the formatting error and tries to save
4. VS cries.

**Comment by bpasero** [comment]
adding @ramya-rao-a who maybe can explain how the Go formatter comes into play. It should run as a save participant and in that case would not cause any issues, but maybe it runs differently by the extension whenever a file is saved?
