### ISSUE TITLE
Missing collapse

### ISSUE THREAD

**Issue by madansr7** [Microsoft/vscode#48306]
Issue Type: <b>Bug</b>

Opened a valid JSON file with 550,000 lines in it. 
Code folding doesn't work for a file with so many lines. 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (6.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by madansr7** [comment]
@aeschli, did you get a chance to look into this one?

**Comment by aeschli** [comment]
We currently limit the number of folding ranges to 5000.
Also, big files are not sent to the language server.

**Comment by madansr7** [comment]
@aeschli , thanks for the response. I am sure the 5k limitation is for a reason and the lang server component might be important. But from a end-user point of view, if I can load the same file (sizes 20MB) in SublimeText (in less than 3 seconds) and still use code folding, it makes for a bad user experience to not be able to do the same in vscode.

**Comment by aeschli** [comment]
There's now a warning shown when the large file is opened and you can choose to enable the features anyway
