### ISSUE TITLE
Feature Request: Warn when extensions / packages required by the project are not installed

### ISSUE THREAD

**Issue by granteagon** [Microsoft/vscode#48300]
Some extensions may be required by the team (such as formatting), NPM/Nuget packages may need to be installed, etc.  Would be nice if there was a way to warn users that their machine is not correctly configure for developing the current project.

**Comment by ramya-rao-a** [comment]
You can run the `Extensions: Configure Recommended Extensions..` command to configure recommended extensions for your current workspace. This will create an `extensions.json` file that you can then check-in/commit to your repository. Then, when anybody opens this repository they will be prompted to install the recommended extensions

**Comment by granteagon** [comment]
Awesome.  Thanks!
