### ISSUE TITLE
Dim files in explorer upon clicking New Folder icon twice

### ISSUE THREAD

**Issue by yebrahim** [Microsoft/vscode#48305]
Issue Type: <b>Bug</b>

This is on Linux, didn't try to repro on other systems.
Steps: Click the New Folder or New File icons in the Explorer sidebar twice, the list of files stays dim after the input box is gone.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.9.0-5-amd64

**Comment by oDoraemon** [comment]
This should be a duplicate issue with mine. 
https://github.com/Microsoft/vscode/issues/47606

**Comment by yebrahim** [comment]
Happy to close then, thanks.
