### ISSUE TITLE
Test: editor.codeActionsOnSave

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#48303]
- [x] anyOS @sandy081 
- [x] anyOS @weinand 

Complexity: 2

Test for #42092 and #46678

## Background
The new `editor.codeActionsOnSave` setting lets you configure a set of source code actions to be run when you save file. For example, the setting:

```json
"editor.codeActionsOnSave": {
    "source.organizeImports": true
}
```

enables organize imports on save.

## Testing
**Basic**
1. In a ts project, set:

    ```json
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
    ```

1. In a ts file with un-ordered imports, save
     * Confirm that the imports are correctly organized
1. Now make the file unformatted as well and save again
     * Confirm that the imports are organized and that the file is formatted

**Disable**
1. Now set 

    ```json
    "editor.codeActionsOnSave": {
        "source.organizeImports": false
    }
    ```

1. Confirm that organize imports is no longer run

**Other settings**
1. Try other forms such as

    ```json
    "editor.codeActionsOnSave": {
        "source.organizeImports.unicorn": true
    }
    ```

    ```json
    "editor.codeActionsOnSave": {
        "source": true
    }
    ```

    ```json
    "editor.codeActionsOnSave": {
        "source.org": true
    }
    ```

2. Confirm that only examples like 2 actually enable this setting. The specific rule is: apply all code actions whose kind (`source.organizeImports`) is equal to or a subpart of the setting kind (`source` or `source.organizeImports`). 

**Language specific overrides**
1. Now try using this as a language specific setting:

    ```json
	"[typescript]": {
		"editor.codeActionsOnSave": {
			"source.organizeImports": true
		}
	}
    ```

1. Confirm that you can enable this setting for just ts and not for js
1. Confirm that the language specific setting overrides a global seting
1. Confirm that for settings such as:

     ```json
	"editor.codeActionsOnSave": {
		"source.organizeImports": true
	},
	"[typescript]": {
		"editor.codeActionsOnSave": {
			"source.unicorn": true
		}
	}
    ```

That the settings are properly merged and organize imports is run

**Timeouts**
1. With organizeImports on save enabled, open the vscode workspace
1. Try immediatly saving a ts file in `src/` before the ts server has fully loaded
1. Confirm that this operation timesout
1. Confirm that once ts is inited, that organize imports on save works again

**Comment by weinand** [comment]
@mjbvz sorry, but I have no clue what you are talking about under "Other settings" and what is the "unicorn" thing?

**Comment by sandy081** [comment]
If I understand correctly, properties are scoped. It means

`source: true` implies `source.*: true` which means `source.organizeImports: true`

**Comment by mjbvz** [comment]
Yes, sorry about the confusion. The intent of that test is that no code actions of kind `source.organizeImports.unicorn` should exist, so nothing should happen.

Let's say an extension returns three code actions with kinds:

- source.cleanup
- source.organizeImports
- source.organizeImports.foo

With `"editor.codeActionsOnSave": { "source": true}`, all three should be fired since they are all under the `source` scope.

With `"editor.codeActionsOnSave": { "source.organizeImports": true}`, only the two organize imports should would be fired.

With `"editor.codeActionsOnSave": { "source.organizeImports.foo": true}`, only the last code action should be fired

And with `"editor.codeActionsOnSave": { "source.foo": true}`, none of the code actions should be fired

**Comment by weinand** [comment]
@sandy081 @mjbvz thanks for the clarification. 

A simple sentence in the "Background" section like "properties under editor.codeActionsOnSave are similar to glob patterns" would have made things clearer.

Is this a new wildcard scheme in settings or are we using this already somewhere?
Why are you not using real glob patterns or wildcards?
I'm always a bit reluctant when adding another meta-language on top of JSON...

/cc @bpasero @jrieken
