### ISSUE TITLE
Question: Any plans to add CodeLens to JavaScript/TypeScript?

### ISSUE THREAD

**Issue by Kurtz1993** [Microsoft/vscode#4831]
Hi!

I was wondering if there are any plans to add this awesome feature to JavaScript/TypeScript language in future releases. That'll be awesome!

**Comment by egamma** [comment]
@Kurtz1993 we like the feature too, it is on the backlog.

**Comment by waderyan** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/10717
