### ISSUE TITLE
Consider opening existing file if not already active editor when creating new file with explorer with existing name

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#48319]
I have a feature suggestion concerning the Explorer page where when you try to create a file by name (or relative path), if the file (of folder) already exists, you get an error like this:

![image](https://user-images.githubusercontent.com/6831144/39082019-5a807d86-454c-11e8-8dbd-2f705e71fc8b.png)

I would like to suggest, instead of the error being shown (or maybe in addition to it being turned into an error notification), an editor is opened with the file in question or focused, it it already is open. In case a directory path is being typed and commited by pressing Enter, the relevant directory node in the Explorer pane should be expanded (and again, maybe an error notification with the existing error message should be shown). Thoughts?

Meta: are VS Code feature suggestions accepted anymore? It seems to me like the GitHub contributing template only deals with getting rid of people who want to ask questions (not considering that there are questions that are not a good fit for SO, but would be valid questions here and the fact that VS Code questions on SO have a pretty poor track record of being answered) and what's left is just a bug report template. I think clearing this up (whatever the case is) in the template would be welcome.

**Comment by isidorn** [comment]
fyi @RMacfarlane regarding feedback for issue reporter

**Comment by RMacfarlane** [comment]
@TomasHubelbauer I updated the issue template to mention feature requests
