### ISSUE TITLE
new feature can be added

### ISSUE THREAD

**Issue by shivamgupta0897** [Microsoft/vscode#48312]
VS Code can have the feature of  visual design surface known as Live View.
It will be a nice feature

**Comment by ramya-rao-a** [comment]
Can you elaborate on what feature are you requesting?

**Comment by shivamgupta0897** [comment]
I mean to say VS Code can have the the feature of live page which means while building the web page one can see what is happening in web page side by side. The person doesn't need to save the code and refresh the page on browser.

**Comment by TomasHubelbauer** [comment]
This seems like a good fit for an extension, while the majority of people use VS Code for web development, its core shouldn't capture all the possible features other web IDEs have so people who don't use it for web development (or have different workflow which wouldn't benefit from Live View in VS Code) don't have to be exposed to a bigger core (which is more likely to have bugs, especially in interactions between rarely used features).

**Comment by rbenson** [comment]
So https://marketplace.visualstudio.com/items?itemName=negokaz.live-server-preview basically or https://marketplace.visualstudio.com/items?itemName=hdg.live-html-previewer?
