### ISSUE TITLE
I think that this tools should show in activity bar

### ISSUE THREAD

**Issue by roadhub** [Microsoft/vscode#48314]
- VSCode Version: Version 1.22.2 
- OS Version: macOs

Steps to Reproduce:
![fda21287-ba4e-45b1-88fb-f1832f0ad514](https://user-images.githubusercontent.com/18000037/39081015-2b4c80bc-456c-11e8-966e-7310d24adec0.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roadhub** [comment]
The space between `setting` and  `extension` is wasted, but in fact , it is useful for same tool

**Comment by usernamehw** [comment]
Duplicate of #43645 ?

**Comment by ramya-rao-a** [comment]
Thanks @usernamehw 
@roadhub This is covered in #43645
