### ISSUE TITLE
Terminal not rendered properly after some time

### ISSUE THREAD

**Issue by NobbZ** [Microsoft/vscode#48316]
- VSCode Version:

```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

- OS Version:

```
$ uname -a
Linux arch-tuxedo 4.16.3-1-ARCH #1 SMP PREEMPT Thu Apr 19 09:17:56 UTC 2018 x86_64 GNU/Linux
$ zsh --version
zsh 5.5.1 (x86_64-unknown-linux-gnu)
$ awesome --version # The window manager I use, which might be related, see below                                                                     
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

Steps to Reproduce:

1. Open the terminal and leave it open while working.
2. After a random time (sometimes minutes, sometimes hours) the terminal will only be drawn as a unicolored pane. Switching "tags" (similar to virtual desktops in windows as I understand the windows term), seems to increase the chance of braking, but it does also happen without switching.

When we are in this state of unicolored pane, then hovering the mouse over pathes will still make me able to see the tooltip (ctrl+click -> open). Typing blindly still makes me able to run commands and even when I mousedrag a region, I can copy and paste it, so the terminal itself remains functional, but it isn't redrawn properly.

Does this issue occur when all extensions are disabled?: Yes/No

I only tried it for an hour, as working in VScode without any extensions is near to impossible, also the fact that the bug is not easily reproducable but is related to time makes it hard to actually say something more clear about this.

**Comment by Tyriar** [comment]
@NobbZ could you take a screenshot of the whole terminal panel when this happens? Also could you check if hiding and showing the terminal again, or resizing the terminal fixes the issue?

**Comment by NobbZ** [comment]
Sorry, because of an extended holiday I didn't had access to the affected system for more than a week.

![vscode-terminal](https://user-images.githubusercontent.com/58951/40405596-9147de5c-5e5d-11e8-878d-2a44f4da0bba.png)

This is how it happened this morning. Sometimes though, it just has the color that is visible in the center block. This happens often from the shown state when moving the mouse around.

I can say though, that after resizing the terminal, the problem goes away.

**Comment by NobbZ** [comment]
PS: I do think it is a bit harsh, to take over three weeks for a first reply, while demanding an answer from the OP in a week.

You should reconsider the timings.

**Comment by Tyriar** [comment]
@NobbZ needs more info will close an issue without a reply after 7 days, we can easily reopen though. This is one of the few things we're doing to keep our issue count under control and to ensure that devs can actually get some work done :smile: 

On this issue though, it looks like this is a common problem caused by Chromium that also occurs on Windows. I'll close this off as it's upstream but I imagine it will get fixed in the future by an Electron update.
