### ISSUE TITLE
Add known languages to autocomplete for language-specific settings

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#48317]
Issue Type: <b>Bug</b>

It works in this case (trigger autocomplete in **`|`**):
```json
{
    "[|"
}
```
It doesn't work in case of plain typing (start typing **`[java`**):
```json
{
    "|"
}
```

![autocomplete](https://user-images.githubusercontent.com/9638156/39081796-55cbf6ae-4550-11e8-96bd-e3f87ab78649.gif)

**Comment by jabacchetta** [comment]
To add to this, if a language-specific setting already exists for a language, then that language will appear in IntelliSense while typing. If the language does not have its own custom settings yet, you must manually trigger IntelliSense after the opening bracket, as @usernamehw suggests.

**Comment by usernamehw** [comment]
Works now.
