### ISSUE TITLE
TLSV1_ALERT_PROTOCOL_VERSION error when using pip from bash terminal

### ISSUE THREAD

**Issue by Elikrag** [Microsoft/vscode#48329]
- VSCode Version: 1.15.1
- OS Version: OSX Sierra 10.12.6

TLSV1_ALERT_PROTOCOL_VERSION  occurs for pip install <x> commands. Same commands function okay in native bash.

Steps to Reproduce:

1. Open built in terminal
2. Run any pip install command

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Works for me, I'll need more details to repro:

<img width="738" alt="screen shot 2018-05-11 at 8 01 59 pm" src="https://user-images.githubusercontent.com/2193314/39952964-3ce598d2-5556-11e8-8b85-351f6245a924.png">

Maybe your shell isn't configured correctly. Have you tried changing to a non-login shell? Add to settings:

```
"terminal.integrated.shellArgs.osx": []
```
