### ISSUE TITLE
Command to stage hunk under the cursor

### ISSUE THREAD

**Issue by franciscolourenco** [Microsoft/vscode#48323]
`Stage hunk` would stage the block of uninterrupted lines under the cursor which changed.

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/39135844-2f944934-471a-11e8-83cd-4f7c1c824b7b.png)

**Comment by franciscolourenco** [comment]
@joaomoreno, the screenshot you posted show a command to stage selected ranges, not the hunk under the carey. what you showed us equivalent to line or selection staging.

**Comment by joaomoreno** [comment]
How about this one?

<img width="983" alt="screen shot 2018-04-24 at 09 01 07" src="https://user-images.githubusercontent.com/22350/39171085-13636392-479e-11e8-950c-df63fff49091.png">

**Comment by franciscolourenco** [comment]
@joaomoreno that looks more like it! I understand that menu is available in the normal editor if you click on the diff decorations in the gutter?

Are there currently commands to do the following?
1. navigate between these change hunks 
2. open the diff decoration menu
3. stage the change

--------
Off topic: which color theme is that in the screenshot?

**Comment by joaomoreno** [comment]
1. The commands are `Move to Next Change` and `Move to Previous Change`
2. Hmm maybe not this one
3. We don't have one for this

Feel free to create independent issues for those missing commands.

---

I use the Ayu Mirage theme for quite some time now. Absolutely my favourite in the store.

**Comment by franciscolourenco** [comment]
1. This commands only seem to work on the normal editor, not in scm view right?

----------------------- 
Somehow my colors look way more saturated: 

<img width="840" alt="screen shot 2018-04-24 at 09 51 33" src="https://user-images.githubusercontent.com/208149/39173473-1a74cb7e-47a5-11e8-9b22-e134245c9a41.png">
<img width="1180" alt="screen shot 2018-04-24 at 09 49 27" src="https://user-images.githubusercontent.com/208149/39173474-1aa3c3fc-47a5-11e8-91f3-4f0886f26cc8.png">

**Comment by joaomoreno** [comment]
Yeah, only works in the regular editor, unfortunately.

They do... which OS are you on? I'm on macOS. There might be an OS level setting which lets you reduce overall saturation.

**Comment by franciscolourenco** [comment]
I'm on macOS 10.12.6 Sierra. 
I thought you were on Ubuntu judging by this contextual menu.

<img width="384" alt="screen shot 2018-04-24 at 09 59 14" src="https://user-images.githubusercontent.com/208149/39173875-3d932a96-47a6-11e8-9577-8dff93c0f24c.png">

**Comment by franciscolourenco** [comment]
Strange thing is that your screenshots and the official screenshots look correct. Wonder if this is something electron/webkit related. 

https://camo.githubusercontent.com/cd48eaf1d2bc4329db6d5ad7003bda5af7db81a6/68747470733a2f2f692e696d6775722e636f6d2f4b59584a6242752e706e67

**Comment by franciscolourenco** [comment]
> 1. The commands are Move to Next Change and Move to Previous Change

https://github.com/Microsoft/vscode/issues/48964	


> 3. We don't have one for this

https://github.com/Microsoft/vscode/issues/48965
