### ISSUE TITLE
Samba文件更新后VSC工作区文件不会自动更新

### ISSUE THREAD

**Issue by LanFly** [Microsoft/vscode#48320]
Issue Type: <b>Bug</b>

我使用Samba管理我的文件。我打开Samba中的一个文件夹，然后在Samba服务器中使用git更新该文件夹的内容，比如checkout、pull命令。VSC在文件更新后不会自动更新，需要重新打开该文件夹。

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.01GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
docthis-customize-tags|dwe|0.4.5
vue-snippets|hol|0.1.5
prettify-json|moh|0.0.3
cpptools|ms-|0.16.1
jscs|ms-|0.1.9
sublime-keybindings|ms-|3.0.3
markdown-preview-enhanced|shd|0.3.5

(3 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
Please report again in english.
