### ISSUE TITLE
intellisense stop working on node require() statement

### ISSUE THREAD

**Issue by goonode** [Microsoft/vscode#48338]
- VSCode Version: code-insider-1.23.0-1524201267
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. make a new project folder (i used express generator like: express --view=pug --css=sass )
2. npm install
3. open the folder in vscode
4. create a new file (i.e. test.js)
5. insert a require statement (i.e. const rl = require('readline'); and press enter)

Now cpu go to 100% , intellisense stop working (but also code formatter, linting...)

Closing vscode and re-run solve this issue until a new require statement is used.

Does this issue occur when all extensions are disabled?: Yes

update: it seems also the stable release (i tested on code-stable-code_1.22.2-1523551015_amd64) is affected by this issue.

**Comment by mjbvz** [comment]
@goonode Can you also please try installing and using typescript@next in your workspace by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). The quick version:

* `npm install typescript@next --no-save`
* In a JavaScript file, run the `Select TypeScript version` command and select the workspace version of typescript

**Comment by goonode** [comment]
@mjbvz I'm just doing it all. Following your instructions in the first test (i had TypeScript version 2.8.1 installed globally) i installed the TypeScript 2.9.0-dev.20180422 locally to the project and i'm using it but the issue persists. Also, for the second test, i created the jsconfig.json, with the same results.

However i notice the issue happens only if i type in the code line, and not if i copy and past the whole code line from another file. The exact moment the issue come is when i type in '' (two single quote
) inside the require(). Also pressing ctrl+space the popup show me the Loading... string forever.
![loading_snap](https://user-images.githubusercontent.com/38342960/39141473-377595a0-4728-11e8-9c62-9588a80833b3.png)

**Comment by Dartv** [comment]
I had the same issue. Installing the newest version of typescript solved it.

**Comment by mjbvz** [comment]
@goonode Did you also select TS 2.9 as the active version in your workspace. You can check this by running the `Select TypeScript Version` command from a javascript or typescript file: 

![screen shot 2018-04-27 at 2 01 56 pm](https://user-images.githubusercontent.com/12821956/39385003-907e207e-4a23-11e8-8a63-69705df26399.png)

**Comment by goonode** [comment]
@mjbvz Yes, i'm sure

![tslatest](https://user-images.githubusercontent.com/38342960/39396810-80eb1e78-4af5-11e8-9242-aaa769480734.png)

and after

![tslatest-after](https://user-images.githubusercontent.com/38342960/39396830-e741dcde-4af5-11e8-8203-ec19fa92e186.png)

Also i'm using the latest snapshot of code-insder (code-insider-1.23.0-1524818652_amd64), and the ts version 2.8.3 should be the version bundled in.

Also i made a lot of test from my side to try to see if the issue disappear (ie removing .config/Code - Insider folder end restarting from clean configuration, erasing user prefs, using tsconfig.json, and so on) but all without success. 

ps: the strange thing is if i copy and past a whole "require" line then the intellisense works on that line, but if i type in the line this does not work.

**Comment by mjbvz** [comment]
Ok, thank you for confirming.

To help us investigate this ,can you please try collecting the typescript server log while using TypeScript@next:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. In vscode with a js/ts file open, run the `TypeScript: Open TS Server logs` command. This should open a log directory with a `tsserver.log` file in it

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by goonode** [comment]
It seems to me there is no error in log, could it be this issue is not related to typescript ?

Please, find below, both files created by logger:
 
[collected-2.9.tar.gz](https://github.com/Microsoft/vscode/files/1964324/collected-2.9.tar.gz)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23914
