### ISSUE TITLE
Debug console hyperlinks are not clickable

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/vscode#48337]
- VSCode Version:  1.22.2
- OS Version:  WIndows 10

Steps to Reproduce:

1.  Output a hyperlink to the debug console
2.  Click on it

![image](https://user-images.githubusercontent.com/966863/39092442-ec373026-4605-11e8-8ff5-464cab86f050.png)

It would be great if the link would open in a new browser instance, or if the click event could be caught in the extension that created it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/34026
