### ISSUE TITLE
CPP `dotnet restore --configfile NuGet.Config` fails

### ISSUE THREAD

**Issue by peteromueller** [Microsoft/vscode#4833]
- VSCode Version: 0.10.11 (February 2016)
- OS Version: 10.11.4

Steps to Reproduce:

1. install VSCode
2. install ext install cpptools according https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

The at step  4: dotnet restore --configfile NuGet.Config.

I get the following error:
dotnet restore --configfile NuGet.Config
log  : Restoring packages for /Users/pmueller/.vscode/extensions/ms-vscode.cpptools-0.4.1/project.json...
error: Failed to retrieve information from remote source '/Users/pmueller/.nuget/packages/'.

...

error: Unable to load the service index for source https://www.myget.org/F/dotnet-core/api/v3/index.json.
error:   The type initializer for 'Crypto' threw an exception.
error:   Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)

How can I fix this?
Thanks,
Peter

**Comment by sridmad** [comment]
Peter,

Thanks for trying out the extension. We are pushing an update to the extension today that should have more detailed steps for installing debugger bits.

Thanks,
-sridhar

**Comment by aeschli** [comment]
This issue should go in the C++ extension issue tracking system (email at mailto:c_cpp_support@microsoft.com).
@sridmad Can you add it to your tracking system?
