### ISSUE TITLE
Fails to detect NPM modules

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#48334]
Issue Type: <b>Bug</b>

NPM module are installed, yet code insiders fails to detect the modules.

![screenshot_20180421_225444](https://user-images.githubusercontent.com/439226/39090893-b67ce0c8-45b7-11e8-854a-a28f7e90e237.png)

VS Code version: Code - Insiders 1.23.0-insider (c1cd4378c5e5dc434ed959e13556d05240a8ca18, 2018-04-20T05:12:24.983Z)
OS version: Linux x64 4.4.0-119-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (3 x 3013)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.80GB (0.30GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.14.1
EditorConfig|Edi|0.12.1
Angular-BeastCode|Mik|6.0.12
sort-lines|Tyr|1.6.1
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
geeks-ms|jor|0.0.1
sort-typescript-imports|mic|1.4.1
angular2-inline|nat|0.0.17
language-stylus|sys|1.9.1
vim|vsc|0.11.4
better-align|wwm|1.1.6
markdown-pdf|yza|1.0.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this repo with all extensions disabled? Please provide some repo steps or a small example project

**Comment by mjbvz** [comment]
I'm closing this issue as it hasn't had recent activity. Sorry, it feel off my radar
