### ISSUE TITLE
vs code function suggest

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#48335]
add code intellisense;show that the current code is using IntelliSense（ the built-in / install extended code IntelliSense）;can manually modify it;this can solve some of the programming language mixed writing caused by IntelliSense do not work.Of course, users need to set up a switch to allow users to choose whether to join this function.
In order to distinguish file types, the text effect can be changed to language ICON.

![001](https://user-images.githubusercontent.com/20437381/39091080-a8dfb9b4-461f-11e8-8c4c-cd612614b9c9.png)

**Comment by lihua06** [comment]
The main purpose of this function is to set up the current file code IntelliSense priority by manual setting, so as to solve the problem of code mixing to produce no work or confusion.

**Comment by mjbvz** [comment]
Sorry, I do not understand this issue. In your example, please describe the steps to reproduce the problem and the expected behavior

**Comment by lihua06** [comment]
Please close this question. I believe you have been used to modifying the file type to trigger the intelligent hint of the mixed file.THANK YOU
