### ISSUE TITLE
workbench.action.files.newUntitledFile does not set window.activeTextEditor in tests.

### ISSUE THREAD

**Issue by JackKCWong** [Microsoft/vscode#48344]
I am trying to write a Mocha test which:
1. close all editors & open a new one. (setUp the test case)
2. do some test.

I can see the close & open succeeded but `window.activeTextEditor` is still `undefined` even in the presence of an untitled editor. I could not find any docs / google to troubleshoot this issue.
  

- VSCode Version: 1.22.2
- OS Version: Linux  4.15.17-300.fc27.x86_64 #1 SMP Thu Apr 12 18:19:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. run the below test
```typescript
    test("Something 1", function () {
        commands.executeCommand("workbench.action.closeAllEditors")
            .then(done => {
                return commands.executeCommand("workbench.action.files.newUntitledFile");
            })
            .then(done => {
                if (window.activeTextEditor) {
                    return window.activeTextEditor.edit(editBuilder => {
                        editBuilder.insert(new Position(0, 0), "hello world");
                    });
                }
                throw new Error('can not open new editor');
            })
            .then(done => {
                if (window.activeTextEditor) {
                    assert.equal(window.activeTextEditor.document.getText(), "hello world");
                }
            })
            .then(success => {
                assert.ok("success: " + success);
            }, err => {
                assert.fail(err, {}, err);
            })
            ;
    })
```
2. I can see a new untitled editor appears but the `window.activeTextEditor` is undefined and the test  fails with "can not open new editor"

**Comment by bpasero** [comment]
@jrieken seems to be a timing issue (and I remember we had this issue reported before). When I wait some millies, the editor is there. Since visually the editor shows up, maybe it is some race condition when we synchronise/update the active editor over to the extension host side?

**Comment by jrieken** [comment]
> Since visually the editor shows up, maybe it is some race condition when we synchronise/update the active editor over to the extension host side?

Depends on the command and how that waits document creation. 

@JackKCWong Please try this with *real* api, not a command, e.g. with `showTextDocument(vscode.Uri.parse('untitled:Foo-1')`?
