### ISSUE TITLE
Feature Request: Make common used editing functions as a part of vscode

### ISSUE THREAD

**Issue by ToMakeSense** [microsoft/vscode#48341]
I would like built-in vs code to be more powerful in editing like sublime
![image](https://user-images.githubusercontent.com/6244148/39093653-8c90a1f2-4655-11e8-9ca1-1d5b14f7f032.png)

So making common used editing functions below as a part of vscode will be a better idea(properly shortcuts included)
- [x] Trim whitespaces(front, end, both)
- [ ] Remove duplicated lines
- [ ] Insert numbers, eg: [Insert Numbers](https://github.com/Inori/vscode-InsertNumbers/) (vscode doesn't have to be that powerful)
- [x] Lower case, upper case, capitalized case, title case, eg:[convert case](https://convertcase.net )
- [ ] One more thing, vscode's  edit menu is too much brief :unamused: ...
![untitled](https://user-images.githubusercontent.com/6244148/39093913-aead741e-4659-11e8-8ec0-f8f6c1a2f6b6.png)

**Comment by ToMakeSense** [comment]
#15727

**Comment by sbatten** [comment]
Some of these commands do indeed exist in the core product, but they are not shown in the menu. I believe we prefer keeping them accessible primarily via the command palette. As for commands that are implemented via extensions, it isn't currently possible to add them to the edit menu, but it could be in the future.

/cc @bpasero @jrieken

**Comment by ToMakeSense** [comment]
Commands exist in the core product I found:
- [X] Trim whitespaces(front, end, both)
- [X] Lower case, upper case, capitalized case
- [ ] Remove duplicated lines
- [ ] Insert numbers
