### ISSUE TITLE
Allow attaching screenshots to the generated API docs

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode#48343]
Hello, I have found myself struggling with imagining what the different providers available to the extension APIs are and ended up having to always go and mock up a quick extension using it to see what the provider does. To alleviate this and help new extension authors, I thought I'd go and attach a bunch of screenshots to the extension API documentation at:

https://code.visualstudio.com/docs/extensionAPI/vscode-api

I can see, however, that this page is actually generated from the typings file at:

https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts

Would it be okay to update that file (I don't think it itself is generated) to include animated images in the MarkDown comments and start placing those in a new `img` directory?

**Comment by jrieken** [comment]
Not sure yet. Apart from the technical aspects, having just an image or animation might not be enough.  We often try to add a link to the docs, like so: 

```md
/**
 * The completion item provider interface defines the contract between extensions and
 * [IntelliSense](https://code.visualstudio.com/docs/editor/intellisense).
 *
 * Pr...
```

Albeit not as obvious it has more power because the doc pages are more rich. @TomasHubelbauer What provider where you lacking documentation about?

**Comment by TomasHubelbauer** [comment]
In particular, I found the link going from the `HoverProvider` to the documentation page for Intellisense confusing. But thinking about this some more, I think low hanging fruit would be just interlinking these documentation pages from the `register*Provider` method sections in addition to the `*Provider` class sections. I know that if you click thru the method signature's return type, you'll get there, but IMO we can make this experience more straightforward. What do you think about this duplication? Benefits outweight costs (maintenance) or is it a bad idea?

**Comment by jrieken** [comment]
> What do you think about this duplication? Benefits outweight costs (maintenance) or is it a bad idea?

I like it.

**Comment by TomasHubelbauer** [comment]
I'll try to carve out some time soonish and contribute a PR implementing it.
