### ISSUE TITLE
Test: Npm Scripts explorer

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#48354]
- [x] macOS: @weinand 
- [x] windows @gregvanl 

Complexity: 3

Authors: @egamma

## Background
![image](https://user-images.githubusercontent.com/172399/39098692-8028d63c-4623-11e8-8378-606a03c5cb18.png)

The npm scripts explorer supports to:
- open a script inside a package.json file or the scripts section when the package.json file is selected, This is the default action when clicking on a script
- run a script as a Task with the output shown in the terminal, both yarn and npm are supported for running the script
- debug a script, when the script defines the node debug options. 

To enable the scripts explorer use the setting  `npm.enableScriptExplorer` and set it to true.

## Testing

- test single folder and multi-folder setups. In the single folder the folder is not shown to the user.
- test that all debug options. Both the new and legacy debug options should be detected. When the debug options are missing then this is reported to the user with a link to the documentation.
- The explorer should only appear when the workspaces that contain a `package.json`file.
- Out of date script names should be detected. There is a refresh action to refresh the scripts
- The setting `npm.packageManager` is honored.

**Comment by weinand** [comment]
@egamma I assume I have to use the latest version from the repo for this and build it myself?
