### ISSUE TITLE
Errors in Settings and keybindings 

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#48356]
I'm getting two errors when editing my `user settings` & `keybindings.json` those errors are; *end of file expected* (user settings) & *expected comma or closing brace* (keybindings.json).  

As for the *end of file expected* error, I've double-checked all closes braces numerous times as I have the settings enclosed within braces as such;
`{
 <settings>
 }
`
The *expected comma or closing brace* is enclosed within an array followed by braces for each keybinding.

**Comment by sandy081** [comment]
@SheepDomination It would be helpful to reproduce to show the content (or sample) when these errors are appearing.

**Comment by SheepDomination** [comment]
The first error is within the *user settings*.
`{
<series of lines related to settings for vscode
}`

`{
<settings for extension>
}`
It's the first parenthesis for the *<settings for extensions>* that is firing a *end of file expected* error ?

Moving onto the *keybindings.json* file error, rather then abbreviate the code as it was simpler too with the *user settings* error; I've posted an exact replica of what is within my *keybindings.json* file.

`[
    { "key": "ctrl+e",
    "command": "toggle",
    "when":"workbench.view.explorer",
    },
    { 
    "key": "shift+alt+r",
    "command": "settings.cycle.workbench.viewextensions", 
    "settings.cycle":[{
        "id":"extenView",
        "values":[
            {
            "workbench.extensions.action.openExtensionsFolder":true
            },
            {
            "workbench.extensions.action.showDisabledExtensions":false
            }
        ]
    }`
The last parenthesis in the code as seen above is firing a *expected comma or closing bracket* error ?

**Comment by SheepDomination** [comment]
I've added two closing parenthesis `} }` at the end of the *keybindings.json* those two parenthesis render as an error ?

The *settings* file is enclosed within an open `{` and closing `}` parenthesis but the first parenthesis gives an *end of file expected error* ?

**Comment by sandy081** [comment]
> I've added two closing parenthesis } } at the end of the keybindings.json those two parenthesis render as an error ?

Both files are `json` files and they need to be syntactically correct. 
Please refer to http://json-schema.org/ how json schema works.

Regarding settings file, can you please provide an example, otherwise it is hard to help

**Comment by SheepDomination** [comment]
I solved the keybinding.json error.  As for the settings error; 
`{
    "commentBox.textAlignment":"left",
    "commentBox.boxWidth":75
}`

The first parenthesis is an error ?

**Comment by sandy081** [comment]
It looks to me valid. Can you please provide the screenshot of the error by opening the Problems view?

**Comment by SheepDomination** [comment]
![2018-04-25_12-54-18](https://user-images.githubusercontent.com/6827459/39260555-dfab32d8-4887-11e8-89b8-131809c459b2.png)

**Comment by SheepDomination** [comment]
Found my problem; don't separate settings within parenthesis per extension, keep it as one.
