### ISSUE TITLE
Custom decorations should render ontop of indent guides

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#48353]
Issue Type: <b>Bug</b>

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17133

Make a decoration with left/right borders

![image](https://user-images.githubusercontent.com/5593825/39098106-02ffccd6-4666-11e8-8f7e-eb6ffe56ae72.png)

Note the left border is not shown, because the custom decoration is below the indent lines in the css

![image](https://user-images.githubusercontent.com/5593825/39098134-839de2d8-4666-11e8-8721-41eee42acc29.png)

Moving the custom decoration to the end will make it draw correctly:

![image](https://user-images.githubusercontent.com/5593825/39098140-9e9941d6-4666-11e8-85c4-6583e0ae0ad5.png)

**Comment by alexandrudima** [comment]
Full steps to reproduce:

* `package.json`:
```js
{
    "publisher": "alex",
    "name": "48353",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {
	var dectype = vscode.window.createTextEditorDecorationType({
		border: '1px solid blue'
	});
	vscode.window.activeTextEditor.setDecorations(dectype, [
		new vscode.Range(0, 0, 0, 1),
		new vscode.Range(1, 0, 1, 1),
		new vscode.Range(2, 0, 2, 1),
		new vscode.Range(3, 0, 3, 1),
		new vscode.Range(4, 0, 4, 1),
		new vscode.Range(5, 0, 5, 1),
		new vscode.Range(6, 0, 6, 1),
		new vscode.Range(7, 0, 7, 1),
		new vscode.Range(8, 0, 8, 1),
		new vscode.Range(9, 0, 9, 1),
	]);
}
```
* Have a file `test.js`:
```js
for (let index = 0; index < array.length; index++) {
    // const element = array[index];
    // this is another line
}
```

![image](https://user-images.githubusercontent.com/5047891/39116283-590c080a-46e4-11e8-8669-9c6e9c421bb2.png)

**Comment by CoenraadS** [comment]
Thanks for the quick turnaround ❤️
