### ISSUE TITLE
Tasks fail to run on networked locations

### ISSUE THREAD

**Issue by rbenson** [Microsoft/vscode#48351]
My workplace maps the Documents folder to a networked location, so it's automatically backed up. So it looks like `C:\Users\Username\documents` it is really `\\domain\server\username\documents`. My tasks.json is below. If I run my task in a networked directory (ex `\\domain\server\username\documents\md_test`), I get a  "Failed to create terminal for task Convert to markdown" error. If I make the same directory structure in my user folder, C:\Users\username\, or my desktop, the task runs fine.

        {
            // See https://go.microsoft.com/fwlink/?LinkId=733558
            // for the documentation about the tasks.json format
            "version": "2.0.0",
            "tasks": [
                {
                    "label": "Convert to markdown",
                    "type": "shell",
                    "command": "markdown-it \"${file}\" -o \"${fileBasenameNoExtension}\".html",
                    "group": {
                        "kind": "build",
                        "isDefault": true
                    },
                    "problemMatcher": []
                }
            ]
        }

OS: Win 10 Enterprise 64 bit 
VSC: 1.2.2

**Comment by dbaeumer** [comment]
@Tyriar are there any restrictions in terms if UNC paths. When executing the task the task system will use the UNC folder as the cwd.

@rbenson can you try one work around. Set
```
"options": {
	"cwd": "C:\\"
}
```
to see if the task runs successful or not.

**Comment by rbenson** [comment]
@dbaeumer  The task still failed, though that caused the terminal to popup, where it didn't before. I tried setting `cwd` to the directory of my markdown files, but that didn't work.

The terminal is blank.

**Comment by Tyriar** [comment]
> @Tyriar are there any restrictions in terms if UNC paths. When executing the task the task system will use the UNC folder as the cwd.

@dbaeumer I've never tested the terminals on network drives.

**Comment by rbenson** [comment]
@Tyriar I just looked, the terminal shows the correct path. I did `ls`, `cd ..`, and `code .` and they all worked as expected, though ls and `code .` took maybe 2 seconds to do it.

**Comment by dbaeumer** [comment]
I found the problem. CMD.EXE doesn't support starting with an UNC path as the cwd. I have code to check this but that one doesn't only check for Windows. Need to make this cmd.exe specific.

@rbenson I assume you are using PowerShell. Right ?

**Comment by dbaeumer** [comment]
To verify you need to have a workspace on a UNC drive. You can share some folder of your Windows machine and then use it using UNC path \\localhost\sharedFolder. @bpasero may be you can verify since you know how that trick works.

**Comment by rbenson** [comment]
@dbaeumer No - I am using bash. I made  a workspaces directory in the root of my Documents directory (moved from C:\Users\Name\.vscode\workspace to `\\domain\server\username\documents\vscWorkspaces`), and the task still failed.  Setting the terminal to PS,  the task still fails.

Please reopen

**Comment by dbaeumer** [comment]
I fixed it yesterday so you need to either test this with insiders from today or wait until we ship the next stable. As said it didn't work with PowerShell either since the old code checked for Windows not for Windows & cmd.exe. 

Regarding bash: task and bash are not well supported under Windows. Major problem here is that VS Code assume that when running under Windows `\` and drive letters are used. We are looking into making this work nicer.

**Comment by rbenson** [comment]
Thanks for that. I don't haves the privs to enable insders, so I'll keep a look out for the patch.

**Comment by roblourens** [comment]
Does this fix the scenario or just add a warning? I see the new warning when using cmd and running the vscode build task without cwd customized on the task. In other cases, I just see a terminal error message.

- Open `\\localhost\c$\Users\roblou\vscode`
- Terminal is powershell, run build task
- `The terminal process terminated with exit code: 1`
- Same if I set `"cwd": "c:\\"`

cmd
- Terminal is cmd.exe, run build task
- `Can't execute a shell command on an UNC drive using cmd.exe.`
- If I set `"cwd": "c:\\"`, `The terminal process terminated with exit code: 4294963238`

Also, lots of errors from task detection.

**Comment by dbaeumer** [comment]
UNC paths aren't supported under `CMD.EXE` so the warning is expected. The are under PowerShell to my knowledge. I will reopen and will check again.

@roblourens for the first case could you open a terminal ?

**Comment by roblourens** [comment]
Yes, it looks like 
![image](https://user-images.githubusercontent.com/323878/39384786-c9673570-4a22-11e8-8673-1710d9f2b989.png)

**Comment by dbaeumer** [comment]
Need to move the issue.

**Comment by dbaeumer** [comment]
@alexr00 something to investigate again.

**Comment by alexr00** [comment]
I ran this task and it worked (echoed "testing'):

    {
        label": "testTask",
        "type": "shell",
        "command": "echo testing",
        "options": {
            "cwd": "\\\\HOST\\Newfolder",
            "shell": {
                "executable": "powershell.exe"
            }
        }
    }

I also saw the error about using UNC drives with cmd.exe.

It doesn't look like there's a bug here now 😊

**Comment by dbaeumer** [comment]
@alexr00 thanks for trying to reproduce.
