### ISSUE TITLE
Zooming in / out beyond the maximum still increases / decreases window.zoomLevel

### ISSUE THREAD

**Issue by moonPtr** [microsoft/vscode#48357]
Since it's a little tough to explain, here's a video showcasing it: https://youtu.be/rVCn0rhj76k

**Comment by ramya-rao-a** [comment]
What is the maximum you are referring to? Can you provide more details on the issue?
Please read or wiki on [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions)

**Comment by moonPtr** [comment]
Maximum / Minimum as in the values at which it stops zooming in / out any further (-8/9 for me, i don't know if it depends on things like monitor resolution)

**Comment by alexandrudima** [comment]
@moonPtr I don't understand what you mean, can you please explain like I'm 5 ?

**Comment by moonPtr** [comment]
When you press Ctrl +, it zooms in
When window.zoomLevel reaches 9, Ctrl + will increase window.zoomLevel but it doesn't actually zoom in any more
Same thing with Ctrl - (zoom out)

So if you press Ctrl + 20 times, you have to press Ctrl - 10 times before it ACTUALLY zooms out again

**Comment by moonPtr** [comment]
@alexandrudima I don't know if this helps, but I recorded a quick video
https://youtu.be/rVCn0rhj76k
The second code instance is used to watch the window.zoomLevel setting of the first instance. Zooming is done via Ctrl + and Ctrl -

**Comment by alexandrudima** [comment]
@moonPtr Thank you for the explanation.

**Comment by bpasero** [comment]
Would accept a small reasonable PR if someone wants to chime in.

**Comment by gioragutt** [comment]
@bpasero Hey man, I've uploaded a PR, not quite sure how this'd be handled by you guys, in terms of coding standards, so I would love a code review on that.

**Comment by bpasero** [comment]
I think a good solution to this (if possible) would be to try to set the desired zoom level and then check if the zoom level was applied and only then update the setting (or restore it to the previous value). I think there is API from Electron to query the current zoom level.
