### ISSUE TITLE
Extension and Plugins offline availablity.

### ISSUE THREAD

**Issue by mohammadayoub96** [Microsoft/vscode#48350]
### Issue Type
Feature Request

### Description

I love this editor, Please provide with this feature, Extension and Plugins should be available offline as adobe brackets.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

**Comment by rbenson** [comment]
You can save the package and install it locally.

**Comment by mohammadayoub96** [comment]
So Please show me the method, how can i do this?

**Comment by rbenson** [comment]
If you can download the ext originally, it will be located in your `C:\Users\Username\.vscode\extensions\` folder, The directories are usually titled `authorId.name-version`, copy that directory to like a usb stick. Put the usb stick into the other computer that's offline, copy from the usb to the similar location.

**Comment by mohammadayoub96** [comment]
Thank u Very much. u solved my problem but there should be an official way of doing this.

**Comment by rbenson** [comment]
All extensions are are files written in javascript, typescript, and sometimes others languages. There's a file within each directory called package.json, that's how VS Code 'knows' what to do with it. I am not sure how an official way would look since most would either know this or just re-download the ext on a new computer.

**Comment by mohammadayoub96** [comment]
I think Developers must make and support extensions in zip file that will be the complete solution. Zip file contain all the files and after dragging zip file on VS Code install extensions Page it will added to local path as you said :\Users\Username\.vscode\extensions\.
As Adobe Brackets installs extensions

![36259727-2b14bd36-1285-11e8-8a17-9945e3d222dd](https://user-images.githubusercontent.com/20210961/39100975-4e285dae-46ac-11e8-9fc1-665d900d5409.png)

**Comment by ramya-rao-a** [comment]
- Go to the [Marketplace](https://marketplace.visualstudio.com/vscode) and find the extension you want
- Download the extension using the link on the right
<img width="183" alt="screen shot 2018-04-22 at 7 00 59 pm" src="https://user-images.githubusercontent.com/16890566/39103424-7a51d498-465f-11e8-95f0-7568b55311ff.png">
- This will download a file with extension ".vsix". This is similar to a zip file and has all the required files
- Open VS Code and run the command `Extensions: Install from VSIX...` and select the copied vsix file

**Comment by mohammadayoub96** [comment]
Thank you very much, God bless you a lot.
