### ISSUE TITLE
Cannot get Decorations for a textEditor

### ISSUE THREAD

**Issue by ryanluker** [Microsoft/vscode#48364]
- VSCode api version: 1.1.10
- OS Version: Linux

## Steps to Reproduce:
1. Render decorations with ```textEditor.setDecorations```
2. Try to find current decorations with ```textEditor.getDecorations``` but it doesnt exist?

## Background:
I am looking at adding true e2e tests for my vscode extension
https://github.com/ryanluker/vscode-coverage-gutters/pull/126/commits/3af53e004958137ae4f940b0f4e809775dee4b24#diff-579bc502e2c0744db6d55afe38b9f3d9R14
but there doesnt seem to be a way to see the current decorations?

Based on some internet searching I couldnt find anyone else doing this level of e2e testing (correct me if I am wrong and or if there is examples in the vscode project itself for this), so this issue would probably be more of a feature request to add a new piece of functionality to get decorations? I have a feeling the lack of ```getDecorations``` might be for security / performance reasons but I am happy to be wrong in this :smiley: .

**Comment by alexandrudima** [comment]
The root cause is performance. We don't want to sync back all those (potentially thousands) of decorations back on each keystroke.

**Comment by DanTup** [comment]
@alexandrudima Is there any other way we can get the the updated range for a decoration as the user modified the document? Eg., let's say I apply a decoration to a line of code and then the user inserts a newline before it - is there any way I can find the new range of that decoration?

**Comment by DanTup** [comment]
@alexandrudima Thanks for confirming. For now, I'm keeping track of the ranges myself and subscribing to onDidChangeTextDocument and then updating my ranges based on the changes being made. It's kinda clunky, but seems to work (as long as the user doesn't edit the file outside of Code, then things will fail).

I'm not sure whether to raise a feature request for better handling of this (really what I'd love is to be able to attach metadata to a random range of code and let Code track it for me) because I suspect not many extensions will need to do this kind of thing.

**Comment by DanTup** [comment]
Yeah; I know my use is a bit weird (I don't know if there are other use cases for this) and I'm not sure whether decorations is the best way to handle it (in my case I am rendering decorations for this data, so it'd be convenient, but if making something more reusable it might make sense to keep separate).

For now, my mapping of edits *seems* to be working well so I don't think I'm blocked; but I might shout for ideas if I hit problems trying to maintain the state myself.

**Comment by alexandrudima** [comment]
I suggest we continue tracking in #54147, as #54147 has a more clear description and avoids the decoration pitfall by mentioning new explicit API for tracked ranges.
