### ISSUE TITLE
how to auto expand Object/ Array in debug console

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#48369]
- VSCode Version:1.22.2
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. when i use vscode i console something in my code .when console a long object i need to click it . if i console many object . i need click one by one.
![image](https://user-images.githubusercontent.com/3990411/39108713-389c7650-46fc-11e8-9fa6-db11198637db.png)

2.how to config auto expand Object/Array in debug console.

**Comment by zhiqiang21** [comment]
thanks.

**Comment by saurabhrb** [comment]
> This is a fair feature request to always autoExpand objects in the debug console.
> We are not doing this out of the box becuase it is a bit unexpected and becuase some objects can take a lot to expand.
> Leaving this open as a feature request and if more users request it we woudl be open to PRs that fix this

can we have a "Expand All" UI option in Debug console similar to "Collapse All"?

**Comment by weinand** [comment]
@saurabhrb "expand all" is a bad idea because data structures often have cycles and that would result in endless expands.

**Comment by skogler** [comment]
Just ran into this issue, its really annoying in some cases.
I do not agree that cycles would be a problem, expanding even a single level would already be very helpful.

**Comment by RichVanderwal** [comment]
I'd like an "expand all" button with a loop detector to take care of the cycling behavior above. It would save me a lot of time when examining the data structures of my running program!

**Comment by rg314** [comment]
Just had the same issue. This is super annoying. Expand all :)

**Comment by ValerioB88** [comment]
same. Please have an "expand all". Just one level is most of the time ok.

**Comment by vinodCustomerSuccess3000** [comment]
expand all should be obvious feature, it makes no sense to show them as object/array :( we would never know whats inside. Atleast build a flag like --expand

**Comment by ryanoboril** [comment]
Please add Expand All - do not make it automatic, and do not keep closing this feature request
