### ISSUE TITLE
TypeScript incorrect optional parameter syntax highlighting

### ISSUE THREAD

**Issue by RetroCraft** [Microsoft/vscode#48361]
Issue Type: <b>Bug</b>

The syntax highlighting for an optional property named `new` within an interface is coloured wrong.

Expected results: consistent colours for each property name and type

Actual results:

![Image](https://i.imgur.com/OrQ1nVi.png)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|Memory (System)|15.94GB (6.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-database|baj|1.5.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
python|ms-|2018.3.1
ejs-language-support|Qas|0.0.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/605 to track this upstream
