### ISSUE TITLE
Snippets docs becomes frozen when using useCodeSnippetsOnMethodSuggest 

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#48368]
- VSCode Version: 1.23.0-ins
- OS Version: win7x64

```
Version 1.23.0-insider
Commit c1cd4378c5e5dc434ed959e13556d05240a8ca18
Date 2018-04-20T05:17:25.189Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64
```
**_exts disabled_**

-----------------

_xxx.component.ts_
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  animations: [
    
  ]
})
export class AppComponent {
}

```

-----------------

Snippets list gets frozen state on different items of the list.

GIF:
![snippets list frozen](https://user-images.githubusercontent.com/24613274/39106689-01dea0ba-46c6-11e8-8773-c57985514f31.gif)

One more example:

![trigger](https://user-images.githubusercontent.com/24613274/39106996-e2cdb678-46c7-11e8-9244-9eee8b08479a.gif)

Maybe the problem is in the duplicated useless items in the list, but not sure.

**Comment by ramya-rao-a** [comment]
@user3323 Do you have emmet enabled for this file type? Do you still see this issue if you disable emmet? Try adding the below in your settings to test this theory:
```
"emmet.showExpandedAbbreviation": "never"
```

**Comment by user3323** [comment]
@ramya-rao-a , hello.

I figured out what an option makes a problem:

`"typescript.useCodeSnippetsOnMethodSuggest": true`

GIF:
![ts option makes freeze](https://user-images.githubusercontent.com/24613274/39164621-f08a4e18-4788-11e8-81b7-b5312f238691.gif)

**Comment by ramya-rao-a** [comment]
Is there any codebase that we can try and repro this?
Or can you provide a sample code that we can use?

#47988 is similar to this issue, but has nothing to do with `"typescript.useCodeSnippetsOnMethodSuggest": true`

**Comment by user3323** [comment]
@ramya-rao-a 

`node_modules` ---> `@angular`
`src` ---> `qqq.ts`

[snippets_list_frozen.zip](https://github.com/Microsoft/vscode/files/1941667/snippets_list_frozen.zip)

------------------

I cannot repro it in stable build (TypeScript v2.8.1):
```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

... so, it happens only in Insiders (TypeScript v2.8.3):
```
Version 1.23.0-insider
Commit b845ce918f2689344795e845ae6ef691916c3079
Date 2018-04-24T05:17:07.677Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by user3323** [comment]
@ramya-rao-a 
and about similarity of issues.. well, I think it only looks like that (but not), because in the instances and repros you can face both of them simultaneously...
https://github.com/Microsoft/vscode/issues/47988 is more like my another issue https://github.com/Microsoft/vscode/issues/46457 (that moment I thought it was an extension problem)... then https://github.com/Microsoft/TypeScript/issues/23087 was created to track it, and yesterday it was labeled as bug, and fixed already (cannot test it)

**Comment by ramya-rao-a** [comment]
Thanks @user3323 
Using your code sample, I can repro this when `typescript.useCodeSnippetsOnMethodSuggest` is enabled and this has nothing to do with the root cause for #47988 

cc @mjbvz

**Comment by ramya-rao-a** [comment]
@user3323 I dont see this happening anymore. Can you try again from your end?

**Comment by roblourens** [comment]
Removing from milestone
