### ISSUE TITLE
Recommended Extensions - No suggestions

### ISSUE THREAD

**Issue by tekk** [Microsoft/vscode#48367]
Issue Type: <b>Bug</b>

I see no recommended extensions.

VS Code version: Code - Insiders 1.23.0-insider (c1cd4378c5e5dc434ed959e13556d05240a8ca18, 2018-04-20T05:12:24.983Z)
OS version: Linux x64 4.14.34-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 1953)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|11.64GB (3.80GB free)|
|Process Argv|/home/tekk/Installed/VSCode-linux-x64/code-insiders|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
php-pack|fel|1.0.1
python|ms-|2018.3.1
csharp|ms-|1.14.0
vscode-icons|rob|7.22.0

</details>

## Screenshot
![manjaro-vscode-recommended](https://user-images.githubusercontent.com/721967/39103676-78b4862e-46ac-11e8-8e06-fae05abc656b.png)

**Comment by ramya-rao-a** [comment]
Is this a new installation?
