### ISSUE TITLE
macOS - integrated terminal - rendering issues specifying just terminal.foreground

### ISSUE THREAD

**Issue by methodbox** [Microsoft/vscode#48362]
- VSCode Version: 1.22.2
- OS Version: 10.13.4

Steps to Reproduce:

1. Set *only* "terminal.foreground": "#ffa500", (color doesn't matter)
2. Exit terminal by command - reopen terminal

Does this issue occur when all extensions are disabled?: Yes/No - Yes

If you do not specify a "terminal.background" in User Settings when specifying a "terminal.foreground" the terminal will do this:

![image](https://user-images.githubusercontent.com/12660440/39100989-d11b53dc-4658-11e8-9fdd-d4a4319f739b.png)

It also seems to hang when trying to scroll up and down (intermittent).

After specifying "terminal.background": "#000000" it works fine.

I suspected having transparency enabled in the macOS system terminal would cause this, but setting opacity @ 100% had no effect.

**Comment by Tyriar** [comment]
I can't repro. This happens when `terminal.background` has an opacity and I think it has a fix coming soon. What theme are you using? I'm guessing your theme defines terminal.background as transparent.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/46374
