### ISSUE TITLE
Is it possible to change already published extension's name?

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#48378]
I have an extension with name `vscode-box-drawing` and I'd like to change it `vscode-markdown-drawing` to bring it in line with my other extension names (it only supports MarkDown files). Is this possible?

I am not talking about the human-friendly name displayed in the VS Code UI, but the one which is a part of the extension's identifier in the Marketplace.

If I change it in `package.json` and republish, I am worried I'll get a brand new extension and will have to remove the old. That is also doable, but before I do that, I'd like to know if there is a better way.

#3670 (about changing extensions' publisher) is distinct from this.

**Comment by sandy081** [comment]
Yes this can be done. Please contact Marketplace team @viradhamMS @pkuma-msft
