### ISSUE TITLE
Tool bar problem

### ISSUE THREAD

**Issue by alexsynovia** [Microsoft/vscode#48374]
Issue Type: <b>Bug</b>

Bonjour, VS code est complètement buggé. Je ne sais absolument pas comment reproduire ce genre de chose. Ci-joint un screen du bug.
![image](https://user-images.githubusercontent.com/37076821/39113745-ef5c6c9e-46dc-11e8-8831-c634f440dac4.png)

Comme vous pouvez le constater, la tool bar apparaît en blanc. De plus, il m'est possible de déplacer les icones de mon bureau en cliquant sur la partie blanche. 

Bon courage, 
bsx.<3

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.89GB (3.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
Please report issues in english.
