### ISSUE TITLE
getDiagnostics with a Uri returns different results to getDiagnostics without filtered by the same Uri

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#48371]
I have the following code in a test:

```ts
const allErrors = vs.languages.getDiagnostics();
const errors1 = allErrors.filter((e) => e[0].fsPath === "m:\\Coding\\Applications\\Dart-Code\\test\\test_projects\\hello_world\\lib\\test.dart");
const errors2 = vs.languages.getDiagnostics(vs.Uri.file("m:\\Coding\\Applications\\Dart-Code\\test\\test_projects\\hello_world\\lib\\test.dart"));
assert.equal(errors1.length, errors2.length);
```

The assert fails, with there being 1 item in `errors1` and 0 items in `errors2`. As far as I can tell, these should be the same.

**Comment by DanTup** [comment]
Actually, I'm confused here - I found I hadn't waited for my diagnostics to finish updating, so it's possible these were being updated in the background. I'm not sure how that works since this is synchronous code, but when I await my diagnostic changes correctly before this, I get consistent results.

@jrieken Is there any multithreading going on here? Could calling `getDiagnostics` repeatedly with no async code still result in different results? If so, I think this is working as intended.

**Comment by jrieken** [comment]
No, multithreading but looking at your sample you should know that `getDiagnostics(Uri)` uses `Uri.toString()` as identifier and *not* `Uri.fsPath` (which is something you should only ever use for fs-access)

**Comment by DanTup** [comment]
Yeah, I was only using `fsPath` here for trying to debug. Does `toString()` normalise the drive letter? My first thought was that it's because I may have uppercase drive letters being sent from the diagnostics provider, but that wouldn't explain why it went away when I waited till after my analysis. I'll dig a little more..

**Comment by DanTup** [comment]
Ok, I don't think it's related to the drive letter casing; I guess `toString()` must be handling this, as the output of this:

```ts
const allErrors = vs.languages.getDiagnostics();
const errors1 = allErrors.filter((e) => e[0].fsPath === "m:\\Coding\\Applications\\Dart-Code\\test\\test_projects\\hello_world\\lib\\empty.dart");
const errors2 = vs.languages.getDiagnostics(vs.Uri.file("m:\\Coding\\Applications\\Dart-Code\\test\\test_projects\\hello_world\\lib\\empty.dart"));
const errors3 = vs.languages.getDiagnostics(vs.Uri.file("M:\\Coding\\Applications\\Dart-Code\\test\\test_projects\\hello_world\\lib\\empty.dart"));
```

is:

```text
1
0
0
```

**Comment by DanTup** [comment]
Ok, this is (unsurprisingly) user error! :)

The return types of `getDiagnostics` with and without a `Uri` are not the same. When calling for all, I'm getting back an array of tuples and was counting the length of them, but comparing them against the count of errors. If I add `[0][1]` to the end of the `errors1` line the results are consistent!
