### ISSUE TITLE
Opens Website on every startup

### ISSUE THREAD

**Issue by chwzr** [Microsoft/vscode#48370]
VS Code opens the VSCode website every time I start VS Code. ( I know it should only open on first startup after install)

- VSCode Version:1.21
- OS Version: High Sierra 10.13.3

Steps to Reproduce:

1. Install VSCode on OSx
2. Open it. Then Close it and reopen.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
