### ISSUE TITLE
Color file types in Explorer

### ISSUE THREAD

**Issue by devnullnor** [Microsoft/vscode#4837]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce: Explorer bar

When finding files in the Explorer, my eyes have trouble focusing. File types like .js, .html, and .css could be colored to easier distinguish them from one another.

**Comment by Anjmao** [comment]
+1. Where is like 10 bugs(feature requests) to add file type icons to easer find different files :)

**Comment by Tyriar** [comment]
I don't think we would color files based on the file type, we are however looking at including git status to color files https://github.com/Microsoft/vscode/issues/178 and adding file type icons https://github.com/Microsoft/vscode/issues/211

**Comment by Tyriar** [comment]
There's an extension API request to change color and opacity of files in the explorer too https://github.com/Microsoft/vscode/issues/1394

**Comment by devnullnor** [comment]
Thank you. Consider this case is solved/closed.
