### ISSUE TITLE
Add an additional DiagnosticSeverity below information

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#48376]
We used to have 4 levels of diagnostic in the problems pane:

- Error
- Warning
- Information
- Hint

Information and Hint appeared the same, but were sorted. We used this to seperate some things like lints (`Information`) and TODOs (`Hint`). In a recent Code change, Hints were removed from the Diagnostics window (they're rendered as a grey "..." in the editor) which means TODOs all disappeared.

While we can put them back as `Information`, it will re-introduce the issue that lints aren't weighted above TODOs.

Is it possible to have another level of severity (maybe `Comment` would fit with TODOs, HACKs etc.) or the ability to custom sort these?

**Comment by jrieken** [comment]
Most use warning for lint messages. Why isn't that an option for you?

**Comment by DanTup** [comment]
Hmm, maybe it is, they come back as `INFO` from our server, so we just mapped them directly onto Code's severities. I'll see if I can get some opinions on this (I'm not writing enough Dart myself to have a great grasp on the sorts of things in warnings and lints).
