### ISSUE TITLE
How to close all of the code snippets

### ISSUE THREAD

**Issue by lzxb** [Microsoft/vscode#48382]
Code snippets cause me to often output errors

![image](https://user-images.githubusercontent.com/8424643/39119185-d0761ece-471d-11e8-876e-cb6f3eeb985e.png)

**Comment by jrieken** [comment]
Do you mean the `"editor.snippetSuggestions": "none"`-setting?

**Comment by lzxb** [comment]
My setting
```json
{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "vscode-icons",
    "window.zoomLevel": 1,
    "editor.lightbulb.enabled": false,
    "editor.snippetSuggestions": "none"
}
```

I expect to be able to close all the hints of code fragments to reduce error.

**Comment by jrieken** [comment]
> to close all the hints of code fragments to reduce error.

Not sure what this means? Do not want to see the `config`-entries? Do you not want auto-complete at all? The entries seems to come from an extension, please try without extensions or disable the extension that adds those entries

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/39123182-a5aab5a4-4729-11e8-91e3-3a53f4c0ec00.png)

I did not install these extensions, nor did I know where it came from.

**Comment by jrieken** [comment]
Please try this

<img width="660" alt="screen shot 2018-04-23 at 13 51 49" src="https://user-images.githubusercontent.com/1794099/39124921-7d782c5a-46fd-11e8-9bac-e44fa5ebfc51.png">

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/39127140-bbca8e4c-4736-11e8-851c-17645f18b9c2.png)
![image](https://user-images.githubusercontent.com/8424643/39127156-c352641e-4736-11e8-8a27-de24747ea678.png)


Still exist

**Comment by jrieken** [comment]
@mjbvz might be JS...

**Comment by lzxb** [comment]
`JS` file

**Comment by mjbvz** [comment]
Please answer the other questions
