### ISSUE TITLE
$TMPDIR is defined incorrectly in the terminal in mac serina

### ISSUE THREAD

**Issue by ThomasHickman** [Microsoft/vscode#48380]
Issue Type: <b>Bug</b>

In the vscode terminal:
```
$ ls $TMPDIR
ls: /private/private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/: No such file or directory
```
In an external terminal:
```
$ ls $TMPDIR | wc -l
    2655
```

I've also checked that `$TMPDIR` isn't being incorrectly set to my vscode instance by executing this in the devtools console:
```
> var cp = require("child_process")
undefined
> cp.execSync("echo $TMPDIR").toString()
"/private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/
"
```

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv|/Users/th10/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
What's the problem here? That's the usual macOS temp dir format.

**Comment by ThomasHickman** [comment]
@joaomoreno In a vanilla Mac os Terminal (bash):
```bash
[th10@mib108970i ~]$ echo $TMPDIR
/private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/
```

In the vscode terminal window: 
```bash
[th10@mib108970i /]$ echo $TMPDIR
/private/private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/
```

I don't see why these two should differ, but they do.

**Comment by ThomasHickman** [comment]
I get the same result when I click on the code icon in the dock to launching it from the terminal

**Comment by ThomasHickman** [comment]
I also tried running a task to output the `TMPDIR` and I still get the same result:
tasks.json:
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo $TMPDIR",
            "type": "shell",
            "command": "echo $TMPDIR"
        }
    ]
}
```

Output:
```
> Executing task: echo $TMPDIR <

/private/private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/

Terminal will be reused by tasks, press any key to close it.
```

**Comment by joaomoreno** [comment]
Can you show me the output of `ps ewwax | grep "Visual Studio"`?

**Comment by ThomasHickman** [comment]
I executed this and one bit of the output was something like `/bin/bash -l TMPDIR=/private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/ ...` - I therefore looked in `~/.profile` and `export TMPDIR="/private${TMPDIR}"` was in there. I removed this line and things worked properly - it looks like my ~/.profile was being run twice or the result of TMPDIR in the environment of the ~/.profile script was being persisted into the other login shell
