### ISSUE TITLE
can't run the angular 4 while saving 

### ISSUE THREAD

**Issue by haridassvenkatesh** [Microsoft/vscode#48388]
Issue Type: <b>Bug</b>

Now i can't run the angular while saving envery time using ''ng serve' cmd

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 1176)|
|Load (avg)|5, 2, 1|
|Memory (System)|7.70GB (5.00GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.37
html-css-class-completion|Zig|1.17.1
project-manager|ale|0.25.0
tslint|eg2|1.0.28
php-intellisense|fel|2.3.1
vscode-gitbuild|grz|1.0.1
Angular2|joh|2.16.1
vscode-gitignore-generator|pio|1.0.1
vscode-icons|rob|7.22.0
git-merger|sha|0.4.1
vscode-open-in-github|ziy|1.3.1

</details>

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
