### ISSUE TITLE
Document highlights with seemingly random failures

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#48386]
no step, but video proof... happens when clicking around and when relying on document highlights (I usually look onto the scrollbar for over usages). it seems that some symbols (for which TS knows more, see hover) simply fails to compute a hover...

![apr-23-2018 12-19-26](https://user-images.githubusercontent.com/1794099/39121032-a837e960-46f0-11e8-9076-3189033cf4b8.gif)

**Comment by mjbvz** [comment]
Let me know if you are still seeing this on TS 3.0
