### ISSUE TITLE
VS Code does not treat typescript dot files like normal typescript files

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/vscode#48385]
- VSCode Version: 1.22.2
- OS Version: Arch Linux

### Steps to Reproduce

1. Create `tsconfig.json`

```json
{
  "compilerOptions": {
     "target": "es2017",
     "module": "commonjs",
     "lib": ["es2017"]
  }
}
```

2. Create 2 files: `.dotfile.ts` (begin with a dot) and `normalfile.ts`

```typescript
Object.entries({})
```

### Expected behavior

There should be no problem

### Actual behavior

In `.dotfile.ts`, linter marks `entries` word with message `[ts] Property 'entries' does not exist on type 'ObjectConstructor'`.

Things are okay in `normalfile.ts`

### Screenshot

![screenshot from 2018-04-23 22-39-18](https://user-images.githubusercontent.com/11488886/39137305-76f66f0a-4747-11e8-926e-6a0a801cf71f.png)

**Comment by mjbvz** [comment]
Yes this is by-design. In most cases you do not want dot files included in a project. 

To explicitly include dot files, try setting:

```json
{
    "compilerOptions": {
        "target": "es2017",
        "module": "commonjs",
        "lib": [
            "es2017"
        ]
    },
    "exclude": [
        "node_modules"

    ],
    "include": [
        "**/*.ts",
        "**/.*.ts"
    ]
}
```

**Comment by KSXGitHub** [comment]
@mjbvz Still, there's inconsistency: `tsc` cli treats them differently (allowing them). I wouldn't complain if its behavior was consistent. My point is VS Code should only tell user what `tsc` cli would tell.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23750
