### ISSUE TITLE
Debugging express prototype/constructor variables infinitely nested

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4839]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Node.js Express application (I'm using https://github.com/heroku/node-js-sample)
2. Set a breakpoint inside index.js at line 4 (app.set('port', ...)
3. Start debugging 
4. Expand express: function createApplication() {...}
5. Expand Application: Object
6. Expand checkout: function (path){...}
7. Expand prototype: Object
8. Repeat steps 6 and 7

Actual:
Can expand these 2 indefinitely

**Comment by weinand** [comment]
I cannot reproduce this in the latest.
