### ISSUE TITLE
Suggestion: close terminal if task succesfully run and same task is executed again

### ISSUE THREAD

**Issue by biboc** [Microsoft/vscode#48397]
It is a suggestion for a new "feature"

Run Task A, terminal opens and task runs successfully. Terminal is still opened with result of the task.
Run Task A again, could you close first terminal? Can we currently do this? I'm launching test again and again and I must press a key to close the terminal otherwise I would have 20 terminals opened.

**Comment by Tyriar** [comment]
@biboc the terminal should be getting reused when you trigger the same task?

**Comment by biboc** [comment]
It is what I would like, but instead, a new terminal is opened
I'm on Ubuntu 16.04

**Comment by biboc** [comment]
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by dbaeumer** [comment]
How does the task look like. You can control this using the `presentation.panel` property. Set it to `shared` or `dedicated` and the terminal should be reused. Is the task configured that way ?

**Comment by biboc** [comment]
`presentation.panel`: "shared" works great 
Thanks
