### ISSUE TITLE
Smoketest: Terminal suite fails

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48396]
https://monacotools.visualstudio.com/Monaco/_build/index?context=allDefinitions&path=%5C&definitionId=106&_a=history

```
2018-04-23T11:09:19.8955860Z   1) Test Terminal opens terminal, runs 'echo' and verifies the output:
2018-04-23T11:09:19.8981810Z      Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by jrieken** [comment]
@Tyriar FYI i have disabled the terminal smoke test to get a green build: https://github.com/Microsoft/vscode/commit/21700be50716bd230c161dbb6adc7f69a9f5e51f

**Comment by Tyriar** [comment]
This actually caught a pretty nasty bug early, terminal layout/dimensions are quite broken. Luckily it only affects the dev build, not sure why just yet. Investigating...

**Comment by joaomoreno** [comment]
@Tyriar Yup it seems to be failing there. Btw, you can use `--verbose` when running `yarn smoketest`, it will print the raw commands send to Code. In this case, it will repeatedly show the `paste` command and not succeeding:

```
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
** paste div[id="workbench.panel.terminal"] .terminal-wrapper textarea.xterm-helper-textarea echo 1525255432400
```

I've also just pushed a change which will also make `--verbose` open the dev tools of any open workbench window, so we can `console.log` from the renderer and see the output, while the smoke test runs. 👍 

Anyway, the issue is that `new DataTransfer()` doesn't work anymore... hummm... my bad!

https://github.com/Microsoft/vscode/blob/2d15717a661e48e1c98b993e6a0c7b8df3a85d39/src/vs/platform/driver/electron-browser/driver.ts#L117

![image](https://user-images.githubusercontent.com/22350/39517726-00af0d14-4e01-11e8-8bc4-f56a700c7705.png)

I've replaced that with using XTerm's `send()` API. @Tyriar does the change make sense?

**Comment by Tyriar** [comment]
@joaomoreno yeah that works :+1:, thanks for fixing this :smiley:
