### ISSUE TITLE
No hover values for long watch variables

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4840]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Start debugging
2. Find a heavily nested variable to add to watch and/or slide the debug bar to the left so it is very thin.

Actual:
Hovering over watched variables does not display their value. If there is a heavily nested variable, even expanding the debug section to the right as far as it goes still displays ... and there is no way to see the value.

**Comment by isidorn** [comment]
Can you please include a screen-shot of what you are seeing. 
What behavior are you expecting to see?

**Comment by vsccarl** [comment]
@isidorn If you hover over the long variable:
![debughover](https://cloud.githubusercontent.com/assets/12900364/14259694/e3342a34-fa5c-11e5-8db9-040c927406f4.JPG)
I would expect the value to be displayed like this: 
![debughoverpreview](https://cloud.githubusercontent.com/assets/12900364/14259711/ffa36022-fa5c-11e5-9fbb-1e7c78bfa016.JPG)

When there are heavily nested variables, there is no way to see the value dependent on screen size.
