### ISSUE TITLE
The "Local image" preview fails to render on Windows when both files are in the same directory on:  a \\ based network share; the root of a drive

### ISSUE THREAD

**Issue by jpluimers** [microsoft/vscode#48403]
- VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
- OS version: Windows_NT x64 10.0.16299

I tried:

- searching through the existing open issues but could not find a matching one
- specifying the issue below as specific as I could

# Image preview test

Steps to reproduce:

1. Download <https://via.placeholder.com/350x150.png> to a local directory
2. Save this text in the same directory as `test.md` (see permutations below)
3. Open `test.md` in Visual Studio Code 1.22 or higher (tested on Windows 10 Pro x64 or Mac High Sierra)
4. Enable the markdown preview window

The "Local image" preview fails to render on Windows when both files are in the same directory on:

- a  `\\` based network share
- the root of a drive

The "Local image" preview succeeds on Windows when the files are on a regular drive letter in a subdirectory (even when the drive is pointing to a network share).

The "URL image" preview always succeeds (when there is an active internet connection)

## URL image

![URL image](https://via.placeholder.com/350x150.png)

## Local image

![Local image](350x150.png)

The "Local image" fails when the files are stored at:

- `\\tsclient\tmp`
- `\\tsclient\tmp\directory`
- `\\localhost\c$\ProgramData\Temp`
- `T:\`  after a `net use T: \\tsclient\tmp`
- `C:\`
- a Mac

The "Local image" succeeds when the files are stored at:

- `C:\ProgramData\Temp`
- `X:\ProgramData\Temp` after a `net use X: \\localhost\C$`
- `T:\directory`  after a `net use T: \\tsclient\tmp`

Preview of failure

> 
![screenshot 2018-04-23 15 16 36](https://user-images.githubusercontent.com/2033367/39129398-b0082410-470a-11e8-95c1-6030acbd4854.png)

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (2 x 2300)|
|Memory (System)|8.00GB (4.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.14.1
markdown-all-in-one|yzh|1.2.0

</details>

**Comment by lmcarreiro** [comment]
In both cases, it doesn't show you the link to open in the "Recent" list from the Welcome tab:

![image](https://user-images.githubusercontent.com/13019179/58384910-513dda80-7fbf-11e9-9fbc-f67d3a9a7ea0.png)

**Comment by mjbvz** [comment]
Still needs a fix from #74332

**Comment by mjbvz** [comment]
@jpluimers Please test in the next insiders builds and let me know if there are any cases that do not work

**Comment by gregvanl** [comment]
Still cases when \\machine\share breaks the preview. Mostly when opening the folder for the first time by typing in '\\machine\share' from the Open Folder dialog. It will often work when reopening the share from the File > Open Recent.

DevTools shows:
workbench.main.js:2803 Webview: Cannot load resource outside of protocol root
(anonymous) @ workbench.main.js:2803
r @ workbench.main.js:35
Promise.then (async)
l @ workbench.main.js:35
(anonymous) @ workbench.main.js:35
n @ workbench.main.js:35
e.session.protocol.registerBufferProtocol @ workbench.main.js:2803
apply @ C:\Users\gregvanl\AppData\Local\Programs\Microsoft VS Code Insiders\resources\electron.asar\renderer\callbacks-registry.js:47
handleMessage @ C:\Users\gregvanl\AppData\Local\Programs\Microsoft VS Code Insiders\resources\electron.asar\renderer\api\remote.js:285
ipcRenderer.on.args @ C:\Users\gregvanl\AppData\Local\Programs\Microsoft VS Code Insiders\resources\electron.asar\renderer\api\remote.js:275
emit @ events.js:182

**Comment by mjbvz** [comment]
Closing this due to lack of further user interest over the last two years
