### ISSUE TITLE
Input focus stuck on autocomplete suggestion popup

### ISSUE THREAD

**Issue by dstpierre** [Microsoft/vscode#48405]
Issue Type: <b>Bug</b>

This behavior is new since last update.

Steps to reproduce:

1. In a `.go` file, for example a test

```go
func TestSomething(t *testing.T) {
}
```
2. When typing (t *testing.T|)  | represent the input cursor.

3. The autocomplete suggestion capture the input focus and doing End, Home or arrow left, right does not work anymore.

Before the update I was not stock inside the autocomplete popup and navigational keyboard was working.

Now I need to do ENTER or ESC for example to close the popup and regain control of navigation keys.

Is there any settings I can turn this new behavior off?

Thanks

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.16.3-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 2299)|
|Load (avg)|0, 0, 0|
|Memory (System)|15.60GB (4.66GB free)|
|Process Argv|/opt/visual-studio-code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
reasonml|fre|1.0.34
Go|luk|0.6.78
python|ms-|2018.3.1
azure-account|ms-|0.4.0
cpptools|ms-|0.16.1
vscode-code-outline|pat|0.1.0
elm|sbr|0.16.0

</details>

**Comment by inosik** [comment]
> The autocomplete suggestion capture the input focus and doing End, Home or arrow left, right does not work anymore.

Sounds like #43511, although that didn't change the behavior of arrow-left and arrow-right for me.

**Comment by inosik** [comment]
I updated to 1.22.2 yesterday and noticed this new behavior after 2 minutes. As pointed out in https://github.com/Microsoft/vscode/issues/43511#issuecomment-376104914, you can restore the "old" behavior by adding this to your `keybindings.json`:

``` json
{
	"key": "home",
	"command": "-selectFirstSuggestion"
},
{
	"key": "end",
	"command": "-selectLastSuggestion"
}
```
