### ISSUE TITLE
TypeScript: everytime I complete a suggestion an error shows up in the console

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48414]
![flicker_chrome58](https://user-images.githubusercontent.com/900690/39132613-89b6205c-4712-11e8-8efe-c21462bafbd7.gif)

/cc @jrieken @ramya-rao-a

**Comment by ramya-rao-a** [comment]
From the gif, it doesnt look like the error is showing up for completing suggestion.
It shows up after you type `()` when calling a method.

And so is the same as #46852
