### ISSUE TITLE
Syntax color fail with "target:event" for angular2

### ISSUE THREAD

**Issue by ericmartinezr** [Microsoft/vscode#4841]
- VSCode Version: 0.10.11
- OS Version: Windows 7

Steps to Reproduce:

1. Set up an angular2 project 
2. Write `@HostListener('document:keydown', ['$event'])`

That syntax is valid for angular2, but the color fails as shown in the following image

![image](https://cloud.githubusercontent.com/assets/13039652/14194430/e7e7220a-f784-11e5-8036-81ed392983c5.png)

**Comment by ericmartinezr** [comment]
For what it worth I'll add some more screen shots

Having HostListener inside a class
![image](https://cloud.githubusercontent.com/assets/13039652/14398594/b85774b2-fdbb-11e5-8df3-426ed42615a4.png)

Having HostListener ouside the class
![image](https://cloud.githubusercontent.com/assets/13039652/14398603/c9544dc6-fdbb-11e5-91d6-21a596aa6335.png)
*Ignore the red line*

Removing the `:` inside the class
![image](https://cloud.githubusercontent.com/assets/13039652/14398618/e84a0a18-fdbb-11e5-9fa4-00503d14899a.png)
*No good nor bad coloring*

So I think this may be a mix of having `:` inside of `{ }` ?

**Comment by aeschli** [comment]
I tried the following example:
```typescript
import {Component, HostListener, Directive} from 'angular2/core';

@Directive({selector: 'button[counting]'})
class CountClicks {
  numberOfClicks = 0;
  @HostListener('click', ['$event.target']) onClick(btn) {
    console.log("button", btn, "number of clicks:", this.numberOfClicks++);
  }
}
@Component({
  selector: 'my-app',
  template: `<button counting>Increment</button>`,
  directives: [CountClicks]
})
export class AppComponent {
  constructor() { console.clear(); }
}
```

I get more colors than in the screenshots above, but things seem out of order. E.g. string don't get the 'string' scope.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#143
