### ISSUE TITLE
Keyword search

### ISSUE THREAD

**Issue by cossio** [Microsoft/vscode#48417]
If I search for the string "hello world" in the Search box (Ctrl + Shift + F), it only finds occurrences where "hello" is followed by "world". It doesn't find files where the words "hello" and "world" occur non-consecutively. 

I know it is possible to do regexp, but that's horrible to type everytime I want to do this.

There should be an easy way to do Keyword search, where it finds all the files containing all of the given words, but not necessarily consecutively.

**Comment by roblourens** [comment]
In my personal opinion, this isn't what I would expect from text search in a text editor. It isn't a good match for the tools that we currently use to implement search. But, at some point we will have extension API to allow implementing search differently, and then someone can implement like this if they want to.
