### ISSUE TITLE
Change/add Emmet suggestion for <form>

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#48416]
Issue Type: <b>Feature Request</b>

Emmet completes `form` as `form action=""`.  In this day and age, using Angular and other frameworks I almost never need an `action` and I always need to delete it.

Can this  be removed from the default suggestion?  Or, at least, have it pre-selected for easy deletion, as in `${1:action="$2"}`?

VS Code version: Code - Insiders 1.23.0-insider (c1cd4378c5e5dc434ed959e13556d05240a8ca18, 2018-04-20T05:10:42.823Z)
OS version: Darwin x64 17.5.0

**Comment by ramya-rao-a** [comment]
@smlombardi Please log this issue at https://github.com/emmetio/snippets. You can also send a PR for your suggested fix. The file to change would be https://github.com/emmetio/snippets/blob/master/html.json#L57

A workaround is to create your own [custom snippet](https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets) for `form` such that it overrides the default one

**Comment by smlombardi** [comment]
@ramya-rao-a  Thanks.  That repo has no "issues" tab...

Also, I created a `snippets.json` in my home folder and added ` "emmet.extensionsPath": "~/snippets.json"` to my user settings, but VSCode complains "no such directory" when I try to use Emmet.

Mu snippets.json so far is 
```
{
  "html": {
    "snippets": {
      "form": "<form${1:[action=${2}]}></form>"
    }
  }
}
```

**Comment by ramya-rao-a** [comment]
Try https://github.com/emmetio/expand-abbreviation/issues for logging the issue

`emmet.extensionsPath` should point to the directory where the snippets.json file resides not the file itself.
