### ISSUE TITLE
Test installing bundled language packs

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#48413]
Refs: https://github.com/Microsoft/vscode/issues/45663

- [x] anyOS @sbatten 
- [x] anyOS @joaomoreno 

Complexity: 3

Authors: @dbaeumer, @sandy081

To verify:

- Start VS Code in bundled German language: `code-insiders --locale de`
- Make sure that you get a warning prompt to install German Language Pack extension
- Install it and **Restart** (reload is not enough!)
- Make sure that warning is not shown again
- check that the LP extension for German is used by doing the following:
  - got to the App Data directory. Under Windows this is for me `C:\Users\dirkb\AppData\Roaming\Code - Insiders`
  - Ensure that there is a clp directory
  - open `languagepacks.json` file and ensure that there is a `'de'` entry in the top level object literal.
  - cd into clp
  - ensure that there is a directory entry ending in `.de`
  - ensure that the directory is fille with data. 
- Install an unbundled language pack from Market place, for example Portugese (Brazil)
- Restart VS Code in Portugese language
- Make sure no warning is shown

**Comment by sandy081** [comment]
@dbaeumer Added a TPI for Bundled Language Packs item. Feel free to add to it or have a separate one for yours.

**Comment by dbaeumer** [comment]
@sandy081 thanks. Added mine here.
