### ISSUE TITLE
Test: Custom SCM views

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48429]
Test for #45686: 

- [x] windows: @tsalinger 
- [x] macOS: @sandy081 
- [x] linux: @ramya-rao-a 

Complexity: 4

Authors: @joaomoreno

---

There's a new view location `scm`:

- As an extension developer, you can:
  - Contribute views to the SCM viewlet
  - Control view visibility using `when` contexts
- As a user, you can:
  - Resize the views
  - Hide the views with context menu actions both in the views titles as well as the viewlet title area
  - Reorder contributed views
  - Still have multiple repositories selected as well as multiple contributed views visible simultaneously

**Comment by eamodio** [comment]
@joaomoreno I quickly tried this out with a quick and dirty version for GitLens, and at least on Windows everything looks good to me. Although I will note that I can't reorder the main Git view, nor can I hide it --  though I'm guessing that is on purpose.

**Comment by joaomoreno** [comment]
@eamodio Thanks for testing! I've only enabled reordering among contributed views. Things would get overly complicated otherwise. But this isn't the last iteration for sure, let's see as we go along.

**Comment by eamodio** [comment]
Makes perfect sense, I just wanted to mention it in case it was on purpose :)
