### ISSUE TITLE
.vue扩展名中的scss没有了语法提示，编辑器有红色的波浪线

### ISSUE THREAD

**Issue by liliangabc** [Microsoft/vscode#48424]
Issue Type: <b>Bug</b>

不知道什么时候，vue扩展名中的scss没有了语法提示，VS code当成css识别了，希望尽快解决

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.16299

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
tornado|abd|0.0.1
vscode-css-formatter|aes|1.0.1
solargraph|cas|0.16.0
dart-code|Dar|2.11.2
githistory|don|0.4.0
code-runner|for|0.9.3
python|ms-|2018.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
vetur|oct|0.11.7
Ruby|reb|0.18.0
vscode-icons|rob|7.22.0
nativescript|Tel|0.7.3
nativescript-xml-snippets|tsv|1.0.6
vscode-react-native|vsm|0.6.9

(6 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Please report issues in english.

**Comment by liliangabc** [comment]
Reinstalled VS code normal, thank you
