### ISSUE TITLE
Language Pack Icon

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#48425]
Can we get an icon for language packs?

![image](https://user-images.githubusercontent.com/1487073/39136157-6fa41810-46cf-11e8-8e78-43f99d06ee39.png)

**Comment by misolori** [comment]
FYI @chryw. I'll work with you to get this new icon in the queue.

**Comment by misolori** [comment]
This is already updated on the marketplace, attaching here for reference.

**Icon**
![image](https://user-images.githubusercontent.com/35271042/39787198-06e00f12-52d9-11e8-954a-828cd8d782ca.png)


**Gallery view**
![image](https://user-images.githubusercontent.com/35271042/39787161-ce38ce06-52d8-11e8-967c-755c1cef453f.png)

**Extension page**
![image](https://user-images.githubusercontent.com/35271042/39787168-d93fdf1a-52d8-11e8-9769-76989c292d2b.png)


[Market_LanguagePack_128x.zip](https://github.com/Microsoft/vscode/files/1985871/Market_LanguagePack_128x.zip)
