### ISSUE TITLE
Allow to disable drag and drop in the files explorer

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#4842]
It would be interesting to be able to disable the _drag and drop_ operations in the TreeView, mostly to avoid _mistakes_ :disappointed: 

Another option it would be to make the _Undo/Redo_ operations to work for the TreeView operations.

Thanks in advance

**Comment by SneWs** [comment]
I have to second this. It's super annoying that all of a sudden you've managed to move a folder into another folder. Had you been able to Undo it would not have been such a PITA, but there is no such option currently. 

I mainly have this issue when working in a Linux box where the trackpad is a bit finicky and all of a sudden it registers a touch while dragging and voila, you have moved something to some place where it's not supposed to be.

**Comment by joaomoreno** [comment]
Undo would be awesome, but likely hard to achieve.

We can add a setting to disable dnd, what do you think @bpasero?

**Comment by bpasero** [comment]
@joaomoreno I will introduce a delay of 500 ms before you can actually drop within the tree. That should fix these issues of accidental drop.

**Comment by joaomoreno** [comment]
I think that will fix accidental dragging... not so sure about accidental dropping. 😕

**Comment by bpasero** [comment]
@joaomoreno hm, my understanding is that people are frustrated when suddenly they DND a folder in the explorer from one location to another. I do not think people want to disable being able to drop from outside the explorer into the explorer (e.g. from desktop to import the file). 

Also, if the problem is about dropping to the wrong location, disabling DND is not an option. For that we need the confirmation dialog (https://github.com/Microsoft/vscode/issues/1414). I am not sure we can solve all the issues with one fix.

**Comment by bpasero** [comment]
Given all the user frustration, I pushed a change to introduce `explorer.enableDragAndDrop` until we have figured out a better solution (https://github.com/Microsoft/vscode/issues/6486 and https://github.com/Microsoft/vscode/issues/1414)

**Comment by Tyriar** [comment]
Drag and drop doesn't work, you can still drag items though which I'm assuming was intentional since this is a temporary fix.

**Comment by bpasero** [comment]
@Tyriar that is right, I am not turning off DND in the tree. Maybe I can look into that.

**Comment by gordonbisnor** [comment]
This happens to me constantly.The ability to drag and drop folders is great, but it happens inadvertently and seemingly without adequate visual cues during or notification afterward.
