### ISSUE TITLE
Implement FileSystemProvider

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#48421]
Refs: #47475

- [ ] macOS @bpasero 

Complexity: 4

This items is about implementing a *real* file system provider such that we can validate our file system provider API and find gaps. The outcome should be a prototype of a `file`-FileSystemProvider, e.g.  move the logic from the [`FileService`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/electron-browser/fileService.ts#L79) into a FileSystemProvider and see what's not possible, e.g permissions.

**Comment by bpasero** [comment]
I moved the result of my file system provider to https://github.com/Microsoft/vscode-extension-samples/tree/master/nodefs-provider-sample
