### ISSUE TITLE
Extensions recommendations list is not displaying Cordova extension when opening Cordova project.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4843]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Create Cordova project structure using Yeoman. (Project Type Windows 8 mobile app)
2. Launch VS code and open root directory of Cordova project.
3. Click on extension info icon from the status bar.
4. Select options for Extension recommendations and verify list.

Actual: Not getting option for Cordova extension.
Expected: It should identify project type and display recommendations list accordingly.

![image](https://cloud.githubusercontent.com/assets/17735796/14194631/653b70aa-f765-11e5-8503-30256adddd17.png)

**Comment by egamma** [comment]
The list of recommendataions is a curated list and cordova is not on this list, so this works as designed.
