### ISSUE TITLE
Test: New Integrated Terminal Proposed APIs

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#48434]
#13267 & #46192

- [x] Windows:  @rebornix 
- [x] macOS: @bpasero 

Complexity: 3

Authors: @Tyriar

The terminal has the following new APIs:

```ts
declare module 'vscode' {

	export namespace window {
		/**
		 * The currently active terminals or an empty array.
		 *
		 * @readonly
		 */
		export let terminals: Terminal[];

		/**
		 * An [event](#Event) which fires when a terminal has been created, either through the
		 * [createTerminal](#window.createTerminal) API or commands.
		 */
		export const onDidOpenTerminal: Event<Terminal>;
	}

	export interface Terminal {
		onData: Event<string>;
	}
}
```

Please test them out to ensure they're working as expected. https://github.com/Microsoft/vscode-extension-samples/tree/master/terminal-sample has some usage examples.

**Comment by johnbendi** [comment]
@Tyriar is the a `getActiveTerminal` api?

**Comment by Tyriar** [comment]
@johnbendi active here is used differently to elsewhere, I'll change the wording. There is no way to get the currently active terminal right now, there's no issue tracking this either to my knowledge.
