### ISSUE TITLE
VSCode Intellisense + Extensions stops working after some time

### ISSUE THREAD

**Issue by nobobo1234** [Microsoft/vscode#48436]
- VSCode Version: 1.22.2
- OS Version: Microsoft Windows 10 Pro V10.0.16299.371

So when I start to work in my React project in Vscode after a certain amount of time I noticed that my Intellisense stopped working and some of my extensions, such as Prettier. This happens to my everytime lately. Even disabling extensions won't work. A fix for this is to restart the code editor but that gets irritating after some time. I also tried to reinstall it, but that didn't work. I wouldn't really know how to reproduce it but my workflow is

1. Start up Git Bash and run ``yarn start``
2. Right click in folder and click `Open with Code`
3. Work on my react project for a while
4. After a certain amount of time Vscode extensions + intellisense stopped working

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by elowes** [comment]
me too

**Comment by mjbvz** [comment]
@nobobo1234  Do you see this issue in [VS Code insiders](https://code.visualstudio.com/insiders/)? How about if you upgrade to `typescript@next` in your workspace by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by nobobo1234** [comment]
I haven't tried to code in the insiders edition. And I don't use typescript react, I use es6 react.

**Comment by mjbvz** [comment]
Please try in insiders. And TypeScript powers both js and TS intellisense so upgrading to `typescript@next` does apply to js as well

**Comment by nobobo1234** [comment]
Okay i'll try

**Comment by TurtleGamingFTW** [comment]
I think I have found something with this. I was going to change my typescript version to a newer one and found that `typescript.tsdk` was placed as null. Btw, I am using insiders

**Comment by Rafael955** [comment]
Same here, VSCode version is 1.23.1, Windows 7, it works at the beginning but soon it simply stops for no reason.

**Comment by mjbvz** [comment]
Closing since OP has not reported back
