### ISSUE TITLE
File not found in search

### ISSUE THREAD

**Issue by pankleks** [Microsoft/vscode#48439]
When pressing Ctrl + P (go to file), it looks like VS code does not include in search folders excluded in `.gitignore`

VS code: 1.22.2

**Comment by roblourens** [comment]
That's by design, but you can disable it with "`search.useIgnoreFiles": false` if you prefer

**Comment by pankleks** [comment]
thanks!

**Comment by leonkunert** [comment]
This irritates me immensely, the gitignore should be used for git relateted contexts and not for search in the editor. In the name of sane defaults change it to false per default.
