### ISSUE TITLE
[feature request] split integrated terminals

### ISSUE THREAD

**Issue by gioragutt** [Microsoft/vscode#48444]
As someone who uses terminals a lot, and uses a lot of them, I absolutely love the ability to split the terminal into 2 terminals (and more if possible).

The use cases are obvious - have multiple terminals, when each handles a different task.

f.e: when doing `angular`, one tab `ng serve`s, and another is used for generating components and etc.

**Comment by octref** [comment]
This has been available for a while: https://code.visualstudio.com/updates/v1_21#_split-terminals
![terminal-split](https://user-images.githubusercontent.com/4033249/39154646-da80016a-4703-11e8-986c-e1a36cdc050f.gif)

**Comment by gioragutt** [comment]
Wow! Had no idea. Thank you!
