### ISSUE TITLE
Allow for Custom New File Template

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#48449]
Posibility to create a user defined type file template. For example, create a Laravel Blade File Template So while creating a new file the user can choose New File Template->Blade and get boilerplate code automatically.

**feature-request**

**Comment by Sharpie360** [comment]
Also, the ability to have multiple templates for different file types, based on what technology is called for in the new project. For example, having html boilerplate templates that is Materlize.css ready or Bootstrap ready on load of said template.

**Comment by nealot** [comment]
Check out https://github.com/visualzoran/vz-file-templates
