### ISSUE TITLE
Why when I save my .go file all spaces converts to tabs? How to disable this?

### ISSUE THREAD

**Issue by artekha** [Microsoft/vscode#48445]
I like how go package formats my code after saving especially adding/removing packages when needed, but why it converts tabs to spaces and how to disable this?

![screencast 2018-04-24 00-35-17](https://user-images.githubusercontent.com/12628672/39154686-c9c39572-4757-11e8-99e8-47c1916b21e0.gif)

**Comment by ramya-rao-a** [comment]
On the bottom right of the editor, click on the "Spaces:2". In the options that come up, select "Indent using tabs" and try again
