### ISSUE TITLE
Editor indent size using 4 when it's set to 2

### ISSUE THREAD

**Issue by ssilverman** [Microsoft/vscode#48440]
Issue Type: <b>Bug</b>

The editor is now using an indent size of 4 even though editor.tabSize is set to 2.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (2.64GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.16.1
platformio-ide|pla|0.14.1
debug|web|0.22.0

</details>

**Comment by alexandrudima** [comment]
@ssilverman There are 3 settings that control editor indentation.

```js
  // When opening a file, `editor.tabSize` and `editor.insertSpaces` will be detected 
  // based on the file contents.
  "editor.detectIndentation": true,

  // Insert spaces when pressing Tab. This setting is overridden based on the file 
  // contents when `editor.detectIndentation` is on.
  "editor.insertSpaces": true,

  // The number of spaces a tab is equal to. This setting is overridden based on the 
  // file contents when `editor.detectIndentation` is on.
  "editor.tabSize": 4,
```

In other words, by default `editor.tabSize` means the fallback tab size, in case the file does not give sufficient clues regarding its indentation. If you wish to **always** use tab size 2, then you can use:
```
"editor.detectIndentation": false,
"editor.tabSize": 2
```
