### ISSUE TITLE
Allow split terminal to inherit working directory from previous terminal

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#48447]
Have an option to inherit previous session's directory, so when I'm splitting I always end up with two terminals of the same working directory. iTerm2 has this and is very useful:

![image](https://user-images.githubusercontent.com/4033249/39154758-360c3724-4704-11e8-8ccd-2c32f98fa2db.png)

**Comment by cedric05** [comment]
shall i work on it ?

**Comment by Tyriar** [comment]
@cedric05 I think this will need some ground work first to pull in the cwd in a nice way on all platforms which may be tricky.

**Comment by cedric05** [comment]
for windows there is no straight forward solution.
https://stackoverflow.com/a/25853120/5313475

**Comment by octref** [comment]
I would find this really useful, as previously split terminal command splits at least for the same workspace. However that was gone in favor of split (in active workspace) two versions ago, which I don't find much useful.

Example: Let's say I have two workspace A/B.

- Open new Terminal, select A
- Split in A
- Somehow the split panel is on B

@Tyriar Is that intended?

**Comment by Tyriar** [comment]
@octref the default split action now lets you select the workspace, just like the default create terminal action:

![image](https://user-images.githubusercontent.com/2193314/41868741-cd7d319c-786b-11e8-8d22-e26a799d78e6.png)

**Comment by octref** [comment]
@Tyriar I'm more looking at the Split in active workspace one, because I don't want to do the selection when splitting each time. Currently the active workspace seems to be determined by the current open file. I would expect it to be determined by the terminal from which I'm splitting.

e.g.: If I have a terminal open on node-pty, splitting from it should always give me a terminal at the root of node-pty, no matter which file I'm on.

**Comment by Tyriar** [comment]
@octref yeah that's what this feature request is about, right?

**Comment by octref** [comment]
@Tyriar Sorry, just found myself repeating myself unknowingly 😅

**Comment by Tyriar** [comment]
After chatting with @octref I found what would solve his problem is splitting taking the _`initialCwd`_ of the terminal being split. This is so when in a multi-root workspace it won't show the popup. I propose we add a setting of the form:

```js
terminal.integrated.splitCwd: 'choose' | 'initialCwd';
```

`choose` would be the current behavior, `initialCwd` would use the cwd of the terminal being split. Note that this is a string setting not a boolean to allow mac/linux to support the actual cwd in the future (doesn't appear to be possible without hacks on Windows). Also I didn't give the setting name/values much time, we can probably come up with better names.

**Comment by alexr00** [comment]
@Tyriar, just want to make sure I understand: `initialCwd` on Windows wouldn't do anything?

**Comment by Tyriar** [comment]
@alexr00 `initialCwd` on windows would use the `initialCwd` from the terminal being split:

https://github.com/Microsoft/vscode/blob/3ba326658d0dba29f238175fb79a6ddab08001af/src/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#L36

**Comment by Tyriar** [comment]
The follow up which we could do in October if you have time, would be to add a `cwd` option with the following behavior:

- Linux/macOS: Run `lsof -p <pid> | grep cwd` when a split happens to pull the cwd
- Windows: Fallback to initialCwd behavior (mention in setting doc)

**Comment by Tyriar** [comment]
@alexr00 I added a test plan item so we get better OS coverage for this one.
