### ISSUE TITLE
Getting multiple info pop-ups after installing Cordova extension and they are contradictory.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4844]
- VSCode Version:0.10.12-alpha
- OS Version:Windows10

Steps to Reproduce:
1. Create Cordova project structure using Yeoman (Proj type WIndows8 Mobile app).
2. Launch VS code and open proj root folder.
3. Click on extensions Icon from the status bar and select option for install extension.
4. Select Cordova extension and install it.
5. Verify extension should be installed successfully and user should get info pop-up to restart the window.

Actual: Getting two info pop-up as below and those are contradictory.
 
![image](https://cloud.githubusercontent.com/assets/17735796/14194766/c3f69bbe-f766-11e5-8de0-4dfe5a887446.png)

Expected: Only one pop-up as below:
![image](https://cloud.githubusercontent.com/assets/17735796/14194774/dabdc58e-f766-11e5-8bb1-96ec3a8239dc.png)

**Comment by alexandrudima** [comment]
Looks like the extension suggestion doesn't realize the extension was just installed.

**Comment by joaomoreno** [comment]
This happens because you clicked the `README` link. Not nice but expected. Consequence of #637
