### ISSUE TITLE
closing extension host window doesn't terminate debug session

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#48442]
Regression in VS Code Insiders:

- start extension host debugging
- close extension host window

Observe: debug session doesn't stop

This did worked in VS Code 1.22

**Comment by isidorn** [comment]
The issue here is that I am not getting the `exit` event from the adapter.
When I compare it to stable there I am getting the `exit` event nicely from the adapter.

Forwarding to @weinand and @roblourens so they first investigate on their side.

**Comment by weinand** [comment]
Most likely this is not an adapter issue but a problem of the refactored VS Code code.
I will investigate.

**Comment by weinand** [comment]
@isidorn No, this is a regression introduced through your fix for #43516.
I've reverted the fix via https://github.com/Microsoft/vscode/commit/bb77f586648e23b369168800acdf4693c152cc7f and re-openend #43516.
