### ISSUE TITLE
Enabling renderWhitespace and fontLigatures causes problems with some fonts

### ISSUE THREAD

**Issue by dinofx** [Microsoft/vscode#48446]
- VSCode Version: 1.22.2
- OS Version: 10.12

Steps to Reproduce:
1.  With:
	"editor.fontFamily": "Fira Code",
	"editor.fontLigatures": true,
	"editor.renderWhitespace": "all",
2. Notice that rendered tabs and spaces are half size and overlapping with neighboring characters.

Perhaps this is a bug in the Fira Code font, but VSC could either not use the user's fontFamily for rendered whitespace, or isolate the rendered whitespace characters in some way so that they don't have (kerning?) problems.

Does this issue occur when all extensions are disabled?: Yes

<img width="791" alt="screen shot 2018-04-23 at 5 37 02 pm" src="https://user-images.githubusercontent.com/7581987/39154684-1d3245ea-471d-11e8-9b31-8c9149146a22.png">
<img width="821" alt="screen shot 2018-04-23 at 5 36 54 pm" src="https://user-images.githubusercontent.com/7581987/39154685-1d3ee12e-471d-11e8-9860-d3c886be9e2e.png">

**Comment by alexandrudima** [comment]
@dinofx Is it possible that you have somehow installed a *broken* version of Fira Code ?

Fira Code works great for me:

![image](https://user-images.githubusercontent.com/5047891/39171041-ea4bd444-479d-11e8-81a5-844db53eb1c8.png)

**Comment by dinofx** [comment]
I downloaded FiraCode_1.205.zip.  Note that I was going to take a screenshot with larger font size, but the problem doesn't occur for font size > 12px.

**Comment by dinofx** [comment]
<img width="70" alt="screen shot 2018-04-24 at 12 05 48 pm" src="https://user-images.githubusercontent.com/7581987/39199598-dde830de-47b7-11e8-8077-f7b136dc9c74.png">

Even Hasklig isn't perfect.  I find its TAB character to be bigger than needed compared to the default, and it still overlaps the vertical bar.

BTW, I don't see TAB chars in your screenshot above.  And what's with these vertical lines?  I don't know that I need both vertical bars and right arrows at every TAB 😀

**Comment by alexandrudima** [comment]
@dinofx I cannot reproduce the things you have posted in your first screenshot, where the dots are misplaced. Can you?

---

Here are how things look for me with:
```
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.renderWhitespace": "all",
    "editor.fontSize": 11
```

![image](https://user-images.githubusercontent.com/5047891/39230258-2ab1c2dc-4866-11e8-93fc-5ca99c168164.png)

If you are annoyed by the tiny overlap between indent guides and whitespace characters that is due to the colors being transparent, you can edit the colors and remove the transparency. e.g.

```
    "workbench.colorCustomizations": {
        "editorWhitespace.foreground": "#444444",
        "editorIndentGuide.background": "#444444"
    }
```

![image](https://user-images.githubusercontent.com/5047891/39230339-76918e80-4866-11e8-86f8-7be6eb4a38cf.png)

If you don't like the vertical lines at all, you can turn them off with `"editor.renderIndentGuides": false`

**Comment by dinofx** [comment]
Notice in the original screenshot at "distance =" (and other places), the '=' overlaps the dot for the whitespace.  All SPACE chars and even tabs were appearing too small (since this is a monospace font).  I tried 11px, and could not reproduce.  Somehow after playing with this some more, 12px started working again.  If I can reproduce this again I'll update.
