### ISSUE TITLE
Auto-attach not working on macos

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#48452]
- Enable auto attach
- Start `node --inspect test.js` in terminal
- Nothing happens

Debugged awhile, DebugService.substituteVariables fails because `launch` is undefined, and the error is silently swallowed.

**Comment by isidorn** [comment]
Assigning firts to @weinand since he refactored the substitution. Feel free to assign back to me and I can investigate

**Comment by weinand** [comment]
related to #48423

**Comment by weinand** [comment]
@isidorn please create a debt item for Rob's suggestion.
