### ISSUE TITLE
vscode python can't  jump to some packet  function impleament of sklearn ,etc,  sklearn.model_selection.train_test_split. but pycharm could

### ISSUE THREAD

**Issue by ai-chen2050** [Microsoft/vscode#48459]
Issue Type: <b>Bug</b>

I hope that i could jump some function implement of sklearn freely

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 15.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3200)|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (2.07GB free)|
|Process Argv|/Users/duzhe/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.3
vscode-elm-jump|joe|0.0.1
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.3.1
vscode-yaml|red|0.0.11
vscode-icons|rob|7.22.0
vscode-jump|sha|0.0.2

</details>

**Comment by ai-chen2050** [comment]
it can go to the __init__.py of this packet Folders, but cannot from declare in __init__.py to function implement in other file in the same Folders.  

![image](https://user-images.githubusercontent.com/27693952/39164731-a812c23e-47b3-11e8-8521-5c309524e294.png)

but ,,, can't go to the function impleation in _split file, below as folows: (ps : this is my manul open _split file)

![image](https://user-images.githubusercontent.com/27693952/39164803-fa06e548-47b3-11e8-9ade-85689b412ebc.png)

**Comment by ai-chen2050** [comment]
@doudou @threeve @AArnott @kaiwood @tonyc

**Comment by ai-chen2050** [comment]
what's you meaning ? you mean exist extension could solve this issue ? what's that ?

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by ai-chen2050** [comment]
Thanks for your detailed explain, I have understanding your advices. Tks again ~ ~
