### ISSUE TITLE
Install task should be available by default in npm extension

### ISSUE THREAD

**Issue by nickmccurdy** [Microsoft/vscode#48456]
It appears that as of https://github.com/Microsoft/vscode/commit/1420d41bf817843796e7cddfaa2c0c111ac9f991#r28075777, VSCode no longer provides an `install` task by default in its npm extension, making setting up new projects less convenient when there is no install hook in `package.json` (which applies to most packages).

- VSCode Version: 1.22.2 and 1.23.0-insider
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Start a new project with a `package.json` file.
2. Add a test script.
3. Run `Tasks: Run Build Task`. Note that test is present, but install is not.
4. Add an install script.
5. Run `Tasks: Run Build Task`. Note that both install and test are present. VSCode now recognizes the built in install task because it thinks it's a custom script, when it's actually an npm install hook.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
Removed since a poll in the team gave that everybody is running install from the command line. 
However, adding install doesn´t hurt.

**Comment by nickmccurdy** [comment]
I just tried this out in Insiders and `task install` works great, thank you!
