### ISSUE TITLE
Provide file icons per file type

### ISSUE THREAD

**Issue by chrisxvin** [Microsoft/vscode#4845]
- VSCode Version: Feb. stable build (0.10.11)
- OS Version: Win 10 Pro

Steps to Reproduce:
1.  Install VSCode.
2.  See any code file in Explorer, icons are changed to vscode style, and cannot tell out C#/C++/H/etc...

Please add an option to choose whether to use VSCode file icon or not.

PS: This problem doesn't appears in insider build 0.10.13.

**Comment by joaomoreno** [comment]
Brad can we get custom icons for each file type?

**Comment by bgashler1** [comment]
@joaomoreno: Sure, we support numerous languages, though.  Do we have a list of file associations that are affected so I can design just for those?

**Comment by chrisxvin** [comment]
Well, I found again this problem on version 1.1.0-insider, build date 2016-5-9.
This time, C# file type associated with VSCode is set to "Visual Studio Code - Insiders", icons are all the same, :-(   Can't tell it is a C# code file.
Screenshot is here:
![image](https://cloud.githubusercontent.com/assets/628293/15201834/956cd36c-1827-11e6-851a-6f28d11c6e4d.png)

**Comment by joaomoreno** [comment]
Related to #7196

**Comment by joaomoreno** [comment]
@chrisxvin, #7196 just got closed, so in the next update those `Visual Studio Code - Insiders` labels will get much more specific (e.g. `C# Source File`).

That should help a lot until we get the icons to really ice this cake off. 👍

**Comment by acmario** [comment]
Any chance to have specific icons for each or at least main file types?

**Comment by ashikns** [comment]
Is there any update on this? Or at least some extension or registry script I can use to achieve this?

**Comment by misolori** [comment]
We're working on updating our file type icons that utilize the seti icons. There will be two icons at various sizes, the larger one will include the file type + vsc logo, the smaller one will only include the file type. Below is an example (on the mac) for both sizes:

**Larger view**
![image](https://user-images.githubusercontent.com/35271042/39787266-5f945b7c-52d9-11e8-97e1-2a852aead035.png)

**Smaller view**
![image](https://user-images.githubusercontent.com/35271042/39787385-f197caa4-52d9-11e8-9418-56a44d09da62.png)

**Comment by bpasero** [comment]
@misolori should we put this on the agenda again once we tackled Settings editor? Looks like we never really picked up on this.

**Comment by misolori** [comment]
@bpasero yes, let's do this after the Settings editor.

**Comment by NavyAdmiral** [comment]
@misolori Will it be possible to provide an api/settings to change the icons that will be shipped on default by vscode? Letting extensions modify file icons per file type in Explorer would be great.

**Comment by misolori** [comment]
@bpasero do we have a full list of all of the file types we'd want to support? The Seti theme has +160 file types, though a lot overlap:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/45199127-f42aaa80-b21e-11e8-8017-e3c8e93f6318.png">

**Comment by bpasero** [comment]
@misolori maybe we limit this to the top file types users are using Code with and find a generic icon for the rest? Not sure we need all the file types?

**Comment by misolori** [comment]
@bpasero I thought about maybe starting with the file types that appear in the Language Mode picker. But I’ll look through the telemetry we have for the top file types.

**Comment by bpasero** [comment]
@misolori yeah that list is open ended though when you install extensions
