### ISSUE TITLE
goToNextReferenceFromEmbeddedEditor and goToPreviousReferenceFromEmbeddedEditor does not remapped by keybindings.json

### ISSUE THREAD

**Issue by i5on9i** [Microsoft/vscode#48462]
- VSCode Version: 1.22.2
- OS Version: Windows 10

Steps to Reproduce:

1. open C:\Users\<user>\AppData\Roaming\Code\User\keybindings.json
2. set 'goToNextReferenceFromEmbeddedEditor' and 'goToPreviousReferenceFromEmbeddedEditor' with f7 and f8

	```
	    { "key": "f8",                    "command": "goToNextReferenceFromEmbeddedEditor",
	        "when": "inReferenceSearchEditor" }
	    ,{ "key": "f7",              "command": "goToPreviousReferenceFromEmbeddedEditor",
	        "when": "inReferenceSearchEditor" },
	```

3. it does not work, but f4 still works

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> it does not work, but f4 still works

Where does it not work? Note that this is only for the case in which the embedded editor is focused, so when having the focus somewhere else the `goToPreviousReference` and `goToNextReference` commands must be used

**Comment by i5on9i** [comment]
First of all, sorry for my poor english.

I meant that the issue is the remapping of the "goToNextReferenceFromEmbeddedEditor" and "goToPreviousReferenceFromEmbeddedEditor" does not work.

I have known how them work. I used them with "F4" and "shift+F4" , which is original short-cut.

However, when I write my own shortcut in keybinding.js of "goToNextReferenceFromEmbeddedEditor" and "goToPreviousReferenceFromEmbeddedEditor",  my new short-cut of them didn't work.

**Comment by jrieken** [comment]
I understand you question. My question is: "Where is the focus when this isn't working? In the embedded editor, the embedded tree, or somewhere else in the tool?"

**Comment by i5on9i** [comment]
I've tried some positions where the original short-cut is working such as embedded editor and just editor.

however, nothing happens, it looks the functions work only "f4" and "shift-f4" is mapped as the key.

**Comment by jrieken** [comment]
Yes, that's expected because there are *two* commands per directions (so fours in total): `goToNextReference ` _and_ `goToNextReferenceFromEmbeddedEditor` plus `goToPreviousReference ` _and_ `goToPreviousReferenceFromEmbeddedEditor `. If you want the same keybinding (f7/f8) everywhere you must override all, not just the two.

**Comment by i5on9i** [comment]
Oh i see
sorry for disturbing you. ;)

take care
