### ISSUE TITLE
Webview: Failed to read the localStorage property from Window

### ISSUE THREAD

**Issue by jscsharp** [Microsoft/vscode#48464]
I am using  new  Webview API which is been  used in "markdown-language-features" extension.
The  js library which I am using, has code to use "localStorage",  and causes an exception  in:
https://github.com/Microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/workbench/parts/webview/electron-browser/webviewElement.ts#L128 

**The  exception is :**

bubbles:false
cancelBubble:false
cancelable:false
composed:false
currentTarget:webview.ready
defaultPrevented:false
eventPhase:2
isTrusted:false
level:2
line:277
**message:
"Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs."**
path:
Array(11)
returnValue:true
sourceId:
"vscoderesource:/g:/vscode/extensions/myExt/MyLib.js"
srcElement:webview.ready
target:webview.ready
timeStamp:8945533.940000001
type:"console-message

The security setting for my page in Webview is same as 
https://github.com/Microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/extensions/markdown-language-features/src/features/previewContentProvider.ts#L171 

My question is:  is it allowed to use LocalStorage in Webview? or is there any setting to set?

Thanks

**Comment by mjbvz** [comment]
Yes local storage is disabled. We may try turning it back on at some point but there are not any definite plans for this

**Comment by jscsharp** [comment]
Thanks.
