### ISSUE TITLE
[themes] default themes: use editorLineNumber.activeForeground

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#48465]
I'm using Default Dark+ and my question is do these colors will be enabled by default or we need to do it by ourself?

1. `editorLineNumber.activeForeground` - introduced in 1.21 version and disabled by default in Default Dark+ theme, but enabled in Quiet Light, etc. My suggestion is to enable it by default.

2. `editorIndentGuide.activeBackground` - will be introduced in 1.23 version. My suggestion is to enable it by default.

**Comment by aeschli** [comment]
The default themes already got a color for `editorIndentGuide.activeBackground` through https://github.com/Microsoft/vscode/commit/0100518547990f6f8584f2d4cda8c9970e973ec9.

I push a commit that sets a default for `editorLineNumber.activeForeground` so the default themes now also support it.
