### ISSUE TITLE
Watch view doesn't show red for error message sometimes.

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode#48468]
- VSCode Version: 1.22.2
- OS Version: Win10 64Bit

Steps to Reproduce:

1. Install vscode-java-debug plugin, and start the debug and evaluate a bad expression, the error message should be shown in red, but actually it sometimes shows white: 
![img](https://user-images.githubusercontent.com/17075863/39167488-e190a05e-47c1-11e8-8063-776c39168889.png)

While debugger gives vscode the following reponse:
```
 {"success":false,"message":"Constructor of a local type cannot be used in an evaluation expression","request_seq":17,"command":"evaluate","body":{"error":{"id":1000,"format":"Constructor of a local type cannot be used in an evaluation expression"}},"seq":24,"type":"response"}
```

**Comment by isidorn** [comment]
@andxu what does "sometimes" mean? Can you please file this with reproducable steps?
Can you also reproduce this when you debug plain javascript?
Do you see value.unavalable.error when you inspect that element?

![inspect](https://user-images.githubusercontent.com/1926584/39190227-6bbdbb74-47d4-11e8-9307-8a2e3ac1609f.gif)

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/39222248-4b6c5cc8-486e-11e8-8847-602ac3ae0a03.png)

**Comment by andxu** [comment]
Sometime it works fine: 
![image](https://user-images.githubusercontent.com/17075863/39222293-866f9e52-486e-11e8-8d75-9c0ffa39ec04.png)

**Comment by andxu** [comment]
![bad](https://user-images.githubusercontent.com/17075863/39222477-684ef0de-486f-11e8-912f-817e65e66a61.gif)
![normal](https://user-images.githubusercontent.com/17075863/39222478-688d22a0-486f-11e8-9957-407b1e69efb0.gif)

**Comment by andxu** [comment]
Steps to repro:
1. install java debugger extension,
2. Open a folder, create a new BreakpointTest.java, and fill in the code:
```
class A {

    void m() {
        System.out.println("outer");
    }

    String n() {
        return "outer";
    }
}

public class BreakPointTest {
    public static void main(String[] args) {
        new BreakPointTest().go();
        int j = 0;
        new A() {
            @Override
            void m() {
                System.out.println("anonymous");
            }
        }.m();
        for (int i = 1; i <= 100; i++) {
            if (i <= 99) {
                j++;
            } else {
                System.out.println(j);
            }

        }
    }

    void go() {
        new A().m();
        class A {
            String n() {
                return "inner";
            }

            void m() {
                System.out.println("inner");
            }
        }
        new A().m();
    }

    static class A {
        String n() {
            return "middle";
        }

        void m() {
            System.out.println("middle");
        }
    }
}
```

**Comment by isidorn** [comment]
@andxu I have pushed a potential fix for this. Please try the vscode insiders tomorrow and let us know if this fixed the issue on your end

**Comment by weinand** [comment]
@andxu have you been able to verify that our fix works?
