### ISSUE TITLE
how to auto detect , auto encoding ?

### ISSUE THREAD

**Issue by xianghongai** [Microsoft/vscode#4846]
hi ,
- VSCode Version: 0.1011
- OS Version:windows 7 x64

![3](https://cloud.githubusercontent.com/assets/2075006/14199058/5ee79aa4-f813-11e5-8ca2-86d781fe4ed9.png)

not working

```json
{
    "files.encoding": "shiftjis",
    "files.encoding": "eucjp",
    "files.encoding": "big5hkscs",
    "files.encoding": "Big5",
    "files.encoding": "GB18030",
    "files.encoding": "GB2312",
    "files.encoding": "utf8",
    "files.encoding": "GBK"
}
```

**Comment by bpasero** [comment]
@xianghongai so in what encoding is this file?

**Comment by xianghongai** [comment]
hi,@bpasero ,
![1](https://cloud.githubusercontent.com/assets/2075006/14268167/85c334ea-fb0a-11e5-83dc-a9e9dcfb6968.png)
ANSI , Chinese Simplified(GBK) .

**Comment by bpasero** [comment]
@xianghongai can you attach it here?

**Comment by iHuahua** [comment]
兄弟，别指望了，我很久之前就提过，他们的回答是目前已经支持带DOM头的文件编码检测，不带DOM的不检测，我弄了个插件检测编码的，现在编码是检测成功了，但是切换编码卡住了，他喵的切换的API不开放，未来很长一段时间这个功能都不会有，不介意的话可以等等我的插件上线，由于接口限制，插件只能到 `Change File Encoding`那一步，顺带把检测的编码告诉你，手动切换一下

**Comment by bpasero** [comment]
@iHuahua maybe as full file?

**Comment by xianghongai** [comment]
@iHuahua batch file :)
[文件命名操作.zip](https://github.com/Microsoft/vscode/files/207697/default.zip)

**Comment by xianghongai** [comment]
@iHuahua 谢谢了，目前我是几个编辑器混着用的，可以解决一些问题，千万不要用sublime text编辑这种GBK编码格式的文件！我写批处理，几百行代码后，ST突然一个auto encoding 把我代码中文部分全乱码了！而且是撤销不了的乱码。

**Comment by bpasero** [comment]
I do not see myself able to handle this issue, @egamma please advise.

**Comment by egamma** [comment]
@iHuahua @xianghongai  the development team does not speak Chinese. Can you please find someone that can translate your comment to English?

**Comment by xianghongai** [comment]
thx, @bpasero , @egamma ,
iHuahua he said the vs code support dom document encoding detection, he said he is developing a plug-in to solve the problem is not dom document coding, such as .txt .bat .reg files. because of the vs code interface restrictions, at present can only be achieved "Change File Encoding" by manual switching, can't auto encoding.
some problems because windows code pages (ANSI) by locale select the encoding, such as chinese simplified gbk, korean euc-kr,  japanese cp932 and so on. 
maybe these questions no solution.

**Comment by egamma** [comment]
fyi @bpasero

**Comment by fanfeilong** [comment]
hi, when open a Lua file which is encoding as GBK and without BOM header, the VS Code can not aoto  dectect the encoding. I need to switch utf8 to GBK by hand every time i open a new such file, It's annoying. I've install the `gbktoutf8` extension to solve it (`ext install gbktoutf8`). But I hope the VS Code have some configuration to do it better.

**Comment by dongritengfei** [comment]
I have many projects, some of them are GBK encoded, other are UTF-8 encoded, so what can I do for setting different encoding for each project. appreciate for any help

**Comment by draculaw** [comment]
any updates for this issues?

**Comment by techteak** [comment]
please fix it

**Comment by Com-Mean** [comment]
any update of this issue？

**Comment by mauriciord** [comment]
Same here, always open a file at "UTF-8", but i need some files at "Western Windows 1252"

**Comment by skest3qc** [comment]
I am also having this kind of problem. Orignal file is ANSI with german umlauts and code converts it to UTF-8, then I am loosing the umauts.

**Comment by White99** [comment]
Very very old problem. 
We hope this issues can be resolved as soon as possible...

**Comment by mauriciord** [comment]
Yes, very old

Atenciosamente,
Maurício R. Duarte.

2016-09-06 10:14 GMT-03:00 White99 <notifications@github.com>:

**Comment by AaronWharton** [comment]
It's disgusting when I find all the notes have been garbled.It will take me hours to solve the issue.Why not release an extension to automatically switch the encoding format?

**Comment by zhangxaochen** [comment]
我的解决方式：
文件->首选项->用户设置->自动打开 settings.json。粘贴：
```
    // 读取和编写文件时将使用的默认字符集编码。
    "files.encoding": "GB2312"
```
GB大写。
done。

**Comment by DaniuLi** [comment]
any updates for this issues?

**Comment by 9chu** [comment]
It's a pity that vscode does not support auto encoding detect, but the Visual Studio does support that, and even the notepad2 could do that.

**Comment by jeff-wu** [comment]
any updates?

**Comment by fallenwood** [comment]
any updates or new apis?

**Comment by visitantz** [comment]
It's indeed annoying, usually web related files are utf-8 encoding, windows platform files are local encoding, so "files.encoding" setting is not helping at all, you still need to manually set half files each time.

**Comment by liucailin** [comment]
any updates?

**Comment by iKexinLL** [comment]
any updates?

**Comment by Forec** [comment]
Any supports or updates?

**Comment by lionel3** [comment]
Any updates?

**Comment by hackjackyer** [comment]
C:\Users\USERNAME\AppData\Roaming\Code\User\settings.json文件内容。即可
`{
"files.encoding": "GB2312"
}`

**Comment by fallenwood** [comment]
@hackjackyer 我们需要是`VSCode`自动检测文件编码并设置正确的编码，而不是只套用一个预设的编码

---

What we need is the ability that `VSCode` can detect the encoding of the file and set the correct encoding automatically rather than a default encoding to apply to all files.

**Comment by iKexinLL** [comment]
为什么不写个插件来对所有(或者大部分)的编码来进行判断呢?
---------------
Why not write a plugin for judge the encoding?
if encoding = 'utf-8'
elif ....

**Comment by lorensi** [comment]
Any update?

**Comment by HakuDouga** [comment]
**Update**

Pull request: #21416

**Comment by zjutjsj1004** [comment]
为什么我明明是UTF8，但是自动转换为GB2312，导致显示乱码

**Comment by a4027971** [comment]
settomg
"files.autoGuessEncoding": true,

**Comment by mauriciord** [comment]
> setting
> 
> "files.autoGuessEncoding": true,

@a4027971 Is this option real ? Exists ?

**Comment by a4027971** [comment]
> Is this option real ? Exists ?
@mauriciord 

VSCode verision : 1.14.1
OS : windows 7 x64

This option really exists 

[official documentation](https://code.visualstudio.com/docs/getstarted/settings)

**Comment by 1255225613** [comment]
hot key:ctrl+Comma, then change " "files.autoGuessEncoding": false " to " "files.autoGuessEncoding": true ".
