### ISSUE TITLE
cant use sudo, apt ,npm, etc in my vscode terminal even though I have Ubuntu bash installed on Windows 10

### ISSUE THREAD

**Issue by J-S-Thomas** [Microsoft/vscode#48475]
- VSCode Version: 1.22
- OS Version: Windows 10

Steps to Reproduce:
1. I Entered something Basic Like sudo apt update or npm update and I get This Error Message:         
bash: sudo: command not found
bash: npm: command not found

2. How Can I fix this problem so I can strictly use the terminal in vscode and not a separate terminal, in order to save space on my screens?

**Comment by Tyriar** [comment]
@J-S-Thomas what's in your settings.json file?

@bitcrazed I haven't seen this problem before, any ideas on how to diagnose/solve?

**Comment by amaajemyfren** [comment]
You may need to install Node.js to get  the npm command to work.

What happens when you do
`sudo` apt-get -y update`

**Comment by bitcrazed** [comment]
@J-S-Thomas Sounds like your integrated terminal isn't configured to start WSL. Please ensure you have the following line in your VSCode config (hit CTRL + ,)

```javascript
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe"
```
