### ISSUE TITLE
Code Helper SIGSEGV forced macbook system shutdown

### ISSUE THREAD

**Issue by ivorc** [microsoft/vscode#48477]
The following SIGSEGV caused my macbook to shutdown without warning while VSCode was in the background unused.

Process:               Code Helper [1265]
Path:                  /Users/USER/Downloads/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
Identifier:            Code Helper
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Electron [357]
Responsible:           Code Helper [1265]
User ID:               502

Date/Time:             2018-04-24 08:11:02.067 +0100
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Bridge OS Version:     3.0 (14Y664)
Anonymous UUID:        D2D05427-AE2C-BB5F-202D-A3F7F2A5934B

Time Awake Since Boot: 54 seconds

System Integrity Protection: enabled

Crashed Thread:        2  Watchdog

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0:
--> 
    __TEXT                 000000010e4a9000-000000010e4aa000 [    4K] r-x/rwx SM=COW  > [/Users/ivorcaldwell/Downloads/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper]

...

Thread 2 Crashed:: Watchdog
0   com.github.electron.framework 	0x000000010f289b63 0x10e4b6000 + 14498659
1   com.github.electron.framework 	0x000000010e7401c0 0x10e4b6000 + 2662848
2   com.github.electron.framework 	0x000000010e70974b 0x10e4b6000 + 2438987
3   com.github.electron.framework 	0x000000010e709a9c 0x10e4b6000 + 2439836
4   com.github.electron.framework 	0x000000010e70a05d 0x10e4b6000 + 2441309
5   com.github.electron.framework 	0x000000010e70d303 0x10e4b6000 + 2454275
6   com.github.electron.framework 	0x000000010e6c184a 0x10e4b6000 + 2144330
7   com.github.electron.framework 	0x000000010e70cd14 0x10e4b6000 + 2452756
8   com.apple.CoreFoundation      	0x00007fff285d1a61 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
9   com.apple.CoreFoundation      	0x00007fff2868b47c __CFRunLoopDoSource0 + 108
10  com.apple.CoreFoundation      	0x00007fff285b44c0 __CFRunLoopDoSources0 + 208
11  com.apple.CoreFoundation      	0x00007fff285b393d __CFRunLoopRun + 1293
12  com.apple.CoreFoundation      	0x00007fff285b31a3 CFRunLoopRunSpecific + 483
13  com.github.electron.framework 	0x000000010e70d6af 0x10e4b6000 + 2455215
14  com.github.electron.framework 	0x000000010e70d14c 0x10e4b6000 + 2453836
15  com.github.electron.framework 	0x000000010e70941e 0x10e4b6000 + 2438174
16  com.github.electron.framework 	0x000000010e722473 0x10e4b6000 + 2540659
17  com.github.electron.framework 	0x000000010e742d49 0x10e4b6000 + 2673993
18  com.github.electron.framework 	0x000000010e7175b7 0x10e4b6000 + 2495927
19  libsystem_pthread.dylib       	0x00007fff50bd4661 _pthread_body + 340
20  libsystem_pthread.dylib       	0x00007fff50bd450d _pthread_start + 377
21  libsystem_pthread.dylib       	0x00007fff50bd3bf9 thread_start + 13

**Comment by bpasero** [comment]
Full stack:

```
gpu::GpuWatchdogThread::DeliberatelyTerminateToRecoverFromHang() (in Electron Framework) (gpu_watchdog_thread.cc:369)
base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask*) (in Electron Framework) (task_annotator.cc:39)
base::MessageLoop::RunTask(base::PendingTask*) (in Electron Framework) (message_loop.cc:421)
base::MessageLoop::RunTask(base::PendingTask*) (in Electron Framework) (message_loop.cc:419)
base::MessageLoop::DoDelayedWork(base::TimeTicks*) (in Electron Framework) (message_loop.cc:561)
base::MessagePumpCFRunLoopBase::ScheduleDelayedWork(base::TimeTicks const&) (in Electron Framework) (message_pump_mac.mm:0)
base::mac::FrameworkBundlePath() (in Electron Framework) (bundle_locations.mm:48)
base::MessagePumpCFRunLoopBase::RunDelayedWorkTimer(__CFRunLoopTimer*, void*) (in Electron Framework) (message_pump_mac.mm:172)
```
