### ISSUE TITLE
Intellisence Not Working

### ISSUE THREAD

**Issue by ihassanamjad** [Microsoft/vscode#48478]
Issue Type: <b>Bug</b>

Intelllisence stops working automatically. I have to restart the program to see intellisence working. Kindly resolve this issue out.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|7.89GB (1.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe E:\Projects\Alfain\estore\estore_client|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-babel-coloring|dza|0.0.4
react-native-react-redux|EQu|1.8.0
vsc-material-theme|Equ|2.0.1
auto-close-tag|for|0.5.6
material-icon-theme|PKi|3.3.0

</details>

**Comment by bpasero** [comment]
@ihassanamjad what file type are you editing?

**Comment by ihassanamjad** [comment]
@bpasero I am editing JS file in React

**Comment by mjbvz** [comment]
Do you also see this problem in [VS Code insiders](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by ihassanamjad** [comment]
@mjbvz Yes, I have disabled all the extensions but the issue is still there. When I start VS Code, Intellisence works perfectly fine, but after some time it stops showing suggestions. If I press Ctrl + Space it shows "Loading" in suggestions.

**Comment by uvuwuewuewue** [comment]
I still have the problem even in Insider version,
steps to reproduce : 
1 - try importing something from a third party package, (ex [material-ui](https://material-ui-next.com/))
2- If you  import something that doesn't get suggested immediatly  by Intellisence from that package, it will crash (ex material-ui/Icon  almost never gets suggested and leads to the bug)

**Comment by mjbvz** [comment]
Please also try upgrading your workspace to `typescript@next` by following these instructions: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions. Make sure you select the workspace version of typescript by running the `Select TypeScript Version` command after installing

A similar bug was fixed in typescript@next
