### ISSUE TITLE
ProtocolHandler API: doesn't work if Code isn't running yet

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48479]
Testing #48427

**Comment by weinand** [comment]
@joaomoreno on macOS running the following from a terminal
`open vscode-insiders://andreweinand.protocol-handler/foo`
opens VS Code and shows the redirecting alert.
But after pressing "Yes" the handler isn't called because VS Code was launched with the `--enable-proposed-api` flag.

**Comment by joaomoreno** [comment]
Interesting, I didn't see it happening for me. I'll investigate more...

**Comment by sbatten** [comment]
Same behavior on Windows for me

**Comment by joaomoreno** [comment]
This was a cute issue. The protocol handler would register while the user was being prompted whether he wants to let the extension handle the URI. It would then get lost after confirmation.

Steps:

1. Run `code-insiders --open-url vscode-insiders://vscode.git/clone?url=git%40github.com%3AMicrosoft%2Fvscode-vsce.git`.

You should be prompted as to whether you'd want to let the git extension handle the URL. If accepted, the clone action should take place.
