### ISSUE TITLE
Ability to fold all the comments in vscode at one click

### ISSUE THREAD

**Issue by sabbiu** [Microsoft/vscode#48473]
there is similar plugin in sublime text editor called, fold comments. I want this feature in vscode too..

> Is there anything similar to this?

**Comment by aeschli** [comment]
We already have a fold comment command (Ctrl+K Ctrl + /). Not good enough?

Please add more details what you are suggesting.

**Comment by sabbiu** [comment]
Thanks! this was exactly what I was looking for...
