### ISSUE TITLE
Find All References does not find references in modules within same workspace

### ISSUE THREAD

**Issue by guw** [Microsoft/vscode#48474]
- VSCode Version: 1.23.0-insider 
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Clone `git@github.com:forcedotcom/salesforcedx-vscode.git`
2. Run `npm run bootstrap`
3. Open Code in project root folder
4. Open `requestService.ts`
5. Invoke _Find All References_ on method `getEnvVars()`

Expected Result:

- All references from within the VS Code workspace are found. In particular, references in `*.ts` files which import `RequestService` should be found

Actual Result:

- Only reference within the same module are found.

It looks like VS Code is confused by the way `RequestService` is imported in other modules. For example, the `import` statement in `breakpointService.ts` imports `RequestService` from `@salesforce/salesforcedx-utils-vscode/out/src/requestService`. Note the additional `out` folder in the path. It is required because of how Node expects it at runtime. If the `out` folder is omitted _Find All References_ will correctly find the references. However, ommitting the `out` folder breaks the imports (`require`) at runtime.

I tried a path mapping in `tsconfig.json` by setting `baseUrl` and `paths` as shown below. But it wasn't successful, i.e. non of them seemed to make a difference in VS Code.

`packages/salesforcedx-apex-debugger/tsconfig.json`:
```
{
  "compilerOptions": {
    ..
    "rootDir": ".",
    "outDir": "out",
    "baseUrl": ".",
    "paths": {
      "@salesforce/salesforcedx-utils-vscode/out": [
        "../salesforcedx-utils-vscode"
      ]
    }
    ..
}
```

I wonder if VS Code should detect that the `out` folder is specified by `tsconfig.js` `outDir` option and map it to the actual TypeScript source within `rootDir`.

**Comment by mjbvz** [comment]
This sounds like a good use case for TypeScript [project references](https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/#project-references)

Project references should ensure that references are found properly across modules in your workspace

**Comment by tamethecomplex** [comment]
hi @guw , Have you found a solution to this problem?

@mjbvz , have you gotten tsc language services (e.g. refactoring, go to def, find all references) to work with the new TS project references feature?  I haven't gotten it to work.  For example, renaming "fn4" in pkg2 at the example repo [here](https://github.com/RyanCavanaugh/learn-a) doesn't result in the renaming of the same symbol in the dependent package (pkg3).
