### ISSUE TITLE
VS Code on linux (Code - OSS) won’t start

### ISSUE THREAD

**Issue by GoDzM4TT3O** [Microsoft/vscode#48472]
- VSCode Version: Unknown- how do I get it?
- OS Version: Raspbian 9 stretch (Raspberry Pi 0 w)

Steps to Reproduce:

1. Open Terminal
2. Run <code>code-oss</code>

This will print an error:
<code>/usr/bin/code-oss: line 35: 9054 Segmentation fault
ELECTRON_RUN_AS_NODE=1 “$ELECTRON” “$CLI” “$@“</code>

Any idea on how to fix this issue?
- Node version: v9.8.0
- npm version: v5.8.0

Notes:
I added ‘<code>deb https://packagecloud.io/headmelted/codebuilds/raspbian/ jessie main</code>’ - as the tutorial said - to add the code-oss repo;
I ran ‘<code>sudo apt-get install code-oss</code>’ to install code-oss;
I ran ‘<code>code-oss</code>’ in the Terminal with no result. Tried to load the GUI from the app menu but it doesn’t start.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I do not think we officially support running on a Raspberry...

**Comment by joaomoreno** [comment]
Yeah, we don't support ARM yet. Sorry!
