### ISSUE TITLE
Option to disable quote paring

### ISSUE THREAD

**Issue by ShayBox** [Microsoft/vscode#48470]
- VSCode Version: Stable
- OS Version: Windows 10

Steps to Reproduce:

1. Select anything
2. Press a quote type

Does this issue occur when all extensions are disabled?: Yes

Please provide an option to disable this behavior
![image](http://shay.is-your.pet/34cg.gif)
Without having to disable bracket pairing as well, I don't like this behavior but I want bracket pairing 😞

**Comment by rebornix** [comment]
You can turn this off by setting `"editor.autoClosingBrackets": false`.
