### ISSUE TITLE
closeAllFiles does not close Default Settings and Default Keyboard Shortcuts

### ISSUE THREAD

**Issue by stephenmartindale** [Microsoft/vscode#4847]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. Bind a keyboard shortcut to `workbench.files.action.closeAllFiles`
2. Open either `File -> Preferences -> User Settings` or `File -> Preferences -> Keyboard Shortcuts`
3. Observe that the right-hand pane shows your editable settings file and either `Default Settings` or `Default Keyboard Shortcuts`, respectively.
4. Press your keyboard shortcut for `workbench.files.action.closeAllFiles`
5. Observe that the right-hand pane closes but the left-hand pane (`Default Settings` or `Default Keyboard Shortcuts`) remains open.

Intriguingly, if you open multiple files in multiple panes, `workbench.files.action.closeAllFiles` behaves exactly as one would expect and closes all of them, returning you to an empty workspace.

**Comment by bpasero** [comment]
Has been fixed for our next release. You can try it out from our insiders release: http://code.visualstudio.com/Download#insiders
