### ISSUE TITLE
Customizable 'Open in Command Prompt' console

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#4848]
_Open in Command Prompt_ currently opens `cmd.exe`, it would be nice to customize it to run e.g. Cmder or ConEmu which are much better alternatives.

**Comment by Peter-Juhasz** [comment]
Or PowerShell

**Comment by joaomoreno** [comment]
Related to #597 #3495

**Comment by borekb** [comment]
This is probably a duplicate of #3495 then. Closing.
