### ISSUE TITLE
Should it be `editorIndentGuide.activeBorder`?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#48483]
re #48418

There is a setting new `editorIndentGuide.activeBackground` and I wonder if `Backrgound` is a good pick. What would `Foreground` be? Should it be `Border` or just color?

**Comment by bpasero** [comment]
@jrieken since we already have `editorIndentGuide.background` I think having `editorIndentGuide.activeBackground` makes sense and we cannot really change colors after the fact. But yeah, something like `border` would have probably made more sense in the first place.

**Comment by jrieken** [comment]
makes sense
