### ISSUE TITLE
Changes in user launch configuration not picked up by debug dropdown

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#48487]
Refs: #48423

Not sure if this was caused by refactoring so assigning to both of us.

1. Have a launch configuration in your user settings
2. Rename that launch configuration -> notice how the select drop down name is not updating

**Comment by isidorn** [comment]
I plan to investigate after I am done testing, so I can first look into it.

**Comment by weinand** [comment]
I'm pretty sure that I didn't touch anything in that area.

**Comment by weinand** [comment]
I'm stilling seeing the issue (on macOS and windows)

**Comment by isidorn** [comment]
I can reproduce this and the issue seems to be that I am not getting [`onDidChangeConfiguration`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L60) from @sandy081 thus forwarding the issue to him.

Additional data: 
1. If I change any other user setting I nicely get the event
2. Only if I change things inside the `launch` section in user settings I am not getting an event

I believe this was working 2 days ago, might it be that you changed something in the meantime?

**Comment by sandy081** [comment]
@isidorn I have not touched anything in this area this week. But assigning to April for investigation to check if something got broken.

**Comment by sandy081** [comment]
Moving this as it is not important to fix.

**Comment by sandy081** [comment]
This is fixed now.
