### ISSUE TITLE
Allow me to pick a different folder in case you don't like my first pick

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#48485]
Testing #48428

Open `vscode-insiders://vscode.git/clone?url=git%40github.com%3AMicrosoft%2Fvscode-textmate.git`

The experience is too unforgiving IMHO.

I typed `/Users/alex/src` as that is where I keep my git repositories as folders. I got this error and now I need to start again from the browser.

> The root cause is that I already have `vscode-textmate` checked out at that location.

![image](https://user-images.githubusercontent.com/5047891/39175719-5747232a-47ab-11e8-93b8-0b233034df6d.png)

**Comment by joaomoreno** [comment]
I decided to go with an incrementing counter suffix, like we do in the explorer.

**Comment by alexandrudima** [comment]
@joaomoreno Would also be very nice to look at the existing folder and let me know if I have the repository already cloned. 

An option could let me choose if I want to clone it again or simply open it... but let's also track this in #48490
