### ISSUE TITLE
Installing from VSIX fails when another extension depends on the extension you're installing

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#48489]
You're unable to install an extension from a vsix if you have an external installed that depends on it.

In this case, I have installed Flutter from the marketplace which depends on Dart Code. I'm trying to install a beta of Dart Code from a VSIX. The install fails saying I cannot uninstall Dart Code because Flutter depends on it. While that's true, I'm not really trying to uninstall Dart Code, I'm trying to upgrade it.

I presume when Dart Code updates in the marketplace this check would be skipped, so possibly the vsix install could do the same?

**Comment by DanTup** [comment]
I've had some reports of this again - I often use vsix's for testing, but I also have an extension that depends on it. It's not currently a huge number of users, but more and more people are installing the "extension pack" so it's likely to get worse; it'd be great if there was a fix (or an easy workaround).

**Comment by sandy081** [comment]
@DanTup It is working for me. I installed a extension A that depends on extension B and I could update extension B (using VSIX) without issues. Are there any steps I am missing here?

**Comment by DanTup** [comment]
Hmmm; I cannot reproduce it either. Feel free to close; I'll ping who last reported it to see if they can repro (or have them let me know if they do have it again).
