### ISSUE TITLE
Display fullwidth characters

### ISSUE THREAD

**Issue by trunglanh** [Microsoft/vscode#48481]
- VSCode Version: 1.22.2
- OS Version: Windows 7 professional 32 bit build 7601

Steps to Reproduce:
Byte length of all string are 20 bytes but width are different
Encoding: shift jis
**Example text**
```
AAAAAAAAAAAAAAAAAAAA|
12345678901234567890|
ウェスティン        |
おはよう            |
（株）サンリツ京浜事|
```
**In vscode**

![image](https://user-images.githubusercontent.com/36248781/39173271-40d6e09c-47df-11e8-85f2-53b30ee64b6c.png)

**In notepad**

![image](https://user-images.githubusercontent.com/36248781/39174180-eccd0f1e-47e1-11e8-9158-62e1774563a4.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@trunglanh We render editor fonts using Chromium's font rendering. Chromium renders text using the widths and sizes encoded in the font itself. In other words, we don't do any special provisioning for CJK glyphs, we end up painting them using the font's settings.

Your example renders fine for me when I use a font which always renders CJK glyphs with the width of two latin characters:

```
    "editor.fontFamily": "Inconsolata"
```

![image](https://user-images.githubusercontent.com/5047891/39230592-509097d4-4867-11e8-819f-48da9f5cea1a.png)
