### ISSUE TITLE
Add `#` as trigger character for region completions in CSS/SCSS/LESS

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#48488]
Issue Type: <b>Feature Request</b>

Testing #48235

There are snippets for SCSS, it would make sense to have these for CSS and LESS too.

VS Code version: Code - Insiders 1.23.0-insider (b845ce918f2689344795e845ae6ef691916c3079, 2018-04-24T05:10:57.500Z)
OS version: Darwin x64 16.7.0

**Comment by octref** [comment]
@chrmarti What kind of snippet? We do have some for CSS/LESS.

![snippet](https://user-images.githubusercontent.com/4033249/39279765-f5da492c-48af-11e8-9ea3-f0ad716d7f78.gif)

**Comment by octref** [comment]
One thing I noticed, however, is when you type `/* #` the IntelliSense is not shown automatically. You need to manually trigger it. I can look into adding `#` as a completion trigger.

**Comment by octref** [comment]
Actually we return a list of items that doesn't make sense for cases such as `/* #| */`. I'll look into supporting only region completions in comment (don't think there are other valid completions in there). And if we return empty results, people who have enabled word based suggestion could use that in comments.

**Comment by octref** [comment]
For this one, we need to turn on this:

```json
  "editor.quickSuggestions": {
    "comments": true
  }
```

Which we don't really do in any language servers, so closing.
