### ISSUE TITLE
unverified breakpoint icon is not strong enough

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#48491]
When creating a breakpoint in an active debug session and this breakpoint cannot be verified, the resulting icon is almost invisible:

![2018-04-24_10-48-05](https://user-images.githubusercontent.com/1898161/39176424-13c33be6-47ad-11e8-8449-29e2f1b87b79.png)

The problem is that the icon's stroke is too thin.
In previous versions the icon had a thicker stroke:

![2018-04-24_10-51-15](https://user-images.githubusercontent.com/1898161/39176585-7615ac20-47ad-11e8-87d4-881df7facb66.png)

I suggest that we restore the previous icon.

**Comment by isidorn** [comment]
Agree that it is a bit too light.
I do not just want to take the previous icon since the color and style are different.

Thus it would be great if @chryw could tackle this
Also fyi @misolori

**Comment by chrmarti** [comment]
Not quite as strong as in the 'before' above, but stronger. Marking verified.
![image](https://user-images.githubusercontent.com/9205389/40788211-cef6a7ae-64ef-11e8-9878-1312d6ad39ba.png)
