### ISSUE TITLE
Git: Clone command should find repository, if known

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#48490]
Testing #48428

When I think of a link to a git repository, I think of something that is to be opened.

* open `vscode-insiders://vscode.git/clone?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvscode-textmate.git`
* pick a folder
* open the same link again
* I expect VS Code to ask me if I want to open the place where I have it already (the default), or if I want to clone it again (not the default).

Today, clicking on the same link makes another clone which IMHO is a bit useless, how many people would want to clone the same repository twice...

**Comment by joaomoreno** [comment]
I like that. It'll be tough since we have to search the file system for it. Maybe we come up with some heuristics for search patterns?

**Comment by alexandrudima** [comment]
@joaomoreno If I have opened that repository with vscode (ever), you can (from the git extension) remember that somewhere locally. Then, when you are asked to clone the same origin, you can propose to open instead.

**Comment by joaomoreno** [comment]
Yeah I guess we can do some recording

**Comment by joaomoreno** [comment]
Sounds 👍 . The feature should trigger whenever the user runs the clone command (same path as clicking that URL). The storage should be bounded... let's say 50 repos?

**Comment by Double-A-92** [comment]
> @joaomoreno If I have opened that repository with vscode (ever), you can (from the git extension) remember that somewhere locally. Then, when you are asked to clone the same origin, you can propose to open instead.

That might not always work, because the cloned repo could've been deleted by the user.

**Comment by bhuvinth** [comment]
@rdosanjh : Have you taken it up? If not I would like to give it a try.

**Comment by mkolm** [comment]
I would like to try to work on this issue if it is still available. Which files should I look at and edit?
