### ISSUE TITLE
Debug console overlaps terminal when debug starts

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#48493]
Refs: https://github.com/Microsoft/vscode/issues/48423

I know there was already an issue for this but I could not find it, so creating a new one.

1. Have some simple node repo, for instance our smoke test repository
2. Have `"console": "integratedTerminal"` in your `launch.json`
3. Start debugging, notice how the debugConsole is shown over the integrated terminal

I thought the debug adapter will overwrite the alunch configuration and add `"internalConsoleOptions": "neverOpen"`. I did not double check if the debug adapter is properly setting this argument.

**Comment by weinand** [comment]
@isidorn this is the fix (and the old issue) on my side:

https://github.com/Microsoft/vscode-node-debug/blob/8c6f4d53dfda491d1bb335dd57147e9fdad9c782/src/node/extension/configurationProvider.ts#L92-L95

**Comment by weinand** [comment]
@isidorn I cannot reproduce this (and I've verified that "internalConsoleOptions" is set to "neverOpen" iff "console" is "integratedTerminal")
