### ISSUE TITLE
Certain CSS properties are not suggested

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#48495]
Testing #48443

The following properties are not suggested via intellisense:
* `gap`
* `image-resolution`
* `row-gap`

**Comment by octref** [comment]
@alexandrudima Thanks, those were intentionally left out. `image-resolution` because it was not standard but marked standard. `gap` and `row-gap` due to a [misunderstanding on MDN docs](https://github.com/mdn/data/issues/213). I pushed a fix for it.
