### ISSUE TITLE
[Feature Request] SQF syntax highlighting

### ISSUE THREAD

**Issue by ole1986** [Microsoft/vscode#485]
I would really like to hgave the ArmaA SQF (Status Quo Function) file format syntax highlighting in it.
More Info: https://community.bistudio.com/wiki/SQF_syntax

**Comment by joaomoreno** [comment]
This would be a great extension to write, @ole1986

**Comment by ole1986** [comment]
https://github.com/Armitxes/VSCode_SQF its already been made by another person. Thanks
