### ISSUE TITLE
Example code for WebView should live in https://github.com/Microsoft/vscode-extension-samples

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#48505]
Tests https://github.com/Microsoft/vscode/issues/48453

as all our other sample code.

**Comment by mjbvz** [comment]
Pushed https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-sample

**Comment by sandy081** [comment]
@mjbvz Looks like this was not added to the `.code-workspace` file. Added it.
