### ISSUE TITLE
intellisense for "onUri" event behaves strange

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#48504]
testing #48427:

- open package.js of your new extension
- set caret in "activationEvents" in order to add a new event
- request code assist
- select "onUri" and press return

Observe: "onView" is inserted

![2018-04-24 11 24 46](https://user-images.githubusercontent.com/1898161/39178756-cb1f67e2-47b2-11e8-897c-1aefb04947c4.gif)

Selecting any other event works fine.

**Comment by joaomoreno** [comment]
Great catch, it was a bad copy.
