### ISSUE TITLE
Extension tests: debugger does not disconnect when tests finishes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48507]
Steps to Reproduce:

1. `yo code` to produce a TS extension
2. run the extension tests

=> after the tests finish, the debug toolbar is still showing

![image](https://user-images.githubusercontent.com/900690/39179510-ca667b7c-47b4-11e8-89ff-59b23eeebe6e.png)

**Comment by weinand** [comment]
most likely a duplicate of #48442

**Comment by bpasero** [comment]
@weinand if this is a duplicate and that one has been verified, why is this one marked as verification needed?

**Comment by weinand** [comment]
Because of the "most likely" in my comment above. I wasn't really sure whether the fix for #48442 fixes this issue too.

**Comment by bpasero** [comment]
@weinand yup verified

**Comment by weinand** [comment]
great, thx!
