### ISSUE TITLE
"Install shell command `code` doesn't do anything"

### ISSUE THREAD

**Issue by cafreeman** [Microsoft/vscode#4850]
- VSCode Version: 0.10.13 Insiders
- OS Version: Mac OS X El Capitan

Steps to Reproduce:

1. Install the insiders 0.10.13 Insiders build
2. Open VS Code and run the "Install `code` command in PATH" utility from the command palette.
3. restart terminal
4. try to run `code`
5. nothing happens

Checked `.bashrc`, `.bash_profile`, and `.zshrc` (`zsh` is actually my shell, but I checked the `bash` ones just to be safe) and saw no evidence that VS Code had tried to write anything.

**Comment by Tyriar** [comment]
@cafreeman the insiders build will actually install `code-insiders`, the "typo" in the command palette for the insiders build is captured in https://github.com/Microsoft/vscode/issues/3877

If you're still experiencing issues, you can try running `whereis code-insiders` to help diagnose the issue.
