### ISSUE TITLE
Terminal API: debounce onData()?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#48513]
Refs: https://github.com/Microsoft/vscode/issues/48434

It looks like every single character I type produces a onData event in the terminal. Should this maybe be debounced? What is the scenario for having this API that it needs to fire on each keystroke?

**Comment by JacksonKearl** [comment]
Is this user-facing? How can I verify?

**Comment by Tyriar** [comment]
@eamodio can you put some steps in please?

**Comment by eamodio** [comment]
To test this you need to create an extension:

1. Run `npx -p yo -p generator-code -c 'yo code --extensionType=command-ts'` to scaffold an extension
1. Add `"enableProposedApi": true` to the `package.json`
1. Change `"activationEvents"` in the `package.json` to `"activationEvents": ["*"]`
1. Replace the `activate` function in `extension.ts` with the following
```ts
export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(
        (vscode.window as any).onDidWriteTerminalData(
            (e: { readonly terminal: vscode.Terminal; readonly data: string }) => {
                console.log(`${e.terminal.name}\n${e.data}`);
            }
        )
    );
}
```
1. Run the extension and switch to the _Debug Console_
1. In the newly launched vscode extension host window, open a terminal and run an `ls` command or a command that will output a bunch of data
1. Back in the original vscode window, in the _Debug Console_ ensure you see the output from the terminal with multiple lines for each event (prior to these changes it would have only be 1 line per event at most)
