### ISSUE TITLE
Terminal API: onData event fires when I resize the terminal?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48517]
Refs: https://github.com/Microsoft/vscode/issues/48434

It looks like the onData event fires as soon as I resize the terminal. This seems unexpected to me because nothing was typed to the terminal.

![flicker_chrome58](https://user-images.githubusercontent.com/900690/39181032-aeca4426-47b8-11e8-9263-cd15203f9817.gif)

**Comment by Tyriar** [comment]
This is as designed, it may change when the Windows pty is improved but it depends on powershell/cmd's implementation.
