### ISSUE TITLE
Terminal API: clarify onData event

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48516]
Refs: https://github.com/Microsoft/vscode/issues/48434

I am a bit confused what the `onData` event for the terminal API actually provides me. It seems to me that each keystroke I do is reflected (even when I press backspace I get some weird `[K` showing up). I think this deserves more documentation and possibly also a different name. E.g. if this is about notifying whenever something is showing in the integrated terminal, should it be `onText` or `onOutput` instead?

**Comment by Tyriar** [comment]
@bpasero opps I didn't include jsdoc for it.

>  if this is about notifying whenever something is showing in the integrated terminal, should it be onText or onOutput instead?

This is not what it is, it's data from the raw pty, including escape sequences. That's why https://github.com/Microsoft/vscode/issues/48517 is as expected; because on Windows it redraws the screen whenever you resize. I'll clarify in a comment :+1:

**Comment by bpasero** [comment]
@Tyriar and what is the use case for having this APIß

**Comment by Tyriar** [comment]
```ts
	export interface Terminal {
		/**
		 * Fires when the terminal's pty slave pseudo-device is written to. In other words, this
		 * provides access to the raw data stream from the process running within the terminal,
		 * including ANSI sequences.
		 */
		onData: Event<string>;
	}
```

**Comment by Tyriar** [comment]
@bpasero enabling multiplexing of the terminal.

**Comment by bpasero** [comment]
I strongly suggest to stay away from the word `slave`.

**Comment by Tyriar** [comment]
@bpasero that's the technical term and helps describe exactly what it does, there is a master and a slave side to the pty https://en.wikipedia.org/wiki/Pseudoterminal

**Comment by bpasero** [comment]
Dunno, at one point we got bashed for using words such as `slave` in the code. E.g. we say "master / detail" and not "master / slave".

**Comment by Tyriar** [comment]
I think this is a little different though as it's an established technical term of which there is no other name, not a UI paradigm we're introducing.
