### ISSUE TITLE
Support Linux URL handlers

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48528]

**Comment by langpavel** [comment]
This may be useful as a hint: [shengyou/vscode-handler#installing-on-linux](https://github.com/shengyou/vscode-handler#installing-on-linux-ubntu)
Please, take a two minutes to look into source, it may work only for `open`:
https://github.com/shengyou/vscode-handler/blob/master/vscode-handler#L3

**Comment by segevfiner** [comment]
[shared-mime-info-spec - URI scheme handlers](https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html#idm140625828587776)

I think adding a [NoDisplay](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys) desktop file with `MimeType=x-scheme-handler/vscode` that launches VS Code with `--open-url` is what's needed to implement this.

**Comment by langpavel** [comment]
nice relevant gist: https://gist.github.com/peakhmr/9623e8f6da0acbec10d4ae1171bb7c70

**Comment by segevfiner** [comment]
VS Code has native support for opening it's own URL scheme via the hidden `--open-url` argument, I don't think there is a need for wrapper script shenanigans.

**Comment by AmandaCameron** [comment]
I've not checked too far into it (Just subscribed to this to keep up to
date) but the wrapper script is probably there because `%u` in the standard
would include the "vscode://" prefix.

**Comment by segevfiner** [comment]
> I've not checked too far into it (Just subscribed to this to keep up to date) but the wrapper script is probably there because `%u` in the standard would include the "vscode://" prefix.

That's what should happen, that's what `--open-url` handles. You can test #56727 if you like. Alternatively you can test this (Which is what the PR adds):

For OSS:
```desktop
[Desktop Entry]
Name=Code - OSS - URL Handler
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code-oss/code-oss --open-url %U
Icon=code-oss
Type=Application
NoDisplay=true
StartupNotify=true
StartupWMClass=Code - OSS
Categories=Utility;TextEditor;Development;IDE;
MimeType=x-scheme-handler/vscode
Keywords=vscode;
```

For release version:
```desktop
[Desktop Entry]
Name=Visual Studio Code - URL Handler
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --open-url %U
Icon=code
Type=Application
NoDisplay=true
StartupNotify=true
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=x-scheme-handler/vscode
Keywords=vscode;
```

Drop it into `/usr/share/applications` or `~/.local/share/applications` and run `update-desktop-database` on that directory. If you test with the official release,
