### ISSUE TITLE
passing the CLI option "--enable-proposed-api" without extension id isn't flagged as an error

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#48521]
testing #48427:

I was running "code-insiders" with  the "--enable-proposed-api" option without noticing that the option requires an extension ID.

This should be fixed either by
- reporting an error and aborting "code", or by
- interpreting a missing extension ID as the semantics "enable proposed API for any extension"

**Comment by eamodio** [comment]
Please support the latter 😄 
> interpreting a missing extension ID as the semantics "enable proposed API for any extension"

**Comment by alexandrudima** [comment]
:+1:

I was in an endless loop running `code-insiders --enable-proposed-api` and then reading the error message `Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api`.

Please don't make me find out the extension id.

**Comment by jrieken** [comment]
Well, the error message should simply print the extension id...

**Comment by jrieken** [comment]
fixed vai #52861
