### ISSUE TITLE
vscode.FileSystemProvider API feedback

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#48527]
Testing #48412

Grouping all of these suggestions in one item to make it easier to talk about them:

✅ 1. typo `FileSystemProvider2` => `FileSystemProvider`
```ts
/**
 * An event to signal that a resource has been created, changed, or deleted. This
 * event should fire for resources that are being [watched](#FileSystemProvider2.watch)
 * by clients of this provider.
 */
readonly onDidChangeFile: Event<FileChangeEvent[]>;
```

✅ 2. arguments passed in (even via options) should perhaps not have optionals.
```ts
/**
 * Subscribe to events in the file or folder denoted by `uri`.
 * @param uri
 * @param options
 */
watch(uri: Uri, options: { recursive?: boolean; excludes?: string[] }): Disposable;
```

3. Nail down as many `stat` options as possible now. Some ideas:
* document that type information (via `isFile`, `isDirectory` or `isSymbolicLink`) is always mandatory
* `followSymlinks`
* `includeSize`
* `includeModifiedTime`
* `includeCreationTime` (see below)

✅ 4. Perhaps enlarge the stat already with creation time. What else are we missing from e.g. node's stat ?

5. `readDirectory` should take in the exact same stat options as a sub-option. In fact, all of the methods that return a stat should take perhaps as a sub-option the options that can be passed into stat.

✅ 6. It is not clear if `createDirectory` should be recursive or not (for missing intermediate directories). 
 Same for `writeFile`.

✅ 7. It is not clear if `delete` should delete recursively.

✅ 8. Comment is inconsistent (remove "from the underlying storage" or add it everywhere...)
```ts
// Delete a file or folder from the underlying storage.
```

✅ 9. Parameter naming, use `source` and `destination` or something.
```ts
/**
 * Copy files or folders. Implementing this function is optional but it will speedup
 * the copy operation.
 *
 * @param uri The existing file or folder.
 * @param target The target location.
 * @param token A cancellation token.
 */
copy?(uri: Uri, target: Uri, options: FileOptions, token: CancellationToken): FileStat | Thenable<FileStat>;

```

✅ 10. What is a `FileError.EntryNotFound` error ?
```ts
/**
 * Retrieve metadata about a file. Throw an [`EntryNotFound`](#FileError.EntryNotFound)-error
 * in case the file does not exist.
 *
 * @param uri The uri of the file to retrieve meta data about.
 * @param token A cancellation token.
 * @return The file metadata about the file.
 */
```

✅ 11. Another typo `FileType2`:
```ts
/**
 * Retrieve the meta data of all entries of a [directory](#FileType2.Directory)
 *
 * @param uri The uri of the folder.
 * @param token A cancellation token.
 * @return A thenable that resolves to an array of tuples of file names and files stats.
 */
readDirectory(uri: Uri, options: { /*future: onlyType?*/ }, token: CancellationToken): [string, FileStat][] | Thenable<[string, FileStat][]>;
```

12. Why does `createDirectory` return a stat and `writeFile` does not?

✅13. Should `delete` throw if the file or directory to be deleted is not found ?

✅14. Should `rename` throw if the source is not found or if the target exists? Should it overwrite the target ? Same question about `copy`.

**Comment by dbaeumer** [comment]
Will add my comments here as well:

1. document inlined types
```ts
/**
 * Subscribe to events in the file or folder denoted by `uri`.
 * @param uri
 * @param options
 */
watch(uri: Uri, options: { recursive?: boolean; excludes?: string[] }): Disposable;
```
We should document `recursicve` and `excludes`

2. Should we like NodeJS use functions instead of poperties for `isFile`, 'isDirectory`, .... (see https://nodejs.org/api/fs.html#fs_stats_isdirectory). Would it make more consistent and removes the discussion whether these properties are optional.

3. FileOptions have a `read` and `write` property and can be passed to readFile and writeFile. Do we need this at all. What happens if I call writeFile and have `FileOptions.read = true`.

**Comment by jrieken** [comment]
Some general change notice: Based on @dbaeumer's feedback and discussion I have removed cancelation-tokens (we can still add them later). Based @alexandrudima feedback I have removed most kitchen-sink-who-knows-what-comes-options because we can only ever use them to relax an operation. Not having tokens (that block the last argument-position) makes it nicer to eventually add them back.

**Comment by jrieken** [comment]
> Why does createDirectory return a stat and writeFile does not?

Fixed, now only `stat` returns `FileStat` and other operations return nothing.

**Comment by dbaeumer** [comment]
Marking as verified. Joh and I went over the API yesterday again in a review session.
