### ISSUE TITLE
Custom views sizes are not retained after refresh

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#48533]
Testing #48429

![kapture 2018-04-24 at 12 53 09](https://user-images.githubusercontent.com/10746682/39182852-7c914f4e-47be-11e8-975a-3b985a8d2a16.gif)

**Comment by joaomoreno** [comment]
@sandy081 I knew you'd file this! 😀 

It's much harder here because the user might have 2 scm repositories selected. On reload, that selection goes away. But we can do something.

**Comment by joaomoreno** [comment]
Merging with #35036
