### ISSUE TITLE
printf debug output is not shown in C gdb debug

### ISSUE THREAD

**Issue by fboerman** [Microsoft/vscode#48531]
### Issue Type
Bug

### Description

I created a small test project in C with 2 printf statements then I created a debug config with this:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "gdb",
            "request": "launch",
            "target": "./GOL",
            "cwd": "${workspaceRoot}",
        }
    ]
}
```

now I can break in the program when running the debugger. However the printf is never shown anywhere. The output shows nothing both in debug console as in all other views.

### VS Code Info

VS Code version: Code - OSS 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-12T09:43:38.180Z)
OS version: Linux x64 4.16.3-1-ARCH

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.16.1
debug|web|0.22.0

</details>
Reproduces only with extensions

**Comment by weinand** [comment]
Please file this issue against the cpptools extension (VS Code has no built-in C support).
