### ISSUE TITLE
npm explorer does not list all scripts

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#48537]
testing #48354:

- open npm scripts explorer on package.json file of node-debug

Observe: not all scripts are shown:

![2018-04-24_14-01-16](https://user-images.githubusercontent.com/1898161/39185622-1f306358-47c8-11e8-9bf6-b77e1f57396e.png)

I don't know who does the filtering and why, but as long as there is no explanation what is being filtered, I'm getting somewhat suspicious...

**Comment by egamma** [comment]
This is intentional, the taskprovider filters out pre/post scripts since they are always run as part of other scripts and it doesn´t make sense to run them individually.

**Comment by weinand** [comment]
@egamma here is a counter-example from today's testpass:

For testing latest VS Code vscode.d.ts I had to run the `postinstall` script which was missing from the explorer:

![2018-04-24_22-21-37](https://user-images.githubusercontent.com/1898161/39212185-4333ad64-480e-11e8-850d-f9b1125544f6.png)

**Comment by blopez2010** [comment]
I have another example in latest VS Code, `test` script is missing from the explorer:

![image](https://user-images.githubusercontent.com/15872584/39925348-8700a3da-54e8-11e8-941f-786351a9b572.png)

**Comment by egamma** [comment]
@blopez2010 I assume your test tasks has an associated problem matcher. Then this is a duplicate of #48831

**Comment by egamma** [comment]
@weinand changed the treatment of pre/post scripts given your use case. The pre/post scripts are no longer filtered but they are rendered in an de-emphasized way so that you can still navigate to them and run them.

![image](https://user-images.githubusercontent.com/172399/40063397-82db5b24-585d-11e8-9b90-01d0755fc196.png)
