### ISSUE TITLE
Consider to use modal alerts instead of error notifications

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#48538]
testing #48354:

- open NPM Scripts explorer
- select an arbitrary script that is not meant for debugging
- run "Debug" from context menu  

Observe:
This error alert appears:
![2018-04-24_14-07-26](https://user-images.githubusercontent.com/1898161/39186030-73c18720-47c9-11e8-834a-68f7f57ae7ae.png)

On my large screen I missed this and wondered what was happening...

Since running the "Debug" action is initiated by the user, I suggest to use a modal alert that jumps into the user's face instead of "hiding" a notification in a corner.

**Comment by egamma** [comment]
Agreed that an alert would be better. However, Alerts currently do not have support for links.
