### ISSUE TITLE
Could not debug scripts tags in Web Views.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#48548]
I tried to debug script tags in Web View but the script tags don't show up in the sources tab

![capture](https://user-images.githubusercontent.com/1931590/39189268-1fd04ff8-47d2-11e8-92d3-daf3ed631403.png)

**Comment by mjbvz** [comment]
This is a chrome/electron limitation. On first load, inline scripts are not loaded in to the developer tools sources. I believe external scripts are properly loaded
