### ISSUE TITLE
Merge editor.largeFileSize and editor.largeFileLineCount

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#48546]
As @isidorn points out in https://github.com/Microsoft/vscode/issues/44986#issuecomment-383912403, most likely people will want to turn off the limitations, and giving a value is more or less meaningless...

We could have a single setting called `editor.largeFileOptimizations` and turn it to false. @isidorn any better ideas for the setting name ?

**Comment by isidorn** [comment]
I like that setting name, I would in the hover describe the idea and warn the user that changing the default behavior could lead to vscode being unresponsive when opneing large files.

**Comment by alexandrudima** [comment]
There is now a single setting called `editor.largeFileOptimizations` with the following description: "Special handling for large files to disable certain memory intensive features".
