### ISSUE TITLE
Import language extension message

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48549]
Testing #48413

![image](https://user-images.githubusercontent.com/22350/39189054-99fe0e06-47d1-11e8-95a5-902db0ddbf3a.png)

The article `the` is missing twice in the first sentence. Also, it would be better to swap the two phrases, in order to understand better the motivation behind this notification. Like so:

> In the near future, VS Code will only support language packs in the form of Marketplace extensions. Please install **the** 'German Language Pack for Visual Studio Code' extension in order to continue to use **the** currently configured language.

**Comment by sandy081** [comment]
Thanks @joaomoreno for the nice suggestion
