### ISSUE TITLE
Activity bar is rendered when a non-existent icon is used

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#48555]
testing https://github.com/Microsoft/vscode/issues/48407

```
"contributes": {
	"viewsContainers": {
		"activitybar": [
                        {
			    "id": "test",
			    "title": "Test",
			     "icon": "resources/test.svg"
		        }
                  ]
	}
}
````
1. Removing the ```icon``` property shows the following error notification:
```
property `icon` is mandatory and must be of type `string`
```

2. ```"icon": "somethingRandom"```, results in no error notification and there is an invisible activity bar that works as if there was an icon. The console shows ```GET file:///C:/vscode_projects/testplanItemsApril/test-view-containers--48407/ net::ERR_FILE_NOT_FOUND```

![viewwithouticon](https://user-images.githubusercontent.com/15158320/39190332-adb36114-47d4-11e8-8c61-ed4fa20619f4.gif)

I'm not sure if it makes sense to render an activity bar in the second case and maybe it should also show an error notification like in the first one.

**Comment by sandy081** [comment]
Yes & No. I think most of our contributions that need icons assume that icon exists. If icon does not exist, then an issue should be filed against extension.

**Comment by fabiospampinato** [comment]
I just stumbled into this, it would be nice if VSC saved us time warning us about a non-existent icon.
