### ISSUE TITLE
[ Feature Request ] Tree view navigation improvement

### ISSUE THREAD

**Issue by Aetherall** [Microsoft/vscode#48558]
Hello everyone !

It would be super usefull to be able to `zoom` in the tree view.
And by zoom I mean "change the tree view root to a subfolder"

Let's say I am working on a big (deep) project architecture

![image](https://user-images.githubusercontent.com/13298494/39191344-0c5d4e08-47d7-11e8-8432-9d7f565a7a1c.png)

Then I double click on `app` and the tree view "navigates" to this folder

![image](https://user-images.githubusercontent.com/13298494/39191579-8644bc56-47d7-11e8-92ea-066cdede41e4.png)

The title should show `SE3 > app` and I should be able to click on SE3 to move up to SE3 as root

This could come with many other features, such as intellisense prioritizing the imports from the current subtree

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28905
