### ISSUE TITLE
Npm scripts explorer: cannot debug node versions < 8.0

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#48552]
testing #48354:

- use `nvm which 7.10.1` to find the path to a node executable of a pre-8.0 version of node
- create an npm script that uses this version of node, e.g.
   `"debug": "/Users/weinand/.nvm/versions/node/v7.10.1/bin/node --debug-brk hello.js"`
- in npm script explorer select the new script and run the context menu action "Debug" on it

Observe: debugger times out after 10 seconds. 

I've debugged this on the VS Code side and the problem is a missing `"protocol": "legacy"` attribute in the launch config passed to `vscode.debug.startDebugging`. Without that the debugger assumes the "inspector" protocol.

I suggest to always pass the `"protocol"` attribute. Use a value of `"inspector"` when detecting a "inspect" option and a value of `"legacy"` when detecting a "debug" option in the npm script.

**Comment by egamma** [comment]
@thanks for tracking this down!
