### ISSUE TITLE
Auto updater log should contain version information

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48565]

**Comment by roblourens** [comment]
Whereabouts is this log?

**Comment by joaomoreno** [comment]
Sorry @roblourens!

Verifier, please do a code review: https://github.com/Microsoft/inno-updater/commit/f23e651cd34b43c3611b379e92bd671cd21f364d

If you get an insider update meanwhile, you can check the log file `%TEMP%\ vscode-inno-updater.log `.
