### ISSUE TITLE
Add when clause for when file exists in workspace

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#48569]
I am working on an extension for a specific project type, where a file with a specific name will always exists in the workspace for that project. I am adding some buttons to the ` editor/title` menu, and it would be nice if I could make the buttons only show up if that specific file exists in the workspace. Looking through the documentation, I can't find a when clause for this, but I have a feeling one already exists, and is just not documented.

**Comment by jrieken** [comment]
Marking as out of scope since this is very specific, however you can implement this using the `setContext`-command, file events, and the vscode.workspace.fs API.
