### ISSUE TITLE
Moving views on linux: Tooltip too wide

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#48568]
testing #48407

Testing on a Ubuntu 16.04 LTS VM:
![movingiconslinux](https://user-images.githubusercontent.com/15158320/39200860-9c0a229a-47ed-11e8-80b2-9e43ad16b844.gif)

**Comment by sandy081** [comment]
@joaomoreno Guess this is not a regression. Moving this to next milestone.

**Comment by joaomoreno** [comment]
I'd just merge this with #48567 and get a proper hover feedback, like the one in the explorer.
