### ISSUE TITLE
VScode dosen't show ESP hardware

### ISSUE THREAD

**Issue by MHz000** [Microsoft/vscode#48561]
Issue Type: <b>Bug</b>

Newbie trys to setup VS code to support ESP's in arduinos IDE. VSc doesn't find the #include <ESP8266WiFiMulti.h>  file and no ESP hardware can be selected just AVR's.
setting.jsons contain: "arduino.additionalUrls":  "http://arduino.esp8266.com/stable/package_esp8266com_index.json",
What is wrong, what is missig in my settings?
Thank-you

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz (4 x 2208)|
|Memory (System)|7.89GB (4.06GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.16.1
vscode-arduino|vsc|0.2.12

</details>

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
