### ISSUE TITLE
Moving View Containers: visual indicator might improve UX

### ISSUE THREAD

**Issue by tsalinger** [microsoft/vscode#48567]
testing #48407

Just a nitbit but I'm used to the following type of UX when reordering items:
![movingiconsvlc](https://user-images.githubusercontent.com/15158320/39199403-a9489bd4-47e9-11e8-9284-19862dc07672.gif)

The current implementation feels more like moving one view into the other instead of above or below it.
![movingiconsvscode](https://user-images.githubusercontent.com/15158320/39199475-d23fc652-47e9-11e8-9013-887f80a8ee7b.gif)

A border-top or border-bottom on the destination item (similar to gif 1) might improve the experience.

**Comment by sandy081** [comment]
@joaomoreno Not sure if there a FR already for DnD feedback

**Comment by joaomoreno** [comment]
@sandy081 Don't think there is. 👍

**Comment by sandy081** [comment]
@joaomoreno Assigning to you as it seems split view related.

**Comment by joaomoreno** [comment]
I believe @sbatten and @misolori should own this. Splitview is a widget. This is about feedback on view panes.

**Comment by sbatten** [comment]
my DnD changes from the view movement work already address this.
