### ISSUE TITLE
Integrated terminal doesn't handle fontSize change well

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/vscode#48564]
Issue Type: <b>Bug</b>

### Expected
Given an open integrated terminal and a setting of `"terminal.integrated.fontSize": 12`

When changing `"terminal.integrated.fontSize"` to `13` and saving

Then the prompt text should still be visible

### Actual
The prompt is pushed outside the viewport and there is no way to make it visible again other than dismissing and reopening the integrated terminal.

<img width="574" alt="screenshot 2018-04-24 16 37 21" src="https://user-images.githubusercontent.com/406937/39194529-40855e62-47de-11e8-9d0e-9564a295954c.png">

VS Code version: Code - Insiders 1.23.0-insider (f4b63ac06955bd1ea220b851a79bd0ae5315fb0c, 2018-04-23T14:02:40.433Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 10, 7|
|Memory (System)|16.00GB (0.49GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mocha|Com|0.1.1
vscode-markdownlint|Dav|0.15.0
EditorConfig|Edi|0.12.1
cql|Law|0.8.7
vscode-docker|Pet|0.0.26
code-settings-sync|Sha|2.9.0
vscode-base64|ada|0.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
vscode-npm-source|dku|1.0.0
docs-authoring-pack|doc|0.0.1
docs-markdown|doc|0.0.1
gitlens|eam|8.2.4
ts-tslint|eg2|0.0.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
code-runner|for|0.9.3
ReplaceWithNewline|jma|0.0.1
docthis|joe|0.6.0
haml|kar|1.1.0
vscode-scss|mrm|0.6.2
vscode-azureappservice|ms-|0.7.1
vscode-azurefunctions|ms-|0.8.1
vscode-azurestorage|ms-|0.3.0
vscode-cosmosdb|ms-|0.6.0
DocFX|ms-|0.1.3
mssql|ms-|1.3.1
python|ms-|2018.3.1
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
vscode-node-azure-pack|ms-|0.0.2
vsliveshare|ms-|0.2.405
team|ms-|1.133.0
azurerm-vscode-tools|msa|0.4.0
debugger-for-chrome|msj|4.3.0
color-highlight|nau|2.3.0
project-snippets|reb|0.5.0
Ruby|reb|0.18.0
vscode-yaml|red|0.0.11
vscode-sort-json|ric|1.11.0
vscode-icons|rob|7.22.0
vscode-hexdump|sle|1.6.0
code-spell-checker|str|1.6.9
code-spell-checker-german|str|0.1.2
vscode-todo-highlight|way|0.5.12
change-case|wma|1.0.0

(4 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This broke at some point, pretty sure it used to work.

**Comment by lumaxis** [comment]
@Tyriar I can still very easily reproduce this:

![terminal font size issue](https://user-images.githubusercontent.com/406937/45487385-74409b00-b75e-11e8-9dd3-e74bab445c58.gif)

**Comment by Tyriar** [comment]
@lumaxis the issue with rows appearing cut off appears to be fixed. I think that gif will be explored in https://github.com/Microsoft/vscode/issues/58159
