### ISSUE TITLE
Remember custom height set for source control panels

### ISSUE THREAD

**Issue by kspearrin** [Microsoft/vscode#48566]
- VSCode Version: 1.22.2
- OS Version: Window 10

```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Steps to Reproduce:

1. Open source control sidebar.
2. Adjust height of panels.
3. Restart VS code and go back to source control.
4. Height of panels is not remembered.

Working with a workspace with lots of projects, I would like to keep my settings remembered here so that I can see all of my projects. Ex:

![image](https://user-images.githubusercontent.com/1190944/39196787-f5c5176e-47b0-11e8-905b-6641df35b1ec.png)

Instead it goes back to the default every time, which is small.

![image](https://user-images.githubusercontent.com/1190944/39196930-4b2e04ea-47b1-11e8-8260-428034d51045.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Merging with #35036
