### ISSUE TITLE
Glob patterns in problems view filter with ** not working as expected

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#48577]
Issue Type: <b>Bug</b>

Testing #48390

Steps to repro:
1. Generate a problem in a `.ts` file
2. Enter `**/*.ts` in the problems view filter

Expected the problem to be filtered out, but it isn't. However, the pattern `**\*.ts` does work.

VS Code version: Code - Insiders 1.23.0-insider (b845ce918f2689344795e845ae6ef691916c3079, 2018-04-24T05:10:57.500Z)
OS version: Darwin x64 17.4.0

**Comment by sandy081** [comment]
@RMacfarlane `**/*.ts` matches `.ts` files, hence it is shown. To exclude (filter out) you should use `!**/*.ts`
