### ISSUE TITLE
Entering '*' in problems view filter box causes all problems to be highlighted

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#48575]
Issue Type: <b>Bug</b>

Testing #48390
![highlighted](https://user-images.githubusercontent.com/3672607/39203383-7474a578-47a9-11e8-8fdf-caa8d209c28c.gif)

VS Code version: Code - Insiders 1.23.0-insider (b845ce918f2689344795e845ae6ef691916c3079, 2018-04-24T05:10:57.500Z)
OS version: Darwin x64 17.4.0

**Comment by sandy081** [comment]
Nobody complained, and its the same behaviour in other places too.

Closing as will not fix
