### ISSUE TITLE
Integrated terminal does not see Node from NVM

### ISSUE THREAD

**Issue by tyrsius** [Microsoft/vscode#48576]
- VSCode Version: 1.22.2 (1.22.2)
- OS Version: 10.12.6 (16G1314)

After installing NVM and uninstalling node from homebrew my OS terminal is working normally, but the VS code terminal does not see node.

I am using this setting, but disabling it doesn't fix the issue
```
"terminal.integrated.shellArgs.osx": [
    "-l"
  ]
```

**OS Terminal**
```
$ which node
/Users/tkye/.nvm/versions/node/v8.11.1/bin/node

$ node -v
v8.11.1
```

**VS Code Terminal**
```
$ which node
(nothing)

node -v
bash: node: command not found
```

My `.bashrc` contains this
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

I have run `nvm alias default lts/carbon` in both terminals, the command works. If I run `nvm use node` in the VS code terminal node will work for that session, but new shells are still missing node. Its like VS Code never loads nvm.

Clearly VS Code is remembering the homebrew node installation, but I don't know how. Its not in the `bash_profile` or `bashrc`, and the nvm stuff IS in there. Where else does VS Code load this from? Where else does VS code differ from the OS shell?

**Comment by tyrsius** [comment]
Sorry code bot, but that issue has nothing in it.

**Comment by raulcesar** [comment]
I too am having this issue. 
VS code Version 1.22.2
OS Version: Arch Linux (4.16.3-1-ARCH)
Also, just to complement tyrsius comment, in my case, if I source my .bashrc file (inside vs code terminal), it picks up NVM for that session, so it seems like the VS Code terminal ignores .bashrc at startup

**Comment by Tyriar** [comment]
This is the default setting on mac:

```
"terminal.integrated.shellArgs.osx": [
    "-l"
  ]
```

It means basg_profile will run, not bashrc. Does changing it to `[]` fix the problem?

**Comment by sandangel** [comment]
@Tyriar  I confirm that changing to [] fix this issue

**Comment by Tyriar** [comment]
@raulcesar I just wrote an FAQ on the prefix issue, check it out here for the proper way to fix: https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md#why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched

**Comment by harveyramer** [comment]
@Tyriar that completely resolved my nvm/vscode issues. Thank you!
