### ISSUE TITLE
Missing settings warning when offline

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#48572]
Testing #48391

- Install the beautify extension
- Create an extension with an "application" scope setting, following #48391
- Go offline
- Set that setting in the workspace settings.json
- There is a warning that the beautify json schema can't be downloaded, but no warning about the application scoped setting

If you disable the beautify extension, then the warning is shown properly even when offline. So it seems like the other missing schema is interfering even though it shouldn't matter for this case.

**Comment by sandy081** [comment]
@aeschli Known?

**Comment by aeschli** [comment]
Looks like a bug in the beautify extension.
It uses a external ref in the schema: https://github.com/HookyQR/VSCodeBeautify/blob/63b6a2261efc07af7dd7e9df6920f499da54f97c/package.json#L51

**Comment by aeschli** [comment]
This issue was moved to HookyQR/VSCodeBeautify#229
