### ISSUE TITLE
Allow to configure files.autoSave per workspace folder

### ISSUE THREAD

**Issue by alansferreira** [Microsoft/vscode#48579]
It would be nice if you had a setting for 'auto-save', for specific folders.

Because some technologies like Angular and React-Native, which use 'hot reload', have synchronization problems when auto-save is enabled and forces reloading, so I would like to disable them only for those specific folders.

Thanks, visual studio code team !!

This is the best tool I've ever used for development!

**Comment by cedric05** [comment]
i want to work on it. any recommendations where to start?

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/42170
