### ISSUE TITLE
New view containers api has inconsistent naming 

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#48583]
Testing #48407 

The new `viewsContainers` contribution point has inconsistent naming. The expected name appears to be `viewsContainers` while in a couple places in the code (which gets surfaced to the users confusingly in the debug console) we use `viewsContainer`. This also permeates inconsistently through the schema interface name `viewsContainerSchema` and the localization labels within it: `....views.containers...`

**Comment by sandy081** [comment]
@sbatten Good finding.

Regarding schema `viewsContainerSchema` - it is for single viewsContainer hence it is named like that. There is also schema for `viewsContainers while internally refers to `viewsContainerSchema`.
