### ISSUE TITLE
Source action context menu feels weird

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#48589]
#48455

It's essentially an overflow menu inside a context menu but it's worse as it needs a click and to then move the mouse to the new menu. Why don't we open a quick pick with the source actions instead?

**Comment by mjbvz** [comment]
Any opinion on this one @jrieken? We don't support sub context menus but using a quick pick would be doable.

I personally like the context menu does because it shows in the document and I often miss quick picks that appear at the top of the screen

**Comment by jrieken** [comment]
I'd say this will be much nicer once we have support for submenus. Also, Format should go in there

**Comment by justschen** [comment]
this one is pretty old but we've had conversation on this with the action list menu. i think the general consensus was that we decided not to do flyouts/submenus
