### ISSUE TITLE
Find All Bug

### ISSUE THREAD

**Issue by miking-the-viking** [Microsoft/vscode#48587]
Issue Type: <b>Bug</b>

Recently the find (ctrl + shift + f) has stopped returning any results.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (3.19GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_45067|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
compulim-vscode-closetag|Com|1.1.0
vscode-markdownlint|Dav|0.15.0
beautify|Hoo|1.3.0
cql|Law|0.8.7
material-icon-theme|PKi|3.3.0
vscode-docker|Pet|0.0.26
code-settings-sync|Sha|2.9.0
quokka-vscode|Wal|1.0.121
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
vscode-database|baj|1.5.1
npm-intellisense|chr|1.3.0
laravel-blade|cjh|1.1.2
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
php-pack|fel|1.0.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
phpcs|ika|1.0.5
vscode-insertdatestring|jsy|2.2.2
php-cs-fixer|jun|0.1.62
php-symbols|lin|2.1.0
dotenv|mik|1.0.1
mssql|ms-|1.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
sublime-keybindings|ms-|3.0.3
vsliveshare|ms-|0.2.405
team|ms-|1.133.0
debugger-for-chrome|msj|4.3.0
php-docblocker|nei|1.6.0
vetur|oct|0.11.7
laravel-blade|one|1.18.0
vscode-code-outline|pat|0.1.1
vscode-icons|rob|7.22.0
laravel-5-snippets|sac|2.0.1
vue-vscode-snippets|sdr|1.3.0
autoimport|ste|1.5.3
pdf|tom|0.2.0
JavaScriptSnippets|xab|1.6.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@miking-the-viking can you please provide more info of your setup and what you do

**Comment by miking-the-viking** [comment]
I am working on a large project and was trying to find all instances of the word _sensor_ within the project. Using the Find All feature (not excluding any files) I attempted the search, however no results were returned. It seems to be a sporadic issue, today when I attempt it I'm getting a couple results (far from all of them) from the first folder in the project, but nothing from subsequent folders/files.

**Comment by roblourens** [comment]
- Are the missing results covered by a .gitignore or pattern from `search.exclude` or `files.exclude`?
- Does it happen in every folder, or just one particular folder?
