### ISSUE TITLE
Views contributed to containers that don't exist don't error

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#48582]
Testing #48407 

When an extension authors a new view and adds it to a non-existent view container, no error is logged. Instead they are just added to the Explorer view container.

**Comment by sandy081** [comment]
Following warning will be shown in such cases

`View container 'id' does not exist and all views registered to it will be added to 'Explorer'.`

**Comment by mjbvz** [comment]
I still see this behavior in 6d7bb1a174f588360366af26a2ec8f27064ca110

For the contributions:

```
"contributes": {
    "views": {
      "nonesuch": [
        {
          "id": "myview",
          "name": "My View"
        }
      ]
    }
  },
```

no error and the view is added to the explorer: 

<img width="568" alt="screen shot 2018-04-26 at 7 57 01 pm" src="https://user-images.githubusercontent.com/12821956/39342265-0b478f22-498c-11e8-8c5f-f0024bb184d6.png">

**Comment by sandy081** [comment]
@mjbvz Warning is shown in the console as it is meant for extension authors.
