### ISSUE TITLE
Expose / Copy path to user settings file

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/vscode#48581]
Issue Type: <b>Feature Request</b>

Related to https://github.com/Microsoft/vscode/issues/43082, which would be the ideal implementation. If that can't happen, at least provide a way to easily copy the path to the user settings file, so that I can manually replace it with a cloud shared one. For example, you could add a right click context menu on the user settings tab to copy the path, just like you have one for normal editor tabs.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

**Comment by sandy081** [comment]
@cdmihai This is already supported

![image](https://user-images.githubusercontent.com/10746682/39258547-869d479e-48b4-11e8-83bb-24e4640aef48.png)

**Comment by cdmihai** [comment]
@sandy081 Oh, I see. I hadn't noticed the topmost tab, just the inner one (the one left to workspace settings). Sorry about that :)
