### ISSUE TITLE
onDidChangeDiagnostics throws error

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#48591]
Testing #48411

When using the `vscode.languages.onDidChangeDiagnostics`, I see the below error.

![image](https://user-images.githubusercontent.com/16890566/39207183-31805176-47b4-11e8-8e26-700fe218cd9f.png)

I am testing using a sample extension in dev mode (i.e F5 on the extension's code)

This doesnt happen when using `vscode.languages.getDiagnostics` in the absence of  `vscode.languages.onDidChangeDiagnostics`

**Comment by ramya-rao-a** [comment]
Since `onDidChangeDiagnostics` is available in the `vscode.d.ts` it is no longer in "proposed state" and should be available for use.

**Comment by jrieken** [comment]
Thanks @mjbvz
