### ISSUE TITLE
Bépo: Can't type AltGr + Space when completion suggestion is displayed 

### ISSUE THREAD

**Issue by Geobert** [Microsoft/vscode#48598]
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows 10 64bits

Steps to Reproduce:

1. trigger a smart completion with Ctrl+Space
2. try to type AltGr+Space, nothing happen

I'm reporting this because I'm using a keyboard layout called bépo and underscore is on AltGr+Space and it's quite annoying to not be able to type underscore while completion is suggesting.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@Geobert <kbd>AltGr</kbd>+<kbd>Space</kbd> reaches us in the form of <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Space</kbd>. This is unfortunately a decision done before my time so I cannot comment to its correctness:
https://en.wikipedia.org/wiki/AltGr_key#Control_+_Alt_as_a_substitute

![image](https://user-images.githubusercontent.com/5047891/39237722-942a1dca-487c-11e8-9fe2-b84ac00c9c96.png)

Anyways, out of the box we ship with a keybinding associated to <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Space</kbd>:
![image](https://user-images.githubusercontent.com/5047891/39237757-ac7a870c-487c-11e8-85e4-96f304d674d7.png)

This works for all the other keyboard layouts AFAIK and is the first time I hear it is breaking one, namely bépo.

Anyways, the good news is that you can remove or change this built-in keybinding. In fact, you can change any of the built-in keybindings. Here is the documentation for how to do that: https://code.visualstudio.com/docs/getstarted/keybindings .

One can argue that we should ship by default with keybindings which work out-of-the-box perfectly even in bépo. This is something we are tracking in #1240

**Comment by Geobert** [comment]
Thank you!
