### ISSUE TITLE
Why are createWebviewPanel options mandatory param when it can be {}

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#48594]
#48453

We should be able to safely make this an optional param?

**Comment by mjbvz** [comment]
Couldn't come up with a compelling API reason why it should be optional (or why it shouldn't be), so let's just keep it as is

**Comment by Tyriar** [comment]
Because it seems like it would be more consistent making it optional than not:

https://github.com/Microsoft/vscode/blob/ee36a84ff1abb0b8bc7509f651b0d97a734cd14c/src/vs/vscode.d.ts#L1118

https://github.com/Microsoft/vscode/blob/ee36a84ff1abb0b8bc7509f651b0d97a734cd14c/src/vs/vscode.d.ts#L1131

https://github.com/Microsoft/vscode/blob/ee36a84ff1abb0b8bc7509f651b0d97a734cd14c/src/vs/vscode.d.ts#L4511

https://github.com/Microsoft/vscode/blob/ee36a84ff1abb0b8bc7509f651b0d97a734cd14c/src/vs/vscode.d.ts#L4520

https://github.com/Microsoft/vscode/blob/ee36a84ff1abb0b8bc7509f651b0d97a734cd14c/src/vs/vscode.d.ts#L4657

https://github.com/Microsoft/vscode/blob/ee36a84ff1abb0b8bc7509f651b0d97a734cd14c/src/vs/vscode.d.ts#L4669

https://github.com/Microsoft/vscode/blob/ee36a84ff1abb0b8bc7509f651b0d97a734cd14c/src/vs/vscode.d.ts#L5481

https://github.com/Microsoft/vscode/blob/ee36a84ff1abb0b8bc7509f651b0d97a734cd14c/src/vs/vscode.d.ts#L5492

There are places where options are mandatory when all the properties are optional like this:

https://github.com/Microsoft/vscode/blob/ee36a84ff1abb0b8bc7509f651b0d97a734cd14c/src/vs/vscode.d.ts#L5500

But it doesn't make much sense to use `{}` here.
