### ISSUE TITLE
Can't run vscode-website npm scripts

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#48590]
- VSCode Version: 1.23.0 Insiders
- OS Version: Windows 10

Found will testing https://github.com/Microsoft/vscode/issues/48354

Steps to Reproduce:

1. Clone the vscode-website repo and follow setup instructions in README.md
2. Enable npm script explorer and correctly see all 6 scripts from package.json.
3. Try to Run the "start" script

You see a notification "The process task system can only execute custom tasks" and the script isn't not run. All 6 scripts can not be started.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
The project contains a task.json and has customized tasks. Without the task customization the error cannot be reproduced.

**Comment by egamma** [comment]
Changed the task fetching so that that is now done using the tasks API, this avoids the error, but since taskProviders do not work with task 1.0, the npmScripts view will be empty. Nothing I can do for now to improve this.
