### ISSUE TITLE
Getting "command not found" error in my extension despite having the onCommand activation event

### ISSUE THREAD

**Issue by markvincze** [Microsoft/vscode#48605]
- VSCode Version: 1.22.2
- OS Version: Win10 64 bit

Steps to Reproduce:

1. Start VSCode with [this extension](https://github.com/markvincze/vscode-codeFragments) (either by installing it from the marketplace, or with the debugger) **with the Explorer view being hidden**.
2. Create a new file, type some text and select it.
3. Try to save it as a Code Fragment with the extension by opening the Command Palette and executing the "Save selection as Code Fragment" command

It won't work, the following error will be displayed: `command 'codeFragments.saveSelectedCodeFragment' not found`.

In my extension I have the following activation events:

```
    "activationEvents": [
        "onCommand:saveSelectedCodeFragment",
        "onView:codeFragments"
    ],
```

I expect the first one to prevent this problem, so that it should make sure that the extension is activated when that command is executed.  
With some experimentation I noticed that if I also add `"*"` as an activation event, then the issue goes away. But is that the proper way? I don't necessarily want to load my extension on startup, it'd be enough to be activated the first time this command is executed.  
Is this the expected behavior, or a bug?

In either case, I think the [documentation](https://code.visualstudio.com/docs/extensionAPI/activation-events#_activationeventsoncommand) should be clarified, because it's unclear whether the `onCommand`  event should be enough in this case or not.

**Comment by jrieken** [comment]
Your `activate`-function returns *before* having registered the commands: https://github.com/markvincze/vscode-codeFragments/blob/7b6e3eda9f5d23de4cd3c63cc8f6c7ad695e9d5a/src/extension.ts#L154. Instead you should either register them before returning or return a promise that resolves when registration is done.
