### ISSUE TITLE
Should experimental and nonstandard CSS properties have warning icon next to Read More icon?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#48601]
Users may not have the Read More flyout open while editing and might miss experimental and nonstandard warnings. Should the warning triangle and red siren icon be also shown next to the Read More blue icon?

Found during testing https://github.com/Microsoft/vscode/issues/48443

**Comment by octref** [comment]
I've pulled it out because we have some concerns for the too bright emojis. Need to reconsider the UX.

**Comment by octref** [comment]
Actually because many people use transpilers, these warnings won't be accurate. Let's forget about this then.
