### ISSUE TITLE
ProtocolHandler redirect dialog should give some different messaging if the extension does not exist

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#48608]
Testing #48427 on Windows

If a user opens vs code with an extension uri that is expected to handle it and the extension is either not installed or disabled, the redirect message shouldn't pretend that clicking 'yes' will do something. Instead, we should either direct them to the extension in the marketplace or how to install it. Or in the case that this extension does not exist in the marketplace, express that clearly.

**Comment by joaomoreno** [comment]
What we'll do here is just not handle messages for unknown extension IDs in each window.

**Comment by chrmarti** [comment]
Verified that nothing happens.
