### ISSUE TITLE
Inconsistent layout of debug title

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#48603]
Issue Type: <b>Bug</b>

Notice the different length of the debug target's title. I think it should be the same length and left aligned regardless of the target's description:

![image](https://user-images.githubusercontent.com/4033249/39213517-a841e358-47c6-11e8-8898-70b38eae056d.png)

VS Code version: Code - Insiders 1.23.0-insider (b845ce918f2689344795e845ae6ef691916c3079, 2018-04-24T05:10:57.500Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (1.81GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1388883|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.0.1
vscode-docker|Pet|0.0.26
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.2
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
theme-monokai-pro-vscode|mon|1.1.6
vscode-scss|mrm|0.6.2
vscode-azurefunctions|ms-|0.8.1
python|ms-|2018.3.1
azure-account|ms-|0.4.0
cpptools|ms-|0.16.1
PowerShell|ms-|1.6.0
vsliveshare|ms-|0.2.405
debugger-for-chrome|msj|4.3.0
vetur|oct|0.11.7
polacode|pnp|0.2.2
java|red|0.23.0
vscode-csstree|sme|0.6.0
vim|vsc|0.11.5

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
As designed, it has the longest length of any of the options possible.
I feel like this is personal preferences, if it always had the same length I would get bugs the other way around (can not read the full title).
Thus closing as designed. Will reopen if more people find this bad.
