### ISSUE TITLE
retainContextWhenHidden should restore focus within the webview as well

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#48604]
#48453

Repro:

Create a webview with `retainContextWhenHidden: true` containing an `<input>`. Open the webview, add text to the webview and select it. Press ctrl+tab twice, notice the selection is there but the focus is not.

**Comment by mjbvz** [comment]
Focus should also be restored when just switching back to a visible webview from another editor group

**Comment by mjbvz** [comment]
As I thought about this more, I think we should leave this up to extensions actually. They have a much better understanding of how focus should be restored. I'm worried that existing extensions may already implement their own logic or that we would get the focus restoration wrong.

I'll open issues against the github PR extension to implement focus restoration
