### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by stang1013** [Microsoft/vscode#48613]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by stang1013** [comment]
Thanks Ben, I disabled couple angular extensions and get the problems fixed.

Best Regards
Steven
