### ISSUE TITLE
Problems view filter *.js includes json file

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#48610]
re #48390

* Search in Search Viewlet, filter results by `*.js`, no results from JSON files
* Filter in Problems Panel by `*.js`, results from JSON files are there.

**Comment by rebornix** [comment]
`**/*.js` filters out JSON file results successfully.

**Comment by sandy081** [comment]
@roblourens Works for me

![kapture 2018-07-24 at 12 39 30](https://user-images.githubusercontent.com/10746682/43133310-abb041c8-8f3e-11e8-9502-93b9564bfa0f.gif)
