### ISSUE TITLE
Issue reporter takes 7 seconds to render in Windows in latest Insiders

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#48617]
Issue Type: <b>Bug</b>

- Open the issue reporter 
- The window opens quickly but is blank
- Takes about 7 seconds to render anything in the Window

Happens only in the Insiders
Stable is fine

VS Code version: Code - Insiders 1.23.0-insider (b845ce918f2689344795e845ae6ef691916c3079, 2018-04-24T05:17:07.677Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (18.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by RMacfarlane** [comment]
With ebf9c8c730041c7fd1586ad8458e8a5c3b2d38fc, I updated the windows-process-tree package which now does the cpu usage calculation in a worker thread. The render time for the issue reporter is lower, more like 3 seconds, but still not as good as stable. Previously a separate process was spawned to list processes, so I think the time could still be improved by forking from main
