### ISSUE TITLE
Settings Sync extension does not have any effect?

### ISSUE THREAD

**Issue by carlocardella** [Microsoft/vscode#48615]
- VSCode Version:
Version 1.23.0-exploration
Commit 5e0fbe54562b6291114d1219f8bf5bbcb77af1b1
Date 2018-04-24T05:58:08.964Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

- OS Version:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299

Steps to Reproduce:
I use Settings Sync (Shan.code-settings-sync) to sync my settings and extensions across multiple machines: I can install Settings Sync and other extensions (for example Powershell) but downloading settings from my Gist seems to fail, no settings are actually updated and no extensions are installed through the sync process. 

Are extensions supposed to work out of the box with the new Electron?

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Yes, extensions should work with new Electron.

Please file a bug against the settings-sync extension
