### ISSUE TITLE
IntelliSense mismatch for package.json contributes.viewContainers

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#48629]
testing #48407

when authoring the `viewsContainers` contribution in `package.json`, IntelliSense shows `label` as a property to set, but when running I get an error saying `title` is required.  `title` does not show up in IntelliSense.

![image](https://user-images.githubusercontent.com/1487073/39223009-9c29e40c-47f4-11e8-89de-d328f6986bd2.png)

**Comment by sandy081** [comment]
Good catch.
