### ISSUE TITLE
php  $this->$someting

### ISSUE THREAD

**Issue by ichynul** [Microsoft/vscode#48628]
Issue Type: <b>Feature Request</b>

I need a warnning when I writing php code like this : $this->$someting.
`<?php`
`class A`
`{`
`        protected $user_id = 0;`
`        //...`
`        function b()`
`        {`
`               //...`
`               echo($this->$user_id);//wrong ,give a warnning`
`               echo($this->user_id);//right`
`        }`
`}`

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
So what's the warning?

Are you using a PHP extension?

**Comment by m-thorsen** [comment]
Although it's subjectively preferred to wrap "variable properties" in curly braces, **$object->$variableProperty** is still valid and probably shouldn't produce a warning.

**Comment by roblourens** [comment]
Re-reading it, I think you're right. I'll close this unless I'm wrong @ichynul

**Comment by ichynul** [comment]
@m-thorsen  @roblourens 
we usually defining a global variable in PHP like this: 
`protected $fieldname`
but using it with "this" keyword in local functions like that:
`$this->fieldname`
not `$this->$fieldname ` 
If added a "$" before filld name ,  this will make some unexpected errors ,and It's hard to find this in many code lines.
So if we write like `$this->$fieldname` in php ,it 99% cases is wrong, because we usually don't defining a global variable like that `protected $$fieldname` ,I had never write like that ,and don't know if it's ok in php.
Maybe a  PHP extension will fix it .

**Comment by roblourens** [comment]
It's still valid PHP. If you want a warning about it because it's not your preferred style, there might be a lint rule for that.

**Comment by ichynul** [comment]
ok thinks , I try  to learn about lint rule .

**Comment by ichynul** [comment]
I write a extension to check this .
![_20180501142301](https://user-images.githubusercontent.com/10061650/39463630-95326f78-4d4b-11e8-8a6b-14e6b8a89b51.png)
![_20180501142317](https://user-images.githubusercontent.com/10061650/39463631-96647116-4d4b-11e8-85ae-ba6b7a5b6123.png)

**Comment by ichynul** [comment]
@m-thorsen ,thanks , I got it .
```php
class Test{
  public $name = "abc";
  public $abc = "test";

  public function Test(){
       $name1 = "name";
       echo $this->name;   //  abc
       echo $this->$name1;  //  abc
       $name2 = $this->$name1;  
       echo $this->$name2;  // test
  }
}
