### ISSUE TITLE
Unable to attach to Node process

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/vscode#48620]
Issue Type: <b>Bug</b>

When starting a Node process with e.g.`node --inspect-brk node_modules/mocha/bin/_mocha` I can correctly see the debugger listeing in the terminal.

However, eventhough I have Auto Attach turned on, VS Code does not auto-attach to the process. Also, manually using `Debug: Attach to Node Process` and selecting the process results in an error. 

The exact same command on the exact same project works just fine on the current stable release.

<img width="471" alt="screenshot 2018-04-25 02 36 55" src="https://user-images.githubusercontent.com/406937/39220604-775802ec-4832-11e8-892b-c0783d68bf91.png">
<img width="810" alt="screenshot 2018-04-25 02 38 14" src="https://user-images.githubusercontent.com/406937/39220606-7b260dec-4832-11e8-8228-3c60e0eac872.png">

VS Code version: Code - Insiders 1.23.0-insider (b845ce918f2689344795e845ae6ef691916c3079, 2018-04-24T05:10:57.500Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|4%|

</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mocha|Com|0.1.1
vscode-markdownlint|Dav|0.15.0
EditorConfig|Edi|0.12.1
cql|Law|0.8.7
vscode-docker|Pet|0.0.26
code-settings-sync|Sha|2.9.0
vscode-base64|ada|0.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
vscode-npm-source|dku|1.0.0
docs-authoring-pack|doc|0.0.1
docs-markdown|doc|0.0.1
gitlens|eam|8.2.4
ts-tslint|eg2|0.0.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
code-runner|for|0.9.3
ReplaceWithNewline|jma|0.0.1
docthis|joe|0.6.0
haml|kar|1.1.0
vscode-scss|mrm|0.6.2
vscode-azureappservice|ms-|0.7.1
vscode-azurefunctions|ms-|0.8.1
vscode-azurestorage|ms-|0.3.0
vscode-cosmosdb|ms-|0.6.0
DocFX|ms-|0.1.3
mssql|ms-|1.3.1
python|ms-|2018.3.1
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
vscode-node-azure-pack|ms-|0.0.2
vsliveshare|ms-|0.2.405
team|ms-|1.133.0
azurerm-vscode-tools|msa|0.4.0
debugger-for-chrome|msj|4.3.0
color-highlight|nau|2.3.0
project-snippets|reb|0.5.0
Ruby|reb|0.18.0
vscode-yaml|red|0.0.11
vscode-sort-json|ric|1.11.0
vscode-icons|rob|7.22.0
vscode-hexdump|sle|1.6.0
code-spell-checker|str|1.6.9
code-spell-checker-german|str|0.1.2
vscode-todo-highlight|way|0.5.12
change-case|wma|1.0.0

(4 theme extensions excluded)

</details>

**Comment by weinand** [comment]
That was a temporary problem in Insiders. Fixed in latest Insiders.

**Comment by lumaxis** [comment]
Confirmed fixed, thanks @weinand!
