### ISSUE TITLE
Workbench picks up settings.json file at the top of the workspace

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#48627]
Issue Type: <b>Bug</b>

1. Open a project
2. Use Git: Pull command in the Command Palette 
The file icons disappeared and there is an error.
[renderer3.log](https://github.com/Microsoft/vscode/files/1945159/renderer3.log)

VS Code version: Code - Insiders 1.23.0-insider (b845ce918f2689344795e845ae6ef691916c3079, 2018-04-24T05:17:07.677Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
debugger-for-chrome|msj|4.3.0

</details>

**Comment by bpasero** [comment]
@shizengzhou can you share a screenshot how this looks like for you?

**Comment by joaomoreno** [comment]
The error in the log is #48523

@shizengzhou Yes, please share a screenshot.

**Comment by joaomoreno** [comment]
@bpasero Have you seen this before? I don't think this is related to git at all.

**Comment by bpasero** [comment]
@joaomoreno no this is news to me

/cc @aeschli @sandy081 

@shizengzhou can you make sure to reproduce with todays latest insider?

**Comment by shizengzhou** [comment]
@bpasero I'm sure to reproduce with todays latest insider.

**Comment by bpasero** [comment]
@shizengzhou are the icons coming back when you change the icon theme?

**Comment by shizengzhou** [comment]
@bpasero VS Code seems to treat the settings.json in the project as my settings.json by mistake.

**Comment by sandy081** [comment]
@shizengzhou You mean `settings.json` under `.vscode` folder? And does it has file icon theme setting?

**Comment by shizengzhou** [comment]
@sandy081 There is no` .vscode` folder. Yes, it has file icon theme setting.

**Comment by sandy081** [comment]
Yes, file icon theme in the workspace settings is overriding your theme in user settings which is expected.

**Comment by joaomoreno** [comment]
@sandy081 I just hit this too by accident, seems like a regression.

**Comment by joaomoreno** [comment]
Also, when that happens, changing a theme causes a `.vscode/settings.json` file to be created with that theme selection. 😕

**Comment by sandy081** [comment]
Yeah.. it is a regression from my refactorings. My relative checks were happening on root folder instead of `.vscode` folder and caused this.

@shizengzhou Thanks for reporting this.
