### ISSUE TITLE
Cloning with protected SSH key may or may not show an error dialog

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#48624]
Testing #48428.

I'm using SSH with a key that is passphrase protected for git operations. I didn't have VS Code running and tried to open` vscode-insiders://vscode.git/clone?url=git%40github.com%3AMicrosoft%2Fvscode-vsce.git`. I.e. the SSH key was still locked.

I'm correctly asked for permission and am promted for the folder. The cloning fails since the key is locked. I repeated this several times. I have a 50/50 chance of getting an error dialog. The git log always shows the error.

**Comment by joaomoreno** [comment]
How about simply using the command `Git: Clone`, do you also get that 50/50 chance of an error dialog? Can you show me the screenshot of the error you're getting as well as the git output of it?
