### ISSUE TITLE
Show disabled feedback when dragging views to other viewlets

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#48636]
It is possible to visually drag an explorer to another viewlet, but when you drop it, nothing happens.

open the debug viewlet
click, hold, and drag the `watch` explorer sash to the search viewlet icon on the activity bar and hold it there for a couple of seconds
the search viewlet will appear
drop the explorer on the search viewlet

result: nothing happens
expected: the explorer should be in the search viewlet

This is a little more interesting when dragging/dropping custom explorers. for example, dragging the docker explorer to another viewlet.

**Comment by isidorn** [comment]
@chrisdias it would be great if you assign the issue to the owner of the testplan so that the bot does not need to guess. Thanks

**Comment by sandy081** [comment]
I do not think we support moving views from one view container (activity bar entry) to another. We should show some feedback that it is not droppable.

**Comment by sandy081** [comment]
@sbatten Closing this as we support moving views across locations with feedback.
