### ISSUE TITLE
custom view contribution: what size icon to use?

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#48637]
testing #48407

what size, etc. icon is recommended?  i was expecting it to be scaled down to fit, but it looks like it should be about 25x25px.

![image](https://user-images.githubusercontent.com/1487073/39225506-a2ebe2a6-4801-11e8-9401-05c6ad9fbc28.png)

**Comment by sandy081** [comment]
Working with @misolori on the spec. Here is the sample

![image 2](https://user-images.githubusercontent.com/10746682/39230047-63b3a9ac-4865-11e8-862e-7766027e2816.png)
