### ISSUE TITLE
Fails to remove space on blank like on save

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#48631]
Issue Type: <b>Bug</b>

1. Press return to create a new line between lines of code.
1. Make sure new line is indented with spaces.
1. Save file.

![screenshot_20180424_223059](https://user-images.githubusercontent.com/439226/39223360-b17b8b60-480f-11e8-9590-c8c0fc1b2405.png)

Notice the empty line with space still have spaces.

VS Code version: Code - Insiders 1.23.0-insider (b845ce918f2689344795e845ae6ef691916c3079, 2018-04-24T05:12:06.211Z)
OS version: Linux x64 4.4.0-121-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (3 x 3013)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.80GB (1.25GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders /home/code/dev/docs/guides|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.15.0
EditorConfig|Edi|0.12.1
Angular-BeastCode|Mik|6.0.12
sort-lines|Tyr|1.6.1
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
geeks-ms|jor|0.0.1
sort-typescript-imports|mic|1.4.1
angular2-inline|nat|0.0.17
language-stylus|sys|1.9.1
better-align|wwm|1.1.6
markdown-pdf|yza|1.0.1

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@rajinder-yadav can you check if you have `editor.trimAutoWhitespace` set to `true` and you don't have extensions changing the format of the document when save?

**Comment by rajinder-yadav** [comment]
This seems to be working, I had to set "trim trailing whitespace" to true, thanks.

![image](https://user-images.githubusercontent.com/439226/45253051-9ab1a100-b32e-11e8-89b1-80c10692144b.png)
