### ISSUE TITLE
Sometimes won't react to touchpresses

### ISSUE THREAD

**Issue by carcigenicate** [Microsoft/vscode#4863]
- VSCode Version: 0.10.11
- OS Version: Windows 10 10586.164
- Surface Pro 4

Steps to Reproduce:

1. Install Code
2. Attempt to press anything using only a touchscreen.

I'm not entirely sure how to reproduce it. I downloaded Code yesterday to learn Typescript, and none of the buttons worked when I tried to use the touch screen, but worked if I used the touchpad or pen. I uninstalled it, because that's a dealbreaker, tried Visual Studio, but found it to be a little complicated just to mess around in, so I decided, what the hell, and re-installed Code. It now works fine.

**Comment by alexandrudima** [comment]
@carcigenicate This sounds like you might have hit a problem that went aways after a restart.

If you encounter this problem again, we would love to get some steps on how to reproduce.

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
