### ISSUE TITLE
debug: extension development: stop doesn't stop debugging (or does it?)

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#48633]
MacOS
Version 1.23.0-insider (1.23.0-insider)
b845ce918f2689344795e845ae6ef691916c3079

scaffold out a new TypeScript extension using `yo code`
load the workspace, press `F5`
the extension dev environment comes up as expected
now, close the ext dev environment by clicking the close (red button on mac) button

result: we are still in debug mode, or at least it appears to be, because the debug toolbar is still visible

press refresh on the debug toolbar

result: toolbar goes away, the extension dev host is not restarted

**Comment by weinand** [comment]
duplicate of #48442
