### ISSUE TITLE
Splitview: support scrolling when views take more space than available

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#48632]
testing #48407

When contributing a large number of explorers, at some point you cannot scroll to them.  for example, i created 20+ explorers:

![image](https://user-images.githubusercontent.com/1487073/39223318-48923676-47f6-11e8-9761-4eaff9d8eeb9.png)

When I start to expand each one, such that the extend pass the bottom of the viewlet, there is no scroll bar that would let me scroll down to see the explorers that are below the screen.

![image](https://user-images.githubusercontent.com/1487073/39223369-9eae8e9c-47f6-11e8-8a90-84fff6561e2a.png)

This isn't specific to #48407, the same thing happens if I contribute alot of explorers to the main explorer.

**Comment by sandy081** [comment]
Also adding @joaomoreno as this is related to split view.

**Comment by joaomoreno** [comment]
Splitview doesn't really support this, since there would be scrollbars within scrollbars... But we can think about it.
