### ISSUE TITLE
VSCode can not switch between vscode windows.

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#48646]
Windows 10 x64
vscode 1.22.2 x64

When we open more than one vscode window. I try to switch another vscode window. but the previous windows persist in front, so i failed to switch to other window.

**Comment by bpasero** [comment]
This sounds like an issue with your Windows installation and nothing VS Code can do about.

**Comment by netroby** [comment]
No, I means two vscode editor windows can not switch one to another.

**Comment by netroby** [comment]
ping @bpasero 

The problem exists. it's about vscode editor window. I can not switch between two or more vscode editor windows
