### ISSUE TITLE
Format Comments

### ISSUE THREAD

**Issue by Karlito88** [Microsoft/vscode#48647]
I have a problem. I want to comment a method it's called "change". The method contains a switch-case which I wanted to document. In this comment, I want **linebreaks** and tags like HTML <br> doesn't work. I need to create an empty line to archive a linebreak. The problem on this is that the comment explodes because this method gets a lot of variables. The Comment looks like

     /* This method gets the values and the select-param out of the template (*.html).
     * the select param is only a number that the method know what to do
     *
     * numbers:
     *
     * 1 = zoomButton
     *
     * 2 = zoomType (x,y,xy)
     *
     * '#' = Chart export
     *
     * @param {string} value value of the new propertie
     * @param {number} select number for choose the option
     */
private change(value: string, select: number): void {} 

And this is too long. 
Question: How to format Comments (with linebreaks or something)

Greetings KarL

**Comment by mjbvz** [comment]
Html is not supported in comments but markdown is. To add an explicit line break between two sequential lines, add a double space at the end where you want the break:

```
 /**
  * a  
  * b
  */
```

**Comment by Karlito88** [comment]
Thanks for the reply. 
Is there any documentation for formating comments?
