### ISSUE TITLE
Terminal can't start

### ISSUE THREAD

**Issue by kanonlemon** [Microsoft/vscode#48643]
Issue Type: <b>Bug</b>

i can't start CMD or PowerShell in Vscode, and these always hang, when i start a debug, it's also blocked

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|15.95GB (6.42GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
PowerShell|ms-|1.6.0

</details>

**Comment by weinand** [comment]
@kanonlemon Please provide detailed steps:
how do you start CMD or PowerShell in VS Code?
what do you mean by "when i start a debug, it's also blocked"?
