### ISSUE TITLE
Show SCM status of files in the editor title

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/vscode#48644]
- VSCode Version: 1.22.2
- OS Version: Windows 10

The title bar currently does not display files modified in git.
Is there an option to enable this, like in the working files section?

![vscode](https://user-images.githubusercontent.com/3099626/39232323-94412c64-488a-11e8-941d-c9f56e33484b.png)

**Comment by bpasero** [comment]
Actually duplicate of https://github.com/Microsoft/vscode/issues/47916
