### ISSUE TITLE
Wrong syntax Highlighting

### ISSUE THREAD

**Issue by Anjmao** [Microsoft/vscode#4864]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. open vs code
2. create typescript file with keywords like class

Here is how it should be, class with green color, return with pink
![image](https://cloud.githubusercontent.com/assets/3028012/14212988/36aeb4ca-f83e-11e5-85ba-d5094d0bd733.png)

Here is how it actual looks
![syntax](https://cloud.githubusercontent.com/assets/3028012/14213045/878eb688-f83e-11e5-8ecc-5c8b360733d7.png)

Almost every time I update vs code to newer version I get this problem.

**Comment by dbaeumer** [comment]
@aeschli can you please take this.

**Comment by aeschli** [comment]
@Anjmao What color theme are you on?
The 'sadFile.ts' one looks like the Dark Visual Studio, the first one looks like Dark+.
Make sure to switch to the Dark+.
There were some theme swirls in the past, but we have settled now with to the 2 styles of default themes (VS and plus).

**Comment by aeschli** [comment]
@Anjmao I'd need more information....
