### ISSUE TITLE
I Use it open a file and cursor is Thickening and i can‘t write in anything.

### ISSUE THREAD

**Issue by xulayen** [Microsoft/vscode#48642]
As a problem，if i change Typewriting to english and write in ‘ssss’,then i can write something.then i can't use "Ctrl + A" Shortcut key

![image](https://user-images.githubusercontent.com/15044564/39229548-c7b8d7f8-4895-11e8-837a-715d94554dd1.png)

**Comment by xudatui** [comment]
i  me too,how to change

**Comment by 20160705** [comment]
感觉是vscode开启了vim模式，试试输入q（退出vim模式）

**Comment by lukeberry99** [comment]
Is it possible that you have the vim extension enabled?

**Comment by bpasero** [comment]
This sounds like caused by an extension. Please report to them or delete it.
