### ISSUE TITLE
Closing or restarting the editor doesn't terminate the process running in the terminal

### ISSUE THREAD

**Issue by rahuldpi** [Microsoft/vscode#48658]
- VSCode Version: 1.22 
- OS Version: Mac OS 10.12.1

Does this issue occur when all extensions are disabled?: Yes

**Steps to Reproduce:**
1. Run any service in the terminal eg: `mongod`
2. Quit visual studio code and relaunch it
3. Now again run the same command in the terminal. It will display an error "Another mongod instance is already running".

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/44408

**Comment by StickNitro** [comment]
Was going to take a look at this, can anyone suggest a good place to start please?

**Comment by Tyriar** [comment]
The process is launched from VS code here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/node/terminalProcess.ts

It uses the https://github.com/Microsoft/node-pty module to launch the process. Running `code --status` should help visualize the process tree under VS Code.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/45535
