### ISSUE TITLE
showQuickPick: canSelectMany has no effect

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#48653]
Refs: #48471

1. Have an extension with the following api call
```javascript
vscode.window.showQuickPick(['first', 'second', 'third', 'fourth', 'fifth'], {
            canSelectMany: true
        }).then(result => vscode.window.showInformationMessage(result.toString()));
```
2. I can not select multiple items when the quick pick is shown

I am doing something wrong here or is this a bug?

**Comment by isidorn** [comment]
Well canSelectMany is what I get proposed in the suggestions.
@chrmarti Are we sure we are not breaking anything by renaming api options?  Or was the canSelectMany never surfaced to users?

`canPickMany` works just fine

**Comment by chrmarti** [comment]
My typo, sorry. `canPickMany` is correct and we only ever shipped with that.
