### ISSUE TITLE
Debugger: Expression and Log Message cannot be removed from a breakpoint

### ISSUE THREAD

**Issue by GraceDong** [Microsoft/vscode#48657]
- VSCode Version: 1.22.2
- OS Version: CentOS 7

Steps to Reproduce:

1. Install C# extension
2. Create a .net core app
3. Open the app with VSCode
4. Set a breakpoint and add an Expression or Log Message, e.g: 1>0
![image](https://user-images.githubusercontent.com/20184778/39235835-97908468-48a9-11e8-83a6-262cb5f34b83.png)
5. Delete this expression and press 'Enter' to close the input box
![image](https://user-images.githubusercontent.com/20184778/39236005-19f9db66-48aa-11e8-8418-4ff7cfa33efb.png)
6. Check the breakpoint status

Expected behavior:
This breakpoint should be restored to a breakpoint without expression.

Actual behavior:
The expression still exist. 

Does this issue occur when all extensions are disabled?: Yes/No
No, because I cannot set a breakpoint when the extension is disabled.

**Comment by weinand** [comment]
Please file this against the C# extension.

**Comment by weinand** [comment]
Please ignore my previous comment.
This is a VS Code issue.

**Comment by weinand** [comment]
@isidorn I cannot delete a log message by setting it to an empty string. VS Code reverts this to the original string.

**Comment by isidorn** [comment]
@weinand yes, there was an issue in the breakpoint widget.
More precisely I did not distuinguish if a user set a condition to "", or if he does not have the condition input box opened at all.
