### ISSUE TITLE
API feature request: allow to specify focused item/index in `window.showQuickPick`

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode#48650]
### vscode.window.showQuickPick
By default, it focuses on the first item. Is there any plan to allow to pre-focus on a certain item. E.g. 
```
window.showQuickPick( original params ... , focused_index?: number)
```

There is scenario that we don't want to change the order of the items, but do want to pre-focus on a certain item, so most of time users can directly hit <enter> to continue.

e.g. 
In following scenario, we let users to select a version number of some libs, listed by the order of releasing date. And we want to focus on the **latest stable version**. 
```
---------------------
choose the version
---------------------
2.1.0-beta
2.0.0-beta
1.5.3    <------------
1.4.8
1.3.9
```

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-debug/issues/275

**Comment by tomzx** [comment]
See #11483 and #27352.
