### ISSUE TITLE
FileSystemProvider: workspace folder does not load initially

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48665]
Refs: https://github.com/Microsoft/vscode/issues/48421

**Setup:**
* clone https://github.com/bpasero/remote-fs
* F5

=> the explorer shows an error for the root folder and only clicking "Refresh" loads it

![image](https://user-images.githubusercontent.com/900690/39240438-0c4f1a24-4884-11e8-86da-c420e9a03e40.png)

I am not sure if this is already covered by the https://github.com/Microsoft/vscode/issues/48275 issue

/cc @jrieken

**Comment by jrieken** [comment]
@bpasero You are using the wrong activation event... We call and wait for for `onFileScheme:<scheme>` which doesn't wait for `*` activations to be finished. Not sure if this correct activation or not. 

/cc @alexandrudima @sandy081

**Comment by isidorn** [comment]
The issue is that the root can not be resolved and this is properly shown in the explorer.
Once we have https://github.com/Microsoft/vscode/issues/48275 this can be tackled using that as well -> may

**Comment by jrieken** [comment]
@isidorn Yes, but that's because the extension activation isn't awaited...

**Comment by bpasero** [comment]
Works with this activation:

```json
"activationEvents": [
    "onFileSystem:datei"
]
```
