### ISSUE TITLE
FileSystemProvider: watcher is being called for in-workspace files

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48667]
Refs: https://github.com/Microsoft/vscode/issues/48421

**Setup:**
* clone https://github.com/bpasero/remote-fs
* F5
* click "Refresh" in the explorer
* you should see the current working directory as a remote folder using the file system provider for scheme `datei://`

**Steps**
* add a breakpoint to the watch method
* open a file that is within the workspace

=> the watcher method is called for this file even though it is within the workspace and so I would expect this not to be called and instead be covered by the (recursive) folder watcher

Could be related to https://github.com/Microsoft/vscode/issues/48666

**Comment by jrieken** [comment]
> the watcher method is called for this file even though it is within the workspace an

Cannot reproduce, please show me. The current, expected behaviour is that it's called for the workspace and files outside the workspace

**Comment by bpasero** [comment]
Issue was with my workspace file.
