### ISSUE TITLE
FileSystemProvider: unable to save with or reopen with encoding

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48662]
Refs: https://github.com/Microsoft/vscode/issues/48421

**Setup:**
* clone https://github.com/bpasero/remote-fs
* F5
* click "Refresh" in the explorer
* you should see the current working directory as a remote folder using the file system provider for scheme `datei://`

**Steps**
* open a file
* click in the status bar on the encoding picker to either reopen or save with encoding

=> we do not seem to support this, nothing happens

/cc @jrieken

**Comment by jrieken** [comment]
```

encoding.js:123 Uncaught (in promise) TypeError: Cannot read property 'end' of undefined
    at encoding.js:123
    at encoding.js:112
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109)
```

**Comment by bpasero** [comment]
@jrieken yes I was about to report, seems to originate from the `toDecodeStream`

**Comment by jrieken** [comment]
This is some bizarre WinJS.Promise vs Promise thing

**Comment by jrieken** [comment]
I do have a better understand of this and it's scary... During `Promise.resolve` (which is async) the winjs-promise resolves and goes into the [success-state](https://github.com/Microsoft/vscode/blob/joh/next/src/vs/base/common/winjs.base.js#L886) which is a oneway, e.g. it doesn't have a then-function. Somehow, tho Promise.resolve still holds on to that ends up calling it and boom. The take aways is to not use a winjs-promise in Promise.resolve.
