### ISSUE TITLE
FileSystemProvider: watcher for workspace folder not hooked up?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48666]
Refs: https://github.com/Microsoft/vscode/issues/48421

**Setup:**
* clone https://github.com/bpasero/remote-fs
* F5
* click "Refresh" in the explorer
* you should see the current working directory as a remote folder using the file system provider for scheme `datei://`

**Steps**
* do a file modification outside the editor

=> this change is not reflected in the UI
=> it does not seem as if the watch API of my provider is called

Could be related to https://github.com/Microsoft/vscode/issues/48665

**Comment by jrieken** [comment]
> do a file modification outside the editor

What does mean? In your extensions or inside another editor?

**Comment by bpasero** [comment]
@jrieken no, the file is within the workspace folder that I open and I just delete a file from that folder using finder (macOS). 

I think the underlying issue is that my watch implementation is not being called for the workspace root folder and as such I can never produce the file events in the first place.

**Comment by bpasero** [comment]
Issue with my workspace file.
