### ISSUE TITLE
FileSystemProvider: FileOptions is a bit weird to support/understand

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48668]
Refs: https://github.com/Microsoft/vscode/issues/48421

Today `vscode.FileOptions` is this:

```typescript
export interface FileOptions {

	/**
	 * Create a file when it doesn't exists
	 */
	create?: boolean;

	/**
	 * In combination with [`create`](FileOptions.create) but
	 * the operation should fail when a file already exists.
	 */
	exclusive?: boolean;

	/**
	 * Open a file for reading.
	 */
	read?: boolean;

	/**
	 * Open a file for writing.
	 */
	write?: boolean;
}
```

And it is being used in:
* `readFile`
* `writeFile`
* `rename`
* `copy`

**create vs exclusive**
not clear what the relation between create and exclusive is, can it be both or either one? maybe this should be reflected in some enum so it is clear it can only be one value?

**read vs write**
what is the use case for this option? should I handle the case in `writeFile` if `options.write` is not configured? today in my implementation I totally ignore this.

**Comment by jrieken** [comment]
Yeah, it's a bit of a kitchen sink...

**Comment by jrieken** [comment]
> what is the use case for this option? should I handle the case in writeFile if options.write is not configured? today in my implementation I totally ignore this.

It leaks a little the plan of having fopen/fclose but technically you can combine things, e.g. create a file when trying to read it, like the `w+`-flag

Similar `exclusive` is the `x` flag which causes failure when combined with `+` and when the file already exists.

**Comment by bpasero** [comment]
@jrieken ah ok I was not directly making the connection to the fs file modes, maybe an example in the docs would have helped or different names.
