### ISSUE TITLE
FileSystemProvider: file operations not reflected

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48669]
Refs: https://github.com/Microsoft/vscode/issues/48421

**Setup:**
* clone https://github.com/bpasero/remote-fs
* F5
* click "Refresh" in the explorer
* you should see the current working directory as a remote folder using the file system provider for scheme `datei://`

**Steps**
* do a local operation from the explorer such as "New File"

=> after doing so the file is opened in the editor but the explorer is not showing it
=> it seems there is a file [operation](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L467) but the outcome is not good?

/cc @jrieken

**Comment by isidorn** [comment]
@bpasero I can not reproduce it. Do you see this constantly?
Can you reproduce this with a regular FS? On what OS are you?

![fileexplorer](https://user-images.githubusercontent.com/1926584/39245197-4a8e488c-4893-11e8-9a93-53712b914a36.gif)

**Comment by isidorn** [comment]
I think this is the same casue as #48663
Let's wait for @sandy081 to fix that one

**Comment by bpasero** [comment]
Sorry, this was me having a bad workspace file entry where I used a relative URI.
