### ISSUE TITLE
FileSystemProvider: unable to copy/move a file over an existing one

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48660]
Refs: https://github.com/Microsoft/vscode/issues/48421

**Setup:**
* clone https://github.com/bpasero/remote-fs
* F5
* click "Refresh" in the explorer
* you should see the current working directory as a remote folder using the file system provider for scheme `datei://`

**Steps**
* move or copy a file into a directory that already exists

=> an unknown error shows up
=> I would expect the typical dialog we have that asks to overwrite the target

**Comment by jrieken** [comment]
I have copy and moves regular files but not folders, nor binary files. That is tracked in #41543
@bpasero what exactly are you copying and what is the error?

**Comment by bpasero** [comment]
@jrieken this was just `README.md` of our `vscode` repo from top level into `test` folder where the file also exists.

**Comment by jrieken** [comment]
ok, understood. @bpasero is the `IFileService` contract that it should signal the existence of the destination? I was assuming that the command/action makes sure everything is prepared correctly and then call the service with `override` set accordingly. Is the expectation that the service shows the prompt?

**Comment by bpasero** [comment]
@jrieken contract would be that the file service signals this fact via [`FILE_MOVE_CONFLICT`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L638) which will bring up the dialog (in the explorer from the DND operation). And then if confirmed, [`moveFile`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L107) or `copyFile` with `overwrite: true` is called.

**Comment by jrieken** [comment]
maybe April...

**Comment by jrieken** [comment]
This now works for move, for copy I seem to always get a different name from the action anyways, e.g. `foo.1.ts` instead of `foo.ts`. That seams to be the standard behaviour and nothing special to remote resources. *Important* is that this requires the file system provider to behave correctly, e.g it must throw `FileExist`-errors when creating a file with the overwrite option.
