### ISSUE TITLE
FileSystemProvider: search does not return local results

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48670]
Refs: https://github.com/Microsoft/vscode/issues/48421

**Setup:**
* clone https://github.com/bpasero/remote-fs
* F5
* click "Refresh" in the explorer
* you should see the current working directory as a remote folder using the file system provider for scheme `datei://`

**Steps**
* open a file
* use search viewlet to search for a word that occurs in the opened file

=> no results shown even though we could return the results from all opened buffers

//cc @jrieken

**Comment by jrieken** [comment]
Yeah, there are separate umbrella items for search and remote files

**Comment by bpasero** [comment]
@jrieken @roblourens if the editor is in memory I would expect that this should just work without a remote implementation of the search actually. We do the same for untitled files which are also searchable and not on disk.

**Comment by jrieken** [comment]
Agreed - it seem on purpose but mostly because we want to filter non-persistable documents I guess. See: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/searchService.ts#L172

**Comment by roblourens** [comment]
That exact example repo no longer works but I think this is basically covered by https://github.com/Microsoft/vscode/issues/58370 now.
