### ISSUE TITLE
Unable to compare large XML files above 50MB

### ISSUE THREAD

**Issue by BipulRaman** [Microsoft/vscode#48679]
Issue Type: <b>Bug</b>

Unable to compare large XML files. Around 65 MB each file size, having around 4,51,000 rows/lines in the file.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|31.88GB (24.63GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Bipul\Desktop\Compare|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
mssql|ms-|1.3.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
team|ms-|1.133.0
iis-express|war|1.1.0
markdown-all-in-one|yzh|1.2.0

</details>

**Comment by alexandrudima** [comment]
We currently show a message if one of the files is too large

![image](https://user-images.githubusercontent.com/5047891/39365648-ff65ace2-4a31-11e8-9950-db8910ca16c9.png)
