### ISSUE TITLE
Fatal: VSCode may cause system hang

### ISSUE THREAD

**Issue by huoyaoyuan** [Microsoft/vscode#48673]
- VSCode Version: 1.22
- OS Version: Windows 10 17134.1

##### Steps to Reproduce:

Activating VSCode window will have a ~10% chance to get the whole OS hanged. Only mouse cursor can move, and any command doesn't work.

This **only** applies to one of my machine. The hardware platform is Intel Core i7-8700K/Z370. Also reproduces on another PC with the same hardware.

This **not only** applies to VSCode, but also VS installer and Chrome.

This maybe a firmware/Chromium bug, but I can't find anywhere else to take attention.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@huoyaoyuan does it reproduce if you run "`code --disable-gpu`"?

**Comment by huoyaoyuan** [comment]
@bpasero Not reproduced after testing for half an hour.
GPU: Intel UHD Graphics 630, with driver from Windows Update.

**Comment by huoyaoyuan** [comment]
The issue has been fixed by some (external) version, and can be closed now.
