### ISSUE TITLE
Animate sidebar toggling

### ISSUE THREAD

**Issue by mquandalle** [Microsoft/vscode#4867]
Sublime Text has a fast and smooth transition on sidebar toggling. I noticed that some of the VSCode elements also have a similar transition, like the “find widget” (opened on <kbd>Ctrl</kbd>+<kbd>F</kbd>).

Should the sidebar have this transition on VSCode?

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
