### ISSUE TITLE
Problems aren't getting proper file path links from nested makefiles with relative paths

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#48681]
Copied from https://github.com/Microsoft/vscode-cpptools/issues/1871
@tehKaiN

This is gonna be a bit tricky to fix, but it's kinda doable. ;) It's a bit of general vscode problem but it's tightly connected to any makefile-based building. Since makefiles are mostly used with C/C++ I'm posting it here.

I have a folder containing subprojects and a `common` folder containing shared code. Each subproject has it's own makefile. I have build tasks for each of subprojects and they are configured in manner as follows:

``` json
{
	"label": "make packer",
	"type": "shell",
	"command": "make",
	"group": "build",
	"problemMatcher":"$gcc",
	"args": [
		"-C", "${workspaceFolder}/subproj1",
	]
},
```

During building I get GCC error:

```
make: Entering directory `D:/prg/myfolder/subproj1'
# Some irrelevant lines here
Building file: ../common/test.c
../common/test.c: In function 'testfn': # warning content irrelevant
```

Which translates to problem in file located at `D:/prg/common/test.c` which is wrong because it should be 
`D:/prg/myfolder/common/test.c`

The reason for such behavior is as simple as relative path being applied to workspace folder and not makefile parent directory. I'll probably change my makefile so that it would use absolute path (if I figure out how to enforce it), but I guess it's worth reporting anyway. The `entering directory` message is constant across makefile versions and there is a `leaving directory` message accompanying it, so this could be used to auto detect current directory.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/11663.
