### ISSUE TITLE
Horizontal scroll bar in Explorer view?

### ISSUE THREAD

**Issue by carlocardella** [Microsoft/vscode#48684]
**VSCode Version**:
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Version 1.23.0-insider
Commit 36e6cbb7667e7874748d8fbf2021b743d2d90afc
Date 2018-04-25T05:17:12.103Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**OS Version**:
OS Name: Microsoft Windows 10 Enterprise
OS Version: 10.0.16299 N/A Build 16299

**Steps to Reproduce**:

1. In Explorer open a folder structure with enough subfolder and files o cause part of the file names to be hidden
2. There is no horizontal scrollbar, the only way to completely show the hidden file names is to resize the side bar (or hover the mouse on the file(s) you are interested in)

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/5784415/39256653-4c324c44-4864-11e8-96b8-4e2454fa467c.png)

**Comment by isidorn** [comment]
"workbench.tree.horizontalScrolling": true
