### ISSUE TITLE
[Folding] CSS/Less/SCSS Regions Don't Work With Syntax Aware Folding

### ISSUE THREAD

**Issue by HodofHod** [Microsoft/vscode#48689]
Issue Type: <b>Bug</b>

Adding `/* #region */ `and `/* #endregion */ ` markers to CSS, Less, or SCSS files does not enable folding for those regions. 

This only applies when `"editor.foldingStrategy"` is set to `"auto"`. When it is changed to `"indentation"`, folding works as expected.

![vscode issue](https://user-images.githubusercontent.com/1865736/39259968-f5130d14-4885-11e8-9ad9-1e6076865030.gif)

Reproduced with all extensions disabled.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.16299

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/46591 already available in insider. Use https://code.visualstudio.com/insiders/ or wait for next month's release.
