### ISSUE TITLE
Some filetypes do not appear on the taskbar jumplist and cannot be pinned

### ISSUE THREAD

**Issue by GuardianMajor** [microsoft/vscode#48688]
Issue Type: <b>Bug</b>

Since the app icon is pinned to the taskbar, when you open an item it shows up on the list and you can quickly access them or if you use them constantly, you can pin them.

However, some of the most regularly accessed files that I need to continually modify do not appear on the list and cannot be pinned. These files have the `.cmd` and `.bat` extensions, may also be occurring with other extensions too but these are the two in my experience.

Why don't all file types that are opened show up on the list and be pinnable? If they are code (or not) and can be edited (or are) in VSC, then why not be able to pin them or even see them on the list?

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|Memory (System)|3.92GB (1.09GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|0.3.0
cform|aws|0.0.10
unique-lines|bib|1.0.0
reg|ion|0.0.2
mssql|ms-|1.3.1

</details>

**Comment by GuardianMajor** [comment]
Please note, this is not a duplicate of pinning stuff INSIDE VSC but rather the OS facing capability, specifically this menu:

![jumplist](https://user-images.githubusercontent.com/5274181/39260043-11adf20e-486d-11e8-9188-696d6d1eb75c.PNG)

**Comment by kczx3** [comment]
On a related topic, I am on version 1.23.1 and the only option I see in the JumpList on Windows is "New Window" under the Tasks sub-heading.
![image](https://user-images.githubusercontent.com/15206020/39926437-394cbc18-54fd-11e8-91aa-9303cab0c929.png)
