### ISSUE TITLE
RUN: VS Code from no-or-not-enough-user-rights-supporting-based- (FAT-XX|exFAT|UDF) -drives, independent of targeted OS

### ISSUE THREAD

**Issue by claudiusraphael** [Microsoft/vscode#4868]
- VSCode Version: latest | downloaded now 20160401220400
- OS Version: Ubuntu Linux Xenial | latest updates as of right now (just an example)

Steps to Reproduce:

1. Download VS Code for Linux 32|64 & Extracting|Unpacking|Unzipping it to a FAT-XX|exFAT|UDF-based drive
2. Try to launch it

TARGET: Running VS Code from drives which are formatted with file-systems, which do NOT support USER-RIGHTS or similar mechanisms; for example from:
- EFS-Partitions
- SD-|CF-|-Cards
- Shared partitions for cross-platform-use

I am totally aware of the NEEDs of specific OSs, but i am asking for A-WAY-AROUND.

Does such a way exist? If so, what would be the generic VS-Code-Whopper-to-consume-right-here-and-now-independent-of-my-origin-location-and-target?

I am having a very deep-going feeling that VS Code would be able to salute under such conditions, do not ask me why.

Does anyone think that the described (or at least a specific variant of it) could be possible? If so, please add your 2-million-cents (means a very detailed) comment to this issue a.k.a. request;

Thanks for your interest.

**Comment by Tyriar** [comment]
@claudiusraphael do you mean support running VSCode from a location that only has read access?

**Comment by Tyriar** [comment]
If this is indeed about running from a drive that does not have read access, this can be fixed with the `--user-data-dir` command line arg coming in the April release (see https://github.com/Microsoft/vscode/issues/3068).

```
code --user-data-dir /some/dir/with/write/access
```

Reopen if I misunderstood, thanks.
