### ISSUE TITLE
Why I could not use the SecureCRT.app after I press ctrl +` on Mac OSX 10.13.4

### ISSUE THREAD

**Issue by man2018** [Microsoft/vscode#48685]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.
Hi,I want to use the SecureCRT.app ,and I have alread edited the "terminal.external.osxExec": "SecureCRT.app"
},but it is can out open the SecureCRT.app when I press ctrl +` ,My osX version is 10.13.4 ,made in 2014 mid,64 bit.
Please help me ,Thanks very much

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by man2018** [comment]
I have been modified it ,but it's not effective
![2018-04-25 23 54 27](https://user-images.githubusercontent.com/18020785/39257496-3fc654b6-48e4-11e8-9063-15dfd13b2915.jpg)

**Comment by Tyriar** [comment]
ctrl+` is the integrated terminal, which is configured using `terminal.integrated.shell.osx`. The _external_ terminal is triggered with cmd+shift+c
