### ISSUE TITLE
Toggling search viewlet is showing different search results

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#48686]
![kapture 2018-04-25 at 17 52 01](https://user-images.githubusercontent.com/10746682/39257286-767f5d96-48b1-11e8-9a40-4dd9f6830a71.gif)

**Comment by roblourens** [comment]
Not different results - one has an exclude. But this is because they don't share state. https://github.com/Microsoft/vscode/issues/44491

**Comment by sandy081** [comment]
@roblourens But if you see the gif, search viewlet in side bar is showing inconsistent results

**Comment by roblourens** [comment]
I think they share some model object but not the view. Probably related but I'll leave it open.

**Comment by roblourens** [comment]
I don't really know of an issue here besides what #44491 covers
