### ISSUE TITLE
RunInTerminalResponse given from vscode does not have a body.

### ISSUE THREAD

**Issue by fabioz** [Microsoft/vscode#48680]
- VSCode Version: 1.22.2
- OS Version: Windows 10

The debug protocol:
https://raw.githubusercontent.com/Microsoft/vscode-debugadapter-node/master/debugProtocol.json specifies that RunInTerminalResponse has a mandatory body, yet, the result from vscode when asked to run something in the integrated terminal does not have a body.

i.e.: The output I have is {'request_seq': 2, 'command': u'runInTerminal',u'type':u'response', 'success': True, 'seq': 5}

So, even if the body is an empty object, the actual body should be there (or the specification should be updated to make it optional).

**Comment by weinand** [comment]
Since making a mandatory element optional would be a breaking DAP change, I've made sure that VS Code returns a 'body' element in the response.

**Comment by weinand** [comment]
Yeah, that was a simple, low-risk fix... ;-)
