### ISSUE TITLE
How to handle multiple format/rename providers?

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#48695]
Had this question while testing #48409. But I had a similar problem at #41882.

The problem is, through API we allow multiple language feature providers to co-exist, but we always have the implicit assumption that only 1 format/rename provider will exist for one file.
When multiple providers exist, @jrieken suggested that the provider with the highest `DocumentSelector` wins. However when multiple formatter uses the same selector (such as a string like `markdown`), there is no clear rule as to which one wins.

For hover and completion, VS Code calls all registered providers and reconcile the results. However for format/rename, there is no clear winner as to which one wins.

For an extension author, he doesn't know if his formatter or another formatter is being used.
For users, they don't know which formatter got picked.

**Comment by jrieken** [comment]
>  there is no clear rule as to which one wins.

There is: It's the one that comes last. So, the behaviour is deterministic. 

> For an extension author, he doesn't know if his formatter or another formatter is being used.
For users, they don't know which formatter got picked.

Yes, that's why we recommend to have options to enable/disable formatter. Also why would you install multiple formatters for the same language? You also don't install two compilers for the same language?

**Comment by octref** [comment]
> There is: It's the one that comes last. So, the behaviour is deterministic.

Imagine two extensions A and B registering two `renameProviders`. They both call `registerRenameProvider` in their activation. How does author of either A or B know his extension would "win", as the order is based on VS Code's sequence of loading extensions?

**Comment by octref** [comment]
> Yes, that's why we recommend to have options to enable/disable formatter. Also why would you install multiple formatters for the same language? You also don't install two compilers for the same language?

Well, now we already have prettier / TS language service formatter for both js/ts.

**Comment by jrieken** [comment]
Yep, but that's why we have: `"typescript.format.enable": true|false`
