### ISSUE TITLE
ARM Template Extension: Mapping JSON files to JSONC breaks IntelliSense

### ISSUE THREAD

**Issue by erictorbenson** [Microsoft/vscode#48696]
I currently map the "JSON with Comments" language type to *.json to allow editing of ARM templates without flagging comments as errors. When I do this, IntelliSense for the ARM template does not suggest completions. I can't find a setting that looks like it would let me override this behavior.

Steps to Reproduce:
1. Install a fresh copy of VS Code and install the ARM Tools Extension.
2. Add the following to the User Settings and reload VS Code:
`{
    "files.associations": {
        "*.json":"jsonc"
    }
}`
3. Load an ARM template and attempt to auto-complete a parameter, variable, etc. IntelliSense window will not appear.
4. Comment out the line above and reload, functionality returns.

**Comment by aeschli** [comment]
@erictorbenson Do you use the https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools?

**Comment by erictorbenson** [comment]
Yes I do, version 0.4.0.

[cid:image001.jpg@01D3E226.DD429800]

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-azurearmtools#100
