### ISSUE TITLE
File problems not always refreshing on changes

### ISSUE THREAD

**Issue by diminutivesloop** [Microsoft/vscode#48693]
Issue Type: <b>Bug</b>

Sometimes when I correct a reported problem in a file VSCode will continue to report the problem until the file is closed and re-opened. This has happened for several different files types so I don't believe it's caused by a particular language extension.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930MX CPU @ 3.00GHz (8 x 3192)|
|Memory (System)|31.94GB (16.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|yes|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.2
ng-template|Ang|0.1.9
vscode-eslint|dba|1.4.8
find-related|eam|0.7.0
gitlens|eam|8.2.4
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.3.1
java-properties|ith|0.0.2
vscode-duplicate|mrm|1.2.1
vsliveshare|ms-|0.2.405
debugger-for-chrome|msj|4.3.0
tsimporter|pmn|1.2.14
java|red|0.23.0
sass-indented|rob|1.4.9
sort-lines|Tyr|1.6.1
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0
vim|vsc|0.11.5

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@diminutivesloop Problems are generated by the extensions and they own their lifecycle. So please report an issue against the corresponding extension.
