### ISSUE TITLE
[Feature Request] keyboard shortcut to launch a specific configuration

### ISSUE THREAD

**Issue by JerryGoyal** [Microsoft/vscode#48694]
I'm not sure if it is already requested. I tried searching but didn't find any resource.

I strongly believe that some projects can have multiple debug configurations. So, it would be efficient to set different shortcuts to invoke different configurations.

There's a way to see all configurations and select one if we add below to keybindings: 
```
{
        "key": "ctrl+r",
        "command": "workbench.action.debug.selectandstart"
    }
```
But no way to directly run a configuration.

**Comment by isidorn** [comment]
Yes, we do not support that currently, the selectAndStart is the alternative as you already found out
