### ISSUE TITLE
NPM Script explorer should honor .gitignore

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#48698]
I have a workspace with test data that is listed in my `.gitignore` file. However, the NPM Script Explorer lists all scripts in my test data folder.  

I'd like to be able to tell the explorer that it should honor the `.gitignore` file. I personally don't need a setting but others might want to see the current behavior.

**Comment by egamma** [comment]
Request makes sense. For now you can use the `npm.exclude` setting to exclude folders.

**Comment by kieferrm** [comment]
I have a workspace that has several top-level folders that all start with the prefix `samples-`. I tried
```json
    "npm.exclude": [
        "samples-*/**"
    ]
```
and
```json
    "npm.exclude": "samples-*/**"
```
in workspace settings. Both don't work. The pattern though works for `files.exclude`. Any hint?

**Comment by kieferrm** [comment]
The excludes are matched against absolute file paths and not workspace-relative ones. Thus `**/samples-*/**` works. It would be nice if `npm.exclude` and `files.exclude` would behave the same.
