### ISSUE TITLE
Console messages in Developer Tools are hard to read with dark theme

### ISSUE THREAD

**Issue by rbolsius** [Microsoft/vscode#48690]
Issue Type: <b>Bug</b>

1.  Open the Developer Tools window via the Help menu
2.  Open the Developer Tools Settings via the three dots menu for by clicking F1
3.  Change the theme from Light to Dark and close the settings
4.  Look for messages in the console from the Extension Host.  These are nearly impossible to read since the text foreground color is forced to be black and the background color is now dark.  The label which is pure blue is also nearly impossible to read against the dark background.

The fixed color theme that is hard coded in files such as console.ts and extensionHost.ts is the cause.  For example,

```
consoleArgs = [`%c[${label}] %c${args[0]} %c${topFrame}`, color('blue'), color('black'), color('grey')];
consoleArgs = [`%c[${label}] %c${args[0]}`, color('blue'), color('black'), ...args.slice(1)];
```

Screenshot of the difficult to read text:
![dev-console-dark-theme](https://user-images.githubusercontent.com/2106964/39260951-8a51b962-4880-11e8-9436-4e218b8596de.png)

The messages should either not be colored so that the text will be readable in both light and dark themes, or the text should be styled according to the active theme.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

**Comment by rbolsius** [comment]
Screenshot of the difficult to read text:
![dev-console-dark-theme](https://user-images.githubusercontent.com/2106964/39260951-8a51b962-4880-11e8-9436-4e218b8596de.png)

**Comment by isidorn** [comment]
This is a theming issue, since these colors are not custmoizable, forwaridng to @bpasero and @aeschli

**Comment by bpasero** [comment]
@rbolsius wait, is this the chrome dev tools? how come that one has a dark background? can you show a full screenshot please?

**Comment by rbolsius** [comment]
This is what the settings page looks like with the dark theme applied:
![dev-console-settings-dark-theme](https://user-images.githubusercontent.com/2106964/39315387-27497cc6-493c-11e8-9e39-aa0284fc5043.png)

**Comment by bpasero** [comment]
@rbolsius how do you enable dark theme in chrome devtools?

**Comment by bpasero** [comment]
@rbolsius wow I was not aware of that. But I do not think VSCode will do anything about it because dev tools is not really for users, only for VSCode developers and I think it is fair to require them to use the light theme.

**Comment by user3323** [comment]
@bpasero 

why do we need dark theme in that case? :)

FYI the dark theme - is the basics for almost all developers.
It looks really good, and does not make any problems for eyes, when there are not much light in the room.

So, why should we use light theme? Nonsense.
