### ISSUE TITLE
[bat] Batch File Syntax highlighting not working on variables or comments.

### ISSUE THREAD

**Issue by Tornup** [Microsoft/vscode#487]
After upgrading to version 0.10.1 Syntax highlighting within windows .bat files has become reduced.

Previous versions would syntax highlight variables (%VARIABLENAME%) and comments(REM-COMMENT TEXT" now these both appear as normal text:

![image](https://cloud.githubusercontent.com/assets/594681/11335412/f2e5a0c6-91d3-11e5-84d7-51d17cc69b0c.png)

![image](https://cloud.githubusercontent.com/assets/594681/11335426/06c101c6-91d4-11e5-9789-d016f364fa4b.png)

**Comment by aeschli** [comment]
We use the text mate grammar from https://github.com/sublimehq/Packages

**Comment by dpodder** [comment]
I patched the grammar with a fix for these in pending PR #1678
![issue-487](https://cloud.githubusercontent.com/assets/2354388/12023973/c0d9b3e0-ad64-11e5-935a-31c43fcb7f60.png)

**Comment by aeschli** [comment]
fixed by #1678
