### ISSUE TITLE
Watch for deletes in out of workspace files

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4870]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Add user settings file to working files
2. Reveal in explorer or navigate to the file
3. Delete the file in File Explorer

Actual:
File remains in working files even though it doesn't exist.

Expected:
When you remove other files from your project, they are immediately removed from both the project and working files.

**Comment by bpasero** [comment]
We do not react to file deletes in the working files section currently.

**Comment by bpasero** [comment]
This landed.
