### ISSUE TITLE
Webview reveal does not focus on the webview when not passing parameters

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#48708]
#48453

When I call `panel.reveal()`, both tabs blank out (get unfocused?).

![webview-reveal](https://user-images.githubusercontent.com/4033249/39266734-b43004f6-487f-11e8-9969-42292d71bd9a.gif)

This is different than when I call `panel.reveal(vscode.ViewColumn.Two)`.

![webview-reveal-2](https://user-images.githubusercontent.com/4033249/39266842-fff37436-487f-11e8-973e-41ae5e89f1a6.gif)

**Comment by mjbvz** [comment]
Also fixed by 6091135
