### ISSUE TITLE
Suggestion: Support allowing extension to dynamically control view to contribute to

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#48706]
Suggest to allow an extension to specify at runtime/activation which view they contribute to.  

Today I declare the view in `package.json` as a new view, a built-in view, or into another contributed view (e.g. `azure`). It would be useful to let an extension define the view to contribute to at runtime. For example, I could provide a setting for the Docker extension to let the user choose if they want the Explorer in a new viewlet (e.g. `DOCKER`), the current Explorer viewlet, or perhaps a 3rd option if one existed.  

Maybe this can be accomplished using a `when` clause:  (https://github.com/Microsoft/vscode/issues/48704)?  I could contribute multiple `viewsContainers` in `package.json` with unique `when` clauses. Then in my extension, I could set one of those to `true` and the explorer would move to the appropriate view.

**Comment by sandy081** [comment]
I think this is similar to #48704. Marking this duplicate of that.
