### ISSUE TITLE
How to get the resolved rename range, or should we drop range?

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#48700]
Testing #48409

After resolving a rename location, there is no direct way to get the returned range. It's possible for extension author to save the range somewhere and retrieve it in `provideRenameEdits`, but this seems cumbersome.

This API naming pattern is similar to `CompletionItemProvider` but work in the reverse way. Originally I thought it would resolve the range for the returned edit from `provideRenameEdits`.

I think an alternative might be

```ts
resolveRenamePlaceholder?(document: TextDocument, position: Position, token: CancellationToken): ProviderResult<string>;
```

The range is not being used by VS Code anyway. Dropping it would make it clear it's the extension author's responsibility to provide range in `provideRenameEdits`. He can run `document.getText(range)` to get the placeholder text.

@mjbvz Also what's your thoughts since you are testing this too?

**Comment by mjbvz** [comment]
Yes, I also did not understand how range was used when first trying to implement the API. Maybe the resolved rename context (range and placeholder) should be passed on `provideRenameEdits`, like we do for `CompletionContext`

**Comment by jrieken** [comment]
> save the range somewhere and retrieve it in provideRenameEdits, but this seems cumbersome.

Why would you want that? The language brain should be able to compute the range of symbol at a position, even two times in a row. The resolve-call is only to support the UI so that it can decide how to position the input-widget. I don't see a reason to feed that range back to the provider.

**Comment by jrieken** [comment]
Talked to @kieferrm and we believe part of the confusion might be the name. We figure we can tackle this in two steps

1. For April: rename the `resolveRenameLocation`-function to `prepareRename`
2. For later ( and optionally) pass the result of rename to the `provideRenameEdits`-function.

The latter should only be needed when computing the location/range (or some other yet unknown piece of information) is very expensive and shouldn't be repeated. Then we can use the XYZContext-trick.
