### ISSUE TITLE
Git gutter breaks when filename case changes

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#48714]
Create a file and commit it to Git. Change the file's case, even just one letter, so that Test.js becomes test.js, for instance.

Then restart VSC, just to be sure. Open the test.js file. Modify it. No Git gutters will appear.

**Comment by joaomoreno** [comment]
@garyking Which OS are you on?

**Comment by garyking** [comment]
I'm on Mac OS X 10.13.3.

**Comment by blunket** [comment]
seems like a duplicate of #29861
