### ISSUE TITLE
Username and Password for Github get asked for each push

### ISSUE THREAD

**Issue by TheMegaMatt** [Microsoft/vscode#48710]
Issue Type: <b>Bug</b>

When pushing a repository to github, username an password get reuqested again

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2195)|
|Memory (System)|7.95GB (3.05GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
ng-template|Ang|0.1.9
vscode-icontheme-nomo-dark|be5|1.3.5
markdown-checkbox|bie|0.1.1
markdown-preview-github-styles|bie|0.1.2
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
githistory|don|0.4.0
vscode-npm-script|eg2|0.3.3
LogFileHighlighter|emi|2.4.0
vsc-material-theme|Equ|2.0.1
docthis|joe|0.6.0
vscode-icon-theme|jtl|1.6.2
php-cs-fixer|jun|0.1.62
csharp|ms-|1.14.0

</details>

**Comment by lukebatchelor** [comment]
(disclaimer: not a maintainer, just stumbled across this)

Would you mind checking how you've set up the remote for that repo?

```
git remote -v
```

And look to see if you've used a `https:` protocol instead of `git`. It should look like

```
origin  git@github.com:org/repo-name.git (fetch)
origin  git@github..com:org/repo-name.git (push)
```

That might be the cause.
