### ISSUE TITLE
Calling window.foo = 5 does not do make the variable global in Webview script

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#48715]
#48453

When I try to assign a global variable, such as doing `window.foo = 5` in the Webview script, it is not available in the console of Webview developer tools.

OK, actually found I can access it in here:

![image](https://user-images.githubusercontent.com/4033249/39274276-4d265d02-4896-11e8-9ee3-eb4d66732038.png)

I think this should go together with point 5 in #48705. Being able to interact with their script can help people with development/debugging a lot.

**Comment by mjbvz** [comment]
Good suggestion, I'll add a note on this. We cannot change the inspector behavior as far as I know

**Comment by mjbvz** [comment]
For verification, make sure the docs section on this makes sense and that you can follow these instructions to see a variable set in a webview
