### ISSUE TITLE
TypeScript language service dies unexpectedly

### ISSUE THREAD

**Issue by definitelycarter** [Microsoft/vscode#48716]
- VSCode Version: 1.22.2
- OS Version: MacOS 10.13.4 (17E199)

Steps to Reproduce:

1.  Open typescript file
2.  Edit typescript file

Does this issue occur when all extensions are disabled?: No

I get the following error message below very frequently with the latest update.  Nothing is happens I when click "Report Issue" (the message disappears).  It also seems like VSCode is auto saving files even though the preference is turned off.  It also seems like type checking / analysis in between edits lag for a bit.

My VSCode typescript version is set to 2.8.1 my workspace version (in `node_modules`) is 2.6.2

<img width="469" alt="screenshot" src="https://user-images.githubusercontent.com/6287039/39273853-183f6080-48ae-11e8-896c-75e5f3fc79bb.png">

**Comment by definitelycarter** [comment]
I noticed that I don't experience this issue *if* I tell vscode to use the workspace version (2.6.2) of typescript.  It appears that the issue is either:

- vscode with typescript 2.8.1
- typescript 2.8.2 conflicting with 2.6.2

**Comment by mjbvz** [comment]
Can you please test this in the current vscode insiders build which uses typescript 2.8.3

**Comment by definitelycarter** [comment]
It appears that vscode with 2.8.3 or the vscode insiders doesn't have this issue

**Comment by mjbvz** [comment]
Closing as resolved by 2.8.3 which will ship with the April vscode release

**Comment by definitelycarter** [comment]
I have started facing this issue again.  This time I am running VSCode Insiders and Typescript 2.8.3
