### ISSUE TITLE
TypeScript build task output not populating error list with `--pretty` on

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/vscode#48711]
Issue Type: <b>Bug</b>

As of TypeScript 2.9, `--pretty` is enabled by default on a new ts project, however the error list does not seem to pick these up from build. 

Is there anything specific on the TS side to add to the errors to make the errors grokable by the error list?

here are steps to reproduce
* `mkdir test`
* `npm install typescript@next`
* `tsc --init`
* add a .ts file with errors
* `code .`
* build

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (6.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe stc|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2

</details>
ed by issue reporter -->

**Comment by dbaeumer** [comment]
I fixed it on our end. Having two problem matchers is not nice for the users. 

@mhegazy one thing: the fix now assumes that a message only contains line,column information and never line,column,endline,endcolumn which was possible with the old matcher. But to my knowledge TS always emitted line,column only.

**Comment by dbaeumer** [comment]
@mjbvz please review https://github.com/Microsoft/vscode/pull/48744 and merge if you think the fix is fine.
