### ISSUE TITLE
Powershell session crashes and will not restart

### ISSUE THREAD

**Issue by mortenherman** [Microsoft/vscode#48712]
Issue Type: <b>Bug</b>

I have tried several times that if I stop a debug session in powershell, that I cannot attach a debugger again. also when the debugger environment crashes even though VSCode asks to restart it, it does not work afterwards.

one of the places I have seen the issue with stopping the debug session was running a long invoke-restmethod call, and prior to the http call returning, using shift + F5 to stop debugging often enters this state.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.86GB (9.16GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.0.20
PowerShell|ms-|1.6.0

</details>

**Comment by weinand** [comment]
Please file this issue against the PowerShell extension.
