### ISSUE TITLE
Expose the Id in the base Breakpoint class

### ISSUE THREAD

**Issue by JimSuplizio** [Microsoft/vscode#48722]
- VSCode Version: 1.23.0-insider
- OS Version: all

Steps to Reproduce:

1. Register your own breakpoint handler with vscode.debug.onDidChangeBreakpoints.
2. Inside of the handler the vscode.BreakpointsChangeEvent has arrays for breakpoints removed, added and changed. 

We're using the conditional breakpoints, with a specific condition, to do some processing. With things like **added** and **removed** this is pretty straightforward, the uri/line will uniquely identify the breakpoint but for a **changed** event this isn't the case. There's no good way to know which breakpoint actually changed. The breakpoint coming in has the same URI but a new line number with no reference to the original line number. I'm unable to easily identify which breakpoint changed. 

The Breakpoints, themselves, each have an Id which is unique for the life of the session (or at least until they're deleted) and right now I'm casting the Breakpoint to any to get the _id **(bp as any)._id;** but this doesn't seem like a good long term solution.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Proposal is to add a readonly `id` attribute to the `Breakpoint` class and surface the internal and undocumented `_id` attribute via a getter:

Here is the interface for the proposed API (which is merged with the Breakpoint class):

```ts
export interface Breakpoint {
	/**
	 * The id of the breakpoint.
	 */
	readonly id: string;
}
```

**Comment by JimSuplizio** [comment]
Thank you @weinand!
