### ISSUE TITLE
Add a space to search bar in Extensions page when choosing a dropdown option

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#48725]
On the Extensions sidebar, when we choose an option from the dropdown, like "Show installed extensions", and then `@installed` replaces the search box, please also add a space at the end of that, so we don't have to add a space ourselves if we want to add to the search.

Just a small quality-of-life change, I think, that would be nice.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @garyking
