### ISSUE TITLE
Modifying a file while running debug does not properly update

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4872]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. With a basic Node.js project set a breakpoint anywhere in index.js before you set the port. 
I cloned this https://github.com/heroku/node-js-sample.git and have a breakpoint set on line 1 of index.js
2. Start debugging
3. After hitting the break point, change the port from 5000 to say 8000
4. Continue debugging

Actual:
Output prints that the app is running on port 5000, not the updated 8000 port.

![debugnotupdating](https://cloud.githubusercontent.com/assets/12900364/14221876/2704bf0c-f81f-11e5-8bf7-73bcd282797b.JPG)

**Comment by weinand** [comment]
node.js does not detect and reload modified source automatically. You will have to run a tool like 'nodemon' to get this behaviour.
