### ISSUE TITLE
debug console cut a long string

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#48727]
- VSCode Version:1.22.2
- OS Version:10.13.4

Steps to Reproduce:

1. i console a long string in debug console ，it was cut at the end line . i not see all string 
2. how can i config string wrapp at the end line .

Does this issue occur when all extensions are disabled?: Yes/No

yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/46777
