### ISSUE TITLE
Emmet not indenting and line breaking as it should.

### ISSUE THREAD

**Issue by elamahpla** [Microsoft/vscode#48724]
```
{
    "editor.renderWhitespace": "none",
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontSize": 20,
    "window.zoomLevel": 0,
    "workbench.statusBar.visible": false,
    "workbench.activityBar.visible": false,
    "editor.tabSize": 2,
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "emmet.syntaxProfiles": {
        "javascript": "jsx"
    },
    "workbench.sideBar.location": "left",
    "editor.minimap.enabled": false
}
```
Settings file. Using React (JS/JSX), up until today I've been able to type out an HTML element with Emmet then, as we all know, hit tab then enter for an open and closing div tag with an empty line between them, now, I have to hit enter twice, then scroll up with up arrow or clicks. Was working just fine on Friday, now not at all. 

As a side note, commenting seems to be broken as well. When I highlight a large chunk of code and try to comment out with CMD+/, it only highlights a piece of it, sometimes a lot, sometimes not.

**Comment by ramya-rao-a** [comment]
Please provide the version of VS Code you are using and a sample code for us to repro this on

**Comment by elamahpla** [comment]
Version 1.22.2 (1.22.2)

```
import React from 'react';

const WhiteSpace = () => (
  <div className="WhiteSpace">
    <h1>WhiteSpace</h1>
  </div>
);

export default WhiteSpace;
```

So when I type, for example:

```
<div>
</div>
```
Is how it appears after hitting enter, before this week, it was doing this:

```
<div>

</div>
```

**Comment by ramya-rao-a** [comment]
Can you try after disabling all other extensions? Run `code --disable-extensions`

**Comment by elamahpla** [comment]
Found what was wrong. 

https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring

Caused the issue.
