### ISSUE TITLE
Move the stop Button from the same position of step into

### ISSUE THREAD

**Issue by leandrol3** [Microsoft/vscode#48720]
### Issue Type
Feature Request

### Description

When Im debugging using Mac Book Pro Touch Bar pressing Step Into button, sometimes code needs to wait to be processed and the button, in THE SAME POSITION come to be STOP! So, if you are not aware you would loose your processing.

Feature Request: Move the STOP Button (in the Touch Bar) from the same position STEP INTO!

![image](https://user-images.githubusercontent.com/25961688/39275368-6a283ef0-48bb-11e8-9b9c-3ba78728bdcf.png)
![image](https://user-images.githubusercontent.com/25961688/39275383-7220b7b8-48bb-11e8-8289-dbc5cba7c549.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.5.0

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/54084
