### ISSUE TITLE
Disable tooltip on hover on treeview items

### ISSUE THREAD

**Issue by sefaYavuz** [Microsoft/vscode#48737]
Currently the explorer in the sidebar shows the full path of a file/folder on hover. This very annoying, is there a way to disable this?

---

- VSCode Version: 1.22.2
- OS Version: Windows 10 Pro 1709

Steps to Reproduce:

1. Open the explorer
2. Hover over a file or folder

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
No there is no way to disable this. Closing for now as we do not plan to address this.
If I hear more complaints about this I might considers adding a settings.
Thanks!
