### ISSUE TITLE
[JavaScript] Wrong indentation of case blocks

### ISSUE THREAD

**Issue by mic4ael** [Microsoft/vscode#48735]
- VSCode Version: **1.22.2 (x64)**
- OS Version: **Fedora 27 (4.15.17-300.fc27.x86_64)**

Steps to Reproduce:

![peek 2018-04-26 09-48](https://user-images.githubusercontent.com/3616940/39292690-33ed4d5e-4937-11e8-9d97-c4ee2c091571.gif)

1. Write a simple `switch` statement like this
```javascript
switch (action.type) {
    case 'test':
    return    
}
```
2. The indentation seems to be broken. `return` is in the same column as `case` and also there are 4 spaces added after `return`

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mic4ael** [comment]
Also the issue happens on my Linux OS as well as OSX.

**Comment by mjbvz** [comment]
Pushed fix. Please test in the next insiders build and let me know if auto-indenting cases proves helpful or annoying
