### ISSUE TITLE
Some shortcuts not working on Mac with external keyboard

### ISSUE THREAD

**Issue by borisyordanov** [Microsoft/vscode#48739]
- VSCode Version: 1.21.2
- OS Version: macOS High Sierra 10.13.4

Steps to Reproduce:

1. Open code
2. Press OS button + `

Does this issue occur when all extensions are disabled?: Yes

Some more background: I'm using a MacBook Pro with a [Logitech MK710 keyboard and mouse combo](https://www.logitech.com/en-us/product/wireless-desktop-mk710?crid=1759). The keyboard is mapped successfully with the OS and all system shortcuts works just as well as they do with the laptop's built-in shortcuts. 

There are issues with some VSC shortcuts though, for example, i can still use the shortcut for opening a new file, but i the shortcut for opening a new terminal doesn't work (if i use the external keyboard, it works with the built-in keyboard)

**Comment by bpasero** [comment]
@borisyordanov can you follow https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-mac-keybindings please?

**Comment by borisyordanov** [comment]
Thanks to everyone for trying to help, @alexandrudima was right - the `OS +`` shortcut doesn't work, because it's not the correct shortcut!
