### ISSUE TITLE
"Loaded Scripts" tree is empty

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#48730]
- Debug anything with node
- It empty

**Comment by roblourens** [comment]
I debugged the extension side and it seems like the DA and extension are doing the right thing... loadedSource events are received and processed and the tree gets data.

**Comment by weinand** [comment]
I'm seeing this issue only sporadicly for Extension Host debugging.
I could not reproduce this for node or node2 debugging.

**Comment by roblourens** [comment]
I saw it 100% consistently yesterday, but not today. Missing it with EH debugging is probably for the same reason it happens with Chrome debugging, the node-debug extension isn't activated and it only works when node-debug is activated.
