### ISSUE TITLE
Editor's auto-complete adds an Extral quotation mark while editing notation

### ISSUE THREAD

**Issue by zhangmin93** [Microsoft/vscode#48734]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Us auto-complete (I typed  `/*`  in the row right before the funtion, and pressed 'Enter') to add a nonation for a function (decalration) in Javascript;
2. Type some charater( a-Z, 0-9, or any chinese charaters will do ), and type `"`(the quotation mark) 2 times right after that charater, you will see `"""` (3 quotation marks) , which i was expecting `""` (2 quotation marks).

Is this a feature?

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.89GB (1.86GB free)|
|Process Argv|D:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
xml|Dot|1.9.2
tslint|eg2|1.0.28
gc-excelviewer|Gra|2.0.20
beautify|Hoo|1.3.0
webpack|jer|2.0.2
mssql|ms-|1.3.1
python|ms-|2018.3.1
vetur|oct|0.11.7

</details>

**Comment by alexandrudima** [comment]
@zhangmin93 Yes, this is a feature which auto closes pairs, like e.g. `(` and `)`, `[` and `]`, `"` and `"`, etc.

You can turn this feature off via `"editor.autoClosingBrackets": false`
