### ISSUE TITLE
Search: revealing the next search result when dismissing one does not reveal in tree

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48740]
Steps to Reproduce:

1. dismiss search results from the end
2. ...until you get a file with many search results
3. the last one is properly selected
4. ....but not revealed

![before](https://user-images.githubusercontent.com/900690/39295736-77e973fe-493f-11e8-9f40-38465d332d2f.gif)

**Comment by roblourens** [comment]
Fixed between dff19fccea7966317114ec183f34a0c8d77d43de and c45ad77

**Comment by bpasero** [comment]
I think we no longer select the entry automatically when removing the last one from a folder @roblourens ?

**Comment by bpasero** [comment]
Ah yeah, due to https://github.com/Microsoft/vscode/issues/48911 which is good.
