### ISSUE TITLE
Allow hiding some recommended extensions

### ISSUE THREAD

**Issue by rmunn** [Microsoft/vscode#48743]
Issue Type: <b>Feature Request</b>

I'd like to be able to hide some extensions, in particular ones that keep showing up in the "Recommended Extensions" list but that I'm not interested in. For example, today VS Code recommended the Visual Studio Team Services, and when I hovered over it, the tooltip said "This extension is recommended because you have Git installed." This means that the recommendation is going to keep on showing up.

At my current job, we don't use Team Services, so this extension is of no interest to me; I'd like to not have the recommendation show up since it's mildly distracting. I don't want to hide the entire Recommended sidebar, as it is sometimes useful. But I would like to have an option to right-click on a recommended extension and say "Don't show this to me again" so that I can de-clutter the extensions list a little bit, removing extensions that I'm never going to want to install.

VS Code version: Code - Insiders 1.23.0-insider (6d7bb1a174f588360366af26a2ec8f27064ca110, 2018-04-26T05:16:57.657Z)
OS version: Windows_NT x64 10.0.16299

**Comment by rmunn** [comment]
None of those issues appear to be a duplicate of this feature request.

**Comment by JacksonKearl** [comment]
With #51941, a user is able to ignore recommendations for particular extensions they find not useful across all instances of vscode. Additionally, in cases where a team finds an extension irrelevant or redundant for a particular workspace, the team is able to ignore recommendations for that extension, and track those ignored recommendations in either their `.vscode/extensions.json` or `*.code-workspace` file. This will be available in the next Insiders build.
