### ISSUE TITLE
Git DIFF takes long to show

### ISSUE THREAD

**Issue by darren-dev** [Microsoft/vscode#48742]
Issue Type: <b>Performance Issue</b>

Open a solution that's source controlled
Make a change to the source
Click on the 'Source Control' button in Visual Studio
Click on the file you've edited

-- The application takes 10-20 seconds to display the diff results

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|15.89GB (2.53GB free)|
|Process Argv|D:\Applications\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    90	104164	code main
    0	    98	107792	   gpu-process
    0	   287	140320	   window (xreelstrip.js (Working Tree) - fortuna-engine - Visual Studio Code)
    0	    97	175712	     extensionHost
    0	    97	 10740	       electron_node polymer-language-server.js 
    0	   144	191032	       electron_node electronForkStart.js tsserver.js 
    0	    29	 20072	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    23	204252	       electron_node jsonServerMain.js 
    0	    38	298864	       electron_node xreelstrip.js 
    0	     8	176560	     electron-crash-reporter
    0	    21	181724	     searchService
    0	    15	183048	     terminal
    0	     4	119536	       winpty-process
    0	     3	118324	         "C:\Program Files\Git\bin\bash.exe"
    0	     5	156452	           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	     5	165036	         console-window-host (Windows internal process)
    0	     7	183476	     watcherService 
    0	     4	144124	       console-window-host (Windows internal process)
    0	    64	174036	   shared-process
    0	    83	286788	   powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'd:\Applications\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
    0	     7	270692	     console-window-host (Windows internal process)
    0	    69	299980	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (xreelstrip.js (Working Tree) - fortuna-engine - Visual Studio Code)
|    Folder (fortuna-engine): 323 files
|      File types: png(247) js(29) json(22) db(15) jpg(6) html(2) gitignore(1)
|                  md(1)
|      Conf files: launch.json(1) package.json(1) webpack.config.js(1);
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
xml|Dot|1.9.2
vscode-npm-script|eg2|0.3.3
vscode-npm|fkn|3.3.0
beautify|Hoo|1.3.0
solidity|Jua|0.0.40
node-module-intellisense|lei|1.5.0
git-tree-compare|let|1.2.1
start-git-bash|McC|1.2.1
vscode-autoprefixer|mrm|2.1.2
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
vetur|oct|0.11.7
polymer-ide|pol|0.6.0
vscode-icons|rob|7.22.0
php-formatter|Sop|0.2.4
vscode-wakatime|Wak|1.2.1
quokka-vscode|Wal|1.0.121
html-css-class-completion|Zig|1.17.1

</details>

**Comment by rebornix** [comment]
Please provide more info of how to reproduce this issue, for example, the content which takes long time to diff.

**Comment by darren-dev** [comment]
It's any content - I'm currently working on a javascript project and basically all .js files take a long time to diff.

I reinstalled VScode and it's working okay.

**Comment by rebornix** [comment]
As it no longer exists, I'll close it for now.
