### ISSUE TITLE
Broken undo stack with move lines up with multiple cursors

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48741]
```
if (foo) {
	return bar	
}

// a comment
```

1. Create a text file with the contents above, no special mode needed
2. Put cursor in the middle of word `comment`
3. Duplicate cursors up twice (on Linux it's <kbd>Alt Shift Up</kbd>)
4. Move line up (on Linux it's <kbd>Alt Up</kbd>)
5. Undo :boom: 

![peek 2018-04-26 10-57](https://user-images.githubusercontent.com/22350/39296249-acaa9482-4940-11e8-98b6-344ba20bd760.gif)

**Comment by alexandrudima** [comment]
This was introduced via 3114b0ca670b7366206f0fea0b8f056528c7b532 where we sort reverse operations. But the sorting of reverse operations can be done only if the order is non significant. The order is significant if edit ranges are touching. So, reverse operations should not be sorted when edit ranges are touching.

**Comment by alexandrudima** [comment]
Thanks for catching this @joaomoreno !

**Comment by joaomoreno** [comment]
Where's my check 💰
