### ISSUE TITLE
No macOS Finder icon for .mjs files

### ISSUE THREAD

**Issue by jaydenseric** [Microsoft/vscode#48748]
VS Code doesn't provide an icon for macOS Finder when it is the default app for .mjs files.

[The `.mjs` file extension is the official way to run native ESM in Node.js](https://nodejs.org/api/esm.html#esm_enabling) and should be supported by VS Code out of the box.

- VSCode Version: v1.23.0-insider
- OS Version: macOS v10.13.4

Steps to Reproduce:

1. Create a `test.mjs` file.
2. In Finder, right click on the file and click `Get info`.
3. Under `Open with` select `Visual Studio Code`.
4. Click `Change All…`.
5. You will see the icon everywhere is still the default blank icon provide by macOS: 

<img width="147" alt="screen shot 2018-04-26 at 7 55 00 pm" src="https://user-images.githubusercontent.com/1754873/39299309-c52ea9d0-498b-11e8-855b-80ab3f6e0fd4.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by flaw600** [comment]
Let me take a crack at this @joaomoreno
