### ISSUE TITLE
Node process is left hanging on WSL when debugger is stopped

### ISSUE THREAD

**Issue by fxlemire** [Microsoft/vscode#48755]
- VSCode Version: 1.22.2
- OS Version: Windows 10 Pro 1709, Build 16299.402

Similar to #38424 but still occurring.

Steps to Reproduce:

1. Create the following `index.js` script (taken from [release notes](https://github.com/Microsoft/vscode-docs/blob/master/docs/nodejs/nodejs-debugging.md#automatically-attach-debugger-to-nodejs-subprocesses)):

```js
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length / 2;

if (cluster.isMaster) {
  console.log(`Master ${process.pid} is running`);

  // Fork workers.
  for (let i = 0; i < numCPUs; ++i) {
    cluster.fork();
  }

  cluster.on('exit', (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
} else {
  // Workers can share any TCP connection
  // In this case it is an HTTP server
  http.createServer((req, res) => {
    res.writeHead(200);
    res.end('Hello world\n');
  }).listen(8000);

  console.log(`Worker ${process.pid} started`);
}
```

2. Add the following `.vscode/launch.json`:

```js
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch",
      "program": "${workspaceFolder}/index.js",
      "useWSL": true
    }
  ]
}
```

3. Put a breakpoint on the 5th line (the `if` statement).

4. Start the debugger.

5. When the breakpoint is hit, stop the debugger.

6. In WSL, type `ps aux | grep node` and notice the 3 node processes still running.

N.B. It seems related to the `cluster` package. If the `const cluster = require('cluster');` line is commented out, the problem does not occur, so this package must be doing something `WSL || useWSL` doesn't like, even before the actual forking occurs.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ggondim** [comment]
I have this issue too, with 6~8 node process hanging. Here's my `launch.json`:

```
{
      "type": "node",
      "request": "launch",
      "name": "Nodemon (WSL) - Production",
      "runtimeExecutable": "nodemon",
      "program": "${workspaceRoot}/server.js",
      "restart": true,
      "console": "internalConsole",
      "internalConsoleOptions": "neverOpen",
      "env": {
        "NODE_ENV": "production"
      },
      "useWSL": true
    }
```

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
