### ISSUE TITLE
Huge .browse.VC.db file too

### ISSUE THREAD

**Issue by ljf1239848066** [Microsoft/vscode#48752]
- VSCode Version:1.22.2
- OS Version:Windows 7 SP1

Steps to Reproduce:

1.I was working on Android source project a few hours. Safe check tool warning me saying there was no enough disk space left.Then I found out that a huge file .browse.VC.db (~11.36GB in size). I had to delete it.
2.I think I do get the purpose of the file, but is it supposed to be this huge? or is the behavior strange? or how can I change it's location to other disk?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by ljf1239848066** [comment]
Ok, I found the solution at [here](https://github.com/Microsoft/vscode-cpptools/issues/150):

1.Ctrl+P
2.Open c_cpp.properties.json
3.Edit the follow node:
```
"browse": {
                "path": [
                    "${workspaceFolder}",
                    "D:/Program Files/VS2017/VC/Tools/MSVC/14.11.25503/include/*",
                    "D:/Program Files/VS2017/VC/Tools/MSVC/14.11.25503/atlmfc/include/*",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/um",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/ucrt",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/shared",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/winrt"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "D:/Others/VSCode/browse.vc.db"
            },
```
4.Change `"databaseFilename"`value to location where you want to store the `browse.vc.db` file.
