### ISSUE TITLE
Allow to colorize action icons in views

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#48751]
- VSCode Version: 1.22.2
- OS Version: macOs

Currently, there is no ability to colorize action labels in scm viewlet and it's impossible to see them with different colors. See screenshot below.

![image](https://user-images.githubusercontent.com/30043375/39302186-72b8e32c-495a-11e8-8a58-12be6b9f7870.png)

**Comment by joaomoreno** [comment]
Yeah, unfortunately that applies to pretty much most of the workbench. Those actions are contributed with two sets of icons: for dark theme and for light theme.

We don't have the notion of themeable contributed icons, as far as I know. cc @bpasero @aeschli

**Comment by bpasero** [comment]
//cc @misolori

**Comment by misolori** [comment]
We already do this in the tree view (see #55857 ) but extension contributions have yet to get this. Closing this in favor of #31466 because that's the only way for extensions to get colorization in icons is re-using our icons/icon font.
