### ISSUE TITLE
Pixel-perfection: Active border tab on the first tab has bad margin.

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#48765]
- VSCode Version: 1.22.2
- OS Version: macOS High Sierra 10.13.3

Active tab borders look great on normal tabs

<img width="383" alt="screen shot 1397-02-06 at 8 41 43 pm" src="https://user-images.githubusercontent.com/2157285/39318144-970477a4-4992-11e8-8059-7b5ddc40c368.png">

But the first tab has `1px` margin on the left and right sides which makes it look bad:

<img width="384" alt="screen shot 1397-02-06 at 8 41 49 pm" src="https://user-images.githubusercontent.com/2157285/39318145-97326920-4992-11e8-92a9-f7f3fea02e85.png">

By magnification you'll see:

<img alt="screen shot 1397-02-06 at 8 44 36 pm" src="https://user-images.githubusercontent.com/2157285/39318225-cf18e0a8-4992-11e8-9c40-5a178e022fe6.png">

<img width="164" alt="screen shot 1397-02-06 at 8 46 40 pm" src="https://user-images.githubusercontent.com/2157285/39318277-f8479000-4992-11e8-9060-b2f0192c33c2.png">

**Comment by bpasero** [comment]
If someone wants to fix this and the change is reasonably small, feel free.

**Comment by ahmadawais** [comment]
@bpasero I took a stab on this one, see if it can make it to the May2018 milestone. Here's the PR → https://github.com/Microsoft/vscode/pull/50854

**Comment by bpasero** [comment]
@ahmadawais yeah I have a fix like that sitting in the ben/editor branch that I am planning to push end of week.

**Comment by pmkary** [comment]
@bpasero  @ahmadawais thanks a lot to both of you guys 👍

**Comment by ahmadawais** [comment]
Glad to help 👍

**Comment by bpasero** [comment]
Closing via https://github.com/Microsoft/vscode/commit/fd7d510b0b7c72f2208910a7570ac3695e4fba53
