### ISSUE TITLE
[Feature Request] Git Reset

### ISSUE THREAD

**Issue by arxpw** [Microsoft/vscode#48764]
The ability to do `git reset --hard` directly from **CTRL+SHIFT+P** would be a ( small ) but a very useful additional git feature. Currently we have to do this from the terminal, this would remove those extra steps.

Cheers

**Comment by joaomoreno** [comment]
What exactly do you intend to do with that command?

**Comment by arxpw** [comment]
Please see below
https://git-scm.com/docs/git-reset

`--hard
Resets the index and working tree. Any changes to tracked files in the working tree since <commit> are discarded.`

Thank you

**Comment by joaomoreno** [comment]
Well, I know that. I'm asking because we have commands to remove changes from either the index (Unstage) or the working tree (Discard). Have you given those a try? If so, in what do they differ from what you intend to do?

**Comment by ddnexus** [comment]
@joaomoreno: Unstage and discard are pretty much useless in a branch context. 
An interface to reset a branch to a specific commit, either hard, soft, mixed etc. would be extremely useful.
