### ISSUE TITLE
Treeview refresh button expands treeview even if collapsed 

### ISSUE THREAD

**Issue by ColinLaws** [Microsoft/vscode#48762]
Issue Type: <b>Bug</b>

If you press the collapse button to close up all folders, and you hit the refresh button, the tree view will take the path to your open tab and drill down and open all folders to your working file.

I understand this is likely intentional, but it didn't seem to fit the purpose of a refresh button, refresh just updates the project folders/files, it shouldn't be doing anything else. 

If you do that because you want the user to know that a refresh occurred, consider just making the entire treeview remove all files/folders, and then repopulate with the structure you had open instead of opening up a bunch of folders. 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3384)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.74GB (0.28GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.9.0
html-css-class-completion|Zig|1.17.1
php-intellisense|fel|2.3.1
vue-snippets|hol|0.1.5
vscode-todo-highlight|way|0.5.12

</details>

**Comment by isidorn** [comment]
`"explorer.autoReveal": false`
