### ISSUE TITLE
Extension uninstallation prompt should list dependencies when asking whether to uninstall them

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#48768]
Currently it [says](https://github.com/Microsoft/vscode/blob/a9e16bab72ad8dda0fffb9bdcb44eac96679005b/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L559):
> Would you like to uninstall '{0}' only or its dependencies also?

And you can select "Extension Only", "Uninstall All", "Cancel".

At this point I'm unsure which extensions will get uninstalled if I click "Uninstall All". It should list the dependencies in the same prompt.

**Comment by sandy081** [comment]
Duplicate of #14544
