### ISSUE TITLE
Intellisense should not trigger on cut, backspace or delete of selections

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4876]
This may be a personal preference, it feels weird to me.

Steps to Reproduce:
1. Type some intellisense symbol (eg. `window` in javascript)
2. Select 1+ characters at the end (eg. `dow` in `window`)
3. <kbd>ctrl</kbd>+<kbd>x</kbd>, <kbd>delete</kbd> or <kbd>backspace</kbd> to remove the text
4. I would not expect intellisense to come up at this point

**Comment by bpasero** [comment]
:100: , I am very annoyed by intellisense popping up when deleting text.

**Comment by axefrog** [comment]
Agree, I've just been hunting around for a way to disable backspace as as an intellisense/suggestions trigger, but there doesn't seem to be any that I can see. I'm sure plenty of people love it, but I'd like to be able to disable it in my own settings at least.

**Comment by alexandrudima** [comment]
This has been fixed in the meantime
