### ISSUE TITLE
Commits

### ISSUE THREAD

**Issue by OmarYahia** [Microsoft/vscode#48761]
Issue Type: <b>Bug</b>

when I commit and push files it doesn't appear at bitbucket

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|15.65GB (6.94GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
This doesn't seem to be a Code issue at all. Please ask questions in StackOverflow, you might get better answers there.
