### ISSUE TITLE
should create a new tab after I open a file via ctrl+P

### ISSUE THREAD

**Issue by EasonQiu** [Microsoft/vscode#48773]
Issue Type: <b>Bug</b>

when I open a file via ctrl+P, it will replace my current opened file, I want to always open a new tab for new files that will not replace my current one

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|31.89GB (8.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
python|ms-|2018.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.3.0

</details>

**Comment by shizengzhou** [comment]
@EasonQiu You can try this: `"workbench.editor.enablePreviewFromQuickOpen": false,`
