### ISSUE TITLE
Can't invoke the last executed task with shortcut

### ISSUE THREAD

**Issue by WardenGnaw** [Microsoft/vscode#48776]
From https://github.com/Microsoft/vscode-cpptools/issues/1882 by @ftrofin
--------------------------------------------------------------------------------

macOS 10.12.6
Version Studion Code Version 1.22.2
ms-vscode.cpptools 0.16.1

I have a simple tasks.json file that defines a few build tasks (all of them invoke xcodebuild with the same project file but different schemas):

       {
            "label": "Build Project1",
            "type": "shell",
            "command": "xcodebuild -project ${workspaceRoot}/Make/mac/MyProject.xcodeproj -scheme Project1.Debug build |xcpretty",
            "group": "build"
        },
        {
            "label": "Build project2",
            "type": "shell",
            "command": "xcodebuild -project ${workspaceRoot}/Make/mac/MyProject.xcodeproj -scheme Project2.Debug build |xcpretty",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
... and so on. There are 9 tasks total.

1. I would like to be able to invoke the last executed task again with a simple command. Right now I have to click Tasks->Run Tasks... and then select the top entry again (VSC puts the last executed task at the top of the list). Would be nice to do this more easily. This is very useful expecially for build tasks. I can work around this by fiddling with the `isDefault` property (moving it around) but I think having the concept of the "last invoked task" might be useful.
2. The pop-up window that comes up with the list of the tasks takes a long time (about 5 seconds) *every time* although the list is very short. This adds up when you call it very frequently (edit/build loop).

I know that 1 sounds like a feature request and 2 is more like a bug/improvement but I thought they are related so I put them both in the same ticket. Please let me know if you need more info.

Thanks!

F.

**Comment by dbaeumer** [comment]
@ftrofin thanks. You are correct.

Regarding the 5 seconds. This can only happen if there is a wired auto detection going on. And even then it should only happen once. You can disable most of the auto detections using for example `"gulp.autoDetect": "off"`. Do you have any other task runners installed in your workspace. If so which. And could you provide me with a GitHub repository I can clone that demos this.

**Comment by ftrofin** [comment]
Thanks Dirk. So where would I put the "gulp.autoDetect" property? In the workspace/user config file?

**Comment by dbaeumer** [comment]
@ftrofin in the settings. Either user or workspace.

**Comment by ftrofin** [comment]
OK, I had to disable ALL autodetect task settings:
```    "jake.autoDetect": "off",
    "gulp.autoDetect": "off",
    "grunt.autoDetect": "off",
    "typescript.tsc.autoDetect": "off",
    "npm.autoDetect": "off"```
If I have any of these on, the behavior persists. With all of them off, the task popup window comes up immediately.

**Comment by dbaeumer** [comment]
@ftrofin can you provide me with a GitHub repository that demos this. Or can you try to pin point the plugin causing the slow down by selectively enable the auto detection?
