### ISSUE TITLE
Toggle case of selection

### ISSUE THREAD

**Issue by haibison** [Microsoft/vscode#4877]
- VSCode Version: 0.10.11
- OS Version: Fedora 23, 64bit

Please add command to toggle case of selection, such as:

- `lower case`
- `UPPER CASE`
- `Capitalize Words`
- Invert: `Input` -> `iNPUT`

Thank you  `:-)`

**Comment by Tyriar** [comment]
Looks like this extension might be just what you're looking for https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case

**Comment by haibison** [comment]
Thank @Tyriar , I searched in internal commands but didn't find it. Next time I'll search the store too.

Have a nice day  `:-)`
