### ISSUE TITLE
Integrated Terminal: Spaces in Right Prompt immediately after Powerline character do not render in the correct color

### ISSUE THREAD

**Issue by j0hnm4r5** [Microsoft/vscode#48775]
Spaces in Right Prompt immediately after Powerline character do not render in the correct color in the integrated terminal.

![](https://i.imgur.com/fLxs82w.png)
> Example

- VSCode Version: 1.22.1
- OS Version: macOS 10.13.4
- ZSH Prompt: Powerlevel9k w/ Nerdfonts

Steps to Reproduce:

1. Use a ZSH theme with a right prompt
2. Visually check integrated terminal for issue

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What's in your settings.json?

**Comment by Tyriar** [comment]
You're not using a powerlines font?

> `"terminal.integrated.fontFamily": "Hurmit Nerd Font"`

**Comment by Tyriar** [comment]
Thanks for the info! Let's track this in https://github.com/xtermjs/xterm.js/issues/1453
