### ISSUE TITLE
Buggy syntax highlighting for multi-line import statements in TS

### ISSUE THREAD

**Issue by thomas-darling** [Microsoft/vscode#48770]
Issue Type: <b>Bug</b>

The syntax highlighting for TypeScript import statements seem to only work if the word `import` is immediately followed by a space - if immediately followed by a line break, it fails.

This means this will be incorrectly highlighted:
```ts
import
{
    Foo
}
from "foo"
```

While this, where a space has been added after `import`, works:
```ts
import 
{
    Foo
}
from "foo"
```

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.4.0

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#607
