### ISSUE TITLE
move line up or down don't work properly.

### ISSUE THREAD

**Issue by krauser085** [Microsoft/vscode#48786]
- VSCode Version: 1.22.2
- OS Version: Windows 10 version-1703

When I work with 'move line up or down' with keybord shortcut 'ctrl + arrow-up or arrow-down',
indentations on lines is changed. 

Steps to Reproduce:

1. move line up or down with keyboard shortcut ctrl + arrow-up or arrow-down. (especially on Html)
2. check the indentations has been chagned

![bug-report](https://user-images.githubusercontent.com/23311128/39335897-ed9aef78-49ef-11e8-9b5e-cfa5c60e1893.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
If you want, the adjustment of the indentation can be turned off via `editor.autoIndent`

**Comment by krauser085** [comment]
@alexandrudima thanks for your comment. but I like to use it and I hope It will be fixed soon 😄

**Comment by rebornix** [comment]
Same issue as https://github.com/Microsoft/vscode/issues/54829#issuecomment-422501144, where I left some initial investigations. Let's track this bug there.
