### ISSUE TITLE
Feature Request:  Is that possible to provide variable '${SelectedText}' to return current selected text?

### ISSUE THREAD

**Issue by virtualnode** [Microsoft/vscode#48789]
Selected Text is very useful when we config a custom tasks on vscode.
Eg.,

{
            "label": "Run Robot Case",
            "type": "shell",
            "windows": {
                "command": "pybot.bat"
            }
            ,"args": [
                "-d./output",
                "-t ${SelectedText}",
                "${file}"
            ]
           
        }

**Comment by dbaeumer** [comment]
@isidorn we have an issue for this already. I search but couldn't find it. Do you know the number?

**Comment by dbaeumer** [comment]
Found it 😀 

Dups https://github.com/Microsoft/vscode/issues/27466

**Comment by virtualnode** [comment]
Good! Thanks for your efforts. 
It works!
{
            "label": "Run Case",
            "type": "shell",
            "windows": {
                "command": "pybot.bat"
            },
            "args": [
                "-d./output",
                "-t ${selectedText}",
                "${file}"
            ],
            "problemMatcher": []
        }
