### ISSUE TITLE
Integrated powershell terminal haulting

### ISSUE THREAD

**Issue by ahmedig** [Microsoft/vscode#48787]
The powershell integrated windows is always crashing!
I use it to test my Azure scripts, and debug my scripts, but everytime it just hangs forever, and even when I stop the debugger it keeps haulting forever. I have to delete the terminal session, and start over.

The message that I get from VSCode when that happens:
The powershell session has terminated due to an error, would you like to restart it?
Source: Powershell (Extension).

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (6.09GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
swagger-viewer|Arj|1.6.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.2.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
terraform|mau|0.0.23
vscode-azureappservice|ms-|0.7.1
vscode-azurefunctions|ms-|0.8.1
vscode-azurestorage|ms-|0.3.0
vscode-azureterraform|ms-|0.1.1
vscode-cosmosdb|ms-|0.6.0
vscode-kubernetes-tools|ms-|0.1.7
mssql|ms-|1.3.1
vscode-ai|ms-|0.1.7
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
csharp|ms-|1.14.0
PowerShell|ms-|1.7.0
resharper9-keybindings|ms-|1.1.0
vscode-azureextensionpack|ms-|0.0.9
team|ms-|1.133.0
azurerm-vscode-tools|msa|0.4.0
azure-hdinsight|msh|0.0.16
debugger-for-chrome|msj|4.3.0
vscode-docker|Pet|0.0.26
vscode-yaml|red|0.0.11
vscode-icons|rob|7.23.0
usql-vscode-ext|usq|0.2.13
application-insights|Vis|0.4.2
azure-iot-edge|vsc|0.2.0
azure-iot-toolkit|vsc|0.6.0
ReactSnippets|xab|2.1.0

</details>

**Comment by Tyriar** [comment]
This is either caused by the PS extension https://github.com/PowerShell/vscode-powershell or by winpty https://github.com/Microsoft/vscode/issues/45693.
