### ISSUE TITLE
Auto-completion with Tab and Enter

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#4878]
- VSCode Version: 0.10.11
- OS Version: Fedora 23, 64bit

It would be great if there's an option for (auto-completion):
- Pressing <kbd>Tab</kbd> will replace the rest.
- Pressing <kbd>Enter</kbd> will insert into current caret position.

Or vice-versa.

Thanks,

**Comment by jrieken** [comment]
not sure if I understand that. @haibison can you clarify what the different between _replace the rest_ and _insert into current care pos_ means?

**Comment by haibison** [comment]
Hi @jrieken,

Thanks. I mean, for example here's the content I'm typing (the pipe is the caret):

    someFunc|Abc

And the auto-completion list offers `someFunction`. Then:

- If I press <kbd>Tab</kbd>, it replaces `Abc` with `tion`, so it would become `someFunction`.
- If I press <kbd>Enter</kbd>, it inserts `tion` into the caret position, so it would become `someFunctionAbc`.

If there's a white space after the caret, then either <kbd>Tab</kbd> or <kbd>Enter</kbd> will just insert the offered text into current caret position (which is current behavior).

**Comment by jrieken** [comment]
Understoof, thanks for clarifying

**Comment by joaomoreno** [comment]
We could provide two different commands here and use the keybindings as a way for the user to customise the behaviour.

**Comment by jrieken** [comment]
Yeah - tho we need to think what is means wrt text edits completion providers describe. Technically they can already do this (just select the corresponding range)...

**Comment by joaomoreno** [comment]
@jrieken How are we on this?

**Comment by Springrbua** [comment]
Eclipse has a setting for this, where you can choose to replace or insert. If you choose to insert, you stil can hit <kbd>ctrl</kbd> + <kbd>enter</kbd> to replace.  
Android Studio (or IntelliJ in general?) has the same feature, where <kbd>tab</kbd> replaces and <kbd>enter</kbd> inserts as much as I remember.
It would be nice, if we could have it in vscode too :)

**Comment by Lamester** [comment]
We need this feature.  It's very annoying, especially when Visual Studio 2017 allows this behavior and VS Code does not.

**Comment by jrieken** [comment]
actually related (maybe same) to #10266

**Comment by silverqx** [comment]
Yeah, replace on `tab` and append on `enter`, i lack this feature too

**Comment by cjbarth** [comment]
Why is it that the older issue is the one marked as duplicate? I would expect that newer issues duplicating existing issues would be the ones marked as duplicates.

**Comment by geekley** [comment]
@jrieken Is this really a duplicate? Has this been implemented? I would expect `"editor.suggest.insertMode"` to have a third option like `replaceWhenTab` to allow both behaviors, like in Android Studio. So that I can choose to insert with ENTER or replace with TAB.
