### ISSUE TITLE
Provide Word-Wrap Provider API

### ISSUE THREAD

**Issue by mhchem** [microsoft/vscode#48797]
I would like to see the possibility to influence the word-wrapping via an extension.

Use cases:

1. Provide the indentation depth of wrapped lines
For instance, for a Markdown document with a bullet list
```
- wrapping like this
  would make more sense
- than wrapping like
this
```

2. Provide possible line breaks. Knowing the semantics, better breakpoints can be found.

For instance

```js
if (bSomething === true && oOther === false || sSomething === false && bOther === true) {
                          ^                   ^                       ^
```

3. Provide mandatory break points (knowing the visible line width)

For instance, breaking like this
```js
if (bSomething === true && oOther === false ||
    sSomething === false && bOther === true) {
```
instead of
```js
if (bSomething === true && oOther === false || sSomething === false && 
bOther === true) {
```
or even
```js
if (bSomething === true && oOther === false || sSomething === false && bOther
=== true) {
```

**Comment by axefrog** [comment]
I raised the same issue a while back but it was closed due to lack of interest:
https://github.com/Microsoft/vscode/issues/17948

**Comment by mhchem** [comment]
@axefrog Similar, but not "the same".
