### ISSUE TITLE
[FIXED] Cannot `Open changes` or `Open File (HEAD)` in the source control panel #4328

### ISSUE THREAD

**Issue by brucejo75** [Microsoft/vscode#48795]
@joaomoreno,

I found and fixed my issue in #43428.  I thought I would write up my fix and how I debugged it hoping to help someone else out in this situation. [I could not add any comments to #43428] because it is closed.

version `1.19.3` worked for me but all versions after that failed.  version `1.20` was where submodule support was introduced into **vscode**.  Which made submodules suspicious.

### Essentially my `.gitmodules` file was messed up.
1. I had previously tried to create a number of sub-modules in my project.
2. After working with it a while I then went back to a larger repository.
3. I deleted my sub-modules, but I did not clean up my `.gitmodules` file as specified [here](https://gist.github.com/myusuf3/7f645819ded92bda6677) or [here](https://davidwalsh.name/git-remove-submodule).  This left a lot of stray submodules in the `.gitmodules` file.
**Note**: my `.git/config` file did not have any evidence of the sub-modules.

Once I cleaned up my `.gitmodules` file I was able to once again `Open Changes` and `Open File (HEAD)`.

### How to test for the issue
I had gone down a number of avenues, but a simple check was to delete the `.gitmodules` file and see if the issue went away.

**Comment by joaomoreno** [comment]
@brucejo75 Pretty cool that you were able to find out what that was. It's interesting how none of the git commands warned the user about such a broken state. Thanks for letting me know, I'll copy your post to the other thread so we keep it together in case more users come with that problem.
