### ISSUE TITLE
Mensaje de Error en Visual studio Code, pide ES6

### ISSUE THREAD

**Issue by arturocoronel100** [Microsoft/vscode#48790]
Buenos dias:
Desde hace unos dias me sale un mensaje de error y es este:

'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). (W104)

y pongo las siguientes lineas en mi archivo js (JavaScript)

{
    "jshint.options": {
      "esversion": 6
    }
  }

A pesar de todo eso sigue saliendo otro mensaje de errror:

';' expected.
Unrecoverable syntax error. (12% scanned). (E041)

Por favor les agradeceria que vean este caso y se pueda resolver todo esto.
Muchas gracias anticipadamente
Atentamente,
Arturo Coronel
arturo_coronel100@hotmail.com

**Comment by mjbvz** [comment]
This error is coming from one of your extensions, likely jshint. Please file the issue against them
