### ISSUE TITLE
ExtensionHostCreashed

### ISSUE THREAD

**Issue by starry-zhao** [Microsoft/vscode#48792]
- VSCode Version:1.22.2
- OS Version:windows10 1803

Steps to Reproduce:

1. Open the vscode and open a python file and it will appear.
2.
![2018-04-27](https://user-images.githubusercontent.com/38775546/39344494-679c02ec-4a15-11e8-97ef-66dac0e9daf9.png)
<img width="960" alt="2018-04-27 3" src="https://user-images.githubusercontent.com/38775546/39344497-696ac626-4a15-11e8-9318-c25ad8cd4ca5.png">

Does this issue occur when all extensions are disabled?: Yes/No
no

**Comment by bpasero** [comment]
@starry-zhao 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by starry-zhao** [comment]
I don't seem to be able to turn on the software, which is always black scree
<img width="960" alt="2018-04-27 4" src="https://user-images.githubusercontent.com/38775546/39345668-58c90bc8-4a1c-11e8-82bb-022e7fee8391.png">
n.

**Comment by bpasero** [comment]
@starry-zhao does it work if you run "`code-insiders --disable-gpu`" from the command line?

**Comment by starry-zhao** [comment]
@bpasero 还是不行，无法正常工作，你可以给我一下您的邮箱吗？我录制了屏幕视频，可以发给您看下。
Still can't, can't work normally, can you give me your mailbox?I recorded video on the screen and I can send it to you.

**Comment by bpasero** [comment]
@starry-zhao I trust you from the screenshot above. But to clarify, you can still run Code (the stable version) and it shows the window but then the extension host crashes or does that also not start anymore?

As for code insiders, can you run `code-insiders --verbose` from the command line and attach the output here?

**Comment by starry-zhao** [comment]
@bpasero 我有些不太明白，您想说什么？
我是想，直接发视频给您，您会不会看得更清楚，可以得到更多的信息。
我这边情况就是稳定版是打开后都正常，但是我打开文件夹时过一小会会弹出扩展宿主意外终止的提示，我本来想说忽略他，但是python的扩展也无法打开了。基本就是这样。
你发给我的预览版，我打开是黑屏状态，无法使用。
I don't quite understand. What are you trying to say?
I just want to send video directly to you, you will not see more clearly, you can get more information.
My side is on the stable release is normal, but when I open the folder a small terminated unexpectedly tips will pop up extension host, said I tried to ignore him, but the python extension cannot open. That's basically it.
The preview you sent to me, I opened the black screen state, can not use.

**Comment by alexandrudima** [comment]
@starry-zhao

* If you disable the python extension, does the extension host crash ?

* If you disable all extensions, does the extension host crash ?

**Comment by starry-zhao** [comment]
@alexandrudima  disable the python extension, The extended host does not crash.
But I only have a python extension.I tried to install a c/c++ extension, although I didn't run c code, but I didn't show the extended host crash.
I think the problem is really python extensions？But for the time being, I'm using him to write python, which is bad if you can't extend it in python.

**Comment by alexandrudima** [comment]
No, that is good news. 

Because now we can direct you to the team which writes the Python extension and they can help troubleshoot with you.

@starry-zhao I'm assuming you have the Python extension from Microsoft. Can you please open a new issue at https://github.com/Microsoft/vscode-python/issues and explain that the extension host crashes when you have the Python extension. You can link to this issue.
