### ISSUE TITLE
WithProgress / progress.report not working as documented?

### ISSUE THREAD

**Issue by njpanderson** [Microsoft/vscode#48793]
- VSCode Version: 1.2.2
- OS Version: Mac Os 10.13.4

Steps to Reproduce:

1. Create progress callback using `vscode.window.withProgress()` and the following options:

```
{
	location: vscode.ProgressLocation.Notification,
	title: 'Push'
}
```

2. Invoke "report" on returned `progress` function using the following data:

```
progress.report({ message: 'any string' });
```

The notification window appears with a progress bar and "Push" as a label, but no message (or for that matter, increment) data appears.

Does this issue occur when all extensions are disabled?: No - my development extension is enabled for debugging. All other extensions are disabled, though.

**Comment by bpasero** [comment]
@njpanderson I cannot reproduce, can you attach your source code?

My test was this:

```typescript
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "test-ts" is now active!');

    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        // The code you place here will be executed every time your command is executed

        // Display a message box to the user
        vscode.window.withProgress({
            location: vscode.ProgressLocation.Notification,
            title: 'Push'
        }, progress => {
            progress.report({ message: 'any string' });
            
            return new Promise((resolve) => {
                setTimeout(() => {
                    resolve();
                }, 5000);
            });
        })
    });

    context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {
}

```

![before](https://user-images.githubusercontent.com/900690/39346219-41a89316-49ed-11e8-8ab4-e680dbd5b04a.gif)

**Comment by njpanderson** [comment]
Thanks for the super fast reply! Of course you can see the full snippet:

```

// Start progress interface
return vscode.window.withProgress({
	location: vscode.ProgressLocation.Notification,
	title: 'Push'
}, (progress) => {
	return new Promise((resolve, reject) => {
		// Globally assign the rejection function for rejection outside
		// of the promise
		this.progressReject = reject;

		progress.report({ message: i18n.t('processing') });

		// Create an interval to monitor the fnProgress function return value
		this.progressInterval = setInterval(() => {
			let state;

			if (typeof fnProgress === 'function') {
				state = fnProgress();
			}

			if (typeof state === 'string') {
				// Value is defined - write to progress
				progress.report({ message: i18n.t('processing_with_state', state) });
			} else {
				// No value - just use a generic progressing notice
				progress.report({ message: i18n.t('processing') });
			}
		}, 10);

		// Execute all queue items in serial
		this.execQueueItems(
			(results) => {
				clearInterval(this.progressInterval);
				this._updateStatus();
				resolve(results);
			}
		);
	});
});
```

 - `this.execQueueItems` just does asynchronous work but is probably safe to just replace with a timeout, running `resolve` after x.
 - `i18n.t` returns a valid string, I've tested this with console logging.
- `fnProgress` is just a callback function defined in the outer function which retrieves progress details - in the least, it should at least say "Processing".

![progress](https://user-images.githubusercontent.com/12379690/39346571-c8518bcc-49e6-11e8-9d92-7f5eb071315b.gif)

**Comment by bpasero** [comment]
@njpanderson can you replace that I18N call with a static string to ensure this is not an issue with that library returning an empty string?

**Comment by njpanderson** [comment]
Yep:

```
						if (typeof state === 'string') {
							// Value is defined - write to progress
							progress.report({ message: 'testing with state' });
						} else {
							// No value - just use a generic progressing notice
							progress.report({ message: 'testing no state' });
						}
```

Tried this in situ - still nothing

**Comment by njpanderson** [comment]
Have just tried the example code you gave me above and that does work too. Will look into this further from my end although not currently seeing any meaningful differences.

**Comment by bpasero** [comment]
@njpanderson please try to come up with a reproducible sample that has no external dependencies. Until then I assume this is a bug with your extension.

**Comment by njpanderson** [comment]
Absolutely fine - totally understand, will try and recreate with a bare module tonight. Very strange!

**Comment by bpasero** [comment]
@njpanderson thanks

**Comment by njpanderson** [comment]
@bpasero I've looked into this further, and I think it might actually be due to the frequency of the `report` calls my code was making.

I've since added logic to only invoke the `progress.report` function when the state has changed, which means that it's called far less frequently (as opposed to being updated every 10ms), and seems to now work.

Do you have any idea if I'm on the right track with my suspicions?

**Comment by bpasero** [comment]
Yeah I think I am buffering the updates to prevent flooding.
