### ISSUE TITLE
Go to defination not work properly of any function or method (PHP)

### ISSUE THREAD

**Issue by DhirenGangal** [Microsoft/vscode#48798]
Issue Type: <b>Bug</b>

When i press F12 key on any called function then dosn't navigate to  defination 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2020 @ 2.90GHz (2 x 2893)|
|Memory (System)|7.90GB (3.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ci-snippets2|Ani|1.0.0
php-debug|fel|1.12.3
jquery-snippets|Hri|1.0.0
mssql|ms-|1.3.1
sublime-keybindings|ms-|3.0.3
code-spell-checker|str|1.6.9

(4 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@DhirenGangal what language are you programming in?

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
