### ISSUE TITLE
change the width of the line number

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#48791]
At present, the default width of the VSCODE line number is large. I want to change it; if you can change it to an adaptive width, I believe it will be better.
![202](https://user-images.githubusercontent.com/20437381/39343052-70a62712-4a0d-11e8-904b-402d18f38a1d.png)

**Comment by lihua06** [comment]
@alexandrudima It is hoped that the default minimum width setting can be added to user settings

**Comment by alexandrudima** [comment]
@lihua06 

```
	"editor.lineNumbersMinChars": 1,
	"editor.glyphMargin": false,
	"editor.folding": false,
```

![image](https://user-images.githubusercontent.com/5047891/39347868-0f2bf830-49f5-11e8-8e3e-ec71cf0b10e2.png)

**Comment by lihua06** [comment]
@alexandrudima thank you

**Comment by lihua06** [comment]
@alexandrudima 
1: "editor.lineNumbersMinChars" Unknown setting parameters
2： How to achieve this effect？it should be able to provide my work effect.
![tim 20180427144304](https://user-images.githubusercontent.com/20437381/39348359-55c191d6-4a29-11e8-9c68-a4a848acf9f2.png)

**Comment by alexandrudima** [comment]
Yes, `editor.lineNumbersMinChars` is an undocumented setting. It will get a warning squiggly, but it will work correctly. Those are indent guides and whitespace.
