### ISSUE TITLE
Unicode characters show as question marks in method documentation hover window

### ISSUE THREAD

**Issue by ktos** [Microsoft/vscode#488]
I have a few methods which documentation contains Unicode (UTF-8) characters. When showing documentation by hovering over a method I get garbage question mark characters instead in this window.

Looks like (when hovering over Jednorożec's constructor):
![2015-11-23](https://cloud.githubusercontent.com/assets/1633261/11335474/c3cee9c4-91dc-11e5-9579-df8edf0ac317.png)

XML documentation for this method:
![2015-11-23 1](https://cloud.githubusercontent.com/assets/1633261/11335478/c61b000a-91dc-11e5-85be-2eee073ef994.png)

All files are saved as UTF-8.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#4
