### ISSUE TITLE
Old 3rd party npm dependencies in core package.json

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#48804]
> Note: if updating brings in new npm modules, you need to register them in the OSS tool before pushing to master!

Please reassign if the assignment is incorrect.

Use the characters: ☑ or ☐

| done | npm module | current | latest | owner |
|---|---|---|---|---|
| ☐ | applicationinsights | 0.18.0 (17 Jan 2017) | 1.0.2 | @ramya-rao-a  |
| ☑ | getmac | 1.0.7 (5 Mar 2015) | 1.4.1 | @chrmarti  |
| ☑ | ~~http-proxy-agent~~ | 0.2.7 (7 Jul 2015) | 2.1.0 | @joaomoreno |
| ☑ | ~~https-proxy-agent~~ | 0.3.6 (7 Jul 2015) | 2.2.1 | @joaomoreno |
| ☑ | ~~iconv-lite~~ | 0.4.19 (10 Sep 2017) | 0.4.21 | @bpasero |
| ☑ | keytar | 4.0.5 (27 Jul 2017) | 4.2.1 | @chrmarti |
| ☑ | ~~semver~~ | 4.3.6 (1 Jun 2015) | 5.5.0 | @joaomoreno |
| ☑ | ~~sudo-prompt~~ | 8.0.0 (2 Nov 2017) | 8.2.0 | @bpasero |
| ☑ | ~~v8-inspect-profiler~~ | 0.0.7 (8 Dec 2017) | 0.0.8 | @jrieken |
| ☑ | ~~yauzl~~ | 2.8.0 (22 Apr 2017) | 2.9.1 | @joaomoreno |

Please use `yarn add MODULE` to upgrade the dependencies.

fyi @egamma

**Comment by chrmarti** [comment]
keytar was already registered. I've now registered getmac. There appears to be a way to automate registration: https://docs.opensource.microsoft.com/using/automated-registration.html

**Comment by bpasero** [comment]
@alexandrudima @chrmarti this is not just about OSS right, this is to update the dependency to latest in debt week?

**Comment by alexandrudima** [comment]
Yes, this issue is about upgrading to newer npm dependencies...

If the upgrade results in usage of new 3rd party npm modules, then those must be registered in the OSS tool.

**Comment by bpasero** [comment]
**Verification `iconv-lite`:**
* Verify you can save as different encoding (e.g. cp1252)

**Verification `sudo-prompt`:**
* Windows: try saving a admin protected file (e.g. something from program files)
* Linux: try saving an admin protected file (e.g. etc/hosts)

**Comment by ramya-rao-a** [comment]
There is a separate issue #44052 tracking the update of the application insights module.
Closing this issue as the rest of the items are checked off.
