### ISSUE TITLE
LineStart and LineEnd editor keyboard shortcuts

### ISSUE THREAD

**Issue by mrahhal** [Microsoft/vscode#4880]
The only thing keeping me away from vscode are the following shortcut configurations (which I make heavy usage of) that exist in Visual Studio as well as other editors like atom:

- Editor.LineStart (just like the `home` button)
- Editor.LineEnd (just like the `end` button)

The reason is that for example I like to assign `alt+A` to LineStart which is much more accessible than `home`.

**Comment by alexandrudima** [comment]
@mrahhal Would the following rule in your `keybindings.json` work? (Preferences > Keyboard Shortcuts):

```json
// Place your key bindings in this file to overwrite the defaults
[
{ "key": "alt+a", "command": "cursorHome", "when": "editorTextFocus" }
]
```

**Comment by mrahhal** [comment]
Yes! This does work. I used:

```
[
	{ "key": "alt+a", "command": "cursorHome", "when": "editorTextFocus" },
	{ "key": "alt+d", "command": "cursorEnd", "when": "editorTextFocus" }
]
```

Thanks.
