### ISSUE TITLE
Markdown: Change Preview Security Settings command does not work when preview is active

### ISSUE THREAD

**Issue by lankymart** [Microsoft/vscode#48809]
This is a re-report of an existing issue that was closed, but I'm still experiencing it.

https://github.com/Microsoft/vscode/issues/39387

Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T17:28:16.777Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

Steps to Reproduce:

1. Open Untitled file.
2. Change the file syntax to markdown.
3. Click the Preview button to bring up the markdown preview.
4. Add an HTTP image to the markdown, to trigger the Blocked Content Message in the preview pane.
5. Click on the Blocked Content Message to bring up the Command Window options for Markdown: Change Preview Security Settings command.
6. Select an option and nothing happens.

Does this issue occur when all extensions are disabled?: Yes

If the command is run without the preview pane open it works fine, it seems specifically related to the preview pane and the Blocked Content Message.

**Comment by mjbvz** [comment]
I can't repo this in VS Code insiders. Can you please test this on insiders and ensure you select the `Allow insecure content` option:

![screen shot 2018-04-27 at 12 57 49 pm](https://user-images.githubusercontent.com/12821956/39382528-a022b7e6-4a1a-11e8-8a26-6daf2ab94c17.png)

**Comment by lankymart** [comment]
Sorry @mjbvz, I didn't realise this wasn't in the release version yet. Will look at getting the insiders build in future before posting an issue.

**Comment by lankymart** [comment]
Just downloaded the Insiders release and tested and cannot reproduce, sorry for not checking this first.
