### ISSUE TITLE
Make zen-mode more "zen"-able

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/vscode#48811]
Right now I have some distraction lines in zen-mode. This is the dark line on the left side and ugly scrollbar with minimap (you can also resize zen pane by dragging those things). I didn't find the way to hide those things for zen-mode only.

![screen shot 2018-04-27 at 12 52 36](https://user-images.githubusercontent.com/46930/39356975-197216d8-4a1a-11e8-9806-2c4f6115ebbb.png)

- VSCode Version: 1.22.2
- OS Version: macOS 10.13.4

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/45617
