### ISSUE TITLE
Cannot click to move cursor in terminal

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#48814]
I would like to move the cursor in the terminal on the current command line using the mouse:

![image](https://user-images.githubusercontent.com/5047891/39358308-f38f2338-4a15-11e8-902d-182601312627.png)

I need to replace `src` in that path with `out` and I'm stuck with pressing alt+left repeatedly to get to that position.

I would like to be able to click to go there.

**Comment by Tyriar** [comment]
@alexandrudima did alt+click not work? https://code.visualstudio.com/updates/v1_21#_move-cursor-with-altclick

**Comment by alexandrudima** [comment]
oh cool, I didn't know about alt+click.
