### ISSUE TITLE
Allow tasks to run commands from the Command Palette

### ISSUE THREAD

**Issue by TuurDutoit** [Microsoft/vscode#48818]
It would be very nice to be able to run commands in the Command Palette from a Task in `tasks.json`.

For example, I have a task that builds my Java webapp with Maven and I have the Tomcat plugin installed (`adashen.vscode-tomcat`). This plugin defines a few commands, including one to deploy a war file to the Tomcat server. It would be very handy to be able to create a task that automatically deploys the war built by the Maven task to the running Tomcat server, by calling the appropriate command in the Command Palette.

This new tasks.json could look something like this:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "type": "shell",
            "command": "mvn -B verify",
            "group": "build"
        },
        {
            "label": "Deploy",
            "type": "command",
            "command": "adashen.vscode-tomcat:tomcat.war.run",
            "args": ["/home/tuur/Projects/MyApp/target/app.war"]
        }
    ]
}
```

A way of chaining commands would also be a great help: this way, the Deploy task could automatically call the Build task.

My current environment:
```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by dbaeumer** [comment]
Just to clarify: you want that a tasks triggers a command instead of executing a shell. Then this dups https://github.com/Microsoft/vscode/issues/11396.

Chaining tasks is possible. use `"dependsOn": ['Build']` in task `Deploy`.

OK to close ?

**Comment by TuurDutoit** [comment]
Yep, that's it. Didn't find that issue when searching...

Is `dependsOn` in the docs? I can't seem to find it there.

Thanks for the info though! OK to close for me.

**Comment by dbaeumer** [comment]
I have an item for the doc somewhere. Closing.
