### ISSUE TITLE
FileSystemProvider: saving with UTF-* encodings does not seem to work properly

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48813]
Refs: https://github.com/Microsoft/vscode/issues/48421

**Setup:**
* clone https://github.com/Microsoft/vscode-extension-samples/tree/master/nodefs-provider-sample
* F5
* open a workspace with a `datei://` root folder

**Steps**
* open a file
* click on the encoding picker to select "Save with encoding"
* select any of the UTF-8 encodings (with BOM, UTF-16 LE, UTF-16 BE)
* file gets saved properly
* close file
* reopen file

=> you see garbage (for UTF-16)
=> there is no BOM (for UTF-8 with BOM)

When I check the saved files, they do not seem to have a proper encoding (checked using HEX dump extension):
* UTF-8-with BOM: does not have the BOM as first byte
* UTF-16 LE/BE: does not have the typical UTF-16 structure where either the little or big endian is a 0-byte

I think my file system provider is correctly implementing the `readFile`/`writeFile` methods because I work with Buffer and never to any string conversion nor use encodings when reading or writing.

**Comment by jrieken** [comment]
Muhaha, great find. The writeFile-logic is using a decode-stream and not en encode-stream: https://github.com/Microsoft/vscode/blob/9a7fe683a8b938718a3b6015faca28f2d145e20f/src/vs/workbench/services/files/electron-browser/remoteFileService.ts#L475

**Comment by bpasero** [comment]
@jrieken yup better, though the BOM seems to not be present still. I can file a separate issue on that to mark this one as verified. 

The contract basically is, depending on what encoding is picked to save a file:
* `UTF-8`: we do not automatically add a UTF-8 BOM
* `UTF-8` with BOM: we add the UTF-8 BOM because the user explicitly asked for it
* `UTF-16 LE`: we always add a UTF-16 BOM because this makes it easier for us to not falsely think the file is binary
* `UTF-16 BE`: we always add a UTF-16 BOM because this makes it easier for us to not falsely think the file is binary

UTF-8 with BOM is not a real encoding in node or `iconv-lite`, but we have it in our world for the particular case of adding an explicit UTF-8 BOM to the file.

**Comment by bpasero** [comment]
Forgot one case: If the file is `UTF-8` with a BOM already and we save it, we do not remove the BOM but preserve it.

**Comment by jrieken** [comment]
Is that something we should add in the encoding utils? https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/encoding.ts#L124 
I'd feel dirty copying the code...

**Comment by bpasero** [comment]
@jrieken I have extracted that into https://github.com/Microsoft/vscode/issues/48826
