### ISSUE TITLE
Drag from "Open File" dialog

### ISSUE THREAD

**Issue by nblackburn** [Microsoft/vscode#48812]
Issue Type: <b>Bug</b>

- Click File.
- Click "Open File...".
- Drag a file from the dialog into the editor.
- The editor should crash.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|7.94GB (2.04GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitkraken-glo|axo|1.0.2
cacher-vscode|Cac|1.0.3
npm-intellisense|chr|1.3.0
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.4
EditorConfig|Edi|0.12.1
vscode-npm-script|eg2|0.3.3
theme-monokai-pro-vscode|mon|1.1.6
python|ms-|2018.3.1
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.3.0
vetur|oct|0.11.7
vscode-docker|Pet|0.0.26
code-settings-sync|Sha|2.9.0

(1 theme extensions excluded)

</details>

**Comment by JsonWud** [comment]
I'm still seeing this in what appears to be the latest version of vscode on Windows 10:

Version: 1.29.0 (user setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Today I made the same error, inadvertently mixing two different styles of opening a file. I also replicated it with all extensions disabled.

**Comment by nblackburn** [comment]
I can confirm that this issue is still present in the latest version of VSCode.

```
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by nissan18** [comment]
The issue is still present in:
```
Version: 1.28.2 (user setup)
Date: 2019-03-14
Electron: 3.1.6
Chrome: 66.03359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS version: Windows_NT x64 10.0.15063
```

**Comment by nblackburn** [comment]
Seems to be fixed in the newer releases.

```
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by nissan18** [comment]
I am on exactly the same version but the issue still occurs for me.
