### ISSUE TITLE
[cpp] Switching to Atom's language-c for C/C++ syntax highlighting

### ISSUE THREAD

**Issue by jamesqo** [Microsoft/vscode#4881]
TextMate's [repo](https://github.com/textmate/c.tmbundle) for C/C++ syntax highlighting doesn't look like it's been updated in a while, while Atom's JSON-based equivalent is being [actively maintained](https://github.com/atom/language-c/commit/4c6e4f971429ec235cfb664387dea6dade25d38b) and is easier to read. Should we switch to the latter?

Related issue I opened on Linguist about this: github/linguist#2932

cc @aeschli

**Comment by egamma** [comment]
// CC @asthana86
