### ISSUE TITLE
slash(/)  in branch name causes error

### ISSUE THREAD

**Issue by awebdeveloper** [Microsoft/vscode#48815]
- VSCode Version: 1. 12
- OS Version: Mac osx sierra 

Steps to Reproduce:

1. Create a branch with / in it
2. Try to push/publish it 

Get the following error 

```
fatal: upstream branch 'refs/heads/build/task' not stored as a remote-tracking branch
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by awebdeveloper** [comment]
branch name is "build/task"

**Comment by awebdeveloper** [comment]
no build branch doesnt exists

**Comment by joaomoreno** [comment]
Can you push from the command line?

**Comment by joaomoreno** [comment]
What syntax do you use in the command line?

You can use `Git: Show Git Output` and run the action to see what syntax VS Code uses.

**Comment by awebdeveloper** [comment]
I use just plain **git push**. I have set an upstream though

This is what crashes

fatal: upstream branch 'refs/heads/build/task' not stored as a remote-tracking branch

**Comment by joaomoreno** [comment]
Can you show me your full config file? `cat .git/config`

**Comment by awebdeveloper** [comment]
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
        hooksPath = .githooks
[remote "origin"]
        url = ssh://........./Web
        fetch = +refs/heads/develop:refs/remotes/origin/develop
[branch "develop"]
        remote = origin
        merge = refs/heads/develop
[branch "build/task"]
        remote = origin
        merge = refs/heads/build/task
```

**Comment by joaomoreno** [comment]
This is the command we run to find out what is the upstream of a certain branch:

```
git rev-parse --symbolic-full-name build/task@{u}
```

Can you run it on your repo?

**Comment by awebdeveloper** [comment]
I get 

`fatal: no upstream configured for branch build/task`

**Comment by awebdeveloper** [comment]
need any more info @joaomoreno

**Comment by joaomoreno** [comment]
Interesting. Then run `git branch --set-upstream-to=origin/build/task`. This will setup the upstream.

**Comment by awebdeveloper** [comment]
error: the requested upstream branch 'origin/build/task' does not exist
hint:
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint:
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.

**Comment by joaomoreno** [comment]
So does that branch appear in `git branch -r`?

**Comment by awebdeveloper** [comment]
no...it doesnt

**Comment by joaomoreno** [comment]
So... when you run `git push` to what remote branch does it push to?

**Comment by awebdeveloper** [comment]
i have set up git push as matching(same branch only mode.....whatever its called). So it gets pushed to /build/task

**Comment by joaomoreno** [comment]
Excellent... but you just told me there's no such `build/task` branch on your remote.

**Comment by awebdeveloper** [comment]
the issue seems to be that i cloned with depth=1.
