### ISSUE TITLE
Ctrl+click should always navigate to class

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#48820]
Issue Type: <b>Feature Request</b>

In my NodeJS project, I have 2 files: `base.js` and `foo.js`

### `base.js`
```js
module.exports = class Base {
	constructor() {
		console.log( "base" );
	}
}
```

### `foo.js`
```js
const Base = require( "./base" );

class Foo extends Base {
	bar() {
		const base      = new Base();
		const BaseClass = Base;
	}
}
```

When you ctrl+click on the `Base` in `new Base()` in `foo.js`, you are sent to the constructor, which is understandable and convenient IMHO.

When you ctrl+click on the `Base` in the line below, you are sent to the `require` statement in the same file.

I understand the distinction, but I often find it confusing in everyday operation, because I usually just want to navigate to the file that contains the class, regardless of the context the class name is in.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment]
The `Go to type definition` command should already do you describe. 

I've also opened https://github.com/Microsoft/TypeScript/issues/23742 to track this issue on the TS side
