### ISSUE TITLE
Request an Icon like Eclipse on Linux

### ISSUE THREAD

**Issue by vanduc1102** [Microsoft/vscode#4882]
Can you guys provided an icon or linux version like Eclipse did, So that when I create a shortcut on Ubuntu. I can assign the icon for shortcut. 
Thanks

**Comment by Tyriar** [comment]
.deb packages are coming in the upcoming release which will installs a .desktop entry as well as a bin command. It's currently available on the insiders build: http://code.visualstudio.com/insiders
