### ISSUE TITLE
Use $customized instead of custom for customized tasks. 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#48835]
According to the API doc reserved type need to start with $.

**Comment by dbaeumer** [comment]
Moving to June. This is too risky to fix so late in the endgame. Should be a little bit in insiders.

**Comment by isidorn** [comment]
Not for july, pushing out to August since dirk is on vacation

**Comment by dbaeumer** [comment]
This needs verification in code since it was a debt item. Nothing visible to the outside to verify.

**Comment by dbaeumer** [comment]
Done the code verification.
