### ISSUE TITLE
C++ toggle header / cpp keymap (Ctrl+K Ctrl+O)

### ISSUE THREAD

**Issue by almaasrawi** [Microsoft/vscode#48843]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open a C++ project
2. open a cpp file
3. Press Ctrl+K Ctrl+O

Expected:
 Open the corresponding header file

Actual:
 Open the Open File dialog

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment]
After installing the [C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools), the default keybinding for command `C/C++: Switch Header/Source` is <kbd>Alt</kbd> + <kbd>O</kbd>, or you can change it to anything you want in the Keyboard Shortcut settings.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
