### ISSUE TITLE
Breakpoints are ignored in Ruby debugger

### ISSUE THREAD

**Issue by udiudi** [Microsoft/vscode#48848]
Issue Type: <b>Bug</b>

I'm running Ruby 2.5.1 and Rails 5.2 project. 
I usually run RSpec and Rails server with the debugger, it used to work in the past, but now when I add breakpoints to a spec or a Rails controller the breakpoint is ignored (but for sure the code runs).

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.0.1
vscode-docker|Pet|0.0.26
rails|bun|0.5.7
solargraph|cas|0.16.0
path-intellisense|chr|1.4.2
gitlens|eam|8.2.4
vscode-npm-script|eg2|0.3.3
ruby|gro|0.0.6
ruby-rubocop|mis|0.7.0
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|3.0.3
Ruby|reb|0.18.0
vscode-icons|rob|7.23.0
sass-indented|rob|1.4.9
ayu|tea|0.14.0
simple-ruby-erb|vor|0.2.1
vscode-import-cost|wix|2.6.2
JavaScriptSnippets|xab|1.6.0

(3 theme extensions excluded)

</details>

**Comment by weinand** [comment]
Please file this issue against the Ruby debugger extension.
