### ISSUE TITLE
Difficult to read intellisense popup box

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/vscode#4884]
**Visual Studio Code** (version 0.10.11 on Windows 10586.164):
![image](https://cloud.githubusercontent.com/assets/9047283/14229163/73d5eb04-f92c-11e5-9963-49df1a64e733.png)

Source code, documentation, signature, all look almost the same. The following issues make it difficult to read:
- Same background as the underlying text view
- Same font and color as source code for documentation and signature, even line heights matches
- Difficult to see where does documentations ends and where does the actual signature begins
- Signature is incorrectly syntax highlighted: only the const keyword is highlighted, while any or any other type is not
- Wraps the signature into multiple lines which makes it more difficult to read, even if I still have a bunch of space horizontally on my screen
- **+1** Links in the documentation text look like highlighted keywords. First thought was it is a bug: even the text is colorized, then seen that they are links.

![image](https://cloud.githubusercontent.com/assets/9047283/14229256/6bacae60-f92f-11e5-8fe5-b5b8eaafe5a0.png)

For reference, **Visual Studio**:
![image](https://cloud.githubusercontent.com/assets/9047283/14229203/a5f05be6-f92d-11e5-8228-ee48ac4569fd.png)
- Different background and typography, it does not feel like it is embedded into the editor (the other one looks like an area in the editor with a border, there is no depth)
- Documentation and signature is separated visually
- Signature colorized correctly (keywords, types, identifiers)
- Signature is not wrapped into multiple lines

Steps to Reproduce:
1. Hover on anything

**Comment by Tyriar** [comment]
Ping @bgashler1

**Comment by alexandrudima** [comment]
fyi @jrieken @joaomoreno

**Comment by joaomoreno** [comment]
Please update to the latest version of VS Code.

**Comment by joaomoreno** [comment]
Actually, just a duplicate long lost in time.
