### ISSUE TITLE
"Property processName is not allowed." in launch.json

### ISSUE THREAD

**Issue by hsandt** [Microsoft/vscode#48844]
- VSCode Version: 1.22.2
- OS Version: Windows 10

The config.json parser does not recgonize the new processName parameter, only the processId one. Therefore, if you put processName but not processId, you'll get 2 warnings in the issues list:
- Missing property "processId"
- Property processName is not allowed.

Steps to Reproduce:

1. Create a launch.json configuration with this:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processName": "my_program.exe"
        }
    ]
}

2. Open the Issues panel or go to next error (F8) to see the 2 errors mentioned at the beginning.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
If someone introduces a new attribute like "processName", the schema must be updated too.
File this issue against the "cppvsdbg" extension.

**Comment by hsandt** [comment]
Done on https://github.com/Microsoft/vscode-cpptools/issues/1904
