### ISSUE TITLE
PROBLEMS pane: file path is not correctly prefixed with forward slash `/`

### ISSUE THREAD

**Issue by zfields** [Microsoft/vscode#48841]
**Example output from file pane:**
```
src_file.cpp Users/zfields/dev/source/application/lib/src_file.cpp
* use of undeclared identifier 'id' (213,5)
```

When I click on the problem, I get the following error message.

**Error message:**
```
Unable to open 'src_file.cpp': File not found
(file:///Users/zfields/dev/source/application/Users/zfields/dev/source/application/lib/src_file.cpp).
```

It looks like **VSCode** is trying to use a relative path from `${workspaceFolder}`, even though the PROBLEMS pane is showing an absolute-ish path. Perhaps the path from the PROBLEMS pane would be appropriately identified as an absolute path if it was prefixed with a forward slash `/`.

**Comment by sandy081** [comment]
URI is provided by the markers service and is used to open it in the editor. Forwarding it to @jrieken

**Comment by jrieken** [comment]
It's the extension that feeds those uris into the system. @zfields please forward this to the cpp-extension. Thanks

**Comment by zfields** [comment]
Since Microsoft is the creator of the extension in question, it's a little bit surprising that you are acting like to two companies, instead of two teams in the same company.

Why didn't you forward the issue to the appropriate team, instead of simply closing the issue. This is terrible customer service. Remember, Microsoft owns the problem, I just let Microsoft know it has one.

**Comment by sean-mcmanus** [comment]
@zfields The error messages you show do not appear to be from a Microsoft managed extension. I'm not sure which extension it's from, so I'm not sure where to forward the issue. If you use the Help->Report Issue in VS Code it should attach the installed extensions to the bug report.

In regards to "customer service" and forwarding bugs to the correct location, I'm not aware of any strict Microsoft policy...sometimes we tell users to create the issue at the correct spot themselves and other times we'll create the bug for them (if we feel like it)...there are pros/cons with each approach.

I remember seeing some cases where C++ extension bugs were filed in the vscode issues page, but the user never forwarded the bug to the C++ issues page, so it was lost, which is bad for our C++ extension, but one would expect the bugs would eventually get reported at the correct location by other users.

**Comment by zfields** [comment]
@sean-mcmanus 

I hope you can see how this attitude is problematic...
> "I'm not aware of any strict Microsoft policy..."
>  "...we'll create the bug for them (if we feel like it)"

Which leads to problems (for you) like these...
> "...bugs were filed in the vscode issues page, but the user never forwarded the bug to the C++ issues page, so it was lost, which is bad for our C++ extension"

Not to mention, your attitude is alienating people like me, who are trying to use Microsoft software (the reason you have a job) and do your team a solid by reporting your bugs (allows you to improve your software).

**Comment by bobbrow** [comment]
I think it's just a poorly coded bot that closed your issue.  The VSCode team used to forward issues to us, but I understand there are issues of scalability with this process.  @jrieken, could perhaps a tag be added for certain high traffic extensions and the bot could consume that data and do the forwarding?  I can open a new suggestion for that and I think it would improve the experience for everyone.
