### ISSUE TITLE
Search takes 3-6 presses of <enter> before actually searching

### ISSUE THREAD

**Issue by simonlast** [Microsoft/vscode#48849]
Issue Type: <b>Bug</b>

1. Open search
2. Type a search query
3. Press enter. The first few times it doesn't search. Eventually, after 3-6 presses it will finally search.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
wrap|dt|0.0.1
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
path-autocomplete|ion|1.9.0
vscode-lua|tri|0.12.4
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.1

</details>

**Comment by simonlast** [comment]
Ah, I just tried again and you're right. It takes a good 5 seconds or so to actually perform the search. I'm on a very large repo.

**Comment by simonlast** [comment]
Is there anything that can be done about this?

**Comment by roblourens** [comment]
- If your repo has lots of symlinks, try the `"search.followSymlinks"` setting
- Or use the `.exclude` settings or the "files to include/exclude" text boxes to narrow down the search
- Also see this new wiki page: https://github.com/Microsoft/vscode/wiki/Search-Issues
