### ISSUE TITLE
Option to not collapse search results

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#48842]
In search results view, if a file has many results its node appears collapsed. There should be an option to disable that or specify a number of results over which the node will be collapsed.

Many times I run a search with many results across many files and think I'm looking at all the results in front of me, but it turns out I missed a collapsed node in the middle with many results underneath. It's very easy to miss so I want to disable that feature.

**Comment by roblourens** [comment]
Just got a request for the opposite :)

This would cover customizing the collapse behavior in the search view: https://github.com/Microsoft/vscode/issues/48641
