### ISSUE TITLE
Typescript syntax highlighting of method signatures broken when long lines are wrapped.

### ISSUE THREAD

**Issue by majelbstoat** [Microsoft/vscode#48858]
Using 1.22.2, Typescript 2.8.1

Syntax highlighting is correct in the first screenshot:
<img width="1012" alt="screenshot 2018-04-27 13 12 22" src="https://user-images.githubusercontent.com/425787/39383133-fe71095e-4a1c-11e8-8737-88ac8888a94c.png">

When wrapped due to line length, the highlighting is somewhat broken:
<img width="699" alt="screenshot 2018-04-27 13 12 38" src="https://user-images.githubusercontent.com/425787/39383134-fe893074-4a1c-11e8-9c5c-302ec6bbf78b.png">

(I searched, couldn't find a duplicate)

**Comment by mjbvz** [comment]
Please share the text from those screenshots

**Comment by majelbstoat** [comment]
```typescript
  urls = (
    name: string,
    params: { [key: string]: string | number } = {},
    extra: { [key: string]: string | number } = {}
  ): URLPair => {
    // ... 
  }
```

**Comment by mjbvz** [comment]
Thanks. Seems fixed in VS Code insiders:

![screen shot 2018-04-27 at 4 04 35 pm](https://user-images.githubusercontent.com/12821956/39388415-b6c334e8-4a34-11e8-9fb9-55ba6bba42a3.png)
