### ISSUE TITLE
Search shows duplicate matches through symlinks

### ISSUE THREAD

**Issue by dapirian** [Microsoft/vscode#48856]
If you have symlinks in a directory to file in the same directory and search for a term in the file, it'll show duplicate matches from each symlinked file plus the actual file. Every other editor figures out not to do this, even `grep` doesn't show duplicate results. On Ubuntu, 1.22.2

**Comment by roblourens** [comment]
You can set `"search.followSymlinks": false` to prevent it from following symlinks. Looks like grep just doesn't follow symlinks by default.
