### ISSUE TITLE
 Cannot read property 'inputBox' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#48851]
Issue Id: <b>686f19bf-01f4-ecf6-2159-252574f59930</b><br /><br />*Versions* <br />- 1.23.0-insider (4/24/2018 5:14:33 AM)<br />-  f4b63ac06955bd1ea220b851a79bd0ae5315fb0c<br />-  36e6cbb7667e7874748d8fbf2021b743d2d90afc<br />*Stack* <br />TypeError: Cannot read property 'inputBox' of undefined<br />[/vs/workbench/browser/parts/quickinput/quickInput.ts#436:16 (localize)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/workbench/browser/parts/quickinput/quickInput.ts#L436:16 (localize))<br />[/vs/workbench/common/theme.ts#397:7 (editorWidgetBackground)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/workbench/common/theme.ts#L397:7 (editorWidgetBackground))<br />[/vs/workbench/common/theme.ts#390:5 (call)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/workbench/common/theme.ts#L390:5 (call))<br />[/vs/base/common/event.ts#140:15 (colorCustomizations)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/base/common/event.ts#L140:15 (colorCustomizations))<br />[/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#239:49 (findThemeDataBySettingsId)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#L239:49 (findThemeDataBySettingsId))<br />[/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#207:24 (onComplete)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#L207:24 (onComplete))<br />[/vs/base/common/winjs.base.js#1185:0 (_notify)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/base/common/winjs.base.js#L1185:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0 (_run)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/base/common/winjs.base.js#L1083:0 (_run))<br />[/vs/base/common/winjs.base.js#1051:0 (onComplete)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/base/common/winjs.base.js#L1051:0 (onComplete))<br />[/vs/base/common/winjs.base.js#1581:0 (then)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/base/common/winjs.base.js#L1581:0 (then))<br />[/vs/base/common/winjs.base.js#762:0 (enter)](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/base/common/winjs.base.js#L762:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0](https://github.com/microsoft/vscode/blob/b845ce918f2689344795e845ae6ef691916c3079/src/vs/base/common/winjs.base.js#L1083:0)<br />    at n.Class.derive._creator._setCompleteValue (out/vs/workbench/workbe<br />

**Comment by ramya-rao-a** [comment]
Closing as I was testing the tool
