### ISSUE TITLE
File is a CommonJS module; it may be converted to an ES6 module.

### ISSUE THREAD

**Issue by Yugloocamai** [Microsoft/vscode#48859]
I know this issue was recently closed, but they locked the thread and the final answer provided by @mjbvz is incorrect.  He stated that you must **add "javascript.suggestionActions.enabled": false to your user settings**, but it needs to be added to your WORKSPACE settings, not user settings.  Hopefully he'll update the other thread with the correct answer.

**Comment by mjbvz** [comment]
The setting live in either your user settings or workspace settings. The workspace settings will override the one in your user settings
