### ISSUE TITLE
After the last update, all my extensions have been reenabled

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/vscode#48852]
Issue Type: <b>Bug</b>

I updated VSCode to the latest insider version, and suddenly all my extensions were enabled. Many of them were deliberately disabled before, and now I have to clean up the mess...

VS Code version: Code - Insiders 1.23.0-insider (e679bfee4360cb1bc152e6e0ea7583d8d042e07e, 2018-04-27T08:46:53.881Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (4.06GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (103)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rebound-delete|aar|1.1.0
paste-fixer|aar|1.0.0
html-snippets|abu|0.2.1
calculate|aca|2.0.0
vscode-caniuse|aka|0.5.3
Bookmarks|ale|0.19.0
read-only-indicator|ale|0.7.0
vscode-lcov|ale|0.2.0
vscode-color|ans|0.4.5
amvim|aui|1.25.0
code-gnu-global|aus|0.2.2
Doxygen|bbe|1.0.0
solidity-extended|bea|3.0.2
addfileextension|bgs|0.1.4
htmltagwrap|bra|0.0.7
vscode-standardjs-snippets|cap|0.7.7
vscode-standardjs|che|1.2.1
npm-intellisense|chr|1.3.0
bracket-select|chu|0.0.1
jsrefactor|cms|2.11.7
gitignore|cod|0.5.0
compulim-vscode-closetag|Com|1.1.0
riot-tag|cri|0.1.7
autoit|Dam|0.1.8
vscode-markdownlint|Dav|0.15.0
jshint|dba|0.10.18
vscode-eslint|dba|1.4.8
vscode-instant-markdown|dba|1.4.1
vscode-hasher|dee|1.0.1
vscode-new-file|dku|4.0.2
vscode-npm-source|dku|1.0.0
githistory|don|0.4.0
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
gitlens|eam|8.2.4
EditorConfig|Edi|0.12.1
vscode-npm-script|eg2|0.3.3
LogFileHighlighter|emi|2.4.0
vscode-npm|fkn|3.3.0
StackSearchExt|gcr|0.0.2
gc-excelviewer|Gra|2.0.20
CppSnippets|har|0.0.13
beautify|Hoo|1.3.0
JSDocTagComplete|Hoo|0.0.2
minify|Hoo|0.3.0
base-converter|hoo|0.0.1
RelativePath|jak|1.4.0
hungry-delete|jas|1.5.0
docthis|joe|0.6.0
join-comment-aware|joh|0.0.3
typings-autoinstaller|jvi|1.2.0
format-indent|Kas|1.3.0
Lua|key|0.0.9
vscode-nsis|Kry|0.0.1
vs-color-picker|lih|0.7.0
VBScript|lug|0.0.2
ftp-sync|luk|0.3.3
edge|luo|0.2.0
rainbow-csv|mec|0.2.1
dotenv|mik|1.0.1
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
find-jump|mks|1.2.4
prettify-json|moh|0.0.3
python|ms-|2018.3.1
cpptools|ms-|0.16.1
PowerShell|ms-|1.7.0
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.3.0
node-modules-resolve|nau|1.0.2
createGUID|nwa|0.0.2
new-cmd|odo|0.2.0
ejs-language-support|Qas|0.0.1
quicktype|qui|10.0.24
json-organizer|rin|0.0.3
LiveServer|rit|3.2.1
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
vscode-coverage-gutters|rya|1.3.1
bracket-jumper|sas|1.1.8
code-settings-sync|Sha|2.9.0
trailing-spaces|sha|0.2.11
vscode-autohotkey|sle|0.2.2
slack|soz|0.0.14
pasteandformat|spo|0.0.5
guides|spy|0.9.1
addDocComments|ste|0.0.8
rewrap|stk|1.8.1
code-spell-checker|str|1.6.9
ignore-gitignore|stu|1.0.1
js-complexity-analysis|Tom|2.0.0
sort-lines|Tyr|1.6.1
bracket-padder|via|0.0.1
vscode-devdocs|ben|0.1.0
gitblame|wad|2.4.2
quokka-vscode|Wal|1.0.121
vscode-todo-highlight|way|0.5.12
bootstrap-3-snippets|wcw|0.1.0
change-case|wma|1.0.0
join-lines|wma|0.2.2
FilterText|yhi|0.0.8
html-css-class-completion|Zig|1.17.1

</details>

**Comment by usernamehw** [comment]
Maybe restoring from backup could help: https://github.com/Microsoft/vscode/issues/47320#issuecomment-379250378

**Comment by bpasero** [comment]
Sorry for that, was related to a electron update we played around with, should not happen again.
