### ISSUE TITLE
TypeScript syntax highlighting is broken when using backticks and equals signs on a single line

### ISSUE THREAD

**Issue by niieani** [Microsoft/vscode#48857]
- VSCode Version: 1.23-0-insider
- OS Version: macOS

<img width="649" alt="screen shot 2018-04-27 at 22 00 15" src="https://user-images.githubusercontent.com/563469/39382633-6f918dae-4a66-11e8-8608-5cc502e57281.png">

## Steps to Reproduce:

1. Enter the following code in a .ts file:

```ts
const example = () => (
  {example: "`x=y`"} // everything after this line is highlighted like a string
)

const brokenHighlighting = true
```

Interestingly, the same issue occurs with:

```ts
const example = () => (
  {example: `x=y`} // everything after this line is highlighted like a string
)

const brokenHighlighting = true
```

But it does **not** occur when the preceding bracket `(` is on the same line as `{`:

```ts
const example = () => ({
  example: "`x=y`"
})
```

Does this issue occur when all extensions are disabled?: **Yes**

This does not occur in latest stable v1.22.2, so this is a regression.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#608
