### ISSUE TITLE
Monokai button focus color is too similar to checkbox enabled border color

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#48855]
Checkbox toggled on
![image](https://user-images.githubusercontent.com/323878/39381631-a3135da0-4a17-11e8-99ff-e62f42e9afca.png)

Checkbox focused
![image](https://user-images.githubusercontent.com/323878/39381639-a83f5b1c-4a17-11e8-89aa-2ecaae80a7cb.png)

Dark+ has a brighter color for "toggled on" and dimmer for "focused"

**Comment by mick-io** [comment]
I can tackle this.

**Comment by roblourens** [comment]
Sure! 🎉

**Comment by mick-io** [comment]
Pull request submitted. Thanks for the opportunity.
https://github.com/Microsoft/vscode/pull/48867

**Comment by roblourens** [comment]
I think this is waiting on general icon work in #8017

**Comment by roblourens** [comment]
Closing as dupe of #8017
