### ISSUE TITLE
Copy/cut and pasting not working while fired another event like shift+delete

### ISSUE THREAD

**Issue by sumit14078** [Microsoft/vscode#48854]
Issue Type: <b>Bug</b>

1. Copy/cut text.
2. Fire shortcut key like ( shift + delete ).
3. Now try to paste the copied text ( not going to paste any single character).

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.89GB (4.43GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
By default, <kbd>Shift</kbd>+<kbd>Delete</kbd> will **write** to the clipboard even when nothing is selected.

You can use `"editor.emptySelectionClipboard": true` to disable writing to the clipboard when nothing is selected.

Read more in #45965
