### ISSUE TITLE
Can't select File Explorer panel using the keyboard

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#4885]
When activating the File Explorer panel by hitting `<CTRL>+<SHIFT>+<E>`, either the "Working Files" section or the project folder section is active.

However, I don't seem to be able to scroll beyond any of both lists using the arrow keys on my keyboard, which is rather annoying.

- VSCode Version: 0.10.11
- OS Version: Windows 10/64

Steps to Reproduce:

1. Hit `<CTRL>+<SHIFT>+<E>` on the keyboard so the File Explorer panel gets activated
1. From the list which currently (and apparently randomly) has received focus, hit any of the `ARROW UP`/`ARROW DOWN` keys until you reach the junction point between both file lists.

=> You cannot scroll across the two file lists in File Explorer panel using the keyboard:

![vscfileexplorer](https://cloud.githubusercontent.com/assets/9283914/14231679/d5a917ec-f98c-11e5-8439-4b2f1676f77a.gif)

**Comment by bpasero** [comment]
F1 > Focus on Files Explorer. I think we might have added this only recently, so give our insiders release a try: http://code.visualstudio.com/Download#insiders

**Comment by SetTrend** [comment]
@bpasero 
I don't think your answer truely matches my report.

I'm complaining about the fact that a user cannot easily navigate between Working Files and project folder files in Files Explorer. The cursor stops at the border between them when using the arrow keys (see animation above).

**Comment by bpasero** [comment]
@SetTrend but the title of this issue is about not being able to use the keyboard to go there, you can change keybindings in settings?

**Comment by SetTrend** [comment]
@bpasero 
I agree. I'm sorry that I missed some details in my issue's title that rendered it incomprehensible.

Given the example screencast depicted above, here are the steps to fully reproduce the issue:

- Open a folder in Visual Studio Code
- If no file is listed in the "Working Files" section of Files Explorer, edit any file listed in the folder browser (the lower section) of Files Explorer in order to add it to the "Working Files" section of Files Explorer.
- Provided that you have now at least one file listed in the "Working Files" section of Files Explorer, click any of the file names listed in the "Working Files" section of Files Explorer by using the mouse in order to open it in the editor on the right.
- Hit `<CTRL>+<1>` to give focus to the editor panel.
- Hit `<SHIFT>+<CTRL>+<E>` to move focus from the editor on the right to the Files Explorer panel on the left. _(The highlighted line should be the file name in the "Working Files" section of Files Explorer.)_
- Hit `<ARROW DOWN>`
- Hit `<ARROW DOWN>` again
- Hit `<ARROW DOWN>` again
- Hit `<ARROW DOWN>` again

=> You will notice that you will not be able to enter the lower section of the File Explorer panel using the `<ARROW DOWN>` key on the keyboard.

That's what I'm complaining about: There is no keyboard navigation in Visual Studio Code allowing me to navigate between the Working Files section and the folder section of Files Explorer.

**Comment by bpasero** [comment]
Understood, but I am really questioning that you would be able to arrow down from one tree to the other, I can see people complain about this if we would add it. It is usually not typical tree behaviour on any OS to navigate to the next tree on arrow down. Instead, you eventually just reach the end of the tree and thats it.

**Comment by SetTrend** [comment]
Agreed. But how would you suggest to navigate between both trees using the keyboard?

Perhaps `<PAGE DOWN>`/`<PAGE UP>` might do?

**Comment by bpasero** [comment]
I think you can assign any keybinding you want given that both commands are configurable since 1.0.

**Comment by SetTrend** [comment]
Which commands would these specifically be?

**Comment by bpasero** [comment]
workbench.files.action.focusFilesExplorer and workbench.files.action.focusWorkingFiles

**Comment by SetTrend** [comment]
Brilliant!

Just for what it's worth - and if anyone is interested - here's my bindings:

```json
// Place your key bindings in this file to overwrite the defaults
[ { "key": "ctrl+k ctrl+e"
  , "command": "workbench.files.action.focusFilesExplorer"
  }
, { "key": "ctrl+k ctrl+shift+e"
  , "command": "workbench.files.action.focusWorkingFiles"
  }
]
```
<br/>
BTW: The `workbench.files.action.focusFilesExplorer` entry became available in the list of available keybindings with today's update of Visual Studio Code.

**Comment by x3rAx** [comment]
In case someone else stumbles over this:

The command `workbench.files.action.focusWorkingFiles` has been removed. You could use `workbench.files.action.focusOpenEditorsView` instead.

These are my bindings:
```
{ "key": "ctrl+shift+e",     "command": "workbench.files.action.focusFilesExplorer"},
{ "key": "ctrl+shift+alt+e", "command": "workbench.files.action.focusOpenEditorsView"},
```

Many thanks @SetTrend for pointing me to the right direction!
