### ISSUE TITLE
Python equality '==' not working properly

### ISSUE THREAD

**Issue by DSdavidDS** [Microsoft/vscode#48860]
Issue Type: <b>Bug</b>

Running the following on python debug

input = raw_input('enter \'x\': ')
if (input == 'x'):
    print('pass')
else:
    print('fail')

print("debug: "+str(type('x'))+" "+str(type(input)))
print('x'==input)

results in a 'fail' upon inputting 'x'. It should be a 'pass'

Results work properly when running from cmd.exe

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|7.96GB (4.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
cpptools|ms-|0.16.1

</details>

**Comment by weinand** [comment]
Please file Python issues against the Python extension since VS Code has no built-in Python support.
