### ISSUE TITLE
Can't scroll using touch on Linux

### ISSUE THREAD

**Issue by darkwater** [Microsoft/vscode#48865]
I'm using a Dell XPS 13" 2-in-1 (laptop with touchscreen) with Void Linux, and I'm unable to scroll editors using the touchscreen.

Tapping and tap-and-hold works to move cursor and open a context menu, but scrolling doesn't work in editors, sidebar tree/lists or the output panel. Scrolling does work in the terminal panel.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.15.12_1

**Comment by jaded0** [comment]
Reopen this

**Comment by trustytrojan** [comment]
reopen this

**Comment by vineeth-krishna-0** [comment]
stil not working
