### ISSUE TITLE
Feature Request: Open Binary File With Text Encoding

### ISSUE THREAD

**Issue by cdunford** [Microsoft/vscode#48866]
I am trying to use vscode as a log viewer for several applications I work with. The log files are just text files, but contain various control characters or other stuff at the beginning such that vscode believes they are binary files and won't process them. I would like to have the ability to force vscode to reopen these files with a specific text encoding. Various other tools that I've used support this ability.

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/39394579-1dd6d03c-4b06-11e8-87d2-92793f2ee3fe.png)

Doesn't this link work?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
