### ISSUE TITLE
256 Color Support Missing With WSL Bash Terminal

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#48869]
Issue Type: <b>Bug</b>

I've read through plenty of other issues and posts. I am not sure what I am missing here. I cannot get 256 color support when using the WSL bash.exe as my integrated terminal. My understanding is that 256 color support [was added](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/) in the creators update. I am working off a fresh Windows 10 install. Here is my terminal setting:

![256](https://user-images.githubusercontent.com/1389303/39390702-f6f34520-4a5d-11e8-8e41-ef793dd41119.png)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|31.86GB (21.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
vscode-npm-script|eg2|0.3.3
dotenv|mik|1.0.1
mssql|ms-|1.3.1
debugger-for-chrome|msj|4.3.0
code-settings-sync|Sha|2.9.0
guides|spy|0.9.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/45693
