### ISSUE TITLE
Cmd+Click URL Containing Comma in Integrated Terminal doesn't follow full URL

### ISSUE THREAD

**Issue by jadchaar** [Microsoft/vscode#48875]
Issue Type: <b>Bug</b>

Try clicking a URL like the ones listed here: https://darksky.net/dev/docs#/dev/docs (I don't want to include my example link because it contains an API key) using the integrated terminal.

Let's take the example link on the docs page: https://api.darksky.net/forecast/0123456789abcdef9876543210fedcba/42.3601,-71.0589

If you are to cmd+click this in the integrated terminal (if it is printed out for example), only the https://api.darksky.net/forecast/0123456789abcdef9876543210fedcba/42.3601 part will go through and the rest will not be detected.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-markdownlint|Dav|0.15.0
vsc-material-theme|Equ|2.0.1
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
start-git-bash|McC|1.2.1
material-icon-theme|PKi|3.3.0
vscode-docker|Pet|0.0.26
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
gitlens|eam|8.2.4
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.5.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
terminal|for|0.0.10
rest-client|hum|0.18.3
Go|luk|0.6.78
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
vscode-scss|mrm|0.6.2
python|ms-|2018.3.1
cpptools|ms-|0.16.1
debugger-for-chrome|msj|4.3.0
vscode-icons|rob|7.23.0
sass-indented|rob|1.4.9
gi|rub|0.2.11
JavaScriptSnippets|xab|1.6.0
ReactSnippets|xab|2.1.0
markdown-all-in-one|yzh|1.2.0

(10 theme extensions excluded)

</details>

**Comment by jadchaar** [comment]
<img width="840" alt="screen shot 2018-04-28 at 1 24 38 am" src="https://user-images.githubusercontent.com/7388203/39392402-326cf388-4a83-11e8-9879-47aac197fd12.png">
Here is an example of what is selected on hover. My API key is redacted.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21125
