### ISSUE TITLE
Open Side by Side is Top - Bottom now!

### ISSUE THREAD

**Issue by nhvu1988** [Microsoft/vscode#48876]
Issue Type: <b>Bug</b>

Why I can't open 2 editor side by side? now it just opens the second editor on the bottom of the current one!!!

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17134

**Comment by d4nyll** [comment]
Try one of the following:

* Go to _View_ > _Toggle Editor Group Layout_
* Press <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd>
* At the top of your sidebar, in the _Open Editor_ tab, press the _Vertical Editor Group Layout_ button.

**Comment by nhvu1988** [comment]
@d4nyll ah I see it, many thanks!
