### ISSUE TITLE
Add a settings key to disableAllExtentions

### ISSUE THREAD

**Issue by hossimo** [Microsoft/vscode#48871]
Issue Type: <b>Feature Request</b>

// Temporally disableAllExtentions
  "extensions.disableAllExtentions": true,

would be great for testing a bug or tring to find an issue, 

Perhaps you could pass an array to list disabled Extentions

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 16.7.0

**Comment by sandy081** [comment]
You can use the command line argument `code --disable-extensions`
