### ISSUE TITLE
showQuickPick return 'undefined' immediately without waiting for Promise is resolved.

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#48879]
- VSCode Version: 1.22.1 or 1.22.2
- OS Version: Windows

This issue could repro randomly (may be one tenth), and it usually happen when you just open VS Code.

**Code to Reproduce:**

Refer to https://github.com/Microsoft/vscode-azure-iot-toolkit/blob/521fb95b4b55a2d4db7204a96824981438771f08/src/iotHubResourceExplorer.ts#L143

**Console log:**
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] ~~~[2018-04-28T03:13:48.936Z]loadIoTHubItems.start
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] ~~~[2018-04-28T03:13:49.092Z]showQuickPick resolve:
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] ~~~[2018-04-28T03:13:49.092Z]value:undefined
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] ~~~[2018-04-28T03:13:50.683Z]loadIoTHubItems.length:3 

**Actual:**
`loadIoTHubItems.length:3` indicates the Promise (`iotHubItems`) is resolved. However, the showQuickPick return 'undefined' immediately before Promise is resolved.

**Expect**
the showQuickPick should wait for Promise to be resolved.

**Comment by saichand345** [comment]
Any update on this ? I am facing same issue. Basically showQuickPick is returning undefined and the pick list is immediately disappearing.

**Comment by chrmarti** [comment]
@saichand345 Do you have a reproducible case? Could you try with the latest insiders build? The latest insiders build uses a new implementation for `showQuickPick`.

**Comment by saichand345** [comment]
I am trying with latest insiders build itself. With earlier VSCode versions(not Insiders) this used to happen once in a while but with insiders build it is happening almost all of the times. Is there any alternative for showQuickPick ?

**Comment by chrmarti** [comment]
There is no alternative. Could you describe the steps you take to reproduce it?

**Comment by chrmarti** [comment]
@saichand345 Are you using quick navigation actions in the keybindings?

**Comment by chrmarti** [comment]
@formulahendry Please retry with 1.24 which uses a new implementation for showQuickPick().

In @saichand345 's case an output channel was opened concurrently to the QuickPick and so both competed for the UI focus. When the QuickPick was faster than the output channel, the QuickPick would close when the output channel grabbed focus. The fix was to open the output channel with `preserveFocus = false`.

**Comment by formulahendry** [comment]
Hi @chrmarti, try the API with 1.24, however this issue still exists..

**Comment by chrmarti** [comment]
@formulahendry Does something else draw UI focus? What happens when you add the option `ignoreFocusOut: true`?

**Comment by formulahendry** [comment]
Hi @chrmarti , sorry for the late response. Nothing else draw UI focus, and I am already using `ignoreFocusOut: true`

**Comment by chrmarti** [comment]
I can reproduce this when I set certain breakpoints. Curiously that is a side-effect of the breakpoints and not something that needs fixing on our side (seriously! :D). When you reproduce this, make sure you do so without hitting any breakpoints.

**Comment by chrmarti** [comment]
Filed an issue for the unexpected side-effect of the breakpoint: https://github.com/electron/electron/issues/13819

Changed to a more robust way of tracking the focus here: https://github.com/Microsoft/vscode/issues/53867

Closing this, let me know if you see this again.

**Comment by alexandrudima** [comment]
I wanted to verify this, but it was not clear to me what the steps are.

**Comment by chrmarti** [comment]
- Install IoT Toolkit extension
- Run 'Select IoT Hub' command
- Pick a subscription
- Ensure the 'Select IoT Hub' picker does not close by itself:
![image](https://user-images.githubusercontent.com/9205389/43710377-c1ec183c-996f-11e8-8a5d-0ba5f0a5f348.png)

This was reported as not reproducing reliably, so please run it a few times to verify.

**Comment by joaomoreno** [comment]
After running that 5+ times, it did not reproduce.
