### ISSUE TITLE
[Feature Request] Split Terminal Font for Windows and OSX

### ISSUE THREAD

**Issue by pingshunhuangalex** [Microsoft/vscode#48886]
Since it's much easier to have ZSH and Powerline terminal settings in OSX. I found myself using different fonts for my Mac and Windows. Also, some font name actually gets recognised differently on Windows and Mac machine, even using the same font file.

Right now, there is only one setting controlling the font of the terminal which I found rather inconvenient (`terminal.integrated.fontFamily`).

I propose we have OS related font family settings for terminal like:
`terminal.integrated.fontFamily.windows` and `terminal.integrated.fontFamily.osx`

Thanks.

**Comment by Tyriar** [comment]
I expect this problem to be solved eventually with https://github.com/Microsoft/vscode/issues/8962

**Comment by specter119** [comment]
@Tyriar how to solve this with https://github.com/Microsoft/vscode/issues/8962?

**Comment by Tyriar** [comment]
Opps, wrong issue: https://github.com/Microsoft/vscode/issues/17619

**Comment by specter119** [comment]
@Tyriar I think we need support os-specific settings in `settings.json` rather than `launch.json`.
By the way, set `"terminal.integrated.fontFamily" : "'font Mac', 'font Win', 'font Linux'"` can work for all platforms, but "terminal.integrated.fontSize" is still unable to be defined properly on different platforms.

**Comment by Tyriar** [comment]
@specter119 Most of the latter comments are discussing it for settings.json.

**Comment by specter119** [comment]
@Tyriar 

```json
{
    "windows": {	
        "terminal.integrated.fontFamily": "Monokai",	
        "terminal.integrated.fontSize": 16,	
    },	
    "osx": {	
        "terminal.integrated.fontFamily": "Meslo LG S for Powerline",	
        "terminal.integrated.fontSize": 12	
    },	
    "linux": {	
        "terminal.integrated.fontFamily": "Noto Mono"	
    }
}
```

not work with all my devices. you can just try to change  "terminal.integrated.fontSize" by this way.

**Comment by Tyriar** [comment]
@specter119 yes we should get a generic solution, rather than doing this for every single setting.
