### ISSUE TITLE
Emmet suggestions in non-jsx code in .tsx files

### ISSUE THREAD

**Issue by osenvosem** [Microsoft/vscode#48887]
I found a couple of similar issues and there was told that the problem is solved, but it seems it isn't.

![screen shot 2018-04-28 at 13 18 38](https://user-images.githubusercontent.com/6762673/39395499-f2732c92-4ae7-11e8-91d6-d996f6d9a1c9.jpg)

**Comment by ramya-rao-a** [comment]
Until, the fix is out you can disable the emmet completions in tsx files by adding the below setting:
```
"emmet.showExpandedAbbreviation": "inMarkupAndStylesheetFilesOnly"
```

You will still be able to expand Emmet Abbreviations by using the `Emmet: Expand Abbreviation` command. If you want to use `tab` to expand abbreviations, then add the below setting:
```
"emmet.triggerExpansionOnTab": true
```

**Comment by ramya-rao-a** [comment]
The fix will be out in the next [Insiders](https://code.visualstudio.com/insiders) on Monday
Thanks for reporting!
