### ISSUE TITLE
No detail in DEBUG CONSOLE for Object in Typescript

### ISSUE THREAD

**Issue by STayinloves** [Microsoft/vscode#48884]
- VSCode Version: 1.22.2
- OS Version:

Steps to Reproduce:

1. console.log an object in typescript code
2. debug the code

![image](https://user-images.githubusercontent.com/18565449/39395091-dd02d0ea-4b0c-11e8-99b4-1d6258a59968.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is designed behavior as you are trying to expand the object after you have stopped debugging.
If you expand the object while debugging everything should be fine.

Let me know if that is not the case and I will reopen
