### ISSUE TITLE
path of tsconfig didn't transform when use different default integrated terminal

### ISSUE THREAD

**Issue by STayinloves** [Microsoft/vscode#48882]
- VSCode Version:1.22.2
- OS Version:Windows10 1703

Steps to Reproduce:

1. default integrated terminal to Git Bash in Windows
2. create a build task for a ts project
2. run the build task

![image](https://user-images.githubusercontent.com/18565449/39394959-e7d63518-4b0a-11e8-8ab2-855e192fed77.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/38178
