### ISSUE TITLE
Can't download VSCode from Russia

### ISSUE THREAD

**Issue by AlekseiLevykh** [Microsoft/vscode#48899]
- VSCode Version: Doesn't have any version yet
- OS Version: Windows 10 /Fall Creators Update/

Steps to Reproduce:

1. Try to download VSCode https://az764295.vo.msecnd.net/stable/3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9/VSCodeSetup-x64-1.22.2.exe
2. Browser return empty page all day (proposes search via Bing)

-----
IMHO:
Two weeks ago RKN (Roskomnadzor) started war with Telegram and blocked millions IP's, probably that is reason why I can't download VSCode.

Is anybody help me to download VSCode (x64 for win) from another server or send me via email. Thanks!

**Comment by yuantongkang** [comment]
Baidu will save you trouble

**Comment by AlekseiLevykh** [comment]
Ok. Found the installer on the Softpedia.
Closed.
