### ISSUE TITLE
javadoc viewer shows code in one line if the line starts with '@'

### ISSUE THREAD

**Issue by idosu** [Microsoft/vscode#48898]
Issue Type: <b>Bug</b>

write a javadoc like this:
``` java
/**
 * <pre><code>
 * {@literal @}AnAnnotation
 * class AClass {
 *     AType aField;
 * }
 * </code></pre>
 */
```

and when you hover to see the javadoc It will show it as followed
```
@AnAnnotation class AClass { AType aField; }
```

If you write `<!-- -->` before the `{@literal @}` It will show it as intended

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|Memory (System)|15.88GB (11.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Gradle|caz|1.1.2
githistory|don|0.4.0
xml|Dot|1.9.2
beautify|Hoo|1.3.0
vscode-apache|mrm|1.1.1
csharp|ms-|1.14.0
printcode|nob|2.3.0
ant-tree-viewer|ped|0.3.2
java|red|0.23.0
vscode-hexdump|sle|1.6.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0
markdown-pdf|yza|1.0.2

</details>

**Comment by rebornix** [comment]
Please file issue against the Java extension you are using.
