### ISSUE TITLE
Integrated Browser

### ISSUE THREAD

**Issue by ndunks** [Microsoft/vscode#48892]
This is a feature request about ability to open/run web project in VSCode without needed to open external browser. I think it will be useful and may reduce memory usage (if compared with opening two browser).

If VSCode has integrated browser, is possible to directly control web app development such as reload page/css and watching file. so web app development will be more powerful.

Thanks

**Comment by mjbvz** [comment]
Out of scope of core vscode. An extension could implement this if they really wanted to

**Comment by VladislavAnkudinov** [comment]
agreed, it would be cool to have integrated browser
