### ISSUE TITLE
Add language to Output channels

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#48890]
My extension often outputs pretty huge structures of EDN and Clojure text. It would be fantastic to be able to attach the `clojure` language ID to the calls to `append and appendLine` in order to have output syntax highlighted. This would be great for log rows as well and probably lots of other scenarios.

**Comment by sandy081** [comment]
@PEZ Do you need lang id per line or lang id for the complete channel? Not sure having lang id per line might be supported.

**Comment by sandy081** [comment]
@PEZ As said, having languageId per chunk will not be feasible. I can take this as request to have a languageId per channel.

**Comment by pflannery** [comment]
@sandy081 I think implementing this would also enable colouring of log output too.

I would like to colour the log output from my extension so it is easier to read.

![image](https://user-images.githubusercontent.com/1727302/83590547-ecac4880-a54d-11ea-87e5-c50006af084b.png)

so it looks like this

![image](https://user-images.githubusercontent.com/1727302/83590646-1f564100-a54e-11ea-90b2-6527b724dd6f.png)
