### ISSUE TITLE
APT on Arch

### ISSUE THREAD

**Issue by PizzaLovingNerd** [Microsoft/vscode#48895]
Hello, I am running Arch Linux with vscode. It asked me if I wanted to install Python ctags. I clicked yes, and it ran apt-get in a terminal. But apt isn't my distribution's package manager. Maybe it should either detect the package manager or ask the user which package manager to use.

- VSCode Version: 1.22.2
- OS Version: Arch Linux (Rolling Release)

Steps to Reproduce:

1. Run a Linux distribution that isn't Ubuntu or Debian
2. Wait for it to ask if you want to install if you want to install Python Ctags
3. Click Yes

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
