### ISSUE TITLE
Disable line wrapping in integrated terminal feature

### ISSUE THREAD

**Issue by Halcyonations** [Microsoft/vscode#48897]
Can we add a "terminal.integrated.disableLineWrapping" feature to settings? Because when I encounter an unexpected error it wraps then I maximize the panel but it stays wrapped.

**Comment by Halcyonations** [comment]
For clarification : That is when the panel is on the right

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688

**Comment by Phrohdoh** [comment]
Disable wrapping entirely is a bit different than reflowing upon resize.
Could this be re-evaluated (as not a dupe) for that reason?

**Comment by Tyriar** [comment]
@Phrohdoh disabling xterm wraparound mode should be supported which is how you can disable line wrapping completely at the program level. The terminal does what the program tells it to do right now.

**Comment by Tyriar** [comment]
@Phrohdoh not really entirely, if a program doesn't want wrapping it can tell the terminal not to wrap. Is there any other terminal (non-WIndows/without scroll bar) that supports disabling line wrapping as you're asking?
