### ISSUE TITLE
[json] Support to contribute JSON schema from an extension

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#489]
See https://github.com/Microsoft/vscode-jshint/issues/4 as a use case.

**Comment by dbaeumer** [comment]
@aeschli I discussed this with Alex and there are two ways we came up with how that can happen:

* make JSON an extension that provides API. The JSHint extension would then prereq the JSON extension
* make the JSON validator an npm module (may be depending on the VSCode API) which is used by JSHINT.

**Comment by scottaddie** [comment]
@dbaeumer I favor the JSON extension idea over the npm module. I also envision this JSON extension being useful for the [ESLint extension](https://marketplace.visualstudio.com/items/dbaeumer.vscode-eslint). There is a schema available for it [here](http://json.schemastore.org/eslintrc), so it could also leverage this proposed JSON extension's API to inject another item into `json.schemas`.  Let me know if there's anything I can do to help out.

**Comment by aeschli** [comment]
@dbaeumer I think all we need is letting you (and others) configure the default JSON settings.
There we associate a file pattern with a schema URL. Right now these settings are in an unpractical form (all in one array), but I want to bring them to a key-value scheme (pattern - schema URI), so each mapping can be configured separately.

**Comment by aeschli** [comment]
Implemented

**Comment by aeschli** [comment]
If you want that VS Code provides validation and intellisense for your JSON configuration files, you have to configure a JSON schema.
If there's already such a schema accessible via http or http, add the following to the `contributes`  section:
```json
    "contributes": {
        "jsonValidation": [{
            "fileMatch": ".jshintrc",
            "url": "http://json.schemastore.org/jshintrc"
        }]
```
If you want to provide one in your extension, have something like
```json
        "jsonValidation": [{
            "fileMatch": ".htmlhintrc",
            "url": "./schemas/htmlhintrc.schema.json"
        }]
```
