### ISSUE TITLE
Extension development: vscode.workspace.applyEdit() runs only once. Other instances are ignored (?)

### ISSUE THREAD

**Issue by plibither8** [Microsoft/vscode#48908]
- VSCode Version: 1.22.2
- OS Version: Ubuntu 16.04

I am creating an extension for VSCode that requires multiple ranges of texts to be deleted by one command (function). For this, I am using `vscode.workspace.applyEdit()` function, calling it multiple times using a loop.

The problem: The `applyEdit()` _applies the edit_ only for the first time its called and the next multiple times its called using the loop, it does nothing.

Here's the code: 

```typescript
let text = activeEditor.document.getText();
let regEx = new RegExp(this.expression, "ig");
let match: any;
let edits: Array<any> = [];

//Pushing all edits to the `edits` array
while (match = regEx.exec(text)) {

    let edit = new vscode.WorkspaceEdit();
    let startPos = activeEditor.document.positionAt(match.index);
    let endPos = activeEditor.document.positionAt(match.index + match[0].length);
    let range = new vscode.Range(startPos, endPos);
    edit.delete(activeEditor.document.uri, range);
    edits.push(edit);

}

//Applying all edits
for (let i: number = 0; i < edits.length; i++) {
    vscode.workspace.applyEdit(edits[i]);
}
```

**Comment by jrieken** [comment]
The `applyEdit`-function returns a `Thenable` which must be awaited

**Comment by plibither8** [comment]
Hey @jrieken , could you please elaborate as to how to implement that? This is my first extension so I might need that extra help :D. Thanks!
