### ISSUE TITLE
Support refactoring across multiple projects in a workspace.

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/vscode#48905]
If I open several projects in a workspace, I'd like refactorings to apply across the projects. For instance, when renaming a class field in one project that a dependencies of the others, the field should update in the other projects as well.

**Comment by mjbvz** [comment]
What language are you working in?

**Comment by justinfagnani** [comment]
TypeScript

**Comment by mjbvz** [comment]
By multiple projects do you mean multiple `tsconfig.json`s?

**Comment by justinfagnani** [comment]
Yes. Specifically we have a monorepo setup with Lerna, and a standard `.code-workspace` file checked in with all of our packages in it.

Within a workspace there are a few things that don't quite work as well as they could besides refactoring, ex: jump to definition opens the .d.ts file of another package, instead of the original source.

**Comment by mjbvz** [comment]
@justinfagnani I believe this falls under [TypeScript 3.0's new project references support](https://blogs.msdn.microsoft.com/typescript/2018/07/12/announcing-typescript-3-0-rc/). When using project references, I expect that rename and other refactorings apply to linked projects as well. Without them, we treat each project as independent.

Let me know if you don't see refactoring working as expected when using project references
