### ISSUE TITLE
Visual Studio Code favicon needs to at least have an outline...

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#48907]
- VSCode Version: Stable 1.22
- OS Version: Windows 10 Pro, using default UI theme

Visual Studio Code's favicon is hidden away when window title is active. But it appears when it's not.

I was thinking maybe the favicon needs an outline, a bit of color tweaking, or have it so there's a shadow or something.

![gif](https://user-images.githubusercontent.com/6444116/39403282-988e6e5e-4b45-11e8-8bad-4cf6cb241111.gif)

Steps to Reproduce:

1. Open Visual Studio Code.
1. Notice Visual Studio Code is now focused, so the window title is active.
2. Open File Explorer.
2. Notice Visual Studio Code is no longer focused, so the window title is set to inactive.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Please reopen if you can still see this with our new icon. via https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#updated-visual-studio-code-icon

**Comment by tommai78101** [comment]
@bpasero 

NICE! I saw the new icons. It looks beautiful. Please help me pass my feedback to the icon designers. They did a really nice job.
