### ISSUE TITLE
Code completion with C/C++ extension

### ISSUE THREAD

**Issue by mhalber** [Microsoft/vscode#4890]
Hi,
I've been testing the new C/C++ extension, however I am running into some problems with code completion suggestions.

Here is an example with C/C++ extension installed, forcing suggestions using cmd+space.
It results in perpetual "Loading..." pop up:
![screen shot 2016-04-03 at 2 38 39 pm](https://cloud.githubusercontent.com/assets/6202456/14234198/bff5f8d4-f9aa-11e5-8469-06e0e4058893.png)

With the extension uninstalled, the suggestions show up immediately
![screen shot 2016-04-03 at 2 47 25 pm](https://cloud.githubusercontent.com/assets/6202456/14234217/30154b60-f9ab-11e5-8bcc-c887b76714c8.png)

The features like go to symbol and go to definition are working properly with the extension installed,
however it seems to hinder the code completion.

- VSCode Version: 0.10.11
- OS Version: El Captain (OS X 10.11.4 )

**Comment by egamma** [comment]
// @asthana86 - pls adopt

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscppsamples#1
