### ISSUE TITLE
Allow to show multiple lines in a notification

### ISSUE THREAD

**Issue by Misiur** [Microsoft/vscode#48900]
I would like to display a few lines in my notifications, but I see that's explicitly forbidden:

https://github.com/Microsoft/vscode/blob/8616dbae8bc2abf7972a45449b0fb6b2b2d0f429/src/vs/workbench/common/notifications.ts#L412-L413

Is there some kind of low-level api access to display either non-link parsed raw string with new lines, or even allowing full html support?

**Comment by bpasero** [comment]
Notifications are imho not the right place to show structured text with formatting. I do not think we would want to expose API to allow for newlines in notifications.

**Comment by bpasero** [comment]
Closing due to https://github.com/Microsoft/vscode/issues/48900#issuecomment-385332787
