### ISSUE TITLE
Ability to control expanded state of views in views container

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#48901]
Currently if you contribute a new views container, and contribute more than 1 view, all the views start collapsed. This leads, imo,  to a fairly poor first experience for the user, see below:

![image](https://user-images.githubusercontent.com/641685/39400994-35c9f3f6-4b09-11e8-8655-ca496019dabb.png)

Could views either by expanded by default in this scenario, or have another setting to control the expanded state in the `package.json`?

//cc @sandy081

**Comment by eamodio** [comment]
None of those are duplicates

**Comment by sandy081** [comment]
Custom views are made collapsed by default because of scalability. Previously one can contribute views only to explorer. Since, they can be now contributed to custom view containers this is no longer an issue. Hence changed the default behaviour to expand.

**Comment by sandy081** [comment]
Custom views are shown collapsed by default only in in-built view containers. Otherwise they show expanded by default.
