### ISSUE TITLE
Need event for when configuration is updated without a change in effective value

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#48904]
- Have listener on `onDidChangeConfiguration`
- Have `"editor.renderWhitespace": "boundary"` in User settings, and not set in workspace settings
- Add `"editor.renderWhitespace": "boundary"` to workspace settings
- `onDidChangeConfiguration` is not fired

I need an event on the ConfigurationService that will fire in this case, when any setting is changed on any scope, even if it doesn't result in a change to the effective value of the setting, so the settings editor UI can be updated.

@sandy081 thoughts? Is there already a way to get this?

**Comment by sandy081** [comment]
@roblourens Currently event is triggered only when there is a change in the effective value. But, I see your use case where all changes to the sources should be triggered. The event can also have information about what source has changed.
