### ISSUE TITLE
Issues about integrated terminal

### ISSUE THREAD

**Issue by Luberen** [Microsoft/vscode#48917]
There are some issues while typing Korean characters in integrated terminal.

![t1](https://user-images.githubusercontent.com/26616056/39408039-13e4542c-4c0b-11e8-90a7-b35053bfc27c.png)
(1) Alignment of last entered character is not correct

![t2](https://user-images.githubusercontent.com/26616056/39408060-69c58e9c-4c0b-11e8-8091-b977d825094a.png)
(2) If I click somewhere else, last entered character is deleted.

These issues don't occur in Cmd.

**Comment by Tyriar** [comment]
This is working as expected as it depends on the IME being used. Some IMEs/platforms align properly.

**Comment by Luberen** [comment]
I'm using Microsoft's standard IME.
