### ISSUE TITLE
cpu run exhaust

### ISSUE THREAD

**Issue by hf7612** [Microsoft/vscode#48910]
When I run code filex.txt,the cpu will run to 98%,then I found that it will trverse the whole /home/$USER directory,because the directory have too many files,so cpu will run exhaust.

- VSCode Version:
- OS Version:
版本 1.22.2
提交 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
日期 2018-04-12T16:34:44.222Z
Shell 1.7.12
渲染器 58.0.3029.110
Node 7.9.0
架构 x64
Steps to Reproduce:

1.When I run code filex.txt,the cpu will run to 98%,then I found that it will trverse the whole /home/$USER directory,because the directory have too many files,so cpu will run exhaust.
2.

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
