### ISSUE TITLE
File paste feature request

### ISSUE THREAD

**Issue by jmussman** [Microsoft/vscode#48915]
Modify file paste in the explorer to either ask to replace an existing file instead of pasting it with a new name, or provide a paste-and-replace feature that replaces existing files with what is being pasted. It is really cumbersome to first find and delete the files before pasting, and even worse to paste and then have to delete the original and rename the new file.

Regards

**Comment by isidorn** [comment]
@jmussman thanks for the feedback however we will not change this behavior. This is how native os explorers behave.
You can make an extension which contributes the action which you need and rebing the keybindings to invoke the action of your extension.

**Comment by jmussman** [comment]
I understand that you don’t want to do it, and that’s your choice. But, please TELL ME ONE EXPLORER THAT HAS THE NATIVE BEHAVIOR AS VS CODE WORKS? NOT WINDOWS, NOT OS X, AND NOT ONE SINGLE LINUX DESKTOP THAT I CAN THINK OF. Microsoft arrogance and stupidity, all over again. God, you people are so frustrating, and have been for decades.

**Comment by jmussman** [comment]
Really? Without a chance to respond? You people are so arrogant.
