### ISSUE TITLE
Importing a newly-created file breaks intellisense

### ISSUE THREAD

**Issue by kiyutink** [Microsoft/vscode#48913]
- VSCode Version: 1.22.2
- OS Version: Windows 10 (10.0.16299)

Steps to Reproduce:
1. Create a new file 
2. Import the newly-created file in another file

Does this issue occur when all extensions are disabled?: **Yes**

When it happens it also breaks eslint (fixed eslint errors don't disappear) and probably other extensions too, in some way.
I checked it with and without all extensions. Also checked it in vscode insiders (version 1.23.0-insider). It occurs every time. 
I also made a gif where I reproduce the bug - https://i.imgur.com/C5NVRlp.gif
You can see that in the beginning intellisense works but it stops working after I import a variable from a new file

**Comment by mjbvz** [comment]
Does this still happen if you upgrade your workspace to `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)?

**Comment by kiyutink** [comment]
yea i imported a few files, and i think that fixed it
thanks

**Comment by mjbvz** [comment]
We'll pick up TS 2.9 in VS Code 1.24
