### ISSUE TITLE
Search: dismissing file or result now aggressively changes active selection

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48911]
Steps to Reproduce:

1. have some search results
2. click on one result
3. dismiss a result from another bucket (either dismiss an entire file or inidividual result

=> the current selected search result from step 1. is no longer selected

I suggest to fix this for April as it looks like a regression. Imho we should only jump the active search selection if the active one is dismissed (or its parent).

**Comment by roblourens** [comment]
I agree with that but it doesn't look like a regression. I see the same behavior in 1.22

Is this the scenario? gif is 1.22

![apr-29-2018 18-51-16](https://user-images.githubusercontent.com/323878/39413387-5f4cdb46-4bde-11e8-81ae-f48bd4e754bc.gif)
