### ISSUE TITLE
Allow manually specifying promise timeouts

### ISSUE THREAD

**Issue by nevadascout** [Microsoft/vscode#4892]
- VSCode Version: 0.10.11
- OS Version: Windows 10

I have a promise that takes just over a second to complete, but due to [this code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionHostProcess.ts#L53) (shown below) it is always rejected.

```
process.on('unhandledRejection', (reason, promise) => {
	unhandledPromises.push(promise);
	setTimeout(() => {
		const idx = unhandledPromises.indexOf(promise);
		if (idx >= 0) {
			unhandledPromises.splice(idx, 1);
			console.warn('rejected promise not handled with 1 second');
			onUnexpectedError(reason);
		}
	}, 1000);
});
```

I would like to be able to specify a timeout manually for my promise to allow it to run for 2 seconds _(for example)_ before timing out and being rejected. (1 second should remain as the default timeout)

**Comment by jrieken** [comment]
@nevadascout How would you specify such a timeout?

**Comment by jrieken** [comment]
Closing as there isn't nice way to doing this.
