### ISSUE TITLE
tab key stops working randomly !!!!

### ISSUE THREAD

**Issue by jasonbronson** [Microsoft/vscode#48924]
Issue Type: <b>Bug</b>

Unknown what causes it but tab key works in any other window just stops in the editor. 
Botttom of screen does not show active items or key bound anywhere else. Emmet is set to trigger on tab but basic tab key is not working.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz (4 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.37
beautify|Hoo|1.3.0
crane|Hvy|0.3.8
material-icon-theme|PKi|3.3.0
code-settings-sync|Sha|2.9.0
terminal-tabs|Tyr|0.1.1
scratchpad|awe|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.3.1
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
php-pack|fel|1.0.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
sftp|lix|1.1.7
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
vscode-attrs-sorter|mrm|2.1.0
python|ms-|2018.3.1
csharp|ms-|1.14.0
PowerShell|ms-|1.7.0
vuejs-extension-pack|mub|1.0.3
php-docblocker|nei|1.6.0
vetur|oct|0.11.7
laravel-blade|one|1.18.0
vscode-code-outline|pat|0.1.1
java|red|0.23.0
laravel-5-snippets|sac|2.0.1
highlight-matching-tag|vin|0.4.4
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0
vscode-todo-highlight|way|0.5.12

</details>

**Comment by alexandrudima** [comment]
@jasonbronson 

### Are there any customizations to <kbd>Tab</kbd> keybindings ?

* Is there nobody else binding to the <kbd>Tab</kbd> key?
* Does this reproduce when disabling all extensions? (`code --disable-extensions`)?
* You can also find the complete list via `cmd+k cmd+s`, clicking on `keybindings.json` and searching for `"tab"`. Out of the box, there should be 6 hits for a total of 5 commands. Do you have more than that ?
```js
{ "key": "tab", "command": "tab",
                   "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus" },
{ "key": "tab", "command": "editor.emmet.action.expandAbbreviation",
                   "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorReadonly && !editorTabMovesFocus" },
{ "key": "tab", "command": "insertSnippet",
                   "when": "editorTextFocus && hasSnippetCompletions && !editorTabMovesFocus && !inSnippetMode" },
{ "key": "tab", "command": "jumpToNextSnippetPlaceholder",
                   "when": "editorTextFocus && hasNextTabstop && inSnippetMode" },
{ "key": "tab", "command": "acceptSelectedSuggestion",
                   "when": "suggestWidgetVisible && textInputFocus" },
```
* Are there customizations made in your `keybindings.json`

### Are there settings changes that affect the <kbd>Tab</kbd> behaviour?

Did you change any of the following settings:
* `config.emmet.triggerExpansionOnTab` (would lead to <kbd>Tab</kbd> executing `editor.emmet.action.expandAbbreviation`) 
* `editor.tabCompletion` (would lead to <kbd>Tab</kbd> executing `insertSnippet`)

### Do you use <kbd>Tab</kbd> for moving focus?
* The default keybinding uses `!editorTabMovesFocus`
* This is a context key that can be toggled by <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>M</kbd>
* This toggle will make it that pressing <kbd>Tab</kbd> will move focus.
