### ISSUE TITLE
Trigger command failed in preview window sometimes

### ISSUE THREAD

**Issue by qjebbs** [Microsoft/vscode#48926]
- VSCode Version: 1.22.2
- OS Version: MacOS 10.13.4

Steps to Reproduce:

I write a extension [Super Replace](https://github.com/qjebbs/vscode-super-replace) which takes preview window as user interface. In the daily use, I observe that one out of 10 or 20 times, the command cannot trigger, and the console logs `prevented webview navigation`.

It's really hard to debug this, since it comes out randomly.

After a long time debugging, I suspect it a problem about adding the event listener `handleInnerClick `.

Here is the code (from [webview-pre.js](https://github.com/Microsoft/vscode/blob/82d97b4c3c9c0c42f3005d4fc9114885ca652094/src/vs/workbench/parts/webview/electron-browser/webview-pre.js)):

```ts
loadTimeout = setTimeout(function () {
    clearTimeout(loadTimeout);
    loadTimeout = undefined;
    onLoad(newFrame.contentDocument, newFrame.contentWindow);
}, 200);

newFrame.contentWindow.addEventListener('load', function (e) {
    if (loadTimeout) {
        clearTimeout(loadTimeout);
        loadTimeout = undefined;
        onLoad(e.target, this);
    }
});
```

`onLoad` is the function who adds the listener.

```ts
var onLoad = function (contentDocument, contentWindow) {
if (contentDocument.body) {
    // Workaround for https://github.com/Microsoft/vscode/issues/12865
    // check new scrollTop and reset if neccessary
    setInitialScrollPosition(contentDocument.body);

    // Bubble out link clicks
    contentDocument.body.addEventListener('click', handleInnerClick);
}
// ...
}
```

In most times, it works as expect. But if the webview was loaded in more than 0.2 second, we got trouble:

1. the `setTimeout` triggers, but the onLoad function cannot do it's job, because `contentDocument.body` is not ready.
1. the `load` event triggers, it cannot do the job either, because the `loadTimeout` has been set to `undefined` in last trigger.

So we can see, the `handleInnerClick` is not added in this case. This explains why the `prevented webview navigation` happens most in cold starts.

**Comment by chongchai** [comment]
I get the same problem for my extension. 
After open preview html, it will fail to execute command in the html with error '**[Embedded Page] prevented webview navigation**'. This happens most  when the first time to open the preview html.
