### ISSUE TITLE
Copied search results should be sorted same as in the tree

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#48928]
- Do a search in the sidebar
- Right click on the results and select "copy all"
- Paste into an editor
- See that the pasted results are not sorted the same as in the tree! These should match.

Use https://github.com/Microsoft/vscode/blob/e72ea2399be2d01927ab4e3c60fb5fba72a17da6/src/vs/workbench/parts/search/browser/searchResultsView.ts#L114

and apply to https://github.com/Microsoft/vscode/blob/e72ea2399be2d01927ab4e3c60fb5fba72a17da6/src/vs/workbench/parts/search/browser/searchActions.ts#L761

**Comment by cedric05** [comment]
please review https://github.com/Microsoft/vscode/pull/48999

**Comment by Krzysztof-Cieslak** [comment]
Should be closed, fixed by #48999
