### ISSUE TITLE
Drag and drop onto scrollbar - explorer stays highlighted

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#48929]
I did this on accident, but it took a little effort to figure out how I did it.

- Drag file from Finder onto Explorer
- Get scrollbar in Explorer to be visible, like by dragging near the top/bottom of the Explorer
- The entire explorer becomes highlighted when you hold the file over the scrollbar
- Drop file onto the scrollbar
- The entire explorer stays highlighted.

It stays highlighted through interacting with the explorer and even switching to another viewlet. Only can be reversed by dragging another file onto the explorer.

![apr-29-2018 21-41-54](https://user-images.githubusercontent.com/323878/39415292-4febe7f6-4bf6-11e8-86ca-0a0068a50a79.gif)

**Comment by roblourens** [comment]
Actually a much easier way to repro is to two-finger scroll while dragging the file to get the scrollbar to appear.

**Comment by cedric05** [comment]
i'm able to reproduce it. will try to fix it

**Comment by cedric05** [comment]
not able to find issue. any help?

**Comment by manixate** [comment]
I gave it a go here: #49747
