### ISSUE TITLE
VS code not being updated but only gives notification to update each time.

### ISSUE THREAD

**Issue by zymr-keshav** [Microsoft/vscode#48927]
- VSCode Version: _1.22.1_ (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd)
- OS Version: _macOS High Sierra v 10.13.3_

whenever I open vs code. it gives notification on right bottom side to update it with 2 buttons

```
Restart Visual Studio Code to apply the latest update.

Update Now | Later | Release Notes

```

and when I click on **Update Now** , and restart ( note it never reopen automatically) and it again gives the same notifications message.

means it's not getting updated at all. why is this happening? and how to fix this?

Note: I have not disabled any extension . and also do not alter any vs code update related settings.

**Comment by joaomoreno** [comment]
Can you run `ps ax | grep Code` while Code is running and show me the result?

**Comment by zymr-keshav** [comment]
Surprisingly it's being updated automatically now. I have disabled one of the extension but don't remember which one. Note that I have already checked with `ps ax`  and there was no process running for *Code*
