### ISSUE TITLE
Intellisense Squiggles Jump around

### ISSUE THREAD

**Issue by tomkulaga** [Microsoft/vscode#48925]
- VSCode Version:
1.22.2 stable
- OS Version:
Windows 10 x64 1709 
Steps to Reproduce:

1. Create new file
2. Type some code, make sure its gibberish to induce error squiggle
3. Create some blank lines
4. Type some more error code
5. Delete one of the blank lines to force the line with the error squiggles to move up.
6. See the squiggle jump

Please see the attached GIF [squiggle_jump](https://user-images.githubusercontent.com/1594598/39412346-35eb5a68-4c5e-11e8-9fd3-e12d5936539c.gif)

![squiggle_jump](https://user-images.githubusercontent.com/1594598/39412346-35eb5a68-4c5e-11e8-9fd3-e12d5936539c.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
The `IMarkerService.onMarkerChanged` fires twice when pressing <kbd>Enter</kbd> and briefly moves the marker back to the wrong location before TS has a chance to compute new markers and set them to the new line: 

Here I am running with the following diff in `modelServiceImpl.ts`:

![image](https://user-images.githubusercontent.com/5047891/39421867-5074716e-4c6b-11e8-903c-f84236693e93.png)

I have run `npm install @types/react` and use the following snippet:
```ts
import * as React from 'react';

asdasdad

class tt extends React.Component {
    
}
```

I believe this is a regression in `IMarkerService`.
![kapture 2018-04-30 at 11 42 29](https://user-images.githubusercontent.com/5047891/39421948-9ef0bdde-4c6b-11e8-80e5-e68800ccf15b.gif)

**Comment by jrieken** [comment]
This is TypeScript setting the old diagnostics first, then updating with the actual diagnostics
