### ISSUE TITLE
How to apply File Explorer context menu to custom tree view?

### ISSUE THREAD

**Issue by luozhihua** [Microsoft/vscode#48932]
Has any way to apply File Explorer context menu items to custom tree view such as `Copy file/folder`, `Paste`, `Copy path`, `Rename`...

**Comment by isidorn** [comment]
This is currently not possible. I do not think we have plans to support this but @sandy081 can decide

**Comment by luozhihua** [comment]
I see some new APIs in master branch like `FileSystemProvider`, It's possible to supported by `FileSystemProvider`?  

Maybe I don't really need to use the `Explorer` menus onto `Tree view`, If we can by execute some `Commands` or call `APIs` for a specified file path or "Uri”，that can do copy, paste, rename operations also is good.

I list out some exists `Commands` below, but these are all running with the specific context of activated Explorer TreeItem, If can pass some parameters to do the same things are very useful:

- `explorer.newFile`
- `explorer.newFolder`
- `explorer.openToSide`
- `filesExplorer.copy`
- `filesExplorer.paste`
- `renameFile`
- `copyFilePath`
- `filesExplorer.findInFolder`
- `filesExplorer.findInWorkspace`

**Comment by sandy081** [comment]
@luozhihua There are no plans to support file explorer context menu items in custom tree view context menu. 

But you can call those commands from extension I suppose. @isidorn Can you please confirm that and if so, also please provide information about how to call these commands.

**Comment by isidorn** [comment]
It is possible to call those commands from extensions using the `commandService`.
You can find the ids of those commands in this file
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L48

**Comment by sandy081** [comment]
Thanks @isidorn 

Closing this. Please reopen it if there is a specific request. Thanks.
