### ISSUE TITLE
Allow file operations on entries in opened editors

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4893]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1.  Launch app and add any file or open any folder.
2. Verify rename operation inside explorer using F2 key.

Actual: There is no way to rename explorer contents using any keyboard shortcut or with mouse double click.

Scenario:
I tried to add a html file but forgot to add extension. As there is no way to rename the file or change the extension inside explorer window so I added other file with the same name and .html extension. That took me to perform couple of actions along with copy and paste the file contents. If we have a option to rename the file or change the file extension by pressing F2 then it would be more convenient and save multiple user's actions.
![image](https://cloud.githubusercontent.com/assets/17735796/14235846/b996acf4-f9be-11e5-9352-4dfdeb46a0e3.png)

**Comment by bpasero** [comment]
This is by design, you need to open a folder to perform all file operations.

**Comment by bpasero** [comment]
We will not change this.
