### ISSUE TITLE
goto code via CTRL Click

### ISSUE THREAD

**Issue by MikeLeicester** [Microsoft/vscode#48939]
the goto code feature via a control click on function name needs a massive overhaul

currently when i CTRL+click on a function name i will get the first match found my VS:CODE

this could be pretty much anywhere on the current root directory

it should always priorities the current file, then the current directory then navigate up to the root folder 

i currently have the following structure

root/website1/js/script1.js
which includes

```
function Load() {
    LoadData();

}
function LoadElastic(elastic) {
...
}

function LoadFeature(feature) {
    ...
}

function LoadData() {
   ...
}
```

and 

root/website1/js/script2.js

```
function LoadData() {
...
}
```

with out fail when i CTRL click on load data i get redirected to the LoadData function in script2.js even though the correct function is in the same file 40 lines below the click point

in other examples i've had its actually been redirected to to the correct file but in a different project branch, which if you don't notice leads to massive headaches with debugging and then repairing 2 broken branches

the issue seems to affect all code languages not just js

**Comment by mjbvz** [comment]
If those two files are loaded on the same page, `LoadData` may very well point to either of the definitions based on the evaluation order.

The fix here is to make your files into modules, or to use namespaces or similar to ensure that you are always referencing the expected version of `LoadData` in a given file
