### ISSUE TITLE
Is possible provide an API to close specified File or TextDocument?

### ISSUE THREAD

**Issue by luozhihua** [Microsoft/vscode#48945]
I wrote an Extension to auto open a group files of the same Angular components and Vue component, but has no perfect way to close them.

For example, users opened a document named `dialog.component.ts`, My Extension will auto open some sibling files which named as `dialog.component.scss` or `dialog.component.html` in multi column views,  But has no perfect way to close these files which opened by the extension.

Currently the only can do is to through the command `workbench. Action. CloseActiveEditor`, but there are a lot of uncertainty, such as I can only through the command `window.showTextDocument` to force  a ` Text Document` to get activated, but the active status will be changed with user behavior, this is a big uncertain factors. And if a ` Text Document` exists in another column view already, in fact two same document will be open at the same time.

I don't know if I've described my question clearly.

**Comment by jrieken** [comment]
Yeah, it's deprecated but there is `TextEditor#hide` which does what you want. Just make sure to *not* hold on to a reference of the editor after that.

**Comment by luozhihua** [comment]
@jrieken Thanks for reply! I found `TextEditor#hide` in VSCode documentation page, But it's also marked as deprecated: 
https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametexteditoraspan-classcodeitem-id333texteditorspan 
Can I still use it?
