### ISSUE TITLE
VSCode is freezing after a big search is done a and the search results are not accessible

### ISSUE THREAD

**Issue by dmusev** [Microsoft/vscode#48941]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|nativescript|Telerik|0.7.2|
|html-css-class-completion|Zignd|1.15.0|
|vscode-eslint|dbaeumer|1.2.11|
|Ruby|rebornix|0.14.0|
|vscode-react-native|vsmobile|0.4.4|
|JavaScriptSnippets|xabikos|1.6.0|
|ReactSnippets|xabikos|2.1.0|;

---

Steps to Reproduce:

1.Do a search for a word that appears several times in several files quite big
2. When you try to close some of them the ide freezes and it is not resposible

**Comment by roblourens** [comment]
Most likely https://github.com/Microsoft/vscode/issues/31551, there are some issues handling results from very long lines. But 1.13 is very out of date, please update, it may work better in a recent version.
