### ISSUE TITLE
Node.js did not respond to request 'continue' in a reasonable amount of time.

### ISSUE THREAD

**Issue by priytam1993** [Microsoft/vscode#48947]
Issue Type: <b>Bug</b>

Node.js did not respond to request 'continue' in a reasonable amount of time.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2592)|
|Memory (System)|7.91GB (2.65GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe d:\Project Work\prod\perfecticeapi|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
html-class-suggestions|And|1.0.7
vscode-standard-format|che|0.0.12
vscode-style-formatter|dwe|1.0.0
csharpextensions|jch|1.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.3.0
vscode-docker|Pet|0.0.26
auto-format-imports|pit|0.2.1
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by roblourens** [comment]
Which version of Node are you using?
