### ISSUE TITLE
Auto Updater is crashing 

### ISSUE THREAD

**Issue by anuragpathak** [Microsoft/vscode#48949]
Issue Type: <b>Bug</b>

As soon as I click on Update now.
Visual studio closes 
and updater crashes

VS Code version: Code - Insiders 1.23.0-insider (e679bfee4360cb1bc152e6e0ea7583d8d042e07e, 2018-04-27T08:46:53.881Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (3.58GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
beautify|Hoo|1.3.0
docthis|joe|0.6.0

</details>

**Comment by joaomoreno** [comment]
Do you have a screenshot of the crash? A log file?
