### ISSUE TITLE
Right click context menu over the Workspace side panel label should have option, "Edit Workspace"

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#48948]
- VSCode Version: Stable 1.22
- OS Version: Windows 7 Enterprise LTS

This is the context menu when you right click on the Workspace side panel label:

![image](https://user-images.githubusercontent.com/6444116/39429074-b96f4608-4c57-11e8-9f46-79e6e7cfffe9.png)

There should be an option in the context menu, called "Edit Workspace", which will do any of the followings based on certain conditions:

- If `.code-workspace` file doesn't exist, or it hasn't been found, create a new JSON file for the user.
- If `.code-workspace` file doesn't exist, or it hasn't been found and the user specifies to create a new file, allow the user to choose where to save it via File Explorer.
- If `.code-workspace` file exists, then open that file up for the user to make modifications.

This is especially important when it comes to managing multiple root workspaces and `.code-workspace` files.

**Comment by isidorn** [comment]
fyi @sandy081

**Comment by sandy081** [comment]
I would not put it in the views context menu, instead in the file explorer as it has related actions.

**Comment by tommai78101** [comment]
@sandy081 Not even as the UI buttons next to the Workspace name?

**Comment by sandy081** [comment]
@tommai78101 I mean the file explorer in VS Code

![image](https://user-images.githubusercontent.com/10746682/39566852-461fc93a-4ebd-11e8-9bd0-449727fab41a.png)

**Comment by tommai78101** [comment]
Ah ok, that makes more sense. It would be better to put all related options together.

But how did you show that context menu? I'm not able to see it.

**Comment by sandy081** [comment]
@tommai78101 Right click on the empty space

**Comment by tommai78101** [comment]
![gif](https://user-images.githubusercontent.com/6444116/39715273-c4b73194-51fa-11e8-83e9-a0a1540ca52b.gif)

Am I clicking in the right area?

**Comment by sandy081** [comment]
@tommai78101 No, please open the workspace section and do collapse all. Now right click in the empty area

**Comment by tommai78101** [comment]
@sandy081 Ok, now I see the menu.
