### ISSUE TITLE
Input text get inserted into wrong place.(editing in the middle of text)

### ISSUE THREAD

**Issue by tqtifnypmb** [Microsoft/vscode#48942]
Issue Type: <b>Bug</b>

I was editing a markdown file which contains both Chinese and English text. After some insertions and deletions, the typed English character was inserted before cursor and cursor position didn't change.

example: ( ‘|’ means cursor )
before typing:    ....(some Chinese & English text here)...  p|p ....(some Chinese & English text here)...
after typing ‘A’:    
             
- actual result:  p|Ap       
- expect result:  pA|p

It happened several times. I don't knonw how to reproduce it.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (8.19GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
cpptools|ms-|0.16.1

</details>

**Comment by rkottmann** [comment]
It seems I have a very similar issue even if all is in English. It appears while Editing java in even more often editing markdown. It makes vscode unusable. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.30GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.3
markdown-mermaid|bie|1.0.0
vscode-markdownlint|Dav|0.17.0
xml|Dot|1.9.2
EditorConfig|Edi|0.12.2
javac-linter|fau|1.3.1
url-encode|fle|1.1.0
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.0.21
XMLLanguageSupport|IBM|0.0.1
auto-comment-blocks|kev|1.0.1
ant-tree-viewer|ped|0.3.2
java|red|0.25.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.8.0
vscode-mermaid-preview|vst|0.8.3
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.4.0


</details>

**Comment by rkottmann** [comment]
Does not happen with extensions disabled

**Comment by rebornix** [comment]
It seems some extensions are messing with the cursor position. You can try to disable some extension to see which one is doing so.
