### ISSUE TITLE
[Node.js > 8.0 Debugger] Unable to debug with error message about ms-vscode.node-debug

### ISSUE THREAD

**Issue by Fghurayri** [Microsoft/vscode#48946]
## - VSCode Version: 
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-13T19:17:59Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

## - OS Version:
`Linux solus 4.15.17-65.current #1 SMP PREEMPT Fri Apr 20 11:36:00 UTC 2018 x86_64 GNU/Linux`

## Steps to Reproduce:
1. Create a file with node code to debug. (example below).
2. Click on debug icon.
3. Click on the 'run' symbol to start debugging.
4. You will be asked to select environment, select Node.js.
5. Observe the error message.

## Error message:
`[ms-vscode.node-debug]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-vscode.node-debug`

I tried running this command but still the issue isn't solved:
`code-oss . --enable-proposed-api ms-vscode.node-debug`

## Code example:
```javascript
var i = 0;
setInterval(() => {
  console.log('iteration ' + i);
  i++;
},1000)
```

## Error message:
![image](https://user-images.githubusercontent.com/27068874/39427545-cd6c0bde-4c8c-11e8-9109-386568edab36.png)

## Populated launch.json after accepting the error prompt:
```javascript
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/test.js"
    }
  ]
}
```

## Does this issue occur when all extensions are disabled?: Yes/No
Yes
`code-oss . --disable-extensions`

**Comment by roblourens** [comment]
Is this the normal stable code build, or did you build it yourself? Otherwise I don't understand why you're starting it with `code-oss`?

**Comment by roblourens** [comment]
Ok, it looks like an unofficial build, but it should be possible to make it work. I can't unpack that eopkg file, so can you look for the product.json file, which should be in the package at a path like `Resources/app/product.json`. It should have a section like

```
"extensionAllowedProposedApi": [
		"ms-vscode.node-debug",
		"ms-vscode.node-debug2"
],
```

can you check that it's there?

**Comment by Fghurayri** [comment]
I found that file under `/usr/share/vscode/resources/app/product.json` and it didn't have the section you mentioned. I added that as `sudo` and the debugging worked as expected!

Much appreciated, Rob!
