### ISSUE TITLE
Screen locks for about 20 seconds when window is focused

### ISSUE THREAD

**Issue by ShaneGH** [Microsoft/vscode#48943]
Issue Type: <b>Bug</b>

1. When edititing code
2. Alt + tab to another window
3. Alt + tab back

Screen is completely unresponsive
While screen is unresponsive, user performs a gesture (e.g. try to select text), the resulting gesture will visible if alt + tab out and then back again

Issue may have something to do with editing css, as this is the only area I have experienced the problem.
Issue happens about 80% of the time

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|7.91GB (1.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
Ionide-fsharp|Ion|3.19.4
csharp|ms-|1.14.0
vs-keybindings|ms-|0.2.0
vscode-docker|Pet|0.0.26
typescript-hero|rbb|2.3.2

</details>

**Comment by ShaneGH** [comment]
Verified that this occurs when all extensions are disabled

**Comment by bpasero** [comment]
Likely https://github.com/Microsoft/vscode/issues/28709
