### ISSUE TITLE
Tasks.json environment variable expansion case sensitive

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#4895]
- VSCode Version:0.10.13 alpha
- OS Version:Windows 10

Steps to Reproduce:
1. Add an variable to your tasks.json ex. ${env.PATH}
        "command": "echo",
   "isShellCommand": true,
   "args": ["${env.PATH}"],
2. Run the task.
   This will expand correctly on Linux and OS X but not Windows since the expansion is case sensitive and PATH on Windows is "Path".
   Env Var expansion shouldn't be case sensitive so that the same task can run on all platform.
   This bug was requested by @dbaeumer in vscode-docs issue https://github.com/Microsoft/vscode-docs/issues/247

**Comment by dbaeumer** [comment]
@isidorn this is done by the resolver service. IMO env variables on all OSes are case insensitive. Should we address this.

**Comment by isidorn** [comment]
Let's keep it open and if some user is passionate he can tackle it
[Code pointer] (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L36)

**Comment by weinand** [comment]
On linux and macOS environment variables are case sensitive, so "Path" and "PATH" are different variables on linux and macOS (but not on Windows).

@dbaeumer so you are asking for making env var lookup case insensitive on Windows only, correct?

**Comment by dbaeumer** [comment]
I thought they are always case insensitive. So it should be case insensitive then on Windows only

**Comment by heaths** [comment]
@isidorn, I'm actually about done with a change for this if you want to take a look.

**Comment by isidorn** [comment]
@heaths thanks, I will review the PR.

**Comment by heaths** [comment]
@isidorn did you want me to squash it or anything (fixed a broken test because I forgot the existing code returned an empty string for missing _environment_ variables)? Different projects have different requirements and I didn't see anything about squashing in your contrib docs.

**Comment by isidorn** [comment]
@heaths no need to squash, I will add the comments to the PR directly if something is needed. Thanks
