### ISSUE TITLE
Disable strictFunctionTypes in typescript

### ISSUE THREAD

**Issue by dgofman-equinix** [Microsoft/vscode#48959]
Hi I need to disable strict function parameter in Visual Studio by using "strictFunctionTypes" argument.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html

https://github.com/Microsoft/TypeScript/pull/18654

I tried adding "strictFunctionTypes": false into tsconfig.json and setting.json but VScode ignore reading those settings.

**Comment by mjbvz** [comment]
Please check that the typescript file is part of the expected `tsconfig` project by running the `Go to project configuration` command in it. This should open the `tsconfig` with `strictFunctionTypes` disabled

**Comment by dgofman-equinix** [comment]
I tried all options:

1) under my project ".vscode/settings.json add path to latest typescript folder "^2.8.3"

"typescript.tsdk": "./node_modules/typescript/lib"

2) in tsconfig.json set strict and strictFunctionTypes to false

{
    "compileOnSave": false,
    "strictFunctionTypes": false,
    "compilerOptions": {
        "sourceMap": true,
        "target": "es5",
        "strict": false,
        "noImplicitAny": false,
        "strictFunctionTypes": false
    },
    "exclude": [
        "node_modules"
    ]
}

3) restarted VS code

but still getting the same error, No issues compiling code via command line

tsc --p ./tsconfig.json

**Comment by mjbvz** [comment]
Does `Go to project configuration` open `./tsconfig.json`?

**Comment by dgofman-equinix** [comment]
Sorry, I have tow tsconfig.json files.
One for nodeJS another for compiling ES5.

When I opened "workspace settings" (Ctrl+Shift+P)  (link bellow)
https://code.visualstudio.com/docs/getstarted/settings

I have to use command line:
">TypeScript: Go to Project Configuration"

Now I added "strictFunctionTypes": false under "compilerOptions" what is fixed that issue.

Thanks for your help.

**Comment by mjbvz** [comment]
Glad to hear the issue was resolved. Unsure about the config problem. The settings file is generally intended for vscode and extension settings, not general config options. I recommend putting port in the `launch.json` or getting it from the environment
