### ISSUE TITLE
Its not possible to send all control codes to the terminal window.

### ISSUE THREAD

**Issue by pjs102** [Microsoft/vscode#48950]
Issue Type: <b>Bug</b>

Its not possible to send all control codes to the terminal window.  When running an ssh session to a linux box, clicking Ctrl-S will pause the screen, but you are unable to send in Ctrl+Q to resume the session.  

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.16.0
vscode-markdownlint|Dav|0.15.0
cpptools|ms-|0.16.1
Ruby|reb|0.18.0
java|red|0.23.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0

</details>

**Comment by Tyriar** [comment]
@pjs102 are you using WSL bash?

**Comment by pjs102** [comment]
I'm running Windows powershell. From there i'm launching "vagrant ssh" to a virtual machine.

**Comment by Tyriar** [comment]
I'm guessing the problem is one of the following then:

- PowerShell not passing through the escape sequences correctly, if this doesn't happen in a native PS window then,
- A winpty problem which are being collected in the issue https://github.com/Microsoft/vscode/issues/45693
