### ISSUE TITLE
"Move to Next Change" and "Move to Previous Change" don't work in SCM view

### ISSUE THREAD

**Issue by franciscolourenco** [Microsoft/vscode#48964]
Issue Type: <b>Bug</b>

1. Make multiple changes in a file
2. Open the file in differ view — inline or side-by-side, it doesn't matter
3. Evoke the comand "Move to Next Change"

The caret is expected to move to the next change, like it happens in the normal editor, however nothing happens

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by franciscolourenco** [comment]
Is this a duplicate of https://github.com/Microsoft/vscode/issues/48964 ?

**Comment by franciscolourenco** [comment]
Is this a duplicate of https://github.com/Microsoft/vscode/issues/44904 ?

**Comment by joaomoreno** [comment]
Yes it is!
