### ISSUE TITLE
Can't pass in launch debug argument raw to the shell

### ISSUE THREAD

**Issue by kamranayub** [Microsoft/vscode#48967]
I'm trying to pass in an argument for my Jest config via create-react-app (react-scripts-ts). Since `moduleNameMapper` isn't a Jest option CRA lets me override by default, I have to pass it via CLI arguments.

This works fine in our npm scripts, like so:

    react-scripts-ts test --env=jsdom --moduleNameMapper='{\"^~/(.*)\":\"<rootDir>/src/$1\"}'

But now I'm trying to configure the same command to debug our tests via VS Code. Here's my launch.json as it is right now:

```js
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug CRA Tests",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts-ts",
      "args": [
        "test",
        "--runInBand",
        "--no-cache",
        "--env=jsdom",
        "--moduleNameMapper='{\"^~/(.*)\":\"<rootDir>/src/$1\"}'",
        "--showConfig"
      ],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```

The issue is that VS Code is forcing the `moduleNameMapper` arg to be quoted if it contains any quotes. This makes it so Jest can't parse the argument and then it fails to use my additional mapping override (you can tell with the `--showConfig` arg).

    node_modules/.bin/react-scripts-ts --inspect-brk=16624 test --runInBand --no-cache --env=jsdom "--moduleNameMapper='{\"^~/(.*)\":\"<rootDir>/src/$1\"}'" --showConfig

Since the `moduleNameMapper` expects a JSON object as the argument value, is there any way to get VS Code to just let me pass it in raw?

- VSCode Version: 1.22.2
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. Create a launch.json file
2. In the `args` array, add a argument that would contain a quote like `"--moduleNameMapper='{\"^~/(.*)\":\"<rootDir>/src/$1\"}'"`
3. Inspect debug output to see VS Code adds quotes around the argument string

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
You're right that it's interpreted as JSON before it's passed to the process, so you'll have to escape any special characters same as you would in a JS string.

If you want `--moduleNameMapper='{\"^~/(.*)\":\"<rootDir>/src/$1\"}'` passed to the process, you'll have to escape the `\` like

`--moduleNameMapper='{\\\"^~/(.*)\\\":\\\"<rootDir>/src/$1\\\"}'`

You can look at what it writes to the Debug Console to check it.

**Comment by kamranayub** [comment]
I'm positive I tried that but I'll double check, I don't think it's the
escape characters, I think it's the surrounding quotes.

**Comment by kamranayub** [comment]
Yeah, I've tried this--the issue isn't really escaping, it's the fact VS Code adds surrounding quotes which the program doesn't expect and fails to parse as an argument option.

My proposal is to allow VS Code to optionally allow unquoted (i.e. raw) arguments to the shell for this kind of use case.

Something like:

```js
args: [
        "test",
        "--runInBand",
        "--no-cache",
        "--env=jsdom",
        { raw: true, arg: "--moduleNameMapper='{\"^~/(.*)\":\"<rootDir>/src/$1\"}'" },
        "--showConfig"
]
```

**Comment by roblourens** [comment]
Does it work for you if you don't use `"console": "integratedTerminal"`?

**Comment by kamranayub** [comment]
@roblourens It still showcases the same issue, the output *shows* that it is not using surrounding quotes but symptoms are the same (i.e. the parameter isn't picked up) which makes me think it's still being quoted behind the scenes. Pasting the same command into a separate terminal works fine, like before.

**Comment by roblourens** [comment]
How can I try this or verify that it's working? I tried the exact command that you pasted originally:

![image](https://user-images.githubusercontent.com/323878/39789574-9b381b76-52e5-11e8-8b45-40d9ae279a54.png)

**Comment by roblourens** [comment]
I tried it and I think the problem is actually the single quotes around the object. They are necessary in a shell but not when passed to the process directly. Try 

`"--moduleNameMapper={\"^~/(.*)\":\"<rootDir>/src/$1\"}",`

that seems to work for me.

**Comment by kamranayub** [comment]
Yes it works! All I had to do was also escape `$1` with `\\$1`. For reference, this is the config that works:

```
{
      "name": "Debug Tests",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts-ts",
      "args": [
        "test",
        "--runInBand",
        "--no-cache",
        "--env=jsdom",
        "--moduleNameMapper={\"^~/(.*)\":\"<rootDir>/src/\\$1\"}"
      ],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "console": "integratedTerminal"
    }
```
