### ISSUE TITLE
Diff in new window?

### ISSUE THREAD

**Issue by thaindq** [Microsoft/vscode#48962]
- VSCode Version: 1.22.2
- OS Version: Windows 10 (1709)

Steps to Reproduce:

1. Use diff command: `C:\Program Files\Microsoft VS Code\Code.exe -n -d $LOCAL $REMOTE`
2. VS Code seems to ignore `-d` argument when `-n` is provided.

Expectation:
* A diff screen is opened in a new VS Code window.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I cannot reproduce on macOS using this command:

`code-insiders -n -d ~/Desktop/test-js/package.json ~/Desktop/end-js/package-lock.json `

Does it reproduce when you pass in actual file paths on disk?

**Comment by thaindq** [comment]
Passing in actual files seems to work. I was using Sourcetree to perform diff command and this only happens when a VSCode window has already been opened. I can see the diff tab was opened and closed immediately.

![](https://i.imgur.com/2EjO21f.gif)

**Comment by bpasero** [comment]
@thaindq any difference if you configure `"workbench.editor.closeOnFileDelete": false`?

**Comment by thaindq** [comment]
@bpasero there is no difference

**Comment by bpasero** [comment]
@thaindq are you sure the "-n" option is passed from your external program?

**Comment by thaindq** [comment]
@bpasero yes, this is my sourcetree configurations

![](https://i.imgur.com/RUUUPh5.png)

**Comment by thaindq** [comment]
@bpasero yes it does

**Comment by bpasero** [comment]
@thaindq and if you do "`-n $LOCAL`" and afterwards "`-n $REMOTE`" does it reproduce with either? What gets opened when you try it?

**Comment by thaindq** [comment]
It reproduce with the former. The latter opens the `$REMOTE` file normally (no diff).

**Comment by bpasero** [comment]
@thaindq can you get hold of the actual value that your program puts in just so we now how this program executes Code?

**Comment by thaindq** [comment]
I'm unable to catch what Sourcetree sends to VSCode but this is what I can gather from Task Manager.

After diffing without VSCode window opened beforehand
![](https://i.imgur.com/9Aa2lOu.png)
After opening an empty VSCode window (manually)
![](https://i.imgur.com/f5Mhhke.png)
After diffing with a VSCode window opened beforehand
![](https://i.imgur.com/r5A5Xqz.png)

**Comment by bpasero** [comment]
yeah try that

**Comment by thaindq** [comment]
I try with SmartGit and it works correctly. It's likely Sourcetree problem so I'll close this, and thank you for your help @bpasero
