### ISSUE TITLE
Support API to cancel/dismiss a notification (that you sent)

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#48960]
Now that the notification UI has changed, notifications will likely be used for more things, including ephemeral things. So it would be great to have a way to "cancel" or dismiss a notification that an extension itself sent.

For example, in the CodeStream extension, I have a few cases where I show a notification in response to a request (someone asking you to join a live share, etc) and if that live share is no longer valid, I might like to clear the notification. Another case would be to show notifications for messages received (via a setting of course) but to be able to cancel previous notifications, and thus allowing me to send a new "grouped" notification.

Maybe use a CancelationToken on `showInformationMessage`, etc?

/cc @bpasero

**Comment by eamodio** [comment]
This could also provide a convenient mechanism to know when a notification was dismissed as well.

**Comment by eamodio** [comment]
@jrieken While this is a very close to https://github.com/Microsoft/vscode/issues/44122, that issue is closed and locked. So I couldn't add any comments or anything. I was also suggesting an alternative control method that would be less about new api's to control notifications, but just using cancellation tokens similar to other apis vscode already has.

Can one of these issue be reopened?

**Comment by jrieken** [comment]
Not convinced and I happily repeat why I think programmatic removal of notifications is a bad idea: It is a notification, e.g. something that interrupts you and that grabs your attention. Interrupting someone and then saving "na, just kidding keep on working" isn't good. So, please convince me that it is a good idea to show and then hide notifications while I am working on something?

**Comment by eamodio** [comment]
My main argument is for notifications that are transient (or only valid for some time period) and that you would not want to build up. For example, connectivity issues -- we might want to show a notification to the user that we are failing to connect, but still keep trying for a bit in the background, and if we re-connect clear out the old useless notification.

Also for notifications that could be grouped together it can allow for that, by allowing cancelling a previous notification and group it into a new incoming one.

Since notifications themselves are now transient there is no guarantee that the user has even seen it before it goes to the notifications "panel" so keeping that as clean for the user imo is a good goal.

**Comment by TomasHubelbauer** [comment]
I think I have found a good use case for dismissing no longer applicable notifications programatically…

![image](https://user-images.githubusercontent.com/6831144/41100104-bd166ac6-6a60-11e8-95fd-511949db3921.png)
