### ISSUE TITLE
File tree getting strange rendering artifacts almost 10 times a day now.

### ISSUE THREAD

**Issue by sergiotapia** [Microsoft/vscode#48966]
- VSCode Version: 1.22.2
- OS Version: os sierra

Steps to Reproduce:

Dunno, just happens randomly throughout the day. To fix, I need to click the refresh icon in the tree, but that stops it for a bit only.

![image](https://dzwonsemrish7.cloudfront.net/items/323x2p0H2x121m391c41/Screen%20Recording%202018-04-30%20at%2002.56%20PM.gif?v=73361601)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
@joaomoreno sounds like a duplicate of the one you already have, right?
