### ISSUE TITLE
Flask debugger: error: could not import "C"

### ISSUE THREAD

**Issue by tcvandongen** [Microsoft/vscode#48972]
Issue Type: <b>Bug</b>

When starting the flask debugger I get the error below. This does not occur when I start the  debugger via the command prompt. My expectation would be that the flask app will run and that I can access it via localhost. I do not understand what "C" is which it tries to import and when starting the debugger I received an error: unable to find "". This might be related to the problem.

PS C:\Users\tcvandongen\Desktop\Developer Projects\Networkz> cd 'c:\Users\tcvandongen\Desktop\Developer Projects\Networkz'; ${env:FLASK_APP}='C:\Users\tcvandongen\Desktop\Developer Projects\Networkz/networkz.py'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'c:\Users\tcvandongen\Desktop\Developer Projects\Networkz\venv\Scripts\python.exe' 'C:\Users\tcvandongen\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_launcher.py' 'c:\Users\tcvandongen\Desktop\Developer Projects\Networkz' '50697' '34806ad9-833a-4524-8cd6-18ca4aa74f14' 'RedirectOutput,RedirectOutput' '-m' 'flask' 'run' '--no-debugger' '--no-reload'
 * Serving Flask app "C:\Users\tcvandongen\Desktop\Developer Projects\Networkz/networkz.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: python -m flask run [OPTIONS]

Error: Could not import "C".

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|Memory (System)|7.89GB (4.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1

</details>

**Comment by elliotwoods** [comment]
@tcvandongen - i'm getting the same. any success?
