### ISSUE TITLE
cmder integrated terminal task issues

### ISSUE THREAD

**Issue by nicholasjbbaldwin** [Microsoft/vscode#48986]
Issue Type: <b>Bug</b>

1. Download cmder from http://cmder.net/ and set as integrated terminal for windows using instructions here https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions
2. Create a simple.bat file with `@echo this works`.
3. Make a shell task that runs simple.bat as the command.
4. Run said task.

Actual results: 
```
> Executing task in folder test_project: simple.bat

C:\sandbox\test_project
λ 
```
Cursor sits there, echo does not happen and the task never completes.

Expected results: 
```
> Executing task in folder test_project: simple.bat

this works
```

Thoughts:
If we must use the integrated terminal to run tasks, could we have an option to use a different shell for these tasks if they don't play nice with the task system?

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|15.95GB (7.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
better-comments|aar|1.2.2
vscode-color|ans|0.4.5
gitlens|eam|8.2.4
vscode-html-css|ecm|0.2.0
Go|luk|0.6.78
vscode-todo-parser|min|1.9.1
python|ms-|2018.3.1
cpptools|ms-|0.16.1
debugger-for-chrome|msj|4.3.0
material-icon-theme|PKi|3.3.0
stylelint|shi|0.36.0
vscode-hexdump|sle|1.6.0
vim|vsc|0.11.5
vscode-wakatime|Wak|1.2.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by dbaeumer** [comment]
You can specify a shell to use in the tasks.json file:

```
{
	"version": "2.0.0",
	"options": {
		"shell": {
			"executable": "cmd.exe",
			"args": [
				"/d", "/c"
			]
		}
	},
	"tasks": [
		{
			"label": "echo",
			"type": "shell",
			"command": "dir"
		}
	]
}
```

The options can be specified per tasks as well.

Do you know which command line args cmder use to execute a command and then quite (like /d /c for cmd.exe). Then I can add them. As a work around for now you can have the options in the tasks.json point to cmder.exe and use the right options.

**Comment by dbaeumer** [comment]
@nicholasjbbaldwin any information?

**Comment by patstew** [comment]
The problem is that the VS Code documentation recommends doing this to start cmder:
```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": ["/K", "C:\\cmder\\vscode.bat"]
```
and you can only have one /K or /C, so appending another one to do the task doesn't work. You'd need to to end up with an arguments array like:
`["/K", "C:\\cmder\\vscode.bat", "&", "task_command", "task_arg"]`

**Comment by dbaeumer** [comment]
I am a little puzzled. Isn't cmder a standalone executable which supports something like `/k`or `/C`itself?

**Comment by patstew** [comment]
There is a cmder executable, but it's a full terminal emulator in its own right that can't be used as the integrated shell. See #12006
