### ISSUE TITLE
Feature request: terminal scrolling is independent of open fraction, make it adjustable

### ISSUE THREAD

**Issue by willauld** [Microsoft/vscode#48984]
I move between terminal and edit pain frequently changing the fraction of each that is open. Often when the terminal has a small fraction showing the scroll "jump" is so large that I can't get what I want into the window even when there is enough room. I like to see a small jump or some how have a fine control of the scroll.

**Comment by Tyriar** [comment]
ctrl+shift+up/down let you scroll a single line.

**Comment by willauld** [comment]
That works in the edit window (which is nice) but not in the terminal window where I have the problem.

**Comment by Tyriar** [comment]
@willauld I suggest you open the keyboard shortcuts view and look at the scroll shortcuts on your system. It's different to the editor and it's different based on platform:

![image](https://user-images.githubusercontent.com/2193314/39950229-b03740b4-5534-11e8-8879-58a0a820c2d4.png)

**Comment by willauld** [comment]
That is perfect. Just the functionality I need. Thanks Much!
