### ISSUE TITLE
cmder integrated terminal moves cursor two characters for each space

### ISSUE THREAD

**Issue by nicholasjbbaldwin** [Microsoft/vscode#48988]
Issue Type: <b>Bug</b>

This seems to be an issue with the interaction between cmder and vscode, this may not be an issue with vscode, but I am trying to get some more context.

When using cmder as an integrated terminal (after following instructions on https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions) there is a strange graphical issue where some characters (space and colon for example) will cause the visual cursor to jump two positions in the buffer and some movement commands (i.e. ctrl+left) will jump to the wrong visual position. The editing position will still be correct, but this means that typing and editing commands in the buffer becomes very cumbersome since I cannot rely on the cursor position being accurate. 

Screengrab showing the issue (slowed down at points to show the glitch):
![cmder_glitch](https://user-images.githubusercontent.com/3220546/39460440-302e3618-4cb8-11e8-89b4-eb77b96bfe21.gif)

What I'm wondering is if there is some sort of wide character issue that may be the cause here, this glitch does not occur when cmder is used as a normal shell outside of vscode so my guess is there is some transformation when input is passed to the integrated shell that causes cmder to assume a two byte character was inserted.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|15.95GB (8.09GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
better-comments|aar|1.2.2
vscode-color|ans|0.4.5
gitlens|eam|8.2.4
vscode-html-css|ecm|0.2.0
Go|luk|0.6.78
vscode-todo-parser|min|1.9.1
python|ms-|2018.3.1
cpptools|ms-|0.16.1
debugger-for-chrome|msj|4.3.0
material-icon-theme|PKi|3.3.0
stylelint|shi|0.36.0
vscode-hexdump|sle|1.6.0
vim|vsc|0.11.5
vscode-wakatime|Wak|1.2.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Tyriar** [comment]
This looks like an issue with the emulation layer that sits between conhost and vscode, we're collecting all these issues in https://github.com/Microsoft/vscode/issues/45693
