### ISSUE TITLE
Allow to change the color of file icons

### ISSUE THREAD

**Issue by Nxt3** [Microsoft/vscode#48982]
In Atom, you can use `less` to override the file icon color so it's different than what's in the tree view.

<img width="622" alt="screen shot 2018-04-30 at 8 38 14 pm" src="https://user-images.githubusercontent.com/2940826/39456730-b6ba4610-4cb6-11e8-8128-4a194354c65e.png">

In the screenshot, the `.gitignore` file has a red file icon--but in the tab, it's white.

Is something like this possible with VS Code currently? If not, I think themes should have ability to theme this aspect.

**Comment by aeschli** [comment]
Our file icons can be multi colored and are defined by icon themes.
We currently have no plan to add color theming on top of that.

**Comment by wopian** [comment]
ref: https://github.com/PKief/vscode-material-icon-theme/issues/242
