### ISSUE TITLE
[loc][Query][DevDiv] Please clarify placeholder "{0}"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#4898]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Hi, we have a question about the source text. Can you please help?

source:
{0}
{0}
{0}

Resource ID:
".resx", 0; "json.bower.package.hover"
".resx", 0; "json.npm.package.hover"
".resx", 0; "json.nugget.package.hover"

File Name:
extensions\json\server\out\jsoncontributions\bowerJSONContribution.nls.resx
extensions\json\server\out\jsoncontributions\packageJSONContribution.nls.resx
extensions\json\server\out\jsoncontributions\projectJSONContribution.nls.resx

Query:
Can you please clarify these placeholders? What will it be replaced by?

**Comment by aeschli** [comment]
In package.json, bower.json and in project.json, you can hover over a entry in the dependency section. It would show you a hover with the name, description  and the latest version of that dependency.

The resource string mentioned is the first line of the hover, representing the name of the dependency.
I could change it to no use a NLS lookup.
