### ISSUE TITLE
Resolution of windows explorer is tiny on 4k

### ISSUE THREAD

**Issue by FallingReign** [Microsoft/vscode#48995]
![tiny explorer](https://user-images.githubusercontent.com/3497830/39464979-06b7e980-4d64-11e8-9d83-270bf1d80ae6.PNG)

Issue Type: <b>Bug</b>

open vs code on a 4k monitor.
save as, or open folder to show explorer.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.86GB (1.86GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.12.0
beauty|yhp|0.0.2

</details>

**Comment by bpasero** [comment]
Nothing we control, this is OS specific.
