### ISSUE TITLE
Integrated terminal not working

### ISSUE THREAD

**Issue by kkbrains** [Microsoft/vscode#48994]
- VSCode Version: v1.22.2
- OS Version: Mac OS Sierra v10.12.6

Steps to Reproduce:

1. Open vscode and click View->"Integrated terminal",  it shows blank screen

I have cross checked the vscode settings and the bash terminal pointing to the right folder path
`  // The path of the shell that the terminal uses on OS X.
  "terminal.integrated.shell.osx": "/bin/bash",`

On Developer tools I am getting the following console message while clicking terminal window

`[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. Terminal.ts:2212`
`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. Terminal.ts:2212`
`[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.`

**Comment by Tyriar** [comment]
Can you close all VS Code windows and then launch in a terminal with `code --log trace`. This will expose some terminal logs that you can get to from the command "Developer: Open Log File..." (F1 opened command palette). Can you get the logs when the issue happens and paste it in here?
