### ISSUE TITLE
updating multiple colors with color picker is not happening.

### ISSUE THREAD

**Issue by devsumanmdn** [Microsoft/vscode#48990]
## Bug report:
**When selecting multiple colors and update them with the color picker in a CSS file only the one which is selected in the last is getting updated.**

- VSCode Version: March 2018 (version 1.22)
- OS Version: Ubuntu 16.04

Steps to Reproduce:  

1. Choose multiple color values in a CSS file.
2. Then try to pick a color from color picker.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
The color picker doesn't depend on selections, it's only for color where the mouse hovers over...

**Comment by octref** [comment]
Closing since working as-designed.
