### ISSUE TITLE
Edited code disappeared!

### ISSUE THREAD

**Issue by BenjaminSamuel** [Microsoft/vscode#48991]
Issue Type: <b>Bug</b>

I edited the code and now I am unable to see the changes. 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|15.90GB (10.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Darkness_Creator\AppData\Roaming\Code\Backups\workspaces.json|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by rebornix** [comment]
Could you please provide more detailed info to help troubleshoot? A gif can help.
