### ISSUE TITLE
scripts/code.sh interfering with VS Code Alpha

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4899]
Sometimes the dev version of VS Code and VS Code Alpha seem to 'merge' on the mac. Then they show as one one icon. Also, reloading VS Code Alpha sometimes make the extension host of VS Code Dev crash...

**Comment by jrieken** [comment]
@joaomoreno We talked about this

**Comment by joaomoreno** [comment]
Very creepy yeah

**Comment by joaomoreno** [comment]
cc @bpasero any thoughts?

**Comment by bpasero** [comment]
The dock issue might well be https://github.com/Microsoft/vscode/issues/4443

I never saw a reload in selfhost crash the extension host in dev though...

**Comment by jrieken** [comment]
Also, I then see stuff like this tho no ./scripts/code.sh is running

```jrieken:~/Code/vscode$ ./scripts/test-integration.sh
[12:37:50] Using gulpfile ~/Code/vscode/gulpfile.js
[12:37:50] Starting 'electron'...
[12:37:50] Finished 'electron' after 320 μs
Running extension tests from the command line is currently only supported if no other instance of Code is running.
jrieken:~/Code/vscode$
```

**Comment by bpasero** [comment]
That should only ever show up if `--extensionTestsPath` is provided from the command line.

**Comment by jrieken** [comment]
fyi - I see this a lot and it prevents me from running the integration tests properly

**Comment by joaomoreno** [comment]
I either need a reproducible scenario or just ping me when it happens on your machine and we can look at it together, @jrieken, since I don't seem to hit it.

**Comment by jrieken** [comment]
often happens like this

* run ./scripts/code.sh from iterm
* quit code.sh by press ion Ctrl+C in iterm (not invoke Cmd+Q)
* run ./scripts/test-integration.sh
* happens

**Comment by joaomoreno** [comment]
Hm just tried a bunch of times, still nothing. :(

**Comment by joaomoreno** [comment]
@jrieken, @bpasero found it! It wasn't a communication problem between dev and alpha but we were just calling `dock.hide()` on dev way too early.
