### ISSUE TITLE
Move down list item keeps ident

### ISSUE THREAD

**Issue by amkgo** [Microsoft/vscode#48993]
Create an HTML file with the following list:
```
<ul>
    <li>
       list 1
    </li>
    <li>
        list 2
    </li>
    <li>
        list 3
    </li>
</ul>
```
Select the first 3 lines(list 1 item) and press `Alt+Arrow Down` to move the list down. Every time the list indent one tab like the following:
```
<ul>
    <li>
        list 2
    </li>
    <li>
        list 3
    </li>
                            <li>
                               list 1
                            </li>
</ul>
```

When select the list 1 and press `Alt+Arrow Up` to move the item up, it works as expected.

**Comment by rebornix** [comment]
Same issue as https://github.com/Microsoft/vscode/issues/54829#issuecomment-422501144, where I left some initial investigations. Let's track this bug there.
