### ISSUE TITLE
support node  debug console copy function

### ISSUE THREAD

**Issue by foxundermoon** [Microsoft/vscode#48998]
there is the copy function, but can not copy to clickboard.

![image](https://user-images.githubusercontent.com/2764106/39471786-b1356424-4d77-11e8-91ae-b1f2c6773922.png)

it is  vevry usefull  when debug  copy some json  object. just as under chrome console.

**Comment by isidorn** [comment]
Context menu -> copy should do the trick for you.
If that is not what you want please elaborate on your request and we will reopen this. Thanks
