### ISSUE TITLE
Updater's STDOUT is making VSCode painful to use in the new WSL (Spring 2018 update)

### ISSUE THREAD

**Issue by nickjj** [Microsoft/vscode#49002]
Hi,

* VSCode Insiders (today's build) is installed inside of Windows 10 Pro 18.03 (Spring 2018)
* I'm also running WSL (Ubuntu 16) and using ConEmu / Bash

When starting VSCode with `code-insiders .` from a directory, it will correctly launch VSCode but it will also output a whole bunch of updater specific text to STDOUT which takes over the foreground of the terminal.

Prior to the 18.03 update you could hit CTRL+C to kill the updater's foreground process and VSCode would continue to run, but now VSCode will exit.

Additionally, if you hit CTRL+Z to suspend the VSCode process, the updater's output will still continue to be output to the foreground and take over your terminal. At this point if you hit CTRL+C the updater's foreground process will exit and VSCode will remain open.

In the end, this means that your terminal is not really usable for 15 seconds after opening VSCode and you need to hit CTRL+Z, wait then hit CTRL+C. This is very disruptive.

What's even worse too is if the updater runs while VSCode is open, it will hijack your terminal's line buffer making you lose every thing you've typed into the terminal but haven't sent in as a command yet.

Unfortunately, even disabling updates doesn't resolve the issue because if you set the channel to `none` then VSCode still outputs "Updates are disabled" as a foreground process.

I've included a screenshot for clarity below:

![vscode](https://user-images.githubusercontent.com/813219/39474142-7c43ff70-4d20-11e8-864c-76d5d5b625cb.jpg)

The above happens with or without everything coming after the `&` (I was experimenting with workarounds). I also have a Bash alias which maps `code-insiders` to `code` in case you're wondering.

**Comment by nickjj** [comment]
A successful workaround was discovered by someone on Reddit.

Instead of launching VSCode with `code .` you'll need to run `cmd.exe /c code.cmd .`. To make this a bit more friendly, you can set up an alias in your `~/.bashrc` such as `alias code="cmd.exe /c code.cmd"`.

If you're using Insiders you'll need to change that to `alias code="cmd.exe /c code-insiders.cmd"`.

Any dangers or gotchas for doing this?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/44540

**Comment by nickjj** [comment]
Are there any potential issues with running `code.cmd` directly? Loss of functionality, potential edge cases?

**Comment by Tyriar** [comment]
@nickjj oh sorry, I missed the original question 😄. I can't think of any obvious issues with the workaround you're using 👍
