### ISSUE TITLE
Find/Replace lookbehind

### ISSUE THREAD

**Issue by canichols2** [Microsoft/vscode#49005]
Issue Type: <b>Bug</b>

(?!<pv)(contact|item|member|rental|system_user|address|lookup|telephone)(?!(_item|_group|_id|_name|_type|_meaning|_context|_lab|ship))

The Regex lookbehind doesn't work. I need to select and replace all text that matches the top line that doesn't start with "pv", but vscode doesn't recognize the lookbehind negation. I'm doing it perfectly well with the lookahead.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.93GB (4.50GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
polymer-snippets|chi|1.0.1
gc-excelviewer|Gra|2.0.20
vscode-coding-tracker|han|0.6.0
CppSnippets|har|0.0.13
ftp-simple|hum|0.6.3
svg|joc|0.1.0
language-polymer|jon|1.1.0
Polymer2Snippets|jus|0.1.1
sshextension|kon|0.2.1
ftp-sync|luk|0.3.3
rainbow-csv|mec|0.2.1
python|ms-|2018.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
polymer-ide|pol|0.6.0
live-sass|rit|1.3.0
LiveServer|rit|3.2.1
vscode-icons|rob|7.23.0
sass-indented|rob|1.4.9

(3 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/8635 .

**Comment by canichols2** [comment]
@rebornix
Does the fact that this is a duplicate problem from years ago, that's been closed, and locked from comments/edits mean that it's a problem that is never going to get fixed?
