### ISSUE TITLE
Incorrect syntax highlighting in JS with `instanceof` operator in conditional

### ISSUE THREAD

**Issue by JonathanWolfe** [Microsoft/vscode#49006]
### Info
Seems to be an issue with the `end` regex here: https://github.com/Microsoft/vscode/blob/master/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L2325-L2338
The appropriate OR clause seems to be included `\\|\\|` but isn't activating. Maybe there's a syntax error in there somewhere but it's a very hard regex to read.

### Steps to Reproduce:
![image](https://user-images.githubusercontent.com/1449779/39478809-7048c104-4d31-11e8-8720-7541be378753.png)
```js
function isDate( input ) {
	return input instanceof Date || Object.prototype.toString.call( input ) === '[object Date]';
}
```

### Desired
![image](https://user-images.githubusercontent.com/1449779/39478860-8f9df10a-4d31-11e8-8e55-17e74d6734d8.png)
```js
function isDate( input ) {
	return ( input instanceof Date ) || Object.prototype.toString.call( input ) === '[object Date]';
}
```

**Comment by mjbvz** [comment]
Should be fixed in VS Code insiders:

<img width="804" alt="screen shot 2018-05-01 at 9 38 02 am" src="https://user-images.githubusercontent.com/12821956/39482313-677745cc-4d23-11e8-9b24-bfcbfe7fbc6c.png">
