### ISSUE TITLE
Activity Bar background color/hinting option for open windows

### ISSUE THREAD

**Issue by andrewwilley** [Microsoft/vscode#49001]
When working in multiple windows, it would be useful to allow a right-click menu option to select a different color for the activity bar, while leaving the other themed elements the same.  This would help when working on code in different folders that may have similar files to provide visual feedback as to what window is currently open.

**Comment by bpasero** [comment]
This can be done via  a workspace setting and:

```json
"workbench.colorCustomizations": {
	"activityBar.background": "#ff0000"
}
```

**Comment by andrewwilley** [comment]
Interesting.  I tried that, but it only applied when entered as a user setting, didn't apply when I added it as a workspace setting for a folder.
