### ISSUE TITLE
Emmet shortcuts not working

### ISSUE THREAD

**Issue by suit0r** [Microsoft/vscode#49004]
Issue Type: <b>Bug</b>

Since the last, April update, my emmet shortcuts stopped working. I checked for conflicts, and there are none, but stuff like go to matching pair, balance inward/outward, and more are not working anymore. Is this a reinstall fix?

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|Memory (System)|7.89GB (1.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
scss-lint|ada|0.1.3
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.3
vscode-markdownlint|Dav|0.15.0
jshint|dba|0.10.18
beautify|Hoo|1.3.0
csstriggers|kis|0.4.0
vscode-autoprefixer|mrm|2.1.2
debugger-for-chrome|msj|4.3.0
material-icon-theme|PKi|3.3.0
sass-indented|rob|1.4.9
vscode-field-lights|sve|0.0.10
JavaScriptSnippets|xab|1.6.0

(3 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
Can you look at your keybindings file, and ensure that they shortcuts are still there?
Run `Preferences: Open Keyboard Shortcuts File`. On the right, are your shortcuts present?

**Comment by suit0r** [comment]
hi there,

yes they're still there. what's worse, executing them manually through the command palette doesn't work either.

**Comment by ramya-rao-a** [comment]
Can you run `code --disable-extensions` and try again?
If not, then please provide a code sample, with steps of what you tried to do and the file type you tried it in

**Comment by suit0r** [comment]
got it fixed, somehow, by switching working directories. simply closing and opening vscode wasn't cutting it, but thanks for all your help.

**Comment by ramya-rao-a** [comment]
@suit0r Any reason this issue is re-opened?

**Comment by suit0r** [comment]
sorry I did it a bit prematurely, but the issue returned, so I guess I'll get more details for you. it seems certain Emmet commands like balance and go to closing bracket glitch

**Comment by ramya-rao-a** [comment]
Ok, first try running `code --disable-extensions`. I want to ensure that none of the other extensions you have is interfering with the emmet commands

**Comment by suit0r** [comment]
hi again. just ran vs code with extensions disabled and neither the shortcut nor the Emmet command command palette works

**Comment by suit0r** [comment]
hi again. it's very intermittent. I will keep ab eye out on the log now, but I find it mostly happens if I open a file. not from. the working directory.

**Comment by MartCube** [comment]
Seems I have the same problem. Since the last, April update I cant use emmet in my vue files

**Comment by bbailleux** [comment]
@suit0r Can you be kind enough to tell us where those config files are located and which one precisely you have deleted?
