### ISSUE TITLE
Indent ES7/Babel Object Rest/Spread Properties in arrow functions

### ISSUE THREAD

**Issue by damienleroux** [Microsoft/vscode#4901]
- VSCode Version: 0.10.13-insider
- OS Version: window 7 Pro SP1

Using VSCode and Babel/ES7 for JavaScript, I have issues when indenting code using [the object spread operator](https://github.com/sebmarkbage/ecmascript-rest-spread). This specification allow to write:

```javascript
    let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
    x; // 1
    y; // 2
    z; // { a: 3, b: 4 }
```

Steps to Reproduce:

1 . write this code:

```javascript
function main() {
  var p; //a promise

  var callback = () => {
    var data = { x: 1, y: 2, a: 3, b: 4 };
    let { x, y, ...z } = data;
    x; // 1
    y; // 2
    z; // { a: 3, b: 4 }
  };

  p.then( callback );
}
```
All works fine when auto indenting this code

2 . When trying to make `callback ` an anonymous function, it doesn't indent as wanted anymore:

```javascript
function main() {
  var p; //a promise

  p.then(() => {
    var data = { x: 1, y: 2, a: 3, b: 4 };
    let { x, y, ...z } = data;
x; // 1
y; // 2
z; // { a: 3, b: 4 }
  } );
}
```

Has anyone meet this problem?

**Comment by egamma** [comment]
The TS/JS language service does not support Rest/Spread properties, pls see https://github.com/Microsoft/TypeScript/issues/2103.

**Comment by damienleroux** [comment]
Using ESLint to lint error, I succeed to [lint ES7/babel code as wanted](http://stackoverflow.com/questions/36327096/visual-studio-code-linter-es7-babel-code/36327097#36327097). So VSCode work perfectly well with ES7 code. Indentation in VSCode already fills a lot of use case: it is very awesome. Just the sum of this spread + anonymous function doesn't work :( as expected.

Thank you for the link but I don't want TypeScript to recognize it, I only need to have VSCode indent ES7 Rest/Spread properties in all cases. Let me know if I miss the point about the relation between TypeScript and VSCode.

Do you think a VS Code feature should be proposed? or is it a matter of improve VSCode parser?

**Comment by alexandrudima** [comment]
@damienleroux When you say "auto indenting", do you mean you run the formatter (`Format Code` from the context menu)?

**Comment by damienleroux** [comment]
Yes it is, doing alt-shift-f

**Comment by alexandrudima** [comment]
Thank you! Closing this one in favor of #4889 .
