### ISSUE TITLE
Hover tooltip with multiple languages in markdown is rendered incorrectly

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/vscode#49018]
VSCode: 1.22.2 x64, Windows 10

When hover contains MarkupContent with markdown that has fenced blocks with different languages, all blocks are colorized as a first language.

Returning array of [deprecated] MarkupStrings produces correct result (as is using `appendMarkdown` in TS.

![image](https://user-images.githubusercontent.com/12820357/39488708-e928cab4-4d37-11e8-847e-03c30a87182a.png)

![image](https://user-images.githubusercontent.com/12820357/39488753-0baf2c0e-4d38-11e8-9e88-b2597c96de71.png)

**Comment by MikhailArkhipov** [comment]
HTML is an attempt to keep documentation preformatted as `<pre>` are not supported and triple-tick block without the language appears to default to the editor language.

**Comment by MikhailArkhipov** [comment]
It is a bit complicated as it involves language server in .NET Core + VSC. So far I worked around by intending via `&nbsp;` rather than using `html`. But repro should be simple - feed markdown as displayed above. Such as
```
``````python
def class
``````
``````html
while not if
``````
```

**Comment by mjbvz** [comment]
I can't repo this in vscode insiders using the logic:

```js
new Hover(
`\`\`\`python
def class
\`\`\`
\`\`\`html
while not if
\`\`\``);
```

To create the documentation.

![screen shot 2018-05-02 at 11 27 34 am](https://user-images.githubusercontent.com/12821956/39541859-d34453b6-4dfb-11e8-90ba-d73f0b8daf97.png)

Please share an example extension
