### ISSUE TITLE
Code fold markdown lists regression

### ISSUE THREAD

**Issue by pylang** [Microsoft/vscode#49017]
I was able to code fold lists in markdown.  Now I cannot.   I can *only* fold by markdown headings.

- VSCode Version: 1.22.1
- OS Version: Win 7 

Steps to Reproduce:

1. Make a nested list in a `.md` file.
2. Try to code fold

Code-folding with Headers (Available)
![2018-05-01 15_08_22- untitled-1 md - working - visual studio code](https://user-images.githubusercontent.com/10778668/39488909-ca849b00-4d51-11e8-9ac7-8c85f6125b67.png)

Code-folding lists (No long available since prior releases)
![2018-05-01 15_08_56- untitled-1 md - working - visual studio code](https://user-images.githubusercontent.com/10778668/39488913-cceb84c6-4d51-11e8-9559-73bb422f70a1.png)

I would like to be able to collapse large lists again.  Perhaps this was a deprecated since adding the new [feature of folding markdown headers](https://code.visualstudio.com/updates/v1_22#_fold-markdown-by-heading-level).  If so, I'm not aware of the rationale for removing it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This was never really supported. It just happened to work with our old indentation based folding because. You can disable syntax based folding if you want to restore the old behavior

Marking as extension candidate
