### ISSUE TITLE
Allow to open an editor into a specific editor group

### ISSUE THREAD

**Issue by ppggff** [microsoft/vscode#49026]
Be able to open file (from explorer or other) always in specific editor group (one of left/center/right/current/...). 

This is useful when editing in one group, and doing some quick look of other files in another group.

**Comment by bpasero** [comment]
@ppggff if you Alt-click it will force open to the side. Did you try?

**Comment by ppggff** [comment]
@bpasero 
Thanks.

I found Alt-click will open file in the "right side" group when possible. For example:
  1. current at left group, Alt-click will open file at right group
  2. current at right group(no center group), Alt-click will open file at a **new** right group, and current group rename to center group
  3. current at right group(with center group), Alt-click do nothing

So Alt-click will work when editing in left or center group. 
But it cannot open file at left side, this make Alt-click not very useful in some situation.
For example, sometimes, I want to use left side group to edit code file, and use right side group
to keep some notes. My work flow is:
  1. check the notes at right group
  2. open a code file at left
  3. edit code file at left
  4. update notes at right
  5. open another code at left    // must active left group first! Alt-click won't work

**Comment by bpasero** [comment]
@ppggff do you have a suggestion with which gesture you could trigger this given that there are many groups to pick from where to open?

**Comment by ppggff** [comment]
@bpasero 
maybe:
  1. a checkbox or something in sidebar/status bar, to set default editor group (could be a setting)
  2. Alt + different mouse key
  3. Alt-click for right group, Shift-Alt-click(or Ctrl+click) for left group (do not auto create center group, could be a setting)

**Comment by frog1014** [comment]
So far it doesn't allow a user to spilt the editor when now is 3 splits.
for example:
There are Spilt group, a, b, and c, and index.js is in the group a, then it doesn't work when I press ctrl+\ to attempt to spilt index.js to group b, I have to reduce the group amount to lower than 3.

**Comment by AAAboutajedyne** [comment]
> @ppggff do you have a suggestion with which gesture you could trigger this given that there are many groups to pick from where to open?

Alt + click opens it at the next group, and if the current is the last group, it doesn't create a new group it cycles back to the first
.Ex: I have 2 groups:
  .. if the current group is (1), if I Alt + click it opens the file at the (2) group
  .. if I'm at the (2) group  it opens it at the (1) group

Creating a new group by using just wanting to open a file in a group (Alt + click) is too much and is a bad design decision I think, cause opening a file doesn't need to change the preferred dev's layout. 

Layouting (How much group I need, and where they must be placed) is a static thing that doesn't change often by devs - each one has a preferred layout; and when they want to change it, they have a set of options (split horizontally, split vertically, buttons on the menu, ...), but opening a file next to the current group is another thing.
