### ISSUE TITLE
Do not reset WSL permissions metadata on save

### ISSUE THREAD

**Issue by drujd** [Microsoft/vscode#49021]
The April Windows 10 update brings many improvements to WSL. One of them is the possibility to save unix permissions as NTFS file metadata:

https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/

One of the caveats is: "Editing a file using a Windows editor may remove the file's Linux metadata. In this case, the file will revert to its default permissions"

As of now, VSCode unfortunately does exactly that - when you save the file, the metadata (containing i.e. the execution permission bit) is deleted.

It would be nice to keep the file's metadata on save.

**Comment by nickjj** [comment]
I also just upgraded to 18.03 and am noticing the same behavior.

Files get reset back to 755 as soon as you save them with VSCode (running in Windows).

**Comment by andrewmackrodt** [comment]
Unfortunately PhpStorm safe writes lose metadata for NTFS files (but not those mounted via SSH which v1 of that project was using).

From previously looking at this issue I believe it's a node.js issue.

**Comment by DarthSpock** [comment]
This is applicable for anything done in VSCode, not just nodejs just as mentioned in the OP. They need to do work on their end but what about everything else? I don't think we can or should expect package maintainers to update for this behavior since it's a Windows specific issue. IDEs need to be able to handle the behavior, which from your guys point of view is a feature request, but a necessary one in order to maintain security of our data.

**Comment by drujd** [comment]
@DarthSpock VSCode is written in Node.js/Electron. It utilizes Node.js methods for file operations.

**Comment by DarthSpock** [comment]
And the referenced issue in nodejs was closed when trying to address this saying "use this workaround". I pinged them about it to see what they say about it. But if it gets a "won't fix", then the team here will need to fork off from them and implement it themselves.

**Comment by drujd** [comment]
This might help: https://github.com/Microsoft/vscode/pull/42899

**Comment by onomatopellan** [comment]
I just couldn't wait and compiled VScode myself with PR #42899 and indeed it fixes this issue and unix permission are conserved when CTRL+S a file on DrvFs.
I hope they merge it soon.

**Comment by DarthSpock** [comment]
Problem is something with AppVeyor is blocking the merge and none of the MS devs appear to be troubleshooting the issue. For now the only workaround that preserves Linux permissions when working in WSL is to use the native Linux VS Code and doing so means suffering performance drops. Until the perf issues are resolved in WSL, Windows VS Code is the best route so this issue should be shown some serious attention over other new features since this is fundamental to workflow.

**Comment by Oxfos** [comment]
I'm also using WSL and I start VS Code (Windows) from Bash by simply typing `code`. But I experience the same problem, i.e. files being stripped all permissions when modified in VS Code (I see that when I start a new Bash session).
I was thinking to install the Linux VS Code but I read above that performance would be reduced. So I'd better wait. It would be nice if in a new VS Code version Linux permissions are not stripped when files are modified.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/pull/42899 is merged which claims to fix this. Alternate data streams will no longer be removed when saving a file. 

(I still think it is not advised to save files from Windows that are owned by WSL though, so do this at your own risk)

**Comment by nickjj** [comment]
> (I still think it is not advised to save files from Windows that are owned by WSL though, so do this at your own risk)

These aren't necessarily files owned by WSL. They are files that happen to be mounted into WSL.

Insiders 1.27 as of commit 6e559 (August 20th 2018's build) still resets files back to 755 on edit btw, not sure if that PR has made it into an insiders release yet.

**Comment by bpasero** [comment]
@nickjj can you verify with today's insider build

**Comment by nickjj** [comment]
@bpasero Seems to be working great now.

Here's what I did to test it:

1. `touch hi.txt`
2. `chmod 644 hi.txt`
3. `stat -c '%a %n' hi.txt` (to verify it is 644)
4. `code hi.txt`
5. Edit file in VSCode and then save it with VSCode
6. Repeat step 3, and it was still 644.

**Comment by bpasero** [comment]
@nickjj how does that setup work exactly? How is `hi.txt` linked from Windows into Linux? Specifically, how does `code hi.txt` turn into an absolute file path for VSCode to open?

**Comment by MicrosoftEurope** [comment]
@nickjj You should put the details into hi.txt

**Comment by nickjj** [comment]
@bpasero VSCode is installed directly within Windows (Windows installer) and `hi.txt` is a file that exists in a mounted drive that's mounted into WSL. The file and drive's content lives outside of the internal WSL file system.

The terminal I use (ConEmu) preloads `wslpath` to allow me to run `code` (which is a symlink of `code-insiders` btw) directly from within a WSL terminal. It's pretty rad!

**Comment by bpasero** [comment]
@nickjj makes sense, thanks

**Comment by bpasero** [comment]
Setting to verified based on https://github.com/Microsoft/vscode/issues/49021#issuecomment-414643802

**Comment by drujd** [comment]
Can also confirm that the Insiders build retains alternate data streams / WSL permissions! Thank you!

**Comment by bpasero** [comment]
Great. Also let me know if anyone is seeing weird issues when saving in general, the code change impacts every single save on Windows.
