### ISSUE TITLE
Add option to set a top-padding of the first line

### ISSUE THREAD

**Issue by m93a** [microsoft/vscode#49027]
- VSCode Version: 1.22.2
- OS Version: Windows 10 Pro 1709, build 16299.371

Steps to Reproduce:
1. Open new file
2. The first line is aesthetically close to the top of the window, especially if you want to start with a header or class definition etc.
3. Find out there is no way to add a padding there

I really think there should be an option `editor.firstLinePadding` for it.
![image](https://user-images.githubusercontent.com/1671665/39511572-2bdab3ca-4dee-11e8-94b1-0a6fb0920869.png)

**Comment by kirkstrobeck** [comment]
Agree, but think it could be `editor.paddingTop`, along with left and right.

**Comment by connor4312** [comment]
Definitely an edge case and not noticeable with small values, but the minimap doesn't take the padding into account when rendering 🙂 

![image](https://user-images.githubusercontent.com/2230985/75370216-98703900-5879-11ea-84b2-1db2175e5013.png)

**Comment by alexdima** [comment]
@connor4312 Yes, that is the current way the minimap works. It does not render any view zones. This can be observed for all view zones, such as the ones added by the diff editor, the inline references and this new padding.
