### ISSUE TITLE
UI title text doesnt fit with black box first time

### ISSUE THREAD

**Issue by segux** [Microsoft/vscode#49028]
Issue Type: <b>Bug</b>

When i hover over any element, i can see the title popup but the first time text is not fit to the box and can read it.
Only occurs the first time i hover on element.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.13.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 800)|
|Load (avg)|3, 4, 4|
|Memory (System)|15.55GB (3.45GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
ts-tslint|eg2|0.0.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
sass-lint|gle|1.0.1
intellij-idea-keybindings|k--|0.2.23
markdown-shortcuts|mdi|0.8.1
code-beautifier|mic|2.0.3
vscode-todo-parser|min|1.9.1
vsliveshare|ms-|0.2.547
debugger-for-chrome|msj|4.3.0
tsimporter|pmn|1.2.14
vscode-sass-format|sas|1.1.4
markdown-preview-enhanced|shd|0.3.5
autoimport|ste|1.5.3
language-stylus|sys|1.9.2
vscode-npm-scripts|tra|0.2.0
vscode-todo-highlight|way|0.5.12

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by segux** [comment]
Im testing and now looks fine.  Good job!

**Comment by segux** [comment]
@bpasero  wow, this is what i was wanting for long time ago. I hate to download every new version and install manually. 

Thanks! I love vscode and i love what are you doing guys. Javascript will dominate the world hahaha
