### ISSUE TITLE
VS code exits when using Ctl+w if no tab in open

### ISSUE THREAD

**Issue by rbecheras** [Microsoft/vscode#49023]
- VSCode Version:

```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

- OS Version:

```bash
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

Steps to Reproduce:

1. Lauch `vscode`
2. optionnal step: open one or many tabs
3. optionnal step: use `Ctl+w` to close all the openned tabs with the classic "close tab" keyboard shortcut
4. use `Ctl+w` one more time because sometime, wanting to close all the oppened tabs, we tape once too often the shortcut...

and it results with exiting vscode 

Does this issue occur when all extensions are disabled?: Yes, it doenst rely on any extension

**Comment by usernamehw** [comment]
You can unbind it.

**Comment by rbecheras** [comment]
Yes but I want to use `Ctl+w` to close tabs.

The problem is that it exit the app if no tab is opened.

Plus there is already `Ctl+q` to exit the app.

**Comment by usernamehw** [comment]
You can remove only the one that closes editor. Search for `ctrl+w` in keyboard shortcuts.

**Comment by rbecheras** [comment]
Ok I will search as soon I am front of my laptop.

But is there normal that if there is a shortcut (`Ctl+w`) that is configured to close the editor, it only close it when no opened tab anymore?

You confirm that behavior as normal?

**Comment by usernamehw** [comment]
Yep, it is `as-designed`.

**Comment by rbecheras** [comment]
Ok thank you very much. I'll can try it in some 10s of minutes
