### ISSUE TITLE
TypeScript Logpoint message doesn't include variables in the expected position

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#49039]
When I put `{expression}` inside a log point, it gets logged on the end of the message with a placeholder (`%0`) in its place. I don't know if this is intended or a bug; it's not what I expected.

I think it's specific to TypeScript rather than VS Code:

<img width="710" alt="screen shot 2018-05-02 at 10 45 30 am" src="https://user-images.githubusercontent.com/1078012/39516934-48d679c0-4df6-11e8-951a-95afd35af6db.png">

The lines with `CL` come from the `console.log` and the `LP` lines from the LogPoint.

(Edit: I'm using Insiders, not stable)

**Comment by roblourens** [comment]
This is the extensionHost. @isidorn does extensionhost output bypass the debug adapter and get handled somewhere else? I think I remember something like that.

**Comment by isidorn** [comment]
@roblourens that is correct. The extension host output gets handled [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L172)

**Comment by roblourens** [comment]
Ok, I think this is on vscode to support `%O` then.

**Comment by isidorn** [comment]
PRs that fix this are welcome

**Comment by weinand** [comment]
This is a bug that needs to be fixed.

**Comment by isidorn** [comment]
@roblourens @weinand do you already handle this case on your adapter side. If yes can you please give me a pointer?

Also note that if the message is `Hello my name is {name} and I like {kind} pizza.` the output is `Hello my name is %O and I like %O pizza. isidor ham`.
So it seems like the correct algorithm is to go from the right and each %0 replace with the whitespace seperated word from the end

**Comment by weinand** [comment]
Here is the node-debug code that converts the log message and its embedded expressions into a single expression that can be evaluated to produce the final string.

**Comment by isidorn** [comment]
@weinand this seems to do the opposite of what I need. Unless I am mistaken?
So it seems there is no code I could reuse, correct?

**Comment by weinand** [comment]
@roblourens Could we address the issue on the sending side, where the "%O" is not properly understood?

**Comment by roblourens** [comment]
Ignore that PR, it doesn't handle objects. But you have all the pieces there on the front end. You just need to parse the %O parameter and if the arg is an object, write it to the repl as an object. I can update the PR to handle objects if it isn't clearr

**Comment by roblourens** [comment]
Noticed another (very minor) issue: https://github.com/Microsoft/vscode/issues/57163

The code in vscode-chrome-debug-core for parsing format args is pretty complete if you want inspiration. Or I could try to spin it off into something that could be shared: https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/consoleHelper.ts#L76

**Comment by isidorn** [comment]
@roblourens something which could be shared would be great, yes.
Let me know if you do not have time for this in the endgame and in that case I will write some simple solution on the frontend side and we can share in the future.

**Comment by weinand** [comment]
@isidorn I don't understand how you want to parse the single string "Hello my name is %O and I like %O pizza. isidor ham." into the format string and its parameters?

**Comment by isidorn** [comment]
@weinand I would like to follow the parsing logic that you do on the adapter side.
Originaly I thought that the rule is change every %0 with a word from the end of the string - so first %0 would be replaced with isidor the second with ham. Though I might be wrong.

**Comment by weinand** [comment]
My "parsing logic" just replaces embedded `{expression}` with a "%O" and adds the "expression" as a additional parameter to the parameter list. This is simple because there is no ambiguity.
But if you just a have a string with words, how do you know where  what a parameter is?
How would you parse "Hello my name is %O and I like %O pizza. mister isidor ham and bacon."?

**Comment by isidorn** [comment]
"Hello my name is %O and I like %O pizza. mister isidor ham and bacon."? I would parse to
"Hello my name is and and I like bacon. pizza. mister isidor ham"?

Yes your suggestion makes it more clear on how to parse

**Comment by weinand** [comment]
Just for clarification:
if this is the original log message:
```
Hello my name is {'mister isidor'} and I like {'ham and bacon'} pizza.
```
This will be translated by the DA into this executable breakpoint condition:
```
console.log('Hello my name is %O and I like %O pizza.', 'mister isidor', 'ham and bacon');
```
which should output this (if everything works fine):
```
Hello my name is mister isidor and I like ham and bacon pizza.
```
and this flat string if `%O` is not interpolated:
```
Hello my name is %O and I like %O pizza. mister isidor ham and bacon
```
here the structural separators are lost and I see no way how to guess them without help from the sending side.

**Comment by roblourens** [comment]
You're not parsing a string, you actually have the original arguments. The EH side intercepts `console.log` with the correct arguments and sends it as-is to the frontend:

https://github.com/Microsoft/vscode/blob/master/src/bootstrap.js#L118

**Comment by roblourens** [comment]
I don't know if I'll have time this week because I have quite a few settings editor issues left, but you could just take my PR for something which is good enough most of the time.

**Comment by isidorn** [comment]
@roblourens sounds like a plan, thanks a lot. Have fun with settings :)

**Comment by isidorn** [comment]
I have pushed a fix proposed by @roblourens 
So the regular string messages work fine for me now.
For handling objects I expect follow up issues.
