### ISSUE TITLE
Shortcuts with all modifiers not working anymore

### ISSUE THREAD

**Issue by janschill** [Microsoft/vscode#49032]
- VSCode Version: 1.22.2
- OS Version: 10.13.4

Steps to Reproduce:

1. Open Keyboard Shortcuts File (cmd+shift+p >Open Keyboard Shortcuts File)
2. Add shortcut with all modifiers and another key eg. "ctrl+shift+cmd+alt+q" and a command like "workbench.action.toggleMaximizedPanel"
3. Try shortcut

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexandrudima** [comment]
@janschill I cannot reproduce with other letters. I have added the following to `keybindings.json`:

```js
{
	"key": "ctrl+shift+alt+cmd+m",
	"command": "actions.find"
}
```

After I twist my fingers to press all of those modifiers and <kbd>M</kbd>, the find widget shows up for me.

I cannot get the same working with <kbd>Q</kbd>. I have verified and we are not receiving the keypress for `ctrl+shift+alt+cmd+q` from the OS. Perhaps asking on an Apple forum might help...
