### ISSUE TITLE
[DEP0016] DeprecationWarning: 'GLOBAL'/'root' is deprecated, use 'global'

### ISSUE THREAD

**Issue by tmxklzp** [microsoft/vscode#49036]
![image](https://user-images.githubusercontent.com/20590535/39514800-da38e644-4e2a-11e8-87fd-692413470bd3.png)

- VSCode Version:1.22.2
- OS Version:Windows 10 Pro 64-bit
- Node Version: 8.9.0

Steps to Reproduce:

1.Start debug mode and write some commands in Debugging console.
![image](https://user-images.githubusercontent.com/20590535/39515521-ee8e4f2e-4e2c-11e8-8e9e-c48ee4724075.png)

2.After it executes complete, two warnings appear.
![image](https://user-images.githubusercontent.com/20590535/39515532-fa4b47f4-4e2c-11e8-8e02-1abfa8f4b0ae.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by tmxklzp** [comment]
Yes, it happens when I don't evaluate __proto__.
Actually __proto__ acts just like every other expressions.
But what I don't mention before is that, the two warnings don't appear when I evaluate the same expression in a short period of time. For those expressions, include __proto__ or __dirname or 1+2 or 'aaa', I start debugger and evaluate someone of them, warnings appear.Stop and start again with the same expression, it doesn't appear, unless I change the other expression

**Comment by roblourens** [comment]
I saw it once or twice, and thought maybe it was connected to when I evaluated `__proto__`. That would make sense, if the debugger is looking through the global prototype and touches `GLOBAL` or `root`. But I can't repro it reliably.

**Comment by Edgar-P-yan** [comment]
Once I had the same warning too, but I didn't write in the debug console or used `global` or `GLOBAL`. I couldn't reproduce it. I think the problem is not in console evalution but in the debugger itself.

**Comment by bywwcnll** [comment]
![image](https://user-images.githubusercontent.com/14292067/50945174-7c230880-14ce-11e9-8b3f-20a481379945.png)
It happens in the debugger

**Comment by am2641** [comment]
I've just run into this problem and it seems to be crashing the debugger when I work with WebdriverIO. As soon as I enter "browser.getTitle()" in the debugger command window, the debugger hangs and won't process any other command.

<img width="737" alt="vscode" src="https://user-images.githubusercontent.com/17334113/65558204-f080d780-df89-11e9-8c33-84ea210f07d2.PNG">

**Comment by mactive** [comment]
It happens in the debugger

**Comment by mactive** [comment]
It happens in the debugger

**Comment by am2641** [comment]
It seems like the debug console can't handle execution of methods

**Comment by mathias22osterhagen22** [comment]
The same happened to me when I used the "page.click" function of puppeteer. What is strange it is that I call this function already 10 times before.

The debugger just crash

![image](https://user-images.githubusercontent.com/60438474/85540228-09044800-b617-11ea-93ff-130f9121c8c7.png)

**Comment by mathias22osterhagen22** [comment]
Today it appends to me with Axios?

![image](https://user-images.githubusercontent.com/60438474/97454364-f8ead500-1936-11eb-9211-4a650e991c3e.png)
