### ISSUE TITLE
Incorrect Typescript syntax highlighting when using `instanceof`, followed by `||`, in `if` statement

### ISSUE THREAD

**Issue by mgthomas99** [Microsoft/vscode#49031]
- VSCode Version: 1.22.2
- OS Version: Windows 10 Pro 64-bit (10.0, Build 14393)

Steps to Reproduce:

1. In a Typescript file, write an `if` statement that contains an `instanceof` expression, followed by either a logical-or or logical-and operator, and then another expression.

Here is a screenshot of how the syntax highlighting looks:
![How the syntax highlighting looks](https://i.imgur.com/tDdgu2V.png)

Here is how it *should* look:
![How the syntax highlighting *should* look](https://i.imgur.com/MdwyAqd.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the text from those screenshots

**Comment by mgthomas99** [comment]
Here is the exact code file that is causing a problem. Line 15 (first line within the constructor) is the exact line.

```typescript
import hexrgb from "hex-rgb";
import rgbhex from "rgb-hex";
import inRange from "in-range";
import isHex from "is-hex";

export class ColourTransferKey {

  public red: number;
  public green: number;
  public blue: number;

  private _x: number;

  public constructor(x?: number, value?: Uint8Array | number[] | string) {
    if (value instanceof Uint8Array || Array.isArray(value)) {
      this.red   = value[0] || 0;
      this.green = value[1] || 0;
      this.blue  = value[2] || 0;
    } else {
      this.hex = value || "FFFFFF";
    }
    this.x = x || 0;
  }

  public get hex(): string {
    return "#" + rgbhex(this.red, this.green, this.blue);
  }

  public set hex(x: string) {
    if (x.startsWith("#")) x = x.substring(1);
    if (! isHex(x)) throw new Error("Expected hex string");

    const rgb = hexrgb(x);
    this.red = rgb.red;
    this.green = rgb.green;
    this.blue = rgb.blue;
  }

  public get x(): number {
    return this._x;
  }

  public set x(x: number) {
    if (! inRange(x, 0, 1)) {
      throw new Error("`x` must be in range [0, 1]");
    }
    this._x = x;
  }

}

```

**Comment by wangweixuan** [comment]
They were fixed in https://github.com/Microsoft/TypeScript-TmLanguage/commit/c4d834c232aacd99890b28d64c6ba3deda1bfd58
and merged in https://github.com/Microsoft/vscode/commit/d0bc1c3fe4c3790ae72f4692e4cdbcff469e5f80#diff-833eb8d6808e9f783ae62832e68bce3aR2212

**Comment by mjbvz** [comment]
Thanks. Yes looks fixes in insiders builds
