### ISSUE TITLE
Intellisense for dart not working

### ISSUE THREAD

**Issue by ShoshanaTzi** [Microsoft/vscode#49045]
Issue Type: <b>Bug</b>

I use vs code with dart,
the Intellisense is not working, and also - go to definition (F12)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|15.89GB (5.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --open-url -- vscode:extension/Dart-Code.dart-code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.12.1
beautify|Hoo|1.3.0
csharpfixformat|Leo|0.0.69
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.3.0
vscode-icons|rob|7.23.0
format-all-files|xyk|0.2.0

</details>

**Comment by rebornix** [comment]
Please file issues against the Dart extension you are using.
