### ISSUE TITLE
[loc][Query][DevDiv] Please clarify placeholders "{0} {1}"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#4904]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Hi we have a query about the source text. Can you please clarify?

Source:
{0} {1}

File Name:
src\vs\workbench\browser\parts\editor\sideBySideEditorControl.nls.resx

Resource ID:
".resx", 0; "inputDecoration"

Query:
Can you please clarify what the placeholders will be replaced by? Thanks!

**Comment by bpasero** [comment]
0: editor input status indicator (e.g. dirty indicator)
1: editor input title

**Comment by mkyjakova** [comment]
Thanks!
