### ISSUE TITLE
Copied Block of code, pasted on HTML element wrong format pasted.

### ISSUE THREAD

**Issue by samael205** [Microsoft/vscode#49046]
- VSCode Version: 1.22.2
- OS Version: Windows 10

Steps to Reproduce:

1. Copy a block of code from Visual Studio Code
2. Paste in textbox of Google Group's box reply message or in an Google New Message box reply

Here is a screen that shows what append:
[Cutted Styles Pasted code](https://imgur.com/a/LTHn6UG)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
Let's track this in https://github.com/Microsoft/vscode/issues/31829 . This is because that we use non-break-spaces in html but they are not being rendered as expected in some applications, we probably want to think about what we want to use there.
