### ISSUE TITLE
(Debug F5) no working when extend  vscode plugin

### ISSUE THREAD

**Issue by zhaoyangsoft** [Microsoft/vscode#49040]
- VSCode Version:
version:  1.22.2 

- OS Version:
OS Version: 10.13.4 (17E199)
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

Steps to Reproduce:
extend  vscode plugin 
https://code.visualstudio.com/docs/extensions/example-hello-world
1.  yo code
2. code . 
3. click Debug(F5)
4. only show [Extention] on the StatusBar
![image](https://user-images.githubusercontent.com/1456421/39516918-e9d56bc6-4e30-11e8-8280-cc080d679f53.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by isidorn** [comment]
This works fine for me.
Please try with latest vscode insiders https://code.visualstudio.com/insiders/
