### ISSUE TITLE
[FEATURE REQUEST] Allow search in all codepages

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/vscode#49043]
We frenquently have to use alternative encoding 850 or 437 to edit legacy code. Unfortunately no way around this for now.
 It would be cool to be able to search in workspaces with these encodings.

![2018-05-02 11_51_13-remote desktop manager azugtpeapp01](https://user-images.githubusercontent.com/25029667/39518689-3827c616-4e04-11e8-904e-4aaaa56f0a62.png)

**Comment by roblourens** [comment]
It should work if you set `"search.useRipgrep": false`, but that won't work forever...

Otherwise it's unlikely that ripgrep will add support for legacy encodings.

**Comment by Raydir** [comment]
I just stepped over this issue because the same would be necessary for me... 
@roblourens  does that means there is no real solution for this?
