### ISSUE TITLE
Cannot GET /test.html

### ISSUE THREAD

**Issue by DIPSHUBHAM** [Microsoft/vscode#49049]
`Issue` Type: <b>Bug</b>

it is unable to open the html files with live server extension or without live server extension. some times it's open the file and some times says cannot get/file name .

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
   
    <link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js"></script>
    <title>Document</title>
</head>
<body>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="styleimg.css">
    <link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js"></script>  
</body>
</html>

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU 1005M @ 1.90GHz (2 x 1896)|
|Memory (System)|5.89GB (3.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe F:\Web\college\COMPLETE PAGES\styleimg.css|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.1
LiveServer|rit|3.2.1

</details>

**Comment by isidorn** [comment]
Please file this issue with reproducable steps. On how to file issues please follow these suggestions
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
