### ISSUE TITLE
Column-Select is biased to the right - this is inconsistent with traditional shift-select behaviour

### ISSUE THREAD

**Issue by stephenmartindale** [Microsoft/vscode#4905]
- VSCode Version: 0.10.13-insider
- OS Version: Windows 10

I am properly enjoying the new _insider_ release - it offers so much! - and it is with great regret that I must file this first bug...

Steps to Reproduce:

1. Create a block of text such as this one:

```
var gulp = require('gulp');
var path = require('path');
var rimraf = require('rimraf');
var isarray = require('isarray');
var merge = require('merge-stream');
var concat = require('gulp-concat');
var newer = require('gulp-newer');
```

2. Place the caret on the first line, on the left of the `var` keyword.
3. Hold `alt + shift` and left-click on the right hand side of the `var` keyword on the last line to make a column selection.
4. Observe that if the mouse was even a few pixels overlapped with the `space` character, the column of spaces will also be included in the selection - the selection is biased towards the right.
5. Now repeat step two and make a single-line selection by holding shift and clicking on the right hand side of the `var` keyword on the _first_ line - observe that the selection is biased to the left - i.e. you have to be almost completely past the `space` character or else it is _excluded_ from the selection.

Clearly, column-select's behaviour is non-traditional in this regard.

Personally, I prefer to "draw" my column selections like you can in full-fat Visual Studio when you hold down `alt`. This shift-select style is fine but it should at least be consistent with U.I. norms.

**Comment by alexandrudima** [comment]
@stephenmartindale Great catch! There is somewhere a +1 bug in the column selection code (evident by the fact that I can't use column select to the beginning of a line):

fyi @egamma 

![column-select-plus-one](https://cloud.githubusercontent.com/assets/5047891/14245817/079b9662-fa64-11e5-9a1d-7772aae927b2.gif)

**Comment by stephenmartindale** [comment]
Nice GIF. I wanted to post something like that but, while dev. tools are something I know well, screencasting and recording are things of which I ken naught. Can you recommend a tool for the making of such GIFs for future issue reports?

I see it's fixed for April, too. THIS is why I like VS Code - stuff actually happens! We had to wait ten years for "collapse all" in Solution Explorer!

**Comment by alexandrudima** [comment]
@stephenmartindale I'm on Windows and really like http://recordit.co/ 

This is now fixed on master and is also backported to the 1.0 release branch, so next insiders build should get the fix.

**Comment by OlsonDev** [comment]
@stephenmartindale Recordit is great for its simplicity but it's capped at really low FPS (I think 10fps). For most bug reports, that's fine. However, I prefer recording clips with [OBS](https://obsproject.com/) and then either just using the `.mp4` directly (60+fps) or finding an online service to convert to `.gif` (usually capped to 30fps).

**Comment by csholmq** [comment]
http://www.cockos.com/licecap/ is multi platform and is very straight forward. On my laptop I recorded in 20 fps which seems to be the limit in my case.
