### ISSUE TITLE
Log point code execution always expects string return (should support arrays and objects)

### ISSUE THREAD

**Issue by proreact-mj** [Microsoft/vscode#49053]
- VSCode Version: 1.22.2
- OS Version: Win10

Steps to Reproduce:

1. Define someObj as an object or array
2. Set log point like "Some message {console.log(someObj)}"
3. Run

Does this issue occur when all extensions are disabled?: Yes

Background
logs undefined as console.log does not return a string (%s)
![image](https://user-images.githubusercontent.com/13857623/39525548-8a7a5970-4e1c-11e8-874a-f05175737c4a.png)

resulting VM1370
console.log('Some message %s', (console.log(goals)))

Having object as expandable elements in the debug console is incredibly powerful and it work. 
The undefined is just messing with the eye. 
Omitting the console.log wrapper just returns the type definition of someObj

This is completely livable, as it does work, but maybe consider native support for printing objects/arrays to the debug console with log point without the console.log wrapper as this is really useful.

**Comment by isidorn** [comment]
I think this is fixed in latest vscode insiders and should work in the next vscode stable release.
Forwarding to @roblourens to confirm

**Comment by isidorn** [comment]
Actually I just verified this works in latest insiders. Closing
Next stable should be out in the next couple of days so you can try it out.

Also no need to write conosle.log inside lop statements, `{goals}` is enough in your use case

**Comment by proreact-mj** [comment]
Awesome. 
Thanks for the quick reply. 

right now {goals} just outputs "object" or "array [#]" respectivtly, but I look forward to the new version. Thanks.

**Comment by proreact-mj** [comment]
Confirmed working in 1.23
