### ISSUE TITLE
Unclear what is editorIndentGuide.activeBackground

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#49055]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.23.0-insider (b8475d1dc68bfee70c3fbe3e7fc39f6e0003803b, 2018-05-01T00:21:32.926Z)
OS version: Windows_NT x64 10.0.16299

I want to disable the editorIndentGuide highlighting.

In the release notes

>VS Code can now highlight the active indent guide, as you move your cursor between various source code blocks. The color name is `editorIndentGuide.activeBackground`:

![image](https://user-images.githubusercontent.com/5593825/39527103-e983594a-4e20-11e8-91c1-c2b69cd8c6be.png)

![image](https://user-images.githubusercontent.com/5593825/39527116-f5038858-4e20-11e8-81a9-705d849d7f09.png)

**Comment by alexandrudima** [comment]
This is a color name. It can be used in a theme or in the setting `workbench.colorCustomizations`. e.g.:

```js
	"workbench.colorCustomizations": {
		"editorIndentGuide.activeBackground": "#9e9e9e"
	}
```
