### ISSUE TITLE
How to debug Typescript Angular 2 browser side code on Windows?

### ISSUE THREAD

**Issue by faustomura** [Microsoft/vscode#4906]
- VSCode Version:0.10.11
- OS Version:Windows 8.1

I can't debug browser side typescript code of Angular 2 "Tour Of Heroes" sample code ( http://plnkr.co/edit/?p=preview )
The only way to debug browser side code is use the "Debugger for chrome" extensions? 
Are a alternative way to debug browser side typescript code? Alternative in Internet Explorer/Firefox?

If i try to add a breakpoint with Debugger for chrome extensions i se in the log console this error "can't be resolved to a loaded script.".

I already start chrome whit --remote-debugging-port=9222
My launch copnfiguration is :+1: 
`		{
			"name": "Chrome Attach",
			"type": "chrome",
			"request": "attach",
			"port": 9222,
			//"url": "http://localhost:9085/_template/dev/www/dashboard",
			"url": "http://localhost:9085/_template/dev/www/dashboard",
			//"webRoot": "${workspaceRoot}",
			"webRoot": "${workspaceRoot}",
			"diagnosticLogging": true,
			"outDir": "${workspaceRoot)",
			"cwd":"${workspaceRoot}",
			"sourceMaps": true
		},
`

**Comment by egamma** [comment]
>The only way to debug browser side code is use the "Debugger for chrome" extensions? 

If you want to debug inside VS Code then this is the way to do it.

If there are issues please file them against the extension https://github.com/microsoft/vscode-chrome-debug/issues
