### ISSUE TITLE
SCM window show folder name even if a name is specified in workspace

### ISSUE THREAD

**Issue by lapo-luchini** [Microsoft/vscode#49067]
- VSCode Version: 1.22.2
- OS Version: Windows 10

Steps to Reproduce:

1. have a workspace with many SVN projects
2. most show up in the UI as "trunk" (being the last directory in their path on SVN and, thus, in a multi-project checkout)
3. define a "name" in the workspace file for each of them in order to see the correct name
4. switch to the SVM view (ctrl-shift-G)
5. most project are shown as "trunk" again

Does this issue occur when all extensions are disabled?: No
(because SVN is an extension and this doesn't apply)

Reference screenshots and full configuration infos in JohnstonCode/svn-scm#250

**Comment by lapo-luchini** [comment]
(tangential to this issue, but it would be nice to somehow support custom naming of projects, or extraction from `.../real-name/trunk` path, or something to support SVN-style branching in other cases that a named workspace)

**Comment by rebornix** [comment]
Please file issue against the extension you are using, thanks!

**Comment by lapo-luchini** [comment]
I did originally, they say that string comes from VSCode, not from the extension…

**Comment by lapo-luchini** [comment]
The "trunk" text seems to be calculated from code outside the extension, in [line 157](https://github.com/Microsoft/vscode/blob/d7bd90445a26dacc2d73b2a81393cf5559271594/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L157) of `scmViewlet.ts`, by using `basename`:
```typescript
if (repository.provider.rootUri) {
    templateData.title.textContent = basename(repository.provider.rootUri.fsPath);
    templateData.type.textContent = repository.provider.label;
}
```
I was trying to make a patch myself, but so far I can't find the "project" object that repository object descends from.
