### ISSUE TITLE
TypeScript refactorprovider provider uses activeTextEditor's selection

### ISSUE THREAD

**Issue by srivatsn** [Microsoft/vscode#49060]
The refactor provider for TypeScript uses the activeTextEditor's selection(https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/refactorProvider.ts#L131) to get the range instead of using the range that's passed in. This is problematic if the provider is invoked via an API. For eg, in a LiveShare guest session if the guest makes a selection, we would only get refactorings for the host's selection.

/cc @jrieken @kieferrm

**Comment by mjbvz** [comment]
Verified with code check that normal case no longer uses `activeTextEditor`. Opened #50856 to also allow us to move the rename operation itself away from using `activeTextEditor`
