### ISSUE TITLE
Folder icon for Seti icon theme

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#49065]
- VSCode Version: 1.22.2
- OS Version: macOS

My suggestion is to add folder icons for Seti icon theme and it will be completely done because currently, I need to download another icon extension even if the default one can be used, but the problem is, it doesn't contain folder icon.

**Comment by rebornix** [comment]
If you are using Seti icon extension, please file issue against them, thanks ! 

Link https://github.com/hellopao/vscode-seti-icons

**Comment by svipben** [comment]
@rebornix Seems it's out-dated, the last commit was 2 years ago, seems you need to change Seti to someone else...
