### ISSUE TITLE
SVG previews in vscode

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#49064]
VSCode currently shows previews for images and markdown files. Its a super useful feature.

Having previews for svg would be super helpful too, especially since a lot of icons and designs are made in svg. 

In fact, VSCode should expose a preview api where we can build a preview for any extension we'd like. e.g graphviz dot graphs

**Comment by tommai78101** [comment]
Does that also mean the Previews will play GIF and APNG files? Or that's already supported?

**Comment by mjbvz** [comment]
Check out: https://marketplace.visualstudio.com/items?itemName=cssho.vscode-svgviewer

**Comment by mjbvz** [comment]
SVG is not a simple format. It is closer to html than pngs, and in VS Code core we do not want to deal with the complexity of properly and securely displaying svgs in the editor.

Given this, and given that a good extension already exists for displaying svgs, we likely would not take a PR that adds this functionality
