### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by ericrousse** [Microsoft/vscode#49061]
Issue Type: <b>Bug</b>

Just a daily usage of the app. Had the same behavior yesterday. Was simply working with playbook. At the beginning of the day it was around 230mb, now reaching 1.5gb and slow response time from time to time.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2693)|
|Memory (System)|7.91GB (0.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
armsnippet|art|0.7.0
git-easy|bib|1.9.1
azuretoolsforvscode|bra|2.0.2
vscode-standard-format|che|0.0.12
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.15.0
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
gitlens|eam|8.2.4
vscode-npm-script|eg2|0.3.4
vsc-material-theme|Equ|2.0.1
ansible|haa|0.2.8
live-html-previewer|hdg|0.3.0
rest-client|hum|0.18.3
search-node-modules|jas|1.3.0
format-php|Kas|1.1.2
rainbow-csv|mec|0.2.1
prettify-json|moh|0.0.3
vscode-azureappservice|ms-|0.7.1
vscode-azurefunctions|ms-|0.8.1
vscode-azurestorage|ms-|0.3.0
vscode-azureterraform|ms-|0.1.1
vscode-cosmosdb|ms-|0.6.0
vscode-devskim|MS-|0.2.2
vscode-kubernetes-tools|ms-|0.1.8
mssql|ms-|1.3.1
vscode-ai|ms-|0.1.7
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
PowerShell|ms-|1.7.0
vscode-azureextensionpack|ms-|0.0.9
team|ms-|1.133.0
azurerm-vscode-tools|msa|0.4.0
azure-hdinsight|msh|0.0.16
require-sort|Per|0.0.1
vscode-docker|Pet|0.0.26
material-icon-theme|PKi|3.3.0
diff|raf|0.0.1
vscode-yaml|red|0.0.11
bash-beautify|sha|0.1.1
git-autoconfig|shy|0.0.1
usql-vscode-ext|usq|0.2.13
application-insights|Vis|0.4.2
azure-iot-edge|vsc|0.3.0
azure-iot-toolkit|vsc|0.6.1
vscode-ansible|vsc|0.1.5
gitblame|wad|2.4.2
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by tresdev** [comment]
Same here. just one folder with some node modules on one window takes up more than 500mb. I can't even work with more than three windows. I'm using Windows 10. I even tried turning off ALL extensions, which actually brought almost no change at all.

**Comment by rebornix** [comment]
Pls have a look at https://github.com/Microsoft/vscode/wiki/Performance-Issues. This helps us tracking down the problem.

**Comment by ericrousse** [comment]
Trying to follow the documentation, but I can't find Developer: Open Process Explorer. I have many more options under Developer:, but not the Process Explorer.

Tried vscode.exe --status, but it doesn't really mention which process is which extension.

But that URL should be proposed in the Issue Reporter window.  I'll try to play around and disable some extensions. Thanks!

**Comment by ericrousse** [comment]
This morning I did the upgrade to 1.23.0, seems to be better not sure if its related. But so far so good. No extensions hasn't been updated.
