### ISSUE TITLE
Linter error flag is showing up while changing language mode to CSS and then back to original.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4907]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1. launch app and open any HTML file. 
2. Verify file type displayed correctly in the task bar.
3. Click on file extension from task bar and change it to CSS.
4. Verify proper error and warning flag should be raised on editor.
5. Now click on auto detect and verify it should change to HTML and all the errors should go away.

Actual: Editor detected html file but error flag for CSS remain as it is.
Expected: once auto detect covert from CSS to HTML then editor should identify appropriate linter.
![image](https://cloud.githubusercontent.com/assets/17735796/14242993/c95cbab8-fa07-11e5-8c64-2ec9effa934c.png)

**Comment by MitchellSternke** [comment]
I've been noticing this issue too whenever I switch languages on any file that has error markers (regardless of filetype, it doesn't necessarily have to be HTML). I've also seen it happen when using extensions that have language services that implement error reporters, including [OmniSharp](https://github.com/OmniSharp/omnisharp-vscode) and [mssql](https://github.com/microsoft/vscode-mssql). So it would appear that this is a language-independent issue. 

Perhaps error markers should disappear/be cleared when the language mode is changed for a file?

**Comment by alexandrudima** [comment]
Perhaps this is no longer an issue (since we moved HTML and CSS out to extensions)

**Comment by aeschli** [comment]
I can't reproduce this anymore.
