### ISSUE TITLE
Allow to reload an opened file with the contents on disk

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/vscode#49075]
This is a feature request.

VS Code already has a built in feature that would "reload" the editor after a new installation of an extension.

I would like to request for that "reload" feature be exposed, so it is in the Toolbar Menu Option. It will be accessed via `File` > `Reload`, or `File` > `Reload Editor`. Whatever it can be called.

The thing is, VS Code doesn't prompt you if an opened document has been modified outside of VS Code. So, if an extension is freezing because it's parsing an out-of-sync document, I would like for VS Code to allow the user to "reload" the editor, so all of the documents are surely in-sync, and for the extension to continue working.

This feature request is an extension to #30702, where that issue wanted VS Code to stop reloading. In my request, amending #30702, we can expose the option to "reload" VS Code, so some people may prefer doing it manually, some people prefer the current behavior, and some people can disable it via editor configurations.

**Comment by bpasero** [comment]
`File > Revert File` will do this even if the file is not dirty.

**Comment by tommai78101** [comment]
Thanks.
