### ISSUE TITLE
Debug Breakpoints not working in Windows 10

### ISSUE THREAD

**Issue by rohithjidagam** [Microsoft/vscode#49074]
The debugging of single test works fine on Mac Machines with Node version >=8. But, on the windows machine, the debug doesn't work properly, which means, placing a breakpoint and debug the test, the debugger doesn't stop at breakpoint, it inturns run the test making the breakpoint turned to grey and saying that "unverified breakpoint, breakpoint ignored because generated code not found (source map problem?)."

In Windows machines, the trace log is below:

SourceMaps: expanded globs and found 63709 scripts
SourceMaps: could not preload for generated script: c:\<project-path>\node_modules\@ms\odsp-utilities\dist\esm\odsp-utilities\logging\odb\IBeaconHandlers.js. Error: Error: EMFILE: too many open files, open 'c:<project-path>\node_modules\@ms\odsp-utilities\dist\esm\odsp-utilities\logging\odb\IBeaconHandlers.js'.

I am trying with below versions:
"@types/jest": "^22.2.3",
"jest": "^22.4.3",
"ts-jest": "^22.4.4",
"babel-jest": "^22.4.3",
node: 8.9.4

**Comment by isidorn** [comment]
Please read this to configure source maps propeperly https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-maps

**Comment by rohithjidagam** [comment]
I followed that and this is my config:

{
      "type": "node",
      "request": "launch",
      "name": "Debug Tests In Current File",
      "sourceMaps": true,
      "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
      "cwd": "${workspaceFolder}",
      "args": ["--i", "--config", "jest.config.json", "${relativeFile}"],
      "outFiles": ["${workspaceFolder}/**/*.js"]
    }

**Comment by roblourens** [comment]
> SourceMaps: expanded globs and found 63709 scripts
> Error: Error: EMFILE: too many open files, open 'c:\node_modules@ms\odsp-utilities\dist\esm\odsp-utilities\logging\odb\IBeaconHandlers.js'.

It looks like your outFiles pattern matches tons of files. Is there any way you can make it more precise? I will have to change the debug adapter to not open so many files at once.

**Comment by roblourens** [comment]
Actually, it's not likely that I'll work around this in the debug adapter. It will also launch a lot faster if you narrow down the outFiles pattern, so that's definitely the best fix.

**Comment by rohithjidagam** [comment]
@roblourens  : Thanks for getting back. But, I think jest will generate the .js files in its memory. How do we know the path, where the .js files are being generated? Please correct me if my understanding is wrong.

**Comment by roblourens** [comment]
Yeah, in that case, outFiles is not useful, and you can remove it.

**Comment by rohithjidagam** [comment]
I tried that, same problem. Between, how do we make debugger stop at breakpoint? I am using node 8.9.4, Windows 10, vscode 1.21.1. I tried with ts-jest 21.2.3 and 22.4.4 (latest)
Same configs on mac works perfectly fine.

**Comment by roblourens** [comment]
Can you run the `.scripts` command in the console to see if it's resolving your sourcemaps correctly?

**Comment by rohithjidagam** [comment]
I ran the .scripts and checked the log, the symlinks are generated only for files in the node_modules folder and not for files in the workspaces.

**Comment by roblourens** [comment]
Can you paste some of the output here?

**Comment by rohithjidagam** [comment]
› assert.js
› async_hooks.js
› bootstrap_node.js
› buffer.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\@babel\code-frame\lib\index.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\@babel\highlight\lib\index.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\abab\index.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\abab\lib\atob.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\abab\lib\btoa.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\ansi-styles\index.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\arr-flatten\index.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\asn1\lib\ber\errors.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\asn1\lib\ber\index.js
› c:\Users\rojidaga\Desktop\teams-code-space\teams-modular-packages\node_modules\asn1\lib\ber\reader.js

**Comment by roblourens** [comment]
Can you paste the portion that has the files you want to set breakpoints in? That's the point of looking at that command's output.

**Comment by rohithjidagam** [comment]
I don't see those files in the output. I only see that symlinks are being generated for files in the node_modules folder and not for files in the workspaces folder.

**Comment by roblourens** [comment]
If the files don't show up there, then they are not loaded. Double check that the files you expect are actually running.

**Comment by rohithjidagam** [comment]
The files are not being showed up there. That is the problem we are facing. I tried to setup the config in 2 sample projects(with jest and without jest). The symlinks are generated correctly in project without jest but with jest, I get this same issue. Can you please share some jest configuration?

**Comment by roblourens** [comment]
Have you seen this example? https://github.com/Microsoft/vscode-recipes/tree/master/debugging-jest-tests
