### ISSUE TITLE
Find All references is slow and gives no indication that processing is happening

### ISSUE THREAD

**Issue by bdharrington7** [Microsoft/vscode#49079]
Issue Type: <b>Bug</b>

I'm working on a relatively small express nodejs application server, and whenever I change a method signature, it takes about 5-10 seconds to find usages of that method again. This is fine (it could be faster, but this is not what the issue is about), but the window that pops up gives no indication that something is happening. Sometimes I see the "loading" title in the popover window flash, but it disappears very quickly, displaying a blank window. 

Steps to reproduce: 
Use some small-to medium size project, and change the method signature of a method used in other modules. Save the file, and then use Find all references on that method. 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-docker|Pet|0.0.26
vscode-css-formatter|aes|1.0.1
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
gitlens|eam|8.2.4
useful-react-snippets|igo|1.4.4
vscode-language-babel|mgm|0.0.14
debugger-for-chrome|msj|4.3.0
color-highlight|nau|2.3.0

</details>

**Comment by jrieken** [comment]
> Sometimes I see the "loading" title in the popover window flash, but it disappears very quickly, displaying a blank window.

That is unexpected, the 'Loading...' title should show until there is data to render. How large is the data set you are seeing? Is just a few results or many, many? Can you attach a screen recording and readings from the console?
