### ISSUE TITLE
Webview can overlap and block interactions underneath

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#49086]
- VSCode Version: 1.23
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open a webview (might need a fixed internal width) and size the window small enough

![image](https://user-images.githubusercontent.com/641685/39552677-3715d40a-4e38-11e8-883e-89feaba8f689.png)

As you can see in this image that webview is somehow on top of the explorer views, and it blocks clicking on anything underneath them.

Does this issue occur when all extensions are disabled?: No

//cc @mjbvz

**Comment by mjbvz** [comment]
Do you have reliable repo steps? I've not been able to repo this problem

**Comment by eamodio** [comment]
I can still reproduce this. You do need to have the sidebar positioned on the right side though.

1. Open GitLens settings (or welcome)
2. Size the vscode window so that it is very narrow
3. Notice that the webview will overlap the sidebar (you won't get hovers or be able to click on the left side of the items in the tree views (Explorer file view is easy to see)

**Comment by mjbvz** [comment]
Sorry but I've never been able to reproduce this. Are you still seeing it in recent VS code versions?

**Comment by eamodio** [comment]
@mjbvz It looks fixed now to me
