### ISSUE TITLE
Show JSHint errors/warnings on a file and folder levels

### ISSUE THREAD

**Issue by stanislavgeorgiev** [Microsoft/vscode#49083]
Hi,

I'm using VSCode for my JavaScript development and I also have JSHint configured. VSCode shows the errors/warnings when I open a file but it would be really useful if there was an indication within the File Explorer when a file has errors/warnings in it, an exclamation mark icon overlay for example. It would be even nicer if that overlay propagates to the parent folder and so on to the root folder (similar to how the it would show changed files). I think this error/warning overlay can help not only JS development but other languages as well.

Cheers,
Stan.

**Comment by RMacfarlane** [comment]
@stanislavgeorgiev Thanks for the suggestion! What version of VS Code are you using? There's a feature that was added in 1.20 that should do this: https://code.visualstudio.com/updates/v1_20#_error-indicators-in-the-explorer

**Comment by stanislavgeorgiev** [comment]
Thanks for pointing that out @RMacfarlane. I'm using 1.22 and I guess I thought that the green highlighting is showing the changed files! Nevermind then and thanks for the help :+1: :)
