### ISSUE TITLE
Explorer window in Zen Mode can be open, but can not be closed

### ISSUE THREAD

**Issue by ggarek** [Microsoft/vscode#49089]
- VSCode Version: 1.22.2 (1.22.2)
- Mac OS Version: 10.13.4 (17E199)

Steps to Reproduce:

1. Enter `Zen Mode`
2. Open `Explorer` window with hotkey
3. Press same hotkey (expect `Explorer` window to close)
4. `Explorer` window stays open

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this.
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
If yes what hotkey are you using?

**Comment by ggarek** [comment]
Thanks, @isidorn, i did not know about insiders edition 😍 

Just tried it
```
Version 1.24.0-insider (1.24.0-insider)
2404210629c744e6237a14d7b5fa852e24c6e898
2018-05-04T07:59:51.629Z
```

The behaviour is same.

Here is the flow once again:

1. [act] Open VSCode
2. [act] Enter Zen Mode 🌶 🔑 **(CMD+K Z)**
3. [observe] The Explorer window is not visible
4. [act] Open Explorer window 🌶 🔑 **(CMD+SHIFT+E)**
5. [observe] The Explorer window is visible
6. [act] Try to hide Explorer window 🌶 🔑 **(CMD+SHIFT+E)**
7. [observe] The Explorer window is still visible _(nothing happened)_

I have checked `Keyboard Shortcuts` for Explorer related keys.
There is `Show Explorer` command, which i was using. But there is no opposite command, e.g. `Hide Explorer`.

So, my assumption is, that `Show Explorer` is _(or should be)_ in fact `Toggle Explorer`. In other words, i expect Explorer window to open and close using same hot key.

I see two possible cause:
1. VSCode is missing `Hide Explorer` command (or i did not find it, in this case its name does not contain word `explorer`, which is strange)
2. The present command `Show Explorer` is in fact `Toggle Explorer` and has a bug

Imo, `toggle` behaviour is more obvious and easy to follow. 

p.s.: upon entering Zen Mode, Explorer window always disappears. (expected)

**Comment by isidorn** [comment]
CMD + SHIFT + E does not toggle the explorer, thus it does not hide it.
To hide the sidebar use the CMD + B which acts as a toggle.
You can customize all these keybindings if you do not like the default behavior.
