### ISSUE TITLE
Git keeps calling 'git status'

### ISSUE THREAD

**Issue by transtone** [Microsoft/vscode#49090]
same as https://github.com/Microsoft/vscode/issues/43234
and https://github.com/Microsoft/vscode/issues/43408

- VSCode Version: 1.23.1
- OS Version: macos-10.13.4
- git version: 2.17.0

update git to latest  not solve the bug.
can I hide git loading badge?

**Comment by joaomoreno** [comment]
Can you run `Git: Show Git Output` and show me the log?

**Comment by transtone** [comment]
```
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse develop
> git rev-parse --symbolic-full-name develop@{u}
> git rev-list --left-right develop...refs/remotes/origin/develop
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
```

![kapture 2018-05-03 at 16 49 45](https://user-images.githubusercontent.com/46688/39567634-3ec04dd8-4ef2-11e8-8594-01b49e8b8ed7.gif)

**Comment by joaomoreno** [comment]
@transtone Can you show me the full Git Output since the startup of VS Code? Is this still happening?
