### ISSUE TITLE
[css][folding] custom css region folding Word

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#49092]
Using 1.23, CSS region folding can only be found

* / * #region header* /

* / * #endregion * /

Can we add custom words to user settings?

/ * #css header*/

* / * #endcss * /

**Comment by aeschli** [comment]
@lihua06 How common is the use of these markers? We should only add it to the default markers if they are commonly used. Otherwise, the request would rather by a dup of #36002
