### ISSUE TITLE
i18n: wrong german translation for "Warning" label

### ISSUE THREAD

**Issue by bgse** [Microsoft/vscode#4909]
- VSCode Version: 0.10.13-insiders

Steps to Reproduce:

1. trigger a warning dialog, e.g. start up vscode with git <2.0.0 installed

![vscode_warn](https://cloud.githubusercontent.com/assets/8385202/14247298/864b6aba-fa6d-11e5-82a8-2415c1bbc02e.png)

"Warning" gets translated to "Warnen" (verb) in german version, but it should be "Warnung" (noun) in this case.

**Comment by bgse** [comment]
PR for your convenience:

https://github.com/Microsoft/vscode/pull/4919

**Comment by dbaeumer** [comment]
@bgse Unfortunately we can't accept PRs on translations since the i18n files are machine generated. I will assign this issue to the translation team and will close the PR.

**Comment by johnliu2016** [comment]
Ported to loc team

**Comment by johnliu2016** [comment]
ported to loc team

**Comment by johnliu2016** [comment]
@bgse Corrected the German string to "Warnung" in loc files, should be in next build update.
