### ISSUE TITLE
Support Windows 10 Timeline feature

### ISSUE THREAD

**Issue by Vijay-Nirmal** [microsoft/vscode#49096]
In Windows 10 April 2018 Update, Microsoft releases a new feature called [Timeline](https://www.youtube.com/watch?v=nNdirfTlU4E). This is a very helpful feature for restoring the work. Please add support for this feature

**Comment by digitalbanana** [comment]
this would be awesome 👍

**Comment by UDXS** [comment]
+1

**Comment by richeney** [comment]
+1

**Comment by david-genger** [comment]
This would be amazing! also, Microsoft do it for yourself 😉

**Comment by UDXS** [comment]
It could be an extension but I feel like Microsoft should be supporting their own features.

**Comment by david-genger** [comment]
But they are not, it is taking to long for things to be implemented.
I was wondering why they did not implement the chrome extension on their own?

And we developers are faster than the corporate hell out there.

**Comment by Gustash** [comment]
+1

**Comment by benyaminl** [comment]
Does this already implemented yet?

**Comment by Chaphasilor** [comment]
@sbatten any *timeline* for this feature? \^\^
