### ISSUE TITLE
VCS label not uniform with workspace setting

### ISSUE THREAD

**Issue by tdchien** [Microsoft/vscode#49095]
Issue Type: <b>Feature Request</b>

When customize folder display on workspace I noticed git label seen display not uniform. Please check this bellow image for more detail

![image](https://user-images.githubusercontent.com/1614393/39567437-3c1463de-4ee9-11e8-961f-2994dcac6e69.png)

![image](https://user-images.githubusercontent.com/1614393/39563593-0909db9e-4edb-11e8-8200-84ae1aeb4c0f.png)

![image](https://user-images.githubusercontent.com/1614393/39563578-fa74b662-4eda-11e8-960a-296bcf5fa5f0.png)

Thanks

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

**Comment by joaomoreno** [comment]
Repositories don't always match folders. A single folder can easily have more than one repository within. It can even have none. The names you provide in that config file are intended for **folders**, not **repositories**.
