### ISSUE TITLE
Resizable "Opened Editors"

### ISSUE THREAD

**Issue by h2u** [Microsoft/vscode#491]
Please, add ability to resize (vertically) "working files" area.

**Comment by martellaj** [comment]
@bpasero Are you working on this issue meow?

**Comment by bpasero** [comment]
No, we just decided to give issues an owner.

**Comment by martellaj** [comment]
I started to look at this one (because it's something I really wanted), but found there is a setting (`"explorer.workingFiles.maxVisible": 50`) that handles it perfectly. Personally, I don't think this feature should be implemented.

**Comment by OlsonDev** [comment]
I'd either like it to be resizable with the mouse or a corresponding `"explorer.workingFiles.minVisible"` get added. So, for example, I could set `"explorer.workingFiles.dynamicHeight"` to `true`, `minVisible` to `10`, `maxVisible` to `20`.

- From 0-10 files, I'd have buffer (empty space) between working files and the folder explorer
- From 11-20 files, it'd dynamically grow
- At 20+ files, I'd see a scrollbar

**Comment by martellaj** [comment]
I don't understand the need to have a `"explorer.workingFiles.minVisible"`. What advantage of having a buffer between working files and the folder explorer? That scenario essentially exists already (other than having the buffer, which like you said, is just adding empty, unusable space into the sidebar).

I **could** see why people want a resizable working files, but I think the current implementation satisfies the need. I'd almost bet that when @h2u created the issue that they didn't know about the `"explorer.workingFiles.maxVisible"` setting.

**Comment by OlsonDev** [comment]
> What advantage of having a buffer between working files and the folder explorer?

I see two advantages. It reduces clutter and thus cognitive load. It improves muscle memory: if I know file X isn't open but is roughly Y pixels down the list, I can open it faster. With the buffer, its location doesn't change (often). Sure, I could use `Ctrl+P` but I might also know my current ignore settings won't find it, or there are many similarly named files so I'll have to filter through stuff. If we had tabs, this wouldn't be an issue for me: there'd be less clutter and my project files wouldn't be constantly moving on me.

**Comment by acutexyz** [comment]
@bpasero is this going to be implemented any soon? Now the "Opened Editors" area takes about 20% of vertical space while the project tree beneath it takes the rest 80%. 
I intuitively tried to "click and drag to resize" but for some reason it doesn't work.

**Comment by bpasero** [comment]
@acutexyz the new owner of this feature is @isidorn

**Comment by isidorn** [comment]
@acutexyz not planned to be implemented soon (there is 'explorer.openEditors.visible' as a somewhat of a workaround in the meantime)

**Comment by mugi-luffy** [comment]
+1

**Comment by Shaun-Cox** [comment]
For me, when I close (minimize) the Folder Explorer and Gitlens Explorer, I'd just wish they floated to the *bottom* and let that naturally open up all the available room for the Open Editors explorer.  Right now, I just see a bunch of empty space below the last closed explorer and the bottom of my screen, and the Open Editors explorer is a tiny window over a small number of files and I'm forced to scroll a large list of open files through this small view.

**Comment by hbdevelop1** [comment]
This open editors area is a great idea.
I hope you guys take it a step further and make it easily resizable.
There was a suggestion that "explorer.openEditors.visible" was enough.
The trouble with this is that it applies to all projects and instances of vscode.
I always have more than one instance of vscode running with different number of files open in each.
It would just be great if I could adjust the size of this area and the Folder area as I wish, without having to always scroll one of them in instances of vscode.

**Comment by petval** [comment]
Yes I really miss this feature, having to scroll up and down all the time affects my focus needed elsewhere.

**Comment by isidorn** [comment]
Fixed by @ironyman in https://github.com/Microsoft/vscode/issues/491
