### ISSUE TITLE
vscode doesn't save the files 

### ISSUE THREAD

**Issue by alighali85** [Microsoft/vscode#49108]
vscode doesn't show the recent changes of files 👍 

* the case is when I change some code and save it I can still see the changes but git changes tree are empty.

* if I open the file with another IDE I cant see the recent changes I have did on vscode.
that's really annoying and I need every time to switch outside vscode depending on other ID to push my recent changes to Git hubs.

thanks

**Comment by joaomoreno** [comment]
Do the changes appear if you run `Git: Refresh`?

**Comment by alighali85** [comment]
yes I got them later after run Git:Refesh 
... is it possible because I have muti IDEs installed on my machine and work at same directory?
