### ISSUE TITLE
[loc][Query][DevDiv] Please clarify placeholders "{0} ({1})"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#4910]
- VSCode Version:
- OS Version:

Steps to Reproduce:
Hi, we have a query about the placeholders in source.

source:
{0} ({1})

File Name:
src\vs\base\browser\ui\actionbar\actionbar.nls.resx

Resource ID:
".resx", 0; "titleLabel"

Query:
Can you please clarify the placeholders? What will they be subtituted by? Thanks!
(vso tfs 557907)

**Comment by bpasero** [comment]
0: action label
1: action keybinding

**Comment by mkyjakova** [comment]
Thanks!
