### ISSUE TITLE
codeActionsOnSave removing json file

### ISSUE THREAD

**Issue by eddiemoore** [Microsoft/vscode#49104]
Issue Type: <b>Bug</b>

Using the new `organizeImports` will remove a json file that was actually used in the code. Using Typescript.
```js
import introspectionQueryResultData from './fragmentTypes.json'

// later
const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData,
})
```
After running the action on save it removes the import statement.

VS Code version: Code - Insiders 1.23.0-insider (a656d397e424173c86f32703e0c0293bd8084da0, 2018-05-03T00:02:37.895Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_2388551|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.18
graphql-for-vscode|kum|1.10.2
debugger-for-chrome|msj|4.3.0
vscode-icons|rob|7.23.0
language-stylus|sys|1.9.2
gitblame|wad|2.4.2
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.6.2
JavaScriptSnippets|xab|1.6.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23903
