### ISSUE TITLE
Support applying WorkspaceEdit/editBuilder changes sequentially (and/or document current behaviour)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#49114]
If you have a file like this:

```text
ORIG 1
ORIG 2
ORIG 3
```

And you run this code:

```ts
const changes = new vs.WorkspaceEdit();
// Insert some text on line 1
changes.replace(document.uri, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)), "LINE 1\n");
// Insert some text on line 2
changes.replace(document.uri, new vs.Range(new vs.Position(1, 0), new vs.Position(1, 0)), "LINE 2\n");
// Insert some text on line 3
changes.replace(document.uri, new vs.Range(new vs.Position(2, 0), new vs.Position(2, 0)), "LINE 3\n");
await vs.workspace.applyEdit(changes);
```

The final line inserted "LINE 3" ends up on line 5. This is (presumably) because VS Code is working out which locations to make the changes before applying any of them, then applying them all.

The Dart analysis server doesn't work this way; it provides a bunch of edits with the assumption that they'll be applied sequentially (so offsets are already adjusted for earlier changes in the list).

While it's fixable by using multiple WorkspaceEdits, you lose the "all or nothing" functionality provided by WorkspaceEdit and would have do manually roll changes back if one fails.

I think it'd be nice to support (both for WorkspaceEdit and editBuilder) allowing pre-adjusted offsets. If not, the docs should at least call out this behaviour so the it's clear to users that multiple edits inside a `WorkspaceEdit` will not have the same effect as multiple sequentially-applied `WorkspaceEdit`s.

**Comment by jrieken** [comment]
> The Dart analysis server doesn't work this way; it provides a bunch of edits with the assumption that they'll be applied sequentially (so offsets are already adjusted for earlier changes in the list).

Interesting. I'd say the likelihood of us changing how edits are applied is low, not to say very, very low. Yeah, you can fire sequential edits (which isn't proper), talk to your server-folks, or do the merge math inside your extension.

**Comment by DanTup** [comment]
@jrieken Understood (FWIW I was actually asking for an option, rather than changing the default). The chances of Dart language server changing are also kinda slim, since there are many IDEs using it as-is.

For now I'm firing sequential edits but I'll look at how hard it'd be to update the offsets - I do think it'd be nice if Code provided a helper for it though; I suspect having edits this way isn't unique to Dart so having it centralised would avoid many people re-implementing it.

Btw, can a note be added to the docs to at least mention this is how it works? Our implementation hsa been bad for a long time (though I think out of luck, none of the edits we got back had multiple edits until now).

**Comment by jrieken** [comment]
> I suspect having edits this way isn't unique to Dart so having it centralised would avoid many people re-implementing it.

TBH it's the first time I hear about such a request and it feels unnatural to me. I am not very keen on adding this because I don't want to confuse folks. Today, things are easy. You are in state `A`, apply `n` edits, end you end in state `B`.

**Comment by DanTup** [comment]
I think it's easy to argue both ways make sense. If you were implementing a simple editor and someone gave you a bunch of edits, it seems like more work to figure out all the changes up-front without applying them than just looping through them and applying them to the current state each time.

Anyway, I don't feel strongly about it; I think there are few people implementing things where this's make sense so probably it's the right call not to add the complexity. I do think you should call it out in the docs though; just to help people if they do end up with a server that works how Dart's does. It took a bit of faffing for me to understand what was going on (I had edits with the same offsets that were all inserting characters and they just came through backwards! though admittedly, the server was sending the edit in a pretty bad way there).

**Comment by DanTup** [comment]
@jrieken I tried to implement offset rewriting, but it turns out to not be possible. Let's say my changes say:

- Insert a B at offset 1
- Insert an A at offset 1

There's no offset I can give to Code that would insert an A at offset 1, because using offset 1 will instead insert the character at offset 2 because of the first edit. I could try re-ordering the edits; but I don't know if I could do that reliably (and also, if they overlap I'm stuck anyway).

I'm discussing the issue with the Dart server team but it does seem like having no support for atomic sequential edits is a limitation in Code. For now I'm going to just have to apply sequentially and hope they never fail; but that's far from ideal.

**Comment by jrieken** [comment]
> There's no offset I can give to Code that would insert an A at offset 1, because using offset 1 will instead insert the character at offset 2 because of the first edit.

How about merging the edits into 'Insert BA at offset 1'?
