### ISSUE TITLE
Output Panel: Smart Scroll

### ISSUE THREAD

**Issue by dwilliamson** [Microsoft/vscode#49110]
Issue Type: <b>Feature Request</b>

Previously requested in #36217 but closed to further conversation.
Accepted as an issue for the Debug Console in #10486 and fixed in 2a215cc.
I'm confused by #32632 which seems to contradict all this. I'm probably misreading.

Currently addressed using the "scroll lock" button in the Output panel. Relevant code here:

https://github.com/Microsoft/vscode/blob/39748bd8b87c08455a7821ab7a4034071d684815/src/vs/workbench/parts/output/electron-browser/outputServices.ts#L538-L544

As my builds are for very large projects I like to be able to stop the scrolling when I see something whiz by that's of interest. In Visual Studio I got used to simply clicking anywhere in the output window to place the cursor and have auto-scroll stop.

After inspection I no longer use the mouse but press Ctrl+End to jump to the end of the console and resume auto-scroll.

Aiming for the tiny scroll lock button to both stop and resume is really fiddly and no longer consistent with the Debug Console.

I would *love* to see support for this added.

Thanks for an amazing IDE!

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment]
@dwilliamson this feature request makes sense.
We accept PR's that fix this. You have already provided a code pointer.
If more users ask for this and no PR comes and I can look into it myself in a couple of milestones.
Thanks!

**Comment by dwilliamson** [comment]
I was hoping you'd say that :) I have a fix that seems to work well. Will test it for a few hours before looking at what it takes to get a PR through to you.
