### ISSUE TITLE
Use react，why css peek isn't working

### ISSUE THREAD

**Issue by davychan1985** [Microsoft/vscode#49118]
show "You can't find any definitions about..."

**Comment by mjbvz** [comment]
We don't provide built-in support for jumping to css from jsx code. Try looking in the marketplace for an extension that offers this

**Comment by pranaygp** [comment]
@davychan1985 look at CSS peek on the Marketplace. It currently doesn't support jsx out of the box, but people have reported it working (at least for id tags). I'd love to accept a PR for JSX support though (there's already an issue for it)
