### ISSUE TITLE
Quick Switch Window... doesn't seem to switch

### ISSUE THREAD

**Issue by skube** [Microsoft/vscode#49119]
Unless I'm using it incorrectly, the Quick Switch Window functionality only seems to switch once. Subsequent uses only flickers a menu and doesn't switch back.

I'll created a giphy to illustrate:
https://media.giphy.com/media/pqszD16Zmbynikr3Mi/giphy.gif

- VSCode Version: 1.22.2
- OS Version: 10.13.4

Steps to Reproduce:

1. Open multiple folders at the same time
2. Use `⌘` + `Shift` + `P` and select `Quick Switch Window...`

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@skube the command is only meant to be executed via keybindings, not the picker. The idea is that you press the key combination for it and hold the keys to tab between windows in the same way Alt+Tab works on Windows where pressing Alt switches the window.

**Comment by skube** [comment]
Interesting, but it still doesn't work when using with keybindings. It will Quick Switch Once and then not work thereafter.

**Comment by bpasero** [comment]
@skube add this to keybindings.json:

```json
{
	"key": "ctrl+u",
	"command": "workbench.action.quickSwitchWindow"
},
{
	"key": "ctrl+u",
	"command": "workbench.action.quickOpenSelectNext",
	"when": "inQuickOpen"
}
```

* open 2 windows
* press Ctrl+U and hold the Ctrl key
* press U again
* release the Ctrl

That is how this feature (and all other related quick switch actions) work.

**Comment by skube** [comment]
That sort of works, but I still maintain the _quick_ switching of windows is a broken experience. 

As an example, `ctrl` + `tab` will progress thru open Editors (i.e. files) as long as you hold down `ctrl`
Tapping `ctrl` + `tab` will cycle only the last two (essentially quick jumping)

I would expect the **Quick Switch Window** to behave the same, but it does not.
