### ISSUE TITLE
Autocomplete only works on every other key press with multiple cursors on same line

### ISSUE THREAD

**Issue by giraluna** [Microsoft/vscode#4911]
If the primary cursor is not the only cursor on it's line, autocomplete suggestions are only available on every other key press.
![vscode_autocomplete_singleline](https://cloud.githubusercontent.com/assets/6246237/14247922/390e26ea-fa7a-11e5-82a4-6f9a60ee403f.gif)

Manually opening the suggestions works, but causes the next key press to not trigger autocomplete. If secondary cursors are on a different line than the primary cursor autocomplete works as expected. Number and order of secondary cursors doesn't seem to matter.

Expected: Autocomplete triggers after every key press.

Steps to Reproduce:
1. Default settings, no extensions. Tested with .ts and .php files.
2. Create multiple cursors on one line and type anything that would open the autocomplete suggestion box.
- VSCode Version: 0.10.11, 0.10.13-insider
- OS Version: Windows 7

**Comment by jrieken** [comment]
The problem is `this.lineContentAfter !== context.lineContentAfter`, us comparing the line content after the cursor and bailing out if it has changed. With multiple cursors on the same line that happens all the time...
