### ISSUE TITLE
Windows 10 1803 upgrade

### ISSUE THREAD

**Issue by omartin2010** [Microsoft/vscode#49123]
Issue Type: <b>Bug</b>

I can't repro because would need to re-upgrade my copy of Windows 10. After it's been upgraded to windows 1803, paths to command prompts in settings were broken.

But love the product anyways!! :)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (6.35GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe C:\Users\omart\OneDrive - Microsoft\Customers\Aptiv\AzureTestTsr\AzureTest\matconvnet\datareader.py|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
nbpreviewer|jit|1.0.0
vscode-cudacpp|kri|0.1.1
vscode-azureappservice|ms-|0.7.1
vscode-kubernetes-tools|ms-|0.1.8
python|ms-|2018.4.0
vscode-ai|ms-|0.1.7
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
PowerShell|ms-|1.7.0
azurerm-vscode-tools|msa|0.4.0
vscode-yaml|red|0.0.11
cmake|twx|0.0.17
vim|vsc|0.11.5

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@omartin2010 you don't know what you old paths were? Which shell(s) were you pointing at?

**Comment by omartin2010** [comment]
luckily it's still n the default file : "C:\\WINDOWS\\Sysnative\\cmd.exe"
and I've added my user settings "C:\\WINDOWS\\System32\\cmd.exe"...\
does that help?

**Comment by Tyriar** [comment]
@omartin2010 sysnative should only show up in the default when you're running the 32-bit version VS Code in the 64-bit version of Windows. Are you using the 32-bit version? (I think you can check in Help > About)

**Comment by omartin2010** [comment]
Good point - Help/About shows
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T17:28:16.777Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture **ia32**

so I'm on 32 bits. Nevertheless, it's interesting that after the upgrade the problem surfaced. Not sure if other did. I guess I should upgrade to 64 bite version of vs code anyways.

**Comment by Tyriar** [comment]
@omartin2010 are you on 32-bit Windows? Not sure if this is lying or not:

> OS version: Windows_NT ia32 10.0.17134

If you're on 64-bit Windows you should definitely upgrade to 64-bit VS Code or you will hit weird compatibility issues like this.

**Comment by omartin2010** [comment]
I'm on 64bit windows - so if it's worth  me upgrading VScode to 64bits, I'll do so. I started but then seen that it needs to be uninstalled and didn't want to reconfigure the settings.json, etc., that I had done... if it doesn't delete these config files I guess I should be good.

**Comment by Tyriar** [comment]
It won't touch your settings/keybindings, uninstalling should leave them where they are.

**Comment by Tyriar** [comment]
I'll close this, let me know if there's problems when you update
