### ISSUE TITLE
Quick find and Find in files return phantom files

### ISSUE THREAD

**Issue by publicJorn** [Microsoft/vscode#49124]
- VSCode Version: 1.22.2
- OS Version: MacOS Sierra 10.12.6

Description:
- When I use quick find or Find in files feature, very often vscode will find a file twice (or more).
- I have revealInExplorer on, so when I switch tabs the explorer view will center on the file.
- With the "normal" file it will center, with the phantom file it will not.
- Changing any of the files and then saving will reflect the change in both files.
- Note that the files have the same path.

Steps to Reproduce:
To illustrate the problem, here some screenshots:

See SidebarMobileSticky appear twice in Find in files:
![screen shot 2018-05-03 at 15 42 08](https://user-images.githubusercontent.com/1209869/39580780-4020a54a-4eea-11e8-9270-115b82a9e245.png)

Even three times in Quick find:
![screen shot 2018-05-03 at 15 47 19](https://user-images.githubusercontent.com/1209869/39580824-5b8f70e0-4eea-11e8-96a4-8d730b1bf95d.png)

Moving from `routes.json` tab to left, explorer view doesn't center:
![screen shot 2018-05-03 at 15 44 33](https://user-images.githubusercontent.com/1209869/39580858-6ff64f7c-4eea-11e8-9ab0-860bac689009.png)

Moving from the "phantom" SidebarMobileSticky tab to the "real" one, it will center:
![screen shot 2018-05-03 at 15 44 44](https://user-images.githubusercontent.com/1209869/39580906-96be1d88-4eea-11e8-8a75-285ae03bea7e.png)

- This also happens when I disable all extensions.
- It does not seem to happen in ALL projects however... I haven't been able to find a common ground on when it happens or not. But it seems to occur mostly with larger projects.

**Comment by roblourens** [comment]
Is that file open? I'm guessing that it's open with a path that is somehow different than the canonical path of the file on disk. 

If you click the multiple results, are you able to open multiple copies of the one file?

**Comment by publicJorn** [comment]
Actually the paths and files are the same (see last two screenshots).
However, on a hunch I started searching about vscode cache and came upon this post: https://stackoverflow.com/questions/45216264/clear-file-content-cache-in-visual-studio-code

The command *Clear Editor History* resolved the problem :)
