### ISSUE TITLE
Main text window resizable border

### ISSUE THREAD

**Issue by rafaelkperes** [Microsoft/vscode#49121]
Issue Type: <b>Bug</b>

I couldn't really reproduce it again, as I'm not sure how it got to that state. I believe it was due to some extensions. I tried launching code with disabled extensions, and it persists.
As I lack in words to describe the issue, what happens is that border (blank space between line numbers and actual border) in the screenshot:
![Blank border](https://i.imgur.com/YBE9WCV.png)

Sorry if this is a duplicate.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 3.10.0-862.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600T CPU @ 2.80GHz (4 x 3569)|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (9.80GB free)|
|Process Argv|/usr/share/code/code src/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.37
output-colorizer|IBM|0.1.2
numbered-bookmarks|ale|0.11.1
project-manager|ale|0.25.2
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
gitlens|eam|8.2.4
terminal|for|0.0.10
vscode-dimmer|hoo|2.1.0
Go|luk|0.6.78
python|ms-|2018.4.0
sublime-keybindings|ms-|4.0.0
partial-diff|ryu|1.1.0
vscode-todo-highlight|way|0.5.12
markdown-all-in-one|yzh|1.2.0

(3 theme extensions excluded)

</details>

**Comment by rafaelkperes** [comment]
Is there any update on this? To this day, the editor is still facing the issue.

**Comment by rebornix** [comment]
@rafaelkperes sorry for replying late. Do you run into this issue if you do `code --disable-extensions`? I can't reproduce this issue on my Ubuntu 18.04. It would be great if I can have more info.

**Comment by rafaelkperes** [comment]
Hi. Yes, but only in Zen Mode (I don't remember if it was always only in Zen Mode, but that's the current situation).
By they way, I'm on `Red Hat Enterprise Linux Client release 7.4 (Maipo)`.

**Comment by rebornix** [comment]
@isidorn I think he is referring to the centered editor feature ;)
