### ISSUE TITLE
[Intellisense] Prioritize methods than other entries in "require" and "imports"

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#49120]
Since i do not always know exactly what an **import** or a **require** offer to me as methods, it will be great if intellisense can sort it's result to put them first in the list : 

In short, changing this (actual behaviour) which includes full of global methods : 
![image](https://user-images.githubusercontent.com/5599375/39577862-c24b5b4e-4ee2-11e8-9415-0c84b0433c15.png)

Into this (needed behaviour) which prioritize needed methods to import : 
![image](https://user-images.githubusercontent.com/5599375/39578015-46e74cdc-4ee3-11e8-956c-b22e5443c834.png)

It can save the time to open the other file to check names, or the time to scroll down to find the method.

**Comment by mjbvz** [comment]
The suggestions at the head of the list are all snippets, correct?

**Comment by DavidBabel** [comment]
Oh yes, you are right. So the real issue here, is to reorder the entries like this : 
- methods to import
- snippets (i know the option editor.snippetSuggestions, but imports must be before, since snippets are useless in require and imports)
- others

**Comment by mjbvz** [comment]
Ok, I'd say this falls under #1304

Hard since people can create snippets for imports too

**Comment by DavidBabel** [comment]
When you are into brackets, nothing else than methods are utils.
