### ISSUE TITLE
VS Code 1.22.2 wont launch on macOS Sierra 10.13.4

### ISSUE THREAD

**Issue by schirato** [Microsoft/vscode#49122]
- VSCode Version: 1.22.2
- OS Version: Sierra 10.13.4

Steps to Reproduce:

1.  Click on the VS Code icon
2. The same opens the application but stays on a black screen
3. All items in the menu, clicking does nothing
4. Only that works is to see the version of VS Code
5. Often you need to reinstall VS Code
6. And when running later it opens the msg of the mac asking: "Visual Studio Code.app” is damaged and can’t be opened. You should move it to the Trash."

The problem occurs every time the mac is restarted forced or terminated without closing the vscode

Does this issue occur when all extensions are disabled?: Yes
![screen shot 2018-05-03 at 10 52 32](https://user-images.githubusercontent.com/4511849/39580700-1efa8ee6-4ec0-11e8-887e-00c67103b78f.png)

**Comment by bpasero** [comment]
@schirato does  it help if you download VS Code again and remove the old installation?

**Comment by schirato** [comment]
@bpasero I've done this process N times and the same problem always occurs. This problem began to present more frequently about 2 months ago.
