### ISSUE TITLE
Closing a file should NOT scroll the file explorer to the location of the next file that is open

### ISSUE THREAD

**Issue by rclai** [Microsoft/vscode#49128]
- VSCode Version: 1.22.2 (1.22.2)
- OSX Version: 10.13.4 (17E202)

Steps to Reproduce:

- Have multiple files from different folders open at a time (You need to have lots of files, otherwise there's no file explorer scrolling obviously)
- Close one of those files
- Watch your file explorer scroll (and maybe uncollapse a bunch of folders) to the location of the next file that is open

This is not so much a bug as it is a huge UX annoyance. At least give us some setting to not have the file explorer abruptly move when I close a file.

Consider this case: I already have some files open in other folders but I want to go into one specific folder, and edit each file while closing them after I finish editing each file. So I scroll to that folder, open one file, edit, close, then-BAM-my file explorer ends up in a completely different place, the place of the current file that is now open on some completely different folder. So now I have to scroll all the way back to where I was and find the next file I was supposed to edit.

**Comment by isidorn** [comment]
`explorer.autoReveal: false`

**Comment by rclai** [comment]
Thank you!
