### ISSUE TITLE
IsolatedStorage directory creation (and non-reclamation) 

### ISSUE THREAD

**Issue by sethgrid** [Microsoft/vscode#49139]
- VSCode Version: April 2018 (version 1.23)
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:
0. Use Live Share
1. Open a directory of files using `code .`
2. Make a change to a file, like adding whitespace to the front of a line, adjusting the text.
3. In the directory that you were just in. You will now see `IsolatedStorage/`. It will never go away without manual removal now.

Does this issue occur when all extensions are disabled?: No

Thank you for this prompt!
I dug in. When I removed live share, this stopped happening. So the issue is live share creating this directory. Added step (0) above.

**Comment by rebornix** [comment]
Please file issue against Live Share ;)

**Comment by jeffreypriebe** [comment]
Same issue. I don't have LiveShare installed.
Using Current VS Code 1.23.0, Mac OS 10.13.4
