### ISSUE TITLE
Recherche d'une variable dans le workspace

### ISSUE THREAD

**Issue by AndyLCQ** [Microsoft/vscode#49130]
Issue Type: <b>Bug</b>

Je fais un CTRL SHIFT + F pour rechercher. Je tape "$http" pour trouver toutes les variables nommées "$http" cela ne fonctionne pas.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 3392)|
|Memory (System)|3.90GB (0.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.0
gitlens|eam|8.2.4
php-intellisense|fel|2.3.1
smarty|imp|0.3.0

</details>

**Comment by roblourens** [comment]
Can you explain the problem in more detail?

**Comment by AndyLCQ** [comment]
Hi,

My problem is that I tried to search everywhere where I had my var in all the projet.
So I made a Ctrl + shift + F to search in the projet ; I write « $myvariable » and press enter but nothing happens even if I knew there was more than 1 occurrence. 

Hope it’s better.
Sorry for my English 

Envoyé de mon iPhone

**Comment by roblourens** [comment]
Please see this wiki page for some search troubleshooting tips: https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results
