### ISSUE TITLE
debug.enableAllHovers should show all hovers

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#49131]
Currently `"debug.enableAllHovers": true` only pings all the hover providers.
Idealy it would allow to show all other hovers and not keep them hidden.

In order for this to be done we would need to introduce a hover registry such that the hovers are not independent hacks.
The ColorPicker would also need to be cleaned up.

fyi @alexandrudima

**Comment by andrecasal** [comment]
I've tried setting `"debug.enableAllHovers": true` but I see no changes - the hovers are all the same. Isn't this setting supposed to show hovers like the color picker during a debugging session?

**Comment by andrecasal** [comment]
According to [this video](https://www.youtube.com/watch?v=9QXwSg9-2qQ) on the [Live Share page](https://visualstudio.microsoft.com/services/live-share/), this setting only makes sense for Live Share clients who connect to a Live Share server. Both server and client need to have the Live Share extension installed.

This being the case, it makes sense for this setting to not be in VS Code by default and be a Live Share contributed setting instead.
