### ISSUE TITLE
Failed to Install VS Code Update 

### ISSUE THREAD

**Issue by og-neth** [Microsoft/vscode#49132]
- VSCode Version: 1.22.1
- OS Version:  Windows 8.1

Steps to Reproduce:

1. Install the update when prompted by Visual Code application once launching Visual Code
2. Wait for it to finish downloading in the background 
3. VS Code error appears describing to file an issue on Github and attach the log

Does this issue occur when all extensions are disabled?: Yes
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1971817/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
This should be #47815
