### ISSUE TITLE
Ubuntu 18.04 - Terminal rendering glitch

### ISSUE THREAD

**Issue by CZakalwe** [Microsoft/vscode#49137]
Issue Type: <b>Bug</b>

The terminal sometimes ends up rendered totally white with glitchy specks of colour all over the place. Can still see a cursor but no text is visible:

![screenshot from 2018-05-04 06-28-47](https://user-images.githubusercontent.com/28881186/39596414-64583f64-4f66-11e8-9e67-8e6a9c600903.png)

This seems to happen after waking the PC from sleep with VSCode running. No other apps have any issues in this scenario including the Terminal application which was also running when PC was woken from sleep.

Distro: Ubuntu 18.04
GFX: Dual Nvidia GTX960 Video cards on Nvidia drivers

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3282)|
|Load (avg)|0, 0, 0|
|Memory (System)|15.57GB (8.78GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.2.4
python|ms-|2018.4.0
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
PowerShell|ms-|1.7.0

</details>

**Comment by CZakalwe** [comment]
Confirmed. It definitely happens when sleeping the PC with VSCode running and then waking it again.
No other apps have any issues so far.

**Comment by Tyriar** [comment]
This is an upstream Chromium bug, nothing we can do on our side.
