### ISSUE TITLE
Folding all JavaScript code would incorrectly skip HTML strings

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/vscode#49136]
- VSCode Version: Stable 1.22
- OS Version: Windows 7 Enterprise LTS

Steps to Reproduce:

1. Copy the following code into a blank document in VS Code:

```javascript
function foo() {
  var string = `
<div>
	<span>Hello world</span>
  <div>
  	<div>
    	<div>
      	<div>
        	<span>Mind the gap.</span>
        </div>
      </div>
    </div>
  </div>
</div>
`;
  string = string.replace("gap", "cap");
  console.log(string);
}
```
2. Save it as JavaScript.
3. Attempt to fold the code region using the default hotkey, `Ctrl`+`Shift`+`[`. You might have a different hotkey mapping for this feature.

**Expected:**

```javascript
function foo() {...
}
```

**Actual results:**
```javascript
function foo() {...
<div>...
</div>
}
```

I don't think it has to do with js-beautify, because code folding is a VS Code feature. If I'm wrong, let me know.

**Comment by mjbvz** [comment]
Caused by indentation based folding. Set `"typescript.experimental.syntaxFolding": true,` to fold based on syntax instead

**Comment by tommai78101** [comment]
Thanks, I didn't know there are some experimental features going on.
