### ISSUE TITLE
Opening .VSIX from explorer fails.

### ISSUE THREAD

**Issue by code4clouds** [Microsoft/vscode#49133]
- VSCode Version: 1.22.2
- OS Version: Windows 10  (10.0.17134.1)

Steps to Reproduce:

1.  Double-click a .vsix file in the Windows File Explorer
2.  .vsix files open as a binary file.
3.  file errors out (maybe is confused with Visual Studio?), although the right click "open->with" VSCode also causes the problem

Does this issue occur when all extensions are disabled?: Yes

User Story:
As a VSCode user,
I would like .vsix file to be associated with VSCode at installation,
so when I double click on the file, it opens VSCode and proceeds to install the extension.

**Comment by joaomoreno** [comment]
We don't support opening VSIX from the explorer, since VSIX is an extension which can be opened by other apps, such as Visual Studio itself. Please use the workbench actions to install a VSIX.
