### ISSUE TITLE
VSCode produces debug spew on CMD window

### ISSUE THREAD

**Issue by NielsFerguson** [Microsoft/vscode#49143]
Issue Type: <b>Bug</b>

I launch VSCode from my CMD window using the file extension association. (e.g. I type 'main.c' and it launches VSCode on that file.) That works fine, but it then keeps producing debug spew on the CMD window I launched it from first. A sample is below. This then interferes with the use of that CMD window. Also, just after launching a file this way there is an additional line feed on the CMD window which shouldn't happen. Please fix.

[main 3:33:31 PM] update#setState idle
[main 3:34:01 PM] update#setState checking for updates
[main 3:34:01 PM] update#setState idle
[main 4:34:01 PM] update#setState checking for updates
[main 4:34:01 PM] update#setState idle
[main 5:34:01 PM] update#setState checking for updates
[main 5:34:02 PM] update#setState idle
[main 6:34:01 PM] update#setState checking for updates
[main 6:34:01 PM] update#setState idle
[main 7:34:01 PM] update#setState checking for updates
[main 7:34:01 PM] update#setState idle
[main 8:34:01 PM] update#setState checking for updates
[main 8:34:01 PM] update#setState idle
[main 9:34:01 PM] update#setState checking for updates
[main 9:34:01 PM] update#setState idle
[main 10:34:01 PM] update#setState checking for updates
[main 10:34:01 PM] update#setState idle
[main 11:34:01 PM] update#setState checking for updates
[main 11:34:01 PM] update#setState idle
[main 12:34:01 AM] update#setState checking for updates
[main 12:34:01 AM] update#setState idle
[main 1:34:01 AM] update#setState checking for updates
[main 1:34:01 AM] update#setState idle
[main 2:34:01 AM] update#setState checking for updates
[main 2:34:01 AM] update#setState idle
[main 3:34:01 AM] update#setState checking for updates
[main 3:34:02 AM] update#setState idle
[main 4:34:01 AM] update#setState checking for updates
[main 4:34:02 AM] update#setState idle
[main 5:34:02 AM] update#setState checking for updates
[main 5:34:02 AM] update#setState idle
[main 6:34:02 AM] update#setState checking for updates
[main 6:34:02 AM] update#setState idle
[main 7:34:02 AM] update#setState checking for updates
[main 7:34:02 AM] update#setState idle
[main 8:34:02 AM] update#setState checking for updates
[main 8:34:02 AM] update#setState idle
[main 9:34:02 AM] update#setState checking for updates
[main 9:34:02 AM] update#setState idle
[main 10:34:02 AM] update#setState checking for updates
[main 10:34:02 AM] update#setState idle

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17662

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|Memory (System)|31.92GB (22.66GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe S:\os\public\amd64chk\internal\sdk\inc\featurestaging-msrc-globalsettings.h|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.16.1

</details>

**Comment by rebornix** [comment]
@NielsFerguson do you see this issue when you have extensions disabled?

**Comment by NielsFerguson** [comment]
I can't find the switch to disable extensions; your help system is utterly useless and the UI is counter-intuitive for a Windows person. (The UI is horrible in too many ways to list here.)
The only extension I use is the Microsoft C/C++ one so that is still a bug on us.
