### ISSUE TITLE
Log message doesn't work on breakpoints

### ISSUE THREAD

**Issue by blopez2010** [microsoft/vscode#49144]
Issue Type: <b>Bug</b>

I've testing new hot feature when debugging and placing breakpoints with log messages but it doesn't work as expected on Angular 5, look at the screenshot. It doesn't let me look at the object being printed in the Debug Console. It only prints `Plans: Array(2)`.

![image](https://user-images.githubusercontent.com/15872584/39599608-7c3fc13e-4ed9-11e8-9c5a-b707e85f629a.png)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (2.59GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_569483|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
angulardoc-vscode|Ang|4.0.1
json2ts|Gre|0.0.6
beautify|Hoo|1.3.0
output-colorizer|IBM|0.1.2
vscode-docker|Pet|0.0.26
wallaby-vscode|Wal|1.0.83
html-snippets|abu|0.2.1
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
copy-relative-path|ale|0.0.2
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
docthis-customize-tags|dwe|0.4.5
gitlens|eam|8.2.4
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.15
vscode-util|guo|1.0.5
vscode-guid|hea|1.3.1
rest-client|hum|0.18.3
angular2-switcher|inf|0.1.7
RelativePath|jak|1.4.0
typings-autoinstaller|jvi|1.2.0
vs-color-picker|lih|0.7.0
prettify-json|moh|0.0.3
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|4.3.0
vscode-icons|rob|7.23.0
partial-diff|ryu|1.1.0
code-spell-checker|str|1.6.10
es-quotes|vil|0.2.6
vscode-todo-highlight|way|0.5.12
change-case|wma|1.0.0
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.6.0
markdown-all-in-one|yzh|1.2.0

(3 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Appears fixed with the new debugger

![](https://memes.peet.io/img/20-11-be0423ae-e9d1-4308-807b-0793d92a6961.png)
