### ISSUE TITLE
Dark and Light text themes in Marketplace

### ISSUE THREAD

**Issue by rushfrisby** [Microsoft/vscode#4914]
I submitted my extension to the VS Marketplace on Friday with the "light" text theme because the hex code for my header is dark gray. When I view the page in the marketplace however I get black text.

https://marketplace.visualstudio.com/items?itemName=RushFrisby.Encryptor

I submitted the extension again with the dark text theme just to see if the logic was somehow reversed but no luck. Here is what my package.json looks like:

```json
{
    "name": "Encryptor",
    "displayName": "Encryptor",
    "description": "Encrypts and decrypts files and strings in VS Code",
    "version": "0.2.0",
    "publisher": "RushFrisby",
    "icon": "images/lock.png",
    "galleryBanner": {
        "color": "#333333",
        "theme": "light"
    },
    "engines": {
        "vscode": "^0.10.10"
    },
    "categories": [
        "Other"
    ],
    "activationEvents": [
        "onCommand:extension.encryptor_EncryptFile",
        "onCommand:extension.encryptor_DecryptFile",
        "onCommand:extension.encryptor_EncryptString",
        "onCommand:extension.encryptor_DecryptString"
    ],
    "main": "./extension",
    "contributes": {
        "commands": [{
            "command": "extension.encryptor_EncryptFile",
            "title": "encryptfile"
        },
        {
            "command": "extension.encryptor_DecryptFile",
            "title": "decryptfile"
        },
        {
            "command": "extension.encryptor_EncryptString",
            "title": "encryptstr"
        },
        {
            "command": "extension.encryptor_DecryptString",
            "title": "decryptstr"
        }]
    },
    "scripts": {
        "postinstall": "node ./node_modules/vscode/bin/install"
    },
    "devDependencies": {
        "vscode": "^0.11.0"
    }
}
```

**Comment by joaomoreno** [comment]
It's a bit counter intuitive but:

- `light` means that the the background color will be somewhat light, so the text itself will be dark
- `dark` means that the background color will be somewhat dark, so the text itself will be light

Since your background color (`#333333`) is rather dark, you should use the `dark` theme, not the light one.

When I change the theme, *bump the version* and republish, I do see an updated header in the marketplace. It should work for you too.

**Comment by rushfrisby** [comment]
thanks I'll make the change. must have been cached or delayed when i tried switching to dark.

**Comment by joaomoreno** [comment]
Cache would explain it yeah. :+1:
