### ISSUE TITLE
1.23.0-insider repeats installation over and over.

### ISSUE THREAD

**Issue by jsuddsjr** [Microsoft/vscode#49149]
We have written the 
Issue Type: <b>Bug</b>

Open Vscode, see the blue notification on the Settings button. Click and "Install Update". The update starts in the background. Then later, I'm asked to install again, and again, and again. Current version info: 

[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]

Version 1.23.0-insider
Commit e6076fad9a41821f8647b60375ad21535f424498
Date 2018-05-02T21:01:28.348Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

[OK] [Copy]

VS Code version: Code - Insiders 1.23.0-insider (e6076fad9a41821f8647b60375ad21535f424498, 2018-05-02T21:01:28.348Z)
OS version: Windows_NT x64 10.0.17133

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.82GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
python|ms-|2018.4.0
csharp|ms-|1.14.0
git-merger|sha|0.4.1
html-css-class-completion|Zig|1.17.1

</details>
needed data into your clipboard because it was too large to send. Please paste.

**Comment by joaomoreno** [comment]
Can you show me screenshots of those multiple "asks to install"? Is the wording always the same?
