### ISSUE TITLE
Support Markdown export to html

### ISSUE THREAD

**Issue by KidLau** [Microsoft/vscode#49157]
Issue Type: <b>Feature Request</b>

markdown preview is built-in function now, if support export to html, that will be perfect.
please considering it!

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment]
This is out of scope for an editor. Consider using a markdown -> html  command line tool instead
