### ISSUE TITLE
Organize Imports removes "type" keyword for importing Flow types

### ISSUE THREAD

**Issue by mvolkmann** [Microsoft/vscode#49155]
Issue Type: <b>Bug</b>

Run "Organize Imports" on a line like this:
```js
import {type PersonType, validatePerson} from './people';
```
The "type" keyword will be removed.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.09GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron VSCodeNotes.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.15.0
code-settings-sync|Sha|2.9.2
fish|Ted|0.0.4
sort-lines|Tyr|1.6.1
quokka-vscode|Wal|1.0.121
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
flow-for-vscode|flo|0.8.1
auto-rename-tag|for|0.0.15
haskell-linter|hoo|0.0.6
language-haskell|jus|2.4.0
printcode|nob|2.3.0
vscode-code-outline|pat|0.1.1
perforce|sle|3.1.0
vim|vsc|0.11.5
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.6.2

</details>

**Comment by mvolkmann** [comment]
This issue is not a duplicate of any listed above. To add a bit more detail, these are valid ways to import Flow types:

```js
import type {SomeType, AnotherType} from './some-file';
import {someFunction, type SomeType, type AnotherType} from './some-file';
```

**Comment by mjbvz** [comment]
The built-in js/ts extension does not support flow. Please try installing the flow extension and disabling the built-in js/ts extension

**Comment by mvolkmann** [comment]
I don't believe the Flow extension has an "Organize Imports" feature.
I think the use of Flow is common enough that this should be considered in the provided "Organize Imports" feature. Otherwise all developers that use Flow will be prevented from using this feature.

**Comment by mvolkmann** [comment]
How about just gathering up all the imports that include the “type” keyword from Flow and putting them at the bottom of the imports that you can organize. That would allow Flow users to still use the feature.
