### ISSUE TITLE
Parameterised commands should not show up in keybindings overview

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4915]
While looking into #58 I noticed that we register commands that require arguments to run. They still show up in the list of unassigned commands in the keybindings list which imho is not good because if you try to run them they cannot work without input. I think we should indicate this to the keybinding service that assigning a keybinding to those does not work.

<img width="501" alt="screen shot 2016-04-04 at 17 25 42" src="https://cloud.githubusercontent.com/assets/900690/14253063/50d214ca-fa8a-11e5-8563-be736487fa71.png">

<img width="435" alt="screen shot 2016-04-04 at 17 25 48" src="https://cloud.githubusercontent.com/assets/900690/14253068/54fac16e-fa8a-11e5-97c3-cf76d70b61fc.png">

@alexandrudima @jrieken fyi

**Comment by jrieken** [comment]
yeah... commands starting with an `_` should already be filtered. Unsure what to do the others...
