### ISSUE TITLE
Build process injects unknown code into artifact

### ISSUE THREAD

**Issue by taoeffect** [Microsoft/vscode#49159]
- VSCode Version: current
- OS Version: irrelevant

Steps to Reproduce:

1. run `gulp vscode-[architecture]-min`

Does this issue occur when all extensions are disabled?: Irrelevant?

-------

Gulp will [connect to `marketplace.visualstudio.com`](https://github.com/Microsoft/vscode/blob/67cd9258fd0ed429ddc626d488d48bd65c2f2283/build/lib/extensions.ts#L108) during the build and download additional code not found in the git repo, and inject that code into the final artifact.

This makes it very unclear what code is actually powering VSCode, and also makes it impossible to build the software without an Internet connection.

**Comment by marekr** [comment]
https://github.com/Microsoft/vscode/blob/67cd9258fd0ed429ddc626d488d48bd65c2f2283/build/lib/extensions.ts#L54

https://github.com/Microsoft/vscode/blob/838f4024b30ffc477ea6fbc1eba8e21afc3aff2e/build/lib/builtInExtensions.js#L45

https://github.com/Microsoft/vscode/blob/838f4024b30ffc477ea6fbc1eba8e21afc3aff2e/build/lib/builtInExtensions.js#L59

https://github.com/Microsoft/vscode/blob/838f4024b30ffc477ea6fbc1eba8e21afc3aff2e/build/lib/builtInExtensions.js#L107
https://github.com/Microsoft/vscode/blob/838f4024b30ffc477ea6fbc1eba8e21afc3aff2e/build/lib/builtInExtensions.js#L85
https://github.com/Microsoft/vscode/blob/838f4024b30ffc477ea6fbc1eba8e21afc3aff2e/build/lib/builtInExtensions.js#L21

https://github.com/Microsoft/vscode/blob/838f4024b30ffc477ea6fbc1eba8e21afc3aff2e/build/builtInExtensions.json

The beauties of open source.
You can actually look at it. 

You can see its downloading node debug extensions to prepackage.

**Comment by rebornix** [comment]
We don't put every extension into our core code base right now, which requires a download step for extensions like node debug.

**Comment by taoeffect** [comment]
> The beauty of open source.

This isn't open source, and that's the problem.

You're downloading unknown code from Microsoft's servers during the build step.

I did look at the files you mentioned, and they reference URLs that point to GitHub, but these URLs are ignored completely, and instead the mystery code is fetched from Microsoft's servers at the last minute.

You are welcome to treat your project and your users with this level of disrespect. It's your project and your call to do so, but I will not be using VSCode, and I'm seriously considering instituting a company-wide policy for all of our developers to avoid using it as well.

**Comment by RyanCavanaugh** [comment]
@taoeffect the person you're quoting does not work at Microsoft or on the VS Code team

**Comment by taoeffect** [comment]
@RyanCavanaugh Thanks, I edited my comment to make it clearer that I was replying to both @marekr and @rebornix.

**Comment by RyanCavanaugh** [comment]
Please don't interpret a closed issue as a sign of disrespect. The question was asked - why is VS Code downloading something - and answered. From a repo maintainer's perspective, there is no additional action and thus the correct state of the issue is closed. This doesn't mean "go away", it is just a metadata bit in a database that repo maintainers use to track the state of an issue.

**Comment by taoeffect** [comment]
> Please don't interpret a closed issue as a sign of disrespect. The question was asked - why is VS Code downloading something - and answered.

I'm sorry, this wasn't meant to be an issue about me having a question.

Rather, it's an issue about VSCode doing something dangerous that it shouldn't be. Closing this issue would involve not doing said shady/dangerous thing, which, [is apparently a pattern in Microsoft projects](https://lobste.rs/s/orc6nw/vscode_still_sends_search_keystrokes#c_va9isr).

Please respect your developers and users and do not download unknown code during the build step. Just because there's a config file that claims it's "nodejs debugging stuff", doesn't mean that's what gets downloaded, and certainly doesn't mean this project is "open source" when it's obfuscating what source actually gets run.

**Comment by RyanCavanaugh** [comment]
This is fundamentally no different from running `git submodule update`.

> Just because there's a config file that claims it's "nodejs debugging stuff", doesn't mean that's what gets downloaded

I don't understand the implication here. How would it download something else?

> doesn't mean this project is "open source" when it's obfuscating what source actually gets run.

It's a multi-repo build system. VS Code is not intentionally obfuscating anything - it says right there what it's doing, and the `builtInExtensions.json` file *lists the GitHub repos* for the packages it downloads: https://github.com/Microsoft/vscode/blob/838f4024b30ffc477ea6fbc1eba8e21afc3aff2e/build/builtInExtensions.json

**Comment by taoeffect** [comment]
> This is fundamentally no different from running `git submodule update`.

Let's see...

- `git submodule update` is something the developer does before the build step
- `git submodule update` represents a _completely different_ trust model
- `git submodule update` actually gives developers a chance to inspect the code that goes into the final product

Indeed, doing `git submodule update` instead of the nonsense it's currently doing would have been a great way to close this issue.

> It's a multi-repo build system. VS Code is not intentionally obfuscating anything - it says right there what it's doing, and the builtInExtensions.json file lists the GitHub repos for the packages it downloads:

The GitHub repos that it completely ignores... yes.

**Comment by marekr** [comment]
@taoeffect Well incidentially....the .vsix it downloads is just a zip file....and inside are just js files ;)

**Comment by eligrey** [comment]
@rebornix One of the issues brought up by @taoeffect is that the build process fails without an internet connection. I feel like this issue should be reopened and renamed to "build fails without internet connection". I understand that you don't wish to fix this issue at this time, but it should be in a later milestone instead of a 'wontfix'.

**Comment by auchenberg** [comment]
Today's "Want free VS Code? Build it from source" HN discussion: https://news.ycombinator.com/item?id=17346492
