### ISSUE TITLE
update  failed

### ISSUE THREAD

**Issue by ALongLi** [Microsoft/vscode#49156]
- VSCode Version:  1.22.2
- OS Version:   win7  

Steps to Reproduce:

1. vscode-inno-updater.log

May 04 08:42:55.126 INFO Checking for possible conflicting running processes... (attempt 11)
May 04 08:42:55.131 INFO Kill process if found: 6656, Code.exe
May 04 08:42:55.131 INFO Kill process if found: 5844, Code.exe
May 04 08:42:55.131 INFO Kill process if found: 5608, Code.exe
May 04 08:42:55.131 INFO Kill process if found: 9344, Code.exe
May 04 08:42:55.131 INFO Kill process if found: 9748, Code.exe
May 04 08:42:55.131 INFO Kill process if found: 8628, Code.exe
May 04 08:42:55.131 INFO Kill process if found: 9720, Code.exe
May 04 08:42:55.131 INFO Kill process if found: 1348, Code.exe
May 04 08:42:55.131 INFO Kill process if found: 7672, Code.exe
May 04 08:42:55.131 INFO Kill process if found: 7688, Code.exe
May 04 08:42:55.132 INFO Kill process if found: 9928, Code.exe
May 04 08:42:55.132 INFO Kill process if found: 6988, Code.exe
May 04 08:42:55.132 INFO Kill process if found: 9732, Code.exe
May 04 08:42:55.132 INFO Kill process if found: 9744, Code.exe
May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 WARN Kill error Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

May 04 08:42:55.132 ERRO Failed to get process file name: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
@ALongLi Is this still an issue for you?
