### ISSUE TITLE
Question about Icons for ViewContainers

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode#49151]
Both the blog post and the new documentation for the viewContainers contribution points state that the icons are supposed to be a 28x28 icon centered in a 50x40 square. I have a feeling there is a mistake here, because 50x40 is definitely not a square, and I would assume based on the looks of the icons they're actually supposed to be a square dimension.

**Comment by sandy081** [comment]
@ThadHouse Thanks for pointing that out. It should be 50*40 container.
