### ISSUE TITLE
Clear Terminal stops working after upgrading to v1.23.0

### ISSUE THREAD

**Issue by JounQin** [Microsoft/vscode#49162]
- VSCode Version: 1.23.0
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. add a simplest node server file like following:

	``` js
	// server.js
	const http = require('http')

	const server = http.createServer()
	
	server.listen(4000)
	```
2. run `node server.js`
3. press `cmd+K` or right click then click `clear(⌘+K)`

It will display `^L` in terminal.

![image](https://user-images.githubusercontent.com/8336744/39609890-de3bac04-4f7e-11e8-885a-6323f98f338a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by partiel** [comment]
same with windows 10
```
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by partiel** [comment]
Same in win10

```
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

before <kbd>ctrl</kbd>+<kbd>k</kbd>

![image](https://user-images.githubusercontent.com/38056733/39611526-d76092c6-4f8a-11e8-8a74-97b2ddca2297.png)

after <kbd>ctrl</kbd>+<kbd>k</kbd>

![image](https://user-images.githubusercontent.com/38056733/39611570-2e1e6692-4f8b-11e8-8538-f500e00a215f.png)

scroll up

![image](https://user-images.githubusercontent.com/38056733/39611581-3dc8a3c8-4f8b-11e8-8253-0935479f27b4.png)

same with `clear` bash command

![image](https://user-images.githubusercontent.com/38056733/39611595-62207f34-4f8b-11e8-9232-b0720f844143.png)

**Comment by danielsan22** [comment]
Same here, just restart my mac and now i cant clear terminal when a process is running.

**Comment by Tyriar** [comment]
I think this was changed a little preemptively. The plan after the release was to do something like this https://github.com/Microsoft/vscode/issues/48974, but that would still be flaky under some situations (such as for tasks). I think I'll just revert to the old behavior outright for the recovery build.

**Comment by Tyriar** [comment]
Pushed to master and release/1.23
