### ISSUE TITLE
Can't find "Checking For Updates..." under Help tab in Zip version for win. 

### ISSUE THREAD

**Issue by leonqli** [Microsoft/vscode#49165]
Does anybody have the same problem? Thanks! 

Best, 
Leon

**Comment by jaywick** [comment]
I've had a similar issue here - https://github.com/Microsoft/vscode/issues/47485

**Comment by leonqli** [comment]
Find solutions for zip version? I try avoid *.exe version installation because that needs admin's help.

**Comment by garu57** [comment]
I did a fresh installation on a new pc (no proxy) with win 10, again with zip, but no option to check for updates in menus. Given this and my updates in #47485, is this a limitation of zip installation?

**Comment by joaomoreno** [comment]
The ZIP doensn't have update support. In order to update, simply download the latest ZIP and extract it over the old version.

**Comment by leonqli** [comment]
This should be at least specified in the download... Otherwise, users will waste lots of time before knowing this...
