### ISSUE TITLE
Why refresh the detail page every single time?

### ISSUE THREAD

**Issue by HankelBao** [Microsoft/vscode#49163]
**Steps to procedure**:  

1. Open the plugin details page and browse some introduction about configurations  
2. Open the configuration file and write/copy some configs  
3. Return to the plugin detail page and hope to continue browsing.  

**What did I expect to happen**:  
Don't refresh the page when users just switch back into the extension tab.

**Comment by mjbvz** [comment]
Duplicate of #36310
