### ISSUE TITLE
Clang-format format document makes cursor jump back and forth

### ISSUE THREAD

**Issue by renkun-ken** [Microsoft/vscode#49166]
- VSCode Version: 1.23.0
- OS Version: macOS 10.13.4

This problem only occurs in the latest release (1.23.0).

Steps to Reproduce:

1. Create a `cpp` file and write a simple struct with a few fields.
2. Save the document to a file.
3. Use `Format Document` provided by `Clang-format`
4. Each time `Format Document`, the cursor jumps back and forth in the document, which does not happen in previous releases of VSCode.

I'm not sure if this is the problem of the extension or the editor so I also raised an issue at <https://github.com/xaverh/vscode-clang-format-provider/issues/63>.

**Comment by renkun-ken** [comment]
It looks like both `C/C++` and `Clang-format` perform formatting on the same file. Disable either resolves the problem.

**Comment by rebornix** [comment]
Seems @renkun-ken already found the root cause, you may want to disable extension based on what workspace you are in.
