### ISSUE TITLE
Highlighted indent guide for long blocks

### ISSUE THREAD

**Issue by fr43nk** [Microsoft/vscode#49173]
- VSCode Version: 1.23
- OS Version: Windows 7

Steps to Reproduce:

In my source code (c++) blocks between braces are longer than the height of my editor window. So I have to scroll down to see where the highlighted indention ends. The moment the cursor gets hidden throughout  that scrolling the highlighting gets off.

**Comment by Muchiachio** [comment]
Always if they are too long horizontally and word wrap is enabled, wrapped lines don't get the highlight.
![image](https://user-images.githubusercontent.com/6647444/39614761-e493e9bc-4f7a-11e8-81fc-e184a47e7be9.png)

**Comment by MaleDong** [comment]
Well……this problem also happens when pointing at the end bracket "}" for long JSON object or related things：
![49173](https://user-images.githubusercontent.com/6959154/39615517-2dee85ee-4fa9-11e8-8058-824ab2bde7ba.png)

**Comment by alexandrudima** [comment]
@Muchiachio I've extracted your comment to a separate issue: #49344

**Comment by MaleDong** [comment]
@arempe93：This network isn't used just for a demo:)

**Comment by julesgilson** [comment]
although it seems to work if the cursor is at the end of the indent block and you scroll up

**Comment by alexandrudima** [comment]
To reproduce, scroll the cursor out of the viewport (above):

![kapture 2018-05-29 at 15 37 24](https://user-images.githubusercontent.com/5047891/40662299-3bf1ab42-6356-11e8-98ec-a72793675651.gif)
