### ISSUE TITLE
feature-request: Sync VSCode settings and extensions on the cloud

### ISSUE THREAD

**Issue by hsir** [Microsoft/vscode#49179]
I have VSCode installed on multiple desktops. Is there a way for me to sync all my user settings, along with my extensions and color schemes on the cloud so I don't have to manually do the works?

I cloud sync the `settings.json` file with Dropbox or iCloud Drive and manually replace the file under the corresponding directory, but my extensions and color schemes will not be synced.

**Comment by ekfuhrmann** [comment]
There is an extension that works great for syncing everything in vsCode --
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

So long as you keep track of your Github account token that you create for it, it does a great job of syncing vscode across multiple machines/systems.

**Comment by rebornix** [comment]
dup of https://github.com/Microsoft/vscode/issues/2743
