### ISSUE TITLE
希望能做一个导入和导出扩展的功能

### ISSUE THREAD

**Issue by xcsweb** [Microsoft/vscode#49180]
Issue Type: <b>suggest</b>

希望能做一个导入和导出扩展和snippets的功能或者生成package.json的东西，换电脑之后可以快速的安装扩展和snippets

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|15.88GB (9.69GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-peek|dar|1.0.2
app-migrator|deb|0.0.3
php-debug|fel|1.12.3
code-runner|for|0.9.3
beautify|Hoo|1.3.0
vscode-npm-dependency|how|1.2.0
docthis|joe|0.6.0
vscode-fileheader|mik|0.0.2
debugger-for-chrome|msj|4.3.0
vetur|oct|0.11.7
autoimport|ste|1.5.3
ayu|tea|0.14.0
quokka-vscode|Wal|1.0.121

(1 theme extensions excluded)

</details>

**Comment by transtone** [comment]
你需要一个配置同步插件：
https://marketplace.visualstudio.com/items?itemName=nonoroazoro.syncing

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2743 and yes above extension can solve your problem.
