### ISSUE TITLE
Problems stay around after deleting file

### ISSUE THREAD

**Issue by bersbersbers** [Microsoft/vscode#49187]
Issue Type: <b>Bug</b>

In my workspaces (one Python, one LaTeX), problems stay around after I delete the file that created the problems. Example:

In my Python workspace, I 
- Create bug.py
- Write anything that raises a pylint error (`bug` is good, yields "E0602: Undefined variable 'bug'")
- Wait for problem to appear
- Delete bug.py

In my LaTeX workspace, I
- Create bug.tex
- Write `\documentclass{article}bug\begin{document}`
- Wait for problem to appear (missing \begin{document})
- Delete bug.tex

In both cases, the problem sticks around. I had originally reported this as https://github.com/Microsoft/vscode-python/issues/1235, but I feel this is an issue independent of Python.

Unfortunately, the problem appears harder to repro than I thought. For example, this is how it does NOT reproduce:
- Open new instance of VS Code
- File, Open Folder, select an empty folder
- File, New File, write garbage
- File, Save As, Bug.py
- Note pylint error
- Explorer pane, right-click Bug.py, Delete
- Pylint error disappears.

Console output is empty after deleting the file in question.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z) (also 1.21.1)
OS version: Windows_NT x64 10.0.17134 (also Win 10 1709)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (32 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.87GB (243.56GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|5.3.2
svn-scm|joh|1.29.0
python|ms-|2018.4.0
multi-command|ryu|1.2.0
code-spell-checker|str|1.6.10

</details>

**Comment by sandy081** [comment]
@bersbersbers This is nothing to do with VS Code. Extensions manage the problems, VS Code just provides the UI. If an extension does not remove the problem from the system after the file is deleted then the problem remains and is shown. Can you please confirm from the respective extension that it is removing problems after file is deleted or closed?

**Comment by bersbersbers** [comment]
For the record, this problem was fixed in https://github.com/JohnstonCode/svn-scm/commit/fd090c48eaf311c8750bf21c5792503b13968208
