### ISSUE TITLE
Missing keybinding to navigate explorer _not_ working files

### ISSUE THREAD

**Issue by davidpmccormick** [Microsoft/vscode#4918]
Once a file within working files has been clicked on, there doesn't appear to be a keybinding to enable the selection of this file within the tree view of the explorer.

**Comment by bpasero** [comment]
For our 1.0 release you can assign the new command `workbench.files.action.focusFilesExplorer`

Try it out today from our insiders release: http://code.visualstudio.com/Download#insiders
