### ISSUE TITLE
TypeScript format indent error

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#49184]
- VSCode Version: 1.23.0-insiders
- OS Version: Win7

**Expect**
![](http://wx2.sinaimg.cn/mw690/0060lm7Tly1fqzcn3xz92j30je03swei.jpg)

**Actual**
![](http://wx1.sinaimg.cn/mw690/0060lm7Tly1fqzcn3y0p8j30jz03o3yi.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the source code from those screenshots
