### ISSUE TITLE
After each update, launcher shortcut is gone [Manjaro/Deepin]

### ISSUE THREAD

**Issue by rinav** [Microsoft/vscode#49183]
- VSCode Version: 1.23.0
- OS Version: Manjaro 17.1.9 Hakoila (Deepin)
- Commit: 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45

Issue: When ever there is a new update of VSCode, the launcher shortcut on the deepin-dock is removed/gone. This has been happening from past 5-6 releases. 

I am using  **[aur/visual-studio-code-bin 1.23.0-1](https://aur.archlinux.org/packages/visual-studio-code-bin/)** package to install it 

Steps to Reproduce:

1. yaourt visual-studio-code-bin to install from aur 
2. after installation, from deepin-menu right click on the Visual Studio Code Icon and click on "send to dock"
3. creates the launcher shortcut on dock
4. wait for new version update and update vscode via yaourt -Syua (install the new update)
5. after update, the icon on the dock is gone

Does this issue occur when all extensions are disabled?: Yes

![deepinscreenshot_20180504130017](https://user-images.githubusercontent.com/3099775/39617000-9be3be10-4f9b-11e8-9650-362d560b7485.png)

**Comment by Tyriar** [comment]
The aur package is unofficial

**Comment by rinav** [comment]
What can be done it this regard?

**Comment by Tyriar** [comment]
@rinav reach out to the AUR package maintainer
