### ISSUE TITLE
Installation issue - Error writing to registry key

### ISSUE THREAD

**Issue by sakowiczm** [microsoft/vscode#49196]
- VSCode Version: 1.23.0
- OS Version: Windows 7

Steps to Reproduce:

1. Removed previous version of VS Code.
2. Run installer, at some point I'm getting:

```
Error writing to registry key:

HKEY_CLASSES_ROOT\VSCodeSourceFile
RegSetValueEx failed; code 87.

The parameter is incorrect.
```

**Comment by chrmarti** [comment]
Is VS Code installed after that and can you launch it?

**Comment by sakowiczm** [comment]
If I ignore I get few more writing to registry errors but VSCode can be launch at the end but none of the environment integration stuff works. 
Additional registry keys that fail:

```
RegSetValueEx failed; code 87.

HKEY_CLASSES_ROOT\VSCodeSourceFile\DefaultIcon
HKEY_CLASSES_ROOT\VSCodeSourceFile\shell\open\command
HKEY_CLASSES_ROOT\Applications\Code.exe\DefaultIcon
HKEY_CLASSES_ROOT\Applications\Code.exe\shell\open\command
HKEY_CURRENT_USER\SOFTWARE\Classes\*\shell\VSCode
HKEY_CURRENT_USER\SOFTWARE\Classes\*\shell\VSCode\command
HKEY_CURRENT_USER\SOFTWARE\Classes\directory\shell\VSCode
HKEY_CURRENT_USER\SOFTWARE\Classes\directory\shell\VSCode\command
HKEY_CURRENT_USER\SOFTWARE\Classes\directory\background\shell\VSCode
HKEY_CURRENT_USER\SOFTWARE\Classes\directory\background\shell\VSCode\command
HKEY_CURRENT_USER\SOFTWARE\Classes\Drive\shell\VSCode
HKEY_CURRENT_USER\SOFTWARE\Classes\Drive\shell\VSCode\command
```

**Comment by joaomoreno** [comment]
Can you show me a screenshot of that error?

**Comment by sakowiczm** [comment]
Sure.

![regsetvalueexerror87](https://user-images.githubusercontent.com/721228/39628732-e3aae290-4fa1-11e8-9eee-6810053cb246.png)

**Comment by joaomoreno** [comment]
@sakowiczm Is there anything special about your system, that you can think of?

If you open the registry (regedit.exe), can you navigate to `HKEY_CLASSES_ROOT\VSCodeSourceFile`?

**Comment by sakowiczm** [comment]
The only thing that comes to mind that this system is company managed and they push down their policies. But I'm installing it as admin user - and that worked well for all other software including VS.

I've tried manually remove entry HKCR\VSCodeSourceFile before installation of VSC. When the error occurs, entry is re-created but it's empty:

![image](https://user-images.githubusercontent.com/721228/39747923-921f2ee2-52a6-11e8-809a-5e53cbe81ba0.png)
