### ISSUE TITLE
Python: sluggish performance getting Symbols , Itelli sense, Quick Open

### ISSUE THREAD

**Issue by derekwallace** [Microsoft/vscode#49190]
Hi,
Im using VSCode for about 4 months now. As an editor its great. I love the constant updates and new features.
However im struggling with simple things that are very improtant
1. Quick open often only list recently opened files
2. SYmbol in files rarely works 
3. intellisense often doenst work
4. User Snippets sometimes dont work. I use these a lot. and sometimes they work, but mostly they dont (at the same time intellisense doesnt work).

I am using Windows 10, latest vscode . 
I am using a network drive to access files stored in remote server.
The workspace folder is large (7,000 files), and ive used settings to try and minimize what folders are visible and what files are searched for.

I also use CODE OUTLINE.
If i select a file it can take 10+sec for its symbol list to update.

I have tried disabling extensions to no affect.

This is an example of a profile. select a file at 2000ms and at about 10000ms the CODE OUTLINE updates. I have asked author of CODE OUTLINE and he says he just uses the Symbol API.

![profile](https://user-images.githubusercontent.com/5574230/39619312-4c9f803a-4f7f-11e8-98b1-6921c1c70983.png)

Thx
Derek

**Comment by derekwallace** [comment]
If I move my codebase to local c drive the performance is much better.
Is code continually accessing files on disk? Could slow disk access be the root cause! Opening files is very quick.
Does code have a dB that it caches the symbols?
Does it rescan the file every time you select it from the open editors..

Thx

**Comment by chrmarti** [comment]
Quick Open for files does both: It caches every file listing so it can use that while collecting the next file listing which happens once per Quick Open command.

Quick Open for files is generally quite fast, I assume you have symbol search enabled. Could you disable `"search.quickOpen.includeSymbols"` and see if Quick Open for files improves?

**Comment by derekwallace** [comment]
I dont have includeSymbols enabled.
  "search.quickOpen.includeSymbols": false

I have noticed the followin
1. open code, open a file and i do nothing for a few minutes, then in general things work correctly
QuickOpen, intellisense, symbols in files.
2. if i now do something e.g. open another file then the following happens
- a clock/timer symbol appears on the Explorer icon. this runs for 30+ secs. (this can go on for minutes...)
- a line scrolls across  under the word "Explorer" pane
- during this time all the features no longer work; quick open, intelisense.
- if i type in an open file the "line scrolls across as above" while this is happening , again intelliesense does not work

3. typing in the file causes the horizontal line scrolling (10+sec).
- again things can be unresponsive during this time..

It feels like every time you open/type/select different file, things start to happen in backgrupnd that take a lot of time and hence some features in the app stop working.

As an editor, things remain usable. but the more useful features are completely un-usable.
ive tried everything in the configuration settings, but the behaviour is consistent.

![image](https://user-images.githubusercontent.com/5574230/39779873-5820269a-5302-11e8-8507-960a791e8d19.png)


![image](https://user-images.githubusercontent.com/5574230/39779923-8eb7bfec-5302-11e8-8a45-69798fee1f0a.png)

**Comment by derekwallace** [comment]
uninstalled python extension
installed pydev extension. 
behaviour is very differnt . finding symbols in file works.
intellisense works.

looks like python is the issue.
ive disabled pydev and reinstalled python. same behaviour again. un-usuable.

my conclusion is that python on a network drive is un-usuable.

**Comment by derekwallace** [comment]
noticed this
python extension enabled.
select .py file. suggestions dont work. (.eg global snippet)
select .tct file. suggestions work.

disable python extension
select .py file. suggestions  work.
select .tct file. suggestions work.


The python extension is hogging/stalling/hanging/overloaded or someting.

Task master is not showing significant CPU usage.

**Comment by chrmarti** [comment]
Moving this for the Python extension specific issues. Please open additional issues if anything is left after that. Thanks.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-python#1675
