### ISSUE TITLE
Update to 1.23 fails

### ISSUE THREAD

**Issue by peterfaller** [Microsoft/vscode#49195]
- VSCode Version: 1.22
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open VSCode
2. Update

Does this issue occur when all extensions are disabled?: Yes/No

Can't tell - code will no longer run ...

Contents of vscode-inno-updater.log:

May 04 11:28:52.384 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
May 04 11:28:52.387 INFO Checking for running Code.exe processes... (attempt 1)
May 04 11:28:52.387 INFO Code.exe is running, wait a bit
May 04 11:28:52.879 INFO Checking for running Code.exe processes... (attempt 2)
May 04 11:28:52.883 INFO Code.exe is running, wait a bit
May 04 11:28:53.384 INFO Checking for running Code.exe processes... (attempt 3)
May 04 11:28:53.388 INFO Code.exe is running, wait a bit
May 04 11:28:53.890 INFO Checking for running Code.exe processes... (attempt 4)
May 04 11:28:53.894 INFO Code.exe is not running
May 04 11:28:53.894 INFO Checking for possible conflicting running processes... (attempt 1)
May 04 11:28:53.898 INFO Inno Updater v0.4.3
May 04 11:28:53.898 INFO Starting update, silent = false
May 04 11:28:53.925 INFO do_update: "C:\\Program Files\\Microsoft VS Code\\Code.exe", _
May 04 11:28:53.925 INFO move_update: "C:\\Program Files\\Microsoft VS Code\\unins000.dat", _
May 04 11:28:53.925 INFO Delete: "Code.exe" (attempt 1)
May 04 11:28:53.977 INFO Delete: "Code.exe" (attempt 2)
May 04 11:28:54.178 INFO Delete: "Code.exe" (attempt 3)
May 04 11:28:54.900 INFO Delete: "Code.exe" (attempt 4)
May 04 11:28:55.429 INFO Delete: "Code.exe" (attempt 5)
May 04 11:28:56.679 INFO Delete: "Code.exe" (attempt 6)
May 04 11:28:58.480 INFO Delete: "Code.exe" (attempt 7)
May 04 11:29:00.931 INFO Delete: "Code.exe" (attempt 8)
May 04 11:29:04.131 INFO Delete: "Code.exe" (attempt 9)
May 04 11:29:08.182 INFO Delete: "Code.exe" (attempt 10)
May 04 11:29:13.182 INFO Delete: "Code.exe" (attempt 11)
May 04 11:29:13.182 ERRO Access is denied. (os error 5)

**Comment by chrmarti** [comment]
Looks like #49176.

**Comment by peterfaller** [comment]
The uninstall/reinstall worked.
