### ISSUE TITLE
organizeImports should respect tslint.json

### ISSUE THREAD

**Issue by ninjaonsafari** [Microsoft/vscode#49194]
It would be nice if the organizeImports would respect the settings in tslint.
If you have an import such as:
```
import {
    ActivatedRouteSnapshot,
    CanActivate,
    CanActivateChild,
    Router,
    RouterStateSnapshot
} from '@angular/router';
```

it will organize it as follows:

```
import { ActivatedRouteSnapshot, CanActivate, CanActivateChild, Router, RouterStateSnapshot } from '@angular/router';
```

The problem is that I have the tslint rule `max-line-length` set to 100 characters. 

- VSCode Version:  1.23.0
- OS Version: Windows 8

Steps to Reproduce:

1. Activate `organizeImports`
2. Add tslint.json with the rule `max-line-length: [true, 100]`
3. Save `.ts` file 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Support for max-line-length is tracked by https://github.com/Microsoft/TypeScript/issues/22991
