### ISSUE TITLE
Shortkey for 'Place Cursor on Multiples Lines' not Working

### ISSUE THREAD

**Issue by mrhammadasif** [Microsoft/vscode#49192]
Issue Type: <b>Bug</b>

1. Select multiple lines
2. Press `shift+cmd+L`

Expected Result:
Cursor should be placed on multiple lines but it doesn't works

Workaround:
I have tried selecting the command in the Command Palette and its works

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.32GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_557192|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.3.0
vscode-docker|Pet|0.0.26
unity-tools|Tob|0.1.15
unity-debug|Uni|1.3.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
node-modules-context-menu|dar|0.0.3
jshint|dba|0.10.18
tslint|eg2|1.0.28
apacheconf-snippets|eim|1.1.9
search-node-modules|jas|1.3.0
expand-region|let|0.1.2
unity-snippets-modified|lio|0.4.0
string-manipulation|mar|0.2.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
vscode-scss|mrm|0.6.2
csharp|ms-|1.14.0
sublime-keybindings|ms-|4.0.0
vetur|oct|0.11.7
Lodash|oys|1.0.0
npmsmartimporter|ref|3.0.0
sass-indented|rob|1.4.9
code-spell-checker|str|1.6.10
blade-runner|yuk|1.0.0

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Sorry we don't have `Place Cursor on Multiples Lines ` command, if you are using an extension, please file issue against it.

**Comment by mrhammadasif** [comment]
Sorry, I was referring to `Add Cursor to Line Ends`
