### ISSUE TITLE
Language plugin adding new problem matcher

### ISSUE THREAD

**Issue by waywardmonkeys** [Microsoft/vscode#492]
In my [vscode-dylan](https://github.com/dylan-lang/vscode-dylan/) extension, I'd like to be able to add a new problem matcher so that it can be shared between all projects that run the [Dylan](http://opendylan.org/) compiler.

**Comment by nadako** [comment]
I'd like to have the same for the [vscode-haxe](https://github.com/jcward/vscode-haxe) extension.

**Comment by dbaeumer** [comment]
I need to push this out. I spent all my time in adapting TS 2.0.3.

**Comment by dbaeumer** [comment]
See the discussion in https://github.com/Microsoft/vscode/issues/15179. We will revisit the task running framework and how extension can participate in build which makes contributing problem matchers not needed anymore. The work on the new task running system will start in January.

I will close this issue favour of https://github.com/Microsoft/vscode/issues/15179.
