### ISSUE TITLE
Auto debug restart on source change

### ISSUE THREAD

**Issue by rrousselGit** [Microsoft/vscode#49209]
_New feature suggestion :_

With mono-repo/multi-root workspaces, we usually want to work on more then one _project_ at a time.
Which means we  may have many debug sessions running simultaneously. 

With compounds it's easy to start multiple debug dessions. The problem is, when editing the code, we rarely need to restart _all_ of them. 

The problem is, it's relatively tedious to restart one specific debug session. 

So here's my suggestion :

Add the a new field to `launch.json` configurations ; which would define an auto-restart behavior.
That field would be of type `boolean | string[]`. 

An example of usage would be :

```
    "configurations": [
        {
            "type": "foo",
            "request": "launch",
            "autoRestart": true,
            ...
        },
        {
            "type": "foo",
            "request": "launch",
            "autoRestart": [
                   "${workspaceRoot}/src/*",
                   "${workspaceRoot}/test/*",
              ],
              ...
        },
```

The idea beind it would be that the debug session would be automatically rebooted when: 
    - `autoRestart === true` and the workspace had a source change
    - `autoRestart` is a list of paths, and one of these paths had a source change

This would retrigger both `preLaunchTask` and `postDebugTask`

**Comment by rrousselGit** [comment]
Not really. Because the debug session which requires a restart isn't necesseraly focused. 
And there's also not necesseraly only one debug session to restart.

For example, we could debug ProjectA + ProjectB+ ProjectC simultaneously. 
Make a change on ProjectA. But reload both A and B because B depends on A.

**Comment by rrousselGit** [comment]
> However other debug types would have to support this.

The idea behind it is to _not_ be dependant on the language used 😄 


If that feature makes sense, I can definitely contribute to make it happens.

Is there anyone I can contact to know "Where to get started" or if that even fits vscode ?

**Comment by isidorn** [comment]
@rrousselGit I am that someone to contact. And for now we would not accept this feature as part of the core functionlaity. Let's leave this feature request open and see if it generates some traction.

**Comment by rrousselGit** [comment]
I see. So what can I do in the mean time beside waiting ? As it's something which would greatly improve my current workflow based on a wide variety of techs.

Would that be possible using a custom made extension ?

**Comment by weinand** [comment]
@rrousselGit yes, try to implement this feature as an extension first.

**Comment by kilianc** [comment]
> VS Code's node debugger supports nodemon with the "restart" flag.

Does this mean that I can live-reload code in my container (restart node) and when few seconds later when 9229 becomes open again vscode debugger will attach again until I stop it manually?

**Comment by rrousselGit** [comment]
@weinand Not all vscode supported languages are JS. The goal would be to have something that works _everywhere_
Nodemon works great for js. But I have a broad variety of languages and some don't have a nodemon equivalent 

Sadly it doesn't seems possible with an extension

**Comment by weinand** [comment]
@kilianc yes, node debug's "restart" flag does exactly this.

**Comment by weinand** [comment]
No plans to work on this.

**Comment by lopugit** [comment]
I would like this feature, for mocha testing. Gonna see if the nodemon solution works for mocha environments

**Comment by mmcc007** [comment]
@rrousselGit Just ran into this problem developing a dart server. Following [this stackoverflow suggestion](https://stackoverflow.com/a/49142066/1420881) I installed the [Save and Run Ext ](https://marketplace.visualstudio.com/items?itemName=padjon.save-and-run-ext) extension and modified it for a dart command line program:
```
{
  "saveAndRunExt": {
    "commands": [
      {
        // "match": "\\.(css$|js$|html$)",
        "match": ".dart$",
        "isShellCommand": false,
        "cmd": "workbench.action.debug.restart",
        "isAsync": false
      },
      {
        "match": ".dart$",
        "isShellCommand": false,
        "cmd": "dart.rerunLastTestDebugSession"
      }
    ]
  }
}
```
This will restart the server and rerun the last debug session if any dart file is saved. Both server and test debug sessions work.
Works great for me, at least on initial use of this extension.
From what I can tell, should be possible to configure this extension to work for all languages.

**Comment by Sanmeet007** [comment]
Thanks alot  @mmcc007 it worked perfectly like i needed !
