### ISSUE TITLE
There is an extra line breaker when copying text to Keynote

### ISSUE THREAD

**Issue by jackalcooper** [Microsoft/vscode#49203]
Issue Type: <b>Bug</b>

1. Select some text in VSCode
2. Copy them to Apple Keynote app's text box by pasting with matching style mode.
3. An extra line breaker is inserted.
[What is matching style pasting mode](https://webapplog.com/paste-and-match-style-on-mac-os-x/)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/jackalcooper/oss/oneflow|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
dustjs|Azk|0.1.1
vscode-markdownlint|Dav|0.15.0
gc-excelviewer|Gra|2.0.21
vscode-docker|Pet|0.0.26
copy-relative-path|ale|0.0.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.8
prototxt|dmi|0.0.6
githistory|don|0.4.0
gitlens|eam|8.2.4
vscode-npm-script|eg2|0.3.4
vscode-great-icons|emm|2.1.31
git-project-manager|fel|1.5.1
ocaml|hac|0.6.43
bucklescript-tea-tools|jac|0.0.6
vscode-cudacpp|kri|0.1.1
vscode-elixir|mjm|1.1.0
mssql|ms-|1.3.1
python|ms-|2018.4.0
cpptools|ms-|0.16.1
vscode-code-outline|pat|0.1.1
red|red|0.2.2
rust|rus|0.4.2
octave|toa|0.0.3
cmake|twx|0.0.17
transpose|v4r|0.0.5
gitblame|wad|2.4.2
change-case|wma|1.0.0
erlang-otp|yuc|0.2.4
vscode-proto3|zxh|0.2.1

(3 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Similar issue with https://github.com/Microsoft/vscode/issues/21686 , let's track it there.
