### ISSUE TITLE
Expand debug console objects as default

### ISSUE THREAD

**Issue by savpek** [Microsoft/vscode#4920]
Current version: 0.10.11.

Feature request:
![image](https://cloud.githubusercontent.com/assets/481896/14255611/7fa70dd8-fa9d-11e5-8463-2fd1ad4039b8.png)

When i type object in console i expect to see actual information about object. Currently it doesn't expand target, so to see what properties eg. it actually i have to: grap mouse -> expand object. I think usually that 'object' or whatever non expanded information is useles to user, for that reason default should be other way around. What i propose is that objects are expanded on default when they are printed to console.

So output as default may look like this:
![image](https://cloud.githubusercontent.com/assets/481896/14255699/eeeb190a-fa9d-11e5-8495-38e4d1969c46.png)

Other possibility may be shortcut to expand last (or all) objects in output.

**Comment by isidorn** [comment]
This is now supported
