### ISSUE TITLE
Integrated terminal (bash) does not render "_" char

### ISSUE THREAD

**Issue by DanielSSilva** [Microsoft/vscode#49206]
- VSCode Version: 1.23.0
- OS Version: Linux Mint 18.3 Sylvia

Steps to Reproduce:

1. Open integrated terminal
2. type `_`.
3. It is not rendered but it's used.

This can be seen in the following image:

![image](https://user-images.githubusercontent.com/6862119/39628121-ec4dcf68-4f9f-11e8-9605-03fbdd143ee5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
