### ISSUE TITLE
File opens in both views

### ISSUE THREAD

**Issue by abhyudayasrinet** [Microsoft/vscode#49200]
Issue Type: <b>Bug</b>

If I have a file open in the left editor and my focus is in the right editor and I click on the file name in the explorer then it opens the file in the right editor. Ideally, it should just shift my focus to where it's open in the left editor.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|7.87GB (2.53GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\abhyu\Desktop\work\doggles\homepage popup|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.1
gc-excelviewer|Gra|2.0.21
python|ms-|2018.4.0
cpptools|ms-|0.16.1
csharp|ms-|1.14.0

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
Can be configured with `"workbench.editor.revealIfOpen": true`
