### ISSUE TITLE
Process Explorer: "CPU %" column french name is too long: "% PROCESSEUR"

### ISSUE THREAD

**Issue by SylChamber** [microsoft/vscode#49211]
Issue Type: **Bug**

The column name for CPU in French is too long and overlaps on the second column (Memory): currently it's "% PROCESSEUR". 

I suggest replacing the string with the French translation used in Windows task manager:

% UC

"UC" is the standard French abbreviation for "CPU" according to CSA and CEI. See the [Canadian Government's linguistic data bank on term "CPU"](http://www.btb.termiumplus.gc.ca/tpv2alpha/alpha-eng.html?lang=eng&i=1&srchtxt=cpu&index=alt&codom2nd_wet=KD).

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2699A v4 @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|12.00GB (8.16GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
cucumberautocomplete|ale|2.10.0
vscode-markdownlint|Dav|0.15.0
vscode-eslint|dba|1.4.8
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.0.21
beautify|Hoo|1.3.0
reg|ion|0.0.2
docthis|joe|0.6.0
md-navigate|jri|0.0.1
pasteurl|kuk|0.3.11
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
csharp|ms-|1.14.0
PowerShell|ms-|1.7.0
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.3.0
material-icon-theme|PKi|3.3.0
stylelint|shi|0.36.0
sort-lines|Tyr|1.6.1
console|vil|0.0.6
change-case|wma|1.0.0
markdown-all-in-one|yzh|1.2.0

</details>

**Comment by SeanPrashad** [comment]
Hey @SylChamber - I'd love to give this a shot if it's still available?

**Comment by RMacfarlane** [comment]
Closing, as the column name no longer overlaps, though it still reads "% du processeur". The translations are not in this repo
