### ISSUE TITLE
Auto indent adding extra line after block comment

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#49217]
This is my main issue with auto indent in JS/TS and has almost driven me to disable it.

Type out a block comment and press enter twice gives this:

```
/**
 * 
 */

 
```

![image](https://user-images.githubusercontent.com/2193314/39637093-e36daaf4-4f76-11e8-9e5a-c7177a2fcaf7.png)

Would be great if this specific case could be handled.

**Comment by rebornix** [comment]
Duplicate #35709
