### ISSUE TITLE
Display diagnostic error codes

### ISSUE THREAD

**Issue by tboby** [Microsoft/vscode#49215]
**Would it be possible for the diagnostic error code to be surfaced to the user in some way?**

Diagnostics as defined in the [LSP](https://microsoft.github.io/language-server-protocol/specification#diagnostic) and [vscode-api](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Diagnostic) have a `code` field which is not easily visible to the user in vscode.  Language servers/compilers often allow the suppression of specific diagnostics by passing a list of error codes to ignore. Currently, as far as I know, extensions have to intercept LSP diagnostics and hardbake the code into error message, or incorrectly use the `source` field.

E.g:
![image](https://user-images.githubusercontent.com/447391/39634655-494b971e-4fb3-11e8-899b-f806494e8a38.png)
![image](https://user-images.githubusercontent.com/447391/39634128-da42a3ea-4fb1-11e8-9be2-826ecb36a69a.png)
Both of these solutions are less than ideal, as they mean that the raw "Copy" data is incorrect, and inconsistent across extensions.

It seems odd that `source`, a field that is generally obvious from context, is displayed, but there is no proper support for the `code` field.

I'm not sure what the best way of actually displaying it would be, but a few things come to mind:
1. Add it to the hover (as suggested by @egamma  in #44017 )
2. Display it together with the source
3. Display it instead of the source, and move the source to the end of the row

**Comment by tboby** [comment]
Neither of these issues are duplicate, although the second isn't far off, nice try!

**Comment by jrieken** [comment]
Yes, fair request. For the sake of completeness there is the hover, the f8-feature, and the error list. 

> It seems odd that source, a field that is generally obvious from context, is displayed,

The motivation for that is the presence of different validators, e.g. TypeScript for syntax/semantic checks and TSLint for linting. 

Adding @sandy081 for the errors list and for more feedback

**Comment by sandy081** [comment]
I think the current format `[${source}] ${message} (${line}, ${column})` is simple and clean. If we want to add code I would prefer to keep it before message, just like the example 1 in the description:

`[${source}] ${code}: ${message} (${line}, ${column})` ??

**Comment by egamma** [comment]
How about showing it at the end. The message is the most important part of a diagnostic and it would be good when it comes first. 


`[${source}] ${code}: ${message} (${line}, ${column})` ??

**Comment by mattacosta** [comment]
I'm also guilty of (mis)using the source field for error codes.

While I also agree that the message is the most important part, I would also say that the code is equal to or greater in importance than the source because it is useful for things like error suppression comments or looking up documentation (such as googling "c# error 1234"), while the source is only useful if someone has multiple extensions with non-obvious diagnostics. Therefore option 3 would seem to be the best fit, but option 2 would also be acceptable if it's too much of a change.

**Comment by sean-mcmanus** [comment]
The C/C++ extension is adding error/warning codes so that users can disable particular errors/warnings like VS 2017 has so we'd highly like VS Code to add this. In the mean time, how do you recommend we expose the error codes to users -- add it to the end of the message or show it in our Output window logs?

**Comment by sandy081** [comment]
How about showing error code at the end as @egamma mentioned

![image](https://user-images.githubusercontent.com/10746682/45808200-8aea7300-bcc5-11e8-8803-38a904eef271.png)

**Comment by jrieken** [comment]
Maybe not at the end-end but before the line/column info?

**Comment by tboby** [comment]
Oh, please prioritise it over message on narrow screens (like line numbers currently do)
![image](https://user-images.githubusercontent.com/447391/45809637-92f3e400-bcc0-11e8-81b6-01862603548a.png)


Also, having line/column as far right causes things to line up nicely!

**Comment by sandy081** [comment]
Before line numbers

![image](https://user-images.githubusercontent.com/10746682/45810521-14507400-bccb-11e8-9c04-e35843a59be4.png)

@tboby 

![image](https://user-images.githubusercontent.com/10746682/45810570-2f22e880-bccb-11e8-88b9-d2faba7e024e.png)

**Comment by egamma** [comment]
@sandy081 I´ve removed rendering of the `code` (the tslint ruleName) for tslint, but now the rule name no longer shows up in the hover. So the question is whether we should also show the code in the hover somehow.

![image](https://user-images.githubusercontent.com/172399/46724452-57728700-cc7a-11e8-965c-acc5d1510495.png)

**Comment by egamma** [comment]
@dbaeumer pls check whether you have the same issue of duplicate error code in eslint.

**Comment by cdeutsch** [comment]
Please bring back the name in the hover. If I need to disable a rule that's where I get the name from.

**Comment by sandy081** [comment]
Yes

**Comment by dbaeumer** [comment]
Removed it from ESLint and published new version for `^1.28`

**Comment by drKnoxy** [comment]
Hey i'm the maintainer of eslint-disable, any tips on how to get at the rule id so that we can disable rules again?

**Comment by dbaeumer** [comment]
@drKnoxy you might want to have a look at https://github.com/Microsoft/vscode-eslint/pull/530 which adds the as quick fixes to the extension directly.

**Comment by charpeni** [comment]
Starting from `vscode-eslint@1.28`, the easiest way to get eslint's rule id is to open the Problems window.

![image](https://user-images.githubusercontent.com/7189823/47860228-74583100-ddc6-11e8-9296-1a4f6f3845dc.png)

cc @cdeutsch @drKnoxy
