### ISSUE TITLE
organize imports does not use braces space setting

### ISSUE THREAD

**Issue by cainlevy** [Microsoft/vscode#49218]
Issue Type: <b>Bug</b>

With either or both of the following settings:

```
"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
```

Running organize still reformats with spaces:

```
import Foo, { Bar } from './Foo';
```

I would expect it to reformat without spaces:

```
import Foo, {Bar} from './Foo';
```

Related: https://github.com/Microsoft/vscode/issues/47654

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-docker|Pet|0.0.26
sort-lines|Tyr|1.6.1
solargraph|cas|0.16.0
tslint|eg2|1.0.28
vscode-styled-components|jpo|0.0.18
Go|luk|0.6.78
dotenv|mik|1.0.1
ruby-rubocop|mis|0.7.0
vsliveshare|ms-|0.3.51
Ruby|reb|0.18.0

</details>

**Comment by mjbvz** [comment]
Fixed by 04255d26e1a8639409db239ed4be66a9baa038a4
