### ISSUE TITLE
Can't open files in VS Code from Windows Explorer when an Admin instance is already running

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#4921]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

Open VS Code
In Explorer, double click a file that's associated with VS Code or right click and use "Open in Code".
Often, nothing happens unless I close the previous instance of Code. Sometimes, it works.

**Comment by bpasero** [comment]
@roblourens is the previous instance of Code healthy in that moment? Can you try to do the same from the command line like this:
* run code.exe --verbose for the first instance (from the directory where code is installed in program files)
* run code.exe --verbose for the second instance and pass it a file to open
* attach the output in case it fails

**Comment by roblourens** [comment]
I can run it twice from the command line, but after running it the first time, I can't open another instance by double-clicking a file or dragging a file onto the running instance. Sometimes it works but not always.

Here's the log, but nothing shows up when I double click another file.

```
E:\dv2\inetcore\devtoolbar\v4>"C:\Program Files (x86)\Microsoft VS Code\Code.exe" --verbose .

E:\dv2\inetcore\devtoolbar\v4>
### VSCode main.js ###
c:\Program Files (x86)\Microsoft VS Code\resources\app { pathArguments: [ 'E:\\dv2\\inetcore\\devtoolbar\\v4' ],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined,
  disablePlugins: false,
  locale: undefined }
Lifecycle#unload() 1
[6572:11528:0411/161230:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
[6572:11528:0411/161230:VERBOSE1:crash_service.cc(142)] window handle is 007211D8
[6572:11528:0411/161230:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at C:\Users\roblou\AppData\Local\Temp\edv2\VSCode Crashes
[6572:11528:0411/161230:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\roblou\AppData\Local\Temp\edv2\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[6572:11528:0411/161230:VERBOSE1:crash_service_main.cc(84)] Ready to process crash requests
[6572:10760:0411/161230:VERBOSE1:crash_service.cc(323)] client start. pid = 11044
[6572:10760:0411/161230:VERBOSE1:crash_service.cc(323)] client start. pid = 37716
[19640:12880:0411/161230:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
[19640:12880:0411/161230:VERBOSE1:crash_service.cc(142)] window handle is 00221392
[19640:12880:0411/161230:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at C:\Users\roblou\AppData\Local\Temp\edv2\VSCode Crashes
[19640:12880:0411/161230:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\roblou\AppData\Local\Temp\edv2\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[19640:12880:0411/161230:ERROR:crash_service.cc(301)] could not start dumper
IPC#vscode-workbenchLoaded
```

**Comment by roblourens** [comment]
More useful - opening the second instance from the command prompt

```
PS C:\Users\roblou\.vscode\extensions\vscode-webkit-debug> code .\testapp\ --verbose
PS C:\Users\roblou\.vscode\extensions\vscode-webkit-debug> & 'C:\Program Files (x86)\Microsoft VS Code\Code.exe' --verbo
se .\testapp\
PS C:\Users\roblou\.vscode\extensions\vscode-webkit-debug>
Error: connect EPERM \\.\pipe\Code-ec7481-sock
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
```

**Comment by roblourens** [comment]
@bpasero - Still reproes in 1.1.1, but now I can always launch a second one from the command line, but not from windows explorer. In task manager, I see a new Code.exe process appear, then disappear after a couple seconds, and no new Code window.

**Comment by joaomoreno** [comment]
I can't seem to reproduce. Is there anything special about your system? Corporate managed, for example?

The `EPERM` error indicates that it can't connect to the named pipe crated by the first instance. Rests to figure out whether that happens because it fails to connect or maybe the first instance drops the named pipe at some point.

If you keep trying repeatedly, it sometimes works, did I get that right?

**Comment by roblourens** [comment]
It's acting a little differently now from when I filed the bug, and I don't see that error anymore.

If I open the first Code instance from the command prompt, then I think I can always open a second one from the command prompt. But, if I try to open the second one from the file explorer, by double-clicking a file or using the context menu option, it doesn't work - I don't get a new instance of Code, and the file isn't opened in the existing instance.

But, if the first Code instance is opened from file explorer, then I can always open more instances from either the command prompt or file explorer with no problem.

So I think I just discovered a workaround - I can first open an instance from file explorer, and leave it open in the background. 

Anything I can do to help debug?

**Comment by roblourens** [comment]
And one more thing -

If I open the first instance from the command prompt, I can open a second instance from the *same* command prompt, but if I have a different cmd window open, I can't open a second instance from that different prompt.

**Comment by joaomoreno** [comment]
Some other user found out he's using an elevated prompt in #6137, is this your situation too?

**Comment by roblourens** [comment]
Oh yeah, I am. Should have realized that would be significant. So if the first one is opened as administrator, I can't open another from a not-admin window.

**Comment by Tadimsky** [comment]
Haha, sounds familiar. Look at our user tags "Microsoft member" :)

**Comment by bpasero** [comment]
We gotta fix this...

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/6560

**Comment by joaomoreno** [comment]
#1614

**Comment by fjsuarez** [comment]
I'm running VSCode Insiders v1.15-0-insider and I'm still experiencing this issue:
Steps to reproduce:

- Open a folder from an elevated command prompt with `code-insiders path\to\folder\`
- Try to open a text file from the context menu (Right click on file > Open with Code Insiders)

File does not open, neither on the existing window or a new one.
