### ISSUE TITLE
editor.tabSize seems not work

### ISSUE THREAD

**Issue by DRL9** [Microsoft/vscode#49221]
Issue Type: <b>Bug</b>

1. open workspace settings
2. set `tabSize:2`
3. open a javascript file (tabsize is 4), press `alt+shift+f` to format

expect: the tabSize become 2.
result: the tabSize is still 4.

This bug appeared after I updated to 1.23.0

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 3119)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.92GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by rebornix** [comment]
@mjbvz does ts formatter take tabSize into account?

**Comment by mjbvz** [comment]
Yes we do use the tabsize for formatting. The problem is that VS Code tells us that the tab size for the current editor is still four. I believe this is the same problem / question as #48440

Try setting:

```
"editor.detectIndentation": false,
"editor.tabSize": 2
```

To force a tabsize of 2

**Comment by DRL9** [comment]
>Try setting:
>```
>"editor.detectIndentation": false,
>"editor.tabSize": 2 
>```
It works for me. Thanks.
