### ISSUE TITLE
Windows key omitted from menu shortcut hint

### ISSUE THREAD

**Issue by AHelper** [Microsoft/vscode#49225]
- VSCode Version: 1.23.0
- OS Version: Win7-x64, fc23-x64

Steps to Reproduce:

Right-click in a TS file, observe the shortcut for `Refactor...`
![1](https://user-images.githubusercontent.com/2072395/39638833-1ab52e86-4f8d-11e8-944c-b93eaf57bf80.png)

Uh...? This reads as: Press Shift+R, and you refactor.  That seems... conflicting...
![2](https://user-images.githubusercontent.com/2072395/39638841-1eae9ad6-4f8d-11e8-9672-01fe68f35d05.png)

Ah, it seems the "Windows" key doesn't show up in shortcut hints in menus.  I'd recommend mapping it to "Win", such as "Shift+Win+R".

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
We should be using ctrl here, not the windows key
