### ISSUE TITLE
Organize imports not respecting new line as separator of import groups

### ISSUE THREAD

**Issue by sillero** [Microsoft/vscode#49229]
Issue Type: <b>Bug</b>

1. Activate `organizeImports`
2. Use new line to group imports like this:
```
import c from './c';
import b from './b';
import f from './f';

import d from './d';
import a from './a';
import e from './e';
```
3. Save file
4. Output
```
import a from './a';
import b from './b';
import c from './c';
import d from './d';
import e from './e';
import f from './f';
```
5. Expected:
```
import b from './b';
import c from './c';
import f from './f';

import a from './a';
import d from './d';
import e from './e';
```

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1417562|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
material-icon-theme|PKi|3.3.0
vscode-docker|Pet|0.0.26
sort-lines|Tyr|1.6.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
mustache|daw|1.1.1
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.4
ts-tslint|eg2|0.0.4
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
autorun|kri|1.0.0
vscode-language-babel|mgm|0.0.14
python|ms-|2018.4.0
cpptools|ms-|0.16.1
vscode-coffeelint|slb|0.0.2
vscode-npm-scripts|tra|0.2.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is by-design. We sort all imports into a single block

Other extensions may offer for more advanced options like preserving groups
