### ISSUE TITLE
Linux .deb does not install without running apt-get update on terminal first

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#4922]
- VSCode Version: 0.10.13-insider
- OS Version: Ubuntu 14.04 LTS

The ".deb" package may not install if a user hasn't already run the command `apt-get update` on the terminal before opening the package and doesn't already have Git installed.  While most experienced Linux users will run this command frequently, I don't think we should count on everyone knowing this—even they may not know what's causing this.  At a minimum we should give a hint "Hint: did you run `apt-get update` on the terminal before installing this package?".  However, it would be even nicer if we could do this for them.

Steps to Reproduce:

1. Go to http://code.visualstudio.com/Download?insiders=true
2. Download the ".deb" version
3. Open it and attempt to install it in the "Ubuntu Software Center"
4. You will be told that the software installer cannot install two packages (the Git manual and Git 1.9), and the installation will fail for VS Code.

**Comment by Tyriar** [comment]
@bgashler1 this is happening because git is listed as a dependency. Personally I think the off chance of `git` not being available to `apt-get` before an update if preferable to git integration not working out of the box.

I thought git came pre-installed on Ubuntu 14.04?

**Comment by borgdylan** [comment]
I would recommend installing GDebi first and using that as a deb installer. It will grab all dependencies automatically. http://packages.ubuntu.com/wily/gdebi or http://packages.ubuntu.com/wily/gdebi-kde for KDE users .

**Comment by borgdylan** [comment]
@Tyriar git is never pre-installed on ubuntu.

**Comment by Tyriar** [comment]
Closing this off as per my last comment.
