### ISSUE TITLE
Error maximized window

### ISSUE THREAD

**Issue by kaaf030191** [Microsoft/vscode#49220]
Issue Type: <b>Bug</b>

When maximized window appear section white in bottom up the text code.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (4.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.12
mapfile|chi|0.0.1
githistory|don|0.4.0
php-debug|fel|1.12.3
dotenv|mik|1.0.1
mssql|ms-|1.3.1
debugger-for-chrome|msj|4.3.0
laravel-blade|one|1.18.0
sass-indented|rob|1.4.9
sensitive-replace|vil|0.1.1

</details>

**Comment by bpasero** [comment]
@kaaf030191 screenshot?
