### ISSUE TITLE
After upgrade plugins is not working

### ISSUE THREAD

**Issue by arte0s** [Microsoft/vscode#49226]
Issue Type: <b>Bug</b>

After upgrade VS Code Beautify and CodeOutline plugins is not working.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.46GB (2.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-code-outline|pat|0.1.1

</details>

**Comment by rebornix** [comment]
Please file issues against the extensions you are using, thanks!

**Comment by arte0s** [comment]
However solution was in VS Code: I cleared localStorage in Dev Tools and now both of plugins are working.
