### ISSUE TITLE
High CPU usage "Looking for CSS classes" after update

### ISSUE THREAD

**Issue by pelted** [Microsoft/vscode#49228]
- VSCode Version: April 2018 (version 1.23)
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Load a project or reload the workspace window

Does this issue occur when all extensions are disabled?: Confirmed it does not

After the 1.23 update I'm seeing excessive CPU usage for the first couple of minutes during "Looking for CSS classes in the workspace." Prior to the update this was not an issue. No additional extensions were added, so it seems something related to recent changes.

**Comment by rebornix** [comment]
> Does this issue occur when all extensions are disabled?: Some

Can you elaborate more on this? I would expect a yes or not answer to determine whether it's a VSCode issue or an extension one, thanks!

**Comment by pelted** [comment]
Okay, it looks like it is extensions related. I had the command line command to do so wrong. Now I guess it's narrowing it down. It is related to this extension: [zignd/HTML-CSS-Class-Completion](https://github.com/Zignd/HTML-CSS-Class-Completion) I will post issue there, but this problem did not occur until right after I installed the April update.
