### ISSUE TITLE
Editor "Find" panel keybinding is overridden

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#49231]
- VSCode Version: 1.23.0
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Hit Cmd + F to show the "Find" panel.
2. Hit Cmd + Option + R to toggle the regex mode.
3. This almost always opens Finder for the current directory. Sometimes it works correctly, but I haven't been able to determine what steps modify the behaviour.

This is me doing the above steps:

![vsc](https://user-images.githubusercontent.com/50314/39641455-33397dc2-4f9c-11e8-835e-ce5309e0cc05.gif)

I also noticed that Cmd + Option + C, which should toggle case, does nothing. Cmd + Option + W, to toggle whole words, works.

My keybindings: https://gist.github.com/atombender/d61bb4d54d6abca9ebb2a1c9f25c58d0

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Reveal File in OS checks if the editor is focused `editorTextFocus`, which is false when the find widget is focused. We need to check if editor internal widgets are focused or not.

**Comment by atombender** [comment]
Super, thanks!

**Comment by isidorn** [comment]
@rebornix thanks for fixing this!

**Comment by atombender** [comment]
@rebornix I think the same fix is needed for Cmd + Option + C.

**Comment by isidorn** [comment]
@atombender that is already fixed here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L436
