### ISSUE TITLE
Markdown link provider misses link for image

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#49238]
Steps to Reproduce:

1. For the markdown:

```md
[![a](b)](c)

```

**Bug**
Only `b` is detected as a clickable link.

**Comment by flurmbo** [comment]
Hey @mjbvz can I try working on this one?

**Comment by mjbvz** [comment]
Sure, here's the relevant regular expression that matches links: https://github.com/microsoft/vscode/blob/32d22dbace8f2deed5dfb44e19f813f76ff1d0f0/extensions/markdown-language-features/src/features/documentLinkProvider.ts#L54

And the related tests:

https://github.com/microsoft/vscode/blob/6d31c16989acb4eb61ba04e66047ef50b67a2ebc/extensions/markdown-language-features/src/test/documentLinkProvider.test.ts#L1

You can run the tests by opening VS Code and selecting the `Markdown Extension Tests` from the debug target menu.

The regexp is rather complex so let me know if you have any questions

**Comment by gsunit** [comment]
@mjbvz Could you please tell me what is the expected behaviour?

**Comment by mjbvz** [comment]
In the example, it should underline `b` and `c` as clickable links that open files `b.md` and `c.md`
