### ISSUE TITLE
Intellisense not as described [js]

### ISSUE THREAD

**Issue by Galaen** [Microsoft/vscode#4924]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. open an empty JS file.
2. write some unknown variable like "globalVar".
3. [ In this video](https://channel9.msdn.com/events/JavaScript-Webinar-Series/Visual-Studio-Code-for-Angular-developers/Visual-Studio-Code-for-Angular-developers) (around 0:20:30) I can see it should have some kind of green squiggles (for warnings) but I don't have them and cannot add definition like he does.

I do not have any extension installed. I thought this was something that worked by default.
I tried to add a jsconfig.json but with no more result

Is this a bug ? A change ? or linked to my environment ?

**Comment by egamma** [comment]
It is a change, sorry. The recommendation is to use eslint and the vscode-eslint extension to get JS diagnostics. Pls see https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/vFebruary.md#linters.
