### ISSUE TITLE
Expose search.action.refreshSearchResults

### ISSUE THREAD

**Issue by tomzx** [Microsoft/vscode#49248]
v1.23.0

This was initially asked in #23558.

#23558 listed refresh, collapse all and clear. In the keyboards bindings, one can access `search.action.collapseSearchResults` and `search.action.clearSearchResults` but not `search.action.refreshSearchResults`.

![code_2018-05-04_16-38-01](https://user-images.githubusercontent.com/188960/39651875-90cd6972-4fb9-11e8-9dc7-0e3a0b16d000.png)

I'm currently trying to write an extension that would automatically start a search with a given word. At the moment I'm able to get the search sidebar to show and to clear the current search, but I cannot execute/run the search.

**Comment by roblourens** [comment]
I think 'refresh' isn't what you want exactly because it's only enabled when there are already results in the view. You want to be able to start a search, which doesn't have a command behind it currently.

I don't really want to add commands for extensions to basically automate the vscode UI like this, it doesn't feel like something that a vscode extension should be doing. What's your scenario?

**Comment by tomzx** [comment]
My current code uses `DocumentLinkProvider` to generate clickable ranges that are then sent to the VS Code search engine. It's basically your poor man's [peek](https://code.visualstudio.com/docs/editor/editingevolved#_peek). Basically all there is left at this point is for the search to trigger. At the moment the user will have to type enter to finish this process.

I might be wrong, but at the moment every extension has to implement itself how it searches through files. Given there is already some facility in VS Code to search, it seems to make sense to make use of that.

**Comment by roblourens** [comment]
Ok, I don't think this is a good fit for extensions.

> Also, I foresee that future versions of VS Code may provide better search support for files provided by the FileSystemProvider than by implementing something that expects files always exist on the current file system.

If that's your end goal, then yes. You can follow https://github.com/Microsoft/vscode/issues/47058 for that exact issue.
