### ISSUE TITLE
New Feature: Need to jump forward/backward while debugging

### ISSUE THREAD

**Issue by muthursyamburi** [Microsoft/vscode#49240]
- VSCode Version: 1.16.1
- OS Version: Windows 7

This is a new feature request rather than a bug reporting. I really really wish to see an option in the debug, which will help me to jump forward/backward while I am in any line. Say I am in line#12. If I wanted to skip few lines below and wanted to go to line# 15, I should be able to do that. Also, if I wanted to jump back to line# 6, with out any issues, I should be able simple go to that line and say "move the debug line to this". This is independent of any language. And I believe the debugging stuff is kind of a factory class as its UI looks to be the same with Java code, Python, NodeJS, C++ etc. So I believe, if you enable this feature to the base class of the debug, it will be available to all languages and there could be few more changes needed additionally in the implementation part of it. I haven't gone through the source code, just was thinking aloud.

This is very effectively done in Eclipse debugging, while that really lacks in the JetBrains editors (WebStorm, Intellij IDEA etc).

Please bring this feature. Its a must for a developer.

 
Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
You can always go forward by a context menu -> "Run to Cursor". Or via F1 > Run to Cursor.
Going backwards has to be supported by particular debuggers and is for instance supported in the Chakra debugger.
As an alternative you can use the "Restart Frame" function which is available for node in the call stack.

Bottom line, go forward you have, go backwad has to be implemented by each extension and you can file feature requests against them.

**Comment by muthursyamburi** [comment]
RE: jumping forward. I am aware of the "Run to Cursor" functionality which will run all the intermediate commands before reaching to the line under the cursor, while I am talking about "jumping" to the specific line by skipping all the intermediate instances. That is the feature I am looking for which is available in Eclipse very easily.

For jumping backward, thanks to let me know that it should be handled by the extension. I will talk to them separately.

Request you to please not close this request until the "jumping" forward functionality is implemented. Please let me know if you need more clarifications for what I am really requesting for.

**Comment by isidorn** [comment]
Skipping intermidiate lines would also have to be supported by each debug adapter specifcly so please also file that as a feature request to extensions.
Thanks
