### ISSUE TITLE
Should "Display Language" be added to the Preferences menu?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#49245]
File > Preferences > Display Language would fit with the other customizations such as theme and keyboard shortcuts.

**Comment by dbaeumer** [comment]
WE discussed this ~ one year ago and then decided not to add it since usually the display language is picked up from the OS. I will keep the item around again to see if it gains more traction this time.

**Comment by gregvanl** [comment]
No seeing customer comments through doc feedback. Closing for bug push.
