### ISSUE TITLE
Toggle auto-format on save per-language

### ISSUE THREAD

**Issue by ecraig12345** [Microsoft/vscode#49246]
It would be nice there was a way to enable or disable auto-format on save per-language. For example:

```json
{
  "editor.formatOnSave": true,
  "editor.formatOnSave.disableForLanguages": ["css"]
}
```
or the opposite:
```json
{
  "editor.formatOnSave": false,
  "editor.formatOnSave.enableForLanguages": ["typescript"]
}
```

My specific use case:

- In general, I want to auto-format on save for languages such as TypeScript that have decent formatters (whose style I agree with)
- For some languages, such as SCSS and CSS, I haven't found a formatter whose style agrees with mine, so I don't want to always auto-format on save in those languages.
- BUT in those same languages, sometimes I'm looking at some code with absolutely no formatting (for example, blob of CSS styles copied from browser debugger), and any formatting style is preferable to the total lack of formatting.

In the last case, I have to enable an extension, format my code, and then re-disable the extension, which is kind of a pain.

(If someone can point me to the right place, I might be interested in implementing this. Also, apologies if this has been requested already--tried to search but may not have used the right terms.)

**Comment by mjbvz** [comment]
This is already be possible using [language specific settings](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings):

```md
"[typescript]": {
     "editor.formatOnSave": true
}
```

The language specific setting override the generic, top level settings. You can use this to either enable format on save for specific language or disable it for specific languages

**Comment by ecraig12345** [comment]
Got it, thank you! Somehow missed that there were language-specific settings.
