### ISSUE TITLE
scripts starting with "pre" or "post" are not shown in the new npm scripts explorer

### ISSUE THREAD

**Issue by xaviergonz** [Microsoft/vscode#49249]
- VSCode Version: 1.23.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. create a project with a package.json
2. add a script with a name that starts with "pre", such as "prettier-all", or "post" such as "postman"
3. it won't be shown

Does this issue occur when all extensions are disabled?: N/A

**Comment by egamma** [comment]
@xaviergonz the setting `npm.includeDirectories` is from this extension https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script and it is not supported by the bundled npm extension. This extension only supports `npm.exclude`.

However, I´m not able to reproduce the behaviour you are describing, please see the screenshots below. Can you please provide more details about your setup.

![image](https://user-images.githubusercontent.com/172399/39693082-198f4c3c-51e3-11e8-9a71-8c4880b132b0.png)

**Comment by xaviergonz** [comment]
Thanks for the tips!
I found the issue
my script is called "prettier-all", but apparently the script explorer doesn't show anything that starts with "pre"
if I change the script name to "pettier-all" then it shows.
I will rename the issue accordigly.

**Comment by egamma** [comment]
Filtering of pre/post scripts makes sense since these scripts are run as part of other scripts, but it needs to be done in smarter way than just based on the prefix to handle the case raised by this issue.

**Comment by xaviergonz** [comment]
Maybe it could do something like this?
hide = script starts with "pre" or "post" && script without "pre" or "post" exists

e.g.
preview, [ preview ] -> true (starts with pre) && false (view does not exist) -> false, preview not hidden
preview, [ preview, view ] -> true (starts with pre) && true (view does exist) -> true, preview is hidden
postview, [ postview, view ] -> true (starts with post) && true (view does exist) -> true, postview is hidden

**Comment by egamma** [comment]
@xaviergonz I have implemented along the lines you have suggested https://github.com/Microsoft/vscode/blob/4f652fc36ca63c5b730fdc6ff9973eb56110ec7b/extensions/npm/src/tasks.ts#L49.
