### ISSUE TITLE
workbench.action.terminal.clear does not clear terminal output

### ISSUE THREAD

**Issue by nathagey** [Microsoft/vscode#49241]
- VSCode Version: 1.23.0
- OS Version: macOS v10.13.4 

Steps to Reproduce:

1. Start an NPM script in terminal that stays open, and has terminal output.
2. Focus on the terminal window.
3. Use default `⌘ + K` keyboard shortcut to clear terminal output.
4. `^L` shows up at the end of the output, and terminal does not clear.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/49162
