### ISSUE TITLE
Ctrl Click (Cmd Click on mac) on require does not follow JSON

### ISSUE THREAD

**Issue by brocoli** [Microsoft/vscode#49250]
- VSCode Version: 1.23.0 / 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
- OS Version: macOS High Sierra 10.13.4 (17E199)

Steps to Reproduce:

1. Start from blank project / folder
2. Create a json file `foo.json` with any valid json content
3. Create a js file `bar.js` with the following code
```javascript
module.exports = {}
```
4. Create a js file "index.js" with the following code and open it
```javascript
const foo = require('./foo');
const other = require('./bar');
```
5. Try Ctrl Click on `foo`. It won't work
6. To demonstrate that Ctrl Click in general is still working, try Ctrl Click on `bar`. VS Code will jump to the file `bar.js`
7. *(NB: if you remove `module.exports = {}` from `bar.js`, VS Code can't jump to it either)*

Does this issue occur when all extensions are disabled?: Yes

### Expected behaviour:

VS Code should jump to a file when Ctrl Clicking any path-like string literal, as long as the file the path points to exists.

For instance, we use a package called `rewire` for testing that provides a `rewire('./path/to/file')` function that `require`s the module, but changing `const`s to `let`s, and allowing us to change the module's contents with stubs and mocks. If VS Code only jumps to file when the string literal is inside a `require` call or an `import` statement, it will never be able to jump to a `rewire`d file.

But even still, just not failing to jump to JSON would be a big improvement. Our test code has lots of `require`s to testing fixtures, and since we want to ensure those are serialisable data, we use JSON files for them.

**Comment by mjbvz** [comment]
In VS Code 1.24 (current insiders build), we can resolve json files. To enable this, you need to add `resolveJsonModule` to your `jsconfig` or `tsconfig`:

```json
{
  "compilerOptions": {
    "resolveJsonModule": true
  }
}
```

At the moment though, imported json files must have `.json` file extension. See https://github.com/Microsoft/TypeScript/issues/24357

Supporting cases like rewrite is our of scope but could be provided by an extension or a typescript server plugin

**Comment by mjbvz** [comment]
Note to verifier: 

* make sure you have a `jsconfig.json`:

```json
{
  "compilerOptions": {
    "resolveJsonModule": true
  }
}
```

* And use the import `const foo = require('./foo.json');`
