### ISSUE TITLE
Disable Lightbulb and 3 Notification Dots Are Still There

### ISSUE THREAD

**Issue by rag4214** [Microsoft/vscode#49253]
I am doing a bit of Discord Node.js development, and VSCode keeps wanting me to change my `.require()` statements into ES6 `import` with the 3 little dots and lightbulb. This was annoying to me, so I decided to disable it. However, the 3 little notification dots under one of my require statements are still there, despite the lightbulb being disabled. 
(Before)
![screen shot 2018-05-04 at 10 48 37 pm](https://user-images.githubusercontent.com/35985028/39659025-6bd17990-4fed-11e8-99e3-b22ba2aebefd.png)
(After)
![screen shot 2018-05-04 at 10 48 53 pm](https://user-images.githubusercontent.com/35985028/39659026-727a7d6e-4fed-11e8-9879-98b08353c94e.png)
![screen shot 2018-05-04 at 10 52 12 pm](https://user-images.githubusercontent.com/35985028/39659049-d88bb488-4fed-11e8-97d8-0843877fcb41.png)

- VSCode Version: 1.23.0
- OS Version: 10.13.4

Steps to Reproduce:

1. Change preferences to disable editor lightbulb
2. 3 notification dots are still present

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Set `"javascript.suggestionActions.enabled": false`
