### ISSUE TITLE
Feature Request: Sign In option

### ISSUE THREAD

**Issue by manoj1991** [Microsoft/vscode#49256]
I would like to have a Sign In option in VS Code because when I use VS Code on a different machine I'm unable to get the customizations and extensions that I have got on my machine's VS Code. The Sign In options should be same as Google Chrome where the user Sign's In and gets all the extensions and customizations on that respective machine.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2743
