### ISSUE TITLE
Update to workspace folder settings does not work

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#49258]
Issue Type: <b>Bug</b>

This is very similar to a previously reported issue https://github.com/Microsoft/vscode/issues/36448
Unfortunately we (Python Extension) didn't catch this bug as our CI tests run against the stable versions of VS Code and we released our extension a day before VSC. Once a new version of VS Code was released our CI tests started to fail.

In light of this issue we'll consider either running our tests against VSC insiders or releasing after VSC (TBD).

**Here are the steps to replicate the issue:**

* Use VSC Insiders or **latest stable version (Version 1.23.0)**
* Create a multiroot workspace folder name `workspace1`
* Create workspace settings file with the setting `editor.autoIndent = false`
* Create a workspace folder settings file with the same settings
* Execute the following code inside VS Code (via an extension)
* You'll see that the last update fails, expected value is `false`, but we get true.
* Note, uncommenting the `setTimeout` (delay) will get around this issue. (same as #36448)

```typescript
        const workspaceUri = Uri.file('full path to workspace1');

        let settings = workspace.getConfiguration('editor', workspaceUri);
        await settings.update('autoIndent', false, ConfigurationTarget.Workspace);
        settings = workspace.getConfiguration('editor', workspaceUri);
        await settings.update('autoIndent', true, ConfigurationTarget.WorkspaceFolder);

        settings = workspace.getConfiguration('editor', workspaceUri);
        console.log(`editor.autoIndent is ${settings.get('autoIndent')}, and expected true`);

        settings = workspace.getConfiguration('editor', workspaceUri);
        await settings.update('autoIndent', true, ConfigurationTarget.Workspace);
        settings = workspace.getConfiguration('editor', workspaceUri);
        await settings.update('autoIndent', false, ConfigurationTarget.WorkspaceFolder);

        // Trick, place a delay and the values get loaded
        // await new Promise(resolve => setTimeout(resolve, 2000))

        settings = workspace.getConfiguration('editor', workspaceUri);
        console.log(`editor.autoIndent is ${settings.get('autoIndent')}, and expected false`);
```

VS Code version: Code - Insiders 1.24.0-insider (2404210629c744e6237a14d7b5fa852e24c6e898, 2018-05-04T08:05:15.549Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_21140520|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
xml|Dot|1.9.2
gc-virtualdocumentspy|Gra|1.0.1
vscode-docker|Pet|0.0.26
application-insights|Vis|0.4.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
gitlens|eam|8.2.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
docthis|joe|0.6.0
Go|ms-|0.6.79
MagicPython|mag|1.0.12
dotenv|mik|1.0.1
extension-manifest-editor|ms-|0.1.5
python|ms-|2018.5.0-alpha
vsliveshare|ms-|0.3.93
debugger-for-chrome|msj|4.4.1
autodocstring|njp|0.2.1
typescript-hero|rbb|2.3.2
vscode-yaml|red|0.0.11
vscode-icons|rob|7.23.0
cython|tcw|0.1.0
jinja|who|0.0.8

</details>

**Comment by SchoofsKelvin** [comment]
I have a similar issue, also in VSCode 1.23.0, but in my case, updating the global settings seems to have no effect until a reload or until workspace settings are changed:

* The global setting 'sshfs.configs' looks something like this:
```json
"sshfs.configs": [
	{
		"root": "/var/www",
		"putty": "server2",
		"label": "My 2nd server",
		"name": "server2"
	}
]
```
* The Workspace setting also looks that way. If the setting is missing there, the bug doesn't happen
* I change that array (adding/modifying/removing entries) either using the editor, `.update()` or both
*(Code-wise, I update using `vscode.ConfigurationTarget.Global` as third parameter)*
* `getConfiguration('sshfs').inspect('configs')` keeps returning the old values
* Only when I reload the window **or change the Workspace settings** does it update
*(as in, `.inspect('configs').globalValue` now returns the updated settings)*
(somehow changing the Workspace settings busts the "global settings cache")
* At this point, changing the global settings has again no effect until the above step is repeated

________

Both tested with and without any extensions (including built-in ones)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (0.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\schoo_000\Workspaces\NPM\NPM.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>
