### ISSUE TITLE
Cannot install Azure Resource manager tools on VS code running on Mac OSX

### ISSUE THREAD

**Issue by andyzhu** [Microsoft/vscode#4925]
- VSCode Version: 0.10.11
- OS Version: Mac OSX 10.11.4

Steps to Reproduce:

1. ext install azurerm-vscode-tools
2. the VS code displayed "No commands matching"

**Comment by egamma** [comment]
Works for me:
![image](https://cloud.githubusercontent.com/assets/172399/14504943/3cf12584-01b7-11e6-9872-ab80a1669f00.png)

I suspect entered `>ext install azure`?

![image](https://cloud.githubusercontent.com/assets/172399/14504890/f93e9fba-01b6-11e6-9900-2ee2485a4ad0.png)
