### ISSUE TITLE
Microsoft SQL tool service layer process causes high ram usage

### ISSUE THREAD

**Issue by DucNguyenPTIT** [Microsoft/vscode#49254]
The Microsoft SQL tool service layer keeps exceedingly eats up my ram, sometimes up to 5GB. At first, I think it was because of openning SQL file. But later, I found out that it happens no matter which file is opened. It got my system hanged until I killed the process.  It was the Microsoft mssql extension, but this kind of thing has never happened before. This happened the first time after updating VSCode to v1.23.

**Comment by rebornix** [comment]
Please file issue against the SQL tool you are using, thanks ;)
