### ISSUE TITLE
can't install debugger for chrome anyway. 

### ISSUE THREAD

**Issue by pjj1214** [Microsoft/vscode#49267]
Issue Type: <b>Bug</b>

can't install debugger for chrome anyway. 

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
open-html-in-browser|cod|0.1.21
vscode-eslint|dba|1.4.8
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
code-beautifier|mic|2.0.3
vscode-language-pack-zh-hans|MS-|1.23.3
vscode-css-peek|pra|2.1.0
background|sha|1.1.17

(1 theme extensions excluded)

</details>

**Comment by YegorK** [comment]
Updates successfully on my latest MacOS, but is stuck on latest Windows 10 and Windows Server 2k16 machines.

**Comment by carm960** [comment]
The same for me, Vs Code ver: 1.23.0 - Windows 10
Debugger for Chrome can't complete installation.

**Comment by roblourens** [comment]
It should be fixed now, please try again.
