### ISSUE TITLE
cpu占用率很高！

### ISSUE THREAD

**Issue by jinxiuxue** [Microsoft/vscode#49264]
Issue Type: <b>Bug</b>

cpu占用率很高！

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.84GB (10.92GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
vscode-html-css|ecm|0.2.0
vscode-less|mrm|0.6.3
vetur|oct|0.11.7

</details>

**Comment by rebornix** [comment]
Please provide detailed information otherwise we can't help troubleshoot.
