### ISSUE TITLE
setBreakPointsRequest no longer called in my debug adapter

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#49266]
Issue Type: <b>Bug</b>

This used to work until the April 2018 update came in today. In my extension [vscode-antlr4](https://github.com/mike-lischke/vscode-antlr4) I implemented a debug adapter, which supports break point requests. Now when I start debugging an ANTLR4 grammar the launch request is sent, but not the `setBreakPointsRequest`, which of course disables any real debugging activity. I haven't changed anything in my code (it stopped working even for the installed extension). vscode suggested to change the `Languages` category to `Programming Languages`, but that didn't make a difference.

I read the release notes to see if something changed related to that issue, but couldn't find anything obvious.

To reproduce, install my extension, get an ANTLR4 grammar (e.g. [this one for csv data](https://github.com/antlr/grammars-v4/blob/master/csv/CSV.g4)) and open it in vscode. Now set a breakpoint on a line without any code. When successful this breakpoint should be disabled. Start debugging with a launch config like this:

```
{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "Current Grammar",
            "type": "antlr-debug",
            "request": "launch",
            "input": "input.txt",
            "startRule": "csvFile",
            "printParseTree": true,
            "visualParseTree": false
        }
    ]
}
```

while the grammar file is active in vscode. If it complains about not finding input.txt, create a dummy file.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (13.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.3.0
dot|Ste|0.0.1
numbered-bookmarks|ale|0.11.1
spellright|ban|2.3.3
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
duk-debug|des|0.4.2
tslint|eg2|1.0.28
php-intellisense|fel|2.3.1
live-html-previewer|hdg|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
svg|joc|0.1.0
vscode-phpfmt|kok|1.0.21
vscode-antlr4|mik|2.0.3
prettify-json|moh|0.0.3
vscode-yacc|se2|1.1.0

</details>

**Comment by isidorn** [comment]
@mike-lischke I followed your exact steps and I see the `setBreakpoints` request being sent out.
Can you also reproduce this with the latest vscode insiders?
Also when I debug following your steps I get the error from your adapterin the debug console, however that might be unrelated since I see the breakpoints being sent out.

Please note that I was doing this on a mac and using vscode insiders.
Also are you sure your adapter is nicely sending the initialized event since sending breakpoints is dependent on that.

```
Parser error (1, 1): mismatched input '<EOF>' expecting {',', '\r', '\n'}
<unknown>:1
Parse Tree:
csvFile (
 hdr (
  row (
   field    <Error>"<EOF>"
  )
 )
 row (
  field   <Error>"<EOF>"
 )
)
```

**Comment by mike-lischke** [comment]
I tried with the latest insiders build and see the same effect (no extensions installed, just open my extension and start debugging, then open my test folder with the grammar and start grammar debugging in the extension host). I'm also on a Mac.

The [initialize event is sent](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/frontend/AntlrDebugAdapter.ts#L67) and I doubled checked that I used the code as is on Github.

But as I wrote already, I haven't changed anything. I updated vscode and that started to fail. Is it possible to return to a previous release of vscode?

**Comment by isidorn** [comment]
@mike-lischke no we do not support reverting to a previous release of vscode.
Since I can not reproduce this issue you could try to debug it on your side
1. F1 > open developer tools
2. Put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L299)
3. Try to figure out why the breakpoints are not being sent from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L1248)

Thanks

**Comment by mike-lischke** [comment]
@isidorn Thanks a lot for pointing me to the right direction. Once I debugged that code also my `setBreakPointsRequest` started to work again (don't ask me why suddenly) and I could find the true culprit for my debug problem. And that showed me a workflow problem in the debug adapter setup.

In order to set a break point I need my debugger backend set up. To set this up I need the file being debugged. That file (name) is passed in as launch request parameter and I can create the backend. However, sending the `InitializedEvent` in the launch request has not the desired effect, because now the debugger is started before the breakpoints are set. I need to send this event in the `initializeRequest` call, but that doesn't have the launch parameter with the file I need for my debugger backend. Catch 22. Can I somehow force the initialize event to be handled before `launchRequest` returns? Or what else could I do here?

**Comment by weinand** [comment]
@mike-lischke I think you are running into a very common issue: your DA can only handle `setBreakpointRequests` late (in the `launchRequest`), but you need to receive them all before starting your backend. 
The best way to solve this is by waiting for the `configurationDoneRequest` in your `launchRequest`. mock-debug shows how you can do this easily:
https://github.com/Microsoft/vscode-mock-debug/blob/8da8a32a80a151acd7910bf04190d12f0f04a6cd/src/mockDebug.ts#L111-L134

**Comment by isidorn** [comment]
@weinand thanks for jumping in
@mike-lischke let us know if that fixes the problem for you so we can close this issue

**Comment by mike-lischke** [comment]
Thank you @weinand. It works again and my mistake is also corrected. Something new learned.

I much appreciate your great support here!
