### ISSUE TITLE
Language packs doesn't activate/deactivate after a reload

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode#49262]
- VSCode Version: 1.23.0
- OS Version: Windows 10 Version 1803

Steps to Reproduce:

1. Install a language pack (the German one for example)
2. Click the "reload" button in the extensions UI

Everything looks like before but after I restart VS Code completely some translations are different.

The same issue occurs when uninstalling a language pack. After the reload the translations of the language pack stay. Only after a full restart they are switching back to the bundled ones.

Maybe this issue is #44501? I'm not sure though.

**Comment by dbaeumer** [comment]
It is a dup of #44501
