### ISSUE TITLE
Multi-root Workspaces Untitled

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#49260]
Workspaces one-root displays the current folder name;
And Multi-root Workspaces shows untitled;
Can rename Workspaces, or show Workspaces directly, remove the current folder name；

Workspaces plus name seems to be an extra one, please direct（as shown below）
 show Workspaces directly:
![tim 20180505162740](https://user-images.githubusercontent.com/20437381/39661269-477a6ad6-5081-11e8-9e9c-cc45991a73f8.png)

**Comment by lihua06** [comment]
"can assign a name property to each root folder in the workspace file"

Does not solve my problem, it still shows untitled

**Comment by lihua06** [comment]
Modifying the source language file has solved this problem。

**Comment by bpasero** [comment]
In order to get rid of "Untitled Workspace", just save it (File > Save Workspace As).
