### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by ShiinaHikari** [Microsoft/vscode#49265]
- VSCode Version:1.23.0
- OS Version:Ubuntu 18.04 LTS

Steps to Reproduce:

1.Install .deb file
2.run code and  it can't launch
3.delete /home/username/.config/Code .This time vscode can launch
4.Install extension,and vscode is always display installing......

Does this issue occur when all extensions are disabled?: Yes/No
My issue is about extension :(

**Comment by ShiinaHikari** [comment]
Ues tar.gz,extension problem also exist :(
Ues sudo run vscode,problem solved
But I think it's not a good way to solve it,and vscode also don't recommend to run it with root
Please fix it

**Comment by sandy081** [comment]
@ShiinaHikari Can you please set the log level to `trace` using `Set Log Level` command and provide us the shared process logs from the Output panel?
