### ISSUE TITLE
Typing #ID in CSS opens up colours intellisense

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#49269]
When I'm typing an id using # character in my CSS file, for some reason I'm getting intellisense for the colours. I like it but shouldn't it detect if I'm inside the curly brackets for actual styles?
 
- VSCode Version: 1.23.0
- OS Version: Windows 10 Home

![vscode](https://user-images.githubusercontent.com/16131590/39663658-df0ebe32-503c-11e8-8b54-b541391dc7f4.jpg)

**Comment by ramya-rao-a** [comment]
I can't seem to repro this. Can you share a small code sample where I can try?

**Comment by moseleyi** [comment]
I'm using LESS in that file so I'm basically writing something like this:
```
#wrap {
    #div{}
}
```
but when I press `#` inside wrap it opens colouring intellisense

**Comment by aeschli** [comment]
Like this?
![image](https://user-images.githubusercontent.com/6461412/40609218-4bd6f74e-626e-11e8-9316-052e7e891a0d.png)

**Comment by ramya-rao-a** [comment]
What @aeschli shared above is definitely a bug and I can see it in scss files too.
But @moseleyi,  I still can't repro what you first shared in https://github.com/Microsoft/vscode/issues/49269#issue-320508720. Do you still have that issue?

**Comment by moseleyi** [comment]
Yes still have it, exactly like @aeschli  mentioned. since I'm not actually entering the value of CSS property it shouldn't give me colours, should it?

**Comment by ramya-rao-a** [comment]
@moseleyi I am referring to what shared in your first comment in this issue. There your cursor is still in the selector section of the rule. Are you still having that issue?

**Comment by moseleyi** [comment]
My selector is inside another selector so it's exactly the same as aeschli, you just can't see the starting point of the definition but it's more like:

```
#something{
   #something_else, #<my_cursor_is_here>{}
}
```

**Comment by ramya-rao-a** [comment]
Thanks! I see it now.
