### ISSUE TITLE
Image previewer with FileSystemProvider fails security-policy

### ISSUE THREAD

**Issue by mikolino** [Microsoft/vscode#49278]
- VSCode Version: 1.23
- OS Version: Win 8.1

Steps to Reproduce:

1. Open image from a folder served by a filesystemprovider
2. Check the dev log

It seems that the image previewer is set to disallow anything but data: and https:

Error:

    internal/process/next_tick.js:109 Refused to load the image 'sftp://sync@server.net/var/www/favicon.ico' because it violates the following Content Security Policy directive: "img-src 'self' https: data:".

For easy reproduction I can confirm that the issue is present in the "official" MemFS extension as well.

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
@mjbvz I think it is this change, but all my resources using the new webview are all getting access denied now. How can I fix this?

**Comment by mjbvz** [comment]
Unlikely a5f35c0 caused it. Please open another issue if you are seeing problems

**Comment by mjbvz** [comment]
To verify:

- In a non local folder
- Open a image file

The image should now be displayed properly

**Comment by chrmarti** [comment]
Verified with MemFS.
