### ISSUE TITLE
Do not delete tab-ful of spaces when pressing backspace

### ISSUE THREAD

**Issue by yushiyangk** [microsoft/vscode#49279]
Suppose that tab width is set to 4, and a line begins with 8 spaces followed by some text. Placing the cursor between the spaces and the text and pressing backspace deletes 4 spaces at once.

This is not desirable behaviour *when editor.insertSpaces is set to false*.

**Comment by yushiyangk** [comment]
No the first suggestion is the exact opposite of my issue, and moreover it already reflects the status quo.

That is not desirable behaviour *when editor.insertSpaces is set to false*.

**Comment by a-vrma** [comment]
Are you using the VsCodeVim plugin?

**Comment by ZhengRui** [comment]
I am using VsCodeVim plugin and facing this issue, I have to press delete multiple times to delete a tab which is annoying. Will try TabSanity and see if it helps.

**Comment by a-vrma** [comment]
Yeah if anyone else is having this problem while using vscodevim look at VSCodeVim/Vim#1691.

**Comment by rebornix** [comment]
For the original issue, it can be disabled by `editor.useTabStops`.
