### ISSUE TITLE
Very tiny typing mistake on user settings template

### ISSUE THREAD

**Issue by dannevesdantas** [Microsoft/vscode#49277]
Hi, I have noticed a very tiny typing mistake on the settings template when I was translating it to pt-br.

- VSCode Version: 1.23.0
- OS Version: Windows 10 Home Single Language Build 1709

Steps to Reproduce:

1. Open VS Code
2. File > Preferences > Settings
3. On DEFAULT USER SETTINGS the "**files.maxMemoryForLargeFilesMB**" setting description says _"Controls the memory available to VS Code after restart when trying to open large files. Same affect as specifying --max-memory=NEWSIZE on the command line"_ but I believe it should be "**Same effect as...**". **Effect** instead of **Affect**.

The sentence is located at https://github.com/Microsoft/vscode/blob/0b5ff1f4a9aea6798b319ef739e69fab30ee3456/src/vs/workbench/parts/files/electron-browser/files.contribution.ts#L289

Does this issue occur when all extensions are disabled?: Yes

Thanks.

**Comment by rebornix** [comment]
@sbatten I'm happy that this config is now owned by you, not me.
