### ISSUE TITLE
Use PolicyKit

### ISSUE THREAD

**Issue by Paviluf** [Microsoft/vscode#49270]
As you can see here https://github.com/Microsoft/vscode/issues/46560 Vs Code use kdesudo and really should not do that. Indeed kdesudo is deprecated and instead Vs code should use PolicyKit. It's goes the same for gksudo.

**Comment by Tyriar** [comment]
No results for either:

https://github.com/Microsoft/vscode/search?utf8=%E2%9C%93&q=gksudo&type=
https://github.com/Microsoft/vscode/search?q=kdesudo&unscoped_q=kdesudo

I don't see it used in the main Electron repo either? https://github.com/electron/electron
