### ISSUE TITLE
Feature Request: Select word at caret

### ISSUE THREAD

**Issue by mxxcx** [Microsoft/vscode#49273]
Select word at caret, is the best feature I like of intellij (Ctrl + W), I moved to vscode but I really miss it, is there any chance we can get it? I tried once a plugin but didn't worked well.

**Comment by ajitid** [comment]
Equivalent to that in VSCode is Expand Select.

**Comment by mxxcx** [comment]
Expand Select doesn't fill like it, is just jumps to the biggest block, intellij one seems much smarter.

**Comment by ajitid** [comment]
Add selection to next find match (<kbd>Ctrl</kbd>+<kbd>D</kbd>) does this.

**Comment by rebornix** [comment]
@mxxcx could you please provide more info like in which cases `ctrl+d` doesn't work for you?

**Comment by mxxcx** [comment]
vscode version seems to extend to much, is not as granular, for example https://gyazo.com/dab16d9ff938efc16a8d50b60eda37f3

While intelijava version is better, I can select a word, detects ., -> and other operators/boundaries. 
https://gyazo.com/a675b6511a6efeff7a9c70217e60a943
