### ISSUE TITLE
feature-request code-insiders Remove Spaces from Executable name

### ISSUE THREAD

**Issue by gotaug** [Microsoft/vscode#49276]
- VSCode Version: Code-Insiders 1.24.0-insider
- OS Version: Win10 64

Please remove the spaces from the name of the executable that launches the Insiders version, changing it from "Code - Insiders" to Code-Insiders"

This is a small thing but it will make it easier to figure how to call this version in the command prompt.  Command prompt won't accept spaces and calling the program with a different spelling (removing the spaces yourself) is inconsistent.

**Comment by joaomoreno** [comment]
When installing Code, there will be a `code-insiders` in your PATH, which you can just call from the command line.
