### ISSUE TITLE
vscode.workspace.findFiles() can return no result with certain RIPGREP_CONFIG_PATH

### ISSUE THREAD

**Issue by cinch** [Microsoft/vscode#49283]
- VSCode Version: 1.23.0
- OS Version: Arch Linux

Steps to Reproduce:

1. set this environment variable (for example inside .bashrc): export RIPGREP_CONFIG_PATH=~/.config/ripgreprc
2. inside ~/.config/ripgreprc put "--color=always" (without quotes)
3. create a new test project: $ dotnet new console
4. launch vscode: $ code .
5. install the omnisharp c# extension and witness how it doesn't start the omnisharp server.
it can't launch the server, because it calls "vscode.workspace.findFiles(...)"  (it's in omnisharp v.1.14.0 on src/omnisharp/launcher.ts line 48), which doesn't return any results due to the ripgrep configuration from the environment variable. findFiles will simply return an empty array without any results, but it should return one result.

workaround: i put "unset RIPGREP_CONFIG_PATH" inside the launcher of /usr/bin/code

Does this issue occur when all extensions are disabled?: Yes. on the master branch, launch the debug task called "VS Code API Tests (single folder)". the test calling findFiles will fail:  
2) workspace-namespace findFiles:      AssertionError: 0 == 1

**Comment by BurntSushi** [comment]
VS Code probably wants to use ripgrep with the `--no-config` option, which will prevent ripgrep from reading its configuration from the environment.

**Comment by roblourens** [comment]
Yes, thanks @BurntSushi

**Comment by chrmarti** [comment]
Moving to recovery milestone. (I assume that was the intention.)
