### ISSUE TITLE
[css] @supports and/or/not should be case insensitive

### ISSUE THREAD

**Issue by AmeliaBR** [Microsoft/vscode#49288]
Issue Type: <b>Bug</b>

Example of code that is valid in browsers but is marked up as a syntax error in VS Code (with the result that code inside the braces is also mis-parsed):

```css
@supports (column-width: 1rem)
  OR (-moz-column-width: 1rem)
  OR (-webkit-column-width: 1rem) {
/* create columns, with fallback properties */
}
```

On testing, it seems that VSCode expects the combinators (`and`, `or`, `not`) to always be lowercase. But, like most of CSS, they should be case insensitive.  Lowercase _could_ be a linting recommendation, but uppercase is definitely not a syntax error!

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
Verified it works, also double checked this behavior is correct:

> CSS style sheets are generally case-insensitive, and this is also the case for media queries.

From https://www.w3.org/TR/css3-mediaqueries/#syntax (sent there from https://drafts.csswg.org/css-conditional-3/#at-supports )
