### ISSUE TITLE
VSCode is bugging me about pylint

### ISSUE THREAD

**Issue by soerendip** [Microsoft/vscode#49281]
Issue Type: <b>Bug</b>

I tried installing it, I tried Disable pylint and Disable linting, notting works.... eachtime I open CSCode the message box appears saying "Linter pylint is not installed". 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.86GB (6.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0
PowerShell|ms-|1.7.0

</details>

**Comment by sandy081** [comment]
@soerendip Looks related to python extension, Please file the issue against it.
