### ISSUE TITLE
Exceptions/variables still visible after stopping debugging and unresponsive variables window

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4928]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Start debugging a Node.js project that will throw an exception
2. Click on an item in the Call Stack

It will show a loading icon next to Exceptions in the variables list.
![exceptionloading](https://cloud.githubusercontent.com/assets/12900364/14261116/1af94826-fa64-11e5-89b9-000895b07714.JPG)

3. Stop debugging before it loads the exception

Actual:
Variables list still tries to load exceptions after stopping debugging and the variables windows becomes unresponsive even after stopping and restarting debugging.

**Comment by isidorn** [comment]
Fixed yesterday
