### ISSUE TITLE
Cannot install Chrome Debugger Extension

### ISSUE THREAD

**Issue by xrousseau** [Microsoft/vscode#49286]
Issue Type: <b>Bug</b>

I can install extensions except for the Chrome Debugger.

It keeps saying "installing" even after many minutes (I waited up to 20)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (5.69GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.2.4
electron-debug|kod|18.5.0
dotenv|mik|1.0.1
vscode-docker|Pet|0.0.26

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It should be fixed now, please try to install 4.4.3.
