### ISSUE TITLE
Functions paint in the wrong colors/styles sometimes due to perhaps either a VSCode or MS C/C++ parser bug.

### ISSUE THREAD

**Issue by gmcode** [Microsoft/vscode#49296]
- VSCode Version: 1.24.0
- OS Version: Windows 7

Steps to Reproduce:

1. Paste the code below into a test.cpp file and load it:
```
int Whatever1()
{
    return (int)::Whatever2();
}
int Whatever3()
{
}
```

2. Notice that VS Code highlights all three functions in three different colors using the Dark + scheme.
If you put a space character before the :: then vs code gets it right and chooses a single function color in all 3 cases.

I think VS code or the C/C++ parser (whichever is at fault here) should get this right without having to put a space in to get one function color.

By the way, I think VS code should do a better job in diagnosing errors while parsing color themes.
i.e. it should spot two ## in the html color or if there is insufficient / wrong hex digits.
It would also be nice if the color editor that works for settings worked in theme files too.
If there was an easy 'apply style automatically saving and restarting' for testing schemes would be great,

**Comment by aeschli** [comment]
I created https://github.com/atom/language-c/issues/276 for the highlighting issue.

To create a color theme I recommend you to define the new theme first in the settings: Use the 
 `editor.colorCustomizations` and `workbench.colorCustomizations` setting. That way you get syntax errors and don't need to restart and you also get the color pickers.

https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_adding-a-new-color-theme has more info.
