### ISSUE TITLE
Fast switching work area missing

### ISSUE THREAD

**Issue by notek** [Microsoft/vscode#49295]
I want to be able like  quickly switch between workspaces like the shortcut key "ctrl+command+p" in sublime text.

like this：
![image](https://user-images.githubusercontent.com/3304247/39670261-0d01597a-5133-11e8-8016-1f14d2382b81.png)

**Comment by usernamehw** [comment]
`File: Open recent`?

**Comment by notek** [comment]
@usernamehw In fact, I'm using "open recent" now, but I always think he's not pure.

**Comment by notek** [comment]
@usernamehw I know this plugin, but always fantasy vscode can natively support it, just like sublime text

**Comment by bpasero** [comment]
There is a workspace picker:

![image](https://user-images.githubusercontent.com/900690/39684659-be510f9c-51bd-11e8-81c8-19836e521e85.png)

![image](https://user-images.githubusercontent.com/900690/39684670-c555a4d8-51bd-11e8-8d5c-4ca0cdb827ec.png)
