### ISSUE TITLE
[Feature Request] Support ability to switch between multiple keybindings.json files

### ISSUE THREAD

**Issue by monners** [microsoft/vscode#49294]
# Feature Request for multiple keybindings.json files

## How it works now
Manually copy/paste desired config into `keybindings.json`, repeat to switch back

## Feature request
Allow multiple keybinding config files to be imported and selected programmatically

# Why
As a programmable keyboard user, I have one workflow for when I'm using my external keyboard, and another for when I'm using my laptop.  I would like to be able to define a set of keybindings for each use case separately, and be able to toggle between both from within VSCode.

## Example
On my keyboard, I use `FN+ j/k/i/l` as arrow keys, which outputs the native keycodes for `left/down/up/right`.  To duplicate this behavior on my laptop keyboard, I have to define the following:

```
{
    "key": "ctrl+j",
    "command": "cursorLeft",
    "when": "textInputFocus"
},
{
    "key": "ctrl+k",
    "command": "cursorDown",
    "when": "textInputFocus"
},
{
    "key": "ctrl+i",
    "command": "cursorUp",
    "when": "textInputFocus"
},
{
    "key": "ctrl+l",
    "command": "cursorDown",
    "when": "textInputFocus"
}
```

However, when I switch back, I've got to reset these bindings to the defaults (along with all of the other keyboard-specific shortcuts I've defined).  This would be far easier if I could just select from a pre-existing keybinding config from within the editor.

**Comment by shamseerahammedm** [comment]
I don't know if this is the correct place , but with the latest update of vs code my custom key bindings for emmet wrapping is not working anymore. any solutions ? my vs code details:
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

`[
    { "key": "ctrl+shift+g", "command":"editor.emmet.action.wrapWithAbbreviation", "when": "editorTextFocus && !editorReadonly" }
]`

**Comment by sandy081** [comment]
@shamseerahammedm Please file a separate issue for your problem. It is not recommended to diverge and track multiple problems in one issue. Sorry for that.
