### ISSUE TITLE
Markdown Preview does not interpret kbstyle() [Not sure if it is a Bug]

### ISSUE THREAD

**Issue by lucaslra** [Microsoft/vscode#493]
In the vscode-docs repo there are some markdown documents who contains function like syntax "kbstyle()"

![image](https://cloud.githubusercontent.com/assets/2528972/11336344/acd245ec-91cb-11e5-90c8-c53b931cef89.png)

The Markdown preview doesn't seem to understand this syntax, but in the official documentation page it has a different coloring.

![image](https://cloud.githubusercontent.com/assets/2528972/11336368/e6c8bb0a-91cb-11e5-9886-b71956591429.png)

I'm not sure if this is a Bug, or just an expected behavior, as I haven't found any documentation on this "kbstyle()" syntax

**Comment by bpasero** [comment]
I think this is something we add from our custom markdown parser and is not supported in general.
