### ISSUE TITLE
No suggestions when there are no characters for suggest widget

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4930]
- VSCode Version: latest alpha
- OS Version: os x

Steps to Reproduce:

1. open any file, js, ts, css, for instance actionbar.css
2. enter a new line and try to trigger css intelli-sense, notice there are no suggestions
3. now try to trigger intelli-sense after any character, e.g 'b' notice you get intelli-sense

I also get no suggestions when triggering after a '.' 

![screen shot 2016-04-04 at 23 24 20](https://cloud.githubusercontent.com/assets/1926584/14263711/641547f0-fabc-11e5-9d0a-ef15e6a91b57.png)

**Comment by jrieken** [comment]
fixed that yeserday
