### ISSUE TITLE
synchronize

### ISSUE THREAD

**Issue by winningH** [Microsoft/vscode#49309]
Issue Type: <b>Feature Request</b>

I hope next version can synchronize all the settings including themes and keys by the account or email

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2743
