### ISSUE TITLE
Unexpected exception when creating a WebView

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#49300]
Issue Type: <b>Bug</b>

When I create a new webview panel in a command handler, I get an unexpected exception about a disposed webview, even though the webview is still alive:

```
An error occurred while running command antlr.rrd.singleRule DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model2) has been disposed
extensionHostProcess.js:700
    at Object.t.disposed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:164:793)
    at e.$tryApplyEdits (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3457:571)
    at e._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2891:894)
    at e._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2891:612)
    at e._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2890:682)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2890:451)
```

This error comes up after the closure returned control and happens *only* when I dock the webview panel in the first column. Using e.g. the second column doesn't cause any trouble. The panel is still alive, even after the exception was thrown. I can dock it to different columns and otherwise interact with it (e.g. select text). When I close the tab I get the disposal log message, as expected. It makes no difference if I set the HTML content or any of the options.

Here's the creation code:

```
    context.subscriptions.push(commands.registerTextEditorCommand('antlr.rrd.allRules', (editor: TextEditor, edit: TextEditorEdit) => {
        const panel = window.createWebviewPanel(
            'antlr-rrd-diagram',
            "ANTLR RRD: " + path.basename(editor.document.fileName),
            ViewColumn.One,
            {
                enableScripts: true,
                retainContextWhenHidden: true
            }
        );

        panel.webview.html = diagramProvider.createWebviewContent(editor, true);
        panel.onDidDispose(() => {
            console.log("Panel DISPOSED");
        }, null, context.subscriptions);
    }));
```

At the moment I don't store the panel reference anywhere, nor do I act on it in any other way, beyond this small block. So, I believe it's not my code that causes the exception.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (14.38GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mike-lischke** [comment]
vscodebot, you are not doing a good job atm ;-)

**Comment by mjbvz** [comment]
Looks like it is the `TextEditor` this is disposed. `createWebviewPanel` both creates and shows the webview, so any texteditor in the target column will be destroyed once it is called (because it is no longer visible)

The fix is to get everything you need from the text editor before calling `createWebviewPanel` and also don't call this (or any view modifying methods) in the handler for a text editor command
