### ISSUE TITLE
Intellisense: Suggest contextual items before "Language Basics"

### ISSUE THREAD

**Issue by paterasMSFT** [Microsoft/vscode#49304]
When Intellisense comes up without any input (e.g. when I hit CTRL+space with the cursor on whitespace), it renders "Language Basics" (at least in TypeScript) at the top of the list:

![image](https://user-images.githubusercontent.com/35780775/39673450-7bf8673e-510a-11e8-9052-db3b2db4ac1a.png)

Below that are contextual suggestions, which are far more likely to be relevant. This is most frequently a pain point when I'm consuming a React component. The component's props are in the list, which is very useful, but I have to scroll to the bottom of the list to include each one, as I usually don't know their names off-hand. I do know class, ctor, foreach, function, etc., off hand, so those items are very easy to filter into (which is also something I don't find myself wanted to do very often, anyway).

Please prioritize contextual Intellisense items before "Language Basics", or at least give us an option to do so.

Thank you.

**Comment by jrieken** [comment]
You can control that with this setting: `"editor.snippetSuggestions": "bottom"`
