### ISSUE TITLE
TypeScript: Warning for upper case `lib` value in tsconfig.json

### ISSUE THREAD

**Issue by sangaman** [Microsoft/vscode#49307]
- VSCode Version: 1.22.2
- OS Version: Windows 10 Home - 10.0.16299 Build 16299

Steps to Reproduce:

1. In a TypeScript project, go to `tsconfig.json` and set a value for `lib` using upper case letters such as `ES2015` or `ES2016` 
2. Observe a warning message `Value is not accepted. Valid values: "es5", "es6", "es2015", "es7", "es2016", "es2017", "es2018", "esnext", "dom", "dom.iterable", "webworker", "scripthost", "es2015.core", "es2015.collection", "es2015.generator", "es2015.iterable", "es2015.promise", "es2015.proxy", "es2015.reflect", "es2015.symbol", "es2015.symbol.wellknown", "es2016.array.include", "es2017.object", "es2017.sharedmemory", "es2017.string", "es2017.typedarrays", "es2018.promise", "es2018.regexp", "esnext.array", "esnext.asynciterable".`

I'm not sure if this is a problem with vscode specifically but I haven't been able to connect it to anything else. The possibly values on the official website do have upper case letters (https://www.typescriptlang.org/docs/handbook/compiler-options.html) and there's no warning message if the `target` value uses upper case letters.

It would be desirable if the `lib` option behaves like `target` and accepts either upper or lower case letters without warnings, either way works as far as compiling code goes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Opened https://github.com/SchemaStore/schemastore/issues/449 to track this upstream
