### ISSUE TITLE
commd +k  Unable to clean up the terminal 

### ISSUE THREAD

**Issue by Liberxue** [Microsoft/vscode#49301]
Issue Type: <b>Bug</b>

1. commd +k  Unable to clean up the terminal, I'm obsessive-compulsive!!!
2. In the terminal clear    Unable to clean up the terminal

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
vscode-author-generator|edw|0.0.4
vscode-npm-script|eg2|0.3.4
vscode-ariatemplates-highlighter|max|0.2.2
easy-less|mrc|1.4.5
python|ms-|2018.4.0
cpptools|ms-|0.16.1
Go|ms-|0.6.79
node-debug2|ms-|1.20.0
team|ms-|1.133.0
makefiles-support-for-vscode|nae|0.0.3
vetur|oct|0.11.7
vscode-react-native|vsm|0.6.9

</details>

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/49162
