### ISSUE TITLE
Terminal API to return exit/termination of REPL environment

### ISSUE THREAD

**Issue by d0mf1g** [Microsoft/vscode#49312]
- VSCode Version: 1.23.0
- OS Version: Windows 10

Hello,

I would like to refer to an issue from the VS Code Python extension:

https://github.com/Microsoft/vscode-python/issues/1205

One of the extension's developer says the current API for working with the terminal is limited in such that they have no way of knowing if we exited the Python environment.

Does this issue occur when all extensions are disabled?: N/A; need Python extension.

**Comment by Tyriar** [comment]
I don't think there's a way to do this that works on all platforms, shells and scripts.
