### ISSUE TITLE
vue single file component typescript vscode problems

### ISSUE THREAD

**Issue by wysisoft** [Microsoft/vscode#49314]
I have a simple single file vue component, and i'm having a few problems with it. 

1 - I cannot rename the variable 'v' in the code below
2 - when I do an F12 on the 'v' in 'v=1', the cursor goes DOWN instead of up.

<script lang='ts'>
let v = 0;
v = 1;
</script>

<style>
.greeting {
  font-size: 20px;
}
</style>

<template>
  <div>
  </div>
</template>

**Comment by octref** [comment]
F2 to rename is not implemented. 2 sounds like a bug similar to this one: https://github.com/Microsoft/TypeScript-Vue-Starter/issues/45
