### ISSUE TITLE
Nothing gets rendered on running VS Code on OS X 10.11.4

### ISSUE THREAD

**Issue by abhinav-shah** [Microsoft/vscode#4931]
- VSCode Version: 0.10.11 (February 2016)
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Download VS Code zip.
2. Unzip and launch VS Code App.

On launching the App, the only menu I get is "Code"  and that only has the option to "Quit". 
Attached is the screenshot.

![screen shot 2016-04-04 at 2 49 58 pm](https://cloud.githubusercontent.com/assets/5296138/14264439/9b64f130-fa74-11e5-88bf-f9bbf064e6ce.png)

**Comment by bpasero** [comment]
@abhinav-shah can you run this from the command line and attach the output:

`/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`

**Comment by abhinav-shah** [comment]
Ran it from command line: Didn't get any output

➜  ~ /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron

**Comment by bpasero** [comment]
@abhinav-shah any chance you might have an older version of VS Code installed that Mac tries to open?

**Comment by abhinav-shah** [comment]
nope. I even tried running the [March Insiders Release](https://code.visualstudio.com/Download#insiders) this morning. Still the same thing. It doesn't render anything.

**Comment by bpasero** [comment]
Sorry, out of ideas. @joaomoreno maybe more ideas?

**Comment by joaomoreno** [comment]
Did it use to work at any point in time? Either stable or insiders? Any old version?

**Comment by abhinav-shah** [comment]
it never worked for me.

**Comment by bpasero** [comment]
@abhinav-shah does it work if you do `sudo /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`

**Comment by abhinav-shah** [comment]
I tried with sudo. It didn't work.

**Comment by bpasero** [comment]
Another idea if you want to try it out: Can you run VS Code from sources? See https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by abhinav-shah** [comment]
Tried running from sources. Still the same problem.

Is it related to https://github.com/atom/atom/issues/11147

**Comment by bpasero** [comment]
Would not think so, anything printed to the console? Can you try running "scripts/code.sh --verbose" and copy the output here?

**Comment by abhinav-shah** [comment]
here you go - 

➜  vscode git:(master) scripts/code.sh --verbose
[14:42:43] Using gulpfile ~/Downloads/vscode/gulpfile.js
[14:42:43] Starting 'electron'...
[14:42:43] Finished 'electron' after 447 μs
{ [Error: ENOENT: no such file or directory, open '/Users/abhishah/Library/Application Support/Code-Development/storage.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/abhishah/Library/Application Support/Code-Development/storage.json' }

**Comment by bpasero** [comment]
Can you see if /Users/abhishah/Library/Application Support/Code-Development exists with user permissions to write to it or otherwise create this?

**Comment by abhinav-shah** [comment]
I created a file "storage.json" under  /Users/abhishah/Library/Application Support/Code-Development.

The contents of storage.json are {}.

Now when I run code.sh i get the following:

➜  vscode git:(master) scripts/code.sh --verbose
[16:25:01] Using gulpfile ~/Downloads/vscode/gulpfile.js
[16:25:01] Starting 'electron'...
[16:25:01] Finished 'electron' after 461 μs


However, I still don't get the editor screen.

**Comment by bpasero** [comment]
Ok, seems unrelated then. Though I wonder why this file could not be created in the first place. Are you running Code with a different user account or permissions?

**Comment by abhinav-shah** [comment]
nope, i am not running code with a different user account / permissions

**Comment by abhinav-shah** [comment]
I don't know what happened, but i downloaded VS code today and ran it, and it started working. ty!

**Comment by bpasero** [comment]
Wow cool 👍
