### ISSUE TITLE
Need ability to set focus using treeview.reveal

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#49311]
- VSCode Version: 1.23

There doesn't seem to be a way to shift the focus to a treeview item.  With `reveal` I can select the item, but it would be very useful to have another parameter on reveal `options` to also make the item the active focus.

**Comment by sandy081** [comment]
@dakaraphi 

I am adding another option `focus` to reveal API to focus the revealed element. By default this option will be `false`.
