### ISSUE TITLE
Git provider auto stashes when doing a commit

### ISSUE THREAD

**Issue by reporter123** [Microsoft/vscode#49324]
I frequently make commits where not everything in the working directory is staged. I don't expect to have all other changes stashed when doing so. This interferes with making a second commit from the same worktree state as I now have to un-stash the changes in order to stage them. Please make this optional as it does not fit all work flows. It also does not follow the behavior of git when used via other tools or the commandline. Shouldn't it be documented somewhere?

**Comment by joaomoreno** [comment]
> I frequently make commits where not everything in the working directory is staged.

VS Code knows this. If there is something staged, only that will be committed. If there is nothing staged, everything will be staged and then committed. Doesn't this work for you?

**Comment by reporter123** [comment]
Let me make sure where on the same page here. My issue does not occur if everything is stage or if nothing is staged. The behavior under these circumstances is sensible.
Say there two changed files A and B. I stage A. Most git tools if a commit is done B will remain in the worktree unstaged. B can then be staged and committed separately. vscode for some reseason is doing "git stash" after every commit. This interferes with the above process by force me to unstash B before I can commit it.

**Comment by reporter123** [comment]
I had a script running on commit that I forgot about. Anyway solved my problem thanks for your time/
