### ISSUE TITLE
Modify vscode `workspaceStorage` folder path

### ISSUE THREAD

**Issue by zhaojuntao** [Microsoft/vscode#49326]
I have asked it on [stackoverflow](https://stackoverflow.com/questions/50187662/modify-vscode-workspacestorage-folder-path) , but I haven't got any answer yet .

- VSCode Version: 1.22.2
- OS Version: Windows 10 1703

Description :  

The default workspaceStorage storage path is C:\Users\Administrator\AppData\Roaming\Code\User\workspaceStorage.

It takes up a lot of disk space, so I want to know how to modify this default storage path.

THANKS!
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@zhaojuntao you can do this via "`code --user-data-dir <some dir>`"
