### ISSUE TITLE
Not getting correct launch.json when targeting node.js debugger.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4932]
- VSCode Version:0.10.13-alpha
- OS Version: WIndows10

Steps to Reproduce:
1. Upgrade VSCode from 0.10.12 to 0.10.13-alpha. 
2. I had many extensions installed with 0.10.12. like (C#, GO, Ruby, Cordova, TSlint etc.)
3. Open any folder which contains .ts file.
4. Generate tasks.json.
5. Set node.js debugger and generate launch.json.
6. Verify launch.json file contents

Actual: 
It is taking default launch type as "GO" and complaining if changing to "node".
	"configurations": [
		{
			"name": "Launch",
			"type": "go"			
		}
        ]
![image](https://cloud.githubusercontent.com/assets/17735796/14265872/e0f861e2-fa78-11e5-8677-d5f27d45c225.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/17735796/14266050/62776582-fa7a-11e5-9a9e-8000c63008bf.png)

**Comment by isidorn** [comment]
Can not reproduce on my machine, i even installed the go extension.

If you see this regularly on your machine, please do the following
1. create a public repository on github for which i can reproduce this
2. try to create a minimal number of steps needs - e.g. is step 4 really neccessery?
