### ISSUE TITLE
API for custom editor panes

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#49325]
Issue Type: <b>Feature Request</b>

<b>Update/Clarification: I am suggesting a UI API that could be used <i>instead of</i> the WebView API.</b>

Looking at #12176 and #5604 as well as the conversation around the WebView API, it seems that a common thread is the lack of support for contributing editor panes from an extension. I noticed some concern that the WebView API would facilitate extensions adding UI that was completely outside of the normal VSCode UI APIs, constraints, and thus UX, as it will allow arbitrary UIs that could be entirely inconsistent with the existing VSCode UI. While I support the WebView API, as there are definitely some strong use-cases, I agree that maintaining consistency of UI/UX design across the board is important.

I think that it would be extremely valuable to have an API for building interfaces within the editor pane; an API that would work within the constraints of the existing VSCode UI and thus be consistent with it. If there were such an API, I think many (if not most) extension developers who are using or considering WebViews would instead use this API.

And as far as #12176 and #5604, I think an API for custom editor panes is a natural prerequisite. I think such and API could take VSCode from "very useful" to "essential and critical" development tool.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

**Comment by Kroc** [comment]
This would benefit extensions such as hex dump. As it stands, hex dump cannot work when you just click on a binary file (it shows the usual warning), you have to right-click the file and select "Show hexdump".

**Comment by firelizzard18** [comment]
@kroc What you're looking for is #12176. This issue is about an API that could be used to create custom editors, instead of the current method of using WebViews.

**Comment by dschaefer** [comment]
And I really don't think this would be such a big leap from WebView. Right now, I can add a menu item to explorer to open a WebView to show the contents of a binary file, or even a text file, using a visualization that makes sense for that file. I could then add UI to allow the user to make changes to that visualization that could be saved back to the file. What's missing is the dirty bit to show the file needs saving in the tab and the ability to clear it when we save.

Now I'm probably over simplifying and we probably want to participate in editor commands available from the File and Edit menus as well. But that's the general idea.

I'm thinking of things like modeling tools, form based editors, etc. that give a great experience. Not everything a developer works with is text, or want to work with text. And by making WebViews so powerful, we're almost there. You're almost teasing us :).

**Comment by Kroc** [comment]
I can't speak of engineering complexity or difficulty, but this could also be seen as a way to more elegantly implement the current 'custom editors' in VSCode, like the Settings editor, Keyboard settings etc. You could think of them as custom editors used for those specific files. The user could also choose which 'editor' applies to which files such that they could choose in a orthogonal way if they want to use raw JSON, the half/half editor currently used, or the upcoming GUI. These could even be moved out to built-in extensions.

**Comment by dschaefer** [comment]
Did a quick check but it doesn't look like the clipboard commands from the menu are getting to the document in the webview. The keyboard ones are working fine. But that could be a separate issue.

**Comment by firelizzard18** [comment]
**To clarify,** I am suggesting something separate and different from the WebView API. I want a **separate** API that can be used to build editors. As in, something that would make VSCode's UI components accessible and allow extension developers to contribute editors that used VSCode's own UI elements.

@dschaefer

**Comment by dschaefer** [comment]
The main reason I suggest the webview approach is that it complies with their architecture of keeping extensions in their own processes to keep the main UI responsive. I'll create new bugs for my suggestions and leave this one to your original goals.

**Comment by jbrownson** [comment]
@dschaefer please post a link here if/when you open the new issue, I'd like to follow it too.

**Comment by leidegre** [comment]
Does it really make sense to push a feature like this into VS Code? I get why it would be nice to do so but thinking about the added complexity of doing so, it's going to breed a lot of extensions that probably work oh, not so-so well. Which I think would be a great disservice to the whole VS Code text-centric ecosystem. Arguably the success of VS Code is it's simplicity.

However, having a way of providing a read-only custom view of arbitrary binary files, might be reasonable for browsing purposes and I don't think it matters if the break away from the UI consistency that is VS Code, it would just be a web page displaying information. Possibly with the option to configure that such tools are edited using external editors.

**Comment by dschaefer** [comment]
I think it's a natural fit. With webviews, we're already have the most complicated part. Just need to hook it up so that the framework opens up the webview instead of the text editor and hooks up a few editor actions.

And going through the code, not sure I agree it's simple. There's a pretty powerful but complex framework underneath that simple UI. But that's what makes vscode so good.

And at the end of the day, if an extension does a bad job of it, it gets bad reviews and can always be uninstalled. Those who do a good job will make sure they don't disturb the great text editor experience and we'll have the right IDE for the next 20 years.

**Comment by mjbvz** [comment]
As I understand it, the original request here was for a set of user interface components that extensions could use to build custom UI. I feel this is out of scope. We do not want to get into the business of being a general purpose user interface library.

Instead, we push extensions to provide data that VS Code can surface to users in consistent and performant manner. This obviously limits what extensions can do but we feel these limitations are key to maintaining the overall quality and of VS Code

A few related issues:

* Fully customizable editors (using webviews) #12176
* Custom sections of user interface within editors (also using webviews): #66418

Closing this feature request as out of scope
