### ISSUE TITLE
when i update version document format have something wrong

### ISSUE THREAD

**Issue by Luis-Chen** [Microsoft/vscode#49329]
Issue Type: <b>Bug</b>

after i update vs code to 1.23(lastest)
my document format style are change 
![](https://i.imgur.com/8MxZUvh.png)

i don`t know how to fix

in normal document format style should be like this 

![](https://i.imgur.com/GTJk8V1.png)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.72GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.15.0
vsc-material-theme|Equ|2.0.1
beautify|Hoo|1.3.0
output-colorizer|IBM|0.1.2
vscode-extension-auto-import|Nuc|1.4.1
material-icon-theme|PKi|3.4.0
better-comments|aar|1.2.2
markdown-preview-github-styles|bie|0.1.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
es7-react-js-snippets|dsz|1.6.0
gitlens|eam|8.2.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
vscode-great-icons|emm|2.1.31
prettier-vscode|esb|1.3.1
git-project-manager|fel|1.5.1
terminal|for|0.0.10
markdown-table-formatter|jos|0.2.3
vscode-styled-components|jpo|0.0.18
markdown-shortcuts|mdi|0.8.1
code-beautifier|mic|2.0.3
prettify-json|moh|0.0.3
team|ms-|1.133.0
debugger-for-chrome|msj|4.4.3
vscode-icons|rob|7.23.0
markdown-preview-enhanced|shd|0.3.5
stylelint|shi|0.36.0
react-beautify|tai|0.3.0
theshukran-react-utils|the|1.0.2
JavaScriptSnippets|xab|1.6.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is likely caused by one of your extensions. Does it repo when you disable all of them?

**Comment by Luis-Chen** [comment]
oh i am didn`t but i found something wrong cause form `react-beautify` extension
