### ISSUE TITLE
con not input anyword 

### ISSUE THREAD

**Issue by EvilBoom** [Microsoft/vscode#49333]
Issue Type: <b>Bug</b>

i can not input anything after open vs code

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.33GB free)|
|Process Argv|D:\vscode\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|44%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vimStyle|74t|0.5.4
html-snippets|abu|0.2.1
project-manager|ale|0.25.2
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.48
vscode-html-css|ecm|0.2.0
auto-rename-tag|for|0.0.15
HTMLHint|mka|0.5.0
vscode-language-pack-zh-hans|MS-|1.23.4
python|ms-|2018.4.0
cpptools|ms-|0.16.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I can not reproduce this.
Can you please file this with reproducable steps. A video / picture would help.
If you F1 > developer tools > console do you see some errors?
