### ISSUE TITLE
Cannot clear terminal

### ISSUE THREAD

**Issue by songkrod** [Microsoft/vscode#49334]
I try to clear my terminal with command+K and it will not work when I my node server started (manually start node server). I just found this problem in 1.23.0 version. really sorry for my poor English.

**Comment by yume-chan** [comment]
What shell do you use?

When you press <kbd>Command</kbd> + <kbd>K</kbd>, did it show a `^L` or just nothing happened?

**Comment by songkrod** [comment]
this issue fixed in version 1.23.1 <3 Thank you all
