### ISSUE TITLE
Search filenames across worksapce 

### ISSUE THREAD

**Issue by Aijaz13** [Microsoft/vscode#49336]
Issue Type: <b>Feature Request</b>

Hi,

When I am searching for a filename using Cmd+P ,VS code is not searching for files across entire project directory. It is searching for filename which is present in currently opened files in the editor.

May be the feature is present under different shortcut. Please provide the same.

Thanks

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 16.7.0

**Comment by roblourens** [comment]
Please see the troubleshooting tips in this wiki page: https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by Aijaz13** [comment]
I am referring search for files, not the content, but the filename itself. 
Current functionality  Cmd+p is searching for filenames only in the current folder.
What if I want to search across the entire project? My files are rarely in the folder I'm currently in.

**Comment by roblourens** [comment]
Ok, what do you mean by "current folder" and "project" in this case? You can open one folder in a vscode window, and quickopen will search in that folder. You can also open multiple folders using the "Add folder to workspace" command and it will search in all open foldres.
