### ISSUE TITLE
Cannot save file after document switch with `showTextDocument`

### ISSUE THREAD

**Issue by qjebbs** [Microsoft/vscode#49338]
Issue Type: <b>Bug</b>

A user of my extension has report this bug (https://github.com/qjebbs/vscode-plantuml/issues/118). I can reproduce this bug simply with following code:

```ts
let e = vscode.window.activeTextEditor;
vscode.commands.executeCommand("markdown.showPreviewToSide").then(
    () => {
        vscode.window.showTextDocument(e.document.uri, { viewColumn: e.viewColumn })
    }
);
```
Suppose it's the implement of a command, open a markdown document, and execute this command, the preview window is open, and it automatically switch back to the markdown document.

We will found that before manually re-switching the tab, we can not save the document. Neither `cmd+s` or the menu.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

**Comment by mjbvz** [comment]
I can't reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled and a simple command that just runs:

```ts
let e = vscode.window.activeTextEditor;
vscode.commands.executeCommand("markdown.showPreviewToSide").then(
    () => {
        vscode.window.showTextDocument(e.document.uri, { viewColumn: e.viewColumn })
    }
);
```

Let me know if you are still hitting this problem. (although it's also generally a good idea not to hold onto the active editor object as it may be invalid by the time the `then` is evaluated)
