### ISSUE TITLE
Tooltip background color

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#4933]
_From @rogeralsing on March 29, 2016 9:17_

The tooltips when hovering method names etc. are somewhat hard to read as the background and syntax highlight is the same as the rest of the code window.
it would be nice if at least the background color was a bit different, (lighter/darker depending on theme)

For example, the peek definition makes things much clearer, there is a distinct bg color that shows that this block of code is from somewhere else.

_Copied from original issue: Microsoft/vscode-go#272_

**Comment by lukehoban** [comment]
Moving this to VS Code since it's a general issue. There doesn't appear to be anything an extension can do to override this, but even if there was, it seems to make sense to address generally.

**Comment by rogeralsing** [comment]
![badtooltip](https://cloud.githubusercontent.com/assets/647031/14274205/2d08b950-fb10-11e5-87cc-8b7897defd3d.png)

Here is an example of the problem.
There is a tooltip in there and it is _Very_ hard to see it

**Comment by Peter-Juhasz** [comment]
I have summarized some of the issues (beyond background color) that make difficult to read tooltips in #4884.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/4884
