### ISSUE TITLE
Can provide workbench.main. extended.css?

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#49331]
Issues
vscode not propose to amend source file workbench.main.css，also want to modify the source CSS file to achieve the desired effect.
Idea：
providing an extended CSS file without modifying the source CSS source file can also achieve the effect of using a DIY editor.

**Comment by lihua06** [comment]
Vscode has become an indispensable partner in the development process; I believe it can get better. I modify the source css file or load the css file via JS. But I have to copy it again every time I update it

![tim 20180507124614](https://user-images.githubusercontent.com/20437381/39685446-35fd28c8-51f5-11e8-952b-4f4370379158.png)

**Comment by aeschli** [comment]
VSCode's CSS files are internal and not designed to be modified by users. 
We support color themes and icon themes instead and colors can also be defined in the user settings.
If there's something that you would like to have added there, please file a specific issue.
