### ISSUE TITLE
command to open New Window on open workspace 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#49346]

**Comment by isidorn** [comment]
After investigating into this I have found that this already exists as a command
`Workspaces: Open Folder as Workspace in New Window` and behaves as I would expect.

Closing since this seems to work as expected - we just need to advertise this command a bit more.

@egamma please let me know if you had something else on mind and I can reopen this.

![openworkspace](https://user-images.githubusercontent.com/1926584/39806230-a92aeecc-5379-11e8-935c-69ac7c4f947e.gif)

**Comment by isidorn** [comment]
Noticed that his command only works for single folder -> reopening to also respect multi root workspaces.
Will also rename it to "Duplicate Workspace in New Window"

**Comment by bpasero** [comment]
@isidorn I like it! should probably maybe not be enabled/work if the workspace is empty?

**Comment by isidorn** [comment]
@bpasero I excplitiy allowed for that since people might get used to that command as always opening a workspace, not sure why not to allow that case and make the user use another command.
I do not find the current behavior counter intuitive

**Comment by bpasero** [comment]
@isidorn oke
