### ISSUE TITLE
Remove unnecessary values from intellisense popup

### ISSUE THREAD

**Issue by mikecann** [Microsoft/vscode#4934]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. Setup code like screenshot:
![hwhlc](https://cloud.githubusercontent.com/assets/215033/14267492/6f6ccb54-fb03-11e5-854d-cf8fdfb9e678.png)

2. Notice the unnecessary values in the intellisense

**Comment by jrieken** [comment]
closing as duplicate of #1304
