### ISSUE TITLE
Retrain issue classifier bot

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#49341]

**Comment by alexandrudima** [comment]
May I have a special request: That we forbid the bot from using `editor-core`. The reason is that in the past half year we have now multiple labels that cover what `editor-core` used to cover.

**Comment by chrmarti** [comment]
@alexandrudima Missed your request on the first run. Now `editor-core` is ignored. That improved the precision of the editor classifier (the one that runs after the main classifier decided it is an editor issue), likely because there was a lot of overlap between that old and the new labels it was split into.
