### ISSUE TITLE
Active indent guide is not highlighted for wrapped lines

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#49344]
From @Muchiachio
Extracted from https://github.com/Microsoft/vscode/issues/49173#issuecomment-386513066

---

Also if they are too long horizontally and word wrap is enabled, wrapped lines don't get the highlight.
![image](https://user-images.githubusercontent.com/6647444/39614780-1c93959c-4f7b-11e8-823a-e0c89d7d23e4.png)

**Comment by patrickfatrick** [comment]
Also lines with no code or white space.
