### ISSUE TITLE
Verified false breakpoint w/message does not reflect message in breakpoint list UI

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#4935]
- VSCode Version: 0.10.14-insider
- OS Version: Windows 10 1511

Steps to Reproduce:

1. Install PowerShell extension
2. Open Examples folder under the PowerShell extension directory
3. Set a breakpoint in DebugTest.ps1 on any line (with script on it).
4. Close VSCode and from Windows explorer or console, rename DebugTest.ps1 to DebugTest2.ps1
5. Reopen VSCode and the Examples folder.  Note in the Debug view, the breakpoint is still set on DebugTest.ps1
6. Select the DebugTest2.ps1 file and start debugging the script. 
7. Note that there is no indication that the breakpoint in the Debug view didn't get set. 

I would have expected at least the tooltip to display the message that we return from the debug host e.g.:
```javascript
    {
      "type": "response",
      "request_seq": "2",
      "command": "setBreakpoints",
      "success": true,
      "body": {
        "breakpoints": [
          {
            "verified": false,
            "message": "Source does not exist, breakpoint not set.",
            "source": "c:\\Users\\Keith\\.vscode-insiders\\extensions\\ms-vscode.PowerShell-0.5.0\\examples\\DebugTest.ps1",
            "line": 23,
            "column": null
          }
        ]
      }
    }
```
I get that the message is normally meant for the tooltip on the breakpoint glyph in the editor gutter but if the user doesn't happen to have that file open (or it does not exist anymore), they won't see the error.  

I think the breakpoints list in the Debug should "reflect" breakpoints that failed verification and provide the user with a way to see the message returned by the debug host.

https://github.com/Powershell/PowershellEditorServices/issues/195

**Comment by isidorn** [comment]
@rkeithhill and where would you shoud that message in the breakpoints view without introducing too much clutter. I suggest to show it on hover. What do you think?

**Comment by rkeithhill** [comment]
@isidorn I was thinking that the Breakpoints viewlet could show a glyph indicating there is a problem with the breakpoint and provide a tooltip to display the message e.g.:

![vscode_invalid_breakpoint](https://cloud.githubusercontent.com/assets/5177512/14534792/f9de7758-0227-11e6-8a67-78ee560c3bcf.png)

**Comment by isidorn** [comment]
Now if the breakpoint is unverified we show the message on hover and we show the whole breakpoint grayed out - same as how we show all breakpoints when you deactivate them.
Let me know if you like it

**Comment by vsccarl** [comment]
@isidorn I'm not able to verify this fix in the latest alpha. With the breakpoint set in the now nonexistent original DebugTest.ps1 I am also not able to debug other files.

**Comment by rkeithhill** [comment]
@vsccarl the issue with not being able to debug with the PowerShell is a known issue with the PowerShell extension.  We should have a fixed version (0.6.0) released in a week or so.  For now, you can work around this by setting a breakpoint in your program and then you should be able to debug.

**Comment by rkeithhill** [comment]
@isidorn OK, checked the PSES ext daily bits and I still don't see the breakpoint grayed out and there is no hover tip.  Now I am checking this in the BREAKPOINTS viewlet which I assume is what you're talking about, right?  Because the breakpoints in question are for files that no longer exist so it would be impossible to see the grayed out breakpoint in the editor window.  :-)

**Comment by isidorn** [comment]
@rkeithhill yeah, it is in the breakpoints veiwlet :) Today is last game of endgame, which means we only look at critical bugs, thus I will investigate why is this not fixed on monday, though that means it will only be available in our may release.
I myself have seen this working in action. Are you sure the adapter sends verified false for these breakpoitns?

**Comment by rkeithhill** [comment]
Yes we set verified to false. Is there anything else in this response message that might be wrong?

Log file snippet from debug session:
```
    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": "3",
      "command": "setBreakpoints",
      "success": true,
      "body": {
        "breakpoints": [
          {
            "verified": false,
            "message": "Source does not exist, breakpoint not set.",
            "source": "c:\\Users\\Keith\\.vscode-alpha\\extensions\\ms-vscode.PowerShell-0.5.0\\examples\\DebugTest.ps1",
            "line": 18,
            "column": null
          }
        ]
      }
    }
```

**Comment by isidorn** [comment]
Found the issue - now it should work

**Comment by rkeithhill** [comment]
@isidorn I've confirmed the fix.  Thanks!
