### ISSUE TITLE
vscodedebug Nodejs   connect ECONNREFUSED 127.0.0.1

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#49357]
- VSCode Version:1.23.0
- OS Version:10.13.4
- node Version: 10.0.0
- nodemon Version : 1.17.4

Steps to Reproduce:

1. when  i  use  nodemon debug nodejs .when i edit code make node server auto restart .but when i start nodeserver about one minute later  vscode will alert form tell me 

![image](https://user-images.githubusercontent.com/3990411/39696754-45acc2a2-5221-11e8-8980-8dc39974810d.png)

launch.js config 

```
"configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "media-platform",
            "runtimeExecutable": "/usr/local/bin/nodemon",
            "runtimeArgs": [
                "--debug"
            ],
            "restart": true,
            "program": "${workspaceFolder}/index.js",
            // "sourceMaps": true,
            "skipFiles": [
                "${workspaceRoot}/node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ],
            "protocol": "inspector"
        }
    ]
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by tomcooksey** [comment]
I get this same issue after latest update! Help -- stuck!

**Comment by roblourens** [comment]
So it doesn't reattach after nodemon restarts? Or, does that message pop up while you are debugging?

**Comment by tomcooksey** [comment]
It pops up for me when I try and start Node from inside VS Code, this is my launch.json 

```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Edvent",
            "program": "${workspaceRoot}/server/server.js",
            "runtimeExecutable": "/Users/tomcooksey/.nvm/versions/node/v6.10.0/bin/node",
            "env": {
                "ADMIN_PASSWORD": "xxxxxxxxxxxx",
                "AWS_ACCESS_KEY_ID": "xxxxxxxxxxxxxxx",
                "AWS_SECRET_ACCESS_KEY": "xxxxxxxxxxxxxxxxxx",
                "S3_BUCKET": "xxxxxxxxxxxxxx",
                "NODE_ENV": "development",
                "ADMIN_EMAIL": "xxxxxxxxxxx",
                "SITE_URL": "xxxxxxxxxxxxx",
                "SENDGRID_API_KEY": "xxxxxxxxxxxxxx"
            }
        }
    ]
}
```

**Comment by roblourens** [comment]
@tomcooksey You aren't using nodemon, your issue is unrelated, please open a new issue.

**Comment by zhiqiang21** [comment]
There are some mistakes in  my code ,when i run it .  it will pops up this  window.

**Comment by roblourens** [comment]
Does it say "Auto Attach: On" in the status bar?

**Comment by zhiqiang21** [comment]
"Auto Attach: Close   "   Is there anything to do with this

**Comment by hatpick** [comment]
Mine says off, but I get the popup with the error (timeout is 10 seconds)

**Comment by zhiqiang21** [comment]
i use both 'auto attach: on' and 'auto attach:off' 。my vscode will also  often pop up.

**Comment by roblourens** [comment]
I can't tell whether this is https://github.com/Microsoft/vscode/issues/49403. I'm guessing it is somehow.

@hatpick You can increase the timeout in your launch config, try that.

**Comment by hatpick** [comment]
this is what I had
```
       {
            "name": "Electron: Main",
            "type": "node",
            "protocol": "inspector",
            "console": "integratedTerminal",
            "request": "launch",
            "program": "${workspaceFolder}/main.js",
            "preLaunchTask": "my gulp pretask",
            "env": {
                "NODE_ENV": "development"
            },
            "sourceMaps": true,
            "outFiles": ["${workspaceFolder}/**/*.*"],
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
            "timeout": 30000
        }
```
And it was working before 1.23.1, then I had to remove these two `"protocol": "inspector",
"console": "integratedTerminal"` to fix it.

**Comment by roblourens** [comment]
Can you open a new issue @hatpick?
