### ISSUE TITLE
Integrated terminal sluggish when expanded

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [Microsoft/vscode#49352]
- VSCode Version: 1.23.0
- OS Version: mac os 10.13.4

Steps to Reproduce:

1. maximize terminal pannel size
2. start typing or scrolling
3. observe text appearing w/ a big delay
3. observe scrolling console content to be very sluggish (vscode's process explorer CPU usage spikes to 200% for processes w/ name `window` and `gpu-process`)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ishaanbahal** [comment]
Facing this same issue since latest release. A lot of flickering (whole vscode flickers) on resizing the terminal window. And it has become fairly sluggish, there is visible lag. I am using the terminal in side dock mode, non maximized.

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/1360

**Comment by ivanvoznyakovsky** [comment]
@Tyriar still experiencing the issue when terminal window is expanded. Both DOM and canvas modes are sluggish.
MacBook Pro (Retina, 15-inch, Late 2013) 
2.3 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 750M 2048 MB/Intel Iris Pro 1536 MB
