### ISSUE TITLE
TypeScript suggestions are broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#49350]
Suggestions are broken this morning on Selfhost. I'm using VS Code's TypeScript version: 2.9.0-insiders.20180503

Other language features seem to work.

![image](https://user-images.githubusercontent.com/22350/39693811-992e4ed2-51e5-11e8-88be-9cea0097be9c.png)

**Comment by neilsustc** [comment]
Code formatter seems not to work either.
