### ISSUE TITLE
Searching user settings is ineffective

### ISSUE THREAD

**Issue by jtanx** [Microsoft/vscode#49356]
- VSCode Version: 1.22.2
- OS Version: Windows 10 1709

Steps to Reproduce:

1. Open the user settings page
2. Be in the user settings pane
3. Press Ctrl+F, expect to be able to search the user settings JSON.
4. Instead, focus is stolen to the 'main' search panel. While matching text is sort of highlighted in the user JSON, it's not automatically scrolled to, making it very hard to find particular settings if the user JSON is large. I expect behaviour similar to doing 'Ctrl+Shift+P' and choosing 'Find'.

It does not scroll the user settings pane
![image](https://user-images.githubusercontent.com/5137410/39696638-a520abee-5231-11e8-9ded-2fa2d1a261e4.png)

Instead, if I do:
![image](https://user-images.githubusercontent.com/5137410/39696664-bb6fdc94-5231-11e8-8047-48b690c46989.png)

I get
![image](https://user-images.githubusercontent.com/5137410/39696688-cd4f9ee0-5231-11e8-8f4c-ba185040fb71.png)

Which is what I expect.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
> While matching text is sort of highlighted in the user JSON, it's not automatically scrolled to

You can scroll to the matching settings on the right side by pressing "enter" to page through the results.

You can change the keybindings yourself if you want, like


```
{
        "key": "cmd+f",
        "command": "-settings.action.search",
        "when": "inSettingsEditor"
},
```

Also we are working on a totally new settings UI, follow https://github.com/Microsoft/vscode/issues/3355 for updates.

**Comment by jtanx** [comment]
> You can scroll to the matching settings on the right side by pressing "enter" to page through the results.

I just tried, and the only thing that happens is it tabs through the search results on the *left hand* pane, not my user settings.

Using the keyboard shortcut as suggested does work for the *right hand* pane, but then the *left hand* pane becomes unsearchable from a shortcut, which isn't ideal either.
