### ISSUE TITLE
Reload TS file doesn't preserve editor scroll/cursor position

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#49351]
On today's Insiders, if I reload the workbench when a TS file is focused, the cursor and scroll positions aren't restored. This doesn't happen with other file types.

**Comment by bpasero** [comment]
@joaomoreno can you share a video? I cannot reproduce.

**Comment by joaomoreno** [comment]
Yeah I also can't reproduce at home... Hmm...
