### ISSUE TITLE
Tree should differentiate between selecting/clicking an item or its twistie

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#49368]
Selecting `ITree` or the triangle in front of it is currently the same things... One should be able to tell them apart

<img width="293" alt="screen shot 2018-05-07 at 15 50 32" src="https://user-images.githubusercontent.com/1794099/39705451-bd113ca0-520e-11e8-968b-20a3492d61b5.png">

**Comment by joaomoreno** [comment]
Done!
