### ISSUE TITLE
Underscore is not Visible in Terminal

### ISSUE THREAD

**Issue by Aditya7861** [Microsoft/vscode#49360]
- VSCode Version: 1.23.0
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. Whenever I put underscore in inbuilt terminal it shows just blank space 
2. I tried reinstalling again then also got the same problem

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
