### ISSUE TITLE
Extensions are not working

### ISSUE THREAD

**Issue by highskillzz** [Microsoft/vscode#49369]
After upgrading to the latest version, none of the extensions are showing any recommendations like they are supposed to no matter, how many times I remove and add them again.

**Comment by ffloimair** [comment]
I'm seeing the same problem with a fresh installation of 1.23.0 on MacOS X. No extensions are found when searching for extensions or selecting "recommended extensions".

Is there any way to get download the previous version as a workaround for now? The download on the web only offers the latest version.

**Comment by ffloimair** [comment]
Actually the F1 trick made them immediately visible. Thanks for the hint.
However I have never had this issue before on any machine (Windows, Linux or Mac) and immediately after install it didn't show anything when clicking at the recommended extensions or when searching for an extension. After the F1 trick everything was suddenly appearing. Now it works, so I'm happy.
I'll try to reproduce it on another machine though and let you know if I'm seeing the same problem again.

**Comment by ramya-rao-a** [comment]
> it didn't show anything when clicking at the recommended extensions 

Just to be clear, what exactly are you referring to when you say "clicking at the recommended extensions"? Is it the "recommended" section that shows up along with "installed" section? Or is it the "Show Recommended Extensions" from the menu? Can you provide a screenshot?

**Comment by highskillzz** [comment]
My problem is different, to describe it before updating I have an extension called express snippets and when I type app it shows be snippets but after updating it has completely stopped even other extensions are showing this behavior

**Comment by ramya-rao-a** [comment]
@highskillzz So your problem is that when you are searching for extensions, nothing is showing up? When you clear all text from the search box, do you see your installed extensions? Can you share some screenshots?

**Comment by ffloimair** [comment]
Yes, i meant the "recommended" section on the left when clicking at extensions. I never did anything via the menu in regards to extensions.
In the aftermath it seemed that the list of available extensions was not fetched until the F1 trick.
It's working flawlessly since then.

**Comment by ramya-rao-a** [comment]
@highskillzz We haven't heard back from you, so am assuming that things are working as expected.
