### ISSUE TITLE
Integrated Terminal canvas rendering issues

### ISSUE THREAD

**Issue by cideM** [Microsoft/vscode#49367]
- VSCode Version: Version 1.24.0-insider (1.24.0-insider)
- OS Version: macOS High Sierra 10.13.4

Steps to Reproduce:

1. Open integrated terminal 
2. Run command that does a lot of writing to stdout (or so I assume) (e.g., `yarn test` or `jest ./path/to/testfile`, which runs a suite of `jest` tests) **with colors**
3. Terminal now exhibits what I would call ghosting

<img width="555" alt="screen shot 2018-05-07 at 15 40 11" src="https://user-images.githubusercontent.com/4246921/39705228-0e7ff5b4-520e-11e8-90e7-ee1642b2052d.png">
<img width="945" alt="screen shot 2018-05-07 at 15 44 37" src="https://user-images.githubusercontent.com/4246921/39705229-0ed3d436-520e-11e8-9a77-b87cf76a4913.png">

(second screenshot is really dark, but you can make out text even though **I cleared the terminal**)

Steps that **solve** the issue
1. Open integrated terminal 
2. Run `jest --colors=false ./path/to/testfile` and everything works
 
Does not occur in VSC stable darwin.

Does this issue occur when all extensions are disabled?: Yes
Other startup flags I tried:

 * --disable-gpu
 * --disable-gpu-blacklist
 * --force-gpu-rasterization

Also, clearing the terminal repeatedly removes the ghosting but if the command had been running for a long time a faint echo of the output remains.

**Comment by yume-chan** [comment]
Actually, it's earlier than #49438, but Microsoft is closing duplicates to that.

**Comment by cideM** [comment]
This is fixed with the most recent update

**Comment by Tyriar** [comment]
Should be fixed in latest Insiders, see https://github.com/Microsoft/vscode/issues/49438
