### ISSUE TITLE
Regression overlapping rendering of text in integrated terminal

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#49371]
Issue Type: <b>Bug</b>

Regression overlapping rendering of text in integrated terminal.  See screen shot.
![image](https://user-images.githubusercontent.com/2301847/39707985-224efaf8-51d3-11e8-8d77-8210a83032cf.png)

![may-07-2018 08-48-12](https://user-images.githubusercontent.com/2301847/39708105-7f0a2b5a-51d3-11e8-8566-53fd0f107547.gif)

VS Code version: Code - Insiders 1.24.0-insider (d29620f2ba89327f51bb6fb2f05dfdd65e2fcafe, 2018-05-07T08:49:53.483Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron /Users/junger/desktop/Untitled.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
sort-lines|Tyr|1.6.1
vscode-eslint|dba|1.4.8
prettier-vscode|esb|1.3.1
flow-for-vscode|flo|0.8.1
python|ms-|2018.4.0
java|red|0.24.0
vscode-fileutils|sle|2.8.1
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.7.0

</details>

**Comment by cideM** [comment]
I think you are running into the same bug as I have in #49367

**Comment by Tyriar** [comment]
Should be fixed in latest Insiders, see https://github.com/Microsoft/vscode/issues/49438
