### ISSUE TITLE
Webview API: incomplete docs and typescript/intellisense

### ISSUE THREAD

**Issue by rwnkl** [Microsoft/vscode#49372]
- VSCode Version: 1.23.0
- OS Version: Windows 10 Pro 1803

Docs: vscode namespace API
window.createWebviewPanel(viewType: string, title: string, position: ViewColumn, options?: !!!MISSING TYPE intersection): WebviewPanel

TypeScript/IntelliSense:
- function window.createWebviewPanel missing; there is window.createWebview
- object WebviewPanel missing

**Comment by mjbvz** [comment]
You need to upgrade your targeted VS Code version to 1.23+ in the package.json `engines` section. After doing this, run npm install to pull in the latest `vscode.d.ts`
