### ISSUE TITLE
Terminal API: Shared terminal won't send data for subsequent task executions

### ISSUE THREAD

**Issue by alpaix** [Microsoft/vscode#49379]
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:10.813Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

#### Steps to Reproduce
1. Add a task to a project with `"presentation.panel": "shared"`
```js
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "start",
            "problemMatcher": [
                "$eslint-compact"
            ],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            "isBackground": true
        }
    ]
}
```
2. Run the task in a task terminal with a listener attached to `onData`. 
3. Observe data being sent to the listener.
4. Run the task again.

#### Expected
The listener receives data sent to the terminal.

#### Actual
No data sent.

**Comment by dbaeumer** [comment]
@Tyriar assigning to you since the onData is on the terminal in the extension API. Please ping if I need to do something special in the shared use case.

**Comment by Tyriar** [comment]
I've assigned it to May so I'll try get to it, I'm a bit overwhelmed this iteration so I hope it will get done but it may slip.

**Comment by aeschli** [comment]
Verified that the second invocation of the task still results in `onData` callback.
