### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by pedrogallon** [Microsoft/vscode#49373]
- VSCode Version: 1.22.2
- OS Version: Win7 x64

Steps to Reproduce:

1. Check for updates
2. Install update

[Log file (vscode-inno-updater.log)](https://file.io/miAzp3)

Does this issue occur when all extensions are disabled?: no tested

**Comment by joaomoreno** [comment]
@pedrogallon I can't seem to download that log file, do you mind reuploading it?

**Comment by joaomoreno** [comment]
Does the `C:\Program Files\Microsoft VS Code\Code.exe` file exist at all?
