### ISSUE TITLE
editor.codeActionsOnSave conflict "tslint.autoFixOnSave": true,

### ISSUE THREAD

**Issue by Giancarlo1974** [Microsoft/vscode#49370]
visual studio code 
Versione 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Data 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Nodo 7.9.0
Architettura x64

Windows 10

Steps to Reproduce:

1. file -> preference

// Place your settings in this file to overwrite the default settings
{
  "workbench.colorTheme": "Visual Studio Dark",
  "php.validate.executablePath": "C:/xampp/php/php.exe",
  "php.executablePath": "C:/xampp/php/php.exe",
  "php.suggest.basic": true,
  "workbench.iconTheme": "vscode-great-icons",
  "workbench.startupEditor": "newUntitledFile",
  "php.memoryLimit": "2048M",
  "typescript.check.tscVersion": false,
  "workbench.startupEditor": "newUntitledFile",
  "window.zoomLevel": 1,
  "editor.tabSize": 2,
  "editor.detectIndentation": false,
  "editor.insertSpaces": true,
  // Consente di configurare le impostazioni dell'editor di cui eseguire l'override per il linguaggio [yaml].
  "[vue]": {
    "editor.insertSpaces": true,
    "editor.tabSize": 2
  },
  "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
  "prettier.singleQuote": true,
  "prettier.eslintIntegration": true,
  "git.ignoreMissingGitWarning": true,
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/dist": true
  },
  "typescript.referencesCodeLens.enabled": true,
  "tslint.ignoreDefinitionFiles": false,
  "tslint.autoFixOnSave": true,
  "tslint.exclude": "**/node_modules/**/*",
/*
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
  */
  "telemetry.enableTelemetry": false
}

2) in any ts file, i try to write
//...
i got the tslint error:
[tslint] comment must start with a space (comment-format)

if i try to save, the editor fix the problem:
// ...

3) Now i enable

  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },

the autofix function doesn't fix

**Comment by egamma** [comment]
Fix will be in 1.0.30
