### ISSUE TITLE
There is no document formatter for 'typescript'-files installed.

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#49375]
Issue Type: <b>Bug</b>

1. Run `format document` in a TypeScript file.
2. Occasionally you will see the message `There is no document formatter for 'typescript'-files installed.` But I'm now unable to reproduce that and I get no message, and no formatting.
3. `tsserver.log` doesn't show any format requests.

VS Code version: Code - Insiders 1.24.0-insider (d29620f2ba89327f51bb6fb2f05dfdd65e2fcafe, 2018-05-07T08:55:27.483Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (8.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe .|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by andy-ms** [comment]
OK, I just looked back and now it's formatted. So it must just take a really long time?

**Comment by mjbvz** [comment]
@andy-ms Are you running the formatter immediately after restarting vscode?

**Comment by andy-ms** [comment]
@mjbvz Yes.

**Comment by andy-ms** [comment]
This might be a related issue: If I ask for completions soon after vscode I get bad completions, apparently from every word in the text.

![completion](https://user-images.githubusercontent.com/19274678/39764332-46baa894-5294-11e8-9d9b-520984f9ccf2.jpg)

Wait 10 seconds, request again, and they're good.

![completion_good](https://user-images.githubusercontent.com/19274678/39764451-7dbbb310-5294-11e8-95bf-1a35e572f045.jpg)

**Comment by andy-ms** [comment]
The latest vscode-insiders is formatting correctly if I wait 10 seconds after opening. There is still an error if I format too early. It seems to be related to when the blue bar for a git diff appears.

**Comment by mjbvz** [comment]
How soon after opening VS Code are you running format. The TS extension should be activated within the first few seconds, but the formatting request may time out while the tssserver is spinning up (by default we give formatters 1750ms to complete before cancelling them)

**Comment by andy-ms** [comment]
This was only reproducing on windows before. The latest update seems to have fixed it unless I'm really quick with the formatting request. It still seems like an odd error to display though.

**Comment by mjbvz** [comment]
Ok, closing it since it sounds like this issue is resolved unless you trigger the requests very quickly before we've had a chance to register the formatter

**Comment by jgauffin** [comment]
I get it every time i try the format document option from the command palette.
Intellisense works fine.

**Comment by robertmain** [comment]
Yep. I'm seeing it here too.
