### ISSUE TITLE
Sending custom request and custom event between debug adapter and extension

### ISSUE THREAD

**Issue by tarunbansal11** [Microsoft/vscode#49389]
Hi,

So far I was in the expression that DA only communicates with vscode debugger front-end (lives inside vscode) through DAP which is a wire protocol. Then I came across following under vscode module -

1.  DebugSessionCustomEvent (DA to extension)
2. customRequest (extension to DA)

My DA is written in C++.Please help me understand by answering some of following questions -

1. How are custom request and custom event transferred, is this a direct communication between extension and DA, or is it via vscode ? I mean if it via vscode than custom request first goes to vscode from extension and then vscode sends it to DA, right ? 
2. What is the meaning of "custom" here ? Are we customising the request and event available in DAP or we are customising the receiver side (extension instead of vscode) in case of event and sender side in case of request (extension instead of vscode) in traditional DAP.
3. How custom event is generated at DA side ?
 

Regards,
Tarun

**Comment by isidorn** [comment]
1. You can send a custom request from your extension by calling the `session.customRequest` api. This request is forwarded to the debug adapter
2. The meaning of the word custom is that you can send any command using it to your debug adapter. For example "stepOverTwoLines"
3. Custom event on the DA side simple fire an event like all other events and then you can listen to it on your extension side with the `onDidReceiveDebugSessionCustomEvent` listener

More details here https://code.visualstudio.com/docs/extensionAPI/api-debugging#_debug-session-api

**Comment by bvicinay** [comment]
How do you capture the custom request in the Debug Adapter?

**Comment by isidorn** [comment]
Just send an event with any reason except this speicified here and that will be treated as a custom event
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L258

This looks like node debug sending a custom event https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L454
