### ISSUE TITLE
Merge include/exclude makes UI less easy to use

### ISSUE THREAD

**Issue by pban1993** [Microsoft/vscode#49387]
Issue Type: <b>Bug</b>

I really dislike the "merge include exclude" feature, any chance this can be reverted via custom settings?

![image](https://user-images.githubusercontent.com/10714218/39715389-f37d64da-51e1-11e8-8316-bc3ee3bda906.png)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|31.89GB (19.31GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
gitblame|wad|2.4.2

</details>

**Comment by roblourens** [comment]
It was reverted in 1.23
