### ISSUE TITLE
Tab Highlighter Highlights Wrong Tab Line When on the First/Last Line of a Tab Block

### ISSUE THREAD

**Issue by Tresky** [Microsoft/vscode#49384]
Issue Type: <b>Bug</b>

Have any scoped code and place your cursor on the first or last line of a block. The tab-highlighter will highlight the tab line of a single scope above where it should. When the cursor is **within** the scope (not first or last line), it works as expected.

### Sample Code
```
function foo (cb) { // this scope gets highlighted
|   // placing cursor on if-statement on the below line will highlight the tab for the function-scope; expected the if-scope.
|   if (this.bar) { // < --- this tab-line *should* be highlighted
|       cb()
|   }
}
```

### Screenshot
<img width="461" alt="screen shot 2018-05-07 at 1 26 05 pm" src="https://user-images.githubusercontent.com/3902022/39715138-3b574420-51fa-11e8-83bd-6baa6787ecab.png">

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
erb|Cra|0.0.1
rails-snippets|Hri|1.0.8
vscode-docker|Pet|0.0.26
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.4
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
ruby|gro|0.0.6
haml|kar|1.1.0
vue|liu|0.1.5
dotenv|mik|1.0.1
python|ms-|2018.4.0
vetur|oct|0.11.7
vscode-code-outline|pat|0.1.1
vscode-icons|rob|7.23.0
language-stylus|sys|1.9.2

</details>

**Comment by alexandrudima** [comment]
Let's continue tracking in #49342
