### ISSUE TITLE
instanceof doesn't work for FileSystemError

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#49386]
- VSCode Version: 1.24.0 insiders - d29620f2ba89327f51bb6fb2f05dfdd65e2fcafe
- OS Version: Mac

I need to determine whether an error implements `vscode.FileSystemError`, but e.g. `vscode.FileSystemError.Unavailable('foo') instanceof vscode.FileSystemError` returns `false`.

For now, I'm using `typeof(error.name) === 'string' && error.name.includes('(FileSystemError)')`, but I'd prefer to use something less hacky.

**Comment by jrieken** [comment]
Hm.... Might be this https://stackoverflow.com/questions/41102060/typescript-extending-error-class#41102306

**Comment by jrieken** [comment]
Maybe for the recovery release...
