### ISSUE TITLE
Decorations: Show decorations in tabs

### ISSUE THREAD

**Issue by jackyliang** [microsoft/vscode#49382]
Hi there

I come from IntelliJ where the status of Git (uncommitted changes, staged, modified, etc) is highlighted in the tab like this: 

![screen shot 2018-05-07 at 9 56 17 am](https://user-images.githubusercontent.com/4315746/39713796-e8edb164-51dc-11e8-9a05-9c0436ae857d.png)

In some ways VS Code does that too by highlighting changes in the File Browser column on the left

![screen shot 2018-05-07 at 9 54 51 am](https://user-images.githubusercontent.com/4315746/39713740-b96427c0-51dc-11e8-8516-8ca6f04b9677.png)

Which is great! But I would love if I could have these highlighted file names displayed on the Tab as well. Is there a certain CSS or setting I could change to enable this? 

I did variations of Google of "VS Code highlight tab git" and the sorts, but nothing really comes up. I would appreciate if you could give me some guidance on this issue.

**Comment by jackyliang** [comment]
@joaomoreno @jrieken thanks for giving visibility to this issue! Is this a simple setting/CSS change or would is it a new feature?

**Comment by nicolasbadia** [comment]
Same, for me!
Coming from Atom and I really miss this feature.

**Comment by hasannizamani** [comment]
Coming from WebStorm I'm really missing this in VS Code, would speed up switching tabs.

**Comment by molizz** [comment]
Coming from Goland I'm really missing this in VS Code, would speed up switching tabs.

**Comment by trafium** [comment]
Coming from RubyMine I'm really missing this in VS Code, would speed up switching tabs.

**Comment by DisasterMan78** [comment]
Coming from having too many damn tabs open, I'm really looking forward to this in VS Code, would speed up switching tabs!

😄

**Comment by adamreisnz** [comment]
Coming from Atom I'm really missing this in VS Code, would speed up switching tabs.

**Comment by mohsinulhaq** [comment]
any update on this?

**Comment by yami0101** [comment]
Would also love to see this in VS Code.

**Comment by Ghostaunt** [comment]
I'm surprised to don't see this feature in vscode

**Comment by dan-grayson** [comment]
In October 2018 (v1.29), Highlight Modified Tabs was added for dirty files, but there still doesn't appear to be support for source control modified styling on tabs.

https://code.visualstudio.com/updates/v1_29#_highlight-modified-tabs

The Highlight Modified Tabs feature is not really useful if you have autosave enabled, which I expect most users do. Highlighting source control modified files would be far more useful and enable faster tab switching.

**Comment by DisasterMan78** [comment]
Unless you have data on how many users have autosave enabled, it's not really justification.
For those that do, it will have no effect. For those that don't it remains useful, and it's there anyway.

Totally agree that SC modified files would still be really helpful.

**Comment by fonziemedia** [comment]
Hello, has anyone found a way to do this via extension/hack? Really missing this feature..

**Comment by viraj892** [comment]
Coming from IDEA I'm really missing this in VS Code, would speed up switching tabs.

**Comment by KartikM123** [comment]
Anyone found a workaround?

**Comment by mattdaviscodes** [comment]
Also wondering where this stands.

**Comment by lleheny0** [comment]
Even just a plugin for this would be nice if it's not a planned feature.

**Comment by jrieken** [comment]
A first version of this is in master and will be in the next insiders release (https://code.visualstudio.com/insiders/). Editor decorations can also be configured via `workbench.editor.decorations.colors` and `workbench.editor.decorations.badges`

<img width="974" alt="Screenshot 2020-12-17 at 09 16 51" src="https://user-images.githubusercontent.com/1794099/102461918-6d91e400-4049-11eb-97d0-1a047ab86e1b.png">

**Comment by jrieken** [comment]
To verify: Make sure that editors show git and error decorations. Try with tabs and no tabs, with breadcrumbs and not breadcurmbs enabled.
