### ISSUE TITLE
welcome page links underline

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#49381]
- VSCode Version: 1.23.0
- OS Version: macOS

Steps to Reproduce:

1. Open Welcome Page
2. Move cursor to any link, you will see it will not be underlined like it is in Interactive Playground

**Comment by chrmarti** [comment]
We chose to not show underlines on the Welcome Page to keep the visual appearance smooth. E.g., when the user is not interacting with the page, but just moves the mouse across. The Welcome Page is different in this from the Playground in that it automatically opens on startup and is shown more often without the user immediately interacting with it.
