### ISSUE TITLE
Inconsistent naming of colors

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#49393]
`textLink.activeForeground`

**active** name is misleading. Wouldn't it be better to call it **hover**?
Examples of the right wording: 
```
scrollbarSlider.activeBackground
scrollbarSlider.hoverBackground

tab.activeBorder
tab.hoverBorder
```

**Comment by aeschli** [comment]
The `textLink.activeForeground` is used for both :hover and :active.

I update the doc, but would rather not split it up or rename for now.
