### ISSUE TITLE
Update Visual Studio Code to version 1.23.0 fails

### ISSUE THREAD

**Issue by azarc3** [Microsoft/vscode#49394]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1981003/vscode-inno-updater.log)
Issue Type: <b>Bug</b>

Visual Studio Code fails to update using the tooling provided in the menus. The error in the log file is **Access Denied** (on Code.exe)

1. Launch VS Code via Cortana Search; hit enter to select matched result.
2. Click Gear Icon; if already checked, click **Install Update**, otherwise, click **Check for Updates** and then **Install Update**.
3. If necessary, progress though dialog(s).
4. Error occurs.

Does this issue occur when all extensions are disabled?: Yes

Failure behavior is the same across at least 10 attempts to install.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.89GB (8.19GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|0.3.93

</details>

**Comment by azarc3** [comment]
Is similar to #48000 but not the same generated log file. Also, #48000 is already closed... and obviously this is still happening.

**Comment by dexblack** [comment]
Rendering in Maximized mode is broken.
A window titled "Welcome - folder_name - Visual Studio Code" takes over the top 12% or so of the window and hides the IDE display. The window does not respond to Max/Min/Close buttons.

Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Windows 10 x64 Professional

**Comment by GerbenRampaart** [comment]
Exact same thing for me.

**Comment by GerbenRampaart** [comment]
💩  <- added a poop emoji because I recently learned the vscode team filters for that.
