### ISSUE TITLE
Can't debug proposed API even when 'enableProposedApi' is set to true

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#49396]
- VSCode Version: 1.23.0
- OS Version: Windows 10 x64
- Node.js Version: 10.0.0

Steps to Reproduce (repro project: [vscode-ext-demo](https://github.com/cnshenj/vscode-ext-demo)):
1. Use `yo code` to generate a vscode extension project
2. Add `"enableProposedApi": true` to package.json
3. Use a proposed API in the `sayHello` command, e.g.:
```
vscode.workspace.fetchTasks().then(tasks => vscode.window.showInformationMessage(`# tasks: ${tasks.length}`));
```
4. Debug the extension

What I got is this error: "Running the contributed command 'extension.sayHello' failed.".
By enabling breakpoints in "All Exceptions" I can see the exception happens here:
File `extHost.api.impl.ts`
Line `75`
Function `throwProposedApiError`
Message `TypeError: Cannot read property 'id' of undefined`

There are two issues:

1. Why proposed API still can't be used when `enableProposedApi` is true?
2. Why parameter `extension` is `undefined`?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
@sandy081 Could this be caused by us checking the value on the main side?

**Comment by jrieken** [comment]
@cnshenj How sure are you that this happens with **1.23**? We have a known issue with proposed api and latest insiders **1.24**, but its the first time we hear that about stable

**Comment by cnshenj** [comment]
@jrieken I don't have any insider builds installed. I only have 1.23 stable on my dev box.

You can probably repro in 5 minutes by cloning my test project (URL in OP), then opening it using 1.23 and hitting F5.

**Comment by sandy081** [comment]
@jrieken Is there a difference if it is computed on the main side in this scenario while developing extension?

**Comment by sandy081** [comment]
I also wonder if we support proposed APIs in Stable version. My understanding is that it is only supported in Insiders

**Comment by cnshenj** [comment]
I can fully understand proposed API only being available in Insider builds. The problem is the inconsistency between the product and the documentation. The Insider builds are released separately and have a different version number. The proposed APIs are documented in release notes of 1.23 stable, which do not mention Insider builds at all. While I actually have to use 1.24-insider to debug proposed APIs.

At least mentioned Insider builds requirement together with the `enableProposedApi` property in release notes.

**Comment by gregvanl** [comment]
We now include details in the release notes Proposed API section where proposed APIs are discussed.
