### ISSUE TITLE
Should file tree get focus after opening a workspace for the first time?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#49395]
Issue Type: <b>Feature Request</b>

Currently it opens a workspace with 0 open editors and revealed file tree, yet focus is not within the viewlet.

**Comment by isidorn** [comment]
I have no strong feeling about this but I believe after open
1. focus should be in the editor if there is some editor open
2. otherwise focus should be in the explorer

We accept PRs that fix this.
@bpasero fyi
