### ISSUE TITLE
Color Theme completely changed

### ISSUE THREAD

**Issue by rodrigoestevao** [Microsoft/vscode#494]
I used to edit my TSQL scripts on Visual Studio Code. When was added the feature to support Themes, the Dark themes was completely changed (at least for TSQL scripts). Ok, I started using the Monokai Dimmed, and now, on the last version, it was completely changed again. Why do this on existing themes??? Would be easier just create another theme ? :(

**Comment by aeschli** [comment]
@rodrigoestevao Sorry for that, there has been some major changes in the way we tokenize and colorize, and we weren't able to stay compatible. We now use text mate grammar files to drive our colorizer with the advantage that they playing nicely with text mate themes and there is a bigger community that maintains these grammars.
There are now plenty of themes to choose from and I hope you find one that you like.
