### ISSUE TITLE
ja-JP translation of update notification's "Later" label mismatches meaning in ja-JP custom

### ISSUE THREAD

**Issue by saneyuki** [Microsoft/vscode#4940]
## Version

- VSCode Version:
  - 0.10.13-insider
  - with ja-JP locale
- OS Version:
  - Windows 10
  - OSX 10.11

## Steps to Reproduce

1. Update vscode from menu's "Check for Update..."
2. See the notification bar which display `Visual Studio Code - Insiders will be updated after it restarts.` in English.

## Actual Result

- "Later" button's label is "後続" if you use vscode with ja-JP locale.
  - This translation mismatches ja-JP localization custom. This "Later" means "Restart vscode Later", but the current translation ("後続") means "following" or "next" in English.

## Expected Behavior

Its label should be "後で" or other words which means "Restart later".

**Comment by johnliu2016** [comment]
@saneyuki Can you attach a s/s showing the mistranslated "Later" label? That would help understand the context

**Comment by saneyuki** [comment]
> Can you attach a s/s showing the mistranslated "Later" label? That would help understand the context

Sorry, I forgot to take the screenshot. I need to wait the next insider update.

**Comment by saneyuki** [comment]
@johnliu2016 

> Can you attach a s/s showing the mistranslated "Later" label? That would help understand the context

Sorry, I forgot to take the screenshot. I need to wait the next insider update.

**Comment by johnliu2016** [comment]
@saneyuki We went ahead to fix the jpn string as suggested, feel free to verify on update.
