### ISSUE TITLE
Rendering in split visual diff mode is choppy

### ISSUE THREAD

**Issue by justinmchase** [Microsoft/vscode#49408]
Issue Type: <b>Bug</b>

When I am using split visual diff mode visible regions all over the app are blinking in and out of visibility. So basically random rectangles are blinking in and out all over the app. Scrolling or clicking or typing or zooming in/out will cause it to flash and different regions to be drawn or not.

When using any other view I never / rarely have this issue it is specifically the side-by-side visual diff.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
solidity|Jua|0.0.43
vscode-docker|Pet|0.0.26
vscode-standard-format|che|0.0.12
vscode-standardjs|che|1.2.1
githistory|don|0.4.0
gitlens|eam|8.2.4
vscode-dimmer|hoo|2.1.0
copy-markdown-as-html|jer|1.1.0
php-cs-fixer|jun|0.1.62
prettify-json|moh|0.0.3
azure-account|ms-|0.4.0
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.4.3
cucumber|ste|0.11.5
gitblame|wad|2.4.2

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@justinmchase This looks like something is broken within Chromium. Does this reproduce when launching with `code --disable-gpu` ?

**Comment by justinmchase** [comment]
Just tried it, yes it does.

Also, I am noticing in the `GPU Status` section of my report it says `unavailable_software` or `unavailable_off` for each category. Is it possible that I have the opposite problem, is there a way to force it to enable gpu?

**Comment by justinmchase** [comment]
Wow, ok so I tried `code --enable-gpu .` and that is a night and day difference. I noticed it chop slightly once but fixed it self immediately and the rendering of the entire application in general even in this view is way better.

So I suppose this issue could be modified to just affect non-gpu rendering? Also, why would code not go to GPU rendering by default for me? Can I set this setting globally by default?

**Comment by alexandrudima** [comment]
VSCode is built with Electron, which is built with Chromium.

AFAIK, Chromium decides all of this using some built-in lists. i.e. they check the hardware make or driver version and decide to turn on/off GPU acceleration based on that.

There is nothing in VSCode's code-base which controls that. The best would be if you could reproduce similar problems in other Chromium based applications, such as Chrome, and reach out to their issue tracker.

If you cannot reproduce in Chrome, it is possible that the issue has already been fixed, and it will just take some time until we update to a newer version of Electron which contains a newer version of Chromium.
