### ISSUE TITLE
can't install extensions

### ISSUE THREAD

**Issue by MikeHolder** [Microsoft/vscode#49404]
Issue Type: <b>Bug</b>

attempting to install the extension through the VSCode marketplace thing in VScode doesn't do anything. I have to go to the site and install the thing by downloading the VSIX. 

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (26.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0

</details>

**Comment by MikeHolder** [comment]
![image](https://user-images.githubusercontent.com/16567422/39721552-884eb6cc-5205-11e8-9cbd-7e4129ae50e6.png)
 when using the terminal to install the extension this is what it throws.

I have completely uninstalled VSCode, removed it from %appdata%/roaming/code and %user%/.vscode, rebooted, and then reinstalled VSCode making sure to have it add everything to the PATH and it still doesn't work.

**Comment by MikeHolder** [comment]
[2018-05-07 14:52:15.758] [renderer6] [error] File not found (file:///c:/Users/Michael/AppData/Roaming/Code/logs/20180507T145113/main.log): Error: File not found (file:///c:/Users/Michael/AppData/Roaming/Code/logs/20180507T145113/main.log)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1277:219)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2936:473
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\graceful-fs\graceful-fs.js:241:16
    at FSReqWrap.oncomplete (original-fs.js:114:15)

**Comment by MikeHolder** [comment]
So, I sort of figured it out. Apparently the issue was the TEMP variable in the Environment Variables. I removed it and it works perfectly now. /shrug

**Comment by isidorn** [comment]
@MikeHolder seems like it work now, closing it. 
@sandy081 fyi
