### ISSUE TITLE
Node.js debugging async emitHookFactory

### ISSUE THREAD

**Issue by Cellule** [Microsoft/vscode#49402]
Issue Type: <b>Feature Request</b>

While debugging node.js with async function, I often end up in the function emitHookFactory from the node internal scripts.
The debugging experience would be better if that function was skipped as it has no value to the user.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17665

**Comment by roblourens** [comment]
You can! Just add

```
"skipFiles": [
    "<node_internals>/**"
],
```

To your launch config

**Comment by Cellule** [comment]
Would you consider making this the default with a launch configuration of type node ?

**Comment by roblourens** [comment]
Possibly. Need to do some thinking around this and also https://github.com/Microsoft/vscode-chrome-debug-core/issues/245
