### ISSUE TITLE
Rename error disappear so fast that I can see them clearly

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#49411]
_From @davyzhang on May 7, 2018 1:31_

I didn't press any key during the showing of the message, just waited
![untitled 1](https://user-images.githubusercontent.com/576863/39680999-4bf9ccba-51d9-11e8-8bf2-46f5dbed5421.gif)

_Copied from original issue: Microsoft/vscode-go#1663_

**Comment by ramya-rao-a** [comment]
@jrieken Previously, rename errors would show up as notifications and would disappear only if user has cancelled/closed the notification. 
Now we see the rename error message inline and it stays for just about 3 seconds which is not enough for the users to read any extra information that the extension might have provided.

**Comment by jrieken** [comment]
Well, it's clearly not meant for such a verbose messages (and I have doubt the notifications UX can cope with that). Can't you abbreviate things and show more information in the output channel as we do it with other things?

**Comment by ramya-rao-a** [comment]
Fair enough. Will use the output channel.
