### ISSUE TITLE
Activity bar: missing commands for focusing to contributed views containers

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#49412]
Every default views container has a command for focusing to it:

```
workbench.view.debug
workbench.view.explorer
workbench.view.extensions
workbench.view.scm
workbench.view.search
```

While, as far as I know, one can't define custom commands for focusing to contributed views containers. 

If I have to use the mouse to use them then I'm just not going to.

----

There's the `workbench.action.openView` command, but it's just too slow switching views this way. Perhaps this could accept a `viewId` argument, so that we could actually use it for focusing to arbitrary views.

**Comment by sandy081** [comment]
@fabiospampinato There are similar commands to built in ones are registered for contributed ones. Please check in the keyboard shortcuts editor

![image](https://user-images.githubusercontent.com/10746682/39776495-565fb920-5301-11e8-8555-9efdf9f4a21c.png)

**Comment by fabiospampinato** [comment]
@sandy081 oh nice, they are even included in the default `keybindings.json`, thanks!

It would be helpful to mention this thing somewhere though, I see no trace of it in the release notes, and searching for `site:code.visualstudio.com/docs "workbench.view.extension"` on Google returns 0 results.

**Comment by fabiospampinato** [comment]
@sandy081 searching for "view.extension" in [April's release notes](https://code.visualstudio.com/updates/v1_23) gives 0 results.

**Comment by sandy081** [comment]
@fabiospampinato Only Command name `View: Open Package Explorer` was mentioned
