### ISSUE TITLE
Closing integrated terminal makes UI hang

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#49419]
Issue Type: <b>Bug</b>

Since updating to today's (5/7) Insiders Build, I've run into an issue where closing the integrated terminal will cause VS Code to hang and pop a dialog asking me to reopen or wait. The problem is intermittent, but I frequently open and close the integrated terminal and have run into the issue 3 or 4 times today.

VS Code version: Code - Insiders 1.24.0-insider (d29620f2ba89327f51bb6fb2f05dfdd65e2fcafe, 2018-05-07T08:55:27.483Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (20.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.0.7
bracket-pair-colorizer|Coe|1.0.48
gitlens|eam|8.2.4
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
sort-typescript-imports|mic|1.4.1
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.4.3
polacode|pnp|0.2.2
project-snippets|reb|0.5.0
vscode-icons|rob|7.23.0
vscode-todo-highlight|way|0.5.12

(3 theme extensions excluded)

</details>

**Comment by martellaj** [comment]
Been in Code all day with today's build. Just hit the issue again.

Version 1.24.0-insider
Commit 8a07c8d935998d1b1153dde0c5b337189d35cea0
Date 2018-05-08T05:16:07.736Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Tyriar** [comment]
@martellaj when this happens next could you try run `code-insiders --status` from the command line and paste in the output?

**Comment by martellaj** [comment]
@Tyriar Yes, I'll give it a go. Doing it in a terminal outside of VS Code will work, right?

**Comment by Tyriar** [comment]
@martellaj as long as a terminal is responsive (in a different window?)
