### ISSUE TITLE
Terminal redraw

### ISSUE THREAD

**Issue by eddiemoore** [Microsoft/vscode#49417]
Issue Type: <b>Bug</b>

Latest Insiders build is not drawing the integrated terminal properly. See Screenshot:
<img width="824" alt="screen shot 2018-05-08 at 9 48 49 am" src="https://user-images.githubusercontent.com/199016/39730490-41109212-52a5-11e8-9b4b-a3b3bdfe7064.png">

Things start overlapping inside and not clearing properly.

VS Code version: Code - Insiders 1.24.0-insider (d29620f2ba89327f51bb6fb2f05dfdd65e2fcafe, 2018-05-07T08:49:53.483Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 5|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4715647|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.18
graphql-for-vscode|kum|1.11.0
debugger-for-chrome|msj|4.4.3
vscode-icons|rob|7.23.0
language-stylus|sys|1.9.2
gitblame|wad|2.4.2
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.6.2
JavaScriptSnippets|xab|1.6.0

(1 theme extensions excluded)

</details>

**Comment by eddiemoore** [comment]
Additional screenshot
<img width="444" alt="screen shot 2018-05-08 at 9 53 16 am" src="https://user-images.githubusercontent.com/199016/39730570-af59a5ba-52a5-11e8-8fc8-9660b23c3df6.png">

**Comment by jaydenseric** [comment]
Same here:

<img width="806" alt="screen shot 2018-05-08 at 1 46 14 pm" src="https://user-images.githubusercontent.com/1754873/39737059-81f60d4a-52c6-11e8-9a26-db38d61ffbf7.png">

It happens when I attempt my lint npm script, which runs eslint and prettier in fix mode.

**Comment by jaydenseric** [comment]
Duplicates https://github.com/Microsoft/vscode/issues/49371 and https://github.com/Microsoft/vscode/issues/49367.

**Comment by Tyriar** [comment]
Should be fixed in latest Insiders, see https://github.com/Microsoft/vscode/issues/49438
