### ISSUE TITLE
Wrong code coloring when mixing templates with strings in Typescript

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#4941]
- VSCode Version: 0.10.14-insiders
- OS Version: Windows 10 x64

this line inside a .ts file make everything after that line to look like a string:

```ts
export function authUrl(id?: string){
   let token: string = id ? `?token=${issueToken({id: id}, 600, 'moip')}` : '';
    
   return /*...*/;
}
```

**Comment by aeschli** [comment]
This go fixed for the coming 'March' release. (Preview available at https://code.visualstudio.com/insiders)
