### ISSUE TITLE
A view can't be contributed to multiple places

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#49414]
Given the recent addition of contributable views containers I moved a view one of my extensions contributes from the explorer to its own section in the activity bar. But I also still want to support having the view in the explorer, as some people might like it better there, especially since views containers aren't keyboard-friendly (https://github.com/Microsoft/vscode/issues/49412).

Well, using the same view id in multiple places doesn't work (the view in the explorer is empty):

<img width="466" alt="screen shot 2018-05-07 at 23 43 47" src="https://user-images.githubusercontent.com/1812093/39728327-ba4190ea-5256-11e8-874b-911439a748f1.png">

I had to register the same view twice with 2 different ids to get it to work (and then use those ids in `package.json`):

<img width="611" alt="screen shot 2018-05-07 at 23 44 53" src="https://user-images.githubusercontent.com/1812093/39728328-ba61a42a-5256-11e8-9e96-542b571b9dca.png">

If this is a design choice and not a bug it doesn't make sense to me.

**Comment by fabiospampinato** [comment]
Because of this I also had to duplicate all my contributed right-click commands (https://github.com/Microsoft/vscode/issues/49449).

**Comment by sandy081** [comment]
Contributing the same view at multiple locations makes sense to me.

**Comment by sandy081** [comment]
@fabiospampinato After further thinking it does not makes sense to support a view with same id at multiple locations. Because view id is unique across and having multiple views with same id will cause ambiguity while using `TreeView` API. 

For your use case, the right approach would be to allow users to move views across view containers similar to how `Search view` can be moved between Sidebar and Panel. 

If this has to be done through extension API, right approach would be to provide an API to move a view.

**Comment by fabiospampinato** [comment]
> @fabiospampinato After further thinking it does not makes sense to support a view with same id at multiple locations. Because view id is unique across and having multiple views with same id will cause ambiguity while using TreeView API.

What specific API would be ambiguous? The way I think about multiple views with the same id is that they are basically the same thing that shows up in multiple places, in this sense it shouldn't be possible to "change" only one instance of this view without affecting the others.

> For your use case, the right approach would be to allow users to move views across view containers similar to how Search view can be moved between Sidebar and Panel.

That would be great, but I'm not sure if this addresses exactly my use case:

- My extension for managing projects contributes a view that shows you all your projects.
- It also contributes a views container to the activity bar, so it definitely makes sense to put said view in there.
- Someone may also want to display said view in the explorer too, since in the explorer you see the currently opened projects (workspace folders) it might make sense to also view all other projects available too.

This use case is definitely supported today, but the problems are:

- I have to register 2 ids for basically the same thing (minor annoyance)
- I have to duplicate all commands contributed to those views (slightly less minor annoyance) (fixing https://github.com/Microsoft/vscode/issues/33547 would remove this problem though).

**Comment by sandy081** [comment]
@fabiospampinato I mean the `TreeView` api. For example if you call `reveal` API, element which view should be revealed? They are not a same view showing in different locations, they are different views. Imagine if we open the panel location for contributing views.

If a view has to be shown at multiple places then it has to be duplicated.

**Comment by fabiospampinato** [comment]
Makes sense.

I'm closing this issue then, thanks.
