### ISSUE TITLE
JsDoc typed deconstructed parameters don't get picked up

### ISSUE THREAD

**Issue by MarcelRusu** [Microsoft/vscode#49420]
Vs code can't infer the type of a deconstructed object parameter from jsdoc

- VSCode Version: 1.22.2
- OS Version: x64 elementary OS 0.4.1 Loki

Steps to Reproduce:

1. write a function with deconstructed object parameter
2. try to document the type

```js
/**
 * @param { { x: number } } param0
 */
const f = ({ x }) => console.log(x)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is fixed in VS Code insiders builds which pick up a new TypeScript version
