### ISSUE TITLE
Successful build of VSCode on Windows 10, no exe created

### ISSUE THREAD

**Issue by ipkpjersi** [Microsoft/vscode#49424]
- VSCode Version: bfe73c4eacefaec00cb3fda0397843c55aa4f147
- OS Version: Windows 10 LTSB 2016

Steps to Reproduce:

1. Successfully install all dependencies
2. Run yarn
3. Run yarn run watch or yarn run compile
4. Try to run code.bat in the scripts folder

![](https://i.imgur.com/Vn4jFHA.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@ipkpjersi in the vscode folder is there a .build\electron folder containing the `Code - OSS.exe`

**Comment by ipkpjersi** [comment]
I'm re-opening this, how do I package VSCode for install? On Windows I ran: yarn run gulp vscode-win32-x64 but I do not see an exe I can run or install.

CC: @dbaeumer

**Comment by ipkpjersi** [comment]
Sorry for the double post, but while I am here, building and trying to install VSCode on Ubuntu 16.04 isn't working well either: 

![](https://i.imgur.com/KOJxC9A.png)

**Comment by dbaeumer** [comment]
@ipkpjersi if you build under Windows the generated executable is is a sibling folder to the `vscode` folder named `VSCode-win32-x64`.

The executable is still names `Code - OSS.exe`. The open source repository doesn't contain the scripts to build a VS Code install package 100% conforming to the one shipped in the official code install packages. Major reason being that the official packages are signed by MS. 

I close the issue. Please ping if something is still unclear.
