### ISSUE TITLE
Inline unit-test debugging for python was broken after taking the latest update

### ISSUE THREAD

**Issue by southwood** [Microsoft/vscode#49427]
My in-line unit test debug triggers for python disappeared with the last auto update. It took a lot to get that working given all the environment constraints I'm working with - can I revert to the previous version of VSCode somehow?

If you're going to ship frequently and prompt users to run the auto-updater, it would be nice to have a quick roll-back mechanism.

Also, I don't use twitter. I tried sending this with the "smily" emoji button in the bottom right only to lose my message after twitter told me I need to sign-up for a new account. This could be improved. Maybe jump to twitter immediately instead of providing a UX that seems to accept in-app feedback.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|Memory (System)|16.00GB (0.88GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0

</details>

**Comment by southwood** [comment]
Also VSCode is consuming a lot more CPU than it did prior to the update. Activity Monitor is showing "Code Helper" using 100% of one of my CPUs pretty much nonstop for the last 10min and I'm not doing anything in VSCode..

I'd really like a way to revert this update.

**Comment by isidorn** [comment]
As for the python issue pleae file it against the python extension.
As for the Code Helper cpu issue please file a new issue here following these steps https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks

**Comment by southwood** [comment]
@Isidorn Any tips for reverting to the previous version of VSCode? I didn’t update the extension. I suspect that if I were able to undo the VSCode update things would work again.

**Comment by isidorn** [comment]
@southwood we do not support that
