### ISSUE TITLE
Visual Studio Code should honor a editor.fontSize value smaller than 8

### ISSUE THREAD

**Issue by webermatthew** [microsoft/vscode#49428]
No matter how small you set "editor.fontSize" in visual studio code, it doesn't actually render any smaller than the "8" size. Go ahead, try "5" or "6" - it will just display the "8" size.

I'd really like to push my retina screen to the max and be able to pick smaller fontSizes – with a good pair of magnifying reading glasses or loupes, you can easily read smaller sizes. Super-small font sizes are incredibly helpful when working with a split editor on a laptop.

**Comment by alexandrudima** [comment]
Would you consider contributing a PR? I suggest to not go lower than 5 or 6, as folks have accidentally set a very small fontSize in the settings and were then blocked.

https://github.com/Microsoft/vscode/blob/b2c8d97d9b8817ded0eaf8419ee24905889a9edc/src/vs/editor/common/config/fontInfo.ts#L20

**Comment by alexr00** [comment]
Works nicely! It might be nice to have a minimum, similar to `task.quickOpen.history` so that it is very clear that numbers smaller than 6 don't do anything.

**Comment by alexandrudima** [comment]
Nice suggestion! Done!
