### ISSUE TITLE
fuck you

### ISSUE THREAD

**Issue by Hbllol** [Microsoft/vscode#49426]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.2.1|
|path-intellisense|christian-kohler|1.4.2|
|wpy-beautify|doingweb|2.0.10|
|vscode-html-css|ecmel|0.2.0|
|vscode-great-icons|emmanuelbeziat|2.1.27|
|auto-rename-tag|formulahendry|0.0.15|
|vue-snippets|hollowtree|0.1.5|
|beautify|HookyQR|1.3.0|
|vscode-filesize|mkxml|2.0.0|
|debugger-for-chrome|msjsdiag|4.1.0|
|vetur|octref|0.11.7|
|vuehelper|oysun|0.1.0|
|view-in-browser|qinjia|0.0.5|
|JavaScriptSnippets|xabikos|1.5.0|
|D3Snippets|yoyo|0.1.11|;

---

Steps to Reproduce:

1.
2.

**Comment by Hbllol** [comment]
code is very small  good ~

**Comment by VinLark** [comment]
Yeah, makes perfect sense
