### ISSUE TITLE
Saving as wrong encoding possibly lost contents

### ISSUE THREAD

**Issue by yh1224** [Microsoft/vscode#49423]
- VSCode Version: 1.23.0
- OS Version: Windows 10 (1803)

Steps to Reproduce:

1. Type multibyte characters.
2. Command Palette > Change File Encoding > Save with Encoding > Western (Windows 1252)
3. Close and reopen it.
4. All multibyte characters changed to '?'

Other commonly case:

1. Set autoGuessEncoding to true.
2. Open new file, type "テスト", save as UTF-8 and close it.
3. Open this file. It wrongly guessed as "Windows 1252".
4. Erase all content, type multibyte characters again, save and close it.
5. Reopen this file. It losts all multibyte characters. (changed to '?')

I can't notice losting contents until reopened it.
I want some alert for lost contents.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by yh1224** [comment]
I know it's my error in operation, but losting contents (without alert) is not kindness.

**Comment by yh1224** [comment]
same as #44505
