### ISSUE TITLE
after updated to the latest version, VS Code not recognizing a git repo workspace

### ISSUE THREAD

**Issue by komagic** [Microsoft/vscode#49422]
- VSCode Version:
- OS Version: win10

Steps to Reproduce:

1.  Bracket Pair Colorizer unable to work too
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by komagic** [comment]
VS Code not recognizing a git repo workspace，and yet VS Code shows: "This workspace isn't yet under git source control."

**Comment by joaomoreno** [comment]
What does `git status` return from that directory?

**Comment by paulohtobias** [comment]
I have the same problem and I don't know if I should open another issue so I'm commenting here.
`git status` returns from integrated terminal (I'm using cmd, not powershell)
```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by komagic** [comment]
today，i dont know why but it works again~~
