### ISSUE TITLE
Feature Request: Allow user to override contributes made by extension

### ISSUE THREAD

**Issue by ppggff** [microsoft/vscode#49430]
Be able to control or custom contributes made by extensions (maybe in the info-page of each installed extension), such as disable button in editor title, item in context menu.
This feature will make interface clear after install many extensions.

And further more, may be we could let user custom contributes to interface in a setting file.

**Comment by ppggff** [comment]
#44141 could be fixed with this feature.

**Comment by sandy081** [comment]
@ppggff Are you talking about disabling each contribution of an extension or an extension itself?

**Comment by sandy081** [comment]
If it is about fine grained control of disabling individual features of an extension, then I would like to close this out of scope. Otherwise, please reopen it and explain the requirement in detail. Thanks.

**Comment by ppggff** [comment]
> If it is about fine grained control of disabling individual features of an extension, then I would like to close this out of scope. Otherwise, please reopen it and explain the requirement in detail. Thanks.

hi, not disable them, just hide their UI: buttons/menus/shortcuts and so on.

**Comment by ppggff** [comment]
@sandy081 how to reopen it?

**Comment by sandy081** [comment]
Hiding shortcuts -> I do not think it is possible.

Regarding hiding buttons/menu - Reopening it and passing it on to @jrieken

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Amenus

**Comment by ppggff** [comment]
thanks
I give up on this issue, hope some one will found the same problem bothering them and submit a new one.
