### ISSUE TITLE
Feature Request: Add IntelliCode like autocompletion in vscode

### ISSUE THREAD

**Issue by kirtangajjar** [microsoft/vscode#49437]
Visual Studio has just launched [IntelliCode](https://www.visualstudio.com/services/intellicode/).
It would be great to have same kind of functionality in vscode.

**Comment by sterling000** [comment]
This would be absolutely huge, as a long time Visual Studio + ReSharper user, the ONLY thing holding me back from moving to VS Code is the lack of an exhaustive intellisense extension. JetBrains said in a recent forum post that they have no plans to port ReSharper to VS Code and instead are building a competing IDE with Rider. The community is already turning on them saying that Rider is exactly what they are trying to move away from and moving to VS Code. 

There is a massive opportunity here for the IntelliCode & VS Code people to fill a gap and complete the migration for all the VS people who want a lighter cross platform IDE.

**Comment by myfairsyer** [comment]
There are extensions both [for Visual Studio](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.VSIntelliCode) and [for VSCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode).

Currently the former only supports C# and the latter Python.

However in the [announcement blog post on MSDN](https://blogs.msdn.microsoft.com/visualstudio/2018/05/07/introducing-visual-studio-intellicode/) and the comments @AmandaSilver and @markw-t wote things like

> [W]e want to expand to other languages later

> We’re looking at support for other languages as we make progress on the IntelliCode features, although we can’t make any commitments at this point.

> [W]e definitely see the potential for IntelliCode’s capabilities across many languages

> [W]e’ll take feedback from users on which languages we should look to support next as we expand the experiment

**Comment by markw-t** [comment]
By the way the [IntelliCode exension for Visual Studio Code](https://aka.ms/vsic/xtn/vscode) now supports TypeScript, JavaScript, Java and Python - hope you find it useful.

**Comment by DanTup** [comment]
@markw-t how does this extend to other languages? Is the IntelliCode extension intending to cover more languages, or is it up to other languages to implement themselves in their own language extensions?

**Comment by markw-t** [comment]
Hey @DanTup 

Thanks for the question. Each language has its own "base model" which our data scientists have to train on a large corpus of repos to get typical usages of each type for a given coding context. Then work is done in the relevant IntelliCode client (VS or VS Code) to plumb that model into the completion system. 

We don't yet have a public extensibility model that would allow languages to add their own coverage, although that's something we can consider - feel free to raise it as a suggestion on our [issues list](https://aka.ms/vsicissues) for others to weigh in and vote on.  There are clear challenges in making the process of model training scale to extenders too, so this is not a trivial problem to solve. 

We are taking customer feedback on demand for support for other languages - you'll see several suggestions on the issues page we are tracking for other languages there.  However the team's energies are also focused on broadening IntelliCode's capabilities, for example the new [refactorings detection](https://aka.ms/vsic/blog/refactorings), so there are trade-offs in what gets done first.
  
Hope that helps clarify the situation - do drop me a line at mwthomas at microsoft dot com if you want to discuss further or have any feedback (good or bad) about IntelliCode.

Cheers
Mark

**Comment by DanTup** [comment]
@markw-t Thanks - I wasn't specifically *asking* for extensibility support, mostly just interested whether it was already on the cards (and if so what form it would take). I work on the Dart/Flutter extensions, though I suspect other language extension authors probably have the same interest - is there value here that we can provide to our users (it's not clear whether MS are building some specific functionality for some specific languages, or a framework for any language to provide this functionality to their users).

I can open an issue about this, though it might not be much different to https://github.com/MicrosoftDocs/intellicode/issues/2. It's more of a question about what the plans are than a request for something.

**Comment by markw-t** [comment]
Thanks for the clarification @DanTup . Extensibility is not on the immediate backlog and does have a fair bit of work associated as I mentioned, so for now we are closer to your description of making specific functionality for some specific languages. 

No harm in opening a language-specific issue for Dart/Flutter to gauge interest in the feature.

**Comment by DanTup** [comment]
>  for now we are closer to your description of making specific functionality for some specific languages.

Got it, thanks for the clarification! I opened https://github.com/MicrosoftDocs/intellicode/issues/133 about Dart support for people to put 👍 's on.
