### ISSUE TITLE
Live Share - Sign In Timeout Issue

### ISSUE THREAD

**Issue by prasadgl** [Microsoft/vscode#49431]
Issue Type: <b>Bug</b>

1. Install Visual Studio Live Share. 
2. Reload after the extension is installed
3. Wait for the dependencies install to be complete
4. Restart Visual Studio Code
5.  See the Signing In message
6.  Getting the Time out error Message.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.88GB (7.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
markdown-preview-github-styles|bie|0.1.2
azuretoolsforvscode|bra|2.0.2
simple-react-snippets|bur|1.1.1
cake-vscode|cak|0.10.1
npm-intellisense|chr|1.3.0
vscode-css-modules|cli|0.2.2
vscode-markdownlint|Dav|0.15.0
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
xml|Dot|1.9.2
gitlens|eam|8.2.4
EditorConfig|Edi|0.12.1
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
vscode-reveal|evi|2.0.3
auto-close-tag|for|0.5.6
webpack-snippets|gog|0.0.4
beautify|Hoo|1.3.0
rest-client|hum|0.18.4
webpack|jer|2.0.2
vscode-azureappservice|ms-|0.8.0
vscode-azurefunctions|ms-|0.8.1
vscode-azurestorage|ms-|0.3.0
python|ms-|2018.4.0
azure-account|ms-|0.4.0
csharp|ms-|1.14.0
node-debug2|ms-|1.19.0
notepadplusplus-keybindings|ms-|1.0.2
PowerShell|ms-|1.7.0
vsliveshare|ms-|0.3.93
team|ms-|1.133.0
azurerm-vscode-tools|msa|0.4.0
vscode-jest|Ort|2.7.0
vscode-docker|Pet|0.0.26
material-icon-theme|PKi|3.4.0
code-settings-sync|Sha|2.9.2
trailing-spaces|sha|0.2.11
vscode-react-native|vsm|0.6.9
gitblame|wad|2.4.2
webpack-progress|wk-|0.0.8

(3 theme extensions excluded)

</details>

![ls timeout](https://user-images.githubusercontent.com/1765856/39739048-79eefb76-52ac-11e8-851d-34b7cb2206e8.PNG)
![ls sign in](https://user-images.githubusercontent.com/1765856/39739049-7a233a3a-52ac-11e8-9afd-a6577e38e1e7.PNG)

**Comment by egamma** [comment]
Moving to the Live Share extension.
