### ISSUE TITLE
Improve dark colour themes like Monokai for colouration of tabs

### ISSUE THREAD

**Issue by uglycoyote** [Microsoft/vscode#49432]
When using the Monokai theme or many of the other dark themes, e.g. "Dark(Visual Studio)",  it is extremely confusing that all of the tabs are highlighted except for the active one.  This is especially problematic when only two files are opened.  In such circumstances, I find myself constantly clicking on the darker tab in order to switch the other file, but of course this does nothing because the dark tab is the current one.

What makes this all the more confusing is that the unselected tab colour is almost identical to the selected text highlight background colour.

**Sane:**

Sublime Text with Monokai and Flatland Dark theme, index.html is the selected file and is highlighted brighter.  Furthermore, the selected tab has a curved base which subtly overlaps the non-active tab and ties in with the horizontal bar of the same colour, further visually reinforcing which tab is currently active.

<img width="456" alt="screen shot 2018-05-07 at 10 07 30 pm" src="https://user-images.githubusercontent.com/2461007/39738944-138121e8-5243-11e8-912e-1e223bf21f20.png">

**Not Sane:**

VS Code with Monokai theme, with index.html on the left as the active tab.  It is "highlighted" by being darker than the other tabs.  The tabs are completely square and so other than the colour there is no visual cue as to which tab is active.  Note similarity between highlighted text and the colour of the inactive tab.

<img width="576" alt="screen shot 2018-05-07 at 10 04 07 pm" src="https://user-images.githubusercontent.com/2461007/39738923-f9fd9b0c-5242-11e8-8a99-825d56c1c62b.png">

**Comment by bpasero** [comment]
PR welcome if small.

**Comment by uglycoyote** [comment]
the following in my user settings improves the situation

```
"workbench.colorTheme": "Monokai",
"workbench.colorCustomizations": {
    "[Monokai]": {
		"tab.inactiveBackground": "#2c2e27",
		"tab.inactiveForeground": "#ccccc7", // needs to be bright so it's readable when another editor group is focused
		"tab.activeBackground": "#494842",
                "tab.activeForeground": "#d3d1cc", 
    }
},
```

The file defining the colours is [here](https://github.com/Microsoft/vscode/blob/master/extensions/theme-monokai/themes/monokai-color-theme.json).  It does not define "inactive" tab colours, only active colours.  So it's possible at the time when the theme was authored the default inactive colour was darker and that some point later the default was changed, creating the problem.

I'm not sure if I want to try to make a PR myself,  because I'm not really set up for building and testing VSCode from sources and also as I mentioned the problem is present in more than one theme (a broader fix may be needed than just to Monokai).   I could fork VSCode and edit the one Monkai config file using the web interface and just submit PR without testing and hope for the best, but I imagine that sort of behaviour is frowned upon.

**Comment by Tyriar** [comment]
It's "highlighted" as being the same color as the editor, it looks better when there are multiple editors:

![image](https://user-images.githubusercontent.com/2193314/39935481-fc3bdaec-54fd-11e8-93cb-8085df50b12c.png)

Inverting it as you suggest looks wrong imo:

![image](https://user-images.githubusercontent.com/2193314/39935500-0cc86272-54fe-11e8-9da7-8443b9aaa603.png)

+ @roblourens @misolori

**Comment by Fraasi** [comment]
This was very confusing choice of colors for me also. I really like this monokai-theme, so I solved it like this:   (commented colors are the originals)
```
"tab.inactiveBackground": "#272822", // "#414339"
"tab.activeBackground": "#414339",    // "#272822"
"tab.activeBorder": "#f5db19",
```
![2018-05-11_2313](https://user-images.githubusercontent.com/22402899/39945156-18d28cd6-5572-11e8-9696-462d59023608.png)

This has worked for me, and I didn't have to change the color scheme.

**Comment by Kroc** [comment]
It's currently not possible to have a bottom-border on the inactive tabs, but *no* bottom border on the active tab.

Other possibilities include a top-border colour for the active tab, that way it can connect to the page on the bottom, and have a bright colour indicator, e.g. Notepad++ (to some extent)

**Comment by roblourens** [comment]
I agree with @Tyriar, the inactive tabs looked grayed out and sort of "behind" the active tab/editor.

**Comment by uglycoyote** [comment]
@Fraasi, yes the yellow underline definitely helps to underscore the active tab, I like that.

@Tyriar I disagree that having the tab the same colour as the editor is a good visual indicator that it is the current tab, especially when the inactive tabs are brighter and there is a solid separating line between the editor and the tabs.  Though I could start to agree with you if your first screenshot was changed to something like this (photoshopped hack)

![image](https://user-images.githubusercontent.com/2461007/39948487-0f51b070-552b-11e8-8895-ac4893ae169d.png)

**Comment by Tyriar** [comment]
@uglycoyote the shadow means that there's content to scroll above the top so it seems a little think it still makes sense to keep the shadow. You can see it without the shadow if you scroll to the top:

![image](https://user-images.githubusercontent.com/2193314/39949536-2319d966-5530-11e8-9ebb-4931640b848e.png)

**Comment by Kroc** [comment]
NB: you can remove the shadow that appears when scrolled by adding this to your settings:

```json
workbench.colorCustomizations": {
    "scrollbar.shadow": "#0000"
}
```

**Comment by misolori** [comment]
We could try reducing the opacity of the inactive tabs (text + icons) so it's more obvious which tab is active:
![image](https://user-images.githubusercontent.com/35271042/40016270-acea4ea0-576a-11e8-94f4-f6260e359fc9.png)

**Comment by uglycoyote** [comment]
@misolori, There's a comment on this line in the current Monokai theme json:

```	"tab.inactiveForeground": "#ccccc7", // needs to be bright so it's readable when another editor group is focused```

I'm imagining that it was originally darker, and someone added the comment when making it brighter to try to solve the readability problem.  I tend to agree with this person, that highlighting the inactive tabs to a brighter grey while simultaneously dimming the text makes for poor contrast, not to mention that it is a mixed message.

In the Explorer window and other left-docked windows,  a lighter shade of grey is used consistently to highlight the current item.  Having some consistency about what colour represents "selected"  seems more important than having colour-coordinating the selected tab with the editor background.

Looking at some other software, it seems other programs solve these issues by having some kind of a "header bar", and having the colour of the header bar and the selected tab be the same.  

Chrome (incognito)
<img width="848" alt="screen shot 2018-05-14 at 12 08 28 pm" src="https://user-images.githubusercontent.com/2461007/40017948-bedac7a2-576f-11e8-98ab-0edceb388f6e.png">

Sublime Monokai & Flatland Dark
<img width="502" alt="screen shot 2018-05-14 at 12 12 48 pm" src="https://user-images.githubusercontent.com/2461007/40018116-34e2d0ca-5770-11e8-8ad7-8c654cf081b9.png">

Thus they have the "selected tab colour matches something below it" property that you desire without forcing the selected tab to be darker than the unselected ones, even though the editor (or main content window in the case of Chrome) is dark.

**Comment by misolori** [comment]
For the Monokai theme, the inactive tabs do appear too bright. I'd suggest reducing the background color from `#414339 ` to `#34352f`.

**Before**
![image](https://user-images.githubusercontent.com/35271042/40023199-2164a6fe-577f-11e8-8272-b012e9ec4515.png)

**After**
![image](https://user-images.githubusercontent.com/35271042/40023250-49297368-577f-11e8-95f6-b6774602b8b1.png)

This pattern where the inactive tabs are grayed out works well with the rest of our dark themes:

**One Dark Pro**
![image](https://user-images.githubusercontent.com/35271042/40023958-981e384e-5781-11e8-845c-0c3f40b48274.png)

**Flatland Monokai**
![image](https://user-images.githubusercontent.com/35271042/40024324-c84688c2-5782-11e8-97bb-701bd00e2631.png)


**Absent (Rainglow)**
![image](https://user-images.githubusercontent.com/35271042/40023928-74f4310c-5781-11e8-9fb3-98a9602ad605.png)

**Comment by Tyriar** [comment]
@misolori I agree that does look better, I think we should probably concern other places like the status bar to use that color as well. Then `#414339` can still be used primarily for selection?

**Comment by roblourens** [comment]
I like that darker color for inactive tabs, but I would keep the same color other places like the status bar. I like the status bar brighter to contrast with the editor background. It's used for `list.inactiveSelectionBackground`, but that should also stay brighter so it stands out in the list.

**Comment by roblourens** [comment]
Also, the breadcrumbs bar under the tabs kind of helps with the general tab discussion above...

![image](https://user-images.githubusercontent.com/323878/45455281-6bd35c00-b69b-11e8-8dc3-d5738b41a9a0.png)

**Comment by roblourens** [comment]
We can try this out in Insiders, let me know if you have any feedback...

**Comment by howar31** [comment]
I think it'll be much better if the background color of the inactive tabs is the same as the tab gutter:

![image](https://user-images.githubusercontent.com/880459/46397426-cbfe7080-c724-11e8-837a-2a1d0bd2ec86.png)

```json
	"workbench.colorCustomizations": {
		"tab.inactiveBackground": "#1E1F1C",
		"tab.inactiveForeground": "#AAAAAA",
		"tab.activeForeground": "#FFFFFF",
	}
```
