### ISSUE TITLE
What's the dark theme used in Visual Studio Live Share blog post?

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/vscode#49434]
Which dark theme is getting used in the following blog post?

https://code.visualstudio.com/blogs/2018/05/07/live-share-public-preview

**Comment by egamma** [comment]
@lostintangent might now 😄

**Comment by lostintangent** [comment]
@xeonuex It’s [Andromeda Italic](https://marketplace.visualstudio.com/items?itemName=EliverLara.andromeda) :)

**Comment by xeoneux** [comment]
@lostintangent thanks! 😸
