### ISSUE TITLE
New feature Organize Import has mis-deleting import statements

### ISSUE THREAD

**Issue by rockmandash** [Microsoft/vscode#49436]
The original code
![image](https://user-images.githubusercontent.com/7580792/39741385-532fdf76-52cc-11e8-826a-abbbdb77bc49.png)

Please notice the first line.
Organize import has delete all the import statements, so all the code is mess up
![image](https://user-images.githubusercontent.com/7580792/39741341-226054a2-52cc-11e8-93be-6930ba3122a1.png)

**Comment by Elijen** [comment]
@rockmandash This specific case is fixed in Insiders release.

**Comment by rockmandash** [comment]
Thank you
