### ISSUE TITLE
Unable  to uninstall and find path to map to Shell

### ISSUE THREAD

**Issue by bensonkb** [Microsoft/vscode#49433]
Issue Type: <b>Bug</b>

OS: Ubuntu 18.04
Code : 1.22
Not able to Open code in command Prompt and Installing new Code is not replacing the exsiting application, Dual Application occurs. 

apt purge code - Cant find the code application. 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1466)|
|Load (avg)|2, 1, 1|
|Memory (System)|7.71GB (1.38GB free)|
|Process Argv|/app/extra/vscode/code --extensions-dir=/home/djaxtech/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bensonkb** [comment]
**Here is the cache found in the dir. Even after remove the com.visualstudio.code folder. Code Apllication Exist and com.visualstudio.code is recreated.**
`root@Lenovo-G50-80:/home/tech/.var/app/com.visualstudio.code# cd 
cache/  config/ data/   .ld.so/ `

**Comment by Tyriar** [comment]
How did you install?

**Comment by bensonkb** [comment]
Installed the package through dpkg installation.

**Comment by Tyriar** [comment]
`/home/tech/.var/app/com.visualstudio.code` doesn't look familiar to me, I suspect you installed from some unofficial source and it's not fully removed.

The deb package will install to `/usr/share/code`, data directories used are `~/.vscode` (for extensions) and `~/Code` (for user data).
