### ISSUE TITLE
intellisense does not work when using `module.exports.fnName`

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#4943]
- VSCode Version: 0.10.14 (insiders) and below
- OS Version: Mac OS X 10.11.3

Steps to Reproduce:

1. Create a file called `cfx.js` with the following content

```js
'use strict';
module.exports.generateCanvas = function (fileOrUrl) {
	console.log(fileOrUrl);
};
```

2. Create a file `index.js`

```js
'use strict';
var cfx = require('./file1');
```

3. When you type `cfx.` in `index.js`, it will not suggest `generateCanvas`. If you change `cfx.js` to `exports.generateCanvas` instead of `module.exports.generateCanvas`, it works.

This seems to be a bug because both notations are equivalent.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7824

**Comment by SamVerschueren** [comment]
Thanks @egamma

**Comment by danielo515** [comment]
Does that mean that is not a problem in VSCode but on typescript itself?

**Comment by SamVerschueren** [comment]
I believe it's the TypeScript language server that deals with this so I think it is.
