### ISSUE TITLE
Activity bar: the order of the views containers is not preserved properly

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#49443]
If I move my custom views container to the top then search and explorer swap places:

![vscode](https://user-images.githubusercontent.com/1812093/39747406-82575c94-52ad-11e8-93d3-990a11a8558b.gif)

**Comment by isidorn** [comment]
Fixed in latest I believe.
Closing. @sandy081 reopen if I am wrong

**Comment by sandy081** [comment]
Fixed in https://github.com/Microsoft/vscode/issues/48580
