### ISSUE TITLE
fs.readFileSync, fs.readFile will make the debugger stop with heap out of memory.

### ISSUE THREAD

**Issue by akq** [Microsoft/vscode#49447]
- VSCode Version:1.23.0
- OS Version: OSX, windows 

Steps to Reproduce:

1. for the code below: 
read a file larger than 20M.
```javascript
var fs = require('fs');
var data;
try{
    //get same result when using readFile
    data = fs.readFileSync('/your/file/which/is/larger/than/20M');
}catch(err){
    console.log(err);
}
console.log('ok,', data)
```
2. add the breakpoint at the last line. 
3. F5 to debug the file

The code of mac os version will respond error `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` after about 10 minutes (as the screenshot below). windows version will not respond after over one hour.

osx 
![image](https://user-images.githubusercontent.com/1907927/39748742-6eed5394-52e3-11e8-8acf-8082354adf9a.png)

windows 
![image](https://user-images.githubusercontent.com/1907927/39797403-8b7e6e16-538e-11e8-9ad5-fd6e6a5b88ce.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by roblourens** [comment]
Works fine for me. Tried with newer and older versions of node. Do you ever hit the breakpoint? Is there anything else you do?

**Comment by akq** [comment]
No, the debugger won't hit the breakpoint and exit with heap out of memory.
if no breakpoint, it can run normally.
I have tried node v10, it definitely can hit the breakpoint. but our production is v6.
Is it a bug only with v6?

**Comment by roblourens** [comment]
So if you run normally from a terminal without debugging, does the script run successfully? Or does it still crash?

**Comment by akq** [comment]
it can successfully run without debugging.

**Comment by roblourens** [comment]
Ok, what if you run with `node --inspect` in the terminal (but don't use a debugger)? Just to narrow down the cause...

Also, if you don't set the bp, but use the debugger, does it work?

**Comment by akq** [comment]
yes, I can run the code with the inspect option and adding a breakpoint.
see the attachment. So I think it's should be a bug of vs code debugging system.

![image](https://user-images.githubusercontent.com/1907927/39911395-cd03f2b6-552d-11e8-81f9-e1759a2be17c.png)


![image](https://user-images.githubusercontent.com/1907927/39911182-1c086f3c-552d-11e8-8a7b-15f1b156f053.png)

**Comment by roblourens** [comment]
Is that 32-bit windows 7? Guess it only happens there and not in Windows 10, I still can't repro any problem.

Can you try in VS Code again but with the sidebar closed (so the variables wouldn't show up and won't be requested from the debugger)

**Comment by akq** [comment]
no, 64-bit windows 7, but I can reproduce it on 64-bit windows 10 with node v5 , v6 and v7, with sidebar open and closed

it can't hit the breakpoint on windows 10, with node v5,  v6, v7
![image](https://user-images.githubusercontent.com/1907927/39963399-b9f919e2-569c-11e8-8f2b-fb5ae2632e6c.png)

![image](https://user-images.githubusercontent.com/1907927/39963415-2899e48a-569d-11e8-8106-caefc44efaf5.png)

![image](https://user-images.githubusercontent.com/1907927/39963471-3a34f21a-569e-11e8-89ad-ecb73cfbcb87.png)

![image](https://user-images.githubusercontent.com/1907927/39963483-86e3584a-569e-11e8-9ce0-fc140fa4d732.png)

But it can hit BP with node v0.12

![image](https://user-images.githubusercontent.com/1907927/39963847-67e90146-56a9-11e8-9500-7f0161d17e99.png)

**Comment by roblourens** [comment]
Actually it looks like you are using the older debug protocol (with --debug) with the older versions of node.

Since you said

> I have tried node v10, it definitely can hit the breakpoint.

I'm guessing it's just a problem with that. If you set `"protocol": "inspector"`, does it still happen?

**Comment by akq** [comment]
Yes, it works now. I also found the [document](https://code.visualstudio.com/docs/nodejs/nodejs-debugging) to describe the issue. 

> It can be more stable when debugging very large JavaScript objects. The legacy protocol can become painfully slow when sending large values between the client and server.
