### ISSUE TITLE
can not clear buffer in Integrated terminal

### ISSUE THREAD

**Issue by jim-binea** [Microsoft/vscode#49444]
Issue Type: <b>Bug</b>

when i try to clear buffer in Integrated terminal. it is not work, and show "^L".

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 12, 6|
|Memory (System)|8.00GB (2.40GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.15
react-native-snippet|jun|0.4.3
graphql-for-vscode|kum|1.11.0
color-highlight|nau|2.3.0
vscode-code-outline|pat|0.1.1
convert-css-in-js|pau|1.0.0
java|red|0.24.0
markdown-preview-enhanced|shd|0.3.5
autoimport|ste|1.5.3
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.7.0

</details>

**Comment by yume-chan** [comment]
Duplicate of #49162

It will be resolved in 1.23.1 by reverting the terminal clear logic.

**Comment by jim-binea** [comment]
thanks
