### ISSUE TITLE
Roll back problematic auto updates

### ISSUE THREAD

**Issue by southwood** [Microsoft/vscode#49442]
I would like a way to quickly revert to a version of VSCode that works when updates to VSCode break my workspace in some way. I have regretted taking updates to VSCode because of this on multiple occasions so I am requesting this feature.

**Comment by joaomoreno** [comment]
You can set `update.channel = none` and manually update VS Code from then on.

**Comment by southwood** [comment]
I want a button “revert to previous version” next to “check for updates” or something. That’s what this feature request is for.

I really want to like VSCode but each time I try it again I end up sinking more time into setup than it’s worth and then something like this happens and I give up on using it. 

TBH my favorite new feature since the last time I tried it is the command to “reload window” without restarting it (because it gets into defunct states so often while running).
