### ISSUE TITLE
When clause: can't use OR (||) operator

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#49449]
I tried to use the OR (||) operator in a `when` condition, like this:

<img width="661" alt="screen shot 2018-05-08 at 12 37 39" src="https://user-images.githubusercontent.com/1812093/39752952-62f3d746-52bd-11e8-926b-70e1394d932f.png">

But it didn't work, because of this I had to [horribly duplicate](https://github.com/fabiospampinato/vscode-projects-plus/blob/f1b3225d67f5625fa1a51d62636258a4c886d7ab/package.json#L358-L399
) all my contributed right-click commands.

**Comment by isidorn** [comment]
Closing as duplicate.
@alexandrudima please reopen if you do not already have a feature request for this, though I know it is previously requested

**Comment by fabiospampinato** [comment]
It is document anywhere what kind of syntax the "when" clause supports? I thought the string was first parsed, basically transforming `view == projects.views.explorer.all` to `view == 'projects.views.explorer.all'` and then `eval`-ed, but this doesn't seem to be the case.

**Comment by alexandrudima** [comment]
The duplicate is #33547

We haven't documented the language properly anywhere. The parser is incredibly simplistic.

https://github.com/Microsoft/vscode/blob/4557aadf4cef34e0222eb035d10c4195b29c09d0/src/vs/platform/contextkey/common/contextkey.ts#L46:L79
