### ISSUE TITLE
Automatically rename paired HTML/XML tag

### ISSUE THREAD

**Issue by aleks-angelov** [Microsoft/vscode#49446]
A small but useful quality-of-life feature - when you rename one HTML/XML tag, automatically rename the paired HTML/XML tag. This functionality already exists in Visual Studio.

There is currently an extension for this, but it is buggy: https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag

**Comment by aeschli** [comment]
duplicate of #47069
