### ISSUE TITLE
Add changelog on ubuntu/debian repository

### ISSUE THREAD

**Issue by danielcosta** [Microsoft/vscode#49450]
It would be nice to have the changelog of updated versions on Software Updater from Ubuntu. Nowadays the "changes" tab only show current and available version with the following notice: "This update does not come from a source that supports changelogs."

![Software Updater](https://i.imgur.com/jVvQvmI.png)

- VSCode Version: 1.22+ (probably affects all versions)
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Setup VSCode as described here: https://code.visualstudio.com/docs/setup/linux
2. Get **Software Updater** notification for VSCode's new version

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
The changelog pops up after installation on all platforms, plus it's available online. I don't think it's worth the effort to support pulling these in and converting from markdown just for .deb users. (especially when snap is a WIP).
