### ISSUE TITLE
Cmder as the terminal doesn't open in CWD

### ISSUE THREAD

**Issue by affanshahid** [Microsoft/vscode#49455]
Using information from https://github.com/Microsoft/vscode/issues/12006, I managed to inject Cmder into my terminal inside code but it opens in my user directory instead of the current folder. How do I go about fixing this?

Relevant settings:
```json
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": ["/K", "D:\\Program Files\\cmder\\vendor\\init.bat"]
```

**Comment by alexmaday** [comment]
If you check out the question: "Can I use Cmder's shell with the terminal on Windows?" within the vscode docs at https://code.visualstudio.com/docs/editor/integrated-terminal, they make mention of a `vscode.bat` file you need to point to, *instead of* the `vendor\init.bat`

**Comment by affanshahid** [comment]
Woops, missed that! Thank you.
