### ISSUE TITLE
add " () "to selected method default 

### ISSUE THREAD

**Issue by abvaalgit** [Microsoft/vscode#49458]
when i type "." front of an object  VS suggest me methods and fields name for selecting ...
it is good but just bad approach ...when i select a method name ,it must default put double parentheses front of the method name. name without paired parentheses is so boring for developer..please add this enhancement to vs..
thanks lover of vc

**Comment by jrieken** [comment]
@abvaalgit Sorry my crystal ball and the magic mirror broke so you need to provide some more information. How about starting with the programming language in which you want this to happen.

**Comment by masterrjj24** [comment]
Try to set this on your User Settings:

"typescript.useCodeSnippetsOnMethodSuggest": true,

**Comment by abvaalgit** [comment]
@masterrjj24 i don't need your answer ....this feature must be default without setting

**Comment by abvaalgit** [comment]
- @jrieken info is complete ..."read more"  is needed not info

**Comment by abvaalgit** [comment]
@jrieken  when choosing  a method that is suggesting vs ...vs must add a () to end of method name ....do you understand

**Comment by abvaalgit** [comment]
@jrieken change this feature  to "typescript.useCodeSnippetsOnMethodSuggest": true;

**Comment by jrieken** [comment]
> vs must add a () to end of method name ....do you understand

Unless you use a function as argument. Albeit being useful, inserting the call-part isn't always correct and that's why it is a setting. Marking as question.
