### ISSUE TITLE
[html] comments close despite `html.autoClosingTags` being disabled

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#49459]
Issue Type: <b>Bug</b>

I've got html.autoClosingTags set to false, yet when I type `<!--` the editor auto completes -->

VS Code version: Code - Insiders 1.24.0-insider (8a07c8d935998d1b1153dde0c5b337189d35cea0, 2018-05-08T05:16:07.736Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (5.11GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
copy-relative-path|ale|0.0.2
spellright|ban|2.3.4
markdown-preview-github-styles|bie|0.1.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.48
prettier-vscode|esb|1.3.1
apiconnecttools|IBM|0.0.5
coldfusion|ili|1.0.1
wordcounter|kir|1.2.2
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.8.0
azure-account|ms-|0.4.0
vetur|oct|0.11.7
polacode|pnp|0.2.2
htmlescape-vscode-extension|ray|0.0.4
vue-vscode-extensionpack|sdr|0.1.2
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|2.9.2
vscode-status-bar-format-toggle|tom|1.3.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.6.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Oh, that's the auto pair support.

**Comment by aeschli** [comment]
There's no setting for auto pairs  ;-(

Is it that of a pain?

**Comment by cfjedimaster** [comment]
Yes. :) I find myself wrapping content a lot with comments to disable it and this requires me to delete the end pair and retype it. I strongly believe that *every* auto behavior in an IDE should be configurable. (Code also doesn't let you completely disable auto tabbing either.)

**Comment by Proxy404** [comment]
I'd like to second this request. While editing my html files I comment out large sections and have to delete the auto close as well.

**Comment by KamasamaK** [comment]
That use case of commenting sections of code would be more simply accomplished by highlighting the content and using one of the comment commands to wrap it. The default shortcuts for toggling comments are below and can be configured. Also, for a language like HTML that only has block comments, both commands will work.
Line: `Ctrl`+`/`
Block: `Shift`+`Alt`+`A`

**Comment by cfjedimaster** [comment]
"more simply accomplished" assumes you know the key combo. I'm horrible at remembering them. That's why I'd want a setting to simply disable it.

**Comment by itsknob** [comment]
`Ctrl K`+`Ctrl S` brings up a searchable list of all of the shortcuts. It's the only one I remember.

**Comment by cfjedimaster** [comment]
Cool. Still want this fixed though. ;)

**Comment by KamasamaK** [comment]
I hadn't really realized before that they chose that combination for `K`eyboard `S`hortcut.

One that is an absolute must is `Ctrl`+`Shift`+`P` for the Command Palette. It has every command searchable by description and displays the keyboard shortcut on the right side.

**Comment by aeschli** [comment]
The request to make autoClosingPairs configurable is #38352. Marking as dup of that.
