### ISSUE TITLE
When  i select something in the editor, it will automatically paste the selected content.

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#49461]
Issue Type: <b>Bug</b>

When selecting something in the editor, there will be automatically paste the selected content, when you right-click the editor, and then left-click will appear automatically paste the selected content. When I select something in the editor , automatically paste selected content when switching vscode from another application.
My expansion has been closed, and this situation will still appear

VS Code version: Code - Insiders 1.24.0-insider (8a07c8d935998d1b1153dde0c5b337189d35cea0, 2018-05-08T05:16:07.736Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.15GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-database|baj|1.5.1
vscode-wxml|cod|0.1.9
dart-code|Dar|2.12.1
flutter|Dar|2.12.2
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.4
tslint|eg2|1.0.28
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
code-runner|for|0.9.3
vscode-cosmosdb|ms-|0.7.0
vscode-language-pack-zh-hans|MS-|1.23.4
windowsiot|ms-|0.0.20
sqlops-debug|ms-|1.0.2
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.4.0
azure-account|ms-|0.4.0
cpptools|ms-|0.17.0
csharp|ms-|1.14.0
github-issues-prs|ms-|0.9.0
Go|ms-|0.6.79
js-atom-grammar|ms-|0.1.14
jscs|ms-|0.1.9
mono-debug|ms-|0.15.8
PowerShell|ms-|1.7.0
typescript-javascript-grammar|ms-|0.0.41
quantum-devkit-vscode|qua|0.2.18022202
java|red|0.24.0
vscode-yaml|red|0.0.11
rust|rus|0.4.2
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.7.0
debug|web|0.22.0

(1 theme extensions excluded)

</details>
。

**Comment by isidorn** [comment]
Please try reproducing this with all extensions disabled

**Comment by czfadmin** [comment]
I have disabled all the extensions and this will still appear.

**Comment by czfadmin** [comment]
I don't know if this is a bug or not. When I select something in the editor area, I haven't done anything else. I don't want to copy it. VSCode will automatically copy the selected content.

**Comment by rebornix** [comment]
@czfadmin do you still run into this issue with latest version?

**Comment by czfadmin** [comment]
@rebornix I have not encountered this situation in the latest version. 👍

**Comment by rebornix** [comment]
@czfadmin thanks! Close this one for now but if you run into it again, let's reopen it.
