### ISSUE TITLE
Upgrade to v1.23 fails repeatedly

### ISSUE THREAD

**Issue by compwiz32** [Microsoft/vscode#49466]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1984235/vscode-inno-updater.log)
Issue Type: <b>Bug</b>

perform auto update after program was launched.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|Memory (System)|15.70GB (7.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.7.0
vscode-icons|rob|7.23.0

(6 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Does this still happen after restarting your machine?
