### ISSUE TITLE
Option to not style rendered whitespace with TextEditorDecorationType

### ISSUE THREAD

**Issue by 0xCLARITY** [microsoft/vscode#49462]
Issue Type: <b>Feature Request</b>

When whitespace is rendered, and a style is applied to the text of the current line, I would like to not have that font style applied to the rendered whitespace (tabs and spaces) in that line.

## Use Case:
Some extensions add text styles for certain types of comments. The two I know of are "Better Comments" and "TODO Highlight".

When you apply a style to an entire comment line, say to style a `# WARNING: ...` line as bright red, the rendered whitespace also turns bright red, which adds noise to the comment.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.4.0

**Comment by hbergren** [comment]
I realized my description could have been better, so here is a clarifying picture. The red comment is generated with the "TODO Highlight" extension:

![aggressive_whitespace](https://user-images.githubusercontent.com/11398766/39779088-24fe1e7e-52d6-11e8-836a-8d748e7c310e.png)

**Comment by alexandrudima** [comment]
I don't think this is something we can support in the rendering code, simply because decorations come in very many flavours.

For example, a decoration that adds underlines or changes the background color should not break at whitespace boundaries. I guess the same is true for the border...

**Comment by hbergren** [comment]
Ah, I'm starting to see the complexity.

Would it be possible to add an option to either:
- Opt out of applying the decoration font color to rendered whitespace, OR
- Expose a separate `DecorationRenderOption` of `whitespaceColor?`

I think that would solve the 80% use case. Of course, I'm not sure if it's possible to distinguish between true text and rendered whitespace like that.

**Comment by fabiospampinato** [comment]
I've just got an issue regarding this matter https://github.com/fabiospampinato/vscode-todo-plus/issues/67.

For my particular use case fixing https://github.com/Microsoft/vscode/issues/50346 would also allow me to fix this one. But I would much prefer to have an option for opting out of decorating whitespaces rather than coding the logic myself.

**Comment by LepkoQQ** [comment]
I've been trying to fix this in my extension as well and if we could opt out of whitespace styling it would be great.

**Comment by joyceerhl** [comment]
This seems verified to me based on the following steps:

1. Installed Todo highlight extension
2. Added this config 
  ``` json
  "todohighlight.keywords": [
    {
      "text": "foo bar baz",
      "color": "#ff0000",
      "border": "1px solid red",
      "borderRadius": "2px",
      "backgroundColor": "rgba(0,0,0,.2)"
    }
  ]
  ```

VS Code stable:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/30305945/214709814-dc7d8194-e7c0-4e77-878d-96e820169ec6.png">
VS Code insiders:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/30305945/214710161-d56a471c-907a-4db8-82c6-dd5ab46a0573.png">
