### ISSUE TITLE
How to extend javascript code completion and other features

### ISSUE THREAD

**Issue by minggo** [Microsoft/vscode#4946]
Now i create `cocos.d.ts` for my javascript library code completion. It works perfectly. But i have some special requirements. In my library, the inheritances looks like:

```javascript
cc.Class({
    extends: cc.Component,  // the base class is cc.Component
    myfunc: function() {
        var s = this.myFunc();   // myFunc is a property of cc.Component, want completion for properties of cc.Component, want type checking and all other features that are available
         s.   // want code completion, type checking and all other features that are available
        ...
    },
    ...
});
```

As the codes shows, the inheritance is runtime related. How can i extend javascript code completion to let VSCode know `this` is an instance of `cc.Component`'s subclass?

**Comment by minggo** [comment]
@isidorn @weinand Any idea? Thanks.

**Comment by minggo** [comment]
@dbaeumer Any idea?

**Comment by dbaeumer** [comment]
@minggo to my knowledge you can't right now. But moving to TS. May be they have an idea.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7929

**Comment by minggo** [comment]
@dbaeumer If i can extend TS, then how to make it take effect in VSCode?

**Comment by dbaeumer** [comment]
You need to extend the code completion request and do you own computation by either providing an extension and parsing the JS code yourself and computing completion items (you might want to look at the vscode documentation for how to write an extension here: https://code.visualstudio.com/Docs ) or by providing a different tsserver.

**Comment by minggo** [comment]
I know VSCode extension, but it seems too complicated for me to do as good as VSCode internally. As i know, VSCode internally also depend to TS parser to provide code completion. Can i just extend the TS parser internally?

**Comment by dbaeumer** [comment]
@minggo unfortunately not. You can patch the TS extension however your changes will be lost on the next update.

**Comment by minggo** [comment]
Got it. Can i add a new language to VSCode that just extends TS?

**Comment by dbaeumer** [comment]
Yes you can, but that is equally complicated as providing a second completion provider for JS or TS. I think the complexity in your case is building the AST, computing the right bindings, ... And there is currently no support to ease that.

**Comment by minggo** [comment]
Got it, thanks.
