### ISSUE TITLE
Vscode does not respond suddenly

### ISSUE THREAD

**Issue by JohnsonYan** [Microsoft/vscode#49463]
Issue Type: <b>Bug</b>

causing the computer mouse to click on the screen no matter how it is done, and can only restart

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (4.66GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|5.3.3
vscode-language-pack-zh-hans|MS-|1.23.4
markdown-all-in-one|yzh|1.3.0

</details>

**Comment by komagic** [comment]
一般我是把显卡调整为自动选择而不是独立显卡,    同时关掉谷歌浏览器的硬件加速

**Comment by isidorn** [comment]
Please follow this steps to file a meanigful issue. Thanks
https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by komagic** [comment]
顺便吐槽一句.atom 编辑器经常 卡死 ~~

**Comment by komagic** [comment]
just try to discuss with her，not you sir - -~

**Comment by isidorn** [comment]
Ok

**Comment by JohnsonYan** [comment]
Thankyou guys,I try to reinstall the vscode and fixed it.
Still don't know why but now it runs well, so...
