### ISSUE TITLE
Interrupts in integrated terminal

### ISSUE THREAD

**Issue by tom-programming** [Microsoft/vscode#49470]
Issue Type: <b>Bug</b>

1 Use Linux system. Open the integrated terminal and run "yes". I am assuming that the experience on the integrated terminal should be the same as with a regular terminal

2 Ctrl - C should send a SIGINT and stop the process. It doesn't (but it works somehow in "top")
3 Ctrl-\ should send a SIGQUIT and stop the process with a core dump, but it is masked by a keyboard shortcut that creates a new terminal tab. Even removing this shortcut no signal is sent (again it appears that it works in "top")

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.4.0-121-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz (12 x 3899)|
|Load (avg)|1, 1, 1|
|Memory (System)|31.34GB (13.77GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
Depending on your hardware `yes` could run faster than the parser. Luckily a community contribution is currently in progress to boost the speed of the parser which should improve the situation https://github.com/xtermjs/xterm.js/pull/1399
