### ISSUE TITLE
Selection highlighting no longer highlights partial matches

### ISSUE THREAD

**Issue by mstrkingdom** [Microsoft/vscode#49476]
Issue Type: <b>Bug</b>

Step to reproduce:
Highlight text that is duplicated elsewhere in the document

Expected:
All instances of text that match the selection are highlighted

Actual:
Partial text matches are not highlighted

An example of the old behavior:
![old](https://user-images.githubusercontent.com/16228181/39769820-14ebdb2c-52a2-11e8-9ccb-9b5d0274d2b9.gif)

And the current behavior:
![new](https://user-images.githubusercontent.com/16228181/39769610-8141adde-52a1-11e8-811d-ad548dcd7ca0.gif)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (3.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
xml|Dot|1.9.2
gitlens|eam|8.2.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
svgeditor|hen|1.0.0
beautify|Hoo|1.3.0
Lua|key|0.0.9
ecdc|mit|0.12.0
python|ms-|2018.4.0
cpptools|ms-|0.16.1
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.3.0
vscode-docker|Pet|0.0.26
vscode-icons|rob|7.23.0
jinja|who|0.0.8
markdown-all-in-one|yzh|1.2.0

</details>

**Comment by alexandrudima** [comment]
The selection highlighter respects the match case and whole words find settings:

![image](https://user-images.githubusercontent.com/5047891/39820235-a2999d66-53a5-11e8-9525-5e1c88d4ae43.png)

**Comment by mstrkingdom** [comment]
Oh....I see that now.  I didn't realize those options were related and didn't see any indication that the selection highlighting was being filtered somehow.  Thanks, closing.
