### ISSUE TITLE
(C#) #endregion directive is not being highlighted in the editor

### ISSUE THREAD

**Issue by kurozael** [Microsoft/vscode#4947]
- VSCode Version: 0.10.11
- OS Version: OSX 10.11.4 (El Capitan)

Steps to Reproduce:

1. Open Visual Studio Code in a C# project.
2. Create a #region, #endregion block.

You'll notice that #endregion is not highlighted in the same way that #region is.

![noendregionhighlight](https://cloud.githubusercontent.com/assets/486972/14276763/02dfd3ae-fb18-11e5-939d-f0bbff85335f.png)

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#174
