### ISSUE TITLE
allow for typeahead in treeview and list controls with a lot of potential content

### ISSUE THREAD

**Issue by zersiax** [Microsoft/vscode#49471]
- VSCode Version: 1.22
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Open the Explorer pane, shift+ctrl+e.
2. Start typing the first letters of a filename to move focus towards it, similar to within Windows Explorer listviews Observe that nothing happens.

It would be fantastic for keyboard-only users to quickly zoom towards a specific item in the list. Ctrl+p helps somewhat in this regard but isn't ideal in all circumstances.

**Comment by isidorn** [comment]
@zersiax thanks for your feature request however this was already requested and captured in this issue https://github.com/Microsoft/vscode/issues/10026
Please upvote it there, thanks
