### ISSUE TITLE
(C#) Custom classes are recognized by intellisense, but not syntax highlighted

### ISSUE THREAD

**Issue by kurozael** [Microsoft/vscode#4948]
- VSCode Version: 0.10.11
- OS Version: OSX 10.11.4 (El Capitan)

Steps to Reproduce:
1. Open Visual Studio Code in a C# project.
2. Create a new class, i.e: MyClass in a file MyClass.cs
3. Go to a different file. Add a MyClass as a member variable

You'll notice that MyClass is not highlighted in the same way that "bool", or "float" might be.

![nocustomclasshighlight](https://cloud.githubusercontent.com/assets/486972/14276752/f3c889a6-fb17-11e5-97fe-8f3e91c648fc.png)

**Comment by vladpazych** [comment]
And if you have more than one class in file, methods from only last class will be highlighted.

**Comment by mjbvz** [comment]
I believe this was fixed at some point:

![screen shot 2017-11-15 at 2 36 18 pm](https://user-images.githubusercontent.com/12821956/32864006-5fd8ea6c-ca12-11e7-8f82-8317cffcd105.png)
