### ISSUE TITLE
Webview resources (vscode-resource) all fail with access denied

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#49484]
- VSCode Version: 1.24
- OS Version: Windows 10 x64

With today's insiders release all my `vscode-resource` refs (css and js) are all failing with access denied. Up until last night everything worked fine.

/cc @mjbvz

**Comment by mjbvz** [comment]
I can't repo. Do you have example code? How are you referencing the files?

**Comment by eamodio** [comment]
@mjbvz I can no longer reproduce this, did something explicitly change? Although I guess either way this can be closed.

**Comment by mjbvz** [comment]
Thanks. It may have been broken for one of the insiders builds. Let me know if you see this again
