### ISSUE TITLE
Menubar broken in Sets

### ISSUE THREAD

**Issue by guidowalter** [microsoft/vscode#49487]
Issue Type: <b>Bug</b>

When using VSCode with Sets in Windows RS5 Insider, the menu  bar is broken

VS Code version: Code - Insiders 1.23.0-insider (609c4ba1e7abc39952ef5fb7f3a22c0be0349efe, 2018-04-10T05:17:17.461Z)
OS version: Windows_NT x64 10.0.17661

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.92GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.7.0

</details>

**Comment by bpasero** [comment]
@guidowalter screenshot?

**Comment by chen-ye** [comment]
@bpasero not OP, but I have the same issue: 

![image](https://user-images.githubusercontent.com/1904031/40017817-17de1916-5780-11e8-9a37-7e8a3f794896.png)

Running maximised on a 1080p monitor in a mixed DPI triple screen config.

**Comment by bpasero** [comment]
@guidowalter how does it look like when you run our current insiders release with  `"window.titleBarStyle": "custom"`?

**Comment by guidowalter** [comment]
@bpasero I cannot check it anymore as Sets have been removed from the Insider Builds (https://blogs.windows.com/windowsexperience/2018/06/27/announcing-windows-10-insider-preview-build-17704/). Will test it when it returns. Thanks!

**Comment by bpasero** [comment]
It does not appear as if sets are coming to Windows ever.
