### ISSUE TITLE
Integrated terminal is blank and cannot be reset

### ISSUE THREAD

**Issue by Ithyllias** [Microsoft/vscode#49488]
Issue Type: <b>Bug</b>

Hello!
A couple of weeks ago I logged into my computer session and all of a sudden my VSCode integrated terminal was just a blank screen that I couldn't interact with. It generates no error in the developper tools, changing it to cmd, powershell or git-bash doesn't do a thing either. I've tried uninstalling my VSCode and reinstalling it, updating it, rolling back my versions of Angular, node and Typescript just in case. Nothing seems to do a thing. I've looked throughout the github repo bug reports and found a few similar case but the suggested and accepted solutions did not work for me. Creating new windows, emptying and re opening the terminal don't change anything, and I have no idea whatsoever of how I came to this state in the first place.

Hope someone can help!

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (18.78GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
team|ms-|1.133.0

</details>

**Comment by Tyriar** [comment]
@Ithyllias can you share your settings.json file? Also can you try change the shell using the "Change Default Shell" command in the command palette (F1) to see if that fixes it?

**Comment by Ithyllias** [comment]
Okay, yep, I've used that command to switch it to the bash.exe but still nothing in the terminal. I also tried to close and reload it to no avail :(

**Comment by Tyriar** [comment]
@Ithyllias did the other shells work?

**Comment by Tyriar** [comment]
Can you close all VS Code windows and then launch in a terminal with `code --log trace`. This will expose some terminal logs that you can get to from the command "Developer: Open Log File..." (F1 opened command palette). Can you get the logs when the issue happens and paste it in here?

**Comment by Ithyllias** [comment]
I did, and somehow now it works!! I did not even need to go check in the logs... Well thanks a lot for your time, i'll check those logs if it ever happens again!

**Comment by Tyriar** [comment]
Yes please do, glad to hear it's working again 👍
