### ISSUE TITLE
"Go To Definition" unnecessarily shows import definition 

### ISSUE THREAD

**Issue by webberwang** [Microsoft/vscode#49486]
Not so much a bug, but a better approach.

- VSCode Version: 1.23.0
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. F12 on a definition usage
2. 2 definitions will show up (import & original)

In WebStorm, the IDE will automatically jump to the original definition (ignoring the import statement). 95% of the time, we're looking for the original definition (not the import statement).

It really kills productivity having to select the original definition in the window popup. The import definition should just be ignored by default, or have some sort of setting to toggle whether the import definition should be shown.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please test in insiders and provide a code example that shows when we incorrectly jump to the import

**Comment by webberwang** [comment]
I ended up disabling all plugin in VSCode & the error went away, turns out the culprit was the extension "Auto Import".
