### ISSUE TITLE
Double curly braces inserted

### ISSUE THREAD

**Issue by vomout** [Microsoft/vscode#49480]
I have "editor.autoClosingBrackets": false in VSCode settings, as auto-braces are annoying and a source of a million build errors with latex (using LaTeX-Workshop). Sometimes, however, when I insert a new closing curly brace near an existing one, the new one is inserted doubled. With the procedure below I always manage to reproduce the issue in newly created tabs without any syntax set or language chosen. However, I believe to have observed the issue in other situations as well, not involving tab-switching.

- VSCode Version: 1.23.0
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. Set  "editor.autoClosingBrackets": false (may not even be necessary)
2. Open a new tab (cmd-n). Type a closing curly brace }.
3. Open a new tab (cmd-n).
4. Switch back to the first opened tab.
5. Type a closing curly brace }.
6. Observe two new curly braces being inserted, resulting in altogether three of them. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
This reproduces with any character, e.g. `a`.

**Comment by chiaisthewei** [comment]
This seems related: if you have any type of opening/closing punctuation, e.g. double quotes, quotes, brackets, parentheses, when you move away from the file and come back, and type something in them that was the same as the previous character, it results in a multiple duplicate characters.

**Comment by chiaisthewei** [comment]
Short video of an example: https://streamable.com/ygrsx

**Comment by reedspool** [comment]
@alexandrudima Hello, wondering when I will see this fixed on my machine? I see it's very recently been fixed and closed, and I'm very thankful for that, but I don't know how to figure out where in the pipeline that fix is. Cheers.

**Comment by alexandrudima** [comment]
@reedspool 

When a commit is pushed to master, the next day's build of [VS Code Insiders](https://code.visualstudio.com/insiders/) will very likely contain that commit (except for weekends, then it is Monday).

The current stable version is June 2018 (1.25). When an issue is closed, it is typically assigned a milestone. For this issue, that would be "July 2018". Typically, the stable channel will see the previous month's release a few days in the next month, so in a few days the July 2018 branch will be released to the stable channel. Sometimes, the wait is shorter, sometimes the wait is longer, depending on what we discover during testing and stabilization.
