### ISSUE TITLE
Is it a bug in vscode ?

### ISSUE THREAD

**Issue by DFVSQY** [Microsoft/vscode#49481]
- VSCode Version: 1.23.0
- OS Version: win10 x64

Steps to Reproduce:

Please see[ this issue](https://github.com/Microsoft/vscode-cpptools/issues/1956#issuecomment-387480960), they said that this is a bug in vscode.

**Comment by DFVSQY** [comment]
@isidorn  I think i have already made this issue clear. because [they can reproduce my bug](https://github.com/Microsoft/vscode-cpptools/issues/1956#issuecomment-387480960).

**Comment by isidorn** [comment]
Clsoing as will not fix, lack of good repro steps

**Comment by DFVSQY** [comment]
@isidorn i think this bug has been fixed in the newer version.
