### ISSUE TITLE
one pix more between minimap and sidebar

### ISSUE THREAD

**Issue by zjjott** [Microsoft/vscode#49499]
- VSCode Version: 1.23.0
- OS Version: macOS 10.13.4  
- Display: 1920 x 1200

Steps to Reproduce:

1. input a long string more than one line(about 80 char)
2. between minimap and sidebar,there is one pix out like this:
![image](https://user-images.githubusercontent.com/3733548/39792845-414a03f0-5375-11e8-8182-29675f93cec8.png)

![image](https://user-images.githubusercontent.com/3733548/39792861-51a3fc4c-5375-11e8-9e75-eb7b8412cac8.png)

**Comment by alexandrudima** [comment]
@zjjott I cannot reproduce. Are you using `window.zoomLevel` perhaps ?

**Comment by alexandrudima** [comment]
For pixel perfect rendering, please use `"window.zoomLevel": 0`.
