### ISSUE TITLE
Clang autoformat has stopped working properly in the latest release

### ISSUE THREAD

**Issue by gilcolgate** [Microsoft/vscode#49493]
Issue Type: <b>Bug</b>

Have .cc code.

Had clang autoformat installed.

Select 'Format Document'

Document is unchanged.

Tried with numerous documents.

Example of very simple document ( with formatting error, names redacted)

#pragma once
namespace thenamespace {
 
int DoSomething(
    const std::string& version_string,
    const  configuration& config); }; 

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.13.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.37GB (9.10GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-glsllint|CAD|0.0.3
spgo|Sit|1.2.2
code-gnu-global|aus|0.2.2
githistory|don|0.4.0
gitlens|eam|8.2.4
githd|hui|1.1.3
vscode-clang|mit|0.2.2
python|ms-|2018.4.0
cpptools|ms-|0.17.0
proto|pet|0.0.2
trailing-spaces|sha|0.2.11
shader|sle|1.1.3
clang-format|xav|1.6.2

(3 theme extensions excluded)

</details>

**Comment by gilcolgate** [comment]
Uninstalling Visual Studio Code and reinstalling it fixed the issue. I don't know why this happened.

**Comment by gilcolgate** [comment]
Discovered what this actually is. (On Ubuntu)  Previously when you ran clang it would sometimes hang (why? Maybe a bug in clang). Visual Studio Code would stop clanging. Quitting Visual Studio code and reopening it would kill all the clang jobs. Since this was not disruptive I never reported this bug.

Now it seems that the clang jobs are run on the side, so quitting visual studio code does not stop them. Once clang stopped working again,   I saw 12 clang jobs in my SysInfo.

I manually closed them and then Visual Studio code could clang again.

Summary: Sometimes clang hangs, and future clang jobs queue up. Previously quitting and restarting Visual Studio Code would close the clang jobs, but now it doesn't.

**Comment by willdzeng** [comment]
![image](https://user-images.githubusercontent.com/12994633/39848356-5c0ad5de-53bb-11e8-9360-af2dfb713629.png)

I found the same thing, it hangs forever.

**Comment by gilcolgate** [comment]
I am not sure why this is happening, but now whenever I auto format code launches   a process  clang-format in the system tasks, with a executable  "/home/gilcolgate/.vscode/extensions/ms-vscode.cpptools-0.17.0/bin/../LLVM?bin/clang_format" with parameters, and then just sits waiting forever. Once only about a minute later the format went off and my file suddenly became formatted. 

If I run clang format from the command line it works properly and instantly:
/usr/bin/clang-format-5.0 -i XXX.cc

Note:
"clang-format.executable": "/usr/bin/clang-format-5.0",

I tried copying this /usr/bin/clang-format-5.0 to replace /home/gilcolgate/.vscode/extensions/ms-vscode.cpptools-0.17.0/bin/../LLVM?bin/clang_format but this made no difference.

**Comment by mjbvz** [comment]
Please file this issue against the cpptools extension
