### ISSUE TITLE
User Snippets function does not work well.

### ISSUE THREAD

**Issue by vinsonyung** [Microsoft/vscode#49498]
- VSCode Version: 1.23.0
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Add PHP snippets, prefix it with "met" in "User Snippets"

```json
"new method": {
	"prefix": "met",
	"body": [
		"${1:public} function ${2}(${3})",
		"{",
		"\treturn ${4}",
		"}"
	],
	"description": "Creat new method"
},
```

2. Create class with functions

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    /**
     * Get the profile record associated with the user.
     */
    public function profile()
    {
        return $this->belongsTo(User::class);
    }

   # Use snippet "met" here
}
```

3. Type "met", it sometimes does not show up the snippet in popup menu.
https://pasteboard.co/HkjfxH6.gif

Does this issue occur when all extensions are disabled?: No

Extensions:
  ansible v0.2.8
  ansible-autocomplete v0.0.2
  code-settings-sync v2.9.2
  dart-code v2.12.1
  EditorConfig v0.12.1
  githistory v0.4.0
  Go v0.6.79
  java v0.24.0
  jinja v0.0.8
  laravel-blade v1.18.0
  laravel5-snippets v1.4.0
  npm-intellisense v1.3.0
  php-cs-fixer v0.1.70
  php-debug v1.12.3
  php-docblocker v1.6.0
  phpcs v1.0.5
  prettier-vscode v1.3.1
  python v2018.4.0
  rest-client v0.18.4
  sass-indented v1.4.9
  semantic-ui-snippets v0.0.7
  theme-material-theme v1.0.1
  vetur v0.11.7
  vscode-docker v0.0.26
  vscode-eslint v1.4.8
  vscode-icons v7.23.0
  vscode-intelephense-client v0.8.8
  vscode-java-debug v0.9.0
  vscode-java-pack v0.3.0
  vscode-java-test v0.6.1
  vscode-markdownlint v0.15.0
  vscode-maven v0.7.0
  vscode-npm-script v0.3.4
  vscode-raml v3.0.1
  vscode-table-formatter v1.2.1

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">
