### ISSUE TITLE
terminal.integrated.shell does not expand $HOME or ~

### ISSUE THREAD

**Issue by FiloSottile** [microsoft/vscode#49496]
Issue Type: <b>Feature Request</b>

The various `terminal.integrated.shell` settings do not support neither `$HOME` nor `~`, making it impossible to make a cross-machine config when the user names are not the same.

For example, this will fail:

```
"terminal.integrated.shell.osx": "~/homebrew/bin/zsh"
```

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

**Comment by Tyriar** [comment]
We currently enable this sort of thing for the `env` setting using this syntax:

```
"terminal.integrated.env.osx": "${env.HOME}"
```
