### ISSUE TITLE
Sadness on latest update... 'bug' fixed

### ISSUE THREAD

**Issue by gilcolgate** [Microsoft/vscode#49492]
Issue Type: <b>Bug</b>

Formerly you could 'clear terminal' even while your terminal was busy with a process. Now it queues the control-l until the process is  done.

I don't know how often the previous behavior was useful , but it was plenty. I would often start my compile, clear the terminal, and only have to deal with the errors of that run. Or I would be debugging an interactive program with lots of output, and clear the output, so I am only looking at what the computer is doing right now.

I would like there be a way to clear the terminal even when the terminal is busy.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.13.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.37GB (9.50GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-glsllint|CAD|0.0.3
spgo|Sit|1.2.2
code-gnu-global|aus|0.2.2
githistory|don|0.4.0
gitlens|eam|8.2.4
githd|hui|1.1.3
vscode-clang|mit|0.2.2
python|ms-|2018.4.0
cpptools|ms-|0.17.0
proto|pet|0.0.2
trailing-spaces|sha|0.2.11
shader|sle|1.1.3
clang-format|xav|1.6.2

(3 theme extensions excluded)

</details>

**Comment by arfl** [comment]
This behaviour is really really annoying and the terminal is pretty useless now, at least for me. Started using external terminal again...

**Comment by Tyriar** [comment]
I reverted this change, it'll go out in the recovery build 1.23.1. See https://github.com/Microsoft/vscode/issues/49162#issuecomment-386820864
