### ISSUE TITLE
Inserting ( trying to ) insert a c language snippet should give example in C language - But it gives json language example

### ISSUE THREAD

**Issue by raikrahul** [Microsoft/vscode#49490]
Issue Type: <b>Bug</b>

1 ) Try to insert a snippet, while doing a project, in C 

2) See the example

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.15.0-20-generic

**Comment by jrieken** [comment]
@raikrahul Please provide actionable information. Thanks
