### ISSUE TITLE
Command to open raw user settings.json, not in split view

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#49495]
We have a setting to disable the settings split view, but it might be useful to have a command to open the user settings.json outside of the split view for a one-off.

From https://github.com/Microsoft/vscode/issues/41040#issuecomment-387479618

**Comment by roblourens** [comment]
@usernamehw I am reverting the PR, it actually doesn't work. We intercept the editor open here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/common/preferencesContribution.ts#L83

**Comment by usernamehw** [comment]
Damn, it's already a part of my workflow 😢. What's wrong with it?

**Comment by roblourens** [comment]
So it opens the raw settings.json outside of the split view for you? For me, it actually just acts the same as the normal open settings command and opens the settings split view.

**Comment by roblourens** [comment]
And you don't have `"workbench.settings.openDefaultSettings": false`?

**Comment by usernamehw** [comment]
I don't have `"workbench.settings.openDefaultSettings": false`. The command itself works for me. Does it break some other functionality?

![works](https://user-images.githubusercontent.com/9638156/40560314-4a1c3864-6062-11e8-8855-9c04b5d7d895.gif)


OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
I see now. Opens a split view on linux VM. Was it ever working before on non-Windows environments?

**Comment by roblourens** [comment]
Yeah it only works on Windows, because the == check with fspath can fail due to drive letters being different. I guess that's a separate bug... I'll revert this tomorrow.

**Comment by roblourens** [comment]
We got a good bug out of this: #50760

**Comment by roblourens** [comment]
Now that the settings UI exists, I don't plan on investigating much more on the JSON editor. The split JSON UI will probably go away at some point (the JSON files themselves will always remain)

**Comment by roblourens** [comment]
We will always allow users to see the json file. Hopefully you can still open the raw json file with `"workbench.settings.openDefaultSettings": false`.

**Comment by usernamehw** [comment]
I know about that option, it's not great.

**Comment by roblourens** [comment]
I'll close this just because I am cleaning up issues that are specific to the JSON split editor. But to be clear, editing the JSON file will never go away :)
