### ISSUE TITLE
Selection expansion command and hotkey

### ISSUE THREAD

**Issue by oliverjanik** [Microsoft/vscode#495]
One of the features I can't live without is selection expansion and contraction. This is obviously language specific but it would be amazing.

Here are two implementations:
 - https://www.jetbrains.com/resharper/help/Coding_Assistance__Extend_Shrink_Selection.html
 - https://github.com/aronwoost/sublime-expand-region

**Comment by egamma** [comment]
Already supported: the command is 'Expand Select', 'Shrink Select'.

**Comment by oliverjanik** [comment]
Seems this is not supported for HTML and even in JS is nowhere as smart as Resharper one.
