### ISSUE TITLE
[Tree view API] Load the tree view before expanding the panel

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#49504]
Use [Azure IoT Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit) to reproduce
![image](https://user-images.githubusercontent.com/1050213/39797834-8febf00c-5390-11e8-8ba6-5d3460c51055.png)

**Before VS Code v1.22:**
The tree view will be rendered right after the extension is activated

**Starting from VS Code v1.22:**
The tree view will be rendered only after you click the 'Azure IoT Hub Devices' panel

I am wondering whether it is a designed change or bug?
If it is a change by design, i want to know whether there is a way to render the tree view in advance. The reason is that it takes several seconds to get the IoT Hub devices info from service side and render the tree view, we want to render the tree view list as early as possible.

**Comment by sandy081** [comment]
@formulahendry Not sure if I understand completely. What do you mean by 

- Rendering after activation vs after user click?

Is the view empty even if it is visible and expanded?

**Comment by formulahendry** [comment]
Hi @sandy081,  the view is empty after the first time it is visible and expanded, then it takes some seconds to render the view.
I want to render the view after activation (which is the behavior before VS Code 1.22), instead of after user click (which is current behavior)

**Comment by formulahendry** [comment]
Before VS Code 1.22, the view is rendered after activation. So when user click the 'Azure IoT Hub Devices' panel, they could see the view immediately.

**Comment by sandy081** [comment]
@formulahendry Yes this is expected. Tree view is not rendered until it is visible. You can load your model when activated and feed tree view with data using data provider when asked.
