### ISSUE TITLE
"Auto-attach" not working on node.js under bash / linux subsystem

### ISSUE THREAD

**Issue by JeffDOfTheNorth** [Microsoft/vscode#49502]
Requirements:
- Linux subsystem for Windows installed
- NodeJs installed

Repro steps:
1. Launch VS code
2. Make a file (server.js) Paste in code (bottom of report), and set a breakpoint on response.write("hi")
3. Launch the terminal (CTRL+`)
4. In the terminal, run:
     > bash
     > node --inspect server
5. In a browser, navigate to http://localhost:3000

### Actual 
your breakpoint isn't hit (because VS Code isn't attached)

### Expected
your breakpoint is hit. If, in step 4, you had not run bash, and instead run node from a standard command prompt or powershell prompt, it will work, and the breakpoint will be hit when you navigate to yoru browser. 

### Code:
var http = require('http')
var server = http.createServer(function(request, response)
{
    response.write("hi!");
    response.end();
})
server.listen(3000);

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:10.813Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (9.80GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.4.3

</details>
 your clipboard because it was too large to send. Please paste.

**Comment by crispinb** [comment]
I find the same regardless of value of `terminal.integrated.shell.windows` (ie. pointing to any of bash, wsl, cmd or powershell). Using a minimal node example similar to that of the OP, enabling auto-attach never has any effect.


Vs Code version: Version: 1.27.0-insider
Commit: fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099
Date: 2018-08-17T05:18:51.696Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS Version: Windows 10.0.17134 Build 17134

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
