### ISSUE TITLE
Visual bug in terminal

### ISSUE THREAD

**Issue by Wragdan** [Microsoft/vscode#49505]
Issue Type: <b>Bug</b>

I'm using Insiders editions, and since yesterday, when i use the integrated terminal, it sort of appears like a badly cleaned whiteboard, when i could still see commands on the back even after running ``` clear```. It happens when running yarn or npm, where it updates the terminal screen often. 

![image](https://user-images.githubusercontent.com/17775924/39799767-aa2c5c0e-5322-11e8-9636-283ed08ee341.png)

VS Code version: Code - Insiders 1.24.0-insider (8a07c8d935998d1b1153dde0c5b337189d35cea0, 2018-05-08T05:10:44.902Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.64GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron restaurantApi|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-markdownlint|Dav|0.15.0
rails-snippets|Hri|1.0.8
material-icon-theme|PKi|3.4.0
vscode-docker|Pet|0.0.26
rails|bun|0.5.7
solargraph|cas|0.17.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.8
vscode-new-file|dku|4.0.2
gitlens|eam|8.2.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.1.1
Angular2|joh|6.0.0
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
vscode-azureappservice|ms-|0.8.0
mssql|ms-|1.3.1
python|ms-|2018.4.0
azure-account|ms-|0.4.0
cpptools|ms-|0.17.0
csharp|ms-|1.14.0
vsliveshare|ms-|0.3.93
debugger-for-chrome|msj|4.4.3
heroku-command|pko|0.0.8
Ruby|reb|0.18.0
java|red|0.24.0
language-stylus|sys|1.9.2
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.7.0
vscode-todo-highlight|way|0.5.12
JavaScriptSnippets|xab|1.6.0
ReactSnippets|xab|2.1.0
markdown-all-in-one|yzh|1.3.0

(1 theme extensions excluded)

</details>

**Comment by Wragdan** [comment]
If it helps, i use zsh with oh-my-zsh, using `refined` theme. For plugins i have zsh-autosuggestions. I have no problem when using iterm or terminal.

**Comment by Wragdan** [comment]
I could solve it changing my settings like this [comment](https://github.com/Microsoft/vscode/issues/49438#issuecomment-387583242)
```json
    "workbench.colorCustomizations": {
        "terminal.background": "#122738"
    },
```
but it's still a bug, which wasn't there yesterday.

**Comment by mgaudet** [comment]
I am seeing this too, but am not able to rectify it with the above `terminal.background` fix.
