### ISSUE TITLE
why the tip of method and parameters is Chinese garbled

### ISSUE THREAD

**Issue by mrpengfei** [Microsoft/vscode#4950]
- VSCode Version:0.10.11
- OS Version:windows 10

Steps to Reproduce:
why the tip of method and parameters is Chinese garbled. 

1. 
![qq 20160405161945](https://cloud.githubusercontent.com/assets/5754718/14276360/12949f8a-fb51-11e5-8fac-4a940491a161.png)

2.

**Comment by alexandrudima** [comment]
Moved to OmniSharp/omnisharp-vscode#140
