### ISSUE TITLE
switch terminal is wrong when I use split terminal

### ISSUE THREAD

**Issue by mizutoki79** [Microsoft/vscode#49516]
- VSCode Version: 1.23.0
- OS Version: Windows 10 Pro 1709

Steps to Reproduce:

1. Create new integrated terminal
2. Split terminal
3. Create new integrated terminal
4. Open Command Palette
5. Select "Terminal: Switch Active Terminal"
6. Select 2
example
```
1: pwsh, pwsh
2: pwsh
```
7. I think that open "2:pwsh", but actually open "1: pwsh, pwsh" and active 2nd shell (right pane).

![vscode](https://user-images.githubusercontent.com/13725109/39806318-94c5d2f4-53b4-11e8-9533-941b685f439e.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Thanks for spotting this, I recently fixed for the rename/kill buttons in the `term` menu but missed switching not working.
