### ISSUE TITLE
Ability to access selected elements in Tree view

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#49511]
Provide an API in `Treeview` to get selected elements

**Comment by chrisdias** [comment]
The simple case would be something like this. i want to add a "delete" button to the Docker explorer which would delete/remove a single image.  I need to be able to get the selected item in the tree when clicking on the "X" command in the explorer title bar area.

![image](https://user-images.githubusercontent.com/1487073/40077353-476052e2-5836-11e8-8382-e86a6be388b4.png)

Selection change is not necessary in this scenario, but I could see how that might be interesting.

Another scenario is the Azure App Service/Functions extension where you want to be able to select an app service, then click on the "deploy" action and deploy to that service.  That way, you don't have to ask the user a bunch of questions on where to deploy to.

//cc: @fiveisprime

**Comment by sandy081** [comment]
Thanks @chrisdias. Got it.

**Comment by DanTup** [comment]
@sandy081 If we can add icons to the toolbar(?) as shown in the screenshot above, a change event might address the issues I'd originally asked about dynamic context menus for - we could hook the change event and toggle some contexts, and apply those contexts to the actions on that toolbar? :)

**Comment by sandy081** [comment]
@DanTup not sure what you mean... I remember about the dynamic context menu issue but do not understand your comment related to it.

Can you please add your comment in the issue related to dynamic context menu if it is nothing to do with this issue so that this will not get distracted. 

Thanks

**Comment by sandy081** [comment]
Added `selections` api to `TreeView`

```typescript
/**
 * Currently selected elements.
*/
readonly selection: ReadonlyArray<T>;

```

**Comment by DanTup** [comment]
@sandy081 Sorry for the confusion; you asked above whether a change event was required. My comment was that if you do add a change event, it may solve the issue I had that I wanted the dynamic context menu for.

So, my comment is basically a request for the change event :-)

**Comment by sandy081** [comment]
Commented in the issue related to dynamic menus. Lets discuss over there.
