### ISSUE TITLE
When opening an extra terminal window (New terminal) it doesn't get focus

### ISSUE THREAD

**Issue by torjuss** [Microsoft/vscode#49514]
Issue Type: <b>Bug</b>

Open the integrated terminal. Then open another terminal window by pressing the plus sign. The second terminal window should now get focus, but it doesn't so I have to use the dropdown to switch to the new terminal.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (21.95GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Workspace\ISY.360\Construct|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
react-native-react-redux|EQu|1.8.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-firefox-debug|hbe|1.2.1
vscode-redux-devtools|jin|0.0.11
resharper9-keybindings|ms-|1.1.0
debugger-for-chrome|msj|4.4.3
vscode-icons|rob|7.23.0

</details>

**Comment by Tyriar** [comment]
I've never seen this before 😕, Do you have any errors in the console? (Help > Toggle Developer Tools)
