### ISSUE TITLE
Failed to install VS Code update

### ISSUE THREAD

**Issue by patrickhrastnik** [Microsoft/vscode#49512]
The VS Code Update asked me to open a new issue and attach the following logfile.

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1986942/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
Does this still happen after restarting your system?

**Comment by patrickhrastnik** [comment]
I have had this issue several times with VS Code Updates.
I always have to reboot my PC and download and install the setup manually without starting VS Code after reboot.
The update won't work if I try to start it via the prompt in VS Code, and it won't work if I have had VS Code opened since the last reboot.

**Comment by joaomoreno** [comment]
Which OS version are you on?

**Comment by patrickhrastnik** [comment]
Windows 10 Pro 64-bit

Here's the information VS Code generates when creating an error report:

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (0.44GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
vs-code-xml-format|fab|0.1.5
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.5.6
live-html-previewer|hdg|0.3.0
typings-autoinstaller|jvi|1.2.0
vscode-language-pack-de|MS-|1.23.3
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.4.3
material-icon-theme|PKi|3.4.0
vscode-sql-beautify|sen|0.0.4
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Do you have any USB storage devices connected to your computer? The error seems related to one of them not working properly.

**Comment by patrickhrastnik** [comment]
Not a USB storage device, but an infrared module for a wireless mouse. That's the only USB device connected.

**Comment by patrickhrastnik** [comment]
Do you need any further info?

**Comment by joaomoreno** [comment]
Yeah... but I'm out of ideas for more questions. 😆 

Where is Code installed in your file system? Which path?

Do you have another machine where you could try to reproduce the problem?

**Comment by patrickhrastnik** [comment]
> Where is Code installed in your file system? Which path?

"C:\Program Files\Microsoft VS Code"

> Do you have another machine where you could try to reproduce the problem?

We're gonna try if we have the same problem on my colleague's working station.

**Comment by patrickhrastnik** [comment]
On my colleague's working station the setup ran through without any problems.

**Comment by joaomoreno** [comment]
@patrickhrastnik And has this new update ever worked for you, or always fails with this error?

**Comment by patrickhrastnik** [comment]
This new update always failed for me. It has never worked this way.

**Comment by joaomoreno** [comment]
I'm out of ideas. It seems your machine has something about it which makes the update fail with 

> Ein an das System angeschlossenes Gerät funktioniert nicht

I suggest to disable background updates with the following setting:

```
"update.enableWindowsBackgroundUpdates": false
```
