### ISSUE TITLE
String truncation limit lifted to 10000

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4952]
- [x] Windows @jrieken 
- [x] OS X @kieferrm 
- [x] Linux @vsccarl 

The node v8 debugger protocol truncates strings automatically to a (non configurable) 80 characters and appends a '...  (length: 123)'.
Node debug tries to extend this rather small limit to 10000 by retrieving the string contents for long strings through 'evaluate'.

Verify that:
- strings in the debugger are only truncated if they are longer than 10000.
- the UI (hovers, variables view, repl) shows long strings correctly.

**Comment by v-pavanp** [comment]
I think it should be 1000.
![image](https://cloud.githubusercontent.com/assets/17735796/14398575/13b97462-fd9a-11e5-9a9c-8adea3feb600.png)

**Comment by vsccarl** [comment]
Strings that are roughly 4,000 or more are being proportionally being truncated when using console.log(string) in Linux. A string that is 4069 characters is being output with only 4047 characters. A string that is 9922 characters outputs only 9504 characters.
