### ISSUE TITLE
Feature Request : possibility to run task from folder in Explorer panel

### ISSUE THREAD

**Issue by XenoMehdi** [microsoft/vscode#49522]
It is very helpful to add the possibility to run one of the configured task on a specific folder in the project, by right clicking on the folder in explorer and chose the task, the folder path then will be used as the option  "cwd". this give more flexibility for big projects with Makefiles inside each folder.

**Comment by alexr00** [comment]
I think having https://github.com/microsoft/vscode/issues/71461 would be a neat solution for having lots of makefiles. You could have one task that prompts for a folder and runs the make.
