### ISSUE TITLE
c++自动补全main函数重复出现两个int

### ISSUE THREAD

**Issue by 5555yxy** [Microsoft/vscode#49520]
Issue Type: <b>Bug</b>

如题
![snipaste_2018-05-09_17-59-22](https://user-images.githubusercontent.com/24839642/39808911-dfe2a840-53b2-11e8-935a-49831f822083.png)
![snipaste_2018-05-09_17-59-40](https://user-images.githubusercontent.com/24839642/39808913-e3529c60-53b2-11e8-9d48-62c064a7dcf1.png)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (4.54GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.2
vscode-language-pack-zh-hans|MS-|1.23.4
mssql|ms-|1.3.1
python|ms-|2018.4.0
cpptools|ms-|0.17.0
vscode-code-outline|pat|0.1.1
rust|rus|0.4.2

(1 theme extensions excluded)

</details>

**Comment by wangweixuan** [comment]
这是因为自动补全的代码里自带一个 int 了，你前面又打了一个 int，所以有两个。你不要打 int，直接打 main 然后选自动补全就是正常的，这不算 VS Code 的 bug。
