### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Corons** [Microsoft/vscode#49526]
Issue Type: <b>Bug</b>

在我使用python 执行的时候 ，有的时候多余的空格会让我报错SyntaxError: unexpected EOF while parsing，这个很影响我写代码（关键在于有时候能执行不报错，而有的时候突然的报错，让我无法理解）

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Users/coron/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.15.0
vscode-language-pack-zh-hans|MS-|1.23.4
code-settings-sync|Sha|2.9.2
project-manager|ale|0.25.2
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
vscode-great-icons|emm|2.1.31
code-runner|for|0.9.3
highlight-icemode|ice|0.0.6
Angular2|joh|6.0.0
cmake-tools-helper|mad|0.2.1
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.4.0
azure-account|ms-|0.4.0
cpptools|ms-|0.17.0
debugger-for-chrome|msj|4.4.3
vscode-yaml|red|0.0.11
vscode-icons|rob|7.23.0
python|tht|0.2.3
cmake|twx|0.0.17
cmake-tools|vec|0.11.1
vim|vsc|0.11.6

</details>

**Comment by isidorn** [comment]
Please follow this steps and file a proper issue in english, thanks!
