### ISSUE TITLE
Feature Request : possibility to deactivate comments in Search panel

### ISSUE THREAD

**Issue by XenoMehdi** [Microsoft/vscode#49521]
I suppose that sometimes a developer need to look for a variable or function inside the code but not in the comments, it will be more helpful to give the possibility to activate or deactivate search in the comments from search panel.

**Comment by roblourens** [comment]
Our search just operates at the text level and it's not likely that we'll be able to support a feature like this that parses every file.

But, we are working on a search provider extension API which would make it possible for an extension to implement this...
