### ISSUE TITLE
Clarify activeParameter in SignatureHelp

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#49528]
`activeParameter` is currently speced to be only valid on the active signature. However we use it as well if the users scrolls through signature options to highlight the active parameter. We should adjust the doc accordingly and we might want to consider whether signartures that have less number of parameters than the active parameter should be filtered.

**Comment by jrieken** [comment]
I believe we have all of that now, esp the user selected value is passed on to extensions now
