### ISSUE TITLE
cannot using CTRL+c as copy

### ISSUE THREAD

**Issue by whoisleehom** [Microsoft/vscode#49533]
Issue Type: <b>Bug</b>

cannot using ctrl+c as copy as usual, no idea of what's going on

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:10.813Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (9.86GB free)|
|Process Argv|D:\tools\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.23.4
python|ms-|2018.4.0
cpptools|ms-|0.17.0

</details>

**Comment by whoisleehom** [comment]
solved this problem by changing all copy's keyboard shortcuts to ctrl+c

**Comment by Tyriar** [comment]
@whoisleehom is this within the editor?

**Comment by whoisleehom** [comment]
Yes, within the editor. But I solved it by changing all COPY to CTRL+C. This situation never happened before.

发送自 Windows 10 版邮件应用

发件人: Daniel Imms
发送时间: 2018年5月11日 23:51
收件人: Microsoft/vscode
抄送: whoisleehom; Mention
主题: Re: [Microsoft/vscode] cannot using CTRL+c as copy (#49533)

@whoisleehom is this within the editor?

**Comment by alexandrudima** [comment]
@whoisleehom Can you please provide any reproducible steps?

**Comment by sagarpatil232** [comment]
I'm also having the same issue.
Even when I uninstalled and re-installed still issue is there. Basically whenever the editor opens, the cursor just blinks like as if insert key is on.

**Comment by alexandrudima** [comment]
@sagarpatil232 The OP claims <kbd>Ctrl</kbd>+<kbd>C</kbd> does not work. How exactly do you have the same issue if the cursor "just blinks like as if insert key is on". Have you disabled all extensions before reproducing ?

**Comment by sagarpatil232** [comment]
Thanks. Disabling vim extension worked for me.

**Comment by whoisleehom** [comment]
Yes, it is within the editor.

发送自 Windows 10 版邮件应用

发件人: Daniel Imms
发送时间: 2018年5月11日 23:51
收件人: Microsoft/vscode
抄送: whoisleehom; Mention
主题: Re: [Microsoft/vscode] cannot using CTRL+c as copy (#49533)

@whoisleehom is this within the editor?

**Comment by alexandrudima** [comment]
@whoisleehom Can you please provide any reproducible steps?
