### ISSUE TITLE
VSCode is unable to fetch JSON schemas from URLs that contain the '@' character

### ISSUE THREAD

**Issue by ydogandjiev** [Microsoft/vscode#49535]
- VSCode Version: 1.23.0
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. Create a JSON file with $schema property pointing to a URL that contains the '@' character:
`{
  "$schema": "https://unpkg.com/@microsoft/teams-js@1.3.0-beta.1/dist/MicrosoftTeams.schema.json"
}
`
2. The problems tab shows the following error:
`Unable to load schema from 'https://unpkg.com/%40microsoft/teams-js%401.3.0-beta.1/dist/MicrosoftTeams.schema.json': Invalid URL: /%40microsoft/teams-js%401.3.0-beta.1/dist/MicrosoftTeams.schema.json
`

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by aeschli** [comment]
From how I understand https://www.ietf.org/rfc/rfc1738.txt it is valid to encode `@` in the URL by `%40`, it is even recommended as `@` is a character with a special meaning.
 
So would say the bug is with the 'unpkg.com' server.
