### ISSUE TITLE
The save does not save.

### ISSUE THREAD

**Issue by danilocecilia** [Microsoft/vscode#49531]
When I press ctrl+s to save any change, It sometimes unchanged values when debugging, so I have to go back to the file I´ve changed before and saved it again multiple times ...

**Comment by isidorn** [comment]
Please follow these steps to file a good issue with reproducable steps
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by geeksamu** [comment]
If you were using `Import-cost` extension. Disable it and try to save.
I faced the same problem and solved it by disabling this extension.

**Comment by geeksamu** [comment]
No No, I think I found the problem with my case
I'm using Angular and when I try to import anything that I don't use the typescript code. VSCode removes it when I save the code.

But if you imported anything and used it. It won't remove it.
I hope this would help

**Comment by isidorn** [comment]
I would still need more details from @danilocecilia
