### ISSUE TITLE
Javascript Label bad colors on Editor

### ISSUE THREAD

**Issue by fbaezap** [Microsoft/vscode#49532]
The colors are failing with the label statement
![test](https://user-images.githubusercontent.com/4632032/39816578-0b5dce3c-5372-11e8-8e4e-50ba3d05c878.png)

- VSCode Version: 1.23.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a Javascript File
2. Paste following code
```javascript
class Test {
  constructor() {
    hola: {
      const x = 1;
      console.log('bad highlight');
      break hola;
    }
  }
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#610
