### ISSUE TITLE
 Uncaught Error: Model is disposed!

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#49547]
Issue Id: <b>945795f9-17b3-9ace-787a-2b4a32586f34</b><br /><br />*Versions* <br />- 1.23.0<br />-  b8475d1dc68bfee70c3fbe3e7fc39f6e0003803b<br />*Stack* <br />Error: Model is disposed!<br />[/vs/editor/common/model/textModel.ts#364:9 (_assertNotDisposed)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/common/model/textModel.ts#L364:9 (_assertNotDisposed))<br />[/vs/editor/common/model/textModel.ts#684:7 (getVersionId)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/common/model/textModel.ts#L684:7 (getVersionId))<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#184:32 (_ensureValidState)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/common/viewModel/splitLinesCollection.ts#L184:32 (_ensureValidState))<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#706:7 (convertViewPositionToModelPosition)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/common/viewModel/splitLinesCollection.ts#L706:7 (convertViewPositionToModelPosition))<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#109:21 (convertViewPositionToModelPosition)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/common/viewModel/splitLinesCollection.ts#L109:21 (convertViewPositionToModelPosition))<br />[/vs/editor/browser/view/viewOutgoingEvents.ts#137:46 (_convertViewToModelPosition)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/browser/view/viewOutgoingEvents.ts#L137:46 (_convertViewToModelPosition))<br />[/vs/editor/browser/view/viewOutgoingEvents.ts#130:26 (_convertViewToModelMouseTarget)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/browser/view/viewOutgoingEvents.ts#L130:26 (_convertViewToModelMouseTarget))<br />[/vs/editor/browser/view/viewOutgoingEvents.ts#119:17 (_convertViewToModelMouseEvent)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/browser/view/viewOutgoingEvents.ts#L119:17 (_convertViewToModelMouseEvent))<br />[/vs/editor/browser/view/viewOutgoingEvents.ts#99:25 (emitMouseDown)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/browser/view/viewOutgoingEvents.ts#L99:25 (emitMouseDown))<br />[/vs/editor/browser/view/viewController.ts#311:22 (emitMouseDown)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/browser/view/viewController.ts#L311:22 (emitMouseDown))<br />[/vs/editor/browser/controller/mouseHandler.ts#259:22 (_onMouseDown)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/browser/controller/mouseHandler.ts#L259:22 (_onMouseDown))<br />[/vs/editor/browser/controller/mouseHandler.ts#110:82 (callback)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/browser/controller/mouseHandler.ts#L110:82 (callback))<br />[/vs/editor/browser/editorDom.ts#127:3](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/editor/browser/editorDom.ts#L127:3)<br />

**Comment by alexandrudima** [comment]
Cannot reproduce.
