### ISSUE TITLE
Files are being deleted when using git - Live Share

### ISSUE THREAD

**Issue by DotNetRussell** [Microsoft/vscode#49556]
- VSCode Version: 1.23
- OS Version: Mac OS - High Sierra 10.13.3

Steps to Reproduce:

1. Setup a share session with a Windows 10 machine running visual studio 2017 
(host should be mac and guest should be windows 10 machine)

2. Make some code changes on the windows machine in visual studio and save the file 
(don't close anything)

3. On the mac, while the share session is still active, use git to commit and push your changes

4. Rebase the branch and squash at least one commit 

NOTE: The files are deleted on the Windows Machine by Visual Studio and that in turn deletes them on the Mac

Expected Result: Files shouldn't be deleted

**Comment by joaomoreno** [comment]
Please file this in https://github.com/MicrosoftDocs/live-share/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
