### ISSUE TITLE
Vs Code as Default program remove custom context menus on files

### ISSUE THREAD

**Issue by Uglyfatdude** [Microsoft/vscode#49557]
When I choose VS Code as default program to open SQL files on Windows, my custom context menu elements on files are lost. Afterward, if I choose another program, the context menu items are back.

![image](https://user-images.githubusercontent.com/37719150/39822082-b7eb61aa-5377-11e8-9e1f-129b2cd4c1e2.png)
![image](https://user-images.githubusercontent.com/37719150/39822124-d04fccae-5377-11e8-8aaf-44854cfbcea8.png)
![image](https://user-images.githubusercontent.com/37719150/39822159-ea084a4a-5377-11e8-97e6-225e0af42f20.png)

**Comment by Uglyfatdude** [comment]
Anything?

**Comment by Uglyfatdude** [comment]
We add those custom menu entries by adding a registry entry at "HKEY_LOCAL_MACHINE\\Software\\Classes\\sql_auto_file\\shell\\...".

Here is an example : 
![image](https://user-images.githubusercontent.com/37719150/40666134-048759fa-632d-11e8-9486-58ec9696cdd9.png)

**Comment by joaomoreno** [comment]
Yeah but you're restricting them to the `sql_auto_file` type. VS Code will change the type to something like `VSCode.sql` when associating the file with it. You can add your menu entries to that type in order to still get them.

**Comment by Uglyfatdude** [comment]
I'm not sure to understand to what type of file I should associate the menus. The VSCode.sql type does not seem to exists.

**Comment by Uglyfatdude** [comment]
Here is the entry : 
![image](https://user-images.githubusercontent.com/37719150/40739037-2193419e-6413-11e8-84a2-01936dc67edf.png)

And still nothing on the context menu :
![image](https://user-images.githubusercontent.com/37719150/40739148-60c38806-6413-11e8-8f57-fb16022155eb.png)

**Comment by joaomoreno** [comment]
That's odd. How about under `VSCodeSourceFile`?

**Comment by Uglyfatdude** [comment]
Already tried that, but no more results...

**Comment by joaomoreno** [comment]
What is the value of `HKCR/.sql/(Default)`?

**Comment by Uglyfatdude** [comment]
The value is sql_auto_file

**Comment by joaomoreno** [comment]
I'm out of clues then. On my system, I set up the keys within `sql_auto_file` and they appear in the Explorer menu. :/
