### ISSUE TITLE
API for extending the Explorer pane tree with new subitems

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#49555]
I'd like to start a discussion on whether it would be accepted to extend the VS Code extension API in a way which would allow adding new subtrees to the Explorer pane tree. I am talking about the default tree, not new tree views which extensions can already contribute.

I am an author of an extension which would benefit from this ([VS Code MarkDown To-Do](https://marketplace.visualstudio.com/items?itemName=TomasHubelbauer.vscode-markdown-todo)). Instead of mimicking the tree in a new tree view, I think it should be possible (for multiple extensions at once) to contribute subtrees for explorer tree file items.

Visual Studio (I think, if I remember correctly) does that where it allows to continue expanding for example C# files to namespace, class and method levels. This is another use case that I think would be well served by such API.

**Comment by TomasHubelbauer** [comment]
A year later and I find myself googling the same thing yet again to find my own issue requesting this functionality. Oh well.

Perhaps I am the only one who could make use of it, but seeing how much for example the now integrated outline functionality suffers from not being a part of the same tree, perhaps I am not and had this been available, a better implementation of it could have been provided by extension authors.

It's a shame it was closed without so much as a comment, because I don't feel the merits of this functionality have been given a fair thought.

**Comment by isidorn** [comment]
I could reopen this but we would still not do this in the next year since it is not on our plan and honestly I do not see us adding this at the moment.
