### ISSUE TITLE
Huge graphical glitch

### ISSUE THREAD

**Issue by peneuro** [Microsoft/vscode#49559]
Issue Type: <b>Bug</b>

VSC opens but it's impossible to use it.
I was using it without a single problem, then i closed it and when I reopened it, the GUI was looking [this way
](https://drive.google.com/open?id=1UuZ_65NIZLKD2ZJQtLFW4uBPcCUfuDWb)

I just have no idea of how can it be possible

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G (4 x 2695)|
|Memory (System)|7.46GB (2.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.3
cpptools|ms-|0.17.0
csharp|ms-|1.14.0
vs-keybindings|ms-|0.2.0
java|red|0.24.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.7.0

</details>

**Comment by kylef000** [comment]
Is this persisting?

**Comment by isidorn** [comment]
Can you reproduce this with vscode insiders
https://code.visualstudio.com/insiders/
