### ISSUE TITLE
Ctrl + C not ending local node server

### ISSUE THREAD

**Issue by Psiethyr** [Microsoft/vscode#49554]
Issue Type: <b>Bug</b>

When I run a local server in node in CMD on the latest VSCode update, and attempt to end the process (for example once an edit to the code base has happened and I need to restart the server) the Ctrl+C process to exit out doesn't work.

This is only the case when the server is running, that is to say if I am in a general CMD application Ctrl+C works fine, it is only an issue when the server is running and has only appeared since I updated to the newest VSCode.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Tyriar** [comment]
Tracked in https://github.com/Microsoft/vscode/issues/45693
