### ISSUE TITLE
Support xterm.js' letterSpacing setting

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#49566]
`terminal.integrated.letterSpacing` should support integer (pixel) values

**Comment by Tyriar** [comment]
@rfgamaral you can test it out in tomorrow's Insiders:

<img width="591" alt="screen shot 2018-05-09 at 10 25 42 am" src="https://user-images.githubusercontent.com/2193314/39829451-5c1fb6ae-5373-11e8-98aa-b3e5b1539e2a.png">

**Comment by rfgamaral** [comment]
Great, awesome job, thanks :)

I know it's a bit unrelated, but hard would it be to implement a similar setting on https://github.com/zeit/hyper?

**Comment by Tyriar** [comment]
@rfgamaral should be pretty easy, you would need to expose the xterm setting and then make sure that sizing still works correctly.

**Comment by rfgamaral** [comment]
Thank you :)
