### ISSUE TITLE
Scrolling using a Surface Dial will only ever scroll in one editor group.

### ISSUE THREAD

**Issue by joe-askattest** [microsoft/vscode#49562]
Issue Type: <b>Bug</b>

The Surface Dial seems to only work on one editor group. If you have two or more editor groups, the dial will only scroll in one of them. Even if you switch focus to another editor group, the first group is the only editor group that will scroll. It should follow the focus.

## Steps to reproduce

1. Open a file in the editor.
2. Open a second file in a new editor group. So you have two files open side by side.
3. Focus the first file, and then use a Surface Dial to scroll up and down.
4. Focus the second file, and then use a Surface Dial to scroll up and down.

## Expected Result:

 * When the first file is focused, scrolling with the Surface Dial should scroll the first file up and down.
 * When the second file is focused, scrolling with the Surface Dial should scroll the second file up and down.

## Actual Result:

 * When the first file is focused, scrolling with the Surface Dial scrolls the first file.
 * When the second file is focused, scrolling with the Surface Dial still scrolls the first file.
 * You can only scroll the first file using the dial. It's not respecting the focus.

Happens with `--disable-extensions`.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vetur|oct|0.11.7
rust|rus|0.4.2
language-stylus|sys|1.9.2

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
