### ISSUE TITLE
Title bar and sidebar change color to red when opening an specific git repo

### ISSUE THREAD

**Issue by svictoreq** [Microsoft/vscode#49569]
Issue Type: <b>Bug</b>

I cloned a private repo from my job's GitLab account, and when I open it, the lateral sidebar and the title bar changes it's color to red. But this only happens with that specific repo.

This happens with, and without extensions, as you can see here:
![screenshot 2018-05-09 14 21 15](https://user-images.githubusercontent.com/29575744/39832688-eacd9c3c-5395-11e8-890d-27b3479bb7e6.png)
And also happens on the latest Insiders version:
![screenshot 2018-05-09 14 28 24](https://user-images.githubusercontent.com/29575744/39832887-80a5088a-5396-11e8-90e3-448ddf29d63d.png)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.4.0
city-lights-icon-vsc|Yum|1.0.1
project-manager|ale|0.25.2
polychrome-vscode-themes|cdo|0.0.8
vscode-eslint|dba|1.4.8
font-switcher|eva|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.18
theme-monokai-pro-vscode|mon|1.1.6
debugger-for-chrome|msj|4.4.3
advanced-new-file|pat|1.2.0
LiveServer|rit|3.2.1
sass-indented|rob|1.4.9

(13 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
This actually looks good so it is done by some extension or some extension setting.

**Comment by svictoreq** [comment]
It is not cause by an extension, look:

**Comment by isidorn** [comment]
@svictoreq you might have some extension which modifies CSS,
Can you sahre your settings file?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by isidorn** [comment]
Then it must be some mac custom title setting.
@bpasero would know better -> forwarding to him

**Comment by bpasero** [comment]
@svictoreq does the workspace have a .vscode folder with a settings.json inside that maybe defines some custom theme or colors? Those settings would override your user settings.

**Comment by svictoreq** [comment]
@bpasero Yes!, that was the problem... I'm so sorry! I didn't know you could change that in the settings file...
