### ISSUE TITLE
Ghosted text when switching windows in tmux

### ISSUE THREAD

**Issue by julianlam** [Microsoft/vscode#49565]
Issue Type: <b>Bug</b>

Hi there,

Updated vscode this morning:

```
$ apt-cache policy code-insiders
code-insiders:
  Installed: 1.24.0-1525842823
  Candidate: 1.24.0-1525842823
```

My tmux window now shows ghosted text whenever scrolling is involved (or new lines are entered, etc.), see screenshot:

![bug](https://i.imgur.com/GLSa80O.png)

Thought it was related to updating with vscode running, so I restarted, yet the issue persists.

1. Open vscode
1. Open integrated terminal
1. tmux attach (or tmux to start new session)
1. Create new window

Note ghosting effect when typing or running program that outputs lots of text.

VS Code version: Code - Insiders 1.24.0-insider (84d023798b51a8ad607fd865dd8e16949ee3c398, 2018-05-09T05:11:31.333Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 1445)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.67GB (0.20GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
gitblame|wad|2.4.2

</details>

**Comment by zackkrida** [comment]
Getting this on all terminal commands on OSX with zsh

**Comment by adamduren** [comment]
OSX and zsh as well here if that helps.

**Comment by yume-chan** [comment]
Duplicate of #49438

Please do a search before posting new issues.

**Comment by julianlam** [comment]
I did search, but did not find the appropriate issue.
