### ISSUE TITLE
Integrated terminal gets unresponsive after some usage

### ISSUE THREAD

**Issue by sekogan** [Microsoft/vscode#49560]
Steps to Reproduce:

1. Start VS Code, open the integrated terminal and run a program producing ~80 lines of output. Run that program again 4-5 times.
2. Scroll the integrated terminal's window back and forth.

VS Code gets unresponsive for 5-20 seconds. The task manager shows huge spikes in CPU and memory usage:

![vscode_hang](https://user-images.githubusercontent.com/722508/39824094-300b5dcc-53b7-11e8-8080-ebe1e1ea7e39.png)

Tried to run VS Code with `--ignore-gpu-blacklist` as suggested in #48193 but it didn't help.

ETW traces of the issue: https://1drv.ms/u/s!Avfdd6lsYwdUgrAzPJpI012h9EkEmA

Does this issue occur when all extensions are disabled?: Yes

- VSCode Version:
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows 10 x64 1803
- Graphics: 3840x2160, Intel HD 630 + NVIDIA GTX 1050

**Comment by sekogan** [comment]
Cannot reproduce the issue when VS Code is launched with `--disable-gpu`.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/46954
