### ISSUE TITLE
Fails to update

### ISSUE THREAD

**Issue by Austen-Oberheu** [Microsoft/vscode#49568]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1989055/vscode-inno-updater.log)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Try to update.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by LeaFrock** [comment]
Hey, come on! So what's the problem? I meet the error too, but i find no answers among the links. Now i can't update to version 1.23. My exe file is at the path "D://" but the error message shows that it doesn't find the code.exe in "C://". I guess the problem occurs if the filepath is not the default one while being installed. What a ridiculous and disturbing mistake if i guess right.
