### ISSUE TITLE
Windows 10 "Sets" play havoc with full screen and Zen modes

### ISSUE THREAD

**Issue by alexch** [Microsoft/vscode#49570]
Issue Type: <b>Bug</b>

Using the latest Windows Preview release, the new "Sets" feature (which adds tabs to every app) draws over full-screen and Zen mode, making the top of the VS Code display cluttered and obscured.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17661

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|62.09GB (44.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.17.1
jsrefactor|cms|2.12.3
tslint|eg2|1.0.28
Ruby|reb|0.18.0

</details>

screenshot (Zen mode):

![image](https://user-images.githubusercontent.com/8524/39836189-8c82504a-53a0-11e8-90e9-c78f34c3f205.png)

**Comment by isidorn** [comment]
This has nothing to do with zen mod, but with full screen electron.
Please file this against electron https://github.com/electron/electron
I would bet the same happens with chrome fullscreen

**Comment by alexch** [comment]
May I suggest you leave this bug *open* until the underlying Electron issue is both fixed **and** incorporated into an actual release of VS Code?

**Comment by isidorn** [comment]
Sure, can you provide a link to the electron issue you created?
