### ISSUE TITLE
Persistent webviews don't refresh when changing between then

### ISSUE THREAD

**Issue by benrr101** [Microsoft/vscode#49578]
- VSCode Version: SQL Operations Studio v0.30.1, forked from vscode v1.21
- OS Version: Windows 10 x86_64

Steps to Reproduce:
1. Load an extension that can generate webview tabs, using the following webview options
```
let webviewOptions = <vscode.WebviewOptions> {
    enableScripts: true,
    retainContextWhenHidden: true
};
```
2. Open a webview
3. Open a different webview
4. Switch tabs back and forth

Expected result: the contents of the active tab will change to the selected webview
Actual result: the webview remains the same

Workaround: Selecting a non-webview (eg, a text document) tab changes the content to the non-webview. Selecting a webview tab changes to the desired webview.

**Comment by mjbvz** [comment]
Sorry, we don't officially support webviews in anything in anything older than vscode 1.23

**Comment by benrr101** [comment]
@mjbvz Is this an issue in vscode >=1.23?

**Comment by mjbvz** [comment]
I can't repo it in the current vscode builds. If you can, please provide steps and I can take a look
