### ISSUE TITLE
Opacity in the terminal

### ISSUE THREAD

**Issue by elbertcastaneda** [Microsoft/vscode#49575]
Issue Type: <b>Bug</b>

Open the terminal in the vscode
Execute any command 
You will see how the opacity causes the text to overwrite with the another texts

VS Code version: Code - Insiders 1.24.0-insider (84d023798b51a8ad607fd865dd8e16949ee3c398, 2018-05-09T05:10:45.678Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.17GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_716975|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|1.2.5
xml|Dot|1.9.2
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.4.0
code-settings-sync|Sha|2.9.2
vscode-surround|Swo|1.0.1
pomotimer|afr|0.3.1
project-manager|ale|0.25.2
vscode-database|baj|1.5.1
solargraph|cas|0.17.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.8
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.2.4
vscode-html-css|ecm|0.2.0
nativecolorpicker|elb|0.0.5
json-tools|eri|1.0.2
prettier-vscode|esb|1.3.1
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
php-pack|fel|1.0.1
flow-for-vscode|flo|0.8.1
vscode-yarn|gam|1.6.0
ginfuru-vscode-jekyll-syntax|gin|0.0.5
vscode-jekyll-snippets|gin|0.8.7
icon-fonts|idl|1.10.1
textile|idl|0.1.4
code-guid|jam|1.0.1
vscode-lebab|jer|1.0.2
vscode-styled-components|jpo|0.0.18
docomment|k--|0.1.0
vscode-abap|lar|0.1.0
MagicPython|mag|1.0.12
dotenv|mik|1.0.1
python|ms-|2018.4.0
cpptools|ms-|0.17.0
csharp|ms-|1.14.0
node-debug2|ms-|1.19.0
PowerShell|ms-|1.7.0
team|ms-|1.133.0
debugger-for-chrome|msj|4.4.3
embrace|myc|1.0.0
language-liquid|nei|0.0.3
Ruby|reb|0.18.0
java|red|0.24.0
LiveServer|rit|3.2.1
vscode-icons|rob|7.23.0
vscode-sql-beautify|sen|0.0.4
vscode-table-formatter|shu|1.2.1
react-beautify|tai|0.3.0
theshukran-react-utils|the|1.0.2
python|tht|0.2.3
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.7.0
gitblame|wad|2.4.2

</details>

**Comment by yume-chan** [comment]
Duplicate of #49438
Please do a search before posting new issues.

**Comment by elbertcastaneda** [comment]
Ok
