### ISSUE TITLE
Can't raise editor window without the click also propagating to an element inside of it

### ISSUE THREAD

**Issue by natevw** [Microsoft/vscode#49573]
Issue Type: <b>Bug</b>

After the recent update, I keep ending up with random files open. I think this is happening when I click over from a different app back to an editor window in the background.

I suspect the behavior may have changed after the latest update which I just restarted for.

BEFORE UPDATE: clicking onto a background (i.e. not frontmost/active) VS Code window simply brought it to the front and activated it

AFTER UPDATE: raising an inactive VS Code window also propagates the "click" to whatever happens to be below the mouse. This is not expected and is never my user intent!

Workaround: switching back to VS Code via Cmd-Tab instead of mouse, or being very careful to click on a blank area of the editor.

---

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.52GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_3879859|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0
vscode-code-outline|pat|0.2.0

</details>

**Comment by bpasero** [comment]
Yes we changed that intentionally but you can disable this via `"window.clickThroughInactive": false`

**Comment by natevw** [comment]
Thanks @bpasero! Setting applied and sanity restored :-)
