### ISSUE TITLE
Git repository has too many active changes

### ISSUE THREAD

**Issue by M4l2c3l0** [Microsoft/vscode#49571]
Hi everyone,

I know this question has been asked before already but despite the digging, I was unable to find a straight forward answer as I am really newbie at this.
I've just installed VS Code editor which is so just so good (very much used to Atom) and I'd like to get back to using Git again with which I fiddled with a few months ago, but as I installed the editor, it returned the following message on over 5K items:

`The git repository at '/Users/XXX' has too many active changes, only a subset of Git features will be enabled.`

That literally seems to be every file I ever passed through Git back then somehow. Any way I could get it to forget about those and only focus on the future ones?

Thank you all in advance for your help.

My specs:
VSCode Version - 1.23.0
OS Version - macOS High Sierra 10.13.4

**Comment by 129emma** [comment]
Got same issue here, so anooying

**Comment by joaomoreno** [comment]
You have ran `git init` somewhere up the directory tree, very likely in your home. Open a Command Prompt, `cd` to the folder of a file which causes this and run `git rev-parse --show-toplevel`. This will return the root of your repository. If that should not be a repository, simply delete the `.git` folder within that returned folder.

**Comment by wadgreen** [comment]
the same massage withe me
