### ISSUE TITLE
Allow to get/set the encoding and charset

### ISSUE THREAD

**Issue by iHuahua** [Microsoft/vscode#4958]
Such as [`IEncodingSupport::setEncoding`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorStatus.ts#L910) , i want to code an extension for detect file's encoding. now detect encoding successed, but i don't known how to change encoding by API, could u help me?

**Comment by bpasero** [comment]
We currently do not have API to set the encoding for files from extensions.

**Comment by iHuahua** [comment]
@bpasero  Think for your reply. Would you have plan to add API in future? or support encode detect just like ATOM?
https://github.com/Microsoft/vscode/issues/2123
Than my native language is Chinese, and vscode does not support encode detect without DOM header. so, I have to code an extension for encode detect, if both of them could not be supported, it will be a pity. your native language is English, perhaps you can not  feel the pain about the garbled.
If I have not reply in time, please email to me, `ihuahua#live.com` , # => @

**Comment by bpasero** [comment]
This issue is currently assigned to the backlog. Every sprint we pick items from the backlog to plan for the current iteration. Please see https://github.com/Microsoft/vscode/wiki/Issue-Tracking#planning

**Comment by iHuahua** [comment]
@bpasero yeah, thanks very very much, I love vscode.

**Comment by jrieken** [comment]
actually also a duplicate. first issue was #824

**Comment by iHuahua** [comment]
my god. it was been closed. i think the APIs has been provided in vscode 1.2. A half of my extension has been finished. T_T...
