### ISSUE TITLE
希望css能够以inline模式格式化

### ISSUE THREAD

**Issue by tsdd** [Microsoft/vscode#49586]
- VSCode Version: 1.23.0
- OS Version: windows 7

Visual Studio格式化css时，能够选择展开、半展开、行内，希望vs code也加入这个功能。

**Comment by AnClark** [comment]
Please let me translate it into English:

When using Visual Studio to format CSS, we can choose Expand/Semi-Expand/Inline mode. Hope that VS Code can also implement this feature.

**Comment by gylidian** [comment]
我觉得这个功能非常非常非常方便。

**Comment by aeschli** [comment]
Please check out the Marketplave for css formatters and file your suggestion against your favorite formatter.

The request to add a built-in css formatter to VSCode is #19166, but we have no plans to add one as we don't have the resources to implement and maintain one.
