### ISSUE TITLE
new indent guide color is not working

### ISSUE THREAD

**Issue by adrianmak** [Microsoft/vscode#49584]
I changed to other color but the color of guide didnt change

"workbench.colorCustomizations": {
    "editorIndentGuide.activeBackground": "#ffff00"
}

**Comment by alexandrudima** [comment]
This works fine for me, I changed the color to red to have a better contrast:

![image](https://user-images.githubusercontent.com/5047891/39912919-75907716-5500-11e8-98b1-34fe20426e72.png)
