### ISSUE TITLE
firstLine parameter in extension contribution

### ISSUE THREAD

**Issue by Serhioromano** [Microsoft/vscode#49592]
Reading here https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages

> the first line inside the file (firstLine below)

This is a parameter how VS Code can detect file type. 

1. This is a string. Can we make it an array|string? Because my file may start with `PROGRAM ` or `FUNCTION ` or `FUNCTION_BLOCK ` or few others. 
2. Can we introduce `skipComments` parameters for first line detection? For instance my file starts

   ```
   (* this is file descritption
   multiple line *)
   PROGRAM PLC_PRG
   ...
   ```

   Although file starts with comment with is usual practice but actually starts with `PROGRAM `. We may have comments in front or not. My proposal to introduce  `skipComments` (true|false) and use `comments.blockComment` and `comments.lineComment` parameters to detect comment style. Or skip comments in front of the file automatically without any additional parameter, when detecting file type.

**Comment by alexandrudima** [comment]
Re 1. You can use a regex e.g. https://github.com/Microsoft/vscode/blob/844c7f1c94c7cadb25d46fb97f0d3d4c4b66b3cc/extensions/shellscript/package.json#L17
