### ISSUE TITLE
Generating equivalent C++ header from debugProtocol.json

### ISSUE THREAD

**Issue by tarunbansal11** [Microsoft/vscode#49596]
Hi @isidorn ,

I am writing a DA in C++. I need to use DAP which is available as debugProtocol.json. I can see that debugProtocol.d.ts was auto-generated from debugProtocol.json. Is there any way to generate C++ equivalent classes from debugProtocol.json

Thanks.

**Comment by isidorn** [comment]
As far as I know there is no way. However forwarding to @weinand who owns the debug protocol and who did the auto-generation

**Comment by weinand** [comment]
Sure there is a way: write a generator program (similar to generator.ts) that converts the json-schema into C++ classes.

**Comment by tarunbansal11** [comment]
Thanks @weinand  and @isidorn  for your suggestions. I will take help of generator.ts to write required generator.
