### ISSUE TITLE
Have a "Close All" button as editor action in the toolbar

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#49591]
This may be the best extension that no one knows about...

https://marketplace.visualstudio.com/items?itemName=benjpas.close-all

but, i'm tired of reinstalling it!

Suggestion: Include this functionality in the core of VS Code.

**Comment by Emeryao** [comment]
I think the `Close All Editors` works fine for me 😝 

![image](https://user-images.githubusercontent.com/3591899/39851566-1ed28b1e-544a-11e8-9469-afb96f04c759.png)

**Comment by usernamehw** [comment]
Possible duplicate of #9285

**Comment by bpasero** [comment]
I am now showing this command when you press the `Alt` key:

![before](https://user-images.githubusercontent.com/900690/40872768-580f1c78-6654-11e8-9879-16201d4daf62.gif)
