### ISSUE TITLE
Powershell integrated console command input errors (System.ArgumentOutOfRangeException)

### ISSUE THREAD

**Issue by msftrncs** [Microsoft/vscode#49594]
Issue Type: <b>Bug</b>

Fill the PowerShell integrated console buffer (DIR \WINDOWS\SYSTEM32 for instance) and then proceed to type a command longer than the console window so that it has to scroll, and an error will occur "System.ArgumentOutOfRangeException": The value must be greater than or equal to zero and less than the console's buffer
size in that dimension.
Parameter name: top
Actual value was 3000.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
I found this while trying to use the 'F8' run selection, as it would trigger this.  This happens right away in a new instance of VSCode with integrated PowerShell console.  It also happens when trying to recall previous commands that are longer than the console window is wide.  This is made worse if the current path is pretty long, making the command prompt take up most of the line.  Running "clear" allows the command to finally be entered without receiving the error.  
There are also some text display overwrite issues when recalling commands longer than the window is wide, specially if the number of lines of the recalled command is more than the number of lines visible in the console window.  

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       U 430  @ 1.20GHz (4 x 1197)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.68GB (1.54GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.1
PowerShell|ms-|1.7.0

</details>

**Comment by Tyriar** [comment]
This is either an issue with the powershell extension (https://github.com/PowerShell/vscode-powershell) or winpty (see https://github.com/Microsoft/vscode/issues/45693)
