### ISSUE TITLE
Find widget only highlights the first 19999/20000 matches

### ISSUE THREAD

**Issue by zwb1988** [microsoft/vscode#496]
Using the search with regular expression in the VS Code 0.10.1, it only highlights the matched items with couple hundreds of lines from the top and skips the rest of the document.

This can be done by creating an empty document and fill it up with thousands lines of text and perform a regex search.

**Comment by aasierra** [comment]
@zwb1988 I have proposed a fix here https://github.com/Microsoft/vscode/pull/501

**Comment by zwb1988** [comment]
@aasierra Cool. I have found out that normal search has exactly the same issue. I see you changed the constant LIMIT_FIND_COUNT, the method findMatches will apply the same rule to the normal search (if I am not mistaken). 
Don't know how will this change affect the searching performance in a huge file thought (like a file size in MB or GB).

**Comment by aasierra** [comment]
@zwb1988 Yep regarding huge files at the very least I changed it to this to hopefully get things talked about. Also increasing for all search types was done intentionally to increase search limit for everything not just Regex as I am sure other users will be confused why normal searches do not match everything as well.

**Comment by aasierra** [comment]
@zwb1988 Although, regarding large files, the way lines are stored I believe will allow for a large amount to not have issues but when it gets large it should act the same as other text editors might.

**Comment by alexandrudima** [comment]
I can't accept the PR for the time being. The find results (from `findMatches`) are converted to decorations. Decorations are copied and transformed in the view model (to take line wrapping into account).

The code around decorations is not prepared to deal with decorations count in the 1M range for sure, which is something that can happen when opening a ~20MB file and searching for "a" or something...

**Comment by alexandrudima** [comment]
Starting with 587854a5bcae72950da0e9412ab773933a350e6b, all find widget operations (find next, find prev, replace, replace all) now function outside the 1k decorations limit.

**Comment by alexandrudima** [comment]
PR #36410 reimplements decorations as an interval tree and brings in a number of key optimizations around decorations. It raises the find limit from 1k to 20k.

**Comment by dijonkitchen** [comment]
Sounds like the issue can close!

**Comment by Gektorian** [comment]
I have near 101237 items in the XML file and I can't count them because of this 19999+ limit. Is there a way to provide default limit that we can change in workspace preferences?

**Comment by SergeiNarozhnyi** [comment]
Upvote. Limits should be defined as per the workspace, if required

**Comment by ToMakeSense** [comment]
This issue should be closed, after PR #126762 merged.

**Comment by amunger** [comment]
it looks like this was implemented but the setting is not working for me https://github.com/microsoft/vscode/issues/169017
