### ISSUE TITLE
Refresh file without reloading the whole window

### ISSUE THREAD

**Issue by NN---** [Microsoft/vscode#49603]
VSCode has 'Reload window' command which does more than just refreshing a single file.
I would like to have 'Refresh file' command which just reloads current file.

**Comment by NN---** [comment]
I don’t talk Abo extensions.
I want a button to read the file once again and show update file without reloading whole window.

**Comment by psychelzh** [comment]
Is this button what you need?

![image](https://user-images.githubusercontent.com/13306020/39860873-7bbde95a-5471-11e8-901f-5bccb889cbde.png)

**Comment by isidorn** [comment]
@psychelzh that button should do the trick for refreshing the explroer
@NN--- each file should react automatically to file events and you should not manually refersh it. If that is not the case please file a new issue with reproducable steps on how you got into that state

**Comment by NN---** [comment]
The file is not updated automatically for me.
I’ll create a new issue.
Ok
