### ISSUE TITLE
Search in a project tree just like in intellij idea [feature]

### ISSUE THREAD

**Issue by v1ar31** [Microsoft/vscode#49600]
![idea-search](https://user-images.githubusercontent.com/5954269/39856987-868cbf64-543a-11e8-84df-1df5f30c66a0.gif)

This is a good solution for a quick search in node_modules for example.

**Comment by ivanvoznyakovsky** [comment]
duplicate of #10026

**Comment by roblourens** [comment]
Thanks @ivanvoznyakovsky
