### ISSUE TITLE
[Feature Request] File Explorer context menu > Open folder

### ISSUE THREAD

**Issue by andreujuanc** [Microsoft/vscode#49609]
Hello,

Maybe there is an extension to do this, but I think it should be native. I found that time to time I open parent folders of solutions or projects and then I just want to open a nested folder from the file explorer to either a new instance of vscode, or to the current one. 

Yes, I do use vscode as file explorer. It's just amasing to be able to see file contents and browse around.

So, my requests/ideas: Open any folder, lets say `C:\Users\bgates\Source\Repos\` So you can see all repos you have cloned there, and then rightclick on file explorer over a selected folder (which are git projects) should show:
1. Open folder
2. Open folder in new Instance

This is just a small scenario I have, and might be dumb, but it happens more often than not.

BTW, workspaces do not apply to this solution.

Maybe It'd be a good time to learn to make an extension? C:

Thanks

**Comment by isidorn** [comment]
Shoudl be easy do be done via extension -> have fun :)

**Comment by andreujuanc** [comment]
I understand it could be done via extension. I might even give it a try.

But it's so basic and useful that i thought it could be a nice feature.

**Comment by isidorn** [comment]
@andreujuanc thanks but we try to keep vscode minimalistic
