### ISSUE TITLE
Don't include the active file in the suggested results

### ISSUE THREAD

**Issue by KevinColemanInc** [Microsoft/vscode#49607]
When I am searching for a file, it always prefers recently searched files at the top of the results.  This is great, until I want to open a different file with a similar name.

If the file is already open, I am probably not looking for it in the search.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/2381771/39863604-5778fa62-5471-11e8-9e18-61e5ccb3777f.png">

**Comment by roblourens** [comment]
Dupe of https://github.com/Microsoft/vscode/issues/30770, also see https://github.com/Microsoft/vscode/issues/27317
