### ISSUE TITLE
VS Code characters fades

### ISSUE THREAD

**Issue by framontb** [Microsoft/vscode#49601]
After upgrading Visual Studio Code to version 1.23.0 (Windows 10 Pro; on Toshiva TECRA Z40-A), sometimes characters fades. I discard a graphical issue because the only window which fades is VS Code window, but not shure if it is a bug. You can see an example in the following image (look at main menu, file name or url variable inside the editor):
[https://stackoverflow.com/questions/50252795/vs-code-characters-fades](url)
![vscode-fades_example](https://user-images.githubusercontent.com/13080709/39858080-c4e83afe-5435-11e8-9964-9a1fa65c5b8b.jpg)

- VSCode Version: 1.23.0
- OS Version: Microsoft Windows 10 Pro

Steps to Reproduce:

1. Open the VS Code normally.
2. Work normally with VS Code and other apps.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Does this still happen in 1.26?

**Comment by framontb** [comment]
No, it isn't. It seems that the issue was solved.
