### ISSUE TITLE
Copy debug variables

### ISSUE THREAD

**Issue by mfrsousa** [Microsoft/vscode#49605]
Issue Type: <b>Bug</b>

On Debug Variables when debugging php file all right mouse button click options are disabled and cannot copy/set any values or add to  watches.

![image](https://user-images.githubusercontent.com/1540796/39862973-296f317e-543d-11e8-9922-c1ae674d7e8b.png)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.28GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
path-intellisense|chr|1.4.2
prettier-vscode|esb|1.3.1
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
php-cs-fixer|jun|0.1.72
php-namespace-resolver|Meh|1.0.8
vscode-scss|mrm|0.6.2
vscode-todo-highlight|way|0.5.12
markdown-all-in-one|yzh|1.3.0

</details>

**Comment by isidorn** [comment]
That is because the php extensoin does not provide [`evaluateName`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1355) for variables.
Please file this issue against their repo and mention what I just commented. Thanks

**Comment by felixfbecker** [comment]
@isidorn I have a feeling this used to work - is this a new requirement?

**Comment by isidorn** [comment]
@felixfbecker yup. This was working in limited cases thus we choose to be more precise and only enable those actions for the `evaluateName` when they are 100% precise. I think we mentioned that in some release notes. Thanks
