### ISSUE TITLE
Very high RAM usage on Win10

### ISSUE THREAD

**Issue by matekuna92** [Microsoft/vscode#49618]
Issue Type: <b>Bug</b>

Since I've installed VScode on my work PC, it has very high RAM usage. Since I need to use a lot of browser tabs, often the IDE, or the browser freezes, or crashes totally. 

Ram usage is between 3-5 GB (!!) almost whole day.

I tried to disable extensions, or using only one workfile in VScode, but it's the same. 

The usage sometimes goes down to normal level, but 99% of the time I rather use other IDE, because I cant open anything else beside VSCode. 

App version: 1.23.0 , x64, Win 10

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
save-typing|akh|0.1.0
html-class-suggestions|And|1.0.7
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
jquery-snippets|Hri|1.0.0
font-awesome-codes-css|med|0.1.1
font-awesome-codes-html|med|0.0.7
css-grid-snippets|oha|0.0.5
vscode-css-peek|pra|2.1.0
html5-boilerplate|sid|1.0.1
bootstrap4-vscode|the|4.1.1
highlight-matching-tag|vin|0.4.4
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.6.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by matekuna92** [comment]
Dear bpasero! 

Thank you very much for the fast response. 

I tried disable almost all of them, seems like that few remaining addon caused some very high usage. 

Disabling CSS Grid snippets and CSS peek extensions seems solving the problem for now, I will continue monitoring the app. 

Thanks for the help !
