### ISSUE TITLE
CTRL+Shift+P (and others) not working

### ISSUE THREAD

**Issue by Panossa** [Microsoft/vscode#49614]
- VSCode Version: VS Code Community Edition V.15.7.1
- OS Version: Win 7

Steps to Reproduce:

1. Install Visual Studio via Unity installer.
2. Press CTRL+Shift+P.

Does this issue occur when all extensions are disabled?: Can't test, "code" is not a command.

**Comment by Panossa** [comment]
Additional info: I can't even open File->Preferences as the menu point is missing. Found out /AppData/Roaming/Code/... has the preference json file but I don't have a "Code" folder in AppData/Roaming.

**Comment by isidorn** [comment]
This is for a visual studio code repository, not visaul studio.

If your issue is for vscode let us know if you can reproduce with vscode insiders and we can reopen https://code.visualstudio.com/insiders/
