### ISSUE TITLE
Failed to install VS Code update

### ISSUE THREAD

**Issue by danielcai1987** [Microsoft/vscode#49611]
- VSCode Version: 1.22.2
- OS Version:  Windows 7 Professional SP1

Steps to Reproduce:

**vscode-inno-updater.log**

May 10 18:37:26.891 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
May 10 18:37:26.900 INFO Checking for running Code.exe processes... (attempt 1)
May 10 18:37:26.901 INFO Code.exe is running, wait a bit
May 10 18:37:27.394 INFO Checking for running Code.exe processes... (attempt 2)
May 10 18:37:27.442 INFO Code.exe is running, wait a bit
May 10 18:37:27.938 INFO Checking for running Code.exe processes... (attempt 3)
May 10 18:37:27.944 INFO Code.exe is running, wait a bit
May 10 18:37:28.444 INFO Checking for running Code.exe processes... (attempt 4)
May 10 18:37:28.449 INFO Code.exe is running, wait a bit
May 10 18:37:28.949 INFO Checking for running Code.exe processes... (attempt 5)
May 10 18:37:28.955 INFO Code.exe is running, wait a bit
May 10 18:37:29.455 INFO Checking for running Code.exe processes... (attempt 6)
May 10 18:37:29.460 INFO Code.exe is running, wait a bit
May 10 18:37:29.960 INFO Checking for running Code.exe processes... (attempt 7)
May 10 18:37:29.965 INFO Code.exe is running, wait a bit
May 10 18:37:30.465 INFO Checking for running Code.exe processes... (attempt 8)
May 10 18:37:30.469 INFO Code.exe is running, wait a bit
May 10 18:37:30.973 INFO Checking for running Code.exe processes... (attempt 9)
May 10 18:37:30.988 INFO Code.exe is running, wait a bit
May 10 18:37:31.488 INFO Checking for running Code.exe processes... (attempt 10)
May 10 18:37:31.493 INFO Code.exe is running, wait a bit
May 10 18:37:31.993 INFO Checking for running Code.exe processes... (attempt 11)
May 10 18:37:31.997 INFO Code.exe is running, wait a bit
May 10 18:37:32.497 INFO Checking for running Code.exe processes... (attempt 12)
May 10 18:37:32.502 INFO Code.exe is running, wait a bit
May 10 18:37:33.002 INFO Checking for running Code.exe processes... (attempt 13)
May 10 18:37:33.006 INFO Code.exe is running, wait a bit
May 10 18:37:33.506 INFO Checking for running Code.exe processes... (attempt 14)
May 10 18:37:33.510 INFO Code.exe is running, wait a bit
May 10 18:37:34.010 INFO Checking for running Code.exe processes... (attempt 15)
May 10 18:37:34.015 INFO Code.exe is running, wait a bit
May 10 18:37:34.521 INFO Checking for running Code.exe processes... (attempt 16)
May 10 18:37:34.521 INFO Code.exe is running, wait a bit
May 10 18:37:35.019 INFO Checking for running Code.exe processes... (attempt 17)
May 10 18:37:35.023 INFO Code.exe is running, wait a bit
May 10 18:37:35.523 INFO Checking for running Code.exe processes... (attempt 18)
May 10 18:37:35.528 INFO Code.exe is running, wait a bit
May 10 18:37:36.028 INFO Checking for running Code.exe processes... (attempt 19)
May 10 18:37:36.034 INFO Code.exe is running, wait a bit
May 10 18:37:36.534 INFO Checking for running Code.exe processes... (attempt 20)
May 10 18:37:36.539 INFO Code.exe is running, wait a bit
May 10 18:37:37.039 INFO Checking for running Code.exe processes... (attempt 21)
May 10 18:37:37.044 INFO Code.exe is running, wait a bit
May 10 18:37:37.544 INFO Checking for running Code.exe processes... (attempt 22)
May 10 18:37:37.550 INFO Code.exe is running, wait a bit
May 10 18:37:38.050 INFO Checking for running Code.exe processes... (attempt 23)
May 10 18:37:38.054 INFO Code.exe is running, wait a bit
May 10 18:37:38.554 INFO Checking for running Code.exe processes... (attempt 24)
May 10 18:37:38.559 INFO Code.exe is running, wait a bit
May 10 18:37:39.059 INFO Checking for running Code.exe processes... (attempt 25)
May 10 18:37:39.063 INFO Code.exe is running, wait a bit
May 10 18:37:39.563 INFO Checking for running Code.exe processes... (attempt 26)
May 10 18:37:39.568 INFO Code.exe is running, wait a bit
May 10 18:37:40.068 INFO Checking for running Code.exe processes... (attempt 27)
May 10 18:37:40.078 INFO Code.exe is running, wait a bit
May 10 18:37:40.578 INFO Checking for running Code.exe processes... (attempt 28)
May 10 18:37:40.583 INFO Code.exe is running, wait a bit
May 10 18:37:41.083 INFO Checking for running Code.exe processes... (attempt 29)
May 10 18:37:41.088 INFO Code.exe is running, wait a bit
May 10 18:37:41.588 INFO Checking for running Code.exe processes... (attempt 30)
May 10 18:37:41.593 INFO Code.exe is running, wait a bit
May 10 18:37:42.093 INFO Checking for running Code.exe processes... (attempt 31)
May 10 18:37:42.098 INFO Code.exe is running, wait a bit
May 10 18:37:42.598 INFO Checking for running Code.exe processes... (attempt 32)
May 10 18:37:42.614 INFO Code.exe is running, wait a bit
May 10 18:37:43.114 INFO Checking for running Code.exe processes... (attempt 33)
May 10 18:37:43.119 INFO Code.exe is running, wait a bit
May 10 18:37:43.619 INFO Checking for running Code.exe processes... (attempt 34)
May 10 18:37:43.624 INFO Code.exe is running, wait a bit
May 10 18:37:44.132 INFO Checking for running Code.exe processes... (attempt 35)
May 10 18:37:44.139 INFO Code.exe is running, wait a bit
May 10 18:37:44.639 INFO Checking for running Code.exe processes... (attempt 36)
May 10 18:37:44.643 INFO Code.exe is running, wait a bit
May 10 18:37:45.143 INFO Checking for running Code.exe processes... (attempt 37)
May 10 18:37:45.147 INFO Code.exe is running, wait a bit
May 10 18:37:45.647 INFO Checking for running Code.exe processes... (attempt 38)
May 10 18:37:45.653 INFO Code.exe is running, wait a bit
May 10 18:37:46.153 INFO Checking for running Code.exe processes... (attempt 39)
May 10 18:37:46.160 INFO Code.exe is running, wait a bit
May 10 18:37:46.660 INFO Checking for running Code.exe processes... (attempt 40)
May 10 18:37:46.665 INFO Code.exe is running, wait a bit
May 10 18:37:47.165 INFO Checking for running Code.exe processes... (attempt 41)
May 10 18:37:47.170 INFO Code.exe is running, wait a bit
May 10 18:37:47.670 INFO Checking for running Code.exe processes... (attempt 42)
May 10 18:37:47.675 INFO Code.exe is running, wait a bit
May 10 18:37:48.175 INFO Checking for running Code.exe processes... (attempt 43)
May 10 18:37:48.182 INFO Code.exe is running, wait a bit
May 10 18:37:48.682 INFO Checking for running Code.exe processes... (attempt 44)
May 10 18:37:48.687 INFO Code.exe is running, wait a bit
May 10 18:37:49.196 INFO Checking for running Code.exe processes... (attempt 45)
May 10 18:37:49.199 INFO Code.exe is running, wait a bit
May 10 18:37:49.699 INFO Checking for running Code.exe processes... (attempt 46)
May 10 18:37:49.703 INFO Code.exe is running, wait a bit
May 10 18:37:50.203 INFO Checking for running Code.exe processes... (attempt 47)
May 10 18:37:50.209 INFO Code.exe is running, wait a bit
May 10 18:37:50.709 INFO Checking for running Code.exe processes... (attempt 48)
May 10 18:37:50.714 INFO Code.exe is running, wait a bit
May 10 18:37:51.214 INFO Checking for running Code.exe processes... (attempt 49)
May 10 18:37:51.218 INFO Code.exe is running, wait a bit
May 10 18:37:51.718 INFO Checking for running Code.exe processes... (attempt 50)
May 10 18:37:51.722 INFO Code.exe is running, wait a bit
May 10 18:37:52.222 INFO Checking for running Code.exe processes... (attempt 51)
May 10 18:37:52.227 INFO Code.exe is running, wait a bit
May 10 18:37:52.728 INFO Checking for running Code.exe processes... (attempt 52)
May 10 18:37:52.732 INFO Code.exe is running, wait a bit
May 10 18:37:53.232 INFO Checking for running Code.exe processes... (attempt 53)
May 10 18:37:53.236 INFO Code.exe is running, wait a bit
May 10 18:37:53.741 INFO Checking for running Code.exe processes... (attempt 54)
May 10 18:37:53.743 INFO Code.exe is running, wait a bit
May 10 18:37:54.243 INFO Checking for running Code.exe processes... (attempt 55)
May 10 18:37:54.248 INFO Code.exe is running, wait a bit
May 10 18:37:54.748 INFO Checking for running Code.exe processes... (attempt 56)
May 10 18:37:54.752 INFO Code.exe is running, wait a bit
May 10 18:37:55.253 INFO Checking for running Code.exe processes... (attempt 57)
May 10 18:37:55.257 INFO Code.exe is running, wait a bit
May 10 18:37:55.758 INFO Checking for running Code.exe processes... (attempt 58)
May 10 18:37:55.763 INFO Code.exe is running, wait a bit
May 10 18:37:56.267 INFO Checking for running Code.exe processes... (attempt 59)
May 10 18:37:56.273 INFO Code.exe is running, wait a bit
May 10 18:37:56.773 INFO Checking for running Code.exe processes... (attempt 60)
May 10 18:37:56.779 INFO Gave up waiting for Code.exe to exit
May 10 18:37:56.779 INFO Checking for possible conflicting running processes... (attempt 1)
May 10 18:37:56.784 INFO Kill process if found: 12396, Code.exe
May 10 18:37:56.785 INFO Kill process if found: 17712, Code.exe
May 10 18:37:56.785 INFO Kill process if found: 11984, Code.exe
May 10 18:37:56.785 INFO Kill process if found: 17500, Code.exe
May 10 18:37:56.786 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:56.786 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:56.786 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:56.786 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:56.835 INFO Checking for possible conflicting running processes... (attempt 2)
May 10 18:37:56.841 INFO Kill process if found: 12396, Code.exe
May 10 18:37:56.841 INFO Kill process if found: 17712, Code.exe
May 10 18:37:56.841 INFO Kill process if found: 11984, Code.exe
May 10 18:37:56.841 INFO Kill process if found: 17500, Code.exe
May 10 18:37:56.842 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:56.842 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:56.842 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:56.842 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:57.048 INFO Checking for possible conflicting running processes... (attempt 3)
May 10 18:37:57.055 INFO Kill process if found: 12396, Code.exe
May 10 18:37:57.056 INFO Kill process if found: 17712, Code.exe
May 10 18:37:57.056 INFO Kill process if found: 11984, Code.exe
May 10 18:37:57.057 INFO Kill process if found: 17500, Code.exe
May 10 18:37:57.057 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:57.057 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:57.058 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:57.058 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:57.506 INFO Checking for possible conflicting running processes... (attempt 4)
May 10 18:37:57.510 INFO Kill process if found: 12396, Code.exe
May 10 18:37:57.511 INFO Kill process if found: 17712, Code.exe
May 10 18:37:57.511 INFO Kill process if found: 11984, Code.exe
May 10 18:37:57.511 INFO Kill process if found: 17500, Code.exe
May 10 18:37:57.512 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:57.512 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:57.512 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:57.512 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:58.310 INFO Checking for possible conflicting running processes... (attempt 5)
May 10 18:37:58.315 INFO Kill process if found: 12396, Code.exe
May 10 18:37:58.316 INFO Kill process if found: 17712, Code.exe
May 10 18:37:58.316 INFO Kill process if found: 11984, Code.exe
May 10 18:37:58.316 INFO Kill process if found: 17500, Code.exe
May 10 18:37:58.316 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:58.317 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:58.317 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:58.317 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:59.565 INFO Checking for possible conflicting running processes... (attempt 6)
May 10 18:37:59.569 INFO Kill process if found: 12396, Code.exe
May 10 18:37:59.569 INFO Kill process if found: 17712, Code.exe
May 10 18:37:59.570 INFO Kill process if found: 11984, Code.exe
May 10 18:37:59.570 INFO Kill process if found: 17500, Code.exe
May 10 18:37:59.570 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:59.571 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:59.571 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:37:59.571 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:01.371 INFO Checking for possible conflicting running processes... (attempt 7)
May 10 18:38:01.376 INFO Kill process if found: 12396, Code.exe
May 10 18:38:01.376 INFO Kill process if found: 17712, Code.exe
May 10 18:38:01.377 INFO Kill process if found: 11984, Code.exe
May 10 18:38:01.377 INFO Kill process if found: 17500, Code.exe
May 10 18:38:01.378 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:01.378 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:01.378 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:01.379 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:03.827 INFO Checking for possible conflicting running processes... (attempt 8)
May 10 18:38:03.831 INFO Kill process if found: 12396, Code.exe
May 10 18:38:03.831 INFO Kill process if found: 17712, Code.exe
May 10 18:38:03.831 INFO Kill process if found: 11984, Code.exe
May 10 18:38:03.832 INFO Kill process if found: 17500, Code.exe
May 10 18:38:03.832 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:03.832 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:03.833 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:03.833 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:07.031 INFO Checking for possible conflicting running processes... (attempt 9)
May 10 18:38:07.036 INFO Kill process if found: 12396, Code.exe
May 10 18:38:07.036 INFO Kill process if found: 17712, Code.exe
May 10 18:38:07.036 INFO Kill process if found: 11984, Code.exe
May 10 18:38:07.037 INFO Kill process if found: 17500, Code.exe
May 10 18:38:07.037 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:07.037 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:07.038 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:07.038 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:11.086 INFO Checking for possible conflicting running processes... (attempt 10)
May 10 18:38:11.090 INFO Kill process if found: 12396, Code.exe
May 10 18:38:11.090 INFO Kill process if found: 17712, Code.exe
May 10 18:38:11.091 INFO Kill process if found: 11984, Code.exe
May 10 18:38:11.091 INFO Kill process if found: 17500, Code.exe
May 10 18:38:11.091 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:11.092 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:11.092 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:11.092 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:16.090 INFO Checking for possible conflicting running processes... (attempt 11)
May 10 18:38:16.094 INFO Kill process if found: 12396, Code.exe
May 10 18:38:16.094 INFO Kill process if found: 17712, Code.exe
May 10 18:38:16.094 INFO Kill process if found: 11984, Code.exe
May 10 18:38:16.095 INFO Kill process if found: 17500, Code.exe
May 10 18:38:16.095 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:16.095 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:16.095 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:16.096 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

May 10 18:38:16.096 ERRO Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Does this still happen after restarting your system?
