### ISSUE TITLE
Search colors name (color name autocomplete)

### ISSUE THREAD

**Issue by viniciuscenci** [Microsoft/vscode#49619]
- VSCode Version: 1.23.0
- OS Version: High Sierra

Steps to Reproduce:

1.  Create CSS File
2. Type the code below

`body{
    background: blue
}`

**ISSUE**: I want to see **all the "blue" colors** (e.g "RoyalBlue", "LightBlue", etc...), but I only get the ones that start with blue...
![screen shot 2018-05-10 at 10 40 44 am](https://user-images.githubusercontent.com/2103416/39872519-a0df9bda-543e-11e8-8b1f-a02ff5b6e00b.png)

Would be nice to type "red", and see a list of colors from that group, specially for prototyping. There's a nice view of the grouping at this [Wikipedia page](https://en.wikipedia.org/wiki/Web_colors#X11_color_names).

**Comment by aeschli** [comment]
The suggest widget filters proposals like `cornflowerblue`

**Comment by aeschli** [comment]
I think the current way of filtering is reasonable.

**Comment by jrieken** [comment]
@aeschli how about `CornflowerBlue` vs `cornflowerblue `?

**Comment by aeschli** [comment]
CSS identifiers are case-insensitive, so both `CornflowerBlue` and `cornflowerblue` are both valid.
But in CSS using all-lowercase is the norm for colors and other values. See for example https://www.w3.org/TR/css-color-3/#svg-color

**Comment by viniciuscenci** [comment]
I think it's more a usability thing. What is the point of filtering by name? Not to show too many results? The developer/designer is obligated to know all the colors names? Thats the point... **The filtering could be keeped as is, but at least showing the complete list of colors after pressing the spacebar**... :) something like this:

![1](https://user-images.githubusercontent.com/2103416/40000405-1817f528-5762-11e8-8d2a-1fcb9c45a2bb.jpg)

or:

![2](https://user-images.githubusercontent.com/2103416/40000939-83cc1546-5763-11e8-8e40-8d50f731ce9a.jpg)
