### ISSUE TITLE
Feature Request Advanced Search

### ISSUE THREAD

**Issue by kyoukhana** [Microsoft/vscode#49616]
I really love Visual Studio code.  The only issue is that I wish we had a advanced search like in PHP storm.  I am sure it's coming.  
<img width="1149" alt="advanced-search" src="https://user-images.githubusercontent.com/756849/39870550-cdca37d6-542f-11e8-8e0c-d6b5eda93e2d.png">

**Comment by roblourens** [comment]
There are a bunch of feature requests that cover phpstorm's features, such as search in a tree view: https://github.com/Microsoft/vscode/issues/20224
