### ISSUE TITLE
Question: How to display a code thumbnail scrollbar?

### ISSUE THREAD

**Issue by s-a** [Microsoft/vscode#4961]
Does this feature already exist?

**Comment by alexandrudima** [comment]
@s-a Do you mean something like a minimap?

**Comment by s-a** [comment]
Yes . Like sublime Text. I think in MSVS it is called scroll bar minimap.
Am 05.04.2016 17:58 schrieb "Alexandru Dima" <notifications@github.com>:

**Comment by s-a** [comment]
![image](https://cloud.githubusercontent.com/assets/1270662/14291918/fae8351c-fb65-11e5-9672-8094694c6e24.png)

**Comment by alexandrudima** [comment]
Thank you, let's track this feature request in #4865
