### ISSUE TITLE
Explorer view causes switching tabs

### ISSUE THREAD

**Issue by bam** [Microsoft/vscode#49615]
- VSCode Version: 1.23.0
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Open "compare" tab (compare any two files)
2. Press Cmd+Shift+E (Explorer view)
3. VS Code opens preview of the file selected in explorer view (automatically switches from compare tab)

**Comment by bpasero** [comment]
@isidorn I like our current behaviour of reselecting whatever was last active in the explorer when clicking back to it. The intention was that you might have been doing some diff-work in the SCM viewlet and when you are done you click on the explorer to open your last active file. I actually rely on this behaviour quite often.

**Comment by isidorn** [comment]
@bpasero I think we already had this discussion. Makes sense, I probably also rely on this. Thanks for claryfing.
@bam sorry will have to close as desigend as most users open explorer to get rid of the diff view.
