### ISSUE TITLE
Feature Request: Filter Errors/Warning/Info from status bar

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#49625]
It would be nice if clicking the errors/warnings/infos buttons on the status bar filtered the problems window accordingly rather than hiding the problems window. It still makes sense to show the window if it's currently hidden, but there several other methods to close it.

This could be related to https://github.com/Microsoft/vscode/issues/47354

**Comment by sandy081** [comment]
@Gruntfuggly You mean to have a single button for each problem type?

**Comment by Gruntfuggly** [comment]
Yes - at the moment, the three types are a single button which opens/closes the problems window. If they were separate buttons, the action could be to hide/shows problems of the associated problem type (which may be a desirable feature in it's own right - I believe you can do this in Visual Studio) or open the problems view if it is currently closed.

**Comment by sandy081** [comment]
How will it help users who are used to open problems view just by clicking there. With the new behaviour it will only shows those problems of one type depending on the button clicked. This will not make existing users happy right?

Instead having filters in the problems view might be helpful IMO.

**Comment by Gruntfuggly** [comment]
I was thinking that the filter would only change if the buttons are clicked when the view is already open. 

I agree that filters in the problem view might be a better solution though, as it would be hard to show in the status bar, which filters are currently enabled.

**Comment by sandy081** [comment]
Cool.. Closing this in favour of #47354
