### ISSUE TITLE
unable to install twigcs

### ISSUE THREAD

**Issue by chu01** [Microsoft/vscode#49626]
Issue Type: <b>Bug</b>

Couldnt install twigcs on macosx

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_8554536|
|Screen Reader|no|
|VM|18%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.15.0
php-project|Fro|2.2.0
beautify|Hoo|1.3.0
vscode-database|baj|1.5.1
twigcs|cer|0.4.2
jshint|dba|0.10.18
vscode-eslint|dba|1.4.8
drupal-8-snippets|dss|0.0.2
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.3
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
vue-snippets-js-html-pug-razor|heb|0.0.3
docker-linter|hen|0.5.0
composer|ika|0.7.1
drupal-7-snippets|jun|0.0.7
php-symbols|lin|2.1.0
VS-code-drupal|mar|0.0.12
twig-language|mbl|0.2.9
vscode-apache|mrm|1.1.1
atom-keybindings|ms-|3.0.4
php-docblocker|nei|1.6.0
vetur|oct|0.11.7
drupal7-hooks-snippets|pau|0.0.2
drupal-8-javascript-snippets|tse|0.0.2
drupal-8-twig-snippets|tse|1.0.2
twig|wha|1.0.2

</details>

**Comment by RMacfarlane** [comment]
@chu01 What happens when you try to install it? Do you see any errors?

From the list of extensions that were sent, it looks like it has been installed. It might be worth deleting the folder for it under `~/.vscode/extensions` and trying to reinstall it
