### ISSUE TITLE
VSCode does not update when using the VSCode updater

### ISSUE THREAD

**Issue by sevnadj** [Microsoft/vscode#49620]
- VSCode Version:1.22.2
- OS Version: Windows 7 Enterprise Service Pack 1

Steps to Reproduce:

1. Run the auto-installer to click Install when Visual Studio Code opens
2. Click Update Now when new version is downloaded
3. VS Code runs updater, but then the error message pops up that says:
"Failed to install VS Code update. Please download and reinstall VS Code.
4. This was also done in Administrator mode as well, same error

Here's the error log:
May 10 09:47:26.008 INFO Starting: C:\Program Files (x86)\Microsoft VS Code\Code.exe, false
May 10 09:47:26.011 INFO Checking for running Code.exe processes... (attempt 1)
May 10 09:47:26.012 INFO Code.exe is running, wait a bit
May 10 09:47:26.512 INFO Checking for running Code.exe processes... (attempt 2)
May 10 09:47:26.516 INFO Code.exe is running, wait a bit
May 10 09:47:27.016 INFO Checking for running Code.exe processes... (attempt 3)
May 10 09:47:27.020 INFO Code.exe is not running
May 10 09:47:27.020 INFO Checking for possible conflicting running processes... (attempt 1)
May 10 09:47:27.023 INFO Inno Updater v0.4.3
May 10 09:47:27.024 INFO Starting update, silent = false
May 10 09:47:27.063 INFO do_update: "C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe", _
May 10 09:47:27.063 INFO move_update: "C:\\Program Files (x86)\\Microsoft VS Code\\unins000.dat", _
May 10 09:47:27.063 INFO Delete: "Code.exe" (attempt 1)
May 10 09:47:27.114 INFO Delete: "Code.exe" (attempt 2)
May 10 09:47:27.314 INFO Delete: "Code.exe" (attempt 3)
May 10 09:47:27.764 INFO Delete: "Code.exe" (attempt 4)
May 10 09:47:28.564 INFO Delete: "Code.exe" (attempt 5)
May 10 09:47:29.814 INFO Delete: "Code.exe" (attempt 6)
May 10 09:47:31.614 INFO Delete: "Code.exe" (attempt 7)
May 10 09:47:34.064 INFO Delete: "Code.exe" (attempt 8)
May 10 09:47:37.264 INFO Delete: "Code.exe" (attempt 9)
May 10 09:47:41.314 INFO Delete: "Code.exe" (attempt 10)
May 10 09:47:46.314 INFO Delete: "Code.exe" (attempt 11)
May 10 09:47:46.315 ERRO The process cannot access the file because it is being used by another process. (os error 32)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Does this still happen after restarting your system?
