### ISSUE TITLE
Ctrl click to follow hash query param url gets urlencoded

### ISSUE THREAD

**Issue by WORMSS** [Microsoft/vscode#49628]
Issue Type: <b>Bug</b>

When hovering over a url you are promoted to Ctrl + click to follow link

When doing so for links with query params

```text
http://localhost:3000/foo?bar=baz
```

You go to the url you expect. But when you go to a url that has a query param in a hash 
 or a hashbang, the hash part is urlencoded incorrectly

```text
http://localhost:3000/#/foo?bar=baz
```
Turns into 
```text
http://localhost:3000/#/foo%3Fbar=baz
```

This also happens when all extensions are disabled.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:10.813Z)
OS version: Windows_NT ia32 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (3.83GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jrieken** [comment]
> http://localhost:3000/#/foo%3Fbar=baz

I'd say that's correct because the spec says that the query part comes before the fragment part. So, in that sample there is no query part and the fragment part is '#/foo?bar=baz'. See https://tools.ietf.org/html/rfc3986#section-3

**Comment by WORMSS** [comment]
@jrieken ok.. Then my wording is bad... You are Messing up the fragment.. My fragment is `/foo?bar=baz` but that is not what gets opened.. vscode turns it into `/foo%3Fbar=baz`.

So can you re-open the issue please.

**Comment by jrieken** [comment]
Correct, the `?` doesn't need escaping when inside the fragment-part

**Comment by WORMSS** [comment]
Just so you know. I made a new issue about this #49808 with the correct terminology and deleted my last comment.

After reading back my last comment, it made me sound like a jerk. and that was not how I had intended it to be.

**Comment by jrieken** [comment]
> After reading back my last comment, it made me sound like a jerk. and that was not how I had intended it to be.

Never mind, it made we think a second time about this (which given soo many notifications on a Monday morning sadly doesn't always happen).
