### ISSUE TITLE
Multi-targeting Debug appears to be again broken

### ISSUE THREAD

**Issue by JohnGalt1717** [Microsoft/vscode#49624]
- VSCode Version: 1.23.0
- OS Version: Windows 10 Spring

Steps to Reproduce:

1. Create a .net core website

2. Add the following to your launch.json:

`
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp2.1/xyz.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "launchBrowser": {
                "enabled": false,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "https://localhost:5002",
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}/ClientApp",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "runtimeArgs": [
                "--disable-infobars",
                "--disable-session-restore"
            ],
            "sourceMapPathOverrides": {
                "webpack:/*": "${webRoot}/*"
            }
        },
`
2. Add the following compound:

`        {
            "name": "Debug in Chrome",
            "configurations": [
                "Launch Chrome",
                ".NET Core Launch (web)"
            ]
        },
`

3. Hit F5

4. Observe the following error:
5. Running each separately works fine.

Does this issue occur when all extensions are disabled?: NA. Requires extensions

VS Code still won't launch one debugger and then launch the second either, but right now this is breaking for our team causing major time wastage. Compound debugging really needs some love in general.

**Comment by isidorn** [comment]
@JohnGalt1717 thanks for your feedback.
What error do you get? You did not paste that in.
Can you reproduce with vscode inisders https://code.visualstudio.com/insiders/
Do none of the sessions start or just one?

**Comment by isidorn** [comment]
Please answer my other questions. Thanks

**Comment by JohnGalt1717** [comment]
Insider appears to work.
It launches the .NET core project, but not chrome.

**Comment by auchenberg** [comment]
@JohnGalt1717 Can you launch each of the debug configurations on their own with success?

**Comment by JohnGalt1717** [comment]
Yes.

**Comment by roblourens** [comment]
> "Configuration error at 'program'".

That error sounds like it's coming from the .NET debugger. The Chrome extension doesn't take a 'program' attribute.

When you say you can launch them on their own, do you mean, one at a time but they end up both running at the same time, or only by running one at a time?

If the second, can you try starting one manually, then starting the second manually?

**Comment by roblourens** [comment]
> Insider appears to work.

And it works fine in Insiders? That implies some vscode issue which is fixed already, based on that I'll assign back to @isidorn...

**Comment by JohnGalt1717** [comment]
The .NET Debugger does have a program attribute. However it starts fine (and requires that attribute) but then Chrome fails.

If you start .NET Debugger THEN start Chrome Debugger it works fine.

It's ONLY in the case of the compound debugging that the Chrome Debugger freaks out.

**Comment by roblourens** [comment]
The extension doesn't know that it's starting as part of a compound config, and I'm guessing that it's not actually being invoked by vscode. To test that, can you add `"trace": true` to the chrome config, run the compound again, and see whether it writes the path of a log file to the console?

**Comment by JohnGalt1717** [comment]
The only thing that I can see in the debug console (or anywhere else after turning on tracing is: "The parameters to the Event method do not match the parameters to the WriteEvent method. This may cause the event to be displayed incorrectly"

**Comment by JohnGalt1717** [comment]
It appears that something in the whole process is leaving crap behind in the temp folder. Closing Vs code, clearing temp and then restarting it will work for a while and then it happens again.

**Comment by roblourens** [comment]
Which temp folder?

**Comment by JohnGalt1717** [comment]
<user>/appdata/local/temp

**Comment by roblourens** [comment]
Ok, I don't think vscode writes there. Not sure what that would impact. I think we are still at

> Insider appears to work.

**Comment by isidorn** [comment]
If insiders works then there is no action needed. Please wait for the new stable update in about two weeks
Thanks
