### ISSUE TITLE
File > Open Recent > list never has my recently opened files

### ISSUE THREAD

**Issue by cfcoder** [Microsoft/vscode#49629]
Issue Type: <b>Bug</b>

I can open files from the Explorer left sidebar or using Ctrl-P and enter the file name to open. Wether I leave them open in the editor or close them, either way these files do not show up in my Open Recent list. What I find it is is a list of files that I have no idea how they got in that list. I don't understand your algorithm for this but I cleared the list and can open and close files in the editor and the list remains empty. It is not tracking files I open and close in the editor. Seems totally broken to me and makes me wonder why no one else has reported this yet.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (3.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
beautify|Hoo|1.3.0
coldfusion|ili|1.0.1
vscode-cfml|Kam|0.3.1
hg|mrc|1.2.3
mssql|ms-|1.3.1
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.4.3
hgwo|pxg|1.1.2
subtle-brackets|raf|2.1.1
vscode-icons|rob|7.23.0
highlight-matching-tag|vin|0.4.4
change-case|wma|1.0.0
better-align|wwm|1.1.6
beauty|yhp|0.0.2
html-css-class-completion|Zig|1.17.1

</details>

**Comment by bpasero** [comment]
That list is populated from opening something into VSCode from outside (e.g. via command line or File > open). It is not meant to change whenever you open an editor from within.

**Comment by cfcoder** [comment]
That seems to be of quite limited value then. Don’t most people that open
files for edit inside VS Code do so from the left side file Explorer panel
or using the command P or control P keyboard option?

For me, ideally, you should put files you open and then close into that
list, so that you can reopen them later as needed. I rarely open files from
outside the app because that’s not using the file navigator/explore inside
the app.

So I guess I don’t understand your comment and why you’re closing this
ticket.   .
