### ISSUE TITLE
Powershell set-location 'breaks' integrated terminal

### ISSUE THREAD

**Issue by ilicmarko** [Microsoft/vscode#49631]
Issue Type: <b>Bug</b>

I don't know if this is **fixable** or even if this is considered a bug. I want to report it, if someone encounters this he knows how to fix it.
I have a custom profile set for my PowerShell, because 99% of the time I use it in my `Projects` directory I added it as my default.

```
set-location C:\Users\Maverick\Documents\Projects
```
Unfortunately, this will ‘break’ VS Code’s integrated terminal in a way that when you open a project it won’t open the terminal in the same directory. Furthermore, the command `Open in Command Prompt` won’t work.
If in Windows when you open your VS Code and the terminal doesn’t open in the working directory or when you click on a folder and select `Open in Command Prompt` and your terminal just refreshes. **Check if you have a Windows PowerShell profile with a default directory**

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-caniuse|aka|0.5.3
codealike-code|Cod|0.0.20
gitignore|cod|0.5.0
php-debug|fel|1.12.3
canvas-snippets|hol|0.3.2
beautify|Hoo|1.3.0
docthis|joe|0.6.0
dotenv|mik|1.0.1
mssql|ms-|1.3.1
python|ms-|2018.4.0
cpptools|ms-|0.17.0
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.4.3
vetur|oct|0.11.7
material-icon-theme|PKi|3.4.0
laravel-5-snippets|sac|2.0.1
code-settings-sync|Sha|2.9.2
php-ci|sma|0.2.10
addDocComments|ste|0.0.8
code-spell-checker|str|1.6.10
ayu|tea|0.14.0
wordpress-snippet|tun|1.1.2
lorem-ipsum|Tyr|1.2.0
gitblame|wad|2.4.2
vscode-wakatime|Wak|1.2.1
quokka-vscode|Wal|1.0.123
vscode-todo-highlight|way|0.5.12

</details>

**Comment by Tyriar** [comment]
Does this repro when you close all Windows and launch with `code --disable-extensions`?

**Comment by ilicmarko** [comment]
Yes i does.

**Comment by Tyriar** [comment]
Re-reading this I think you're saying that Open a folder in command prompt is not opening in that folder but instead in `Projects`. If so this is expected as you've put it in your profile; powershell inits to the correct folder and then you set the location. Let me know if that's not the case.
