### ISSUE TITLE
Terminal hangs with using SSH

### ISSUE THREAD

**Issue by migs911** [Microsoft/vscode#49630]
Issue Type: <b>Performance Issue</b>

Terminal hangs when i have any connect via SSH in it. It happends when i'm not using connected terminal for some time.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.84GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_69649|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   24	   147	   466	code main
    4	   164	   552	   gpu-process
    0	    49	   580	   shared-process
    0	   229	 14610	   window (tp.ditaval — cloud)
    0	    82	 14612	     extensionHost
    0	    49	 14613	     watcherService
    0	    49	 14614	     terminal
    0	     0	 14615	       /bin/zsh -l
    0	    33	 15818	     terminal
    0	     0	 15819	       /bin/zsh -l
    0	    49	 15898	     searchService
    0	   229	 17293	   window (Добро пожаловать — YandexCloud-API (рабочая область))
    0	    98	 17399	     extensionHost
    0	    49	 17404	       electron_node jsonServerMain.js 
    0	    49	 17400	     watcherService
    0	    33	 17448	     terminal
    0	     0	 17449	       /bin/zsh -l
    0	    82	 18896	   shared-process
    0	     0	 18905	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-terminal-here|Tyr|0.1.1
vscode-dash|dee|1.10.0
gitlens|eam|8.2.4
vscode-firefox-debug|hbe|1.2.1
svn-scm|joh|1.29.0
jumpprotobuf|ldc|0.0.3
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.4.0
Go|ms-|0.6.79
vscode-yaml|red|0.0.11
vscode-sort-json|ric|1.11.0
markdown-all-in-one|yzh|1.3.0
vscode-proto3|zxh|0.2.1

</details>

**Comment by Tyriar** [comment]
By hangs do you mean the terminal freezes and doesn't receive any more output (and needs to be killed?). Could you paste in the output of `code --status` when you're in this state?
