### ISSUE TITLE
No path autocompletion of ES6 modules.

### ISSUE THREAD

**Issue by admmasters** [Microsoft/vscode#4963]
- VSCode Version: Version 0.10.14-insider (0.10.14-insider)
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Using ES6 within foo.js try and use autocompletion to insert bar.js
2. "No suggestions"

I don't think this is a bug - rather a feature that does not exist, considering the nature and shape of modern JS, IMHO this should be standard - WebStorm for instance has this and Atom has many plugins that do this - if this is the role of an extension then fair enough - I'll look into writing one, just feel this should be part of the editor core.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7931
