### ISSUE TITLE
"[ts] 'types' can only be used in a .ts file" Error in TS file

### ISSUE THREAD

**Issue by teachtyler** [Microsoft/vscode#49639]
Issue Type: <b>Bug</b>

Am working in an Angular 5 repo. 
 
1. Reopened vscode 
2. Navigated to .ts file
3. Corresponding Error, but only in .ts file that was opened at launch. 

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:10.813Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (6.91GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
typescript-react-snippets|abo|0.2.0
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|0.19.1
clojure|avl|0.9.8
vscode-styled-jsx|bla|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
cjsx|cri|0.0.6
angular2-snippets|dan|1.0.19
vscode-eslint|dba|1.4.8
vscode-instant-markdown|dba|1.4.1
lualinter|dcr|1.0.3
vscode-npm-source|dku|1.0.0
bower|don|0.0.3
githistory|don|0.4.0
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.28
vsc-material-theme|Equ|2.0.1
reasonml|fre|1.0.34
code-sync|gol|2.5.3
haskell-linter|hoo|0.0.6
vscode-ghc-mod|hoo|1.2.0
vscode-angular2-emmet|jak|2.0.3
Angular1|joh|0.2.0
Angular2|joh|6.0.0
language-haskell|jus|2.4.0
Lua|key|0.0.9
vue|liu|0.1.5
Angular2Tests|Mar|0.7.3
json-to-ts|Mar|1.5.5
vscode-lebab|mrm|2.5.0
python|ms-|2018.4.0
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.4.3
color-highlight|nau|2.3.0
indent-rainbow|ode|7.2.2
vscode-code-outline|pat|0.2.0
remote-vscode|raf|1.1.0
vscode-icons|rob|7.23.0
vscode-parinfer|sha|0.6.1
visualclojure|sti|2.0.0
react-redux-es6-snippets|tim|2.1.0
vscode-lua|tri|0.12.4
jsx|Twe|0.0.1
haskelly|UCL|0.5.2
Angular2|UVB|0.4.1
vscode-react-native|vsm|0.6.9
iis-express|war|1.1.0
wymseeangular1snippets|wym|0.1.18
JavaScriptSnippets|xab|1.6.0
D3Snippets|yoy|0.1.11

(2 theme extensions excluded)

</details>

**Comment by teachtyler** [comment]
![image](https://user-images.githubusercontent.com/10254377/39889025-aaf4b08a-5464-11e8-93bd-3304a5cee03c.png)

**Comment by mjbvz** [comment]
Does this issue still occur when you disable all of your installed extensions and restart vs code?

**Comment by teachtyler** [comment]
Error went away after disabling everything. Problem didn't come back after enabling them all either.
