### ISSUE TITLE
VS code arrow expanding aint working

### ISSUE THREAD

**Issue by AndonMitev** [Microsoft/vscode#49642]
![untitled](https://user-images.githubusercontent.com/32274987/39890433-6bd7d24e-54a3-11e8-907f-c3c7a567322b.png) As u can see down in my menu arrow its clicked but dont expand any data from array any possible solutions?

**Comment by isidorn** [comment]
Object evaluation only works while you are debugging due to the architecture of our debugger.
Closing as designed
