### ISSUE TITLE
Terminal Clear Command does not work for ANY keybinding. Simply prints ^L

### ISSUE THREAD

**Issue by mikeyaworski** [Microsoft/vscode#49641]
VS Code version: 1.23.0
OS Version: macOS 10.13.4

I am trying to use `cmd+k` or any other keyboard shortcut to clear my terminal. The following is a screenshot of my keybinding for clearing the terminal:

<img width="767" alt="screen shot 2018-05-10 at 3 23 51 pm" src="https://user-images.githubusercontent.com/10966214/39889545-32b6f68a-5466-11e8-9fff-372a7aa1eed2.png">

It is the only shortcut used to clear the terminal and is a default one. I have no custom keyboard shortcuts. The following is what happens when I try to use said shortcut on the terminal:

<img width="286" alt="screen shot 2018-05-10 at 3 26 31 pm" src="https://user-images.githubusercontent.com/10966214/39889689-8d2739b8-5466-11e8-9f79-73e83027fb93.png">

I have tried changing the shortcut to `cmd+8` and other obscure keybinds, all of which result in the same image above. It simply prints `^L` to my console. Currently the only way for me to clear the terminal is by typing `clear`.

**Comment by nilshartmann** [comment]
Hi @mikeyaworski!

Had the same issue, with 1.23.0 but with recent update 1.23.1 the bug seems to be resolved. Both keyboard shortcut and "Clean" from context menu work again.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/49162
