### ISSUE TITLE
Intellisense hints showing raw JSDoc tags

### ISSUE THREAD

**Issue by futagoza** [Microsoft/vscode#49640]
I've noticed this for a couple of releases now, but it seems to be more annoying when I'm just working on JavaScript with JSDoc's in the comments for type hinting. Here's an example:

```js
/**
 * `Array#forEach` for objects, arrays and array-like's
 * 
 * @param {{}|[]} object An object or array-like object.
 * @param {(value:any,key?:string|number,object?:{}|[])=>any} iterator A method to call on each property.
 * @param {any} context An object used as `this` within the `iterator` method.
 * @return {void} 
 */
function forEach( object, iterator, context ){
    // ...
}
```
When you hover over `forEach` it will show the JSDoc comment but also show the raw tags, without the type information. This is the same for the arguments for the method as well, only it looks weirder as it shows the comment for the argument, then the raw JSDoc string without the type data.

If this is an intended feature, can you consider adding a setting that restores the original behaviour where the raw tags did not show in the hints/tooltips? (e.g. `"jsDocRawTags.enabled": true`)
___________________________________________________

- VSCode Version: 1.23.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Create a JSDoc comment for a variable or method
2. Hover over the object name or reference to the object

Does this issue occur when all extensions are disabled?: Yes

Related maybe: #3073

**Comment by mjbvz** [comment]
This is by design. Otherwise there is no way to see the documentation  for the parameters. Not helpful when you are hovering over the declaration itself but this is helpful when using the function in other files

Not in favor of adding more settings
