### ISSUE TITLE
Click to symbol does not jump to file but to the import (JSX/JS).

### ISSUE THREAD

**Issue by admmasters** [Microsoft/vscode#4964]
- VSCode Version: Version 0.10.14-insider (0.10.14-insider)
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Cmd+Click on a Component in JSX (also JS).
2. VSCode jumps to the import and not the file itself.

Expected:
VSCode should just jump to the file referenced in the import as its smart enough to know the specific import.

**Comment by mquandalle** [comment]
I get that behavior also on non-JSX functions.

**Comment by admmasters** [comment]
Updated, you are correct.

**Comment by dbaeumer** [comment]
This is how the TS server currently resolved. IMO the behavior is 'technically' correct but not very user friendly. IMO the tsserver should either:

- offer a flag to control that
- resolve the definition to the 'implementation' if the import doesn't rename the symbol
- jump to the import if it does rename the symbol.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7930
