### ISSUE TITLE
Scrolling not working on Windows, desktop since 1.23

### ISSUE THREAD

**Issue by acourdavault** [Microsoft/vscode#49643]
Hello,
I just updated to v1.23, the scroll does not work anymore,

I have tried "window.smoothScrollingWorkaround": true, as suggested in some thread, but not working.
It was perfectly working a few minutes ago before the update.

I work on Windows 10 Home edition

Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:10.813Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

**Comment by bpasero** [comment]
@acourdavault can you explain what you see now?
