### ISSUE TITLE
g++ not responding in integrated terminal

### ISSUE THREAD

**Issue by WardenGnaw** [Microsoft/vscode#49650]
From https://github.com/Microsoft/vscode-cpptools/issues/1978 by @salbeira
----------------------------------------------------------------

Using ArchLinux on a Dell XPS 15 9560.

Whenever I try to start the g++ in the integrated terminal the call hangs and outputs nothing. Even just compiling a simple "Hello World" Program using the g++ manually, not called from make, causes the call to hang. CTRL+C still allows cancelling. The integrated terminal says that the normal "bash" is running.

Calling g++ or make from the directory the project I am working on is located in a normal external terminal works fine.

``g++ foo.cpp -o foo`` - hangs
even
``g++ --version`` - hangs

**Comment by Tyriar** [comment]
My only guess here is that the environments differ (`env`) and that's causing g++ to have issues. Are you on the latest version of VS Code?

**Comment by salbeira** [comment]
I am on the latest version as far as I know (1.23.0).
Sometimes using TAB-completion also brings the current line to "hang" (CTRL+C again works).
I guess simply posting all set environment variables is not really helpful. What are you looking for?

**Comment by Tyriar** [comment]
@salbeira I don't know g++ so I'm not sure I will be able to help much in solving this, I doubt this is a problem with the terminal though, my guess is it's an environment related issue with g++.
