### ISSUE TITLE
I can't use the "gg=G" to format the vue file.but I can use the shift+alt+f to format that.

### ISSUE THREAD

**Issue by CG-man** [Microsoft/vscode#49658]
I can't use the "gg=G" to format the vue file.but I can use the shift+alt+f to format that.

**Comment by mjbvz** [comment]
I do not understand the issue. Please follow these steps to provide more information about the problem you are seeing: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests
