### ISSUE TITLE
Should indent guides be highlighted one level deeper?

### ISSUE THREAD

**Issue by deanchao** [Microsoft/vscode#49664]
![image](https://user-images.githubusercontent.com/4556756/39905279-144cbcbc-550f-11e8-86fd-49b4da823f5d.png)

I like the new feature [Highlighted indent guides](https://code.visualstudio.com/updates/v1_23#_highlighted-indent-guides) very much, but there is one small question that botheres a lot, that is I think the indent guide should be highlighed one level deeper, like the image above.

Are there more people think like me? Mybe we should discuss this.

**Comment by alexandrudima** [comment]
Let's continue tracking in #49342
