### ISSUE TITLE
Copy/Paste adds new line

### ISSUE THREAD

**Issue by bamse16** [Microsoft/vscode#49662]
Issue Type: <b>Bug</b>

Hi,

This started to happen after the last release, a very strange behaviour.

When editing JavaScript (haven't tested other), after copy/paste, the line below paste gets a new line. If you cmd+z, that new line disapears. See attached video: https://www.dropbox.com/s/13f8rh1uysx327w/New%20Line%20On%20Paste.mov?dl=0. All I did, was copy/paste the same value.

I'm not sure if this issue is vscode related or vscode-eslint related.

Thank you,
Marius

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Users/marius/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-eslint|dba|1.4.8
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.4.3
elm|sbr|0.17.0

</details>

**Comment by lardissone** [comment]
I think there should be an option to disable the newline after pasting.

If you paste something inside a line block it adds a new line below too.

**Comment by ayozebarrera** [comment]
@bamse16 format != newline

I've using formatOnPase from the start and now I'm having this issue.. **always**, it inserts a new line

**Comment by joshuaquek** [comment]
I am getting the issue too :(

**Comment by joshuaquek** [comment]
Oh lol I think I solved the issue:

Add this into your VS Code settings:

`"editor.autoIndent": false`

**Comment by ayozebarrera** [comment]
My problem was Beautfy extension.. don't know when I installed it but if I disable it, problem solved!
