### ISSUE TITLE
"emmet.triggerExpansionOnTab:true" Cause Tab not available

### ISSUE THREAD

**Issue by EryouHao** [Microsoft/vscode#49666]
- VSCode Version: 1.23.1
- OS Version: 10.13.4

Steps to Reproduce:

1. user setting："emmet.triggerExpansionOnTab": true, due to tab in editor not work

Does this issue occur when all extensions are disabled?: No

**Comment by ramya-rao-a** [comment]
@EryouHao Can you explain further?
