### ISSUE TITLE
Task API: TaskExecution contain a TaskResult

### ISSUE THREAD

**Issue by rickvanprim** [Microsoft/vscode#49665]
I think it would be useful if a `TaskExecution` provided a way to get the result of the Task being executed which would include the exit code, stdout, and stderr.  This would allow for things like providing a different notification when a Task completes depending on success or failure, or scanning the output and reporting back certain details.

I also think it would be useful if a cached `TaskExecution` could be polled to see when it has a `TaskResult`, so that if an extension kicks off a Task, it can monitor it for completion, instead of having to subscribe to `onDidEndTask` when it's only concerned with a particular Task.

**Comment by dbaeumer** [comment]
I still don't see why polling is preferred over eventing especially in a system like NodeJS. Can you let me know in which case polling is preferred.

**Comment by rickvanprim** [comment]
I don't know NodeJS well enough to directly address that, so it could very well be unnecessary.  My perspective is that I would expect to be able to track the life of a Task without having to subscribe to a global event and compare each ending Task with the one I'm interested in.

For comparison, creating a process in Windows/Linux/MacOS returns a process ID which can be used query the state of that process, terminate it, etc.  Your `terminateTask()` API fits that pattern (using the `TaskExecution` as the identifier).  For completeness I'd expect to be able to get the `TaskResult` from a similar API, or a future to the `TaskResult` which could then be waited on.

**Comment by dbaeumer** [comment]
Since NodeJS is an async event based system (single threaded) polling can only be done using a setInterval which at the end results in the same as adding an event handler to the task end event. I will look into how to best allow for query (which does make sense) but not to encourage polling.
