### ISSUE TITLE
VS Code sends inconsistent Source object in setBreakpointsRequest

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4966]
- VSCode Version: alpha
- OS Version: OS X 10.11.4

It is not possible to clear or disable breakpoints in inlined source. The reason for this is that a different Source object is passed to setBreakpointsRequest when clearing or disabling the breakpoint.

- set a breakpoint in inlined source
- restart debug session and inspect Source object passed to setBreakpointsRequest:
  ![2016-04-05 16-31-20](https://cloud.githubusercontent.com/assets/1898161/14285625/91c6a17c-fb4c-11e5-9b5f-141b19e4625f.png)
  as you can see the Source object has all the information to set the breakpoint in the inlined source
- delete (or disable) the breakpoint and again inspect Source object passed to setBreakpointsRequest:
  ![2016-04-05 16-32-25](https://cloud.githubusercontent.com/assets/1898161/14285701/d27694de-fb4c-11e5-910a-ac1662e46047.png)

  here the Source no longer has the adapterData which makes it impossible to correctly disable the breakpoint in node 

VS Code must always send the same Source object to setBreakpointsRequest.

**Comment by isidorn** [comment]
Fixed via f56ccb0
