### ISSUE TITLE
Allow project name to be presented on search and context menu when in multi-root workspace

### ISSUE THREAD

**Issue by renatofsp** [Microsoft/vscode#49676]
For instance, if I have two projects with a folder with the same name lets say:
- folder1/webapp (in workspace file a set the name to 1)
- folder2/webapp  (in workspace file a set the name to 2)

and I make a search using ctrl+p (opening context menu) or using the search feature the results appear web app for both folders making it hard to identify what folder it really points to.

Is there a way to make the label defined in the workspace folder to be the one presented on the context menu and/or search instead of webapp in both we will get 1 for results belonging to the folder1 and 2 for the results belonging to the folder2

**Comment by Lukapt** [comment]
+1

**Comment by renatofsp** [comment]
fixed on version 1.25.1
