### ISSUE TITLE
Error when move code up and down

### ISSUE THREAD

**Issue by khanhvu14** [Microsoft/vscode#49679]
When I move selection of code down or up, the "selection of code" auto translate to right align 1 tab.
Please help to check the attach image.
<img width="1440" alt="screen shot 2018-05-11 at 4 01 38 pm" src="https://user-images.githubusercontent.com/4197632/39916424-9e35e29e-5534-11e8-887b-d12987d6673d.png">

<img width="1440" alt="screen shot 2018-05-11 at 3 57 31 pm" src="https://user-images.githubusercontent.com/4197632/39916341-629e1364-5534-11e8-83f5-3f1306123cdd.png">
<img width="1440" alt="screen shot 2018-05-11 at 3 57 34 pm" src="https://user-images.githubusercontent.com/4197632/39916343-6334430c-5534-11e8-9a66-fd281b472503.png">

**Comment by rebornix** [comment]
Same issue as https://github.com/Microsoft/vscode/issues/54829#issuecomment-422501144, where I left some initial investigations. Let's track this bug there.
