### ISSUE TITLE
Inconsistent TS syntax highlighting

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#49674]
- VSCode Version: 1.23.0
- OS Version: macOS Sierra

Steps to Reproduce:

1. Look at attached image. The second mention of FormDialog on that last line is blue... shouldn't it be green as well? Doesn't make sense that the same reference is being highlighted differently on the same line.

![screen shot 2018-05-11 at 2 07 49 pm](https://user-images.githubusercontent.com/9585787/39911207-cd86d662-5524-11e8-83a8-14ea579a5d9e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by DJMcNab** [comment]
The first time `FormDialog.result` is a type, so it is highlighted as a type. The second time it is a variable, so it highlighted as such.

**Comment by jpike88** [comment]
Should there be some sort of colour difference that indicates that FormDialog is an import? Is becomes especially handy when it's tucked away deep in the code somewhere, as it's not a local variable.

**Comment by DJMcNab** [comment]
I think that thatwould require Microsoft/language-server-protocol#18. But it seems like it could be a good idea if that issue is resolved.

**Comment by mjbvz** [comment]
This is by design. `FormDialog` is used as a type in the first location, while in the second it is used as an object. Theme are free to change these colors but our default themes choose to make this distinction clear
