### ISSUE TITLE
cursorUndo moves the back to the start of the selection

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#49678]
If I add many multiple cursors such that the first cursor has scrolled off the top of the screen, when I then use undoCursor to remove the last cursor, the window jumps back to show the first cursor in the middle of the screen. This makes it really hard to undo multiple cursors as I have to keep scrolling back to the last one.  Really the scroll position should stay where it is, or scroll to where the previous last cursor is.

**Comment by Gruntfuggly** [comment]
None of the linked issues cover this issue - this is specifically when removing an added multiple cursor.

**Comment by alexdima** [comment]
Fixed with the fix for #6234
