### ISSUE TITLE
Cannot read property 'clearHistory' of undefined

### ISSUE THREAD

**Issue by tejasjadhav** [Microsoft/vscode#49673]
Issue Type: <b>Bug</b>

1. Clear search history manually from Search menu.
2. Close and open VS Code.
3. Go to command prompt and enter _Search: Clear Search History_.

![screenshot from 2018-05-11 12-32-36](https://user-images.githubusercontent.com/10093001/39911020-741c0f8c-5517-11e8-9b4a-be01d07dcfaa.png)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.16.7-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2645)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (2.20GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
code-settings-sync|Sha|2.9.2
string-converter|ada|0.1.1
django-snippets|bib|1.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.4
prettier-vscode|esb|1.3.1
vscode-random|jre|1.3.2
MagicPython|mag|1.0.12
dotenv|mik|1.0.1
python|ms-|2018.4.0
atom-keybindings|ms-|3.0.4

</details>

**Comment by roblourens** [comment]
I guess this only works when the viewlet is open... I need to separate search history from the view itself.
