### ISSUE TITLE
Failed to delete using Trash in Ubuntu 18.04

### ISSUE THREAD

**Issue by AyushG3112** [Microsoft/vscode#49675]
- VSCode Version: 1.23.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Try Deleting a File from the VSCode explorer. Error occurs:

![screenshot from 2018-05-11 12-57-46](https://user-images.githubusercontent.com/21307931/39912231-b61283fe-551b-11e8-8fe2-ca2c217777d7.png)

Tried with multiple projects.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Can you delete using Trash outisde of vscode?
Can you reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/
Do you see some errors if you open F1 > developer tools > console?

**Comment by AyushG3112** [comment]
@isidorn 

I can delete using Trade from my File Explorer(`nautilus`)
Insiders Build is not working wither.
No Error Happening in the console.

**Comment by isidorn** [comment]
@AyushG3112 can you please 
F1 > developer tools > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L695) and check out what is the `error`.
For more investigation you can step into the `fileService.del` call and check out what is going on there.

Thanks!

**Comment by AyushG3112** [comment]
@isidorn could you point me to how to add a breakpoint in the line you mentioned?

**Comment by isidorn** [comment]
@AyushG3112 just click on a line number
https://developers.google.com/web/tools/chrome-devtools/javascript/

**Comment by AyushG3112** [comment]
@isidorn I know that, what my question is is: How to I navigate to that file in the devtools? I tried looking through the `sources` tab but could not find it.

**Comment by isidorn** [comment]
@AyushG3112 oh sorry, misunderstood. Open `sources` tab wait for a minute, ctrl + P -> type "fileActions"

**Comment by AyushG3112** [comment]
Error stack trace says

``` console
"Error: Failed to move 'README.md' to the trash
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2944:157
    at <anonymous>"
```

**Comment by isidorn** [comment]
Not sure if we can do something about this. It is coming from the file service thus forwaridng to @bpasero

**Comment by bpasero** [comment]
@Tyriar might know what to do on Linux to enable the trash functionality in VS Code.

**Comment by Tyriar** [comment]
I looked into the implementation of Electron's delete a while ago. You may need to install some dependency, see https://github.com/Microsoft/vscode/issues/22820#issuecomment-288239512

**Comment by AyushG3112** [comment]
@Tyriar I have `gvfs-trash` installed, the the delete works using it, the output is as follows:

``` console
$ gvfs-trash Screenshot\ from\ 2018-05-12\ 22-41-36.png
This tool has been deprecated, use 'gio trash' instead.
See 'gio help trash' for more info.
```

VS Code delete still fails though.

**Comment by AyushG3112** [comment]
@bpasero @Tyriar `shell.moveItemToTrash()` returned `true`, and file got moved to trash. VS Code still throws the same error though.

**Comment by Tyriar** [comment]
@AyushG3112 what version of Electron did you check on? Perhaps something happened between 1.7.12 (vscode) and 2.0.0 (the quick stack repo) https://github.com/electron/electron-quick-start/blob/9f0ab1460f949e656b0ff37a732cd950363dc1cd/package.json#L20

**Comment by AyushG3112** [comment]
It said `2.0.0`, I'll try with `1.7.2` when I next boot into Linux.

**Comment by AyushG3112** [comment]
I tried installing 1.7.12, however, the postinstall script of electron hanged on my PC. The problem MIGHT be an incomplete/broken electron installation rather than a broken API or missing dependency.
