### ISSUE TITLE
无法使用ctrl +c 

### ISSUE THREAD

**Issue by pccx125** [Microsoft/vscode#49671]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。
Issue Type: <b>Bug</b>

ctrl +c  无法使用  但是右键是可以完成复制粘贴的，我不知道是什么原因 之前还是好好的 今天打开就这样了

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (4.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\vscode\read\read.cpp|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
GBKtoUTF8|buk|0.0.2
bracket-pair-colorizer|Coe|1.0.48
code-runner|for|0.9.3
CppSnippets|har|0.0.13
jlang-clang|l3d|0.0.8
vscode-clang|mit|0.2.2
vscode-language-pack-zh-hans|MS-|1.23.4
python|ms-|2018.4.0
cpptools|ms-|0.17.0
vim|vsc|0.11.6
clang-format|xav|1.6.2

(1 theme extensions excluded)

</details>

**Comment by AnClark** [comment]
@pccx125 抱歉，这个地方只能用英文反馈问题，因为开发者主要都用英语来交流。另外烦请你把出现问题的步骤用英文复现一下。

EN: Sorry, here we can only submit feedbacks in English, as developers are mainly communicated with English. And also please describe how you meet this problem.

**Comment by isidorn** [comment]
Exactly please file issue in english with reproducable steps
