### ISSUE TITLE
Find and replace doesn't open files anymore

### ISSUE THREAD

**Issue by Alber70g** [Microsoft/vscode#49681]
The new behaviour is very confusing. Is there a way to change it through configuration or is it a bug?

- VSCode Version: Version 1.23.0 (1.23.0)
- OS Version: MacOS 10.12.6 Sierra

Steps to Reproduce:

0. Use find-and-replace from sidebar
0. Click the replace all button

Expected: Opens all editors with unsaved changes to each file
Actual: Opens nothing and just changes files on disk

Does this issue occur when all extensions are disabled?: *Yes*

[edit: additional info]

I see it's an improvement on the release from [1.22 save-automatically](https://code.visualstudio.com/updates/v1_22#_save-automatically-when-search-replace)
I'd like to have an option where this behaviour can be modified into the 'old' way.

**Comment by sandy081** [comment]
Related #46983

**Comment by sandy081** [comment]
@Alber70g 

> I'd like to have an option where this behaviour can be modified into the 'old' way. 

Do you mean you do not want to auto save or you want the files to be opened after replace operation is done?

If you do not want auto save, may I know why you don't want that?
