### ISSUE TITLE
"Not showing x further errors and warnings" increases diagnostic severity in explorer

### ISSUE THREAD

**Issue by tboby** [Microsoft/vscode#49687]
Issue Type: <b>Bug</b>

1. Enable `"problems.decorations.enabled": true` in settings
2. Open a folder with a file that has many (e.g 100+) "warning" severity diagnostics
3. Observe explorer decoration for file

Expected:
Green "warning/info/hint" colouring and "+9" text

Actual
Red "error" colouring and "+9" text

Note, the problems list behaves correctly and doesn't consider the "fake" error when sorting files like it would a real error.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-8370 Eight-Core Processor                (8 x 4335)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (0.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
paradox-syntax|ada|1.0.1
gitkraken-glo|axo|1.0.3
vscode-markdownlint|Dav|0.15.0
tslint|eg2|1.0.28
scaffold|fir|1.0.0
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|3.20.3
Ionide-Paket|Ion|1.11.0
path-autocomplete|ion|1.9.0
vscode-nuget-package-manager|jmr|1.1.6
python|ms-|2018.4.0
csharp|ms-|1.15.0
yo|sam|0.9.3
cwtools-vscode|tbo|0.4.23

</details>

**Comment by jrieken** [comment]
Yep, it should take the most severe diagnostic, not just error
