### ISSUE TITLE
Opening files causes watched projects (e.g. using Nodemon) to restart even though nothing has changed

### ISSUE THREAD

**Issue by liam-potter** [Microsoft/vscode#49683]
Issue Type: <b>Bug</b>

I have a number of projects using different frameworks that have have automated restarts/hot reloading whenever a file is changed. Until a few weeks ago they all worked fine but now when opening files it has started to trigger the hot reloading process when simply opening a file.

The issue occurs when all extensions are disabled. Has VSCode recently changed something that may be causing this?

VS Code version: Code - Insiders 1.24.0-insider (987c3dccf45ef0447b7b4c52c81794fab2b6dad5, 2018-05-11T05:16:29.994Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (7.22GB free)|
|Process Argv|D:\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.4
vscode-npm-script|eg2|0.3.4
auto-close-tag|for|0.5.6
vue-snippets|hol|0.1.5
discord-vscode|icr|2.5.0
edge|luo|0.2.0
dotenv|mik|1.0.1
color-highlight|nau|2.3.0
vetur|oct|0.11.7
indent-rainbow|ode|7.2.2
vscode-icons|rob|7.23.0
sass-indented|rob|1.4.9
language-stylus|sys|1.9.2
ayu|tea|0.14.0
vscode-import-cost|wix|2.6.2

</details>

**Comment by liam-potter** [comment]
The basic issue is that VSCode seems to be doing something to a file when it is opened that file/folder watchers see as a change.

The repro would simply be to start any project which uses file watchers such as `nodemon` to enable something like hot-reloading. Then simply click on a file that is being watched in the file explorer to open it and watch the file watcher do what it's been told to do when a file has changed (e.g. run hot-reloading).

Even though at this point the file has not been changed, the file watcher still thinks the file has been changed and does whatever it's been told to do when that file changes.

At first I thought the issue was specific to `nodemon` however I am having the issue with multiple projects that use different watcher libraries/techniques. Right now I'm having the issue with an AdonisJS project using `nodemon` and a NuxtJS project using `webpack-dev-middleware`.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment]
@liam-potter can you:
* run code --verbose from the command line for a fresh instance
* open the developer console (Help > Toggle Developer Tools > Console)
* watch the output in the console when you open a single file

I wonder if you see file events reported from us too when just opening files.

**Comment by liam-potter** [comment]
I'm out at a wedding today but will try this tomorrow. Thanks.

**Comment by liam-potter** [comment]
Apologies for the delayed response @bpasero - post wedding party recovery period!

I have followed the steps provided and did not see anything logged in the console - I take it this means VSCode isn't firing any file events when opening files?

I am wondering if this could potentially be related to the antivirus software or something like that at work as I have been unable to replicate this behaviour on my home machine. As such I am closing this issue as I do not believe VSCode is causing the problems here.
