### ISSUE TITLE
No extension can display when I use Ctrl+Shift+X

### ISSUE THREAD

**Issue by leondai78** [Microsoft/vscode#49680]
Issue Type: <b>Bug</b>

I tried to reinstall the vscode but the problem still occurs. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2650)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.68GB (2.66GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sandy081** [comment]
@leondai78 Do you mean Extension view is not shown on using keybinding ctrl+shift+x?

Can you please open your keybindings editor and type "ctrl+shift+x" in the search box and see what commands are associated to it?
