### ISSUE TITLE
[folding] Folding and Move Line does not work

### ISSUE THREAD

**Issue by mhchem** [Microsoft/vscode#49686]
1. Copy this text into an editor
```
aaaa
    bbbb
    cccc
    dddd
eeee
    ffff
    gggg
```

2. Fold All, you will see "aaaa" and "eeee".

3. Place cursor in first line ("aaaa")

4. Move line down (`Alt + DownArrow`)

5. Unfold All

6a. Expected
```
eeee
    ffff
    gggg
aaaa
    bbbb
    cccc
    dddd
```

6b. Experienced

```
    bbbb
eeee
    ffff
    gggg
aaaa
    cccc
    dddd
```

**Comment by aeschli** [comment]
Trying the example above I get 
```
    bbbb
aaaa
    cccc
    dddd
eeee
    ffff
    gggg
```

**Comment by mhchem** [comment]
Ooops. Sorry for the incorrect bug report. I was anticipating to move collapsed groups so much that I did not realize that. Sorry. Well, I guess I should open a feature request then (#49886).
