### ISSUE TITLE
Middle mouse button invokes column selection and selection paste on Linux at the same time

### ISSUE THREAD

**Issue by CherkashinSergey** [microsoft/vscode#49693]
Issue Type: <b>Bug</b>

1) Save some text file.
2) Use middle mouse button to select column.
3) See, that file is already considered as changed.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:28.220Z)
OS version: Linux ia32 4.4.0-124-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|1.97GB (0.64GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.2.4
cpptools|ms-|0.17.0
code-spell-checker|str|1.6.10

</details>

**Comment by bpasero** [comment]
@CherkashinSergey can you share a video how this looks like?

**Comment by CherkashinSergey** [comment]
![filechanging](https://user-images.githubusercontent.com/16877939/39937141-7caa8bb6-5557-11e8-99f4-3daf44955782.gif)

**Comment by bpasero** [comment]
@CherkashinSergey could it be that somehow you execute "Paste" too? Can you run the command "Compare active file with saved" to find out the diff?

**Comment by gombosg** [comment]
I'm having the same issue on Fedora 28. "Middle click paste" is disabled in GNOME Dconf (`org.gnome.desktop.interface gtk-enable-primary-paste=false`) but AFAIK this only affects GTK apps (middle-click paste still works in terminal windows) and there could be a separate Electron setting, too.

E.g. in Firefox, it has to be disabled in `about:config` (`middlemouse.paste` property).
In Chromium it's enabled by default and I haven't found a similar configuration value to disable it. :disappointed: 

Middle-click paste is something of a default behavior for *NIX systems, but apparently this can cause conflicts.

**Comment by cjhowe7** [comment]
If you have something in your clipboard, it will paste it as well. There's no way to disable this behavior in X, so the middle click column selection feature is unusable on Linux (Code doesn't run under Wayland afaict).

**Comment by ivanstepanovftw** [comment]
Middle click works well in IDEA under X, but not in OSS...

**Comment by ivanstepanovftw** [comment]
![image](https://user-images.githubusercontent.com/8203898/66233334-c949a900-e6f3-11e9-9c36-23191da84e9a.png)

**Comment by ivanstepanovftw** [comment]
![ezgif-3-8ce242c8dcb2](https://user-images.githubusercontent.com/8203898/66233369-da92b580-e6f3-11e9-92da-e9803b5ab569.gif)
