### ISSUE TITLE
File Explorer display bug

### ISSUE THREAD

**Issue by xuefengchang** [Microsoft/vscode#49691]
- VSCode Version:  1.23.1
- OS Version:  macOS 10.12.6

Steps to Reproduce:

1. modify any file, the color of the file will change as well as the folder it belongs to;
2. undo all modifications to this file，the color of the file is still the state after it was modified.

I think that after all the changes to the file have been revoked, it should not keep the modified state.
Thanks!

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Please share the project with us because this isn't happening with my sample project
