### ISSUE TITLE
Crash every few minutes

### ISSUE THREAD

**Issue by Izion** [Microsoft/vscode#497]
Code seems to be crashing on me every few minutes, occasionally it will last an hour or so but then locks up not saving any work and suggests I restart the program. Not had this issue before it seems to have come with the last update but It doesn't report any error message to send over is there anything I can provide to help narrow down the cause?

Code 0.10.1

Processor	Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
Video Card 1	AMD Radeon R9 200 Series
Video Card 2	Intel(R) HD Graphics 3000
Memory	16 GB
Operating System	Microsoft Windows 7 Professional Edition Service Pack 1, 64-bit

**Comment by h2u** [comment]
I think you need to read this issue: #160

**Comment by Izion** [comment]
Thanks h2u, I did have a read through but missed this one sounds like my problem will close this post :)
