### ISSUE TITLE
Webstorm like Navigation for Angular Projects

### ISSUE THREAD

**Issue by arangates** [Microsoft/vscode#49702]
When we click on a Variable or function name Webstorm shows the usages across the files ...this is the most important feature of Webstorm that no editor has yet .This feature facilitates  faster debug time and easy to navigate between files especially when we have Component architecture and files has Parent child relationships and they share data between them. 

```  @Input() public comment: boolean;

  public FieldType = FieldType;

  @Input()
  public set errors(errors: any) {
    this._errors = errors;
  }

  public get errors() {
    return this._errors;
  }

  @Input() public namePostfix = '';
  @Output() public dynamicChoices = new EventEmitter<Array<string>>();
```
![screenshot from 2018-05-11 16-27-16](https://user-images.githubusercontent.com/7692801/39929400-3af890d8-5538-11e8-9d94-0432347a3483.png)

**Comment by mjbvz** [comment]
The `Find all references` command does this. If you don't see it working as expected, please provide a small example project
