### ISSUE TITLE
Workspace does not respect `editor.formatOnSave` config from folder settings

### ISSUE THREAD

**Issue by samijaber** [Microsoft/vscode#49708]
- VSCode Version: 1.23.0
- OS Version: Mac OS 10.13.4

Steps to Reproduce:

1. Have the following config in your folder settings:
```js
 {
   "[javascript]": {
        "editor.formatOnSave": true
    },
    "[javascriptreact]": {
        "editor.formatOnSave": true
    },
    "[typescript]": {
        "editor.formatOnSave": true
    },
    "[typescriptreact]": {
        "editor.formatOnSave": true
    },
    "prettier.eslintIntegration": true,
    "eslint.validate": [
      "javascript",
      "javascriptreact",
      "typescript",
      "typescriptreact"
    ],
}
```

2. create a workspace that includes this folder, do not specify anything in the settings.
3. edit a file in said-folder and try to save it. I am using the `Prettier - Code Formatter` with ESLint extensions in this case to format.

Observed Behaviour: File does not format on save.
Expected Behaviour: File formats on save, as file settings are meant to override workspace settings

Does this issue occur when all extensions are disabled?: Irrelevant, since this is tied to extensions formatting on save.

NOTE: The only way I can work around this is by copying the following subset of my folder settings into my workspace settings:

```js
{
   "[javascript]": {
        "editor.formatOnSave": true
    },
    "[javascriptreact]": {
        "editor.formatOnSave": true
    },
    "[typescript]": {
        "editor.formatOnSave": true
    },
    "[typescriptreact]": {
        "editor.formatOnSave": true
    },
}
```

**Comment by mjbvz** [comment]
If you disable prettier and eslint, does the built-in JavaScript and TypeScript formatter get run in this case?

**Comment by didacrios** [comment]
Hi all, same problem here

**Code**
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**OS**: Microsoft Windows 10 Enterprise  
**Version**	10.0.15063 Build 15063

**Installed extensions:** 
dawhite.mustache - Syntax highlighting for mustache

**Steps to Reproduce:**

Set this json in ``./.vscode/settings.json`` (Folder Settings)

```json
{
    "editor.formatOnSave": true,
    "editor.trimAutoWhitespace": true,
    "html.format.wrapAttributes": "force-aligned",
    "html.format.contentUnformatted": "pre",
    "html.autoClosingTags": true,
    "[javascript]": {
        "editor.formatOnSave": false,
    },
    "[html]": {
        "editor.tabSize": 2,
        "editor.detectIndentation": false
    },
    "[mustache]": {
        "editor.tabSize": 2,
        "editor.detectIndentation": false
    }
}
```
Create sample JavaScript file and HTML ``sample.js`` and sample.html in the folder Project

    ./sample.js
    ./sample.html

Write some HTML and JavaScript

**Observerd behaviour:**
HTML code is formatted
JavaScript code is formatted

**Expected behaviour:**
HTML code be formatted
JavaScript remain unformmated

If I use this folder settings in the workspace settings ```./sample-project.code-workspace`` it Works as expected

**Comment by hunhejj** [comment]
Same here. 
@mjbvz Disabled eslint & Prettier, but it still did not get formatted on save.

**Comment by hunhejj** [comment]
When opening the folder directly, it is working as expected. Hence there is no problem with the settings itself.

**Comment by hunhejj** [comment]
@mjbvz What other info do you need in order to investigate this issue?

**Comment by jrieken** [comment]
@sandy081 This is how I ask for the configuration, I think that's correct: https://github.com/Microsoft/vscode/blob/63102e94c3e05d34e205f1b56496bb253c8b2ce4/src/vs/workbench/api/electron-browser/mainThreadSaveParticipant.ts#L208

**Comment by sandy081** [comment]
Looks correct

**Comment by sandy081** [comment]
Looks like override identifier settings are not working in folder settings.
