### ISSUE TITLE
Live share search for file broken

### ISSUE THREAD

**Issue by loctrice** [Microsoft/vscode#49703]
When you connect to a share session, you can't navigate to file by name/search. 

- VSCode Version: 1.23.0
- OS Version: Mac High Sierra 10.13.4

Steps to Reproduce:

1. Connect to shared workspace
2. cmd + p 
3. Type any partial or complete file name - no instances found

**Comment by roblourens** [comment]
This isn't supported yet but it will probably be enabled by https://github.com/Microsoft/vscode/issues/47058
