### ISSUE TITLE
When specified "editor.wordHighlightBackground", word selection highlight color is not displayed or is faintly displayed.

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/vscode#49700]
- VSCode Version: 1.23
- OS Version: Windows 7 Enterprise LTS

### Easiest Steps to Reproduce:

1. In any JavaScript file, click on a word that is commonly used, like `try`, `catch`, `for`, or `null`. Somehow, `let`, `var`, `=>`, and `function` cannot be highlighted. (Separate issue I guess)
2. Once the highlighted word is lit up, hold `Shift` key, and press `Left Arrow` or `Right Arrow` keys to start selecting the letters in the highlighted word.
3. Observe it's difficult to see the `"editor.selectionHighlightBackground"` color.

### Expected results:

Customized user settings that specified `"editor.selectionHighlightBackground"` should override whatever selection highlighting colors in the VS Code, and should highlight the selection based on the user settings even when `"editor.wordHighlightBackground"` is kicking in.

Or something that would at least make word selection more visible while the word highlighting color is displayed.

### Actual results:

![gif](https://user-images.githubusercontent.com/6444116/39927657-f90767a8-5500-11e8-8b57-d30f2688ca2b.gif)

You can hardly see what I'm selecting when the word highlight color is shown / lit up.

### My User Settings:

```json
{
	"beautify.config": "C:\\workspace\\.vscode\\.jsbeautifyrc",
	"bracketPairColorizer.forceUniqueOpeningColor": true,
	"bracketPairColorizer.timeOut": 0,
	"diffEditor.renderSideBySide": false,
	"editor.cursorStyle": "line-thin",
	"editor.detectIndentation": false,
	"editor.fontFamily": "Consolas, 'DejaVu Sans Mono', 'MingLiU', 'Meiryo', monospace",
	"editor.fontSize": 11,
	"editor.insertSpaces": false,
	"editor.renderWhitespace": "all",
	"editor.tabSize": 3,
	"eslint.options": {
		"rules": {
			"requireParamDescription": false,
			"requireReturnDescription": false
		}
	},
	"html.format.indentInnerHtml": true,
	"typescript.experimental.syntaxFolding": true,
	"window.restoreWindows": "all",
	"workbench.colorCustomizations": {
		"editor.selectionBackground": "#14a",
		"editor.selectionHighlightBackground": "#733",
		"editor.wordHighlightBackground": "#660",
		"editorCursor.foreground": "#fff"
	},
	"workbench.startupEditor": "newUntitledFile",
}
```

**Comment by aeschli** [comment]
Always use transparency for selection and highlight colors. That way you can distinguish overlapping ranges.

I've documented that in the hover description for the impacted colors as well as in the [color spec](https://code.visualstudio.com/docs/getstarted/theme-color-reference).

**Comment by tommai78101** [comment]
@aeschli I used CTRL+F to search for transparency, but there are only 2 places mentioning about transparency at: `sideBar.dropBackground` and `panel.dropBackground`. None of the `editor` related options mentioned anything about transparency.

And also, the entire article never mentioned if Visual Studio Code uses ARGB, or RGBA color scheme format. I don't know what format to use?

**Comment by aeschli** [comment]
The colors that should have transparency say: `The color must not be opaque to not hide underlying decorations`.

I'll add that the supported color formats are `#RGB`, `#RGBA`, `#RRGGBB` and `#RRGGBBAA`

**Comment by tommai78101** [comment]
Thanks @aeschli .
