### ISSUE TITLE
Syntax highlighting isn't working on one Javascript file

### ISSUE THREAD

**Issue by tccolin70** [Microsoft/vscode#49705]
Issue Type: <b>Bug</b>

Hi. I tried to open my JavaScript file, and for some reason all the lines were blue instead of having their syntax highlighted

![image](https://user-images.githubusercontent.com/29287920/39932294-0cd3cbb6-5540-11e8-9cc7-82eacc446ad2.png)

however, this other javascript file which is in the same folder is properly highlighted

![image](https://user-images.githubusercontent.com/29287920/39932464-840d8366-5540-11e8-948c-e484417b6275.png)

I have tried everything. from restarting to uninstalling all my extentions. i even reinstalled VSCode. but nothing appears to work.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (4.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.1.0
unity3d-pack|dim|1.0.0
beautify|Hoo|1.3.0
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.0
unity-code-snippets|kle|1.1.0
csharpfixformat|Leo|0.0.69
unity-snippets-modified|lio|0.4.0
csharp|ms-|1.15.0
vscode-code-outline|pat|0.2.0
111-unity-csharp-extensionpack|pen|2.0.0
vscode-unitymeta|PTD|0.0.3
project-snippets|reb|0.5.0
vscode-icons|rob|7.23.0
shader|sle|1.1.3
ayu|tea|0.14.0
unity-tools|Tob|1.0.3
unity-debug|Uni|1.3.0
change-case|wma|1.0.0
unity-snippets|Ycl|0.1.2
mono-snippets|zra|0.0.2

</details>

**Comment by mjbvz** [comment]
Please share the text of the code in those screenshots

**Comment by tccolin70** [comment]
here's the glitchy code

[buggy code.zip](https://github.com/Microsoft/vscode/files/1996730/buggy.code.zip)

**Comment by mjbvz** [comment]
That's no javascript. What language are you using?

**Comment by tccolin70** [comment]
Unityscript, but the syntax highlight works as the two languages are pretty similar. i've been using vscode as my main editor for over half a year now with unity projects, and never had any problem with it

**Comment by mjbvz** [comment]
Sorry but our built in js grammar targets standard javascript and may or may not work for other dialects. Try looking for an extension that provides a proper Unityscript grammar

**Comment by tccolin70** [comment]
While it isn't true standard javascript the syntax is very similar, your js grammar works with it, the second screenshot and all this time i spent using it proves it. 

it's not the special quirks of UnityScript which are broken. in fact, those used to work fine. 

it's just that there's one single file, with no difference in syntax from another UnityScript file (which works completely okay as you can see in the second screenshot) that has its syntax highlight turned off/glitched and i can't figure out why. 

i have done a bit more ressearch and copy/pasting code that *does* get syntax highlighted in other files, doesn't highlight it when it's pasted in this file. 

is there a master switch that can enable/disable syntax highlighting on a single file?
If not, then i'm afraid your syntax highlighter might have a little bug causing it not to work on random files.

Also, there's no UnityScript extension, for the simple reason that the JS/TS extension works fine with it.

**Comment by tccolin70** [comment]
sorry to bump this thread but apparently getting rid of the "import" line near the beggining seems to fix the issue.
