### ISSUE TITLE
Missing "Organize Imports" action on 1.24

### ISSUE THREAD

**Issue by Nxt3** [Microsoft/vscode#49710]
- VSCode Version: 1.24.0-insiders (May 11)
- OS Version: 10.12.6

I was using VS Code 1.23 (April 2017 stable) and then switched to VS Code Insiders. I no longer have the `Organize Imports` action. If I disable all extensions in VSC Insiders, the option reappears. ~~However, if I go back to VSC 1.23 WITHOUT disabling extensions, `Organize Imports` is still an action that is available.~~

If I'm using Typescript v2.8.3, `Organize Imports` is there. If I use Typescript v2.7.2, `Organize Imports` doesn't exist.

Does this issue occur when all extensions are disabled?: **No** (VSC Insiders)

**Comment by mjbvz** [comment]
This is by design. Only TS 2.8+ supports organize imports
