### ISSUE TITLE
Tabs inserted at wrong position / caret moved to the wrong position

### ISSUE THREAD

**Issue by jonas-k** [Microsoft/vscode#49717]
- VSCode Version: 1.23.1 (also present in older versions)
- OS Version: macOS 10.12

Steps to Reproduce:

Open a TypeScript file
Set indentation to tab
Set autoformatter to format braces to the next line (not sure if necessary)
Enter "class foo"
Press enter.
Expected result: (caret is denoted as "|")
```
class foo
|
```
or
```
class foo
<tab>|
```
Actual result:
```
class foo
|<tab>
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
I can't reproduce this issue with latest version.

![typescript-enter](https://user-images.githubusercontent.com/876920/45064346-175f2980-b068-11e8-8737-448838a68bde.gif)

Close it for now and we can reopen if you can still reproduce and can provide more information.

**Comment by jonas-k** [comment]
I can confirm that with the latest version the issue is resolved. Thank you.
