### ISSUE TITLE
unable to hit breakpoint from VS Code v1.23.1

### ISSUE THREAD

**Issue by jkristia** [Microsoft/vscode#49715]
Issue Type: <b>Bug</b>

With latest update v1.23.1 I can no longer hit breakpoints in VS Code.
The work around is to set the breakpoint in Chome Devloper Tools. Once hit, I can step the code and inspect variables in VS Code.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (21.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
tslint|eg2|1.0.28
rest-client|hum|0.18.4
vs-color-picker|lih|0.7.0
python|ms-|2018.4.0
csharp|ms-|1.15.1
debugger-for-chrome|msj|4.4.3

</details>

**Comment by roblourens** [comment]
Are you debugging Node or Chrome? Did it work in 1.22? Can you provide any more details about your project, or can you share it?

**Comment by jkristia** [comment]
I'm debugging in Chrome. As I mentioned, setting the breakpoint in Chrome Developer Tools makes VS Code hit the break point and then from there I can step in VS Code and inspect variables. However, I cannot set other breakpoints in VS Code, they show as disabled. This worked before I upgraded.
I cannot share the project, but the project was initially created using angular cli (it is now rather large).

The launch configuration is :
`	"configurations": [
		{
			// google-chrome --remote-debugging-port=9222 http://localhost:4200
			"name": "Attach Chrome",
			"type": "chrome",
			"request": "attach",
			"port": 9222,
			"url": "http://localhost:4200/*",
			"sourceMaps": true,
			"webRoot": "${workspaceRoot}",
			// "trace": true,
			"sourceMapPathOverrides": {
				"webpack:///*":"/*"
			}
		},
`

**Comment by roblourens** [comment]
This probably isn't caused by vscode. A change in your project or the chrome extension is more likely.

Check that your sourceMapPathOverrides is still correct - if you remove that property, does it work? If you run the `.scripts` command in the debug console, does it show your sources being resolved correctly to paths on disk?

**Comment by jkristia** [comment]
I apologize. This is not VS Code related.
I tried with v1.22.2 on the same branch of our project. Same issue.
I tried v1.23.1 on our release branch and there it works correct.

**Comment by jkristia** [comment]
Update. Removing `"sourceMapPathOverrides": { "webpack:///*":"/*" } },` from the launch config solved my issue.
