### ISSUE TITLE
Breakpoints checkboxes should toggle on clicking the label

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#49711]
- Click the "All Exceptions" or "Uncaught Exceptions" labels
- Row is selected but their state stays the same

I usually expect this to toggle the checkbox too.

**Comment by isidorn** [comment]
Would you expect this behavior only for Exception Breakpoints or for all breakpoints (function, source)?

**Comment by roblourens** [comment]
I forgot about source breakpoints, it might make sense to keep it consistent and close this issue...

**Comment by isidorn** [comment]
I could be convinced to only have this behavior for Exception breakpoints.
However nobody else complained about this.

Thus closing for consistency for now. Thanks
