### ISSUE TITLE
VS Code's Editor Window Does Not Show/Launch (Sometimes)

### ISSUE THREAD

**Issue by sgtoj** [Microsoft/vscode#4971]
- VSCode Version: 0.10.14-insider & 0.10.11
- OS Version: Win10 Build 14279

Steps to Reproduce:

1. *Using and Closing VS Code (Standard or Insider)?*
2. (Re-)Launching VS Code

VS Code (Standard and Insider) will sometimes not show the IDE Window when launch. There are ~4x Code.exe or Code-Insider.exe process that show running in Task Manager. Beside rebooting, the only workaround I have found is deleting the files and directories in '...\AppData\Roaming\Code - Insiders\' or '...\AppData\Roaming\Code\' then relaunching it. 

What I have noticed is, CodeHelper.exe is never launched with the Code.exe or Code-Insider.exe when I am experiencing this issue.

I cannot find any debug/verbose log for VS Code or associated events in the Windows Event Log.

**Comment by bpasero** [comment]
Can you try to run VS Code in verbose mode? 
* find the Code.exe in the programs folder
* execute `code.exe --verbose`

When you run the second instance you can do the same and it should print something to the console (as well as the first instance should print something).

**Comment by sgtoj** [comment]
I will do.

**Comment by sgtoj** [comment]
Ran in the problem again. Here is the verbose output when trying to launch Code Insider after experiencing the problem. 

```
### VSCode main.js ###
c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app { pathArguments: [],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  pluginHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }
Lifecycle#unload() 1
```

VS Code released version is able to launch without any issues. However, this issue has happen to VS Code release in the past. 

Attached the VS Code Crashes log. The last write time of the log is about the same time I closed it. 

Attachments: 
[operation_log.txt](https://github.com/Microsoft/vscode/files/206253/operation_log.txt)

**Comment by sgtoj** [comment]
I decided to keep the `"Code - Insider.exe" --verbose` running and kill each of instant of Code via Task Manager. After the killing one of the process, the VS Code Insider launch with a popup saying it had crashed. It then preceded to reload properly. 

Here is the verbose logging recorded when doing so...

```
C:\Program Files (x86)\Microsoft VS Code Insiders>
### VSCode main.js ###
c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app { pathArguments: [],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  pluginHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }
Lifecycle#unload() 1
"Code - Insiders.exe" --verbose

C:\Program Files (x86)\Microsoft VS Code Insiders>
Sending env to running instance...
[VS Code]: render process crashed!
[uncaught exception in main]: Error: write EPIPE
Error: write EPIPE
    at exports._errnoException (util.js:837:11)
    at Socket._writeGeneric (net.js:675:26)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at e.send (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\electron-main\main.js:6:12276)
    at new e (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\electron-main\main.js:6:2769)
    at Server.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\electron-main\main.js:6:12849)
[13796:12340:0406/070327:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
[13796:12340:0406/070327:VERBOSE1:crash_service.cc(142)] window handle is 00350356
[13796:12340:0406/070327:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at C:\Users\Brian\AppData\Local\Temp\VSCode Crashes
[13796:12340:0406/070327:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\Brian\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[13796:12340:0406/070327:VERBOSE1:crash_service_main.cc(84)] Ready to process crash requests
[13796:9168:0406/070327:VERBOSE1:crash_service.cc(323)] client start. pid = 18644
[13796:9168:0406/070327:VERBOSE1:crash_service.cc(323)] client start. pid = 1704
[18936:18736:0406/070327:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
[18936:18736:0406/070327:VERBOSE1:crash_service.cc(142)] window handle is 002012D6
[18936:18736:0406/070327:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at C:\Users\Brian\AppData\Local\Temp\VSCode Crashes
[18936:18736:0406/070327:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\Brian\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[18936:18736:0406/070327:ERROR:crash_service.cc(301)] could not start dumper
IPC#vscode-workbenchLoaded
```

**Comment by bpasero** [comment]
@sgtoj wait, are you saying it works with latest stable but not with insiders? or with a previous version?

I suggest to not kill code processes while one is running this might easily bring the other done.

Best would be a setup where one instance runs clean (no other instance) with "--verbose" and when you open the second instance see if anything is being output to the console for the second instance.

Here is what you should get if the second instance is successfully talking to the first:

First Instance
```
(4:03:16 PM) Received data from other instance { pathArguments: [ '/Users/bpasero/Development/monaco' ],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugExtensionHostPort: 5870,
  logExtensionHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  disableExtensions: false,
  waitForWindowClose: false }

```

Second Instance
```
(4:03:16 PM) Sending env to running instance...
(4:03:17 PM) Sent env to running instance. Terminating...
```

**Comment by sgtoj** [comment]
I will do that when it happens again.

**Comment by sgtoj** [comment]
@bpasero The Insider version is my main tool. However, I had the same issue with the stable release too. Last time it happened with the stable release, it prompted me to create this issues.   

Here is the result of the process you said to follow when it occurred. I have tested it a few times, the second instant never gets past `Sending env to running instance...`

```
c:\Program Files (x86)\Microsoft VS Code Insiders>
### VSCode main.js ###
c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app { pathArguments: [],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  pluginHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }
Lifecycle#unload() 1
"Code - Insiders.exe" --verbose

c:\Program Files (x86)\Microsoft VS Code Insiders>
Sending env to running instance...
```

**Comment by bpasero** [comment]
I wonder if this is something caused by your insiders build of Windows (Win10 Build 14279). What seems to happen is that the second instance cannot talk to the first via the named pipe we establish.

**Comment by sgtoj** [comment]
@bpasero If you want to close this, feel free to do so. Although I haven't used Code as much as I normally since updating to the latest Windows Insider fast build, I haven't seen the issue since upgrading. If the issue occurs again, I will create a new issue.

**Comment by bpasero** [comment]
:+1:
