### ISSUE TITLE
Group similarly-named files into a virtual folder

### ISSUE THREAD

**Issue by fpintos** [Microsoft/vscode#49721]
Issue Type: <b>Feature Request</b>

Add the hability to group multiple files from a single file-system folder into a virtual folder in the tree view.

This would be similar to the effect that Visual Studio does when an msbuild item has a <DependentUpon> tag, for example, with WinForms controls and T4 templates.

For example:
- In a Typescript React application using Sass we often have several .tsx and .scss files in a single folder. They are usually named Foo.tsx and Foo.scss. These files can be viewed as a single logical entity, so it would be nice if they were to show as a single 'Foo' item in the tree by default. 

Clicking this virtual item would open the primary file (tsx in this case, I suppose we would need rules to decide which file is the primary given a set of files).

The item would appear with the expand button next to it, so if one wants to edit the other items one can expand and interact with each individual file.

And obviously there would be a setting to control this, because I imagine some people might prefer the flat list as it is today.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment]
I think there are similar feature requests like this. Please search our repository for issues with tag file-explorer and you will find it.

**Comment by fpintos** [comment]
Ok, found the main one.
#6328
