### ISSUE TITLE
Documentation 'Bug' in Interactive Playground

### ISSUE THREAD

**Issue by ahsinclair11** [Microsoft/vscode#49726]
Issue Type: <b>Bug</b>

In the _Interactive Playground_ section **Rename Factoring**, the instructions tell the user to "Hit F2 while in the symbol Book to rename all instances ..." 

In fact you have to "Hit Ctrl+F2".

Minor bug, majorly great software.

Cheers

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-perl|hen|1.14.4
perl-debug|mor|0.4.1

</details>

**Comment by Tyriar** [comment]
@ahsinclair11 it should be F2 by default, do you have custom keybindings?

**Comment by ahsinclair11** [comment]
Just this one I wrote yesterday below (the whole json file)

I searched in the keybindings for F2 and it says ...
COMMAND                   KEYBINDING     SOURCE         WHEN
Change All Occurrence Ctrl+F2              Default           editorTextFocust && !editorReadonly

There's other entries for F2 with no Ctrl but they don't seem at all relevant.


// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "ctrl+k 1",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus",
        "args": {
            "langId": "perl",
            "name": "insertforeachloop"
        }
    }
]

**Comment by chrmarti** [comment]
@alexandrudima Any idea what could be going on here?

**Comment by alexandrudima** [comment]
@ahsinclair11 I cannot reproduce. When I hit <kbd>F2</kbd> in a file that supports semantical rename, I can rename the variable. e.g.:

![kapture 2018-05-15 at 10 04 16](https://user-images.githubusercontent.com/5047891/40044343-5ebc0fda-5827-11e8-8e5d-239b1de8cb52.gif)

Also, right clicking correctly reflects this for me:

![kapture 2018-05-15 at 10 05 39](https://user-images.githubusercontent.com/5047891/40044404-8f79040c-5827-11e8-80bc-a33ba3b7cf28.gif)

**Comment by jeremypeters** [comment]
Not working for me either, fresh install, MacOS 10.12.6.

F2 just turns up my screen brightness.

**Comment by alexandrudima** [comment]
@jeremypeters https://gaming.stackexchange.com/questions/18152/how-do-i-use-function-keys-on-a-mac

**Comment by jeremypeters** [comment]
Thanks - feel like a bit of an idiot now - it seems I've never had a to use a function key for anything in 5 years of owning a Macbook pro.
