### ISSUE TITLE
Possible documentation error in detailed description of the jsconfig.json project file

### ISSUE THREAD

**Issue by ioanungurean** [Microsoft/vscode#49727]
[Down Level Compilation with TypeScript Compiler](https://code.visualstudio.com/docs/languages/jsconfig#_down-level-compilation-with-typescript-compiler)

Option | Description
--- | ---
`module` | Specify module code generation. The values are "commonjs", "system", "umd", "amd", "es6", "es2015"

I might be wrong but can you explain to me what is the difference between `ES6` and `ES2015`? From what I read in the description I understand that `ES6` and `ES2015` are 2 different options which I don't think is the case right?

**Comment by mjbvz** [comment]
I believe these are the same here. ES6 was the originally supported value. ES2015 was added for consistency with new Ecmascript releases (es2016, es2017, ...)
