### ISSUE TITLE
Extend/Override Icon Theme Associations

### ISSUE THREAD

**Issue by p0lar-bear** [Microsoft/vscode#49725]
Issue Type: <b>Feature Request</b>

There doesn't seem to be any way to add to or override associations for icon themes.

The Seti icon theme has an icon for Nunjucks templates, and then I went and downloaded the Nunjucks extension to add the `nunjucks` language to my Code instance. My client has a server configuration set up where the server is allowed to serve a very strict whitelist of file types based on extension, so to work around it, I've named my nunjucks template files as `*.njk.html` and set up my file associations so `*.njk.html` files are associated with the `nunjucks` language. However, the icons for the files associated with `nunjucks` appear with the generic text file icon.

Digging deeper, I've deduced that icon associations are handled solely by the icon theme's config file at the moment and there is no apparent way to change or add to an existing icon theme's `fileExtensions` or `languageIds` (please correct me if I'm wrong, I've been digging all over the place for info), be it via user/workspace settings or other extensions. In this case, Seti doesn't have an entry in its `languageIds` for the `nunjucks` language, so vscode determines that the icon must be the generic one.

And my guess is that exposing an API for this via config or other extensions has the potential for issues, given that it seems there is no set standard for `iconDefinitions` identifiers.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

**Comment by aeschli** [comment]
It's actually the same request as #47432.
When generating the seti theme we should also generate language associations for non-built in languages.

**Comment by p0lar-bear** [comment]
Fair, though I still think it may be worthwhile to look into formally defining/standardizing icon theme components like `iconDefinitions`  and expected `languageIds` now that icon themes have been out in the wild for a while. An API for icon definitions would allow users to tweak edge cases like mine, language extension developers to provide "default" icons for their language, or community members to offer patches for existing icon themes as opposed to waiting for the icon theme developers to add X language to their manifest.
