### ISSUE TITLE
Support FileSystemProvider  with vscode cli

### ISSUE THREAD

**Issue by liximomo** [Microsoft/vscode#49731]
I am working on an [extension](https://marketplace.visualstudio.com/items?itemName=liximomo.remotefs) that providing several file system schemes(sftp, ftp). It would be great that FileSystemProvider can  working through CLI:

```
code sftp://myhost/path/file_or_dir
```

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/34770
