### ISSUE TITLE
folder name exists conflict bug

### ISSUE THREAD

**Issue by ycjcl868** [Microsoft/vscode#49734]
## ScreenShot

![image](https://user-images.githubusercontent.com/13595509/39953185-e1044076-55d8-11e8-9d30-3e289fecca9f.png)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. create new `view` folder(or other name) If don't exist folder.
2. change the `view` folder name to `views`
3. change the `views` to `view`  (The bug might be re reproduced)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by harryi3t** [comment]
I just like to add that opening vscode with `code --disable-extensions` solves the issue. But, opening it normally and then disabling all the extensions manually does not.

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by ycjcl868** [comment]
@harryi3t When I `code --disable-extensions` , It still conflicted.

My VSCode version:  
![image](https://user-images.githubusercontent.com/13595509/39987483-830d0d52-5797-11e8-84d7-1ea91d99c125.png)


![image](https://user-images.githubusercontent.com/13595509/39987146-7943f21e-5796-11e8-8ea6-fbd78384aba4.png)

**Comment by harryi3t** [comment]
@isidorn Yeah this happens on vscode insiders too
![vscode_insiders_rename_folder_bug](https://user-images.githubusercontent.com/5207331/40035794-215198dc-5821-11e8-8304-e02418acf7da.gif)

**Comment by isidorn** [comment]
Good catch, thanks a lot for reporting this.
The fix will be available in tomorrow's insiders
