### ISSUE TITLE
Stop script in NPM Script Explorer

### ISSUE THREAD

**Issue by deadcoder0904** [microsoft/vscode#49738]
Feature to stop desired task in NPM Script Explorer

**Comment by egamma** [comment]
@deadcoder0904 you can terminate a running script from `Tasks>Terminate Task`, does this cover your needs?

**Comment by deadcoder0904** [comment]
A context menu on the script might be better than that. You don't need to go to the Menu bar to do it. I think that's why the NPM Explorer is made :)

**Comment by egamma** [comment]
Fair request, but you can also do it from the NPM Explorer today, just execute the script again and you will get a notification whether you want to terminate or restart the task ;-)

![image](https://user-images.githubusercontent.com/172399/40024562-fb4b608e-57ce-11e8-8eb2-02a502eae70f.png)

**Comment by texastoland** [comment]
A square stop button would be nice for long-running tasks like `start` [server] since Terminate Task takes a couple more steps (search command and pick task as I often have 2-3 running).

**Comment by deadcoder0904** [comment]
Yeah I guess. 

Since 1 script isn't going to be started twice or technically it shouldn't so a stop button  like 🔳 can replace the play button.

**Comment by texastoland** [comment]
Agreed. @egamma I used the restart task notification today. Super helpful!

**Comment by egamma** [comment]
The idea is good, there is API to track task execution. I´ll investigate.

**Comment by kresdjan** [comment]
A elegant solution I think would be to switch the play icon out with a stop (and perhaps also a refresh icon) but stop or restart a running task in the "Scripts Explorer".
