### ISSUE TITLE
Using a bad experience in vscode

### ISSUE THREAD

**Issue by hengzhao2** [Microsoft/vscode#49732]
Issue Type: <b>Bug</b>

When you start the program, it will be black screen, and you need to switch to quit the black screen, which makes it impossible for me to use vscode.

VS Code version: Code - Insiders 1.24.0-insider (987c3dccf45ef0447b7b4c52c81794fab2b6dad5, 2018-05-11T05:16:29.994Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (5.18GB free)|
|Process Argv|E:\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.48
beautify|Hoo|1.3.0
vscode-language-pack-zh-hans|MS-|1.23.4
open-in-browser|tec|1.1.0
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by Tyriar** [comment]
I think I can reproduce in today's build:

![image](https://user-images.githubusercontent.com/2193314/40005490-e1fed12e-574c-11e8-95dd-e3f6a5aad0e0.png)

**Comment by Tyriar** [comment]
`code-insiders --disable-gpu` seems to work around the problem.

**Comment by Tyriar** [comment]
The problem seems to have gone away after locking the PC and logging back in 2 hours later 😕
