### ISSUE TITLE
Cannot input Chinese

### ISSUE THREAD

**Issue by JianYongChan** [Microsoft/vscode#49733]
Issue Type: <b>Bug</b>

I cannot input Chinese in the VS-code downloaded by using snap on Ubuntu 18.04 LTS, while the one downloaded from the official website works well!

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2620)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.70GB (0.29GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.15.0
vscode-language-pack-zh-hans|MS-|1.23.4
vscode-great-icons|emm|2.1.31
mysql-syntax|jak|1.3.1
easy-icons|jam|0.3.1
Lua|key|0.0.9
cpptools|ms-|0.17.0
java|red|0.24.0
vscode-icons|rob|7.23.0
markdown-preview-enhanced|shd|0.3.5
vscode-lua|tri|0.12.4
vim|vsc|0.11.6
markdown-all-in-one|yzh|1.3.0

</details>

**Comment by Tyriar** [comment]
We don't support the snap package yet.
