### ISSUE TITLE
Bug feedback

### ISSUE THREAD

**Issue by CyshallChan** [Microsoft/vscode#49735]
- VSCode Version:1.23.1
- OS Version:Windows10 1803

Each time reopen VSCode,  will pop up release notes page,Very annoying.

Steps to Reproduce:

1.Close all vscode windows.
2.Reopen vscode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deadcoder0904** [comment]
Can't confirm. Doesn't happen on Mac OS latest release. No Insiders build.

**Comment by iamCristYe** [comment]
Doesn't happen on latest Windows stable build.

**Comment by deadcoder0904** [comment]
Ohh @CyshallChan I never said it doesn't happen on yours. I said it doesn't happen on my Mac. I believed you :)

**Comment by iamCristYe** [comment]
@CyshallChan So sorry this happens on your machine. Have you tried reinstalling?

**Comment by CyshallChan** [comment]
@iamCristYe  Yes,three times.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by CyshallChan** [comment]
Solved after Reinstall the system，Thank you all for your help.
