### ISSUE TITLE
Auto close feature for command palette should be changed. 

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4973]
I personally feel it is annoying when command palette closed automatically without any user action on editor window. It is common use case when user switch focus to the other app and come back to VSCode.
In my case:
1. I generally switch to outlook by clicking on email pop-up alert.
2. When I launch the picker (extension window) and want to read about extension before installing it (moved from VSCode to browser window after clicking on Readme).

- VSCode Version:0.10.12-alpha
- OS Version: All

Steps to Reproduce: 

1. Launch app and the press F1 or click on the status bar to open the picker.
2. Now switch focus to other app and come back to VSCode.

Actual: Command palette is auto closed when user switch to the other app.
Expected: Instead of auto close we should allow the user to perform close action by clicking anywhere outside the picker.
![image](https://cloud.githubusercontent.com/assets/17735796/14293997/db0f9c68-fb23-11e5-8cb8-4183d9d5484b.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/444
