### ISSUE TITLE
Highlighted indent guides not working in 'light themes'

### ISSUE THREAD

**Issue by Stephanevg** [Microsoft/vscode#49745]
- VSCode Version:
1.23.1
- OS Version:
Windows 10

Steps to Reproduce:

1. try the Highlighted indent guides in a dark theme. It works
2. try Highlighted indent guides on a light theme (like powershell ISE theme for example) and it doesn't
3. Switch back to a dark theme, and it works again.

**Comment by alexandrudima** [comment]
The highlighted indent guide is configurable via a color.

https://code.visualstudio.com/updates/v1_23#_highlighted-indent-guides

Perhaps the theme you are using did not yet update to use the new color. You can workaround on your side by using color customizations:

```
"workbench.colorCustomizations": {
    "editorIndentGuide.activeBackground": "#ff0000"
}
```
