### ISSUE TITLE
Cannot `Go to Next Symbol Highlight` after `Go to Symbol in File`

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#49743]
Go to symbol `variable`:
```javascript
const variable = 1;
// ----------
// ----------
console.log(variable);
```
Right after that I can't execute `editor.action.wordHighlight.next` because the symbol is not highlighted.
If I just put cursor before `variable` by clicking, symbol is highlighted and command executes.

Also doesn't work after: `Go to Symbol in Workspace`, `Go to Definition`, `Find All References` => and go to next symbol ... probably some others.

I tried removing `hasWordHighlights` condition from the keybinding but had no luck.

Actually, `Find All References` <kbd>Shift</kbd>+<kbd>F12</kbd> & `Go to Definition` <kbd>F12</kbd> work without symbol highlight and I think commands  `Go to Next Symbol Highlight` & `Go to Previous Symbol Highlight` should work that way too (but be no-op if there is no symbol under cursor).

---

OS version: Windows_NT x64 10.0.16299

**Comment by usernamehw** [comment]
Yes, reproduces.

I don't think workspace structure is related in any way to the issue. It's a single file.

Are we talking about the same command? `editor.action.wordHighlight.next`

**Comment by mjbvz** [comment]
Yes, here's what I see:

![may-14-2018 08-51-11](https://user-images.githubusercontent.com/12821956/40008386-07f03fc4-5754-11e8-96d0-f1d0f47724f4.gif)

**Comment by mjbvz** [comment]
Ok, need to run go to symbol first. Can repo now

**Comment by mjbvz** [comment]
Not language specific. I can repo in python and css as well

@alexandrudima / @rebornix Assigning you as I'm not sure of the proper owner here. Please reassign to the correct owner

**Comment by alexandrudima** [comment]
The word highlighter computes occurences only if the editor cursor is explicitly set via the mouse (clicking) or via the keyboard (left cursor, right cursor), and not if the cursor is set programmatically.
