### ISSUE TITLE
Extension API to close TextDocument

### ISSUE THREAD

**Issue by jacobdufault** [Microsoft/vscode#49740]
Similar to #48945, I'd like to be able to close an arbitrary `TextDocument`.

At the moment, there is a `hide` method on `TextEditor` but it is deprecated. The replacement is to use `workbench.action.closeActiveEditor`, which does not let me target a specific `TextDocument`.

For context, I'm writing an extension that lets the user manage a set of tabs, similar to windows in tmux.

**Comment by jrieken** [comment]
> For context, I'm writing an extension that lets the user manage a set of tabs, similar to windows in tmux.

Closing as dupe of #15178 because you'll need much more API for that.
