### ISSUE TITLE
vscode opened from terminal outputs some kind of log in the terminal itself, hitting Ctrl + C closes vscode all together

### ISSUE THREAD

**Issue by mikevoid101** [Microsoft/vscode#49744]
- VSCode Version: 1.23.1
- OS Version: Windows 10

Steps to Reproduce:

1. open terminal (hyper, bash etc.)
2. type ```$ code .``` in a project folder
3. annoying log output dumps in the terminal, hit Ctrl + C, vscode closes

Does this issue occur when all extensions are disabled?: Yes

Notes:
Loom video: https://www.useloom.com/share/2bd48b3179dd4d4b9da6657855cba491
I tested using hyper and regular bash terminals.

This happens frequently, but not all the time, I'm not sure what is triggering it. Previously, before my last windows update, when I hit ctrl+c it would just stop the output in the terminal, now it closes vscode too.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/44540
