### ISSUE TITLE
Tslint in VSCode cannot be disabled

### ISSUE THREAD

**Issue by dominikschopper** [Microsoft/vscode#49754]
- VSCode Version: 1.23.1
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. Open a pure JS Project with js/jsx files
2. Disable tslint completely or tslint.jsEnable either in User or Worspace settings
```
    "tslint.enable": true,
    "tslint.jsEnable": false
```
3. Open a js file and create a tslint error.
  VSCode is underlining the error and it only switches off,
  if I `// @ts-nocheck` ... 

This issue does not occur without extensions, since its the tslint extension I am asking about ;)

thx and keep up the good work

**Comment by egamma** [comment]
>VSCode is underlining the error and it only switches off, if I // @ts-nocheck ...

@dominikschopper this indicates to me that the error is not reported by tslint but by TypeScript. Errors reported by tslint are prefixed with `[tslint]`, errors reported by TS are prefixed with `[ts]`. Please reopen the issue when the error is prefixed with `[tslint]`.

**Comment by dominikschopper** [comment]
thx! did not get that.
