### ISSUE TITLE
stackTrace requested twice

### ISSUE THREAD

**Issue by maziac** [Microsoft/vscode#49753]
Hi,

I'm struggling with the debug adapter protocol.

When stepping over, as far as I have understood, vscode send the 'next' command to the debug request.
Then it would request the threads, the stack traces, the scopes and the variables in turn.
I can see this sequence by putting in log statements.
However, I found that the stackTrace is requested twice right after another with same parameters.

See this log (the vscode communication is in bold):

**ZesaruxDebugSession.dispatchRequest:  ->: next({"threadId":1})**
ZesaruxSocket.sendSocket:  Sent: cpu-step-over
**ZesaruxDebugSession.sendResponse:  <-: next(undefined)**
ZesaruxSocket.receiveSocket:  Received:   CDE8 INC DE
ZesaruxDebugSession.sendEvent:  <-: stopped({"reason":"step","threadId":1})
**ZesaruxDebugSession.dispatchRequest:  ->: threads(undefined)
ZesaruxDebugSession.sendResponse:  <-: threads({"threads":[{"id":1,"name":"thread_1"}]})**
**ZesaruxDebugSession.dispatchRequest:  ->: stackTrace({"threadId":1,"startFrame":0,"levels":20})**
ZesaruxSocket.sendSocket:  Sent: get-registers
**ZesaruxDebugSession.dispatchRequest:  ->: stackTrace({"threadId":1,"startFrame":0,"levels":20})**

- VSCode Version: 1.23.1
- OS Version: macOS 10.13.4

**Comment by isidorn** [comment]
Seems like a dup of https://github.com/Microsoft/vscode/issues/49670
Let's continue the discussion there
