### ISSUE TITLE
plugins only work after one hour after upgrade 1.23.1

### ISSUE THREAD

**Issue by smallnest** [Microsoft/vscode#49750]
- VSCode Version: 1.23.1
- OS Version: MacOS High Sierra 10.13.4

Steps to Reproduce:

1. upgrade vscode from 1.23.0 to 1.23.1
2. start vscode and many plugins such as git, vscode-go can't work
3. see "Developer Tools" and no errors
4. after one or two hours, those plugins can works.

The same issue occured on another macbook.

**Comment by alexandrudima** [comment]
@smallnest There is nothing *delayed* that we are doing w.r.t. extensions. I also don't understand what you mean that those plugins can't work. Can you please give more steps/information ?

**Comment by smallnest** [comment]
I  uninstalled vscode by following https://medium.com/@jimkang/complete-uninstall-remove-vscode-mac-5e48bef3bdec, and then installed 1.23.1. Now it can work so I closed  this issue
