### ISSUE TITLE
Feature request: support for extensions which need to run code in response to completion items being shown, updated or hidden

### ISSUE THREAD

**Issue by walrus95** [Microsoft/vscode#49759]
Greetings!

I’m writing to request a particular feature be added to Visual Studio Code to better support extension development. I’m looking to write an extension which runs some code every time Visual Studio Code shows, updates or hides its list of completion items to the user (also known as IntelliSense.) I would like to see API support for executing some code every time Visual Studio Code shows, updates or hides its list of completion items.

In the meantime, is there a workaround I could use to emulate this feature until support is officially added? For example, one possible workaround would be to run some code every time the user types and have that code check to see if the length of the available completion items is non-zero.

If there already exists support for running some code every time Visual Studio Code shows, updates or hides its list of completion items, I would like to request that better documentation be added to the project to highlight the existence of this feature and to illustrate its use.

Thank You.

**Comment by jrieken** [comment]
This feature doesn't exist and the primary goal of the extension API is to not expose UI internals. Instead, the API usually asks for plain data and keeps things like sorting/filtering etc private. Therefore it is very unlikely that we will ever implement something like that. 

My recommendation would be that you share the idea with us and try to land it as PR in the project itself. Thanks and Happy Coding
