### ISSUE TITLE
Code Insider does not work on mac

### ISSUE THREAD

**Issue by cadupedroni** [Microsoft/vscode#4975]
- VSCode Version: 0.10.15-insider
- OS Version: 10.11.4 (OS X El Capitan)

Steps to Reproduce:

1. Download the official website
2. Unzip the file and try to run

**Comment by Tyriar** [comment]
@cadupedroni what happens when you run it?

**Comment by cadupedroni** [comment]
The VSCode Insiders he shows at the top of the Code-but Insiders screen closes immediately.

One difference I found on now was in the folder that it creates within ~/Library/"Application Support"/Code-Insiders, have the User folder empty and the DevTools file Extensions with just []

**Comment by joaomoreno** [comment]
Does it happen if you download it and extract it again?

What application do you use for extracting?

What output do you get when running straight from the terminal?

```
/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron
```

cc @bpasero

**Comment by cadupedroni** [comment]
Thank you very much! Now worked perfectly.

The problem is permission denied.

`I ran sudo/Applications/Visual\ Studio \-\ Insiders.app \ Code/Contents/MacOS/Electron`

**Comment by cadupedroni** [comment]
Good morning
Today I went to open the Visual Studio Code and it only works if I run sudo/Applications/Visual\ Studio \ \-\ Insiders.app Code/Contents/MacOS/Electron

When I try to click the icon in the dock, the problem continues, is there any permanent solution that works by clicking on the icon of the vscode insiders?

**Comment by joaomoreno** [comment]
You might wanna delete the whole `~/Library/"Application Support"/Code - Insiders ` directory and never start Code with `sudo` again.

**Comment by cadupedroni** [comment]
I couldn't find the directory of the Code in this way

**Comment by cadupedroni** [comment]
Deleted the directory and downloaded again the Code Insiders, but the problem continues.

**Comment by cadupedroni** [comment]
The error was caused by lack of permission in the folder/Users/youruser/Library/Application Support

With the command -> sudo chmod 775

Was solved
