### ISSUE TITLE
Git changes not shown when using workspace

### ISSUE THREAD

**Issue by feugy** [Microsoft/vscode#49757]
Issue Type: <b>Bug</b>

When opening a single project versioned with git, uncommitted changes are highlighted in both file explorer and current editor.

![highlight](https://user-images.githubusercontent.com/186268/39960230-5c7053a8-561f-11e8-89d4-043c8e428c91.png)

Since version 1.23, those changes are not visible any more when opening a workspace containing this project.

![no highlights](https://user-images.githubusercontent.com/186268/39960244-860d5332-561f-11e8-9a9f-56bf3ce19aa5.png)

This used to work with previous versions.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2601)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.53GB (9.86GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.23.0

</details>

**Comment by jrieken** [comment]
Can you attached the git log (F1 > Output > Git) please. Thanks
