### ISSUE TITLE
Do not prompt to save as admin for a file after authenticated once

### ISSUE THREAD

**Issue by vvavrychuk** [Microsoft/vscode#49766]
VS Code has "Retry as Admin" feature when trying to save files with insufficient access permissions. It was discussed in http://github.com/Microsoft/vscode/issues/1614.

The problem is that this access elevation after first retry as admin is not remembered for some time and I am getting password prompt all the time. Comparing to this sudo has timestamp_timeout which controls how sudo expires.

**Comment by bpasero** [comment]
Please lobby for this over at https://github.com/jorangreef/sudo-prompt/commits/master

**Comment by fvrlak** [comment]
If your file has name `myfile.py`
than you would type
`sudo chmod 777 myfile.py` - not save thought but works
