### ISSUE TITLE
navigation hotkeys in quickOpen menu starts working after small delay

### ISSUE THREAD

**Issue by AntonPuko** [Microsoft/vscode#49765]
Hi, from one of the last versions of vscode insiders hotkeys in quickOpen menu starts working after very small delay. It's really annoying since I'm using very fast command sequence to navigate back to the previous file like: open quickopenmenu -> workbench.action.quickOpenNavigateNextInFilePicker

- VSCode Version:  1.24.0-insider
- OS Version: windows 10

Steps to Reproduce:
1. open `quickOpen` menu
2. very rapidly press a  hotkey related to the menu, for example, a bind to this command `workbench.action.quickOpenNavigateNextInFilePicker`

Does this issue occur when all extensions are disabled?: Yes

**Comment by AntonPuko** [comment]
thanks for the fast fix!

**Comment by chrmarti** [comment]
Thanks for filing the issue!
