### ISSUE TITLE
[javascript] syntax highlighting bug when object property name starts with "var"

### ISSUE THREAD

**Issue by jalipert** [Microsoft/vscode#4976]
![highlighting_bug](https://cloud.githubusercontent.com/assets/1097608/14295345/29e0b556-fb43-11e5-8a29-7fb348e0cc63.png)

- VSCode Version:0.10.11
- OS Version:Windows 10

Steps to Reproduce:

1. add a property to an object starting with the letters "var"
2. observe incorrect syntactical highlighting

**Comment by egamma** [comment]
This is fixed in the insiders build 0.10.14

You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders
