### ISSUE TITLE
VSCode Version 1.23.1 reintroduces yaml formatting bug

### ISSUE THREAD

**Issue by trondhindenes** [Microsoft/vscode#49770]
This was an error a while ago, which has resurfaced:
vscode 1.23.1 doesn't correctly indent yaml files anymore - for example, tabs places the cursor at incorrect locations for yaml

**Comment by aeschli** [comment]
@trondhindenes Can you add a small code example that shows the problem?

**Comment by trondhindenes** [comment]
I might have pulled the trigger too soon (or a restart of Code fixed it). In any case, i'm not able to repro :thinking:  so closing the issue. Thanks for responding! I'll reopen if I notice I'm able to repro at some point.
