### ISSUE TITLE
x11 forwarding for vscode

### ISSUE THREAD

**Issue by coderyangyangyang** [Microsoft/vscode#49771]
Issue Type: <b>Feature Request</b>

I always work on ssh to Linux server,but I can't use X11 forwarding to show my vscode GUI from Linux server 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3451
