### ISSUE TITLE
Extension uninstall "x" is not centered 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4977]
- VSCode Version: 0.10.12-alpha (latest)
- OS Version: Windows 10

Steps to Reproduce:

1. Open installed extensions 

![uninstallxoffset](https://cloud.githubusercontent.com/assets/12900364/14295554/04775684-fb2b-11e5-8744-e23c86754bff.JPG)

**Comment by joaomoreno** [comment]
b1572f504ea9001a28928aae6eb968259b777165 introduced this

**Comment by isidorn** [comment]
@joaomoreno checkout my fix, I am just adding maring-right to the x icon to make it nicely aligned - seems to work well for me.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/14911898/caba3b9c-0df8-11e6-8a7d-32589437cb09.png)
