### ISSUE TITLE
Emmet balance In after balance out should go back to initial selection and not first child

### ISSUE THREAD

**Issue by anantoghosh** [Microsoft/vscode#49777]
Using emmet's balance in after using balance out shrinks to incorrect selection.

**Current Behavior:**
![2018-05-13_16-10-42](https://user-images.githubusercontent.com/12339068/39966365-410363cc-56c8-11e8-8dba-d9d04fc22b94.gif)

**Expected Behavior:**
Currently balance in selects just the first child element for the selected tag. It should select in the order reverse of balance out.

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Maxhodges** [comment]
good lord why doesn't the VS code team just make this work!
https://github.com/Microsoft/vscode/issues/4795#issuecomment-346622659

**Comment by ramya-rao-a** [comment]
Thanks @Heldenkrieger01 
I have assigned it to the current milestone, and get it this week

**Comment by ramya-rao-a** [comment]
@Heldenkrieger01 I had to make some changes over your PR. Do take a look. 

The fix has been merged.

@anantoghosh @Maxhodges Can you give it a try in tomorrow's [Insiders](https://code.visualstudio.com/insiders)?

**Comment by Maxhodges** [comment]
excellent! Sure I'll be happy to test!

**Comment by anantoghosh** [comment]
Tried it out. It's working well! Thanks 😄

**Comment by ramya-rao-a** [comment]
Thanks @anantoghosh
