### ISSUE TITLE
Possibility to prevent certain sections of code being formatted by VSCode

### ISSUE THREAD

**Issue by NearAutomata** [Microsoft/vscode#49782]
I was considering to use another extension to structure my import statements into columns such as the following:
```typescript
import {    Commandlet   } from "@cli/Framework/Commandlet" ;
import {    Manifest     } from "@cli/Framework/Manifest"   ;
import {    PackageJson  } from "@cli/Framework/PackageJson";
import {    VerbsData    } from "@cli/Framework/VerbsData"  ;
import {    IPackage     } from "@cli/Schemas/IPackage"     ;
import {    IPackageJson } from "@cli/Schemas/IPackageJson" ;
import * as fs             from "fs"                        ;
import * as path           from "path"                      ;
```
Unfortunately though, running the VSCode formatter (either manually or automatically when saving) sanitizes the number of spaces and yields the following more usual output:
```typescript
import { Commandlet } from "@cli/Framework/Commandlet";
import { Manifest } from "@cli/Framework/Manifest";
import { PackageJson } from "@cli/Framework/PackageJson";
import { VerbsData } from "@cli/Framework/VerbsData";
import { IPackage } from "@cli/Schemas/IPackage";
import { IPackageJson } from "@cli/Schemas/IPackageJson";
import * as fs from "fs";
import * as path from "path";
```
I'd like to know whether there is any option available or feature planned to configure the fomatter s.t. it does not format my customized imports or other configurable sections.

**Comment by mjbvz** [comment]
This is tracked by https://github.com/Microsoft/TypeScript/issues/18261

There are no imminent plans to change the built-in JS/TS formatter, but another formatting extension may be able to preserve the formatting or reformat the code the way you are after

**Comment by NearAutomata** [comment]
@mjbvz I stumbled upon beautifier myself but the author mentions in HookyQR/VSCodeBeautify#122 that he is not going to add real Typescript support to the extension and says in multiple comments that one should rely on the VSCode formatter.

Do you have any further information on Microsoft/TypeScript#18261? Has any work been done on this or is it just untouched?

**Comment by mjbvz** [comment]
It's not high priority work for the TypeScript team but I'm sure someone would be happy to help you look into it if you are interested

**Comment by NearAutomata** [comment]
@mjbvz Unfortunately I don't have either the capacities nor the required knowledge to contribute. Most likely I'll be trying to find a workaround in the meantime using some script that will format the import groups of a file after it has been saved.
