### ISSUE TITLE
Feature Request: "Global Problem Level (warn/error)" Setting for ESLint (or any other extension/linter)

### ISSUE THREAD

**Issue by ashrafhadden** [Microsoft/vscode#49788]
- VSCode Version: v1.23.1
- OS Version: OSX 10.13.4

**Issue**
Most ESLint Shared Configs (ex. [AirBnB](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb), [StandardJS](https://github.com/standard/eslint-config-standard)) use "error" as their default rule severity. I use large eslint-config's through [vscode-eslint](https://github.com/Microsoft/vscode-eslint/issues/46) and prefer to have all of my ESLint Problems (VSCode's "Problems" Window under View menu) show up as warnings since they are almost all style-related. This allows me to keep all of my _actual_ error Problems (i.e. syntax errors) separate from my style Problems. Currently I have to find and replace all "error" with "warn" in my eslint-config's or maintain massive .eslintrc files to override all the "error"'s.

**Proposed Solution**
Add a "Global/Maximum Problem Level" option in VSCode Settings that overrides all Problem levels for a particular linter or extension that produces Problem output.

**Related Issue**
I wasn't sure which repo was more relevant to this issue so I also posted in [vscode-eslint](https://github.com/Microsoft/vscode-eslint/issues/468)'s repo.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/468
