### ISSUE TITLE
Debug provide capability to always show stack frame column indicator

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/vscode#49783]
Issue Type: <b>Bug</b>

In my debug extension it frequently happens that debugging stops in multiple positions within a line. That's why I heavily depend on proper debug position markers.

However the handling is currently not fully satisfying:

1) For the first stop on a line the debug marker is never shown:

<img width="857" alt="debug1" src="https://user-images.githubusercontent.com/2398704/39967616-09ec37b4-56bf-11e8-9a6b-a81f1238e1a9.png">

2) Well, not always as this image shows:

<img width="906" alt="debug4" src="https://user-images.githubusercontent.com/2398704/39967629-381bf5b6-56bf-11e8-8c31-ecdf0e409085.png">

, but mostly it's missing. The difference here is that in case 1) this was the first stop on that line, while for 2) we have a recursive rule, so when I step-in the debugger ends up at the first rule name (the body of a rule begins after the colon). Pretty inconsistent. The debug marker should always show unless there is no column info (however my stack traces always has column info).

3) Also within a line the marker shows up or not, depending on how a position was reached (not the position itself).

_Reached the position after stepping into `identifier` and returned._
<img width="932" alt="debug2" src="https://user-images.githubusercontent.com/2398704/39967655-b82e80ac-56bf-11e8-8d20-b3757265f6ea.png">

_Reached the position after stepping over `identifier`._
<img width="976" alt="debug3" src="https://user-images.githubusercontent.com/2398704/39967676-3e88ab96-56c0-11e8-8b38-e9580d030470.png">

4) The debug marker is not shown for non-TOS elements in a call stack and the TOS loses the marker when navigating the call stack.

![debug5](https://user-images.githubusercontent.com/2398704/39967693-bc461884-56c0-11e8-8e33-bc023fc499cb.gif)

As you can here the marker before the `identifier` rule is lost when returning after selecting other than the TOS in the stack trace. That's a pretty bad thing as you totally lose where you came from. Imagine a rule body with 20 and more sub rule invocations, spread over multiple lines, which is very common in such grammar files.

I guess 1) is implemented by intention to support languages that rarely use debug stops within a line, but I beg for an option to always show the debug markers and always respect the given column value!

Btw: you can see this behavior also with the TS debugger, e.g. when you debug a for-loop, which is one of the rare occasions where a debug position within a line is used.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (15.41GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by isidorn** [comment]
@mike-lischke thanks for your feedback.
This is currently designed behavior as you guessed correctly. I will leave this open to provide a debug adapter capability to always show a column and not be overly smart.
fyi @weinand 

Also we really like concise issues, long text takes a lot of time to read.

**Comment by mike-lischke** [comment]
> Also we really like concise issues, long text takes a lot of time to read.

Well, I reported 3 problems which are very likely all caused by the same implementation. I assumed that would make things more compact. I can create 3 individual issues instead, but I doubt that makes handling easier in any way.

**Comment by mike-lischke** [comment]
Hmm, I understand your desire to have a more automatic way to deal with feature requests, but I'm afraid this approach will mostly reject feature requests, unless they are affecting really a lot of people. The sheer amount of bugs + FRs in this repo quickly leads to entries that are hidden forever, unless someone searches specifically for this exact problem. Alone because of the way problem reports can be written, this is likely to never happen.

But of course you have to concentrate on things that are useful for most of the vscode users. As such it would be more honest to just reject an FR that you think is not of enough interest. Keep in mind that writing a good bug report or FR usually requires a fair amount of work too.

**Comment by mike-lischke** [comment]
I was afraid this would happen and I don't consider this issue a feature request, but rather a bug. The behavior is inconsistent and should be fixed.

**Comment by isidorn** [comment]
Moving to backlog. Thanks
