### ISSUE TITLE
Fix the value of ${workspaceFolder} for multi-root-workspace

### ISSUE THREAD

**Issue by myguddy** [Microsoft/vscode#49799]
- VSCode Version: 1.23.1
- OS Version: High Sierra 10.13.4

Steps to Reproduce:

1. Create simple java and configure the launch.json
     {
            "type": "java",
            "name": "Debug (Launch)-Main",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "Main",
            "args": ""
        },
2. run task
3. create multi-root-workspace
4. add the directory(step1.)
5. run task
6. error come out "java.lang.ClassNotFoundException: ...."

it needs java extension pack.
I use vscjava-vscode-pack

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
As the error says please scope your workspaceFolder, for example if your first folder in a multi root workspace is called Server use
`${workspaceFolder:Server}`
