### ISSUE TITLE
eslint and jshint extensions do not change uninstall to install button after uninstalling

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4979]
- VSCode Version: 0.10.12-alpha (latest)
- OS Version: Windows 10

Steps to Reproduce:

1. Install jshint and eslint
2. Open install extensions
3. Uninstall either or both. 

Actual:
The uninstall button remains after uninstalling. If you uninstall more than once, the dialog saying you need to restart does not show up.

**Comment by vsccarl** [comment]
Also after uninstalling multiple times and then restarting I'm getting this error:
![uninstallmultipleerror](https://cloud.githubusercontent.com/assets/12900364/14297262/cc8ed28a-fb32-11e5-8942-4d79e7ecd0a7.JPG)

**Comment by joaomoreno** [comment]
Can't really reproduce the uninstall button remaining, maybe this got fixed meanwhile?
