### ISSUE TITLE
Will VSCode upload my settings.json file ?

### ISSUE THREAD

**Issue by vikyd** [Microsoft/vscode#49797]
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1.Will VSCode upload my settings.json file ?

ref: https://code.visualstudio.com/blogs/2018/04/25/bing-settings-search

**Comment by roblourens** [comment]
Nope
