### ISSUE TITLE
Bug in renaming folder

### ISSUE THREAD

**Issue by harryi3t** [Microsoft/vscode#49792]
Not able to rename a folder back
![renaming_folder](https://user-images.githubusercontent.com/5207331/39969501-091f92b4-56fa-11e8-8162-ea7ae1781b8e.gif)

This happens only with folders and not with files.

- VSCode Version: 1.21.3
- OS Version: macOS High Sierra 10.13.4

Steps to Reproduce:

1. create a folder `test`
2. rename it to `tests`
3. try renaming it back to `test`

Does this issue occur when all extensions are disabled?: No!
I had 22 extensions enabled. I thought to help debug this issue faster I could try disabling each plugin until this issue does not happen. Sadly even after disabling each plugin and after restarting the app, the issue is still there.

**Comment by harryi3t** [comment]
Thanks 🤖 , but that is an entirely different issue 😉

**Comment by usernamehw** [comment]
Duplicate of #49734

**Comment by harryi3t** [comment]
Closing this issue in favor of https://github.com/Microsoft/vscode/issues/49734
