### ISSUE TITLE
Use the same Start Menu folder for Stable and Insiders

### ISSUE THREAD

**Issue by justalemon** [Microsoft/vscode#49796]
Issue Type: <b>Feature Request</b>

After installing Code Insiders, a separate folder will be created on the Start Menu exclusive for it:

![captura de pantalla 8](https://user-images.githubusercontent.com/11861253/39973077-ed1b46d2-56e8-11e8-9a6f-147270b512b5.png)

I think that this is a bad idea because they are *different* versions of the **same product**. Take [Discord](https://discordapp.com/) for example:

![captura de pantalla 7](https://user-images.githubusercontent.com/11861253/39973076-e792d694-56e8-11e8-955b-a59bdb9e5372.png)

One folder is used for multiple versions of the product (where PTB = Beta and Canary = Alpha).

Using the "Visual Studio Code" folder for both versions or dropping the shortcuts directly (like Visual Studio 2017) are valid options to make things clean:

![captura de pantalla 11](https://user-images.githubusercontent.com/11861253/39973293-2603ce58-56ec-11e8-831f-6892a1fb7a15.png)
![captura de pantalla 12](https://user-images.githubusercontent.com/11861253/39973294-26275b0c-56ec-11e8-8159-c933233c2a3c.png)

VS Code version: Code - Insiders 1.24.0-insider (987c3dccf45ef0447b7b4c52c81794fab2b6dad5, 2018-05-11T05:16:29.994Z)
OS version: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment]
We actually treat them as separate products. So we won't probably do this.
