### ISSUE TITLE
tasks.json arguments end unexpectedly after semicolon

### ISSUE THREAD

**Issue by hawkerm** [Microsoft/vscode#49798]
- VSCode Version: 1.23.1
- OS Version: Windows 10 16299.371

Steps to Reproduce:

1. Create a tasks.json with arguments containing a semi-colon (see below, testing with `echo`).
2. Run the task
3. Note that nothing is echoed after the semi-colon, mid argument.

If you remove the semicolon it works as expected.

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "echo",
            "args": [
                "-cp",
                "lib\\SpaceBattle.jar;lib\\gson-2.2.jar",
                "src\\${fileBasename}"
            ], 
      }]
}
```

Output:
```
-cp
lib\SpaceBattle.jar
```

If you remove the semi-colon, then you get this:

```
-cp
lib\SpaceBattle.jarlib\gson-2.2.jar
src\AvoidingShip.java
```

I would expect this output when I have the semi-colon:
```
-cp
lib\SpaceBattle.jar;lib\gson-2.2.jar
src\AvoidingShip.java
```

**Comment by dbaeumer** [comment]
The problem here is that in PowerShell ';' is a statement separator and you need to quoute that argument to prevent PowerShell to interpret this. The task framework by default only escapes/quotes spaces since it is not clear to use what the purpose of the`;` is. An example how this should look like is:

```
		{
			"label": "echo",
			"type": "shell",
			"command": "echo 'dirk;echo baeumer'",
			"problemMatcher": []
		}

```

which echos `dirk;echo baeumer`

**Comment by hawkerm** [comment]
@dbaeumer I feel like this used to work before?  Does it depend on if PowerShell is selected as the default terminal then?

**Comment by dbaeumer** [comment]
Yes, this is PowerShell sepcific. In cmd.exe `;` is not a statement separator and will very likely printed as is (I have not tested it).
