### ISSUE TITLE
Code removing "unused" imports that are actually used

### ISSUE THREAD

**Issue by ceckenrode** [Microsoft/vscode#49794]
I'm running into a problem where code seems to be removing an "unused" import that's actually being used. This happens whenever I save.

![import](https://user-images.githubusercontent.com/9385814/39972393-90826420-56dc-11e8-837f-200857580f82.gif)

In my case, it's removing `h` import on save, which is required for once the JSX is compiled, but not used explicitly in my file.

Is this a bug or a setting I can turn off?

I'm running 

Code Version 1.23.1 (1.23.1)

on Mac OS 10.13.4 

Steps to Reproduce:

Try saving this code with the `preact` npm package installed. The `h` import is removed for me, even though it is used after compilation.

```js
import { render, h } from "preact";

render(<p>Hello World!</p>, document.querySelector("#root"));
```

Thanks!

**Comment by mjbvz** [comment]
You need to tell our intellisense that you are using `h` as the react factory. To do this, create a `jsconfig.json` with the contents:

```ts
{
  "compilerOptions": {
    "jsx": "react",
    "jsxFactory": "h",
  },
  "exclude": [
    "node_modules",
    "**/node_modules"
  ]
}
```
