### ISSUE TITLE
Change the editor fallback defaults to insertSpaces: true, tabSize: 4

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#498]
I don't have a preference setting about spaces vs tabs. When I open `.travis.yml`, VSCode **always** uses tabs instead of spaces to create new indentation. This is very problematic since YAML files **forbid** tabs.

![image](https://cloud.githubusercontent.com/assets/22350/11338152/b61513e2-91f2-11e5-8a5d-78df2e7346d1.png)

I thought the editor would automatically figure out the indentation to use?

**Comment by alexandrudima** [comment]
@joaomoreno

Our project settings force the insertion of tabs:

`.vscode/settings.json`

```
// Place your settings in this file to overwrite default and user settings.
{
	"editor.insertSpaces": false, // <---- THIS IS THE ONE
	"files.trimTrailingWhitespace": true,
...
}
```

**Comment by joaomoreno** [comment]
Should this only act on when there is no definite hint about the file's indentation? E.g.: new files.

**Comment by alexandrudima** [comment]
The settings get applied by the workbench to each editor regardless the model being for an empty file or not. If this setting is left out, then the model is used for guessing. If the guessing code is not confident, it falls back to insertSpaces:false, tabSize:4. The fallback values have no configuration story. 

I think our intent here is to say: "all TypeScript, CSS and JS files should use tabs". This sounds to me as a great usecase for [.editorconfig](https://marketplace.visualstudio.com/items/chrisdias.vscodeEditorConfig)

**Comment by joaomoreno** [comment]
Is there any mode specific configuration instead? YAML actually banned tabs, so our editor putting one in there is just wrong. That is true for our project as it is for every user out there writing YAML.

**Comment by Tyriar** [comment]
I've run into this too, I want the behavior of `auto` but fallback to space, not tab. Not sure if atom does anything special here or just falls back to space by default.

**Comment by hashhar** [comment]
For those wondering, Atom also falls back, but to spaces.
Spaces is a better option because almost all compilers support spaces.

**Comment by alexandrudima** [comment]
I'm ok with changing the fallback values, I especially like the reasoning that all compilers support spaces.

So the action out of this issue is to change the fallback defaults to `insertSpaces: true, tabSize: 4`
