### ISSUE TITLE
[javascript] syntax highlighting for class arrow properties is broken

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#4980]
- VSCode Version: 0.10.14
- OS Version: Windows 10

Steps to Reproduce:

1. Write this code: 
```
class x {
  abc = () =>
    this.func(this.arr.concat(['one 1', 'two 2', 'three 3']));
}
```
2. The syntax higlighting is broken
3. See the image below

![untitled](https://cloud.githubusercontent.com/assets/760112/14296483/02d5767c-fb98-11e5-89fc-51487c19cb1b.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#142
