### ISSUE TITLE
终端选项卡不能打开

### ISSUE THREAD

**Issue by lky5230** [Microsoft/vscode#49804]
Issue Type: <b>Bug</b>

1、升级到1.23.1
2、打开目录的某个文件
3、按ctrl+` 不能轻易打开终端

注意：只能在没打开代码或者目录聚焦时ctrl+`才能打开

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.45GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
wpy-beautify|doi|2.0.10
vscode-language-pack-zh-hans|MS-|1.23.4
mssql|ms-|1.3.1
vetur|oct|0.11.7

(1 theme extensions excluded)

</details>

**Comment by lky5230** [comment]
终端选项卡不能打开

**Comment by isidorn** [comment]
Please file this in english

**Comment by pionxzh** [comment]
Simple translation for other dev:
1. Upgrade to version 1.23.1
2. Open a file in the file manager
3. Press **Ctrl+`** can't open the terminal easily

Note: Terminal can only be open when there is no file opened or focus on the file manager window

Personal reply:
I can't reproduce this issue, it just work fine for me with version 1.23.1

**Comment by mjbvz** [comment]
@lky5230 Do you see this issue in the current vs code insiders build: https://code.visualstudio.com/insiders/
