### ISSUE TITLE
Find And Replace in Selection using regex not working

### ISSUE THREAD

**Issue by hanxue** [Microsoft/vscode#49801]
When I use the `regex` mode in Find and Replace, the action is applied to the entire file instead of only the selected text. 

### Environment
- VSCode Version: 1.23.0
- OS Version: MacOS 10.10.5

Steps to Reproduce:

1. Open a file and select some code snippet
2. Use `Replace` <kbd>Option</kbd> <kbd>Command</kbd> <kbd>F</kbd>
3. Click on `Find in Selection` <kbd>Option</kbd> <kbd>Command</kbd> <kbd>L</kbd>
4. Click on Replace All

See video below

![vscode_search_and_replace_regex_not_working_for_section](https://user-images.githubusercontent.com/760008/39976091-6f6e9834-5764-11e8-8afa-14eb1fd40987.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
The first time when you open the find widget, *Find in Selection* is already turned on so when you click the icon again, it's turned off so that's why it doesn't work.
