### ISSUE TITLE
Finalize Task API

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#49806]
- move Task API to vscode.d.ts
- support correlating a task with a terminal.

**Comment by dbaeumer** [comment]
@alpaix and @rickvanprim I added events to the task execution that signals when the underlying process starts and when it ends. The start contains the process id, the end the exitCode.

Please let me know if this will work for you (minus the polling for now).

See also https://github.com/Microsoft/vscode/issues/49665

**Comment by alpaix** [comment]
@dbaumer I'll be happy to migrate as soon as it's available. What's the timeline for enabling the new API in insiders and public? When will it be available for testing?

**Comment by dbaeumer** [comment]
@alpaix I pushed a change today that adds the above API to vscode.d.ts (namespace tasks). I left the old workspace API in proposed but I would like to remove it until end of the week. Can you confirm that you moved to the new task namespace.

**Comment by alpaix** [comment]
@dbaeumer We do not plan to support older API as the Live Share remote tasks functionality is an experimental feature. We'll release a final revision along with the latest stable Task API when it's available in non-insiders VSCode version.
