### ISSUE TITLE
markdown.json no work

### ISSUE THREAD

**Issue by xiaohuoni** [Microsoft/vscode#49802]
- VSCode Version:1.23
- OS Version:windows 7

Steps to Reproduce:

1.set markdown.json
```json
{
	"h1": {
		"prefix": "md::h1",
		"body": [
			"# $1"
		],
		"description":"h1 title"
	},
}
```
2.new a file : test.md
input `md::` no intellisense

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
I can't repo in insiders. Manual triggering always works, so does trigger on type if you set:

```
    "[markdown]": {
        "editor.quickSuggestions": true
    }
```

**Comment by jrieken** [comment]
@xiaohuoni Please check with the comment above

**Comment by xiaohuoni** [comment]
Thanks for reminding, but I'm here one o'clock in the morning. So I'll deal with it in eight hours.

**Comment by xiaohuoni** [comment]
Thanks,markdown.json work well,when i set:
```josn
"[markdown]": {
        "editor.wordWrap": "on",
        "editor.quickSuggestions": true
},
```
