### ISSUE TITLE
ViewsService.openView doesn't focus view but container viewlet

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#49816]
Code sits in the `joh/outline`-branch: https://github.com/Microsoft/vscode/blob/joh/outline/src/vs/workbench/parts/outline/electron-browser/outline.contribution.ts#L22 

* have the command below which opens and focuses my custom view
* bind the command to a user keybinding
* invoke the command
* 🐛 the explorer shows but also takes focus

```ts
CommandsRegistry.registerCommand('outline.focus', accessor => {
	let viewsService = accessor.get(IViewsService);
	return viewsService.openView(_outlineDesc.id, true);
});
```

**Comment by sandy081** [comment]
Looks like your view has not overridden the `focus` method. By default `ViewletPanel` triggers the focus event in `fcous` method and it is left to the views to focus the right element. 

Fixed to focus the dom element by default.
