### ISSUE TITLE
VSCode not preserving added debug configuration properties on restart

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#49810]
You would need to install the live share extension on vscode insiders.
- Open a C# o Node project (or any project you would like)
- Start a debug session with a breakpoint
- Hit breakpoint once and then select restart
- So far so good you would hit second time and press restart
- Then an error happen on our debug adapter since there is a missing expected property that is expected

I put breakpoints on our side and the first restart did invoke again our debug configuration provider but not the second restart.
I even start our debugger on port 4711 (and configure our provider to use that port).
The normal start and first restart hit my server and accept sessions.
The second restart did not hit my server and attempt a direct launch of the debug adapter with missing information on the launch configuration.

fyi @rodrigovaras

**Comment by isidorn** [comment]
@rodrigovaras this is a great catch, thanks a lot for using insiders and reporting this
I have pushed a fix which will be available in tomorrow's insiders. Can you please let me know if you no longer see the issue then?

**Comment by rodrigovaras** [comment]
After i update vscode insiders the problem dissappear, all good and thanks.

**Comment by isidorn** [comment]
@rodrigovaras thanks for letting us know, adding verified label.
