### ISSUE TITLE
Case insensitive search no longer working.

### ISSUE THREAD

**Issue by Nemesarial** [Microsoft/vscode#49817]
Issue Type: <b>Bug</b>

When searching without the Match-Case flag set, only returns exact case-matching results.

Update:
The issue only seems to occur when using capital letters in the search field. 
search for "recaptcha" will return "reCaptcha" and "recaptcha"
search for "reCaptcha" will only return "reCapcha" even when ignoring case

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-github|Kni|0.28.1
vscode-jest|Ort|2.7.2
code-settings-sync|Sha|2.9.2
quokka-vscode|Wal|1.0.124
vscode-node-readme|ben|3.0.2
handlebars-preview|cha|1.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
dust|nem|0.0.1
vscode-npm-script|eg2|0.3.4
LogFileHighlighter|emi|2.4.0
vscode-great-icons|emm|2.1.32
vscode-highlight|fab|1.1.0
vue-snippets|hol|0.1.5
docthis|joe|0.6.0
vs-code-quick-require|mil|0.2.2
vscode-filesize|mkx|2.1.0
vscode-scss|mrm|0.6.2
toggle|reb|0.0.1
vscode-workspace-switcher|sad|1.5.1
stylelint|shi|0.36.0
vcl|tho|0.1.2
vsc-jsonsnippets|wmo|0.1.4

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Is this for file search or for the editor text search? Do you see it in VS Code insiders?

**Comment by Nemesarial** [comment]
It was not on insiders and it was in the file search section
search.smartCase: false

**Comment by roblourens** [comment]
> and it was in the file search section

There is no match-case flag in file search so I assumed you meant text search. But file search should be case insensitive for file names, can you show a screenshot or something?
