### ISSUE TITLE
IntelliSense takes ~15 minutes to start working

### ISSUE THREAD

**Issue by pswai** [Microsoft/vscode#49815]
- VSCode Version: 1.23.1
- OS Version: MacOS High Sierra 10.13.3

Steps to Reproduce:

1. Create a `jsconfig.json` in project root folder
2. Navigate to any JS file, notice that in Status Bar it is "fetching data for better TypeScript IntelliSense"
3. Even after it is done, IntelliSense still does not work with `tsserver`  at 100% CPU 
([tsserver.log](https://github.com/Microsoft/vscode/files/1999849/tsserver.txt))

I tried creating an example repo but the issue does not appear in the new repo :/ Probably the number of files is low.

Does this issue occur when all extensions are disabled?: Yes

After spending 2 days investigating, I found that there was a major refactor to typescript extension in version 1.22. I have reverted back to version 1.21 and it is working properly. This is 
[the log for version 1.21](https://github.com/Microsoft/vscode/files/1999860/tsserver.txt).

I think that the `exclude` option is not being honoured, however I have also tried `include`, it did not help either.

Another option I have tried was installing `typescript@next` (2.9-dev) and point `tsdk` to it. Unfortunately it did not help.

My `jsconfig.json`:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "allowSyntheticDefaultImports": false,
    "baseUrl": "./",
    "paths": {
      "components/*": ["src/modules/components/*"],
      "lib/*": ["src/modules/lib/*"],
      "state/*": ["src/modules/state/*"]
    }
  },
  "exclude": ["node_modules", "**/node_modules/*"]
}
```

**Comment by mjbvz** [comment]
Do you see this issue in VS Code insiders?

**Comment by pswai** [comment]
@mjbvz Thanks for the quick response! Sorry I don't know about VS Code Insiders, let me try it now.

**Comment by mjbvz** [comment]
@pswai Can you please test this again on VS Code insiders which includes TypeScript 2.9.2. I have not been able to repo this issue. If you still see this issue, please try installing typescript@next (3.0.0) and collecting the logs again so we can forward this to the TypeScript team

**Comment by pswai** [comment]
@mjbvz VSCode Insiders with TS 2.9.2 is having the same issue. However together with typescript@next (Version 3.0.0-dev.20180623) is working great!

I have not tested typescript@next with VSCode stable yet but i guess it should solve the issue as well.

**Comment by mjbvz** [comment]
Ok, let me know if you are still seeing this issue when using typescript 3.0. The latest  VS Code insiders already includes TypeScript 3.0.1 and it will go out to normal users in the July release
