### ISSUE TITLE
Can't see change log linked issues

### ISSUE THREAD

**Issue by ljporljp** [Microsoft/vscode#49819]
Issue Type: <b>Bug</b>

When i opened the page"https://github.com/Microsoft/vscode/milestone/70?closed=1" from change log(1.23.1), i can't see anything.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (0.89GB free)|
|Process Argv|D:\Pro\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.3.3
Bookmarks|ale|0.19.1
code-gnu-global|aus|0.2.2
vscode-database|baj|1.5.1
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.4
vscode-markdownlint|Dav|0.16.0
vscode-eslint|dba|1.4.8
vscode-hasher|dee|1.0.1
jupyter|don|1.1.4
xml|Dot|1.9.2
gitlens|eam|8.2.4
tslint|eg2|1.0.28
file-icons|fil|1.0.12
code-runner|for|0.9.3
gc-excelviewer|Gra|2.0.21
beautify|Hoo|1.3.0
nsis|idl|3.13.2
latex-workshop|Jam|5.3.3
Lua|key|0.0.9
cmake-tools-helper|mad|0.2.1
vscode-clang|mit|0.2.2
ecdc|mit|0.12.0
vscode-language-pack-zh-hans|MS-|1.23.4
mssql|ms-|1.3.1
python|ms-|2018.4.0
vscode-ai|ms-|0.1.8
cpptools|ms-|0.17.0
csharp|ms-|1.15.1
Go|ms-|0.6.79
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.4.3
color-highlight|nau|2.3.0
vscode-code-outline|pat|0.2.0
qub-xml-vscode|qub|1.2.8
java|red|0.24.0
vscode-icons|rob|7.23.0
code-settings-sync|Sha|2.9.2
shader|sle|1.1.3
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
unity-debug|Uni|1.3.0
cmake-tools|vec|0.11.1
vscode-redis|vit|1.2.0
vscode-java-debug|vsc|0.9.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is an issue with github

**Comment by lnicola** [comment]
@ljporljp It's loading now.

**Comment by ljporljp** [comment]
@mjbvz @lnicola Ok,thinks.
