### ISSUE TITLE
Improve the save dialog when deleting dirty files

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4982]
- VSCode Version: 0.10.12-alpha (latest)
- OS Version: Windows 10

Steps to Reproduce:

1. Modify a file and do not save
2. Delete the file

Actual:
Confirmation that you want to delete shows up, then after it asks if you would like to save the file.

Expected:
No confirmation asking if you would like to save after confirming delete.

**Comment by bpasero** [comment]
We prompt to prevent data loss, but I agree that the provided options do not make so much sense in that case.

**Comment by bpasero** [comment]
Now doing the same as when deleting a folder with dirty files, not asking for confirmation. But keeping the file dirty in the editor.
