### ISSUE TITLE
[Feature Request] Mouse Gestures Support

### ISSUE THREAD

**Issue by LonMcGregor** [Microsoft/vscode#49823]
Many web browsers either natively support the use of mouse gestures or have extensions that enable this. (E.g. Vivaldi Natively, Microsoft Edge has an official Microsoft Web Extension for this).

A mouse gesture is the ability to hold a modifier key (commonly Right Click) and move the mouse in a direction, and upon letting go of the modifier, a command will be carried out.

Example use cases:
* Hold Right Click, Move mouse down, then to the right to: close a tab.
* Hold Right Click, Move mouse up, then to the right to: start a debug task

This could also be combined with a scrolling movement, as the editor Notepad++ Supports:
* Hold Right Click, Scroll Up to: Cycle to the tab to the left of current

Another common use case is the Rocker Getsure:
* Hold Right Click, Click Left to: Go back (alternative to Alt+Left)

More information:
* Wikipedia: https://en.wikipedia.org/wiki/Pointing_device_gesture & https://en.wikipedia.org/wiki/Mouse_chording
* Edge Extension: https://www.microsoft.com/en-us/store/p/mouse-gestures/9nblggh4nkf9
* Vivaldi Implementation: https://help.vivaldi.com/article/mouse-gestures/

**Comment by mjbvz** [comment]
Duplicate of #3130
