### ISSUE TITLE
How to hide the Restart button in the debug toolbar when attached to a process that can't be restarted?

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#49822]
We're implementing "Attach to Process" but sometimes have no ability to re-launch the app being debugged (we don't have all the necessary info if the user launched it separately).

I can't find any way to hide the Restart button or reliably tell in the debug config provide that the request to resolve came from a restart (so we can inform the user it's not supported).

**Comment by isidorn** [comment]
This is currently not suppored, but we could add a capability or modify the current [supportsRestartRequest](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1150)

**Comment by DanTup** [comment]
I think currently `supportsRestartRequest` is whether the DA can handle the restart itself so I think there need to be three states:

1. Restart is not supported (eg. you attached to something you can't restart)
2. Restart is supported and should be handled by Code (eg. terminate, re-start)
3. Restart is supported by the DA (call restartRequest)

I'm not sure if `supportsRestartRequest` could be extended to handle (1) in a non-breaking way?

(In the meantime; what do you think the best way to reject this is? Is there a way to tell when something is a restart request from an attached process within the debug configuration provider's resolve method?)

**Comment by DanTup** [comment]
@weinand Is there a way for me to declare `supportsRestartRequest: true` just for an attached session? That way I could at least stop Code trying to handle the restart, and send back a warning to the user that it's not supports (and basically do nothing).

**Comment by DanTup** [comment]
@weinand Sure, it's not about blocking the user, it's about hiding a button that is non-functional. Detaching and re-attaching to a process is essentially a no-op (there is no visible effect to the user) and having a button that just does nothing by design when you click it feels a bit weird.

**Comment by weinand** [comment]
It is not really a no-op because detaching and re-attaching will be visible because VS Code will briefly leave debug mode and the debug toolbar disappears and comes back.

**Comment by DanTup** [comment]
Sure, but I mean - what's the point in that? Why do you want a button that causes a toolbar to briefly disappear and then come back? It seems like it doesn't really do much functionality/logically, so it may as well be hidden/disabled?

**Comment by weinand** [comment]
@DanTup I fully agree with your statements.
But given that we have quite a few feature requests on our plate, I consider the effort for adding DAP protocol for hiding the Restart button not worth the effort...
