### ISSUE TITLE
Conditional breakpoints cause out-of-memory crash

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#49829]
Issue Type: <b>Bug</b>

Given is the following NodeJS code:
```js
"use strict";

const subject = {
  foo: new ArrayBuffer(1024 * 1024),
  bar: new Array()
};

for (let iteration = 0; iteration < 1024 * 1024; ++iteration) {
  subject.bar[iteration] = iteration;
}

console.log(subject.bar[1337]);

console.log("Done");
```

Running this code should finish instantly and print `1337` and `Done`.

Now add a new breakpoint on the line `subject.bar[iteration] = iteration;` and set a condition of `!subject`.

When you now run the file in the NodeJS debugger, it will apparently run forever. Memory usage of the VS Code process will increase towards 4 GB at which point the debug adapter will crash.

At least it crashes in my main application. I only watched this minimal example rise to 2 GB, but I'm sure it's the same cause and a crash can be provoked by running more iterations.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.91GB (40.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe landslide/landslide.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|0.11.0
bracket-pair-colorizer|Coe|1.0.48
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
innosetup|idl|1.0.3
vscode-lebab|mrm|2.5.0
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|4.4.3

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
What version of node are you using?

**Comment by oliversalzburg** [comment]
I tried with 8.11.0, 8.11.1 and 10.1.0. All were affected.

**Comment by roblourens** [comment]
I see the same thing when debugging with chrome devtools. Unfortunately I think this is basically expected behavior. 1024*1024 times, the program stops and evaluates a script, which is slow. When a debugger is attached, scripts are never garbage collected, so they are collected forever, causing the increase in memory. I don't think the debug adapter can improve things here unfortunately.

**Comment by oliversalzburg** [comment]
Is some kind of UI indication maybe an option? Like an exclamation mark on the breakpoint if it is causing considerable resource usage or excessive evaluations, or forcing a break on the breakpoint when whatever buffer is exceeded here reaches a certain threshold?

I had this breakpoint somewhere deep in the code and had forgotten about it. I did not make the mental connection to a breakpoint-related issue, so the search was confusing and I was troubleshooting a lot.
