### ISSUE TITLE
Feature Request - Extension Group

### ISSUE THREAD

**Issue by FBoucher** [microsoft/vscode#49826]
### Context

Depending on what I'm doing, I disable some extension and enable others.

If I'm doing markdown editing, I really don't need the OmniSharp, and all the C# extension on... so I pass them one by one and disactivate them.

I do that to keep the minimum extension active and keep VSCode super fast. By having them all Enabled it's convenient,  but it slows down a lot the app and the experience is less enjoyable.

### Feature Description

With the Extension Group I could with ONE selection (from a down list) enable a set of extensions and deactivate all the others. Instead of going through 3-4 enable/ disable... one click and the work could be done.

Of course, we will need a way to create our own Extension group....

**Comment by FBoucher** [comment]
I would love to participate in the development of that feature, I'm just not sure where to start and where are saved the active vs inactive extensions.

**Comment by PandawanFr** [comment]
Any progress on this? Would love to have this feature but there doesn't seem to have been anything new since Nov 2018...

**Comment by FBoucher** [comment]
@PandawanFr still nothing. I'll try to start something.

**Comment by PandawanFr** [comment]
Alright thanks! Also, [this issue](https://github.com/Microsoft/vscode/issues/40239) seems to be related

**Comment by al73rna** [comment]
Any update on this issue? As someone working with a ton of different tools this could be a life changer. 
Also it would be great if we could just put all of the theme/icon pack extensions in a separate collapsable group and not have to browse through them every time we are looking for something.

**Comment by FBoucher** [comment]
I saw [Profile Switcher](https://marketplace.visualstudio.com/items?itemName=aaronpowell.vscode-profile-switcher) from @aaronpowell it looks like the solution.  I need to test to it close this issue.

**Comment by al73rna** [comment]
@FBoucher Thank you! That extension is working flawlessly.

**Comment by FBoucher** [comment]
@al73rna It's @aaronpowell that you need to thanks ;) 
Share the news I'm sure he will be happy. 
I will close this request then.

**Comment by PandawanFr** [comment]
Idk if we should close this issue. The Profile Switcher extension is [kind of a hack](https://github.com/Microsoft/vscode/issues/40239#issuecomment-520566528). It uninstalls the extensions completely rather than enabling/disabling them (due to a limitation in the VSCode Extensions API).

So the two solutions I can think of are:
1. Make an official extension group feature incorporated into VSCode (aka this issue).
2. Add the ability for extensions/VSCode configs to enable/disable extensions (aka issue #40329).

**Comment by FBoucher** [comment]
@PandawanFr that would be a much better solution of course!
It would need to be integrated into VSCode, as it will look very suspicious if an extension disables other extensions.

I'm happy to reopen it if the product team agree that it makes sense...

/cc @sandy081

**Comment by aaronpowell** [comment]
@PandawanFr I agree with @FBoucher's comment that it would be a risky proposition for extensions to be able to disable other extension at will so while my extension is a hack I find it to be an acceptable hack.

**Comment by PandawanFr** [comment]
So allowing extensions to enable/disable extensions is risky, but installing/uninstalling is not? Doesn't sound very logical to me. 

Regardless, I do agree that having it integrated as an official feature from VSCode would be best.
