### ISSUE TITLE
Tree events not properly triggered on ctrl+hover on symbol

### ISSUE THREAD

**Issue by DaGhostman** [Microsoft/vscode#49821]
- VSCode Version: >= 1.20
- OS Version: Win10 (1803) & Ubuntu (14.04)

Steps to Reproduce:
I am an extension author and am utilizing the custom tree view API. In my ext I am binding on
```
        vscode.window.onDidChangeActiveTextEditor((ev?: vscode.TextEditor) => {
            if (vscode.window.activeTextEditor) {
                this.refresh(vscode.window.activeTextEditor.document);
            }
        });
        vscode.workspace.onDidSaveTextDocument((document) => this.refresh(document));
        vscode.workspace.onDidOpenTextDocument((document) => this.refresh(document));
        vscode.workspace.onDidCloseTextDocument((document) => this.refresh(document));
```

1. Hold down `ctrl` and hover on a symbol
2. The tree view updates with the symbols of the hovered element's file
3. Move the mouse away from the symbol

Expected: The view to update to the currently open file
Actual: The view stays with the contents of the previously hovered file

Does this issue occur when all extensions are disabled?: No (as extension is not loaded)

Is this the intended behaviour or not, since it seems that the `onDidChangeActiveTextEditor` is not triggered on mouse leave. 

Am I doing something wrong?

**Comment by jrieken** [comment]
> Is this the intended behaviour or not, since it seems that the onDidChangeActiveTextEditor is not triggered on mouse leave.

If I understand correctly you wanna know how the active editor behaves on mouse move?

**Comment by DaGhostman** [comment]
Thanks for the quick response :)

Well possibly that, I don't know what to expect actually... if the `ctrl+hover` behaviour  is supposed to happen then - yes; otherwise I am looking to get what the event triggered on mouse "not-hover" so I can restore the view to the current file or how to check if `ctrl` is down

**Comment by jrieken** [comment]
sorry, but I don't understand what's going on in that gif

**Comment by DaGhostman** [comment]
Oh, sorry maybe I should've added some description as well.

Notice when the underscore appears under `MvcEvent` that is the hover when `ctrl` is pressed. The view on the left updates based on the contents of the file where `MvcEvent` is defined, but when the mouse leaves it does not update back to the initial contents of the file.

Is it a bug in vscode or there is another event that gets triggered that I am not attaching to?

**Comment by jrieken** [comment]
Ok, I believe I slowly start to understand. For a start, there is event like hover in/out etc because the API hides the UI internals and works with data only (see XYZProvider-interfaces). Then, there is this `vscode.workspace.onDidOpenTextDocument((document) => this.refresh(document));` in your extensions which means when a document is opened (that doesn't mean shown but effectively loaded from disk) you update your view. Instead, you might wanna listen on `onDidChangeVisibleTextEditors` (in addition to `onDidChangeActiveTextEditor`)

**Comment by DaGhostman** [comment]
Hmm after some tweaking and trial an error I've come to a successful result. You ware absolutely right about the cause `onDidOpenDocument`... I feel kinda dumb for not looking up the docs properly before opening this issue 🙁 Anyway thank you for the suggestion about `onDidChangeVisibleTextEditors` event, and it turns out that dropping both the `onDid(Open|Close)TextDocument` works absolutely fine for the case.

Sorry for wasting your time and please, keep up the good work 🙂
