### ISSUE TITLE
Hide Activity Bar Not Working

### ISSUE THREAD

**Issue by d4nyll** [Microsoft/vscode#49820]
In my User Settings, I have set:

```
"zenMode.hideActivityBar": true,
"workbench.activityBar.visible": false,
```

However, the activity bar is still there.

Furthermore, when I look at the _View_ menu, the option reads 'Show Activity Bar'. When I click 'Show Activity Bar', nothing happens. My User Settings are not modified, and the option remains 'Show Activity Bar'.

---
I have tried on both of the following versions:
```
# VSCode Insider
Version 1.24.0-insider
Commit 5d12f53178b72e88431347f8e248c49335a7fefc
Date 2018-05-14T05:11:05.143Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

# VSCode
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T15:23:19.356Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Steps to Reproduce:

1. Open Editor
2. Right-Click on the activity bar
3. Select 'Hide Activity Bar'

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by isidorn** [comment]
@d4nyll are you in zen mode or not?
Can you reproduce if you open a vscode with a brand new user data directory?
`.code --user-data-dir=SOME_PATH`
Do you have some error in your user settings? Can you paste them here?
