### ISSUE TITLE
Improve handling of "Debug adapter process has terminated unexpectedly"

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#49827]
Issue Type: <b>Feature Request</b>

I have an unknown issue where NodeJS will exit and I only get a bubble saying:

> Debug adapter process has terminated unexpectedly

This is not helpful. I don't understand what is happening and I'm not even seeing what NodeJS wrote to stdout/stderr, which might help me understand the situation.

It's additionally confusing because the handling of this unexpected issue is happening silently. So while I'm still watching my browser, NodeJS has already exited and VS Code knows that. I feel like this is one of the situations where it would be acceptable to draw attention to the application.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by oliversalzburg** [comment]
Related to #49829

**Comment by weinand** [comment]
What version of node are you using?

**Comment by oliversalzburg** [comment]
@weinand Given that #49829 can't be solved, could you reconsider this issue?

I just had another case of Node (or the debug adapter) randomly exiting (no breakpoints this time) and I'm left clueless again.

**Comment by weinand** [comment]
Since VS Code doesn't know why a DA is crashing, it cannot provide any additional information.
The only thing we can change is the kind of notification.
E.g. we could show a modal (blocking) dialog instead of the more ambient notifications.

Is this what you are suggesting?
