### ISSUE TITLE
PHP+JS+HTML code segments highlighting

### ISSUE THREAD

**Issue by IgorSte** [Microsoft/vscode#49830]
Is there a chance to highlight PHP, JS and HTML code segments that are mixed in a single php file?
Also, the syntax keywords are not highlighted in these files as well.

For example, on the screen shot below there is the comparison of VS Code layout and layout of another text editor. The Notepad editor marks PHP and JS code segments each with its own color, so it is extremely easy to distinguish one from another one
![image](https://user-images.githubusercontent.com/31000984/40000460-82bcd8ee-5794-11e8-860d-e4c7418e31f9.png)
The color theme used is standard "Light+"

As FE developer I'm facing such mix quite often. The VS Code is perfect, but at the moment it is very hard to work with such PHP files due to lack of visibility.

**Comment by roblourens** [comment]
This does work, but it looks like your code sample is missing a `</style>` tag, which is breaking syntax highlighting after that in the script. It should work if you fix that.
