### ISSUE TITLE
Após atualizar a versão do vscode, não consigo pegar o valor das variáveis pelo debug.

### ISSUE THREAD

**Issue by joaoleao01** [Microsoft/vscode#49837]
Issue Type: <b>Bug</b>

Bom dia.
Utilizo a extensão ADVPL do colaborador killerall.
Após atualizar a versão do VS Code, não cosigo mais usar a função 'Get Value' da aba 'Variables'.
As opções ficam desabilitadas.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.86GB (1.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
advpl-vscode|Kil|0.8.2

</details>

**Comment by mjbvz** [comment]
Please file this issue against the  ADVPL extension
