### ISSUE TITLE
CTRL+Z stuck

### ISSUE THREAD

**Issue by JesseBoogaard** [Microsoft/vscode#49833]
Issue Type: <b>Bug</b>

while testing out the liveshare plugin CTRL+Z got stuck and removed all our progress, we think this issue has to do with the fact that one of us had format on save enabled and the other didn't

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (11.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
p5js-snippets|aci|0.0.6
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.16.0
vscode-eslint|dba|1.4.8
line-counter|dol|0.5.2
gitlens|eam|8.2.4
vscode-npm-script|eg2|0.3.4
live-p5|fil|1.1.0
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
latex-workshop|Jam|5.3.3
docthis|joe|0.6.0
vue|liu|0.1.5
sftp|lix|1.1.7
vscode-mocha-sidebar|mat|0.19.0
python|ms-|2018.4.0
PowerShell|ms-|1.7.0
vsliveshare|ms-|0.3.98
debugger-for-chrome|msj|4.4.3
vetur|oct|0.11.7
material-icon-theme|PKi|3.4.0
vscode-yaml|red|0.0.11
vscode-icons|rob|7.23.0
vscode-paste-and-indent|Rub|0.0.8
vue-vscode-snippets|sdr|1.3.0
background|sha|1.1.17

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Please report the issue over at https://github.com/MicrosoftDocs/live-share/issues
