### ISSUE TITLE
No terminal colors with mvn

### ISSUE THREAD

**Issue by GoGoris** [Microsoft/vscode#49834]
- VSCode Version: 1.23.1
- OS Version: Windows 10 Enterprise  v1703

There is no color highlighting when I run maven inside the vscode terminal. 
I would think that this is a maven bug, but the highlighting works flawlessly when I run it from the windows or Git Bash command prompt.

Steps to Reproduce:

Running mvn in the windows command prompt or Git Bash shows the colors correctly.
Running jest also shows the colors correctly in vscode.
Running `echo -e "Default \e[36mCyan"` also works and shows the color correctly.
**Running  `mvn` or `mvn.cmd` in the vscode terminal prints the color codes instead of showing colored text.**

Output:
```
[?[1;34mINFO?[m] ?[1m------------------------------------------------------------------------?[m
[?[1;34mINFO?[m] ?[1;32mBUILD SUCCESS?[m
[?[1;34mINFO?[m] ?[1m------------------------------------------------------------------------?[m
[?[1;34mINFO?[m] Total time: 53.568 s
[?[1;34mINFO?[m] Finished at: 2018-05-14T16:08:50+02:00
[?[1;34mINFO?[m] ?[1m------------------------------------------------------------------------?[m
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/45693
