### ISSUE TITLE
Invalid Emmet expanding when multiplication operator is not specified

### ISSUE THREAD

**Issue by Oliver-Fish** [Microsoft/vscode#49839]
When expanding an Emmet snippet with item numbering without specifying any multiplication operator the output stays as $ instead of replacing it with the number 1 

Take the following snippet "p{$}"
```
**Output:** <p>$</p>
**expected output:** <p>1</p>
```
However the following snippets give expected output "p{$}*" "p{$}*1"
`**Output:** <p>1</p>`

- VSCode Version: 1.23.1
- OS Version: Windows 10 & Arch Linux

Steps to Reproduce:

1. Expand the following Emmet snippet p{$}
2. Confirm the output is `<p>$</p>` instead of `<p>1</p>`

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by ramya-rao-a** [comment]
Thanks for reporting!
Logged upstream issue https://github.com/emmetio/html-transform/issues/17
