### ISSUE TITLE
VScode loses windows keyboard config

### ISSUE THREAD

**Issue by madsongr** [Microsoft/vscode#49836]
- VSCode Version: 
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
Windows 7

Steps to Reproduce:

1. After some time of coding, vscode is losing keyboard configuration.
2. For example: key "{" turns into "}" when pressed. "Ctrl + ;" to comment code stops to work and I have to find which key to press to comment. 
3. I have to close and open vscode again to get the right keys again.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this issue reproduce if you disable all extensions? Do you see it in VS Code insiders?

**Comment by madsongr** [comment]
@mjbvz I'm going to do some tests to check that.

**Comment by madsongr** [comment]
@mjbvz I disabled extension by extension reloading everytime but it did not fix my issue. I had to close and open VS Code to make it works again.

**Comment by alexandrudima** [comment]
@madsongr You can run without extensions from the command line using `code --disable-extensions`.

What do you mean when you say "vscode is losing keyboard configuration". Do you have multiple keyboard layouts configured with Windows? Are you perhaps switching keyboard layouts while VS Code is running? Is typing in the editor not reflecting your current keyboard layout? How about typing in the find widget?

**Comment by madsongr** [comment]
@alexandrudima "Is typing in the editor not reflecting your current keyboard layout?" Yes. After some time of coding this is what happens. It automatically changes keyboard layout.

**Comment by alexandrudima** [comment]
@madsongr I cannot reproduce what you are describing. When I have multiple keyboard layouts installed, the currently active one is reflected when typing in the editor or in other places in the UI (such as the find widget).

Do you have installed other software on your machine that would change the keyboard layout at the OS level?

**Comment by madsongr** [comment]
@alexandrudima no, I don't. I'm using vscode after installing windows 10 and it didn't happen anymore. I'll keep testing it. Now I noticed that when I open vscode the last html file I was working on has all the body tag collapsed. This is happening every time I open vscode.

**Comment by alexandrudima** [comment]
@madsongr Please keep an eye out if you encounter such keyboard trouble in the future and try to capture the steps that lead to it.

Regarding the html and the collapsed body tag, it is best if you open a new issue, as that appears to be something completely unrelated to keyboard layouts. Again, try to create an issue with steps, that can be reproducible. Sometimes, including a screenshot can help us reproduce.
