### ISSUE TITLE
High-contrast theme has ugly serif font on Output dropdown box

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#4983]
- VSCode Version: 0.10.11
- OS Version: Mac OS X El Capitan

We have an ugly serif font and mis-styled dropdown box (light theme and larger dropdown control than normal) in the high contrast theme.

<img width="138" alt="screen shot 2016-04-01 at 5 49 32 pm" src="https://cloud.githubusercontent.com/assets/11839736/14298235/ab15dea4-fb38-11e5-9ff7-e084861da7d3.png">

Steps to Reproduce:

1. Go to High Contrast Theme
2. Open Output pane

**Comment by bpasero** [comment]
@bgashler1 I think I fixed this, check latest!
