### ISSUE TITLE
Stubborn dialogue warning.

### ISSUE THREAD

**Issue by xerosugar** [Microsoft/vscode#49848]
- VSCode Version: 1.23.0
- OS Version: Win 7 

Steps to Reproduce:

1. Run your build tast.
2. When your app is running, run the build command again. A dialogue that says "The task ... is already running" pops up in the corner.
3.1 Close the app by clicking the X in the window's corner. The dialogue is still there even though the app is closed.
3.2. Restarting the app through a kb shortcut does not close the dialogue.
3.3 Terminating the app through a kb shortcut does not close the dialogue.

Does this issue occur when all extensions are disabled?: 
My project relies on extensions so could not test.

**Comment by isidorn** [comment]
This is just how electron modal dialogs behave on windows 7.
Please file an issue against electron https://github.com/electron/electron

And it is proper to show that error, I believe @dbaeumer is showing it from the tasks
