### ISSUE TITLE
 [Loc] Request to add Armenian (hy) language to Transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [microsoft/vscode#49846]
See guidance at https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project. 
We need 3 contributors vote here before enable the language in Transifex.
Please vote here by pasting you Transifex account here. For example, https://www.transifex.com/user/profile/12345

**Comment by Lev09** [comment]
Here is my profile url
https://www.transifex.com/user/profile/levonhakopyan/

**Comment by aabgaryan** [comment]
https://www.transifex.com/user/profile/abgaryanfx/

**Comment by donkikos** [comment]
Here is my profile https://www.transifex.com/user/profile/tigran.shahverdyan/

**Comment by donkikos** [comment]
Hi @danyeh, when is Armenian language going to be available on transifex?

**Comment by aabgaryan** [comment]
@danyeh we have 3 contributors.

**Comment by jomardyan** [comment]
+Vote

**Comment by danyeh** [comment]
We don't have plan to enable additional language for VSCode in MLCP in near term. Hence close the request here.
New request should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)

**Comment by aabgaryan** [comment]
Thanks for the ultra fast reply 🍑
