### ISSUE TITLE
Allow IDE Specific Custom Keys Feature as available in Intellij.. Code is really fast and very useful as it has integrated Terminal in it. just add this feature it will be very appreciated.

### ISSUE THREAD

**Issue by vikkymandoi** [Microsoft/vscode#49847]
I have been learning many languages in the years of experience... Code is really a good IDE and it is very light. i personally liked it, as per my experience i have been coding in Eclipse for many years.. and now from few years with Android Coding i have been using Intellij., 

Code should address to this issue that using shortcut keys is the most important for any developer. i am familiar with Eclipse shortcut keys so i simply change the settings to Eclipse in Intellij. if this feature is available in Code too this will be good.

**Comment by mjbvz** [comment]
We already support configurable keybindings: https://code.visualstudio.com/docs/getstarted/keybindings

Please describe what you are trying to accomplish so that I can understand the issue better

**Comment by vikkymandoi** [comment]
That's y i specified like Intellij.. they simply have a Drop down where i can select Eclipse and all keys change to that.. here i have to manually configure them :) ..

**Comment by mjbvz** [comment]
There are keymaps extension packs that you can enable and disable:

<img width="507" alt="screen shot 2018-05-14 at 11 09 23 am" src="https://user-images.githubusercontent.com/12821956/40015173-50f97df8-5767-11e8-863b-b5d683142606.png">
