### ISSUE TITLE
"Go to next problem" display isn't large enough

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#49843]
* Type:
```ts
const x: { a: { b: 0 } } = { a: { b: 1 } };
```
* Ctrl-shift-p and select "Go to next problem".

![next_problem](https://user-images.githubusercontent.com/19274678/40008842-35b556b4-5755-11e8-9627-ffc99e9ec7d3.jpg)
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.24.0-insider (5d12f53178b72e88431347f8e248c49335a7fefc, 2018-05-14T05:16:26.538Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (8.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe src|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by andy-ms** [comment]
It looks like you need `"editor.fontSize": 12` set to reproduce the error.

**Comment by jrieken** [comment]
I can repro with `11`, thanks
