### ISSUE TITLE
Preserve last value of Quick Open

### ISSUE THREAD

**Issue by cmackenz** [Microsoft/vscode#49840]
- VSCode Version: 1.23.1
- OS Version: Mac OS High Sierra v10.13.4

Steps to Reproduce:

1. Open Quick Open `⌘P`
2. Search for a file
3. Close Quick Open (or select a file)
4. Open Quick Open `⌘P`
5. Last search value is gone

Does this issue occur when all extensions are disabled?: Yes/No

It would be great to preserve the last value of the Quick Open search field as I am usually searching for similarly named files when using Quick Open in quick succession.

refL https://github.com/Microsoft/vscode/issues/17163

**Comment by mjbvz** [comment]
Previously opened files are shown in the recently opened section:

<img width="609" alt="screen shot 2018-05-14 at 10 41 10 am" src="https://user-images.githubusercontent.com/12821956/40013764-5d6a9436-5763-11e8-91d7-c34450a76aec.png">

Quick open history is covered by #18232

**Comment by utilityboy** [comment]
@mjbvz I think the point of this one in particular is to easily modify the last item you opened.  In a number of javascript frameworks and in rails for example, the workflow to open files related files quickly.  

e.g. in the case of Ember, often you'll type something like `mycomp js` to open code and then immediately `mycomp hbs` to open the corresponding template.

In the case of Rails, I'd see similar usecases for opening a class and then easy opening the corresponding spec.

So it's not so much about the "history" but quickly opening similar or related files.  Please consider reopening.

**Comment by Madd0g** [comment]
I have many files named after their feature, when refactoring a feature group I type a complicated fuzzy search to get them all in one quick open search, but then to get them all to show up again, I need to type it (and remember it) all over again.

Of course it also helps if a user accidentally clicks the wrong result in the search.

Quick open is a great file navigation experience (I rarely use the explorer), having a preselected (once you start typing it is replaced) last search term in it when you open it is such a no-brainer and such a big productivity boost. 

I also think that the last term shouldn't be hidden under another (history) keypress. Please consider reopening.
