### ISSUE TITLE
Add setting to persist auto attach setting

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#49842]
Issue Type: <b>Feature Request</b>

Currently, if one turns auto attach on, it'll be turned off for next reload.
Why can't we have a setting that persists until user turns it off?

Alternative, according to the doc:

> Currently, we detect the patterns --inspect, --inspect-brk, --inspect-port, --debug, --debug-brk, --debug-port (all optionally followed by a '=' and a port number).

Maybe we could turn on auto attach when these arguments are detected?

VS Code version: Code - Insiders 1.24.0-insider (5d12f53178b72e88431347f8e248c49335a7fefc, 2018-05-14T05:10:56.657Z)
OS version: Darwin x64 16.7.0

**Comment by weinand** [comment]
Has been fixed in the July 2018 release.
