### ISSUE TITLE
organizeImports remove referenced import

### ISSUE THREAD

**Issue by JJamieZhang** [Microsoft/vscode#49844]
Issue Type: <b>Bug</b>

```
import ObjA from 'file';
.......
const Objs = {
  ObjA,
};
```

Code like this. ObjA is being referenced but organizeImports still remove its import.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

</details>

**Comment by mjbvz** [comment]
This is already fixed in insiders
