### ISSUE TITLE
Deleting a folder with a modified file shows save changes prompt when exiting 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4984]
- VSCode Version: 0.10.12-alpha (latest)
- OS Version: Windows 10

Steps to Reproduce:

1. Modify a file in a folder and do not save
2. Delete the folder containing that file
3. Exit VS Code

Actual:
Prompt shows asking if you would like to save the file you deleted within the folder. If you choose yes, when you re-open Code the folder and file will be restored.

**Comment by bpasero** [comment]
This is to prevent data loss.
