### ISSUE TITLE
Shell command install code .  is lost when you reload VS

### ISSUE THREAD

**Issue by Rolando-Barbella** [Microsoft/vscode#49854]
Issue Type: <b>Bug</b>

Every time you reload VS, you lose the `code .` shell command in the terminal and have to add it again.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (2.92GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
react-redux-react-router-snippets|dis|0.4.29
githistory|don|0.4.1
es7-react-js-snippets|dsz|1.6.0
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
sass-lint|gle|1.0.2
githd|hui|1.1.3
node-debug2|ms-|1.20.0
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.4.3
sass-indented|rob|1.4.9
vscode-react-native|vsm|0.6.9
vscode-import-cost|wix|2.6.2

</details>

**Comment by gioragutt** [comment]
@Rolando-Barbella can you give a better explanation about what you meant? perhaps provide a GIF?

**Comment by Tyriar** [comment]
@Rolando-Barbella how do you add the shell command and can you share your `~/.bash_profile` file?
