### ISSUE TITLE
Add jsconfig.json option to resolve directory-named-webpack-plugin paths

### ISSUE THREAD

**Issue by tylerkayser** [Microsoft/vscode#49857]
Issue Type: <b>Feature Request</b>

In our Webpack configuration, we use directory-named-webpack-plugin to remove redundant segments from our file pathing.  i.e.

`'components/Dropdown/Dropdown'` becomes `'components/Dropdown'`

It would be great if the IDE was able to understand this pathing and look for files named after their directory, rather than only looking exclusively for index.js files.

I propose adding an option within jsconfig.json to support this functionality.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.4.0

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24116
