### ISSUE TITLE
Markdown preview does not adjust base for image links when switching between tabs

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#49859]
Issue Type: <b>Bug</b>

1) Open a markdown file
2) Show preview to side
3) Open a markdown file in a different folder, one that has image links (e.g. https://github.com/Microsoft/vscode-cosmosdb/blob/master/README.md)
!) the image links are broken

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31230 @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (7.28GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
mongogo|bag|0.1.2
regex|chr|0.2.0
vscode-markdownlint|Dav|0.16.0
githistory|don|0.4.1
jupyter|don|1.1.4
tslint|eg2|1.0.28
vscode-bump|fab|1.5.0
docthis|joe|0.6.0
vscode-antlr4|mik|2.0.3
vscode-azurestorage|ms-|0.3.1
vscode-cosmosdb|ms-|0.7.1
python|ms-|2018.4.0
azure-account|ms-|0.4.0
csharp|ms-|1.15.1
vscode-versionlens|pfl|0.21.0
yo|sam|0.9.3
extension-api|spy|0.2.0
python|tht|0.2.3
code-lens-roundup|wad|1.0.0

</details>

**Comment by mjbvz** [comment]
Please describe the basic structure of the workspace. Where does the markdown file live? How about the images?

**Comment by StephenWeatherford** [comment]
I'd suggest cloning the repro with the file I mentioned in step 2 and open the main folder in VS Code.  All images are in a relative folder "resources".  Example link:

```
![Browse CosmosDB and MongoDB databases](resources/Browse.png)
```

I only noticed this problem happening fairly recently.  Works fine if I open this readme first, but if I first open one in another folder, it seems like it's looking at references relative to the folder where the first markdown file was opened.

**Comment by mjbvz** [comment]
I can't repo this in VS Code insiders following these steps:

1. Clone https://github.com/Microsoft/vscode-cosmosdb
1. Open folder in VS Coder
1. Open `/grammar/readme.md`
1. Open preview to side
1. Switch to `Readme.md`

All the images seem to load properly. Are those the steps you are following?

**Comment by StephenWeatherford** [comment]
You need to open an .md from a folder outside of the repro (in my case it usually happens when opening a readme.md from a similar repro which I'm comparing to the current one).  Try this:

1. Clone https://github.com/Microsoft/vscode-cosmosdb
2. Open folder in VS Code
3. Open /grammar/readme.md
  **3b. Save File As -> c:\temp\readme.md**
4. Open preview to side
  **4b. Put selection back in the c:\temp\readme.md tab**
5. Switch to /Readme.md **(the one in the main folder)**
