### ISSUE TITLE
Enum should be defined before use

### ISSUE THREAD

**Issue by kendrickw** [Microsoft/vscode#49852]
The enum `NodeColor` is used before definition in `rbTreeBase.ts`:

https://github.com/Microsoft/vscode/blob/95dfbe441038ed4cae61aae56c07c1a1f75b1b27/src/vs/editor/common/model/pieceTreeTextBuffer/rbTreeBase.ts#L81

https://github.com/Microsoft/vscode/blob/95dfbe441038ed4cae61aae56c07c1a1f75b1b27/src/vs/editor/common/model/pieceTreeTextBuffer/rbTreeBase.ts#L87

This problem doesn't affect VScode, but it does cause problem when creating a single UMD bundle with [@timkendrick/monaco-editor](https://github.com/timkendrick/monaco-editor)

Not sure why typescript isn't flagging this as an error.  But [this issue in TypeScript repo](https://github.com/Microsoft/TypeScript/issues/21#issuecomment-72304434) seem to suggest that this should already been disallowed.

**Comment by rebornix** [comment]
@kendrickw nice catch!
