### ISSUE TITLE
'Move to new file' refactoring for JavaScript and TypeScript

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#49866]
Add a new refactoring that extracts a class or function to a new file next to the current one. For example, for the simple project:

`code.ts`:

```ts
export class Foo { }
export class Bar { }
```

If the user highlights`Bar`, the `extract to new file` action would result in:

`code.ts`:

```ts
export class Foo { }
```

`bar.ts`:

```ts
export class Bar { }
```

**Comment by mohsen1** [comment]
Awesome! Love to see this happen in the next release!  

Per my example in #50474 extracted class/function should be exported from the new file and get imported into the original file.

**Comment by kakty3** [comment]
Why it is not working for `.jsx` files

**Comment by thomasjm** [comment]
Likewise for `.tsx` files, I press the button and nothing happens.
