### ISSUE TITLE
There's no way to find options in preferences file, only ways to filter them.

### ISSUE THREAD

**Issue by brocoli** [Microsoft/vscode#49862]
The Search bar in the preferences file only filters preferences.

This means that you can't check for related preferences around the one you searched for.

When you filter preferences there's also no indication where they may be in the default preferences file, since the filtering removes the categories from the view, and there's no way to jump to a particular preference.

**Comment by roblourens** [comment]
I don't have a good answer, but we are redoing the settings experience in general in #3355 to be more user friendly in general.
