### ISSUE TITLE
Support dragging instruction pointer during debug

### ISSUE THREAD

**Issue by Reanmachine** [Microsoft/vscode#4986]
Visual Studio's Debugger has a really useful feature that lets you drag the instruction pointer around while debugging, it's great for replaying a section if you missed something or skipping over logic that you're not interested in.

![Example](http://i.imgur.com/kuYKGSB.gif)

It would be really nice if this was available in VSCode.

**Comment by weinand** [comment]
@isidorn the debug protocol provides support for this.

**Comment by isidorn** [comment]
@weinand good to know. Still not very excited about this feature since it feels very IDE-ish for me

**Comment by eamodio** [comment]
I would love this ability -- moving the instruction pointer. Although I don't feel at all strongly that drag and drop need to be there, just the ability to set the location of the ip.

**Comment by ckasabula** [comment]
Miss this being a long-time (20yr) VS user. Agree that drag/drop isn't necessary. Dragging of breakpoints is supported, which VS doesn't support. Would be tricky to differentiate what to drag if IP is on a line w/ a breakpoint.
