### ISSUE TITLE
Emmet abbreviations not working in vue files

### ISSUE THREAD

**Issue by MartCube** [Microsoft/vscode#49864]
I was working on a Vue project while received the latest update for my VScode . 
When I installed the update , the Emmet abbreviations did not work in my **vue template**.
I tried emmet in ordinary html file and it works fine.
I assume that something is wrong with the new update.
Does anyone has a solution or a working setup to share ?

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Extensions:
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.48
vscode-eslint|dba|1.4.8
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
debugger-for-chrome|msj|4.4.3
vetur|oct|0.11.8
material-icon-theme|PKi|3.4.0
LiveServer|rit|4.0.0
autoimport|ste|1.5.3
open-in-browser|tec|1.1.0
bootstrap4-vscode|the|4.1.1
JavaScriptSnippets|xab|1.6.0

**Comment by ramya-rao-a** [comment]
@MartCube Please log this issue in the repo for the vetur extension. Emmet in vue files comes from the vetur extension

**Comment by MartCube** [comment]
Updating Vetur solved my problem!
