### ISSUE TITLE
Searching for additional color themes from the command palette should carry search terms

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#49860]
When searching for additional themes via the command palette's "Install additional color themes..." should carry the user's search terms into the search query:

**Current**
![image](https://user-images.githubusercontent.com/35271042/40024929-c75b8fb4-5784-11e8-8429-7196b0bcfade.gif)

**Expected**
![ezgif com-gif-maker 4](https://user-images.githubusercontent.com/35271042/40024935-ce316c5a-5784-11e8-9caa-b40cccb9c240.gif)

**Comment by usernamehw** [comment]
Duplicate of #40518

**Comment by roblourens** [comment]
Thanks @usernamehw
