### ISSUE TITLE
VSCode freezes as long as containing folder is opened

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#49876]
Issue Type: <b>Bug</b>

Right click on a file, choose "Open containing folder". Folder openes in File manager. While folder is opened, VSCode is completely frozen. Close folder to VSCode work normal again.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.16.8-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.55GB (6.12GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.6.0
vscode-simple-icons|Lau|1.8.3
vscode-todo|Mat|0.8.0
material-icon-theme|PKi|3.4.0
vscode-docker|Pet|0.0.26
html-css-class-completion|Zig|1.17.1
Bookmarks|ale|0.19.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
githistory|don|0.4.1
vscode-npm-script|eg2|0.3.4
phpunit|ema|2.1.1
php-intellisense|fel|2.3.1
text-transform|flo|0.1.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
search-node-modules|jas|1.3.0
vscode-phpfmt|kok|1.0.25
vscode-apache|mrm|1.1.1
python|ms-|2018.4.0
azure-account|ms-|0.4.0
cpptools|ms-|0.17.0
Go|ms-|0.6.80
php-docblocker|nei|1.6.0
swaggitor|qns|0.1.1
gitblame|wad|2.4.2
nodejs-extension-pack|wad|0.1.9
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.6.0

(2 theme extensions excluded)

</details>

**Comment by DasJott** [comment]
I don't know about how the insiders build is and I can not install it here on my working machine.

Disable all extensions makes no difference.
VSCode reminds all clicks being made while frozen. They are all executed makro like on closing the file manager window.

Using Arch LInux with DDE and the DDE file manager here. Maybe that helps?

**Comment by mjbvz** [comment]
Please test on the insiders build: https://code.visualstudio.com/insiders/
