### ISSUE TITLE
Integrated terminal appears to blur

### ISSUE THREAD

**Issue by hjfitz** [Microsoft/vscode#49878]
Issue Type: <b>Bug</b>

Resize the terminal and run something with a lot of output

VS Code version: Code - Insiders 1.24.0-insider (84d023798b51a8ad607fd865dd8e16949ee3c398, 2018-05-09T05:10:45.678Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.24GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_32776|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
material-icon-theme|PKi|3.4.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
code-runner|for|0.9.3
python|ms-|2018.4.0
polacode|pnp|0.2.2
sass-indented|rob|1.4.9
language-stylus|sys|1.9.2
vscode-import-cost|wix|2.6.2

(2 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/6014476/40041619-8d88a712-5816-11e8-98de-d8a57d31ca34.png)

**Comment by Tyriar** [comment]
Update your insiders, this is fixed.
