### ISSUE TITLE
intellisense does not work as expected

### ISSUE THREAD

**Issue by sudo-suhas** [Microsoft/vscode#49872]
Issue Type: <b>Bug</b>

When I try to use a typescript module from VSCode in common js, intellisense does not work correctly. Probably because of default export(I think). Since the package functionality works correctly but the intellisense does not, I am reporting this as a bug.

1. Create a new Node.js project (`npm init -y`)
2. Add [`sindresorhus/ow`](https://github.com/sindresorhus/ow) to the package(`npm i ow`)
3. Import the package in a JS file and trigger intellisense:
  ![image](https://user-images.githubusercontent.com/22251956/39978207-e24bfa84-575c-11e8-86d6-070144a7e087.png)
  ![image](https://user-images.githubusercontent.com/22251956/39978234-131d1580-575d-11e8-92e3-7f6d69066690.png)

I opened an issue(sindresorhus/ow#76) in the `ow` repository but they were not aware of any Typescript(export annotation?) workarounds to make the intellisense work correctly. If there is one, please do point me to the relevant resource. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2469)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|11.45GB (4.04GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.48
EditorConfig|Edi|0.12.1
CreateModule|Hoo|0.0.5
vscode-jest|Ort|2.7.2
code-settings-sync|Sha|2.9.2
markdown-emoji|bie|0.0.7
better-toml|bun|0.3.2
gitignore|cod|0.5.0
vscode-npm-source|dku|1.0.0
githistory|don|0.4.1
vscode-npm-script|eg2|0.3.4
code-runner|for|0.9.3
Go|ms-|0.6.80
vetur|oct|0.11.8
polacode|pnp|0.2.2
vscode-icons|rob|7.23.0
linter-xo|sam|2.1.3
shellcheck|tim|0.4.0
gitblame|wad|2.4.2
vscode-open-in-github|ziy|1.3.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is because of how ow's d.ts file is structured. It says:

```ts
export default = _default
```

If you want `require('ow')` to mean the same thing as `import ow from 'ow'`, I believe you instead need to write:

```ts
declare const _default: Ow;
export = _default;
```

**Comment by SamVerschueren** [comment]
@mjbvz Wouldn't that mean it should be imported as `import * as ow from 'ow'`? Because that's not what we want. We want to keep the default import style for ESM.
