### ISSUE TITLE
CPU spikes at 100% when going to definitions in JS files, search is slow

### ISSUE THREAD

**Issue by rpellerin** [Microsoft/vscode#49885]
- **Version:** 1.23.1
- **Commit:** d0182c3417d225529c6d5ad24b7572815d0de9ac
- **Date:** 2018-05-10T16:04:33.747Z
- **Shell:** 1.7.12
- **Renderer:** 58.0.3029.110
- **Node:** 7.9.0
- **Architecture:** x64
- **OS version:** Xubuntu 16.04

Installed extensions:
- `alefragnani.bookmarks`
- `dbaeumer.vscode-eslint`
- `eamodio.gitlens`
- `esbenp.prettier-vscode`
- `rebornix.ruby`
- `robinbentley.sass-indented`
- `sianglim.slim`

Steps to Reproduce:

1. Launch vscode from the command line, with an exported `PATH` containing nvm's node_modules, etc. It opens the last opened project, which is quite a big project with many npm dependencies and JavaScript source files
2. Control-click on a `import` statement in any JS file, I can see the blue bar telling me that it's searching/loading. After 10 to 20 seconds, the import is opened. During the search, CPU spikes at 100%.

I also witnessed such spikes while doing absolutely nothing in VS code.

Here is what `ps aux` tells me when the CPU load is at 100%:
```bash
romain   10197 68.0  3.9 1541964 648724 ?      Rl   10:15   9:13 /usr/share/code/code /usr/share/code/resources/app/extensions/typescript-language-features/out/utils/electronForkStart.js /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-tscancellation-7c7ad74bb1a46630a5b1.sock* --locale en
```

Here is my `jsconfig.json` file:

```json
{
  "compilerOptions": {
    "baseUrl": "./app/assets",
    "paths": {
      "modules/*": ["./javascripts/modules/*"],
      "*": ["./javascripts/*", "./images/*"]
    }
  },
  "include": ["app"], // I know this is redundant with exclude
  "exclude": [
    "node_modules",
    "bin",
    "ci",
    "config",
    "db",
    "lib",
    "log",
    "public"
  ]
}

```

Does this issue occur when all extensions are disabled?: Yes, same behavior.

Thank you!

**Comment by rpellerin** [comment]
I do, same behavior.

```
Version 1.24.0-insider
Commit 5799dec0ee9e7673cc013165a0132622f37b5e92
Date 2018-05-16T07:07:29.620Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by mjbvz** [comment]
@rpellerin In the latest VS Code insiders, try upgrading your workspace to use the latest typescript version by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

Does that fix the issue?

**Comment by rpellerin** [comment]
I tried, no improvement :/

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`

**Comment by rpellerin** [comment]
Also, with stable, I get
![image](https://user-images.githubusercontent.com/5323445/41988324-080584b4-7a3c-11e8-9e1e-189e17303d6b.png)

**Comment by mjbvz** [comment]
Thanks. First issue is #53166  Can you use the standard ubuntu process explorer to see the cpu usage of tsserver on insiders.

Have you also tried installing typescript@next into your workspace by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by rpellerin** [comment]
@mjbvz I'll post here the cpu usage of tsserver tomorrow.
As to installing typescript@next, yes I tried, no improvement.

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this

Please test using vscode-insiders which includes TypeScript 3.0. If you still see the problem, post up collect the cpu usage information
