### ISSUE TITLE
Source Action doesn't cancel stale request

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#49884]
* have a busy extension host or tsserver
* selection 'Source Action...'
* while the request is pending keep changing the selection or start typing
* 🐛 the new menu shows eventually, expectation is that the request should have been canceled because I went off doing something else

**Comment by mjbvz** [comment]
Yes not specific to source actions. Regular code action triggers do the same as far as I can tell. To repo:

1. Open vscode source
1. Quickly select a number in some js (for a refactoring) and hit ctrl+.
1. Move the cursor around
1. Once TS finishes loading, we show the code actions for the refactoring at where ever the cursor is currently
