### ISSUE TITLE
Debugger is crashing when trying to debug with "Step info (F11)"

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4988]
- VSCode Version: 0.10.12-alpha
- OS Version: windows10

Steps to Reproduce:
1. Launch app and open any folder which contains .ts file.
2. Set node debugger and generate launch.json.
3. Update program path to target correct .js file to debug.
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/test.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"preLaunchTask": null,
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},

4. Now start debugging and once debug options window is showing up keep debugging with
  "Step info (F11)".

![image](https://cloud.githubusercontent.com/assets/17735796/14301215/d9b78a8e-fb4a-11e5-824e-8993776b83ba.png)

**Actual: **

1. When I reached to the below line in timers.js and try to debug more then debugger is crashing 
![image](https://cloud.githubusercontent.com/assets/17735796/14301278/490b06ea-fb4b-11e5-8c05-dbcd9d44ec6a.png)
2. Debug options go away and output window displaying message: " Debugger is listening on port 26483").
![image](https://cloud.githubusercontent.com/assets/17735796/14301299/8966e38a-fb4b-11e5-9e3b-421c93e508d1.png)
3. No error message in chrome.

**Expected:**
![image](https://cloud.githubusercontent.com/assets/17735796/14301320/a7e2f0c4-fb4b-11e5-8862-2e1edfdf1ac1.png)

Note: Debugger is working fine for all other options : Continue (F5) , Step Over F(10), Step Out (Shift+F11), Restart and Stop (except "Step info (F11)").

**Comment by weinand** [comment]
@v-pavanp above you said "debugger is crashing".
Why do you think that the debugger is crashing?

**Comment by v-pavanp** [comment]
Because I am not getting expected output. Here I am expecting error message in the output window but it is showing up like:
https://cloud.githubusercontent.com/assets/17735796/14301299/8966e38a-fb4b-11e5-9e3b-421c93e508d1.png

Expected:
https://cloud.githubusercontent.com/assets/17735796/14301320/a7e2f0c4-fb4b-11e5-8862-2e1edfdf1ac1.png

Also while going further from line number 104 the debugger is closing suddenly and it is also closing open file in editor. (I am expecting it should go one step further when I am pressing "Step info (F11)").

**Comment by v-pavanp** [comment]
Info provided so removing more-info label.

**Comment by weinand** [comment]
can no longer reproduce.
