### ISSUE TITLE
Type Aliases can only be used in a .ts file

### ISSUE THREAD

**Issue by ruslan-bikkinin** [Microsoft/vscode#49894]
Issue Type: <b>Bug</b>

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.13.0-41-generic

## Description:

We are maintainers of [vscode-react-native](https://github.com/Microsoft/vscode-react-native) extension for VS Code and we have a lot of users requests for solving this (https://github.com/Microsoft/vscode-react-native/issues/631).

Currently, flow [does support type aliases](https://flow.org/en/docs/types/aliases/#toc-type-alias-syntax) and every modern React Native project supports type aliases for javascript files. Moreover, basic projects that has been generated via `react-native init <appname>` already has used type aliases for component props. In this case it looks very weird that VS Code doesn't support it for `javascriptreact` language.

There are several similar issues already (https://github.com/Microsoft/vscode/issues/15171, https://github.com/Microsoft/vscode/issues/25737) but none of them are opened but even forbidden for leaving any feedback. 

Also, Sublime and Atom doesn't have such problem.

![image](https://user-images.githubusercontent.com/30265843/40051674-4a5695e8-5844-11e8-9e43-546487d1b74e.png)

![image](https://user-images.githubusercontent.com/30265843/40052023-6c38380a-5845-11e8-8447-7c71e21a2e84.png)

## Steps to Reproduce:

1. Clone [blank React Native project](https://github.com/ruslan-bikkinin/rn631) that has been generated using `react-native init rn631` command.
2. Install node modules for project by using `npm i`.
2. Open it in VS Code.
3. Open `App.js` file and switch language mode to `Javascript React`.

## Expected Behavior

No problems found by VS Code

## Actual Behavior

![image](https://user-images.githubusercontent.com/30265843/40048557-372def2e-583b-11e8-8b35-e8b20bb8fe07.png)

**Comment by mjbvz** [comment]
Yes that's flow, not valid javascript. Not really sure what we are supposed to do since you cannot run that file without preprocessing it, and because even if we suppressed the error we would not actually use the type information correctly (since we don't understand flow)

I suggest disabling the built-in js/ts extension and installing the flow extension. That way you get rid of the error and get proper flow intellisense
