### ISSUE TITLE
The terminal process command '/bin/bash -l' failed to launch (exit code: 1)

### ISSUE THREAD

**Issue by Bibi10** [Microsoft/vscode#49898]
- VSCode Version: Version 1.23.1 (1.23.1)
- OS Version: MacOs High Sierra 10.13.4

Steps to Reproduce:

1.Try to open terminal 
2.The terminal process command '/bin/bash -l' failed to launch (exit code: 1)

Does this issue occur when all extensions are disabled?: Yes/No
![screen shot 2018-05-15 at 14 36 46](https://user-images.githubusercontent.com/15184336/40057049-7e092b86-584d-11e8-99a7-aafab781c7b4.png)

**Comment by Tyriar** [comment]
Are you on a corporate network? Can you run `/bin/bash -l` in an external terminal?

**Comment by Bibi10** [comment]
Yes, and after running /bin/bash -l  and an import of /bin/bash in my settings the terminal started working again.
