### ISSUE TITLE
Intellisense suggestions sometimes based off the last letter typed

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4989]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Start typing any Javascript. I was trying to get console 
2. When typed at the right speed intellisense will sometimes only suggest based off the last letter typed

![intellisenseletter](https://cloud.githubusercontent.com/assets/12900364/14301524/658fb278-fb4d-11e5-873a-9517434fcb53.png)

Sometimes it will be based off the last 2 letters you typed (again dependent of typing speed)
![intellisense2letters](https://cloud.githubusercontent.com/assets/12900364/14301546/96c8b592-fb4d-11e5-8cbb-fc9a91eb8138.png)

There are also suggestions in the list not related to 'con' at the bottom.

**Comment by alexandrudima** [comment]
@jrieken This looks like a UI-side issue?

**Comment by d4rkr00t** [comment]
Hi, it looks like a race condition, because if I type slow it filters suggest items correctly but when I type fast suggest is filtered based off the last letter typed:

![out](https://cloud.githubusercontent.com/assets/200119/14403708/825c01de-fe6a-11e5-95e8-974a9cd9bd2b.gif)

**Comment by d4rkr00t** [comment]
VSCode Version: 0.10.14-insider
OS Version: OSX 10.11.3

**Comment by d4rkr00t** [comment]
But I can't reproduce it on versin 0.10.14-insiders

**Comment by jrieken** [comment]
We made quite some changes for 0.10.14. Closing and keeping an eye open for this
