### ISSUE TITLE
Malformed Characters Not Visible

### ISSUE THREAD

**Issue by tmknight** [Microsoft/vscode#49897]
English
Version 1.24.0-insider
Commit 5d12f53178b72e88431347f8e248c49335a7fefc
Date 2018-05-14T05:16:26.538Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

I've noted that somehow a malformed character was created in a PS script I was working on.  However, it was not visible in Code.  I could only see it in native PS and PS IVE.

Bad character in PS IVE:
![image](https://user-images.githubusercontent.com/548588/40056578-d0223ef0-5819-11e8-8faa-3d7a4edc92b9.png)

Same code opened from same file as above in Code with BP enabled:
![image](https://user-images.githubusercontent.com/548588/40056581-d3a8bc7a-5819-11e8-9660-3ddbf9b38605.png)

**Comment by alexandrudima** [comment]
This is most likely a file encoding issue.

**Comment by bpasero** [comment]
@tmknight 
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by tmknight** [comment]
I'm **not saying** that VSC caused the malformed character.  I'm reporting that VSC **doesn't recognize** it as malformed.  VSC shows it as it is 'meant' to be, however the character truly is malformed and in the eyes of PowerShell.exe is treated as such.  Which is the correct and expected behavior in VSC.
