### ISSUE TITLE
Support EBCDIC encodings

### ISSUE THREAD

**Issue by ind1go** [microsoft/vscode#49891]
There are no EBCDIC encodings available in the encoding chooser when opening a file, making it impossible to read files in EBCDIC encodings like cp37 and cp1047.

🙋‍♂️   I'll happily take a look at this if someone can point me in the right direction to get started!

-----------

- VSCode Version: 1.23.0
- OS Version: MacOS

Steps to Reproduce:

1. Open a file which is in an EBCDIC encoding
1. ⌘+⇧+P to open the command palettle
1. Change File Encoding -> Reopen with Encoding
1. Weep when no EBCDIC options are displayed in the list 😢 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Depends on https://github.com/ashtuchkin/iconv-lite/issues/111

**Comment by lukebrowell** [comment]
https://github.com/ashtuchkin/iconv-lite/pull/112
