### ISSUE TITLE
[coffeescript] syntax highlighting broken when divide symbol is not separated using space

### ISSUE THREAD

**Issue by vedanshujain** [Microsoft/vscode#499]
<img width="231" alt="screen shot 2015-11-23 at 8 16 36 pm" src="https://cloud.githubusercontent.com/assets/7571618/11339358/2c163ae0-921f-11e5-80a4-510ef8c05863.png">

**Comment by aeschli** [comment]
We use the text mate grammar from https://github.com/textmate/coffee-script.tmbundle

**Comment by aeschli** [comment]
This issue was moved to textmate/coffee-script.tmbundle#8

**Comment by crisward** [comment]
I can confirm, using the same textmate bundle in sublime works, so this must have something to do with vscode.

**Comment by almarklein** [comment]
Hooray!

**Comment by vedanshujain** [comment]
Hey,
minor thing... this is still breaking at one point in my project which reduces to
<img width="121" alt="screen shot 2016-04-12 at 2 00 51 am" src="https://cloud.githubusercontent.com/assets/7571618/14441679/8e6e3f24-0053-11e6-9b5f-a6d21ae471d9.png">

**Comment by aeschli** [comment]
Yes, I know. The '/' character is both used for division and the start of a regex.  I can try to do some more tricks but from what I understand, only a context sensitive parser can get it 100% right.

**Comment by vedanshujain** [comment]
Can we at least change it to match only one line.. regexp with single '/' will always be in single line as opposed to a regexp block

**Comment by aeschli** [comment]
We process line by line, so the lookahead can only match on the current line. Did I miss anything?

**Comment by vedanshujain** [comment]
Yeah lookahead will only match the current line, however tokeniser definition currently have `begin` and `end` block which matches multiple line, as opposed to `match` block which block single line (see my change for reference). Now this will not solve the problem I commented above, however it will keep the erroneous colorising only to that line instead of expanding it to all the lines below it until it finds an `/`

For egs:
currently if we have
 ```
a = b/c + d/e
someOtherStuff
```
The text `someOtherStuff` will also be incorrectly coloured in current case. However, since regexp starting with `/` would always be single liner, we can change the tokeniser definition to user `match` instead of `begin` and `end` block which prevent incorrect colouring in `someOtherStuff` even though d/e is coloured incorrectly. Let me know if I have not explained clearly...

**Comment by aeschli** [comment]
@vedanshujain Thanks for the explanation. I understand. To make sure we won't match on multiple lines, I added the look ahead to the begin pattern.
The patterns are matched only against a single line, not the full content. So unless we don't see the regex on the same line, the rule will never be entered.
I improved the lookahead so now also your example works.

**Comment by lelandcope** [comment]
Is this fixed because I am having this issue on version 1.7.1 (macOS Sierra) where my multiline comments aren't working properly.

![image](https://cloud.githubusercontent.com/assets/4503835/20113714/6c4d96c6-a5a6-11e6-9ee4-d1f017d2a582.png)
