### ISSUE TITLE
Folding region starts on #endregion

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#49904]
Issue Type: <b>Bug</b>

Using the language specific folding:

![image](https://user-images.githubusercontent.com/9205389/40062758-3a2f53cc-585c-11e8-9889-7dcc427987ef.png)

![image](https://user-images.githubusercontent.com/9205389/40062918-852dd772-585c-11e8-98fd-39abf9ca49a3.png)

```ts
// #region 1

async function foo3() {
	
}

// #endregion

// #region 2

async function bar4() {

}

// #endregion
```

VS Code version: Code - Insiders 1.24.0-insider (0d376d890ceb406cabd2b4281deebf5f4038a78c, 2018-05-15T05:10:53.660Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_18792939|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (18)</summary>

Reproduces without extensions.

</details>

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/24152 to track this upstream

**Comment by chrmarti** [comment]
@mjbvz This seems to be planned for TypeScript 3.0. Should we reopen this issue to track it and then verify? (Trying to verify.)

**Comment by mjbvz** [comment]
I added a work around for this on our side. Here are the folding ranges I now see:

<img width="404" alt="screen shot 2018-05-31 at 10 49 21 am" src="https://user-images.githubusercontent.com/12821956/40798611-508cceea-64c0-11e8-95b9-c6ede73e1959.png">
