### ISSUE TITLE
Allow input on debug console without debug session

### ISSUE THREAD

**Issue by Gamadril** [Microsoft/vscode#49900]
I'm working on a language extension which can upload code to a connected device over serial port. It is not possible to debug the code in the classic way (breakpoints etc.), so creating a debug-adapter wouldn't make much sense. However the device can "print" messages back over serial port and also read from serial port during code execution.
With `vscode.debug.activeDebugConsole.appendLine()` I can show received messages to the user. However I could not find any API to get the input from the debug console directly. When I enter something there only "Please start a debug session to evaluate" appears.

It would be nice if the debug console could be also used as a "terminal" for custom input/output.

**Comment by isidorn** [comment]
Search for issues with label `feature-request` and `debug` if you want to find the exact duplicate

**Comment by Gamadril** [comment]
I did my best to find the corresponding issue. I found several issues like that one https://github.com/Microsoft/vscode/issues/35514. But they all seem to reference the OS shell.
Last comment from the issue above is:

> There is no good solution to differentiate REPL input vs. stdin input. Closing, since there are no plans to work on this.

However what I mean is just an "input" field for user input. Debug view already has it. Why not just allow an input listener on it? If there are no registered listeners - show an error about not existing debug session. Otherwise just call the listener with the input value without any complex logic behind it.

**Comment by isidorn** [comment]
Somewhat a duplicate of https://github.com/Microsoft/vscode/issues/34752
I understandt it is not 100% the same but this issue defently depends on that one. I can leave this open but in honesty I do not see us working on it in the immediate future. Thanks
