### ISSUE TITLE
Integrated terminal split view render issue in macOS full screen

### ISSUE THREAD

**Issue by mschristensen** [Microsoft/vscode#49907]
- VSCode Version: 1.23.1
- OS Version: masOS High Sierra 10.13.4

Steps to Reproduce:

1. Open VSCode and maximise it to full screen
2. Open integrated terminal
3. Click + to open a second terminal
4. From the second terminal, click 'split terminal' to open a third terminal. This will break the rendering of the second and third 'split' terminals. Note that it will render correctly if you minimise and then again maximise the window.

Does this issue occur when all extensions are disabled?: Yes

<img width="802" alt="screen shot 2018-05-15 at 15 35 47" src="https://user-images.githubusercontent.com/9295665/40063800-07bd8f5e-5856-11e8-81c6-003ac9534d54.png">

**Comment by Tyriar** [comment]
Strange, I haven't had any issues with layout since it was added. What was the state before this and does the prompt eventually display?

Also a screenshot of what you're expecting (after minimize/maximize) would be good.

**Comment by mschristensen** [comment]
This seems to be fixed with Version 1.24.0
