### ISSUE TITLE
Intellisense doesn't work with constant function parameters

### ISSUE THREAD

**Issue by startrekdude** [Microsoft/vscode#4990]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

[files.zip](https://github.com/Microsoft/vscode/files/205553/issue.zip)

1. Create a file called SomeAPI.js with the following content:
```javascript
var SomeAPI = (function () {
   "use strict";  
    var exports = {};
    
    exports.sayHello = function (name) {
        alert("Hello, " + name);
    }

    return exports;
})();
```
2. Create a file called SomeAPI.d.ts with the following content:
```typescript
declare namespace SomeAPI {
    function sayHello (name: string) => void;
}
```
3. Create a file called app.js with the following content:
```javascript
/// <reference path="./SomeAPI.d.ts"/>
(function (SomeAPI) {
    "use strict";

    var hello = function () {
        SomeAPI.sayHello(document.body); // Oops! No Intellisense!
    }

    document.addEventListener("DOMContentLoaded", hello);
})(SomeAPI); // This one works
```
4. Mouse over the line where it says "SomeAPI.sayHello" (in app.js). 

Observed Behaviour:
Visual Studio Code's Intellisense informs the user that SomeAPI is of the any type, as is it's child sayHello.

Expected Behaviour:
Visual Studio Code informs the user that SomeAPI is a namespace and that sayHello is a function that takes a string.

Why this bug is important to fix:
Immediately-Invoked Function Expressions were a common way of doing modules and scoping before ES6's (awesome) import statements. There is a lot of legacy code that still uses them.

**Comment by egamma** [comment]
Moving to TypeScript for investigation

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7928
