### ISSUE TITLE
Cannot install extension which has a version identifier (like x.y.z-whatever)

### ISSUE THREAD

**Issue by remss** [Microsoft/vscode#49905]
- VSCode Version: 1.22.2
- OS Version: Win10 amd64

Steps to Reproduce:

1. Take an extension that works fine, for example https://github.com/editorconfig/editorconfig-vscode
2. Create .vsix package and install it (`vsce package; code --install-extension EditorConfig-0.12.1.vsix`) => it works fine
3. Now change the version in package.json, with "0.12.1-beta.1"
4. Create .vsix package and install it (`vsce package; code --install-extension EditorConfig-0.12.1-beta.1.vsix`) => command failed with message `Implement me. Unknown stdin file type!`

**Comment by remss** [comment]
I have found a workaround: uninstall the extension before installing the new one.

    $ code --install-extension EditorConfig-0.12.1.vsix
    Extension 'EditorConfig-0.12.1.vsix' was successfully installed!

    $ code --uninstall-extension EditorConfig.editorconfig
    Uninstalling EditorConfig.editorconfig...
    Extension 'EditorConfig.editorconfig' was successfully uninstalled!

    $ code --install-extension EditorConfig-0.12.1-beta.1.vsix
    Extension 'EditorConfig-0.12.1-beta.1.vsix' was successfully installed!

**Comment by sandy081** [comment]
@remss I am not getting any errors while installing a vsix with above versions. I could do it without uninstalling.

Can you please try with latest version and let me know?
