### ISSUE TITLE
Inline git revert removes unrelated changes

### ISSUE THREAD

**Issue by pftbest** [Microsoft/vscode#49902]
Issue Type: <b>Bug</b>

Unable to reproduce on a small example, but can consistently reproduce on my closed source project.
I've lost some work because of this.
Here is a video: http://88.99.85.67:1337/vscode.mp4

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.16.8-1-ARCH

Extensions: none

**Comment by joaomoreno** [comment]
Can you try to narrow it down and reproduce with a smaller sample?

**Comment by pftbest** [comment]
@joaomoreno 
Here is a small project to reproduce
[vscode_corruption.tar.gz](https://github.com/Microsoft/vscode/files/2068512/vscode_corruption.tar.gz)

**Comment by joaomoreno** [comment]
@pftbest Kudos for the reproducible case! Love it.

**Comment by flaw600** [comment]
@joaomoreno I'll take a crack at it.

**Comment by flaw600** [comment]
@joaomoreno I'm unable to reproduce the issue in VS Code Insiders: Version 1.25.0-insider (1.25.0-insider). Can you please confirm that this is still an issue?

**Comment by pftbest** [comment]
I can still reproduce in
```
Version 1.24.1 (1.24.1)
24f62626b222e9a8313213fb64b10d741a326288
2018-06-13T17:36:01.396Z
```
and in
```
Version 1.25.0-insider (1.25.0-insider)
07d89abf1522a67f0e8105770505077f454ab021
2018-06-28T05:05:08.481Z
```

**Comment by flaw600** [comment]
@pftbest I'm not sure. I'm running the same version of insiders you are and I'm not able to reproduce any unrelated changes being reverted in inline revert with gutter

**Comment by pftbest** [comment]
@flaw600 Are you using macOS or Linux? I can reproduce on both this systems, but I never tried on windows.

**Comment by flaw600** [comment]
@pftbest macOS Sierra, however I may be missing something at this late hour. I'll check again tomorrow

**Comment by flaw600** [comment]
@pftbest oh I see it now. I think I know why it's doing it but I'll tackle it tomorrow

**Comment by pftbest** [comment]
Hello @flaw600 Did you manage to reproduce the issue?

**Comment by flaw600** [comment]
@pftbest yes I was able to reproduce the issue, but I haven't had time to work on it yet.
