### ISSUE TITLE
jsconfig.json - checkJs and exclude not working together nicely

### ISSUE THREAD

**Issue by brownbl1** [Microsoft/vscode#49910]
Issue Type: <b>Bug</b>

I have a jsconfig.json that looks like:
![image](https://user-images.githubusercontent.com/2136925/40063891-51923726-582c-11e8-8809-f0ace5c3ea4a.png)

My goal is to achieve the equivalent of adding `//ts-check` to all js files in my project. I also have some .jsx files I want to exclude, but even if I add the `**/*.jsx` pattern to the exclude section, I still get errors and squiggles in my jsx.
![image](https://user-images.githubusercontent.com/2136925/40064001-9d44b572-582c-11e8-9129-2648986056fd.png)

If I add `// @ts-nocheck` to this file, it removes all errors and squiggles.

But I know the exclude config section is doing _something_, because if I omit it I get many more errors that I didn't have otherwise.
![image](https://user-images.githubusercontent.com/2136925/40064199-0543ad9a-582d-11e8-8a0e-00f1f426b0d7.png)

So in summary, it seems that there is a bug here in that the exclude option does not function in quite the same way as `// @ts-nocheck`.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (17.68GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\benjamin.brown\Downloads\0000-ben-browns-test-spa.json|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
cake-vscode|cak|0.10.1
npm-intellisense|chr|1.3.0
xml|Dot|1.9.2
prettier-vscode|esb|1.3.1
gc-excelviewer|Gra|2.0.21
vscode-nuget-package-manager|jmr|1.1.6
graphql-for-vscode|kum|1.11.0
mssql|ms-|1.3.1
python|ms-|2018.4.0
csharp|ms-|1.15.1
PowerShell|ms-|1.7.0
vscode-icons|rob|7.23.0
vscode-coverage-gutters|rya|2.0.0
code-settings-sync|Sha|2.9.2
vscode-hexdump|sle|1.6.0
pdf|tom|0.2.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24133
