### ISSUE TITLE
Provide an active editor for webviews via window.onDidChangeActiveTextEditor

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#49915]
- VSCode Version: 1.24
- OS Version: Windows 10 x64

Steps to Reproduce:

1.  Setup an extension to listen to `window.onDidChangeActiveTextEditor`
2. Open a webview (markdown preview or something else)
3. Observe that the active editor is `undefined`

Can some sort of editor be returned so that an extension can get some identifying information about the webview -- its id, etc?

This limits extensions from being able to appropriately deal with webviews.

This is somewhat related to #49914

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
We discussed this but decided against it for the following reasons:

* Webviews are not editors, so we would need a new api. Introducing a new API for something like `onDidChangeActiveView` was too complex and heavy weight. 
* So instead we made webviews private to their creators. No other extension can get a handle to a webview that your extension creates.

Instead your extension must track which of its webview is currently active using the events on the webviews objects
