### ISSUE TITLE
IntellIsense and "custom debugger" lost after running "debug test" feature

### ISSUE THREAD

**Issue by DanielSSilva** [Microsoft/vscode#49916]
Issue Type: <b>Bug</b>

On a project that uses XUnit for unit testing, after using VSCode's feature to "Debug Test", I lose intellisense and that very same feature disapears until I restart...
Any idea what might cause it? Any logs that I can share?
I'm posting this here because I'm assuming that the "Debug Test" is a feature from VSCode and not from the Omnisharp extension. If it's not, I'll move the issue

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-41-generic (Mint 18.3)

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.4.0
gitlens|eam|8.2.4
docomment|k--|0.1.0
prettify-json|moh|0.0.3
csharp|ms-|1.15.1
PowerShell|ms-|1.7.0
code-spell-checker|str|1.6.10
vscode-todo-highlight|way|0.5.12

</details>

**Comment by weinand** [comment]
@DanielSSilva I‘m not aware of a VS Code „Debug Test“ feature. What debugger are you using.
