### ISSUE TITLE
How to debug Visual Studio Code

### ISSUE THREAD

**Issue by daneel0livaw** [Microsoft/vscode#49913]
Hi!

I would like to debug Visual Studio Code to see how it works, especially how the IntelliSense feature works. How can this be done? Can I do this WITHIN Visual Studio code, or do I need some 3rd party software to do this? If the only option is the latter, then could you please recommend me an app, and provide some tips how to do it? Thank you in advance.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#debugging
