### ISSUE TITLE
Bot: improve duplicate message 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#49912]
When an issue is closed as a duplicate by the bot, the bot should take into account the other labels on the issue and give a helpful message to the user to easily find the original issue. The message should contain a link to the search query of issues with the mentioned labels.

Example: user comes and says I want find widget in debug console
I put the following labels: `"*duplicate"`, `"debug"`, `"feature request"`
Bot says "this as a duplicate ..."(same as before) + "To find the original issue follow [this query](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Adebug+label%3Afeature-request)".

**Comment by Bharat123rox** [comment]
@chrmarti @isidorn I would like to take this up as an easier contribution before moving on to more advanced issues... I know that [this](https://github.com/Microsoft/vscode/blob/8a6811306160ddf02ae90592c1e5d782d591399c/.github/commands.yml#L63) is the segment to be edited. Any help on how to go about fetching labels dynamically from an issue / PR (using Github API or some other way?) would be appreciated, thanks!

**Comment by chrmarti** [comment]
@Bharat123rox Thanks for joining in. Unfortunately the code of the bot is not public at the moment and this issue will need code changes there. There are many other issues you can pick from, we usually label them as 'help wanted': https://github.com/Microsoft/vscode/labels/help%20wanted

**Comment by JacksonKearl** [comment]
See link in comment here https://github.com/microsoft/vscode/issues/112204

**Comment by isidorn** [comment]
AWESOME!!!!
@JacksonKearl thanks a lot
@jrieken you maybe no longer need your custom azure function
fyi @joaomoreno
