### ISSUE TITLE
TypeScript, string literal, compiler false positive error

### ISSUE THREAD

**Issue by bill-mybiz** [Microsoft/vscode#4991]
- VSCode Version: 0.10.11, 0.10.13-insider, 0.10.14-insider
- OS Version: Windows 10
- TypeScript Version: 1.8.9 locally via tsdk workspace, also occurs with this setting removed.
- Node Version: 4.1.1

Steps to Reproduce:

1) String literal declaration as follows (You can also download the source [here](https://github.com/ibgib/bibleGib)):
```
/** String literal with possible values. Used in place of an enum to allow string type. */
export type RequestType = 'LaunchRequest' | 'IntentRequest' | 'SessionEndedRequest';
export const RequestType = {
    LaunchRequest: 'LaunchRequest' as RequestType,
    IntentRequest: 'IntentRequest' as RequestType,
    SessionEndedRequest: 'SessionEndedRequest' as RequestType
};
```
2) Build the project (ctrl+shift+B) **with the file closed, i.e. not in the edit window**. In my project, I have created a task as follows:
```
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"args": ["-p", "."],
	"showOutput": "silent",
	"problemMatcher": "$tsc"
}
```
3) The compiler shows that there are multiple errors (for each of the above string literal declarations). When you navigate to the error (thus opening the file in a window), however, the error message disappears. If you compile with the offending file already open (in my case, either helper.ts or alexa-skills-kit.ts), the compiler error does not show at all.

Because it not showing up with the file open in a window, I would think that there is something funky going on with caching and the string literal feature. Possibly a TypeScript issue and not a VS code issue?  I am attaching a screenshot:
![false_positive_compile_error_string_literal](https://cloud.githubusercontent.com/assets/1253349/14301820/8d7acf30-fb60-11e5-9a36-d9a2bf4a5038.png)

**Comment by dbaeumer** [comment]
@bill-mybiz I think it is a mismatch of the external tsc command you are using and the tsserver. When you run tsc -version what is printed. If this is not 1.8.9 please upgrade tsc to version 1.8.9.

I am closing this because it is very likely a version mismatch between the external compiler and the internal TS service.

@bill-mybiz please ping if the versions are the same.

**Comment by bill-mybiz** [comment]
@dbaeumer That does indeed seem to be the case. 

It seems that in troubleshooting the previous Salsa+TypeScript issue, we switched to a newer version of node and didn't have TypeScript installed globally. So even though TypeScript is installed as a dev dependency locally for the project, the tsc compiler (versioning) relies on the global install of TypeScript. 

Thanks for your help.
