### ISSUE TITLE
Insiders is not showing full object values in Debug Console or value tooltip

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#49927]
Issue Type: <b>Bug</b>

I'm debugging an extension (therefore Node.js) 

1.23.1:
![image](https://user-images.githubusercontent.com/6913354/40075489-41d73a48-5831-11e8-8249-7613993858b6.png)

Insiders:
![image](https://user-images.githubusercontent.com/6913354/40075264-c6231598-5830-11e8-9082-4bf650883c70.png)

Easiest to repro:  
1) While debugging Node.js:
2) Type this into debug console:
  {a:{b:"hi"}}
3) Try expanding it
!) No additional data shows up

1.23.1:
![image](https://user-images.githubusercontent.com/6913354/40075709-d3dab1b8-5831-11e8-937b-0dab63313cc1.png)

Insiders:
![image](https://user-images.githubusercontent.com/6913354/40075612-979d65b0-5831-11e8-9d75-9ae0a888740b.png)

VS Code version: Code - Insiders 1.24.0-insider (5d12f53178b72e88431347f8e248c49335a7fefc, 2018-05-14T05:16:26.538Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31230 @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (5.86GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\Repos\vscode-azurearmtools|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tree-view|Cha|1.1.0
vscode-markdownlint|Dav|0.16.0
tslint|eg2|1.0.28
vscode-azurestorage|ms-|0.3.1
vscode-cosmosdb|ms-|0.7.1
vscode-language-pack-de|MS-|1.23.2
azure-account|ms-|0.4.0
azurerm-vscode-tools|msa|0.4.1
antlr4|nct|0.0.1

</details>

**Comment by isidorn** [comment]
@StephenWeatherford thanks for this great catch and for using insiders.
This was caused by my refactoring of how the debug session connects to the extension host for extension debugging.
A fix is to actually just remove the inactive state for the debug session since it is actually not used anywhere in a useful way.

Verifier
1. Start debugging an extesnion
2. Type this into debug console:
{a:{b:"hi"}}
3. Verify it expands properly

**Comment by StephenWeatherford** [comment]
Thanks!
