### ISSUE TITLE
Should provide option for "Show next statement" to get the current debug point.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4993]
When debugging the large app it is common scenario when user lose the current debug point.
To get the current debug point VSCode should provide an option "Show next statement" in the context menu (when user right click on editor).

Like in Visual Studio:
![image](https://cloud.githubusercontent.com/assets/17735796/14302630/02d566a4-fb58-11e5-8292-e9870e212ef4.png)

**Comment by jawn** [comment]
Any news on this topic?

**Comment by weinand** [comment]
no
