### ISSUE TITLE
how make comment link to other project file ?

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#49933]
hi, it a native way in vscode to add comment link to another method or class.
I want to alt+Click on a comment to bring me to the file.

example 
```javascript
//file:///C:/Users/jonle/Documents/Games/A%20New%20Fantastic%20Time/js/rpg_scenes.js#methodName
Scene_IntroTile.prototype.create = function() {
    console.log('create: ', create);
    //Scene_Base.prototype.create.call(this);

};
```
i want alt+click bring me to the local file `/js/rpg_scenes.js#methodName`
what the good way to do this, any plugin or native way existe ?
Thank a lot for help.
I find the way little long to make.

**Comment by mjbvz** [comment]
No built-in way, but an extension can do this. See the [extension editing extension](https://github.com/Microsoft/vscode/blob/6da964f2788a260185829db8407829c81684672d/extensions/extension-editing/src/extension.ts#L23) for example
