### ISSUE TITLE
vscode crashes running in docker

### ISSUE THREAD

**Issue by jmcfallargo** [Microsoft/vscode#49937]
- VSCode Version:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Linux Ubuntu 16.04 running in docker. Docker image based on Ubuntu 16.04

Steps to Reproduce:

VSCode crashes if I open an instance in which it automatically resumes opening an untitled workspace or a saved workspace.  

1. Run VSCode from docker.
2. Open a directory that is bind mounted in the docker container
3. VSCode will operate normally - file editing, debugging, etc
4. Close VSCode
5. Open VScode running out of the docker container again
6. open any file ==> crash

The work around is to do the following instead of step 6 above
6. File->Close Workspace (exit VSCode )
7. Open VScode running out of the docker container again
8. File->add folder to workspace

The workaround will work until you close and open using steps 1-6

I have run with full logging on and don't see any indications in the logs as to what the cause is.

In the script to run the docker image, I bind mount the current working directory and the following persistent directories:
-v ${VSCODE_EXT}:/home/user/ms/extensions 
-v ${VSCODE_DIR}:/home/user/ms/.vscode 
-v ${VSCODE_CONFIG}:/home/user/ms/code

I use the following as my docker launch command:
 "code -w -n --extensions-dir /home/user/ms/extensions --user-data-dir=/home/user/ms/.vscode"

I have tried running docker in privileged mode, disabled gpu, and extensions with the same behavior.

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
