### ISSUE TITLE
Paste sequence

### ISSUE THREAD

**Issue by dumal** [Microsoft/vscode#49931]
Issue Type: <b>Bug</b>

When I copy and paste a large string of characters the code does not completely glue. I tried to paste an svg image into base64.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5200  @ 2.50GHz (2 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|3.99GB (0.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\laragon\www\meat-app-starter|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28

</details>

**Comment by rebornix** [comment]
@dumal we don't support pasting rich text into VSCode but you can drag the file into VSCode and edit.
