### ISSUE TITLE
triple click in terminal should select entire line

### ISSUE THREAD

**Issue by AlJohri** [Microsoft/vscode#49935]
on most terminals, double click selects a single word, and triple click selects the entire line. in the integrated terminal, the definition of "line" seems different. in regular terminal, even if the line is long and is wrapped, it will select the full line.

in code, it only selected a piece of the line if it wraps

iterm2:

<img width="1280" alt="screen shot 2018-05-15 at 5 19 50 pm" src="https://user-images.githubusercontent.com/2790092/40084154-35a33820-5864-11e8-917c-b83e063ae68a.png">

code:

<img width="1199" alt="screen shot 2018-05-15 at 5 19 28 pm" src="https://user-images.githubusercontent.com/2790092/40084162-38c98464-5864-11e8-8f32-393db2a0df80.png">

I couldn't find any config option to change this behavior. I find myself surprisingly relying on it quite a bit.

**Comment by Tyriar** [comment]
Nice find 👍 created upstream bug https://github.com/xtermjs/xterm.js/issues/1456
