### ISSUE TITLE
没有侧边栏

### ISSUE THREAD

**Issue by sfjhahaha** [Microsoft/vscode#49940]
- VSCode Version: Code 1.18.1 **[Unsupported]** (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.4.8
jquerysnippets|don|0.0.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-pack-zh-hans|MS-|1.23.4
debugger-for-chrome|msj|4.4.3
background|sha|1.1.17
easysass|spo|0.0.6
open-in-browser|tec|1.1.0
JavaScriptSnippets|xab|1.6.0
html-css-class-completion|Zig|1.17.1

(6 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Use the `View: Toggle side bar visibility` command
