### ISSUE TITLE
After update, Select all is work wrong

### ISSUE THREAD

**Issue by TonyGao** [Microsoft/vscode#49949]
VSCode version 1.23.1
Node 7.9.0
Windows 7 64bit

Steps to Reproduce:

1. Open any file
2. Press Ctrl + a or use menu to select all

Then, the text area is alway selected, and I can't edit this file anymore, even after I close the editor and reopen VSCode, the files is also in that state. Is this a bug?

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@TonyGao My suspicion is drag and drop is blocking you. Can you try to set `editor.dragAndDrop` to `false` and see if you can reproduce?

**Comment by TonyGao** [comment]
It's my bad, after days it's not occur anymore, I don't know why, but I will close this issue.
