### ISSUE TITLE
Terminal process terminated when minimizing the workspace explorer

### ISSUE THREAD

**Issue by nhvu1988** [Microsoft/vscode#49946]
Issue Type: <b>Bug</b>

Description:

I'm using vscode to develop an application with angular cli and nodejs server and sometimes I got this error when minimizing the explorer

Steps:
1. Open 2 terminals, 
    - one is running `ng build -w` to detect changes on angular application
    - another is running `node server` to run node application
2. Resize the workspace explorer to minimum size
3. Randomly, one terminal will turns off and shows this error 
![ERR](https://i.imgur.com/9PSOmHB.jpg)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17666

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.89GB (12.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
EditorConfig|Edi|0.12.1
code-beautifier|mic|2.0.3
dotenv|mik|1.0.1
mssql|ms-|1.3.1
material-icon-theme|PKi|3.4.0
vscode-table-formatter|shu|1.2.1

</details>

**Comment by nhvu1988** [comment]
It occurs when changing position as well
![Error](https://i.imgur.com/TmDwePh.gifv)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
