### ISSUE TITLE
sidebar cannot sense file deletion from outside(e.g. delete in terminal)

### ISSUE THREAD

**Issue by cjqpker** [Microsoft/vscode#49947]
![1](https://user-images.githubusercontent.com/14192091/40094899-04d7dffa-58fc-11e8-9f9c-a4f7468549e0.jpg)
![2](https://user-images.githubusercontent.com/14192091/40094907-07f31114-58fc-11e8-8afe-56888870f58e.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28432
