### ISSUE TITLE
"connect ENOENT" accessing extensions

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#49942]
(also when attempting Help->Report Issue)

- VSCode Version: 1.23.1
- OS Version: win10.1803

Steps to Reproduce:

1. 'Help->Report Issue', or 'Show Installed Extensions'
2. popup: `connect ENOENT \\.\pipe\62fcf4e7f327dff3d6f32488846443de-1.23.1-shared-sock`

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Closing for now.
