### ISSUE TITLE
VSCode Debug for Electron stopped working after update to V1.23.1

### ISSUE THREAD

**Issue by hatpick** [Microsoft/vscode#49943]
This is what I had
```
       {
            "name": "Electron: Main",
            "type": "node",
            "protocol": "inspector",
            "console": "integratedTerminal",
            "request": "launch",
            "program": "${workspaceFolder}/main.js",
            "preLaunchTask": "my gulp pretask",
            "env": {
                "NODE_ENV": "development"
            },
            "sourceMaps": true,
            "outFiles": ["${workspaceFolder}/**/*.*"],
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
            "timeout": 30000
        }
```
I get the alert box error: Nodejs connect ECONNREFUSED

And it was working before 1.23.1, then I had to remove these two `"protocol": "inspector",
"console": "integratedTerminal"` to fix it.

Timeout was set to 30 secs, but the error says 10 secs.

vscode: 1.23.1
OS: Windows 10

**Comment by roblourens** [comment]
> And it was working before 1.23.1, then I had to remove these two "protocol": "inspector", "console": "integratedTerminal" to fix it.

Do you mean it works now if you remove `"protocol": "inspector"`?

What version of Electron? Older versions won't work with inspector.

**Comment by roblourens** [comment]
And, does it launch electron successfully?

**Comment by hatpick** [comment]
Electron version is 2.0, with the above configuration it doesn't work, when I remove those two lines, it works. It used to work right before I updated to vscode 1.23.1

**Comment by roblourens** [comment]
> Electron version is 2.0, with the above configuration it doesn't work

But does it launch electron? If not, what do you see in the terminal?

I want to know, does it launch electron and fail to attach, or fail to launch electron?

**Comment by hatpick** [comment]
No it doesn't launch electron.

**Comment by roblourens** [comment]
- Does it work if you get rid of the preLaunchTask?
- Can you set `"trace": true`, and see whether it writes the path to a log file in the debug console? If so, please upload it here.

**Comment by roblourens** [comment]
Then can you run it separately in a terminal so you can try the launch config without a preLaunchTask?

**Comment by hatpick** [comment]
```
{
            "name": "Electron: Main",
            "type": "node",
            "protocol": "inspector",
            "console": "integratedTerminal",
            "request": "launch",
            "program": "${workspaceFolder}/main.js",
            **"preLaunchTask": "my gulp pretask",**
            "env": {
                "NODE_ENV": "development"
            },
            "sourceMaps": true,
            "outFiles": ["${workspaceFolder}/**/*.*"],
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
            "timeout": 30000
        }
```

without pretask launches the electron.

**Comment by roblourens** [comment]
> I don't get the previous error.

Oh well, please follow up if you figure out what was happening
