### ISSUE TITLE
Cannot update Insiders build --> crash of inno_updater.exe

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#49953]
- VSCode Version: 1.24.0-ins
- OS Version: win7x64

```
Version 1.24.0-insider
Commit 987c3dccf45ef0447b7b4c52c81794fab2b6dad5
Date 2018-05-11T05:16:29.994Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Update is downloaded... pressing "Install Update", then "Update now"....
... and crash of the "**_inno_updater.exe_**"

![image](https://user-images.githubusercontent.com/24613274/40097477-029d82d4-58df-11e8-95c3-4fae66a11414.png)

docs - [inno - crash.zip](https://github.com/Microsoft/vscode/files/2007557/inno.-.crash.zip)

Any thoughts?

**Comment by bburhans** [comment]
I can reproduce this on the Windows 7 Professional using the **stable** Visual Studio Code version below when it tries to upgrade itself to 1.23.1.

Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by joaomoreno** [comment]
@user3323 Is this really a process crash? What does the alert dialog say?

**Comment by user3323** [comment]
@joaomoreno  yes, it's a typical crash dialog.

I think here is one in English:

![image](https://user-images.githubusercontent.com/24613274/40704214-2c489332-63f0-11e8-9531-226fb8092562.png)

but it happened 2 weeks ago... for now it's fixed

**Comment by joaomoreno** [comment]
Good to know, closing for now.
