### ISSUE TITLE
Right click event is triggered for the bottom left corner of  'Settings' button

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode#49958]
Issue Type: <b>Bug</b>

Rpeo Steps:
1. Open VS Code.
2. Right click the bottom left corner of  'Settings' button.

Expect:
Nothing happened.

Actual:
Right click event is triggered.

More info:
There should display a tooltip for the 'Settings' button.

VS Code version: Code - Insiders 1.24.0-insider (d9299d952a59cb93a399eaf5bd38eb52e25fbdd4, 2018-05-16T05:16:02.701Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|8.00GB (3.94GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cosmosdb|ms-|0.7.2-alpha
azure-account|ms-|0.4.0

</details>

**Comment by bpasero** [comment]
I like this behaviour as you can right-click, keep the mouse button down, go over an entry and release to trigger.
