### ISSUE TITLE
Tab Close Icon Hidden Behind Action Menu

### ISSUE THREAD

**Issue by bbyrdsong** [Microsoft/vscode#49954]
Issue Type: <b>Bug</b>

If you have an upper right Action menu with more than 2 action icons, the complete action menu bar covers the far right tab's close icon.  Work around of course is right-click, Close or press Ctrl-F4.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.16.0
gitlens|eam|8.2.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
beautify|Hoo|1.3.0
solidity|Jua|0.0.43
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.4.3
vscode-docker|Pet|0.0.26
vscode-icons|rob|7.23.0
quokka-vscode|Wal|1.0.124

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@bbyrdsong screenshot?
