### ISSUE TITLE
Suggest widget in launch.json is inconsistent

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#49951]
Have noticed this on several occasions. Not doing anything special.

- Open a launch config, start typing a prop name
- Suggest widget appears
- Continue typing a few more characters
- It disappears
- Continue typing and it alternately appears/disappears

![may-15-2018 21-32-26](https://user-images.githubusercontent.com/323878/40096827-990a9c14-5887-11e8-80f8-8c64ddc8948e.gif)

**Comment by jrieken** [comment]
Not for me...

![may-16-2018 09-26-31](https://user-images.githubusercontent.com/1794099/40102619-41390d9a-58eb-11e8-90ee-4dccdb5541c2.gif)

**Comment by roblourens** [comment]
It doesn't always happen but it seems to get into a state where it happens consistently. I've seen it a few times over the past week at least.

How can I debug it next time I see it?

**Comment by jrieken** [comment]
Any chance you have emmet enabled? Or another extension that contribute results to json?

**Comment by roblourens** [comment]
No emmet-specific settings. I don't think I have any relevant extensions.

**Comment by jrieken** [comment]
Well, debug time then. Check/log how [`cancel`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestModel.ts#L207) is being called, esp while typing... Because focus loss and various things trigger this I'd using `console.log(new Error().stack)`

**Comment by roblourens** [comment]
I haven't seen this again.
