### ISSUE TITLE
Particular Font Gets Rendered Incorrectly

### ISSUE THREAD

**Issue by krtk6160** [Microsoft/vscode#49957]
- VSCode Version: 1.23.1
- OS Version: Ubuntu 16.04 LTS

The font Monaco gets rendered incorrectly. It is very thin in VS Code, but normal in other text editors. Even changing the `fontWeight` doesn't fix the problem. This problem doesn't occur with other fonts.

This is not the same as #35675, because the font isn't distorted, it looks like it's lower resolution somehow.

Here's a picture of VS Code with Sublime Text side-by-side for comparison.

![vscodeanomaly](https://user-images.githubusercontent.com/17320781/40101184-49a6843a-5904-11e8-9b22-5060950effde.png)

Steps to Reproduce:

1. Open user settings
2. Set `"editor.fontFamily": "Monaco"`

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
Font rendering in the editor is handled by Chromium. Please try to reproduce in Chromium and file an issue against them.

**Comment by krtk6160** [comment]
I'm not sure how to do that.
Should I just install chromium and change system font to Monaco to see if the problem exists there too?

**Comment by alexandrudima** [comment]
@krtk6160 Here is a website that uses `Monaco`:

http://jsbin.com/saquhuyeti/edit?html,js,output

![image](https://user-images.githubusercontent.com/5047891/40551471-50775aba-603d-11e8-90f6-fbb1cb83005a.png)


Since we use the same rendering engine, I expect Chromium to render the same text in the same buggy way. If you find, for example, that Firefox renders Monaco correctly, you can create an issue against Chromium...

**Comment by krtk6160** [comment]
@alexandrudima I tried to reproduce the problem in chromium, but was unable to do so.
I installed chromium version `58.0.3029.110-0ubuntu0.16.04.1281` and it rendered the font correctly. I also tried it on the latest stable chrome and it works perfectly.

**Comment by alexandrudima** [comment]
@krtk6160 Can you please try a recent insiders version where we have upgraded to Chromium `61.0.3163.100` ?

https://code.visualstudio.com/insiders/

**Comment by alexandrudima** [comment]
Indeed, it looks like today's linux x64 build didn't succeed. Most likely it will be out tomorrow.

![image](https://user-images.githubusercontent.com/5047891/41239949-a4a3fb20-6d99-11e8-8247-5e92bfcd721c.png)

**Comment by krtk6160** [comment]
I tried the latest 1.25 Code - Insiders build, and the problem remains. I even reinstalled the font, but even that didn't help. Does this rule out chromium as the source of the problem?

**Comment by krtk6160** [comment]
@alexandrudima Something interesting just happened. I changed the font size after reinstalling the font, and it works fine now. The problem occurs when the size is set to `14`, but not when it's set to `14.5`, `15`, or even `13`.

![vscodefontissue](https://user-images.githubusercontent.com/17320781/41285396-9e33840c-6e59-11e8-8e69-5379c1074ffd.gif)

I think I'll just keep the size to `14.5` for now and hope the problem gets fixed somehow in future builds.
Thank you for your time.

**Comment by alexandrudima** [comment]
That is absolutely crazy! Perhaps there is some persistent font cache somewhere for that font size that needs to be reset?

**Comment by krtk6160** [comment]
@alexandrudima I was able to reproduce the problem in Firefox, Chrome (version 66), and Chromium (versio 58) as well now, and it only exists when the font size is 14px. I only know the `fc-cache -fv` command, which I've already run and it doesn't seem to fix the problem.

**Comment by krtk6160** [comment]
@alexandrudima I was finally able to fix the issue. I had to disable bitmap fonts for Monaco by editing the `~/.fonts.conf` file.
This is what I added to the file that fixed the issue:
`<match target="font">
  <test qual="any" name="family">
    <string>Monaco</string>
  </test>
  <edit name="embeddedbitmap">
    <bool>false</bool>
  </edit>
</match>`

I found the solution [here](https://bbs.archlinux.org/viewtopic.php?id=188964).

**Comment by alexandrudima** [comment]
Thanks for following up and documenting the fix! :heart:
