### ISSUE TITLE
Terminal always hangs

### ISSUE THREAD

**Issue by kanonlemon** [Microsoft/vscode#49962]
Issue Type: <b>Bug</b>

Every time when i update the version, it backes to normal. \
But when restart, it hangs again

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (11.44GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.0.1
vscode-language-pack-zh-hans|MS-|1.23.4
python|ms-|2018.4.0
PowerShell|ms-|1.7.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169
