### ISSUE TITLE
Allow document formatter to be set for associated language in settings

### ISSUE THREAD

**Issue by MeikTranel** [Microsoft/vscode#49960]
Issue Type: <b>Feature Request</b>

Given the following workspace config:

```
{
    "files.associations": {
        "*.props": "msbuild",
        "*.targets": "msbuild",
        "*.proj": "msbuild",
        "*.csproj": "msbuild",
        "*.dproj" : "msbuild"
    },
    "[msbuild]":{
        "editor.tabSize": 2,
        "editor.insertSpaces": true
    }
}
```

When trying to use "Format Document" VSCode notifies the user that the MSBuild Project Tools Language Extension has not provided a document formatter.
As a user i would like to be able to expand on working associated language specific overrides, by adding a document formatter.

This could look something like this: 

```
{
    "files.associations": {
        "*.props": "msbuild",
        "*.targets": "msbuild",
        "*.proj": "msbuild",
        "*.csproj": "msbuild",
        "*.dproj" : "msbuild"
    },
    "[msbuild]":{
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
        "editor.documentFormatter": "vscode.xml"
    }
}
```

which would force vscodes built-in xml formatter to be used in spite of the missing language specific formatter.

VS Code version: Code - Insiders 1.24.0-insider (d9299d952a59cb93a399eaf5bd38eb52e25fbdd4, 2018-05-16T05:16:02.701Z)
OS version: Windows_NT x64 10.0.16299

**Comment by jrieken** [comment]
That's not really possible because we don't know those formatters statically. Formatters are registered dynamically for a language or a more complex set of documents (e.g. files on disk matching the foo/**/* pattern). Because of lazy activation the extension with the desired formatter might not yet be activated and to complicate things it might contribute multiple formatters...

**Comment by MeikTranel** [comment]
Shouldn't formatters have the same kind of exposure to the user as a debugger has? Exposed via central registry and then accessible via registry key like JSON Validation for example?
