### ISSUE TITLE
ESC is not dismissing context window

### ISSUE THREAD

**Issue by jmusser-claris** [Microsoft/vscode#49979]
Issue Type: <b>Bug</b>

When typing in VSCode an intellisense context window appears, normally I can press ESC and the window will dismiss.  As this does work most of the time, there are random moments where it will not work and I am forced to manually click somewhere in the application.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.48GB (7.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
cform|aws|0.0.10
vscode-eslint|dba|1.4.8
githistory|don|0.4.1
gitlens|eam|8.2.4
git-project-manager|fel|1.6.1
vscode-angular-components-intellisense|ipa|0.8.1
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|6.1.1
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.4.3
vetur|oct|0.12.1
vscode-docker|Pet|0.0.26
java|red|0.24.0
pdf|tom|0.2.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.8.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by maibatsu** [comment]
Same thing on KDE Neon.

```
VS Code: 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

OS: KDE Neon LTS 5.12
KDE Plasma: 5.12.5
KDE Frameworks: 5.46.0
Qt: 5.9.3
Kernel: 4.13.0-39-generic

CPU: Intel G1840
RAM: 8gb
```

**Comment by ramya-rao-a** [comment]
@jmusser-claris @maibatsu Do you have any sample code where you can repro this consistently? If not, we dont have much to go on with

**Comment by maibatsu** [comment]
@ramya-rao-a Sorry for late response. In my case, this happened in all my js projects, but right now it work as expected. :confused:

**Comment by ramya-rao-a** [comment]
Thanks for getting back @maibatsu 
@jmusser-claris Are you still seeing this? If yes, then can you provide a sample code where we can try?
