### ISSUE TITLE
Markdown preview stopped using some colors

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#49978]
Issue Type: <b>Bug</b>

For instance, blockquote border and links:

![md_preview](https://user-images.githubusercontent.com/9638156/40122725-2043cea8-592d-11e8-989b-03ef15ec12a5.gif)

VS Code version: Code - Insiders 1.24.0-insider (115ab2d6572df48d3548ed841e19eac5e7761721, 2018-05-16T12:59:04.240Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
Fixed link color by not using alpha channel. 

Can't find the color responsible for the blockquote.

**Comment by mjbvz** [comment]
Please provide repo steps. What theme colors are you setting?

**Comment by mjbvz** [comment]
Pushed a few fixed for block quote borders. Should be in the next insiders build

**Comment by usernamehw** [comment]
```json
"textLink.foreground": "#8fbf60ee",
```
