### ISSUE TITLE
Sluggishness lately 

### ISSUE THREAD

**Issue by mpicard** [Microsoft/vscode#49976]
Issue Type: <b>Performance Issue</b>

Lots of sluggishnes  lately since 1.2x, especially with git relation interactions like opening diffs, opening file from git tab, and lots of other sluggishness 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2380)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.49GB (3.41GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	   143	 24055	code main
    0	    16	 24058	   zygote
   12	   412	 24098	     window (ratings-target.reducer.spec.ts (Working Tree) - central-ui - Visual Studio Code)
    7	   159	 24801	       extensionHost
    1	    79	 25508	         electron_node tslintServer.js 
    3	   174	 25510	         electron_node electronForkStart.js tsserver.js 
    0	    48	 25571	           electron_node typingsInstaller.js 
    0	    63	 25706	         electron_node jsonServerMain.js 
    0	    95	 27235	         electron_node htmlServerMain.js 
    0	    48	 27256	         electron_node cssServerMain.js 
    0	    63	 24802	       watcherService
    0	    48	 25513	       searchService
    0	    48	 32015	       terminal
    0	     0	 32022	         /usr/bin/zsh
    0	    95	 24101	     shared-process
    3	   127	 24088	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ratings-target.reducer.spec.ts (Working Tree) - central-ui - Visual Studio Code)
|    Folder (central-ui): 474 files
|      File types: ts(233) html(180) scss(23) json(10) js(6) yml(4) png(2)
|                  css(2) xml(2) editorconfig(1)
|      Conf files: settings.json(1) package.json(1) tsconfig.json(1)
|                  tslint.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.28
fontsize-shortcuts|fos|1.5.0
language-haskell|jus|2.5.0
dotenv|mik|1.0.1
python|ms-|2018.4.0
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.4.3
angular2-inline|nat|0.0.17
typescript-hero|rbb|2.3.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Do you have sluggishness with other features?

**Comment by mpicard** [comment]
No, nothing else seems to be laggy. It's just the git tab. It's resolved itself on it's own at the time being. It could be a plugin but I have no plugins related to git. If it occurs again I will update. You could close this in the mean time. I'm still using same version 1.23.1 and same plugins so

**Comment by mpicard** [comment]
To be specific, whenever the UI was waiting for git command to return like refresh files, open a file, open a diff, etc all from git tab, it would be very slow to respond.

**Comment by joaomoreno** [comment]
Got it. Closing it for now.
