### ISSUE TITLE
[c#] projects.json auto-completion syhould use NuGet.Config

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#4997]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. Open project.json e.g. one of these https://github.com/aspnet/cli-samples
2. Copy NuGet.config from the sample repo also
3. Start typing "Microsoft.AspNetCore." and try to autocomplete, it does not give you right entries.

This is maybe because VS Code uses some other way (rather than omnisharp) to autocomplete the project.json. Or the bug is in OmniSharp.

This issue has been checked by other people in here: https://github.com/OmniSharp/omnisharp-roslyn/issues/413

**Comment by thecodejunkie** [comment]
I also noticed this today

```xml
<configuration>
  <packageSources>
    <add key="AspNet CI Feed" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

and I am only getting version (probably package names as well but I've not tried) info back from the main nuget feed

![image](https://cloud.githubusercontent.com/assets/50543/14541797/065f6082-028c-11e6-8ab8-f2c82fa5f5e9.png)

**Comment by Ciantic** [comment]
I must add that the project.json autocompletion bug may still be in OmniSharp only, and not in VS Code feature. There was some confusion at the time as it was figured out.

**Comment by aeschli** [comment]
Moving to omnisharp as the project.json completion support will be provided from there in the future.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#236
