### ISSUE TITLE
New outline:  no outline in IIFE 

### ISSUE THREAD

**Issue by paror** [Microsoft/vscode#49985]
Issue Type: <b>Bug</b>

In the new outline tool, there is no element visible in IIFE. 

For sample:
(function() {
    function foo() {}
})();

The function "foo" is not visible in the outline

(thanks for this new tool)

VS Code version: Code - Insiders 1.24.0-insider (5799dec0ee9e7673cc013165a0132622f37b5e92, 2018-05-16T07:07:37.740Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|12.00GB (1.65GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.9
vscode-language-pack-fr|MS-|1.23.0
debugger-for-chrome|msj|4.4.3
minifyandconcat|par|0.1.0
convert-css-in-js|pau|1.0.0
vscode-open|san|0.1.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
TS issue. Symbol search also does not work in this case
