### ISSUE TITLE
How to change vscode language.

### ISSUE THREAD

**Issue by aiaisl** [Microsoft/vscode#4998]
I'm update vscode to insider 0.10.14, Is happy to see vscode support Chinese in UI and comment. But the command translates Chinese too, is hardly to input, because I must change IME to type Chinese. Is any idea to deal this problem?

**Comment by dbaeumer** [comment]
Two things: 
- we are working on allowing to input command names in English as well.
- you can configure the language by either starting vscode with --locale="en" to switch back to English or by running "Configure Language" and edit the corresponding file.
