### ISSUE TITLE
html highlight is bugged when next tag starts with same prefix

### ISSUE THREAD

**Issue by phra** [Microsoft/vscode#49982]
HTML syntax highlight is broken when the next html tag starts with the same prefix of the previous one. see attached image.

![image](https://user-images.githubusercontent.com/984628/40124756-8b518a40-5929-11e8-8385-659d51b9745f.png)

- VSCode Version: 1.23.1
- OS Version:

![image](https://user-images.githubusercontent.com/984628/40124845-b7031546-5929-11e8-91bc-b853d1ce2168.png)

Steps to Reproduce:

1. `<p><i><img src=...`

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
@phra I'm not able to reproduce this. Can you give full file example? The editor is in HTML mode, right (not PHP or TS React)?

**Comment by phra** [comment]
@aeschli just create a new project with the following html: `<div><i><input></i></div>`. is maybe it related to the fact that the inner tag is self-closing?


![image](https://user-images.githubusercontent.com/984628/40171557-df89c65c-59cb-11e8-8360-3191c364cf4b.png)

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#84
