### ISSUE TITLE
Arquivos que fecham ao abrir outros

### ISSUE THREAD

**Issue by miwls** [Microsoft/vscode#49984]
Issue Type: <b>Feature Request</b>

PT-BR
Às vezes eu quero abrir mais de um arquivo no editor mas ao clicar no segundo arquivo se eu não tiver efetuado alguma alteração no primeiro este fecha e o segundo abre no lugar, por favor desativem essa função, eu quero deixar aberto mais de um arquivo no editor e não que ao clicar em um o outro feche

EN (Translated by google translator)
Sometimes I want to open more than one file in the editor but when I click on the second file if I have not made a change in the first this close and the second opens in place, please disable this function, I want to leave more than one file open in the editor and not that by clicking on the other close

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment]
Set `"workbench.editor.enablePreview": false` to disable this
