### ISSUE TITLE
Erratic tab behavior when opening files

### ISSUE THREAD

**Issue by strider72** [Microsoft/vscode#49987]
Issue Type: <b>Bug</b>

Tabs are weirdly erratic in VBCode.  I almost aways have multiple files open in different tabs.  My problem is that often times I'll go to open a file, and instead of opening in a new tab, it will replace a file I already had open.  I wanted both files open.  Sometimes it does this, other times it doesn't.  Other times, when I open a file, instead of opening it all the way to the right, where I would expect, it randomly creates a new tab somewhere in the middle of the existing tabs.

The tab-in-the-middle thing is minor; but the replacing an open file with a different open file really messes me up.  I lose track of what file I was using, which significantly disturbs my workflow.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.92GB (8.11GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
open-in-editor-vscode|gen|0.9.7
classic-asp-html|jtj|0.1.0
intellij-idea-keybindings|k--|0.2.23
mssql|ms-|1.3.1
printcode|nob|2.3.0
subtle-brackets|raf|2.1.1
lorem-ipsum|Tyr|1.2.0
omnipascal|Wos|0.15.0
highlight-trailing-white-spaces|yba|0.0.2

</details>

**Comment by mjbvz** [comment]
Have you tried setting: `"workbench.editor.enablePreview": false`?

**Comment by strider72** [comment]
Huh. Yep, that appears to be it.  Thanks.
