### ISSUE TITLE
Using up-arrow in Python terminal for conda env does not show last command

### ISSUE THREAD

**Issue by jn7dt** [Microsoft/vscode#49980]
(Copied from [vscode-python](https://github.com/Microsoft/vscode-python/issues/1690))

## Environment data

- VS Code version: 1.23.1
- Extension version (available under the Extensions sidebar): 2018.4.0
- OS and version: Windows 10 1709 (Build 16299.309)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.4 Anaconda (64-bit)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 
- Relevant/affected Python packages and their versions: 

## Actual behavior

- last command is not displayed in integrated terminal when up-arrow is pressed within Python REPL

## Expected  behavior

- last command would be displayed

## Steps to reproduce:
1. Ctrl + Shift + P -> Python: Create Terminal ![create_python_terminal](https://user-images.githubusercontent.com/23556165/40083478-41655168-5862-11e8-956d-94dfe2fbffc1.png)
2. (in terminal window) type "python" to start REPL ![terminal_start_activate_env](https://user-images.githubusercontent.com/23556165/40083483-47b7f714-5862-11e8-8c5e-08c52576a0b4.png)
3. (enter any command, for example:) test = 'testing' ![up_arrow_nothing](https://user-images.githubusercontent.com/23556165/40083485-498b031a-5862-11e8-8c2f-c3b58c45fed7.png)
4. press up-arrow to display last command (nothing happens) 

Starting REPL with Ctrl + Shift + P -> Python: Start REPL and then continuing with steps 3 and 4 results in the same issue.

**Comment by Tyriar** [comment]
Works for me when I launch a powershell terminal and run python in it, which I think is what the Python extension does https://github.com/Microsoft/vscode-python/blob/master/src/client/common/terminal/service.ts#L58-L76, not sure what that stripe_page stuff is doing though.

@brettcannon can you reproduce?

**Comment by brettcannon** [comment]
@Tyriar nope. Either this is some crazy readline issue, or it's the OP's Python install.

**Comment by jn7dt** [comment]
The "&cmd /k 'activate stripe_page & powershell'" is activating the conda virtualenv (stripe_page in this case).

You are right that in a normal integrated powershell terminal, the up-arrow works as expected within the Python REPL. However, I believe that calls the Python env on my system path rather than the virtual/conda env. Using the Python extension to start a terminal or REPL uses the virtual/conda env that I have selected. See version difference here when simply running "python" from powershell, and where up-arrow displays last command: 
![image](https://user-images.githubusercontent.com/23556165/40132415-b577a88c-590a-11e8-888f-c3ecc8dd61a2.png)

**Comment by brettcannon** [comment]
@jn7dt no, running `python3` from a standard terminal is not the same as `Python: Create Terminal` as the latter activates the conda environment as you noticed.

This is quickly sounding like there's an issue in your conda env in that readline or something is not installed and that's causing your REPL to not have history available (or somehow the way we have to activate your conda environment, but until conda natively supports PowerShell we don't have any other options either).

**Comment by jn7dt** [comment]
@brettcannon That could be the case, I can investigate that. However, running the same command to activate the env ("&cmd /k activate stripe_page") in an external powershell window works fine with all the terminal functionality expected. Maybe the strangest thing, on review, is that the same workflow in external and integrated terminals produces different results.

**Comment by brettcannon** [comment]
@jn7dt if you're not running that specific `PowerShell` call then that shouldn't drop you into a PowerShell prompt but instead cmd. If that's not the case then we can discuss changing how to we execute this on the extension over on vscode-python.
