### ISSUE TITLE
Feature request: more information in outline view

### ISSUE THREAD

**Issue by ljw1004** [microsoft/vscode#49995]
There doesn't yet seem to be an issue to track the question of extra information for nodes in outline view. Here's the list suggested by @MartinHaeusler - https://github.com/Microsoft/vscode/issues/5605#issuecomment-241707033

1. Public/private/protected. I'd hope these could be icon badges super-imposed on the existing icons.
2. Type signature of functions+methods+fields, in a separate typeface
3. Final/static/abstract/readonly indication. Again hopefully via a small badge on the icon.

**Comment by jrieken** [comment]
This is mostly duplicating https://github.com/Microsoft/vscode/issues/23927 which is about kind modifiers. Regarding more detail: we have a property for that in the proposed API but no one provides information yet

**Comment by jrieken** [comment]
We now have #23927 which did set the path for supporting public, private and static, abstract etc, etc. The signature of properties can be shown via the [details](https://github.com/microsoft/vscode/blob/bcaa2be1b51441fd11685e599b2704908f25a6f2/src/vs/vscode.d.ts#L2614-L2617)-field. 

Closing as most work left is in adding more SymbolTags and on extensions to populate the fields accordingly.
