### ISSUE TITLE
Feature request: Lock/Unlock adjacent tabs together so they don't get split up in tab bar

### ISSUE THREAD

**Issue by galilg** [Microsoft/vscode#49999]
Developing web apps requires working with the html and javascript (or angular component.ts), css files open side by side.  Sometimes they get split up by new tabs opening and you come back later to find them far apart.  It'd be nice to have an option to lock/unlock adjoining tabs to the left and right of each tab to be able to create blocks of tabs that you want to remain undivided.

**Comment by mjbvz** [comment]
Would better be addressed by #6328 and #21018
