### ISSUE TITLE
ja-JP Too translated default settings.json "window.reopenFolders"

### ISSUE THREAD

**Issue by ogasawara-k** [Microsoft/vscode#4999]
- VSCode Version:0.10.14-insider
 - with ja-JP locale
- OS Version:Windows 10

## Current
```
// 再起動後にフォルダーを再度開かれている方法を制御します。[なし] を選択するとフォルダーを再度開くことはありません。[1 つ] を選択すると最後に作業したフォルダーを再度開きます。[すべて] を選択すると前回のセッションのフォルダーすべてを再度開きます。
```

## Request
```
// 再起動後にフォルダーを再度開かれている方法を制御します。[none] を選択するとフォルダーを再度開くことはありません。[one] を選択すると最後に作業したフォルダーを再度開きます。[all] を選択すると前回のセッションのフォルダーすべてを再度開きます。
```

**Comment by johnliu2016** [comment]
@ogasawara-k can you attach a s/s indicating both "none", "one" and this long string? It makes sense to keep them consistent

**Comment by ogasawara-k** [comment]
Current

![default](https://cloud.githubusercontent.com/assets/16556202/14347457/226da5da-fcf2-11e5-8d4c-536795661a50.png)

**Comment by ogasawara-k** [comment]
@johnliu2016 attached Screen-Shot

**Comment by ogasawara-k** [comment]
another
![p2](https://cloud.githubusercontent.com/assets/16556202/14347999/cc3b83be-fcf4-11e5-826b-6b03fa1202ea.png)

**Comment by johnliu2016** [comment]
@ogasawara-k Thanks for the screenshots.

"none" and "one" are over-localized, this repro for chs, cht, deu, jpn, kor, rus. @Lukaschal Please revert the translations in following LCL file (e.g. of JPN)

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization?path=%2FLocalize%2Fjpn%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Felectron-browser%2Fmain.contribution.nls.resx.lcl&version=GBmaster&_a=contents

<Item ItemId=";reopenFolders" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Controls how folders are being reopened after a restart. Select 'none' to never reopen a folder, 'one' to reopen the last folder you worked on or 'all' to reopen all folders of your last session.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[再起動後にフォルダーを再度開かれている方法を制御します。[なし]5D; を選択するとフォルダーを再度開くことはありません。[1 つ]5D; を選択すると最後に作業したフォルダーを再度開きます。[すべて]5D; を選択すると前回のセッションのフォルダーすべてを再度開きます。]]></Val>
          </Tgt>
        </Str>

**Comment by ogasawara-k** [comment]
@johnliu2016 
and "all"  are over-localized,

**Comment by johnliu2016** [comment]
Thanks @ogasawara-k, @Lukaschal "all' also over localized in the same languages as "none"/"one"

**Comment by lukaschal** [comment]
DEU, RUS fixed. JPN, KOR, CHT, CHS waiting for linguistic input.

**Comment by lukaschal** [comment]
JPN:

再起動後にフォルダーを再度開く方法を制御します。'none' を選択するとフォルダーを再度開くことはありません。'one' を選択すると最後に作業したフォルダーを再度開きます。'all' を選択すると前回のセッションのフォルダーすべてを再度開きます。

KOR:
New translations implemented.

다시 시작한 이후에 폴더를 다시 여는 방법을 제어합니다. 폴더를 다시 열지 않으려면 'none'을 선택하고, 마지막으로 작업한 폴더를 다시 열려면 'one'을 선택하고, 마지막 세션의 모든 폴더를 다시 열려면 'all'을 선택합니다.

CHS:

控制重启后重新打开文件夹的方式。选择“none”表示永不重新打开文件夹，选择“one”表示重新打开最后使用的一个文件夹，或选择“all”表示打开上次会话的所有文件夹。

CHT:

控制重新啟動後重新開啟資料夾的方式。選取 [none] 永不重新開啟資料夾，選取 [one] 重新開啟最近一個使用的資料夾，或選取 [all] 重新開啟上一個工作階段的所有資料夾。
