### ISSUE TITLE
Copy-paste indented content results in incorrect indentation

### ISSUE THREAD

**Issue by rp0m** [Microsoft/vscode#50005]
**Steps to Reproduc**e:
**1**. Select and copy a block of multi-line, differently tabbed code
**2**. Paste it inside itself, by adding a new line
**Expected**: pasted code formatting is the same as copied code, plus any extra tabs
**Actual**: pasted code formatting changes from the copied code

This issue also occurs when pasting on another element. Normally this results in correctly indented first line and incorrectly indented following lines.

**Comment by mjbvz** [comment]
What language are you working in? Also please provide example code that demonstrates this problem

**Comment by rp0m** [comment]
This is mainly when working with HTML. Here is a sample (with line numbers):

Copy this:
```
1. <div>
2.     <div>
3.         <div></div>
4.     </div>
5. </div>
```
Add a line break between lines 2 & 3 (2 tabs automatically in this scenario), then paste the copied content into there. The resulting code is:
```
1. <div>
2.     <div>
3.             <div>                            // Tabbed twice instead of once
4.                     <div>                    // Tabbed twice instead of once
5.                         <div></div>     // Tabbed correctly
6.                     </div>                   // Matches the incorrectly tabbed opening tag
7.                 <div>                        // Does not match the incorrectly tabbed opening tag
8.         <div></div>
9.     </div>
0. </div>
```

This is a simple example, but this gets worse when pasting more things with various tabs. Ends up being a complete mess. The only way to stay sane is to run the auto-format on save, which I prefer not to do, as I prefer to manually style my code.

Does this illustrate the problem well enough?

**Comment by tommai78101** [comment]
Hello, I've been suffering from this issue when designing email HTMLs for a long while. I have finally found an older issue that explains the exact things that are considered as bugs.

Liking this issue, in hopes it raises priority.

**Comment by rebornix** [comment]
Thanks all for your feedback, let's track this issue in https://github.com/Microsoft/vscode/issues/32320 , which talks about similar bug (indentation adjustment when pasting, moving, entering) in HTML/PHP like language. All your input will be considered when we tackle this issue. 

For you now if the indentation adjustment makes pasting worser, you can turn this off by setting `editor.autoIndent` to `false`. Thanks again for your help!
