### ISSUE TITLE
[PHP] provideCompletionItems is not called for items inside of -> methods and also for variables starting with $

### ISSUE THREAD

**Issue by atishay** [Microsoft/vscode#50004]
Issue Type: <b>Bug</b>

If you register a `registerCompletionItemProvider` in an exptension for PHP, it is not always called and completion items are not provided in the following cases:

1. Variable name starts with $

```php
 arr_item = new ClassItem;
 a                         // Completion Item Provider called
```

```php
$arr_item = new ClassItem;
$a                          // Completion Item Provider not called
```

2. Arrow functions

```php
 arr_item = new ClassItem;
 arr_item.t          // Completion Item provider called for the keystroke t 
```

```php
 arr_item = new ClassItem;
 arr_item->t          // Completion Item provider not called for the keystroke t 
```

NOTE: The completion item provider is not registered with any trigger characters.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_10988154|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
MochaSnippets|Ala|0.0.1
All-Autocomplete|Ati|0.0.12
vscode-markdownlint|Dav|0.16.0
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
jquery-snippets|Hri|1.0.0
latex-workshop|Jam|5.4.0
vscode-jest|Ort|2.7.2
code-settings-sync|Sha|2.9.2
quokka-vscode|Wal|1.0.124
html-css-class-completion|Zig|1.17.1
jslint|ajh|1.2.1
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
riot-tag|cri|0.1.7
vscode-eslint|dba|1.4.9
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
php-intellisense|fel|2.3.1
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
ginfuru-vscode-jekyll-syntax|gin|0.0.5
docthis|joe|0.6.0
sublime-babel-vscode|jos|0.2.10
prettify-json|moh|0.0.3
extension-manifest-editor|ms-|0.1.5
python|ms-|2018.4.0
cpptools|ms-|0.17.0
sublime-keybindings|ms-|4.0.0
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.4.3
elm|sbr|0.17.0
code-spell-checker|str|1.6.10
html-preview-vscode|tht|0.1.1
cmake|twx|0.0.17
better-align|wwm|1.1.6

</details>

**Comment by jrieken** [comment]
> If you register a registerCompletionItemProvider in an exptension for PHP

How do you register it? Any trigger character associated with it? Also, when no trigger character is hit you use the php word definition and trigger when at the start of a word. Last, there are user-settings to disable these things and I wonder if you any of them set?

**Comment by atishay** [comment]
`context.subscriptions.push(vscode.languages.registerCompletionItemProvider('php', CompletionItemProvider));`

I can provide a dummy extension where you can put a breakpoint if needed.

**Comment by jrieken** [comment]
What is the php word definition?

**Comment by atishay** [comment]
I am not creating any PHP word definition separately (this is not a language server). Instead the code relied on whatever language definition is present by default in VSCode for PHP. I also tried adding [PHP intelligence](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) but did not get the correct calls.

**Comment by jrieken** [comment]
Ok, that means `$` and `>` aren't part of words and that you need to register those as separate trigger characters (arguably `$` could be a word character). This is how the default completion item provider does it: https://github.com/Microsoft/vscode/blob/c562bd257d1e6034df2dee83e1b24b538e8ab34a/extensions/php-language-features/src/phpMain.ts#L20
