### ISSUE TITLE
Information tooltips are clickable and selectable and get in the way

### ISSUE THREAD

**Issue by distinctdan** [Microsoft/vscode#50002]
Issue Type: <b>Bug</b>

If I hover over some code so that an information tooltip appears, that tooltip is both clickable and selectable, so that it gets in the way. There's no reason for this to be the case. Info tooltips should move out of the way when I move the mouse towards them, and they certainly shouldn't be clickable or selectable.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.0

</details>

**Comment by joaomoreno** [comment]
Lots of people use them to select their contents and copy the contents out. Sometimes the contents get too big so they need to be scrollable. Mouse interaction is necessary here.
