### ISSUE TITLE
Regex search yields zero results when matches exist

### ISSUE THREAD

**Issue by tedhudek** [Microsoft/vscode#50001]
- VSCode Version: 1.23.1
- OS Version: Windows 10,version 1709

Steps to Reproduce:

1. Clone https://github.com/MicrosoftDocs/windows-driver-docs.
2. Open repo in VS Code (staging branch).
3. `Ctrl+Shift+F`, turn on Use Regular Expression.
4. Search for: `^The.*?:$`
5. No results.
6. Remove `$` and search again.
7. Thousands of results.
8. Click the second result (`3dprint\3d-manufacturing-keywords-overview.md`)
9. Editor opens with file.
10. Re-add `$` at end of regex and search again.
11. One result (just the open file).
12. Close file and re-run search.
13. Zero results.
14. Expected result: 4625 matches

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Do your files use CRLF line endings? Most likely https://github.com/Microsoft/vscode/issues/36309#issuecomment-338476460

**Comment by tedhudek** [comment]
I would go as far as to say that this is totally broken. The best case result is the user doesn't trust Code for regex searching and goes off and uses another tool (my case). The worst case is they proceed on the understanding that a pattern doesn't match and never discover that it really does.

**Comment by tedhudek** [comment]
And why is the find in files behavior different if a file is open (i.e. we get a match, step 11 above)? Completely non-intuitive.

Cheap workaround is to insert `\s+` before `$`, for example: `^The.*?:\s+$`.  But still!

**Comment by roblourens** [comment]
Open files are searched in the editor model using the JS regex engine and there are a couple subtle differences between that and the Rust regex engine used by ripgrep, a tool that that search uses.

I guess #36309 is "\s matches CR" and this is "$ doesn't match CR".

This one we can actually work around automatically by replacing `$` with `\r?$`. That's a hack but sounds like maybe the right thing to do...

**Comment by tedhudek** [comment]
A separate issue could be that when invoking Find in Files, the output should be the same regardless of whether a file is open.  I understand there is a different engine used by `Ctrl+F` within a single file, and when using `Ctrl+Shift+F` across all files, but when using the latter, the output should not change when files are open or closed.

**Comment by roblourens** [comment]
That would be ideal and I wish I could make it work, but to support things like search finding matches in modified files, it's not practical.

**Comment by tedhudek** [comment]
It still seems counterintuitive that `\r?$` matches more things than `$`. At first glance, it would seem that the former is a subset (or equal set) of the latter.

**Comment by roblourens** [comment]
It's really `foo$` vs `foo\r?$` where the first matches nothing because ripgrep doesn't consider `\r` as `$`.

**Comment by tedhudek** [comment]
From my limited understanding, Windows uses CR+LF, or `\r\n`, but UNIX uses just line feed, i.e. `\n`. Is ripgrep equating `$` with `\n`? If so, then why does it matter what precedes the line feed? Sorry, just want to understand fully :)

**Comment by roblourens** [comment]
No problem at all. You are exactly right. But from ripgrep's perspective, `\r` is a character sitting between `foo` and `$` (if the line is `foo\r\n`, and your regex is `foo$`).

If the regex doesn't have a match for that character, then the regex engine stops matching when it reaches `\r`. If we insert an optional `\r` in that place, then the regex will match.

**Comment by tedhudek** [comment]
Of course! Got it :)

Thanks, Rob!
