### ISSUE TITLE
Grammar error in update text

### ISSUE THREAD

**Issue by TravisSpomer** [Microsoft/vscode#50008]
Issue Type: <b>Bug</b>

**Repro steps:**
1. Click the gear icon and click "Install update"

**Notice:**
Visual Studio Code 1.23.1 is being installed in the background, we'll let you know when it's done.

**Problem:**
Grammar error.

**Expect:**
After the word "background" should be a period or a semicolon.  A comma does not make sense in that context.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17134

Extensions: none

**Comment by mjbvz** [comment]
Please submit a PR

**Comment by mjbvz** [comment]
Fixed by #50063
