### ISSUE TITLE
window freezes when output large amount of data to Terminal

### ISSUE THREAD

**Issue by beatgates** [Microsoft/vscode#50011]
We have written the needed data into your clipTerminal using cmd, run:
npm test
The test successfully finishes, however terminal is no longer responsive, and so is the VS Code main.

a.test.js:
describe.only('some test', () => {
  it(`should return results `, () => {
    var r = []
    for (i = 0; i < 1440 * 365; i++) {
      r[i] = i
    }
    console.log(r.join())
  })
})

package.json:
{
  "name": "a",
  "version": "1.0.0",
  "description": "kk",
  "main": "index.js",
  "scripts": {
    "test": "jest"
  },
  "author": "me",
  "license": "ISC",
  "devDependencies": {
    "jest": "^22.4.3"
  }
}

**Comment by Tyriar** [comment]
Yeah, this will be tackled in various ways as time goes on. There's a PR out atm which should help a lot with this. https://github.com/xtermjs/xterm.js/pull/1399
