### ISSUE TITLE
It deletes my whole code

### ISSUE THREAD

**Issue by Xiurik** [Microsoft/vscode#50015]
So sometimes, when my team and i are coding (each one on his own computer) we are deleting code and copy code from one ts to another, and then one of the files we edited is deleted (his content only), at time we dont know whats the real issue and we think than when we do the CTRL+C simustanuisly like 6 times is when it happens.

**Comment by mjbvz** [comment]
This issue is not actionable. Please see [this guide](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests) for how to file a proper issue. Include: 

* VS Code version
* OS version
* Installed extensions
* Steps to reproduce
