### ISSUE TITLE
Not able to collapse class sometimes

### ISSUE THREAD

**Issue by Trevinlc1997** [Microsoft/vscode#50012]
Issue Type: <b>Bug</b>

Sometimes the bracket Collapse works well "{...}" but othertimes it doesn't give me the option to collapse the full class, hiding its contents completely. 

Here is the pactiular code I have trouble collapseing, it seems to only allow you to collapse private/public.

```
class session  : public std::enable_shared_from_this<session> 
{
public:
  session(tcp::socket socket)
    : socket_(std::move(socket))
  {
  }

  void start()
  {
    do_read();
  }

private:
  void do_read()
  {
    auto self(shared_from_this());
    socket_.async_read_some(boost::asio::buffer(data_, max_length),
        [this, self](boost::system::error_code ec, std::size_t length)
        {
          if (!ec)
          {
            do_write(length);
          }
        });
  }

  void do_write(std::size_t length)
  {
    auto self(shared_from_this());
    boost::asio::async_write(socket_, boost::asio::buffer(data_, length),
        [this, self](boost::system::error_code ec, std::size_t /*length*/)
        {
          if (!ec)
          {
            do_read();
          }
        });
  }

  tcp::socket socket_;
  enum { max_length = 1024 };
  char data_[max_length];
};


```

![screenshot from 2018-05-16 19-16-42](https://user-images.githubusercontent.com/24485362/40150218-fe779d98-593d-11e8-9efe-49458efe04ca.png)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.16.8-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 2731)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.66GB (10.90GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
gitlens|eam|8.2.4
cpptools|ms-|0.17.0
cmake|twx|0.0.17

</details>

**Comment by mjbvz** [comment]
The cpp extension needs to implement language aware folding (if they do not already). Our builtin c++ support just uses indentation based folding. 

Closing as extension candidate
