### ISSUE TITLE
Mac [Command+S] will make mouse out of focus

### ISSUE THREAD

**Issue by hoperyy** [Microsoft/vscode#50014]
Issue Type: <b>Bug</b>

Mac

 [Command+S] on keyboard will make mouse out of focus

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.4.0

<details>

![image](https://user-images.githubusercontent.com/5757051/40150774-4f22f48e-59ae-11e8-95c7-ca4fcd2160e2.png)

![image](https://user-images.githubusercontent.com/5757051/40150785-670c665c-59ae-11e8-8d7b-0e20982ecb8d.png)

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (5.91GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_4113388|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-language-pack-zh-hans|MS-|1.23.4
vscode-styled-jsx|bla|0.2.2
vscode-eslint|dba|1.4.9
tslint|eg2|1.0.28
json-tools|eri|1.0.2
qiniu-upload-image|imy|1.0.0
vue|liu|0.1.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
evermonkey|mic|2.4.5
prettify-json|moh|0.0.3
sublime-keybindings|ms-|4.0.0
vscode-paste-image|mus|0.9.5
vetur|oct|0.12.1
vscode-versionlens|pfl|0.21.0
partial-diff|ryu|1.1.0
stylelint|shi|0.36.0
vscode-markdown-paste-image|tel|0.7.1
markdown-all-in-one|yzh|1.3.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you clarify what you mean by out of focus?

**Comment by hoperyy** [comment]
![vscode](https://user-images.githubusercontent.com/5757051/40153160-f1ea45da-59ba-11e8-8661-b0b82ad8fdd4.gif)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by hoperyy** [comment]
Thanks a lot @bpasero @Tyriar .

It's finally a bug of VSCode plugin "JS-CSS-HTML Formatter", issue here: https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/90
