### ISSUE TITLE
cygwin command within terminal settings error ?

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#50010]
I want to access a Cygwin command within terminal of code.  I found [this](https://stackoverflow.com/questions/46061894/vs-code-cygwin-as-integrated-terminal/48545827#48545827) but when entering the setting into my user settings, terminal ceases to work ?

**Comment by Tyriar** [comment]
There's an answer directly below it with far more upvotes https://stackoverflow.com/a/46937756/1156119
