### ISSUE TITLE
git, Can not be used in new installation state

### ISSUE THREAD

**Issue by pch1024** [Microsoft/vscode#50019]
Issue Type: <b>Bug</b>

我最近新装了VS Code,我发现git不工作了，我只好自己下载了git,并配置相关vscode git 设定。
我依稀记得以前我安装完成可以立即投入工作，我很怀念那时候的VSCode。

I recently installed VS Code, and I found that git was not working. I had to download GIT and configure the vscode git settings. 
I rarely remember that I was able to work immediately before I installed it. I miss the VSCode at that time.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-wxml|cod|0.1.9
vscode-eslint|dba|1.4.9
app-migrator|deb|0.0.3
vscode-html-css|ecm|0.2.0
we-app-vscode|eme|0.8.0
prettier-vscode|esb|1.3.1
vue-snippets|hol|0.1.5
vscode-language-pack-zh-hans|MS-|1.23.4
vetur|oct|0.12.1
minapp-vscode|qiu|1.0.4
JavaScriptSnippets|xab|1.6.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
> git was not working

What's the actual error? A screenshot would be helpful.
