### ISSUE TITLE
Highlight changed lines

### ISSUE THREAD

**Issue by BankofFunny** [Microsoft/vscode#50023]
Issue Type: <b>Feature Request</b>

Changed no saved lines / Changed saved lines should be conspicuous in minimap and line number bar

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
Are you using source control? The changed lines already show up in the gutter if you are

**Comment by Gruntfuggly** [comment]
I've noticed that staged changes don't show in the gutter.

**Comment by fishpen0** [comment]
I also have experienced the issue that staged changes do not show in the gutter.  Staging a file causes the gutter highlights to vanish.  It would make more sense for staged changes to be highlighted with a different color and still be revertable or diff-viewable from clicking the gutter highlight.

**Comment by alexandrudima** [comment]
@Gruntfuggly @fishpen0 This is as designed. The quick diff shows a diff from the index to the file on disk.
