### ISSUE TITLE
Conditional breakpoints

### ISSUE THREAD

**Issue by ggrimbert** [Microsoft/vscode#50026]
Hi,

I have a bug with conditional breakpoints. When I try to remove one, a popup shows (here in French), and it freezes the totallity my computer. I can't click, inside the popup or somewhere else; I can't switch screen / windows.The only way to take back control on my computer is to open a terminal and kill the vscode process.

It only happens with conditional breakpoints. 

I never had this problem with previous versions (Not very sure what was the last version I used with conditional breakpoints, I guess 1.22.1)

- VSCode Version: 1.23.0
- OS Version: Ubuntu 16.04

For information : 
Using Kubuntu, KDE V5.8.9; Plasmashell V5.8.9

Steps to Reproduce:

1. Add a breakpoint anywhere (tried only with Typescript code, not sure if this has any effect)
2. Open breakpoint and add any condition (right click -> edit)
3. Click on the breakpoint to remove it

![image](https://user-images.githubusercontent.com/15869188/40162009-ccd4e730-59b2-11e8-9d97-2f093bf11588.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Can you also reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
Does your screen also freeze for any modal dialog, for instance if you right click on a file in the explorer and choose delete?

**Comment by ggrimbert** [comment]
The same problem appears with the insiders version.
My screen freeze only for this one; If I open other modad dialogs I have no problem.

**Comment by isidorn** [comment]
@bpasero migh you have a clue why would the conditional breakpoint dialog be special?

**Comment by ggrimbert** [comment]
I've only seen this issue with this dialog; the others work as expected.

**Comment by isidorn** [comment]
Ok @jonathan-snark is als hitting it on some weird linux version.
I do not really have an idea why on some linux this dialog would freeze an electron app, but sounds like an electron issue.
If more users complain I could not show the dialog on linux as a workaround.

@jonathan-snark can you also reproduce this with other vscode modal dialogs?
@bpasero @weinand thoughts welcome

**Comment by RaphMu** [comment]
Hi, i also have this issue on Ubuntu 16.04.
But I was able to close the dialog with the key combination ALT+F4, seems to be frozen only for mouse clicks. And it freezes only with left mouse click, with right mouse click the breakpoint can be removed and edited.

**Comment by isidorn** [comment]
Since multiple users have reported this on linux ->
As a workaround I will simply not show this dialog on linux. Accidently removing a breakpoint is better than freezing your machine due to an electron issue.

**Comment by weinand** [comment]
@isidorn please create an Electron issue for this problem.

**Comment by isidorn** [comment]
I have created issue https://github.com/electron/electron/issues/13112
And have pushed a check if linux do not show the dialog
