### ISSUE TITLE
Menu mnemonics aren't underlined in Linux

### ISSUE THREAD

**Issue by sshock** [Microsoft/vscode#50022]
- VSCode Version: 1.23.1
- OS Version: Debian Linux 9.4

Steps to Reproduce:
1. Run visual studio code.
2. Open the File or any other menu.

Expected Results:
Mnemonics are underlined (e.g., the x in Exit).

Actual Results:
None of the mnemonics are underlined.

Why aren't they underlined on Linux?  It works properly on Windows.

**Comment by sshock** [comment]
Here are screenshots from Windows and Linux for comparison.

Windows:
![windows](https://user-images.githubusercontent.com/1693761/40155511-62b18f22-5951-11e8-8185-4bc6fe3168dc.png)

Linux:
![linux](https://user-images.githubusercontent.com/1693761/40155515-650a5b64-5951-11e8-96c1-24312514aec4.png)

**Comment by Tyriar** [comment]
Doesn't appear to be fixed under Electron 2/GTK3. @sshock you might want to see if it repros in Electron and report there https://github.com/electron/electron/issues

**Comment by sshock** [comment]
I installed electron (well, electron-quick-start) and sure enough the mnemonics were not underlined.

So I guess I need to report this upstream like you said.

**Comment by sshock** [comment]
Hmm, I don't know if we can say this is an upstream issue, because electron (at least electron-quick-start) doesn't show underlines on Linux or Windows.  It doesn't show underlines anywhere.

If electron never shows underlines, but vscode does on Windows but not Linux, that sounds like vscode is the one responsible for this.

**Comment by sshock** [comment]
On second thought, maybe it is an upstream issue.  I don't understand how all this works, but I just tested Slack as well, which is also based on electron, and it has the exact same issue (underlines not showing up on Linux, but they do on Windows).

**Comment by Tyriar** [comment]
A recent workaround for this is to use the custom title bar which we added to improve accessibility/theming:

```
"window.titleBarStyle": "custom"
```

**Comment by sshock** [comment]
That works great, thanks!

**Comment by bpasero** [comment]
Closing, given the workaround.
