### ISSUE TITLE
Custom highlighting that isn’t language dependent

### ISSUE THREAD

**Issue by trentonnesbitt** [Microsoft/vscode#50020]
custom syntax highlighting that is not language dependent. Like when these characters appear: “HFG” highlight #FF000 and so on.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please provide an example that shows the expected behavior

**Comment by trentonnesbitt** [comment]
@usernamehw That extension is exactly what I was looking for, thank you!
