### ISSUE TITLE
Intellisense and CLang-Format does not work

### ISSUE THREAD

**Issue by kamilosxd678** [Microsoft/vscode#50039]
- VSCode Version: 1.23.0
- OS Version: Debian 9 Stretch
- Language: C++

I am programmer myself so I know how vague "not working" is, but I have changed nothing and Intellisense suddenly stopped working. It does not want to autocomplete anything, on hover I just get Loading... for eternity, and when I Ctrl+Click on something - it just plays the loading animation (blue line from left side to right side of the screen). For Clang-Format addon, it was working fine and suddenly stoped - same thing like Intellisense. Reseting code does not help, rebooting does not help, reinstalling code does not help, reinstalling extensions does not help. I do not want to reinstall my whole system.

Installed Extensions:
- ms-vscode.cpptools
- austin.code-gnu-global
- xaver.clang-format
- webfreak.debug

Does this issue occur when all extensions are disabled?: No support for C++ Intellisense without extensions

**Comment by mjbvz** [comment]
Please file this issue against those extensions. They should be able to help you investigate what may be going wrong
