### ISSUE TITLE
 spawn REG ENOENT

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5003]
Issue Id: <b>9cf75569-f3dd-823a-a718-5d80301fedb9</b><br /><br />*Versions* <br />- 0.10.10<br />-  f291f4ad600767626b24a4b15816b04bee9a3049<br />-  43ff6af3d4564f59196caa9be4897fc33c15f24c<br />-  97d4ad1c55a82369f65078406ed770e8a34055fc<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />-  17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c<br />-  ef2a1fcaa553d14d7731b284a5ac5e4a55c42936<br />-  18ebb4a4f5491af7b16e91e42fc36410bbb2e4d7<br />*Stack* <br />Error: spawn REG ENOENT<br />    at exports._errnoException (util.js:837:11)<br />    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32) <no sourcemaps><br />    at onErrorNT (internal/child_process.js:344:16) <no sourcemaps><br />    at doNTCallback2 (node.js:442:9)<br />    at Immediate._tickCallback [as _onImmediate] (node.js:356:17)<br />    at processImmediate [as _immediateCallback] (timers.js:374:17)<br />

**Comment by aeschli** [comment]
Also many occurrences:

Error: spawn cmd.exe ENOENT 
 at exports._errnoException (util.js:837:11) 
 at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32) 
 at onErrorNT (internal/child_process.js:344:16) 
 at doNTCallback2 (node.js:442:9) 
 at process._tickCallback (node.js:356:17)

**Comment by alexandrudima** [comment]
Not clear who should get this or what one could do about it.

**Comment by egamma** [comment]
See also #5189

**Comment by egamma** [comment]
@bpasero any ideas?

**Comment by bpasero** [comment]
@egamma if I had to guess, I would think this is our "reg.exe" spawning on Windows to find out the machine identifier for telemetry.

**Comment by egamma** [comment]
@bpasero  looks like your guess is good, see this issue and this comment https://github.com/NativeScript/nativescript-cli/issues/1029#issuecomment-147467771.

>the log says that both reg.exe and xcopy.exe are missing. Please verify that your windows and windows system directories are correctly set in PATH environment variable as first entries

Since this is caused by a misconfiguration from the user we should protect against this exception and not treat this as an error telemetry event.

**Comment by bpasero** [comment]
@egamma fair enough, I noticed that later versions of winreg seem to have fixed the bad error reporting. they did not install an error handling when spawning reg.exe and this resulted in an uncaught error exception that bubbled all the way up to us. My fix is to update to winreg 1.2.0. I will also add test plan items for all Windows versions we support to ensure that this is not a breaking change for us.
