### ISSUE TITLE
Tasks in tasks.json not recognized

### ISSUE THREAD

**Issue by patrickhrastnik** [Microsoft/vscode#50036]
Issue Type: <b>Bug</b>

Since a few days VS Code doesn't recognize the tasks defined in workspace .vscode > tasks.json anymore. This previously worked.

What happened the past few days:
- I tried to update VS Code using the Update prompt provided in VS Code. That failed (see issue #49512)
- I updated my node and npm setup (globally) to the latest versions (npm version 6.0.1, node version 10.1.0)
I cannot exactly remember when the problem occured the first time. I don't know if it was after the failed VS Code update, or after the node/npm updates.

I hoped successfully updating VS Code to Version 1.23.1 (manually by downloading the setup from code.visualstudio.com) would fix this issue, but it didn't.

The gulp file and tasks.json were not modified ever since.
We use different code branches with the same setup, and in none of them VS Code recognizes the defined tasks.

Tasks are executeable in command line using "gulp" command - so the gulp file basically works.

Folder and file structure as follows (files provided as txt for Github compatibility):
[./vscode/settings.json](https://github.com/Microsoft/vscode/files/2012678/settings.txt)
[./vscode/tasks.json](https://github.com/Microsoft/vscode/files/2012664/tasks.txt)
[./gulpfile.js](https://github.com/Microsoft/vscode/files/2012662/gulpfile.txt)
[./package.json](https://github.com/Microsoft/vscode/files/2012681/package.txt)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (0.87GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Projekte\HolterOnline\test|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
vs-code-xml-format|fab|0.1.5
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.5.6
live-html-previewer|hdg|0.3.0
typings-autoinstaller|jvi|1.2.0
vscode-language-pack-de|MS-|1.23.2
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.4.3
material-icon-theme|PKi|3.4.0
vscode-sql-beautify|sen|0.0.4
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
The reason seems to be that your gulpfile is broken. Running `gulp --task-simple` in a terminal produces this for me:
``` 
module.js:540
    throw err;
    ^

Error: Cannot find module './config/modernizr'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\50036\gulpfile.js:28:24)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by patrickhrastnik** [comment]
Sorry, I didn't include the entire package / not all necessary files.
Here's a zip file with the entire branch content.
[test.zip](https://github.com/Microsoft/vscode/files/2016646/test.zip)

**Comment by patrickhrastnik** [comment]
@dbaeumer It's on both machines gulp@3.9.1

**Comment by dbaeumer** [comment]
Thanks. The reason why VS Code doesn't list any tasks is that `gulp --task-simple` doesn't list any although the tasks do exist. Does it list task correctly on your home machine. If so 
this is nothing VS Code can fix since it relies on the correct behavior of gulp. Can you open an issue against gulp to find out why this is the case?

**Comment by patrickhrastnik** [comment]
`gulp --task-simple` didn't list any tasks on my home machine, but VS Code showed the tasks anyway. That's what I'm wondering about.
The gulp command prompted on my home machine the same error as on my workstation - no default task defined.

**Comment by dbaeumer** [comment]
That is very strange since VS Code takes the output of gulp --task-simple parses it and shows those tasks. If this produces no output on both machines both shouldn't show any tasks. Do you have a tasks.json file on our home machine that is different than the one from the workstation?

**Comment by patrickhrastnik** [comment]
To test if it has any effect, I added a task "default" to the gulpfile and to tasks.json
But VS Code doesn't show up tasks anyway.
`gulp --task-simple` executes task `default`, but VS Code doesn't recognize the tasks.
I restarted VS Code to make sure it was not a caching issue. At first, when entering "task ", it seems like VS Code is looking for tasks, but it doesn't find any.
![image](https://user-images.githubusercontent.com/30524365/40604557-c1554a48-625f-11e8-9f3c-a86b0aeb03ea.png)

Please pull pending changes in patrickhrastnik/vscode-issue50036

**Comment by dbaeumer** [comment]
Pulling latest from your repository and executing `Run Task` lists the following tasks for me which seems correct:

<img width="483" alt="capture" src="https://user-images.githubusercontent.com/1931590/40605352-6d52b6a8-6262-11e8-8657-bb1ed0f18c63.png">

Doesn't this work for you?

**Comment by patrickhrastnik** [comment]
No, this didn't work for me. VS Code doesn't show the tasks.
Anyway, I may try to reinstall VS Code.
Thanks

**Comment by dbaeumer** [comment]
Any special global user settings ?

**Comment by patrickhrastnik** [comment]
I don't think so.
Here's the content of my user settings file

{
    "window.zoomLevel": 0,
    "workbench.iconTheme": "material-icon-theme",
    "material-icon-theme.showUpdateMessage": false,
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/dist": true,
        "**/.vscode": true,
        "**/typings": true
    },
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "editor.tabSize": 4,
    "editor.wordWrap": "on",
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\cmd.exe",
    "workbench.colorTheme": "Neon Vommit"
}

**Comment by dbaeumer** [comment]
Actually looks normal. I don't know why this is working for me but not for you :-(
