### ISSUE TITLE
Create a new file, "Permission denied writing to file (file:///home/james/go/src/github.com/jamesray1/stringutil/reverse.go)"

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#50031]
Issue Type: <b>Feature request</b>

Following the instructions while setting up Go, getting up to the second instruction here: https://golang.org/doc/code.html#Library, I got the errror in the title:  "Permission denied writing to file (file:///home/james/go/src/github.com/jamesray1/stringutil/reverse.go)". This happens also from the integrated terminal and from Terminal on Manjaro:

```
james at james-pc in ~/go/src/github.com/jamesray1/stringutil
$ touch reverse.go
touch: cannot touch 'reverse.go': Permission denied
```

Running `sudo touch reverse.go` works. However, having to do this every time is rather tedious, it would be good if there was a way to enable sudo permissions from a GUI within VS Code.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.14.39-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2130 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.52GB (0.73GB free)|
|Process Argv|/opt/visual-studio-code/code /home/james/.profile|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dot|Ste|0.0.1
better-toml|bun|0.3.2
Go|ms-|0.6.80
rust|rus|0.4.4
debug|web|0.22.0

</details>

**Comment by Tyriar** [comment]
If it happens on the default terminal and it's the Go documentation you should follow up with them

**Comment by Tyriar** [comment]
For me I run sudo once in the terminal and I don't need to again for some time. Maybe this is a config issue with Manjaro?
