### ISSUE TITLE
tag highlighting not working

### ISSUE THREAD

**Issue by Postnov** [Microsoft/vscode#50030]
При клике на тег блока я хочу увидеть где он заканчивается, вместо этого vsc подсвечивает такие же теги.

![image](https://user-images.githubusercontent.com/24803363/40164001-074e41c8-59c1-11e8-822c-54b239457961.png)

**Comment by mjbvz** [comment]
Translated:

> When I click on the block tag, I want to see where it ends, instead VSC highlights the same tags.

**Comment by aeschli** [comment]
Is the editor in PHP mode? if yes, then this is a known issue, duplicate of #2915.
