### ISSUE TITLE
Allow both "onFocusChange" and "afterDelay" for "files.autoSave"

### ISSUE THREAD

**Issue by vsDizzy** [microsoft/vscode#50035]
It would be nice to have both options enabled simultaneously.
I want rare saves during I'm typing code in the editor and instant save after I switched to the browser to see my changes in action.

Example:
```js
  "files.autoSave": ["onFocusChange", "afterDelay"],
  "files.autoSaveDelay": 10000,
```

Vote if you like this.

**Comment by enesaltinkaya** [comment]
I sometimes think ppl who develop this application are brain dead.

**Comment by MichalMichalak** [comment]
So... this never got implemented in the end???

**Comment by vsDizzy** [comment]
@MichalMichalak yes, not implemented, sadly.
