### ISSUE TITLE
Invert keyboard shortcuts overview (cheat sheet)

### ISSUE THREAD

**Issue by helmbold** [Microsoft/vscode#50042]
Currently the [overview of keyboard shortcuts](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) is of the form 

    shortcut -> action

Example:

    Ctrl + K Ctrl + C -> Add line comment

But that is like a phonebook with numbers first and names second! It is not like "uhm, let's see what I can do with `Crtl + K Ctrl + C` today" but the other way around: "How can I make a line comment?".

Speaking in code, the current state is like a `Dictonary<Shortcut, Action>` where you have to iterate over all values to find the desired key (the shortcut). What we need is like a `Dictonary<Action, Shortcut>`.

Invert the overview so that it is of the form 

    action -> shortcut

Example:

    Add line comment -> Ctrl + K Ctrl + C

**Comment by gregvanl** [comment]
@helmbold You have a fair point and it would match how the Keyboard Shortcuts editor displays Commands on the left and the Keybinding to the right. That said, it isn't too cumbersome to scan through the right column for a command.
Moving the issue to the vscode-docs repo for VS Code documentation and we can see if other people vote this issue up.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1625
