### ISSUE TITLE
鼠标选中问题

### ISSUE THREAD

**Issue by qin-ziqi** [Microsoft/vscode#50040]
Issue Type: <b>Bug</b>

描述：当用鼠标选中一段代码后，再次在别的地方单击想取消选中，并将鼠标悬停在某个位置时，会出现无法取消选中的问题，需要多次点击鼠标或者按键盘的方向键才能实现。
实际：鼠标选中后，再次单击无法取消选中；
预期：鼠标选中后，再次鼠标单击时，光标可以停留在预期的位置；

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.87GB (1.28GB free)|
|Process Argv|D:\MyDownload\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-html-css|ecm|0.2.0
vue-snippets|hol|0.1.5
Angular2|joh|6.1.1
Angular-BeastCode|Mik|6.0.15
vscode-language-pack-zh-hans|MS-|1.23.4
autoimport|ste|1.5.3
html-snippets|wge|0.1.5
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by octref** [comment]
Please use English to report your issue and attach a gif https://www.cockos.com/licecap/
I cannot reproduce your problem.

**Comment by qin-ziqi** [comment]
description: When you select a piece of code with the mouse, click again to uncheck it somewhere else, and hover the mouse in a certain position, there will be problems can not be unchecked, you need to click the mouse several times or press the arrow keys of the keyboard to achieve.

actual: After the mouse is selected, clicking again cannot uncheck.

expected: After the mouse selects a piece of code, the cursor can stay in the expected position when the mouse is clicked again;
