### ISSUE TITLE
Debugger control does not hide after run

### ISSUE THREAD

**Issue by leksiq** [Microsoft/vscode#50048]
Issue Type: <b>Bug</b>

When running node.js script by Ctrl-F5 debugger control is still visible despite of the script is finished.

![2018-05-17_16-51-04](https://user-images.githubusercontent.com/37418441/40182348-e0c6975c-59f3-11e8-93c3-8d9be7095568.png)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|19.73GB (11.82GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.23.0

</details>

**Comment by isidorn** [comment]
I just checked and VSCode if doing `start debug` with no breakpoints VSCode nicely gets the `terminated` event from the debug adapter and the debug toolbar is no longer shown.
However if I do "start without debugging" there is not `terminated` event coming from the debug adapter -> forwarding to @roblourens and @weinand

**Comment by roblourens** [comment]
This is the fix from the end of last month - `this.isExtensionHost` is a method :D I didn't catch that

![image](https://user-images.githubusercontent.com/323878/40246692-8345b7a8-5a7e-11e8-9f16-f2a45e95d4c2.png)
