### ISSUE TITLE
more context for this parameter pelase

### ISSUE THREAD

**Issue by aldonetti** [Microsoft/vscode#50041]
on file https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts
folks helping out with the translations would like to know what is the parameter gong to be replaced with - or get a sample, please. this is the string:
"Visibility cannot be toggled for this view {0}"

thanks!

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
Parameter that will be replaced here is the id of the view
