### ISSUE TITLE
Terminal doesn't return after python2 script ends

### ISSUE THREAD

**Issue by cechmanek** [Microsoft/vscode#50046]
Issue Type: <b>Bug</b>

// The terminal doesn't accept new commands if I click to close the image window. 
// The python2 script is still running, but I cannot force it to exit. I have to completely
// kill the terminal each time. A key press works as expected and ends the script
// full code that reproduces error:

import numpy as np
import cv2

if __name__=="__main__":
  black_square = np.ones([30,30])
  white_square = np.zeros([30,30])

  first_row = black_square.copy()

  for i in xrange(13):
    first_row = np.hstack([first_row, black_square * i%2])

  checkerboard = first_row.copy()

  for i in xrange(14):
    checkerboard = np.vstack([checkerboard, first_row])

  cv2.imshow('checkerboard', checkerboard)
  cv2.waitKey()

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.4.0-124-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.74GB (51.20GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
python|ms-|2018.4.0
cpptools|ms-|0.17.0

</details>

**Comment by Tyriar** [comment]
If it's a python issue there's nothing really that we can do.
