### ISSUE TITLE
20000+ characters not syntax highlighting

### ISSUE THREAD

**Issue by krum110487** [microsoft/vscode#50056]
- VSCode Version: 1.23.1
- OS Version: Windows 10 (latest)

Steps to Reproduce:

1. Paste in an xml or json or whatever you want with 20000+ characters

Does this issue occur when all extensions are disabled?: Yes

Hello, I know that there is a 20k limit, so this is less of a bug, and more of a desired feature. It would be nice if it told the user "Hey this file is huge and that is why it is not syntax highlighting" then maybe you could tell it to ignore the 20k count and just highlight it all regardless of the time it takes. Then you keep your performance as well as allow it to work anyway.

This came up for me because I wanted to check a large xml for a value and wanted the syntax highlighting to help read it, but it simply didn't highlight, so I started deleting characters until I got down to 19999.

It would have been nice to at least know WHY it wasn't working, or allow me to tell it to simply work. It would also be nice to be able to set that 20k to something higher optionally.

**Comment by alexdima** [comment]
In the meantime, there is a setting `editor.maxTokenizationLineLength` and a popup.
