### ISSUE TITLE
Admin Access required every day

### ISSUE THREAD

**Issue by chadgrant** [Microsoft/vscode#50057]
I work at a place where you have to go through many layers of red tape to get admin access to my workstation. Even after getting that access and adding whatever helper this is .... I get this pop up every day.

![image](https://user-images.githubusercontent.com/1848046/40191264-c8626f08-59b5-11e8-9658-367bc3a06ad7.png)

**Comment by joaomoreno** [comment]
Redownload VS Code, place it into your User's `Applications` folder. [Make sure it's not quarantined](https://apple.stackexchange.com/questions/104712/what-causes-os-x-to-mark-a-folder-as-quarantined). It should never ask you for credentials any more.
