### ISSUE TITLE
Stopped Working After Windows 10 April 2018 Update

### ISSUE THREAD

**Issue by wwmyers** [Microsoft/vscode#50052]
- VSCode Version: 1.23.1
- OS Version: Windows 10 April 2018 Update

1. Tried restarting computer and vscode,
2. Tried reinstalling vscode. Still not working.
3. Seems like editor is working behind the black screen, I just can't see anything behind the black screen. I can see the folder titles when I hover over with the mouse in both the file folders and the menu selector in the tree view. I can also adjust the width of the tree view even though I can't see the tree view.
4. Menu at the top seems to work just find, but none of the work space displays anything.

Does this issue occur when all extensions are disabled?:  Can't see the settings to be able to adjust
![vscode black screen](https://user-images.githubusercontent.com/8205297/40186317-cc1b4176-59c2-11e8-9a3e-c44719b9e0f2.PNG)

**Comment by wwmyers** [comment]
Just tried reinstalling it, still no changes.

**Comment by wwmyers** [comment]
Just tried installing atom editor, and it's doing the same thing but with a white screen. It must have something to do with the windows update. And yes, I've checked my system with windows defender. everything was just working a couple days ago and last night I did the update for windows. Now my editors aren't working.

**Comment by bpasero** [comment]
@wwmyers does it reproduce if you run `code --disable-gpu`?

**Comment by bpasero** [comment]
Ok let me know how that works out.

**Comment by wwmyers** [comment]
so far, vscode is still working like it never had an issue :) I'll wait for
next windows update.

**Comment by axisogai** [comment]
Same thing for me, not woking
