### ISSUE TITLE
workbench.action.openNextRecentlyUsedEditor doesn't work

### ISSUE THREAD

**Issue by CombeeMike** [Microsoft/vscode#50051]
- VSCode Version: 1.23.1
- OS Version: Windows 10, Version 1709

Steps to Reproduce:

* Set shortcut `ctrl + tab` for action `workbench.action.openNextRecentlyUsedEditor` and press it
* or call `Open Next Recently Used Editor` from "all commands" menu
--> Nothing happens in both cases. No menu is shown, selected tab/editor is not changed, ...

Also doesn't work from the "all commands" menu if I don't set the shortcut but leave it at its default `workbench.action.openNextRecentlyUsedEditorInGroup`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@CombeeMike this command is work to navigate in the history of documents, so in order for that to work you have to first "Go Back" in history (via that command). Can you try?

**Comment by CombeeMike** [comment]
Ok, it works after using `Go Back` but then the command doesn't make any sense anymore (at least for me) since I never use the `Go Back` command...

I guess I'm on the same track as #37366 then..
