### ISSUE TITLE
 Path must be a string. Received undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5005]
Issue Id: <b>d62ec6f0-0926-ab33-6205-be52435fc002</b><br /><br />*Versions* <br />- 0.10.13-insider<br />-  17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c<br />*Stack* <br />TypeError: Path must be a string. Received undefined<br />    at assertPath (path.js:8:11)<br />    at Object.win32.join (path.js:221:5)<br />    at new ConfigurationProperties (C:\Users\a123\.vscode-insiders\extensions\ms-vscode.cpptools-0.4.1\out\src\C_Cpp_ConfigurationProperties.js:24:35) <no sourcemaps><br />    at Object.setupConfigurationProperties (C:\Users\a123\.vscode-insiders\extensions\ms-vscode.cpptools-0.4.1\out\src\C_Cpp_ConfigurationProperties.js:163:15) <no sourcemaps><br />    at C:\Users\a123\.vscode-insiders\extensions\ms-vscode.cpptools-0.4.1\out\src\C_Cpp.js:70:66 <no sourcemaps><br />    at FSReqWrap.oncomplete (fs.js:82:15)<br />

**Comment by egamma** [comment]
FYI @asthana86

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscppsamples#2
