### ISSUE TITLE
vscode attach "PickPSHostProcess" command has no value

### ISSUE THREAD

**Issue by jwmarrott** [Microsoft/vscode#50058]
Issue Type: <b>Bug</b>

Debug w PowerShell Attach to Host Process
Choose PS Process
Error immediately pops up saying command has no value

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (9.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.7.0

![image](https://user-images.githubusercontent.com/31501070/40192769-94f6878c-59c2-11e8-9ec2-fd24a62df80f.png)

</details>

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
