### ISSUE TITLE
Global Search not working when folder name contains brackets: Error parsing Glob... invalid range

### ISSUE THREAD

**Issue by ivanhojvat** [Microsoft/vscode#50054]
- VSCode Version: 1.23.1
- OS Version: Windows 10

Steps to Reproduce:

1. name a source code folder like DEV [JKR-25]. Very important, must use brackets and this format [LETTERS-numbers]
2. on Visual studio code open that folder
3. do any global search, for example try to find jquery
4. below the search field an error appears
Error parsing glob '!/repo/DEV [JKR-25]/**/.git': invalid range 'R' > '2'

It seems that the folder name is being use as part of a regular expression.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please try Insiders, it should work there.
