### ISSUE TITLE
Backslash in code block causes markdown preview/rendering coloring issue

### ISSUE THREAD

**Issue by schallm** [Microsoft/vscode#50059]
- VSCode Version: 1.23.1
- OS Version: Windows 10 (1709)

Steps to Reproduce:

1. Create Markdown file
2. Paste following text
\```sql
select '\\' + foo from bar
\```
3. View preview

Interestingly, this seems to be an issue in several products... Github and TFS also color this incorrectly...  Do they all use the same coloring library?

```sql
select '\' + foo from bar
```
vs
```sql
select 'hello' + foo from bar
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
We use highlight.js inside the markdown preview for colorization. This is an upstream bug with their sql highlighter

Closing as upstream
