### ISSUE TITLE
how to wirte in task ouput 

### ISSUE THREAD

**Issue by ilove3q** [Microsoft/vscode#50068]
- VSCode Version: 1.23.1
- OS Version: win 10

I use extention run code to run the programe. But it is show in task output. I couldn't input there. The task show:  cannot edit in read-only editor . How to write there?
Thank you very much

**Comment by ilove3q** [comment]
Sorry, could you explain me clearly? I did it when i found on web but did not get results. Thanks

**Comment by dbaeumer** [comment]
@ilove3q can you please provide steps on how to reproduce your problem. It is very hard to understand from your description.

**Comment by ilove3q** [comment]
@dbaeumer when I installed code run and i could write some the valeur in the "output", but now, in the "output"does not allow writing. I change my setting code-runner.runInTerminal : true, the the programe show in terminal which can write the valeur. what happended?

**Comment by dbaeumer** [comment]
Sorry I am still not sure I understand you correctly.

You can not write into the terminal. The terminal shows the input / output of the program task you executed. Can you explain why you want to write there?
