### ISSUE TITLE
Visual code doesn't display files in some virtualized folders while dir cmd does (used GVFS)

### ISSUE THREAD

**Issue by abhijeeg** [Microsoft/vscode#50064]
Issue Type: <b>Bug</b>

- Clone a new gvfs os repo.
- open a folder in vscode.
- On the explorer pane in vscode, contents of some folders are dispayed while for some it is not displayed.
- using a dir command on cmd.exe shows the files in those folders.

I saw that the files not shown in the explorer pane were opened by a process Microsoft.VSCode.CPP.Extension.exe but still not displayed.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.17672

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|31.79GB (11.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.17.0
team|ms-|1.133.0

</details>

**Comment by timba64** [comment]
I have a similar problem. When I try add folder in Project, in the explorer pane in vscode, i see not all folders in folder /var.
I couldn`t see and work with my Projects in /var/www
VS Code version: 1.23.1 date: 2018-05-10T16:04:33.747Z (1.7.12)
OS version: Linux Mint 18.3 64bit (3.6.7)

**Comment by changddcn** [comment]
I have a similar problem too . when i open the  folder  /Users/dd/Desktop/mypython as a project ,the folder on the left didn't  display correct, appeared some same name folders,when i clicked one of them,error occored like this : (ENOENT: no such file or directory, stat '/Users/dd/Desktop/mypython/skyeye_a/download/bruteforce/mail/log')

**Comment by abhijeeg** [comment]
C:\WINDOWS\system32> code --verbose

[main 12:34:21 PM] Starting VS Code
[main 12:34:21 PM] from: c:\Program Files\Microsoft VS Code\resources\app
[main 12:34:21 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false }
[main 12:34:21 PM] Resolving machine identifier...
[main 12:34:21 PM] Resolved machine identifier: 1cab164d46bf85960f264e26fe385d30e468ca6012815b66b8071f78064cb23f
[main 12:34:21 PM] update#setState idle
[20908:0529/123422.875:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[20908:0529/123422.902:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[20908:0529/123422.919:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[main 12:34:23 PM] windowsService#whenSharedProcessReady
[main 12:34:23 PM] windowsService#startCrashReporter
[main 12:34:23 PM] windowsService#setRepresentedFilename 1
[20908:0529/123423.850:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[main 12:34:23 PM] IPC#vscode-workbenchLoaded
[main 12:34:24 PM] windowsService#isFocused 1
[20908:0529/123424.601:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[20908:0529/123426.869:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[20908:0529/123428.003:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[main 12:34:51 PM] update#checkForUpdates, state =  idle
[main 12:34:51 PM] update#setState checking for updates
[main 12:34:51 PM] RequestService#request https://vscode-update.azurewebsites.net/api/update/win32-x64/stable/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
[main 12:34:51 PM] update#setState downloading
[main 12:34:51 PM] RequestService#request https://az764295.vo.msecnd.net/stable/d0182c3417d225529c6d5ad24b7572815d0de9ac/VSCodeSetup-x64-1.23.1.exe
[main 12:34:54 PM] update#setState downloaded
[20908:0529/123502.578:INFO:CONSOLE(79)] "Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\abgautam\AppData\Roaming\Code\clp'

Error: ENOENT: no such file or directory, scandir 'C:\Users\abgautam\AppData\Roaming\Code\clp'", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (79)

**Comment by bpasero** [comment]
@abhijeeg would you be able to install node.js and do a little experiment? We are using node.js to access the file system and we could try to isolate this issue: https://nodejs.org/en/download/

**Comment by abhijeeg** [comment]
Sure.
Please let me know what is needed.

Br,
Abhijeet

Thanks and Br,
Abhijeet Gautam,

**Comment by bpasero** [comment]
@abhijeeg after you did that, can you:
* open a terminal
* type node
* in the command prompt from node type: `fs.statSync("C:\\Users\\abgautam\\AppData\\Roaming\\Code\\clp")`
* see if you get an error or any output

Anyone else on this thread you can try the same with your paths.

**Comment by abhijeeg** [comment]
@bpasero - It is indeed an error.

```
C:\Users\abgautam>node
> fs.statSync("C:\\Users\\abgautam\\AppData\\Roaming\\Code\\clp")
Error: ENOENT: no such file or directory, stat 'C:\Users\abgautam\AppData\Roaming\Code\clp'
    at Object.fs.statSync (fs.js:948:11)
>
```

**Comment by bpasero** [comment]
@abhijeeg then I fear there is nothing VSCode can do about it. I suggest you report this as a bug to the node.js team: https://github.com/nodejs/node/issues

Are you able to open the file just fine using the Windows explorer?
