### ISSUE TITLE
SCM gutter indicators do not work in workspaces

### ISSUE THREAD

**Issue by voidtrance** [Microsoft/vscode#50061]
- VSCode Version: 1.23.1 (SHA: d0182c3417d225529c6d5ad24b7572815d0de9ac)
- OS Version: Fedora 25

Steps to Reproduce:

1. Open a Folder of a project in Git
2. Save as new Workspace.
3. Close VSCode
3. Launch VSCode and open the same folder with "Open Folder..."
4. Open a file under Git revision control
5. Make a random change. SCM guttern indicators appear.
6. Close folder
7. Open workspace created in step 2.
8. Open same file as step 4.
9. Make a random change. This time gutter indicators do not appear. 

Does this issue occur when all extensions are disabled?: Yes

I've also tested this after removing my user configuration in ~/.config/Code. Same things happens. It appears that when working with workspaces, the SCM gutter indicators just don't work.

**Comment by joaomoreno** [comment]
I can't reproduce. Can you find a smaller step sequence which reproduces this? If you open the `Developer Tools`, do you see any errors there?

**Comment by voidtrance** [comment]
I am sure that you can shorten the step sequence. What I provided were enough steps to show both the working case and the non-working case.

The issue remains after toggling Developer Tools. I am not able to see any errors in any of the panes.

I've done more testing and this seem to be an issue with a specific project. This was a pre-existing project prior to me starting to use vscode. Opening the project as a folder and editing does show the gutter indicators. Opening the same project as a workspace does not.

I've tried deleting and re-creating the workspace for that project but that did not fix it.

I've also testing with other pre-existing projects but I can't reproduce the issue there. However, with the project having the issue, it's consistent.

Unfortunately, I can't share the project. I don't know where this goes from here. I am guessing that since you can't reproduce it, we would have to leave it alone.

**Comment by joaomoreno** [comment]
Maybe try to figure out what it is about that specific project that makes things different from all other projects?
