### ISSUE TITLE
Minimap and/or Minimap Slider isn't correct

### ISSUE THREAD

**Issue by m4xc4v413r4** [Microsoft/vscode#50069]
Issue Type: <b>Bug</b>

"editor.minimap.enabled": true
"editor.minimap.renderCharacters": true

The minimap slider, more specifically the highlight area it shows of where you are on the code is not the correct position.
I assume that highlight should go from the top line to the bottom line of the visible code   in the editor, but it's off by quite a lot.

You can see what I'm talking about in the following picture.
https://i.imgur.com/z3a1jVO.jpg

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|14.94GB (8.04GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.3.0
material-icon-theme|PKi|3.4.0
todotasks|san|0.5.0
wow-bundle|Sep|1.2.5
vscode-lua|tri|0.12.4

</details>

**Comment by m4xc4v413r4** [comment]
ok, this is really strange.
Today I open vscode, on the same project, same file, and the minimap highlight is on the correct place.

At first I was completely confused but then I found something strange.
When the "Side Bar" is open, the minimap highlight is correct, when it's closed it's not correct anymore.

[Gif example of this happening.](https://i.imgur.com/xnF0xdI.gifv)

This is making me think that it has something to do with "word wrap" / "max columns".

**Comment by alexandrudima** [comment]
@m4xc4v413r4 I see the problem in your GIF, but I could not reproduce.

I am pressing <kbd>Ctrl</kbd>+<kbd>B</kbd> and <kbd>Alt</kbd>+<kbd>Z</kbd> to toggle the sidebar or to toggle word wrap, but I don't observe the slider being off:

I wonder what other settings you have, if this reproduces when extensions are disabled and if this reproduces for any file or only for a specific file.

![kapture 2018-05-25 at 16 57 50](https://user-images.githubusercontent.com/5047891/40551340-e2469d30-603c-11e8-949c-bdccb3d49c37.gif)

**Comment by m4xc4v413r4** [comment]
@alexandrudima Can you do me a favor and try that with "editor.minimap.renderCharacters": true ?

To be honest I'm not sure of anything anymore.
I just did some more testing, with and without extensions, hiding and showing the Side Bar with mouse and keyboard shortcut, enabling and disabling word wrap, and I'm now more confused than ever.
I don't see consistency, some times the problem is there, some times it's not, other times the problem exists but goes away after closing and opening VSC without changing the settings.

I literally did the exact same thing as my previous gif, with same extensions and same settings, and now there's no problem when toggling the Side Bar.
I tried toggling the wordwrap after that because you menioned it and that breaks it for me again. I never touched it when I originally noticed the problem though, I don't think I ever touched wordwrap since I first turned it on and I've been using VSC since 0.10 or something so a couple of years.

I'mgoing to leave some more gifs here for different thing I tried.
If there's anything specific you want me to try, a specific test or any information I can provide you, feel free to ask for it.

With extensions. With minimap.renderCharacters on:
[Toggling Side Bar](https://i.imgur.com/W74wXRR.gifv) - Same test i had done on the other gif but not it works fine :/
[Toggling WordWrap](https://i.imgur.com/p69xUHG.gifv) - Breaks it pretty much the same way I was experiencing before, even though I never toggled wordwrap before. I even toggle the Side Bar at the end and it doesn't change anything, only the wordwrap does.

With extensions. With renderCharacters off:
[Toggling Side Bar and WordWrap](https://i.imgur.com/VoWMAw4.gifv) - The same two tests don't cause problems if renderCharacters is not enabled.

Without extensions every test results in the exact same thing as before:
[Toggling Side Bar and WordWrap with and without renderCharacter](https://i.imgur.com/3fAixP4.gifv)

So the problem might be between minimap.renderCharacter and word wrapping, maybe even their word wrapping limits (max columns) since we can put a limit on both the editor and the minimap.

My current settings are as following:

> {
> 	"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
> 	"window.zoomLevel": 0,
> 	"editor.wordWrap": "on",
> 	"window.menuBarVisibility": "toggle",
> 	"zenMode.fullScreen": false,
> 	"zenMode.hideTabs": false,
> 	"zenMode.hideStatusBar": false,
> 	"workbench.iconTheme": "material-icon-theme",
> 	"editor.minimap.enabled": true,
> 	"editor.minimap.renderCharacters": true,
> 	"editor.minimap.maxColumn": 120,
> 	"editor.insertSpaces": false,
> 	"editor.tabSize": 4,
> 	"editor.detectIndentation": false,
> 	"editor.acceptSuggestionOnEnter": "smart",
> 	"editor.renderWhitespace": "none",
> 	"editor.showFoldingControls": "always",
> 	"extensions.autoUpdate": false,
> 	"editor.quickSuggestions": {
> 		"other": true,
> 		"comments": false,
> 		"strings": true
> 	},
> 	"editor.multiCursorModifier": "alt",
> 	"git.enableSmartCommit": true,
> 	"workbench.startupEditor": "newUntitledFile",
> 	"editor.smoothScrolling": false,
> 	**"gitlens.advanced.messages": {
> 		"suppressShowKeyBindingsNotice": true,
> 		"suppressWelcomeNotice": true
> 	},**
> 	"files.trimTrailingWhitespace": true,
> 	**"gitlens.blame.ignoreWhitespace": true,
> 	"gitlens.gitExplorer.files.layout": "auto",
> 	"gitlens.keymap": "chorded",**
> 	"markdown.preview.scrollEditorWithPreview": false,
> 	"markdown.preview.scrollPreviewWithEditor": false,
> 	"markdown.preview.linkify": true,
> 	"[markdown]": {
> 		"editor.wordWrap": "on",
> 		"editor.quickSuggestions": true
> 	},
> 	**"lua.format.lineWidth": 500,
> 	"lua.preferLuaCheckErrors": true,**
> 	"editor.fontLigatures": true,
> 	"editor.fontFamily": "Fira Code, Consolas, monospace",
> 	"editor.fontSize": 13,
> 	"editor.fontWeight": "500",
> 	**"gitlens.historyExplorer.enabled": true,
> 	"gitlens.codeLens.enabled": false,
> 	"gitlens.hovers.currentLine.over": "line",
> 	"gitlens.mode.statusBar.alignment": "left",
> 	"gitlens.statusBar.alignment": "left",**
> 	"editor.minimap.side": "right",
> 	"editor.minimap.showSlider": "mouseover"
> }

This includes the extension related settings (the ones in bold), those obviously are irrelevant on the no extensions tests.

**Comment by alexandrudima** [comment]
Do you see any problems in the console? `F1 > Developer: Toggle Developer Tools` or in the logs `F1 > Developer: Show Logs... > Window (VS Code)` ?

Do you perhaps have CJK characters in that specific file. It might be a dup of #49378

**Comment by m4xc4v413r4** [comment]
No errors, some [Violations](https://i.imgur.com/kVKnmVz.jpg) though (I think the JS ones happened while recording the gif that I have linked at the end here), and found out some more things.

So far all my tests were done with the window using half the screen (I use a 21:9 2560x1080 screen) using Windows Snap feature.

Because I opened the console to test what you wanted I noticed that when I go above a certain width on the VSC window size, the behavior changes (you can actually see when this happens by looking at the minimap), wordwrap doesn't cause a problem anymore, but simply pressing Alt (which toggles the Menu Bar as you probably know) creates the same problem, but on the previous size I was using, pressing Alt doesn't create the problem.

[Example of this happening](https://i.imgur.com/GBAFyvd.gifv)

**Comment by alexandrudima** [comment]
@m4xc4v413r4 I see it happening for you and I have tried and tried, but I am still unable to reproduce. I see that there is a clear point for your setup (when you enlarge the width of VS Code) after which the minimap is off.

But after trying and trying, I could still not reproduce... I wonder if you can perhaps share the file that reproduces it, or if it reproduces on any file for you...

I've even reviewed the source code that computes the minimap layout to look for a possible division by 0 or some other corner case, but I failed to find anything obvious: https://github.com/Microsoft/vscode/blob/7a557d12c961511039d3906c26c76c8556c30909/src/vs/editor/browser/viewParts/minimap/minimap.ts#L216-L296

To rule out some things, can you please disable all extensions, and slowly comment out your settings (including font settings, etc) to try to narrow down what exactly causes it to reproduce...
