### ISSUE TITLE
Duplicate Object Key in Settings - Is there a Fix?

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#50065]
Before closing. I've checked all threads and closed issues posted. I've not seen any indication to what the problem is, if this is a duplicate installation problem, an extension problem, a VS Code problem, or any mention of a solution.

So if I'm wanting some advice on what I should do, is there any? I can't post on any of the other threads so there's no gauge of how many might be experiencing this still or what could be done about it. Any chance we can get that here or at one of the other threads?

Thank you. Love VS Code.

**Comment by mjbvz** [comment]
Unclear to me what the issue is. Where is the error shown? Can you share you settings file?

**Comment by weinand** [comment]
You cannot specify a setting more than once in a settings file.
If you do, you will see an error:
![2018-05-22_11-20-01](https://user-images.githubusercontent.com/1898161/40353565-159f10f0-5db2-11e8-95eb-d3f6ea06c3fa.png)

**Comment by DanJ210** [comment]
I meant to add a screenshot so I apologize. Just so I'm getting this across correctly, the duplicate keys you're seeing are not under my user or workspace settings. They are within VS Code settings, the settings that I cannot actually edit myself on the left side of user and workspace settings.

![duplicate_keys](https://user-images.githubusercontent.com/16159685/40490194-07f727c0-5f39-11e8-8f82-8b2fa28707f6.PNG)

**Comment by weinand** [comment]
Oh, I see.

**Comment by sandy081** [comment]
Are you opening this file using the command `Open Raw Default Settings`? I do not see warnings but following error

![image](https://user-images.githubusercontent.com/10746682/40730434-edbd4c5e-642e-11e8-887d-47c267f038dd.png)


@aeschli What does this error mean?

**Comment by aeschli** [comment]
It's when you put content after a root object or array.

![image](https://user-images.githubusercontent.com/6461412/40732172-01d4a562-6433-11e8-8fe0-335e5024c651.png)

**Comment by DanJ210** [comment]
Hello, no I am not opening anything with a command. I'm just using VS Code as normal. Adding extensions as needed. Only when I added the tslint did I start getting these duplicate key problems.

**Comment by DanJ210** [comment]
Is there anything you guys/girls would like me to try? Removing extensions or uninstalling tslint from command line? Seeing if that does anything? Idk I'm just throwing out suggestions.

**Comment by sandy081** [comment]
@DanJ210 How did you open the settings file you have shown in the screenshot?

**Comment by DanJ210** [comment]
@sandy081 The only way I know how. File -> Preferences -> Settings.

**Comment by sandy081** [comment]
Are you able to reproduce it ?

**Comment by DanJ210** [comment]
Well it's still an issue. Is that what you mean?

**Comment by DanJ210** [comment]
All I have to do is open up settings no matter what project I'm working on and I can pull up all of the duplicates.

**Comment by rowild** [comment]
Same thing here: tslint caused troubles with defining duplicate keys. This happened, because tslint and tslint-for-vue were installed at the same time. tslint-for-vue description made me believe that it extends tslint, but instead it seems that only one of them should be activated.

**Comment by sandy081** [comment]
@rowild Thanks for the hint. I can reproduce it now.

**Comment by DanJ210** [comment]
So do I need to do anything to help or do I sit tight for some future releases? No problem either way just wondering what I can do.

**Comment by DanJ210** [comment]
Thanks @rowild and @sandy081 for the help, btw.

**Comment by rowild** [comment]
@dan-silver Well, you might try to find out, whether you have extensions installed that overwrite each other. Uninstall all and any of your extensions, then - step-by-step - install them again. Either the problem will magically disappear or you'll get to the point, where you find the extension that is responsible for the mess.

That is a bit time-consuming, but probably better then waiting... :-)
In case you find anything, please don't forget to post back! Thanks in advance!

BTW: Depending on how many extensions you have, it could probably be a better idea to go to the .vscode/extension folder in your home directory and pull the exts out manually all at once. Then put them back again, one-by-one.... (that's how I would do it...)

Good luck!

**Comment by vindicatorr** [comment]
@rowild, that was the case for me.
I was using the PlatformIO extension to create an arduino project and I also had Microsoft's Arduino extension enabled at the same time.
After I disabled Microsoft's Arduino and reloaded, no more duplicate settings.

Dont' know why extensions would duplicate global/default settings.

**Comment by DanJ210** [comment]
@rowild Would the VS Code developers be where I could suggest or request a feature to deal with extensions that are trying to add duplicate entries?

**Comment by rowild** [comment]
@DanJ210 I would assume that this is the most proper place anyway. Maybe starting a new thread would serve the awareness better... VS Code should definitely handle that situation better...

**Comment by DanJ210** [comment]
@sandy081 Is this something that the VS Code team is aware of and are wanting to address at some point?

**Comment by sandy081** [comment]
Extensions should not duplicate settings from other extensions otherwise both extensions listen to the same setting change and might react differently. 

Fix from our side is not show duplicates in our Default Settings Editor.

I would suggest to file an issue against `TSLint Vue` extension to not to contribute duplicate settings.
