### ISSUE TITLE
[Mac] Show path on Dock's right-click menu

### ISSUE THREAD

**Issue by Rhywun** [Microsoft/vscode#50070]
Issue Type: <b>Feature Request</b>

When I right-click the Code icon in the Dock, the menu shows a list of recently-opened documents and folders. If the folders have the same name, there is no way to distinguish them. Perhaps it would help to add the full path as a tooltip? Not sure if possible.

<img width="197" alt="greenshot 2018-05-17 18 38 59" src="https://user-images.githubusercontent.com/1157174/40207254-98ba517a-5a01-11e8-996d-9c44c0fee64d.png">

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 16.7.0

**Comment by bpasero** [comment]
We do not have any control over the names in the list, sorry.
