### ISSUE TITLE
Cannot access history buffer in PowerShell debug console

### ISSUE THREAD

**Issue by MarkKharitonov** [Microsoft/vscode#50073]
My issue is exactly the same as https://github.com/Microsoft/vscode/issues/41948, the comments to which imply that it all should work as expected, yet it does not - the up arrow does not work at all and all the commands must be typed from scratch.

**Comment by roblourens** [comment]
So if you type a command, and press enter, then press the up arrow, nothing happens?

**Comment by MarkKharitonov** [comment]
Exactly.

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by roblourens** [comment]
And does it happen 100% of the time? And I'm curious whether you debug other things besides Powershell, and whether you see the same there.

**Comment by MarkKharitonov** [comment]
It happens 100% of the time when I debug a Powershell script. Without debugging when just working in the powershell terminal the history buffer works fine. I will try the insiders build.

**Comment by MarkKharitonov** [comment]
Just checked insiders - the issue is there as well. I also checked on another machine and it is there as well.

**Comment by isidorn** [comment]
I can not reproduce this.
Can you please provide a video?

**Comment by MarkKharitonov** [comment]
Sure, https://drive.google.com/open?id=13RSxEzcsuXUoXBl7fSQBmDCsQk1VkmnA
I use ShareX, it does not show me hitting the up arrow, but notice when I run Get-History there are more commands there. As if every time I hit Up a command is executed (which is the same Get-History command).
If you need more information, please instruct me how to provide it.
Thank you.

**Comment by isidorn** [comment]
Thanks for the video. This is happening in the terminal, forwarding to @Tyriar

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell

**Comment by Tyriar** [comment]
History works fine when running powershell.exe, this is an issue with the extension's console.
