### ISSUE TITLE
not able to run VSCode python on Raspian (Rpi 3 B) 

### ISSUE THREAD

**Issue by rogerone04** [Microsoft/vscode#50076]
- VSCode Version: Code - OSS 1.14.0 (05b254dcfb44422238c6fdb665721a41ee4ce6ac, 2017-06-20T20:22:03.289Z)
- OS Version: Linux arm 4.14.34-v7+
- Extensions: 
Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
python|tht|0.2.3

Installed the CODE-OSS on raspian but not able to run test code:

import  numpy as np 
x=1
y=2
z=(x+y)
print(Z)
Debugging receiving variables errors! with a long list of "ArithmeticError" and others.

Does somebody got VSCode running on Ranpian?

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
That just sounds like a Python, or maybe an issue with the Python extension.

**Comment by rogerone04** [comment]
It was,
I've been programing with VS code on W10 and there the "shebang" line is not necessary. Debian runuing python on a armf processor needs!!!
begginers mistake, Thanks anyway!
