### ISSUE TITLE
where is the welcome page?

### ISSUE THREAD

**Issue by robertalage** [Microsoft/vscode#50077]
Issue Type: <b>Feature Request</b>

The welcome page is not showing

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by chrmarti** [comment]
'Help > Welcome' opens it and on the page there is a checkbox at the bottom left to have it open automatically on startup.
