### ISSUE TITLE
 Cannot read property 'document' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5007]
Issue Id: <b>098051f7-8a68-a04d-fe08-5331e1befd6f</b><br /><br />*Versions* <br />- 0.10.13-insider<br />-  17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c<br />*Stack* <br />TypeError: Cannot read property 'document' of null<br />    at extensions\ms-vscode.cpptools-0.4.1\out\src\C_Cpp.js:59:24 <no sourcemaps><br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />    at doNTCallback0 (node.js:420:9)<br />    at process._t<br />

**Comment by jrieken** [comment]
fyi @egamma - that's what we see with C++ a lot

**Comment by egamma** [comment]
FYI @asthana86

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscppsamples#3
