### ISSUE TITLE
Function color bug in Monokai theme

### ISSUE THREAD

**Issue by phtdacosta** [Microsoft/vscode#50081]
- VSCode Version: 1.23.1
- OS Version: Windows 8.1

As you guys can see in the image, two **pow** functions are green but the last one is blue. Don't really know if it is an actual bug, but it seems to be so.

![image](https://user-images.githubusercontent.com/8548534/40216120-fe5d95bc-5a3a-11e8-8170-731ac1e452cd.png)

**Comment by mjbvz** [comment]
Please share the source code text from that screenshot

**Comment by phtdacosta** [comment]
Sorry for not showing up earlier, there is the code:
```c
unsigned long long int uint62to10_ (const char* str_) {
    unsigned long long int aux = 0;
    unsigned char aux_ = strlen(str_);
    while ( *str_ ) {
        ((*str_ - 0) > 96) ? 
            (aux += (9 + ((*str_++ - 0) - (96 - 26))) * pow(62, --aux_)) :
            ( ((*str_ - 0) > 64) ? (aux += (9 + ((*str_++ - 0) - 64)) * pow(62, --aux_)) : (aux += ((*str_++ - 0) - 48) * pow(62, --aux_)) ); 
    }
    return aux;
}
```

**Comment by mjbvz** [comment]
Caused by different scopes. One odd `pow` has `support.function`, the others are `entity.name.function`

**Comment by phtdacosta** [comment]
Just for curiosity, are the scope "judgement" based on something special? I ask because it happened again, with another code in another language, and although it does not bring any problem, it is visually a bit annoying. >.<

**Comment by aeschli** [comment]
I filed https://github.com/atom/language-c/issues/278 against the c grammar
