### ISSUE TITLE
[pug] Use pug grammar & rename language id

### ISSUE THREAD

**Issue by lunelson** [Microsoft/vscode#50086]
Vscode's pug language definition [currently relies on an outdated external source](https://github.com/Microsoft/vscode/blob/master/extensions/pug/syntaxes/pug.tmLanguage.json#L3). It uses a conversion script which pulls from the Sublime Text plugin https://github.com/davidrios/jade-tmbundle/, rather than the current version of that code, which is https://github.com/davidrios/pug-tmbundle/.

There may not be much difference 🤷‍♂️. However in principle I think the source should be updated. Moreover, that repo has a pending PR from me concerning filter block syntax support in pug, which I would like to see in vscode some day 😏.

If this is as simple as it looks, I'd be glad to do a PR for it. Maybe a maintainer can just confirm the viability?

**Comment by aeschli** [comment]
Thanks for filing the issue and for offering help. There are some more steps necessary: updating dependencies and getting the legal work done, so let me do that.

**Comment by aeschli** [comment]
To verify:
- test that jade and pug files still have syntax highlighting
- test pug embedded in markdown

**Comment by aeschli** [comment]
Note: I reverted the rename of the language id as this would break many extensions.
But verification remains the same.

**Comment by roblourens** [comment]
Still need the markdown grammar change?

**Comment by aeschli** [comment]
@roblourens the scope name has changed to `source.pug` and the markdown grammar references it. I made the changes in the vscode repo, but the changes should also be made in the markdown grammar repo as to not overwrite the changes on the next update: See Microsoft/vscode-markdown-tm-grammar#17
