### ISSUE TITLE
这个“终端”命令功能的字母之间的间距太大了，找不到控制的属性

### ISSUE THREAD

**Issue by jws2003** [Microsoft/vscode#50085]
Issue Type: <b>Feature Request</b>

这个“终端”命令功能的字母之间的间距太大了，找不到控制的属性，我也醉了，能控制大小，字体，行高，就是不能控制字符间距。好难受。

 // 控制终端的字体系列，这在编辑器中是默认的。fontFamily 的值。
  "terminal.integrated.fontFamily": "",

  // 控制终端的字号(以像素为单位)。
  "terminal.integrated.fontSize": 14,

  // 终端中非粗体字使用的字重。
  "terminal.integrated.fontWeight": "normal",

  // 终端中粗体字使用的字重。
  "terminal.integrated.fontWeightBold": "bold",

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

**Comment by Tyriar** [comment]
A letterSpacing was added and will be available in 1.24. This may also be relevant https://github.com/Microsoft/vscode/issues/35681
