### ISSUE TITLE
not opening folder when type `code .` in macOs

### ISSUE THREAD

**Issue by cyberid41** [Microsoft/vscode#50089]
Issue Type: <b>Bug</b>

in terminal I am trying to typing `code .` but not opening containt folder.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.32GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
githistory|don|0.4.1
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
git-project-manager|fel|1.6.1
php-cs-fixer|jun|0.1.80
debugger-for-chrome|msj|4.4.3
tsimporter|pmn|1.2.14
stylint|vtf|0.0.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
What happens exactly? Do you already have the folder opened? Can you provide a screenshot?

**Comment by cyberid41** [comment]
Hi @Tyriar , thanks for response my issue

I tried reproduce as follows:

- open terminal using zsh
- type command `code .`
- the screen vscode only showing welcome page and recent project opened

I am providing screenshots:

<img width="1280" alt="screen shot 2018-05-21 at 10 54 46" src="https://user-images.githubusercontent.com/5117289/40290096-2f536a54-5ce6-11e8-9276-6e350276f5c3.png">
<img width="1280" alt="screen shot 2018-05-21 at 10 54 42" src="https://user-images.githubusercontent.com/5117289/40290097-2fc85c1a-5ce6-11e8-9010-c698316699e9.png">

**Comment by joaomoreno** [comment]
What does `which code` return?

**Comment by cyberid41** [comment]
`which code` returned 

```
code () {
	if [[ $# = 0 ]]
	then
		open -a "Visual Studio Code"
	else
		[[ $1 = /* ]] && F="$1"  || F="$PWD/${1#./}"
		open -a "Visual Studio Code" --args "$F"
	fi
}
```

**Comment by joaomoreno** [comment]
Can you remove that bash function and run the `Shell Command: Install 'code' command in PATH` command within VS Code? Thanks!
