### ISSUE TITLE
Add language-specific _language settings_

### ISSUE THREAD

**Issue by lunelson** [Microsoft/vscode#50087]
Although vscode has (as of recently) [language-specific editor settings](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings), I would like to request language-specific *language settings* i.e. the ability to override definitions in a language's `language-configuration.json` file (found in `vscode/extensions/[language]/`).

For example let's say I would like to set the backtick as a "surrounding pair" character in `pug`, so I can select some text and mark it as an es6 string literal by hitting backtick (like I can do in JavaScript), and not have the backtick character replace the selection: ideally, as a setting, this would require only something like this in my "User Settings" file, to override `pug`'s `surroundingPairs` definition:

```json
  "[pug]": {
    "surroundingPairs": [
      ["{", "}"],
      ["[", "]"],
      ["(", ")"],
      ["`", "`"],
      ["'", "'"],
      ["\"", "\""]
    ],
  },
```

**Comment by alexandrudima** [comment]
I think this is best handled by tweaking the `pug` surrounding pairs. Surrounding pairs for a language should be based on the syntax of said language. So, if `` ` `` are used for strings in pug, then `` ` `` should be in the surrounding pairs.
