### ISSUE TITLE
Disarranged windows with VS code

### ISSUE THREAD

**Issue by Robbie999** [Microsoft/vscode#50095]
Bug: the VS-code Window disarranges other windows. 

- VSCode Version: 1.20.1
- OS Version: Windows 7

Steps to Reproduce:

1. Start explorer
2. Start VS Code
3. Move the VS code window partly over the explorer window
4. Move the explorer window away from the VS code window
5. Overlapping parts of the VS code window are
![disarranged-window](https://user-images.githubusercontent.com/39404412/40229524-fc8a49c6-5a83-11e8-83e4-f1598a76894f.jpg)
 still vissible in the explorer window

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this repo in the latest VS Code: 1.23? What if you start VS Code with the `--disable-gpu` flag?
