### ISSUE TITLE
Do not remove a file from "Save As" when deleting it in that dialog

### ISSUE THREAD

**Issue by jhandby** [Microsoft/vscode#50099]
Issue Type: <b>Bug</b>

1. Open a new tab (File -> New File). Paste in some text

2. File -> Save - call the file "something.txt"

3. Realise that you meant to use the .sql file extension, not .txt. So, open "Save As", and in the file browse dialog:
 - delete "something.txt" using the Windows right click menu on that file
 - enter "something.sql" as the filename in the text field at the bottom of the Save dialog
 - click 'Save'

4. Visual Studio Code abruptly closes the tab without any kind of save, discarding its contents, and complains that it can't stat the original file. Result = work lost.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
gitlens|eam|8.3.0
code-runner|for|0.9.3
Ionide-fsharp|Ion|3.20.4
Ionide-Paket|Ion|1.11.0
mssql|ms-|1.3.1
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
erlang|pgo|0.3.2

</details>

**Comment by jhandby** [comment]
I can see how, in some other situations, the deletion of a file with no unsaved changes should result in it disappearing from the editor. But in this situation the whole entire reason it's being deleted is because you're midway through saving it as something else, and Visual Studio Code knows that you are (because you have the "Save As" dialog open), and so discarding the file contents is surprising to the user. At least it was to this user :)

**Comment by bpasero** [comment]
I would not treat this as dataloss though because you use an external tool (the windows explorer) to delete the file and it is not dirty in the editor.

**Comment by jhandby** [comment]
What I'm saying is that it's possible for a user to do something that's a bit weird but which nevertheless is a workflow which makes sense to them, which would work fine with Notepad, or Visual Studio, and to discover that their data has been thrown away.

When I delete the file, I do so knowing that my data is still in a Visual Studio Code tab, and I plan to save it in about 10 seconds' time. The "surprising" part to the user is that the tab is discarded immediately because the file has been deleted.

**Comment by jhandby** [comment]
I get that Visual Studio Code did what it thought was right because the file was "not dirty in the editor". I'm saying that, in this situation, relying on whether or not the file is dirty is not sufficient.

**Comment by bpasero** [comment]
I will have to close this as "designed". There is no way for VSCode to know that the dialog was used to delete the file.

**Comment by jhandby** [comment]
Surely it's possible to suspend polling for changes / deletion of file X while you have the Save As dialog open for the buffer which vscode thinks corresponds to file X?


---- Benjamin Pasero wrote ----


I will have to close this as "designed". There is no way for VSCode to know that the dialog was used to delete the file.

**Comment by jhandby** [comment]
I'll try to explain what I mean a bit better.

If a user opens vscode and selects File > New File, they have a vscode buffer, never saved, that does not yet correspond to a file on disk. Vscode knows this, so it must have a way to represent a buffer in that state.

After the user first saves the file, a link is established between the vscode buffer and a file on disk. Vscode will monitor the state of that file. This link between a buffer and a file, once established, cannot currently be undone.

The user selecting File > Save As is a pretty clear indication of their intent to change the file which the current buffer is linked to, to refer to a different disk file. So why not suspend the file status checking for this buffer for the duration of the Save As interaction, given that you know that the user is about to break the link between the buffer and its current disk file?

There must be a way to represent a buffer for which file status checking is not being done, as a new never-saved buffer will also be in this state.


Sent from my Xperia™ by Sony smartphone


---- Benjamin Pasero wrote ----


I will have to close this as "designed". There is no way for VSCode to know that the dialog was used to delete the file.
