### ISSUE TITLE
Allow filters on debug console

### ISSUE THREAD

**Issue by DanielSSilva** [Microsoft/vscode#50093]
When debugging, Debug Console displays a lot of messages about modules loaded, threads that exited, etc. Eg:
![image 1](https://user-images.githubusercontent.com/6862119/40227780-5a3594ec-5a87-11e8-951a-176335079995.png)
it would be really useful to be able to filter those messages, like it is on Visual studio, stated on [this StackOverflow answer](https://stackoverflow.com/a/14720692/5268288).

I've searched around and I wasn't able to find anything similar. A workaround is to add to the `launch.json` the following `"console": "externalTerminal"`

**Comment by roblourens** [comment]
You could make a request on the C# extension to allow some filtering. Otherwise, this is for searching in the debug console: https://github.com/Microsoft/vscode/issues/4338

**Comment by DanielSSilva** [comment]
I've found #1017. What about this one? `Options already exist for other types of messages such as module loads (under logging.moduleLoad)`. I've created the issue here because it seemed something that "affects" different languages

**Comment by roblourens** [comment]
I don't think #1017 is related.

**Comment by DanielSSilva** [comment]
Ups, sorry, it's 1017 on other repo :D
I meant #33965

**Comment by DanielSSilva** [comment]
I understand now. I'll open an issue on c# extension then. thanks !
