### ISSUE TITLE
 Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5009]
Issue Id: <b>103d55ee-a82c-de60-96a5-be88ff0e1e33</b><br /><br />*Versions* <br />- 0.10.9<br />-  f291f4ad600767626b24a4b15816b04bee9a3049<br />-  5b5f4db87c10345b9d5c8d0bed745bcad4533135<br />-  17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />*Stack* <br />Error: ENOENT: no such file or directory<br />    at Error (native)<br />    at fs.lstatSync (fs.js:844:18)<br />    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:192:16)<br />    at realpathSync (fs.js:1454:21)<br />    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:275:24)<br />    at toRealPath (module.js:109:13)<br />    at tryFile (module.js:105:22)<br />    at tryExtensions (module.js:115:20)<br />    at Function.Module._findPath (module.js:156:20)<br />    at Function.Module._resolveFilename (module.js:334:25)<br />

**Comment by alexandrudima** [comment]
Last seen 5 months ago
