### ISSUE TITLE
TypeScript "Rename Symbol" breaks enhanced object literal

### ISSUE THREAD

**Issue by rix0rrr** [Microsoft/vscode#50096]
- VSCode Version: 1.23.1
- OS Version: Ubuntu Linux 16.04

## Steps to Reproduce

When I write the following code:

```ts
function hello() {
    const foo = "1234";
    return { foo };
}
```
And I use **Rename Symbol (F2)** to rename `foo` to `bar`, my code changes to this:
```ts
function hello() {
    const bar = "1234";
    return { bar };
}
```
But this does not mean the same thing. The return type of my object has changed. It should have refactored to:

```
return { foo: bar };
```

(*OR* it should have found all call sites and renamed there as well to be consistent with class member renames, but it doesn't do that either)

## Expectation

When renaming local variables, I want the program's behavior to remain the same.

## Actual behavior

The behavior of my program has changed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Tracked by https://github.com/Microsoft/TypeScript/issues/15787
