### ISSUE TITLE
Python "Rename Symbol" doesn't work for f-string

### ISSUE THREAD

**Issue by SZubarev** [Microsoft/vscode#50109]
Issue Type: <b>Bug</b>

When using "Rename Symbol" function in Python it doesn't rename symbols used inside f-strings.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1159451|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.6.0
vscode-docker|Pet|0.0.26
Bookmarks|ale|0.19.1
gitlens|eam|8.3.0
LogFileHighlighter|emi|2.4.0
code-runner|for|0.9.3
rainbow-csv|mec|0.2.1
python|ms-|2018.4.0
autodocstring|njp|0.2.1
trailing-spaces|sha|0.2.11
vscode-todo-highlight|way|0.5.12

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python
