### ISSUE TITLE
Comments in .tmLanguage.json disable syntax highlighting (with JSON with comments)

### ISSUE THREAD

**Issue by rgosens2** [Microsoft/vscode#50101]
- VSCode Version: 1.23.1
- OS Version: macOS 10.12

Steps to Reproduce:

1. Add e.g. MASM language extension
2. Add a // comment in masm.tmLanguage.json
3. Reload Window
4. Syntax highlighting no longer works in .asm files

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
That's as designed: Comments are not valid in tmLanguage.json.

You can use put comments in custom properties, such as here:
https://github.com/Microsoft/vscode/blob/f92bacec327be5308c0f045873a5eb84b1a80006/extensions/pug/syntaxes/pug.tmLanguage.json#L12

**Comment by rgosens2** [comment]
Even with this in User Settings?:

`"files.associations": {
    "*.json": "jsonc"
},`
