### ISSUE TITLE
Outline view for PHP broken since update

### ISSUE THREAD

**Issue by ant-g** [Microsoft/vscode#50110]
Issue Type: <b>Bug</b>

Outline view shows duplicate entry for all items (except plain attibutes by the look of it).  This was working prior to the Outline being added to the side-bar.  

1. Open PHP based file with Class with methods
2. Select Outline view

![image](https://user-images.githubusercontent.com/13222689/40241975-36a5149e-5ab4-11e8-941b-1a6593518621.png)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (25.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
php-pack|fel|1.0.1
todo-tree|Gru|0.0.53
vs-keybindings|ms-|0.2.0
team|ms-|1.133.0
vscode-code-outline|pat|0.2.1
java|red|0.25.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.8.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Do single entries show up if you start with `--disable-extensions`?

**Comment by ant-g** [comment]
Yes, still happens with `--disable-extentions` 

Also,  although I ran with `--disable-extentions` all the extentions seemed to still be active, so I disabled them manually individually.  
The outline option disappeared when I disabled its extention, although I'm sure when I had previously disabled the Outline Extension on its own, it had made no difference.

When I re-enabled it on it's own the outline option appeared but it was showing empty.  I carried on enabling extensions and 'reload'ing  and at some point during this process the outline view populated (still with double entries).  I back-tracked through the extensions disabling again, but it made no difference so I must assume that the Outline view was simply taking time to parse before displaying.

**Comment by roblourens** [comment]
I didn't notice this was an outline contributed by an extension. You'll have to open an issue on that extension.

My guess would be that since you have multiple extensions with PHP language support (intelephense and php-intellisense) they are both showing symbols in the tree.

**Comment by ant-g** [comment]
Yes, it was the two separate language support extensions being active that caused it.  It would seem my earlier enabling/disabling didn't take effect without restarting Code.

However, prior to the VS Code update that moved Outline to the side-menu, having these both active didn't cause a problem.  i.e. when Outline was an expandable layer in the Explorer window the double entries did not appear even though I had all the same extensions active.

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/50110#issuecomment-390898668

@ant-g When having multiple extensions installed that provide an outline, then the name of the extension should become a root. In quick outline (the flat list overlay) they are all mixed...

<img width="231" alt="screen shot 2018-05-29 at 15 58 20" src="https://user-images.githubusercontent.com/1794099/40663519-23a2b8ee-6359-11e8-8502-de821a59e409.png">

**Comment by jrieken** [comment]
Closing as I have checked the double register case and after checking some php outlines

**Comment by aeschli** [comment]
@jrieken How to verify?

**Comment by jrieken** [comment]
I checked the outline, esp quick outline, of the top 2 php extensions works

**Comment by aeschli** [comment]
Thanks, verified.

**Comment by ant-g** [comment]
@jrieken `When having multiple extensions installed that provide an outline, then the name of the extension should become a root`
Ok, I only have one extension providing the outline Code Outline (https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline), this uses symbol data from language specific extensions, of which I have two; IntelliSense and Intelephense.  

When these are both active the duplication appears in the tree beneath the Code Outline root.

Therefore I believe this is an issue for the Code Outline extension and will raise it there.
Thanks.

**Comment by jrieken** [comment]
Hm, now I actually understand. This isn't an issue with VS Code, the outline you are referring too is from that extension. I initially though that's an extension that provides data, not UI. So, is it that the extension has stopped working correctly? I doubt that is related to the changes we made and it might be an issue with the extension itself...

**Comment by ant-g** [comment]
I'm pretty sure that it all worked ok with all the same extensions active when Outline (as provided by the extension) was included as a sandwich layer in the Explorer view, so there may have been an unintended consequence of how things are handled when moving away from that style; however I agree that this now seems like an extension issue.  

I've raised an issue for it here https://github.com/patrys/vscode-code-outline/issues/141 
In order for the extension to solve the problem there may be a call on the VS Code API for help?

Thanks for exploring the issue though, I'm a big fan of VS Code having used it for a few months now with Team Services and Git.
