### ISSUE TITLE
 Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5011]
Issue Id: <b>1da3c212-7881-3be7-bfa4-62875dcd8ff6</b><br /><br />_Versions_ <br />\- 0.10.13-insider<br />\-  17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c<br />_Stack_ <br />TypeError: Cannot read property 'match' of undefined<br />[/vs/editor/common/model/textModelWithTokensHelpers.ts#L187:19 (match)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/common/model/textModelWithTokensHelpers.ts#L187:19 %28match%29)<br />[/vs/editor/common/services/editorSimpleWorker.ts#L38:30 (_getWordAtText)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/common/services/editorSimpleWorker.ts#L38:30 %28_getWordAtText%29)<br />[/vs/editor/common/services/editorSimpleWorker.ts#L53:28 (getWordAtPosition)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/common/services/editorSimpleWorker.ts#L53:28 %28getWordAtPosition%29)<br />[/vs/editor/common/services/editorSimpleWorker.ts#L228:26 (getWordUntilPosition)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/common/services/editorSimpleWorker.ts#L228:26 %28getWordUntilPosition%29)<br />[/vs/editor/common/services/editorSimpleWorker.ts#L216:19 (_suggestUnfiltered)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/common/services/editorSimpleWorker.ts#L216:19 %28_suggestUnfiltered%29)<br />[/vs/editor/common/services/editorSimpleWorker.ts#L212:26 (_suggestFiltered)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/common/services/editorSimpleWorker.ts#L212:26 %28_suggestFiltered%29)<br />[/vs/base/common/worker/simpleWorker.ts#L277:51 (apply)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/base/common/worker/simpleWorker.ts#L277:51 %28apply%29)<br />[/vs/base/common/worker/simpleWorker.ts#L259:69 (_handleMessage)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/base/common/worker/simpleWorker.ts#L259:69 %28_handleMessage%29)<br />[/vs/base/common/worker/simpleWorker.ts#L129:29 (handleMessage)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/base/common/worker/simpleWorker.ts#L129:29 %28handleMessage%29)<br />[/vs/base/common/worker/simpleWorker.ts#L97:7 (_handleMessage)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/base/common/worker/simpleWorker.ts#L97:7 %28_handleMessage%29)<br />

**Comment by ramya-rao-a** [comment]
This is a very old one. Not sure if it still repros. 
@alexandrudima I'll close this one. If it still occurs in the recent builds, we can always open a new one

**Comment by mirague** [comment]
I still see this happen to me every day in the latest VSCode. Any pointers?

**Comment by ramya-rao-a** [comment]
@mirague can you share the call stack from the console? You can open the console by running "Developer: Toggle Developer Tools"

**Comment by mirague** [comment]
@ramya-rao-a This is the call stack:
```
Cannot read property 'match' of undefined
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ mainThreadMessageService.ts:64
n.Class.derive._oncancel @ winjs.base.raw.js:1641
t.showMessage @ mainThreadMessageService.ts:34
t.$showMessage @ mainThreadMessageService.ts:28
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by ramya-rao-a** [comment]
@mirague Which version of VS Code are you using?

cc @bpasero

**Comment by mirague** [comment]
@ramya-rao-a @bpasero I'm on version `1.13.1`
