### ISSUE TITLE
开发helloworld扩展断点不显示堆栈和变量相关信息

### ISSUE THREAD

**Issue by iiwmind** [Microsoft/vscode#50118]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。
Issue Type: <b>Bug</b>

按照官网进行helloworld扩展开发时，断点后调试不起作用，调用堆栈信息和变量、以及监视窗口都不起作用；

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (2.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
folder-indexing|ast|0.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-qrcode|Com|0.2.0
vscode-eslint|dba|1.4.9
githistory|don|0.4.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.2
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
carbon-now-sh|eri|1.1.1
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
vscode-nginx-conf-hint|han|0.0.5
output-colorizer|IBM|0.1.2
plantuml|jeb|2.7.5
docthis|joe|0.6.0
vscode-emacs-friendly|lfs|0.8.2
json-to-ts|Mar|1.5.5
vscode-language-pack-zh-hans|MS-|1.23.5
PowerShell|ms-|1.7.0
vsliveshare|ms-|0.3.125
debugger-for-chrome|msj|4.4.3
color-highlight|nau|2.3.0
vscode-code-outline|pat|0.2.1
LiveServer|rit|4.0.0
vscode-icons|rob|7.23.0
text-marker|ryu|1.1.0
code-settings-sync|Sha|2.9.2
vscode-nginx|sha|0.5.0
open-in-browser|tec|1.1.0
quokka-vscode|Wal|1.0.124
vscode-todo-highlight|way|0.5.12
project-stone|won|0.1.1
JavaScriptSnippets|xab|1.6.0
ReactSnippets|xab|2.1.0

(2 theme extensions excluded)

</details>

![debug](https://user-images.githubusercontent.com/27390750/40244963-dad7a0d0-5af6-11e8-870c-bc61abd39cbe.png)

**Comment by Tyriar** [comment]
Appears to be about the hello world debug example not working.

**Comment by iiwmind** [comment]
After restart system（win10），it's be OK.
