### ISSUE TITLE
Perl syntax highlighting bug on regular expressions containing '#' inside a conditional

### ISSUE THREAD

**Issue by variacc** [Microsoft/vscode#50115]
Issue Type: <b>Bug</b>

The Perl syntax highlighting breaks on regular expressions that implicitly use the default input variable ($_) and contain the '#' character. 
The syntax highlighting breaks if the following conditions are met:
* The regex implicitly uses the default $_ variable
* The regex is NOT the first item in the conditional
* The regex follows an 'and' or 'or' operator 

The rest of the line following the # is highlighted as a comment.

`if (/^#/ and $something) { moo(); } # Syntax highlighting is good`
`if ($something && /^#/)   { moo(); } # Syntax highlighting is good`
`if ($something and /^#/) { moo(); } # Syntax highlighting breaks!`

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
Our perl grammar comes from [this repo](https://github.com/textmate/perl.tmbundle). Please file this issue upstream
