### ISSUE TITLE
Cannot read property 'setVisible' of undefined

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50117]
Steps to Reproduce:

- Install Gitlens extension
- Open SCM View and make sure Gitlens view is shown
- Hide Gitlens view by right clicking and hide
- Click on Explorer

Expected: No Errors and explorer should be shown
Actual: Errors are shown and explorer is empty

I've seen this constantly when I switch viewlets, since Thursday's Insiders. I can't repro when running out of sources but I think it's related to an extension treeview.

![image](https://user-images.githubusercontent.com/323878/40244858-e3f0c3be-5a78-11e8-86ff-d1cafab0fdf8.png)

Also lots of weird glitches in the sidebar:

![image](https://user-images.githubusercontent.com/323878/40244901-fddddd34-5a78-11e8-9629-8c2398e85d90.png)

Stack:

```
t.setVisible (scmViewlet.ts:1207)
(anonymous) (compositePart.ts:301)
then (winjs.base.js:1581)
t.showComposite (compositePart.ts:247)
(anonymous) (compositePart.ts:152)
then (winjs.base.js:1581)
t.doOpenComposite (compositePart.ts:128)
t.openComposite (compositePart.ts:111)
(anonymous) (sidebarPart.ts:122)
then (winjs.base.js:1581)
t.openViewlet (sidebarPart.ts:122)
e.openViewlet (viewletService.ts:74)
t.run (viewlet.ts:135)
(anonymous) (actions.ts:114)
```

**Comment by sbatten** [comment]
i'm also experiencing this issue and @roblourens suspects a relation to GitLens which I do have installed. I'm seeing the scm-viewlet in the DOM on top of the explorer-viewlet at the same time.

**Comment by BrianArditoAGL** [comment]
I'm seeing this with CTRL+B to toggle Explorer.

**Comment by eamodio** [comment]
GitLens users are seeing this too (I can't seem to reproduce it though): https://github.com/eamodio/vscode-gitlens/issues/378

This comment seems to provide the culprit:
https://github.com/eamodio/vscode-gitlens/issues/378#issuecomment-390546686

Which lines up with this code -- somehow a panel is undefined?
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L1205-L1208

/cc @roblourens @joaomoreno

**Comment by eamodio** [comment]
FYI, people are reporting it on stable as well as insiders.

**Comment by sanket-bhalerao** [comment]
Here is something weird I found for replicating the issue
- enable GitLens (for me its GitLens, it may or may not be the same for you.)
- switch to the Source control tab
- switch back to Explorer tab
- at first you will see an empty explorer, click on the explorer icon again to see all your files.
- after this if you click one time on any icon from the left sidebar some weird behavior  is seen on the UI
- the 'setVisible' issue will be visible in the developer tool is visible in the console.

i am on latest release for both VSC insiders and GitLens
VSC -
_Version 1.24.0-insider
Commit a521c01d56ec7f07bea2471880f28a77f37983af
Date 2018-05-21T05:18:01.058Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64_

GitLens- _8.3.2_

**Comment by sandy081** [comment]
Thanks for the steps. I could reproduce it and update the description with steps.

**Comment by sandy081** [comment]
Workaround is to enable gitlens view and not disable it at all.

![image](https://user-images.githubusercontent.com/10746682/40368276-aec22f46-5ddb-11e8-952c-ab6186c1e370.png)

**Comment by joaomoreno** [comment]
Thanks @sandy081!
