### ISSUE TITLE
prompt to change language after update

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#50119]
Issue Type: <b>Bug</b>

I have the Hungarian language pack installed but I do not have `locale.json` set to Hungarian. I must have been testing it at some point, but I was running by default with English strings.

I upgraded to 1.23.1 and on restart I was prompted to change the UI to Hungarian.  The language pack may have been upgraded as well, I don't know what the vesion was before I upgraded code itself.

![image](https://user-images.githubusercontent.com/1487073/40248403-ac58c1a2-5a84-11e8-884a-c3acf2ce49c6.png)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.98GB (2.17GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-opennewinstance|chr|0.0.4
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
vscode-azureappservice|ms-|0.8.1
vscode-language-pack-hu|MS-|1.23.2
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
vscode-docker|Pet|0.0.27
gitblame|wad|2.4.2

</details>

**Comment by ramya-rao-a** [comment]
@sandy081 Am just curious... Was this issue due to the `onDidInstallExtension` event being fired for not just extension installs but extension updates as well?

**Comment by sandy081** [comment]
@ramya-rao-a Yes. Now the event has information about whether it is for install or update.
