### ISSUE TITLE
Intellisense error when using clone function.

### ISSUE THREAD

**Issue by MicahZoltu** [Microsoft/vscode#50111]
- VSCode Version: 1.23.1
- OS Version: Windows 10

Steps to Reproduce:
```
class Foo {
	clone() { return new Foo() }
}

class Bar {
	/** @param {Foo} foo */
	constructor(foo) {
		this.foo = foo
		this.foo = this.foo.clone()
	}
}
```

Intellisense thinks the type of `this.foo` is `any`.  If you remove the line `this.foo = this.foo.clone()` or change it to `this.foo = foo.clone()` intellisense correctly detects the type for `this.foo`.

I _suspect_ the issue is that when intellisense is doing its first pass to determine the type of `this.foo` it assumes `this.foo` is `any` during evaluation.  This results in it detecting that `this.foo` is being assigned to `any.clone()` which of course returns `any`.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

----

Workaround for future readers, you can annotate the type of `this.foo` explicitly with `/** @type Foo */`.

**Comment by MicahZoltu** [comment]
It would seem my choice of the variable name `foo` triggered the dupe bot.  Next time I'll use more obscure names.  😛

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24253
