### ISSUE TITLE
"Running Save Participants" may take very long to complete

### ISSUE THREAD

**Issue by maximedupre** [Microsoft/vscode#50123]
This seems to be a rather recent issue and it is not a problem caused by an extension.

On a pretty large project (mainly Typescript), if I delete the `node_modules` folder, run `npm install`, wait until it is finished and modify/save a file, it may be well over 10 minutes until this file is saved.

It seems like VSC is analyzing the whole `node_modules` folder (perhaps to match imports to modules all over the code?).

A solution is to force quit and reopen

**Comment by maximedupre** [comment]
A solution is to force quit and reopen VSC.

**Comment by mjbvz** [comment]
Does this repo in VS Code insiders? How about with all extensions disabled?

**Comment by CyberPhoenix90** [comment]
I can confirm this happens even in vs code insiders. But I am not sure it really relates to npm install, it seems to happen at seemingly random times
Was not yet able to reproduce this with all extensions disabled

**Comment by mjbvz** [comment]
@CyberPhoenix90 Can you please try tracking down which extension is causing this

**Comment by CyberPhoenix90** [comment]
After some trial and error it seems pretty conclusive that the culprit is  the extension Path Intellisense by Christian Kohler. It slows down deletion significantly and makes the editor stuck on saving participants after a large change in the file system

**Comment by mjbvz** [comment]
@maximedupre Are you still seeing this issue in VS Code insiders with extensions disabled?

**Comment by maximedupre** [comment]
Sorry, I did not have the time to try and reproduce the bug, with the current or insiders version of Code. In my case, the problem is probably caused by "Versions Lens", an extension that analyses the node modules and displays their versions.

**Comment by sja1n** [comment]
@mjbvz I am using latest VS code version 1.24.1 and able to reproduce the issue, especially while saving  markdown files and i don't have any plugins related to markdown

**Comment by mjbvz** [comment]
Closing this since we have not heard back from original opener. Seems caused by extension

**Comment by ShogunPanda** [comment]
This is happening for me as well, taking almost a minute.

**Comment by maximedupre** [comment]
The bug still occurs for me too. My only extensions now are "Debugger for Chrome" and "Atom One Dark Theme", so "Versions Lens" wasn't the problem.

**Comment by thomassvensen** [comment]
This is happening for me, too, and it seems to hang *forever* in my case. Only way to fix is to restart VSCode, but now it re-occurs almost immediately after restart, making VSCode almost unusable. For me also, it seems related to 
```
"editor.codeActionsOnSave": {
"source.organizeImports": true
}
```
I have none of the extensions mentioned above, but have these:
GitLens, Vim, REST Client, Rainbow Brackets, Prettier, ESLint

**Comment by CyberPhoenix90** [comment]
I also have prettier and gitlens from that list
The problem still persists to this day even on the insiders version

**Comment by stereokai** [comment]
@mjbvz Let's reopen this, this is definitely still reproducing for several people

**Comment by evercloud** [comment]
I fixed a similar problem by uninstalling/disabling TypeScript Hero extension. :)

**Comment by raptor59** [comment]
Yep, experiencing this constantly. With large php / html mixed files. I think either "close html/xml tag" or "highlight matching tag" plugins cause the problems. When saving - it takes ages with "saving participants" and nothing else is happening. My Deploy reloaded even not fireing up
