### ISSUE TITLE
Feature Request: Highlighting of changed lines and files with Team Foundation Server

### ISSUE THREAD

**Issue by walrus95** [Microsoft/vscode#50121]
I'm a Visual Studio Code user who uses Team Foundation Server for versioning. I'd like to request that Visual Studio Code integrate with Team Foundation Server like it does for Git to give highlighting of the lines of code which have been modified since the last commit. I would also like to see highlighting of files which have pending changes, like with Git. This is very important. Thank you!

**Comment by joaomoreno** [comment]
https://marketplace.visualstudio.com/items?itemName=ivangabriele.vscode-tfs
