### ISSUE TITLE
Terminal Cursor Size/Position incorrect when using DOM renderer

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#50125]
Issue Type: <b>Bug</b>

VS Code asked me to switch to the DOM renderer in the terminal to improve performance. I did that, but now at the default font size (12) the cursor in the terminal is larger than the text, and positioned so that the bottom of the cursor is at the text base line. 

Switching back to the canvas renderer shows a correctly sized/positioned cursor.

<img width="432" alt="screen shot 2018-05-18 at 2 57 09 pm" src="https://user-images.githubusercontent.com/13488/40252891-ca01139a-5aab-11e8-803f-fffe457037ae.png">

VS Code version: Code - Insiders 1.24.0-insider (912fff91ac4ff1bff9695e8da69abd729f7ae956, 2018-05-18T05:11:58.249Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (1.33GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
material-icon-theme|PKi|3.4.0
vscode-docker|Pet|0.0.26
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.50
vscode-svgviewer|css|1.4.4
githistory|don|0.4.1
tslint|eg2|1.0.29
Angular2|joh|6.1.1
prettify-json|moh|0.0.3
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.125
debugger-for-chrome|msj|4.4.3
autoimport|ste|1.5.3

(4 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@jtsom were you having performance issues previously? Was the switch suggestion valid?

**Comment by jtsom** [comment]
I really didn't notice any performance issues, so I was surprised by the message. (It's a MacPro so I would hope there wouldn't be performance issues...)

**Comment by Tyriar** [comment]
@jtsom the message is meant to show up only if the first frame takes >= 50ms to render, so it's surprising to hear you weren't having issues before. I may need to tweak the condition thanks 😃
