### ISSUE TITLE
"Open File" + paste file path + Enter/Go opens file in default app, not VSCode

### ISSUE THREAD

**Issue by samyun** [Microsoft/vscode#50120]
Issue Type: <b>Bug</b>

1. Ctrl+O or File->Open File...
2. Paste/type full path to file (eg D:\bob\src\...\Resources.resw)
3. Enter or Go

EXPECTED: Open file in VSCode
ACTUAL: File opened in default app for file type (eg Visual Studio)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17672

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (14.92GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0

</details>

**Comment by bpasero** [comment]
@samyun I guess that might depend if the file type is associated with another program. Can you check if it is associated with VSCode?

**Comment by samyun** [comment]
It's associated with VS. I usually work in VS, but I occasionally open one-off files in VS Code. 

I feel like it makes more sense that no matter what the program a file type is associated with, if you open it through VS Code, it opens in VS Code.

**Comment by bpasero** [comment]
@samyun but that dialog is coming from windows and windows decides how to open a file. I am closing this as there is nothing we can do about it unless we would drop this native file picker.
