### ISSUE TITLE
Inconsistent right padding for files with short filename when `tabCloseButton` is off

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#50129]
Issue Type: <b>Bug</b>

With
```
"workbench.editor.tabCloseButton": "off"
```

That's fine

![image](https://user-images.githubusercontent.com/4033249/40253356-474879d2-5a94-11e8-9d4a-58df51c08faa.png)

Now I close the second `main.d.ts`, middle tab has really large whitespace to the right.

![image](https://user-images.githubusercontent.com/4033249/40253385-5df30c60-5a94-11e8-877d-94529fd1a623.png)

This isn't an issue in 1.23.1:

![image](https://user-images.githubusercontent.com/4033249/40253465-b679ed2c-5a94-11e8-9704-c15e01f1fb41.png)

![image](https://user-images.githubusercontent.com/4033249/40253471-b87152f0-5a94-11e8-8447-c06e5b6fa5bd.png)

Wondering if @sbatten's work on the minibar relates to this.

VS Code version: Code - Insiders 1.24.0-insider (912fff91ac4ff1bff9695e8da69abd729f7ae956, 2018-05-18T05:11:58.249Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_528513|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.0.1
githistory|don|0.4.1
tslint|eg2|1.0.29
prettier-vscode|esb|1.3.1
theme-monokai-pro-vscode|mon|1.1.6
Go|ms-|0.6.80
debugger-for-chrome|msj|4.4.3
vetur|oct|0.12.3
shader|sle|1.1.3
vscode-csstree|sme|0.6.0
language-stylus|sys|1.9.2
vim|vsc|0.12.0

(4 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@octref "Wondering if @sbatten's work on the minibar relates to this." <- how is that possible when his work is still on a branch?

I would accept a PR on this if someone is willing to look into this.

**Comment by octref** [comment]
@bpasero NVM, I thought he checked it in...

**Comment by bpasero** [comment]
@octref I tried to reproduce with  a simple sample and could not:

![before](https://user-images.githubusercontent.com/900690/40409613-bea2ad42-5e6b-11e8-8369-a8e7955c5df3.gif)

Please provide an exact sample workspace for me to reproduce including settings.

**Comment by octref** [comment]
You can rename both `extension.ts` to `ext.ts` and see what happens.

 ![image](https://user-images.githubusercontent.com/4033249/40439794-e47a9f8e-5e70-11e8-8463-b76870375c75.png)

I realized this might be as-designed for `tabSizing: fit` - seems there is a minimum width that each tab needs to have, so if file names are short this inconsistency happens. It has nothing to do with opening multiple files with same name.

This strategy works well with tabCloseButton, but without it it looks a bit unbalanced.

![image](https://user-images.githubusercontent.com/4033249/40440134-061aacdc-5e72-11e8-9923-7676b4fb4193.png)

**Comment by bpasero** [comment]
Closing as designed. You can change to `tabSizing: shrink`

For fit, we set a default width of 120px:

![image](https://user-images.githubusercontent.com/900690/40464493-d61422d4-5f1b-11e8-839f-7591dae56b28.png)
