### ISSUE TITLE
Terminal link tooltip location is wrong under the DOM renderer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#50128]
The underline also isn't appearing

<img width="676" alt="screen shot 2018-05-18 at 12 12 49 pm" src="https://user-images.githubusercontent.com/2193314/40253488-cc7b1272-5a94-11e8-9fe6-d104c0e0e3f7.png">

**Comment by yikeshome** [comment]
I also encountered this problem on Ubuntu 16.04, underline is not displayed on std input , and std output for Terminal. Hope can be fixed.

Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by agurodriguez** [comment]
Regarding the underline don't appearing I'm trying this solution https://github.com/agurodriguez/xterm.js/commit/be4142d79582765600229103cb7a1e1bc2ac9058, and it seems to work (I'm going to sleep right now, but tomorrow I'll make some testing).

Do you think it's a feasible solution?

**Comment by alexr00** [comment]
@agurodriguez , we probably don't want to handle the tooltip location in xterm.js since xterm.js should just be providing all the info it has in the mouse event without making specific assumptions about how that info will be used. I'll let @Tyriar comment on the underline 😊

**Comment by Tyriar** [comment]
@agurodriguez I made some comments on the underline, looks pretty close to what we're after. I created https://github.com/xtermjs/xterm.js/issues/1704 to track this, a PR would be fantastic! You would also want to remove the line in xterm.d.ts that says link underlines are not supported.

**Comment by agurodriguez** [comment]
Underline don't appearing was fixed in https://github.com/xtermjs/xterm.js/pull/1705

We should wait for `xterm`'s 3.8.0 release in order to update `vscode` and close this issue, right?

**Comment by Tyriar** [comment]
@agurodriguez I've already pulled in your changes, we'll close this off when https://github.com/Microsoft/vscode/pull/59060 is merged.

**Comment by Tyriar** [comment]
Hmm, something is still a bit off, mousing over and pausing on the bottom few pixels will show the tooltip in the correct position but the pixels above will show the tooltip where it should be for the line above 🤔 

![image](https://user-images.githubusercontent.com/2193314/46113787-a4e3f400-c1a4-11e8-84ab-17728f9c2c11.png)
![image](https://user-images.githubusercontent.com/2193314/46113788-a9101180-c1a4-11e8-9bbd-3be8b589c66f.png)

**Comment by agurodriguez** [comment]
I still have no idea why this is happening but this is what I got so far:

Target of the `mousedown` event in the **expected behavior** scenario:

> The `span` right below the `span` where I had the pointer
>
> <img width="457" alt="screen shot 2018-09-30 at 12 21 27 am" src="https://user-images.githubusercontent.com/13837769/46252928-daa80780-c446-11e8-83fd-76991b0337db.png">

Target of the `mousedown` event in the **unexpected behavior** scenario:

> The actual `span` where I had the pointer
>
> <img width="728" alt="screen shot 2018-09-30 at 12 21 07 am" src="https://user-images.githubusercontent.com/13837769/46252926-da0f7100-c446-11e8-8af0-5eb31806b8fc.png">

**Comment by Tyriar** [comment]
PR out upstream which should fix this: https://github.com/xtermjs/xterm.js/pull/1716

**Comment by Tyriar** [comment]
I can no longer reproduce.
