### ISSUE TITLE
vs code not display all emoji in ubuntu 18

### ISSUE THREAD

**Issue by dimensi** [microsoft/vscode#50122]
Issue Type: <b>Bug</b>

I don't know why, but i not have problem display emoji in chrome or ff or terminal, only in vs code i got this
![image](https://user-images.githubusercontent.com/11390039/40251488-1e474f38-5ae2-11e8-86cf-640ea12f37a1.png)
![image](https://user-images.githubusercontent.com/11390039/40251566-4dd4fb7e-5ae2-11e8-83c7-f47b24ff15aa.png)
![image](https://user-images.githubusercontent.com/11390039/40251600-6ddf926c-5ae2-11e8-8b86-5d004d6b0c38.png)
Before i was on manjaro kde and not having problems.

I have settings for terminal font family
```
  "terminal.integrated.fontFamily": "'Roboto Mono for Powerline', 'Noto Color Emoji'",
```

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-4350 Quad-Core Processor (4 x 2283)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|4, 2, 1|
|Memory (System)|15.40GB (12.64GB free)|
|Process Argv|/snap/vscode/37/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-language-pack-ru|MS-|1.23.0
vscode-docker|Pet|0.0.26
code-settings-sync|Sha|2.9.2
indenticator|Sir|0.6.0
vscode-wakatime|Wak|1.2.2
quokka-vscode|Wal|1.0.124
lit-html|bie|1.2.0
vscode-svgviewer|css|1.4.4
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.9
gitlens|eam|8.3.1
prettier-vscode|esb|1.3.1
file-icons|fil|1.0.12
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.9.0
svg|joc|0.1.0
docthis|joe|0.6.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.6
vscode-scss|mrm|0.6.2
python|ms-|2018.4.0
atom-keybindings|ms-|3.0.4
vetur|oct|0.12.3
language-stylus|sys|1.9.2
stylus-supremacy|thi|2.10.1
vscode-todo-highlight|way|0.5.12
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by dimensi** [comment]
Okay, i install Noto emoji and Segui Ui Emoji, now i have emoji.
![image](https://user-images.githubusercontent.com/11390039/40252328-b60fd48c-5ae4-11e8-94af-1368e97108c2.png)

**Comment by Tyriar** [comment]
@alexandrudima any idea why emoji wouldn't be showing up correctly?

**Comment by dimensi** [comment]
I run vs code on manjaro 17.1 and not have problem with emoji.
![image](https://user-images.githubusercontent.com/11390039/40350782-6fcf0afc-5db3-11e8-9410-db9404297c8d.png)

**Comment by alexandrudima** [comment]
@Tyriar 

It probably has to do with our ancient version of Chromium. We are on Chromium 58 (released on April 19, 2017) and the current stable version is Chromium 66.

**Comment by Tyriar** [comment]
This looks like an environment/font issue to me since it works fine for @dimensi

**Comment by leaanthony** [comment]
I am also having this issue. Easily reproducible:

1. Create new file on Mac VSC 
2. Enter Emoji (In my case a rocket)
3. Save file and copy to Ubuntu 18.04
4. Open in VSC

![emojifail](https://user-images.githubusercontent.com/1943904/42724960-4de9d33c-87bf-11e8-933d-d7931ac602a0.png)

VSC Terminal output:
![image](https://user-images.githubusercontent.com/1943904/42725050-ba809606-87c0-11e8-81b3-2f36eda69c2e.png)

Ubuntu Terminal output:
![image](https://user-images.githubusercontent.com/1943904/42725043-abc9789e-87c0-11e8-921c-d5e9cb974d0b.png)

Settings:
 Mac:
 "editor.fontFamily": "Fira Mono for Powerline, Menlo, Monaco, 'Courier New', monospace",

 Ubuntu:
 "editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
