### ISSUE TITLE
Git: There are no active source control providers after update

### ISSUE THREAD

**Issue by paulohtobias** [Microsoft/vscode#50138]
- VSCode Version: 1.23.1
- OS Version: Windows 10 - 1709

Steps to Reproduce:

1. Happens with all folders

Does this issue occur when all extensions are disabled?: Yes

After these last April updates, vscode no longer shows any git information for my projects, and when I open the Source Control panel, it says that "There are no active source control providers". As I said, it happens on all projects using git.

I installed git using msys2, and it is in D:\dev\msys64\usr\bin\git.exe

My git.path is null but apparently vscode is able to locate git just fine
![image](https://user-images.githubusercontent.com/25034157/40261594-e4dfe9ee-5ad7-11e8-8273-f267ffb90fcf.png)

Then it runs `git rev-parse --show-toplevel` and `git config --get commit.template` and "Open repository" shows a path that I believe does not work in Windows: `\d\Paulo\Workspace\C\controller_to_keyboard` when it should be `D:\Paulo\Workspace\C\controller_to_keyboard`. After that this loops a few times.
![image](https://user-images.githubusercontent.com/25034157/40261720-b1123b8e-5ad8-11e8-8fae-68fb463ccb42.png)

What's weird for me is that it worked fine with the old versions and now it stopped, so I don't think it's a problem with the git I have.

I did tried going back to a previous version and it still shows me the There are no active source control providers message, so I don't know what to do anymore.

**Comment by paulohtobias** [comment]
I downloaded it using MSYS2's command `pacman -S git`. I don't know exaclty where did it com from,  but [this link](https://github.com/Alexpux/MSYS2-packages/tree/master/git) might be it.
![image](https://user-images.githubusercontent.com/25034157/40622428-0397e628-6278-11e8-8ba0-f223e1e1dfcd.png)

So, to answer you question, I think it's not the one you linked, but a modified version from MSYS2

**Comment by joaomoreno** [comment]
We only officially support [Git for Windows](https://git-scm.com/), so I suggest you install that.
