### ISSUE TITLE
Profiles for keybindings

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#50134]
For bug reports, please fill in the details below. For feature requests, please describe the desired feature.
-->

Hello,

Sorry if this is a duplicate but one feature I think would be really helpful is to be able to create profiles for keybindings and other environment variables.

I just left a job where we pair programmed on everything and driving on someone else's machine would always confuse each of us a bit as we were used to our own shortcuts or behaviours. Whether that was related to formatting/code styling or simply navigating within the IDE.

**Comment by s6o** [comment]
I've a similar feature request, but in addition to **user** specific keybinding profiles, it would also be great to have **operating system** specific (global) profiles on other supported platforms (e.g. macos, linux, win 10).

Why?  - muscle memory - I've have a main machine, running macos, but also use linux and windows 10 (running natively on the macbook). My muscle memory is mostly used to VS Code's mac shortcuts, it would be nice if for example in the VM (e.g. VirtualBox) instance running my (linux) VS Code instance I could do **"select keybinding profile: macos"** - as my (host) machine and keyboard (layout) haven't really changed.

Similar use cases apply if the main machine would be running linux (windows in a VM) or windows 10 (with a linux in a VM).
