### ISSUE TITLE
TS "function" color is changed when it's not used

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50135]
Seems inconsistent with how variables work:

<img width="449" alt="screen shot 2018-05-18 at 2 42 28 pm" src="https://user-images.githubusercontent.com/2193314/40259279-525c5814-5aaa-11e8-87bb-821571d9480c.png">

**Comment by andy-ms** [comment]
This is due to Microsoft/TypeScript#22388 -- if it's not desired we could revert that.

**Comment by Tyriar** [comment]
@andy-ms I find it unexpected/distracting personally. This would probably drive me to disable it but I wanted to dogfood for a while longer 😄

**Comment by mjbvz** [comment]
@andy-ms Do you know what VS does for C#? Do they grey out just the symbol name:? The entire signature? Entire declaration?

**Comment by andy-ms** [comment]
@amcasey might know.

**Comment by amcasey** [comment]
My personal preference would be to gray out the keyword (`const` in the original example) when all of the declared variables are unused.  I think @andy-ms may have recently enabled this?

**Comment by mjbvz** [comment]
Yes I'd prefer this as well. Makes it more obvious that something is unused

**Comment by mjbvz** [comment]
Upstream issues for June: https://github.com/Microsoft/TypeScript/issues/24500

We decided to just color the symbol name (except for imports)

**Comment by andy-ms** [comment]
Should be fixed by Microsoft/TypeScript#24566.

**Comment by mjbvz** [comment]
Fixed upstream in TS 2.9.2
