### ISSUE TITLE
 Unexpected token ]

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5013]
Issue Id: <b>f3cc2e1d-6230-6369-eb72-6ce5b5069350</b><br /><br />*Versions* <br />- 0.10.14-insider<br />*Stack* <br />SyntaxError: Unexpected token ]<br />    at Object.parse (native)<br />    at ConfigurationProperties.handleConfigurationChange (C:\Users\a123\.vscode-insiders\extensions\ms-vscode.cpptools-0.4.2\out\src\C_Cpp_ConfigurationProperties.js:99:43) <no sourcemaps><br />    at C:\Users\a123\.vscode-insiders\extensions\ms-vscode.cpptools-0.4.2\out\src\C_Cpp_ConfigurationProperties.js:61:19 <no sourcemaps><br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />    at e._onFi<br />

**Comment by egamma** [comment]
FYI @asthana86

**Comment by willbar** [comment]
I'm hitting this issue in 1.1.0-alpha (76625649235f4e9e4fbc9ec466f35061a944758a) and it prevents me opening any *.ts files.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscppsamples#151
