### ISSUE TITLE
Hyperlinks don't open

### ISSUE THREAD

**Issue by kroppt** [Microsoft/vscode#50139]
- VSCode Version: 1.23.1
- OS Version: GNOME 4.12.12-gentoo btw

Steps to Reproduce:

1. Open VS Code
2. Click hyperlink
3. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

I have tested multiple overlays, but none of them work. This has been an issue for me for multiple releases. Also happens on my laptop (same OS).

Not sure how link handling occurs, so no idea what else to provide.

**Comment by mjbvz** [comment]
What file type are you in? Can you please provide example file contents containing a link?

**Comment by kroppt** [comment]
It works nowhere.

Example: open file, write URL, Ctrl+Click it when it turns into hyperlink. Does not open.

Another: Welcome page opens. Click URL for Stack Exchange. Does not open.

**Comment by alexandrudima** [comment]
Seems like an Electron issue. AFAIK we end up invoking `window.open` when opening a link. The same happens from the Welcome page. Looks like in this case `window.open` is broken in Electron.

**Comment by bpasero** [comment]
@kroppt can you:
* Help > Toggle Developer Tools
* select "Console"
* type `window.open("http://www.bing.com")`
* hit Enter

=> does this open a browser? or show any error message?

**Comment by kroppt** [comment]
I updated to 1.24 on both of my systems. Doesn't work. What you suggested just returns null.
