### ISSUE TITLE
Search is searching in directories it should be ignoring

### ISSUE THREAD

**Issue by vcsjones** [Microsoft/vscode#50136]
- VSCode Version: Version 1.23.1 (1.23.1)
- OS Version: macOS 10.13.4 (17E202)

Steps to Reproduce:

1. Open a folder/workspace that has an initialized git repository
2. Search using the search pane to search the workspace using something that would be in a `.git` folder. For example, a commit message.
3. Note that search is returning results from inside the `.git` directory.

Note that this occurs with other ignored directories for me, including user-defined ones. For example, in addition to including the default `files.exclude` in the User Settings JSON file, I added `"**/log": true` and noticed that it was searching inside the `log` directory of our application.

Does this issue occur when all extensions are disabled?: Yes

------------

Aside from disabling all extensions, I have also tried the following:

1. Completely resetting my User Settings JSON file to `{}` since the default setting for `files.exclude` exclude the `.git` directory. Search results for the `.git` directory continued to return.

1. Explicitly adding entries to `search.exclude` does not address the issue (though that should inherit from `files.exclude`)

Attached is a screenshot of the issue. This is with a default User Settings JSON file, with all extensions disabled.

![screen shot 2018-05-18 at 5 50 04 pm](https://user-images.githubusercontent.com/361677/40259477-374e5c4c-5ac4-11e8-859b-ef61080cf1b5.png)

**Comment by roblourens** [comment]
Please see the tips in the wiki to help troubleshoot this: https://github.com/Microsoft/vscode/wiki/Search-Issues

**Comment by vcsjones** [comment]
>The search viewlet has a toggle button, "Use Exclude Settings and Ignore Files", which will disable checking both of these things. Make sure that it's toggled on - it's not uncommon that users turn it off and forget about it.

Agh that was it. That is very unintuitive since the toggle was collapsed out of sight. I actually didn't know that toggle existed. I must have toggled it by mistake.
