### ISSUE TITLE
Custom explorer nodes not displaying

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#50143]
Issue Type: <b>Bug</b>

One of the nodes in the Docker explorer fails to refresh.  In the debugger, i can see the call to `getTreeItem()` returning the proper data, but the children don't appear.  It doesn't happen all the time, but it does happen about 90% of the time. This code has not changed in months and worked earlier, so I believe something changed in Code itself.

To repro:

* Create some azure container registries
  * In the Azure portal, choose `Create a Resource` on the left side
  * Search for `Container Registry`
  * Click `Create`
  * Provide a unique `Registry Name`, the proper `Subscription`, `Resource Group`, etc.
  * Click `Create`, should only take about 30sec to create the registry, so create a couple more...

* Get the code

```
git clone https://github.com/microsoft/vscode-docker
cd vscode-docker && npm install
code-insiders .
```

* `F5` to run the extension
* Install the [Azure Account extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account) into the Extension Development Host instance
* Open the command palette, choose `Azure: Sign-in` and sign into your account
* `cmd+p` and Reload the Extension Development Host
* Open the `Docker` view on the Activity Bar
* expand the `Registries` node 
* expand the `Azure` node

You should see your registries.

![image](https://user-images.githubusercontent.com/1487073/40264326-7615e254-5ad5-11e8-876c-9c7b12b38120.png)

* Collapse the Azure node
* Press `refresh` on the `DOCKER: EXPLORER` bar
* Expand the `Azure` node

Result: it should be empty.  If it isn't, try the expand/collapse/refresh pattern a few times, or reload the Extnesion Development Host and do it again.

![image](https://user-images.githubusercontent.com/1487073/40264321-553e44fe-5ad5-11e8-9edd-3ac52464b551.png)

I've set a breakpoint on line `31` of `explorer\models\azureRegistryNodes.ts` and see it being called, with the appropriate data being returned.  But, the children are not loaded.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.98GB (1.73GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-opennewinstance|chr|0.0.4
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
vscode-azureappservice|ms-|0.8.1
vscode-language-pack-hu|MS-|1.23.2
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
vscode-docker|Pet|0.0.27
gitblame|wad|2.4.2

</details>

**Comment by sandy081** [comment]
@chrisdias Thanks for the steps. Will try to reproduce it and investigate.

**Comment by chrisdias** [comment]
Tested on latest insiders, everything working as expected. thanks @sandy081 !!!
