### ISSUE TITLE
There is an ESNext syntax that cannot be correctly recognized in file with the extension name of vue.

### ISSUE THREAD

**Issue by shijinyu** [Microsoft/vscode#50150]
## Info

- Platform: macOS
- Vetur version: 0.12.3
- VS Code version:1.23.1

## Problem

The codes looks like:

file: demo.vue

```html
<template>
  <button>Click Me</button>
</template>
<script>
import { assign } from 'decorators';
export default {
  methods: {
     @assign('handleClick')
     handleClick() {
         // do something ....
     }
  }
}
</script>
```

I fully understand that the grammar of decorator can only decorate a class or the properties and methods of a class.The code seems to output only one object, but It is only a syntactic sugar for a vue component which can be compiled correctly. 

I'm not sure if this issue should be commited to vscode, but I have no use. I am eager to get a reply. Thank you.

**Comment by mjbvz** [comment]
Please file this issue against the Vue extension
