### ISSUE TITLE
C++ Not working/Not supported stuff?

### ISSUE THREAD

**Issue by Rednas83** [Microsoft/vscode#50158]
Issue Type: <b>Bug</b>

MinGW version=mingw32\6.3.0

In visual studio everything is working as expected but in vs code I can't get the Linting to work (only a warning when an include file does not exist) and also I have these startup errors when for example a STRING is declared.
 |- String (returns startup error 0x0000139 on runtime)
 |- Delete (returns startup error 0x0000139 on runtime)
 |- TryCatch (returns startup error 0x0000139 on runtime)
 |- Destructor (returns startup error 0x0000139 on runtime)
 |- fstream (returns startup error 0x0000139 on runtime)

Was someone able to get the stuff from above working or is just me having these startup errors?

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.98GB (3.99GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.3
VBScript|lug|0.0.2
python|ms-|2018.4.0
cpptools|ms-|0.17.1
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.4.3
code-settings-sync|Sha|2.9.2

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
