### ISSUE TITLE
Typescript: Intellisense not working with union type

### ISSUE THREAD

**Issue by WilliamChelman** [Microsoft/vscode#50153]
- VSCode Version: 1.23.1
- OS Version: Pop!_OS 17.10

Steps to Reproduce:

1. Create a typescript file and try the following. When the type is "unioned" with undefined, the autocomplete cannot advise to use the enum anymore.
![test](https://user-images.githubusercontent.com/5839451/40267417-3c5e6888-5b5c-11e8-9f0b-1c43db8da634.gif)

2. This is most annoying with situations like this, with optional parameters given to functions.
![test 1](https://user-images.githubusercontent.com/5839451/40267509-d5509114-5b5d-11e8-9e85-8d346aacf7fe.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24304
