### ISSUE TITLE
color theme in .vscode

### ISSUE THREAD

**Issue by johngrabner** [Microsoft/vscode#50157]
Feature Request: .vscode can set theme (ie: colors) so that different open projects can each have their unique color.

Uses Case:  
1. Editing multiple related but distinct projects (for example server side and client side)
2. Editing main project and node modules.
3. Open and closing projects in the process of editing a large project with lots of dependencies.
    A color assigned to each project would make it faster to select the correct editor.

Why: Many users often have multiple editors open.  Looking at the code to determine what project you are on takes time.  A color per project would make it fast to move to correct editor.

**Comment by johngrabner** [comment]
I may be missing something, but I think your suggestion will give a color theme to all open files.
I want files in directory pager_proxy (including it's launch.json to be red) while 
           files in directory socket_inter (including it's launch.json to be dark. Files from both these projects 
are open at the same time.

When I copy "workbench.colorTheme": "red" into my launch.json nothing happens.

**Comment by mjbvz** [comment]
Ok, it was not clear that you meant controlling the themes for multiple projects in a single window instead a window for each project

Adding @aeschli

**Comment by johngrabner** [comment]
Ok, I now get the interface.

File > Preference > Setting > User Setting .... are global
File > Preference > Setting > Workspace ... are mapped to .vscode/settings.json and apply to the project.

**Comment by aeschli** [comment]
`different theme per folder` could be implemented by an extension:

- listen to the active editor
- update the `"workbench.colorTheme"` setting based on your settings.
