### ISSUE TITLE
feature of terminate only a connected user for live share

### ISSUE THREAD

**Issue by haydarsahin34** [Microsoft/vscode#50152]
Issue Type: <b>Feature Request</b>

Hello, dears vscode dev team!
I am very happy for came live share support to vs code. But I have new feature suggestion for you. You should add feature of terminate only a connected user.

Happy Coding...

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Tyriar** [comment]
https://github.com/MicrosoftDocs/live-share
