### ISSUE TITLE
 Cannot read property '_acceptIsDirty' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5016]
Issue Id: <b>c4f0878f-7db4-0ca4-c001-b5b09ebb5441</b><br /><br />*Versions* <br />- 0.10.12-insider<br />-  17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c<br />-  43ff6af3d4564f59196caa9be4897fc33c15f24c<br />*Stack* <br />TypeError: Cannot read property '_acceptIsDirty' of undefined<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />    at doNTCallback0 (node.js:420:9)<br />    at process._tickCallback (node.js:349:13)<br />

**Comment by aeschli** [comment]
Also found in 0.10.14-insider, 0.10.13-insider

**Comment by jrieken** [comment]
@alexandrudima It seems we still talk about models that don't exist in the ext host... Ideas?

**Comment by jrieken** [comment]
hard to understand... It can only be that we create an untitled document which then isn't sync over to the extension host...

**Comment by jrieken** [comment]
Moving to May in the hope that the additional assertion provides more insights

**Comment by jrieken** [comment]
moving out further cos error telemetry isn't there yet

**Comment by dbaeumer** [comment]
Marking as verified due to @jrieken last comment
