### ISSUE TITLE
CPP Highlighting of multiple inheritance

### ISSUE THREAD

**Issue by pointerless** [Microsoft/vscode#50161]
- VSCode Version: 1.23.1
- OS: Debian 9, 4.9.0.6-AMD64

When a class is inheriting from more than one base class, e.g.
``` C++
class Inheritor : public BaseA, public BaseB{};
```
VSCode only highlights the ```public BaseA``` and not the second inheritance. Following is an example of a class that inherits from SFML's Drawable and Transformable base classes, I do this regularly and it always incorrectly highlights it:

![image](https://user-images.githubusercontent.com/33691245/40270484-3fd6dca0-5b86-11e8-89ee-b5a7e93ff48e.png)

This code compiles correctly and has no actual syntax errors. I have tried moving characters and formatting differently, same highlighting problem.

**Comment by pointerless** [comment]
That was an accidental closure, sorry!

**Comment by aeschli** [comment]
duplicate of https://github.com/atom/language-c/issues/81
