### ISSUE TITLE
underscore character does not show up on terminal 

### ISSUE THREAD

**Issue by adityashourya** [Microsoft/vscode#50178]
Issue Type: <b>Bug</b>

underscore character is hidden in integrated terminal. however the key still registers. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.56GB (0.56GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.0.1
Angular-BeastCode|Mik|6.0.15
python-docs|Muk|0.8.3
html-snippets|abu|0.2.1
django-html|bib|1.2.0
django-snippets|bib|1.1.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
MagicPython|mag|1.0.12
python|ms-|2018.4.0
jinja|who|0.0.8

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
