### ISSUE TITLE
Search with a file pattern in "files to include" finds nothing

### ISSUE THREAD

**Issue by peterwmwong** [Microsoft/vscode#50175]
Issue Type: <b>Bug</b>

I believe a recent change (past week?) has broken searching with file patterns in "files to include"

![vscode-search-fail](https://user-images.githubusercontent.com/284734/40275516-ddf9453c-5bb6-11e8-9d43-c4a743b302b1.gif)

Looking at the "Output" for "search-rg"...

```
provideTextSearchResults one, {"folder":"file:///Users/peter.wong/projects/vscode-search-fail","excludes":["**/.git","**/.svn","**/.hg","**/CVS","**/.DS_Store","**/node_modules","**/bower_components"],"includes":["**/*.txt/**","**/*.txt"],"useIgnoreFiles":true,"followSymlinks":true}
rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case -g '**/*.txt/**' -g '**/*.txt' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' --no-ignore-parent --follow --fixed-strings -- 'one' '.'
 - cwd: /Users/peter.wong/projects/vscode-search-fail
```

Executing the same `rg` command in the terminal (in the same `cwd`)...

```
 ~/projects/vscode-search-fail> rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case -g '**/*.txt/**' -g '**/*.txt' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' --no-ignore-parent --follow --fixed-strings -- 'one' '.'
two.txt
1:one

one.txt
1:one
```

VS Code version: Code - Insiders 1.24.0-insider (912fff91ac4ff1bff9695e8da69abd729f7ae956, 2018-05-18T05:11:58.249Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.42GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
line-jumper|ale|0.1.0
markdown-mermaid|bie|1.0.0
pgformatter|bra|1.3.0
gitlens|eam|8.3.1
cpptools|ms-|0.17.1
Ruby|reb|0.18.0
rust|rus|0.4.4
vscode-hexdump|sle|1.6.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by siegebell** [comment]
dup of #50098?

**Comment by peterwmwong** [comment]
@siegebell #50098 is different in that "Output"/"search-rg" has errors (`The system cannot find the path specified. (os error 3)`).  This issue there are no errors.

**Comment by roblourens** [comment]
Yes, thanks...
