### ISSUE TITLE
Auto-switch to show trimmed whitespaces in diff editor when the only change is whitespaces

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#50170]
Issue Type: <b>Feature Request</b>

Having a file where the only changed lines are trimmed whitespaces. That renders just like any normal editor (`"diffEditor.renderSideBySide": false`). (Actually I was staring at a file for some time => then went looking for errors in console => then git logs). Only after that realized a mistake.

It would be convenient to switch the mode to show trimmed whitespaces automatically (when there are no other changes).

**Comment by usernamehw** [comment]
Actually, **U**ntracked file does this the same way (no Working tree label in editor tab, nothing highlighted). Wouldn't it better to make the entire file green(or whatever color added diff is).

**Comment by bpasero** [comment]
Yes, I would also prefer to see the change if its just whitespace 👍

**Comment by alexandrudima** [comment]
Let's track in #45131
