### ISSUE TITLE
Terminal show nothing unless running as administrator on Windows 10

### ISSUE THREAD

**Issue by Yurunsoft** [Microsoft/vscode#50173]
Issue Type: <b>Bug</b>

see the image, my terminal show nothing everytime when i update the vscode

![qq 20180520085132](https://user-images.githubusercontent.com/20104656/40274562-c6b5d5c0-5c0b-11e8-962d-fb912e59d0b4.png)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (4.63GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
php-namespace-resolver|Meh|1.0.8
vscode-language-pack-zh-hans|MS-|1.23.5
php-docblocker|nei|1.6.0

</details>

**Comment by Tyriar** [comment]
What's in your settings.json file?

**Comment by Yurunsoft** [comment]
I have not modified settings.json
The same version of vscode is normal on another computer and I am looking for a reason

**Comment by Tyriar** [comment]
@Yurunsoft are you 100% sure it's empty (ctrl+,)? The terminal can add a setting automatically on Windows.

**Comment by Yurunsoft** [comment]
100% on my computer
I have not modified settings.json
I read the configuration in default settings.json is correct

**Comment by Yurunsoft** [comment]
OK, I'll try again later, thank you

**Comment by Yurunsoft** [comment]
When I Run as Administrator it's ok...

**Comment by arthurwhite** [comment]
It's not OS-specific.
I'm on macOS 10.13.5 and see the same bug since I updated VS Code to 1.24.1.

`"terminal.integrated.rendererType": "dom"` doesn't change anything.

Running `sudo code .` makes the terminal work, but that's a very bad solution.

**Comment by alexr00** [comment]
@Yurunsoft, are you still seeing this?

**Comment by Yurunsoft** [comment]
@alexr00 Thank you very much, after I installed the VSCode single-user version, the problem was solved.
