### ISSUE TITLE
Git operations are extremely slow

### ISSUE THREAD

**Issue by LouieK22** [Microsoft/vscode#50182]
Issue Type: <b>Performance Issue</b>

All operations with Git take extremely long amounts of time to process. Upwards of 15 seconds just for a change to be staged. The issue still occurs with all extensions disabled. Git commands run fine in the integrated terminal and in a normal command prompt.

VS Code version: Code - Insiders 1.24.0-insider (115ab2d6572df48d3548ed841e19eac5e7761721, 2018-05-16T12:59:04.240Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (0.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    80	510848	code-insiders main
    0	    70	511140	   shared-process
    0	   157	511152	   gpu-process
    0	   219	534640	   window (hyptek-research-facility - Visual Studio Code - Insiders)
    0	    55	513328	     extensionHost
    0	    32	528596	     terminal
    0	     6	518428	       winpty-process
    0	    11	518988	         console-window-host (Windows internal process)
    0	    63	528028	         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    14	528688	     watcherService 
    0	    10	528708	       console-window-host (Windows internal process)
    0	    74	536260	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (hyptek-research-facility - Visual Studio Code - Insiders)
|    Folder (hyptek-research-facility): 81 files
|      File types: lua(59) md(10) json(3) gitkeep(2) gitignore(1) bat(1)
|                  yml(1) htpasswd(1) types(1) conf(1)
|      Conf files: tasks.json(1) settings.json(1);
```

</details>
Extensions: none

**Comment by LouieK22** [comment]
It had to be done

![](https://i.imgur.com/8gd0uFu.jpg)

**Comment by joaomoreno** [comment]
Can you reproduce in another machine? Can you reproduce using our [insider release](https://code.visualstudio.com/insiders)?

**Comment by LouieK22** [comment]
In the latest insiders build the bug still exists. I am unable to use another machine at this time, however Git runs fine from the integrated terminal.

**Comment by joaomoreno** [comment]
You can go through #34898 and read more about this. I eventually ran out of ideas and I'll likely will do so with your system. Go through our discussion in that issue and try out different things. Let me know if you manage to solve it.
