### ISSUE TITLE
Symbols names get trimmed

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#50185]
`SymbolInformation.name` gets trimmed, basically (some) spaces get removed, I don't think this should be the case.

My use case:

I've added `Go to Symbol` support to [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) for easily switching between projects, and it makes sense to me to maintain the indentation:

<img width="1254" alt="screen shot 2018-05-20 at 17 05 10" src="https://user-images.githubusercontent.com/1812093/40280262-d6e66212-5c50-11e8-8038-97d322b9249e.png">

I had to replace all the spaces with non-breakable spaces (`U+00A0`) in order to achieve this.

**Comment by jrieken** [comment]
I actually think that's fair. The purpose of quick outline is a flat list that allows for rapid access to symbols in a document. With the outline tree, that we are currently adding, you will have the desired behaviour without using ascii-art
