### ISSUE TITLE
The render thread is crashed(no response) accidentally

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#50181]
Issue Type: <b>Bug</b>

The render thread is crashed(no response) accidentally, and system infos that `The Graphic Card Driver(ATI) is crashed, and resume again.`

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 390  @ 2.67GHz (4 x 2666)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.86GB (0.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe F:\GitHub\LuaCoderAssist|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.3.3
Bookmarks|ale|0.19.1
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.17.0
vscode-eslint|dba|1.4.9
githistory|don|0.4.1
gitlens|eam|8.3.1
tslint|eg2|1.0.29
code-runner|for|0.9.3
twitch-chat|ham|0.2.1
CppSnippets|har|0.0.13
plantuml|jeb|2.7.5
cpp-pack|jew|0.0.2
Lua|key|0.0.9
luacoderassist|liw|1.3.8
ftp-sync|luk|0.3.3
markdown-shortcuts|mdi|0.8.1
vscode-language-pack-zh-hans|MS-|1.23.5
python|ms-|2018.4.0
cpptools|ms-|0.17.1
node-debug2|ms-|1.19.1
PowerShell|ms-|1.7.0
team|ms-|1.133.0
debugger-for-chrome|msj|4.4.3
vscode-code-outline|pat|0.2.1
node-tdd|pra|0.2.4
LiveServer|rit|4.0.0
partial-diff|ryu|1.1.0
text-marker|ryu|1.1.0
lrdb|sat|0.3.2
Align|ste|0.2.0
cmake-tools|vec|0.11.1
c-cpp-snippets|wlh|0.1.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Seems like a hardware/driver problem. Also getting off Windows 7 might fix your problems.
