### ISSUE TITLE
CompletionItem.additionalTextEdits should (optionally?) be a single undo action

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#50187]
In the Haxe extension, we implemented an auto-import feature using the `CompletionItem.additionalTextEdits` API. It works great, except for one thing: the insertion of the item itself and the additional edit are two separate undo actions. As you can see here, to undo both, I have to press Ctrl+Z twice, so it's a bit cumbersome:

![](https://i.imgur.com/DZ7amJv.gif)

Instead, I expected that both edits would count as a _single undo action_, as I'm used to from other IDEs. [IntelliJ does it that way with Java for instance](https://i.imgur.com/R5wgBZy.gifv). It seems this is not specific to how we implemented this in Haxe, as TypeScript's auto-import in VSCode [has the same issue](https://i.imgur.com/28Ifi1Z.gifv).

______________

I can see two solutions to this:

- always merge the insertion of the item itself and all the additional edits into a single undo action
- allow specifying whether an additional text edit should be merged into the "main" undo action via an additional flag

The first solution is probably not acceptable since it might be considered a breaking change and some use cases may rely on the old behavior.

**Comment by jrieken** [comment]
Possible but only when not having a snippet as insert text...

**Comment by Gama11** [comment]
That's ok for us in most cases. Out of curiosity, why would it only work for `PlainText` insertions?

**Comment by jrieken** [comment]
Fair question... We did it because usually snippets cause more followup edits and are more closely related to manual edits appearing after its insertion, e.g. you insert a snippet, then the user fills in it placeholders. 

Tho, thinking about this again and we should consider always having one undo operation for both inserts...

**Comment by Gama11** [comment]
>we should consider always having one undo operation for both inserts

That would be helpful for us in the case of generating an override - that can generate auto-imports via `additionalTextEdits`, but is also a snippet insertion at the same time to change the cursor position:

![](https://i.imgur.com/luIkc8s.gif)

For "regular" auto-imports when selecting an unimported type from completion, we don't use snippet insertion.

**Comment by jrieken** [comment]
Yeah, I agree and think it's in reach. @mjbvz I vaguely remember that we talked about this in the context of TypeScript completions that add an import. Having a single undo operation would mean that the completion *and* import would disappear. Would that work for you?

**Comment by jrieken** [comment]
@mjbvz ping

**Comment by jrieken** [comment]
Ok, we will try that change and see if we break to much muscle memory...
