### ISSUE TITLE
Support for custom SymbolKind values

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#50186]
I've added `Go to Symbols` support to [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus), and I had to pick a `SymbolKind`, but none of them makes sense for this extension, as it's not providing syntax highlighting for a programming language.

I think there should either be support for passing no value for `SymbolKind` (hiding the icon, this is not happening at the moment) or support for defining custom `SymbKind`s.

<img width="1254" alt="screen shot 2018-05-20 at 17 05 10" src="https://user-images.githubusercontent.com/1812093/40280309-5d5e51a6-5c51-11e8-8ebf-c662ae799a2d.png">

**Comment by jrieken** [comment]
> support for passing no value for SymbolKind (hiding the icon, this is not happening at the moment) or support for defining custom SymbKinds.

We will not so custom icons because that puts a higher burden onto extension authors, esp when this bubbles up to the LSP which then means you can to provide icons matching various different IDEs/editors. Having no icon seems like an option but might also look weird when having mixed items, e.g. with and without icon...

**Comment by fabiospampinato** [comment]
> We will not so custom icons because that puts a higher burden onto extension authors

How so? They could just keep using one of the available SymbolKinds.

> Having no icon seems like an option but might also look weird when having mixed items, e.g. with and without icon...

In my particular case I'm only providing file-level symbols, and there aren't any other symbols providers for that file type.

IMO it would also be weird if 2 completely different things use the same symbol, i.e. maybe somebody uses `SymbolKind.Field` for fields while my extension uses it for projects, mostly just because that icon has the same color as projects in `*.todo` files highlighted by my extension.

**Comment by Q-back** [comment]
@jrieken 
I'm confused. Do you mean that it will **not be possible** to provide custom icons for _outline_/_symbol list_? https://github.com/microsoft/vscode/issues/51334
On the other hand [here](https://github.com/microsoft/vscode/issues/49995#issuecomment-539423720) you said it should be possible.

Can you confirm if it's possible to provide custom icons for outline, please?
