### ISSUE TITLE
Gulp cannot find locally installed node

### ISSUE THREAD

**Issue by NN---** [Microsoft/vscode#50193]
I have node installed in local folder and not installed globally.
For different tools I configured to run with terminal and configured node path:

```
"terminal.integrated.env.windows": { "PATH": "mynodepath" },
"tslint.nodePath": "mynodepath",
"npm.runInTerminal": true,
"yarn.runInTerminal": true,
```

I don't see option to configure gulp autodetected to use terminal and avoid installing Node globally.

```
'node' is not recognized as an internal or external command,
operable program or batch file.

Auto detecting gulp for folder Test failed with error: Error: Command failed: node_modules\.bin\gulp.cmd --tasks-simple --no-color
'node' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by Tyriar** [comment]
You should just add node to your PATH globally, that solves all the issues. Otherwise you can do it for each feature/extension:

```
"terminal.integrated.env.windows": { "PATH": "mynodepath;${env.PATH}" }
```

**Comment by NN---** [comment]
I have already set nose in terminal path but seems like VSCode gulp runner doesn’t use it.
Adding node globally is not a good option for me.

**Comment by Tyriar** [comment]
@NN--- you can report against the extension if you want but the real solution is to globally set it. Maybe you could try a powershell/batch script to setup the node path when launching VS Code?

**Comment by NN---** [comment]
According to documentation it is not an extension but part of VSCode: https://code.visualstudio.com/docs/editor/tasks

**Comment by Tyriar** [comment]
Which part? tslint is an extension, if `npm.runInTerminal` is true it should inherit the env from `terminal.integrated.env.windows`.

**Comment by NN---** [comment]
My bad, I thought it comes with VSCode.
Thanks.
