### ISSUE TITLE
WYSIWYG mardown editor

### ISSUE THREAD

**Issue by arangates** [Microsoft/vscode#50194]
when people open markdown beginners might find it hard to edit the markdown files.
so a WYSIWYG markdown editor would be very much guiding and much ergonomic.
just like what https://stackedit.io/app# does and the good new is ,it is open source already https://github.com/benweet/stackedit

**Comment by usernamehw** [comment]
With markdown extensions and a toolbar below menu it would be kind of similar to WYSIWYG.

Configurable toolbar - #41309
