### ISSUE TITLE
We need: A Universal, Configurable Outline View / Tree view

### ISSUE THREAD

**Issue by ipalfy** [Microsoft/vscode#50191]
Having a "universal", configurable Outline / Treeview would be an extremely important feature-addition to vs code. All others have it, eclipse has it a lot, JetBrains does it very smart and even Visual Studio (non-code) is full of tree views. And even if vscode calls itself an editor: A good treeview is essential.

In fact I have half a dozen of extension installed, a markdown outline, a json tree view and an xml Treeview. This is getting really chaotic, since all work somehow different. Besides all that we have outlining in files (expand / collapse). Interestingly Code outlining works well in most cases, even with pug (jade) files.

However code outlines are hard to use. Those outlining keyboard shortcuts are hard to remember, and the tiny +/- signs are hard to reach with the mouse. BTW: why not make the whole area left to a collapsible region clickable to collapse?

So a universal Treeview could be the solution, one that works (at least) with the same collapse-points as the editors code outline. There might be a dozen of additional features for outlines when it coms to js, c# and others,  but I am not even sure they are needed, since code files should be as small as possible anyway.

The really annoying files (that need a treeview) are Html, css (less, sass), Markdown, json, xml, etc. And yes, the Treeview has to be fast, even with large files. Otherwise its useless. 

In addition:

- I would like to synchronize the treeview with the editors code outline, so I could optionally use the tree to expand / collapse inside the editor-view too. For example when clicking with cmd-key pressed. This could make sense in both directions.
- An optional, realtime "Highlight in tree" would also be very welcome. So when I scroll trough a file, I can see where I am in the tree. Branches will open (if not already expanded) and close automatically after scrolled over. Similar to Bootstrap's scrollspy.
- Another important addition could be a tree filter, so only branches are shown containing a given word.
- For json / xml-Files, the branch names could be made of "*name*" attributes, so we don't get a list of guids a s a tree. It would be really smart to make the naming of a branch configurable.
- Another nice options is (via icon): close (collapse) one or all Childs of a branch. This would be awesome in file explorer too!
- Two other icons could be useful: > (right) and < (left) to set the level of open branches throughout the tree. I would prefer this over level-numbers.

Ok, not the right place, but I would even organize everything in the lower pane - where terminal is - in a treeview. So you could add a new terminal window, like adding a new file in explorer. This way, selecting one of the many open terminal sessions would be much easier and less hidden than in a dropdown.

**Comment by Gruntfuggly** [comment]
There is a new outline view in the pipeline, with several of your requested features. You can try it in the Insiders build...

**Comment by ipalfy** [comment]
Yes, I saw: @jrieken seems to work on it. I just wanted to add my five + 1 cents to it. See also https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+outline+label%3Aoutline

**Comment by ipalfy** [comment]
Now I hope, @isidorn doesn't not get too confused with this ;-)

**Comment by ipalfy** [comment]
Whoah: Just looked at insiders build. Awesome! Love it!

**Comment by isidorn** [comment]
Seems to be done, @ipalfy please open a new issue if you stil have some ideas on how to improve

**Comment by ipalfy** [comment]
Yes, all fine.

**Comment by elhispano** [comment]
I can't see regions in the outline view in c#. There is some way to add support for this?
