### ISSUE TITLE
VSC loses encoding of characters

### ISSUE THREAD

**Issue by IrishJoeUS** [Microsoft/vscode#50197]
Issue Type: <b>Bug</b>

We support English and Spanish speaking users. We have strings containing Spanish text within the code. When opening files containing accent marks over vowels, the accented characters are replaced with "�" with no warning and saved that way. 

I cannot find a way to have VSC automatically open and save files with (Central Europen) Windows 1250 or other compatible encoding. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jshint|dba|0.10.18
vscode-eslint|dba|1.4.9
xml|Dot|1.9.2
tslint|eg2|1.0.29
javac-linter|fau|1.3.1
beautify|Hoo|1.3.0
classic-asp|ili|0.0.2
Angular2|joh|6.1.1
classic-asp-html|jtj|0.1.0
Angular-BeastCode|Mik|6.0.15
debugger-for-chrome|msj|4.4.3
java|red|0.25.0
vscode-icons|rob|7.23.0
open-in-browser|tec|1.1.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.8.0
JavaScriptSnippets|xab|1.6.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by IrishJoeUS** [comment]
I played around with the encoding at the bottom right, but I need a way for all of our source files to load and save with the original encoding intact and not altered.

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by IrishJoeUS** [comment]
@bpasero Can you point me to where in Visual Studio Code I need to go to set the

"[markdown]": {
    "files.encoding": "utf8"
}

or perhaps a better choice

"[markdown]": {
    "files.encoding": "Windows 1250"
}

So that all files are automatically opened and saved with the encoding to preserve the accented vowels?

I have been looking at the menu options in VSC, but I have not been able to locate where to set that.

Thanks.

**Comment by bpasero** [comment]
@IrishJoeUS `Ctrl+Shift+P` > User Settings

**Comment by IrishJoeUS** [comment]
I also tried 

"[markdown]": {
"files.encoding": "utf8"
}

but still the accented vowels are translated to �. Sorry if I am being dense about this.

**Comment by bpasero** [comment]
@IrishJoeUS if you look at the lower right status bar you can see the encoding that is currently used for the file. If you see the encoding is proper and the text is still showing ???, then the encoding is not matching the one of the file you are opening.

**Comment by IrishJoeUS** [comment]
Hi @bpasero. Good idea to check that. I tried

{
    "[markdown]": {
        "files.encoding": "windows1252"
        }
}

In the user settings and when that didn't work the workspace settings, but it is being ignored because when I open the code files the encoding in the lower right still says UTF-8 and all the accented vowels are changed to �s. 

I only have 
{
    "[markdown]": {
        "files.encoding": "windows1252"
        }
}
in the user settings (and tried the same in workspace settings). Am I missing some extra code to make the windows 1252 encoding take effect?

**Comment by IrishJoeUS** [comment]
@bpasero I may have stumbled onto a solution. I kept trying things and eventually tried removing parts of the example until my user settings contained only 

{
        "files.encoding": "windows1252"
        
}

And nothing else. So far opening files with that has resulted in the correct encoding.
