### ISSUE TITLE
Add the directory from the vs code command line to the workspace

### ISSUE THREAD

**Issue by rlvillacarlos** [Microsoft/vscode#50198]
I have tried to search how to add the current directory of the vs code command line to the workspace but I cannot seem to find an answer. 

If this feature is already available, I would really appreciate if someone can point out how to do this. 

If in case this is not available, then can I request that this be added as a feature of future release. 

Thank you.

**Comment by bpasero** [comment]
@rlvillacarlos see the output of running `code --help`

![image](https://user-images.githubusercontent.com/900690/40294397-af7c922a-5cd5-11e8-9152-afa9d4a1c87a.png)

**Comment by rlvillacarlos** [comment]
Thanks
