### ISSUE TITLE
the Problems panel continues to show errors in a file even if it is deleted from the project

### ISSUE THREAD

**Issue by alessandroaiello** [Microsoft/vscode#50192]
The problems panel notified me of errors on a file, I removed the file from the project because I did not need any more but the panel kept showing errors related to the file, if I clicked on the problem, a notification signaled the absence of the file and suggested to create it

**Comment by sandy081** [comment]
@alessandroaiello Do you know which extension is generating those problems? Please file an issue against that extension as it is responsible to remove them.
