### ISSUE TITLE
VS CODE getting stuck on ZEN MODE when hitting alt + tab multiple times

### ISSUE THREAD

**Issue by OguzhanKelleci** [Microsoft/vscode#50195]
- VSCode Version: Latest version of vs code  (20-05-2018)
- OS Version: Windows 10

Steps to Reproduce:

1. Get in vs code open a project , get in ZEN MODE ( ctrl + K Z ) 
2. Hit (alt + tab) multiple times, spam it than your whole pc is stuck and only mouse can move

Does this issue occur when all extensions are disabled?: Yes/No
 Edit: YES it still occurs

**Comment by mjbvz** [comment]
So when you disable extensions, this issue goes away?

**Comment by OguzhanKelleci** [comment]
I disabled extensions and it still occurs

**Comment by isidorn** [comment]
Please follow these steps to file better perfomance issues
https://github.com/Microsoft/vscode/wiki/Performance-Issues

Also only try to repro with insiders.
Can you also repro if you just go to full screen? And not zen mode
