### ISSUE TITLE
Insiders changes breaks some implementations of DocumentSymbolProvider

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#50207]
The current version of Dart code's symbol provider works in Stable, but shows 0 results in Insiders.

I think this is because I'm not returning an instance of `SymbolInformation` but rather returning an object that implements the (previous?) interface.

I suspect this will be considered a bug of mine and I should be creating instances of `SymbolInformation`, however it's possible others have done this and the failures appears to be silent (I don't see any warnings that what I returned will not be used).

I think this has come up before - TypeScript is happy that my objects are the required type, but changes in Code sometimes fail if they're not real instances. I'm not sure what the official line is (or whether there's a TypeScript setting I can enable to warn when people do this?).

**Comment by jrieken** [comment]
>  TypeScript is happy that my objects are the required type, but changes in Code sometimes 

Yeah, that some TypeScript weirdness as they don't consider the ctor being part of the structural identity... I'll see if I can make a change

**Comment by jrieken** [comment]
Hm, this actually shouldn't be an issue anymore. I have pushed https://github.com/Microsoft/vscode/commit/49323b3798d2595bcaa093c94d45b7f3627bfff1#diff-6ed04bc0a0e32b52bb98d493792f857e 12 days ago... @DanTup Do you recall with what version of insiders you have tried this?

**Comment by DanTup** [comment]
I don't, but my tests are still failing today on the CI (I run them on stable and insiders). LMK if you can't repro and I'll make a small code sample.

**Comment by jrieken** [comment]
Yeah, there was another nested instanceof-check. Messy stuff... I have pushed a workaround that help for now. This code will likely undergo further changes when the API becomes stable
