### ISSUE TITLE
OutputEvent, where does it go to

### ISSUE THREAD

**Issue by maziac** [Microsoft/vscode#50208]
Hi,

I'm trying to make use of the OutputEvent. I thought it would output some text to the console.

E.g. in launchRequest I use:

	const outputEvt = new OutputEvent('Error', 'loading');
        this.sendEvent(outputEvt);

When this code gets run nothing happens.

I.e. where should I find it's output?

- VSCode Version: 1.23.1
- OS Version:macOS 10.13.4

**Comment by roblourens** [comment]
It does go to the debug console but you have to change the category. These are the values that vscode accepts: `'console', 'stdout', 'stderr', 'telemetry'`
