### ISSUE TITLE
"Convert to ES6 module" not working with IIFE pattern

### ISSUE THREAD

**Issue by osya** [Microsoft/vscode#50205]
- VSCode Version: 1.23.1
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Create a file test_file.js with the following content:
```
var path = require('path');

(function () {
    var path = require('path');
}());
```
![scr](https://user-images.githubusercontent.com/998657/40297920-14f5fae2-5cea-11e8-86d1-cc4261470383.png)
Click lightbulb and select "Convert to ES6 module" then the 1st `require` transforms to the `import path from "path";`. It is correct. Then comment 1st `require` and click lightbulb and select "Convert to ES6 module" for the 2nd `require`. 2nd `require` doesn't converted to the `import path from "path";`. ES6 imports must be at the top level of your JavaScript files. So, I suppose, for `require` in IIFE there should be NO option "Convert to ES6 module"

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24297
