### ISSUE TITLE
SVG - Unknown config { editor.tabSize }

### ISSUE THREAD

**Issue by IamManchanda** [Microsoft/vscode#50209]
<img width="943" alt="screen shot 2018-05-21 at 3 53 26 pm" src="https://user-images.githubusercontent.com/4970624/40303129-2d6b9dfa-5d0f-11e8-9479-899eb0c5369a.png">

**Comment by sandy081** [comment]
@IamManchanda This is because there is no language registered with id `svg`.

**Comment by IamManchanda** [comment]
But what if I need it?

**Comment by sandy081** [comment]
There should be an extension registering that language... but what is your usecase?
