### ISSUE TITLE
Save as isn't translated in command palet

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/vscode#5020]
- VSCode Version: 0.10.14 -Insiders
- OS Version: Windows7
- Local: Japanese

 ### Issue
[Save as] isn't translated in command palet. see following image.

![saveas](https://cloud.githubusercontent.com/assets/9623009/14310612/c8b966ca-fc1d-11e5-981d-132814f842c8.png)

In [FIle] - [Save as] is translated as `名前を付けて保存`.

**Comment by isidorn** [comment]
Verified by code review, translations will arrive tomorrow
