### ISSUE TITLE
[Feature Request] Shortcut key for Debug and Docker

### ISSUE THREAD

**Issue by IamManchanda** [Microsoft/vscode#50211]

**Comment by IamManchanda** [comment]
For a person like me ... who is always looking for extra canvas space ... I really hide the activity bar and rely on shortcut keys for other things ...

For debug and docker (not using docker right now)... I need to reopen the activity bar ... I think this needs to be corrected!

**Comment by roblourens** [comment]
For debug you have ctrl+shift+d. For Docker you can assign your own shortcut to the "Show Docker" command

**Comment by IamManchanda** [comment]
@roblourens Nothing happens with `ctrl+shift+d` (I am on a mac)

**Comment by roblourens** [comment]
cmd+shift+d on mac
