### ISSUE TITLE
 source: property 'sourceReference' is missing

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5021]
Issue Id: <b>a7ec43ce-8e47-9380-f877-47043ebb6d6a</b><br /><br />*Versions* <br />- 0.10.12-insider<br />-  4ce22442fa12d252ab0ead8b64b0cf68220196f3<br />-  17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c<br />-  e0c7d51ffaee89b1db81683697b91531ee57cdbd<br />-  0f5937cb211ab3dd8ac6690ffea102251b05c7f2<br />-  43ff6af3d4564f59196caa9be4897fc33c15f24c<br />*Stack* <br />Error: source: property 'sourceReference' is missing<br />[/vs/workbench/parts/debug/node/rawDebugSession.ts#L79:29](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/src/vs/workbench/parts/debug/node/rawDebugSession.ts#L79:29)<br />[/vs/base/common/winjs.base.raw.js#L1470:0 (onError)](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/src/vs/base/common/winjs.base.raw.js#L1470:0 (onError))<br />[/vs/base/common/winjs.base.raw.js#L1176:0 (_notify)](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/src/vs/base/common/winjs.base.raw.js#L1176:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/src/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1316:0 (_run)](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/src/vs/base/common/winjs.base.raw.js#L1316:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L79:5 (errorDispatch)](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/src/vs/workbench/parts/debug/node/v8Protocol.ts#L79:5 (errorDispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L147:5 (clb)](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/src/vs/workbench/parts/debug/node/v8Protocol.ts#L147:5 (clb))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L114:11 (dispatch)](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/src/vs/workbench/parts/debug/node/v8Protocol.ts#L114:11 (dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L69:8 (handleData)](https://github.com/microsoft/vscode/blob/ef2a1fcaa553d14d7731b284a5ac5e4a55c42936/src/vs/workbench/parts/debug/node/v8Protocol.ts#L69:8 (handleData))<br />    at emitOne (events.js:77:13)<br />

**Comment by isidorn** [comment]
I think this was fixed last week via f56ccb001a8d3fa2678303cd9ad6e46181c40b41
