### ISSUE TITLE
Ubuntu AppMenu HUD not working

### ISSUE THREAD

**Issue by andoniu** [Microsoft/vscode#50213]
- VSCode Version:
$ code --version
1.23.1
d0182c3417d225529c6d5ad24b7572815d0de9ac
x64

- OS Version:
$ uname -a
Linux oandoniu-mobl1.ti.intel.com 4.16.8-300.fc28.x86_64 #1 SMP Wed May 9 20:23:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Open code
2. xprop | grep GTK
3. click on code window
4. Should be available at least: _GTK_MENUBAR_OBJECT_PATH and _GTK_UNIQUE_BUS_NAME

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Currently this is reporting the same as Chrome does, you should follow this up against Chromium/Electron
