### ISSUE TITLE
Doesn't warn usage of undefined class properties

### ISSUE THREAD

**Issue by goldylucks** [Microsoft/vscode#50216]
Issue Type: <b>Bug</b>

When I just installed vscode, the following would throw warnings:
```js
class Foo () {
  bar = this.undefinedMethod() // should warn
  baz = this.undefinedProperty // should warn
  func = () => this.undefinedMethod() // should warn
  func = () => this.undefinedProperty // should warn
}
```

I think the warning was "undefineMethod doesn't exist on class Foo".

Now I get no warnings.

I tried disabling all extensions and still no warnings. I don't know how to reproduce the expected behavior.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 843)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.43GB (6.74GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by goldylucks** [comment]
The above 2 links by @vscodebot don't cover this issue

**Comment by mjbvz** [comment]
We don't show semantic errors in js by default. You need to [enable typechecking](https://code.visualstudio.com/Docs/languages/javascript#_type-checking). The easiest way is to add `// @ts-check` at the top of your file
