### ISSUE TITLE
Cannot find runtime 'node' on PATH.

### ISSUE THREAD

**Issue by gtzinos** [Microsoft/vscode#50215]
VS Code cannot find runtime 'node' on PATH. I've tried some ways to handle it, but failed.

VSCode Version: Version 1.23.1
OS Version: Ubuntu 16.04
Environment variables checked seems no problem there.
I can execute from the terminal with node app.js

launch.json:

       {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/job/app.js"
        }

I found a similar but closed issue at https://github.com/Microsoft/vscode/issues/32130

Workaround:

sudo apt remove code && sudo apt install code

**Comment by roblourens** [comment]
So the workaround of reinstalling Code makes it work? If it's working after that, is there still a problem?

**Comment by gtzinos** [comment]
Hello @roblourens , after reinstalled it worked for 2-3 debugs and after i reopened it, it failed again. I follow the same steps every time i get errors.

**Comment by roblourens** [comment]
How are you opening vscode? From the terminal, clicking on icon, etc?

**Comment by gtzinos** [comment]
Basically i am using ` code . `.

**Comment by roblourens** [comment]
And you said you can use `node` in the terminal? Can you use it in both the terminal that you are launching code from, and the integrated terminal in vscode?
