### ISSUE TITLE
Disable sideBarSectionHeader shadow

### ISSUE THREAD

**Issue by ronilaukkarinen** [Microsoft/vscode#50219]
Can you disable sideBarSectionHeader shadow? if not, I'd like to request that feature. I only found these in the the documentation: 

sideBarSectionHeader.background: Side Bar section header background color.
sideBarSectionHeader.foreground: Side Bar section header foreground color.

Screenshot:
![Shadow](https://rolle.design/shadow-screenshot.png "Screenshot")

**Comment by bpasero** [comment]
@ronilaukkarinen you could play with `scrollbar.shadow` but it has an impact on all scrollbar shadows, also in the editor etc.

**Comment by bpasero** [comment]
Closing as per https://github.com/Microsoft/vscode/issues/50219#issuecomment-394238893
