### ISSUE TITLE
File resolution issues with TypeScript, TSLint, etc. in projects which have been pnpm install'ed in the WSL

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#50214]
_(Please excuse this vague and slightly off-topic issue report since I was not sure where to post it in the first place.)_

In order to have a better shell at hand I wanted to move to WSL and run zsh. After installing the WSL I installed node and npm inside the WSL and afterwards pnpm inside of it. However I started to notice an issue when installing packages with pnpm from the WSL since pnpm does create a strict node_modules folder and relies heavily on symlinks to prevent duping. As you can imagine symlinks created inside the WSL aren't compatible with Windows itself since they are just files.

![image](https://user-images.githubusercontent.com/32624319/40305124-7fb91206-5cf9-11e8-87a9-9db8b973081e.png)

On the left side you can see the node_modules folder when running pnpm from Windows and on the right side when I run it from the WSL. Surprisingly enough command line tools and scripts defined in the package file all work well. The only actual issue are the symlinks that are confusing VSCode, the linter etc. since it cannot resolve imported packages from the node_modules folder as expected.

My current workaround is just to be careful and only install packages from a generic Windows cmd while leveraging the WSL for everything else.

I am curious and would like to know whether there is anything reasonable that can be done to fix this either in VSCode, pnpm or is it some bigger endeavor when it comes to the combination of WSL and Windows itself?

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
