### ISSUE TITLE
NPM Scripts tab. "Run" as default action for double-click

### ISSUE THREAD

**Issue by col1n** [Microsoft/vscode#50222]
People use this tab mostly to run npm scripts instead of editing.
Therefore , please, set "Run" as default action for double-click.

**Comment by egamma** [comment]
This requires API from the custom views. There is now an inline action to run a script pls see https://github.com/Microsoft/vscode/issues/49204#issuecomment-386990673

**Comment by egamma** [comment]
There is now the setting `npm.scriptExplorerAction` that allows to configure the default action on run.
