### ISSUE TITLE
Disable filename column in Debug console

### ISSUE THREAD

**Issue by d-sphinx** [Microsoft/vscode#50227]
Is it possible to remove "filename link" column in the debug console output? It takes valuable horizontal screen space with absolutely no info for me, because all messages end with that "logger.js:49" link (and i know it already). I guess that "filename link" column should be at least optional.

Thank you.

**Comment by d-sphinx** [comment]
![2018-05-21 17_25_10-greenshot](https://user-images.githubusercontent.com/4455753/40313029-296e8178-5d1d-11e8-9c58-eb2d23f89283.png)

**Comment by isidorn** [comment]
This is currently not possible, but if more users ask for this feature we would be open to a PR that adds this debug configuration.

**Comment by weinand** [comment]
low-hanging fruit: fix it or close it.
