### ISSUE TITLE
Terminal history not deleted

### ISSUE THREAD

**Issue by Legends** [Microsoft/vscode#50225]
- VSCode Version: 1.23.1
- OS Version: Win 10 x64

I have one annoying thing I want to report.
I have a comand under scripts in `package.json` which I execute via the terminal.

The command executes and throws an error, because of a bug in my code.
The cmd spits out a ton of data regarding the error including stacktrace.

Now I do: `cls` to clear the screen, which works.
But if I execute the command again, after I've made some code adaptations and there is still an error, I scroll up to see the beginning of the error text, but the previous error text appears above again, which makes it difficult to distinguish, am I still looking at the current issue or did I scroll too high and looking at the previous error...

As a workaround I kill the terminal, then the history is gone!

Obviously I don't want to kill the terminal everytime, just execute `cls` to clear it.
It should be like with `cmd.exe`.

**Comment by Tyriar** [comment]
ctrl+k on Windows will clear the terminal, what you're seeing is https://github.com/xtermjs/xterm.js/issues/106

**Comment by Legends** [comment]
When I press Ctrl + K I get:

> ^K

Didn't get...

**Comment by Tyriar** [comment]
Ah that's because you have a chord defined in your keybindings or an extension adds one (this happens for complicated reasons). You can fix this by adding the keybinding to the bottom of your keybindings.json or by calling "Terminal: Clear" through the command palette (F1):

```js
{ "key": "ctrl+k",                "command": "workbench.action.terminal.clear",
                                     "when": "terminalFocus" }
```

**Comment by Legends** [comment]
Not sure what I have defined :-) , but this works nice! Thanks!
