### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by harlyon** [Microsoft/vscode#50220]
Requesting for a feature which allows for user profile to be created into VScode. this will save all user snippets,themes and extension. in a case whereby a user workstation is damaged or crashed ,one can be able to download VScode on a new machine with his profile and all snippets, themes and extension are added automatically

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Duplicate of #329 / #2743
