### ISSUE TITLE
Git doesn't highlight uncommited changes and can't open any file from the Git panel

### ISSUE THREAD

**Issue by krasi-georgiev** [Microsoft/vscode#50229]
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Fedora 27

Does this issue occur when all extensions are disabled?: Yes

![simplescreenrecorder-2018-05-21_18 49 53](https://user-images.githubusercontent.com/8903888/40317236-90969eb0-5d29-11e8-968a-71c192d263ae.gif)

**Comment by joaomoreno** [comment]
Can you run `Git: Show Git Output` to see which commands Git is running?

Can you open the `Developer Tools` and see if you have errors within?

**Comment by krasi-georgiev** [comment]
This is the log after doing the following.


Open vscode
edit `vendor/github.com/prometheus/tsdb/db.go`
Go to git view to see all modified files. 
Open `db.go` - at this point it shows the blue lines where the file is modified.
Switch the tab to open another file
Switch the tab back to a modified file - at this point the blue lines have disappeared.

When I switch tabs only these logs lines show
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel


Looking for git in: git
Using git 2.17.0.391.g1f1cddd55 from git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /home/krasi/src/github.com/prometheus/prometheus
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :vendor/github.com/prometheus/tsdb/db.go
> git check-ignore -z --stdin
> git rev-parse --show-toplevel
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git check-ignore -z --stdin
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel

Just now I noticed that when I edit ` cmd/prometheus/main.go` it works as expected and always shows the blue lines for uncommitted changes.

this file is not in the .gitignore or the exclude list.

https://github.com/prometheus/prometheus/blob/master/.gitignore


```
cat  .git/info/exclude
# git ls-files --others --exclude-from=.git/info/exclude
# Lines that start with '#' are comments.
# For a project mostly in C, the following would be a good set of
# exclude patterns (uncomment them if you want to use them):
# *.[oa]
# *~
.DS_Store
.vscode
.gitmodules
go.mod
debug
cmd/prometheus/data*
```

**Comment by krasi-georgiev** [comment]
no error in the console view of the Developer Tools

**Comment by joaomoreno** [comment]
Can you reproduce in a smaller sample repository?

**Comment by krasi-georgiev** [comment]
sorry wouldn't have time for that , what is the problem with the prometheus repo? shouldn't take more than few seconds to download.

**Comment by joaomoreno** [comment]
I cloned the prometheus repo and cannot reproduce this issue.

What I meant with my question was: do you also see this behaviour in smaller repositories?

**Comment by krasi-georgiev** [comment]
Did you edit the same file ?
`vendor/github.com/prometheus/tsdb/db.go`
I think it only happens in files under the vendor dir.


I will monitor if it happens in smaller repos.

**Comment by joaomoreno** [comment]
Yes I edited the same file. Let me know if it repros in smaller repos.

**Comment by smilingpeanut** [comment]
This also happens on my machine with any of my local repos. I also cannot stage individual files... I can only stage all changes. It's been happening for several months.

When I try to see the changes in a file, this gets logged in the console:

https://cloudup.com/cmM-Gi9r2Gi (screenshot)

macOS High Sierra 10.13.4
Code 1.23.1 d0182c3417d225529c6d5ad24b7572815d0de9ac

Not sure what other information is needed, but I'm happy to provide it.

**Comment by joaomoreno** [comment]
@smilingpeanut You have a different problem. Please file a new issue and cc me there.
