### ISSUE TITLE
Bad suggestion from typescript

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50228]
Maybe this is as designed but it's a pretty bad suggestion in this case as it breaks the code:

![image](https://user-images.githubusercontent.com/2193314/40314862-a4094ed0-5cce-11e8-8cd1-0deb77b9afc1.png)

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/24303 to track this upstream

**Comment by Tyriar** [comment]
@mjbvz thanks for putting together the stripped down example for them!
