### ISSUE TITLE
TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5022]
Our error telemetry reports now also reports issues for extension.
The 'Cannot read property 'document' of undefined' occurs for may different plugins, e.g.
 - https://github.com/spywhere/vscode-guides/issues/2
 - https://github.com/Microsoft/vscode/issues/5007
 - .vscode-insiders/extensions/mitaki28.vscode-clang-0.2.0/out/src/extension.js:71:55 
 - .vscode-insiders/extensions/Ionide.Ionide-fsharp-1.5.2/fsharp.js:3142:34

Wondering if these are related and if we should do something about it (maybe better document it)

**Comment by jrieken** [comment]
For some it seems like `activeTextEditor` isn't understood be `undefined` in cases. Also, I know we make it `undefined` when changing

**Comment by jrieken** [comment]
Made the doc more clear, made the falsy value `undefined` in all cases
