### ISSUE TITLE
emmet preference not working on scss file

### ISSUE THREAD

**Issue by pfreema1** [Microsoft/vscode#50224]
- VSCode Version:  1.23.1 
- OS Version:  macOS Sierra Version 10.12.6

Setting the emmet.preference property `sass.propertyEnd` to `""` still results in a `;` being added to the end.

Steps to Reproduce:

1.  in User Settings, add the following:
`"emmet.preferences": {
      "css.propertyEnd": "",
      "sass.propertyEnd": ""
  }`

2.  In a scss file, use emmet to auto fill a property on a class.  It still ends with `;`, even though it should be nothing.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by ramya-rao-a** [comment]
For scss files, use `scss.propertyEnd` instead.
