### ISSUE TITLE
Found Solution for Cursor jumping to EOF

### ISSUE THREAD

**Issue by EGCCKingdom** [Microsoft/vscode#50236]
I was learning how to configure VS Code and after a while, every time I typed in a single letter and paused to look at the dropdown of possible next letters, etc., the cursor would jump to the EOF. 

This was horribly frustrating. It occurred to me that I had added the following user setting:

"files.autoSave": "afterDelay"

YUP! When I removed that, everything works as I expected. This is a bug in the AutoSave mechanism because it loses the place of the cursor and ends up at the end of the file.

**Comment by weinand** [comment]
@EGCCKingdom I'm always using `"files.autoSave": "afterDelay"` and I've never experienced this.
Do you still see this problem when you disable all extensions?

**Comment by weinand** [comment]
@EGCCKingdom and @kennedyps4: Do you still see this problem when you disable all extensions?

**Comment by EGCCKingdom** [comment]
I have no idea. I am writing from my laptop, but the VS Code issue was on my PC. Unfortunately, my Windows 10 update wiped out the boot record on my PC. I am dead in the water and praying I haven't lost years of work. That's a whole other thread I've got to deal with.



________________________________

**Comment by chrmarti** [comment]
Might be an extension that updates the file on save. Let us know if you see this without extensions.
