### ISSUE TITLE
Remove breakpoint freezes touchpad buttons

### ISSUE THREAD

**Issue by santiagoaldanondo** [Microsoft/vscode#50230]
- VSCode Version: 1.23.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Create a breakpoint.
2. Edit breakpoint to "Log Message"
3. Click "Remove Breakpoint"
4. The touchpad buttons freeze and stop working untill you kill the process.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by santiagoaldanondo** [comment]
I think it might be that VSCode gets frozen due to an error and then the touchpad buttons stop working. Everything works but I cannot click anywhere, nor in VSCode neither in any other application. It happened to me again today trying to debug a program and getting a timeout

**Comment by santiagoaldanondo** [comment]
Well, this has only happened to me using vscode, so I can't tell if there is something else that does not work in my computer. 

The mousepad buttons stops working, but I can use the keyboard and use the mousepad for moving.

The problem is only solved after killing vscode processes. In fact when killing these processes using "top" from terminal, they keep reproducing, so I ended up running killall vscode.

I could record this problem but I cannot figure out how to show that I am actually clicking the buttons in the touchpad.

**Comment by roblourens** [comment]
> Click "Remove Breakpoint"

Do you right click on the breakpoint, then find "Remove Breakpoint"? Or do you click the breakpoint, see a dialog popup, and click "Remove Breakpoint" on that popup?

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/50026

**Comment by santiagoaldanondo** [comment]
1. Left click to create breakpoint
2. Right click on breakpoint, click edit breakpoint
3. Click on dropdown, select log message, write something on the input and press enter
4. Left click on the breakpoint
5. A popup is shown telling "This logpoint has a message that will be lost on remove. Consider disabling the logpoint instead -> The touchpad buttons stop working.
6. Use Alt + Tab to navigate to the console, run killall code a couple of times (first time the popup is still there).
7. Back to work
