### ISSUE TITLE
TypeScript auto imports no longer show in intellisence once a type has been added locally

### ISSUE THREAD

**Issue by duro** [Microsoft/vscode#50233]
Issue Type: <b>Bug</b>

I have noticed that when all my types are living in the @types directory, ass is well. Libraries like React, React Native, etc. all of their exposed modules show up as you type, and can be auto-imported.

But once I try to overload or extend the types for a library, ALL of the exposed modules, including the ones I have declared locally, no longer show.

Once the module has been manually imported, type checking and intellisence works.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.28.1
vscode-docker|Pet|0.0.27
vscode-eslint|dba|1.4.9
tslint|eg2|1.0.29
vscode-great-icons|emm|2.1.32
prettier-vscode|esb|1.3.1
flow-for-vscode|flo|0.8.1
docthis|joe|0.6.0
vscode-styled-components|jpo|0.0.18
string-manipulation|mar|0.2.0
terraform|mau|1.1.2
vscode-language-babel|mgm|0.0.14
typescript-javascript-grammar|ms-|0.0.41
vsliveshare|ms-|0.3.125
debugger-for-chrome|msj|4.4.3
color-highlight|nau|2.3.0
vscode-coverage-gutters|rya|2.0.0
vscode-fileutils|sle|2.8.1
vscode-react-native|vsm|0.6.10
jinja|who|0.0.8

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Can you please provide a code example of this problem or a small example project

**Comment by duro** [comment]
@mjbvz Please see this repo for a reproduction. Readme has simple instructions to reproduce.

https://github.com/duro/react-native-vscode-type-issue-repro

**Comment by mjbvz** [comment]
Thanks. I cannot reproduce this issue in vscode insiders:

![screen shot 2018-05-23 at 10 55 34 am](https://user-images.githubusercontent.com/12821956/40442217-d9eba714-5e77-11e8-9a58-a6ba1cba0aa9.png)


Can you please test in insiders with all extensions disabled.
