### ISSUE TITLE
 window title is not changing to new settings.

### ISSUE THREAD

**Issue by lion444** [Microsoft/vscode#50238]
window tile is not changing to new settings.

- VSCode Version:
Version 1.24.0-insider
Commit 912fff91ac4ff1bff9695e8da69abd729f7ae956
Date 2018-05-18T05:17:26.925Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:
Windows 7

Steps to Reproduce:

1. Open users settings file.
2. Enter "window.title": "${rootPath}${separator}${activeEditorName}${separator}${appName}"
3. Restart VS Code

**Comment by weinand** [comment]
@lion444 I cannot reproduce this problem with VS Code 1.24.0-insider on Windows 7.
And for me the window title change does not even require a "Restart VS Code":

![2018-05-22 10 44 32](https://user-images.githubusercontent.com/1898161/40351668-4635fdbe-5dad-11e8-9b8f-86b8b2940a88.gif)

Do you still see the problem when disabling all extensions?

**Comment by lion444** [comment]
Let me try disabling extensions.

**Comment by lion444** [comment]
disabled all extensions. Here is my settings. 'test' does not show:

{
    "workbench.colorTheme": "Visual Studio Light",
    "window.title": "test",
    "terminal.integrated.shell.windows": "C:\\Windows\\Sysnative\\cmd.exe",
    "typescript.check.tscVersion": false,
    "window.zoomLevel": 0,
    "extensions.ignoreRecommendations": false,
    "git.autofetch": true,
    "azure.resourceFilter": [
        "b4dfda2a-75c5-4351-a2e6-67183642ee8b/1b3b4c66-fda1-4ea6-a02c-7c22c01d4508"
    ],
    "gitlens.gitExplorer.view": "history",
    "gitlens.keymap": "alternate",
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": false,
        "suppressShowKeyBindingsNotice": true
    },
    "gitlens.historyExplorer.enabled": true,
    
}

**Comment by lion444** [comment]
hmm. it just now started working. No idea why, but thanks for the input.
