### ISSUE TITLE
[css] at-rule unknown error

### ISSUE THREAD

**Issue by raptoria** [Microsoft/vscode#50242]
I'm trying to use css-modules like so:
@value green: #aaf200;

and I keep getting 
[css] at-rule unknown.

I've tried installing and uninstalling every css-modules extension I could find, but the error won't go away. Any ideas?

VSCode Version: 1.23.1
Node: 7.9.0
OS Version: Windows 7 Professional

**Comment by aeschli** [comment]
The css support validated against the standard css spec. To turn off validation use
`"css.validate": false`

The request to support css-modules is #14539

**Comment by mfour-merickson** [comment]
I don't think disabling css validation completely is the correct approach for fixing this issue.   Is there any other possible solution?

**Comment by aeschli** [comment]
we have https://github.com/Microsoft/vscode-css-languageservice/issues/51 to improve the handling of unknown @at rules.

**Comment by raptoria** [comment]
I agree, I'd prefer not to have to give up CSS validation to use an at-rule in VS Code

**Comment by mfour-merickson** [comment]
I have “temporarily” gotten around this issue by moving CSS linting to Stylelint, but that should not be the desired solution.

 

- me

 

I agree, I'd prefer not to have to give up CSS validation to use an at-rule in VS Code

**Comment by aeschli** [comment]
Progress in tracked in Microsoft/vscode-css-languageservice#51.

@mfour-merickson If you can paste css examples where you get errors that would be helpful, so we can make sure these get fixed.

**Comment by raptoria** [comment]
@aeschli  this is the main error for me:
@value green: #aaf200;
