### ISSUE TITLE
Telemetry error log is flooded

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5024]
It seems that the new insiders build (0.10.13, 0.10.14) generates far more telemetry error entries than before. It's too many to process by the telemetry tracker.

- The entries are not correctly folded, due to the specific extension path in the trace
 TypeError: Cannot read property 'document' of undefined 
 at Function.readLineAt (C:\Users\a123\.vscode-insiders\extensions\vscodevim.vim-0.0.15\out\src\textEditor.js:65:53)
- We might want to turn of reporting logs for all extensions, although it is interesting to see commonly made errors, e.g, https://github.com/Microsoft/vscode/issues/5022

**Comment by jrieken** [comment]
[virtual-0.0.1.zip](https://github.com/Microsoft/vscode/files/208048/virtual-0.0.1.zip)

**Comment by aeschli** [comment]
I verified the fix running a build in Windows and Linux 64.

**Comment by jrieken** [comment]
@aeschli Can you add the verified tag?
