### ISSUE TITLE
Using Pipe transport to build task via g++ in WSL

### ISSUE THREAD

**Issue by Agarwal-Nikhil** [Microsoft/vscode#50247]
- VSCode Version: 1.22.2
- OS Version: Windows 10 Build 17134

Steps to Reproduce:

1. Write task.json using Pipe transport to build task via g++ in WSL

How to use Pipe transport to build task via g++ in WSL? What is the syntax of the tasks.json with pipe transport? (Reference: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md)

**Comment by dbaeumer** [comment]
@Agarwal-Nikhil can you provide the tasks.json. I am actually not sure I understand your problem. Do you want run the g++ compiler in WSL. If so this is supported by specifying bash as the shell to use and then run g++ inside the shell. However this has issue with problem detection variable resolving. Look for issues tagged with `WSL`. We are working on a approach to address this.

**Comment by Agarwal-Nikhil** [comment]
@dbaeumer Yes I want run the g++ compiler in WSL. Yes I am know that: If so this is supported by specifying bash as the shell to use and then run g++ inside the shell. What I want is to build the source code using task.json that is generated in the VS Code (Go to Top bar --> Go to Tasks --> Configure tasks). Also as WSL recommends data (files) to be stored in the Windows 10 (and not in WSL) how can we use variable like \"${file}\" as this path would in Windows notation of backslash, but WSL would require path in forward slash.

**Comment by dbaeumer** [comment]
If you want to provide a task that uses pipe transport then this can now be done using an extension. They can contribute tasks which don't need to be stored in the tasks.json but can augmented there.

Regarding the variable substitution: we are aware of this and are working on a solution for this.

Does this answer your questions?

**Comment by Agarwal-Nikhil** [comment]
Thanks for your reply. What's that extension? I searched for pipe but didn't get anything relevant.

**Comment by dbaeumer** [comment]
@Agarwal-Nikhil someone has to build it and add that support to VS Code via an extension. This can either be you or since it is g++ specific may be the MS vscode extension form the marketplace. We have no plans to support this out of the box right now.
