### ISSUE TITLE
Updates JS/TS imports on directory rename

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50244]
Follow up on #19439

**Request**
1. In a js project:

```
index.js
jsconfig.json
sub/
    a.js
    b.js
```

with `index.js`:

```js
import {a} from './sub/a'
import {b} from './sub/b'
```

1. Rename `sub` to `sub2`

**Expected behavior**
All import paths that reference `sub` get updated to `sub2`:

`index.js`:

```js
import {a} from './sub2/a'
import {b} from './sub2/b'
```

**Comment by mjbvz** [comment]
Depends on https://github.com/Microsoft/TypeScript/issues/24260

**Comment by AlCalzone** [comment]
Should this be working in 1.24.1 with TypeScript 2.9.2 or do I have to wait for another VSCode update?

**Comment by mjbvz** [comment]
No you need to be on vscode insiders

**Comment by jamesmillerburgess** [comment]
Really looking forward to this! 👍

**Comment by n2o1988** [comment]
Hi all, I'm on VSCode 1.25.1 and I still can't get the rename/move folders refactoring to work. It does work with single files, but not with folders. 
I was wondering if it is already available or if I need to wait for the next version (or be on `vscode insiders`) to have this?
