### ISSUE TITLE
insertSpaceBeforeFunctionParentheses not working for generic functions

### ISSUE THREAD

**Issue by hesxenon** [Microsoft/vscode#50245]
- VSCode Version: 
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows10 Pro
- Language: TypeScript

Steps to Reproduce:

1. set `"typescript.format.insertSpaceBeforeFunctionParenthesis": true`
2. write any function link `function formattingTest<T> (param: T) { }`
3. run autoformat
4. space between `>` and `(` is removed/is not inserted

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This appears to be fixed in VS Code insiders
