### ISSUE TITLE
image not loading from sub folders with out full pass 

### ISSUE THREAD

**Issue by wbiggs20** [Microsoft/vscode#50243]
I made a site in a folder  called website and an image folder called img I put the images in the folder ./ But is I open the .html file it says image not found but if I ad the image to the root folder it works 

- VSCode Version: 1.23.1
- OS Version: Windows 10 64 bit home

Steps to Reproduce:

1. add image <img src="../img/anything/png">
2. put image in a folder called img 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
@wbiggs20 how do you references the image in the html file?

**Comment by wbiggs20** [comment]
after I add the image in code the try opening it in a web browser

**Comment by weinand** [comment]
This is not a problem of VS Code.
