### ISSUE TITLE
Bad performance when executing `deleteLeft`/`type` in extensionHost

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#50254]
- VSCode Version: v1.24.0 insider 912fff9
- OS Version: Windows 10

Steps to Reproduce:

1. download [test.zip](https://github.com/Microsoft/vscode/files/2024839/test.zip)
2. install `test.vsix` then open `sample.md`
3. press <kbd>Backspace</kbd> several times (line 137 for example)
4. see the lag

The only thing that `test.vsix` does is registering a command `onBackspaceKey` and then execute `deleteLeft`.

```ts
export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(vscode.commands.registerCommand('onBackspaceKey', onBackspaceKey));
}

function onBackspaceKey() {
    return vscode.commands.executeCommand('deleteLeft');
}
```

```json
"commands": [
    {
        "command": "onBackspaceKey",
        "title": "On Backspace Key"
    }
],
"keybindings": [
    {
        "command": "onBackspaceKey",
        "key": "backspace"
    }
]
```

**Comment by alexandrudima** [comment]
@neilsustc I cannot reproduce any noticeable slow-down. I have added an "I am running" statement to your extension's command:

![kapture 2018-05-28 at 12 35 06](https://user-images.githubusercontent.com/5047891/40610653-93ea88ac-6273-11e8-9df1-c66cb7cc041a.gif)


I have added a strategic `console.log` statement to measure the impact of communicating with the extension host.
![kapture 2018-05-28 at 12 36 50](https://user-images.githubusercontent.com/5047891/40610736-d8e65454-6273-11e8-8c55-62295ed4416c.gif)

I could measure a latency of only a few ms (2-5ms) between the invocation of `onBackspaceKey` and the invocation of `deleteLeft`.

Do you have other running extensions when you attempt this? `F1 > Show running extensions`.

**Comment by neilsustc** [comment]
Can you test the `sample.md` (for example line 137) which is included in the zip.

**Comment by alexandrudima** [comment]
![kapture 2018-05-28 at 14 06 03](https://user-images.githubusercontent.com/5047891/40613799-4c7fecd4-6280-11e8-85ee-6c0c78965ace.gif)

The delay is again in the ms range (5-10ms).

**Comment by neilsustc** [comment]
Thanks. I am going to test it again and get back to you soon.

**Comment by neilsustc** [comment]
Okay, I find there is no observable delay using a clean build. So this issue is invalid.

BTW, I realise that the existed extension is not *fully replaced* although it says "Overwriting extension [the installed one] with [the one being debugged]" when debugging it.
I debugged my extension by commenting out all other features. But it seems that some of them are still taking effects...
