### ISSUE TITLE
Search File Pattern Fail

### ISSUE THREAD

**Issue by MrDesjardins** [Microsoft/vscode#50250]
Issue Type: <b>Bug</b>

If I search for "onclick" without the quote and without anything in the "files to include" or "files to exclude" I am seeing a result in some of my src/ folder inside some of my .tsx file.

However, if I add in the "files to includes" any of these possibilities, I have no result:
```
src/**/*.tsx
/src/**/*.tsx
**/*.tsx
*.tsx
```
I am expecting to see all the tsx file with "onclick"

VS Code version: Code - Insiders 1.24.0-insider (a521c01d56ec7f07bea2471880f28a77f37983af, 2018-05-21T05:11:15.297Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_327760|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
line-counter|dol|0.5.2
gitlens|eam|8.3.2
EditorConfig|Edi|0.12.2
tslint|eg2|1.0.29
vscode-codemetrics|kis|1.16.0
python|ms-|2018.4.0
vscode-jest|Ort|2.8.0
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.0.27
java|red|0.25.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.8.0
vscode-wakatime|Wak|1.2.2
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.6.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I fixed a couple bugs involving include patterns in Insiders. Can you try again with tomorrow's build? #50175 and #50311.

**Comment by MrDesjardins** [comment]
It's working now. Thank you very much for the fast response.
