### ISSUE TITLE
system halted

### ISSUE THREAD

**Issue by qhaMYW4cH** [Microsoft/vscode#50253]
Issue Type: <b>Bug</b>

step1.open vscode---------->open one c/c++ file
step2.press "F11",ful screen
step3.use ibus (chinese input),write something
step4.you will found ,the system balted

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3542)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|15.59GB (13.65GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.23.5
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.17.1
bar|olb|0.0.9
dlang-bundle|web|0.3.0

</details>

**Comment by Tyriar** [comment]
@qhaMYW4cH does it still happen when you close all windows and run `code --disable-extensions`?
