### ISSUE TITLE
VS Code Not Open

### ISSUE THREAD

**Issue by chandansharma702** [Microsoft/vscode#50258]
Issue Type: <b>Bug</b>

Hi ,
I like Microsoft product most but in case of vs code it is frustrating me when I open it. It shows always as keep waiting/Reopen in dialogue box and also not able to open any file. please do something.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (10.11GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
json-tree-view|Cha|1.1.0
compulim-vscode-closetag|Com|1.1.0
live-html-previewer|hdg|0.3.0
prettify-json|moh|0.0.3
python|ms-|2018.4.0
open-html-in-browser|pea|0.0.3
html-preview-vscode|tht|0.1.1
ab-html-formatter|zov|0.0.2

</details>

**Comment by Tyriar** [comment]
Can you post a screenshot of what you're seeing, just to be clear?
