### ISSUE TITLE
Use javascript not  AutoComplete?

### ISSUE THREAD

**Issue by yi-huan** [Microsoft/vscode#5025]
- VSCode Version: 1.0.0
- OS Version: win8.1

In the old version:
![default](https://cloud.githubusercontent.com/assets/5660790/14311474/44bf32c6-fc1a-11e5-8567-b2b277db63b1.gif)

Now:
![default](https://cloud.githubusercontent.com/assets/5660790/14311539/71559140-fc1a-11e5-85af-ac46c22ecddc.gif)

What should I do can be as old as ?

**Comment by yi-huan** [comment]
以上问题是根据 [官方文档中智能感知](http://code.visualstudio.com/docs/editor/editingevolved#_intellisense) 提出。
![111111111](https://cloud.githubusercontent.com/assets/5660790/14553966/6fa801b2-031c-11e6-849f-d0d51feb414d.gif)

**Comment by egamma** [comment]
Intellisense now only works for .js files. So you have to save the file with .js suffix and it will work as before.

![image](https://cloud.githubusercontent.com/assets/172399/14556496/bfce07b4-02f8-11e6-8c3a-39320a07f657.png)

**Comment by yi-huan** [comment]
@egamma Thank you so much.
