### ISSUE TITLE
Vscode下的终端在运行python，如果输出有很多行的时候会出现IOError: [Errno 0] Error的问题

### ISSUE THREAD

**Issue by arsenaltj** [Microsoft/vscode#50261]
Issue Type: <b>Bug</b>

Vscode下的终端在运行python，如果输出有很多行的时候会出现IOError: [Errno 0] Error的问题，而windows自带的powershell或者cmd就没有这个问题，这是怎么回事:
比如：
for i in range(100):
    print i

输出的时候就会有IOError: [Errno 0] Error

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.32GB free)|
|Process Argv|D:\development_software_soft\vscode\vscodeInstall\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.23.5
python|ms-|2018.4.0
cpptools|ms-|0.17.1
sublime-keybindings|ms-|4.0.0
veriloghdl|msh|0.3.2

</details>

**Comment by Tyriar** [comment]
Duplicate: https://github.com/Microsoft/vscode/issues/36630

It's fixed in Windows, you need to update.
