### ISSUE TITLE
Match case short cut (⌥⌘C) when searching inside file (⌘F) does not work anymore

### ISSUE THREAD

**Issue by godspeedelbow** [Microsoft/vscode#50263]
- VSCode Version: 1.23.1 (1.23.1)
- OS Version: Mac OS X 10.13.4

Steps to Reproduce:

1. Open file
2. `⌘F` to start searching
3. `⌥⌘C` to toggle **Match Case**. Verify that Match Case is *not* toggled

Note:
- `⌥⌘W` *does* toggle **Match Whole Word** 
- In **Find in Files** (`⌘⇧F`), **Match Case** _is_ toggled upon `⌥⌘C`

Does this issue occur when all extensions are disabled?: Yes

**Comment by godspeedelbow** [comment]
In **Find in Files** (`⌘⇧F`), **Match Case** _is_ toggled upon `⌥⌘C`

**Comment by roblourens** [comment]
No changes here, you probably have a conflicting keybinding.

You can check in the keybindings editor, you may have an extension that contributes a conflicting keybinding

![image](https://user-images.githubusercontent.com/323878/40383489-e4df6e5c-5db5-11e8-94cc-2d6529802e4d.png)

**Comment by godspeedelbow** [comment]
hi @roblourens, this is how it looks for me. Not sure about `copyFilePath` but it looks like no conflicts. Plus, this also happens when I run VS Code without extensions

<img width="914" alt="screen shot 2018-05-22 at 21 01 56" src="https://user-images.githubusercontent.com/1466424/40384308-6efd0264-5e03-11e8-82e8-9bdbb5161641.png">

**Comment by roblourens** [comment]
Can you try in insiders?

**Comment by roblourens** [comment]
Oh actually this was another bug, copyFilePath is taking over here. It's fixed in Insiders.
