### ISSUE TITLE
gitignore may not work well

### ISSUE THREAD

**Issue by CreeperLKF** [Microsoft/vscode#50260]
Issue Type: <b>Bug</b>

My .gitignore configured as
```
*.*

!*.cpp
!*.c
!*.py
!*.pas
!*.jar
!*.md
!*.tex
!*.bak
!*.h
!*.hpp
!*.lyx
!*.txt
```
and I can commit files which have suffix above.
but files which have suffix ".cpp" have grey color on the left file window(I forget the word).
I modified ".gitignore" and I find that if I add a line "!\*.log" before "!\*.cpp",
the \*.cpp files are trun to white but the \*.log files are still grey.
so I think Code ignored the first line of the .gitignore file...
I am not sure about if it is a problem.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.14.0-deepin2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6498DU CPU @ 2.50GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.68GB (2.90GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.23.5
material-icon-theme|PKi|3.4.0
mdmath|goe|2.2.1
vscode-graphviz|joa|0.0.1
changeEncode|lan|0.0.8
ecdc|mit|0.12.0
cpptools|ms-|0.17.1

(1 theme extensions excluded)

</details>

**Comment by CreeperLKF** [comment]
emm...
I think the bug is from git...
My .gitignore was set like this:
```
*.*

!*.txt
!*.cpp
!*.c
!*.py
!*.pas
!*.jar
!*.md
!*.tex
!*.bak
!*.h
!*.hpp
!*.lyx
```
But I get ".gitignore:3:!*.txt	test.txt" from running "git check-ignore" while I can track it, commit it and push it......
![deepinscreenshot_select-area_20180529181117](https://user-images.githubusercontent.com/28673129/40652843-02ea366e-636c-11e8-9b50-393b5c35a894.png)
![deepinscreenshot_select-area_20180529181820](https://user-images.githubusercontent.com/28673129/40653168-e59bbe7e-636c-11e8-997a-6736eb0f48bc.png)
The strange file was grey but modified like this
![deepinscreenshot_select-area_20180529181322](https://user-images.githubusercontent.com/28673129/40652949-530eeaa4-636c-11e8-9f8b-4d9a5eb49466.png)
And a normal ignored file is like this
![deepinscreenshot_select-area_20180529181637](https://user-images.githubusercontent.com/28673129/40653085-a080b9fc-636c-11e8-87b0-511a06791b1b.png)
Thanks.

**Comment by jrieken** [comment]
Ok, closing as question then. There is some un-intuitive behaviour with git and editing gitignore files after the fact.
