### ISSUE TITLE
Debugging .NET Core C# code using Console: "The handle is invalid"

### ISSUE THREAD

**Issue by kierenj** [Microsoft/vscode#50262]
Issue Type: <b>Bug</b>

Run the following C# code (.NET Core) under the debugger:

`var row = Console.CursorTop;`

Receive the exception:

```c#
Exception has occurred: CLR/System.IO.IOException
Exception thrown: 'System.IO.IOException' in System.Console.dll: 'The handle is invalid'
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_CursorTop()
```

This only happens when using the VS Code debug console (when debugging).

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.69GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-new-file|dku|4.0.2
docomment|k--|0.1.0
azure-account|ms-|0.4.0
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
vscode-docker|Pet|0.0.27

</details>

**Comment by kierenj** [comment]
Ok, I immediately then thought to check launch.json and found `console` setting.

Using `externalTerminal` for that prop fixes this.

Is there anything that could be done to make it more obvious/easier/the internal VS code debug console  work with it?  Running in the integrated terminal (using powershell in VS Code) works fine..

**Comment by roblourens** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2336
