### ISSUE TITLE
Extension API: Get relative position of cursor in viewport

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#50264]
Issue Type: <b>Feature Request</b>

One of *the* most-reported issue with VSCodeVim is the cursor is in incorrect position following an editorScroll (https://github.com/VSCodeVim/Vim/issues/1348). For VIM scroll commands such as <kbd>ctrl</kbd>+<kbd>d</kbd>, the VSCodeVim extension uses the `editorScroll` command to scroll the editor the appropriate direction. However, the `editorScroll` command moves the cursor to the top/bottom of the viewport whereas for VIM, the cursor should main at the same relative location in the viewport. (References: http://vimdoc.sourceforge.net/htmldoc/scroll.html#CTRL-D)

It'd be great to add this ability in the existing `editorScroll` command or add a new API to ascertain the current position in the viewPort (e.g. 10 lines from the top). Once we have this information, the extension can call `cursorMove` with `viewPortTop`/`viewPortBottom` to move the cursor appropriately. 

Repro: 
* Add the following keybindings.json:
```
    {
        "key": "ctrl+f",
        "command": "editorScroll",
        "when": "editorTextFocus",
        "args": {
            "to": "down",
            "value": 1,
            "by": "page",
            "revealCursor": true
        }
    }
```
* Notice that the cursor moves to the top of the viewPort following the editorScroll.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by rebornix** [comment]
@jpoon we added a new property `visibleRanges` to `TextEditor` a couple of iterations ago, from which you can know which lines are visible. So to make `Ctrl+D` work as expected, the only thing we need to do is comparing the cursor position with first visible line, and apply the line offset after `editorScroll` is executed.

Current VSCodeVim behavior:

![ctrl-d-old](https://user-images.githubusercontent.com/876920/41138984-beea0a90-6a99-11e8-9c77-adadc8efea86.gif)

Apply the line offset after scrolling

![ctrl-d-new](https://user-images.githubusercontent.com/876920/41138987-c69e9b70-6a99-11e8-8fe1-fc76f16063f7.gif)

The code change is also pretty simple (I didn't take care selection or multi cursor in below code)

```js
    let lineOffset;
    let editor = vscode.window.activeTextEditor;
    if (editor && editor.visibleRanges && editor.visibleRanges.length) {
      let firstLine = editor.visibleRanges[0].start.line;
      let currentSelectionLine = editor.selection.start.line;
      lineOffset = currentSelectionLine - firstLine;
    }

    let timesToRepeat = vimState.recordedState.count || 1;

    vimState.postponedCodeViewChanges.push({
      command: 'editorScroll',
      args: { ... }
    }

    if (lineOffset) {
      vimState.postponedCodeViewChanges.push({
        command: 'cursorMove',
        args: {
          to: 'down',
          select: vimState.currentMode !== ModeName.Normal,
          by: 'line',
          value: lineOffset,
        },
      });
    }
```

Let me know if I miss anything and I can file a PR.

**Comment by jpoon** [comment]
@rebornix sounds like that'll work! as you already have the code, please file the PR!

**Comment by rebornix** [comment]
I think this one is already fixed.
