### ISSUE TITLE
[emmet] adopt language id change 'jade' to 'pug'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50268]
In Microsoft/vscode#50086 I switched to a changed the language id of `jade` to `pug`.

The emmet code has still some references to 'jade' that might have to be updated.

**Comment by aeschli** [comment]
I reverted the language id change, too many external extensions depend on the `jade` id

**Comment by octref** [comment]
Can't we have both jade and pug? Currently this is very confusing, a language `jade` lives under `extensions/pug`.

I would want two languages, `extensions/jade` and `extensions/pug`, contributing the same language under different names.

**Comment by aeschli** [comment]
Two language ids just make things worse for the user experience. There are plenty of extensions that make contributions (e.g. snippets, formatters, previews) for 'jade'. There are also user snippets and language specific user settings that use the language id.

To do this properly, we need to introduce a new `languageIdAlias` property on our language contribution point. The `jade` language extension would define `"languageIdAlias": "pug"`.
All contribution point handlers that deal with language ids and all language feature registries would have to be updated to merge contributions to the two languages.

I'd only start that work if we get the more request for other languages as well.
