### ISSUE TITLE
Help - IronPytho

### ISSUE THREAD

**Issue by wta12** [Microsoft/vscode#50267]
- VSCode Version: 1.23.1
- OS Version: Window 10 Education x64

Steps to Reproduce:
"type": "python",
                "request": "launch",
                "name": "Python35",
                "program": "${file}",
                "cwd": "${fileDirname}",
                "showDebuggerOutput": true
1.  i run debug with shown configuration and get this cmd:
G:\PyRevitRun>cd g:\PyRevitRun && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && python "C:\Users\User\.vscode\extensions\ms-python.python-2018.4.0\pythonFiles\PythonTools\visualstudio_py_launcher.py" g:\UserWork_Folder\Revit_2017\PyRevit\PyRevitRun 54329 34806ad9-833a-4524-8cd6-18ca4aa74f14 RedirectOutput,RedirectOutput g:\Work_Folder\Revit_2017\PyRevit\PyRevitRun\pyWinUI.py "
2. VS code auto moves to CMD Terminal Tab - i want to keep at debug console for better viewing - is there any setting for auto cleaning at CMD Terminal Tab every time i run debug cmd

Does this issue occur when all extensions are disabled?: No
Thanks

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-python#1726
