### ISSUE TITLE
Opening specific WSL distro in integrated terminal in project folder, instead of WSL home folder.

### ISSUE THREAD

**Issue by metalim** [Microsoft/vscode#50265]
Not sure why [#32717](https://github.com/Microsoft/vscode/issues/32717) was closed and locked without solution, but here's what I found from `ubuntu1804 /?`:

```
Launches or configures a Linux distribution.

Usage:
    <no args>
        Launches the user's default shell in the user's home directory.
...
    run <command line>
        Run the provided command line in the current working directory. If no
        command line is provided, the default shell is launched.
```

Or, in other words:
`ubuntu1804` or `<other-WSL-name>` - will launch *specific* distro (Ubuntu 18.04 in this case) shell in WSL home folder
**`ubuntu1804 run bash` or `<other-WSL-name> run bash` - will launch *specific* distro bash in current (project) folder**
And of course the old way: `bash` or `wsl` - will launch ***default*** WSL distro shell in current (project) folder. Can be selected with `wslconfig /s <distro-name>`

To conclude: to run specific (non-default) WSL distro in integrated terminal, in project folder, you need following in your VSCode settings:
```Javascript
    "terminal.integrated.shell.windows": "ubuntu.exe", // or "<other-distro-name>.exe"
    "terminal.integrated.shellArgs.windows": ["run", "bash"], // or just ["run"] for newer distros
```
and leave `terminal.integrated.cwd` empty.

**Comment by Tyriar** [comment]
Thanks, unlocked/opened the issue.

**Comment by ilkersigirci** [comment]
I tried this  both on Ubuntu and Ubuntu1804 apps on windows store. Unfortunately, I still can't make integrated terminal to open cwd

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/vscode/issues/32717#issuecomment-391089327
