### ISSUE TITLE
Content changes when undo is performed after changing git branch on same file.

### ISSUE THREAD

**Issue by abhishekp1996** [Microsoft/vscode#50278]
- VSCode Version: 1.23.1
- OS Version: Linux 16.04 LTS

Steps to Reproduce:

1. Edit a file, then commit and change branch.
2. Do a undo (Ctrl + Z), the code changes and git shows new changes

Does this issue occur when all extensions are disabled?: N/A

I don't if this is a issue, but undo history should be reset after changing branch. I edited a file on another branch and commited and changed branch, and in the new branch I pressed Ctrl + Z, I saw git marking new changes.

Maybe this could be an issue for people new to VS Code.

**Comment by joaomoreno** [comment]
> but undo history should be reset after changing branch

I have do disagree on this. Undo, which is related to the text buffer in memory, has nothing to do with SCM, which is related to files on disk.
