### ISSUE TITLE
Applying js/ts quick fix all code actions on save

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#50275]
I want to define a keyboard shortcut for the "remove all unused imports" code action. However, I can't find documentation for the different `kind`s that can be used with the [`editor.action.codeAction` command](https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions).

I also want to run the "remove all unused imports" code action on save. However, it's not clear what code actions can be used with the [`editor.codeActionsOnSave` setting](https://code.visualstudio.com/updates/v1_23#_run-code-actions-on-save). Again, I can't find documentation on this.

Is this possible? If so, could we add documentation for this?

**Comment by mjbvz** [comment]
It's up to you. The kinds we pre-define, such as `Refactor` or `SourceOrganizeImports`, are used to implement a few UI elements like the refactoring menu but they are just suggested starting points. You can tack on whatever more specific scopes you want to these base kinds. Just make sure they are documented if you intend people to create keybindings for them

`editor.action.codeAction` takes any kind

 `editor.codeActionsOnSave` requires a `source.*` action since it applies to the entire file

I'll add notes on where the various base kinds are used to the `d.ts`

**Comment by OliverJAsh** [comment]
Thanks for improving the code comments. I'm still not sure I understand how to achieve my goal with regards to the "remove all unused imports" code action. AFAIK, this code action is contributed to VSCode by TypeScript, so I would expect kinds/commands to be provided out of the box?

**Comment by mjbvz** [comment]
We use `SourceOrganizeImports` for this

**Comment by OliverJAsh** [comment]
AFAICS, `SourceOrganizeImports` orders imports as well as removes unused imports, whereas I only want to remove unused imports.

My understanding was that all options that appear in the context menu (screenshot below) were their own code action kind/commands.

This is the specific code action I want to perform, both as a keyboard shortcut and on save:

![image](https://user-images.githubusercontent.com/921609/40449346-2449adbc-5ed0-11e8-8edc-aab083f17b65.png)

I've got this far with the keyboard shortcut:

``` json
    {
        "key": "cmd+shift+r",
        "command": "editor.action.codeAction",
        "args": {
          "kind": "source.organizeImports",
          "apply": "never"
        }
    }
```

However, this doesn't provide the option I'm looking for. When I use this shortcut:

![image](https://user-images.githubusercontent.com/921609/40449433-5559cb76-5ed0-11e8-9965-824b098c19c1.png)

Can you help me understand how I would achieve this, both as a keyboard shortcut and on save?

**Comment by mjbvz** [comment]
ok, I think you just want to  create your own code action kind then:

```js
const kind = vscode.CodeActionKind.Source.append('removeUnusedImports')
```

Then you can use this in keybindings:


```json
    {
        "key": "cmd+shift+r",
        "command": "editor.action.codeAction",
        "args": {
          "kind": "source.removeUnusedImports"
        }
    }
```

And on save:

```json
"editor.codeActionsOnSave": [ 
     "source.removeUnusedImports"
]
```

**Comment by OliverJAsh** [comment]
Would I create this code action kind in an extension?

**Comment by mjbvz** [comment]
We've introduced the concept of a [`fix all` source action](https://code.visualstudio.com/updates/v1_32#_fix-all-source-actions). This action can be run on save and address multiple auto fixable problems in a file. The tslint extension for example uses this action to fix all autofixable problems in TS files

Using a fix all action, an extension can now run specific quick fixes such as `remove all unused imports` on save. Closing this as extension candidate. Let me know if there's anything blocking you from writing an extension that does this

**Comment by OliverJAsh** [comment]
@mjbvz I think that only closes half of this issue. In my original post I also mentioned the ability to assign a keyboard shortcut:

> I want to define a keyboard shortcut for the "remove all unused imports" code action.

Unless I'm missing something, I don't think this is currently possible?
