### ISSUE TITLE
字体显示不出来

### ISSUE THREAD

**Issue by HuXiaoTu** [Microsoft/vscode#50270]
Issue Type: <b>Bug</b>

打开命令行 ，关联bash 输入git指令，当进行到commit - m ‘输入中文时’，  git指令消失不见 但回车后能显示与执行 ，只是输入时无法正常显示

VS Code version: Code - Insiders 1.24.0-insider (a521c01d56ec7f07bea2471880f28a77f37983af, 2018-05-21T05:18:01.058Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|7.80GB (2.96GB free)|
|Process Argv|E:\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.4
vsc-view-in-browser|dai|1.0.0
vscode-eslint|dba|1.4.9
vscode-language-pack-zh-hans|MS-|1.23.5
sublime-keybindings|ms-|4.0.0
vetur|oct|0.12.3
markdown-pdf|yza|1.2.0

</details>

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by HuXiaoTu** [comment]
This is my settings.json file. Thanks~

发送自 Windows 10 版邮件应用

发件人: Daniel Imms
发送时间: 2018年5月22日 21:20
收件人: Microsoft/vscode
抄送: HuXiaoTu; Author
主题: Re: [Microsoft/vscode] 字体显示不出来 (#50270)

Can you share your settings.json file?

**Comment by Tyriar** [comment]
Email attachments don't work in replies on GitHub, you'll need to paste in the contents into your reply or go to the web ui.

**Comment by HuXiaoTu** [comment]
`{
	// Defines VSCode's display language.
	// See https://go.microsoft.com/fwlink/?LinkId=761051 for a list of supported languages.
	// Changing the value requires restarting VSCode.
	"locale":"zh-CN"
}`
Why my vscode is in English after the update？

**Comment by Tyriar** [comment]
@HuXiaoTu that's your locale.json, not settings.json.
