### ISSUE TITLE
source.organizeImports must not remove empty line between import

### ISSUE THREAD

**Issue by nikolay-borzov** [Microsoft/vscode#50277]
Usually imports are organized in groups separated by empty line (e.g. node packages, services, components). I think that `organizeImports` should respect existing groups and perform organizing within each group.

- VSCode Version: 1.23.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Set user settings:
```
"editor.formatOnSave": true,
"editor.codeActionsOnSave": {
  source.organizeImports": true
}
```
2. Create `.ts` file
```
import path from 'path'

import fs from 'fs'

const currentDir = path.resolve(__dirname)
const data = fs.readdirSync(currentDir)
```

3. Press `Ctrl+S`

4. Result:
```
import fs from 'fs'
import path from 'path'

const currentDir = path.resolve(__dirname)
const data = fs.readdirSync(currentDir)
```

Does this issue occur when all extensions are disabled?: Yes (Disabled TSLint and Prettier)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24324
