### ISSUE TITLE
Tasks: Terminate task command: terminate a java task running in WSL does not actually kill it.

### ISSUE THREAD

**Issue by khe817** [Microsoft/vscode#50287]
Issue with command: F1 > Tasks: Terminate task: terminating a java task running in Windows Subsystem for Linux (WSL) does not actually kill it.

The terminal the java task is running in is closed with no error. But the task itself is still running astray if I look into the Task manager window. This issue does not happen when I run other tasks in WSL (e.g. `ping google.com`)

## How to reproduce:

- Set up integrated terminal to use WSL:

```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe",
```
- Download a sample Spring Boot project. E.g. https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-web-static 

- Set up task to run a Spring Boot project :

```json
{
    "label": "build & run",
    "type": "shell",
    "command": "mvn spring-boot:run",
    "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": true,
        "panel": "shared"
    },
    "isBackground": true
}
```

- Run the task. See in windows Task Manager a process named "java" appears.

- Terminal the task using the command: F1 > Tasks: Terminate Task

- The terminal inside VSCode is closed. But the process "java" is still there in Task Manager, and the java Tomcat server is still up (trying ping it to test: `$ curl localhost:8080/`).

### System info:

CPUs | Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)
-- | --
GPU Status | 2d_canvas: enabled, flash_3d: enabled, flash_stage3d: enabled, flash_stage3d_baseline: enabled, gpu_compositing: enabled, multiple_raster_threads: enabled, _onnative_gpu_memory_buffers: disabled, _softwarerasterization: unavailable, _softwarevideo_decode: enabled, video_encode: enabled, vpx_decode: enabled, webgl: enabled, webgl2: enabled
Memory (System) | 31.92GB (21.53GB free)
Process Argv | C:\Program Files\Microsoft VS Code\Code.exe
Screen Reader | no
VM | 0%

### Installed extensions:

Extension | Author (truncated) | Version
-- | -- | --
better-whitespace | chm | 1.0.1
jshint | dba | 0.10.18
FreeMarker | dco | 0.0.9
gitlens | eam | 8.3.2
vscode-html-css | ecm | 0.2.0
triggertaskonsave | Gru | 0.1.6
vscode-gitk | how | 1.3.2
thymeleaf | juh | 1.0.1
ping-endpoint | khe | 0.0.3
vscode-spring-boot | Piv | 0.2.1
java | red | 0.25.0
vscode-icons | rob | 7.23.0
trailing-spaces | sha | 0.2.11
shell-launcher | Tyr | 0.1.6
vscode-java-debug | vsc | 0.9.0

**Comment by khe817** [comment]
When I run the command directly in the integrated terminal WSL, I can't use the command `F1 > Tasks: Terminate Task` to end it. However, I can terminate the running process by sending `Ctrl + C` to the terminal. That is how I have been ending tasks, instead of using the command  `F1 > Tasks: Terminate Task`.

**Comment by DarthSpock** [comment]
I should mention a second work-around here. In build 17134 you can kill tasks running from WSL in TaskManager including `init`, which if you're killing the console, would be a safe bet to go with. If you're already running this build, I also recommend switching from bash.exe to wsl.exe.

**Comment by khe817** [comment]
@DarthSpock  Upgrading windows to build 17134 or higher fixed the issue for me.

Thank you very much for your help!

**Comment by DarthSpock** [comment]
Probably should be a note made in documentation for features of build 17134 that resolve issues with VS Code such as this one. Sounds like your original OP 

> F1 > Tasks: Terminate task:

relied upon the TaskManager feature in the background if you successfully ran that scenario.
