### ISSUE TITLE
Feature Request: Create temp file with a short cut and open in browser option when you right click on file

### ISSUE THREAD

**Issue by ragar005** [Microsoft/vscode#50289]
Lets say you want to test some html or javascript code and don't want to save the file in the disk.
we need to have a short cut to save a temp file and create a html file and also right click on the file to open in a browser.
I see an extension to create tmp file by jgoday but it would be cool if i can right click on the file to see an option to open in browser.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-application

**Comment by ragar005** [comment]
Cool!... Thanks
