### ISSUE TITLE
JavaScript formatting issue (improper indent-level in output)

### ISSUE THREAD

**Issue by Rua-Yuki** [Microsoft/vscode#50284]
- VSCode Version: 1.23.1
- OS Version: macOS 10.13.3

For the longest time (at least 6 months), there's been an issue with formatting JavaScript source files in VS Code, where the indent levels within the output are exaggerated, resulting in ESLint complaining.

The issue surfaces when calling a method where at least two parameters are object literals which are defined over multiple lines.

Take the following code for example:

```js
Whatever.update({
  id: 'asdf'
}, {
  someValue: 1
});
```

Most people would consider the code above to be all great, without any need for a change in formatting.

Unfortunately... upon using VS Code's formatter (⇧⌥F here), a difference in opinion is shown, with the code instead being changed to:

```js
Whatever.update({
  id: 'asdf'
}, {
    someValue: 1
  });
```

The expected behaviour is that the code is not changed as is above, as doing so totally violates any sane or commonly accepted formatting standards.

**Additional notes:**

- This does not seem to be an issue with [js-beautify](https://github.com/beautify-web/js-beautify)–at least not when directly testing against the current version (is VS Code using some funky config?).

- This issue affects both Windows and macOS, and has been present for at least 6 months or so.

- This issue does occur even while all extensions are disabled. 

- The surrounding code seems to have no effect on provoking or preventing this behaviour. This bug shows both when the problem code exists in its own file and when multiple levels deep in other code.

- The botched indenting will continue for anything chained against the method call, resulting in error-squiggle (wavy underlines) madness from ESLint when using promises, or otherwise chaining.

**Comment by Rua-Yuki** [comment]
To elaborate on the following phrase...
> The issue surfaces when calling a method where at least two parameters are object literals which are defined over multiple lines.

What is meant by this is any case where at least two parameters are specified like so (> 1 line):
```js
{
  key: 'value'
}
```
as opposed to (1 line/"inline"):
```js
{ key: 'value' }
```

The terminal and opening braces for each object need not begin on the same line. Additionally, there may be parameters of any type between the offending definitions, including inline objects–the indentation issue will still present itself.

**Comment by mjbvz** [comment]
Thank. Tracked by https://github.com/Microsoft/TypeScript/issues/8644

Closing as upstream
