### ISSUE TITLE
Debugger does not work with python code found in Google Drive - MS Code version 1.23.1

### ISSUE THREAD

**Issue by Manigrid** [Microsoft/vscode#50290]
Debugger does not work with python code found in Google Drive - MS Code version 1.23.1

- VSCode Version: 1.23.1
- OS Version: Windows 10.

Steps to Reproduce:

1. Put hello.py in google drive (mine is set to g:) - 
2. add breakpoints to any line. 
3 run debugger

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
What happens after you run the debugger? Please include more details besides "it doesn't work". I'm moving this to the vscode-python repo.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-python#1743
