### ISSUE TITLE
.js syntax highlighting not working

### ISSUE THREAD

**Issue by alexlamsl** [Microsoft/vscode#50293]
Issue Type: <b>Bug</b>

- download https://github.com/mishoo/UglifyJS2/blob/master/test/compress/evaluate.js
- open it in VSCode
- observe that syntax highlighting is mostly dysfunctional

It works without a glitch a few versions ago.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

Extensions: none

**Comment by alexlamsl** [comment]
Thanks @mjbvz :+1:

**Comment by tomwang1013** [comment]
still not working for some file

**Comment by mjbvz** [comment]
@tomwang1013 Open a new issue. Please include the source code as text of all screenshots
