### ISSUE TITLE
Outline not useful on typical Ember code

### ISSUE THREAD

**Issue by gnapse** [Microsoft/vscode#50297]
- VSCode Version: 1.23.1
- OS Version: macOS High Sierra

**Steps to Reproduce**

1. Open a file containing [declarations of Ember classes and/or object instances](https://guides.emberjs.com/v3.1.0/object-model/classes-and-instances/).
2. Open the outline sidebar.

**Actual results:** The outline does not include the members of the Ember classes declared in the file.
**Expected results:** The outline should include the Ember classes declared in the file, as well as their members nested under each.

Does this issue occur when all extensions are disabled?: Yes

For instance, for a code like this:

```javascript
import { computed } from '@ember/object';
import Component from '@ember/component';

export default Component.extend({
  tagName: 'li',
  fullName: computed('item.{firstName,lastName}', function() {
    const { firstName, lastName } = this.get('item').getProperties('firstName', 'lastName');
    return `${firstName} ${lastName}`;
  }),
  actions: {
    onButtonClick() {
      // do something
    },
  }
});
```

I'd expect something like this in the outline view:

```
Component.extend
    tagName
    fullName
    actions
        onButtonClick
```

I'm not sure if these issues specific to support for a certain framework way of doing things makes sense, or are to be covered by plugins that add support to the editor for that framework. However, in this case I do not see anything special going on from a js-language POV. Shouldn't the outline view consider this object being passed to `Component.extend` and its properties? Though I understand that if it did this for any object literal in a source file, it could get messy and unusable too. Thoughts?

**Comment by mjbvz** [comment]
This is out of scope for our built-in support. We have no knowledge that the object literal passed to `Component.extend` is conceptually a class, and showing all object literal keys in the object outline would be noisy. The outline works  fine if you use real classes

An ember extension could implement this feature however
