### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'setValue' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5029]
Issue Id: <b>dde50080-636f-cf99-9146-8947241dd071</b><br /><br />*Versions* <br />- 0.10.13-insider<br />-  17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c<br />*Stack* <br />TypeError: Cannot read property 'setValue' of undefined<br />[/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L158:37 (setValue)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L158:37 (setValue))<br />[/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L116:15 (setContext)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L116:15 (setContext))<br />[/vs/editor/common/commonCodeEditor.ts#L674:19 (set)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/common/commonCodeEditor.ts#L674:19 (set))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#L399:20 (call)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/browser/widget/codeEditorWidget.ts#L399:20 (call))<br />[/vs/editor/common/commonCodeEditor.ts#L230:7 (_attachModel)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/common/commonCodeEditor.ts#L230:7 (_attachModel))<br />[/vs/editor/contrib/referenceSearch/browser/referenceSearchWidget.ts#L592:17 (setModel)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/editor/contrib/referenceSearch/browser/referenceSearchWidget.ts#L592:17 (setModel))<br />[/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1448:0 (call)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/base/common/winjs.base.raw.js#L1448:0 (call))<br />[/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/43ff6af3d4564f59196caa9be4897fc33c15f24c/src/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />

**Comment by alexandrudima** [comment]
Cannot reproduce
