### ISSUE TITLE
In new settings UI, `search.location` shows as complex setting instead of dropdown

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#50295]
Issue Type: <b>Bug</b>

I wanted to toggle the search view location and was surprised that in the new settings UI, `Edit in settings.json` is shown instead of a dropdown with `sidebar` and `panel` options. Similar settings like `Workbench.Panel: Default Location` show as a dropdown, so I'm not sure what's going on with `search.location`. 

VS Code version: Code - Insiders 1.24.0-insider (dbd7f09189947497c77755d0738c115d689c680f, 2018-05-22T05:11:02.913Z)
OS version: Darwin x64 17.4.0

**Comment by roblourens** [comment]
Good catch, thanks
