### ISSUE TITLE
debug console scrollable horizontally, just like code 

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#503]
_From @joeblew99 on November 23, 2015 15:11_

would make debugging much smoother is the debug console window was scrollable horizontally.
in a code window its nice that i can scroll easily to see long longs.

If there is a way to maybe force the debug console window to flow onto the next line that would be also good.

_Copied from original issue: Microsoft/vscode-go#66_

**Comment by lukehoban** [comment]
Yes - one or both of these does seem necessary to make the debug console usable.

**Comment by joeblew99** [comment]
Thanks.
This ide is really nice to work in compared to the others I have tried for golang.

**Comment by isidorn** [comment]
We are reluctant to add horizontal scrolling as no other terminal / repl has this and would be strange.
Flowing text to the next line - word wrap is the way to go. We will look into this.

**Comment by joeblew99** [comment]
Certainly understand. Thanks for feedback.

**Comment by niedzielski** [comment]
If the debug console cannot be docked horizontally, is it possible to hide it / keep it minimized?

**Comment by isidorn** [comment]
Not at the moment, will be possible in the future.
