### ISSUE TITLE
Allow to rename untitled buffers

### ISSUE THREAD

**Issue by anothergituser** [Microsoft/vscode#50303]
Hello,
Can new and unsaved files be renamed? For when you just need a throw away buffer for what ever and there's no reason to save it. It's difficult to remember what you had in there when all are named Untitled-1, 2, 3
Thanks.

**Comment by Cryonis** [comment]
Is there any update to this feature? It would be immensely helpful for when you're dealing with a lot of scrap code.

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/37414
