### ISSUE TITLE
Cannot close a console if `code` is running

### ISSUE THREAD

**Issue by AnthonyMastrean** [microsoft/vscode#50308]
Issue Type: <b>Bug</b>

It appears that I cannot close a console if I launched `code` from that console and if Visual Studio Code is still running.

Steps to Reproduce:

1. Open a PowerShell console
2. Run `code .`
3. Type `exit` or click the X to close the PowerShell console
4. (Note it hangs!)
5. Wait a bit...
6. Now close Visual Studio Code
7. Watch the console close only _after_ Visual Studio Code exits!

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (3.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.29
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
vsliveshare|ms-|0.3.198
vscode-docker|Pet|0.0.27

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I think this is a powershell thing, it doesn't exit if its child processes don't or something?

**Comment by AnthonyMastrean** [comment]
But, code isn’t blocking the console. I can enter other commands and even launch other apps or more instances of code. 

Other editors don’t lock the console like this. There must be some kind of process start mode or something that effects this, right?

**Comment by rjmholt** [comment]
Some extra data points:

- When VSCode window is closed, the PowerShell window is closed
- If PowerShell runs `code` but does not open a new window (because one for the directory is already open) the issue does not occur

I suspect this is some window/UI/container handle ownership issue. Is there somewhere you could point me to to look at the code? It seems there maybe aren't so many people hitting this problem, but I have for the last 18 months and thought I should finally stick my hand up to look into it 😄

**Comment by DHowett-MSFT** [comment]
JFYI I apparently filed a copy of this at #66750 with a lot more info on why it's happening.

**Comment by DHowett-MSFT** [comment]
Er, I apparently did _not_ file that one. I just commented on it. Saturday morning isn't the right time for bug triage :smile:

**Comment by DHowett** [comment]
Typically, closing a bug won't fix warrants a comment about why not. 😄
