### ISSUE TITLE
Pasting on wrong line when copying entire line

### ISSUE THREAD

**Issue by Jtaks** [Microsoft/vscode#50307]
Issue Type: <b>Bug</b>

Expected: Line is pasted where cursor is currently located.

Actual: Line is pasted above cursor line.

Steps to reproduce:
1. `ctrl + c` or `ctrl + x` with no selection to copy/cut whole line
2. `ctrl + v`

![vsbug](https://user-images.githubusercontent.com/6249932/40391305-04062658-5dd5-11e8-81a8-2339d31f3a51.gif)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-41-generic

Extensions: none

**Comment by alexandrudima** [comment]
This is how the feature works. When copying without a selection, the entire line is copied to the clipboard and a mark is set. When pasting in such case, the pasted line gets inserted above the current line.
