### ISSUE TITLE
Find and Replace in current file: Regular Expressions

### ISSUE THREAD

**Issue by Agarwal-Nikhil** [Microsoft/vscode#50306]
- VSCode Version: 1.22
- OS Version: Ubuntu 18.04

This is find and replace issue in VS Code.

I want to find the following text in my Markdown file in VS Code:

```
## [](https://www.website.com/)Heading
```

and Replace with this text

```
## [Heading](https://www.website.com/)
```

So I use `## \[]\(.+?\)(.*)` to find the expressions. But to replace with the above expression I typed this `## [$1]\(.+?\)(.*)` but it doesn't works. How can I do this? Do regular expression doesn't work in replace?

**Comment by roblourens** [comment]
I think you want to do something like

`## \[](\(.+?\))(.*)`
`## [$2]$1`

Right? Otherwise I'm not sure what you're expecting to happen when you replace with `.*`.

**Comment by Agarwal-Nikhil** [comment]
Thanks!
