### ISSUE TITLE
Custom Block Comment Formatting/Better Comment Formatting

### ISSUE THREAD

**Issue by pzuraq** [microsoft/vscode#50301]
We've been using doc comments more and more in our code to automatically generate documentation, which is starting to be really productive. Tools like ESDoc and Typedoc are capable of statically analyzing the code and producing a ton of helpful docs. 

Our generator setup generally compiles the description in doc comments as Markdown, which makes writing examples super easy. Except, VSCode's comment blocks in Javascript interfere with this quite a lot, specifically the leading `*` characters on each line. There are two main ways it is problematic:

1. Copy pasting a snippet into a doc block comment does _not_ add leading `*`, which results in having to add an asterisk to each line. This can be very painful with large examples:

  ```js
  /**
   * this is an example function, here's how you use it
   * 
   * ```js
  //example.js
  foo();
   */
  ```

2. Tabbing does not tab relative to the doc comment block, but the overall document. This means that tab depth is off by one when writing examples in doc blocks, which results in really wonky indentation:

  ```js
  /**
   * this is an example function, here's how you use it
   * 
   * ```js
   * //example.js
   * foo({
   *  bar: 'baz'
   * });
   */
  ```

One solution here is to allow a way to customize block comments. We are currently using comments _without_ a preceding asterisk:

```js
/**
  this is an example function, here's how you use it
  
  ```js
  //example.js
  foo();
*/
```

This is good for the most part, but VSCode doesn't expect it and actively fights it to some extent. It'll insert asterisks whenever we try to start a comment block, and if you copy paste some code after a block it'll mess up indentation (likely because it thinks that the closing `*/` represents the indentation level, but it's set back one space). The below example was a real world attempt to copy-paste the function and the comment:

```js
    /**
      Helper function to click with options like the meta key and ctrl key set

      @param {Object} options - click event options
    */
   async clickWith(options) {
    await click(findElement(this), options);
  },
```

Another option would be to fix the comment blocks so the editor can handle them, allowing users to type markdown in line at proper indentation levels, and copy paste with preceding asterisks added. I think both options would be great wins for DX, especially since markdown helps with code examples in comments so much.

**Comment by paulxtiseo** [comment]
For JavaScript, the "Document This" extension does a good job of formatting the appropriate comment block.

However, it would be nice if VSCode could collapse those kinds of blocks natively.

**Comment by pzuraq** [comment]
I tried out the Document This extension, but it doesn't appear to address the issues I outlined above. It's still very difficult to embed markdown within a doc comment and have indentation work as expected, and indentation on copy/paste is still messed up when using doc comments without a leading asterisk before each line.

**Comment by rishacha** [comment]
Is there anyone working on this? Can I try and work on it? It seems like a problem I would like to fix because I face it everyday.

**Comment by rishacha** [comment]
Actually [#20044](https://github.com/Microsoft/vscode/issues/20044) addresses this issue. I simply disabled all extensions for comments and it worked

**Comment by IanVS** [comment]
Regarding https://github.com/Microsoft/vscode/issues/50301#issuecomment-492150341, I tried running with extensions disabled, and vscode still does not add leading asterisks correctly.  `Document This` also does not add leading asterisks when making a new line.  I'm using VSCode 1.40, FWIW.

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847 and https://github.com/microsoft/vscode/issues/34621).
