### ISSUE TITLE
Allow to apply zooming only to the editor

### ISSUE THREAD

**Issue by tsakowi** [microsoft/vscode#50305]
When zooming should only be applied to the written code and not over the entire editor interface, the left panel and its icons become very small or very large when using this feature, in other editors the same thing does not happen. Please fix it. Thank you.

Al hacer zoom solo debería aplicarse sobre el código escrito y no sobre toda la interfaz del editor, el panel izquierdo y sus iconos se vuelven muy pequeño o muy grande al utilizar esta característica, en otros editores no sucede lo mismo. Favor de arreglarlo. Gracias

**Comment by f-breidenstein** [comment]
This is a duplicate of #48019

**Comment by AKTECHNICAL** [comment]
Yes same issue
