### ISSUE TITLE
VSCode not scrolling horizontally on hitting Home/End key for lines with more than 10,000 characters

### ISSUE THREAD

**Issue by Avinm** [microsoft/vscode#50304]
- VSCode Version: 1.23.1
- OS Version: Windows 7, OSX

Steps To Reproduce:

1. Open a new file
3. Add a single line with **exactly 10000** characters (word wrap: off)
4. Hit Home Key, VSCode will scroll to the beginning, following the cursor
5. Hit End Key, VScode will scroll to the end, following the cursor.
6. Add 1 or more characters,
7. Press Home/End keys, cursor moves correctly but VSCode does not scroll along with the cursor.

Expected Result:
VSCode should scroll horizontally in sync with the cursor.

**Comment by alexandrudima** [comment]
The resolution is that revealing will work, but the cursor will not be painted. That is because we want to signal that the cursor is in the not painted region...

**Comment by Avinm** [comment]
Isn't it the normal behavior that the cursor also moves to the end?
