### ISSUE TITLE
[Loc] Request to add Arabic (generic) language to Transifex VS Code project

### ISSUE THREAD

**Issue by chadidi** [microsoft/vscode#50316]
This the official language in 27 countries should be added ASAP.
I am surprised that no one request it yet, this is my transfix profile:
https://www.transifex.com/user/profile/chadidi97/ 
please put yours in the comment below if you wanna contribute 

> At least 3 people needed to open the project in transifex

Thanks,
Abdellah Chadidi

**Comment by danyeh** [comment]
VS Code itself does not have plan to enable bi-di support yet. So we won't enable any bi-di language in Transifex at this moment to avoid waste community member's time.
We record this message in [request language wiki](https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project). See 3rd paragraph.

**Comment by akqira** [comment]
I will contribute if bi-di is enabled. 
Thanks
Abdelkader KEBIR

**Comment by atefBB** [comment]
@chadidi @akqira Look like we should investigate on adding arabic UI language! 
Happy to contibute.

**Comment by chadidi** [comment]
Hi everyone,

Just referencing all the issues about:

1. Arabic Translation
  #47826 #48389 #49667 #51066
  

> note for people that opened the issues above: Its better to translate the Arabic (generic) first cause more people use it.

2. RTL support
  #45180 #28571 #14019 #11770

**Comment by Kalmuraee** [comment]
I'm interested in contributing whenever supporting bi-directional languages is on the radar.
https://www.transifex.com/user/profile/KAlmuraee/

Best Regards,
Khalid Almuraee

**Comment by saibimajdi** [comment]
Interested in contributing.

**Comment by mahrousfci** [comment]
I am interested also for Arabic language, I think there is no a real need for supporting dialects, and the basic official is sufficient

**Comment by danyeh** [comment]
We don't have plan to enable additional language for VSCode in MLCP in near term. Hence close the request here.
New request should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)
