### ISSUE TITLE
Avoiding Exiting Bash - Exits Terminal 

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#50317]
I have `"terminal.integrated.shell.windows"` set to bash but when exiting bash within terminal; terminal closes. How can I set terminal not to close when simply exiting bash and when existing bash have it fall back to command ?

**Comment by Tyriar** [comment]
When you exit bash the terminal has no process to run a command in. Do you mean you want it to launch a new shell when you exit the last one or something?

**Comment by SheepDomination** [comment]
Instead of terminal closing when existing bash, for example.  I want it to switch to `command` or `powershell` rather then simply closing the terminal window / tab.

**Comment by Tyriar** [comment]
For easier launching of multiple shells I recommend using an extension:

- https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
- https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals
