### ISSUE TITLE
Add a complex command to open the command palette with a specific group

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode#50315]
I want to add a button to the editor title menu to help my users open the command palette with my specific group already typed in.

**Comment by bpasero** [comment]
That exists via the `workbench.action.quickOpen` command. E.g. as keybinding:

```json
{
	"key": "ctrl+0",
	"command": "workbench.action.quickOpen",
	"args": "test"
}
```

**Comment by ThadHouse** [comment]
That shows files with a specific prefix, not the command palette with a specific prefix. @bpasero

**Comment by ThadHouse** [comment]
Oh nevermind. I guess you just have to add `>` in front of that top open the palette.
