### ISSUE TITLE
Allow to place tabs at the bottom

### ISSUE THREAD

**Issue by rpavlovs** [Microsoft/vscode#50318]
In fullscreen mode on mac when I reach to change a tab, I keep accidentally pressing on the top edge of the screen. Which makes top bar slide down, completely covering the tabs :|

Would it be possible to have an option to move tabs to the bottom of the screen? This way I can have my dock on a side and never worry about over-reaching.

**Comment by nodgear** [comment]
Again in 2021, why is it silently marked as out-of-scope?

**Comment by federicom-scale** [comment]
This would be a really nice feature to have

**Comment by ralaul** [comment]
I'd prefer to have the tabs on the bottom as well, specially for my main office setup case, where one of my displays is rotated to portrait. I find it nice to not need to scroll in most files, having the tabs on the bottom would also make it easier on my neck. +1 on the feature request

**Comment by Pingear** [comment]
@rpavlovs 
@yuhr 
@nodgear 
@ralaul 
@federicom-scale

Hello to all)
Opened a [new issue](https://github.com/microsoft/vscode/issues/140674) on the same topic. The community has 60 days to vote on an issue. If he gets 20 votes, the developers will move him to the backlog.
So if you are still interested in this functionality, mark the new issue with a reaction.
