### ISSUE TITLE
Fails to read latest files contents if SSH connection terminates

### ISSUE THREAD

**Issue by d3x0r** [microsoft/vscode#50319]
Linux; CentOS (some version)
I connect to this server over ssh, and use X forwarding to use VS Code on the server.  The VS Code on reload reloads some previous state, from a long time ago; but never updates the current state of files open.  I assume if only saves on graceful exit?  
(Menu popups are not working with the current VS code version 
`code-stable-code_1.23.1-1525968403_amd64.tar.gz`) so I was going to say I can't say which version it is; but I found the download....

Maybe the current state could also be saved when a file is saved?

**Comment by bpasero** [comment]
@d3x0r when you close and reopen the file, does it then still show old state?

**Comment by d3x0r** [comment]
No; the last state correctly shows with VSCode is restarted (by using the X and relaunching).
It does not update if the SSH connection is terminated.   My ISP has intermittent blips of 30 seconds of non connection; and it's long enough to cause the ssh connection to terminate abruptly.

**Comment by bpasero** [comment]
We do not cache any state on our end for files that we open so I suspect this could be an issue between VSCode and the libraries we use for disk access.

**Comment by d3x0r** [comment]
not the contents; the files themselves - the list of currrently open files is what doesn't update

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by d3x0r** [comment]
I just kinda learned to live with it... 
I have arch, and recent Arch package is only a 4.x something electron...
other systems are ... inconvenient to update.
I actually started to think of it as a feature... always got at least something I wanted when I started, since it never saved the changes, it was always the point I did kindly close it.  *shrug*  kill -9 probably does it too
