### ISSUE TITLE
Selected info was not changed with conversion indent character.

### ISSUE THREAD

**Issue by fujitatakesh** [Microsoft/vscode#50313]
Reproduce steps below..
Step1:
  Open a source file with space indented.
Step2:
  Select a line with indented.
  And selected range info is displayed right side in taskbar.
Step3:
  Change space to tab.
Step4:
  Selected range info isn't changed before change indent character.

**Comment by weinand** [comment]
I can reproduce.

**Comment by rebornix** [comment]
Can you provide more details about how to reproduce? I tried files with spaces, tabs, mixed but can't reproduce.

![selected-indent](https://user-images.githubusercontent.com/876920/41069745-19d767dc-69a4-11e8-8dea-276d26f3c001.gif)

**Comment by fujitatakesh** [comment]
My environment (Mac OS) reproduced. I supposed it depends on an extension.
Can you remove extension and try it again?

**Comment by rebornix** [comment]
I didn't reproduce when running `code --disable-extensions`, can you try it as well and see if any of your local extensions make it happen?

**Comment by rebornix** [comment]
@fujitatakesh thanks, I can reproduce now

![selected-indent](https://user-images.githubusercontent.com/876920/41132528-913c0c06-6a76-11e8-8a4f-c63f63e7a1ab.gif)

**Comment by rebornix** [comment]
To verifiers:

* Make sure the selection start and end position doesn't change after the indentation conversion when you testing.
