### ISSUE TITLE
VSCoder insider will discard the containerName of SymbolInformation

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode#50321]
- VSCode Version: The latest insider version
- OS Version: Windows 10 18.04

Steps to Reproduce:

1. Install this extension in insider version
2. Show the outline from the explorer context menu
3. Open the project from here: https://github.com/spring-projects/spring-petclinic
4. Open the PetApplication.java file 

Expected: 

- From the language server side, the containerName of SymbolInformation is returned in the debug scenario.  But is is not available on the client side. 
- The issue doesn't appear on the VSCode stable 1.23.1

**Comment by DanTup** [comment]
I just came to report the same thing. There's something really weird about it, it seems to work for some code but not others... I have two document symbol providers, a "legacy" one that I use for old versions of the Dart SDK and a new one for the new versions (this one functions as both a Workspace and Document symbol provider). The returned `SymbolInformations` look the same to me, yet the newer one is losing the containerNames and the legacy one is not (testing both in insiders). It's not just lost in the UI, if you call `vscode.executeDocumentSymbolProvider` and examine the results it's not on the objects there either.

**Comment by DanTup** [comment]
Ok, this one's weird. I return two items with `name: name, containerName: containerName` and they display like this:

![screen shot 2018-05-23 at 8 20 23 am](https://user-images.githubusercontent.com/1078012/40409283-40aa4584-5e62-11e8-85ff-8354d5789e9a.png)
<img width="777" alt="screen shot 2018-05-23 at 8 20 30 am" src="https://user-images.githubusercontent.com/1078012/40409284-40c017e2-5e62-11e8-9b9a-9cf019a49a01.png">

**Comment by DanTup** [comment]
@jrieken - I wonder if this is related to the hierarchical symbol changes? I haven't updated for that yet; this is the behaviour running the current live version of the extension (so what users would get if insiders released as-is).

**Comment by jrieken** [comment]
True story. Somehow lost in translation...

**Comment by sbatten** [comment]
Using @aeschli 's example, I am still seeing the flat outline.

**Comment by jrieken** [comment]
ping @sbatten

**Comment by DanTup** [comment]
FWIW, my integration tests for my symbol provider seem to be passing against Insiders now :-)

**Comment by jrieken** [comment]
Ok, closing based on @DanTup insights.

**Comment by sbatten** [comment]
maybe I'm misunderstanding what this should look like, but I thought the outline should  have class A as a parent of the method main and any other methods.

```
public class A {
	public static void main(String[] args) throws Exception {
	}

	public int run(){ return 0; }
}
```
![image](https://user-images.githubusercontent.com/6561887/40990516-f0a688ec-68a5-11e8-8e18-ddb7e95a5b15.png)

**Comment by DanTup** [comment]
@sbatten I think it should too, are you using an outdated Insiders build or could it be an issue with the language extension?

I just tried this manually again with my example from above and the `containerName`s that were previously missing are definitely coming through:

![screen shot 2018-06-05 at 6 07 00 pm](https://user-images.githubusercontent.com/1078012/40991353-733ddebe-68eb-11e8-9232-ea5248b799a0.png)

<img width="808" alt="screen shot 2018-06-05 at 6 07 05 pm" src="https://user-images.githubusercontent.com/1078012/40991361-7809239a-68eb-11e8-9cfb-3504c3ccd738.png">

**Comment by sbatten** [comment]
maybe its just an issue with the outline, container names do show in show symbols
![image](https://user-images.githubusercontent.com/6561887/40991705-77d0b524-68a9-11e8-8f23-58c7577119bd.png)

**Comment by DanTup** [comment]
Ah, I totally missed that your screenshot was outline. I haven't done much testing with that so it might have different issues.

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/50321#issuecomment-394790421

Yeah, that's the design. We show container names only in quick outline, not in the outline tree. The whole reason `containerName` exists is the fact that we have been using a flat list for symbols and they are meant to provide parent context. Since the tree has that by its nature we don't need it anymore.

**Comment by DanTup** [comment]
@jrieken Is the API for providing this data in a tree finalised, or does the outline currently try to make a tree based on `containerName`? Last time I checked, it seemed like I could enable the outline, but the API to update the provider was still being tweaked?

**Comment by jrieken** [comment]
Yeah, we finalise the API this month (see https://github.com/Microsoft/vscode/issues/34968) until then we synthesise trees based on range containment.

**Comment by DanTup** [comment]
Aha, that's what you're using - I wondered if it was based on container name, but the range makes much more sense! Thanks :)

**Comment by jrieken** [comment]
For reference (and pride): https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L54
