### ISSUE TITLE
open file from path not hapenning

### ISSUE THREAD

**Issue by pawarvijay** [Microsoft/vscode#50326]
- VSCode Version:1.23.1
- OS Version: MAC OS High sierra v 10.13.4

Steps to Reproduce:

1.create tank.js file , export it
2. create bazooka.js file , import import tank.js file and see you are able to open tank.js

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the file contents. How are you exporting and importing for example?

**Comment by pawarvijay** [comment]
# Code Sample
**Header.js**
```
import React, { Component } from 'react';
export class Header extends Component {
  render(){
   return <span>Yo Header</span>
 }
}

export default Header
```

**App.js**
```
import React, { Component } from 'react';
import Header from './Header';
export class App extends Component {
  render(){
    return <div></div>
  }
}
export default App;
```

so on` cmd + click` on './Header'; 
i am not able to navigate to header.js file
on ubuntu its working nicly

**Comment by mjbvz** [comment]
I cannot repo this in VS Code insiders. Can you please test in insiders with all extensions disabled.

Also, does your project have a `jsconfig.json`?

**Comment by mjbvz** [comment]
Please try creating a [jsconfig.json](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson) at the root of your project with the contents:

```
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by pawarvijay** [comment]
1 : no , it dosen't navigate
2 :  also tried by disabling all extensions
3 : also tried {
    "compilerOptions": {
        "target": "ES6"
    },
    "include": [
        "client/**/*","server/**/*"
    ]
}

**Comment by pawarvijay** [comment]
[its working in jan build 2018 version 1.20](https://code.visualstudio.com/updates/v1_20)

**Comment by pawarvijay** [comment]
@mjbvz 
Closing this issue

I think it my machine related problem .

i checked on other 2 mac machines with exact same mac & vs code version its working fine
