### ISSUE TITLE
Bad highlight of some js files using flow

### ISSUE THREAD

**Issue by imyzf** [Microsoft/vscode#50328]
- VSCode Version: 1.23.1
- OS Version: macOS 10.13.4

Most of the js files using flow are highlighted correctly, only some one like this Vue.js source code:
https://raw.githubusercontent.com/vuejs/vue/38d5459e109a83b4992168c673403503278ff3c1/src/core/vdom/create-element.js

![image](https://user-images.githubusercontent.com/8298849/40410364-32db6bc0-5ea0-11e8-9597-14568ec0a370.png)

Now the only solution is to install JavaScript Atom Grammar, but it would be better if the built-in JavaScript grammar could fix this. Thanks.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Our built-in js grammar doesn't support flow. Try installing the flow extension which provides its own grammar
