### ISSUE TITLE
[html] support style less content

### ISSUE THREAD

**Issue by kdong007** [Microsoft/vscode#50327]
- VSCode Version: Version 1.23.1 (1.23.1)
- OS Version: mac 10.13.4 (17E199)

Steps to Reproduce:

```
<style lang="less" type="text/less">
    .chats {
        padding: 30 px;
        .chat {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
    }
</style>
```
put this in a html file. editor complains about the syntax. The error tip indicates VSC is using css to parse the code. How do I tell the parser to parse less or do I need some plugin to do this?

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by aeschli** [comment]
We currently don't support less content in styles. The workaround is to disable css validation in HTML:
`"html.validate.styles": false`

**Comment by kdong007** [comment]
@aeschli  kkk thanks.
