### ISSUE TITLE
Settings: show affordance to expand as is done for notifications

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#50324]
When there is more text for a setting then the UI shows a ´...´ . 

![image](https://user-images.githubusercontent.com/172399/40407362-76bf8786-5e64-11e8-859e-206b773d4acb.png)

In addition, to the ´...´ the setting entry should also show an expand affordance on hover, same as it is done in the notifications, see the ´^´ on the right in the screenshot below.

![image](https://user-images.githubusercontent.com/172399/40407260-21122a64-5e64-11e8-9be7-74c10216ea88.png)

CCing @bpasero for input.

**Comment by roblourens** [comment]
Today we show

![image](https://user-images.githubusercontent.com/323878/40457498-a17c31b2-5eab-11e8-93a9-1d40abaaa38b.png)
