### ISSUE TITLE
var name disables autocomplete

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#50330]
- VSCode Version: 1.23
- OS Version: macOS

Very weird behavior.

```js
class Application {
  constructor() {
    this.cache = {};
  }
  log() {}
}

const name = new Application();
name. // no autocompletion for cache and log
```

If call my var `name` autocomplete disappears. But if I for e.g. call it `app` it works.

![image](https://user-images.githubusercontent.com/10441177/40412001-becd3562-5e7a-11e8-9df1-ac809fcc8f95.png)
![image](https://user-images.githubusercontent.com/10441177/40412013-c949eb3e-5e7a-11e8-9b28-703e52d85a4d.png)

**Comment by svipben** [comment]
Found another one problem. If I call my variable `length` it will give me these suggestions.

![image](https://user-images.githubusercontent.com/10441177/40412095-0568c05e-5e7b-11e8-8a91-4e46a2980d95.png)

**I believe there's something wrong with built-in methods and that's why this problem occurs. Because `name` and `length` are mostly native/built-in**

**Comment by svipben** [comment]
This happens with JavaScript and TypeScript.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24354
