### ISSUE TITLE
Scrolling a Markdown document eats 100% cpu, spawns empty cmd.exe processes, 

### ISSUE THREAD

**Issue by mzt** [Microsoft/vscode#5033]
- VSCode Version:
0.10.11

- OS Version:
Win 7 x64

Steps to Reproduce:

1. Create an md file and paste the following block multiple times so you can scroll the document:
```
## lorem ipsum
dolor sit amet

```
2. Hold down arrow and watch processes

![markdown-bug](https://cloud.githubusercontent.com/assets/16809885/14315700/475ef18a-fbff-11e5-86d1-f208c5fee245.png)

**Comment by bpasero** [comment]
@mzt wow weird, I cannot reproduce. Do you run with extensions?

Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions`

**Comment by mzt** [comment]
@bpasero My bad, it was the Instant Markdown extension.
