### ISSUE TITLE
Document what VariablePresentationHint does

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#50331]
I've tried searching the docs and GitHub, but I can't figure out what `VariablePresentationHint` values are supposed to do (except a `kind` of `virtual`). As far as I can tell, nothing changes in the UI.

Are these values just provided for future-proofing, or should they do something? I was looking for a way to make getters (which have executed code to be displayed) look slightly different to fields in my variables list.

**Comment by weinand** [comment]
"hints" are optional and every frontend is free to ignore them.

"VariablePresentationHint" are ignored by VS Code but honored by VS. If you want to see them in VS Code please file a feature request with details about what exactly VS Code should be implemented.
