### ISSUE TITLE
V1.23.1 takes up a lot of system resources

### ISSUE THREAD

**Issue by davidhopper2003** [Microsoft/vscode#50332]
Issue Type: <b>Bug</b>

I have been using VSCode to edit and build C++ projects under Ubuntu 16.04. Versions prior to V1.23.1 worked very well. But V1.23.1 version is very bad, long-term high-intensity CPU, consuming a lot of memory, and often being crashed. I don't know why such a poor version is released?

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 9, 8|
|Memory (System)|15.52GB (3.31GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.17.0
bazel-code|Dev|0.1.9
latex-workshop|Jam|5.5.0
vscode-language-pack-zh-hans|MS-|1.23.5
vscode-docker|Pet|0.0.27
cpp-snippets|aga|1.0.1
code-gnu-global|aus|0.2.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-eslint|dba|1.4.10
vsc-invoke|dch|0.0.5
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
vscode-great-icons|emm|2.1.32
vscode-pydev|fab|0.1.5
md2reader|gdr|0.8.0
easy-icons|jam|0.3.1
vscode-elm-jump|joe|0.0.1
jumpprotobuf|ldc|0.0.3
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
python|ms-|2018.4.0
cpptools|ms-|0.17.3
vs-keybindings|ms-|0.2.0
autodocstring|njp|0.2.1
proto|pet|0.0.2
elm|sbr|0.18.0
MDTools|sea|1.0.1
cmake|twx|0.0.17
cmake-tools|vec|0.11.1
jinja|who|0.0.8
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.4.0
vscode-proto3|zxh|0.2.1

</details>

**Comment by weinand** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by davidhopper2003** [comment]
![image](https://user-images.githubusercontent.com/31435476/40416881-0862c1f2-5eb1-11e8-956f-aea7676e95ff.png)

**Comment by davidhopper2003** [comment]
@weinand OK, I'll follow your advice. Thanks a lot.

**Comment by davidhopper2003** [comment]
![image](https://user-images.githubusercontent.com/31435476/40457933-c4a4031a-5f2b-11e8-989c-d81048929807.png)
![image](https://user-images.githubusercontent.com/31435476/40458283-d54ba842-5f2d-11e8-8942-d00e299cde1a.png)

**Comment by davidhopper2003** [comment]
@weinand Mircrosoft.VSCode.CPP.Extension.linux takes up a lot of CPU resources and Microsoft.VSCode.CPP.IntelliSense.Msvc.linux occupies a lot of memories.

**Comment by davidhopper2003** [comment]
@weinand  Versions prior to V1.23.1 worked very well and didn't take too much system resources at all.

**Comment by davidhopper2003** [comment]
@weinand I Furthermore, I can't often use current version to jump to the definition of a function and format the cpp code and these problems didn't occur in previous versions. 
.

**Comment by weinand** [comment]
Since all of your issues are related to the the cpp extension (which is not part of VS Code), I'll move this issue to their repository.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#2036
