### ISSUE TITLE
Tree is showing a same item multiple times

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#50336]
![kapture 2018-05-23 at 12 08 35](https://user-images.githubusercontent.com/10746682/40418255-1d142e8a-5e82-11e8-8838-553afa409a86.gif)

@joaomoreno 
I do not have general steps to reproduce... But I can consistently reproduce it with the docker extension. Let's investigate at my desk and see if we can find a easy way to reproduce it.

**Comment by Gruntfuggly** [comment]
I also found the same problem (#48274) - I believe it was caused by triggering too many `onDidChangeTreeData` events.
