### ISSUE TITLE
Support collapsing stack frames

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#50334]
Sometimes call stacks in the debugger contain a lot of frames from code that isn't the users (for example SDK code):

```text
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      HotRunner.validateReloadReport (package:flutter_tools/src/run_hot.dart:407)
#3      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:528)
#4      _rootRunUnary (dart:async/zone.dart:1128)
#5      _CustomZone.runUnary (dart:async/zone.dart:1012)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#9      _Future._completeWithValue (dart:async/future_impl.dart:478)
#10     Future.wait.<anonymous closure> (dart:async/future.dart:392)
#11     _rootRunUnary (dart:async/zone.dart:1128)
#12     _CustomZone.runUnary (dart:async/zone.dart:1012)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#16     _Future._complete (dart:async/future_impl.dart:468)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#19     Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1047)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:30)
#21     _rootRunUnary (dart:async/zone.dart:1128)
#22     _CustomZone.runUnary (dart:async/zone.dart:1012)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#24     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#25     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#26     _Future._complete (dart:async/future_impl.dart:468)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
```

It would be good if we could somehow allow these to be collapsed so the user can focus on their own code, and only expand these if required.

Maybe it could even just be another presentationHint type for "unimportant" or "external" code, and VS Code can collapse consecutive frames with that hint, allowing them to be expanded by clicking?

**Comment by isidorn** [comment]
@weinand yes, this could be easily done since we already use a tree for representing stack frames

**Comment by roblourens** [comment]
Do we differentiate between different types of frames that might be collapsed separately? For example, if I have code that is "skipped by skipFiles" and code that is "skipped by smartStep", it might make sense for these to be marked differently so they would be collapsed as separate groups. I'm not sure what else debuggers are using presentationHint for.

I can imagine it making sense to hide "smartStep" skipped frames entirely, since I never care about them, while "skipFiles" frames I may want to inspect but don't want them to be in my face.

Maybe the DA should be able to label the collapsed group with a label that describes what's in it.

And think about the case where the collapsed frames are at the top of the stack. e.g. I break on an exception in a "skipped" file. Chrome devtools will collapse the blackboxed frames at the top of the stack and focus the first non-blackboxed frame, and show the error at that non-blackboxed frame. I'm not sure whether I like that or not, typically in that case I end up expanding the frames and looking at the real line of code that errored. But it's worth thinking about different scenarios.

**Comment by DanTup** [comment]
> I'm not sure what else debuggers are using presentationHint for.

In Dart/Flutter we use a few:

1. `label` for async boundary markers
2. `subtle` for frames we don't have source for (I'm not totally sure why we'd have this, but it's in the code!)
3. `deemphasize` for non-debuggable code (eg. SDK or third party packages; users can toggle these) - this hint is strangely on the `source` property

Probably we'd want to collapse them all together. Eg. imagine the stack looks like:

- User code
- Framework Code
- Async boundary
- Framework Code
- Async boundary
- Framework Code
- Unknown Source
- User Code

Having them collapse individually wouldn't make sense here (so doing it automatically by presentationHint would probably suck); though allowing the DA to assign a named group so they can control it might make sense.

> e.g. I break on an exception in a "skipped" file. Chrome devtools will collapse the blackboxed frames at the top of the stack and focus the first non-blackboxed frame

I would love something like this. One of my gripes with the Dart debugger right now is that it breaks on exceptions inside code I've marked non-debuggable and I couldn't see an obvious way to jump back to the first debuggable source frame.

**Comment by isidorn** [comment]
I have pushed an initial version of this. Please try it out in tomorrow's insiders

In short it will collapse all subsequent stack frames with source that has presentation hint `demphasized`. The parent element will have the title Show More Stack Frame + source.origin if they all share the origin.
In the future we can do a more sophisticated grouping based on origin.

Here's an example how it looks

![showmore](https://user-images.githubusercontent.com/1926584/47513397-737f4680-d87e-11e8-89c6-d5f4a0fabe3d.gif)

**Comment by roblourens** [comment]
Awesome. Would be great to show the number of hidden frames (Show N more frames)

**Comment by isidorn** [comment]
Suggestion accepted

**Comment by DanTup** [comment]
@isidorn This currently shows `undefined` in the message for my existing code (before I've changed anything); I don't think that's expected:

![screen shot 2018-10-31 at 1 40 18 pm](https://user-images.githubusercontent.com/1078012/47791904-b031be80-dd12-11e8-887d-15cec91462f7.png)

**Comment by DanTup** [comment]
Also - it feels slightly strange to re-collapse as you're clicking on them. If you do want to navigate up the stack while debugging. I don't have a suggestion to fix that though; it'd need some other way to re-collapse 🤔

**Comment by DanTup** [comment]
Also, is there a better description for what we can/should put in `origin`? The comment says:

/** The (optional) origin of this source: possible values 'internal module', 'inlined content from source map', etc. */

But the `etc.` isn't very helpful. The comment [here](https://github.com/Microsoft/vscode/issues/1621#issue-123729342) suggests that it may have specific meanings (beyond just a string), though it seems like it might really just be a text label?

The values I'd like to put in it are for SDK sources and for third party packages.

**Comment by weinand** [comment]
origin is just a string shown in the UI but not interpreted by VS Code in any way.

**Comment by DanTup** [comment]
@weinand Great, thanks - I'll add suitable labels then :-)

(though the `undefined` label should still be fixed, I guess a lot of code might not provide it).

**Comment by weinand** [comment]
@isidorn please fix the "undefined" label for October.

**Comment by DanTup** [comment]
> Also - it feels slightly strange to re-collapse as you're clicking on them

Seems like this behaviour is specific to when a frame has no source. If the frame has source, it navigates there and leaves the section expanded.

**Comment by isidorn** [comment]
I have fixed the undefined label via 9f4969b523

**Comment by roblourens** [comment]
> Also - it feels slightly strange to re-collapse as you're clicking on them

Yeah I thought I couldn't recollapse them, is this a bug or how do I do that?

**Comment by isidorn** [comment]
You can not recolapse. This is a design decision made by @weinand and me since they collapse again after you step.
Let's go with this design for now, and if you hate it after trying it out a bit more we can reconsider this.
Thanks

**Comment by DanTup** [comment]
> Yeah I thought I couldn't recollapse them, is this a bug or how do I do that?

Based on the above, it's not supposed to collapse. However it seems to be a bug that if you don't have source code for a frame (you return an error from `sourceRequest`) then it does collapse immediately when you click on that frame.
