### ISSUE TITLE
Smoke test: flaky debug tests

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50337]
Some debug tests are failing very often recently (e.g. https://vscode.visualstudio.com/VS%20Code/_build?buildId=874)

I commented them out (via https://github.com/Microsoft/vscode/commit/7cc501658abe19ee2fcfe95e65decdeb689baf3c)

**Comment by isidorn** [comment]
I will handle this as a dup of https://github.com/Microsoft/vscode/issues/48110
And will look into in debt week next week. Thanks for commenting them out and sorry about that

**Comment by joaomoreno** [comment]
@isidorn This isn't an issue with the Debug smoketests, but the Search one. The Search leaves dirty data behind and the the app simply can't be debuged since it has syntax errors. I will uncomment the tests.

**Comment by isidorn** [comment]
@joaomoreno thanks!
