### ISSUE TITLE
C# colorization of inline function is not quite right

### ISSUE THREAD

**Issue by TwitchBronBron** [Microsoft/vscode#50339]
Issue Type: <b>Bug</b>

There is some inconsistent behavior with the colorization of c# parameters inside of inline functions. See this screenshot: 

![image](https://user-images.githubusercontent.com/2544493/40419681-110931a4-5e54-11e8-89b3-1c973c51e7bf.png)

<details>
<summary>Source code</summary>

```

namespace TestNamespace {
    public class TestClass
    {
        public TestClass(
        )
        {
            //the parameters have weird coloring at the end
            CallMeBack((param, paramWithNumbers12345, param678WitLettersAtEnd)=>{

            });
            
            //these parameters aren't colored at all
            CallMeBack((
                param1, 
                paramWithNumbers12345, 
                param678WitLettersAtEnd
            )=>{

            });
        }
    }
}

```

</details>

<br/><br/>

VS Code version: Code - Insiders 1.24.0-insider (a521c01d56ec7f07bea2471880f28a77f37983af, 2018-05-21T05:18:01.058Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.99GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
tslint|eg2|1.0.29
php-intellisense|fel|2.3.1
vscode-mysql|for|0.3.0
docomment|k--|0.1.0
code-beautifier|mic|2.0.3
csharp|ms-|1.15.2

</details>

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#120
