### ISSUE TITLE
Inconsistent selection/comment behaviour (minor issue)

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#50333]
With the following code:
```
double
SliderRange::toDataValue( int fromSliderPosition ) const
{
    const double value = minimum_ + ( maximum_ - minimum_ ) / 100.0 * fromSliderPosition;
    const double clamped = std::min( maximum_, std::max( minimum_, value ) );
```
Selecting the first two lines and commenting causes the start of the selection to stay with the 'd' of the first line.

Selecting the last two lines and commenting keeps the start of the selection at the start of the line, which is what I would expect.

This probably has no effect on 99.9% of users, but it causes issues in my extension.

**Comment by weinand** [comment]
Please file against the C++ extension

**Comment by alexandrudima** [comment]
This is debatable. 

I don't think the selection should contain the newly added `//` characters. Here we have the same case and I think this is perfectly OK:

![kapture 2018-05-28 at 11 27 41](https://user-images.githubusercontent.com/5047891/40607921-2bc67fb4-626a-11e8-8958-9fa7214b21ee.gif)

**Comment by Gruntfuggly** [comment]
Why does the selection include the // characters when it is added on the indented lines? Surely it should just do the same in both cases? To be honest I don't really mind if it does or doesn't, it would just be good if it did the same thing in all cases. 8-)

**Comment by alexandrudima** [comment]
At least when having a word selected, it is oftentimes desirable to leave the word selected and not expand the selection to the added `//`.

For example, if the class name is selected, perhaps a <kbd>Ctrl</kbd>+<kbd>C</kbd> or a <kbd>Ctrl</kbd>+<kbd>F</kbd> would follow

![kapture 2018-05-29 at 12 40 43](https://user-images.githubusercontent.com/5047891/40654092-92d2269e-633d-11e8-8fdf-267a936f00a8.gif)

But, at the same time, I agree that this looks unbalanced:
![kapture 2018-05-29 at 12 42 21](https://user-images.githubusercontent.com/5047891/40654169-c5c821fc-633d-11e8-921c-6221612c64e5.gif)
