### ISSUE TITLE
`vscode.workspace.onDidChangeTextDocument` is called with no changes

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#50344]
I've noticed the function passed to `vscode.workspace.onDidChangeTextDocument` gets called twice if I just insert a new line into the document, the first time it gets called `contentChanges` is empty. 

An extension might perform a lot of work when the document changes, triggering this event without any actual change seems pretty wasteful.

**Comment by fabiospampinato** [comment]
`contentChanges` seems to be empty only after the very first change to the document.

**Comment by fabiospampinato** [comment]
@jrieken from what I can see the function passed to `onDidChangeTextDocument` is called twice in succession after the very first edit, if somebody for some reason is relying on this behavior they are probably writing bad code.

**Comment by jrieken** [comment]
I am not here to judge code quality but my role is to not break existing extensions ;-) I think checking the `contextChanges`-array for being empty isn't a high burden. It's also documented like that

>This usually happens when the [contents](#TextDocument.getText) changes but also when other things like the [dirty](#TextDocument.isDirty)-state changes.

**Comment by jrieken** [comment]
Closing because no code change is planned
