### ISSUE TITLE
Support navigating through previously shown previews with Ctrl+Tab

### ISSUE THREAD

**Issue by 3v1n0** [Microsoft/vscode#50347]
Imagine the case where

1. You're working on `file-a`
2. `ctrl+p` to switch to `file-b`
3. `ctrl+p` to switch to `file-c`
4. Ctrl+tab to go back...

And actually the editor goes to `file-a` as I didn't touch the `file-b`...

Now, I know this can be mitgated with `workbench.editor.enablePreviewFromQuickOpen`, but I actually want previews from quick open as I only look at them quickly and I want avoid to use memory for that; but at the same time I want to be able to go back to where I was.

So, it should be possible to also keep an history of opened previews and allow to navigate through that with `Ctrl+[shift]+Tab`, without making them persistent editors, and thus wasting memory.

PS: assuming of working in Linux / Windows, but same applies with Cmd keybindings on mac too, of course.

**Comment by bpasero** [comment]
@3v1n0 you can use Ctrl+O for that, it contains a list of any editor ever opened during the session. Did you try?

**Comment by 3v1n0** [comment]
@bpasero mhmhm, in Linux that will just open the file opener, not really what I wanted.

Plus, in any case it wouldn't be in a Switcher-way.

**Comment by 3v1n0** [comment]
Mh, @bpasero how can be that be achieved?

**Comment by bpasero** [comment]
I for example use this with `Ctrl+Q`. Configured as keybinding:

```json
	{
		"key": "ctrl+q",
		"command": "workbench.action.openPreviousEditorFromHistory"
	},
	{
		"key": "ctrl+q",
		"command": "workbench.action.quickOpenNavigateNext",
		"when": "inQuickOpen"
	}
```
