### ISSUE TITLE
Breakpoint not hit under "ts-node" unless "breakOnLoadStrategy" is set.

### ISSUE THREAD

**Issue by vsDizzy** [Microsoft/vscode#50342]
This is https://github.com/Microsoft/vscode/issues/45657 related and special for @roblourens 
I made a repo reproducing the problem https://github.com/vsDizzy/vscode-bp-not-hit

**Comment by roblourens** [comment]
> unless "breakOnLoadStrategy" is set

If it works with breakOnLoadStrategy, what's the problem? 😁 

This is basically expected here - ts-node compiles files in memory then runs the program so the debugger can only get sourcemaps while the code is already running. Then it's a race between loading sourcemaps to set BPs, and the code running.

**Comment by vsDizzy** [comment]
Thanks for the explanation.
