### ISSUE TITLE
(LaTeX) document formatting on save doesn't work

### ISSUE THREAD

**Issue by mcoweber** [Microsoft/vscode#50345]
Hi,

I use VS Code as LaTeX editor and for this purpose, I've installed LaTeX Workshop (https://github.com/James-Yu/LaTeX-Workshop) which also comes with a formatter integration. If I right-click in a .tex file and select "Format document", auto-formatting is working as expected. However, although I've set "editor.formatOnSave": true, .tex files are not formatted on save.
The weird thing is, that in the output window, there is the statement "Formatted -filename-" as expected and in the same way as for the right-click --> "Format document" execution.

According to James and my understanding, there should be no difference between these two options. Is a formatter called differently (e.g. with different parameters) dependent on how it is executed? Or is there some special integration necessary to enable formatting on save?

Best regards
Marc

**Comment by weinand** [comment]
As far as I know there is no special integration necessary to enable formatting on save.
But be aware that format on save doesn't kick in when when auto saving after delay. 

See https://code.visualstudio.com/updates/v1_6#_format-on-save.

If that doesn't help please file an issue against the LaTeX extension.
