### ISSUE TITLE
What does "Running Save Participants..." mean?

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#50351]
VSC: v1.23.0

I've noticed there's a new statusbar item that's displayed when I save a file:

<img width="201" alt="screen shot 2018-05-23 at 14 47 16" src="https://user-images.githubusercontent.com/1812093/40425295-4610b22a-5e98-11e8-88ac-016e2aa427d1.png">

What does it even mean? Searching for `site:https://code.visualstudio.com/docs participants` gives 0 results on Google.

And why does it take forever (2s+) to display this thing even when I'm saving a plain text, completely empty, non modified, file?

**Comment by weinand** [comment]
Maybe related to #50123

**Comment by mjbvz** [comment]
These are actions that are performed on save by extensions, such as format on save

Do you still see this delay when you disable all extensions?

**Comment by fabiospampinato** [comment]
This is pretty weird, I have no idea how to reproduce this (showing the statusbar item) reliably but this is what's happening for me:

- I couldn't reproduce it with all extensions disabled
- I couldn't reproduce it on the "main" window
- I could reproduce it on the "debug" window, the one that shows up when developing extensions , the one with '[Extension Development Host]' written in its titlebar
- I'm not developing an extension that contributes an action to "format on save"
- I restarted the debug session and now I can't reproduce it anymore 🤷‍♂️

**Comment by mjbvz** [comment]
Ok, let me know if you find reliable repo steps. Its possible the extension host window ended up in a bad state somehow

**Comment by ShogunPanda** [comment]
This is happening for me as well, taking almost a minute.

**Comment by vimalprakashts** [comment]
For me also it takes long time to save , some times loses the find and replace updates 

![image](https://user-images.githubusercontent.com/1901861/42723342-b2b8dd08-8779-11e8-9cd9-60228275b868.png)
