### ISSUE TITLE
toggle line comment

### ISSUE THREAD

**Issue by ens121** [Microsoft/vscode#50350]
Issue Type: <b>Feature Request</b>

Minor...

If we have a commented out HTML line:
```  <!--div class="blah"></div-->```

The toggle line comment keyboard shortcut changes it to:
```  div class="blah"></div```

Using this comment style is something we do when we need a single line commented out.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
By design, `add comment` adds the comment tags (`<!--` and `-->`) and ` Remove comment` removes them. What's stays in between is not touched. Adding smartness here would just break other use cases. We rather want to keep this simple and predictable.
