### ISSUE TITLE
[ FEATURE REQUEST ] Set the default launch option as no debug

### ISSUE THREAD

**Issue by kekkokk** [Microsoft/vscode#50358]
Hi guys,
I see that there's already an option to start without debugging by pressing ctrl + f5.
The problem is that sometimes we need to start our configurations (multiple at the same time) by default with nodebug option.
The only way I found to select a launch configuration is by selecting it from the bropdown menu here:
![screen shot 2018-05-23 at 18 19 29](https://user-images.githubusercontent.com/15072723/40437528-e3b5faf4-5eb5-11e8-99a6-22c38dd59cf4.png)

Or by selecting it here:
![screen shot 2018-05-23 at 18 29 37](https://user-images.githubusercontent.com/15072723/40438037-506628f8-5eb7-11e8-8528-7c36e63262d9.png)

but once you click that, a debug session is launched.

Can't we just add a dropdown menu in this last screen so we can select DEBUG or RUN?
It's a bit annoying to have to ctrl + f5 every time

**Comment by roblourens** [comment]
You could swap the keybindings around easily. Or do you want to change the behavior of the run button?

Another tip, you can set `"noDebug": true` in your launch config for the same result. It will give you a warning but it will work.

**Comment by kekkokk** [comment]
In my opinion letting the user doing it by interface adding a dropdown menu would be very nice, since the feature already exist in the "core".
but "noDebug": true definitely did the trick for me in this case.
Many thanks
