### ISSUE TITLE
How can I add an COM reference into a c# proj in vscode

### ISSUE THREAD

**Issue by shikouzhong** [Microsoft/vscode#50353]
Yes, we can add a nuget package using the dotnet comand line, but I don't know how to add a COM reference in vscode, just as in vs community.

I have searched the stackoverflow, but no right answer for c# proj in vscode.

- VSCode Version: 1.23.0
- OS Version: Windows 10 1803

**Comment by weinand** [comment]
Please file this question against the C# extension (since VS Code has no built-in C# or .net support).
