### ISSUE TITLE
Workspace multiple git repos not updating

### ISSUE THREAD

**Issue by GradyD** [Microsoft/vscode#50357]
Issue Type: <b>Bug</b>

If I add multiple folders to my workspace and each is a unique git repo the branch in use is not updated on a per file/folder basis. 

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|Memory (System)|15.88GB (5.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ansible|haa|0.2.8
PowerShell|ms-|1.7.0
vscode-docker|Pet|0.0.26
vscode-icons|rob|7.23.0
salesforcedx-vscode|sal|42.14.0
salesforcedx-vscode-apex|sal|42.14.0
salesforcedx-vscode-apex-debugger|sal|42.14.0
salesforcedx-vscode-core|sal|42.14.0
salesforcedx-vscode-lightning|sal|42.14.0
salesforcedx-vscode-visualforce|sal|42.14.0
jinja|who|0.0.8

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
#47332
