### ISSUE TITLE
[folding] place folding actions inside editor

### ISSUE THREAD

**Issue by jcklpe** [microsoft/vscode#50359]
Hi, I'm a UX designer who is new to vscode and have been learning code for the past year and a half. 

I really like the customizability of VScode! but there's one thing I wish I could change with how code folding works. 

To my knowledge no other code editor does this, so perhaps it's a silly idea but I think it would be easier to follow the nesting of code if the button to fold and unfold code were next to the actual guidelines. 

Here is what my current set up looks like. I'm using the Guides and Bracket's Colorizer extensions to better highlight nesting/sections of code. 

![image](https://user-images.githubusercontent.com/9451726/40438130-e48d6b1c-5e7c-11e8-8f1b-2d38f17efc04.png)

And here's what I would propose instead. 

![image](https://user-images.githubusercontent.com/9451726/40440103-ae02ac96-5e82-11e8-9be1-734babfb9e2e.png)

My ideal would be for the color of the code fold buttons to also be stylable so that something like the Bracket Colorizer extension could then match the color of the brackets to the color of the code folding button etc as pictured, but the concept remains the same even if you don't account for that.

**Comment by aeschli** [comment]
Keeping it open to collect votes, but to be honest, that would be quite some work to implement.

**Comment by thedonquixotic** [comment]
Just out of curiosity and my own desire to learn, but what makes it difficult
to implement? My understanding is that VScode is an electron app, and so the app
is basically a website styled with CSS and manipulated with JS. I'm guessing
that the code folding indicators are not rendered in the same pane as the code
maybe? Or they would have to be absolute positioned and that would have to be
calculated based on some kind of measurement? Would it be possible to implement
the icons as before pseudo elements and then they could be placed relative to
the specific code chunks they've manipulating? I'm just spitballing. I'm
extremely ignorant of how this stuff works, but I'm curious to learn more.

Sincerely,David Aslan French  
Jackalope.tech Design X Code: Pushing the boundaries of design, art, and code.
 jackalope.tech  
Find me on Facebook  Let's connect!  








On Mon, May 28, 2018 4:16 AM, Martin Aeschlimann notifications@github.com 
wrote:
Keeping it open to collect votes, but to be honest, that would be quite some
work to implement.

**Comment by jcklpe** [comment]
I also just realized that to be more clear was that the solution I liked best that was similar (but better thought out than mine) was the hierarchical solution #2 by @bgashler1

I know that story is 3 years old and this story is a year old but I thought it was at least worth clarifying my thoughts as this thread is still open and might be useful documentation on the possible future feature. I'm still learning how to program Javascript but I might be able to learn writing extensions for vscode soon. I'd really like to tackle this if I can learn how so please don't think I'm just posting here to annoy y'all. I've hacked together some fairly neat tweaks using the js and css code injection extension and I'd like to actually learn how to work this stuff out properly and make it a real extension I can share with other people so hopefully eventually I'll learn that. Anyway thanks!

**Comment by jcklpe** [comment]
Made a comment in another thread and decided to make an updated mockup for this issue , so I thought I'd also drop that updated mock up here too:

![sketch](https://user-images.githubusercontent.com/9451726/63218296-098da180-c11d-11e9-8ccd-057d617280ec.jpg)
![sketch2](https://user-images.githubusercontent.com/9451726/63218297-0b576500-c11d-11e9-9497-2f599f7d654e.jpg)
