### ISSUE TITLE
Smoke: flaky test (Search replaces first search result with a replace term)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50355]
As seen in https://vscode.visualstudio.com/VS%20Code/_build?buildId=876

Commented out via https://github.com/Microsoft/vscode/commit/77bbc7e3e4a72c1a84ddbf7ce03b65787043b00a

**Comment by roblourens** [comment]
Not sure what changed but @joaomoreno enabled it and it hasn't failed yet 🤷‍♂️ Thanks Joao
