### ISSUE TITLE
Command line open a same file twice, generate two windows

### ISSUE THREAD

**Issue by yingbo** [Microsoft/vscode#5035]
- VSCode Version:  0.10.11
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. In Terminal, type "code ~/.profile" will open the window with .profile.
2. Type "code ~/.profile" again, a new window will open with the same .profile file. It should resume the window in step 1.

**Comment by bpasero** [comment]
Two options:
* you configure VS Code to open files in the same window: window.openFilesInNewWindow = true
* you start with "-r" option to reuse last active instance

**Comment by bpasero** [comment]
closing as designed, given the workarounds.
