### ISSUE TITLE
Is it possible to use variables from settings.json in c_cpp_properties.json?

### ISSUE THREAD

**Issue by r3d9u11** [Microsoft/vscode#50356]
Is it possible to use variables from settings.json in c_cpp_properties.json?
I'm saw [notice](https://github.com/Microsoft/vscode-cpptools/issues/697#issuecomment-374176668) on this theme, but this feature doesn't work for me :(
settings.json:
```
{
    "arduino.path": "/home/r3d9u11/Software/arduino-1.8.5"
}
```
c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${config:arduino.path}/hardware/arduino/avr/cores/arduino",
                "${config:arduino.path}/hardware/arduino/avr/variants/mega",
                "${config:arduino.path}/hardware/tools/avr/avr/include",
                "${config:arduino.path}/hardware/tools/avr/avr/include/util",
                "${config:arduino.path}/hardware/tools/avr/lib/gcc/avr/4.9.2/include"
            ],
            "defines": [
                "UBRRH",
                "UNICODE"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "databaseFilename": "",
                "path": [
                    "${config:arduino.path}/hardware/arduino/avr/cores/arduino",
                    "${config:arduino.path}/hardware/arduino/avr/variants/mega",
                    "${config:arduino.path}/hardware/tools/avr/avr/include",
                    "${config:arduino.path}/hardware/tools/avr/avr/include/util",
                    "${config:arduino.path}/hardware/tools/avr/lib/gcc/avr/4.9.2/include"
                ]
            },
            "cStandard": "c11",
            "cppStandard": "c++17",
            "compilerPath": "/usr/bin/gcc",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
main.c:
![asd](https://user-images.githubusercontent.com/15020827/40432156-abe1b3a6-5eb1-11e8-86b4-f1ee6a5250ac.png)
(searching process is freezed)

Test project: [TestAvrC.zip](https://github.com/Microsoft/vscode/files/2031622/TestAvrC.zip)

VSCode 1.23.1

Thanks.

**Comment by bobbrow** [comment]
@r3d9u11, take a look at [this document](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Customizing%20Default%20Settings.md).  The C++ extension exposed new VS Code settings that you can reference in your **c_cpp_properties.json** file (or you can use them instead of having a **c_cpp_properties.json** at all)

**Comment by bobbrow** [comment]
You can also add your own custom "env" to **c_cpp_properties.json** that will be recognized using the standard `${env:var}` syntax.  See [this document](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md).

**Comment by Gouthamm4G** [comment]
But I noticed that the initialized variables don't work inside `env` when it is referenced right next to the definition. For example,
```
{
    "env": {
        "envRoot": "apps/tool/buildenv",
        "arm6.include": "${envRoot}/arm6/include",
    },
    "configurations": [
        {
            "name": "Custom",
            "includePath": [
                "${arm6.include}"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "path": [
                     "${arm6.include}"
                ]
            },
            …
        }
    ],
    "version": 4
}
```
This doesn't seem to work. That would be really useful
