### ISSUE TITLE
diffEditor.renderIndicators doesn't work for peek

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#50362]
- VSCode Version: 1.23.1
- OS Version: macOS

`"diffEditor.renderIndicators": false` doesn't work for peek diff changes (I don't know if I said that correctly).

![image](https://user-images.githubusercontent.com/10441177/40442600-cbe95210-5ecc-11e8-961e-c193fac4ffb0.png)

**Comment by joaomoreno** [comment]
Yeah they should not even appear there.

**Comment by joaomoreno** [comment]
Fixed in `master`.
