### ISSUE TITLE
Themes: switching between light and dark theme shows weird artefacts over editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5036]
![untitled](https://cloud.githubusercontent.com/assets/900690/14319240/bd7df0a8-fc10-11e5-9992-6c7b959921fd.gif)

@aeschli might be a consequence of your changes?

**Comment by bpasero** [comment]
Hm looks like this flashing was already previously so your change might not be related...

**Comment by alexandrudima** [comment]
@bpasero The whole thing is flashing :). But I notice the glyph margin takes a while to react, is that what you mean?

**Comment by bpasero** [comment]
@aeschli knows, we talked. 

@alexandrudima so it seems the glyph margin is not updating as live as the other parts. is there a reason?

**Comment by alexandrudima** [comment]
Yes, because the editor updates the DOM at the next animation frame. I will make a change to update the DOM in case of a theme change synchronously.

**Comment by bpasero** [comment]
@alexandrudima thanks man! <3
