### ISSUE TITLE
VS Code launches itself when I plug in a USB drive -- never requested, not desired

### ISSUE THREAD

**Issue by polycopter** [Microsoft/vscode#50367]
- VSCode Version:Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Linux Mint 18 'Sarah' Cinnamon 64-bit

Steps to Reproduce:

1. plug in any USB storage (external HD, thumb drive, etc.)
2. vscode launches itself

Does this issue occur when all extensions are disabled?: cannot test that

**Comment by polycopter** [comment]
yikes! no, please don't assume it's a duplicate of that! or else, tell me how to re-open that one, because someone closed it (in my view) prematurely (maybe my fault because I didn't pay attention). That just says: "it's windows fault, not vscode" which of course can't be true. Maybe it could be Linux Mint's fault (or cinnamon?), but not Windows, there's no Windows here... and anyway if I uninstall vscode & the problem disappears, how can it really be Linux Mint's fault? Somehow vscode has made this happen.

**Comment by weinand** [comment]
This must be an OS issue since how can VS Code open itself if it does not run?

Uninstalling VS Code doesn't prove that this is VS Code fault because how could linux launch something that doesn't exist?

**Comment by Tyriar** [comment]
@polycopter I cannot reproduce this on Linux. I know this is not the answer you want, but it has to be OS-related or something else to do with your environment like some other program launching the default editor?

For your information this is how the deb package works:

- The control file: https://github.com/Microsoft/vscode/blob/master/resources/linux/debian/control.template
- This runs in the post install step: https://github.com/Microsoft/vscode/blob/master/resources/linux/debian/postinst.template
- The `/usr/` paths that VS Code gets installed to can be found here: https://github.com/Microsoft/vscode/blob/189f560fa5c84c8eea0e6a13c0ca691e3f37c1a9/build/gulpfile.vscode.linux.js#L33-L86

**Comment by polycopter** [comment]
"...some other program launching the default editor?" -- at no time did I explicitly say to my OS, you have a new "default editor," and it's vscode. Is it possible that this is a behavior of the vscode installation, and/or something it does automatically when first run -- to set itself as "the default editor" w/o the user asking it to do so? If so, then I would still be inclined to think that it is vscode's "fault" -- I'm not interested in blaming, just fixing, tbh. So thank you for the information, although it's a bit "greek" to someone as yet relatively unschooled in Linux package management.

**Comment by Tyriar** [comment]
> Is it possible that this is a behavior of the vscode installation, and/or something it does automatically when first run -- to set itself as "the default editor" w/o the user asking it to do so?

Possible of course, but unlikely given my knowledge of how the package works. I'd love to be proven wrong and have a bug fixed but I don't think it's a VS Code issue and this is the only report we have ever had of this.
