### ISSUE TITLE
[Feature Request] Keep the editing line always at the center of editor

### ISSUE THREAD

**Issue by drdebmath** [microsoft/vscode#50379]
Instead of moving the line focus below when enter key is pressed, there should be an option to keep the editor focus line always at the center of the editor.
<br>
Suppose the editor displays 20 rows, then the line being edited should always be at the 10th row of the editor. <br>
Every time I am navigating with the cursor to a line above or below, along with moving the cursor, it should move the scrollbar such that the cursor always remains at the 10th row.

**Comment by Gruntfuggly** [comment]
Try this extension:
https://marketplace.visualstudio.com/items?itemName=tickleforce.scrolloff

**Comment by drdebmath** [comment]
The above extension works fine.. 
**except** when word-wrap is enabled, a single line appears as multiple lines. In that case it takes into account the actual line number according to new line characters rather than the relative line number in the editor.<br>
When I move the cursor inside the wrapped line, it does not do anything. 
Thanks for the extension.

**Comment by jerviscui** [comment]
You can use Typewriter Auto-scroll VSCode Extension
