### ISSUE TITLE
Run tests from extension closes my main window

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5037]
- VSCode Version: 0.10.12-alpha
- OS Version: Linux ElementaryOS Freya

Steps to Reproduce:

1. yo code, create a TypoeScript project
2. npm on the new fodler
3. Open vscode on the new folder
4. In the debug viewlet run the tests
5. A window opens, and when closing closes also the main window

**Comment by bpasero** [comment]
Eh nö?
