### ISSUE TITLE
Scrollbar should be at the editor edge

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#50370]
Issue Type: <b>Bug</b>

The list of settings in the settings editor does not takes the whole width of the editor. This is fine, but the composition of elements in wrong. The scrollbar should still show up at the right edge of the editor rather than the right edge of the list.

![screen shot 2018-05-23 at 2 23 42 pm](https://user-images.githubusercontent.com/4674940/40452001-4657cf0a-5e95-11e8-9bcc-19f64cbc76c0.png)

VS Code version: Code - Insiders 1.24.0-insider (aa1aafbabbd26e906c01e56f8a673b68a5c96666, 2018-05-23T05:11:10.604Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.63GB free)|
|Process Argv|/Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_21181490|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.0.1
material-icon-theme|PKi|3.4.0
vscode-docker|Pet|0.0.27
solargraph|cas|0.17.3
npm-intellisense|chr|1.3.0
regex|chr|0.2.0
githistory|don|0.4.1
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
git-project-manager|fel|1.6.1
crazy|kie|0.0.2
svgpreview|kis|0.2.0
vscode-azurestorage|ms-|0.3.1
mssql|ms-|1.3.1
python|ms-|2018.4.0
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
Go|ms-|0.6.80
vsliveshare|ms-|0.3.198
printcode|nob|2.3.0
Ruby|reb|0.18.0
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.3.1

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I tried this earlier and had trouble making the shadow at the top narrow, but the scrollable container wide. Will try again.
