### ISSUE TITLE
Visual studio keep hanging then stop working

### ISSUE THREAD

**Issue by khoanguyenlio** [Microsoft/vscode#50377]
Issue Type: <b>Performance Issue</b>

I got an updated last week then now my application sometime got hanging for a while then popup the modal and ask me to wait or reset. 
* If I clicked wait, they will hang for awhile then re-popup the modal
* If I click reset, it's reset then for a while the system got hanged again.
This one really annoy. So now, I have to change the IDE for working. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:38.209Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (6.44GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    75	 19560	code main
    0	   223	  7896	   window (file-upload.component.ts - angular-workspace (Workspace) - Visual Studio Code)
    0	    32	  5892	     searchService
    1	    94	 28228	     extensionHost
    0	    31	 29140	     watcherService
    0	    61	  9616	   shared-process
    0	    60	 10436	   gpu-process
    0	    63	 12264	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (file-upload.component.ts - angular-workspace (Workspace) - Visual Studio Code)
|    Folder (mrp): 966 files
|      File types: ts(501) scss(163) html(158) png(66) svg(34) json(15) js(6)
|                  xml(5) jpg(4) md(2)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1);
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-angular2-files|ale|1.5.0
vscode-eclipse-keybindings|alp|0.9.7
angular2-snippets|dan|1.0.19
vscode-eslint|dba|1.4.10
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|8.3.2
tslint|eg2|1.0.29
vsc-material-theme|Equ|2.0.1
code-runner|for|0.9.3
angular2-switcher|inf|0.1.7
Angular2|joh|6.1.1
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|4.4.3
material-icon-theme|PKi|3.4.0
autoimport|ste|1.5.3
quokka-vscode|Wal|1.0.125
vsc-angular-cli|web|1.0.0

(3 theme extensions excluded)

</details>

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by khoanguyenlio** [comment]
@weinand yah you were right. Some extension got problem. Sorry for lately reply :D
