### ISSUE TITLE
I set Dolphin as default file manager, but VSCode opens Nautilus instead of Dolphin

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#50386]
- **VSCode Version:** 1.24.0-insider
- **OS Version:** Ubuntu 18.04 with GNOME, KDE, Unity and XFCE

Steps to Reproduce:

1. I set Dolphin as default file manager via command and in the defaults.list.
2. I open VSCode Insiders
3. I open a folder
4. VSCode opens Nautilus instead of Dolphin

VSCode does not recognise that Dolphin is a new default file manager. 

Does this issue occur when all extensions are disabled? Yes

**Comment by weinand** [comment]
@gusbemacbe what do you mean by step 3 "open a folder"? 

"Opening a folder" in VS Code means clicking on the folder in the explorer (and that works fine for me).

**Comment by gusbemacbe** [comment]
Inside VSCode, I selected File -> Open Folder ...

**Comment by weinand** [comment]
Aha, you mean VS Code uses the wrong "open file dialog".

**Comment by saileshkush95** [comment]
I'm also facing same problem

**Comment by gusbemacbe** [comment]
@weinand and @bpasero, the same problem still insists. I am using Deepin OS and Manjaro, VSCode opens the ugly X11/Xorg-based Nautilus instead of Deepin File (Deepin OS's default file manager) and Dolphin (Manjaro's).

**Comment by bpasero** [comment]
@gusbemacbe did you try with our latest insider release that comes with Electron 2.0.x and GTK3 support? Just wondering if that would change anything here.

**Comment by gusbemacbe** [comment]
@bpasero 

Sorry for my absence, I was sick. 

ON Manjaro, it supports perfectly GTK3, but it still opens Nautilus instead of Dolphin File.

On Deepin OS, it does not support GTK3, and still also opens Nautilus instead of Deepin File Manager.

**Comment by davidpomerenke** [comment]
Still an issue. 

Would be nice if VSCode just used the default file manager or if there was at least a setting for changing this manually. Nautilus can be used, but it does not integrate well in KDE, it sometimes is quite annoying.

**Comment by gusbemacbe** [comment]
@bpasero

**Comment by dimative** [comment]
Please recommend to me better solution for this issue. I want to use deepin file manager but vscode runs.

**Comment by gusbemacbe** [comment]
@bpasero

**Comment by cmpute** [comment]
Same problem here

**Comment by davidpomerenke** [comment]
Seems not to be fixed yet. Could you reopen the issue and (if you agree) remove the "more info needed" tag? @gusbemacbe @bpasero

**Comment by gusbemacbe** [comment]
I called him twice. This issue passed one year. Nobody considered this issue as important. I am already used to use GTK-based dialg in KDE. 

It is the moderator who will decide or not to reopen.

**Comment by dimative** [comment]
+1

**Comment by chrisshyi** [comment]
I have the same problem on Kubuntu 18.04 as well.

**Comment by dimative** [comment]
Me too. I am using Deepin 15.9.2

**Comment by chrisshyi** [comment]
How does VS Code communicate with the operating system's file manager, I wonder?

**Comment by gusbemacbe** [comment]
@chrisshyi 

As VSCode is written in GTK, it will use GTK2-based Xorg dialog. The GTK-based apps can not communicate with non-GTK standard file managers. To open the KDE-based dialog or Dolhin as a standard file manager, VSCode needs to be written in QT.

**Comment by chrisshyi** [comment]
@gusbemacbe 

I see, that really clarifies things. Would you mind pointing me to where the GTK part of the source code resides? I'd love to learn more about how VSCode works internally.

Thanks!

**Comment by tomdavidson** [comment]
VSCode is not built with GTK but with TypeScript with packaging and run time via Electron. Electron needs to be updated to be aware of its desktop environment. Every Electron app has this issue - ie its an upstream issue and not VSCode - https://github.com/electron/electron/issues/2911#issuecomment-429474776

**Comment by gusbemacbe** [comment]
@chrisshyi 

VSCode uses Electron and Nodejs, which compiles only for GTK. 

https://github.com/Microsoft/vscode/blob/0fde6619172c9f04c41f2e816479e432cc974b8b/build/azure-pipelines/linux/continuous-build-linux.yml#L5

But @sylveon, which is responsible for making VSCode's transparency with KDE, must know how to solve it. 

Like VSCode, on KDE, Firefox, Google, Inkscape, etc., are GTK-based and open the GTK2-based Xorg dialog.

**Comment by sylveon** [comment]
https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#KDE_file_dialogs_for_GTK+_applications

**Comment by gusbemacbe** [comment]
@sylveon 

I installed `kgtk-wrapper`, tested it with VSCode and it did not work. And `kgtk` does not support GTK3-based apps, as Inkscape.

**Comment by sylveon** [comment]
That article mentions `kdialog` for Chromium. Since Electron uses Chromium, I'd expect it to work.

**Comment by matrs** [comment]
In multiple Linux distros using KDE/plasma with `kdialog` (mint,arch/manjaro, kubuntu ) chrome and chromium use the default file browser (dolphin), but in none of these distros vs code uses it. It still uses a GTK based dialog, so that's not a solution.

**Comment by atyshka** [comment]
Yeah this is definitely possible, since it works for firefox and other apps. Anyone know is this is an issue with Electron or VSCode?

**Comment by matrs** [comment]
Thumbs up the first post, although this is closed i think that's the only way to bring some attention to this. It should be possible, but it seems  clear that it isn't important for this project.

**Comment by madprops** [comment]
This is an Electron issue. I do prefer if I could use Dolphin.

**Comment by gusbemacbe** [comment]
It seems that there is a truck used by IntelliJ IDEA developers:

```shell
message()
{
  TITLE="Cannot start IntelliJ IDEA"
  if [ -n "$(command -v zenity)" ]; then
    zenity --error --title="$TITLE" --text="$1" --no-wrap
  elif [ -n "$(command -v kdialog)" ]; then
    kdialog --error "$1" --title "$TITLE"
  elif [ -n "$(command -v notify-send)" ]; then
    notify-send "ERROR: $TITLE" "$1"
  elif [ -n "$(command -v xmessage)" ]; then
    xmessage -center "ERROR: $TITLE: $1"
  else
    printf "ERROR: %s\n%s\n" "$TITLE" "$1"
  fi
}
```

**Comment by gusbemacbe** [comment]
@bpasero 

There is something interested that drew my attention. I used Gitahead, that used Dolphin dialog instead of X dialog:

![gitahead](https://user-images.githubusercontent.com/2257024/65381184-82ef5580-dcc2-11e9-86c5-3fd1c568ff7d.gif)

But Gitahead is not an Electron-based. 

And SVG Cleaner opens the KDE dialog instead too:

![svg-cleaner](https://user-images.githubusercontent.com/2257024/65381194-cea1ff00-dcc2-11e9-9e29-1844c4c93440.gif)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by gusbemacbe** [comment]
I am on Arch Linux with KDE, the which uses pacman or AUR, but I installed manually the package. It seems that it does not work yet. I will test yet.

![image](https://user-images.githubusercontent.com/2257024/66544946-ee815180-eb0f-11e9-89e2-855ac02f5942.png)

**Comment by gusbemacbe** [comment]
In the second test, I installed via rm installed from AUR, and installed Electron 6, but it was still the same thing.

Maybe better I test on Fedora with KDE.

**Comment by bpasero** [comment]
@gusbemacbe thanks, would you be willing to test out Electron bare (without VSCode) to see if it reproduces? I can guide you through it, but you would need to install Electron Fiddle: https://electronjs.org/fiddle

**Comment by gusbemacbe** [comment]
In the third test, on Fedora with KDE, it is still the same problem. It does not open Dolphin instead. 

I installed Electron Fiddle, and ran the run, it still opens the awful GTK dialog instead:

![image](https://user-images.githubusercontent.com/2257024/66552707-31e3bc00-eb20-11e9-8248-9cebc7ffac87.png)

Maybe you create two versions of VSCode for Linux, one for any KDE/QT-based environment, and another version for any GTK-based environment, like the openSUSE developers created the KDE version of Firefox.

**Comment by gusbemacbe** [comment]
@bpasero, you duplicated the same text. I have already tested on Fiddle.

**Comment by bpasero** [comment]
@gusbemacbe great, can you report this as issue then to Electron? See https://github.com/atom/electron

**Comment by gusbemacbe** [comment]
@bpasero, ready.

**Comment by aderchox** [comment]
+1

**Comment by cryptism** [comment]
Is there any workaround right now?

**Comment by Natetronn** [comment]
I'm running into this issue as well. Was there a solution?

**Comment by cryzed** [comment]
Same problem.

**Comment by TomasAsadauskas** [comment]
Same here. Using kubuntu, VS Code opens GTK open file dialog.

**Comment by shawnee247** [comment]
Yes because it's stolen and someone else is using it I need to have them reported by authorities and retrieve it for me also takes look at my VR body it's dismembered I need help I'm Shawn Daniel Mclean I'm dolphin

**Comment by pynkpanther** [comment]
- using fresh Xubuntu20.04 install
- xubuntu uses Thunar
- installed VS Code from default package manager
- when tryin to `open containing folder`:

![Screenshot_2021-01-06_09-08-12](https://user-images.githubusercontent.com/10895291/103744863-c6c4b600-4ffe-11eb-9c26-31c044616d6f.png)

**Comment by OverShifted** [comment]
Hi.
For me vscode and a few other applications open XFCE's Thunar instead of Dolphin which is the default file manager.
Any possible fixes?

**Comment by NhatGit** [comment]
Do you talk about fail to choose default "file manager dialoge" ? I think it is problem of linux. Vscode and chrome, ... all app use same "defaul file manager dialoge" defined somewhere in setting. I have search google for an hour about this.

**Comment by jlost** [comment]
I have this problem as well (thunar opens instead of nemo, preferred app is nemo), but it also happens in Brave, so I'm not convinced it's a VS Code issue.

**Comment by Yanpas** [comment]
I only have dolphin and code opens everything in dolphin

Make sure you follow: https://www.freedesktop.org/wiki/Specifications/shared-mime-info-spec/

Also worth reading https://wiki.archlinux.org/index.php/default_applications

**Comment by tomdavidson** [comment]
@Yanpas my Debian & Ubuntu experience over the years has been non-KDE apps such as FireFox and VS Code do not use Dolphin. I read through the references but did not understand what needs to be changed to have an experience like yours. Can you elaborate?

**Comment by matrs** [comment]
Hey @Yanpas , I quote my old answer in this same issue:
> In multiple Linux distros using KDE/plasma with `kdialog` (mint,arch/manjaro, kubuntu ) chrome and chromium use the default file browser (dolphin), but in none of these distros `code` uses it. It still uses a GTK based dialog, so that's not a solution.
> Also, addressing @begusbemacbe comment, `firefox` uses a gtk-based dialog but the solution listed in the `arch` wiki works, that's using ` xdg-desktop-portal` and editing its `.desktop` file. So all these non-kde apps may use `dolphin` to open files, isn't the case for vscode.

All of the user here have KDE, **none** of us has had the experience you have

**Comment by Yanpas** [comment]
I just wanted to point that unlikely someone from vscode dev team would be digging plethora of different linux setups to debug this issue. Let's be honest, it's minor and affected group of users is minor as well.

So to help them it's worth to grasp how the all the stack/chain looks like (e.g. vscode -> electron -> xdg-open -> mimetype configs) and point where the issue is.

Gtk file-save dialog is most likely tied to electron, not code. And the solution would be xdg portals.

I'm not using kde currently, using RHEL gnome instead, so just came here to give advise ❤️

**Comment by tristan957** [comment]
Issue has been fixed upstream: https://github.com/electron/electron/pull/19159/

**Comment by gusbemacbe** [comment]
@bpasero, Tristan has merged and fixed, it is ready, please provide us VSCode Exploration for Linux for us to test.

**Comment by tristan957** [comment]
Gonna require the next point release of Electron I would assume, and possibly an upgrade to Electron 12 from VSCode's perspective because I am not sure if the feature will be backported. Best not to rush the VSCode maintainers :D.

**Comment by deepak1556** [comment]
> In some cases you may need to export GTK_USE_PORTAL=1 in your environment if your distro isn't doing it for you. I think it could make sense to start distributing Visual Studio Code with this environment variable set in the shell script that /usr/bin/code actually is. On systems where GTK is the xdg-desktop-portal backend, this will have no effect.
>
> I think this might be the script that needs to be changed? https://github.com/microsoft/vscode/blob/main/scripts/code.sh

@tristan957 change needs to be made in https://github.com/microsoft/vscode/blob/main/resources/linux/bin/code.sh, feel free to send a PR

**Comment by tristan957** [comment]
Cool. I'll do that later tonight. Thanks @deepak1556

**Comment by jonejkim** [comment]
> I have this problem as well (thunar opens instead of nemo, preferred app is nemo), but it also happens in Brave, so I'm not convinced it's a VS Code issue.

Just pitching in that I am experiencing the same issues on Manjaro Gnome. VSCode opens files in Thunar instead of Nemo when right clicked on file explorer item and click "Open Containing Folder". Other applications like Typora successfully opens with Nemo when taken equivalent action.

**Comment by cryzed** [comment]
@tristan957 did you end up doing this? I wasn't able to find your pull request.

**Comment by tristan957** [comment]
@cryzed totally forgot. I'll add it to my things to do, but it won't make a difference until VSCode builds against electron 14.

**Comment by cryzed** [comment]
@tristan957 that's okay - I'd just hate for this issue to get long feet and then get delayed until another electron version. Thank you!

**Comment by pyutil** [comment]
Same here, Debian+KDE+Dolphin. Thanks for future help.

**Comment by andreescocard** [comment]
Same here with mx linux

**Comment by owl-from-hogvarts** [comment]
I guess the main problem here is that vs code is officially distributed via snapcreaft, therefor running in sandbox environment and thus can't access xdg. I have heard that snapcraft presents `xdg portal` but does vs code use it?

**Comment by tristan957** [comment]
Flatpak and Snap both support the portals. VSCode is not being distributed with Electron 14, so VSCode does not use the portals.

**Comment by gusbemacbe** [comment]
> Flatpak and Snap both support the portals. VSCode is not being distributed with Electron 14, so VSCode does not use the portals.

Flatpak's VSCode still uses the GNOME 3 dialogue. I prefer the KDE dialogue.

**Comment by jlost** [comment]
Any estimates on Electron 14? What version is it currently using?

**Comment by owl-from-hogvarts** [comment]
> What version is it currently using?

electron 12 according to package.json

**Comment by towen** [comment]
Using `code_1.60.2-1632313585_amd64.deb` on Debian Sid with KDE (GNOME is not installed, but obviously GTK is) also installed `xdg-desktop-portal` and `xdg-desktop-portal-kde` and set `GTK_USE_PORTAL=1` but code **still** uses the 🤬 GNOME filepicker.

I just checked `/usr/share/code/resources/app/package.json` and it seems the latest Code 1.60.2 has been updated to use Electron `1.13.8` 😭
Is there any way to force it to use Electron 14.0.1 instead?

**Comment by aindriu80** [comment]
I'm running Pop OS! 21.04 and have Dolphin as my default file browser however VSCode uses the GNOME default file manager (Nautilus) that ships with GNOME instead.  It's very annoying, the GNOME default file is much less capable and has an emphasis on aesthetics over function, for example, I can't paste an address into the address bar (when using an extension) see screenshot.

![2021-11-30_10-22](https://user-images.githubusercontent.com/8885837/144029840-b14226ca-21cf-4242-89e6-ba93c2ba33ef.png)

**Comment by tristan957** [comment]
You need to wait for VSCode to ship with  Electron 14. It currently ships with 13.

**Comment by sbeve72** [comment]
When can we expect it to ship with Electron 14+

**Comment by gusbemacbe** [comment]
Hello!

cC: @aderchox, @aindriu80, @andreescocard, @atyshka, @chrisshyi, @cmpute, @cryzed, @davidpomerenke, @jlost, @madprops, @matrs, @michael-nhat, @Natetronn, @OverShifted, @owl-from-hogvarts, @pynkpanther, @saileshkush95, @shawnee247, @sylveon, @tomdavidson, @TomasAsadauskas, @towen, @ulziibat-n, @Yanpas.

Here is good news and a small and quick tutorial.

Congrats, @bpasero, @deepak1556 @tristan957! 

# Good news! 

Dolphin is working on VSCode Insiders 1.65 with Electron 16! See the image below:

![image](https://user-images.githubusercontent.com/2257024/153440021-9681d7cd-20e5-4bba-bc60-c39029ed0ceb.png)

# Tutorial

1. Install `xdg-desktop-portal` and `xdg-desktop-portal-kde`;
2. Open the terminal and run the commands:

    ```sh
   xdg-mime default org.kde.dolphin.desktop inode/directory
   xdg-mime default org.kde.dolphin.desktop inode/directory application/x-gnome-saved-search
   ```

3. Insert the option to the file `defaults.list`:

    ```sh
    echo "inode/directory=org.kde.dolphin.desktop" >> $HOME/.local/share/applications/defaults.list
    ```

4. Run the command `sudo nano /etc/environment` and insert `GTK_USE_PORTAL=1`;
5. Clean the caches, using BleachBit or Stacer;
6. Restart your computer.

**Comment by sylveon** [comment]
Please don't mass ping people like that. If they're interested in the issue they'll be watching it.

**Comment by runil** [comment]
I'm still having issues with this. If I'm running VSCode in a gnome session, it still uses Nautilus for its file dialog.

**Comment by gusbemacbe** [comment]
> I'm still having issues with this. If I'm running VSCode in a gnome session, it still uses Nautilus for its file dialog.

@runil, did you follow my tutorial above ([click here)](https://github.com/microsoft/vscode/issues/50386#issuecomment-1035081994)?

**Comment by tristan957** [comment]
Nautilus is not a file chooser. In GNOME, the file chooser is the GTK file chooser which is what is supposed to happen. Use KDE if you want the KDF file chooser.

**Comment by sbeve72** [comment]
@tristan957 it doesn't work on KDE either

**Comment by tristan957** [comment]
It indeed does work on KDE. You just have to set it up and be using VSCode insiders.

**Comment by runil** [comment]
> > I'm still having issues with this. If I'm running VSCode in a gnome session, it still uses Nautilus for its file dialog.
> 
> @runil, did you follow my tutorial above ([click here)](https://github.com/microsoft/vscode/issues/50386#issuecomment-1035081994)?

> It indeed does work on KDE. You just have to set it up and be using VSCode insiders.

Can confirm that this is the case for now. Does indeed work fine in KDE session using the Insider build. Still looking for a way to override the default file chooser in a Gnome session.

**Comment by ryan-ronnander** [comment]
Despite other applications working flawlessly with the KDE file picker in both OpenSUSE Tumbleweed and Ubuntu 20.04, I cannot get this to work for VSCode insiders.

**Comment by tristan957** [comment]
Make sure you have the environment variable GTK_USE_PORTAL=1 set

**Comment by ryan-ronnander** [comment]
> Make sure you have the environment variable GTK_USE_PORTAL=1 set

It is set in my environment, it is also set explicitly inside `code.sh`, relevant packages are installed (`xdg-*`, `kdialog`, etc). Firefox functions as expected in KDE while VSCode does not. Followed the tutorial commands posted above just in case they're needed and that didn't help either.

**Comment by tristan957** [comment]
Don't know what to tell you. It works for other people as evidenced by the thread. :(

**Comment by gusbemacbe** [comment]
@ryan-ronnander, doesn't my new tutorial work for you either?

**Comment by sbeve72** [comment]
> > Make sure you have the environment variable GTK_USE_PORTAL=1 set
> 
> It is set in my environment, it is also set explicitly inside `code.sh`, relevant packages are installed (`xdg-*`, `kdialog`, etc). Firefox functions as expected in KDE while VSCode does not. Followed the tutorial commands posted above just in case they're needed and that didn't help either.

Same here

**Comment by KucharczykL** [comment]
Can confirm it works on Arch Linux but doesn't work on Tumbleweed.

**Comment by zomp** [comment]
BTW, should it work on the regular (not Insider) release? It is Electron 17 already. It does not work on Kubuntu 21.10 to me.
