### ISSUE TITLE
Opening a new terminal or splitting an existing one always asks for cwd

### ISSUE THREAD

**Issue by costincaraivan** [Microsoft/vscode#50389]
**Steps to Reproduce:**

1. Open a terminal with ``workbench.action.terminal.new`` or ``workbench.action.terminal.split``

**What happens:**

1. Visual Studio Code asks for a working directory.

**What should have happened instead:**

1. Visual Studio Code just opens the terminal, since I already have: 
``"terminal.integrated.cwd": "/c/java"``  
in my settings.json.

This is quite annoying when working with a bigger number of terminals, especially if they're quite transient (you open one, do stuff, close it, open another one, etc.). In case anyone's wondering, this would be the kind of workflow you'd have in screen/tmux (from which I'm transitioning right now).

>  Version
>  1.23.1
> Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
> Date 2018-05-10T17:11:17.614Z
> Shell 1.7.12
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

Keybindings:

    {
        "key": "ctrl+shift+t",
        "command": "workbench.action.terminal.new",
        "when": "terminalFocus"
    },
    {
        "key": "ctrl+shift+-",
        "command": "workbench.action.terminal.split",
        "when": "terminalFocus"
    }

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Using these should solve your problem: `workbench.action.terminal.newInActiveWorkspace` and `workbench.action.terminal.splitInActiveWorkspace`

**Comment by costincaraivan** [comment]
Awesome!

Somewhat separate, is there a settings reference anywhere? The settings file doesn't have comments for the terminal.integrated.* settings 😢

**Comment by Tyriar** [comment]
_Settings_ should all have comments?

<img width="513" alt="screen shot 2018-05-24 at 9 37 12 am" src="https://user-images.githubusercontent.com/2193314/40499199-15bada9e-5f36-11e8-8fce-2258d8d5a6e2.png">

**Comment by costincaraivan** [comment]
You're right, my bad, I meant the commands 😕

**Comment by Tyriar** [comment]
Yes keybindings have no comments at the moment, we've talked about this in the team before 😃
