### ISSUE TITLE
Performance issue when saving

### ISSUE THREAD

**Issue by feco93** [Microsoft/vscode#50388]
Issue Type: <b>Performance Issue</b>

It's triggered by saving file. In developer tools there is a warning message about it:
WARN Aborted codeActionsOnSave after 750ms
After this warning message the intellisense doesn't working properly.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.69GB (2.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    98	167104	code main
    0	    74	112956	   shared-process
    0	   159	147336	   gpu-process
    0	   188	162632	   shared-process
    0	    75	170072	   shared-process
    0	   267	192272	   window (searchFields.service.ts - DyntellBI - Visual Studio Code)
    0	    11	187340	     electron-crash-reporter
    0	    41	187448	     searchService
   25	   279	193648	     extensionHost
    0	    40	140932	       electron_node jsonServerMain.js 
    0	   242	142548	       electron_node server.js 
    0	   187	176588	       electron_node electronForkStart.js tsserver.js 
    0	    33	192112	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    68	194588	       electron_node tslintServer.js 
    0	    14	194124	     watcherService 
    0	     9	194556	       console-window-host (Windows internal process)
    0	    32	195032	     terminal
    0	     6	167716	       winpty-process
    0	    10	 75024	         console-window-host (Windows internal process)
    0	    67	193820	         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     3	187592	           C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" start"
    0	    34	146080	             electron_node npm-cli.js 
    0	     3	182088	               C:\WINDOWS\system32\cmd.exe /d /s /c ng serve
    0	   827	194728	                 node   "C:\Projects\Web.BI\DyntellBI\node_modules\.bin\\..\@angular\cli\bin\ng" serve
    0	   250	193516	                   electron_node worker.js 
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (searchFields.service.ts - DyntellBI - Visual Studio Code)
|    Folder (DyntellBI): 2131 files
|      File types: json(531) ts(286) scss(120) html(85) sth(54) png(33) js(22)
|                  svg(22) log(22) old(16)
|      Conf files: launch.json(1) settings.json(1) package.json(1)
|                  tsconfig.json(1) tslint.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
path-intellisense|chr|1.4.2
gitlens|eam|8.3.2
EditorConfig|Edi|0.12.2
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
Angular2|joh|6.1.1
code-beautifier|mic|2.0.3
vscode-scss|mrm|0.6.2
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.4.3
typescript-hero|rbb|2.3.2
JavaScriptSnippets|xab|1.6.0
markdown-all-in-one|yzh|1.4.0

</details>

**Comment by Tyriar** [comment]
One or multiple of your extensions are taking too long, I don't think there's an easy way to identify which.
