### ISSUE TITLE
Only 32 fields in objects on debug

### ISSUE THREAD

**Issue by guitarhero1488** [Microsoft/vscode#50399]
I see only 32 object's field instead all on debug. So my object has 150 fields and some of that field has 150 fields as well, but I see only 32! Please, fix it, I'm so tired already :'(

**Comment by guitarhero1488** [comment]
up

**Comment by roblourens** [comment]
What are you debugging? If it's not node, please file this on the extension.

**Comment by guitarhero1488** [comment]
I'm sorry, I use xdebug and phpdebug extension

**Comment by roblourens** [comment]
Please file the issue on that extension, vscode doesn't restrict the number of properties coming from debug adapters.
