### ISSUE TITLE
TypeScript Language Service, getApplicableRefactors() won't be called if user is not selecting something

### ISSUE THREAD

**Issue by cancerberoSgx** [Microsoft/vscode#50392]
TypeScript Language Service plugin suggestions will never show up unless users have some text selected. 

If the user has not selected any text and requests refactor suggestions (ctrl-shif-f  or ctr-shift-p "Refactors...") vscode will always show "No code actions available" no matter if some plugin want's to suggest something in this situation.

Internally, the plugin's `getApplicableRefactors()` is never called if user has not selected some text so plugin implementations have no possibility to show suggestions in that scenario.

Since the signature of of that method is :

```typescript
function getApplicableRefactors(fileName: string, positionOrRange: number | ts.TextRange): ts_module.ApplicableRefactorInfo[] {
```
It's clear that the intention of the API is to show suggestions both when text is selected or not (notice `positionOrRange: number | ts.TextRange`

Steps to Reproduce:
Assume you have a TypeScript Language Service plugin that will always return a action in its getApplicableRefactors() implementation
1. Without selecting anything, trigger Refactors suggestions (ctrl-shif-f  or ctr-shift-p "Refactors...")

Expected behavior: the plugin suggestion is shown
Actual behavior: :"No code actions available" is shown

Does this issue occur when all extensions are disabled?: Yes

**Comment by cancerberoSgx** [comment]
Note: a workaround is using `getCodeFixesAtPosition` instead - that is called when user has no selection, but the API and semantics are different and could be insufficient for **refactor** implementations

**Comment by mjbvz** [comment]
Fixed in insiders I believe. 

Computing refactorings may be expensive, so we only request refactorings in the following:

* User has a selection
* User manually requests refactorings (this only happens in 1.24+, aka the current insiders builds)

**Comment by cancerberoSgx** [comment]
OK got it, thanks!, question, how would be the case when user doesn't request refactors automatically ? As far as I know user always has to perform an explicit action like ctrl-p or ctrl+shift+f  or search for "refactors... " ctrl+shipt+p ... Am I missing something ? are you talking about third party extensions exposing language service refactors programmatic ally ?  thank you very much sorry for the trouble.

**Comment by mjbvz** [comment]
Quick fixes are requested automatically when the cursor moves onto an error. We don't do this for refactorings because of the cost of computing them
