### ISSUE TITLE
Please place the icon in the center place

### ISSUE THREAD

**Issue by hangim** [microsoft/vscode#50393]
- VSCode Version: 1.23.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Install VSCode on Ubuntu
2. Add VSCode to left dock for the quick start
3. View /usr/share/code/resources/app/resources/linux/code.png

Does this issue occur when all extensions are disabled?: Yes

The VSCode icon **not** in the **center** place, the left margin is more than the right margin!

I know it's maybe by design but looks very uncomfortable, especially when placed with other software in the left dock.

![screenshot from 2018-05-24 20-12-36](https://user-images.githubusercontent.com/1856788/40484627-d8842d48-5f8e-11e8-8338-8dc8cc4c2ab3.png)

![screenshot from 2018-05-24 20-11-14](https://user-images.githubusercontent.com/1856788/40484577-a5eba4ce-5f8e-11e8-9484-4d76d97cd593.png)

**Comment by chryw** [comment]
@weinand I forwarded this to the original icon designer Matthieu (forgot his github id). I think he can help.
@misolori for visibility

**Comment by bpasero** [comment]
via https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#updated-visual-studio-code-icon
