### ISSUE TITLE
100% on all CPU by vscode-ripgrep/bin/rg process

### ISSUE THREAD

**Issue by mgcrea** [Microsoft/vscode#50396]
Very often while opening big NodeJS i've got a rogue `rg` process that go crazy and eat 100% CPU.

- VSCode Version: 1.23.1
- OS Version: OSX 10.13.4

Steps to Reproduce:

1. Open big NodeJS backend project
2. Wait for fans to blow
3. Open htop

```
11556 olivier    17   0 7939M 3393M ? 706. 20.7 18:20.43 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/node_modules/react-native/package.json --no-ignore --follow --quiet -- .
```

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
This is the react-native extension deciding whether you've opened a react-native project.

Related to https://github.com/Microsoft/vscode/issues/34711

You could also file an issue on the react-native extension asking whether they really need to search under `**` or just `/node_modules/react-native/package.json`
