### ISSUE TITLE
Unable to Debug Single PowerShell File

### ISSUE THREAD

**Issue by mbrinkho** [Microsoft/vscode#50397]
Issue Type: <b>Bug</b>

Right-click PS1 file in Explorer, choose "Open With Code."  Click Debug, menu to the right of green arrow says "No configurations."  Clicking the gear gives message "Please first open a folder in order to do advanced debug config..."  Seems to be the same behavior as https://github.com/Microsoft/vscode/issues/285 although that issue is closed.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (5.46GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Company\Server\Check-ServiceRemote.ps1|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.7.0
vscode-icons|rob|7.23.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This should work, but you can't use the gear icon which is for configuring a launch.json. Try clicking the green arrow button. If that doesn't work for your scenario, please file an issue on the Powershell extension.
