### ISSUE TITLE
Webview: very hard to resize editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5039]
For some reason our sash between editors is not clickable if you try to grab it from the web view side:
* have a web view in slot 2
* move with the mouse from slot 2 towards 1 to grab the resize handle
* you can only grab it when you are outside the web view

It does not seem to be related to the z-index, because the sash has a z-index of 100.

Any clues?

**Comment by jrieken** [comment]
I actually don't understand what you mean. It seems to me no different than with other editors. Need to see when we are both in

**Comment by bpasero** [comment]
@jrieken yup I can show you. I am seeing general issues with the fact that the webview seems to be on top of everything:
* for a normal editor (slot 2) I can click on the sash a few pixels left and right of the sash to grab and drag it but when the webview is there, I cannot click the sash as soon as my mouse enters the webview (in other words, the total clickable area for the sash is half compared to a normal editor where the sash is just on top of both editors left and right)
