### ISSUE TITLE
Conntect-MicrosoftTeams hangs in VSC but works with bare PS shell

### ISSUE THREAD

**Issue by CombineLabs** [Microsoft/vscode#50400]
- VSCode Version:1.23.1
- OS Version:Windos 10 Pro

Steps to Reproduce:

1. Install-Module -Name MicrosoftTeams -RequiredVersion 0.9.1
2. Connect-MicrosoftTeams (It works in bare PS Shell, non VSC)
3. If this needs to be moved to PowerShell Extension help, that would be fine

Does this issue occur when all extensions are disabled?: No (I only have PowerShell 1.7.0 installed

**Comment by weinand** [comment]
Please file this against the PowerShell extension.
