### ISSUE TITLE
Linux: File watcher limit does not seem to respect excluded folders

### ISSUE THREAD

**Issue by davidjoliver86** [Microsoft/vscode#50417]
- VSCode Version: 1.23.1
- OS Version: Kubuntu 18.04

I'm receiving the "Visual Studio Code is unable to watch for file changes in this large workspace" warning, but it seems like the file watcher is trying to watch for files in paths that I've specifically excluded. I work in a large Terraform codebase, so it's common to have thousands of temporary files within a `.terraform` folder.

Maximum number of files to be watched (default):
```
$ cat /proc/sys/fs/inotify/max_user_watches
8192
```
Number of files in my codebase *excluding* `**/.terraform/**`:
```
$ find | grep -v "\.terraform" | wc
   1565    1565   61582
```
Total number of files in my codebase *including* `**/.terraform/**`:
```
$ find | wc
  36527   36527 4146837
```
Excerpt of my settings that implies `**/.terraform/**` should be ignored by the file watcher:
```
"files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/.terraform": true,
        "**/.tox": true,
},
...
"files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/**": true,
        "**/.terraform/**": true,
        "**/.tox/**": true
},
```

While I am aware of the workaround mentioned here: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc, I don't believe this fix should be necessary. The watcher should be ignoring everything under a `.terraform` folder, thus I shouldn't be hitting the file watcher limit. I've even tried togging the experimental file watcher with no success.

Steps to Reproduce:

1. Start VS Code with lots of files under `.terraform`.
2. Observe warning message.
3. Clear out `.terraform` folders putting me back under the file watcher limit.
4. Warning message no longer appears.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Related/duplicate: https://github.com/Microsoft/vscode/issues/45295

**Comment by anoop-ananthan** [comment]
is there no solution to this problem? Hot-reloading will not work,  Nodemom won't work. All it has to do is not ignore watching files in `node_modules`. the solution in the above link doesnot work.

**Comment by acrixl** [comment]
same problem
files.watcherExclude  not working

debian buster/sid
**vscode: Code - OSS**
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-26T23:50:00.463Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by bpasero** [comment]
I cannot reproduce the steps from https://github.com/Microsoft/vscode/issues/50417#issue-326274277. My setup:
* have a folder `chokidar` on `~/Desktop`
* copy the contents of the vscode `node_modules` into the chokidar folder and call it `.terraform`
* configure `files.watcherExclude` to contain `"**/.terraform/**": true`
* open the folder -> no warning shows up
* remove the setting
* -> warning shows up

**Comment by loicgasser** [comment]
I can confirm that `files.watcherExclude` is also ignored on Ubuntu 16.04
here is the version I am running:
```
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:34:20.517Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by bpasero** [comment]
Does this still happen?
