### ISSUE TITLE
Can't view missing module name when path is too long

### ISSUE THREAD

**Issue by benlowry** [Microsoft/vscode#5041]
- VSCode Version:  0.10.11
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. start a project in a long path: eg /Users/accountname/work/my-project
2. require a file with the full path: var x = require(__dirname + "/file.js"),
3. launch your app and you'll get an exception with a character limit used up by the folder structure

![screen shot 2016-04-06 at 9 47 30 am](https://cloud.githubusercontent.com/assets/2373805/14323163/ab03e6e6-fbdc-11e5-91ba-af8032feee00.png)

Maybe the project's root directory could be truncated from the exception messages?

**Comment by weinand** [comment]
@benlowry in the April release we only truncate strings that are longer than 10000 characters.

**Comment by benlowry** [comment]
Is there a way to view the full exception message coming?  I can't get from the truncated version in my screenshot to the full detail - copying the value also copies the snipped version.
