### ISSUE TITLE
Conditional breakpoints: up/down to navigate through condition history

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode#50412]
Every time I use conditional breakpoints I use the same condition for a lot of breakpoints, or all breakpoints.

e.g.: In the chrome debug adapter core I want to debug the scriptParsed event for app.js, so I put several breakpoints to do this, and then I put a condition so that the breakpoints won't stop for files other than app.js

It'd be great if there was a way to set a global condition that applies to all breakpoints, or to all breakpoints or a single file, or to a set of breakpoints.

Regarding the UI: 
Maybe we could add a context menu on each file, and you can put a condition and breakpoints on that file only stop if that condition is true:
 
![image](https://user-images.githubusercontent.com/14098140/40505248-7a32f620-5f48-11e8-9ae5-65ccb9f0d632.png)

Or add an All Breakpoints line in the breakpoints widget where you can configure the condition for all breakpoints:
![image](https://user-images.githubusercontent.com/14098140/40505261-83587b4e-5f48-11e8-835d-9d7f84e57869.png)

**Comment by roblourens** [comment]
Another solution would be to have history in the breakpoint condition input box, where you can press the up arrow, just like in the console. That would make it a bit easier to reuse conditions.

**Comment by digeff** [comment]
Sometimes I want to refine the original condition after I added it. It'd be great if the different breakpoints shared the same condition identity, so I'd only need to update a single condition instead of one per breakpoint when I change it.

**Comment by isidorn** [comment]
I like @roblourens suggestion, that up / down would navigate condition history. 
Updating the global condition sounds too complex and a very specific use case imho. So we would not do that.

@digeff would the up/down arrows to go through history help at all in your use case?

**Comment by roblourens** [comment]
As a workaround you could set up global conditions yourself with a bp condition like `global.myCondition()` then in the debug console, define the condition with `global.myCondition = () => true` then you can edit the condition for all those BPs at the same time.

That's kind of a stretch but might be a useful hack in some cases.

**Comment by digeff** [comment]
I think that the up / down navigation will certainly help.

Would it be possible to also add telemetry to count how many times the user uses the exact same condition for different breakpoints? That way we'll know in the future if this is a scenario that customers care about or not.

**Comment by isidorn** [comment]
Renaming this issue to reflact the open / down arrow feature request which we might actually add.
We might consider adding telemetry but not for now.

In the meantime you can use @roblourens workaround
