### ISSUE TITLE
Unverified breakpoint, Breakpoint ignored because generated code not found (source map problem?)

### ISSUE THREAD

**Issue by rimoffall** [Microsoft/vscode#50428]
- VSCode Version:  1.23.1
- OS Version: 10.12.5
- debugger for chrome: 4.4.3

Steps to Reproduce:

## 1. case1 
<pre>{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/src"
        }
    ]
}</pre>
when i use this __launch.json__ to debug create-react-app,the breakpoint is gay circle and show "Unverified breakpoint, Breakpoint ignored because generated code not found (source map problem?)."
## 2.case2
<pre>{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/src"
            "breakOnLoad": true,
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "*": "${webRoot}/*"
              },
        }
    ]
}</pre>
when i use this  __launch.json__ debugging create-react-app,the breakpoint is gay circle and show "Unverified breakpoint, Breakpoints set but not yet bound"

when run .scripts in Debug Console, both cases show "
› extensions::app
› http://localhost:3000/static/js/bundle.js"

Does this issue occur when all extensions are disabled?: Yes/No
yes
#

**Comment by roblourens** [comment]
Thanks for posting `.scripts` output. It implies that bundle.js doesn't have a sourcemap, otherwise it would write the details of the sourcemap.

Can you debug your original sources in chrome devtools?
