### ISSUE TITLE
Add a task type to wait for other task

### ISSUE THREAD

**Issue by Kronuz** [Microsoft/vscode#50422]
# Feature Request

A new feature request to add a task type to wait for some other running task.

## Purpose
The purpose of the feature is to support the scenario where one needs to debug server *and* client code at the same time by using a compound.

## Use Case

In our scenario, the server needs to be compiled prior launching its debug session (via a “Build Server” task), and you can use `preLaunchTask` for that; however the client launches immediately and there is no easy way to make it wait for the “Build Task” started by the server to end. The usecase would be to also add a preLaunchTask to the client (of this new type) to wait for the other task “Bbuild Task”) to end.

## Alternatives

Maybe some other way to wait for a port to be open and ready, so the client being launched waits for the server to start listening to it.

**Comment by dbaeumer** [comment]
There is the concept of `dependsOn`. You can do:

```typescript
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "echo",
			"type": "shell",
			"command": "echo Hello` World"
		}, {
			"label": "compound",
			"dependsOn": [ "echo" ],
			"problemMatcher": []
		}
	]
}
```

Please ping if this doesn't fulfill your request.
