### ISSUE TITLE
Auto-import doesn't import from vscode-debugadapter correctly

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50423]
- Clone https://github.com/microsoft/vscode-chrome-debug-core
- Open chromeDebugAdapter.ts
- Remove 'logger' from the vscode-debugadapter import statement
- In this case, it knows that `logger` can be imported from vscode-debugadapter

![image](https://user-images.githubusercontent.com/323878/40502441-d6244b54-5f3f-11e8-9f31-921ceacb23fa.png)

- Delete the entire vscode-debugadapter import
- Now it does not suggest importing `logger` from `vscode-debugadapter`

![image](https://user-images.githubusercontent.com/323878/40518096-a1b93a22-5f6d-11e8-88ba-8f5074192717.png)

The package has `"typings": "./lib/main"`, maybe we just need to set something up differently?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24604
