### ISSUE TITLE
Multiple Additive Drag for Multi Cursor

### ISSUE THREAD

**Issue by sliceofbytes** [microsoft/vscode#50421]
Feature Request
------------------

Additive Drag for Multiple Selection - Basically Sublime's `Ctrl + Middle Mouse + Drag (Windows)`

This allows you to make additive multi cursor selection. Basically create another multi cursor selection without losing the first.

**Comment by iansan5653** [comment]
Ideally this would be <kbd>alt</kbd> + `middle mouse button`. It's definitely something missing from the new column selection feature.

**Comment by iansan5653** [comment]
@alexandrudima I might be interested in submitting a pull request for this feature. Can you direct me to the relevant area of the code?

**Comment by sliceofbytes** [comment]
I'm not sure where the relevant code would be.
