### ISSUE TITLE
[html] auto-generate JSDoc comments for embedded JavaScript functions

### ISSUE THREAD

**Issue by jjloneman** [microsoft/vscode#50420]
- VSCode Version: 1.22.2
- OS Version: Windows 7 x64

Steps to Reproduce:

1. In an embedded `<script>` tag in an HTML page, create a plain ES5 JavaScript function, like `function printName(name) { }`, and above it, type `/**` and press `Enter`.
2. It won't generate the JSDoc.

Additionally, it would be nice if this could be enabled for any `<script>` tag embedded in other file formats. For example, I frequently have to edit classic `.asp` pages and `.csp` (Caché Server Pages) files, for which I set the default file associations to be `HTML`, so that it does syntax highlighting for both HTML and JavaScript in the files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by watfordgnf** [comment]
@mjbvz if this is out of scope for the vscode repo, which repo should this be migrated to/opened on?

**Comment by mjbvz** [comment]
This issue was open for a year and only got two upvotes during that time. We have no plans to address it at this time given the limited community feedback

See https://github.com/microsoft/vscode/wiki/Issue-Grooming
