### ISSUE TITLE
Salsa does not warn undeclared variable

### ISSUE THREAD

**Issue by WangJi** [Microsoft/vscode#5042]
Before Salsa was implemented, when I write like this without define `foo`:
```javascript
console.log(foo);
```
VS code can give a hint warning that  `the variable foo is not defined`

While after update to 0.10.11,  salsa won't do this. How can I get this feature back?

PS: The ts server I'm using is `1.9.0-dev.20160128`

**Comment by egamma** [comment]
@WangJi the recommendation is to use a linter like eslint pls see https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/vFebruary.md#linters

**Comment by WangJi** [comment]
Got it.
I didn't read the update log carefully.
