### ISSUE TITLE
Allow split editor keyboard shortcut for horizontal and vertical

### ISSUE THREAD

**Issue by imoby** [Microsoft/vscode#50431]
Currently the only keyboard shortcut for split editor is cmd/ctrl+\ which splits the editor. However, it would be nice to have the ability to have separate key bindings for horizontal and vertical split editors. For example, cmd/ctrl+\ can be the default split view and shift + cmd/ctrl + \ could be the remaining one.

**Comment by bpasero** [comment]
This landed as part of https://github.com/Microsoft/vscode/issues/14909#issuecomment-393870565

New commands to split into any direction:
* `workbench.action.splitEditorUp`
* `workbench.action.splitEditorDown`
* `workbench.action.splitEditorLeft`
* `workbench.action.splitEditorRight`
