### ISSUE TITLE
AppVeyor link is broken in testing-extensions docs

### ISSUE THREAD

**Issue by kokororin** [Microsoft/vscode#50430]
Doc Link: https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-on-windows-with-appveyor

Broken Link:
You can also run extension tests on Windows with AppVeyor. To get started, you can review the VS Code integration tests AppVeyor [configuration file](https://github.com/Microsoft/vscode/blob/master/appveyor.yml).

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1635
