### ISSUE TITLE
Markdown: preview icon does not match split icon

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50438]
Check this:

![image](https://user-images.githubusercontent.com/900690/40533855-535a9046-6004-11e8-8034-54af0109df29.png)

It seems to me the colors in the markdown icon are not the same as in the split icon. Ideally both would match in light and dark theme.

/cc @misolori

**Comment by bpasero** [comment]
Also, I cannot really explain why, but the first icon looks 1px more to the top compared to the other, even though both seem to be perfectly aligned. Maybe this is actually triggered by using different colors but not sure.

**Comment by misolori** [comment]
The split icon fill color is `#656565`, the markdown preview icon is `#424242`.

And yes, @bpasero, that first icon is taller by 1px on both sides. I could reduce the size so it matches the vertical spacing of the rest of the toolbar icons.
![image](https://user-images.githubusercontent.com/35271042/40551229-33aa3cdc-5ff1-11e8-8ee4-9f9e33c41d9c.png)

**Comment by bpasero** [comment]
@misolori I think it would be good to have a consistent set of icons for at least the extensions that we ship with. Of course we cannot easily enforce that for other extensions 👍

**Comment by misolori** [comment]
@bpasero I think we could definitely do that, I'll add that to my list of icon changes/updates.

/cc @chryw
