### ISSUE TITLE
Keeping arrow down in editor is not very fluid

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5043]
When I have a larger markdown file (or any file) and I press and hold arrow down to scroll down, I see some issues:
* CPU goes up to 30% which seems weird for such an operation
* the selection highlighter updates very hectic (this explains the CPU spike)
* the whole scrolling noticably slows down and is not very snappy

I wonder if selection highlight and find match highlight should update buffered in this case to make the scrolling fluid and less UI hectic.

![untitled](https://cloud.githubusercontent.com/assets/900690/14326280/96186dbe-fc2d-11e5-8183-0ca94eb097fa.gif)

**Comment by alexandrudima** [comment]
@bpasero Nice catch! I've tested the arrow down with my perf testing, but I did it in a large TypeScript file. Since TypeScript has rich find occurrences, the selection highlight does not kick in (as it does for markdown).

**Comment by alexandrudima** [comment]
Doing it 2000 times (at each animation frame):

Before:
![image](https://cloud.githubusercontent.com/assets/5047891/14390495/ac7daab6-fdb7-11e5-8220-5d8093daeac0.png)

After:
![image](https://cloud.githubusercontent.com/assets/5047891/14390504/bc859cfc-fdb7-11e5-9e0f-d7f9d46fecfe.png)


[AFTER.cpuprofile.txt](https://github.com/Microsoft/vscode/files/210514/AFTER.cpuprofile.txt)
[BEFORE.cpuprofile.txt](https://github.com/Microsoft/vscode/files/210513/BEFORE.cpuprofile.txt)

**Comment by bpasero** [comment]
Nice!
