### ISSUE TITLE
内容包含有中英文时，无法Tab对齐。

### ISSUE THREAD

**Issue by Rushing0711** [Microsoft/vscode#50439]
Issue Type: <b>Bug</b>

内容包含有中英文时，无法Tab对齐。

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.77GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Rushing\Resources\Linux\Learning\Linux学习笔记【重构版】.txt|
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

**Comment by Roger-WIN** [comment]
Please use English to feedback. And paste a screenshot at least.

**Comment by Roland0511** [comment]
Same problem, the width of two Chinese characters should be equal to four English characters.
"editor.fontFamily": "Consolas, 'Courier New', monospace",

![tim 20180531105825](https://user-images.githubusercontent.com/588050/40758788-96f50dc4-64c1-11e8-98a5-2d3be6927d75.png)

**Comment by Rushing0711** [comment]
Think you, I'll try it.




| |
李明
邮箱：liming20110711@163.com
|

签名由 网易邮箱大师 定制

在2018年05月31日 11:04，lizhou.zhu 写道：

Same problem, the width of two Chinese characters should be equal to four English characters.
"editor.fontFamily": "Consolas, 'Courier New', monospace",

**Comment by Roland0511** [comment]
also you can see this:
https://www.minifish.life/2017/12/26/font.html

**Comment by Rushing0711** [comment]
Ok！Think very much.




| |
李明
邮箱：liming20110711@163.com
|

签名由 网易邮箱大师 定制

在2018年05月31日 11:34，lizhou.zhu 写道：

also you can see this:
https://www.minifish.life/2017/12/26/font.html

**Comment by rebornix** [comment]
Close as it's not a Code issue, thanks all for your help.
