### ISSUE TITLE
Microsoft.VSCode.CPP.Extension.darwin eat cpu on mac

### ISSUE THREAD

**Issue by sunnyawake5** [Microsoft/vscode#50433]
vscode: 1.23.1
macos: 10.13.4

**Comment by weinand** [comment]
duplicate of https://github.com/Microsoft/vscode-cpptools/issues/2036

**Comment by sean-mcmanus** [comment]
@sunnyawake5 We've found/fixed a deadlock that can lead to infinite CPU usage (i.e. "livelock"): https://github.com/Microsoft/vscode-cpptools/issues/2043 . We'll try to release an update soon.

**Comment by duzhen16** [comment]
@sean-mcmanus This extension is very nice to use except causing high CPU usage, could you please fix this bug as fast as you can ? Thank you

**Comment by weinand** [comment]
@duzhen16 you've just added a comment meant for the cpp extension in the wrong place.
This is the VS Code repository. Your comment really should go to https://github.com/Microsoft/vscode-cpptools/issues/2043

**Comment by sean-mcmanus** [comment]
@duzhen16 The bug I mentioned was fixed with 0.17.4. If you're experiencing other issues still, please file an issue with repro details at https://github.com/Microsoft/vscode-cpptools/issues .
