### ISSUE TITLE
Command to open next file with changes in diff view

### ISSUE THREAD

**Issue by CombeeMike** [Microsoft/vscode#50434]
I tend to quickly review all changes before committing them. Doing this solely via keyboard works quite well e.g. in IntelliJ but currently doesn't so much in VSCode.

Here's my current workflow and where it's "broken":

1. Show all changes via command `Show SCM`, <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>m</kbd>
2. <kbd>tab</kbd> to focus list with changed files
3. <kbd>down</kbd> to to select first file in list
4. <kbd>enter</kbd> to open the diff view
5. Use command `workbench.action.compareEditor.nextChange` (<kbd>alt</kbd>+<kbd>down</kbd>) to navigate through all changes within the file

Open next file in diff view:

6. Close current diff view via <kbd>ctrl</kbd>+<kbd>f4</kbd>
7. Go back to changes view via `Show SCM`, <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>m</kbd>
8. <kbd>tab</kbd> to focus list with changed files
9. <kbd>down</kbd> to select next file in list
10. <kbd>enter</kbd> to open the diff view
11. Review changes -> Back to point 5

Points 6 to 10 are very cumbersome, especially since `Show SCM` sets focus to the text input which forces me to use <kbd>tab</kbd> & <kbd>down</kbd> to get back to the changes list...

The perfect thing would be a command like `workbench.action.compareEditor.openNextFileWithChanges` which would replace points 6 to 10:

6. Command `workbench.action.compareEditor.openNextFileWithChanges` shows the changes of the next file from the changes list in the currently open diff view (or opens new one if none is open)
7. Review changes -> Back to point 5

**Comment by CombeeMike** [comment]
Is it possible to achieve this with an extension?
I've not written any extensions so far but am willing to take a shot.

I'm asking beforehand because I don't want to investigate time only to find out down the road that there's a technical roadblock...

**Comment by alexandrudima** [comment]
@joaomoreno I am not sure where this could be implemented, in the SCM viewlet UI, or perhaps in the SCM extension directly. Giving to you for ideas...
