### ISSUE TITLE
 cann't input chinese by ubuntu!!!

### ISSUE THREAD

**Issue by kekxv** [Microsoft/vscode#50436]
Issue Type: <b>Bug</b>

 cann't input chinese by ubuntu!!!

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz (4 x 2443)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (2.60GB free)|
|Process Argv|/snap/vscode/37/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.23.5
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.17.3

</details>

**Comment by Tyriar** [comment]
What happens when you try and what IME are you using? Does it work in the editor or terminal?
