### ISSUE TITLE
Vscode Terminal Context Aware colors [ stderr ]

### ISSUE THREAD

**Issue by jeyanthimuthuram** [Microsoft/vscode#50437]
- VSCode Version: Version 1.22.2 (1.22.2)
- OS Version: MacOSX

Suggestion:
              * vscode can identify programming errors  `python err , java err`  and show them in different colors ( or atleast stderr can be shown in different color )
             * An additional flag to toggle it would be much nicer :)

**Comment by Tyriar** [comment]
No plans to do this, see https://github.com/Microsoft/node-pty/issues/71 for a discussion
