### ISSUE TITLE
Files in open editors dissappear.

### ISSUE THREAD

**Issue by qwordy** [Microsoft/vscode#50443]
Issue Type: <b>Bug</b>

Files in open editors dissappear.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|20, 23, 13|
|Memory (System)|8.00GB (0.96GB free)|
|Process Argv|/private/var/folders/dc/fvq5crxd0mj7kyjx_7jn487jnjvfwn/T/AppTranslocation/82EDC85D-CF4A-4637-8189-FA15951EF0B0/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
I don't understand?
When do they disappear? 
Please provide detailed steps for how to reproduce this.

**Comment by qwordy** [comment]
![vscodebug](https://user-images.githubusercontent.com/5019528/40599386-7c2a0984-627f-11e8-9eab-70d1f8b535a7.png)
Sorry for not providing details before. The problem occurred again today. The 'OPEN EDIRTORS' suddenly became empty after I opened some files from left bottom directory view. It is the same project(directory) as 3 days ago. Restarting vscode can fix. I never encounter this bug in other projects and in other platforms' vscode. Maybe it has something to do with file content opened.

**Comment by isidorn** [comment]
We have rewritten the open editors view to handle the grid layout so it would be great if you can try with vscode insiders in a week.
Apart from that if you F1 > developer tools > look at the console are there any errors?
