### ISSUE TITLE
Git: sidebar file tree doesn't highlight changed files

### ISSUE THREAD

**Issue by alexdevero** [Microsoft/vscode#50444]
Issue Type: <b>Bug</b>

1) Change file in the workspace
2) Observe changes in the sidebar file tree

- File in the sidebar file tree is not highlighted as changed.
- Code in file is highlighted as it should.

VS Code version: Code - Insiders 1.24.0-insider (eed12c19a5ece4d7d1d3276eef89e335a3ec1497, 2018-05-25T05:17:05.420Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.50GB free)|
|Process Argv|E:\Programs\Documents\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
language-postcss|cpy|1.0.5
vscode-svgviewer|css|1.4.4
EditorConfig|Edi|0.12.2
vsc-material-theme|Equ|2.1.0
auto-close-tag|for|0.5.6
wordcounter|kir|1.2.2
contextualduplicate|laf|0.2.0
vscode-language-babel|mgm|0.0.14
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.2.2
vscode-duplicate|mrm|1.2.1
vscode-icons|rob|7.23.0
code-settings-sync|Sha|2.9.2
code-spell-checker|str|1.6.10
code-spell-checker-czech|str|0.1.0
dictionary-completion|yzh|0.6.1
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
> Change file in the workspace

What do you mean by this?

Also, can you share a screenshot?

**Comment by alexdevero** [comment]
Git seems to be working now.

What do you mean by this? - change some file in the folder to let git detect the change.

**Comment by joaomoreno** [comment]
OK. Closing the issue for now then. If it comes back try to reproduce and provide specific steps. Thanks!

**Comment by superandrew213** [comment]
I'm seeing this as well. On the sidebar file/folder is not highlighted if file has been changed.

Sidebar highlight only shows when file is opened in editor and has an eslint error.

**Comment by elizalc** [comment]
Same happens to me. I add this to vs code configuration to enable git highlights and badges and it works.
`
"explorer.decorations.badges": true,
"explorer.decorations.colors": true,
`

**Comment by superandrew213** [comment]
I have those settings turned on already but it's not working.
