### ISSUE TITLE
Auto switches to output window when in terminal

### ISSUE THREAD

**Issue by raldred** [Microsoft/vscode#50440]
Issue Type: <b>Bug</b>

I'm typing in the terminal, something happens to my code in the background and the VScode integrated terminal switches to the output window, it does it all the time, when scss intellisense writes output

"[Error - 11:30:05] (node:1490) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'getTime' of undefined"

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
project-manager|ale|0.25.2
vscode-color|ans|0.4.5
better-toml|bun|0.3.2
solargraph|cas|0.17.3
vscode-quick-select|dba|0.2.5
gitlens|eam|8.3.2
rspec-snippets|kar|0.0.3
dotenv|mik|1.0.1
vscode-scss|mrm|0.7.0
python|ms-|2018.4.0
azure-account|ms-|0.4.0
Go|ms-|0.6.80
vsliveshare|ms-|0.3.198
debugger-for-chrome|msj|4.4.3
rails-run-spec-vscode|nok|0.1.2
heroku-command|pko|0.0.8
vscode-css-peek|pra|2.1.0
Ruby|reb|0.18.0
sass-indented|rob|1.4.9
Align|ste|0.2.0
vscode-import-cost|wix|2.7.1

</details>

**Comment by Tyriar** [comment]
One of your extensions is probably causing this.
