### ISSUE TITLE
ProblemMatcher related information feature request

### ISSUE THREAD

**Issue by tksuoran** [Microsoft/vscode#50447]
I use custom problem matcher. It has regexp, file, line, column, severity, message. It works, but I am missing out related information.; March 2018 release notes gave impression that problems can have "related information". I have this related information, but I think I currently cannot feed this to problems in VSCode, at least problemMatcher does not seem to have this functionality. Or can it?

I have the source information in .json, so one option would be to provide a way to feed this to problems more directly, instead of using regexp based problemMatcher.

**Comment by dbaeumer** [comment]
Correct. Related information can only be added to a problem using the API right now.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/55253
