### ISSUE TITLE
.tsconfig.json not working

### ISSUE THREAD

**Issue by qawsqs** [Microsoft/vscode#50442]
- VSCode Version: 1.23.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. code --disable-extensions

2. Create .tsconfig.json in project root: ![tsconfig](https://i.imgur.com/QEU3wZu.png)

3. Create ./src/test.js: ![test](https://i.imgur.com/DgVWIaL.png)

Result: type checking not working

Expected Result: check types as with // @ts-check: ![tscheck](https://i.imgur.com/onEI8xr.png)

**Comment by spitWind** [comment]
try it by jsconfig.json?

**Comment by qawsqs** [comment]
My bad, there should be not dot in front of `tsconfig.json`
