### ISSUE TITLE
Test: Grid - Open Editors View

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50459]
Refs: https://github.com/Microsoft/vscode/issues/14909
Complexity: 3

- [x] any os @ramya-rao-a 
- [x] any os @joaomoreno 

**Builds:** See https://github.com/Microsoft/vscode/issues/50458

With the introduction of grid layout, the "Open Editors" view is now reflecting the new layout and many changes went into that need testing.
Assign issues to @isidorn

**Verify:**
* the view works as before, except for the fact that groups now carry a number instead of a fixed position
* the view always reflects what is going on in the grid layout
* active editor is always focused in the open editors group
* you can use all commands of the context menu (single / multi select) both for editor and groups
* you can use all commands of the toolbar
* you can DND editors between Open Editors view, Editor part and the explorer

**Comment by rwatts3** [comment]
I would love to participate in testing, 

are there any instructions on how to test and provide feedback ?

**Comment by bpasero** [comment]
@rwatts3 thanks for the offer, I will announce this in https://github.com/Microsoft/vscode/issues/14909 once we started test week next week.
