### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by masonicboom** [Microsoft/vscode#5045]
I'm interested in support for printing out code files.

Is there a way to cause the editor to render the full file into the DOM (as opposed to only the visible set of rows)? That seems like the main hurdle.

**Comment by alexandrudima** [comment]
This can be somewhat achieved by copying and pasting into a software that can accept HTML from the clipboard e.g. Word

**Comment by mjbvz** [comment]
Duplicate of #5953
