### ISSUE TITLE
Auto find close </div> when click <div> 

### ISSUE THREAD

**Issue by phyphy** [Microsoft/vscode#50452]
- VSCode Version: 1.23.1
- OS Version: Windows 10

Steps to Reproduce:

1. If click `<div>` should not highlights all `<div>` or `</div>`
2. Just highlights close `</div>` where related `<div>` who clicked for easy to find where close place, like sublime

I hope next update will fix it, thanks.

**Comment by aeschli** [comment]
I assume that's when in a PHP file. Duplicate of #2915.

Fix is to use the Intelliphense extension, or file an issue against the PHP extension that you use.
