### ISSUE TITLE
Parameter hints do not disappear

### ISSUE THREAD

**Issue by lishine** [Microsoft/vscode#50467]
Issue Type: <b>Bug</b>

Still show up hints with parameter and function types as I hover over the code!
Please suggest what I can do. Thanks!

Clean install and only the bellow config:
```
{
    "editor.matchBrackets": false,
    "editor.parameterHints": false,
    "javascript.format.enable": false,
    "javascript.implicitProjectConfig.checkJs": false,
    "typescript.implementationsCodeLens.enabled": false,
    "debug.internalConsoleOptions": "neverOpen",
    "javascript.validate.enable": false,
    "typescript.validate.enable": false,
    "debug.showInStatusBar": "never",
    "debug.hideActionBar": false,
    "debug.openDebug": "neverOpen",
    "typescript.suggestionActions.enabled": false,
    "javascript.suggestionActions.enabled": false
}
```
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.86GB (3.49GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by usernamehw** [comment]
```javascript
"editor.hover": false,// reload the editor
```

**Comment by lishine** [comment]
Cool ! It works!
But...it turns off many useful hints.
What I actually want to turn off - is all these types hints...

**Comment by lishine** [comment]
Not see:
Hover over a function or parameter or method or import. It shows (function) or (parameter) or (alias) or (method) :any etc.

See:
Hover over a warning. In settings over a setting

**Comment by roblourens** [comment]
This is tracked by https://github.com/Microsoft/vscode/issues/30114, there isn't a good way to do this currently. You can disable the builtin Typescript/Javascript extension if you don't want any TS language features.
