### ISSUE TITLE
Missing `workbench.action.debug.clear` command

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#50461]
There's a button for clearing the debug console, there's a command for clearing the terminal, but there isn't a command for clearing the the debug console.

Ideally there should be a command for every single one of those little buttons.

**Comment by roblourens** [comment]
This exists, it's called `workbench.debug.panel.action.clearReplAction`

**Comment by fabiospampinato** [comment]
Oh nice, thanks! I couldn't find it reading `keybindings.json`.

**Comment by LAITONEN** [comment]
But still, there is no **command** to clear the debug console. In Chrome Console there is **clear()**. I expected to have the same here, but it does not work, even though when I execute **clear**, it shows that there is such function declared.
<img width="749" alt="screen shot 2018-06-03 at 3 26 58 pm" src="https://user-images.githubusercontent.com/23742868/40886541-96098902-6742-11e8-859a-9c5bcf097272.png">

**Comment by roblourens** [comment]
Filed https://github.com/Microsoft/vscode-debugadapter-node/issues/185 for that @LAITONEN
