### ISSUE TITLE
Folding is broken 

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#50462]
VSC: v1.23.1

I see lines disappearing, and sometimes the gutter is filled with "undefined":

![kapture 2018-05-25 at 17 12 29](https://user-images.githubusercontent.com/1812093/40552014-dbd39352-603e-11e8-9784-7003c5ae2662.gif)

It's not showcased in this GIF but sometimes the buttons for folding the lines are misplaces by one line or something, and clicking them does nothing.

I also had this problem in v.1.23.0.

**Comment by aeschli** [comment]
I tried to reproduce this this with content from https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/statusbars/statistics.ts#L119 but was not able.

Can you provide the content of the file where you see this?
Any special settings? Can you test if that reproduces without extensions?

**Comment by fabiospampinato** [comment]
> I tried to reproduce this with content from https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/statusbars/statistics.ts#L119 but was not able.
> Can you provide the content of the file where you see this?

That's exactly the file I was using in the gif, but I can reproduce it with anything long enough basically.

I think the trick is scrolling all the way to the bottom and then folding something.

> Can you test if that reproduces without extensions?

I can reproduce it without extensions.

> Any special settings? 

I couldn't reproduce it without this:

```json
{
    "editor.scrollBeyondLastLine": false
}
```

---

Here's a screenshot of the other issues I mentioned (`undefined` in the gutter, misplaced folding buttons), I'm not sure how to reproduce those, sometimes they happen, sometimes they don't.

<img width="864" alt="screen shot 2018-05-28 at 12 41 27" src="https://user-images.githubusercontent.com/1812093/40611092-421366a0-6275-11e8-979a-06712c6b49cc.png">

**Comment by alexandrudima** [comment]
Let's track in #50296
