### ISSUE TITLE
[UI] Improve look / overall experience of search

### ISSUE THREAD

**Issue by garygreen** [Microsoft/vscode#50464]
Currently the searching of code feels unintuitive as compared to alternative editors like Sublime Text and Atom (see below for comparison).

### Sublime

![sublime-search](https://user-images.githubusercontent.com/1702638/40552449-97807050-6037-11e8-9782-f16afb7da554.PNG)

### Atom

![atom search](https://user-images.githubusercontent.com/1702638/40553303-18a2120e-603a-11e8-8dfe-23e6dfd62412.PNG)

### VS Code
![vscode search](https://user-images.githubusercontent.com/1702638/40552451-99c50970-6037-11e8-8e98-1421da7b531f.PNG)

Areas which could be improved:

- [ ] Add line numbers
- [ ] Show "context" lines above and below (possibly configurable, as Atom does)
- [ ] Keep formatting/indentation when showing context lines
- [ ] More liberal spacing, makes it easier to glance and scan through results. Everything feels too bunched up at the moment
- [ ] Use the same font as the main code window
- [ ] Add option to show results in a new window (rather than forcing it into a pane which can be fiddly to use and restricts you to performing and seeing results for only one search)

It would be great to see search get more love and attention 😄

**Comment by roblourens** [comment]
Thanks for the feedback. I think all of these suggestions are covered by existing feature requests.

- Line numbers: https://github.com/Microsoft/vscode/issues/10085
- Context lines: https://github.com/Microsoft/vscode/issues/18791
- Using the monospaced font we tried once and it was not popular

etc

All of these are things I'd like to address some day. We have tons of exisitng search feature requests: https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afeature-request+label%3Asearch
