### ISSUE TITLE
Files with .es6 suffix are treated as TypeScript files

### ISSUE THREAD

**Issue by jbutz** [Microsoft/vscode#5046]
- VSCode Version: 0.10.11
- OS Version: OS X El Capitan v 10.11.4

Steps to Reproduce:

1. Create a new file with the extension `.es6` and the following code
   ```javascript
   class Testing {
       constructor() {
           this.myValue = "Hello World";
       }
       
       test() {
           return this.myValue;
       }
   }
   ```
2. The Language Mode is automatically set to "JavaScript", but on `this.myValue` you get `Property 'myValue' does not exist on type 'Testing'` errors.
3. Close the file and rename it to use a `.js` extension
4. Open the file and notice that the errors are gone

**Comment by egamma** [comment]
What is happening is that VS Code registers `.es6` files as JavaScript files and Code sends them over to the tsserver. Inside the tsserver `.es6`are not treated as JavaScript files but as TypeScript files. For this reason you get the additional errors. 

One work around is to disable the error diagnostics from the tsserver for js files: `"javascript.validate.enable": false`

Moving to TypeScript, there needs to be a way to configure that `.es6` files should be treated as JavaScript files.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7926
