### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by maaudrana** [Microsoft/vscode#50463]
Hallo
I am a graphics designer who wants to make logo for this projects.if you have any requirements then let me know.its totally free for open source projects.
Thank you

**Comment by TomasHubelbauer** [comment]
The VS Code logo has [quite a history](https://code.visualstudio.com/blogs/2017/10/24/theicon) and the current logo designers probably got it handled now. :-)

**Comment by chrisdias** [comment]
Hello @maaudrana -

Thanks for the offer! However, @misolori recently joined the VS Code team as our designer, and we think he's doing a great job :-).  

So, I think we're all set for now.
