### ISSUE TITLE
Ctrl+click randomly stops working

### ISSUE THREAD

**Issue by misterjunio** [Microsoft/vscode#50468]
Issue Type: <b>Bug</b>

I am working on a C/C++ project. After my project window is open for some time ctrl+click no longer goes to any variable/function definition, instead a blue "loading" bar appears on top of the editor forever. Closing the window and opening the project in a new one solves it. Sorry, I know this is really hard to reproduce but maybe you have some idea why it might happen..

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
cpptools|ms-|0.17.3

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
