### ISSUE TITLE
Source Control selector interferes with Git provider options

### ISSUE THREAD

**Issue by OwenGr** [Microsoft/vscode#50473]
![image](https://user-images.githubusercontent.com/12298985/40558836-d84d8328-6011-11e8-9c01-8fe85fee2eb1.png)

The ellipsis that appears on the SOURCE CONTROL: GIT line is always visible and appears just above the ellipsis that appears when hovered over on the header immediately below. This is confusing and leads to misclicking when attempting to interact with the git options 'commit, sync, more'. It seems to me that it's much less common for someone to install multiple SCM providers on a regular basis than to work with the git options, so the Source Control ellipsis should be removed from the UI here and placed somewhere less common. 

- VSCode Version: 1.23.1
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Open a project.
2. Go to the Source Control tab.
3. Hover mouse over PROJECT NAME GIT. Notice two ellipsis next to each other, as in the image above.
4. Accidentally click on the wrong one and have to click away before re-accessing the menu.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gintsgints** [comment]
Configurable option to remove that bar, could be solution.

**Comment by gintsgints** [comment]
Confirm, it is solved at latest VSCode version. Both buttons now are together.

**Comment by joaomoreno** [comment]
👍
