### ISSUE TITLE
there is no way to open code-insiders at a certain folder with --diff parameter

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#50470]
what i tried:
- code-insiders ./ --diff ./.dev/scripts/src/linting/no-loops-in-imports.ts scripts/src/linting/no-loops-in-imports.ts
- code-insiders --diff ./.dev/scripts/src/linting/no-loops-in-imports.ts scripts/src/linting/no-loops-in-imports.ts --add ./
- code-insiders --diff ./.dev/scripts/src/linting/no-loops-in-imports.ts scripts/src/linting/no-loops-in-imports.ts ./

nothing works

**Comment by bpasero** [comment]
@aleksey-bykov are you trying to compare the same file with itself maybe?

**Comment by aleksey-bykov** [comment]
no files are different

**Comment by bpasero** [comment]
@aleksey-bykov does it reproduce in our stable release too?
