### ISSUE TITLE
Autocompletition between HTML and CSS/SCSS

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#50476]
Im really missing autocompletition / suggestion elements / identifikators / classes between HTML and CSS/SCSS languages , and vice versa of course.

All plugins which i tested works not very well, and i also think, that should be native behavior.

Is it planned in the near future?

**Comment by aeschli** [comment]
duplicate of #46200

**Comment by Kcko** [comment]
Please? Its not duplicate. Its not about folding ...

**Comment by aeschli** [comment]
sorry, wrong bug: duplicate of #47331
