### ISSUE TITLE
Autocompleting replacing expression in unexpected ways

### ISSUE THREAD

**Issue by otri** [Microsoft/vscode#50475]
Issue Type: <b>Bug</b>

The autocomplete system is mistaking my lambda closure variable as something else.  So it's swapping out my symbol for a conflicting symbol.

For example, typing this out is hard:
_MainGame.PlayState.Subscribe( newState => {} );

"newState" gets substituted for "NetworkStateSynchronization"

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (13.39GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron /Volumes/SPD-otri/SPD_Projects/ShapeImmersive/SI-KittyKong -r -g /Volumes/SPD-otri/SPD_Projects/ShapeImmersive/SI-KittyKong/Assets/KKGame/Scripts/PrepareToStart.cs:1|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
unity-tools|Tob|1.0.4
unity-debug|Uni|1.3.0
unity-snippets|Ycl|0.1.2
csharp|ms-|1.15.2
vscode-icons|rob|7.23.0
mel|sat|0.1.2
vscode-nginx|sha|0.5.0
markdown-all-in-one|yzh|1.4.0

</details>

**Comment by mjbvz** [comment]
Is this for c#?
