### ISSUE TITLE
Test: js/ts code preferences 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50488]
Test for #45948 + #49653
 
Complexity: 1

- [x] Windows @bpasero 
- [x] Mac @misolori
- [x] Linux @kieferrm  

**Summary**
Two new options have been added for js and ts:

- `"javascript.preferences.importModuleSpecifier"` / `"typescript.preferences.importModuleSpecifier"`- Controls the type of import paths used for auto imports and quick fixes

- `"javascript.preferences.quoteStyle"` / `"typescript.preferences.quoteStyle"` - Controls the type of quotes used for auto imports and quick fixes

**Testing**
Try configuring these settings and triggering quick fixes / auto imports to make sure they are observed (the VS Code workspace already configures default values for these)

**Comment by bpasero** [comment]
I tested for TypeScript only because this test plan is missing instructions how to get imports working in a JS project.

**Comment by mjbvz** [comment]
For js, try a project that uses modules such as one generated by [create react app](https://github.com/facebook/create-react-app). For proper project-wide intellisense, you may also need to create a `jsconfig.json` file at the root of the project
