### ISSUE TITLE
Automatically fill "files to include" when opening search

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#5048]
I'd like to add a feature to automatically fill "files to include" with the currently focused directory when opening the search. It is quite handy and other IDEs offer this feature, too.
So if you focus the folder "foo" in tree of the "Explorer" view and you press ⌘⇧F, than "files to include" should be filled with "foo", so the user can search directly in "foo".

The search value is automatically filled, too, if you have text selected in the editor. This happens in `getSelectionFromEditor` and is possible because the "Search" view has access to the editor (`this.editorService.getActiveEditor().getControl()`).

I tried to find a way to get the focused element in the tree "Explorer" view. 

This is possible in `OpenSearchViewletAction`:

```
class OpenSearchViewletAction extends ToggleViewletAction {
    public static ID = VIEWLET_ID;
    public static LABEL = nls.localize('showSearchViewlet', "Show Search");

    constructor(id: string, label: string, @IViewletService viewletService: IViewletService, @IWorkbenchEditorService editorService: IWorkbenchEditorService) {
        if (viewletService.getActiveViewlet() instanceof ExplorerViewlet) {
            const viewer = (<ExplorerViewlet>viewletService.getActiveViewlet()).getExplorerView().getViewer();
            console.log(viewer.getFocus());
        }
        super(id, label, VIEWLET_ID, viewletService, editorService);
    }
}
```

This will call `this.viewletService.openViewlet(this.viewletId, true);` (in `ToggleViewletAction#run`) later, so we switch to the "Search" view. It seems there is no way to pass the focused element from the tree "Explorer" view to the "Search" view here, so I can fill "files to include".

Any hint how I can do that...?

**Comment by bpasero** [comment]
@donaldpipowitch what about the action "Find in Folder" from the context menu in the explorer on folders?

**Comment by donaldpipowitch** [comment]
@bpasero You're right. This is good enough for most cases (didn't know about that).

But can I place a hotkey on "Find in Folder"? And could I press this hotkey when the element is focused/selected, so I don't need to open the context menu?

Can I open the context menu for multiple tree elements, so I can search in multiple folders? (I don't if I could do that with `tree.getFocus()`, because it returns `any`. Is this always a single element or can it be multiple elements?)

**Comment by bpasero** [comment]
Those things you mention are currently not possible but some of them captured in other issues. #4557 for example.

**Comment by donaldpipowitch** [comment]
I've looked further into the code now. The keyboard shortcuts for the current context menu actions are configured in [`keybindingForAction` (fileActions.ts)](https://github.com/Microsoft/vscode/blob/52c47af70511ec3ecd72033bd35ed2bb997ada08/src/vs/workbench/parts/files/browser/fileActions.ts#L2338). The "Find in Folder" action is added in [`getSecondaryActions` (search.contribution.ts)](https://github.com/Microsoft/vscode/blob/55dfa604084153e47d09b2dcf54933394fa8721d/src/vs/workbench/parts/search/browser/search.contribution.ts#L77) and defined as [`FindInFolderAction` (searchViewlet.ts)](https://github.com/Microsoft/vscode/blob/55dfa604084153e47d09b2dcf54933394fa8721d/src/vs/workbench/parts/search/browser/searchViewlet.ts#L66).

As far as I can tell I'd need to solve three steps to reach my goal:
1. Make keyboard shortcuts for context menu actions configurable.
2. Call context menu actions if the relevant keyboard shortcut is pressed when the element in the tree is _focused_. (E.g. you can press ⌘C to copy a file when the element is focused in the tree view _or_ via context menu. Rename works in the same way. I think this should be the default behaviour for all context menus.)
3. Allow focusing more than one element, so I can copy multiple files at once or search in multiple folders.

To solve step 1 I need a little bit more explanation about editor actions and keyboard shortcuts. I guess I'd need to replace `keybindingForAction` with some `CommonEditorRegistry.registerEditorAction` logic. `CommonEditorRegistry.registerEditorAction` gets an `EditorActionDescriptor` instance, which has `IEditorActionKeybindingOptions`. These `IEditorActionKeybindingOptions` probably need a _new contex_ to express _when context menu is open or element is focused in tree_ right? Is [this](https://github.com/Microsoft/vscode/blob/2395a89ab84cb92ef41400408a71a1956f830d4e/src/vs/editor/common/editorCommon.ts#L2552) the complete list of all available contexts? Where would I start to add a new context?

**Comment by bpasero** [comment]
I do not think this is an easy task for a pull request, there is too much debt in the way the tree exposes a controller for keybindings. Imho the keybinding service should be properly hooked up from the tree controller so that it becomes easy for clients of the tree to configure keybindings properly.

**Comment by donaldpipowitch** [comment]
> I do not think this is an easy task for a pull request.

If you have time for mentoring I could try it :)

**Comment by owlcode** [comment]
I'm pretty sure that active tab should be inside "files to include" by default when searching / replacing. Although I have found pretty good workaround - click twice on "regular expression", all files will be included. If your phrase is unique enough, it's not that hard to find current file. Worked for me.

**Comment by roblourens** [comment]
This is possible with a keybinding like


```json
{
    "key": "alt+cmd+f",
    "command": "filesExplorer.findInFolder",
    "when": "explorerViewletFocus"
}
```
