### ISSUE TITLE
Inline Git reverts unrelated whitespace changes

### ISSUE THREAD

**Issue by kunitsyn** [Microsoft/vscode#50481]
Issue Type: <b>Bug</b>

When using Git inline diff to revert lines, all whitespace changes in a file will be reverted as well.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (7.30GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|44%|

</details>

Steps to Reproduce:

1. Open a file checked in Git.
2. Make a whitespace-only change in it. (Note it won't be highlighted in inline Git.)
3. On the separate line, make a regular change in it.
4. Revert change from step 3.

![out](https://user-images.githubusercontent.com/2458966/40565850-d5fc130e-6076-11e8-979a-989d12323082.gif)

Expected outcome:
Only change from step 3 is reverted.
Actual outcome:
Changes from both step 2 and step 3 are reverted.

Note:
I believe this is different from the bug https://github.com/Microsoft/vscode/issues/49902, since changes that are reverted there are clearly not whitespace-only. If it is not the case, please sorry.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kunitsyn** [comment]
I could try to fix it. The problem seems to be in the `editorSimpleWorker.ts`, which is a worker that sends messages to the render thread. But I don't know how to debug it; no matter what debug configuration from `launch.json` I use, breakpoints that I set are not triggered, and debug prints via `console.log` also do not work.

Is it possible to debug the worker's code from VS Code (or by other means)?

**Comment by joaomoreno** [comment]
cc @alexandrudima

**Comment by alexandrudima** [comment]
Yes, it is possible to debug the worker code by the same way the UI code is debugged. Simply open the file in the Sources pane in Dev Tools and place breakpoints as needed.

But IMHO this is not a problem in the diff algorithm.
