### ISSUE TITLE
Test: search provider API

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50497]
Test for #47058

Complexity: 2

- [x] AnyOS @chrmarti 

Steps:

- Write a simple extension that uses the SearchProvider API. See an example at https://github.com/Microsoft/vscode-extension-samples/blob/roblou/searchProviderExample/fsprovider-sample/src/searchProvider.ts
- File issues if you have any issues getting results to show up, or if any part of the API itself is confusing.

**Comment by chrmarti** [comment]
@roblourens I can't get it to work with todays insiders build and also tried MemFS. The search provider is never called.

**Comment by chrmarti** [comment]
That makes it work. 👍
