### ISSUE TITLE
Test: JS/TS update imports on file move

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50494]
Testing for https://github.com/Microsoft/vscode/issues/49579

- [x] macOS @auchenberg 
- [x] linux @ramya-rao-a 
- [x] windows @RMacfarlane

Complexity: 1

**Summary**
VS Code will now attempt to update import paths when you move or rename a js/ts file using the vscode API. This is controlled by the `javascript.updateImportsOnFileMove.enabled` setting. The default behavior of this setting is to prompt the user for each file rename / move

Note that directory renames are currently not supported. This is tracked by #50244 

**Testing**
In a js/ts project with imports and a `tsconfig` or `jsconfig`, try moving and renaming files. Confirm that you are prompted and can automatically update import paths. 

Things to try:

* Test different values for `javascript.updateImportsOnFileMove.enabled`, such as `"always"` and `"never"`
* Make sure format style and preferences are respected

**Comment by tommhuth** [comment]
this caused major trouble for me, ending up with all my imports (including node_modules) being mangled into redonk stuff like: 
```js
// wtf?
import React from "../../../../../Library/Caches/typescript/2.9/node_modules/@types/react"
// this points directly to my node_modules folder, instead of @scope/shared-react-components/native
import { SplashPosterSubtitle, SplashPoster, SplashPosterTitle } from "../../../../shared-react-components/native"
```

**Comment by auchenberg** [comment]
@tommhuth Yes please.
