### ISSUE TITLE
Problem with doublequote in section 

### ISSUE THREAD

**Issue by agowa338** [Microsoft/vscode#50495]
The yaml syntax highlighting is getting confused by linebreak and quotes within a ">-" section.

Version Information
- VSCode Version: 1.23.1
- OS Version: ArchLinux (4.16.11-1-ARCH #1 SMP PREEMPT Tue May 22 21:40:27 UTC 2018 x86_64 GNU/Linux)

Steps to Reproduce:

1. Save the following into a file called example.yml:
```
command: >-
    certonly --standalone -d {{ item }} -m "{{ ansible_certbot_contact_mail
    }}" --agree-tos --keep-until-expiring --preferred-challenges http-01
    --http-01-address 0.0.0.0 -vvvv {% if ansible_certbot_testing %}
    --test-cert {% endif %}
register: container_res
```
2. Open that file with Visual Studio Code

Does this issue occur when all extensions are disabled?: Related to build in extension

**Comment by aeschli** [comment]
This issue was moved to textmate/yaml.tmbundle#24
