### ISSUE TITLE
Error while saving and opening py files - A system error occurred (EPERM: operation not permitted, open 'c:\UNC\trypythonex\cgi-bin\gs.py')

### ISSUE THREAD

**Issue by SundareshSankaran** [Microsoft/vscode#50490]
Issue Type: <b>Bug</b>

A system error occurred (EPERM: operation not permitted, open 'c:\UNC\trypythonex\cgi-bin\gs.py')

1. Created a new file
2. Ctrl S as a py file
3. Obtained error whenever I try to save

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.12GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\UNC\trypythonex\cgi-bin\excode.py|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
django-snippets|bib|1.1.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
MagicPython|mag|1.0.12
python|ms-|2018.4.0
git-merger|sha|0.4.1
jinja|who|0.0.8

</details>

**Comment by bpasero** [comment]
@SundareshSankaran this indicates that you are trying to save a file where you do not have the right permissions to do so. Are you running VSCode as a different user than the file was created with?
