### ISSUE TITLE
Sort alphabetically Default User Preferences by section (or extension) name, it is hard to locate specific extension's available settings

### ISSUE THREAD

**Issue by vhanla** [Microsoft/vscode#50500]
- VSCode Version: 1.23.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open user preferences (`ctrl`+`,`)
2. Search for preferences available for specific extension or section (e.g. Editor, Window, Workspace, etc.)

Does this issue occur when all extensions are disabled?: No
Irrelevant (needs to be extensions on)

If there are few extensions installed, it is obviously easy to locate each section, but as many as new extensions are installed it becomes a long unordered list of sections.

![messy](https://i.imgur.com/K1Pa6aO.png)

As you can see, sections are sorted in random order and if many extensions are installed, finding settings for the one specific extension is not as easy as if at least it could be sorted alphabetically. 
Also, it is not possible to filter out by section (or extensions) names. 
Useful only, using the search settings box, yet, you should know by advance the settings name before searching for it, but then, results also hides the section (or extension) which the settings found belongs to.

Maybe there is a `@filter` to use in the search settings box, but is not easy to know, as for example, extensions sidebar offers it, and some filter words are hidden and almost look like undocumented features.

**Comment by sandy081** [comment]
We are coming up with a new settings editor @roblourens is currently working on it. So assigning it to him.

**Comment by roblourens** [comment]
Not investing much in the old settings JSON editor now that the UI exists
