### ISSUE TITLE
Indent children in sidebar

### ISSUE THREAD

**Issue by kobenauf** [Microsoft/vscode#50506]
Issue Type: <b>Feature Request</b>

In the list of files in the sidebar, the hierarchy indents children so each file's icon is aligned under its parent's first letter.  Technically this is indented, because the parent is a folder, and the folder's icon is a collapse/expand arrow.  However my mind does not see the arrow as part of the indentation indicating parent/child relationship, but instead sees it as an external control feature.  This causes the folders content to appear as siblings of the folder, not children.  Bottom line, I request you consider indenting the children file 2 more spaces.

VS Code version: Code - Insiders 1.24.0-insider (eed12c19a5ece4d7d1d3276eef89e335a3ec1497, 2018-05-25T05:17:05.420Z)
OS version: Windows_NT x64 10.0.17134

**Comment by realuser** [comment]
See also https://github.com/Microsoft/vscode/issues/35447 and consider reacting/commenting to get more eyes on it

**Comment by shreeve** [comment]
Wahoo... it looks like this is finally getting resolved officially!

Check out: #66605 - Introduce tree.indentPixels configuration

Thanks @isidorn, @joaomoreno, and @bpasero!
