### ISSUE TITLE
Build task with Ninja shows wrong problems directory

### ISSUE THREAD

**Issue by parof** [Microsoft/vscode#50503]
I'm using [Ninja](https://ninja-build.org/) build system to build a C project. I'm using the extension [C/Cpp](https://github.com/Microsoft/vscode-cpptools). When i build the project with the Build task, the extension shows the warnings and the errors int the problems panel, but the paths to the files are wrong: they point to upper directories in the file system tree.

- VSCode Version: 1.23.1
- OS Version: Ubuntu 17.10 x64
- Needed extension: C/Cpp (https://github.com/Microsoft/vscode-cpptools)
- C/Cpp extension version: 0.17.3

Steps to Reproduce:

1. Go to the ${workspaceRoot} directory of a C project. I'm actually workign on [this](https://github.com/parof/CGen/tree/954eb2bc8e02a80583d0f6ecc5b65a2b84a14d55)
2. Create the build directory with [Meson](https://mesonbuild.com/): `meson build`
3. Configure the Build task as 
```
        {
            "label": "Build",
            "type": "shell",
            "command": "ninja",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "cwd": "${workspaceRoot}/build"
            },
            "problemMatcher": [
                "$gcc"
            ]
        }
```
4. Launch build task
5. Look at the output: the warnings should point to files in the ${workspaceRoot} directory, but actually for me they point to some other locations. Example:  
Console output with warnings
![console_output](https://user-images.githubusercontent.com/32315224/40574542-4afb1684-60d4-11e8-809c-4c0dd12dab5c.png)
Problems panel(pointing to the wrong directory, because my project is located in `/home/phreppo/CGen`)
![problems_output](https://user-images.githubusercontent.com/32315224/40574546-5225a604-60d4-11e8-96ed-cb0dc1ec449e.png)
Dialog window that appears when I click on one warning. In this particular example the file that should be opened is `/home/phreppo/CGen/test/t_list.c`
![click_error](https://user-images.githubusercontent.com/32315224/40574538-489a6958-60d4-11e8-83a4-f99049500544.png)

Does this issue occur when all extensions are disabled?: No, but just because C/Cpp extension is needed to show problems.

**Comment by dbaeumer** [comment]
@parof please provide the issue here Microsoft/vscode-cpptools since the Gcc problem matcher is provided by the CPP extension. VS Code doesn't ship with one. 

What you can do is to try tweaking the probem matcher yourself. Something like 

```
	"problemMatcher": {
		"base": "$gcc",
		"fileLocation": ["relative", "${workspaceFolder}/build"]
	}
```
