### ISSUE TITLE
Cannot validate php file Info popup should have option to open settings

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5050]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Open a php file 
2. Dialog pops up saying "Cannot validate the php file"

Expected:
Most other warnings ask if you would like to open the config file.
![phpconfig](https://cloud.githubusercontent.com/assets/12900364/14330474/91f0351a-fbf5-11e5-89ec-989e0aae554e.JPG)

**Comment by BeenStone** [comment]
I met it yet, how to stop it ?

**Comment by dbaeumer** [comment]
To stop it either provide the setting using File > Preferences > Workspace Settings or disable it using the setting "php.validate.enable": false

**Comment by roblourens** [comment]
#8735
