### ISSUE TITLE
Forever updating intellisence after building the project

### ISSUE THREAD

**Issue by DouglasLiuGamer** [Microsoft/vscode#50502]
Issue Type: <b>Bug</b>

Notice that this issue does not happen before. Just encounter it recently.

I am working on a C++ project and I use MSYS outside to build it. Most of the time (not always, but chances are high) after I build the project, VS Code will start updating intellisence forever. This can be temporarily fixed by reloading the screen. But it is still annoying.

I am already using the latest version.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (4.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.3
code-spell-checker|str|1.6.10

</details>

**Comment by DouglasLiuGamer** [comment]
It seems that not only using MSYS, simply using Git through the integrated-terminal to change some files will cause the forever intellisense updating.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
