### ISSUE TITLE
Allow to use simple markdown formatting in notification messages

### ISSUE THREAD

**Issue by AdrieanKhisbe** [Microsoft/vscode#50512]
- VSCode Version: 1.23
- OS Version: Macosx 10.11

As of https://github.com/Microsoft/vscode/issues/20595, it seems that *markdown formatting* in `showInformationMessage` has been disabled.

Would it be possible to reactivate it on demand?
At least with the original subset cf https://github.com/Microsoft/vscode/issues/20595#issuecomment-281099832.

It could be done via an extra option in [MessageOptions](https://code.visualstudio.com/docs/extensionAPI/vscode-api#MessageOptions), `enableMarkdown`, or by providing a [MarkedString](https://code.visualstudio.com/docs/extensionAPI/vscode-api#MarkedString)

**Comment by bpasero** [comment]
Closing for same reason as https://github.com/Microsoft/vscode/issues/48900#issuecomment-385332787
