### ISSUE TITLE
Automatic Indentation error in Python

### ISSUE THREAD

**Issue by rahulguptakota** [microsoft/vscode#50511]
Issue Type: <b>Bug</b>

On typing in the following in a python file:

for line in data[1:]:

The next line should be automatically indented by 1 tab (or equivalent) as per python's requirement but instead it starts from the left.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2183)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (2.21GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.17.0
composer-support-client|Hyp|0.19.1
latex-workshop|Jam|5.5.0
gitlens|eam|8.3.2
language-haskell|jus|2.5.0
python|ms-|2018.4.0
csharp|ms-|1.15.2
grammarkdown-language|rbu|0.4.3

</details>

**Comment by Tyriar** [comment]
Not sure if this is extension or auto indent on our side

**Comment by rahulguptakota** [comment]
I will check.

**Comment by rahulguptakota** [comment]
This bug does not occur without extensions. So, i guess one of them might have messed up.

**Comment by rahulguptakota** [comment]
Yup, with the Python extension given by Microsoft, this indentation bug pops up.
