### ISSUE TITLE
shortcut shift + alt  doesn't work

### ISSUE THREAD

**Issue by goldylucks** [Microsoft/vscode#50518]
Issue Type: <b>Bug</b>

1. Install vscode
2. Open keyboard preferences
3. Click enter on any shortcut
4. Hit shift+alt+anyKeyHere
the above doesn't work, and only sets shift+anyKey, or alt+anykey, but never both of them.
5. open to `keybindings.json`
6. On the user section, right side, change any shortcut manually to "shift+alt+anyKey"
7. test the command from step 6

One of the commands I've tested on is 
```
    {
        "key": "shift+alt+right",
        "command": "editor.action.selectHighlights",
        "when": "editorTextFocus"
    },
    // Note I've already disabled the default `shift+alt+right`, which didn't work anyway
    {
        "key": "shift+alt+right",
        "command": "-editor.action.smartSelect.grow",
        "when": "editorTextFocus"
    }
```

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.43GB (2.31GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
snapshot-tools|asv|0.0.7
vscode-eslint|dba|1.4.10
flow-for-vscode|flo|0.8.1
duplicateselection|kka|1.0.1
debugger-for-chrome|msj|4.4.3
vscode-subword-navigation|ow|1.2.0
ReactSnippets|xab|2.1.0

</details>

**Comment by alexandrudima** [comment]
@goldylucks I cannot reproduce. I am able to receive `shift+alt+` keybindings.

If the keybindings box does not show any of the `shit+alt+` keybindings, it means we are not receiving the keypress. I would suggest to check other applications on your OS, can other apps receive this keypress. Most likely I think you have something installed or configured which makes it that these keybindings don't reach us.

**Comment by goldylucks** [comment]
seems like you're right, I had `shift+alt` mapped to switch input source. Tho from what I remember, on `Atom` I could still use.

anyway, I've removed `shift+alt` from it's system binding, and now it works. Thanks for the help!
