### ISSUE TITLE
New settings editor - "Also modified in" doesn't show up for workspace folders

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50516]
- Open multiroot workspace
- Edit setting in folder
- Open User settings scope in settings editor
- "Also modified in" doesn't show the workspace folder

Need to query every workspace folder for every setting.

**Comment by roblourens** [comment]
Fixed recently

**Comment by bpasero** [comment]
@roblourens I am no longer seeing this, does it still apply with the blue change bars?

**Comment by roblourens** [comment]
I think I confused this with another issue, it's not fixed for workspace folders.

**Comment by roblourens** [comment]
Dupe of #57370
