### ISSUE TITLE
Broken indent lines.

### ISSUE THREAD

**Issue by YusifKhalilov** [Microsoft/vscode#50514]
Sometimes vscode displays broken indent lines.

![screen_shot_2018-05-26_at_11_16_30_am](https://user-images.githubusercontent.com/16528284/40579187-e18a275a-60d6-11e8-836e-2940aa1ace03.jpg)

**Comment by YusifKhalilov** [comment]
Sometimes yes. It happens in both situations.

**Comment by YusifKhalilov** [comment]
usually it happens after "Format Document"

**Comment by alexandrudima** [comment]
My suggestion is to stop using `window.zoomLevel`. Only with `"window.zoomLevel": 0` you can get pixel perfect rendering.
