### ISSUE TITLE
Option to use // @ts-check with JavaScript Standard Style

### ISSUE THREAD

**Issue by aral** [Microsoft/vscode#50520]
When using the [vscode-standardjs extension](https://github.com/standard/vscode-standardjs), you have to set `"javascript.validate.enable": false`. This also disables `// @ts-check` from working. 

It would be great to have the option of using JavaScript Standard Style _and_ have TypeScript type checking via JSDoc comments.

Could we add an option (e.g., `"javascript.validate.tscheck": true`), which enables just TypeScript checking when `"javascript.validate.enable": false`?

**Comment by mjbvz** [comment]
Yeah I don't know why they recommend that. Not disabling validation does not seem to cause any problems. Our built-in js validator only really warns about bad syntax in its default state

Try following up with the extension
