### ISSUE TITLE
Launch configuration improvement

### ISSUE THREAD

**Issue by johnbester** [Microsoft/vscode#50527]
The launch configuration as it stands is very powerful, but I could not find any way to do two things that are reasonably simple to implement, but make a great improvement. I have search for possible existing ways to do this, but could not find any.

If you debug a web based application (assume nodejs as an example), you have to start your web server and if you have Debugger for Chrome, you have to launch chrome with remote debugging enabled as well. Now, if you decide to stop the node server, you click the debugger stop button and a side effect is that chrome is closed as well. This can be improved in a number of ways:

1. Add a standard launch configuration option to assign a key (custom string value that is unique to a project). Typically you could have "key":"browser" for starting chrome and "key":"server". (Maybe the "name" property can be used for this, but it seems to be used as descriptive text in most cases since it is also used in the launch combobox). Now allow keyboard bindings to be added for these names. Depending on which workspace is open, these shortcuts will work if there is launch configuration for that specific key. This will allow the user to start two launch configurations in succession by using key presses. Depending on the implementation either the first match or all matches can be started.

2. By using "key" as explained in (1), you could also set up a launch dependency. For example, if you launch "browser", it could depend on "server" and you would even be able to set a delay. So, give the server 3 seconds to start if it has not been started yet before opening the browser. This allows a user to set up a single launch configuration that would get a required debugging environment in a single launch action.

3. In order to avoid closing your browser if you restart, you might want to disable the "stop" action when your browser was launched". Typically your plugin would handle this action, but surely you can allow a user to mask specific events from being sent to the plugin. This would allow the user to mask the "stop" event and still have "reload"/"restart" events going to the plugin.

**Comment by isidorn** [comment]
@roblourens we do not support invoking commands with arguments. There is probably an open feature request for this.

**Comment by roblourens** [comment]
I'm referring to this: https://code.visualstudio.com/docs/getstarted/keybindings#_command-arguments

**Comment by johnbester** [comment]
Thanks for all the input. The compound launch configuration is a solution to launch dependency I originally mentioned and the key binding "args" does provide the architecture to define key bindings for various launch configurations and all that is needed is the ability make use of "args": { "name": "My Launch" } to workbench.action.debug.start (and maybe workbench.action.debug.restart and workbench.action.debug.stop).
