### ISSUE TITLE
Does not debug es6 nodejs 

### ISSUE THREAD

**Issue by elissaioskon** [Microsoft/vscode#50522]
- VSCode Version:1.23.1
- OS Version: Windows 8

Steps to Reproduce:
I have a project with expressjs that uses es6 so i bundle it with webpack.
I try to debug with vscode debug with the settings bellow:
my launch.json is ->
![image](https://user-images.githubusercontent.com/26840252/40580357-306f3ac2-6145-11e8-81e8-d81733dc6856.png)

the error it prints is:
![image](https://user-images.githubusercontent.com/26840252/40580361-53603b08-6145-11e8-9202-3f2643fd78f8.png)

If i just run bundle but without outFiles it runs 
![image](https://user-images.githubusercontent.com/26840252/40580486-e580bc0e-6147-11e8-8353-df7edaf6ae56.png)

But i need to run the original because i need to place my breakpoints there.Why this is happening?
Thanks

**Comment by roblourens** [comment]
You need to set `program` to the main file that will actually run (bundle.js) and outFiles to all the .js files so it can find your sourcemaps.

**Comment by elissaioskon** [comment]
Thanks for the answer, i tried to set program to bundle.js which is my main file. Then i add at 
outfiles : [${workspaceFolder}/src/] where all my sources are(because i have many folders in src with subfolders that have the actual .js files) But when i run debug in vscode it runs bundle.js but it does not stop to any breakpoint i place.
Also i want to mention that my source maps are at  bundle.js.map

**Comment by elissaioskon** [comment]
i still cant debug.
```
"configurations": [
        {
            "cwd": "${workspaceRoot}",
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/src/server/build/bundle.js",
            "outFiles": [
             //also tried  "${workspaceFolder}/*.js"
                "${workspaceFolder}/**/*.js"
            ],
            "sourceMaps": true
        }
    ]
```
it see only the bundle but not my js files with the original code and source maps.
![image](https://user-images.githubusercontent.com/26840252/40853419-b0d75466-65d6-11e8-857d-1a46acca801b.png)

i have try also to change webpack devtool to inline source maps because i the source maps was produced to an other file named express.js.map but nothing changed.

My file structure is 
![image](https://user-images.githubusercontent.com/26840252/40853552-2d930e8c-65d7-11e8-99e6-d8870cedd74b.png)
in the src/server/express.js is my server
in the src/server/build/bundle.js is my bundled file produced by webpack.

i set break points to the original source code and doesn't see them.
![image](https://user-images.githubusercontent.com/26840252/40853727-c7f59198-65d7-11e8-9630-5f82d8042255.png)
 

What other information can i provide to find see whats going on?

**Comment by roblourens** [comment]
What's the output of the `.scripts` command in the debug console? It will tell us whether sourcemaps are being resolved correctly.

**Comment by elissaioskon** [comment]
@roblourens  i sent  the output to your github email because the data are a little sensitive.

**Comment by roblourens** [comment]
You can see the paths from the sourcemaps like `webpack:///src` and the resolved paths next to them in (). You can see that they are not resolved to absolute paths. So you'll have to set some `sourceMapPathOverrides` to fix them manually. 

You can try 

```json
"sourceMapPathOverrides": {
    "webpack:///src/*": "${workspaceFolder}/*",
    "webpack:///./*": "${workspaceFolder}/*",
},
```

to start

**Comment by elissaioskon** [comment]
Thank you for yourr time.now vs code can see the original lines(like Server is listening on port express.js:65)
but when i set breakpoints it does not stop the program  and if i hover it says:
![image](https://user-images.githubusercontent.com/26840252/40873449-d595ece4-6668-11e8-99f7-f1555c86f24c.png)

**Comment by elissaioskon** [comment]
My config now is the above and it works :) 
"configurations": [
        {
            "cwd": "${workspaceRoot}",
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/src/server/build/bundle.js",
            "outFiles": [
                // "${workspaceFolder}/*.js"
                "${workspaceFolder}/**/*.js"
            ],
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${workspaceFolder}/src/*",
                "webpack:///config/*": "${workspaceFolder}/config/*",
                "webpack:///./*": "${workspaceFolder}/*",
            },
        }
    ]

Thanks for the support.

**Comment by roblourens** [comment]
Great, glad to hear it.

**Comment by elissaioskon** [comment]
Also i would like to mention that it does more than 11 sec to start debug from the time a hit the play button...

**Comment by roblourens** [comment]
It's just invoking 'node' with your program here, not much else going on. Is it 11 seconds from launching the program to hitting your breakpoint?

**Comment by roblourens** [comment]
It might be that it's taking a very long time to find all the .js files in your outfiles pattern. Now that you have it working you can find a more targeted outFiles pattern to set.

**Comment by elissaioskon** [comment]
Yes, this was the problem. i change the outfiles and make them more explicit and it does not lag.

My Old outfiles 
"${workspaceFolder}/*.js"

My Updated outfiles
"${workspaceFolder}/src/**/*.js",
"${workspaceFolder}/config/**/*.js"
