### ISSUE TITLE
能换一换软件的logo吗，太丑了

### ISSUE THREAD

**Issue by xcmm** [microsoft/vscode#50524]
Issue Type: <b>Feature Request</b>

不能用tweet，只能意见反馈了，^_^

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by weinand** [comment]
Machine translation:
> Can not use tweet, can only feedback, ^_^

I don't know what you mean.
Please try explain (ideally in English).

**Comment by Roger-WIN** [comment]
Can you feedback in English? I am also Chinese, and I know at least this basic rule.
