### ISSUE TITLE
Search highlighting in some themes could be improved

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5052]
- VSCode Version: 0.10.12-alpha (latest)
- OS Version: Windows 10

Steps to Reproduce:

1. Search for something that occurs in a file many times
2. Click between the results in the same file.

Actual: 
Very low visibility that your selection has changed between the results in the same file.

![searchselection](https://cloud.githubusercontent.com/assets/12900364/14333322/f791fff4-fc02-11e5-8838-ffc7015f107e.JPG)

Also with the Solarized Light theme some text is almost unreadable when selected by search
![searchunreadable](https://cloud.githubusercontent.com/assets/12900364/14333358/28dbf5ce-fc03-11e5-8224-d873bf4f0051.JPG)

**Comment by nathantschultz** [comment]
It would be nice if the user could customize the search results highlight color. It's really hard to tell what is highlighted and what isn't when searching.

**Comment by sandy081** [comment]
This is fixed by #11095
