### ISSUE TITLE
[json] JSON array suggestion should stay single line

### ISSUE THREAD

**Issue by fxedel** [Microsoft/vscode#50528]
Issue Type: <b>Feature Request</b>

When you edit a JSON document with a JSON schema attached and accept a suggestion for a property that takes an array, the array is immediately enlarged into three lines.

But often, you don't want the array to take a line per array item, because the whole array could be written into a single line. You have to delete the automatically added lines by hand then. This is much more work than it would to take to press Enter if VSCode created inline arrays. 

![output](https://user-images.githubusercontent.com/7782229/40584906-bbfcd61c-61a9-11e8-9fe8-02e7a57a968b.gif)

So my suggestion is not to create these extra lines and let the user decide whether he wants each item in a single line (press Enter) or the whole array in a single line.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.15.0-23-generic

**Comment by felixfbecker** [comment]
Agreed - same with objects actually. It's way easier to press <kbd>return<kbd> another time than to backspace it back on one line.
