### ISSUE TITLE
Dropdown for `require` in JS should also show JSON files

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#50536]
- VSCode Version: Version 1.23.1 (1.23.1)
- OS Version: macOS 10.13.4 (17E199)

Steps to Reproduce:

1. Create a JSON file. 
2. Create a JS file. In the file, start typing: `require(./`. 
3. At this point, the dropdown for files in the current dir will appear. The JSON file that we created does not appear in the list. Yet it should, since requiring JSON files in JS is perfectly valid, and will simply return a JS object.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
importing json files is not supported by all runtimes so you currently have to opt in to this feature. In VS Code insiders, set ` "resolveJsonModule": true` in your `jsconfig` or `tsconfig`

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve",
        "resolveJsonModule": true
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```
