### ISSUE TITLE
which font this is in the version 1.23 snapshot?

### ISSUE THREAD

**Issue by shaocongliang** [Microsoft/vscode#50538]
![release 1 23](https://user-images.githubusercontent.com/30583506/40592191-da9e3bc4-624e-11e8-82bc-f7169c974fbd.jpeg)

**Comment by alexandrudima** [comment]
@shaocongliang Sorry, I'm not sure what you mean ?

**Comment by shaocongliang** [comment]
The font name of code snippet in the picture.

**Comment by alexandrudima** [comment]
Here are the default font settings:

https://github.com/Microsoft/vscode/blob/7a9c0801581a811c964afc922ca7ddfe99fd0b8a/src/vs/editor/common/config/editorOptions.ts#L2215-L2217

The screenshot appears to be taken on a Mac, so I suppose the font family would be Menlo or Monaco, depending on what you have installed on your system.

**Comment by shaocongliang** [comment]
Here is my operation system info.
![macos](https://user-images.githubusercontent.com/30583506/40617742-dba61758-62c1-11e8-8c01-b23de9371d90.jpg)

![menlo](https://user-images.githubusercontent.com/30583506/40618199-5ec6f8fe-62c3-11e8-85ce-9d39cbf6f81a.jpg)
![release 1 23](https://user-images.githubusercontent.com/30583506/40618200-60f52c4a-62c3-11e8-8d89-59b80c30055c.jpeg)

Note the letter 'g' in the first line of the code snippet in the screenshot

**Comment by alexandrudima** [comment]
@shaocongliang I've listed the default fonts in my previous comment. The fonts can be also changed via user settings, so you can check your `settings.json` and look at what fontFamily you have configured there.

**Comment by shaocongliang** [comment]
![settings](https://user-images.githubusercontent.com/30583506/40619485-c9c9db9a-62c7-11e8-9820-9f0561a70535.jpg)
Letter 's' is different

**Comment by m-thorsen** [comment]
https://fonts.google.com/specimen/Inconsolata

**Comment by alexandrudima** [comment]
@shaocongliang By default, we ship on OSX the following font configuration:

`"editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace"`

This looks like this:

![image](https://user-images.githubusercontent.com/5047891/40620200-3dd8cd32-6298-11e8-955e-9a193026bd0e.png)

---

How should I know what you have configured for `editor.fontFamily` such that it looks different ?

**Comment by alexandrudima** [comment]
Oh, thanks @m-thorsen now I understand what the OP wants.

@shaocongliang You want me to recognize fonts in screenshots. What a waste of my time :(

**Comment by shaocongliang** [comment]
@alexandrudima very sorry for my bad english expressing.
@m-thorsen thanks
