### ISSUE TITLE
Visual Studio Code Will Not Open Folder or show setting windows and other

### ISSUE THREAD

**Issue by maccurt** [Microsoft/vscode#50531]
I am using v 1.23.1 on windows 7

When I open  visual code there are no other windows for the app that will show.  If I Open a folder it will not show the code. If I click on  File > Preferences > Settings it will not open the window (I assume a modal). I have uninstalled it several time, and removed everything out of %appdata% code. It has worked in the past, but it might have been a previous version.

I can't get to the remove extensions window to remove extensions

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64.

**Comment by bpasero** [comment]
@maccurt can you share a screencast of what you do and how it behaves?

**Comment by maccurt** [comment]
I had to do this to make it work:
 code --disable-gpu 

is there a better fix. I just want to launch VC?
