### ISSUE TITLE
Multiple "do you want to save changes" dialogs

### ISSUE THREAD

**Issue by d07RiV** [Microsoft/vscode#50539]
Issue Type: <b>Bug</b>

1. Open multiple files in different tabs (optional)
2. Modify one of the files
3. Switch to a different, preferably far away tab (optional)
4. Press and hold Ctrl+F4, attempting to close all tabs
5. When VS code gets to your modified file, it emits multiple "do you want to save changes" dialogs, which have to be resolved one by one, because of queued ctrl+f4 inputs.

Expected behavior: only one dialog should be displayed.

(I'm aware of Ctrl+K/W, which does avoid this issue)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|15.95GB (3.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.10
prettier-vscode|esb|1.3.1
docthis|joe|0.6.0
sublime-babel-vscode|jos|0.2.10
cpptools|ms-|0.17.3
node-debug2|ms-|1.22.7
debugger-for-chrome|msj|4.4.3
shader|sle|1.1.3
autoimport|ste|1.5.3
vscode-react-native|vsm|0.6.10

</details>

**Comment by bpasero** [comment]
@d07RiV does it emit multiple dialogs for the same file or different files?

**Comment by bpasero** [comment]
I can reproduce, thinking of maybe introducing some code that will check if the request for saving an editor is running and then joining that request to prevent duplication.
