### ISSUE TITLE
Studio code frozen

### ISSUE THREAD

**Issue by gtzinos** [Microsoft/vscode#50537]
It tried to suggest me a plugin in a loop and then it frozen forever

![image](https://user-images.githubusercontent.com/11459192/40591641-736546fe-621d-11e8-887c-df617b2d4984.png)

**Comment by gtzinos** [comment]
Wrong match.

**Comment by sandy081** [comment]
@gtzinos May I know what does the suggestion looks like?

**Comment by gtzinos** [comment]
Sure, it suggested me to download Python plugin and i figured out that i had installed it.

**Comment by ramya-rao-a** [comment]
Was the suggestion like this?

<img width="485" alt="screen shot 2018-05-28 at 9 36 04 am" src="https://user-images.githubusercontent.com/16890566/40623226-9709a69e-625a-11e8-913e-e50bdcac0f5d.png">

Looks like you have the `MagicPython` extension from MagicStick Inc. installed and the suggestion is for the `Python` extension from Microsoft. Is that right?

When the suggestion showed up, what did you do with it? Pressed Esc? Closed it using the "X" button? Chose "Never show me again"?

**Comment by gtzinos** [comment]
UPDATE:

I faced the issue everytime i open a project based on python, and it kills all the memory until I have to restart:
-
![image](https://user-images.githubusercontent.com/11459192/40654075-ea74c390-6345-11e8-80bf-876ca021836a.png)

Finally i removed python extension + magic python plugins

**Comment by gtzinos** [comment]
I disabled all available plugins, as i can't continue my work..

**Comment by ramya-rao-a** [comment]
> It stacked in a loop (tried to suggest me multiple times the python plugin for 10-20 seconds) then it stopped and appeared in the right bottom side. 

Can you share a screenshot of the stacked up messages?

> I faced the issue every time I open a project based on python,

Do you see this even after installing the suggested python extension?

**Comment by gtzinos** [comment]
- It stacked in a loop (tried to suggest me multiple times the python plugin for 10-20 seconds) then it stopped and appeared in the right bottom side.

I have already share you the screenshot. After 20 seconds the message appeared ( The 'Python' extension is recommended..')

- I faced the issue every time I open a project based on python,

Yes every time except when i disable all extensions

- I am guessing even after you disable all plugins, you will still get the suggestion. But at this point do you see the stacked up message or just a single one that you can close and then carry on with your work?

No i don't get messages

**Comment by ramya-rao-a** [comment]
The recommendation for the Python extension is shown when a python file is opened. For every new python file opened in the editor, the recommendation is shown again. 

I am still not sure how we can end up in a situation where the prompt shows up multiple times without opening a python file for each prompt.

I have pushed a change to show this recommendation for given file type only once during a VS Code session.

Can you try the latest [Insiders](https://code.visualstudio.com/insiders) which has the above mentioned fix?

**Comment by gtzinos** [comment]
Hello @ramya-rao-a now it works fine, by usiing code insiders! Good Job!

**Comment by ramya-rao-a** [comment]
Thanks for verifying!
The same fix will be out in the stable build next week.

**Comment by gtzinos** [comment]
Thanks a lot!
