### ISSUE TITLE
Build task is not saving the changes before building the project.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5053]
- VSCode Version: 0.10.12-alpha
- OS Version: windows10

Note: I am taking error scenario with non-existing file to under this issue correctly.

Steps to Reproduce:
1. Launch app and open ts project from  https://github.com/v-pavanp/ForTestingCode/blob/master/TypeScript.zip location.
2. Now update tasks.json file by providing  args value as "app.ts" and save the changes and build (CTRL+.Shift+B) it.
"args": ["$app.ts"],
3. Verify error message.
error TS5007: Cannot resolve referenced file: 'app.ts'.
4. Now update the args value to "app1.ts" and build it without saving.
"args": ["$app1.ts"],
5. Verify error message in the output window.
error TS5007: Cannot resolve referenced file: 'app.ts'.

Expected: 
error TS5007: Cannot resolve referenced file: 'app1.ts'.

Actual:
When user trigger build operation without save then build task is not performing save before build operation hence result is showing up for old value.

In the below screenshot I updated args value to app1.js and performed build without saving.
I could see the result is showing up for app.js.

![image](https://cloud.githubusercontent.com/assets/17735796/14333131/f93ca666-fc01-11e5-91f1-b6d72f85f837.png)

**Comment by dbaeumer** [comment]
This got addressed a long time ago.
