### ISSUE TITLE
TS type checking and default parameters

### ISSUE THREAD

**Issue by a-heryani** [Microsoft/vscode#50535]
Issue Type: <b>Bug</b>

TS type checking does not seem to be smart enough to discount required params that have default values set. For example, I am getting a ts-check error/warning message that 

_**Argument of type '{ maxAge: number; keys: string[]; }' is not assignable to parameter of type 'CookieSessionOptions'.
  Property 'name' is missing in type '{ maxAge: number; keys: string[]; }'.**_

<img width="379" alt="image" src="https://user-images.githubusercontent.com/26278881/40590109-a15c7b58-623c-11e8-8092-4edb574b6655.png">

However in the type definition file, 'name' defaults to session name so I should not need to pass it in explicitly

<img width="486" alt="image" src="https://user-images.githubusercontent.com/26278881/40590106-7f82f318-623c-11e8-80c1-4bf9b94cd1c8.png">

Here are npm version numbers

<img width="356" alt="image" src="https://user-images.githubusercontent.com/26278881/40590140-3419e098-623d-11e8-9614-a9ed4e0ab1d9.png">

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

**Comment by ashwinkjoseph** [comment]
I have received the same error, did you ask in StackOverflow? did you find the solution? Please post the solution/link to the StackOverflow Question here
