### ISSUE TITLE
vscode on microsoft store

### ISSUE THREAD

**Issue by mateuspv** [Microsoft/vscode#50541]
Hey, I`m doing a fresh install of windows and noticed that vscode is not on microsoft store app.
I think it should be since its a MS product, right? 
Let me know if makes sense.
Tnx.

**Comment by weinand** [comment]
yes.

**Comment by MaxiPigna** [comment]
It would be great having VS Code on Microsoft Store, it would be possibile to use always the most updated version without having to start updates and then restart VS Code. 
Is this request on your roadmap?
