### ISSUE TITLE
can not launch vscode on SUSE linux Enterprise Server 12 SP2

### ISSUE THREAD

**Issue by zjuchujinjin** [Microsoft/vscode#50543]
- VSCode Version: code-1.23.1-1525968555.el7.x86_64
- OS Version: SUSE Linux Enterprise Server 12 SP2

Steps to Reproduce:

1.install vscode with command `rpm -i code-1.23.1-1525968555.el7.x86_64.rpm`
2.start vscode with command `code --user-data-dir /root/vscode/`
3.the vscode was hanged up after running the command

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by zjuchujinjin** [comment]
@bpasero there is nothing output in command line window

**Comment by bpasero** [comment]
@Tyriar any clues?

**Comment by Tyriar** [comment]
@zjuchujinjin `code --verbose` showed nothing? Maybe double check there are no running instances of vscode.

**Comment by zjuchujinjin** [comment]
@Tyriar yes，but I can see process is running with command `ps -ef | grep code`, the output as below:

```
bash /usr/bin/code --user-data-dir /root/vscode/ --verbose
/usr/share/code/bin/../code /usr/share/code/bin/../resources/app/out/cli.js --user-data-dir /root/vscode/ --verbose
/usr/share/code/code --unity-launch
```
