### ISSUE TITLE
The Magnet

### ISSUE THREAD

**Issue by Yuriuh** [Microsoft/vscode#50547]
Issue Type: <b>Feature Request</b>

The Magnet in start menu is too ugly. why not beautify it?

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
What is the magnet? Can you add a screenshot?

**Comment by Yuriuh** [comment]
<img width="513" alt="magnet" src="https://user-images.githubusercontent.com/33216220/41076929-94e13190-6a46-11e8-9d68-19254ec3f143.png">

I mean vscode's icon in start menu is just a pure blue.

**Comment by joaomoreno** [comment]
There is something wrong in your system. This is the default look:

![image](https://user-images.githubusercontent.com/22350/41085529-9b98848e-6a37-11e8-8cb8-7542de5bf567.png)
