### ISSUE TITLE
After latest windows update, all visual studio code shortcuts, executables, etc are gone. Like it vanished.

### ISSUE THREAD

**Issue by tshoemake** [Microsoft/vscode#50544]
Issue Type: <b>Bug</b>

The title says it all.  I updated Windows with the required Windows Update Friday night (5/27).  Saturday when I go to look at the code I'd worked on in MS VSC, I noticed the taskbar icon is missing.  Then I hit the Windows key and start typing visual code, nothing returns  - only MS Visual Studio 2017. I was worried I'd lost a ton of code from the night before but luckily, the source code in my local repository was updated. But it was a huge scare as I was gone this weekend for a wedding I was to be in.  I just got home and was able to see the code was still there... seriously... thankfully.  The way I got VSC to run was at this path: C:\Program Files (x86)\Microsoft VS Code\_\bin\code (windows command script).  

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:38.209Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (21.41GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\_\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.3.2
debugger-for-chrome|msj|4.4.3

</details>

**Comment by joaomoreno** [comment]
That's odd. You should probably file an issue to the Windows team: https://support.microsoft.com/en-us/help/27932/windows-10-send-us-feedback

As for Code, just reinstall it, you should be fine.
