### ISSUE TITLE
Related to JS #3509 Javascript Completion fails if 'exports' is qualified with 'module'

### ISSUE THREAD

**Issue by contreras-jorgev** [Microsoft/vscode#5054]
- VSCode Version: 0.10.11 (0.10.11)
- OS Version: OS X or Windows 

This works:
 -- foo.js --
    'use strict';

     const circle = require('./circle');
     console.log( `The area of a circle of radius 4 is ${circle.area(4)}`);

     circle.   <= you get 'area' and 'circumference'

-- circle.js --
   'use strict';
    const PI = Math.PI;

   exports.area = (r) => PI * r * r;
   exports.circumference = (r) => 2 * PI * r;

This fails: (note in circle.js, 'exports' is qualified with 'module.' 

 -- foo.js --
    'use strict';

     const circle = require('./circle');
     console.log( `The area of a circle of radius 4 is ${circle.area(4)}`);

     circle.   <= you DON't get 'circumference'

-- circle.js --
   'use strict';
    const PI = Math.PI;

   module.exports.area = (r) => PI * r * r;
   module.exports.circumference = (r) => 2 * PI * r;

**Comment by egamma** [comment]
Moving to TypeScript for investigation.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7927
