### ISSUE TITLE
integrated terminal now displays full cwd, never did that before (Python 3.6.5)

### ISSUE THREAD

**Issue by rrice2004** [Microsoft/vscode#50550]
- VSCode Version:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows 7

Steps to Reproduce:

1. Updated Software. Issues started. Added "terminal.integrated.cwd": "C:\\Users\\Rob\\Google Drive\\Python\\projects\\"}  to my Workspace settings. Closed and reopened Studio.  Same issue

2. I used to get just the following when debugging:

C:\Users\Rob\Google Drive\Python\projects>
[script results or errors]

Now I get:
C:\Users\Rob\Google Drive\Python\projects>cd "C:\Users\Rob\Google Drive\Python\projects" && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:/Users/Rob/AppData/Local/Programs/Python/Python36/python.exe C:\Users\Rob\.vscode\extensions\ms-python.python-2018.4.0\pythonFiles\PythonTools\visualstudio_py_launcher.py "C:\Users\Rob\Google Drive\Python\projects" 14122 34806ad9-833a-4524-8cd6-18ca4aa74f14 RedirectOutput,RedirectOutput "c:\Users\Rob\Google Drive\Python\projects\powerball generator.py" "

[Script results or errors]

It's added way too much to the start of the terminal it's confusing.

Does this issue occur when all extensions are disabled?: Yes/No  Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
