### ISSUE TITLE
Click on a conditional breakpoint

### ISSUE THREAD

**Issue by jonathan-snark** [Microsoft/vscode#50551]
Issue Type: <b>Bug</b>

When i click on the inline conditional breakpoint icon, it shows a dialog box. This box says to me "This breakpoint has a condition that will get lost ....". This box is not clickable/killable

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.16.8-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 1201)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (0.55GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.2
material-icon-theme|PKi|3.4.0
vscode-docker|Pet|0.0.27
code-settings-sync|Sha|2.9.2
mapfile|chi|0.0.1
code-sql|cod|0.0.3
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.4
vscode-babel-coloring|dza|0.0.4
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
vscode-npm|fkn|3.3.0
code-runner|for|0.9.3
asciidecorator|hel|0.2.0
vue-snippets|hol|0.1.6
Angular2|joh|6.1.1
vscode-json5|mrm|1.0.0
python|ms-|2018.4.0
cpptools|ms-|0.17.3
Go|ms-|0.6.80
color-highlight|nau|2.3.0
vetur|oct|0.12.3
sass-indented|rob|1.4.9
trailing-spaces|sha|0.2.11
pdf|tom|0.2.0
debug|web|0.22.0

(4 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you also reproduce with latest vscode insiders?
Can you please add a video showing this? Thanks

**Comment by isidorn** [comment]
Thanks, dup of https://github.com/Microsoft/vscode/issues/50026
I will comment on that issue
