### ISSUE TITLE
When using ConvertTo-SecureString, got an error "The string is missing the terminator"

### ISSUE THREAD

**Issue by alex-3sr** [Microsoft/vscode#50559]
Issue Type: <b>Bug</b>

Hi,

just writing powershell script, and use F5 for start my script.
When i use the PS command **ConvertTo-SecureString**, my script can't run in vscode

Example of a script for repro
`$pass_string = "stringtosecure"`
`$pass_secure = ConvertTo-SecureString -String $pass_string -Force -AsPlainText`
`Try { Write-Output "Hello world"}`
`Catch {Write-Output "Exception"}`

And when I run it, i've this error message 
`At C:\scripts\testalex.ps1:10 char:28`
`+     Write-Output "Exception"`
`+                            ~`
`The string is missing the terminator: ".`

Thank you,
Alex

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (22.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
team|ms-|1.136.0
gitlazy|tad|1.0.2

</details>

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
