### ISSUE TITLE
Indic Texts

### ISSUE THREAD

**Issue by A-p-p-u** [Microsoft/vscode#50552]
- VSCode Version: 1.23.1
- OS Version: Ubuntu 16.04

Malayalam text is rendered in a jumbled way in the terminal. Other Indic scripts are rendered imperfectly, but not as messed up as Malayalam text.

Steps to Reproduce:

1. Type or paste some Indic text in the editor - it renders correctly.
2. Type or paste the same text in the integrated terminal - it is messed up.

This same text is not messed up when pasted (not typed) in konsole terminal. Konsole is able to render the text correctly. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by A-p-p-u** [comment]
When I try to solve this problem by using konsole as the integrated terminal, I get no terminal. This is the result:
![screenshot from 2018-05-28 07-35-07](https://user-images.githubusercontent.com/7231689/40612933-78a3e9e0-624a-11e8-8dfa-46ea80aaf0ae.png)

**Comment by Tyriar** [comment]
See https://github.com/xtermjs/xterm.js/issues/1468
