### ISSUE TITLE
Read menu registry before having scanned package.json files

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50557]
In my grid branch (`ben/editor`) I have adopted all of the editor toolbar entries to be commands going through the `IMenuService` mechanisms. For some reason, the actions do not show up until the extension host is ready which looks rather ugly on reload/startup:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/40606332-59da0fd8-6265-11e8-9587-3d201c6fb96e.gif)

I understand that we need to reload the actions once the extension host is ready do collect more actions, but the commands that are contributed out of the box should not wait for the extension host to be ready?

The waiting seems to happen here: https://github.com/Microsoft/vscode/blob/4a0ab3675617f9650ca8f254dd9493fb759d23b1/src/vs/platform/actions/common/menu.ts#L29

**Comment by jrieken** [comment]
The menu registry has been populated by extensions exclusively in the beginning and therefore it waits for package.json-files being read (not extension host process startup) and therefore it has been designed like that. It needs an event on the registry
