### ISSUE TITLE
Conditional breakpoint prompt should offer to enable (not disable) breakpoints if breakpoint is already disabled

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#50569]
- Create a conditional breakpoint
- Click on the breakpoint in the gutter to get the "Disable instead of remove?" prompt
- Click "Disable breakpoint"
- Click on the breakpoint again in the gutter

The dialog that pops up asks if you want to disable the breakpoint instead of removing it; but it's already disabled. It would be better to ask if the user wants to remove it or *enable* it since it feels quite natural to re-enable it via the path you disabled it.

**Comment by isidorn** [comment]
This is a fair feature request and we accept PRs that fix this.
Code pointer https://github.com/Microsoft/vscode/blob/8f47ba52a023fa8e9707f805a7dc771170326e7a/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L201
