### ISSUE TITLE
Open editors: focus not cleared when group without editors has focus

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#50563]

**Comment by isidorn** [comment]
Fixed on branch, closing

**Comment by bpasero** [comment]
@isidorn I wonder, given that empty groups can also have focus, should the "open editors" view activate the selected group when you click it?

**Comment by isidorn** [comment]
@bpasero I think that makes sense.
The scenario I see users doing is clicking on a group in open editors then clicking shit in the explorer so it would open in that group

I just pushed a commit that changes this.

The only possible downside is that clicking on a unfocused group with editors the selection moves to the first editor. You have to click one more time on that group to keep it selected. IMHO this is fine becuase why would you want to have a selection on a group
