### ISSUE TITLE
diffEditor.renderSideBySide false shows two columns of line numbers

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#5056]
- VSCode Version:0.10.14 code-insiders
- OS Version:Windows 10

Steps to Reproduce:

1. Set "diffEditor.renderSideBySide":false
2. Select a Git controls file with changes
You will see two columns of line numbers in the left editor gutter.

**Comment by alexandrudima** [comment]
This is expected:

The line numbers on the left relate to where the content was "before"
The line numbers on the right relate to where the content is "after"

![image](https://cloud.githubusercontent.com/assets/5047891/18128659/376b351c-6f87-11e6-8952-2735e4dd1e96.png)
