### ISSUE TITLE
error with select a single word with mouse or hot key

### ISSUE THREAD

**Issue by bi-kai** [Microsoft/vscode#50561]
- VSCode Version: 1.23.1
- OS Version: win7

Steps to Reproduce:

1. double click on a word, it will select the full string with dot, like this:
![image](https://user-images.githubusercontent.com/15070379/40608357-ce9a82b6-629d-11e8-8552-bfb6209a2f49.png)
2. `ctrl+shift+right arrow key` acts the same result as above.

I just want to select a single word with mouse or hot key.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@bi-kai 

How have you configured `editor.wordSeparators`.

The default is:
```
"editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"
```

**Comment by bi-kai** [comment]
@alexandrudima Hi, I have nerver modified this param， this is my settings.json:
![image](https://user-images.githubusercontent.com/15070379/40632992-fde7aedc-631e-11e8-88ec-0ed88086560a.png)

**Comment by alexandrudima** [comment]
@bi-kai I believe you have modified this setting.

The (1) next to user settings indicates that there is a search result in your user settings. I believe you have modified this configuration and removed `.` from the list of word separators. Can you please check your user settings?

<img width="717" alt="screen shot 2018-05-29 at 09 53 41" src="https://user-images.githubusercontent.com/5047891/40645314-511acaba-6326-11e8-9250-99fc0960e73b.png">

**Comment by bi-kai** [comment]
You are right, I wander if my `user settings` was modified by some plugins, I have no idea about the existence of this config:
![image](https://user-images.githubusercontent.com/15070379/40694917-5a26f888-63f1-11e8-98cb-89770aac501b.png)

BTW, I couldn't comments some config in setting file with `json` format, will `yaml` be better?

**Comment by alexandrudima** [comment]
The `settings.json` use `JSONC` which is a variant of `JSON` that allows comments, so you can use `//` and `/* */` as you wish.
