### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by natalya-kim** [Microsoft/vscode#50565]
- VSCode Version: 1.23.1
- OS Version: Linux Mint 18.3
- NodeJS: v10.2.1
- NPM: 5.6.0

- Extensions:

| Extension      | Author     | Version |
| ------------- |:-------------:| -----:|
| vscode-markdownlint     | DavidAnson | 0.17.0 |
| todo-tree  | Gruntfuggly     |  0.0.55 |
| vsc-material-theme |  Equinusocio   |  2.1.0  |
| JSDocTagComplete |  HookyQR  |  0.0.2  |
| Russian Language Pack for VS Code | Microsoft  |  1.23  |
| vscode node readme |  bengreenier  |  3.0.2  |
| markdown-preview-github-styles |  bierner   |  0.1.2  |
| npm intellisense |  christian-kohler  |  1.3.0 |
| vscode svgviewer |  cssho   |  1.4.4  |
| vue peek |  dariofuzinato   |  1.0.2  |
| githistory |  donjayamanne   |  0.4.1  |
| gitlens |  eamodio  |  8.3.2  |
| prettier vscode |  eg2   |  1.3.1 |
| theme-gantheory |  gantheory   |  0.0.2  |
| graphql for vscode |   kumar-harsh  |  1.11.0  |
| dotenv |  mikestead   |  1.1.0  |
| vscode pugbeautify |  mrmlnc   |  1.0.2 |
| vsliveshare |  ms-vsliveshare   |  0.3.198  |
| vetur |  octref  |  0.12.3  |
| language-stylus |  sysoev |  1.9.2  |
| stylus supremacy |  thisismanta   |  2.10.1  |
| vim | vscodevim   |  0.3.198  |
| vscode-import-cost |  wix   |  2.7.0  |
| markdown-all-in-one |  yzhang   |  1.4.0  |

Steps to Reproduce:

1.Open VS Code
2.Switch between files and edit  code
2.Wait for it to crash

Console output:

```
[Extension Host] debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
%c 1: node::Abort() [/usr/share/code/libnode.so]
 2: 0x7f06546266d7 [/usr/share/code/libnode.so]
 3: %c0x7f0653deec07 [/usr/share/code/libnode.so]
 4: %c0x7f0653deeb85 [/usr/share/code/libnode.so]
 5: %cv8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/share/code/libnode.so]
 6: %c0x7f0653e3d5c8 [/usr/share/code/libnode.so]
 7: 0x7f06544004fb [/usr/share/code/libnode.so]
 8: 0x7f0654402e75 [/usr/share/code/libnode.so]
 9: 0x7f06544007b7 [/usr/share/code/libnode.so]
10: 0x7f0654403eb8 [/usr/share/code/libnode.so]
11: 0x7f06543ff734 [/usr/share/code/libnode.so]
12: %cv8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/usr/share/code/libnode.so]
13: %c0x7f065417285e [/usr/share/code/libnode.so]
14: 0x746af78437d
%c
<--- Last few GCs --->

[32723:0x150b3881a000]   190996 ms: Mark-sweep 2052.1 (2095.4) -> 2052.1 (2095.4) MB, 1545.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1546 ms) last resort 
[32723:0x150b3881a000]   192546 ms: Mark-sweep 2052.1 (2095.4) -> 2052.1 (2095.4) MB, 1549.4 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x27691ad2b959 <JS Object>
    2: selectorParts [/home/nataly/.vscode/extensions/sysoev.language-stylus-1.9.2/node_modules/stylus/lib/parser.js:~1561] [pc=0x746b043bbb8](this=0x3ebe35bdd729 <a Parser with map 0x389e8b1983b9>)
    3: selector [/home/nataly/.vscode/extensions/sysoev.language-stylus-1.9.2/node_modules/stylus/lib/parser.js:1540] [pc=0x746b023322e](this=0x3ebe35bdd729 <a Parser with map 0x389e8b1983b9>)
    4...
```
```
index.js:5 Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
onError @ index.js:5
events.js:163 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2901 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
```

Does this issue occur when all extensions are disabled : No

**Comment by weinand** [comment]
Since this does not occur when all extensions are disabled, this looks like an extension issue.
