### ISSUE TITLE
Doesn't show extension in explorer if filename contains one of char sequences: [`-C`,`-G`,`-g`,`-J`,`-O`,`-Q`,`-S`]

### ISSUE THREAD

**Issue by demeter-macik** [Microsoft/vscode#50576]
Issue Type: <b>Bug</b>

Doesn't show extension in explorer if filename contains one of char sequences: [`-C`,`-G`,`-g`,`-J`,`-O`,`-Q`,`-S`]

Explorer: 

![vscode](https://user-images.githubusercontent.com/15798474/40621331-a8a98224-629c-11e8-8f2f-3688c8c2c140.png)

File list:
```
$ ls -gnG
total 12
-rw-r--r-- 1    0 May 28 17:27  a-C.js
-rw-r--r-- 1    0 May 28 17:28  a-g.js
-rw-r--r-- 1    0 May 28 17:28  a-G.js
-rw-r--r-- 1    0 May 28 17:28  a-J.js
-rw-r--r-- 1    0 May 28 17:28  a-O.js
-rw-r--r-- 1    0 May 28 17:28  a-Q.js
-rw-r--r-- 1    0 May 28 17:28  a-S.js
-rw-r--r-- 1  261 May 28 17:02  generate.js
-rw-r--r-- 1    0 May 28 17:17 '-\.js'
drwxr-xr-x 6 4096 May 28 17:02  node_modules
-rw-r--r-- 1  198 May 28 17:02  package.json
```

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.16.5-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3727)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.53GB (2.88GB free)|
|Process Argv|/opt/visual-studio-code/code /home/macikdem/projects/storage-core.api-nodejs|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
vscode-eslint|dba|1.4.10
gitlens|eam|8.3.2
path-autocomplete|ion|1.10.0
docthis|joe|0.6.0
vscode-json5|mrm|1.0.0
bash-beautify|sha|0.1.1
code-spell-checker|str|1.6.10

</details>

**Comment by weinand** [comment]
@demeter-macik I cannot reproduce this.
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by demeter-macik** [comment]
I tried to run VS Code without extension - no changes. It doesn't show extensions (it shows `..` instead).

**Comment by demeter-macik** [comment]
Tested on other system. VS Code works fine. Must be something wuth by OS.
