### ISSUE TITLE
Contributed tree doesn't always update (request children) when change event is fired

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#50579]
I'm having a weird issue where sometimes my tree view doesn't update when I add new nodes. I've added some logging at the top of `getChildren` and also right before I call `this.onDidChangeTreeDataEmitter.fire(testNode.parent);` and it seems to be batched up (I call fire several times before it fires), but then for the next couple of updates it doesn't update at all:

<img width="991" alt="screen shot 2018-05-28 at 4 32 41 pm" src="https://user-images.githubusercontent.com/1078012/40621524-fbaaabfe-6294-11e8-87d9-2085e549d19b.png">

The text `getChildren was called!` and `Returning x items` is from the `getChildren` method. There are no errors or warnings in the console. I've checked all my nodes have unique IDs (`suite_${this.suite.path}_test_${this.test.id}`) since this caused silent failures before; but I'm not sure how to debug further.

(This repro is totally reliable, it's always the same)

cc @sandy081.

**Comment by DanTup** [comment]
If it helps, the first requests are all in quick succession, then there's a 5 second pause before the others come in (it's a 5 second delay in the middle of a test).

**Comment by sandy081** [comment]
@DanTup Is it possible to share the sample you have to reproduce?

**Comment by DanTup** [comment]
@sandy081 Let me see if I can strip it down - currently it'd need a Dart and Flutter SDK set up, but I should be able to make a small hard-coded version.

**Comment by DanTup** [comment]
In a very simple example it seems to work... I'll see if I can slowly work from one to the other and see where it starts failing.

**Comment by DanTup** [comment]
In a surprise to nobody, this turned out to be some ropey logic on my part. I presume there's some buffering of the updates which is why the delay seemed to trigger it or not.

I basically have some fake nodes in my tree that I skip over in `getChildren`/`getParent`:

```ts
ublic getChildren(element?: vs.TreeItem): vs.ProviderResult<vs.TreeItem[]> {
	if (!element) {
		return _.flatMap(Object.keys(suites).map((k) => suites[k].suites));
	} else if (element instanceof SuiteTreeItem || element instanceof GroupTreeItem) {
		// If we got a Suite and it has only a single phantom child group, then just bounce over it.
		// (but still include its tests so we can see loading...)
		if (element instanceof SuiteTreeItem && element.groups.length === 1 && !element.groups[0].group.name)
			return []
				.concat(element.tests)
				.concat(element.groups[0].groups)
				.concat(element.groups[0].tests);
		else
			console.log("not skipping...");
		return []
			.concat(element.groups)
			.concat(element.tests);
	}
}

public getParent?(element: vs.TreeItem): vs.ProviderResult<vs.TreeItem> {
	if (element instanceof GroupTreeItem || element instanceof TestTreeItem) {
		// If our parent is a phantom group at the top level, then just bounce over it.
		if (element.parent instanceof GroupTreeItem && !element.parent.group.name && element.parent.parent instanceof SuiteTreeItem)
			return element.parent.parent;
		return element.parent;
	}
}
```

However, I wasn't doing the same thing when I was calling fire - so I was calling fire for the fake parent that isn't rendered, rather than jumping over it to its parent, which is the one actually shown in the tree.

I should've removed that logic before filing the bug. Apologies!

**Comment by sandy081** [comment]
No worries.. Thanks for figuring it out.
