### ISSUE TITLE
Paste whole line after a bracket does not correctly indent 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5057]
- VSCode Version: 0.10.12-alpha (latest)
- OS Version: Windows 10

Steps to Reproduce:
1. Place cursor/caret at the end of a line and copy to copy the whole line
2. Navigate to the end of a line with an open bracket
3. Paste

Actual:
Does not correctly indent the next line after pasting:
![noindent](https://cloud.githubusercontent.com/assets/12900364/14335365/6b2103fa-fc0f-11e5-8bd6-a9bb89cfcef5.JPG)

Expected:
In VS2015 it will indent the pasted line after the bracket.

**Comment by alexandrudima** [comment]
There is now a setting `editor.formatOnPaste`.
