### ISSUE TITLE
More smart autocomplete like vim

### ISSUE THREAD

**Issue by vitahlin** [Microsoft/vscode#50571]
- VSCode Version: 1.23.1
- OS Version: macOS High Sierra 10.13.4

Vim Records:
![vimrecord](https://user-images.githubusercontent.com/6998610/40615934-7ca4aec8-62bb-11e8-818d-be608dcccac0.gif)

VSCode Records:
![vscoderecord](https://user-images.githubusercontent.com/6998610/40615950-9408c77a-62bb-11e8-8637-9793d3e778b9.gif)

When I input `ship_name` and use down or up key to toggle Suggestions, it can fill what I selected in vim, but I need to press `enter`  in VSCode. How to set config for that ?

**Comment by jrieken** [comment]
I don't really understand what you are doing in VIM. Can you please provide detailed steps that explain the desired behaviour?

**Comment by vitahlin** [comment]
Thanks for your reply.

In vim , if I input `ship_name`, there are two suggestions in the list ,at that time ,if I want to use `ship_name_list`, I just enter `DOWN`  to select the `ship_name_list`,then it can autofill `ship_name_list` and do not need to enter `TAB` or `ENTER` . 
But in VSCode, if I want to input what the VSCode suggestioned I need to press `ENTER` or `TAB` .
Sorry , my English is not well .Can you understand what I mean?

**Comment by jrieken** [comment]
> In vim , if I input ship_name, there are two suggestions in the list ,at that time

Is there a special way in which you trigger suggestions or does it always fill-in the currently selected item?

**Comment by vitahlin** [comment]
I installed plugin named `YouCompleteMe` in Vim .

**Comment by vitahlin** [comment]
Well done. Thanks for your help.
