### ISSUE TITLE
No indentation in next line with more than one colons in a line

### ISSUE THREAD

**Issue by Amblizer** [Microsoft/vscode#50582]
Issue Type: <b>Bug</b>

As the title, `for n, i in enumerate(aset):` acts normally but `for n, i in enumerate(aset[:]):` results in no additional indentation in the next line.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (25.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Document\Routine\Leetcode\0. temp.py|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
python|ms-|2018.4.0

</details>

**Comment by Tyriar** [comment]
What language is this?

**Comment by Amblizer** [comment]
I'm writing in python, and the issue still exists by now.

**Comment by rebornix** [comment]
![50582](https://user-images.githubusercontent.com/876920/45787963-b8371280-bc2c-11e8-9dbc-06787da1f0d6.gif)

This issue is not reproduceable in vanilla VSCode.
