### ISSUE TITLE
High CPU usage when opening JavaScript file with many base64 strings

### ISSUE THREAD

**Issue by derrickb** [Microsoft/vscode#50586]
- VSCode Version: 1.23.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open a .js file containing many base64 strings
2. VSCode will hang for a long time

Does this issue occur when all extensions are disabled?: Yes

Context:
I use https://github.com/berlysia/grunt-encode-asset-base64 to generate an assets.js file that looks like this:
```
var Assets = {};
Assets['image1'] = 'data:image/png;base64,...';
Assets['image2'] = 'data:image/png;base64,...';
// about 200 more
```
When opening in VSCode, the app will hang for a good ten seconds before it becomes interactive again. Once the lag is done I can scroll through assets.js just fine, but if I close it and reopen it (sometimes by accident if I meant to click the file next to it... argh) the app will lag again. I imagine VSCode is trying to parse the whole document for js-related syntax highlighting and such. Is there an optimization that can be made for variables containing base64 strings?

Right now my workaround is to name the file `assets.txt`, which loads instantly and without problems as expected.

**Comment by mjbvz** [comment]
Can you please share an example file?

Also, please test this in VS Code insiders

Thanks

**Comment by derrickb** [comment]
I've decided to avoid structuring my files this way. The issue is still present but I don't currently have time to provide a test case that isn't related to my closed-source product.
