### ISSUE TITLE
Convert to Tab/Spaces toggles render whitespace after saving

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5058]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file
2. Turn on toggle render whitespace
3. Convert tabs -> spaces or spaces -> tabs
4. Save

Actual:
Toggle render whitespace is turned off after saving.

**Comment by isidorn** [comment]
I can not reproduce this with latest VSCode alpha. What I did
1. View > Toggle Render Whitespace
2. Status bar click on Tab Size: 4 > convert indentation to spaces
3. Save
4. Render whitespace is still turned on

I tryed this with multiple combinations of the steps and failed to repro.
Let me know if you can still repro and a gif would be useful
