### ISSUE TITLE
Show Replace history for Editor find widget

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#50583]
Show Replace history for Editor find widget

**Comment by sandy081** [comment]
Follow up issue from #18233

**Comment by sandy081** [comment]
@rebornix I saw that you fixed it in #50189. I am sorry I did not inform you that I was also looking into this. Actually, I have introduced history in Search & Find in the beginning, so I thought I will finish it by fixing this :).

Anyway, I implemented in generic way here. History navigation was implemented outside the inputBox. So every time we need this feature I am duplicating it. For example, similar code is there at following places

- Search input
- Search replace
- Search pattern inputs
- Find input
- Find replace
- Problems filter
- Terminal find

I now have a HistoryInputBox widget which has history navigation. Only thing that has to be done from outside to call APIs add/show.

Let me also tell you another cool change I am doing here. At present, we have two commands (previous/next) per each input box for navigating history. Since history navigation is encapsulated in the widget, I can now have only two commands for all above input boxes. It is similar to the List widget with commands. So basically, I will remove all commands and replace them with following two commands

`input.action.historyNext`, `input.action.historyPrevious`.

This is a breaking change but worth to have.

**Comment by rebornix** [comment]
@sandy081 I remembered I saw this issue/task someday but when I was going through my debts I forgot about it. Your change is the right way to handle the history navigation and it's great that we have this `HistoryInputBox`. BTW, do you plan to adopt this component for Terminal and Webview Find box ?

**Comment by sandy081** [comment]
Yes, Terminal & Webview find widgets were also adopted.

**Comment by sandy081** [comment]
@rebornix @Tyriar @mjbvz

I see that you are using find history navigation feature in Editor, Terminal & Webview respectively. Currently each component defines its own commands for navigation. As an user if I want to customise, I have to update all these commands which is cumbersome. Hence, I have merged all these commands into two generic commands `input.action.historyNext` and `input.action.historyPrevious`. Please read [comment](https://github.com/Microsoft/vscode/issues/50583#issuecomment-395462945) for more information. Impact of this change is that the current history navigation commands will be deprecated in favour of above. 

For one milestone, I would be showing following deprecating warning message when user triggers current commands and will remove them in the following milestone.

![image](https://user-images.githubusercontent.com/10746682/41124262-aa8db846-6aa1-11e8-8eb2-144dd5742e23.png)

**Comment by roblourens** [comment]
I like this change, thanks for doing this. Please just give me a FYI @mention for stuff like this in the future, I thought it was broken for a bit :)

**Comment by rebornix** [comment]
cc @cleidigh .

**Comment by Tyriar** [comment]
LGTM 👍

**Comment by sandy081** [comment]
@roblourens Oops.. Sorry Rob.. How could I forget you... Not next time 👍

**Comment by sandy081** [comment]
@roblourens @rebornix @Tyriar @mjbvz 

FYI: Removed following commands 

```json
[

		'search.history.showNextIncludePattern',
		'search.history.showPreviousIncludePattern',
		'search.history.showNextExcludePattern',
		'search.history.showPreviousExcludePattern',
		'search.history.showNext',
		'search.history.showPrevious',
		'search.replaceHistory.showNext',
		'search.replaceHistory.showPrevious',

		'find.history.showPrevious',
		'find.history.showNext',

		'workbench.action.terminal.findWidget.history.showNext',
		'workbench.action.terminal.findWidget.history.showPrevious',

		'editor.action.extensioneditor.showNextFindTerm',
		'editor.action.extensioneditor.showPreviousFindTerm',

		'editor.action.webvieweditor.showNextFindTerm',
		'editor.action.webvieweditor.showPreviousFindTerm'

	]
```
