### ISSUE TITLE
Close button is not visible all the time in side by side editing.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5059]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1.  Launch app and open two files for side by side editing.
2. Adjust the position of the editor area and verify close button.

Actual: Close button is hiding when user adjusting editor view area.
Expected: File close button should be visible all the time.

![animation1](https://cloud.githubusercontent.com/assets/17735796/14335835/3511124c-fc13-11e5-9f77-eea6c35e6a68.gif)

**Comment by bpasero** [comment]
Fixed yesterday.
