### ISSUE TITLE
VSCode overloads CPU on delaying computer clock

### ISSUE THREAD

**Issue by yagotome** [microsoft/vscode#50597]
When I delay my clock with VSCode open, it starts to use overly CPU and make my computer so slow that I need to kill VSCode process.

- VSCode Version: 1.23.1
- OS Version: Windows 10 version 1709 OS Build 16299.431

Steps to Reproduce:

1. Open VSCode
2. Delay your clock some minutes or hours

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
I don't think that "turning back the computer clock" is a relevant scenario to support but anyway...

Please try to find out what part of VS Code puts a strain on the CPU by following these guidelines https://github.com/Microsoft/vscode/wiki/Performance-Issues and provide additional information.

**Comment by yagotome** [comment]
I know supporting that is not that relevant, but this problem may indicate some coupling in VS Code which is not pretty good, that's why I reported.

The following images are screenshots of process explorer and `code --status`, with and without extensions, respectively. In all these scenarios the problem happened.

![vscode-process-explorer-with-extensions](https://user-images.githubusercontent.com/16280594/40856328-dff48eb8-65ad-11e8-8bdb-067e0ba41511.PNG)
![code-status-with-extensions](https://user-images.githubusercontent.com/16280594/40856329-e0586ffa-65ad-11e8-8d93-acfdcaee6d63.PNG)
![vscode-process-explorer-no-extensions](https://user-images.githubusercontent.com/16280594/40856330-e07d82ae-65ad-11e8-8c96-5cc18962c8bd.PNG)
![code-status-no-extensions](https://user-images.githubusercontent.com/16280594/40856331-e0af1b66-65ad-11e8-91a4-315a8a5998dd.PNG)

**Comment by aeschli** [comment]
I also see very high numbers in out process manager, but not in the OS's process view.

**Comment by weinand** [comment]
May be the CPU load calculation we use in the VS Code Process Manager is getting confused by the time moving backwards...

**Comment by RMacfarlane** [comment]
Hmm, the IT settings on my work computer aren't letting me manually set the time. I tried using a Linux VM and it keeps resyncing the time after a minute or so, so I haven't had any luck reproducing. I'll give it a try with my laptop at home later.

From the screenshots, it looks like the CPU usage between the process explorer and Task Manager are very similar. @aeschli What OS did you see the difference on?

The `window` CPU usage looks high to me, @yagotome could you use the `Developer: Toggle Developer Tools` command and then use the `Performance` tab to collect a profile of it when the slow down is happening?

**Comment by aeschli** [comment]
@RMacfarlane I'm on linux that runs as a VM. Maybe I'm wrong given @yagotome screenshot.
I often see the process explorer showing load long after that load happened and only slowly ticking backward. If you prefer I can open a new issue just for that.

**Comment by RMacfarlane** [comment]
@aeschli Let's open a new issue for that, looks like CPU is reported incorrectly on Linux. The process explorer and `--status` are both using `ps` to get CPU usage. Linux documentation for `ps` says "CPU usage is currently expressed as the percentage of time spent running during the entire lifetime of a process.  This is not ideal, and it does not conform to the standards that ps otherwise conforms to."

**Comment by aeschli** [comment]
I created https://github.com/Microsoft/vscode/issues/51200 for that issue.

**Comment by yagotome** [comment]
@RMacfarlane I have collected a profile from `Performance` tab while that problem was happening.

[Profile-20180612T102442.zip](https://github.com/Microsoft/vscode/files/2094204/Profile-20180612T102442.zip)

![image](https://user-images.githubusercontent.com/16280594/41293341-5df30e72-6e2b-11e8-8ede-8666cd7ef7b7.png)
