### ISSUE TITLE
css and style not support less grammar

### ISSUE THREAD

**Issue by dagger9527** [Microsoft/vscode#50594]
Issue Type: <b>Bug</b>

css and style not support less grammar

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.10GB free)|
|Process Argv|E:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
vscode-svgviewer|css|1.4.4
xml|Dot|2.1.0
vue-snippets|hol|0.1.6
vscode-language-pack-zh-hans|MS-|1.23.5
vetur|oct|0.12.3
open-in-browser|tec|1.1.0
vim|vsc|0.12.0

</details>

**Comment by octref** [comment]
If you mean `<style>` in html, it only supports css.
If that's not what you mean, please be more specific in your question.
