### ISSUE TITLE
Enable variable "paths" (e.g. dot notation) to be exported in the debugger

### ISSUE THREAD

**Issue by rjmholt** [Microsoft/vscode#50598]
I'm a maintainer of the PowerShell VSCode extension and there's interest from our users in being able to right click on variables in the debugger and get a full "path" to that variable (like a dot-notation) so it could be copy-pasted into a REPL to retrieve the value itself.

An example is something like an object with the following structure:
* `foo`
    * `bar`
        * `zip`
            * `[0]`
                * `x`
                * `y`
            * `[1]`
                 * `x`
                 * `y`
            * `[2]`
                 * `x`
                 * `y`
    * `baz`

The the concept is that I could right-click on `x` under e.g. `[0]` and have the option to copy a path to it to the clipboard, as something like `foo.bar.zip[0].x`. (The `zip` array assumes that all the items are the same type, but naturally that's not necessarily the case).

The full issue is at https://github.com/PowerShell/vscode-powershell/issues/1328.

Does anything like this (or an ability to customise debugger menu items) already exist? Is there maybe already an ask for this? Otherwise, where in the VSCode source would be the jumping-in point for a feature like this?

I could imagine this being useful in other languages too, but very open to discussion. Thanks!

**Comment by isidorn** [comment]
@rjmholt thanks for the feature request. VSCode already supports this, right click on a variable -> "Copy as Expression"

If this action is disabled for powershell that means that the powershell debug adapter should implement an [`evaluateName`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1355) for each variable.

<img width="254" alt="screen shot 2018-05-29 at 10 40 19" src="https://user-images.githubusercontent.com/1926584/40647684-c5e5f4b8-632c-11e8-8cf4-57334b721a8a.png">
