### ISSUE TITLE
Missing cURL Options's Color Highlight 

### ISSUE THREAD

**Issue by JohnMagdy** [Microsoft/vscode#50590]
Issue Type: <b>Feature Request</b>

Hello everybody, so it 'd be great if you added a feature which makes the ***PHP's cURL Options*** Highlighted.

Example Options:
```
                CURLOPT_CUSTOMREQUEST
		CURLOPT_CONNECTTIMEOUT
                CURLINFO_HTTP_CODE
```
For more info: http://php.net/manual/en/function.curl-setopt.php

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:38.209Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by roblourens** [comment]
I think this would be a better fit for an extension, than the basic PHP syntax highlighter. If you want to file it upstream, that project is hosted at https://github.com/atom/language-php. But you should include more details about why this is a good idea and how it should work.
