### ISSUE TITLE
Go to Next Problem pop up is too small

### ISSUE THREAD

**Issue by newhoggy** [Microsoft/vscode#50595]
Issue Type: <b>Bug</b>

Press F8 on a very large error.

For example in the following screenshot the error does not fit in the allocated space:

![image](https://user-images.githubusercontent.com/63014/40633803-50b9bdf6-6335-11e8-861e-06a04606c2ab.png)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-markdownlint|Dav|0.17.0
vscode-docker|Pet|0.0.27
code-settings-sync|Sha|2.9.2
sort-lines|Tyr|1.7.0
vscode-hie-server|ala|0.0.17
Bookmarks|ale|0.19.1
copy-relative-path|ale|0.0.2
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.10
githistory|don|0.4.1
ocaml|hac|0.6.43
rest-client|hum|0.18.4
hoogle-vscode|jca|0.0.4
language-haskell|jus|2.5.0
terraform|mau|1.1.2
azure-account|ms-|0.4.0
gitlink|qez|0.4.2
vscode-multiclip|sle|0.1.3
stylish-haskell|vig|0.0.9

</details>

**Comment by jrieken** [comment]
@newhoggy Can you attach the code snippet and extension you are using to generate this error?
