### ISSUE TITLE
the cmd dialog left when use the win+R to start up the vscode

### ISSUE THREAD

**Issue by sigmarising** [microsoft/vscode#50596]
- VSCode Version: 1.21.3
- OS Version: windows10 1803 17134.81

Steps to Reproduce:

1. press Win + R to Run
2. type "code" and enter
3. the vscode start-up normally, but the cmd dialog left there, which I expect to disappear automatically

![1](https://user-images.githubusercontent.com/25470568/40634735-258d65a8-6329-11e8-8e5b-7562aac51752.gif)

PS. 
I once thought that there maybe some process prevent the cmd to exit when running "code". So I do the following step:

1. start-up the cmd
2. type "code" and enter
3. nothing block the cmd, I can type another sentence immediatly

![2](https://user-images.githubusercontent.com/25470568/40634881-e940283c-6329-11e8-971d-a788703ab839.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Heldenkrieger01** [comment]
I _cannot_ confirm this issue, the cmd closes on my machine as expected. Addressing the first video: there **is** something blocking the cmd from exiting, otherwise it would close / show something similar to the 2nd video. The second video is expected behavior. (similar to starting notepad etc.)

**Comment by sigmarising** [comment]
@Heldenkrieger01 

I try again on my conputer. This time I not only test the start-up of vscode but also the notepad. The Following is the screen-capture:

![1](https://user-images.githubusercontent.com/25470568/40715693-00193e1c-6439-11e8-812e-148f597fc380.gif)

When start the vscode, there is still something block the cmd from exiting. But the notepad doesn't have this problem.

---

I will do this test on other computers later.

**Comment by sigmarising** [comment]
I do the test on another two computers which run windows 10. And I reproduce the bug. 

Which operate system do you use? @Heldenkrieger01

**Comment by Northurland** [comment]
I get EXACTLY the same problem and this has happened throughout a whole year. Used system versions 1803 and 1809. 
Something may help: system default language setting: Chinese (simplified), since that's also on @sigmarising 's system.

**Comment by liuyji** [comment]
This is still happen in version 1.37 and 1.37.1, Windows 1903. Well my Windows language is also Chinese Simplified.

I will provides some details here:

1. double click code.cmd in the bin folder, the Command Prompt will not automatically exited.
2. Close VS Code will close the Command Prompt but close command prompt will not close the opened VS Code.
3. If you delete "@echo off" in the bat file you will see the Command Prompt is blocked at "endlocal" command. In fact it always blocks at the last command.
4. If you already have VS Code running, the first point is not true now, the bat will open a new window and exit normally.

**Comment by the-ress** [comment]
duplicate: #66750

**Comment by GTMoraes1** [comment]
It's 2020 and this issue is still present on a cleanly installed, US-English Windows 10 Build 2004, on a clean, freshly installed VSCode build.

One thing I noticed is that if you run "code" again, with an already open iteration of VSCode, the cmd window will disappear.
