### ISSUE TITLE
Test prompts for non-core language packs

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#50592]
Test for #45663

- [ ] Mac @chrisdias 
- [x] any @sandy081 

Complexity: 2

Below are the non-core languages for which we have language packs in the marketplace
- pt-br (Portuguese (Brazil))
- tr (Turkish)
- bg (Bulgarian)
- hu (hungarian)

Steps:
- Change OS locale to any one of the above (In Windows, you will have to install the OS language pack)
- Close all instances of VS Code
- Open VS Code. You should be prompted about the existence of a language pack in the marketplace.
- Test both `Install`, `Install and Restart` and the `Don't show me again` options.

Change the OS locale back to English, change locale in VS Code using the `Configure Display Language` command. and repeat the above tests.

**Comment by ramya-rao-a** [comment]
**Note to testers**: The prompts will be in English until the below is done by @danyeh and his team.

@danyeh To test this feature end to end, we need the language packs for the non-core languages to 
- include translations for the file [vs/platform/node/minimalTranslations](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/node/minimalTranslations.ts)
- be published using the latest version of the vsce tool (1.41.0)

Is it possible to get this done by say Wednesday?

**Comment by danyeh** [comment]
bg and hu have translation ready. Will finish publish and test by Wednesday.

**Comment by danyeh** [comment]
@ramya-rao-a , I tested on Windows OS by following the steps. I don't see any prompt (not even in English). Any other hint?
Here is what I did.
- Windows 10 - 1709
- Install pt-br, bg OS language pack.
- Set input method, display language, Language for non-Unicode programs to one of the language (either pt-br or bg)
- Install and/or launch VS Code 1.24.0-Insiders.
- Nothing happened. Checked recommended extension: Only VSTS show up.

**Comment by chrisdias** [comment]
@danyeh make sure you don't have a `locale.json` in `%APPDATA%\Code - Insiders\User`

**Comment by ramya-rao-a** [comment]
@danyeh Did you restart your machine after setting the display language? Also, like @chrisdias said, ensure you dont have the `locale.json` file. Even if you do, ensure its empty or set to the locale you are testing.

**Comment by danyeh** [comment]
Now I can see there is prompt but not the one we expect. Here is detail.
Steps:
- Windows 10 - 1709
- Install pt-br, bg OS language pack.
- Set input method, display language, Language for non-Unicode programs to one of the language (either pt-br or bg)
- Uninstall VS Code 1.24.0-Insiders. Delete AppData\Roaming\Code - Insiders; Delete %userprofile%\.vscode-insiders
- Reboot
- Install VS Code 1.24.0-Insiders.

Result:
- Prompt in English
![image](https://user-images.githubusercontent.com/19785531/40741864-812fdea8-6401-11e8-836d-035949a177ce.png)
- Click Install and Restart
- VS Code restarted as bg language UI
- There steps repro on pt-br too.

Examine resource file:
- Go to %userprofile%\.vscode-insiders
- Check main.i18n.json
- Translation exist.
![image](https://user-images.githubusercontent.com/19785531/40742160-714925e8-6402-11e8-928a-c2bc6a7265ad.png)

**Comment by ramya-rao-a** [comment]
@danyeh Did you publish the extension using the latest version of the `vsce` tool?

**Comment by danyeh** [comment]
My colleague did the publish. He confirmed vsce version is 1.41.0

**Comment by ramya-rao-a** [comment]
@joaomoreno This [commit](https://github.com/Microsoft/vscode-vsce/commit/638e4357f004c99ea97259d08d0d492f78685e9a) was made after the vsce tool was published. We need this for the core translations to appear as an asset. Can you publish another version?

@danyeh Sorry about that. Once @joaomoreno publishes the next version of the vsce tool, you/your team will have to get that version and re-publish the non-core language packs.

**Comment by sandy081** [comment]
@ramya-rao-a I tested on Windows. VSCE had an issue if the path started with `.` and @joaomoreno fixed it on Tuesday. May be he would have forgotten to publish. 

I used a test extension to test it. Its here - https://marketplace.visualstudio.com/items?itemName=sandy081.999-pack1

**Comment by joaomoreno** [comment]
Oh yeah, I did not publish. On the way: https://travis-ci.org/Microsoft/vscode-vsce/builds/386056427

**Comment by ramya-rao-a** [comment]
@danyeh Can you re-publish the language packs for the below locales using the 1.41.1 version of the vsce tool?

- pt-br (Portuguese (Brazil))
- tr (Turkish)
- bg (Bulgarian)
- hu (hungarian)

**Comment by ramya-rao-a** [comment]
Thanks @danyeh!

**Comment by ramya-rao-a** [comment]
@chrisdias Marking this test item as complete as per our discussions offline
