### ISSUE TITLE
File watcher fails over Samba share

### ISSUE THREAD

**Issue by jmm** [Microsoft/vscode#506]
The Explore sidebar doesn't always reflect the current state of the file system, e.g. I add a file from outside of vscode and it doesn't appear in Explore. I frequently have the same problem with Atom (which I also have running and which may be consuming all of the watches), but at least in Atom's tree view I can collapse, expand a folder via keyboard commands to get it to refresh. Is there a way to do it in vscode? If not, I pose it as a feature request. Thanks!

**Comment by bpasero** [comment]
@jmm the explorer should always be in sync with the file system, otherwise this indicates a problem with our file watcher. On what OS are you on? And can you reproduce the issue repeatadly?

**Comment by jmm** [comment]
@bpasero In this case I saw it while accessing a Samba share running on Linux from vscode 0.10.1 running on Win 7 x64.

> And can you reproduce the issue repeatadly?

Not sure yet -- I just tried vscode for the first time recently. And I was getting inexplicably high CPU usage (total usage much higher than the sum of the values in the CPU column in Task Manager) that I think was at least partially attributable to vscode, so I closed it for the time being. I've had nothing but problems with file watching in Atom, so I suspect I'll see this issue again in vscode.

In any case, although it would obviously be good for it to always be in sync, there's a refresh button that I can activate with the mouse to work around when it happens, but I'd like something keyboard activated as well.

**Comment by jmm** [comment]
@bpasero Ok, I still had higher CPU usage than I should've after closing vscode, then Atom crashed and I still had high CPU usage. I traced some of it to the Program Compatibility Assistant Service via an `svchost.exe` instance. With Atom not running I started vscode again and I can repro immediately: open a folder on the Samba share, go to the shell and `$ touch newfile` and it doesn't show up in Explore. Collapse, expand the subtree doesn't make it appear either. I have to click the Refresh button.

**Comment by bpasero** [comment]
Yeah, our watcher might not work reliably for network shares.

**Comment by CronLogic** [comment]
Definitely can reproduce this.  Moving folder to non-network share seems to solve any problems.

**Comment by Cirych** [comment]
Folder with source code placed on VM (CentOS) and shared via samba. That remote folder connected to windows as network drive.

New file showed in VSCode's explorer immediately, after created in remote console, on first level (folders root). If it's created on 2nd and deeper levels - just need refresh explorer.

Also problem with IntelliSense and .d.ts files
Example with Angular.
In code I can see error on "angular" word and choose download .d.ts file in pop-up menu. After downloading nothing changes with error. But, if I just open .d.ts file in VSCode - error disappear!
So another time starting VSCode I need to open each .d.ts file to remove errors.
Empty jsconfig.json created in folder, but no changes.

One more problem with downloading .d.ts files. First time I try to download any of them - I'v got error. Second time - some downloaded, some not. If I just visit "typings" folder from VSCode explorer - any file will be downloaded.

Remote - CentOS7, samba with maximum permissions.
Local - Windows Server 2012 (platform=3&osversion=6.3.9600)
VSCode - 0.10.6 (on local machine)

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-filewatcher-windows#8

**Comment by jmm** [comment]
@bpasero Can you please restore the original title of this issue and reopen it? There are 2 separate logical issues:

1. Refreshing the explorer pane via keyboard command.

1. Keeping the explorer automatically in sync with the file system.

Item # 1 is the subject and original title of this GitHub issue, but it was taken over by the other issue. That the explorer should always stay in sync with the file system is a separate issue for the following reasons:

1. It doesn't.
1. There's no telling if / when it will. (And there doesn't appear to be any activity on it since March 24 except for adding it to the *Backlog* milestone.)
1. There's already a command / control to refresh the explorer for whatever reason (we've already discussed a great one ;) -- problems with syncing). This GitHub issue is about activating it via keyboard instead of pointing device.

Thanks!

**Comment by bpasero** [comment]
@jmm try `workbench.files.action.refreshFilesExplorer` from our insiders build (http://code.visualstudio.com/Download#insiders)
