### ISSUE TITLE
html can't use emmet and can't format some minutes later

### ISSUE THREAD

**Issue by Theembers** [Microsoft/vscode#50608]
- VSCode Version: 1.23.1
- OS Version: windows 10 1803

Steps to Reproduce:

1. coding by vue  (with Vetur)
2. <template> html can't use emmet and can't format
3. <style> no prompt such as color  
4. if i restart vscode, it's working some  minutes then occur.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Please log the issue first in the repo for the [vetur extension](https://github.com/vuejs/vetur).
If it is determined there that the issue is with VS Code, then we can re-open this issue here.
