### ISSUE TITLE
C/C++ Extensions runs at 33% cpu

### ISSUE THREAD

**Issue by dreamzzzz** [Microsoft/vscode#50603]
Issue Type: <b>Bug</b>

C/C++ Extensions runs at 33% cpu, even thow the ui and code have bin idel during the night and it do not help if its minimized. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (4.68GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
tslint|eg2|1.0.30
tsimporter|pmn|1.2.14
typescript-hero|rbb|2.3.2
cmake-tools|vec|0.11.1

</details>

**Comment by tcanabrava** [comment]
not 33%, it's 100% of one core. and it runs untill it finishes parsing the project. 
maybe it should be paralelized if possible.

**Comment by dreamzzzz** [comment]
That's ok, but it for some reason never finishes. It some times gets stuck and just keeps running. The problem might be related to that the project is a Linux project that have parts of the files needed in the bash for windows that can not be found by code.  I basically using code as a editor only and running cmake/make in the bash window

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
