### ISSUE TITLE
Can't dismiss intellisense (python) by pressing the escape key

### ISSUE THREAD

**Issue by lostllama** [Microsoft/vscode#50604]
Issue Type: <b>Bug</b>

1. Cause intellisense property prompt to show up
2. press escape

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:38.209Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.60GB (2.45GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe C:\work\graphics\GenerateThumbnailPython|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.30
auto-close-tag|for|0.5.6
python|ms-|2018.4.0

</details>

**Comment by ramya-rao-a** [comment]
I dont see this issue with Python code.

@lostllama Do you have any small sample code where you can repro this consistently? If not, we dont have much to go on with.
