### ISSUE TITLE
Unable to restore serialized grid in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50609]
Steps to Reproduce:

* 1 editor, split right, split down
* Close editor to the far left
* Reload
=> boom

**Comment by beastdestroyer** [comment]
@bpasero The new grid layout looks really cool, and will help a lot with multitasking, however now it seems to open vertically rather than horizontally (opens from below rather than right) and I can't seem to drag it to the right or anything, any help on this? Thanks!

**Comment by bpasero** [comment]
@beastdestroyer the grid layout is not available yet so you are probably still using the old layout which is only 1-dimensional.
