### ISSUE TITLE
Terminal green highlight off

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#50619]
Refs: #50499

1. Have 	`"terminal.integrated.rendererType": "dom"`
2. vscode repo, open terminal 
3. do "scripts/" and tab to get completion, notice how the green highlight is off, it should show what is selected

The rendering issue here is that the scripts are by default shown in green, and the selected one is shown with no color at all -> confusing
I can not repro this with stable, thus I think the `dom` rendering is to blame

Proposed fix the highlighted one should be rendered with a selection effect, not just plain.

<img width="475" alt="screen shot 2018-05-29 at 10 57 13" src="https://user-images.githubusercontent.com/1926584/40648793-8fdecf0e-632f-11e8-8d55-933546040d07.png">

**Comment by Tyriar** [comment]
@isidorn what's the shell and plugins you're using?

**Comment by isidorn** [comment]
I use iterm / zshell on os x.

**Comment by Tyriar** [comment]
@isidorn oh-my-zsh?

**Comment by isidorn** [comment]
@Tyriar yes

**Comment by Tyriar** [comment]
@isidorn can you show what you see in an external terminal?

**Comment by isidorn** [comment]
Sure
![screen shot 2018-09-25 at 16 32 15](https://user-images.githubusercontent.com/1926584/46021274-9502dc00-c0e0-11e8-9faa-af6136eb6abb.png)

**Comment by isidorn** [comment]
I think the bot is worn ghere.
Please let me know if you need more info, removing label for now

**Comment by Tyriar** [comment]
Seems to be working now
