### ISSUE TITLE
Trying to rearrange open files causes odd selection

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5061]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:
Related to #5060

1. Open 2 files side by side
2. Grab the top bar of the file (not on the title) and try to move it straight over to the right 

![rearrangewindows](https://cloud.githubusercontent.com/assets/12900364/14336394/39393eda-fc18-11e5-9f53-9aa837673ec2.gif)

**Comment by bpasero** [comment]
Fixed yesterday.
