### ISSUE TITLE
Opening launch.json from Debug view is taking lot of time

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#50615]
Testing #49892

- Install [Java debugger](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) extension
- Open Debug view
- Click on gear icon to open launch.json

Expected: Launch.json is shown immediately
Actual: Launch.json is opened after starting the java language server (Check the status bar)

Obviously this is an extension related issue.. but wondering why is it blocking the command we own. Hence filed it here.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/37929
