### ISSUE TITLE
Debug session dropdown is shown even if there is just one session

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#50612]
Testing #49892

- Started first debug session (Attach to Extension Host)
- Started second debug session (VSCode API tests) and it got finished

Expected: Debug sessions drop down is no longer shown as there is just one session

![image](https://user-images.githubusercontent.com/10746682/40645886-ebd5dee0-6327-11e8-994a-4bd130775aa1.png)

**Comment by isidorn** [comment]
This is designed behavior, we explicitly do this after some discussions with @weinand 
We want to show that the user is in a "multi session scenario".

Closing as designed
