### ISSUE TITLE
[yaml] highlighting issue with backslash

### ISSUE THREAD

**Issue by sardorocket** [Microsoft/vscode#50618]
Issue Type: <b>Bug</b>

YAML: Highlighting has a problem, refer to the screenshot.

<img width="930" alt="screen shot 2018-05-29 at 10 52 45" src="https://user-images.githubusercontent.com/15870134/40648421-b33ec392-632e-11e8-84a4-2e3567b62a0f.png">

text
```yaml
    - name: Backup staging db
      shell: |
        mysqldump \
          -h {{ lts_mysql_host }} \
          -u {{ lts_mysql_user }} \
          -p {{ lts_mysql_password }}  \
          --max_allowed_packet=512M \
          {{ lts_mysql_database }} \
      tags:
        - lts-staging
```

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
gitignore|cod|0.5.0
systemd-unit-file|coo|1.0.0
vscode-eslint|dba|1.4.10
ansible-vault|dho|0.1.3
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
terraform-autocomplete|erd|0.0.8
flow-for-vscode|flo|0.8.1
terraform|mau|1.1.2
dotenv|mik|1.0.1
python|ms-|2018.4.0
cpptools|ms-|0.17.3
Go|ms-|0.6.80
jenkinsfile-support|sec|0.1.0
vscode-nginx|sha|0.5.0
cmake|twx|0.0.17
vscode-react-native|vsm|0.6.10
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by sardorocket** [comment]
Like in #49770 restart didn't help

**Comment by aeschli** [comment]
This issue was moved to textmate/yaml.tmbundle#25
