### ISSUE TITLE
Allow to assign a label to editor groups

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#50629]
Testing #50459

Should we maybe support renaming Open Editor groups? The current `Group 1`, `Group 2` approach is very bland. Also, the number metaphor breaks down as soon as I move groups around in the grid, the numbers can and will get out of order.

**Comment by bpasero** [comment]
I think this would be nice to have 👍

**Comment by pokemane** [comment]
I like this idea.  I was just playing around with the `layoutEditorGroups` command and thought about having names as part of the group definitions along with the size, allowing you to label your little "sub-workspaces" and keep them organized by file type, origin, relation to other files, etc.

Not sure how far I'm venturing into "this should/could be an extension" territory with this part:  Being able to specify which file extensions or tab types go in which group would be pretty rad.  Instant organization of your tabs into your favorite layout, sorted by type or extension, at one keystroke.

**Comment by JordoHeffernan** [comment]
Is this still in the works? Because this would be a great feature!

**Comment by joeythomaschaske** [comment]
I sure could use this now
