### ISSUE TITLE
Automated imports: import style "auto" not working as expected

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50622]
Refs: #50488

I would expect `"typescript.preferences.importModuleSpecifier": "auto"` to use the style of the other imports in the file but it seems to behave differently?

**Comment by mjbvz** [comment]
Thanks. The description for `"auto"` is wrong here. For paths, `"auto"` actually tries using the shortest path instead of inferring path style like we do with quotes

**Comment by mjbvz** [comment]
The setting documentation explains the behavior now. Note that non-relative paths also require setting a `baseUrl` in the `tsconfig` or `jsconfig`

**Comment by bpasero** [comment]
@mjbvz was there a change?

**Comment by mjbvz** [comment]
I clarified the setting documentation. It now explicitly says that `auto` uses the shortest path type and that you need to set a `baseUrl` for non-relative paths

**Comment by bpasero** [comment]
@mjbvz I do not see much more clarification though, I see this still:

![image](https://user-images.githubusercontent.com/900690/40832320-5d59749a-658b-11e8-892b-1d05a98f16b5.png)

**Comment by mjbvz** [comment]
The part about `"auto" infer the shortest path type`. The entry for `non-relative` also now mentions baseUrl and ts/jsconfig

**Comment by ohjames** [comment]
This isn't working for me at all. Even though `app/util/blah` is the "shortest" it chooses `../../../util/blah` for me unless I change the option to `non-relative`. `app` is shorter than `../../..`.
