### ISSUE TITLE
Automated imports: wrong preview in hover

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50620]
Refs: https://github.com/Microsoft/vscode/issues/50488

The preview shows an import that uses an absolute file path on disk even though the result is not like that (rather `import { IEditorService } from "vs/workbench/services/editor/common/editorService";`)

![image](https://user-images.githubusercontent.com/900690/40648673-4b614c58-632f-11e8-9631-5b3259a3850e.png)

**Comment by bpasero** [comment]
Hm maybe this is actually unrelated to the automated import but rather a hint how TS found the symbol. Still, would be nice to get the same module path showing up what the automated import would produce.

**Comment by mjbvz** [comment]
I believe this was fixed by TS 2.9.1 final:

<img width="1003" alt="screen shot 2018-06-01 at 2 56 51 pm" src="https://user-images.githubusercontent.com/12821956/40865204-0fa99df8-65ac-11e8-96a4-77d12b64f5a0.png">
