### ISSUE TITLE
Test: running vscode with gksudo or sudo permission

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#5062]
- @aeschli

Test plan for https://github.com/Microsoft/vscode/issues/3068

- [x] Test Ubuntu
- [x] Test Fedora

### Basic test case

```bash
sudo mkdir ~/perms-test
sudo touch ~/perms-test/file
sudo code-alpha --user-data-dir ~/root-data-dir ~/perms-test
# edit and save `file` in vscode
```

### Known limitations

- Files can only be saved if the root user has write access, you can check file permissions using `ls -la`. Example output gives `-rw-r--r--` which means user read/write, group read, all read. If the 'daniel' user owns this file, 'root' will be able to read but not save.
- Opening the browser via vscode will hang the editor, see https://github.com/Microsoft/vscode/issues/5063

**Comment by aeschli** [comment]
Running `sudo code-alpha --user-data-dir ~/root-data-dir ~/perms-test` results in

`It is recommended to start vscode as a normal user. To run as root, you must specify an alternate user data directory with the --user-data-dir argument.`

`sudo code-alpha --user-data-dir=~/root-data-dir ~/perms-test` however, works.

**Comment by Kowus** [comment]
I use Ubuntu 14.04.5 x86 and "**code-alpha**" isn't a recognized command. However, when I run 

`sudo code --user-data-dir=~/root-data-dir ~/perms-test`, it worked
