### ISSUE TITLE
Terminal find should center results in viewport

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#50623]
Refs: #50499

You probably already have issues that the find widget is getting in the way of results in the terminal.

Here I want to suggest a simple heuristic to make it come in the results less frequently.
When a find result is hit you always reveal it on the first line -> thus the chance of it overlapping with the find widget is very hight
Editor always reveals the find resutls in the center of the screen. I suggest that you do the same.
Editor has some nice methods like center if outside viewport, I would expcet the same behavior in the terminal

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/46561
