### ISSUE TITLE
[loc][Query] Context for "Outline"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#50626]
For string below community member is asking about the context? Can you please check? Thanks!

**Original comments**
BG ISSUE - What is this exactly? Some context please.
by lyubomirv, 12 days ago

**Context**
src/vs/workbench/parts/outline/electron-browser/outline.contribution:English (en):plaintext:name

**Resource**
vs_workbench_parts_outline

**String Hash**
5898cbacc2c1f9d1bf41e6c85ce441b7

**String text**
Outline

**Comment by jrieken** [comment]
The term 'Outline' is used to refer to a quick overview of a source file, e.g the structure of a source file.
