### ISSUE TITLE
Split terminal multiple times very slugish

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#50627]
Refs: #50499

I do not think this is conected to dom rendering of the terminal.
Open terminal:
Click on the split termianl like 10 times very fast -> whole vscode is slugish for the next minute and there are some visual glitches.
If this action is so heavy I would expect that it gets disabled while a new terminal is initatialising

**Comment by Tyriar** [comment]
I can't seem to repro a particular perf problem on mac or Windows, there's a slow down for a few seconds which is expected but everything is fine after that. I do notice some glitches on mac which might be worth looking into though.

**Comment by isidorn** [comment]
This might also be connected to the fact that I use zshell

**Comment by Tyriar** [comment]
@isidorn oh-my-zsh?

**Comment by Tyriar** [comment]
That shouldn't affect perf while idle though 😕

**Comment by isidorn** [comment]
@Tyriar yes

**Comment by Tyriar** [comment]
Closing this as there isn't really a fix that I'd want to do apart from improving the speed of the terminal (which is something that's always being looked into). Disabling the action while split is happening would be annoying as I often quickly hit ctrl+shift+5 twice to split twice.
