### ISSUE TITLE
Always scroll a complete line

### ISSUE THREAD

**Issue by MacDisein** [microsoft/vscode#50624]
If you scroll via mouse wheel the editor should always scroll a complete line.

![half_line](https://user-images.githubusercontent.com/8401876/40648937-f7a7f99e-632f-11e8-8691-1fe1ab36b6a7.jpg)

As you can see, line 6 is not completly visible, while scrolling with the mouse wheel the complete line should snap in.

EDIT: The same happens when scrolling via cursor keys or scroll bar.

**Comment by jtlapp** [comment]
I updated the editor today (23 Nov 2018) to v1.29.0 and the mouse wheel suddenly started scrolling by about 3.1 lines per tick.

I changed the Mouse Wheel Scroll Sensitivity in settings to .33 and now it seems to be scrolling exactly 1 line per tick.

**Comment by jtlapp** [comment]
But now scrolling with my trackpad is painfully slow. All my other apps scroll just fine, at reasonable speed. What happened to scrolling in VSC???
