### ISSUE TITLE
[loc][Query] Source text question "Select To Previous Command"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#50633]
For string below community member is asking if source is correct with "Select To"? Can you please check? Thanks!

**Original comments**
BG ISSUE
Select To? - by lyubomirv, 2 months ago

**Context**
src/vs/workbench/parts/terminal/electron-browser/terminalActions:English (en):plaintext:workbench.action.terminal.selectToPreviousCommand

**Resource**
vs_workbench_parts_terminal

**String text**
Select To Previous Command

**Comment by Tyriar** [comment]
Yes that is correct, what it does is makes a select from the current start to the previous command. Say you have this output:


```
$ abc

$def | < cursor
```

Select to previous command will select from the cursor (`|`) to the first `$`.
