### ISSUE TITLE
Split editor: Strange visual feedback on Alt

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50639]
Testing #50458

- Open an editor, move the move over the 'Split Editor Right' toolbar action
- press and release `alt` key
- when the key is released, the icon switches the images very shortly
-> Should switch when alt is released
![alt-split](https://user-images.githubusercontent.com/6461412/40652358-569d6288-6338-11e8-825d-0a675fb1b2c6.gif)

- Keep `alt` key pressend and move the mouse above the action
- Tooltip shows up and still shows 'Split editor right`
-> Should be 'Split editor below`

- Click
- the icon switches the images very shortly, looks like a flicker
![alt-split2](https://user-images.githubusercontent.com/6461412/40652520-b4d8f43e-6338-11e8-93cf-440ae91db2b1.gif)

**Comment by bpasero** [comment]
This is not really grid specific, I am just leveraging our infrastructure for alternate commands, forwarding to @isidorn

**Comment by isidorn** [comment]
This should be fixed in the latest since we changed the behavior that pressing alt swithces the command, no need for hover.
@aeschli please let me know if you still see some weirdness and I will reopen

**Comment by aeschli** [comment]
I verified that this looks good now.
