### ISSUE TITLE
Show a warning if a filename includes leading or trailing whitespace

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50631]
After https://github.com/Microsoft/vscode/issues/12013 has landed I think we could help the user avoid producing files with leading or trailing whitespace by simply showing a warning as soon as the filename has that. It would just be a hint to prevent accident whitespace in filenames. I guess it could be quite frustrating to debug an issue that only came in by having a file with whitespace, especially if it is trailing whitespace that is not possible to see in the explorer.

**Comment by isidorn** [comment]
Good idea. We can add that in the filename validator.
