### ISSUE TITLE
Settings: have a consistent opening experience

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50636]
Refs: https://github.com/Microsoft/vscode/issues/50496

I find it a bit weird that only the keybinding to open settings opens the new experience and not our other actions (e.g. from the gear menu). I would suggest to behave consistently and have clear guidance how to get back to the previous experience, possibly with a setting to always use the old experience if desired.

**Comment by bpasero** [comment]
I see that this was only there for testing purposes so I guess we can close this issue and should remember to change back to open the classic settings.

**Comment by roblourens** [comment]
I forgot about the gear menu. I'll change that next time I make the new editor the default.
