### ISSUE TITLE
Include signal in TaskProcessEndEvent

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#50637]
Issue Type: <b>Bug</b>

Testing #50577

Similar to https://nodejs.org/api/child_process.html#child_process_event_exit. A process can exit with a code OR with a signal.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T06:13:09.810Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by dbaeumer** [comment]
Good point. I will include the signal however that requires work in the terminal.

@Tyriar would you be able to provide this information?

**Comment by Tyriar** [comment]
The signal would need to be passed over from node-pty with the exit code. It doesn't need a change in node-pty if you want to give it a shot @dbaeumer.

It's emitted on the pty process: https://github.com/Microsoft/node-pty/blob/9faf0fff3958b8c8e79e60a18fe31013f9bc05e7/typings/node-pty.d.ts#L51-L57

Needs to be fetched here: 

https://github.com/Microsoft/vscode/blob/30bcdffcb3ed38fef027bf5e546ca3d769ae3752/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L74-L77

And probably passed over as a `message` as node's `process.exit` doesn't accept a signal. Then given to tasks in the same way exit code is.

**Comment by dbaeumer** [comment]
@Tyriar thanks!

**Comment by alexr00** [comment]
Since no one else has asked for this, I'm going to say it is out of scope.
