### ISSUE TITLE
[loc][Query] Context for "Notification Toast"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#50635]
For string below community member is asking about context? Can you please check? Thanks!

**Original comments**
BG ISSUE
What is this? by lyubomirv, 3 months ago

**Context**
src/vs/workbench/browser/parts/notifications/notificationsToasts:English (en):plaintext:notificationsToast

**Resource**
vs_workbench

**String text**
Notification Toast

**Comment by bpasero** [comment]
@josefhosek this is a toast:

![screen shot 2018-05-29 at 13 05 50](https://user-images.githubusercontent.com/900690/40655242-07d28c42-6341-11e8-894b-8043c678bb12.png)
