### ISSUE TITLE
[loc][Query] Context for "View"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#50630]
For string below community member is asking about the context to determine correct translation? Can you please check? Thanks!

**Original comments**
ES ISSUE
Todas las traducciones de la palabra View podrían bien significar Ver (como así veo que se ha traducido en todas ellas) o Vista.
Depende del contexto, y el contexto no existe, por lo que ambas podrían considerarse válidas.
by J0rgeSerran0, 3 days ago

**Context**
src/vs/workbench/browser/actions/toggleEditorLayout:English (en):plaintext:view

**Resource**
vs_workbench

**String Hash**
72bee30eb446ad00eb9dcffcaef7fdff

**String text**
View

**Comment by bpasero** [comment]
@josefhosek this is our command category that shows up in the commands picker:

![screen shot 2018-05-29 at 13 04 37](https://user-images.githubusercontent.com/900690/40655189-dad235a8-6340-11e8-8217-9bca34abaf69.png)
