### ISSUE TITLE
Settings: "Edit in Settings" link should be more helpful

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50647]
Refs: #50496

When clicking on the "Edit in Settings" link we should at least highlight the setting in the classic editor to be useful. Now I have to search the setting again in the old editor.

I think a better experience would be to show an embedded editor in the new settings editor and allow to type there, similar to the playground where we show small editors for typing.

**Comment by roblourens** [comment]
Now it does show just the matching setting in the json editor.
