### ISSUE TITLE
Settings: "reset" link seems like unfinished UX

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50646]
Refs: https://github.com/Microsoft/vscode/issues/50496

The new look of resetting a modified setting almost looks broken to me or at least unfinished. I think I liked the previous arrow we had much better:

![image](https://user-images.githubusercontent.com/900690/40653758-63baeebe-633c-11e8-877e-14ccb469ce6d.png)

I think we should revisit this new look. It looks unbalanced and we seem to have 2 new colors to indicate the same thing (green and blue?):

![image](https://user-images.githubusercontent.com/900690/40653791-7d698f8c-633c-11e8-9f4f-aed67e94b689.png)

**Comment by roblourens** [comment]
It's removed
