### ISSUE TITLE
Settings: folder/workspace settings tab should hide settings that cannot be applied

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50641]
Refs: #50496

When I click on folder or workspace settings, I always seem to be seeing all settings. But some settings (like `update.channel`) cannot be applied in any other scope and so should not be visible.

**Comment by octref** [comment]
Presentation wise I suggest greying those setting out and have a hover-tip that explains it.
Main motivation is with search I still want to see all matches.

**Comment by roblourens** [comment]
Yeah I can match the current editor by hiding them, or do something else. We can cover this in our user study around settings scope issues.

**Comment by bpasero** [comment]
This is very broken now. 

Scenario 1:
* open settings
* click "Workspace"
* search for "Window"
* click on "Window" settings in the tree
* click on "User"

=> workspace settings still showing

Scenario 2:
* open settings
* click on "Window" settings in tree
* search for "Window"
* click on "Window" settings in tree
* click on "Workspace"

=> all "User" settings show up even though I clicked "Workspace"

**Comment by roblourens** [comment]
Fixed with https://github.com/Microsoft/vscode/issues/57352

**Comment by bpasero** [comment]
@roblourens ok works better now, the selection in the TOC is still lost when switching between user and workspace setting.
