### ISSUE TITLE
Error in Quick open while searching for files

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#50642]
Testing #50498

- Open VS Code workspace
- Enable search providers
- Open `Quick Open...`
- Type `the`

🐛 `e.filter` is not a function

![image](https://user-images.githubusercontent.com/10746682/40653185-af50feba-633a-11e8-829f-07e27dbb0a3d.png)

**Comment by sbatten** [comment]
@roblourens this is also happening for me.

I type `actionbar.ts` and get the issue. If I type it 1 character per second, I do not encounter the issue. If I type quickly, I do get the error.
