### ISSUE TITLE
Settings: input field for value looks readonly

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50650]
Refs: #50496

![image](https://user-images.githubusercontent.com/900690/40653930-fe4cd578-633c-11e8-824f-d9d857a9e76d.png)

I feel like this setting should visually indicate that it is editable by having a border.

**Comment by roblourens** [comment]
I agree, I think we should introduce new theme tokens for controls in the settings editor.

**Comment by roblourens** [comment]
It has a border on the light themes so it's usable, will figure out full theming story in July.
