### ISSUE TITLE
Lack of feedback when searching for similar issues in extensions when reporting an issue on an extension

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#50656]
Issue Type: <b>Bug</b>

Create an issue with the issue reporter
File on an extension
Select different extensions
Expected: Feedback on whether or not there are similar issues found for the selected extension
Actual: Some extensions provide no feedback.

It's not clear if there is still a query running as there is no progress feedback.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T05:16:50.002Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.22GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.4.10
vscode-great-icons|emm|2.1.32
vscode-gutter-preview|kis|0.12.2
vscode-azureappservice|ms-|0.8.1
vscode-cosmosdb|ms-|0.7.1
azure-account|ms-|0.4.0
csharp|ms-|1.15.2
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.4.3
addDocComments|ste|0.0.8
cordova-tools|vsm|1.3.10

</details>

Found while testing: #50491

![issuereporternofeedback](https://user-images.githubusercontent.com/1704059/40655892-97336ae8-633a-11e8-890b-dea860a50c64.gif)

**Comment by RMacfarlane** [comment]
@stevencl Good catch. Some of the extensions don't provide a GitHub url to search against (or it's incorrectly formatted), so no search is done in those cases. Would text like `Unable to search for similar issues because this extension does not list a GitHub repository` make sense?

I also look at two different extension properties when "Preview on GitHub" is hit to try to find the repo and only one for search, so I'll fix it so that it's more likely to find a valid repo url

**Comment by stevencl** [comment]
I don't know if you need the full explanation, maybe 'No similar issues found' would be sufficient? Unless the user can do something with the fact that the extension doesn't list a repo?

**Comment by RMacfarlane** [comment]
@stevencl There's nothing the user can do in that case, so I went with your suggestion of showing 'No similar issues found'
