### ISSUE TITLE
Issue reporter removes option to include enabled extensions when reporting issue with extension

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#50655]
Issue Type: <b>Bug</b>

Create an issue with the issue reporter
Select 'An Extension' in the File On drop down
Actual: The 'Include my enabled extensions' checkbox disappears
Expected: The checkbox to remain in place

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T05:16:50.002Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (0.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

Found while testing https://github.com/Microsoft/vscode/issues/50491

**Comment by RMacfarlane** [comment]
This is actually by design, the idea being that if a user has narrowed a problem down to a particular extension, the list of extensions the user has is very likely not a useful piece of information to have in the bug report.
