### ISSUE TITLE
Settings: shows up as non-editable even though it is just a number?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50653]
Refs: https://github.com/Microsoft/vscode/issues/50496

I am not sure why `editor.cursorWidth` shows up as non-editable even though its value seems to be just a number?

![image](https://user-images.githubusercontent.com/900690/40654459-b39d488a-633e-11e8-8277-28a1644a320b.png)

**Comment by roblourens** [comment]
I didn't notice we have type=number and also type=integer...
