### ISSUE TITLE
Settings: toggling between modified settings and all collapses all groups

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50651]
Refs: #50496 

* click on "Show modified only"
* click again

=> the commonly used group is not expanded

**Comment by roblourens** [comment]
Is it collapsed when you click "show modified only"? Was it collapsed initially? I can't repro.

**Comment by bpasero** [comment]
![before](https://user-images.githubusercontent.com/900690/40698688-96599b1a-63d0-11e8-8470-47f345c1462e.gif)

@roblourens reproduces if none of the "Commonly Used" settings is modified.

**Comment by roblourens** [comment]
They don't collapse anymore
