### ISSUE TITLE
Issue reporter should ask before overwriting clipboard

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#50659]
Issue Type: <b>Bug</b>

Make sure there is some data in clipboard before trying this. Select some text on a webpage for example and copy it.
Create an issue with the issue reporter
Enter steps, check include system and enabled extensions.
Click Preview on GitHub
Expected: Prompt saying that there is too much data to send to GitHub, would you like to overwrite the clipboard with information that you can paste in the GitHub issue?
Actual: Data overwritten in clipboard with data from issue reporter without any prompting.

It's not clear if there is still a query running as there is no progress feedback.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T05:16:50.002Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.22GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.4.10
vscode-great-icons|emm|2.1.32
vscode-gutter-preview|kis|0.12.2
vscode-azureappservice|ms-|0.8.1
vscode-cosmosdb|ms-|0.7.1
azure-account|ms-|0.4.0
csharp|ms-|1.15.2
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.4.3
addDocComments|ste|0.0.8
cordova-tools|vsm|1.3.10

</details>

Found while testing #50491

**Comment by msftrncs** [comment]
It'd be nice if this issue could be resolved by not requiring the clipboard operation in the first place.   To do that though, GitHub would need an API that allowed submitting all the issue detail with a web request directly from VS Code, and then return a URL from which that temporarily stored issue could be retrieved by a browser.

**Comment by RMacfarlane** [comment]
@msftrncs Yeah, I'd love to not use the clipboard for this. The way to avoid that with the current GitHub API would be to actually create the issue instead of previewing it, but this would require an auth piece
