### ISSUE TITLE
Missing onDidChangeSelection-like event

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#50662]
re #50580

Maybe slight off topic but given that there are events for collapse/expand and the selection-property I think the selection change event is missing (and it feels incomplete/unfinished)

**Comment by sandy081** [comment]
Tree view has now `onDidChangeSelection` event with following object

```typescript
/**
 * The event that is fired when there is a change in [tree view's selection](#TreeView.selection)
 */
export interface TreeViewSelectionChangeEvent<T> {

	/**
	 * Selected elements.
	 */
	readonly selection: T[];

}
```
