### ISSUE TITLE
Filename number sort in explorer

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#5066]
- VSCode Version: 0.10.14-insider
- OS Version: Windows 10

Steps to Reproduce:
1. create files named `*(0-10).*`
2. note sorting order, different from windows explorer, unity3d, etc

![image](https://cloud.githubusercontent.com/assets/962340/14340961/dfa58caa-fc5a-11e5-9906-b0dea3cd9bcf.png)

![image](https://cloud.githubusercontent.com/assets/962340/14340974/02e26512-fc5b-11e5-8629-2aec79ac9854.png)

thanks

**Comment by Tyriar** [comment]
One way this could be done is to split the base name from the extension and sort with that first.

I'm not particularly for or against this. I typically pad with 0's in the rare I have files like this.

**Comment by bpasero** [comment]
Done for January.
