### ISSUE TITLE
Windows: integrated terminal doesn't automatically resize app

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#50668]
- VSCode Version 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527)
- OS Version: Windows 10 x64 (insider, build 17672)

Steps to Reproduce:

1. open the integrated terminal and resize it so that it's really small
2. type `bash` and `nano foo.txt`
3. resize the terminal panel

What happens:

nano's display isn't resized to take the new space available. This does not happen in a CMD prompt: nano's display is properly resized here.

![terminal_resize](https://user-images.githubusercontent.com/199648/40659799-99db0b7e-634f-11e8-92a7-7281f11da6ac.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
