### ISSUE TITLE
[Insiders] Renaming a file caused File Explorer to grey out but still be functional

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#50661]
- VSCode Version: Insiders 1.24.0
- OS Version: Windows 10: 1803, 17134.48

Steps to Reproduce:

1. Select a file (mine in this case was a html one)
2. Right-click and rename it
3. It might lag/freeze for a bit (that happened to me, but since I was defragging disk I thought nothing of it)
4. After it's done, you'll see it greyed out but functional

Quick Resoltuion:
1. Press F1 and click "Reload Window"
2. Just restart VSCode 

Does this issue occur when all extensions are disabled?: I cannot say for sure, it seems to have been a one-time issue that could have been caused by my PC just simply lagging, but I don't think it being greyed out and having to restart it to fix it is just my PC's fault right?

Also it seems to be a rare occurance, so i doubt it would bother many people, but you can never say for sure

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? If you see it is an issue with the extension, please file it against the extension repository itself.
