### ISSUE TITLE
Do not need two buttons to install

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#50669]
Testing #50592

When the language pack is recommended, I think a single button to Install and Restart should be enough instead of two buttons one for install and other for install and restart.

IMO, users might generally want to apply the language pack immediately after installing it from the recommendation. Note that we also show Restart notification if user chooses to install.

**Comment by ramya-rao-a** [comment]
When I added the 2 options, I was thinking of users who might be in the middle of their work and wouldn't want to restart yet. But then, on second thoughts, the prompt shows up right after window load, so the user wouldn't be doing much yet.

I'll remove the just "Install" button.
