### ISSUE TITLE
Support moving below/above two columns

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#50666]
Testing #50458 

- open the 'two columns' layout
- it would be nice to also move an editor below or above the two columns. Currently, you can only move inside one of the columns.

**Comment by bpasero** [comment]
Good point, this might make the layout more complex though. /cc @joaomoreno

**Comment by joaomoreno** [comment]
@bpasero It can be done with the indexing API... not with the view API which you are currently using. We need to think about it.
