### ISSUE TITLE
UX: Ctrl+W should not close VSCode when there are no tabs

### ISSUE THREAD

**Issue by leocb** [Microsoft/vscode#50671]
Issue Type: <b>Feature Request</b>

This is a very "opinion based" issue, so let's reach common ground together!

Since VSCode can remain open without any tabs, IMO, the Ctrl+W shortcut should not close the editor when there are no tabs left.
Google Chrome, for example, cannot exist without a tab, so it makes sense when closing the last tab the browser should close too. This is not the case with VSCode since we can still do stuff without any tabs.

I'm used to hold Ctrl+W to close all my tabs, and everytime I end up closing the editor too. This is not desired.

What do you think? should this behavior change?

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-22-generic

**Comment by bpasero** [comment]
@leocb you can just unbind that keybinding to close the window via Cmd+W from the keybindings editor. There is also a related issue that asks for showing a confirmation dialog before quitting.
