### ISSUE TITLE
VS Code becomes unresponsive for silly searches

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#50676]
Testing #50498:

- open vscode workspace with VS Code
- search for 'e'

Observe:
VS Code becomes unresponsive and the cancel button appears very late (if at all), so there is almost no chance to cancel a search.

**Comment by roblourens** [comment]
Yes, with the original search, the frontend gets complete FileMatches. With the new one, it gets a stream of individual matches which have to be merged into FileMatches. The way I do this right now is inefficient and we spend a ton of time there...
