### ISSUE TITLE
Bad sizing when running layoutEditorGroups twice

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50674]
Testing #50458

- add a new keybinding
```
    {
        "key": "Ctrl+0",
        "command": "layoutEditorGroups",
        "args": {
            "orientation": 1,
            "groups": [{ "size": 0.2 }, { "size": 0.2 }, { "size": 0.6, "groups": [{}, {}] }]
        }
    }
```
- invoke the keybinding: new empty groups are added with the sizes as specified
- invoke the keybinding again: the groups are resized, not following the sizes as specified

**Comment by bpasero** [comment]
Adding @joaomoreno, as discussed this would need a bit of support from the grid widget to deserialize a set of groups with certain layout.
