### ISSUE TITLE
Watermark in empty editors looks odd for different editor group sizes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50678]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

One suggestion that could make it look better is to scale up to the maximum size much faster than is currently being done. Instead of using `background-size: 15%` use something more like `max-width` to drive the size of the image.

![image](https://user-images.githubusercontent.com/2193314/40665951-736dc59e-6313-11e8-97cf-65ad78780975.png)

**Comment by Tyriar** [comment]
The other extreme 😄 

![image](https://user-images.githubusercontent.com/2193314/40666106-d0fd650c-6313-11e8-9a4e-a29ac1b56385.png)

**Comment by bpasero** [comment]
@Tyriar I am open for suggestions but the `max-width` thing does not work for me:

![image](https://user-images.githubusercontent.com/900690/40667502-9c23340c-6362-11e8-8336-b8f81ced7817.png)

**Comment by bpasero** [comment]
I realized that `background-size: 15%` only adjusts the width proportion of the background. Setting it to something like `background-size: 50% 50%` makes the background image adjust both in height and width depending on the container size:

![before](https://user-images.githubusercontent.com/900690/40721564-1850cc26-641a-11e8-807b-1809134707f3.gif)

I think that seems like a better solution to ensure that the background image is always centered. This approach does not allow to provide a `max-width` though.

**Comment by Tyriar** [comment]
@bpasero :+1: sizing down is better than clipping in both directions

**Comment by bpasero** [comment]
Now using a combination of max-width and background-size. The nice side effect of this change is that even for the empty case (1 group, no editors) the letterpress logo will size down when the window is small (previously it would overflow).

**Comment by bpasero** [comment]
Can be verified with:
* Windows: [Download](https://az764295.vo.msecnd.net/insider/6b1123504e0a6d6c234dbc7eea492056fcac68f8/VSCode-win32-ia32-1.24.0-insider.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/insider/08cacfaa32ca6ca092b901c013e910192d88ea1f/VSCode-darwin-insider-unsigned.zip)

**Comment by Tyriar** [comment]
Looks great, thanks @bpasero! :smile:
