### ISSUE TITLE
Allow both border top and bottom for tabs

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50677]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

I was expecting a line on the top of a tab but it doesn't work.

```
  "workbench.colorCustomizations": {
    "tab.activeBorderTop": "#FF0000"
  }
```

![image](https://user-images.githubusercontent.com/2193314/40665821-189789d4-6313-11e8-9870-78528192762b.png)

**Comment by Tyriar** [comment]
It works on Dark+, but not [my theme](https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-sapphire)?

**Comment by bpasero** [comment]
@Tyriar first of all, you cannot have both bottom border and top border, I should have stated that. Is your theme maybe defining a bottom border for the active tab?

**Comment by bpasero** [comment]
@usernamehw I am not sure how useful that is to see both borders, I would wait for enough people to ask for this before pushing it. Not a big fan of how this ends up looking:

![image](https://user-images.githubusercontent.com/900690/40668109-f8f39c0c-6363-11e8-9a3f-001725d7e283.png)

**Comment by Tyriar** [comment]
@bpasero yes it is, seems like a strange restriction (pretty sure I know why it's there though). It should be stated at the very least in the comment.

**Comment by Tyriar** [comment]
It wouldn't look too bad if the thicknesses of the lines were the same. But I'd be happy if it was just stated in the description.

**Comment by bpasero** [comment]
I can see if we can make it look good if both borders are on. For June, when grid landed.

**Comment by bpasero** [comment]
Will update the description for June and wait for more user feedback before allowing this.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/41339867-416ff1ea-6ef6-11e8-8ddb-7ccee9240a07.png)

**Comment by misolori** [comment]
Verified
![image](https://user-images.githubusercontent.com/35271042/41989058-e63cf82e-79f2-11e8-97ee-c101a1d52a83.png)
