### ISSUE TITLE
improve openSideBySideDirection setting

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50670]
Testing #50458

Playing with the setting
   ` "workbench.editor.openSideBySideDirection": "horizontal"`...

When `horizontal` is set, the split action opens an new editor on the right, splitting the editor vertically.

Why not using 'right' and 'below' as values? Even 'left' and 'above' would make sense

**Comment by bpasero** [comment]
Yeah, maybe being very specific about the direction is better.

**Comment by bpasero** [comment]
I settled on `right` and `down` to be in sync with `Split Right` and `Split Down`.

**Comment by bpasero** [comment]
Verify with builds from #50458
