### ISSUE TITLE
Disable welcome page when user is root

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5067]
I had to revert https://github.com/Microsoft/vscode/commit/ad7e861dbb9127e919bc686da162b19cbb7e2391 for some reasons:
* this change seems to cause test failures on Windows and Linux at least on our internal build machines
* you are using node-api in the common layer `process.getuid()`. if so, the entire file has to move into electron-browser namespace

**Comment by Tyriar** [comment]
@bpasero is there some place where general wrappers around electron calls can go? The ideal solution for this is to wrap all calls to `shell.openExternal`.

**Comment by bpasero** [comment]
You could add it into https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/window/electron-browser/windowService.ts

**Comment by Tyriar** [comment]
Put out this PR to solve the root problem https://github.com/electron/electron/pull/5084
