### ISSUE TITLE
Debug console window should go away when user perform build with CTRL+SHIFT+B

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5068]
- VSCode Version: 0.10.12-alpha
- OS Version: MAC and Windows10

Steps to Reproduce:
1. Launch app and open any ts project.
2. Configure tasks.json and launch.json for node.
3. Build project with CTRL+SHIFT+B and verify output in output window.
4. Now start debugging and verify output in debug window.
5. Make changes in the tasks.json or delete generated .js file and rebuild with CTRL+SHIFT+ B.

Actual: 
1. Output window is not showing up.
2.  Debug window is showing up all the time with previous execution result.
Expected: Debug window should go away and replaced with output window.

![animationforoutputwindow]
(https://cloud.githubusercontent.com/assets/17735796/14342646/02a13502-fc50-11e5-84d9-4d56cf45513a.gif)

**Comment by dbaeumer** [comment]
This is configurable in the tasks.json file. Depending on the value of the showOutput property the output window might not come to front when building. This is useful if you have a problem matcher associated which scans the output. Then the result is in the markers and there is no need to look at the output. If you use tsc in the tasks.json then the default for the output window is silent which only brings the output window to front if something 'critical' is happening when running the task (e.g. for example the command can't be found)
