### ISSUE TITLE
cursorUndo should be discoverable via the command palette

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50689]
I eventually found it when [asked on Twitter](https://twitter.com/Lumaxis/status/1001491899654356993) but it was difficult:

Step 1:

![image](https://user-images.githubusercontent.com/2193314/40670703-c23c8e3e-631e-11e8-92e9-7286a33e3149.png)

Step 2:

![image](https://user-images.githubusercontent.com/2193314/40670713-cb6ddb48-631e-11e8-9f5e-699d534139a1.png)

Step 3 (after almost giving up):

![image](https://user-images.githubusercontent.com/2193314/40670734-d8d0140e-631e-11e8-8476-b4ca0de820b9.png)

**Comment by alexandrudima** [comment]
@rebornix I don't think "Remove Selection of Last Find Match" is a good label for `cursorUndo`. I use `cursorUndo` in very many other scenarios. Some other editors call it soft undo. It undoes the cursor movements until the last edit.

**Comment by rebornix** [comment]
I followed the naming of Sublime "Soft Undo" which covers Undo Movement, Undo Selection, etc.

**Comment by Tyriar** [comment]
Cursor Undo actually seems more informative to me than Soft Undo as the latter could apply to anything.

**Comment by mjbvz** [comment]
I was confused by the label `Soft Undo` as well but the feature seems to work
