### ISSUE TITLE
Cannot drag and move empty editor groups

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50687]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

They need files opened in them to be able to move them around

**Comment by bpasero** [comment]
@Tyriar that is just not implemented because I was questioning the usefulness of such behaviour. We can wait for more user feedback on this before deciding anything.
