### ISSUE TITLE
[loc][Query] Capitalization for "Kimbie Dark Theme" and more

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#50684]
For string below community member is asking about capitalization between these pairs of strings on below screenshot, as it is not consistent now? On the left, they are all upper cases, but on the right, they are not. Can you please check? Thanks!

**Original comments**
ES ISSUE
Independientemente del nombre del tema:
Kimbie Dark o Kimbie Oscuro, creo que en inglés, "Dark" debería ir en mayúscula.
En caso contrario, la otra traducción "Kimbie Dark Theme" no estaría bien ya que no son iguales.
by J0rgeSerran0, 3 months ago

**Context**
extensions/theme-quietlight/package:English (en):plaintext:displayName

**String text**
Quiet Light Theme AND Quiet light theme for Visual Studio Code
![image](https://user-images.githubusercontent.com/18324231/40668541-147a0a6e-6365-11e8-9efc-f34f2d154f37.png)

**Comment by aeschli** [comment]
These strings are visible in the extensions viewlet:

![image](https://user-images.githubusercontent.com/6461412/40711239-f6d3a128-63fa-11e8-924d-397912f979d9.png)

One is the extension name (Capitalized as all other extension names), the other one is the extension description (Sentence capitalization, `Visual Studio Code` as a product name)

IMO all is fine and consistent. 

Please reopen if I misunderstood or you disagree.
