### ISSUE TITLE
contributed tslint-plugin still has to be specified in the tsconfig.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#50682]
- install the vscode-ts-tslint extension from the market place. This extension contributes the tslint-language- service
- rename vanilla.txt to vanilla.zip and expand it [vanilla.txt](https://github.com/Microsoft/vscode/files/2048689/vanilla.txt)
- open the vanilla folder

The tsling-language-service plugin is loaded and you will see warnings from tslint.
![image](https://user-images.githubusercontent.com/172399/40666655-8f2c00e6-6360-11e8-89a3-b38be0eb35c6.png)

No remove the plugin definition from the tsconfig.json. 
```json
{
    "compilerOptions": {
        // "plugins": [
        //     {
        //         "name": "tslint-language-service"
        //     }
        // ],
        "module": "commonjs",
        "target": "es6",
        "allowJs": true,
        "noImplicitAny": false,
        "sourceMap": false
    }
}
```

Now the plugin is no longer loaded. My understanding is that contributed TS server plugins are now automatically loaded.

**Comment by mjbvz** [comment]
Are you using the workspace version of TypeScript?

**Comment by egamma** [comment]
No, this workspace is not using the workspace version. The workspace doesn´t have a workspace version of TypeScript. 

Interestingly the `lit-hmtl` language server plugin is loaded and activated without any configuration in the tsconfig.json.

The source of the extension can be found here https://github.com/Microsoft/vscode-ts-tslint, but the VSIX had to be patched manually due to node-module dependencies see https://github.com/Microsoft/vscode-ts-tslint/blob/master/Notes.md.

**Comment by mjbvz** [comment]
Small bug in contribution, should be:

```
 "typescriptServerPlugins": [
            {
                "name": "tslint-language-service"
            }
        ]
```

I've pushed a fix. I'll also add a schema for this contribution point.

**Comment by egamma** [comment]
@mjbvz thanks for catching this! I´ve published a new version of the extension.
