### ISSUE TITLE
[loc][Query] Context for "Plus"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#50683]
For string below community member is asking for a context of "Plus"? Can you please check? Thanks!

**Original comments**
ES ISSUE
Faltaría conocer el contexto de Plus.
Puede parecer un producto como Visual Studio (de ahí que esté en mayúsculas).
Puede ser algo similar a (otros y Visual Studio).

Por lo tanto, esa parte del contexto es bueno conocerla para determinar una traducción correcta.
by J0rgeSerran0, 3 months ago

**Context**
extensions/theme-defaults/package:English (en):plaintext:description

**Resource**
theme-defaults

**String text**
The default light and dark themes (Plus and Visual Studio)

**Comment by aeschli** [comment]
The Plus is from the name of our default theme: Dark+ and Light+.

But I changed the description to avoid 'Plus'. See change set.
