### ISSUE TITLE
Default focus is very subtle in empty editor groups, not many options for themes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50686]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458 

![image](https://user-images.githubusercontent.com/2193314/40669360-9ff3d79a-631b-11e8-8118-d70b94fbe5ac.png)

For custom themes, I notice that `editorGroup.activeEmptyBackground` is available but that doesn't really seem to fit very well:

![image](https://user-images.githubusercontent.com/2193314/40669606-2b17b620-631c-11e8-984c-8adcd166acb2.png)

vs:

![image](https://user-images.githubusercontent.com/2193314/40669614-327c7f0e-631c-11e8-8d77-6222ee95c0a7.png)

Something that could work is to be able to specify the background of active and non-active editor groups. That way themes could make the non-active editor slightly darker than the rest to make it much more obvious.

**Comment by bpasero** [comment]
@Tyriar but there are two colors: `editorGroup.activeEmptyBackground` and `editorGroup.emptyBackground` for that purpose, did you try?

**Comment by Tyriar** [comment]
> I thought this issue was about making empty groups easier to see, or did I miss something?

Easier to see while also fitting the aesthetic of the theme. This is very easy to see, but it doesn't fit with the theme as no where else has such a large area filled with the "focus color" (even after dimming it to 25% opacity):

![image](https://user-images.githubusercontent.com/2193314/40672849-ddc2c67c-6324-11e8-8588-ace36c48ec23.png)

One way to make it fit with the rest of the these would be to use a darker color for all inactive editor backgrounds (both empty and non-empty) like this:

```
"editor.background": "#800000",
"editor.activeBackground": "#FF0000"
```

But the latter setting doesn't exist:

![image](https://user-images.githubusercontent.com/2193314/40672898-07fec85a-6325-11e8-9ede-a7d9bdd53f02.png)

**Comment by bpasero** [comment]
@Tyriar I am still not sure I understand the need for more colors. Given `editorGroup.activeEmptyBackground` for the background of an empty group when the group is active and `editorGroup.emptyBackground` when the empty group is inactive, can you not do whatever you want as theme author?

**Comment by bpasero** [comment]
@Tyriar I see where you are going: you actually want to be able to change the background color of active vs. inactive editor groups independent if they are empty or not. I am not 100% sure this is the right way forward though. So far we did not allow to change the background color of the editor based on being active or not. 

I have talked to Steven about this and we might want to revisit the notion of active editors vs inactive in general. 

If you agree I would mark this a duplicate of https://github.com/Microsoft/vscode/issues/2352

**Comment by bpasero** [comment]
I actually think this works quite nicely with e.g. a theme setting of:

```json
"workbench.colorCustomizations": {
    "editorGroup.emptyBackground": "#333333"
}
```

![flicker_chrome58](https://user-images.githubusercontent.com/900690/40714702-aa5edab6-6403-11e8-8314-988bbd6d19e2.gif)

**Comment by Tyriar** [comment]
Sure, let's close as duplicate of https://github.com/Microsoft/vscode/issues/2352
