### ISSUE TITLE
Snippets are being displayed in auto-complete while inside of a comment

### ISSUE THREAD

**Issue by prashantv** [Microsoft/vscode#5069]
- VSCode Version: 0.10.14-insider (0.10.14-insider) 
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Start a comment (e.g. in a .go file, start `// `
2. Write some text, and then start entering the beginning of a snippet (e.g. `main`, or `for`)
3. Press enter (expecting line break after the word `main` or `for`)

The snippet is inserted inside of the comment. 

Snippets should be disabled inside of a comment.

Attached screencast in zip:
[vscode-comment-snippet.zip](https://github.com/Microsoft/vscode/files/207893/vscode-comment-snippet.zip)

**Comment by aeschli** [comment]
Some people might want to write snippets for comment content. We don't want to prevent that.
Closing.

**Comment by prashantv** [comment]
The issue in this case is that the Go plugin defines these snippets, and knows that they are never useful for comments. If they can't be disabled completely, can the plugin specify whether the snippet should be excluded in some contexts like in a comment?

There's similar issues when writing:
"package main" - the "main" autocomplete is shown and ends up changing the code to
```go
package func main() {
}
```

Or when writing `func main` and typing enter, it becomes
```go
func func main() {
}
```

Both of which are very annoying (e.g. see https://github.com/Microsoft/vscode-go/issues/225).

It seems like snippets should be able to (optionally) specify a context for where they should be shown.
