### ISSUE TITLE
Outline view doesn't work for newly created untitled file

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#50699]
Testing #50614

* create an untitled file, my default language for untitled file is markdown
* nothing shows up in outline view
* switch to another file, say `Readme.md`
* switch back, the outline shows symbols.

**Comment by jrieken** [comment]
Likely that we first need to active the extension in question, or that the extension doesn't support untitled files...

**Comment by jrieken** [comment]
This is an issue with the markdown extension, it seems to fail to outline untitled files

**Comment by jrieken** [comment]
> I see a few second delay, but I do end up with symbols in the untitled file without opening another file.

That's likely because of a heuristic that's in place: Whenever the amount of symbols changes by a lot between two edits we delay updating. That's to prevent flicker but likely gets in your way when having empty files. See https://github.com/Microsoft/vscode/issues/49975 for details

**Comment by mjbvz** [comment]
I can't repo on bfd155e6039f64d2795c6b514a029ebd01a33527 with a simple file: 

![screen shot 2018-05-30 at 11 08 19 am](https://user-images.githubusercontent.com/12821956/40738979-d578b1ea-63f9-11e8-93e3-80745cfebd1b.png)

@rebornix Any other steps? What was the content of the new file?

**Comment by jrieken** [comment]
> now I can see the outline but it took around 2~3 seconds with one line content # a.

Yeah, that's due to aggressive back-off when the outline changes between edits. That's a heuristic to keep the outline view stable. Tho, I have pushed to change to be more aggressive when the text model is small (less than 25 lines)

**Comment by rebornix** [comment]
Sounds good to me. Feel free to close this issue.
