### ISSUE TITLE
Editor group commands are inconsistent

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50691]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

Group vs EditorGroup:

```
workbench.action.focusFirstEditorGroup
workbench.action.focusAboveGroup
workbench.action.focusActiveEditorGroup
workbench.action.focusBelowGroup
workbench.action.focusLastEditorGroup
workbench.action.focusLeftGroup
workbench.action.focusRightGroup
```

**Comment by bpasero** [comment]
I prefer to not include "editor" in the action ID and the three which still have it were previously there so I could not change them. But maybe I should add "editor" to all the new ones...

**Comment by Tyriar** [comment]
Maybe consistency is a lost cause. Here is a list of all commands that have "Group" but not "Editor" in the name:

```
workbench.action.focusNextGroup
workbench.action.focusPreviousGroup
workbench.action.focusAboveGroup
workbench.action.focusBelowGroup
workbench.action.focusLeftGroup
workbench.action.focusRightGroup
workbench.action.joinAllGroups
workbench.action.joinTwoGroups
workbench.files.action.saveAllInGroup
```

**Comment by bpasero** [comment]
Unfortunately many of the commands that have "editorGroup" in their ID existed before so I tend to leave them untouched. The majority of new commands I added do not use "editorGroup" so I pushed a change to remove more of these occurrences for the new commands. Specifically:

`workbench.action.closeEditorGroup `=> `workbench.action.closeGroup`
`workbench.action.closeAllEditorGroups` => `workbench.action.closeAllGroups`
`workbench.action.newEditorGroupLeft|Right|Up|Down` => `workbench.action.newGroupLeft|Right|Up|Down`

**Comment by bpasero** [comment]
Verify with builds from #50458
