### ISSUE TITLE
1. c/c++ plugin , the  IntelliSense is always not work. 2. Microsoft.VSCode.CPP.Extension.darwin always use cpu , even when I quit form vscode. 

### ISSUE THREAD

**Issue by CharlieCheng2014** [Microsoft/vscode#50690]
Issue Type: <b>Bug</b>

#just use the c/c++ plugins, and code c++.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.23.5
vscode-docker|Pet|0.0.27
cpptools|ms-|0.17.3
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
Please open an issue at https://github.com/Microsoft/vscode-cpptools
