### ISSUE TITLE
outline explorer is not the same as symbols view for settings editor

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#50698]
Testing #50614

This is probably intended so close if so. What I noticed is symbols view from command palette only shows symbols from right side editor but outline view combines both content from left side editor and the right one.

![image](https://user-images.githubusercontent.com/876920/40674111-b047d35a-6328-11e8-82f0-527fb31568aa.png)

**Comment by jrieken** [comment]
I don't understand tbh. What setting is a sample of showing only in the tree?

**Comment by jrieken** [comment]
@rebornix ping

**Comment by rebornix** [comment]
It turns out that I used different sorting for the outline explorer.
