### ISSUE TITLE
Settings: Make form controls consistent in shapes and alignment

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#50704]
#50496

Currently we have the sharp-cornered input boxes and round cornered `<select>`s

Would be better to apply a `border-radius: 5px` to match, or remove all rounded corners.

![slice](https://user-images.githubusercontent.com/4033249/40674798-b105642c-632a-11e8-934a-876bf605b601.png)

---

Another issue is the checkboxes look really out of the place.
`chrome://flags` made all yes/no into `<select>` so everything look clean & consistent.
You can say it's one more click, however by making all controls the same `<select>`, Chrome is able to use the filled select box as an indication for "modified".

![image](https://user-images.githubusercontent.com/4033249/40674812-be61ed66-632a-11e8-93b6-af92168c069f.png)

An alternative approach, still from Chrome, is to have all form controls right-aligned.

![image](https://user-images.githubusercontent.com/4033249/40675026-6329196e-632b-11e8-93a3-f188782b2044.png)

**Comment by roblourens** [comment]
The round-cornered dropdowns are only on macos, I can't decide whether to make all controls on the page round-cornered or square, either way they will be inconsistent with those controls elsewhere in vscode. @misolori has mocked up new checkbox designs that I will implement at some point.
