### ISSUE TITLE
Import update on file move not working for non-relative file paths

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#50707]
Testing https://github.com/Microsoft/vscode/issues/50494

Issue Type: <b>Bug</b>

Repro steps:

1. In VSCode repo, drag `issueReporterModel.ts` into a subfolder using the file explorer
2. Open `issueReporterMain.ts` , which references this file

When `updateimportsOnFileMove` is set to `prompt`, no prompt is shown, and when it's `always`, nothing happens. Works as expected when the file path in `issueReporterMain.ts` is relative.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T05:16:50.002Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/24544 to track this upstream. We should try getting this fixed for next iteration
