### ISSUE TITLE
Minimum version of nodejs to create an extension

### ISSUE THREAD

**Issue by terrymyer** [Microsoft/vscode#50701]
What is the minimum version of node.js to create extensions for vscode.
I could not find docs for this.
I found vscode uses electron 1.7.12 which uses node version 7, but vscode itself uses `8.9`, please could someone explain this.

**Comment by bpasero** [comment]
@terrymyer yes `node 7.9.0` is the version extensions are running against via electron. we typically try to keep the node.d.ts up to date for extensions to reflect this version ([here](https://github.com/Microsoft/vscode-extension-vscode/blob/master/package.json#L34)).
