### ISSUE TITLE
Settings UI text input cannot handle fast text input

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#50708]
Issue Type: <b>Bug</b>

1. Open settings preview
2. Find a setting that accepts text input (e.g. `files.defaultLanguage`)
3. Reset the setting to empty string
3. Type in the setting quickly (e.g. `markdown`)

Letters will be overwritten and reordered. You will get something like: `mrkdoaw`

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T05:16:50.002Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
Better now but https://github.com/Microsoft/vscode/issues/55803 exists
