### ISSUE TITLE
Open preview to side not working as expected with grid system

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50703]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

With the following layout:

![image](https://user-images.githubusercontent.com/2193314/40675156-c0a8c7c4-632b-11e8-8be4-b3b1c0ec6afd.png)

Opening an editor to the side will open in the group below, not to the side:

![image](https://user-images.githubusercontent.com/2193314/40675179-d9396424-632b-11e8-96b1-2c434c06ee5c.png)

**Comment by bpasero** [comment]
This is the same underlying issue as https://github.com/Microsoft/vscode/issues/50679
