### ISSUE TITLE
Splitting the editor too many times will move the workbench off screen

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50711]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

The terminal doesn't handle this particularly gracefully either but the "damage" should be contained to the overall editor container at the least:

![image](https://user-images.githubusercontent.com/2193314/40676278-203238da-632f-11e8-8988-627bf0dbe5c7.png)

**Comment by bpasero** [comment]
@joaomoreno not sure if the grid widget could do something better in that case where it overflows. Or the workbench could set some CSS property to not overflow maybe?

I would not agree with the "important" label though because it is quite easy to get out of this.

**Comment by joaomoreno** [comment]
I can take this.

**Comment by joaomoreno** [comment]
This fixes the width:

```
		// Assert Sidebar and Editor Size to not overflow
		const preferredEditorPartSize = this.parts.editor.preferredSize;
		if (editorSize.width < preferredEditorPartSize.width) {
			let diff = preferredEditorPartSize.width - editorSize.width;
			let initialDiff = diff;

			if (panelPosition === Position.BOTTOM) {
				panelDimension.width = preferredEditorPartSize.width;
			} else if (diff > 0 && (!options || options.source !== Parts.PANEL_PART)) {
				const oldWidth = panelDimension.width;
				panelDimension.width = Math.max(this.partLayoutInfo.panel.minWidth, panelDimension.width - diff);
				diff -= oldWidth - panelDimension.width;
			}

			if (sidebarSize.width > 0 && diff > 0) {
				const oldWidth = sidebarSize.width;
				sidebarSize.width = Math.max(this.partLayoutInfo.sidebar.minWidth, sidebarSize.width - diff);
				diff -= oldWidth - sidebarSize.width;
			}

			editorSize.width += initialDiff - diff;
		}
```

Moving to @bpasero

**Comment by bpasero** [comment]
Verify with builds from #50458

**Comment by Tyriar** [comment]
The damage is contained! Nice :smiley:
