### ISSUE TITLE
Allow to select multiple tabs for drag and drop (via shift key)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50713]
#50458 

Similar to modern browsers, it would be convenient to be able to shift+click to select multiple tabs to move them to another editor group while keeping the previous editor group in place.

**Comment by skyvondave** [comment]
If this is still a desirable issue from people in the community then it should be left open or put into some kind of backlog state, not closed because it somehow seems overwhelming... seems like basic project management to me.

It'll just have another "duplicate" ticket opened up when someone else wants it, like our team does.

**Comment by orlando** [comment]
I'm looking for this too, any idea where to look to get this implemented?

**Comment by Tyriar** [comment]
The issue sat here for 4 months with 0 votes on it, so it goes closed during our [annual-ish issue clean up](https://code.visualstudio.com/updates/v1_28)

**Comment by skyvondave** [comment]
So a duplicate issue should be filed?

**Comment by Kenobi-the-2nd** [comment]
I agree--this would definitely be a useful feature in my workflow. I've created another feature request [here](https://github.com/microsoft/vscode/issues/89958.). Please vote it up if you're looking for this feature.

**Comment by mayafrog** [comment]
> I agree--this would definitely be a useful feature in my workflow. I've created another feature request [here](https://github.com/microsoft/vscode/issues/89958). Please vote it up if you're looking for this feature.

Sad to see that this didn't make it into the backlog. Hopefully, they will add this one day

**Comment by Binly42** [comment]
> > I agree--this would definitely be a useful feature in my workflow. I've created another feature request [here](https://github.com/microsoft/vscode/issues/89958). Please vote it up if you're looking for this feature.
> 
> Sad to see that this didn't make it into the backlog. Hopefully they'll add it eventually

@mayafrog @Kenobi-the-2nd , Currently we may upvote https://github.com/microsoft/vscode/issues/119327 ~
