### ISSUE TITLE
workbench.action.focusNthEditorGroup commands should split right from the current editor group in some cases

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50718]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

Repro steps (Windows keybindings):

1. Open VS Code, close all editors
2. ctrl+2
3. alt+shift+o
4. ctrl+1
5. ctrl+3

I expect ctrl+3 to split right on the top editor since it's focused.

Expected:

![image](https://user-images.githubusercontent.com/2193314/40677225-e63d3460-6331-11e8-8196-fe6aa9401050.png)

Actual:

![image](https://user-images.githubusercontent.com/2193314/40677212-dbdaec7e-6331-11e8-8b15-e168a7f3e0d7.png)

**Comment by bpasero** [comment]
@Tyriar I am not sure I would agree, I tried to maintain previous behaviour: `Cmd+1` would focus the first view column, `Cmd+2` the second and `Cmd+3` the third. Now imagine you have a layout where 2 groups are opened side by side and you focus the first and press `Cmd+3`. With your model, a new group would open in the center and as such `Cmd+2` would now go to the right group and `Cmd+3` to the center group?

**Comment by bpasero** [comment]
Let's leave this up for more feedback from others. I think the scenario from https://github.com/Microsoft/vscode/issues/50718#issue-327432881 is an interesting one to support.
