### ISSUE TITLE
Intelligence works only for first open files in typescript project

### ISSUE THREAD

**Issue by krabolov** [Microsoft/vscode#5071]
- VSCode Version: at least 0.10.11 - 0.10.14-insider
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Install typings for project's dependencies. Open any file which use external libs from typings. AR == ER: autocomplete works.
2. Open any other file: typings don't work. No autocomplete, but error "Cannon find name"

**Comment by egamma** [comment]
Need more info so that I can reproduce this problem. Can you reproduce this behaviour in this sample https://github.com/Microsoft/vscode-samples/tree/master/node-express-javascript?

I don't fully understand the error condition you describe in step 2. Where does 'cannot find name' appear? Can you add an animate gif that illustrates the problem.

**Comment by krabolov** [comment]
Whew, have spent several hours on finding minimal reproducible sample. Here is the root of all evil:
1. `typings install lodash --ambient`
2. create tsconfig.json with explicit including array of included files:
`{
  "compilerOptions": {
    "target": "es3",
    "sourceMap": true
  },
  "files": [
    "typings/browser.d.ts"
  ]
}
`
3. Create first *.ts file, after typint `_.` autocomplete options for lodash appeared.
4. Create one more *.ts file, after typing `_.` no autocomplete for lodash functions appeared.

Removing "files" from tsconfig fix the problem (but in our project there is bunch of included files from different places, so this is not an option for me).

**Comment by egamma** [comment]
Thanks for coming up with a repr

>{ "compilerOptions": { "target": "es3", "sourceMap": true }, "files": [ "typings/browser.d.ts" ] } 

With this definition only the `browser.d.ts` is considered to belong to the project. If you want to work with selected files only then the correct setup is:
```
   files: ["file1.ts", "file2.ts", "typings/browser.d.ts"]
```

>but in our project there is bunch of included files from different places, so this is not an option for me

Can you try to use the `exclude` attribute (http://www.typescriptlang.org/docs/handbook/tsconfig.json.html) to define the files that should not be included. Notice that the files attribute and excludes cannot be combined.

**Comment by krabolov** [comment]
```
{
  "compilerOptions": {
    "target": "es3",
    "sourceMap": true
  },
  "files": [
    "../../typings/browser.d.ts",
    "./our_typings.d.ts",
    "./../../../one_more_proj/its_typings.d.ts",
    ...
  ]
}
```
Here is part of tsconfig from project. Problem is not in excluding some unnecessary files, but to include all needed one. They located in different directories and the only way to work with them is to put in `files`  attribute.

`browser.d.ts` was like example, it contains links on all installed typings, so including this file I also gain access to all other installed typings inside `typings/browser/` directory.

Anyway this scheme **works**, autocomplete shows hints, linter finds problems and so on. But it works **only for first opened file** (and after relaunch if this file will not be the first to open - it will not have autocomplete and errot checking). Any files that will be opened after first one will not have all those autocompletions and linter options.

So it really looks like some sort of issue that should be fixed, but not like undocumented feature :)

**Comment by krabolov** [comment]
Any updates? I can't fix project structure (it's too big and old) so this issue is a real joykiller.

**Comment by egamma** [comment]
I cannot reproduce what you describe for the scenario from your comment. I get Intellisense on both files, see the screenshots below.

I suspect that your `files` attribute is causing this issue, the source files that are exposing this problem are not in the `files` list. If you use the `files` attribute then the list must be complete.

![image](https://cloud.githubusercontent.com/assets/172399/14587230/efff540c-04af-11e6-841b-83ca89f62c10.png)

![image](https://cloud.githubusercontent.com/assets/172399/14587222/c9925c42-04af-11e6-8a0e-a3646bd40611.png)

**Comment by krabolov** [comment]
On screenshots you have opened js files, but I was speaking about ts files (as I understand tsconfig.json doesn't influenced js files). I had to write description better I agree :)

**Comment by egamma** [comment]
Actually I didn't pay enough attention (deleted the comment). Voila the same with TypeScript files. Does this setup work for you? If yes, what is the difference to your setup. My suspicion is still that your `files` attribute is causing this issue. If you use the files attribute then the list must be complete.

![image](https://cloud.githubusercontent.com/assets/172399/14604268/85fc03b6-0527-11e6-8e10-b973e7edb535.png)

![image](https://cloud.githubusercontent.com/assets/172399/14604295/a3054ce2-0527-11e6-8b95-ad1675aa4c71.png)

**Comment by krabolov** [comment]
Sorry for long silence, I was on vacation. Looks like in our project only definition files was included. According to documentation of typescript 

> Any files that are referenced by those specified in the "files" property are also included.

So I just added to `files` attributes list our entry point `app.module.ts` and everything works.

VSCode works according to documentation for tsconfig, not a bug. Thank you for your help.
