### ISSUE TITLE
Settings: Show highlight of match

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#50714]
#50496

Currently words in search query aren't highlighted, as they are in the json editor.

**Comment by roblourens** [comment]
This is by design actually, since the highlights are distracting and misleading when they don't included the synonyms and misspelled matches that bing search gives us.

**Comment by octref** [comment]
It would still be quite useful - when I type a word I want to know which part of the description / setting name it matches against. For cases like misspell or `fooBar` should match both `foo` and `bar`, we can try to handle them more gracefully (maybe ask Bing to return synonym / matched word info), but just the simple exact match would already be quite useful.

**Comment by roblourens** [comment]
> maybe ask Bing to return synonym / matched word info

We did try this but there were too many false positives and it was a bit noisy. I'll leave this open, maybe a less eye-catching highlight would help. But in user studies we saw people skipping results that didn't have a bright orange highlight, even when it was the correct answer.
