### ISSUE TITLE
Move into last group keybinding is unintuitive

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50722]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

I was expecting shift+alt+n to work as well to move into the nth group. The last group one is particularly weird since ctrl+2 targets the second group.

![image](https://user-images.githubusercontent.com/2193314/40677753-6e7791da-6333-11e8-803f-07d0f2e5f1c4.png)

**Comment by bpasero** [comment]
I changed it to `9` instead of `2`.

**Comment by bpasero** [comment]
Verify with builds from #50458
