### ISSUE TITLE
Keyboard Shortcuts message is incorrect.

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/vscode#5072]
- VSCode Version: 0.10.14
- OS Version: Windows7
- Locale: Japanese

### Current message
![workbench action cycleeditor](https://cloud.githubusercontent.com/assets/9623009/14345257/eae14122-fce6-11e5-81b2-e1c1d0c6e3fa.png)

### Correct Japanese
`現在のキーボード レイアウト用に Ctrl+@ キーまたはキー シーケンス (スペースで区切る)を押します`

**Comment by lukaschal** [comment]
Ported to loc team.

**Comment by johnliu2016** [comment]
@dbaeumer this message looks a concatenation of following 2 string in sequence with a key combination coming amid of them
`vs\editor\contrib\defineKeybinding\browser\defineKeybinding.ts
Line 33: const NLS_KB_LAYOUT_INFO_MESSAGE = nls.localize('defineKeybinding.kbLayoutInfoMessage', "For your current keyboard layout press ");`

`vs\workbench\services\keybinding\electron-browser\keybindingService.ts
Line 304: 	'description': nls.localize('keybindings.json.key', 'Key or key sequence (separated by space)'),`

**Comment by johnliu2016** [comment]
@dbaeumer suggested string is a merger of above concatenation in a grammar friendly way, but sounds not fit since they're separate dev strings. 
@YuichiNukiyama do you have better suggestion?

**Comment by johnliu2016** [comment]
@lukaschal string locations:
[defineKeybinding.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fjpn%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcontrib%2FdefineKeybinding%2Fbrowser%2FdefineKeybinding.nls.resx.lcl&version=GBmaster&_a=contents)
      <Item ItemId=";defineKeybinding.kbLayoutInfoMessage" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[For your current keyboard layout press ]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[現在のキーボード レイアウト用に押します]]></Val>
          </Tgt>
        </Str>

[keybindingService.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fjpn%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fservices%2Fkeybinding%2Felectron-browser%2FkeybindingService.nls.resx.lcl&version=GBmaster&_a=contents)
      <Item ItemId=";keybindings.json.key" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Key or key sequence (separated by space)]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[キーまたはキー シーケンス (スペースで区切る)]]></Val>
          </Tgt>
        </Str>

**Comment by lukaschal** [comment]
Fixed as suggested for now.

File: src\vs\workbench\services\keybinding\electron-browser\keybindingService.nls.resx
ID: ".resx", 0; "keybindings.json.key"
SRC: Key or key sequence (separated by space)
TGT: キーまたはキー シーケンス (スペースで区切る) を押します


File: src\vs\editor\contrib\defineKeybinding\browser\defineKeybinding.nls.resx
ID: ".resx", 0; "defineKeybinding.kbLayoutInfoMessage"
SRC: For your current keyboard layout press
TGT: 現在のキーボード レイアウト用に
