### ISSUE TITLE
Reordering activity bar forces item to be visible

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50725]
Issue Type: <b>Bug</b>

Testing #50578

**Steps**
1. Hide the `search` activity bar entry
1. Now use keyboard shortcuts to bring the search view back up
1. Notice the icon is restored while search is visible
1. Now drag the search icon in the activity bar

**Bug**
The search item is now always visible again. If you do not drag it, when you switch away from search the activity bar entry is automatically hidden

(PS. sorry for the nit-picky issues)

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T06:13:09.810Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1692061|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment]
Thanks for reporting.

Item is pinned during drag and drop. This is as per design.
