### ISSUE TITLE
Import quote style not respected on file move

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#50723]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/50494

Repro steps:

1. Set `typescript.updateImportsOnFileMove.enabled` to `always` and `typescript.preferences.quoteStyle` to `single`, no other modifications to typescript settings
2. Have folder with files `a.ts` and `b.ts`, where `b` has `import { FOO} from "./a"` using latest typescript version
3. Move `a.ts`

The quote style remains double quotes in the import statement. I think this is reasonable behavior, but from the test item text, it seems unexpected

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T05:16:50.002Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
I believe that preserving the quote style here is correct (or at least not wrong).

We can revisit this if we get more feedback
