### ISSUE TITLE
Outline View filter is inconsistent

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#50724]
Issue Type: <b>Bug</b>

Testing #50614

For this issue, I'm looking at `actionbar.ts` in the Outline View.
If I search `se` in the filter, I will get results like `HORIZONTAL_REVERSE`
If I search `tor` in the filter, I get nothing
If I search `constructor`, I get all constructors

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T05:16:50.002Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
The rule is that the first query character must be 'strong' match, those are upper-case characters, characters after separators (_,-,...), or the word start. Is it this case that's confusing: "se in the filter, I will get results like HORIZONTAL_REVERSE"?

**Comment by sbatten** [comment]
yea, since HORIZONTAL_REVERSE matches se, it seems like any suffix should match. What is the motivation in limiting to a strong match? Are there really so many symbols in one document that we need to be so strict with filtering?

**Comment by jrieken** [comment]
>  What is the motivation in limiting to a strong match

Basically because it's the same scorer we use for IntelliSense. Tho, for IntelliSense I am inclined to say that only the first occurrence of an upper-case letter is strong and subsequent aren't. Unsure if we should relax the rule the outline...

**Comment by sbatten** [comment]
I can see the case for intellisense as it is meant to be a quick way to get to a single item. In the outline case, I can see users wanting to filter to a subset of similarly named symbols that they want to quickly jump through or see a document overview. In this case, I think the a more intuitive and relaxed match makes sense. I'm open to cases against this, however.

**Comment by jrieken** [comment]
I have pushed a change to relax this a bit (and on the flip side made matching IntelliSense suggestions a little more strict). Now, the first match must not be strong. Not yet sure about this, it might now show too many changes...

<img width="250" alt="screen shot 2018-06-04 at 12 17 55" src="https://user-images.githubusercontent.com/1794099/40912364-9dce8af2-67f1-11e8-90b0-d906552b686b.png">

**Comment by sbatten** [comment]
>Now, the first match must not be strong.
Do you mean you are allowing weak matches or the first character cannot be strong?

**Comment by jrieken** [comment]
The latter, the first match must not be strong (but can be strong), both samples will match: `construc^t^o^r` and `^Team^O^rientation`.

**Comment by jrieken** [comment]
Closing and awaiting issue 🙊
