### ISSUE TITLE
Odd orange bar in activty bar in high contrast mode

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50721]
Testing #50578

Issue Type: <b>Bug</b>

**Steps**
1. In high contrast mode
1. Right click on an activity bar item
1. Dismiss the context menu without selecting anything

**Bug**
A strange orange bar remains next to the clicked item

![screen shot 2018-05-29 at 11 26 57 am](https://user-images.githubusercontent.com/12821956/40677758-727a4f84-6333-11e8-8747-6590b95ba65e.png)

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T06:13:09.810Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1692061|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment]
Not a regression. Hence moving to next milestone.

**Comment by sandy081** [comment]
It is expected as it mentions it is currently focussed element. When you open context menu and dismiss it, focus remains on the activity bar action.
