### ISSUE TITLE
Improve prompt message for installing language packs

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#50738]
Testing: https://github.com/Microsoft/vscode/issues/50592

On Mac 
Version 1.24.0-insider (1.24.0-insider)
bfd155e6039f64d2795c6b514a029ebd01a33527
2018-05-29T06:06:45.676Z

I changed my system locale to `Brazilian Portuguese` (`pt-br`) and received the following prompt:

![image](https://user-images.githubusercontent.com/1487073/40683793-62e308b6-6344-11e8-8a70-d79d20ecbf3a.png)

Suggestions for the prompt:
* Provide the language name (e.g. `Brazilian Portuguese`) and not the code. You could include the code in the prompt, after the name if so desired.
* I'm not sure we need to say that VS Code has to restart if the button says `Install and Restart`. How about this:

![image](https://user-images.githubusercontent.com/1487073/40684783-2e860bd8-6347-11e8-84ae-1da6f4139f5c.png)

**Comment by ramya-rao-a** [comment]
@chrisdias That message neither tells why the language pack needs to be installed nor why the restart is needed. I dont feel that it would drive users towards the install action. Or may be I am reading too much into it...

**Comment by ramya-rao-a** [comment]
How about this:

> Use VS Code in Portuguese by installing the language pack. A restart is needed for it to take effect.

**Comment by chrisdias** [comment]
I believe the term "Language Pack" is pretty common, so I don't know if we need to explain what it is. How about this?

> Do you want to install the Brazilian Portuguese (pt-br) language pack? A restart is required.

**Comment by ramya-rao-a** [comment]
How about?

> VS Code is now available in Portuguese. Install the language pack to get started. Requires restart.

**Comment by chrisdias** [comment]
Perhaps drop the `now` part of the message and make the last part a little less terse:

> VS Code is available in [Brazilian Portuguese]. Install the language pack to get started (a restart is required).

<<< Install and Restart >>> <<< Cancel >>>

Or make it Yes/No:

> VS Code is available in [Brazilian Portuguese]. Do you want to install the language pack? A restart is required.

<<< yes >>> <<< no >>>

**Comment by ramya-rao-a** [comment]
Done.

> VS Code is available in Bulgarian. Install the language pack to get started. A restart is required.

> VS Code is available in Bulgarian. Search for language packs in the Marketplace to get started.

**Comment by aeschli** [comment]
Verified, looks good.
I filed #50937 to improve the spacing in the message dialog so that the gear isn't confused for being part of the text.
![image](https://user-images.githubusercontent.com/6461412/40836708-02740826-6598-11e8-9a79-09d8fb877b99.png)
