### ISSUE TITLE
Keyboard shortcut for "Select All" doesn't work in certain input text fields

### ISSUE THREAD

**Issue by AlainGourves** [Microsoft/vscode#50735]
Issue Type: <b>Bug</b>

With OS X (I've tested 10.11 El Capitan and 10.12 Sierra), some input fields doesn't respond to the common `Command-A` keyboard shortcut, although `Command-X`or `Command-V` work as expected for example.

I've encountered the issue with extension related windows :

- [PlatformIO](https://github.com/platformio) : input field « Search libraries… »
- [Git History](https://github.com/DonJayamanne/gitHistoryVSCode) : input search field

"Pure" VSC search fields work as intended and they display a local menu with a right click whereas the extensions' ones doesn't.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T06:13:09.810Z)
OS version: Darwin x64 15.6.0

https://github.com/platformio/platformio-vscode-ide/issues/67

<details>
<summary>System Info</summary>
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.42GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1245488|
|Screen Reader|no|
|VM|0%|

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
beautify|Hoo|1.3.0
vscode-markdownlint|Dav|0.17.0
vscode-eslint|dba|1.4.10
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
cpptools|ms-|0.17.3
printcode|nob|2.3.0
vscode-icons|rob|7.23.0
vscode-arduino|vsc|0.2.15
html-css-class-completion|Zig|1.17.1

</details>

**Comment by octref** [comment]
Those are webviews where input aren't controlled by VS Code. Please open issue in the extension's repository.

**Comment by qweasd1** [comment]
I think this is a issue of vscode. I can reproduce in by create a webview and put an "input" inside it. The reason should be vscode first intercept the "cmd" + "a" keyboard event and map to vscode host "select all" and doesn't send the event to the input inside webview.

**Comment by octref** [comment]
@mjbvz
