### ISSUE TITLE
Outline.focus command should focus the symbol based on cursor position

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#50732]
Issue Type: <b>Feature Request</b>

Testing #50614

If I use the keyboard to navigate the open editor, the outline view does not track this and thus the outline.focus command does not focus the relevant symbol.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T05:16:50.002Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
> If I use the keyboard to navigate the open editor

Not sure what that means... Is it using the cursor keys to navigate around in an editor?

**Comment by sbatten** [comment]
@jrieken yes, that's what I meant, but I tested this today, and what I was asking for actually works. I see the follow cursor toggle in the menu now.
