### ISSUE TITLE
Git: Illegal value for `line`

### ISSUE THREAD

**Issue by offg777** [Microsoft/vscode#50736]
![image](https://user-images.githubusercontent.com/31667350/40682851-6558e2ec-6352-11e8-9226-e706a5d57e78.png)

- VSCode Version: 2.8.3
- OS Version: Windows 10

Steps to Reproduce:
1. Open Source Control
![image](https://user-images.githubusercontent.com/31667350/40682901-8f842bb2-6352-11e8-9b90-8e2040a8804d.png)

2. Select file
![image](https://user-images.githubusercontent.com/31667350/40683077-048df122-6353-11e8-9699-cd1ea2625dfd.png)

3. Select range
![image](https://user-images.githubusercontent.com/31667350/40683204-70413c3a-6353-11e8-9711-3de937c3d59e.png)

4. Click 3 dots in upper right corner, then click "Stage Selected Range"
![image](https://user-images.githubusercontent.com/31667350/40683259-a6f41b30-6353-11e8-83fa-aa9db2a1ffbc.png)

Result:
![image](https://user-images.githubusercontent.com/31667350/40682851-6558e2ec-6352-11e8-9226-e706a5d57e78.png)

What am I doing wrong?

**Comment by joaomoreno** [comment]
Does this happen with ANY range you select? If not, please provide the exact file contents and describe exactly whats the selection range you are using.

**Comment by offg777** [comment]
Any range from this file: 'page-recent-orders.component.ts'. However, when I select a range from the other files it work as expected. I can commit all the changes in the file in one commit, but I wanted to put them in different commits. Is there a way I could send this file to you privately?

**Comment by joaomoreno** [comment]
Yeah: joao dot moreno at microsoft

**Comment by offg777** [comment]
What is "joao dot moreno at microsoft"?

**Comment by joaomoreno** [comment]
joao.moreno@microsoft.com

**Comment by mvgadagi** [comment]
@joaomoreno  Can you please guide me , I am wanted to take this for fixing

**Comment by mvgadagi** [comment]
@joaomoreno can you please help me I wanted to take a look on this bug

**Comment by nkuba** [comment]
Same problem here:
Version 1.24.1
OS: macOS High Sierra 10.13.5

**Comment by jxramos** [comment]
I'm not positive how general this reproduction is but I found a pretty consistent means of reproducing it for one file I'm working on at the moment. If I have changes in the middle of the file, and the also a change at the end of the file where I delete a trailing blank line, if I try to stage the earlier changed lines but not the last deleted line change I get the `Git: illegal value for 'line'`

![deletelastline](https://user-images.githubusercontent.com/13857038/42777709-b97e6000-88ef-11e8-9e6e-e01d1be418b4.png)

**Comment by joelricci** [comment]
I'm having the same problem. Unless there as a new line after the last chunk in the file, staging fails.
See video below:

![vscode-git-error](https://user-images.githubusercontent.com/1732461/43900652-cce10d92-9be5-11e8-85c9-4f42feae9bb5.gif)

**Comment by mittalyashu** [comment]
Facing the same issue too. Not able to stage a deleted line.

**Comment by KevinSnyderCodes** [comment]
Can confirm that a deleted line at the end of the file causes this issue.

Version 1.26.1
OS: macOS High Sierra 10.13.6
