### ISSUE TITLE
Save All in Group saves files across groups instead of just the group in the current context

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#50737]
Testing #50459

- Have multiple editor groups 
- Edit files in each of the group
- Click on the `Save All in Group` button that appears on hover next to the group title on any of the groups

**Expected**: Only files in the current group are saved
**Actual**: All files across all groups are saved

**Note**: This is the same behavior in the current stable (1.23.1) as well

**Comment by isidorn** [comment]
Fixed on branch. Verified make sure you use a grid build

**Comment by roblourens** [comment]
The latest grid build doesn't have this change yet.

**Comment by ramya-rao-a** [comment]
@isidorn Why not have the fix on master? This is independent of the grid feature

**Comment by isidorn** [comment]
@ramya-rao-a because it was like this for one stable milestone already.
And we changed how we are dealing with some contexts on the grid branch so to avoid conflicts I choose to fix it on the grid branch.
Though now that I think about it, it could have gone on master.
