### ISSUE TITLE
Connect theme browsing to theme acquisition

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#5073]
cc: @joaomoreno 

We have a great theme browsing experience - however sometimes people want to add a theme and may not know how to.  We could connect the theme and the extension experiences together  and filter the extension list by themes to help the user e.g.

<img width="944" alt="screen shot 2016-04-07 at 12 02 12 pm" src="https://cloud.githubusercontent.com/assets/1051190/14347677/9de7e746-fcb8-11e5-9e1c-6f22908bbd84.png">

**Comment by joaomoreno** [comment]
@seanmcbreen If you have enough themes to fill a page, the `Find more...` will not be in view and the user will need to scroll down to see it. Should we put it at the top?

**Comment by seanmcbreen** [comment]
Good point...  I think the bottom is ok - my assumption is that is the list is long they already know how to add them in and we probably have space for it on most screen sizes (as our initial list is pretty long as well).  If however they filter the list could be cool to ensure it's still in view.

**Comment by joaomoreno** [comment]
@bpasero I've implemented this, but the `Find more extensions in the marketplace` action goes away as soon as the user types something that doesn't match it. Can you add something in the pick API which will let it always show? Perhaps an optional `filter` function per pick item, which will let me implement it as `() => true` and defaults to filtering on the label?

**Comment by bpasero** [comment]
@joaomoreno pushed and adopted in https://github.com/Microsoft/vscode/commit/b904d13d001c1325ce23b6ba814e116bd0c3f922

I added a new option to an `IPickOpenEntry` `alwaysShow`, I hope it is clear enough.

**Comment by seanmcbreen** [comment]
Could we sort the theme list by download count as a default?  Right now it's relevance which is cool but likely download count is better.  For instance most of those have screenshots in the preview.

Additionally [and I like what you did here] if the user typed in something that was not in the first list could auto search for that?  If no results show have an option to show most popular or similar?

**Comment by joaomoreno** [comment]
Many of the themes don't even have a download count, we just ship them; how would we sort them? Also, the download count information is not accessible at that point in time, since the theme picker doesn't know anything about the gallery. It could be done with some work... but,

Auto searching, placing results in the quick open widget (again) while automatic applying the theme as you go up and down... that sounds like another feature, we should create another issue and plan for it, leaving this one nicely tied up for endgame verification.
