### ISSUE TITLE
Show progress indicator for views that take a long time to load

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50730]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Clone https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample
1. Update `getChildren` to take a long time to complete using `setTimeout` or similar
1. Start VS Code and switch to the view

**Bug**
No clear progress indicator showing that the view is being loaded. There is a progress indicator when the individual child elements are being expanded

**Comment by sandy081** [comment]
Assigning to May for investigation.

**Comment by sandy081** [comment]
@mjbvz I see the progress always. May I know where you do not see it in particular?

![kapture 2018-05-30 at 12 44 51](https://user-images.githubusercontent.com/10746682/40715859-4a03b106-6407-11e8-91a6-25e8d9f87cdb.gif)

**Comment by mjbvz** [comment]
In a contributed view container, such as the one from the tree view sample, I do not see an progress indicator when the views of the container are first loaded:

![may-30-2018 10-27-54](https://user-images.githubusercontent.com/12821956/40736903-23a086c8-63f4-11e8-9bf0-2d262411e0f4.gif)

**Comment by sandy081** [comment]
Right, progress is not shown for custom view containers. This needs to add support for custom locations in progress service.
