### ISSUE TITLE
Open Editors section should scroll to show group name

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#50740]
Testing #50459

- Open multiple editor groups such that the `Open Editors` section gets a scroll bar
- Click on an editor in the last group such that the first group is now out of sight in the `Open Editors` section
- Click on the editor in the first group.

**Expected**: The corresponding file gets focus in the `Open Editors` section and user can see the group name as well.
**Actual**: The file does get focus in the `Open Editors` section, but the group name is not visible

![image](https://user-images.githubusercontent.com/16890566/40685796-1511dcce-634a-11e8-96aa-2dc0e10ef40b.png)

**Note**: This might not be important if the groups are always numbered. One can guess the number of the current group based on what comes after. But if we support naming of groups, then this might be important

**Note**: It can be possible that the first group has way too many files and an attempt to show the group name would make it impossible to show the file name. In that case we might have to give up on showing the group name

**Comment by isidorn** [comment]
This is a fair feature request, however it might provide too much jumping around if the group contains a lot of editors.
So I am not 100% convinced we need this. Leaving this open to see if more people agree with your point of view, if yes then I would be open to accept a PR tackling this. Thanks
