### ISSUE TITLE
Clarify WebviewPanelSerializer doc

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#50747]
#50696

```ts
interface WebviewPanelSerializer {
  /**
   * Restore a webview panel from its serialized `state`.
   *
   * Called when a serialized webview first becomes visible.
   *
   * @param webviewPanel Webview panel to restore. The serializer should take ownership of this panel.
   * @param state Persisted state. This state comes from the value set inside the webview by `acquireVsCodeApi().setState`.
   *
   * @return Thenable indicating that the webview has been fully restored.
   */
  deserializeWebviewPanel(webviewPanel: WebviewPanel, state: any): Thenable<void>
}
```

> Webview panel to restore.

Well, maybe being too pedantic but the item being stored is the panel's webview, not the panel. 

> The serializer should take ownership of this panel.

"The serializer should take ownership of this panel" is a bit vague.

Maybe something like "The WebviewPanel whose webview will be restored by the serializer"?

> Called when a serialized webview first becomes visible.

I suggest adding some information. It's unclear when this is called. From my testing closing -> opening new `WebviewPanel` won't get it called, but it'll get called for VS Code reload & restart.

**Comment by mjbvz** [comment]
Added notes with fae2d736aa6a0f4879f1c1c3a424476601c70246 and will be updating webview example to use persistence APIs
