### ISSUE TITLE
"Move group left/right" doesn't do anything in a couple cases

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50741]
Testing #50458

- Have this layout: 

```
A|B
A|C
```

This is 3 groups total, one taking the full left side and two others stacked on the right.

- Focus C
- Run "Move Editor Group Right"
- Nothing happens

I expect to get

```
A|B|C
A|B|C
```

If I run "Move Editor Group Left" instead I would get

```
A|C|B
A|C|B
```

which is ✔️ 

If I focus B in the initial state, this is reversed - I can run "move right" but not "move left"

**Comment by bpasero** [comment]
@roblourens currently this command expects there to be a group to the right to swap the active one with. In your example there is no group to the right of C and as such nothing happens. I can see how your desire is to move it to the right of B but I think the command cannot handle that currently and I am not sure how it could.

**Comment by roblourens** [comment]
In the case that works, you go from 2 columns to 3, so it doesn't feel like it's based on a swap. I have no idea how it works internally but from a user's perspective those 2 cases feel very similar.

**Comment by bpasero** [comment]
Maybe I can tweak the lookup to find the target group to move to by not just looking at the direction of the command but also a secondary direction.

**Comment by bpasero** [comment]
When moving I am now considering more neighbours to move to:
* Up/Down: left and right neighbour 
* Left/Right: above and below neighbour

**Comment by bpasero** [comment]
Verify with builds from #50458
