### ISSUE TITLE
"Even editor group widths" name is less accurage in grid layout

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50742]
Testing #50458

I guess it's already inaccurate with vertical splitting, but you might consider renaming this to "Even editor group sizes" or "Reset editor group sizes" or something.

**Comment by bpasero** [comment]
Yes good catch.

**Comment by bpasero** [comment]
I renamed the command but the ID is still `workbench.action.evenEditorWidths` because we had it previously and people might have bound keybindings for it.

**Comment by bpasero** [comment]
Verify with builds from #50458
