### ISSUE TITLE
Focus left/right group doesn't work in some cases

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50743]
Testing #50458

- Have two editor groups side by side
- "Focus left/right editor group" commands work correctly
- Split the second group vertically so the layout is now

```
A|B
A|C
```

- Focus A
- "Focus right editor group" does nothing

And within the B/C column, focus left/right switches between B/C which should be up/down.

**Comment by roblourens** [comment]
Not sure whether it's the same as #50679 or not

**Comment by bpasero** [comment]
Yes quite likely, this command is relying on the gridwidget giving me the groups.
