### ISSUE TITLE
global declaration no work in Multi-root Workspaces

### ISSUE THREAD

**Issue by eightHundreds** [Microsoft/vscode#50757]
- VSCode Version: 1.23.1
- OS Version: windows 10 

The global declaration will not work when file excluded by tsconfig.json and file open in multi-root workspaces

the demo

https://github.com/eightHundreds/VsCodeDebugDemo/tree/muti-root-bug-demo

1. clone
2. open vscodedebug.code-workspace
3. open project jest-with-ts
3. npm install
4. check `tests/index.test.ts` ,`it` will prompt 'Can't find name'

But if you open the `jest-with-ts` dir separately,the problem will be gone

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26667
