### ISSUE TITLE
Per-host / per-os settings

### ISSUE THREAD

**Issue by jacobdufault** [Microsoft/vscode#50754]
Currently, settings can be customized per-language

```json
{
  "[cpp]": {
    "editor.codeLens": true
  }
}
```

It'd be great to extend this to also support hostname and os name, ie,

```json
{
  "[host:home]": {
    "cquery.launch.command": "cquery.exe"
  },

  "[os:linux]": {
    "editor.smoothScrolling": true
  }
}
```

Making this work with arbitrary context-keys would be great as well, but host/os should get most of the cases.

**Comment by sardorocket** [comment]
what is the use case for this option?

**Comment by jacobdufault** [comment]
Maintaining a single settings file for use across multiple computers

**Comment by sandy081** [comment]
Duplicate of #17619
