### ISSUE TITLE
Find/replace: Keyboard shortcuts for "toggleFindCaseSensitive" and "toggleFindRegex" don't work when find has focus

### ISSUE THREAD

**Issue by shawnheide** [microsoft/vscode#50750]
- VSCode Version: 1.23.1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Open a new file
2. Open the Find widget (Command + F)
3. With focus in Find widget, press (Alt+Command+R) for `toggleFindRegex` or (Alt+Command+C) for `toggleFindCaseSensitivity`

Does this issue occur when all extensions are disabled?: Yes/No
Yes

The commands seem to be overridden by `revealFileInOS` (regex) and `copyFilePath` (case sensitivity) since they have the same keybindings with the context `!editorTextFocus`. However, the commands for `toggleFindInSelection` (Alt+Command+L) and `toggleFindWholeWord` (Alt+Command+W) seem to work since they don't have any commands with the same bindings.

**Comment by rebornix** [comment]
If you have focus in the find input box or any button inside the find widget, `toggleFindRegex` and `toggleFindCaseSensitivity` can work. If you open the find widget, and click on the result label (`x of y`), we currently think it's not focused.
