### ISSUE TITLE
New setting to group intellisense suggestions by the class where the members were declared (or overriden last)

### ISSUE THREAD

**Issue by geekley** [Microsoft/vscode#50755]
There is a feature I really miss in VS Code. It might be the only reason I'm still using MonoDevelop.

In MonoDevelop, you can **group suggestions of members** (like methods, properties, delegates, inner classes, etc) by the class where they were declared (or overriden last).

Note in the image below that the group should show **the fully qualified name** of the class with the members declared in that class. If the item is declared in a namespace, the group should be that namespace.
![image](https://user-images.githubusercontent.com/38332912/40690737-af86c27c-637e-11e8-84a7-bf03967ab10a.png)
As you can see in the image above, the suggestion shows members from System.Object last, preceded by each class/interface in the inheritance "chain".

The first group would be the actual type of the variable. It makes sense that this is grouped and appears first, since that is what you are a lot more likely to pick. So the order is extremely important.
![image](https://user-images.githubusercontent.com/38332912/40691053-7572dca4-6380-11e8-8655-46e29b773585.png)

By the way, obsolete/deprecated members appear last in the group.
![image](https://user-images.githubusercontent.com/38332912/40728437-7e888246-6400-11e8-8c14-c2ad6a457473.png)

This feature is REALLY useful, because when you are searching for a method and you don't know the exact name, you can mentally "filter" the suggestion based on where you expect the method to be declared (and ignore everything else).

Also, you can use this to quickly inspect what is declared in the class, and to know whether or not a method has been overriden (which may change expected behavior, for example).

I used C# as the example, but it should be like this for all object-oriented languages. I think it could also be implemented for javascript (though the implementation might be a little different in this case).

I believe this feature should be the default, but people may also want to disable it in some cases.
Therefore, I suggest settings like the following to control this:
```
// Controls if suggestions show items grouped by the namespace/class where they are declared
// - always: Always group items in the suggestion popup
// - whenUnfiltered: Group items only if the suggestion isn't filtered by typing part of the name
// - never: Disables grouping of items in the suggestion popup
"editor.groupSuggestions.enable": "always",

// Set to true to automatically scroll the popup to hide the first group name in suggestions
"editor.groupSuggestions.hideFirstGroupName": true
```
The second setting is also the behavior in MonoDevelop. It hides the first group so it doesn't occupy space in the popup unnecessarily.

**Comment by jrieken** [comment]
related to #50291, needs support from extensions to be doable

**Comment by nandorojo** [comment]
This would be great. I always click the wrong suggestion. At least sorting them would be nice.

**Comment by geekley** [comment]
I'd like to make an addendum: if the context of the suggestion is an instance, then it also makes sense putting static elements and constants after instance elements.
Although, in this case, it's debatable which of those two ordering criteria should have precedence, specially if grouping is implemented.

> needs support from extensions to be doable
Well, there is also an alternative way to show grouping: without headers, like Chrome Console does. Maybe that's an easier option to consider.
