### ISSUE TITLE
Desktop "freezed" after right click on a logPoint [Ubuntu]

### ISSUE THREAD

**Issue by sidati** [Microsoft/vscode#50759]
![image](https://media.giphy.com/media/2es6mfpcJsCqESmZz8/giphy.gif)

- VSCode Version: 1.23.1
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Create LogPoint in JS file
2. Click on it [mouse right click ]
=> All the desktop freezed until click `enter` which is "remove log-point" (the selected button on the pop-in window) or click on `escap`.

Does this issue occur when all extensions are disabled?: Yes/No
**YES**

**Comment by octref** [comment]
There is a native dialog when you add that logpoint. You wouldn't be able to make any edits in VS Code until you click a button on that dialog. This is as-designed.

**Comment by sidati** [comment]
But i cannot use mouse either to click on the buttons i can only use keyboards, is that expected ??

**Comment by sidati** [comment]
Beside it freezes all the desktop even the other apps 😣

**Comment by octref** [comment]
Oh OK that's unexpected. @isidorn Giving to you since it's related to log-points.

**Comment by isidorn** [comment]
Duplicate, fixed in latest

**Comment by sidati** [comment]
Hi @isidorn, do you mean the next release ? Cuz i have the latest version and i still have this issue 😅

**Comment by octref** [comment]
@sidati He meant https://code.visualstudio.com/insiders/
