### ISSUE TITLE
Find all references window out of sync

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#5075]
- VSCode Version: Version 0.10.14-insider (0.10.14-insider) - 17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c
- OS Version: OS X Yosemite

I often use the Find All References window to make code changes as it's so convenient.

However, the summaries on the right hand side become out of sync as you make code changes (specifically adding/removing lines).

See below:
![Animated gif](http://i.giphy.com/fWu8KaGXgUAgM.gif)

Not a big deal, because clicking on the next line still takes you to the right place even though it shows the wrong code!

**Comment by jrieken** [comment]
yes, the rhs preview isn't live...
