### ISSUE TITLE
Backspace, Tab and number "5" keys not working as expected

### ISSUE THREAD

**Issue by carsoni** [Microsoft/vscode#50756]
Issue Type: <b>Bug</b>

I am running Code 1.23.1 on Ubuntu 16.04 LTS and viewing remotely over VNCServer

The keys mentioned in the title are not working in vscode. 

The suggested use of "keyboard.dispatch": keyCode in various postings does not solve the problem.

The keys work in all other applications through the VNC viewer without a problem. Interestingly they also work in the text editor of the VSCode issue reporter but not in the app itself.

Using the Define KeyBinding within keybindings.json in code I was able to glean the following behaviors for the keys

Number 5:
code: backspace, keyCode:53, key: 5 => UI: Backspace, user settings: backspace, dispatch: [Backspace] 

Backspace:
code: AltLeft, keyCode:8, key: Backspace => UI: Alt, user settings: alt, dispatch: null

Tab:
code: CapsLock, keyCode:9, key: Tab => UI: CapsLock, user settings: capslock, dispatch: [CapsLock]

Thinking that it might be a locale issue I moved my locale to en_US from en_AU and rebooted. No change.
I then tried various keyboard layouts - pc105, pc104, pc102, pc101, microsoft, microsoft4000 with a reboot after each. Again no change.

Now it's 4 hours later and I need you guys to step in to help please

I'm pretty sure this is a problem relating to something in the Electron environment as I had exactly the same issues with backspace and "5"  when using Atom on the same machine however I solved that problem with a couple of coffee scripts which fire off on Atom startup. Perhaps I can do the same with VSCode? I really hope so as I would very much prefer to use your product but will have to revert to Atom if this cannot be solved.

Thanks in advance for your help
Regards
Ian Carson

That Atom code is as follows:

```
# ~/.atom/init.coffee
    Object.defineProperty global, 'functions', get: ->
      delete require.cache[require.resolve('./functions')]
      require('./functions')

    atom.keymaps.addKeystrokeResolver (keypress) ->
      functions.onFive(keypress)

    atom.keymaps.addKeystrokeResolver (keypress) ->
      functions.onPercent(keypress)

    atom.keymaps.addKeystrokeResolver (keypress) ->
      functions.onEnter(keypress)
```

and in support
```
# ~/.atom/functions.coffee

    exports.onFive = (keypress) ->
      if keypress.event.key is '5' and keypress.type isnt 'keyup'
        return '5'

    exports.onPercent = (keypress) ->
      if keypress.event.key is '%' and keypress.type isnt 'keyup'
        return '%'

    exports.onEnter = (keypress) ->
      if keypress.keystroke is 'space' and keypress.type isnt 'keyup'
        return 'enter'
```

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.4.0-127-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3686)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.31GB (28.90GB free)|
|Process Argv|/usr/share/code/code --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by carsoni** [comment]
I should also mention that I tried all of the above with 2 different keyboards my "normal" one a Microsoft Arc (wireless) and also a Logitech k120 (usb). The same behavior was exhibited by both.
Ian

**Comment by alexandrudima** [comment]
@carsoni 

> Number 5:
> code: backspace, keyCode:53, key: 5 => UI: Backspace, user settings: backspace, dispatch: [Backspace] 

Specifically, this information `dispatch: [Backspace]` tells me that dispatching is still executing on code and not keyCode.

i.e.

* go to user `settings.json`. Be sure to save the file with the contents:
```
{
    "keyboard.dispatch": "keyCode"
}
```
* restart VS Code.

**Comment by carsoni** [comment]
@alexandrudima   That's got it! Consider me suitably humbled. I hadn't saved the file - what an idiot! ;-)
