### ISSUE TITLE
Grid: Support multi-sash resizing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50769]
In the grid world (or actually in the workbench too) there are sashes that can cross. At these locations it would be nice to be able to click-and-drag to resize both sashes at once.

**Comment by rfoust** [comment]
Not sure I totally understand the description of this issue, but is this referring to being able to take a 2x1 (2 windows on top, one on bottom), and dragging the bottom one to the right to make it 1 on the left, and then 2 stacked on the right?  I could eventually do it by going to Editor Layout -> Two Columns but not by dragging the bottom editor.  Didn't want to open a new issue yet not knowing if that was a bug or feature. :)

**Comment by joaomoreno** [comment]
@rfoust Not really. This is more about supporting resizing two sashes simultaneously, if they are orthogonal to each other and intersect at some point. If a user hovers in an area surrounding that point, clicks and drags it, both sashes should be resized: one horizontally, the other vertically.

**Comment by bpasero** [comment]
@joaomoreno can we make the hit-zone to enter into the 2-dimensional resizing larger? I find it very hard to get there for some reason. It seems like a very small area where I can initiate this kind of resizing, but maybe that is on purpose?

Also, was the idea to allow this for sashes outside of the grid too or only in the grid?

**Comment by joaomoreno** [comment]
Yeah we can make it a bit larger, let me see what I can do.

This doesn't work for any two intersecting sashes, it's an opt-in thing. It is possible to get it to work for other sash combinations, even across widgets, but it requires adoption.

**Comment by joaomoreno** [comment]
@bpasero  https://github.com/Microsoft/vscode/commit/4e4fcc420ca1926051eedfe7fa1585e7da786a59

**Comment by bpasero** [comment]
Yeah thats a bit better 👍
