### ISSUE TITLE
[html] format javascript in html

### ISSUE THREAD

**Issue by apoliszk** [Microsoft/vscode#5076]
- VSCode Version:0.10.11
- OS Version:win8

Steps to Reproduce:
1. write js in a html file
2. format code
3. the indent of the second line in script tag is not right

![20160407231107](https://cloud.githubusercontent.com/assets/6794482/14356191/75b5d298-fd16-11e5-87c1-2c37be30939c.png)

**Comment by aeschli** [comment]
We currently do not format code inside HTML

**Comment by Oceanswave** [comment]
Ran into a similar situation, however in 1.2.1 JS code within script tags in a .aspx file as its indenting and line breaks removed.


Are you saying that this is a side effect of formatting code within html/aspx that code gets formatted?

E.g. HTML rules are being applied when shift-alt-f is run?

**Comment by moander** [comment]
Is this hard to implement or is it possible to just take the content of the <script> tag, run it trough whatever indentation method that is used for .js files and place the result back into the script tag?

**Comment by mrmlnc** [comment]
@moander, see #8938. @aeschli started the implementation of support nested languages.

**Comment by moander** [comment]
Cool :)

I found an extension that seems to work btw. It formats `<script>` content on save. 

```
ext install vscode-JS-CSS-HTML-formatter
```

**Comment by aeschli** [comment]
Formatting of JavaScript in HTML got added in December.
