### ISSUE TITLE
Bad fsPath checks on Windows

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50760]
I noticed that this test 
https://github.com/Microsoft/vscode/blob/43d168182c8df35a99c7f5ee0ef227de34f75fbd/src/vs/workbench/parts/preferences/common/preferencesContribution.ts#L82 and the same one here https://github.com/Microsoft/vscode/blob/43d168182c8df35a99c7f5ee0ef227de34f75fbd/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L783

can fail on Windows when resource.fsPath has a lower case drive letter and `appSettingsPath` has an upper case drive letter. @bpasero I think we are trying to enforce a lower case drive letter inside vscode, right? Is the environmentService wrong or should this just be a case-insensitive comparison?

**Comment by bpasero** [comment]
@roblourens if you use `URI.fsPath`, the drive letter will always be normalised to be lowercase. It could be that we are not doing the right thing for the environmentservice though, good catch.

**Comment by bpasero** [comment]
I am seeing some more usages of `fsPath === xyz` that might need a revisit:
* @mjbvz https://github.com/Microsoft/vscode/blob/e77bbc0af7cbd41e7cb0ffae2f1c926a45ca702b/extensions/markdown-language-features/src/commands/openDocumentLink.ts#L49
* @joaomoreno https://github.com/Microsoft/vscode/blob/d49246788f83d555cf26bfde69044ee3fbce9faf/extensions/git/src/contentProvider.ts#L133
* @joaomoreno https://github.com/Microsoft/vscode/blob/d49246788f83d555cf26bfde69044ee3fbce9faf/extensions/git/src/commands.ts#L1740

**Comment by joaomoreno** [comment]
Thanks for looking out. Pushed changes to git.

**Comment by isidorn** [comment]
@mjbvz your change makes an assumption to work with local files. Can't you instead do a uri.parse and comapre uri.toString()
You are also not covering the case that you might be non on linux and that the casing differ.
Reopening so you consider this and moving to June.

**Comment by mjbvz** [comment]
This is the right check in my understanding. `fspath` normalizes drive letter case and slash style for windows style paths. It is the same as `.path` for non local paths. Using `fspath` instead of `toString` fixed a number of casing bugs in markdown

**Comment by mjbvz** [comment]
That's #12448
