### ISSUE TITLE
Remove "File is a CommonJS module; it may be converted to an ES6 module" suggestion

### ISSUE THREAD

**Issue by medikoo** [Microsoft/vscode#50767]
Putting it at every require is just not right, as still in many cases it's better to stick to CJS than to ESM.
So putting such message is quite annoying.

- CJS is great modules format when we want to target pre ES2017 implementations without transpilation (it's format that bundles directly with no syntax changes, even to ES3 engines, ESM will always require transpilation step)
- There is no plan to remove or deprecate CJS in Node.js. ESM is being added there as a second format, and due to richer functionality of CJS (e.g. public access to cache), one may still prefer to write CJS for Node.js programs.
- ESM still doesn't work reliably in many enviroments (e.g. in Node.js it's just behind experimental-flag, and it's likely this implementation will change)

Related issue: https://github.com/Microsoft/vscode/issues/47299

**Comment by mjbvz** [comment]
Try vscode insiders

https://github.com/Microsoft/TypeScript/issues/23391

**Comment by medikoo** [comment]
> Try vscode insiders. We adjusted when they show up

Great to hear that. Adding this info at #47299 will reduce confusion
