### ISSUE TITLE
Diff/Compare with Clipboard

### ISSUE THREAD

**Issue by n3rd4i** [Microsoft/vscode#50765]
- VSCode Version: 1.23.1
- OS Version: 10.0.16299.431

Steps to Reproduce:

1. Select text from any textbox and Copy (to clipboard) (can be from vscode or outside)
2. Right-click any Vscode text and select "Compare with Clipboard"

Does this issue occur when all extensions are disabled?: Yes

![1_30-05-2018 09-14-25](https://user-images.githubusercontent.com/7346660/40705126-5cd331c0-63ea-11e8-9b32-fc50e69b5a6e.png)
![2_30-05-2018 09-14-18](https://user-images.githubusercontent.com/7346660/40705132-61302660-63ea-11e8-88e8-7898ce1917a7.png)

**Comment by bpasero** [comment]
That exists:

![image](https://user-images.githubusercontent.com/900690/40710138-2a520556-63f8-11e8-901a-ed79bc003e46.png)

**Comment by n3rd4i** [comment]
The point was to compare it with selected text from Vscode file, not with the whole file.
