### ISSUE TITLE
CPU High occupancy rate

### ISSUE THREAD

**Issue by sbbs3626** [Microsoft/vscode#50761]
Issue Type: <b>Bug</b>

Visual Code for MacBook Pro,if I install php debug,the cpu will be 98%,and temperature rise

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.17.0
vsc-material-theme|Equ|2.1.0
beautify|Hoo|1.3.0
vscode-language-pack-zh-hans|MS-|1.23.5
code-settings-sync|Sha|2.9.2
vscode-javascript-snippet-pack|aka|0.1.5
path-intellisense|chr|1.4.2
cssrem|cip|0.0.3
jshint|dba|0.10.18
vscode-eslint|dba|1.4.10
jquerysnippets|don|0.0.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.4
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.6
jquery-snippets|Hri|1.0.0
githd|hui|1.1.4
svn-scm|joh|1.29.0
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.5.0
easy-less|mrc|1.4.5
vscode-autoprefixer|mrm|2.1.2
vscode-csscomb|mrm|5.2.2
mssql|ms-|1.3.1
python|ms-|2018.4.0
csharp|ms-|1.15.2
vetur|oct|0.12.3
csslint|ray|0.0.11
sass-indented|rob|1.4.9
vue-vscode-snippets|sdr|1.3.0
markdown-preview-enhanced|shd|0.3.5
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

</details>

**Comment by cottrell** [comment]
Persistant problem for years. Will try to scale back all extensions but basically this is why I use vim ... IDEs just don't work because people keep adding frills.

**Comment by octref** [comment]
Please open an issue at https://github.com/felixfbecker/vscode-php-debug.
