### ISSUE TITLE
replace all - search

### ISSUE THREAD

**Issue by jcdsr** [Microsoft/vscode#50768]
Issue Type: <b>Bug</b>

seems when I use find and replace all button from the search on the l the left menu tab, the action save all the documents that has been changed. I would like to disable that, this error didn't happen before

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

**Comment by sandy081** [comment]
Auto save feature was newly added as per users request. May be a setting to disable that if not needed?

**Comment by sandy081** [comment]
@jcdsr May I know why would you like to disable saving during replace all action?
