### ISSUE TITLE
Question: Dataflow between Current Document and Webview

### ISSUE THREAD

**Issue by goessner** [Microsoft/vscode#50772]
I'm not able to use current document data inside of an associated webview.

![grafik](https://user-images.githubusercontent.com/4902746/40709875-7d375a7e-63f7-11e8-8aa3-a0a86ce8358c.png)

I even tried to insert the local file via `<script src="./color.js"></script>` with the help of `localResourceRoots` ... but failed.

I wish, the cats example would be working with a cats document.

**Comment by mjbvz** [comment]
Either:

* Inline it

* Use a full path with a `vscode-resource` scheme. See the [docs section on loading local resources](https://code.visualstudio.com/docs/extensions/webview#_loading-local-content). Relative paths will only work if you set the `<base>` in the webview html
