### ISSUE TITLE
The interface overview should show a terminal hint

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#50775]
The interface overview doesn´t show the terminal. I suggest to also show a hint to open the integrated terminal.

![image](https://user-images.githubusercontent.com/172399/40712322-af8207f8-63fd-11e8-94ce-3e222d42844e.png)

// fyi @chrisdias @seanmcbreen

**Comment by Tyriar** [comment]
> A fake terminal, actually opening a terminal might be a bad idea as on Windows a notification will pop up and on some environments the terminal will immediately close (like if a sysadmin sets `$SHELL` to `/bin/false`. There's no way of detecting if it will fail ahead of time.

**Comment by chrmarti** [comment]
Adding a hint (no fake terminal for now).
