### ISSUE TITLE
Connect the sash in the 2x2 grid

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50770]
Testing #50458

- open the 'grid 2x2' layout
- move the horizontal sash: The sash only moves in one side.

It would be great if sash on the other side also moves so that the two sashed stay aligned.

**Comment by bpasero** [comment]
Depends on the grid widget providing a way for me to build a grid layout where views are connected instead of split. I think for the beginning we could do this as a one-off for the "Grid 2x2" layout.

**Comment by joaomoreno** [comment]
Started some work here: https://github.com/Microsoft/vscode/tree/joao/grid2x2

It's, of course, tougher than expected... but I think we can get something nice going.

**Comment by joaomoreno** [comment]
Fixed by f9911c7446a997e9294d1612b02279741e0a9775
