### ISSUE TITLE
Intergrated Terminal

### ISSUE THREAD

**Issue by athulrs** [Microsoft/vscode#50778]
Issue Type: <b>Bug</b>

Keyboard copy ctrl+shift+c is not working in intergrated terminal.
Whereas Paste is perfectly fine

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-38-generic

**Comment by Tyriar** [comment]
Does it happen when you close all windows and run `code --disable-extensions`?
