### ISSUE TITLE
Resolve conflict between (quick) suggestions and snippet placeholders

### ISSUE THREAD

**Issue by vammex** [Microsoft/vscode#50776]
Issue Type: <b>Performance Issue</b>

impossible  ux  has been made for executing automatic "for-loop"
i input "i" as iterator and click tab to move to an array determination, but it automatically replaces "i" with smth like id or any other word starting with i
same if i input "j" - it will be replaced with join
first, it's a crazy discomfort
second even i try to fix it manually i miss all quick way to make for-loop using tabs and so on
please fix it, just to avoid automatic replaces inside automatic processes!

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	 12756	code main
    0	   288	  2804	   window (events.js - test27 - Visual Studio Code)
    0	    69	  3296	     extensionHost
    0	    92	  3972	       electron_node electronForkStart.js tsserver.js 
    0	    34	 10436	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    33	  4424	     searchService
    0	    14	  7428	     watcherService 
    0	     8	  7064	       console-window-host (Windows internal process)
    1	    71	  6328	   shared-process
    0	   125	 13276	   gpu-process
    0	    76	 13584	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (events.js - test27 - Visual Studio Code)
|    Folder (test27): 230 files
|      File types: png(91) js(85) jpg(11) ttf(8) json(7) html(6) otf(5) css(4)
|                  eot(3) svg(3)
|      Conf files:;
```

</details>
Extensions: none

**Comment by jrieken** [comment]
We have reverted the change and restored the old behaviour because of #52999 and #51722

**Comment by vammex** [comment]
after all these reverts which way the topis issue will work? with crazy suggestions or not?

**Comment by jrieken** [comment]
Next try! The following change has been made (for July insiders). When a snippet is active, quick suggestions (suggestions as you type) are disabled. There is a new setting `editor.suggest.snippetsPreventQuickSuggestions` with which the old behaviour get be stored.

**Comment by vammex** [comment]
today a new release has been executed.
where is snippetsPreventQuickSuggestions there?
