### ISSUE TITLE
Deprecate old color ids, don't remove them

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50773]
Testing #50458

- open `abyss-color-theme.json` in an editor
- not that `editorGroup.background` is marked as invalid.

I assume the setting got renamed.

For a better user experience, keep the old setting and provide a deprecation message with `registerColor` that will be shown to the user. To play nice with existing themes, we can let the new color inherit the old color.

**Comment by bpasero** [comment]
@aeschli I am now doing this:

```typescript
registerColor('editorGroup.background', {
	dark: null,
	light: null,
	hc: null
}, nls.localize('editorGroupBackground', "Deprecated background color of an editor group."), false, nls.localize('deprecatedEditorGroupBackground', "Deprecated: Background color of an editor group is no longer being supported with the introduction of the grid editor lyout. You can use editorGroup.emptyBackground to set the background color of empty editor groups."));
```

There is no good direct mapping to any of the new colors imho. I do not want to use this color for empty groups because by default I think empty groups should just share the same background as editors.

**Comment by aeschli** [comment]
verified in Version 1.24.0-insider (1.24.0-insider) 62af395b9974f38fcf15acafc8ac9818b0db7084
