### ISSUE TITLE
[invokeFunction] unkown service 'privateBreakopintWidgetService'

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#50777]
This was raised in #46742 but it's marked as March and I just hit it today (in Stable, v1.23.1):

<img width="503" alt="screen shot 2018-05-30 at 10 42 44 am" src="https://user-images.githubusercontent.com/1078012/40712814-802e95fe-63f6-11e8-9696-4fb3ae6d957f.png">

There are two typos in the message:

- `unkown` -> `unknown`
- `Breakopint` -> `Breakpoint`

I was adding and editing logpoints while debugging my extension (the logpoints where in the TypeScript for the VS Code extension; this is unrelated to the debug adapter within my extension - I'm working on editor stuff).

**Comment by DanTup** [comment]
(cc @isidorn)

**Comment by isidorn** [comment]
I can not hit this issue following the steps in #46742
Can you reproduce in Insiders, if yes what are your steps?
Typos I have just fixed - thanks for pointing out!

**Comment by DanTup** [comment]
Ok, it seems like I can repro reliably in Stable with these steps (I'm not sure if all are required):

1. Run my extension so I'm in a debug session
2. Add a logpoint that prints "test"
3. Hit the logpoint so it gets printed
4. Edit the logpoint
5. Set the type to `Expression`
6. Type something in the expression field and press `<Enter>`

However, I can't repro in Insiders. I don't know if it's because it's fixed, or just because the criteria for it happening are more complicated.

**Comment by isidorn** [comment]
If you can not repro in insiders I will guess it is fixed. This was a 5 week iteration and a bunch of commits went in.
Thus closing. If you see it in insiders let me know and I will reopen
