### ISSUE TITLE
Too many files open in system on OSX

### ISSUE THREAD

**Issue by Allerby** [Microsoft/vscode#50771]
VSCode Version: 1.23.1
MacOS Version: 10.13.4
I have no installed extensions. Brand new laptop, fresh vscode install, never installed any extensions.

Steps to Reproduce:

1. create and open an emberjs project in vscode (preferable one with a few addons)
2. sudo lsof -n | cut -f1 -d' ' | uniq -c | sort | tail
3. Watch your vscode go to 8000+ file descriptors and watch your applications drop like flies.

Does this issue occur when all extensions are disabled?: Yes/No
Yes, fresh install - never installed extensions.

**Comment by shobhitchittora** [comment]
@Allerby Need more info on this. Can't really reproduce this. I'm guessing you might already have many files open by some or the other program.

**Comment by octref** [comment]
@Allerby Can you tell us how you were generating the ember project?

It's probably caused by VS Code's file watcher. If you have other projects like `node_modules`, you need to add their patterns to `files.watcherExclude`:

```json
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true
  }
```

**Comment by Allerby** [comment]
Sorry should have been more specific, by addons I mean Ember addons - not vscode extensions..

Haven't used PHP in over 2 years, as stated in the OP this is happening solely when opening an EmberJS project. 

To confirm what I said earlier and for anyone coming across this thread later, sometimes an ember projects /tmp/ folder can grow unusually large due to unknown [issues](https://github.com/ember-cli/ember-cli/issues/1186) with addons. If you're using ember and see this side effect, try adding the tmp folder to your list of excluded files to watch:

```
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true,
    "**/tmp/**": true
  }
```

Seems to have worked for me.
