### ISSUE TITLE
Setting iconPaths in tree nodes seems to mess up indenting

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#50780]
This one is kinda weird; I'll post an update if I can get an isolate code sample to repro it. I have a tree which looks like this:

![screen shot 2018-05-30 at 11 36 24 am](https://user-images.githubusercontent.com/1078012/40715594-f8e71910-63fd-11e8-8b95-961fe6b45546.png)

All node have `resourceUri` set and only the first two nodes are collapsible. The rendering of the tree is pretty accurate; here's what a text dump looks like:

<img width="749" alt="screen shot 2018-05-30 at 11 36 45 am" src="https://user-images.githubusercontent.com/1078012/40715634-18892ec0-63fe-11e8-9f18-688feab45fa7.png">

However when I add `iconPaths` to root node and the leaf nodes, it becomes this:

![screen shot 2018-05-30 at 11 37 28 am](https://user-images.githubusercontent.com/1078012/40715655-2a363f78-63fe-11e8-9a2d-67322fb8dd6a.png)

For some reason the lowest-level item that was most indented originally (`Test order of oeprations: 12 + 3 * 4 = 24`) is somehow less-indenting than the nodes below it, which makes them look like children, even though they're less-deep.

(cc @sandy081 ... it's possible this is my crazy logic, but the only difference in the screenshots is commenting out `iconPath`... I'll try and simplify a repro).

**Comment by DanTup** [comment]
I was testing ins table, but just checked Insiders and it's the same.

**Comment by DanTup** [comment]
Ugh, even though it makes no sense to me, if I remove my phantom-group-hiding, it stops. So either it's my bug, or it's dependent on the levels (which seems unlikely). Feel free to ignore this for now, I'll post back shortly!

**Comment by DanTup** [comment]
@sandy081 Ok, here's a repro. If you comment out the line that sets the `iconPath` in `TestTreeItem` then it renders correctly, but with the icon in place, the second test gets indented instead of un-indented.

```ts
import * as path from "path";
import * as vs from "vscode";
import { extensionPath } from "../extension";

let suite: SuiteTreeItem;

export class TestResultsProvider implements vs.TreeDataProvider<object> {
	private onDidChangeTreeDataEmitter: vs.EventEmitter<vs.TreeItem | undefined> = new vs.EventEmitter<vs.TreeItem | undefined>();
	public readonly onDidChangeTreeData: vs.Event<vs.TreeItem | undefined> = this.onDidChangeTreeDataEmitter.event;

	constructor() {
		setTimeout(() => this.sendFakeData(), 1000);
	}

	private sendFakeData() {
		suite = new SuiteTreeItem();

		const groupNode = new GroupTreeItem({ id: 1, parentID: null, name: "GROUP 1" });
		groupNode.parent.children.push(groupNode);

		const testNode1 = new TestTreeItem({ id: 2, name: "TEST 1 (INSIDE GROUP 1)" }, groupNode);
		groupNode.children.push(testNode1);

		const testNode2 = new TestTreeItem({ id: 3, name: "TEST 2 (NOT INSIDE GROUP)" }, suite);
		suite.children.push(testNode2);

		this.onDidChangeTreeDataEmitter.fire();
	}

	public getTreeItem(element: vs.TreeItem): vs.TreeItem {
		return element;
	}

	public getChildren(element?: vs.TreeItem): vs.TreeItem[] {
		if (!element) {
			return [suite];
		} else if (element instanceof SuiteTreeItem || element instanceof GroupTreeItem) {
			return element.children;
		}
	}

	public getParent?(element: vs.TreeItem): SuiteTreeItem | GroupTreeItem {
		if (element instanceof TestTreeItem || element instanceof GroupTreeItem)
			return element.parent;
	}
}

export class SuiteTreeItem extends vs.TreeItem {
	public readonly children: Array<GroupTreeItem | TestTreeItem> = [];

	constructor() {
		super("SUITE", vs.TreeItemCollapsibleState.Expanded);
		this.id = "suite";
		this.iconPath = vs.Uri.file(path.join(extensionPath, `media/icons/tests/pass.svg`));
	}
}

class GroupTreeItem extends vs.TreeItem {
	public readonly children: Array<GroupTreeItem | TestTreeItem> = [];

	constructor(public group: Group) {
		super(group.name, vs.TreeItemCollapsibleState.Expanded);
		this.id = `group`;
	}

	get parent(): SuiteTreeItem | GroupTreeItem {
		return suite;
	}
}

class TestTreeItem extends vs.TreeItem {
	private _status: string; // tslint:disable-line:variable-name
	constructor(public test: Test, public parent: SuiteTreeItem | GroupTreeItem) {
		super(test.name, vs.TreeItemCollapsibleState.None);
		this.id = `test_${this.test.id}`;

		// Comment this out to fix it...
		this.iconPath = vs.Uri.file(path.join(extensionPath, `media/icons/tests/pass.svg`));
	}
}

export interface Item {
	id: number;
	name?: string;
}

export interface Test extends Item {
	groupId?: number;
}

export interface Group extends Item {
	parentID?: number;
}
```

With `iconPath` set:

![screen shot 2018-05-30 at 1 04 58 pm](https://user-images.githubusercontent.com/1078012/40719065-1a33f6e0-640a-11e8-9481-d57c3eebde30.png)

Without:

![screen shot 2018-05-30 at 1 04 29 pm](https://user-images.githubusercontent.com/1078012/40719073-26a08402-640a-11e8-8765-c1f1b955bd69.png)

**Comment by sandy081** [comment]
@DanTup This is because you have a mix of parent nodes with and without icons. 

Following are the alignment principles:

- If the parent does not have icon and children have icons, then children icons are aligned with twisty. 
- Siblings alignment: Aligned by icon, if all have icons. Aligned by label if non have icons. In a mix case, labels are aligned with icons. 

No place holder icons or empty spaces will be introduced. It is the tree owner's responsibility to provide icons or not to have proper alignment.

In your example, you are having siblings one with icon and the other without. Hence you are having issue with alignment. I would suggest to have icons for all siblings or not but not mixed. 

This was already discussed in the issue - https://github.com/Microsoft/vscode/issues/28974

**Comment by DanTup** [comment]
Understood, thanks for the info!
