### ISSUE TITLE
Explorer's full path tooltip layout is wrong.

### ISSUE THREAD

**Issue by vincedani** [Microsoft/vscode#50784]
- VSCode Version: 1.21.1
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:
1. Open explorer and unfold a folder.
2. Move cursor from folder's content to the folder name.
3. The tooltip appears but with wrong layout.
![vs_code](https://user-images.githubusercontent.com/16573361/40721277-52e8c484-6419-11e8-8cd4-9f263fb976f5.png)
If I move the cursor to the folder's name again, then OK.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)
