### ISSUE TITLE
Can't use Ibus to input Chinese under Ubuntu

### ISSUE THREAD

**Issue by Ambitie** [Microsoft/vscode#50783]
Can't use Ibus to input Chinese under Ubuntu
- VSCode Version: last
- OS Version:Ubuntu 18.04

**Comment by octref** [comment]
Are you trying to input Chinese in terminal or editor?

**Comment by Ambitie** [comment]
editor-ime : rime for ibus  .

**Comment by Ambitie** [comment]
Any CJK word can't  input
