### ISSUE TITLE
Duplicating files loses track of references or even crashes VS Code

### ISSUE THREAD

**Issue by KokoDoko** [Microsoft/vscode#5079]
- VSCode Version: latest
- OS Version:OS X El Capitan

Steps to Reproduce:

1. create a file "ball.ts" that has a class "Ball"
2. create a new file in the file explorer pane
2. paste the whole code of ball.ts into the new file
3. now type your new class name in the new file, for example "Paddle"

result:

- the file name of your new file in the explorer keeps changing to "ball-1.ts".
- every time you rename that file to "paddle.ts", VS Code creates a new "ball-2.ts" and so forth.
- even if you manage to get rid of all the redundant files and you end up with one paddle.ts that has a "Paddle" class, VS Code still keeps complaining that you have two Ball classes. 
- the only way to fix this is quit VS Code and restart.

**Comment by dbaeumer** [comment]
@KokoDoko for the duplicate warning see https://github.com/Microsoft/TypeScript/issues/7744

@bpasero I move this to you. It looks like the explorer has still focus and does something on paste ? I can't imagine how otherwise the file would become ball-1.ts

**Comment by bpasero** [comment]
@KokoDoko hard to understand what you are doing, mind to attach a video? I am often using liCECap on Mac to produce animated gifs.
