### ISSUE TITLE
[loc][Query] Context for "Plugin -> Extension?"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#50798]
For string below community member is asking if in source "plugin" should not have been "extension" instead? Can you please check? Thanks!

**Original comments**
BG ISSUE
Plugin -> Extension? by lyubomirv, 2 months ago

**Context**
extensions/typescript-language-features/package:English (en):plaintext:typescript.tsserver.pluginPaths

**Resource**
typescript-language-features

**String text**
Additional paths to discover Typescript Language Service plugins. Requires TypeScript >= 2.3.0.

**Comment by mjbvz** [comment]
No, this should be `plugins`. That's the term that typescript uses for them. They are distinct from VS Code's extensions
