### ISSUE TITLE
npm explorer: pre and post task not grey when script is empty

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50790]
Testing #50568

```
  "scripts": {
    "pretask": "",
    "task": "",
    "posttask": ""
  },
```
![image](https://user-images.githubusercontent.com/6461412/40724237-e0e4f1b6-6420-11e8-9ba6-482d2415910b.png)

**Comment by sandy081** [comment]
I still see pre and post tasks not greyed out when empty

![image](https://user-images.githubusercontent.com/10746682/40776647-a50d52f4-64cb-11e8-990c-547dd5974550.png)
