### ISSUE TITLE
`npm.exclude` doesn't seem to work

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50792]
Testing #50568

- in your root folder create a subfolder 'fooo'
- inside create a package.json with
```
{
  "name": "fooo",
  "scripts": {
    "pretask": "",
    "task": "",
    "posttask": ""
  }
}
```
- try to exclude that folder from the npm explorer
```
    "npm.exclude": [
        "**/fooo", "fooo", "/fooo", "**/fo0o**"
    ]
```

- npm explorer still shows

![image](https://user-images.githubusercontent.com/6461412/40724237-e0e4f1b6-6420-11e8-9ba6-482d2415910b.png)

**Comment by egamma** [comment]
`**/foo/**` works, but this is bogus. Changed to match the folder name and not the path of the package.json.
