### ISSUE TITLE
Update Imports On File Move: description should better explain the TS requirement for a JS setting

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#50806]
Issue Type: <b>Bug</b>

Testing #50488

![image](https://user-images.githubusercontent.com/35271042/40730851-81bf0ee2-63e4-11e8-9126-95d1c9913ace.png)

This might be my own lack of understanding, but when I was first configuring this setting and read the "Requires TypeScript >= 2.9", I was confused as why I needed TS if my project wasn't using it. It was very frustrating trying to get this setting to work. It wasn't until someone assisted me in learning that this javascript setting **relies** on the TS _engine_, regardless if my project uses TS or not. 

The description should better read something like: "This setting uses the TypeScript _engine_ and requires TypeScript >= 2.9".

_Note: Engine might not be the best word_

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T06:13:09.810Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_5203190|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by EthanJStark** [comment]
Agreed, neither the comment nor the feature description specify how to get this feature working. After `npm install -g typescript` and restarting VS Code, I'm still unable to get it working.

**Comment by mjbvz** [comment]
This basically should always work except if you have configured a workspace version of typescript. That's an advanced use case that only effects people who have explicitly configured their workspace's typescript version. If you are seeing issues with this feature in VS Code insiders, please open a new issue

I've add a bit more context to the setting descriptions. Not a lot of space here so let me know if you have a better suggestion for the wording

**Comment by roblourens** [comment]
I think the new wording for JS settings "Requires using Typescript xyz in the workspace" would still be confusing, since I might not feel like I'm using TS. Maybe "Requires having Typescript xyz installed in the workspace"?
