### ISSUE TITLE
add please Visual Studio Code to clipboard by clicking help>info>ctrl+c

### ISSUE THREAD

**Issue by sl5net** [Microsoft/vscode#50802]
i got:

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Datum 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

i want:

Visual Studio Code
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Datum 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

**Comment by fab1o** [comment]
And the [Copy] button gives me this:

```
Version 1.24.0-insider
Commit 43d168182c8df35a99c7f5ee0ef227de34f75fbd
Date 2018-05-30T05:16:49.918Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

I guess this could also have the [Window Title]

**Comment by bpasero** [comment]
Yeah, we have a copy button for that purpose.

**Comment by sl5net** [comment]
No. This Button Not offener.  Visual Studio Code.
Please See my Frist message
