### ISSUE TITLE
Update Imports On File Move: does not persist file extension

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#50804]
Issue Type: <b>Bug</b>

Testing #50488

**Example**
![ezgif com-gif-maker 9](https://user-images.githubusercontent.com/35271042/40729782-0cbf686e-63e2-11e8-9211-f5632c97e3ef.gif)

**Resulting error**
![image](https://user-images.githubusercontent.com/35271042/40729816-1bff9a7e-63e2-11e8-805d-bc384369b92e.png)

When moving a js file while using the "Update Imports On File Move" setting and the import has the file extension explicitly set, the auto update will strip out the ".js" extension. This causes issues with the js file referencing it as it needs the extension name.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T06:13:09.810Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|16.00GB (0.78GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_5203190|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24493
