### ISSUE TITLE
[scss] different icons for keywords used

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50803]
Verifying #41929

![image](https://user-images.githubusercontent.com/6461412/40729241-40d795f0-642c-11e8-9fd2-dea2d96ce8ee.png)

We should use the same icon for all keyword proposals. Ok for me to use the same one as for `@each`

**Comment by sandy081** [comment]
@octref @aeschli I still see same icons as before in insiders and dev

![image](https://user-images.githubusercontent.com/10746682/40773561-8ef7b692-64c3-11e8-9c7f-b60bc3e2b3c7.png)

**Comment by aeschli** [comment]
we have to publish a new version of vscode-css-languageservice first. I'll do that ASAP
