### ISSUE TITLE
Preserve undo stack when saving file with a different name

### ISSUE THREAD

**Issue by gaearon** [Microsoft/vscode#50801]
Issue Type: <b>Bug</b>

I'm often working on reducing very large issues to small test cases. This means having a working undo/redo stack is essential to my work. Unfortunately Code just lost an hour's worth of undo/redo history.

1. Work on a file.
2. Press Cmd+Shift+S to "save as" another file (because I want to keep a current snapshot)
3. Bam. You get teleported into a file with new filename and no undo history.

Expected: the file under the old name should still be open in another tab and have its undo/redo stack preserved and in the same exact spot. The action of saving a file under a different name should not destroy its undo/redo stack.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.38GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.3.1
sublime-babel-vscode|jos|0.2.10
subtle-brackets|raf|2.1.1

(1 theme extensions excluded)

</details>

**Comment by gaearon** [comment]
Nope, it's not related.

**Comment by octref** [comment]
You can subscribe to #7169 and #7536 for updates.

**Comment by gaearon** [comment]
I think these count as the same issue if we consider “save as” to:

1. Close existing file
2. Represent a different file

That’s different from my mental model.

Since “save as” replaces the current file I’m working on right as I edit it (my cursor stayed at the same place) I would expect it to keep undo stack too.

In other words, **I’m not asking to preserve undo stack between closing and opening a file**. I think what I’m asking is more like **not treating Save As as closing a file and opening a different one**.

**Comment by octref** [comment]
That's a fair point. I also find it a bit confusing since most apps I use doesn't close the existing doc for "Save As". I've edited the title, as undo stack is tracked in other issues.

Meanwhile, you can try selecting a file in file explorer, Cmd+C, Cmd+V to replicate it.

**Comment by alexandrudima** [comment]
Let's track in #17977
