### ISSUE TITLE
Update Imports On File Move: alert the user when they're not using the correct TS version

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#50808]
Issue Type: <b>Bug</b>

Testing #50488

If the user has the "javascript.updateImportsOnFileMove" setting enabled but hasn't set the correct version of TypeScript, we should alert the user that they need to select the correct version. It would be even better if it asked if they want to let VS Code do it for them.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T06:13:09.810Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_5203190|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by mjbvz** [comment]
Good suggestion but I don't think it is worth the effort and maintenance cost. The vast majority of our uses are using the workspace version of typescript which does support this feature. Users will only not see this feature if they have specifically opted to use an older workspace version of TypeScript (in which case, they likely do not want to change their version)
