### ISSUE TITLE
Uri#toJSON/toString performance

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#50800]
We have talked about improving performance of `toString` and `toJSON`, e.g. the latter shouldn't call `toString` but rely on an eventually cached value. Also, for `toString` things can be optimised, e.g use string concatenation and maybe a custom variant of encodeUriComponent. 

/cc @octref @roblourens

**Comment by jrieken** [comment]
@rebornix Measuring the performance of `toString` and recalling you mentioned the array and join usage: For me, the biggest part here is encoding uri components. How did you profile this? In chrome, nodejs, or electron? (I used the latter)

<img width="617" alt="screen shot 2018-05-31 at 15 44 03" src="https://user-images.githubusercontent.com/1794099/40785772-b1c42982-64e9-11e8-9fda-5617abfaf22c.png">

![image](https://user-images.githubusercontent.com/1794099/40785787-be430a34-64e9-11e8-9e81-2cceb1283245.png)

**Comment by rebornix** [comment]
@jrieken I ran all benchmarks in nodejs 8.10

The benchmark above was tested against `10,000` urls like `https://code.visualstudio.com?query={number}`, it's pretty simple and that's probably why the `join` accounts for such a large portion of time. I did another round of testing against all files in vscode repo, the results are like below

![image](https://user-images.githubusercontent.com/876920/40812943-55dcb9e6-64ed-11e8-8d28-7fe6f12d984b.png)

This is more realistic and `join` accounts for `14%`. String concat on a Rope implementation might take less time. But you are right, most time is spent in encoding and we need to optimize that.

**Comment by jrieken** [comment]
Started to work on this in #50940. Using string concatenation vs array didn't show much of a difference. I have added a custom version of `encodeUriComponents` and that helps a lot, esp since most uris/paths we use don't need encoding. You can run `./scripts/test.sh --runGlob **/uri.test.perf.js --debug` which creates URIs for all files in the `src/` folder. It measures how `toString` and `toJSON` perform and with the current work it takes ~7ms to call `toString` for all those ~3500 URIs (down from ~60ms)

**Comment by rebornix** [comment]
@jrieken checking char code is fast 👍

**Comment by octref** [comment]
@jrieken Can you make a new release for vscode-uri? Would want the updates.

**Comment by jrieken** [comment]
yeah, will do. slightly more tricky because I have now more dependencies but I'll see what I can do
