### ISSUE TITLE
Feature Request: Angular HTML Code Completion

### ISSUE THREAD

**Issue by jesusvalenzuelar** [Microsoft/vscode#50815]
As a Angular developer, I'd love to have the posibility to have intellisense or code completion in our html templates.

How can it works?

- Usually we define a component, based on naming convention, like app.component.ts, well and we define a inline template or templateUrl for our angular component.
- In HTML we can define one or more models, like razor syntax at the top of the file
- In any part of our html display auto-completion based on the models
- It can help use to avoid writing problems of properties and methods

As extra functionality we can add:
* Event binding completion based on the component methods
* Class binding
* Directive bingind like ngFor, ngIf, etc.

Attached is an image to preview how it could works!!!

![vscode-angular-new-feature-request](https://user-images.githubusercontent.com/16480127/40734503-7c3936a6-63ed-11e8-8aaf-d6cec0e5d537.png)

**Comment by mjbvz** [comment]
Please file this request against the angular extension: https://github.com/angular/vscode-ng-language-service

**Comment by jesusvalenzuelar** [comment]
Awesome, thanks.
