### ISSUE TITLE
Windows 7: tasks.json changes not detected until VS Code restarted

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#5081]
- VSCode Version:0.10.11 stable, 0.10.14-insiders
- OS Version:Windows 7

Steps to Reproduce:

1. Follow the CSS transpiling section and create a tasks.json with 'node-sass' as the command.
2. Save tasks.json
3. Ctrl+Shift+B to Run Build Task

"No task runner configured." error displayed.

4. Restart VS Code in the same folder.

'node-sass' now runs correctly

**Comment by gregvanl** [comment]
Also repros on 0.10.14-insiders

**Comment by gregvanl** [comment]
Doesn't repro on Windows 8.1 and 10

**Comment by gregvanl** [comment]
Closing and opening the folder, refreshes the tasks.json configuration.
I've reproduced this on two Windows 7 VMS and can grant access to anyone who'd like to take a look.

**Comment by gregvanl** [comment]
I'm using http://xlab DevDiv Private Cloud VMs for my testing.  It's very easy to create Windows 7 machines for testing. I assume the Zurich team has access to this service.

**Comment by alexandrudima** [comment]
@dbaeumer Might be related to #5083

**Comment by gregvanl** [comment]
Duplicate of #5083. The issue goes away when .NET 4.5 is installed and the File Watcher is working again.

**Comment by LegoChicken** [comment]
I'm still seeing this problem in Windows 7 Professional Service Pack 1 with .Net 4, 4.5, 4.5.1 and 4.6.1 installed. It is most annoying that I can edit the tasks.json to change my build and then not get that task until I restart VS Code. Using 1.12.1.

**Comment by BillDenton** [comment]
I'm still seeing this problem in Windows 7 Professional Service Pack 1 with .Net 4, 4.5, 4.5.1 and 4.6.1 installed. It is most annoying that I can edit the tasks.json to change my build and then not get that task until I restart VS Code. Using 1.12.1.

**Comment by LegoChicken** [comment]
Can this issue be reopened? Or shall I open a new one?

**Comment by dbaeumer** [comment]
@BillDenton if you create a new file using the Windows file explorer directly in a folder that is open in VS Code does the file show up in VS Code's explorer pane?

**Comment by BillDenton** [comment]
Yes, it does appear. I opened the VS Code explorer pane, right clicked on a file, selected Reveal in explorer, copied the file in Window explorer. Immediately the file appeared in VS Code explorer.

**Comment by BillDenton** [comment]
I have multiple folders (for different branches off the same project). I switch between them using File, Open Folder. However, so I can use the same configuration for all folders, I have created a .vscode directory in each root folder. In there the tasks.json, c_cpp_properties.json, launch.json and settings.json are symbolic links back to a common configuration stored elsewhere. Could this be messing up the change detection?

**Comment by dbaeumer** [comment]
@BillDenton yes, this is the problem. Under Windows the file change event is triggerd on the traget and therefore VS Code doesn't know about it. See https://github.com/Microsoft/vscode/issues/25547

**Comment by BillDenton** [comment]
I also tried a creating a symbolic link to the common folder, rather than each file individually. I could avoid this problem by have common tasks.json, launch.json and c_cpp_properties.json that can overridden  a folder basis.

**Comment by BillDenton** [comment]
I think I solved this by using hard links. By using http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html with "Hardlink Clone".
