### ISSUE TITLE
Support overriding SHELL args when configuring a task

### ISSUE THREAD

**Issue by ivankravets** [Microsoft/vscode#50819]
See example https://github.com/platformio/platformio-vscode-ide/issues/89#issuecomment-393165896

**Comment by ivankravets** [comment]
Wow! 😊 

How will it work? 

P.S: I thought about you yesterday :)

**Comment by dbaeumer** [comment]
As with a shell executable. Something like
```
"options: {
    "shell": {
        "args": ["...."]
    }
}
```
As long as no executable is specified I still add `-c` or `-Command` depending on the used shell.

**Comment by ivankravets** [comment]
Thank you so much that implemented this so quickly! I've just tested it and have some issues. Please reopen this issue:

1) How is difficult to allow this configuration even for `vscode.ProcessExecution`? We, really, don't need `vscode.ShellExecution` for `platformio` binary.
2) Which consequences will we have switching our Tasks from `vscode.ProcessExecution` to `vscode.ShellExecution`?
3) I really don't know how internally works this runner. Nevertheless, from a top point of view, I have some tasks which PlaformIO's extension provides me. I click ⚙️ near this task and VSCode propose me to override/extend existing configuration for this task:
    - Do you see this task as extension did configure it for you?
    - If yes, why should I again configure "executable" if extension already did it for me? I agree, with a new task I should do that, you don't know which executable to use for overriden arguments. In PIO case it is equal to `new vscode.ShellExecution(IS_WINDOWS ? 'platformio.exe' : 'platformio', this._args, { env: process.env })`. 
4) Extra configuration of existing task does not work properly. Instead of overriding existing arguments, it does something strange. It seems that it overrides, but finally adds ALL arguments from original command as single argument... I created for you a simple dump which should help you to reproduce this issue:

**tasks.json**
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "PlatformIO",
            "task": "Build",
            "problemMatcher": [
                "$platformio"
            ],
            "options": {
                "shell": {
                    "executable": "platformio",
                    "args": [
                        "-e", "invalid_arg"
                    ]
                }
            }
        }
    ]
}
```

**Result**
```
> Executing task: platformio run <

VSCode args = ['platformio', '-e', 'invalid_arg', 'platformio run']
Error: no such option: -e
The terminal process terminated with exit code: 2
```

P.S: I really like this way with customazing existing tasks. I think it could be intrested not only for PlatformIO users.

**Comment by dbaeumer** [comment]
@ivankravets I see your use case but you are asking for something different then tweak the shell args. So I would like to ask you to open a new issue where we can discuss the feature. You are basically asking for allowing to configure an existing task based on some other user configuration. I think this is more like https://github.com/Microsoft/vscode/issues/43782. So may be your wish is simply a dup of https://github.com/Microsoft/vscode/issues/43782

**Comment by ivankravets** [comment]
I understand what do you mean under "shell args". Nevertheless, from dev/point of view, we have `new vscode.ShellExecution('platformio', this._args, { env: process.env })`.  How to configure it from `tasks.json`? #43782 is slightly different.

Maybe, we should generate task based on `"type": "shell"` instead of own task type? Is it possible?

**Comment by dbaeumer** [comment]
I am not sure if this is a good idea since it forces to make the task complete in the tasks.json file. The shell args are the arguments that are passed to the shell interpreter (e.g. to bash or PowerShell like for example `-NoProfile`) and the `platformio` command will not see them. 

Is `platformio` a script or an executable. If it is an executable why don't you make it a ProcessExecution. Does it need to run in a shell for environment reasons?

**Comment by ivankravets** [comment]
> If it is an executable why don't you make it a ProcessExecution. 

We use `vscode.ProcessExecution()` , see https://github.com/platformio/platformio-vscode-ide/blob/develop/src/tasks.js#L238

I switched to `ShellExecution` just for testing.

Ok, could you explain to me what does mean "Configure" option near each PlatformIO task? When you click on it, you will see `tasks.json` with prefilled data. What is the aim of this cloned item in `tasks.json`?

**Comment by ivankravets** [comment]
Thanks! I got it. I will update our docs with "shell" task examples.

**Comment by dbaeumer** [comment]
To verify under Linux/Mac:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "options": {
        "shell": {
            "args": [
                "--version"
            ]
        }
    },
    "tasks": [
        {
            "type": "shell",
            "label": "echo",
            "command": "echo Hello"
        }
    ]
}
```

This should print the version instead of eching Hello

**Comment by ivankravets** [comment]
We updated our docs and provided examples for "shell", see http://docs.platformio.org/en/latest/ide/vscode.html#custom-tasks
