### ISSUE TITLE
Can't use ansible snippets in vscode

### ISSUE THREAD

**Issue by Yannick91** [Microsoft/vscode#50810]
Hi,

I am experiencing a weird issue concerning the snippet function of the VScode extension for Ansible.
Normally, when you install the extension and create a new file (yaml) you start typing the beginning of a method it shows you a menu where you can choose to see 'snippets'. However, in my case this is never shown. 

![2018-05-30 17_53_41- main yml - iiams_ansible - visual studio code](https://user-images.githubusercontent.com/39049887/40731925-abf517aa-6421-11e8-9d71-5f865c0cee53.png)

I have reproduced this on another PC, and it works without any other additional configuration. 

----
- VSCode Version: Code 1.18.1 
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 
vscode-ansible|vsc|0.2.6
---

I hope you can take a look at this?

Thanks a lot!

Kind regards,

Yannick

**Comment by jrieken** [comment]
can you attach your settings files please?

**Comment by jrieken** [comment]
This issue was moved to VSChina/vscode-ansible#121
