### ISSUE TITLE
goto previous breakpoint goes to first breakpoint

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50812]
Verifying #31806

- In a typescript file, create 3 breakpoints
- Use 'Goto next breakpoint' three times to navigate to the last breakpoint
- Use 'Goto previous breakpoint': It brings you back to the first.
I'd expected it would just go one back.
![prev-breakpoint](https://user-images.githubusercontent.com/6461412/40733023-047446c2-6435-11e8-9c26-8d8610692f86.gif)

**Comment by isidorn** [comment]
@aeschli good catch
