### ISSUE TITLE
Workspace setting default value in new Setting Editor is ambiguous

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#50827]
- VSCode Version: Insider
- OS Version: macOS

Steps to Reproduce:

1. Working on a multi root workspace
2. Have `files.autoSave` set to `afterDelay` in User Setting
3. Open workspace setting
4. Search for `autoSave`.

![image](https://user-images.githubusercontent.com/876920/40741283-07ff86ce-6400-11e8-8714-358c92cebb55.png)

When I looked at this setting, I thought auto save is turned off but since the auto saving still happened on my machine, I was confused what's going on there. Later on I realized that even though it's say `off` in above image, it's not actually effective.

With the json editor, I don't have such confusion as if nothing exists in the workspace settings file, I know for sure nothing is overriding my User Setting. Here in this case with the new Setting Editor, I don't know if it's the default value or an explicit setting.

**Comment by roblourens** [comment]
At one point I considered graying out unmodified values. What do you think about that?

**Comment by rebornix** [comment]
I'm not sure about if grayed out value would lead to unexpected meaning (disabled). 

For User Setting there is a default value, while for Workspace Setting there is no such *default* value concept. Probably something indicating that the value is not set?

**Comment by geekley** [comment]
May be related to #58901 .

I would suggest changing "(Modified in: User)" above to "(Overriden in: User)" below the value, followed by the actual value the setting will have (read-only).  
I would also expect that clicking the "(Overriden in: User)" link would navigate to the corresponding setting in User Settings tab.

**Comment by roblourens** [comment]
"Overridden in User" sounds like "this scope is overridden in User" which is not true. Going the other direction it might be true ("Overridden in Workspace" seen from the User scope, it may be true that the User value is overridden by the Workspace).

Also there is no one "actual value" since you can have a setting configured in multiple folders in a workspace. Basically I want to give the user a gentle hint that the setting is configured other places, and leave it up to them to figure out what the effective value will be in what situation, because it's too hard to explain all of this in a simple UI.

**Comment by geekley** [comment]
Maybe it would be less confusing if each workspace setting had an "Override in this workspace" checkbox before the setting. The override option would never be faded out, and the setting would be faded out (half opacity) only if the override option is not set. This avoids the confusion with disabled, and makes the action of overriding more explicit.

**Comment by andrecasal** [comment]
From a user's point of view, there is no difference between default settings and user settings that are the same. I suggest to always show the default settings as if they where applied. Having a "override" or an "applied" definition is not useful.

Personally, I keep an updated copy of all default settings in my user settings.json file and only change the ones I want, precisely to avoid this ambiguity.

**Comment by rzhao271** [comment]
Merging into https://github.com/microsoft/vscode/issues/58038
