### ISSUE TITLE
Keep current line stable at top of editor viewport when editor resizes

### ISSUE THREAD

**Issue by vanceism7** [microsoft/vscode#50826]
Issue Type: <b>Bug</b>

This is a bug effecting the scroll beyond functionality. When you scroll beyond the last line of your file, positioning the last line of the editor close to the top border of the editor window, opening and closing the bottom bar (the terminal, problems tab, etc) will cause the editor to jump upward about 10-15 lines or so

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A12-9800 RADEON R7, 12 COMPUTE CORES 4C+8G  (4 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (10.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.3
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|3.21.0
Ionide-Paket|Ion|1.11.1
hoogle-vscode|jca|0.0.4
language-haskell|jus|2.5.0
python|ms-|2018.4.0
csharp|ms-|1.15.2
rust|rus|0.4.4
haskero|Van|1.3.1
vscode-vtools|ven|1.0.4
vim|vsc|0.12.0

</details>

**Comment by alexandrudima** [comment]
The same can be simulated by resizing the window:

![kapture 2018-07-27 at 10 44 30](https://user-images.githubusercontent.com/5047891/43311220-13e10f3c-918a-11e8-8fb8-cb92382c7fe6.gif)

**Comment by alexandrudima** [comment]
Let's track in #46875
