### ISSUE TITLE
Top-level imports should be de-emphasised in outline view

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50829]
#5605

When sorting by position or name in large files, the outline view is filled with imports. Here's an example of the outline using the quite large [Terminal.ts](https://github.com/xtermjs/xterm.js/blob/master/src/Terminal.ts) in xterm.js:

![image](https://user-images.githubusercontent.com/2193314/40741694-fb5a6f32-6400-11e8-8630-f34c8761ba86.png)

Personally I don't find these imports useful at all and would prefer if they were removed all together, capturing them in an "Imports" node would be fine too though.

**Comment by jrieken** [comment]
This is a problem with the TypeScript outline with is very verbose. We should revisit and make sure we don't show everything here...

**Comment by mjbvz** [comment]
Yeah no one has ever complained about us including imports  in the normal symbol search but it's probably not very useful either. Will see if we can filter them out

**Comment by Tyriar** [comment]
Woo! :tada:
