### ISSUE TITLE
Hang when copy/pasting file with large number

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50822]
- Have file named `file-9007199254740992.txt` in explorer
- Copy/paste it
- Window hangs

This is from https://github.com/Microsoft/vscode/pull/50003. We shouldn't attempt this when the number is >= Number.MAX_SAFE_INTEGER.

It loops forever here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L1049

This bug will happen whenever incrementFileName fails to modify the file name.

**Comment by Krzysztof-Cieslak** [comment]
@isidorn, I guess only interesting thing about this what we should do in this case as we need to create some new file name?  Add `.1` without changing the original number?

**Comment by isidorn** [comment]
@Krzysztof-Cieslak that sounds reasonable
