### ISSUE TITLE
Find in selection toggle is different to use regex toggle

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50825]
Dark+:

![image](https://user-images.githubusercontent.com/2193314/40740701-5c37b8b2-63fe-11e8-9fab-c90d6534a5e3.png)

**Comment by rebornix** [comment]
We align the find in selection hover/visited color with arrows and close button. Would love to hear @misolori 's idea on this.

**Comment by misolori** [comment]
We should use the same treatment as our other toggles:
![image](https://user-images.githubusercontent.com/35271042/45514925-a3094200-b75b-11e8-88a2-cc203adb9a5d.png) ![image](https://user-images.githubusercontent.com/35271042/45515054-f3809f80-b75b-11e8-97eb-b7c9cfbcc860.png)


So this would be:
![image](https://user-images.githubusercontent.com/35271042/45515021-dd72df00-b75b-11e8-8a18-6c94e2a4d8d3.png)

The only thing that is different is that all of our toggles are within an input field and this one is not.

**Comment by Tyriar** [comment]
It's still a little different how the button shifts down, I guess that can be deferred to https://github.com/Microsoft/vscode/issues/8017 as the main problem is fixed.
