### ISSUE TITLE
Titlebar spawns underneath Windows taskbar at top of screen

### ISSUE THREAD

**Issue by jechasteen** [microsoft/vscode#50830]
A fresh install of Code - stable, insiders and code-oss - will spawn a floating window relative to the top of the screen, not to the work area. Code stores the window position, so moving the window makes it spawn in the new location next time.

![screenshot 1](https://user-images.githubusercontent.com/13788397/40691106-5e04607c-6378-11e8-9336-9d2155f1aac9.png)

Issue Type: <b>Bug</b>

Steps to reproduce:

- Taskbar at top of screen
- Display resolution: 1366x768
- Install fresh copy of Code.
- Run Code (with or without extensions disabled)

VS Code version: Code 1.23.1+
OS version: Windows_NT x64 10.0.16299

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/73681
