### ISSUE TITLE
Outline view sort by types should sort inside the type

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50834]
I would have expected the items within a specific type to have secondary sorting of either name or position. Right now is appears to be random. Here's the outline for my settings file:

![image](https://user-images.githubusercontent.com/2193314/40743046-49897190-6405-11e8-9cf4-6a25ba3e63db.png)

**Comment by jrieken** [comment]
Yeah, the tree doesn't use a stable sort algorithmn. @joaomoreno there is arrays#mergeSort for that purpose.

**Comment by joaomoreno** [comment]
@jrieken Do we always need stable sorting in the tree, since it seems to be slower than `Array.sort`? Would an option make sense?

**Comment by jrieken** [comment]
I think stable sorting is desirable but an option would also do it.

**Comment by Tyriar** [comment]
Outlines are typically pretty small, even for large files. I wouldn't expect stable vs unstable to make much difference here.

**Comment by jrieken** [comment]
v8 Array#sort used quick sort for arrays larger then 10 elements I believe - that causes this randomness.

**Comment by str** [comment]
Just for everyone else that was trying to find the open ticket about "sort by type **then** by name", this is it. Please help by upvote the issue.

**Comment by ansiblejunky** [comment]
Can we get this fixed? Outline for my markdown files is simply incorrect, as I described in the linked issue I [created](https://github.com/Microsoft/vscode/issues/63040).  This is definitely a bug. If you have the outline for markdown files, it should be listing the headings in the correct order as they are in the actual markdown file.

**Comment by jrieken** [comment]
this is fixed in latest insider.

**Comment by ansiblejunky** [comment]
@jrieken Thanks!

**Comment by drew-512** [comment]
Thanks to ppl working this issue!  Indeed, the Outline view showing random order slows productivity.  

As a former Apple developer for 18 years, I'm proud to love on VS Code for all needs.  Thanks VSC team for all your hard work, making rock-solid IDE, and showing Apple what proper FOSS, next-gen tools look like!!
