### ISSUE TITLE
Markdown preview language colors don't match theme

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50832]
It looks like we're using some fixed color set which really doesn't seem to fit with many themes. Is there a plan to support inheriting these from the theme?

![image](https://user-images.githubusercontent.com/2193314/40742247-c0a16664-6402-11e8-94b0-a6d8346c9b48.png)

**Comment by mjbvz** [comment]
There is no api to extract the editor colors and I don't think there are plans to add one :( We just use highlight js since it is fairly small and is used on a number of websites

**Comment by Tyriar** [comment]
Can we change the default colors to approximately match Dark+/Light+ then?

![image](https://user-images.githubusercontent.com/2193314/40744315-00f36482-6409-11e8-9333-3f9bfc028333.png)

**Comment by mjbvz** [comment]
Done with 608bbb7c0162ed445377da5456dc37810031ead8

Updated issue title to reflect this

**Comment by aeschli** [comment]
Just as an idea, the IColorTheme gives you access to the token colors. You could look for some common scopes, like `comment`. 

Alternativly we cann add more colors here: https://code.visualstudio.com/docs/getstarted/theme-color-reference#_text-colors
