### ISSUE TITLE
Azure Web App service cannot log in

### ISSUE THREAD

**Issue by latitudehopper** [Microsoft/vscode#50833]
- VSCode Version: 1.23.1
- OS Version: Kubuntu 18.04

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Install Azure Web App
2. Log in using link and code.
3. Return to VS Code only to have nothing logged in.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by octref** [comment]
Please open issue at https://github.com/Microsoft/vscode-azureappservice.
