### ISSUE TITLE
Problems should be sorted by line

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50835]
The file below produces the following problems:

![image](https://user-images.githubusercontent.com/2193314/40743193-b609e296-6405-11e8-8409-e72d3baa9a7b.png)

Notice how the problems appear to be grouped by the provider of the problems, rather than by line. Because of this using F8/shift+F8 to navigate problems jumps all over the file, my expectation is that it goes in order like F3/shift+F3, F4/shift+F4, alt+f3/alt+shift+f3, etc.

Test file:

```ts
/**
 * Copyright (c) 2016 The xterm.js authors. All rights reserved.
 * @license MIT
 */

/*
 * A simple utility for cloning values
 */
export const clone = <T>(val: T, depth: number = 5): T => {
  const a = '';

  
  if (typeof val !== 'object') {
    return val;
  }

  // cloning null always returns null
  if (val === null) {
    return null;
  }

  // If we're cloning an array, use an array as the base, otherwise use an object
  const clonedObject: any = Array.isArray(val) ? [] : {};

  for (const key in val) {
    // Recursively clone eack item unless we're at the maximum depth
    clonedObject[key] = depth <= 1 ? val[key] : clone(val[key], depth - 1);
  }

  return clonedObject as T;
};
(function() {
  function foo() {}
  })();
```

**Comment by jrieken** [comment]
Yeah, we sort by severity and then by location

**Comment by Tyriar** [comment]
> Yeah, we sort by severity and then by location

That's not true either though, otherwise the trailing whitespace problem would be first. So when I was using F8 to go through the file it was going down, up, up, down, was quite disorienting.

> it is primarily sorted by severity and then by line which IMO makes sense.

If that's by design so be it, not ideal for me but it's probably not worth a setting. I think the secondary sorting should be fixed as part of this though.

**Comment by sandy081** [comment]
After investigating, I figured out that it was broken in last milestone. Fixed it.

**Comment by aeschli** [comment]
Verified
![image](https://user-images.githubusercontent.com/6461412/40845313-9e2a8bbe-65b6-11e8-8d8d-6b5a42aca8a6.png)
