### ISSUE TITLE
`enableProposedApi` but not seeing the proposed typings in VS Code

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#50839]
I am trying to use the [`FoldingRangeProvider`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#FoldingRangeProvider) in my extension, but that symbol is not getting recognized by TypeScript.

I know it has only been [released in 1.23](https://code.visualstudio.com/updates/v1_23#_folding-provider-api), but by default Yeoman puts `1.22` in `engines` in `package.json`. I changed it to `1.23` and I also added `"enableProposedApi": true` to `package.json` but I suspect I need to do more than this?

VS Code still underlines the symbol with an error, it doesn't seem to have picked up the proposed API typings.
I did reinstall everything by using `npm install` after changing over to `1.23` and `enableProposedApi`.
I also reloaded the VS Code window to completely restart the TypeScript language server.

**Comment by jrieken** [comment]
> I changed it to 1.23 and I also added "enableProposedApi": true to package.json but I suspect I need to do more than this?

You don't need proposed api for this, just the a more recent version of `vscode.d.ts`. It should work with setting the engine version and running npm install - there is a post install task that takes care of this. Can you attach the output of npm install?

**Comment by TomasHubelbauer** [comment]
Sorry, I has the `import` declaration with 1.22 but lost it somehow before the `npm install` to 1.23 and I never noticed the squiggly lines turned from the "symbol not found" error to "you're not actually importing this" error.  Mea culpa.
