### ISSUE TITLE
HoverProvider text using Markdown, URL to file + Line number?

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#5084]
I've been using HoverProvider to quickly display the origin file of a user function in Lua.
I'm using the Markdown syntax for creating a clickable link, which opens the file in the editor:

`[c:\temp\file.lua](file:c:\temp\file.lua)` -> [c:\temp\file.lua](#here)

I'm wondering if this link syntax also supports line number, and if it does, what is the syntax of it?

I believe this question is also generally related to all places where an extension can display text formatted with Markdown.

**Comment by jrieken** [comment]
It's currently not possible, tho I like the idea.

**Comment by jrieken** [comment]
I will handle this as a duplicate of #3676

**Comment by jrieken** [comment]
@Janne252 You Ok with the github style links? Like `file:///my/files/test.txtL42`?

**Comment by Janne252** [comment]
@jrieken Absolutely, that's short and simple.

**Comment by jrieken** [comment]
deal
