### ISSUE TITLE
Small shift of characters when typing before tab

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50849]
Issue Type: <b>Bug</b>

Testing #45457

1. For a markdown file

    ```md
    a	b
    ```

1. Make sure you are using tab indentation and the tab size is 4.
1. Type a few characters directly after the `a`

**Bug**
Notice a small shift of the `b` while typing:

![may-30-2018 17-04-58](https://user-images.githubusercontent.com/12821956/40753992-a2cc263c-642b-11e8-86b6-d868470d4861.gif)

VS Code version: Code - Insiders 1.24.0-insider (43d168182c8df35a99c7f5ee0ef227de34f75fbd, 2018-05-30T07:06:30.237Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kentquirk** [comment]
Possibly relevant screenshot, showing misalignment of the semicolons:

![image](https://user-images.githubusercontent.com/755528/41291284-4cf397b2-6e1d-11e8-86cc-edb0107bf302.png)

**Comment by alexandrudima** [comment]
Fixed by the fix for #54146
