### ISSUE TITLE
jsconfig doesn't apply to *.es, *.mjs, etc.?

### ISSUE THREAD

**Issue by gakada** [Microsoft/vscode#50842]
Version: 1.23.1.

I have the following `jsconfig.json`

```json
{
  "compilerOptions": {
    "experimentalDecorators": true
  }
}
```

however, it only affects `*.js` files, I still see the error in `*.es` files when decorators are used.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24545
