### ISSUE TITLE
In certain contexts identifiers that end with "_t" are highlighted as class/struct/namespace name in C++

### ISSUE THREAD

**Issue by esmirnov** [Microsoft/vscode#50841]
Hello!
I notice that identifiers with "_t" at end are highlighted as a type name. Is it a bug or feature?

![image](https://user-images.githubusercontent.com/576417/40746509-486d17fe-6463-11e8-847c-afb3ea3aaf28.png)

See here https://github.com/Microsoft/vscode-cpptools/issues/2042

**Comment by octref** [comment]
Seems to be a feature, since this is tokenized as `sys-type` and `time_t` seems to be a standard part of the ISO C library: https://en.wikibooks.org/wiki/C_Programming/time.h/time_t
