### ISSUE TITLE
Hover tooltip won't display Workspace messages.

### ISSUE THREAD

**Issue by edgarngg** [Microsoft/vscode#50848]
Issue Type: <b>Bug</b>

Whenever I hover on things, they try to show a message but I have to hover again to be able to see it.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2328)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 1, 1|
|Memory (System)|15.57GB (2.83GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.9.0
beautify|Hoo|1.3.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.10
gitlens|eam|8.3.2
vscode-npm-script|eg2|0.3.4
sublime-babel-vscode|jos|0.2.10
vscode-language-babel|mgm|0.0.14
polacode|pnp|0.2.2
vscode-filter-json|ric|1.0.0
vscode-icons|rob|7.23.0
gitconfig|sid|1.0.1
react-beautify|tai|0.3.0
prettify-selected-json|vth|1.0.3

(4 theme extensions excluded)

</details>

**Comment by octref** [comment]
Can you record a gif to show what's happening?

**Comment by edgarngg** [comment]
Hi, sure here's a gif, happens from time to time. not constant
![imageedit_1_7786943681](https://user-images.githubusercontent.com/4851108/40803884-9cce92d0-64ce-11e8-95cf-1f30533dc24d.gif)

**Comment by octref** [comment]
Which extension contributes to the section on the left? It doesn't look like built-in file explorer.

**Comment by edgarngg** [comment]
Oh that's vscode-icons extension, but this happens in every part of the workspace there's ability to hover, including the code itself.

**Comment by edgarngg** [comment]
Heres a shot of another case without vscode-icons extension only white theme
![tooltiphoverbug](https://user-images.githubusercontent.com/4851108/40805257-8d6d65f6-64d2-11e8-8541-dff23aa44be0.png)

**Comment by octref** [comment]
Can you give me a whole screenshot - I just want to know which extension contributed to the part containing this:

![image](https://user-images.githubusercontent.com/4033249/40806898-a93d2d48-64d7-11e8-9685-50c8fa415608.png)

**Comment by edgarngg** [comment]
Do you mean the colors, its Andromeda italic theme
![image](https://user-images.githubusercontent.com/4851108/40807134-5326222e-64d8-11e8-81dc-3a9160b051f1.png)

**Comment by edgarngg** [comment]
here's another with all extensions disabled
![image](https://user-images.githubusercontent.com/4851108/40807370-faa97a1e-64d8-11e8-8ffd-ec1ff07ddda4.png)

**Comment by octref** [comment]
@edgarngg OK it doesn't seem to be problem caused by the contributed explorer (such as that of gitlens). Can you try running `code --disable-gpu` to see if that helps?

@bpasero @Tyriar Any ideas? Seems like a electron glitch to me.

**Comment by edgarngg** [comment]
Alright I'll switch over to that and let you know if it still happens. 

Thanks

**Comment by edgarngg** [comment]
This is not happening anymore with --disable-gpu . Hope that helps figuring out what the problem is.

Thanks for the help.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)
