### ISSUE TITLE
Can't always add file to .gitignore file by Command Palette

### ISSUE THREAD

**Issue by ilove3q** [Microsoft/vscode#50844]
Why I can't always add files to .gitignore by Command Palette: git: add file to .gitignore? Someone files which i can do with that but another files I can't do.

- VSCode Version: 1.23
- OS Version: Win 10 and win 7

**Comment by ilove3q** [comment]
@joaomoreno  I don't want to open file .gitignore and wirte in there, i can use Command Palette, it's faster. But somme files can be wirtten, not all

**Comment by joaomoreno** [comment]
I'm asking: What is preventing you to run the command?

Do you see an error? Does the command not work? You need to give me more information.

**Comment by ilove3q** [comment]
I don't know the preventing run the command! On the file which i want to ignore, i run F1 and select add file to gitignore. But the file isn't added to gitignore. And there is not an error notify

**Comment by joaomoreno** [comment]
Nothing happens? Can you share the repository you are using an tell me which file it is? Can you show a screen recording?

**Comment by ilove3q** [comment]
[http://www.upsieutoc.com/image/4hRgOt
http://www.upsieutoc.com/image/4hRjBq](url)
I can upload the images like that, there isn't notify appear
