### ISSUE TITLE
Extension host terminated unexpectedly - which extension?

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#50843]
Sometimes my VSCode is taking 100% of my CPU and way too much memory. When I open Task Manager I can only see multiple tasks for VSCode process not the names of which extensions are responsible for it, which is fine. But when I kill the offender I am getting a nice notification in VSCode that I killed something. 

It would be even nicer if I knew which extension have I killed, so that I can reevaluate if bringing it back to life is in my machine's best interest.

![image](https://user-images.githubusercontent.com/16131590/40749097-8119bebc-6428-11e8-868e-afc096c241e4.png)

**Comment by alexandrudima** [comment]
Can you please take a look at https://github.com/Microsoft/vscode/wiki/Performance-Issues

I think you have already identified that an extension is going crazy in the extension host. So you can look at https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by moseleyi** [comment]
The thing is that I did not identify which extension was killed because the information is not displayed anywhere

**Comment by alexandrudima** [comment]
@moseleyi We cannot automatically determine which extension consumes 100% CPU.

Can you please profile the extensions as described here - https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions and then create an issue against the extension that causes the 100% CPU usage.

**Comment by moseleyi** [comment]
That's strange.. so you report that an extension has been killed but you don't get any information about which one?

**Comment by alexandrudima** [comment]
@moseleyi Yes. It is not possible to correlate the termination of the extension host process with a specific extension automatically.

**Comment by moseleyi** [comment]
Thanks for explanation, that's a shame as it's very difficult to find an offender that uses high cpu or memory but I guess this answers my question

**Comment by alexandrudima** [comment]
@moseleyi Yes, it is possible to find the extension that uses high CPU, it just needs to be a manual process. The steps are documented here https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions
