### ISSUE TITLE
Slow down the laptop performance 

### ISSUE THREAD

**Issue by swarup260** [Microsoft/vscode#50855]
### Issue Type
Bug

### Description

I'm using ubuntu 16.04 ( my pc config. :- i3 6gen,8gb ram and 1 tb hdd) . After opening  Vscode my laptop freeze and also my all over performance decrease. 

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.10.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 2000)|
|Load (avg)|2, 1, 1|
|Memory (System)|7.67GB (2.38GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.0.21
beautify|Hoo|1.3.0
php-namespace-resolver|Meh|1.0.9
material-icon-theme|PKi|3.4.0
syntax-lookup|Syn|0.3.1
vscode-intelephense-client|bme|0.8.8
phpserver|bra|2.4.4
goto-documentation|cxf|0.0.1
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.12.3
php-intellisense|fel|2.3.2
code-runner|for|0.9.3
vscode-phpfmt|kok|1.0.30
code-beautifier|mic|2.0.3
theme-monokai-pro-vscode|mon|1.1.6
mssql|ms-|1.3.1
sublime-keybindings|ms-|4.0.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by octref** [comment]
This is likely caused by the PHP extension you are using. Please open issue in their repository (php-intellisense).

You can also use Help -> Open Process Explorer to see which extensions are causing the problems.
