### ISSUE TITLE
Remove old proposed file system provider api

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#50859]
We have kept the old file system provider api around but now a month has passed and we should remove it.

**Comment by jrieken** [comment]
fyi @dlebu

**Comment by dlebu** [comment]
@jrieken Sounds good. I'll make a change on our end to stop using the old one. How long do we have until you remove it from insiders?

**Comment by jrieken** [comment]
I'll make the change next week and since Insiders is frozen for the May-release it'll be most likely Thursday. Is that ok for you?

**Comment by dlebu** [comment]
@jrieken Thanks for the heads up. I'll follow up with our team and try to release an update before Thursday.

**Comment by jrieken** [comment]
@dlebu Also make sure to use the official activation event `onFileSystem`, not `onFileSystemAccess` which has been removed
