### ISSUE TITLE
weird highlight on javascript

### ISSUE THREAD

**Issue by WhiteCat6142** [Microsoft/vscode#5085]
- VSCode Version:0.10.14-insider
- OS Version:Win7

Like below
if(s.indexOf("abc*:")===-1)continue;*

**Comment by Tyriar** [comment]
What theme are you using and can you provide a screenshot?

**Comment by WhiteCat6142** [comment]
![test](https://cloud.githubusercontent.com/assets/15012282/14365334/19226014-fd48-11e5-9474-7842a07cd71e.png)

**Comment by WhiteCat6142** [comment]
I used Default(Dark+) theme,but theme doesn't affect this issue.
(Sorry for meanless code)

**Comment by Tyriar** [comment]
Thanks :) this is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11
