### ISSUE TITLE
Investigate to rewrite workbench layout using grid widget

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#50853]
Given the introduction of the grid widget, we should explore to use it as the driver for the workbench layout, at least for the parts that are connected via sashes:
* sidebar (left / right)
* panel (bottom / right)
* editor area

**Related issues:**
* Allow 100% panel width even with the explorer view is open #42149
* Provide workbench.panel.location "left" option #37877
* Provide workbench.panel.location "top" option #50984
* Panel and viewlet on right should have a border between them #37373

**Grid widget prerequisites**
* [x] allow to mark a specific view in the grid as the one to resize when the outer container grows (this is to make sure the editor area always increases in size if the window gets larger)
* [x] allow to "snap to hide" so that e.g. you can use the mouse to make the sidebar small enough that it hides and move back to show it again

**Comment by bpasero** [comment]
Some prerequisites for the grid widget before this can happen:
* [ ] allow to mark a specific view in the grid as the one to resize when the outer container grows (this is to make sure the editor area always increases in size if the window gets larger)
* [ ] allow to "snap to hide" so that e.g. you can use the mouse to make the sidebar small enough that it hides and move back to show it again

**Comment by joaomoreno** [comment]
Splitview now supports:

- resize priorities, which allows to mark a specific view in the grid as the one to resize when the outer container grows
- snap to hide

🎆

**Comment by joaomoreno** [comment]
Gridview now supports all of that too! 🎉

**Comment by bpasero** [comment]
Awesome 👍

**Comment by joaomoreno** [comment]
> This looks really cool, if it's what I think it is.

This is very likely not what you think it is.

This issue aims to use the grid widget for layouting. It will not introduce any new layouting features. It will not enable you to move viewlets around. It is a purely engineering issue to clean up some old layouting code.

**Comment by costincaraivan** [comment]
> This is very likely not what you think it is.

😞 So it's clean up/refactoring. Oh well, I imagine it's needed to move forward 😄 

Is there some plan/UX thing about making the terminals more flexible/will there ever be the possibility of using VS Code in a tmux-like fashion? It's so, so close to it. Or, alternatively, is there some sort of longer term roadmap for 2019, so that I can stop spamming this bug report? 😃

**Comment by joaomoreno** [comment]
I believe @Tyriar already runs an issue for that.

**Comment by Tyriar** [comment]
@costincaraivan see https://github.com/Microsoft/vscode/issues/10546#issuecomment-416306717

**Comment by Novack** [comment]
Hello, I cant grasp some of the slang used to define steps and aims here, but I've been told at #65971 that this work would enable us to relocate Debug panels from side bar to bottom?

**Comment by joaomoreno** [comment]
@Novack No, this does not enable that.

**Comment by Novack** [comment]
Ups, thank you.

**Comment by sbatten** [comment]
@joaomoreno After getting the grid layout mostly working on my branch, it seems the methodology of having to remove parts from the grid and add them back is very costly. e.g. toggling the status bar requires adding the status bar under the editor, but first we must remove the sidebar and activity bar, then we can add them all back. This takes around 200ms in my testing which is far too slow for say toggling the menubar in full screen. Would it be possible to hide views without changing their membership in the grid? I can fake this now by setting the size to 0 but this requires a snap value and changing the minimum size (and also adds a sash to resize elements).

Another thing I noticed is that adding or removing a view essentially relays out the grid so I can't batch operations. Anyway to do that?

**Comment by joaomoreno** [comment]
> toggling the status bar requires adding the status bar under the editor, but first we must remove the sidebar and activity bar, then we can add them all back

You're just lacking API on the grid to add the status bar when you don't have a possible reference view.

You are currently using the Grid which works really well for our editor pane. You simply can't `move` or `add` an editor into an area without a reference point (under two existing editors). I can add API for you to be able to do that, a different value for the `direction` parameter.

> Would it be possible to hide views without changing their membership in the grid?

Not a good idea because hiding means everything is still in the DOM (perf) and potentially taking DOM focus. That would propagate into `enabled` state changes all the way down to all the widgets. Removing them is the way to go.

> adding or removing a view essentially relays out

If you add/remove views in the same stack frame, layout should only occur once. There's no setTimeout anywhere which would trigger more layouts. Can you show me those multiple layouts in a single stack frame, using the Perf tool?

**Comment by joaomoreno** [comment]
That extra API needs some extra thought. Let me get back to you on this.

**Comment by joaomoreno** [comment]
An alternative to adding new API to place views next to branch nodes, would be to simply wrap your views around a view wrapper which can be hidden/shown. Here's what that would look like: https://github.com/Microsoft/vscode/pull/67049/files

Such a view wrapper has `show()` and `hide()` methods which will basically add and remove the DOM nodes from the tree as well as notify the grid of the constraint changes. You could wrap all your views with this helper, add them all on startup and conditionally show and hide them on demand.

Would this work for you?

**Comment by sbatten** [comment]
@joaomoreno  oooo will try this today

**Comment by joaomoreno** [comment]
Didn't actually run it, so might not be complete, but you get the idea.

**Comment by marcos-diaz** [comment]
Please note that ideal decoupling should not be just about choosing left/right position of the whole sidebar, but the ability of position each element in whatever panel the user wants, i.e. treeview at left, open files at right, and search at bottom... all at the same time!

**Comment by sbatten** [comment]
closing this item as I believe we have tackled "investigation" :P
