### ISSUE TITLE
API to programmatically begin rename

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50856]
Follow up on #49060

**Problem**
The TS refactor provider uses `activeTextEditor` and the `editor.action.rename` command in order to rename extracted methods / variables. Using `activeTextEditor` causes problems for live share

**Proposal**
I believe we need an API that allows us to begin a rename at a given position in the specific document. This would essentially:

* Make that document the active editor
* Move the selection to the rename location
* Begin the rename operation and show rename UI

I do not believe that a command/api for this exists today

**Comment by jrieken** [comment]
We do have the `editor.action.rename` command which should be used for this. However, it still needs an active editor because the feature requires user interaction. So, we can add the document/uri and position as arguments and make sure we show that editor before running the command.
