### ISSUE TITLE
Cannot search using regular expressions with (?!) in side panel

### ISSUE THREAD

**Issue by infinnie** [Microsoft/vscode#50852]
![image](https://user-images.githubusercontent.com/8168391/40761828-ed2b5028-64cf-11e8-9ab2-82b43803628b.png)

- VSCode Version: 1.23.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open “search” from side panel
2. Enable “Use Regular Expressions”
3. Type `(?!a).`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by infinnie** [comment]
This issue has *nothing* to do with the above linked one, thanks.

**Comment by roblourens** [comment]
vscode's builtin search is based on ripgrep, which doesn't support some regex features like lookaround.

**Comment by infinnie** [comment]
But the Ctrl + F find in document does support this feature.
