### ISSUE TITLE
Task api is still marked as proposed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#50858]
We have moved some of the API to stable but their usage is still restricted with the proposed flag

<img width="1332" alt="screen shot 2018-05-31 at 09 56 59" src="https://user-images.githubusercontent.com/1794099/40769744-0dde0a8e-64b9-11e8-8623-0fd7ed5c4c59.png">

**Comment by dbaeumer** [comment]
Thanks!

**Comment by jrieken** [comment]
Verified in source
