### ISSUE TITLE
JavaScript formatting error

### ISSUE THREAD

**Issue by aayushkapoor206** [Microsoft/vscode#5086]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. Before
![before](https://cloud.githubusercontent.com/assets/13454335/14364253/a53ee48c-fd25-11e5-856a-c556e400f1f0.png)

2. After
![after](https://cloud.githubusercontent.com/assets/13454335/14364269/adbddb7c-fd25-11e5-8acd-2478c9ee2dfe.png)

**Comment by mbana** [comment]
I've tried to diagnose my problem but I can't step through the (minified) VSCode JS code to see what's going on. My code is just refusing to format. Period. The only thing I get in the developer tools:

``WARN: Ignoring commands``

Could you please make a debug version of VSCode avaiable for download on Linux? I believe this might be better in the long run as for the project.

Many thanks

**Comment by egamma** [comment]
The JavaScript formatter is contributed by TypeScript, moving to the TypeScript project for investigation.

@mbana did you try to debug the typescript server or the Code core/renderer process (https://github.com/Microsoft/vscode/wiki/How-to-Contribute#debugging)? The renderer and extension host process supports source maps

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7962
