### ISSUE TITLE
Extension recommendation missing

### ISSUE THREAD

**Issue by giridharangm** [Microsoft/vscode#50868]
Issue Type: <b>Bug</b>

I can't see the extension recommendations

Possible duplicate of #48367, it was closed (not sure why, so, didn't reopen)

VS Code version: Code - Insiders 1.24.0-insider (08537497eecd3172390194693d3d7c0ec8f52b70, 2018-05-31T05:17:57.180Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|7.86GB (1.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
bracket-pair-colorizer|Coe|1.0.55
vscode-eslint|dba|1.4.10
gitlens|eam|8.3.3
prettier-vscode|esb|1.3.1
cpptools|ms-|0.17.3
vscode-icons|rob|7.23.0

</details>
    

### Screens  

![image](https://user-images.githubusercontent.com/2258588/40774969-743217ec-64b6-11e8-8c8f-3198373dec9c.png)  

Also, when I search for `@recommended`, it shows this error:  

![image](https://user-images.githubusercontent.com/2258588/40774993-8978648a-64b6-11e8-918b-8990eb293291.png)

**Comment by ramya-rao-a** [comment]
Thanks for reporting!
This is fixed with https://github.com/Microsoft/vscode/commit/015ec8303cb2f0caf24709bb79fd24444c6361d6

**Comment by giridharangm** [comment]
Awesome! Thanks!
