### ISSUE TITLE
Invalid missing workspace folder warning

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#50866]
* in stall memfs-extension
* run memfs > create workspace
* 🐛 warning shows and sticks

<img width="347" alt="screen shot 2018-05-31 at 11 27 43" src="https://user-images.githubusercontent.com/1794099/40774382-bcde89d0-64c5-11e8-999a-38ece5d58d19.png">

**Comment by Metachemix1** [comment]
It seems if you update the settings via editing the workspace settings in JSON configuration file directly. Closing the workspace and re-importing it '"solves" the issue.

Changing the order of the folders in the editor results in the "can not resolve workspace" error again. Files are saved and viewed correctly though.

**Comment by taradinoc** [comment]
I'm seeing this too, without using extensions or editing any settings files.

Repro steps:

1. Start `code --disable-extensions`
2. File > Open Folder
3. Select a folder
4. File > Add Folder To Workspace
5. Select a different folder

Result:

The second folder has a yellow highlight and exclamation point in the Explorer sidebar. Hovering over it shows the message "Can not resolve workspace folder".
