### ISSUE TITLE
Go to next(previous breakpoint does not work reliably

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#50864]
verifying #31806:

- set one or multiple breakpoints in various files,
- run "Go To Next/Previous Breakpoint" action

Observe:
completely random behaviour. Sometimes I can only go through the breakpoints in one file, sometimes I can switch back and forth between two files. But I'm not able to step through all breakpoints in all files in deterministic order.

I would expect that I can step through breakpoints in the same order as they are listed in the Breakpoints view. And the starting point would be the closest breakpoint in the currently open file. When hitting the end or the beginning of the list, I expect to wrap around.

**Comment by isidorn** [comment]
Good catch
