### ISSUE TITLE
Can't close views when Activity Bar is hidden

### ISSUE THREAD

**Issue by Pnoexz** [Microsoft/vscode#50878]
- VSCode Version: 1.23.1
- OS Version: Linux mint Sylvia

Steps to Reproduce:

1. Hide Activity Bar
2. Open any view (eg, Debug) by any means (ctrl+shift+d, view->show debug, view->open view->debug)
3. Try to close the Debug view without re enabling the Activity Bar

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Ctrl + B to close them
Also View > toggle side bar
