### ISSUE TITLE
JavaScript wrong syntax highlighting for xpath selector

### ISSUE THREAD

**Issue by sdbip** [Microsoft/vscode#50871]
Issue Type: <b>Bug</b>

```javascript
const selector = './/*[starts-with(name(), "component-")]'
```

The `//` characters are interpreted as a single-line comment even though they are part of a string. The same issue applies to back-tick strings and double-quoted strings.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.73GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Johan\Documents\Projects\2MNordic|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|1.2.3
vscode-markdownlint|Dav|0.17.0
githistory|don|0.4.1
todo-tree|Gru|0.0.57
Kotlin|mat|1.6.0
python|ms-|2018.4.0

</details>

**Comment by octref** [comment]
What's the language you are using? In JS/TS they look fine for me:

![image](https://user-images.githubusercontent.com/4033249/40798948-2f956ca0-64c1-11e8-9fd0-1f5c48ee7961.png)
