### ISSUE TITLE
Convert samples to Tasks 2.0.0

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#50876]
We should ensure that all samples provided under https://github.com/Microsoft/vscode-extension-samples us task version 2.0.0. Here is a small recipe how to convert a task 1.0 sample to a task 2.0.0 sample.

**Package.json contains a watch script**

*Replace the content of the tasks.json with*
```js
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "watch",
            "problemMatcher": "$tsc-watch",
            "isBackground": true,
            "presentation": {
                "reveal": "never"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

*Add the following setting to the settings.json*

```js
    // Turn off tsc task auto detection since we have the necessary task as npm scripts
    "typescript.tsc.autoDetect": "off"
```

*Ensure the right pre launch task in launch.json.* It should be

```
"preLaunchTask": "npm: watch"
```

**Package.json DOES NOT contain a watch script**

*Ensure the right pre launch task in launch.json.* It should be

```
"preLaunchTask": "tsc: watch - tsconfig.json"
```

@Microsoft/vscode please check if you own an example and follow the steps above if an update is necessary and check yourself off the list. If you have questions please ping me.

  - [ ] @aeschli
  - [x] @alexandrudima
  - [x] @bpasero
  - [ ] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [ ] @mjbvz
  - [x] @octref
  - [ ] @ramya-rao-a
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @tyriar
  - [x] @weinand

**Comment by egamma** [comment]
![image](https://user-images.githubusercontent.com/172399/41840754-dda903d4-7866-11e8-88a3-b8d099515a36.png)

**Comment by dbaeumer** [comment]
@egamma thanks. Adapted the above samples
