### ISSUE TITLE
[Question] Support PCRE regex for extension?

### ISSUE THREAD

**Issue by Geobert** [Microsoft/vscode#50872]
I don't know if it's the correct place to ask question on VSCode so bear with me if I'm mistaken :)

Is there any plan to support PCRE regex in the future? 

Or at least ECMA 2018 regex to have lookbehind (`(?<=)` and `(?<!)`)  support 

Thanks

**Comment by octref** [comment]
You should open issue for https://github.com/Microsoft/TypeScript for ECMA 2018 regex support.

**Comment by Geobert** [comment]
Done https://github.com/Microsoft/TypeScript/issues/24531

**Comment by mhegazy** [comment]
Based on the discussion in https://github.com/Microsoft/TypeScript/issues/24531, I believe the request here is to allow using ES2018 features in the regexp's support in VSCode features like find/replace. TypeScript is driving the language service for TS and JS but has nothing to do with executing/evaluating these regexp's in VSCode.

**Comment by Geobert** [comment]
@octref: Should this be reopened?

**Comment by octref** [comment]
We use ripgrep and seems no: https://github.com/BurntSushi/ripgrep/issues/188
