### ISSUE TITLE
Consider showing the language pack string in English and the language pack language

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#50875]
We do that for commands and Windows OS for example does the same when installing additional languages.

@sandy081 FYI

**Comment by ramya-rao-a** [comment]
@dbaeumer Are you referring to the notification that we show that a language pack exists?

**Comment by dbaeumer** [comment]
@ramya-rao-a I did not express myself correctly. It shouldn't be English. It should be the language the UI is currently in. So if the UI starts in German, the OS locale is Chinese the message should be shown in German and Chinese. This is what Windows OS does.

**Comment by ramya-rao-a** [comment]
> So if the UI starts in German, the OS locale is Chinese

This is possible if we do `code --locale=de-de` or set the display language to german using the `Configure Display Language` command.

In both cases, at the moment we don't show any message, as the user's explicit choice of the language (German) is already in use.

Why should we show the message to install the Chinese language pack at this moment?

**Comment by dbaeumer** [comment]
Actually, you are right. If I compare that to Windows OS the sting should be shown in both languages when I pick the language pack not when it is to be installed. So in our case it should be in the Extension viewlet when we show the language pack in the editor area.

**Comment by ramya-rao-a** [comment]
> So in our case it should be in the Extension viewlet when we show the language pack in the editor area.

So for a user with OS locale as Bulgarian, the extension editor for the Bulgarian language pack should have a message in both English and Bulgarian saying something similar to what we show in the prompt?

**Comment by dbaeumer** [comment]
No, sorry. For a Bulgarian user the message for a Chinese language pack should be in Chinese and English (best would be Bulgarian but this is IMO not achievable)

**Comment by ramya-rao-a** [comment]
Cant we just get that done via the ReadMe in the language pack?
Some of the language packs already do this.

![lp](https://user-images.githubusercontent.com/16890566/41109760-9cdb5e30-6a2c-11e8-915e-b6062a07ec36.gif)

Agreed that not all language packs do this and we have no way of enforcing this.
In which case, a line just below the description of the language pack in the language of the language pack can help. That sounds good?

**Comment by dbaeumer** [comment]
That sounds good to me.

**Comment by JacksonKearl** [comment]
So it looks to me like every pack has a description in English, via both the title and the actual one-line description. And some packs put their readme in English, while some put it in the target language. Is the idea that we want every language pack to also have a description in the target language? How would we even get that string?

**Comment by ramya-rao-a** [comment]
We would check that string into the file https://github.com/Microsoft/vscode/blob/68ffa00e03677fdb143ae138daab166b3dc05d4d/src/vs/platform/node/minimalTranslations.ts

The language pack will have the translated string which can be extracted from its manigest like we do in https://github.com/Microsoft/vscode/blob/68ffa00e03677fdb143ae138daab166b3dc05d4d/src/vs/workbench/parts/localizations/electron-browser/localizations.contribution.ts#L159

**Comment by JacksonKearl** [comment]
@dbaeumer, Ramya and I discussed having the description for language packs be the title of the language pack, but in the target language. This would remove the duplication currently in language packs where the description is just a rewording of the title. 
Here's an example for Portuguese:
![image](https://user-images.githubusercontent.com/8586769/41181839-1bb6f826-6b28-11e8-886b-7ed0eb0a6efd.png)

**Comment by JacksonKearl** [comment]
Which is similar to the windows system language dialog: 
![image](https://user-images.githubusercontent.com/8586769/41181982-b041fb26-6b28-11e8-8606-bf64914db9a3.png)

**Comment by JacksonKearl** [comment]
We can get something like this pretty easily:
![image](https://user-images.githubusercontent.com/8586769/41196305-7c1ec580-6bf1-11e8-81ba-34a580732e0d.png)

And probably without much more effot get a translated "Language pack extension for {...}", if that would be preferred?

**Comment by dbaeumer** [comment]
The last screen shot make sense for me (minus the fact the language names usually start with a upper case letter. See Spanish and French in the upper screen shot).

**Comment by ramya-rao-a** [comment]
@JacksonKearl `toLocaleUpperCase` should help there.
