### ISSUE TITLE
It is impossible to uninstall MS VS Live Share plugin

### ISSUE THREAD

**Issue by ghadzhigeorgiev** [Microsoft/vscode#50873]
Issue Type: <b>Bug</b>

It is impossible to uninstall MS VS Live Share plugin! It just stucks in "uninstalling......."

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.94GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by sandy081** [comment]
@ghadzhigeorgiev Can you please do the following

- Set the log level to `trace` using `Set Log Level` command
- Retry the operation
- Please share the Shared Process and Current Window logs from Output panel
