### ISSUE TITLE
Odd JSON formatting

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#50882]
Issue Type: <b>Bug</b>

For some reason, half my JSON file now format or separate lines (which is what it used to do, and what I prefer), but the other half formats on single lines.  Why?

<img width="1010" alt="screen shot 2018-05-31 at 10 37 39 am" src="https://user-images.githubusercontent.com/835148/40788805-e6eb557a-64be-11e8-8e90-266546659893.png">

```
[
  {
    "hex": "#3e53a4",
    "variable": "$blue",
    "themecolor": "primary",
    "usage": "Primary button, secondary button borders, active and completed input text, global hyperlink text"
  },
  {
    "hex": "#0072b8",
    "themecolor": "teal",
    "variable": "$medium-blue",
    "usage": "Global accent"
  },
  { "hex": "#009bdf", "variable": "$cyan", "themecolor": "cyan", "usage": "Global accent" },
  { "hex": "#a03f9b", "variable": "$purple", "themecolor": "purple", "usage": "Global accent" },
  { "hex": "#cf0989", "variable": "$magenta", "themecolor": "magenta", "usage": "Global accent, primary headers" }
]
```

VS Code version: Code - Insiders 1.24.0-insider (08537497eecd3172390194693d3d7c0ec8f52b70, 2018-05-31T05:10:58.506Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_2359872|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.5.0
code-settings-sync|Sha|2.9.2
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
bracket-pair-colorizer|Coe|1.0.55
vscode-eslint|dba|1.4.10
tslint|eg2|1.0.30
vscode-great-icons|emm|2.1.32
prettier-vscode|esb|1.3.1
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.10.0
svg|joc|0.1.0
Angular2|joh|6.1.1
code-fragments|mar|1.2.0
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
theme-monokai-pro-vscode|mon|1.1.6
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vetur|oct|0.12.3
vscode-versionlens|pfl|0.21.0
polacode|pnp|0.2.2
stylelint|shi|0.36.3
rewrap|stk|1.9.1
bootstrap4-vscode|the|4.1.1
sort-lines|Tyr|1.7.0
vscode-todo-highlight|way|0.5.12
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by octref** [comment]
Please open issues for prettier.
