### ISSUE TITLE
Feature request: do not apply centered layout to webviews

### ISSUE THREAD

**Issue by christianvoigt** [Microsoft/vscode#50885]
Hi, my use case is the following: 
I am developing a SVG preview extension for a Markdown-like language (similar to the Mermaid extension). The preview uses a webview and should use the full screen in Zen Mode, while the text editor for the language should use the centered layout. 

Currently my webview is displayed with the centered layout, so a lot of space is wasted. I can toggle the centered layout manually, but it would be great if this happened automatically. I suspect that other extensions might have similar problems. If webview providers really want to use a centered layout it would be easy to add a css rule with a max-width, instead of the built in centered layout feature.

The PR for the centered layout had a `centerMode.onlyEditors` setting (https://github.com/Microsoft/vscode/issues/15684). This would be perfect. But apparently this setting has been removed.

**Comment by isidorn** [comment]
This is a fair feature request. I can look into it in June when I plan to look into centered layout for the grid

**Comment by christianvoigt** [comment]
Cool, thank you!

**Comment by isidorn** [comment]
After rewritting the centered layout for the grid layout we decided to no longer limit the centered layout to only be possible to have one editor in it.
Now a user can have custom layout in the centered editor layout. Due to that we no longer automatically enter / exit centered layout.

Due to that I have to close this as will not happen. Sorry

**Comment by christianvoigt** [comment]
Ok, I understand, but maybe there is some other way of allowing custom views provided by extensions some control over how/if the centered layout should be applied? Centering content simply does not make much sense in some cases, especially if the view is displaying graphics instead of text. 

So for example it would be a good solution if an extension could define the maximum width of the content used in centered mode (or use none). I have not looked into the implementation details, so this might make no sense at all. I am just trying to clarify if entering/exiting centered mode automatically is the only way to satisfy this feature request.

**Comment by isidorn** [comment]
Thanks, but this is currently not possible and not on our immediate plan thus I prefer to leave this closed. Thanks for understanding
