### ISSUE TITLE
Full featured support for Behave?

### ISSUE THREAD

**Issue by Valentyn-Khanmamedov** [Microsoft/vscode#50881]
For now only PyCharm professional edition have full support for Behave BDD Gherkin projects on Python. Its a little bit monopolistic. Some VS Code plugins give partially support for behave for example Gherkin plugin. But nice to have a full featured support like this:

Full support for Python Behave 
1. recognizes feature files format and provides syntax highlighting (its partially done by existing gherkin plugins)
2. code snippets for step definitions 
3. navigate from a Scenario description to the actual step definition
4. debug functionality for behave projects

What do you think?

**Comment by octref** [comment]
You should open an issue at https://github.com/Microsoft/vscode-python/issues
