### ISSUE TITLE
File opened in Git View not added to Working Files list

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#5088]
- VSCode Version:0.10.14-insiders
- OS Version:Windows 7

Steps to Reproduce:
1. Open a file in Git View diff
2. Switch to Editor view of the file in the editor.
3. Go to Explorer

File is not included in the Working Files even though open in the editor and switched to Explorer view.
Double-click the file in Explorer and the only change is adding the file to the Working Files list.

**Comment by joaomoreno** [comment]
@bpasero Thoughts?

**Comment by bpasero** [comment]
As designed. We only add if you edit the file.

**Comment by joaomoreno** [comment]
Closing as per comment.

**Comment by gregvanl** [comment]
If I open a file in the editor (double click), it is added to the working files list.
This is the case with or without AutoSave enabled.

**Comment by bpasero** [comment]
@gregvanl but going from a diff to the actual file might not mean the user wants to add the file to working files? he might as well just be interested in reading the file in full.

I think we should be very careful when we add something to the working files list. In the future this will mean adding a heavy weight tab to your list. I would still vote for not adding to working files unless you edit a file or double click it from the explorer.

**Comment by gregvanl** [comment]
Fair enough.  Closing.
