### ISSUE TITLE
Format on save messes up undo stack w/ HTML

### ISSUE THREAD

**Issue by Nxt3** [Microsoft/vscode#50891]
The issue is identical to the one reported here: https://github.com/Microsoft/vscode-go/issues/678

**I'm experiencing this while formatting HTML documents with no external formatters.**

**Comment by felipero** [comment]
This happens to me when `"source.organizeImports": true`. Even when the imports are not changed it adds to the undo stack, so CMD+Z keeps going to the beginning of the file.

**Comment by Nxt3** [comment]
@felipero mine goes to the end of the file.

**Comment by jrieken** [comment]
@Nxt3 Can you add more information and provide reproducible steps? The issue you have mentioned has been fixed since a long time. Is this an issue with only go? Can you reproduce in JS/TS? (I can not). What is your definition of messed up?

**Comment by Nxt3** [comment]
This doesn't have anything to do with `go`--only that the issue reported on that repo is the same, except with HTML.

In the GIF, I make a change to some HTML, save the file (which triggers formatting), and then do `CMD+Z` to undo. I have to perform undo twice, though. It looks like the trailing newline is what the cause is though--not sure.

https://gfycat.com/WelcomeRepentantBluet

**Comment by Nxt3** [comment]
Looks like setting `"html.format.endWithNewline": true,` and `"files.insertFinalNewline": true,` fixes this.
