### ISSUE TITLE
Html script closing-tag not detected when occurs immediately after 2 slashes

### ISSUE THREAD

**Issue by SDP190** [Microsoft/vscode#50898]
Hi, I found a bug, with the html grammar in VS Code, when you place a closing script-tag in the same line immediately after 2 fwd slashes, as:
`<script>  //</script>`
the grammar will not detect the closing tag, and will display it with wrong color format, see images.

This should be marked as a BUG, since a Closing-Tag after 2 slashes is perfectly valid HTML syntax, and so should it be interpreted in VS Code.

(See my post and conversation at [vscode-textmate](https://github.com/Microsoft/vscode-textmate/issues/49), and @alexandrudima suggestion [here](https://github.com/Microsoft/vscode-textmate/issues/49#issuecomment-324358574)).

VS Code:
![sample](https://user-images.githubusercontent.com/16751213/27235025-2fea2a02-528d-11e7-9132-4acd6ab80a2c.JPG)

Visual Studio 2015:
![capture](https://user-images.githubusercontent.com/16751213/27235056-4b630e20-528d-11e7-9479-567e0921b026.JPG)

---

- VSCode Version: Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows 10 (x64) Version 10.0.17134

Steps to Reproduce:

1. Open any html document with VSCode.
2. Insert a script element in the document, and place the script's closing-tag immediately after 2 fwd slashes.

This issue does occur when all extensions are disabled too.

**Comment by aeschli** [comment]
Reproduced with
```
<!DOCTYPE html>
<html>
<head>
    <script>
        //</script>
</head>
<body>

</body>
</html>
```

It's a problem of the TextMate grammar and only affects syntax highlighting.
The HTML language server correctly detects the end script tag.

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#85

**Comment by aeschli** [comment]
We have #20488 as a debt item on our side.
