### ISSUE TITLE
How can an extension use path variables in a settings string that specifies a path?

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#5089]
- VSCode Version: 0.10.14-insider
- OS Version: Windows 10 1511

Steps to Reproduce:

1. Extension provides a setting which specifies a path to a tool configuration file that ships in the extension's install dir.  
2. We want to allow the user to override this path in either a user setting or a workspace setting.
3. We would rather not require the user have to specify a hard-coded absolute path (C:\foo\bar\...) when they override the setting at either the `user` level or the `workspace` level (.vscode\settings.json).
4. So how does an extension handle this situation?  Using a naked relative path e.g. `./ScriptAnalyzerSettings.psd1` would be confusing because the meaning of `.` would likely change depending on which setting file is in effect (global, user or workspace).  
5. I would prefer that our extension could ask VSCode to `expand` certain variables for us before sending the `settings path` to the extension (either during extension activation or when a user changes a settings file).  I would like to see these variables available: `${workspaceRoot}`, `${extensionRoot}` and perhaps `${home}`.  
6. The primary scenario I want to see enabled is having a setting value like `"${workspaceRoot}\custom-settings.psd1`" get translated to an absolute path by VSCode and that absolute path is then provided to the extension e.g. `"C:\work\PowerShell\MyNewModule\custom-settings.psd1"`.

cc @daviwil

**Comment by alexandrudima** [comment]
I think the configuration service could do this such that this knowledge doesn't leak through everywhere.

What do you think @bpasero @aeschli ?

**Comment by bpasero** [comment]
#2809

**Comment by alexandrudima** [comment]
@bpasero I don't think this is about environmental variables (which present a lot more challenges than VSCode built-in paths constants?)

**Comment by rkeithhill** [comment]
The environment variable approach could work.  I see that our extension's language host exe inherits the following env vars from VSCode:

![vscode_envvars](https://cloud.githubusercontent.com/assets/5177512/14392535/0af0dea8-fd7f-11e5-9365-486041d543a5.PNG)

Now, if VSCode also defined VSCODE_WORKSPACEROOT and VSCODE_EXTENSIONROOT we could make this work. However we would have a user education/usability issue.  In some cases (ie launch.json) we tell users to use `${workspaceRoot}` to specify a path to a file in their workspace.  But in settings.json we tell them that to specify a path to a "settings" file in their workspace they have to use `%VSCODE_WORKSPACEROOT%`.  Seems a bit inconsistent.

**Comment by bpasero** [comment]
#2809 covers also variables we introduce.
