### ISSUE TITLE
`typescript.suggestionActions.enabled` prevents greying out of unused variables

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#50890]
With `"noUnusedLocals": true`:

![image](https://user-images.githubusercontent.com/4033249/40797967-b449d9de-64be-11e8-9f0e-90fc24221d14.png)

With it set to `false`:

![image](https://user-images.githubusercontent.com/4033249/40797982-be9d6996-64be-11e8-95ac-f3409cf4aad2.png)

From #50487 I got the impression that when it's set to false (or not set at all), greying out should still happen.

Repro:

- `yo code` for a TS project
- Start typing some unused variables. They won't be greyed out.

**Comment by mjbvz** [comment]
I can't repo this:

<img width="1013" alt="screen shot 2018-05-31 at 10 56 26 am" src="https://user-images.githubusercontent.com/12821956/40798998-4bd14128-64c1-11e8-8d43-559df466e015.png">

Any user settings on your side? Other repo steps?

**Comment by octref** [comment]
Narrowed it down to `"typescript.suggestionActions.enabled": false`.

Once I have it as `true` the grey color works.

**Comment by rebornix** [comment]
@mjbvz not sure if I did anything wrong while verifying this issue:

1. Open VSCode repo
2. Set `noUnusedLocals` to `false`
3. Unused variables are greyed out
4. Set `typescript.suggestionActions.enabled` to `false`
5. They are no longer greyed out.

Based on what @octref described, it seems unused variables should still be greyed out after step 4.

**Comment by mjbvz** [comment]
Yes I see them get temporarily not-grayed out when you first toggle this setting. Reopening or editing the file fixes the issue

The main concern with this bug is that people who previously disabled `suggestionActions` would not see graying out after updating to the new VS Code version. This seems to be fixed in my testing

**Comment by mjbvz** [comment]
Actually there is a bug for updating grayed out vars if you reload the workspace. Will push a fix for that

**Comment by RMacfarlane** [comment]
@mjbvz I'm still seeing the behavior Peng described in the latest build (d49a7913eba125cb44505f1dce90a52e7360a0f5)

**Comment by mjbvz** [comment]
Just checked with @RMacfarlane. This is the problem I mentioned before where toggling the settings resets colorization. Editing the document or reloading the document  gets things grayed out again

Not worth fix since this setting is only one many people are using
