### ISSUE TITLE
Default keybindings that conflict with default Ubuntu OS keybindings

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#509]
_Related https://github.com/Microsoft/vscode/issues/51_

The following default keybindings conflict with default Ubuntu OS keybindings.

Move app to different workspace:

```
{ "key": "ctrl+shift+alt+down",   "command": "editor.action.copyLinesDownAction",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+alt+up",     "command": "editor.action.copyLinesUpAction",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+alt+left",   "command": "workbench.action.focusLeftEditor" },
{ "key": "ctrl+shift+alt+right",  "command": "workbench.action.focusRightEditor" },
```

Maximize/unmaximize(?):

```
{ "key": "ctrl+meta+up",          "command": "editor.action.insertCursorAbove",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+meta+down",        "command": "editor.action.insertCursorBelow",
                                     "when": "editorTextFocus" },
```

**Comment by alexandrudima** [comment]
@Tyriar Again, would love your input to find better out of the box defaults

**Comment by alexandrudima** [comment]
@Tyriar I think the changes for #51 also address this issue. Is that fair?

**Comment by Tyriar** [comment]
@alexandrudima did #51 change `focus*Editor` and `copyLines*Action`?

**Comment by alexandrudima** [comment]
@Tyriar Sorry about that, it was getting late yesterday :smile: You're right, those ones I didn't touch

**Comment by benbro** [comment]
What about Ctrl+D to duplicate line?
This is used in both notepad++ and geany editors:
https://wiki.geany.org/howtos/sorted_keyboard_shortcuts
http://docs.notepad-plus-plus.org/index.php/Keyboard_And_Mouse_Shortcuts
```json
{ "key": "ctrl+d",   "command": "editor.action.copyLinesDownAction",
                                     "when": "editorTextFocus" },
```

**Comment by fiznool** [comment]
Ctrl-d is currently used for multiple cursor selection, I also use this all the time so I'd vote for that to stay as it is!

**Comment by Tyriar** [comment]
Yeah <kbd>ctrl</kbd>+<kbd>d</kbd> is quite a well known keybinding so that definitely isn't going to change.

**Comment by mattez** [comment]
I want to migrate to _vscode_ but, like every body else on Ubuntu, really need to duplicate lines.
Any news about this?

What you recommend?:
- change default Ubuntu keybindings? [Here is how to on AskUbuntu](http://askubuntu.com/questions/744214/how-to-disable-the-keyboard-shortcut-to-switch-between-workspaces). (I haven't tested yet. I don't want to tweak my OS coz of editor)
- or change default keybindings of _vscode_? Is here any conflict free recommended key combination? Have any of you investigate it?

BTW Line Duplication shortcuts in different editors:
_Sublime 2_ use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>D</kbd>
_Brackets_, _notepad++_, _geany_ use <kbd>Ctrl</kbd>+<kbd>D</kbd>

**Comment by alexandrudima** [comment]
@mattez Just customize vscode's keybindings -- `File > Preferences > Keyboard Shortcuts`. 

```json
[{ "key": "ctrl+shift+d", "command":"editor.action.copyLinesDownAction", "when": "editorTextFocus && !editorReadonly" }]
```

**Comment by mattez** [comment]
@alexandrudima Thank you. I'm so impatient. I edited my comment, before I read yours. Now a little ashamed.
It is a pity that the <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>D</kbd> is now used to **Show Debug**	_workbench.view.debug_. It may not suit to all.

**Comment by divyanshu013** [comment]
Hi guys, I can help with this issue if there's a final decision on it. Recently migrated to vscode and ran into this problem today

**Comment by Tyriar** [comment]
I would be hesitant to do anything here as it could break people. However, if there are keybindings that differ on Windows and Linux but they're broken on Linux maybe we could look into this.

Also this issue applies specifically to Unity on Ubuntu which is now deprecated. I haven't checked what windows management keybindings Ubuntu Gnome ships out of the box but we should target them as the primary example on Linux going forward.

**Comment by cpxPratik** [comment]
Why is it not by default set to `Ctrl+D` and `Ctrl+Shift+D` for copy line up and down respectively?? Most editors have them on those bindings.

**Comment by Tyriar** [comment]
@cpxPratik since the initial version ctrl/cmd+d has been assigned to the "Add selection to next find match" command. I wasn't around to explain that decision but it's a very popular keybinding at this point so I doubt we would ever change the default.

**Comment by ryansully** [comment]
I think it's from Sublime Text; I remember using the same shortcut for that as well.

**Comment by cpxPratik** [comment]
@Tyriar I customized key-binding for `copy line down` with `Ctrl+D` and it works for both uses, i.e.  "Add selection to next find match"  too.

**Comment by alexandrudima** [comment]
As we now have very many users on Linux (not only on Unity), I don't plan to make any changes to the default keybindings, as changes to the defaults **will break** the flow of folks not using Ubuntu + Unity.

I am sorry if this causes any grief, but it is very simple to customize keybindings. Furthermore, it is very simple to create an extension which customizes default keybindings. Such an extension could be published to the marketplace and called "Ubuntu Unity optimized keymap" etc.
