### ISSUE TITLE
Wrong Window Title

### ISSUE THREAD

**Issue by wjmsrv** [Microsoft/vscode#50900]
- VSCode Version: 1.23
- OS Version: Windows

Steps to Reproduce:

1. When I open a file the window title shows the path and file name.
2. If there are multiple files open, the window title does not change when I select a different tab.
3. The title doesn't update until I switch to another application then back to VSCode.

**Comment by bpasero** [comment]
@wjmsrv when this happens and you resize the window, does the title then update?
