### ISSUE TITLE
formatOnPaste + code with errors, errors show in wrong location

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50902]
- Open some .ts file
- Have formatOnPaste enabled
- Paste some code that will have errors. It must be multiple lines of text.
- Red squiggles are in the wrong place. They aren't fixed until I make another edit or close/open the file

![image](https://user-images.githubusercontent.com/323878/40809280-ce390962-64de-11e8-8d33-3efd6ddd9cb0.png)

It works in 1.23

Also notice that only the `f` of the first foo is gray.

**Comment by mjbvz** [comment]
Can you please re-test this in a workspace that uses the final release of TE 2.9.1 (not the insiders release of TS). We just picked up this version today and it will be in the next VS Code insiders. After updating, I can't repo this anymore

**Comment by roblourens** [comment]
Yeah we good

**Comment by isidorn** [comment]
Adding verified since @roblourens says this fixed it
