### ISSUE TITLE
Template literal as second assignment expression in ternary breaks highlighting

### ISSUE THREAD

**Issue by garthk** [Microsoft/vscode#5090]
- VSCode Version: `Version 0.10.10 (0.10.10)` or `Version 0.10.14-insider (0.10.14-insider) 17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c`
- OS Version: OS X `10.11.4 (15E65)`
- `javascript.validate.enable` set either `true` or `false`

Steps to Reproduce:

1. Open a new Code – Insiders window
2. Paste in the following JavaScript
3. Observe

```js
function test1(x) {
    const defaultValue = `${x}`;
    const value = x ? x : y;
    console.log('so far, so good');
}

function test2(x) {
    const value = !x ? `${x}` : x;
    console.log('so far, so good');
}

function test3(x) {
    const value = x ? x : `${x}`; // this comment is coloured as if it's part of the template literal
    console.log('this entire line, too');
} // and this one
```

If I'm getting this right:

* `test1` shows `code` knows when a template literal ends, usually
* `test2` shows `code` still knows when a template literal ends if it's the first *AssignmentExpression* in a ternary
* `test3` shows `code` somehow misses the end of a template literal as the second *AssignmentExpression* in a ternary, highlighting from then on as a string

**Comment by garthk** [comment]
I don't think this is the same as #3955, unless the fix promised there hasn't made it into Insiders yet.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#141

**Comment by aeschli** [comment]
I can reproduce in the latest, doesn't seem to be related to #3955.
