### ISSUE TITLE
 Setting search error: Error: XHR timeout: 5000ms

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50904]
1. In settings preview
1. Paste the following in the search box:

    ```
    f sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadff sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadff sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadff sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadff sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadff sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadff sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadff sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadff sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadff sdafadsfdsafiodas[fo kadspof pfds]a f[podsaop[f[poadsfp[ok sadf sdaf sadf fdsaff sdafdsafafdsaffdsafsdafdsafdsafdsafdsafdsafadsfdsafadsf
    ```

1. Type at end 

**Bug**
Notice slugishness, and xhr timeouts in the dev tools

**Comment by roblourens** [comment]
The xhr timeouts are expected, the search service gets really slow with large queries. We don't need to optimize that.

The sluggishness is because it's taking like 2+ seconds to search locally due to creating lots of really large regexes, or something. I'll try to do something about that.

**Comment by roblourens** [comment]
Did some basic safe optimizations in filters.ts, so it's a bit faster now. Could do more but I don't think this case is worth optimizing further.
