### ISSUE TITLE
Multiple Tries

### ISSUE THREAD

**Issue by dmiller72** [Microsoft/vscode#50903]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Many times I have to save more than once for the page to update

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5400  @ 2.70GHz (2 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|2.97GB (0.31GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.55
vscode-svgviewer|css|1.4.4
jquerysnippets|don|0.0.1
prettier-vscode|esb|1.3.1
vscode-install-vsix|fab|1.1.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.3.0
ftp-simple|hum|0.6.3
html-tag-wrapper|hwe|0.2.3
open-in-browser|igo|0.0.99
vscode-github|Kni|0.28.1
wrapSelection|kon|0.6.8
code-beautifier|mic|2.0.3
view-in-browser|qin|0.0.5
live-sass|rit|1.3.0
LiveServer|rit|4.0.0
vscode-icons|rob|7.23.0
sass-indented|rob|1.4.9
code-settings-sync|Sha|2.9.2
html5-boilerplate|sid|1.0.3
code-spell-checker|str|1.6.10
bootstrap4-vscode|the|4.1.1
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.6.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

Please clearly describe what's the behavior and what's the intended behavior and with gif/images.
