### ISSUE TITLE
Using terminal with SSH - typing is lagging

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#50916]
- VSCode Version: 1.23.1
- OS Version: Windows 10 Home 

I'm using VSCode to perform some simple tasks on my server (I used to use MobaXterm) and I use simple SSH.

However when I am logged in to the server and for example type `ls -la` there is at least  1000-2000ms delay between me typing and letters appearing in the terminal (sometimes longer).

I have tested it on different networks so it's not the speed of my internet.

**Comment by Tyriar** [comment]
Can you try the [insiders build](https://code.visualstudio.com/insiders/) and add this setting to see if it's fixed?

```
"terminal.integrated.rendererType": "dom"
```

**Comment by moseleyi** [comment]
I have installed insiders build but it's still very laggy

**Comment by Tyriar** [comment]
@moseleyi can you open devtools (Help > Toggle Developer Tools), go to the performance tab and record a profile? That should reveal what's causing the lag.

**Comment by Tyriar** [comment]
@moseleyi Yes, when you experience the lag

**Comment by moseleyi** [comment]
Okay I don't know what I did but it's not lagging any more, okay maybe just a tiny bit but it's understandable...  I will close this for now but I will remember about profiling it when it happens again and send it over, perhaps there's a correlation between this and some extension, who knows..
