### ISSUE TITLE
Regex hangs VS code

### ISSUE THREAD

**Issue by lionello** [Microsoft/vscode#50915]
Issue Type: <b>Bug</b>

This regex hangs VS code and requires a "force kill": `return (.+)+?=>`

After force kill, the regex is remembered and simple opening the Find widget (CMD+F) will hang VS Code again. Need to close all windows first before showing the Find widget and removing the regex.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
beautify|Hoo|1.3.0
solidity|Jua|0.0.43
sdlang|Lau|0.1.2
vscode-docker|Pet|0.0.27
vscode-direnv|Rub|0.0.2
fish|Ted|0.0.4
quokka-vscode|Wal|1.0.127
Nix|bbe|1.0.1
converter|bey|0.0.3
vscode-standardjs|che|1.2.1
vscode-eslint|dba|1.4.10
dlang|dla|0.9.0
json-tools|eri|1.0.2
gitlab-workflow|fat|0.6.0
url-encode|fle|1.1.0
ansible|haa|0.2.8
applescript|idl|0.10.0
jwt-decoder|igo|0.0.4
plantuml|jeb|2.7.6
fish-ide|lun|0.3.1
ecdc|mit|0.12.0
python|ms-|2018.4.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.246
debugger-for-chrome|msj|4.4.3
vetur|oct|0.12.3
vscode-template-literal-editor|pli|0.9.0
vscode-lldb|vad|0.8.7
jinja|who|0.0.8
markdown-all-in-one|yzh|1.4.0

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
Can you give our Insider build a try? https://code.visualstudio.com/insiders/

I can repro on 1.23.1, but cannot in Insider which will be released next week.
