### ISSUE TITLE
Mislabeled errors in Typescript files (possibly others) in latest insiders build 

### ISSUE THREAD

**Issue by selipso** [Microsoft/vscode#50917]
First of all, thanks for making my new favorite editor. In my opinion, VS Code is my favorite product from Microsoft. Although, I'm getting a bug in the insiders edition that's affecting me to the point of switching back to regular VS Code. Would love to keep testing the insiders build for you if you could please track down and resolve this bug. I disabled all extensions and it still appears in Angular writing Typescript code.

- VSCode Version: 1.24.0-insider
8bf066e3dca775522bdebde4f742e71498b09bca
x64

- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Write Typescript code until an autocomplete suggestion shows up
2. Press Enter when the suggestion matches what you want to write

Result: A red line underneath your perfectly written, correct code. The redline continues to stay even after saving the file and "re-compiling" Typescript.

![image1](https://user-images.githubusercontent.com/5407481/40821424-c26e3e26-651b-11e8-9d58-586ed7413fd5.jpeg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Looks like you are on an old insiders release. Do you see this after updating to the latest version?

**Comment by selipso** [comment]
It does seem to be fixed with the latest release. Thanks! Closing this.
