### ISSUE TITLE
code view cann't resize

### ISSUE THREAD

**Issue by xiaobaolong** [Microsoft/vscode#50914]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
lua-debug|act|0.3.4
workbench|and|0.1.7
code-gnu-global|aus|0.2.2
jshint|dba|0.10.18
vscode-eslint|dba|1.4.10
lua-debug|dev|1.1.0
javac-linter|fau|1.3.1
vscode-lua|gcc|0.1.2
beautify|Hoo|1.3.0
elixirlinter|iam|0.4.1
dynamics-crm-js|JLa|1.2.4
Angular1|joh|0.2.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
Kotlin|mat|1.6.0
lua-intellisense|met|0.2.0
vscode-clang|mit|0.2.2
vscode-elixir|mjm|1.1.0
vscode-language-pack-zh-hans|MS-|1.23.5
python|ms-|2018.4.0
azure-account|ms-|0.4.0
cpptools|ms-|0.17.3
Go|ms-|0.6.80
language-vscode-javascript-angular2|nwa|0.0.11
vscode-docker|Pet|0.0.27
erlang|pgo|0.4.2
vscode-erlang-workbench|pro|0.0.9
java|red|0.25.0
python|tht|0.2.3
vscode-lua|tri|0.12.4
java-snippets|tus|0.0.1
elixir|Twe|0.0.1
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.8.0
erlang-otp|yuc|0.2.4

---

Steps to Reproduce:

1.open the Folder
2.Resize window
3.code view no resize. 
4.close the folder
5.Re open the folder
6.code view resizeed.

****************

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
What do you mean by "code view"? The Editor part?

Can you record a gif http://www-dev.cockos.com/licecap/?
