### ISSUE TITLE
Saving SQL query results as Excel messing decimal points

### ISSUE THREAD

**Issue by mikkosaarinen** [Microsoft/vscode#50918]
Issue Type: <b>Bug</b>

Change country settings on your computer to use comma ',' as a decimal separator.

Run mssql query where the end result have a numeric value in a column. Make sure some values are 0.

=> Results should look like this

4,0000000000000000
0,0000000000000000
6,0000000000000000

Select Save as Excel

=> Excel reports founding an error with the file content and offers to restore as much of the content as it can. If you agree, you see that the decimal format for the zeroes is wrong:

4,00
0.0000000000000000
6,00

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (3.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe Z:\3TEC_ENV\AX2012_3TEC\ProdOrder\TEST_USE\ProdOrder_60_20180531_1435451.xml|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.1

</details>

**Comment by octref** [comment]
Save as Excel is an action offered by mssql extension. Open an issue for them: https://github.com/Microsoft/vscode-mssql
