### ISSUE TITLE
vscode terminal maximum, no responding for a long time

### ISSUE THREAD

**Issue by zmicx** [Microsoft/vscode#50922]
- VSCode Version:1.23.1
- OS Version:Win10

Steps to Reproduce:

1.open vscode , the terminal on the bottom
2. Click "Maximize Panel Size", the window no responding while doing any input
<img width="402" alt="c8c3ed03-dcb8-4890-b71b-857bc2e2492a" src="https://user-images.githubusercontent.com/26269444/40826877-9a8eed04-65ae-11e8-98a0-fe9a7dc0036a.png">

**Comment by Tyriar** [comment]
Can you try the [insiders build](https://code.visualstudio.com/insiders/) and add this setting to see if it's fixed?

```
"terminal.integrated.rendererType": "dom"
```

**Comment by zmicx** [comment]
It works well according to your desc.

**Comment by Tyriar** [comment]
Great! Thats the current workaround for this class of issues, this setting will hit stable this week.
