### ISSUE TITLE
Multiselect across tabs

### ISSUE THREAD

**Issue by Xakher** [Microsoft/vscode#50920]
** Feature request ** 

When the user holds alt to select highlight multiple text segments or create multiple cursors. But when I open another file on another tab and attempt to alt+ select text on both files to change and it does nothing.

**Comment by alexandrudima** [comment]
Focus resides in a single editor at a single time. Only the focused editor is the one that takes input and can be edited.

We will not change this fundamental concept. i.e. allow for having two different editors focused at the same time.
