### ISSUE TITLE
Menus: Alt-key pressed should result in any menu updating

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50926]
There are 2 scenarios where currently we fail to show the alternative command in the editor toolbar menu:

**First Scenario**
* press and hold `Alt` key
* split down
* keep pressing `Alt` key
* 🐛 the toolbar is showing the horizontal split and not the vertical

**Second Scenario**
* press and hold `Alt` key
* focus any non-active editor group
* 🐛 the toolbar is showing the horizontal split and not the vertical

**Comment by isidorn** [comment]
Fixed on bracnh, closing
