### ISSUE TITLE
Wrong path to node in debugger

### ISSUE THREAD

**Issue by modestotech** [Microsoft/vscode#50927]
Issue Type: <b>Bug</b>

Use the following config on a node project, no matter if it's hello world or more complex:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch via NPM",
      "program": "${workspaceFolder}/server.js",
    }
  ]
}
```

I expect the debugger to work, but get the following in the debug console: 
usr/local/bin/node --inspect-brk=44832 server.js 
Node process error: Error: spawn usr/local/bin/node ENOENT

Did some troubleshooting and googling but found no solution. Then I noticed that there's missing a forward slash in the node path, so I added the following to the config: "runtimeExecutable": "/usr/local/bin/node", then it worked. 

I tried to use "runtimeExecutable": "node" and then got the path with the missing forward slash. 'which node' in terminal outputs /usr/local/bin/node.

Where is the erronous path coming from?

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.5.0
code-settings-sync|Sha|2.9.2
vscode-eslint|dba|1.4.10
githistory|don|0.4.1
gitlens|eam|8.3.3
prettier-vscode|esb|1.3.1
intellij-idea-keybindings|k--|0.2.23
node-module-intellisense|lei|1.5.0
debugger-for-chrome|msj|4.4.3

</details>

**Comment by weinand** [comment]
@modestotech are you able to reproduce this problem if you disable all extensions?

**Comment by modestotech** [comment]
@weinand ran the command Disable All Installed Extensions but got the same problem, and the same resolution by setting the explicit "runTimeExecutable" value.

**Comment by weinand** [comment]
@modestotech what happens if you run `node --version` from the command line?

**Comment by modestotech** [comment]
@weinand v10.3.0

**Comment by weinand** [comment]
@modestotech how did you install "node" on your macOS?

**Comment by modestotech** [comment]
@weinand At first I installed it with brew (brew cask install visual-studio-code), but when I got these problems I tried to uninstall it (brew cask uninstall visual-studio-code) and downloaded the Mac release from the the official site. The problem however continued the same. 

Now I'm with the official 'Visual Studio Code.app'.

**Comment by weinand** [comment]
Thanks, but I was asking how you did installed "node" on your macOS?

**Comment by weinand** [comment]
There is something strange here...

If no "runtimeExecutable" is specified, VS Code uses "node" and resolves this against the PATH by using the result from `which node` (https://github.com/Microsoft/vscode-node-debug2/blob/949cdf91e1a6221e885eb69e40c9e794e9296760/src/pathUtils.ts#L220).

I could not find any code that would strip off the leading slash.

**Comment by weinand** [comment]
Does it make a difference if you launch VS Code from the command line?

To answer this try the following:
- shutdown VS Code completely (close all windows),
- in a terminal "cd" to the directory where your project from above lives
- launch code by running "code ."
- press "F5" to start debugging

Do you see the same problem?

**Comment by modestotech** [comment]
@weinand Sorry, my bad. 
I had installed node with Homebrew. Now I tried to uninstall node totally by following this [https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa]. Afterwards I installed node from brew and the path from which is correct (same as before, /usr/local/bin/node).

**Comment by modestotech** [comment]
@weinand Yes, when I started VS Code from the command line, it works and the debugger gets the right path. /usr/local/bin/node. I repeated once again and the same result, from terminal it works, but not by opening the app from the OSX dock.

**Comment by weinand** [comment]
Could you please try this:
- shutdown VS Code completely
- launch VS Code from the Finder or macOS Dock
- fix your launch config by setting "runtimeExecutable" to "/usr/local/bin/node"
- instead of running your server.js run this program and remember the result:
  `console.log(process.env["PATH"]);`
- shutdown VS Code
- now launch VS Code from a terminal
- run `console.log(process.env["PATH"]);` again
- compare the two PATHs.
Do you see something that could explain the problem with the missing leading slash?

**Comment by modestotech** [comment]
Tried according to your instructions. Got the exactly same path in both (compared the length of the strings just to be sure). Just to be clear, I ran console.log command in the node shell, was that what you intended? 
`node`
`console.log(process.env["PATH"]);`

**Comment by weinand** [comment]
No, run it as the "server.js" program from your launch configuration.

**Comment by modestotech** [comment]
Hi again, OK, did that now and got the same result. 
`/usr/local/opt/sqlite/bin:usr/local/bin:usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/max/Library/Android/sdk/tools:/Users/max/Library/Android/sdk/platform-tools`

**Comment by weinand** [comment]
There are two paths in your PATH that are fishy because they don't start with a slash:
`usr/local/bin:usr/local/sbin`

Could you try to fix those (e.g. in .bash_profile) and try to reproduce the problem again.

**Comment by modestotech** [comment]
Well observed, that was the problem. I cleaned up my path variable configuration and now it works. Big thanks for the great support. 
Can you explain why I got this problem with VS Code debugger started from the command line? I haven't had any other path related problems whatsoever, despite the erroneous variable.

**Comment by weinand** [comment]
I do not have a full explanation for the different behaviour in your specific case, but I know that there is a big difference in the environment passed to VS Code when launched from the command line vs. when launched from Finder/Dock. See #50340.

I will leave this bug open for June to investigate why VS Code chokes on this...

**Comment by modestotech** [comment]
Yes, @weinand, that's what I meant. 

Ok, thanks again for the support.
