### ISSUE TITLE
"Open containing folder" crashes when running as root user

### ISSUE THREAD

**Issue by pro-panda** [Microsoft/vscode#50928]
- VSCode Version: 1.23.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open VSCode using root
2. Right click on any file in the explorer and click on `Open containing folder"
3. VSCode crashes

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by Pro-Panda** [comment]
Hi, no `crash` file was formed even after VSCode hung

**Comment by bpasero** [comment]
@Pro-Panda is "root" your normal `C:\` drive or something special?

**Comment by Pro-Panda** [comment]
I am using `Ubuntu 16.04`
By `root`, I was referring to use VSCode with `sudo` permissions.
I usually launch VSCode in `sudo` using: 
```shell
sudo code --user-data-dir=".vscode-root"
```

**Comment by pro-panda** [comment]
@bpasero, any updates on this one ?

**Comment by pro-panda** [comment]
Fixed in one of the recent releases (was unable to reproduce the issue)
