### ISSUE TITLE
Actions.find overlaps the first 2 lines of code

### ISSUE THREAD

**Issue by apostolosapok** [Microsoft/vscode#50929]
- VSCode Version: 1.23.1
- OS Version: Windows Server 2016

Steps to Reproduce:

1. Open actions.find ctrl+f
2. Open new tab ctrl+n

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
@rebornix I remember it used to be Cmd+F always give space to first 2 lines...Now this only applies to untitled files but not other files. Was that intentional?

**Comment by rebornix** [comment]
We didn't re-adjust the position of the find widget when you switch editors, otherwise you will see flickering over often. You can scroll down the editor a bit and then the first two lines will not be covered.
