### ISSUE TITLE
[Feature request] Keyboard shortcuts backward/forward bigword

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#50925]
For example on my terminal I have
```
"\e[3C": vi-forward-bigword
"\e[3D": vi-backward-bigword
```
to navigate between words using Alt+left/right, (faster than Ctrl+left/right). For example `foo bar/test.qux|` pressing Ctrl+left there will lead to `foo bar/test.|qux`, pressing Alt+left leads to `foo |bar/test.qux` which is very practical.

I don't even find Ctrl+left/right in vscode shortcuts, I guess it's native electron/chrome behavior, so it should more be an extension?

### Edit

I see the `integrated-terminal` tag, I think it could not only work on terminal, but in editor as well!

**Comment by Tyriar** [comment]
For the terminal there are several commands that let you jump words which do just this. They are intercepted before being sent to the shell and handled at the VS Code level. There is also a new command coming which allows you to bind keys in VS Code and send arbitrary text. Look out for the `...sendSequence` command in 1.28.

You can configure keybindings in the editor to do this.
