### ISSUE TITLE
Notification progress should show title and increment message

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#50932]
The progress API allows for a title and for messages. Both should be shown, the former is the context the latter steps, Sample: a title would be 'Installing Extension "Foo"' and messages could be 'Checking Version...', 'Downloading...', 'Extracting...', 'Moving Files...'. Today, the title, so the name of the actual operation, hides as soon as a message shows. 

![jun-01-2018 11-17-25](https://user-images.githubusercontent.com/1794099/40833402-20bbef92-658e-11e8-98af-8a19b59289db.gif)

**Comment by bpasero** [comment]
@jrieken I mimic the behaviour we already had:

![before](https://user-images.githubusercontent.com/900690/40833915-85bfad06-658f-11e8-8abb-71f693a27d32.gif)

Changing this now might break extensions that rely on our current behaviour. And if we change it it should be changed also in that status bar location.

**Comment by bpasero** [comment]
Notifications now show the title together with the message if provided:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/40907744-0ad06042-67e5-11e8-8dbd-bf2eb1b366dc.gif)

This also fixes a bug where the notification would actually not show up if the initial `title` was not provided. Now it will show up as soon as a `message` is provided.
