### ISSUE TITLE
Profiling with --inspect-extensions stalls at "Loading profile..."

### ISSUE THREAD

**Issue by ypresto** [Microsoft/vscode#50935]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. code-insiders </path/to/project> --inspect-extensions=9333 --disable-extensions
2. Open inspector URL written in console with chrome.
3. Click "Record" button (gray circle button on top-left) in "Performance" tab
4. (Buffer usage does not increase with any operation)
5. Click stop.
6. "Loading profile..." is shown and no progress in the gauge.

![image](https://user-images.githubusercontent.com/400558/40835886-c76c7014-65cf-11e8-972b-196ae2118f0f.png)

VS Code version: Code - Insiders 1.24.0-insider (a8816968fed45b2cf2ecd67dd3a1678c819d19b3, 2018-06-01T05:10:45.091Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron /Users/yuya/repo/github.com-private/codetakt/portal/ --inspect-extensions=9333 --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by jrieken** [comment]
> Click "Record" button (gray circle button on top-left) in "Performance" tab

I don't think that makes such sense because the extension host run headless without rendering (no html, css, layout etc). You should use the JavaScript CPU Profiler, not the Performance tab. To do that, open `chrome://inspect/#devices` in Chrome and select 'Open dedicated DevTools for Node'
