### ISSUE TITLE
Bug in comments that contain ';' symbol

### ISSUE THREAD

**Issue by khalil2535** [Microsoft/vscode#50938]
Issue Type: <b>Bug</b>

There is a bug when i format and there are comments contain the semicolon symbol they align doubled then when i reformat all the lines align again so they keep aligning more and more.

example :-
before : 
```
w2 dw '12','3'  ; valid
; w1 dw '123'     not vaild
```
after: 
```
w2 dw '12','3'   ; valid
                 ; w1 dw '123'     not vaild
```
after format (#2):
```
w2 dw '12','3'    ; valid
                  ; w1 dw '123'     not vaild
```
after format (#15):
```
w2 dw '12','3'                 ; valid
                               ; w1 dw '123'     not vaild
```

Extension version: 0.0.1
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.4.132-53-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3099)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (2.43GB free)|
|Process Argv|/usr/share/code/code /home/khalil2535/TASM/A.ASM /home/khalil2535/TASM/A.MAP /home/khalil2535/TASM/A.OBJ|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by octref** [comment]
What's the language? What extensions are you using (`code --list-extensions`)?

**Comment by khalil2535** [comment]
ASM Comment Aligner
link : https://marketplace.visualstudio.com/items?itemName=ipid.asm-comment-aligner
photo for it : 
![spectacle tj9574](https://user-images.githubusercontent.com/26520106/40887282-371aa98c-674f-11e8-86da-bc26839f1685.jpg)

**Comment by khalil2535** [comment]
Assembly language
