### ISSUE TITLE
Code completion list pops up when type a period in the end of comments

### ISSUE THREAD

**Issue by Luberen** [Microsoft/vscode#50939]
If I type comments in Korean text and put '.' in the end, code completion list pops up.

Steps to Reproduce:

1. Write comments in Korean text
2. Type '.'

![koreancomment](https://user-images.githubusercontent.com/26616056/40838713-68441a8c-65da-11e8-8963-64a7a0ae3039.png)

English font is text is _Hack_ and Korean font is fallback font.(_Hack_ doesn't support Korean) The issue doesn't occur when I write comments in English text.

**Comment by octref** [comment]
Please open an issue at https://github.com/Microsoft/vscode-cpptools.
