### ISSUE TITLE
Grid: Implement "Centered Editor Layout"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50936]
We should restore the functionality we had. Ideally the code we used to have could be encapsulated into a widget that has these features:
* sashes to the left and right with a container in the center
* sashes move on both sides if one side is dragged
* some way to persist and restore view state

Having this widget, we can throw it into an editor group view based on the condition that centered editor layout is enabled or not.

**Comment by isidorn** [comment]
Yeah this makes perfect sense. I can look into it next week.
