### ISSUE TITLE
Grid layout: support for editor groups merging when dropping onto tabs container

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#50948]
@bpasero testing the latest build with grid layout support:

1. It's possible to move a single tab from one group to another
2. It's possible to split a group by multiple tabs
3. It's not possible to move multiple tabs from one group to another, shouldn't this be supported too?

![move multiple tabs](https://user-images.githubusercontent.com/1812093/40842937-b0158c22-65af-11e8-9ff6-4e9ccaea3757.gif)

**Comment by bpasero** [comment]
@fabiospampinato in your case you drag the space to the right of the last tab into another editor group's tab container empty space, is that true? And you would expect all the editors of the dragged group to go into that space?

**Comment by fabiospampinato** [comment]
@bpasero precisely.

I'm interpreting dragging from an editors group's tabbar as dragging all the tabs simultaneously. This is basically want's happening when splitting an editors group this way (the second point in my bullet list).

It makes sense to me that since I can drag a single tab to another editors group, and since I can drag multiple tabs, I should also be able to drag multiple tabs to another editors group.

**Comment by bpasero** [comment]
The editor group can now be dropped:
* after the last tab to open the editors at the end
* on top of any tab to open the editors there

Unless the operation is a copy operation (e.g. pressed `Alt`-key), the editors will be moved over (otherwise copied).
