### ISSUE TITLE
${workspaceFolder} does not work co

### ISSUE THREAD

**Issue by ari-siuvatti** [Microsoft/vscode#50949]
- VSCode Version:1.23.1
- OS Version:Windows 10, Ubuntu 17.04

Steps to Reproduce:

1.  Add following file load command to launch.json content:
"version": "0.2.0",
    "configurations": [
        {........
            "setupCommands": [
                     { "text": "load ${workspaceFolder}/build/xxxfile.hex}

That works fine in Linux but not in Windows because ${workspaceFolder} include double backslashes remaining part of the path includes normal slashes. If I change slashes to backslashes  it does not work either. I would like to use the same version of launch.json for both Windows and Linux therefore I prefer to have some workaround tip for this or fix it in VSC if it is really a bug and not my misunderstanding.

2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Use the `linux` and `windows` subcategories of the launch.json. More about that can be found here https://code.visualstudio.com/docs/editor/debugging#_platform-specific-properties
