### ISSUE TITLE
Grid - issues with editor toolbar when tabs disabled

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50957]
- Use grid view build
- Disable tabs and autosave
- Change a file
- The group header `x` should change to a circle, and doesn't
- It's correct with tabs enabled

**Comment by bpasero** [comment]
There is actually more issues besides that: we no longer show the "Close" action for inactive groups when tabs are disabled making it impossible to close inactive groups.

**Comment by bpasero** [comment]
Pushed a fix to restore the previous behaviour where the "Close" action will show, even for empty groups. The action will show a dot if the file is dirty. The only thing we lost as part of moving to commands is that the action becomes a X when you hover over it. I could not figure out a way to do this properly using menu service.
