### ISSUE TITLE
Insiders: JS move to new file refactoring import * as refs don't update

### ISSUE THREAD

**Issue by f0urfingeredfish** [Microsoft/vscode#50953]
Issue Type: <b>Bug</b>

If you select a named export with your cursor and choose "Move to new file" the export is moved and named imports are updated but imports using `import * as myExports from 'myModule;'` don't get updated. I would expect a new named import to be added with the correct path to the new module and all the references to `myExports.export` to be changed to the new import.

VS Code version: Code - Insiders 1.24.0-insider (08537497eecd3172390194693d3d7c0ec8f52b70, 2018-05-31T05:10:58.506Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1122578|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by f0urfingeredfish** [comment]
Screen recording of it not updating * imports.
[http://recordit.co/l2dzXnHkHH](http://recordit.co/l2dzXnHkHH)

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/24583 to track this upstream
