### ISSUE TITLE
Running task with arguments using Powershell causes malformed command

### ISSUE THREAD

**Issue by baynezy** [Microsoft/vscode#50956]
- VSCode Version: 1.23.1
- OS Version: Windows 10 build 16299.431

Steps to Reproduce:

1. Run this task without arguments. It runs as expected

```
    {
        "label": "vstest",
        "type": "shell",
        "command": "dotnet vstest",
        "group": {
            "kind": "test",
            "isDefault": true
        },
        "presentation": {
            "echo": true,
            "reveal": "never",
            "focus": true,
            "panel": "shared"
        },
        "problemMatcher": "$msCompile"
    }
```

2. Now add aguments

```
    {
        "label": "vstest",
        "type": "shell",
        "command": "dotnet vstest",
        "args": [
            "./test/Api.Test/bin/Debug/netcoreapp1.1/Api.Test.dll",
            "./test/Api.IntegrationTest/bin/Debug/netcoreapp1.1/Api.IntegrationTest.dll"
        ],
        "group": {
            "kind": "test",
            "isDefault": true
        },
        "presentation": {
            "echo": true,
            "reveal": "never",
            "focus": true,
            "panel": "shared"
        },
        "problemMatcher": "$msCompile"
    }
```

Errors with rogue ampersand:-

	> Executing task: & 'dotnet vstest' ./test/Api.Test/bin/Debug/netcoreapp1.1/Api.Test.dll ./test/Api.IntegrationTest/bin/Debug/netcoreapp1.1/Api.IntegrationTest.dll <

	& : The term 'dotnet vstest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
	spelling of the name, or if a path was included, verify that the path is correct and try again.
	At line:1 char:3
	+ & 'dotnet vstest' ./test/Api.Test/bin/Debug/netcoreapp1.1 ...
	+   ~~~~~~~~~~~~~~~
		+ CategoryInfo          : ObjectNotFound: (dotnet vstest:String) [], CommandNotFoundException
		+ FullyQualifiedErrorId : CommandNotFoundException

	The terminal process terminated with exit code: 1

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
You need to either specify one command or make `vstest` and argument as well. Otherwise VS Code interprets `dotnet vstest` as a command with spaces and quotes it. With `1.24` you can split a command into multiple lines which improves readability (in general a single command is preferred over a command with args since typing into a shell doesn't really have the concept of a command and args. It has the concept of a command line). In your example that would be

```
   "command": [
      "dotnet vstest",
      "./test/Api.Test/bin/Debug/netcoreapp1.1/Api.Test.dll",
      "./test/Api.IntegrationTest/bin/Debug/netcoreapp1.1/Api.IntegrationTest.dll"
   ] 
```

But as said this is only possible with 1.24.
