### ISSUE TITLE
Use dependsOn with background/watch task

### ISSUE THREAD

**Issue by timm-aym** [Microsoft/vscode#50951]
With a `task.json` like the following, I'd like to be able to 

I want to create a task in VS Code that starts `webpack` after `tsc --watch` has emitted the first time.

So far I have been unable to write a `tasks.json` that would achieve this, as the webpack command was executed either too early (`development`) (no files written yet), or never (`development-v2`) (as the `tsc` process was still running).

Should this be supported as of today? Otherwise I would change this into a feature request.

`tasks.json`:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "TSC watch",
      "command": "yarn",
      "args": ["ts-watch"],
      "problemMatcher": "$tsc-watch",
      "isBackground": true
    },
    {
      "label": "webpack development build and server",
      "command": "yarn",
      "args": ["development:webpack-and-server"]
    },
    {
      "label": "development",
      "dependsOn": ["TSC watch", "webpack development build and server"]
    },
    {
      "label": "development-v2",
      "command": "yarn",
      "args": ["development:webpack-and-server"],
      "dependsOn": ["TSC watch"],
      "group": "build",
      "problemMatcher": []
    }
  ]
}
```
- VSCode Version: 1.23.1
- OS Version: macOS 10.13.4

**Comment by dbaeumer** [comment]
@timm-aym this is currently not possible. Major reason is to determine when tsc watch has emitted the first time. This is information the problem matcher has right now but the task system itself only knows when a task as started and when it has finished. But I agree that this is something useful for the system.

**Comment by alexr00** [comment]
Same root request as #6209
