### ISSUE TITLE
Wrong Code Highniting 

### ISSUE THREAD

**Issue by serhioV** [Microsoft/vscode#50954]
Issue Type: <b>Bug</b>

It seems the comments are not differentiated from the string literals, in order to format/highlight the code

```
foreach (Node child in node.XPath("./*[string(umbracoNaviHide) != '1']").Items)
{
  var i = 0;
 string myRegEx = "/*that is not a comment ";
 myRegEx =myRegEx.Trim();
  /*this is a comment*/
}
```

the "./*" in that case is not a comment start, but a XPath expression, inside a string, there is no need to indentify comments inside the " "

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.40GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.10
beautify|Hoo|1.3.0
csharp|ms-|1.15.2
notepadplusplus-keybindings|ms-|1.0.2
team|ms-|1.136.0

</details>

**Comment by mjbvz** [comment]
Cannot repo in VS Code insiders with all extensions disabled:

![screen shot 2018-06-01 at 2 41 56 pm](https://user-images.githubusercontent.com/12821956/40864750-f8d0485e-65a9-11e8-86d8-8750b2714342.png)

**Comment by serhioV** [comment]
here is an example of a cshtml file 
![image](https://user-images.githubusercontent.com/6714786/40910700-1d97ee36-67ed-11e8-94bf-9f5986160ace.png)

**Comment by aeschli** [comment]
This issue was moved to demyte/language-cshtml#21
