### ISSUE TITLE
Issue with saving

### ISSUE THREAD

**Issue by llama5476** [Microsoft/vscode#50966]
Issue Type: <b>Bug</b>

When I'm typing, at any random moment, it won't save changes. It could happen at anytime. A window pops up and says it couldn't save. The only thing I can do is click on 'save as' and rename it as a new file.  This happens whether autosave is enabled or not.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (10.06GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.55
beautify|Hoo|1.3.0
LiveServer|rit|4.0.0
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by Tyriar** [comment]
Does it happen when you close all windows and run `code --disable-extensions`?

**Comment by llama5476** [comment]
"Does it happen when you close all windows and run code --disable-extensions?"

No, it happens any random time, if I am autosaving, it pops up in the bottom right corner as I am typing code. If I am not autosaving it will pop up when I save. It doesn't happen all the time. I never know when

**Comment by bpasero** [comment]
@llama5476 can you show the popup you see?

**Comment by llama5476** [comment]
I'm sorry I couldn't respond, because I was waiting until I could get a screenshot of it when it happened. It finally happened.
![failed to save](https://user-images.githubusercontent.com/38653910/41442200-068b90d4-7004-11e8-8b68-ed23953821ea.JPG)
