### ISSUE TITLE
Allow to hide the settings icon in the sidebar

### ISSUE THREAD

**Issue by baxebu** [Microsoft/vscode#50965]
How to hide wrench on sidebar? I hate this icon. Is there any way to hide it?
![aw6xt](https://user-images.githubusercontent.com/33215968/40857971-034f0100-6607-11e8-9a1d-136c7354cbde.png)

**Comment by sandy081** [comment]
This is not configurable to hide. May I know the reason why do you need this to be hidden?

@bpasero FYI

**Comment by bpasero** [comment]
@baxebu what you can hide, is the entire activity bar:

`"workbench.activityBar.visible": false`

**Comment by baxebu** [comment]
> `"workbench.activityBar.visible": false`
No. I this option and so know. I mean it is the icon of a wrench?

**Comment by baxebu** [comment]
> May I know the reason why do you need this to be hidden?
It just seems to me that this icon is not logical, and aesthetically looks superfluous. When errors in the code are highlighted I accidentally constantly click on this icon wrench, which is not very convenient.

**Comment by xeoneux** [comment]
@bpasero it's not clear if this icon is for settings or not. It should actually be a wrench.

**Comment by baxebu** [comment]
Why you close this issue?

**Comment by baxebu** [comment]
Why can't you hide this icon, make this functionality? Why don't you want to hear people's opinions? You don't give a fuck ?

**Comment by johnykes** [comment]
I also want to hide it, without hiding the activity bar
