### ISSUE TITLE
Allow extension to disable save prompts for individual documents (but display dirty state)

### ISSUE THREAD

**Issue by grork** [microsoft/vscode#50969]
In Visual Studio Live Share, when you're a _guest_, all edits are propagated to the host, who is the source of truth.

However, when the guest closes a document, and it's dirty, they get prompted if they want to save (yes/no/cancel). In the case of the 'yes', we detect it, and ask the host to perform the save. For 'no', we're in a bind, since reverting the file doesn't make sense -- you're no longer making a decision with 'no' that only impacts your IDE state. Other participants can continue to work on that document, and _don't_ want the document to be reverted.

In a perfect world, we'd like the dirty state indicator to continue to function, but have no prompt when the guest closes the document -- they can reopen it to get back to where they were, and there's no data loss. Additionally, if they hit save, we'd still like to know and decide how to handle that.

I don't see a way with editors/documents to:
1. Change it to not prompt
2. Participate before closing (e.g. `onWillCloseTextDocument`) to 'save' the document, so it doesn't appear dirty
3. Override the dirty state

Ultimately, LiveShare is a _view_ onto the hosts content, and there for needs more nuanced control of these indicators/prompts

**Comment by bpasero** [comment]
This should have gotten significantly better for readonly sessions given we no longer report them as dirty (via https://github.com/microsoft/vscode/issues/89405). 

I think the fix here is not to disable the save dialog but allow to close an editor even if it is dirty, or revert it.
