### ISSUE TITLE
Use Polkit on Linux

### ISSUE THREAD

**Issue by Paviluf** [Microsoft/vscode#50964]
Vs Code should use Polkit on Linux instead of Kdesudo / Gksudo / Pkexec. It seem that Vs Code use a module called sudo-prompt to elevate privileges.

https://github.com/electron/electron/issues/13106
https://github.com/Microsoft/vscode/issues/46560
https://github.com/Microsoft/vscode/issues/49270

**Comment by Tyriar** [comment]
@Paviluf would this request make more sense to file against `sudo-prompt`?

**Comment by bpasero** [comment]
Yes, please.
