### ISSUE TITLE
Font size doesn't change on-scroll on Windows 7.

### ISSUE THREAD

**Issue by adsingh14** [Microsoft/vscode#50963]
Issue Type: <b>Bug</b>

These shortcuts aren't working on Win 7.
`Ctrl+ScrollUp`
`Ctrl+ScrollDown`

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:38.209Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by alexandrudima** [comment]
The following must be configured: `"editor.mouseWheelZoom": true` in order for those shortcuts to work.
