### ISSUE TITLE
Intellisense doesn't work with NVM installed

### ISSUE THREAD

**Issue by EWhite613** [Microsoft/vscode#5097]
- VSCode Version: 0.10.11
- OS Version: OS X Yosemite v10.10.5
I have the issue described here: http://stackoverflow.com/questions/36502661/visual-studio-code-intellisense-not-working-on-mac/36503223#36503223

I was attempting to use intellisense following the steps http://stackoverflow.com/a/29993408/3771965 . My colleague got it working. But mine wasn't. Our only difference in environment was that I use Node Version Manager (NVM) and he did not. Once removing NVM and installing plain node, following a restart of VsCode the reference path began to work.

**Comment by dbaeumer** [comment]
@EWhite613 VSCode is not relying on any node version installed so nvm shouldn't have any impact on  this. Would you be able to share your project (or better the one that failed) so that I can try to understand why that was the case?

**Comment by EWhite613** [comment]
Can't reproduce anymore
