### ISSUE TITLE
Allow settings in package.json to be registered as 'private', or allow writing of unregistered settings

### ISSUE THREAD

**Issue by grork** [Microsoft/vscode#50977]
Our extension makes use of transient settings that are used in the `.code-workspace` file to help us in the case of reloading. However, while we generate the `.code-workspace' file outside of Code (we just generate some JSON), and can _read_ unregistered settings from the workspace without registering them, but we can't write them.

We'd like to be able to clear them -- but updating an 'unregistered' setting throws an exception. Registering them is fine, except they now show up in the settings editor, and these are not intended to be used by customers, so we'd rather they didn't show up in auto complete. Marking them 'internal' or 'private' would be one way to resolve this -- or allowing us to write them if they exist, even if not registered.

**Comment by eamodio** [comment]
Related to https://github.com/Microsoft/vscode/issues/30165

I would also love to be able to delete unregistered setting (i.e. old deprecated settings)

**Comment by sandy081** [comment]
@grork Is your use case is to remove the unregistered settings similar to #30165 or you would also want to update unregistered settings? If so, why?

**Comment by grork** [comment]
@sandy081 It's both. We cause our extension to deactivate/reactivate, as well as "open" a workspace (see https://github.com/Microsoft/vscode/issues/50013 for some reasons why)

This means that the information we 'smuggle' in the `.code-workspace` file to help us connect to our remote session on load -- we need to clear that info in the case of #50013 so we don't reconnect. However, there are some additional fall out situations from that that if someone tries to reconnect, we can't get them to "open" the same `.code-workspace` file, because VSCode says "you're already open". So we smuggle info into our state saying "We had been this one, so when you try to open that one, do it slightly differently".

I know one response is "You're extension should use an external settings file, vs code workspace settings are meant for the user" -- and maybe we could, but since we support multiple disparate sessions concurrently (in different windows), this becomes _another_ file to track. The `.code-workspace` is a convenient location to store things, since it is workspace local to the session, and it's easy to clean up as a single item.

**Comment by sandy081** [comment]
@grork In short you are using .code-workspace file for carrying some information that does not belong to .code-workspace file. And you use configuration API to read? Now you want to use the same API to write?
