### ISSUE TITLE
VSCode keeps opening 2nd tab with the same file

### ISSUE THREAD

**Issue by farlock85** [Microsoft/vscode#50973]
Open a failry complex typescript file. After a few minutes of editing and ctrl+clicking references it will suddenly open a 2nd tab of the same file which go out of sync.

The syntax parser will go completely haywire on the file you are editing resulting in formatting the document completely throwing it off.

The only solution is the save all files, close them an re-open them.

Happening in version 1.23.1

Edit: easy to reproduce: double click a file in the explorer so that the filename in the tab is not italic, ctrl+click on a function name that should jump to a function in the same file, it will open a new tab with the same document.

**Comment by mjbvz** [comment]
Do you still see this in VS Code insiders?

Possible duplicate of #51183

**Comment by farlock85** [comment]
Haven't come across it for a few days now!
