### ISSUE TITLE
Changing display language needs restart to take effect, but user is not notified of the same

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#50970]
Changing display language (either via the `Configure Display Language` command or editing the `locale.json` file directly) needs restart to take effect, but user is not notified of the same.

I would suggest that we show a prompt that would say something like `A restart is required for the change in display language to take effect`. Options being `Restart` and `Dont show again`.

**Comment by dbaeumer** [comment]
Makes sense

**Comment by JacksonKearl** [comment]
The `Configure Display Language` command seems to just open `locale.json` for editing. `locale.json` has default contents:
```
{
	// Defines VSCode's display language.
	// See https://go.microsoft.com/fwlink/?LinkId=761051 for a list of supported languages.
	// Changing the value requires restarting VSCode.
	"locale":"en"
}
```

Do we need more notification than that line right above? If so should this be implemented on save? Or what?

**Comment by ramya-rao-a** [comment]
Honestly, thats the first time I saw that message in the comments. Even though... its right there!

I believe having a notification still helps. Especially because in this case we need a restart (close all windows and start again. In Mac, quit and restart) and not just a reload on the single window.

It should show up after the file is saved if `platform.locale` is not the same as what was just configured. I am not sure if we are firing any events when the locale is changed. If we do, then you can piggy back on that.  If we don't and its not trivial to add one, then I am ok with closing this issue given that the comment has the instruction to restart.
