### ISSUE TITLE
Provide workbench.panel.location "top" option

### ISSUE THREAD

**Issue by bilogic** [microsoft/vscode#50984]
This is with reference to locked issue #2806

**Besides bottom and right, can the panel be placed at the top?**
Let me explain:

New output is appended to the bottom of the output/terminal, aka right at the edge of the display. 
This causes a lot of eye movement between filename tabs, code and new output.

However, if panel is placed on top, code can easily be scrolled so that the part being edited is always around the display's center, with the newest output just right above it.

Thank you.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/37877

**Comment by ika-musuko** [comment]
Hi, I made a PR for this about a month ago. Please take a look when possible. Thank you.

https://github.com/microsoft/vscode/pull/93653

**Comment by edwinshelton** [comment]
Hi! Is there a status update on this feature? Thank you!

**Comment by bilogic** [comment]
@ika-musuko how can i help to pass the PR?

**Comment by szotsaki** [comment]
There's an [open PR](https://github.com/microsoft/vscode/pull/93653) for this feature. If @ika-musuko rebases it, @bpasero, could you please merge it?

**Comment by bilogic** [comment]
@szotsaki there is a more promising PR here https://github.com/microsoft/vscode/pull/207721

**Comment by szotsaki** [comment]
Great, thank you! I hope it gets approved.

For VSCode developers: please, see Yakuake (or Guake) if you'd like to see a complete KDE (or Gnome) program evolved around this very feature.

Unfortunately, I have to work in Windows environment, so this feature would provide the closest implementation of the Linux variants.

**Comment by wisniewski94** [comment]
One of the reasons why it would be good to have is that, in full-screen mode, the input line in a terminal is at the very bottom of the screen. Now, if you work in bed, you most likely have your Mac on your legs/stomach so you need to flex your eyes to the very bottom. And this is something I believe worsens vision.

**Comment by bilogic** [comment]
@wisniewski94 the issue is being looked into at https://github.com/microsoft/vscode/pull/207721

**Comment by benibenj** [comment]
In the newest version of Insiders you are now able to move the panel to the top.
Try it out here: https://code.visualstudio.com/insiders/

**Comment by bilogic** [comment]
cool thanks! is there a timeline when it will be in the stable release?

**Comment by gjsjohnmurray** [comment]
@bilogic based on #220925, early August.

**Comment by abhijit-chikane** [comment]
@benibenj 
does it make sense to reflect this setting in 'Customize Layout' popup as requested [here](https://github.com/microsoft/vscode/issues/222202) ?

**Comment by wisniewski94** [comment]
Thanks so much for shipping this ❤️
