### ISSUE TITLE
Ctrl comment bug

### ISSUE THREAD

**Issue by linkjay** [Microsoft/vscode#50980]
- VSCode Version: 1.23.1
- OS Version: Linux computer 4.16.12-1-ARCH #1 SMP PREEMPT Fri May 25 23:30:31 UTC 2018 x86_64 GNU/Linux

Steps to Reproduce:

1. comment a few lines 
2. select commented lines and non-commented
3. use ctrl-comment and the commented lines get another set of comments added

I can't really tell if this is supposed to be a feature, but I think it should either uncomment or comment all of them instead of just adding another comment marker. This happens on other language profiles too. 

It seems that the ctrl-comment feature just adds the comment thing to wherever your selection box starts and ends. I think it should just manage the comments at the start of a line and sync them all together. So they are all either uncommented or commented at any time.

For stuff like HTML or CSS where they have an end, remove all comments in it and then just have a comment bound at the start and end of the selection box?

Does this issue occur when all extensions are disabled?: Yes

![gif of issue](https://i.linkjay.io/ACVYJD.gif)

**Comment by rcjsuen** [comment]
I think this is intentional. Otherwise, it makes it difficult to comment and then un-comment blocks with both code and comments.

Consider the following case if the editor did not prepend additional `//` characters...

**Original:**
```JavaScript
var x;
// comment
var y;
```
**After Commenting:**
```JavaScript
// var x;
// comment
// var y;
```
**After Un-commenting:**
```JavaScript
var x;
comment
var y;
```
Now I'll have a syntax error on the second line. :(

**Comment by octref** [comment]
@rcjsuen Thanks for the explanation.

Closing as-designed.
