### ISSUE TITLE
Highlight c#6.0 "String Interpolation"

### ISSUE THREAD

**Issue by ahdung** [Microsoft/vscode#50981]
for example:
![_20180602092657](https://user-images.githubusercontent.com/12094247/40869078-86d5ba7e-6647-11e8-92f2-e3deaeffb758.png)

This `{s}` should be Black. Thank you.

**Comment by aeschli** [comment]
This is what I see in the current master matching 1.24 with the default theme:

![image](https://user-images.githubusercontent.com/6461412/40912873-2244dd94-67f3-11e8-9849-ea2d2bf49c69.png)

's' is correcty colored as a variable.

```
var s = "adasds";
Console.WriteLine($"Hello {s}");
```

Please give more information, maybe it's an issue of the theme.

**Comment by ahdung** [comment]
@aeschli I see, i'm using `Light (Visual Studio)` theme, please let the theme highlight too, Thank you.

**Comment by aeschli** [comment]
The `Light (Visual Studio)` theme uses the regular background color for variable references. That's by design.
Use the `Light+` theme if you like to have variables (and method/functions) colorized.
