### ISSUE TITLE
Angular 6 will not compile via the integrated terminal but does in cmd.

### ISSUE THREAD

**Issue by NoEnigmas** [Microsoft/vscode#50989]
If I run an existing Angular 6  CLI version (6.0.2) or a newly created Angular 6 CLI version (6.0.7) using CMD and it compiles and runs but run the same in Visual Studio Code and it fails to compile with the following messages

$ ng serve
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\node_modules\@angular\cli\bin\ng'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

About 10 days ago all was well since then I have made no changes to the code or the operating environment although there was one Windows 10 update. 

I have uninstalled, reinstalled version 1.23.1 upgraded Node.js and npm and rebooted my computer and it still does not compile but CMD does.

**Comment by NoEnigmas** [comment]
After more investigation I find that git bash is the problem. Sorry for any inconvenience.

**Comment by nestorjunior** [comment]
I'm having this problem!
