### ISSUE TITLE
Empty list of FoldingRanges overrides VS Code folding providers

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#50990]
Issue Type: <b>Bug</b>

* Create a python file with the following code:
```python
if True:
    print(1)
```
* VS Code will allow code to be collapsed at the first line
* Install the [python extension from vsix](https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix)
* Code folding now fails

Note: The extension is returning an empty array in the method `FoldingRangeProvider.provideFoldingRanges`

Based on the documentation in [Folding Provider API](https://code.visualstudio.com/updates/v1_23#_folding-provider-api), this shouldn't happen.

**Solution:**
* The python extension needs to return `undefined` as the return value, instead of an empty array `[]`.

VS Code version: Code - Insiders 1.24.0-insider (92754223624dcbe9aca0e5ca3ba8a53808b122b6, 2018-06-01T13:37:15.690Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
gc-virtualdocumentspy|Gra|1.0.1
application-insights|Vis|0.4.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.10
githistory|don|0.4.1
xml|Dot|2.2.0
gitlens|eam|8.3.3
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
githd|hui|1.1.4
docthis|joe|0.7.0
MagicPython|mag|1.0.12
dotenv|mik|1.0.1
extension-manifest-editor|ms-|0.1.5
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.80
debugger-for-chrome|msj|4.5.0
autodocstring|njp|0.2.1
vscode-docker|Pet|0.0.27
python|ms-|2018.5.0-rc
typescript-hero|rbb|2.3.2
vscode-yaml|red|0.0.12
vscode-icons|rob|7.23.0
yo|sam|0.9.3
cython|tcw|0.1.0
jinja|who|0.0.8

</details>

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-python#1853

**Comment by aeschli** [comment]
See the spec at https://github.com/Microsoft/vscode/blob/eb1d9729cd6104019f34b05099e509ee33ef3502/src/vs/vscode.d.ts#L3474
```
* Returns a list of folding ranges or null and undefined if the provider
* does not want to participate or was cancelled.
```

IMO we correctly impement that behaviour.
We only fall back to indentation based indenting if all providers return null or undefined.

Please reopen if you disagree.

**Comment by DonJayamanne** [comment]
I cannot reopen this issue for some reason.

> does not want to participate or was cancelled.

`Participate` does not mean `override`. From what you're telling me, if a list is provided, then the default VSC behavior is overridden. Participation would means something completely different, they should work together.
