### ISSUE TITLE
[folding] Zombie folding regions after deletion

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#50992]
Issue Type: <b>Bug</b>

* Create a python file as follows:
* Install the [python extension from vsix](https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix)
```python
if True:
    print(2)
    print(2)
    """
    Docs
    """
    print(2)
    print(2) 
```
* Code folding is avialable line index 3. (you should be able to collapse the 3 lines, see video)
* Delete the three lines
* Folding marker is still available (when it shouldn't be).
* Note, at this point the extension is returning `undefined` as the return value for the method `FoldingRangeProvider.provideFoldingRanges`

![folding](https://user-images.githubusercontent.com/1948812/40871750-8e8cd690-65f6-11e8-8b48-971a67528b7a.gif)

VS Code version: Code - Insiders 1.24.0-insider (92754223624dcbe9aca0e5ca3ba8a53808b122b6, 2018-06-01T13:37:15.690Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
gc-virtualdocumentspy|Gra|1.0.1
application-insights|Vis|0.4.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.10
githistory|don|0.4.1
xml|Dot|2.2.0
gitlens|eam|8.3.3
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
githd|hui|1.1.4
docthis|joe|0.7.0
MagicPython|mag|1.0.12
dotenv|mik|1.0.1
extension-manifest-editor|ms-|0.1.5
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.80
debugger-for-chrome|msj|4.5.0
autodocstring|njp|0.2.1
vscode-docker|Pet|0.0.27
python|ms-|2018.5.0-rc
typescript-hero|rbb|2.3.2
vscode-yaml|red|0.0.12
vscode-icons|rob|7.23.0
yo|sam|0.9.3
cython|tcw|0.1.0
jinja|who|0.0.8

</details>

**Comment by aeschli** [comment]
@DonJayamanne Sorry for looking into this so late. I'm installed the VSIX but I don't see a folding region on line 4. Setting breakpoints in the foldi9ng code I also don't see a folding range provider registered.
Anything I'm missing?
