### ISSUE TITLE
add to the [Copy] button "Visual Studio Code" (help>info>Copy button)

### ISSUE THREAD

**Issue by sl5net** [Microsoft/vscode#50995]
please add a hint to press Ctrl + c
result of Ctrl + c is different to Copy button
(for e.g. please add the title to the Copy button)

the [Copy] button gives me :

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Datum 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

CTRL-C gives me:

[Window Title]
**Visual Studio Code**

[Main Instruction]
Visual Studio Code

[Content]

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Datum 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

[OK] [Kopieren]

**Comment by sl5net** [comment]
for comparison please see below.
if i hit the copy button into the ide phpstorm.

i think we need that often. if we past into stackoverflow or so. right? thanks

i got this (with title PhpStorm 2018.1):

PhpStorm 2018.1
Build #PS-181.4203.565, built on March 28, 2018
Licensed to Software Lab 5 - Sebastian Lauffer / Sebastian Lauffer
Subscription is active until January 12, 2019
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by octref** [comment]
Think you should just hit the Copy button as #50802 explained. I'm closing this as-designed.
