### ISSUE TITLE
In Markdown language, list of fenced code block does not have syntax highlighting

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode#50993]
- VSCode Version: 1.23.1
- OS Version: Windows 10 64-bit

Steps to Reproduce:

1. Create a new text document;
2. Change the document’s language to Markdown;
3. Copy the following text into the document:
   ````markdown
   ```python
   def f():
       pass
   ```
   
   1. ```python
      def f():
          pass
      ```
   ````
4. You should notice that the second code block doesn’t get syntax highlighting.

Does this issue occur when all extensions are disabled?: Yes

Related: #22185

**Comment by jcphua** [comment]
Have observed the same issue, however I believe the issue relates more generally to the incorrect closure of styles for the first code block, which affects styling of all subsequent content that appears below it:
```
# Correctly styled Heading 1

Correct lorem ipsum

## Correctly styled Heading 2

Correct lorem ipsum

՝՝՝
hello world
՝՝՝

Incorrect lorem ipsum

## Incorrectly styled Heading 2

Incorrect lorem ipsum
```
(backtick characters above have been substituted with ASCII equivalents for demo purposes)

Latest Insider edition currently still afflicted:
![Version: 1.25.0-insider](https://user-images.githubusercontent.com/1219083/41578096-d6f7337c-73d3-11e8-8415-39bf97052437.png)



> Version: 1.25.0-insider
Commit: 7dc9539a421c9c33e57e2ce0b718f183bb44c756
Date: 2018-06-15T05:17:41.405Z
Electron: 2.0.2
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#21

**Comment by mjbvz** [comment]
@jcphua Unrelated issue. I've opened #52509 to track it
