### ISSUE TITLE
⌘ + / (numpad) does not work to comment

### ISSUE THREAD

**Issue by Flynrod** [Microsoft/vscode#50998]
I noticed that on ISO keyboards one could comment code lines using ⌘ + SHIFT + : (which is / with SHIFT) but when I try to comment with the / on my keyboard numpad, it doesn't work.

- VSCode Version: 1.23.1
- OS Version: 10.13.4

Steps to Reproduce:

1. Open any file
2. Select a text zone
3. Run ⌘ + / numpad

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@Flynrod You would need to create a keybinding for that to work:

```
{
	"key": "cmd+numpad_divide",
	"command": "editor.action.commentLine",
	"when": "editorTextFocus && !editorReadonly"
}
```

Numpad keys are treated especially from the rest of the keys and the characters they produce are not taken into consideration when binding default key mappings to the current keyboard layout.
