### ISSUE TITLE
infinite progress, when trying to delete an extension

### ISSUE THREAD

**Issue by jorjik** [Microsoft/vscode#50999]
Issue Type: <b>Bug</b>

when trying to delete an extension, infinite progress is displayed http://SSMaker.ru/8f237a7a/

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.98GB (0.64GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|0.2.2
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.55
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
dotenv|mik|1.0.1
vscode-language-pack-ru|MS-|1.23.0
mssql|ms-|1.3.1
node-debug2|ms-|1.20.3
vscode-icons|rob|7.23.0
php-formatter|Sop|0.2.4
vscode-react-native|vsm|0.6.10

</details>

**Comment by sandy081** [comment]
@jorjik Can you please set the log level to `trace` using command `Set Log Level` and provide us the logs (Shared process and Current window) from Output panel?

**Comment by jorjik** [comment]
win. return none http://SSMaker.ru/2d7dbfe3/

**Comment by sandy081** [comment]
Are there any issues with logging in your VS Code set up?

**Comment by jorjik** [comment]
if we are talking about running the program, then there is no problem with this

2018-06-06 17:30 GMT+03:00, Sandeep Somavarapu <notifications@github.com>:

**Comment by sandy081** [comment]
Can you do following

- Toggle Developer tools
- Toggle Shared Process

and see if there are any errors while uninstalling the extension?

**Comment by jorjik** [comment]
I do not know how to do it - it seems that this problem is only for --
[DEPRECATED] Azure Functions Tools

пт, 8 июн. 2018 г. в 19:19, Sandeep Somavarapu <notifications@github.com>:

**Comment by sandy081** [comment]
@jorjik These are the commands. Press F1 and look for above commands.
