### ISSUE TITLE
Extension code folding provider always breaks default VS Code code folding behavior

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#50991]
Issue Type: <b>Bug</b>

* Create a python file as follows:
```python
if True:
    print(2)
    print(2)
    """
    Docs
    """
    print(2)
    print(2)
```
* Code folding works as expected at the first line
* Install the [python extension from vsix](https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix)
* The folding provider in the python extension returns a single folding range with the following values:
    * Start line index = 3
    * End line index = 5
    * kind = undefined

Now based on the docs [Folding Provider API](https://code.visualstudio.com/updates/v1_23#_folding-provider-api), this shouldn't happen. As the range is neither overlapping nor starting at the same position as that of VS Code.

VS Code version: Code - Insiders 1.24.0-insider (92754223624dcbe9aca0e5ca3ba8a53808b122b6, 2018-06-01T13:37:15.690Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
gc-virtualdocumentspy|Gra|1.0.1
application-insights|Vis|0.4.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.10
githistory|don|0.4.1
xml|Dot|2.2.0
gitlens|eam|8.3.3
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
githd|hui|1.1.4
docthis|joe|0.7.0
MagicPython|mag|1.0.12
dotenv|mik|1.0.1
extension-manifest-editor|ms-|0.1.5
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.80
debugger-for-chrome|msj|4.5.0
autodocstring|njp|0.2.1
vscode-docker|Pet|0.0.27
python|ms-|2018.5.0-rc
typescript-hero|rbb|2.3.2
vscode-yaml|red|0.0.12
vscode-icons|rob|7.23.0
yo|sam|0.9.3
cython|tcw|0.1.0
jinja|who|0.0.8

</details>

**Comment by aeschli** [comment]
The indentation based ranges are only used if there is no contributed folding provider or none of these providers return a result.

-> The python folding provider is expected to provide all ranges, including the one for `if`.

The thinking is that a contributed folding provider is backed by a parser and scanner and will produce better results by just looking at the indentation. Merging the two is not-trivial and can lead to unexpected results.
But I've heard the request to still support indentation based ranges along with provider ranges. I have to think about it more....

**Comment by DonJayamanne** [comment]
> erging the two is not-trivial and can lead to unexpected results.

This behavior is not documented in the API. The docs are confusing. It says that multiple providers can be registered. Your have the exact same problem on that case, i.e. if multiple providers are registered. So how is this any different?

Please update the docs.

> But I've heard the request to still support indentation based ranges along with provider ranges. I have to think about it more....

Please could you point me to this issue?

**Comment by DonJayamanne** [comment]
@aeschli 
Please could you reopen this issue, or I can create another one.

> Merging the two is not-trivial and can lead to unexpected results.

Unfortunately this logic doesn't make sense. If I or someone else were to create a separate folding provider that implemented the exact same logic in VSC for indentation folding, VSC should still have the same problem in merging the two providers! I.e. VSC should not be able to merge the new folding ranges and the one provided by the python extension. I.e. there is absolutely no way for anyone to solve this problem, unless we always have `one` folding provider.

**Comment by aeschli** [comment]
You need to see the indentation based folding as a default strategy. It's not a regular folding provider. It's like the text based completion proposals. They don't show up all the time. 
I don't want to add it as a regular provider, but rather give each language the full control over the folding ranges.

And oh, yes, if I or someone else were to create a separate folding provider that implemented the exact same logic in VSC for indentation folding, we have code that merges the results. It will work nicely if you don't have any overlapping ranges. If there are overlapping ranges, some ranges will be removed according to the strategy described [here](https://github.com/Microsoft/vscode/blob/5065397f9bc6aed49e2d80168b77a76606a40bab/src/vs/vscode.d.ts#L7119).

Think of this
```
if True:
    """
Docs
    """
    print(2)
    print(2)
```
Here the indentation strategy would create a range from 1 to 2, interfering with the [2,4] range from the Python provider but [1,2] win as it has a smaller start index.

I hope I could convince you that you don't want to be in the merging business and also not want to depend on other providers. The best case is when there is just one provider active at a time.

I will add a sentence to the spec to explain that indentation based folding is not a provider.

**Comment by aeschli** [comment]
https://github.com/Microsoft/vscode/issues/47404 is a similar issue

**Comment by DonJayamanne** [comment]
Got it thanks.
