### ISSUE TITLE
Fix add selection above and add selection below hotkey on Ubuntu

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#51]
I'm used to `alt+shift+up` and `alt+shift+down` expanding the selection above and below the current anchor, as far as I can see this is not implemented in core or an extension.

Edit: This is actually implemented and working fine, the hotkey ctrl+alt+up/down just conflicts with the Ubuntu OS hotkey to change workspace.

**Comment by jel-massih** [comment]
Is this different than the current add cursor above/below with `ctrl+alt+up` and `ctrl+alt+down`?

**Comment by pali88** [comment]
Try

**Comment by Tyriar** [comment]
`alt+shift+up` actually conflicts as well, which conflicts on atom's defaults.

**Comment by alexandrudima** [comment]
@Tyriar I only use Linux in a VM. I think for me some keybindings are lost due to the VM runner.

If you run Linux natively, I would love some help to figure out what would be better default keybindings for `editor.action.insertCursorAbove` and `editor.action.insertCursorBelow`:

```
{ "key": "ctrl+meta+up",          "command": "editor.action.insertCursorAbove",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+meta+down",        "command": "editor.action.insertCursorBelow",
                                     "when": "editorTextFocus" },
```

**Comment by Tyriar** [comment]
@alexandrudima I'm used to alt+shift+down as the default for down (as on atom) and I guess I don't use the insert up because alt+shift+up conflicts as well. This is specific to Ubuntu, not sure about other distros. It would seem that we're running out of modifier key combinations. I'll see what Sublime uses by default tomorrow.

**Comment by Tyriar** [comment]
@alexandrudima `alt+shift+down/up` is the default on Atom and Sublime, makes sense to follow suite.

**Comment by alexandrudima** [comment]
I've pushed the following change to the defaults in c96af39 (tried on ubuntu and lubuntu):
* move lines: from `ctrl+down/up` to `alt+down/up` (aligns with default on windows)
* add cursor: from `ctrl+win+down/up` to `shift+alt+down/up` and also `ctrl+shift+down/up`

This frees up `ctrl+up/down` also on linux (it is already free on windows) for a future scroll viewport commands.
