### ISSUE TITLE
Always notification is displayed when opened non-angular project

### ISSUE THREAD

**Issue by bhaskarmac** [Microsoft/vscode#51000]
Always notification is displayed when opened non-angular project

- VSCode Version:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:38.209Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

- OS Version:
Windows 7 Ultimate

Steps to Reproduce:

1. Open any Angular project
2. Now open the non-Angular project folder using "Open recent" from File menu.
3. Observe the notification is displayed as
![restartdialog](https://user-images.githubusercontent.com/4056847/40872384-151f6a32-666b-11e8-9fa7-b6620d412831.PNG)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
@bhaskarmac this seems to be caused by the `vscode-icons` extension, please report this issue there: https://github.com/vscode-icons/vscode-icons

**Comment by bhaskarmac** [comment]
Thank you @bpasero
