### ISSUE TITLE
Poor visual orientation in folders of the workspace

### ISSUE THREAD

**Issue by 10lojzo** [Microsoft/vscode#51003]
In left EXPLORER pane of VSCode, when I add some folders to the workspace, the labels of these folders are of the same font, case and color as their subfolders and thus are poorly recognizable. There is only small indentation which is not enough by my opinion. For example, if I expand several folders and subfolders in the workspace, it is hard to find the particular project and decide which files and subfolders belong to which project. E.g. visual orientation in workspace is harder. For example in Visual Studio there is a bigger indentation and also there is (different) icon in front of the project label to easily distinguish between different projects.

**Comment by octref** [comment]
You can install "Icon Themes" which will give you icons and let you distinguish between projects/files.

https://marketplace.visualstudio.com/search?term=icon%20theme&target=VSCode&category=All%20categories&sortBy=Relevance
