### ISSUE TITLE
Feature Request: Compare editor selection with Clipboard

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode#51009]
Intial issue was referenced [here](https://github.com/Microsoft/vscode/issues/50765) but was closed on the misunderstanding of the issue/feature requested.

I believe it would be very beneficial to be able to compare a-selected-text from Vscode editor panel (any line or specific selected text) to be able to compare it with what exists in clipboard.

As a clarification, this is NOT the same as comparing the clipboard with ALL the file in VSCode!

**Comment by cumminsd** [comment]
This is a very powerful feature that is available in many IDEs. I was trying to compare two functions in the same file this way and couldn't find the option. This is something I did regularly in IntelliJ.

**Comment by ihipop** [comment]
https://marketplace.visualstudio.com/items?itemName=ryu1kn.partial-diff as rerence

**Comment by bpasero** [comment]
I am closing this given very good extension support such as: https://marketplace.visualstudio.com/items?itemName=ryu1kn.partial-diff
