### ISSUE TITLE
Don't Automatically close the details page of the plug-in

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#51005]
Issue Type: <b>Bug</b>

When I open the details page of a plug-in in VSCode, I switch to other functions in the active column (such as opening the resource manager), and VS code automatically closes the details page that has opened the plug-in, but I don't want to close it.

I have disabled all plug-ins, and this will happen.

VS Code version: Code - Insiders 1.24.0-insider (92754223624dcbe9aca0e5ca3ba8a53808b122b6, 2018-06-01T13:43:03.161Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.01GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\ZFu\AppData\Local\Packages\KaliLinux.54290C8133FEE_ey8k8hqnwqnmg\LocalState\rootfs\home\kalizfu\Documents\Projects\c\lsprograms\fork\main6.c|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
dart-code|Dar|2.13.0
flutter|Dar|2.13.0
docs-markdown|doc|0.0.3
gitlens|eam|8.3.3
code-runner|for|0.9.3
vscode-cosmosdb|ms-|0.7.1
vscode-language-pack-zh-hans|MS-|1.24.1
python|ms-|2018.4.0
azure-account|ms-|0.4.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.80
js-atom-grammar|ms-|0.1.14
jscs|ms-|0.1.9
mono-debug|ms-|0.15.8
PowerShell|ms-|1.7.0
typescript-javascript-grammar|ms-|0.0.41
vetur|oct|0.12.3
platformio-ide|pla|0.15.2
java|red|0.26.0
vscode-yaml|red|0.0.12
rust|rus|0.4.4
vscode-arduino|vsc|0.2.15
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.8.0
vscode-react-native|vsm|0.6.10
debug|web|0.22.0

(1 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
@sandy081 Do you recall if this was intentional? Or is it the nature of web views?

**Comment by sandy081** [comment]
@ramya-rao-a I do not know. May be @joaomoreno ?

**Comment by ramya-rao-a** [comment]
@joaomoreno If this was not intentional, then I would add a `help-wanted` label on this issue.

**Comment by joaomoreno** [comment]
This was an intentional change. When extensions started appearing in editor places, people feared that they would overtake the editor history list, so there is some _garbage collecting_ behaviour in there.

I suggest we introduce a setting for this and reverse the default behaviour: extensions should be kept open by default. 👍

**Comment by ramya-rao-a** [comment]
Thanks @joaomoreno!
