### ISSUE TITLE
Allow to restore window size when double click maximized window title

### ISSUE THREAD

**Issue by mattmyne** [Microsoft/vscode#51002]
Double-clicking the title bar in macOS causes the window to stretch to fill the screen (though not actually maximise), but unlike most other macOS app windows it cannot be restored to its previous size by double-clicking it again.

This is rather frustrating if double-clicked by accident (such as when intending to click and drag the window elsewhere). The window has to be manually resized and moved to try and approximate the dimensions you'd previously set by hand.

**Comment by bpasero** [comment]
@mattmyne does it work if you configure `"window.titleBarStyle": "native"`?

**Comment by mattmyne** [comment]
Yes it works as expected then. The appearance suffers as the native title bar colour then contrasts against the dark theme, and the expansion animation is noticeably more "jittery" than the original behaviour, so I believe fixing the default behaviour is still worthwhile.

**Comment by bpasero** [comment]
Needs:

![image](https://user-images.githubusercontent.com/900690/45738316-5b1d6b80-bbf0-11e8-8e07-cc61dc51cabe.png)

In Settings > Dock
