### ISSUE TITLE
Editor's whitespaces default width

### ISSUE THREAD

**Issue by ekyboy** [Microsoft/vscode#51006]
Issue Type: <b>Feature Request</b>

Hi, I know there's an option "editor.letterspacing" to change width in pixels between letters. I wondering if it's possible to adjust the spacewidth of whitespaces. thanks.   

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-41-generic

**Comment by octref** [comment]
There is none. Please provide a valid use case when such setting could be useful.
