### ISSUE TITLE
Setting to always open terminal on the side

### ISSUE THREAD

**Issue by lineus** [Microsoft/vscode#51004]
It would be swell if there was a setting that would determine where new integrated terminal sessions were started. At the moment, every time I open a new window and an integrated terminal it defaults to the bottom. My preference is **always** the side.  

I searched for existing issues, it's entirely possible I missed it if one exists. I also searched for an existing setting, I didn't see one.

Thanks!

**Comment by Tyriar** [comment]
```json
{
  "workbench.panel.defaultLocation": "right"
}
```

**Comment by lineus** [comment]
You know, that seemed like such an obvious option to be missing. I'm glad it already exists. 

**Thank you!**

It might help to add a sentence in the comment above "workbench.panel.defaultLocation": "right" that includes the words terminal debug console output problems, so that other folks who search for terminal like I did will see that panel is a thing.

**Comment by isidorn** [comment]
@lineus thanks for the feedback. Fixed via 7d6e1e4ae6
