### ISSUE TITLE
intelisense does not work shown "any" for everything 

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5101]
- VSCode Version:1.8.2
- OS Version:ubuntu 15.10

Steps to Reproduce:

1. hower a method from an external module 
2. it will show any and control + click etc methods wont work

**Comment by egamma** [comment]
Is this TS or JS? What is an example of an external module? Can you add a snippet please.

In general of no types can be inferred and `any` is shown then it is expected that ctrl+click does not work.

**Comment by NikosEfthias** [comment]
its  a js module  and it was a module that was symlinked to node_modules now i gave absolute path to actual module rather than symlink seems it is working but still does not understand what is __dirname etc.

**Comment by NikosEfthias** [comment]
and aint support class keyword  on bubble  that opens written typeof (my class name)

**Comment by egamma** [comment]
> it is working but still does not understand what is __dirname etc.

To get Intellisense for node or for other node modules you need to add a type definition file, pls see https://github.com/Microsoft/vscode-docs/blob/vnext/docs/languages/javascript.md#typescript-definition-file

**Comment by NikosEfthias** [comment]
i am trying to install commonjs for typings but it says theres no such module so anyway it doesnt work i already installed node through typings

**Comment by egamma** [comment]
- The .d.ts files where installed using `typings --ambient install node`
- create a jsconfig.json

Then you get Intellisense

![image](https://cloud.githubusercontent.com/assets/172399/14462045/860d4dd0-00c5-11e6-89e0-9cc35ea33e40.png)

**Comment by NikosEfthias** [comment]
@egamma  thank you now it works though still it is a bit complicated without help i dont think anybody can get this

**Comment by egamma** [comment]
Good and we want to make this simpler. We work on automatic acquistion of .d.ts files.

**Comment by NikosEfthias** [comment]
great @egamma  thank you for this great ide :)
