### ISSUE TITLE
Linux: Use system-ui for workbench's font

### ISSUE THREAD

**Issue by kushatc** [Microsoft/vscode#51014]
Visual Studio Code's workbench currently uses `-apple-system, BlinkMacSystemFont, Segoe WPC, Segoe UI, HelveticaNeue-Light, Ubuntu, Droid Sans, sans-serif` as a font. But many Linux distributions use different system fonts (for example Open Sans in elementary and Cantarell in Fedora).

Font stack should have [`system-ui`](https://drafts.csswg.org/css-fonts-4/#system-ui-def). `system-ui` always represents default UI font.

**Comment by bpasero** [comment]
We possibly have duplicates for this.

/cc @Tyriar

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10144
