### ISSUE TITLE
View options should show check marks for active options

### ISSUE THREAD

**Issue by Greengecko19** [Microsoft/vscode#51015]
Issue Type: <b>Feature Request</b>

Hello,
For example, if Word Wrap is active, it should have a check mark.  That way you don't need to go check elsewhere if it's active or not.  Thanks!

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/47855
