### ISSUE TITLE
Open configured terminal with Ctrl + Shift + C

### ISSUE THREAD

**Issue by n3rd4i** [Microsoft/vscode#51011]
This [tutorial](https://code.visualstudio.com/docs/editor/integrated-terminal) shows how to open an external terminal. The problem is that the terminal that is opened is the default terminal for the OS?

What will be useful in my opinion is to have possibility to open the terminal that is selected in your configuration:
![image](https://user-images.githubusercontent.com/7346660/40875261-a2e38328-6678-11e8-8cb4-84ef7a170081.png)

After that selection when one presses: `Ctrl+Shift+C` (for Windows).

**Comment by Tyriar** [comment]
Set `terminal.external.windowsExec` to whatever you want ctrl+shift+c to open
