### ISSUE TITLE
1.23.1 Broken Intellisense for jscheck type checking for Javascript

### ISSUE THREAD

**Issue by mflux** [Microsoft/vscode#51024]
- VSCode Version:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:38.209Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

- OS Version:
Windows 10

Steps to Reproduce:

1. Start a project with jsconfig and checkJs flag.
My full jsconfig:

		{
			"compilerOptions": {
				"target": "ES6",
				"lib": ["es2017"],
				"noLib": false,
				"charset": "utf8",
				"module": "es6",
				"checkJs": true
			},
			"include": [
				"typings/**/*",
				"typings/cpcs.d.ts"
			],
			"exclude": [
				"game/node_modules",
				"game/gameview.js",
				"game/gamecore.js",
				"node_modules",
				"**/node_modules/*"
			]
		}

2. Include typings for your project
3. See that VSCode does not check typings with JS at all.

Does this issue occur when all extensions are disabled?: Yes

Prior to updating to this version, checkJs and JS with JSDoc annotations + Typescript .d.ts files will allow type checking with JS.

After updating, this is no longer the case. Intellisense no longer detects typings throughout an open file (all variables are any). Enabling checking js through user settings will cause Intellisense to fail finding the typings.

**Comment by mflux** [comment]
Not sure if this is related but after including "**/*.js",in the include glob pattern the issue seems to be resolved. Possibly undocumented behavior in the updated version?

**Comment by mjbvz** [comment]
Try running the `JavaScript: Go to project configuration` command from a js file in vscode. This should open your `jsonfig.json`

I suspect the issue is that you have only included files under `typings` in the current project. Adding `**/*.js` under include would ensure that all js files as also included in the project (so long as they are not specifically excluded)
