### ISSUE TITLE
Integrated terminal take up the whole window (or independent)

### ISSUE THREAD

**Issue by LujunWeng** [Microsoft/vscode#51029]
Hi,

Is it possible to let the integrated terminal take up the whole window? I really like thevscode's integrated terminal under Windows 10 and often use the vscode just as a terminal. But other areas cannot be closed and it is really uncomfortable. I even thought of taking the integrated terminal out and make it an standalone application. 

Cheers

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34442

I recommend setting up a keybinding for maximizing the panel such as:

```
{ "key": "ctrl+shift+q",     "command": "workbench.action.toggleMaximizedPanel" }
```
