### ISSUE TITLE
Microsoft.VSCode.CPP.Extension.exe always utilizes ~12% CPU

### ISSUE THREAD

**Issue by tomerb** [Microsoft/vscode#51025]
Issue Type: <b>Bug</b>

Updating IntelliSense badge (red flame) stays in status bar for ever.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:38.209Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (5.54GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version

---|---|---
cpptools|ms-|0.17.4

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
