### ISSUE TITLE
Unable to submit an input from the Output Console due to 'cannot edit in read-only editor'

### ISSUE THREAD

**Issue by talhakabakus** [Microsoft/vscode#51021]
- VSCode Version: 1.23.1
- OS Version: 1709

Steps to Reproduce:

1. Install **Code Runner** extension
2. When I try to submit an input through the **Output** console using **Python**

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
As-designed. You need to copy the content to somewhere else to edit it.

**Comment by Dragaan** [comment]
horse manure.  I have been able to run all of my small (I'm learning) scripts/programs and enter input just file until the last time I restarted the program.  Now it will never let me "cannot edit in read only editor" tooltip pops up with keystroke.  This JUST started happening, out of the blue.

**Comment by octref** [comment]
If you are having issues with extensions, file issues for them, such as https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner or https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode.

**Comment by Dragaan** [comment]
to the OP, just go to the user settings and add -  "code-runner.runInTerminal": true

This will just run it from the terminal  but at least you can see it from within vs code.  :|
