### ISSUE TITLE
[Markdonw folding] fails once there are $$ and {} appears in the same line.

### ISSUE THREAD

**Issue by Jacobi-Leo** [Microsoft/vscode#51027]
- VSCode Version: 1.23.1
- OS Version: Linux Mint 18.3 Sylvia

Steps to Reproduce:

1. Enable extension Markdown-All-in-One (ext install yzhang.markdown-all-in-one).
2. Creat a Markdown file test.md pasted below.

```
Test File
=========

Section one
-----------

$$ a^2 + b^2 = c^2 $$ {#eq:triangle}

Section two
-----------

Something...
```
The previous code folds 'Section two' under 'Section one', instead of being parallelly. Once the {} and its content inside is removed, the behavior is correct. 

Does this issue occur when all extensions are disabled?: No; if the extension Markdonw-All-in-One is disabled, the folding behavior is all correct.

**Comment by mjbvz** [comment]
I cannot repo this is in VS Code insiders with no extensions:

![screen shot 2018-06-04 at 10 20 28 am](https://user-images.githubusercontent.com/12821956/40931734-fb84ca46-67e0-11e8-960a-7a2293d12c4a.png)


Please try filing this issue against the Markdonw-All-in-One extension
