### ISSUE TITLE
Markdown: Sticky "Show Source" action

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#51033]
Steps to Reproduce (tried this from master with the grid work included):

1. open some files
2. open a markdown preview
3. move it into the first editor group (provided it opened to the side before)
4. close the markdown preview
5. 🐛 notice how the next active editor gets a "Show Source" action

**Comment by mjbvz** [comment]
Another case:

1. Open markdown file
1. Open preview in same column
1. Close preview

**Bug**
`Markdown: show source` command still visible
