### ISSUE TITLE
Accessibility - VoiceOver incorrectly reads the code in the editor

### ISSUE THREAD

**Issue by adincebic** [microsoft/vscode#51034]
- VSCode Version:  1.23.1
- OS Version: macOS 10.13.4 High Siera

Steps to Reproduce:
1. Turn VoiceOver on and launch VS Code
2. Open an existing file or create a new one and put some content there
3. Try reading the code using up and down arrows

Expected: Voiceover should read each line as you navigate through the text and say "new line" when it encounters an empty line.

Actual: Voice over reads the current line but very often reads the next and previous line together which gets confusing and anoying. Also, VoiceOver does not say "new line" when there is an empty line, instead it reads the previous line.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexandrudima** [comment]
Let's continue tracking in #70033 , where the OP has reached out directly to Chromium.

**Comment by alexandrudima** [comment]
May I also kindly encourage that you subscribe and comment at https://bugs.chromium.org/p/chromium/issues/detail?id=951777
