### ISSUE TITLE
Markdown: "Show Source" does not work in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#51030]
Steps to Reproduce (tried this from master with the grid work included):

1. open one markdown file (nothing else)
2. click on "open preview to side"
3. 🐛 clicking on "show source" does not work

It looks like this check fails: https://github.com/Microsoft/vscode/blob/1a8ea64a04eb12ba3999fdbe5a8a6a50a3c17474/extensions/markdown-language-features/src/commands/showSource.ts#L18

**Comment by mjbvz** [comment]
Fixed by 4f324d1
