### ISSUE TITLE
workbench.action.editor.nextChange/previousChange should center the viewport

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#51031]
I have these keybinding:

```json
{ "key": "alt+f3",           "command": "workbench.action.editor.nextChange", "when": "editorTextFocus" },
{ "key": "shift+alt+f3",     "command": "workbench.action.editor.previousChange", "when": "editorTextFocus" },
```

Currently it doesn't center the viewport like F3, which makes it less nice.

**Comment by joaomoreno** [comment]
You mean you want it to center the viewport _when the editor needs to be scrolled_?

**Comment by Abhijith-S-D** [comment]
I'm interested to work on this as my first issue. Will you point me in the right direction 😊?

**Comment by Tyriar** [comment]
Looks like a PR is already out https://github.com/Microsoft/vscode/pull/51235 🎉
