### ISSUE TITLE
Integrated Terminal Garbled Problem

### ISSUE THREAD

**Issue by xiaolongba** [Microsoft/vscode#51036]
- VSCode Version: 1.23.1
- OS Version:Win7 64bit

> I integrate MSYS2 shell into Visual studio code on Window and it can work well.And then i called "make  menuconfig" command,the terminal Garbled.But if i open the MSYS2 shell directly on the windows desktop and then called "make menuconfig",everything is ok.This puzzles me.

Steps to Reproduce:
1.open the vscode and <code>Ctrl</code>+<code>`</code>to open the MSYS2 shell
![garbled](https://user-images.githubusercontent.com/16135532/40884245-a58db86c-6742-11e8-904f-ecfdd160d48c.gif)

2.open the msys2 shell directly on the windows desktop
![normal](https://user-images.githubusercontent.com/16135532/40884248-a779609a-6742-11e8-8dc0-ffb8df33554c.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

**Comment by xiaolongba** [comment]
so the solution i can find in #45693?

**Comment by Tyriar** [comment]
There is no solution currently, #45693 tracks the many issues related to winpty.

**Comment by xiaolongba** [comment]
all right.Hope the new release can slove this issue.Thanks u so much for help.
