### ISSUE TITLE
Respect other arguments when running with --diff

### ISSUE THREAD

**Issue by MarekLew** [microsoft/vscode#51041]
Issue Type: <b>Bug</b>

If I try open diff in selected workspace then opened two files  but not diff

Reproduce:

1. Create two files in folder:
```
mkdir A
echo a1>A/a.txt
echo a2>A/b.txt
```
2. create ` B.code-workspace` (from command line example)
```
echo '{"folders": [{"path": "A"}],"settings": {}}' >B.code-workspace
```
3a.  compare A/b.txt to A/a.txt from command line in B.code-workspace but not diff
 `code B.code-workspace --diff A/b.txt A/a.txt`
4a. then opened files A/b.txt  and A/a.txt in B.code-workspace

3b. compare A/b.txt to A/a.txt from command line in B.code-workspace (where A/a.txt is opened) 
```
code B.code-workspace
code -r A/a.txt
code A/a.txt --diff A/b.txt A/a.txt
```
4b. then compare `A/a.txt ->  A/b.txt` but not `A/b.txt ->  A/a.txt`
And when I close `A/a.txt` file then I have https://github.com/Microsoft/vscode/issues/51039

It does not matter if I writes `code -r ...` or `code ...`

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-43-generic
                   and on windows 10 
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz (4 x 903)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|3.77GB (0.91GB free)|
|Process Argv|/usr/share/code/code A|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.55
vs-treeview|DaG|2.5.0
vsc-material-theme|Equ|2.1.0
virtual-folders|Gru|0.1.2-b1
taskmarks|Nor|0.6.1
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
code-gnu-global|aus|0.2.2
spellright|ban|2.5.0
npm-intellisense|chr|1.3.0
python-snippets|cst|0.2.0
jshint|dba|0.10.18
vscode-eslint|dba|1.4.10
gitlens|eam|8.3.3
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
LogFileHighlighter|emi|2.4.0
git-project-manager|fel|1.6.1
favorites|kdc|1.4.4
vscode-gist|ken|1.2.0
git-tree-compare|let|1.2.1
cmake-tools-helper|mad|0.2.1
MagicPython|mag|1.0.12
vscode-checkpoints|mic|1.0.1
vscode-clang|mit|0.2.2
quicksnippet|mou|0.0.1
hg|mrc|1.2.3
python|ms-|2018.4.0
cpptools|ms-|0.17.4
vscode-code-outline|pat|0.2.1
annotator|ryu|0.11.0
partial-diff|ryu|1.1.0
guides|spy|0.9.1
python|tht|0.2.3
cmake|twx|0.0.17
cmake-tools|vec|0.11.1
gitflow|vec|1.2.1
local-history|xyz|1.6.2

</details>

Does this issue occur when all extensions are disabled?: Yes

**Comment by MarekLew** [comment]
I think I've found the trail of the problem:
`code A/c.txt --diff A/a.txt`
and 
`code --diff A/c.txt A/a.txt`
and
`code A/c.txt A/a.txt --diff`

Give the same result. This is a parse `--diff`options error

**Comment by MarekLew** [comment]
No this is command line options error.

**Comment by bpasero** [comment]
@MarekLew so are you saying that --diff should only be supported if there is exactly 2 paths following that argument? And if so, what should happen if the arguments order is not correct?

**Comment by MarekLew** [comment]
@bpasero then 'code a --diff c d' compare a to c and open d or "Gate to hell"(I don't have parser in head)

**Comment by bpasero** [comment]
@joaomoreno is our CLI parsing library even supporting to understand the order of arguments?

**Comment by MarekLew** [comment]
Another example:

If I have files "A/a.txt" and "B/a.txt"

---
0. `code A`
1. `code -r --diff A/a.txt B/a.txt A/a.txt` or `code -r --diff A/a.txt B/a.txt B/a.txt`
Open only diff, but not file
2. `code -r --diff A/a.txt B/a.txt A/b.txt` 
Open files "A/a.txt" and "B/a.txt" and new "A/b.txt" but not diff
---
1. `code A` 
2. `code B` 
3. `code -r --diff A/a.txt B/a.txt`
Open diff in A but not in B (ignore -r)
---
1. `code B` 
2. `code A` 
3. `code -r --diff B/a.txt A/a.txt`
Open diff in B but not in A (ignore -r)
---
1. `code B` 
2. `code A` 
3. `code -r B/a.txt`
Open `B/a.txt` in B but not in A (ignore -r {Force to open a file or folder in the last active window})

**Comment by joaomoreno** [comment]
@bpasero [`--diff` is currently a boolean option](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/argv.ts#L40). It doesn't expect any arguments after itself. There's a check for two files specifically: https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/paths.ts#L29

**Comment by MarekLew** [comment]
It's not necessary support other argument but `-r` must not by ignored. The rest can be avoided somehow.
