### ISSUE TITLE
Shortcut for editing editor.fontSize

### ISSUE THREAD

**Issue by EgoAleSum** [Microsoft/vscode#51044]
At a conference with a customer. They are suggesting that CTRL/CMD and +/- should be configurable to change `editor.fontSize` rather than `window.zoomLevel`. It doesn't look like it's possible to do it at the moment, as there are commands for `workbench.action.zoomIn` and `workbench.action.zoomOut`, but not for font size.

@AgtLucas

**Comment by EgoAleSum** [comment]
+ @AgtLucas

**Comment by octref** [comment]
This will be doable if VS Code has commands for increasing/decreasing font size, which you can then bind to your own keybindings.

**Comment by AgtLucas** [comment]
@octref 👍 

FYI; Atom, Sublime and others has this feature.

**Comment by alexandrudima** [comment]
Funny timing. They were just released. See https://code.visualstudio.com/updates/v1_24#_font-zoom-commands

**Comment by AgtLucas** [comment]
Thanks!
