### ISSUE TITLE
Debugging Python loading indefinitely 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5104]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Clone https://github.com/simpleai-team/simpleai.git
2. Install Python extension
3. Start debugging

Actual:
No debug menu comes up to continue/restart/stop etc. and there is no way to stop debugging.

Can move to https://github.com/DonJayamanne/pythonVSCode if needed.

**Comment by egamma** [comment]
This issue was moved to DonJayamanne/pythonVSCode#72
