### ISSUE TITLE
autoClosingPairs are too aggressive

### ISSUE THREAD

**Issue by kAlvaro** [microsoft/vscode#51047]
Issue Type: <b>Feature Request</b>

No matter the context, as soon as you type `/**` you immediately get `/**𝖨 */` (where `𝖨` is the cursor). If you didn't intend to start a docblock you need to remove the straneous ` */`. Tested in JavaScript and PHP, with and without extensions.

I'd appreciate these two enhancements:

- Expand to docblock only after `/**<space>` or `/**<enter>`.
- Make the overall feature context sensitive (you probably don't want a docblock inside a string literal or a comment).

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
Each language can configure its `autoClosingPairs`, so please file separate issues against each language.
IMO we want a way to configure this in the user settings and also have a way to quickly remove the closing brackets/tokens without removing the initially type characters

**Comment by kAlvaro** [comment]
I've filed issues for the individual languages. I've also realised that in certain contexts (such as flow control structures or string literals) you get a pop-up suggestion but it doesn't get expanded automatically (sorry for not being precise about that).

**Comment by roblourens** [comment]
> Make the overall feature context sensitive (you probably don't want a docblock inside a string literal or a comment).

That should already be the case for strings, not for comments apparently (maybe we should add that one)

@aeschli If I type `(` and get `()`, then press backspace, the autoclosing `)` is removed too. Maybe the same should happen for `/**` too?

> IMO we want a way to configure this in the user settings

Sorry, configure what?

**Comment by aeschli** [comment]
> Maybe the same should happen for /** too?
Good idea, that would help!

> Sorry, configure what?
Currently, only extensions can define the language configuratuon. 
But any users want to custmize these or even turn off the autoClosingPairs.
It would be great if we would also allow somthing like that
```
"[html]": {
    "editor.autoClosingPairs": [
         { "open": "{", "close": "}"},
         { "open": "'", "close": "'" },
         { "open": "<!--", "close": "-->", "notIn": [ "comment", "string" ]}
     ]
}
```
That's also very interesting for the other language configurations such as folding: #36002

**Comment by roblourens** [comment]
Oh got it. Yes that would be cool.

**Comment by roblourens** [comment]
I realized that if I set /** to not autoclose in "comment", then it never autocloses at all. I guess because once you type `/*` you are in a comment scope, so `/**` won't autoclose.

Is it possible to support that? Should I file another feature request for it?

It was requested to use `/** ` (with a space) but I'm not sure about that. I'd rather let users configure that with this setting if they prefer. So is there anything PHP specific that we can do right now?

**Comment by kAlvaro** [comment]
> It was requested to use `/** ` (with a space) but I'm not sure about that.

&hellip; or <kbd>Enter</kbd>. That's how it works in JetBrains IDEs, Eclipse, NetBeans IDE and Komodo IDE (though the triggered feature in those tools is actually a full docblock creation, together with params and return).

**Comment by aeschli** [comment]
The request to make autoClosingPairs configurable is #38352.
#50087 is similar request

**Comment by kAlvaro** [comment]
As workaround, I've created a custom code snippet:

    "/**/": {
        "prefix": "/**/",
        "body": "/**/",
        "description": "Workaround to be able to type /**/"
    }

I only need to be careful and type <kbd>/</kbd> + <kbd>Enter</kbd> (or <kbd>/</kbd> and <kbd>Tag</kbd>) but once you get used to it it's actually a time saver.

**Comment by kAlvaro** [comment]
A better workaround (though it implies fiddling with application files and needs to be reapplied on each upgrade) can be found at [Proposal: Ability not to auto-close comments](https://github.com/Microsoft/vscode/issues/1966#issuecomment-479404534).

**Comment by alexandrudima** [comment]
Let's track in #38352
