### ISSUE TITLE
command line parse error (not positional parse)

### ISSUE THREAD

**Issue by MarekLew** [Microsoft/vscode#51045]
I think I've found the trail of the problem:
`code A/c.txt --diff A/a.txt`
and
`code --diff A/c.txt A/a.txt`
and
`code A/c.txt A/a.txt --diff`

Give the same result. This is a parse `--diff` options error

---

```
code A
code --add B
```
and 

```
code A
code B --add
```
Give the same result.

**Comment by MarekLew** [comment]
from https://github.com/Microsoft/vscode/issues/51041

**Comment by MarekLew** [comment]
and https://github.com/Microsoft/vscode/issues/50470 it is.

**Comment by octref** [comment]
Let's track in #51041 then.
