### ISSUE TITLE
Autocomplete object properties with (smart) trailing comma

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#51049]
imagine I have:

```js
export default {
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify('production'),
    }),
    resolve({
      jsnext: true
    }),
    commonjs // <-- currently typing here
    babel(),
  ],
  watch: {
    exclude: ['node_modules/**'],
  },
};
```

When typing `(` it'll autocomplete with the closing `)`, why not inserting also a comma `,` just after? in order to make things valid?

Same related feature (but only for json configs): https://github.com/Microsoft/vscode/issues/40753

**Comment by octref** [comment]
You could be on the last line of config, like
```
{
  foo: bar()
}
```
Now inserting comma might annoy people who don't like trailing commas.

**Comment by caub** [comment]
@octref yes, but depending on last property or not, it'd insert that comma

**Comment by caub** [comment]
Yes ok, I don't know how the implementation is, but it could have used an AST (snapshots when the code is valid), then it can know in which context and position you're typing, and append the comma if in an object  not in last position. But maybe you're doing something more regex based

**Comment by octref** [comment]
This whole thing is regex based. Analyzing the AST is hard given:
- You need to do that for each typing
- You don't know the shapes of AST of some languages
- Your parser need to generate a valid AST and do analysis on **invalid** code which is what the state of the source code would be 90% of the time
