### ISSUE TITLE
Unable update insiders to the latest version

### ISSUE THREAD

**Issue by Stone-Zeng** [Microsoft/vscode#51043]
It seems that VS Code will check and download the update automatically. However, if I don't install it after several days, it will not be up-to-date and when I install it, VS Code will remind me to install another update.

- VSCode Version: v1.24.0-insiders
- OS Version: Windows 10 1803 (17134.48)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Stone-Zeng** [comment]
It seems to be duplicated with #44685, but for insider version, which means the update is much more frequent.

**Comment by octref** [comment]
Yes this is tracked in #44685.
