### ISSUE TITLE
Incorrect JavaScript highlight when block comment is next to the regexp

### ISSUE THREAD

**Issue by YinTianliang** [Microsoft/vscode#51050]
- VSCode Version: 1.23.1 d0182c3417d225529c6d5ad24b7572815d0de9ac x64
- OS Version:  Manjaro 17.1.10 Hakoila

Steps to Reproduce:

1. Lauch with `code --disable-extensions`
2. Create an empty file with Ctrl + N
3. Enter `var foo = /bar//* test */`
4. Change language mode to JavaScript with Ctrl + K M

Does this issue occur when all extensions are disabled?: Yes

expected to see
![image](https://user-images.githubusercontent.com/17017672/40888517-e33a5056-678a-11e8-9ec4-79ee3b4d580f.png)

actually saw
![image](https://user-images.githubusercontent.com/17017672/40888418-5a1e4044-6789-11e8-8d55-1932169432ce.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#623
