### ISSUE TITLE
Integrated Terminal doesn't open on project root (windows / babun / cygwin / zsh)

### ISSUE THREAD

**Issue by vincentmathis** [Microsoft/vscode#51052]
- VSCode Version: 1.23.1
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. Install Babun Terminal
2. Set integrated terminal to zsh

```
"terminal.integrated.shell.windows": "C:\\Users\\xyz\\.babun\\cygwin\\bin\\zsh.exe",
"terminal.integrated.cwd": "${workspaceFolder}",
```

When opening the terminal it is just empty. Removing the terminal.integrated.cwd line and the shell opens in it's home directory ~

**Comment by Tyriar** [comment]
You probably need this workaround https://github.com/Microsoft/vscode/issues/14977
