### ISSUE TITLE
Download website seems down

### ISSUE THREAD

**Issue by ftw-microsoft** [Microsoft/vscode#51055]
https://vscode-update.azurewebsites.net/latest/win32-x64/* is timing out.

**Comment by octref** [comment]
Both https://vscode-update.azurewebsites.net/latest/win32-x64/insider and https://vscode-update.azurewebsites.net/latest/win32-x64/stable are working fine for me. Are you using any VPN?

**Comment by ftw-microsoft** [comment]
Yes. The Microsoft one.... 8) Disconnected and indeed the download then worked.
