### ISSUE TITLE
Ubuntu 18:  No menu

### ISSUE THREAD

**Issue by DigiAngel** [Microsoft/vscode#51056]
Looks like the menu after going to Ubuntu 18 with Gnome is gone leaving only a Quit menu item:
![screenshot from 2018-06-03 12-39-36](https://user-images.githubusercontent.com/947191/40889888-4a8659e0-672b-11e8-9396-cc22ab61f295.png)

**Comment by Tyriar** [comment]
Isn't the vscode menu still attached to the window in Ubuntu 18.04?

**Comment by DigiAngel** [comment]
It is...once you enable it :D  Had to use the command palette to find the show menu.  Guess I can close this out.  Thank you.
