### ISSUE TITLE
Feature Request: Roam extension installs

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vscode#51065]
Similar to how in Visual Studio 2017, you can sign-in to roam (some) extension installs so you don't have issues if you switch around machines.

To avoid a heavy sign in experience, maybe something as simple as a Gist or URL, listing the extension names and versions that VS Code would understand and restore when switching machines.

**Comment by nschonni** [comment]
Related issues are #42994 and #15442, so feel free to close if you think it's a dupe.

**Comment by sandy081** [comment]
It is a duplicate. Thanks for listing.
