### ISSUE TITLE
Cannot open source file "vcruntime.h"

### ISSUE THREAD

**Issue by Ayanjit** [Microsoft/vscode#51062]
Issue Type: <b>Bug</b>

1. Install MinGW.
2. Create a C file.
3. Write #include <stdio.h>
4. Gives curly green line under #include <stdio.h>
5. Moving cursor to curly lines gives this error.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (55.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
xml|Dot|2.2.0
gc-excelviewer|Gra|2.0.21
python|ms-|2018.4.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
JavaScriptSnippets|xab|1.6.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
