### ISSUE TITLE
Change dock icon for OSX

### ISSUE THREAD

**Issue by heihachi88** [microsoft/vscode#51063]
![image](https://user-images.githubusercontent.com/5739191/40901209-06fc2f62-67f1-11e8-9794-aabc9a1da574.png)

Currently it uses non-osx style icon, i suggest to you use a circle shape or a square with rounded edges, so it would fit macos style.

**Comment by H-C-H** [comment]
The current icon actually follows the macOS icon style very closely. Here is a screenshot of the vscode icon together with several native macOS app icons in my dock:

![dock icons](https://user-images.githubusercontent.com/31404215/40916741-21f3b212-6801-11e8-9eb2-617504d07ae4.png)

You can read more about Apple's official Human Interface Guidelines [here](https://developer.apple.com/macos/human-interface-guidelines/icons-and-images/app-icon/), which says among other things:
> Avoid using the rounded rectangle shape that people associate with iOS app icons.

**Comment by heihachi88** [comment]
Well, i just read OSX guidelines you provided, thanks. I just felt like it's not native because i have all rounded icons:

![image](https://user-images.githubusercontent.com/5739191/40917008-9a9cdd8e-6823-11e8-890a-a85fe58bf1b7.png)

**Comment by bpasero** [comment]
Closing as designed via https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#updated-visual-studio-code-icon
