### ISSUE TITLE
Debugging statusbar new variables to theme it

### ISSUE THREAD

**Issue by carolitascl** [Microsoft/vscode#51060]
Before:
"statusBar.debuggingBackground"
"statusBar.debuggingForeground"

After:
"statusBar.debuggingBackground"
"statusBar.debuggingForeground"
"statusBarItem.debuggingActiveBackground" ( New )
"statusBarItem.debuggingHoverBackground" ( New )

**Comment by isidorn** [comment]
This is a fair feature request.
Let's keep it open and if it generats more user trackation we would be open to a PR that address this
code pointer https://github.com/Microsoft/vscode/blob/4cacd3277c37599356c3ff225d02d166852c7153/src/vs/workbench/parts/debug/browser/statusbarColorProvider.ts#L18
fyi @aeschli
