### ISSUE TITLE
Display support  for keyboard shortcuts series

### ISSUE THREAD

**Issue by KoalaBear84** [Microsoft/vscode#51076]
Issue Type: <b>Bug</b>

Add support of displaying keyboard shortcuts with series like in Visual Studio.

I almost reported a bug on SQL Operations Studio for the keyboard shortcut of Zen mode not working. But it was just wrongly displayed as "CTRL + K Z" instead of "CTRL + K, Z" as Visual Studio does which makes sense. As CTRL + K, CTRL + Z does not work.

Visual Studio (perfect):
![image](https://user-images.githubusercontent.com/5886900/40912495-03563e10-67f2-11e8-99b2-724017936b8c.png)

Visual Studio Code:
![image](https://user-images.githubusercontent.com/5886900/40912514-149ea4e6-67f2-11e8-92b5-838c7c17bc17.png)
![image](https://user-images.githubusercontent.com/5886900/40913653-8bc3f4b0-67f5-11e8-92ab-09a5d630373e.png)

SQL Operations Studio:
![image](https://user-images.githubusercontent.com/5886900/40912526-1c0d4e44-67f2-11e8-9c87-6d98b5160579.png)

Please implement this in Visual Studio Code so that it will be the same in SQL Operations Studio, as it uses the same engine as Visual Studio Code.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:38.209Z)
OS version: Windows_NT ia32 10.0.14393

**Comment by sbatten** [comment]
resolved with new custom menu implementation

**Comment by chrmarti** [comment]
I don't see this change. Neither in native nor custom menus.

**Comment by bpasero** [comment]
I think the way it is displayed currently is fine:

![image](https://user-images.githubusercontent.com/900690/42674770-559c6e36-8671-11e8-92b0-ba3308c3868c.png)

**Comment by KoalaBear84** [comment]
It is not. Maybe only in this scenario, but not in the example I sent. I'm hoping you also use Visual Studio?

**Comment by bpasero** [comment]
@KoalaBear84 we do not use Visual Studio, but Visual Studio Code and we decided to present chords like that.
