### ISSUE TITLE
debugger always fails to "restore"

### ISSUE THREAD

**Issue by ciel** [Microsoft/vscode#5107]
- VSCode Version:
`0.10.11`

- OS Version:
Windows 10x64
Steps to Reproduce:

- .NET CLI version
````
.NET Command Line Tools (1.0.0-rc2-002306)

Product Information:
 Version:     1.0.0-rc2-002306
 Commit Sha:  0747d31f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
````

1. Install Visual Studio Code
2. Install the [dot net cli](https://github.com/dotnet/cli)
3. Open a command line (`cmd` or `PowerShell`)
4. Navigate to a folder
5. Type `dot net new` and hit `ENTER` to create a new project.
6. Right click inside the folder (`Windows Explorer`) and select `Open with VS Code`

The `OUTPUT` window appears and spouts off a lot of attempts to pull in files, and then yields an error; it is different each time for me.

![sample](http://i.xomf.com/rpbvf.jpg)

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#169
