### ISSUE TITLE
Issue with npm 'ttys' library in 'Debug' mode

### ISSUE THREAD

**Issue by nagapavan** [Microsoft/vscode#51070]
- VSCode Version: 1.23.1
- OS Version: Mac OSX 10.13.4

Steps to Reproduce:

1. Use require("ttys") module in imports list
2. start from Debug console

Does this issue occur when all extensions are disabled?: Yes

> Error: ENOENT, no such file or directory '/dev/tty'

Happens only through "debug" mode, normal CLI works fine.

**Comment by weinand** [comment]
The VS Code debug console is not a tty. So it is expected that the "tty" modules cannot find the "/dev/tty" device.

The fix is to set the "console" attribute of your launch config to "integratedTerminal".

**Comment by nagapavan** [comment]
Thanks @weinand
