### ISSUE TITLE
after update to vscode 1.23.1, failed to attach debug 

### ISSUE THREAD

**Issue by chongchai** [Microsoft/vscode#51075]
- VSCode Version: 1.23.1
- OS Version: windows 7
- Extension: C/C++ 0.17.3  

Steps to Reproduce:

1. I use this launch config to debug a c++ project.
```
        {
            "name": "debug test_demo",
            "type": "cppdbg",
            "request": "launch",
            "program": "/usr/${env:USERNAME}/test/test_demo",
            "cwd": "/usr/${env:USERNAME}/test",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "ssh.exe",
                "pipeArgs": [
                    "${env:SSH_HOST}"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/usr/${env:USERNAME}/test" : "${workspaceRoot}"
            }
        },
        {
            "name": "attach test_demo",
            "type": "cppdbg",
            "request": "attach",
            "program": "/usr/${env:USERNAME}/test/test_demo",
            "processId": "${command:pickRemoteProcess}",
            "MIMode": "gdb",
            "miDebuggerPath": "/path/to/gdb",
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "ssh.exe",
                "pipeArgs": [
                    "${env:SSH_HOST}"
                    //"root@xx.xxx.xxx.xxx"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/usr/${env:USERNAME}/test" : "${workspaceRoot}"
            }
        }
```

2. `debug test_demo` is successful and `attach test_demo` is failed. The vscode failed to attch with error `could not resolve hostname ${env:SSH_HOST}: hostname nor servname provided, or not known`.

3.  if I use the `root@xx.xxx.xxx.xxx` instead of `${env:SSH_HOST}` in the `pipArgs`. It's **successful** to start.

4. I have set the SSH_HOST to be root@xx,xxx.xxx.xxx in the environment. And this attach config is successful in the older vscode version like vscode 1.21.1

**Comment by weinand** [comment]
Please file against C++ extension

**Comment by chongchai** [comment]
@weinand  I don't think it is a bug for the c++ extension. Because code and extension is same except that vscode update from 1.21.1 to 1.23.1

**Comment by pieandcakes** [comment]
@weinand The problem is that the environment variable isn't being resolved. this should be happening before we get the launch.json from VS Code. For some reason an update broke this. We don't resolve environment variables in our code.

**Comment by weinand** [comment]
@pieandcakes are all environment variables unresolved when the launch configuration reaches the DA?

**Comment by pieandcakes** [comment]
It looks like program is resolved but not the other ones used in other properties.

**Comment by weinand** [comment]
@pieandcakes do you see this in (the just released) VS Code 1.24 too?

Could you replace the failing "${env:SSH_HOST}" by an environment variable that always exists, e.g. "HOME":
```
${env:HOME}
```
Is this substituted correctly?

**Comment by pieandcakes** [comment]
Looks like it works for me on 1.24. @chongchai can you try your scenario on 1.24?

**Comment by chongchai** [comment]
@pieandcakes  I have taken tests on 1.22.2, 1.23.1 and 1.24.0. 
The result is that version 1.22.2 achieves success while 1.23.1 and 1.24.0 get fail.

Strange to me is that task `debug test_demo`  and `attach test_demo`  use same environment variable 'SSH_HOST' but get the result  `debug test_demo` is successful and `attach test_demo` is failed.  Is there any difference about the environment variable resolution between these two tasks?

**Comment by weinand** [comment]
@chongchai variable resolution is identical. 

Are all environment variables unresolved or is it only "${env:SSH_HOST}"?

Could you replace the failing "${env:SSH_HOST}" by an environment variable that always exists, e.g. "HOME":
```
"pipeArgs": [
    "${env:HOME}"
],
```
Is this substituted correctly?

**Comment by chongchai** [comment]
@weinand  I replace `SSH_HOST` with `HOME`, it still gets error

```
ssh: Could not resolve hostname ${env:HOME}: hostname nor servname provided, or not known
Command failed: "ssh.exe" "${env:HOME}" "bash -c 'uname && if [ $(uname) == "Linux" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) == "Darwin" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi'"
ssh: Could not resolve hostname ${env:HOME}: hostname nor servname provided, or not known
```

So I think all the environment variables is unresolved in the 'pipArgs'. 

ps:   
The environment variable resolution in other keys like 'program' or 'sourceFileMap' is ok on vscode 1.24.0

**Comment by weinand** [comment]
@chongchai '${program}' or '${sourceFileMap}' are **not** environment variables!

I'm only interested in variables that start with `env:` e.g. `${env:USERNAME}`.

Is `${env:USERNAME}` resolved correctly?

**Comment by chongchai** [comment]
@weinand Yes, ${env:USERNAME} is resolved correctly. 

I didn't say '${program}' is environment variable. What I mean is env variable resolution  in 'program'  section (in launch.json). 
I'm sorry to mislead you for my mistake.

**Comment by weinand** [comment]
@chongchai thanks a lot for the clarification.

I would like to understand whether the problem is specific to `${env:SSH_HOST}` or whether it is specific to the location where the env var is used.

Could you replace the `${env:USERNAME}` in "program" by `${env:SSH_HOST}`?
(yes, it does not make sense to use it there, but I just want to know whether it is resolved correctly).

**Comment by weinand** [comment]
@chongchai does it make a difference if you remove the `//"root@xx.xxx.xxx.xxx"` from the "attach" launch config?

**Comment by chongchai** [comment]
@weinand  sorry to reply late. 

> I would like to understand whether the problem is specific to ${env:SSH_HOST} or whether it is specific to the location where the env var is used.
> 
> Could you replace the ${env:USERNAME} in "program" by ${env:SSH_HOST}?
> (yes, it does not make sense to use it there, but I just want to know whether it is resolved correctly).

I replace the ${env:USERNAME} in "program" by ${env:SSH_HOST}. It's successful to resolve the 'SSH_HOST'.


  
> @chongchai does it make a difference if you remove the comment //"root@xx.xxx.xxx.xxx" from the "attach" launch config?

remove comment doesn't make any  difference

**Comment by chongchai** [comment]
@weinand I debug the source code and believe to find the problem code line is here.

https://github.com/Microsoft/vscode/blob/d0182c3417d225529c6d5ad24b7572815d0de9ac/src/vs/workbench/services/configurationResolver/electron-browser/configurationResolverService.ts#L148

I print out the variable in that line : 
`commandId` is `extension.pickRemoteNativeProcess`
`configuration` is 
```
        {
            "name": "attach test_demo",
            "type": "cppdbg",
            "request": "attach",
            "program": "/usr/${env:USERNAME}/test/test_demo",
            "processId": "${command:pickRemoteProcess}",
            "MIMode": "gdb",
            "miDebuggerPath": "/path/to/gdb",
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "ssh.exe",
                "pipeArgs": [
                    "${env:SSH_HOST}"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/usr/${env:USERNAME}/test" : "${workspaceRoot}"
            }
        }
```
So environment variables in `configuration` is not resolved here which causes the problem.

Hope you will check and fix it soon. Thank you.

**Comment by weinand** [comment]
@chongchai thanks a lot for your investigation!

When running the "attach test_demo" configuration, are you seeing a process picker?
And are you able to select a process?

**Comment by weinand** [comment]
@pieandcakes after some more debugging and with the help of @chongchai, I think I understand the problem now.

The command variable `${command:pickRemoteProcess}` uses the feature that the enclosing debug configuration is passed to `pickRemoteProcess` command so that the command code can extract the `pipeTransport` attributes (which probably are necessary to establish the remote connection).

The code is relying on an unspecified feature of variable resolution that non-command variables (e.g. `${env:SSH_HOST})` are already resolved when the debug config is passed to the `pickRemoteProcess` command.

The old implementation of variable substitution was doing everything in one pass so it could very well be that `${env:SSH_HOST}` got resolved before `${command:pickRemoteProcess}`. But there were no guarantees.

One or two releases ago we made variable substitution more deterministic by using a two-pass process: first we resolve all commands, then we resolve all variables. This seems to have broken the assumption used in `${command:pickRemoteProcess}`.

To fix this, I will keep the two passes but reverse them: first all non-command variables are resolved and then the command variables.

Please try this in the next Insiders.

BTW, I noticed in the `"sourceFileMap"` attribute that you are using variables in dictionary keys as well. Since this was not supported in VS Code, you probably did the substitution in your extension.
As of VS Code 1.24 we now substitute variables in keys as well, so you might want to consider to remove your substitution code. See https://code.visualstudio.com/updates/v1_24#_intellisense-for-predefined-variables

**Comment by chongchai** [comment]
@weinand  When your next Insiders comes, I will have a try.

```
When running the "attach test_demo" configuration, are you seeing a process picker?
And are you able to select a process?
```

No, before selecting a process it will pop a failed alert box.

```
BTW, I noticed in the "sourceFileMap" attribute that you are using variables in dictionary keys as well. Since this was not supported in VS Code, you probably did the substitution in your extension.
As of VS Code 1.24 we now substitute variables in keys as well, so you might want to consider to remove your substitution code. See https://code.visualstudio.com/updates/v1_24#_intellisense-for-predefined-variables
```
Yeah, I use a script to substitute that in sourceFileMap in old vscode version. Now it's redundant. (^.^)

**Comment by pieandcakes** [comment]
@weinand Thanks! We've been telling users to update their `sourceFileMap`s to not have environment variables so its good to know we can have them switch back now. 

I'll take a look at the next Insiders build (from today?) to see if it works.

**Comment by weinand** [comment]
@pieandcakes @chongchai today's Insiders has the fix.

**Comment by pieandcakes** [comment]
@weinand Thanks! I'll take a look

**Comment by chongchai** [comment]
@weinand I have tested in the latest insider. It' ok now. Thank you!

**Comment by weinand** [comment]
@chongchai great, thanks for verifying this.
