### ISSUE TITLE
Copy/select folded line does not copy entire line

### ISSUE THREAD

**Issue by schperplata** [Microsoft/vscode#51083]
Issue Type: <b>Bug</b>

- enable code folding
- write long line, larger than screen width so text is folded
- go to the start of this line and press shift+end (select all line)
- logically, all characters in line should be selected (including folded line)

Since not all characters are selected, copying such line leaves previously folded characters in newly created line, which is very unefficient - in order to copy whole line, you must combine copy/paste procedure.

It is OK if you manually select all lines (including folded ones) and copy/paste.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.87GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0
cpptools|ms-|0.17.4

</details>

**Comment by aeschli** [comment]
To select the line including all folded lines, you have to select the full line until the start of the next line.
So it
- place cursor at the beginning of the line that contains the fold marker
- Shift + Down

Please reopen if I misunderstood your request.

**Comment by schperplata** [comment]
Of course I know how I can select multiple lines - my point is this:
Since you can have opened terminal on the right side and explorer/search panel on the left side, and in some cases splitted editor with multiple tabs, line can be folded multiple times. I know this is an extreme example, but I sometimes manage to get just in such situations, where I need to quickly copy a line while searching multiple documents. 

As folding works now, if file screen is really narrow and line is folded multiple times, I must carefully copy all folded lines - instead just copy whole line with **shift + end**.  

I think that if folded line is selected to the end, editor should select the last character just like if my screen was 3km wide and all _one-line-python-program_  will be copied. :)

**Comment by schperplata** [comment]
Of course I know how I can select multiple lines - my point is this:
Since you can have opened terminal on the right side and explorer/search
panel on the left side, and in some cases splitted editor with multiple
tabs, line can be folded multiple times. I know this is an extreme example,
but I sometimes manage to get just in such situations, where I need to
quickly copy a line while searching multiple documents.

As folding works now, if file screen is really narrow and line is folded
multiple times, I must carefully copy all folded lines - instead just copy
whole line with *shift + end.*

I think that if folded line is selected to the end, editor should select
the last character just like if my screen was 3km wide and all
*one-line-python-program * will be copied. :)

**Comment by aeschli** [comment]
We just don't count the folded lines to the first line. The folding placeholder is after the line.
That's why you need to select until the next visible line to copy everything in between.

I take your suggestion, but currently, we have no plans to change the behavior.

**Comment by aeschli** [comment]
I use #51232 for your request.

**Comment by schperplata** [comment]
Good, I agree it is more of a different perspective than wrong behaviour. I
will just select multiple lines and the "problem" is solved.

Thank you.
