### ISSUE TITLE
"Rename Symbol" with hyphens takes only part of the symbol as default value

### ISSUE THREAD

**Issue by christianvoigt** [Microsoft/vscode#51084]
Some languages allow symbols to contain hyphens (my-symbol). Let's say my extension provides support for renaming symbols like "my-symbol". Selecting "Rename Symbol" in VS Code if the cursor is after "m" of "my-symbol" will open a text input with only "my" in it. The default value should be "my-symbol" instead.

This is not affected by the "editor.wordSeparators" setting and cannot be changed by extensions providing support for languages with hyphenated symbols.

**Comment by KamasamaK** [comment]
Can you please state on what language (extension) this occurs and some example code which reproduces this issue?

This should be resolved by the language's `wordPattern` or if necessary by the `RenameProvider.prepareRename`.

**Comment by christianvoigt** [comment]
Thank you for the quick help! I simply did not find the `wordPattern` configuration option. Could you please add documentation for this option to https://code.visualstudio.com/docs/extensionAPI/language-support?

This issue was basically a duplicate of https://github.com/Microsoft/vscode/issues/32438#issuecomment-322242789
which also provides the solution for html-like languages.

Adding it to the `language-configuration.json` did not work (as in https://github.com/Microsoft/vscode/issues/42649), but using `vscode.languages.setLanguageConfiguration` does.

**Comment by KamasamaK** [comment]
Agreed on the lack of documentation, which should be under [contributes.languages](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages) once it works properly. It also appears to be missing `indentationRules`.

**Comment by alexandrudima** [comment]
Documented with https://github.com/Microsoft/vscode-docs/commit/314d3588c7fea83fbe1966a4e47a6316d1d9e36a
