### ISSUE TITLE
Make alt+click (add cursor) work with the right-alt modifier key

### ISSUE THREAD

**Issue by bobanum** [Microsoft/vscode#51089]
For the left handed of the world.
right-alt + up and others work fine, but we cannot add a new cursor.

Thanks

**Comment by alexandrudima** [comment]
@bobanum Do you perhaps use a specific keyboard layout where the right hand side `Alt` is actually `AltGr` ? What OS are you using ?

**Comment by alexandrudima** [comment]
@bobanum You can set `"editor.multiCursorModifier": "ctrlCmd"` to have ctrl+click be the addition of cursors. 

Did you configure your Windows 10 machine to have a specific keyboard layout? Is Right Alt + clicking not working for you also when you attach a different physical keyboard to the laptop ?
