### ISSUE TITLE
Built-in CoffeeScript extension doesn't highlight ES2015 module syntax

### ISSUE THREAD

**Issue by jdemilledt** [Microsoft/vscode#51086]
- VSCode Version: 1.23.1
- OS Version: Arch Linux - no real version

Steps to Reproduce:

1. Use ES2015 module syntax in CoffeeScript

Does this issue occur when all extensions are disabled?: This is an issue with a built-in extension

Expected: When using the [ES2015 module syntax in CoffeeScript](https://coffeescript.org/#modules), imports and exports are highlighted with colors  
Actual behavior: All text for ES2015 imports/exports is white

**Comment by aeschli** [comment]
This issue was moved to atom/language-coffee-script#167

**Comment by aeschli** [comment]
This is the sample:
```
import m from "mitrhil"
import { Toolbar, Drawer, List, ListTile, IconButton, ToolbarTitle } from "poluthene-mithril"
import { MenuIcon } from "./assets/icons.coffee"
import { routeIs } from "./util.coffee"
```
and this is how it looks with the Dark+ default theme:
![image](https://user-images.githubusercontent.com/6461412/41059674-7d94a572-69cd-11e8-8e5d-6d6b4912e157.png)

IMO this is likely a problem with the theme you are using. Which theme is this?

**Comment by misolori** [comment]
@jdemilledt can you try this again with all extensions disabled? I'm not able to repro this issue. Thanks!

![image](https://user-images.githubusercontent.com/35271042/45404029-21f26380-b612-11e8-8ec9-d2db3b2e1470.png)

**Comment by aeschli** [comment]
Closing due to lack of information available Please reopen when you have a sample.
