### ISSUE TITLE
How to get an accurate heap snapshot of extension host?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51085]
I'm investigating a memory leak in my extension. I can somewhat force high memory usage by running my completion provider a lot of times in a loop, however I'm struggling to use the dev tools to actually inspect what's using the memory.

Here you can see my memory usage is almost 2GB, yet if I take a Heap Snapshot of "Main" in the dev tools, it only reports 60MB.

Am I looking in the wrong place?

![screen shot 2018-06-04 at 3 03 43 pm](https://user-images.githubusercontent.com/1078012/40921978-d6446b2e-6808-11e8-8812-3898e8c8d67c.png)

**Comment by DanTup** [comment]
I found this in the console:

> [Extension Host] debugger inspector at %cDebugger listening on port 22299.
> Warning: This is an experimental feature and could change at any time.
> To start debugging, open the following URL in Chrome:
>     chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:22299/a964d77c-3aab-4e58-8412-42b08dd545d2

However, opening that link gives me a message saying the websocket disconnected.

**Comment by DanTup** [comment]
I found the CPU profiling option in the list of running extensions and tried getting a profile (I'm not sure CPU profile will help me, but I thought it was worth a shot). I collected a 4.5MB file, but when I open it in Chrome's Performance view, it doesn't seem to show anything at all:

![screen shot 2018-06-04 at 3 30 41 pm](https://user-images.githubusercontent.com/1078012/40923305-65ce5e32-680c-11e8-9865-e0ff3bf6c463.png)

**Comment by DanTup** [comment]
Aha, so the cpu profile issue is that I was loading it in the wrong place, this is covered here: https://github.com/Microsoft/vscode/wiki/Performance-Issues

It'd still probably help to get a heap snapshot though. I'm expecting a lot of allocations (there are a lot of items coming back in completion), but I'm trying to figure out if they're being held on to.

**Comment by aeschli** [comment]
When you start VSCode in dev mode (`scripts/code.sh`) all processes will be started in debug mode. You should see a message in the VSCode dev tools console which port the extension host was started with.

Once the extension host is up in debug mode is up, you can open the dev tools of any Chrome browser window and connect to it to do memory profiling.

**Comment by DanTup** [comment]
@aeschli Is this different to this one?

> [Extension Host] debugger inspector at %cDebugger listening on port 22299.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:22299/a964d77c-3aab-4e58-8412-42b08dd545d2

I already tried that but it just seems to disconnect immediately. I've not run VS Code in "dev mode" before (only opening my extension project and hitting F5); does this mean I have to run it from source?

**Comment by aeschli** [comment]
Yes, that's the one and I just tried and it worked. I'm not sure if there can only be one connection a time, so try without using the Running Extensions view?

**Comment by DanTup** [comment]
@aeschli Same thing, but I do have the main VS Code instance connected to it, so I'm guessing that's the issue. I guess I can't do this while running in the dev extension host? I'll see if I can make it work in normal Code (it just means if I need to add debug code, I'll have to build vsix's and installed them on each change). I'll report back...

**Comment by DanTup** [comment]
Ok, that worked - running `code --inspect-plugins=9333 .` then I can connect the Chrome dev tools. Thanks!
