### ISSUE TITLE
Outline feature not debouncing requests to symbolProvider API

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#51096]
Issue Type: <b>Bug</b>

Extension - Python Extension

I've noticed that VS Code isn't debouncing requests to the symbol Provider API when the outline panel is visible.

For instance when typing in the editor window I can see VSC is requesting the symbols (for every character typed) & this feels unnecessary.

Is it upto the extension to throttle the requests. Yes I understand a cancellation token is available (**however this doesn't seem to be cancelled either**), however when it comes to updating the UI (`outline view`) I would have assumed we'd be debouncing/throttling requests, **as its pointless to update the UI for every character**.

VS Code version: Code - Insiders 1.24.0-insider (92754223624dcbe9aca0e5ca3ba8a53808b122b6, 2018-06-01T13:37:15.690Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.16GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1163548|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.10
githistory|don|0.4.1
gitlens|eam|8.3.3
tslint|eg2|1.0.30
debugger-for-chrome|msj|4.5.0
python|ms-|2018.5.0-rc
vscode-icons|rob|7.23.0

</details>

**Comment by jrieken** [comment]
> For instance when typing in the editor window I can see VSC is requesting the symbols (for every character typed) & this feels unnecessary.

Should not be, the debounce rate is set to 150ms. See: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/outline/electron-browser/outlinePanel.ts#L123

**Comment by jrieken** [comment]
Yeah, it seems that only the very first request is debounced and then something bad happens... This is a good find.

**Comment by jrieken** [comment]
D'oh, it actually only cancels a pending request when changing the editor, not when typing much. Might be candidate-worthy.

**Comment by DonJayamanne** [comment]
It doesn't seem to debounce it, we have a timeout, but that only adds a delay, we don't seem to be cancelling the previous/pending timers. Also, we aren't making use of a cancellation token when making a request.

**Comment by DonJayamanne** [comment]
Hope we can get it into the release, this outline view hammers the Python language server with too many requests and seems to have cause intellisense to stop working for one user.
Thanks.

**Comment by jrieken** [comment]
I have cherry-picked this one onto `release/1.24`

**Comment by jrieken** [comment]
With my fix I have not only made the debouncing work, I have also increased the rate to 350ms (from 150ms). That should give extensions more breathing room.

**Comment by DonJayamanne** [comment]
@jrieken Shouldn't we be using a cancellation token (which then gets cancelled for subsequent requests for outline)? From what I could tell the cancellation tokens were not getting cancelled.
Without that, the language server will still continue processing previous requests unnecessarily! So, if the language server takes more than 350ms to come back with a response, we'll have the language server processing all requests that keep getting queued and sent to it.

**Comment by patrys** [comment]
Would VSCode consider implementing clamping for provider APIs? Like if several calls (possibly from different extensions) happen before a result is available just give them all the same promise?

**Comment by jrieken** [comment]
@DonJayamanne Yeah, I have pushed another change to properly wire up cancellation. Tho, that change has unfortunately missed the release train.

**Comment by chrmarti** [comment]
Verified in release branch by code inspection.
