### ISSUE TITLE
After Visual Studio Code update I am not able to clean, package the SPFx solution

### ISSUE THREAD

**Issue by ymihir** [Microsoft/vscode#51092]
I have updated my visual studio code to 1.23.1 (i don't know previous version)
After this update I am not able to clean my SPFx project. 
When I execute `gulp clean` then it is showing me below error: ENOTEMPTY: directory not empty, rmdir 'E:\Practice\SharePoint\SPFx\Extensions2\HeaderFooter\temp\deploy'
When I run `gulp package-solution --build` then it is giving EPERM: operation not permitted, open 'E:\Practice\SharePoint\SPFx\Extensions2\HeaderFooter\temp\deploy\8ec0897a-3435-49ff-a26a-b2298331caa8.json'

First time it is successfully able to build. 
When I restart my machine and try to clean the solution then it is working. 
What could be possible reason for this?
How I can switch back to earlier version of Visual Studio code?
![cleanerror](https://user-images.githubusercontent.com/7568187/40929070-3375460a-6841-11e8-8809-aff4dc0ac34b.PNG)

**Comment by aeschli** [comment]
If you close VSCode and run the `gulp clean` command, does it work then?

Are you using any extensions related to SPFx?
