### ISSUE TITLE
Black bar appears in terminal "empty rows" when its resized

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#51094]
Issue Type: <b>Bug</b>

- Run `tsc --watch`
- Terminal split

![image](https://user-images.githubusercontent.com/4033249/40930262-05faa5d6-67dc-11e8-928f-c1bccebd35f5.png)

VS Code version: Code - Insiders 1.24.0-insider (92754223624dcbe9aca0e5ca3ba8a53808b122b6, 2018-06-01T13:37:15.690Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1364301|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
tslint|eg2|1.0.30
vsc-material-theme|Equ|2.1.0
prettier-vscode|esb|1.4.0
theme-monokai-pro-vscode|mon|1.1.6
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.5.0
vetur|oct|0.12.3
vscode-proun|oct|0.0.1
polacode|pnp|0.2.2
vscode-sort-json|ric|1.11.0
vscode-csstree|sme|0.7.0
language-stylus|sys|1.9.2
vim|vsc|0.12.0

(2 theme extensions excluded)

</details>

**Comment by octref** [comment]
The shadowy scorllbar persists even after closing split terminal.

![image](https://user-images.githubusercontent.com/4033249/40930376-67f2cbb0-67dc-11e8-92af-f78bcb001197.png)

**Comment by chrmarti** [comment]
Removing from May milestone after checking with @Tyriar.

**Comment by bgw** [comment]
:confused: :scream: Given the artifacts that's manifesting with, this looks like it might be an electron/chromium bug, and not an xterm.js bug.

**Comment by Tyriar** [comment]
@bgw yes this is the canvas renderer. My first impression was it's a Chromium thing but it looks like the black columns are lining up with the terminal columns which makes me think it's our bug.

**Comment by Tyriar** [comment]
Updating to latest xterm.js doesn't appear to fix this.

**Comment by Tyriar** [comment]
May be related to https://github.com/Microsoft/vscode/issues/51602

**Comment by Tyriar** [comment]
This is looking more and more like a Chromium bug. If I change this line to be `#FF0000`, I do not get the bars. changing it to `#888888` however and I do:

<img width="216" alt="screen shot 2018-06-12 at 1 01 46 pm" src="https://user-images.githubusercontent.com/2193314/41286723-c888c67c-6e40-11e8-9c4d-b1a3b1dc204b.png">
<img width="114" alt="screen shot 2018-06-12 at 1 02 09 pm" src="https://user-images.githubusercontent.com/2193314/41286742-d5647954-6e40-11e8-8caf-0402eed2f105.png">

**Comment by Tyriar** [comment]
Moving to June as it appears to be a Chrome issue and it's less impact than I first thought; it only impacts "null" rows. This does not happen when the viewport has been filled (you see a flicker but it goes away the next frame).

**Comment by bgw** [comment]
@Tyriar, what was the workaround for this?

**Comment by Tyriar** [comment]
@bgw the workaround didn't fix it, I tried to use clearRect in TextRenderLayer.onGridChanged which seemed to work on macOS, but didn't on other platforms https://github.com/Microsoft/vscode/issues/51749#issuecomment-396869595

**Comment by Tyriar** [comment]
Can't repro this out of sources anymore 😕

**Comment by octref** [comment]
I'm on e585e4bf008a50e5b1f4fde71cf6d255e25381bf

![glitch](https://user-images.githubusercontent.com/4033249/41698451-4f6725ec-74d3-11e8-838f-31c288833dec.gif)

**Comment by Tyriar** [comment]
Yeah I see it in insiders, no running out of sources though 😕

**Comment by Tyriar** [comment]
I've also seen this happen:

<img width="381" alt="screen shot 2018-06-26 at 12 56 41 pm" src="https://user-images.githubusercontent.com/2193314/41935960-7935568e-7940-11e8-8eb6-7a8a579e7d6e.png">

**Comment by Tyriar** [comment]
Something similar can also happen in the color picker:

![image](https://user-images.githubusercontent.com/2193314/41936040-aeeca3ae-7940-11e8-91af-578bb4c18922.png)

**Comment by Tyriar** [comment]
I think this one is fixed in Electron 3

**Comment by Tyriar** [comment]
This is also fixed by the webgl renderer I just build https://github.com/xtermjs/xterm.js/pull/1790, not sure if we would ship that before Electron 3 though.

**Comment by bpasero** [comment]
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/
