### ISSUE TITLE
Why is the width of full-width and half-width spaces the same?

### ISSUE THREAD

**Issue by kylin30** [Microsoft/vscode#51090]
Issue Type: <b>Bug</b>

my font family is nsimsun.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|Memory (System)|15.84GB (8.94GB free)|
|Process Argv|D:\Work\winscp\VSCode\Code.exe D:\MirServerSF|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-verdandi|be5|1.8.1
theme-monokai-pro-vscode|mon|1.1.6
python|ms-|2018.4.0
material-icon-theme|PKi|3.5.0
vscode-icons|rob|7.23.0
code-settings-sync|Sha|2.9.2
omnipascal|Wos|0.15.0
file-size|zh9|0.1.3

(4 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Can you add a screenshot that shows the problem?

**Comment by kylin30** [comment]
font family : NSimSun
![1](https://user-images.githubusercontent.com/2984908/41003886-8ac8c63e-694a-11e8-8721-1c8d561bb5b7.png)
![2](https://user-images.githubusercontent.com/2984908/41003896-9051c8a8-694a-11e8-8a04-79c4c61f985e.png)

font family : default
![3](https://user-images.githubusercontent.com/2984908/41003956-cfe04616-694a-11e8-84d2-fc3553f65b73.png)

**Comment by alexandrudima** [comment]
Font rendering is implemented by Chromium and respects the font itself.

i.e. the font owns this decision.
