### ISSUE TITLE
window.restoreFullscreen not working

### ISSUE THREAD

**Issue by vinibudd** [Microsoft/vscode#51099]
- VSCode Version: 1.23.1
- OS Version: Windows 10 Home 64bit

![sem titulo](https://user-images.githubusercontent.com/24849260/40932476-d4f226ca-6804-11e8-8039-da71ea759017.png)

**Comment by bpasero** [comment]
@vinibudd what is not working?

**Comment by vinibudd** [comment]
The open full screen function

**Comment by bpasero** [comment]
Can you explain?

**Comment by vinibudd** [comment]
The problem was solved in build 1.24.0
