### ISSUE TITLE
Code workspace crashes if attempt to open with Code Insiders

### ISSUE THREAD

**Issue by mfour-merickson** [Microsoft/vscode#51097]
- VSCode Version:

1.24.0-insider
92754223624dcbe9aca0e5ca3ba8a53808b122b6
x64

- OS Version:

MacOS 10.12.6

Steps to Reproduce:

1. Create a workspace using VSCode
2. Attempt to open the workspace using VSCode Insiders
3. After selecting workspace file and clicking `Open` beach ball spins and am required to Force Quit

If I create a workspace using Insiders and attempt to open it, all works fine.

Does this issue occur when all extensions are disabled?: Yes/No

No

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by mfour-merickson** [comment]
@bpasero Well, it seems the latest Insides release (just updated this morning) no longer crashes...
