### ISSUE TITLE
Loading long strings while debugging is clunky

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5109]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Following #4952 
2. Create a string with at least 10,000 characters
3. Start debugging 
4. Hover over the variable in the debug window

![longstringdebugging](https://cloud.githubusercontent.com/assets/12900364/14398817/f740df4e-fd9b-11e5-89a4-49130c4666f9.gif)

There is briefly a white box filled with nothing even though it takes a bit of time to load anyway. It should probably not show the box until the text is ready to be shown.

**Comment by isidorn** [comment]
This is just the way that electron renders hover on windows since this is the native hover, not our custom VSCode one.
This also works nicely on Mac, and probably on linux.

Closing as can not fix, since this is electron behavior

**Comment by isidorn** [comment]
We also introduced a 5000 character limit in the hover, so I believe this should behave better now

**Comment by vsccarl** [comment]
The loading time is better but now sometimes it seems to flash or load multiple times while the cursor is still hovered over it (causing the flashing). ![longstringdebuggingupdate](https://cloud.githubusercontent.com/assets/12900364/14925148/ce1d7d1a-0dfa-11e6-8d5b-542fb837038e.gif)

**Comment by isidorn** [comment]
We have introduced a limit of 1024 which should make this experience nicer now
