### ISSUE TITLE
Diffs are very slow

### ISSUE THREAD

**Issue by jreina** [Microsoft/vscode#51093]
Issue Type: <b>Bug</b>

Click the `Source Control` tab, and click a modified file to generate a diff. Diffs have historically generated very quickly, and now they take several seconds to generate. Sometimes I will double-click a modified file in the source control pane, click back to the `Explorer` pane, start working in a file, and the diff I requested will show up after several (10-20) seconds.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (16.37GB free)|
|Process Argv| |
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-node-readme|ben|3.0.2
bracket-pair-colorizer|Coe|1.0.55
vscode-eslint|dba|1.4.10
prettier-vscode|esb|1.4.0
flow-for-vscode|flo|0.8.1
todo-tree|Gru|0.0.57
vscode-mocha-sidebar|mat|0.19.0
dotenv|mik|1.0.1
mssql|ms-|1.3.1
cpptools|ms-|0.17.4
code-settings-sync|Sha|2.9.2
code-spell-checker|str|1.6.10

</details>

**Comment by jreina** [comment]
This is a duplicate of #48742, however this issue is still prevalent. 

I am working on JavaScript files without a `jsconfig` file in the project root.

Also, the source control pane shows `There are no active source control providers.` for 30-60 seconds after opening VS Code.

**Comment by joaomoreno** [comment]
Other people have filed similar issues lately: #50182

Can you update to the latest git version and check whether it still reproduces?

**Comment by jreina** [comment]
After updating to `git version 2.17.1.windows.2` I cannot reproduce the issue.

**Comment by joaomoreno** [comment]
Awesomesauce.
