### ISSUE TITLE
Have a max-width for in-product rendering

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#51108]
Give release notes a max-width. Otherwise in fullscreen they look gigantic:

![image](https://user-images.githubusercontent.com/4033249/40944606-43a91920-680a-11e8-8f81-7bd54547fa52.png)

**Comment by mjbvz** [comment]
Spoke with @gregvanl about this and he was generally not in favor of it. We have since downscaled those images so that they do not look so out of place on huge monitors
