### ISSUE TITLE
Recommended badge on disabled extensions should have a different color/opacity

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#51106]
The first 2 extensions are recommended below with the second one disabled. But the recommendation badge appears the same for both.

![image](https://user-images.githubusercontent.com/16890566/40940228-ff45320e-67fb-11e8-86b9-4b8cc1765c97.png)

**Comment by patrys** [comment]
How about removing the "recommended" badge from already installed extensions? It's not actionable (I've already installed these) and is visually distracting.

**Comment by ramya-rao-a** [comment]
@patrys That is under discussion in #40881. Please provide your thoughts there.

**Comment by JacksonKearl** [comment]
Resolved in #51367.
