### ISSUE TITLE
Ctrl+Shft+G does not open the source control sidebar on Windows.

### ISSUE THREAD

**Issue by GollyJer** [Microsoft/vscode#51107]
![2018-06-04_16h40_12](https://user-images.githubusercontent.com/689204/40940481-f4f88e4e-6815-11e8-853a-f3bf24a71791.png)

I can't get to the Source Control sidebar with keyboard commands.

**Comment by dougireton** [comment]
@GollyJer does this repo with no extensions, e.g. run `code --disable-extensions`?

The CodeLens extension recently overwrote `CTRL+SHIFT+G` so that now you have to hit `CTRL+SHIFT+G, G` with that extension installed.

**Comment by GollyJer** [comment]
@dougireton Uhg... should know better than to report something without disabling extensions first.

That was it.  Thanks!
