### ISSUE TITLE
When Debug a unsaved file, the popup is confusing.

### ISSUE THREAD

**Issue by slayerxj** [Microsoft/vscode#51114]
Issue Type: <b>Bug</b>

When "Debug" a unsaved file,
The popup is:
        '${file}' can not be resolved. Please open an editor.

But this information is not intuitional for user to recognize that this is caused by the file is not saved and have no extension.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (4.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
cpptools|ms-|0.16.1

</details>

**Comment by isidorn** [comment]
Closing as will not fix. More details here https://github.com/Microsoft/vscode/issues/19415
This is only happening when you have an untitled file
If you have a file with changes, the changes will be saved and you can niecly debug
