### ISSUE TITLE
open gulp and CPU fire 95%

### ISSUE THREAD

**Issue by smile-xy** [Microsoft/vscode#51115]
I'm learning to use gulp. When I open the folder(D:\myProject\music)the gulp file inside, CPU burned to 95%.I don't know why, so I have attached code and plug-ins. --- Through Baidu translation
_CPU stopped burning when I was ready to submit._

- `
var gulp = require('gulp');
var imagemin = require('gulp-imagemin');
var htmlClean = require('gulp-htmlclean');
var newer = require('gulp-newer');
var folder = {
    src: './src/',
    build: './build/'
};
gulp.task('img', function () {
    gulp.src(folder.src + 'img/*')
        .pipe(newer(folder.build + 'img'))
        .pipe(imagemin())
        .pipe(gulp.dest(folder.build + 'img'))
});
gulp.task('html', function () {
    gulp.src(folder.src + 'html/*')
        .pipe(htmlClean())
        .pipe(gulp.dest(folder.build + 'html'))
});
// @ts-ignore
gulp.task('default', ['html', 'image']);`

- `{
  "name": "music",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "music",
    "html5",
    "javascript"
  ],
  "author": "2018xy",
  "license": "MIT",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-htmlclean": "^2.7.22",
    "gulp-imagemin": "^4.1.0",
    "gulp-newer": "^1.4.0"
  },
  "dependencies": {
    "jquery": "^3.3.1"
  }
}
`
- The plug-in in use
vscode-file-peek | abi | 1.0.1
html-snippets | abu | 0.2.1
aessoft-class-autocomplete | AES | 0.1.0
vscode-javascript-snippet-pack | aka | 0.1.5
Bookmarks | ale | 0.19.1
color-info | bie | 0.5.0
path-intellisense | chr | 1.4.2
bracket-pair-colorizer | Coe | 1.0.55
vscode-eslint | dba | 1.4.12
jquerysnippets | don | 0.0.1
vscode-html-css | ecm | 0.2.0
php-intellisense | fel | 2.3.2
auto-close-tag | for | 0.5.6
auto-rename-tag | for | 0.0.15
webpack-snippets | gog | 0.0.4
webpack | jer | 2.1.0
code-beautifier | mic | 2.0.3
vscode-language-pack-zh-hans | MS- | 1.23.5
vscode-css-peek | pra | 2.1.0
filenamecomplete | qin | 0.0.3
vscode-icons | rob | 7.23.0
code-spell-checker | str | 1.6.10
open-in-browser | tec | 1.1.0
bootstrap4-vscode | the | 4.1.1
vscode-todo-highlight | way | 0.5.12
bootstrap-3-snippets | wcw | 0.1.0
JavaScriptSnippets | xab | 1.6.0

**Comment by smile-xy** [comment]
When I turn off vscode and open again, CPU burns to 95% again, and it seems that I can't open this file because it's okay to open the other files and open the two JS files when the workspace is not here.

**Comment by dbaeumer** [comment]
@smile-xy can you please provide a GitHub repository I can clone that demos this.

And does it also happen if you start VS Code from a terminal with all extensions disabled (e.g. `code --disable-extensions`)

**Comment by smile-xy** [comment]
It may be related to plug-in, and has just built a new gulp project. After git packed several times, it burned CPU again. Disable all plug-ins to restart and temporarily finds no problem.Maybe I've changed a couple of plug-ins instead.TAT

**Comment by smile-xy** [comment]
After my testing, under the environment of vscode editor gulp, whether this plug-in is loaded directly affects CPU combustion.
I don't know why, but it's just like a game, loading and burning, not loading and nothing.

- CSS Peek | pranaygp.vscode-css-peek | Pranay Prakash

- HTML CSS Support | ecmel.vscode-html-css | ecmel

**Comment by dbaeumer** [comment]
@smile-xy are you saying that when you disabled the above two extension everything works fine. If so I would contact the extension owners. In addition when it happens can you run `code --status` in a terminal and provide the output here. It contains information about which process is burning CPU.

**Comment by smile-xy** [comment]
@dbaeumer There is no problem with installation now. If this happens again, I will provide the output.Thank you very much for your help

**Comment by smile-xy** [comment]
@dbaeumer 
**five rg.exe fire 95%**
Version:          Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS Version:       Windows_NT x64 10.0.16299
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  15.86GB (8.83GB free)
VM:               0%
Screen Reader:    no
Process Argv:     D:\Program Files\Microsoft VS Code\Code.exe
GPU Status:       2d_canvas:                    enabled
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  vpx_decode:                   enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0      118   16788  code main
    0      283    1596     window (gulpfile.js - gulpclass - Visual Studio Code)
    0       36    3612       searchService
   14       22    5792         "d:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg" --files --hidden --case-sensitive -g **/*.scss -g !/undefined -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --follow -- .
    0       10   12648           console-window-host (Windows internal process)
   21       22    7188         "d:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg" --files --hidden --case-sensitive -g **/*.css -g !/undefined -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --follow -- .
    0       10    5944           console-window-host (Windows internal process)
    8       23    7996         "d:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg" --files --hidden --case-sensitive -g **/*.css -g !/undefined -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --follow -- .
    0       10   15972           console-window-host (Windows internal process)
   14       23   13664         "d:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg" --files --hidden --case-sensitive -g **/*.less -g !/undefined -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --follow -- .
    0       10   15388           console-window-host (Windows internal process)
    9       22   14012         "d:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg" --files --hidden --case-sensitive -g **/*.scss -g !/undefined -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --follow -- .
    0       10    7784           console-window-host (Windows internal process)
    0       11   12220       watcherService
    0       10    1204         console-window-host (Windows internal process)
    0       34   15484       terminal
    0        6   15904         winpty-process
    0       65    9652           C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0        4    3900             C:\Windows\system32\cmd.exe /c ""d:\Program Files\Microsoft VS Code\bin\code.cmd" -stat"
    0       34    1200               electron_node cli.js
    0       54    3428                 "d:\Program Files\Microsoft VS Code\Code.exe" -stat
    1       87   16428                   gpu-process
    0       10   11556           console-window-host (Windows internal process)
    0       85   15780       extensionHost
    0       91    3564         electron_node server.js
    0      144    9012         electron_node electronForkStart.js tsserver.js
    0       49   15580           electron_node typingsInstaller.js tsserver.js typesMap.js
    0      245    8984     gpu-process
    0       69   12660     shared-process
Workspace Stats:
|  Window (gulpfile.js - gulpclass - Visual Studio Code)
|    Folder (gulpclass): 9 files
|      File types: js(4) html(2) css(1) json(1) less(1)
|      Conf files: gulp.js(1) package.json(1)

**Comment by smile-xy** [comment]
![img](https://user-images.githubusercontent.com/37609247/41029191-a69a8e48-69ad-11e8-9616-edb2bb725666.png)

**Comment by roblourens** [comment]
Both of those extensions start several searches using findFiles. Please file bugs on those extensions. They could be much more efficient, for example by excluding 'node_modules'.
