### ISSUE TITLE
[ejs] <%=  %> in .ejs file marked as wrong but correct

### ISSUE THREAD

**Issue by omginput** [microsoft/vscode#51118]
Issue Type: <b>Bug</b>

Code marks <%= %> and <% %> expressions in .ejs files as wrong and marks them red with the hint "[js] Expression expected". But this should be allowed in ejs files. Brackets for example has no problems with it.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.82GB (4.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.1.0
vscode-language-pack-de|MS-|1.23.3

</details>

**Comment by aeschli** [comment]
We open ejs files with the HTML language mode without understanding the ejs syntax.
Ideally, there will be a real EJS exension that can properly handle the EJS syntax. From our side we have no support planned.

As a workaround, you can disable the scripts validation for HTML:
`"html.validate.scripts": false`

**Comment by omginput** [comment]
Ok, thank you. Would be nice if there was support in future.

**Comment by aeschli** [comment]
Proper EJS support would ideally come from an extension. The HTML language support does't know of the many templating languages, and it really shouldn't.
We have #49210 to come up with a simpler way of using the HTML mode for templating languages.

**Comment by AlejandroBryan** [comment]
thanks a lot, guys I did fix the problem. @aeschli

**Comment by Chenzo** [comment]
@AlejandroBryan - wait. HOW!? I have this same problem.

**Comment by avichal-neweradeveloper** [comment]
I got the solution everyone it is as simple as downloading the extension ".ejs" it is ejs support for vs code. It adds ejs as a new language,  just check the image below if you are still not sure
https://user-images.githubusercontent.com/65894534/114372026-bcd2c600-9b9e-11eb-8f5b-9d897446ea5e.png

Have an amazing day ahead !!

**Comment by zengxiaoluan** [comment]
> I got the solution everyone it is as simple as downloading the extension ".ejs" it is ejs support for vs code. It adds ejs as a new language, just check the image below if you are still not sure
> https://user-images.githubusercontent.com/65894534/114372026-bcd2c600-9b9e-11eb-8f5b-9d897446ea5e.png
> 
> Have an amazing day ahead !!

This method can't validate js error in script tag.
