### ISSUE TITLE
Git Diff: Grabled contents if file is large

### ISSUE THREAD

**Issue by blackzky** [Microsoft/vscode#51126]
Issue Type: <b>Bug</b>

1. Create a text file that has a file size of 1.22 MB
2. Commit new file
3. Update file
4. Use git diff
=> [NG] The text in the left side is garbled

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.10586

**Comment by joaomoreno** [comment]
What encoding is the file?
