### ISSUE TITLE
Allow extension to read input from integrated terminal api

### ISSUE THREAD

**Issue by bvicinay** [Microsoft/vscode#51123]
The Terminal Extensión API allows an extensión to send a command to the terminal. However, it does not work the other way round. An extensión **cannot read a users' terminal input**. This would be very useful for debugging extensions.

**Comment by bvicinay** [comment]
Is there a way (workaround) for an extensión to read what a user types into a terminal?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/46192
