### ISSUE TITLE
autoGuessEncoding for windows-1257 is not working

### ISSUE THREAD

**Issue by KarlisVe** [Microsoft/vscode#51125]
- VSCode Version: 1.20.0
- OS Version: Windows 7 Pro SP1

Steps to Reproduce:

1. Set VSCode setting "files.autoGuessEncoding": true,
2. Create new file -> Reopen with encoding Baltic (Windows-1257)  -> Save
3. Open File -> check for encoding

Does this issue occur when all extensions are disabled?: Yes

Example of settings & file:
![encodingvsauto](https://user-images.githubusercontent.com/20325506/40961318-e4aad232-68aa-11e8-9578-87c61656e174.PNG)
[win1257vs.txt](https://github.com/Microsoft/vscode/files/2071226/win1257vs.txt)

**Comment by bpasero** [comment]
There is no way the library can detect the encoding from an empty file. It needs to have some content to scan for. I am closing this, as this scenario is unlikely to be supported.
