### ISSUE TITLE
install corrupt

### ISSUE THREAD

**Issue by infdahai** [Microsoft/vscode#51122]
Issue Type: <b>Bug</b>

my intelligense was crupted

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.73GB (4.46GB free)|
|Process Argv|D:\applications\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.55
c-cpp-compile-run|dan|0.0.6
vscode-great-icons|emm|2.1.32
code-runner|for|0.9.3
beautify|Hoo|1.3.0
latex-workshop|Jam|5.5.0
vscode-clang|mit|0.2.2
python|ms-|2018.4.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
color-highlight|nau|2.3.0
background|sha|1.1.18

</details>

**Comment by Tyriar** [comment]
Maybe try launching with `code --disable-extensions`, if not we need more information on the issue.
