### ISSUE TITLE
Quoted quotes break highlighting

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#51129]
I couldn't find a previous issue covering this, but this breaks the syntax highlighting:

![screenshot from 2018-06-05 09-50-05](https://user-images.githubusercontent.com/376658/40965531-df868ba2-68a5-11e8-9012-b85afed67993.png)

**Comment by V-ed** [comment]
Found this that is similar to your problem, but is a little different : https://github.com/Microsoft/vscode-cpptools/issues/671 (_and it was closed as it "wasn't really happening", which is not that useful anyway_)

This is a C++ issue, you may want to create an issue to the extension's repo instead : https://github.com/Microsoft/vscode-cpptools/issues

**Comment by aeschli** [comment]
I tried to reproduce and was not able in 1.24:
![image](https://user-images.githubusercontent.com/6461412/40984929-453a25a2-68e3-11e8-9638-73c8ff09a4ed.png)

Maybe this got fixed in the meantime. Or do you have extensions installed that replace the C++ grammar?

**Comment by Gruntfuggly** [comment]
I had disabled the C++ extension, so I thought it was a core problem, but you prompted me to look a bit further and I realised I am using the [Reloaded C++](https://marketplace.visualstudio.com/items?itemName=reloadedextensions.reloaded-cpp) extension.

This is the cause of the problem and it looks like there is already an issue raised against it:
https://github.com/kobalicek/reloaded-cpp/issues/2
Unfortunately it doesn't look like there is much acvitity...

**Comment by Gruntfuggly** [comment]
I found a way to bodge it in the short term (see kobalicek/reloaded-cpp#2), so I'm happy to close this.
