### ISSUE TITLE
Allow debug-actions-widget position adjustable and configurable.

### ISSUE THREAD

**Issue by v-pavanp** [microsoft/vscode#5112]
It would be great if we can allow user to adjust position of the "debug-actions-widget" according to their choice.
What we will get out of it:
1. We have one open issue (# 4332) where user not able to see the linter error message as it is covered by debug-actions-widget .
2. When user is working with small screen size (with chrome debugger tool window opened), some time file name is covered by debug-actions-widget.

![image](https://cloud.githubusercontent.com/assets/17735796/14399953/0f48d082-fda7-11e5-86f9-2c3f93e861dc.png)

Expected: 
1. Make the "debug-actions-widget" position configurable (Horizontal, vertical etc.)
2. Allow user to adjust position by dragging.

**Comment by knownasilya** [comment]
Instead of making it configurable, why don't we just make it sticky in the left panel. So that it's always at the top when the left panel is open and the panel contents are below it.
