### ISSUE TITLE
VS Code not able to install extensions : "An unknown error occurred. Please consult the log for more details."

### ISSUE THREAD

**Issue by vkvmudunuri** [Microsoft/vscode#51128]
no extensions are getting installed . 
![1](https://user-images.githubusercontent.com/18625838/40965038-51542a4a-68ca-11e8-852a-3d94728813f3.PNG)

this is the screenshot of "developer tools"
![capture](https://user-images.githubusercontent.com/18625838/40965380-2993ade0-68cb-11e8-8f1a-dbd16a83e1ea.PNG)

network snapshot of failure:
![capture](https://user-images.githubusercontent.com/18625838/40971836-86f000f4-68dc-11e8-9257-e1cddd606649.PNG)

**Comment by joaomoreno** [comment]
Looks like it.

Please check out the following docs page: https://code.visualstudio.com/docs/setup/network#_ssl-certificates

Then try `--ignore-certificate-errors`

**Comment by sandy081** [comment]
@vkvmudunuri Please check the docs and try as suggested

**Comment by vkvmudunuri** [comment]
proxy was blocking. setting were changed and urls were whitelisted . no problem now

**Comment by frontallobe** [comment]
Had the same issue. Monitored my Little Snitch Configurations while clicking on "**install**", saw that my settings were off and now everything works fine!
