### ISSUE TITLE
occasionally git_diff is stored as part of commit_message when using VSCode as git_default_editor

### ISSUE THREAD

**Issue by jvlad** [Microsoft/vscode#51121]
- VSCode Version: 1.20.1 f88bbf9137d24d36d968ea6b2911786bfe103002 x64
- OS Version: macOS High Sierra 10.13.4 (17E199)

Steps to Reproduce:

1. Configure VSCode as git default editor
My .gitconfig:
```
[user]
	name = name surname
	email = email@example.com
[core]
	editor = code -w -n
[diff]
    tool = vscode
[difftool "vscode"]
    cmd = code --diff --wait $LOCAL $REMOTE
```

2. using terminal run from within git-repo directory
```
git commit -v
```

**result**: VSCode opens with one editor_tab called `EDIT_COMMITMSG` as expected.

3. Specify commit message shorted than 92 characters (though I have no evidence the length makes any difference)

4. save file, close editor_tab

**unexpected result**: git-diff data appended and stored as a part of specified commit_message

Does this issue occur when all extensions are disabled?: Yes

Issue occurs in about 25-30% of cases of running `git commit -v`.

**Comment by bpasero** [comment]
@jvlad what is "`git-diff data appended and stored as a part of specified commit_message`" can you give an example?

**Comment by jvlad** [comment]
E. g.
I got this:  
```
commit 7d4ba51f4a28ebb50d3134fba7c3fe8be21eac22
Author: Vlad Zamskoi <v.zamskoi@gmail.com>
Date:   Tue Jun 5 23:12:56 2018 +0300

    2Test of trying to reproduce bug of storing git-diff as a part of commit_msg
    diff --git a/package/src/main/java/org/comp/ads/AdProviderFactory.java b/package/src/main/java/org/comp/ads/AdProviderFactory.java
    index 762406b..c400b91 100644
    --- a/package/src/main/java/org/comp/ads/AdProviderFactory.java
    +++ b/package/src/main/java/org/comp/ads/AdProviderFactory.java
    @@ -27,19 +27,4 @@ public class AdProviderFactory {
                            return null;
                    }
            }
    -
    -
    -
    -
    -
    -       public InterstitialAd getFbInterstitialAd(Activity activity) {
    -               return new FbInterstitialAd(activity);
    -
    -
    -
    -       }
    -
    -       public InterstitialAd getFbInterstitialAd(Activity activity, String adId) {
    -               return new FbInterstitialAd(activity, adId);
    -       }
     }
```

While I expect to get only this:  
```
commit 7d4ba51f4a28ebb50d3134fba7c3fe8be21eac22
Author: Vlad Zamskoi <v.zamskoi@gmail.com>
Date:   Tue Jun 5 23:12:56 2018 +0300

    2Test of trying to reproduce bug of storing git-diff as a part of commit_msg
```

So, the commit message out of a sudden contains all the data that (during composing the message) was in EDIT_COMMITMSG editor **below** the lines:  
```
# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.
```

**Comment by bpasero** [comment]
@jvlad this must be a configuration problem with your git, we are literally just opening a file as instructed by git. I am closing this as I do not think there is anything we can do in VS Code.

**Comment by jvlad** [comment]
@bpasero, got you, thanks. However, I don't see how it can be caused by my git since, as I told, the problem occurs not every time but occasionally.

Will try another editor for git to see if the problem is reproduced.
