### ISSUE TITLE
Race when trying to call reveal on a newly-added tree node

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51136]
I have some code that creates a new tree node and then tries to show it using `reveal()`. It seems like this code is racy because it takes time for the tree to process the new node. Eg., given this code:

```ts
const node = new SuiteTreeItem(...);
this.onDidChangeTreeDataEmitter.fire(node);
this.onDidChangeTreeDataEmitter.fire();
setTimeout(() => this.tree.reveal(node), 100);
```

If I make the timeout value big enough, it works fine. If it's too low then sometimes I'll get `Cannot resolve tree item for element 1/suite_1_1`.

I wonder if it's related to the buffering of updates in the tree? Maybe any pending updates need applying before `reveal` is processed? Strangely the very first node always seems to work, so maybe when there are no nodes it's already doing that?

(Otherwise, is there a better way to do this? Or a way to just show the tree, and not care about the node?)

**Comment by DanTup** [comment]
(cc @sandy081)

**Comment by sandy081** [comment]
@DanTup On what version of VS Code are you seeing this issue?

**Comment by DanTup** [comment]
Can't repro in insiders; apologies I should've tried there first :-)
