### ISSUE TITLE
VS Code Version 0.10.11 (0.10.11) - No intellisense available for razor

### ISSUE THREAD

**Issue by Felsig** [Microsoft/vscode#5113]
- VSCode Version: 0.10.11 (0.10.11)
- OS Version: OSX El Capitan 10.11.2 

Specifically when writing code like @Model.Id or the similar I get no sort of intellisense. I assumed that would be a feature as the website states support for Razor. Is this just not a feature?

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#168

**Comment by egamma** [comment]
There is currently no Intellisense for razor. Moving to omnisharp-vscode for investigation.

**Comment by Felsig** [comment]
Thanks!
