### ISSUE TITLE
VSCode crashes after opening and Ubuntu sends me a crash warning

### ISSUE THREAD

**Issue by gusbemacbe** [Microsoft/vscode#51146]
- VSCode Version: 1.24.0-insider 08537497eecd3172390194693d3d7c0ec8f52b70 x64
- OS Version: Ubuntu 18;04 64 bits

Steps to Reproduce:

1. VSCode opens and crashes
2. I received a warning window about Code Insiders crash

Does this issue occur when all extensions are disabled?: No

The log is bigger, I have to send the link to you. 

https://www.dropbox.com/s/j5vuca29hn7yin6/log-code-insiders-crash.txt?dl=0

**Comment by TomasHubelbauer** [comment]
You said this doesn't happen with extensions disabled. Is that accurate? If yes, did you try disabling extensions one by one to see which one could be causing that?

**Comment by gusbemacbe** [comment]
No, the extensions did not cause VSCode to crash. 

When I updated VScode, it open automatically, but it crashed

**Comment by gusbemacbe** [comment]
@bpasero and @Tyriar, please remove my topic, it is useless.

**Comment by TomasHubelbauer** [comment]
If it has been resolved, you can just close this issue.
