### ISSUE TITLE
cannot able to get list type when running in terminal in python

### ISSUE THREAD

**Issue by jitu46** [Microsoft/vscode#51144]
Issue Type: <b>Feature Request</b>

following is the error when i try to run the following command in the terminal provided by visual studio code.
jitender@jitender-linux:~/Jitender/Codes$ x = list()
bash: syntax error near unexpected token `('

while in gnome terminal  when i run the command. 
x = list()
type(x)
it gives the result as type = list

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-43-generic

**Comment by Tyriar** [comment]
Can you post a screenshot?
