### ISSUE TITLE
Tyring to remove a disabled log point with log message, suggests disabling it again

### ISSUE THREAD

**Issue by arikanorh** [Microsoft/vscode#51147]
- VSCode Version: 1.24.0-insider
- OS Version: Wİndows 10

Steps to Reproduce:

1. Add a log point with a message
2. Then click logpoint icon, it will warn you about considering disabling instead of removing
3. Accept disable
4. Then disabled log point icon again.
5. Now same warning popup will be shown and it will again suggest disabling logpoint although it is already disabled

Does this issue occur when all extensions are disabled?: Yes/No
Yes
![logpoint_bug](https://user-images.githubusercontent.com/17791032/40973717-ede41b38-68cd-11e8-8ed1-ab9c36df19ee.PNG)

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/50569
