### ISSUE TITLE
Intellisense and snippets no longer working reliably

### ISSUE THREAD

**Issue by lloydjatkinson** [Microsoft/vscode#51142]
Issue Type: <b>Bug</b>

* Run latest insider update
* Create global snippets

Neither intellisense or snippets are working reliably. Forcing it to load via CTRL + Space displays empty "Loading" dialog. Typing the name of a snippet no longer triggers the snippet.

Sometimes it will work fine after a restart of VS Code, but not always.

VS Code version: Code - Insiders 1.24.0-insider (f67e6397855fb25becbdf33df185f96da7fdd108, 2018-06-04T20:56:48.515Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.97GB (1.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
copy-relative-path|ale|0.0.2
razor-plus|aus|0.1.4
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.55
vscode-eslint|dba|1.4.12
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.4.0
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.10.0
favorites|kdc|1.4.4
prettify-json|moh|0.0.3
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.5.0
vetur|oct|0.12.3
project-snippets|reb|0.5.0
aspnet-helper|sch|0.6.4
vue-vscode-extensionpack|sdr|0.1.2
vue-vscode-snippets|sdr|1.3.0
code-spell-checker|str|1.6.10
vscode-status-bar-format-toggle|tom|1.3.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.6.0

(3 theme extensions excluded)

</details>

**Before restart**

![image](https://user-images.githubusercontent.com/5633938/40980197-c04947a0-68cf-11e8-9180-9867d9388c52.png)

**After restart**

![image](https://user-images.githubusercontent.com/5633938/40980237-d9324b40-68cf-11e8-9237-715ddf38b652.png)

**Comment by lloydjatkinson** [comment]
Checked possible duplicate issue, it's not.

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by kattkieru** [comment]
This is a persistent issue for the past few versions.  I'm not on Insiders (on 1.23.1) and it's still occurring.  Sometimes Intellisense will work for a few minutes, but usually it just dies.  When it does run, it runs much slower than it did earlier this year.

I thought this was a C++ issue only, but then I started experiencing the same in my Python projects.  I just disabled all installed extensions as noted above and now in-file completion is working fine.  On re-enabling the Python extension (2018.5.0), Intellisense breaks on Python files once again.  This includes symbol lookup; it'll just sit and spin with the _Loading_ message.  At times even if I close Code, I'll end up with a Code in the background going at 99% CPU. (Couldn't figure out why my MBP fans were spinning up just from editing a Python file.)

These issues occur on Win7, Win 10 Home (latest), and macOS.

I'd be happy to run anything you need to help you track this down. Intellisense is why I switched to Code a year ago.

**Comment by jrieken** [comment]
Sound like an extension issue, when they run go crazy they can block all other extensions from running. Can you follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by lloydjatkinson** [comment]
I've ran the profiler (as soon as it started recording the problem vanished initially but I managed to reproduce it after a while).
[CPU-20180608T120322.239Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2084268/CPU-20180608T120322.239Z.cpuprofile.txt)

**Comment by jrieken** [comment]
The view that enables to profile the extension host also shows the extension that has consumed most time. Can you forward this issue to them?
