### ISSUE TITLE
Python Print statement

### ISSUE THREAD

**Issue by jitu46** [Microsoft/vscode#51141]
Issue Type: <b>Feature Request</b>
in python3 file
x= 5
print('x : ',x)
if i run this statement in visual studio code then i get the result as 
('x: ',5)

where as in the terminal it shows x: 5

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-43-generic

**Comment by Tyriar** [comment]
Maybe you're running python2 in the integrated terminal? That's what I see in python2:

<img width="218" alt="screen shot 2018-06-06 at 4 28 25 am" src="https://user-images.githubusercontent.com/2193314/41012499-13b41ccc-6942-11e8-9491-32958ca7b1c0.png">
