### ISSUE TITLE
'editor.findWidgetResizeBorder' does not follow color name guidelines

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#51140]
`editor.findWidgetResizeBorder` should be

`editorFindWidget.resizeBorder` or `editorWidget.resizeBorder`

**Comment by aeschli** [comment]
@rebornix I make the change on master and release/1.24: Using `editorWidget.resizeBorder`

**Comment by rebornix** [comment]
@aeschli thanks for making it right.
