### ISSUE TITLE
Missing provideDocumentFormattingEdits call

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#5114]
- VSCode Version: 0.10.14-insider _and_ 0.10.11
- OS Version: Windows 10

I'm creating a Document Formatter and it seems that `provideDocumentFormattingEdits` is not being called. Instead, it always calls `provideDocumentRangeFormattingEdits`, with the `range` parameter defined as:

```
_end:e
  _character:0
  _line:12 // the line where the cursor is positioned
_start:e
  _character:0
  _line:0
```

I'm using [CSS Formatter](https://github.com/aeschli/vscode-css-formatter) as reference, and it presents similar issue. It always calls `provideDocumentRangeFormattingEdits`, but the `range` object has `e._character <> 0`.

Thanks for your help

**Comment by jrieken** [comment]
Yes, that how the format feature is implemented. When both document and range formattings-provider are present the range-based provider will be used - with the whole document range. 

Closing as I think that assumption is valid. @alefragnani Do you have a scenario in which the implemented behaviour doesn't make sense?

**Comment by alefragnani** [comment]
Ok, It make sense :+1:  But shouldn't the range be the _whole_ document?

I'm creating a formatter that uses _external tools_ and I'm supporting 2. One of them only works for _well formed files_ and so, it does not work for _selected pieces of text_. If both providers where called, I would only need to check the _tool_ in the right provider, to avoid error messages.

Thanks for your help.

**Comment by jrieken** [comment]
> Ok, It make sense :+1: But shouldn't the range be the whole document?

If it's not the whole document it's a bug. Tho, this seems about right: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/format/common/format.ts#L40

**Comment by alefragnani** [comment]
My bad, I misinterpreted the `range` values :disappointed: It is working perfectly :+1: 

Being so, I assume I only need the range formatter code, and could remove the document formatter.

Thanks

**Comment by jrieken** [comment]
Correct - we figure that a range formatting provider is the harder problem than a document formatting provider.
