### ISSUE TITLE
Improve color name `editorUnnecessary.foreground`

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#51152]
`editorUnnecessary.foreground` got added as a new color.
My first thought was that this is the color of an unnecessary editor.

TypeScript calls the ranges `unused spans`, so I suggest we use `unused`, not `unnecessary`

- `editorUnusedCode.foreground`
- `editor.unusedCodeForeground` (similar to editor.lineHighlightBackground)
- `editor.unusedCodeForeground`

We had some discussions in the ZRH standup that it should go along with future semantic highlights, but no proposal was made on what that would mean for the name.
@dbaeumer @jrieken @egamma

**Comment by wistcc** [comment]
I would like to take this one if you guys think this is a `good first issue`. Seems like I just need to rename `editorUnnecessary` by `editorUnused` on these files:
- `/src/vs/editor/browser/widget/codeEditorWidget.ts`
- `/src/vs/editor/common/model/intervalTree.ts`
- `/src/vs/editor/common/services/modelServiceImpl.ts`
- `/src/vs/editor/common/view/editorColorRegistry.ts`

**Comment by mjbvz** [comment]
Thanks @wistcc but this is not a good choice. Easy code change but we need to discuss the design of this feature more. For example,  should we fade out code instead of changing it all to grey?

**Comment by mjbvz** [comment]
Falls under #51104

**Comment by reeddunkle** [comment]
@mjbvz I'm just getting up-to-speed on the change. Thanks for adding the key `editorUnnecessaryCode.opacity` to control the alpha variable for the fadeout.

Is there still an option to change the color or has that been removed?

**Comment by mjbvz** [comment]
No, this option was been removed when we finalized the unused variable api

**Comment by Izhaki** [comment]
@mjbvz 

This is pretty bad... we used to have unused code highlighted in yellow so it is crystal clear (fading is not enough as some themes use light grey for comments etc.)

Now with 1.25.0, this feature seem to be broken (no `editorUnnecessaryCode.opacity`/`editor.showUnused` combination seems to have an effect).

Related: https://github.com/Microsoft/vscode/issues/51420
