### ISSUE TITLE
[json] schema loading should use the system proxy

### ISSUE THREAD

**Issue by tkrotoff** [Microsoft/vscode#51151]
- VSCode Version: 1.23.1
- OS Version: Windows 10 x64 1803

Steps to reproduce:

1. Corporate proxy + PC with Windows properly configured to use the proxy (NTLM) => everything works (including Chrome, Firefox)
2. No `"http.proxy"` inside vscode settings
3. No problem to search and install vscode extensions
4. => Problem when loading a JSON schema
```
Unable to load schema from 'https://schemastore.azurewebsites.net/schemas/json/babelrc.json':
Unable to connect to https://schemastore.azurewebsites.net/schemas/json/babelrc.json.
Error: connect ETIMEDOUT 168.62.224.13:443
```
5. Set `"http.proxy"`
6. No problem loading JSON schema

vscode seems to use the system proxy for everything (notably extensions) as expected #7140, except when loading a JSON schema. (of course I can open `https://schemastore...` with the multiple browsers installed on the PC).
If I manually set `"http.proxy"` then JSON schema work.

**Comment by aeschli** [comment]
depends on https://github.com/Microsoft/vscode/issues/12588
