### ISSUE TITLE
Link that span on multiple lines are not highlighted

### ISSUE THREAD

**Issue by Geobert** [Microsoft/vscode#51157]
- VSCode Version: Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Win7 and Win10

Steps to Reproduce:

1. write `[my link](https://my_url.com)`
2. it's hightlighted
![image](https://user-images.githubusercontent.com/72570/40977672-7c17350c-68c9-11e8-9ce4-84ef732b4ca8.png)

3. put line break between `my` and `link`
4. hightlighting is gone:
![image](https://user-images.githubusercontent.com/72570/40977691-911424b0-68c9-11e8-98dc-9269f727da34.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Geobert** [comment]
Same issue with `markup.inline.raw.string.markdown`

**Comment by alexandrudima** [comment]
The built-in link detector does not accept line breaks inside links. So, that part is as-designed (i.e. a link across two lines in a plain text file).

I don't know about the specific markdown grammar link detection.

**Comment by mjbvz** [comment]
Yes, it is very difficult to write a textmate grammar rule for markdown links that works across lines. I've looked into it but don't think we will get around this anytime soon.

Closing as out of scope
