### ISSUE TITLE
Debug session dropdown sometimes doesn't populate names for a while

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51162]
I'm spawning multiple debug sessions like this:

```ts
testSuites.forEach((suite) => {
	const ws = vs.workspace.getWorkspaceFolder(vs.Uri.file(suite));
	const relativePath = path.relative(fsPath(ws.uri), suite);
	vs.debug.startDebugging(ws, {
		name: `Dart ${relativePath}`,
		noDebug: true,
		program: suite,
		request: "launch",
		type: "dart",
	});
});
```

Sometimes when I do this, the debug session dropdown remains blank for some period (5-10 seconds?) which is kinda confusing:

![screen shot 2018-06-05 at 2 56 04 pm](https://user-images.githubusercontent.com/1078012/40980621-c50eea64-68d0-11e8-88d5-65e87b2c5e42.png)

It does eventually update and show the names I provided. Possibly it's for the duration of running the resolve method? If so, I think if it's going to show the drop-down maybe it should use the original name and the update it when the resolve method finishes?

**Comment by isidorn** [comment]
At the moment when the dropdown is emtpy can you see something in the callstack or is it also empty?
If you click on the dropdown does it stay empty?
You could put a breakpoint or some logging here to checkout if the names array is empty at some moment
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L217

**Comment by DanTup** [comment]
I can't repro this since the update; the items seem to always appear immediately. It's possible there's something different in the project I'm testing, but I don't think so. So I'll close this for now and if I see it again I'll dig through the code you link.
