### ISSUE TITLE
Terminal process terminates during build task when output is too large

### ISSUE THREAD

**Issue by joemm1** [microsoft/vscode#51163]
If I hook up a build task to build my project then it causes the build terminal to exit with "The terminal process terminated with exit code: 1". This seems to be because the output is too long.

If I change build flags to reduce the size of the output then the problem goes away. Similarly, if I reduce the size of "terminal.integrated.scrollback" it seems to happen less.

(Of course both of these workarounds are not ideal).

The exact same build command run in a terminal window inside Visual Studio Code has no such problems.

Thanks in advance. Let me know if there's anything I can provide to help.
Joe

**Comment by dbaeumer** [comment]
@joemm1 can you please provide me with a GitHub repository I can clone that demos this.

**Comment by joemm1** [comment]
It happens in an empty workspace if I eg just create a task to echo incrementing digits:

{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "echo",
			"type": "shell",
			"command": "for i in `seq 1 10000`; do echo $i; done",
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}

If I run that multiple times it gives up at varying points but always before 6000.

This is with "terminal.integrated.scrollback": 50000. If I reduce my scrollback size to 1000 it completes fine.

Whereas if I run that command directly from the integrated terminal, it completes fine whatever the scrollback size.

Thanks,
Joe

**Comment by joemm1** [comment]
(Note this is on macOS)

**Comment by dbaeumer** [comment]
@Tyriar can you please have a look. I don't do anything special in this case. Simply launching a terminal with the command passed with `-c`. This seems to be related to `terminal.integrated.scrollback` and it works fine for a value of 1000.

**Comment by Tyriar** [comment]
I had a look, it's an interesting bug which I don't fully understand. The process should run completely independently of the UI and it's the UI which appears to be affecting the process. It repro's far less with large scrollbacks when the buffer is full (which means no HTML layouts need to happen to adjust the scroll bar - this slows down the UI significantly).

My current guess is it's a race condition related to https://github.com/Microsoft/node-pty/issues/85?

**Comment by tksuoran** [comment]
The issue has become more serious recently. I use tasks which cat (or sed) files to terminal, and that gets parsed to problems. Now that output is truncated, effectively for all such tasks, as result not all problems get parsed to Problems window.

**Comment by Tyriar** [comment]
Seems to be fixed?

**Comment by x432ph** [comment]
I still have this problem in vscode 1.39.2.

If my task executes a program that prints many numbers to the console (e.g. numbers from 0 to 4999), then the output in the built in console will sometimes randomly stop too soon, sometimes after 4000, sometimes even before 2000.

Executing the same program in my normal console on my system, instead of in the integrated vscode terminal, this problem never occurs, so it's not a bug in my program.

I tested this under Debian 11.

**Comment by x432ph** [comment]
![Screenshot from 2019-11-04 16-56-31](https://user-images.githubusercontent.com/20044139/68135565-2f5c6280-ff24-11e9-8ce2-b17f966bce03.png)

As you can see in this screenshot, even if this bug occurs, the bold text **Press any key to close the terminal.** still appears after the output cuts off. Maybe this information is useful to track down the location of the bug?
