### ISSUE TITLE
Dragging panel tabs is blurry

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#51166]
[via @isidorn](https://github.com/Microsoft/vscode/pull/51061#issuecomment-394614016):

> The only left issue is the blurry tab - here's a gif showing that. First is your branch - notice how it is not so crisp, second is stable. 

![Image](https://user-images.githubusercontent.com/1926584/40962125-ef9da3fa-68a4-11e8-9347-14a5d7afe438.gif)

**Comment by isidorn** [comment]
I have noticed that there is a same issue when you drag editor tabs around
So it is probably not easy to fix since @bpasero left it there and I probably also complained there

**Comment by bpasero** [comment]
I think when you drag an HTML element it will literally be taken as drag image unless you provide your own drag image. I am not sure we want to change that?

**Comment by isidorn** [comment]
We should not change that, but what I find weird is that the HTML element in this case looks blury.
I guess this is just native html behavior

**Comment by misolori** [comment]
@isidorn should I assign this to someone else if it's not a easy fix?

**Comment by isidorn** [comment]
@misolori don't worry I also have a lot of issues that I do not know how to fix.
Though I think there is no good way to fix this since this is native behavior and nobody complained about the tabs that have the same issue. Thus closing as will not fix
Not clue why it was better before
