### ISSUE TITLE
Have a way to run multiple watches together

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#51168]
When working on Language Servers, it's common to watch-compile on two folders. For example:

https://github.com/octref/vscode-language-server-template/blob/master/package.json#L9-L10

For us, we have

```
"compile": "gulp compile-extension:css-language-features-client && gulp compile-extension:css-language-features-server"
```

But we can't do

```
gulp watch-extension:css-language-features-client && gulp watch-extension:css-language-features-server
```

Because only one will be run.

Are there any way to do this with gulp, or can we include something like https://github.com/mysticatea/npm-run-all or https://github.com/kimmobrunfeldt/concurrently?

**Comment by jrieken** [comment]
no clue, not the right person to answer this

**Comment by jrieken** [comment]
maybe @joaomoreno knows more?

**Comment by joaomoreno** [comment]
Well, that's a freebie:

```
gulp watch-extension:css-language-features-client watch-extension:css-language-features-server
```

**Comment by octref** [comment]
@aeschli Did that for CSS, do you want to do the same for html/json? https://github.com/Microsoft/vscode/commit/e6bb52df4d26e086aa2035045daa315460e562d0

**Comment by aeschli** [comment]
@octref Feel free to add. I always use the yarn watch on the vscode folder.
