### ISSUE TITLE
On opening Problems view, sync (reveal?) to current file 

### ISSUE THREAD

**Issue by tboby** [Microsoft/vscode#51160]
With the setting `problems.autoReveal` enabled, opening a file "reveals" the problems in that file. However, when opening the Problems view, it does not "reveal" the problems in the **current** file.

When you have many files/errors, it's not trivial to find the current file, and it seems silly to swap to another file and back! This may be related to diagnostics being added *after* a file is opened.

Could the default behaviour on opening the problems view be to "reveal" that file's diagnostics? To avoid losing position, perhaps this should be the default behaviour *the first time the problems view is opened after changing file*.

**Comment by sandy081** [comment]
Assigning to june for investigation.

**Comment by sandy081** [comment]
@tboby It works properly for me. When I open Problems view, the current active file is revealed in the Problems view. Do you have specific steps / sample to reproduce?

**Comment by tboby** [comment]
@sandy081 A gif showing my language server creating the diagnostics, then me changing to the problems tab, and it not revealing: https://i.imgur.com/cWQDP8q.gifv

I'll try and create a sample project a bit later. :)

**Comment by sandy081** [comment]
Not sure what's happening in the gif.. A sample would be grateful.

**Comment by tboby** [comment]
@sandy081 Ok, got a repo + steps:
1. clone https://github.com/tboby/vscode-issue-51160
2. Open folder "vscode-issue-51160"
3. Open file "5errors.ts"
4. Open "Output" panel
5. "Reload window"
6. "Run build task"
7. Open "Problems"

Expected:
`5errors.ts` is revealed

Actual:
`25errors.ts` is revealed and `5errors.ts` is not visible.

![2018-06-26_14-28-53](https://user-images.githubusercontent.com/447391/41915366-7091454e-794d-11e8-8211-1c5fd278776d.gif)
