### ISSUE TITLE
Deploy to Azure using App Service

### ISSUE THREAD

**Issue by jleach** [Microsoft/vscode#51165]
- VSCode Version: 1.23.1 
- OS Version: 10.13.4

Steps to Reproduce:

1. Sign into Azure

As per this site `https://code.visualstudio.com/tutorials/app-service-extension/getting-started` when sign into Azure I get `Error: Cannot find subscription with name....`.  I'm not behind a proxy and I've tried on several different internet connections. This happens with both the App Service Extension and the Azure Function extension.

**Comment by aeschli** [comment]
@jleach I see you also reported https://github.com/Microsoft/vscode-azure-account/issues/60. Is it about the same issue? If yes, can you mention there that you are behind a proxy? I'd suggest closing the current issue as Microsoft/vscode-azure-account is the right place.

**Comment by jleach** [comment]
Great. That website above directed me here so I wasn't sure where the wright project is. Closing...
