### ISSUE TITLE
Arrow key cursor movement with the same file open in two groups

### ISSUE THREAD

**Issue by tedthemusician** [Microsoft/vscode#51170]
Issue Type: <b>Bug</b>

1. Open the same file in two groups (opening one file and typing `Ctrl+/` is adequate)
1. Place the cursor at an arbitrary location in one group's editor
1. Place the cursor at a different location in the other group's editor
1. Click the first editor's title tab
1. Press any keyboard arrow key

**Expected result:** The first editor's cursor moves up, down, left, or right one character relative to its previous position.

**Actual result:** The first editor's cursor moves up, down, left, or right one character relative to the second editor's cursor position.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (4.11GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\ted\AppData\Local\Temp\scp58116\cwroot\docroot\coreweb_viewerdev\app\controllers\studies_api_controller.php|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.2
vscode-nextgenas|bow|0.12.0
json-tools|eri|1.0.2
vscode-relative-line-numbers|ext|0.0.5
vimL|fal|0.0.3
php-debug|fel|1.12.3
language-haskell|jus|2.5.0
python|ms-|2018.4.0
language-stylus|sys|1.9.2
vim|vsc|0.12.0
vscode-todo-highlight|way|0.5.12
better-align|wwm|1.1.6

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@tedthemusician very likely caused by the vim extension, can you report this issue there?
