### ISSUE TITLE
JavaScript React Syntax - Template literal inside component props breaks highlighting

### ISSUE THREAD

**Issue by Vivalldi** [Microsoft/vscode#51171]
Issue Type: <b>Bug</b>

Inside a `.jsx` file (JavaScript React Syntax) call a component in render and pass a prop with template literals.
Example:
```
...
return () {
    <div>
      <SomeComponent key={`some-${someVariable}`} />
      <AnotherComponent />
    </div>
}
```

In the above example syntax highlighting will work as expected until just after the second backtick in the `SomeComponent`. Everything thereafter is then highlighted to be the same color.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.0.21
vscode-docker|Pet|0.0.27
city-lights-icon-vsc|Yum|1.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
vscode-new-file|dku|4.0.2
vscode-npm-script|eg2|0.3.4
vscode-great-icons|emm|2.1.33
enki-vscode-theme|enk|0.3.1
atom-keybindings|ms-|3.0.4
vsliveshare|ms-|0.3.262
debugger-for-chrome|msj|4.5.0
polacode|pnp|0.2.2
postcss|ric|2.0.0
gitblame|wad|2.4.2
vscode-todo-highlight|way|0.5.12

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
I can't repo in vscode insiders:

<img width="738" alt="screen shot 2018-06-05 at 1 05 31 pm" src="https://user-images.githubusercontent.com/12821956/40999893-2b574b0a-68c1-11e8-8670-02d07f70ac2c.png">

Please test in insiders with all extensions disabled

**Comment by Vivalldi** [comment]
Ahh so turns out this get's a little bit more interesting. The actual case is as follows,

```
class Foo {
    render(){
        const barList = bars.map(bar => (
            [
                <Baz key={`bar-${bar.id}`} />,
                <Qux />
            ]
        ));
    }
}
```

The important bit being the "dropped" square bracket. I'll just avoid dropping the bracket but it is a bit odd.

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/624 to track this upstream
