### ISSUE TITLE
node-weak is evil

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5117]
- VSCode Version: 0.10.12-alpha (251829217a4b023830e508fba0274ad660908c22)
- OS Version: Windows 10

Steps to Reproduce:

1. open files from the typescript repository (best with d.ts files from lib folder)
2. wait until you see a dialog popping up and the extension host going down (see animation)

This was likely introduced by https://github.com/Microsoft/vscode/commit/bac28cc23d17839eb0715790a462ace853597a83. Luckily the windows dialog points me to an assertion in the weak that causes this (https://github.com/TooTallNate/node-weak/blob/master/src/weakref.cc#L221). 

Now I notice that there are many more assertions in that library, each of them will cause the extension host to crash. Since I try to update to Electron 0.37.x, I see the extension host crash in a very similar way (though I am not presented with the nice dialog pointing me to where it crashes).

We should talk about finding a better solution to virtual document recycling. On a separate note, I am not sure why each document has to go through node-weak if we only use it for virtual documents cleanup?

![untitled](https://cloud.githubusercontent.com/assets/900690/14402633/fbd488b2-fe3b-11e5-9794-dbf13174cb41.gif)

@jrieken @alexandrudima fyi

**Comment by jrieken** [comment]
interesting...

**Comment by jrieken** [comment]
I'll see what we do there

**Comment by jrieken** [comment]
@bpasero Did you try to run the extension host with [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDocuments.ts#L297) avoiding the `isWeak` call, like make it return false?

**Comment by bpasero** [comment]
@jrieken indeed, when I return `false` I cannot reproduce the crash so far. I wonder if node-weak thinks an object is not yet dead and we return the proxy and shortly later the object gets garbage collected and calls into the proxy result in the crash.

**Comment by jrieken** [comment]
yeah, that's why I added the `isNearDeath` check which in the end causes more trouble... But it's definitely the right direction. 

@bpasero Did you also try the opposite? Leaving the `isDead` check but never returning a proxy but always fresh documents?

**Comment by jrieken** [comment]
closing as the changes that caused the issue are reverted and on-top more careful `isWeak` check is used. Unsure where the electron adoption is tracked but discussion about incompatibly should happen there.

**Comment by bpasero** [comment]
@jrieken when I always return a fresh weak-reference (but still do the isweak check) it also does not crash. so the issue seems to be returning a weak reference that actually maybe is near death and calling methods on it.

Btw I also tested with your changes in https://github.com/Microsoft/vscode/commit/edc2d3fa5b1ab92edab29cd87d7e87c049896063 but could still reproduce the crash unfortunately.

**Comment by bpasero** [comment]
Let's continue in https://github.com/Microsoft/vscode/issues/5162
