### ISSUE TITLE
Diff editor: Show encoding and eol differences

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#5118]
- VSCode Version:
  0.10.14-insider 17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c
- OS Version:
  Windows 10 x64
  Steps to Reproduce:

Diff files which changes BOM existence and/or line-feed type (CR,LF,CRLF).
The diff view shows us the files are different but we actually see no difference.

I think there should be two status bars (area?) to indicate BOM existences and line-feed types for both versions.

**Comment by egamma** [comment]
fyi @joaomoreno

**Comment by sguillia** [comment]
It would be an enhancement to be able to toggle between "_Show CRLF / LF differences in diff view_" and "_Don't show them_".

But I love the feature that allows to ignore line-feed diffs - please keep it.

Note that line feeds may be heterogeneous: a same file can have both LF and CRLF.

**Comment by alexandrudima** [comment]
Let's continue tracking in #19254 because that one has more upvotes.
