### ISSUE TITLE
C/Cpp: Edit Configurations command missing

### ISSUE THREAD

**Issue by ljreder** [Microsoft/vscode#51189]
Issue Type: <b>Settings Search Issue</b>

It seems when an include file in C++ is missing a path the documentation is out of date.  I tried the "C/Cpp: Edict Configurations" command and it did not exit.  Also the c_cpp_properties.json I could not find.  I was able to simply set C_Cpp.default.includePath to fix it.

VS Code version: Code - Insiders 1.24.0-insider (b4e6fe3bd751448783ed20c8e49fdabd69514b8d, 2018-06-05T16:44:23.745Z)
OS version: Darwin x64 17.5.0

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.2.0
vscode-clang|mit|0.2.2
python|ms-|2018.5.0
cpptools|ms-|0.17.4

</details>No fuzzy results

Query: includePath
Literal matches: 2

**Comment by aeschli** [comment]
Can you file this against https://github.com/Microsoft/vscode-cpptools? Thanks!
