### ISSUE TITLE
Cannot configure php.executablePath using a remote server

### ISSUE THREAD

**Issue by bigweld86** [Microsoft/vscode#51187]
Cannot configure php.executablePath using a remote server

- VSCode Version: 1.23.1
- OS Version: Win 10
- External Server OS: Centos

Steps to Reproduce:

1. Try configuring php.validate.executablePath and php.executablePath by adding the whole path to the server
2. Save

**Comment by roblourens** [comment]
See https://github.com/Microsoft/vscode/issues/43636
