### ISSUE TITLE
JS/TS "go to definition" can open wrong file after file case change on case-insensitive systems

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#51183]
*Opening individual cases to track bugs around file system casing with js/ts*

**Steps**
1. On a case insensitive file-system (normal Mac OS or windows)
1. Run `Clear editor history` and `Clear recently opened`
1. Restart VS Code in an empty project
1. Create a file called `abc.ts` with the contents: 

    ```ts
    export const abc = 123
    ```

1. With the file open, rename it to `ABC.ts`
1. Run go to definition on `abc`

**Bug**
Opens a  duplicate file in the same window. TS now in weird state.

**Comment by RMacfarlane** [comment]
Able to repro on latest insiders:
VS Code version: Code - Insiders 1.25.0-insider (07d89abf1522a67f0e8105770505077f454ab021, 2018-06-28T05:19:16.448Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Seems fixed now.
