### ISSUE TITLE
Opening settings editor fails the first time, after grid changes merged

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#51188]
I think this started in master after the grid changes were merged. 

The first time I open the (old) settings editor, I get this error:

```
TypeError: Cannot read property 'id' of undefined
    at EditorViewStateMemento.loadState (/Users/roblou/code/vscode/src/vs/workbench/common/editor.ts:1071:29)
    at TextFileEditor.BaseTextEditor.loadTextEditorViewState (/Users/roblou/code/vscode/src/vs/workbench/browser/parts/editor/textEditor.ts:275:38)
    at /Users/roblou/code/vscode/src/vs/workbench/parts/files/browser/editors/textFileEditor.ts:140:34
    at Object.notifySuccess [as _notify] (/Users/roblou/code/vscode/out/vs/base/common/winjs.base.js:1185:60)
    at Object.enter (/Users/roblou/code/vscode/out/vs/base/common/winjs.base.js:867:31)
    at _Base.Class.derive._creator._run (/Users/roblou/code/vscode/out/vs/base/common/winjs.base.js:1083:30)
```

`group` is undefined

I'm able to open it the second time.

**Comment by bpasero** [comment]
@roblourens how do you reproduce this exactly? And are we talking about this editor:

![image](https://user-images.githubusercontent.com/900690/41020097-e564e516-6961-11e8-8577-1b074d3d76ca.png)

**Comment by roblourens** [comment]
I was seeing it often, and this morning @isidorn mentioned that he has seen it too. But I just tried on the latest in master and did not see it. So I will reopen this if I see it again.

**Comment by roblourens** [comment]
I saw it again. Let me know how I can help debug.

**Comment by bpasero** [comment]
@roblourens the first step would be to write down the steps how to reproduce

**Comment by bpasero** [comment]
@roblourens also, what is the visible impact when this error happens? Does one side of the setting stay empty (left or right)?

**Comment by roblourens** [comment]
Literally just open the settings editor. The whole editor appears for an instant, then closes.

I've seen it when I press `ctrl+,` and also when the settings editor is just persisted as open.

**Comment by roblourens** [comment]
Right after opening code-oss, and pressing ctrl+,. 

![jun-06-2018 22-30-16](https://user-images.githubusercontent.com/323878/41080011-4301792e-69d9-11e8-9e5b-31fe62df9e56.gif)

**Comment by bpasero** [comment]
Even though I cannot reproduce I pushed a check for group being null. Somewhere in Sandys settings editor, the group is not being forwarded to one of the two sides.

**Comment by isidorn** [comment]
@bpasero I confirm that I was seeing this. Sometimes reproes by simply opening settings, sometimes not - sorry for bad steps
