### ISSUE TITLE
Add HTML representation when copying text to clipboard

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#51198]
Please add an HTML variant when copying text from an editor to the clipboard, with all color + font informations the syntax highlighter applies. This allows to paster nicer copies of the text into other documents, which support HTML.

**Comment by Cirieno** [comment]
Actually, I would like to suggest the exact opposite: when copying from VSCode and pasting into Outlook emails or Skype chats etc, the formatting is also copied (including sometimes the background colour of the whole VSCode document ie black for my theme) and while both these programs have a "paste unformatted" option it's easy to forget and sometimes lingering invisible HTML elements continue to affect further typing.

Suggestion: a "copy unformatted" or similar option in the right-click context menu.

**Comment by mike-lischke** [comment]
I just realized I wish for something that exists already. I really don't know why I got the impression there wouldn't be formatting for clipboard text. So, I'll close this FR. @Cirieno can you open your own Issue/FR?

**Comment by Cirieno** [comment]
:)
Will do.
