### ISSUE TITLE
markdown snippets doesen't work

### ISSUE THREAD

**Issue by iRuxu** [Microsoft/vscode#51194]
Issue Type: <b>Bug</b>

1.setting the markdown snippets in markdown.json file
2.use the snippet in a README.MD file
3.type the prefix and tab ,and it didn't work

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (9.61GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe F:\Study\Test\hbs|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.30
prettier-vscode|esb|1.4.0
minify|Hoo|0.3.0
docthis|joe|0.7.1
theme-monokai-pro-vscode|mon|1.1.6
vscode-language-pack-zh-hans|MS-|1.23.5
python|ms-|2018.5.0
team|ms-|1.136.0
material-icon-theme|PKi|3.5.0
sass-indented|rob|1.4.9
vscode-gulp|tan|0.0.4
open-in-browser|tec|1.1.0
vscode-todo-highlight|way|0.5.12
ascii-unicode-escape|yar|0.1.0

</details>

**Comment by aeschli** [comment]
Did you enable tab completion?
`"editor.tabCompletion": true`

**Comment by iRuxu** [comment]
yes. thank u very much.
i follow your tips .it's fixed.
but a little confused.
why i can use the tab to active snippet in other lang files..
