### ISSUE TITLE
methods on variables in scripts 

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#51195]
Is it possible to as in python a *dir()* on a variable from a script within terminal ?

**Comment by Tyriar** [comment]
It's not clear what you mean, I suspect you may be trying to do something inside the terminal's shell which is a different world that VS Code doesn't have much control over. The `terminal.integrated.env` and `terminal.integrated.shellArgs` settings are the main ways to tell the terminal how to do something.

**Comment by SheepDomination** [comment]
What I mean, is it possible to run a language command on variables from within a script in terminal ? As you can see a list of methods etc of a variable in python using `dir()` ?

**Comment by Tyriar** [comment]
It's still not clear what you mean. If you're in a Python shell you can write python in it and access the variables within the terminal. 😕

**Comment by SheepDomination** [comment]
You write a variable in a script; now you want to use the terminal to access methods and such from the variable in the script, for which you may want to use in your script.

**Comment by Tyriar** [comment]
@SheepDomination you write a `test.py` script file and run it in the terminal The terminal accessed the variables and methods in the script because it's being run?

**Comment by SheepDomination** [comment]
> The terminal accessed the variables and methods in the script because it's being run? 
Access the methods of the variables from the script within terminal.

**Comment by Tyriar** [comment]
It's not, to me "methods of the variables from the script" are all 100% contained within python, which runs *within* the terminal.

**Comment by SheepDomination** [comment]
Then I assume you can access variables options of a script from terminal ?
