### ISSUE TITLE
Powershell Integrated Terminal issue with import-module for msonline

### ISSUE THREAD

**Issue by TheComaCorpse** [Microsoft/vscode#51190]
Issue Type: <b>Bug</b>

While using the Powrshell Integrated Console.

Import-module msonline should import the cmdlets but I get an error 

"import-module : Could not load file or assembly 'file:///C:\Program Files (x86)\WindowsPowerShell\Modules\msonline\1.1.183.8\Microsoft.Online.Administration.Automation.PSModule.dll' or one of its dependencies. An attemptwas made to load a program with an incorrect format.At line:1 char:1
+ import-module msonline
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], BadImageFormatException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand"

When using the powershell console Import-module msonline works as expected. 

tried uninstalling and reinstall module mulitple times from PSgallery with same result. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (24 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|47.91GB (31.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.3
Go|ms-|0.6.81
PowerShell|ms-|1.7.0

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
