### ISSUE TITLE
PHP Blade comments do not show correct color

### ISSUE THREAD

**Issue by mikelnorth** [Microsoft/vscode#51192]
In Laravel/Lumen a PHP framework there is a special type of comment, it looks like {{-- --}} this comment is translated by Lumen to be /* */ type of comment.

In vs code - all versions, all themes. the Blade comment does not display the same color as every other comment type, ie //, /* */, <?-- -->

Can there be a way to specifically give color to a certain symbol or text contained in a symbol?

the comment would look like so

{{-- This is a comment --}}
this would be compiled to
/* this is a comment */

current solution is downloading the extension https://marketplace.visualstudio.com/items?itemName=cjhowe7.laravel-blade

**Comment by m-thorsen** [comment]
Blade is not natively supported, you need an extension. This one has served me well:
https://marketplace.visualstudio.com/items?itemName=cjhowe7.laravel-blade

The comment syntax is `{{-- --}}`, not `{-- --}` though

**Comment by mikelnorth** [comment]
Thanks, @m-thorsen ,

I ended up finding the extension not long after the post.

**Comment by techns27** [comment]
Hi @m-thorsen 

I have tried with the link given in your comment. But for me it's not working.
It's not highlighting comment.
Whether its  OR {{-- --}}

Please advice.

Thanks.
