### ISSUE TITLE
Running "debug" or "run" via cmd+shift+p on a go project returns error: command 'npm.runScript' not found

### ISSUE THREAD

**Issue by balupton** [Microsoft/vscode#51196]
Issue Type: <b>Bug</b>

Video of the issue exists at https://youtu.be/MMEg7WmCLKY

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.31GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
EditorConfig|Edi|0.12.4
material-icon-theme|PKi|3.5.0
vscode-docker|Pet|0.0.27
vscode-eslint|dba|1.4.12
terraform|mau|1.1.2
terraform-snippets|min|2.0.1
python|ms-|2018.5.0
Go|ms-|0.6.81
vscode-sort-json|ric|1.11.0
stylelint|shi|0.36.3
fish-vscode|sky|0.2.0
ayu|tea|0.14.0
shellcheck|tim|0.5.1

</details>

User Settings:

```
{
	"editor.cursorBlinking": "solid",
	"editor.cursorStyle": "line-thin",
	"editor.detectIndentation": false,
	"editor.folding": false,
	"editor.fontFamily": "Monoid-Retina, Monoid, Hasklig, Source Code Pro, IBM Plex Mono, Hack, Monaco, Fira Code, Fira Mono, PT Mono, Andale Mono, Menlo",
	"editor.fontLigatures": true,
	"editor.fontSize": 12,
	"editor.formatOnSave": true,
	"editor.insertSpaces": false,
	"editor.minimap.enabled": false,
	"editor.renderControlCharacters": true,
	"editor.renderIndentGuides": true,
	"editor.renderWhitespace": "all",
	"editor.roundedSelection": true,
	"editor.tabSize": 3,
	"editor.wordWrap": "on",
	"eslint.alwaysShowStatus": true,
	"eslint.autoFixOnSave": true,
	"eslint.enable": true,
	"eslint.run": "onType",
	"extensions.autoUpdate": true,
	"files.associations": {
		"*.pine": "go"
	},
	"files.exclude": {
		"**/.DS_Store": true,
		"**/.git": true,
		"**/.hg": true,
		"**/.svn": true,
		"**/.vscode": false,
		"**/database": true,
		"**/database.json": true,
		"**/node_modules": true,
		"**/yarn.lock": true
	},
	"files.trimTrailingWhitespace": true,
	"flow.enabled": false,
	"flow.useNPMPackagedFlow": true,
	"git.confirmSync": false,
	"javascript.format.enable": true,
	"javascript.format.insertSpaceBeforeFunctionParenthesis": true,
	"javascript.implicitProjectConfig.checkJs": true,
	"javascript.validate.enable": false,
	"markdownlint.config": {
		"MD007": {
			"indent": 4
		},
		"MD012": false,
		"MD034": false
	},
	"python.linting.pylintPath": "/usr/local/bin/pylint",
	"search.useIgnoreFiles": true,
	"typescript.implementationsCodeLens.enabled": false,
	"typescript.referencesCodeLens.enabled": false,
	"typescript.validate.enable": true,
	"window.nativeTabs": true,
	"window.titleBarStyle": "native",
	"window.zoomLevel": 0,
	"workbench.colorTheme": "Ayu Mirage",
	"workbench.editor.closeOnFileDelete": false,
	"workbench.editor.tabCloseButton": "left",
	"workbench.fontAliasing": "antialiased",
	"workbench.iconTheme": "material-icon-theme",
	"workbench.startupEditor": "newUntitledFile",
	"zenMode.fullScreen": false,
	"zenMode.hideStatusBar": false,
	"zenMode.hideTabs": false,
	"zenMode.restore": true,
	"go.gopath": "~/go"
}
```

**Comment by JacksonKearl** [comment]
To be clear, the fix here is that "Debug" and "Run" have been removed entirely from the command pallet? Cant see them in either a go project or a node/electron one.

**Comment by chrmarti** [comment]
@JacksonKearl The commands were from the NPM view, they were never meant to apply to Go. The fix was to hide them from the command palette.
