### ISSUE TITLE
Don't comment the whole line if something is being selected

### ISSUE THREAD

**Issue by Sibiraj-S** [Microsoft/vscode#51208]
```
Code Version: 1.23.1
Os Verison     : WIndows 10 build 1803
```

If I select some text and comment it the whole line gets commented, but should it behave like that?
For some formats it is okay, but files like HTML, this approach doesn't suit well.

![select](https://user-images.githubusercontent.com/20282546/41028334-ca527f38-6996-11e8-9a1f-09ef32833448.gif)

**Comment by aeschli** [comment]
There are two different comment commands:
- Toggle line comment
- Toggle block comment

The second one is what you are looking for.
