### ISSUE TITLE
View visibility should be per user not per workspace

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#51203]
1. Hide the outline view
2. Open a new workspace, outline view is visibile 🐛

Me as a user find this particulary disturbing.

fyi @jrieken

**Comment by sandy081** [comment]
@isidorn I cannot reproduce it. Attaching the video of the steps I did. Let me know if they are same as yours


![kapture 2018-06-06 at 16 44 40](https://user-images.githubusercontent.com/10746682/41045662-110b000a-69a9-11e8-94f0-9dcadd316717.gif)

**Comment by warpdesign** [comment]
I had the same problem today. Started VSCode which opened the latest opened directory, I activated the outline. Then chose "open folder" and selected another directory: the outline was deactivated.

```
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:37:01.579Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by isidorn** [comment]
@sandy081 here are the steps which produce funky results for me
1. Purple vs code, hide outline view 
2. Open any other workspace in the same vscode window -> notice outline view is shown

Or try the other way around
Have outline view shown in the workspace, close that folder and in the purple it might not be shown

Please try a couple of times since it does not repro 100%
The visivbility is not the only problem, sometimes collapsed / expaned is also not preserved

**Comment by ramya-rao-a** [comment]
Why do we have the view ordering and sizing per workspace but view visibility across all workspaces?

Shouldnt all 3 be stored at user level?

**Comment by sandy081** [comment]
No reason. Making them global will make it consistent too.
