### ISSUE TITLE
Peek Window Refinements

### ISSUE THREAD

**Issue by abierbaum** [Microsoft/vscode#5120]
Based upon the feedback and development of the File Peek extension (https://marketplace.visualstudio.com/items?itemName=abierbaum.vscode-file-peek) I have a few ideas for refinements for the Peek View.  See also: #3178 for the original discussion.

  * Allow disabling "escape" in peek window.  When showing a file in the "peek" view, if the user presses escape in either view, the peek window goes away. This isn't great with this use case because someone may naturally press escape to clear the selection in one of the windows

  * Allow user to manually adjust the size of the peek window by dragging a splitter at the bottom of the peek window.

  * Allow disabling the double click behavior inside the click window. (if you double click it opens the peeked file in the editor, replacing the current file) This doesn't work very well if the user just wants to double click to highlight a word inside the peek editor

I know what I am asking about is a bit different than what the peek view was probably intended to support. I am effectively using it as a "picture-in-picture" type view to open a sub-editor inside another editor so the developer can see and edit multiple related files in context. I haven't see any editor implement this before but it seems like a pretty interesting way to allow code editing.

**Comment by egamma** [comment]
fyi @jrieken

**Comment by jrieken** [comment]
> Allow user to manually adjust the size of the peek window by dragging a splitter at the bottom of the peek window.

✅ on that. The rest will likely come as user options

**Comment by jrieken** [comment]
closing we have now

* resizable peek windows for (peek def and find ref)
* the `stablePeek` setting to disable `ESC` and double click close-behaviour inside peek editors

**Comment by abierbaum** [comment]
@jrieken Very happy to see those features added.  What version of vscode has them?

**Comment by jrieken** [comment]
The May update will have this - expect an insider update the next days maybe tonight and the final update in ~10days

**Comment by reorx** [comment]
How about keep peek editor open when switching between tabs when `stablePeek` is on? Currently it will disappear when I switch to another tab then switch back. This is disturbing if I'm doing refactoring works from the “Find All References” peek editor, I may constantly switching around, when I go back I have to run “Find All References” again.

If this is a considerable idea, I can create a new issue for this, thank you.

**Comment by niemyjski** [comment]
"Allow disabling the double click behavior inside the click window. (if you double click it opens the peeked file in the editor, replacing the current file) This doesn't work very well if the user just wants to double click to highlight a word inside the peek editor" +100000000

**Comment by niemyjski** [comment]
I just want to be able to double click on a reference and open that file without the peek preview..
