### ISSUE TITLE
Default to AND rather than OR in marketplace search

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/vscode#51207]
Please make the marketplace search use AND rather than OR when combining keywords for search.

Using OR was fine while the marketplace was very small - but it's a real problem now that there are so many extensions, making it practically impossible to narrow down your search.

For example, if I search for `scss format`, I don't expect dozens of SCSS-related extensions none of which support any kind of reformatting.

Likewise, if I search for `scss unicorns`, I don't really expect any results at all.

I understand you're just trying to make sure that every search potentially returns *something*, but it's not how search engines work in general, not what most people expect, and not really useful when you have to manually read through the descriptions of 40 extensions only one or two of which actually have the feature you're looking for.

**Comment by isidorn** [comment]
Upstream issue https://github.com/microsoft/vsmarketplace/issues/154

**Comment by isidorn** [comment]
This is fixed in latest [VS Code Insiders](https://code.visualstudio.com/insiders/). Please try it out and let us know if there are still examples where you think that search is not working.
We expect the fixed search to be in VS Code Stable start of December.
Looking forward to feedback - thanks!
