### ISSUE TITLE
Typescript / Python: Don't detect opened file and open it in second tab.

### ISSUE THREAD

**Issue by SowingSadness** [Microsoft/vscode#51209]
OS Version: Windows 10
VSCode Version: 1.24.0-insider
Фиксация f67e6397855fb25becbdf33df185f96da7fdd108
Дата 2018-06-04T20:56:48.515Z
Оболочка 1.7.12
Отрисовщик 58.0.3029.110
Узел 7.9.0
Архитектура x64

Steps to Reproduce:
1. Open folder [bugPath.zip](https://github.com/Microsoft/vscode/files/2075405/bugPath.zip)
2. Open lib/include.ts
3. Open **app.js** and click to Foo statement

![image](https://user-images.githubusercontent.com/576443/41168988-32bb82a8-6b50-11e8-877b-7bd91d2dd634.png)

This bug seems to cause that effect: https://github.com/Microsoft/vscode-python/issues/1010

In big project VSCode looks crazy and show wrong errors when you have changed dependency file in wrong tab.
I added one argument in a parent constructor then deleted it in a wrong tab. After I builded TS but the error didn't hide. And the effect is permanenty until i reload VSCode. It to annoy me very much.
![image](https://user-images.githubusercontent.com/576443/41028975-384f1aaa-6983-11e8-9884-d61e2e001b38.png)

**Comment by mjbvz** [comment]
Please test the latest VS Code insiders build. I've made a few fixes around this but do not know if your specific case was addressed

**Comment by SowingSadness** [comment]
@mjbvz hi, feels better with errors but a path detection is wrong.
[Jun 18 2018 11_09 AM.zip](https://github.com/Microsoft/vscode/files/2110467/Jun.18.2018.11_09.AM.zip)

**Comment by mjbvz** [comment]
Can you please put together a small example project that demonstrates the issue. I'd like to be able to recreate the issue on my side

**Comment by SowingSadness** [comment]
@mjbvz 
I have added example of project in the [bugPath.zip](https://github.com/Microsoft/vscode/files/2132017/bugPath.zip) and a demo record in [Jun 25 2018 9_49 AM.zip](https://github.com/Microsoft/vscode/files/2132013/Jun.25.2018.9_49.AM.zip)

**Comment by mjbvz** [comment]
Thanks. This is #12448

The issue is that you are using an uppercase path in the file reference, but on disk it uses a lowercase path. Unfortunately we are not able to recognize that these are in-fact the same file on windows, which is why you end up with two editors. The workaround is to ensure you use consistent path casing everywhere
