### ISSUE TITLE
Ctrl+e when terminal is in focus, opens `quickOpen`

### ISSUE THREAD

**Issue by thetrompf** [Microsoft/vscode#51201]
- VSCode Version: 1.23.1
- OS Version: Linux

Steps to Reproduce:

1. focus integrated terminal
2. type in a command
3. move cursor some characters to the left
4. hit `ctrl+e` 

Does this issue occur when all extensions are disabled?: Yes

The solution mentioned in #27342 is alright if you don't like the behavior altogether. But I use the `workbench.action.quickOpen` a lot and I like to not deviate from the default shortcuts, the only time I don't like the shortcut is when the integrated terminal has focus. 

I tried putting the following into `keybindings.json`:

```json5
[
    {
        "command": "workbench.action.quickOpen",
        "key": "ctrl+e",
        "when": "!terminalFocus"
    }
]
```

But it did not have any effect.

**Comment by Tyriar** [comment]
This is unfortunately the case because ctrl+e was added before the terminal was. You were pretty close to the fix, try something like this:

```
    {
        "command": "-workbench.action.quickOpen",
        "key": "ctrl+e"
    },
    {
        "command": "workbench.action.quickOpen",
        "key": "ctrl+e",
        "when": "!terminalFocus"
    }
```
