### ISSUE TITLE
Importing solc using require crashes intellisense

### ISSUE THREAD

**Issue by rado122** [Microsoft/vscode#51215]
If solc is installed using npm and being required using require('solc') intellisense crashes for the whole project. This happens on Ubuntu using: 
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by mjbvz** [comment]
Do you see this in vscode insiders?

**Comment by mjbvz** [comment]
Thanks. Confirmed and opened https://github.com/Microsoft/TypeScript/issues/24762 to track this upstream
