### ISSUE TITLE
Copy debug data in a pop-up menu (right-click)

### ISSUE THREAD

**Issue by d-sphinx** [Microsoft/vscode#51211]
Hi, during debug session it would be nice to add an ability to copy pop-up data (strings, structures, ...) to a clipboard by right-clicking on a field and selecting an appropriate item. The same way like Webstorm allows.

![2018-06-06 12_35_10-fre step processor js - workflowengine - visual studio code](https://user-images.githubusercontent.com/4455753/41030519-311f104c-6987-11e8-90db-e14cb457d5cf.png)

**Comment by isidorn** [comment]
You can do that currently in the variables view.
I like keeping the hover minimalistic with no additional context menu actions on top.

Thus closing as will not fix.
