### ISSUE TITLE
Non-relative importModuleSpecifier broken when rootDirs is present 

### ISSUE THREAD

**Issue by srcspider** [Microsoft/vscode#51210]
- VSCode Version: 1.24.0-insider (Commit b4e6fe3bd751448783ed20c8e49fdabd69514b8d)
- OS Version: Ubuntu 16.04 LTS

Assuming following workspace settings:

```
{
    "javascript.preferences.importModuleSpecifier": "non-relative",
    "javascript.preferences.quoteStyle": "single",
    "typescript.preferences.importModuleSpecifier": "non-relative",
    "typescript.preferences.quoteStyle": "single",
}
```

Steps to Reproduce:

1. Create a simple sandbox project
2. `mkdir -p runtime/core/lib/foo`
3. `echo "export class Bar {}" > runtime/core/lib/foo/bar.ts`
4. `echo "export const bar = new Bar();" > runtime/core/lib/example.ts`
5. Your `tsconfig.json` should have `"baseUrl": "./runtime"`
5. Your `tsconfig.json` should also have `"rootDirs": [ "./runtime" ]`
6. Add the `tsconfig.json` specified below
. `Ctrl+Shift+P` > Reload Window (just to make sure tsconfig.json is captured)
7. Go to example.ts and try to auto-fill import

Expected Suggestion: `import { Bar } from 'core/lib/foo/bar.ts';`
Actual Suggestion: `import { Bar } from './foo/bar.ts';`

Removing the `rootDirs` solves the problem.

If my understanding of rootDirs isn't wrong the point is to specify what should be considered the root directory when compiled outputs things like source maps? [Docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html#virtual-directories-with-rootdirs)

I am not sure why this would be an incompatible interaction. If it's intentional (for some odd reason) then there should be warnings either in the intelisense or in the workspace/global preferences that the setting will not take effect at all.

Note: In `v1.19.3` (ie. the last version that was usable before vscode became biased towards `../../../../../../../../bar.ts`) the import suggestion was not affected by the rootDirs settings

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25108
