### ISSUE TITLE
Wrong characters counter

### ISSUE THREAD

**Issue by Kleveriwe** [Microsoft/vscode#51220]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.2
kivy-vscode|Bat|0.2.0
npm-intellisense|chr|1.3.0
jquerysnippets|don|0.0.1
vscode-highlight|fab|1.2.0
tortoise-svn|fan|0.1.1
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
python|ms-|2018.4.0
vscode-jsp|pth|0.0.2
subtle-brackets|raf|2.1.1
open-in-browser|tec|1.1.0
vscode-todo-highlight|way|0.5.12

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Click "Tweet Feedback"
2. Choose 🤕 
3. Write random text with 270 chars
4. Choose 😄 
5. "Tell us why?" (**-13 characters left**)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Because a smiley will add text to the tweet.
