### ISSUE TITLE
Collapsing folded block on a single line on VSCode

### ISSUE THREAD

**Issue by jokoon** [Microsoft/vscode#51223]
https://github.com/Microsoft/vscode/issues/3353#issuecomment-300536907

This comment is about VSCode collapsing code blocks on a single line, like this

    void func() { ... }

Instead of

    void func() { ...
    }

Can it be achieved in either VSCode? I'm really looking for this feature for visualizing code in a lean fashion. MSVC does this.

**Comment by aeschli** [comment]
duplicate of #3352
