### ISSUE TITLE
Get access to DOM event from tests

### ISSUE THREAD

**Issue by DanEEStar** [Microsoft/vscode#5122]
I am really interested in vim extensions for VS Code.
So I tried to add some integration test to some already existing extensions.

In my tests I want to set the editor text at the beginning. Then I want in a high-level way "simulate" key presses. In the end I want to assert the resulting text or behavior.

I have a hard time to "simulate" the key presses.

I was looking at the vim-mode extension for the atom text editor. In its test it has direct access to the DOM document and can therefore directly call the `dispatchEvent` method and add new `KeyboardEvent`s
https://github.com/atom/vim-mode/blob/670910880797cc545e6c62422615c8d988e44e98/spec/spec-helper.coffee#L46

Can I do the same in VS Code? 
Or are there other ways/ideas to simulate keyboard input in my tests?

**Comment by jrieken** [comment]
@alexandrudima Isn't this possible with the `executeCommand`-api and the `type` commands?
