### ISSUE TITLE
Can't download plugins

### ISSUE THREAD

**Issue by AceSrc** [Microsoft/vscode#51227]
- VSCode Version: VSCode Version: 1.23.1
- OS Version: Windows 10

When downloading plugins, it always report an error:
![error](https://user-images.githubusercontent.com/22877736/41044194-40569f3e-69d8-11e8-8408-0ae461bc10de.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@dbaeumer Is it related to the bug you fixed recently in shared process?

**Comment by dbaeumer** [comment]
@sandy081 yes the first one. But it never caused a problem beside printing it to the output. So it couldn't cause failing downloading a plugin.

**Comment by sandy081** [comment]
@AceSrc Please check your `TEMP` variable and configure it correctly.
