### ISSUE TITLE
Better support drag and drop from external application into Code that deletes files on drop

### ISSUE THREAD

**Issue by amirtal** [microsoft/vscode#51229]
VSCode Version: 1.21.1
OS Version: Windows 7
Steps to Reproduce:

Open a zip file
Drag and a drop a file from the zip to the VSCode window
Unable to open 'setup.xml': File not found (file:///c:/Users/YELGUZ~1/AppData/Local/Temp/7zE8FA66FD2/setup.xml).
=> The folder 7zE8FA66FD2
new issue microsoftvscode - google chrome
doesn't exist !

Does this issue occur when all extensions are disabled?: Yes/No
Yes

this was already created as "File not found error when drag and drop from a zip file #47232"
but was closed with an evasive answer, blaming 3rd party app.
this is clearly not the case, since same issue is not present in any other text editor (notepad++, sublime text, even plain notepad.exe)

after the user stated this fact the thread is closed, why? 
was this resolved? was this confirmed?

Amir.

**Comment by bpasero** [comment]
@amirtal what zip program are you using for this?

**Comment by amirtal** [comment]
Winrar, file should be extracted to a temp folder AFAIK.

Amir

________________________________

**Comment by bpasero** [comment]
I tried WinRAR and 7Zip with different findings:
* WinRAR produces a wrong file path for me when I drop, I am not sure this is an issue with Electron (our UI framework) or WinRAR
* 7Zip produces a good file path for me in the temp directory but I get the same issue as reported that the file was not found

@amirtal it seems to me that both WinRAR and 7ZIP delete the temp file right at the moment where it is being dropped. If so, there is literally nothing VSCode can do to open that file because we only open the file after the drop operation. I would suggest to report this to the WinRAR team to ask if they can fix this.

**Comment by amirtal** [comment]
i have tested specifically with winrar.
for example, opening a rar file with an html file inside.
double-click or drag html file to chrome/firefox and the file is opened.
i can see existing folder "C:\Users\Amir\AppData\Local\Temp\Rar$EXa0.380" still exists, and file is still present inside this folder.

there are several other reports of same issue closed with similar description.
this is what differs winrar from most other zip managers: it extracts the file(s) to a temp folder and perform all actions from there, it should work just as any other file/folder.

Amir

**Comment by ngtrian** [comment]
This easy with notepad.. lol

**Comment by KargJonas** [comment]
The same issue occurs when I try to drag n' drop from the (default ) Windows "Compressed Folder Tools".

**Comment by nsgundy** [comment]
Having the same issue when dragging and dropping files from 7zip as mentioned earlier. VS code is my main editor, but for this particular use case I have to resort to others (notepad++). The couple of extra clicks to first extract the file and then drag it into VS code followed by deleting the file is too inconvenient.

**Comment by Tibus** [comment]
Why is this still not managed?

**Comment by imReker** [comment]
It's not out-of-scope, vs code is an editor an should support this simple operation just like Notepad.
