### ISSUE TITLE
Build: Flaky ripgrep download

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#51221]
There have been a couple of builds in which `ripgrep` failed to download:

- https://vscode.visualstudio.com/VSCode/_build/index?buildId=1533&_a=summary
- https://vscode.visualstudio.com/VSCode/_build/index?buildId=1534&_a=summary

Any thoughts on why this could happen?

**Comment by roblourens** [comment]
The fact that it happened in multiple builds at around the same time probably points to some hiccup on github's end? I could add something to retry if it fails, but I don't know whether it would have helped in this case.

**Comment by joaomoreno** [comment]
Got it! Let's close it then :+1:
