### ISSUE TITLE
[themes] `keywords` colorization should not include keyword.operator

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#51237]
- VSCode Version: 1.23.1
- OS Version: macOS

```
  "editor.tokenColorCustomizations": {
    "keywords": {
      "fontStyle": "italic",
    }
  },
```

It shouldn't `italic` equal sign (`=`), plus (`+`), minus (`-`), etc.

This is very cool setting instead of creating/editing existing theme I can just change `tokenColorCustomizations`, but it's weird it affects some types like equal sign, plus, minus, etc. which I believe should be as it's and don't care about `fontStyle` when applied via `keywords` in `tokenColorCustomizations`.

**Comment by svipben** [comment]
@aeschli @RMacfarlane this will be in the new release 1.25.0?

**Comment by RMacfarlane** [comment]
@svipben Yes, issues that are in the "June 2018" milestone will go into the 1.25.0 release

**Comment by svipben** [comment]
I updated VS Code and still this issue exists...

/cc @aeschli @RMacfarlane

**Comment by svipben** [comment]
Seems only this is italic.

![image](https://user-images.githubusercontent.com/10441177/42340391-94b87512-8098-11e8-9c21-2c02b5e09f74.png)

**Comment by svipben** [comment]
I created separate issue for this: https://github.com/Microsoft/vscode/issues/53688
