### ISSUE TITLE
Show keyboard shortcuts in tooltip for custom view containers

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode#51234]
The Azure extensions contribute an Azure tab for all of the extensions to reside. Right now, there does't appear to be a way to bind the view to a keyboard shortcut (e.g. Super+Shift+X for extensions).

See https://github.com/Microsoft/vscode-azureappservice/issues/457

**Comment by sandy081** [comment]
@fiveisprime There is a way to bind the keybinding...

![image](https://user-images.githubusercontent.com/10746682/41090534-c8f2a696-6a44-11e8-98e4-a7edd9cd68c5.png)

Issue is that it is not visible on hover on icon.

**Comment by sandy081** [comment]
To Verify


Simpler repro:
1. Install Docker extension
2. Reload and hover shows "Docker"
3. Close VS Code and restart
4. Now hover shows "workbench.view.extension.dockerView"
