### ISSUE TITLE
[folding] select line with folding should include folded range

### ISSUE THREAD

**Issue by fab1o** [Microsoft/vscode#51232]
- VSCode Version: 1.24.0-insider
- OS Version: MacOS

Steps to Reproduce:

1. create a region in javascript `//# region hey ..... //#endregion`
2. close the region
3. Select the region and ctrl+c
4. Paste the code

It should paste the entire code in the region like Visual Studio does with C#, but instead it only pastes the region comment

Does this issue occur when all extensions are disabled?: Yes

**Comment by fab1o** [comment]
Same in Windows

**Comment by aeschli** [comment]
To select the folded ranges you have to select up to the next line.
