### ISSUE TITLE
Workspace symbol list performs poorly for huge numbers of results

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51236]
This might be expected, but... :)

If I return around 80,000 items from my symbol provider, VS Code hangs really badly (frozen UI). It's not just JSON serialisation because getting it from my language server and parsing that JSON only takes a couple of seconds, but Code hangs for a long time.

For now, I'm going to truncate my results to about 500; however this isn't a perfect solution because VS Code doesn't allow me to give the user any indication that the results are truncated.

Some possible improvements:

1. Allow symbol providers to indicate that the results are truncated and just tag a message along the bottom of the list
2. Truncate the results yourself in Code, and tag a message along the bottom of the list
3. See if you can make it perform better :) I don't know if it's easy to profile to figure out what's slow; are all the items added into the DOM always, or just a visible slice?

Anyway, not a big deal; but it'd be good to have some guidance on this. We can't control how big the projects are that our users open so if the guidelines are to truncate the results it'd be good if that was a bit more official.

**Comment by jrieken** [comment]
Yeah, it's our tree

**Comment by joaomoreno** [comment]
Merging with #18180
