### ISSUE TITLE
synax check error

### ISSUE THREAD

**Issue by Oger-Me** [Microsoft/vscode#5123]
- VSCode Version: 0.10.11
- OS Version: Windows 10

my code like this :
{
	prev_text: '<',
	next_text:">",
	items_per_page: 6,
        ## // behind line will fire synax check error.
	**link_to: 'javascript:;',**
	callback: function(currentPage){
	}
}

**Comment by egamma** [comment]
I cannot reproduce this

![image](https://cloud.githubusercontent.com/assets/172399/14504657/f9292046-01b5-11e6-809c-492305d20a32.png)

Can you please add a screenshot of what you are seeing.

**Comment by egamma** [comment]
Cannot act on this with more information - closing, pls reopen when there is more information.

**Comment by Oger-Me** [comment]
@egamma I'm sorry. I'm late. And the latest version is ok.
