### ISSUE TITLE
Refactoring not working on Windows 10.

### ISSUE THREAD

**Issue by distante** [Microsoft/vscode#51239]
- OS Version: Windows 10 Pro (1803 - Build 17134.48)
- VSCode:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Open a complex project (in my case was an Ionic app)
2. Try to refactor some member class.

Does this issue occur when all extensions are disabled?: Yes

Example:
![Refactor is not working](https://i.imgur.com/HX5E0jp.gif)

**Comment by mjbvz** [comment]
Yes, there are no refactorings available. What is the expected behavior here?

**Comment by distante** [comment]
Hi @mjbvz, I should apologize. I completely mixed PHP Storm's (What I **have** to use at work) Refactor with VSCode's Rename Symbol. I am so sorry.

**Comment by mjbvz** [comment]
No problem. Yes, right now rename is its own action with its own menu item. We may move it under `refactorings` at some point in the future
