### ISSUE TITLE
Allow enabling color picker everywhere

### ISSUE THREAD

**Issue by hho** [Microsoft/vscode#51238]
Color codes in hex are used in many more places than just HTML/CSS. Additionally, a lot of file formats can embed HTML/CSS inside them (e.g. templating formats). It is therefore unreasonable to expect that a user has extensions for every format installed **and** every extension supports the color picker.

It would be good, if we could get an option to force the color picker enabled for the current file/all files (highlighting hex codes, showing the color square, etc).

**Comment by aeschli** [comment]
It's already an API that an extension can implement: [the color provider API](https://github.com/Microsoft/vscode/blob/d685a125b5ab5143dfcae626d590b4105d8fb21a/src/vs/vscode.d.ts#L7112).

A color provider will deliver the ranges of the colors and the allowed color formats.
This requires understanding the file format (where can be color values, where are comments or string literals).

I recommend you to write an feature request against the extension you use for your language.
Or implement an extension that does it! :-)
