### ISSUE TITLE
Opening settings.json (Command-,) on macOS causes Code to open ~ as a git repo.

### ISSUE THREAD

**Issue by plotfi** [Microsoft/vscode#51233]
- VSCode Version: 1.23.1
- OS Version: High Sierra 10.13.5 (17F77)

Steps to Reproduce:

1. Open VSCode on macOS
2. Hit Command-,

Get greeted with:

"The git repository at '/Users/foo' has too many active changes, only a subset of Git features will be enabled."

It still happens with I run code --disable-extensions but when I disable the VSCode git extension manually it goes away.

**Comment by joaomoreno** [comment]
You have run `git init` on your home folder. Delete `~/.git` if that should not be a git repository.
