### ISSUE TITLE
How to disable notification toast (The right corner popup window)?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [Microsoft/vscode#51240]
Hi, there.

All the sudden, I start to get notification when there is an error occur in my code. It's very annoying and I would like to disable it. 

<img width="993" alt="screen shot 2018-06-06 at 12 08 08 pm" src="https://user-images.githubusercontent.com/33362998/41053834-4b582872-6982-11e8-863c-b97ec7537391.png">

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by saleswhale-vincent** [comment]
@bpasero Sorry for jumping in on a closed topic but I think there's a valid use case for completely disabling toast notifications. Personally, I find the new toast notifications distracting and it really takes me out of my flow whenever one pops up.

**Comment by saleswhale-vincent** [comment]
Thanks for pointing me to the right place!
