### ISSUE TITLE
"clear console" escape sequence is checked for debug console without the escape character

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#51245]
From Microsoft/vscode-debugadapter-node#185

https://github.com/Microsoft/vscode/blob/78d7d64c5d16b8d89d1dd2b0cc7fcbe966feb48b/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L669

is checking literally `[2J` not `\u001b[2J`

**Comment by roblourens** [comment]
Thanks! Another suggestion, Chrome devtools shows a hint in the console after it's cleared, like this:

![image](https://user-images.githubusercontent.com/323878/41114781-46efaffe-6a3a-11e8-8638-3564dc9dfbde.png)

which is probably useful for knowing that there may have been output there previously. Should we consider something like that for vscode too?

**Comment by isidorn** [comment]
![screen shot 2018-06-08 at 10 24 51](https://user-images.githubusercontent.com/1926584/41147383-8f1aa49c-6b06-11e8-911b-baaaa9df2b0c.png)

fyi @weinand

**Comment by roblourens** [comment]
That sounds good. Especially because chrome devtools doesn't look for this escape code.

**Comment by roblourens** [comment]
One more thing :) 

https://github.com/Microsoft/vscode/blob/19dcc2d86952dd01deb4162143b3eee15c1e48aa/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L673

This is a literal backslash, you want `'\u001b[2J'` which is a unicode escape sequence in JS.

**Comment by weinand** [comment]
@isidorn it would help if you would verify your code by actually running it ;-)

**Comment by isidorn** [comment]
@roblourens thanks rob, I pushed a fix
@weinand thanks for the example, but I tried that and the clear does not send any console output to the vscode ux, thus I could not verify with that example (and still can not)

**Comment by weinand** [comment]
@isidorn So how should we verify this feature then?

Have you tried `console.log('hello \u001b[2J world')`?
Do you understand why npmjs.com/package/clear is failing?

**Comment by isidorn** [comment]
@weinand yes the console log example works that is how I verified
npmjs clear is failing beacuse no console output statement is coming from the debug adapter. I did not investigate inside the debug adapter as to why that is happening. I can create an independent issue if that will help?

**Comment by weinand** [comment]
@isidorn there is no need to investigate inside the debug adapter.
If you step through the few lines of "clear()" you will see that the sequence is sent to "process.stdout.write" instead of "console.log".
To capture this as Output events you have to add an `"outputCapture": "std"` to the launch config.

Try this and verify that "clear" works with your feature.

**Comment by isidorn** [comment]
@weinand thanks, after changing `"outputCapture": "std"` I can verify that the "clears" works with our feature.

**Comment by JacksonKearl** [comment]
Is the verification needed here that "Console was cleared" was printed? If so verified. But the original issue is about not checking for escape sequence correctly. Which I verified too I guess.

**Comment by roblourens** [comment]
Yeah, I guess there were two parts, is the console cleared, and does it print the message.

**Comment by JacksonKearl** [comment]
the console is cleared even when the escape sequence is in the middle of a log string, and it does print the message, and it does log the remainder of the string after the escape sequence
