### ISSUE TITLE
SCM: Improve full path readability

### ISSUE THREAD

**Issue by sarahwbs** [microsoft/vscode#51248]
When searching files, or reviewing changes to commit to a git repo, it is often impossible to tell which file is which without hovering over the file name and waiting for the tool tip to appear (which is frustratingly slow), or making the sidebar wide enough to show the full path. Please add a setting that would allow these paths to wrap to the width of the sidebar.

![screen shot 2018-05-28 at 3 48 34 pm](https://user-images.githubusercontent.com/1950127/41056212-cd8d9072-6999-11e8-8074-01bed2e78687.png)

The closest I could find to this issue is #10170, however I would like to see a feature to address this issue.

**Comment by joaomoreno** [comment]
@sarahwbs Wrapping the paths doesn't seem like a good idea to me, since it would steal space away from results and make the view overall confusing to look at. If all you need is a glance, you can always hover and see the full path. But maybe what you want is to see the end part of the path, instead of the beginning?

Would #14582 also cut it?

**Comment by sarahwbs** [comment]
I see your point about taking space away from the results... Seeing the end part of the path might be more useful, as long as the option remains to see the full path by making the sidebar wider.

Another possibility that *might* be simpler to implement is showing the tooltip on the filename a little quicker (maybe 100ms). It's hard to tell exactly but it feels like I'm waiting at least one second for that tooltip to appear, longer than it seems to take for tooltips to appear, say, in my browser.

**Comment by itamark** [comment]
Hey @joaomoreno @sarahwbs has the solution to this been resolved in any way? I'd like to take it if possible.

**Comment by sarahwbs** [comment]
So far I'm dealing with this solution my making my sidebar ridiculously wide, so please go for it!

**Comment by itamark** [comment]
@sarahwbs So here's the thing. The tooltips seem to operate as regular native HTML titles. Which means the speed with which it appears is not configurable. 
Would changing the items to two-line help? Meaning - instead of inline, have them have one line filename, the next line - path?

**Comment by joaomoreno** [comment]
Closing this as fixed with the current feature of rendering SCM as a tree.
