### ISSUE TITLE
On Command + Save VS Code Cuts Off the First Few Characters of JavaScript Code

### ISSUE THREAD

**Issue by BenCook28** [Microsoft/vscode#51244]
Issue Type: <b>Bug</b>

I wrote JavaScript code, then press command save.  I expected my code not to change.  But I realized that I lost several beggining characters after spending time checking to make sure I closed off everything.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.4.0
vscode-elixir|mjm|1.1.0
autoimport|ste|1.5.3

</details>

**Comment by mjbvz** [comment]
Does this repo if you disable all extensions? Prettier and autoimport both could cause this

**Comment by BenCook28** [comment]
The bug still happened when I disbled prettier-vscode.

**Comment by BenCook28** [comment]
Thanks mjbvz, I disabled the other two extensions just in case, and I'll keep you posted.

**Comment by BenCook28** [comment]
I don't seem to have the bug now, but I updated many JavaScript files and the bug only happened on two or three of them when I reported the bug.
