### ISSUE TITLE
There is no document formatter for 'html'-files installed

### ISSUE THREAD

**Issue by vitaliydz** [Microsoft/vscode#51243]
Issue Type: <b>Bug</b>

Trying format my html file Crl+Alt+F and receive this message: 
"There is no document formatter for 'html'-files installed."

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
angular2-snippets|dan|1.0.19
Angular-BeastCode|Mik|6.0.15
angular2-inline|nat|0.0.17

</details>

**Comment by aeschli** [comment]
I can't reproduce as the built-in HTML support has a formatter which is installed by default.
There are two ways of disabling it:
- `"html.format.enable": false`
- disable the built-in 'HTML Language Feature` extension.

Can you check in your settings and in the extensions viewlet that this is not the case?

Also, in an editor that shows an HTML file, is the 'Format' action available in the context menu?

**Comment by vitaliydz** [comment]
@aeschli it's my bad.
Thx for your time!
I didn't see next tab 'WORKSPACE SETTINGS' after 'USER SETTINGS'. In that tab property "html.format.enable" was false. 
But, I didn't manualy change the property (I event didnt know that I can).
The same problem at my laptop too and I suggest it can be caused one of extension.
