### ISSUE TITLE
copy navigate lines in files opened

### ISSUE THREAD

**Issue by gilberto389** [Microsoft/vscode#5124]
I have many
![b2](https://cloud.githubusercontent.com/assets/1904029/14407950/04025376-fea4-11e5-8ba0-a29215e4dbf0.png)
 windows open:
window "1" and window "2" if I am in the "1" at the beginning, I'm reviewing the first few lines, if I open the window "2" and navigate to the end of the file, when I open the window "1" NOW it shows the final lines when I was seeing was the beginning of the file, it's annoying when you have many files and need not miss in network calls, functions, variables, etc.

- VSCode Version:0.10.11
- OS Version:win 7 64 bits, sp1
- JS files (canvas game development)
Steps to Reproduce:

1. open two files (these have more than 500 lines) Position yourself at the beginning of the first .
2. the second fence and navigate to the last lines.
3. reopen the other and see how it is now showing the last lines.

**Comment by bpasero** [comment]
@gilberto389 from your description I have no clue what the bug is, please attach a video.

**Comment by gilberto389** [comment]
whether it is because it happens, the problem is that when you return to the previous window, the program places the window so that shows the position of the cursor, NOT far as I surfed, say I'm with the cursor on the line 1, I navigate to line 1000 but failed to place the cursor on that line but just needed to see it, then I click on another file, when I go the screen is located so that shows me the line 1 and not the line 1000 which is I am analyzing.

Now, the solution would then click there and ready, not where it comes from that philosophy (policy, directive or whatever) but is the first editor I see doing that.

I used sublime, notepad ++, and brackets.

**Comment by bpasero** [comment]
@gilberto389 are you switching windows with Alt+Tab or something else? I am still not sure I understand.

**Comment by gilberto389** [comment]
ok, i sent a video:
https://drive.google.com/file/d/0Bwx5lO1eBkVQcDhRSXpOS0VPUE0/view?usp=sharing

**Comment by bpasero** [comment]
@gilberto389 thanks, so the issue in the video I see is that you scrolled down in the one file and when you click back into it, the scrolling position is not restored. Is that what you are complaining about?

**Comment by gilberto389** [comment]
yes, would click in the position just want to analyze, as once I have a lot of open files, a click that save me in every review I is helpful.

**Comment by bpasero** [comment]
Which VS Code version do you use?

**Comment by gilberto389** [comment]
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version 0.10.11
Commit f291f4ad600767626b24a4b15816b04bee9a3049
Date 2016-03-11T17:10:35.304Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

[OK]

2016-04-13 2:47 GMT-05:00 Benjamin Pasero <notifications@github.com>:

> Which VS Code version do you use?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/5124#issuecomment-209286947>
>



-- 
Gilberto Fandiño Barbosa
Desarrollador de videojuegos en HTML5
Diseño 2D (Inkscape /gimp )
Programador BackEnd (php/mysql)

**Comment by bpasero** [comment]
Weird. Does it reproduce from our insiders release? 
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by gilberto389** [comment]
Well, not if you have to see, initially I was using brackets.io so the working folder does not believe from scratch in Vs Code.

abri entire folder:

File-> Open-> folder

**Comment by gilberto389** [comment]
**ok, very well, many thanks**

When you select a code snippet if repositions the focus, that if it makes sense (at least to me)

[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]

Versión 0.10.15-insider
Confirmación 67567498285c2081312077cc24370d97676fc20a
Fecha 2016-04-11T10:56:21.409Z
Shell 0.35.6
Representador 45.0.2454.85
Node 4.1.1

[Aceptar]

**Comment by bpasero** [comment]
@gilberto389 sorry, having issues understanding, you say this is good now with insiders?

**Comment by gilberto389** [comment]
with insider works very well, thanks

**Comment by bpasero** [comment]
Great :+1:
