### ISSUE TITLE
Suddenly can't use breakpoints on TypeScript file (source map error)

### ISSUE THREAD

**Issue by Eduardogbg** [Microsoft/vscode#5125]
- VSCode Version: Newest
- OS Version: Windoes 10

Steps to Reproduce:

1. Create a project with the files in the following repository:
https://github.com/Eduardogbg/vscode-issue-sample
2. Try to set a breakpoint on the .ts file

OBS: I also uploaded the task file used to create the transpiled javascript and its respective source map, because maybe the error is in the process of generating the source map, idk.

@Edit 
As reported in my repository, everything is fine with Insider's version.

**Comment by egamma** [comment]
>As reported in my repository, everything is fine with Insider's version.

We will push the insiders version to stable this week, no further action on this planned on this one for now. // @isidorn @weinand

**Comment by Eduardogbg** [comment]
Alright, thanks!
