### ISSUE TITLE
[CLI] `-r` parameter  is ignored when file folder is open in another window

### ISSUE THREAD

**Issue by MarekLew** [Microsoft/vscode#51254]
Issue Type: <b>Bug</b>

If I create folders A and B and file a.txt in A:

0. prepare folders and file
`mkder A;mkdir B`
`echo  B/a.txt>B/a.txt`

1. `code B` 
active window B
2. `code A` 
active window A
3. `code -r B/a.txt`
Open `B/a.txt` in B but not in A (ignore -r {Force to open a file or folder in the last active window})

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz (4 x 1288)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|3.77GB (1.29GB free)|
|Process Argv|/usr/share/code/code A|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.55
vs-treeview|DaG|2.5.0
vsc-material-theme|Equ|2.1.0
virtual-folders|Gru|0.1.2-b1
taskmarks|Nor|0.6.1
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
code-gnu-global|aus|0.2.2
spellright|ban|2.5.0
npm-intellisense|chr|1.3.0
python-snippets|cst|0.2.0
jshint|dba|0.10.18
vscode-eslint|dba|1.4.10
gitlens|eam|8.3.3
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
LogFileHighlighter|emi|2.4.0
git-project-manager|fel|1.6.1
favorites|kdc|1.4.4
vscode-gist|ken|1.2.0
git-tree-compare|let|1.2.1
cmake-tools-helper|mad|0.2.1
MagicPython|mag|1.0.12
vscode-checkpoints|mic|1.0.1
vscode-clang|mit|0.2.2
quicksnippet|mou|0.0.1
hg|mrc|1.2.3
python|ms-|2018.4.0
cpptools|ms-|0.17.4
vscode-code-outline|pat|0.2.1
annotator|ryu|0.11.0
partial-diff|ryu|1.1.0
guides|spy|0.9.1
python|tht|0.2.3
cmake|twx|0.0.17
cmake-tools|vec|0.11.1
gitflow|vec|1.2.1
local-history|xyz|1.6.2

</details>

**Comment by bpasero** [comment]
Yeah that is sort of working as designed because we can provide the best working environment for a file if it is opened in the context of the folder (e.g. for language services to do the right thing). I would feel not easy to make a change here.

**Comment by MarekLew** [comment]
Please change documentation "--diff force to open a file or folder in the best active window" or some semilar.

**Comment by MarekLew** [comment]
@bpasero " I would feel not easy to make a change here" 
I find this in 15 minutes.
https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/windowsFinder.ts#L34

```
export function findBestWindowOrFolderForFile<W extends ISimpleWindow>({ windows, newWindow, reuseWindow, context, filePath, userHome, codeSettingsFolder, workspaceResolver }: IBestWindowOrFolderOptions<W>): W | string {
	if (!newWindow && filePath && (context === OpenContext.DESKTOP || context === OpenContext.CLI || context === OpenContext.DOCK)) {
+                if  (reuseWindow) return getLastActiveWindow(windows);
		const windowOnFilePath = findWindowOnFilePath(windows, filePath, workspaceResolver);
		if (windowOnFilePath) {
			return windowOnFilePath;
		}
	}

	return !newWindow ? getLastActiveWindow(windows) : null;
}
```

**Comment by MarekLew** [comment]
@bpasero "Yeah that is sort of working as designed because we can provide the best working environment for a file if it is opened in the context of the folder (e.g. for language services to do the right thing). I would feel not easy to make a change here". Context file is the problem. When I open '--diff' then is opened in first file context, but editale is second file. This is wrong file context and I don't  change this becouse '-r' not work.

**Comment by MarekLew** [comment]
I compile VSC and my solution work correct:
```
if  (reuseWindow){
 return getLastActiveWindow(windows);
}
```
You can add a paramert to search for the best window:
`-b, --best-window                 Force to open a file or folder in the best active window.`

**Comment by MarekLew** [comment]
https://github.com/MarekLew/vscode/commit/a60bcc53c6241e4dd25f05f4d826908e78ce1a29
