### ISSUE TITLE
JSX: Collapse icons are disappear

### ISSUE THREAD

**Issue by imakou** [Microsoft/vscode#51266]
- VSCode Version 1.24.0 (1.24.0)
- OS Version: MacOS 10.13.4

Steps to Reproduce:

![screen shot 2018-06-06 at 6 06 05 pm](https://user-images.githubusercontent.com/1507950/41067697-88af8508-69b4-11e8-8068-0ddd5c3af322.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This was never officially supported, see https://code.visualstudio.com/updates/v1_24#_syntax-aware-folding-enabled-by-default-for-jsts

Syntax aware support for this is tracked by https://github.com/Microsoft/TypeScript/issues/23273

**Comment by 1412108** [comment]
I have never had this error in previous version @@ 
Now I had

**Comment by mjbvz** [comment]
It only worked because it happened to be indented (which is how all folding used to work). If you had a line:

```ts
const a = <div>
<a>
</a>
</div>
```

You'll notice the folding never worked

**Comment by ggregoire** [comment]
Solution from another issue: `"typescript.experimental.syntaxFolding": false`

**Comment by ChessMess** [comment]
Unfortunately release 1.25 took away the "typescript.experimental.syntaxFolding": false setting change solution and kept the non-working folding :(

**Comment by ggregoire** [comment]
Replace 

`"typescript.experimental.syntaxFolding": false`

with 

```
"[javascript]": {
  "editor.foldingStrategy": "indentation"
},
"[javascriptreact]": {
  "editor.foldingStrategy": "indentation"
},
"[typescript]": {
  "editor.foldingStrategy": "indentation"
},
"[typescriptreact]": {
  "editor.foldingStrategy": "indentation"
}
```

**Comment by Vladmel1234** [comment]
This one also resolving the issue 
`  "editor.foldingStrategy": "indentation"`
