### ISSUE TITLE
JavaScript syntax hilighting error - labeled block

### ISSUE THREAD

**Issue by mrjacobbloom** [Microsoft/vscode#51264]
When editing a js file, unlabeled blocks work fine:
![image](https://user-images.githubusercontent.com/2879020/41066477-293972b0-699f-11e8-99e8-6d9ee0efba4e.png)
But as soon as you add a label, things highlight incorrectly:
![image](https://user-images.githubusercontent.com/2879020/41066521-4955465a-699f-11e8-97c9-9b5fb6c0290d.png)

- VSCode Version: 1.23.1
- OS Version: Win10 Enterprise

Steps to Reproduce:

1. Create a new file
2. Set the Language mode to JavaScript
3. Add curly brackets
4. Between the brackets, add any valid JS code

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Seems fixed in vscode 1.25 insiders:

<img width="404" alt="screen shot 2018-06-06 at 3 10 25 pm" src="https://user-images.githubusercontent.com/12821956/41067830-dca28976-699b-11e8-91b2-c9e3a8e18e2c.png">
