### ISSUE TITLE
Automatically update Linux repository packages

### ISSUE THREAD

**Issue by AndreasBackx** [Microsoft/vscode#51267]
Using Arch Linux as an example, @dcelasun currently seems to handle the AUR packages for the stable and insider builds. This seems like it could be integrated into the deployment of new releases which could lead to faster availability for Arch Linux users. The latest insiders builds could then also be tested by Arch Linux users.

This could then also be done for other Linux distros? This could be merged with #5458 where @Tyriar mentions that he'd like to add the Ubuntu snap to the CI/CD so it's automatically deployed I assume.

**Comment by dcelasun** [comment]
There has been [some discussion](https://github.com/Microsoft/vscode/issues/6495#issuecomment-220158936) around this topic in the past. While officially publishing a snap/flatpack etc. is a good idea, I think distro specific packaging should still be done by distros and their users.

For Arch Linux, the [insiders build](https://aur.archlinux.org/packages/visual-studio-code-insiders) always fetches the latest build (see [pkgver](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=visual-studio-code-insiders#n22)) so I don't have to release a new version for every build.

**Comment by Tyriar** [comment]
I've been struggling to get the time to finish off the snap support, so I completely agree with @dcelasun 😄
