### ISSUE TITLE
On Fedora many times when I switch windows, the scroll position seems to reset

### ISSUE THREAD

**Issue by g0dkar** [Microsoft/vscode#51269]
Issue Type: <b>Bug</b>

I'm editing a `.yaml` file and often after I switch windows to read some documentation or something, when I get back to VSCode, **sometimes** the window seems to have scrolled randomly, sometimes up sometimes down (when this happens, the caret is never on the screen). I have to move the caret to actually get back where it was supposed to be.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.16.13-300.fc28.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3526)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.53GB (4.10GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.7.0
vscode-eclipse-keybindings|alp|0.9.7

</details>

**Comment by alexandrudima** [comment]
@g0dkar Can you please give some reproducible steps? I cannot reproduce when switching windows or applications.

**Comment by g0dkar** [comment]
I'll try recording it to show you. Unfortunately, the steps to reproduce are pretty much those x_x

It might be related to using the mouse scroll on other windows (on Firefox, for example) then alt-tabbing back to VSCode.

**Comment by alexandrudima** [comment]
Hmm, I wonder if our window receives the scroll events and scrolls while you are scrolling in a different one...
