### ISSUE TITLE
Copies of extensions after update - no deleting previous extension

### ISSUE THREAD

**Issue by ManPython** [Microsoft/vscode#51270]
I noticed that in my catlog \.vscode\extensions exist many versions after update, eg.
ms-python.python-2018.3.1
ms-python.python-2018.4.0
ms-python.python-2018.5.0

- VSCode Version: 1.24.0  / from .zip

- OS Version:W7 x64 SP1

Steps to Reproduce:

1. Just do some update of extension as new version
2. Run extension manager, update to new version

Is this normal?
Why update not deleting previous?

**Comment by ManPython** [comment]
Maybe we need some list of instaled plugins. Not only dir /p

**Comment by sandy081** [comment]
@ManPython We do the extensions clean up during the start up of VS Code. So restarting the VS Code will remove the outdated extensions.
