### ISSUE TITLE
Xamarin project error

### ISSUE THREAD

**Issue by PierBover** [Microsoft/vscode#5127]
- VSCode Version:0.10.11
- OS Version: 10.11.3

Steps to Reproduce:

1. Create a blank cross platform Xamarin project
2. Open the project folder in VSCode

I get this error in VSCode

```
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] Error initializing task MakeDir: Could not load file or assembly 'Xamarin.iOS.Tasks.Core' or one of its dependencies
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Failed to process project file '/Users/pier/Projects/TestHTTP/iOS/TestHTTP.iOS.csproj'.
[ERROR] Error: Failed to start OmniSharp
```

The project builds fine in Xamarin btw.

**Comment by egamma** [comment]
moving to omnisharp-vscode for investigation.

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#167
