### ISSUE TITLE
Unable to set breakpoint outside initial launch module 

### ISSUE THREAD

**Issue by ldesegur** [Microsoft/vscode#51278]
I have installed the node project "Parsoid" from its source repo (https://github.com/wikimedia/parsoid)

I opened the project root dir with latest VSCode then added this basic pass thru config.yaml:

> > worker_heartbeat_timeout: 300000
> > 
> > logging:
> >     level: debug
> > 
> > services:
> >   - module: lib/index.js
> >     entrypoint: apiServiceWorker
> >     conf:
> > 
> >         # Configure Parsoid to point to your MediaWiki instances.
> >         mwApis:
> >         - # This is the only required parameter,
> >           # the URL of you MediaWiki API endpoint.
> >           uri: 'https://en.wikipedia.org/w/api.php'
> >           domain: 'en.wikipedia.org'  # optional
> > 
> 

I can run the app with:

http://localhost:8000/en.wikipedia.org/v3/page/html/Apple
I am now ready to inspect the code with the debugger. I add this launch.json:
```

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/bin/server.js"
        }
    ]
}


```

When I launch with the debugger, the breakpoint I added to bin/server.js is recognized. However, anything outside this dir is ignored (stating that it can't verify the other breakpoints).

[Image](https://i.stack.imgur.com/i5Qdo.png)

Only initial launch module has its breakpoint bounded.

These breakpoints are set but not bounded. What should I modify in my config file to get them bounded?

- VSCode Version:
Version 1.23.1 (1.23.1)

- OS Version:
macos 10.13.4

Does this issue occur when all extensions are disabled?: Yes

**Comment by albertosantini** [comment]
Same issue here about the breakpoints not bounded.

I think it is related to the starting folder.

For instance, you cannot debug a package **linked** in `node_modules`: the breakpoints are set, but not bounded.

 - mylib
 - myproject
    - node_modules
      - link to mylib (`npm install ../mylib` in myproject folder)


Setup

- VSCode Version:
    Version 1.24.1

- OS Version:
    Windows 10

See also https://github.com/Microsoft/vscode/issues/48713.

This is a distinct issue; anyway reading https://github.com/Microsoft/vscode/issues/46913#issuecomment-377313319
> The issue with the breakpoint starting out gray, then turning red once it's hit, it expected if the code is not actually loaded initially. The breakpoint only turns red once it's bound to a real location in loaded code.

Any hint?

**Comment by albertosantini** [comment]
Sorry for the noise.

At least, in my scenario, I resolved the issue adding to `launch.json`

```
{
    "runtimeArgs": [
        "--preserve-symlinks"
    ]
}
```
reading https://github.com/Microsoft/vscode/issues/51588#issuecomment-397213633

Anyway I continue to experiment the issue for the code not actually loaded initially.
