### ISSUE TITLE
Some Hangul syllables are not properly displayed

### ISSUE THREAD

**Issue by DannyuNDos** [Microsoft/vscode#51276]
Issue Type: <b>Bug</b>

갈(U+AC08) is displayed as 가ㄹ(U+AC00 U+3139). 감(U+AC10) is displayed as 가ㅁ(U+AC00 U+3141). 강(U+AC15) is displayed as 가ㅈ(U+AC00 U+3148).
Yet the executables built with Code seem okay.
I'm unsure whether any other syllables are not properly displayed.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.15.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1191)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.65GB (3.55GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
language-haskell|jus|2.5.0

</details>

**Comment by Tyriar** [comment]
Cannot repro on 1.28 Insiders/macOS:

<img width="401" alt="screen shot 2018-09-20 at 9 55 45 am" src="https://user-images.githubusercontent.com/2193314/45834174-5d98c780-bcbb-11e8-9232-270b3c7e618b.png">

Let us know if you still see it happening or if there are additional repro steps.
