### ISSUE TITLE
cursorWordStartLeft etc. do not manage undo history properly

### ISSUE THREAD

**Issue by zeromus** [microsoft/vscode#51275]
- VSCode Version: 1.23.1
- OS Version: Windows 7

Steps to Reproduce:

1. Make a new document
2. enter this: `foo bar baz`
3. ctrl+left twice; the cursor should be before bar.... that is: `foo |bar baz`
4. type `q` so we have `foo q|bar baz`
5. hit ctrl+z
6a. result: `foo bar|`
6b. expected result: `foo |bar baz`

Compare to visual studio, firefox.

You will also notice a discrepancy between how those others do things, and how you're likely to end up doing it. I do not object to this discrepancy.

Subsequent undo steps in FF, VS: `foo |bar baz`, `<empty string>`
Subsequent undo steps in chrome: buggy and apparently nondeterministic
Likely to be subsequent steps in VSCode, ideally, after bug is fixed: `foo |bar baz`, `foo bar|`, `foo|`, `<empty string>`

Additional steps, as justification--you can see why the behaviour is expected by considering ctrl+left to be a shortcut for hitting left several times:

7. After typing `foo bar baz` press left until you get to `foo |bar baz`
8. type `q` so we have `foo q|bar baz`
9. repeat undoing and watch it work as "likely to be subsequent steps in VSCode, ideally, after bug is fixed"

Does this issue occur when all extensions are disabled?: Yes

**Comment by cedric05** [comment]
+1

**Comment by rebornix** [comment]
@alexandrudima knows how we manage undo stops ;)

**Comment by alexandrudima** [comment]
Yeah, it looks like word navigation does not push a new element in the undo stack...
