### ISSUE TITLE
Compiling vscode should not run out of file handles

### ISSUE THREAD

**Issue by clarcharr** [Microsoft/vscode#51272]
- VSCode Version: 1.23.1
- OS Version: Arch Linux (latest)

Reproduce via:

```
cower -d code
cd code
makepkg -is
```

Right now, `nofile` is set to 4096, which is the default. I have never reached this limit under any program, ever, except when compiling vscode. I think that asking people to raise the limit is reasonable, but when I first log into a TTY and run these commands I still reach the limit. The compilation scripts should definitely be refactored to use file handles more efficiently so that a bare system can compile vscode without any special configuration changes.

**Comment by joaomoreno** [comment]
Sorry, we won't _fix_ this any time soon. Please increase your file handle limit if you want to compile vscode.

**Comment by clarcharr** [comment]
Users shouldn't have to have administrator-level access to their systems in order to compile an IDE. I understand that this is not a priority, but it is definitely a bug.
