### ISSUE TITLE
TS Server breaks after format file

### ISSUE THREAD

**Issue by mgambati** [Microsoft/vscode#51279]
- VSCode Version: 1.23.1
- OS Version: Windows 10 

Steps to Reproduce:

1. Install prettier extension and create ts file.
2. Save the file, mess up formatting and format file.

Reproducing this bug will not always work, but I reproduced it on 2 machines. TS Server logs looks normal, no error or warning.

Restarting TS Server restores it to normal behavior, sometimes changing line ending restores it too.

Since it doesn't look like a prettier bug i'm reporting here.

![image](https://user-images.githubusercontent.com/813131/41074319-90a65590-69d5-11e8-9c36-6adf54473f2d.png)

**Comment by mjbvz** [comment]
I'm unable to reproduce this issue in the current insiders build with the latest prettier. Can you please try upgrading to test this again. If you still see this issue, can you please share an example file the breaks the server on format

Thanks

**Comment by mgambati** [comment]
Managed to fix somehow. Removed all configs and extensions and uninstalled then installed again.
