### ISSUE TITLE
Can we support printing TypeScript signature hints?

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/vscode#51281]
I found this feature supported by `Ocaml and Reason IDE` plugin enhanced the experience in writing ReasonML much better.
Considering TypeScript IDE tools is built-in in VScode, there is the request that adding such signature hints.

![image](https://user-images.githubusercontent.com/1303154/41075941-9de2224a-6a41-11e8-989b-210bb4e43d37.png)

**Comment by mjbvz** [comment]
[This extension](https://marketplace.visualstudio.com/items?itemName=MartinJohns.inline-types) already implements something similar to what you propose

Closing as extension candidate. We may revisit this in the future but have no plans on adding it to core vscode
