### ISSUE TITLE
可以让 emmet 支持行内样式吗

### ISSUE THREAD

**Issue by ok2fly** [Microsoft/vscode#51283]
Issue Type: <b>Feature Request</b>

可以让 emmet 支持行内样式吗

<div style="bg#c"></div>  例如这样在style属性里面 按 tab  键， emmet 不起作用

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17133

Google translate:

> Can emmet support inline styles? For example, if you press the tab key inside the style attribute, emmet will not work.

**Comment by ramya-rao-a** [comment]
Emmet does work in style attributes

![style](https://user-images.githubusercontent.com/16890566/41115994-f52b2212-6a3d-11e8-9abc-1c2f52e228f3.gif)

Have you set `emmet.triggerExpansionOnTab` to `true`?
