### ISSUE TITLE
will clear endregion tag when delete all unsed declarations

### ISSUE THREAD

**Issue by cipchk** [Microsoft/vscode#51288]
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. A minimal reproduction of angular component file.

```ts
import { Component, Input, HostBinding, OnInit, OnChanges } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-demo',
  template: ``,
})
export class DemoComponent {
  // region: files

  @Input() name: string;

  // endregion

  private _cls = true;

  constructor(private http: HttpClient) {}
}
```

2. Delete all unsed declarations

```ts
import { Component, Input } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-demo',
  template: ``,
})
export class DemoComponent {
  // region: files

  @Input() name: string;


  constructor() {}
}
```

Result destroyed `region` tag integrities.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/24758 to track this upstream
