### ISSUE TITLE
Cannot read property 'fsPath' of null

### ISSUE THREAD

**Issue by swarmchen** [Microsoft/vscode#51289]
when i was uploading.....

Cannot read property 'fsPath' of null

sftp  bug

**Comment by aeschli** [comment]
We need a stacktrace to find out more here...

Are you saying that happend while using a command from the `sftp` extension?
If yes, please file the issue against that extension (and close this issue).

**Comment by caneco** [comment]
Yes… it's from that extension

PS: getting the same thing here :)

![image](https://user-images.githubusercontent.com/502041/41095136-654fe690-6a48-11e8-8caa-1138cb3ee838.png)
