### ISSUE TITLE
Update vscode makes extension view in browser failed

### ISSUE THREAD

**Issue by aeoluswing** [Microsoft/vscode#51291]
Application updates results in failure of running extension.

- VSCode Version: 1.24.0
- OS Version: windows7 EE SP1

Steps to Reproduce:
1. Update Application Version (From 1.23.1 to 1.24.0).
2. Restart VSCode.
3. Edit any html file.
4. Trigger the extension view in browser.

Steps above will cause a failure,error message:Running the contributed command:'extension.viewInBrowser' failed.

**Comment by sandy081** [comment]
@aeoluswing This command is coming from an extension. Please file an issue against the extension that owns this command.
