### ISSUE TITLE
1.24 broke/removed markdown support for base64 data URIs in CompletionItem & Hover 

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#51290]
- VSCode Version: 1.24
- OS Version: Windows 10 Pro 64-bit

It would seem that the most recent update broke a feature that I was (ab)using to render images in CompletionItemProvider and HoverProvider: The base64 encoded image is no longer displayed:
![image](https://user-images.githubusercontent.com/4705573/41080227-208fd282-6a2e-11e8-96ae-cefdf4deb1bf.png)

In previous version, it worked like this:

![gif](/Janne252/vscode-fontawesome-auto-complete/raw/master/video/demo-autocomplete.gif)

This functionality can be tested with [vscode-fontawesome-autocomplete](https://github.com/Janne252/vscode-fontawesome-auto-complete)

1. Install the extension
2. Create a new `.html` file
3. Start typing `fa` and browse the auto-completion items. Expand the documentation by clicking the blue `i` button if necessary.

**Comment by mjbvz** [comment]
Looks like your data uri contains spaces. I don't know why this worked previously but it likely should not have. Try either percent encoding it or base64 encoding it

Other extensions using data-uri images (such as color info) seem to work fine in the latest release

**Comment by Janne252** [comment]
@mjbvz Thanks for the quick response, base64 encoding the image data indeed fixed the issue.

Off-topic note:
I guess the markdown rendering engine was updated? Not really an issue but it seems that tables no longer render properly if the heading row cells only consist of spaces. Apparently adding a `&nbsp;` to the first header cell fixes that.
