### ISSUE TITLE
Numbers like 10e15 should be highlighted as any other numbers

### ISSUE THREAD

**Issue by huttarichard** [Microsoft/vscode#5129]
if you type in *.js file for example `10e15`, it looks like variable rather ten number

**Comment by matheusmonte** [comment]
I think I know how to solve this, I will try

**Comment by matheusmonte** [comment]
the current production version happens, but not happens development version. I think in the next build everything will be ok

**Comment by aeschli** [comment]
Yes, looks like this got fixed in the grammar. It's in the coming release (preview available at https://code.visualstudio.com/insiders)
