### ISSUE TITLE
Smoketest: Flaky debug test

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#51296]
https://vscode.visualstudio.com/VSCode/_build/index?buildId=1581&_a=summary

```
2018-06-07T00:30:31.6728030Z   1) Test Debug configure launch json:
2018-06-07T00:30:31.6745390Z      Error: Timeout: get text content ' .monaco-editor[data-uri$="launch.json"] .view-lines' after 20 seconds.
2018-06-07T00:30:31.6762090Z       at out/vscode/code.js:142:23
2018-06-07T00:30:31.6777110Z       at Generator.next (<anonymous>)
2018-06-07T00:30:31.6791700Z       at fulfilled (out/vscode/code.js:8:58)
2018-06-07T00:30:31.6806720Z       at <anonymous>
```

@isidorn This is a new one, never saw it before. Failed on macOS.

[build-artifacts-darwin.zip](https://github.com/Microsoft/vscode/files/2079230/build-artifacts-darwin.zip)

**Comment by joaomoreno** [comment]
Looks like missing file events once more, since we [write to `launch.json` in disk](https://github.com/Microsoft/vscode/blob/master/test/smoke/src/areas/debug/debug.test.ts#L26) and just wait for it to appear in the editor. :cry:

**Comment by bpasero** [comment]
Yeah, do not rely on file events in tests.

**Comment by isidorn** [comment]
Oh my.
I can change the test to wait for a tab appearing with the title `launch.json`

**Comment by bpasero** [comment]
You can force load from disk by executing the File > Revert File command.

**Comment by isidorn** [comment]
@bpasero ok, I will try that, thanks

**Comment by isidorn** [comment]
Works nicely, thanks Ben for the tip

**Comment by joaomoreno** [comment]
No thanks to Joao for the issue, investigation and fix idea. 😢 

![sadness](https://media.giphy.com/media/10tIjpzIu8fe0/giphy.gif)

**Comment by isidorn** [comment]
Thanks Joao
![image](https://user-images.githubusercontent.com/1926584/41106186-d2a52b3e-6a6f-11e8-894d-e92410a44044.png)
