### ISSUE TITLE
tasks.json doesn't expand command substitution

### ISSUE THREAD

**Issue by lightgoleft** [Microsoft/vscode#51294]
Issue Type: <b>Bug</b>

I tried to do command substitution for tasks, like: 

{
      "label": "echo",
      "command": "echo",
      "args": [
        "${command:cmake.launchTargetPath}"
      ],
      "type": "shell",
      "problemMatcher": []
    }

But the substitution neither trigger the command nor replace it with returned result. results: 

> Executing task: echo ${command:cmake.launchTargetPath} <

But command substitution in launch.json works as expected. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3796)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.58GB (10.24GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
code-settings-sync|Sha|2.9.2
android-dev-ext|ade|0.5.0
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
code-gnu-global|aus|0.2.2
gitlens|eam|8.3.4
CppSnippets|har|0.0.13
task-master|ian|0.1.39
python|ms-|2018.5.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
cmake|twx|0.0.17
cmake-tools|vec|1.0.0
debug|web|0.22.0

</details>

**Comment by dbaeumer** [comment]
Dups #47585
