### ISSUE TITLE
"Your Code installation appears to be corrupt. Please reinstall."

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51295]
Here's what I did:

- Opened Code to do some work this morning (I was not on the new version)
- Code downloaded the update in the background and showed a (1) badge in the sidebar - I didn't install it 
- Launched dev extension host to test my extension
- Quit dev extension host
- Quit main code Window
- Opened Code
- Clicked Check for Updates

Then I saw "Your Code installation appears to be corrupt. Please reinstall.". I don't know if the last step was required to cause this, or whether this is reproducible this way.

**Comment by DanTup** [comment]
Oh, but the "Restart to Update" option was still on the sidebar, so I clicked it, and it seems to have updated and work fine. Not sure whether the dialog was buggy, or it really was corrupt, and finishing the update just happened to have been the same as a reinstall.

In any case, I don't think this should happen.

**Comment by aeschli** [comment]
That message is shown when we detect that a file in the installation got modified. Any chance that happend? Some extensions try to go around API boundaries my changing the VSCode source code.

**Comment by DanTup** [comment]
@aeschli The only extensions I have installed are:

- Dart (mine, definitely doesn't do this)
- Extension Manifest Editor (Microsoft DevLabs)
- TSLint (egamma)
- VS Live Share (MS, also disabled)

So I don't think it's likely any of them were modified. I don't know if launching the dev extension host might do weird things when there's a pending update though - could it have started trying to install it?

**Comment by aeschli** [comment]
I guess without reproducible steps there is not much we can do. Closing for now. I'm happy to reopen if we get more similar reports.
