### ISSUE TITLE
One of my file myteriously rolled back to it's earlier version after update

### ISSUE THREAD

**Issue by Akumzy** [Microsoft/vscode#51301]
Issue Type: <b>Bug</b>

So I update my vscode yesterday being 06-06-2018 and today being 07-06-2018 (DD-MM-YYYY)
I boot up my local node server and started getting an error log on terminal  and I noticed that this particular file content is not of yesterday or two days before yesterday.
I don't know how that happened.

How to reproduced ? I don't know 

VSCODE version: 1.24 (lastest version)
NODE version: 10.3.0
OS : Ubuntu 18.04 LTS

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.15.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz (4 x 1209)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.69GB (1.05GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
bracket-pair-colorizer|Coe|1.0.58
minify|Hoo|0.3.0
uikit-3-snippets|Ken|1.2.2
emoji|Per|0.0.3
nativescript|Tel|0.7.4
Bookmarks|ale|0.19.1
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitlens|eam|8.3.4
vscode-great-icons|emm|2.1.33
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.7
dotenv|mik|1.0.1
python|ms-|2018.5.0
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.5.0
vetur|oct|0.12.5
laravel-blade|one|1.18.0
polacode|pnp|0.2.2
live-sass|rit|1.3.0
LiveServer|rit|4.1.0
vue-vscode-extensionpack|sdr|0.1.2
vue-vscode-snippets|sdr|1.3.0
markdown-preview-enhanced|shd|0.3.5
vscode-status-bar-format-toggle|tom|1.3.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.6.0
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.4.0

(3 theme extensions excluded)

</details>

**Comment by Akumzy** [comment]
I just noticed, I still have compiled version of the file with every changes I have made intact

**Comment by bpasero** [comment]
Sorry for that, but without good steps to reproduce there is not much I can look into.
