### ISSUE TITLE
Add the function relationship call graph function

### ISSUE THREAD

**Issue by MRkuan** [Microsoft/vscode#51306]
When I open a C language project using vscode, I want to know the relationship between the function call and being called, but it seems that vscode's right click on the function menu option does not appear relevant options.You can view the function call relationship in visual studio, you can add this function by clicking on the right click menu, and it would be better if you made the call diagram as source insight, thank you very much

**Comment by aeschli** [comment]
Can you file that feature request against the [cpp extension](https://github.com/Microsoft/vscode-cpptools/issues)? Thanks a lot!
