### ISSUE TITLE
Unity Snippets not working

### ISSUE THREAD

**Issue by sherzodkh** [Microsoft/vscode#51304]
I have installed unity snippets, it worked well till now, but after updating vs code,  unity auto compete snippets not working and not even showing !
I don't know this is because of vs code or extenison bug.

**Comment by jrieken** [comment]
In what version of VS Code is that, stable or insiders? Then what extension do you use?

**Comment by bruno1308** [comment]
Codelens stopped working for me on the mac Version 1.24.0

**Comment by jrieken** [comment]
@sherzodkh ping

**Comment by sherzodkh** [comment]
Recently, I have updated to 1.24. It was the previous of this vs code stable version of course
Also, some times it does not recognize unity script and after deleting my vs code, and installing again work again.
