### ISSUE TITLE
IMEs don't work in the VS Code snap package

### ISSUE THREAD

**Issue by peishaofeng** [Microsoft/vscode#51308]
Issue Type: <b>Bug</b>

I can't input any Chinese after switching to IME mode after upgrading to Ubuntu 18.04 + VSCode 1.23, but previous version (code 1.21) works fine.

I've also checked in other application like gedit even emacs, they all works, so i have to submit this issue report seeking for help.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 1681)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (3.40GB free)|
|Process Argv|/snap/vscode/37/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.23.5
material-icon-theme|PKi|3.5.0
project-manager|ale|0.25.2
tslint|eg2|1.0.30
vscode-emacs-friendly|lfs|0.8.2

</details>

**Comment by Tyriar** [comment]
How did you install vscode?

**Comment by peishaofeng** [comment]
I installed VSCode via Ubuntu Software Apps. 
After removing and re-download deb file(rev 1.24.0) from official site then install vscode manually, it works fine now.

Thank for your answer, it's not a problem anymore.

**Comment by Tyriar** [comment]
> I installed VSCode via Ubuntu Software Apps.

This is an unofficial distribution which uses a snap package. This is a known issue /cc @flexiondotorg

**Comment by fuji44** [comment]
FYR: Japanese is also the same.

```
$ uname -srvmpio
Linux 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ sudo apt list ibus ibus-mozc 
一覧表示... 完了
ibus/bionic,now 1.5.17-3ubuntu4 amd64 [インストール済み]
ibus-mozc/bionic,now 2.20.2673.102+dfsg-2 amd64 [インストール済み]

$ sudo snap list vscode
Name    Version            Rev  Tracking  Publisher     Notes
vscode  1.27.1-1536226049  53   stable    snapcrafters  classic
```

**Comment by fuji44** [comment]
Relevant Issue
https://github.com/snapcrafters/vscode/issues/28

**Comment by flexiondotorg** [comment]
@Tyriar   This can be closed. I worked with @joaomoreno to resolve this via the `snapcraft.yaml` your CI creates at the Snapcraft Summit in November 2018.
