### ISSUE TITLE
Info icon about keyboard layout in keybindings shown erroneously?

### ISSUE THREAD

**Issue by CombeeMike** [Microsoft/vscode#51314]
- VSCode Version: 1.24.0
- OS Version: Windows 10

Steps to Reproduce:
Don't know exactly how to reproduce this on different machines/environments...

Does this issue occur when all extensions are disabled?: Yes

Keybindings shows `info` about different keys on my layout even though the correct one is already set:
![image](https://user-images.githubusercontent.com/30658772/41087134-274d8a98-6a3c-11e8-959b-0024be326974.png)

![image](https://user-images.githubusercontent.com/30658772/41087218-61518c08-6a3c-11e8-8085-f236643a2b7d.png)

![image](https://user-images.githubusercontent.com/30658772/41087243-72dcd216-6a3c-11e8-9eea-7966675c7900.png)

How can I get rid of those info icons? The shown bindings are working as expected...

**Comment by alexandrudima** [comment]
@CombeeMike What keyboard layout are you using ?

**Comment by CombeeMike** [comment]
@alexandrudima I'm using `Deutsch (Österreich)`:

![image](https://user-images.githubusercontent.com/30658772/41228684-7947e448-6d79-11e8-9635-184eef4405c4.png)
