### ISSUE TITLE
ERROR - "Unable to open 'User Settings': Cannot read property 'id' of undefined.

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#51310]
- VSCode Version: 1.25.0-ins
- OS Version: win7x64

I've tried to open "**Settings**" by pressing `Ctrl+,` and it just blinked, closed, and I've got an error in "**Notifications**":

![image](https://user-images.githubusercontent.com/24613274/41086217-014ee26e-6a42-11e8-902a-51485760a7fc.png)

> "Unable to open 'User Settings': Cannot read property 'id' of undefined.

What is that?

I don't have any "id" in the "User Settings", nor keys, nor values.

Another try of `Ctrl+,` and the settings was opened normally.

**Comment by aeschli** [comment]
Can you open the Dev Tools and see if there's more information in the console?
From the menu use `Help > Toggle Developer Tools` and then open the 'Console' tab.

**Comment by sandy081** [comment]
Assigning to @roblourens. I suppose new settings editor is the default one to open in insiders.

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/51188, I think it should be fixed tomorrow.
