### ISSUE TITLE
[Extension] "write EPROTO" error while trying to download an extension through proxy

### ISSUE THREAD

**Issue by JabX** [Microsoft/vscode#5131]
- VSCode Version: Feb / March (didn't work before too anyway)
- OS Version: Windows (7 or 10)

I have configured my proxy settings in VSCode, and that works because I can search through extensions, and the "package.json module discovery feature" (I don't know how it's called) also works. It's just that when I click to download an extension I get a cryptic "write EPROTO" error. I tried various proxy configurations, but I didn't find anything that worked. Either I can connect or I can't, but I can never download.

Thanks for your time.

**Comment by joaomoreno** [comment]
Is your proxy http or https? Is there any chance I can use it too to try to reproduce?

**Comment by JabX** [comment]
It's a company proxy so no you can't use it...
I think it's a http proxy but I'm not sure. In any case it "works" the same with both 'http' and 'https' in the proxy url.

**Comment by JabX** [comment]
The brand new 1.0 release actually fixed this!
I don't know if anyone did anything for this between the insider release and 1.0 but I'm glad it works now.

**Comment by joaomoreno** [comment]
Happy to know!

**Comment by JabX** [comment]
Well, it turns out it only worked on my PC: my colleagues still have the error on their machines.
We have the exact same local config, the same global `.npmrc`, the same environnment variables (if any of that helps). The only difference we have if that I use Windows 10 and they're on Windows 7. And I used the insider version before the official release (which wasn't working for me anyway).

**Comment by JabX** [comment]
The new 1.1 release brought some more details in the error:
`messageService.ts:128 - write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:y:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794`

If any of that helps.

**Comment by LunarBiscuit** [comment]
I have the same error - tried the same things I used to get ATOM working but no luck so far. Would really love the fix.

**Comment by JabX** [comment]
I tried to build VS Code from source to investigate the problem, but it looks like I can't even fetch all the required dependencies when I run `npm install` because it needs to get `vscode.d.ts` from somewhere on Github but it can't (with the same error).

My proxy is configured correctly on both npm and git though.

**Comment by joaomoreno** [comment]
@JabX Sounds like a separate issue, do you mind creating it? Attach npm's log as well.

**Comment by debapamdas** [comment]
Facing the same issue in latest vs code version 1.1.1. I am able to search through the extensions but getting error while installing
write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:y:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794

**Comment by piggyslasher** [comment]
Same issue here :( Really want to get VS Code to work.

**Comment by electrohope** [comment]
I have the same issue with Windows 7

**Comment by JabX** [comment]
In the latest 1.3.0 version (with the new extension panel), installing an extension now simply hangs without any kind of error message (not even in the dev tools).

**Comment by piggyslasher** [comment]
C'mon.... This has never been fixed. Am on 1.4.0

![image](https://cloud.githubusercontent.com/assets/1991125/17429961/246a6bbc-5b24-11e6-9155-4a4cf4f2197a.png)

Can someone please fix this?

**Comment by joaomoreno** [comment]
@piggyslasher Is it possible for me to try using your proxy server for debugging and producing a fix?

**Comment by piggyslasher** [comment]
It's an internal proxy. Sorry. I only have access to it in our VPN. Atom plugins we're also quite hard to get working, but the solutions on this page helped me get it sorted:

https://github.com/atom/apm/issues/322#issuecomment-96430856

Do you think VSCode might have some similar issue?

**Comment by joaomoreno** [comment]
Do you happen to know which comments exactly helped you?

**Comment by piggyslasher** [comment]
It was the commend #322 that I linked to...

Also, in some cases, if node-gyp fails (it was normally node-gyp errors) I manually ran the following command.

```bash
HOME=~/.atom/.node-gyp/ "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.22.0" "--dist-url=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist" "--arch=darwin" "--ensure" "--verbose" "--proxy=http://10.9.1.80:8080"
```

But it was mostly the ATOM_NODE_URL fix that I got plugins to install in the first place.

**Comment by piggyslasher** [comment]
Basically the proxy doesn't allow ssh connections out. Maybe that's the reason? Can you default to using https for pulling extensions?

**Comment by joaomoreno** [comment]
We only use HTTPS.

**Comment by piggyslasher** [comment]
I tried using the command-line... Maybe this would help more. First time there were more errors.

![image](https://cloud.githubusercontent.com/assets/1991125/17643183/8951f8b2-6194-11e6-918b-50be745cf3dc.png)

**Comment by piggyslasher** [comment]
More error info in the dev-tools

![image](https://cloud.githubusercontent.com/assets/1991125/17647575/5bbe7972-6228-11e6-867a-234395302f28.png)

```ts
messageService.ts:119
write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:y:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:
: Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:y:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:,,    at exports._errnoException (util.js:890:11),    at WriteWrap.afterWrite (net.js:769:14)
```

**Comment by piggyslasher** [comment]
IT WORKS :)

**Comment by piggyslasher** [comment]
Not sure what you all did, but it's working now.

**Comment by joaomoreno** [comment]
Great to know.

**Comment by pietaridaemonna** [comment]
Win 7. i just updated 1.7.2 to 1.8 (and also tried 1.9 dev) and error is there.. 1.7.2 was working fine, 1.8 won't let me install powershell plugin  due to 

>  write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:y:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794

http.proxy or anything in config didnt change.
