### ISSUE TITLE
[error] Error: net::ERR_INTERNET_DISCONNECTED

### ISSUE THREAD

**Issue by KNobles** [Microsoft/vscode#51311]
Ok so yesterday I was able to download some extensions and today I wanted to install some but for some reason I had a message saying "An unknown error occurred. Please consult the log for more details.". As I go check the logs i get these (pic related) 

"[2018-06-07 09:55:35.108] [main] [info] update#setState idle
[2018-06-07 09:56:05.121] [main] [info] update#setState checking for updates
[2018-06-07 09:56:05.148] [main] [error] Error: net::ERR_INTERNET_DISCONNECTED
[2018-06-07 09:56:05.149] [main] [info] update#setState idle"

![image](https://user-images.githubusercontent.com/14289711/41086870-90fe8240-6a3b-11e8-8304-7fc854acc20c.png)

**Comment by sandy081** [comment]
@KNobles Looks like you are not connected to Internet. Can you please check that and let us know again?
