### ISSUE TITLE
Folder search with regex doesn't work

### ISSUE THREAD

**Issue by fr43nk** [Microsoft/vscode#51313]
- VSCode Version: 1.24.0
- OS Version: Windows 7

Steps to Reproduce:

1. Create a simple cpp file.
2. write code like follows:
```
m_pTesting->isEqual(103, m_pTest->getErrIdByIdx(0), logText,
                    strLen, appRes);
```
Use the Search in Folder user interface and use the following regular expression for searching:
```
(logText,)([\s\n]{3,})(strLen,)
```

But instead of selecting the part
```
logText,
                    strLen,
```
it selects
```
pTest->getErrIdByIdx(0), 
```

Using the in file search (ctrl+H) it works correct

**Comment by roblourens** [comment]
Multiline search is not supported yet: https://github.com/Microsoft/vscode/issues/13155
