### ISSUE TITLE
Ctrl+Shift+H (replace in files) should auto-reveal the replace field

### ISSUE THREAD

**Issue by Kroc** [Microsoft/vscode#51319]
The shortcut `CTRL`+`SHIFT`+`H` (replace in files), should reveal the replace field, normally hidden with search.

**Comment by roblourens** [comment]
It should do that. Does it not do that for you? Could the keybinding be overridden?

**Comment by Kroc** [comment]
Yes, sorry -- it was Activitus Bar that was breaking it!
