### ISSUE TITLE
Folder-level language-specific configuration ignored in multi-root workspace

### ISSUE THREAD

**Issue by metrip** [microsoft/vscode#51316]
Issue Type: <b>Bug</b>

1. Create a workspace with two root folders
2. Create a Typescript file in first folder
3. Edit folder settings for first folder
4. Observe that toggling value of "editor.autoClosingBrackets" between true and false changes editor behavior in the file, when inputting a "{", as expected
5. Remove setting
6. Observe that toggling value of "[typescript]": { "editor.autoClosingBrackets" } between true and false does not change editor behavior

Behavior not limited to autoClosingBrackets. Used as a simple example.

Language-specific configuration works as expected in workspace settings.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 3|
|Memory (System)|16.00GB (1.75GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.7.0
vscode-markdownlint|Dav|0.18.0
vscode-docker|Pet|0.0.27
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
gitlens|eam|8.3.4
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
dotenv|mik|1.0.1
Go|ms-|0.6.82
debugger-for-chrome|msj|4.5.0
json-parse-stringify|nex|1.0.2
vscode-coverage-gutters|rya|2.0.0
rewrap|stk|1.9.1
language-stylus|sys|1.9.2

(4 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Let's start investigation from brackets.

**Comment by alexandrudima** [comment]
I think this is a settings issue/question... @sandy081 Do we support `[language]` configurations in folder settings in a multi-root workspace?

**Comment by sandy081** [comment]
Yes we support them and it is working for me with the above example. Can you please share your workspace/user/folder settings to repro?
