### ISSUE TITLE
Add option to have JavaScript/TypeScript and CSS/LESS/SCSS share one single set of options

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#51327]
Whenever I set-up a new development machine with Visual Studio code I see a bunch of same JavaScript and TypeScript options and a bunch of same CSS, LESS and SCSS options.

Would you please add an option to have TypeScript inherit all user-altered JavaScript options and to have SCSS/LESS inherit user-altered CSS options and SCSS inherit user-altered LESS options?

So this kind of user-altered settings inheritance would be true:

```
JavaScript
  \ -- TypeScript

CSS
  \ -- LESS
         \ -- SCSS
```

This would ease setting up VS Code a lot, particularly when the new Settings GUI is coming up. That GUI could, for instance, show a page with common settings and additionals pages with settings only pertinent to the particular flavour of a language.

see: #50249

**Comment by aeschli** [comment]
Sorry, no plans for this. That would make the settings UI even more complicated.

**Comment by aeschli** [comment]
Sure, I can keep it open.

**Comment by roblourens** [comment]
This is like https://github.com/Microsoft/vscode/issues/57330. We would have to add metadata to a setting that basically says "when this setting is not configured, it falls back on the value of setting xyz".

I'm not really a fan of this - I think it's confusing and I don't know how to illustrate this situation to the user in UI. We need to show "if you set this setting, you are also changing these other settings..." and "this setting is falling back on this other setting's value...". But I do understand that if a user configures javascript.xyz, they probably want typescript.xyz to be the same.

**Comment by mjbvz** [comment]
If setting is shared by multiple languages, it should probably move under `editor.*` or some similar scope that acts like the `editor.*` settings. Then you could override it per language using language specific settings

**Comment by octref** [comment]
@SetTrend I don't think we can add this feature in an easy-to-usage, straightforward way, so I suggest that you use the multi-cursor features with the JSON editor to do this:

![settings](https://user-images.githubusercontent.com/4033249/47466075-70b02300-d7a4-11e8-8d49-84b729a61917.gif)

**Comment by SetTrend** [comment]
Thanks, y'all for taking the time to discuss this issue.

I may have suggested to have a "base class" type of setting for `script` and `style`, having `JavaScript` and `TypeScript` derive from `script`, and `CSS`, `SASS` and `LESS` derive from `style`.
