### ISSUE TITLE
Shortcut Bug

### ISSUE THREAD

**Issue by asifsaho** [Microsoft/vscode#51326]
Issue Type: <b>Bug</b>

I have changed the keybinding with the extension InteliJ IDEA Keybindings but most of the time CTRL+P to open file doesn't work. If I click on the file tab bar (not on filename) then hit the shortcut it works. Please take care of this bug.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (9.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.2
intellij-idea-keybindings|k--|0.2.23
php-formatter|Sop|0.2.4
wordpress-snippet|tun|1.1.2

(1 theme extensions excluded)

</details>

**Comment by auchenberg** [comment]
This issue was moved to kasecato/vscode-intellij-idea-keybindings#126
