### ISSUE TITLE
keybindings.json default settings error

### ISSUE THREAD

**Issue by kojiman** [Microsoft/vscode#51323]
Issue Type: <b>Bug</b>

keybindings.json default settings error.

1. Disable all extensions.
2. Open keybindings.json.
3. Show PROBLEMS panel.

PROBLEMS:
- keybindings.jons vscode://defaultsettings/keybindings.json 1
  - [jsonc] Invalid escape character in string. (214, 46)

{
	"resource": "/keybindings.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "261",
	"severity": 8,
	"message": "Invalid escape character in string.",
	"source": "jsonc",
	"startLineNumber": 214,
	"startColumn": 46,
	"endLineNumber": 214,
	"endColumn": 142
}

keybindings.json(214): 
{ "key": "shift+alt+o",           "command": "editor.action.organizeImports",
                                     "when": "editorTextFocus && !editorReadonly && supportedCodeAction =~ /(\s|^)source\.organizeImports\b/" },

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:02.816Z)
OS version: Windows_NT ia32 10.0.16299

**Comment by aeschli** [comment]
Looks like a problem when generating the keybindings.json default.

**Comment by sandy081** [comment]
@jrieken Looks like you are not escaping while serialising the reg ex context key

**Comment by jrieken** [comment]
@sandy081 On a second thought... Should I really escape for json in there? Isn't that the responsibility for the keybindings editor? E.g. when parsing I don't get the JSON-escaped string but a normal JS-string.

**Comment by sandy081** [comment]
What is the source of the content you are parsing? Are you reading it from user `keybindings.json` file? If so is not it an escaped string?

**Comment by jrieken** [comment]
> What is the source of the content you are parsing?

It's a JavaScript string. The notion of JSON doesn't (and shouldn't) leak into the context key objects. Those are defined here: https://github.com/Microsoft/vscode/blob/b0ef947992f10643e5d8f3e854adaaa3c6865681/src/vs/platform/contextkey/common/contextkey.ts#L360. Someone calls serialise on my object and assumes the returned string is valid JSON - which is an invalid assumption.

**Comment by Gubith** [comment]
Am I correct to assume the bug does not actually cause a problem for most users and can be disregarded?

I was concerned because settings errors have always resulted in edits failing to save & apply.

I've had this issue for a week but it has not affected using Code.

**Comment by sandy081** [comment]
@Gubith Can you please elaborate the issue you are having? If it is not the same issue as this, please file a separate issue with proper steps to reproduce?

**Comment by Gubith** [comment]
I have the same error as OP, same line, same keybinding.

**Comment by sandy081** [comment]
@Gubith It is fixed and is available in insiders. Please try the insiders and check

**Comment by tburly** [comment]
Confirming the same error. I'm on version 1.25.1 (Windows). The only thing different than the OP's case is a reported line number (223 in my case). Shouldn't vscode's auto-generated settings files be excluded from the JSON linter by default? I see no use in reporting this sort of error to a user.
