### ISSUE TITLE
Add a new terminal panel but vscode didn't switch to the new one

### ISSUE THREAD

**Issue by gemmi** [Microsoft/vscode#51328]
Issue Type: <b>Bug</b>

0, open vscode (initialization)
1, vscode shows the termianl panel, and there is only one terminal panel
2, click "add" button, and a new panel is added, but vscode still shows the first one other than switch to the new one, you must select the option in the selectbox manually and switch.

**Expected:** switch to the new one after clicked.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.2
vscode-eclipse-keybindings|alp|0.9.7
color-info|bie|0.5.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.58
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
javadebugger|don|0.1.5
xml|Dot|2.2.0
gitlens|eam|8.3.4
graphviz-preview|EFa|1.1.0
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
vscode-power-mode|hoo|2.2.0
docthis|joe|0.7.1
Kotlin|mat|1.6.0
markdown-shortcuts|mdi|0.8.1
vscode-language-pack-zh-hans|MS-|1.24.3
python|ms-|2018.5.0
debugger-for-chrome|msj|4.5.0
vetur|oct|0.12.5
material-icon-theme|PKi|3.5.0
Ruby|reb|0.18.0
vue-vscode-snippets|sdr|1.3.0
dot|Ste|0.0.1
open-in-browser|tec|1.1.0
vscode-import-cost|wix|2.7.1
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by Tyriar** [comment]
This is meant to be what happens. Can you reproduce the problem when you launch with `code --disable-extensions`?

**Comment by gemmi** [comment]
@Tyriar Sorry it's a occasionally problem, i tried some times but the panel switches correctly now, with both extensions disabled and enabled.
