### ISSUE TITLE
Search field "spawn EACCES" on search

### ISSUE THREAD

**Issue by Rossie** [Microsoft/vscode#51333]
Issue Type: <b>Bug</b>

Open workspace.
Typing text in the search field.
Hitting enter.
It says in a red popup: "spawn EACCES"

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
ci-snippets2|Ani|1.0.0
jshint|dba|0.10.18
fileheadercomment|doi|0.0.3
tslint|eg2|1.0.30
php-intellisense|fel|2.3.2
seito-openfile|Fr4|1.5.1
Angular-BeastCode|Mik|6.0.15
vscode-apache|mrm|1.1.1
debugger-for-chrome|msj|4.5.0
vscode-icons|rob|7.23.0
php-ci|sma|0.2.10
bootstrap4-vscode|the|4.1.1
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by roblourens** [comment]
Did this work in 1.23?

Can you verify that `"C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe"` exists?
