### ISSUE TITLE
v1.24.0 changed some characters, ~breaking my extension

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#51335]
[Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) uses the following characters for distinguishing between pending, done and cancelled todos:  `☐`, `✔` and `✘`.

An example file highlighted by this extension under VSC v1.23.0 and Windows would look like this:

<img width="309" alt="before" src="https://user-images.githubusercontent.com/1812093/41093601-0dab4f02-6a4c-11e8-86fe-5a4457b8a100.png">

Updating to v.1.24.0, still on Windows, messes up some of those characters:

<img width="309" alt="after" src="https://user-images.githubusercontent.com/1812093/41093362-664d279e-6a4b-11e8-8f92-599cd1ae19fd.png">

Notice how the `☐` character is now always black no matter what, and the `✔` has always it's particular shade of green, the latter problem is better seen in this other screenshot:

![Green](https://user-images.githubusercontent.com/2088490/41092948-601e5d3a-6a4a-11e8-9523-cbaabd70def7.png)

For some of my users the `✔` character is no longer monospaced either, messing up the alignment (/cc @fabysdev @samael205):

![Alignment](https://user-images.githubusercontent.com/2088490/41084056-59ce99fc-6a33-11e8-847f-192da15d118d.png)

I'm using the same version of Todo+, I didn't change the font, I didn't change any setting, I just upgraded VSC from v1.23.0 to v.1.24.0.

I can't reproduce this in macOS.

**Comment by alexandrudima** [comment]
We merged in https://github.com/Microsoft/vscode/pull/50168 in order to fix https://github.com/Microsoft/vscode/issues/32840

The only workaround I can think of for now is to manually edit the default `editor.fontFamily` and set it to something like `Consolas`.

I'm not sure how to proceed, we might need to roll back the changes done in #50168. (fyi @rianadon)

**Comment by fabiospampinato** [comment]
I see 🤔 I think the mistake was using emojis in the extension in the first place as they are not guaranteed to always look the same.

I think the best option here is keeping https://github.com/Microsoft/vscode/pull/50168 in and I'll replace those characters in my extension with something else.

The issue with this is that no longer updated extension (like @sandy081's [To Do Tasks](https://marketplace.visualstudio.com/items?itemName=sandy081.todotasks)) will remain affected by this.

**Comment by alexandrudima** [comment]
This got fixed via 7399f84 and 0f0770d
