### ISSUE TITLE
Allow custom icons for symbols in the symbol list / outline

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51334]
It'd be nice if an extension could provide additional icons for showing in the Outline view. For example, if a method is a Test method, it'd be nice to show with a different icon to non-test methods in the class. Currently symbols are fixed based on SymbolKinds.

**Comment by jrieken** [comment]
@DanTup please start using issue search

**Comment by DanTup** [comment]
Whoops, sorry! I did look through the docs and vscode.d.ts to ensure it didn't already exist, but must've forgotten to search - I do usually :-)
