### ISSUE TITLE
Missing User notice on reching size-, time- or other limits...

### ISSUE THREAD

**Issue by dermoench42** [Microsoft/vscode#51339]
On trying to open a huge xml File (~400Mb) I run into some Editor Size and executions time limts. The File wasn't highlighted and I couldn't format it. I spend a few hours on digging into the problem assuming there is some bug either n xml tools or the editor.
Unfortunately I found that this buggy behaviour was initiated by some silently and hidden defined limits on size and execution time. These limits prevents the tools and plugins working on huge files.

Since that is very bad or ugly, politely I should say unlucky, software behaviour: silently failing on well known arbitrary conditions based on design, because it takes hours of attention and produce unnecessary noise on issue trackers until the reason is found.

I'd like to request a user informing mechanism, e.g. notice or alert, in the case limits are reached and preventing the editor and other parts from doing their job.

Many thanks in advance!

Ervin Peters

**Comment by alexandrudima** [comment]
Funny timing, this has just shipped in the 1.24 version.

When opening a large file where the limits kick in, there is now a dialog that asks you what you want to do:

![image](https://user-images.githubusercontent.com/5047891/41234607-f952f80e-6d8c-11e8-8bbe-20d6c51f4f82.png)

**Comment by dermoench42** [comment]
Tried it, but I would suggest to not store the answer globally but only for the opened file. Or choose between three options: 
never show | forcefully enable for this file | forcefully enable globally
.
I opened my 500Mb xml file an ms access database export file, 'forcefully enabled features' and got an 'invalid string length' error. There seem to a few other limits behind :}.

ervin
