### ISSUE TITLE
SCSS file path autocomplete not working after 1.24.0 release

### ISSUE THREAD

**Issue by afisher88** [Microsoft/vscode#51331]
**- VSCode Version:**
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**- OS Version:**
 Windows 10 Pro 64bit version 1803, OS Build 17134.48

Steps to Reproduce:

1.  Create a project with two SCSS files
2. Use `@import '../path/to/file/'`  to try to import one from another
3. SCSS methods are suggested but not paths

This was working up until I updated to 1.24.0 today. Confirmed with no extensions enabled.

![autocomplete](https://user-images.githubusercontent.com/5710575/41092905-e15147a4-6a41-11e8-9914-87a75bf50778.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by tojacob** [comment]
Yep!

**Comment by vittaljk** [comment]
Yeah facing the same issue

**Comment by shashikiran797** [comment]
+1

**Comment by anjapadu** [comment]
Similar issue. In my case it autocomplete routes but dont autocomplete component of imported libraries.

![image](https://user-images.githubusercontent.com/16998699/41476921-81c086cc-7088-11e8-8829-88beee02afa7.png)

On the previous version it autocompleted  and autoimport de component from the imported Library.

**Comment by adrianmui** [comment]
yep!

**Comment by octref** [comment]
We have completion for `url()` but not SCSS's import yet. For SCSS we also need some special handling of paths, because `@import 'reset'` actually imports `_reset.scss`.

Moving to July milestone.
