### ISSUE TITLE
Unused variable detection : greyed-out is hard to understand

### ISSUE THREAD

**Issue by nn-hh** [Microsoft/vscode#51348]
Depending on the theme very hard to see.
Is not the gray wavy line better?

**Comment by paterasMSFT** [comment]
Is it possible to change the color with a user setting?

**Comment by mjbvz** [comment]
Thanks @paterasMSFT! Here's the user setting you can use to customize this currently:

```json
	"workbench.colorCustomizations": {
		"editorUnnecessary.foreground": "#ffff00"
	}
```

We are also thinking about fading out code instead of using a solid grey color. Part of #51104

**Comment by Izhaki** [comment]
No longer working in 1.25.0

https://github.com/Microsoft/vscode/issues/51420
