### ISSUE TITLE
emmet - not possible to add attributes to html tags

### ISSUE THREAD

**Issue by joshgreen** [Microsoft/vscode#51340]
Its not possible to add attributes to html elements using emmet

- VSCode Version: 1.23.1
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

1. try make emmet expand `table[width=600]`
2. hit tab

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by ramya-rao-a** [comment]
Works as expected for me.

![table](https://user-images.githubusercontent.com/16890566/41116100-365eb14a-6a3e-11e8-812b-78a362523e99.gif)

Have you set `emmet.triggerExpansionOnTab` to `true`?

**Comment by joshgreen** [comment]
thanks that was the problem
