### ISSUE TITLE
No exported members for module after upgrade

### ISSUE THREAD

**Issue by mweiczorek** [Microsoft/vscode#51343]
Strange issue with newest release, all my React component modules that import from the SemanticUI React package suddenly spawn errors like:

/node_modules/semantic-ui-react/dist/commonjs/index"' has no exported member 'ButtonProps'.

<img src="https://image.ibb.co/mZf3k8/vs.png" />

An example of the file /node_modules/semantic-ui-react/dist/commonjs/index.js:
```
Object.defineProperty(exports, "__esModule", {
  value: true
});

...
var _Menu = require('./collections/Menu');

Object.defineProperty(exports, 'Menu', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_Menu).default;
  }
});
```

This only happens with the "semantic-ui-react" package, as far as I can tell. This happened right after upgrading VSCode to 1.24.0, and happened on two separate projects using SemanticUI. It's not happening with any other packages as far as I can tell.

Aside from the errors, I've lost all intellisense and automatic imports for SemanticUI.

Restarting VSCode does not help
Manually installing types/semantic-ui-react with npm doesn't help

I should add the project works just as it did before, with no errors

Using:
TypeScript 2.9.1
SemanticUI React 0.77.2
Developing Electron app

- VSCode Version: 1.24.0
- OS Version: Windows 10 (Version 1709, Build 16299.431)

Steps to Reproduce:

1. Install older version of VSCode
2. Start project with react, and semantic-ui-react
3. Upgrade VSCode to 1.24.0

Does this issue occur when all extensions are disabled?: Yes (all are disabled)

**Comment by LioraPost** [comment]
also have this problem

**Comment by mjbvz** [comment]
If you run `go to definition` on `'semantic-ui-react'`, which file is opened? If you are using typescript, do you also see this error when running `tsc` with TS 2.9?

**Comment by mjbvz** [comment]
Also, make sure you uninstall the old `@types/semantic-ui-react`. The types should now be shipped with that package

**Comment by LioraPost** [comment]
when i run go to definition on 'semantic-ui-react' it opens the file:
\node_modules\semantic-ui-react\dist\commonjs\index.d.ts

i get the same errors using tsc with ts 2.9.1

the old type definitions are not installed

**Comment by mjbvz** [comment]
What does your `tsconfig.json` contain?

**Comment by mjbvz** [comment]
Nevermind, `tsconfig` seems unrelated. This repos for me with 0.77.2 but not with the latest semantic-ui (0.88.x)
