### ISSUE TITLE
CMD + CLICK = Find all reference! WHAT????

### ISSUE THREAD

**Issue by Xestero** [Microsoft/vscode#51349]
Issue Type: <b>Bug</b>

CMD + CLICK = Find all reference! WHAT????
Its worked correctly before i have restarted application (after latest update, application has been restarted for 1-2 hours ago)

1) Hold "CMD"
2) "Left Click" on method in any class
 
<img width="1349" alt="screen shot 2018-06-07 at 14 33 01" src="https://user-images.githubusercontent.com/12487768/41100672-45406b08-6a62-11e8-82f5-745b16694d88.png">

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
react-native-react-redux|EQu|1.9.0
solidity|Jua|0.0.43
Angular-BeastCode|Mik|6.0.15
material-icon-theme|PKi|3.5.0
vscode-wakatime|Wak|1.2.2
html-css-class-completion|Zig|1.17.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
vscode-dash|dee|1.10.0
es7-react-js-snippets|dsz|1.7.0
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
vscode-npm|fkn|3.3.0
solidity-solhint|idr|1.1.4
team|ms-|1.136.0
debugger-for-chrome|msj|4.5.0
vscode-versionlens|pfl|0.21.1
sass-indented|rob|1.4.9
vscode-react-native|vsm|0.6.10
ReactSnippets|xab|2.1.0

</details>

**Comment by aeschli** [comment]
Please add more information. Is it a bug, feature request... Steps, screenshots, what do you expect, what do you see.

**Comment by rfgamaral** [comment]
Not sure if related or the same exact issue but <kbd>Alt</kbd>+<kbd>Click</kbd> (to follow references on Windows) on JS projects stopped working. "Find All References" returns no definitions.

All this used to work just fine on 1.23.x.

**Comment by aeschli** [comment]
@Xestero Thanks for the screenshot. The peek window shows up if there are two (or more) definitions for the symbol. (looks like find references, but it is not the same). Also see the title of the peek window...

@rfgamaral Can you file a separate issue with a code sample?
