### ISSUE TITLE
Support "project has build errors, debug anyway?" for debug sessions that don't have a preLaunchTask task

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51341]
For TypeScript, if I hit F5 and have build errors, I get a dialog like "Build errors were detected [Show Errors], [Debug Anyway]".

I'd been asked for the same thing in Dart, but it seems that VS Code's version is based on a preLaunchTask failing (which we don't have).

I thought I could just implement this at the top of my `resolveDebugConfiguration` method, however when we bail out of there, we end up opening `launch.json` which would be unexpected in this situation.

Is there a way I can provide this? If not, can we have something?

**Comment by isidorn** [comment]
The debug anyway action shows up if the task failed or if there are errors in the workspace.
So theoretically you could use the marker service to generate some errors and you will get this dialog for free before starting a debug session.
Can you please try that and let us know how it works? Thanks

**Comment by DanTup** [comment]
@isidorn It definitely doesn't work just by having errors, I think because of this:

```ts
const errorCount = resolvedConfig.preLaunchTask ? this.markerService.getStatistics().errors : 0;
```

Since `preLaunchTask` is undefined, it gets a 0 here.

**Comment by DanTup** [comment]
and by marker service, I presume you just generate some diagnostics? I have a screen full of errors but hitting F5 just launches - breakpoint on the code above shows it gets 0, then a few lines later it just returns (before the dialog) because of the 0 errors.

**Comment by isidorn** [comment]
@DanTup you are correct it is becuase of that line that we ignore errors.
The reason for this is that if a user has a totally unrelated error in his workspace we do not want to spam them with modal dialogs.

So in order for us to change this behavior and always respect the error count there shuold be some mechanism to opt into this. Since doing this out of the box is not ideal.

**Comment by DanTup** [comment]
Yeah, making it opt-in seems reasonable. If #51069 was done, we could also just implement this ourselves.
