### ISSUE TITLE
Focus first newly created empty group when changing layouts

### ISSUE THREAD

**Issue by aleksijuvani** [microsoft/vscode#51342]
@bpasero 

With the grid layout insiders build, switching from single-column mode to "2 columns" via a hotkey will keep the first editor group focused. This is unintuitive to me, because when switching to "2 column" layout I will usually want to immediately open a file in that second column. In Sublime Text changing to "2 column" layout will focus the newly opened column. Changing to "3 column" layout will focus the third column, and so on.

**Comment by bpasero** [comment]
@aleksijuvani would it be accurate to say it should just always focus the first empty group?

**Comment by aleksijuvani** [comment]
That would work for me. If we want to imitate Sublime Text though, I think it always focuses the *last* empty group instead of the first.

Sublime Text also has some weird behaviour that if you're going from a larger column layout (say 3 columns) to a smaller one (2 columns or single-column), it will always focus column 1. I'm not sure if that behaviour is something worth replicating though.
