### ISSUE TITLE
False Warnings: Not Recognizing System Path on Windows

### ISSUE THREAD

**Issue by iwmq** [Microsoft/vscode#51345]
Hi guys, when I tried to install Python extensions, the log showed warings reading that my *python scripts* path is not in PATH. While I truly know the *python scripts* path is in the system path variable, and these extensions do work well after installation. Can these false warnings be fixed, because they are really annoying.

**Comment by aeschli** [comment]
@iwmq Please file this issue against https://github.com/Microsoft/vscode-python. Thanks a lot!
