### ISSUE TITLE
launch.json is not autoloading after created

### ISSUE THREAD

**Issue by pius-pworld** [Microsoft/vscode#5134]
- VSCode Version:0.10.11
- OS Version:Windows 7 ultimate 64 bit 

Steps to Reproduce:

1. When i first press f5 launch.json is created but debug console is not opening... Again pressing f5 (Please set up the launch configuration file to debug your application visual studio code) massage showed..
2.  When i close vs code and re open it this time last created launch.json is loaded and pressing f5 debug console opened.

**Comment by isidorn** [comment]
Debug console is only opened once a debug session is started, in this scenario you have not yet setup debugging. Again pressing F5 - is your `launch.json` configured properly - does the `program` attribute point to your actual program to be debugged

I can not reproduce the behavior you are explaining. A gif, or a repository for which I can repro this would be useful.
Will reopen if more details are provided.
