### ISSUE TITLE
"No" option for feedback popup

### ISSUE THREAD

**Issue by diepvriezer** [Microsoft/vscode#51353]
I really love the editor, but when you ask: "Would you like to give feedback?" and the options are "Take the survey" and "Remind me later" I just.. Please stop doing this, make a button "No"; if this were a conversation we would never talk again.

Then I found out you have to use Twitter; why ask at all? People who tweet will do so regardless. Keep up the great work, you guys are awesome!

**Comment by ramya-rao-a** [comment]
A few months ago, when we introduced the new UI for notifications, we stopped showing all the `Don't show again` options as buttons. Instead they are now available in the gear/settings icon on the same notification.

![image](https://user-images.githubusercontent.com/16890566/41263881-87283b10-6d9e-11e8-9921-5250bdd344a9.png)

Click on that, and you will get the `Don't show again` option.

![image](https://user-images.githubusercontent.com/16890566/41263828-37bbf51c-6d9e-11e8-8bc6-49be39b41d0c.png)
