### ISSUE TITLE
Default action for `ctrl + a` should be `cursorEnd`, not `cursorLineStart`

### ISSUE THREAD

**Issue by artdent** [microsoft/vscode#51359]
- VSCode Version: 1.24.0
- OS Version: macOS High Sierra, 10.13.4

Steps to Reproduce:

1. Type ctrl+a
2. Expected: cursor moves to leftmost non-whitespace character
3. Actual: cursor moves to column 0

This is a reopening of #47319, which was previously closed with the note that keybindings are customizable. My suggestion is that the default keybinding be changed to match macOS user expectations.

The current default is:
```
{ "key": "ctrl+e",                "command": "cursorLineEnd",
                                     "when": "textInputFocus" },
{ "key": "ctrl+a",                "command": "cursorLineStart",
                                     "when": "textInputFocus" },
```

The more idiomatic default would be:
```
{ "key": "ctrl+e",                "command": "cursorEnd",
                                     "when": "textInputFocus" },
{ "key": "ctrl+a",                "command": "cursorHome",
                                     "when": "textInputFocus" },
```

**Comment by DieLaughing** [comment]
If you are still discussing this, can you maybe see why Ctrl+a is non-existent on Linux? Thanks.

**Comment by rebornix** [comment]
@alexandrudima do you mind commenting or triaging this one as I saw we have change for this command before https://github.com/Microsoft/vscode/commit/5b7b38d8a5ef6025dea1bc889f3719e5e9cd4ed1

**Comment by alexdima** [comment]
I have tested Sublime Text and Text Edit on macOS. `ctrl+a` goes to the first column in both programs, not to the first non-whitespace character. I therefore believe our default keybinding is good.
