### ISSUE TITLE
Remeber typed text while terminal starting up

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#51355]
There a feature of iTerm which I absolutely love:
As soon as I start it up I start typing, and even though it is not initialitized it will remember what I typed and respect that as soon as he is started up fully.
I would love for our intergrated terminal to have that as well as it says quite some time when starting a new terminal

**Comment by Tyriar** [comment]
There is a queue that is kept before the process is started up which does this already. I don't think there's much else we can do as it's probably waiting on the DOM element construction and focus in our case. We can chat about this next week if you want 😃

**Comment by isidorn** [comment]
@Tyriar does not really work for me on my machine (os x, zsh oh my). We can talk in the afternoon
