### ISSUE TITLE
No option in VSCode to clone Git Repository

### ISSUE THREAD

**Issue by Famadeco** [Microsoft/vscode#51365]
Issue Type: <b>Performance Issue</b>

The option to clone Git Repository in VSCode 1.24.0 cannot be found in the welcome window as directed by the Microsoft Cloud Society (MCS) trainer. 

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:02.816Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Duo CPU      T2450  @ 2.00GHz (2 x 1995)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|2.99GB (1.05GB free)|
|Process Argv|C:\Users\hp\AppData\Local\Temp\Rar$EX06.322\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    77	  7740	code main
    0	   101	  3072	   window (Welcome - Visual Studio Code)
    0	     9	  6756	     extensionHost
    0	     7	  6992	     searchService
    0	     1	  7860	     electron-crash-reporter
    2	    60	  4084	   shared-process
    0	   180	  5688	   "C:\Program Files\Mozilla Firefox\firefox.exe" -osint -url "https://github.com/Microsoft/vscode"
    0	   164	   900	     "C:\Program Files\Mozilla Firefox\firefox.exe" -contentproc --channel="5688.3.631681284\2137522911" -childID 1 -isForBrowser -intPrefs 44:0| -boolPrefs 299:0| -stringPrefs 285:38;{eb66b501-cffd-41b0-aedf-ab41163e6564}| -schedulerPrefs 0001,2 -greomni "C:\Program Files\Mozilla Firefox\omni.ja" -appomni "C:\Program Files\Mozilla Firefox\browser\omni.ja" -appdir "C:\Program Files\Mozilla Firefox\browser"  5688 "\\.\pipe\gecko-crash-server-pipe.5688" 1476 tab
    0	   217	  1572	     "C:\Program Files\Mozilla Firefox\firefox.exe" -contentproc --channel="5688.13.2057256768\51354166" -childID 2 -isForBrowser -intPrefs 44:0| -boolPrefs 299:0| -stringPrefs 285:38;{eb66b501-cffd-41b0-aedf-ab41163e6564}| -schedulerPrefs 0001,2 -greomni "C:\Program Files\Mozilla Firefox\omni.ja" -appomni "C:\Program Files\Mozilla Firefox\browser\omni.ja" -appdir "C:\Program Files\Mozilla Firefox\browser"  5688 "\\.\pipe\gecko-crash-server-pipe.5688" 2376 tab
    0	    34	  6784	     "C:\Program Files\Mozilla Firefox\firefox.exe" -contentproc --channel="5688.34.1130703415\1221413886" -childID 5 -isForBrowser -intPrefs 44:0| -boolPrefs 299:0| -stringPrefs 285:38;{eb66b501-cffd-41b0-aedf-ab41163e6564}| -schedulerPrefs 0001,2 -greomni "C:\Program Files\Mozilla Firefox\omni.ja" -appomni "C:\Program Files\Mozilla Firefox\browser\omni.ja" -appdir "C:\Program Files\Mozilla Firefox\browser"  5688 "\\.\pipe\gecko-crash-server-pipe.5688" 6808 tab
    0	    43	  6860	     "C:\Program Files\Mozilla Firefox\firefox.exe" -contentproc --channel="5688.20.432208694\758470201" -childID 3 -isForBrowser -intPrefs 44:0| -boolPrefs 299:0| -stringPrefs 285:38;{eb66b501-cffd-41b0-aedf-ab41163e6564}| -schedulerPrefs 0001,2 -greomni "C:\Program Files\Mozilla Firefox\omni.ja" -appomni "C:\Program Files\Mozilla Firefox\browser\omni.ja" -appdir "C:\Program Files\Mozilla Firefox\browser"  5688 "\\.\pipe\gecko-crash-server-pipe.5688" 3096 tab
    0	    77	  8064	     "C:\Program Files\Mozilla Firefox\firefox.exe" -contentproc --channel="5688.0.280577464\1672406508" -greomni "C:\Program Files\Mozilla Firefox\omni.ja" -appomni "C:\Program Files\Mozilla Firefox\browser\omni.ja" -appdir "C:\Program Files\Mozilla Firefox\browser"  "C:\Users\hp\AppData\LocalLow\Mozilla\Temp-{eb66b501-cffd-41b0-aedf-ab41163e6564}" 5688 "\\.\pipe\gecko-crash-server-pipe.5688" 1224 gpu
    0	    44	  6980	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.2
gitignore|cod|0.5.0
git-extension-pack|don|0.1.3
githistory|don|0.4.1
gitlens|eam|8.3.4
vscode-open-in-github|ziy|1.3.1

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by joaomoreno** [comment]
Right, this action was removed from the Welcome screen. Use the command palette to execute it: <kbd>F1</kbd>, `Git: Clone`.
