### ISSUE TITLE
No option to revert back to horizontal terminal

### ISSUE THREAD

**Issue by zainimran** [Microsoft/vscode#51363]
Issue Type: <b>Bug</b>

On selecting the option to have a vertical terminal, I don't see an option to go back to the horizontal view.

<img width="1440" alt="vscode bug" src="https://user-images.githubusercontent.com/17803773/41109752-2722ec16-6a91-11e8-8ada-1c367728029c.png">

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.93GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_999668|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
vscode-markdownlint|Dav|0.18.0
gc-excelviewer|Gra|2.0.21
code-settings-sync|Sha|2.9.2
html-css-class-completion|Zig|1.17.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.3.4
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
rest-client|hum|0.18.4
sublime-babel-vscode|jos|0.2.10
python|ms-|2018.5.0
vsliveshare|ms-|0.3.264
debugger-for-chrome|msj|4.5.0
vscode-icons|rob|7.23.0
code-spell-checker|str|1.6.10
JavaScriptSnippets|xab|1.6.0
plsql-language|xyz|1.3.3

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Related to lack of an overflow for the panel actions.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/46017
