### ISSUE TITLE
Export/Import error from debugging session

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#51362]
I'd like to to save / export / serialize an error, which occured on debugging session. And some time after send it to a colleague and/or load / import / deserialize it back into visual studio code and inspect or analyze it.

This is very useful for a case when an error is not trivial to reproduce.

**Comment by weinand** [comment]
What kind of error is this?

**Comment by Deilan** [comment]
@weinand Javascript exception, C# exception, etc.

**Comment by weinand** [comment]
But for analysing an error post-mortem you would need a full dump of the program, right?

**Comment by Deilan** [comment]
@weinand It would be even better, but I'm not sure is there a way to do it.

The previous point: having a stacktrace and ability to navigate between levels of it right in the source code makes a life a little bit easier.

**Comment by weinand** [comment]
Aha, you only need threads and/or stackframes, but not variables.

**Comment by Deilan** [comment]
@weinand We have to start somewhere. :) As a next step forward, variables / dump would be also great.
