### ISSUE TITLE
Auto update import paths and "move to a new file" refactoring does not work

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [Microsoft/vscode#51366]
- VSCode Version: 1.24.0, 1.25.0-insider
- OS Version: macOS 10.13.4

Import paths are not updated and it's not possible to refactor a class to a new file with a specific value of `files` in `tsconfig.json`.

Here's a [test repo](https://github.com/ivanvoznyakovsky/ts-refactoring-issue).

Without changing anything try to move file `app/services/service1.ts` to `app/services/core` folder. No request to update imports hence `app/services/index.ts` has broken `import`.
Open `app/services/service1.ts` and try to refactor out `Service2` class to a new file. After clicking `Move to a new file` nothing happens. Literally nothing.
Now comment out `"files": ["./app/app.ts"]` in `tsconfig.json` or replace it with one of commented out lines for `files` and try to do all the above. All should work as expected.

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur in insiders build?: Yes

**Comment by mjbvz** [comment]
For update paths: When you set `"file: [./app/app.ts"]`, you've told typescript that only that one file is part of the project. That's why the references are not update in that case. You need to include at least the moved file and the referencing file in the same project

The move to file issue is a bug. I've opened https://github.com/Microsoft/TypeScript/issues/24757 to track this

**Comment by ivanvoznyakovsky** [comment]
> For update paths: When you set "file: [./app/app.ts"], you've told typescript that only that one file is part of the project.

how is this possible? isn't it that by setting `file: ["./app/app.ts"]` I only tell TS that this is my entry point for the whole project. all the rest is imported down the road. 
we have a project that has almost 50K ts files. are you suggesting to add all of them to `files`?

**Comment by mjbvz** [comment]
Use [`include` and/or `exclude`](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html)

**Comment by ivanvoznyakovsky** [comment]
it's not a solution but rather a workaround on the bug that for some reason a file is not resolved to be included in the project.

**Comment by ivanvoznyakovsky** [comment]
main purpose of `file: ["./app/app.ts"]` is to get a single file after compilation and not 50k of compiled files. doesn't it make sense?

**Comment by zuzusik** [comment]
@mjbvz according to [docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):

> Any files that are referenced by files included via the "files" or "include" properties are also included

so looks like this feature is not aligned with core concepts - I would still consider this as a bug
