### ISSUE TITLE
Unused variable detection - Is not working properly

### ISSUE THREAD

**Issue by velozmontero** [Microsoft/vscode#51361]
- VSCode Version: May 2018 (version 1.24)
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Create react component
2. import fe from 'fast-equals';
3. Use fe.deep(object1, object2) inside a component method

```ts
import React, { Component } from 'React';
import fe from 'fast-equals'; // greyed-out 

class SomeComponent extends Component {
  someMethod = () => fe.deep(object1, object2);
  render() { return someMethod() ? <div>equal</div> : <div>not equal</div> }
}

export default SomeComponent;
```
Problem: 
import fe from 'fast-equals'; remains greyed-out even thought I'm using it.

**Comment by mjbvz** [comment]
I can't repo.

- What is the language mode of the document? (this is shown in the status bar)
- Do other editor features work properly?
- Do you see this if you disable all extensions?

**Comment by velozmontero** [comment]
What is the language mode of the document? (this is shown in the status bar) Javascript
Do other editor features work properly? yes
Do you see this if you disable all extensions?  yes

**Comment by mjbvz** [comment]
Please provide additional repo steps because I don't see this in an empty project:

<img width="1252" alt="screen shot 2018-06-07 at 10 16 36 am" src="https://user-images.githubusercontent.com/12821956/41115301-f1782c70-6a3b-11e8-82e7-55dd764d5732.png">

**Comment by sirianni** [comment]
I have a similar issue.  The language mode is "JavaScript React"

![image](https://user-images.githubusercontent.com/381302/41300186-220439c4-6e33-11e8-8adf-2627a2d17e54.png)

**Comment by mjbvz** [comment]
Please post text along with any screenshots

**Comment by sirianni** [comment]
I updated the comment above (not sure if comment updates generate notifications...)

**Comment by mjbvz** [comment]
I'm still not able to reproduce this issue:

![screen shot 2018-06-12 at 10 33 24 am](https://user-images.githubusercontent.com/12821956/41306806-278c16ca-6e2c-11e8-99ba-3a1436010fc2.png)

- Does the greying out start out this way or do you only see it after editing the file?
- If you run `go to definition` on `React` in `import React`, what file does it open up?
- Does you project has a jsconfig.json? If so, please share that as well

**Comment by velozmontero** [comment]
I just disabled the feature after I posted the issue. I created a react component and imported the module. If you use in method inside the class it goes grey. 
To me the feature is useless because ESLint already tells me when I have memory leaks like unused variables so if you want you can close the issue Im ok with that.

**Comment by sirianni** [comment]
> Does the greying out start out this way or do you only see it after editing the file?

Only after I edit and save the file.

> If you run go to definition on React in import React, what file does it open up?

`declare namespace React {` in `~/.cache/typescript/2.9/node_modules/@types/react/index.d.ts`
However, I expect the false positive for `React` since that isn't actually used in this file (it is required however, by eslint rule `[eslint] 'React' must be in scope when using JSX (react/react-in-jsx-scope)`)

> Does you project has a jsconfig.json? If so, please share that as well

No.

After some trial and error it seems that this line triggers the bug:
```javascript
import { withQueryParams } from 'elmer/dist/components/Router';
```

If I comment that out, it behaves as expected.  The source for `elmer/dist/components/Router` is a `webpack`ed module definition.  Perhaps there is something in there that's breaking the parser.

```javascript
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("prop-types"), require("react"), require("underscore"), require("react-autobind"), require("react-router-dom"), require("react-router"), require("urijs"));
	else if(typeof define === 'function' && define.amd)
		define(["prop-types", "react", "underscore", "react-autobind", "react-router-dom", "react-router", "urijs"], factory);
	else if(typeof exports === 'object')
		exports["elmer"] = factory(require("prop-types"), require("react"), require("underscore"), require("react-autobind"), require("react-router-dom"), require("react-router"), require("urijs"));
	else
		root["elmer"] = factory(root["prop-types"], root["react"], root["_"], root["react-autobind"], root["react-router-dom"], root["react-router"], root["urijs"]);
})(window, function(__WEBPACK_EXTERNAL_MODULE__0__, __WEBPACK_EXTERNAL_MODULE__1__, __WEBPACK_EXTERNAL_MODULE__3__, __WEBPACK_EXTERNAL_MODULE__5__, __WEBPACK_EXTERNAL_MODULE__8__, __WEBPACK_EXTERNAL_MODULE__11__, __WEBPACK_EXTERNAL_MODULE__25__) {
return /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

<SNIP>
```

**Comment by trsdln** [comment]
I'm experiencing similar issue with another NPM package: 

![image](https://user-images.githubusercontent.com/6911494/41337613-61cabe50-6ef8-11e8-830e-046c21a55d70.png)

I'm using `"fluture": "^7.1.1",`.
VSCode Version 1.24.0 (1.24.0)

Hope it will help.

**Comment by mjbvz** [comment]
Can you share the source for `elmer/dist/components/Router`

**Comment by sirianni** [comment]
Yes.  This is the webpack'd version: [index.js.txt](https://github.com/Microsoft/vscode/files/2107182/index.js.txt)

**Comment by mjbvz** [comment]
Thanks. I confirmed this bug and opened https://github.com/Microsoft/TypeScript/issues/24999 to track it upstream 

@velozmontero Do you still see this issue in vscode insiders?

**Comment by mjbvz** [comment]
Closing as we haven't heard back on if this has been fixed in insiders

**Comment by vincentnacar02** [comment]
There is a bug inside the constructor of my ts file class, using a private variable inside the constructor without using **this**, the variable marked as unused.

![image](https://user-images.githubusercontent.com/11674307/42339254-0be76852-80bf-11e8-9c82-760ea23213df.png)

**Comment by mjbvz** [comment]
That is not a bug. The error displayed in the editor is something like `alien2 is written but never read`. You should not create a property if you are not using going to use  `this.alien2` and only reference the parameter in the constructor

**Comment by trsdln** [comment]
@mjbvz Is this bug fixed?

Because issue I was experiencing is still there:

![image](https://user-images.githubusercontent.com/6911494/42373625-3059ee62-811e-11e8-98a4-49f1eed6e8c6.png)

VSCode Version 1.24.1
