### ISSUE TITLE
Cannot format jsx syntax

### ISSUE THREAD

**Issue by Lwenli1224** [Microsoft/vscode#51369]
Issue Type: <b>Bug</b>

Cannot format jsx syntax

![bug](https://user-images.githubusercontent.com/16096724/41112979-054ef748-6ab3-11e8-918b-baea64a19fc0.png)

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (4.64GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_102425|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
vsc-material-theme|Equ|2.1.0
material-icon-theme|PKi|3.5.0
vscode-docker|Pet|0.0.27
ejs-language-support|Qas|0.0.1
vsc-material-theme-italicize|Ser|0.0.14
code-settings-sync|Sha|2.9.2
ejs-snippets|Tao|0.1.0
terminal-tabs|Tyr|0.2.0
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
vscode-caniuse|aka|0.5.3
vscode-javascript-snippet-pack|aka|0.1.5
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-wxml|cod|0.1.9
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.12
app-migrator|deb|0.0.3
githistory|don|0.4.1
gitlens|eam|8.3.4
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
we-app-vscode|eme|0.8.0
prettier-vscode|esb|1.5.0
file-icons|fil|1.0.12
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
terminal|for|0.0.10
vue-snippets|hol|0.1.7
vscode-favorites|how|1.4.0
search-node-modules|jas|1.3.0
webpack|jer|2.1.0
docthis|joe|0.7.1
azure-functions-tools|joh|0.3.3
intellij-idea-keybindings|k--|0.2.23
vscode-codemetrics|kis|1.16.0
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.5.0
vscode-autoprefixer|mrm|2.1.2
vscode-azurefunctions|ms-|0.9.1
vscode-language-pack-zh-hans|MS-|1.24.3
azure-account|ms-|0.4.0
js-atom-grammar|ms-|0.1.14
debugger-for-chrome|msj|4.5.0
vscode-paste-image|mus|1.0.2
vscode-for-node-js-development-pack|nod|1.1.0
vetur|oct|0.12.5
code-rhythm|onv|1.0.4
vuehelper|oys|0.1.0
minapp-vscode|qiu|1.4.0
LiveServer|rit|4.1.0
vscode-icons|rob|7.23.0
vue-vscode-snippets|sdr|1.3.0
markdown-preview-enhanced|shd|0.3.5
language-stylus|sys|1.9.2
react-beautify|tai|0.3.0
react-redux-es6-snippets|tim|2.1.0
pdf|tom|0.3.0
vscode-npm-scripts|tra|0.2.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.6.0

(13 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Probably caused by prettier or one of your other extensions. They have been known to cause this exact issue in the past. Try tracking down which one is causing the problem and file the issue against them
