### ISSUE TITLE
Improve finding symbols 

### ISSUE THREAD

**Issue by GammaGames** [Microsoft/vscode#51360]
I have the following code that uses backbonejs:

```javascript
var com = com || {};
com.library = com.library || {};
com.library.collection = com.library.collection || {};

com.library.collection.Shelf = Backbone.Collection.extend({
    model: com.library.model.Book,

    initialize: function() {
    },

    getLength: function() {
        return "The shelf has " + this.length + " books.";
    },

    getBooks: function() {
        var str = '';
        this.each(function(current) {
            str += current.getTitle() + "\r\n";
        });
        return str;
    },

    comparator: function(a, b) {
        return a.get('year') < b.get('year') ? -1 : 1;
    },
});

com.library.collection.Shelf2 = Backbone.Collection.extend({
    model: com.library.model.Book,

    initialize: function() {
    }
});
```

The current symbols I get in the outline view are:
![image](https://user-images.githubusercontent.com/7832163/41108462-cf470b44-6a31-11e8-9f93-99cfeefcfcbd.png)

Is there a way to improve the symbol parsing so it would show each object and variable, or is my style incompatible with the symbol parser? It would be really handy to show the namespaced objects and their functions.

**Comment by mjbvz** [comment]
Root cause is https://github.com/Microsoft/TypeScript/issues/10868

Not easy to fix. This will also prevent intellisense from working properly on those objects
