### ISSUE TITLE
some keyboard shortcuts ignored in integrated terminal

### ISSUE THREAD

**Issue by mvolkmann** [Microsoft/vscode#51376]
Issue Type: <b>Bug</b>

I have only seen this happen in Windows, not macOS. I created keyboard shortcuts using the alt key and a letter for many commands. When the focus is in an integrated terminal that is running a Windows Command Prompt, many of them just enter the letter instead of running the associated command.

For example, I have this in keybindings.json:

```json
  {
    "key": "alt+r",
    "command": "workbench.action.toggleMaximizedPanel"
  },
```
If the focus is in an editor, pressing alt+r runs the command.
If the focus is in a terminal, this enters the letter "r" in the terminal.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (20.91GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
gitlens|eam|8.3.4
tslint|eg2|1.0.30
prettier-vscode|esb|1.5.0
auto-rename-tag|for|0.0.15
vscode-settings-cycler|hoo|1.0.1
printcode|nob|2.3.0
vscode-code-outline|pat|0.2.1
vscode-versionlens|pfl|0.21.1
vscode-icons|rob|7.23.0
code-spell-checker|str|1.6.10
fish|Ted|0.0.4
sort-lines|Tyr|1.7.0
vim|vsc|0.12.0
quokka-vscode|Wal|1.0.130
vscode-todo-highlight|way|0.5.12

</details>

**Comment by Tyriar** [comment]
This is as designed, see the commandsToSkipShell setting for an explanation.
