### ISSUE TITLE
Expose editor.suggestSelection to extension for customization

### ISSUE THREAD

**Issue by shengyfu** [Microsoft/vscode#51371]
Currently VSCode doesn't expose editor.suggestSelection to extension for customization. This limits specific code extensions' ability to customize the default selection in the completion item list. If an extension needs to rank the completion list (for instance based on a ML model) the extension wants to set the default selection to point to the top ranked item, unless the user wants to override the behavior.

**Comment by MikhailArkhipov** [comment]
How's about `first`, 'lastUsed` and `dynamic` options. In the latter case the selection is specified by the extension. It may not necessarily be the first item.
