### ISSUE TITLE
rpc: can't find method RPCServer.Eval

### ISSUE THREAD

**Issue by andrewmeissner** [Microsoft/vscode#51370]
- VSCode Version: 1.24.0
- OS Version: macOS High Sierra Version 10.13.5

Steps to Reproduce:

1.  Golang debugging with delve
2.  Hit any break point - everything is broken.  trying to "watch" anything yields the error in the subject header (rpc: can't find method RPCServer.Eval).  Trying to evaluate anything in the debug console yields the same error.

Does this issue occur when all extensions are disabled?: Yes/No
No - but only because go debugging isn't supported.

**Comment by stephane-moreau** [comment]
I had the same type of issues a few hours back (no watch variables - no interactive inspection in debug console)
Only stepping  / nexting and tooltip variable inspection did work

Looks like adding useAPIv1 : false to my launch.json configuration do workaround the issue at least for now

**Comment by andrewmeissner** [comment]
@ramya-rao-a 

![pacha](https://user-images.githubusercontent.com/5331913/41140961-73c3c8f8-6aad-11e8-9ff9-cd4a5f2b5fe2.png)

Adding that to my debug configs works great!  Thanks so much for getting me going again!

**Comment by owennewo** [comment]
On linux this setting is case sensitive
Good: `"useApiV1": false`
Bad: `"useAPIV1": false`
