### ISSUE TITLE
Package dependency not found

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#5137]
- VSCode Version: 0.10.11
- OS Version: Linux

I have the following `project.json` file:

```json
{
    "version": "1.0.0-*",
    "description": "Test Console Application",
    "authors": [
        ""
    ],
    "tags": [
        ""
    ],
    "projectUrl": "",
    "licenseUrl": "",
    "tooling": {
        "defaultNamespace": "CSharp-gtk"
    },
    "commands": {
        "ConsoleApplication": "MainApp"
    },
    "frameworks": {
        "dnx451":{
            "dependencies": {
                "GtkSharp": "3.1.3"
            }
        }
    }
}
```

I then have the following `using` statements in my `MainApp.cs` file:

```csharp
using System;
using Glade;
using Gtk;
```

Even though VSCode can't find the `Glade` item, I can still run it with the following command:

`mcs -pkg:glade-sharp-2.0 -out:build/MyPackage Source/MainApp.cs`

So, is there a way for me to reference the `glade-sharp-2.0` item so I can get intellisense to work with it?

**Comment by egamma** [comment]
Moving to vscode-omnisharp for investigation.

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#166
