### ISSUE TITLE
Auto-update failed on Windows 7

### ISSUE THREAD

**Issue by Rhywun** [Microsoft/vscode#51383]
The auto-update to the latest May 2018 version failed. Log attached.

WIndows 7 Enterprise SP 1

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2081784/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
@Rhywun Thanks for the pointer.

@roblourens It seems that `rg.exe` kept executing even after Code has quit.

**Comment by roblourens** [comment]
@Rhywun Was rg.exe using high CPU before you killed it? If you happen to see this again, please get the command line arguments from that rg.exe process.

**Comment by Rhywun** [comment]
@roblourens I did not notice that it was using high CPU so probably not.

> If you happen to see this again, please get the command line arguments from that rg.exe process.

Is that visible somewhere in Task Manager? I'm not seeing it.

**Comment by roblourens** [comment]
Yes, I think you have to add a column with that info to Task Manager.

**Comment by roblourens** [comment]
From what I understand, rg.exe should have died when its parent died. I call `.kill` on the process on `process.on('exit'` and there isn't time before the process shuts down to do any extra cleanup if that fails for some reason. Any suggestions there @joaomoreno?

**Comment by joaomoreno** [comment]
Bit lost too... I believe Code is shutdown gracefully: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/update/electron-main/abstractUpdateService.ts#L143

**Comment by roblourens** [comment]
I'm not sure what else to do here, but @Rhywun please keep an eye open for other zombie rg.exe processes and let me know if you see more. Besides updating, even just after a normal shutdown.
