### ISSUE TITLE
Emojis don't take enough space, some stay floating.

### ISSUE THREAD

**Issue by berithpy** [microsoft/vscode#51385]
![screenshot from 2018-06-07 15-26-14](https://user-images.githubusercontent.com/8316977/41121780-62ab0928-6a67-11e8-8d32-42a59aa6dbbd.png)
I found similar issues but not exact ones. I was scrolling through my shell history with the up arrow in the keyboard and after going past some emojis they stayed floating there (the eggplant and fire one) after clearing and changing folders some of the remnants disappeared.

- VSCode Version: 1.24
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1.Use color emojis on the terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by berithpy** [comment]
Some more info, it looks like the emojis remove spaces from their left when you are scrolling through your shell history.

**Comment by Tyriar** [comment]
Created upstream issue: https://github.com/xtermjs/xterm.js/issues/1502

@berithpy can you comment exact repro steps how you got to this state? Really granular at like the keystroke level like "foo", enter, etc...

**Comment by berithpy** [comment]
ok!  
- Open the integrated terminal
- Create a folder with an emoji as its name with ```mkdir 🍆```
- Open the folder with ```cd 🍆```
- Use ```ls ```
- Scroll through those three commands with ↑ key or ↓ key like this ↑↑ ↓↓  ↑↑ ↓↓ ↑↑ ↓↓ multiple times.

To input the emojis I pasted or wrote them with the special character input (ctrl+shift+u) it didn't seem to make a difference.
Gif example, sorry for the quality!
![emoji4](https://user-images.githubusercontent.com/8316977/41168008-acdf5a2a-6b12-11e8-916a-bb5b85c54b90.gif)

**Comment by vexx32** [comment]
I'd also like to bring up that a majority of Gitmoji do not render correctly:

![image](https://user-images.githubusercontent.com/32407840/51434611-2ae3e900-1c33-11e9-8ed7-22fc0a96425f.png)

Not sure if this should be in a separate issue or not, though. 😄

**Comment by seva0stapenko** [comment]
The issue with emoji spacing and subsequent issues with viewing/editing commands from history can be observed on Macs as well. My setup is OSX Mojave 10.14.6 and VSCode 1.38.1.
PS1 is defined as:
PS1="[\[\033[01;38;5;46m\]\u\[\033[00m\]🌀\h: \[\033[01;38;5;46m\]\W\[\033[00m\]] $ "

(At) emoji is clipped in VSCode terminal window.
Editing/viewing bash command history is a mess, especially with long commands that span more than a single line.

**Comment by Tyriar** [comment]
Artifacts left -> https://github.com/xtermjs/xterm.js/issues/1502

The half width thing is tracked in https://github.com/xtermjs/xterm.js/issues/1709
