### ISSUE TITLE
Accessing the extensions menu hangs forever

### ISSUE THREAD

**Issue by chrisseto** [Microsoft/vscode#5138]
- VSCode Version:  0.10.11
- OS Version: OSX Yosemite 10.10.5 (14F1605) 
![screen shot 2016-04-10 at 23 33 18](https://cloud.githubusercontent.com/assets/5532905/14416169/0560d91e-ff75-11e5-8729-92bc8e46374e.png)

Steps to Reproduce:

1. Press `^ + Shift + P`
2. Hit `install extensions` or `show install extensions`
3. Wait forever

No console errors pop up and no network requests pop up either.
I've deleted every file and folder on this computer with the `VSCode` in the name and still encounter this issue.

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by chrisseto** [comment]
@joaomoreno I'm not behind a proxy.
I've tried both with and without a VPN and on different networks/ISPs.

Should I be expecting to see network requests in the network tab?

**Comment by chrisseto** [comment]
The problem went away on its own after upgrading to 1.0

**Comment by joaomoreno** [comment]
Good to know!
