### ISSUE TITLE
Outline view sorting seems to be random

### ISSUE THREAD

**Issue by plmcgrn** [Microsoft/vscode#51389]
Issue Type: <b>Bug</b>

Tested with PowerShell code

When viewing the Outline, the order of the symbols does not correspond in any way to the order they are defined in the code editor.  Variables are at the top of the code, but at the bottom of the outline.  Functions at the top of the editor are in the middle of the Outline, etc.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.95GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_5149929|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.1
PowerShell|ms-|1.7.0
vscode-open-in-github|ziy|1.3.1

</details>

**Comment by plmcgrn** [comment]
![image](https://user-images.githubusercontent.com/889547/41123670-7206a7be-6a6d-11e8-89ae-591657c4d80a.png)

**Comment by jrieken** [comment]
stable sort issue, cannot find the dupe right now...
