### ISSUE TITLE
Why does the install directory contain api-ms-win-core-*.dll files?

### ISSUE THREAD

**Issue by Siecje** [Microsoft/vscode#51386]
I just installed VS Code on `Windows 10 version 1709 (OS Build 16299.431)` and noticed that there are
`api-ms-win-core-*.dll` files in the install directory `C:\Program Files\Microsoft VS Code\`

Since they are system API sets they should be installed by the OS.

I do have those files in `C:\Windows\System32\downlevel\`

**Comment by bpasero** [comment]
This is part of the Electron framework we are using, I suggest you ask this at their repository here: https://github.com/atom/electron

**Comment by Siecje** [comment]
I tried asking the Electron project[0], but they said it was not an Electron issue.

I'm curious if it is required to have the Universal C Runtime in Windows[1] in the installation directory.

The Universal C Runtime comes with Windows 10, and will be installed on older versions of Windows through Windows Updates.

I believe the correct thing to do is to check if `ucrtbase.dll` is available using `LoadLibraryEx`[2] and if it is not then install the package (.msu) for the current operating system[1].

This makes it available in the system directory and updates will be managed by Windows Update.

0: https://github.com/electron/electron/issues/13197
1: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows
2: https://msdn.microsoft.com/en-us/library/windows/desktop/ms684179(v=vs.85).aspx
