### ISSUE TITLE
Can't not resolve workspace folder

### ISSUE THREAD

**Issue by mogarick** [Microsoft/vscode#51382]
Issue Type: <b>Bug</b>

I created a workspace and added a couple of folders but vscode highlights them in yellow with an exclamation mark. Hovering it the messages says ""Can't not resolve workspace folder" but the weird thing is that the folder is showing its contents correctly.

![screen shot 2018-06-07 at 1 20 26 pm](https://user-images.githubusercontent.com/4414145/41118452-9c2856ae-6a55-11e8-835f-6aafb8edbab7.png)

this is the file tree for the project and workspace (file example with fake folders names but same structure)

/Volumes/MySecondaryDisk/OtherFolder
- myworkspace.code-workspace
- folder01
  - mywsfolder01
  - mywsfolder02
- folder02

my workspace file has the the following content

```
{
	"folders": [
		{
			"path": "folder01/mywsfolder01"
		},
		{
			"path": "folder02"
		},
		{
			"path": "folder01/mywsfolder02"
		}
	],
	"settings": {}
}
```

I don't know whys is this behaviour happening.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz (2 x 2660)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 5, 6|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_3203854|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|0.3.2
xml|Dot|2.2.0
yuml|Jai|3.1.1
material-icon-theme|PKi|3.5.0
vscode-docker|Pet|0.0.27
vscode-boot-dev-pack|Piv|0.0.4
vscode-concourse|Piv|0.2.1
vscode-manifest-yaml|Piv|0.2.1
vscode-spring-boot|Piv|0.2.1
vscode-wakatime|Wak|1.2.2
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.4
vscode-nomnoml|doc|0.3.0
gitlens|eam|8.3.4
json-tools|eri|1.0.2
code-runner|for|0.9.3
svn-scm|joh|1.29.1
dotenv|mik|1.0.1
mssql|ms-|1.3.1
debugger-for-chrome|msj|4.5.0
gradle-language|nac|0.2.3
color-highlight|nau|2.3.0
polacode|pnp|0.2.2
qub-xml-vscode|qub|1.2.8
java|red|0.26.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
vscode-spring-initializr|vsc|0.3.0
vscode-todo-highlight|way|0.5.12
JavaScriptSnippets|xab|1.6.0

(4 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/50866

**Comment by ArmandoValencia** [comment]
Change your workspace config to something like this:

`{
	"folders": [
		{
			"path": "C:/folder01/mywsfolder01"
		},
		{
			"path": "C:/folder02"
		},
		{
			"path": "C:/folder01/mywsfolder02"
		}
	],
	"settings": {}
}`

Save, then restart VsCode.
