### ISSUE TITLE
Highlighting under cursor broken in vscode 1.24

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#51390]
- VSCode Version: 1.24
- OS Version: OSX 10.13.4

Steps to Reproduce:
VSCode 1.23 highlighting
<img width="245" alt="image" src="https://user-images.githubusercontent.com/10656375/41123657-609a953a-6a6d-11e8-9342-c2c55d1106c7.png">

VSCode 1.24 highlighting
<img width="243" alt="image" src="https://user-images.githubusercontent.com/10656375/41123712-91c1f702-6a6d-11e8-81f6-3a3fbdc0bf27.png">

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rebornix** [comment]
Related https://github.com/Microsoft/vscode/issues/51335 , I suppose it's caused by our newly introduced `z-index` for decorations. @alexandrudima

**Comment by alexandrudima** [comment]
@rebornix I don't think this is related to #51335 at all. It might be caused by https://github.com/Microsoft/vscode/commit/8f0d370203e0649a339c657d834b2c5516424402#diff-e653ac38a64dd65c7e3f8438feb8a094

**Comment by alexandrudima** [comment]
Copy-Paste friendly repro:

```json
{
    "tracers": [
        {
            "name": "request"
        },
        {
            "name": "bar"
        }
    ]
}
```
