### ISSUE TITLE
Typescript separate formatting rules for anonymous functions / lambdas

### ISSUE THREAD

**Issue by vrachels** [Microsoft/vscode#51395]
Requesting additional functionality to differentiate the formatting between anonymous and named functions.
ie: "typescript.format.placeOpenBraceOnNewLineForAnonymousFunctions": boolean
or: "typescript.format.placeOpenBraceOnNewLineForInlineFunctions": boolean

similarly, having a separate indentation pattern would be ideal.
the main gripe is that with new line for functions = true, the anonymous/inline functions end up looking something like:
```
foo()
{
    array.forEach(() =>
    {
       // bar
    });
}
```
while my preferred is more like one of:
```
fooWithInlineNewLineFalse()
{
    array.forEach(() => {
        // bar
    }
}
fooWithInlineIndent()
{
    array.forEach(() =>
        {
            // bar
        }
}
fooWithBoth()
{
    array.forEach(() => {
            // bar
        }
}
```

Before posting, my researched showed that switch/case indenting has similar outstanding issues as well, but nothing related to this particular area.

I don't see any way for vscode to customize either situation.  Pointers to an extension that supports such things would be happily appreciated.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24777
