### ISSUE TITLE
cursorWordStart* treating certain special characters like words half the time

### ISSUE THREAD

**Issue by davelogear** [Microsoft/vscode#51398]
I just discovered the solution to the Ctrl+left/right arrow key issue where the cursor would plop at the beginning or end of the word (depending on which direction you going, causing selection frustration) - https://github.com/Microsoft/vscode/issues/34457 - but now I notice that the cursor will plop at the beginning of a certain character if I'm going right but skip it going left... rather than having a consistent expected cursor drop, causing selection frustration. 

Other editors and even this message box puts the cursor at the beginning of each word or character _consistently_ no matter which direction you're going.

Example: 

(JavaScript) `if(message.includes('whatever'))` - If the cursor is at the beginning of 'message' then you hit Ctrl+right, the cursor will stop before the period; if the cursor is at the end of 'includes' and you hit Ctrl+left, the cursor will plop at the beginning of it but hitting it again doesn't put the cursor at the beginning of the period, it just goes to the beginning of 'message'.

In JetBrains editors, using Ctrl+right/left always stops at the period (even though I'd prefer it to skip the period or in-between glue either way since it's minimal to just let go of Ctrl while keying). Yes I know I can just click with the mouse but that takes forever and is more mistake-prone.

- VSCode Version: 1.23.1
- OS Version: Windows 7 Pro 64-bit

Steps to Reproduce:

1. I pretty described how to reproduce above. Make a code file, type some valid code, notice how Ctrl+right/left arrow behave nonsensically.

Does this issue occur when all extensions are disabled?: Yes

**Comment by zeromus** [comment]
I believe this is the same issue https://github.com/Microsoft/vscode/issues/51119

**Comment by alexandrudima** [comment]
Yes, let's track in #51119
