### ISSUE TITLE
Support JSDoc type information

### ISSUE THREAD

**Issue by Zumbala** [Microsoft/vscode#514]
Below a JSDOC comment which does not show properly in document type javascript.

```
// Interface new functions
/**
 * @param  {Object} to
 * @param  {Object} from
 * @param  {Boolean|String} override=false
 */
function Interface(to,from,override) {
       // some code
    }
```

It always shows **"to:any, from:any, override:any"**
why not **"to:any, from:any, override:Boolean=false|String"** or something simular

**Comment by satahippy** [comment]
+1

**Comment by TerrorBite** [comment]
+1

**Comment by zoo-zoo** [comment]
+1

**Comment by Thaina** [comment]
Now this already one with salsa, take a look at typescript

**Comment by mlewand** [comment]
Any updates in this regard? This would be a great addition for JavaScript development! 😺

**Comment by mjbvz** [comment]
Try out VSCode 1.7. The TypeScript team added this feature, and I believe that we now correctly pick up type info from jsdoc comments.

![jsdo](https://cloud.githubusercontent.com/assets/12821956/20449065/01a7bb82-ad9c-11e6-9249-058599e7109a.png)

Please let me know if you run into any issues. Thanks.

**Comment by poislagarde** [comment]
@mjbvz it still doesn't work for object properties:

```js
/**
 * @param {Object} bar
 * @param {number} bar.str
 */
function foo(bar) {}
```

I'm also not sure how I should reference types defined in npm modules, i.e.:

```js
/**
 * @param {mongodb.ObjectID} bar
 */
function foo(bar) {}
```

**Comment by mjbvz** [comment]
The first issue is a known limitation of TypeScript currently. It is being tracked upstream here: https://github.com/Microsoft/TypeScript/issues/11597

As a work around, you can use the syntax:

```js
/**
 * @param {{ str: number }} bar
 */
function foo(bar) { }
}
```


For the second case, I think TS only supports `import` right now:

```js
import * as mongodb from 'mongodb'

/**
 * @param {mongodb.MongoClient} bar
 */
function foo(bar) {}
```
