### ISSUE TITLE
Unused detection & template-based frameworks

### ISSUE THREAD

**Issue by fedoranimus** [Microsoft/vscode#51405]
I'm not sure how best to support this, but one issue with flat-out highlighting "unused" code is that sometimes it's used in unparseable files by the IDE.

For instance, in many template based Javascript frameworks (Aurelia, for example), properties and methods may only be referenced by the HTML templates that the `.ts` file is paired with.

This leads to many false positives being highlighted as "Unused".

Perhaps a `// js-doc` type syntax could be read to alleviate this?

```
// test-view.html
<button click.delegate="showAddDialog()">Add</button>
```

```
// test-view.ts
public showAddDialog() {
 // ...
}
```
`showAddDialog()` will be highlighted as it's never referenced in `test-view.ts`, but removing it will cause many headaches as the click action will now throw an exception. (Granted, there are several other issues with template-based frameworks and code traceability)

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/24790 to track this upstream
