### ISSUE TITLE
sidebar can move file OR cut file

### ISSUE THREAD

**Issue by beroft** [Microsoft/vscode#51401]
Issue Type: <b>Feature Request</b>

I hope the sidebar can move file or cut file. now I must in the finder do this.

VS Code version: Code - Insiders 1.25.0-insider (43cb490a3bdb7388ef8f919c238f062cc66b4738, 2018-06-07T17:28:27.924Z)
OS version: Darwin x64 17.6.0

**Comment by aeschli** [comment]
With 'sidebar' do you mean the 'explorer'?
The explorer support drag & dropping of files (move). By holding down `alt` it will copy.

**Comment by beroft** [comment]
In the explorer, I know drag & dropping of files (move), but if I open too many folders and files drag & dropping of files will be slow, I must scroll the location folder.

**Comment by chrmarti** [comment]
The Explorer's context menu only has Copy. The request is to have Cut too.
