### ISSUE TITLE
Unused values feature

### ISSUE THREAD

**Issue by thenexus00** [Microsoft/vscode#51406]
Issue Type: <b>Bug</b>

With the new unused value feature I have noticed that if I set the values within if statements it still things that it is not being used, even though it is.
If You have set something with a default value and call it later that should be considered used?

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
beautify|Hoo|1.3.0
html-snippets|abu|0.2.1
Bookmarks|ale|0.19.1
vscode-color|ans|0.4.5
razor-plus|aus|0.1.4
htmltagwrap|bra|0.0.7
vscode-svgviewer|css|1.4.4
githistory|don|0.4.1
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.5.0
live-html-previewer|hdg|0.3.0
vscode-nuget-package-manager|jmr|1.1.6
drupal-7-snippets|jun|0.0.7
vscode-liquid-snippets|kil|1.1.0
sftp|lix|1.1.11
VS-code-drupal|mar|0.0.12
ecdc|mit|0.12.0
prettify-json|moh|0.0.3
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.264
debugger-for-chrome|msj|4.5.0
language-liquid|nei|0.0.3
vscode-css-peek|pra|2.1.0
pdf|tom|0.3.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.6.0
ReactSnippets|xab|2.1.0

(7 theme extensions excluded)

</details>

**Comment by thenexus00** [comment]
Example:

```
var link =  click.attr('href'),
searchVal = $('input#edit-query').val(),
searchType = '?';
```

```
if ( link.indexOf('?') > 0 ){
   searchType = '&';
}else{
   searchType = '?';
}
```

**Comment by alexfung888** [comment]
you only write to searchType. It is never read.

**Comment by mjbvz** [comment]
Yes,  a variable is only ever written to, it is marked as unused
