### ISSUE TITLE
Really need 'find in file'.

### ISSUE THREAD

**Issue by FFengIll** [Microsoft/vscode#51410]
Now we can right click folder and `find in folder` using vscode search. (thanks for the good feature!)
But why not a `find in file` for convenience? (really need this for most of the time)
I have checked the code and it is easy to add this feature - I just doubt the reason to pass it.
Thanks.

**Comment by FFengIll** [comment]
furthermore, we can not search file name. (though we have many other methods)

**Comment by shane-smith** [comment]
(Replace Cmd with Ctrl if you are on Windows)

Cmd+P allows you to open any file based on the file name.
Cmd+F allows you to then search in the currently open file.

**Comment by roblourens** [comment]
I've got https://github.com/Microsoft/vscode/issues/48958, sounds like that's what you're looking for.

**Comment by FFengIll** [comment]
@shane-smith yep, we can do that, but cmd+f can not search all and show all in one time (think about the search view on the side).

**Comment by shane-smith** [comment]
Hi @FFengIll - try Cmd+Shift+F for that.

You can then press down/up arrow to look through results, and it'll open up the preview on the right.

I think that is what you're asking for?
