### ISSUE TITLE
Allow variable substitution in extension, workplace, and other settings files.

### ISSUE THREAD

**Issue by irvinec** [Microsoft/vscode#51412]
I work on Windows and we usually have at least two windows repos on our dev machines that have their own set of build settings. I like to create workplaces for parts of the code that I work on often or I am working on in that moment. It would be nice to not have to create workplace files for each repo and each build flavor that I use. e.g. in my .code-workplace file (... is just committing part of the path):

"folders": [
        {
            "path": "${env:SDXROOT}/onecoreuap/.../lib"
        },
        {
            "path": "${env:SDXROOT}/.../winrt"
        }
    ],
...
"C_Cpp.default.includePath": [
            "${workspaceFolder}",
            "${env:SDXROOT}/...",
            "${env:SDXROOT}/.../published/winrt",
            "${env:SDXROOT}/onecoreuap/.../inc",
            "${env:OBJECT_ROOT}/onecore/.../${env:O}",
            "${env:SDXROOT}/onecore/published/inc"
 ],

This way vscode would be configured based on what build window and repo I opened it in.
Thanks!

**Comment by sandy081** [comment]
@irvinec Are you looking for variable substitution for folders section or in other sections too? For me, from Description it looks to me only for folders?
