### ISSUE TITLE
Integrated terminal display problem

### ISSUE THREAD

**Issue by ciaojhen** [Microsoft/vscode#51418]
- VSCode Version:1.24.0
- OS Version:win10 1803

Steps to Reproduce:

1. While pulling terminal windows, display will be wrong.
![vscodebug](https://user-images.githubusercontent.com/22856021/41140391-ddb3451e-6b1f-11e8-81d1-64a87634445d.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
