### ISSUE TITLE
unable to update 

### ISSUE THREAD

**Issue by pankajsaini123** [Microsoft/vscode#51415]
Issue Type: <b>Bug</b>

I am using vs code, and i am facing issue regarding updates .
why it always require admin permission to start, and
It able to fetch updates but does not able to update.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 6.0.6002

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|7.92GB (4.17GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|0.2.0
beautify|Hoo|1.3.0
trimspaces|igo|0.0.24

</details>

**Comment by joaomoreno** [comment]
> It able to fetch updates but does not able to update.

What do you mean not able? Did you get an error? If so, do you have a screenshot/logfile?
