### ISSUE TITLE
Two windows opening while opening through context menu.

### ISSUE THREAD

**Issue by inkxe-biswajit** [Microsoft/vscode#51419]
- VSCode Version: 1.24
- OS Version: Windows 7

Steps to Reproduce:
 I have opening more than two projects previously in VSCode . After update vsCode I found this issue. Please check.
1. Right Click on Project folder (In window explorer) -> Click on "Open With Code". 
2. Two windows are opening simultaneously. See the attached images.
![image](https://user-images.githubusercontent.com/20985890/41140463-4b676dac-6b0b-11e8-969b-7983d2050af6.png)
![image](https://user-images.githubusercontent.com/20985890/41140740-bfa622fc-6b0c-11e8-8655-363c8a4cdda3.png)

Does this issue occur when all extensions are disabled?: Yes/No : No

**Comment by bpasero** [comment]
This is expected if you carry over dirty files from a previous session.
