### ISSUE TITLE
Themeable "Unused variables are greyed-out"

### ISSUE THREAD

**Issue by kraftwer1** [Microsoft/vscode#51420]
I love this new feature! However, it would be great to allow me as a theme author to override the default "greyed-out" color to match it with my color scheme.

Here's an example of an unused import:

```import { foo } from "bar";```

**Inspect TM Scope (now) (not differentiable from an _used_ import)**

```
keyword.control.import.ts
meta.import.ts
source.ts
```

**Inspect TM Scope (expected)**

```
keyword.control.import.ts
meta.unused.ts # something like that - maybe there's a better name?
meta.import.ts
source.ts
```

**Comment by mjbvz** [comment]
This is already supported using the `editorUnnecessary.foreground` theme color:

```json
"workbench.colorCustomizations": {
    "editorUnnecessary.foreground": "#ff00ff"
}
```

**Comment by dedmazayukr** [comment]
In version

**Comment by dedmazayukr** [comment]
With last update **missed option** `"editorUnnecessary.foreground"`

Version: 1.25.0
Commit: `0f080e5267e829de46638128001aeb7ca2d6d50e`
Date: 2018-07-05T13:10:37.273Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
![image](https://user-images.githubusercontent.com/22115961/42414330-298c4d90-823c-11e8-8c45-4b04b16d729d.png)
