### ISSUE TITLE
[Esc] key to close keyboard shortcuts editor

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#51426]
Not all windows opened with keyboard shortcuts may be closed  with `Esc` key. A case in point is **Keyboard shortcuts** window.

## Workflow
1. Click `Ctrl+K`, `Ctrl+S`
2. Keyboard shortcuts window appears.
3. Click `Esc`. You expect to close a window, but it is not closed.

**Comment by sandy081** [comment]
@wzup Do you Esc configured to close editor ?

**Comment by wzup** [comment]
Not sure I clearly understand what you mean. 
`Esc` is not configured to close editor. 
`Ctrl+Shift+W` is set to close editor.

This is what is opened on `Ctrl+K` `Ctrl+S`. And when I click `Esc` this window (or tab?) is not being closed.

![selection_808](https://user-images.githubusercontent.com/3880497/41171059-cf228cfc-6b57-11e8-9343-2f489ebf9e57.png)

An example of close with `Esc`, try:
1) `Ctrl + Shift + P`. Popup appears.
2) `Esc`. Popup disappears. 

I expect the same behavior for `Ctrl+K`, `Ctrl+S`.

**Comment by codestothestars** [comment]
As a user, I find this interesting. In probably most applications, the keyboard shortcut editor appears in a separate settings window that `Esc` would typically close, whereas here in VS Code, it's just in a special kind of editor/tab. Personally, I'm already used to closing this with `Ctrl+W`, but given that this is a settings-related context, I can see why someone would expect `Esc` to work.

**Comment by codestothestars** [comment]
Also, seems like the title might be better as "[Esc] key to close keyboard shortcuts editor".

**Comment by sandy081** [comment]
Yeah, Keybindings and Settings preferences are editors and closing editor command applies to these. `Esc` is used to search clear filter which is the common pattern in VS Code. I am not convinced to use `Esc` for closing the editor.
