### ISSUE TITLE
Timeout: Test Search replaces first search result with a replace term

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#51427]
https://vscode.visualstudio.com/VSCode/_build?buildId=1669

   1) Test Search replaces first search result with a replace term:
      Error: Timeout: get text content 'div[id="workbench.view.search"] .search-view .messages[aria-hidden="false"] .message>p' after 20 seconds.
       at D:\a\1\s\test\smoke\out\vscode\code.js:142:23
       at Generator.next (<anonymous>)
       at fulfilled (D:\a\1\s\test\smoke\out\vscode\code.js:8:58)
       at <anonymous>

**Comment by joaomoreno** [comment]
Not sure what goes on here. Pushed a change which introduces some delay between `mouseDown` and `mouseUp`, when simulating a click. Hopefully that is it. Let's keep this one meanwhile.

**Comment by joaomoreno** [comment]
Closing for now
