### ISSUE TITLE
Cursor Redo

### ISSUE THREAD

**Issue by samholmes** [microsoft/vscode#51429]
Looks like cmd+u is available to undo your cursor positioning, but there is no cursorRedo function. cmd+shift+u brings up the output pane. In sublime text, cmd+shift+u is a cursor redo shortcut. I'd like to be able to redo cursor positioning.

**Comment by suigh** [comment]
The "cursor redo" is a very useful feature, especially when you checking the codes go back and forth.  

"Cursor doesn't move in a redo operation (#15761)" cannot handle this request as it is talking about "ctrl+z", it is about how to undo the operations instead of the cursor position.

**Comment by alexdima** [comment]
In the meantime, there is now a cursor redo action.
