### ISSUE TITLE
Timeout: Test Git stages correctly

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#51425]
https://vscode.visualstudio.com/VSCode/_build?buildId=1671

   1) Test Git stages correctly:
      Error: Timeout: get elements 'div[id="workbench.view.scm"] .monaco-list-row > .resource' after 20 seconds.
       at D:\a\1\s\test\smoke\out\vscode\code.js:142:23
       at Generator.next (<anonymous>)
       at fulfilled (D:\a\1\s\test\smoke\out\vscode\code.js:8:58)
       at <anonymous>

**Comment by chrmarti** [comment]
Same as first: https://vscode.visualstudio.com/VSCode/_build?buildId=1683

**Comment by joaomoreno** [comment]
Closing for now.
