### ISSUE TITLE
please allow to pass parameters to the DVCS (version control) pane.

### ISSUE THREAD

**Issue by kobi2187** [Microsoft/vscode#51423]
I would like to pass a command such as this to `hg`:
`hg status 'set:unknown() and not binary()'`
I can do this in the terminal, but wonder if I can pass parameters to the built in version control gui. 
Can you please add a configuration option so I can append extra parameters to the command?
Thanks!

**Comment by joaomoreno** [comment]
Mercurial is an extension. Please file this issue in the appropriate repository: https://marketplace.visualstudio.com/items?itemName=mrcrowl.hg
