### ISSUE TITLE
syntaxFolding is not working in javascript-react Jsx section

### ISSUE THREAD

**Issue by YouWillBe** [Microsoft/vscode#51421]
- VSCode Version:v1.24.0
- OS Version:Mac OS X High Sierra 10.13.5

Steps to Reproduce:

1.syntaxFolding is not working in javascript-react Jsx section

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by simida0852** [comment]
I also encountered the same problem:sweat::sweat::sweat:

**Comment by YouWillBe** [comment]
@simida0852 巧了，老铁

**Comment by mjbvz** [comment]
Duplicate of #51266

**Comment by 1412108** [comment]
Have this isssue fixed ?
