### ISSUE TITLE
find files include patterns do not look for folder matching

### ISSUE THREAD

**Issue by ssbarnea** [Microsoft/vscode#51436]
- VSCode Version: 1.23.1
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. Add two folders to your workspace, foo and bar.
2. Shift-Cmd+F to open find dialog
3. Put a string inside search box and put "bar" (or "bar/*")  inside files to include box"
4. perform a search

Apparently you cannot put folder patterns there, they just don't work. 

The **same feature works very well inside atom**, where you can narrow down the search area by mentioning the folder name. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
You can do this with `./foo and ./bar`. Patterns without ./ are patterns that are applied inside the folders.
