### ISSUE TITLE
Task "haxe: active configuration" not found

### ISSUE THREAD

**Issue by ncannasse** [Microsoft/vscode#51431]
- VSCode Version: 1.24.0

We used to reference the preLaunchTask by its "label" property and it works great. Now we are looking into using the task name instead (see discussion here https://github.com/vshaxe/vshaxe/issues/230) and it seems to work on most computers, expect on some of them where the task cannot be found.

Here's an example launch.json using HashLink-debugger extension:

```js
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "ProjectName",
            "request": "launch",
            "type": "hl",
            "hxml": "project.hxml",
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "haxe: active configuration"
        }
    ]
}
```

On most computers, VSCode will successfully locate and launch the preLaunchTask. On few of them, it will error with `Task 'haxe: active configuration' not found` while the Haxe support extension is correctly installed and working.

The `haxe: active configuration` task is correctly listed when pressing Shift+Ctrl+B and runs succesfuly.

We tried full VSCode uninstall + removing extensions + reinstall from scratch and the issue persists on these computers. Any advice about what might cause the task not to be recognized in launch.json preLaunchTask is welcome.

**Comment by isidorn** [comment]
This sounds like an issue in tasks that it can not find the passed taskName
However from tomorrow's insiders we are supporting that in `preLaunchTask` ( and `postDebugTask`) you can reference a task using a task identifier, so in your example it would be
"preLaunchTask": {
"type": "haxe"
"label": "active configuration"
}

Note that the "label" is customizied by your extension and I am not sure what is the exact name,
Forwarding to @dbaeumer 
@ncannasse and you can try tomorrow's insiders

**Comment by ncannasse** [comment]
@isidorn any reason why the task could not be found on some computers and still work on most others?

**Comment by dbaeumer** [comment]
I am very confident that the computers that can't find the task run under a French locale. Under French the label is correctly generated as `haxe : active configuration` (notice the space after haxe). This got fixed with the allowing to reference tasks via its type identifier. As a work around you can give the tasks a label in the tasks.json file which you then use. 

I am closing the issue as a dup of https://github.com/Microsoft/vscode/issues/50799

**Comment by ncannasse** [comment]
Some up on this issue: you're right I'm on french locale, but it shouldn't really be locale dependent...
Also, I tried today using 
```"prelaunchTask" : {
"type": "haxe",
"label": "active configuration"
}```

Using VSCode 1.25.0, and I'm getting an error `Task {0} cannot be found`.  Any insight/workaround?

**Comment by Gama11** [comment]
You need to use `args` instead of `label`, since [that's what the task definition looks like](https://github.com/vshaxe/vshaxe/blob/753641f560fb033d2f14ee1b31bd1db823bf9a4b/package.json#L951-L968) - this works for me:

```json
"preLaunchTask": {
	"type": "haxe",
	"args": "active configuration"
}
```
