### ISSUE TITLE
remove (overlay) section on CMD + CLICK

### ISSUE THREAD

**Issue by Xestero** [Microsoft/vscode#51437]
Issue Type: <b>Performance Issue</b>

How to "go to definition" without (overlay) section?
<img width="1459" alt="screen shot 2018-06-08 at 11 16 14" src="https://user-images.githubusercontent.com/12487768/41150294-e7c0d65a-6b0d-11e8-9937-88a119941684.png">

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.67GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Workspace Info</summary>

```
|  Window (MenuBtn.js — Untitled (Workspace))
|    Folder (web): 895 files
|      File types: js(670) json(44) css(19) otf(18) woff(14) woff2(14)
|                  scss(14) ttf(14) less(14) png(14)
|      Conf files: package.json(2) jsconfig.json(1) launch.json(1)
|                  settings.json(1) gulp.js(1)
|      Launch Configs: node(3) chrome;
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
react-native-react-redux|EQu|1.9.0
solidity|Jua|0.0.43
Angular-BeastCode|Mik|6.0.15
material-icon-theme|PKi|3.5.0
vscode-wakatime|Wak|1.2.2
html-css-class-completion|Zig|1.17.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
vscode-dash|dee|1.10.0
es7-react-js-snippets|dsz|1.7.0
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
vscode-npm|fkn|3.3.0
solidity-solhint|idr|1.1.4
team|ms-|1.136.0
debugger-for-chrome|msj|4.5.0
vscode-versionlens|pfl|0.21.1
sass-indented|rob|1.4.9
vscode-react-native|vsm|0.6.10
ReactSnippets|xab|2.1.0

</details>

**Comment by aeschli** [comment]
@Xestero Can you add a screenshot to show what you mean by '(overlay) section' ?

**Comment by Xestero** [comment]
<img width="1642" alt="screen shot 2018-06-08 at 12 33 54" src="https://user-images.githubusercontent.com/12487768/41153925-96e79cfe-6b18-11e8-8735-94173e45a807.png">

**Comment by SimpelFix** [comment]
Can reproduce.

If you click "Go to definition" (F12, CTRL+Click, Go-menu, right click menu), no only does vscode navigate to the definition but also open a "peek definition" window.

**Comment by jrieken** [comment]
Yeah, that happens when a symbol has more than one definition. VS Code doesn't randomly pick/favours one but shows both.

**Comment by SimpelFix** [comment]
In Typescript "Go to definition" for non-prototype-methods will find two 'definitions'. Is this intended?

For example:

```typescript
class GoToDefinitionTest {
    constructor() {
        /** 'go to definition' will find definition and body */
        this.methodNonPrototype();
        /** 'go to definition' will find defintion */
        this.methodPrototype();
    }

    private methodNonPrototype = () => {
        console.log('methodNonPrototype');
    };
    private methodPrototype() {
        console.log('methodPrototype');
    }
}
```
![2018-06-08_16-48-07](https://user-images.githubusercontent.com/11723561/41164676-0590061e-6b3c-11e8-9546-5d6139facafc.png)

**Comment by Xestero** [comment]
What u mean with "symbol"?
In my code its only one definition of (example) "buildNormalizedDataSource"
But its display two definitions (same definition) and  overlay up to ~30% of screen
How to remove this section with all definitions on click "Go to definition". I will just go to definition

**Comment by jrieken** [comment]
Yeah, that is a weird sample. TypeScript has the concept of defining a symbol in multiple places but this doesn't look like one...

**Comment by waynebloss** [comment]
There is no need to show a UI when there are multiple definitions. See #53164
