### ISSUE TITLE
Broken syntax highlighting with arrow function expression with parentheses

### ISSUE THREAD

**Issue by Silverwolf90** [Microsoft/vscode#51443]
Issue Type: <b>Bug</b>

JavaScript syntax highlighting is incorrect when an arrow function's body is wrapped in parentheses:

![image](https://user-images.githubusercontent.com/1631625/41151760-9c093c06-6b09-11e8-998a-affef548da89.png)

Without the parentheses the syntax highlighting works as expected:

![image](https://user-images.githubusercontent.com/1631625/41151822-ccce2c20-6b09-11e8-8c5f-f7df6032d1b0.png)

```javascript
const test = () => (
  true || false ||
  asdf ||
  0 ||
  "string"
);
```

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.87GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_5731703|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.9
column-jump|Coe|0.0.4
vscode-markdownlint|Dav|0.18.0
gc-excelviewer|Gra|2.0.21
beautify|Hoo|1.3.0
latex-workshop|Jam|5.5.1
vscode-docker|Pet|0.0.27
terminal-tabs|Tyr|0.2.0
html-css-class-completion|Zig|1.17.1
vscode-color|ans|0.4.5
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.4
vscode-eslint|dba|1.4.12
gitlens|eam|8.3.4
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
flow-for-vscode|flo|0.8.1
auto-rename-tag|for|0.0.15
rest-client|hum|0.18.4
angular2-switcher|inf|0.1.7
Angular2|joh|6.1.1
auto-comment-blocks|kev|1.0.1
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
vscode-cosmosdb|ms-|0.7.1
mssql|ms-|1.3.1
azure-account|ms-|0.4.0
Go|ms-|0.6.82
debugger-for-chrome|msj|4.5.0
angular2-inline|nat|0.0.17
vscode-icons|rob|7.23.0
json-to-js-object|sal|0.0.4
guides|spy|0.9.1
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
es-quotes|vil|0.2.6
highlight-matching-tag|vin|0.4.4
vscode-todo-highlight|way|0.5.12
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
markdown-all-in-one|yzh|1.4.0
vscode-open-in-github|ziy|1.3.1

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Fixed in vs code insiders:

<img width="342" alt="screen shot 2018-06-08 at 1 19 00 pm" src="https://user-images.githubusercontent.com/12821956/41179148-85efe6a8-6b1e-11e8-926a-322a57ff7c9c.png">
