### ISSUE TITLE
Escape stops working

### ISSUE THREAD

**Issue by rafacesar** [Microsoft/vscode#51441]
- VSCode Version: 1.24.0
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Open some file
2. Open the terminal
3. Run some command (e.g. `ls`)
4. Copy the result
5. Paste the result on the opened file (after this the `esc` key stops)
6. Try using the search field or use multi-cursor option and then try exiting from then using the `escape` key

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
This happens because Terminal tries to run Terminal Selection Clear command when there is selection in the terminal. I added a `terminalFocus` check for this command, @Tyriar decides if this should go to Recovery.

**Comment by Tyriar** [comment]
@rebornix I cherry picked it over to `release/1.24`
