### ISSUE TITLE
Search function is blank

### ISSUE THREAD

**Issue by Virunee** [Microsoft/vscode#51448]
Issue Type: <b>Bug</b>

When I open up VSC and click on the Search button on the left hand side navigation panel. The Search panel is blank and I cannot use the global search function.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 903)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 3|
|Memory (System)|7.69GB (0.24GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-docker|Pet|0.0.27
tslint|eg2|1.0.30
vscode-cosmosdb|ms-|0.7.1
python|ms-|2018.5.0
azure-account|ms-|0.4.0
code-spell-checker|str|1.6.10

</details>

![image](https://user-images.githubusercontent.com/16624508/41155593-93c63474-6b16-11e8-9a12-864af34cc2c8.png)

**Comment by roblourens** [comment]
Do any errors pop up? Can you check for errors in the dev tools (Help > Toggle developer tools)

**Comment by roblourens** [comment]
Also,

- Does this happen every time? Did it work fine in 1.23?
- If there are no errors, can you try launching code with a new user-data-dir? Like `code --user-data-dir=/tmp/codedata1
