### ISSUE TITLE
 Cannot read property 'getValueInRange' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5144]
Issue Id: <b>dff8e2a5-a437-69be-9f2d-2f90bc8fc188</b><br /><br />*Versions* <br />- 0.10.14-insider<br />-  43ff6af3d4564f59196caa9be4897fc33c15f24c<br />*Stack* <br />TypeError: Cannot read property 'getValueInRange' of null<br />[/vs/editor/contrib/find/common/findController.ts#L569:32 (getValueInRange)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/editor/contrib/find/common/findController.ts#L569:32 (getValueInRange))<br />[/vs/editor/contrib/find/common/findController.ts#L523:8 (_update)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/editor/contrib/find/common/findController.ts#L523:8 (_update))<br />[/vs/base/common/eventEmitter.ts#L241:18 (data)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/eventEmitter.ts#L241:18 (data))<br />[/vs/base/common/eventEmitter.ts#L267:8 (_emitToSpecificTypeListeners)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/eventEmitter.ts#L267:8 (_emitToSpecificTypeListeners))<br />[/vs/base/common/eventEmitter.ts#L285:8 (_emitEvents)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/eventEmitter.ts#L285:8 (_emitEvents))<br />[/vs/editor/contrib/find/common/findState.ts#L202:22 (emit)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/editor/contrib/find/common/findState.ts#L202:22 (emit))<br />[/vs/editor/contrib/find/browser/findWidget.ts#L105:17 (change)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/editor/contrib/find/browser/findWidget.ts#L105:17 (change))<br />[/vs/base/common/eventEmitter.ts#L241:18 (data)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/eventEmitter.ts#L241:18 (data))<br />[/vs/base/common/eventEmitter.ts#L267:8 (_emitToSpecificTypeListeners)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/eventEmitter.ts#L267:8 (_emitToSpecificTypeListeners))<br />[/vs/base/common/eventEmitter.ts#L285:8 (_emitEvents)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/eventEmitter.ts#L285:8 (_emitEvents))<br />

**Comment by alexandrudima** [comment]
Same root cause as #5457
