### ISSUE TITLE
Outline: Syncing the current symbol name

### ISSUE THREAD

**Issue by linuxjh** [Microsoft/vscode#51442]
So, I tried the new v1.24 with C, C++ extension from Microsoft.

1. Syncing the current symbol name in C, C++.
Clicking in a symbol, a function, a type, a variable in editor area should highlight the current symbol name in outline. This should be two-way: 
outline -> code, 
code -> outline

2. Symbols order should be the order of the code.

3. Add a new project-wide outline. Symbols could be ordered by name. 

Make it as good as it is in Source Insight.

**Comment by jrieken** [comment]
Did you discover any of those settings/toggles?

<img width="399" alt="screen shot 2018-06-08 at 12 20 53" src="https://user-images.githubusercontent.com/1794099/41153226-6b400ec6-6b16-11e8-8dfe-65c8b70a288d.png">

**Comment by linuxjh** [comment]
1. Clicking a function not highlight the function name in outline.

2. Yes, the Sort by Position works. No problem!

Thanks

**Comment by jrieken** [comment]
> Clicking a function not highlight the function name in outline.

In what language does that happen? Note that we don't have reliable data yet and that we synthesise some trees. Likely at the cost of us not knowing what ranges to use.

**Comment by linuxjh** [comment]
I tried C, C++ source files

**Comment by jrieken** [comment]
With which extension?

**Comment by linuxjh** [comment]
The C,C++ extension from Microsoft.

**Comment by jrieken** [comment]
closing as dupe of #34968. without more support from extensions these feature are prone to fail
