### ISSUE TITLE
Reindent Selected Lines command bug?

### ISSUE THREAD

**Issue by hackhowtofaq** [microsoft/vscode#51458]
- VSCode Version: 1.24.0
- OS Version: Mint 18.3

Steps to Reproduce:

1. Select below an indented line. Reindent is working as expected
2. Select below an empty line. Reindent is not respecting the indent above the empty line

![vscode_bug](https://user-images.githubusercontent.com/1138336/41163518-8a64f4c6-6b41-11e8-80e1-35b653215bd8.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by zhangkaiyulw** [comment]
Hi @rebornix, when doing reindentation, I've got some idea and what's your opinion on that, does it make sense? It's all about ignoring empty lines.
1. do not indent empty lines.
2. do not use the first previous empty line as indentation reference.

**Comment by zhangkaiyulw** [comment]
Hi @rebornix, this commit may fix this bug. If it's fixed, do I need to move `indentConverter` to another place?

**Comment by rebornix** [comment]
This issue is no longer reproducible.
