### ISSUE TITLE
Lag scroll and high window CPU usage

### ISSUE THREAD

**Issue by vedmant** [Microsoft/vscode#51451]
I'm experiencing laggy scrolling, for any file even if I run vs code with disabled extensions (code --disable-extensions);
Process Explorer shows windows process takes a lot cpu while I'm scrolling, up to 120% sometimes, usually about 60-80% https://screencast.com/t/SmUJtQBvQa

- VSCode Version: Version 1.24.0 (1.24.0)
- OS Version: Mac OS 10.13.4 (17E202) 
- MacBook Air Early 2014 i7 cpu 8g ram

Steps to Reproduce:

1. Open vs code
2. Scroll file fast up and down
3. See lags and high window process usage in the Process Explorer

Does this issue occur when all extensions are disabled?: Yes/No

Yes, extensions are disabled.

**Comment by vedmant** [comment]
Here I attached performance profile, you can see sometimes it has some frames > 100ms [Profile-20180610T124305.json.zip](https://github.com/Microsoft/vscode/files/2087703/Profile-20180610T124305.json.zip)

**Comment by alexandrudima** [comment]
@vedmant Sorry for taking such a long time to dive deep into this. Indeed, some frames take an unusual long time. I think that the view fails to use the monospace optimizations that are built in. This frame is indicative of that:

<img src="https://user-images.githubusercontent.com/5047891/45353128-59352600-b5ba-11e8-94a2-bc6827bcdaec.png" width="150" />

Are you using a custom font family that is not monospace? Are you using ligatures? Are you using `window.zoomLevel`?  Are you using `editor.disableMonospaceOptimizations` ? Are you using ligatures? What are your settings? Can you attempt to reset them and try to reproduce ?

**Comment by vedmant** [comment]
Hi,

Are you using a custom font family that is not monospace? - I use  "editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace",

Are you using ligatures? - No

Are you using window.zoomLevel? - No

Are you using editor.disableMonospaceOptimizations ? - No, don't have that option at all

Are you using ligatures? - No

What are your settings? - I don't have much settings

```
{
  "editor.fontSize": 14.5,
  "editor.lineHeight": 19,
  "terminal.integrated.fontSize": 14,
  "window.zoomLevel": 0,
  "workbench.colorCustomizations": {
    "statusBar.background": "#303030",
    "statusBar.noFolderBackground": "#222225",
    "statusBar.debuggingBackground": "#511f1f"
  },
  "editor.detectIndentation": false,
  "editor.tabSize": 2,
  "workbench.colorTheme": "Sublime Monokai",
  "editor.minimap.enabled": false,
  "workbench.activityBar.visible": false,
  "extensions.ignoreRecommendations": false,
  "explorer.autoReveal": false,
  "workbench.editor.enablePreview": false,
  "editor.tabCompletion": true,
  "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },
  "[scss]": {
    "editor.insertSpaces": true,
    "editor.tabSize": 2
  },
  "[html]": {
    "editor.insertSpaces": true,
    "editor.tabSize": 2
  },
  "[javascript]": {
    "editor.formatOnSave": true
  },
  "[python]": {
    "editor.insertSpaces": true,
    "editor.tabSize": 2
  },
  "editor.formatOnPaste": true,
  "editor.renderWhitespace": "boundary",
  "python.formatting.provider": "autopep8",
  "python.formatting.autopep8Args": ["--indent-size=2", "--max-line-length=100"],
  "python.formatting.yapfArgs": ["--style", "{indent_width: 2, spaces_before_comment: 2}"],
  "emmet.includeLanguages": {"erb": "html"},
  "prettier.semi": false,
  "prettier.printWidth": 120,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
}
```

Can you attempt to reset them and try to reproduce ? - I'll try this a bit later

**Comment by alexandrudima** [comment]
Here is the subset of settings that might impact rendering from the above:

```
{
  "editor.fontSize": 14.5,
  "editor.lineHeight": 19,
  "window.zoomLevel": 0,
  "workbench.colorCustomizations": {
    "statusBar.background": "#303030",
    "statusBar.noFolderBackground": "#222225",
    "statusBar.debuggingBackground": "#511f1f"
  },
  "workbench.colorTheme": "Sublime Monokai",
  "editor.minimap.enabled": false,
  "workbench.activityBar.visible": false,
  "editor.renderWhitespace": "boundary",
}
```
