### ISSUE TITLE
Completing path doesn't work properly

### ISSUE THREAD

**Issue by Flynrod** [Microsoft/vscode#51453]
VSCode suggest an auto-completion of a rather strange path.

- VSCode Version: 1.24.0
- OS Version: 10.13.5 (17F77)

Steps to Reproduce:

1. Create an HTML element where a path can be specified
2. Complete the access path 'a bit'

Does this issue occur when all extensions are disabled?: Yes

Example :
![capture d ecran 2018-06-08 a 15 29 41](https://user-images.githubusercontent.com/29288223/41160980-9472b9ea-6b31-11e8-8c9e-2b502f716dcf.png)

**Comment by octref** [comment]
I have this following folder structure, and it's working fine for me:

![image](https://user-images.githubusercontent.com/4033249/41627690-2b8b4930-73d6-11e8-8837-a1a3da1a0585.png)

If `/assets` is a top-level folder in your project, you'll only get completion on `/assets` (notice the starting slash).

Can you let me know what's the structure of your project? And on which html file are you prompting path suggestion?
