### ISSUE TITLE
VSCode thinks there are 2 definitions of a React Component

### ISSUE THREAD

**Issue by mdo5004** [Microsoft/vscode#51459]
VSCode thinks there are 2 definitions of a React Component

This issue was brought up recently but without sufficient info. Here is a minimal reproduction example:

- VSCode Version: 1.24.0
- OS Version: MacOS High Sierra 10.13.4 (17E202)

Steps to Reproduce:

1. Create a React app
```bash
$ create-react-app my-bug-example
$ code my-bug-example
```
2. Change src/App.js to 

```
import React, { Component } from 'react';

class App extends Component {
  render() {
    return (
      <div className="App">
      <MyComponent />
      </div>
    );
  }
}

export default App;

class MyComponent extends Component {
  render(){
    return <MySingleComponent text="Instance 1" />
  }
}

class MySingleComponent extends Component {
  render(){
    return <p>{text}</p>
  }
}

```
3. CMD + hover on `<MySingleComponent text="Instance 1" />`

<img width="518" alt="screen shot 2018-06-08 at 10 33 09 am" src="https://user-images.githubusercontent.com/12416969/41164179-88c8ed18-6b08-11e8-9619-8e1f5d093f59.png">

4. CMD + click on `<MySingleComponent text="Instance 1" />`

<img width="471" alt="screen shot 2018-06-08 at 10 33 26 am" src="https://user-images.githubusercontent.com/12416969/41164182-8b65331a-6b08-11e8-98ab-975f5e18e2ff.png">

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24809
