### ISSUE TITLE
Indentation for closing parentheses of method calls is wrong [TS, JS]

### ISSUE THREAD

**Issue by Oikio** [Microsoft/vscode#51457]
Indentation for closing parentheses of method calls is wrong if last argument ends with comma.

- VSCode Version: 1.24.0
- OS Version: MacOS High Sierra 10.13.4 (17E199)

Steps to Reproduce:

Use 'Format Document' feature for this code:
```ts
foo
  .bar(
    x,
    y
  ) // <----- right

foo
  .bar(
    x,
    y,
) // <----- wrong, always on the same column as object
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Xunnamius** [comment]
I'm experiencing something similar, and I've got to say it's pretty annoying. It occurs when all extensions are disabled, but it's automatic formatting (I'm not using "format document" explicitly).

![behavior](https://user-images.githubusercontent.com/656017/41247927-1604b216-6d75-11e8-91d4-91c342c0d000.gif)

I'm loving VS Code; thanks for the great software!

**Comment by mjbvz** [comment]
I can't repo this. Do you have any extensions installed that are providing formatting for js?

**Comment by Oikio** [comment]
I have bunch of extensions installed and I wonder which of them provide formatting, but it looks like none of them is related to 'format document' or 'formatOnSave', and the issue is reproducible with all extensions being disabled. 
Also I tried to delete all setting I have - same behavior. 
If you think it might be related to extensions, here is the [list of extensions I have](https://pastebin.com/xRW8vCkG) just in case.

**Comment by mjbvz** [comment]
Ok, sorry I thought your example was explaining the expected vs actual behavior. I see that having a trailing comma as in the second case does cause the incorrect formatting

I've opened https://github.com/Microsoft/TypeScript/issues/25056 to track this
