### ISSUE TITLE
Parameters passed to super calls are marked unreferenced

### ISSUE THREAD

**Issue by AshleyScirra** [Microsoft/vscode#51456]
Issue Type: <b>Bug</b>

In JavaScript, use the following code snippet:

```js
class C extends B {
	constructor(param)
	{
		super(param);
	}
}
```

The `param` in `constructor(param)` is highlighted grey, to indicate it is an unreferenced parameter. This is incorrect - it is referenced in the super call.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (9.66GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.33

</details>

**Comment by AshleyScirra** [comment]
Another case - the `const foo` is marked unreferenced despite being referenced in the super call:

```js
{
	const foo = "bar";

	class C {
		constructor()
		{
			super(foo);
		}
	}
}
```

**Comment by mjbvz** [comment]
In the second example, there's no base class. This missing base class gets flagged as an error in ts and with js-check enabled javascript. Adding a base class with a constructor seems to fix the problem:

<img width="432" alt="screen shot 2018-06-08 at 1 20 44 pm" src="https://user-images.githubusercontent.com/12821956/41179225-cdba3268-6b1e-11e8-8a6a-652412f76fc3.png">

In the first example, does base class `B` has a constructor?

**Comment by AshleyScirra** [comment]
Oops, you're right, I forgot the base class so the super is not valid. However it still reproduces if you add back in a base class:

```js
{
	const foo = "bar";

	class C extends B {
		constructor()
		{
			super(foo);
		}
	}
}
```

In this case `const foo` is still marked unreferenced.

**Comment by AshleyScirra** [comment]
You're right that it goes away if you declare the base class, e.g.:

```js
{
	const foo = "bar";
	
	class B {} // now 'foo' marked referenced

	class C extends B {
		constructor()
		{
			super(foo);
		}
	}
}
```

However in real-world projects the base class isn't always visible. If it depends on a dynamically loaded script, dynamic import, external library, etc. then it's not statically analysable and so VS Code won't know about it. This shouldn't matter though: even if it's not known what the base class is, there is still obviously a reference to `foo`, so it shouldn't be marked unreferenced.

**Comment by mjbvz** [comment]
Thanks. See fixed in vs code insiders:

![screen shot 2018-06-18 at 3 04 42 pm](https://user-images.githubusercontent.com/12821956/41564797-f199429a-7308-11e8-8e5f-0da80744a2ec.png)
