### ISSUE TITLE
Unused variable detection: unreachable nested functions not greyed out

### ISSUE THREAD

**Issue by jdfarber** [Microsoft/vscode#51460]
- VSCode Version: 1.24.0
- OS Version: macOS Sierra

Steps to Reproduce:

1. Write some nested functions
2. Comment out some of those nested function in the root function
3. Only functions 1 level deep are greyed out 

<img width="221" alt="screen shot 2018-06-08 at 10 36 49 am" src="https://user-images.githubusercontent.com/177753/41164580-83361bfe-6b09-11e8-831f-a8dd117375be.png">

Does this issue occur when all extensions are disabled?: Yes

I would imagine all unreachable code would be greyed out.

**Comment by jdfarber** [comment]
@mjbvz Thanks for assigning this. This feature is incredibly helpful for at-a-glance code cleanup!

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/24894 to discuss this upstream
