### ISSUE TITLE
(Mac) Cmd + K does not seem to clear the terminal in VS Code

### ISSUE THREAD

**Issue by abain-io** [Microsoft/vscode#51463]
...Any ideas? Thanks. It works on my Mac terminal program, but not in VS Code anymore. It used to work. Not sure what I did. Thank you.

**Comment by Tyriar** [comment]
There's a answer in the FAQ on this https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions

**Comment by abain-io** [comment]
Thanks!
