### ISSUE TITLE
Memory use too high in windows powershell terminal

### ISSUE THREAD

**Issue by gengjiawen** [Microsoft/vscode#51465]
Issue Type: <b>Bug</b>

This only occures on windows, not on macOS and ubuntu. Also works fine on webstorm.
The problem still occur if I disable all my extensions.
```
git clone https://github.com/gengjiawen/electron-devdocs
npm i -g cnpm
cnpm i --by=yarn
```
![fe27e14800b6704349698defdc37e52](https://user-images.githubusercontent.com/3759816/41169070-5bd5a3ce-6b7a-11e8-8f11-0ffb4a764ab9.png)

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (11.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by gengjiawen** [comment]
@bpasero My problem is the memory, not cpu, and it still occur when I disable all extensions, which part do you need me to do ?

**Comment by bpasero** [comment]
@gengjiawen find out which process exactly has the high memory consumption, e.g. from our built in process explorer.

**Comment by gengjiawen** [comment]
I can not reproduce this problem now, sorry for the inconvenience, I will reopen if it occur again.

**Comment by gengjiawen** [comment]
When I enable process explorer, the memory doesn't take up too high, but I still get this
![image](https://user-images.githubusercontent.com/3759816/41726374-91e720a8-75a4-11e8-83cf-e7054b43c51c.png)

**Comment by gengjiawen** [comment]
![image](https://user-images.githubusercontent.com/3759816/42447611-156a0006-83ad-11e8-86f7-e781fbe8ee7c.png)

Problem still exists, and `process explorer` not helping, since the process different from after opening it.

**Comment by bpasero** [comment]
@gengjiawen do you see this right when opening the folder or only when working a bit? In your screenshot the GPU process seems to be having a lot of memory consumption. Does this still happen?

**Comment by gengjiawen** [comment]
It happens when I execute some terminal commandwith long output. recently not happened.

**Comment by gengjiawen** [comment]
It happens when I execute some terminal commandwith long output. recently not happened.

**Comment by bpasero** [comment]
> recently not happened

Ok closing then.

**Comment by gengjiawen** [comment]
Happened again in last hour, actually this maybe the driver issue.Anyway I can use webstorm as an alternative.
