### ISSUE TITLE
Outline view does not work/support Java and Scala

### ISSUE THREAD

**Issue by fmerici** [Microsoft/vscode#51462]
Issue: Outline feature added in #49917 does not show a tree view for Java or Scala scripts
- The OUTLINE view displays this message `There are no editors open that can provide outline information.`

- VSCode Version: `Version 1.24.0 (1.24.0)`
- OS Version: `macOS 10.13.5`

Steps to Reproduce:

1. Open a Java and/or Scala file
2. Right click on OPEN EDITORS in the explorer view and check 'Outline

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
You need to install a Java extension for that: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack

**Comment by fmerici** [comment]
Interesting, I already had the Java extension install - I re-installed it and now it works, for Java

However, Scale still does not work..., let me know. Thanks for the help
