### ISSUE TITLE
Copy from SCM diff

### ISSUE THREAD

**Issue by gregcoombe** [Microsoft/vscode#51469]
I'm a fairly heavy user of the inline SCM diffing view ('viewlet'?).

A tiny frustration is that I can't copy deleted lines from this viewlet back into my code. This comes up when I remove some code, then decide that I actually want one or two of the lines back. 

The workaround is not terrible: just revert the entire chunk, then remove the rest of the lines. But it'd be a little easier if I could just copy directly.

Version 1.24.0
Platform: OSX 10.13.4

**Comment by bpasero** [comment]
@gregcoombe isn't this https://github.com/Microsoft/vscode/issues/8226

**Comment by alexandrudima** [comment]
Can only be #8226.
