### ISSUE TITLE
Update installer failed.

### ISSUE THREAD

**Issue by zeelux** [Microsoft/vscode#51477]
Contents of upgrade log file:

Jun 08 13:40:23.865 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
Jun 08 13:40:23.873 INFO Checking for running Code.exe processes... (attempt 1)
Jun 08 13:40:23.888 INFO Code.exe is not running
Jun 08 13:40:23.889 INFO Checking for possible conflicting running processes... (attempt 1)
Jun 08 13:40:23.902 INFO Inno Updater v0.4.3
Jun 08 13:40:23.904 INFO Starting update, silent = false
Jun 08 13:40:24.002 INFO do_update: "C:\\Program Files\\Microsoft VS Code\\Code.exe", _
Jun 08 13:40:24.005 INFO move_update: "C:\\Program Files\\Microsoft VS Code\\unins000.dat", _
Jun 08 13:40:24.011 INFO Delete: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.011 INFO Delete: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.011 INFO Delete: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.012 INFO Delete: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.013 INFO Delete: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.013 INFO Delete: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
Jun 08 13:40:24.015 INFO Delete: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
Jun 08 13:40:24.017 INFO Delete: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.018 INFO Delete: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.020 INFO Delete: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.022 INFO Delete: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.024 INFO Delete: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
Jun 08 13:40:24.026 INFO Delete: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.029 INFO Delete: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.030 INFO Delete: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.031 INFO Delete: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.033 INFO Delete: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
Jun 08 13:40:24.035 INFO Delete: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.037 INFO Delete: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.039 INFO Delete: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.041 INFO Delete: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.042 INFO Delete: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
Jun 08 13:40:24.050 INFO Delete: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.050 INFO Delete: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.050 INFO Delete: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.050 INFO Delete: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.051 INFO Delete: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.053 INFO Delete: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.055 INFO Delete: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.057 INFO Delete: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.058 INFO Delete: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.059 INFO Delete: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.061 INFO Delete: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.063 INFO Delete: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.064 INFO Delete: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.066 INFO Delete: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.067 INFO Delete: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.069 INFO Delete: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.071 INFO Delete: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.073 INFO Delete: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
Jun 08 13:40:24.074 INFO Delete: "bin" (attempt 1)
Jun 08 13:40:24.081 INFO Delete: "blink_image_resources_200_percent.pak" (attempt 1)
Jun 08 13:40:24.082 INFO Delete: "Code.exe" (attempt 1)
Jun 08 13:40:24.134 INFO Delete: "Code.exe" (attempt 2)
Jun 08 13:40:24.336 INFO Delete: "Code.exe" (attempt 3)
Jun 08 13:40:24.788 INFO Delete: "Code.exe" (attempt 4)
Jun 08 13:40:25.590 INFO Delete: "Code.exe" (attempt 5)
Jun 08 13:40:26.842 INFO Delete: "Code.exe" (attempt 6)
Jun 08 13:40:28.644 INFO Delete: "Code.exe" (attempt 7)
Jun 08 13:40:31.096 INFO Delete: "Code.exe" (attempt 8)
Jun 08 13:40:34.297 INFO Delete: "Code.exe" (attempt 9)
Jun 08 13:40:38.349 INFO Delete: "Code.exe" (attempt 10)
Jun 08 13:40:43.351 INFO Delete: "Code.exe" (attempt 11)
Jun 08 13:40:43.353 ERRO Access is denied. (os error 5)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (2.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
csharp|ms-|1.15.2
vscode-docker|Pet|0.0.27
vscode-icons|rob|7.23.0
markdown-authoring|yan|0.1.5

</details>

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
