### ISSUE TITLE
Unable to save settings file because it's dirty

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#51474]
Reported by https://twitter.com/AE86HAN on twitter

![jmurtcys](https://user-images.githubusercontent.com/173559/41171709-5fce6228-6b06-11e8-92f1-068bf7326503.jpg)

**Comment by devamaz** [comment]
@auchenberg seems the path entered is wrong

**Comment by penghan0** [comment]
I already know what's wrong, I lose the .git document.
![3](https://user-images.githubusercontent.com/29083792/41178082-89bf4ac2-6ba9-11e8-8dd2-7dfe7a75b02e.JPG) Here is a another question, why the source control git have 5000+? How to solve it?

**Comment by sandy081** [comment]
@penghan0 Please file a separate issue

**Comment by sandy081** [comment]
@auchenberg Can you please ask the user if there are any steps to reproduce?

**Comment by penghan0** [comment]
I fixed, so can close. Thanks so much
