### ISSUE TITLE
Text overflows split terminal when using dom renderer

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#51479]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Set `terminal.intergrated.rendererType` to `dom`
2. Split the terminal
3. Run a command that will generate long lines that need to be wrapped, ex. `./scripts/code.sh` in the vscode repo

The text runs over the edge into the next terminal:
![screen shot 2018-06-08 at 11 02 56 am](https://user-images.githubusercontent.com/3672607/41174081-eb5f72f8-6b0d-11e8-9e25-8817ec2eb658.png)

VS Code version: Code - Insiders 1.25.0-insider (8f8ed32e737a7a906fac654fb0bd61b257b449b1, 2018-06-08T05:10:42.592Z)
OS version: Darwin x64 17.4.0

**Comment by Tyriar** [comment]
Another case: https://github.com/Microsoft/vscode/issues/51552

**Comment by Tyriar** [comment]
Resizing down doesn't trim the line ends:

<img width="394" alt="screen shot 2018-06-20 at 7 44 23 pm" src="https://user-images.githubusercontent.com/2193314/41650866-6398c7ca-74c2-11e8-8504-ca3c95d087ef.png">

**Comment by mjbvz** [comment]
I still see a slight visual overlap

![screen shot 2018-06-27 at 2 14 51 pm](https://user-images.githubusercontent.com/12821956/42000107-8200fcee-7a14-11e8-99a9-4736654fc842.png)

**Comment by DuncanFaulkner** [comment]
Seeing a similar issue in code-insiders (27" monitor not 4k), same version works fine on 22"
both on ubuntu 18.04 and 16.04 respectively.
Also only seems to affect terminal window all other command windows are fine.
![vs screen shot](https://user-images.githubusercontent.com/1952116/42400389-448447d4-8169-11e8-9eb7-3c9866883868.png)

**Comment by DuncanFaulkner** [comment]
Have just updated to version code-insiders_1.26.0-1530854541_amd64.deb and it's still doing it, will check tomorrow evening to see if that version has fixed the issue

**Comment by DuncanFaulkner** [comment]
@Tyriar yes that has appeared to fix the issue, thanks

**Comment by Tyriar** [comment]
Awesome, thanks for verifying 😃
