### ISSUE TITLE
Searching the project only finds matches in files that have been opened.

### ISSUE THREAD

**Issue by alastairjwright** [Microsoft/vscode#51476]
I found similar bugs reported but were closed because of not enough info.
https://github.com/Microsoft/vscode/issues/41336

So here's my attempt at helping.
- VSCode Version: 1.23.1
- OS Version: macOS Sierra 10.12.6

So this applies to searching the project with Cmd + Shift + F.
It also applies to finding files in the project with Cmd + P.

Steps for recreating. 
1. When I search for a string in my project there are 0 matches. 
![image](https://user-images.githubusercontent.com/3685705/41172168-f90554e6-6b20-11e8-8f32-9ba4961d3aed.png)

2. I then open a file where I know the match exists.

3. Search again and it finds a match.
![image](https://user-images.githubusercontent.com/3685705/41172205-1ab6dede-6b21-11e8-8c2c-89dcb4310c3d.png)

**Comment by roblourens** [comment]
Please see this wiki section for troubleshooting tips: https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results
