### ISSUE TITLE
Visual Flickering Bug When Maximized on High Res Monitor

### ISSUE THREAD

**Issue by CodeProjects** [Microsoft/vscode#51481]
- VSCode Version: 1.24.0
- OS Version: macOS HIghSierra

After updating to 1.24.0, when the window is either maximized or expanded past a certain size the text and other parts of the layout start flashing in a strobe light sort of style. This issue does not occur in 1.23.1.

Steps to Reproduce:
1. Open VS Code.
2. Maximize or enlarge to fill screen.
Result: Parts of VS Code window flickers

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Disabled Extensions: 
-Debugger For Chrome
-VS Live Share

**Comment by bpasero** [comment]
@CodeProjects does this happen when you run "`code --disable-gpu`"?

**Comment by CodeProjects** [comment]
I restarted my computer over the weekend and the issue seems to have disappeared. The problem may have been on my end.
