### ISSUE TITLE
Feature Request: Add a command to sort config JSON

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#51480]
It gets untidy very quickly.

**Comment by ivanvoznyakovsky** [comment]
You can use https://marketplace.visualstudio.com/items?itemName=richie5um2.vscode-sort-json for now

**Comment by octref** [comment]
I'm aware of it. Think it should be built-in.

**Comment by roblourens** [comment]
Got #43670 for sorting settings

**Comment by octref** [comment]
@roblourens Feel free to close as dup. Just saying having "Organize" for both keybinding / config would be great.

**Comment by roblourens** [comment]
Oops, meant to. I'd like to have it too.
