### ISSUE TITLE
Having Problem with JS.Node

### ISSUE THREAD

**Issue by gsyedullah** [Microsoft/vscode#51488]
Issue Type: <b>Bug</b>

I have been using VS Code and node js for javascript output in Visual studio Code and installed code runner as an extension... but whenever I make a mistake in the Coding or when the output is too long o.. The Node js consumes almost all of the ram and processor runs at its maximum speed.. and the Laptop wont shutdown after Shutting down(the power led button remains on and fan keeps spinning)... but it will shut down after killing the node.js process in the task manager.. plz give me a solution on this problem. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (5.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.3

</details>

**Comment by aeschli** [comment]
Please file this against the code-runner extension: https://github.com/formulahendry/vscode-code-runner
