### ISSUE TITLE
Indent guides are rendered for empty lines in gitlens's file blame panel

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [microsoft/vscode#51484]
- VSCode Version: 1.24.0
- OS Version: macOS 10.13.4

<img width="426" alt="screenshot 2018-06-08 14 31 31" src="https://user-images.githubusercontent.com/6418145/41156179-7706b2ce-6b29-11e8-9bf5-86a55f9e6c98.png">

**Comment by ivanvoznyakovsky** [comment]
just noticed that also cursor goes to blame panel when on an empty line
<img width="510" alt="screenshot 2018-06-14 21 35 51" src="https://user-images.githubusercontent.com/6418145/41431261-00f41f08-701b-11e8-86ee-64aeba45436a.png">
but stays in the editor when on non empty line
<img width="428" alt="screenshot 2018-06-14 21 37 04" src="https://user-images.githubusercontent.com/6418145/41431308-29bcbbb6-701b-11e8-844b-6bbaab752625.png">

**Comment by alexdima** [comment]
This is also fixed by the fix for #40127
