### ISSUE TITLE
Smooth navigation through menus

### ISSUE THREAD

**Issue by sathvikc** [Microsoft/vscode#51486]
Issue Type: <b>Bug</b>

I am not able to smooth navigate through all tabs because of `View` tab dropdown.

Please check it here: [GIF Image](https://imgur.com/a/lBDu3LE)

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.15.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 1957)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 1|
|Memory (System)|7.66GB (3.89GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/16826
