### ISSUE TITLE
Accessibility: Find All References is confusing to use when using a screenreader

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#51498]
_Learnings from NVAccess testing_

Focus moves into a list of references. Pressing enter on one of these references does move the caret to the correct line in the document, but focus itself stays in the references list. This is confusing. It should move to the document.

**Steps**

1. Open   Visual studio code editor.
2. Open any file and create code to target a module, method,  function, classes, variables or any of the   intellisense completions under:   https://code.visualstudio.com/docs/editor/intellisense
3.  Enable the   Intellisense by pressing "Ctrl+Spacebar" key.
4. Navigate through the different completions using keyboard and   observe behavior with assistive technologies.
5. With a file open, use F12 to activate "Go to   Definition" and observe behavior with    assistive technologies
6. With a file open, hit ALT + F12 to activate "Peek   Definition" and observe behavior with    assistive technologies
7. Hit "Options" key and select  "Find All References", observe   behavior with ATs and make changes to refrences on the RHS of the Peek window

**Comment by jrieken** [comment]
> but focus itself stays in the references list. This is confusing. It should move to the document.

Can you explain why that's confusing? Staying in the tree, not the editor, is the whole idea because that allows you to navigate references quickly and with ease.

**Comment by jrieken** [comment]
ping @auchenberg

**Comment by auchenberg** [comment]
I'm waiting for more info from NVAccess, who tested this.

**Comment by jrieken** [comment]
Please reopen with actionable information.
