### ISSUE TITLE
Accessibility: Not clear how to get to extension details when using a screenreader

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#51497]
**Learnings from NVAccess testing:**

I'm not sure how to get to the "details".

**Steps:**

1. Open   Visual studio code editor.
2. Using   "Ctrl+Shift+X" key navigate to the extension side view bar option.
3. Using Tab key navigate to the "More" option and   select different options( "Show installed Extension, Show outdated   extension, Show popular Extension,Etc")
4. Select an extension and using "Tab" and   "Arrow" keys navigate through the extension details window on the  RHS

**Comment by ramya-rao-a** [comment]
@misolori What do you think of a "Read more" button for each item? It will get a little noisy. Any other ideas?

**Comment by ramya-rao-a** [comment]
Or just update the aria label on the extension item with "Click to read more" ? Because hitting Enter when the list item has focus, does open the details

**Comment by misolori** [comment]
@ramya-rao-a definitely prefer making changes on the code side. The label should probably read like “View extension details” so it’s a little more explicit.

**Comment by ramya-rao-a** [comment]
And I am guessing the focus should then move to the editor after hitting the user hits Enter and start reading there...
