### ISSUE TITLE
Rename Symbol doesnt seem to work when using a screen reader

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#51499]
_Learnings from NVAccess testing:_

I typed in the new symbol name, but after pressing enter and reading the document again,  nothing changed.

**Steps:**
1. Open Visual studio code editor.
2. Open any file and create code to target a module, method,  function, classes, variables or any of the   intellisense completions under:   https://code.visualstudio.com/docs/editor/intellisense

3. Enable the   Intellisense by pressing "Ctrl+Spacebar" key.
4. Navigate through the different completions using keyboard and   observe behavior with assistive 
5. Use F2 to "Rename Symbol" in one editor and observe   behavior in multiple editiors

**Comment by jrieken** [comment]
> Use F2 to "Rename Symbol" in one editor and observe behavior in multiple editiors

@auchenberg Can you be more concrete? What is your expected behaviour? I get this when renaming a symbol 

<img width="766" alt="screen shot 2018-06-11 at 11 28 14" src="https://user-images.githubusercontent.com/1794099/41223650-b0187776-6d6a-11e8-91b5-640a9e54bf6d.png">

**Comment by jrieken** [comment]
ping @auchenberg

**Comment by auchenberg** [comment]
I'm waiting for more info from NVAccess, who tested this.

**Comment by jrieken** [comment]
Please reopen with actionable information
