### ISSUE TITLE
The last VS Code update failed.

### ISSUE THREAD

**Issue by danielcasler** [Microsoft/vscode#51491]
The last VS Code update failed and VS Code was stuck at the small installing update dialogue. I had to close it manually. When I tried to restart VS Code it couldn't find the .exe file and my shortcuts were removed.

I cant reinstall VS Code as its telling me I have to remove the 32 bit version first, which I can't do as there is no VS Code in program files.

I tried to remove VS Code manually from the program files to no avail!

How do I remove VS Code so I can reinstall it? I'm completely blocked right now and cannot work as my editor is offline and using another editor is very traumatic.

Thanks!

**Comment by joaomoreno** [comment]
@danielcasler That's interesting. Can you install the 32-bit version, then uninstall it? Afterwards, you should be able to install the 64-bit version.
