### ISSUE TITLE
Frequent lockups with VS Code 1.24.0

### ISSUE THREAD

**Issue by pixe1master** [Microsoft/vscode#51490]
Issue Type: <b>Bug</b>

I'm not sure what is causing it but soon after I updated from 1.23.x to 1.24.0 VS Code started locking up (not responding to user inputs - mouse clicks or typing and mouse cursor wasn't changing as I hovered over different UI elements).  If I wait 30 seconds or longer then it becomes responsive again but then a little later it locks up again and I have to wait.  This isn't productive so I've reverted to 1.23.1.

I didn't try disabling extensions to see if an extension is causing the problem.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (19.57GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
numbered-bookmarks|ale|0.11.1
ts-loader-problem-matcher|alq|0.3.0
vscode-svgviewer|css|1.4.4
toggle-excluded-files|eam|1.6.0
graphviz-preview|EFa|1.1.0
tslint|eg2|1.0.30
beautify|Hoo|1.3.0
plantuml|jeb|2.7.6
docthis|joe|0.7.1
codeshell|Kip|0.2.2
vscode-mocha-sidebar|mat|0.19.1
vsliveshare|ms-|0.3.264
debugger-for-chrome|msj|4.6.0
okazukiplantuml|oka|0.2.2
vscode-code-outline|pat|0.2.1
vscode-versionlens|pfl|0.21.1
node-tdd|pra|0.2.4
vscode-icons|rob|7.23.0
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.4.0

</details>

**Comment by aeschli** [comment]
@pixe1master Can you use the Process Explorer (Help > Process Explorer)? Can you see a load when the locking happens?

**Comment by pixe1master** [comment]
I'm currently staying on VS 1.23.1 on my laptop but I have VS 1.24.0 on a desktop system... I'll check later on that system to see if I'm seeing the same behavior.  If I see it I'll try Process Explorer.

**Comment by phawxby** [comment]
Exact same problem.

![image](https://user-images.githubusercontent.com/1090602/41413351-bbc35448-6fda-11e8-812f-a28976273189.png)

Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by bpasero** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by phawxby** [comment]
I will begin to work through the verification checklist and get back to you. 

I performed a full Windows 10 reinstall last night as I was experiencing full system freezing and crashing, I believed it to be a system issue so went for the full wipe. System back online I did a burn-in with prime 95 and a few games, no crashing and stable high 50's centigrade system temperatures. 

Back to work this morning and the crashes started again. Just anecdotal at the moment but it seems like it most frequently happens when using the integrated terminal. I have being using windows command prompt rather than the integrated terminal and so far, no crashes. 

But what I can say is:
- I have no extensions installed, this is a totally fresh build so haven't even installed my VS Code extensions yet
- It did not occur until I updated a few days ago. 

Weirdly I've also have a few GPU crashes which have coincided with the app hang.
![image](https://user-images.githubusercontent.com/1090602/41413979-b11bf322-6fdc-11e8-8284-dab2e4e999e6.png)

**Comment by phawxby** [comment]
3 hours in and I've not had a single crash, freeze or stutter by avoiding the integrated terminal. I've forcibly set `"terminal.integrated.rendererType": "dom"` to try and determine if it's a canvas problem. 

@pixe1master I don't suppose you were using the integrated terminal were you?

**Comment by phawxby** [comment]
3 hours on the Dom renderer, it's a bit slow but no crashes. I'll switch back to the canvas renderer tomorrow and see if the crashes start again.

**Comment by phawxby** [comment]
Aaaand we're back to crashing. The electron wrapper remains responsive but the contents are totally frozen. 

Canvas rendering. That's rather a lot of GPU usage to render a terminal. 
![image](https://user-images.githubusercontent.com/1090602/41469415-f57b8ad2-70a4-11e8-91cd-cf1f925ad466.png)

Dom rendering.
![image](https://user-images.githubusercontent.com/1090602/41469463-38d72732-70a5-11e8-983c-109cf10c67ca.png)

**Comment by bpasero** [comment]
@Tyriar you might want to engage

**Comment by Tyriar** [comment]
If the canvas renderer is causing a crash this couldn't be anything other than a Chromium issue imo. @phawxby can you try download the [insiders build](https://code.visualstudio.com/insiders/) which is on a later version of Electron/Chromium and see if it repros?

**Comment by phawxby** [comment]
@Tyriar ahead of you. I've been running insider the last 2 hours without a single crash. Whatever went wrong in the latest release appears fixed in the latest insider build. 

![image](https://user-images.githubusercontent.com/1090602/41476281-fb7fd47e-70b8-11e8-8a40-d3eddbf0accb.png)

**Comment by Tyriar** [comment]
@phawxby good to hear!

@pixe1master could you also try the insiders build to see if it fixes the problem?
