### ISSUE TITLE
Git problem in vscode

### ISSUE THREAD

**Issue by sharif210** [Microsoft/vscode#51507]
Git repository has too many active changes only a subset of features will be executed i am getting this while running vs code how i solve this problem i am using windows os

**Comment by sharif210** [comment]
Say step by step how to get out of this issue

**Comment by sharif210** [comment]
On windows os how do i get rud of my problem

**Comment by joaomoreno** [comment]
Run `git rev-parse --show-toplevel` to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.

**Comment by sharif210** [comment]
All are saying .git folder it is not working even if i delete that can u please give me a permanent solution regarding my issue
