### ISSUE TITLE
Limit snippet typing bounds

### ISSUE THREAD

**Issue by kobi2187** [Microsoft/vscode#5150]
- VSCode Version: Version 0.10.11
  Commit f291f4ad600767626b24a4b15816b04bee9a3049
  Date 2016-03-11T16:19:03.130Z
  Shell 0.35.6
  Renderer 45.0.2454.85
  Node 4.1.1
- OS Version: Linux Mint 17.3 Cinnamon 64 bit.

Steps to Reproduce:
1. create a snippet that has (same) ids
2. use that snippet.
3. go to one of them, type something then delete. continue deleting beyond the starting position.
   OR
4. go to one of them, type something then enter, it will continue to the next line, in all of the location markers.

result: it deletes text in all the locations, since it uses multi cursors but has no bounds. it also goes to next lines if pressing enter.

expected behaviour: limit the bounds. from starting position until end of the line.

**Comment by alexandrudima** [comment]
fyi @jrieken

**Comment by kobi2187** [comment]
if you need more information, contact me here.

**Comment by jrieken** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
