### ISSUE TITLE
Semicolon automatically added at the end of import statement

### ISSUE THREAD

**Issue by bojand** [Microsoft/vscode#51506]
- VSCode Version: 1.24.0
- OS Version: MacOS High Sierra 10.13.4

Steps to Reproduce:

Not sure if this is a bug or some setting, or something changed in the settings with the latest release 1.24.0, but it seems semicolons are automatically inserted at the end of `import` statements and I can't seem to figure out what does it and how to turn it off.

I normally use standardjs, which enforces no semicolons.

I have `chenxsan.vscode-standardjs` extension.

Steps to reproduce:

do `npm init` and `npm i --save lodash` and `npm i --save-dev standard`.

add a new `.js` file and add a line 
```
import _ from 'lodash'
```
click save

vscode automatically seems to insert `;` semicolon at the end of import lines.
this does not happen for `require()` lines.

I have tried changing and turning off bunch of settings with no success.
Tried turning on trace logging and extension inspection.

One log that _seems_ peculiar that gets logged when I click save and the code is formatted as described is:

```
[exthost1] [trace] ExtHostCommands#executeCommand _typescript.organizeImports
```

Yes

If there is some setting to turn this off i coulnd't find it, sorry.

**Comment by bojand** [comment]
Seems this is due to my custom settings:
```
"[javascript]": {
      "editor.codeActionsOnSave": {
        "source.organizeImports": true
      }
    },
```
Setting. It adds a `;` at the end. Turning it off resolved the issue.

**Comment by vith** [comment]
I don't think turning off these features is really solving the problem ;)

But it sounds like this is another manifestation of the same core issue as https://github.com/Microsoft/TypeScript/issues/19882

**Comment by vith** [comment]
In the meantime, this extension doesn't have the semicolon problem: https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports

**Comment by robert-zaremba** [comment]
@vith  - I installed `amatiasq.sort-imports` and still have the semicolon problem.
