### ISSUE TITLE
I can't use "Go To Definition" function

### ISSUE THREAD

**Issue by 68593018** [Microsoft/vscode#51505]
- VSCode Version: 1.24.0
- OS Version: Win7

Steps to Reproduce:

1. I downloaded the VSCode from https://code.visualstudio.com/ yesterday and open a jetty.project-jetty-9.4.9.v20180320 folder, but I can't use the "Go To Definition", it doesn't work.
2. But when I unziped the src.zip of JDK8, and then open the src folder, it works fine

I have searched so many information in google, but I can't find any solution to fix the bug, thanks.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by baoyinli** [comment]
Also appear

-VSCode Version: 1.24.0
- OS Version: Mac 10.12.6

**Comment by aeschli** [comment]
Can you please file that against the [Java extension](https://github.com/redhat-developer/vscode-java)
