### ISSUE TITLE
Windows Server version 1803: VS Code crashes when opening a file

### ISSUE THREAD

**Issue by pjh** [Microsoft/vscode#51504]
- VSCode Version: 1.24.0
- OS Version: Windows Server version 1803

Steps to Reproduce:

1. Start a Windows Server version 1803 VM. I'm running in Google Compute Engine.
2. In a Powershell run:
```
PS C:\> Invoke-WebRequest https://raw.githubusercontent.com/PowerShell/vscode-powershell/master/scripts/Install-VSCode.ps1 -OutFile C:\Install-VSCode.ps1
PS C:\> C:\Install-VSCode.ps1
```
3. Once installation has completed start VS Code:
```
PS C:\> & 'C:\Program Files\Microsoft VS Code\Code.exe'
```
4. Choose `File -> Open File...` and VS Code will crash.

**Comment by pjh** [comment]
Specifying a file to open on the command line still works fine. If I run e.g.:
```
PS C:\> & 'C:\Program Files\Microsoft VS Code\Code.exe' C:\Windows\WindowsUpdate.log
```

then I can edit the file, save it, close VS Code, and reopen the file again.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
