### ISSUE TITLE
Latest Update Fails

### ISSUE THREAD

**Issue by nhabbott** [Microsoft/vscode#51501]
- VSCode Version: Possibly 1.23.0 **or** 1.23.1 
- OS Version: Windows 10.0.17134 Build 17134

Steps to Reproduce:

1. Open VSCode
2. Accept prompt to update to the latest version.
3. Update dialog appears and seems to be running fine.
4. In the middle of the update, an error message appears stating to make a new issue on GitHub and to include the log file.
5. The update fails.

Does this issue occur when all extensions are disabled?: Yes/No
N/A

Log File:
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2086438/vscode-inno-updater.log)

**Comment by nhabbott** [comment]
Possibly related to: #51491

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
