### ISSUE TITLE
Unused declaration/import issues

### ISSUE THREAD

**Issue by cabbiepete** [Microsoft/vscode#51503]
- VSCode Version: 1.24.0
- OS Version: Mac OS 10.13.4

Steps to Reproduce:

The code below exhibits this issue.

```
import React from 'react';
import PropTypes from 'prop-types';

const colStyles = {
  textAlign: "center"
};

const MyComponent = () => (
        <div style={colStyles} />
);
```

The `const colStyles` is greyed out and marked as unused by visual studio code and removed if you select "Delete all unused declarations" when in it is used within the JSX code.

Similar things seem to happen for multiple named imports

```
import {
  Row,
  Column
} from 'grid';

const MyComponent = () => (
  <Row>
   <Column>Text</Column>
  </Row>   
);
```

Where grid exports a Row and a Column. In the above code Column is greyed out in the import even though it is used. Interestingly Row is not greyed out. 

If I switch the names order in the import to

```
import {
  Column,
  Row
} from '@myhr/react-ui/lib/components/grid';
```

Now Column is not greyed out but Row is.

I love the idea of the new feature but currently cannot trust it, hopefully this helps with resolving issues.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this

**Comment by cabbiepete** [comment]
Yeah it is intermittent in the current version since the patch release, if I can come up with a pattern that is reliable I'll post and reopen.
