### ISSUE TITLE
Text expansion utilities don’t work correctly

### ISSUE THREAD

**Issue by benhourigan** [microsoft/vscode#51510]
When using a text expansion utility (aText on macOS, Breevy on Windows 10), the text used to trigger the expansion is not replaced correctly in VS Code.

In this example, we use the trigger `\lipsumm` to expand some placeholder text. On VS Code, the first six characters, `\lipsu`, remain after the placeholder text is inserted.

![vs-code-text-expansion](https://user-images.githubusercontent.com/1298049/41187316-d776bcce-6bd0-11e8-96eb-a2efc9c859d8.jpg)

In all other tested applications (eg, Atom, Emacs, Vim, Firefox, Word), the entire trigger is correctly replaced.

**Comment by svenax** [comment]
For what it's worth, expansion works just fine with Typinator on macOS.

**Comment by mstenemo** [comment]
I can confirm that I have this problem with Breevy in Windows 10, although for me it only appeared after installing the Vim extension VSCodeVim, and disabling VSCodeVim seems to solve it. 

I tried changing the settings of VSCodeVim in user settings to find what could be causing it, but I was unable to find anything that solved this issue. Any ideas what in VSCodeVim could be causing it (so I can test disabling it in the user settings)?

**Comment by benhourigan** [comment]
Thanks for figuring this out @mstenemo --- I tested it myself on Mac with aText as the replacement utility, and VSCodeVim does appear to be the issue. With VSCodeVim disabled, the replacement works correctly.

I am now using vimStyle for Vim emulation, and with that extension on, text expansion is still working correctly.

**Comment by benhourigan** [comment]
@mstenemo It’s been there since at least the end of July 2017, when I used VSCode for the first time.

**Comment by mstenemo** [comment]
@benhourigan VSCodeVim does appear to be the culprit, so I think this issue can be closed. I am keeping the issue open at [VSCodeVim repo](https://github.com/VSCodeVim/Vim/issues/2818), and ideally this conversation would be merged there.

I am now using [amVim](https://marketplace.visualstudio.com/items?itemName=auiworks.amvim#overview), and text expansion is working correctly there as well, so there are at least 2 working alternatives.

**Comment by benhourigan** [comment]
I thought I’d solved this issue for good, and then it cropped up again when I enabled the [Markdown All in One](https://github.com/neilsustc/vscode-markdown) extension.

See https://github.com/neilsustc/vscode-markdown/issues/200 for discussion.

**Comment by pauljacobson** [comment]
I opened the issue for Markdown All in One. I use Alfred.app for my text expansion, and it fails partially only when I do text expansion with Alfred in VS Code with the Markdown All in One extension enabled (at least, that's the main extension I've used, and has the features I'm looking for).

**Comment by masters3d** [comment]
I wonder if this is the same issue as https://github.com/Microsoft/vscode/issues/57121
In my case, turning off all plugs doesn't change anything. I am curious if it is only a Windows Issue.

**Comment by benhourigan** [comment]
@masters3d Not Windows-only: I’m experiencing this on macOS 10.13.6.

**Comment by mstenemo** [comment]
I have had no problems with AutoHotkey specific to VSCode, so I do not think that it is the same as  #57121. I have no idea how they differ in their implementation and why only some plugins seem to cause this problem.
