### ISSUE TITLE
Can a json file be prompted with a property name?

### ISSUE THREAD

**Issue by tolerance-go** [Microsoft/vscode#51518]
![image](https://user-images.githubusercontent.com/37258382/41190546-6106666e-6c13-11e8-9b81-5691ab383b0e.png)
What should I do to get a syntactic prompt for the specified json file

**Comment by DJMcNab** [comment]
Are you looking for [the documentation on json schemas](https://code.visualstudio.com/docs/languages/json#_json-schemas-settings)? 

This describes how you can include JSON schemas to allow intellisense in a json file.
