### ISSUE TITLE
expect to join built-in PostCSS support

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#51517]
expect to join built-in PostCSS support / vscode postcss Task Configuration Tutorial

**Comment by dbaeumer** [comment]
@lihua06 can you please provide more details about the problem you are seeing. I don't understand your issue from the description you provided.

**Comment by lihua06** [comment]
Similar to this

https://code.visualstudio.com/Docs/languages/CSS#_transpiling-sass-and-less-into-css
Transpiling Sass and Less into CSS

Can add POSTCSS into css docs

**Comment by dbaeumer** [comment]
@lihua06 can you please open the issue here: https://github.com/Microsoft/vscode-docs
