### ISSUE TITLE
Outline view not working in Go

### ISSUE THREAD

**Issue by moeenz** [Microsoft/vscode#51514]
Issue Type: <b>Bug</b>

When clicked on outline items in a Go source file it just opens an `Untitled` file and says "There are no editors open that can provide outline information". I checked with Python and it was fine.

<img width="800" alt="1" src="https://user-images.githubusercontent.com/2020895/41189723-b5fccb80-6be7-11e8-9f13-8e7f1cf903b2.png">
<img width="800" alt="2" src="https://user-images.githubusercontent.com/2020895/41189734-c89f1752-6be7-11e8-994f-8785681db3ed.png">

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
vscode-markdownlint|Dav|0.18.0
EditorConfig|Edi|0.12.4
gc-excelviewer|Gra|2.0.21
vscode-docker|Pet|0.0.27
html-snippets|abu|0.2.1
toml|be5|0.0.3
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
vscode-dash|dee|1.10.0
githistory|don|0.4.1
tslint|eg2|1.0.30
LogFileHighlighter|emi|2.4.0
vscode-great-icons|emm|2.1.33
vsc-travis-ci-status|fel|1.1.0
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
python|ms-|2018.5.0
azure-account|ms-|0.4.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.82
debugger-for-chrome|msj|4.6.0
vetur|oct|0.12.5
vscode-code-outline|pat|0.2.1
java|red|0.26.0
RustyCode|sav|0.19.1
vscode-nginx|sha|0.5.0
language-stylus|sys|1.9.2
ayu|tea|0.14.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
gitblame|wad|2.4.2
debug|web|0.22.0
markdown-all-in-one|yzh|1.4.0

(1 theme extensions excluded)

</details>

**Comment by moeenz** [comment]
I don't find this issue in the recommended duplicate ones.

**Comment by ramya-rao-a** [comment]
This is being tracked in https://github.com/Microsoft/vscode-go/issues/1725
