### ISSUE TITLE
Status bar text without a click action should not have text cursor on hover

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#51515]
Can't take a screenshot but the text in this has the text cursor but cannot be selected:

<img width="194" alt="screen shot 2018-06-09 at 11 35 03 am" src="https://user-images.githubusercontent.com/2193314/41190118-50878ff0-6bd9-11e8-9c64-c4a34837c411.png">

**Comment by bpasero** [comment]
@Tyriar is that on macOS? I do not see that, I just see the arrow cursor.

**Comment by Tyriar** [comment]
Yes macOS, I can repro now.

**Comment by Tyriar** [comment]
Thanks @LeonardoBraga 😃
