### ISSUE TITLE
Finding definitions exported by string key does not work

### ISSUE THREAD

**Issue by Flamefire** [Microsoft/vscode#51520]
- VSCode Version: 1.24.0
- OS Version: WIn10 x64

Steps to Reproduce:

1. Export by string key:
```
function parse(){return 1;}
exports["parse"] = parse; // exports.parse = parse;
```
2. Import and try GoTo Def:
require("./foo")
foo.parse(); // Not found

Does this issue occur when all extensions are disabled?: Yes

Both versions (`exports["parse"] = parse; // exports.parse = parse;`) should work exactly the same.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24895
