### ISSUE TITLE
[loc]Request to add Kannada (Kan) language to VS Code project in Transifex L10N

### ISSUE THREAD

**Issue by PallaviAbhijith** [Microsoft/vscode#51526]
We expect at least three Kannada language contributors sign up and product team sign off before adding new language to Transifex. Please vote by adding your Transifex account name here in this issue (request).
How to request guide:  https://www.transifex.com/user/profile/PallaviAbhijith/

**Comment by PallaviAbhijith** [comment]
Not covered in existing list.

**Comment by abhijithda** [comment]
Looking for Kannada language option in VS Code.
https://www.transifex.com/user/profile/abhijith

**Comment by bhagn** [comment]
I'm not able to request for Kannada language on Transifex, as the language has already been requested. Not sure how to join. Here's my transifex profile:
https://www.transifex.com/user/profile/bhagn/

**Comment by dhoomakethu** [comment]
Same here as @bhagn above, not able to find/request for kannada language for vscode on transifex. Let me know how can I contribute. For reference here is my transifex profile
https://www.transifex.com/user/profile/dhoomakethu/

**Comment by veeru-as** [comment]
https://www.transifex.com/user/profile/veeru_as/

**Comment by danyeh** [comment]
Thank you for showing interest to contribute! Kannada (Kn) has been enabled for VS Code projects in Transifex.
