### ISSUE TITLE
Yaml is broken in VS Code 1.24.0

### ISSUE THREAD

**Issue by trondhindenes** [Microsoft/vscode#51522]
- VSCode Version: 1.24.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:
Given this yaml doc:
When I hit enter on line 64, the cursor is moved 4 spaces in. There's no reason why it should do that. I love Code, but these yaml issues happen far too frequent.

Original doc
![screenshot from 2018-06-09 16-15-20](https://user-images.githubusercontent.com/1747120/41192614-c05d3196-6c00-11e8-9ddc-7b0386c2da33.png)

After hitting Enter while cursor is in position 0 on line 64:
![screenshot from 2018-06-09 16-15-32](https://user-images.githubusercontent.com/1747120/41192616-d20ebcc0-6c00-11e8-95f8-c9d466af5131.png)

**Comment by aeschli** [comment]
I'm not aware of any changes in that area and I also can't reproduce this.
- is your editor in 'yaml' mode
- Can you try without extensions?
- the default settings for yaml are:
	"[yaml]": {
		"editor.insertSpaces": true,
		"editor.tabSize": 2,
		"editor.autoIndent": false
	}
Please make sure you have not modified the `"editor.autoIndent": false` setting
