### ISSUE TITLE
Commands executed from command palette are not logged

### ISSUE THREAD

**Issue by cezn** [microsoft/vscode#51529]
- VSCode Version: 1.24.0
- OS Version: Ubuntu 16.04

Step to reproduce:
1. Set log level to trace.
2. Execute command using keyboard shortcut
3. Check command log in output panel - command logged.
4. Execute same command using command palette.
5. Check command log in output panel - command is not logged. 
![code_log_commands](https://user-images.githubusercontent.com/14140583/41194561-57019a62-6c1d-11e8-9a68-dcaa3857ec92.gif)  

Expected behavior:
Commands executed from command palette are logged to output panel.

**Comment by alexdima** [comment]
This has been fixed in the meantime:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/5047891/86638106-03274300-bfd7-11ea-8847-ce1bab8c6fb4.png">
