### ISSUE TITLE
Error Message"Cannot read property 'toString' of null" when using Save All if Markdown Preview is open

### ISSUE THREAD

**Issue by michaeldaw** [Microsoft/vscode#51523]
It seems like this may be related to #51381, but that one doesn't mention the Markdown Preview window, and that's the only place I've seen this.

In summary, markdown files can be saved, but if the Save All command is used, the editor seems to attempt to also "save" the Preview, which results in the error mentioned in the title.

- VSCode Version: 1.25.0-insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Create a markdown file.
2. Click on "Open Preview to the Side" (Ctrl +K V).
3. Edit the file with some text.
4. Use the Save All command (with a shortcut key or File->Save All
5. Observe an error popup that reads "Cannot read property 'toString' of null"
![image](https://user-images.githubusercontent.com/8949148/41193257-d58c1fb2-6bc6-11e8-8392-264bf53f05af.png)

Other info:
The user can save the markdown file individually. Also, if the Markdown Preview view is in focus and the Save command is attempted, the message is displayed but as a warning instead of an error:
![image](https://user-images.githubusercontent.com/8949148/41193253-cd52e6b4-6bc6-11e8-9a3f-06bb8d78ac69.png)

The error **does** occur with extensions disabled.

**Comment by mjbvz** [comment]
Looks fixed in latest insiders build: 28d5806f24f99c2c6ad633e4e08ed5ea00169c83

Let me know if you still see it on this build with all extensions disabled
