### ISSUE TITLE
Starting VSCode with a non-English layout and then switching to English

### ISSUE THREAD

**Issue by jonathanherdt** [Microsoft/vscode#5152]
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.4

Steps to Reproduce:
1. Switch to non-English keyboard layout (in my case German)
2. Start VSCode
3. Switch to U.S. keyboard layout
4. Hit CMD+/
5. Nothing happens, even though this should comment / uncomment
6. Switch back to German keyboard layout
7. Hit CMD+- ('-' (dash) on the German keyboard layout is in the same location as '/' (slash) on the U.S. keyboard layout)
8. Now you get comment / uncomment

Possibly related issues: #4619, #1549, #1492

**Comment by alexandrudima** [comment]
For performance reasons, we detect the keyboard layout once, when you first press a key. We then cache this information until a restart. AFAIK there is no browser event to know when the keyboard layout has changed, so we would need to poll on the keyboard layout. It is unfortunate.

**Comment by whee** [comment]
I believe there is more to it. I am using the Dvorak keyboard layout. If the first key combination I press is "Cmd-,", VS Code acts as if I hit 'Cmd-w" -- the QWERTY key. There is no switching of layouts in this case and the only layout configured on my system is Dvorak.

**Comment by jonathanherdt** [comment]
Yup, pretty much what I found, too. The behavior of VSCode doesn't make much sense in this way. It accepts the wrong key combination if it starts up with the user having set a non-English keyboard layout. Maybe this is also related to me having set English as my system language.

**Comment by henriiik** [comment]
I ran into this problem as well, (i use swedish and english keyboard layouts).

Perhaps a solution could be to have a command that you can invoke to clear the cache?

**Comment by alexandrudima** [comment]
> Perhaps a solution could be to have a command that you can invoke to clear the cache?
:+1:

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today'sInsiders build), on OSX, we detect keyboard layout changes and update the keybinding service appropriately. I have tested with these exact steps

**Comment by mpseidel** [comment]
Having the same issue in Windows. Anything I can do about it?
