### ISSUE TITLE
Why is Copy/Paste so far down the right-click list?!

### ISSUE THREAD

**Issue by davelogear** [Microsoft/vscode#51527]
Sometimes right-click copy/paste is easier than Ctrl+C or Ctrl+V... but for some reason VS Code puts Copy and Paste WAY down the right-click list, and I'm not understanding this.

Are these features used less often than the ones above them?

![image](https://user-images.githubusercontent.com/32692076/41194292-6b2324ee-6bd6-11e8-91c3-2057bfff5644.png)

I also notice Windows does the same thing... and it's very annoying.

**Comment by alexandrudima** [comment]
I think we tried to align with existing context menus and thus arrived at this order.

IMHO, cut, copy and paste are some of the most used shortcuts on the planet. IMHO it is far more likely that someone uses the keyboard and not the mouse to Copy, and probably more likely that someone uses the mouse (via context menu) to Refactor or Format Selection, etc.

We don't plan to change this order.

**Comment by davelogear** [comment]
Sometimes I only need the mouse, sometimes I only need the keyboard... I say make repetitive tasks as easy as possible. A lot of times I'm in code or whatever just using the mouse or keyboard, and having to keep switching or hunt and peck over and over adds up.
