### ISSUE TITLE
Extension host only modules gets loaded in renderer side

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5153]
extHostDocuments requires "weak" even though this module is only used in the extension host side it gets loaded from the renderer side because of https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L49

Imho we should do a clean split between modules needed for API that get loaded on the renderer side vs. extension host side. Otherwise it is easy to accidentally sneak in modules into the renderer. We should stay away from that because module loading slows down startup.

**Comment by jrieken** [comment]
This case should be doable, tho not everything can be done like that cos of our proxying story

**Comment by jrieken** [comment]
Actually, we cannot do this without reasonable effort. The proxy story is all about knowing both endpoints _MainXYZ_ and _ExtHostXYZ_ on both sides. This approach gives type-safety but the drawback is that the code is loaded on both sides.

**Comment by jrieken** [comment]
fyi @alexandrudima

**Comment by bpasero** [comment]
Here is a list of modules we load from the renderer and their times, weak seems to cause around 10% of the overall loading:

![image](https://cloud.githubusercontent.com/assets/900690/14429912/aa76f0e8-ffff-11e5-942e-f3fc25d0ce97.png)

**Comment by jrieken** [comment]
I know - it's a said story...
