### ISSUE TITLE
All of my TypeScript tasks stopped working since the 1.24 update

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#51534]
- VSCode Version: 1.24
- OS Version: Windows 10

I have a workspace with about 15-20 project folders, some of which are TypeScript projects. Each TypeScript project has its own set of build tasks in its respective `.vscode` folder. Up until now, I could press CTRL+SHIFT+B and the quick bar would show me a list of all of my build tasks from which I could make a selection to initiate a build.

Today I tried this and instead of the normal behaviour, the tasks panel is displaying one of these for every build task in every project:

```
Error: The typescript task detection didn't contribute a task for the following configuration:
{
    "label": "@frptools/corelib [es2015]",
    "group": "build",
    "type": "typescript",
    "tsconfig": "@frptools\\corelib\\tsconfig.es2015.json",
    "option": "watch",
    "problemMatcher": {
        "base": "$tsc-watch",
        "fileLocation": [
            "relative",
            "${workspaceFolder}/../../../"
        ]
    }
}
```

No explanation _why_ it "didn't contribute a task". I haven't changed these tasks in months, nor have I have changed the workspace structure in that time. The only difference I can see is that I updated to VS Code 1.24 yesterday.

Here's an example of the `tasks.json` file in one of my projects:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "@frptools/corelib [es2015]",
      "group": "build",
      "type": "typescript",
      "tsconfig": "@frptools\\corelib\\tsconfig.es2015.json",
      "option": "watch",
      "problemMatcher": {
        "base": "$tsc-watch",
        "fileLocation": ["relative", "${workspaceFolder}/../../../"]
      }
    },
    {
      "label": "@frptools/corelib [commonjs]",
      "group": "build",
      "type": "typescript",
      "tsconfig": "@frptools\\corelib\\tsconfig.commonjs.json",
      "option": "watch",
      "problemMatcher": {
        "base": "$tsc-watch",
        "fileLocation": ["relative", "${workspaceFolder}/../../../"]
      }
    },
    {
      "label": "@frptools/corelib [tests]",
      "group": "test",
      "type": "typescript",
      "tsconfig": "@frptools\\corelib\\tsconfig.tests.json",
      "option": "watch",
      "problemMatcher": {
        "base": "$tsc-watch",
        "fileLocation": ["relative", "${workspaceFolder}/../../../"]
      }
    }
  ]
}
```

**Comment by dbaeumer** [comment]
I will investigate. One quick question: did you by any change turn typescript task auto detection off. The setting is `typescript.tsc.autoDetect` and it must be set yo on to make this work in our setup.

**Comment by dbaeumer** [comment]
I am not able to reproduce this using the attached example. @axefrog can you provide me with a GitHub repository I can close that demos this?

[51534.zip](https://github.com/Microsoft/vscode/files/2089133/51534.zip)

**Comment by axefrog** [comment]
@dbaeumer Thanks for taking a look. I haven't disabled that feature to my knowledge...

I am not sure I can provide repo - my workspace is a collection of repositories managed via a unified Yarn workspace. Is there some kind of logging that might help me provide more useful information?

**Comment by dbaeumer** [comment]
Actually not. We can try one thing. Rename tasks.json to tasks.json.off and then execute Task > Run Task. Will the tasks be listed. If yes, press the gear button next to one of the tasks and see if the generated tasks.json differs?
