### ISSUE TITLE
Integrated Terminal Suppresses Windows Crash Reporter

### ISSUE THREAD

**Issue by bhelyer** [Microsoft/vscode#51538]
Issue Type: <b>Bug</b>

<b>Steps to reproduce</b>:
1. Open VS Code
2. Open Integrated Terminal
3. Run A Program That Crashes*

<b>Expected Result</b>: The "test.exe has stopped working" report that allows the user to launch a debugger.
<b>Actual Result</b>: Nothing. The program silently fails, forcing the user to repro in a cmd.exe window or to attach the debugger before the crash (if possible).

*A segfault will suffice. Here's a C program you can use if you don't have any buggy software handy:
```c
#include <stdlib.h>

int main(void) {
    int* ip = NULL;
    return *ip;
}
```

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 945 Processor (4 x 3010)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Bernard\Desktop\volta.code-workspace|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
