### ISSUE TITLE
Multiple commands for events in trees

### ISSUE THREAD

**Issue by nickdodd79** [Microsoft/vscode#51536]
Not sure if I have missed something in the documentation, but I need to handle multiple events on items in a tree (click, double click and enter). I have an extension that displays and runs gulp tasks within a workspace. 

At the moment, I have a command that tracks the selection of an item, which in turn controls relevant nav icons depending on the item's state (e.g. if idle an execute icon is shown, if executing a terminate icon is shown).

I am hoping to add a feature where users a can double click or press enter to execute a task, but still allow selection to be activated with a single click. This would require multiple commands to be registered for a tree item.

Can a change be made so `TreeItem` instances can have event driven commands. Something like:

`clickCommand`
`keypressCommand`
`doubleClickCommand`

Which will also provide the triggered event object. In the example of keypress, providing the event will allow the key that activated the event to be resolved.

**Comment by sandy081** [comment]
There are plans to support double click command but not keypress. See https://github.com/Microsoft/vscode/issues/39601
