### ISSUE TITLE
Local editor settings not being overridden by ESLint settings

### ISSUE THREAD

**Issue by geuis** [Microsoft/vscode#51539]
- VSCode Version: Version 1.24.0 (1.24.0)
- OS Version: Mac High Sierra 10.13.4 
- ESLint Extension: 1.4.12

Steps to Reproduce:
1. The default behavior for VSCode is to add spaces to objects:
```
const x = { a: 123 };
```
2. I have a `.eslintrc` config setup with the rule `"object-curly-spacing": ["error", "never"]`. Linting occurs and reports the default spacing behavior as an error as expected. 
3. This behavior can be overridden in the VSCode settings via `"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false`
4. I was expecting that the default behavior of VSCode would be overridden by the ESLint rules when formatting code. 

Does this issue occur when all extensions are disabled?: No. The ESLint extension must be installed for VSCode to utilize the `.eslintrc` rules.

This may be an issue correctable in the ESLint extension. If so I will move this issue to that project.

**Comment by dbaeumer** [comment]
This is not the case. I see the desire but currently there is not knowledge between TS/JS and ESLint in terms of extensions. And the setting story of VS Code doesn't allow the temporary shadowing of settings. And writing them to a settings file wouldn't be nice either. Feel free to open an issue against ESLint, however given the current architecture of VS Code it is not easy addressable.

**Comment by geuis** [comment]
Thanks @dbaeumer. Totally understandable. Going with having the local vscode settings checked into the project.
