### ISSUE TITLE
Command to open/toggle the inline changes view which opens by clicking the diff decorator

### ISSUE THREAD

**Issue by franciscolourenco** [Microsoft/vscode#51549]
Request for a command to toggle the inline changes view under or closest to the cursor.

<img width="1085" alt="screen shot 2018-06-10 at 15 49 30" src="https://user-images.githubusercontent.com/208149/41202201-e198fa32-6cc5-11e8-8f50-99ff180c55b4.png">

**Comment by joaomoreno** [comment]
The command is `editor.action.dirtydiff.next`, the keybinding is <kbd>Alt F3</kbd>.

**Comment by franciscolourenco** [comment]
Ah! there is "Move to next change" and "Show next change". thanks!
