### ISSUE TITLE
terminal only supports monospace fonts

### ISSUE THREAD

**Issue by HappySven** [Microsoft/vscode#51543]
VSCode Version: 1.24.0-insiders
OS Version: ubuntu18.04

I use zsh and powerline9k.

My regular terminal looks like....
![terminal](https://user-images.githubusercontent.com/24653356/41201018-148537c2-6ce3-11e8-8499-f35f30ee4c5e.png)

And this is my integrated terminal
look like this.
![vscode](https://user-images.githubusercontent.com/24653356/41201019-152b243e-6ce3-11e8-89cf-d5e351361ad6.png)

I try to change `terminal.integrated.fontFamily`  when i had read #7116,#15119
but then ..
![only](https://user-images.githubusercontent.com/24653356/41201082-ef64ff44-6ce3-11e8-867a-a4444e7c03c4.png)

how can i fix this ? this my first issue :)

**Comment by Tyriar** [comment]
You set your font to monospac, it's missing the e.

**Comment by HappySven** [comment]
Even though i hit that button ' use 'monospace' ', my integrated terminal font still break. I think the problem is not about 'missing e', its about 'only support' make me can not change it to other font . Just like 'Hack Nerd Font Bold' (what my regular terminal use).
So , how can i make `terminal.integrated.fontFamily` support it ?

(I am a student, and my english is not good, if i writ something wrong, just forget is  :) )

**Comment by HappySven** [comment]
@Tyriar

**Comment by Tyriar** [comment]
The way the popup works is when the font is changed it will measure the `i` of the font and the `w`, if their width differs it's assumed it's not a monospace font. If you like your font and you get the warning you're fine to keep using it and ignore the warning, but we don't support proportional fonts: https://github.com/Microsoft/vscode/issues/35681

**Comment by HappySven** [comment]
I fix it by install all of this https://github.com/ryanoasis/nerd-fonts .
And the change `terminal.integrated.fontFamily` to a nerd font.

![screenshot from 2018-06-11 13-58-52](https://user-images.githubusercontent.com/24653356/41214769-9808306c-6d7f-11e8-8aed-d2bcedaedd1c.png)

Best everybady of you ! @Tyriar

**Comment by Zingoer** [comment]
@HappySven 
I've download the Nerd Font Meslo to my ~/.local/share/fonts. 
I try to change my `terminal.integrated.fontFamily` to
`"terminal.integrated.fontFamily": "Meslo LG S Regular"`
or
`"terminal.integrated.fontFamily": "Meslo LG S Regular Nerd Font Complete"`
But I still get the same problem. Do I need to do anything to enable nerd font?

**Comment by AlexZeitler** [comment]
@Zingoer `MesloLGM Nerd Font` fixed it for me as well. Thanks!
