### ISSUE TITLE
output got messy code

### ISSUE THREAD

**Issue by OhYee** [Microsoft/vscode#51541]
If I use python to run a file to show chinese in the task, it will output messy code in output.
And if I use javac to compile file in the task, it will output messy code in output.

I have read #50451 #38915 #35235, but it is no use.

It just occur when I use the third part program to output the chinese but not Windows command. And the terminal can run them without messy code.

The Python version is Python 3.6.0

**May be the system language should be chinese**

> If my english is hard to understand, maybe use chinese is better.
> 
> 使用Windows自带的指令输出中文内容没有乱码，但是task调用别的第三方应用再输出中文会乱码
> 这个问题只在output存在，在终端中正常

- VSCode Version: 1.24.0
- OS Version: Windows Insider Preview 17686.re_prerelease.180603-1447

Steps to Reproduce:

1. tasks.json
```
{
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "test",
            "command": "echo",
            "args": [
                "中文"
            ]
        },
        {
            "taskName": "test2",
            "command": "cat",
            "args": [
                "${file}"
            ]
        },
        {
            "taskName": "test3",
            "command": "python",
            "args": [
                "${file}"
            ]
        }
    ]
}
```
2. test.py
```
print("123abc中文")
```
3. run tasks `test` `test2` `test3`
4. got the output
  - test
    `中文`
  - test2
    `print("123abc中文")`
  - test3
    `123abc����`
5. use terminal to run the python file `python test.py`, it run correctly

Does this issue occur when all extensions are disabled?: Yes

the screenshot:

- test
 ![test](https://user-images.githubusercontent.com/13498329/41199336-84863614-6cc2-11e8-9e4e-44ee5816883e.jpg)
- test2
 ![test2](https://user-images.githubusercontent.com/13498329/41199370-4a630330-6cc3-11e8-955a-fbaf6ad140f9.jpg)
- test3
 ![test3](https://user-images.githubusercontent.com/13498329/41199380-7d672c84-6cc3-11e8-923a-96ca446ec4cc.jpg)
- terminal 
![terminal](https://user-images.githubusercontent.com/13498329/41199383-85d8c440-6cc3-11e8-8ba4-65df7f8160e6.jpg)

**Comment by dbaeumer** [comment]
You should upgrade to Tasks 2.0.0 which executes in the terminal which has full support to ANSI control characters and better encoding. See https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200 and https://code.visualstudio.com/docs/editor/tasks#_changing-the-encoding-for-a-task-output
