### ISSUE TITLE
Command to "Open Changes"

### ISSUE THREAD

**Issue by franciscolourenco** [Microsoft/vscode#51548]
Keyboard shortcut to see the SCM changes for the current file, is missing, even though there is a button in the UI.

<img width="151" alt="screen shot 2018-06-10 at 15 32 31" src="https://user-images.githubusercontent.com/208149/41202044-c8a45e88-6cc3-11e8-902f-81fbd3191d57.png">

**Comment by joaomoreno** [comment]
You can define your own keybindings: https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by franciscolourenco** [comment]
I was actually referring to the command, for some reason it was not showing up in the command list, but now it is. thanks!
