### ISSUE TITLE
unable to stop single quote warning

### ISSUE THREAD

**Issue by peterremote1980** [Microsoft/vscode#51542]
in tsx file, it warn me:

[tslint] ' should be " (quotemark)

Tried different options in tslint.json and still unable to hide this warning in latest vscode. Please help

The below setting was working, but not now
	"lintConfig": {
		// Opt-in to Lint rules which help to eliminate bugs in JavaScript
		"rules": {
			**"quotemark": [true, "single"]**
		}
	}

Thanks
Peter

**Comment by mxschmitt** [comment]
Duplicate of https://github.com/Microsoft/vscode-tslint/issues/354

**Comment by aeschli** [comment]
Closing as duplicate
