### ISSUE TITLE
Unable to open 'file.ext': File not found (file:///file.ext). 

### ISSUE THREAD

**Issue by sebasijan** [Microsoft/vscode#51540]
## Environment data
`dotnet --info` output:

	.NET Command Line Tools (2.1.300-preview1-008174)

	Product Information:
	 Version:            2.1.300-preview1-008174
	 Commit SHA-1 hash:  b8df89a54f

	Runtime Environment:
	 OS Name:     Windows
	 OS Version:  10.0.17134
	 OS Platform: Windows
	 RID:         win10-x64
	 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

	Microsoft .NET Core Shared Framework Host

	  Version  : 2.1.0-preview1-26216-03
	  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

VS Code version:

	Visual Studio Code
	Version 1.23.1
	Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
	Date 2018-05-10T17:11:17.614Z
	Shell 1.7.12
	Renderer 58.0.3029.110
	Node 7.9.0
	Architecture x64

C# Extension version:

## Steps to reproduce

 1. Create console app
 2. Leave some error in the code and try to debug
 3. Click on the error in `Problems` tab

![Uploading image.png…]()

## Expected  behavior

When I click on the error it should just take me to the error.

## Actual behavior

VSCode complains that the file cannot be found, even though it clearly knows about the file since it notified me about the error......

![capture](https://user-images.githubusercontent.com/13226838/41198440-77689ff6-6cbf-11e8-97f8-f2952db98f35.PNG)

**Comment by weinand** [comment]
Please file this issue against the C# extension.
You can use this tool: https://github-issue-mover.appspot.com/
