### ISSUE TITLE
VS Code creates new a file instead of overwriting the existing one

### ISSUE THREAD

**Issue by Crunnie** [Microsoft/vscode#51545]
- VSCode Version: 1.24
 - OS Version: Windows 10 Pro

**Steps to Reproduce:**

(Using code for a discord.js bot)
1.  Create a command (for example a basic earn command) and hook it up to a .json file that __isn't__ in the same folder as the command.js file
2. Launch the bot using F5 key
3. Use the command

**What should happen?:**
The .json file overwrites.

**What actually happens:**
It creates a new .json file in the desktop (or any other folder outside the folder you're working in, yes I checked the code and I redirected to the .json file correctly)

**Does this issue occur when all extensions are disabled?:** 
Yes

**Comment by bpasero** [comment]
> Create a command (for example a basic earn command) 

@Crunnie how, what does this mean? Are you using some extension?

**Comment by Crunnie** [comment]
@bpasero I don't use any extensions. It's just normal code.

**Comment by bpasero** [comment]
@Crunnie can you maybe record a screencast of what the issue is?
