### ISSUE TITLE
Syntax colouring error on `of` when out of a `for ... of` statement

### ISSUE THREAD

**Issue by fguitton** [Microsoft/vscode#51544]
- VSCode Version: 1.24.0
- OS Version: Windows 10

Hello everybody !

The following issue is also present on a vanilla fresh install of VSCode Insider.

While using something like the RxJS library which exports an `of` function, the syntax colouring misses on it. I imagine is believes it part of a `for … of` structure.

![image](https://user-images.githubusercontent.com/2495155/41201102-94102e50-6ca9-11e8-9db5-63e7bf873c88.png)

Best day to you all 👍

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#628
