### ISSUE TITLE
[Request] Better scrolling of the file tabs headers

### ISSUE THREAD

**Issue by blendsdk** [Microsoft/vscode#51546]
Hi,

I was wondering if the file tab headers can be scrolled in a more user friendly way. At the moment a thin line appears on the bottom of tab headers which makes clicking and grabbing difficult.

Please see screenshots:

![screen shot 2018-06-10 at 14 41 39](https://user-images.githubusercontent.com/5524595/41201741-caea3df8-6cbd-11e8-9f5d-64704b8e585a.png)
![screen shot 2018-06-10 at 14 46 56](https://user-images.githubusercontent.com/5524595/41201742-cb021ce8-6cbd-11e8-82d3-a479bc5be500.png)

- VSCode Version: 1.24.0
- OS Version: OSX Sierra

**Comment by bpasero** [comment]
@blendsdk so what is your suggestion?

**Comment by blendsdk** [comment]
@bpasero my suggestion would be to remove the mini-horizontal scrollbar and have clickable UI to shift the tabs to left and right if the total number of tab widths exceeds the screen area. For example:

(Make your browser smaller and click Run)
https://fiddle.sencha.com/#view/editor&fiddle/1ri6
