### ISSUE TITLE
"Move to Next Change" and "Move to Previous Change" should open next inline changes view

### ISSUE THREAD

**Issue by franciscolourenco** [Microsoft/vscode#51550]
When one inline changes view is open, "Move to Next Change" and "Move to Previous Change" should also show the change after moving the cursor.

They should also open the diff view in case it was closed.

<img width="1085" alt="screen shot 2018-06-10 at 15 49 30" src="https://user-images.githubusercontent.com/208149/41202244-6b851bfe-6cc6-11e8-8ccc-ca0dd38f9ab9.png">

**Comment by joaomoreno** [comment]
There is `Move to Next Change`, but there is also `Show Next Change`. You want the latter.
