### ISSUE TITLE
Option to suppress noImplicitAny warnings in imports

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#51558]
The latest VS Code now shows warnings on any imports that are typed as any.  You can turn this off by setting `noImplicitAny: false` is tsconfig.json, but it would be incredibly useful to have an IDE-level setting that would allow us to disable this.

**Comment by mjbvz** [comment]
This should be off by default if the file is not part of any `tsconfig` or `jsconfig`. Do you have a small example project that demonstrates the problem?

**Comment by arackaf** [comment]
Oh no, the file is definitely a part of my tsconfig. I'm just saying it would be a good UI feature to optionally tell VS Code to not report / warn about this.

**Comment by mjbvz** [comment]
Please file this against typescript since I believe this would also be an error when you run `tsc`
