### ISSUE TITLE
Place scrollbarSlider.background below syntax blocks/characters in minimap

### ISSUE THREAD

**Issue by will-stone** [microsoft/vscode#51555]
Hi. Thanks for the latest release! Loving the latest features.
I'm a themer and I've noticed that to make the minimap background look good, I need to use a transparent colour for `scrollbarSlider.background`; otherwise the built-in amount of transparency used is still quite dark:

<img width="106" alt="image" src="https://user-images.githubusercontent.com/654103/41203260-5c4158c8-6ccc-11e8-8cd7-0d7454cd93de.png">

I was wondering if it'd be a good idea if the syntax characters/blocks could be _on top of_ the highlight, meaning I can work easier with solid colours and not need think about how much transparency Code is going to add for me (because it wouldn't be needed any more).

**Comment by alexandrudima** [comment]
It is very convenient to have the slider rendered on top of the minimap pixels, as they can be independently optimized. From frame to frame, the minimap will reuse its pixels from the previous frame, and painting the slider as part of the minimap pixels would make such an optimization a lot more difficult.

**Comment by will-stone** [comment]
Huh? Isn’t it just a z-index tweak?

**Comment by alexandrudima** [comment]
To change the dom elements order, we would need to:
- tweak z-index
- rethink how mouse handling works (a listener is now registered on the slider dom node)
- make the minimap canvas have a transparent background.

**Comment by will-stone** [comment]
I've only had a peek at the dev tools and the DOM structure but my thoughts would be:
- Move slider behind canvas (the map) using z-index
- Allow mouse events to pass through the canvas by using `pointer-events: none`
- Canvas is transparent by default so whatever is colouring this in can be turned-off.

**Comment by will-stone** [comment]
Thanks @alexandrudima I've had a poke around in there and I can't see an easy way to simply remove the background without removing items that may be important to other parts of the UI. However, I've never looked as Code's code before and so I'm going to have to leave this for the professionals.
