### ISSUE TITLE
SCM keyboard/command usability improvements

### ISSUE THREAD

**Issue by franciscolourenco** [Microsoft/vscode#51551]
Issue to keep track of all issues related to SCM keyboard usage:

https://github.com/Microsoft/vscode/issues/48964
https://github.com/Microsoft/vscode/issues/48965
https://github.com/Microsoft/vscode/issues/51548
https://github.com/Microsoft/vscode/issues/38113
https://github.com/Microsoft/vscode/issues/44904
https://github.com/Microsoft/vscode/issues/7717
https://github.com/Microsoft/vscode/issues/51549
https://github.com/Microsoft/vscode/issues/51550

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
