### ISSUE TITLE
Ctrl+P and Ctrl+N for up/down navigation everywhere

### ISSUE THREAD

**Issue by chanshing** [Microsoft/vscode#51556]
Hi, is it possible to customize `Ctrl+P` and `Ctrl+N` for up/down navigation (almost) everywhere? I saw a feature was implemented for Quick Open in [issues/7876](https://github.com/Microsoft/vscode/issues/7876), but I would also like to have it in the command palette or for example while searching a simbol using `@` and `#`. 
For Quick Open, there is `quickOpenNavigateNext` or `quickOpenSelectNext` when `inQuickOpen`, but I couldn't find similar things for command palette or when searching symbols.
Thanks!

**Comment by roblourens** [comment]
"Quick open" includes the command palette and everything else here. Ctrl+P/N works for me there, it should work for you too. Does it not?

**Comment by chanshing** [comment]
You are right, my mistake is that I was using the conditional `inQuickOpen && inFilesPicker` so it was only working in Quick Open but not in the command palette. By having only `inQuickOpen` solved the problem. Thanks!
