### ISSUE TITLE
Setting to show modals as normal notifications

### ISSUE THREAD

**Issue by tehwalris** [Microsoft/vscode#51559]
Recently modal pop-up windows are shown for important information (eg. must pull before push in git). I understand that this behavior is intentional and benefits many users.

However having both modals and normal notifications has the following downsides:
- Two different places to look (middle vs bottom of screen)
- Two different sets of shortcuts to dismiss
- Modals can be very disruptive in some window managers
- Fuels discussions about what should be modal (like [this](https://github.com/Microsoft/vscode/issues/48606))

I suggest adding a global setting to show all modals as notifications. It would default to the current behavior. This would address the issues I listed for users who they concern without confusing new users.

**Comment by bpasero** [comment]
We decided that some notifications must be modal when it makes sense. Closing as no intent to change this.
