### ISSUE TITLE
Syntax highlighting stopped working

### ISSUE THREAD

**Issue by shivam-tripathi** [Microsoft/vscode#51553]
- VSCode Version:  1.24.0 (1.24.0)
- OS Version: Mac OS X High Sierra 10.13.1

Steps to Reproduce:

1. Start typing, syntax highlights
2. Suddenly syntax highlighting stops to work

It occurs across all themes. The syntax highlighting disappears and all text appears gray.

Does this issue occur when all extensions are disabled?: Yes, the syntax highlighting is there for a split second and then it disappears.
 
![vscode-weird](https://user-images.githubusercontent.com/9463078/41202987-ee55d21c-6cee-11e8-9ac3-0fcd1f8bec6e.gif)

**Comment by shivam-tripathi** [comment]
Perhaps, now reading the above duplicate detection - I think this happened after I tried to open a file of around 250+MB size on disk. I closed the file before it could load. There was some notification regarding optimisations, but as I didn't open the file I closed it. After that, this 😭

**Comment by shivam-tripathi** [comment]
Also, this is happening only in JS files. I tried tying in python and C++ files, and it works fine there. Files which have been previously created have their syntax highlight intact, but any new addition to the files doesn't work. 
I don't know if it's important, but I tried to open a big file a couple of minutes before this happened. I closed it before it could open, and closed all associated notifications with it.

**Comment by shivam-tripathi** [comment]
Ok, looked into a bit. I think this is becase of linting errors - or rather any form of error - whichever line has some error, turns gray untill the error has been resolved. Something similar to red underlining - just that syntax highlighting disappears and code turns gray in color.

**Comment by bruno02221** [comment]
Yes @shivam-tripathi, this is the new _unused import detection_ feature from version **1.24**, look: https://code.visualstudio.com/updates/v1_24#_highlight-unused-variables-and-imports

**Comment by shivam-tripathi** [comment]
Oh, great! Thank you for clarifying.
VSCode rocks! 😃
