### ISSUE TITLE
Characters are not rendered with correct width when using dom renderer

### ISSUE THREAD

**Issue by johnp789** [Microsoft/vscode#51552]
- VSCode Version:
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-07T23:36:38.731Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
Arch Linux 4.16.11 on x86_64

Steps to Reproduce:

1. Set `"terminal.integrated.rendererType": "dom"`
2. Open integrated terminal with bash session
3. Run `for i in $(seq 1 30) ; do echo -n 0123456789 ; done`
4. Observe missing digits at right-hand edge of terminal
5. Compare with default renderer, where all digits are visible, and characters are rendered with slightly narrower widths

![screenshot from 2018-06-10 08-47-40](https://user-images.githubusercontent.com/243768/41202274-29a57920-6c8c-11e8-962a-5fbdabed7039.png)

With the default terminal renderer, this issue is not observed:

![screenshot from 2018-06-10 08-46-38](https://user-images.githubusercontent.com/243768/41202294-7c441448-6c8c-11e8-9884-17b314046b37.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51479
