### ISSUE TITLE
console.log by default in Intellisense when writing `log`

### ISSUE THREAD

**Issue by BrodaNoel** [Microsoft/vscode#51567]
Hi guys!
Check this screenshot:
<img width="570" alt="screen shot 2018-06-10 at 21 20 55" src="https://user-images.githubusercontent.com/1837969/41207970-1dbdff48-6cf4-11e8-85bf-b2bcc9cebb6b.png">

If I press ENTER, the first option is only to leave "log" wrote as it is.
But, if I press "DOWN ARROW", and then ENTER, this second option is going to replace my `log` with `console.log`. I guess this second option, should actually be the first one in the IntelliSense options.

**Comment by aeschli** [comment]
The second one is a snippet proposal. Read here about snippets: https://code.visualstudio.com/docs/editor/userdefinedsnippets

The setting ` editor.snippetSuggestions` lets you control how snippets are sorted relative to the regular proposals.
