### ISSUE TITLE
Changes in ç letter on the US-Intl keyboard

### ISSUE THREAD

**Issue by la-costa** [Microsoft/vscode#51561]
Something is strange, before version 1.24.0 the letter cedilla was being generated when pressed the symbol ' followed by the letter c.
Now if i do this, the VS Code shows "ć". In this version, i need to press Alt + '.
All my workspace (Gnome) works correctly, only in VS Code i have this issue.
It seems that in the past, Fedora had some problem like this:: https://ask.fedoraproject.org/en/question/28468/problems-with-letter-c-in-us-international-keyboard-fedora-19/

- VSCode Version: 1.24.0 - 6a6e02cef0f2122ee1469765b704faf5d0e0d859
- OS Version: Ubuntu 18.04 - x64
- Keyboard: US-Intl with dead keys.

Steps to Reproduce:

1. Press the key ' followed by the letter c. 
2. If the letter ç is shown then it is correct, otherwise it is wrong.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gusbemacbe** [comment]
Did you try <kbd>Alt</kbd> + <kbd>+</kbd> + <kbd>C</kbd>?

**Comment by la-costa** [comment]
@gusbemacbe  <kbd>Alt</kbd>+<kbd>C</kbd> does nothing, but <kbd>Alt-right</kbd>+<kbd>C</kbd> give ©.

**Comment by gusbemacbe** [comment]
You forgot of <kbd>+</kbd>.

I mean Alt + Plus + C:

![image](https://user-images.githubusercontent.com/2257024/41236866-89e6d766-6d68-11e8-8560-b8c906b96229.png)

**Comment by gusbemacbe** [comment]
@alexandrudima maybe it is not VSCode's problem, but Ubuntu US International keyboard's problem. A Romanian guy suggested to press AltGr + Plus + C to insert cedilla. Click to go #163 on the official issue of Ubuntu at Launchpad:

https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/518056/comments/163

**Comment by la-costa** [comment]
@gusbemacbe the <kbd>AltGR</kbd>+<kbd>+</kbd>+<kbd>C</kbd> also does not work. About the #163 I do not think that's the problem either. 
All my workspace is working properly, only happens in VS Code. And only after this last update. I tried doing a downgrade, but it also did not work.
What defines the keyboard layout for the VS Code?

**Comment by gusbemacbe** [comment]
Strange, Luciano, it always works for me on VSCode. I am a multilingual Brazilian and own a Russo-British Apple keyboard and I use the layout English UK Machinotsh International (without dead keys) and always use <kbd>AltGr</kbd> + <kbd>+</kbd> + <kbd>C</kbd> to insert cedilla on VSCode.

Try the layout US International without dead keys and test the same buttons I suggested.

**Comment by alexandrudima** [comment]
@la-costa It is possible that you have a keybinding bound to `ctrl+alt+=` that *steals* the keybinding from typing. You can press `ctrl+k ctrl+s` and searching for `ctrl+alt+` and take a screenshot of that list / unbind `ctrl+alt+` keybindings.

**Comment by gusbemacbe** [comment]
Wait, are you speaking of <kbd>Ctrl</kbd> or <kbd>C</kbd>?

**Comment by la-costa** [comment]
@gusbemacbe i am speaking of <kbd>C</kbd>. I am Brazilian, so cedilla (ç) is an important letter for me. Are you using Windows or Linux? Because i think the problem could be only in Linux. 

I tried the layout US International without dead keys and also did not work.

An important point is that all my applications work as expected, it's just the VS Code that does not. So I think it's interpreting the wrong layout of the environment. Is there any variable or parameter in the VS Code to set manually?

@alexandrudima I think this is not the cause, but I'm sending what you asked for.

![screenshot from 2018-06-12 08-55-20](https://user-images.githubusercontent.com/16106846/41288922-6612e878-6e1e-11e8-8da4-068d0a1089c2.png)

**Comment by gusbemacbe** [comment]
> @gusbemacbe i am speaking of C. I am Brazilian, so cedilla (ç) is an important letter for me. Are you using Windows or Linux? Because i think the problem could be only in Linux.

No, I also use the same version of Ubuntu that you are using. I assure you that <kbd>AltGr</kbd> + <kbd>+</kbd> + <kbd>C</kbd> works for me on VSCode Insiders on Ubuntu 18.04 64bits, using UK International (without dead keys) keyboard. Remember that on Linux, UK International, Apple UK International, Apple US International and US International keyboards are same in case of cedilla. 

According to the the UK and US International keyboards layouts on Linux:

<kbd>AltGr</kbd> + <kbd>'</kbd> or <kbd>'</kbd> + <kbd>C</kbd> are designed exclusively for Slavic languages, like Croatian, Czech, Polish and Serbian. Observe that <kbd>AltGr</kbd> + <kbd>'</kbd> or <kbd>'</kbd> + <kbd>any letter</kbd> also apply for the vocals and some consoants in some Slavic languages, like É, Í, Ó, Ú, Ń, Ź, etc. 

<kbd>AltGr</kbd> + <kbd>+</kbd> are designed for French (<kbd>C</kbd>), Portuguese (<kbd>C</kbd>), Romanian (<kbd>S</kbd> and <kbd>T</kbd>) and Turkish (<kbd>S</kbd>).

**Comment by la-costa** [comment]
@gusbemacbe ok, I get it, but it does not work.

This is my keyboard layout on the Ubuntu:

![screenshot from 2018-06-12 09-28-47](https://user-images.githubusercontent.com/16106846/41290486-68841b9a-6e23-11e8-9ca1-1d980ab608e0.png)
![screenshot from 2018-06-12 09-28-23](https://user-images.githubusercontent.com/16106846/41290490-68ab8392-6e23-11e8-84f3-787b79323127.png)

**Comment by gusbemacbe** [comment]
Observe the screenshot take from the article of US International on Wikipedia:

![image](https://user-images.githubusercontent.com/2257024/41290276-c3d1b1fc-6e22-11e8-84f0-053e12b4d762.png)

The <kbd>'</kbd> + <kbd>c</kbd> to insert cedilla works only on Windows. Not applicable on Linux (X11), so you have to <kbd>AltGr</kbd> + <kbd>+</kbd>  + <kbd>C</kbd>. 

Source: https://en.wikipedia.org/wiki/QWERTY#US-International

**Comment by gusbemacbe** [comment]
Ah, I am going to test your layout on my Ubuntu.

**Comment by la-costa** [comment]
@gusbemacbe This post has some information about the issue.

https://askubuntu.com/questions/363115/how-to-type-latin-small-letter-c-with-cedilla

After Ubuntu 16.04 the cedilla letter works fine, without need any configuration. The configuration looks ready for GTK and QT.

<kbd>AltRight</kbd>+<kbd>,</kbd> = "ç" also works.

It looks like the VS Code is no longer using the "IM_MODULE" setting.

**Comment by gusbemacbe** [comment]
Strange, on VSCode, I have just tested the US International with dead keys, pressing Alt + Comma and was able of inserting cedilla. Maybe were you confounding Alt + Quotation with Alt + Comma?

**Comment by la-costa** [comment]
@gusbemacbe No, i am not confounding, but it's so much detail that even I was in doubt :smile: 

I my Ubuntu, both works Quotation and Comma. In VS Code, only Comma. 

For me it seems something related to the configuration that VS Code uses.

**Comment by gusbemacbe** [comment]
Very good that you have solved. Maybe the Microsoft developers will reconsider `IM_MODULE` for making Quotation working on VSCode if a French or Brazilian wants to use an US International with dead keys keyboard. 

I prefer Apple UK/US International keyboard, building a ABC Extended for X11/Xorg to replace UK/US [Machintosh] International without dead keys on Linux, because it allows me to type in more than 30 pan-Latin languages, including Esperanto, IPA, Vietnamese, Yoruba and Brazilian Amerindian languages. They work perfectly on VSCode.

**Comment by la-costa** [comment]
In version 1.25.1 (or some update of my Ubuntu) the combination <kbd>'</kbd><kbd>c</kbd> worked again.
