### ISSUE TITLE
Not possible anymore to open user settings via `go to file`

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#51563]
Issue Type: <b>Bug</b>

1. Open user settings <kbd>Ctrl</kbd>+<kbd>,</kbd>
2. Go to file: type `settings.json`
3. Hit enter
4. File not opened as in previous vscode versions (it opened raw `settings.json` (current file))

VS Code version: Code - Insiders 1.25.0-insider (8f8ed32e737a7a906fac654fb0bd61b257b449b1, 2018-06-08T05:20:32.976Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
1. <kbd>Ctrl</kbd>+<kbd>P</kbd>
2. Type `settings.json`

**Comment by sandy081** [comment]
@usernamehw It works for me. 

Is it possible to provide a gif of how you are reproducing?

**Comment by usernamehw** [comment]
...

1. <kbd>Ctrl</kbd>+<kbd>,</kbd>
2. Right click on the tab `User Settings`
3. Reveal in explorer
4. Right click
5. Open with code insiders
6. It can't even open this file without default settings view

**Comment by sandy081** [comment]
> It can't even open this file without default settings view

@usernamehw This is intentional to open settings file in a split view always unless you disable the setting `workbench.settings.openDefaultSettings` to false. This will disable opening default settings completely.

**Comment by usernamehw** [comment]
It was working before. How is that a good change?

**Comment by sandy081** [comment]
@usernamehw It was changed long time before. It helps users to discover settings.

**Comment by usernamehw** [comment]
Yeah...
