### ISSUE TITLE
Trim trailing whitespace only in specific file types

### ISSUE THREAD

**Issue by VentyCZ** [Microsoft/vscode#51564]
If I enable removing trailing whitespace and the file I edit is a Markdown file (which requires trailing whitespace for newlines in certain cases) and save the file the required trailing whitespace is removed.

There could be a black/whitelist option for file types which should be ignored (or only enabled for) by the aforementioned function (this option might be ignored while using the command directly).

I have to pay attention to what file type I'm editing and it's frustrating.

**Comment by yume-chan** [comment]
You can add settings for specified file types like this:

```` json
"files.trimTrailingWhitespace": true,
"[markdown]": {
    "files.trimTrailingWhitespace": false
}
````

Some settings doesn't support targeting file types yes, but fortunately `files.trimTrailingWhitespace` does support.

**Comment by VentyCZ** [comment]
@yume-chan Thanks for the info! Just tried it and it works! Closing the issue now.
