### ISSUE TITLE
Remove unnecessary start menu folder for Visual Studio Code for Windows

### ISSUE THREAD

**Issue by sirredbeard** [Microsoft/vscode#51562]
When the VS Code installer installs Start Menu icons on Windows 10 it creates a folder at:

C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio Code

And places a shortcut, Visual Studio Code.lnk, therein.

![vscode](https://user-images.githubusercontent.com/33820650/41205833-a311d45c-6cc8-11e8-9a5a-676e2ca19fd1.PNG)

The creation of this folder is unnecessary.

There is only one icon being installed.

It is the creation of an unnecessary extra step.

![before](https://user-images.githubusercontent.com/33820650/41205862-07acd600-6cc9-11e8-82e5-7254f9775512.png)

The installer should place Visual Studio Code.lnk directly in C:\ProgramData\Microsoft\Windows\Start Menu\Programs\.

It would be much cleaner and more immediately visible and accessible in the Start Menu.

![after](https://user-images.githubusercontent.com/33820650/41205871-4a4d8bbc-6cc9-11e8-925c-1029cabbc9fd.png)

**Comment by yello-w** [comment]
Hey, there! I'm new and would like to contribute to this. I have already cloned the repository and was able to build and run the project locally. Could someone please advise on how to find what needs to be changed?

**Comment by sirredbeard** [comment]
I am new to Code too. 
I think a place to look would be installer configuration.
Code on Windows appears to use a pretty typical Windows 10 installer wrapper.
I am not sure if it is a Windows built-in installer, WISE Installer, or another though. I know it's not Nullsoft.
Most of these installers have some sort of installer configuration script that moves everything into place.
Similar to Homebrew scripts on macOS or snaps on Ubuntu.
It is possible that needs to be tweaked.
There is also a very real possibility that this has all been incorporated to be handled automatically but that may be one place to look.

**Comment by sirredbeard** [comment]
Is there any discussion on this that should be had before crafting a pull request?

**Comment by yume-chan** [comment]
@yello-w Code uses [Inno Setup](https://en.wikipedia.org/wiki/Inno_Setup) for installing, here are the related lines:

https://github.com/Microsoft/vscode/blob/14651bd65287800980aaa210faf77f71afa28ef1/build/win32/code.iss#L74-L77

I suspect you are just required to remove the `{#NameLong}` part from `{group}\{#NameLong}`, but I can't build the installer (and I don't know why) so I can't test it.

**Comment by joaomoreno** [comment]
You should be able to build the OSS installer with

```
yarn gulp vscode-win32-x64-setup
```

**Comment by EbXpJ6bp** [comment]
http://www.jrsoftware.org/ishelp/index.php?topic=consts
>{userstartmenu} & {commonstartmenu} *
The path to the top level of the Start Menu.

**Comment by EbXpJ6bp** [comment]
I couldn't build when removed the {#NameLong}.

```
Error on line 75 in D:\Git\vscode\build\win32\code.iss: Parameter "Name" must include a path for the icon, for example, "{group}\My Icon"
Compile aborted.

**Comment by EbXpJ6bp** [comment]
`Name: "{commonstartmenu}\Programs\{#NameLong}"; Filename: "{app}\{#ExeBasename}.exe"; AppUserModelID: "{#AppUserId}"` works as expected

**Comment by Chiramisu** [comment]
Is there even agreement that this is the desirable action? It's really more of a philosophical debate, but I have both the released and Insiders versions installed and actually like them being in a folder.

![code insiders](https://user-images.githubusercontent.com/944951/41945237-f0afa5aa-7960-11e8-868a-12c0ac6f9cf8.png)

Furthermore, it can almost be considered a moot issue since the design intent behind the Start Menu in Windows 10 is for pinning tiles and searchability. I have both mine pinned, so I never actually look at the scrolling menu. Even if they weren't pinned, you just start typing with the Start Menu active and Cortana / Windows Search will find it instantly. ;)

**Comment by flaw600** [comment]
@Chiramisu I don't agree that the design intent for the Start Menu is to pin things, and even if it is, it's a pain to go into a folder to pin in to the Menu. Moreover, this is inconsistent behavior when compared against Mac, where each version of Code (Insiders vs Stable) is its own entity.

As for agreement, it *is* considered a bug, so I think that settles that issue right there. Is anyone working on this?

Can we have someone who's actually working on this be the asignee?

**Comment by sirredbeard** [comment]
I think you raise some good points, @Chiramisu. I clearly have my preference but I had hoped to see some more discussion on this, thank you.

**Comment by joaomoreno** [comment]
Unfortunately, I'm siding more with @Chiramisu on this. I would also add that the start menu is searchable, which makes finding Code a very fast task. I prefer avoiding the mess of changing this for all existing users and just go with the current option. Sorry @sirredbeard and others.
