### ISSUE TITLE
Load new data from opened file from disk

### ISSUE THREAD

**Issue by MJBrune** [Microsoft/vscode#51566]
Issue Type: <b>Bug</b>

step one) open any file in visual studio and make changes to it.
step two) make difference changes on disk.
step three) notice that double clicking in the file tree will not open those new changes in a file.

Desired results: The file should open, maybe in a new tab than the changed data and maybe the editor can display the difference? such as in my case I have a save.json file of game data. So I format the json to prettify it and once I have new save data I'd rather just re-prettify. Opening that same content in a new tab such as marked save.json-modificationdate and renaming the old tab to it's last modification date or just .old would be preferred. Currently there isn't a way without losing data.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.18.0
json-tools|eri|1.0.2
vscode-clang|mit|0.2.2
python|ms-|2018.5.0
cpptools|ms-|0.17.4
Go|ms-|0.6.82

</details>

**Comment by bpasero** [comment]
I do not think that behaviour makes sense for an editor.

**Comment by MJBrune** [comment]
Alright well sublime text editor has this feature if anyone is looking for another editor that has this feature.
