### ISSUE TITLE
commit in the shell, the git status bar didn't update

### ISSUE THREAD

**Issue by cc2victoria** [Microsoft/vscode#51568]
Issue Type: <b>Bug</b>

when I commit my code by shell, the git status bar did't update. It still shows the status before I committed.
![bug](https://user-images.githubusercontent.com/15710358/41211147-186771ae-6d68-11e8-89a8-2ee0cfed9948.png)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.00GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
app-migrator|deb|0.0.3
vscode-npm-script|eg2|0.3.4
we-app-vscode|eme|0.8.0
beautify|Hoo|1.3.1
vscode-language-pack-zh-hans|MS-|1.23.5
debugger-for-chrome|msj|4.6.0
vetur|oct|0.12.4
postcss|ric|2.0.0
templex|sle|0.1.1
markdown-pdf|yza|1.2.0

</details>

**Comment by cc2victoria** [comment]
No, those are different bugs.
I commit my code and push it by the shell. But the git bar still shows the status before.
I test just now, when I run `git checkout`. It also shows the status before.

**Comment by joaomoreno** [comment]
If you show the Explorer view in Code, and then make a change in that folder using the Windows Explorer (eg delete a file), does Code reflect that change?

**Comment by cc2victoria** [comment]
Yes

**Comment by joaomoreno** [comment]
@sandy081 More badge issues.

**Comment by sandy081** [comment]
@joaomoreno  Is it a old issue? I see that this is reported on VS Code 1.23

**Comment by joaomoreno** [comment]
> when I commit my code by shell, the git status bar did't update. It still shows the status before I committed.

@cc2victoria Does the badge eventually recover?
