### ISSUE TITLE
Autocomplete occurring on certain symbols like ( and .

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#51571]
- VSCode Version: 1.24.0
- OS Version: macOS 10.13.4

Reproduction:
1. Start typing something that pops up suggestions
2. Type a `(`

Does this issue occur when all extensions are disabled?: Yes

![screencap](https://user-images.githubusercontent.com/12532733/41212907-154fb2d0-6d07-11e8-8a85-74034e9d4da4.gif)

**Comment by mjbvz** [comment]
This is by design. Either escape out of the suggestions or set `"editor.acceptSuggestionOnCommitCharacter": false` to disable accept on `(`

**Comment by zo** [comment]
I think this option should be disabled by default.
It can be annoying in some cases like in the above exemple.
