### ISSUE TITLE
Marketplace is getting over loaded with language pack queries when user language is english

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#51577]
Marketplace is getting over loaded with language pack queries when user language is `en-*` (en-us, en-gb ...)

When user language is english (en or en-*) do not query for language packs as VS Code default language is english.

@ramya-rao-a FYI

**Comment by sandy081** [comment]
@dbaeumer Currently our core languages are `en` and `en-us`. But, I am skipping all `en` and `en-*` language packs from being recommended as it is unnecessary.

Underlying issue here is that, Marketplace is getting overloaded with the queries.

**Comment by dbaeumer** [comment]
@sandy081 I see. Makes sense to me.

**Comment by sandy081** [comment]
@ramya-rao-a Is it possible to verify this fix?

**Comment by ramya-rao-a** [comment]
Verified.
