### ISSUE TITLE
"type": "node"  - The debug type is not recognized.

### ISSUE THREAD

**Issue by zenVentzi** [Microsoft/vscode#51572]
> The debug type is not recognized. Make sure you've got a corresponding debug extension installed and that it is enabled.

vscode v. 1.23.1
node v. 7.9.0
windows 10

Node Debug build in extension is enabled. Restarted vscode multiple times to no avail. It used to work just up until yesterday, not sure what much has changed to cause that "not recognized" warning.  Also, it doesn't appear when clicking the Add Configuration... button.

**Comment by weinand** [comment]
@zenVentzi how does your debug configuration (launch.json) look like?
Does this problem occur if you disable all extensions?

**Comment by erihanse** [comment]
Same problem here. The Node Debug extension seems to be broken.

**Comment by weinand** [comment]
@erihanse please provide reproducible steps.
how does your debug configuration (launch.json) look like?
Does this problem occur if you disable all extensions?

**Comment by erihanse** [comment]
I was following these steps: https://code.visualstudio.com/docs/nodejs/nodejs-tutorial

When I came to the point where I was starting to debug (Debugging Hello World), a launch.json was created with following content:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
I wasn't prompted for what environment to use for debugging (like python, java or Node.js). 
When trying to paste the configuration,
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
    ]
}
```
a green squiggly line is underneath "node", saying
"The debug type is not recognized. Make sure that you have a corresponding debug extension installed and that it is enabled."

**Comment by erihanse** [comment]
Also, the extension says "Reload" no matter how many times I try to press reload.
![image](https://user-images.githubusercontent.com/9251274/41259737-fb233da4-6dd4-11e8-9400-21d5c40db185.png)

**Comment by weinand** [comment]
@erihanse It would be helpful if you could add a screenshot showing the VS Code window with  the error squiggly in the debug configuration. Thanks!

**Comment by erihanse** [comment]
Here you go :) 
![image](https://user-images.githubusercontent.com/9251274/41259916-a1c300d6-6dd5-11e8-85ac-60c67b3f38c4.png)

**Comment by weinand** [comment]
Hmm, this really looks like a missing node-debug extension.

What extensions do you have installed?
Just open the extension viewlet and select "Show installed extensions" from the menu.

Paste the result here, like this:
![2018-06-12_00-19-25](https://user-images.githubusercontent.com/1898161/41260128-83bcc120-6dd6-11e8-89a6-6953acb2d486.png)

**Comment by erihanse** [comment]
There are quite many, they don't all fit on the same screen. Will this output do? 
```
Extension | Author (truncated) | Version
-- | -- | --
vscode-python-docstring | aza | 0.0.5
altervista-thesaurus | bru | 0.1.0
vscode-eslint | dba | 1.4.12
xml | Dot | 2.2.0
es7-react-js-snippets | dsz | 1.8.1
gitlens | eam | 8.3.5
prettier-vscode | esb | 1.5.0
gc-excelviewer | Gra | 2.0.21
word-count | hyp | 0.1.1
latex-workshop | Jam | 5.5.1
docthis | joe | 0.7.1
node-module-intellisense | lei | 1.5.0
mssql | ms- | 1.3.1
python | ms- | 2018.5.0
csharp | ms- | 1.15.2
Go | ms- | 0.6.82
node-debug2 | ms- | 1.18.4
wordcount | ms- | 0.1.0
debugger-for-chrome | msj | 4.6.0
vscode-docker | Pet | 0.0.27
java | red | 0.26.0
surrounding | sif | 1.4.0
vscode-hexdump | sle | 1.6.0
code-spell-checker | str | 1.6.10
python | tht | 0.2.3
vscode-java-debug | vsc | 0.9.0
vscode-java-pack | vsc | 0.3.0
vscode-java-test | vsc | 0.6.1
vscode-maven | vsc | 0.9.0
vim | vsc | 0.12.0
vscode-todo-highlight | way | 0.5.12
```

**Comment by weinand** [comment]
The "node-debug2" looks outdated: 1.18.4 instead of 1.23.x.
"node-debug2" is built-into VS Code and there should be no way to install it.
Where did you get it from?

Try to remove it from VS Code.

If the problem persist, try to disable all extensions.
You can use the "Disable all Installed Extensions" for this.

**Comment by erihanse** [comment]
Yeah, well it says "reload" on the extension. 
![image](https://user-images.githubusercontent.com/9251274/41260586-52e5a290-6dd8-11e8-8d58-e260f96131b9.png)

Do I have to reinstall vs code to fix this?

**Comment by weinand** [comment]
Before reinstalling try to remove the bogus node-debug2 extension from your extension folder.
- shut down VS Code
- there should be a "ms-vscode.node-debug-1.18.4" in ".vscode/extensions" in your user directory. Remove "ms-vscode.node-debug-1.18.4".
- launch VS Code and try again

**Comment by erihanse** [comment]
Okay, now the version got bumped atleast, but the same error is there.
![image](https://user-images.githubusercontent.com/9251274/41261820-cb53af06-6ddd-11e8-8dab-a64cc5d3dedb.png)

I see there is a CI build job which is failing for Windows, can that be the case? That's what I initially meant by the extension was "broke".

**Comment by weinand** [comment]
@erihanse the two last screenshots show the extensions available on the Marketplace, not what you have loaded on your system or inside VS Code. So the version numbers you are seeing are out of your control.

If you want to see what is built-into VS Code or what you have installed on top of it, please use the queries from the extension menu:

![2018-06-12_01-29-51](https://user-images.githubusercontent.com/1898161/41262266-22d6ff2e-6de0-11e8-8f4a-23929d2a9a78.png)

**Comment by weinand** [comment]
BTW, what version of VS Code are you using?
I assume 1.23.1, since that's the version this bug was filed against.

**Comment by erihanse** [comment]
Oh okay, think my memory got mixed up. I'm running 1.24.0 as of today. Haven't really done any development with the extension for half a year, so all I can say is that it worked then.

**Comment by erihanse** [comment]
I tried uninstalling and installing again, to no avail.

**Comment by weinand** [comment]
Oh, that explains it.
"Node Debug (legacy)" is important because it delegates to "Node Debug" for Node.js versions >= 8.0.
Without "Node Debug (legacy)" node debugging is basically disabled.

**Comment by brokenthorn** [comment]
How is this closed. I'm still experiencing the same symptoms with newer VSCode. Node Debug (legacy) is disabled from factory. If it's integral to the node debugging facilities in VSCode, why disable it from the factory?

**Comment by weinand** [comment]
@brokenthorn No, "Node Debug (legacy)" is not disabled from factory.
If it is disabled for you, then it was disabled by accident.
