### ISSUE TITLE
Interactive Playground Refactoring via Extraction does not work

### ISSUE THREAD

**Issue by TclasenITVT** [microsoft/vscode#51575]
- Version 1.24.0
- Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
- Datum 2018-06-06T17:35:40.560Z
- Shell 1.7.12
- Renderer 58.0.3029.110
- Node 7.9.0
- Architektur x64
- OS Version: Microsoft Windows 10 Enterprise 10.0.15063

Steps to Reproduce:

1. Open Interactive Playground
2. Scroll down to the Refactoring via Extraction example (All Examples before this one worked)
3. Select rows 3 to 5
4. Press CRTL+. shows "no codeactions available"(translated from german text: 'keine Codeaktionen verfügbar')
5. Press right mouse button select refactorings -> no refactorings available 

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
This might be a limitation of what the TypeScript service offers for extraction.

**Comment by TclasenITVT** [comment]
Then you should change the example code to work around the limitation or just throw this example out of the interactive playground? I just used the extraction feature with js yesterday. Extracting into a global function, that worked fine.

**Comment by AtreidesModi** [comment]
Same issue here on OS X 1.28.1 with all extensions disabled.  The Interactive Playground example states:

Refactoring via Extraction
Sometimes you want to refactor already written code into a separate function or constant to reuse it later. Select the lines you want to refactor out and press ⌘. or click the little light bulb and choose one of the respective Extract to... options. Try it by selecting the code inside the if-clause on line 3 or any other common code you want to refactor out.

Selecting typeof el === 'number' && el % 2 === 0 indeed presents the "lightbulb" and ⌘. brings context menu to Extract to inner function, global space or constant.  None of the 3 options produce a result.

**Comment by jsejcksn** [comment]
This is quite important for onboarding, yes?

I'm here because I experienced the same behavior described in #55101. My output:

```
[renderer1] [error] Error: Failed to create file walkThroughSnippet:/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/parts/welcome/walkThrough/electron-browser/editor/vs_code_editor_walkthrough.md#4.js
    at new t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1474:150)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3446:577
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by kdkd** [comment]
This is still occurring in 1.32.3 on MacOS, but the error has slightly changed:

```
ERR m: Failed to create file walkThroughSnippet:/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/walkThrough/electron-browser/editor/vs_code_editor_walkthrough.md#4.js
    at t.scheme.l.Schemas.file._withProvider.then.then.then.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3300:573)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by themotu** [comment]
Occurs in latest insiders version also

**Comment by mjbvz** [comment]
I'm just going to remove this section from the interactive playground. Our normal documentation covers refactoring in much more detail. I don't think fixing the interactive playground for this case would be simple and we should not highlight a feature that doesn't work properly
