### ISSUE TITLE
global settings

### ISSUE THREAD

**Issue by SmuSmu** [Microsoft/vscode#51573]
Hi,

I like to force some settings. So some should be a must and some should be some presetted options that user can change afterwards.

For example I like to disable update check for all local users because we deploy updates with other tools.

**Comment by joaomoreno** [comment]
`"update.channel": "none"`

**Comment by SmuSmu** [comment]
Sorry but you did not understand my request.

I like to force the setting globally. In the moment every user can set everything. But I like to fix some settings so that all developers have the same settings.
