### ISSUE TITLE
Duplicate file option on right-click in explorer

### ISSUE THREAD

**Issue by Splike** [Microsoft/vscode#51574]
When right-clicking a file in the Explorer, I'd very much like a "Duplicate" option, which will duplicate the selected file.

Yes, there is a duplicate issue, but I'd still like to re-open the request.
Right-clicking a file an clicking "copy" is easy. But actually finding a place in the explorer (when there are a lot of files), and being able to "paste" is not very easy.

**Comment by isidorn** [comment]
Also can be done via extension
