### ISSUE TITLE
Open --diff file in the context of the folder the editable file is in

### ISSUE THREAD

**Issue by MarekLew** [microsoft/vscode#51580]
Issue Type: <b>Bug</b>

When I open `code --diff B/a.txt A/a.txt` then is opened in first file context(`B/a.txt`), but _editable(and intelisense)_ is second file(**`A/a.txt`**). This is **wrong file context** (PS. and I don't change this because '-r' not anymore open this in last active editor) because **file `A/a.txt` not exist in `B` folder**.

### Example:
If I have files "A/a.txt" and "B/a.txt"

1. `code B` 
2. `code A` 
3. `code --diff B/a.txt A/a.txt` or `code -r --diff B/a.txt A/a.txt`
Open diff in **B** but **not in A**

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.68GB (2.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bpasero** [comment]
@MarekLew you want both sides to be editable?

**Comment by MarekLew** [comment]
No. Open diff in A folder. Where left file exist and is editable(correct context ).

**Comment by MarekLew** [comment]
https://github.com/MarekLew/vscode/commit/50082096398cdf755f58f6b9f547391e950ce8e9
