### ISSUE TITLE
Log file as requested after upgrade failuer

### ISSUE THREAD

**Issue by phildhall** [Microsoft/vscode#51583]
- VSCode Version: Don't know it's disappeared !!
- OS Version: Win 10 Pro v 10.0.17134

Steps to Reproduce:

1. Can't.

Does this issue occur when all extensions are disabled?: Yes/No
1. Can't, having to reinstall from scratch ... f***s sake ... (facepalm)

As requested in the error window.
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2089105/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
