### ISSUE TITLE
html commenting not working

### ISSUE THREAD

**Issue by DavidNjoroge** [Microsoft/vscode#51584]
Issue Type: <b>Bug</b>

am working on angular 
on a html page when you use the shortcut ctr+/ to comment
it shows this format and its not working for me
 {% comment %} </div> {% endcomment %}

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 1557)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|7.69GB (1.14GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
gc-excelviewer|Gra|2.0.21
Angular-BeastCode|Mik|6.0.15
vscode-extension-auto-import|Nuc|1.4.1
vscode-docker|Pet|0.0.27
ionic2|Tha|3.0.2
unity-tools|Tob|1.0.4
unity-debug|Uni|1.3.0
unity-snippets|Ycl|0.1.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
simple-react-snippets|bur|1.1.1
vscode-eslint|dba|1.4.12
jquerysnippets|don|0.0.1
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
tslint|eg2|1.0.30
javac-linter|fau|1.3.1
Angular1|joh|0.2.0
node-module-intellisense|lei|1.5.0
angular1-code-snippets-johnpapastyle|lpe|0.1.0
MagicPython|mag|1.0.12
python|ms-|2018.5.0
csharp|ms-|1.15.2
java|red|0.26.0
js-jsx-snippets|sky|0.0.9
autoimport|ste|1.5.3
vscode-snippets|the|0.1.3
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
vscode-spring-initializr|vsc|0.3.0
full-react-snippets|wal|1.1.2
jinja|who|0.0.8

</details>

**Comment by aeschli** [comment]
@DavidNjoroge Can you add a small code snippet that shows the problem. Please also run without extensions.

**Comment by DavidNjoroge** [comment]
I restarted my pc and the error was gone sorry for the inconvenience

**Comment by DavidNjoroge** [comment]
the error is still persistant, i tried to remove most extensions but i cant comment or uncomment html

**Comment by aeschli** [comment]
@DavidNjoroge Can you add a small code snippet that shows the problem?

**Comment by DavidNjoroge** [comment]
deleted all the extensions since they werent even being uninstalled and it fixed the commenting issue
