### ISSUE TITLE
Outline view removes object context from function names in Javascript

### ISSUE THREAD

**Issue by MelleB** [Microsoft/vscode#51589]
Issue Type: <b>Bug</b>

. Create a javascript file with the following contents:
```
const MyObject = {};
const MyObject.MySubObject = {};
MyObject.MySubObject.myFunction = function(args) {}
```
2. Look at the outline, it shows `myFunction`. In the previous version it showed `MyObject.MySubObject.myFunction`. I am missing this context information, especially in larger script files where  function names might contain duplicates.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.15.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2525)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (7.71GB free)|
|Process Argv|/usr/share/code/code --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by jrieken** [comment]
> In the previous version it showed MyObject.MySubObject.myFunction.

Do you mean in the quick outline? Can you attach a screen shot of that?
