### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#51597]
Steps:
* macOS
* open quick open
* type a "/"
* continue typing some characters
* eventually you get this:

![image](https://user-images.githubusercontent.com/900690/41225040-33c99ea8-6d6e-11e8-90ec-a168e0db97ac.png)

@roblourens @chrmarti could this possibly come from the feature were we try to stat the path if it is absolute? Because I had to fix https://github.com/Microsoft/vscode/issues/42726 I lifted this check into the `openFileHandler`, so I would not need this kind of functionality anymore in the search service. I think we should probably remove it from there as it imho only makes sense in the context of quick open?

**Comment by roblourens** [comment]
I think this is from the `process.on('exit'` handlers in fileSearch.ts, new ones are added before the previous ones are removed when typing quickly, but it all balances out in the end. I can't get it to repro in 1.24 so I'll see what's changed.

It would be good to remove that from the search service if we can.

**Comment by chrmarti** [comment]
I added this listener to make sure ripgrep is killed when the search process goes down after reports of hanging `rg` processes. Quick typing in QuickOpen should end up in the cache, where do you see ripgrep spawned by each keystroke?

**Comment by bpasero** [comment]
@chrmarti https://github.com/Microsoft/vscode/issues/51597#issue-331121125

**Comment by roblourens** [comment]
If you type with / first, then it skips the cache, because it has to check the filesystem for every keypress. If that file doesn't exist then it runs rg.

**Comment by bpasero** [comment]
I would just remove that feature from search.

**Comment by chrmarti** [comment]
Doing it all on the search side would be more efficient than doing part of it in the `openFileHandler` handler because you then call the extension host only once.

Maybe the check for an absolute file could be moved before the cache, so the cache can then be used if there was not hit.

**Comment by bpasero** [comment]
@chrmarti maybe more efficient, but does it make sense that the search service behaves like that? I think its contract is to search in the scope of the workspace and all opened files but not for the file path if it happens to be a file on disk and it is passed into the service. Besides, what does it mean for remote scenarios that a user puts in a remote file path, would we then also ask each remote file provider if the file exists?

**Comment by roblourens** [comment]
I agree that this makes more sense to handle outside of the search service. Opened a PR.
