### ISSUE TITLE
Document is not centered in Centered layout and Zen mode after resizing

### ISSUE THREAD

**Issue by alexdevero** [Microsoft/vscode#51591]
Issue Type: <b>Bug</b>

Openned document is not centered in centered and zen mode after resizing it, changing its width. The gaps on sides are not changed evenly, only one sides either grows or shrinks.

1) Open some document.
2) Toggle Zen or Centered mode
3) Rezize the width of the document.

Expected:
When resizing the document, changing its width, the gaps will shrink/grow evenly - the document will remain in the center of the screen.

Zen mode:
![vscode-centered-layout-issue-zen-layout](https://user-images.githubusercontent.com/4237724/41221689-1e214e06-6d65-11e8-9223-fa8eb622a1b3.gif)

Centered layout:
![vscode-centered-layout-issue-centered-layout](https://user-images.githubusercontent.com/4237724/41221701-25834636-6d65-11e8-906e-6d3b1b03ca72.gif)

VS Code version: Code - Insiders 1.25.0-insider (28d5806f24f99c2c6ad633e4e08ed5ea00169c83, 2018-06-11T05:17:42.700Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.20GB free)|
|Process Argv|E:\Programs\Documents\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
language-postcss|cpy|1.0.5
vscode-svgviewer|css|1.4.4
EditorConfig|Edi|0.12.4
vsc-material-theme|Equ|2.1.0
auto-close-tag|for|0.5.6
wordcounter|kir|1.2.2
contextualduplicate|laf|0.2.0
vscode-language-babel|mgm|0.0.14
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.2.2
vscode-duplicate|mrm|1.2.1
vscode-icons|rob|7.23.0
code-settings-sync|Sha|2.9.2
code-spell-checker|str|1.6.10
code-spell-checker-czech|str|0.1.0
dictionary-completion|yzh|0.6.1
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/50936
