### ISSUE TITLE
[loc][Query][VSCode] Please clarify whether this should be locked "{0}, git branch"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#5159]
Hi, we have a query about a string in the English text. Can you please help?

Source:
{0}, git branch

File Name:
src\vs\workbench\parts\git\browser\gitQuickOpen.nls.resx

Resource ID:
".resx", 0; "branchAriaLabel"

Query:
This seems to be a git command. Should it have been locked? Thanks!

**Comment by joaomoreno** [comment]
@bpasero check this, it is aria

**Comment by bpasero** [comment]
@mkyjakova for example "master, git branch". the first part is the branch name and the second just an explanation for screen readers.

**Comment by mkyjakova** [comment]
Thanks! So if I understand correctly, it should not be locked. Correct?

**Comment by bpasero** [comment]
Locked?

**Comment by bpasero** [comment]
Ping me on Lync please if you need further help :)

**Comment by mkyjakova** [comment]
Thanks for asking! Git commands have to be locked by the core team in order to remain in English. If they are not locked, our translators translate them as regular words. 
So my question here is whether this is a git command (because it looks like one) or not. If it is, it should be locked so that it is not translated. Hopefully, this makes more sense, if not please let me know. Thanks!

**Comment by bpasero** [comment]
I think it would be good to keep "Git" untranslated.

**Comment by joaomoreno** [comment]
No, it is not a git command. It is used for screen reading: it informs the user that `{0}` is a branch coming from a git repository.

**Comment by mkyjakova** [comment]
Great. Thanks both :)
