### ISSUE TITLE
notification icons missing after latest update

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#51595]
Issue Type: <b>Bug</b>

I just edited and saved a couple of files and then spotted the little blue change count notifications on VC icon are missing.

Was fine before I updated yesterday

![image](https://user-images.githubusercontent.com/618922/41224535-a3486eee-6d64-11e8-83bd-04b129942c18.png)

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
git-extension-pack|don|0.1.3
githistory|don|0.4.1
gitlens|eam|8.3.5
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
search-node-modules|jas|1.3.0
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.6.0
vscode-versionlens|pfl|0.21.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.6.0
html-css-class-completion|Zig|1.17.1
vscode-open-in-github|ziy|1.3.1

(2 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Duplicate of #51396

**Comment by sandy081** [comment]
@SteveALee Did you try to change the position of the SCM icon on the left (activity bar) like in issue #51396 ?

**Comment by SteveALee** [comment]
What a nice friendly bot! :)

@sandy081 I assume that means drag it down in the icon order? Who knew you could do that? :) Sadly that makes no difference for me.

![image](https://user-images.githubusercontent.com/618922/41345445-8eafdc5e-6efb-11e8-8f91-8305d169dd0a.png)

**Comment by sandy081** [comment]
@joaomoreno Moving this to you as it looks unrelated to the bug I fixed.

**Comment by joaomoreno** [comment]
@SteveALee Did you change the `git.countBadge` setting?

**Comment by SteveALee** [comment]
@joaomoreno Nope. And I can't see it any reference in settings file.

The project is free of any git or code config files - https://github.com/straight-street/mulberry-symbols

Is there an easy way to temporarily disable all extensions? Gitlens is active.

**Comment by joaomoreno** [comment]
Yeah, use `--disable-extensions`. Does it still reproduce like that too? Does the issue happen often, or was it just that one time? Can you reproduce with any other project?

**Comment by SteveALee** [comment]
Full marks for the obvious switch! :) I missed that had arrived after I made a request.

> Does it still reproduce like that too? 

Sadly

> Does the issue happen often, or was it just that one time? Can you reproduce with any other project?

Always happens, any project. :(

I do have latest Git4Windows installed as well as I use it's bash for my CLI

**Comment by SteveALee** [comment]
OK some more info after I updated to 12.4.1

* Other project work fine. This one still fails
* t
The blue clock overlay icon appears and then vanishes
* This project is a slightly unusual structure and the `EN` folder contains > 3K files

**Comment by joaomoreno** [comment]
All other projects work fine, but this fails...

Can you show me a quick video recording of you staging some files, committing others...?

**Comment by SteveALee** [comment]
Sure, https://www.youtube.com/watch?v=HRzPTH5O6F0

**Comment by joaomoreno** [comment]
@SteveALee It says that the video is unavailable.

**Comment by SteveALee** [comment]
It's definitely there!
I wonder if only some regions? I'm UK - will check

**Comment by SteveALee** [comment]
This one came from right clicking on the video https://youtu.be/HRzPTH5O6F0

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/41590834-49a9d79c-73b8-11e8-8a64-512b527500c8.png)

😢

**Comment by SteveALee** [comment]
This crazy! What is up with YouTube! (:
`
http://opendirective.net/GPII/VSCode51595.zip

**Comment by joaomoreno** [comment]
Yup, that was a great video! Unfortunately, I have no clue why this might be happening...

Can you try running with a new user data dir and see whether it still reproduces on that folder? Try `code --user-data-dir DIRNAME`.

It's very interesting how this only happens for one specific project...

**Comment by SteveALee** [comment]
OK it's fixed somehow.

I tried `--user-data-dir DIRNAME .` and it worked then tried without and it still worked!
I've not knowingly changed anything in the project or global code or git config.

Just have to put it down to one of those things.

thanks for your help

**Comment by joaomoreno** [comment]
So odd. Let me know if it comes back!
