### ISSUE TITLE
Peek definition finding 2 definitions when there is only 1

### ISSUE THREAD

**Issue by frednomoon** [Microsoft/vscode#51599]
Having a very annoying problem in the most recent update (Update 1.23.1) that seems similar to one that other people have been reporting.

The most common example is this, where vscode is getting confused between a React Component, and the cached typescript definition of a React Component (in my root directory)

[https://imgur.com/a/ZwOSOOi](url)

However I have also seen a stranger problem (see screenshot below), where vscode is detecting 2 separate definitions in the same line of code:

[https://imgur.com/a/pPCLIZu](url)

Have downgraded to April release to fix this for now!

**Comment by aeschli** [comment]
dupicate of #51489
