### ISSUE TITLE
Test timeout: Test Preferences turns off editor line numbers and verifies the live change

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#51592]
https://vscode.visualstudio.com/VSCode/_build?buildId=1782

   1) Test Preferences turns off editor line numbers and verifies the live change:
      Error: Timeout: get elements '.line-numbers' after 20 seconds.
       at D:\a\1\s\test\smoke\out\vscode\code.js:142:23
       at Generator.next (<anonymous>)
       at fulfilled (D:\a\1\s\test\smoke\out\vscode\code.js:8:58)
       at <anonymous>
 
   2) Test Preferences changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it:
      Error: Timeout: get element '.part.activitybar.right' after 20 seconds.
       at D:\a\1\s\test\smoke\out\vscode\code.js:142:23
       at Generator.next (<anonymous>)
       at fulfilled (D:\a\1\s\test\smoke\out\vscode\code.js:8:58)
       at <anonymous>

**Comment by joaomoreno** [comment]
cc @sandy081 #48261
