### ISSUE TITLE
Color picker shows wrong values

### ISSUE THREAD

**Issue by monastyrskiiden** [Microsoft/vscode#51596]
Color picker doesn't convert HEX values with opacity to RGBA format.

- **VSCode Version:** 1.24.0
- **OS Version:** Windows 10 Pro x64

**Steps to Reproduce:**

1. Here's a video with problem
https://drive.google.com/file/d/11UbtsKENiWkbKCOjcu9GE_KZro1ZcyUy/view

**Extensions:**

- auto-close-tag v0.5.6
-   auto-rename-tag v0.0.15
-   autofilename v0.1.3
-   bracket-pair-colorizer v1.0.58
-   code-settings-sync v2.9.2
-   color-highlight v2.3.0
-   githistory v0.4.1
-   JavaScriptSnippets v1.6.0
-   LiveServer v4.1.0
-   material-palenight-theme v1.8.0
-   monokai-alt v1.0.0
-   prettier-vscode v1.5.0
-   sublime-keybindings v4.0.0
-   theme-monokai-dark-soda v0.0.5
-   Theme-Monokai-Easylight v1.0.0
-   vscode-great-icons v2.1.33
-   vscode-language-pack-ru v1.24.3
-   vscode-theme-onedark v2.1.0

Does this issue occur when all extensions are disabled?: **Yes**

**User Settings:**
[user_settings.txt](https://github.com/Microsoft/vscode/files/2089465/user_settings.txt)

**Comment by aeschli** [comment]
Can you clarify what you mean by 'showing the wrong colors' ?

All looks ok to me:
- the 8-digit hex format is introduced by CSS4 https://drafts.csswg.org/css-color/#hex-notation
- when dragging the color slider, you need to release the mouse button to apply the new color.
- to switch to `rgba(..)` format, click on the header of the color picker

**Comment by monastyrskiiden** [comment]
Oh, didn't know that, sorry my fault. The problem is solved. Thx!
