### ISSUE TITLE
[Help] Multiple TextEdits[] not working

### ISSUE THREAD

**Issue by saviorisdead** [Microsoft/vscode#516]
If method `provideDocumentFormattingEdits` actually returns multiple TextEdits silently nothing happens. Is it a bug? Or I doing something wrong? Is there a documentation about how changes of TextEdits applied to document?

**Comment by jrieken** [comment]
@saviorisdead Can you provide some detail about how the edits look? They can not overlap and there is an issue with touching ranges

**Comment by saviorisdead** [comment]
I am working on integrating rustfmt to vscode. So i have file like this:
```rust
use std::process::exit;

fn main()
{
    exit(0);    
}
```
Rustfmt produces output formatted like this:

```
Diff of /Users/sid/Desktop/code/rust/test_project/src/main.rs:


Diff at line 1:
 use std::process::exit;⏎
 ⏎
+fn main() {⏎
+    exit(0);⏎
-fn main()⏎
-{⏎
-    exit(0);    ⏎
 }⏎
```
So, basically, what i am doing. I am parsing this ouput and form two TextEdit's. First one to delete, second one to insert. For this example it would be:

```typescript
let textEdits: vscode.TextEdit[] = [];

let deleteRange = new vscode.Range(2, 0, 3, Number.MAX_SAFE_INTEGER);
let deleteEdit = vscode.TextEdit.delete(deleteRange);

let insertEdit = new vscode.TextEdit.insert(new vscode.Position(2, 0), newText);
```
I thought that TextEdit applied sequentially, so this could work.

I do this like that because if i use TextEdit.replace other issue comes up - dangling new lines, if new text has less lines.

**Comment by jrieken** [comment]
Yes, you must use the replace semantics which is (1) select the range of text that is to be replaced, (2) provide the new text. If you format the whole document you must use the whole document range and the output from your formatter as new text. It's not a dirty solution considering it describes what you are doing: replacing the whole text with new text.

**Comment by saviorisdead** [comment]
Replace semantics has some issues or i am doing it wrong.
Example:
```
a,
b
c

d
```
Which transforms to:
```
a, b
c

d
```
So, TextEdit would be:
```typescript
let replaceRange = new vscode.Range(0, 0, 2, Number.MAX_SAFE_INTEGER);
let replaceEdit = new vscode.TextEdit.replace(replaceRange, newText);
```
Which produces:
```
a, b
c
<- extra empty line

d
```
My great adventure with multiple TextEdits was desperate effort to get rid of this issue. :)

**Comment by jrieken** [comment]
It seems like `newText` has a trailing line break character at the end. You don't need to provide that in order to _complete_ the line.

**Comment by saviorisdead** [comment]
Ok, that seems to be the issue. Big thanks for your help :+1:

**Comment by jrieken** [comment]
Thank you. I will make sure make the doc more clear
