### ISSUE TITLE
File Drag and Drop on to editor area flickers 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#51600]
![kapture 2018-06-11 at 12 09 54](https://user-images.githubusercontent.com/10746682/41225999-7959d3d2-6d70-11e8-844f-4de0bc94b75c.gif)

**Comment by bpasero** [comment]
Not reproducible.

**Comment by sandy081** [comment]
I can also not reproduce it anymore. 

@bpasero On a related note, Why `esc` is not cancelling the drag and drop operation?
