### ISSUE TITLE
cannot create random location multi cursor

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5160]
- VSCode Version:1.8.2
- OS Version:ubuntu 15.10

Steps to Reproduce:

i can create multi cursors by alt-shift+(down/up) but not all the time where i wanna place cursor is exactly under the line in sublime i can press and hold ctrl and click to add cursor to any location but seems theres no way to do this in vscode . is there a way to to this without hacking ctrl-d combination by adding prefix?

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/3091

**Comment by alexandrudima** [comment]
@NikosEfthias It is possible with Alt+click, but there is no way to change it to Ctrl+click.

**Comment by NikosEfthias** [comment]
@alexandrudima  the problem is alt click is reserved on linux by the X
