### ISSUE TITLE
Tree: isVisible() is being called twice from a refresh call

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#51601]
Steps to Reproduce:

1. open a folder with just one file
2. put a breakpoint at https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L714
3. reload the window

=> this method is being called twice instead of just once which I would have expected.

**Comment by joaomoreno** [comment]
This will very likely not change... Is this expensive in the explorer?

**Comment by bpasero** [comment]
@joaomoreno can be, if:
* a folder has tons of children (e.g. 2000)
* there is a exclude pattern defined that matches with a when condition (e.g. hide all derived JS files)

This is basically after investigation in https://github.com/Microsoft/vscode/issues/47187

**Comment by joaomoreno** [comment]
Closing as won't fix.
