### ISSUE TITLE
Rendering glitch in status bar

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#51602]
Just on the latest insiders:

Note the vertical line between warnings and errors:
![image](https://user-images.githubusercontent.com/5047891/41226364-908da9ce-6d71-11e8-921c-67c01515a438.png)

**Comment by sandy081** [comment]
@alexandrudima I do not see it. Is it theme related?

**Comment by alexandrudima** [comment]
Now I don't see it anymore either

![image](https://user-images.githubusercontent.com/5047891/41236351-31943c88-6d91-11e8-874d-19623bbb35cc.png)

**Comment by alexandrudima** [comment]
Looks like one of those random Chromium issues (fyi @Tyriar)
