### ISSUE TITLE
No intellisense on document.querySelector().style

### ISSUE THREAD

**Issue by dnistreanu** [Microsoft/vscode#51607]
**OS**: Win 10 x64 Pro
**VsCode**: 
```
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Steps**:
- Write `document.querySelector('.yourSelector').style`

**Result**: Observe that intellisense doesn't show `.style` suggestion or` .style.something` suggestion.

**Note**: Same for `.src`

**Comment by mjbvz** [comment]
We cannot guarantee that the node returned from `querySelector` will have a `style`. To force this, you can use jsdocs:

```js
const node = /** @type {HTMLElement} */ (document.querySelector('.mystyle'));
node.style
```
