### ISSUE TITLE
code folding issue

### ISSUE THREAD

**Issue by cctry** [Microsoft/vscode#51604]
- VSCode Version: 1.23.1
- OS Version: Windows10

Steps to Reproduce:

When writing C/C++ code with conditional compilation preprocessor instructions like \#ifdef, the code folding feature works abnormally.
It cannot fold a function correctly with a pair of preprocessor instructions inside. The code between the start of the function and \#ifdef will be folded but rest of the code not.
The code should be folded as a whole function including everything between the braces.

# Example:
![expand](https://user-images.githubusercontent.com/17473714/41227709-5a1d9ac0-6da8-11e8-8623-b570d4f2ac05.PNG)
after folded
![folded](https://user-images.githubusercontent.com/17473714/41227909-0e3e9b44-6da9-11e8-86ad-2cd1dc1b7aa4.PNG)

The 'return' statement remains unfolded.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
There's a new 'folding provider' API where language extension can contribute language aware foldig ranges.

Moving to the CPP extension for consideration.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-cpptools#2116
