### ISSUE TITLE
Auto "this" inserting after latest update

### ISSUE THREAD

**Issue by aliev** [Microsoft/vscode#51603]
- VSCode Version: Version 1.24.0 (1.24.0)
- OS Version: 10.13.5 (17F77)

Steps to Reproduce:

1. Open any js file
2. Type this.setState()

Does this issue occur when all extensions are disabled?: Yes

I attached the video what happening:

https://www.dropbox.com/s/xkteo8yz9e7xpyu/Untitled.mov?dl=0

My vscode config file: https://gist.github.com/aliev/9588ebc0153bfb30363c75a84815d90f

**Comment by mxschmitt** [comment]
Please use the "Report Issue" reporter from VS Code in the Help menu. There you automatically get a list of all installed extensions and so on.
And try to disable all extensions to see if the issue still exists.

**Comment by mjbvz** [comment]
I'm unable to reproduce this problem in VS Code insiders.

- Does it occur in all js files or just a few? How about in other projects?
- What specific keys are you pressing here? Do you press enter to accept the suggestion for example?

**Comment by aliev** [comment]
I can't reproduce as well after restarting vscode. sorry for confusing
