### ISSUE TITLE
Open 2 different projects in seperate VSC windows

### ISSUE THREAD

**Issue by lukasru** [Microsoft/vscode#51605]
Hello,
- If I open two projects (folders) in the same moment using VSC (client and server files) from 2 different VSC windows, second one is always opening in first window (overrides first project). But If I wait few minutes it works ok. 

- please recover functionality to open a file in slide window using Ctrl + Left Mouse click (or add setting for that). Currently it almost impossible to deal with files in slides.

**Comment by bpasero** [comment]
I do not understand what this is about.

**Comment by lukasru** [comment]
this is an error request and issue to fix

**Comment by bpasero** [comment]
@lukasru does this depend on the number of files in the folder, can you also reproduce with empty folders? Can you show a video how this looks like for you?
