### ISSUE TITLE
showInformationMessage promise never completes if notification is dismissed with ESC

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51608]
Seems like this has come up and fixed before in #5797, but I'm seeing it today.

Eg. this code:

```ts
try {
	const a = await vs.window.showInformationMessage(
		`This is a test....`,
		"DO THING",
	);
	console.log(`User picked ${a}`);
} catch {
	console.log("CATCH");
} finally {
	console.log("FINALLY");
}
```

Never outputs anything if the user hits `<escape>` to dismiss it.

**Comment by bpasero** [comment]
ESC does not dismiss the notification, it will still be there in the notifications center. Closing it there will wire up the promise properly.

**Comment by DanTup** [comment]
Oh whoops, didn't realise I could get to them there. That solves my issue then, thanks! 👍
