### ISSUE TITLE
Support launching npm scripts from the package.json

### ISSUE THREAD

**Issue by edimitchel** [Microsoft/vscode#51613]
I work for a project with many npm modules.
I use the new feature "NPM Scripts", it works well, but I would like to suggest two enhancements :

* A button to shrink all modules in the npm script list view -> extracted into #54645
* Provide in source code file list a contextual menu where scripts can be launched.

Thanks !

**Comment by egamma** [comment]
@edimitchel in the future please file a feature request per issue, otherwise we cannot really track them. I´ll focus this issue on the launch a script from the source code. I´ve adjusted the title of this issue accordingly and extracted the other request into #54645

**Comment by egamma** [comment]
Fixed with 5c5f93cdbcc763b94ed996d73ed4e5329e60d7a8

**Comment by egamma** [comment]
Reopening to collect feedback on whether this should be enabled by default.

**Comment by egamma** [comment]
Feedback from twitter 
![image](https://user-images.githubusercontent.com/172399/43121636-b4465888-8f1e-11e8-9935-86acfd1c029b.png)

**Comment by egamma** [comment]
Regarding the options for a less invasive implementation:
- gutter/decorators: there is currently no support in the API for getting a click event on a decoration
- context menu actions: show the Run action in the context menu of the editor, not easily discoverable.
- hover actions: gitlens has started to provide actions on hover 
![image](https://user-images.githubusercontent.com/172399/43128525-7f9b4a80-8f32-11e8-8557-8f11abf74878.png)

My thinking is to disable the feature until we have a less invasive implementation.

**Comment by texastoland** [comment]
I find myself collapsing scripts because they have doubled in height. I love GitLens's hover actions. In this case there's no extra context to provide. In the case of the tweet it looks quite noisy. A minimal compromise could be a button in the gutter on hover?

**Comment by egamma** [comment]
I´ve added the link option to the list of options in the https://github.com/Microsoft/vscode/issues/51613#issuecomment-407338404 above.

**Comment by egamma** [comment]
@texastoland there is currently no API for an extension to add a clickable button in the gutter.

I´ve now settled on the actions as links in the hover that is shown when hovering over the script name.

![image](https://user-images.githubusercontent.com/172399/43227643-98d64882-905f-11e8-87e1-a77d6521e556.png)

**Comment by texastoland** [comment]
👍🏽 it looks nicer only visible in context thank you!

**Comment by egamma** [comment]
Fixed with 73b72464b3f71db7ac3b763f37e84769bd411a7b

**Comment by isidorn** [comment]
Works nicely -> verified

**Comment by edimitchel** [comment]
Thank for for your perfect work !
