### ISSUE TITLE
Lag when two finger scrolling on Dell XPS 13 touchpad

### ISSUE THREAD

**Issue by sashafrolov** [Microsoft/vscode#51617]
Issue Type: <b>Bug</b>

This is very similar to issue @14716 which was closed about a year ago. When scrolling with 2 fingers in any files, the scrolling is choppy and jumpy. However, resizing the window fixes this issue immediately. Even after resizing the window back to fullscreen, the issue has still been fixed. This issue still occurs on my Dell XPS 13, which was one of the more common laptops in the thread of that issue. All other reports of this bug have been closed, but I am still experiencing it. The Alt-Tabbing in @45150 appears to be one cause of this bug.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.82GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0

</details>

**Comment by bpasero** [comment]
@sashafrolov does `window.smoothScrollingWorkaround: true` help?
