### ISSUE TITLE
Insiders 1.25.0 extension does not work if there is only one installed

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#51619]
- VSCode Version: 1.25.0-insiders
- OS Version: Win10 64bit

Steps to Reproduce:

Create hello world extension using:
```
npm install -g yo generator-code
yo code
```

Put this to the .vscode-insiders/extensions/

It does not work.

However, if you install any other extension (so that you have two installed extensions!) it works.

Same is true for all extensions I presume: they don't work if you have only one installed.

**Comment by alexandrudima** [comment]
@Ciantic 

You must place the extension like this:

`$HOME/.vscode-insiders/extension/myExtension/package.json`

But why are you placing it in that location, when you can launch it from anywhere using <kbd>F5</kbd> ?

**Comment by Ciantic** [comment]
@alexandrudima they don't work either if you install only one from a market place.

I was testing my own https://marketplace.visualstudio.com/items?itemName=Ciantic.keymapceditor-vsc by installing to fresh insiders. It does not work.

Neither does hello world, if you have only one installed.

**Comment by Ciantic** [comment]
@alexandrudima 

`\.vscode-insiders\extensions\helloworldvsc\package.json`

Just try it, create only one extension to fresh Insiders, it does not work. But if you install any other extension both works.

**Comment by alexandrudima** [comment]
@Ciantic I cannot reproduce.

I have a single extension installed:
![image](https://user-images.githubusercontent.com/5047891/41241204-a7b20bc4-6d9c-11e8-9846-a710f18ae84d.png)

I can run the insiders and the single installed extension is picked up:
![image](https://user-images.githubusercontent.com/5047891/41241239-b98a5b08-6d9c-11e8-99fe-ec9c4909b644.png)

**Comment by alexandrudima** [comment]
@Ciantic Let's try to clarify. Are you having trouble with an extension that you are authoring or with any extension that you install from the marketplace?

**Comment by Ciantic** [comment]
@alexandrudima the bug can be reprod with Hello World:

```
npm install -g yo generator-code
yo code
```

`C:\Source\HTML5\vsc-example\helloworldvsc\package.json`

ONLY one installed.

Then try running Hello World command:

![image](https://user-images.githubusercontent.com/64731/41241375-6eba54bc-6da5-11e8-8180-0d1278a0b7c3.png)


It does not work. It does not run the activation at all.

**Comment by Ciantic** [comment]
after that, install some other extension, magically the Hello World starts to working.

**Comment by Ciantic** [comment]
There appears to be an error in the console if you have only one extension installed also:

![image](https://user-images.githubusercontent.com/64731/41241676-4067fa6e-6da6-11e8-92d8-8b83cf07939b.png)

But it disappears if I install second extension.

**Comment by Ciantic** [comment]
I have also reinstalled VS Code Insiders twice, and blown the %appdata%\VSCode Insiders directory couple of times.

It keeps happening for me.

**Comment by Ciantic** [comment]
@alexandrudima your extension does not work either if I have only it installed.

It shows in the context menu but it does not copy anything.

**Comment by Ciantic** [comment]
I tested now inside fresh Hyper-V Windows 10 container, same problem.

Only Copy relative path -extension installed and it does not work. It shows up in the context menu but it does not activate. Nor copy anything to the clipboard because it does not activate.

![image](https://user-images.githubusercontent.com/64731/41243186-3d6e3090-6daa-11e8-8d6d-76322368844e.png)

Same error in console (no network connectivity in the container, those errors are not relevant).

**Comment by alexandrudima** [comment]
@Ciantic Thank you for your patience. I can reproduce the exception.
