### ISSUE TITLE
Syntax highlighting is not working - Typescript  in May release

### ISSUE THREAD

**Issue by ramramps** [Microsoft/vscode#51610]
This is in Typescript...
After 200 lines, the syntax highlighting breaks. 

It was all working in 1.23.1. This ain't a large file.  The file has no lint errors or compile errors. 

I tried all the inbuilt themes. I don't have any theme extension.

- VSCode Version: Version 1.24.0 (1.24.0)
- OS Version: Mac OS 10.13.3
- Typescript: 2.9.1

Steps to Reproduce:

<img width="1266" alt="screen shot 2018-06-11 at 9 19 43 am" src="https://user-images.githubusercontent.com/8495197/41233877-a3437990-6d58-11e8-959a-78096463755f.png">

Does this issue occur when all extensions are disabled?: Yes/No - No

**Comment by aeschli** [comment]
@ramramps Can you attach the problematic code?

**Comment by ramramps** [comment]
I have the file attached in the issue...There is no problematic code here.

**Comment by mjbvz** [comment]
Please include the code as text

**Comment by klst-speterson** [comment]
+1

Typescript w/ a Node application.

Happened about an hour ago, immediately following an update.

Not sure what version I was coming from unfortunately.

- Typescript: 2.9.1

- VS Code: 1.24.0

- OS: Windows 10 Pro

If this helps at all:
Commenting out this unfinished function declaration:
<img width="271" alt="full grey" src="https://user-images.githubusercontent.com/25499683/41307149-6359627e-6e46-11e8-8675-2626f5b00ec2.PNG">

Uncommenting this unfinished function declaration:
<img width="257" alt="some grey" src="https://user-images.githubusercontent.com/25499683/41307171-6d62bca2-6e46-11e8-88c1-1a2b3b026692.PNG">

Let me know if I can provide any more info.

**Comment by ramramps** [comment]
@mjbvz I cannot add the code here. NDA must be signed.

**Comment by mjbvz** [comment]
Simplify it to a minimal repo that still demonstrates the problem. Just keep deleting stuff and confirming that the bug still exists after each step. You should be able to remove all the real logic and can even rename variables if you want
