### ISSUE TITLE
Problem with New-Manifest, encoding and github

### ISSUE THREAD

**Issue by PrzemyslawKlys** [Microsoft/vscode#51618]
- VSCode Version: 1.24.0
- OS Version: Windows 10 Enterprise Insider

I've created Module.psd1 manifest by using:

New-ModuleManifest @manifest

When I read this in VSCode, it displays just fine, when uploading it to github, it's still fine. 

![image](https://user-images.githubusercontent.com/15063294/41239036-c482ad6c-6d97-11e8-8ab3-4bfa425b7608.png)

When I change something in psd1 and try to upload it (there is a comparison shown) following appears:

![image](https://user-images.githubusercontent.com/15063294/41238831-394d2f38-6d97-11e8-943e-a155fd7e5fb6.png)

I've noticed that at the bottom it says the file is UTF16-LE when created. After I resave it as UTF-8, push code to github any subsequent changes are good.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@PrzemyslawKlys it looks like only the left hand side encoding is wrong, would that be accurate?

**Comment by PrzemyslawKlys** [comment]
It's always showing whatever is source controlled (uploaded to github) as garbage. The right side is the new side. It can show that even thou i just changed 1 line 0.1 to 0.2.
