### ISSUE TITLE
Restore "snap to minimize/maximize" feature with grid editor layout

### ISSUE THREAD

**Issue by martin-wiseweb** [Microsoft/vscode#51614]
- VSCode Version: 1.25.0-insider
- OS Version: Windows 7

## Steps to Reproduce:

1. Open 2 files
1. Split panes
1. Drag the panes so one is as small as possible
1. Click that pane

### Expected Result

The small pane, when clicked on, should expand to take as much space as possible, shrinking the other pane(s).

### Actual Result

The pane stays small.

---

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This came in when we moved to grid. @joaomoreno to comment how feasible it would be to restore this in the grid widget.

**Comment by benjaminblack** [comment]
Unpleasantly surprised to discover this feature gone in the stable release yesterday. Please bring this feature back.

**Comment by bpasero** [comment]
Pushed a change to maximize a view in the grid that is either vertically or horizontally with minimal size.

**Comment by benjaminblack** [comment]
Thank you!

**Comment by lsps9150414** [comment]
@bpasero May I ask if the feature is released in  1.25.1? My view is not expanded when focused
![8 -12-2018 12-52-04](https://user-images.githubusercontent.com/5022617/43998699-9bef49ec-9e2e-11e8-91f3-bab939e4df62.gif)

**Comment by bpasero** [comment]
@lsps9150414 no, July is 1.26. But you can stop waiting for stable releases and start using our nightly releases where this fix already landed: You can give our preview releases a try from: https://code.visualstudio.com/insiders/
