### ISSUE TITLE
Autocomplete dropdown for images in markdown

### ISSUE THREAD

**Issue by rajesh-s** [Microsoft/vscode#51611]
Thanks for the Markdown editor support in Visual Studio Code. 

Feature suggestion:
An autocomplete drop-down for image paths while working with Markdown(_md_) files can be a helpful feature. 
* The syntax for adding images in Markdown:
``` ![image description](image path) ```

* If there was a autocomplete suggestion drop-down for the **image path** in the above command, working with large Markdown documentation files with lots of images will become way more easier to add new images and eliminate broken links when the attachments are moved from source

**Comment by rishab-pdx** [comment]
Hello, @mjbvz , I would like to contribute here. I think we can have a new settings key `"markdown.ImagesPath"` - which defines the path of images for a folder. If this is the right approach to go with where can I start on this ? If this is not the right approach can you suggest me a right one and where I can start digging through so that I can make things clear.

**Comment by neilsustc** [comment]
This is already done (see the [changelog](https://github.com/neilsustc/vscode-markdown/blob/master/CHANGELOG.md#auto-completions)) if you won't mind adding one more [extension](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one). 😏

**Comment by rajesh-s** [comment]
@yzhang-gh  What I've see is that this still does not work without relaunching VSCode i.e when new images are added to a folder, they do not appear on the auto-complete suggestions until VSCode is relaunched.

Thanks!

**Comment by yzhang-gh** [comment]
Seems to work well on my laptop. Maybe you have a special file structure? You can file an issue [here](https://github.com/yzhang-gh/vscode-markdown/issues), better with some reproducing steps.

**Comment by rajesh-s** [comment]
Okay thanks will try that!
