### ISSUE TITLE
VS Code update 1.23.1 has lost a show matching pair feature

### ISSUE THREAD

**Issue by Dagge1** [Microsoft/vscode#51629]
After automatic update 1.23.1 VS Code has lost ability to find matching pair element. Now when I click on some tag, it highlights all tags with same name instead of matching pair only (as it has done before). How can I prevent VS Code from updating all the time. I just need a reliable platform, not constant changes.

Thanks

**Comment by RMacfarlane** [comment]
@Dagge1 Thanks for reporting, sorry you're seeing this issue. Can you provide some additional info: What file type does this happen for? Does the issue still repro when you disable all extensions? (Can run with `code --disable-extensions` to temporarily disable them)

You can add the setting `"update.channel": "none"` to turn off automatic updates

**Comment by Dagge1** [comment]
Hello, thanks for your code hints. I work with php files. This happens when I try to find matching html tag, all tags with same tag name get highlighted. However, matching brackets inside php script/block of code works fine.

Btw, is there an abbreviation for entering php script block <?php  ... ?>

Thanks for your prompt help.

**Comment by RMacfarlane** [comment]
This looks like a known issue: https://github.com/Microsoft/vscode/issues/2915 According to that thread, support for highlighting matching html brackets in php hasn't been implemented yet in the core product. Are you using the intelephense extension? https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by Dagge1** [comment]
Re. extension, I'm not using it or any other extension

**Comment by RMacfarlane** [comment]
Ok. Since we have another open issue on this, we'll use that to track it. Closing this as a duplicate.
