### ISSUE TITLE
Improve error message “Literal '\n' not allowed.” when searching project for a multi-line string

### ISSUE THREAD

**Issue by roryokane** [Microsoft/vscode#51623]
- VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
- OS version: Linux x64 4.15.0-22-generic

Steps to Reproduce:

The same steps as for #49287.

1. Open “SEARCH” (find in files)
1. Activate the regular expression search
1. Type anything with “\n”
1. An error will be shown: “Literal '\n' not allowed.”

![error message “Literal '\n' not allowed.”](https://user-images.githubusercontent.com/79168/41244118-1883a02c-6d72-11e8-9637-33d539277030.png)

Issue #13155 “Support multi-line search for Global search” requests that a search containing `\n` works instead of not showing an error. That's **not** what this issue is about.

This issue is about the error message wording.

> Literal '\n' not allowed.

This error message makes me think “Why? `\n` is valid in regexes, right? Yes, I think it is. Hmm, maybe I can paste a literal newline? No, VSCode refuses to paste it. Why is this happening? Let me search the error message.” And eventually I find #13155.

The message would be clearer if it changed “not **allowed**” to “not **supported**”:

> Literal '\n' currently not supported.

This way, I understand that I didn't do anything wrong when I entered my regex, and that I have to use a different tool to search for this regex.

The error message could even include a link to open the relevant issue in the user's web browser:

> Literal '\n' not yet supported. ([details](https://github.com/Microsoft/vscode/issues/13155))

(I changed “currently not” into “not yet” there because that might be necessary for the error message to fit in the limited space it has.)

Changing the error message should be a lot quicker than waiting for #13155 to be actually solved, so I think it would be worth doing even though this error will eventually go away.

**Comment by roblourens** [comment]
I tweaked the error message. I don't think that linking to the feature request would really help anyone, but emphasizing that it's not *supported* makes sense.

**Comment by innerlee** [comment]
But it is supported in the per-file search.

**Comment by j0be** [comment]
But @innerlee, because it is supported, you won't get that error message in the per-file search. 

![screen shot 2018-06-25 at 15 34 52](https://user-images.githubusercontent.com/5649072/41871574-5a65c62a-788d-11e8-9502-34a195f48386.png)
![screen shot 2018-06-25 at 15 34 58](https://user-images.githubusercontent.com/5649072/41871575-5a771b3c-788d-11e8-8f6d-75ea7f761f0d.png)
