### ISSUE TITLE
node-weak issues with Electron and node 5.x

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5162]
We see native crashes when using node-weak together with latest Electron version (see https://github.com/electron/electron/issues/4299).

Setup VS Code:
* checkout `ben/electron`
* `git clean -xfd`
* `scripts/npm.sh install`
* `gulp watch`
* `scripts/code.sh`
* this should start with Electron 0.37.5 just fine

Setup a workspace to reproduce the crash:
* git clone `https://github.com/Microsoft/TypeScript.git`
* I can reproduce on https://github.com/Microsoft/TypeScript/commit/94ada07
* open the workspace
* open `lib/dom.generated.d.ts` (or any other large d.ts file they have)
* hover over some of the interfaces to the top (triggers language service)
* open `harness/runner.ts`
* hover over `runTests` to the top to trigger language service
* jump back and forth between these two files (`Cmd+Tab`) and repeat
* eventually you should get the crash (it seems to reproduce more easily after a window reload for some reason)

Things that make it not reproduce:
* disabled git (somehow the git-index resources as models cause issues)
* disabling node-weak
* changing node-weak to always return a fresh weak reference

**Comment by jrieken** [comment]
pushed https://github.com/Microsoft/vscode/commit/6d7880101e2dbcdf823646797fe4533b0dc439bd as an attempt to workaround the issue

**Comment by jrieken** [comment]
I am very eager to figure out what's happening here. Despite that I checked the whys and hows of weak being in our code base and why it's a good feature it not a _must_. We can get rid of it without breaking API or the need of adding API. Basically, today it's used like this: Periodically we check if virtual documents are still open in any editor, iff not we check if there still usages/references in the extension host, iff not we dispose. IMO this is the nicer and more correct behaviour, but we can employ the same tactics as we do for _real_-documents and just dispose them as we think it's a good time - ignoring any extension host usage.

fyi @egamma

**Comment by bpasero** [comment]
We decided to take out node-weak for now. We can revisit this by implementing our own version of weak references with officially supported API from V8.
