### ISSUE TITLE
dependsOn is no longer working

### ISSUE THREAD

**Issue by IAmHopp** [Microsoft/vscode#51627]
Issue Type: <b>Bug</b>

Hi,

I have a set of tasks defined for everyday use, the build one being a series of tasks linked via dependsOn. Due to one of the recent builds [don't know if it was today's, I don't think I built anything on friday], tasks with dependsOn are no longer working on my machine.

This simple scenario, for example, fails:

tasks.json
```
[...]
        {
            "command": "Write-Host 'Second'",
            "dependsOn": "First",
            "group":
            {
                "isDefault": true,
                "kind": "build"
            },
            "label": "Second",
            "type": "shell"
        },
        {
            "command": "Write-Host 'First'",
            "label": "First",
            "type": "shell"
        }
[...]
```

Running the task Second without dependsOn works and "Second" is correctly outputted. Running with dependsOn errors out with the following Tasks output:

> Cannot read property 'type' of undefined

I can verify this still works as intended on 1.24.0. Any guidance here would be appreciated.

VS Code version: Code - Insiders 1.25.0-insider (28d5806f24f99c2c6ad633e4e08ed5ea00169c83, 2018-06-11T05:17:42.700Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.3.5
mssql|ms-|1.3.1
team|ms-|1.136.0
java|red|0.26.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by dbaeumer** [comment]
@IAmHopp thanks for the issue report. I am able to reproduce. Very likely caused by allowing task identifiers in `dependsOn` property.

**Comment by IAmHopp** [comment]
Thanks, man.
