### ISSUE TITLE
Replace in files will stop after 10000 items

### ISSUE THREAD

**Issue by redknightlois** [microsoft/vscode#51624]
- VSCode Version: 1.23.1
- OS Version: Windows

Steps to Reproduce:

1. Open a tab separated CSV of 300MB
2. Edit -> Replace in files -> 
      Search ``'\<tab>'``,
      Replace ``','`` 
      Match whole word

The replace will only replace 10000 items. I know this is probably by design (because of the effort of actually warning me that there are more than 10000 items and won't be shown) but not replacing everything when I hit `Replace **All**` is a bug (it goes against well-established conventions).

**Comment by roblourens** [comment]
Actually duplicate of https://github.com/microsoft/vscode/issues/8563
