### ISSUE TITLE
Python: Go to Symbol in File Broken

### ISSUE THREAD

**Issue by rwinslow** [Microsoft/vscode#51634]
Issue Type: <b>Bug</b>

Whenever I try to `Go to Symbol in File` I get a message "No Symbols Found". I work with a large codebase and do not need Workspace symbols, only within the file. This was working maybe a version ago but has since been broken for a couple of weeks. Disabling extensions does not help.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.1
prettify-json|moh|0.0.3
python|ms-|2018.5.0
Go|ms-|0.6.82
vscode-icons|rob|7.23.0
ayu|tea|0.14.0

(2 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@rwinslow Thanks for reporting! `Go to Symbol in File` isn't supported out of the box for Python, the python extension adds this functionality. I'm going to move this over to their repository.

**Comment by RMacfarlane** [comment]
This issue was moved to Microsoft/vscode-python#1931
