### ISSUE TITLE
With Follow Cursor in Outline, function name should higlight if cursor is any line within the function

### ISSUE THREAD

**Issue by RogFedex** [Microsoft/vscode#51635]
If mouse cursor in editor view is in the middle of a function the outline should select the function name. As of now the Outline is selecting the function only if function header is selected and not when the cursor is somewhere in the middle of the function

**Comment by RMacfarlane** [comment]
@RogFedex What language are you using?

**Comment by RogFedex** [comment]
C language

**Comment by jrieken** [comment]
That happens because we don't get a tree-structure from extensions yet. We work on finalising the API and until then we synthesise the tree, something with suboptimal results.
