### ISSUE TITLE
No Intellisense for globally installed JavaScript modules

### ISSUE THREAD

**Issue by d4mr** [Microsoft/vscode#51639]
Intellisense and suggestions do not work for modules that are installed globally using `npm install -g`.
It only works if the module is listed in the `package.json` file at the root of the project folder.

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/20401 which is a duplicate of https://github.com/Microsoft/TypeScript/issues/8760

The recommendation is to always have dependencies listed in the local `package.json`
