### ISSUE TITLE
Incorrect ternary autoformatting

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#51632]
- VSCode Version: Version 1.24.0
- OS Version: Lubuntu 18.04

Steps to Reproduce:

1. type in a `Javascript` file:
```js
const foo = 1 ? {
    foo: 1
} : {
    foo: 2
};

const bar = 1 ? {
    bar: 1
} : 2 ? {
    bar: 2
} : {
    bar: 3
}

const qux = 1 ? {
    qux: 1
} : 2 ? {
    qux: 2
} : 3 ? {
    qux: 3
} : {
    qux: 4
}
```

The code is currently correctly indented

2. Save the file (if `editor.formatOnSave: true`) or format the code, it produces:
```js
const foo = 1 ? {
    foo: 1
} : {
        foo: 2
    };

const bar = 1 ? {
    bar: 1
} : 2 ? {
    bar: 2
} : {
            bar: 3
        }

const qux = 1 ? {
    qux: 1
} : 2 ? {
    qux: 2
} : 3 ? {
    qux: 3
} : {
                qux: 4
            }
```
 

Does this issue occur when all extensions are disabled?: Yes

note: wrapping the last objects of the ternaries in `()` will make the formatting correct

**Comment by RMacfarlane** [comment]
Thanks for reporting, it looks like this is already covered by this issue: https://github.com/Microsoft/vscode/issues/22110
