### ISSUE TITLE
--install-extensions is not installing locally downloaded extensions.

### ISSUE THREAD

**Issue by KonTy** [Microsoft/vscode#51637]
Issue Type: <b>Bug</b>

My team ran across a nasty bug that blocks us from installing our custom plugin in VSCode

According to documentation you supposed to be able to download a plug-in from VSCode extension repository, save it to disk and install it. The documentation is here (https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) but when I do that with the latest version on VSCode nothing happens. Well, it just launches VSCode and that’s it, no extension install happens. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz (36 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (20.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-formatter|cym|1.0.2
vscode-markdownlint|Dav|0.18.0
prettify-json|moh|0.0.3
python|ms-|2018.5.0
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
vscode-autohotkey|sle|0.2.2

(1 theme extensions excluded)

</details>

**Comment by jflefebvre06** [comment]
Same problem detected (I use portable version)

**Comment by sandy081** [comment]
@KonTy Can you set log level to Trace using `Set Log Level` command. Open shared process log in output panel and let us know what you see there?

**Comment by KonTy** [comment]
@sandy081 can you point me at instructions on how to do that? I tried searching for these and couldh't find how to do what you are asking. 

PS. It would be much easier for you to just repro it. It repro's 100% of the time for me everyone around here. 

1. Download any VSIX file for the VS marketplace to you HDD
2. in the command line run: "code --install-extensions <path-to-your-vsix>

**Comment by sandy081** [comment]
It works for me both stable (1.24) and insiders version of VS Code.

Can you please update your VS Code and try?
