### ISSUE TITLE
feature: Add an option to hide private members in Intellisense

### ISSUE THREAD

**Issue by iignatov** [Microsoft/vscode#5163]
- VSCode Version: 0.10.11
- OS Version: Windows 8.1 (64-bit)

It would be great to hide the private members in Intellisense, as in some frameworks/libraries _(e.g. Ionic 2)_ there are a lot of members shown in the Intellisense popup when only few of them are public _(i.e. targeted at the end user)_. This makes the use of Intellisense harder especially at the beginning when exploring a new framework/library or functionality/class for the first time. Now the private members are marked as such _(with `@private`)_ but sometimes it still requires too much scrolling/browsing to find the needed class member in the Intellisense popup.

**Comment by tinganho** [comment]
also hide nested functions.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/14009 to support hiding members with the jsdoc `@private` / `@protected` annotation. For external libraries, the `*d.ts` files we use to power intellisense should not include private members.

Closing as upstream. Let me know if there are other specific scenarios where private members should not be shown
