### ISSUE TITLE
Duplicate module load error

### ISSUE THREAD

**Issue by echeypaz** [Microsoft/vscode#51636]
Bundling `index.android.js`  [development, non-minified]  0.0% (0/2), failed.
error: bundling failed: ambiguous resolution: module `f:\shoutem\aaa\extensions.js` tries to require `shoutem.about`, but there are several files providing this module. You can delete or fix them: 

  * `F:\shoutem\aaa\extensions\shoutem.about\app\package.json`
  * `f:\shoutem\aaa\extensions\shoutem.about\app\package.json`

**Comment by RMacfarlane** [comment]
@echeypaz Please provide more details about how to reproduce this problem. What did you run to see this error? What version of VSCode are you using and what is your OS?

**Comment by echeypaz** [comment]
Hi @RMacfarlane, Thanks,
VSCode Version 1.24.0
Nodo 7.9.0
Arquitectura x64.
Windows 10.
I was debugg a react-native app (with react-native tools)

**Comment by RMacfarlane** [comment]
Thank you for the details! I'm still not sure how to reproduce this. Can you please describe exactly what you did to see this, or share your code? Is this an issue with VSCode itself, or is this specific to the `react-native` extension? This does not sound like a feature of VSCode itself and might be better moved to https://github.com/Microsoft/vscode-react-native

**Comment by echeypaz** [comment]
I completely agree. The problem arises when debugging with react-native-tools, because when I use the chrome debugger, after launching react-native run-android, this problem does not play. Could you move the post to the right place?

**Comment by RMacfarlane** [comment]
This issue was moved to Microsoft/vscode-react-native#727
