### ISSUE TITLE
Update Failed POPUP requested new issue

### ISSUE THREAD

**Issue by Chris-43** [Microsoft/vscode#51643]
- VSCode Version: ???? It is gone  I will download new
- OS Version: Windows 10

Steps to Reproduce:

1.havent' tried 
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2092021/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
