### ISSUE TITLE
Feature request: Persistent filter in outline view

### ISSUE THREAD

**Issue by dsteg** [Microsoft/vscode#51647]
Currently the text entered in the filter field of outline view vanishes upon entering text in the main editor windows. It would be helpful if filter criteria could be made persistent (e.g., I sometimes use it to only display  "fig:"  in a latex document).

**Comment by jrieken** [comment]
Yeah, makes sense. Tho, I wonder if we should keep it only stable for the current editor, all editor, or all editors of the same language... Ideas?

**Comment by dsteg** [comment]
Good question.
My preference would be to have it only for the current editor. 
Of course, individual use cases will differ. Maybe add an option below "Filter on Type" that makes it persistent for someone who wants the same filter on a large number of files.

**Comment by jrieken** [comment]
* keeps filter stable while staying inside the current file
* resets filter when changing to another file

![jun-15-2018 11-37-20](https://user-images.githubusercontent.com/1794099/41461628-84bbf430-7090-11e8-96a2-ed0ea3b13093.gif)
