### ISSUE TITLE
Intellisense - JSX element type '{ComponentName}' does not have any construct or call signatures

### ISSUE THREAD

**Issue by ShawnCholeva** [Microsoft/vscode#51644]
- VSCode Version: 1.24.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Download the project form this repo: https://github.com/ShawnCholeva/matierialui-import-issue
2.  Run yarn command in folder that contains package.json
3.  Navigate to src/home/home.tsx .
4.  View intellisense issue.
5.  Rename home.tsx to home.jsx, and view that the intellisense error is no longer there.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#24893
