### ISSUE TITLE
only show one tab,new tab will replace exist tab

### ISSUE THREAD

**Issue by daskyrk** [Microsoft/vscode#51649]
Issue Type: <b>Bug</b>

when open new file, new tab will replace the exist opening file tab, but when i close the current tab, the tab opened before will show. So I can't switch tab between multiple opening files.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
output-colorizer|IBM|0.1.2
material-icon-theme|PKi|3.5.0
project-manager|ale|0.25.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
react-redux-react-router-snippets|dis|0.4.29
vscode-new-file|dku|4.0.2
githistory|don|0.4.1
gitlens|eam|8.3.5
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-auto-open-markdown-preview|hnw|0.0.4
expand-region|let|0.1.2
vs-color-picker|lih|0.7.0
vscode-language-pack-zh-hans|MS-|1.24.3
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.6.0
color-highlight|nau|2.3.0
sass-indented|rob|1.4.9
addDocComments|ste|0.0.8
language-stylus|sys|1.9.2
full-react-snippets|wal|1.1.2
vscode-todo-highlight|way|0.5.12
JavaScriptSnippets|xab|1.6.0

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
Thanks for reporting! Is this what you are describing?

![preview](https://user-images.githubusercontent.com/3672607/41308610-4192f278-6e31-11e8-8e90-f81f5800b87f.gif)

Whenever you open a new file, it is shown as a preview. To make the open tab permanent, you can double click the tab, or edit the file. You can also disable this behavior by adding `"workbench.editor.enablePreview": false` and `"workbench.editor. enablePreviewFromQuickOpen": false` to your settings.

Please reopen this issue if that doesn't solve your problem.

**Comment by daskyrk** [comment]
I double clicked the file ,but the tab not permanent, when double click another file, it will not append a new tab just like this:
![img](http://i4.bvimg.com/649740/a8fb3b3e14985494.gif)

**Comment by daskyrk** [comment]
@RMacfarlane It seems that I can't reopen this issue :(

**Comment by daskyrk** [comment]
@RMacfarlane I finally found it's my user setting incorrect, i set
`workbench.editor.showTabs=false`
which cause it, It's ok now. but i don't remember when did i set it ....
