### ISSUE TITLE
Certain key combinations are treated wrong in MacOS

### ISSUE THREAD

**Issue by dkundel** [Microsoft/vscode#5164]
- VSCode Version: 0.10.11
- OS Version: MacOS 10.11.2

Steps to Reproduce:
1. Install the 'Advanced New File' extension or create a shortcut that is listening for Mac on `alt+cmd+n`
2. It displays the keyboard shortcut correctly in the command palette
3. It doesn't trigger the respective command.
4. Changing it to `alt+cmd+`` will do the trick and trigger the shortcut when you press <kbd>Alt</kbd>+<kbd>Cmd</kbd>+<kbd>N</kbd>

It appears that this is happening because <kbd>Alt</kbd>+<kbd>N</kbd> is an actual special character and rather than triggering the actual keys it handles the special characters.

**Comment by sarbbottam** [comment]
@egamma @bpasero could you share your concerns?

**Comment by alexandrudima** [comment]
@dkundel What keyboard layout do you have?

**Comment by dkundel** [comment]
I have a US keyboard layout. Not sure about the others. This has been reported by a couple of folks.

**Comment by ihorskyi** [comment]
Same issue here, can't use neither `cmd+alt+n` nor `alt+cmd+n` for shortcut in vscode.
**MacOS**: 10.9.5
**VSCode**: 1.5.3
**Keyboard Layout**: US

At the same time `cmd+alt+m` & `alt+cmd+m` works fine

**Comment by alexandrudima** [comment]
I @dkundel @ihorskyi Do other applications on your machine recognize `alt+cmd+n`. What happens when you press the key combo in the Define Keybinding widget?

![cmd-alt-n](https://cloud.githubusercontent.com/assets/5047891/19784888/b2debe48-9c97-11e6-837e-00bbbe7ecae5.gif)

**Comment by dkundel** [comment]
It shows <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>`</kbd> in the widget.

**Comment by alexandrudima** [comment]
@dkundel I have just written a wiki describing in detail how we handle keybindings in VS Code -- https://github.com/Microsoft/vscode/wiki/Troubleshooting-Keybindings. Would you mind giving it a quick read so we end up talking about the same things.

From seeing <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>\`</kbd>, it appears that Chromium is sending our way a `keydown` event with the `keyCode = VKEY_OEM_3 = 192`. Would you mind checking that is indeed the case:

Go to https://www.w3.org/2002/09/tests/keys.html in Chrome and Safari and press the key combination `cmd+alt+n`. Please paste in here what events you see on your machine (a screenshot or copy-paste the results below show).

**Comment by dkundel** [comment]
It indeed sends the keyCode 192 for <kbd>N</kbd> when it's used with <kbd>cmd</kbd>+<kbd>alt</kbd>

Here are the results:
```
keydown (0): [keyCode: 91][shift: false][ctrl: false][alt: false][meta: true]
keydown (1): [keyCode: 18][shift: false][ctrl: false][alt: true][meta: true]
keydown (2): [keyCode: 192][shift: false][ctrl: false][alt: true][meta: true]
```

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's upcoming Insiders build) appear to detect correctly this keypress.

![image](https://cloud.githubusercontent.com/assets/5047891/24291221/5b76698e-1088-11e7-8fba-283343b62b57.png)

Additionally, I have written the following keybinding rule in my `keybindings.json`:

```
{
    "key": "alt+cmd+n",
    "command": "actions.find",
    "when": "editorTextFocus"
}
```

And when pressing `cmd+alt+n` the find widgets pops up correctly.

**Comment by dkundel** [comment]
Thank you!
