### ISSUE TITLE
"workbench.action.findInFiles" should automatically add the root folder of the current project (the project of the file in editor) to 'files to include' 

### ISSUE THREAD

**Issue by RogFedex** [microsoft/vscode#51640]
We dont want to search in all project in workspace of the selected text in a file with "workbench.action.findInFiles". If we have a new api "workbench.action.findInFilesInProject" for this purpose of searching only in the project the file on which we have selected text then also is good

**Comment by roblourens** [comment]
Is this what you want when searching with ctrl+shift+f in the UI, or are you trying to invoke search from an extension?

**Comment by RogFedex** [comment]
I like to have the 'find in files' poulated automatically with the root folder name (based on the file in editor) with ctrl+shift+f in the UI

**Comment by roblourens** [comment]
Ok. I disagree that most people would want this behavior. Typically if I'm working in a workspace with multiple folders, it's because I care about all of those folders. Other features of vscode don't have a concept of a "current" folder.

But, I would consider a new command to do this.

**Comment by RogFedex** [comment]
Yes, new command would be perfect as it is also needed at times to search across workspace projects.

**Comment by roblourens** [comment]
It would now be possible for an extension to implement this by passing arguments to the findInFiles command.
