### ISSUE TITLE
Commands never execute if sent to terminal before it is ready to accept input

### ISSUE THREAD

**Issue by alexvy86** [Microsoft/vscode#51653]
- VSCode Version: 1.24.0
- OS Version: Windows 10 Pro (build 1803)

I originally reported this [here](https://github.com/Microsoft/vscode-python/issues/1857). In short, it seems that commands are sometimes being sent to the integrated terminal before it is ready to receive them (e.g. if the terminal prompts the user for input right after it launches), and consequently those commands do not actually execute. If that command is a Debug command, VS Code ends up thinking that a debugging session is in progress even though that session never started.

My setup has Git Bash as the integrated terminal, launched as a login shell, and a script that runs when Git Bash launches which might prompt the user for input (the passphrase for my SSH key). When I start debugging my project, if the new terminal instance happens to prompt me for input, the debug command never executes (it seems the terminal doesn't receive it at all).

### Steps to Reproduce:
(Assumes you have at least one SSH key in your home folder, protected with a passphrase, and Git For Windows installed)
1.  Set your integrated terminal to launch an interactive login terminal by adding this to VS Code's User Settings (adjust path if needed):
```json
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
"terminal.integrated.shellArgs.windows": ["-l"],
```
2. Create a `.profile` file in your home folder (e.g. `C:\Users\<your-username>`) or wherever your HOME environment variable (inside Bash) points to, and write this in it:
```
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

# Adding 12 hrs
if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add -t 43200
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add -t 43200
fi

unset env
```
3. Open a `.py` file in VS Code, select the `Python: Current File` debug configuration and start debugging.

You'll be prompted for the private key passphrase, but once you provide it nothing else happens, the terminal just sits there and you can use it normally to execute other commands. However, VS Code thinks debugging is in progress and cannot be made to think otherwise without restarting it.

### Does this issue occur when all extensions are disabled?
Yes/No/**Not sure this applies**

**Comment by Tyriar** [comment]
The terminal is working as expected imo, explanation added to https://github.com/Microsoft/vscode-python/issues/1857#issuecomment-397633430

**Comment by alexvy86** [comment]
@Tyriar good point about the "bad passphrase" line So does this mean that a terminal prompting for user input when it launches cannot be supported at all? You said in your comment in [the other issue](https://github.com/Microsoft/vscode-python/issues/1857#issuecomment-397633430):
> there isn't really a way to "fix" this upstream

Does that mean there is no way to differentiate when a terminal is "ready", prompting for a command, or is prompting for user input in the middle of the script? I guess that makes sense, I'm just not familiar with this topic.

**Comment by Tyriar** [comment]
> Does that mean there is no way to differentiate when a terminal is "ready", prompting for a command, or is prompting for user input in the middle of the script?

Yes there is no reliable way to know if the terminal is accepting input and for what it is accepting input for.
