### ISSUE TITLE
关于打开文件bug

### ISSUE THREAD

**Issue by XSmarter** [Microsoft/vscode#51656]
Issue Type: <b>Bug</b>

相同的文件名，左侧资源管理器点击打开时，不创建新的tab，会覆盖之前相同文件的tab

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (3.29GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe E:\Work\alibaba\pro\alibaba|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
svn-scm|joh|1.29.2
vscode-language-pack-zh-hans|MS-|1.23.5

</details>

**Comment by Tyriar** [comment]
Translation:

> About opening a file bug
> 
> The same file name, when the left explorer clicks Open, a new tab is not created, it overwrites the previous tab of the same file

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
