### ISSUE TITLE
Window flickering when scrolling around "Code Folding" and "Errors and Warnings" in Interactive Playground

### ISSUE THREAD

**Issue by jamesh627** [Microsoft/vscode#51654]
- VSCode Version: 1.24.0
- OS Version: Mac OS High Sierra 10.13.5
- Extensions: dbaeumer.vscode-eslint, jeff-hykin.code-eol, justusadam.language-haskell, lihui.vs-color-picker, mechatroner.rainbow-csv, ms-python.python

Steps to Reproduce:

1. Open VS Code.
2. Click on Interactive "Playground" from the "Welcome" page.
3. Scroll down to around "Code Folding" and "Errors and Warnings"
4. Watch the screen flicker (other parts of the screen, including other windows currently open, are unaffected).

Does this issue occur when all extensions are disabled?: Yes

Video link: https://youtu.be/w-az75ZtqX8

What I've tried:
 - Restarting VS Code had no effect.
 - Running `code --disable-gpu` had no effect.
 - Restarting and then running `code --disable-gpu` had no effect.
 - Disabling all extensions had no effect.

**Comment by jamesh627** [comment]
I've just noticed that even though I did "Disable All Installed Extensions" via the Command Palette, the jeff-hykin.code-eol extension appears to still be active as I can see the newline characters it inserts (you can see them in the video, too).

**Comment by RMacfarlane** [comment]
Thanks for reporting! This is very strange behavior.

It looks like the `Disable All Installed Extensions` doesn't reload the window, which is needed for the change to take effect. Can you try again after reloading it, or use `Reload Window With Extensions Disabled` to temporarily disable extensions?
