### ISSUE TITLE
Links on Visual Studio Code Feature Poll page don't work

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#5165]
https://visualstudio.uservoice.com/forums/293070-visual-studio-code

Links go to Github and Requested Extensions go to https://visualstudio.uservoice.com/forums/(https://github.com/Microsoft/vscode/issues) and https://visualstudio.uservoice.com/forums/(https://github.com/Microsoft/vscode/wiki/Requested-Extensions) respectively

Maybe a markdown error?

**Comment by egamma** [comment]
CC @seanmcbreen

**Comment by waderyan** [comment]
Weird. They don't seem to be parsing the textile markdown correctly. I moved the links to inline and it works now.
