### ISSUE TITLE
用 vscode 打开项目里包含cnpm下载的包会很卡

### ISSUE THREAD

**Issue by csj8520** [Microsoft/vscode#51652]
第一种方式 : 在 cnpm i 完成后，打开 vscode 将设置中的 search.followSymlinks 修改为 false 。

第二种方式 : 在 cnpm 命令后面添加参数，即使用 cnpm i --by=npm 来安装

上面是我找到的解决方法但是我想知道search.followSymlinks 这个配置是干啥的
还有为什么使用cnpm，vscode就回卡

**Comment by mjbvz** [comment]
Sorry, I do not understand the issue. Please provider:

* List of steps to reproduce the problem
* Expected behavior
* Actual behavior

**Comment by rebornix** [comment]
If I understand correctly, what he is saying is using [cnpm](https://github.com/cnpm/cnpm) in vscode is slow, but it get mitigated if 

* use npm
* set `search.followSymlinks` to `false`

@roblourens any idea why that setting changes the behavior?

**Comment by roblourens** [comment]
Hey @csj8520 this is expected, that is exactly the scenario that the 'followSymlinks' setting is for. cnpm adds a lot of symlinks inside node_modules which take a very long time for search to follow. You can also exclude node_modules from your search with the 'files.exclude' or 'search.exclude' settings.
