### ISSUE TITLE
Ctrl+S In TreeView Causes 'Cannot read property 'toString' of undefined' Error

### ISSUE THREAD

**Issue by pltrant** [Microsoft/vscode#51651]
- VSCode Version: 1.24
- OS Version: Windows 10

Steps to Reproduce:

1. Highlight a node in a custom TreeView
2. Hit Ctrl+S (to save the current document)

Causes an 'Cannot read property 'toString' of undefined' error to be displayed.

**Comment by RMacfarlane** [comment]
@pltrant Thanks for reporting! Can you open the console with `Developer: Toggle Developer Tools` and copy an errors you see there?

**Comment by pltrant** [comment]
No errors or messaging show up in the Developer Tools console.  It's with a custom TreeView and just results in this notification:

![image](https://user-images.githubusercontent.com/9040032/41311630-65af6e52-6e4a-11e8-8567-4a16c72a6283.png)

**Comment by sandy081** [comment]
@pltrant Which tree view is it causing on?

**Comment by pltrant** [comment]
The original issue happened in the tree view created from my extension, but I just reproduced the error with the JSON outline tree view from your [tree-view-sample repo](https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample):

![image](https://user-images.githubusercontent.com/9040032/41609329-23daafe4-73b0-11e8-9c09-81274261e87d.png)

**Comment by sandy081** [comment]
@isidorn cmd+s on a custom view is triggering save file command [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L460) and is causing this issue.

I think file command should not be executed in this context, even so, it should not throw an exception.

Assigning it to you.

**Comment by isidorn** [comment]
@pltrant good catch, thanks.
