### ISSUE TITLE
vscode with vim

### ISSUE THREAD

**Issue by uraidiot** [Microsoft/vscode#51655]
- VSCode Version: 1.24.0
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. file type: .php
2. use vim mode

the application takes up  the 96% cpu

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
@uraidiot Thanks for reporting! Since this is an issue with a specific extension, please file it on the extension itself, most likely here: https://github.com/VSCodeVim/Vim
