### ISSUE TITLE
PHP: square brackets in regex-looking string break syntax highlighting

### ISSUE THREAD

**Issue by LenAnderson** [Microsoft/vscode#51659]
Issue Type: <b>Bug</b>

Steps to Reproduce:

This code:

    <?php
    $foo = '/abc[/';
    $bar = 1;

Highlights like this:
![screenshot](https://i.imgur.com/5xwL8qa.png)

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|7.91GB (2.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --disable-gpu|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
code-runner|for|0.9.3
svn-scm|joh|1.29.1
php-symbols|lin|2.1.0
rainbow-csv|mec|0.4.1
easy-less|mrc|1.4.5
vscode-apache|mrm|1.1.1
csharp|ms-|1.15.2
vscode-code-outline|pat|0.2.1
spgo|Sit|1.3.1

</details>

**Comment by roblourens** [comment]
Upstream: https://github.com/atom/language-php/issues/244
