### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#51664]
Issue Id: <b>55412e0a-2a46-b1c9-67ff-13e290d83729</b><br /><br />*Versions* <br />- 1.24.0<br />-  f67e6397855fb25becbdf33df185f96da7fdd108<br />-  92754223624dcbe9aca0e5ca3ba8a53808b122b6<br />*Stack* <br />TypeError: Cannot read property 'id' of undefined<br />[/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#396:53](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L396:53)<br />    at Array.map (native)<br />[/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#395:27 (onComplete)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L395:27 (onComplete))<br />[/vs/base/common/winjs.base.js#1185:0 (_notify)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L1185:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0 (_run)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L1083:0 (_run))<br />[/vs/base/common/winjs.base.js#1051:0 (onComplete)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L1051:0 (onComplete))<br />[/vs/base/common/winjs.base.js#1185:0 (_notify)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L1185:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0 (_run)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L1083:0 (_run))<br />[/vs/base/common/winjs.base.js#1051:0 (onComplete)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L1051:0 (onComplete))<br />[/vs/base/common/winjs.base.js#1185:0 (_notify)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L1185:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/winjs.base.js#L1083:0)<br />    at n.Cl<br />

**Comment by sandy081** [comment]
Identifier of an extension should never be null. Adding a null check is not a right approach. Will wait for a real issue instead.
