### ISSUE TITLE
 Cannot read property 'onDidChangeTitle' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#51660]
Issue Id: <b>4a236dab-f5d3-3f82-6b00-3d7661f17c4b</b><br /><br />*Versions* <br />- 1.24.0<br />-  92754223624dcbe9aca0e5ca3ba8a53808b122b6<br />-  b4e6fe3bd751448783ed20c8e49fdabd69514b8d<br />-  f67e6397855fb25becbdf33df185f96da7fdd108<br />*Stack* <br />TypeError: Cannot read property 'onDidChangeTitle' of undefined<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#1345:80 (onSelectionChange)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L1345:80 (onSelectionChange))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#1155:8 (call)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L1155:8 (call))<br />[/vs/base/common/event.ts#142:18 (fire)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/event.ts#L142:18 (fire))<br />[/vs/workbench/services/scm/common/scmService.ts#115:29 (_i)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/services/scm/common/scmService.ts#L115:29 (_i))<br />[/vs/base/common/lifecycle.ts#51:16 (dispose)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/lifecycle.ts#L51:16 (dispose))<br />[/vs/workbench/services/scm/common/scmService.ts#76:18 (dispose)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/services/scm/common/scmService.ts#L76:18 (dispose))<br />[/vs/workbench/api/electron-browser/mainThreadSCM.ts#317:13 (apply)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/api/electron-browser/mainThreadSCM.ts#L317:13 (apply))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#265:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L265:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#250:27 (_invokeHandler)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L250:27 (_invokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#196:39 (_receiveRequest)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L196:39 (_receiveRequest))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#178:9 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L178:9 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#111:65 (onMessage)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L111:65 (onMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#307:4 (call)](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L307:4 (call))<br />[/vs/base/common/event.ts#140:15](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/base/common/event.ts#L140:15)<br />    at Socket.<anonymous> (out/vs/workben<br />

**Comment by joaomoreno** [comment]
Great catch, bot!

Repro:

1. Install an extension which contributes a view to the SCM viewlet
2. Open a repository
3. Run `Git: Close Repository`
4. 💥
