### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'beginFrame' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#51663]
Issue Id: <b>12ca1213-b307-9bdf-d410-7c1a071af500</b><br /><br />*Versions* <br />- 1.24.0<br />-  92754223624dcbe9aca0e5ca3ba8a53808b122b6<br />-  a8816968fed45b2cf2ecd67dd3a1678c819d19b3<br />*Stack* <br />TypeError: Cannot read property 'beginFrame' of undefined<br />    at TextRenderLayer.onGridChanged (\node_modules.asar\vscode-xterm\lib\renderer\TextRenderLayer.js:143:24)<br />[/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#481:25](https://github.com/microsoft/vscode/blob/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L481:25)<br />    at \node_modules.asar\vscode-xterm\lib\renderer\Renderer.js:154:60<br />    at Array.forEach (native)<br />    at Renderer._renderRows (\node_modules.asar\vscode-xterm\lib\renderer\Renderer.js:154:28)<br />    at RenderDebouncer._innerRefresh (\node_modules.asar\vscode-xterm\lib\utils\RenderDebouncer.js:29:14)<br />    at \node_modules.asar\vscode-xterm\lib\utils\RenderDebouncer.js:24:88<br />

**Comment by Tyriar** [comment]
Upstream PR is out: https://github.com/Microsoft/vscode/issues/51663

**Comment by Tyriar** [comment]
You can review via code review of the PR
