### ISSUE TITLE
Auto close notifier by a timer

### ISSUE THREAD

**Issue by NateLing** [Microsoft/vscode#51678]
VSCode notifier cannot auto close, even a long time. i think the better way is auto close it by a timer.

![image](https://user-images.githubusercontent.com/9606668/41278898-a2c0328c-6e5d-11e8-84d4-ce0df7838f50.png)

**Comment by bpasero** [comment]
@NateLing good catch, this is a regression.

**Comment by bpasero** [comment]
@RMacfarlane that is by design, assuming that the notification wants user input
