### ISSUE TITLE
Git icon not "spinning" when pushing from command palette

### ISSUE THREAD

**Issue by ErlendEllingsen** [Microsoft/vscode#51677]
- VSCode Version:  1.23.0
- OS Version: Windows 10

Steps to Reproduce:

1. Push to git from command palette instead of clicking the visual icon
2. Icon will not "spin" as it does when clicking it.

The refresher / spinner icon is a nice indicator that a git action is being performed. When pushing from command palette there is no real indication that any action is going on in the bottom left area.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by joaomoreno** [comment]
The spinning icon only spins when the `Sync` command runs, not `Pull` or `Push`.

**Comment by mvgadagi** [comment]
I am working on this bug, But I am not able to reproduce this issue, Kindly confirm again
![image](https://user-images.githubusercontent.com/3121238/41477545-3fcc8914-70e2-11e8-9614-3b1446eac5f1.png)
![image](https://user-images.githubusercontent.com/3121238/41477555-49c3f61e-70e2-11e8-9f02-7512dafcbe69.png)
