### ISSUE TITLE
Feature: Use package.json to save state of extensions 

### ISSUE THREAD

**Issue by jascodes** [microsoft/vscode#51675]
One of extensions have regression so downgrading it and  freezing extension to **specific** version is not possible. I have to freeze all automatic updates and manually find vsix for old version and install it.

**This is hot shit**

My idea is that there is package.json file in global settings of vscode and we use npm dependancies(vscode extension projects) to list the extensions.

- This will reduce developer learning curve for creating extensions.
- One can freeze particular extension version, or auto update minor versions, or major
e.g 
```
{
  "dependencies": {
    "@marketplace/piotrpalarz.vscode-gitignore-generator": "^1.2.2",
    "extension" : "git://github.com/user/extension.git#commit-ish",
    "@marketplace/ms-vscode.cpptools": "2.3.2",
    "jas99/myextension": "~1.1.0", // by default use github
    "@gitlab.com/jas99/myextension": "1.0"
  }
}

```

In addition to that one can also load dependencies/extensions with local package.json file in workspace settings.

Thx

**Comment by sandy081** [comment]
Related https://github.com/Microsoft/vscode/issues/37162

**Comment by sandy081** [comment]
You can downgrade to a specific version by using `Install Another Version...` action on extension. After installing a specific version auto updates on this extension are disabled until you update to the latest manually.

I think this suffice your requirement, hence closing this. If you do not agree please reopen it with explanation.
