### ISSUE TITLE
Python extension does not stop at breakpoints

### ISSUE THREAD

**Issue by shortjonescipher** [Microsoft/vscode#51674]
![capture-1](https://user-images.githubusercontent.com/15865604/41276368-63cd4240-6e67-11e8-9fa5-2546eb910211.png)
Issue Type: <b>Bug</b>

On any Python script, such as 'print("hello world")', the debugger does not stop on any enabled breakpoints, but runs the script until it terminates. The debug configuration is Python: Current File,

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.17GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.5.0

</details>

**Comment by RMacfarlane** [comment]
This issue was moved to Microsoft/vscode-python#1940
