### ISSUE TITLE
Worker postMessage @deprecated

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#51685]
- VSCode Version: 1.24.0
- OS Version: macOS

![image](https://user-images.githubusercontent.com/30043375/41285075-dd2c443e-6e43-11e8-8acf-468e78cc430d.png)

https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage

Why it's deprecated if it isn't?

**Comment by RMacfarlane** [comment]
@bsvipas Where is this interface from?

**Comment by yume-chan** [comment]
1. It has been marked as deprecated for several versions.
https://github.com/Microsoft/TypeScript/blob/v2.9.1/lib/lib.dom.d.ts#L15199
https://github.com/Microsoft/TypeScript/blob/v2.9.1/lib/lib.webworker.d.ts#L1519

2. From this commit:
https://github.com/Microsoft/TypeScript/commit/79e5e79ef7724066889fbce97e9e6d6db4e746b5#diff-0abb36c63a4c22194c1931b03ac33053R1514

3. The reason as stated in Microsoft/TypeScript#23653, is
>The file is auto-generated from the webidl definition of edge. they have marked it as deprecated, and that is why it shows up as such.

4. It has already been fixed and should ship with next TypeScript release.
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts#L2322
