### ISSUE TITLE
TypeScript intelisense- no suggestions for implement all inherited abstract members and methods

### ISSUE THREAD

**Issue by micnyk** [Microsoft/vscode#51686]
Issue Type: <b>Bug</b>

I have some complex abstract class which contains both methods and abstract methods and members.

When I create a class that extends it and implements abstract methods, I got errors that abstract methods are not implemented but not any intelisense hint for auto generating these methods

![errors](https://user-images.githubusercontent.com/13575087/41286015-572b1fae-6e3e-11e8-8019-e996f38e44eb.PNG)
![fix-hint](https://user-images.githubusercontent.com/13575087/41286016-5749e376-6e3e-11e8-8d82-f48e6f679222.PNG)

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-5600K APU with Radeon(tm) HD Graphics    (4 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.94GB (10.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.3.5
tslint|eg2|1.0.30
prettier-vscode|esb|1.5.0
dotnet-test-explorer|for|0.3.0
gc-excelviewer|Gra|2.0.21
csharpextensions|jch|1.3.0
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.6.0
vscode-docker|Pet|0.0.27

</details>

**Comment by mjbvz** [comment]
Please share complete some example code as text. I can't repo this in a simple example:

```js
abstract class Base {
    abstract f();
}

class Sub extends Base {}
```

<img width="596" alt="screen shot 2018-06-12 at 9 52 00 am" src="https://user-images.githubusercontent.com/12821956/41304923-49efb9a2-6e26-11e8-88ed-c08a75ae27f8.png">

**Comment by micnyk** [comment]
@mjbvz 

`import { Action } from 'redux';
import { AsyncActionCreators, actionCreatorFactory, Action as FsaAction, Success, Failure } from 'typescript-fsa';
import { ReducerBuilder } from 'typescript-fsa-reducers';
import { AppDispatch } from 'services';

const actionCreator = actionCreatorFactory();

export abstract class ApiAction<TState, TRequest, TResult> {
  actionCreators: AsyncActionCreators<TRequest, TResult, {}>;

  handlers = {
    started: this.started,
    done: this.done,
    failed: this.failed
  };

  constructor(type: string) {
    this.actionCreators = actionCreator.async<TRequest, TResult>(type);
  }

  buildReducer(builder: ReducerBuilder<TState, TState>): (state: TState, action: Action) => TState {
    return builder
      .caseWithAction(this.actionCreators.started, this.handlers.started)
      .caseWithAction(this.actionCreators.done, this.handlers.done)
      .caseWithAction(this.actionCreators.failed, this.handlers.failed);
  }

  dispatchStarted(dispatch: AppDispatch, request: TRequest) {
    dispatch(this.actionCreators.started(request));
  }

  dispatchDone(dispatch: AppDispatch, request: TRequest, result: TResult, multiTabShare: boolean = false) {
    const success = {
      params: request,
      result: result
    };

    dispatch(this.actionCreators.done(success, { multiTabShare }));
  }

  dispatchFailed(dispatch: AppDispatch, request: TRequest, error: {}) {
    const failed = {
      params: request,
      error: error
    };

    dispatch(this.actionCreators.failed(failed));
  }

  showLoader = true;

  // Should result of action be shared between all opened browser tabs
  abstract multiTabShare: boolean;
  // Actual action that should happen- eg. API call
  abstract run(dispatch: AppDispatch, request: TRequest): void | Promise<TResult>;
  // Action started reducer
  abstract started(state: TState, action: FsaAction<TRequest>): TState;
  // Action done reducer
  abstract done(state: TState, action: FsaAction<Success<TRequest, TResult>>): TState;
  // Action failed reducer
  abstract failed(state: TState, action: FsaAction<Failure<TRequest, {}>>): TState;
}
`

**Comment by mjbvz** [comment]
Thanks but I still can't repo this.

![screen shot 2018-06-13 at 10 31 04 am](https://user-images.githubusercontent.com/12821956/41367788-e6b89604-6ef4-11e8-8198-ccfc2146a9aa.png)

How are you triggering the suggestions? Clicking the lightbulb? Keyboard shortcut?

**Comment by micnyk** [comment]
@mjbvz so any suggestions what can be wrong with my vscode?
Maybe some cache files should I delete?

**Comment by mjbvz** [comment]
Yes. Are you using a custom version of typescript in your workspace?
