### ISSUE TITLE
Unverified breakpoint, Breakpoints set but not yet bound <Node.js>

### ISSUE THREAD

**Issue by reverietito** [Microsoft/vscode#51683]
I'm trying to debug a Node.js application using the 'Debugger for chrome' extension. 

## Expected behaviour
stop the program when it reaches any breakpoint.

## Actual behaviour
does not stop at any breakpoint. the _black breakpoint_ (not a regular red breakpoint) shows message '_Unverified breakpoint, Breakpoints set but not yet bound_'.

## Note
I found [this](https://github.com/Microsoft/vscode-react-native/issues/625) which says VS code 1.24 fixed this issue for React-Native but there is no mention for Node.js 

Here is my _launch.json_
```
"version": "0.2.0",
    "configurations": [
        {
            "name": "Launch localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/src"
        }
    ]
```

- VSCode Version: 1.24
- OS Version: 10.12.6 macOS Sierra
- Node.js Version: 8.11.2 LTS

Steps to Reproduce:

1. Install 'Debugger for chrome' extension in VS code 1.24 and change the launch.json config as mentioned.
2. Try setting a breakpoint on any line that would be hit when the app runs. Run the app in debugger mode from VS code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Yes, you can use the "Debugger for chrome" extension for debugging node.js programs. But then you will have to create a correct launch configuration (i.e. using the correct debug port).
So using "Debugger for chrome" is recommended for debugging the UI running in a web browser.

A much simpler approach is to use VS Code's built-in debugger and a debug configuration like this:
```
"version": "0.2.0",
    "configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch myProgram",
			"program": "${workspaceFolder}/myProgram.js"
		},
    ]
}
```

**Comment by weinand** [comment]
What kind of node.js app do you want to debug?
Do you want to debug the server or the client (running in a browser)?

Is the url `localhost:3000` what you would paste into a web browser to see a Web UI or is this the debug port of your node.js runtime?

**Comment by reverietito** [comment]
Of course I want to debug the server-side.

The node.js app is configured to run on port no. 3000

**Comment by reverietito** [comment]
BTW if I want to put a breakpoint on my client-side code and debug even then the breakpoints are not getting hit. while hovering on the BPs it keeps showing the same message.

**Comment by weinand** [comment]
If you want to debug the server side then you have to run node.js in debug mode.
The simplest way to do this is by using the debug config from above:
```
"version": "0.2.0",
    "configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch myProgram",
			"program": "${workspaceFolder}/myProgram.js"
		},
    ]
}
```

Replace "myProgram.js" by the entry point of your server code.
If you start a debug session with that config, the node debugger will start node in debug mode and will attach to the standard debug port.

Set a breakpoint in your server code.

If you then access your server by pasting "http://localhost:3000" in a browser, the breakpoint should be hit.
