### ISSUE TITLE
Feat: NPMScriptExplorer Tasks should have a restart hotkey

### ISSUE THREAD

**Issue by GeorgeWL** [Microsoft/vscode#51692]
In the past when I was using the terminal instead of the NPM Script Explorer my workflow after a breaking change would be:

* run command on terminal
* terminate with `ctrl`-`c`
* `up arrow`+`enter`
* rerun the task

I'd like the script explorer to have a built-in hotkey or prompt for restarting the task, as well as the usual message.

**Comment by egamma** [comment]
@GeorgeWL the the command to restart the running task already exists (Tasks>Restart Running Task in the menu bar), all you have to do is to assign a key binding to it in the keybindings editor. 

Pls reopen if this doesn´t cover your needs.

![image](https://user-images.githubusercontent.com/172399/41763874-bb2257ca-75ff-11e8-887f-8182d6b65558.png)

**Comment by GeorgeWL** [comment]
tbh, I thought I'd already closed this @egamma I have made a request elsewhere though for a tweak to the behaviour of the Tasks Start/Stop/Restart command if there's only one task to Start/Restart https://github.com/Microsoft/vscode/pull/47853
