### ISSUE TITLE
Workspace symbols throw error if not provided location 

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51695]
In the docs for Workspace Symbol Provider is says:

> To improve performance implementors can skip the location of symbols and implement resolveWorkspaceSymbol to do that later.

But if I do this:

```ts
public async provideWorkspaceSymbols(query: string, token: CancellationToken): Promise<SymbolInformation[]> {
	return [new SymbolInformation("name", SymbolKind.Class, "containerName", null)];
}

public async resolveWorkspaceSymbol(symbol: SymbolInformation, token: CancellationToken): Promise<SymbolInformation> {
	// This never gets called
}
```

I get no symbols listed in the editor and this in the console:

```
ERR Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at Object.from (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:647:478)
	at Object.e.from (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:646:703)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:693:697
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:76:971)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:80:277)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:84)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:523)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:104:13
	at <anonymous>
```

I tried both `null` and `undefined` but got the same. Interestingly the `location` property also isn't marked with a `?` on `SymbolInformation`.

**Comment by DanTup** [comment]
@jrieken maybe broken by this?

https://github.com/Microsoft/vscode/commit/2d05792d35226ca727067413580ab05479862709#diff-00712023721c685fc8697e7bc7e85cb6L70

```
-			&& !this._bearing.range
+			&& !this._bearing.location.range
```

My location is `null`. The docs suggest this is valid, but now I'm not sure if I should be giving a dummy location or something? The location constructor suggests I need to give it a Uri and Range or Position.

Any ideas?

**Comment by jrieken** [comment]
Hm, seems like the comment isn't correct... We never supported omitting the `location` but we allows to omit the `range` property of the location so that we resolve it later. I will correct the comment.

**Comment by DanTup** [comment]
So the correct thing is for me to create a `Location` with a `uri` but without a `range`? Should the range be marked as optional on the class/constructor then?

**Comment by jrieken** [comment]
Yeah, that's the correct thing to do... Yeah, `range` should probably be optional tho it kind of waters down that type. Need some more thinking...

**Comment by DanTup** [comment]
Maybe `location` on the symbol should be something like `Location | Uri`?

I found the API a little weird for another reason - when `resolve` is called, we get given a `SymbolInformation` but that doesn't have the offset/len I'm trying to resolve to a line/column so I have to downcast it. Maybe the provider should be generic over something that extends SymbolInformation so we'd get better typing in the resolve method.

Possibly there aren't many users of this API though, so it might be unwarranted complexity! It's currently the only way to get an accurate range if your language server is offset/len though and you need to `openTextDocument` to resolve the location.

**Comment by jrieken** [comment]
I have pushed a change to the comments. Not planning further changes right now, but there is the idea of deprecating `SymbolInformation` and have a new type `WorkspaceSymbol` similar to the new type `DocumentSymbol`
