### ISSUE TITLE
Same User, Multiple Sessions, Instance collision

### ISSUE THREAD

**Issue by markbaillie** [Microsoft/vscode#5169]
- VSCode Version: 0.10.11
- OS Version: Server 2012 R2 6.3 Build 9600

Steps to Reproduce:

1. Open an RDP session to a server
2. Launch code via opening a file
3. Open another RDP session to a server as the same user
4. Launch code via opening a different file 

The file will open on the already first user session instance of code

**Comment by bpasero** [comment]
@markbaillie can you pass in `-n` to the Code launch to force opening a new instance? Did you maybe configure the setting `window.openFilesInNewWindow` to true?
