### ISSUE TITLE
Default behaviour of the Terminate/Restart Current Task if only one task to choose that task automatically

### ISSUE THREAD

**Issue by GeorgeWL** [Microsoft/vscode#51699]
If one were to run `workbench.actions.tasks.terminate` or `workbench.actions.tasks.restart` after setting a custom keybinding for them, the UI will always prompt for the user to choose which tasks to restart/terminate.

This is great if there's multiple tasks running. But if there's only one task running then it can be a major annoyance and slow down your workflow.

I propose that the behaviour can be set (with a workbench setting) to select the only running item by default if there's no other running tasks. (A naive tasks.length == 1 check would do it or something like that?)

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/pull/47853.

**Comment by Gama11** [comment]
I ended up implementing a workaround using the new tasks API:

https://marketplace.visualstudio.com/items?itemName=vshaxe.terminator

**Comment by GeorgeWL** [comment]
that's not really related to this issue at all...it does get rid of the popup I suppose, which is another unrelated issue. @Gama11

**Comment by Gama11** [comment]
Yeah, I suppose you're right. It's a bit different, but still related. :)
