### ISSUE TITLE
Solution Explorer

### ISSUE THREAD

**Issue by PandaMakesCode** [Microsoft/vscode#51702]
Issue Type: <b>Bug</b>

Where is solution explorer???
I have looked at over 20 microsoft websites that say "Open Solution Explorer" without telling you where it is or how to do it.
One said to go to View -> Pads -> Solution Explorer, but i could get to view. There is no pads in View

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3250 @ 3.20GHz (2 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (4.09GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nextgenas|bow|0.12.0
open-html-in-browser|cod|0.1.21
vscode-eslint|dba|1.4.12
xml|Dot|2.3.0
vscode-gitignore-syntax|dun|0.1.2
vscode-npm-script|eg2|0.3.4
vscode-opn|lfu|1.1.2
python|ms-|2018.5.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.82
Ruby|reb|0.18.0
java|red|0.26.0
stylelint|shi|0.36.3

</details>

**Comment by V-ed** [comment]
`Visual Studio` and `Visual Studio Code` are two very different products.

I guess that's that you are searching about as I found [this thread](https://developercommunity.visualstudio.com/content/problem/151680/where-is-the-solution-explorer.html) that mentions your "View -> Pads -> Solution Explorer".

There is no "Solution Explorer" builtin into VSCode, but you can get one using the [vscode-solution-explorer](https://marketplace.visualstudio.com/items?itemName=fernandoescolar.vscode-solution-explorer) extension.

When looking online for solutions to problems related to `Visual Studio Code` (this repository), prepend your searches with "`vscode`", that might help for the future!

**Comment by PandaMakesCode** [comment]
Is there a reference explorer?

**Comment by RMacfarlane** [comment]
@PandaMakesCode `Visual Studio Code` is a written as a lightweight editor, so something like a solution or reference explorer isn't in the base product, but could be added by an extension. Thanks @V-ed for the explanation and suggestion of [vscode-solution-explorer](https://marketplace.visualstudio.com/items?itemName=fernandoescolar.vscode-solution-explorer) extension.

We use our GitHub issues to track bugs, so we would appreciate it if you directed questions to https://stackoverflow.com/questions/tagged/vscode. Thank you!
