### ISSUE TITLE
Find dialog loses focus on history navigation

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/vscode#51707]
Issue Type: <b>Bug</b>

I did change find history navigation shortcut to `cmd + ↓`. After that find dialog just loses focus after first trigger of that shortcut.

VS Code version: Code 1.24.1 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
vscode-color|ans|0.4.5
snapshot-tools|asv|0.0.7
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.30
beautify|Hoo|1.3.1
vscode-styled-components|jpo|0.0.18
atom-keybindings|ms-|3.0.4
vscode-icons|rob|7.23.0
code-settings-sync|Sha|2.9.2
language-stylus|sys|1.9.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
We check `CMD+Arrow` explicitly in Find Widget somehow, which always gives the control back to the editor.

**Comment by Ky6uk** [comment]
in VSCode version `v1.25.0` find/replace dialog now more convenient than before. Using pure `Arrow` keys are great for using!
