### ISSUE TITLE
Can't add predefined launch configurations with the menu to an existing launch.json file

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#5170]
A user reported this issue to us: https://github.com/Microsoft/vscode-react-native/issues/208
While trying to add a predefined launch configuration to an existing launch.json, the button doesn't work as we'd expect it to work.

I think it'd make sense to have a way to add a predefined launch configuration to an existing launch.json file.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/478
