### ISSUE TITLE
Collapse open button [-] not showed

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/vscode#51705]
- VSCode Version: Versione 1.24.0 (1.24.0) - 6a6e02cef0f2122ee1469765b704faf5d0e0d859
- OS Version: High Sierra 10.13.4

Steps to Reproduce:

1. Open a huge JavaScript files with classes and functions
2. Collapse all functions with the [-] collapse button.
3. Open the file again
4. The functions will keep the collapsed state, but not [+/-] collapse button is present, so it is not possibile to open the collapsed functions with the [+] button.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share some example code that demonstrates this issue

**Comment by loretoparisi** [comment]
@mjbvz cannot share that exact code since it proprietary, but I can find a use case of other code. I can add that I often use this feature, so I typically have

1) 2000-3000 lines javascript files
2) all functions collapsed with [-] button
3) when I open these files since the last update (Referred above) I cannot see the [+] button.

I will try to reproduce this issue with some open source code file.

**Comment by mjbvz** [comment]
If you wait, do the expand buttons ever appear?

**Comment by loretoparisi** [comment]
@mjbvz so I have found that the buttons are not displayed, but they actual are in position and ...working! Without being displayed correctly. So basically the `hover` on the button does not work properly, because the button works.

**Comment by mjbvz** [comment]
I've tried this in the latest vscode insiders with large JS files but have not been able to reproduce the issue.

@loretoparisi Do you see this in VS Code insiders? If you find an open source file that you can share it would also help us investigate this

**Comment by loretoparisi** [comment]
@mjbvz let me try to show you in some way.

**Comment by mjbvz** [comment]
Closing as not reproducible in latest insiders. @loretoparisi If you are still seeing this issue, please share an example file. It doesn't even have to be semantically valid code
