### ISSUE TITLE
I have 'the notorious' black screen issue

### ISSUE THREAD

**Issue by Babzaveli** [Microsoft/vscode#51701]
Hey Everyone,

When I start VS Code I get the black screen that everyone else gets. I know the solution is to run VS Code using "code --disable-gpu". However, the problem, I have is that I do not actually know how to 'run VS Code using "code --disable-gpu". I know this is quite an ask but could anyone please explain to me the steps I need to take.

I have also tried to put VS Code into Zen Mode (Ctrl+K Z); however the only change is that VS Code changes from a maximised window that is blank to a full screen window that is blank.

Specifications:

- VSCode Version: 1.24.0
- OS Version: Windows 10

Steps to Reproduce:

1. Download VS Code
2. Open it
3. Get a black/blank screen
4. Don't know what to do next??

Reproduces with extensions: Don't know because I can't get extensions, however i reckon it will still be the same

**Comment by Babzaveli** [comment]
I have pasted an image of what VS Code looks like when I open it

![image](https://user-images.githubusercontent.com/40207197/41298066-7c4eb2fe-6e58-11e8-9fbc-7065138a47cd.png)

**Comment by V-ed** [comment]
Here's `how to 'run VS Code using "code --disable-gpu"` :

Open a command prompt in Windows (_`Windows Key + r`, and type `cmd` in the box that opens_), then type the command you've talked about : `code --disable-gpu`.

Also, if this doesn't work, refer yourself to [this comment](https://github.com/Microsoft/vscode/issues/15211#issuecomment-350971070) for another way of fixing this issue (that comment talks about the shortcut of vscode, for your information).

**Comment by Babzaveli** [comment]
@V-ed Thank you so much, it works perfectly for me now. Thanks again for helping out a fellow noob :)

**Comment by V-ed** [comment]
No problems!

You might want to close this issue now that your problem is fixed! ;)
