### ISSUE TITLE
hideByDefault property on the IViewDescriptor isnt honored

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#51713]
From what I could see, the property called `hideByDefault` on the `IViewDescriptor` was introduced in 1.24.0 with https://github.com/Microsoft/vscode/commit/b97a811afd8edccbb7e785bd5815acab93ae2734.

But in master, today, it isnt used anywhere.

Post the work done in #47766, I was looking to change what views are shown by default in the Extensions view. I assumed setting `hideByDefault` would do the trick, but it doesnt.

We should bring this feature back such that
- Any new view with this property set should be hidden by default.
- An existing view with this property set should be hidden by default unless the user has chosen to show it explicitly

**Comment by sandy081** [comment]
@ramya-rao-a It was broken while adopting to custom views model. Will fix it.

**Comment by ramya-rao-a** [comment]
@sandy081 I can confirm that the `hideByDefault` property works as expected for new views. But they do not work for existing views.

I believe this is because we store the hidden state (true or false) for each view.
But this hidden state doesn't tell us if its hidden because VS Code decided to do so or the user decided to do so.

I would suggest the below
- Include another property "hiddenByUser" in the view state that we store in the local storage
- If `!hiddenByUser && hideByDefault` then hide the view

**Comment by sandy081** [comment]
@ramya-rao-a What do you expect if the user makes the view visible ?

**Comment by ramya-rao-a** [comment]
Then it should stay visible regardless of the `hideByDefault` property.

**Comment by ramya-rao-a** [comment]
As discussed offline, `hideByDefault` only applies to newly created views for now
