### ISSUE TITLE
Outline in Perl fails to link back to file/line

### ISSUE THREAD

**Issue by vphantom** [Microsoft/vscode#51715]
Issue Type: <b>Bug</b>

I had success using the new Outline view with a JavaScript file.  However when editing a Perl file:

* Hovering over any symbol in the outline shows a tool-tip like "line 519 of null". The line number is correct, but it seems to lose the notion of file.

* Clicking on any symbol opens a new, empty window entitled "Untitled-1" instead of scrolling to the correct line of the current file.

* I disabled the `henriiik.vscode-perl` extension and subsequently had nothing in Outline so there's a relationship there, but that still doesn't tell me if this is a vscode or extension issue.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.9.0-0.bpo.2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3868)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.57GB (2.10GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.0
output-colorizer|IBM|0.1.2
vscode-docker|Pet|0.0.27
thrift|cdu|0.0.1
vscode-eslint|dba|1.4.12
gitlens|eam|8.3.5
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.5.0
php-debug|fel|1.12.3
php-intellisense|fel|2.3.2
php-pack|fel|1.0.1
code-runner|for|0.9.3
reasonml|fre|1.0.37
vscode-perl|hen|1.14.4
auto-comment-blocks|kev|1.0.1
vscode-apache|mrm|1.1.1
vscode-code-outline|pat|0.2.1
tt|sam|0.0.4
vscode-nginx|sha|0.5.0
trailing-spaces|sha|0.2.11
rewrap|stk|1.9.1
html-mason|via|1.0.0
markdown-all-in-one|yzh|1.4.0
vscode-proto3|zxh|0.2.1

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
Thanks for reporting! The Outline view exposed a new API for extensions to use but didn't add support for it for all languages - the JavaScript support is from an extension that's built in to VS Code. So for Perl it it coming from the `vscode-perl` extension. Please open this issue there.
