### ISSUE TITLE
Move between search fields and results with cursor keys

### ISSUE THREAD

**Issue by lmartins** [Microsoft/vscode#51711]
Issue Type: <b>Bug</b>

Hi!

I've noticed that the last couple of builds have disabled this feature where you could navigate from the search fields into the search results box using only the keyboard.

Any chance this could be brought back?

VS Code version: Code - Insiders 1.25.0-insider (fa7ded2f007be6ae288b29392501f3dc34105abd, 2018-06-12T08:15:14.394Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|40.00GB (0.38GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-simple-icons|Lau|1.8.3
code-settings-sync|Sha|2.9.2
html-css-class-completion|Zig|1.17.1
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|0.19.1
alignment|ann|0.3.0
vscode-mjml|att|1.3.0
vscode-twig-pack|baj|1.0.0
vscode-intelephense-client|bme|0.8.8
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
laravel-goto-view|cod|1.2.0
bracket-pair-colorizer|Coe|1.0.58
vscode-simpler-icons|dav|1.5.2
vscode-eslint|dba|1.4.12
vscode-quick-select|dba|0.2.5
vscode-dash|dee|1.10.0
mjml-syntax|dig|0.0.1
gitlens|eam|8.3.5
vsc-material-theme|Equ|2.1.0
prettier-vscode|esb|1.5.0
php-debug|fel|1.12.3
php-file-types|fet|1.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
referenceshelper|gay|0.2.2
vscode-flatland-icon-theme|geb|0.0.6
html-tag-wrapper|hwe|0.2.3
code-select-until|jak|0.6.0
vscode-liquid-snippets|kil|1.1.0
graphql-for-vscode|kum|1.12.0
php-symbols|lin|2.1.0
vue|liu|0.1.5
php-namespace-resolver|Meh|1.0.9
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.8
vsliveshare|ms-|0.3.264
debugger-for-chrome|msj|4.6.0
trailing-semicolon|nau|1.0.2
language-liquid|nei|0.0.3
vetur|oct|0.12.5
laravel-blade|one|1.18.0
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.5.0
LiveServer|rit|4.1.0
laravel-artisan|rya|0.0.20
laravel-5-snippets|sac|2.0.1
vscode-fileutils|sle|2.9.0
ayu|tea|0.14.0
wordpress-snippet|tun|1.1.2
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.7.1
change-case|wma|1.0.0
ReactSnippets|xab|2.1.0

(18 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
This was due to the change of defaults

Default shortcuts for History navigation in the input boxes are Up and Down arrows
Default shortcuts for navigating among input boxes are cmd+Up Arrow and cmd+Down Arrow
Change was done because of #12645. This made all our history navigation to be consistent and use Up and Down arrows.

You can always change the behaviour back by updating the keybindings to the following commands

Search Inputs navigation commands: search.focus.nextInputBox and search.focus.previousInputBox

Input history navigation commands: history.showPrevious and history.showNext

**Comment by lmartins** [comment]
Ah cool, thanks @sandy081  CMD+arrows works for me, thanks!
