### ISSUE TITLE
Updates: It's OK to remove the prompt asking if I want to install updates to VSCode in the background. Seriously, one less thing to think about.

### ISSUE THREAD

**Issue by kpacquer** [Microsoft/vscode#51714]
When I start VSCode and there's an update, it asks me if I want the update, and tells me it can do this in the background. Why not just do this in the background?

Note, once the update is ready, the following prompt is just fine. It currently asks if I want to apply the update. However, if you remove the first prompt, you may need to tweak this wording of the install prompt. "We've installed an update to Visual Studio Code. Want to try it now? We'll hold your tabs open for you. [Yes, let's try it!] [No, keep working] [Release notes]" or something to that effect

**Comment by RMacfarlane** [comment]
@kpacquer It looks like there is already an issue tracking this: https://github.com/Microsoft/vscode/issues/9539

Please go give it a thumbs up! Closing this as a duplicate.
