### ISSUE TITLE
Add a Search Everywhere Dialog

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/vscode#51718]
Similar to ctrl-t, ctrl-p, etc... I'd love to see a search everywhere dialog that searches for files **and** symbols throughout my project at the same time.  This is very similar to the jetbrains double-shift dialog.

It's helpful when I know a name I've seen, but am not sure if it's a symbol in a module/file or if it's part of the name of the file itself.

Results are handled and prioritized asynchronously.

![image](https://user-images.githubusercontent.com/115199/41310759-13c62506-6e48-11e8-8c77-a4e2d97ffa69.png)

**Comment by roblourens** [comment]
This is exactly what the setting `"search.quickOpen.includeSymbols": true` enables, try that out.
