### ISSUE TITLE
Need ability to copy warning or error messages in modal dialogs on macOS

### ISSUE THREAD

**Issue by ldesegur** [Microsoft/vscode#51712]
Every dialog has something useful to offer. Just writing it and asking the developer to rewrite it (path to a github repo, name of package to install, etc.) should be a simple matter or copy/paste. Not so if you don't give this ability to the user.

Dialogs on MacOS applications have long being able to offer this functionality. It's in the toolbox, just not expose to the UI on VSCode apparently.

**Comment by bpasero** [comment]
> Dialogs on MacOS applications have long being able to offer this functionality.

Can you give an example where this currently does not work in VSCode?
