### ISSUE TITLE
Implementing an interface via quick actions fails in VSCode 1.24

### ISSUE THREAD

**Issue by ScottMorris** [Microsoft/vscode#51719]
I just ran into an issue where when I try to implement an interface using the auto complete in VSCode 1.24 it barfs!  It opens a separate file with the [name of the class].ts and mangles the autofill of the interface.

When I downgrade back to version 1.23 everything works as intended.

- VSCode Version: 1.24
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Write a simple class definition that implements an interface
2. Use the Implement Interface auto function
3. Chaos ensues.

**Comment by mjbvz** [comment]
Please test this in VS Code insiders. Share some example code if it still doesn't work

**Comment by ScottMorris** [comment]
I just tried the latest VSCode Insider Build.  It has a slightly different issue.  It implements the interface properly but still opens a new tab with the name of file, with a capital letter as the first letter.

test.ts → test.ts + Test.ts

I'll write up a code sample when I get home this evening that reproduces this.

This is the version of VSCode Insiders I'm using
![image](https://user-images.githubusercontent.com/404967/41321842-cc4b3672-6e73-11e8-944e-d8161cfe1524.png)

**Comment by ScottMorris** [comment]
I've written some examples.  When I try and reproduce the duplicate file in a different tab with a capital letter as the first letter of the file name I can't seem to get that to work.  But when I try and impiment the interfaces within a new class things break.  I've attached a zip file here with a few examples and comments that hopefully help with this issue.  Here are some code samples.

`iDataSource.ts`
```typescript
export interface IDataSource {
    init();
    get();
    set();
}
```
`sampleDataSource.ts`
```typescript
import { IDataSource } from "./iDataSource";

// When I hit "Impement interface 'IDataSource'"" it adds the init, get and set methods, but puts 
// the second method on the wrong line.  When I remove init, it also puts the second method on
// the wrong line.
export class SampleDataSource implements IDataSource {
    // With init()
    init() {
        throw new Error("Method not implemented.");
    }    get() {
        throw new Error("Method not implemented.");
    }
    set() {
        throw new Error("Method not implemented.");
    }

    // Without init()
    // get() {
    //     throw new Error("Method not implemented.");
    // }    set() {
    //     throw new Error("Method not implemented.");
    // }
}
```

Even a very simple example of this interface causes the malformation.

![idatasource](https://user-images.githubusercontent.com/404967/41329210-42d03bc8-6e9a-11e8-9974-828ee2ef20b4.png)

When I add in a property to the interface things get weird and it only adds the property without the methods.

`iDataSource2.ts`
```typescript
import { Person } from "../person";

export interface IDataSource2 {
    state: any;
    get(): Promise<Person>;
    set(): Promise<Person>;
}
```

`sampleDataSouce2.ts`
```typescript
import { IDataSource2 } from "./iDataSource2";

// When I hit "Impement interface 'IDataSource2'"" it only adds the state property and complains:
// Class 'SampleDataSource2' incorrectly implements interface 'IDataSource2'.
//    Property 'get' is missing in type 'SampleDataSource2'.
export class SampleDataSource2 implements IDataSource2 {
    state: any;



}
```

There is a third example but it is a lot longer and I don't want to take up too much space, it is contained within the sample zip file.

Check out the complete code samples here: [interface-example.zip](https://github.com/Microsoft/vscode/files/2096540/interface-example.zip).

**Comment by ScottMorris** [comment]
I've tried to isolate what caused the capitalisation issues I was experiencing, but they don't seem to happen in my current version of VSCode Insiders.  The odd thing was when I changed the name of the `.ts` file from starting with an `a` to a `b` it stopped capitalising the first letter.

**Comment by mjbvz** [comment]
Thanks for the example code. I've opened https://github.com/Microsoft/TypeScript/issues/24977 to track this issue upstream
