### ISSUE TITLE
Implement interface snippet does not show.

### ISSUE THREAD

**Issue by OttoChamo** [Microsoft/vscode#51717]
So, I was configuring my project to work with typescript, when after creating tsconfig.json and eslint.json files, after creating a simple interface and trying to implement it in a class suddenly I notice that the yellow bulb appears but only with the option of moving my class to another file but no the implement snippet, What Am I doing wrong?

I already installed tslint extension, tried reloading and disabling and nothing works.

**Comment by mjbvz** [comment]
Is there a red squiggly indicating that the interface is not implemented properly? Please share some example code

**Comment by OttoChamo** [comment]
Yeah.

Here is my Example code.
```
export interface IExample {
     add(data: any): void;
     delete(id: number): void
}
```
And a Class that implements it.

```
export class SampleClase implements IExample {
}
```
After that, the yellow bulb that suggests to implement all the methods does not appear.

**Comment by mjbvz** [comment]
I'm unable to repo this. Can you please test that example in the latest vscode build
