### ISSUE TITLE
Make it easier to distinguish between multiple VS Code windows

### ISSUE THREAD

**Issue by jrnail23** [Microsoft/vscode#51710]
Sometimes I work with different projects in separate VS Code windows/instances at the same time, and I'd really like a way to more easily tell those windows apart.
I was thinking something like setting a color theme or maybe even just something as simple as the color of the status bar at the bottom as a per project (folder) setting.  Come to think of it, something along the lines of the latter would be most preferable, since themes are like religion to a lot of devs!

**Comment by RMacfarlane** [comment]
Thanks for the feature request! There is an existing feature to set themes per workspace (ie project), which you can do by adding something like `"workbench.colorTheme": "Quiet Light"` to your workspace settings.

Currently, we change the status bar color based on whether or not you are in debug mode, so it might be better to allow changing something else like the menu bar color. (This is something someone else suggested :) https://github.com/Microsoft/vscode/issues/22634) See also https://github.com/Microsoft/vscode/issues/16363

I'm going to close this as a duplicate, please go thumbs up the other issue!

**Comment by jrnail23** [comment]
in case anyone else comes across this issue, the following (in my workspace settings file) did exactly what I wanted:
```json
{
	"workbench.colorCustomizations": {
		"statusBar.background": "#666666",
		"sideBar.background": "#444444"
	}
}
```
Here are the docs for those color customizations: https://code.visualstudio.com/docs/getstarted/theme-color-reference
