### ISSUE TITLE
Run Task... fuzzy match quick pick performance degrades with a large number of tasks

### ISSUE THREAD

**Issue by devkarr** [Microsoft/vscode#51723]
Issue Type: <b>Bug</b>

I am working on a large code base that uses a script to auto-generate many build and test targets.  I am creating an extension that will create new tasks from this large target list.  The extension is based on the `task-provider-sample` in the vscode-extension-samples.

The generated task list is well over 5000 entries and the performance of the fuzzy matcher in the `Run Task...`quick pick is too slow -- the system freezes for several seconds after the first key press.

The `Go to File...` fuzzy match quick pick does not seem to have this problem.

My current work around is to filter the original target list but I would prefer not to.  Can this be fixed?

VS Code version: Code 1.22.2 (ff9c0981d7cd3dd319dbb888673d2fc6f8fa09e5, 2018-06-07T19:05:04.178Z)
OS version: Darwin x64 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.83GB free)|
|Process Argv|/Applications/Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
tslint|eg2|1.0.30
json-tools|eri|1.0.2
fuzzysearch|gay|0.2.1
sublime-keybindings|ms-|4.0.0
shellcheck|tim|0.5.1
lodash-snippets|tom|1.0.0
vscode-lldb|vad|0.8.8
cmake-tools|vec|1.0.1

</details>

**Comment by dbaeumer** [comment]
I profiled this and it clearly looks like a dup of: https://github.com/Microsoft/vscode/issues/18180
