### ISSUE TITLE
Outline view does not work/support Scala

### ISSUE THREAD

**Issue by fmerici** [Microsoft/vscode#51720]
Issue: Outline feature added in #49917 does not show a tree view for Scala scripts
- The OUTLINE view displays this message __`There are no editors open that can provide outline information.`__

- VSCode Version: Version 1.24.0 (1.24.0)
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Open a Scala file
2. Right click on OPEN EDITORS in the explorer view and check 'Outline

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@fmerici Thanks for reporting! The outline feature added the API for different extensions to create an outline, but didn't automatically add support for this for all languages. This should be implemented in a Scala extension. It looks like the most popular Scala extension is not yet using it, but you could add a feature request there: https://github.com/dragos/dragos-vscode-scala
