### ISSUE TITLE
Tab inside snippet doesn't trigger suggestion

### ISSUE THREAD

**Issue by kevva** [Microsoft/vscode#51722]
Since a couple of days back, triggering a suggestion using tab inside a snippet doesn't work anymore if the snippet has multiple steps. This has always worked before so it seems like a regression to me. It works if I use the enter key though.

![kapture 2018-06-12 at 21 48 12](https://user-images.githubusercontent.com/709159/41313495-5bf0e388-6e8a-11e8-833d-fe34385ff828.gif)

This could be related to #51142, but when running VSCode without any extensions enabled, the problem still persists:

![kapture 2018-06-12 at 21 51 20](https://user-images.githubusercontent.com/709159/41313700-e9ca6896-6e8a-11e8-85e6-2bc4329b923d.gif)

- VSCode Version: Version 1.25.0-insider
- OS Version: macOS High Sierra 10.13.1

Steps to Reproduce:

1. Inside a snippet, trigger a suggestion by typing a variable or likewise, and then press tab.
2. If the snippet has multiple "steps", it will then ignore the suggestion and move to the next step instead.

**Comment by JeanMertz** [comment]
Experiencing the same problem right now. Using Code Insiders, when I autocomplete a function signature, the cursor jumps to the first argument, if I now type a few letters and then hit `tab` to autocomplete the suggestion that is given to me, the suggestion is not completed, and instead the cursor moves to the next field in the function signature.

**Comment by jrieken** [comment]
Yeah, we have done that via https://github.com//Microsoft/vscode/issues/50776. There is a group of people that really dislike this behaviour and we have pushed a change to disable `tab` as accept character when in snippet mode (which also aligned it with the tab-completion behaviour). 

I'd reckon we keep this for more feedback and decide towards the end of the milestone what to do. To restore the old behaviour, add this to your `keybindings.json`-file

```json
{
        "command": "acceptSelectedSuggestion",
        "key": "tab",
        "when": "suggestWidgetVisible && textInputFocus"
}
```

**Comment by jrieken** [comment]
We have reverted the changes for #50776 which closes this issue. We will revisit in July
