### ISSUE TITLE
[bug] on 32bit Win7 : notification appears for 64bit VS Code

### ISSUE THREAD

**Issue by dreamflow** [Microsoft/vscode#51726]
bug description :
on 32bit Win7 : VS Code shows the notification that the 64bit version
of VS Code is available . but this doesn't make sense , because the
64bit version cannot be installed nor ran on a 32bit Windows OS .
the problem is also that this notification cannot be deactivated .

![vs code - 64bit availability notification on 32bit win7](https://user-images.githubusercontent.com/13277579/41316343-64853604-6e92-11e8-94e9-e411e81a1ed9.png)

expectation :
this notification should only appear if the 32bit version of VS Code
is run on a 64bit Windows OS . or  at least it should be possibel to
deactivate this specific notification .

Please search existing issues to avoid creating duplicates : done , nothing found .

- VSCode Version: 1.24.0
- OS Version: Win7 Ultimate SP1 32bit

Steps to Reproduce:
run the 32bit version of the latest VS Code on a 32bit Windows OS

Does this issue occur when all extensions are disabled?: yes

**Comment by joaomoreno** [comment]
I wouldn't worry too much about this. Simply click `Don't show again`.

**Comment by dreamflow** [comment]
before i have clicked on the X that appears when hovering
on the right end of the notification rectangle . but that removed
this notification only temprorary till the next VSCode session .

with your sollution this notification is now entirely gone .
thank you !
