### ISSUE TITLE
Comparing old revisions in Git is not straightforward.

### ISSUE THREAD

**Issue by fssrepository** [Microsoft/vscode#51728]
The interface is very hard to use, and not comfortable, when i want to switch between revisions to try out, or just compare them together. Used latest Ubuntu and 1.24.0 VS Code.

1) Embedded terminal window needs a button somewhere instead of ctrl+shift+P
2) I think right mouse click should be enough for "select this commit for compare" -what is "this"? As it's not the highlighted one, just where you have clicked on compare, which can be a totally different one.
3) In embedded terminal git soft reset does not do file change, so it does not trigger automatic build. (like in the case of ng serve)
4) Switching horizontal to vertical tab (terminal window) - switch button disappears (no room for display), so it needs some time to figure out to enlarge the window horizontally to move back, wherever it was.

The whole thing was totally confusing to me, and deviated my focus. I feared that i will screw my workspace, i was not confident at all.

**Comment by RMacfarlane** [comment]
@fssrepository This sounds like it's describing UI added by the githistory or gitlens extensions - could you please report it on the extension?
