### ISSUE TITLE
Prevent accidentally staging or unstaging files when commit is in progress

### ISSUE THREAD

**Issue by sekhavati** [microsoft/vscode#51721]
- VSCode Version: 1.24.0
- OS Version: macOS High Sierra 10.13.5
- Source Control: Git

### Description:

Files are able to be staged/unstaged even if a commit is currently in progress. This can lead to accidental file commits or the opposite (accidentally removing a file from a commit). 

I did not expect to be able to change the set of the files once a commit has been initiated and assumed any subsequent stages would be queued for a future commit or perhaps it would be possible to disable the stage/unstage buttons when a commit is running?

### Steps to Reproduce:

1. Have multiple files changes in your repo
2. Stage one of these files
3. Enter a message and and press Cmd+Enter to commit
4. Stage another file whilst step (3) is still running 

### Result
The file staged in step 4 is now included as part of the commit initiated in step 3. **Step 3 may take a while, for example if automatic code formatting or unit tests are run as a pre-commit hook.**

**Comment by sstern6** [comment]
Found this issue with a long precommit hook.  Is this something the community is looking for?  I dont mind taking a swing at a PR.  @joaomoreno

**Comment by joaomoreno** [comment]
@sstern6 Sure. The git extension already has the notion of which operations are currently running. If a staging operation happens during a commit, there are a few options (by my order of preference):

1. Attempt to execute them after the commit completes
2. Ignore them
3. Report a warning/error that the action cannot run

**Comment by sstern6** [comment]
@joaomoreno thanks!  I think ill take a swing at 1, do you have ref off the top of your head to a starting point file i can look at?

Thanks

**Comment by joaomoreno** [comment]
Definitely https://github.com/Microsoft/vscode/blob/4fa62b246c4305b4ca00507551f77c58135ce928/extensions/git/src/repository.ts#L665

**Comment by sekhavati** [comment]
I've also since noticed that the commit message field remains editable whilst a commit is in progress. I think it'd be a good idea to disable it for the duration.

**Comment by sstern6** [comment]
Great catch @sekhavati

**Comment by gfting** [comment]
Hello! I'm interested in working on this issue if it's still live.

**Comment by gfting** [comment]
@joaomoreno bump on this: still need help?

**Comment by sstern6** [comment]
go for it!

**Comment by richardhuf84** [comment]
Would be keen to see a solution for this issue.

**Comment by lszomoru** [comment]
This has now been addressed as most commands contributed by the git extension are disabled while the commit operation is running. And so is the commit input field. Please give it a try with the latest Insiders release and let me know if you see anything unexpected. Thank you!
