### ISSUE TITLE
Bash memory leak

### ISSUE THREAD

**Issue by thebillkidy** [Microsoft/vscode#51724]
Issue Type: <b>Performance Issue</b>

Windows: Whenever I am using the Bash terminal now in vscode I am getting slowness over time. Currently after 1h of running my task manager is saying 14% CPU usage

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17686

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (6.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    89	  7588	code main
    1	    76	  8892	   shared-process
    0	   221	 14868	   window (index.js - Untitled (Workspace) - Visual Studio Code)
    0	   107	  3208	     extensionHost
    0	    19	  4404	       electron_node tslintServer.js 
    0	    19	 13296	       electron_node htmlServerMain.js 
    0	    23	 14544	       C:\Users\Nutzer\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.264\dotnet_modules\vsls-agent.exe --autoexit --pipe afb65d1b386442bfb0c1918d82e14c03 --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	     5	 16600	         console-window-host (Windows internal process)
    0	    22	 16700	       electron_node server.js 
    0	    19	 21276	       electron_node eslintServer.js 
    0	    24	 21420	       electron_node electronForkStart.js tsserver.js 
    0	    18	 12824	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    17	  8936	     searchService
    0	    10	 13288	     electron-crash-reporter
    0	    18	 16840	     terminal
    0	     5	  8108	       winpty-process
    0	     4	 10084	         C:\WINDOWS\System32\bash.exe
    0	     4	 18272	           C:\WINDOWS\System32\lxss\wslhost.exe {d11528ee-a20d-4bc9-8e58-7c15e73264f6} 468 476 480
    0	     6	 19912	             console-window-host (Windows internal process)
    0	    10	 10536	         console-window-host (Windows internal process)
    0	    18	 20132	     watcherService
    0	    77	 15620	   gpu-process
    0	    66	 16124	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js - Untitled (Workspace) - Visual Studio Code)
|    Folder (Blog): 745 files
|      File types: jpg(215) html(149) png(139) md(74) js(39) pdf(22) mp3(18)
|                  css(15) ejs(8) svg(8)
|      Conf files: gulp.js(1) package.json(1) launch.json(1)
|    Folder (MyProjects): 1695 files
|      File types: json(419) dll(205) js(148) py(127) jpg(94) xml(79) pdf(76)
|                  txt(74) pyc(41) cs(37)
|      Conf files: package.json(28) csproj(7) launch.json(2) sln(2)
|                  tsconfig.json(2) tslint.json(2) webpack.config.js(2)
|                  makefile(2) tasks.json(1) gulp.js(1);
```

</details>
<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.30
json-tools|eri|1.0.2
code-runner|for|0.9.3
mdmath|goe|2.2.1
gc-excelviewer|Gra|2.0.21
ftp-simple|hum|0.6.4
graphql-for-vscode|kum|1.12.0
ftp-sync|luk|0.3.3
vscode-azurefunctions|ms-|0.9.1
mssql|ms-|1.3.1
python|ms-|2018.5.0
azure-account|ms-|0.4.0
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
vsliveshare|ms-|0.3.264
vscode-docker|Pet|0.0.27
polacode|pnp|0.2.2
LiveServer|rit|4.1.0
vscode-icons|rob|7.23.0
code-spell-checker|str|1.6.10
quokka-vscode|Wal|1.0.130
vscode-proto3|zxh|0.2.1

</details>

**Comment by Tyriar** [comment]
The process information in the expandable section says only the shared process was using 1% CPU at the time?

**Comment by thebillkidy** [comment]
Could it be related to WSL Bash itself? I saw that the process was using the Bash file in the Ubuntu windows store installation. Where should I open this issue then? (because then it's most likely not related to VSCode but to WSL)

**Comment by Tyriar** [comment]
So bash is idle and it's consuming that much? Can you try use process explorer to capture the process tree causing issues? That should help identify what's to blame.

**Comment by thebillkidy** [comment]
Hi Tyriar,

So currently I replicated it by just doing a big console spam in vscode itself where I get the following result from:

![image](https://user-images.githubusercontent.com/591282/41398405-86598246-6fb7-11e8-81db-b6cbdda8c1b1.png)

I also created a dump from the conhost, which you can find here: https://mega.nz/#!DzhRwRwb!0OI9hBcpZSUTm8PluNiixLYlhkUPXU-UnpFlOjQmRro

Does this help?

**Comment by Tyriar** [comment]
@thebillkidy is it possible to show the "command line" as a column in task manager? Otherwise this tool lets you do it https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer, this would tell us more about what console window host is doing.

**Comment by thebillkidy** [comment]
This is what I got:

![image](https://user-images.githubusercontent.com/591282/41402987-0457e852-6fc4-11e8-8f77-b525adbd9859.png)

So it's being launched from the WSL... I'm really suspecting a WSL bug here

**Comment by Tyriar** [comment]
Let's see what happens in https://github.com/Microsoft/WSL/issues/3299
