### ISSUE TITLE
While editing a Json type file, every time it saves, the cursor goes to the end of the file.

### ISSUE THREAD

**Issue by dparvin** [Microsoft/vscode#51732]
Issue Type: <b>Bug</b>

I have a Json file (I have it saved with a txt extension, but have selected Json as its typeof the file on the status bar) which when I edit it, and then save it, my cursor is not where I left it, it is at the bottom of the file.  It seems to be a problem with selecting the file type as Json.  When I select JSON with comments, the problem is gone.  If I have Auto-Save turned on or off, the cursor goes to the bottom of the file when ever it saves.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.77GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\TFS\Denali\Code\Dev\Sisense Rebranding\Rebranding Plan.txt|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
vscode-color|ans|0.4.5
azuretoolsforvscode|bra|2.0.2
vscode-clock|Com|0.0.1
xml|Dot|2.3.0
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.12.3
docker-explorer|for|0.1.6
phpcs|ika|1.0.5
vstsbuildstatus|jep|0.7.1
vstsservicestatus|jep|1.3.0
format-indent|Kas|1.3.0
vscode-codemetrics|kis|1.16.0
php-symbols|lin|2.1.0
phpmd|lin|1.1.4
vscode-JS-CSS-HTML-formatter|lon|0.2.3
VBScript|lug|0.0.2
prettify-json|moh|0.0.3
vscode-azureappservice|ms-|0.8.1
vscode-azurefunctions|ms-|0.9.1
vscode-azurestorage|ms-|0.3.1
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
csharp|ms-|1.15.2
mono-debug|ms-|0.15.8
PowerShell|ms-|1.7.0
typescript-javascript-grammar|ms-|0.0.41
vsliveshare|ms-|0.3.292
team|ms-|1.136.0
azurerm-vscode-tools|msa|0.4.2
debugger-for-edge|msj|1.0.2
vscode-docker|Pet|0.0.27
view-in-browser|qin|0.0.5
qub-msbuild|qub|0.6.3
vscode-icons|rob|7.23.0
code-settings-sync|Sha|2.9.2
vscode-microsoftteams|ste|1.0.6
code-spell-checker|str|1.6.10
msbuild-project-tools|tin|0.2.38
usql-vscode-ext|usq|0.2.14
application-insights|Vis|0.4.2
azure-iot-toolkit|vsc|0.6.3
code-lens-roundup|wad|1.0.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by RMacfarlane** [comment]
Thanks for reporting this, can you try using the `Reload Window with Extensions Disabled` command to temporarily disable your extensions? (Can return to the previous state by closing and reopening VSCode). On save, automatic formatters get run, so I suspect one of them is causing the problem
