### ISSUE TITLE
Ruby def/end should highlight the same as brackets

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5173]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10

When you click on or next to an opening or closing bracket it highlights the other. In Ruby it would be nice if selecting near a def or end highlighted/outlined the respective open/closing one.

**Comment by rebornix** [comment]
Let's use https://github.com/Microsoft/vscode/issues/55159 to track this issue, which proposed a solution for it.
