### ISSUE TITLE
Wrong cursor position in intergrated terminal with speical character left of prompt

### ISSUE THREAD

**Issue by OpportunityLiu** [Microsoft/vscode#51739]
Issue Type: <b>Bug</b>

1. Install [posh-git](https://github.com/dahlbyk/posh-git)
2. Open powershell in intergrated terminal
3. Run `Import-Module posh-git`
4. Set working directory to a git folder to show the git status in prompt
5. Input any command with space, i.e. `ls . -Recurse`, the cursor position is wrong
![1](https://user-images.githubusercontent.com/13471233/41329203-c7d2c66a-6efe-11e8-9a07-d1aa2428fb87.gif)

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.83GB (2.94GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
xml|Dot|2.3.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.30
docker-explorer|for|0.1.6
matlab|Gim|0.9.0
rainbow-csv|mec|0.4.1
vscode-language-pack-zh-hans|MS-|1.24.3
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
vscode-docker|Pet|0.0.27
code-settings-sync|Sha|2.9.2
hosts|tom|0.0.8
gitblame|wad|2.4.2
vscode-cil-complete|wk-|0.0.5
markdown-all-in-one|yzh|1.4.0

</details>

**Comment by OpportunityLiu** [comment]
It seems there is something wrong with character `≡`, the following step also reproduces:
```powershell
C:\> mkdir ≡
C:\> cd ≡
C:\≡> ls . -Recurse
```

**Comment by yume-chan** [comment]
I can't reproduce this problem with the `mkdir ≡` way in both 1.24.0 and 1.25.0-insider.

![1](https://user-images.githubusercontent.com/1330321/41340877-f5d670d0-6f2a-11e8-9dc7-6e70fc06036d.gif)

(In the gif the `terminal.integrated.cursorStyle` is `line`, but I also tried with `block`)

**Comment by Tyriar** [comment]
I'm guessing this is related to ambiguous character width, see https://github.com/xtermjs/xterm.js/issues/1467

**Comment by yume-chan** [comment]
> Are you using powershell on windows?

Yes, I'm using Windows 10 1804 x64 in English, PowerShell, and I'm also using posh-git.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
