### ISSUE TITLE
duplicate Extension deleted on startup

### ISSUE THREAD

**Issue by retepaskab** [Microsoft/vscode#51745]
Issue Type: <b>Bug</b>

1. duplicate one of the extensions in .vscode\extensions folder
2. add some files to one of them
3. start vscode
4. one of the duplicate extensions is deleted, including the non-duplicate files

4. expected: some dialog asking which one to disable, or moving to recycle bin instead of deleting

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|30.91GB (21.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|0.19.1
vscode-color|ans|0.4.5
close-all|ben|1.0.2
tslint|eg2|1.0.30
vscode-npm|fkn|3.3.0
gdl-22|pba|1.22.5
guid|kos|0.0.1
vs-color-picker|lih|0.7.0
language-gettext|mro|0.0.3
python|ms-|2018.5.0
cpptools|ms-|0.17.4
color-highlight|nau|2.3.0
vscode-code-outline|pat|0.2.1
relativegoto|ret|0.0.1
perforce|sle|3.1.0
vscode-hexdump|sle|1.6.0
goto-line-ex|xyz|0.0.4

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
This is a clean up task to remove outdated extensions. If you want to have a back up please copy it in a different folder.

**Comment by retepaskab** [comment]
Still this is very brutal if one doesn't know about it... Deleting unduplicated files.
