### ISSUE TITLE
Git path configuration unavailable

### ISSUE THREAD

**Issue by Mighten** [Microsoft/vscode#51746]
Issue Type: <b>Bug</b>

The default searching path for Git Extension is C:\Program Files\Git, however, I had installed it on the D:\Program Files\Git, so the VS Code failed to detect its installation.

VS Code version: Code 1.24.0 (2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

**Comment by yume-chan** [comment]
You can change `git.path` setting to the path to your `git.exe`, or add `git.exe` to `PATH` environment variable will also work.

**Comment by RMacfarlane** [comment]
Thanks @yume-chan! @Mighten, please try those suggestions and reopen this issue if you continue to have problems.
