### ISSUE TITLE
Where is the "code" field displayed in Problem pane?

### ISSUE THREAD

**Issue by LeThiHyVong** [Microsoft/vscode#51748]
This question is already asked in [StackOverFlow](https://stackoverflow.com/questions/49583669/where-is-the-code-field-in-the-problems-pane) but it has not been answered for 2 months.

In short, according to [VS Code docs](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher), when defining a problem matcher, there is a field for error code (my compiler DID provide one when compiling). However, I can't find it anywhere in problem pane (file, message, line are displayed correctly).
![capture](https://user-images.githubusercontent.com/19317679/41339536-453fe20c-6f1f-11e8-91bb-52c86e69930c.PNG)

My problem matcher
         
```
 "problemMatcher": {
                "fileLocation": [
                    "relative",
                    "${workspaceFolder}\\src"
                ],
                "pattern": {
                    "regexp": "^(.*)\\((\\d+)\\)\\s+:\\s+(C\\d+)\\s+\\((W|E|I)\\)\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "code": 3,
                    "severity": 4,
                    "message": 5
                }
            }
```

Sample message:
`uscommon.h(281) : C0005 (I) Precision lost`

I already tested the regex on https://regex101.com/
Thanks.

**Comment by RMacfarlane** [comment]
Currently, the "code" field is not displayed, but there's a feature request for adding it: https://github.com/Microsoft/vscode/issues/49215 If this is something you'd like, please go comment/thumbs up that issue. Thanks!
