### ISSUE TITLE
Integrated terminal not displaying properly in Light theme

### ISSUE THREAD

**Issue by chewlm86** [Microsoft/vscode#51743]
- Version: 1.25.0-insider
- Commit: 583f1e4934c5fd3b62c2ca5bf177c728b31b9605
- Date: 2018-06-13T05:18:58.565Z
- OS Version: 16.04.1-Ubuntu 

In the latest released, the Integrated terminal is not displaying properly when a Light theme is used.
![vs code terminal bg colour issue](https://user-images.githubusercontent.com/5851437/41334322-ca8dcaf8-6f17-11e8-8959-2e5d90b6376f.png)

[Steps to Reproduce:
Select a Light Theme (eg. Light+)
]

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51749#issuecomment-396869595
