### ISSUE TITLE
Terminal displays with a black background

### ISSUE THREAD

**Issue by BeauAgst** [Microsoft/vscode#51749]
- VS Code version: Code - Insiders 1.25.0-insider (583f1e4934c5fd3b62c2ca5bf177c728b31b9605, 2018-06-13T05:18:10.709Z)
- OS version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Open VSCode
2. Open the integrated terminal

Does this issue occur when all extensions are disabled?: Yes

![example](https://user-images.githubusercontent.com/10343831/41341286-44eee466-6ef1-11e8-9e83-90262376d19a.PNG)

**Comment by BeauAgst** [comment]
Possibly a duplicate of #49261, but has been happening since I installed the newest insider update, as opposed to after locking my screen. 
#46415 is a different issue.

**Comment by yume-chan** [comment]
Actually I believe it has the same cause with #51743
