### ISSUE TITLE
VS Code does not open default browser when clicking on link in release notes page

### ISSUE THREAD

**Issue by iotathome** [microsoft/vscode#51744]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Start VS Code
2. Select Help->Rease Notes
3. Click on e.g. "Commit Log"

After this VS Code tries to open firefox (process is created but nothing shows up) although chrome is the default browser:

* 0            /usr/bin/google-chrome-stable   200       Auto-Modus
  1            /usr/bin/firefox                40        manueller Modus
  2            /usr/bin/google-chrome-stable   200       manueller Modus

VS Code version: Code - Insiders 1.25.0-insider (583f1e4934c5fd3b62c2ca5bf177c728b31b9605, 2018-06-13T05:18:58.565Z)
OS version: Linux x64 3.13.0-151-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|15.57GB (0.16GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.24.3
cpptools|ms-|0.17.4
open-html-in-browser|pea|0.0.3

</details>

**Comment by jnials** [comment]
I am seeing similar behavior, but since I am running KDE I get a KIO Client browser asking for an app to run the file, but since the file has no extension it cannot populate a potential client list.

**Comment by dromer** [comment]
Also getting similar behavior in ```1.27-2``` on Ubuntu 18.04.
vscode opens links with chromium, even though my systemwide default browser is firefox.

In this case it should use ```x-www-browser``` as that is where the default browser is configured to (which is then symlinked by update-alternatives etc.)

**Comment by mastrolinux** [comment]
Can confirm the issue with version: 1.28.1

**Comment by JeffreyCA** [comment]
I just experienced the same issue on Windows with Chrome as my default browser. I restarted Chrome and it started to work again.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by dromer** [comment]
This is suddenly resolved? Haven't seen anyone try these packages yet to confirm.

I can try in a bit, but the latest vscode from repository definitely still has this bug.

**Comment by lyndhurst** [comment]
I cannot try the packages linked above for a few days, but I am on Kubuntu 18.04 and I am affected by this bug as well. When opening MDN references for example, the page is opened in chrome instead of Firefox (system default).

I first thought something got messed up because I recently installed the Live Server extension, and configured it to use Chrome for debugging. However, disabling the extension does not help, and setting it to open HTML pages through Firefox does work fine.

I will try and install the provided deb package over the weekend and give some feedback. In the meantime, let me know if there is any log or info I can provide while reproducing the bug, I will gladly help.

**Comment by dromer** [comment]
Current version (1.40) still opens links in the wrong browser.

**Comment by ottomundo** [comment]
@dromer Try making firefox your default browser THROUGH firefox, I've had it be my default by the terminal, profiles, etc but never actually clicked that option, it just fixed it for me.
