### ISSUE TITLE
Helpers for managing linter warnings

### ISSUE THREAD

**Issue by ksamuel** [Microsoft/vscode#51747]
We have checks that we want to keep, but that we will have exceptionally to by pass. Checks such as "max number of public class attributes", "max line size", "accessing private API", etc. We want to keep them because they force the team to think about the issue. But we can then decide to ignore them contextually. 

Now there are a lot of those checks, so we end up having one or two disabling comments by file on average (and more in unit tests). 

Currently, the classic workflow is to hover on the linter warning to get the warning code, then look up the required arcane comment to disable said warning, and finally type it manually. When editing the code, one have to go look up the code again to check if it's still an issue, or temporary remove it, save, wait for the linter to process the page, hover, check it still an issue, and maybe ctrl + z.

I wish for VSCode to make it easier.

When one hover a linter waring, I wish one could right click and ask to "insert disabling comment for that warning". When I hover a code in a disabling comment, I would also get a hint of what this code does. And if the warning has gone, then the comment could be highlighted so that I know it's not necessary anymore. 

I understand a side effect of this feature would be to make easier to disabling all warnings, all the time. But that's more of a cultural problem than a technical problem. Code review and git hook exist for those things.

**Comment by RMacfarlane** [comment]
Thanks for this feature request. Linters are implemented as extensions to VSCode, not as part of the base product. There are existing APIs for providing fixes on warnings/errors: https://code.visualstudio.com/docs/extensionAPI/language-support#_possible-actions-on-errors-or-warnings

Please move this issue to the repository of the linter you're using.
