### ISSUE TITLE
Extension manages to crash Linux exthost with SIGPIPE

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#51750]
Seen on Linux:

1. Install `Open in GitHub` extension: https://marketplace.visualstudio.com/items?itemName=ziyasal.vscode-open-in-github
2. Open a workspace in Github (vscode)
3. Open a file
4. Run the `Copy GitHub link to clipboard` command

:boom: 

![peek 2018-06-13 11-28](https://user-images.githubusercontent.com/22350/41342625-fb0def20-6efc-11e8-88b1-b538264ef459.gif)

**Comment by joaomoreno** [comment]
I wonder if it's related to the library used to add stuff to the clipboard? https://github.com/ziyasal/vscode-open-in-github/blob/master/src/extension.js#L13

**Comment by joaomoreno** [comment]
@alexandrudima This happens because I didn't have `xclip` installed on my Linux distribution. As soon as I installed it, the command started to work.

`xclip` is what [`copy-paste`](https://github.com/xavi-/node-copy-paste/blob/master/platform/linux.js) uses to access the clipboard, which is how the extension gets stuff onto the clipboard. `copy-paste` seems to just spawn `xclip`, it doesn't use any native code. So, I wonder how it can crash the extension host so easily... just by spawning a process which doesn't exist.

I tried to spawn a random process (`cp.spawn('whatdsadsa', [])`) using the exthost dev tools, and it doesn't seem to crash there at all.

:thinking:

**Comment by alexandrudima** [comment]
@joaomoreno If you have an environment where you can easily reproduce, can you create a simple minimal repro. This sounds like a bug for electron/nodejs/v8.

**Comment by joaomoreno** [comment]
@alexandrudima There we go: https://github.com/electron/electron/issues/13254

**Comment by alexandrudima** [comment]
@joaomoreno Thank you! ❤️

**Comment by bpasero** [comment]
We fixed this for 1.26.1.
