### ISSUE TITLE
[Mac] Runaway CPU usage from 'rg' after opening home directory

### ISSUE THREAD

**Issue by benjibee** [Microsoft/vscode#51757]
I opened by home directory `~/` in VSCode to edit a few bash / git config files and noticed my fans were spinning up and my laptop getting hot. After 10 or so minutes I restarted, opened VSCode and left it running in the background while I checked my email, only to notice the fans were spinning up again.

Activity Monitor shows the following usage:
<img width="912" alt="screen shot 2018-06-13 at 2 34 50 pm" src="https://user-images.githubusercontent.com/620119/41349239-f0d2bdb8-6f17-11e8-9e0e-5afd95a07bfd.png">

This process, `rg`, is owned by VSCode and some searching shows it's for indexing. I ran `sudo opensnoop -n rg` to see what it was up to, noticed it was indexing cache, my photos, all sorts of random stuff, then realized it was indexing my whole user directory / library and this is what was killing my CPU.

- VSCode Version: 1.24.0
- OS Version: 10.13.5 (17F77)

Steps to Reproduce:

1. Open Visual Studio Code
2. Select FIle > Open…
3. Select user's home folder

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This is most likely from an extension looking for a certain filetype. Can you confirm this by getting the arguments for those rg processes? Either from the process viewer in vscode or `ps`.

https://github.com/Microsoft/vscode/issues/34711

**Comment by benjibee** [comment]
This is what running `ps` on the pid of one of the instances shows, I see PHP but I don't know what that tells me:
`rg --files --hidden --case-sensitive -g **/*.php --no-ignore --follow --quiet -- .`

And running `code --list-extensions` shows the following:
```
GrapeCity.gc-excelviewer
Shan.code-settings-sync
cazoobi.solis
anthonydiametrix.ACF-Snippet
azaugg.vscode-cfengine
bradgashler.htmltagwrap
christian-kohler.path-intellisense
d4nuu8.language-kuka-krl
deerawan.vscode-dash
ecmel.vscode-html-css
esbenp.prettier-vscode
felixfbecker.php-intellisense
mikestead.dotenv
mrmlnc.vscode-apache
mrmlnc.vscode-scss
ms-python.python
ms-vscode.cpptools
nikitaKunevich.snippet-creator
onecentlin.laravel-blade
patbenatar.advanced-new-file
robinbentley.sass-indented
sachittandukar.laravel-5-snippets
sdras.night-owl
shinnn.stylelint
sleistner.vscode-fileutils
smlombardi.slime
vsciot-vscode.vscode-arduino
whatwedo.twig
wordpresstoolbox.wordpress-toolbox

If I disable them all, the processes are stop after 1-2 minutes. If I re-enable (PHP IntelliSense)[https://github.com/felixfbecker/vscode-php-intellisense] then the errant `rg` processes return quickly.

**Comment by roblourens** [comment]
Ok, yes this is exactly what #34711 is for
