### ISSUE TITLE
Typescript syntax highlight not correctly working

### ISSUE THREAD

**Issue by Zerokk** [Microsoft/vscode#51753]
- VSCode Version: 1.24
- OS Version: Windows 10 (latest)

Steps to Reproduce:

Basically, a project that was correctly working and highlighting its syntax, it's failing at it after the new update (which I installed today). Take a look:

![image](https://user-images.githubusercontent.com/10697745/41346319-80182bdc-6f06-11e8-9676-3b7c1c20c1b1.png)

Methods should be highlighted like here:

![image](https://user-images.githubusercontent.com/10697745/41346358-94e9e3e8-6f06-11e8-8b97-c2451f02a0e3.png)

Since this broke just after installing the new patch... what fix can I apply? Can the devs acknowledge this problem and take it in account for a next update? 

EDIT: some variables are also not being correctly highlighted (they appear white in my theme).

EDIT 2: it is really annoying sometimes:

![image](https://user-images.githubusercontent.com/10697745/41350985-3fe4624c-6f15-11e8-87ad-634db8252656.png)

**Comment by mjbvz** [comment]
Please test in the latest vscode insiders build. If you still see the problem, please share the source code from those screenshots at text
