### ISSUE TITLE
Error while updating - Update failed

### ISSUE THREAD

**Issue by seb9465** [Microsoft/vscode#51763]
- VSCode Version: 1.23
- OS Version: Windows 10

Steps to Reproduce:
1. I've been asked to update.
2. I started the updates.
3. Got an error when vscode told me to restart the app.
4. The error message told me to take the log file and create an issue with it, so here I am.
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2098211/vscode-inno-updater.log)
![screenshot_1](https://user-images.githubusercontent.com/25237983/41353423-350e06fa-6eea-11e8-9e32-5a82fdafee3b.png)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
