### ISSUE TITLE
Incorrect keybinding shown on hover for opening viewlet when there are multiple keybindings that begin with the same chord

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vscode#51767]
Issue Type: <b>Bug</b>

When I hover over the button that activates the Git panel, it tells me that Ctrl+Shift+G will activate it. But it does not. Rather, that keystroke changes the status bar to indicate it is waiting for the second chord in a multi-keystroke sequence. Pressing Ctrl+Shift+G again is rejected as a non-existent chord.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (1.80GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .\assert.xunit\|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
xml|Dot|2.3.0
gitlens|eam|8.3.5
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.30
git-project-manager|fel|1.6.1
docker-linter|hen|0.5.0
docomment|k--|0.1.0
azure-account|ms-|0.4.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
liveshare-logviewer|ms-|0.2.1
PowerShell|ms-|1.7.0
team|ms-|1.136.0
vscode-docker|Pet|0.0.27
java|red|0.26.0
vsc-docker|Zim|0.34.0

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
Can you run `Preferences: Open Keyboard Shortcuts` and search `Show SCM` to see what the binding for that is? Can you also check to see if you have any installed keymaps with `Preferences: Keymaps`?

**Comment by AArnott** [comment]
I don't have any installed keymaps.

Here is what I see on Open Keyboard Shortcuts:
![image](https://user-images.githubusercontent.com/3548/41378709-c5058038-6f14-11e8-8b62-51ed6078e70b.png)

I have not modified these directly in any way. 

Thanks.

**Comment by RMacfarlane** [comment]
Ah, ok. It looks like the GitLens extension is using Ctrl+Shift+G as the prefix for its keybindings, which is why VSCode waits for more input. You can add `"gitlens.keymap": "none"` to your settings or use the Ctrl+Shift+G+G shortcut à la GitLens. Regardless, we should display the correct keybinding to open the view when you hover

**Comment by AArnott** [comment]
This issue was moved to eamodio/vscode-gitlens#423

**Comment by AArnott** [comment]
I've filed an issue with GitLens, but IMO I think there's still a VS Code bug here, since the keyboard shortcut is displayed but doesn't work.

**Comment by eamodio** [comment]
I believe this issue would be a duplicate of https://github.com/Microsoft/vscode/issues/40389
