### ISSUE TITLE
terminal background become black after installing the latest update of vscode-insiders

### ISSUE THREAD

**Issue by sumanx** [Microsoft/vscode#51766]
- VSCode Version: 1.25.0-insiders, 2018-06-13T05:18:10.709Z
- OS Version: Windows 10 1803

Terminal was set to bash.exe (WSL)
Mac version in my mbp works well.

Does this issue occur when all extensions are disabled?: No

![vsc](https://user-images.githubusercontent.com/620733/41355306-c26676fe-6f53-11e8-8cfa-db8fb45e0cd0.png)

**Comment by Tyriar** [comment]
Should be fixed tomorrow
