### ISSUE TITLE
Installing should default first launch to selected language

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5176]
- VSCode Version: Windows 10
- OS Version: 1.0.0-alpha

Steps to Reproduce:

1. If you have VS Code installed, uninstall.
2. Run setup
3. Select another language (apart from English)
4. Launch after setup

Actual:
VS Code is launched in English (or if you have previously set the language, it will launch in that)

Expected:
By default it should launch in the language you selected during install.

**Comment by dbaeumer** [comment]
@joaomoreno we discussed this once. If we want to do this the installer has to write the locale.json file during installation. What do you think ?

**Comment by joaomoreno** [comment]
I think we will rely on Inno's ability to detect the language from the system and not show the selection box.
