### ISSUE TITLE
Emmet does not work inside script tag with type="text/ng-template"

### ISSUE THREAD

**Issue by jwhitmarsh** [Microsoft/vscode#51768]
This is identical to https://github.com/Microsoft/vscode/issues/34921 but for "text/ng-template"

Emmet expansion (via Tab, or via Command Palette) doens't work on text inside a <script> tag with this type. These tags are used in AngularJS for templates - https://docs.angularjs.org/api/ng/directive/script

- VSCode Version: Version 1.24.0 (1.24.0)
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create an HTML file like this:
```html
<script type="text/ng-template">
  
</script> 
```
2. Write an emmet string inside the script tag and press Tab/use command palette to trigger expansion. Nothing happens.
```html
<script type="text/ng-template">
div>p  
</script> 
```
3. Write an emmet string inside the script tag and press Tab/use command palette to trigger expansion. It works. 
```html
<script type="text/ng-template">

</script> 
div>p
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jwhitmarsh** [comment]
Am I right in thinking that adding "text/ng-template" in the line below would solve this? Is that a satisfactory fix?

https://github.com/Microsoft/vscode/blob/ae9063f0944adb9e4711b033c5790d87c6ba4e4f/extensions/emmet/src/util.ts#L50

**Comment by ramya-rao-a** [comment]
@jwhitmarsh Yes, that would fix it. Feel free to send a PR :)
