### ISSUE TITLE
Error when Trying to Commit with Message

### ISSUE THREAD

**Issue by PinchePanchoPincho** [Microsoft/vscode#51762]
Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Pancho@PANCHO-PC.(none)')
> git config --get-all user.name
> git show :README.md
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose

**Comment by PinchePanchoPincho** [comment]
I got the git-autoconfig extension:  https://marketplace.visualstudio.com/items?itemName=shyykoserhiy.git-autoconfig 

As a noob I have no idea why this error occurred or how I could have gone about filling in email/name. Perhaps someone can enlighten me; I imagine this must be a common problem.

**Comment by joaomoreno** [comment]
What does `git config user.email` return?
