### ISSUE TITLE
ctrl+F1失灵Running the contributed command:'extension.viewInBrowser' failed.

### ISSUE THREAD

**Issue by SNMW** [Microsoft/vscode#51761]
Issue Type: <b>Bug</b>

ctrl+F1失灵

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.26GB free)|
|Process Argv|D:\VSCode\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.24.3
view-in-browser|qin|0.0.5
open-in-browser|tec|1.1.0
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by RMacfarlane** [comment]
This issue was moved to hellopao/view-in-browser#16
