### ISSUE TITLE
 I do not know how..?

### ISSUE THREAD

**Issue by spovedav** [Microsoft/vscode#51777]
Issue Type: <b>Bug</b>

By trying the functions of visual code, remove the navigation bar and it is not intuitive to put it back.
There is no button to guide me to put the navigation bar again ..

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:02.816Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU G530 @ 2.40GHz (2 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (1.25GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
beautify|Hoo|1.3.1
vscode-language-pack-es|MS-|1.24.3
vscode-icons|rob|7.23.0
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by RMacfarlane** [comment]
Thanks for taking the time to file a bug report! Is this what you mean by the navigation bar?
![screen shot 2018-06-13 at 2 10 46 pm](https://user-images.githubusercontent.com/3672607/41378362-b6a89b02-6f13-11e8-93b8-8f0ad9fd2b60.png)

If so, you can press `Ctrl+shift+p` and then type `View: Toggle Activity Bar Visibility` to make it appear again. You can also press `Ctrl+,` to get to settings and remove `"workbench.activityBar.visible": false` from your settings.

If that's not what you mean by navigation bar, please include a screenshot
