### ISSUE TITLE
Update setup dialog defaults to English

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5177]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Install an old build or wait for an update
2. Change language from English to any other supported language
3. Update

Actual:
The setup or install dialog that shows up is in English. 

Expected:
During initial setup you can select the language you would like to use for setup. I think the update setup dialog should be based off the current language setting in Code.

**Comment by dbaeumer** [comment]
@joaomoreno Is this possible at all. Can we base the language of the setup on some external data (e.g. the locale.json file we have)? My expierence was as follows: if I select a language during the first setup that language is used in the setup later on.

**Comment by joaomoreno** [comment]
As expected. We will also remove the option to chose language if it can be detected.
