### ISSUE TITLE
Explore extending settings schema with additional metadata

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#51778]
#51773
#3355
#50249

Extended category/subcategory classifications? New friendly setting names?

**Comment by eamodio** [comment]
Yeah, I would love to be able to group settings, order them, and maybe hide some. Right now the alphabetic ordering, causes all of GitLens' advanced settings to be first in the list, and that is far from ideal. 

Probably out of scope, but it would be great if an extension (like GitLens) could tell the settings editor to not show any settings and instead show a button or something to launch the extension's settings handling

**Comment by eriolchan** [comment]
@roblourens  I met with the same issue as @DanTup , is there any plan to allow custom label for settings UI?

**Comment by rzhao271** [comment]
We now have settings grouping and ordering. Referring to https://github.com/microsoft/vscode/issues/191807 for custom titles.
