### ISSUE TITLE
Provide workspace folder for debug sessions

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51785]
Currently if the user launches multiple sessions we can't tell which one came from which workspace folder (eg. in `onDidStartDebugSession`), we only have `id`/`name`/`type`/`customRequest()`.

This means functionality like hot-reload-on-save we can't easily identify which debug session(s) we should forward the hot reload on to.

Presumably this info is available as it's rendered in the debug session dropdown on the debug toolbar. Is it possible to expose on the DebugSession (or at least to the `onDidStartDebugSession` event)?

**Comment by weinand** [comment]
Makes sense.

**Comment by weinand** [comment]
We could easily surface the rootFolder of the internal DebugSession in the DebugSession API.

**Comment by weinand** [comment]
I've added both the `workspace` and the `configuration` to the DebugSession class. 

With both available on a debug session eliminates the need for a DebugContext class in other areas of the debug API (e.g. in `DebugAdapterProvider.provideDebugAdapter`).

```ts
export interface DebugSession {
	/**
	 * The workspace folder of this session or undefined for a folderless setup.
	 */
	readonly workspaceFolder: WorkspaceFolder | undefined;

	/**
	 * The resolved debug configuration for the session.
	 */
	readonly configuration: DebugConfiguration;
}
```

**Comment by weinand** [comment]
Verification:
- use simple "hello world" extension
- register for "onDidChangeActiveDebugSession" and "onDidStartDebugSession"
- verify that the session in the event has correct "workspaceFolder" and "configuration" attribute values.
