### ISSUE TITLE
when importing a module check if folder and add automatic forward slash

### ISSUE THREAD

**Issue by jhonyourangel** [Microsoft/vscode#51783]
you have created this awesome dorpdown while inserting a path for a module after inserting a "/"
it would be nice if the current selection from the dropdown is a folder then add automatic folder and refresh the dropdown.
this way importing the files/modules will become very easy

**Comment by yume-chan** [comment]
Are you talking about JavaScript?

But it's totally legal to import a folder, most resolver will import `index.xxx` from that folder, some may implement any logic they want, how do you distinct that?

**Comment by jhonyourangel** [comment]
Hi, yes I was talking about JavaScript / type script.

Hmm didn’t thought about that...

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25205
