### ISSUE TITLE
Syntax highlighting bug with template literals

### ISSUE THREAD

**Issue by nealalpert** [Microsoft/vscode#51795]
If you place the string 'css' in a template literal in a JS file syntax highlighting is broken after it.

<img width="527" alt="screen shot 2018-06-13 at 3 11 11 pm" src="https://user-images.githubusercontent.com/2166663/41375584-24bb7d50-6f1c-11e8-9d3e-4add758ccc84.png">

- VSCode Version: 1.24.0
- OS Version: OSX 10.13.5

Steps to Reproduce:

1. Place the string 'css' inside a template literal in a javascript file

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can't repo this. Are you sure that you have disabled all extensions and have restarted VS code?

**Comment by rrandom** [comment]
I met the same problem and fix the highlighting after disabled extension `vscode-styled-jsx` @nealalpert
