### ISSUE TITLE
Settings to customize color of active activity bar entry

### ISSUE THREAD

**Issue by ramdacxp** [Microsoft/vscode#51796]
VSCode settings allow to customize the colors via `workbench.colorCustomizations`.

It is possible to style active **as well** as inactive **file tabs** via `tab.activeBackground` and `tab.inactiveBackground`, but in contrast the **activity bar** allows a general color and background color customization only (e.g. via `activityBar.background`). If used, the foreground color of inactive entries of the activity bar will be dimmed automatically.

Using those settings is is not possible to style the activity bar entry with inverse colors to increase readability and accessibility.

Please provide additional settings like `activityBar.activeBackground`, `activityBar.inactiveBackground`, `activityBar.activeForeground`, and `activityBar.inactiveForeground`.

**Comment by aeschli** [comment]
@sandy081 I guess you've done most on the activity bar recently, do you want to take this?

**Comment by sandy081** [comment]
Sure

**Comment by misolori** [comment]
@sandy081 let me know if there is anything you need from me.

**Comment by sandy081** [comment]
@ramdacxp I do not think you need the list of settings you mentioned in the description. I suppose `activityBar.activeForeground` should be sufficient.

**Comment by sandy081** [comment]
@bpasero FYI

**Comment by bpasero** [comment]
Yeah, we have colors like `tab.activeBackground`, so I think the color key is fine.

**Comment by bpasero** [comment]
Just to clarify, we will not introduce explicit background colors for an activity item right? The issue asks about it but https://github.com/Microsoft/vscode/pull/58517 is only foreground colors.

**Comment by sandy081** [comment]
Yes, I mentioned the same in this [comment](https://github.com/Microsoft/vscode/issues/51796#issuecomment-420565543). I do not see the need of background colours. `activityBar.inactiveForeground ` is enough and is missing to customise activity bar icons.

**Comment by ramdacxp** [comment]
Hi, my intent was to also introduce also background color styling to the activity bar because the selected items behaves like a tab. File tabs background colors can be styled and i would like to have this for the activity bar too.

**Comment by sandy081** [comment]
@ramdacxp I am not a big fan of having background colour for activity bar icons and I think activity bar icons and tabs are not related and current activity bar styling looks nice and simple. 

@bpasero @misolori Let me know your opinions. If you think foreground colours are enough, I will close this with the attached PR.

**Comment by bpasero** [comment]
Yeah I think so too.

**Comment by ramdacxp** [comment]
@sandy081 I personally found the highlighting of the active activity bar too understated (light white instead of grey) resulting in accidental clicks on the already active item (which then closes the side bar completely). A good way around would be the enable the same styling options as for file tabs. This also would improve consistency in the settings.

**Comment by ramdacxp** [comment]
Ok - i was too slow typing my last comment :)

**Comment by sandy081** [comment]
@ramdacxp I think highlighting the activity bar by foreground or background colour will represent the same and user might still have chances to click on it again.

**Comment by sandy081** [comment]
Verify that you can customise the colour of the inactive activity bar icon using the color `activityBarInActiveForeground`
