### ISSUE TITLE
Instructor Mode

### ISSUE THREAD

**Issue by sdras** [microsoft/vscode#51790]
As per the conversation with @auchenberg and @chrisdias, it's been requested by a number of instructors to take zen mode one step further. The expected behavior would:

- Have no LOC numbers visible
- Go full screen
- Remove the icons from the top right
- Have no tabs
- Be available and removed on a toggle

cc @johnpapa @kentcdodds @eggheadio @elijahmanor

Please feel free to add to this thread if I've misrepresented anything. Thank you for your time and effort in this!

**Comment by kentcdodds** [comment]
Here's the best I was able to manage without using a bunch of extensions:

![screen shot 2018-06-12 at 9 59 40 pm](https://user-images.githubusercontent.com/1500684/41371664-4db229c0-6f08-11e8-8d40-41dde6d490a8.png)

I'd like to remove as many unnecessary things as possible. So...

- Hide the scroll bar on the right
- Hide the tab at the top (and icons)
- A little less padding around the code
- Also, I'd like to be able to put the terminal on the left side of the code for my use case

I would also like to add that my use cases are varied. When I do a screencast in a single file then this the above mentioned things are preferred. When I'm doing a workshop, then having the filepath of the currently opened file would be important as well as line numbers.

If there were a way to easily switch between setting overrides (there's probably an extension for this) + have settings for some of these things that don't exist quite yet, then I think that would satisfy my use cases very well :)

**Comment by kentcdodds** [comment]
One other thing. I recently switched to code from atom and one thing I really loved about atom was that there's a stylesheet for css overrides that's built-into the editor. That made this kind of thing pretty stright forward and flexible. Would be cool to have something like that in code :)

**Comment by SRajapakseOscar** [comment]
Hiding line numbers and scrollbar would be very useful and should also be available in zen mode settings.

**Comment by snebjorn** [comment]
Can't this be solved using the screencast feature (implemented in version 1.31) plus this #105226

**Comment by chrisdias** [comment]
i believe this is being handled by profiles https://code.visualstudio.com/updates/v1_74#_profiles
