### ISSUE TITLE
VSCode with golang support ends up being in an unstable state.

### ISSUE THREAD

**Issue by ldesegur** [Microsoft/vscode#51803]
From time to time, using the debugging in VSCode will get me in this broken state where I get the following message:

go build runtime: build output "/usr/local/Cellar/go/1.10.2/libexec/src/runtime/debug" already exists and is a directory
exit status 1
Process exiting with code: 1

I also get a cryptic modal dialog stating that: ${fileDirName} can not be resolve. Please open an editor (?!?)

From there I need to close the app and restart VSCode.

**Comment by weinand** [comment]
If you are using the variable `${fileDirName}` in a launch configuration you will need to have a file open in the editor (because `${fileDirName}` resolves to the directory name of that file). So the message "Please open an editor" makes sense.

**Comment by weinand** [comment]
For the other issue please open a bug against the Go extension.

**Comment by ldesegur** [comment]
Hey Weinand, the             "program": "${fileDirname}", is what I see in the launch.json file. That's a program not a file. Not sure I understand the relationship between editor and program launch though.

**Comment by weinand** [comment]
"program" is typically the file to debug (it depends on the debugger you are using). You can enter a file name there.

If you decide to use a the variable `${fileDirname}` it means:
When the debug session is started, the variable is replaced by the directory of the file currently open in the editor. If no file is open in the editor this must fail. That's the error you are seeing.

If you don't like that behaviour, just don't use the variable.


I recommend to make yourself familiar with VS Code debug configurations: 
see https://code.visualstudio.com/docs/editor/debugging and especially https://code.visualstudio.com/docs/editor/debugging#_variable-substitution
