### ISSUE TITLE
Blinking cursor disappears when zoomed out

### ISSUE THREAD

**Issue by aramix** [microsoft/vscode#51809]
Blinking cursor disappears after each 4 or so chars when moving along the text line. This varies depending on the editor zoom level and font size.

- VSCode Version: 1.24.0 (1.24.0)
- OS Version: macOS High Sierra 10.13.5 (17F77)
- Hardware: MacBook Pro (Retina, 13-inch, Early 2015)

Steps to Reproduce:

1. Set window.zoomLevel to -1
2. Set editor.fontSize to 18
3. Open a text and move cursor from one side to another. You should see it disappearing after a few chars repeatedly. Playing with zoom and font size values changes this behaviour from disappearing more frequently to not disappearing at all.

Does this issue occur when all extensions are disabled?: Yes

I also found out that this is caused by setting "editor.cursorStyle" to "line-thin". When disabled cursor gets thiner in places where it disappears when enabled. So it has to do with the width of the cursor getting too thin and disappearing.

This behaviour also changes depending on the editor window width.

**Comment by alexandrudima** [comment]
To workaround, use `"window.zoomLevel": 0`, and customize `editor.fontSize`

**Comment by aramix** [comment]
@alexandrudima thanks for the feedback. Unfortunately for me that's not a workaround because window.fontSize does not affect the font size in the sidebar. A better workaround for me for now is to set "editor.cursorStyle" to "line" instead of "line-thin".

**Comment by alexandrudima** [comment]
@aramix Please upvote https://github.com/Microsoft/vscode/issues/519

That would allow you to change the workbench font without needing to use the buggy zoom...
