### ISSUE TITLE
ctrl+c is inconsistent

### ISSUE THREAD

**Issue by ormico** [Microsoft/vscode#51804]
Issue Type: <b>Bug</b>

[ctrl]+c frequently does not copy. I do [ctrl]+c, [ctrl]+v a lot and it works perfect in VS2017 but not in VS Code. I throws me off when I copy something, arrow down and hit [ctrl]+v and it pastes something other than what I expected.

sometimes it works, sometimes it doesn't. I sometimes have to type [ctrl]+c a couple of times to make sure I got it after a couple of failures.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.79GB (37.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\projects\LOS Talker\hg\TopOfMindSolution\LBrewer.TopOfMindIntegration.Console\appsettings.config|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
path-intellisense|chr|1.4.2
jshint|dba|0.10.19
xml|Dot|2.3.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.30
prettier-vscode|esb|1.5.0
vs-code-xml-format|fab|0.1.5
code-runner|for|0.9.3
docker-explorer|for|0.1.6
vscode-auto-open-markdown-preview|hnw|0.0.4
path-autocomplete|ion|1.10.0
plantuml|jeb|2.7.6
angular-essentials|joh|0.3.2
Angular2|joh|6.1.1
hg|mrc|1.2.3
vscode-kubernetes-tools|ms-|0.1.10
mssql|ms-|1.3.1
azure-account|ms-|0.4.0
azurecli|ms-|0.4.1
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.6.0
angular2-inline|nat|0.0.17
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.0
polacode|pnp|0.2.2
hgwo|pxg|1.1.2
vscode-yaml|red|0.0.13
code-clip-ring|Sir|0.0.4
prettify-selected-json|vth|1.0.3

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Does this reproduce when you close all windows and run `code --disable-extensions`?

**Comment by ormico** [comment]
no. that seems to make the problem go away. I'm guessing that means one of the plugins is causing the problem. Is there any way to figure out which one is likely to be the culprit?

**Comment by Tyriar** [comment]
@ormico the only way is to selectively disable them. I'm guessing you could also look at their keybinding contributions to find one that conflicts with the standard ones.

**Comment by ormico** [comment]
I looked and I didn't see anything that was binding to [ctrl]+c though I could have missed something.

I have 34 extensions, so going through them one by one will be a pain.

**Comment by ormico** [comment]
I think I found it. I believe the issue is the following extension. I'm leaving this here in case anyone else has the same problem. 

I had forgotten I had this extension, but after reviewing the description I do not think the behavior that I'm seeing is the intended behavior. I wasn't really using it, so i uninstalled.

Clipboard Ring
sirtobi.code-clip-ring
SrTobi
