### ISSUE TITLE
python  debugger can't work properly

### ISSUE THREAD

**Issue by crazydogen** [Microsoft/vscode#51811]
Issue Type: <b>Bug</b>

The problem is that the python debugger has no reponse when I hit f5 after installed . And I faced the problem before.For some reason, I just reset the windows and reinstall  the vscode, it's work. But after few days, the problem  comes out again. I really don't want to reset again this time.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134
Python version : 2.7.15-32bit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (27.86GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.24.3
python|ms-|2018.5.0

</details>

**Comment by crazydogen** [comment]
## debug.log
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"python","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"zh-cn"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsEvaluateForHovers":false,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsSetVariable":true,"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all"},{"label":"Uncaught Exceptions","filter":"uncaught"}]}}
To client: {"seq":0,"type":"event","event":"initialized"}
From client: launch({"name":"Python: Current File","type":"python","request":"launch","logToFile":true,"stopOnEntry":true,"program":"d:\\1\\1.py","pythonPath":"python","cwd":"d:\\1","envFile":"d:\\1\\.env","console":"integratedTerminal","internalConsoleOptions":"neverOpen","debugOptions":["RedirectOutput"],"__sessionId":"2daf6866-4342-4a20-a7f7-e665a536356f"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"DEBUGGER","data":{"trigger":"launch","console":"integratedTerminal","debugOptions":"RedirectOutput","pyspark":false}}}
From client: setExceptionBreakpoints({"filters":[]})
To client: "runInTerminal"({"kind":"integrated","title":"Python Debug Console","cwd":"d:\\1","args":["python","c:\\Users\\Ian\\.vscode\\extensions\\ms-python.python-2018.5.0\\pythonFiles\\PythonTools\\visualstudio_py_launcher.py","d:\\1","61225","34806ad9-833a-4524-8cd6-18ca4aa74f14","RedirectOutput,RedirectOutput","d:\\1\\1.py"],"env":{"PYTHONIOENCODING":"UTF-8","PYTHONUNBUFFERED":"1"}}), timeout: 5000

**Comment by crazydogen** [comment]
## TYPE: Python
terminal errors:
PS D:\1> cd 'd:\1'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'python' 'c:\Users\Ian\.vscode\extensions\ms-python.python-2018.5.0\pythonFiles\PythonTools\visualstudio_py_launcher.py' 'd:\1' '60690' '34806ad9-833a-4524-8cd6-18ca4aa74f14' 'RedirectOutput,RedirectOutput' 'd:\1\1.py'
Traceback (most recent call last):
  File "c:\Users\Ian\.vscode\extensions\ms-python.python-2018.5.0\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\Ian\.vscode\extensions\ms-python.python-2018.5.0\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2607, in debug
    attach_process(port_num, debug_id, debug_options, currentPid, report = True)
  File "c:\Users\Ian\.vscode\extensions\ms-python.python-2018.5.0\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2321, in attach_process
    raise Exception('failed to attach')
Exception: failed to attach

**Comment by biwusun** [comment]
I have the same question like you@crazydogen, have u fixed it already?
