### ISSUE TITLE
Cannot open the project after clone from repository

### ISSUE THREAD

**Issue by buiduyhung13** [Microsoft/vscode#51813]
Issue Type: <b>Bug</b>

1. Open Visual Source Code
2. Open terminal and clone new project from repository
3. Click File->Open and select the clone folder

Expected: Folder is open in visual source code
Actual: It cannot open

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
Bookmarks|ale|0.19.1
vscode-opennewinstance|chr|0.0.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitlens|eam|8.3.5
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-sort|hen|0.2.5
open-in-browser|igo|0.0.99
RelativePath|jak|1.4.0
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
psi-header|psi|1.4.0
java|red|0.26.0
trailing-spaces|sha|0.2.11
code-spell-checker|str|1.6.10
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
vscode-react-native|vsm|0.6.11
gitblame|wad|2.4.2
vscode-open-in-github|ziy|1.3.1

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@buiduyhung13 Thanks for reporting this! When you try to open the folder, does anything at all happen? Can you check to see if there are any errors in the console with `Developer: Toggle Developer Tools`?

**Comment by RMacfarlane** [comment]
Ok, thank you! I'll close this for now. Please submit a new issue if it happens again
