### ISSUE TITLE
Feature Request: Filter Files by Source Control Status

### ISSUE THREAD

**Issue by harshitgupta** [Microsoft/vscode#51817]
Hi,

First of all thank you for the awesome editor. **Never had a better Swiss Knife**.

**Background:** I have some background in iOS development where I used Xcode for development. In Xcode, in the file explorer section, there is button at the bottom, that filter the file list by the source control status i.e. it would only show the files (obviously in source controlled code) that have been edited, added etc. Please look at the following image for reference.

![dfmzv8zueaelnbp](https://user-images.githubusercontent.com/1644577/41388765-1d94ecdc-6f53-11e8-8604-38c497129b2a.jpg)

**Actual Request:** It would be great if we could have the same thing in vs code. It could be separate section in left side bar or a button just like Xcode itself. 

**Supporting Argument:** A project might have 100 files, but at a given time we only interact with 4-5 files. So looking at the list of all the files every time and finding the files that you are working with, distracts you, especially when it comes to the nested folders and files.

Thanks again.

**Comment by isidorn** [comment]
Thansk for the feature request, I feel like this is a bit ouf of scope, but leaving it open for now
