### ISSUE TITLE
Code again spews  output when started from wsl

### ISSUE THREAD

**Issue by blomma** [Microsoft/vscode#51838]
Issue Type: <b>Bug</b>

Version 1.24.1 again spews output on the console when started from wsl, this was fixed in 1.24, so this is a regression from that version, i could not find anything in the release notes for 1.24.1 that this had been reverted. The console also does not return control to me. So essentially the behavior of 1.24.1 is the same as 1.23 in this regard.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (4.28GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe -n .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
gitlens|eam|8.3.5
LogFileHighlighter|emi|2.4.0
prettier-vscode|esb|1.5.0
vscode-todo-plus|fab|2.1.2
Ionide-fsharp|Ion|3.22.0
markdown-shortcuts|mdi|0.8.1
prettify-json|moh|0.0.3
mssql|ms-|1.3.1
csharp|ms-|1.15.2
Go|ms-|0.6.82
vscode-docker|Pet|0.0.27
remote-vscode|raf|1.1.0
elastic|ria|0.12.0
code-settings-sync|Sha|2.9.2
rewrap|stk|1.9.1
ayu|tea|0.14.0
fish|Ted|0.0.4
vscode-status-bar-format-toggle|tom|1.4.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
What does spews output mean?

**Comment by blomma** [comment]
Right sorry. When running

`code -n .` from WSL terminal, in this case Ubuntu 18.04 i get the following output

`[main 10:28:53 AM] update#setState idle`

Also control is not returned to the terminal until i quit visual studio code.

This problem was fixed in 1.24 and in 1.24.1 the problem reappeared.

**Comment by Tyriar** [comment]
This is fixed, you need to update Windows though https://github.com/Microsoft/vscode/commit/8505dcc4694ce23be6b207861384f44ba4f5705b

**Comment by blomma** [comment]
I'm not sure I am following you, are you saying that you changed this behavior between 1.24 and 1.24.1? Because the specific commit you are pointing me to was in march.

**Comment by Tyriar** [comment]
@blomma it was meant to be fixed only in 1.24 and only for a later version of Windows 10. I would expect this output and for control not to return for all other versions of Windows 10. The PR itself was merged in May https://github.com/Microsoft/vscode/pull/44945
