### ISSUE TITLE
React Collapse not working properly in render method

### ISSUE THREAD

**Issue by chakrihacker** [Microsoft/vscode#51835]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by RMacfarlane** [comment]
Hi @chakrihacker, can you please resubmit your bug? There is a limited amount of data we can send to prefill the GitHub template, so we copy the data to the clipboard if it's large and you need to paste it

**Comment by RMacfarlane** [comment]
Based on the title of this issue, I think the issue is probably with folding regions. We recently changed the default folding strategy to be language based instead of indentation based. Please try adding `"editor.foldingStrategy": "indentation"` to your settings to revert to the old behavior
