### ISSUE TITLE
Open containing folder of open file

### ISSUE THREAD

**Issue by jonstodle** [Microsoft/vscode#5183]
- VSCode Version: 0.10.11
- OS Version: Windows 10 1511

Steps to Reproduce:

1. Open any file in VS Code

In the context menu of an open file there should be an option to open the containing folder.

Alternatively the "Open folder" button could open in the containing folder of the currently opened file.

**Comment by egamma** [comment]
// FYI @bpasero

**Comment by Debonnys** [comment]
An "Open current folder" button under the open Folder button or something equally easy would be a very welcome feature!

**Comment by bpasero** [comment]
@chrisdias is this not your extension doing?

**Comment by chrisdias** [comment]
sounds like it!

https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance

**Comment by vytautas-pranskunas-** [comment]
Can this be reopened because i still cannot find this functionality?
