### ISSUE TITLE
Suggestions not shown again after pressing backspace when filtered suggestion list has become empty

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#51843]
Issue Type: <b>Bug</b>

1. For a js file:

```js
const abc = 123;
```

2. Type out `abcd` in the file
3. Note that suggestions show not be shown. 
4. Hit back space

**Expected**
Suggestions start showing again. This is consistent with what happens when if you just type out `abc` and then hit backspace

**Actual**
Suggestions are not shown again

VS Code version: Code - Insiders 1.25.0-insider (11b0f3a40be055e02b721abbb93cb0012818f99e, 2018-06-14T05:11:13.121Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|40.00GB (0.19GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4809878|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jrieken** [comment]
> This is consistent with what happens when if you just type out abc and then hit backspace

No, the difference is that in one case you have an active IntelliSense session and in the other you don't have a session. Backspace isn't used a trigger character but only to "widen" existing completions. Unless there are strong objection I am in favour of closing this 'as designed.
