### ISSUE TITLE
[Accessibility]A11y_VSCode_FindAndReplace_ColorContrast:Color contrast ratio is less than 4.5:1 for the placeholder text.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#51840]
**Environment Details:**
VSCode Version : 1.24.1
OS Version : Win10

**Additional Details:**
ColorContrast,MAS1.4.3

**Repro Steps:**
1.	Launch VS Code.
2.	Navigate to Status Bar and select “Find And Replace " button.

3.	Open color contrast analyzer and check the ratio.

**Actual:**
Color contrast ratio is less than 4.5:1 for the placeholder text.

**Expected:**
Color Contrast ratio should not be less than 4.5:1.
Same issue observed on other color theme also.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

](url)

**User Impact:**
The user will not be able to see the controls.

**MAS Reference:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a73546c7-765f-489c-b18f-afb659fe99e6}
](url)

**Attachment for Reference:**

![accessibility a11y_vscode_findandreplace_colorcontrast](https://user-images.githubusercontent.com/39204909/41395801-8f558a2e-6fcc-11e8-81a9-56acc683eb2d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@AccessibilityTestingTeam-TCS Thanks for all of your hard work, I have maybe a silly question. Do all themes need to meet this color contrast ratio? We have a high contrast theme for this scenario

**Comment by auchenberg** [comment]
@RMacfarlane To be MAS compliant we should meet the contrast requirements out of box. High Contrast Mode is the contrast taken to the extreme for people with low visibility. See https://webaim.org/blog/high-contrast/

**Comment by RMacfarlane** [comment]
The "Find and Replace" input box uses the same colors as the control we use for user input, the quick pick box. There's already an issue tracking the contrast of these colors for that, so since this is the same root cause, I've closed this as a duplicate

https://github.com/Microsoft/vscode/issues/51831
