### ISSUE TITLE
Part of task output in terminal is missing.

### ISSUE THREAD

**Issue by tksuoran** [Microsoft/vscode#51844]
Issue Type: <b>Bug</b>

Task output in terminal is partially missing for the following task:
            "label": "Summary",
            "type": "shell",
            "command": "cat summary.txt",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            "problemMatcher": []
My summary.txt file has 77 lines. Executing the task first time after window reload only shows up to line 38. Second time I execute the task I get to see all lines. Then if I execute Reload Window, again the next cat task shows incomplete output.
IIRC this cat task used to work correctly a while back.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.13.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 1302)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.33GB (0.39GB free)|
|Process Argv|/usr/share/code/code /home/tsuoranta/automotive-cmt/core-private|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.3.5
cpptools|ms-|0.17.4

</details>

**Comment by dbaeumer** [comment]
Looks like a dup of https://github.com/Microsoft/vscode/issues/51163 to me.
