### ISSUE TITLE
How to avoid keeping last files

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#51846]
Issue Type: <b>Bug</b>

When I start VS Code, it always opens last files which I opened last time.
How can I do to avoid it?
I always want to start VS Code with a clean interface. Does VS Code have this configuration option?

I have disabled the "files.hotExit".

Furthermore, how can I do to stop VS Code to remember the file histories under the menu?

VS Code version: Code - Insiders 1.25.0-insider (11b0f3a40be055e02b721abbb93cb0012818f99e, 2018-06-14T05:17:21.496Z)
OS version: Windows_NT x64 10.0.17686

Extensions: none

**Comment by yume-chan** [comment]
`"window.restoreWindows": "none"`?

**Comment by RMacfarlane** [comment]
Thanks @yume-chan!

There's currently no setting for disabling recent opened history, but you can use the `File: Clear Recently Opened` command to clear it. Please file a feature request if this is something you want added.
