### ISSUE TITLE
Inconsistent markdown rendering in markdown preview and vscode extension explorer

### ISSUE THREAD

**Issue by HaaLeo** [Microsoft/vscode#51859]
- VSCode Version: 1.24.1
- OS Version: windows 10 1803

# Steps to Reproduce:

1. Create an extension with a readme file containing `*this should be cursive **this should be bold and cursive***`
2. Publish the extension on the market place
3. Query for the extension in vscode's extension explorer

# Description
The above markdown snippet is rendered as expected on github, vscode marketplace and vscode itself (using the markdown preview). However when you search for the extension in vscode's extension explorer the rendering of this snippet is broken.

Does this issue occur when all extensions are disabled?: yes

# Example
For instance in the [timing extension](https://marketplace.visualstudio.com/items?itemName=HaaLeo.timing) I wrote `[...] *epoch time is the **source*** [...]` in the readme.
* Rendered on the marketplace: 
![2018-06-14-marketplace](https://user-images.githubusercontent.com/23164374/41397830-b82e41aa-6fb5-11e8-9124-313755799412.PNG)

* Rendered with the extension explorer:
![2018-06-14-extension-explorer](https://user-images.githubusercontent.com/23164374/41397884-e739e76a-6fb5-11e8-90ee-89bb0613263e.png)

* Rendered with the markdown preview: 
![2018-06-04-markdown-preview](https://user-images.githubusercontent.com/23164374/41398122-985e1d54-6fb6-11e8-9403-a8a1593fdb84.png)

It would be great if the rendering between vscode's markdown preview, extension explorer and vscode marketplace would be consistent.

**Comment by JacksonKearl** [comment]
The markdown engine we use for the extensions view is very fast/lightweight, but unfortunately not as compliant as the one bundled with the markdown extension. In this case, the engine we use views the three asterisks as syntactically ambiguous, and produces incorrect output. 

I would recommend using the convention of underscores for italics when combining emphasis, which should render consistently everywhere. (i.e. `_epoch time is the **source**_`

**Comment by HaaLeo** [comment]
Is there a way to check how the extension explorer's markdown engine renders the readme **before** I publish the extension to the vscode marketplace? I would like to avoid patches due to wrong markdown rendering.

**Comment by JacksonKearl** [comment]
This demo should show you how we will render it:
https://marked.js.org/demo/?text=When%20*the*%20*epoch%20time%20is%20the%20**source***%20format%20of%20the%20conversion%20its%20unit%20is%20determined%20by%20its%20**digit%20count**%3A%0A
