### ISSUE TITLE
Find all references on a Typescript class constructor returns no results.

### ISSUE THREAD

**Issue by jockjocko** [Microsoft/vscode#5185]
- VSCode Version: 0.10.15-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Create class and constructor.
2. Create a new instance of the newly created class
3. Shift + f12 or right click find all references

I would expect it to find all references of the class being constructed "new ExampleClass()".

**Comment by egamma** [comment]
Moving to TypeScript for investigation.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#8023
