### ISSUE TITLE
C-Tab or C-S-Tab switch the tab in the wrong order

### ISSUE THREAD

**Issue by Menci** [Microsoft/vscode#51860]
- VSCode Version: Version 1.24.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open some tabs in VSCode.
2. Click to switch to the first tab.
3. Click to switch to the second tab.
4. Press <kbd>Ctrl + Tab</kbd>. It is expected to switch to the third tab (like in Chrome), but in fact it switches to the first tab.
4. Continue to *long* press <kbd>Ctrl</kbd>, and press <kbd>Tab</kbd> for some times, it travels the tabs in *correct* order.

If the last tab I've used is not adjust to the current tab, it will switch to that and it results in a MESS order!

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
By default, <kbd>Ctrl+Tab</kbd> navigates to the next most recently opened editor. To navigate the tabs in order, you can use the the `View: Open Next Editor`. You can customize your keyboard preferences to switch <kbd>Ctrl+Tab</kbd> to perform this action.
