### ISSUE TITLE
Emmet not working if use Shopify settings in style.scss.liquid

### ISSUE THREAD

**Issue by SaniJasi** [Microsoft/vscode#51867]
- VSCode Version: Latest
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create styles.scss.liquid (Shopify format)
2. Add some styles and add setting from admin, for example `color: {{ settings.was_price_color }};`
3. Before this setting, emmet works fine, but after not working

I recorded video, please look [http://take.ms/bys3c](http://take.ms/bys3c)

Does this issue occur when all extensions are disabled?: Yes

**Comment by SaniJasi** [comment]
any updates?

**Comment by ramya-rao-a** [comment]
What is the language mode of the file being used?
If it is not css/less/sass, can you share what extension you used to help with this file type?

**Comment by SaniJasi** [comment]
[I work with style.scss.LIQUID files and use SCSS language mode](https://tppr.me/wVruK)

**Comment by ramya-rao-a** [comment]
Can you provide some documentation on the using the `{{` and `}}` as css property value?

**Comment by SaniJasi** [comment]
Please see [ **Using Liquid in Sass files**](https://www.shopify.com/partners/blog/a-beginners-guide-to-sass-with-shopify-part-3)

**Comment by ramya-rao-a** [comment]
@sergeche I recall you mentioning on working on a better parser for scss and less. Would this case be covered there?

**Comment by sergeche** [comment]
This example works fine with current CSS parser in CodeMirror and Atom. Might be an issue with VS Code plugin
