### ISSUE TITLE
[Feature request] Plug-in management By Project

### ISSUE THREAD

**Issue by zsirfs** [Microsoft/vscode#51868]
I think my idea should be unique。

Vscode is a very good editor, I mainly use it for coding. But when we need more and more features, inevitably installed a lot of plug-ins, I try to develop a plug-in based on My project, for example, I am a ts-based project, I only need the relevant ts plugins. Each developer will have a second language and a third language, such as Python, Go, Dart, and so on. However, when developing a project, we do not need to open plugins for other languages, because this will cause vscode to run slowly because too many plugins are open. I am a vim user. When the cursor is moving quickly, it will lead to a cursor segment and the experience is very uncomfortable.

Originally wanted to manually switch plug-ins, but with the increase in plug-ins, this action is very annoying. Although there is a work area configuration that can switch the difference, but I hope the vscode can provide different coding pre-projects can configure different plug-ins, so that different plug racks start according to the project, rather than start, or open access to other plug-ins. Thank you

**Comment by zsirfs** [comment]
Thanks, it is not repeated

**Comment by yume-chan** [comment]
You can enable/disable extensions for each workspace.

And there are some other requests about quickly manage extensions:

#49826: Feature Request - Extension Group
#47053: Add functionality for bulk extension handling

**Comment by sandy081** [comment]
@zsirfs I think you request can be handled by enabling extensions per workspace

**Comment by zsirfs** [comment]
@sandy081 thanks. I know how to personalize the configuration through the workspace. I think the editor can be started or closed automatically through the plugin group instead of through the workspace/config.json configuration.
Thank you again for replying

**Comment by sandy081** [comment]
There are actions available in the extensions view to enable or disable extension per workspace.

![image](https://user-images.githubusercontent.com/10746682/41850482-ff9481e4-7884-11e8-9c87-a6b504031a19.png)

**Comment by zsirfs** [comment]
Thanks. Need to set up each plugin。
