### ISSUE TITLE
Selection highlight settings

### ISSUE THREAD

**Issue by SerCarciofini** [Microsoft/vscode#51869]
Issue Type: <b>Bug</b>

Looks like setting selection highlight this way
"editor.selectionHighlight": false,
"editor.occurrencesHighlight": true
disables occurrencesHighlight anyway, no matter if it's true or false

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.15.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1332)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.71GB (0.93GB free)|
|Process Argv|/usr/share/code/code /tmp/fz3temp-2/archivio.php|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.19
svn-scm|joh|1.29.2
vscode-language-pack-it|MS-|1.24.3
vscode-code-outline|pat|0.2.1

</details>

**Comment by alexandrudima** [comment]
@SerCarciofini This depends from language to language.

It is a bit complicated, but here goes:

---

* extensions can contribute a `DocumentHighlightProvider` for their language. This should be a semantic highlighter which highlights, for example, the same variable. You can see this in action in a `.js` file (notice how `nn` is highlighted semantically, the first occurrence is not highlighted):
![image](https://user-images.githubusercontent.com/5047891/41525804-829bc334-72e2-11e8-9410-b5625d70e1dd.png)
* this feature can be turned off via `editor.occurrencesHighlight`

---

* there is another feature called selection highlighting. This kicks in when making a selection and is non semantic (it will highlight all occurences of the selection):
![image](https://user-images.githubusercontent.com/5047891/41526225-d5188aba-72e3-11e8-9436-628b3b801827.png)
* this feature can be turned off via `editor.selectionHighlight`


---

Now, there is a long tail of languages which we also want to support. For a lot of them, we don't have rich extensions that can implemented semantic highlights. So, if a language does not register a `DocumentHighlightProvider`, we fall back to the selection highlighter even when there is no selection. You can see this kicking in for example in plain text:
![image](https://user-images.githubusercontent.com/5047891/41526297-1400d156-72e4-11e8-954d-f1f635f8f339.png)
* you can think of this fallback as an implementation of a very simple `DocumentHighlightProvider`. Currently, this gets disabled when either `editor.occurrencesHighlight` or `editor.selectionHighlight` are set to false.

Would you expect that this last one should be disabled only when configuring `editor.occurrencesHighlight` to false?

**Comment by alexandrudima** [comment]
To verify, configure:
```
"editor.selectionHighlight": false,
"editor.occurrencesHighlight": true
```

Then open a plain text file and check that words are still highlighted, even if selectionHighlight is turned off.
