### ISSUE TITLE
[Accessibility]A11y_VSCode_GoToSymbolInFile_Keyboard:Tree view closes on pressing the "Tab " key .

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#51877]
**Environment Details:**
VS Code Version:1.24
OS Version:Windows10
**Additional Details:**
NVDA 2018.2,MAS3.2.1
**Steps to Reproduce:**
1.Launch VS Code.
2Navigate   to Go(Alt+G) menu option and select "Go To Symbol in File" from   dropdown or use Ctrl+shift+o.
3.Use the "Tab key" to navigate through the tree view.
**Actual:**
Tree view closes on pressing the "Tab " key
**Expected:**
Tree view closes on pressing the "Tab " key
"Recommendations:
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx
[User] Impact:
User will not be able to use tree view.
**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a4bbd37d-ee11-485e-b5c8-0539f0ac94b2}
Does this issue occur when all extensions are disabled?: Yes
**Attachment for Reference:**
[[Accessibility]A11y_VSCode_GoToSymbolInFile_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2101714/Accessibility.A11y_VSCode_GoToSymbolInFile_Keyboard.pptx)

**Comment by RMacfarlane** [comment]
The same control is opened in many different scenarios (whenever user input is requested) and has the same tab behavior. I'm going to close all but one instance of this problem since the root cause is one control. 
(https://github.com/Microsoft/vscode/issues/51854)
