### ISSUE TITLE
Run a debug which only has preLaunchTask will cause an error message 

### ISSUE THREAD

**Issue by virtualnode** [Microsoft/vscode#51870]
- VSCode Version: 1.24.0
- OS Version:  Windows10 Home Edition

Steps to Reproduce:

1. Create a  task named myTask
2. Create a launch like below:
{
            "type": "PowerShell",
            "request": "launch",
            "preLaunchTask": "myTask",
            "name": "Debug My Task",
            "cwd": "${workspaceRoot}"
        },
3. Run my task by hit the keyboard F5
After completed to run "preLaunchTask", an error by the debugger was shown.  调试适配器进程已意外终止 (The possible translation may : "The process of debug adapter was aborted.") 
![image](https://user-images.githubusercontent.com/38773469/41402333-9db6e9d2-6ff4-11e8-98eb-179ecb13dbea.png)

Does this issue occur when all extensions are disabled?: Yes/No
N/A

**Comment by weinand** [comment]
Please file this issue against the PowerShell extension.
