### ISSUE TITLE
Intel OpenCL Code Builder/GPU Programming

### ISSUE THREAD

**Issue by peter73421** [Microsoft/vscode#51871]
Make available Intel OpenCL Code Builder plugin for OpenCL/GPU programming

**Comment by RMacfarlane** [comment]
@peter73421 Thanks for submitting this feature request, but this repository is tracking only core features for VSCode, not extensions. This extension might be what you're looking for: https://marketplace.visualstudio.com/items?itemName=galarius.vscode-opencl
