### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'version' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5187]
Issue Id: <b>b17130c6-f500-48ee-2661-497bdd9b50b5</b><br /><br />*Versions* <br />- 0.10.15-insider<br />*Stack* <br />TypeError: Cannot read property 'version' of null<br />[/vs/workbench/parts/git/node/rawGitService.ts#L24:31 (version)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/workbench/parts/git/node/rawGitService.ts#L24:31 (version))<br />[/vs/workbench/parts/git/node/rawGitService.ts#L187:34 (getVersion)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/workbench/parts/git/node/rawGitService.ts#L187:34 (getVersion))<br />[/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1311:0 (_run)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/base/common/winjs.base.raw.js#L1311:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1176:0 (_notify)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/base/common/winjs.base.raw.js#L1176:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1306:0 (_run)](https://github.com/microsoft/vscode/blob/67567498285c2081312077cc24370d97676fc20a/src/vs/base/common/winjs.base.raw.js#L1306:0 (_run))<br />

**Comment by aeschli** [comment]
38 hits on 20 machines, all 0.10.15, on Linux, Windows and Mac
