### ISSUE TITLE
Use pnpm to manage extensions' dependencies

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/vscode#51879]
Right now, each extension has its own isolated `node_modules` folder. Some extensions may share common dependencies, so it takes extra disk space to install duplicated packages, it also downloads the same thing more than once.

[pnpm](https://github.com/pnpm/pnpm) can solve this problem: It uses symlinks/hardlinks to avoid downloading the same package twice. It also faster than both npm and yarn (in my personal experience).

**Comment by zkochan** [comment]
A good article that shows the disk space savings of pnpm vs npm/yarn: [NPM, Yarn and PNPM: Which Package Manager Should You Use for SharePoint Framework Projects?](http://www.andrewconnell.com/blog/npm-yarn-pnpm-which-package-manager-should-you-use-for-sharepoint-framework-projects)

**Comment by sandy081** [comment]
@joaomoreno Does it makes sense what user is suggesting?

**Comment by KSXGitHub** [comment]
@sandy081 Although you're not asking me, your question make me confuse. What do you meant by "makes sense"? Is my suggestion above not clear enough? Perhaps I'm assuming something: Does VS Code use npm at all?

**Comment by yume-chan** [comment]
No, Code doesn't use npm at all, all extensions need  to pack their `node_modules` folder into the vsix extension package.

**Comment by KSXGitHub** [comment]
So I'm assuming things. Silly me.
