### ISSUE TITLE
VS code editer changes color when full screen and in Zen mod

### ISSUE THREAD

**Issue by KelvinQAQ** [Microsoft/vscode#51874]
Issue Type: <b>Bug</b>

I upgraded vscode today, and i found it changed color when full screen an at Zen mode. While it did not go wrong at the default window mod.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.90GB (2.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter|don|1.1.4
latex-workshop|Jam|5.5.1
vscode-language-pack-zh-hans|MS-|1.24.3
python|ms-|2018.5.0
markdown-all-in-one|yzh|1.4.0

</details>

**Comment by isidorn** [comment]
Can you repreoduce this with vscode insiders https://code.visualstudio.com/insiders/
If yes please post a screenshot and explain what is wrong
Also reproducable steps would help
