### ISSUE TITLE
**bold** text breaks monospace fonts in ".md" files

### ISSUE THREAD

**Issue by pd93** [Microsoft/vscode#51878]
Issue Type: <b>Bug</b>

- Create a `.md` file anywhere.
- The best way to see the effect of this problem is with a table:
![image](https://user-images.githubusercontent.com/9294862/41405271-4d5727d2-6fc1-11e8-84c9-23882f84e2b1.png)
- Bold text is previewed in bold in the editor.
- This breaks the monospace font and stops columns from lining up.

My font: 'Droid Sans Mono Slashed' (powerline)

Raw Text:
```
| Title | Row   | ----- | ----- | ----- | ----- |
|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| --A-- | --B-- | --C-- | --D-- | --E-- | --F-- |
| **A** | **B** | **C** | **D** | **E** | **F** |
```

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17686

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.96GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

Reproduces with extensions disabled...

**Comment by mjbvz** [comment]
Please share the text from the screenshot

**Comment by pd93** [comment]
```
| Title | Row   | ----- | ----- | ----- | ----- |
|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| --A-- | --B-- | --C-- | --D-- | --E-- | --F-- |
| **A** | **B** | **C** | **D** | **E** | **F** |
```

**Comment by mjbvz** [comment]
Thanks. I can't repo this in vscode insiders:

![screen shot 2018-06-14 at 2 17 59 pm](https://user-images.githubusercontent.com/12821956/41438972-e848b5c8-6fdd-11e8-8ffb-98f07921f67e.png)

Can you please share the font settings you are using

**Comment by yume-chan** [comment]
It depends on the font, Consolas is OK, but bold characters in Inconsolata are wider.

**Comment by pd93** [comment]
Yes, sorry. I'm using a powerline font (Droid Sans Mono Slashed). I guess this is why its happening.

**Comment by alexandrudima** [comment]
Font rendering in the editor is implemented by Chromium and it respects the font settings. So, if the font is built in a way where bold characters are wider, the rendering will render bold characters wider than regular characters.

So the only solution at this time is to change to a different font or a different theme which does not render bolded markdown with bold fonts. The latter is also doable via user settings (not with a full theme).
