### ISSUE TITLE
[bug] unused variable is not greyed-out if import statement is lacking

### ISSUE THREAD

**Issue by dreamflow** [Microsoft/vscode#51882]
bug description :
an unused variable is not greyed-out if no import statement is there
or if the import statement is commented out .

![unused variable is not greyed-out](https://user-images.githubusercontent.com/13277579/41405817-f860c80a-6fca-11e8-84b9-d7bd837f9097.png)

expected behavior :
an unused variable should be greyed-out , independet of the
existence of an import statement in the same *.js file .

test results on different windows versions :
this phenomenon happens the same in Win10 64bit and Win7 32bit .

Please search existing issues to avoid creating duplicates :  done , nothing found

- VSCode Version:  1.24.1
- OS Version:  Win10 64bit and Win7 32bit SP1

Steps to Reproduce:
1 : create a test.js file containing only

    import ''
    let test = 1

2 : comment out or remove the line with the import statement
     and compare the coloring of the unused variable before and after

Does this issue occur when all extensions are disabled?: yes

**Comment by mjbvz** [comment]
This is by-design. If your code does not have an imports or exports, it is considered a loose file and any top level declarations like `test` are put into the global scope (so they are always considered reachable). This matches what browsers do
