### ISSUE TITLE
Preview code when searching a file before open it

### ISSUE THREAD

**Issue by sejas** [Microsoft/vscode#51887]
Hi!, I think it would be very useful the see the file content before open it.
For example: I press `⌘+P` to search the filenames, and It would be great if I can see the file content in a temporal tab when I scroll among them in the dropdown.

<img width="1280" alt="captura de pantalla 2018-06-14 a las 11 43 19" src="https://user-images.githubusercontent.com/779993/41407744-48df6eec-6fc8-11e8-98a7-185047520757.png">

**Comment by roblourens** [comment]
You can press the right arrow key to open the file while quickopen is visible. We also have https://github.com/Microsoft/vscode/issues/8939 for this.
