### ISSUE TITLE
when edit java file, raise json exception, log below.

### ISSUE THREAD

**Issue by hlee13** [Microsoft/vscode#51889]
[extension-output-#3.log](https://github.com/Microsoft/vscode/files/2101969/extension-output-.3.log)

**Comment by RMacfarlane** [comment]
Thanks for filing this issue! Please provide these details:

- VSCode version
- OS
- Installed extensions
- Is this reproducible after you run `Reload Window with Extensions Disabled`?
- Where is this log file from?
