### ISSUE TITLE
Yocto plugin

### ISSUE THREAD

**Issue by peter73421** [Microsoft/vscode#51895]
Yocto Plug-in to develop, deploy, and test applications, as well prepare Yocto images, new recipes, modify existing recipes and ideal case to intagrate with gitlab workflow ...
https://www.yoctoproject.org/docs/2.5/sdk-manual/sdk-manual.html#sdk-eclipse-project

**Comment by RMacfarlane** [comment]
@peter73421 Thanks for submitting this feature request, but this repository is tracking only core features for VSCode, not extensions. If this is an extension you're interested in building, please see our docs: https://code.visualstudio.com/docs/extensions/overview
