### ISSUE TITLE
Error list does not get updated after a while

### ISSUE THREAD

**Issue by markusmauch** [Microsoft/vscode#51898]
This issue is not new but the bigger our code base gets the sooner after a re-launch of the vscode window the error list stops showing the actual output of the tsc watcher.

Also, as soon as the problem occurs, 'go to definition' and other operations that need to understand the code stop working.

Only solution so far: Close and re-open vscode. We're doing this up to 50 times a day. 

- VSCode Version: <= 1.24.1
- OS Version: Windows 10

**Comment by mjbvz** [comment]
Do you see this in VS Code insiders with all extensions disabled?

**Comment by markusmauch** [comment]
Yes and it's been there since at least the last year. We're using .NET reflection in order to generate a lot of TypeScript code and type definitions to describe our backend services and data types. This process replaces some 200 .ts and .d.ts files during the build process. That definitely kills the language service. But it stops working even without generating any file after some time (10 minutes or so).

**Comment by kqadem** [comment]
We are facing the same issues with the latest stable. I assumed it's sth related to the "Angular Language Service" Plugin. I'm kinda fresh in the codebase/project which is quite huge. Me and others would love to use VS Code but this issue blocks us working productively and we have to switch to other alternatives...

+ Go to Definition takes up to 20 seconds.

I will try to find out the reasons tomorrow with the methods described [here](https://github.com/Microsoft/vscode/wiki/Performance-Issuesl)

VSCode Version: Latest Stable
OS Version: Windows 10
TypeScript Version: 2.6
Angular 5 Projekt

**Comment by mjbvz** [comment]
@markusmauch
  
Please collect the TS Server log on vscode insiders:


1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Run the `TypeScript: Open TS Server log` command. This should open a folder with a `tsserver.log` file. Open that file

Look at the end of the file. Can you share the last few line of what is going on? If you can share the  entire logs I can try looking through them

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
