### ISSUE TITLE
run code

### ISSUE THREAD

**Issue by priyankakri21** [Microsoft/vscode#51891]
Issue Type: <b>Feature Request</b>

There is no run code button to run js file

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

**Comment by yume-chan** [comment]
[Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) is a popular extension to run your code.

**Comment by mjbvz** [comment]
For node, you can also just start debugging. It will automatically run the current file if you have not configured a debug configuration on previously
