### ISSUE TITLE
 spawn /usr/bin/gnome-terminal ENOENT

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5189]
Issue Id: <b>27d8c366-d67b-4b72-7774-cf987ecb2f6a</b><br /><br />*Versions* <br />- 0.10.10<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />-  43ff6af3d4564f59196caa9be4897fc33c15f24c<br />-  67567498285c2081312077cc24370d97676fc20a<br />-  f291f4ad600767626b24a4b15816b04bee9a3049<br />-  ef2a1fcaa553d14d7731b284a5ac5e4a55c42936<br />-  149e7a0debf3e32f95978a606e00d3c09bcac3d6<br />*Stack* <br />Error: spawn /usr/bin/gnome-terminal ENOENT<br />    at exports._errnoException (util.js:837:11)<br />    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32) <no sourcemaps><br />    at onErrorNT (internal/child_process.js:344:16) <no sourcemaps><br />    at doNTCallback2 (node.js:442:9)<br />    at process._tickCallback (node.js:356:17)<br />

**Comment by aeschli** [comment]
1106 hits on 107 machines

Is the exception expected? Any chance we can avoid logging?

**Comment by egamma** [comment]
Looks like it is in the terminal related code that @weinand worked with an intern. @Tyriar can you take a look since he is on vacation.

**Comment by weinand** [comment]
This does not seem to come from node-debug because there we verify that /usr/bin/gnome-terminal exists before we spawn it.

**Comment by weinand** [comment]
@aeschli what OS is this? should only occur on linux.

**Comment by Tyriar** [comment]
In v0.10.10 `gnome-terminal` was used in the `LinuxExecutionService` here https://github.com/Microsoft/vscode/blob/0.10.10/src/vs/workbench/parts/execution/electron-browser/executionService.ts#L137

This is no longer registered in `execution.contribution.ts`, removed by @jrieken in b1ba4f83fa6c45359a65e33b9f949f49dc1d8ff7 for https://github.com/Microsoft/vscode/issues/4503

@jrieken can this safely be closed off? Isn't this the code launches the task runner, are you sure it's no longer needed?

**Comment by jrieken** [comment]
It's the terminal service, the execution service isn't needed anymore.

**Comment by aeschli** [comment]
@weinand Linux only

**Comment by joaomoreno** [comment]
@jrieken there are no references of `gnome-terminal` anywhere in our sources. Why do you say this is the terminal service? I think @Tyriar is right and this should now be closed...

**Comment by jrieken** [comment]
ops, my bad. it's safe to close then. we didn't use that service anywhere anymore
