### ISSUE TITLE
opens multiple process in task manager

### ISSUE THREAD

**Issue by syedirfan7** [Microsoft/vscode#51897]
Issue Type: <b>Bug</b>

eats more ram(>1GB) compared  on my laptop with 8gb ram and opens multiple processes. slowsdown my machine. but on other PC and laptop it take <100 mb .. why ?

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.50GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
ng-template|Ang|0.1.9
tslint|eg2|1.0.30
debugger-for-chrome|msj|4.6.0
vscode-icons|rob|7.23.0
autoimport|ste|1.5.3

</details>

**Comment by Tyriar** [comment]
Can you run `code --status` and paste in the process information?

**Comment by syedirfan7** [comment]
Hi @Tyriar ,

here is the process info after doing `code --status


Version:          Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS Version:       Windows_NT x64 10.0.16299
CPUs:             Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)
Memory (System):  7.89GB (4.29GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:\Program Files\Microsoft VS Code\Code.exe
GPU Status:       2d_canvas:                    enabled
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  vpx_decode:                   unavailable_software
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0       81   12108  code main
    0       58    9720     gpu-process
    0       65   12512     shared-process
    0      209   14648     window (app.component.ts - tera - Visual Studio Code)
    0       13    3268       electron-crash-reporter
    0       74    4960       extensionHost
    0       39    6464         electron_node jsonServerMain.js
    0       68    9988         electron_node tslintServer.js
    1      134   11384         electron_node electronForkStart.js tsserver.js
    0       36    7824           electron_node typingsInstaller.js tsserver.js typesMap.js
    0      171   11860         electron_node server.js
    0       14    8432       watcherService
    0       10    4388         console-window-host (Windows internal process)
    0       34   11304       searchService
    0       33   14448       terminal
    0        7    6824         winpty-process
    0       62    1180           C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0       10   12128           console-window-host (Windows internal process)`

**Comment by Tyriar** [comment]
So to break this down into the major parts:

- Main process: 81mb
- GPU/shared process: 83mb
- Window: 209mb
- Extensions: 522mb
- File watcher: 14mb
- Search: 34mb
- Terminal: 112mb

Nothing is standing out as particularly wrong here. The major usage of memory is going to extensions which includes typescript indexing the project, providing the intellisense, etc., tslint and json.
