### ISSUE TITLE
[Accessibility]A11y_VSCode_ProcessExplorer_ScreenReader:Jaws is not reading the row reference and column reference for table cell value.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#51903]
**Environment Details:**
VSCode Version : 1.24.1
OS Version : Win10
**Additional Details:**
ScreenReader[JAWS18.0.5038],MAS1.3.1,MAS4.2.3
**Repro Steps:**
1. Launch VS Code.
2. Navigate to Help(Alt+H) menu option and select "Open Process Explorer" from dropdown.
3. Open color contrast analyzer and check the ratio.

**Actual:**
Jaws is not reading the row reference and column reference for table cell value.

**Expected:**
Jaws should read the row and column reference for the table.
Same issue observed on other color theme also.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
The user will not be able to know the reference.

MAS Reference:
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={30e4fb40-dcc1-45b4-b714-5e2c28b23ae8}](url)
Does this issue occur when all extensions are disabled?: Yes 
**Attachment for Reference**
[[Accessibility]A11y_VSCode_ProcessExplorer_ScreenReader.pptx](https://github.com/Microsoft/vscode/files/2102636/Accessibility.A11y_VSCode_ProcessExplorer_ScreenReader.pptx)

**Comment by isidorn** [comment]
We do not support jaws
