### ISSUE TITLE
Tab character not treated as whitespace when deleting

### ISSUE THREAD

**Issue by jhasse** [microsoft/vscode#5190]
- VSCode Version: 0.10.15-insider
- OS Version: Tested on Fedora Linux 23 and Windows 10
1. `<cursor><space><space>{`
   When pressing `Ctrl+Delete` in this situation only the spaces get deleted.
2. `<cursor><tab>{`
    In this situation also the { character gets deleted, but it should behave exactly the same as in the first case.

**Comment by jhasse** [comment]
It actually also deletes the { when there is only one space: `<cursor><space>{`

I've edited the original post, sorry for my mistake.

**Comment by alexandrudima** [comment]
@jhasse We actually have three different possible implementations of `ctrl+delete` that we ship with to please everybody. Here is how you can switch to the other(s):
```
{ "key": "ctrl+delete", "command": "deleteWordStartRight", "when": "editorTextFocus" }
```
or
```
{ "key": "ctrl+delete", "command": "deleteWordEndRight", "when": "editorTextFocus" }
```

**Comment by jhasse** [comment]
Awesome! `deleteWordStartRight` is what I'm looking for and also what I think should be the default. It's the same behavior as in Sublime Text and Visual Studio if I'm not mistaken?

**Comment by marvinhagemeister** [comment]
**PHPStorm:** the whole line is deleted
**Sublime Text 3:** Everything to the left of the cursor is deleted, everything to the right is kept as is
**Atom:** Same as sublime

**Comment by jhasse** [comment]
Are you on OS X? I think the keybindings are different there then on Windows / Linux.

**Comment by marvinhagemeister** [comment]
Yes, I'm on OSX.

**Comment by alexandrudima** [comment]
It is hard to pick a default that makes everybody happy, given some of our users come from an IDE brackground, some come from other text editors, and some are by now used to our default.

I suggest to leave the default as it is, and point to the alternatives in documentation.

**Comment by jhasse** [comment]
Is there any other editor / IDE / ... though that behaves as VS Code?

**Comment by jhasse** [comment]
Given other editors don't behave like this, please reconsider.
