### ISSUE TITLE
vscode keeps crashing at the end of the update installation 

### ISSUE THREAD

**Issue by sergio-domingues** [Microsoft/vscode#51904]
- VSCode Version: 1.24.1 
- OS Version: W10-64 bit

Steps to Reproduce:

1. Install Update
2. Get prompt to restart vscode in order to apply update
3. Restart vscode
3. Crash message:  "CreateProcess failed; code2; System cannot locate the specified file"

**Log**
Jun 14 15:04:43.773 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
Jun 14 15:04:43.775 INFO Checking for running Code.exe processes... (attempt 1)
Jun 14 15:04:43.783 INFO Code.exe is running, wait a bit
Jun 14 15:04:44.284 INFO Checking for running Code.exe processes... (attempt 2)
Jun 14 15:04:44.292 INFO Code.exe is running, wait a bit
Jun 14 15:04:44.793 INFO Checking for running Code.exe processes... (attempt 3)
Jun 14 15:04:44.800 INFO Code.exe is running, wait a bit
Jun 14 15:04:45.300 INFO Checking for running Code.exe processes... (attempt 4)
Jun 14 15:04:45.307 INFO Code.exe is not running
Jun 14 15:04:45.307 INFO Checking for possible conflicting running processes... (attempt 1)
Jun 14 15:04:45.315 INFO Inno Updater v0.4.3
Jun 14 15:04:45.315 INFO Starting update, silent = false
Jun 14 15:04:45.522 INFO do_update: "C:\\Program Files\\Microsoft VS Code\\Code.exe", _
Jun 14 15:04:45.522 INFO move_update: "C:\\Program Files\\Microsoft VS Code\\unins000.dat", _
Jun 14 15:04:45.523 INFO Delete: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.524 INFO Delete: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.524 INFO Delete: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.525 INFO Delete: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.525 INFO Delete: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.526 INFO Delete: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
Jun 14 15:04:45.527 INFO Delete: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
Jun 14 15:04:45.528 INFO Delete: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.528 INFO Delete: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.529 INFO Delete: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.530 INFO Delete: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.530 INFO Delete: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
Jun 14 15:04:45.531 INFO Delete: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.531 INFO Delete: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.532 INFO Delete: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.532 INFO Delete: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.533 INFO Delete: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
Jun 14 15:04:45.533 INFO Delete: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.534 INFO Delete: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.534 INFO Delete: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.534 INFO Delete: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.535 INFO Delete: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
Jun 14 15:04:45.535 INFO Delete: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.536 INFO Delete: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.536 INFO Delete: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.537 INFO Delete: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.537 INFO Delete: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.538 INFO Delete: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.538 INFO Delete: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.539 INFO Delete: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.539 INFO Delete: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.540 INFO Delete: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.540 INFO Delete: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.541 INFO Delete: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.542 INFO Delete: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.542 INFO Delete: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.542 INFO Delete: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.543 INFO Delete: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.544 INFO Delete: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.544 INFO Delete: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
Jun 14 15:04:45.544 INFO Delete: "bin" (attempt 1)
Jun 14 15:04:45.546 INFO Delete: "blink_image_resources_200_percent.pak" (attempt 1)
Jun 14 15:04:45.547 INFO Delete: "Code.exe" (attempt 1)
Jun 14 15:04:45.551 INFO Delete: "Code.VisualElementsManifest.xml" (attempt 1)
Jun 14 15:04:45.551 INFO Delete: "CodeSignSummary-ca435f23-0cec-45ec-b54b-27be2e2f3403.md" (attempt 1)
Jun 14 15:04:45.552 INFO Delete: "content_resources_200_percent.pak" (attempt 1)
Jun 14 15:04:45.552 INFO Delete: "content_shell.pak" (attempt 1)
Jun 14 15:04:45.553 INFO Delete: "d3dcompiler_47.dll" (attempt 1)
Jun 14 15:04:45.557 INFO Delete: "ffmpeg.dll" (attempt 1)
Jun 14 15:04:45.558 INFO Delete: "icudtl.dat" (attempt 1)
Jun 14 15:04:45.559 INFO Delete: "libEGL.dll" (attempt 1)
Jun 14 15:04:45.559 INFO Delete: "libGLESv2.dll" (attempt 1)
Jun 14 15:04:45.568 INFO Delete: "locales" (attempt 1)
Jun 14 15:04:45.591 INFO Delete: "msvcp140.dll" (attempt 1)
Jun 14 15:04:45.592 INFO Delete: "natives_blob.bin" (attempt 1)
Jun 14 15:04:45.592 INFO Delete: "node.dll" (attempt 1)
Jun 14 15:04:45.597 INFO Delete: "pdf_viewer_resources.pak" (attempt 1)
Jun 14 15:04:45.597 INFO Delete: "resources" (attempt 1)
Jun 14 15:04:48.973 INFO Delete: "snapshot_blob.bin" (attempt 1)
Jun 14 15:04:48.974 INFO Delete: "ucrtbase.dll" (attempt 1)
Jun 14 15:04:48.974 INFO Delete: "ui_resources_200_percent.pak" (attempt 1)
Jun 14 15:04:48.975 INFO Delete: "vcruntime140.dll" (attempt 1)
Jun 14 15:04:48.976 INFO Delete: "views_resources_200_percent.pak" (attempt 1)
Jun 14 15:04:48.977 INFO Rename: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.978 INFO Rename: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.978 INFO Rename: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.979 INFO Rename: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.980 INFO Rename: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.981 INFO Rename: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
Jun 14 15:04:48.982 INFO Rename: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
Jun 14 15:04:48.984 INFO Rename: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.985 INFO Rename: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.986 INFO Rename: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.987 INFO Rename: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.988 INFO Rename: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
Jun 14 15:04:48.988 INFO Rename: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.990 INFO Rename: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.991 INFO Rename: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.993 INFO Rename: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.994 INFO Rename: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
Jun 14 15:04:48.995 INFO Rename: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.996 INFO Rename: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.997 INFO Rename: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.998 INFO Rename: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
Jun 14 15:04:48.999 INFO Rename: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
Jun 14 15:04:49.000 INFO Rename: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.001 INFO Rename: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.002 INFO Rename: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.003 INFO Rename: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.004 INFO Rename: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.005 INFO Rename: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.006 INFO Rename: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.007 INFO Rename: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.008 INFO Rename: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.010 INFO Rename: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.011 INFO Rename: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.012 INFO Rename: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.013 INFO Rename: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.014 INFO Rename: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.015 INFO Rename: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.016 INFO Rename: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.017 INFO Rename: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.018 INFO Rename: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
Jun 14 15:04:49.019 INFO Rename: "bin" (attempt 1)
Jun 14 15:04:49.020 INFO Rename: "blink_image_resources_200_percent.pak" (attempt 1)
Jun 14 15:04:49.021 INFO Rename: "Code.exe" (attempt 1)
Jun 14 15:04:49.072 INFO Rename: "Code.exe" (attempt 2)
Jun 14 15:04:49.273 INFO Rename: "Code.exe" (attempt 3)
Jun 14 15:04:49.724 INFO Rename: "Code.exe" (attempt 4)
Jun 14 15:04:50.525 INFO Rename: "Code.exe" (attempt 5)
Jun 14 15:04:51.777 INFO Rename: "Code.exe" (attempt 6)
Jun 14 15:04:53.578 INFO Rename: "Code.exe" (attempt 7)
Jun 14 15:04:56.029 INFO Rename: "Code.exe" (attempt 8)
Jun 14 15:04:59.231 INFO Rename: "Code.exe" (attempt 9)
Jun 14 15:05:03.282 INFO Rename: "Code.exe" (attempt 10)
Jun 14 15:05:08.283 INFO Rename: "Code.exe" (attempt 11)
Jun 14 15:05:08.284 ERRO Acesso negado. (os error 5)

**Comment by venialgimcrack** [comment]
I'm experiencing a similar issue, with identical steps to reproduce. Here is the output of vscode-inno-updater.log:

Jun 14 12:38:43.400 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
Jun 14 12:38:43.402 INFO Checking for running Code.exe processes... (attempt 1)
Jun 14 12:38:43.407 INFO Code.exe is running, wait a bit
Jun 14 12:38:43.907 INFO Checking for running Code.exe processes... (attempt 2)
Jun 14 12:38:43.911 INFO Code.exe is running, wait a bit
Jun 14 12:38:44.411 INFO Checking for running Code.exe processes... (attempt 3)
Jun 14 12:38:44.414 INFO Code.exe is running, wait a bit
Jun 14 12:38:44.914 INFO Checking for running Code.exe processes... (attempt 4)
Jun 14 12:38:44.922 INFO Code.exe is running, wait a bit
Jun 14 12:38:45.422 INFO Checking for running Code.exe processes... (attempt 5)
Jun 14 12:38:45.431 INFO Code.exe is running, wait a bit
Jun 14 12:38:45.931 INFO Checking for running Code.exe processes... (attempt 6)
Jun 14 12:38:45.939 INFO Code.exe is running, wait a bit
Jun 14 12:38:46.439 INFO Checking for running Code.exe processes... (attempt 7)
Jun 14 12:38:46.447 INFO Code.exe is running, wait a bit
Jun 14 12:38:46.947 INFO Checking for running Code.exe processes... (attempt 8)
Jun 14 12:38:46.950 INFO Code.exe is running, wait a bit
Jun 14 12:38:47.450 INFO Checking for running Code.exe processes... (attempt 9)
Jun 14 12:38:47.458 INFO Code.exe is running, wait a bit
Jun 14 12:38:47.958 INFO Checking for running Code.exe processes... (attempt 10)
Jun 14 12:38:47.966 INFO Code.exe is running, wait a bit
Jun 14 12:38:48.466 INFO Checking for running Code.exe processes... (attempt 11)
Jun 14 12:38:48.474 INFO Code.exe is running, wait a bit
Jun 14 12:38:48.974 INFO Checking for running Code.exe processes... (attempt 12)
Jun 14 12:38:48.981 INFO Code.exe is running, wait a bit
Jun 14 12:38:49.481 INFO Checking for running Code.exe processes... (attempt 13)
Jun 14 12:38:49.489 INFO Code.exe is running, wait a bit
Jun 14 12:38:49.989 INFO Checking for running Code.exe processes... (attempt 14)
Jun 14 12:38:49.997 INFO Code.exe is running, wait a bit
Jun 14 12:38:50.497 INFO Checking for running Code.exe processes... (attempt 15)
Jun 14 12:38:50.501 INFO Code.exe is running, wait a bit
Jun 14 12:38:51.001 INFO Checking for running Code.exe processes... (attempt 16)
Jun 14 12:38:51.008 INFO Code.exe is running, wait a bit
Jun 14 12:38:51.508 INFO Checking for running Code.exe processes... (attempt 17)
Jun 14 12:38:51.516 INFO Code.exe is running, wait a bit
Jun 14 12:38:52.016 INFO Checking for running Code.exe processes... (attempt 18)
Jun 14 12:38:52.024 INFO Code.exe is running, wait a bit
Jun 14 12:38:52.524 INFO Checking for running Code.exe processes... (attempt 19)
Jun 14 12:38:52.532 INFO Code.exe is running, wait a bit
Jun 14 12:38:53.032 INFO Checking for running Code.exe processes... (attempt 20)
Jun 14 12:38:53.040 INFO Code.exe is running, wait a bit
Jun 14 12:38:53.540 INFO Checking for running Code.exe processes... (attempt 21)
Jun 14 12:38:53.547 INFO Code.exe is running, wait a bit
Jun 14 12:38:54.047 INFO Checking for running Code.exe processes... (attempt 22)
Jun 14 12:38:54.054 INFO Code.exe is running, wait a bit
Jun 14 12:38:54.554 INFO Checking for running Code.exe processes... (attempt 23)
Jun 14 12:38:54.562 INFO Code.exe is running, wait a bit
Jun 14 12:38:55.062 INFO Checking for running Code.exe processes... (attempt 24)
Jun 14 12:38:55.070 INFO Code.exe is running, wait a bit
Jun 14 12:38:55.570 INFO Checking for running Code.exe processes... (attempt 25)
Jun 14 12:38:55.578 INFO Code.exe is running, wait a bit
Jun 14 12:38:56.078 INFO Checking for running Code.exe processes... (attempt 26)
Jun 14 12:38:56.086 INFO Code.exe is running, wait a bit
Jun 14 12:38:56.586 INFO Checking for running Code.exe processes... (attempt 27)
Jun 14 12:38:56.594 INFO Code.exe is running, wait a bit
Jun 14 12:38:57.094 INFO Checking for running Code.exe processes... (attempt 28)
Jun 14 12:38:57.102 INFO Code.exe is running, wait a bit
Jun 14 12:38:57.602 INFO Checking for running Code.exe processes... (attempt 29)
Jun 14 12:38:57.610 INFO Code.exe is running, wait a bit
Jun 14 12:38:58.110 INFO Checking for running Code.exe processes... (attempt 30)
Jun 14 12:38:58.118 INFO Code.exe is running, wait a bit
Jun 14 12:38:58.618 INFO Checking for running Code.exe processes... (attempt 31)
Jun 14 12:38:58.626 INFO Code.exe is running, wait a bit
Jun 14 12:38:59.126 INFO Checking for running Code.exe processes... (attempt 32)
Jun 14 12:38:59.134 INFO Code.exe is running, wait a bit
Jun 14 12:38:59.634 INFO Checking for running Code.exe processes... (attempt 33)
Jun 14 12:38:59.642 INFO Code.exe is running, wait a bit
Jun 14 12:39:00.142 INFO Checking for running Code.exe processes... (attempt 34)
Jun 14 12:39:00.150 INFO Code.exe is running, wait a bit
Jun 14 12:39:00.650 INFO Checking for running Code.exe processes... (attempt 35)
Jun 14 12:39:00.658 INFO Code.exe is running, wait a bit
Jun 14 12:39:01.158 INFO Checking for running Code.exe processes... (attempt 36)
Jun 14 12:39:01.167 INFO Code.exe is running, wait a bit
Jun 14 12:39:01.667 INFO Checking for running Code.exe processes... (attempt 37)
Jun 14 12:39:01.675 INFO Code.exe is running, wait a bit
Jun 14 12:39:02.175 INFO Checking for running Code.exe processes... (attempt 38)
Jun 14 12:39:02.183 INFO Code.exe is running, wait a bit
Jun 14 12:39:02.683 INFO Checking for running Code.exe processes... (attempt 39)
Jun 14 12:39:02.691 INFO Code.exe is running, wait a bit
Jun 14 12:39:03.191 INFO Checking for running Code.exe processes... (attempt 40)
Jun 14 12:39:03.199 INFO Code.exe is running, wait a bit
Jun 14 12:39:03.699 INFO Checking for running Code.exe processes... (attempt 41)
Jun 14 12:39:03.707 INFO Code.exe is running, wait a bit
Jun 14 12:39:04.207 INFO Checking for running Code.exe processes... (attempt 42)
Jun 14 12:39:04.215 INFO Code.exe is running, wait a bit
Jun 14 12:39:04.715 INFO Checking for running Code.exe processes... (attempt 43)
Jun 14 12:39:04.723 INFO Code.exe is running, wait a bit
Jun 14 12:39:05.223 INFO Checking for running Code.exe processes... (attempt 44)
Jun 14 12:39:05.231 INFO Code.exe is running, wait a bit
Jun 14 12:39:05.731 INFO Checking for running Code.exe processes... (attempt 45)
Jun 14 12:39:05.738 INFO Code.exe is running, wait a bit
Jun 14 12:39:06.238 INFO Checking for running Code.exe processes... (attempt 46)
Jun 14 12:39:06.245 INFO Code.exe is running, wait a bit
Jun 14 12:39:06.745 INFO Checking for running Code.exe processes... (attempt 47)
Jun 14 12:39:06.753 INFO Code.exe is running, wait a bit
Jun 14 12:39:07.253 INFO Checking for running Code.exe processes... (attempt 48)
Jun 14 12:39:07.261 INFO Code.exe is running, wait a bit
Jun 14 12:39:07.763 INFO Checking for running Code.exe processes... (attempt 49)
Jun 14 12:39:07.765 INFO Code.exe is running, wait a bit
Jun 14 12:39:08.265 INFO Checking for running Code.exe processes... (attempt 50)
Jun 14 12:39:08.273 INFO Code.exe is running, wait a bit
Jun 14 12:39:08.773 INFO Checking for running Code.exe processes... (attempt 51)
Jun 14 12:39:08.780 INFO Code.exe is running, wait a bit
Jun 14 12:39:09.280 INFO Checking for running Code.exe processes... (attempt 52)
Jun 14 12:39:09.285 INFO Code.exe is running, wait a bit
Jun 14 12:39:09.785 INFO Checking for running Code.exe processes... (attempt 53)
Jun 14 12:39:09.788 INFO Code.exe is running, wait a bit
Jun 14 12:39:10.288 INFO Checking for running Code.exe processes... (attempt 54)
Jun 14 12:39:10.296 INFO Code.exe is running, wait a bit
Jun 14 12:39:10.796 INFO Checking for running Code.exe processes... (attempt 55)
Jun 14 12:39:10.804 INFO Code.exe is running, wait a bit
Jun 14 12:39:11.304 INFO Checking for running Code.exe processes... (attempt 56)
Jun 14 12:39:11.307 INFO Code.exe is running, wait a bit
Jun 14 12:39:11.807 INFO Checking for running Code.exe processes... (attempt 57)
Jun 14 12:39:11.815 INFO Code.exe is running, wait a bit
Jun 14 12:39:12.315 INFO Checking for running Code.exe processes... (attempt 58)
Jun 14 12:39:12.323 INFO Code.exe is running, wait a bit
Jun 14 12:39:12.823 INFO Checking for running Code.exe processes... (attempt 59)
Jun 14 12:39:12.835 INFO Code.exe is running, wait a bit
Jun 14 12:39:13.331 INFO Checking for running Code.exe processes... (attempt 60)
Jun 14 12:39:13.339 INFO Gave up waiting for Code.exe to exit
Jun 14 12:39:13.339 INFO Checking for possible conflicting running processes... (attempt 1)
Jun 14 12:39:13.345 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:13.346 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:13.346 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:13.346 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:13.396 INFO Checking for possible conflicting running processes... (attempt 2)
Jun 14 12:39:13.404 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:13.404 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:13.404 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:13.404 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:13.604 INFO Checking for possible conflicting running processes... (attempt 3)
Jun 14 12:39:13.612 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:13.612 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:13.612 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:13.612 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:14.062 INFO Checking for possible conflicting running processes... (attempt 4)
Jun 14 12:39:14.070 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:14.070 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:14.070 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:14.070 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:14.870 INFO Checking for possible conflicting running processes... (attempt 5)
Jun 14 12:39:14.878 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:14.878 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:14.878 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:14.878 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:16.128 INFO Checking for possible conflicting running processes... (attempt 6)
Jun 14 12:39:16.136 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:16.136 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:16.136 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:16.136 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:17.936 INFO Checking for possible conflicting running processes... (attempt 7)
Jun 14 12:39:17.944 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:17.944 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:17.944 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:17.944 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:20.394 INFO Checking for possible conflicting running processes... (attempt 8)
Jun 14 12:39:20.402 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:20.402 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:20.402 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:20.402 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:23.602 INFO Checking for possible conflicting running processes... (attempt 9)
Jun 14 12:39:23.610 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:23.610 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:23.610 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:23.610 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:27.660 INFO Checking for possible conflicting running processes... (attempt 10)
Jun 14 12:39:27.668 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:27.668 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:27.668 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:27.668 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:32.668 INFO Checking for possible conflicting running processes... (attempt 11)
Jun 14 12:39:32.676 INFO Kill process if found: 9808, Code.exe
Jun 14 12:39:32.676 INFO Kill process if found: 7900, Code.exe
Jun 14 12:39:32.676 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:32.676 WARN Kill error Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Jun 14 12:39:32.676 ERRO Failed to get process file name: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

**Comment by sixdimensionalarray** [comment]
I had a similar issue.  In my case, I had a hanging Code.exe process running on Windows that I had to kill first using Task Manager, and then when I restarted code and did the update it worked.

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
