### ISSUE TITLE
Can't fold when using JavaScript deconstruction [picture attached]

### ISSUE THREAD

**Issue by Avivhdr** [Microsoft/vscode#51909]
- VSCode Version: 1.24.1
- OS Version: Windows 10 pro 1709

Steps to Reproduce:

1. Updates vs code today.
2. Bug derived from the recent update.
3. See attached picture.

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/23265867/41422409-8861e246-7001-11e8-9f83-42fbd9f1b9cc.png)

**Comment by mjbvz** [comment]
See the syntax aware folding section of the release notes for background and workaround:  https://code.visualstudio.com/updates/v1_24#_syntax-aware-folding-enabled-by-default-for-jsts
