### ISSUE TITLE
"Go To File" shows nonexistent files

### ISSUE THREAD

**Issue by craigjennings11** [Microsoft/vscode#51905]
- VSCode Version: 1.24.0
- OS Version: Windows 10 x64

Steps to Reproduce:
1. Open the explorer and highlight a file
1. Rename the file by changing its extension (any rename works, this just makes the bug apparent)
1. Do `ctrl+p` to bring up the "Go To File" prompt and type the name of the file without its extension. Notice that there are two files listed, one with the new extension and one with the old extension
1. Selecting the one with the old extension will notify the user that it cannot open the file because it does not exist

Does this issue occur when all extensions are disabled?: Yes

In the below example, I renamed `AdminPage.test.js` to `AdminPage.test.ts`. After working for a while, I attempted to go to the new file. Notice that the old file exists in the list and when selected errors.

![image](https://user-images.githubusercontent.com/1683368/41419067-ba9c800e-6fb6-11e8-8248-b4c8e711fd9f.png)

**Comment by roblourens** [comment]
We have https://github.com/Microsoft/vscode/issues/12665 for this. You can also run the "Clear Editor History" command to clear all of them.
