### ISSUE TITLE
"Failed to show text document, should show in editor #undefined"

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51906]
Had this in test failure logs today (when running against stable). It doesn't really have any information to help me track down what's up:

```
  1) rename_provider
       "before each" hook: activate for "renames the class":
     Error: Failed to show text document file:///Users/travis/build/Dart-Code/Dart-Code/test/test_projects/hello_world/lib/empty.dart, should show in editor #undefined
      at .vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:727:849
      at Object.g [as _notify] (.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:76:971)
      at Object.enter (.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:80:277)
      at n.Class.derive._oncancel._run (.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:84)
      at n.Class.derive._oncancel._completed (.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:523)
      at e.resolveOk (.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:545:791)
      at e._receiveReply (.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:636:165)
      at e._receiveOneMessage (.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:473)
      at .vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:634:315
      at .vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:637:395
      at .vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:95:432
      at e.fire (.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:764)
      at Socket.<anonymous> (.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:338)
      at readableAddChunk (_stream_readable.js:178:18)
      at Socket.Readable.push (_stream_readable.js:136:10)
      at Pipe.onread (net.js:560:20)
```

The code that ran around this time was test setup code which closes all open editors then opens the file specified by the test:

```ts
while (vs.window.activeTextEditor) {
	await vs.commands.executeCommand("workbench.action.revertAndCloseActiveEditor");
	await delay(5);
}

doc = await vs.workspace.openTextDocument(file);
editor = await vs.window.showTextDocument(doc);
```

**Comment by DanTup** [comment]
This may be related to `revertAndCloseActiveEditor`. I recently changed to that from `closeActiveEditor` because I had a test flake because it seemed to hang on the loop in my code above. I saw this and wondered whether maybe it was being prompted to save so should use this.

**Comment by bpasero** [comment]
Sorry, but I will not fix your tests.

**Comment by bpasero** [comment]
@DanTup we could start by you providing a full sample code to reproduce (e.g. from a hello world extension). Maybe this could even be an extension test that fails.

**Comment by DanTup** [comment]
@bpasero Sure, if that'll help I'll try. I thought the error might may sense to you and you might be able to explain what causes it so I didn't want to just give you a load of code that may or may not fail (I've never seen it locally, only intermittently on Travis).

I'll see if I can get a repro, even if it means putting a hello world ext. w/ tests on Travis.

**Comment by bpasero** [comment]
@DanTup the error is nothing I am aware of why it is there. Moving back to @jrieken, I am not sure why I got this assigned in the first place.

**Comment by jrieken** [comment]
@bpasero `workbench.action.revertAndCloseActiveEditor` is your command, right?

**Comment by bpasero** [comment]
@jrieken yes it just closes the editor and reverts it if dirty

**Comment by jrieken** [comment]
@DanTup your turn

**Comment by DanTup** [comment]
Can't repro in a hello world so I'm gonna have to start stripping down the full repo, might take me a little while.

It might help if anyone can explain what conditions would trigger this error - it's not obvious to me from reading the Code code.

**Comment by jrieken** [comment]
It means [`findTextEditorIdFor(editor)`](https://github.com/Microsoft/vscode/blob/4ed727989e7242ed32315bbfc6d33cd93224907a/src/vs/workbench/api/electron-browser/mainThreadEditors.ts#L132) did return undefined, which would mean we opened an editor but not an editor widget...

**Comment by bpasero** [comment]
@DanTup this reproduces in stable right? Asking, because during this month some heavy refactoring went into the editor code.

**Comment by DanTup** [comment]
Yeah, it was in stable 4 days. I don't fail my builds on failed tests for Insiders currently, and it  caused some failed builds (unfortunately I restarted them on Travis to see it if was flaky - it was - so now I can't get at the build logs).

The reason I changed to `revertAndCloseActiveEditor` was that my tests were intermittently hanging when I was trying to close just using `closeActiveEditor`. I figured it was maybe prompted to save, but since I don't think you prompt when running tests, it's possible whatever was causing that is the same thing causing this (they were both intermittent).

I tried adding a short delay after closing, in case there was some race; but it didn't help (though it was only 5ms).

**Comment by bpasero** [comment]
@DanTup we never prompt when running extension tests, so `closeActiveEditor` should always close even if the file is dirty.

**Comment by DanTup** [comment]
@bpasero Thought so; I'll change it back to that - though I think there may still be something up with that - the reason I changed it was that it seemed to be hanging (around the same code). It's fairly frequent (I just had it again - https://travis-ci.org/Dart-Code/Dart-Code/jobs/393661378) though so I can change back and do a few builds and see what happens.

**Comment by DanTup** [comment]
Btw, should I need any sort of delay, or is this code safe?

```ts
while (vs.window.activeTextEditor) {
	await vs.commands.executeCommand("workbench.action.closeActiveEditor");
}
```

If `closeActiveEditor` returns before `activeTextEditor` would return null, I might end up calling it way more than required. I currently have a 5ms delay just in case, but if this code is race-y probably 5ms isn't going to stop it potentially being flaky. I'm basically trying to close all active editors at the start of each test to try and keep each run consistent regardless of possible failures before it (since it's not possible AFAIK to reload the window in tests; since they're running inside the extension host?).

**Comment by DanTup** [comment]
I couldn't repro this and I've switched back to `closeActiveEditor`. I think there's still an issue there (I think it sometimes hangs) but I'll raise an issue about that next time I spot it.
