### ISSUE TITLE
Issue updating VSCODE

### ISSUE THREAD

**Issue by phatguy29** [Microsoft/vscode#51907]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2102875/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
