### ISSUE TITLE
default bell is the most annoything thing that distracts me from my work

### ISSUE THREAD

**Issue by toddbellMSFT** [Microsoft/vscode#51910]
We have written the needed data into your clipboard because it was 
Issue Type: <b>Bug</b>

It pulls me out of my current work state of flow when I hear this bell (does not mesh with my background music).

repro:
1. open terminal (either powershell or WSL bash)
2. click backspace right away

expected: nothing (you don't need to tell me that clicking backspace is doing nothing, I can see that)

actual:

bell sound that irritates me, sends a thought "wow that's irksome" and ends whatever I was attempting to do before.

I want this turned off because it's distracting and happens frequently, but there's no obvious way to turn this off.

I tried the powershell command:
Set-PSReadlineOption -BellStyle None 

which works once, but when I close and re-open VScode, this is no longer the case and I get this bell sound again. 

for wsl bash I tried adding 'set bell-style none' in my /etc/inputrc file, but that does squat for vscode terminal.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (22.96GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
githistory|don|0.4.1
git-project-manager|fel|1.6.1
rainbow-csv|mec|0.4.1
python|ms-|2018.5.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
team|ms-|1.136.0
vim|vsc|0.12.0

</details>
too large to send. Please paste.

**Comment by chrmarti** [comment]
The default is off: `"terminal.integrated.enableBell": false`, please check your settings.

**Comment by Tyriar** [comment]
I think the powershell bell is configured differently to `terminal.integrated.enableBell`. @toddbellMSFT  I think the proper way to disable it is to add `Set-PSReadlineOption -BellStyle None` to your powershell start up script

**Comment by toddbellMSFT** [comment]
@chrmarti Please open back up. My settings for terminal.integrated.enableBell are set (both default and custom) to false. So this setting seems to be broken.

Beep still happens.

**Comment by Tyriar** [comment]
@toddbellMSFT you should look into setting up a powershell profile which will disable the bell on start up, there's no plans on having `terminal.integrated.enableBell` drive this. It may work in the future but that relies on work from the Windows Console team.
