### ISSUE TITLE
Creating a new file on a sshfs filesystem raises filePermission

### ISSUE THREAD

**Issue by smx-smx** [Microsoft/vscode#51915]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Install WinFSP from https://github.com/billziss-gh/winfsp/releases
2. Install sshfs-win from https://github.com/billziss-gh/sshfs-win/releases
3. Map a remote sshfs share - instructions at https://github.com/billziss-gh/sshfs-win/blob/master/README.md
4. Try to create a file on the network share with explorer, cmd, notepad++, etc. (they all work)
5. Try to create a file from vscode in the sidebad (after opening a folder with vscode and using the "new file" button on the sidebar/workspace).
**Result**:
filePermission is raised, "Permission denied writing to file"

Update: creating directories from vscode works instead, only happens when creating files

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.70GB (6.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details>

**Comment by bpasero** [comment]
@smx-smx would you be willing to conduct an experiment by installing node.js and trying it from there? I can share more details if you are willing to. node.js can be downloaded from https://nodejs.org/en/download/

**Comment by smx-smx** [comment]
NodeJS seems to do just fine

```
> const fs = require("fs");
undefined
> fs.unlinkSync("Z:/var/www2/test.html");
undefined
> fs.existsSync("Z:/var/www2/test.html");
false
> fs.writeFileSync("Z:/var/www2/test.html", "Hello");
undefined
> console.log(fs.readFileSync("Z:/var/www2/test.html").toString("ascii"));
Hello <-- content succesfully written and read back
undefined
> fs.truncateSync("Z:/var/www2/test.html", 0);
undefined
> console.log(fs.readFileSync("Z:/var/www2/test.html").toString("ascii"));
undefined
```

I did a brief debugging, the problem is here:
https://github.com/Microsoft/vscode/blob/44aa6c8aac6207f4e4d057287fa8a4cca18c7550/src/vs/workbench/services/files/electron-browser/fileService.ts#L595

That's the source of the exception. When the promise is awaited below, it throws EPERM.

```paths.dirname(absolutePath)
"z:\var\www\test"```

**Comment by bpasero** [comment]
@smx-smx thanks a lot for taking the time to debug this! What I wonder is the output of `fs.statSync("Z:/var/www2");` (assuming we are talking about `Z:/var/www2/test.html`. If that one returns a valid stat, we can make changes to our `mkdirp` function to handle this case.

**Comment by smx-smx** [comment]
```
> fs.statSync("Z:/var/www2");
Stats {
  dev: 3458570112,
  mode: 16822,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: undefined,
  ino: 0,
  size: 0,
  blocks: undefined,
  atimeMs: 1529074657000,
  mtimeMs: 1529074542000,
  ctimeMs: 1529074542000,
  birthtimeMs: 0,
  atime: 2018-06-15T14:57:37.000Z,
  mtime: 2018-06-15T14:55:42.000Z,
  ctime: 2018-06-15T14:55:42.000Z,
  birthtime: 1970-01-01T00:00:00.000Z }
```

(remote user is root, mapped to a local user)

**Comment by bpasero** [comment]
@smx-smx and `fs.mkdirSync("Z:/var/www2")` throws an EPERM error right?

**Comment by smx-smx** [comment]
Yep
```
> fs.mkdirSync("Z:/var/www2");
Error: EPERM: operation not permitted, mkdir 'Z:\var\www2'
    at Object.fs.mkdirSync (fs.js:885:18)
>
```

**Comment by smx-smx** [comment]
It seems to be an issue on the `sshfs-win` side, that it reports `-EPERM` for existing directories.
`cmd` also gives access denied when trying to `mkdir` an existing directory, but explorer promts for a directory merge instead

What vscode could do to work around it is to check if the directory actually exists before trying to create it.

**Comment by bpasero** [comment]
Yeah something like that. Thanks for the help 👍

**Comment by bpasero** [comment]
@smx-smx how about this implementation, can you try:

```typescript
export function mkdirp(path: string, mode?: number): TPromise<boolean> {
	const mkdir = () => {
		return nfcall(fs.mkdir, path, mode).then(null, (mkdirErr: NodeJS.ErrnoException) => {

			// ENOENT: a parent folder does not exist yet
			if (mkdirErr.code === 'ENOENT') {
				return TPromise.wrapError(mkdirErr);
			}

			// Any other error: check if folder exists and
			// return normally in that case if its a folder
			return nfcall(fs.stat, path).then((stat: fs.Stats) => {
				if (!stat.isDirectory()) {
					return TPromise.wrapError(new Error(`'${path}' exists and is not a directory.`));
				}

				return null;
			}, statErr => {
				return TPromise.wrapError(mkdirErr); // bubble up original mkdir error
			});
		});
	}

	// stop at root
	if (path === paths.dirname(path)) {
		return TPromise.as(true);
	}

	// recursively mkdir
	return mkdir().then(null, (err: NodeJS.ErrnoException) => {

		// ENOENT: a parent folder does not exist yet, continue
		// to create the parent folder and then try again.
		if (err.code === 'ENOENT') {
			return mkdirp(paths.dirname(path), mode).then(mkdir);
		}

		// Any other error
		return TPromise.wrapError<boolean>(err);
	});
}
```

**Comment by smx-smx** [comment]
It works aswell 👍 

By the way thanks a lot for the prompt reply and support, even on weekends :)
