### ISSUE TITLE
Mouse Cursor Leaves Debug Property Inspector Popup, Popup Closes

### ISSUE THREAD

**Issue by MattGrdinic** [Microsoft/vscode#51916]
Issue Type: <b>Bug</b>

When you mouse over a property in the debugger and start scrolling in it's attribute list (e.g, a class variable with 30 or so properties), everything works fine if you keep your mouse cursor over the popup window. However, if your mouse cursor leaves the bounds of the property popup the popup closes, even if you're actively scrolling. The expected behavior is like all other OS windows, if I'm actively mouse down *and* scrolling, the window should never close by itself. 

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|24.00GB (1.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
vscode-intelephense-client|bme|0.8.8
xml|Dot|2.3.0
php-debug|fel|1.12.3
vscode-icons|rob|7.23.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I can not reproduce this if I scroll and the hover is still in view
Please let me know what I am doing differently than you.

If the hvoer start location moves out of view then we hide the hover as designed behavior.

![hover](https://user-images.githubusercontent.com/1926584/41464144-8ead1bd2-7099-11e8-9995-c74e576d32d9.gif)

**Comment by MattGrdinic** [comment]
My apologies, I should have been more precise in my explanation! Thank you for the reply, and please allow me to take another stab at this:

So scrolling the entire *page* is fine, it's the scrolling the properties popup window that's at issue. To reproduce:

1. Mouse over a field with enough properties to cause a scroll bar to appear in the popup (just like your video)
2. Mouse over and then click the scroll bar in the popup.
3. Start scrolling in any direction.
4. With the scroll action still active (mouse down), move the mouse cursor outside of the popups bounds.

On Win and Mac, as soon as the mouse cursor leave the bounds, the popup closes. 

I realize this may be by design, but it feels very strange if so, considering the user is in an active action taken upon the popup (scrolling). 

I know, mouse wheel : ) But For some reason I've gotten in the habit of this, and would be neat to see this not be the case.

Thank you again for looking into this, really appreciate the work being done, excellent stuff!

**Comment by isidorn** [comment]
Thanks. I acknowledge this limitation and I have no immediate plans to fix this.
Though a simple PR which fixes this is welcome
Code pointer https://github.com/Microsoft/vscode/blob/82b74e2679f0009e33338c2339cdebe1d0cad256/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L422
