### ISSUE TITLE
Integrated terminal - last column is hidden

### ISSUE THREAD

**Issue by Arnaud73** [Microsoft/vscode#51914]
Issue Type: <b>Bug</b>

In the last 2 releases of VS Code for Mac OS (Sierra), the integrated terminal does not show the last column. If a command spans on multiple lines, the last character of each line disappears.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_4539476|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
EditorConfig|Edi|0.12.4
gc-excelviewer|Gra|2.0.21
material-icon-theme|PKi|3.5.0
vscode-docker|Pet|0.0.27
code-settings-sync|Sha|2.9.2
quokka-vscode|Wal|1.0.130
html-css-class-completion|Zig|1.17.1
vscode-file-peek|abi|1.0.1
vscode-icontheme-nomo-dark|be5|1.3.5
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.4
vscode-dash|dee|1.10.0
createuniqueid|don|0.0.3
xml|Dot|2.3.0
gitlens|eam|8.3.5
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.30
vscode-npm-script|eg2|0.3.4
LogFileHighlighter|emi|2.4.0
prettier-vscode|esb|1.5.0
auto-rename-tag|for|0.0.15
AngularMaterial|har|6.0.0
vscode-text-pastry|jkj|1.2.0
docthis|joe|0.7.1
Angular2|joh|6.1.1
import-sorter|mik|2.0.4
vscode-todo-parser|min|1.9.1
vscode-language-pack-fr|MS-|1.24.3
azure-account|ms-|0.4.0
debugger-for-chrome|msj|4.6.0
angular2-inline|nat|0.0.17
view-in-browser|qin|0.0.5
vscode-icons|rob|7.23.0
sass-indented|rob|1.4.9
code-spell-checker|str|1.6.10
enumerator|swi|0.0.6
vscode-todo-highlight|way|0.5.12
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.6.0

(3 theme extensions excluded)

</details>

Here is an example:
![image](https://user-images.githubusercontent.com/3791370/41426662-9dff6a76-7004-11e8-8879-092420e25915.png)
As you can see, the "t" has disappeared.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51479
