### ISSUE TITLE
Integrated terminal should be added to the interface overview

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#51913]
The Integrated terminal is a key USP for VS Code, and should be added to the interface overview. I imagine opening the interface overview would open the integrated terminal and an annotation is added.

<img width="1552" alt="screen shot 2018-06-14 at 9 56 26 am" src="https://user-images.githubusercontent.com/173559/41426681-399ad566-6fb9-11e8-9600-d556691c6357.png">

Per our discussions on the getting started video @egamma

**Comment by Tyriar** [comment]
I can overlay a fake terminal, actually opening a terminal might be a bad idea as on Windows a notification will pop up and on some environments the terminal will immediately close (like if a sysadmin sets `$SHELL` to `/bin/false`.
