### ISSUE TITLE
Debug breakpoints not working with ts-node or ts-jest

### ISSUE THREAD

**Issue by gfrancischini** [Microsoft/vscode#51923]
- VSCode Version: 1.24.0
- OS Version: Windows 8

```
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:02.816Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32
```

Steps to Reproduce:

1. Clone this repo https://github.com/Microsoft/vscode/issues/45657
2. Add a breakpoint to the file index.test.ts
3. Run the debugger (Jest configuration)

The breakpoints will not hit. 

This seems to be the same issue: https://github.com/Microsoft/vscode/issues/45657

**Comment by roblourens** [comment]
Seems to work for me now.
