### ISSUE TITLE
VSCode does not show/save Portuguese chars correctly

### ISSUE THREAD

**Issue by bazizi** [Microsoft/vscode#51922]
Issue Type: <b>Bug</b>

Example:

	static UCHAR szPortugueseAnsiChars[] = "cordadamorteumagradeçaovocêéboavindatrêscinqüêntamilhãocinqüêntamilharesmarço";
	static WCHAR wszPortugueseUnicodeChars[] = L"cordadamorteumagradeçaovocêéboavindatrêscinqüêntamilhãocinqüêntamilharesmarço";

The above are saved/shown as:

	static UCHAR szPortugueseAnsiChars[] = "cordadamorteumagrade�aovoc��boavindatr�scinq��ntamilh�ocinq��ntamilharesmar�o";
	static WCHAR wszPortugueseUnicodeChars[] = L"cordadamorteumagrade�aovoc��boavindatr�scinq��ntamilh�ocinq��ntamilharesmar�o";

**Note:** Worse than that, the corrupted characters are totally ignored by the diff tool so developers **might push them by accident**

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.69GB (1.27GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.0.0
spellright|ban|2.5.2
gitlens|eam|8.3.5
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.17.4
PowerShell|ms-|1.7.0

</details>

**Comment by V-ed** [comment]
This seems like a file encoding issue on your side.

Make sure your file is in UTF-8 : https://code.visualstudio.com/docs/editor/codebasics#_file-encoding-support.

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
