### ISSUE TITLE
Weird Extension error

### ISSUE THREAD

**Issue by 100Errors** [Microsoft/vscode#51927]
- VSCode Version: 1.24.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode
2. Go to Plugins
3. Type in "TODO" or "todo"
4. Power consumption increases, window freezes for few seconds

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@100Errors To confirm, this happens when you're typing in the "Search Extensions i Marketplace" input box? Please see our guide for performance issues: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by 100Errors** [comment]
![image](https://user-images.githubusercontent.com/34282308/41453772-4a665ffa-7077-11e8-96f7-3751a1299edf.png)

**Comment by sandy081** [comment]
@100Errors Does it happens when you open an extension in the editor by clicking on it? Or just while typing ?

**Comment by 100Errors** [comment]
after I click on an extension / sometimes if I press enter after I typed it

**Comment by sandy081** [comment]
From the profile, I see this is getting hanged while opening the editor. 

@mjbvz For Web view editor
@alexandrudima For editor

Any insights?

**Comment by alexandrudima** [comment]
@sandy081 Maybe I'm opening the wrong attachment, but for me it looks like execution is stuck in a regular expression:

![image](https://user-images.githubusercontent.com/5047891/41918465-aea343c8-795c-11e8-84f6-0e255d81e4c3.png)

Searching for `tok`, this looks like some sort of invocation of `marked.js` ?

**Comment by mjbvz** [comment]
Do you see this in the latest insiders? Marked has had a few issues with regex catastrophic backtracking. I picked up the latest version of marked this iteration
