### ISSUE TITLE
JSDoc Type Import Error 

### ISSUE THREAD

**Issue by IanMitchell** [Microsoft/vscode#51926]
- VSCode Version: 1.24.0
- OS Version: Windows 10 and OSX, most recent versions

![bug](https://cldup.com/iJb2kzyH20.jpeg)

Despite correctly importing the type and displaying it when hovering over the typedef, when using the function the parameter type displays as the import path. New to JSDoc so good chance I'm doing something wrong here though!

If you remove the exported `test` function in `a.js`, things work as expected. Hopefully that's helpful!

---

Steps to Reproduce:

```javascript
// a.js
/**
 * Some Generic Type
 * @typedef {Object} KeyValue
 * @property {string} key item key
 * @property {string} value item value
 */

 export function test() {
   console.log('export');
 }
```

```javascript
// b.js
/** @typedef {import('./a').KeyValue} KeyValue */
// ^ hover displays correct information

/**
 * Test Function
 * @param {KeyValue} item logs this item
 */
function logValue(item) {
  console.log(`${item.key}: ${item.value}`);
}

logValue(<CURSOR>
// ^ displays "import"
```

**Comment by mjbvz** [comment]
Looks fixed in VS Code insiders:

![screen shot 2018-06-14 at 4 01 41 pm](https://user-images.githubusercontent.com/12821956/41442477-43d3549e-6fec-11e8-9815-38c0982aac74.png)

**Comment by IanMitchell** [comment]
Yup, I see the same. Perfect, thank you!
