### ISSUE TITLE
Less than one page of text should not be scrollable

### ISSUE THREAD

**Issue by guycnicholas** [Microsoft/vscode#51929]
[shouldNotScroll.mov.zip](https://github.com/Microsoft/vscode/files/2103941/shouldNotScroll.mov.zip)
Issue Type: <b>Feature Request</b>

If I have a text window open with less than one page of text I should not have a scrollbar.  I assume the current behavior is a feature since it exists in both VS and VSCode, but I fail to see a benefit.  If I scroll the text so that only the last line of the file is visible at the top of the screen, I am unable to interact with any of the blank area that fills the window, so what is the point?  I would at least like there to be an option to allow me to disable the behavior. 

I have attached a video of a 41 line file that I shows what I am talking about.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 16.7.0

**Comment by RMacfarlane** [comment]
Thanks for the clear write up! There is actually a setting to control this - try adding `"editor.scrollBeyondLastLine": false` to your settings

**Comment by guycnicholas** [comment]
Thanks!  I pointed this out to people at Build both this year, for VSCode, and last year for VisualStudio and nobody mentioned a setting.
