### ISSUE TITLE
Set tabSize based on file extension

### ISSUE THREAD

**Issue by JasonMFry** [Microsoft/vscode#51924]
Issue Type: <b>Settings Search Issue</b>

My team uses 2 spaces for Haskell files but Elm files use 4 spaces because that's how elm-format works (I think). It would be nice to be able to set the tabSize based on the file extension.

VS Code version: Code - Insiders 1.25.0-insider (11b0f3a40be055e02b721abbb93cb0012818f99e, 2018-06-14T05:11:13.121Z)
OS version: Darwin x64 17.5.0

Query: elm
Literal matches: 19

**Comment by RMacfarlane** [comment]
Thanks for the feature request! There's an existing feature to configure settings for specific languages which should fit this use case: https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings
