### ISSUE TITLE
warnings are not updated after changing language mode

### ISSUE THREAD

**Issue by wassimoo** [Microsoft/vscode#5193]
- VSCode Version: 0.10.8
- OS Version: windows 10

i changed language mode accidentally from HTML to JS , Errors and warnings appeared which is normal , but after changing it back to HTML mode errors weren't updated. 

![screenshot 14](https://cloud.githubusercontent.com/assets/12980387/14466360/66732cde-00ce-11e6-8ecb-60dc065e0535.png)

**Comment by dbaeumer** [comment]
@jrieken Do you remember in which version we switched to Salsa. The tsserver doesn't validate unsaved files :-(. 

@wassimoo do you have any linter extension installed (e.g. eslint or jshint)

**Comment by wassimoo** [comment]
yes actually i had one called ' HTML hint' but even after uninstalling the ext and updating my vs code to 0.10.11 version the problem still exists .. so i think it has nothing to do with the extension

**Comment by jrieken** [comment]
@dbaeumer I believe that was the Feb release

**Comment by dbaeumer** [comment]
I can't reproduce this anymore with the next stable build. Although not with the latest insider. I am not sure but when enabling Salsa I know that we left the old JS worker based code in. I am pretty sure the errors came from there.

@wassimoo please reopen if you still see the problem on the latest insider or the next stable.

![capture](https://cloud.githubusercontent.com/assets/1931590/14522368/86144cb0-022e-11e6-8552-b9995425c7d9.png)

**Comment by vsccarl** [comment]
I'm able to repro this in the latest alpha. Switching from JS to CSS and back with auto detect.

**Comment by dbaeumer** [comment]
@vsccarl can you please open a new issue with steps how to reproduce this with CSS and JS. The original report talk about JS and HTML and I am not able to reproduce.
