### ISSUE TITLE
Can't launch VS Code from Linux terminal: symbol lookup error

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [Microsoft/vscode#51937]
Few days or weeks ago my VS Code lost the ability to start from the terminal. This is what it prints:
`
/usr/share/code/bin/../code: symbol lookup error: /usr/share/code/bin/../code: undefined symbol: _ZN2v814ScriptCompiler20ExternalSourceStream11SetBookmarkEv
`
I have tried remove `/usr/share/code` and reinstall from .deb but it did not help. Running VS Code from Nautilus or by searching in Ubuntu works perfectly. I have tried to google this symbol and even tried to reinstall `nodejs` and other packages but it did not help.

- VSCode Version:
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Ubuntu 18.04

Steps to Reproduce:
1. Type `code` or `/usr/share/code/code` in terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Did this only just start happening? I can't repro on my side.

**Comment by ArkadiuszNiemiec** [comment]
Yes, it just started. It must be a problem with my environment. I think this symbol comes from `v8` library but I cannot locate it.
This is the `code.desktop` file that actually works:
```
cat /usr/share/applications/code.desktop
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %F
Icon=code
Type=Application
StartupNotify=true
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.23

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code --new-window %F
Icon=code
```
I have tried `code --new-window` and `code --unity-launch` but without any luck.

**Comment by Tyriar** [comment]
This is strange that it works via nautilus but not through the command line when you're calling what the desktop file calls 😕, I'm a bit stumped on this one. @bpasero any ideas?

**Comment by ArkadiuszNiemiec** [comment]
If the snap version is working correctly then it must be something with my libs. Maybe I have an old version of something? But this does not explain why nautilus .desktop file works. Are there any environmental variables that it uses?

**Comment by bpasero** [comment]
@ArkadiuszNiemiec does it reproduce if you run from a [clean environment](https://unix.stackexchange.com/questions/48994/how-to-run-a-program-in-a-clean-environment-in-bash)?

**Comment by bpasero** [comment]
@ArkadiuszNiemiec anything with `env -i code --verbose` ?

**Comment by ArkadiuszNiemiec** [comment]
`env -i code` doesn't work because of lack of `DISPLAY=:0` variable.
I have checked every single one of them and found out that my `LD_LIBRARY_PATH` was the cause of the problem:
```
LD_LIBRARY_PATH=/home/username/catkin_ws/devel/lib:/opt/ros/melodic/lib
```
...both paths come from ROS Melodic, which I need in my workflow :disappointed:

**Comment by Tyriar** [comment]
It sounds like VS Code is working as expected if you're messing with `LD_LIBRARY_PATH`? You could try tweak `LD_LIBRARY_PATH` when you launch VS Code like this:

```
LD_LIBRARY_PATH=blah code
```

And even include that in the `.desktop` entry.

I'm closing this as designed.

**Comment by ArkadiuszNiemiec** [comment]
I really don't think that it works as designed but it's your call. I will write a script that clears this env variable before running code but I still think it's just a workaround.

**Comment by Tyriar** [comment]
@ArkadiuszNiemiec `LD_LIBRARY_PATH` defined where libraries are looked up I believe, if you're messing with that bad things can happen.

**Comment by ArkadiuszNiemiec** [comment]
@Tyriar If I understand it correctly the Code is looking for some lib that is in both system library and in the path from `LD_LIBRARY_PATH`. Since the `LD_LIBRARY_PATH` is before the cache from `/etc/ld.so.cache` it tries to use a lib version from that path, right?
Nonetheless, I still think that any app should work with paths added (without overwriting default ones) to environment variables. Code is the only software that doesn't wont to work with Robotic Operating System installed and configurated.
Thank you anyway, keep up a great work!
