### ISSUE TITLE
Node.js doesn't quit while stop debugging.

### ISSUE THREAD

**Issue by chesteryang** [Microsoft/vscode#51933]
Issue Type: <b>Bug</b>

Everytime starting debugging asp.net core react app, after stop debugging, four more nodejs processes hanging in Task Manager. it quickly consumed all memory and make computer not responsive.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.1.9
vscode-eslint|dba|1.4.12
gitlens|eam|8.3.5
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.31
classic-asp|ili|0.0.4
python|ms-|2018.5.0
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.6.0
vscode-icons|rob|7.23.0

</details>

![nodejs](https://user-images.githubusercontent.com/7731284/41439708-0bbbe24a-6fe9-11e8-8af1-f70ef151dad4.jpg)

**Comment by chesteryang** [comment]
In debugging, process (id=13360) is a child process under dotnet.exe process (id=11188)

![indebugging](https://user-images.githubusercontent.com/7731284/41665243-bcaa6426-7464-11e8-8b42-015be32a27c1.jpg)

Out of debugging, the process (id=13360) didn't get killed and its parent is gone.

![outofdebugging](https://user-images.githubusercontent.com/7731284/41665372-02aa9b08-7465-11e8-98d3-0bfbc30dfc84.jpg)

**Comment by weinand** [comment]
Please file this against the csharp extension.
