### ISSUE TITLE
Allow for refactoring (renaming) across multiple Typescript projects

### ISSUE THREAD

**Issue by dpsthree** [Microsoft/vscode#5194]
I have a folder that contains a Typescript Client and Typescript Node Server subfolder. There is a third top level directory, common, where we store our isomorphic Typescript code.

In order for a rename to work across files a tsconfig.json file is needed that includes the top module of your project and all submodules must be imported properly.

When attempting to perform a rename of a class defined in the common folder the action is only applied to one of the two typescript projects. Adding a top level tsconfig.json that points to the starting modules of both projects did not change this behavior.

Ideally, a refactor would follow all tsconfig.json module trees as needed.

**Comment by egamma** [comment]
Moving to the typescript repository.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#8058
