### ISSUE TITLE
keybinding openInTerminal resuing existing terminal

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#51943]
I have this keybinding:

```json
    {
        "key": "meta+x",
        "command": "openInTerminal"
    }
```

This is practical to switch command-line between projects in the workspace, without having to `cd ../other-project`

But this command creates a new terminal instance every time, except if I don't forget to press Ctrl+D before

What I'd like is something like that, to avoid creating new terminals

```json
    {
        "key": "meta+x",
        "command": "openInTerminal",
        "args": {
             "useExisting": true
         }
    }
```
_________

Also, It would be great if the terminal select include project names so instead of 
```
1: bash
2: bash
3: bash
```

I'd see
```
1: bash - dashboard
2: bash - api-gql
3: bash - redis-worker
```
for example

**Comment by Tyriar** [comment]
`openInTerminal` was not designed for this, you could write an extension to accomplish your goal
