### ISSUE TITLE
what is rg.exe，it takes up much source

### ISSUE THREAD

**Issue by simplast** [Microsoft/vscode#51948]
![Uploading QYQZ{EK$}`L_3RWO`D21P~S.png…]()
when i open vscode ,CPU will be used 98%

**Comment by yume-chan** [comment]
rg means [ripgrep](https://github.com/BurntSushi/ripgrep), is a very fast text searching tool, Code uses it for searching text in folders.

It should launch when you open Code.

**Comment by simplast** [comment]
![1n snzfxc u8 3f 4exee](https://user-images.githubusercontent.com/29967921/41507191-38293bce-7260-11e8-939f-51883aaf6e38.png)
![qyqz ek l_3rwo d21p s](https://user-images.githubusercontent.com/29967921/41507192-3867f56c-7260-11e8-8111-c3f731851563.png)
i had to delete it,it seems to be a bug

**Comment by roblourens** [comment]
Can you get the command line arguments that rg.exe was launched with? Most likely this is from an extension.

**Comment by simplast** [comment]
do you mean this?
![xx](https://user-images.githubusercontent.com/29967921/41725936-9c12bc3c-75a3-11e8-9887-4d91b14efe49.png)

**Comment by roblourens** [comment]
I mean, in the Task Manager, you can right click the columns and show "Command line". Then get the command line for rg.exe so we can see why it's running.

**Comment by simplast** [comment]
![xc](https://user-images.githubusercontent.com/29967921/41816480-d08affd0-77b8-11e8-84e9-d3039d8df2d6.png)

**Comment by roblourens** [comment]
One of your extensions is searching for .css, .less, .scss files
