### ISSUE TITLE
Upgrade to 1.24.1 has broken TypeScript intellisense and other functionality

### ISSUE THREAD

**Issue by nero120** [Microsoft/vscode#51942]
I just upgraded to 1.24.1 and now all of my .ts files have no intellisense, rename, go to defintion, etc. The TypeScript version has also disappeared from the status bar:

![image](https://user-images.githubusercontent.com/4236238/41443146-0e9a12da-7033-11e8-9dba-76004e135250.png)

Removing extensions, deleting node_modules and running npm install made no difference.

**Comment by eugeneross** [comment]
Having same issues with the addition of installed snippets not showing up.

**Comment by kieronlanning** [comment]
I've got the same problem. No syntax highlighting either.

**Comment by nero120** [comment]
I be interested to understand how this *major* issue crept through the "dogfooding" (not a verb btw) process and pre-release testing...

**Comment by mjbvz** [comment]
Please test in VS Code insiders. If you still see this error, provide more information about your project structure. Do you see this in all workspaces?

**Comment by chriswa** [comment]
I had the same (or a similar problem.)

Try opening a different folder, then opening your project folder again.

**Comment by yunxiange** [comment]
I've got the same problem. No intellisense, rename, go to defintion, etc.

**Comment by mjbvz** [comment]
Closing as needs more info from original poster

**Comment by nero120** [comment]
@mjbvz this is not a community project, i do not have time to test as I have my own projects to work on. Obviously there is an issue with 1.24.1 as you can see from all the replies and upvotes so why are you closing it? Don't you test updates thoroughly before you release them or do you just wait for things to break and get users to test them for you?

I had this issue with multiple workspaces, and as i said in the opening post, removing extensions made no difference.

Re-open this issue please.

**Comment by mjbvz** [comment]
Please answer [my questions](https://github.com/Microsoft/vscode/issues/51942#issuecomment-397701715) then

**Comment by nero120** [comment]
> Please test in VS Code insiders

Nope, that's the job of Microsoft's QA team. I assume you guys have one?

> Do you see this in all workspaces?

Yes.

**Comment by nero120** [comment]
I thought i answered your questions? What are you asking me to do?

**Comment by mjbvz** [comment]
Test in the latest VS code insiders build. If that does not work, you can also try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

**Comment by kieronlanning** [comment]
@nero120 @mjbvz I dare say this is getting a little heated.

Given lots of people, like yourself no-doubt, are quite busy and having this very issue, there is obviously a problem somewhere.

A blanket 'Give me all the exact information, or I'm not going to look into it' probably isn't the right response.

What can we do to resolve this immediate issue of lack of information for you?

Can you post steps here, that are concise and appropriate, rather than getting everyone doing a link-chase through the internet.

**Comment by nero120** [comment]
@kieronlanning well said.
