### ISSUE TITLE
unable to debug extHostTask.ts - ReferenceError on defined, in-scope variables...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#51940]
i'm running into an issue while trying to inspect variables within the extension host process while debugging my extension. it seems under certain circumstances variables are not available for inspection. 

despite being in scope and clearly defined, i get `ReferenceError: <variable> is not defined` when attempting to inspect the variable.

![screen shot 2018-06-14 at 3 57 35 pm](https://user-images.githubusercontent.com/367674/41442466-35570960-6fec-11e8-8d95-b30e94ffde2b.png)

perhaps it's an issue w/ sourcemaps and / or sourcemap support in Chromium? 🤷‍♂️

Steps to Reproduce:

1. debug an extension which uses `vscode.tasks.executeTask()` API
2. set a breakpoint at your `executeTask` and step into the function
3. enter `task` into the debug console to try and see its value

- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5

**Comment by weinand** [comment]
Yes, most likely this is a source map issue: local variables are renamed by the TS transpiler but the source map does not reflect that. Try to find the real names in the Variables view and then use those name in the debug console.

**Comment by roblourens** [comment]
I don't think there's anything to be done on vscode's side unless you have more details to show that it's a vscode issue.

**Comment by busticated** [comment]
well, shouldn't the source map be correct? i'm confused how this could be anything but an issue w/ vscode.
