### ISSUE TITLE
Notice prompt covers search bar

### ISSUE THREAD

**Issue by linxiangjun** [Microsoft/vscode#51950]
- VSCode Version:1.24.1
- OS Version:WIN10

Steps to Reproduce:

1.Input 'config\' in search bar,close it
2.use Ctrl + F to open search bar

Does this issue occur when all extensions are disabled?: Yes

**Comment by linxiangjun** [comment]
![issue](https://user-images.githubusercontent.com/20981110/41458407-14d171f8-70b9-11e8-935e-b35484248a42.jpg)

**Comment by rebornix** [comment]
@linxiangjun do you have regex option turned on in your find widget? It seems the content in the input box of the find widget is `content\` and the regex option is turned on.

**Comment by linxiangjun** [comment]
@rebornix you are right,The regex option is turned on

**Comment by linxiangjun** [comment]
In this case it will happen

**Comment by rebornix** [comment]
Reproduce steps:

* Open find widget
* Type in `content\` and turn on the regex mode
* Dismiss the find widget
* Open find widget again.
