### ISSUE TITLE
copy line and paste in the same file doesn't work

### ISSUE THREAD

**Issue by Tech-49** [Microsoft/vscode#51953]
Issue Type: <b>Bug</b>

Step 1:
Create sample file called sample.php

Step 2:
Put this line -- echo "Sample file"

Step 3:
try to copy line by pressing CTRL+c

Step 4:
try to paste in next line -- under the notification window It's saying "command 'test' not found.

I tried to uninstall and install 2-3 time still leg. 

Version detail
--------------

Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.12GB free)|
|Process Argv|F:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by RMacfarlane** [comment]
@Tech-49 Thanks for reporting this. Did you ever install any extensions?

**Comment by Tech-49** [comment]
Thanks for quick response.

No didn't installed any kind of extensions yet.

**Comment by Tech-49** [comment]
FYI I'm using Windows 8.

**Comment by rebornix** [comment]
@Tech-49 can you check if there is anything in your vscode extensions folder under your user folder `{USERFOLDER}/.vscode/extensions`? For example, on my machine the path is `C:\Users\ME\.vscode\extensions>`

**Comment by Tech-49** [comment]
I'll provide more information, there is no reason to close this.
