### ISSUE TITLE
Can't debug extension 

### ISSUE THREAD

**Issue by 025PRO** [Microsoft/vscode#51962]
Can't debug any extension for vscode. Clicking on debug shows infinite loader and "Building..." text in status bar.
<img width="440" alt="screen shot 2018-06-15 at 10 34 09 am" src="https://user-images.githubusercontent.com/4717910/41453689-bf09b70c-7087-11e8-9f18-70ff27f580d5.png">
Also this errors appears in inspector.

<img width="803" alt="screen shot 2018-06-15 at 10 29 00 am" src="https://user-images.githubusercontent.com/4717910/41453512-1250087c-7087-11e8-93ee-0eb77048560d.png">

- VSCode Version: 1.22.2
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

1. generate extension project via yo code
2. run debugger

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@Tyriar I'm seeing the 'syncScrollArea' issue sometimes too. Please note that EH debugging does not involve the terminal at all (because it uses the debug console exclusively).

**Comment by Tyriar** [comment]
This was fixed back in April, I suspect you were just on an older version when you saw it https://github.com/xtermjs/xterm.js/pull/1381, xterm.js was also lagging behind for a while.
