### ISSUE TITLE
[bug] vscode don't detect using variable in "import { match } from 'react-router';"

### ISSUE THREAD

**Issue by believer-ufa** [Microsoft/vscode#51969]
I think vscode has some problem on matching imported variables from another packages.

![image](https://user-images.githubusercontent.com/801727/41455755-b3ee6c40-7097-11e8-9001-c42329e87f1d.png)

It happens only on that variable and that package. Another packages and variables working fine.

VSCode version:

```
1.24.1
24f62626b222e9a8313213fb64b10d741a326288
x64
```

OS: Arch linux, updated on 2018.06.15

Steps to Reproduce:

1. Write code:

```
import { match } from 'react-router';
match();
```

2. See that VSCode thought that we don't use `match` variable.

Does this issue occur when all extensions are disabled?: Yes

------

Maybe because `match` variable in 'react-router' has some typescript interface?

```
export interface match<P> {
  params: P;
  isExact: boolean;
  path: string;
  url: string;
}
```

**Comment by mjbvz** [comment]
I think you meant to import and call `matchPath` instead? `match` is indeed just a type

**Comment by believer-ufa** [comment]
Sorry, @mjbvz , but that code working in my real project. We using react-router v3, and [there](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#match-routes-location-history-options--cb) docs for that `match` function.

So, this is typing bindings error in react-router v3?

**Comment by mjbvz** [comment]
If you are using an older version of react-router, you need to manually install the older types for it:

```ts
npm install --save-dev @types/react-router@3
```

We always grab the most recent types by default
