### ISSUE TITLE
Intellisense and autocomplete not working on files created on remote server

### ISSUE THREAD

**Issue by nurp** [Microsoft/vscode#51965]
Issue Type: <b>Bug</b>
I type in an empty file:
```
import os
os.

```
It works if I create a file say in C:\
It doesn't work if a file is created in \\server. It shows all the variables that exist in that file if I press ctrl+space.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (0.25GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
matlab|Gim|0.9.0
gc-excelviewer|Gra|2.0.21
latex-workshop|Jam|5.5.1
MagicPython|mag|1.0.12
mssql|ms-|1.3.1
python|ms-|2018.5.0
cpptools|ms-|0.17.4
Go|ms-|0.6.82
vscode-hexdump|sle|1.6.0

</details>

**Comment by nurp** [comment]
It suddenly started working.

**Comment by jrieken** [comment]
@nurp what language does this happen in?

**Comment by nurp** [comment]
@jrieken Python 3.4

**Comment by jrieken** [comment]
Ok, please move this issue to the Python extension then. It's not VS Code computing auto complete, we just trigger it and the extension must be fit for files that are on a remote server
