### ISSUE TITLE
Linux: Snippets (C#)

### ISSUE THREAD

**Issue by FuriousFingers** [Microsoft/vscode#5196]
- VSCode Version: 
Version 0.10.15-insider
Commit 67567498285c2081312077cc24370d97676fc20a
Date 2016-04-11T10:51:25.123Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
- OS Version:
Ubuntu x64 15.04

Steps to Reproduce:

1. type prop
2. Press CTRL+SPACE

Nothing occurs.
I also added a prop snippet just in case it wasn't present but based on the documentation it should have all the standard ones in there.

csharp.json:

```
	"property": {
		"prefix": "prop",
		"body": [
			"private prop ${type} $2{name};",
    		"prop ${type} $2{name}(${type} value)",
    		"{",
        		"get",
        			"{",
            			"value = ${name};",
        			"}",
        		"set",
        			"{",
            			"${name} = value;",
        		"}",
    		"}"],
			"description": "Basic property"
	}
}
```

**Comment by egamma** [comment]
Works for me, see below.  Do you have the C# extension installed? Do you get syntax coloring? C# is no longer bundled by default. Also `stable` and `insiders` have separate installation folders, this means if you have it installed for stable then it isn't automatically installed for .

![image](https://cloud.githubusercontent.com/assets/172399/14491103/2f61f398-0177-11e6-9ac8-61c223d6e508.png)

**Comment by FuriousFingers** [comment]
Ok, very strange.  I am not getting any of the intellisense (IS).  I had installedc# extension and restarted the app, thought there was supposed to be IS but thought maybe not for Linux, plus it was the insiders version. First time trying went right to insiders so I think I will take a step back to stable.

Thanks!

**Comment by FuriousFingers** [comment]
So I tried stable version once I was home.  I did the same method of updating the extension c# and not getting any intellisense at all.  Based on your criteria even if I opened a ticket for the regular version it'd be immediately invalid since it definitely works for someone else.

**Comment by FuriousFingers** [comment]
Thought maybe .NET framework but doesn't look like it's out for Linux, or it's built in to the editor.  GLIB latest version, other items from FAQ all covered.  Not sure.
