### ISSUE TITLE
Terminal not response and take very high cpu

### ISSUE THREAD

**Issue by eddylin** [Microsoft/vscode#51963]
Issue Type: <b>Performance Issue</b>

1. Open a terminal(cygwin)
2. ssh to a remote machine.
3. run a mysql query with a very large output.(about 260000 chars)
4. terminal is not responding and take very high cpu.

Happen in insider build and normal build.
This seem happen after 1.24.0

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:17:41.405Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.19GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	  5108	code-insiders main
    0	    64	  9284	   shared-process
    0	    76	 15424	   window (问题报告程序)
   25	   206	 20808	   window (Untitled-1 - Visual Studio Code - Insiders)
    0	    48	  2440	     extensionHost
    0	    13	 15056	     electron-crash-reporter
    0	    33	 21328	     terminal
    0	    10	 20688	       winpty-process
    0	    11	  2000	         console-window-host (Windows internal process)
    0	     4	  8500	         C:\Windows\system32\cmd.exe /c C:\cygwin64\Cygwin.bat
    0	    10	 19792	           bash  --login -i
    0	   122	 21596	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by Tyriar** [comment]
Tracked in https://github.com/xtermjs/xterm.js/issues/1515
