### ISSUE TITLE
change colour of searched line number

### ISSUE THREAD

**Issue by rveruna** [microsoft/vscode#51979]
can you please change the colour of focused searched line in doc. i.e. when searching through style.css with ctrl+g, the line number is not white as it is when searching through doc with ctrl + f.

**Comment by roblourens** [comment]
I'm not sure what you mean by ctrl+g, because that's the same as ctrl+f by default.

**Comment by rveruna** [comment]
from: https://code.visualstudio.com/docs/getstarted/keybindings 

Ctrl+G | Go to Line...

Ctrl+F | Find


when searching with Find (Ctrl+F), line number is white and the rest of them are greyed out, which improves visibility. https://imgur.com/a/QCHG1QT

when searching with Go to Line (Ctrl+G) all of them are greyed out. https://imgur.com/a/FmkXdhQ

Is it possible to make a line white or different colour to also improve visibility when searching with Go to line

**Comment by alexandrudima** [comment]
That is because the white highlight on the line number is showing where the cursor currently is, not where the cursor would be if an action is accepted. When going to line number, the cursor is not moved until the action is accepted. If Escape is pressed, the cursor is left untouched.
