### ISSUE TITLE
"Delete all unused declarations" got error at function arguments

### ISSUE THREAD

**Issue by te3** [Microsoft/vscode#51973]
Issue Type: <b>Bug</b>

```javascript
//before delete:
const menuRender = {
  color: (item, index) => {
    return colorHash[index];
  }
};
```

```javascript
//after delete:
const menuRender = {
  color: (index) => {
    return colorHash[index];
  }
};
```

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.36GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ActiveFileInStatusBar|Ros|1.0.3
vscode-color|ans|0.4.5
githistory|don|0.4.1
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
classic-asp|ili|0.0.4
vscode-random|jre|1.3.2
color-highlight|nau|2.3.0
java|red|0.26.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0

</details>

**Comment by RMacfarlane** [comment]
If the "item" property is unused but needed for a correct type signature of the function, please prefix it with "_", ie. "_item".
