### ISSUE TITLE
Multi instance of the file should preserve the break points.

### ISSUE THREAD

**Issue by v-pavanp** [microsoft/vscode#5197]
In my dev environment I observer that there are two instances of the app.js (same path reference) opened and the only difference is in break points. 

Expected:
We should keep the break point reference across all the instances so that there will be no confusion.

![image](https://cloud.githubusercontent.com/assets/17735796/14469329/fa21e172-0098-11e6-9566-e34dbaccef29.png)

File path:
![image](https://cloud.githubusercontent.com/assets/17735796/14469432/61695f5e-0099-11e6-8583-2022c28be2dd.png)

**Comment by connor4312** [comment]
This appears to be resolved in recent vscode builds; breakpoints persist and update when the file is open in multiple panes.

![image](https://user-images.githubusercontent.com/2230985/66437641-2472e880-e9df-11e9-88dc-361abf2c5d49.png)
