### ISSUE TITLE
ユーザー設定内にGitに関する設定がない

### ISSUE THREAD

**Issue by ddryo** [Microsoft/vscode#51987]
vscodeにてgit連携させようとしたところ、gitアイコンも何も表示されていないことに気がつきました。

>  有効なソース管理プロバイダーがありません。

としか表示されておらず、ユーザー設定画面にて git と検索をかけてもgit.pathの設定すら見当たりません。

high sierra にアップデート後gitがエラーになった時の対処で

`$ xcode-select --install`

を実行したことはあるのですが、こちらもhigh sierra によるバグか何かでしょうか？

**Comment by joaomoreno** [comment]
@ddryo Does Git now work, after you run that `xcode-select --install` command?

**Comment by ddryo** [comment]
Yes, I ran `xcode-select --install`  command...

**Comment by ddryo** [comment]
<img width="627" alt="2018-06-15 20 49 54" src="https://user-images.githubusercontent.com/31400297/41466630-0a24aa48-70de-11e8-96f0-4383807652d3.png">

This is my "user setting" screen when search "git" keyword.

**Comment by ddryo** [comment]
@joaomoreno

**Comment by joaomoreno** [comment]
Can you fully reinstall VS Code? Does that fix it?

**Comment by ddryo** [comment]
@joaomoreno 
I  tried  fully reinstall VS Code.
But, the problem couldn't fix...

**Comment by ddryo** [comment]
@joaomoreno 
Sorry,  the problem fixed!
I did not fully reinstall.  I forgot delete `~/Library/Application Support/Code`.
