### ISSUE TITLE
Better understanding of class properties in Outline view

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode#51988]
How about an item in the Outline view matches the inferred type of the class property?
_-> different icon for `fun` and `prop`_
![image](https://user-images.githubusercontent.com/2313018/41457899-6061ded4-7085-11e8-9dfe-df850a123563.png)

And another suggestion could be that the icon is color coded when possible for primitives
![image](https://user-images.githubusercontent.com/2313018/41459342-a191ae94-7089-11e8-9ca9-92d1ebac1f7f.png)

**Comment by jrieken** [comment]
Looks like TypeScript... @mjbvz There is a kind for property and method and function

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/25062 to track this upstream
