### ISSUE TITLE
Regex search does not work with \n or \r

### ISSUE THREAD

**Issue by nmohamad** [Microsoft/vscode#5199]
- VSCode Version: 0.10.11
- OS Version: Win 7 , SP 1

Steps to Reproduce:
Assume you have a document with the following lines: 
// 1
// 2
// 3

1. Open search window (ctrl+f) and activate search with regex ( alt+R) 
2. type in search box : //\s1
Expected Result : One match 
3. add \n or \r to the end of search regex (now search regex will be : //\s1(\n|\r)
Bug: No Result!!

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/313
