### ISSUE TITLE
Typescript: Implement correctly async abstract methods.

### ISSUE THREAD

**Issue by Ryozuki** [Microsoft/vscode#51991]
- Version 1.24.1
- Commit 24f62626b222e9a8313213fb64b10d741a326288
- Architecture x64
- OS Version: Microsoft Windows [Version 10.0.17134.112]

Steps to Reproduce:

- Define a abstract class with an async method:

```ts
abstract class Example {
  public abstract async test(): Promise<void>;
}
```

- Create another class that extends it and then use vscode to implement the abstract methods:

![screenshot_4](https://user-images.githubusercontent.com/15859336/41459752-c779be5c-708a-11e8-87a9-3c0f498fc137.png)

- As you can see, it doesn't implement them with the async keyword:

```ts
class Test extends Example {
  public test(): Promise<void> {
    throw new Error("Method not implemented.");
  }

}
```

(It also adds a useless newline, maybe it should be detected that there is nothing more after the method and so you don't need that newline)

**Comment by mjbvz** [comment]
You shouldn't use `async` unless you are awaiting something in the implementation. It has no effect on the type signature of the method

**Comment by Ryozuki** [comment]
I see, thanks
