### ISSUE TITLE
Normalize all file paths in the workbench

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5200]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows10

I observed, when I did setup for typescript project to debug my code and provided app.js file path in the launch.json with all lowercase then I could see explorer is showing up two file version and considering them local vs disk version.
1. Path provided in launch.json : "program": "${workspaceRoot}/scripts/app.js",
2. Actual path on the disk: ....\Scripts\app.js

So the only difference between these two paths is the folder name "Script" (uppercase) and "script" (lowercase).

![image](https://cloud.githubusercontent.com/assets/17735796/14472146/9e45d2d8-00a6-11e6-8446-4035534bffa8.png)

Actual:
1. User is keep getting the error for version mismatch when performing edit and save operation.
![image](https://cloud.githubusercontent.com/assets/17735796/14472520/5ceb5d88-00a8-11e6-9f44-b6445f1cdfd9.png)

2. After resolving the mismatch issue using compare tool it is still considering two different file version and managing them separately.

![comparetoolissue](https://cloud.githubusercontent.com/assets/17735796/14472616/d10f72e4-00a8-11e6-8644-93501f312def.gif)
Expected: Path under launch.json should be case neutral and application should not make two file version.

**Comment by weinand** [comment]
@bpasero I don't think that debug is involved here. But if you think otherwise, please assign to @isidorn.

/cc @egamma

**Comment by bpasero** [comment]
The only way to solve this is to always normalize all file paths in a way as they are actually on disk.

**Comment by v-pavanp** [comment]
Today, while building my ts project I found that there are again two version of the ts files and error message is only displaying with one version. Tthat is really confusing me as both the files are identical but VSCode treat them differently. This is really annoying and confusing for end user so please fix this issue.

![image](https://cloud.githubusercontent.com/assets/17735796/14684399/9e382f4a-06e4-11e6-92ad-63fb12581d0e.png)

**Comment by bpasero** [comment]
This should be fine now because our Electron update now includes a version of `fs.realPath` that reports the casing at it is on disk.
