### ISSUE TITLE
Very Slow

### ISSUE THREAD

**Issue by Sasicumaar** [Microsoft/vscode#52013]
Latest version is very slow i cant work as normal ,JS files not loading,Intellisense not working

**Comment by Sasicumaar** [comment]
Latest version is very slow i cant work as normal ,JS files not loading,Intellisense not working

**Comment by abhirathore2006** [comment]
same here

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/51819
