### ISSUE TITLE
[folding] Odd behavior typing next to a folded section

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5201]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Collapse a section
2. Navigate to the left of the ellipsis 
3. Start typing

![foldbehavior](https://cloud.githubusercontent.com/assets/12900364/14473335/6461a7bc-00ac-11e6-8953-8f5112e94383.gif)

It would make sense if the folded section expanded if you start typing next it.

**Comment by aeschli** [comment]
This has to do with the delay on which we update the folding regions.
I know it looks funny, but no plans to change
