### ISSUE TITLE
files.ProblemExclude does not work as expected

### ISSUE THREAD

**Issue by nagylzs** [Microsoft/vscode#52011]
- VSCode Version: 1.24.1
- OS Version: Ubuntu 16.04

This problem is related to issue #22289 . The solution that was given there is to use the files.ProblemExclude user setting. It kinda works, but not 100%.

VS Code tells me that this is an unknown configuration setting:

https://imgur.com/a/qEmUC77

The most strange thing is that it actually works (e.g. problems are filtered out). But at the same time it tells that it does not work.

**Comment by RMacfarlane** [comment]
Hi @nagylzs, the setting to use for this is `files.exclude`. There is a default value for this setting that excludes some commonly ignored types of files and folders, so this is may be why you see it working.

**Comment by nagylzs** [comment]
Okay but that excludes these files from the file browser as well. I need a setting that excludes the files from the "problems" panel only, but NOT from the folder/file browser. Someone has already suggested to use a filter in the "problems" tab, but that is not a correct solution. (The number of problems would still show up.)

Why I need this: there is code that needs to be part of the project and needs to be compiled by TypeScript. (E.g. it not installed with npm but copied into the project). I still want to be able to see it in the file browser, and examine its contents. But I want to exclude it from the built-in code checker - do not want to see any problems/warnings for these files on the "problems" tab.

**Comment by sandy081** [comment]
If no diagnostics/problems have to be generated for specific files, the corresponding extension should provide that feature.

**Comment by nagylzs** [comment]
I was actually talking about typescript (.ts and .tsx) files. Is TypeScript code checker an extension in VsCode? Or is it built in? Is it possible to configure it to supress problems/warnings for specific files? How?

**Comment by sandy081** [comment]
@mjbvz Can you please answer above question?

**Comment by mjbvz** [comment]
TypeScript ships as a built-in extension. You cannot configure it to ignore specific files but you can disable it by setting: `"typescript.validate.enable": false`
