### ISSUE TITLE
Update Imports not working with npm linked modules

### ISSUE THREAD

**Issue by abhirathore2006** [Microsoft/vscode#52022]
When copying a file, it prompts for *Update Imports*   on clicking yes it is updating npm linked module to something like this 

```JS
import { fillModelValue, PhotosModel } from '../../../../../../../../mmf-ui-common/dist/lib';
```
Should be
```Js
import { fillModelValue, PhotosModel } from 'mmf-ui-common';
```
Also it applied same across all the files,which should not happen automatically 

- VSCode Version: 1.25.0
- OS Version: Ubuntu

**Comment by thomasmichaelwallace** [comment]
I'm seeing something very similar now that #51970 is fixed for me:

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:12:05.222Z)
OS version: Darwin x64 17.6.0
*Typescript: Version 3.0.0-dev.20180616* (current `@next`)

`import { expect } from 'chai'`

is becoming

`import { expect } from 'node_modules/@types/chai/index';`

after rename.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/25059 to track this upstream
