### ISSUE TITLE
Launch.json program path intellisense suggestions

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5202]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Create or open the launch.json file
2. Modify the Program path

Actual:
No intellisense suggesting a path.

Expected:
It would be great if it showed you the folder/file options after typing a forward slash '/'. I would expect it to work similarly to File Explorer.

**Comment by egamma** [comment]
@isidorn fyi

**Comment by isidorn** [comment]
nice idea, let's keep it as a feature request and we'll see if more users request it

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
