### ISSUE TITLE
Rename Unsaved Documents

### ISSUE THREAD

**Issue by brunnerh** [Microsoft/vscode#52029]
Issue Type: <b>Feature Request</b>

I tend to have a lot of unsaved files opened (right now 5 of them) for various things like JS snippets, SQL queries or notes. There is little point in saving those files as the contents change all the time, but the names `Untitled-1` to `Untitled-N` make it harder to access them and keep order.

A right-click menu option to change the name would be helpful.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 6.1.7601

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/50303
