### ISSUE TITLE
[Accessibility]A11y_VSCode_AddConfiguration_ScreenReader: NVDA is reading "{}" as blank.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52020]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Screenreader,NVDA[2018.2],MAS1.3.1

**Repro Steps:**
1.Launch VS Code while NVDA is ON.
2.Navigate to Debug(Alt+D) menu option and select "Add Configuration" from dropdown.
3.Observed that, NVDA is  reading "{}" as blank.

**Actual:**
While reading through the "NVDA", it is reading "{}" as blank.

**Expected:**
NVDA should reads "{}" as left parenthesis and right parenthesis instead of blank.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
If screenreader reads it as blank then user will not know anything about parenthesis.

**MAS Reference:**
MAS1.3.1- [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_AddConfiguration_ScreenReader.pptx](https://github.com/Microsoft/vscode/files/2105744/Accessibility.A11y_VSCode_AddConfiguration_ScreenReader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by AccessibilityTestingTeam-TCS** [comment]
While reading through the screenreader such as NVDA then instead of reading it as blank nvda should mentioned it as right-left parenthesis.Issue is also mentioned in the attached ppt.

**Comment by isidorn** [comment]
This is fixed in latest vscode insiders and latest nvda, all suggestions are read out properly
