### ISSUE TITLE
Intellisense path suggestion taking too long time to show up when using require()

### ISSUE THREAD

**Issue by sagwascript** [Microsoft/vscode#52035]
- VSCode Version: 1.24.0
- OS Version: Manjaro Linux 17.1.10

Steps to Reproduce:

1. Create new or open js file
2. Import module (npm/static) using require()
3. Type the path inside of quotation mark
4. Intellisense not showing up, so just type the path manually
5. Intellisense won't work anymore, except I reload vscode

Alternative steps that works:

1. Create new or open js file
2. Import module (npm/static) using require()
3. Type the path inside of quotation mark
4. Wait about a minute or more, Intellisense showing some directories or files
5. Intellisense work as usual
but I can't wait a minute for just importing a module 

I have tried:
1. Importing module using 'import' and when I type the path, Intellisense showing up the directories/files so fast (1-2 sec), and Intellisense works as usual after that. So I think the issue is only happened when I'm using require() and not because of my PC performance.
2. Follow some suggestion on similiar issue (like, installing types/node) but nothing change.

Does this issue occur when all extensions are disabled?: Yes
This is issue also happened in latest vscode-insiders (extension disabled: Yes)

**Comment by mjbvz** [comment]
Do you see this issue in the latest vs code insiders builds?

Also: 
- Does this repo if you start a new project?
- What does your project look like? What dependencies does it have in the `package.json`
- Can you please provide an example project or more specific repo steps

**Comment by mjbvz** [comment]
Please also try upgrading your workspace to use typescripe@next by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

Run the `Select TypeScript Version` from a js file and make sure 3.0.0 is selected

**Comment by sagwascript** [comment]
I just tried it out, and now everything works! Thank you @mjbvz
