### ISSUE TITLE
[Accessibility]A11y_VSCode_KeyboardShortcuts_ScreenReader: NVDA is reading "Search Keybindings" twice.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52030]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Screenreader,NVDA[2018.2],MAS1.3.1

**Repro Steps:**
1.Launch VS Code while NVDA is ON.
2.Navigate to Settings icon in Activity Bar->Press Enter->Select "Keyboard Shortcuts" from dropdown.
3.Navigate to "Search Keybinding" edit text field
4.Observed that screenreader is reading "Search Keybinding" twice.

**Actual:**
While reading through the screen reader as NVDA, it is reading "Search Keybinding" edit text field twice.
here, NVDA is reading "Search Keybinding" edit "Search Keybinding"

**Expected:**
NVDA should reads the button name as "Change Keybinding" button along with the placeholder value

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
User will not understand the placeholer text and exact value of placeholder becuase NVDA reads the both placeholder text as well as placeholder value.

**MAS Reference:**
MAS1.3.1- [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_KeyboardShortcuts_ScreenReader.pptx](https://github.com/Microsoft/vscode/files/2105963/Accessibility.A11y_VSCode_KeyboardShortcuts_ScreenReader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/51999
