### ISSUE TITLE
New grayed out detection for variable not being used has a bug

### ISSUE THREAD

**Issue by piltsen** [Microsoft/vscode#52032]
![image](https://user-images.githubusercontent.com/18350146/41467600-82bb6b06-707d-11e8-9606-20db7c4925c9.png)

I have declared a variable 'graphs' and after using it inside a style={} it still said I was not using it. 

Not a big issue, just thought I should report it. :) 

Thanks

**Comment by piltsen** [comment]
I looked at it now, and it is showing correctly. I have a feeling that the IntelliSense has stopped working, as I was pressing CTRL+Space and the list was not showing, so I restarted Visual Studio Code, and perhaps this solved the issue. 

On a related note, I am having a few issues with IntelliSense.

**Comment by mjbvz** [comment]
Please share that example code as test . Also test in VS Code insiders

**Comment by piltsen** [comment]
```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { withTheme } from '@material-ui/core/styles'
import { FormattedMessage } from "react-intl";
import { Link } from "react-router-dom";

import { Icon, IconButton } from "@material-ui/core";

class DetailHeader extends Component {
  render() {
    const { graphs } = this.props.theme.palette;
    const { detail } = this.props;
    return (
      <div className="row no-gutters paper-padding responsive-utilities-test visible-on" style={{ backgroundColor: graphs.lightBlue, borderRadius: '4px 4px 0px 0px' }} >
        <div className="col-2 col-lg-1 d-flex align-items-center" style={{ color: 'gray' }} >
          <Link to="/dashboard" ><IconButton>
            <Icon>home</Icon>
          </IconButton></Link>
        </div>
      </div>
    );
  }
}

DetailHeader.propTypes = {
  detail: PropTypes.object,
};

export default withTheme()(DetailHeader);
```

I noticed that the graying out (on or off) takes some time after I have deleted or added the variable. Seems like when I force IntelliSense to work, which sometimes it does take some time, it refreshes correctly.

**Comment by mjbvz** [comment]
Do you still see this in the current insiders builds?

**Comment by piltsen** [comment]
I did download the insiders build and it is working now. In fact, it feels more stable than the current stable build.
