### ISSUE TITLE
Not able to perform folding action on <HTML> tag.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5203]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open any html file. 
2. Verify formatting and perform folding by pressing "CTRL+SWIFT+["  or with mouse hover action.

Actual: Except for <HTML> tag folding is working for all other tags.
Expected: Folding should work for all the html tags.

![image](https://cloud.githubusercontent.com/assets/17735796/14476719/5df14344-00be-11e6-83a2-cfb8baa3c28b.png)

**Comment by aeschli** [comment]
Our folding is based purely on indentation. You'd have to fix the indentation to get it working.
Issue #3422 is about adding language smartness to folding. In the case of html this would mean that the indentation strategy knows about opening and closing tags.
