### ISSUE TITLE
Git auto refresh blinking icon bug

### ISSUE THREAD

**Issue by marcelhadorn** [Microsoft/vscode#52037]
Issue Type: <b>Bug</b>

What is this super disctracting git auto refresh blinking clock icon good for in the activity bar? who cares? tell me if it isn't able to refresh, not every fn second that it is able to! This is disctracting as hell.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.1.0
todo-tree|Gru|0.0.63
ACF-Snippet|ant|1.9.0
jshint|dba|0.10.19
githistory|don|0.4.1
vscode-style-formatter|dwe|1.0.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.3.5
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1
spacecadet|geo|0.0.1
sass-lint|gle|1.0.2
vscode-firefox-debug|hbe|1.4.0
react-component|jer|1.0.1
vscode-phpfmt|kok|1.0.30
vscode-scss|mrm|0.6.2
language-gettext|mro|0.0.3
vsliveshare|ms-|0.3.295
debugger-for-chrome|msj|4.6.0
vetur|oct|0.12.5
slack|soz|0.0.14
vscode-todo-highlight|way|0.5.12
JavaScriptSnippets|xab|1.6.0
ReactSnippets|xab|2.1.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Care to submit a PR which adds a setting which avoids calling `withProgress`?

https://github.com/Microsoft/vscode/blob/c51cf862a9604dffe2e3e8792a4b0a45213869a3/extensions/git/src/repository.ts#L409

**Comment by cedric05** [comment]
i will work on it

**Comment by mvgadagi** [comment]
@joaomoreno Does this mean we need have a config for this Settings ,when we set to true it should display otherwise progress shouldn't be displayed

**Comment by mvgadagi** [comment]
@joaomoreno I have created PR for the same kindly review

https://github.com/Microsoft/vscode/pull/52382

**Comment by mvgadagi** [comment]
@joaomoreno I have created the latest PR with better naming conventions and it works, Kindly review the below PR

https://github.com/Microsoft/vscode/pull/52394
