### ISSUE TITLE
Visual Studio Code not visible on a double monitor

### ISSUE THREAD

**Issue by serhioV** [Microsoft/vscode#52034]
Issue Type: <b>Bug</b>

When I first open the Visual Studio Code from the TaskBar, the program open, but as the window position is outside the visible area on the second monitor, I need to Alt+Space to display the window menu, then "Move" the window and "drag" it with the "up" keyboard button, to the visible area... 
 
Happens systematically.  

**PS**. I saw _multiple reports_ about it, all closed, impossible to comment, and the issue not fixed yet.... 

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
beautify|Hoo|1.3.2
csharp|ms-|1.15.2
notepadplusplus-keybindings|ms-|1.0.2
vsliveshare|ms-|0.3.295
team|ms-|1.136.0

</details>

**Comment by bpasero** [comment]
@serhioV can you reproduce this issue now?
