### ISSUE TITLE
Touchbar on Macbook no longer showing

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/vscode#52045]
Issue Type: <b>Bug</b>

Open latest version of code-insiders, and the touchbar doesn't show the regular commands (start debugging button).  I also had an extension I had installed previously to add extra buttons to touchbar, but even disabling or uninstalling that extension doesn't bring the touchbar back. Have tried rebooting machine as well.  It still works on code (non-insiders)

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:12:05.222Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_446573|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
gitlens|eam|8.3.5
vscode-azureeventgrid|ms-|0.1.0
vscode-azurefunctions|ms-|0.9.1
vscode-azurestorage|ms-|0.3.1
vscode-cosmosdb|ms-|0.7.2
python|ms-|2018.5.0
azure-account|ms-|0.4.0
csharp|ms-|1.15.2
Go|ms-|0.6.82
vetur|oct|0.12.5
vscode-docker|Pet|0.0.27
java|red|0.26.0
code-settings-sync|Sha|2.9.2
azure-iot-edge|vsc|0.4.0
azure-iot-toolkit|vsc|0.6.3

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Related to the electron update it seems....

**Comment by bpasero** [comment]
This is a regression from @alexandrudima chnage in https://github.com/Microsoft/vscode/commit/8810c8e74a0a3029c743dc1366e11868065b37bf where we seem to have introduced `URIs` and now start to send a `URI` over to the [`updateTouchBar`](https://github.com/Microsoft/vscode/blob/a85c0b66694fd8980b3bd7d17d74257b59055890/src/vs/platform/windows/common/windows.ts#L195) method.

**Comment by alexandrudima** [comment]
Sorry about that @bpasero 

I didn't realize `ICommandAction` was being serialized.

**Comment by bpasero** [comment]
Fixed by introducing a `ISerializableCommandAction` using `UriComponents`
