### ISSUE TITLE
Git Branch Detection for multiple open projects

### ISSUE THREAD

**Issue by infa-stopiwal** [Microsoft/vscode#52048]
Atom editor is able to identify git branches on the fly based on directory/project being edited when there are multiple projects open in the editor. With VS code one has to go to source control area in the left side toolbar and select the relevant project to know which branch is being worked on. This is not handy as it is possible that some other project is selected instead of the one that is being worked on.
Having this feature would make VS Code my favourite editor. So please do add it.... pretty please!!!

**Comment by infa-stopiwal** [comment]
This might be a duplicate of 47332

**Comment by joaomoreno** [comment]
It is!
