### ISSUE TITLE
Cannot exclude node modules from search.

### ISSUE THREAD

**Issue by mkurayan** [Microsoft/vscode#52056]
- VSCode Version: 1.24.0
- OS Version: Windows 10

I tried several configurations but it looks like It not possible to exclude node modules from search.
![image](https://user-images.githubusercontent.com/9530261/41475063-5d9f745e-70c6-11e8-8e95-b550d6f32f38.png)

**Comment by roblourens** [comment]
The gear button in 'files to exclude' is toggled off, which disables those exclude patterns, please try toggling it back on.

**Comment by mkurayan** [comment]
@roblourens thanks!
I did not notice that it is disabled, because enable & disable states looks very similar.
I enabled gear button, and now everything is works fine.
![image](https://user-images.githubusercontent.com/9530261/41650450-bc25db94-7486-11e8-9572-c106d06d6869.png)
