### ISSUE TITLE
VSTS badges don't display properly in extensions viewer.

### ISSUE THREAD

**Issue by moswald** [Microsoft/vscode#52051]
As an example:
![example](https://user-images.githubusercontent.com/85051/41473395-c99743c8-707e-11e8-8086-a7561de8b734.jpg)

[The badge renders fine when viewed on GitHub itself, though](https://github.com/Microsoft/vsts-vscode).

**Comment by ramya-rao-a** [comment]
Thanks for reporting @moswald 
Do you have any other cases where the badges are not displayed?

**Comment by moswald** [comment]
I do not, unfortunately. In an internal email exchange @joaomoreno requested I create the issue for the original bug reporter who does not have a GH account. Hopefully he'll have more context.

**Comment by ramya-rao-a** [comment]
That's ok, I know how to fix the bug for this particular badge. I was only curious if there are others falling under the same bucket.

Thanks!

**Comment by ramya-rao-a** [comment]
The fix will be out in the Monday's [Insiders](https://code.visualstudio.com/insiders) build
