### ISSUE TITLE
PHP files issue.

### ISSUE THREAD

**Issue by 1337slash** [Microsoft/vscode#52053]
Hi there,
I'm working on a project that needs the php interpreter, and I'm currently using an extension named live-server by @ritwickdey that helps me a lot. The extension launches a development local Server with live reload feature for static & dynamic pages, but on .php files doesn't work. I did a little search on Internet and it's all alright, I included the php.exe inside my vscode settings. Here:
![image](https://user-images.githubusercontent.com/38844361/41475058-fa81f32c-70bd-11e8-92b9-82962a3e1d1b.png)

I have php version `PHP 7.2.1 (cli) (built: Jan  4 2018 04:00:18) ( NTS MSVC15 (Visual C++ 2017) x64 )`
I also tried to put backslashes, like this: `C:\php\php.exe`, but it didn't work.
When I try to open the live server, I get this screen: 
![image](https://user-images.githubusercontent.com/38844361/41475071-02217238-70be-11e8-8c6a-40ee43a93fce.png)

and when I click on index.php it just downloads it. 

So how can I make vscode accept .php files?

My php extensions, and the live-server extension:
![image](https://user-images.githubusercontent.com/38844361/41475022-e7acc966-70bd-11e8-81d6-774dca71e1d2.png)

**Comment by Daylien** [comment]
For serverside languages in Live Server you need the browser extension for it. See [this](https://github.com/ritwickdey/live-server-web-extension/blob/master/docs/Setup.md) documentation. This is not an VSCode related issue. VSCode is only an editor and the extension is not a webserver that interpret any language. If you run into any issue, please open an issue on the repository of the Live Server extension you can find it [here](https://github.com/ritwickdey/vscode-live-server).

**Comment by roblourens** [comment]
Thanks @Daylien
