### ISSUE TITLE
Formal function parameters not shown in outline panel

### ISSUE THREAD

**Issue by NTARelix** [Microsoft/vscode#52052]
I enabled the new outline feature in vscode and noticed a number of symbols weren't present. After some testing I've determined all normal variable declarations and function definitions are shown, but formal parameters aren't.

It's possible this isn't a bug if the purpose of the outline is to provide navigation to symbol definitions, but I haven't found any docs on the feature detailing it one way or another. I assume the outline's main purpose is to provide a list of all available symbols, which includes formal parameters.

- VSCode Version: 1.24.1
- OS Version: macOS High Sierra 10.13.4

Steps to Reproduce:

1. Have a function with formal parameters
2. Have "Outline" feature enabled
3. Find function in outline
4. Notice formal parameters are not present

![screen shot 2018-06-15 at 09 44 57](https://user-images.githubusercontent.com/1240214/41474213-0b087d66-7081-11e8-882c-2e09edebd643.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is by-design. It would add a ton of extra symbols that usually aren't all that helpful and would obscure more commonly used symbols
