### ISSUE TITLE
Outline View Scroll Issue

### ISSUE THREAD

**Issue by pltrant** [Microsoft/vscode#52060]
- VSCode Version: 1.24
- OS Version: Windows 10

I have a SymbolProvider for my extension and everything works correctly with the new Outline view, except the window won't scroll all the way to the bottom when first opened, so I can't see all the methods.  If I maximize the VSCode window, they show up, then when I restore the window to the normal size, the scroll bar correctly scrolls to the bottom.  All the methods show up correctly in the Symbol list from the command palette.

Here are 2 screenshots to show the issue.  In the first screenshot, it looks line the last method is $DONE and the scroll bar is all the way at the bottom.

![image](https://user-images.githubusercontent.com/9040032/41476330-d93cabbc-7086-11e8-896b-ffa35086e52e.png)

I have `follow cursor` enabled, so in the second screenshot, you can barely see the highlight of the method below $DONE in the box even though it won't scroll down:

![image](https://user-images.githubusercontent.com/9040032/41476421-204d6118-7087-11e8-8053-69790bded309.png)

And here is the VSCode window maximized to show the  all the methods at the bottom:

![image](https://user-images.githubusercontent.com/9040032/41476510-6088a2e2-7087-11e8-9f1a-4fab79baa497.png)

**Comment by jrieken** [comment]
We fixed that in insiders.
