### ISSUE TITLE
Sur-consommation des ressources

### ISSUE THREAD

**Issue by RobinHerzog** [Microsoft/vscode#52061]
Issue Type: <b>Bug</b>

Bonjour,

Dès que j'ouvre l'IDE mon mac chauffe au maximum. Je n'avais pas ce problème avant.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|15, 10, 7|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.18
ftp-sync|luk|0.3.3
vscode-language-pack-fr|MS-|1.24.3
autoimport|ste|1.5.3
markdown-all-in-one|yzh|1.4.0

</details>

**Comment by RMacfarlane** [comment]
@RobinHerzog Can you take a look at our performance issue guide, https://github.com/Microsoft/vscode/wiki/Performance-Issues, and report back what you find by following the steps there?

Thanks!

**Comment by RobinHerzog** [comment]
Sounds ok thanks
