### ISSUE TITLE
The settings menu should always open upwards when near the bottom of the screen

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#52069]
Issue Type: <b>Bug</b>

When the window is at the bottom of the screen the menu opens upwards (expected). When the window is **near** the bottom of the screen the menu opens downwards (not expected), which adds unnecessary scrolling. 

![ezgif com-gif-maker 21](https://user-images.githubusercontent.com/35271042/41481287-2e26eecc-7086-11e8-9ce6-a66b729c51b7.gif)

VS Code version: Code - Insiders 1.25.0-insider (fa7ded2f007be6ae288b29392501f3dc34105abd, 2018-06-12T08:15:14.394Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.5
vscode-eslint|dba|1.4.12
gitlens|eam|8.3.5
tslint|eg2|1.0.31
beautify|Hoo|1.3.2
svgpreview|kis|0.2.0
vscode-html-format|moh|0.0.1
vscode-azureappservice|ms-|0.8.1
azure-account|ms-|0.4.0
debugger-for-chrome|msj|4.6.0
material-icon-theme|PKi|3.5.0
vscode-icons|rob|7.23.0
node-chakracore-time-travel-debugger|ttd|0.2.2

(1 theme extensions excluded)

</details>

**Comment by misolori** [comment]
@bpasero can you reference the duplicate issue? I can't find it via search.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/40262
