### ISSUE TITLE
Mouse hover on truncated string should display full string in command pallete window.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5206]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows10

Mouse hove on the truncated path in the command pallete is not displaying full path. User can't dynamically change the command pallete window size so it is hard to identify file path for manual verification.

![image](https://cloud.githubusercontent.com/assets/17735796/14478302/6510d2d8-00c9-11e6-8f28-f0ddb0f70521.png)

**Comment by f111fei** [comment]
@v-pavanp  fixes #5206
