### ISSUE TITLE
[Comments] Allow comment creation outside of a PR

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/vscode#52066]
Currently, it appears like the UI for creating new document comments only appears when you've checked out a PR using the GitHub PR extension (?). For Live Share, we'd like to register a `DocumentCommentProvider`, and allow comments to be created in the context of a Live Share session, regardless if the "host" was currently working on a PR or not. This would enable adding comments for a participant in a persistent, but non-distracting way (e.g. you're working in separate files and/or the other person is momentarily away, and you want to annotate a question/todo to discuss later ).

Ideally, the document comment creation UI (the little chat bubble that appears when you hover over a line) would appear the moment a `DocumentCommentProvider` was registered (and disappear when it was unregistered). That way, Live Share (and other `DocumentCommentProviders`) could control the "lifetime" of comments and when they were enabled.

// CC @auchenberg @jasongin

**Comment by lostintangent** [comment]
Doh! It appears like we misunderstood the behavior of the `DocumentCommentProvider`, so this request is already satisfied. Thanks!

**Comment by auchenberg** [comment]
@lostintangent My mistake, sorry for the confusion!
