### ISSUE TITLE
Revisit sensitive window split / group behavior on drag and drop

### ISSUE THREAD

**Issue by inarius** [Microsoft/vscode#52063]
Issue Type: <b>Feature Request</b>

I have noticed what seems like a recent change in the behavior for grouping/splitting windows when dragging and dropping files into the main editor. I often use this method to open files.

I am now frequently splitting the window at unintended times when I open new files. I believe the target area that triggers a split window is too large, especially when not using VSCode maximized, or on smaller screens.

VS Code version: Code - Insiders 1.25.0-insider (11b0f3a40be055e02b721abbb93cb0012818f99e, 2018-06-14T05:17:21.496Z)
OS version: Windows_NT x64 10.0.15063

![vccode-sensitive-docking](https://user-images.githubusercontent.com/4432847/41476803-7180c4f4-7077-11e8-876f-e93cea7e9cbc.gif)

**Comment by bpasero** [comment]
The current threshold is 30% of width with is a lot more compared to stable (10%). I also think we should optimize for the preferred direction of the user. E.g. when the configured to split to the right, we should maybe make the hitzone for splitting into that direction larger and vice versa.

**Comment by bpasero** [comment]
Pushed 2 changes to improve this:
* reduced the threshold where we account for a split to 20% (making the center as large as 60% to add the file into the group as opposed to causing a split
* making the hitzone for vertical or horizontal split larger depending on the `workbench.editor.openSideBySideDirection`

**`"workbench.editor.openSideBySideDirection": "right"`**
![image](https://user-images.githubusercontent.com/900690/41526789-826ddba6-72e5-11e8-8e3f-f0d829004a03.png)

**`"workbench.editor.openSideBySideDirection": "down"`**
![image](https://user-images.githubusercontent.com/900690/41526828-a4cdb9d2-72e5-11e8-8479-37094d52b8c3.png)
