### ISSUE TITLE
XUnit.ITestOutputHelper.WriteLine not showing up

### ISSUE THREAD

**Issue by fractionalJoe** [Microsoft/vscode#52079]
Issue Type: <b>Bug</b>

When running XUnit test with ITestOutputHelper to write output, the output is not available in the .Net Test Log window. 
### Code
    public class FunctionHandlerTest
    {
        #region fields
        private readonly ITestOutputHelper Output;
        #endregion

        #region ctors
        public FunctionHandlerTest(ITestOutputHelper output)
        {
            Output = output;
        }
        #endregion

        #region methods
        [Fact]
        public void OutputTest()
        {
            Output.WriteLine(JsonConvert.SerializeObject(response, Formatting.Indented));
        }
        #endregion
    }
#### (Edited slightly to replace names of customer' sensitive data with "....")

> Running test .......
> 
> Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   .....
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:01.75
> 
> 
> [xUnit.net 00:00:00.3807450]   Discovering: .....
> [xUnit.net 00:00:00.4582069]   Discovered:  .....
> [xUnit.net 00:00:00.4131600]   Starting:    .....
> [xUnit.net 00:00:00.5760216]   Finished:    .....
> .....: passed
> 
> Total tests: 1. Passed: 1. Failed: 0. Skipped: 0

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.15.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2493)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (7.71GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-test-explorer|for|0.3.1
docomment|k--|0.1.0
csharp|ms-|1.15.2

</details>

**Comment by RMacfarlane** [comment]
This issue was moved to formulahendry/vscode-dotnet-test-explorer#94

**Comment by divinebovine** [comment]
I'm running into this same bug, but I'm not seeing the output on the command line when I run dotnet test.

**Comment by RMacfarlane** [comment]
@divinebovine I moved this issue to the vscode-dotnet-test-explorer repo since it's an issue with that extension, please have a look at the issue there: https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/94
