### ISSUE TITLE
Issue following HelloWorld extension documentation

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#52076]
- VSCode Version:1.25.0-insider
- OS Version:Windows 10

Steps to Reproduce:

1. I created a new extension with yo code. 
2. I'm reading the docs here (https://code.visualstudio.com/docs/extensions/example-hello-world)
3. I hit Debug to start a new instance and got errors immediately:

```
C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe --debugBrkPluginHost=7500 --debugId=5fa85999-6eac-404a-a80d-214e8d124cf6 --extensionDevelopmentPath=C:\projects\languagetool 
Activating extension 'turdfacemcguffin.languagetool' failed: Cannot find module 'C:\projects\languagetool\out\extension'.
extensionHostProcess.js:773
Activating extension `turdfacemcguffin.languagetool` failed:  Cannot find module 'C:\projects\languagetool\out\extension'
extensionHostProcess.js:450
Here is the error stack:  Error: Cannot find module 'C:\projects\languagetool\out\extension'
```

Note that I started Code from WSL. Not sure if that makes a difference.

**Comment by cfjedimaster** [comment]
I tested with a VSC instance *not* started via WSL and it behaved the same. I get an "exited with code 1" in the first Code window.

**Comment by cfjedimaster** [comment]
I should note that looking at the structure as diagrammed (https://code.visualstudio.com/docs/extensions/example-hello-world), I have no "out" folder. So something - I think - was meant to run and generate output and the debug process did not do so correctly.

**Comment by RMacfarlane** [comment]
Whenever you hit Debug, there should be a task that runs to compile the code (`npm run watch`). (This is configured in the `launch.json` file). Can you run `npm run watch` in that folder to see if it produces any errors?

**Comment by RMacfarlane** [comment]
Or actually, can you open up the integrated terminal and confirm that you see activity there when you click on Debug?

**Comment by cfjedimaster** [comment]
So hey - I missed your replies - but this looks to be related, but not the same, as my issue here: https://github.com/Microsoft/vscode/issues/47328. Reading your replies now.

**Comment by cfjedimaster** [comment]
I ran `npm run watch` and as far as I can tell, it is ok:

```
[16:11:53] File change detected. Starting incremental compilation...

[16:11:53] Found 0 errors. Watching for file changes.
```
I also have an out folder now. So get this. Now I did a debug and I still get the error code 1 result in the first window. In the second window, I tried running the HelloWorld command and it worked.

So is something wrong in launch.json? My code came right from `yo code`.

**Comment by RMacfarlane** [comment]
That's very strange. Could you run `npm list -g generator-code` to get the version of the generator you have installed? And could you also try starting the debugger in the stable version of VSCode, 1.24.1?

**Comment by cfjedimaster** [comment]
The version is 1.1.32. I tried stable and it worked perfectly - but I'm still worried about "out" not being generated, so going to test w/ another generated extension.

**Comment by cfjedimaster** [comment]
Ok, new extension, stable Code, and it works perfectly.

**Comment by weinand** [comment]
@cfjedimaster in the generated "launch.json" there is "preLaunchTask" in both launch configurations that builds the project before starting the debug session.

**Comment by cfjedimaster** [comment]
Why did you close this? Yes there is a preLaunchTask and it seems to work in VSC, but not Insiders.

**Comment by weinand** [comment]
Sorry, but I took your comment "Ok, new extension, stable Code, and it works perfectly." as a confirmation that everything works with a newly generated extension.

I've just tried to reproduce your issue on Windows with VS Code Insiders 
(2018-06-18T08:50:30.859Z), but for me everything works fine.

**Comment by cfjedimaster** [comment]
Is there any kind of debugging I can do to possibly help flesh out why it isn't running?

**Comment by weinand** [comment]
Just disable extensions and try to reproduce the problem.

**Comment by cfjedimaster** [comment]
Disabled extensions via the CLI flag and same issue.

**Comment by weinand** [comment]
And you are still seeing this output:
```
C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe --debugBrkPluginHost=7500 --debugId=5fa85999-6eac-404a-a80d-214e8d124cf6 --extensionDevelopmentPath=C:\projects\languagetool 
Activating extension 'turdfacemcguffin.languagetool' failed: Cannot find module 'C:\projects\languagetool\out\extension'.
extensionHostProcess.js:773
Activating extension `turdfacemcguffin.languagetool` failed:  Cannot find module 'C:\projects\languagetool\out\extension'
extensionHostProcess.js:450
Here is the error stack:  Error: Cannot find module 'C:\projects\languagetool\out\extension'
```

And your extension is the unmodified Hello World extension from  code.visualstudio.com/docs/extensions/example-hello-world?

**Comment by cfjedimaster** [comment]
Yes to the first question. I tested again using `yo code`. To your second, I do not know if it is the *exact* same. I used the generator.

**Comment by weinand** [comment]
But how can the "turdfacemcguffin.languagetool" show up in the console output if you have disabled all extensions?

**Comment by cfjedimaster** [comment]
I had assumed VSC "started" with no extensions and when I hit debug, it then loaded *just* that one in the second window. Outside of this bug I'd expect that. (Ie, I want to use an 'empty' Code while working on my new extension.)

**Comment by weinand** [comment]
If you call VS Code with "--disable-extensions" this doesn't apply to the subsequent EH.
So please add a "--disable-extensions" in the launch configuration like this:

```json
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--disable-extensions"
            ],
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        },
```

**Comment by cfjedimaster** [comment]
Same result, and definitely no "out" folder generated.

**Comment by weinand** [comment]
But if you run VS Code's build task manually (Control-Shift-B), the out folder is created?

**Comment by cfjedimaster** [comment]
Nope. I get the modal about code 1 again and nothing else. (Really wish I could share more - am I just missing the additional output?)

**Comment by weinand** [comment]
I do not understand "modal about code 1" What do you mean?

**Comment by cfjedimaster** [comment]
Sorry - the same thing I mentioned in the beginning. The exited with code 1 message at the bottom right.

**Comment by weinand** [comment]
If the build is already failing (to produce the "out" folder), then this is not a debug problem.

**Comment by weinand** [comment]
Please run the "Toggle Developer Tools" from the Help menu and switch to the "Console". Is there some error output if you try to build or launch a debug session?

**Comment by weinand** [comment]
If you are still seeing the 
```
Activating extension 'turdfacemcguffin.languagetool' failed: Cannot find module 'C:\projects\languagetool\out\extension'.
extensionHostProcess.js:773
```
then the issues seems to be outside of VS Code.

**Comment by cfjedimaster** [comment]
Unfortunately the error isn't very helpful:

![image](https://user-images.githubusercontent.com/393660/41551601-f0ad15b2-72f1-11e8-9922-ce6f022537e2.png)

Btw - I apologize for the 'turdfacemcguffin' thing. I had forgotten my publisher ID when testing.
