### ISSUE TITLE
Uses Node typings when not configured in tsconfig.json

### ISSUE THREAD

**Issue by diminutivesloop** [Microsoft/vscode#52071]
Issue Type: <b>Bug</b>

When using APIs that exist in both the browser and Node.js from within TypeScript code VSCode will use the Node typings for that api even if they aren't configured in `tsconfig.json`. 

For example my `tsconfig.json` includes the following options:
```
"typeRoots": ["node_modules/@types"],
"types": ["jasmine", "jasminewd2", "hammerjs"],
"lib": ["es2015", "dom"]
```
And I have the following code:
```
let a: number = setTimeout(()=>{}, 100);
```
In VSCode I get the error "Type 'Timer' is not assignable to type 'number'" in VSCode although the code compiles without error. Note that I do have a transitive dependency on `@types/node` but since I don't include it in my `tsconfig.json` VSCode should not be using it.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930MX CPU @ 3.00GHz (8 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (16.26GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|yes|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|0.25.2
ng-template|Ang|0.1.9
vscode-eslint|dba|1.4.12
find-related|eam|0.7.0
gitlens|eam|8.3.5
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.32
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
todo-tree|Gru|0.0.63
java-properties|ith|0.0.2
vscode-duplicate|mrm|1.2.1
vsliveshare|ms-|0.3.295
debugger-for-chrome|msj|4.6.0
tsimporter|pmn|1.2.14
java|red|0.26.0
sass-indented|rob|1.4.9
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
vim|vsc|0.12.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25061
