### ISSUE TITLE
Update Explorer with context of Terminal

### ISSUE THREAD

**Issue by isaac2004** [Microsoft/vscode#52074]
I often open up VS Code and start using terminal right away to do work. Some times, I will use a CLI of choice to start building an application or init a GitHub repo, like so

````
git init
dotnet new sln -n SampleApp
dotnet new webapi -n SampleApp.Api -o SampleApp.Api
dotnet sln .\SampleApp.Api.sln add .\SampleApp.Api\SampleApp.Api.csproj
````

At this point in time, I have an app created, but in order to start developing that app, I have to File > Open Folder and go to the folder that I just created. I can also `code .` but that opens up a new VS Code instance. 

It would be great if there was a way for me to send the current location of my terminal instance to explorer. Perhaps a command in terminal proper,  or a button in the terminal window.

**Comment by isaac2004** [comment]
cc @burkeholland @johnpapa

**Comment by johnpapa** [comment]
one thing we can do today is `code . -r`. This will open code up in the existing instance of code.

will that cover it?

**Comment by isaac2004** [comment]
ehhhh close, the user experience is not great (Code basically resets itself and I have to reopen terminal). This can work though, but I think there is value in a feature like this if it isn't too difficult. Low Priority obviously

**Comment by Tyriar** [comment]
> Code basically resets itself and I have to reopen terminal

This may go away some time but it's an artifact of VS Code's early design which makes it hard to switch folders.

`code -r .` is the answer as @johnpapa suggests. If you're in a multi-root workspace you could also use `code -a .` which will *add* the folder to the workspace and not require a reload if you already have a multi-root workspace opened.
