### ISSUE TITLE
js文件高亮有問題

### ISSUE THREAD

**Issue by jingsansheng** [Microsoft/vscode#52085]
Issue Type: <b>Bug</b>

1，创建index.js
2，输入以下内容:
import Vue from 'vue';
import Vue from 'vue';
3，只有第二行高亮了

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (27.76GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by LujunWeng** [comment]
Just help to translate
1. create a file `index.js`
2. Enter the following:
```
import Vue from 'vue';
import Vue from 'vue';
```
3. Only the second line is highlighted.

**Comment by mjbvz** [comment]
This is the greying / fading out unused variables  and imports. If you import duplicate symbols, only the last occurrence will be used in the file
