### ISSUE TITLE
Extensions viewlet proportions are not persisted across extensions editor loads

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#52081]
Issue Type: <b>Bug</b>

Only occurs on most recent insiders. 

Open extensions viewlet, change size of recommended pane. Open an extension editor. Recommended pane will snap back to previous size. 

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:17:41.405Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
gitlens|eam|8.3.5
tslint|eg2|1.0.32
regex-railroad-diagrams|kog|0.2.4
debugger-for-chrome|msj|4.6.0
material-icon-theme|PKi|3.5.0
subtle-brackets|raf|2.1.1
code-spell-checker|str|1.6.10

</details>

**Comment by sandy081** [comment]
Fixed by @joaomoreno in split view.
