### ISSUE TITLE
completion error in Json files

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/vscode#52084]
Issue Type: <b>Bug</b>

In a json file add a new property to an object by typing "args":[
notice the closing bracket is added "]". Great.  Now hit ENTER.  You will now find the closing bracket has been doubled resulting in syntax error "]]".

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3510)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (20.94GB free)|
|Process Argv|d:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.1
python|ms-|2018.5.0
cpptools|ms-|0.17.4
vscode-arduino|vsc|0.2.17

</details>

**Comment by rebornix** [comment]
@lovettchris did you see the auto complete window (a dropdown list) after you type `[`?
