### ISSUE TITLE
Installer freezes during update when there's a readonly file in the installation folder

### ISSUE THREAD

**Issue by Yuudaari** [Microsoft/vscode#52083]
- VSCode Version: 1.23 - 1.24 - 1.24.1 (32 bit; have not tested with 64 bit)
- OS Version: Windows 10 17134.112

Steps to Reproduce:

1. Install a version of VSCode between 1.23 and 1.24
2. Put a readonly file in the installation folder (reasons why below)
3. Update VSCode through the in-application "install update" gear icon
4. When VSCode restarts and the small application with the progress bar appears, it will freeze upon encountering the readonly file. If it's a readonly folder, it will hang forever. If it's a file, it will eventually crash and say VSCode will need to be reinstalled.

If you reinstall VSCode, the base installer just notes that there's a readonly file and asks if you want to continue. This is good, it would be nice for it to work with the in-app installer, though.

Does this issue occur when all extensions are disabled?: Yes, unrelated

**Q: Why do I have readonly files in the folder?**
Non-readonly files are removed on update.

**Q: Why do I have non-VSCode files in the folder?**
I replace the `VisualElementsManifest.xml` files for all of the apps I use regularly, [so I can have a pretty start menu](https://puu.sh/AG3XP/10dcf0ee60.png).

**Comment by joaomoreno** [comment]
@Yuudaari Interesting. We won't fix this issue, but if you want to contribute a PR which would make us ship `VisualElementsManifest.xml` with the Windows release, please be my guest.
