### ISSUE TITLE
Go back/forward should not consider points every 5 lines when navigating with keyboard

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#5208]
Steps to Reproduce:
1. Put the cursor somewhere in the middle of the file
2. Hold down arrow key for a while
3. Perform the Goto > Back action several times

It should be smarted what points in the page are recorded. It would be more useful if only events of significance should add new points:
- Starting to type in a new area
- Finding a definition
- Clicking
- etc.

**Comment by bpasero** [comment]
@alexandrudima and me talked about this and I think we came to the conclusion that the editor navigation history is something that should be provided by the editor itself and not by listening to events from the outside.

**Comment by beatthem** [comment]
Hello!
I like behaviour of go to definition and navigate back that in Intellij Idea now - it navigates back only to points before Go To Definition was done.
I don't want to create new issue because this one is almost the same I mean.
Thank you for your work for VS Code.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/29027
