### ISSUE TITLE
Allow to configure number of entries in "File > Open Recent" list

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#52086]
Issue Type: <b>Feature Request</b>

Please consider to add the option to control how many folders and files to remember which had been opened before.

There has been “workbench.commandPalette.history” to control command history, but no option for files history.

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:17:41.405Z)
OS version: Windows_NT x64 10.0.17686

**Comment by bpasero** [comment]
@byyxx128 you mean this history:

![image](https://user-images.githubusercontent.com/900690/41497483-864f45f6-7156-11e8-8d36-cb6a6895ca2a.png)

?

**Comment by byyxx128** [comment]
The history is what you can see in follow menu——
File——Open Recent Files

There‘s no option to control the number.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8682
