### ISSUE TITLE
Extreme CPU (at 744%)

### ISSUE THREAD

**Issue by ksnyde** [Microsoft/vscode#52088]
![image](https://user-images.githubusercontent.com/980757/41495685-b50922ba-70e1-11e8-8e48-5e3987b1eefa.png)

Extreme CPU spike, I ran `code --status` and got the following:

    Version:          Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
    OS Version:       Darwin x64 17.6.0
    CPUs:             Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)
    Memory (System):  16.00GB (0.04GB free)
    Load (avg):       36, 32, 18
    VM:               0%
    Screen Reader:    no
    Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_69649
    GPU Status:       2d_canvas:                    enabled
                      flash_3d:                     enabled
                      flash_stage3d:                enabled
                      flash_stage3d_baseline:       enabled
                      gpu_compositing:              enabled
                      multiple_raster_threads:      enabled_on
                      native_gpu_memory_buffers:    enabled
                      rasterization:                enabled
                      video_decode:                 enabled
                      video_encode:                 enabled
                      vpx_decode:                   enabled
                      webgl:                        enabled
                      webgl2:                       enabled

    CPU %   Mem MB     PID  Process
        4       98     406  code main
        1      131     553     gpu-process
        7      311     575     window (dispatch-spec.ts — firemodel)
        3      213     667       extensionHost
        0       33     794         electron_node electronForkStart.js tsserver.js
        0       16     822           electron_node typingsInstaller.js tsserver.js typesMap.js
        0       16     795         electron_node tslintServer.js
        0       16     841         electron_node jsonServerMain.js
        0       16    1551         electron_node eslintServer.js
      52      770    1817         extensionHost
      50      770    2051         extensionHost
      51      737    3724         extensionHost
      53     1130    3725         extensionHost
      55      639    3726         extensionHost
      51      655    3727         extensionHost
        0       16    3728         extensionHost
        2       82    3763         node --harmony /Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/wallaby/server.js extended-core-ws --projectCachePath=/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/projects/f3d1eac03bf8a243 --configPath=/Users/ken/mine/forest-fire/firemodel/wallaby.js --lkp=/Users/ken/.vscode/extensions/.wlck --client=VSCode --phantomjs=/Users/ken/.vscode/phantomjs_v2.1.1/phantomjs --port=53255
      49       82    3768           node /Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/wallaby/server.js runner 4 53258 mocha@2.1.0  /Users/ken/mine/forest-fire/firemodel/node_modules
        0       16    3780           node /Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/wallaby/server.js runner 0 53258 mocha@2.1.0  /Users/ken/mine/forest-fire/firemodel/node_modules
        0       16    3970           node /Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/wallaby/server.js runner 1 53258 mocha@2.1.0  /Users/ken/mine/forest-fire/firemodel/node_modules
      50       66    4131           node /Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/wallaby/server.js runner 2 53258 mocha@2.1.0  /Users/ken/mine/forest-fire/firemodel/node_modules
        0       16     668       watcherService
        0       16     669       terminal
        0        0     670         /bin/zsh -l
        0        0    4251           bash /usr/local/bin/code --status
        1       33    4261             electron_node cli.js
        0       16     809       searchService
        0       49     577     shared-process

    Workspace Stats:
    |  Window (dispatch-spec.ts — firemodel)
    |    Folder (firemodel): 257 files
    |      File types: js(59) ts(54) html(33) md(28) map(20) jpg(16) png(14)
    |                  json(12) DS_Store(4) css(3)
    |      Conf files: tsconfig.json(2) package.json(1) tslint.json(1)
    |                  launch.json(1) settings.json(1) tasks.json(1)
    Unable to parse /Users/ken/mine/forest-fire/firemodel/.vscode/launch.json

**Comment by ksnyde** [comment]
I noticed that it's having issue with my `launch.json` file. On quick inspection it appears fine to me (at least it's structurally parsable):

{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [

    {
      "name": "All Mocha Tests",
      "type": "node",
      "request": "launch",
      "stopOnEntry": false,
      "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
      "protocol": "inspector",
      "cwd": "${workspaceRoot}",
      "args": [
        "--no-timeouts",
        "--compilers",
        "ts:ts-node/register",
        "${workspaceRoot}/test/**/*-spec.ts"
      ],
      "internalConsoleOptions": "openOnSessionStart"
    },
    {
        "name": "Current TS Test File",
        "type": "node",
        "request": "launch",
        "protocol": "inspector",
        "program": "${workspaceRoot}/node_modules/.bin/_mocha",
        "args": [
          "--no-timeouts",
          "--compilers",
          "ts:ts-node/register",
          "${relativeFile}"
        ],

        "cwd": "${workspaceRoot}"
    },
    {
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "name": "Launch Program",
      "program": "${workspaceRoot}/lib/index.js",
      "outFiles": []
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Port",
      "address": "localhost",
      "port": 5858,
      "outFiles": []
    }
  ]
}

**Comment by ksnyde** [comment]
I finally forced the last helper process to shutdown and then restarted the same project. I then ran `code --status` again:

    Version:          Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
    OS Version:       Darwin x64 17.6.0
    CPUs:             Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)
    Memory (System):  16.00GB (3.22GB free)
    Load (avg):       4, 11, 16
    VM:               0%
    Screen Reader:    no
    Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron
    GPU Status:       2d_canvas:                    enabled
                      flash_3d:                     enabled
                      flash_stage3d:                enabled
                      flash_stage3d_baseline:       enabled
                      gpu_compositing:              enabled
                      multiple_raster_threads:      enabled_on
                      native_gpu_memory_buffers:    enabled
                      rasterization:                enabled
                      video_decode:                 enabled
                      video_encode:                 enabled
                      vpx_decode:                   enabled
                      webgl:                        enabled
                      webgl2:                       enabled

    CPU %   Mem MB     PID  Process
        4      115    4530  code main
        7      164    4531     gpu-process
      12      410    4532     window (dispatch-spec.ts — firemodel)
        3      180    4599       extensionHost
      116      131    4683         electron_node electronForkStart.js tsserver.js
        0       49    4703           electron_node typingsInstaller.js tsserver.js typesMap.js
      58       66    4707             npm
        8       82    4684         electron_node tslintServer.js
      105      115    4685         extensionHost
        0       49    4600       watcherService
        0       33    4601       terminal
        0        0    4602         /bin/zsh -l
        0        0    4728           bash /usr/local/bin/code --status
      13       33    4738             electron_node cli.js
        0       49    4690       searchService
        0       98    4533     shared-process

    Workspace Stats:
    |  Window (dispatch-spec.ts — firemodel)
    |    Folder (firemodel): 257 files
    |      File types: js(59) ts(54) html(33) md(28) map(20) jpg(16) png(14)
    |                  json(12) DS_Store(4) css(3)
    |      Conf files: tsconfig.json(2) package.json(1) tslint.json(1)
    |                  launch.json(1) settings.json(1) tasks.json(1)
    Unable to parse /Users/ken/mine/forest-fire/firemodel/.vscode/launch.json

same problem loading `launch.json` but CPU is at normal levels.

**Comment by mjbvz** [comment]
Does this issue happen if you disable all extensions? It looks like one or more of the extension host processes are going crazy in all the examples
