### ISSUE TITLE
Cursor jumping around on typing

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#52080]
On 678f87ed45c0f18a76ad19fa9de555e77dea78a8

Steps to Reproduce:

1. Enable outline
2. Open a json file: 

```json
{
    "a": {
        "b": 1,
        "a": 
    }
}
```
3. Type a value for `a.a` in the json file

**Bug**

![jun-15-2018 15-25-22](https://user-images.githubusercontent.com/12821956/41491852-630417b2-70b0-11e8-8c09-cbf9e02b5d72.gif)

Only seems to repo when outlined is enabled

**Comment by mjbvz** [comment]
Seems caused by the calls to `_revealTreeSelection`. Doesn't repo 100% of the time. May require switching back and forth between some files first

**Comment by krokofant** [comment]
This is horrible 😅 Was thinking i was being pranked.

Thanks for the workaround.

**Comment by juristr** [comment]
🙈 happens to me as well, also inside TypeScript files. VSCode Insiders basically not usable right now 😞

**Comment by changavila** [comment]
When will this be updated to Vscode Insider Release, VSCode it totally unusable right now.

**Comment by jrieken** [comment]
Yeah, I can push another release for today

**Comment by whimzee** [comment]
ETA on release?

**Comment by juristr** [comment]
@changavila @jrieken @whimzee Meanwhile you can disable the "outline". that'll fix it for now.

**Comment by WoodyWoodsta** [comment]
@juristr How do you go about disabling it?

**Comment by changavila** [comment]
![image](https://user-images.githubusercontent.com/13307287/41527176-e2859f82-7318-11e8-8367-d6ea9cf414fe.png)
Which one?? 

**Outline** does not exist in settings.

**Comment by whimzee** [comment]
Keep in mind you can also use the stable version of vscode until this is fixed. Stable is working fine.

**Comment by juristr** [comment]
@WoodyWoodsta just in the vscode file explorer, right-click on the title area and uncheck "outline"

**Comment by alasdairhurst** [comment]
I'm using 1.25.1 (stable) and running into the same issue. It's only started recently though.
Using Windows 10
![image](https://user-images.githubusercontent.com/8441810/43316518-7ec1e70c-9191-11e8-897c-6b2255e450c3.png)

I don't remember enabling any "outline" setting though.
