### ISSUE TITLE
AZURE APP SERVICE explorer - Not available after installing Azure App Service extension 

### ISSUE THREAD

**Issue by jackharich** [Microsoft/vscode#52097]
Yes, did that for over 45 minutes.

- VSCode Version:
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Win10 64bit.

Steps to Reproduce:

1. Install Azure App Service extension on current version of VCStudio
2. Look for "AZURE APP SERVICE explorer". After one hour of searching VCStudio and the internet, unable to find it.

Does this issue occur when all extensions are disabled?: Yes/No
Come now, this is an extension!!~!!!@

See: https://code.visualstudio.com/tutorials/app-service-extension/getting-started#_sign-in
Note how this page of documentation does NOT say how to show the "AZURE APP SERVICE explorer". It just implies it will magically appear or can be easily found. In my case, neither it true.

All the doc says is "Once the extension is installed, log into your Azure account - in the AZURE APP SERVICE explorer, click Sign in to Azure... and follow the instructions."

I have created a new Azure account. 
This is NOT in the documentation. I laboriously found that with SHIFT CONTROL P you can use Azure: to get commands. One is Configure Deployment Source. I chose that and signed in. But still, there is no "AZURE APP SERVICE explorer". Without that I'm unable to use Azure.

**Comment by jackharich** [comment]
Further experimentation revealed that one must show the workbench activity bar. To gain more precious screen space I was hiding it with workbench.activityBar.visible false. It's a waste of space since hot keys can show the desired panel, EXCEPT for extensions which unfortunately break this model.

May I politely point out the documentation is buggy. It never considers the user may have done what I did. This:

"Once the extension is installed, log into your Azure account - in the AZURE APP SERVICE explorer, click Sign in to Azure... and follow the instructions."

should be changed to something like:

"Once the extension is installed, a new icon will appear on your workbench activity bar near the bottom. Click on that to open the AZURE APP SERVICE explorer. Then click Sign in to Azure... and follow the instructions."

**Comment by RMacfarlane** [comment]
@jackharich Sorry this was so frustrating, the documentation should be updated. This repository is for the core of VSCode, so this issue should be on the extension itself. I'll move it over.

**Comment by RMacfarlane** [comment]
This issue was moved to Microsoft/vscode-azureappservice#472
