### ISSUE TITLE
xtermjs or integrated terminal blacking out while typing

### ISSUE THREAD

**Issue by reap-r** [Microsoft/vscode#52092]
- VSCode Version: 1.24.0
- OS Version: Arch Linux - 4.16.13-2-ARCH

Steps to Reproduce:

1. Open VSCode from terminal using `code .`
2. click on the integrated terminal and start typing something

Does this issue occur when all extensions are disabled?: Yes
![screenshot from 2018-06-16 13-40-43](https://user-images.githubusercontent.com/10115336/41496141-ff504f04-716a-11e8-9452-07aeab732ccd.png)

**Comment by Tyriar** [comment]
I think this is fixed now
