### ISSUE TITLE
Workspace folder problem

### ISSUE THREAD

**Issue by shubhpaliwal** [Microsoft/vscode#52094]
- VSCode Version: 1.24
- OS Version: windows 10

Steps to Reproduce:

1. when i try to add multiple project folders in work-space the an exclamation mark appears on the righ side of folders 
2. That states that cannot resolve work-space folder but all contents of folder is shown and are editable

Does this issue occur when all extensions are disabled?: Yes
![problem](https://user-images.githubusercontent.com/29926320/41496573-4049e574-715c-11e8-9307-6e0e1d9937cd.png)

**Comment by mvgadagi** [comment]
@shubhpaliwal , Can you confirm this issue exists for you Because I am not able to reproduce this one with below config

Version: 1.25.0
Commit: Unknown
Date: Unknown
Electron: 2.0.2
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by isidorn** [comment]
DUp of https://github.com/Microsoft/vscode/issues/50866#issuecomment-397800540
