### ISSUE TITLE
Change the Location of Extensions and Other Data

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#52090]
Issue Type: <b>Feature Request</b>

Please consider to move extensions storage data to other path, like %appdata% or %localappdata%, etc.

Because the folder %userprofile% is transparent for general users. And it makes the user folder very rambling.

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:17:41.405Z)
OS version: Windows_NT x64 10.0.17686

**Comment by RMacfarlane** [comment]
Related: https://github.com/Microsoft/vscode/issues/17691

**Comment by byyxx128** [comment]
Well, what I want is not just to add a option for extensions location.
User’s data should not be saved in %USERPROFILE%.
The following issue told us the reason and solution.
https://github.com/OmniSharp/omnisharp-roslyn/issues/953
Please consider.
