### ISSUE TITLE
Running .Net application on visual studio code in MacBook pro

### ISSUE THREAD

**Issue by AnveshGannamraju** [Microsoft/vscode#52091]
I am doing C# programming in Visual Studio Code in MacBook Pro, so whenever I run the application, a dotnet process is left in the memory, when I open the Activity Monitor the memory is not disposed, and the CPU is running at 100% even after the debugging is stopped. Is something wrong with my code or is there anything else that I should be doing while writing c# code in Mac OS. Please let me know, right now after every run I am opening activity monitor and force quitting the process.

**Comment by weinand** [comment]
Please file this issue against the C# extension.
