### ISSUE TITLE
Grid: drop feedback can stay sticky in some cases

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52093]
![before](https://user-images.githubusercontent.com/900690/41496544-772bc6a8-7142-11e8-81a6-790ede3812ff.gif)

**Comment by mvgadagi** [comment]
@bpasero I am not able to reproduce this issue with 

Version: 1.25.0
Commit: Unknown
Date: Unknown
Electron: 2.0.2
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

![vscode](https://user-images.githubusercontent.com/3121238/41502111-6ae0dd5a-71d0-11e8-8af5-5b4982b2acc6.gif)

**Comment by bpasero** [comment]
@mvgadagi only reproduces when you have an editor split downside of the active one, not to the right.

**Comment by bpasero** [comment]
Might be macOS specific.
