### ISSUE TITLE
Key bindings not working properly

### ISSUE THREAD

**Issue by Zephilim** [Microsoft/vscode#52102]
Issue Type: <b>Bug</b>

This issue was found when trying to define key bindings for scrolltotop and scrolltobottom.

The scrolltotop/scrolltobotton functions do actually work (but not as expected). If I use cmd+uparrow or cmd+downarrow, then I get the funcionality I require. However, there are no key bindings for these key combinations defined for scrolltotop/scrolltobottom, so I don't know why they work.

I only discovered cmd+up/down by accident. I tried to defined cmd+home (scrolltotop) and cmd+end (scrolltobotton) via the key bindings page and even though the key bindings were actually set (you could see the bindings as being defined), they did not work at all. I also tried to use the alt key instead of cmd, but the result was the same.

I also tried to launch VSC without any extenbsions being installed (as instructed to do so) and the issue was still prevalent. This issue may not be just the scrolltotop/scrolltobottom, there may be a systemic issue here. It doesn't make sense for cmd+uparrow/downarrow to work, because they are not defined in the key bindings so something is not right here.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
EditorConfig|Edi|0.12.4
vscode-docker|Pet|0.0.27
code-settings-sync|Sha|2.9.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.3.5
tslint|eg2|1.0.32
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
beautify|Hoo|1.3.2
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|6.1.1
autoconf|mae|0.0.7
Angular-BeastCode|Mik|6.0.16
vscode-cosmosdb|ms-|0.7.2
atom-keybindings|ms-|3.0.4
azure-account|ms-|0.4.0
cpptools|ms-|0.17.4
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.6.0
chai-snippets|nwh|0.1.0
tsimporter|pmn|1.2.14
vscode-icons|rob|7.23.0
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
bootstrap4-vscode|the|4.1.1

(1 theme extensions excluded)

</details>

**Comment by mvgadagi** [comment]
@Zephilim Can you confirm still this exists for you, Because that symbols stays for fraction of second and disappears

**Comment by RMacfarlane** [comment]
@Zephilim Are you trying to scroll text in the integrated terminal, or in the text editor? The commands you mention are `workbench.action.terminal.scrollToTop` and `workbench.action.terminal.scrollToBottom`, but cmd+up/down are the default bindings for `cursorTop` and `cursorBottom`, which scroll text in the editor

**Comment by Zephilim** [comment]
Hi, I was trying to scroll in the editor window, not the integrated terminal. I only used "workbench.action.terminal.scrollToTop" because I noticed the "scrollToTop" which seemed to be what I wanted not realising what "workbench.action.terminal" actually was. Is there an explanation of the "scoping" that is applied to command names, eg in this case "workbench.action.terminal". I am looking at my keybindings.json and in the comments at the end of the file, there is a large list of available commands, but for I don't know what "workbench.action.editor", "workbench.action.debug", "workbench.view.extension" etc... and yes I can have a guess what they mean, but I would rather just read documentation than guess. Thanks.

**Comment by chrmarti** [comment]
https://github.com/Microsoft/vscode-docs/issues/683 is tracking the request for documentation. I suggest using the tabular shortcut editor that shows command labels:
![image](https://user-images.githubusercontent.com/9205389/41600779-1515c7a6-73d7-11e8-9c68-9930ffb2ee45.png)

**Comment by Zephilim** [comment]
Thanks chrmarti
