### ISSUE TITLE
VSCode when offline still searches for dependencies and thus breaks

### ISSUE THREAD

**Issue by AshSimmonds** [Microsoft/vscode#52106]
I went from happily coding away in my cubicle to then an hour later with the exact same stuff but somewhere without internet and the whole thing broke down because it wanted to check a dependency online.

Not great for client demonstrations or coding in "zen mode" if you need to be online all the time.

**Comment by RMacfarlane** [comment]
@AshSimmonds Thanks for reporting this, could you describe in a little more detail what dependency was checked, perhaps by looking at the dev console?

**Comment by AshSimmonds** [comment]
I managed to track it down to the Google Auth thing.

To reproduce add "google_sign_in" to the yaml file and then ditch your internet and try to build.

**Comment by chrmarti** [comment]
That must be an extension, we don't have any Google Auth in what we ship built-in. Could you track that down and file an issue for the extension? Thanks.

**Comment by TomasHubelbauer** [comment]
@AshSimmonds I am curious however, what exactly do you mean by "broke down", because an extension should not be able to crash VS Code or affect your experience drastically like that. Do you mean to say the extension closed Zen mode on you?

**Comment by AshSimmonds** [comment]
It won't build the APK because before it even tries the build it does a dependency check online - which of course fails.

Huh, thought I posted a screenshot originally, sorry. I'll do it again... Right, just re-enabled it in the pubspec.yaml file, switched off interwebs, and problem returns:

![20180619181244_screenshot](https://user-images.githubusercontent.com/9034041/41591661-ed5c5c28-73ec-11e8-81a9-afedd2a3c043.png)

Dunno if it's a VSCode problem or the extension specifically, but I'll cross-post and let the devs figure it out.

Text in case anyone else is searching:

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
> Could not determine artifacts for com.google.firebase:firebase-core:12.0.1
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/12.0.1/firebase-core-12.0.1.aar'.
      > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/12.0.1/firebase-core-12.0.1.aar'.
         > dl.google.com
```

**Comment by AshSimmonds** [comment]
https://github.com/flutter/flutter/issues/18594
