### ISSUE TITLE
Error notification if we declare same class name two times

### ISSUE THREAD

**Issue by Sampath-Lokuge** [Microsoft/vscode#52109]
This is the feature which I need:

Inside the `.scss` where we need error notification if we declare same class name two times. Now there is no such notification. In other words, we can put same class name any number of times right now. Which is very bad. We need some sort of notification here.

`.scss`

```
.min-height-117 {
    min-height: 117px;
}

.min-height-117 {
    min-height: 117px;
}

```

**Comment by octref** [comment]
You can use stylelint with https://stylelint.io/user-guide/rules/no-duplicate-selectors.
