### ISSUE TITLE
⇧⌘E is focusing `working files` and not `explorer`

### ISSUE THREAD

**Issue by sarbbottam** [Microsoft/vscode#5210]
- VSCode Version: 0.10.11
- OS Version: 10.11.4

Steps to Reproduce:

1. Open a file from `working files` (⌘K + E; ↓↑; Enter) or by clicking
2. Now press ⇧⌘E, it should focus the `explorer`, but focuses the `working files`

Note: If the last opened file is from `explorer` or by typing the filename (⌘P), successive ⇧⌘E focuses `explorer`

**Comment by bpasero** [comment]
The command to focus the explorer now focus on the last focused thing (either explorer or working files). There are new commands to focus either working files or explorer.

You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by sarbbottam** [comment]
>There are new commands to focus either working files or explorer.

Could you share the new commands or point to the new key bindings?

https://code.visualstudio.com/Docs/customization/keybindings still suggests
<img width="754" alt="screen shot 2016-04-13 at 10 33 11 am" src="https://cloud.githubusercontent.com/assets/949380/14503052/2bdd0172-0163-11e6-8a96-2bfa1e780f0d.png">

**Comment by bpasero** [comment]
workbench.files.action.focusWorkingFiles is the new command.
