### ISSUE TITLE
VS Code does not recognize javascript anymore after update

### ISSUE THREAD

**Issue by mshi** [Microsoft/vscode#5211]
- VSCode Version: 0.10.11 (0.10.11) f291f4ad600767626b24a4b15816b04bee9a3049
- OS Version: OSX 10.11.4

Ever since VS Code updated and restarted, no files or projects have intellisense nor does it have peek definition, go to definition, etc. It cannot find references to symbols either.

I've tried the insider release and the 10.10 as well. This just started happening within the last week and I have been using Code since release in 2015.

Steps to Reproduce:

1. Open any project (including new express app in the node example page)
2. Nothing works and VS Code does not resolve any references.

I've added jsconfig.json as well and restarted, but it did not make any difference.

**Comment by timbarclay** [comment]
Same here with:

* VSCode version 1.0.0
* Windows 10

It was working before updating yesterday. I have a `jsconfig.json` and some `d.ts` files but I'm not getting any intellisense or go to definition etc.

After I updated, I got a lightbulb saying that I should add a `jsconfic.json` even though I already had one.

**Comment by timbarclay** [comment]
I seem to have got it working again by closing VSCode and then re-opening it using the Open with Code context menu item. Just closing and re-opening didn't help, but opening it this way did. 

Fingers crossed it'll be that simple for @mshi.

**Comment by egamma** [comment]
@dbaeumer any idea what could have gone wrong here?

**Comment by dbaeumer** [comment]
@mshi how is your OSX file system configured in terms of case sensitiveness. We have reports that JS features disappear on a case sensitive OSX file system.

**Comment by dbaeumer** [comment]
@mshi would you be able to share your workspace ?

**Comment by mshi** [comment]
@dbaeumer Hi, yes my OSX file system is case sensitive. This only started happening recently, as mentioned in original post.
And no, sorry I am unable to share my workspace. But like i mentioned, downloading a fresh copy and starting a fresh template express project results in the same behaviors.

**Comment by dbaeumer** [comment]
@mshi you are affected by this: https://github.com/Microsoft/TypeScript/issues/8139

Closing as dup.
