### ISSUE TITLE
The tab reloads when clicking an action button

### ISSUE THREAD

**Issue by ZaLiTHkA** [Microsoft/vscode#52112]
Issue Type: <b>Bug</b>

This is just something I've noticed when browsing and installing different extensions..

Basicaly, when you click any of the "Install" or "Uninstall" buttons, that "click" event causes the extension view to reload. This affects the buttons in both the smaller sidebar view on the left, and in a tab of it's own.

>Probably wouldn't bother most people, but we don't' all have lightnig fast connections, so I notice it with the `README`.md` files that are full of pretty pictures... (:

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960X CPU @ 3.60GHz (12 x 3611)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (26.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.32
vsc-material-theme|Equ|2.1.0
sublime-keybindings|ms-|4.0.0
java|red|0.26.0
code-settings-sync|Sha|2.9.2
vscode-todo-highlight|way|0.5.12

</details>

**Comment by ramya-rao-a** [comment]
I can see in this in the stable build, but not in Insiders.
Can you try this on the latest [Insiders](https://code.visualstudio.com/insiders)?
