### ISSUE TITLE
Switching git branches disables mouse clicks

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#52110]
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture Ubuntu 16.04 x64

Steps to Reproduce:
1. Launch vscode with an existing workspace auto-loaded - the workspace must be in git with multiple branches and some files in the current branch must be modified.
2. Click the branch name in the status bar and choose a different branch from the menu
3. Message is displayed: "Please clean your repository working tree before checkout.".

At this point mouse clicks are completely disabled across the entire screen. Nothing in vscode (including the message box), nor any other applications or OS taskbar/statusbar respond to mouse clicks. The mouse cursor can still be moved, but nothing responds to left, middle or right clicks.

The only way to get the mouse back is to use the keyboard to dismiss the message box or kill vscode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@adelphes Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by adelphes** [comment]
The same issue occurs in the same way with the insiders build. No mouse clicks are registered anywhere on the screen once the messagebox is displayed.
Tried with:

Version: 1.25.0-insider
Commit: b4a18da6e78f95295ea6538f5ae8dd0c9f0869a9
Date: 2018-06-19T07:46:56.566Z
Electron: 2.0.2
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by bpasero** [comment]
@adelphes does this happen with any dialogs? how about when you try to close a dirty file and the dialog from there?

**Comment by adelphes** [comment]
@bpasero  I've tried with both the "dirty file confirmation dialog" and the "no update available dialog" - both appear to be fine.
Some things I've noticed:
- if I use the keyboard to highlight and choose the branch (arrow keys + return) - the dialog is responsive to the mouse. Only if I select the branch name with the mouse does it becomes unresponsive when the message box is shown.
- The dropdown which shows the list of branches appears to be triggered on mouse-down - this is different from normal menu and command-palette behaviour which triggers items on mouse-up.

This second one appears to be key - if I tap the left mouse button quickly enough(!), the dialog behaves normally. Basically, I can replicate it by holding down the mouse button (when selecting the branch name) until the dialog appears.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by adelphes** [comment]
There's nothing obvious in the trace
