### ISSUE TITLE
Issues While Open a Folder

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#52113]
Issue Type: <b>Bug</b>

【My Settings】
    "workbench.editor.closeOnFileDelete": false,
    "window.restoreWindows": "none",
    "files.hotExit": "off"
【Steps】
1. Use right click menu "Open with Code" to open a folder which is never opened before.
2. Then the explore of VS Code will appear on the left.
![image](https://user-images.githubusercontent.com/20079289/41502680-92ab7946-718d-11e8-9fd0-ffb92e1e83e8.png)
3. Then close the explorer manually. (Click the button)
![image](https://user-images.githubusercontent.com/20079289/41502692-fefed426-718d-11e8-9d4f-ba07f389cadf.png)
![image](https://user-images.githubusercontent.com/20079289/41502696-26aaab58-718e-11e8-8a84-eef0a3c5ebad.png)
4. Close the window.
5. Use right menu to open the folder again.
![image](https://user-images.githubusercontent.com/20079289/41502705-65cda59c-718e-11e8-9eb0-6f5b479e02a3.png)
The explorer of code will not appear any more unless I press the button again.
It seems that the folder isn't opened.
https://github.com/Microsoft/vscode/issues/38396
Actually, it has been opened, but the explorer didn't display.
6. Close the explorer again, and close the VS Code windows.
7. Rename the folder, and then open it with the right menu.
![image](https://user-images.githubusercontent.com/20079289/41502747-4eb20cb2-718f-11e8-902b-d3f809c5d4ff.png)
The folder is opened, and the explorer display on the left.
8. Repeat the steps if you like...

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:17:41.405Z)
OS version: Windows_NT x64 10.0.17686

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.53GB (3.83GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.24.3

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Do you see anything in the console F1 > developer tools > console
What is the actual issue here, i do not understand

**Comment by byyxx128** [comment]
I mean, if I open a folder I have opened before, nothing will display in the main window.
It won't happen if I open a folder I never opened before.
I can create a gif if needed.

**Comment by bpasero** [comment]
@byyxx128 you closed the sidebar and we just remember that the sidebar is closed when you start again. Closing "as designed".

**Comment by byyxx128** [comment]
While I don't want VS Code to remember what I did before. How can I do?
Is there a option for this?

**Comment by byyxx128** [comment]
@bpasero Well you are right. But I want VSCode not to remember what I did. Maybe it should be a feature request? I need a option to control if VSCode will remember what I did in a folder.
Maybe they are similar. https://github.com/Microsoft/vscode/issues/52086
