### ISSUE TITLE
Strange code folding suggestion for Python file

### ISSUE THREAD

**Issue by SongRb** [Microsoft/vscode#52124]
- VSCode Version: 1.24.1
- OS Version: Windows 10 17134.112 64bit

Steps to Reproduce:

1. Create a file named test.py
2. Type following sample code
![image](https://user-images.githubusercontent.com/15308237/41506166-08f28082-724b-11e8-9e7f-0550a06b9ff9.png)

3. The fold function did not detect end of python function
![image](https://user-images.githubusercontent.com/15308237/41506162-ec315ef0-724a-11e8-95f7-10d0af8128bf.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
What you are seeing is indentation based folding, and you are asking for language aware folding. That has to be provided by a language extension, such as https://github.com/Microsoft/vscode-python.

vscode-python already has https://github.com/Microsoft/vscode-python/issues/1609 for this.
