### ISSUE TITLE
VS Code no longer responding when expand terminal in zoom mode

### ISSUE THREAD

**Issue by dfsbbl** [Microsoft/vscode#52122]
- VSCode Version: 1.24.1
- OS Version: Windows 10 x64
- Device: Surface Book 1st gen (with 200% DPI)

Terminal used: cmd.

Steps to Reproduce:

1. set zoom level to 1 (+20%) by pressing Ctrl + + or change settings;
2. type something like "gcc --help" to generate a number of lines in the integrated terminal;
3. click the upper arrow on the top right corner of integrated terminal to expand the terminal;
4. scroll up and down in the terminal.

Then the window will stuck, and after some time there will be a new dialogue box telling you that the window is no longer responding.

After I set the zoom level to 0, the problem seems to disappear, so I think it might be related to the zoom setting.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by Tyriar** [comment]
Does the problem go away if you add this to your settings?

```ts
"terminal.integrated.rendererType": "dom"
```

**Comment by brcrista** [comment]
Next time I hit the issue I'll try this.  Like I said, I don't have a consistent repro (@dfsbbl steps don't repro for me).

**Comment by dfsbbl** [comment]
@Tyriar It goes away if I add this to my settings ^_^ Thanks for your advice.

**Comment by Tyriar** [comment]
Closing since the workaround fixes it. I'm tracking feedback on this and hope to improve the situation without the setting eventually.
