### ISSUE TITLE
Find all references doesn't work on closed files

### ISSUE THREAD

**Issue by kiyutink** [Microsoft/vscode#52127]
- VSCode Version: 1.24.1
- OS Version: Windows 10

Steps to Reproduce:
1. Use "Find all references" on a declaration while the file with the reference is closed
2. Open the file with the reference
3. Use "Find all references" 

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
* What language/extension are you using?
* What does closed reference mean?

**Comment by kiyutink** [comment]
JavaScript, no extensions. 
I didn't mean closed reference, I meant to say that the reference won't be found, if the file with the reference is closed (not opened in the editor)

**Comment by mjbvz** [comment]
Do you have a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson)?

**Comment by kiyutink** [comment]
hmm, when i add a jsconfig.json it stops finding references even in opened files

**Comment by mjbvz** [comment]
Please share a minimal code example or small example project

**Comment by kiyutink** [comment]
Hey, I've done some checking and found out that it only happens if you search for references of a variable defined in a .jsx file. Unfortunately, I couldn't find how to configure the project to allow VS Code to enable it. To reproduce this you can just create two files as following: 

file1.jsx:
export const a = 3;

file2.jsx:
import {a} from './file1.jsx'

Then if you search for references of 'a' from file1.jsx you'll get different results depending on whether you have or don't have a jsconfig.json. If you don't have it you'll only see the reference of 'a' in file2.jsx if it's opened in the editor. If you have a jsconfig.json, you won't see the reference regardless of the file being opened in the editor or not.

**Comment by mjbvz** [comment]
In your jsconfig.json, make sure you set `"jsx": "react"`  under `compilerOptions`. That should fix the problem
