### ISSUE TITLE
Can't debug Django applications any longer

### ISSUE THREAD

**Issue by asandeep** [Microsoft/vscode#52121]
Issue Type: <b>Bug</b>

Hi Team,
I am no longer able to debug my Django applications in VSCode.  I tried both existing configuration and new experimental configurations and none of them really work.
When I use normal config (given below), django server starts but all breakpoints converts to: 'Unverified breakpoint' and code never stops on the set breakpoints.
```json
{
            "name": "Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "--noreload",
                "--nothreading"
            ],
            "debugOptions": [
                "RedirectOutput",
                "Django"
            ]
        }
```
With experimental config, django server never starts and all i get in console is this message:

> pydev debugger: starting

> pydev debugger: New process is launching (breakpoints won't work in the new process).
> pydev debugger: To debug that process please enable 'Attach to subprocess automatically while debugging?' option in the debugger settings.

Experimental config:
```json
           {
            "name": "Django Experimental",
            "type": "pythonExperimental",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "--noreload",
                "--nothreading",
            ],
            "django": true,
        }
```

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.4.0-128-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2469)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (0.38GB free)|
|Process Argv|/snap/vscode/37/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
material-icon-theme|PKi|3.5.0
code-settings-sync|Sha|2.9.2
Bookmarks|ale|0.19.1
scratchpad|awe|0.1.0
vscode-eslint|dba|1.4.12
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.3.5
auto-rename-tag|for|0.0.15
ginfuru-vscode-jekyll-syntax|gin|0.0.5
node-module-intellisense|lei|1.5.0
terraform|mau|1.1.2
vscode-cosmosdb|ms-|0.7.2
python|ms-|2018.5.0
azure-account|ms-|0.4.0
debugger-for-chrome|msj|4.6.0
color-highlight|nau|2.3.0
quicktype|qui|10.0.24
gi|rub|0.2.11
guides|spy|0.9.2
code-spell-checker|str|1.6.10
vscode-ansible|vsc|0.2.6
JavaScriptSnippets|xab|1.6.0
markdown-all-in-one|yzh|1.4.0

</details>

**Comment by weinand** [comment]
Please file this issue against the Python extension.
