### ISSUE TITLE
Git: ssh_askpass: exec(): No such file or directory

### ISSUE THREAD

**Issue by acabhishek942** [Microsoft/vscode#52137]
- VSCode Version: 1.23.1
- OS Version: Mac OS High Sierra (10.13.5)

Steps to Reproduce:

1. Push using passphrase enabled SSH key using the up arrow mark in bottom right corner

![screen shot 2018-06-18 at 02 18 27](https://user-images.githubusercontent.com/7778186/41511930-0f2a77b8-729e-11e8-85c0-0b8b39ffc5bd.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you push from the command line? Does `/usr/X11R6/bin/ssh-askpass` exist in your system?

**Comment by joaomoreno** [comment]
More details https://github.com/Microsoft/vscode/issues/32097

**Comment by acabhishek942** [comment]
I could push from the command line. Suggestions in #32097 did solve the problem
