### ISSUE TITLE
Inconsistent scrolling using touchpad

### ISSUE THREAD

**Issue by eduardobr** [Microsoft/vscode#52130]
When using my laptop I have always had problems scrolling the file window.
My guess is that the issue is prominent in the 4K screen. I use Windows scaled at 250%.
The machine is a Dell XPS 15 9560. Terminal used: bash
It seems to get worse after some work in the integrated terminal, even after closing it.

How I could reproduce: create a relatively small project, like from a standard Angular 6 template.
Use the terminal in a way that it generates some output and scrolls, for example running a "npm i".
Try to scroll the file window with the terminal open: this is the moment I feel the lag.
It persists until VSCode is restarted.

It seems like there is some offset before the scroll starts (for up or down).

**Comment by Tyriar** [comment]
Is the problem fixed by maximizing/restoring the window?

**Comment by eduardobr** [comment]
Good news.
After checking that the scroll worked perfectly fine from Ubuntu in the same laptop, I decided to change some Windows drivers.
Installing Intel HID Event Filter 2.2.1.364 fixed it for me.
For those getting here due to the same problem: you might not find this driver version in Dell website using your product tag (I didn't).
Download Dell Update 3.0+ from your product Downloads page, then find the latest Intel HID Event Filter from the application.
