### ISSUE TITLE
Crashes at Welcome Page When Trying to Open Integrated Powershell

### ISSUE THREAD

**Issue by HymanZHAN** [Microsoft/vscode#52138]
Issue Type: <b>Bug</b>

When I am at the "Welcome" page, I try to bring up the Powershell with ctrl + `, and cd to a directory. After I enter the command like "cd D:\Development\" and hit enter, the whole window just freezes and crashes. I can still Minimize or move the window, but nothing responds within the window.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (6.17GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.2
better-toml|bun|0.3.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
tslint|eg2|1.0.32
vscode-npm-script|eg2|0.3.4
language-haskell|jus|2.5.0
python|ms-|2018.5.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.83
PowerShell|ms-|1.7.0
vetur|oct|0.12.5
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.0
LiveServer|rit|5.0.0
rust|rus|0.4.5
markdown-preview-enhanced|shd|0.3.5
vscode-autohotkey|sle|0.2.2
haskelly|UCL|0.5.4
vscode-wakatime|Wak|1.2.2
jinja|who|0.0.8
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.4.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
