### ISSUE TITLE
Output windows should have a filter

### ISSUE THREAD

**Issue by dkorbar** [microsoft/vscode#52134]
It would be really helpful if the output window had a filter text box. In big projects that consume a lot of libraries it's not always necessarily easy to control the output and log level of everything. In those cases a filter in the output window can help a lot to reduce the output to only messages a developer is interested in. For a sample, see the output window of XCode.

**Comment by Mawdac** [comment]
+1

I'd also find this helpful - some of the output windows I deal with end up having 2 timestamps because of how they are executed, making every line unnecessarily long. A filter to customize things would solve a lot of pains like this.

**Comment by isidorn** [comment]
fyi @sandy081

**Comment by sirius0xff** [comment]
+1

**Comment by eypsume** [comment]
I have being find the solution for this feature for all day. there are no any extensions.
Also I think even the terminal output for a task needs absolutely it.

**Comment by Mawdac** [comment]
> I have being find the solution for this feature for all day. there are no any extensions.
> Also I think even the terminal output for a task needs absolutely it.

@eypsume , don't forget to upvote the original issue - I personally would also love to see this happen.

**Comment by sirius0xff** [comment]
bump. The one in xcode is very handy
