### ISSUE TITLE
cv2 (opencv-python) intellisense not working

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/vscode#52139]
Hello, I'm opening a new issue as I saw the previous ones have been closed already and I couldn't post there. It looks like the cv2 intellisense suggestions don't work, and VSCode currently marks as errors all the calls to any method/member of the cv2 module. Here's a screen: 

![image](https://user-images.githubusercontent.com/10199417/41512113-f7c12456-7283-11e8-9b20-6ba0bb1eba06.png)

- VSCode Version: 1.24.1 x64
- OS Version: Windows 10 Pro 17134.112 x64

Steps to Reproduce:

1. Install the cv2 package with `pip3 install --upgrade opencv-python`
2. Open VSCode, create a python file, add `import cv2` and try to use any method from that package

Does this issue occur when all extensions are disabled?: No, as I don't get any kind of suggestions this way, and pylint seems to be disabled entirely with this option.

Thanks!

**Comment by RMacfarlane** [comment]
This issue was moved to Microsoft/vscode-python#1993
