### ISSUE TITLE
[cli] add -b, --best-window.

### ISSUE THREAD

**Issue by MarekLew** [microsoft/vscode#52135]
At this point there is an -r parameter but it does not work as described:
`-r, --reuse-window                 Force to open a file or folder in the last active window.`
Works like:
`-b, --best-window                  Force to open a file or folder in the best opened window.`
And there is no way to be sure that the file will open in the current window.

The action repair `-r` is relatively simple  (https://github.com/Microsoft/vscode/issues/51254 I compiled the VSC and check the operation). And to search for the best window worked, propose to add `-b`.

**Comment by RMacfarlane** [comment]
@MarekLew What does "best" opened window mean?

**Comment by MarekLew** [comment]
@RMaclane
> ... 
 we can provide the **best** working environment for a file if it is opened in the context of the folder ...

**Comment by MarekLew** [comment]
https://github.com/MarekLew/vscode/commit/9c5b31ef6c6da3a9045c93d677de40ec5519c6e3
