### ISSUE TITLE
Debugger breaks on caught error thrown from async function (Typescript)

### ISSUE THREAD

**Issue by Wenzil** [Microsoft/vscode#5213]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:
1. Open VS Code
2. Uncheck the `All Exceptions` checkbox in the "Breakpoints" pane of the debugger
3. Check the `Uncaught Exceptions` checkbox in the "Breakpoints" pane of the debugger
4. Copy, compile and run the snippet below
5. Notice how VS Code breaks on the error thrown by `someAsyncFunction` and opens the compiled script, even though the error is caught by Promise.catch().

``` typescript
//index.ts
'use strict';

async function someAsyncFunction() {
  throw new Error('Could not perform this async operation');
}

someAsyncFunction()
  .then(() => {})
  .catch(function(err) {
    process.exit(1);
  });
```

**Comment by egamma** [comment]
@isidorn fyi

**Comment by weinand** [comment]
@Wenzil this is native node.js behaviour. What version of node.js are you using?

**Comment by Wenzil** [comment]
I'm using Node v4.2.3.

Is there any way VS Code can mitigate the issue? It's really annoying that the compiled script is opened. It really disrupts the normal workflow of a user. Especially since the compiled script then shows up in the quick open view despite being listed in the "files.exclude" setting.

**Comment by Wenzil** [comment]
Unchecking the` Uncaught Exceptions` checkbox is not a good option since I do want the debugger to break on actual *uncaught* errors.

**Comment by Wenzil** [comment]
After some more investigation, I realized the issue only occurs when the error is thrown before any `await` statement in the function.

This will work as expected because the error is thrown after the `await` statement:

```typescript
//index.ts
'use strict';

async function someAsyncFunction() {
  await Promise.resolve();
  throw new Error('Could not perform this async operation');
}

someAsyncFunction()
  .then(() => {})
  .catch(function(err) {
    // caught the error without VS Code breaking into the compiled script due to the thrown error
    process.exit(1);
  });

```

Could it be a Typescript compiler optimization gone wrong?

**Comment by Wenzil** [comment]
@weinand Any update on this?

**Comment by weinand** [comment]
@Wenzil as I said this is native node.js behaviour. Working around this would be a new VS Code feature that takes some time to plan and implement (and I'm currently on vacation). What do you see when using node-inspector?

**Comment by Wenzil** [comment]
Will let you know when I get home

**Comment by Wenzil** [comment]
@weinand node-inspector behaves as expected: unchecking "Pause on caught exceptions" causes the debugger to continue its execution without breaking on the thrown error.

**Comment by drew-r** [comment]
@weinand do you know why node-inspector behaves differently to vscode here?

**Comment by tkrotoff** [comment]
I have the same behavior with this code:
```TypeScript
const p = new Promise((resolve, reject) => reject('hello'));
p.catch(error => {
  console.log('catch error', error)
});
```

vscode stops on `new Promise...`

![screen shot 2017-02-01 at 11 42 52](https://cloud.githubusercontent.com/assets/643434/22503785/9b6b09ce-e873-11e6-8b44-8c7da79933c5.png)

**Comment by weinand** [comment]
dup of #1746
