### ISSUE TITLE
Intellisense is taking about 10-15 seconds to show suggestions with large project

### ISSUE THREAD

**Issue by scottmcpherson** [Microsoft/vscode#52141]
I found these existing issues, but they were closed without a solution:
https://github.com/Microsoft/vscode/issues/38409
https://github.com/Microsoft/vscode/issues/42306

- VSCode Version: 1.24.1
- OS Version: macOS 10.13.1

Also tried with VSCode insiders build 1.25.0

Steps to Reproduce:
I think the problem might be related to the size of the project. My folder structure is as follows:
```
top-level/
  clients/
    client-one/
    client-two/
    client-three/
    client-four/
  packages/
    node-module-one/
    node-module-two/
    node-module-three/
```
I'm using lerna to bootstrap it all together (The clients share the common local packages in the packages dir).

Each client is a react application, and was created using `create-react-app`.

Some stats about the project:
```
Files: 358190
Dirs: 30438
Size: 2.5 GB
```

Does this issue occur when all extensions are disabled?: Yes
I tried with all extensions removed and fresh builds of VSCode.

Also, here's a video capturing the delay at about 10-15 seconds:

[screencast 2018-06-17 15-32-30.mp4.zip](https://github.com/Microsoft/vscode/files/2109492/screencast.2018-06-17.15-32-30.mp4.zip)

**Comment by scottmcpherson** [comment]
@RMacfarlane Let me know what I can do to help resolve this! I'm happy to do a screen share or whatever you need

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25057
