### ISSUE TITLE
Crashed in Zen mode, Cannot change editing area back to normal

### ISSUE THREAD

**Issue by HymanZHAN** [Microsoft/vscode#52142]
Issue Type: <b>Bug</b>

I entered Zen mode and try to continue with my work, but the editor just froze up. After a while, there was a prompt asking "Wait", "Reopen" or "Close". I chose "Wait" and after a while, VS Code recovered. However, the editing area is not restored to its original normal appearance but remains width-editable as if in the Zen mode. I can resize the editing area in terms of width but not able to achieve a full screen as the original.

[screenshot1](https://drive.google.com/file/d/1tpvbOIYsY8K19GtqvktCfKGUx4vm7Tp9/view?usp=sharing)

[screenshot2](https://drive.google.com/file/d/1cnncZFaC0MjTt8v1DL4MkAVN50hoXysZ/view?usp=sharing)

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (6.04GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.2
better-toml|bun|0.3.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
tslint|eg2|1.0.32
vscode-npm-script|eg2|0.3.4
language-haskell|jus|2.5.0
python|ms-|2018.5.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.83
PowerShell|ms-|1.7.0
vetur|oct|0.12.5
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.0
LiveServer|rit|5.0.0
rust|rus|0.4.5
markdown-preview-enhanced|shd|0.3.5
vscode-autohotkey|sle|0.2.2
haskelly|UCL|0.5.4
vscode-wakatime|Wak|1.2.2
jinja|who|0.0.8
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.4.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you reproduce just by going into full screen mode (not zen)?

**Comment by HymanZHAN** [comment]
I just tried the Insider and the Zen mode worked just fine. I now remember that the freezing occurred when I tried to toggle the Explorer with ctrl + B. I will try using Insider for a while and see if anything reoccurs down the road.
The thing is I cannot reproduce it with the stable VS Code installation because the problem remains even if I restart the program or reboot the machine. I just cannot get the editing area back to the original status.

**Comment by isidorn** [comment]
Sure, let me know if you can repro with insiders. And if you can please try to find reproducable steps

**Comment by HymanZHAN** [comment]
Sure

**Comment by isidorn** [comment]
Thanks
