### ISSUE TITLE
Can not resolve workspace

### ISSUE THREAD

**Issue by natgonzalezrosa** [Microsoft/vscode#52140]
Issue Type: <b>Bug</b>

Can not resolve workspace folder

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv|/private/var/folders/y3/65fc4r910bzfm25p_y5d4h_w0000gn/T/AppTranslocation/F417E5D9-F95D-4C85-8746-10D542EAF446/d/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_7722845|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
open-in-browser|tec|1.1.0

</details>

**Comment by RMacfarlane** [comment]
Hi @natgonzalezrosa, can you provide more details about what you were doing when you saw this error? Do you consistently see this error?

**Comment by Latupho** [comment]
I hope I do not hijack this, but like a move on it so here I am.
I do have the same issue.

On the workspace I have at them moment, with this issue, i have 2 folders...
Folder one (The first added and org) is located on a UNC path "\\Fileserver01\sccm01install\program1".
The second folder I've added are located on the same server, but in another folder ish. "\\Fileserver01\sccm01install\Program2\Companyname1\Software1\Software_Version\Rev_version"

It's on the second folder I see this !, with the error message.

If I save the workspace manual a second time, and close my code down, and reopen the workspace, the " are gone and no messages...

It's happening to me, on the first folder add, that is not a part of the first folder...

Hope any of this helps?
Please ask, if you need another information, that can be of use?

**Comment by isidorn** [comment]
This is fixed in latest. Please try vscode insiders, or wait for the next update in a couple of days. Thanks
